### ISSUE TITLE
Packer v1.6.3 Bug in Ansible Provisioner - Ansible Galaxy forces use of Collections

### ISSUE THREAD

**Issue by OblateSpheroid** [hashicorp/packer#10008]
There seems to be a bug with the Ansible provisioner introduced by [PR 9903](https://github.com/hashicorp/packer/pull/9903). This new code forces the galaxy command to run twice, once with roles and once with collections. If no collections are provided, I get:
```
Executing Ansible Galaxy
ERROR! Expecting requirements file to be a dict with the key 'collections' that contains a list of collections to install
```
Problem seems to be in [these lines](https://github.com/hashicorp/packer/pull/9903/files#diff-33694ddf5a0e92f3c15762121dc5402fR651-R659).

**Comment by nywilken** [comment]
Hi there - thanks for reaching out. Quickly looking at the source you pointed out I agree that those lines may be the issue. I think if those lines are moved into their respective guard clause the provisioner should work as expected.  

```go
	if p.config.RolesPath != "" {
		roleArgs = append(roleArgs, "-p", filepath.ToSlash(p.config.RolesPath))
	       if roleInstallError := p.invokeGalaxyCommand(roleArgs, ui, comm); roleInstallError != nil {
		 return roleInstallError
               }
	}

         // Similar logic for the CollectionsPath; if set then run the command
        ...
	return nil
```
Would you like to open a PR and get the credit for the commit, or would you prefer a maintainer do it for you?

**Comment by OblateSpheroid** [comment]
Yeah, that sounds good. I'll go ahead and put in the PR.

**Comment by kds-rune** [comment]
In case anyone encounters this before the 1.6.5 release and needs a quick solution, just include both in your requirements-file:
```bash
# requirements.yml
---
collections: []
roles:
  - name: docker
    src: https://github.com/geerlingguy/ansible-role-docker
    version: '2.9.0'
...
```
