### ISSUE TITLE
Support for vSphere Storage DRS

### ISSUE THREAD

**Issue by vheon** [hashicorp/packer#10004]
#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

From the documentation doesn't seems to be possible to have a packer build with the `vsphere-iso` builder specifying a Storage DRS, only a specific Datastore is allowed. I've tried to set the Storage DRS name as the `datastore` property but it fails with:

```
==> vsphere-iso.packer-build-name: error creating vm: datastore 'Storage-DRS-name' not found
```

#### Use Case(s)

Usually using the Storage DRS allows to keep the same configuration even if new datastores are added for more storage.

#### Potential configuration

I'm not sure if new configuration would be required. Packer could first search for Storage DRS and look for a match of the `datastore` property and if found use it otherwise look for a match of single datastores.

#### Potential References

https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.resmgmt.doc/GUID-827DBD6D-08B7-4411-9214-9E126671457F.html

**Comment by nywilken** [comment]
Hi there, thanks for reaching out. This should be possible, but we have to dig in a little further to see what's involved. We'll take a look at this when we get a chance.

**Comment by vheon** [comment]
@nywilken thanks! I've looked briefly to the govnomi package and it seems to handle such use but I'm not familiar with the library and packer enough to know for sure or where I could've tried to make it work. If you have any pointers to that I can always try or if you need more information or tests just let me know 😉

**Comment by jhawk28** [comment]
@vheon this is where packer looks up the datastore: https://github.com/hashicorp/packer/blob/master/builder/vsphere/driver/vm.go#L204

I would recommend using govc to list the datastores that exist. You can also look at what govc is doing to get the datastore to see if there is any difference than what packer is doing.
