### ISSUE TITLE
azure-arm crash on build EOF on create resource group

### ISSUE THREAD

**Issue by braunsonm** [hashicorp/packer#10012]
#### Overview of the Issue

When building a pretty simple image the packer builder crashes when trying to create the resource group. This happens regardless of if I provide a builder resource group or not.

#### Reproduction Steps

```
{
    "variables": {
        "subscription_id": "FILLIN",
        "managed_image_prefix": "packer-",
        "managed_image_resource_group_name": "myRG",
        "ssh_username": "packer",
        "ssh_password": "thisisatest123T%"
    },
    "sensitive-variables": [],
    "builders": [
        {
            "type": "azure-arm",
            "subscription_id": "{{user `subscription_id`}}",
            "ssh_username": "{{user `ssh_username`}}",
            "ssh_password": "{{user `ssh_password`}}",
            "ssh_pty": "true",
            "managed_image_name": "{{user `managed_image_prefix`}}-{{timestamp}}",
            "managed_image_resource_group_name": "{{user `managed_image_resource_group_name`}}",
            "os_type": "Linux",
            "image_publisher": "Canonical",
            "image_offer": "UbuntuServer",
            "image_sku": "18.04-LTS",
            "vm_size": "B2s",
            "location": "canadacentral"
        }
    ],
    "provisioners":[
        {
            "type": "file",
            "source": "./",
            "destination": "/tmp"
        }
        {
            "execute_command": "echo '{{user `ssh_pass`}}' | {{ .Vars }} sudo -S -E sh '{{ .Path }}'",
            "inline": [
               "/usr/sbin/waagent -force -deprovision+user && export HISTSIZE=0 && sync"
            ],
            "inline_shebang": "/bin/sh -x",
            "type": "shell",
            "skip_clean": true
        }
    ]
}
```

Run `packer build packer.json`

### Packer version

Packer v1.6.3

### Operating system and Environment details

Ubuntu 20.04

### Log Fragments and crash.log files

https://gist.github.com/braunsonm/ea2b2f98b08e0eb209c6c0075c8f9c5d

Crash.log:
https://gist.github.com/braunsonm/2128f61d22884ae05e37377443859c7a

**Comment by braunsonm** [comment]
Comes from this line:
https://github.com/hashicorp/packer/blob/master/builder/azure/arm/step_create_resource_group.go#L64

This isn't a pointer apparently.

**Comment by nywilken** [comment]
Hi there thanks for bubbling this up. This issue is related to the change made in #9985. Taking a look now at your PR.

**Comment by nywilken** [comment]
We've merged a patch for this and will do a fast-follow release to fix it soon. Sorry again for any trouble this may have caused.

**Comment by SwampDragons** [comment]
1.6.4 has been released.
