### ISSUE TITLE
lxd / salt masterless: packer is unable to copy states tree correctly: bad directories (/root and / confusion)

### ISSUE THREAD

**Issue by gaetanquentin** [hashicorp/packer#10023]
#### Overview of the Issue
packer salt module can't copy states tree when used with lxd: bad directories

#### Reproduction Steps
PACKER_LOG=1 packer build -on-error=ask -var-file=../../lab/01_common/default-variables.json  lxd-ubuntu-20.04-saltmaster-2020.json

### Packer/salt/lxd  versions
packer >= 1.6.0: currently 1.6.4
salt version: 3001.1
lxd version: 4.6 (snap)

### Simplified Packer Buildfile

variables:
  "salt_local_pillars_dir": "/home/gquentin/Work/repositories/git/automation/Provisionners/SaltStack/pillar",
  "salt_remote_pillars_dir": "/srv/pillar",
  "salt_local_states_dir": "/home/gquentin/Work/repositories/git/automation/Provisionners/SaltStack/states",
  "salt_remote_states_dir": "/srv",
  "salt_temp_config_dir": "/tmp/salt"

other:
{
  "builders": [
    {
      "type": "lxd",
      "name": "ubuntu-20-04",
      "image": "images:ubuntu/20.04",
      "output_image": "ubuntu-20-04",
      "publish_properties": {
        "description": "Ubuntu focal amd64 with saltmaster 3001  built with packer "
      },
       "profile": "default",
      "launch_config": {
       "security.privileged": "false"
      }
    }
  ],

[ ..]

   {
      "type": "salt-masterless",
      "local_state_tree": "{{user `salt_local_states_dir`}}",
      "remote_state_tree": "{{user `salt_remote_states_dir`}}",
      "local_pillar_roots": "{{user `salt_local_pillars_dir`}}",
      "remote_pillar_roots": "{{user `salt_remote_pillars_dir`}}",
      "temp_config_dir": "{{user `salt_temp_config_dir`}}",
      "custom_state": "sys.tools,sys.locale,sys.sysctl,sys.network,apps.configmanager.salt.master,apps.versioncontrol.git",
      "skip_bootstrap": "true",
      "bootstrap_args": "-x python3 stable 3001.1 ",
      "pause_before": "20s"
    },
[ ..]

### Operating system and Environment details
Host: ubuntu 20.04
lxd container image: ubuntu 20.04

### Log Fragments and crash.log files
```
    ubuntu-20-04: Uploading local state tree: /home/gquentin/Work/repositories/git/automation/Provisionners/SaltStack/states
2020/10/01 13:20:45 packer-builder-lxd plugin: lxc file push --debug -pr /home/gquentin/Work/repositories/git/automation/Provisionners/SaltStack/states packer-ubuntu-20-04/states
2020/10/01 13:20:45 packer-builder-lxd plugin: Running cp command: lxc file push --debug -pr /home/gquentin/Work/repositories/git/automation/Provisionners/SaltStack/states packer-ubuntu-20-04/states

=> here you can see packer copying states dir in the root (/) of target container

    ubuntu-20-04: Moving states to /tmp/salt/states
2020/10/01 13:20:47 packer-builder-lxd plugin: Executing with lxc exec in container: packer-ubuntu-20-04 sudo sudo mv 'states' '/tmp/salt/states'
2020/10/01 13:20:47 packer-builder-lxd plugin: Executing lxc exec: /bin/sh []string{"/bin/sh", "-c", "lxc exec packer-ubuntu-20-04 -- /bin/sh -c \"sudo sudo mv 'states' '/tmp/salt/states'\""}
==> ubuntu-20-04: mv: cannot stat 'states': No such file or directory

=> here you can see in "sudo mv states /tmp/salt/states" that packer try to move states from /root/states and not /states  since default lxc exec env is user root in /root

more theses directories are not theses specified in input variables 
```
Regards

**Comment by SwampDragons** [comment]
Hi, thanks for this bug report! This provisioner is one of our community-supported provisioners, which means that the HashiCorp maintainers don't spend much engineering time on it.  This means that the best way to see a fix make it into Packer is to open a PR. We'll gladly give support and pointers if you're interested in taking a shot at it.

**Comment by gaetanquentin** [comment]
ok so give me pointers please, just to try

**Comment by SwampDragons** [comment]
The salt-masterless provisioner code lives here: https://github.com/hashicorp/packer/blob/master/provisioner/salt-masterless/provisioner.go

The code for moving files is here: 

https://github.com/hashicorp/packer/blob/master/provisioner/salt-masterless/provisioner.go#L485-L500

The temporary config dir _should_ be settable by the user here: https://github.com/hashicorp/packer/blob/master/provisioner/salt-masterless/provisioner.go#L56-L57

So you should be able to manually override it there. To get it working nicely for LXC without setting that folder, it may make sense to add a new key to this defaulting map: https://github.com/hashicorp/packer/blob/master/provisioner/salt-masterless/provisioner.go#L98-L115 (or, if the defaults from UnixOSType work, maybe this can be solved by updating the docs. )

Docs for the provisioner live here: https://github.com/hashicorp/packer/blob/master/website/pages/docs/provisioners/salt-masterless.mdx

**Comment by marco-a-itl** [comment]
The problem seems that
`lxc file push --debug -pr /home/gquentin/Work/repositories/git/automation/Provisionners/SaltStack/states packer-ubuntu-20-04/states`
copies to
`/states` inside the container.
While `lxc exec in container: packer-ubuntu-20-04 sudo sudo mv 'states' '/tmp/salt/states'` is executed starting from user home directory, not from `/`.

Seems lxd builder was never tested...

**Comment by nywilken** [comment]
$BODY
