### ISSUE TITLE
vsphere-iso builder: Better support for removing ethernet before export

### ISSUE THREAD

**Issue by johnjelinek** [hashicorp/packer#10029]
## Description

When I use the normal export capabilities from the `vsphere-iso` builder without removing the ethernet card, the ovf expects the network capabilities to be available wherever the vmdk is imported. This results in an error like this (using `govc` in this example).

> govc: Host did not have any virtual network defined.

To mitigate this, we've added some manual overrides to the shutdown process before the export occurs, but it feels very hacky:
```json
{
  "builders": [
    {
      "type": "vsphere-iso",
      "disable_shutdown": true
      ,
    }],
  "provisioners": [
    {
      "expect_disconnect": true,
      "inline": [
        "echo '{{user `user`}}' | sudo -S shutdown -h +1"
      ],
      "only": [
        "vsphere-iso"
      ],
      "type": "shell"
    },
    {
      "command": "govc device.remove -k -u '{{ user `user` }}:{{ user `pass` }}@{{ user `host` }}' -vm '{{ user `template` }}' ethernet-0",
      "only": [
        "vsphere-iso"
      ],
      "type": "shell-local"
  }]
}
```

Another odd nuance is that when using the `"disable_shutdown": true`, the export from `vsphere-iso` spits out a vmdk named like `template_name-disk-0.vmdk` otherwise it's just named `disk-0.vmdk`, not sure why that is.

#### Use Case(s)

The primary use-case I see is being able to ship my exported template to vcenters different from the one the template was generated on.

#### Versions

Packer v1.6.1
govc 0.23.0

**Comment by nywilken** [comment]
Hi there thanks for reaching out and for providing your workaround - that's good context. We will take a look as soon as we get a chance. 

> Another odd nuance is that when using the "disable_shutdown": true, the export from vsphere-iso spits out a vmdk named like template_name-disk-0.vmdk otherwise it's just named disk-0.vmdk, not sure why that is.

This is odd for sure the expected name is template_name-disk-0.vmdk unless a name is specified. Could you please open a new issue for this case with a simplified build template and a redacted copy of the debug logs `PACKER_LOG=1 packer build template.json` so that we can see what might be happening. Thanks!

**Comment by johnjelinek** [comment]
Regarding the nuance, it appears that the vmdk is perhaps created consistently, but the way it is read in via the ovf is different depending on the version of the vcenter. In 6.5.0, it expects the vmdk to be `disk-0.vmdk` and >6.5.0 it expects `template_name-disk-0.vmdk` -- very bizarre. But I'll do some more research before opening a new ticket.

**Comment by johnjelinek** [comment]
@nywilken: any updates on this? I've run into an issue when I'm building an appliance VM from a vendor-supplied ISO. It needs to have NIC during the build, but no NIC right before the export. We're trying to run `local-shell` provisioners to remove the ethernet before the export, but with `"communicator": "none"`, these provisioners aren't running. Any ideas on how to handle this without manual intervention?

**Comment by johnjelinek** [comment]
Also, it might be nice when `"communication": "none"` that when the shutdown timeout occurs, it forces a shutdown, runs any local-shell provisioners, and exports.
