### ISSUE TITLE
Raw output

### ISSUE THREAD

**Issue by wejdross** [hashicorp/packer#10032]
WHAT:
Please add support for raw output (without coloring), it'll be usefull for everyone who uses Packer as subprocess and grabs the output.

It can be flag like `packer build --raw-output (...)` 
WHY:
this is example from reading text stream:  `b'\x1b[0;32m    vsphere-clone:\x1b[0m\n'`
At least add whitespace on the end so, people can grab `log(streamline.split(' ')[1:-1])`. 
Thanks in advance!
wejdross

**Comment by azr** [comment]
Hey @wejdross, thanks for opening; I think the `--machine-readable` option should do just that ! Please tell us if there's anything to improve; I'll close this one in the meantime. 🙂

**Comment by wejdross** [comment]
Thank You very much, You solved my problem.

**Comment by azr** [comment]
Nice ! 🙂
