### ISSUE TITLE
 Packer crashed! This is always indicative of a bug within Packer.

### ISSUE THREAD

**Issue by VedhaPeriTR** [hashicorp/packer#10033]
We are running packer on Jenkins, using a Linux node. Recently, we have been noticing packer crash in 1 out of 4 jobs
Packer version: 1.4.5

![image](https://user-images.githubusercontent.com/58525688/94944945-94576a00-049f-11eb-971f-503a9bbe940c.png)

![image](https://user-images.githubusercontent.com/58525688/94944983-a0dbc280-049f-11eb-8f7b-d06b11522a32.png)

any help would be great

**Comment by SwampDragons** [comment]
Hi there! This is a known bug that was solved in version 1.5.0 in Pr https://github.com/hashicorp/packer/pull/8369

I'd recommend upgrading to the most recent version of packer, v1.6.4, and calling "packer fix" against your packer templates to get any backwards-breaking changes sorted out.
