### ISSUE TITLE
Packer Temp Key/Pair Doesn't Get Deleted Properly

### ISSUE THREAD

**Issue by csamarajeewa** [hashicorp/packer#10038]
#### Overview of the Issue

When building aws amazon-ebs amis packer tmp key is not properly removed. Packer was executed with options build -machine-readable -color=true -force -parallel-builds=2  -only=x

#### Reproduction Steps

The problem seems to only happen on larger amis. I don't have this issue on some smaller amis I create using the same options and type.

### Packer version

Packer v1.4.2

### Simplified Packer Buildfile

  "type": "amazon-ebs",
  "name": REDACTED
  "access_key": REDACTED
  "secret_key": REDACTED
  "token": REDACTED
  "region": REDACTED
  "ami_regions": REDACTED
  "subnet_id": REDACTED
  "source_ami": REDACTED
  "ami_virtualization_type": REDACTED
  "ebs_optimized": REDACTED
  "ena_support": REDACTED
  "ssh_username": REDACTED
  "ami_name": REDACTED
  "ami_description": REDACTED
  "force_delete_snapshot": true
  "force_deregister": true
  "security_group_ids": REDACTED
  "shutdown_behavior": terminate
  "instance_type": REDACTED
  "encrypt_boot": REDACTED

**Comment by azr** [comment]
Hello @csamarajeewa, thanks for opening 🙂 .
What tmp key are you referring to ? Do you have some logs to share too ? I think we probably will need more informations on the buildfile before we can try to repro, this is not so narrow for us ! Thanks !

**Comment by csamarajeewa** [comment]
Hello,  @azr ,

This ticket refers to the temporary public ssh key packer adds to the host on startup for provisioning. My packer.json file is configured as follows. I build few images using this approach and others do not have this same problem. It seems to only happen on larger images I created. Hopefully this is sufficient for you?

{
  "builders": [
    {
      "type": "amazon-ebs",
      "name": "REDACTED",
      "access_key": "REDACTED",
      "secret_key": "REDACTED",
      "token": "REDACTED",
      "region": "REDACTED",
      "ami_regions": "REDACTED",
      "subnet_id": "REDACTED",
      "source_ami": "REDACTED",
      "ami_virtualization_type": "hvm",
      "ebs_optimized": "false",
      "ena_support": "REDACTED",
      "ssh_username": "REDACTED",
      "ami_name": "REDACTED",
      "ami_description": "REDACTED",
      "force_delete_snapshot": "true",
      "force_deregister": "true",
      "security_group_ids": "REDACTED",
      "shutdown_behavior": "terminate",
      "instance_type": "REDACTED",
      "encrypt_boot": "REDACTED",
    }
  ],
  "provisioners": [
    {
        "type": "ansible",
         "extra_arguments": [
           "--extra-vars", "REDACTED",
            "--REDACTED"
          ],
        "playbook_file": "REDACTED",
        "only": ["REDACTED"]
    }
}

**Comment by SwampDragons** [comment]
Are you saying the temporary ssh private key is being left behind in the machine-running-packer's tmp directory, or that the temporary ssh public key is being left behind in the ~/.ssh/authorized_keys file on the built machine? 

If the latter, you can set the flag `https://www.packer.io/docs/builders/amazon/ebs#ssh_clear_authorized_keys` and Packer will remove the key from the authorized_keys file.

**Comment by csamarajeewa** [comment]
Thx!
