### ISSUE TITLE
[debian package] Recommended docker.io dependency causes a conflict on upgrade

### ISSUE THREAD

**Issue by roktas** [hashicorp/packer#10039]
#### Overview of the Issue

On systems with docker-ce installed, recommended docker.io dependency causes a conflict on upgrade.

#### Reproduction Steps

This is somewhat an edge case.  Try installing packer (with recommended packages) on a system with docker-ce (not docker.io) installed.

```
The following packages have unmet dependencies:
 containerd.io : Conflicts: runc
```

### Packer version

`v1.6.4`

### Operating system and Environment details

Debian Sid

```
Distributor ID: Debian
Description:    Debian GNU/Linux bullseye/sid
Release:        unstable
Codename:       sid
```

### (Possible) Solution

`docker-ce` package should be added to the recommended packages as an alternative.  `Recommends` field should be as follows:

```
Recommends: docker.io | docker-ce
```

(Note the `|` operator)

**Comment by azr** [comment]
Hello @roktas, thanks for opening. 
Looking at that page: https://packages.debian.org/sid/packer, docker.io is already in the recommended packages; but I think you would have to install it with the `--without-recommends` option to avoid this error.

**Comment by roktas** [comment]
Hello @azr,

The problem is the lack of `docker-ce` package as an alternative (not the lack of `docker.io`), that's why I've added it with a `|` (OR operator).  Using  the `--without-recommends` option is a "workaround" for an edge case I think.  Note that the [docker.io](https://packages.debian.org/sid/docker.io) package is the official Debian Docker package.  The upstream Docker community edition is another viable alternative as documented [here](https://docs.docker.com/engine/install/debian/).  My suggestion makes life easier for those who prefer `docker-ce` package (instead of `docker.io`).

**Comment by roktas** [comment]
Removing `Recommends` field completely could be another solution.  In its current form, only docker (which is just one of the builder supported by packer) is declared in this field, whereas  there are other builder packages, i.e. virtualbox, qemu.

**Comment by azr** [comment]
Hey @roktas yes we do not maintain that package, we only flag the archlinux package as out of date during releases. I think you will have better help over to the debian side of things. Could you please update us if you have a fix for this though?

**Comment by roktas** [comment]
> Could you please update us if you have a fix for this though?

Sure.  Closing the issue for now.  Thanks!
