### ISSUE TITLE
Azure ARM packer builder ALWAYS configures a public IP on packer VM and does not use provided vnet, subnet and resource group values

### ISSUE THREAD

**Issue by rahulsen** [hashicorp/packer#10046]
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

Details here:
https://discuss.hashicorp.com/t/azure-arm-packer-builder-always-configures-a-public-ip-on-packer-vm-and-does-not-use-provided-values/15033

Even after providing values for the following variables in the Azure packer template

`virtual_network_name`
`virtual_network_subnet_name`
`virtual_network_resource_group_name`

Packer does NOT use these values and instead dynamically creates a resourcegroup, vnet and subnet for the packer VM. This results in assignment of a public IP on packer VMs which is undesirable.

`private_virtual_network_with_public_ip`- is **NOT** set

A paragraph or two about the issue you're experiencing.

Steps to reproduce this issue

Set the three values provided in the forum posting and see if the ephemeral pkrvm is created using those values OR results in ephemeral vnet, subnet, resource group etc

1.5.4 and 1.6.4 - both exhibit this problem

### Simplified Packer Buildfile

```
{
    "builders": [
	{
		"type": "azure-arm",
		"subscription_id": "{{user `source_gallery_subscription_id`}}",
		"client_id": "{{user `azure_client_id`}}",
		"client_secret": "{{user `azure_client_secret`}}",

		"shared_image_gallery": {
			"subscription": "{{user `source_gallery_subscription_id`}}",
			"resource_group": "{{user `source_gallery_resource_group`}}",
			"gallery_name": "{{user `source_gallery_name`}}",
			"image_name": "{{user `source_image_name`}}",
			"image_version": "{{user `source_image_version`}}"
		},
	    "managed_image_name": "{{user `managed_image_name`}}-{{isotime \"2006-01-02\"}}_{{isotime \"150405MST\"}}",
	    "managed_image_resource_group_name": "{{user `managed_image_resource_group_name`}}",
		"managed_image_storage_account_type": "Premium_LRS",
		"shared_image_gallery_destination": {
			"resource_group": "{{user `destination_gallery_resource_group`}}",
			"gallery_name": "{{user `destination_gallery_name`}}",
			"image_name": "{{user `destination_image_name`}}",
			"image_version": "{{user `destination_image_version`}}",
			"replication_regions": "{{user `destination_replication_regions`}}"
		},

	    "vm_size": "{{user `vm_size`}}",
	    "ssh_username": "{{user `packer_ssh_username`}}",
	    "os_type": "{{user `os_type`}}",
		"os_disk_size_gb": "{{user `os_disk_size_gb`}}",
		"location": "{{user `azure_location`}}",
		"virtual_network_name": "my-existing-vnet",
		"virtual_network_subnet_name": "my-existing-private-subnet-0",
		"virtual_network_resource_group_name": "my-existing-resgrp"
		
	}
    ],
	"_comment": "This is a comment",

	"provisioners": [],

	"post-processors": [
		{
			"type": "shell-local",
			"inline": ["echo test_command_can_be_used_to_execute_in_post_process"]
		},
		{
			"type": "manifest",
			"output": "manifest.json",
			"strip_path": true,
			"custom_data": {
				"pattern": "packerbuild"
			}
		}

	]
}
```

**Comment by nywilken** [comment]
Thanks for reaching out here and for liking to the discuss thread. We will take a look soon to see what might be going on.

**Comment by SwampDragons** [comment]
Hi there, thanks for reaching out. 

I can't reproduce this; if I provide the name of an existing virtual network, Packer is logging that it will use a private endpoint

```
==> azure-arm:  -> Network Connection  : 'PrivateEndpoint'
```

and later connects to a private IP address:

```
==> azure-arm:  -> IP Address          : '10.1.1.4'
```

Can you provide logs from your build to help us debug this?

**Comment by SwampDragons** [comment]
ok, so I did find that if I don't set the build_resource_group_name, then it creates a transient resource group. Try setting that value and let me know if that solves your issue.

**Comment by rahulsen** [comment]
I did set the "virtual_network_resource_group_name" . That is the resource group containing the VNET. See in my sample packer json file above. Is that what you mean by "build_resource_group_name" or is that a different resource group ?

**Comment by nywilken** [comment]
> I did set the "virtual_network_resource_group_name" . That is the resource group containing the VNET. See in my sample packer json file above. Is that what you mean by "build_resource_group_name" or is that a different resource group ?

Hi @rahulsen just following up on @SwampDragons comment. The `"build_resource_group_name"` configuration option is a different option. When set it tells Azure to use an existing resource group for the build; otherwise it will create a transient resource group for the build. 

Given your example configuration you would set `"build_resource_group_name"` to the same value as `"virtual_network_resource_group"`. 

```json
"build_resource_group_name": "my-existing-resgrp",
"virtual_network_name": "my-existing-vnet",
"virtual_network_subnet_name": "my-existing-private-subnet-0",
"virtual_network_resource_group_name": "my-existing-resgrp"
```

**Comment by rahulsen** [comment]
This seems to work. You can close the ticket.

> > I did set the "virtual_network_resource_group_name" . That is the resource group containing the VNET. See in my sample packer json file above. Is that what you mean by "build_resource_group_name" or is that a different resource group ?
> 
> Hi @rahulsen just following up on @SwampDragons comment. The `"build_resource_group_name"` configuration option is a different option. When set it tells Azure to use an existing resource group for the build; otherwise it will create a transient resource group for the build.
> 
> Given your example configuration you would set `"build_resource_group_name"` to the same value as `"virtual_network_resource_group"`.
> 
> ```json
> "build_resource_group_name": "my-existing-resgrp",
> "virtual_network_name": "my-existing-vnet",
> "virtual_network_subnet_name": "my-existing-private-subnet-0",
> "virtual_network_resource_group_name": "my-existing-resgrp"
> ```

This seems to work. You can close the issue.

**Comment by nywilken** [comment]
@rahulsen glad we were able to get this all squared away. Thanks for letting us know. 

Feel free to reach out if you run into any other issue.

**Comment by kanivetsi** [comment]
HI @nywilken!
I'm facing the same issue. I've already specified all required fields in the Packer template:
   "build_resource_group_name": "my_resource_group",
    "virtual_network_name" : "my_vn_name",
    "virtual_network_resource_group_name": "my_resource_group",
    "virtual_network_subnet_name": "SubnetName"
If I don't specify private_virtual_network_with_public_ip: true, I have an error "Timeout waiting for SSH."
I've already tried the latest Packer 1.6.5 version available for download, but the issue still exist.

Could you please advise steps for solving this error?
Regards,
Ihor
