### ISSUE TITLE
Packer 1.6.0 with Shell//Docker

### ISSUE THREAD

**Issue by andycockers** [hashicorp/packer#10043]
#### Overview of the Issue

When creating a Docker image using Packer and Shell, the resulting image is corrupted. If I use packer 1.3.5 then it works correctly.
#### Reproduction Steps

Steps to reproduce this issue

### Packer version

1.6.0

### Simplified Packer Buildfile

```
{
    "builders": [
        {
            "type": "docker",
            "image": "frolvlad/alpine-bash",
            "commit": true
        }
    ],

    "provisioners": [
        {
            "type": "shell",
            "scripts": "../../shell/install-python3/install.sh"
        }
    ],

    "post-processors": [
        [
        {
            "type": "docker-tag",
            "repository": "calmmopey/alpine-python3",
            "tag": "latest"
        },

        {
            "type": "docker-push",
            "login": false
        }
    ]
]
}
```

### Operating system and Environment details

OS: Ubuntu Linux 20.04

The shell script to install python3:

```
#!/bin/bash

apk update

apk add python3
```

### Log Fragments and crash.log files
```
Any attempt to run the built container results in:

/bin/sh: line 1: ELF: not found
/bin/sh: line 2: �: not found
/bin/sh: line 3: �: not found
/bin/sh: /bin/sh: /bin/sh: line 1: line 1: �e�mgUa: not foundM�Z��!9!di9WۓŹ�@ĉ�9�����o�!���7e�
                                                                                              �ݣk��: not found

line 1: ��: not found
/bin/sh: line 1: �n�镳�: not found
/bin/sh: line 4: �: not found
/bin/sh: line 14: �xN@��
                        �G: not found
/bin/sh: line 15: ��/yg�: not found
/bin/sh: line 16: ����
                      �gT��: not found
/bin/sh: line 17: T�: not found
/bin/sh: line 18: �: not found
/bin/sh: line 19: 
                  �e�: not found
/bin/sh: line 20: h: not found
/bin/sh: line 21: �1�: not found
/bin/sh: line 22: �4: not found
/bin/sh: line 23: ��{: not found
/bin/sh: line 24: Z��: not found
/bin/sh: line 25: �: not found
/bin/sh: line 26: ?: not found
/bin/sh: line 9: syntax error: unterminated quoted string
```

**Comment by nywilken** [comment]
Hi @andycockers thanks for reaching out. I'm not able to reproduce but it is possible that I might be doing something different on my end. Can you please add the Packer debug log `PACKER_LOG=1 packer build template.json` and the command that you are using when trying to run the built container, please. 

Heads up I updated the body of the issue to format the template and logs.

**Comment by andycockers** [comment]
Hi @nywilken thank you for your prompt reply.

The console output with debug is attached.
[build-log.txt](https://github.com/hashicorp/packer/files/5328450/build-log.txt)

The command that's being run via a shell script is:

#!/bin/bash

apk update

apk add python3

**Comment by andycockers** [comment]
Sorry, you also wanted the command I'm running on the built container:

docker run -it 7e6d46784468 /bin/sh

**Comment by SwampDragons** [comment]
I believe in that intervening time Packer switched the entrypoint in the default run_command from bash to sh. Take a look in the docker docs for the way "ENTRYPOINT" is configurable bow.  https://www.packer.io/docs/builders/docker

See https://github.com/hashicorp/packer/pull/7069 for more details on specifically what changed. To return to the old behavior, set 

```
"run_command": ["-d", "-i", "-t", "{{.Image}}", "/bin/bash"]
```

in your packer template. 

This command is documented here: https://www.packer.io/docs/builders/docker#run_command

**Comment by andycockers** [comment]
Hi @SwampDragons 

Thank you for your reply. I will try that and report back.

**Comment by andycockers** [comment]
Hi @SwampDragons @nywilken 

Adding "run_command": ["-d", "-i", "-t", "{{.Image}}", "/bin/bash"] to the builder has resolved the issue.

Thank you for your help.
