### ISSUE TITLE
vsphere-clone - Customize requires Linux Customization Settings

### ISSUE THREAD

**Issue by FF186** [hashicorp/packer#10041]
Hi, 

I'm wondering why the `customize` options for `vsphere-clone`  requires the `linux_options:` or else it says that `customize is empty`? 
I want the ability to only add `network_interface`.

```
WORKS
 "customize": {
          "linux_options": {
            "host_name": "packer-test",
            "domain": "test.internal"
          },
          "network_interface": {
            "ipv4_address": "10.0.0.10",
            "ipv4_netmask": "24"
          }
 }
```

```
DOES NOT WORK
 "customize": {
          "network_interface": {
            "ipv4_address": "10.0.0.10",
            "ipv4_netmask": "24"
          }
 }
```

**Comment by azr** [comment]
Hello @FF186 good question ! I think @sylviamoss will answer that better than me, but I'll try here:
Reading the vsphere [docs](https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.vm_admin.doc/GUID-58E346FF-83AE-42B8-BE58-253641D257BC.html):
> Customizing guest operating systems helps prevent conflicts that occur if virtual machines with identical settings are deployed, for example conflicts due to duplicate computer names. You can apply customization as part of virtual machine deployment or later.

So, I think we made the assumption that you always want to avoid a conflict here with Packer and rename things to avoid conflicts with vsphere-clone. But looking at the code & docs this could be made optional; with all that said is that something you would like to have ?
