### ISSUE TITLE
Documentation on Azure Shared Image Gallery with a different subscription id [GH-9875]

### ISSUE THREAD

**Issue by adin3d** [hashicorp/packer#10047]
First, thank you for a very useful feature :)

In regards to Support publishing to a Shared Image Gallery with a different subscription id [GH-9875], is there any documentation or examples on how to use it?

Thank you 🥇

**Comment by azr** [comment]
Hello @adin3d 🙂  ! The example is in the docs over there: https://www.packer.io/docs/builders/azure/arm#shared_image_gallery_destination is that enough for you to get going ?

**Comment by adin3d** [comment]
yes, it seems so :) I am using a devops pipeline and the service connection is made at a subscription scope level, I wonder if that will cause any issues but I will test and get back to you. 

Thank you for your help.

**Comment by nywilken** [comment]
Hi @adin3d it looks like the current documentation is enough so I'm going to close this issue. If, however, you find that you need more help or if you think the documentation can be improved leave a comment on this thread and we will gladly reopen. Thanks!
