### ISSUE TITLE
ami image failed with error

### ISSUE THREAD

**Issue by bhanudevops01** [hashicorp/packer#10055]
[root@chef myfolder]# ./packer build -var 'aws_access_key=XXXXXXXXX' -var 'aws_secret_key=XXXXXXX' example.json
amazon-ebs: output will be in this color.

Build 'amazon-ebs' errored after 330 milliseconds 844 microseconds: error validating regions: RequestError: send request failed
caused by: Post "https://ec2.us-east-1.amazonaws.com/": dial tcp: lookup ec2.us-east-1.amazonaws.com on [::1]:53: read udp [::1]:47368->[::1]:53: read: connection refused

**Comment by nywilken** [comment]
Thanks for opening an issue -- to help you, we really do need the things requested in the issue template: 

- Packer version from `packer version`
- Host platform
- Full debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a gist https://gist.github.com
- The _simplest complete example template and scripts_ needed to reproduce the bug.
  Include these in your gist https://gist.github.com

Thanks!

**Comment by bhanudevops01** [comment]
Thanks for the update. I was able to fix the issue.

**Comment by nywilken** [comment]
Great, I'm going to close this issue then. Feel free to open a new issue if your run into any new problems. Cheers!
