### ISSUE TITLE
Regression in Openstack source with Packer 1.6.3

### ISSUE THREAD

**Issue by asiragusa** [hashicorp/packer#10060]
#### Overview of the Issue

`packer build` fails complaining of multiple source images, when using a `source_image_filter` with `most_recent = true`

#### Reproduction Steps

Define a source like the following
```hcl
source "openstack" "ovh" {
  source_image_filter {
    filters {
      name = "image_name"
    }

    most_recent = true
  }
}
```

`packer build .`

### Packer version

From `1.6.3`

### Operating system and Environment details

Tested on Linux and OSX

### Log Fragments and crash.log files
```
Error: 1 error(s) occurred:

* Only a source_image, a source_image_name or an external_source_image_url can be specified, not multiple.

  on source.pkr.hcl line 1:
  (source code not available)



==> Wait completed after 3 microseconds

==> Builds finished but no artifacts were created.
```

**Comment by SwampDragons** [comment]
Hi, sorry about this! I've opened a PR over at #10065 that'll fix this. You're welcome to pull a build from the store_artifacts link on that PR to test it out, or you can take my word for it. I'll be fixed for the next release.

**Comment by asiragusa** [comment]
Thank you for fixing this so fast!
