### ISSUE TITLE
Packer -var-file cannot parse json with arrays in it

### ISSUE THREAD

**Issue by pwillis-els** [hashicorp/packer#10089]
#### Overview of the Issue

When passing any json file to packer with `-var-json`, if the JSON has arrays anywhere in it, Packer cannot parse it.

As you will see from the below example, it does not matter if Packer using the variables at all, Packer will just die if there are any arrays in the JSON at all.

##### `packer.json`
```json
{
    "variables": {
        "foo":      "{{env `foo`}}"
    },

    "builders": [ {
        "region":                  "{{user `region`}}",

        "ssh_username":            "ec2-user",
        "type":                    "amazon-ebs",
        "ebs_optimized":           true,
        "instance_type":           "t3.medium",
        "source_ami": "blah",

        "ami_name":                "blah",
        "ami_virtualization_type": "hvm",

        "tags": {
            "Foo":         "{{user `foo`}}"
        }
    } ]
}
```
##### `foo1.json`
```json
{
  "foo": "bar"
}
```
##### `foo2.json`
```json
{
  "foo": "bar",
  "bar": [
    {
        "blah": "egh"
    }
  ]
}
```

##### Running Packer on `foo1.json`
```bash
$ packer build -var-file foo1.json packer.json
amazon-ebs: output will be in this color.

Build 'amazon-ebs' errored after 325 milliseconds 380 microseconds: no valid credential sources for  found.

Please see
for more information about providing credentials.

Error: NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors


==> Wait completed after 325 milliseconds 431 microseconds

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: no valid credential sources for  found.

Please see
for more information about providing credentials.

Error: NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors


==> Builds finished but no artifacts were created.
```

##### Running Packer on `foo2.json`
```bash
$ packer build -var-file foo2.json packer.json
Error reading variables in 'foo2.json': json: cannot unmarshal array into Go value of type string
```

### Packer version
Packer v1.6.4

### Operating system and Environment details

Ubuntu 18.04.5 LTS (Bionic Beaver)
Chef Bento box for Vagrant (x86_64)

**Comment by nywilken** [comment]
Hello there @pwillis-els thanks for reaching out. This is actually correct. Packer is expecting tags to be a map of strings 
```
"tags": {
 "foo": "bar",
 "bar": "foobar"
}
```

If you can give us an indication of what you are trying to achieve we might be able to help in finding an alternative.

**Comment by pwillis-els** [comment]
I know that Packer may not allow passing arrays as variables, but the use case I have for this is a single JSON document which contains all the variables I need to run my many Infrastructure as Code projects.

I pass this JSON doc to Terraform with `-var-file`, and Terraform will pick out the variables it needs from the JSON and continue operating normally. But passing this same JSON doc to Packer results in dying due to there being arrays in it (I pass objects with arrays to fill in Terraform variables).

So, if this doesn't work, I'll need to either duplicate my configs, or modify my code to pass individual variables with `-var`, both of which are not great options. If Packer `-var-file` could at least just ignore the unused variables, that would be great.

**Comment by pwillis-els** [comment]
It may not be obvious from the above, but "bar", the array in `foo2.json`, is never used in `packer.json`. It's just sitting in there unused, but it still causes Packer to die

**Comment by nywilken** [comment]
Hi @pwillis-els thanks for the extra context. Packer JSON mode builds will not support this use case for sure. But you will be happy to know that HCL2 enabled Packer builds support variable files with complex types like the one you are describing. 

Variables files for HCL2, which are still defined as JSON, use the HCL parser in Packer and have greater flexibility in handling variables of various types. It will also warn users when there are unused variables, but it will not fail the build like its JSON counterpart. 

With that said, you should be able to pass your variables.json file along with a HCL2 enabled template to `packer build -var-file=variables.json ...` to get the results you are looking for.

I do want to mention that if the variables file is being generated after running `terraform apply` you will mostly likely need to use Jq to manipulate variables or duplicate the variables slightly to ensure that Packer and Terraform can read any shared variables. 

I wrote an example template and variables file to illustrate how HCL2 handles unused variables and arrays. 

template.pkr.hcl
```
variable "commands" {
    type = list(string)
}
source "null" "example" {
    communicator = "none"
}

build {
    sources = ["source.null.example"]

    provisioner "shell-local" {
        inline = var.commands
    }
}
```
variables.json
```json
{
    "commands": ["echo hell0", "uname -a"],
    "bar": [
        {
            "foo": "bar"
        }
    ]
}
```

Build output
```
packer build "-var-file=/mnt/variables.json" /mnt/null-source.pkr.hcl
Warning: Undefined variable

A "bar" variable was set but was not found in known variables. To declare
variable "bar", place this block in one of your .pkr files, such as
variables.pkr.hcl

null.example: output will be in this color.

==> null.example: Running local shell script: /tmp/packer-shell407506431
    null.example: hell0
    null.example: Linux 010f8bc40542 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 Linux
Build 'null.example' finished after 17 milliseconds 535 microseconds.

==> Wait completed after 17 milliseconds 621 microseconds

==> Builds finished. The artifacts of successful builds are:
--> null.example: Did not export anything. This is the null builder
```

Please let me know if migrating to HCL2 helps with your use case.

**Comment by pwillis-els** [comment]
I was able to use my json doc in the way I expected after I converted to HCL2, so this will work for me. Thanks

**Comment by SwampDragons** [comment]
That's great to hear; thanks for updating us!
