### ISSUE TITLE
amazon-ebs: fine-grained IAM policy

### ISSUE THREAD

**Issue by JIoJIaJIu** [hashicorp/packer#10092]
#### Description
I would like to be able to create a custom IAM policy that grants access to the Packer, and only to the resources created by Packer. AWS uses conditions base on `aws:RequestTag` and `aws:ResourceTag` for that purpose, but unfortunately for most of the controlled resources Packer doesn't setup the tags. It leads that CI/CD user has wide permissions - ability to remove/change resources it shouldn't. At this moment I found the only way to limit access by using separated aws region for the Packer

Similar issues: #9894 

#### Use Case(s) / Potential configuration
So would be great:
1. <details><summary>:pencil2: Apply tag `Managed by: Hashicor Packer` to the all existed resources that support it</summary>

    It will allow writing policy as
    ```hcl
    ...
    statement {
      actions = [
        "ec2:CreateSecurityGroup",
      ]
      resources = ["*"]
      condition {
        test  = "StringEquals"
        variable = "aws:RequestTag/Managed by"
        values = [
          "Hashicorp Packer"
        ]
      }
    }

    statement {
      actions = [
        "ec2:AuthorizeSecurityGroupIngress",
        "ec2:DeleteSecurityGroup",
      ]
      resources = ["*"]
      condition {
        test  = "StringEquals"
        variable = "aws:ResourceTag/Managed by"
        values = [
          "Hashicorp Packer"
        ]
      }
    }
    ...
    ```
    
    For actions that supports resources it's possible to point like
    ```hcl
    statement {
        actions = [
          "ec2:CreateKeyPair",
          "ec2:DeleteKeyPair",
        ]
 
        resources = ["arn:aws:ec2:*:${var.aws_account}:key-pair/packer_*"]
     }
    ```
    but 
    1. it's not supported by most of the actions
    2. using tags will make policy simpler and more uniform 
    </details>
2. <details><summary>:bell: Add base tag during creation with TagSpecification for the resources</summary>

    ```go
    runOpts := &ec2.RunInstancesInput{
      ImageId:             &s.SourceAMI,
      ...
      TagSpecifications: []*ec2.TagSpecification{
        {
          ResourceType: aws.String("instance"),
          Tags: []*ec2.Tag{
            {
              Key: aws.String("Managed by"),
              Value: aws.String("Hashicorp Packer"),
            },
          },
        },
        ...
      },
    }
    ```
    to be able to create policy
    ```json
    {
      "Effect": "Allow",
      "Action": [
        "ec2:RunInstances"
      ],
      "Resource": [
        "arn:aws:ec2:*:${var.aws_account}:instance/*"
      ],
      "Condition": {
        "StringEquals": {
          "aws:RequestTag/Managed by": "Hashicorp Packer"
        }
      }
     ```
     rather than apply it after on the created instance, cause it requires the policy that allows to add any tag
    </details>
3. <details><summary>:closed_book: Update minimal IAM policy in the doc</summary>

    It would be great if IAM policy [is provided in docs](https://www.packer.io/docs/builders/amazon#iam-task-or-instance-role) contains these conditions.
    </details>

#### Potential References
* https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazonec2.html
* https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/control-access-with-tags.html
* https://aws.amazon.com/blogs/security/simplify-granting-access-to-your-aws-resources-by-using-tags-on-aws-iam-users-and-roles/

**Comment by nywilken** [comment]
Hi there, thanks for reaching out. This sounds like a great idea. I am unsure if we will have time to work on this any time soon but it sounds like it would be really nice to have. As usual PRs are welcomed :smile: !
