### ISSUE TITLE
Can't thick provision a virtual machine disk, even when specifying "disk_thin_provisioned": true

### ISSUE THREAD

**Issue by CollinLeishman** [hashicorp/packer#10098]
#### Overview of the Issue
Even when specifying "disk_thin_provisioned": true in an ubuntu json file, packer will build the template in vsphere using thin provisioning for the disk.

#### Reproduction Steps

Create a Packer json file with type 'vsphere-iso'
for storage:
 ```
     "storage": [
        {
          "disk_size": "{{user `vm-disk-size`}}",    # specified size 10240 in variables.json file
          "disk_thin_provisioned": false                  # or don't set it at all, as it should default to thick.
        }
      ],
```
Run a packer build
Watch build in vsphere. When VM/template is being provisioned, click on the disk and see 'Thin Provision'.

### Packer version

1.6.4

### Operating system and Environment details

debian 10 amd64

I believe this is a similar issue:
https://github.com/jetbrains-infra/packer-builder-vsphere/issues/128

I am happy to provide more details if needed.

**Comment by nywilken** [comment]
Thanks for reaching out. We’ll take a look when we get a chance.

**Comment by CollinLeishman** [comment]
So this packer build is intended to build a vmware template, and terraform is intended to provision a vm from that template. When I try to provision the VM from the template(from terraform, where thick provisioning is also specified), it throws this error:

```
Error: error reconfiguring virtual machine: error processing disk changes post-clone: disk.0: ServerFaultCode: NoPermission: RESOURCE (vm-291530:2000), ACTION (queryAssociatedProfile): RESOURCE (vm-291530), ACTION (PolicyIDByVirtualDisk)
```

Hope this at least helps!

**Comment by CollinLeishman** [comment]
Has anybody else encountered this or something similar? If anybody knows a workaround or maybe any issues on the vsphere side, I would love to hear it.

**Comment by CollinLeishman** [comment]
This was a storage provider issue. For anyone else who may encounter this, test with several datastores.
