### ISSUE TITLE
Google Compute Engine cannot start from custom-image created by Packer version 1.6.4

### ISSUE THREAD

**Issue by j-flat** [hashicorp/packer#10100]
We have an issue on our Google project, where we are attempting to use Packer baked custom-image to spin up Google Compute Engine instances and the instance doesn't go beyond very first seconds of UEFI boot.  

Nothing on Packer logs (with PACKER_LOG set to 1) states that something has gone wrong with the provisioning or other parts of Packer process, but on Google end there are also no issues. 

If new instance is created from this custom-image, UEFI boot doesn't go beyond this point, if monitored on Serial Port 1 logs:
```
UEFI: Attempting to start image.
Description: UEFI Google PersistentDisk
FilePath: PciRoot(0x0)/Pci(0x3,0x0)/Scsi(0x1,0x0)
OptionNumber: 1.
[1m[37m[40m[01;01H[2J[01;01H2020/10/09 10:41:37 GCEGuestAgent: GCE Agent Started (version 20200813.01)
2020-10-09T10:44:00.5273Z OSConfigAgent Info: OSConfig Agent (version 20200901.01) started.
```

We are using public image from Windows 2019 Server family and this has been tested with both Packer v1.6.2 and Packer v1.6.4 for Windows 64bit Packer.

What Packer is doing on provisioning state is:
- installs & pre-configures IIS on the instance
- downloads Stackdriver Logging and Monitoring Agents
- installs MS Web Deploy 3.6. in order to later deploy .NET Web Application on the instances created from this custom image
- generalizes the image running gcesysprep at the end of the Packer process

We are attempting to generate these custom-images with both Packer v1.6.2 & newer Packer v1.6.4

What I can see is that Packer creates the temporary instance successfully and Google Compute Engine instance details page states that the source-disk should not be deleted when this temporary instance is deleted. However at the end of the Packer process when Packer deletes the temporary instance, also the source disk associated with the custom image gets deleted.

I add here Azure DevOps pipeline yaml configuration, packer.json as well as Azure DevOps logs from packer process to help to further describe how the process is now setup.

[Packer Support.zip](https://github.com/hashicorp/packer/files/5378459/Packer.Support.zip)

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out. 

> What I can see is that Packer creates the temporary instance successfully and Google Compute Engine instance details page states that the source-disk should not be deleted when this temporary instance is deleted. However at the end of the Packer process when Packer deletes the temporary instance, also the source disk associated with the custom image gets deleted.

I suspect this is a false alarm. The gcp builder does delete the entire source instance and associated source disk, but only after creating a new standalone image based on that one. It hasn't changed in like 5 years, so I doubt that's the source of your issue. 

I'll try to investigate this in more detail when I get a chance but my gut instinct is that this is a Windows provisioning/configuration issue rather than something wrong with Packer.

**Comment by j-flat** [comment]
Thank you for taking the time to check this out, we have opened a Google Support ticket as well, since I was doubting the is issue caused by Packer.
