### ISSUE TITLE
Feature root_volume_size on azure-chroot

### ISSUE THREAD

**Issue by reginaldomoura** [hashicorp/packer#10123]
Hello Everyone,

We have a project running on Azure Cloud and one of the applications used by our team is Packer, but from know we decided to improve the time consume inside of our pipeline, an good aprouch is use azure-chroot.

So now we have an issue and may this is solved before, on aws-chroot we use root_volume_size to define the sizing of root volume, in the case of azure-chroot we don't see any flag equal to these one. At Hashicorp Packer have we any solution for that? We build a linux from scratch, but this increase some complexity for our developers.

**Comment by azr** [comment]
Hello @reginaldomoura, thanks for opening, could the [`os_disk_size_gb`](https://www.packer.io/docs/builders/azure/chroot#os_disk_size_gb) option solve this ?

**Comment by reginaldomoura** [comment]
Hi @azr,

In this case no, because the os_disk_size_gb only impact in the image, and I need to change the root path size, because in a default image this size is only 2GB, when install packages I receive disk full error.

Thanks,
Reginaldo Junior

**Comment by azr** [comment]
ah got it @reginaldomoura thanks for trying, @paulmey should answer way better than me then. In the meantime I'll read the docs.
