### ISSUE TITLE
vshpere-clone: Adding customization to builder prevents network adapter from connecting

### ISSUE THREAD

**Issue by egkelly** [hashicorp/packer#10120]
#### Overview of the Issue

When trying to create a packer template from an existing clone with Linux customizations, the builder hangs forever waiting the IP. Please note the network_interface customization is specifically configured to use DHCP. When I check the console, it times out on waiting for the IP adapter to become available. This behavior does not happen when I remove the customizations.

#### Reproduction Steps

Run packer build on a vsphere-clone builder that includes customizations.

### Packer version

1.6.4

### Simplified Packer Buildfile

**NOT WORKING**
```
{
    "builders": [
      {
        "type":                 "vsphere-clone",
  
        "vcenter_server":       "{{ user `vcenter-server` }}",
        "username":             "{{ user `vcenter-username` }}",
        "password":             "{{ user `vcenter-password` }}",
        "insecure_connection":  "true",
  
        "template":             "{{ user `template-name` }}",
        "vm_name":              "{{ user `vm-name` }}",
        
        "datastore":            "{{user `datastore`}}",
        "folder":               "{{user `folder`}}",
        "cluster":              "{{user `cluster`}}",
        "resource_pool":        "{{user `resource_pool`}}",
        "network":              "{{user `network`}}",
  
        "communicator":         "ssh",
        "ssh_username":         "{{user `ssh-username`}}",
        "ssh_password":         "{{user `ssh-password`}}",

        "customize": {
          "linux_options": {
            "host_name":        "{{user `hostname`}}",
            "domain":           "{{user `domain`}}"
          },
          "network_interface": {
            "ipv4_address": ""
          }
        },

        "convert_to_template":  "true"
      }
    ]
  }
```

**WORKING**
```
{
    "builders": [
      {
        "type":                 "vsphere-clone",
  
        "vcenter_server":       "{{ user `vcenter-server` }}",
        "username":             "{{ user `vcenter-username` }}",
        "password":             "{{ user `vcenter-password` }}",
        "insecure_connection":  "true",
  
        "template":             "{{ user `template-name` }}",
        "vm_name":              "{{ user `vm-name` }}",
        
        "datastore":            "{{user `datastore`}}",
        "folder":               "{{user `folder`}}",
        "cluster":              "{{user `cluster`}}",
        "resource_pool":        "{{user `resource_pool`}}",
        "network":              "{{user `network`}}",
  
        "communicator":         "ssh",
        "ssh_username":         "{{user `ssh-username`}}",
        "ssh_password":         "{{user `ssh-password`}}",

        "convert_to_template":  "true"
      }
    ]
  }
```

### Operating system and Environment details

Ubuntu 20.04 WSL

### Log Fragments and crash.log files

```vsphere-clone: output will be in this color.

==> vsphere-clone: Cloning VM...
==> vsphere-clone: Mounting ISO images...
==> vsphere-clone: Adding configuration parameters...
==> vsphere-clone: Customizing VM...
==> vsphere-clone: Power on VM...
==> vsphere-clone: Waiting for IP...
==> vsphere-clone: Power off VM...
==> vsphere-clone: Destroying VM...
Build 'vsphere-clone' errored after 15 minutes 1 second: unable to find an IP```

**Comment by dbond007** [comment]
@egkelly : What version of vmware are you using?
Asking as you need to have 6.7+(supported) I haven't been able to customise Ubuntu 20.04 on anything below from a template.

**Comment by egkelly** [comment]
We're using 6.7 👍

**Comment by egkelly** [comment]
Any ideas on this issue? This is currently a blocker for my team :)

**Comment by SwampDragons** [comment]
Nothing off the top of my head, sorry.

**Comment by dbond007** [comment]
@egkelly I will see if I can replicate the problem over the weekend, if I have time. 
I haven't yet got a 20.04 build working as my home system is on 6.5 (hardware isn't supported on 6.7). I will see if I can get it to work on 6.7 at my work. Spent weeks trying to find out why my build wasn't working with 20.04 but was fine on 18.04. Then saw vmware customisation wasn't supported on 6.5 for it. Which is why I asked you about 6.7.

**Comment by dbond007** [comment]
Hi,
have you had any progress on this? I went to try on the weekend (didn't have time earlier), but the network setup for building didn't have access to the ubuntu repo so couldn't complete the template creation.
While i try to get the openings needed, have you tried cloning the VM using vmware directly without packer and applying a customisation from there, does that work?

**Comment by dbond007** [comment]
@egkelly using vcenter and esxi 6.7, ubuntu 20.04, https://github.com/dbond007/Packer the ubuntu build there and then a basic clone (like you have above, just modded the build one in my repo for clone, stripping out all the other stuff). Network customisation didnt happen, the network was not connected, so was waiting for an IP.
Without the customisations, the network connects and DHCP give it an IP.
Using VMware customistation setting the system name, domain and network to dhcp : Fails, with network disconnected.

So appears to be something to do with the vmware customisation process used (packer uses it too as far as I know)

**Comment by sylviamoss** [comment]
Hey @egkelly, if you clone and customize the VM manually with the same ipv4 address, does the connection work? 
Like @dbond007 said, this doesn't seem to be a problem with Packer customizing the VM.

**Comment by etrombly** [comment]
I can confirm the same issue. I had an existing Centos 7 template that works on the same vcenter, when I try to use an ubuntu 20.04 template the network interface is disconnected during the clone.

`
"customize": {
      "linux_options": {
          "host_name": "{{ user `hostname` }}",
          "domain": "redacted"
      },
      "network_interface": {
        "ipv4_address": "{{ user `ip_address` }}",
        "ipv4_netmask": "24"
      },
      "ipv4_gateway": "redacted",
      "dns_server_list": ["redacted"]
    },
`

The only difference in building the templates is the shutdown command:

For centos

`
echo 'admin'|sudo -S /sbin/halt -h -p
`

for ubuntu

`
sudo /sbin/shutdown -hP now
`

**Comment by dbond007** [comment]
@etrombly what version of esxi are you running, 6.7u3g is needed for 20.04, also the following is needed to be done https://kb.vmware.com/s/article/80934

I am not sure if it will fix it, I have a repo https://github.com/dbond007/Packer/tree/master/ubuntu_base which will build, but I haven't tested yet on 6.7u3g, need to update. I have the same problem here. Ubuntu only, but have put it down to it not being supported on esxi for customisation based upon https://github.com/vmware/open-vm-tools/issues/421

**Comment by etrombly** [comment]
I updated vcenter, deleted the files mentioned in https://kb.vmware.com/s/article/80934, and set open-vm-tools.service to start after dbus, and it works now. Definitely not an issue with packer, just interaction between vcenter and ubuntu. Thanks for the help

**Comment by sylviamoss** [comment]
As this doesn't seem to be a Packer issue and some indeed were able to fix it through its own environment configuration, I'm closing this one.
