### ISSUE TITLE
Shell provisioner - Error uploading script - breaks reboot during build

### ISSUE THREAD

**Issue by sededg** [hashicorp/packer#10137]
**Packer version**
1.6.4

**Host platform:**
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       bionic

**Log output and sample template:**

I am trying to upgrade the ubuntu kernel using packer,  I see is that once the VM starts reboot and the SSH session is terminated packer resumes execution but errors out and dies because it tries to use SSH again to delete the temporary script as added by this change

```
2020/10/21 07:16:46 [INFO] 158 bytes written for 'uploadData'
2020/10/21 07:16:46 packer-builder-vsphere-clone plugin: [DEBUG] Opening new ssh session
2020/10/21 07:16:46 packer-builder-vsphere-clone plugin: [ERROR] ssh session open error: 'client not available', attempting reconnect
2020/10/21 07:16:46 packer-builder-vsphere-clone plugin: [DEBUG] reconnecting to TCP connection for SSH
2020/10/21 07:16:48 packer-builder-vsphere-clone plugin: [ERROR] reconnection error: dial tcp XX:XX:XX:XX:22: connect: no route to host
2020/10/21 07:16:48 packer-provisioner-shell plugin: Retryable error: Error uploading script: dial tcp XX:XX:XX:XX:22 connect: no route to host
2020/10/21 07:16:50 packer-provisioner-shell plugin: [INFO] 158 bytes written for 'uploadData'
2020/10/21 07:16:50 [INFO] 158 bytes written for 'uploadData'
2020/10/21 07:16:50 packer-builder-vsphere-clone plugin: [DEBUG] Opening new ssh session
2020/10/21 07:16:50 packer-builder-vsphere-clone plugin: [ERROR] ssh session open error: 'client not available', attempting reconnect
2020/10/21 07:16:50 packer-builder-vsphere-clone plugin: [DEBUG] reconnecting to TCP connection for SSH
2020/10/21 07:16:51 packer-builder-vsphere-clone plugin: [ERROR] reconnection error: dial tcp XX:XX:XX:XX:22: connect: no route to host
2020/10/21 07:16:51 packer-provisioner-shell plugin: Retryable error: Error uploading script: dial tcp XX:XX:XX:XX:22: connect: no route to host
2020/10/21 07:16:51 [INFO] (telemetry) ending shell
2020/10/21 07:16:51 ui: ==> vsphere-clone: Provisioning step had errors: Running the cleanup provisioner, if present...
2020/10/21 07:16:51 ui: ==> vsphere-clone: Power off VM...
2020/10/21 07:16:54 ui: ==> vsphere-clone: Destroying VM...
2020/10/21 07:16:58 [INFO] (telemetry) ending vsphere-clone
2020/10/21 07:16:58 ui error: Build 'vsphere-clone' errored after 20 minutes 18 seconds: Error uploading script: dial tcp 172.16.130.17:22: connect: no route to host
2020/10/21 07:16:58 ui:
==> Wait completed after 20 minutes 18 seconds
2020/10/21 07:16:58 machine readable: error-count []string{"1"}
2020/10/21 07:16:58 ui error:
==> Some builds didn't complete successfully and had errors:
2020/10/21 07:16:58 machine readable: vsphere-clone,error []string{"Error uploading script: dial tcp XX:XX:XX:XX:22: connect: no route to host"}
2020/10/21 07:16:58 ui error: --> vsphere-clone: Error uploading script: dial tcp XX:XX:XX:XX:22: connect: no route to host
2020/10/21 07:16:58 ui:
```

**My code as below:**

```
 {
            "type": "shell",
            "inline": ["sudo uname -a"]
        },

        {
           "type": "shell",
           "inline": [
           "sudo apt-get update",
           "sudo DEBIAN_FRONTEND=noninteractive apt-get install  -yq linux-headers-{{ user `kernel-version` }}",
           "sudo DEBIAN_FRONTEND=noninteractive apt-get install  -yq linux-image-{{ user `kernel-version` }} --allow-unauthenticated",
           "sudo DEBIAN_FRONTEND=noninteractive apt-get install  -yq linux-modules-extra-{{ user `kernel-version` }}",
           "sudo reboot"
         ],
            "start_retry_timeout": "30m",
            "pause_before": "2s",
            "skip_clean": "true",
            "expect_disconnect": true
     },
        {
            "type": "shell",
            "inline": [
            "sudo uname -a",
            "sudo uptime",
            "sudo dpkg --list | egrep -i --color 'linux-image|linux-headers'",
            "sudo apt-get update",
            "sudo apt-get --purge autoremove -y"
          ]
        },
```

Is there anything am i missing?

**Comment by SwampDragons** [comment]
Can you share the rest of the logs, and a more complete template? It would be helpful to me to know the version of ubuntu you're using and how you're configuring SSH.

**Comment by sededg** [comment]
[packer_debug_error_log.txt](https://github.com/hashicorp/packer/files/5427603/packer_debug_error_log.txt)
[packer_template.txt](https://github.com/hashicorp/packer/files/5427604/packer_template.txt)

**Comment by nywilken** [comment]
Hi there @sededg thanks for the additional context. Quickly looking at the logs I see that the communicator is unable to connect which is a per-requisite for the provisioner. I'll defer to @SwampDragons on how it is supposed to work when issuing a reboot command. But I am curious about the IP of the machine after the reboot. 

Have you checked if the machine is getting a new IP, maybe via DHCP, after the reboot?

**Comment by SwampDragons** [comment]
Thanks for the template and logs. The "no route to host" error could be firewall related, or could be that the instance never comes back up again -- My advice is to verify that the VM is coming back up, with the same IP address as it had before. 

It's not totally clear to me whether the second provisioner is trying to start, or the first one is still trying to reconnect; it probably doesn't actually matter since if it's stuck in the first provisioner it would likely also be stuck in the second, but to verify you can try adding a "breakpoint" provisioner after the first provisioner to give yourself time to check on the VM before Packer times out and fails; Packer will wait for you to hit "enter" before resuming execution: 

```
{
     "type": "breakpoint
}
```

You may also want to set the option `inline_shebang: "/bin/sh -x -e"` to add some more verbose logging.

**Comment by sededg** [comment]
Yes, machine is gets NEW IP after reboot (checked from console), but its not same IP (when machine booted up with IP initially). machine is booted with different IP not even matching subnet. seems like packer was not able to pick new IP?
[build_output_01.txt](https://github.com/hashicorp/packer/files/5437148/build_output_01.txt)
[packer_template_01.txt](https://github.com/hashicorp/packer/files/5437149/packer_template_01.txt)
[packer_debug_error_log_01.txt](https://github.com/hashicorp/packer/files/5437150/packer_debug_error_log_01.txt)

**Comment by SwampDragons** [comment]
Yeah, that's definitely your issue -- Packer cannot handle IP changes mid-build. If you want to to a reboot that forces an IP change, you will have to split the Packer build into two separate, sequential builds.

**Comment by SwampDragons** [comment]
I've opened an issue to track a conversation around trying to get Packer to handle IP address changes: https://github.com/hashicorp/packer/issues/10175; I'm going to close this in favor of that since it's a clearer description of the underlying problem. Meanwhile, hopefully you can work around by splitting the build or figuring out how to make the instance keep the same IP.
