### ISSUE TITLE
VMware Fusion 12 Pro cannot clone VM using vmware-vmx

### ISSUE THREAD

**Issue by leonchik1976** [hashicorp/packer#10130]
Hi, getting error output from Packer "Clone is not supported with your version of Fusion. Packer only works with Fusion 6 Professional or above."

I have VMware Fusion 12 Pro

```
$ /Applications/VMware\ Fusion.app/Contents/Library/vmware-vmx -v

VMware Fusion Information:
VMware Fusion 12.0.0 build-16880131 Release
```

```
$ packer -v
1.6.4
```

template snippet:
```
{
    "type": "vmware-vmx",
    "source_path": "../centos.vmx",
    "ssh_username": "username",
    "ssh_password": "password",
    "shutdown_command": "shutdown -P now"            
}
```

**Comment by azr** [comment]
Hello there, thanks for opening: looks like this is due to this piece of code: https://github.com/hashicorp/packer/blob/9737b85bbcc5643d8a5773aa0a6e9a1b380804d5/builder/vmware/common/driver_fusion6.go#L39-L47

Which has not changed in 2 years.
I haven't upgraded to vmware Fusion 12 pro yet but before I do, could you please share the packer logs for this, they should contain the full error. `PACKER_LOG=1 packer build ...` should give us that.

**Comment by leonchik1976** [comment]
2020/10/20 17:20:27 [INFO] Packer version: 1.6.4 [go1.15.2 darwin amd64]
2020/10/20 17:20:27 Checking 'PACKER_CONFIG' for a config file path
2020/10/20 17:20:27 'PACKER_CONFIG' not set; checking the default config file path
2020/10/20 17:20:27 Attempting to open config file: /Users/leonid/.packerconfig
2020/10/20 17:20:27 [WARN] Config file doesn't exist: /Users/leonid/.packerconfig
2020/10/20 17:20:27 Setting cache directory: /Users/leonid/packer/packer_cache
2020/10/20 17:20:27 Creating plugin client for path: /usr/local/bin/packer
2020/10/20 17:20:27 Starting plugin: /usr/local/bin/packer []string{"/usr/local/bin/packer", "plugin", "packer-builder-vmware-vmx"}
2020/10/20 17:20:27 Waiting for RPC address for: /usr/local/bin/packer
2020/10/20 17:20:27 packer-builder-vmware-vmx plugin: [INFO] Packer version: 1.6.4 [go1.15.2 darwin amd64]
2020/10/20 17:20:27 packer-builder-vmware-vmx plugin: Checking 'PACKER_CONFIG' for a config file path
2020/10/20 17:20:27 packer-builder-vmware-vmx plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/10/20 17:20:27 packer-builder-vmware-vmx plugin: Attempting to open config file: /Users/leonid/.packerconfig
2020/10/20 17:20:27 packer-builder-vmware-vmx plugin: [WARN] Config file doesn't exist: /Users/leonid/.packerconfig
2020/10/20 17:20:27 packer-builder-vmware-vmx plugin: Setting cache directory: /Users/leonid/packer/packer_cache
2020/10/20 17:20:27 packer-builder-vmware-vmx plugin: args: []string{"packer-builder-vmware-vmx"}
2020/10/20 17:20:27 packer-builder-vmware-vmx plugin: Plugin address: unix /var/folders/cv/qdq1fbxj2kjcw7n_g7v3t_hw0000gn/T/packer-plugin414346474
2020/10/20 17:20:27 packer-builder-vmware-vmx plugin: Waiting for connection...
2020/10/20 17:20:27 Received unix RPC address for /usr/local/bin/packer: addr is /var/folders/cv/qdq1fbxj2kjcw7n_g7v3t_hw0000gn/T/packer-plugin414346474
2020/10/20 17:20:27 packer-builder-vmware-vmx plugin: Serving a plugin connection...
2020/10/20 17:20:27 Preparing build: vmware-vmx
2020/10/20 17:20:27 Build debug mode: false
2020/10/20 17:20:27 Force build: false
2020/10/20 17:20:27 On error: 
2020/10/20 17:20:27 Waiting on builds to complete...
2020/10/20 17:20:27 Starting build run: vmware-vmx
2020/10/20 17:20:27 Running builder: vmware-vmx
2020/10/20 17:20:27 [INFO] (telemetry) Starting builder vmware-vmx
vmware-vmx: output will be in this color.

2020/10/20 17:20:28 packer-builder-vmware-vmx plugin: Detected VMware version: 12
2020/10/20 17:20:28 packer-builder-vmware-vmx plugin: Testing against vmware driver *common.Fusion6Driver, Success: true
==> vmware-vmx: Configuring output and export directories...
2020/10/20 17:20:28 packer-builder-vmware-vmx plugin: No floppy files specified. Floppy disk will not be made.
2020/10/20 17:20:28 packer-builder-vmware-vmx plugin: No CD files specified. CD disk will not be made.
==> vmware-vmx: Creating required virtual machine disks
2020/10/20 17:20:28 packer-builder-vmware-vmx plugin: Cloning from: /Users/leonid/Virtual Machines.localized/centos.vmwarevm/centos.vmx
==> vmware-vmx: Cloning source VM...
2020/10/20 17:20:28 packer-builder-vmware-vmx plugin: Cloning to: output-vmware-vmx/packer-vmware-vmx-1603203627.vmx
2020/10/20 17:20:28 packer-builder-vmware-vmx plugin: Executing: /Applications/VMware Fusion.app/Contents/Library/vmrun -T fusion clone /Users/leonid/Virtual Machines.localized/centos.vmwarevm/centos.vmx output-vmware-vmx/packer-vmware-vmx-1603203627.vmx full
2020/10/20 17:20:28 packer-builder-vmware-vmx plugin: stdout: Error: One of the parameters was invalid
2020/10/20 17:20:28 packer-builder-vmware-vmx plugin: stderr:
==> vmware-vmx: Deleting output directory...
2020/10/20 17:20:28 [INFO] (telemetry) ending vmware-vmx
==> Wait completed after 619 milliseconds 907 microseconds
2020/10/20 17:20:28 machine readable: error-count []string{"1"}
==> Some builds didn't complete successfully and had errors:
2020/10/20 17:20:28 machine readable: vmware-vmx,error []string{"Clone is not supported with your version of Fusion. Packer only works with Fusion 6 Professional or above. Please verify your version."}
==> Builds finished but no artifacts were created.
2020/10/20 17:20:28 [INFO] (telemetry) Finalizing.
Build 'vmware-vmx' errored after 619 milliseconds 862 microseconds: Clone is not supported with your version of Fusion. Packer only works with Fusion 6 Professional or above. Please verify your version.

==> Wait completed after 619 milliseconds 907 microseconds

==> Some builds didn't complete successfully and had errors:
--> vmware-vmx: Clone is not supported with your version of Fusion. Packer only works with Fusion 6 Professional or above. Please verify your version.

==> Builds finished but no artifacts were created.
2020/10/20 17:20:29 waiting for all plugin processes to complete...
2020/10/20 17:20:29 /usr/local/bin/packer: plugin process exited

**Comment by azr** [comment]
@leonchik1976 thanks, I just installed vmware fusion 12:

But it looks like your issue is that you have a space in you path, look:

```
Executing: /Applications/VMware Fusion.app/Contents/Library/vmrun -T fusion clone /Users/leonid/Virtual Machines.localized/centos.vmwarevm/centos.vmx output-vmware-vmx/packer-vmware-vmx-1603203627.vmx full
```

I think the first argument needs to be quoted by packer:

```
/Users/leonid/Virtual Machines.localized/centos.vmwarevm/centos.vmx output-vmware-vmx/packer-vmware-vmx-1603203627.vmx full
```

The command probably thinks you want to clone `/Users/leonid/Virtual` into `Machines.localized/centos.vmwarevm/centos.vmx`.

One quick way to solve this could be to not use `..` in your path and only use relative paths. I'll try to quote this Packer side so that this does not happen again.

**Comment by azr** [comment]
Hello there, quick update, putting spaces in paths does work for me and I'm sort of out of guesses here.

**Comment by leonchik1976** [comment]
i recreated from scratch - just base install - i put template in the same folder as vmx file! same error

**Comment by leonchik1976** [comment]
i'm also able to clone machine without any issue via gui of Fusion Pro

**Comment by azr** [comment]
Can you give me the packer template to create the `centos.vmx` file ?

**Comment by leonchik1976** [comment]
hi, first of all, proof of working snapshots
```
leonid@leonids-mac-mini Virtual Machines.localized % /Applications/VMware\ Fusion.app/Contents/Library/vmrun snapshot centos.vmwarevm/centos.vmx test-snapshot
leonid@leonids-mac-mini Virtual Machines.localized % /Applications/VMware\ Fusion.app/Contents/Library/vmrun listSnapshots centos.vmwarevm/centos.vmx         
Total snapshots: 1
test-snapshot

```

the template is above in original post - just omitted there the full path

**Comment by azr** [comment]
I see the one that uses the vmx file not the one that creates it 👀

**Comment by leonchik1976** [comment]
it's suppose to clone it, no? and this is the error

**Comment by azr** [comment]
I would like to recreate the vmx file you are using, to reproduce your case from scratch in case there's something there. I do not have enough info here and it's working on my machine so I'm making the search broader.

**Comment by leonchik1976** [comment]
it's a minimal centos 8 installation

**Comment by azr** [comment]
I know it feels obvious from your side, but "minimal" can mean a lot of things. I've tried to reproduce this with what I consider to be a "minimal" setup and I can't, which is why I'm asking for more information. If you can't or don't want to provide more information, I can't help you further.

**Comment by leonchik1976** [comment]
I can't understand what info do you need?

**Comment by SwampDragons** [comment]
How are you creating the vmx you are trying to clone? Is it another Packer template? If not, where are you getting it?

**Comment by leonchik1976** [comment]
I'm creating vmx by installing centos 8 just like in this page: https://lintut.com/how-to-install-centos-8-minimal-server/

**Comment by azr** [comment]
Hello @leonchik1976, so I've create a centos-8 bento box using the vmware-iso builder of Packer ;

you can find the config file here: https://github.com/chef/bento/blob/2e4f14eeb36264c14962941b6a607402efdd08a7/packer_templates/centos/centos-8.2-x86_64.json#L29-L55
( I added `"keep_input_artifact": true,` in post-processor  to get the vmware files too).

I used `packer build --only vmware-iso centos-8.2-x86_64.json`; this also installs [vmware vm tools](https://github.com/chef/bento/blob/3b3c1aa49e581211faf8f87b5c055051e51c45ff/packer_templates/_common/vmware.sh#L6-L43) but you could add an open-vm-tools install to it.

This build gave me a folder containing:
```shellsession
$ ls ../../builds/packer-centos-8.2-x86_64-vmware 
centos-8.2-x86_64.nvram disk-s003.vmdk          disk-s009.vmdk          disk-s015.vmdk
centos-8.2-x86_64.vmsd  disk-s004.vmdk          disk-s010.vmdk          disk-s016.vmdk
centos-8.2-x86_64.vmx   disk-s005.vmdk          disk-s011.vmdk          disk-s017.vmdk
centos-8.2-x86_64.vmxf  disk-s006.vmdk          disk-s012.vmdk          disk.vmdk
disk-s001.vmdk          disk-s007.vmdk          disk-s013.vmdk
disk-s002.vmdk          disk-s008.vmdk          disk-s014.vmdk
```

Which I could clone using the vmware-vmx Packer builder.

I'm guessing you were exporting the vmware vmx file wrong, or something and I'd recommend on using the bento box config file as a starting point !

I'm going to go ahead an close that issue since it's not caused by Packer. Thanks ! Don't hesitate if you have questions !
