### ISSUE TITLE
vsphere-(iso/clone) tags and custom attributes

### ISSUE THREAD

**Issue by dbond007** [hashicorp/packer#10147]
#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

Allow the adding of tags to templates within vsphere/esxi like available within terraform.
#### Use Case(s)

Allows adding tags to templates so you can add information about the template for example build date, OS version, roles, build version, builder etc So information on the template can be extracted instead of needing to encode as much of this in the template name or external database.

#### Potential configuration

see references

#### Potential References

https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/tag_category
https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/tag
https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/custom_attribute

**Comment by azr** [comment]
Hello there, thanks for opening, I think this is a good idea !

**Comment by dbond007** [comment]
@azr : Wish I could, but right now I have zero experience in go.

**Comment by azr** [comment]
@dbond007, Got it, no worries !
