### ISSUE TITLE
Packer HCL Environment Variables without PKR_VAR_

### ISSUE THREAD

**Issue by kclinden** [hashicorp/packer#10152]
#### Description

When using CI/CD tools such as Jenkins or CodeBuild you may want to reference environment variables that are not managed by the user. The specific example that I am looking at is getting the Git Repo URL and Commit ID from AWS CodeBuild which are stored in `CODEBUILD_SOURCE_VERSION` and `CODEBUILD_SOURCE_REPO_URL`.

When doing the HCL2_Upgrade the input variables resulted in the following:

```
variable "git_commit" {
  type    = string
  default = "${var.CODEBUILD_SOURCE_VERSION}"
}

variable "git_repo" {
  type    = string
  default = "${var.CODEBUILD_SOURCE_REPO_URL}"
}
```
Under JSON this works with the following:
```
    "variables": {
        "git_repo": "{{ env `CODEBUILD_SOURCE_REPO_URL`}}",
        "git_commit": "{{env `CODEBUILD_SOURCE_VERSION`}}"
    }
```

#### Current Error on validation
```
Error: Variables not allowed

  on packer-windows-2016-amazon-ami.json.pkr.hcl line 21, in variable "git_commit":
  21:   default = "${var.CODEBUILD_SOURCE_VERSION}"

Variables may not be used here.

Error: Variables not allowed

  on packer-windows-2016-amazon-ami.json.pkr.hcl line 26, in variable "git_repo":
  26:   default = "${var.CODEBUILD_SOURCE_REPO_URL}"

Variables may not be used here.
```

#### Use Case(s)

Leverage CI/CD created Environment Variables

**Comment by azr** [comment]
Hello there, thanks for opening. [All env vars must be prefixed with `PKR_VAR_`](https://www.packer.io/guides/hcl/variables#from-environment-variables), this is to make sure these var were explicitly defined to be used by Packer as input values and for safety reasons.

One thing you can do is : 

`PKR_VAR_CODEBUILD_SOURCE_VERSION=${CODEBUILD_SOURCE_VERSION} packer build ...`

**Comment by azr** [comment]
To add a little info to this, when we implement build chaining in packer or may be the ability to invoke something like a packer module from a packer module then we would like this submodule to be able to work without forcing the starter to have to set env vars hence the strong push onto not supporting env variables from a template file.

Note: currently we don't know if there is going to be something like a packer module at all ( I'm personally pretty much looking forward for Packer to have that) but it's way easier to say no now than to deprecate it later on.

**Comment by azr** [comment]
Hello there ! Just to say we've given this some thought and decided to make the `env` function available as a default for input variables. After giving it some thought it's not so dangerous and the operators should know what they are doing. Also because lots of users will probably have this exact same issue since you had it, making easier to upgrade.

**Comment by kclinden** [comment]
Awesome that is great news.

**Comment by SwampDragons** [comment]
We spent some time discussing this option internally and decided to reverse course on our decision -- you'll be able to use an env function in HCL once #10240 is merged.

**Comment by zfouts** [comment]
That's fantastic news, thank you!
