### ISSUE TITLE
Add Password Parameter to Inspec Provisioner

### ISSUE THREAD

**Issue by kclinden** [hashicorp/packer#10151]
#### Description

When using Inspec with Windows and WinRM you have to provide a password using the `--password` paremter via inspec exec. Instead of making this be sent as an extra argument add a parameter to the provisioner. 

#### Use Case(s)

Using Packer with Windows WinRM and the Inspec Provisioner over WinRM

#### Potential configuration

```
  provisioner "inspec" {
    backend                = "winrm"
    password              = {{.WinRMPassword}}
    host                       = "{{build `Host`}}"
    inspec_env_vars   = ["CHEF_LICENSE=accept"]
    profile                   = "https://github.com/kclinden/microsoft-windows-server-2016-stig-baseline"
    user                      = "Administrator"
  }
```

**Comment by SwampDragons** [comment]
Thanks for this suggestion! The inspec provisioner is one of our community-supported provisioners, which means that the HashiCorp maintainers don't spend much engineering time on it; this means that the best way to see your suggestion make it into Packer is to open a PR. We'll gladly give support and pointers if you're interested in taking a shot at it.
