### ISSUE TITLE
Add Azure CLI authentication for azure-arm

### ISSUE THREAD

**Issue by simongottschlag** [hashicorp/packer#10156]
#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

We are using Azure CLI for authentication together with most tools today (terraform azure backend, terraform azurerm provider, terraform azuread provider and Ansible azurerm module). This works really well both locally and together with Azure DevOps (Azure Pipelines).

It would be great if we could add the functionality to packer to use the Azure CLI authentication as well, making the local experience more like terraform / Ansible as well as keeping the pipelines standardized.

#### Use Case(s)

User logs in with `az login` or Pipeline logs in with a service principal `az login --service-principal --username APP_ID --password PASSWORD --tenant TENANT_ID` and packer is able to pick up the token, tenantID, subscriptionID and use them instead of manually having to define/import them.

#### Potential configuration

Since this would be kind of like the MSI authentication, I'd like to add a flag that enables this instead of figuring it out by what is provided.

```
"use_azure_cli_auth": true
```

**Comment by nywilken** [comment]
Hi there @simongottschlag, this sounds like a great idea! Thanks for opening up the request and accompanying PR. We will take a look first chance we get.
