### ISSUE TITLE
azure-arm builder - HCL2 syntax failed to identify the managed_image_name argument

### ISSUE THREAD

**Issue by benhurjoel** [hashicorp/packer#10160]
#### Overview of the Issue

I'm trying to create an Image on Azure using the HCL2 syntax and publish it on a Shared Image Gallery. i'm getting the following error:
```
* Specify either a VHD (storage_account and resource_group_name) or Managed Image (managed_image_resource_group_name and managed_image_name) output
```
My template has the managed_image_name argument though
#### Reproduction Steps

My code:
```
source "azure-arm" "packer-exec" {
  subscription_id = var.subscription
  client_id = var.client_id
  client_secret = var.client_secret
  tenant_id = var.tenant_id
  resource_group_name = var.resource_group_name
  os_type = var.os_type
  image_publisher = var.image_publisher
  image_offer = var.image_offer 
  image_sku = var.image_sku
  location = var.location
  vm_size = var.vm_size

  shared_image_gallery_destination {
    subscription = var.subscription
    resource_group = var.resource_group_name
    gallery_name = var.gallery_name
    image_name = var.image_name
    image_version = var.image_version
    replication_regions = var.replication_regions
  }
  managed_image_name = var.managed_image_name
  managed_image_resource_group_name = var.managed_image_resource_group_name

}

build {
    sources = [
        "source.azure-arm.packer-exec"
    ]
    provisioner "ansible" {
      playbook_file = "${var.playbook_path}"
    }
}

```
### Packer version

1.6.4

**Comment by nywilken** [comment]
Hi there @benhurjoel it looks like you are defining a `resource_group_name` attribute as well as a `managed_image_resource_group_name` , which are conflicting attributes. The error you are seeing is a builder validation error and not a HCL2 error.  

If you remove the `resource_group_name` attribute do you still run into this issue?

**Comment by benhurjoel** [comment]
Hi @nywilken .. Thank you  for your comment.. I  just tried removing `resource_group_name` and that worked! Appreciate your help! May I ask to explicitly mention in the document to omit the` resource_group_name` argument if `managed_image_resource_group_name` is defined?
