### ISSUE TITLE
Add ipconfig[n] support for Proxmox builder

### ISSUE THREAD

**Issue by Weilbyte** [hashicorp/packer#10169]
#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

Add support for setting the cloud-init ipconfig setting when using the Proxmox builder. It should be found here as available config type => https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/config

#### Use Case(s)

Easily setting up the VM template to use DHCP without having to mess around with the OS-specific configuration tools.

#### Potential configuration

For example setting v4/v6 to DHCP:
```
{
 "ipconfig": [
    id: 0,
    v4: "dhcp",
    v6: "dhcp"
  ]
}
```

**Comment by azr** [comment]
cc @carlpett
