### ISSUE TITLE
amazon-ebs: ssh_username can not be provided with "-var" or "-var-file"

### ISSUE THREAD

**Issue by TheodorV** [hashicorp/packer#10171]
#### Overview of the Issue

When trying to build an ami with amazon-ebs, I can only specify the ssh-username directly inside the builder or by referring it to a user variable in the "variables" section. If I try to provide it by "-var" or inside a file with "-var-file", the packer build command fails saying that the ssh_username has to be specified.

#### Reproduction Steps

1. Use amazon-ebs to build an ami, with ansible provisioner (should have no effect on the outcome, but, what ever). 
2. Provide the ssh_username for the building instance by referencing it to a variable : "{{user `aws_ssh_username`}}"
3. Do not define the variable "something" inside the "variables" section, do it through a -var-file or directly in the command line using -var

### Packer version

1.6.0

### Operating system and Environment details

Packer is running inside an alpine container. 
AMI will be based on centos 7.8

### Log Fragments and crash.log files

Error initializing core: Failed to interpolate "ssh_username": "{{user `aws_ssh_username`}}": Please make sure that the variable you're referencing has been defined; Packer treats all variables used to interpolate other user varaibles as required.

Question:
Is this a feature or a bug?

**Comment by azr** [comment]
Hello @TheodorV, to define variables you have to define them in the variable section, and to use them you have to quote them in the go templating call, for example:

```json
{
    "variables": {
        "aws_ssh_username": null
    },
    "builders": [
      {
        "ssh_username": "{{user `aws_ssh_username`}}"
      }
    ],
    "provisioners": [
      {
        "type": "shell",
        "inline": ["echo hi"]
      }
    ]
  }
```
Now with this if I run 
```shellsession
$ packerdev build  .vscode/auto-key-gcp.json
Error: 

1 error occurred:
        * required variable not set: aws_ssh_username
```

And to set the variable I can do:
```shellsession
$ packer build -var aws_ssh_username=something file.json
```
