### ISSUE TITLE
ovftool failure not detected

### ISSUE THREAD

**Issue by stuart-c** [hashicorp/packer#10179]
#### Overview of the Issue

The ovftool post-processor is used to copy a VMware image from our build ESXi server to our production cluster. This failed due to a networking error, but even though ovftool failed the overall Packer build was marked as successful. Additionally it looks like the source image was deleted from the build server, preventing a manual copy.

#### Reproduction Steps

Run Packer with VMware build steps, including ovftool post-processor to copy image. Prevent connection to destination vSphere (e.g. incorrect IP address or firewall rejection)

Expected: ovftool fails & Packer fails

Actual: ovftool fails, but Packer continues, deleting source image & marking build as successful

### Packer version

1.6.4

### Operating system and Environment details

Linux (Ubuntu 18.04)

### Log Fragments and crash.log files

15:48:00  ==> vmware-iso: Gracefully halting virtual machine...
15:48:12      vmware-iso: Waiting for VMware to clean up after itself...
15:48:16  ==> vmware-iso: Deleting unnecessary VMware files...
15:48:16      vmware-iso: Deleting: /vmfs/volumes/Datastore1/ubuntu-docker-1603810719/vmware.log
15:48:16  ==> vmware-iso: Cleaning VMX prior to finishing up...
15:48:16      vmware-iso: Detaching ISO from CD-ROM device ide0:0...
15:48:16      vmware-iso: Disabling VNC server...
15:48:17  ==> vmware-iso: Exporting virtual machine...
15:48:17      vmware-iso: Executing: ovftool --noSSLVerify=true --skipManifestCheck -tt=ovf vi://user:%3Cpassword%3E@10.10.10.10/ubuntu-docker-1603810719 ovf-docker/ubuntu-docker-1603810719.ovf
15:50:08  ==> vmware-iso: Destroying virtual machine...
15:50:08  ==> vmware-iso: Running post-processor: manifest
15:50:08  ==> vmware-iso: Running post-processor: vsphere
15:50:08      vmware-iso (vsphere): Uploading ovf-docker/ubuntu-docker-1603810719.ovf to vSphere
15:50:08      vmware-iso (vsphere): Validating Username and Password with dry-run
15:50:09      vmware-iso (vsphere): Calling OVFtool to upload vm
15:50:09      vmware-iso (vsphere): Opening OVF source: ovf-docker/ubuntu-docker-1603810719.ovf
15:50:09      vmware-iso (vsphere): The manifest validates
15:50:14      vmware-iso (vsphere): Error: Internal error: Failed to connect to remote host [xxx.xxx.com] due to [No version for VMODL calls to <cs p:000055a33aaa0760, TCP:xxx.xxx.com:443>]
15:50:14      vmware-iso (vsphere): Completed with errors
15:50:14  Build 'vmware-iso' finished after 51 minutes 30 seconds.
15:50:14  
15:50:14  ==> Wait completed after 51 minutes 30 seconds
15:50:14  
15:50:14  ==> Builds finished. The artifacts of successful builds are:
15:50:14  --> vmware-iso: VM files in directory: ovf-docker
15:50:14  --> vmware-iso: 
15:50:14  --> vmware-iso: VM: ubuntu-docker-1603810719 Folder: Streaming/Templates Datastore: Datastore

**Comment by nywilken** [comment]
Thanks for reaching out. Could you provide the the simplest Packer configuration along with the debug logs `PACKER_LOG=1 packer build <template-path> so that we can take a look at what might be going on here. Thanks!

**Comment by RyuCaelum** [comment]
@nywilken This is the simplest Packer configuration we have (pasted below). The logs for it are here: https://pastebin.com/kiNhSWAS


{
  "variables": {
    "build_time": "{{timestamp}}",
    "build_version": "{{env `BUILD_VERSION`}}",
    "build_name": "test-{{user `build_time`}}",
    "vault_role": "{{env `VAULT_ROLE`}}",
    "type": "base",
    "esxi_host": "{{vault  `host`}}",
    "esxi_user": "{{vault `username`}}",
    "esxi_pass": "{{vault` `password`}}",
    "esxi_datastore": "Datastore1",
    "vcenter_host": "10.10.10.10",
    "vcenter_user": "{{vault ` `username`}}",
    "vcenter_pass": "{{vault  `password`}}",
    "vcenter_datastore": "Datastore",
    "vcenter_cluster": "EQX",
    "vcenter_dc": "EXAMPLE",
    "vcenter_network": "EQX_VLAN108",
    "vcenter_folder": "Streaming/Templates",
    "vcenter_machine": "example.com",
    "ip_address": "11.11.11.11",
    "netmask": "255.255.255.0",
    "gateway": "12.12.12.12",
    "nameservers": "8.8.8.8",
    "vlan": "VLAN_105"
  },
  "provisioners": [
  ],
  "builders": [
    {
      "type": "vmware-iso",
      "vmdk_name": "{{user `build_name`}}",
      "vm_name": "{{user `build_name`}}",
      "iso_url": "http://archive.ubuntu.com/ubuntu/dists/bionic-updates/main/installer-amd64/current/images/netboot/mini.iso",
      "iso_checksum": "f6308b55e132067b8991439d92763078",
      "ssh_username": "ubuntu",
      "ssh_private_key_file": "packer.pem",
      "ssh_timeout": "2h",
      "shutdown_command": "sudo shutdown -P now",
      "remote_type": "esx5",
      "remote_host": "{{user `esxi_host`}}",
      "remote_username": "{{user `esxi_user`}}",
      "remote_password": "{{user `esxi_pass`}}",
      "remote_datastore": "{{user `esxi_datastore`}}",
      "http_directory": "http",
      "vnc_disable_password": true,
      "output_directory": "ovf-{{user `type`}}",
      "boot_command": [
        "<esc><esc><wait>",
        "install auto url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/preseed.cfg <wait>",
        "locale=en_GB.UTF-8 <wait>",
        "console-setup/ask_detect=false <wait>",
        "console-setup/layoutcode=gb <wait>",
        "keyboard-configuration/layoutcode=gb <wait>",
        "domain=global.com <wait>",
        "hostname=packer <wait>",
        "netcfg/disable_autoconfig=true <wait>",
        "netcfg/get_ipaddress={{user `ip_address`}} <wait>",
        "netcfg/get_netmask={{user `netmask`}} <wait>",
        "netcfg/get_gateway={{user `gateway`}} <wait>",
        "netcfg/get_nameservers={{user `nameservers`}} <wait>",
        "netcfg/confirm_static=true <wait>",
        "initrd=/install/initrd.gz -- <enter>"
      ],
      "cpus": 4,
      "memory": 1024,
      "network_adapter_type": "vmxnet3",
      "disk_size": 8192,
      "guest_os_type": "ubuntu-64",
      "vmx_data": {
        "ethernet0.networkName": "{{user `vlan`}}"
      }
    }
  ],
  "post-processors": [
    {
      "type": "vsphere",
      "cluster": "{{user `vcenter_cluster`}}",
      "datacenter": "{{user `vcenter_dc`}}",
      "datastore": "{{user `vcenter_datastore`}}",
      "host": "{{user `vcenter_host`}}",
      "insecure": true,
      "password": "{{user `vcenter_pass`}}",
      "username": "{{user `vcenter_user`}}",
      "vm_name": "{{user `build_name`}}",
      "esxi_host": "{{user `vcenter_machine`}}",
      "vm_folder": "{{user `vcenter_folder`}}",
      "vm_network": "{{user `vcenter_network`}}",
      "only": [ "vmware-iso" ]
    }
  ]
}

**Comment by RyuCaelum** [comment]
@nywilken

**Comment by RyuCaelum** [comment]
@nywilken

**Comment by SwampDragons** [comment]
FWIW To prevent the original artifact from being deleted, you can set "keep_input_artifact: true".
