### ISSUE TITLE
Packer failing to get IP address on macOS 11 with VMware Fusion 12.0

### ISSUE THREAD

**Issue by trodemaster** [hashicorp/packer#10177]
#### Overview of the Issue
When using packer on macOS with VMware Fusion hypervisor the /var/db/vmware/vmnet-dhcpd-vmnet8.leases file is used to provide the guest OS IP address. Due to changes in macOS 11 (in beta as of today) VMware has adopted Apple provided hypervisor.framework and related networking stack. The end result with Fusion 12.0 is that the /var/db/vmware/vmnet-dhcpd-vmnet8.leases file is not populated and packer cant extract the needed IP address to configure the communicators. 

I have opened a bug with VMware on this issue and waiting for details on how they will handle this change. Once I have guidance I will update this bug. If the dhcpd.conf file is going to be populated in a future version of Fusion then this issue will only exist for Fusion 12.0 on macOS 11. If going forward that file will not be used another method to determine the guest OS IP will be needed. 

#### Reproduction Steps
Setup macOS 11 and install packer 1.6.4 and VMware Fusion 12.0. Use packer to build any template that uses ssh/winrm communicator. Note that the build hangs waiting for the vmnet-dhcpd-vmnet8.leases file to be populated. If you copy valid data into that file the packer build will continue as expected. 

### Packer version

1.6.4

### Simplified Packer Buildfile

Confirmed the issue using this packer template https://github.com/trodemaster/packer-macOS-11 however any simple template that uses ssh or winrm will show the issue. This issue is not specific to any guest OS or template. 

### Operating system and Environment details
Host: macOS 11 Beta 10

Forum post noting this issue https://communities.vmware.com/thread/644271

**Comment by SwampDragons** [comment]
Thanks for opening this -- looks like the VMware team have acknowledged in your post that this is an upstream bug, so I'll follow that issue for guidance too. If they don't get back to you soon I'll reach out internally through HashiCorp's partner channels.

**Comment by alexpinheirosoares** [comment]
Ok, so this is not the prettiest workaround in any cases, here it goes:

1. You start up your packer and it will perform then initial OS setup (silent install accordingly with your kickstart, pressed or unannatend.xml).
2. Once your provisioners kick in, it will stay hanged trying to establish SSH (you need to increase your timeout)
3. Open the Fusion Console on the VM that is creating, login and grab the mac address and ip address that the vm has.
4. Go to /var/db/vmware and edit one of the `.lease` files you have there, adding the appropriate lease information (example below):
```
lease 192.168.108.4 {
	starts 2 2020/11/17 16:19:39;
	ends 2 2021/11/17 16:49:39;
	hardware ethernet 00:0c:29:4e:52:58;
	uid 01:00:0c:29:4e:52:58;
}
```
5. Once you save the file, packer will detect the IP address and the provisioners will start.

I am not sure that the "change"/bug correction needs to occur on VMware side or at Packer side (which basically)!

**Comment by trodemaster** [comment]
VMware has acknowledged the issue and I provided a functional solution to them. I imagine their focus is currently on releasing a build for Apple Silicon right now. I also have adopted creating a fake lease while we wait on a resolution.  
https://github.com/trodemaster/packer-macOS-11/blob/main/scripts/fakelease.sh

**Comment by yerkanian** [comment]
You can look up the MAC address in the /var/db/dhcpd_leases (managed by the new Apple DHCP server) on macOS 11 BigSur:

'{
	ip_address=192.168.191.4
	hw_address=1,0:c:29:b0:9e:ae
	identifier=1,0:c:29:b0:9e:ae
	lease=0x5fd4a699
	name=centos8
}`

**Comment by trodemaster** [comment]
Good find yerkanian! My recommendation is to update the packer code that searches for the IP address to check if the host OS is macOS version 11 or greater. If so then take the known mac address and search this /var/db/dhcpd_leases for the lease and related IP address. Also it's highly likely that other builders that start using hypervisor.framework will also benefit from this update.

**Comment by yerkanian** [comment]
The mac address will need to be zero-padded on BigSur before searching the file (/usr/sbin/arp also uses the same format for its output), not sure about the previous versions though.

**Comment by Pyrrvs** [comment]
I made a PR that seems to fix this issue. It was able to use Packer on my MBP with MacOS BigSur to generate a machine image.

**Comment by trodemaster** [comment]
Thanks for the PR Pyrrvs! I have built packer with this PR and confirmed it's working for me. Host os is macOS 11.1RC. Here is the relevan log from my run. 

https://gist.github.com/trodemaster/45c4d3bca4f0cc331520e043b1e6d8a3
