### ISSUE TITLE
vsphere-iso - Content Library ovf upload 403 error

### ISSUE THREAD

**Issue by junk4porthos** [hashicorp/packer#10183]
#### Overview of the Issue

I have a vsphere-iso builder that is failing when trying to upload an ovf to a Content Library.

All other functions are working correctly, including uploading the vm as a template to the exact same Content Library.

The VM starts, builds, and shuts down cleanly. Only failing when the ovf option is set to true for the content library destination.

The user account being used has full admin rights to vsphere and is a member of the Administrators group.

#### Reproduction Steps

Run build with content library destination set to ovf: true

### Packer version

1.6.4

### Simplified Packer Buildfile
      "builders": [
        {
            "name": "windows-srv-2019-std",
            "type": "vsphere-iso",
      
            "vcenter_server":    "{{user `vsphere_host`}}",
            "username":          "svcaccount@vsphere.local",
            "password":          "{{user `vsphere_password`}}",
            "datacenter":        "{{user `vsphere_datacenter`}}",
            "folder":            "{{user `vsphere_folder`}}",
            "cluster":           "{{user `vsphere_cluster`}}",
            "host":              "{{user `vsphere_esxi_host`}}",
            "datastore":         "{{user `vsphere_datastore`}}",
            "vm_version":        "{{user `vsphere_vm_version`}}",

            "vm_name":              "windows-2019-Stndrd-vm-{{isotime \"20060102\"}}",
            "insecure_connection":  "true",
            "guest_os_type":        "windows9Server64Guest",
            "boot_wait":            "4m",

            "communicator":     "winrm",
            "winrm_username":   "packer",
            "winrm_password":   "packer",
      
            "CPUs":             2,
            "CPU_hot_plug":     "{{user `vsphere_cpu_hotplug`}}",
            "RAM":              4096,
            "RAM_hot_plug":     "{{user `vsphere_ram_hotplug`}}",
      
            "disk_controller_type":  "pvscsi",
            "storage": [
                {
                  "disk_size": "{{user `vsphere_disk_size`}}",
                  "disk_thin_provisioned": "true"
                }
              ],
              "network_adapters": [
                {
                  "network": "{{user `vsphere_network`}}",
                  "network_card": "vmxnet3"
                }
              ],
            "cdrom_type":   "sata",
            "iso_paths":    [
                            "[TESTING] ISO/Packer-Windows2019/SW_DVD9_Win_Server_STD_CORE_2019_1909.4_64Bit_English_DC_STD_MLF_X22-29333.ISO",
                            "[] /usr/lib/vmware/isoimages/windows.iso"
                            ],
                  
            "floppy_files": [
                            "scripts/VMware/2019/autoUnattend.xml",
                            "scripts/Windows/init.ps1",
                            "scripts/VMware/drivers/pvscsi/pvscsi-windows8/AMD64",
                            "scripts/VMware/drivers/vmxnet3",
                            "scripts/VMware/VMTools/vmtools.ps1"
                            ],
            "configuration_parameters": {
                            "tools.capability.auto_upgrade": "true"
                            },

            "shutdown_command": "shutdown /s /t 0 /f /d p:4:1 /c \"Packer Shutdown\"",
            "remove_cdrom":         "true",
            "convert_to_template":  "false",
            "content_library_destination" : {
              "library": "{{user `vsphere_contentlib`}}",
              "ovf": true
            }
      
        },

### Operating system and Environment details

Env = Vsphere 6.7.0 Build 16709110
VM = Windows Server 2019

### Log Fragments and crash.log files

2020/10/28 21:00:34 ui: ==> windows-srv-2019-std: Deleting Floppy drives...
2020/10/28 21:00:34 ui: ==> windows-srv-2019-std: Deleting Floppy image...
2020/10/28 21:00:34 ui: ==> windows-srv-2019-std: Eject CD-ROM drives...
2020/10/28 21:00:35 ui: ==> windows-srv-2019-std: Deleting CD-ROM drives...
2020/10/28 21:00:35 ui: ==> windows-srv-2019-std: Importing VM OVF template windows-2019-Stndrd-vm-20201029 to Content Library...
2020/10/28 21:00:37 ui error: ==> windows-srv-2019-std: Failed to import template windows-2019-Stndrd-vm-20201029: POST https://vcsafqdn/rest/com/vmware/vcenter/ovf/library-item: 403 Forbidden
2020/10/28 21:00:37 ui: ==> windows-srv-2019-std: Provisioning step had errors: Running the cleanup provisioner, if present...
2020/10/28 21:00:37 ui: ==> windows-srv-2019-std: Clear boot order...
2020/10/28 21:00:38 ui: ==> windows-srv-2019-std: Power off VM...
2020/10/28 21:00:38 packer.exe plugin: Deleting floppy disk: C:\Users\Test\AppData\Local\Temp\packer990827683
2020/10/28 21:00:38 ui: ==> windows-srv-2019-std: Destroying VM...
2020/10/28 21:00:38 [INFO] (telemetry) ending vsphere-iso

**Comment by junk4porthos** [comment]
Closing issue, I was being dense. I realized it was a permissions issue in vsphere with the service account I was using.

**Comment by dhoeld** [comment]
@junk4porthos Could you please share the way you solved the permission issues? Ran into the same permission issue lately and would be very thankful for any advise. :-)
