### ISSUE TITLE
I've also found this issue, but in my case I can confirm it comes from different ISO versions. For example 2 different revisions of MS2016 Partner ISO gave me different results:

### ISSUE THREAD

**Issue by Lionz01** [hashicorp/packer#10184]
I've also found this issue, but in my case I can confirm it comes from different ISO versions. For example 2 different revisions of MS2016 Partner ISO gave me different results:

The config that works for them both is (in my case) :

```json
 "boot_wait": "0s",
      "boot_command": [
        "a<enter><wait>"
      ],
```

_Originally posted by @marcinbojko in https://github.com/hashicorp/packer/issues/6208#issuecomment-384936851_

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out! I'm a little confused by this issue -- the title implies you can't get it working, but the body says you got them working using the given boot command. Are you currently able to build using these images?

**Comment by marcinbojko** [comment]
Hi @SwampDragons , I think that means (what we proved earlier) different MS ISOs will require different boot strings. During work with packer I've found out that there is no generic rule - some isos are working better and more generic, some require a little rework. I don't think that that's something we can do, except warn users about this.

**Comment by nywilken** [comment]
Hi @marcinbojko catching up on the threads and it seems like you are suggesting a documentation change. If so would you be open to submitting a PR with the updated docs?
