### ISSUE TITLE
API endpoint for Outscale cn-southeast-1 is not correct

### ISSUE THREAD

**Issue by Hakujou** [hashicorp/packer#10186]
#### Overview of the Issue

API endpoint for Outscale cn-southeast-1 is not correct

#### Reproduction Steps

Set region to cn-southeast-1 and use one of Outscale builders.
The API endpoint for Outscale cn-southeast-1 is set to "api.cn-southeast-1.outscale.com" while correct API endpoint is "api.cn-southeast-1.outscale.hk".

**Comment by SwampDragons** [comment]
cc @marinsalinas
