### ISSUE TITLE
Problem with hyper-v and CentOS7

### ISSUE THREAD

**Issue by Tomelin** [hashicorp/packer#10189]
Hi,

I want to build CentOS7 in Hyper-v, but it is returning the following error:

My conf:
{

  "builders": [
    {
      "type": "hyperv-iso",
      "boot_command": [
        "<tab> text ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/ks.cfg<enter><wait>"
      ],
      "boot_wait": "10s",
      "name": "RedHat_{{timestamp}}",
      "disk_size": 81920,
      "guest_additions_mode": "disable",
      "headless": false,
      "http_directory": "http",
      "iso_urls": [
        "CentOS-7-x86_64-Minimal-2003.iso",
        "http://mirrors.mit.edu/centos/7/isos/x86_64/CentOS-7-x86_64-Minimal-2003.iso"
      ],
      "iso_checksum": "sha256:659691c28a0e672558b003d223f83938f254b39875ee7559d1a4a14c79173193",
      "ssh_username": "root",
      "ssh_password": "p@ck3r",
      "ssh_port": 22,
      "ssh_wait_timeout": "1800s",
      "shutdown_command": "echo 'vagrant'|sudo -S /sbin/halt -h -p",
      "virtualbox_version_file": ".vbox_version",
      "vm_name": "packer-centos-7-x86_64_{{timestamp}}",
      "generation": 1,
      "enable_secure_boot": false
    }
  ]
}

![image](https://user-images.githubusercontent.com/7714663/97612966-d61ff580-19f6-11eb-92c2-207f9d462df8.png)

![image](https://user-images.githubusercontent.com/7714663/97612919-c86a7000-19f6-11eb-8900-be82fa232396.png)

What's the problem in my configuration?

**Comment by nywilken** [comment]
Hi there @Tomelin thanks for reaching out. I suspect it may be a kickstarter files configuration but can't say for sure. I recommend you take a look at the Chef Bento box Packer templates as they have a working example of Centos7 on hyper-v https://github.com/chef/bento/tree/master/packer_templates/centos

If you end up needing more help with this kind of initial configuration, the mailing list or community forum are generally more useful. Issues opened here on the Packer issue tracker are only viewed by a small handful of developers who work on the tool, and we don't always have the most depth or experience when it comes to custom issues with particular build configurations.


I'm going to close this is issue as it doesn't appear to be a bug in Packer. But if after looking at the examples above or after speaking with folks on the community forum you think this is a Packer bug. Please leave a comment on the thread and we will gladly reopen. Cheers!
