### ISSUE TITLE
Better support of standard environment variables in HCL2

### ISSUE THREAD

**Issue by zfouts** [hashicorp/packer#10187]
Please search the existing issues for relevant feature requests, and use the
reaction feature
(https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
to add upvotes to pre-existing requests.

#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

HCL2 seemingly does not support using standard system environment variables without resetting them to `PKR_VAR_<NEW_ENV>`.

For example, with JSON you can do the following:
```
    "jenkins_build_user": "{{env `BUILD_USER_ID`}}",
```

With the template conversion, it creates the following:
```
variable "jenkins_build_user" {
  type    = string
  default = "${var.BUILD_USER_ID}"
}
```

Results in the following error:
```
Error: Variables not allowed

  on centos7-base.json.pkr.hcl line 51, in variable "jenkins_build_user":
  51:   default = "${var.BUILD_USER_ID}"
```

Variables may not be used here.
#### Use Case(s)

Being able to utilize standard env vars from your system without having to set some packer specific environment variable such as `PKR_VAR_BLAH` would be more than beneficial. 

#### Potential configuration

Potentially allow for a ${env.Foo} setting within the variable block, such as:
```
variable "jenkins_build_user" {
  type    = string
  default = "${env.BUILD_USER_ID}"
}
```

#### Potential References
https://discuss.hashicorp.com/t/hcl2-environment-variables/9290

**Comment by nywilken** [comment]
Hi thanks for reaching out. The `PKR_VAR` prefix is a requirement to ensure proper variable handling in HCL2 enabled templates. @azr did a great job explaining it [here](https://github.com/hashicorp/packer/issues/10152#issuecomment-717154423). 

I'm going to close this issue as it has already been answered. But if you think we can improve the documentation a bit to call out the requirement. Reach out with the suggestion and we will gladly make the update.

**Comment by SwampDragons** [comment]
We spent some time discussing this option internally and decided to reverse course on our decision -- you'll be able to use an env function in HCL once https://github.com/hashicorp/packer/pull/10240 is merged.

**Comment by zfouts** [comment]
Fantastic news!
