### ISSUE TITLE
vsphere-iso could have a special communicator 'vmtools'

### ISSUE THREAD

**Issue by JamesPGriffith** [hashicorp/packer#10194]
#### Description

`vsphere-iso`, `vsphere-clone`, `vmware-clone`, `vmware-iso` could all have make use of a special communicator that uses the VMware ability to use the guest tools to copy files to the guest and execute commands.

#### Use Case(s)

#9924 now allows Packer to continue if the communicator is none for guests that are isolated from the Packer executor. I saw that Docker has its own communicator so I thought that the VMware builder could take advantage of the guest tools to transfer files to a VM in network isolation and execute commands.

#### Potential configuration

I'm not familiar with Golang enough to provide input here or take this on myself. I did look up this documentation though:
https://pkg.go.dev/github.com/vmware/govmomi/guest/toolbox

#### Potential References
https://github.com/hashicorp/packer/issues/9924
https://pkg.go.dev/github.com/vmware/govmomi/guest/toolbox

**Comment by jhawk28** [comment]
This could be done. The downsides of using the guest tools is that you cannot use a sudo user to execute privileged commands. Commands are "fire and forget". Debugging why something went wrong is challenging.

**Comment by JamesPGriffith** [comment]
Excellent point!

I did some quick reading here and line 435-445 has a fairly simple solution:
https://www.lucd.info/2019/11/17/invoke-vmscriptplus-v3/

That made me think that Ansible has the same ability to elevate to sudo. I've not looked at their code for how that works though. Based on the documentation though It's likely **super** complex...  
https://docs.ansible.com/ansible/latest/user_guide/become.html  

---
Alternatively, document and add some in-app warnings concerning the *assumption* that the user defined has permission to sudo `this` or `any` command.
https://communities.vmware.com/thread/525530

Logging the command's raw output would be helpful to troubleshoot this scenario too. I'm still fairly new to Packer so that may already exist at a high level or simply be part of the communicator-to-be.
