### ISSUE TITLE
use multiple networks on vmware-iso 

### ISSUE THREAD

**Issue by ptulpen** [hashicorp/packer#10195]
Hello,
I would like to create Vms with multiple networks
I already have seen that ths was implemented for vsphere-iso, see https://github.com/hashicorp/packer/pull/8739
But why is this not implemented with vmware-iso

Best regards, Peter

**Comment by nywilken** [comment]
Hi there, thanks for reaching out. I am unsure if we will have time to work on this any time soon but it sounds like a nice feature to have in place. PRs are welcomed if you are interested in adding support for multiple networks.
