### ISSUE TITLE
remote_path not working in amazon-ebs

### ISSUE THREAD

**Issue by dhruv-malik-ptc** [hashicorp/packer#10205]
packer --version 1.4.2

I have this code in my json file:

{
  "builders": [{
    "type": "amazon-ebs",
    "region": "ap-southeast-2",
    "source_ami": "ami-zzxcvbnm",
    "instance_type": "t2.micro",
    "ssh_username": "ec2-user",
    "ssh_timeout": "15m",
    "iam_instance_profile": "ami-factory",
    "ami_name": "packer-al2-ami-{{timestamp}}"
  }],  "provisioners": [
   {
      "type": "shell-local",
      "command": "tar cf ../packer-salt-ec2-user-ami.tar ../centosami-oldcis"
   },
   {
      "type": "file",
      "source": "../packer-salt-ec2-user-ami.tar",
      "destination": "/home/ec2-user/packer-salt-ec2-user-ami.tar"
   },
   {
      "type": "shell",
      "script": "provision.sh",
      "remote_file": "abc.sh",
      "remote_path":  "/opt/"
   }  ]
}
 

My /tmp has noexec on it, I am hardening the AMI..

Even with the remote_path set, the script is still being executed in /tmp

==> amazon-ebs: Running local shell script: /tmp/packer-shell380358367
==> amazon-ebs: /bin/sh: /tmp/packer-shell380358367: Permission denied

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out! That log excerpt is from the "shell-local" provisioner, so I think you're looking in the wrong place in the logs. Can you re-run your build with the env var PACKER_LOG=1 and collect and share the logs in their entirety please?

**Comment by nywilken** [comment]
Hello there, I'm going to close this issue since there hasn't been any updates since @SwampDragons last comment. 

If your are still running into issues please reach out with the requested information and we will gladly review.
