### ISSUE TITLE
QEMU: drive with bus=0, unit=0 (index=0) exists

### ISSUE THREAD

**Issue by Wenzel** [hashicorp/packer#10211]
#### Overview of the Issue

Packer QEMU builder fails with `index(0) exists` error message.
![Capture d’écran de 2020-11-03 15-18-05](https://user-images.githubusercontent.com/964610/97996280-d8fc5b00-1de7-11eb-8af2-de252a8d27ca.png)

Removing the index specification from the command line works though.

#### Reproduction Steps

- download this repo at `packer_fixed` branch: https://github.com/Wenzel/packer-templates/tree/packer_fixed
- `packer build -var-file winxp.json -only qemu windows.json` 

### Packer version

Packer 1.6.5

### Simplified Packer Buildfile

See https://github.com/Wenzel/packer-templates/tree/packer_fixed

### Operating system and Environment details

OS: Ubuntu 20.04
Qemu: 4.2.1

### Log Fragments and crash.log files

[packer.log](https://gist.github.com/Wenzel/91f97b116a75d70e03ab56b0e3d61e7d)

Thanks !

**Comment by amaczuga** [comment]
This will break qemu any time there is disk_interface: ide. 

This affects Packer releases 1.6.3~1.6.5

Thank you for your support!

**Comment by SwampDragons** [comment]
Thanks -- we'll fix this for the next release.

**Comment by Wenzel** [comment]
Packer `v1.6.6` didn't seem to fix the issue here, still got a repro.

**Comment by SwampDragons** [comment]
Ok, sorry about that. We merged another fix and I mixed the issues up in the milestone. I've retargeted this for the 1.7 release

**Comment by digikin** [comment]
Does nightly have the fix since it was released 14 days ago?

**Comment by SwampDragons** [comment]
Nightly doesn't have it; sorry it took so long to fix but you can pull down test binaries from the linked PR's "store_artifacts" job (link here: https://app.circleci.com/pipelines/github/hashicorp/packer/8822/workflows/a5783040-d2e5-44d2-8a40-e06a7c903d32/jobs/104254/artifacts)

**Comment by Hexawolf** [comment]
Observing similar problem on Packer 1.6.6 when trying to run qemu-system-aarch64, using `"disk_interface": "virtio"`:

```
2021/02/12 13:58:26 packer-builder-qemu plugin: Executing /usr/bin/qemu-system-aarch64: []string{"-device", "virtio-net,netdev=user.0,id=user.0,mac=52:54:00:27:XX:XX,bus=pci.0,addr=0x3", "-name", "debian10arm64-aarch64-build.qcow2", "-machine", "type=virt,accel=kvm", "-m", "8192M", "-drive", "file=output/debian10arm64-aarch64-build/debian10arm64-aarch64-build.qcow2,if=virtio,cache=writeback,discard=unmap,format=qcow2,detect-zeroes=unmap", "-drive", "file=/home/XXX/XXX/packer/packer_cache/5f955a9967732c158XXXXXXXXXXXXXXXXXXXXXXX.iso,index=0,media=cdrom", "-vnc", "127.0.0.1:36", "-smp", "cpus=4,sockets=4", "-boot", "once=d", "-netdev", "user,id=user.0,hostfwd=tcp::3947-:22"}
==> debian10arm64-aarch64-build: Overriding default Qemu arguments with qemuargs template option...
2021/02/12 13:58:26 packer-builder-qemu plugin: Started Qemu. Pid: 352XXX
2021/02/12 13:58:26 packer-builder-qemu plugin: Qemu stderr: qemu-system-aarch64: -drive file=/home/XXX/devboxes/packer/packer_cache/5f955a9967732c158XXXXXXXXXXXXXXXXXXXXXXX.iso,index=0,media=cdrom: drive with bus=0, unit=0 (index=0) exists
==> debian10arm64-aarch64-build: Error launching VM: Qemu failed to start. Please run with PACKER_LOG=1 to get more info.
```
