### ISSUE TITLE
vsphere-iso unable to set vhv.enable configuration_parameter

### ISSUE THREAD

**Issue by corrigat** [hashicorp/packer#10215]
#### Overview of the Issue

Using HCL against vSphere 6.7.0 build 16046713 and ESXi 6.7.0 build 16075168 as an administrative userr, I'm unable to set vhv.enable = "TRUE" in vmx config using configuration_parameters while other configuration options do work.

This is super weird and I'm struggling to determine any difference, other than the vhv.enable setting, between vmx files when the setting is applied manually. My thought was to check if there were other dependent settings and validate the name of the setting, but from what I found is this should be correct.

Here is the vmx after StepConfigParams
https://gist.github.com/corrigat/649f41f64f567c11d2714366d813f5df

Here is the vmx after StepRun
https://gist.github.com/corrigat/c2613ac51bd2aa6c1e1da0e56eebba53

I also have a quiet vsphere 7.0 setup at home where this occurs and can provide logs if it would be any help. I checked hostd.log but the reconfigure task section shows nothing added/changed/deleted: https://gist.github.com/corrigat/8a3ee0099999059ae43dc2cc42e09638

Also, I've found that before vmx_data was moved to configuration_parameters, this seems to have worked: https://github.com/hashicorp/packer/issues/8998

#### Reproduction Steps

With a basic template (I'm using CentOS), include configuration_parameters
```hcl    
configuration_parameters = {
      "featMask.vm.hv.capable" = "Min:1"
      "vhv.enable" = "TRUE"
}
```
and build the machine.

* featMask.vm.hv.capable in this case will be present in the vmx configuration file, however, vhv.enable will not be present during or after the build.
* When featmask.vm.vh.capable is removed, leaving only vhv.enable, the vhv.enable setting will still be absent during and after the build.

### Packer version

1.6.5

### Simplified Packer Buildfile
```hcl
source "vsphere-iso" "centos7-base" {
    # vCenter settings
    vcenter_server           = var.vcenter_server
    username                 = var.vcenter_username
    password                 = var.vcenter_password
    insecure_connection      = true
    cluster                  = var.vcenter_cluster
    datacenter               = var.vcenter_datacenter
    #host                     = var.vcenter_host
    datastore                = var.vcenter_datastore
    convert_to_template      = false
    folder                   = var.vcenter_folder
    configuration_parameters = {
      "featMask.vm.hv.capable" = "Min:1"
      "vhv.enable" = "TRUE"
    }

    # VM Settings
    ip_wait_timeout          = "45m"
    ssh_username             = var.connection_username
    ssh_password             = var.connection_password
    ssh_timeout              = "12h"
    ssh_port                 = "22"
    ssh_handshake_attempts   = "20"
    shutdown_timeout         = "15m"
    vm_version               = var.vm_hardware_version
    iso_paths                = [var.os_iso_path]
    iso_checksum             = var.iso_checksum
    vm_name                  = var.vm_name
    guest_os_type            = var.guest_os_type
    disk_controller_type     = ["pvscsi"]
    floppy_files             = ["boot_config/ks.cfg"]
    network_adapters {
      network                = var.vm_network
      network_card           = var.nic_type
    }
    storage {
      disk_size              = var.root_disk_size
      disk_thin_provisioned  = true
    }
    CPUs                     = var.num_cpu
    cpu_cores                = var.num_cores
    RAM                      = var.vm_ram
    boot_wait                = "5s"
    boot_command             = var.boot_command
  }
```

### Operating system and Environment details

packer executed from MacOS 10.15.7

### Log Fragments and crash.log files

Logs do not appear to emit messages regarding success or failure of the configuration_parameter step, no other errors in the output.

**Comment by nywilken** [comment]
Thanks for reaching out. We’ll take a look when we get a chance.

**Comment by Borkason** [comment]
@nywilken The entire `configuration_parameters` is completely broken. The docs state that the API is called. That is the API: https://code.vmware.com/apis/358/vsphere/doc/vim.vm.ConfigSpec.html

According to the docs you should be able to enable nested virtualization by passing this to the API.

```json
"configuration_parameters": {
    "nestedHVEnabled":true 
}
```

However, this just writes nestedHVEnabled = "1" into the vmx file, which is wrong and does not enable VHV/NestedHV.

You can also do this

```json
"configuration_parameters": {
    "aaa":"aaa"
}
```

and packer will write `aaa = "aaa"` into the vmx file.

So why does 

```json
"configuration_parameters": {
    "vhv.enable": true
}
```

not write that setting into the vmx file?

The API docs also state that there is `extraConfig` and as far as I understand this is for passing any key-value pair, whether it is officially supported or not, directly to the vmx file.

It looks to me like `configuration_parameters` does not follow that API at all, but Packer does some random stuff with it that is not documented on the Packer docs anywhere.

**Comment by Borkason** [comment]
Found the issue. You must use `NestedHV=true` in your config. The default is false, which takes precedence over `"vhv.enable": true`.

**Comment by SwampDragons** [comment]
ooh good catch. 

I wonder if we should document this as a "gotcha" on the vsphere docs page.

**Comment by Borkason** [comment]
The deeper issue is that the vsphere builder implemented custom types instead of using the govmomi SDK at its fullest. This would not have happened with the SDK provided types. I opened an issue for that: https://github.com/hashicorp/packer/issues/10271

**Comment by corrigat** [comment]
Apologies for the silence, it's been an incredibly busy year. I confirmed the ability to expose virtualization capabilities to guests with the NestedHV = true option alongside the rest of the VM's configuration for CPU, Memory, etc. I [made a gist](https://gist.github.com/corrigat/91bd21f8e65eb74300417fc39b1da4c7) in case any more internet wanderers come across the thread.
I also now notice NestedHV in the vsphere-iso documentation. It's been so long since I've written out a template with vmx_data that I didn't think to go looking for a regular directive. Thanks so much for taking the time to respond and clarify!
