### ISSUE TITLE
Boot only install OS

### ISSUE THREAD

**Issue by laodc** [hashicorp/packer#10214]
Please search the existing issues for relevant feature requests, and use the
reaction feature
(https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
to add upvotes to pre-existing requests.

#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

The ability to run packer to only boot/install OS on existing VM.

#### Use Case(s)

I create VMs on vsphere using Terraform, after completed, i want to run Packer with preseed to install the OS on the new VM.
Currently I haven't been able to find any method to achieve this (please prove me wrong)

#### Potential configuration

```
```

**Comment by SwampDragons** [comment]
Normally we suggest doing this the other way around -- use Packer to install an os on a new VM, then use teraform to launch that VM.

**Comment by george-vieira** [comment]
I also would like the have the ability to have terraform build my whole infrastructure and vms then have packer install the OS. There's an overlap there between the two and I only need packer to start the instance and install the OS.

Packer has no sense of statefulness afaik, so can't have packer as main process in a CI/CD pipeline where terraform knows what is deployed and what has no and initiate a build for those new instances, then launches packer when needed.

**Comment by trodemaster** [comment]
I have built a system to do this but it required nested virtualization to be enabled. You need to start with a VM that can run VMs inside of itself. Deploy that with terraform and then have terraform trigger a build via remote shell or config management tooling inside that vm. It's doable but I would not do this again and instead would look at other automation tools to drive packer builds directly on the newer vsphere builder.

**Comment by tenthirtyam** [comment]
Recommend closure.

@nywilken

**Comment by lbajolet-hashicorp** [comment]
Thanks @tenthirtyam, looks stale indeed, will close now.
