### ISSUE TITLE
multiregion build fails with KMS

### ISSUE THREAD

**Issue by nwalter82** [hashicorp/packer#10233]
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

Looking to reopen 9247 as I came across this today.

https://github.com/hashicorp/packer/issues/9427#issue-639512591

#### Reproduction Steps
Multi-region packer build with CMK KMS key, both regions using same key alias name.

leaving out kms_key_id per documentation generates error * Cannot share AMI encrypted with default KMS key

adding       "kms_key_id" : "alias/keyalias", fixes the issue and builds happen correctly and are deployed correctly.

Seems overall the code uses the correct keys, it's just a file verification check that fails as the error occurs immediately when trying to build the image (same as a file syntax error etc.).

### Packer version

From `packer version`

### Simplified Packer Buildfile

"builders": [
    {
      "type": "amazon-ebs",
      "access_key": "{{user `aws_access_key`}}",
      "secret_key": "{{user `aws_secret_key`}}",
      "source_ami": "{{user `amibase`}}",
      "instance_type": "m5.xlarge",
      "ssh_username": "ec2-user",
      "ssh_interface": "session_manager",
      "ami_name": "{{user `namebase`}}-{{timestamp}}",
      "ami_users": "123456789",
      "ami_regions": ["us-west-2","us-east-2"],
      "iam_instance_profile": "profile1",
      "encrypt_boot": true,
      "region_kms_key_ids": {
        "us-west-2": "alias/keyalias",
        "us-east-2": "alias/keyalias"
      },

### Operating system and Environment details

MacOS

**Comment by nywilken** [comment]
Hi there @nwalter82 thanks for reaching out. We will try to take a look when we get a chance. In the meantime, can you please provide the version of Packer you are using along with debug logs `PACKER_LOG=1 packer build <template>`

**Comment by nwalter82** [comment]
`2020/11/09 09:46:03 [INFO] Packer version: 1.6.5 [go1.15.3 darwin amd64]
2020/11/09 09:46:03 Checking 'PACKER_CONFIG' for a config file path
2020/11/09 09:46:03 'PACKER_CONFIG' not set; checking the default config file path
2020/11/09 09:46:03 Attempting to open config file: /Users//.packerconfig
2020/11/09 09:46:03 [WARN] Config file doesn't exist: /Users//.packerconfig
2020/11/09 09:46:03 Setting cache directory: /Users/.nosync/infrastructure/packer_cache
2020/11/09 09:46:03 Creating plugin client for path: /usr/local/bin/packer
2020/11/09 09:46:03 Starting plugin: /usr/local/bin/packer []string{"/usr/local/bin/packer", "plugin", "packer-builder-amazon-ebs"}
2020/11/09 09:46:03 Waiting for RPC address for: /usr/local/bin/packer
2020/11/09 09:46:03 packer-builder-amazon-ebs plugin: [INFO] Packer version: 1.6.5 [go1.15.3 darwin amd64]
2020/11/09 09:46:03 packer-builder-amazon-ebs plugin: Checking 'PACKER_CONFIG' for a config file path
2020/11/09 09:46:03 packer-builder-amazon-ebs plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/11/09 09:46:03 packer-builder-amazon-ebs plugin: Attempting to open config file: /Users/.packerconfig
2020/11/09 09:46:03 packer-builder-amazon-ebs plugin: Setting cache directory: /Users//Documents/WB/Code/GIT.nosync/infrastructure/packer_cache
2020/11/09 09:46:03 packer-builder-amazon-ebs plugin: args: []string{"packer-builder-amazon-ebs"}
2020/11/09 09:46:03 packer-builder-amazon-ebs plugin: Plugin address: unix /var/folders/tw/lclgwfd17gs3zycp8kvyb0jr0000gn/T/packer-plugin875933619
2020/11/09 09:46:03 packer-builder-amazon-ebs plugin: Waiting for connection...
2020/11/09 09:46:03 Received unix RPC address for /usr/local/bin/packer: addr is /var/folders/tw/lclgwfd17gs3zycp8kvyb0jr0000gn/T/packer-plugin875933619
2020/11/09 09:46:03 packer-builder-amazon-ebs plugin: Serving a plugin connection...
2020/11/09 09:46:03 Creating plugin client for path: /usr/local/bin/packer
2020/11/09 09:46:03 Starting plugin: /usr/local/bin/packer []string{"/usr/local/bin/packer", "plugin", "packer-provisioner-file"}
2020/11/09 09:46:03 Waiting for RPC address for: /usr/local/bin/packer
2020/11/09 09:46:03 packer-provisioner-file plugin: [INFO] Packer version: 1.6.5 [go1.15.3 darwin amd64]
2020/11/09 09:46:03 packer-provisioner-file plugin: Checking 'PACKER_CONFIG' for a config file path
2020/11/09 09:46:03 packer-provisioner-file plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/11/09 09:46:03 packer-provisioner-file plugin: Attempting to open config file: /Users//.packerconfig
2020/11/09 09:46:03 packer-provisioner-file plugin: [WARN] Config file doesn't exist: /Users//.packerconfig
2020/11/09 09:46:03 packer-provisioner-file plugin: Setting cache directory: /Users//Documents/WB/Code/GIT.nosync/infrastructure/packer_cache
2020/11/09 09:46:03 packer-provisioner-file plugin: args: []string{"packer-provisioner-file"}
2020/11/09 09:46:03 packer-provisioner-file plugin: Plugin address: unix /var/folders/tw/lclgwfd17gs3zycp8kvyb0jr0000gn/T/packer-plugin369598639
2020/11/09 09:46:03 packer-provisioner-file plugin: Waiting for connection...
2020/11/09 09:46:03 Received unix RPC address for /usr/local/bin/packer: addr is /var/folders/tw/lclgwfd17gs3zycp8kvyb0jr0000gn/T/packer-plugin369598639
2020/11/09 09:46:03 packer-provisioner-file plugin: Serving a plugin connection...
2020/11/09 09:46:03 Creating plugin client for path: /usr/local/bin/packer
2020/11/09 09:46:03 Starting plugin: /usr/local/bin/packer []string{"/usr/local/bin/packer", "plugin", "packer-provisioner-shell"}
2020/11/09 09:46:03 Waiting for RPC address for: /usr/local/bin/packer
2020/11/09 09:46:04 packer-provisioner-shell plugin: [INFO] Packer version: 1.6.5 [go1.15.3 darwin amd64]
2020/11/09 09:46:04 packer-provisioner-shell plugin: Checking 'PACKER_CONFIG' for a config file path
2020/11/09 09:46:04 packer-provisioner-shell plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/11/09 09:46:04 packer-provisioner-shell plugin: Attempting to open config file: /Users//.packerconfig
2020/11/09 09:46:04 packer-provisioner-shell plugin: [WARN] Config file doesn't exist: /Users//.packerconfig
2020/11/09 09:46:04 packer-provisioner-shell plugin: Setting cache directory: /Users//Documents//GIT.nosync/infrastructure/packer_cache
2020/11/09 09:46:04 packer-provisioner-shell plugin: args: []string{"packer-provisioner-shell"}
2020/11/09 09:46:04 packer-provisioner-shell plugin: Plugin address: unix /var/folders/tw/lclgwfd17gs3zycp8kvyb0jr0000gn/T/packer-plugin936311075
2020/11/09 09:46:04 packer-provisioner-shell plugin: Waiting for connection...
2020/11/09 09:46:04 Received unix RPC address for /usr/local/bin/packer: addr is /var/folders/tw/lclgwfd17gs3zycp8kvyb0jr0000gn/T/packer-plugin936311075
2020/11/09 09:46:04 packer-provisioner-shell plugin: Serving a plugin connection...
2020/11/09 09:46:04 Creating plugin client for path: /usr/local/bin/packer
2020/11/09 09:46:04 Starting plugin: /usr/local/bin/packer []string{"/usr/local/bin/packer", "plugin", "packer-provisioner-shell"}
2020/11/09 09:46:04 Waiting for RPC address for: /usr/local/bin/packer
2020/11/09 09:46:04 packer-provisioner-shell plugin: [INFO] Packer version: 1.6.5 [go1.15.3 darwin amd64]
2020/11/09 09:46:04 packer-provisioner-shell plugin: Checking 'PACKER_CONFIG' for a config file path
2020/11/09 09:46:04 packer-provisioner-shell plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/11/09 09:46:04 packer-provisioner-shell plugin: Attempting to open config file: /Users//.packerconfig
2020/11/09 09:46:04 packer-provisioner-shell plugin: [WARN] Config file doesn't exist: /Users//.packerconfig
2020/11/09 09:46:04 packer-provisioner-shell plugin: Setting cache directory: /Users//Documents/WB/Code/GIT.nosync/infrastructure/packer_cache
2020/11/09 09:46:04 packer-provisioner-shell plugin: args: []string{"packer-provisioner-shell"}
2020/11/09 09:46:04 packer-provisioner-shell plugin: Plugin address: unix /var/folders/tw/lclgwfd17gs3zycp8kvyb0jr0000gn/T/packer-plugin256625511
2020/11/09 09:46:04 packer-provisioner-shell plugin: Waiting for connection...
2020/11/09 09:46:04 Received unix RPC address for /usr/local/bin/packer: addr is /var/folders/tw/lclgwfd17gs3zycp8kvyb0jr0000gn/T/packer-plugin256625511
2020/11/09 09:46:04 packer-provisioner-shell plugin: Serving a plugin connection...
2020/11/09 09:46:04 Creating plugin client for path: /usr/local/bin/packer
2020/11/09 09:46:04 Starting plugin: /usr/local/bin/packer []string{"/usr/local/bin/packer", "plugin", "packer-post-processor-manifest"}
2020/11/09 09:46:04 Waiting for RPC address for: /usr/local/bin/packer
2020/11/09 09:46:04 packer-post-processor-manifest plugin: [INFO] Packer version: 1.6.5 [go1.15.3 darwin amd64]
2020/11/09 09:46:04 packer-post-processor-manifest plugin: Checking 'PACKER_CONFIG' for a config file path
2020/11/09 09:46:04 packer-post-processor-manifest plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/11/09 09:46:04 packer-post-processor-manifest plugin: Attempting to open config file: /Users//.packerconfig
2020/11/09 09:46:04 packer-post-processor-manifest plugin: [WARN] Config file doesn't exist: /Users//.packerconfig
2020/11/09 09:46:04 packer-post-processor-manifest plugin: Setting cache directory: /Users//Documents/WB/Code/GIT.nosync/infrastructure/packer_cache
2020/11/09 09:46:04 packer-post-processor-manifest plugin: args: []string{"packer-post-processor-manifest"}
2020/11/09 09:46:04 packer-post-processor-manifest plugin: Plugin address: unix /var/folders/tw/lclgwfd17gs3zycp8kvyb0jr0000gn/T/packer-plugin196785539
2020/11/09 09:46:04 packer-post-processor-manifest plugin: Waiting for connection...
2020/11/09 09:46:04 Received unix RPC address for /usr/local/bin/packer: addr is /var/folders/tw/lclgwfd17gs3zycp8kvyb0jr0000gn/T/packer-plugin196785539
2020/11/09 09:46:04 packer-post-processor-manifest plugin: Serving a plugin connection...
2020/11/09 09:46:04 Preparing build: amazon-ebs
2020/11/09 09:46:04 packer-builder-amazon-ebs plugin: [INFO] (aws): No AWS timeout and polling overrides have been set. Packer will default to waiter-specific delays and timeouts. If you would like to customize the length of time between retries and max number of retries you may do so by setting the environment variables AWS_POLL_DELAY_SECONDS and AWS_MAX_ATTEMPTS or the configuration options aws_polling_delay_seconds and aws_polling_max_attempts to your desired values.
2020/11/09 09:46:04 Build 'amazon-ebs' prepare failure: 1 error(s) occurred:

* Cannot share AMI encrypted with default KMS key

1 error(s) occurred:

* Cannot share AMI encrypted with default KMS key

2020/11/09 09:46:04 Build debug mode: false
2020/11/09 09:46:04 Force build: false
2020/11/09 09:46:04 On error: 
2020/11/09 09:46:04 Waiting on builds to complete...
Error: Failed to prepare build: "amazon-ebs"

==> Wait completed after 5 microseconds
==> Builds finished but no artifacts were created.
2020/11/09 09:46:04 [INFO] (telemetry) Finalizing.
1 error(s) occurred:`

**Comment by nwalter82** [comment]
It looks like your problem is likely here:
https://github.com/hashicorp/packer/blob/8b4993e44c9fa523c4ce692c3a0392087e0813c1/builder/amazon/common/ami_config.go#L189

You are not accounting for RegionKeyIds being set that I can see (b.config.AMIRegionKMSKeyIDs)
https://github.com/hashicorp/packer/blob/efc117fb55f1a6810b5cd943f0263ddde6dede29/builder/amazon/ebs/builder.go#L328

**Comment by SwampDragons** [comment]
Thanks for pointing this out. For now it looks like a workaround might be to add your build region's kms key id from the AMIRegionKMSKeyIDs map to the AMIKmsKeyId option as well.

**Comment by kwyatt** [comment]
@SwampDragons // @sylviamoss is this going to make 1.7.1?

**Comment by SwampDragons** [comment]
Yes.
