### ISSUE TITLE
Running a HCL Packer image in Devops Pipeline

### ISSUE THREAD

**Issue by jparr93** [hashicorp/packer#10237]
# ## Overview of the Issue

I can run a packer build locally from my machine in VS Code. I have a Gold-build.pkr.hcl and variables.pkr.hcl file. I run this build by "packer build .\" this works and builds an image.

However, within a Devops pipeline, i point the template location to the gold-build file and the variables file to the variables.pkr file.

This gives me the error

2020-11-10T11:27:32.4587173Z   on D:\a\r1\a\_spring2020-automation-CI\drop\Terraform\packer\variables.pkr.hcl line 5, in variable "managed_image_name":
2020-11-10T11:27:32.4588881Z    5: variable "managed_image_name"{
2020-11-10T11:27:32.4589225Z 
2020-11-10T11:27:32.4589650Z A .pkrvar file is used to assign values to variables that have already been
2020-11-10T11:27:32.4590274Z declared in .pkr files, not to declare new variables. To declare variable
2020-11-10T11:27:32.4590917Z "managed_image_name", place this block in one of your .pkr files, such as
2020-11-10T11:27:32.4591400Z variables.pkr.hcl
2020-11-10T11:27:32.4591662Z 

See the attached for my release pipeline.

![packerbuild](https://user-images.githubusercontent.com/62067573/98669026-abb02f80-2348-11eb-8785-a4f79e688230.png)

**Comment by azr** [comment]
Hey @jparr93, thanks for opening; the error states that at the top of your variable file there is the following block declation:
```
variable "managed_image_name"{
```

And this cannot be inside of a variable hcl file; have you checked the contents of that file ?

**Comment by jparr93** [comment]
@azr thank you for the reply, however it actually errors on all the variables in the variables.pkr.hcl file. These files do work running them in VS Code

**Comment by azr** [comment]
@jparr93, I trust that error. It's here to help you too 🙂 . Is there a way to `cat` or `head` the contents of `variables.pkr.hcl` & `Gold-build.pkr.hcl` before you run anything ? 

I'm sorry I'm repeating myself a lot but `variables.pkr.hcl` should contain only variable settings so stuff like: `managed_image_name = "value"`. That error is displayed because we found a variable declaration ( `variable "managed_image_name"{`.

**Comment by jparr93** [comment]
@azr  not sure on the cat or head. So, if i change the variable.pkr.hcl file to contain variable = "value", should this work, or will i need another file declaring that there are variables?

**Comment by vheon** [comment]
> I'm sorry I'm repeating myself a lot but variables.pkr.hcl should contain only variable settings so stuff like: managed_image_name = "value". That error is displayed because we found a variable declaration ( variable "managed_image_name"{.

@azr I'm sorry to burge in but the docs https://www.packer.io/guides/hcl/variables says to put variable declaration in `variables.pkr.hcl` and the values in some `variables.pkrvars.hcl`. I have it like that and in fact works just fine 😕

**Comment by jparr93** [comment]
> > I'm sorry I'm repeating myself a lot but variables.pkr.hcl should contain only variable settings so stuff like: managed_image_name = "value". That error is displayed because we found a variable declaration ( variable "managed_image_name"{.
> 
> @azr I'm sorry to burge in but the docs https://www.packer.io/guides/hcl/variables says to put variable declaration in `variables.pkr.hcl` and the values in some `variables.pkrvars.hcl`. I have it like that and in fact works just fine 😕

Like i said, my code works fine, it's when i try running it through a Devops pipeline, it errors. I do suspect that the Packer add on for DevOps doesnt support HCL yet, see my screengrab below? It is wanting a JSON file still
![packdevops](https://user-images.githubusercontent.com/62067573/98683355-d7d5ab80-235c-11eb-841a-9e119d438656.png)

**Comment by azr** [comment]
> @azr I'm sorry to burge in but the docs https://www.packer.io/guides/hcl/variables says to put variable declaration in variables.pkr.hcl and the values in some variables.pkrvars.hcl. I have it like that and in fact works just fine 😕

@vheon 👋🏼  ehm yes, that's how it should be 🙂 , that doc statement is correct and I'm just saying the same thing here.

@jparr93:

> Like i said, my code works fine, it's when i try running it through a Devops pipeline, it errors. I do suspect that the Packer add on for DevOps doesnt support HCL yet, see my screengrab below? It is wanting a JSON file still

Does it work to pass the folder instead of the configuration file ? So in packer template location, pass `".../Terraform/packer/"` Packer should list all `.pkr.hcl` files. the `.pkrvcars.hcl` variables file setting should just work here.

**Comment by azr** [comment]
Also, if the tool only wants JSON files: it's not so nice but you _can_ set variable files through JSON. So for example in `.pkrvars.json`:

```
{
  "variable_name": "value"
}
```

**Comment by jparr93** [comment]
@azr worked when specifying the auto,pkrvars file, thank you :) having a weird issue now where it can't find the scripts to run during build, even though they are in the root of where the template is

**Comment by azr** [comment]
@jparr93 great news ! There are path variables you could use to make things more relative to the directory of the build https://www.packer.io/docs/from-1.5/path-variables

**Comment by jparr93** [comment]
@azr so it would be something like path.root\script.ps1

**Comment by azr** [comment]
more something like: `key = "${path.root}/script.ps1"`
