### ISSUE TITLE
Packer Winrm returns '401 - invalid content type' while ansible can connect to the packer VM.

### ISSUE THREAD

**Issue by shadowink** [hashicorp/packer#10264]
#### Overview of the Issue

I've hit a bug in packer using the WinRM communicator with the vsphere-clone builder.  When Packer spins up the VM it cannot connect via WinRM.  If I create an ansible inventory with the VM IP and credentials, then ansible can directly connect to the VM packer created.

The VM I am using as a template in vcenter has WinRM setup and configured correctly for our domain.  WinRM was setup by running 
ConfigureRemotingForAnsible.ps1  -EnableCredSSP -DisableBasicAuth
and disabling HTTP with
winrm delete winrm/config/Listener?Address=*+Transport=HTTP

#### Reproduction Steps

1. Create template VM, verify WinRM works, shut VM down.  Named win-kpc-packer.
2.  run packer:  PACKER_LOG=1 packer build -on-error=ask mypacker.json
3.  Wait for packer to report the VM IP:
==> vsphere-clone: Using winrm communicator to connect: 10.17.3.2
4. Wait for WinRM to come up and packer to try to connect to it

> 2020/11/16 15:20:04 packer-builder-vsphere-clone plugin: [INFO] Attempting WinRM connection...
> 2020/11/16 15:20:04 packer-builder-vsphere-clone plugin: [DEBUG] connecting to remote shell using WinRM
> 2020/11/16 15:20:04 packer-builder-vsphere-clone plugin: [ERROR] connection error: http response error: 401 - invalid content type
> 2020/11/16 15:20:04 packer-builder-vsphere-clone plugin: [ERROR] WinRM connection err: http response error: 401 - invalid content type
> 

5.  While packer repeatedly tries and fails to connect to the VM, create an ansible inventory file targeting the VM:
all:
  hosts:
    10.17.3.2:
      ansible_user: VMADMINACCT
      ansible_password: VMADMINPASS
      ansible_connection: winrm
      ansible_winrm_transport: credssp
      ansible_winrm_server_cert_validation: ignore

6.  Use ansible to connect to the VM via ansible:
ansible -i mypacker.yml -m setup all -vvvv

https://gist.github.com/shadowink/a0aeee534418a0ce7baee859059e76d1#file-mypacker-yml

The packer build will continue to loop through failed connections with the 401 error until the build times out.  During this time, ansible can connect to the machine directly and will return the json of a successful setup run.

### Packer version

1.6.5

### Simplified Packer Buildfile

https://gist.github.com/shadowink/a0aeee534418a0ce7baee859059e76d1#file-mypacker-json

### Operating system and Environment details

VM is Windows 10 Pro.  Packer and ansible are being run on MacOS Catalina 10.15.7

Ansible is v2.10.1

### Log Fragments and crash.log files
==> vsphere-clone: Waiting for WinRM to become available...

2020/11/16 15:18:54 packer-builder-vsphere-clone plugin: [INFO] Attempting WinRM connection...
2020/11/16 15:18:54 packer-builder-vsphere-clone plugin: [DEBUG] connecting to remote shell using WinRM
2020/11/16 15:19:24 packer-builder-vsphere-clone plugin: [ERROR] connection error: unknown error Post "https://10.17.3.234:5986/wsman": dial tcp 10.17.3.234:5986: i/o timeout
2020/11/16 15:19:24 packer-builder-vsphere-clone plugin: [ERROR] WinRM connection err: unknown error Post "https://10.17.3.234:5986/wsman": dial tcp 10.17.3.234:5986: i/o timeout
2020/11/16 15:19:29 packer-builder-vsphere-clone plugin: [INFO] Attempting WinRM connection...
2020/11/16 15:19:29 packer-builder-vsphere-clone plugin: [DEBUG] connecting to remote shell using WinRM
2020/11/16 15:19:59 packer-builder-vsphere-clone plugin: [ERROR] connection error: unknown error Post "https://10.17.3.234:5986/wsman": dial tcp 10.17.3.234:5986: i/o timeout
2020/11/16 15:19:59 packer-builder-vsphere-clone plugin: [ERROR] WinRM connection err: unknown error Post "https://10.17.3.234:5986/wsman": dial tcp 10.17.3.234:5986: i/o timeout
2020/11/16 15:20:04 packer-builder-vsphere-clone plugin: [INFO] Attempting WinRM connection...
2020/11/16 15:20:04 packer-builder-vsphere-clone plugin: [DEBUG] connecting to remote shell using WinRM
2020/11/16 15:20:04 packer-builder-vsphere-clone plugin: [ERROR] connection error: http response error: 401 - invalid content type
2020/11/16 15:20:04 packer-builder-vsphere-clone plugin: [ERROR] WinRM connection err: http response error: 401 - invalid content type
2020/11/16 15:20:09 packer-builder-vsphere-clone plugin: [INFO] Attempting WinRM connection...
2020/11/16 15:20:09 packer-builder-vsphere-clone plugin: [DEBUG] connecting to remote shell using WinRM
2020/11/16 15:20:10 packer-builder-vsphere-clone plugin: [ERROR] connection error: http response error: 401 - invalid content type
2020/11/16 15:20:10 packer-builder-vsphere-clone plugin: [ERROR] WinRM connection err: http response error: 401 - invalid content type

**Comment by nywilken** [comment]
Hello there @shadowink I notice that in your ansible inventory file, which you use to connect use to validate the connection, that you are setting `ansible_winrm_server_cert_validation=ignore`. But that setting is not in the Packer configuration. If you are using a self signed that option also needs to be passed within the `extra_argruments` configuration option. https://www.packer.io/docs/provisioners/ansible#method-1-recommended

Does adding `"extra_arguments": ["-e", "ansible_winrm_server_cert_validation=ignore"]` to the provisioner block resolve the issue for you?

**Comment by shadowink** [comment]
Adding that line to the the provisioner block doesn't solve the problem.
