### ISSUE TITLE
Regression from PR 9513: ssh_private_key_file not documented for vsphere-iso builder

### ISSUE THREAD

**Issue by jpbuecken** [hashicorp/packer#10263]
#### Overview of the Issue

The PR https://github.com/hashicorp/packer/pull/9513/ removed ssh_private_key_file from the vsphere-iso builder documentation.
That is wrong: The builder does support ssh_private_key_file!

Use case: If you build with Redhat kickstart / Suse autoyast or Ubuntu preseeded installation, there is no need to specifiy a (maybe unsecure) password, you just can add a public key. E.g. no need to have a default password in your version control system/git.

#### Reproduction Steps

Read the documentation
Use ssh_private_key_file with the vsphere-iso builder. It works

### Packer version
v1.6.2

**Comment by adeniyistephen** [comment]
@SwampDragons I would love to work on this, Please provide pointers and input on how to work on it. Thanks

**Comment by sylviamoss** [comment]
Hi @adeniyistephen, great to hear you'd like to contribute.
You just need to add the include for the [SSH-Private-Key-File-not-required.mdx](https://github.com/hashicorp/packer/blob/master/website/pages/partials/helper/communicator/SSH-Private-Key-File-not-required.mdx) to the vsphere-iso mdx file under the [Option SSH fields](https://github.com/hashicorp/packer/blob/master/website/pages/docs/builders/vmware/vsphere-iso.mdx#optional-ssh-fields).
The vsphere-clone has the same include code and you can use it as an example. Here you can see it [vsphere-clone.mdx#optional-ssh-fields](https://github.com/hashicorp/packer/blob/master/website/pages/docs/builders/vmware/vsphere-clone.mdx#optional-ssh-fields)

Let me know if you need any more help.

**Comment by adeniyistephen** [comment]
> Hi @adeniyistephen, great to hear you'd like to contribute.
> You just need to add the include for the [SSH-Private-Key-File-not-required.mdx](https://github.com/hashicorp/packer/blob/master/website/pages/partials/helper/communicator/SSH-Private-Key-File-not-required.mdx) to the vsphere-iso mdx file under the [Option SSH fields](https://github.com/hashicorp/packer/blob/master/website/pages/docs/builders/vmware/vsphere-iso.mdx#optional-ssh-fields).
> The vsphere-clone has the same include code and you can use it as an example. Here you can see it [vsphere-clone.mdx#optional-ssh-fields](https://github.com/hashicorp/packer/blob/master/website/pages/docs/builders/vmware/vsphere-clone.mdx#optional-ssh-fields)
> 
> Let me know if you need any more help.

Ok
