### ISSUE TITLE
packer doesn't clean up disk after failure

### ISSUE THREAD

**Issue by roy-work** [hashicorp/packer#10268]
#### Overview of the Issue

Packer fails to clean up the disk after failing

#### Reproduction Steps

1. Run packer against the below example

`packer` will fail to build it; it tries to write a file to `/` without permissions (this is not the bug). Packer, during tear down, doesn't remove the OS disk, leaving it stranded in the RG.

Packer emits,

```
» packer build test-packer.json
azure-arm: output will be in this color.

==> azure-arm: Running builder ...
==> azure-arm: Getting tokens using client secret
==> azure-arm: Getting tokens using client secret
    azure-arm: Creating Azure Resource Manager (ARM) client ...
==> azure-arm: WARNING: Zone resiliency may not be supported in eastus, checkout the docs at https://docs.microsoft.com/en-us/azure/availability-zones/
==> azure-arm: Using existing resource group ...
==> azure-arm:  -> ResourceGroupName : 'packer'
==> azure-arm:  -> Location          : 'eastus'
==> azure-arm: Validating deployment template ...
==> azure-arm:  -> ResourceGroupName : 'packer'
==> azure-arm:  -> DeploymentName    : 'pkrdp0np449heuf'
==> azure-arm: Deploying deployment template ...
==> azure-arm:  -> ResourceGroupName : 'packer'
==> azure-arm:  -> DeploymentName    : 'pkrdp0np449heuf'
==> azure-arm:
==> azure-arm: Getting the VM's IP address ...
==> azure-arm:  -> ResourceGroupName   : 'packer'
==> azure-arm:  -> PublicIPAddressName : 'pkrip0np449heuf'
==> azure-arm:  -> NicName             : 'pkrni0np449heuf'
==> azure-arm:  -> Network Connection  : 'PublicEndpoint'
==> azure-arm:  -> IP Address          : '[snip]'
==> azure-arm: Waiting for SSH to become available...
==> azure-arm: Connected to SSH!
==> azure-arm: Provisioning with shell script: /var/folders/gk/lygtd_4d6x3f6l8k2k2pvczc0000gn/T/packer-shell061049352
    azure-arm: uid=1000(packer) gid=1000(packer) groups=1000(packer),4(adm),20(dialout),24(cdrom),25(floppy),27(sudo),29(audio),30(dip),44(video),46(plugdev),117(netdev),118(lxd)
==> azure-arm: /tmp/script_7162.sh: 3: cannot create /test-file: Permission denied
==> azure-arm: Provisioning step had errors: Running the cleanup provisioner, if present...
==> azure-arm:
==> azure-arm: The resource group was not created by Packer, deleting individual resources ...
==> azure-arm:  -> Microsoft.Compute/virtualMachines : 'pkrvm0np449heuf'
==> azure-arm:  -> Microsoft.Network/networkInterfaces : 'pkrni0np449heuf'
==> azure-arm:  -> Microsoft.Network/virtualNetworks : 'pkrvn0np449heuf'
==> azure-arm:  -> Microsoft.Network/publicIPAddresses : 'pkrip0np449heuf'
==> azure-arm: Deleting the temporary Additional disk ...
==> azure-arm:  -> No Additional Disks specified
==> azure-arm: Removing the created Deployment object: 'pkrdp0np449heuf'
==> azure-arm:
==> azure-arm: The resource group was not created by Packer, not deleting ...
Build 'azure-arm' errored after 3 minutes 27 seconds: Script exited with non-zero exit status: 2.Allowed exit codes are: [0]

==> Wait completed after 3 minutes 27 seconds

==> Some builds didn't complete successfully and had errors:
--> azure-arm: Script exited with non-zero exit status: 2.Allowed exit codes are: [0]

==> Builds finished but no artifacts were created.
```

Afterwards, I'm left with a `pkros0np449heuf` disk. Given the output, it doesn't even seem like `packer` attempts to delete it. Is this intended?

### Packer version

```
Packer v1.6.5
```

### Simplified Packer Buildfile

```json
{
  "builders": [{
    "type": "azure-arm",

    "subscription_id": "<snipped>",
    "client_id": "<snipped>",
    "client_secret": "<snipped>",

    "managed_image_resource_group_name": "packer",
    "managed_image_name": "testpackerimage",

    "os_type": "Linux",
    "image_publisher": "Canonical",
    "image_offer": "0001-com-ubuntu-server-focal",
    "image_sku": "20_04-lts",

    "build_resource_group_name": "packer",
    "vm_size": "Standard_D2a_v4"
  }],
  "provisioners": [{
    "type": "shell",
    "inline": [
      "id",
      "sudo echo 'hello, world' > /test-file"
    ]
  }]
}
```

### Operating system and Environment details

`packer` is running under OS X, packing an Ubuntu VM image.

### Log Fragments and crash.log files

Set the env var `PACKER_LOG=1` for maximum log detail.

**Comment by nywilken** [comment]
Hi there, this sounds like a bug when using an existing resource group. Does the OS disk get deleted when there are no errors? 

Could you please upload the debug logs `PACKER_LOG=1 packer build <template>`. I'm curious if any errors are being logged. Thanks.

**Comment by roy-work** [comment]
> Hi there, this sounds like a bug when using an existing resource group.

Yes, we're using an existing RG. (I think that `packer` can run in a mode where it creates & tears down whole RGs? My only qualm against using that was whether it would require `Contributor` access to the `Subscription`, which is more permission than I'd like to give `packer` and violates PoLP.)

> Does the OS disk get deleted when there are no errors?

I'll see if I can answer this.

> Could you please upload the debug logs `PACKER_LOG=1 packer build <template>`

I can try; I originally looked at doing this, but those logs contained a significant amount of what I considered sensitive data that I didn't want to upload, and they were incredibly verbose, too, making redaction that much more difficult.

**Comment by nywilken** [comment]
> I can try; I originally looked at doing this, but those logs contained a significant amount of what I considered sensitive data that I didn't want to upload, and they were incredibly verbose, too, making redaction that much more difficult.

Got it, no worries on uploading the log. I was wondering if there were any mentions of a failed delete in the debug log output. If you could scan the logs and say yay or nay that is enough. 

>   I'll see if I can answer this.

Does this issue occur with v1.6.4? or v1.6.1? 

There were some changes made to the deletion logic for azure so I suspect it might be a regression but I do want to confirm this behavior in your environment. I will give it a test tomorrow to see if I can reproduce. 

Thanks again for reporting and for your time and help with this issue.

**Comment by roy-work** [comment]
Yep, the OS disk remains, even if the build succeeds.

There doesn't appear to be anything failing, in the logs; AFIACT, all the HTTP statuses are 2xx, and the OS disk isn't mentioned after the actual image is built. It is mentioned in the call to,

```
2020/11/17 17:39:23 packer-builder-azure-arm plugin: Azure request method="PUT" request="https://management.azure.com/subscriptions/<SUBSCRIPTION ID>/resourceGroups/packer/providers/Microsoft.Compute/images/testpackerimage?api-version=2018-04-01" body="{\"location\":\"eastus\",\"properties\":{\"sourceVirtualMachine\":{\"id\":\"/subscriptions/<SUBSCRIPTION ID>/resourceGroups/packer/providers/Microsoft.Compute/virtualMachines/pkrvmn2mq31lbsc\"},\"storageProfile\":{\"zoneResilient\":false}},\"tags\":{}}"
2020/11/17 17:39:25 packer-builder-azure-arm plugin: Azure response status="201 Created" method="PUT" request="https://management.azure.com/subscriptions/<SUBSCRIPTION ID>/resourceGroups/packer/providers/Microsoft.Compute/images/testpackerimage?api-version=2018-04-01" x-ms-request-id="<snip>" body="{\r\n  \"name\": \"testpackerimage\",\r\n  \"id\": \"/subscriptions/<SUBSCRIPTION ID>/resourceGroups/packer/providers/Microsoft.Compute/images/testpackerimage\",\r\n  \"type\": \"Microsoft.Compute/images\",\r\n  \"location\": \"eastus\",\r\n  \"tags\": {},\r\n  \"properties\": {\r\n    \"sourceVirtualMachine\": {\r\n      \"id\": \"/subscriptions/<SUBSCRIPTION ID>/resourceGroups/packer/providers/Microsoft.Compute/virtualMachines/pkrvmn2mq31lbsc\"\r\n    },\r\n    \"storageProfile\": {\r\n      \"osDisk\": {\r\n        \"osType\": \"Linux\",\r\n        \"osState\": \"Generalized\",\r\n        \"managedDisk\": {\r\n          \"id\": \"/subscriptions/<SUBSCRIPTION ID>/resourceGroups/packer/providers/Microsoft.Compute/disks/pkrosn2mq31lbsc\"\r\n        },\r\n        \"caching\": \"ReadWrite\",\r\n        \"storageAccountType\": \"Standard_LRS\"\r\n      },\r\n      \"dataDisks\": [],\r\n      \"zoneResilient\": false\r\n    },\r\n    \"provisioningState\": \"Creating\"\r\n  }\r\n}"
```

<details>
<summary>Same JSON, pretty-printed</summary>

```json
{
  "name": "testpackerimage",
  "id": "/subscriptions/<SUBSCRIPTION ID>/resourceGroups/packer/providers/Microsoft.Compute/images/testpackerimage",
  "type": "Microsoft.Compute/images",
  "location": "eastus",
  "tags": {},
  "properties": {
    "sourceVirtualMachine": {
      "id": "/subscriptions/<SUBSCRIPTION ID>/resourceGroups/packer/providers/Microsoft.Compute/virtualMachines/pkrvmn2mq31lbsc"
    },
    "storageProfile": {
      "osDisk": {
        "osType": "Linux",
        "osState": "Generalized",
        "managedDisk": {
          "id": "/subscriptions/<SUBSCRIPTION ID>/resourceGroups/packer/providers/Microsoft.Compute/disks/pkrosn2mq31lbsc"
        },
        "caching": "ReadWrite",
        "storageAccountType": "Standard_LRS"
      },
      "dataDisks": [],
      "zoneResilient": false
    },
    "provisioningState": "Creating"
  }
}
```
</details>

But after that, it seems like that identifier, `pkrosn2mq31lbsc`, isn't mentioned again. (And that's the disk that exists after the build completes.

I'll see if I can try those other, older versions, too.

**Comment by roy-work** [comment]
So, it seems like v1.6.4 **does** remove the OS disk; there's a line in the output, even, when resources are being torn down, that indicates it:

```
==> azure-arm:  -> Microsoft.Compute/disks : '/subscriptions/<SUBSCRIPTION ID>/resourceGroups/packer/providers/Microsoft.Compute/disks/pkros3ljwvjtshb'
```

(I've been assuming that `pkr` is "packer" and `os` is "OS [disk]". The disks in the 1.6.5 have also been named similarly.)

**Comment by cdtsushant** [comment]
can anybody knows this os disk features in latest version official document please .

**Comment by nywilken** [comment]
Hi there there's an open PR #10713 with a potential fix for this issue. Would you mind pulling down one of the test binaries and confirming that the patch fixes the reported issue?

The test binaries can be downloaded from https://app.circleci.com/pipelines/github/hashicorp/packer/9492/workflows/fb3a2460-88f5-4788-affb-089a5a3ddd87/jobs/113627/artifacts

Cheers!
