### ISSUE TITLE
aws-ebs terminating instance exits with bad status at very end of AMI creation

### ISSUE THREAD

**Issue by simonw7034** [hashicorp/packer#10278]
#### Overview of the Issue

I am building an AMI using the aws-ebs builder. Everything works fine up until what appears to be the cleanup stage, where the "Terminating the source AWS instance" step exits with bad status (even though it appears to finish the AMI build properly), the AMI is created and stored in our VPC but the code exits prematurely and with a non-zero rc. There may be artefacts left in AWS that aren't cleaned up properly (I haven't seen but there could be temporary security groups etc. leftover) and it makes it difficult to incorporate this into a CI build process.

The general build process is: 1) launch source AMI, 2) install some dependencies with apt 3) run a shell script to change the default boot kernel and reboot 4) wait for reboot 5) carry on with further provisioning (not included in this build template)

#### Reproduction Steps

Run`packer build -except=vagrant bf_packer.json` with an appropriate AWS VPC, user permissions and an IAM instance profile with AmazonSSMManagedInstanceCore policy and AWS authentication environment variables set.

### Packer version

Packer v1.6.5

### Simplified Packer Buildfile

[Packer build template](https://gist.github.com/simonw7034/a27d68b2eddf4cd6c030f19d62870793)

### Operating system and Environment details

MacBook Pro, 64-bit

### Log Fragments and crash.log files

[Debug log](https://gist.github.com/simonw7034/ebabe6a06c64fda526739bfcff1d4e0a)

**Comment by pascal-hofmann** [comment]
The same is happening for all our packer builds with `amazon-ebs`:
> ==> amazon-ebs: Bad exit status: -1

**Comment by justincjohnson** [comment]
I have this problem as well.  I see that the newly built AMI appears in the AWS console though.  To confirm, is the current understand that this only (possibly?) impacts cleanup, but not the creation of the AMI?  Thanks.

**Comment by simonw7034** [comment]
> I have this problem as well. I see that the newly built AMI appears in the AWS console though. To confirm, is the current understand that this only (possibly?) impacts cleanup, but not the creation of the AMI? Thanks.

Yes this is impacting on the cleanup of the EC2 instance and any other AWS objects presumably that are created along the way (Temporary security groups being the one that comes immediately to mind)
