### ISSUE TITLE
vsphere builder should use govmomi types to not violate API specifications

### ISSUE THREAD

**Issue by Borkason** [hashicorp/packer#10271]
The vsphere builder uses a custom type [HardwareConfig](https://github.com/hashicorp/packer/blob/8ffa0d20600daac37d207bf49198920941a97d9d/builder/vsphere/common/step_hardware.go#L15) (among others) instead of the govmomi sdk provided [VirtualMachineConfigSpec](https://pkg.go.dev/github.com/vmware/govmomi@v0.23.1/vim25/types#VirtualMachineConfigSpec).

The custom HardwareConfig type directly violates with the govmomi-sdk provided type `VirtualMachineConfigSpec`. For example, `VirtualMachineConfigSpec.NestedHV` is `nil` when not explicitly set. However, when `HardwareConfig.NestedHV` is not set it is `false` if unset and overwrites any `configuration_parameters` that perhaps activate that particular settings, such as `vhv.enable` (which is the key-value for the vmx file).

**Comment by sylviamoss** [comment]
Hey there, thanks for reaching out. 
The HardwareConfig is the Packer configuration struct to which we translate the templates config to. Later on, we write the VirtualMachineConfigSpec provided by govmomi sdk so we can configure the hardware [here](https://github.com/hashicorp/packer/blob/8ffa0d20600daac37d207bf49198920941a97d9d/builder/vsphere/driver/vm.go#L488). 
You are right that we always give a value to `VirtualMachineConfigSpec.NestedHVEnabled` and making `HardwareConfig.NestedHV`also a pointer sounds a good solution for this. 

We will fix this as soon as we get a chance. I will also be happy to review a PR if you wish to fix it before we do!

**Comment by Borkason** [comment]
> I will also be happy to review a PR if you wish to fix it before we do!

Would love to, but the entire vsphere plugin is too complicated for me. Been sitting in front of it for days and still don't understand what's happening.
