### ISSUE TITLE
/boot/efi/ location empty in CentOS/RHEL8 images for MAAS 2.8.2

### ISSUE THREAD

**Issue by c0DeR2020** [hashicorp/packer#10276]
Hi,
I'm trying to create CentOS/RHEL 8 images for MAAS using packer. When the image is deployed on bare-metal server, installation fails reporting "grub2-install: error: cannot rename the file /boot/grub2/grubenv.new to /boot/grub2/grubenv: No such file or directory". Detailed error message from MAAS GUI is mentioned in reference [1].
I extracted the image created, and found that the location '/boot/efi' is empty. Also, '/boot/grub2/grubenv' has symlink to '/efi/EFI/centos/grubenv' which is broken. This aligns with the error message obtained from MAAS GUI. Any insights what might cause the error? Any fixes or work around?

Here's the curtin repo for MAAS installation: https://github.com/canonical/curtin/tree/master/curtin
I've created images in the past for CentOS/RHEL 7 and it works fine in those scenarios.

Thanks,
Shibayan 

--------------------------------------
[1] Error reported in MAAS GUI:
`finish: cmd-install/stage-curthooks/builtin/cmd-curthooks/install-grub: FAIL: installing grub to target devices
        finish: cmd-install/stage-curthooks/builtin/cmd-curthooks/configuring-bootloader: FAIL: configuring target system bootloader
        finish: cmd-install/stage-curthooks/builtin/cmd-curthooks: FAIL: curtin command curthooks
        Traceback (most recent call last):
          File "/curtin/curtin/commands/main.py", line 202, in main
            ret = args.func(args)
          File "/curtin/curtin/commands/curthooks.py", line 1770, in curthooks
            builtin_curthooks(cfg, target, state)
          File "/curtin/curtin/commands/curthooks.py", line 1736, in builtin_curthooks
            setup_grub(cfg, target, osfamily=osfamily)
          File "/curtin/curtin/commands/curthooks.py", line 697, in setup_grub
            install_grub(instdevs, target, uefi=uefi_bootable, grubcfg=grubcfg)
          File "/curtin/curtin/commands/install_grub.py", line 376, in install_grub
            in_chroot.subp(cmd, env=env, capture=True)
          File "/curtin/curtin/util.py", line 708, in subp
            return subp(*args, **kwargs)
          File "/curtin/curtin/util.py", line 275, in subp
            return _subp(*args, **kwargs)
          File "/curtin/curtin/util.py", line 141, in _subp
            cmd=args)
        curtin.util.ProcessExecutionError: Unexpected error while running command.
        Command: ['unshare', '--fork', '--pid', '--', 'chroot', '/tmp/tmpv1alui71/target', 'grub2-install', '--target=x86_64-efi', '--efi-directory=/boot/efi', '--bootloader-id=rhel', '--recheck', '--no-nvram']
        Exit code: 1
        Reason: -
        Stdout: ''
        Stderr: Installing for x86_64-efi platform.
                grub2-install: error: cannot rename the file /boot/grub2/grubenv.new to /boot/grub2/grubenv: No such file or directory.
                
        Unexpected error while running command.
        Command: ['unshare', '--fork', '--pid', '--', 'chroot', '/tmp/tmpv1alui71/target', 'grub2-install', '--target=x86_64-efi', '--efi-directory=/boot/efi', '--bootloader-id=rhel', '--recheck', '--no-nvram']
        Exit code: 1
        Reason: -
        Stdout: ''
        Stderr: Installing for x86_64-efi platform.
                grub2-install: error: cannot rename the file /boot/grub2/grubenv.new to /boot/grub2/grubenv: No such file or directory.
                
        
Stderr: ''

**Comment by nywilken** [comment]
Hi there :wave: this sounds like a possible configuration issue, but I can't say for sure without the Packer version and configuration details. 

If you are still running into issues with this kind of initial configuration, the mailing list or community forum are generally more useful. Issues opened here on the Packer issue tracker are only viewed by a small handful of developers who work on the tool, and we don't always have the most depth or experience when it comes to custom issues with particular build configurations.

I'm going to close this issue, but if you believe this is a Packer bug please reach out with the following details:

- Packer version from `packer version`
- Host platform
- Full debug log output from `PACKER_LOG=1 packer build template.json`.
- Please paste this in a gist https://gist.github.com
- The simplest complete example template and scripts needed to reproduce the bug.
- Include these in your gist https://gist.github.com
