### ISSUE TITLE
[vsphere-iso]  Add support for SATA disk_controller_type  

### ISSUE THREAD

**Issue by telefax** [hashicorp/packer#10274]
While trying to build aarch64 vm:s on my RPI 4 ESXi cluster I was struggling with booting my VM:s after install.
It turns out that CentOS 8 only supports "sata" as controller type but this is not supported by packer.

Packer only supports lsilogic, pvscsi, nvme and scsi. 

Work around was to run packer in debug mode and change scsi controller to sata and then continue.

Similar issue but closed: https://github.com/hashicorp/packer/issues/9732

I'm not sure if this problem only occurs if you build EFI vm:s. I'm unable to select anything else than EFI anyway (only option in vcenter).

At first it didn't even boot the install ISO, but it worked when I set "cdrom_type": "sata". Default IDE didn't work at all.

**Comment by jhawk28** [comment]
I think this is dependent on: https://github.com/vmware/govmomi/issues/1219
