### ISSUE TITLE
Adding a ipv4 Gateway to vSphere-Clone

### ISSUE THREAD

**Issue by matteoiacovitti** [hashicorp/packer#10288]
How do you add a IPv4 Gateway to the VSphere-Clone builder?

I tried the following but it doesn't work:

```
"network": "{{user `vNetwork`}}",
      "customize": {
          "network_interface": {
            "ipv4_address": "10.99.1.50",
            "ipv4_netmask": "24"
          },
          "global_routing": {
              "ipv4_gateway": "10.99.1.1"
          }
      },
```
I also tried global_routing_settings and I tried putting the global_routing insode the Network Interface
```
"network": "{{user `vNetwork`}}",
      "customize": {
        "network_interface": {
          "ipv4_address": "10.99.1.50",
          "ipv4_netmask": "24",
          "global_routing": {
                "ipv4_gateway": "10.99.1.1"
          }
        }
      },
```
I also looked at the code and saw this

```
NetworkInterfaces     NetworkInterfaces `mapstructure:"network_interface"`
	GlobalRoutingSettings `mapstructure:",squash"`
	GlobalDnsSettings     `mapstructure:",squash"`
```
I'm not a programmer, but I'm curious as to why NetworkInterface has the appropriate label but the 2 Global settings have something called squash (again, not sure what any of that means but looks suspicious)

**Comment by sylviamoss** [comment]
Hi @matteoiacovitti, squash means that we are merging these structs into the parent one, which means you don’t need to use and enclosing block to configure those. Your config should look like:
```

"network": "{{user `vNetwork`}}",
      "customize": {
          "network_interface": {
            "ipv4_address": "10.99.1.50",
            "ipv4_netmask": "24"
          },
           "ipv4_gateway": "10.99.1.1"
      },

```

Try this one and let me know if it works. 
Maybe we can improve the docs to make it more clear that the block is not necessary.

**Comment by matteoiacovitti** [comment]
Ah. Thank you for the clarification. I learned something :D 

I tried your suggestion and it worked!! And yes, the documentation needs a bit more revision.
The fact that the ipv4_gateway is under the sub-section Global Routing made it seem that I need to add that in the code.
