### ISSUE TITLE
The validate command does not support the "packer" block type

### ISSUE THREAD

**Issue by smorimoto** [hashicorp/packer#10295]
​The validate command does not support the "packer" block type and will fail even though the document says the block is available.

**Comment by azr** [comment]
Hey @smorimoto thanks for opening ! Are you on the latest version of Packer ? Because it works for me:

```shell-session
$ cat command/test-fixtures/validate/build.pkr.hcl
packer {
  required_version = ">= v1.0.0"
}

source "file" "chocolate" {
  target = "chocolate.txt"
  content = "chocolate"
}

build {
  sources = ["source.file.chocolate"]
}

$ packer version                                              

Packer v1.6.5

$ packer validate command/test-fixtures/validate/build.pkr.hcl  && echo Valid !
Valid !

```

Sounds like the docs need to be more precise about the version where this started to happen.

**Comment by azr** [comment]
I opened #10298 that should do this better 🙂

**Comment by smorimoto** [comment]
I'm currently using 1.6.4, is this probably the cause?

**Comment by azr** [comment]
Yes looks like its the code, we're updating the docs right now 🙂

**Comment by smorimoto** [comment]
Okay, thanks! @azr
