### ISSUE TITLE
Unable to pass arguments - python script - shell provisioner- packer -environment variables

### ISSUE THREAD

**Issue by sededg** [hashicorp/packer#10307]
I am trying to pass arguments on python script using shell provisioner, am i missing anything?

**packer --version**
1.6.4

**Packer code:**
"provisioners": [
        {
            "type": "shell-local",
            "script": "python.py",
            "environment_vars": [
            "pyt_name=pytname",
            "pyt_arch=64-bit"
          ],
            "execute_command": [
            "/bin/bash",
            "-c",
            "{{.Vars}} /usr/bin/python {{.Script}}"
           ]
       }
**Debug log Error:**
==> vsphere-clone: usage: python.py [-h] --pyt_name PYT_NAME --pyt_arch PYT_ARCH
==> vsphere-clone: python.py: error: argument --pyt_name is required

**Comment by SwampDragons** [comment]
It looks like you're setting those variables as environment vars, but the python.py script expects them as arguments rather than env vars.

**Comment by tenthirtyam** [comment]
Recommend closure.

cc @nywilken

**Comment by lbajolet-hashicorp** [comment]
Good catch @tenthirtyam, we can indeed close this one since there hasn't been any update for years.
