### ISSUE TITLE
Qemu Builder with `"disk_image": true` and `"use_backing_file": true` fails

### ISSUE THREAD

**Issue by ChrisPortman** [hashicorp/packer#10300]
Since v1.6.5, using the Qemu builder and specifying a build that includes:

```
  "builders": [
    {
      "type": "qemu",
      "iso_url": "/image/path/base.qcow2",
      "disk_image": true,
      "use_backing_file": true,
      </snip>
    }
  ]
```

Results in the following error in the build:

```
packer-builder-qemu plugin: Executing /usr/bin/qemu-system-x86_64: []string{"-drive", "file=./packer/.build/machine/machine.qcow2,if=virtio,cache=writeback,discard=ignore,format=qcow2", "-drive", "file=./packer/.build/machine/machine.qcow2,if=virtio,cache=writeback,discard=ignore,format=qcow2", "-machine", "type=pc,accel=kvm", "-vnc", "127.0.0.1:24", "-display", "gtk", "-device", "virtio-net,netdev=user.0", "-m", "2048M", "-boot", "c", "-name", "machine.qcow2", "-netdev", "user,id=user.0,hostfwd=tcp::3575-:22"}
packer-builder-qemu plugin: Started Qemu. Pid: 112567
packer-builder-qemu plugin: Qemu stderr: qemu-system-x86_64: -drive file=./packer/.build/machine/machine.qcow2,if=virtio,cache=writeback,discard=ignore,format=qcow2: Failed to get "write" lock
packer-builder-qemu plugin: Qemu stderr: Is another process using the image [./packer/.build/machine/machine.qcow2]?
```

This cause of the error is that the `-drive` option is provided twice with the same image.

It appears that in 1.6.5 a refactor of the qemu builder took place.  The `step_run.go` file includes a function `getDeviceAndDriveArgs` which tests if the build is using an ISO or disk image and adds the `imgPath` to `drivesToAttach` when true.
https://github.com/hashicorp/packer/blob/945908fd74adc3d63687b96caaf55749b44b5625/builder/qemu/step_run.go#L215-L217

Also the `step_create_disk.go`, in addition to actually creating the derived disk, adds the result path to `state -> qemu_disk_paths` which is appended to the `drivesToAttach` in `step_run.go` `getDeviceAndDriveArgs`:
https://github.com/hashicorp/packer/blob/945908fd74adc3d63687b96caaf55749b44b5625/builder/qemu/step_run.go#L219-L220

Both of these paths taken together results in the drive parameters being added twice to the Qemu args for the build.

**Comment by ChrisPortman** [comment]
I've just realized that this is a dupe of #10223.  I'm going to leave it open though for its extra context.  But feel free to close it as appropriate.

**Comment by sylviamoss** [comment]
Thanks @ChrisPortman! We can close this one.
When you tagged https://github.com/hashicorp/packer/issues/10300 this issue automatically appeared there, so it can be used as a source of more information.
