### ISSUE TITLE
Vsphere Clone Builder: Clone a VM from a template in a Content Library

### ISSUE THREAD

**Issue by graham1228** [hashicorp/packer#10318]
Please search the existing issues for relevant feature requests, and use the
reaction feature
(https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
to add upvotes to pre-existing requests.

#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

As a user of the vsphere-clone builder I would like the ability to create a vm from an existing vm template in a content library. 

#### Use Case(s)

We use the content library to store our base OS OVF images and need to be able to utilize these templates to layer on solution specific software leveraging the vsphere-clone builder.

#### Potential configuration

Utilizing the same configuration item, additionally search in all content libraries for the template name
```
template (string) - Name of source VM. Path is optional.
```

#### Potential References
* https://discuss.hashicorp.com/t/vsphere-clone-from-content-library/11818

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out! 

I believe you can already do this using the iso_paths config option: 

https://www.packer.io/docs/builders/vmware/vsphere-clone#iso_paths

**Comment by graham1228** [comment]
@SwampDragons That appears to be specific to .iso and not a template or OVF. Do you have any examples on how to utilize isopaths to specify a template/OVF to clone? I would be willing to give it a try and report back.

**Comment by graham1228** [comment]
@SwampDragons I just tested it out and the `iso_paths` option does not provide the requested feature functionality to clone from an OVF template in a content library.

**Comment by sylviamoss** [comment]
Hey @graham1228, you're right, this a new feature we need to implement for vsphere-clone. We will work on this when we get a chance. 
If you wish to do it yourself, I'll be happy to help you with that.

**Comment by graham1228** [comment]
@sylviamoss I might be able to to take a swing at it if I have some spare time. Thanks for the update.
