### ISSUE TITLE
googlecompute builder: Add option wait_to_add_ssh_keys

### ISSUE THREAD

**Issue by seventieskid** [hashicorp/packer#10312]
#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

We use in-house security hardened GCP machine images to underpin our temporary packer instances. We cannot control the boot sequence of those images. The packer instance boot sequence is clearly interfering with the placement of SSH keys on the packer instance, and hence preventing the subsequent establishment of an SSH session.

The feature we are proposing is to add a switch called `wait_to_add_ssh_keys=20m`. We will separate the packer instance creation into three steps:-

a) Create the packer instance WITHOUT SSH keys
b) sleep for the `wait_to_add_ssh_keys` interval. Configured to be a suitable time interval to allow the GCEGuestAgent to stabilise.
c) Add the SSH keys to the running packer instance

We are prepared to submit a PR, so are gauging interest, and more importantly, likelihood of merging.

Note: The current `pause_before_connecting` option will not give us the functionality we need because it happens AFTER SSH key exchange and SSH connection establishment (should really be called `pause_before_provisioning`, but I digress).

#### Use Case(s)

Guard against disruptive boot sequences on:-

- In-house built GCP machine images used to create packer instances on GCP.
- Standard GCP images (future proofing).

#### Potential configuration

```
wait_to_add_ssh_keys=20m
wait_to_add_ssh_keys=15s
etc
```

#### Potential References

Packer log and cut-down packer instance log:-

https://gist.github.com/seventieskid/bc15a4bb45a8e1ce9b225b18047809ca

**Comment by wilsonfv** [comment]
Hi Gareth @seventieskid 

I dont seem to understand the rational behind these steps 

```
a) Create the packer instance WITHOUT SSH keys
b) sleep for the wait_to_add_ssh_keys interval. Configured to be a suitable time interval to allow the GCEGuestAgent to stabilise.
```

How do we ensure `when` GCEGuestAgent has been initialized properly 
I assume your intension of using the new option `wait_to_add_ssh_keys` is try to guess after `wait_to_add_ssh_keys` (such as 1 minute), GCEGuestAgent would have been ready ?

**Comment by seventieskid** [comment]
The packer image boot sequence is preventing the exchange of SSH keys, and hence the establishment of the SSH connection.

We know the specific step in the boot sequence that's affecting it, but we have no ability to change the boot sequence (either programmatically or by addressing with the team that builds them).

Also, we don't know how the boot sequence will change in the future.

Any solution must not be tied to specific boot steps, but must be arbitrary to cover the existing scenario, and to future proof for boot sequence changes. A delay is the least worst alternative to achieve that. It is also consistent with the "pause_before_connecting" packer parameter approach too.

Packer relies on standard GCP mechanisms for SSH key exchange;  inject a public key as metadata, and let GCP do the rest. To control that, we must prevent public SSH key injection upon initial packer instance creation (and pause startup scripts too), until the boot sequence has completed. Then inject the public SSH key and allow the startup scripts to run.

The delay allow reconfiguration as-and-when the boot sequence changes.

Deep diving the code, it appears to be possible to do the above, and limit the blast radius of the change to the googlecompute builder only.

The revisions in Issue title and description reflect increased learning, as the code is better understood.

**Comment by SwampDragons** [comment]
When we implemented pause_before_connecting, I think this was the original intent, and it was implemented improperly. Instead of adding a new feature, we could probably just fix the one in there to wait to connect at all until the pause is over. 

I'd merge this.

**Comment by seventieskid** [comment]
I'm going to continue to work on this, and submit a PR for review. It's scope will only be the googlecompute builder. pause_before_connecting parameter affects all builders. That's a huge scope, and I don't have the test bed to regression test all builder types.

So I need your guidance. Will hashicorp take on the re-purposing of pause_before_connecting  and retest against all builder types ? I don't think you can repurpose that parameter because it breaks backwards compatibility of the switch for teams out there that already use it.

Much better (for us) is if you could review/merge my PR for googlecompute builder only - that way the scope of the change is limited, and backwards compatibility isn't an issue because we're adding a new switch "wait_to_add_ssh_keys". You also won't have to do the coding !

I'm almost there with the PR - but will stop working on it, if hashicorp's intention is to repurpose pause_before_connecting.

Please advise on your intent.

**Comment by SwampDragons** [comment]
For now go ahead and do your limited-scope change. I'll merge it under the new switch name, and if we end up deprecating/modifying the other wait we can worry about naming then.

**Comment by seventieskid** [comment]
Awesome, thanks for your support.
