### ISSUE TITLE
Packer product name not being set in user agent header

### ISSUE THREAD

**Issue by philharle** [hashicorp/packer#10315]
When running Packer it declares its user-agent Header as follows
"userAgent": `aws-sdk-go/1.34.26 (go1.15.2; linux; amd64)`

This is different to when running Terraform, which presents its user-agent similar to below
"userAgent": `aws-sdk-go/1.34.14 (go1.14.5; darwin; amd64) APN/1.0 HashiCorp/1.0 Terraform/0.13.0 (+https://www.terraform.io)`
The inclusion of the `Terraform` product name is useful as it can be used in AWS IAM polcies as a basic (but not infallible) condition like below:
```
"Condition": {
    "ForAnyValue:StringLike": {
        "aws:useragent": [
            "*Terraform*"
        ]
    }
}
```

Packer's [`/packer-plugin-sdk/useragent/useragent.go`](`https://github.com/hashicorp/packer/blob/73b7499811cb0e910114737c6f73f865d736b9d8/packer-plugin-sdk/useragent/useragent.go#L24`
) suggests it should be prepending `Packer/` into the user-agent header which could be used in a similar method to the above. However this is not what is being seen in the AWS logs.

Using Packer version 1.6.4 (same issue with latest release 1.6.5 too)
Running on Alpine 3.12.1 (same issue on MacOS darwin build too)

**Comment by PaulWBrassard** [comment]
I see this has not been resolved as of Packer v1.7.2, initially I wasn't sure if the 1.6.6 milestone was to indicate that it was resolved as of 1.6.6 and maybe the issue just wasn't marked as resolved.
@philharle any chance this could be updated to indicate what version the fix is targeting now?

**Comment by serverwentdown** [comment]
Is this an issue with `packer-plugin-amazon`, or all packer plugins in general? I see that Terraform uses `awsbase` while `packer-plugin-amazon` uses the SDK directly.

**Comment by serverwentdown** [comment]
Terraform:
- Internal: [`HashiCorp Terraform/%s (+https://www.terraform.io)`](https://github.com/hashicorp/terraform/blob/d35bc0531255b496beb5d932f185cbcdb2d61a99/internal/httpclient/useragent.go#L45) + `TF_APPEND_USER_AGENT`
- AWS plugin: [`aws-sdk-go/1.34.14 (go1.14.5; darwin; amd64) APN/1.0 HashiCorp/1.0 Terraform/%s terraform-provider-aws/%s`](https://github.com/hashicorp/terraform-provider-aws/blob/04390ef20f2ea04c7be9c890bd3ea5e76f32ce6b/aws/config.go#L437)

Packer:
- GitHub Getter: [`packer-getter-github-%s`](https://github.com/hashicorp/packer/blob/4ebc09f08f87bab780d6a854c05183e800d0eed9/command/init.go#L94)
- AWS plugin: [`aws-sdk-go/1.34.26 (go1.15.2; linux; amd64)`](https://github.com/hashicorp/packer-plugin-amazon/blob/506e3ea4e6c9f16af5ecfac0a909aa75269179b1/builder/common/access_config.go#L207)
