### ISSUE TITLE
Packer overrides CMD and ENTRYPOINT already set in FROM image

### ISSUE THREAD

**Issue by dimisjim** [hashicorp/packer#10311]
#### Overview of the Issue

A dev familiar with Dockerfile expects Packer to keep the ENTRYPOINT and/or CMD set in the image where the build is based from. Why would Packer reset these, if they are not overridden explicitly in the commit argument of the builder?

#### Reproduction Steps

1. Create a simple nginx image based on the official one.
2. if no CMD is defined in the commit argument of the builder, it defaults to /bin/sh
3. only when `"ENTRYPOINT nginx -g 'daemon off;'"` the image works as expected

### Packer version

1.6.5

### Simplified Packer Buildfile

this is necessary
```
source "docker" "nginx" {
  image   = "nginx"
  commit  = true
  changes = [
    "EXPOSE 80",
    "ENTRYPOINT nginx -g 'daemon off;'"
  ]
}
```
this should be enough:
```
source "docker" "nginx" {
  image   = "nginx"
  commit  = true
  changes = [
    "EXPOSE 80",
  ]
}
```

considering this exists already: 

### Operating system and Environment details

Ubuntu 20.10,
Docker version 19.03.13, build 4484c46

**Comment by SwampDragons** [comment]
maintainer note: relates to #4914; potentially a dupe. Leaving open because it's been such a long time since anyone looked at 4914.
