### ISSUE TITLE
Azure Shared image gallery : add Storage account type

### ISSUE THREAD

**Issue by pobop** [hashicorp/packer#10313]
#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

Hello,
I would like to choose the sku for "Storage account type" when I push an image to Azure Shared Image Galleries.
Currently the default value is used by packer (Standard HDD/Standard_LRS)

#### Use Case(s)

Increase availabilities of images stored in Azure SIG with usage of "Standard_ZRS"
Or increase performance with  "Premium_LRS"

#### Potential configuration

```
"builders": [
        {
            "type": "azure-arm",                      
            "shared_image_gallery_destination": {                
                "resource_group": "{{user `build_resource_group_name`}}",
                "gallery_name": "{{user `gallery_name`}}",
                "image_name": "{{user `image_name`}}",
                "image_version": "{{user `image_version`}}",
                "replication_regions": ["westeurope"],
                "storageAccountType": "{{user `storageAccountType`}}"
            },            
        }
    ],
```

#### Potential References

Link to ARM documentation https://docs.microsoft.com/en-us/azure/templates/microsoft.compute/2019-12-01/galleries/images/versions#galleryimageversionpublishingprofile-object

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out. Just to make sure, did https://www.packer.io/docs/builders/azure/arm#managed_image_storage_account_type not work for this use case?

**Comment by pobop** [comment]
Hi,

Unfortunately not.
This parameter is applied to the managed images created by packer before to push to SIG the images but once in SIG this parameter is not applied.

**Comment by thenewnano** [comment]
this would be nice to have, work arounds are not really good in this case adding too much overhead.
