### ISSUE TITLE
vsphere-iso: Add support to enable vapp properties

### ISSUE THREAD

**Issue by jpbuecken** [hashicorp/packer#10319]
#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

In vSphere, you can enable vApp Options of a VM via Configure -> vApp Options -> Edit
After that, you can add Properties to the vApp / VM (same window)

![image](https://user-images.githubusercontent.com/38046041/100745060-02a4a400-33df-11eb-8b31-0a73f2ee883d.png)

This should be possible via the vsphere-iso builder.

#### Use Case(s)

With this, you can create a VM with vApp Properties.
Use Case 1: You can add a public-keys property. Configure your Suse autoyast / Redhat/Ubuntu kickstart / Ubuntu preseed to make use of the value during boot (write your own script or make use of cloud-init).
After you have done this, your new vm can be used in turn as a source for vsphere-clone builder. 
Since vsphere-clone supports temporary keys for the public-keys property, there is no need to store a password or public-key file in your source image.
I see this as an absolut security win.

Use Case 2: Similar to vsphere-clone, vsphere-iso may use the public-keys property itself:
1) vsphere-iso creates the vapp property public-keys
2) vsphere-iso is able to generate temporary key pairs and add them as value to the public-keys (additional new feature, same logic as vsphere-clone)
3) Your automatic installation process make use of the value in public-keys and add them to your connect user (e.g. root)
4) vsphere-iso can connect with the ssh communicator with the temporary key pair
Now the same argument as above applies, there is no need to store a hardcoded password or key files inside your vm before you connect with vsphere-iso. E.g. we have the policy to recreate key files regularly. If they are created and removed "on the fly" temporary, this policy is easily fulfilled.

#### Potential configuration

```
     "builders": [
      {
         "type":                      "vsphere-iso",
[...]
        
        "vapp": {
             "enable_vapp_options": true
            "properties": {
                "public-keys": "",
            }
        }
     ]

```

#### Potential References

https://www.packer.io/docs/builders/vmware/vsphere-clone#ssh (search for public-keys and vapp on the side)

**Comment by sylviamoss** [comment]
Hey there! Should not be hard to make the vsphere-clone vapp configuration also available to vsphere-iso. 
It will then look the same, like: 
```
vapp {
     properties = {
        hostname  = var.hostname
        user-data = base64encode(var.user_data)
     }
   }
```
no need to set `enable_vapp_options`, because the existence of the `vapp` block is already telling Packer to enable it. 
We can work on this once we get a chance. Meanwhile, if you wish to make write the solution yourself, I'll feel happy to help and review.

**Comment by djpbessems** [comment]
I'm actually right now adding vApp properties through a PowerCLI script as a local-shell post-processor, but I'm getting the impression that the `vsphere`+`vsphere-template` post-processor chain that follows right after is deleting the vApp properties. Will have to look into this more.

**Comment by jpbuecken** [comment]
> I'm actually right now adding vApp properties through a PowerCLI script as a local-shell post-processor, but I'm getting the impression that the `vsphere`+`vsphere-template` post-processor chain that follows right after is deleting the vApp properties. Will have to look into this more.
> 
> EDIT: I realise my comment might seem off-topic, sorry. I was actually trying to convey that I am interested in this feature too. But I'm not entirely sure now after rereading whether this issue is to request the possibility to _define_ vApp options, or to _use_ vApp options?

Nice idea. But my ultimate goal is "Use Case 2: Similar to vsphere-clone, vsphere-iso may use the public-keys property itself".

Ultimately I need both features: Define and use vApp properties: 
1) Define a  vApp property "public-keys" . This must be executed before the following step: 
2) then vpshere-iso should generate a temporary key pair ( similar to vsphere-clone)
3) then vpshere-iso should add the public key as value the previously defined property (similar to vsphere-clone)
4) then it should attach my iso and boot (as it does now)
My used iso is prepared to make use of "public-keys" inside the OS.
This will avoid the use of a static/persistent cleartext install password or other secret to access the OS.
We avoid such secrets in our git, but to manage and track them outside of git is difficult as well.

**Comment by djpbessems** [comment]
I hadn't thought of using vApp properties *before* boot_command was triggered, but yeah that would be totally awesome too.

Do you agree that this issue can serve both purposes though? Pre-install and post-install definition of vApp properties?
If not, I'll probably create a new issue for post-install.

**Comment by jpbuecken** [comment]
> I hadn't thought of using vApp properties _before_ boot_command was triggered, but yeah that would be totally awesome too.
> 
> Do you agree that this issue can serve both purposes though? Pre-install and post-install definition of vApp properties?
> If not, I'll probably create a new issue for post-install.

IMHO this issue can serve both purposes:

Assume this HCL

```
vapp {
     properties = {
        public-keys = ""
        hostname  = ""
        user-data = base64encode(var.user_data)
     }
   }
```

My expectation is that the resulting template has the vApp properties `public-keys` and `hostname` with empty values, and a property `user-data` with a pre-defined value.
If I do not want some of those properties (e.g. public-keys only used for installation), maybe it is still possible to modify or delete it via local command as you suggested.
