### ISSUE TITLE
file type provisioner unable to download from tmpfs mounts in docker build

### ISSUE THREAD

**Issue by gbjtv** [hashicorp/packer#10326]
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

File download fails when trying to download from a tmpfs mount with this message

```
==> docker: Download failed: Error downloading file: Error: No such container:path: 3b84652dcb09ca252f8d9221f038638609037fbec9a10649e247831850e8f566:/dev/shm/bash
```
#### Reproduction Steps

Run `packer build packer.json` with the buildfile below

### Packer version

1.6.5

### Simplified Packer Buildfile

```json
{
  "builders": [
    {
      "type": "docker",
      "image": "ubuntu:18.04",
      "privileged": true,
      "discard": true
    }
  ],
  "provisioners": [
    {
      "type": "shell",
      "inline": [
        "set -x",
        "mount | grep /dev/shm",
        "cp /bin/bash /dev/shm",
	"ls -l /dev/shm/bash"
      ]
    },
    {
      "type": "file",
      "direction": "download",
      "source": "/dev/shm/bash",
      "destination": "bash"
    }
  ]
}
```
### Operating system and Environment details

1. bare metal running ubuntu 20.04 focal (5.9.10-050910-generic kernel)
2. ec2 instance running ubuntu 16.04 xenial (4.4.0-1117-aws kernel)

### Log Fragments and crash.log files

https://gist.github.com/gbjtv/47d4d2196501b2d4ce17d7ea83e89a20

**Comment by sylviamoss** [comment]
Hello, thanks for reaching out! 
I was checking out the [docker cp doc ](https://docs.docker.com/engine/reference/commandline/cp/)and

> It is not possible to copy certain system files such as resources under /proc, /sys, /dev, tmpfs, and mounts created by the user in the container. However, you can still copy such files by manually running tar in docker exec. Both of the following examples do the same thing in different ways (consider SRC_PATH and DEST_PATH are directories):

So in this case I suggest you run a shell-local to run tar in docker exec, or make a copy o bash elsewhere so you can download it. 

I'm closing this issue, but feel free to reach out to us if needed.
