### ISSUE TITLE
Unable to use log file environment variable

### ISSUE THREAD

**Issue by tking2096** [hashicorp/packer#10344]
#### Overview of the Issue

Using PowerShell, I have successfully enabled logging using the `PACKER_LOG` and `PACKER_LOG_PATH` environment variables. I would like the `error-cleanup-provisioner` to publish the last n lines of this log, but I can't seem to get the value of `PACKER_LOG_PATH` in my template.

#### Reproduction Steps

In PowerShell:
```
$env:PACKER_LOG = "1"
$env:PACKER_LOG_PATH = "C:\Packer\p_log.txt"
```

In packer template, set `log_file_path` user variable:
```
{
    "variables": {
        "aws_access_key": "{{env `AWS_ACCESS_KEY_ID`}}",
        "aws_secret_key": "{{env `AWS_SECRET_ACCESS_KEY`}}",
        "region": "us-east-1",
        "log_file_path": "{{env `PACKER_LOG_PATH`}}"
    },
...
    "error-cleanup-provisioner": {
        "type": "shell-local",
        "execute_command": ["powershell.exe", "{{.Vars}} {{.Script}}"],
        "env_var_format": "$env:%s=\"%s\"; ",
        "tempfile_extension": ".ps1",
        "inline": [
            "$logContent = \"Last 30 lines of build log:`n`n\" + (Get-Content -Tail 30 {{ user `log_file_path` }}",
            "aws sns publish --topic-arn {{ user `sns_failure_topic_arn` }} --subject 'Packer Build Failed' --message \"$logContent\""
        ]
    }
...
}
```

### Packer version
```
PS C:\> packer version
Packer v1.6.5
```
### Simplified Packer Buildfile

_See above._

### Operating system and Environment details
```
OS: Windows Server 2019 Datacenter
Architecture: Intel 64bit running on AWS EC2
User: Administrator
PowerShell Version: 5.1.17763.1490
```
### Log Fragments and crash.log files

The log just shows that ```{{ user `log_file_path` }}``` was replaced with an empty string.

**Comment by nywilken** [comment]
Hi there @tking2096 the env `PACKER_LOG_PATH` is specific to Packer and is processed specifically for debug logging, and not evaluated in the context of a Packer build template.

If you use another env variable to hold the log path and then use its value for PACKER_LOG_PATH and the build variable does it solve your problem? 

In PowerShell:
```
$env:PACKER_LOG = "1"
$env:DEBUG_LOG_PATH = "C:\Packer\p_log.txt"
$env:PACKER_LOG_PATH = $env:DEBUG_LOG_PATH
```

In packer template, set `log_file_path` user variable:
```
{
    "variables": {
        "aws_access_key": "{{env `AWS_ACCESS_KEY_ID`}}",
        "aws_secret_key": "{{env `AWS_SECRET_ACCESS_KEY`}}",
        "region": "us-east-1",
        "log_file_path": "{{env `DEBUG_LOG_PATH`}}"
    },

```

**Comment by tking2096** [comment]
Thanks @nywilken, I will use your approach. It would be nice to have this documented in the `Debugging` section of the documentation to help prevent folks like me from [figuratively] banging their head on their desks. Or perhaps to have the "reserved" environment variables noted in the `templates/user-variables#environment-variables` section.

**Comment by nywilken** [comment]
Hi @tking2096 it is always good to find gaps in the documentation, thank you.   PRs are welcomed if you are interested in make the update. Otherwise, we'll work on updating the docs as soon as we can.

**Comment by adeniyistephen** [comment]
@tking2096 @nywilken Hi, Kindly provide the input and pointers, so i can update the documentations. Thanks :)
