### ISSUE TITLE
spot instances on p3.* fails to connect because packer tries to connect on private IP

### ISSUE THREAD

**Issue by amrragab8080** [hashicorp/packer#10347]
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

Launching a p3.* build node with spot instances. The node launches in a public subnet with a public IP, however packer tries to connect on the private IPv4
```
==> amazon-ebs: Using ssh communicator to connect: 172.31.2.186
--
984 | ==> amazon-ebs: Waiting for SSH to become available...
985 | ==> amazon-ebs: Timeout waiting for SSH.
986 | ==> amazon-ebs: Terminating the source AWS instance...
```
Time's out on the connect. However my environment is flexible enough that my packer launch nodes are also on AWS and can reach the build nodes on its private IP. But wanted to report the bug none the less.

#### Reproduction Steps

```
"builders": [{
    "type": "amazon-ebs",
    "region": "{{user `region`}}",
    "source_ami": "{{user `build_ami`}}",
    "run_tags": {
        "Name": "packer-gpu-processor-{{user `flag`}}"
    },
    "subnet_id": "{{user `subnet_id`}}",
    "security_group_ids": "{{user `security_groupids`}}",
    "spot_instance_types": ["p3.8xlarge","p3.16xlarge"],
    "spot_price": "auto",
    "ssh_username": "ubuntu",
    "ami_name": "ml-gpu-processor_{{user `flag`}}-{{timestamp}}",
    "launch_block_device_mappings":[{
      "delete_on_termination": true,
      "device_name": "/dev/sda1",
      "volume_size": 150,
      "volume_type": "gp2"
    }]

```
### Packer version

1.6.5

### Simplified Packer Buildfile

If the file is longer than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/) of the log or use the [Github detailed
format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d)
instead of posting it directly in the issue.

### Operating system and Environment details

OS, Architecture, and any other information you can provide about the
environment.

Ubuntu 20.04 local build environment.

### Log Fragments and crash.log files

Include appropriate log fragments. If the log is longer than a few dozen lines,
please include the URL to the [gist](https://gist.github.com/) of the log or
use the [Github detailed format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d) instead of posting it directly in the issue.

Set the env var `PACKER_LOG=1` for maximum log detail.

**Comment by nywilken** [comment]
Hello there @amrragab8080 thanks for reaching out. Can you provide the logs `PACKER_LOG=1 packer build <template>` so that we can see what IP information is being made available at build time. When building in a VPC it should select the Public IP if available, otherwise it will default to the private ip. 

There is an option `ssh_interface` that allows to specify the interface to use for connection `"public_ip"` or `"private_ip"`. Does adding `"ssh_interface": "public_ip"` to your configuration change the outcome of your build?

**Comment by amrragab8080** [comment]
symptoms are similar to
https://github.com/hashicorp/packer/issues/5627

With ```PACKER_LOG=1``` I get the following:
```
==> amazon-ebs: Launching a spot AWS instance...
==> amazon-ebs: Interpolating tags for spot instance...
    amazon-ebs: Adding tag: "Name": "packer-gpu-processor-al2-base"
    amazon-ebs: Loading User Data File...
    amazon-ebs: Creating Spot Fleet launch template...
    amazon-ebs: Sending spot request ()...
    amazon-ebs: Instance ID: i-038f0cc80af2473a0
2020/12/08 10:30:56 packer-builder-amazon-ebs plugin: [INFO] Not using winrm communicator, skipping get password...
2020/12/08 10:30:56 packer-builder-amazon-ebs plugin: [INFO] Waiting for SSH, up to timeout: 5m0s
==> amazon-ebs: Using ssh communicator to connect: 172.31.13.128
2020/12/08 10:30:56 packer-builder-amazon-ebs plugin: Using host value: 172.31.13.128
==> amazon-ebs: Waiting for SSH to become available...
2020/12/08 10:31:11 packer-builder-amazon-ebs plugin: [DEBUG] TCP connection to SSH ip/port failed: dial tcp 172.31.13.128:22: i/o timeout
2020/12/08 10:31:16 packer-builder-amazon-ebs plugin: Using host value: 172.31.13.128
2020/12/08 10:31:31 packer-builder-amazon-ebs plugin: [DEBUG] TCP connection to SSH ip/port failed: dial tcp 172.31.13.128:22: i/o timeout
2020/12/08 10:31:36 packer-builder-amazon-ebs plugin: Using host value: 172.31.13.128
2020/12/08 10:31:51 packer-builder-amazon-ebs plugin: [DEBUG] TCP connection to SSH ip/port failed: dial tcp 172.31.13.128:22: i/o timeout
2020/12/08 10:31:56 packer-builder-amazon-ebs plugin: Using host value: 172.31.13.128
2020/12/08 10:32:11 packer-builder-amazon-ebs plugin: [DEBUG] TCP connection to SSH ip/port failed: dial tcp 172.31.13.128:22: i/o timeout
2020/12/08 10:32:16 packer-builder-amazon-ebs plugin: Using host value: 172.31.13.128
```
If you add ```"ssh_interface": "public_ip"``` you get a different error for a bit then its able to get the public ip.
It seems there is a race condition with spot in getting the SSH address - similar to the linked issue.
```
==> amazon-ebs: Waiting for SSH to become available...
2020/12/08 10:34:05 packer-builder-amazon-ebs plugin: [DEBUG] Error getting SSH address: couldn't determine address for instance
2020/12/08 10:34:14 packer-builder-amazon-ebs plugin: [DEBUG] Error getting SSH address: couldn't determine address for instance
2020/12/08 10:34:35 packer-builder-amazon-ebs plugin: [DEBUG] TCP connection to SSH ip/port failed: dial tcp 3.231.50.188:22: i/o timeout
2020/12/08 10:34:40 packer-builder-amazon-ebs plugin: Using host value: 3.231.50.188
```

**Comment by nywilken** [comment]
Awesome, thanks for the quick response and test @amrragab8080. I don't know if we will get a chance to investigate and fix soon but we will try to take a look when we can. If you are interested in opening a PR with a potential fix we would be more than happy to help you push it through.
