### ISSUE TITLE
Packer suppresses ANSI color encoding from ansible output

### ISSUE THREAD

**Issue by queglay** [hashicorp/packer#10348]
#### Overview of the Issue

Packer suppresses ANSI color encoding.  When using provisioners like Ansible, some very long logs can be output and without the color it's difficult to determine where something went wrong.

#### Reproduction Steps

Build anything with Ansible.  Any colors that would normally be output are not visible.

### Packer version

1.6.4

**Comment by nywilken** [comment]
Thanks for reaching out. We’ll take a look when we get a chance.
