### ISSUE TITLE
Add packer fmt -recursive option

### ISSUE THREAD

**Issue by danielkubat** [hashicorp/packer#10349]
#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

Add `-recursive` option to allow integration of `packer fmt`.

#### Use Case(s)

CI integration such as GitHub Action to check/format all `.pkr.hcl` and variable files `.pkrvars` across whole repository/project. Desired functionality is already implemented in Terraform:

```
-recursive     Also process files in subdirectories. By default, only the
               given directory (or current directory) is processed.
```

#### Potential configuration

```
packer fmt -check -recursive -diff
```

#### Potential References

https://www.terraform.io/docs/commands/fmt.html#usage

**Comment by azr** [comment]
Hello there ! Thanks for opening, I think this is a neat idea. I'm unsure if we have the time to implement this _right away_ ( correct me if I'm wrong team ) and so if you want to have this quickly, don't hesitate opening a PR.

The code might end up being super similar to the code on Terraform, so one you could probably use that as a hint. 

Thanks !

**Comment by teddylear** [comment]
@danielkubat @azr I can take a look into this.

**Comment by teddylear** [comment]
@azr I linked a PR with the change. I'm new to golang, so please let me know if there's something I missed or if I need to change anything!

**Comment by teddylear** [comment]
@azr as this is has been merged I believe this can be closed now.

**Comment by danielkubat** [comment]
@teddylear @azr thanks a lot.

**Comment by azr** [comment]
Thanks everyone ! :)
