### ISSUE TITLE
-machine-readable dropped from validate subcommand documentation

### ISSUE THREAD

**Issue by mschuchard** [hashicorp/packer#10346]
The `-machine-readable` flag for the `validate` subcommand has been dropped from documentation. However, as of 1.6.5 it still functions as expected. Does this imply discontinued support for it in the future, or was this perhaps an oversight? I have seen nothing implying it in the CHANGELOG, but need to verify as the Atom Editor integration for Packer relies upon it. Thanks!

**Comment by azr** [comment]
Hello there ! I think this was an oversight yes and we wouldn't remove support for this silently 🙂 .

**Comment by mschuchard** [comment]
Thank you for the clarification. I should mention that it also disappeared from the CLI info for the `validate` subcommand i.e. `packer validate --help`.
