### ISSUE TITLE
Variables should be able to reference other variables (hcl)

### ISSUE THREAD

**Issue by lausser** [hashicorp/packer#10354]
#### Description

In my old json config i had such variable settings:

``` 
cat templates/generic.json
{
  "builders": [
    {
...
     "boot_command": "{{ user `boot_command` }}"
    }
  ]
}
```
```
$ cat variables/centos-7.7.json 
{
  "template_name": "centos-7.7",

  "iso_file": "CentOS-7-x86_64-Minimal-1908.iso",
  "iso_checksum": "7002b56184180591a8fa08c2fe0c7338",
  "iso_checksum_type": "md5",

  "boot_command": "<tab><bs><bs><bs><bs><bs>text inst.ks=http://{{ user `packer_ip` }}:{{ .HTTPPort }}/{{ user `template_name` }}.cfg<enter><wait>",

}
```
Then i call packer with
```
packer build \
    -var-file=variables/centos-7.7.json \
    -var packer_ip="$PACKER_IP" \
    templates/generic.json
```
The important stuff is that this part of the boot_command ....inst.ks=http://{{ user `packer_ip` }}:{{ .HTTPPort }}/{{ user `template_name` }}.cfg..... will be seen by the builder with completely resolved user-variables. Where template_name comes from the same variables yml-file where the boot_command is defined (and could be hardcoded, no problem) and packer_ip comes from outside via -var.
(the background ot this variable packer_ip is: i run packer in a container and .HTTPIP is just an internal ip which cannot be seen by the VM/the http client)
Everything is fine, template gets created.

Now when i try the same with hcl format:

```
cat centos-7.7.pkrvars.hcl 
template_name = "centos-7.7"

iso_file = "CentOS-7-x86_64-Minimal-1908.iso"
iso_checksum = "md5:7002b56184180591a8fa08c2fe0c7338"

boot_command = ["<tab><bs><bs><bs><bs><bs>text inst.ks=http://${var.packer_ip}:{{ .HTTPPort}}/${var.template_name}.cfg<enter><wait>"]
```
and run packer build -var-file centos-7.7.pkrvars.hcl -var packer_ip=192.168.9.22 ..., then i get
```
Error: Variables not allowed

  on centos-7.7.pkrvars.hcl line 6:
   6: boot_command = ["<tab><bs><bs><bs><bs><bs>text inst.ks=http://${var.packer_ip}:{{ .HTTPPort }}/${var.template_name}.cfg<enter><wait>"]

Variables may not be used here.
```

Also when i try to move the settings from a pkrvars.ncl to a pkr.hcl file

```
variable "template_name" {
  type =  string
  default = "centos-7.7"
}

variable "boot_command" {
  type =  list(string)
  default = ["......./${var.template_name}.cfg<enter><wait>"]
}
```
template_name cannot be replaced in the same file, i get the same error "Variables may not be used here"

#### Use Case(s)

Actually it's just backwards-compatibility. Besides from that, the use case would be to have pkrvars.hcl files bundling the same settings with a different set of values and do a final finetuning via -vars.

#### Potential configuration

like i described above

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out. There are two different kinds of "variables" in HCL. "variables", which must be set with hardcoded defaults or set at runtime/in the environment, and "locals", which can use variables and functions.  Take a look at https://www.packer.io/docs/from-1.5/locals#examples for how to use local vars that can reference variables.

**Comment by lausser** [comment]
Oh, i was too slow, just wanted to write:
```
locals {
  template_name = "centos-7.7"
  iso_file = "CentOS-7-x86_64-Minimal-1908.iso"
  iso_checksum = "md5:7002b56184180591a8fa08c2fe0c7338"
  iso_url = "http://127.0.0.1/linux.iso"
  boot_command = ["<tab><bs><bs><bs><bs><bs>text inst.ks=http://${var.packer_ip}:{{ .HTTPPort }}/${var.template_name}.cfg<enter><wait>"]
  sftp_command = "/usr/libexec/openssh/sftp-server -e"
}
```
and
```
boot_command     = "${local.boot_command}"
```

That solves the problem! I had read the part with locals already but not careful enough, my first impression was that these are local to one file.

Thanks for your answer!
Gerhard
