### ISSUE TITLE
Proxmox boot order not being set: (no bootdisk)

### ISSUE THREAD

**Issue by markcaudill** [hashicorp/packer#10353]
#### Overview of the Issue

Prior to upgrading to pve-manager 6.3-2, Packer-built templates would have their boot order configured as "virtio0, any CD-ROM, any net" when using the VirtIO SCSI controller.

Currently, under pve-manager 6.3-2, the boot order is configured as "(no bootdisk), any CD-ROM, any net." The packer build process never reaches the provisioner steps.

#### Reproduction Steps

`packer build -var "build_name=$(date +centos8-ci-%Y%m%d%H%M%S)" packer-centos8.json`

### Packer version

1.6.5

### Simplified Packer Buildfile

```json
{
  "builders": [
    {
      "type": "proxmox",
      "cloud_init": true,
      "template_name": "{{ user `build_name` }}",
      "cores": 1,
      "cpu_type": "host",
      "memory": 2048,
      "os": "l26",
      "scsi_controller": "virtio-scsi-pci",
      "disks": [
        {
          "storage_pool": "vmshared",
          "storage_pool_type": "directory",
          "format": "qcow2",
          "disk_size": "12G"
        }
      ],
      "network_adapters": [
        {
          "bridge": "vmbr0"
        }
      ],
      "iso_file": "local:iso/CentOS-8.2.2004-x86_64-dvd1.iso",
      "iso_checksum": "sha256:c87a2d81d67bbaeaf646aea5bedd70990078ec252fc52f5a7d65ff609871e255",
      "http_directory": "http",
      "boot_wait": "10s",
      "boot_command": [
        "<up><tab>",
        " ip=dhcp",
        " inst.cmdline",
        " inst.ks=http://{{.HTTPIP}}:{{.HTTPPort}}/kickstart-centos8.cfg",
        "<enter>"
      ],
      "ssh_username": "root",
      "ssh_private_key_file": "/home/mark/.ssh/id_ed25519_packer",
      "ssh_timeout": "60m",
      "node": "vmhost-01",
      "insecure_skip_tls_verify": true,
      "unmount_iso": true
    }
  ],
  "provisioners": [
    {
      "type": "shell",
      "inline": [
        "systemctl enable qemu-guest-agent"
      ]
    },
    {
      "type": "shell",
      "script": "scripts/sysprep.sh"
    }
  ]
}
```

### Operating system and Environment details

```
$ uname -a
Linux marks-laptop 5.4.0-54-generic #60-Ubuntu SMP Fri Nov 6 10:37:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

### Log Fragments and crash.log files

No crash logs are generated. The build will simply timeout since an SSH login is never reached.

**Comment by nywilken** [comment]
Thanks for reaching out. We’ll take a look when we get a chance

**Comment by carlpett** [comment]
I believe this is fixed in 1.6.6, by #10260.

**Comment by markcaudill** [comment]
Very cool. Do you know roughly when 1.6.6 will be released?

**Comment by nywilken** [comment]
Thanks @carlpett 

We don't have a firm date for the next release yet. It's looking to be early Jan. However the fix is available for use in the latest Packer [nightly release](https://github.com/hashicorp/packer/releases/tag/nightly). 

If you want to pull it down and give it a test.

**Comment by markcaudill** [comment]
This issue is indeed fixed in the nightly build.

![image](https://user-images.githubusercontent.com/261361/101650216-b6261d80-3a09-11eb-9048-dfd4d84de51e.png)

Thanks for all your help!

**Comment by tabnul** [comment]
There might still be an issue here.

Even though the image creation goes all right after the latest fix, when the image gets cloned (in my case via the terraform proxmox provider) , the boot order gets cleared again. 
Please have a look here; https://github.com/Telmate/terraform-provider-proxmox/issues/282

After manually adding ' bootdisk: scsi0 '  to the Image VM config, it gets cloned correctly and the boot order stays intact.
But , when i manually clone the image, the result is also fine.

So, it seems that in latest Packer, ' bootdisk ' issnt set anymore, which causes issues in the terraform provider.
It is not clear to me who doesnt follow the spec , proxmox seems to think it is all fine since it clones correctly regardless of this setting.

**Comment by markcaudill** [comment]
I had (I think) the same issue and I upgraded my Terraform Proxmox version to 1.6.6 and added the following line to my `resource "proxmox_vm_qemu"` block. I basically did a `terraform import` of one of my Packer-created templates to figure out what was missing in my Terraform resource block. The terraform-provider-proxmox documentation seems out-of-date.

```hcl
boot = "order=virtio0;ide2;net0"
```

**Comment by carlpett** [comment]
Regarding `bootdisk`, it is marked as deprecated in the Proxmox API documentation, and what we write seems to me to be the correct way. I would suspect this is something in the Terraform provider, rather than in Packer?

**Comment by markcaudill** [comment]
Correct (I think). I didn't mean to imply this was an issue in Packer or Terraform, just in the provider and/or its documentation.

**Comment by tabnul** [comment]
I think its a valid conclusion then, that this has to be fixed in the provider. 
Discussion needs to continue here in that case.
https://github.com/Telmate/terraform-provider-proxmox/issues/282
