### ISSUE TITLE
Packer encounters "Error uploading ps script containing env vars" during the powershell provisioner step

### ISSUE THREAD

**Issue by sagilson** [hashicorp/packer#10357]
#### Overview of the Issue

An azure customer is attempting to use the Azure Image Builder service to create a Windows 2004 19h2-evd image that includes only windows update and windows restart. Azure Image Builder uses packer and the azure-arm builder to create images. During the powershell provisioning step, packer is unable to upload a powershell script that contains environment variables, causing packer to fail the image build. 

#### Reproduction Steps

Attempt to create a Windows 2004 19h2-evd image with windows update and restart using either the Azure Image Builder service or packer version with commit hash 5ddd02d1c0e5d8b1b0e2171d2d40c7d7b5641e68 (packer_1.6.1_linux_amd64).

### Packer version

From `packer version`
packer_1.6.1_linux_amd64

Also using
v0.9.0 packer-provisioner-windows-update-linux.tgz 

### Simplified Packer Buildfile

Cannot post for security reasons as I do not own the template in question, but the customer has told me the template only contains base image Windows 2004 w/ sku 19h2-evd and the only customizers are windows update and restart.

### Operating system and Environment details
Debian-like linux distro with more security patches and azure specific changes.

### Log Fragments and crash.log files

[ec332261-ebd9-43ae-80d4-11cd378aad0b] PACKER ERR 2020/12/04 08:17:16 packer-provisioner-powershell plugin: Uploading env vars to c:/Windows/Temp/packer-ps-env-vars-5fc9e087-7e72-f676-6b03-871326abc66c.ps1
[ec332261-ebd9-43ae-80d4-11cd378aad0b] PACKER ERR 2020/12/04 08:17:16 packer-provisioner-powershell plugin: [INFO] 74 bytes written for 'uploadData'
[ec332261-ebd9-43ae-80d4-11cd378aad0b] PACKER ERR 2020/12/04 08:17:16 [INFO] 74 bytes written for 'uploadData'
[ec332261-ebd9-43ae-80d4-11cd378aad0b] PACKER ERR 2020/12/04 08:17:16 packer-builder-azure-arm plugin: Uploading file to 'c:/Windows/Temp/packer-ps-env-vars-5fc9e087-7e72-f676-6b03-871326abc66c.ps1'
[ec332261-ebd9-43ae-80d4-11cd378aad0b] PACKER ERR 2020/12/04 08:28:49 packer-provisioner-powershell plugin: Retryable error: Error uploading ps script containing env vars: Error uploading file to $env:TEMP\winrmcp-2735b5fd-6a49-4753-71d9-0be9e8c8d7fd.tmp: Couldn't create shell: unknown error Post https:///wsman: EOF

**Comment by nywilken** [comment]
Hi there thanks for reaching out. This looks like an error on the winrm receiving end, specifically with writing to the Temp directory. 

Do you know if the system has any size restriction or permission issues when writing to $env:TEMP? 

Packer allows users to set a `remote_path` and `remote_env_var_path` to change the location of the uploaded files. You may want to take a look at these options to see if it fixes the issue.

**Comment by sagilson** [comment]
To the best of my knowledge, there are no issues when writing there.
There is a chance that this error does not occur and the build succeeds. Do you know why this error could be occurring so transiently? I have not been able to find a rhyme or reason as to why this error occurs.

**Comment by sagilson** [comment]
This error also is occurring in builds that use the Windows 10 Desktop 19h2-evd.
Could disabling previous versions of SSL and TLS on the machine as wirnm has connection cause winrm to fail?
