### ISSUE TITLE
Unable to use http_interface with Proxmox provider

### ISSUE THREAD

**Issue by anon8675309** [hashicorp/packer#10369]
When specifying "http_interface" with the packer provider, and not specifying any "http_bind_address", it results in the error:

```
either http_interface of http_bind_address can be specified
```

Expected behavior:
1. Error message should say "or" instead of "of" if these options are actually mutually exclusive
2. When only http_interface is specified in the configuration, this error message does not appear, but it just obtains the IP address from the specified interface

Workaround: use http_bind_address instead of http_interface.  I would prefer http_interface was functional, however this is getting me by for now.

**Comment by jhajek** [comment]
Which operating system are you using?   I can confirm this error on Windows 10 packer 1.6.5 and on Ubuntu Server 18.04.5 packer 1.6.5  when just using the http_interface field.

**Comment by anon8675309** [comment]
I am also using Ubuntu 18.04.5 and packer 1.6.5.
