### ISSUE TITLE
Packer boot command error (ESXI/ Vsphere) 

### ISSUE THREAD

**Issue by Aldrims** [hashicorp/packer#10376]
#### Overview of the Issue
Error when entering boot_command during a Packer build 
![image](https://user-images.githubusercontent.com/46164298/101904217-ce3aa000-3bb5-11eb-982c-949304df5a0a.png)

#### Reproduction Steps
Goal : Create a template for a basic debian 10 in vsphere 
Using ESXI 6.7 
Using vsphere 6.7.0.21000 
Having  3 file on a debian 10.1.0 
debian10_1.json
debian10_variable.json
debian10.cfg
Using the command  "sudo packer build -force -var-file debian10_variable.json debian10_1.json" 
### Packer version
Packer 1.6.5

### Simplified Packer Buildfile
debian10_1.json
![image](https://user-images.githubusercontent.com/46164298/101904513-3c7f6280-3bb6-11eb-930d-8b1d38be31f4.png)
![image](https://user-images.githubusercontent.com/46164298/101905147-435aa500-3bb7-11eb-88ba-f7b91c636e31.png)

### Operating system and Environment details
Debian 10.1.0 
Vsphere 6.7.0.21000 (on a remote server)
### Log Fragments and crash.log files
![image](https://user-images.githubusercontent.com/46164298/101904217-ce3aa000-3bb5-11eb-982c-949304df5a0a.png)
Each time blocking at a different time when writing the boot command

**Comment by jhawk28** [comment]
try changing the https://www.packer.io/docs/builders/vmware/vsphere-iso#boot_keygroup_interval to a slower interval. I've seen this error periodically on our stuff, but haven't identified the specific cause. I've thought about putting in a retry if it gets an error, but I never have a consistent failure to see if it would fix it.

**Comment by jhawk28** [comment]
NOTE: the default boot_keygroup_interval is 100ms

**Comment by Aldrims** [comment]
I'll try that asap multiple time to see if it fix things up, thx for the answer (I'll tell you if it worked)

**Comment by jhawk28** [comment]
I'm wondering if resending the key if it gets an error would work around this issue. An alternative would be to see if the vnc over websocket is more reliable.

**Comment by Aldrims** [comment]
Like doing a script re-sending keys if an error occur  but if it fail 9 times out of 10 it could be very long, for VNC over websocket how can I use it (do you have any documentation or something to help me try it  ? )

**Comment by Aldrims** [comment]
Ok by changing the interval of key group to 30 ms it seems to work a lot better , not perfect but for the moment I don't have any error, I'll edit if I find the same error again

**Comment by jhawk28** [comment]
The current mode is that if it gets an error during any part of the boot command, it will error out. Its not erroring out on 9/10 keystrokes. The idea would be to just retry the keystroke, not the whole boot process. The VNC over web socket was added to the ESXI5 driver for the vmware-iso plugin. We would need to add some code to make it available to the vsphere-iso builder.

**Comment by jhawk28** [comment]
can you check to see if this build fixes the issue: https://app.circleci.com/pipelines/github/hashicorp/packer/8924/workflows/ef5fd9b6-c559-4165-a61a-ac257d675a80/jobs/105663/artifacts

**Comment by Aldrims** [comment]
How do I apply  this fix ? is it  just an apt update ?

**Comment by jhawk28** [comment]
You just download the binary that matches your OS from the link.

**Comment by sylviamoss** [comment]
@Aldrims any feedback on the fix @jhawk28  share with you?

**Comment by Aldrims** [comment]
Didn't successfully used the binary, didnt have the time on that project if I use it I'll post a feedback here

**Comment by sylviamoss** [comment]
Ok. Sounds good! I'll close the issue and if you keep having it, feel free to reach out to us or the community in our [discuss forum](https://discuss.hashicorp.com/c/packer)
