### ISSUE TITLE
macOS Big Sur Host SSH time out when building an image

### ISSUE THREAD

**Issue by usmcfiredog** [hashicorp/packer#10375]
Host is macOS 11.0.1
Packer version 1.6.5
VMware Fusion 12.1

I have built a couple of templates before many times using macOS 10.15 with VMware Fusion 12 and had no problems. Since upgrading to macOS Big Sur I can no longer build a linux or windows vm. Everything goes fine up until it is waiting for ssh to become available where it will sit and wait for 2 hours when it times out. I am able to ssh into the vm from the host with no problems but packer is not able to see that it is available.

**Comment by trodemaster** [comment]
This sounds like the issue you are seeing #10177

**Comment by SwampDragons** [comment]
If indeed you're seeing #10177, it was fixed in #https://github.com/hashicorp/packer/pull/10384 and released in v1.6.6. Upgrading Packer should sort out your problem.

Closing since this was probably already solved.
