### ISSUE TITLE
Feature Request: support hcl modules for source definitions

### ISSUE THREAD

**Issue by ndimiduk** [hashicorp/packer#10387]
#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

Packer apparently supports multiple source blocks, even of the same provider, so long as they have unique names. In cases where most details are identical, it would be nice to define a module that encapsulates these commonalities, and customize it with parameters. This pattern is available in Terraform and works very well.

#### Use Case(s)

For example, suppose you want to build two identical VM images where the only difference is the major version of a piece of software subsequently installed. In this case, I'd want to define a module that defines the VM source, and instantiate a copy of that source for each major version of the target software.

#### Potential References

https://learn.hashicorp.com/tutorials/packer/getting-started-parallel-builds
https://www.terraform.io/docs/modules/index.html

**Comment by SwampDragons** [comment]
This may be a duplicate of https://github.com/hashicorp/packer/issues/9154 

That said, it is already possible to use a source and then set specific custom fields inside a build block _as long as the source has not already set them_ See https://www.packer.io/docs/from-1.5/blocks/build/source for more details.

**Comment by ndimiduk** [comment]
> This may be a duplicate of #9154

Thanks. I figured there must be something requested already, but I couldn't come up with the search criteria.

> That said, it is already possible to use a source and then set specific custom fields inside a build block _as long as the source has not already set them_ See https://www.packer.io/docs/from-1.5/blocks/build/source for more details.

This looks promising, thank you!
