### ISSUE TITLE
"encrypt_boot": "false" still encrypts AMIs in aws accounts with "Always encrypt new EBS volumes"

### ISSUE THREAD

**Issue by wettowelreactor** [hashicorp/packer#10390]
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

"encrypt_boot": "false" fails to work for the "amazon-ebs" if the account has "Always encrypt new EBS volumes" enabled.
During the final copy step no-encrypt is not used so the AMI's created end up with encrypted root volumes.

#### Reproduction Steps

Set the "Always encrypt new EBS volumes" to true in an AWS account. Run any amazon-ebs builder with the "encrypt_boot": "false" set. You will end up with encrypted AMI's

### Packer version

From `packer_1.6.5`, possibly earlier

### Simplified Packer Buildfile

"builders": [{
        "type": "amazon-ebs",
        "access_key": "{{user `aws_access_key_id`}}",
        "secret_key": "{{user `aws_secret_key`}}",
        "associate_public_ip_address": "false",
        "ssh_interface": "private_ip",
        "vpc_id": "{{user `vpc_id`}}",
        "subnet_id": "{{user `subnet_id`}}",
        "security_group_id": "{{user `sg_id`}}",
        "region": "{{user `home_region`}}",
        "source_ami": "{{user `source-ami`}}",
        "shutdown_behavior": "stop",
        "instance_type": "t2.micro",
        "force_deregister": "false",
        "encrypt_boot": "false",
        "ssh_username": "ec2-user",
        "ami_name": "{{user `ami-name`}}",
    }],

### Operating system and Environment details

Amazon Linux 2
Ubuntu 18
RHEL7
RHEL8
CENTOS 7

**Comment by SwampDragons** [comment]
This is true; Packer can't override a global account setting, nor do I think it should. We should probably note this in the feature documentation though.
