### ISSUE TITLE
Different file provisioner behaviour with LXD vs Vagrant

### ISSUE THREAD

**Issue by rossrochford** [hashicorp/packer#10414]
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

Copying a directory to an instance results in a different target path with the LXD builder compared Vagrant

#### Reproduction Steps

```  
provisioner "file" {
    source = "/home/ross/code/build/vm_image/installation_scripts/" # with trailing slash
    destination = "/home/ubuntu/scripts"
  }
```

With Vagrant this places the contents of `installation_scripts` in `/home/ubuntu/scripts`

With LXD this places the contents of `installation_scripts` in `/home/ubuntu/scripts/installation_scripts`

### Packer version

1.6.4

### Simplified Packer Buildfile

lxd:
```
source "lxd" "base-image" {
  image = "ubuntu-daily:focal"
  profile = "default"
  output_image = "lxd-hashi-base"
  # name
  # launch_config = {
  # }
}


build {
  sources = ["source.lxd.base-image"]
   provisioner "file" {
    source = "/home/ross/code/build/vm_image/installation_scripts/" # with trailing slash
    destination = "/home/ubuntu/scripts"
  }
}
```

vagrant:

```
source "vagrant" "example" {
  communicator = "ssh"
  source_path = "${var.hashi_vagrant_repo_directory}/build_packer/ubuntu2004.box"
  provider = "virtualbox"
  add_force = true
  output_dir = "${var.hashi_vagrant_repo_directory}/build_packer/base_image"
}

build {
  sources = ["source.vagrant.example"]
   provisioner "file" {
    source = "/home/ross/code/build/vm_image/installation_scripts/" # with trailing slash
    destination = "/home/ubuntu/scripts"  
  }
}
```

### Operating system and Environment details

Ubuntu 20.04

### Log Fragments and crash.log files

Include appropriate log fragments. If the log is longer than a few dozen lines,
please include the URL to the [gist](https://gist.github.com/) of the log or
use the [Github detailed format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d) instead of posting it directly in the issue.

Set the env var `PACKER_LOG=1` for maximum log detail.

**Comment by SwampDragons** [comment]
I think you need to add a trailing slash to the destination directory path as well: https://www.packer.io/docs/provisioners/file#destination

Packer isn't aware of what OS architecture is running on the guest, so it is basically impossible for Packer to properly sanitize inputs for you.

**Comment by SwampDragons** [comment]
I never heard back on this, so I'm hoping my comment a couple months ago was helpful; closing this but we can reopen if you think there is something else we could do here.
