### ISSUE TITLE
Optional gp3 throughput parameter fails when not set

### ISSUE THREAD

**Issue by rmgates** [hashicorp/packer#10420]
#### Overview of the Issue

Recent changes to packer in 1.6.6 add additional support for gp3 but this now fails when the optional throughput parameter is not set even though it is marked as required: false.

Optional Parameter:
https://github.com/mtougeron/packer/blob/94606d896d4fcbaea50e2542c0c72656b65ac4ba/builder/amazon/common/block_device.go#L89

Hard check:
https://github.com/mtougeron/packer/blob/94606d896d4fcbaea50e2542c0c72656b65ac4ba/builder/amazon/common/block_device.go#L206

#### Reproduction Steps

Use gp3 in amazon-ebs without setting optional throughput parameter.

### Packer version

From `1.6.6`

### Simplified Packer Buildfile
```json
  "builders": [
    {
      "type": "amazon-ebs",
      "ami_block_device_mappings": [{
        "device_name": "/dev/sda1",
        "encrypted": true,
        "volume_size": 8,
        "volume_type": "gp3",
        "delete_on_termination": true
      }],
```

### Operating system and Environment details

Linux

### Log Fragments and crash.log files
```
Error: Failed to prepare build: "amazon-ebs"

1 error(s) occurred:
* Throughput must be between 125 and 1000 for device /dev/sda1
```

**Comment by officel** [comment]
I've run into the same thing.

It seems to be affected by a change in specifications on the AWS side.
https://awsapichanges.info/archive/changes/8875a3-ec2.html

When I added the throughput parameter to the json, it changed to the following error

```
Error: Failed to prepare build: "amazon-ebs"

1 error(s) occurred:

* IOPS must be between 3000 and 16000 for device /dev/xvda



==> Wait completed after 4 microseconds

==> Builds finished but no artifacts were created.
```

So I also added the iops parameter.
That seems to have done the trick.

**Comment by SwampDragons** [comment]
sounds like the validation is too strict. This should be easy enough to clean up.
