### ISSUE TITLE
iso_checksum_url and iso_urls generates "no checksum found" error in latest packer 1.6.6

### ISSUE THREAD

**Issue by ShibayanC** [hashicorp/packer#10423]
Hi,
I'm trying to build a CentOS8.2 MAAS image using packer 1.6.6. Pointing it to the iso repo and checksum it errors out as:
```
Error: Failed to prepare build: "qemu"
* no checksum found in:
http://mirrors.oit.uci.edu/centos/8.2.2004/isos/x86_64/CHECKSUM in
"file:http://mirrors.oit.uci.edu/centos/8.2.2004/isos/x86_64/CHECKSUM"
```

Packer1.6.6 works for urls with https certs (e.g. CentOS8.3), but since I'm looking for an older version of CentOS, the iso url has http not https.
Switching to an older packer version 1.6.0 this problem is resolved. It can pull from repositories without https certs. 

Steps to reproduce this issue
In centos8.json [1] replace the fields with the ones below:
- "centos8_iso_url": "http://mirrors.oit.uci.edu/centos/8.2.2004/isos/x86_64/CentOS-8.2.2004-x86_64-dvd1.iso"
- "centos8_sha256sum_url": "http://mirrors.oit.uci.edu/centos/8.2.2004/isos/x86_64/CHECKSUM"

Then execute: sudo PACKER_LOG=1 ./packer build centos8.json

From `packer version 1.6.6`

References:
[1] https://github.com/canonical/packer-maas/blob/master/centos8/centos8.json

====================  LOGS =================
sudo PACKER_LOG=1 ./packer build centos8.json
2020/12/23 17:58:55 [INFO] Packer version: 1.6.6 [go1.15.6 linux amd64]
2020/12/23 17:58:55 Checking 'PACKER_CONFIG' for a config file path
2020/12/23 17:58:55 'PACKER_CONFIG' not set; checking the default config file path
2020/12/23 17:58:55 Attempting to open config file: /home/name/.packerconfig
2020/12/23 17:58:55 [WARN] Config file doesn't exist: /home/name/.packerconfig
2020/12/23 17:58:55 Setting cache directory: /export/volb/git/packer-maas/centos8/packer_cache
2020/12/23 17:58:55 Creating plugin client for path: /export/volb/git/packer-maas/centos8/packer
2020/12/23 17:58:55 Starting plugin: /export/volb/git/packer-maas/centos8/packer []string{"/export/volb/git/packer-maas/centos8/packer", "plugin", "packer-builder-qemu"}
2020/12/23 17:58:55 Waiting for RPC address for: /export/volb/git/packer-maas/centos8/packer
2020/12/23 17:58:55 packer-builder-qemu plugin: [INFO] Packer version: 1.6.6 [go1.15.6 linux amd64]
2020/12/23 17:58:55 packer-builder-qemu plugin: Checking 'PACKER_CONFIG' for a config file path
2020/12/23 17:58:55 packer-builder-qemu plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/12/23 17:58:55 packer-builder-qemu plugin: Attempting to open config file: /home/name/.packerconfig
2020/12/23 17:58:55 packer-builder-qemu plugin: [WARN] Config file doesn't exist: /home/name/.packerconfig
2020/12/23 17:58:55 packer-builder-qemu plugin: Setting cache directory: /export/volb/git/packer-maas/centos8/packer_cache
2020/12/23 17:58:55 packer-builder-qemu plugin: args: []string{"packer-builder-qemu"}
2020/12/23 17:58:55 packer-builder-qemu plugin: Plugin address: unix /tmp/packer-plugin891324800
2020/12/23 17:58:55 packer-builder-qemu plugin: Waiting for connection...
2020/12/23 17:58:55 Received unix RPC address for /export/volb/git/packer-maas/centos8/packer: addr is /tmp/packer-plugin891324800
2020/12/23 17:58:55 packer-builder-qemu plugin: Serving a plugin connection...
2020/12/23 17:58:55 Creating plugin client for path: /export/volb/git/packer-maas/centos8/packer
2020/12/23 17:58:55 Starting plugin: /export/volb/git/packer-maas/centos8/packer []string{"/export/volb/git/packer-maas/centos8/packer", "plugin", "packer-post-processor-shell-local"}
2020/12/23 17:58:55 Waiting for RPC address for: /export/volb/git/packer-maas/centos8/packer
2020/12/23 17:58:55 packer-post-processor-shell-local plugin: [INFO] Packer version: 1.6.6 [go1.15.6 linux amd64]
2020/12/23 17:58:55 packer-post-processor-shell-local plugin: Checking 'PACKER_CONFIG' for a config file path
2020/12/23 17:58:55 packer-post-processor-shell-local plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/12/23 17:58:55 packer-post-processor-shell-local plugin: Attempting to open config file: /home/name/.packerconfig
2020/12/23 17:58:55 packer-post-processor-shell-local plugin: [WARN] Config file doesn't exist: /home/name/.packerconfig
2020/12/23 17:58:55 packer-post-processor-shell-local plugin: Setting cache directory: /export/volb/git/packer-maas/centos8/packer_cache
2020/12/23 17:58:55 packer-post-processor-shell-local plugin: args: []string{"packer-post-processor-shell-local"}
2020/12/23 17:58:55 packer-post-processor-shell-local plugin: Plugin address: unix /tmp/packer-plugin404093276
2020/12/23 17:58:55 packer-post-processor-shell-local plugin: Waiting for connection...
2020/12/23 17:58:55 Received unix RPC address for /export/volb/git/packer-maas/centos8/packer: addr is /tmp/packer-plugin404093276
2020/12/23 17:58:55 packer-post-processor-shell-local plugin: Serving a plugin connection...
2020/12/23 17:58:55 Preparing build: qemu
2020/12/23 17:58:55 packer-builder-qemu plugin: use detected accelerator: kvm
2020/12/23 17:58:55 packer-builder-qemu plugin: CpuCount 0 too small, using default: 1
2020/12/23 17:58:56 Build 'qemu' prepare failure: 1 error(s) occurred:

* no checksum found in: http://mirrors.oit.uci.edu/centos/8.2.2004/isos/x86_64/CHECKSUM in "file:http://mirrors.oit.uci.edu/centos/8.2.2004/isos/x86_64/CHECKSUM"

1 error(s) occurred:

Error: Failed to prepare build: "qemu"
* no checksum found in:

http://mirrors.oit.uci.edu/centos/8.2.2004/isos/x86_64/CHECKSUM in
"file:http://mirrors.oit.uci.edu/centos/8.2.2004/isos/x86_64/CHECKSUM"

1 error(s) occurred:
2020/12/23 17:58:56 Build debug mode: false

2020/12/23 17:58:56 Force build: false
2020/12/23 17:58:56 On error: 
2020/12/23 17:58:56 Waiting on builds to complete...
==> Wait completed after 3 microseconds
* no checksum found in:
==> Builds finished but no artifacts were created.
2020/12/23 17:58:56 [INFO] (telemetry) Finalizing.
http://mirrors.oit.uci.edu/centos/8.2.2004/isos/x86_64/CHECKSUM in
"file:http://mirrors.oit.uci.edu/centos/8.2.2004/isos/x86_64/CHECKSUM"

==> Wait completed after 3 microseconds

==> Builds finished but no artifacts were created.
2020/12/23 17:58:56 waiting for all plugin processes to complete..

**Comment by ahmedjabli** [comment]
A

**Comment by SwampDragons** [comment]
Did you use any of the other versions between 1.6.0 and 1.6.6? Knowing this will help me pinpoint where the regression occurred more easily.

**Comment by c0DeR2020** [comment]
No, I haven't tried any other versions.

**Comment by The-Loeki** [comment]
Packer 1.7.1 Fedora 33 does this too:

```
            "iso_checksum": "file:https://dl.fedoraproject.org/pub/fedora/linux/releases/33/Server/x86_64/iso/Fedora-Server-33-1.2-x86_64-CHECKSUM",
            "iso_url": "https://dl.fedoraproject.org/pub/fedora/linux/releases/33/Server/x86_64/iso/Fedora-Server-netinst-x86_64-1.2.iso",
```

results in 

```
* no checksum found in: https://dl.fedoraproject.org/pub/fedora/linux/releases/33/Server/x86_64/iso/Fedora-Server-33-1.2-x86_64-CHECKSUM in "file:https://dl.fedoraproject.org/pub/fedora/linux/releases/33/Server/x86_64/iso/Fedora-Server-33-1.2-x86_64-CHECKSUM"
```

**Comment by pkrul** [comment]
This still occurs up to 1.7.9-dev, and is IMHO related to go-getter. 

Go-getter only checks if lines in the checksum file have either two (GNU), four (BSD), or no words, and tries to further process those lines as checksums, which fails if the line is a  comment (#), or is PGP-signed, as seen in go-getter/checksum.go, functions ChecksumFromFile() and  parseChecksumLine().

Any checksum file from Red Hat-related distributions (RHEL, CentOS 8.5, Alma Linux 8.5, Rocker Linux 8.5, Fedora) set in iso_checksum as 'file:<uri>' that is retrieved using 'packer validate .'  will result in "* no checksum found in: [...]" before borking.

Example contents from the Fedora 33 server ISO checksum file mentioned above:

<pre>-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

# Fedora-Server-dvd-x86_64-33-1.2.iso: 2076180480 bytes
SHA256 (Fedora-Server-dvd-x86_64-33-1.2.iso) = 4fe38b45a4c788927ddfdfb224c414f138226a75f27a287995d802cba3cb89d4
# Fedora-Server-netinst-x86_64-33-1.2.iso: 719323136 bytes
SHA256 (Fedora-Server-netinst-x86_64-33-1.2.iso) = 1f1f018e78f0cc23d08db0c85952344ea5c200e67b672da5b07507c066a52ccf
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEEljor6wIAlgj+Z+pCSf13SZVw/zEFAl+S8gUACgkQSf13SZVw
[...]</pre>

See also:
#https://github.com/hashicorp/go-getter/issues/217
#https://github.com/hashicorp/nomad/issues/7723

**Comment by azr** [comment]
Hello there, I recently opened #11495 which should allow checksuming files with a gpg-generated checksum (by ignoring the comments).

Could you tell me if that solves the issue for you ? Binaries from the branch be found in the [PR artifacts](https://app.circleci.com/pipelines/github/hashicorp/packer/11188/workflows/815bae74-040a-4f4c-b4dc-7875102db4f0/jobs/137625/artifacts).

I now wonder if we should have  a special case that will actually also do more with the pgp file and a public key. I'd need to read more about this.
