### ISSUE TITLE
oracle-oci doesn't support VM.Standard.E3.Flex and VM.Standard.E4.Flex shapes

### ISSUE THREAD

**Issue by fcecagno** [hashicorp/packer#10422]
When an instance is created, Oracle requires a ShapeConfig for E3 and E4 instances, which specifies the number of oCPUs and amount of memory. However, there's no way to set it within the builder, and Oracle rejects the instance launch.
I'd suggest to create optional attributes `shape_config_ocpu` and `shape_config_memory`, which would set the ShapeConfig when creating the instance. The default values for this shape, according to the OCI utility, are 1 ocpu and 16 GB of memory.

**Comment by pete198016** [comment]
Hello,
Is there any update on adding E3 Flex shape option into packer ?

**Comment by ravi-devarakonda** [comment]
Hi, do we have an update on adding E3.Flex support in packer?

**Comment by SwampDragons** [comment]
Not right now; we have a long backlog. That said, PRs are always welcome and we always try to prioritize reviews for community contributions.

**Comment by fcecagno** [comment]
Just updated title and description to consider E4.Flex as well.
