### ISSUE TITLE
Failure to reconnect SSH after reboot

### ISSUE THREAD

**Issue by palfrey** [hashicorp/packer#10424]
#### Overview of the Issue

I've got a build (https://github.com/palfrey/guix-vm/blob/master/packer/guix-vm.json) failing under Github Actions. Pretty sure this is a duplicate of https://github.com/hashicorp/packer/issues/7002

#### Reproduction Steps

1. Run `packer build guix-vm.json`

I think this worked ok in earlier Packer versions though...

### Packer version

1.6.6

### Simplified Packer Buildfile

https://github.com/palfrey/guix-vm/blob/master/packer/guix-vm.json

### Operating system and Environment details

MacOS 10.15, doing Guix 1.2 install. Note that this is on MacOS not say Linux as the Linux boxes can't do recursive virtual environments, and so VirtualBox can't run there, but the Macs can.

### Log Fragments and crash.log files

https://github.com/palfrey/guix-vm/runs/1605690824?check_suite_focus=true

**Comment by SwampDragons** [comment]
Looking at those logs, this may be an issue with the temp script cleanup -- let me know if setting `skip_clean: true` resolves it: https://www.packer.io/docs/provisioners/shell#skip_clean

**Comment by SwampDragons** [comment]
Closing, since we never heard back. Hopefully the above comment was the issue.
