### ISSUE TITLE
aws_secretsmanager crashes on non-string JSON values

### ISSUE THREAD

**Issue by ajbdev** [hashicorp/packer#10421]
#### Overview of the Issue

An AWS secret manager JSON secret that contains non-string values will cause packer to crash with a go marshaling error:

```
template: root:1:3: executing "root" at <aws_secretsmanager
`developmentDBSecret52FA5B0R-RsFGddtv` `host`>: error calling
aws_secretsmanager: json: cannot unmarshal number into Go value of type string
```

#### Reproduction Steps

Steps to reproduce this issue

1. Store a secret in AWS secrets manager with a number value. E.g:

```
{
  "port": 5432
}
```
2. Use the `aws_secretsmanager` function to retrieve a secret in a packer config

Observed result: attempting to retrieve any key will throw a JSON marshaling failure. 

### Packer version

1.6.6

### Simplified Packer Buildfile

```
...
"variables": {
  "var1": "aws_secretsmanger `secretname` `keyname`"
}
```

### Operating system and Environment details

Ubuntu 20 amd64

**Comment by ajbdev** [comment]
My golang-fu is too weak to know the proper solution here, but I think the offending code is here: https://github.com/hashicorp/packer-plugin-sdk/blob/main/template/interpolate/aws/secretsmanager/secretsmanager.go#L79-L87

**Comment by SwampDragons** [comment]
Yeah, it looks like the template function only supports string values for secrets; the docs should be clearer on this.

**Comment by SwampDragons** [comment]
you're right about the location of the issue -- we could probably unmarshal into a map[string]interface{} and cast it into the map[string]string var.

**Comment by teddylear** [comment]
@SwampDragons I can take a look into this if that's alright

**Comment by teddylear** [comment]
@SwampDragons I created [this PR](https://github.com/hashicorp/packer-plugin-sdk/pull/18) to address the outlined issue. Please let me know if there's anything that needs to be changed. There is still the question of if this should be changed to return an interface instead of string, but my understanding is that would be a more large scale refactor.

**Comment by teddylear** [comment]
@SwampDragons This should be able to be closed now that PR is merged.

**Comment by azr** [comment]
Right ! Thanks @teddylear
