### ISSUE TITLE
Ansible fails to resolve path to file with template validate %s

### ISSUE THREAD

**Issue by joubbi** [hashicorp/packer#10427]
#### Overview of the Issue

When running a playbook containing the ansible.builtin.template module with a validation command, Ansible fails to find the file generated by the template in Packer. 
It is the variable %s that breaks. It seems to me that the variable %s points to the wrong path (See part of debug at the bottom).

##### Example snippet from a failing playbook
```
- name: "Configure aide"
  template:
    src: "aide.conf.j2"
    dest: "{{ aide_conf_path }}"
    validate: "{{ aide_path.stdout }} -D -c %s"
```

Same playbook runs fine with ansible-playbook from the same machine to the same image once the image is created without the offending playbook.

#### Reproduction Steps

Install https://galaxy.ansible.com/ahuffman/aide
Invoke that role from Packer. This will fail due to the validate row in the main.yml task.

Comment the row containing validate and the build will succeed.
Build an image without the role, run the image in a virtual machine and run the role against the machine and it will work as expected.

### Packer version

Packer v1.6.6

### Simplified Packer Buildfile
```
"provisioners": [
    {
      "type": "ansible",
      "playbook_file": "../ansible/aide.yml",
      "extra_arguments": [ "-vvvv" ]
    }
]
```
```
$ cat ../ansible/aide.yml 
- name: "Install and configure AIDE"
  hosts: "default"
  roles:
    - "ahuffman.aide"
```

### Operating system and Environment details

```
$ cat /etc/lsb-release 
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=20
DISTRIB_CODENAME=ulyana
DISTRIB_DESCRIPTION="Linux Mint 20 Ulyana"

$ kvm --version
QEMU emulator version 4.2.1 (Debian 1:4.2-3ubuntu6.10)
Copyright (c) 2003-2019 Fabrice Bellard and the QEMU Project developers

$ ansible --version
ansible 2.10.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/farid/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/farid/.local/lib/python3.8/site-packages/ansible
  executable location = /home/farid/.local/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
```

### Log Fragments and crash.log files
    qemu: fatal: [default]: FAILED! => {
    qemu:     "changed": false,
    qemu:     "checksum": "402ef66e0f34f01c23ba31f8ea8f7ed64416d27e",
    qemu:     "diff": [],
    qemu:     "exit_status": 17,
    qemu:     "invocation": {
    qemu:         "module_args": {
    qemu:             "_original_basename": "aide.conf.j2",
    qemu:             "attributes": null,
    qemu:             "backup": false,
    qemu:             "checksum": "402ef66e0f34f01c23ba31f8ea8f7ed64416d27e",
    qemu:             "content": null,
    qemu:             "dest": "/etc/aide.conf",
    qemu:             "directory_mode": null,
    qemu:             "follow": false,
    qemu:             "force": true,
    qemu:             "group": null,
    qemu:             "local_follow": null,
    qemu:             "mode": null,
    qemu:             "owner": null,
    qemu:             "remote_src": null,
    qemu:             "selevel": null,
    qemu:             "serole": null,
    qemu:             "setype": null,
    qemu:             "seuser": null,
    qemu:             "src": "~farid/.ansible/tmp/ansible-tmp-1609189480.6933067-48840-116779293865971/source",
    qemu:             "unsafe_writes": false,
    qemu:             "validate": "/usr/sbin/aide -D -c %s"
    qemu:         }
    qemu:     },
    qemu:     "msg": "failed to validate",
    qemu:     "stderr": "Cannot access config file:/rootfarid/.ansible/tmp/ansible-tmp-1609189480.6933067-48840-116779293865971/source:No such file or directory\nNo config defined\nConfiguration error\n",
    qemu:     "stderr_lines": [
    qemu:         "Cannot access config file:/rootfarid/.ansible/tmp/ansible-tmp-1609189480.6933067-48840-116779293865971/source:No such file or directory",
    qemu:         "No config defined",
    qemu:         "Configuration error"

_Note_ My local user running Packer is farid. To me the paths in the above log looks strange/wrong: `~farid/.ansible/..`and `/rootfarid/.ansible/tmp/ansible-tmp-...`

**Comment by SwampDragons** [comment]
I'm not super familiar with Ansible -- is the path being mangled this jinja2 file `src: "aide.conf.j2"` or is it the destination path being provided by aide_conf_path? if the latter, how is aide_conf_path being supplied?

**Comment by joubbi** [comment]
I sort of found the reason for this problem.
I had not set the `user` variable for the Ansible provisioner.
The effects you get by not setting the user are really strange. It's not obvious at all where the strange errors originate from.

This particular bug can be closed, since it was a user error.
But I suggest that the documentation is made more clear about the user variable.
I can't come up with a use case where you would not want to set this to the same user as the communicator.
To me it would make more sense if it was set to the same user by default.
Also, it took me a while to understand that the word communicator is the same as ssh_username used by the builder.

Maybe at least change this sentence:
"If you want to use the same user as the communicator, you will need to manually set it again in this field."
to
"You probably want to use the same user as the communicator (ssh_username), you will need to manually set it again in this field."

It would also be really nice to get a meaningful error message when the Ansible user tries to do something which it doesn't have permissions to, as in my case above. But I understand if that is too complex to handle.
