### ISSUE TITLE
No configuration parameters written in vsphere iso builder

### ISSUE THREAD

**Issue by jorgelon** [hashicorp/packer#10434]
#### Overview of the Issue

The configuration_parameters are not written to the vmx file
It is the same case as described in https://discuss.hashicorp.com/t/how-do-the-configuration-parameters-in-vsphere-iso-builder-work/17454

### Packer version

1.6.6

### Simplified Packer Buildfile

      "configuration_parameters": {
        "msg.autoanswer": "FALSE",
        "svga.vramSize": "16777216"
      },

### Operating system and Environment details

Linux x86_64

**Comment by jorgelon** [comment]
im sorry. seems to be working in 1.6.6

**Comment by jorgelon** [comment]
Cheched that the "svga.vramSize": "16777216" line has not been written in the vmtx file

**Comment by rao76** [comment]
> Checked that the "svga.vramSize": "16777216" line has not been written in the vmtx file but the msg.autoanswer yes

I'm also dealing with the same problem. Certain configuration parameters gets discarded. Have been trying to add the following configuration parameters and the last 5 parameters (soundcard) were not written to the .vmx file. 

Hope it gets fixed soon.

            "configuration_parameters": {
                "vmxnet3.rev.30":                       "FALSE",
                "svga.numDisplays":                     "2",
                "devices.hotplug":                      "FALSE",
                _"sound.present":                        "TRUE",
                "sound.allowGuestConnectionControl":    "FALSE",
                "sound.virtualDev":                     "hdaudio",
                "sound.fileName":                       "-1",
                "sound.autodetect":                     "TRUE"_
            },
