### ISSUE TITLE
Allow logging of vcenter api call to vsphere-iso builder

### ISSUE THREAD

**Issue by emaayan** [hashicorp/packer#10433]
it would be great if we could actually see what api calls are being done to vcenter (something similar to vsphere recording sessions on the webclient) to be able to debug and troubleshoot several issues.

**Comment by jhawk28** [comment]
I don't think the govmomi API supports this. One would need to manually add all these logging messages. The current approach where you can see the step and error messages if something goes wrong provides pretty good tracing to what packer is doing. What issues are you seeing that the current logging doesn't help debug/troubleshoot?

**Comment by emaayan** [comment]
i believe it's related to this issue, https://github.com/hashicorp/packer/issues/9629 
i discovered that when i export with packer a vm which i created in vsphere 6.7 on esxi 6.5, it's created with vmw:BootOrderSection element which prevents it from being imported into esxi 6.5 and 6.0 (import times out, empty disks are created)
i attempted to replace the packer export with govc one in post processors , which resulted in an OVF without a vmw:BootOrderSection element that i could import into esxi 6,6.5 but then i couldn't import it back to vsphere 6.7 and esxi 6.5 (the same machine that created it) 
currently the only thing that works in both cases is the ovftool export itself which i use as post processor.
i'm assuming that eventually the same api is being used to export the vm only with different parameters .

**Comment by jhawk28** [comment]
I don't think that logging will help that issue. The ovftool seems to be the most mature of the export tools and it appears to do some fixes locally that are not captured in the govc code. When I added the export capability, I based it on the govc code assuming that it was doing things correctly. I have some thoughts about how to fix the export issue, but I'll post those on that issue.

**Comment by emaayan** [comment]
using the web ui also does it correctly, doesn't the ui also use the api?
