### ISSUE TITLE
Suppress provisioner command containing secrets

### ISSUE THREAD

**Issue by tjbaker** [hashicorp/packer#10436]
How can I suppress the echo of the provisioner command that contains secrets passed to it?  A condensed test is as follows:

```
locals {
  secret = aws_secretsmanager("/api_key", null)
  sensitive = true
}

build {
  sources = ["source.amazon-ebs.test"]

  provisioner "ansible-local" {
    command           = "SECRET=${local.secret} PYTHONUNBUFFERED=1 ansible-playbook"
    playbook_file     = "playbook.yml"
```

The ec2 instance running the ansible-local playbook does not have aws creds to retrieve the secret and I need to pass it in.  How can I suppress the echo of `Executing Ansible: cd /tmp/packer-provisioner-ansible-local && SECRET=xxx PYTHONUNBUFFERED=1 ...`

Or asked another way, how can I pass secrets as environment variables into ansible-local and not have them print to stdout?

Thanks!

**Comment by SwampDragons** [comment]
Hi! looks like the sensitive variable filtering isn't implemented for locals. It does work for variables, so a block like 

``` hcl
variable "mysecret" {
  sensitive = true
  default = "supersecret"
}
```

should work. I'll figure out whether this is an oversight or intended behavior and get back to you.

**Comment by azr** [comment]
Yes and just to add a little more precision, the following snippet creates two variables:

```hcl
locals {
  secret = aws_secretsmanager("/api_key", null)
  sensitive = true
}
```

`local.sensitive` and  `local.secret`

**Comment by tjbaker** [comment]
aws_secretsmanager_key function can't be used in in a variable block though...
