### ISSUE TITLE
Broken links in Azure-ARM builders documentation

### ISSUE THREAD

**Issue by spellinn** [hashicorp/packer#10439]
There are a number of broken links in the Azure-ARM documentation https://www.packer.io/docs/builders/azure-arm

Both appear several times in the page:
https://azure.microsoft.com/en-us/documentation/articles/resource-groups-vm-searching/
https://github.com/hashicorp/packer/tree/master/examples/azure

**Comment by nywilken** [comment]
Thanks for reaching out. We've made a few directory changes that caused part of this issue. We are looking at adding a broken link checker to help catch these before we deploy. Thanks again for reporting.
