### ISSUE TITLE
Docs: 'Edit this page' links contains the wrong branch

### ISSUE THREAD

**Issue by unixlab** [hashicorp/packer#10446]
On all docs page there is the link 'Edit this page' on the bottom of the page.
If you click the link you will get a 404 - Page Not Found.
For me it looks like all links contains the branch `main`, but it should be `master`.

e.g for the page https://www.packer.io/docs/communicators/ssh
the link for 'Edit this page' is https://github.com/hashicorp/packer/blob/main/website/content/docs/communicators/ssh.mdx
but should be https://github.com/hashicorp/packer/blob/master/website/content/docs/communicators/ssh.mdx

I wasn't able to figure out were this is configured, so decided to open this issue instead of a PR.

**Comment by nywilken** [comment]
Thanks, this is good to know. We'll work on getting this squared away.
