### ISSUE TITLE
Add aws session-manager to published packer docker container

### ISSUE THREAD

**Issue by nitrocode** [hashicorp/packer#10443]
Please search the existing issues for relevant feature requests, and use the
reaction feature
(https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
to add upvotes to pre-existing requests.

#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

I'd like to stop using ssh in favor of ssm. I use the current hashicorp/packer docker container and would like to continue using it, however, I'm unable to run builds using ssm with the container without having to build a new hashicorp/packer-session-manager container.

Would it be possible if the aws session-manager plugin can be added so ssm works out-of-the-box when using the official hashicorp/packer docker container ?

#### Use Case(s)

See above

#### Potential configuration

```
        "ssh_interface": "session_manager",
        "communicator": "ssh",
```

#### Potential References

N/A

**Comment by SwampDragons** [comment]
It's not really feasible for us to make the official docker container contain literally all possible packer dependencies -- we'd end up with a very large container indeed. See my comment here for context: https://github.com/hashicorp/docker-hub-images/issues/100

The good news is our containers are very simple and you should not have trouble building your own based on https://github.com/hashicorp/docker-hub-images/blob/master/packer/Dockerfile-light
