### ISSUE TITLE
Packer v1.6.5 with Amazon EBS Builder - Debug mode causes hang at pre-validating AMI name

### ISSUE THREAD

**Issue by MysticalMount** [hashicorp/packer#10463]
Forgive me if this is off base, but I am experimenting with enabling debug mode for our pipeline.

When running with Packer v1.3.1, our most commonly used, very out of date version of Packer, enabling debug mode using the following command:

            sh """
                set -o pipefail

                export PACKER_LOG=1

                ${packer} build -debug \
                -var 'source_ami_id=${source_ami_id}' \
                -var 'source_ami_name=${source_ami_name}' \
                -var-file=vars.json \
                -var-file=metadata.json \
                main.json | tee build.log
            """
            
 Works fine and results in full debug messages being presented and the build completing.  As can be seen here:
 

==> Builds finished. The artifacts of successful builds are:
2021/01/11 13:37:24 machine readable: amazon-ebs,artifact-count []string{"1"}
==> Builds finished. The artifacts of successful builds are:
2021/01/11 13:37:24 machine readable: amazon-ebs,artifact []string{"0", "builder-id", "mitchellh.amazonebs"}
2021/01/11 13:37:24 machine readable: amazon-ebs,artifact []string{"0", "id", "eu-west-1:ami-XXXX"}
2021/01/11 13:37:24 machine readable: amazon-ebs,artifact []string{"0", "string", "AMIs were created:\neu-west-1: ami-\n"}
2021/01/11 13:37:24 machine readable: amazon-ebs,artifact []string{"0", "files-count", "0"}
2021/01/11 13:37:24 machine readable: amazon-ebs,artifact []string{"0", "end"}
eu-west-1: ami-XXXX
2021/01/11 13:37:24 [INFO] (telemetry) Finalizing.
--> amazon-ebs: AMIs were created:
eu-west-1: ami-XXXX
 
 However when we use the same command but with Packer v1.6.5 [also utilising amazon-ebs builder] - it seems to hang indefinitely at the following stage:
 
 2021/01/11 10:51:27 packer1.6.5 plugin: Checking 'PACKER_CONFIG' for a config file path
2021/01/11 10:51:27 packer1.6.5 plugin: 'PACKER_CONFIG' not set; checking the default config file path
2021/01/11 10:51:27 packer1.6.5 plugin: Attempting to open config file: /var/jenkins_home/.packerconfig
2021/01/11 10:51:27 packer1.6.5 plugin: [WARN] Config file doesn't exist: /var/jenkins_home/.packerconfig
2021/01/11 10:51:27 packer1.6.5 plugin: Setting cache directory: /var/jenkins_home/workspace/XXXXXX/packer_cache
2021/01/11 10:51:27 packer1.6.5 plugin: args: []string{"packer-provisioner-powershell"}
2021/01/11 10:51:27 packer1.6.5 plugin: Plugin address: unix /tmp/packer-plugin371706263
2021/01/11 10:51:27 packer1.6.5 plugin: Waiting for connection...
2021/01/11 10:51:27 Received unix RPC address for /usr/local/bin/packer1.6.5: addr is /tmp/packer-plugin371706263
2021/01/11 10:51:27 packer1.6.5 plugin: Serving a plugin connection...
2021/01/11 10:51:27 Preparing build: amazon-ebs
2021/01/11 10:51:27 packer1.6.5 plugin: [INFO] (aws): No AWS timeout and polling overrides have been set. Packer will default to waiter-specific delays and timeouts. If you would like to customize the length of time between retries and max number of retries you may do so by setting the environment variables AWS_POLL_DELAY_SECONDS and AWS_MAX_ATTEMPTS or the configuration options aws_polling_delay_seconds and aws_polling_max_attempts to your desired values.
2021/01/11 10:51:27 Build debug mode: true
2021/01/11 10:51:27 Force build: false
2021/01/11 10:51:27 On error: 
2021/01/11 10:51:27 Debug enabled, so waiting for build to finish: amazon-ebs
2021/01/11 10:51:27 Starting build run: amazon-ebs
2021/01/11 10:51:27 Running builder: amazon-ebs
2021/01/11 10:51:27 [INFO] (telemetry) Starting builder amazon-ebs
Debug mode enabled. Builds will not be parallelized.
[1;32mamazon-ebs: output will be in this color.[0m

2021/01/11 10:51:27 packer1.6.5 plugin: [INFO] AWS Auth provider used: "SharedCredentialsProvider"
2021/01/11 10:51:27 packer1.6.5 plugin: Found region eu-west-1
2021/01/11 10:51:27 packer1.6.5 plugin: [INFO] AWS Auth provider used: "SharedCredentialsProvider"
[1;32m==> amazon-ebs: Prevalidating any provided VPC information[0m
[1;32m==> amazon-ebs: Prevalidating AMI Name: ami-unencrypted-XXXX
 
 As far as I can tell this is could be an issue - any advice otherwise on how to circumvent this would be appreciated.

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out! That -debug flag indicates that you want manual interaction, and it pauses the build between steps. The pre-validate step you see it "freezing" at is the first step that it would pause after, and I think what's happening is that you're preserving the verbose log output but not the ui output because of the way you're teeing the output... I think if you ran this manually you'd see a UI line along the lines of "pausing after step pre-validate, press enter to continue..." Not sure why it worked in 1.3.1 cause packer should have frozen there too but I think since then we modified tty stuff which may be relevant.

Anyway, if all you want is verbose logs,  `export PACKER_LOG=1` is really all you need, not that debug flag. And if you want the logs to go to a logfile (including UI output) instead of using tee you can set a log path directly using the "PACKER_LOG_PATH" environment variable. So your final command will look like: 

export PACKER_LOG=1
export PACKER_LOG_PATH=build.log
${packer} build -debug \
-var 'source_ami_id=${source_ami_id}' \
-var 'source_ami_name=${source_ami_name}' \
-var-file=vars.json \
-var-file=metadata.json \
main.json

**Comment by MysticalMount** [comment]
Hi Megan/SwampDragon, thats very helpful, thanks for prompt response!  Forgive me for perhaps overlooking the obvious in this area!

Im in the UK so once Im back in the office tomorrow morning Ill give that a whirl and report back!

**Comment by MysticalMount** [comment]
Hi - I can confirm, after some further testing that the above does resolve our issue.  We have noticed that the pipeline output for the generated AMI differs between versions, later versions are prefixed with "AMI:" - however this has no relevance to the original issue.  Thanks SwampDragon/Megan - closing ticket.
