### ISSUE TITLE
Unable to provision Packer Builder EC2 instance

### ISSUE THREAD

**Issue by jtravell** [hashicorp/packer#10479]
Do or can the Amazon Builders for Packer have a way of specifying a provisioning script to run on the "Packer Builder" EC2 instance that the Packer Amazon Builder will create in AWS?  

Specifically, we are getting an error indicating that the command "ec2-bundle-vol" is not recognized by the Packer Builder EC2 instance when Packer uses an Amazon Linux 2 AMI as the base AMI.  The resolution seems to involve installing the AMI Tools on the Amazon Linux EC2 instance.  But the whole reason we are using Packer is to automate AMI creation, so it seems silly to manually create an AMI for use with an automated tool with Packer.  

Here is the link to the Packer Amazon Builder we are using when this error appears:  https://www.packer.io/docs/builders/amazon/instance  
  
>Can you show a way that we can run a provisioning script on the Packer Builder EC2 instance before Packer does its normal operations on the same Packer Builder EC2 instance? 

There must be a JSON property we can add pointing to a shell script that Packer would upload and run.  If not, there must be an easy workaround.

**Comment by SwampDragons** [comment]
The bundle volume step happens after you provision the instance and I believe it runs on the instance being provisioned, so I think you should be able to install the command with a script as part of the provisioning.

**Comment by jtravell** [comment]
@SwampDragons That does not really answer my question.  At this point, it seems the only solution is to use the AWS vendor-specific CLI to create a base image in what is turning out to be a significant effort.  
  
I have created a script that does install the library that includes the `ec2-bundle-vol` command.  But the script is many lines long, which does not seem to fit into any space that Packer makes available.  

If you could show exactly the syntax required to get Packer to upload and run a script before it runs commands like `ec2-bundle-vol`, then I could try that.  Does any such command exist that could be included in the Packer `json`?

**Comment by SwampDragons** [comment]
You would use the shell provisioner: https://www.packer.io/docs/provisioners/shell to run the script, using the "script" option instead of the "inline" option. 

```
{
  "provisioners": [
    {
      "type": "shell",
      "script": "/local/path/to/install_ec2_tools.sh"
    }
  ]
}
```

Here's an example script for installing these tools, though I haven't tested it recently to make sure it still works: 

```
#!/bin/sh
echo "apt-get commands"
sudo apt-get update -y
sleep 10
sudo apt-get install -y ruby
sudo apt-get install -y unzip

echo "wget for ec2 ami tools"
wget https://s3.amazonaws.com/ec2-downloads/ec2-ami-tools.zip

echo "make directory"
sudo mkdir -p /usr/local/ec2

echo "unzip tools"
sudo unzip ec2-ami-tools.zip -d /usr/local/ec2

echo "Create /etc/profile.d/myenvvars.sh"
sudo touch /etc/profile.d/myenvvars.sh

echo "Installing kpartx, grub as required by ec2-ami-tools"
sudo apt-get install kpartx -y
sudo apt-get install grub -y

echo "add to etc/profile.d/myenvvars.sh export variable EC2_AMITOOL_HOME"
sudo bash -c 'echo "export EC2_AMITOOL_HOME=/usr/local/ec2/ec2-ami-tools-1.5.7" >> /etc/profile.d/myenvvars.sh'
sudo bash -c 'echo "export PATH=/usr/local/ec2/ec2-ami-tools-1.5.7/bin:$PATH:" >> /etc/profile.d/myenvvars.sh'
```

**Comment by jtravell** [comment]
@SwampDragons   Thank you.  We were able to figure it out after you pointed us in the right direction.
