### ISSUE TITLE
AWS EC2 instance using packer amazon-ebssurrogate AMI not booting up

### ISSUE THREAD

**Issue by arslan70** [hashicorp/packer#10480]
As the title says, ec2 instance fails to boot up. System status shows 1/2 health check failed. There is very little information in the system log. AWS support is not able to help either.

The main purpose to use amazon-ebssurrogate is to use arm64 architecture which is not supported by amazon-ebs. I doubt that its actually a packer issue, mostly like bad config on my part. Will appreciate some support 

### Packer version

1.6.6

### Simplified Packer Buildfile
[packer.json](https://gist.github.com/arslan70/4d15d4b6fdce9eccc60108293fc7db93)

### Operating system and Environment details

Source AMI: ami-0c582118883b46f4f (latest official amazonlinux2 AMI)
Target Instance family: c6gn
Architecture: arm64

**Comment by pmontanari** [comment]
Hi,

Same issue with for me.

I build an amzn2 X86_64 and arm64 in parallel, using same provisionning script and the generated arm64 AMI won't boot up.
The x86_64 is totally working.

The arm64 system logs have the following error :
```
[    7.469974] cloud-init[1916]: Cloud-init v. 19.3-5.amzn2 running 'init-local' at Wed, 17 Feb 2021 20:44:10 +0000. Up 7.36 seconds.
[[32m  OK  [0m] Started Initial cloud-init job (pre-networking).
[[32m  OK  [0m] Reached target Network (Pre).
         Starting LSB: Bring up/down networking...
[[1;31mFAILED[0m] Failed to start LSB: Bring up/down networking.
See 'systemctl status network.service' for details.
```
So I suspect a bug in the cleaning process when finalizing the image

**Comment by pmontanari** [comment]
So, I finally had it working by disabling predictable network interface names adding this to grub:

`GRUB_CMDLINE_LINUX_DEFAULT="net.ifnames=0 biosdevname=0"`

Now I can start any arm flavor.

Regards
