### ISSUE TITLE
unknown configuration key: '"from_scratch"'

### ISSUE THREAD

**Issue by jtravell** [hashicorp/packer#10507]
Several packer.io documentation pages for AWS Builders refer to a `from_scratch` setting that can be used instead of `source_ami`, but when we try to use `"from_scratch": true` instead of `source_ami` as mentioned in [this documentation](https://www.packer.io/docs/builders/amazon/ebssurrogate#ami-configuration), we get the following error message when we run `packer build ourtemplate.json` :  

    2021/01/21 13:39:42 Preparing build: amazon-ebssurrogate
    1 error occurred:
    2021/01/21 13:39:42 Build 'amazon-ebssurrogate' prepare failure: 1 error occurred:
        * unknown configuration key: '"from_scratch"'
        * unknown configuration key: '"from_scratch"'

The reason this is a bug is that use of `from_scratch` breaks the `ebssurrogate` builder even though every AWS Packer Builder has documentation that refers to `from_scratch` as if `from_scratch` is a valid key.  Digging deeper, the only AWS builder on packer.io that seems to give a fully-spelled-out example of using `from_scratch` is the `aws-chroot` builder, but when we try to use the `aws-chroot` builder we get an error indicating that the `aws-chroot` builder does not work on Windows.  Surely there must be a Packer AWS builder that runs on windows and that is able to orchestrate a raw `from_scratch` installation using an `iso` to create a Linux AMI on AWS, given that the packer.io docs for every AWS builder gives reference to `from_scratch` as a valid property.  

Please show clear documentation describing how to use a raw `iso` to build an AMI completely from scratch.  This functionality must exist if the `from_scratch` mentioned in the docs is valid.  
  
A link to documentation for this with AWS Builders would be sufficient.

**Comment by sylviamoss** [comment]
Hey there!  `from_scratch` is available only to amazon-chroot https://www.packer.io/docs/builders/amazon/chroot#from_scratch, but the docs are confusing because of that piece of information in the `source_ami` option, so I think that should be updated.

**Comment by jtravell** [comment]
@sylviamoss Are you saying that we can only run packer on Linux if we want to build `from_scratch`?  
  
When we try to run the `amazon-chroot` builder using Packer from a Windows machine, the build fails with a message that `amazon-chroot` does not work on Windows.

**Comment by SwampDragons** [comment]
That's correct, you can only do chroot builds on *nix. I don't think the concept of chroot even exists on Windows, and I've not ever used a Windows equivalent.

You may be able to use the ebssurrogate builder instead to meet your needs. https://www.packer.io/docs/builders/amazon/ebssurrogate

**Comment by SwampDragons** [comment]
Sorry, I didn't read your first comment closely enough to realize you'd started out on ebssurrogate. I believe that for this builder, `source_ami` is the ami of the instance being launched, not the volume being provisioned and eventually saved into its own AMI. You'd still be able to build your attached volume however you like, i.e. basically from scratch.

**Comment by SwampDragons** [comment]
I'm pushing a fix to the docs to remove a reference to from_scratch from the amazon-ebssurrogate builder.

**Comment by jtravell** [comment]
@SwampDragons Are you saying that the ebssurrogate builder can be used to create linux images from scratch, meaning from an iso?  If so, can you point to documentation on how to do this?  

There are very big implications of this because it would be a lot easier for Packer to run on a windows server from which Packer's under-the-hood automation would spin up an ephemeral linux Packer Builder instance that would then create the new AMI from scratch.  

Here is the comment of yours from above that causes us to ask if you mean that we can run Packer on a Windows machine while Packer manipulates remote cloud resources to create a new AMI from scratch:  

    I believe that for this builder, source_ami is the ami of the instance being launched, not the volume being provisioned 
    and eventually saved into its own AMI. You'd still be able to build your attached volume however you like, i.e. basically 
    from scratch.

Please clarify.  Thank you.

**Comment by SwampDragons** [comment]
No, I thought you were trying to build a windows volume. I don't think you can build a linux root volume on a windows surrogate. Why do you need the Packer builder to run on Windows if you're trying to build a linux instance?
