### ISSUE TITLE
Error: Unhandled builder type: []uint8

### ISSUE THREAD

**Issue by kelvSYC** [hashicorp/packer#10515]
#### Overview of the Issue

Currently a beginner with Packer, and I am currently using a simple HCL2 file. When trying to run my file, the shell provisioner always fails with the error

```
unhandled builder type: []uint8
```

When run with the `-on-error=ask` option, and manually logging in to the provisioned host, I do not see any evidence that the command from the provisioner was run.

A cursory glance at `hcl2template/types.hcl_post-processor.go`, where a similar issue (#9583) was raised in the past, suggests that the type is indeed not handled, lending to the credence that this may be an HCL2 issue.

#### Reproduction Steps

This issue was spotted with the Lumos Labs Orka plugin, using its Orka builder. As of this point, I have not tested a similar JSON file to see whether the issue is specifically relating to HCL2 handling, or whether the issue relates to Packer/Orka integration

### Packer version

1.6.6

### Simplified Packer Buildfile

```
source "orka" "orka" {
    // Specific settings have been redacted due to containing secrets and other Orka-specific details
}

build {
  sources = ["source.orka.orka"]
  provisioner "shell" {
    inline = ["touch packer-ran-successfully"]
  }
}
```

### Operating system and Environment details

macOS Catalina 10.15.7

### Log Fragments and crash.log files

Include appropriate log fragments. If the log is longer than a few dozen lines,
please include the URL to the [gist](https://gist.github.com/) of the log or
use the [Github detailed format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d) instead of posting it directly in the issue.

Set the env var `PACKER_LOG=1` for maximum log detail.

**Comment by SwampDragons** [comment]
@azr can you take a peek at this for me?

**Comment by SwampDragons** [comment]
You can try pulling down a dev build of the linked patch from our ci server at https://app.circleci.com/pipelines/github/hashicorp/packer/8817/workflows/5410b8ad-bb62-440a-9890-5dac97e46fd5/jobs/104184/artifacts and see if that solves your issue.

**Comment by kelvSYC** [comment]
The dev build does not appear to address the issue; perhaps the diff covered only `uint8` instead of `[]uint8`, as originally reported.
