### ISSUE TITLE
Whether integration with K8S is supported

### ISSUE THREAD

**Issue by zhaocheng173** [hashicorp/packer#10524]
Whether integration with K8S is supported

**Comment by azr** [comment]
Hey @zhaocheng173, Packer does not currently have a Kubernetes support, Packer is an image (ami, docker, etc.) builder.

Packer has a docker image though which runs on k8s.

Do you have a specific use case in mind ?

**Comment by SwampDragons** [comment]
Closing since I'm not sure this is actionable and we never heard back.
