### ISSUE TITLE
GCP: packer 1.6.6 is not able to get service account 

### ISSUE THREAD

**Issue by loibpet** [hashicorp/packer#10538]
#### Overview of the Issue

After upgrading from packer 1.6.5 to packer 1.6.6, packer builds fail  with the error message:

`Your client does not have permission to get URL /computeMetadata/v1/instance/service-accounts/default/email from this server.  That's all we know.`

After downgrading back to packer 1.6.5, packer runs smoothly again.

#### Reproduction Steps

run packer on GCP

### Packer version

1.6.6

### Log Fragments and crash.log files

```
2021/01/29 10:34:41 [INFO] Packer version: 1.6.6 [go1.15.6 linux amd64]
...
2021/01/29 10:34:41 Running builder:
2021/01/29 10:34:41 [INFO] (telemetry) Starting builder
2021/01/29 10:34:41 packer.1.6.6 plugin: [INFO] Requesting Google token via GCE API Default Client Token Source...
2021/01/29 10:34:41 packer.1.6.6 plugin: [INFO] Instantiating GCE client...
2021/01/29 10:34:41 packer.1.6.6 plugin: [INFO] On GCE, capture service account for OSLogin...
2021/01/29 10:34:41 [INFO] (telemetry) ending
...
  <p><b>403.</b> <ins>That’s an error.</ins>
  <p>Your client does not have permission to get URL <code>/computeMetadata/v1/instance/service-accounts/default/email</code> from this server.  <ins>That’s all we know.</ins>
`

==> Builds finished but no artifacts were created.
2021/01/29 10:34:42 waiting for all plugin processes to complete...
2021/01/29 10:34:42 /opt/hashicorp/bin/packer.1.6.6: plugin process exited
2021/01/29 10:34:42 /opt/hashicorp/bin/packer.1.6.6: plugin process exited
2021/01/29 10:34:42 /opt/hashicorp/bin/packer.1.6.6: plugin process exited

Running packer as: packer build -var-file=variables/GCP/europe-west3/clearing-dev.pkr.hcl image-templates/GCP/51WAzqxaU9WJfbQp.dev.rhel7-test.pkr.hcl | tee /tmp/bake-51WAzqxaU9WJfbQp.out


No created image found
```

**Comment by nywilken** [comment]
Hello there @loibpet thanks for reaching out. I believe this issue has been fixed in #10458, which is set to be released in the next version of Packer. 

Can you please pull down the latest nightly release of Packer [here](https://github.com/hashicorp/packer/releases/tag/nightly) and let us know if you are still running into issues. 

Thanks, 
Wilken

**Comment by loibpet** [comment]
```
packer version
Packer v1.7.0-dev
```

`packer build` works now :smiley:

**Comment by nywilken** [comment]
Great, thanks for testing. I'm going to close this issue as it has been resolved and is available within our nightly releases for use. Cheers!
