### ISSUE TITLE
PostProcessor does not respect PackerConfig.PackerForce

### ISSUE THREAD

**Issue by tduffield** [hashicorp/packer#10536]
#### Overview of the Issue

I am working on adding a post-processor to a custom plugin that works with Veertu Anka. The custom plugin contains a builder (to build the VM) and a post-processor (to upload the VM to a registry) The issue I'm running into is that while the builder config seems to respect the `-force` flag, the post-processor does not.  

#### Reproduction Steps

1. Install Anka Develop
2. Install packer 1.7 nightly
3. Build/install the `089a00b87a5f23cf271c098e6bbe73d555aa9a9e ` commit of the [packer-builder-veertu-anka](https://github.com/chef/packer-builder-veertu-anka/commit/089a00b87a5f23cf271c098e6bbe73d555aa9a9e) plugin.
4. Execute build with `PACKER_LOG=1`

### Packer version

1.7.0-dev [go1.15.7 darwin amd64]

### Simplified Packer Buildfile

```
source "veertu-anka-vm" "core-10_15" {
  vm_name = "10.15-core"
  installer_app = "/Applications/Install macOS Catalina.app"
}

build {
  name = "core"

  sources = [
    "source.veertu-anka-vm.core-10_15",
  ]

  post-processor "veertu-anka-registry" {
    tag = "latest"
  }
}
```

### Operating system and Environment details

Running on MacOS 10.5.7. 

### Log Fragments and crash.log files

[Full Gist Output](https://gist.github.com/tduffield/8cf08e7153e8fb9c095e86708d896384)

You'll notice that I output the `Config` value twice: [once for the builder](https://gist.github.com/tduffield/8cf08e7153e8fb9c095e86708d896384#file-gistfile1-txt-L757-L758) and [again for the post-processor](https://gist.github.com/tduffield/8cf08e7153e8fb9c095e86708d896384#file-gistfile1-txt-L967-L968).

**Comment by nywilken** [comment]
Hi there @tduffield thanks for reaching out. We're excited to hear about the custom builder you are working on. We just updated issue #8610 pertaining to an improve plugin experience we are working on for v1.7.0 that will be helpful to you https://github.com/hashicorp/packer/issues/8610#issuecomment-770034737

Regarding your original issue around the force flag not being honored by your Post-Processor. I need to dive a little deeper to see if we have support for the force flag in HCL2 for provisioners and post-processors. As a quick glance it seems like we might be missing it. 

If you run your build using a JSON configuration does the post-processor honor the force flag?

**Comment by tduffield** [comment]
@nywilken Thanks for the reference to that issue; I'll have to check it out. 

I was able to confirm that the post-processor does support the PackerForce flag when used with JSON configuration.
