### ISSUE TITLE
ssh provisioning not working when using the profitbricks builder

### ISSUE THREAD

**Issue by mflorin** [hashicorp/packer#10548]
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

When trying to create an image using the profitbricks builder, provisioning fails due to ssh errors, even with the correct private key file path provided in the json spec.

#### Reproduction Steps

Run packer with the profitbricks builder and the "file" provisioner.

### Packer version

From `1.6.6`

### Simplified Packer Buildfile

```
{
  "builders": [
    {
      "url": "https://api.ionos.com/cloudapi/v5",
      "image": "ubuntu-20.04",
      "type": "profitbricks",
      "disk_size": "5",
      "snapshot_name": "test",
      "location": "de/fra",
      "ssh_username": "root",
      "ssh_password": "password",
      "communicator": "ssh",
      "ssh_private_key_file": "/Users/myuser/.ssh/id_rsa"
    }
  ],
  "provisioners": [
    {
      "type": "file",
      "source": "./welcome.txt",
      "destination": "/root/welcome.txt"
    }
  ]
}
```

### Operating system and Environment details

Tested on OSX and Linux

### Log Fragments and crash.log files

Logs can be found in this [gist](https://gist.github.com/mflorin/c60226cad3f6383d66f57613f3940d7a) .
The relevant message is 
```
[DEBUG] Detected authentication error. Increasing handshake attempts.
==> profitbricks: Error waiting for SSH: Packer experienced an authentication error when trying to connect via SSH. This can happen if your username/password are wrong. You may want to double-check your credentials as part of your debugging process. original error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```

**Comment by SwampDragons** [comment]
Can you manually ssh into the instance using those credentials, during the time Packer is trying to connect?
