### ISSUE TITLE
Amazon-ebs builder instance with specific tags.

### ISSUE THREAD

**Issue by serhiiromaniuk** [hashicorp/packer#10550]
#### Description

Support for **amazon-ebs** builder extended tagging.

#### Use Case

- Track organisation tags, not Packer default "Packer Builder"

#### Potential configuration

```
"instance_tags": {
            "Name": "AMI Builder {{timestamp}}-{{env `ENVIRONMENT`}}"
}
```

Thanks!

**Comment by nywilken** [comment]
Hi @serhiiromaniuk we completely understand the need to extend tagging. The Amazon builder supports tagging for the created instance via `run_tags`, tagging for the AMI via `tags`, and finally tagging for the created snapshots via `snapshot_tags`. 

Have you tried adding the `run_tags` option to your build template? 

More information on the option can be found [here](https://www.packer.io/docs/builders/amazon/ebs#run_tags)

I believe that the current functionality of the Amazon builder handles this use case so I am going to close this issue. But if I am mistaken and your request is different from the existing functionality please lets us know and I will reopen the issue. Cheers!
