### ISSUE TITLE
Is there a way to stop AMI creation on amazon-ebs builder?

### ISSUE THREAD

**Issue by serhiiromaniuk** [hashicorp/packer#10551]
##
##### Purpose:
I want to prevent creation of AMI and let instance with default setting stack to stop, after **provisioners** step. Without any error if **provisioners** finished successfully.

##### Specifications:
Builder: amazon-ebs
Packer: v1.6.6
Workaround: add some conditional scripts and manipulations to track boolean state, before `shutdown -h now`.
##

**Comment by nywilken** [comment]
Hi @serhiiromaniuk there is a new feature set to release in v1.7.0 that might be what you are looking for https://github.com/hashicorp/packer/pull/10531. 

There are  binaries available for testing at https://app.circleci.com/pipelines/github/hashicorp/packer/8876/workflows/94c1312f-8b8a-45a8-ad75-dbdd812efe08/jobs/104995/artifacts

If the `skip_ami_create` option works for your use case, the feature will be available in the next [nightly release](https://github.com/hashicorp/packer/releases) as well.

**Comment by SwampDragons** [comment]
Closing since this will be in the next release.
