### ISSUE TITLE
Vsphere-iso Linux VM is not getting any dhcp replies from Packer

### ISSUE THREAD

**Issue by pentiumoverdrive** [hashicorp/packer#10552]
#### Overview of the Issue

Vsphere iso is not getting any dhcp replies from Packer.

#### Reproduction Steps

Just run packer.

 /usr/local/bin/packer build -var-file=rhel8_vars.json -var-file=secrets.json rhel8_vsphere.jso

### Packer version

Packer v1.6.6 (happens with earlier versions as well).

### Operating system and Environment details

CentOS Linux release 7.9.2009 (Core) running in vmware.

### Detailed description.

I'm unable to get any IP back from Packers DHCP using vsphere-iso.
I tried disabling selinux and firewall, no difference.

This has been working before, but I cannot figure out what the problem is now.

The VM kickstart on rhel 8 (or any other distro) fails with:
"Warning dhcp for interface ens224 failed".

On the server running Packer I can see incoming dhcp requests from the VM I'm trying to build:

10:29:35.050121 00:50:56:9e:82:2e > ff:ff:ff:ff:ff:ff, ethertype IPv4 (0x0800), length 353: (tos 0x10, ttl 128, id 0, offset 0, flags [none], proto UDP (17), length 339)
    0.0.0.0.68 > 255.255.255.255.67: [udp sum ok] BOOTP/DHCP, Request from 00:50:56:9e:82:2e, length 311, xid 0xdd797d4d, secs 50, Flags [none] (0x0000)
          Client-Ethernet-Address 00:50:56:9e:82:2e
          Vendor-rfc1048 Extensions
            Magic Cookie 0x63825363
            DHCP-Message Option 53, length 1: Discover
            Parameter-Request Option 55, length 11:
              Subnet-Mask, BR, Time-Zone, Default-Gateway
              Domain-Name, Domain-Name-Server, Option 119, Hostname
              RP, MTU, Classless-Static-Route
            Vendor-Class Option 60, length 43: "anaconda-Linux 4.18.0-193.el8.x86_64 x86_64"
            Client-ID Option 61, length 7: ether 00:50:56:9e:82:2e

Packer just sits here waiting:

==> vsphere-iso: Creating VM...
==> vsphere-iso: Customizing hardware...
==> vsphere-iso: Mounting ISO images...
==> vsphere-iso: Adding configuration parameters...
==> vsphere-iso: Starting HTTP server on port 8298
==> vsphere-iso: Set boot order temporary...
==> vsphere-iso: Power on VM...
==> vsphere-iso: Waiting 18s for boot...
==> vsphere-iso: HTTP server is working at http://ip:8298/
==> vsphere-iso: Typing boot command...
==> vsphere-iso: Waiting for IP...

On the VM I can set a static IP using dracut shell and ping the packer machine without any problems.

I tried running packer as root too, no difference.
Why is packer not handing out a dhcp lease?

**Comment by jhawk28** [comment]
I don't think that packer provides a dhcp server.

**Comment by pentiumoverdrive** [comment]
> I don't think that packer provides a dhcp server.

Hmm! Thats amazing. Guess I have relied on rogue dhcp servers earlier and with them gone stuff stopped working.
I haven't been able to figure out just by reading the documentation how this works. Maybe packer gets the VM IP in this early stage why checking who is fetching the kickstart file from its embedded web server?

**Comment by jhawk28** [comment]
Packer looks up the IP address of the local machine for the http server. It uses the vmware tools to retrieve the IP from the VM and uses that to connect over ssh for the provisioners.
