### ISSUE TITLE
file function failed when it called twice

### ISSUE THREAD

**Issue by katsew** [hashicorp/packer#10565]
#### Overview of the Issue

I want to get the commit hash from `.git`, so I use [file function](https://www.packer.io/docs/from-1.5/functions/file/file) to get `.git/HEAD`,
then I call it again with the path inside `.git/HEAD`.
It seems that the path is accessible by packer (`/path/to/refs/heads/master`), but it failed with an error
`Call to function "file" failed: no file exists at /path/to/refs/heads/master`.
I double checked the path by running `ls /path/to/refs/heads/master` and it seems ok.

#### Reproduction Steps

1. echo "ref: foo/bar" > TEST
2. mkdir foo && touch foo/bar
3. create [main.pkr.hcl](https://gist.github.com/katsew/87ce312b410a3017e9960afaefdf0c8f)
4. run `packer build .`

### Packer version

Packer v1.6.6

### Simplified Packer Buildfile

[main.pkr.hcl](https://gist.github.com/katsew/87ce312b410a3017e9960afaefdf0c8f)

### Operating system and Environment details

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

### Log Fragments and crash.log files

[error.log](https://gist.github.com/katsew/87ce312b410a3017e9960afaefdf0c8f)

**Comment by sylviamoss** [comment]
There's an extra empty space in the TEXT content. Trimming the empty spaces from the content solves the issue. 

This will work: 
```
locals {
  txt = file("${path.cwd}/${split(" ", trim(file("${path.cwd}/TEXT"), " "))[1]}")
}

source "null" "first-example" {
  communicator = "none"
}

build {
  name = "roles"

  sources = ["null.first-example"]

  provisioner "shell-local" {
    inline = ["echo ${local.txt}"]
  }
}
```

I'll close the issue. Let me know if there's anything else happening in your config.

**Comment by katsew** [comment]
@sylviamoss 

Thanks for the response.
The example you posted not work in my situation,
but after applying tiny fix to your example, it works as I expected.

```
# trimspace removes any space characters from the start and end of the given string.
locals {
  tr = trimspace(file("${path.cwd}/TEXT"))
  sp = split(" ", local.tr)[1]
  tx = trimspace(file("${path.cwd}/${local.sp}"))
}

source "null" "first-example" {
  communicator = "none"
}

build {
  name = "roles"

  sources = ["null.first-example"]
  provisioner "shell-local" {
    inline = ["echo ${local.tx}"]
  }

}
```

Thanks for the help!

**Comment by sylviamoss** [comment]
Nice, `trimspace` is much better! No problem, happy to help 😄
