### ISSUE TITLE
Dependencies on removed commits

### ISSUE THREAD

**Issue by carlpett** [hashicorp/packer#10585]
#### Overview of the Issue

The bump to packer-plugin-sdk 0.11 (#10572) introduces a dependency on packer `v1.6.7-0.20210126105722-aef4ced967ec`, but the commit `aef4ced967ec` doesn't belong to any branch (https://github.com/hashicorp/packer/commit/aef4ced967ec).

This causes builds to fail if building on a system which does not use a module caching proxy that had time to cache the version before it was removed, or disabling it completely. This is for example the case on Fedora Linux, which by default sets `GOPROXY=direct`.

Even setting aside build time issues, it seems unfortunate to set up dependencies on commits which are then orphaned?

#### Reproduction Steps

`GOPROXY=direct go build`

### Operating system and Environment details

Stock Fedora Linux, or other environments setting `GOPROXY=direct` or pointing to internal company proxies.

**Comment by azr** [comment]
Hey @carlpett ! Sorry about that one; good catch, a colleague had the same issue and I thought that it was simply a miss-configuration of the GOPROXY setting. I'm fixing that one asap.
