### ISSUE TITLE
Constant variable type 

### ISSUE THREAD

**Issue by timblaktu** [hashicorp/packer#10598]
Sometimes a constant value needs to be made into a variable, only so it can be referenced from both builder and provisioner or post-processor. I would like to be able to define such variables as "constant" and have packer error if the value ever gets changed from its initial value as set in a variables block. E.g.

```
variables {
  .
  variable "guest_additions_iso_path" {
    type    = string
    constant = true
    default = "/tmp/VBoxGuestAdditions.iso"
    description = "This path is needed in provisioner step, and should not be changed."
  }
  .
}
source "virtualbox-iso" "debian10" {
  .
  guest_additions_path    = var.guest_additions_iso_path  # this constant variable is needed in provisioner step
  .
}
build {
  source "source.virtualbox-iso.debian10" {
  ...
  }
  provisioner "shell" {
    .
    inline = [ 
      .
      "mount -t iso9660 -o loop ${var.guest_additions_iso_path} /tmp/isomount"
      .
    ]
```

**Comment by SwampDragons** [comment]
To make sure I understand here, the idea would be that you cannot set this from the command line or environment, yeah?

**Comment by timblaktu** [comment]
That's right. Over in #10583 I've learned that variables and locals can't be set inside build source blocks, they can only be used there. So, for entities like in my example above (guest_additions_path) which are needed at the builder level and the provisioner level, they need to be defined in _some_ kind of variable to be accessible in both places. Yet it's basically a project constant, and it'd be nice to enforce that it doesn't get accidentally changed.

**Comment by SwampDragons** [comment]
Ok, cool. I agree this is an interesting idea. I'm not sure off the top of my head how difficult this would be technically, but we can investigate it.

**Comment by azr** [comment]
@timblaktu, why not making it a local, ex:

```
locals {
  guest_additions_iso_path = "/tmp/VBoxGuestAdditions.iso"
}
```

This way there's no way to set this to anything else.

**Comment by timblaktu** [comment]
That achieves my goal, for the most part @azr . (Assuming it's obvious to users that locals are constant.) If I use a local instead of a var, presumably the packer build (or validate) would fail if I tried to change it somewhere.

Incidentally, why are locals called locals? Seems like they can be defined in several places, so the name local doesn't make any sense. Shouldn't they be called constants?

**Comment by azr** [comment]
So, these are Packer variables, **input variables** will be treated as input variables from the point of view of a Packer build for example, they can have a default and you _can_ also set them from env or from cli arguments; meaning that if you never set the cli or env arguments nothing can change those. But so they could be seen as settable by someone using your templates.

**Local variables** are opposed to input variables in the sense that they can only be a compound of functions, input variables and other local variables. But so if you never use an input variable in a local variable there is no way an operator can change these.

Looking at the current execution model of Packer here's the order in which HCL is evaluated:

* input vars ( can be changed by cli and env )
* local vars ( compound of functions, input vars and other locals, but cannot change anything input vars )
* datasources ( can use locals and input vars, but not change anything)
* builds... ( can use all of the above, but not change anything )

Once something has been evaluated nothing can change it

**Comment by SwampDragons** [comment]
I wonder if this is a docs question -- maybe we can call out in the local vars documentation that these can be used for "constant" values that you don't want operators to be able to change from the environment or cli

**Comment by azr** [comment]
Yeah I agree, these are like 'template variables' and not variables you can tweak around during runtime.
