### ISSUE TITLE
googlecompute builder ignores precedence of authentication methods when running in GCE

### ISSUE THREAD

**Issue by rbjorklin** [hashicorp/packer#10607]
#### Overview of the Issue

googlecompute builder ignores [precedence of authentication methods](https://www.packer.io/docs/builders/googlecompute#precedence-of-authentication-methods) when running in GCE. **The issue can be worked around by commenting [this line](https://github.com/hashicorp/packer/blob/fd8e76636a532d1f6eda68d1a2f718491ffbf2d4/builder/googlecompute/step_import_os_login_ssh_key.go#L44).**

#### Reproduction Steps

* Run a packer build with the ansible provisioner using `use_os_login` from your local workstation using `account_file`
* Try running the same build from within GCE itself and watch the build either fail or use other credentials than specified

### Packer version
Packer v1.7.0-dev

### Simplified Packer Buildfile

```hcl
source "googlecompute" "build-dev-agent" {
  service_account_email   = "<something>"
  image_name              = "jenkins-build-agent-${formatdate("YYYY-MM-DD't'hh-mm-ss", timestamp())}"
  image_family            = "jenkins-build-agent"
  use_os_login            = true
  project_id              = "<something>"
  source_image_family     = "centos-7"
  ssh_username            = "packer"
  zone                    = "<something>"
  network_project_id      = "<something>"
  subnetwork              = "<something>"
  omit_external_ip        = true
  use_internal_ip         = true
  account_file            = "sa_key.json"
}

build {
  sources = [
    "sources.googlecompute.build-dev-agent",
  ]

  provisioner "ansible" {
    host_alias      = "localhost"
    playbook_file   = "./playbook.yml"
  }
}
```

### Operating system and Environment details

Centos 7, x86_64

### Log Fragments and crash.log files

```
packer-builder-googlecompute plugin: [INFO] Requesting Google token via account_file...
packer-builder-googlecompute plugin: [INFO]   -- Email: intended-account@intended-project.iam.gserviceaccount.com
...
packer-builder-googlecompute plugin: [INFO] OSLogin: GCE service account wrong-account@wrong-project.iam.gserviceaccount.com will be used for identity
==> googlecompute.build-dev-agent: Importing SSH public key for OSLogin...
==> googlecompute.build-dev-agent: Error importing SSH public key for OSLogin: googleapi: Error 403: End user credentials must match the user specified in the request., forbidden
```

**Comment by leson** [comment]
met the same issue with @rbjorklin  , hope have a solution ASAP.
