### ISSUE TITLE
Implement cd_files option for proxmox builder

### ISSUE THREAD

**Issue by clayshek** [hashicorp/packer#10613]
#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

Would be super helpful for the Packer Proxmox builder to be able to provide functionality to include files in an additional CD drive attached to a VM during image build, or to better understand if this isn't possible for some reason. This would be similar to the same cd_files functionality recently merged for qemu, hyperv, and vmware builders in https://github.com/hashicorp/packer/pull/9928. 

#### Use Case(s)

Primary use case would be to provide a method for unattended OS installations where additional files need to be provided, and where using the network is not an option. Examples are for Ubuntu 20.04 autoinstall where cloud-init files are needed, or even Microsoft Windows for providing the AutoUnattend.xml. 

An example reason for not being able to provide the config file(s) over the network is this Packer bug: github.com/hashicorp/packer/issues/9973.

**Comment by paginabianca** [comment]
Hi, you should take a look at the `addtitional_iso_file` option for the Proxmox builder. This option essentially does the same thing as `cd_files` for the other builders but you will have to create the ISO/CD_FILE yourself.

**Comment by clayshek** [comment]
Yep, I'm aware of it, and the `addtitional_iso_file` option is an option, but not as ideal as having `cd_files` because as you mentioned, you need to create the iso yourself, either manually prior to Packer run, or as part of Packer run, which introduces additional, likely OS-specific, dependencies in terms of what utility is used to build the ISO.
