### ISSUE TITLE
[VMware] Parallel threads for OVF Tool if available (requires OVF Tool version >= 4.4)

### ISSUE THREAD

**Issue by Dr-Shadow** [hashicorp/packer#10629]
#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

Support parallelThreads when available for OVF Tool.

#### Use Case(s)

Speed-up import/export from ESXi hosts which is most of the time bottlenecked by the CPU.

#### Quote

> OVF Tool now can upload disk files to the host in parallel, and download disk files from the host in parallel. OVA is unsupported. Parallelism is limited by the number of CPUs. See the --parallelThreads=N option in the OVF Tool User's Guide for details.

#### Potential References

https://vdc-download.vmware.com/vmwb-repository/dcr-public/8e710909-c904-41ec-95bf-fb7047621d0a/9fae5a3d-cfe7-474a-9341-3cc804379dd1/ovf-440-releasenotes.html

**Comment by SwampDragons** [comment]
Hi, thanks for opening. 

I think this sounds nice and I would definitely accept and review a PR implementing it; I'm not sure that the Packer team will have time in the short term to implement it ourselves though. The export function can be found here: https://github.com/hashicorp/packer/blob/master/builder/vmware/common/driver.go#L643

**Comment by azr** [comment]
@Dr-Shadow, do you no longer require this feature ?
