### ISSUE TITLE
Support vSphere datastore clusters 

### ISSUE THREAD

**Issue by MG2R** [hashicorp/packer#10620]
#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

I'm trying to build VM templates in a vSphere cluster. Our disks are housed in a datastore cluster. I'd like to instruct packer to target that cluster for the disk storage. However, when I enter the address of the cluster in the [datastore](https://www.packer.io/docs/builders/vmware/vsphere-iso#datastore) parameter for packer, packer throws the following error:

```
Build 'vsphere-iso' errored after 107 milliseconds 63 microseconds: datastore doesn't exist: Error finding datastore with name /MYDC/datastore/MYDSC: datastore '/MYDC/datastore/MYDSC' not found
```

It seems I need to point towards specific datastores: using `/MYDC/datastore/MYDSC/datastore_1` works perfectly fine.

Is this indeed unsupported? Am I missing something?

**Comment by SwampDragons** [comment]
It does seem to be unsupported; I'm not sure when the Packer team will get a chance to work on this, but PRs are welcome. 

The code in the VSphere driver that searches for datastores can be found here: https://github.com/hashicorp/packer/blob/master/builder/vsphere/driver/datastore.go#L41

**Comment by MG2R** [comment]
Oh hey, thanks for pointing me in the right direction. If I find the time I’ll try and take a look. Never done Go before, though. Not sure if I’ll be able to figure it out.

**Comment by MG2R** [comment]
Ok, it looks like the magic is in [this line](https://github.com/hashicorp/packer/blob/master/builder/vsphere/driver/datastore.go#L65), which will use the [finder.Datastore from the VMware go client](https://github.com/vmware/govmomi/blob/master/find/finder.go#L448). I think I should be able to extend the function so it tries to use [finder.DatastoreCluster](https://github.com/vmware/govmomi/blob/master/find/finder.go#L509) if it can’t find a matching datastore.

However, that would mean the datastore pram for packer would accept both Datastore and DatastoreCluster names. Is that acceptable for you guys?

**Comment by SwampDragons** [comment]
Yeah I think it should be acceptable for that parameter to accept either, though for hosts and clusters we have two different parameters. How about you try it with the same param and if it looks like it'll cause issues to share the option we can add a second template option.

**Comment by vheon** [comment]
I opened a similar issue https://github.com/hashicorp/packer/issues/10004 some time ago but could not find the time to try and implement this myself 😢

**Comment by MG2R** [comment]
I wanted to start working on this as a Fun Friday project, however it seems simply following the CONTRIBUTING.md instructions and building master doesn't work for me:

```
packer -> master $ make
go: github.com/hashicorp/packer-plugin-sdk@v0.0.14 requires
	github.com/hashicorp/packer@v1.6.7-0.20210217093213-201869d627bf requires
	github.com/hashicorp/packer-plugin-sdk@v0.0.12 requires
	github.com/hashicorp/packer@v1.6.7-0.20210208125835-f616955ebcb6 requires
	github.com/hashicorp/packer-plugin-sdk@v0.0.11 requires
	github.com/hashicorp/packer@v1.6.7-0.20210126105722-aef4ced967ec: invalid version: unknown revision aef4ced967ec
make: *** [install-build-deps] Error 1
```
On my personal laptop, I seem to not have this problem, so I was suspecting network config and proxy settings, but my http_proxy is set correctly for both go (through env args) and git (through `git config --global`). Any pointers on how to move past this on my work machine?

**Comment by MG2R** [comment]
I've been working on this for a couple hours now and, unfortunately, must concede that I'm not well-versed enough in go/vmomi/vsphere to get any useful results on this. I delved into older issues on both govmomi and terraform's vsphere provider support for datastore clusters, but it's for too complicated from my current knowledge level.

So far, it seems I need to somehow get a Datastore name out of a StoragePod, which requires whole host of decisionmaking surroung "podspecs" and "vm config specs".

I'm hopeful someone else is able to take a look into this, but for now I'll have to stick to specifying a single datastore for my VM templates.
