### ISSUE TITLE
"only" doesn't work as what the documentation says

### ISSUE THREAD

**Issue by ryuheechul** [hashicorp/packer#10621]
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

in the example here, https://www.packer.io/docs/from-1.5/onlyexcept

```
build {
  name = "my_build"
  sources [
    "source.amazon-ebs.first-example",
  ]
  source "source.amazon-ebs.second-example" {
    // setting the name field allows to rename the source only for this build
    // section.
    name = "second-example-local-name"
  }

  provisioner "shell-local" {
    only = ["source.amazon-ebs.first-example"] # <- especially this line 
    inline = ["echo I will only run for the second example source"]
  }

  provisioner "shell-local" {
    except = ["source.amazon-ebs.second-example-local-name"]
    inline = ["echo I will never run for the second example source"]
  }
}
```

It implies that I need to add `source.` however it doesn't work with it and it works when I do `only = ["amazon-ebs.first-example"]` without `source.`.

Also in `source` stanza under `build`, it seems weird that it works with both with `source.` and without.

And some examples even shows two different examples in one documentation page, like this one, https://www.packer.io/docs/from-1.5/blocks/source.

`source "source.amazon-ebs.example"` vs `source "null.first-example"`
Why not either below?
- `source "source.amazon-ebs.example"` and `source "source.null.first-example"`
- `source "amazon-ebs.example"` and `source "null.first-example"`

#### Reproduction Steps

Hope my description above give you an idea of how to reproduce it.

### Packer version

1.6.6

### Simplified Packer Buildfile

~I used the example from documentation like I mentioned above~ -> maybe this will help, https://gist.github.com/ryuheechul/523d5172c0b0793c96e37684bda233c6

### Operating system and Environment details

macOS 11.2

### Log Fragments and crash.log files

N/A

**Comment by sylviamoss** [comment]
Hello there, thanks for reporting. 
The `only` documentation was incorrect but was fixed here https://github.com/hashicorp/packer/pull/10571 and will be released in v1.7.0. 

About the `source` prefix in the source reference, you're right that is confusing having both without a clear explanation about the two possibilities. I think we can either explicitly document the two possibilities or pick one to go for. Which one would prefer to see in the documentation in this case?

**Comment by ryuheechul** [comment]
@sylviamoss Hey, thanks for your prompt reply!

_Take my opinion with knowing that I'm very new to packer actually!_

In short, I generally prefer without `source.` as this makes it more logical sense and simpler.

A longer thought on this is...

I prefer without `source.` for `source` stanza for sure as it avoid situation like below

```hcl
source "source.[source-type].[name]"
```

but for `provisioner` not so sure what else `only` is supporting. If it's just source I prefer without `source.` again. But if there is another possibility, then it should make sense to have `source.` prefix to distinguish clearly with others.

Either way I think it should be clear on the documentation to avoid the confusion.

Let me know what you think.

**Comment by SwampDragons** [comment]
I think we can close this since the updated documentation has been released: https://www.packer.io/docs/templates/hcl_templates/onlyexcept

> They can also be seen in a template to run or skip provisioners and/or post-processors for a specific source

So I think that makes it pretty clear it's specific to sources.
