### ISSUE TITLE
Add disable_shutdown option to Hyper-V builder

### ISSUE THREAD

**Issue by net147** [hashicorp/packer#10630]
It would be useful to add the disable_shutdown option to the Hyper-V builder, similar to the VirtualBox and VMware builders. For Debian images, the VM can be shutdown from the preseed without requiring SSH.

**Comment by SwampDragons** [comment]
This makes sense to me; It'll be a while until the Packer team has time to implement this but if a community member wants to take a look at doing it, we can prioritize reviewing your PR. 

The shutdown step for hyperv is here: https://github.com/hashicorp/packer/blob/master/builder/hyperv/common/step_shutdown.go

You'd want to add a disable_shutdown option like virtualbox does (see the config [here](https://github.com/hashicorp/packer/blob/master/builder/virtualbox/common/shutdown_config.go) and implementation [here](https://github.com/hashicorp/packer/blob/master/builder/virtualbox/common/step_shutdown.go#L47)], and add that option to the hyperv iso and clone builder config structs.
