### ISSUE TITLE
Documentation: confusion around http_ip vs http_bind_address

### ISSUE THREAD

**Issue by karma0** [hashicorp/packer#10636]
#### Documentation needs clarification

The differences between [http_ip](https://www.packer.io/docs/builders/vmware/vsphere-iso#http_ip) and [http_bind_address](https://www.packer.io/docs/builders/vmware/vsphere-iso#http_bind_address) in the documentation aren't clear, and some clarification is needed around the default binding address of `0.0.0.0` when packer actually _only_ binds to all IPv6 addresses by default.

#### Reproduction Steps

I am running Arch Linux and have disabled IPV6 to the best of my ability, but was running into an issue wherein packer was binding the preseed http server to all IPv6 addresses on a random port and _no_ IPv4 addresses.  With this, `HTTPIP` was resolving to the host's IPv4 external interface and it was causing a failure to connect.

When I searched for similar issues, [issue 6689](https://github.com/hashicorp/packer/issues/6689) matched my problem almost exactly. 

To resolve this, initially, I was trying to set the bind address using `http_ip` as described in the documentation, but somehow overlooked `http_bind_address`.

This part appears to be a bug: I used the bind address `0.0.0.0` (which appears to be the default) and packer would still bind to all IPv6 addresses, like so:

```
tcp6       0      0 :::8783                 :::*                    LISTEN      42229/packer 
```

The only workaround was to manually specify the exact IP address for the exact IP that `HTTPIP` resolves to in the `http_bind_address` vsphere-iso packer configuration.

### Packer version

This same thing happened while using `vsphere-iso` on packer versions 1.6.3, 1.6.5, and 1.7.0.

### Operating system and Environment details

- Laptop running Arch Linux
- IPv6 disabled using NetworkManager and sysctl
- VSphere 7 cluster

**Comment by karma0** [comment]
Please note that I filed this as an issue with the documentation despite there appearing to be some kind of issue with how packer (or vsphere-iso?) resolves "all IP addresses".  The reason is because the documentation doesn't make it clear how this is intended to work.  Should "0.0.0.0" bind to all IPv4 addresses or IPv6 addresses or both?

**Comment by karma0** [comment]
It would seem the only way to get it to bind to an IPv4 is by explicitly setting the IPv4 address, which is less than ideal.  Let me know if you would like me to open a bug for the way that this binds; I'll just need info on how it is intended to work.

**Comment by SwampDragons** [comment]
This is a passthrough to the golang net library's Listen func; looking there, 0.0.0.0 should only be ipv4. An explanation of the address string can be found here: https://golang.org/pkg/net/#Dial.  The only thing I see that is relevant is:

> For TCP, UDP and IP networks, if the host is empty or a literal unspecified IP address, as in ":80", "0.0.0.0:80" or "[::]:80" for TCP and UDP, "", "0.0.0.0" or "::" for IP, the local system is assumed.
