### ISSUE TITLE
hcl2upgrade: pause_before option of provisioners not migrated

### ISSUE THREAD

**Issue by jpbuecken** [hashicorp/packer#10647]
#### Overview of the Issue

Looking at https://www.packer.io/docs/templates/provisioners, provisioners support a generic option "pause_before".

This option is not migrated to hcl after a hcl2upgrade

#### Reproduction Steps

Before:
```
      {
         "type": "shell-local",
         "command": "echo waited 60 sec",
         "pause_before": "60s"
      },
```
The result after packer hcl2_upgrade test.json
```
  provisioner "shell-local" {
    command = "echo waited 60 sec"
  }
```
### Packer version

Packer v1.6.6 (Windows)

**Comment by SwampDragons** [comment]
Thanks for reporting -- we'll take a look at this for the next release.
