### ISSUE TITLE
Feature Request for File & Shell Provisioners: Persist File Mode

### ISSUE THREAD

**Issue by zettabyte** [hashicorp/packer#1064]
The documentation for the shell provisioner makes no explicit mention of the fact that the execution bits on your script's file mode won't survive the `scp` to the VM. You _can_ infer it from the documented, default value of the `execute_command` setting (which is prefixed with  `chmod +x {{.Path}} ; ...`). However, this doesn't document this behavior in a sufficiently obvious location.

Additionally, the file provisioner doesn't document and doesn't even provide a way to infer this same behavior. So, new users (like me) may have to learn from a failed "first pass" that any scripts uploaded via either provisioner will need an explicit `chmod +x` performed against them, even if the source files' modes locally are already executable.

So, I'd request that either:
1. The docs for the shell and file provisioners be updated to explicitly state that the file or shell script, respectively, will _not_ have any execute bits after being transferred to the VM. Or...
2. The behavior (and docs) updated to persist the file mode (at least w/respect to the executable bits) of files or shell scripts `scp`-ed by either of these provisioners.

**Comment by hmehendale** [comment]
I'm running into what seems like this issue with 0.10.1 (on MacOSX, running Linux VM/Docker containers). Scripts uploaded to virtualbox (running CentOS 6.6) get 0644, and those uploaded to Docker (native on Mac) get 0600.

Packer JSON
    {
      "provisioners": [{
          "source": "test.sh", "destination": "/var/tmp/test.sh", "type": "file"
        }
      ], "builders": [{
          "commit": true, "image": "centos:6.6", "type": "docker"
        }
      ]
    }

The local test.sh is marked executable. After a `packer build test.json`, if I check permissions inside the container:
    docker run 62c4ab1 ls -l /var/tmp/test.sh
    -rw-------  1 root root   30 Aug 31 22:30 test.sh

**Comment by mwhooker** [comment]
@hmehendale opened a PR to fix this https://github.com/mitchellh/packer/pull/4443

in the future, best to open a new issue so we don't miss it
