### ISSUE TITLE
Packer 1.6.6 HCL vSphere WinRM Time out Windows 10

### ISSUE THREAD

**Issue by mrdanielmartins** [hashicorp/packer#10650]
Hi Gang,

I have been using Packer1.5.5 with JSON and all works splendidly to build my Windows Server and Windows Workstation boxes. Monday, I decided I wanted to treat myself with version 1.6.6 HCL.

I am faced with this error repeatedly and have no way out:

`2021/02/17 13:13:36 packer-builder-vsphere-iso plugin: [INFO] Attempting WinRM connection...
2021/02/17 13:13:36 packer-builder-vsphere-iso plugin: [DEBUG] connecting to remote shell using WinRM
2021/02/17 13:13:36 packer-builder-vsphere-iso plugin: [ERROR] connection error: http response error: 401 - invalid content type
2021/02/17 13:13:36 packer-builder-vsphere-iso plugin: [ERROR] WinRM connection err: http response error: 401 - invalid content type`

I have verified my HCL, autounattend and PS files, and even attempted the stuff below but to no avail:
1. Set WinRM timeout to 60 minutes
2. Hard setting WinRM user and password statically and through variable
3. Setting WinRM insecure
4. Tried using Packer versions 1.6.5, 1.6.4 and 1.6.0

Relevant files of HCLs, PS1s and autounattend below. This is not the complete file and folder structure, as there isn't anything that would pertain to this issue.
[packer_github_issue.zip](https://github.com/hashicorp/packer/files/5996936/packer_github_issue.zip)

It seems to ignore the configured/explicitly set WinRM username and password? What do you think it could be?

Thank you all,

Daniel

**Comment by mrdanielmartins** [comment]
Ah, I found the source of my troubles! 

I previously had my VARs like so:

```
variable "winadmin_username" {
  type    = string
  default = ""
}

variable "winadmin_password" {
  type      = string
  default   = ""
  sensitive = true
}

```
For luck, I did the following: 

```
variable "winadmin_username" {
}
variable "winadmin_password" {
  sensitive = true
}
```

It seems the declared default variables were overwriting my explicitly set variables file! 

Apologies if this behaviour is expected and all due to user error on my side.

Thank you all,

Daniel

**Comment by SwampDragons** [comment]
oh, phew! I was just trying to test this and really struggling to figure out what was going wrong 😅

**Comment by SwampDragons** [comment]
The declared default should _not_ be overriding an explicitly set file though. I'll look into that.

**Comment by SwampDragons** [comment]
I was just tinkering with a local example and can't get the defaults declared in a `*.pkr.hcl` file to override variable values supplied by a `*.pkrvars.hcl` or a `*.auto.pkrvars.hcl` file. How are you calling Packer?

**Comment by mrdanielmartins** [comment]
Should have posted that before hehe. 

I use a Gitlab pipeline that runs a Docker container with the latest alpine. This in turn is used to run/call Packer.
