### ISSUE TITLE
Windows 10 EFI boot problem

### ISSUE THREAD

**Issue by ibeerens** [hashicorp/packer#10653]
I'm using the Packer Builder for VMware vSphere (vsphere-iso) creation and tried to install Windows 10 using an EFI firmware. First I've got the boot manager, when selecting the EFI VMware Virtual SATA CDROM drive the message "Press any key to boot from CD or DVD" appears. When pressing "enter" the setup starts. Is there a way to automatically start the Windows 10 installation without modifying the Windows ISO?

![boot](https://user-images.githubusercontent.com/8385245/108355998-d33a5200-71eb-11eb-8543-76ccb6e99ef5.png)
![Press](https://user-images.githubusercontent.com/8385245/108356009-d59cac00-71eb-11eb-8357-52a39cf0529d.png)

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out. You can send keypresses using the boot_command option: https://www.packer.io/docs/builders/vmware/vsphere-iso#boot-configuration.

If you're struggling to get Packer working for the first time, I'd recommend reaching out to the [mailing [community forum](https://discuss.hashicorp.com/c/packer) for help. The forum has more people on it than the Github Issue tracker, and more users who may have had your exact situation.
