### ISSUE TITLE
oracle-oci builder always fails due to missing key_file argument

### ISSUE THREAD

**Issue by cdivita** [hashicorp/packer#10663]
#### Overview of the Issue

The `oracle-oci` builder within any template, even the basic one in the documentation, fails with the following error:
> Error: 1 error(s) occurred:
>
>* 'key_file' must be specified

The OCI configuration file is available in the default location. Even if the `key_file` argument is provided, the build continues to fail.

#### Reproduction Steps

Just launch a packer build on a template that uses `oracle-oci` builder.

### Packer version

From `1.6.5`, `1.6.6`, `1.7.0`

### Simplified Packer Buildfile
```
{
  "builders": [
    {
      "availability_domain": "UpwH:US-ASHBURN-AD-1",
      "region": "us-ashburn-1",
      "base_image_ocid": "ocid1.image.oc1.....",
      "compartment_ocid": "ocid1.compartment.oc1..",
      "image_name": "Test",
      "shape": "VM.Standard1.1",
      "ssh_username": "ubuntu",
      "subnet_ocid": "ocid1.subnet.oc1.iad.....",
      "type": "oracle-oci"
    }
  ]
}
```
### Operating system and Environment details

I tried both on Windows 10 (64 bit) and Oracle Linux 7

### Log Fragments and crash.log files
No specific logs are available

**Comment by SwampDragons** [comment]
I think this may have just been solved by #10560 -- you can download the branch test artifact from our CI server here https://app.circleci.com/pipelines/github/hashicorp/packer/8977/workflows/e4f57e81-f879-496c-a8f4-d15266512079/jobs/106397/artifacts.

Can you verify that updating the SDK resolved this?

**Comment by cdivita** [comment]
Hi I confirm that #10560 fixed the issue, thanks a lot !!

**Comment by SwampDragons** [comment]
🎉

**Comment by SwampDragons** [comment]
In that case, I'm going to close this issue. This will go out with the v1.7.1 patch release, or can be gotten from the next "nightly" build which will get released on GitHub next Tuesday.

**Comment by steve-allied-man** [comment]
@SwampDragons Hey hey,

I'm facing same issue on Amazon Linux 2. 

I've downloaded the latest branch test artifact from your CI, there: https://app.circleci.com/pipelines/github/hashicorp/packer/9446/workflows/a71822b4-8319-425c-a82a-d045bfd043d6/jobs/112981/artifacts  

So, executing that binary using direct path

`./packer_linux_amd64 build -debug image-file.json`


Checking the version shows:
```
[root@ip-10-121-131-119 tmp]# ./packer_linux_amd64 version
Packer v1.7.1-dev
```

Error same as was reported:
```
[root@ip-10-121-131-119 tmp]# ./packer_linux_amd64 build -debug image-file.json
Error: Failed to prepare build: "oracle-oci"

1 error(s) occurred:

* 'key_file' must be specified


Debug mode enabled. Builds will not be parallelized.

==> Wait completed after 3 microseconds

==> Builds finished but no artifacts were created.
```

I'm just thinking if I'm not doing something right. Could you advise please?
Was moving cert file here and there, using different permissions, etc..



My json file (reworked real values):

```
{
  "builders": [
    {
      "availability_domain": "{{user `availability_domain`}}",
      "base_image_ocid": "{{user `base_image_ocid`}}",
      "communicator": "ssh",
      "compartment_ocid": "{{user `compartment_ocid`}}",
      "fingerprint": "{{user `fingerprint`}}",
      "image_name": "oci_linux765_{{timestamp}}",
      "key_file": "{{user `key_file`}}",
      "region": "{{user `region`}}",
      "shape": "{{user `shape`}}",
      "ssh_username": "opc",
      "subnet_ocid": "{{user `subnet_ocid`}}",
      "tenancy_ocid": "{{user `tenancy_ocid`}}",
      "type": "oracle-oci",
      "user_ocid": "{{user `user_ocid`}}"
    }
  ],
  "variables": {
    "availability_domain": "IrvI:EU-FRANKFURT-...",
    "base_image_ocid": "ocid1.image.oc1...",
    "compartment_ocid": "ocid1.compartment.oc1...",
    "key_file": "~/.oci/cert.pem",
    "fingerprint": "....",
    "region": "eu-frankfurt-1",
    "shape": "VM.Standard.E3.Flex",
    "subnet_ocid": "ocid1.subnet.oc1...",
    "tenancy_ocid": "ocid1.tenancy.oc1...",
    "user_ocid": "ocid1.user.oc1...."
  }
}
```

Thanks
