### ISSUE TITLE
Ansible Collections get ignored by default using ansible-local provisioner

### ISSUE THREAD

**Issue by emansom** [hashicorp/packer#10666]
#### Overview of the Issue

Providing the `ansible-local` provisioner with a [`galaxy_file`](https://github.com/hashicorp/packer/blob/v1.7.0/provisioner/ansible-local/provisioner.go#L68) results in no Ansible Collections being installed.

Upstream Ansible project are [aware](https://github.com/ansible/ansible/pull/67843) of this issue and have [documented](https://github.com/ansible/ansible/pull/67843#issuecomment-629572885) when the behavior of the `ansible-galaxy` results in installation of collections and roles and when not. Following table created by @jborean93 eleborates on it further:
| Command                                                 | Installed roles?     | Installed collections?  | Change in behaviour                           |
|---------------------------------------------------------|----------------------|-------------------------|-----------------------------------------------|
| `ansible-galaxy install -r requirements.yml`            | Yes                  | Yes                     | Will install collections as well as roles     |
| `ansible-galaxy role install -r requirements.yml`       | Yes                  | No (warning in -vvv)    | Adds msg in -vvv that collections are skipped |
| `ansible-galaxy collection install -r requirements.yml` | No (warning in -vvv) | Yes                     | Adds msg in -vvv that roles are skipped       |
| `ansible-galaxy install -r requirements.yml -p ./`      | Yes                  | No (warning in default) | Adds warning saying collections are skipped   |

#### Potential fix

Removing the `-p` argument from the `ansible-galaxy` command invocation results in the desired behavior of both roles and collections being installed. I locally use a forked version of Packer with [this patch](https://github.com/emansom/packer/commit/242b327e73f41886a67dd918174279476b2936ef) applied with success.

There's a [PR](https://github.com/hashicorp/packer/pull/10667) containing this patch to be applied, before or after further rework.

#### Reproduction Steps

Attempt to install a Ansible Collection using the `ansible-local` provisioner, see provided files below to reproduce. Modify builder type to your needs accordingly; the builder type is not a prerequisite.

### Packer version

`Packer version: 1.6.5 [go1.15.5 linux amd64]`

### Packer Buildfile

`centos8-nginx-lxd.json`
```
{
  "provisioners": [
    {
      "type": "shell",
      "inline": "dnf makecache && dnf -y install epel-release && dnf makecache && dnf install -y python39 libsodium python3-bcrypt python3-paramiko python3-pynacl sshpass python3-pyyaml python3-jinja2 platform-python-pip python3-pip && alternatives --set python /usr/bin/python3.9 && pip3 install ansible"
    },
    {
      "type": "ansible-local",
      "galaxy_file": "requirements.yml",
      "playbook_file": "playbook.yml",
      "extra_arguments": [
        "ansible_python_interpreter=/usr/bin/python3.9"
      ]
    }
  ],
  "builders": [
    {
      "type": "lxd",
      "name": "centos-nginx",
      "image": "images:centos/8-Stream",
      "output_image": "centos-8-nginx-test"
    }
  ]
}
```

### Ansible Playbook

`playbook.yml`
```
---
- hosts: 127.0.0.1
  connection: local
  collections:
    - nginxinc.nginx_core
  roles:
    - role: nginx
```

### Ansible Collections requirements file
`requirements.yml`
```
---
collections:
  - name: nginxinc.nginx_core
    version: 0.3.0
```

### Operating system and Environment details

Workstation running Linux, latest stable Packer and LXD.

### Log Fragments and crash.log files

See following [gist](https://gist.github.com/emansom/61cd34555b96dda6230e32d962d66e1a). Excerpt where it goes haywire:
```
2021/02/19 21:19:39 packer-builder-lxd plugin: Executing lxc exec: /bin/sh []string{"/bin/sh", "-c", "lxc exec packer-acme-focal -- /bin/sh -c \"cd /tmp/packer-provisioner-ansible-local/60301cdb-5fcb-3f4b-cc3f-515856a077d2 && ANSIBLE_FORCE_COLOR=1 PYTHONUNBUFFERED=1 ansible-playbook /tmp/packer-provisioner-ansible-local/60301cdb-5fcb-3f4b-cc3f-515856a077d2/playbook.yml --extra-vars \"packer_build_name=acme-focal packer_builder_type=lxd packer_http_addr=ERR_HTTP_ADDR_NOT_IMPLEMENTED_BY_BUILDER -o IdentitiesOnly=yes\" -vv ansible_python_interpreter=/usr/bin/python3.9 -c local -i /tmp/packer-provisioner-ansible-local/60301cdb-5fcb-3f4b-cc3f-515856a077d2/packer-provisioner-ansible-local240743931\""}
==> acme-focal: [WARNING]: No inventory was parsed, only implicit localhost is available
==> acme-focal: [WARNING]: provided hosts list is empty, only localhost is available. Note that
==> acme-focal: the implicit localhost does not match 'all'
==> acme-focal: ERROR! the role 'nginx' was not found in nginxinc.nginx_core:ansible.legacy:/tmp/packer-provisioner-ansible-local/60301cdb-5fcb-3f4b-cc3f-515856a077d2/roles:/root/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/tmp/packer-provisioner-ansible-local/60301cdb-5fcb-3f4b-cc3f-515856a077d2
==> acme-focal: 
==> acme-focal: The error appears to be in '/tmp/packer-provisioner-ansible-local/60301cdb-5fcb-3f4b-cc3f-515856a077d2/playbook.yml': line 7, column 7, but may
==> acme-focal: be elsewhere in the file depending on the exact syntax problem.
==> acme-focal: 
==> acme-focal: The offending line appears to be:
==> acme-focal: 
==> acme-focal:   roles:
==> acme-focal:     - role: nginx
==> acme-focal:       ^ here
2021/02/19 21:19:39 packer-builder-lxd plugin: lxc exec execution exited with '1': 'cd /tmp/packer-provisioner-ansible-local/60301cdb-5fcb-3f4b-cc3f-515856a077d2 && ANSIBLE_FORCE_COLOR=1 PYTHONUNBUFFERED=1 ansible-playbook /tmp/packer-provisioner-ansible-local/60301cdb-5fcb-3f4b-cc3f-515856a077d2/playbook.yml --extra-vars "packer_build_name=acme-focal packer_builder_type=lxd packer_http_addr=ERR_HTTP_ADDR_NOT_IMPLEMENTED_BY_BUILDER -o IdentitiesOnly=yes" -vv ansible_python_interpreter=/usr/bin/python3.9 -c local -i /tmp/packer-provisioner-ansible-local/60301cdb-5fcb-3f4b-cc3f-515856a077d2/packer-provisioner-ansible-local240743931'
```

**Comment by emansom** [comment]
@alessfg I ran into this issue while trying to deploy the NGINX Ansible Collection on CentOS 8 (with latest stable Ansible, pip installed) utilizing Packer using the `ansible-local` provisioner.

The `ansible` and `ansible-local` seem to have different behavior regarding Ansible collections.

Are you able to reproduce the bug of the NGINX Ansible Collection not being installed by Packer, when running with the `ansible-local` provisioner?
I'm asking because you seem to be the maintainer of said collection and might have stumbled on this issue as well.

**Comment by alessfg** [comment]
I have not tested the `ansible-local` provisioner, but the `ansible` provisioner works fine on my end (check https://github.com/alessfg/nginx-controller-automation-demo/blob/main/packer/nginx/nginx.pkr.hcl#L64-L74). IIRC you are right in that there's some differences re how requirements are parsed when using the `ansible` vs `ansible-local` provisioners. Looks like the `ansible-local` provisioner might need to be updated.
