### ISSUE TITLE
vsphere-iso vsphere-clone mac_address

### ISSUE THREAD

**Issue by sburgess123** [hashicorp/packer#10669]
#### Overview of the Issue

I'm trying to fix the mac address/ip on a windows vm which will ultimately allow me to install some required additional software before converting to a template. I have tried this using both vsphere-iso and vsphere-clone builders to set the mac address and get similar errors 
vsphere-iso error:
"error creating vm: Invalid configuration for device '2'"

vsphere-clone error:
"error creating vm: Invalid configuration for device '0'"

I am able to set the mac address on vm's generally through the vsphere client with no issue using the same credentials

#### Reproduction Steps

Steps to reproduce this issue

### Simplified Packer Buildfile

"guest_os_type": "windows9Server64Guest",
"insecure_connection": "true",
"iso_paths": [
"{{user `os_iso_path`}}",
"{{user `vmtools_iso_path`}}/windows.iso"
],
"remove_cdrom": true,
"network_adapters": [
{
  "network": "{{user `vsphere-network`}}",
  "network_card": "vmxnet3",
  "mac_address": "00-50-56-12-34-56"
}
],
"notes": "Built via Packer",
"password": "{{user `vsphere-password`}}",
"disk_controller_type": "lsilogic-sas",
"storage": [
{
  "disk_size": "{{user `vm-disk-size`}}",
  "disk_thin_provisioned": true
}
],
"type": "vsphere-iso",

### Operating system and Environment details

Windows 2016 server, VCenter Server 7

### Log Fragments and crash.log files

021/02/20 10:44:21 [INFO] Packer version: 1.6.6 [go1.15.6 windows amd64]
2021/02/20 10:44:21 Checking 'PACKER_CONFIG' for a config file path
2021/02/20 10:44:21 'PACKER_CONFIG' not set; checking the default config file path
2021/02/20 10:44:21 Attempting to open config file: C:\Users\burgess\AppData\Roaming\packer.config
2021/02/20 10:44:21 [WARN] Config file doesn't exist: C:\Users\burgess\AppData\Roaming\packer.config
2021/02/20 10:44:21 Setting cache directory: C:\git\windows-base-templates\provision\packer\packer_cache
cannot determine if process is in background: Process background check error: not implemented yet
2021/02/20 10:44:21 Creating plugin client for path: C:\Apps\packer\packer_1.6.6\packer.exe
2021/02/20 10:44:21 Starting plugin: C:\Apps\packer\packer_1.6.6\packer.exe []string{"C:\\Apps\\packer\\packer_1.6.6\\packer.exe", "plugin", "packer-builder-vsphere-iso"}
2021/02/20 10:44:21 Waiting for RPC address for: C:\Apps\packer\packer_1.6.6\packer.exe
2021/02/20 10:44:21 packer.exe plugin: [INFO] Packer version: 1.6.6 [go1.15.6 windows amd64]
2021/02/20 10:44:21 packer.exe plugin: Checking 'PACKER_CONFIG' for a config file path
2021/02/20 10:44:21 packer.exe plugin: 'PACKER_CONFIG' not set; checking the default config file path
2021/02/20 10:44:21 packer.exe plugin: Attempting to open config file: C:\Users\burgess\AppData\Roaming\packer.config
2021/02/20 10:44:21 packer.exe plugin: [WARN] Config file doesn't exist: C:\Users\burgess\AppData\Roaming\packer.config
2021/02/20 10:44:21 packer.exe plugin: Setting cache directory: C:\git\windows-base-templates\provision\packer\packer_cache
2021/02/20 10:44:21 packer.exe plugin: args: []string{"packer-builder-vsphere-iso"}
2021/02/20 10:44:21 packer.exe plugin: Plugin port range: [10000,25000]
2021/02/20 10:44:21 packer.exe plugin: Plugin address: tcp 127.0.0.1:10000
2021/02/20 10:44:21 packer.exe plugin: Waiting for connection...
2021/02/20 10:44:21 Received tcp RPC address for C:\Apps\packer\packer_1.6.6\packer.exe: addr is 127.0.0.1:10000
2021/02/20 10:44:21 packer.exe plugin: Serving a plugin connection...
2021/02/20 10:44:21 Creating plugin client for path: C:\Apps\packer\packer_1.6.6\packer.exe
2021/02/20 10:44:21 Starting plugin: C:\Apps\packer\packer_1.6.6\packer.exe []string{"C:\\Apps\\packer\\packer_1.6.6\\packer.exe", "plugin", "packer-provisioner-powershell"}
2021/02/20 10:44:21 Waiting for RPC address for: C:\Apps\packer\packer_1.6.6\packer.exe
2021/02/20 10:44:22 packer.exe plugin: [INFO] Packer version: 1.6.6 [go1.15.6 windows amd64]
2021/02/20 10:44:22 packer.exe plugin: Checking 'PACKER_CONFIG' for a config file path
2021/02/20 10:44:22 packer.exe plugin: 'PACKER_CONFIG' not set; checking the default config file path
2021/02/20 10:44:22 packer.exe plugin: Attempting to open config file: C:\Users\burgess\AppData\Roaming\packer.config
2021/02/20 10:44:22 packer.exe plugin: [WARN] Config file doesn't exist: C:\Users\burgess\AppData\Roaming\packer.config
2021/02/20 10:44:22 packer.exe plugin: Setting cache directory: C:\git\windows-base-templates\provision\packer\packer_cache
2021/02/20 10:44:22 packer.exe plugin: args: []string{"packer-provisioner-powershell"}
2021/02/20 10:44:22 packer.exe plugin: Plugin port range: [10000,25000]
2021/02/20 10:44:22 packer.exe plugin: Plugin address: tcp 127.0.0.1:10000
2021/02/20 10:44:22 packer.exe plugin: Waiting for connection...
2021/02/20 10:44:22 Received tcp RPC address for C:\Apps\packer\packer_1.6.6\packer.exe: addr is 127.0.0.1:10000
2021/02/20 10:44:22 packer.exe plugin: Serving a plugin connection...
2021/02/20 10:44:22 Preparing build: vsphere-iso
vsphere-iso: output will be in this color.
2021/02/20 10:44:22 Build debug mode: false

2021/02/20 10:44:22 Force build: true
2021/02/20 10:44:22 On error:
2021/02/20 10:44:22 Waiting on builds to complete...
2021/02/20 10:44:22 Starting build run: vsphere-iso
2021/02/20 10:44:22 Running builder: vsphere-iso
2021/02/20 10:44:22 [INFO] (telemetry) Starting builder vsphere-iso
2021/02/20 10:44:22 packer.exe plugin: No URLs were provided to Step Download. Continuing...
2021/02/20 10:44:22 packer.exe plugin: No CD files specified. CD disk will not be made.
==> vsphere-iso: Creating VM...
2021/02/20 10:44:24 [INFO] (telemetry) ending vsphere-iso
Build 'vsphere-iso' errored after 2 seconds 385 milliseconds: error creating vm: Invalid configuration for device '2'.
==> Wait completed after 2 seconds 386 milliseconds
2021/02/20 10:44:24 machine readable: error-count []string{"1"}
==> Some builds didn't complete successfully and had errors:
2021/02/20 10:44:24 machine readable: vsphere-iso,error []string{"error creating vm: Invalid configuration for device '2'."}
==> Builds finished but no artifacts were created.
2021/02/20 10:44:24 [INFO] (telemetry) Finalizing.

==> Wait completed after 2 seconds 386 milliseconds

==> Some builds didn't complete successfully and had errors:
--> vsphere-iso: error creating vm: Invalid configuration for device '2'.

==> Builds finished but no artifacts were created.
2021/02/20 10:44:25 waiting for all plugin processes to complete...
2021/02/20 10:44:25 C:\Apps\packer\packer_1.6.6\packer.exe: plugin process exited

**Comment by sburgess123** [comment]
Anyone had the same issue? Would be good to know if it is a bug or I'm doing something wrong ☺️

**Comment by aru-vmw** [comment]
lsilogic-sas is not a valid disk_controller_type,I think you mean lsisas

**Comment by sburgess123** [comment]
I should add this is a fully working configuration until I add the mac_address field
