### ISSUE TITLE
OpenStack Builder: source_image_filter with wildcards for "name" field

### ISSUE THREAD

**Issue by stefankaufmann** [hashicorp/packer#10675]
#### Description

When using the OpenStack Builder, there is no possibility to filter for source images which contain a certain string in its name. 
The feature should work like https://www.packer.io/docs/builders/amazon/ebs#source_ami_filter

#### Use Case(s)

Our openstack is set up to automatically sync base images for different ubuntu versions. Since timestamps are contained in the name of the image, we always need to change the base image accordingly. This could be prevented if this feature was present. 

The configuration could look like
```
"source_image_filter": {
    "name" : "auto-sync/ubuntu-focal-*"
}
```

**Comment by SwampDragons** [comment]
This seems like a cool idea, and would make an excellent new [data source](https://www.packer.io/docs/plugins/creation/custom-datasources) contribution, or option on the openstack builder. I doubt the internal team will have a chance to work on it for a while, but if anyone wants to write their own plugin or PR the openstack builder, contributions are welcome.
