### ISSUE TITLE
Transition to use aws-sdk-go v2

### ISSUE THREAD

**Issue by SwampDragons** [hashicorp/packer#10691]
There are rumblings that the v1 sdk may be getting deprecated in a year or so; we should investigate what it would take to upgrade so we don't get caught out. 

I don't think it's necessary to investigate until after the core-plugin split is complete, so I'm targeting for v1.8.1

**Comment by Oritasenguah** [comment]
Hi, I am having this issue 

Build 'amazon-ebs' errored after 11 milliseconds 339 microseconds: error validating regions: MissingRegion: could not find region configuration

Is there a fix?

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out. I doubt that error is related to this ticket. This error happens when you do not have the [region](https://www.packer.io/docs/builders/amazon/ebs#region) option set in your config and also do not have an AWS_DEFAULT_REGION environment variable set.
