### ISSUE TITLE
Does the On-Error Provisioner now work in HCL in 1.7.0?

### ISSUE THREAD

**Issue by timblaktu** [hashicorp/packer#10701]
I've been working around the issue of the on-error provisioner not working in HCL, by catching a return code from packer in a shell script. I see now that there is documentation for the on-error provisioner in the HCL-specific docs:

https://www.packer.io/docs/templates/hcl_templates/blocks/build/provisioner#on-error-provisioner

But I didn't see any reference to this in the release notes and just wanted to ask: **Does the On-Error Provisioner now work in HCL in 1.7.0?**

**Comment by SwampDragons** [comment]
Yep!  It didn't make it into the release email with everything else going on but it's in the changelog. From https://github.com/hashicorp/packer/blob/master/CHANGELOG.md#improvements-1

> core/hcl: Templates now support error-cleanup-provisioner. [GH-10604]
