### ISSUE TITLE
Retrieving windows password over winrm times-out intermittently due to hardcoded 3 minute limit. (googlecompute builder)

### ISSUE THREAD

**Issue by tasha-marreiros** [hashicorp/packer#10717]
Please search the existing issues for relevant feature requests, and use the
reaction feature
(https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
to add upvotes to pre-existing requests.

#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

<img width="793" alt="Screenshot 2021-03-03 at 18 01 05" src="https://user-images.githubusercontent.com/10209582/109850460-72c6fe00-7c4a-11eb-803e-9d33d1075489.png">
Windows password times out intermittently due to the 3 minute hardcoded timeout. It would be good to see this made configurable as per the AWS builder.

#### Use Case(s)

Any relevant use-cases that you see.

#### Potential configuration

```
Pass in an option to configure windows_password_timeout
```

**Comment by tasha-marreiros** [comment]
Happy to look at contributing to fix this bug.

**Comment by SwampDragons** [comment]
That would be great!

**Comment by tasha-marreiros** [comment]
I've accepted the CLA but it's not showing up, I'm not sure why. Any ideas? When I click the CLA agreement link it shows that I have accepted it. I have two emails attached to my account and I have tried with both...

**Comment by nywilken** [comment]
> I've accepted the CLA but it's not showing up, I'm not sure why. Any ideas? When I click the CLA agreement link it shows that I have accepted it. I have two emails attached to my account and I have tried with both...

Hi @tasha-marreiros thanks for the heads up. I'll trigger a recheck on the CLA to see if it just needs a kick. If that doesn't work please make sure that your primary email within your GitHub profile matches the address you used in your commit. Otherwise the CLA bot will flag the commit as unsigned.

**Comment by tasha-marreiros** [comment]
Seems to have got into a right state. I can clearly see that I have signed it, but it now seems to think I am two people! :)
