### ISSUE TITLE
Documentation on SSH communicator options are missing

### ISSUE THREAD

**Issue by jasonmccallister** [hashicorp/packer#10722]
#### Overview of the Issue

When trying to configure the SSH communicator to use a remote server with the `null` source, the options for ssh authentication are missing. For example, `ssh_private_key_file` is valid but not documented on this page: https://github.com/hashicorp/packer/blob/master/website/content/docs/communicators/ssh.mdx

### Packer version

Packer v1.7.0

### Simplified Packer Buildfile

```
source "null" "remote" {
  ssh_host = var.host
  ssh_username = var.username
  ssh_private_key_file = var.private_key
  communicator = "ssh"
}

variable "host" {
    type = string
}

variable "private_key" {
    type = string
    default = "~/.ssh/id_rsa"
}

variable "username" {
    type = string
    default = "ubuntu"
}

build {
  sources = ["sources.null.remote"]
}
```

**Comment by SwampDragons** [comment]
Interesting. I've never heard of a use case where the null builder needed this option. Can you give me a little more info about how you're using the null builder here?

The ssh_private_key_file is a value that is valid for some, but not all, builders -- but this is documented on the linked page:

```
~> Note: SSH communicator options: ssh_keypair_name, ssh_agent_auth, temporary_key_pair_name and ssh_private_key_file are also supported by the communicator. But they may not be supported for every builder. Please check the builder specific documentation for additional SSH supported options.
```

If it's working as you expect, we could add it to the https://www.packer.io/docs/builders/null page, though.

**Comment by jasonmccallister** [comment]
@SwampDragons yeah, I'm too lazy to use another tool and setup a null source to provision a Raspberry Pi. Here is the example `build.pkr.hcl`:

```hcl
source "null" "remote" {
  ssh_host             = var.host
  ssh_username         = var.username
  ssh_private_key_file = var.private_key
  communicator         = "ssh"
}

build {
  sources = [
    "sources.null.remote"
  ]

  provisioner "shell" {
    script = "${path.cwd}/scripts/setup_ubuntu.sh"
  }
}
```
