### ISSUE TITLE
packer 1.6.6 & 1.7.0 silently exit with non-zero return value: strace logs

### ISSUE THREAD

**Issue by taqtiqa-mark** [hashicorp/packer#10749]
#### Overview of the Issue

After installing packer `1.6.6` or `1.7.0` for arch `amd64` using this chef recipe:
```ruby
  ark 'Install Hashicorp Packer binary' do
    action :install
    append_env_path true
    checksum hashicorp.packer_checksum
    has_binaries [hashicorp.packer_name]
    mode '0755'
    name hashicorp.packer_name
    prefix_root hashicorp.bin_root
    strip_components 0
    url "https://releases.hashicorp.com/packer/#{hashicorp.packer_version}/packer_#{hashicorp.packer_version}_linux_#{hashicorp.install_arch}.zip"
    version hashicorp.packer_version
  end
```

We observe Packer silently failing to start:

```bash
$ strace -r packer &>packer-1.6.6-abend.log
$ echo $?
1
```
The checksum values are:

`1.6.6` sha256: `721d119fd70e38d6f2b4ccd8a39daf6b4d36bf5f7640036acafcaaa967b00c3b`
`1.7.0` sha256: `935e81c07381a964bdbaddde2d890c91d52e88b9e5375f3882840925f6a96893`

We install Terraform using the same recipe and experience no problems running terraform.

#### Reproduction Steps

As described above.

### Packer version

The command `packer version` returns nothing.  We have tried with version `1.6.6` and `1.7.0`

### Simplified Packer Buildfile

NA.

### Operating system and Environment details

```bash
$ uname -a
Linux desktop.local.lan 5.4.0-54-generic #60~18.04.1-Ubuntu SMP Fri Nov 6 17:25:16 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

### Log Fragments and crash.log files

For version `1.6.6`:  [`strace -r packer`](https://gist.github.com/taqtiqa-mark/d29b7fe806e997f40d70df22660d7592)
For version `1.7.0`:  [`strace -r packer`](https://gist.github.com/taqtiqa-mark/abafd2f7e3f5dca1ac6f86f05466cc05)

**Comment by azr** [comment]
Hello there, thanks for reporting. I'm running on a Mac and could not repro with `docker run -it ubuntu:20.10 bash` or `docker run -it ubuntu:18.04 bash`, though: `uname -a` gives me: `Linux 89ee4072c0ca 4.19.121-linuxkit `. Trying with a VM.

**Comment by azr** [comment]
Yup works on that brand new ubuntu vm too; is there something security that could be blocking your binary ? I'll try looking for a reason.

```
uname -a
Linux parallels-Parallels-Virtual-Platform 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by azr** [comment]
In the meantime, maybe try giving the machine more ram/cpu ?? Does that change anything ?

**Comment by azr** [comment]
Hello again, in the meantime; maybe it could be related to: https://github.com/hashicorp/packer/issues/10687

**Comment by SwampDragons** [comment]
does this happen if you call Packer without `strace`?

**Comment by taqtiqa-mark** [comment]
@SwampDragons  and @azr I've tracked this down to the way `~/.packer.d` is configured.  We setup plugins using links to versioned paths - as `ark` usage shown above does. I haven't worked out exactly what links and permissions result in this behavior.

I believe this is a separate issue to #10687.  
That seems to be related to JSON files this relates to the way `~/.packer.d` or `~/.packer.d/plugins` are setup/configured.

Agreed?

**Comment by taqtiqa-mark** [comment]
Here is a listing of `lsattr -R ~/.packer.d`:

```bash
--------------e--- /home/user/.packer.d/plugins

/home/user/.packer.d/plugins:
--------------e--- /home/user/.packer.d/plugins/vultr

/home/user/.packer.d/plugins/vultr:
--------------e--- /home/user/.packer.d/plugins/vultr/packer-builder-vultr

--------------e--- /home/user/.packer.d/plugins/vultr-2.1.0

/home/user/.packer.d/plugins/vultr-2.1.0:
--------------e--- /home/user/.packer.d/plugins/vultr-2.1.0/packer-builder-vultr

--------------e--- /home/user/.packer.d/plugins/vultr-2.2.0

/home/user/.packer.d/plugins/vultr-2.2.0:
--------------e--- /home/user/.packer.d/plugins/vultr-2.2.0/packer-builder-vultr

--------------e--- /home/user/.packer.d/plugins/github.com

/home/user/.packer.d/plugins/github.com:
--------------e--- /home/user/.packer.d/plugins/github.com/upcloudltd

/home/user/.packer.d/plugins/github.com/upcloudltd:
--------------e--- /home/user/.packer.d/plugins/github.com/upcloudltd/upcloud

/home/user/.packer.d/plugins/github.com/upcloudltd/upcloud:
--------------e--- /home/user/.packer.d/plugins/github.com/upcloudltd/upcloud/packer-plugin-upcloud_v1.0.0_x5.0_linux_amd64_SHA256SUM
--------------e--- /home/user/.packer.d/plugins/github.com/upcloudltd/upcloud/packer-plugin-upcloud_v1.0.0_x5.0_linux_amd64



--------------e--- /home/user/.packer.d/plugins/upcloud-1.0.0

/home/user/.packer.d/plugins/upcloud-1.0.0:
--------------e--- /home/user/.packer.d/plugins/upcloud-1.0.0/CHANGELOG.md
--------------e--- /home/user/.packer.d/plugins/upcloud-1.0.0/packer-plugin-upcloud_v1.0.0_x5.0_linux_amd64
--------------e--- /home/user/.packer.d/plugins/upcloud-1.0.0/LICENSE.txt
--------------e--- /home/user/.packer.d/plugins/upcloud-1.0.0/README.md


--------------e--- /home/user/.packer.d/checkpoint_signature
--------------e--- /home/user/.packer.d/checkpoint_cache
```

**Comment by taqtiqa-mark** [comment]
Here is a listing of `ls -la -R ~/.packer.d`:

```bash
/home/user/.packer.d:
total 20
drwxrwxrwt  3 user user 4096 Mar 16 08:09 .
drwxr-xr-x 61 user user 4096 Mar 16 09:00 ..
-rw-r--r--  1 root  root   320 Mar 16 08:09 checkpoint_cache
-rw-r--r--  1 root  root   394 Mar 16 08:09 checkpoint_signature
drwxrwxrwt  7 user user 4096 Mar 16 08:09 plugins

/home/user/.packer.d/plugins:
total 40
drwxrwxrwt 7 user user 4096 Mar 16 08:09 .
drwxrwxrwt 3 user user 4096 Mar 16 08:09 ..
drwxr-xr-x 3 root  root  4096 Mar 16 08:09 github.com
lrwxrwxrwx 1 root  root    89 Mar 16 08:09 packer-builder-upcloud -> /home/user/.packer.d/plugins/upcloud-1.0.0/packer-plugin-upcloud_v1.0.0_x5.0_linux_amd64
lrwxrwxrwx 1 root  root    62 Mar 16 08:09 packer-builder-vultr -> /home/user/.packer.d/plugins/vultr-2.2.0/packer-builder-vultr
lrwxrwxrwx 1 root  root    89 Mar 16 08:09 packer-plugin-upcloud -> /home/user/.packer.d/plugins/upcloud-1.0.0/packer-plugin-upcloud_v1.0.0_x5.0_linux_amd64
drwxr-xr-x 2 root  root  4096 Mar 16 08:18 upcloud-1.0.0
drwxr-xr-x 2 root  root  4096 Mar 16 08:09 vultr
drwxr-xr-x 2 root  root  4096 Mar 16 08:09 vultr-2.1.0
drwxr-xr-x 2 root  root  4096 Mar 16 08:09 vultr-2.2.0

/home/user/.packer.d/plugins/github.com:
total 12
drwxr-xr-x 3 root  root  4096 Mar 16 08:09 .
drwxrwxrwt 7 user user 4096 Mar 16 08:09 ..
drwxr-xr-x 3 root  root  4096 Mar 16 08:09 upcloudltd

/home/user/.packer.d/plugins/github.com/upcloudltd:
total 12
drwxr-xr-x 3 root root 4096 Mar 16 08:09 .
drwxr-xr-x 3 root root 4096 Mar 16 08:09 ..
drwxr-xr-x 2 root root 4096 Mar 16 08:09 upcloud

/home/user/.packer.d/plugins/github.com/upcloudltd/upcloud:
total 24780
drwxr-xr-x 2 root root     4096 Mar 16 08:09 .
drwxr-xr-x 3 root root     4096 Mar 16 08:09 ..
-rwxr-xr-x 1 root root 25362432 Mar 16 08:09 packer-plugin-upcloud_v1.0.0_x5.0_linux_amd64
-r-xr-xr-x 1 root root       64 Mar 16 08:09 packer-plugin-upcloud_v1.0.0_x5.0_linux_amd64_SHA256SUM

/home/user/.packer.d/plugins/upcloud-1.0.0:
total 24796
drwxr-xr-x 2 root  root      4096 Mar 16 08:18 .
drwxrwxrwt 7 user user     4096 Mar 16 08:09 ..
-rw-r--r-- 1 root  root       116 Feb 20 00:43 CHANGELOG.md
-rw-r--r-- 1 root  root      1079 Feb 20 00:43 LICENSE.txt
-rw-r--r-- 1 root  root      8479 Feb 20 00:43 README.md
-rwxr-xr-x 1 root  root  25362432 Feb 20 00:41 packer-plugin-upcloud_v1.0.0_x5.0_linux_amd64

/home/user/.packer.d/plugins/vultr:
total 28092
drwxr-xr-x 2 root  root      4096 Mar 16 08:09 .
drwxrwxrwt 7 user user     4096 Mar 16 08:09 ..
-rwxr-xr-x 1 root  root  28758016 Mar 16 08:09 packer-builder-vultr

/home/user/.packer.d/plugins/vultr-2.1.0:
total 24900
drwxr-xr-x 2 root  root      4096 Mar 16 08:09 .
drwxrwxrwt 7 user user     4096 Mar 16 08:09 ..
-rwxr-xr-x 1 root  root  25489408 Mar 16 08:09 packer-builder-vultr

/home/user/.packer.d/plugins/vultr-2.2.0:
total 24164
drwxr-xr-x 2 root  root      4096 Mar 16 08:09 .
drwxrwxrwt 7 user user     4096 Mar 16 08:09 ..
-rwxr-xr-x 1 root  root  24735744 Mar 16 08:09 packer-builder-vultr
```

**Comment by taqtiqa-mark** [comment]
Those links and permissions should be acceptable.

Is it possible that `setcap cap_block_suspend=ep /file/path` is required?

**Comment by taqtiqa-mark** [comment]
@azr `PACKER_LOG=1 packer version` as requested follows.  The capability above cannot be set on a symlink.

```bash
~$ PACKER_LOG=1 packer version                                                      
2021/03/16 09:11:57 [INFO] Packer version: 1.7.0 [go1.15.8 linux amd64]                           
2021/03/16 09:11:57 [TRACE] discovering plugins in /usr/local/bin
2021/03/16 09:11:57 [TRACE] discovering plugins in /home/user/.packer.d/plugins                  
2021/03/16 09:11:57 [DEBUG] Discovered plugin: upcloud = /home/user/.packer.d/plugins/packer-builder-upcloud
2021/03/16 09:11:57 [DEBUG] Discovered plugin: vultr = /home/user/.packer.d/plugins/packer-builder-vultr
2021/03/16 09:11:57 [INFO] using external builders: [upcloud vultr]
2021/03/16 09:11:57 [DEBUG] Discovered plugin: upcloud = /home/user/.packer.d/plugins/packer-plugin-upcloud
Error loading configuration: 

fork/exec /home/user/.packer.d/plugins/packer-plugin-upcloud: permission denied
```

**Comment by bbros-dev** [comment]
We've linked this issue to an issue in UpCloud plugin, because @taqtiqa-mark thinks this same issue was encountered while working on a different client's code base.

Hopefully the UpCloud dev @maxfrei can share some insight about whether this issue lies with the plugin code path or the core code path?

**Comment by SwampDragons** [comment]
The "exits silently" part is the same root issue as #10687, and I just pushed a PR to fix it. It should be showing the error message you see in the logs, where it says that there's a permissions issue where Packer can't access: `/home/user/.packer.d/plugins/packer-plugin-upcloud`. 

I just tested with a symlink myself and the symlink itself isn't the issue because I got a working build using a symlink.  What happens if you give "read" permissions to non-root users on the directories inside .packer.d? I haven't had a chance to closely read the code but it may be trying to list the contents of those directories to find packer plugin names.

**Comment by taqtiqa-mark** [comment]
I can get `packer version` to run without error after the following change:

```bash
$ sudo sysctl -w fs.protected_symlinks=0
```

@SwampDragons what is the `#  sysctl fs.protected_symlinks` setting on your system?

**Comment by taqtiqa-mark** [comment]
> is there something security that could be blocking your binary ? I'll try looking for a reason.

@azr I looked at audit logs and saw nothing - but this machine isn't running selinux or apparmour or the like.  The only thing I came across was possibly a missing capability and the `sysctl` setting described above.

I think the sysctl setting provides a workaround, even if it is determined not to be the root cause.
Agreed?

**Comment by azr** [comment]
Hello @taqtiqa-mark, nice, good catch, so because the binary is symlinked and when `fs.protected_symlinks` is set to `1`, the system prevents you from following the symlink, Packer and Packer init don't create symlinks here, also I'd like to note that if you use the plugin within a `required_plugins`, then there will be no need for a symlink, may I ask you why it was created? ( are you working around a Packer issue ?)

Reading the `protected_symlinks` docs:

> When set to “1” symlinks are permitted to be followed only when outside a sticky world-writable directory, or when the uid of the symlink and follower match, or when the directory owner matches the symlink’s owner.

I think that because `/home/user/.packer.d/plugins` belongs to `user` ( and not `root` ), your system denied access.

I'd recommend leaving `protected_symlinks` set to `1` and trying to change the owner of these files and directories to be `user` instead of root to get the following:

```
/home/user/.packer.d/plugins:
drwxrwxrwt 7 user user 4096 Mar 16 08:09 .
drwxrwxrwt 3 user user 4096 Mar 16 08:09 ..
drwxr-xr-x 3 user user  4096 Mar 16 08:09 github.com
lrwxrwxrwx 1 user user    89 Mar 16 08:09 packer-builder-upcloud -> /home/user/.packer.d/plugins/upcloud-1.0.0/packer-plugin-upcloud_v1.0.0_x5.0_linux_amd64
lrwxrwxrwx 1 user user    62 Mar 16 08:09 packer-builder-vultr -> /home/user/.packer.d/plugins/vultr-2.2.0/packer-builder-vultr
lrwxrwxrwx 1 user user    89 Mar 16 08:09 packer-plugin-upcloud -> /home/user/.packer.d/plugins/upcloud-1.0.0/packer-plugin-upcloud_v1.0.0_x5.0_linux_amd64
drwxr-xr-x 2 user user  4096 Mar 16 08:18 upcloud-1.0.0
drwxr-xr-x 2 user user  4096 Mar 16 08:09 vultr
drwxr-xr-x 2 user user  4096 Mar 16 08:09 vultr-2.1.0
drwxr-xr-x 2 user user  4096 Mar 16 08:09 vultr-2.2.0

[...]
/home/user/.packer.d/plugins/github.com/upcloudltd/upcloud:
total 24780
drwxr-xr-x 2 user user     4096 Mar 16 08:09 .
drwxr-xr-x 3 user user     4096 Mar 16 08:09 ..
-rwxr-xr-x 1 user user 25362432 Mar 16 08:09 packer-plugin-upcloud_v1.0.0_x5.0_linux_amd64
-r-xr-xr-x 1 user user       64 Mar 16 08:09 packer-plugin-upcloud_v1.0.0_x5.0_linux_amd64_SHA256SUM
```

**Comment by azr** [comment]
Hello again, we also suggest not running packer ( and `packer init` ) with `root`.


Seeing as this seems to no be a Packer caused problem; I'll close this one; feel free comment here or open a new issue if something's up ! 🙂
