### ISSUE TITLE
 proxmox-clone: Error creating VM: 400 Parameter verification failed.

### ISSUE THREAD

**Issue by jmmeacham** [hashicorp/packer#10747]
#### Overview of the Issue

I get the error ` proxmox-clone: Error creating VM: 400 Parameter verification failed.` but the machine is still built in Proxmox, and I can power this up

#### Reproduction Steps

Steps to reproduce this issue

Run `packer validate -var-file=user.json windows-10.json` (no issues)
Run `packer build --force -var-file=user.json windows-10.json`

### Packer version

Packer v1.7.0

### Simplified Packer Buildfile

[gist](https://gist.github.com/jmmeacham/dc3b43a75d9cda1054145a3b1d747e90)

### Error 

Build 'proxmox-clone' errored after 46 seconds 494 milliseconds: Error creating VM: 400 Parameter verification failed.

### Operating system and Environment details

Proxmox environment
Using Windows 10 image to clone off of with winrm enabled

**Comment by jmmeacham** [comment]
The machine will get cloned, but won't power up resulting in the verification failed?

**Comment by Syntax3rror404** [comment]
How do you enter the username?
Please note, depending on the realm, that you e.g. B. have to enter username@pve for the PVE realm or username@pam for the Linux realm

**Comment by jmmeacham** [comment]
I'm using username@ldap but I'm not sure if authentication really is the issue if the machine is being built anyways
