### ISSUE TITLE
Add Retry to Vsphere Post Processor

### ISSUE THREAD

**Issue by gamethis** [hashicorp/packer#10745]
#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

Add option to retry on failures to upload templates to vsphere environment.
This can be done similar to what was done for vagrant-cloud post processor or can be done with giving customer a option on packer file to add retry and count to retry.

#### Use Case(s)

An intermittent error occurs during the upload phase of template.  Adding a retry variable that retries x number of times to allow greater success.

#### Potential configuration

```
"post-processors":  [
{"type": "vsphere",
"retry": 4,
....
}],
....
```

**Comment by les-tallman** [comment]
I think it would be a good idea to add "retry" for all of the different types of resources.
