### ISSUE TITLE
I am using packer packer_1.7.0 and still got similar errors MissingRegion

### ISSUE THREAD

**Issue by Oritasenguah** [hashicorp/packer#10751]
I am using packer 1.7.0 and still got similar Build 'amazon-ebs' errored after 4 milliseconds 628 microseconds: error validating regions: MissingRegion: could not find region configuration

I am running packer using a JenkinsFile.

==> Wait completed after 4 milliseconds 715 microseconds

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: error validating regions: MissingRegion: could not find region configuration

==> Builds finished but no artifacts were created.
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

Finished: SUCCESS

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out. You need to either set the [region](https://www.packer.io/docs/builders/amazon/ebs#region) option in your config or you need to set the environment variable `AWS_DEFAULT_REGION`
