### ISSUE TITLE
packer init fails to install plugins whose name contain a 'v'

### ISSUE THREAD

**Issue by ddelnano** [hashicorp/packer#10759]
#### Overview of the Issue

I'm the developer for the [packer-plugin-xenserver](https://github.com/ddelnano/packer-plugin-xenserver). I recently upgraded it to use the packer-plugin-sdk and noticed that I was unable to `packer init` despite following all the instructions for migrating to the SDK.

When running `packer init` with the following file in my current working directory I see the following output 
```
ddelnano@ddelnano-desktop:~/code/packer$ cat test.pkr.hcl
packer {
  required_plugins {
   xenserver= {
      version = ">= 0.3.0"
      source = "github.com/ddelnano/xenserver"
    }
   upcloud = {
      version = "= v1.0.0"
      source = "github.com/UpCloudLtd/upcloud"
    }
  }
}

ddelnano@ddelnano-desktop:~/code/packer$ /usr/local/bin/packer1.7 init test.pkr.hcl
could not find a local nor a remote checksum for plugin "github.com/ddelnano/xenserver" ">= 0.3.0"

```
I'm very confident that the packer-plugin-xenserver is compliant and there is something going on inside packer here.

#### Reproduction Steps

1. Install packer 1.7 or later
2.Create the `test.pkr.hcl` as mentioned above
3. Run `PACKER_LOG=1 packer init test.pkr.hcl` and see that it will not install
### Packer version
1.7

**Comment by sylviamoss** [comment]
Thanks for reporting! I see you already opened a PR with the fix. I'll review it.
