### ISSUE TITLE
Cannot decode non-nil codec value into nil error

### ISSUE THREAD

**Issue by mkuzmin** [hashicorp/packer#1076]
After applying change https://github.com/mitchellh/packer/pull/1067 Packer started to fail with error
`reading body codec.decoder: decodeValue: Cannot decode non-nil codec value into nil error (1 methods)`
I have Windows 8 machine.
Full log at https://gist.github.com/mkuzmin/11379996

**Comment by prattpatel** [comment]
I am facing same issues when building windows10. I couldn't debug what does this error mean. 

Build 'virtualbox-iso' errored: 1 error(s) occurred:

* Error destroying builder artifact: reading body codec.decoder: decodeValue: Cannot decode non-nil codec value into nil error (1 methods)

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: 1 error(s) occurred:

* Error destroying builder artifact: reading body codec.decoder: decodeValue: Cannot decode non-nil codec value into nil error (1 methods)

==> Builds finished but no artifacts were created.

**Comment by andrei-dascalu** [comment]
`Build 'virtualbox-iso' errored: 2 error(s) occurred:

* Post-processor failed: Error creating artifact: resource not found
* Error destroying builder artifact: reading body [pos 564]: cannot decode non-nil codec value into nil error (1 methods)

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: 2 error(s) occurred:

* Post-processor failed: Error creating artifact: resource not found
* Error destroying builder artifact: reading body [pos 564]: cannot decode non-nil codec value into nil error (1 methods)

==> Builds finished but no artifacts were created.`

Same thing happening to me as well, Windows10, packer  v0.12.2

**Comment by stephenreay** [comment]
I'm getting this error with packer v1.0.0 when building Parallels images and using the Vagrant-Cloud post processor.

The annoying part is, it *seems* like it successfully uploads a box to atlas, tries to remove something locally from the build, fails, and then "cleans up" by removing the uploaded box.

Maybe its just the messaging that is misleading and that isn't the case?

**Comment by rickard-von-essen** [comment]
@stephenreay Don't resurrect 3 years old bugs open a new issue.
