### ISSUE TITLE
proxmox-iso: additional_iso_files fails when using hcl files

### ISSUE THREAD

**Issue by mmassez** [hashicorp/packer#10771]
#### Overview of the Issue

When building a VM with the proxmox-iso builder the build fails when using additional_iso_files in combination with HCL files.

#### Reproduction Steps

Configure HCL build file with additional_iso_files variable to attach eg autounattend or virtio drivers.
When creating the exact same setup in JSON it works as expected.

### Packer version

Tested with both 1.7.0 and 1.7.1-dev

### Simplified Packer Buildfile
Here is the snippet which makes it fail:
 
    build {
        source "proxmox-iso.proxmox" {
                additional_iso_files {
                device  = "sata5"
                iso_file = "local:iso/Autounattend.iso"
                iso_checksum = "md5:e1b41432886916cbccb69cc8dea4f41d"
            }
        }
        provisioner "shell" {
            inline = [ "echo doing some tests" ]
        }
    }

### Operating system and Environment details

Builds where run on macOS 11.2.2 but I think in this case it's irrelevant as it's internal code.

### Log Fragments and crash.log files

    mmassez@builder windows_2019 % packer build .
    Error: 1 error(s) occurred:

    * 2 errors occurred:
        * unknown configuration key: '"additional_iso_files[0].download_path_key"'
        * unknown configuration key: '"additional_iso_files[0].should_upload_iso"'

    on windows2019.pkr.hcl line 1:
    (source code not available)

    ==> Wait completed after 4 microseconds
    ==> Builds finished but no artifacts were created.

### Workaround
I've found the possible problem. When building from source and updating the builder/proxmox/common/config.go makes it work with the HCL file.
I've added the mapstructure behind both configuration keys and it now works as expected.

    type additionalISOsConfig struct {
    	commonsteps.ISOConfig `mapstructure:",squash"`
	    Device                string `mapstructure:"device"`
    	ISOFile               string `mapstructure:"iso_file"`
    	ISOStoragePool        string `mapstructure:"iso_storage_pool"`
    	Unmount               bool   `mapstructure:"unmount"`
    	ShouldUploadISO       bool   `mapstructure:"should_upload_iso"`
	    DownloadPathKey       string `mapstructure:"download_path_key"`
    }

**Comment by sylviamoss** [comment]
Hey there, I wrote a fix for this. You can test the changes with these binaries: https://app.circleci.com/pipelines/github/hashicorp/packer/9670/workflows/32006ab1-733b-4ee5-8655-9c685b4e9c32/jobs/116127/artifacts

**Comment by mmassez** [comment]
Hey, thanks for the quick reply!
I've tested the updated binary for mac and it works as expected now.
