### ISSUE TITLE
vsphere-clone builder not allowing modification of primary disk when multiple disks specified

### ISSUE THREAD

**Issue by sseebald** [hashicorp/packer#10770]
#### Overview of the Issue

In our environment, we're setting the disk_size parameter in order to allow for dynamic resizing of our primary disks - For example, if a template has a single disk of 100g, and a user wants to make a new template with a primary disk of 120g, setting the disk_size will create a new VM with the new size, and then in the OS we have a step to resize the partition accordingly.

We're trying to now allow our users to build templates with multiple disks. We can add this using the storage{} parameter without issue, but if disk_size is used outside of that, we get the following error:

2021-03-17T01:16:55Z: VM has multiple disks

It seems in our case it's either we allow for dynamic re-sizing of the primary disk, or support the notion of multiple disks in our templates. Ideally, we'd like to have both.

#### Reproduction Steps

Steps to reproduce this issue, example builder definition:

    "builders": [
      {
        "type": "vsphere-clone",
        "name": "sseebald windows 2019 - {{ isotime }}",
        "vcenter_server": "{{user `vsphere_server`}}",
        "insecure_connection": "{{user `vm_insecureConnection`}}",
        "username": "{{user `vsphere_access_user`}}",
        "password": "{{user `vsphere_access_password`}}",
        "datacenter": "{{user `vsphere_datacenter`}}",
        "vm_name": "{{user `vm_name`}}",
        "folder": "{{user `vm_folder`}}",
        "cluster": "{{user `vm_cluster`}}",
        "datastore": "{{user `vm_datastore`}}",
        "template": "{{user `vm_template`}}",
        "convert_to_template": "{{user `vm_toTemplate`}}",
        "communicator": "ssh",
        "ssh_username": "{{user `user_ssh_user`}}",
        "ssh_password": "{{user `user_ssh_passwd`}}",
        "winrm_insecure": true,
        "winrm_port": "5985",
        "winrm_timeout": "6h",
        "shutdown_command": "shutdown /s /t 10 /f /d p:4:1 /c \"Packer Shutdown\"",
        "CPUs": "{{user `cpus`}}",
        "CPU_hot_plug": true,
        **"disk_size": "{{user `disk_size`}}",
        "disk_controller_type": ["pvscsi","pvscsi"],
        "storage":
        {
          "disk_size": "204800",
          "disk_thin_provisioned": true,
          "disk_controller_index": 1
        },**
        "RAM": "{{user `memory_size`}}",
        "RAM_hot_plug": true
      }
    ],

This will result in the VMWare error of "VM has multiple disks" during cloning. Defining all disks in the storage{} block seems to just add that many disks, and doesn't allow for the modification of the primary disk.

### Packer version

From `packer version` - 1.7.0

### Operating system and Environment details

Building Windows templates using the latest packer:full container on docker hub, inside of vsphere using the vsphere-clone provider.

**Comment by sylviamoss** [comment]
Hey there, thanks for reporting. I looked at the vsphere builder code and this looks like something that we need to fix. 
We'll work on this as soon as possible.

**Comment by sylviamoss** [comment]
Hey there, I implemented a fix for this. Could you try out the binary and let me know if it works as expected? 
Here they are: https://app.circleci.com/pipelines/github/hashicorp/packer/9867/workflows/071f6d62-1a11-4e31-ac06-a1651a47aeab/jobs/118886/artifacts
