### ISSUE TITLE
local variables are not supported in override section with HCL

### ISSUE THREAD

**Issue by odg0318** [hashicorp/packer#10786]
#### Overview of the Issue

I am writing a packer template using HCL. But local variables cannot be supported in `override` section in `build`.
Additionally, the contextual variables like `source.name` are unavailable in `override` section.

* https://www.packer.io/docs/templates/hcl_templates/blocks/build/provisioner#build-specific-overrides

#### Reproduction Steps

**The code with override**
```hcl
variable "foo" {
  type = string
  default = "foo"
}

locals {
  bar = "bar"
}

source "null" "this" {
  communicator = "none"
}

build {
  sources = ["source.null.this"]

  source "source.null.this" {
    name = "renamed"
  }

  provisioner "shell-local" {
    inline =  ["echo var.foo=${var.foo} local.bar=${local.bar}"]
    override = {
      renamed  = {
        inline =  ["echo var.foo=${var.foo} local.bar=${local.bar}"]
      }
    }
  }
}
```

**The result**
```shell
Error: Unsupported attribute

  on main.pkr.hcl line 25, in build:
  25:         inline =  ["echo var.foo=${var.foo} local.bar=${local.bar}"]

This object does not have an attribute named "bar".
```

But when I changed `provisioner` section like the below without `override`.
```hcl
  provisioner "shell-local" {
    inline =  ["echo var.foo=${var.foo} local.bar=${local.bar}"]
  }
```

It is working fine.
```shell
null.this: output will be in this color.
null.renamed: output will be in this color.

==> null.renamed: Running local shell script: /var/folders/0b/7mq70dgs46q9cyb5n9w963jh0000gn/T/packer-shell412025963
==> null.this: Running local shell script: /var/folders/0b/7mq70dgs46q9cyb5n9w963jh0000gn/T/packer-shell288793027
    null.this: var.foo=foo local.bar=bar
Build 'null.this' finished after 367 milliseconds 50 microseconds.
    null.renamed: var.foo=foo local.bar=bar
Build 'null.renamed' finished after 418 milliseconds 360 microseconds.

==> Wait completed after 418 milliseconds 489 microseconds

==> Builds finished. The artifacts of successful builds are:
--> null.this: Did not export anything. This is the null builder
--> null.renamed: Did not export anything. This is the null builder
```

### Packer version

```shell
$ packer version
Packer v1.7.0
```

### Simplified Packer Buildfile

I already post in the above.

### Operating system and Environment details

Mac

### Log Fragments and crash.log files

N/A

**Comment by odg0318** [comment]
It seems like that `locals` are not included in context and then the error is triggered here.
https://github.com/hashicorp/hcl/blob/main/ops.go#L203

**Comment by odg0318** [comment]
@SwampDragons @azr Can you confirm this issue is a kind of bugs? Otherwise I wrongly used the option?

**Comment by azr** [comment]
Hey @odg0318 ! Yes thanks for reporting; this wasn't supported before but would be a nice add, we plan on thinking about that for `v1.7.2`, you'll hear more about us then. Currently we are working for `1.7.1` which should be released soon-ish.

**Comment by nywilken** [comment]
👋 I'm going to close this issue as this bug is no longer reproducible starting from Packer v1.7.1. If you are still running into problems with the latest release of Packer please let me know and I will gladly reopen.
