### ISSUE TITLE
'compression_level' expected type 'int', got unconvertible type '[]uint8'

### ISSUE THREAD

**Issue by rasa** [hashicorp/packer#1079]
I'm getting

```
* 'compression_level' expected type 'int', got unconvertible type '[]uint8'
```

using

```
{
...
  "post-processors": [
    {
      "compression_level": "{{user `compression_level`}}",
    }
  ],
  "variables": {
    "compression_level": "9",
  }
}
```

which used to work until just recently.

**Comment by dragon788** [comment]
@mitchellh 
I'm saw this error again (on 0.8.0, but going to test with latest) when I pass an int up in the variables section down as a user variable to the post processing phase. If I quote the int in the variables section, it works, but it previously worked as unquoted.

{
  "variables": {
    "vagrant_compression": 1, # "1", works
  },
#Snipped stuff 
 "post-processors": [
    {
      "type": "vagrant",
      "compression_level": "{{user `vagrant_compression`}}",      
    }
  ]
}
