### ISSUE TITLE
Special pageDown not found with vsphere builder

### ISSUE THREAD

**Issue by Arderos** [hashicorp/packer#10796]
#### Overview of the Issue

When using vSphere ISO builder packer fails with "special pagedown not found" error if pageDown is used

#### Reproduction Steps

Install packer
Create a json file with pageDown in boot command
Using vSphere ISO builder initiate build sequence

### Packer version

1.7.0, 1.6.6, 1.6.5

### Operating system and Environment details

Windows 10, Ubuntu Linux 20, vSphere 7
### Log Fragments and crash.log files

[Log](https://gist.github.com/Arderos/2a4c0619130136f7cafa8cff059a41fe)

**Comment by cathode911** [comment]
We also encountered the same bug so we still have to use packer `1.5.6`

Also please beware that on `vSphere 7U2` packer version `1.5.6` fails on task "Put USB HID scan codes" with "A general system error occurred"

**Comment by sylviamoss** [comment]
Are you typing `pagedown` or `pageDown`?  The log shows `pagedown` (without camel case). If that's the case you should type `pageDown` (camel cased).

**Comment by sylviamoss** [comment]
Anyways, I think it makes sense to allow at least both. I'll leave the issue open to that be fixed.

**Comment by Arderos** [comment]
> Are you typing `pagedown` or `pageDown`? The log shows `pagedown` (without camel case). If that's the case you should type `pageDown` (camel cased).

I’m typing ‘pageDown’

**Comment by cathode911** [comment]
same here
<enter><wait10><enter><wait5><pageDown><wait>

so, it's not a letter case issue

**Comment by sylviamoss** [comment]
The code lower case the keystroke itself so that map is wrong by assuming the key with camel case. I'm writing a fix. Thanks again for reporting!

**Comment by sylviamoss** [comment]
@cathode911  or @Arderos, could some of you test the fix, please? 
Here the binaries you can use: https://app.circleci.com/pipelines/github/hashicorp/packer/9849/workflows/0196e948-c1be-42d5-bcc7-ef02898e1851/jobs/118609/artifacts

**Comment by cathode911** [comment]
Sure, will do today’s evening. Thanks !

**Comment by Arderos** [comment]
I can confirm that both ``<PageDown>`` and ``<PageUp>`` are working now

**Comment by Arderos** [comment]
Thanks for the fix! Now only the bug with two disks on the same controller remains and we can migrate to packer 1.7

**Comment by sylviamoss** [comment]
Nice! I'll work on that one next.
