### ISSUE TITLE
Communicatior SSH against Windows OpenSSH fails with: no supported methods remain

### ISSUE THREAD

**Issue by frippe75** [hashicorp/packer#10805]
Using the vSphere-ISO builder to create a Windows Server 2019 image with communicator set to ssh it fails during authentication using private key option.

Logging in using a normal ssh in parallel using the same user and private key file works.
```
# ssh -i  ~/.ssh/ansible  ansible@10.220.254.12
```

**The settings:**
            "communicator":             "ssh",
            "ssh_username":             "ansible",
            "ssh_certificate_file":     "~/.ssh/ansible",
            "ssh_file_transfer_method": "sftp",

**The outcome:**
```
==> win2019: Pausing after run of step 'StepWaitForIp'. Press enter to continue.
==> win2019: Using ssh communicator to connect: 10.220.254.12
==> win2019: Waiting for SSH to become available...
2021/03/22 17:28:14 packer-builder-vsphere-iso plugin: [INFO] Waiting for SSH, up to timeout: 5m0s
2021/03/22 17:28:14 packer-builder-vsphere-iso plugin: [INFO] Attempting SSH connection to 10.220.254.12:22...
2021/03/22 17:28:14 packer-builder-vsphere-iso plugin: [DEBUG] reconnecting to TCP connection for SSH
2021/03/22 17:28:14 packer-builder-vsphere-iso plugin: [DEBUG] handshaking with SSH
2021/03/22 17:28:14 packer-builder-vsphere-iso plugin: [DEBUG] SSH handshake err: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
```

Not sure what is going on behind the scene. Why us the array of methods = [none] ??

**Comment by SwampDragons** [comment]
I think you may be mixing up [ssh_private_key_file](https://www.packer.io/docs/builders/vmware/vsphere-iso#ssh_private_key_file) and ssh_certificate_file?

**Comment by frippe75** [comment]
That solved the issue. Sorry for the late feedback here
