### ISSUE TITLE
Googlecompute builder using IAP errors unless account JSON token is provided

### ISSUE THREAD

**Issue by PhilHayward** [hashicorp/packer#10813]
#### Overview of the Issue

I'm attempting to use the packer googlecompute builder from within Google Cloud.  The packer environment is authenticated with google cloud using the instance service account.  The packer environment is not in the same VPC as the build instance (and resulting GCE image).  My organization prohibits the use of external IPs.  I would like to use IAP to connect to the build instance, to simplify my firewall configuration.

When I run packer, it errors out when attempting to create the IAP tunnel:
googlecompute: Non-retryable tunnel error: ERROR: (gcloud.auth.activate-service-account) Unable to read file []: [Errno 2] No such file or directory: ''

It appears that packer is attempting to invoke gcloud auth activate-service-account, but since I did not provide an auth token file, it's failing.

I expect packer to use the same authentication for IAP as for all other google cloud operations.  If an auth token file has been specified via the account_file option, it should activate the service account as is currently done.  Otherwise, it should allow gcloud to use the default authentication process.

#### Reproduction Steps

1. Create two VPCs, one to host packer, the other to host the build instance.
2. Configure Cloud NAT for both VPCs. 
3. Create a firewall rule in the build instance VPC to allow IAP SSH access (gcloud compute firewall-rules create allow-ssh-ingress-from-iap \
  --direction=INGRESS \
  --action=allow \
  --rules=tcp:22 \
  --source-ranges=35.235.240.0/20)
4. Create a packer service account, and bind the iap.tunnelResourceAccessor role in addition to the standard roles used for google compute.
5. Create a separate 'builder' service account with both the log writer and metrics writer roles.
6. Create an instance ('packer instance') within the packer VPC, with the packer service account attached to the instance.
7. Run the packer build file below from the packer instance, with variables set as appropriate.

### Packer version

1.7.0

### Simplified Packer Buildfile

{
  "builders": [
    {
      "type": "googlecompute",
      "project_id": "{{user `service_project_id`}}",
      "image_name": "image-{{timestamp | clean_resource_name}}",
      "source_image_family": "ubuntu-1804-lts",
      "disk_size": "10",
      "machine_type": "e2-small",
      "ssh_username": "packer",
      "zone": "{{user `build_zone`}}",
      "network_project_id": "{{user `host_project_id`}}",
      "network": "{{user `host_network`}}",
      "subnetwork": "{{user `subnet`}}",
      "omit_external_ip": true,
      "use_internal_ip": true,
      "scopes": ["https://www.googleapis.com/auth/cloud-platform"],
      "service_account_email": "builder@{{user `service_project_id`}}.iam.gserviceaccount.com",
      "use_iap": true,
      "metadata": {}
    }
  ]
}

### Log Fragments and crash.log files

11:55:56  ==> googlecompute: Step Launch IAP Tunnel...
11:55:56  2021/03/23 17:55:54 packer-builder-googlecompute plugin: Finding an available TCP port for IAP proxy
11:55:56  2021/03/23 17:55:54 packer-builder-googlecompute plugin: Found available port: 8849 on IP: 0.0.0.0
11:55:56  2021/03/23 17:55:54 packer-builder-googlecompute plugin: Setting up proxy to listen on localhost at 8849
11:55:56  2021/03/23 17:55:54 packer-builder-googlecompute plugin: Creating tunnel launch script with args []string{"compute", "start-iap-tunnel", "packer-605a2b7d-16d2-0df3-d1f6-5aa4a97b5629", "22", "--local-host-port=localhost:8849", "--zone", "us-west1-b", "--project", "random-critter-7a05"}
11:55:56  2021/03/23 17:55:54 packer-builder-googlecompute plugin: [INFO] (google): Prepending inline gcloud setup script with #!/bin/sh
11:55:56  2021/03/23 17:55:55 packer-builder-googlecompute plugin: stderr: ERROR: (gcloud.auth.activate-service-account) Unable to read file []: [Errno 2] No such file or directory: ''
11:55:56  2021/03/23 17:55:55 packer-builder-googlecompute plugin: NOT RETRYABLE: ERROR: (gcloud.auth.activate-service-account) Unable to read file []: [Errno 2] No such file or directory: ''
11:55:56  ==> googlecompute:
11:55:56  ==> googlecompute: Non-retryable tunnel error: ERROR: (gcloud.auth.activate-service-account) Unable to read file []: [Errno 2] No such file or directory: ''

**Comment by kaivalya97** [comment]
+1. The builder documentation says this "You must be using a Service Account with a credentials file (using the account_file option in the Packer template)".

I would be happy to contribute making the change.

**Comment by azr** [comment]
Hello there ! Indeed, I think this would be important to have. Thanks for proposing to help @kaivalya97, PRs are welcome here 🙂, tell us if you need help.
