### ISSUE TITLE
Unable to use user variable in vagrantfile_template with HCL2 packerfile

### ISSUE THREAD

**Issue by aacebedo** [hashicorp/packer#10828]
#### Overview of the Issue
I am generating a vagrantfile when creating a box with packer. In this vagrantfile, I use variables defined in the packer file.
In the vagrantfile.tpl I add tags like {{ user `myvariable` }}. When I use a JSON packer file, everything is ok.
I upgraded my packer json file into the HCL2 format and the syntax seems to have changed for those variables as they are not replaced anymore. I may be missing something here but the document "engine" page of the JSON section does not exist in the HCL section.

#### Reproduction Steps
- Create a HCL2  packer file using the vagrant post-processor
- In the vagrant post-processor define a vagranfile_template file
- In the vagrantfile template refers to user defined variables coming from the packer file using the {{ user `myvariable` }} syntax.
- Run packer build, the variables are not changed.

### Packer version
1.7.0

### Simplified Packer Buildfile
```
file.pkr.hcl
[...]
  locals {
   mylocal = "helloworld"
  }
  post-processor "vagrant" {
    keep_input_artifact = true
    vagrantfile_template = ./vagrantfile.tpl
  }
[...]

file vagrantfile.tpl
[...]
something = {{ user `mylocal` }}
[...]
```

### Operating system and Environment details
Linux x86_64

### Log Fragments and crash.log files
N/A

**Comment by aacebedo** [comment]
I have investigate a little bit.
It appears that putting `{{ user "VariableName" }}` shall be the way to get the values.
However even if I put a local or a variable in the HCL file, the `ctx.UserVariables` is not empty when the post-processor is called. 
This leads to enter the line `funcs.go:222` located in `packer-plugin-sdk/template/interpolate` where the code is:
```
		if ctx == nil || ctx.UserVariables == nil {
			return "", errors.New("test")
		}
```
So when the `UserVariables` variable is empty I got a weird error containing "test" and it fails the build with:
```
* Post-processor failed: template: root:4:2: executing "root" at <user `.Toto`>: error calling user: test
```

I am still searching why the `UserVariables` is empty when the post processor is called

**Comment by SwampDragons** [comment]
The vagrantfile isn't a full template, and the only variables that can currently be used in it are  {{ .BoxName }} and {{ .SyncedFolder }}

https://www.packer.io/docs/builders/vagrant#template

**Comment by aacebedo** [comment]
Unfortunately it is the case in the json version and it is a feature I heavily relies on. Thus I won't be able to migrate to hcl2 :(
The code gives the impression that it is a feature that will be added (i.e. the "test" error). Do you think it will be placed on the roadmap or juste considered as nice to have and implemented on a best effort basis  ?

**Comment by aacebedo** [comment]
> The vagrantfile isn't a full template, and the only variables that can currently be used in it are  {{ .BoxName }} and {{ .SyncedFolder }}
> 
> https://www.packer.io/docs/builders/vagrant#template

Note that the link is pointing to the builder. The issue I saw is on the post-processor and it mentions user variables (https://www.packer.io/docs/post-processors/vagrant#output)
