### ISSUE TITLE
vmware-iso need add hpet to vmx template

### ISSUE THREAD

**Issue by aru-vmw** [hashicorp/packer#10824]
#### Overview of the Issue

vmware-iso builder is hardcoded a vmx template in

https://github.com/hashicorp/packer/blob/master/builder/vmware/iso/step_create_vmx.go

however, we noticed the hpet is missing from the template, which will result in some recent Windows releases behavior abnormally

for example, some Windows 10 will BSOD during reboot.
also some application unresponsive https://kb.vmware.com/s/article/67175

the VM created by VMware Product will add hpet by default.

VMware recommends enabling hpet to all VMware machine by setting

hpet0.present = "True" 

in the vmx.

#### Reproduction Steps

Create a VM using vmware-iso builder, 
and there is no 'hpet0.present = "True"'  in the vmx
some recent Windows OS will BSOD during reboot.
after adding the hpet, the problem is gone. 

Users can enable the hpet by themselves by adding it to vmx_data filed. 

 "vmx_data": {
                "hpet0.present": "TRUE"
}
but it would be nice to have this setting as the default for vmware-iso builder.

### Packer version

1.7.0

**Comment by justindemars** [comment]
I also discovered this when trying to build an image for Windows Server vNext.  On the vNext boots they would immediately BSOD.  Interestingly enough, on packer v1.7.0 the vm would reboot several times, BSOD on each boot and eventually (maybe after a ~dozen reboots it would eventually boot up into the OOBE and go about the build.  
On Packer v1.6.1 which is used in our CI/CD pipeline, the build will have that initial BSOD and just become completely stuck there.  
I've added this line to the vmx_data field and the issue appears to be cleared up now as well.
