### ISSUE TITLE
Vmware-iso builder not removing cdrom iso from VMX

### ISSUE THREAD

**Issue by kdanthony** [hashicorp/packer#1083]
Using 0.5.2 and vmware-iso builder with remote_host on ESXi server. Despite it stating its removing the cdrom in the output:

```
==> kdatestl01: Cleaning VMX prior to finishing up...
2014/04/29 01:58:41 ui: ==> kdatestl01: Cleaning VMX prior to finishing up...
2014/04/29 01:58:41 ui:     kdatestl01: Detaching ISO from CD-ROM device...
    kdatestl01: Detaching ISO from CD-ROM device...
2014/04/29 01:58:41 /opt/packer/packer-builder-vmware-iso: 2014/04/29 01:58:41 Writing VMX to: /tmp/packer-vmx190820839/kdatestl01.vmx
2014/04/29 01:58:41 ui: ==> kdatestl01: Compacting the disk image
```

It is still there in the resulting VMX:

```
$ grep ide kdatestl01.vmx
ide1:0.devicetype = "cdrom-image"
ide1:0.filename = "/vmfs/volumes/vmfs-18/packer_cache/4c8a332ab7795eade9c9020ff83f8898f5ef05c610ebd8c203fa3eca534d300a.iso"
ide1:0.present = "TRUE"
```

I saw an older bug about this but it was marked as fixed in a previous version. 

If it matters I am specifying a vmx_data:

```
  "vmx_data": {
    "cpuid.coresPerSocket": "{{user `corespersocket`}}",
    "ethernet0.networkName": "{{user `vmnetwork`}}",
    "memsize": "{{user `vram`}}",
    "numvcpus": "{{user `vcpus`}}"
  }
```

**Comment by epowell** [comment]
ISO was still included on my VM as of 0.8.6. To work around this, I'm using `ofvtool --noImageFiles` to export like @noplay did above.

**Comment by doctorobelix** [comment]
I use the vmx_post_data to wipe out the .iso.
Something like.....

      "vmx_data_post": {
	"ide0:0.startConnected": "FALSE",
	"ide0:1.startConnected": "FALSE",
	"ide1:0.startConnected": "FALSE",
	"ide1:1.startConnected": "FALSE",
	"ide0:0.deviceType": "cdrom-raw",
	"ide0:1.deviceType": "cdrom-raw",
	"ide1:0.deviceType": "cdrom-raw",
	"ide1:1.deviceType": "cdrom-raw",
	"ide0:0.clientDevice": "TRUE",
	"ide0:1.clientDevice": "TRUE",
	"ide1:0.clientDevice": "TRUE",
	"ide1:1.clientDevice": "TRUE",
	"ide0:0.present": "FALSE",
	"ide0:1.present": "FALSE",
	"ide1:0.present": "TRUE",
	"ide1:1.present": "FALSE",
	"ide0:0.fileName": "emptyBackingString",
	"ide0:1.fileName": "emptyBackingString",
	"ide1:0.fileName": "{{user `config_iso_dest`}}",
	"ide1:1.fileName": "emptyBackingString",
      }

Note: It may look like this is adding an .iso back in, but the build script make it configurable to attach an .iso, and the variable is actually 'emptyBackingstring" unless it is over-ridden.
Works for ESX5.5 and survives Ovftool packaging.

**Comment by jcmcken** [comment]
``ovftool --noImageFiles`` also works for me (similar to @noplay and @epowell)

**Comment by michaeltlombardi** [comment]
Using 10.1 against ESXi 5.5 and 6, have not seen this issue. Is anyone else still experiencing it or can this be closed?

**Comment by mwhooker** [comment]
Please re-open if anyone still sees with a current version of packer

**Comment by arrjay** [comment]
I can still repo this with packer built from 1d8e381b

**Comment by WareWolf45** [comment]
I'm still getting ISO attached to cdrom and ethernet not removed even tho packer said it did so.

`==> vmware-iso: Cleaning VMX prior to finishing up...
    vmware-iso: Unmounting floppy from VMX...
    vmware-iso: Detaching ISO from CD-ROM device...
    vmware-iso: Disabling VNC server...
    vmware-iso: Removing Ethernet Interfaces...
==> vmware-iso: Skipping export of virtual machine (export is allowed only for ESXi)...
Build 'vmware-iso' finished.

==> Builds finished. The artifacts of successful builds are:
--> vmware-iso: VM files in directory: output-centos7-vmware-iso`

Packer 1.2.5

**Comment by WareWolf45** [comment]
I apologize, my problem (not removing ethernet interface and mounted iso) is resolved after a complete restart of the computer. VMware Fusion went nuts, at some point it gave up distibuting IP as DHCP and my packer images failed spectacularly. I realized one of my windows 10 VM has no DHCP IP and complete reset and start over was in order :D 
As of this moment everything is fine. Thanks

**Comment by SwampDragons** [comment]
Thanks for the update. It sounds like your issue is upstream, so I'm going to close this issue.
