### ISSUE TITLE
vSphere-iso Builder issue with Packer 1.7.0

### ISSUE THREAD

**Issue by yiwryos** [hashicorp/packer#10834]
When attempting to build a VM template using the vsphere-iso builder and packer 1.7.0 with a account using RBAC based on the documentation in here https://www.packer.io/docs/builders/vmware/vsphere-iso I'm getting the following error 

Build 'vsphere-iso' errored after 3 seconds 462 milliseconds: 404 Not Found

==> Wait completed after 3 seconds 462 milliseconds

==> Some builds didn't complete successfully and had errors:
--> vsphere-iso: 404 Not Found

==> Builds finished but no artifacts were created.

I know the code is good because I can build the template via packer when I login to ESX as admin. So my code is valid
Using the same non-priv account I can create the VM and Template using using the vSphere UI. So the custom roles for the account are valid
The documentation under Required vSphere Permissions state the following permission is needed, however that is not a valid role under ESX 6.7

Datacenter (this object):
Datastore -> Low level file operations

There is no Low level file operations role under Datacenter. That is a valid role for the Datastore permissions.

**Comment by yiwryos** [comment]
With logging and debugging enable I can see the following additional errors 

2021/03/26 10:59:06 ui: ==> vsphere-iso: Destroying VM...
2021/03/26 10:59:07 [INFO] (telemetry) ending vsphere-iso
2021/03/26 10:59:07 ui error: Build 'vsphere-iso' errored after 3 seconds 979 milliseconds: 404 Not Found
2021/03/26 10:59:07 ui:
==> Wait completed after 3 seconds 979 milliseconds
2021/03/26 10:59:07 machine readable: error-count []string{"1"}
2021/03/26 10:59:07 ui error:
==> Some builds didn't complete successfully and had errors:
2021/03/26 10:59:07 machine readable: vsphere-iso,error []string{"404 Not Found"}
2021/03/26 10:59:07 ui error: --> vsphere-iso: 404 Not Found
2021/03/26 10:59:07 ui:
==> Builds finished but no artifacts were created.
2021/03/26 10:59:07 [INFO] (telemetry) Finalizing.
2021/03/26 10:59:08 waiting for all plugin processes to complete...
2021/03/26 10:59:08 /usr/local/bin/packer: plugin process exited
2021/03/26 10:59:08 /usr/local/bin/packer: plugin process exited

**Comment by yiwryos** [comment]
This seems to be a similar issue with https://github.com/hashicorp/packer/issues/9807  but no clear solution is provided. 
BTW I did set "set_host_for_datastore_upload" to true and made no difference. `

**Comment by SwampDragons** [comment]
Can you share the complete logs? It's not clear to me what step the 404 is coming from.

**Comment by yiwryos** [comment]
> 
> 
> Can you share the complete logs? It's not clear to me what step the 404 is coming from.

Here is the output with debugging enabled 
2021/03/30 09:17:39 [INFO] Packer version: 1.7.0 [go1.15.8 linux amd64]
2021/03/30 09:17:39 [TRACE] discovering plugins in /usr/local/bin
2021/03/30 09:17:39 [TRACE] discovering plugins in /root/.packer.d/plugins
2021/03/30 09:17:39 [TRACE] discovering plugins in .
2021/03/30 09:17:39 [INFO] PACKER_CONFIG env var not set; checking the default config file path
2021/03/30 09:17:39 [INFO] PACKER_CONFIG env var set; attempting to open config file: /root/.packerconfig
2021/03/30 09:17:39 [WARN] Config file doesn't exist: /root/.packerconfig
2021/03/30 09:17:39 [INFO] Setting cache directory: /build/CaaS-HostOS-Node-Template/packer_cache
2021/03/30 09:17:39 [TRACE] Starting internal plugin packer-builder-vsphere-iso
2021/03/30 09:17:39 Starting plugin: /usr/local/bin/packer []string{"/usr/local/bin/packer", "plugin", "packer-builder-vsphere-iso"}
2021/03/30 09:17:39 Waiting for RPC address for: /usr/local/bin/packer
2021/03/30 09:17:39 packer-builder-vsphere-iso plugin: [INFO] Packer version: 1.7.0 [go1.15.8 linux amd64]
2021/03/30 09:17:39 packer-builder-vsphere-iso plugin: [INFO] PACKER_CONFIG env var not set; checking the default config file path
2021/03/30 09:17:39 packer-builder-vsphere-iso plugin: [INFO] PACKER_CONFIG env var set; attempting to open config file: /root/.packerconfig
2021/03/30 09:17:39 packer-builder-vsphere-iso plugin: [WARN] Config file doesn't exist: /root/.packerconfig
2021/03/30 09:17:39 packer-builder-vsphere-iso plugin: [INFO] Setting cache directory: /build/CaaS-HostOS-Node-Template/packer_cache
2021/03/30 09:17:39 packer-builder-vsphere-iso plugin: args: []string{"packer-builder-vsphere-iso"}
2021/03/30 09:17:39 packer-builder-vsphere-iso plugin: Plugin address: unix /tmp/packer-plugin281555699
2021/03/30 09:17:39 packer-builder-vsphere-iso plugin: Waiting for connection...
2021/03/30 09:17:39 Received unix RPC address for /usr/local/bin/packer: addr is /tmp/packer-plugin281555699
2021/03/30 09:17:39 packer-builder-vsphere-iso plugin: Serving a plugin connection...
2021/03/30 09:17:39 [TRACE] Starting internal plugin packer-provisioner-shell
2021/03/30 09:17:39 Starting plugin: /usr/local/bin/packer []string{"/usr/local/bin/packer", "plugin", "packer-provisioner-shell"}
2021/03/30 09:17:39 Waiting for RPC address for: /usr/local/bin/packer
2021/03/30 09:17:39 packer-provisioner-shell plugin: [INFO] Packer version: 1.7.0 [go1.15.8 linux amd64]
2021/03/30 09:17:39 packer-provisioner-shell plugin: [INFO] PACKER_CONFIG env var not set; checking the default config file path
2021/03/30 09:17:39 packer-provisioner-shell plugin: [INFO] PACKER_CONFIG env var set; attempting to open config file: /root/.packerconfig
2021/03/30 09:17:39 packer-provisioner-shell plugin: [WARN] Config file doesn't exist: /root/.packerconfig
2021/03/30 09:17:39 packer-provisioner-shell plugin: [INFO] Setting cache directory: /build/CaaS-HostOS-Node-Template/packer_cache
2021/03/30 09:17:39 packer-provisioner-shell plugin: args: []string{"packer-provisioner-shell"}
2021/03/30 09:17:39 packer-provisioner-shell plugin: Plugin address: unix /tmp/packer-plugin429953284
2021/03/30 09:17:39 Received unix RPC address for /usr/local/bin/packer: addr is /tmp/packer-plugin429953284
2021/03/30 09:17:39 packer-provisioner-shell plugin: Waiting for connection...
2021/03/30 09:17:39 packer-provisioner-shell plugin: Serving a plugin connection...
2021/03/30 09:17:39 Preparing build: vsphere-iso
2021/03/30 09:17:39 ui: vsphere-iso: output will be in this color.
2021/03/30 09:17:39 ui:
2021/03/30 09:17:39 Build debug mode: false
2021/03/30 09:17:39 Force build: false
2021/03/30 09:17:39 On error:
2021/03/30 09:17:39 Waiting on builds to complete...
2021/03/30 09:17:39 Starting build run: vsphere-iso
2021/03/30 09:17:39 Running builder: vsphere-iso
2021/03/30 09:17:39 [INFO] (telemetry) Starting builder vsphere-iso
2021/03/30 09:17:39 packer-builder-vsphere-iso plugin: No URLs were provided to Step Download. Continuing...
2021/03/30 09:17:39 packer-builder-vsphere-iso plugin: No CD files specified. CD disk will not be made.
2021/03/30 09:17:39 ui: ==> vsphere-iso: Creating VM...
2021/03/30 09:17:40 ui: ==> vsphere-iso: Customizing hardware...
2021/03/30 09:17:41 ui: ==> vsphere-iso: Mounting ISO images...
2021/03/30 09:17:41 packer-builder-vsphere-iso plugin: Check if ISO path is a Content Library path
2021/03/30 09:17:42 packer-builder-vsphere-iso plugin: ISO path not identified as a Content Library path
2021/03/30 09:17:42 packer-builder-vsphere-iso plugin: Using [**********] ISOs/ubuntu-20.04.1-legacy-server-amd64.iso as the datastore path
2021/03/30 09:17:42 packer-builder-vsphere-iso plugin: Creating CD-ROM on controller '&{{{} 200 0xc00012f6e0 <nil> <nil> <nil> 0 <nil>} 0 []}' with iso '[UPTD_HX_CL001_VOL1] ISOs/ubuntu-20.04.1-legacy-server-amd64.iso'
2021/03/30 09:17:42 ui: ==> vsphere-iso: Adding configuration parameters...
2021/03/30 09:17:42 ui: ==> vsphere-iso: Creating floppy disk...
2021/03/30 09:17:42 packer-builder-vsphere-iso plugin: Floppy path: /tmp/packer567344566
2021/03/30 09:17:42 packer-builder-vsphere-iso plugin: Initializing block device backed by temporary file
2021/03/30 09:17:42 packer-builder-vsphere-iso plugin: Formatting the block device with a FAT filesystem...
2021/03/30 09:17:42 packer-builder-vsphere-iso plugin: Initializing FAT filesystem on block device
2021/03/30 09:17:42 packer-builder-vsphere-iso plugin: Reading the root directory from the filesystem
2021/03/30 09:17:42 ui:     vsphere-iso: Copying files flatly from floppy_files
2021/03/30 09:17:42 ui:     vsphere-iso: Copying file: ./preseed.cfg
2021/03/30 09:17:42 ui:     vsphere-iso: Done copying files from floppy_files
2021/03/30 09:17:42 ui:     vsphere-iso: Collecting paths from floppy_dirs
2021/03/30 09:17:42 ui:     vsphere-iso: Resulting paths from floppy_dirs : []
2021/03/30 09:17:42 ui:     vsphere-iso: Done copying paths from floppy_dirs
2021/03/30 09:17:42 ui: ==> vsphere-iso: Uploading created floppy image
2021/03/30 09:17:42 packer-builder-vsphere-iso plugin: Deleting floppy disk: /tmp/packer567344566
2021/03/30 09:17:42 ui: ==> vsphere-iso: Destroying VM...
2021/03/30 09:17:43 [INFO] (telemetry) ending vsphere-iso
2021/03/30 09:17:43 ui error: Build 'vsphere-iso' errored after 3 seconds 671 milliseconds: 404 Not Found
2021/03/30 09:17:43 ui:
==> Wait completed after 3 seconds 671 milliseconds
2021/03/30 09:17:43 machine readable: error-count []string{"1"}
2021/03/30 09:17:43 ui error:
==> Some builds didn't complete successfully and had errors:
2021/03/30 09:17:43 machine readable: vsphere-iso,error []string{"404 Not Found"}
2021/03/30 09:17:43 ui error: --> vsphere-iso: 404 Not Found
2021/03/30 09:17:43 ui:
==> Builds finished but no artifacts were created.
2021/03/30 09:17:43 [INFO] (telemetry) Finalizing.
2021/03/30 09:17:43 waiting for all plugin processes to complete...
2021/03/30 09:17:43 /usr/local/bin/packer: plugin process exited
2021/03/30 09:17:43 /usr/local/bin/packer: plugin process exited

**Comment by yiwryos** [comment]
> 
> 
> Can you share the complete logs? It's not clear to me what step the 404 is coming from.


Hello just checking back on this, have the logs provided any additional info?
