### ISSUE TITLE
qemu-system-aarch64: no function defined to set boot device list for this architecture

### ISSUE THREAD

**Issue by ujjwalpatil** [hashicorp/packer#10830]
I have been trying to work with qemu-system-aarch64 to create/generate a qcow, but not able to. All of our workstations are x86_64, and I need to create a image/VM for aarch64 platform. Below are the steps I am going through. 

1. I am using packer (packer-builder-qemu plugin) to create qcow.
2. Idea is, I need to boot VM from minimal ISO (RHEL8.2). I have iso for arm64 rhel-8.2
3. Use kick-start template to install/configure bunch of packages.
6. Using ansible to configure system. 
7. Save this image and use this as VM for our test environment. In test, we also have x86_64 hosts, which are suppose to run the qcow and use it for testing.

Above setup works fine and been in use for years for x86_64 platform. 

After trying multiple things, I am getting error as `qemu-system-aarch64: no function defined to set boot device list for this architecture` 

below is packer.json template and logs for packer run. 

` 
`
{
  "builders": [
    {
      "accelerator": "none",
      "boot_command": [
        "<tab> text ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/rhel8.2-beta-ks.cfg<enter><wait>"
      ],
      "boot_wait": "10s",
      "disk_interface": "virtio",
      "disk_size": "81000",
      "format": "qcow2",
      "host_port_max": "3214",
      "host_port_min": "3214",
      "http_directory": "packer-templates/http",
      "iso_checksum": "sha256:f93548399cd1f6731cccb3098d9717aedb57df2409ee98f06719a4d6e832e4fe",
      "iso_url": "file:///home/builder/rhel-8.2-aarch64-dvd.iso",
      "memory": "4048",
      "net_device": "virtio-net",
      "cdrom_interface": "virtio-scsi",
      "qemu_binary": "/home/builder/qemu-build/qemu-5.2.0/build/qemu-system-aarch64",
      "ssh_password": "tigris",
      "ssh_port": "22",
      "ssh_timeout": "10000s",
      "ssh_username": "root",
      "type": "qemu",
     "qemuargs": [
              [ "-machine", "virt" ],
              [ "-device", "virtio-gpu-pci" ],
              [ "-display", "sdl"],
              [ "-cpu", "cortex-a57"],
              [ "-drive", "if=pflash,format=raw,file=QEMU_EFI.img"],
              [ "-drive", "if=pflash,file=varstore.img"],
              [ "-drive", "if=virtio,file=el8-arm.img"],
              [ "-drive", "if=virtio,format=raw,file=/home/builder/rhel-8.2-aarch64-dvd.iso,id=cdrom0,media=cdrom" ]      
      ],    
      "vnc_bind_address": "0.0.0.0",
      "vnc_port_min": "5901",
      "vnc_port_max": "5901"
    }
  ],
  "provisioners": [
    {
      "scripts": [
        "packer-templates/scripts/redhat/rh-ansible.sh"
      ],
      "type": "shell"
    },
    {
      "command": "ANSIBLE_NOCOLOR=1 PYTHONUNBUFFERED=1 ansible-playbook",
      "playbook_file": "ansible-playbooks/ovs.yml",
      "role_paths": [
        "ansible-playbooks/roles/3rdparty",
        "ansible-playbooks/roles/common",
        "ansible-playbooks/roles/virtualization",
        "ansible-playbooks/roles/vrs",
        "ansible-playbooks/roles/summary"
      ],
      "type": "ansible-local"
    },
    {
      "scripts": [
        "packer-templates/scripts/sync.sh"
      ],
      "type": "shell"
    }
  ]
} 
`
`
I really appreciate if someone can please take a look and advise. 

I have tried to follow instructions in this link and was able to atlest get bootup and installation going manually with qemu-system-aarch64, but not with packer  : http://www.redfelineninja.org.uk/daniel/2018/02/running-an-iso-installer-image-for-arm64-aarch64-using-qemu-and-kvm/ 

Here is the cmd which works (mostly) with-out packer. 
`qemu-system-aarch64 
    -cpu cortex-a53 -M virt -m 4096 -nographic 
    -drive if=pflash,format=raw,file=QEMU_EFI.img 
    -drive if=pflash,file=varstore.img 
    -drive if=virtio,file=el8-arm.img 
    -drive if=virtio,format=raw,file=/home/builder/rhel-8.2-aarch64-dvd.iso`

**Comment by jacob-carlborg** [comment]
You can add `-boot strict=off` as an argument to QEMU to avoid this error. Here's an example of where I've successfully built and image with OpenBSD for ARM64/Aarch64 [1].

[1] https://github.com/cross-platform-actions/openbsd-builder

**Comment by sylviamoss** [comment]
@ujjwalpatil please confirm if the @jacob-carlborg's suggestion is useful to you and answers your question.

**Comment by ujjwalpatil** [comment]
@sylviamoss : I tried using the option suggested `-boot strict=off`. With this option, process is stuck/hanged for hours. Sometimes when it does move, I get error saying No boot device found.  

Please close this issue, as I am not using packer for this project anymore and decided to use vert-install manually.
