### ISSUE TITLE
Azure SharedImageGallery Destination doesn't have a subscription property

### ISSUE THREAD

**Issue by fbinotto** [hashicorp/packer#10831]
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

Azure SharedImageGallery Destination doesn't have a subscription property which block us from using an image from a source SharedImageGallery in subscription A and import it to another SharedImageGallery in subscription B. The documentation https://www.packer.io/docs/builders/azure/arm suggests this is possible.

#### Reproduction Steps

      "shared_image_gallery_destination": {
        "subscription": "{{user `sub_id`}}",
        "resource_group": "{{user `target_shared_image_gallery_rg`}}",
        "gallery_name": "{{user `target_shared_image_gallery_name`}}",
        "image_name": "{{user `target_image_name`}}",
        "image_version": "{{user `target_image_version`}}",
        "replication_regions": [
          "australiaeast"
        ]
      },

### Packer version

1.6.1

### Simplified Packer Buildfile

  "builders": [
    {
      "type": "azure-arm",
      "shared_image_gallery": {
        "subscription": "{{user `sub_id`}}",
        "resource_group": "{{user `source_shared_image_gallery_rg`}}",
        "gallery_name": "{{user `source_shared_image_gallery_name`}}",
        "image_name": "{{user `source_image_name`}}",
        "image_version": "{{user `source_image_version`}}"
      },
      "shared_image_gallery_destination": {
        "resource_group": "{{user `target_shared_image_gallery_rg`}}",
        "gallery_name": "{{user `target_shared_image_gallery_name`}}",
        "image_name": "{{user `target_image_name`}}",
        "image_version": "{{user `target_image_version`}}",
        "replication_regions": [
          "australiaeast"
        ]
      },
      "managed_image_name": "{{user `target_image_name`}}{{user `target_image_version`}}",
      "managed_image_resource_group_name": "{{user `target_shared_image_gallery_rg`}}",
      "location": "australiaeast",
      "vm_size": "Standard_D2_v2",
      "virtual_network_name": "{{user `vnet`}}",
      "virtual_network_subnet_name": "{{user `subnet`}}",
      "virtual_network_resource_group_name": "{{user `vnet_rg`}}",
      "os_type": "Windows",
      "communicator": "winrm",
      "winrm_username": "packer",
      "winrm_use_ssl": true,
      "winrm_insecure": true,
      "winrm_use_ntlm": true,
      "winrm_timeout": "6m"
    }
  ],

### Operating system and Environment details

OS, Architecture, and any other information you can provide about the
environment.

### Log Fragments and crash.log files

Include appropriate log fragments. If the log is longer than a few dozen lines,
please include the URL to the [gist](https://gist.github.com/) of the log or
use the [Github detailed format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d) instead of posting it directly in the issue.

Set the env var `PACKER_LOG=1` for maximum log detail.

**Comment by sylviamoss** [comment]
Hello there! This feature was added on Packer v1.6.3 and you are on v1.6.1. You must update Packer to use it.
