### ISSUE TITLE
Feature Request: Add cleanup_remote_cache_max_age feature to vsphere-iso builder

### ISSUE THREAD

**Issue by jpbuecken** [hashicorp/packer#10842]
Please search the existing issues for relevant feature requests, and use the
reaction feature
(https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
to add upvotes to pre-existing requests.

#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

This issue should be a follow up feature request to https://github.com/hashicorp/packer/issues/9843

After cleanup_remote_cache has been implemented as described in #9843 (which would be sufficient in the first step), 
is it possible to do the cleanup based on a 

`cleanup_remote_cache_max_age`

option?

e.g.
`cleanup_remote_cache=true`
`cleanup_remote_cache_max_age = 5` : Delete all files older than 5 days after successful build (not only the one just touched) 

Maybe special cases should be allowed:
`cleanup_remote_cache_max_age = -1`  : Delete file after successful build (behaviour as described in #9843). Default value.
`cleanup_remote_cache_max_age = 0` : Delete all files after successful build (not only the one just touched) 

Maybe a warning should be added or logic is needed to avoid the following:
Warning: If you use cleanup_remote_cache_max_age>=0 you should not run parallel builds since one packer process may delete files by other running packer processes.
Possible Workaround: Use subfolders in packer_cache depending on vm_name value: You cannot build the same vm_name in parallel anyway.

#### Use Case(s)

Keep the uploaded iso some time to rebuild from it again. But still cleanup if newer iso files for the build has been uploaded.

#### Potential configuration

```
   "builders": [
      {
         "type":                      "vsphere-iso",
          "cleanup_remote_cache": true
          "cleanup_remote_cache_max_age": 5.
          [...]
```

#### Potential References
https://github.com/hashicorp/packer/issues/9843

**Comment by sylviamoss** [comment]
Thank you for opening the issue. My first thought was that a build cleaning up artifacts from other builds doesn't sound good. 
But it is worth thinking through this and we will do it when we get a chance.

**Comment by SwampDragons** [comment]
This definitely feels risky/unexpected/not packer's job to me. #9843 suggests cleaning up only an iso used and uploaded by the builder during that build. This suggests cleaning up anything, which could have unintended consequences.

**Comment by jpbuecken** [comment]
> This definitely feels risky/unexpected/not packer's job to me. #9843 suggests cleaning up only an iso used and uploaded by the builder during that build. This suggests cleaning up anything, which could have unintended consequences.

That is why I suggested subfolder per vm_name in packer_cache, e.g.

packer_cache/${vm_name}/123445.iso

packer_cache/123445.iso/123445.iso

```
   "builders": [
      {
         "type":                      "vsphere-iso",
          "cleanup_remote_cache": true
          "cleanup_remote_cache_max_age": 5
          "vm_name": "123445.iso"
          [...]
```

So you restrict cleanup to your target build VM. Cleanup per target would be more reliable because exactly one packer process can build the same target vm_name.

**Comment by SwampDragons** [comment]
Doing that would potentially cache the same iso many times, if a user is building several different images off one base iso, which would have the opposite of the desired effect for anyone who doesn't know to add this feature to their templates. 

I do understand that this would be a nice optimization, but I'm really not interested in having Packer clean up after other processes.
