### ISSUE TITLE
virtualbox-iso fails with `Unknown option: --nested-hw-virt`

### ISSUE THREAD

**Issue by jaymzh** [hashicorp/packer#10853]
#### Overview of the Issue

packer 1.7 assumes a new option called `--nested-hw-virt` which doesn't exist on VirtualBox 5

#### Reproduction Steps

try to build a vbox VM using packer 1.7 watch it fail:

```
VBoxManage: error: Unknown option: --nested-hw-virt
```

### Packer version

1.7.1

### Simplified Packer Buildfile

The contents literally don't matter, it fails as soon as it tries to create the vm

### Operating system and Environment details

Ubuntu 18.04

### Log Fragments and crash.log files

```
2021/03/31 17:50:10 packer-builder-virtualbox-iso plugin: Executing VBoxManage: []string{"modifyvm", "packer-virtualbox-iso-1617238193", "--nested-hw-virt", "off"}
2021/03/31 17:50:11 packer-builder-virtualbox-iso plugin: stdout:
2021/03/31 17:50:11 packer-builder-virtualbox-iso plugin: stderr: Oracle VM VirtualBox Command Line Management Interface Version 5.2.42_Ubuntu
2021/03/31 17:50:11 packer-builder-virtualbox-iso plugin: (C) 2005-2020 Oracle Corporation
2021/03/31 17:50:11 packer-builder-virtualbox-iso plugin: All rights reserved.
2021/03/31 17:50:11 packer-builder-virtualbox-iso plugin: 
2021/03/31 17:50:11 packer-builder-virtualbox-iso plugin: Usage:
2021/03/31 17:50:11 packer-builder-virtualbox-iso plugin: 
2021/03/31 17:50:11 packer-builder-virtualbox-iso plugin: VBoxManage modifyvm         <uuid|vmname>
...
2021/03/31 17:50:11 packer-builder-virtualbox-iso plugin: VBoxManage: error: Unknown option: --nested-hw-virt
```

**Comment by sylviamoss** [comment]
Thanks for reaching out. We’ll take a look when we get a chance

**Comment by billjh** [comment]
It should be introduced in #10736 

https://github.com/hashicorp/packer/pull/10736/files#diff-7c07d450ded2de1671a031277786b07cb18827c6d9e5b9a0b8a765f4bff66a48R68-R72
