### ISSUE TITLE
`packer --version` prints version to `stderr` even when no error occurs

### ISSUE THREAD

**Issue by comay** [hashicorp/packer#10855]
#### Overview of the Issue

Starting in 1.7.1, running `packer --version` inside a back-grounded process causes both the version and some extraneous output to be printed to `stderr`. This can be reproduced easily under Linux:

```
$ packer --version > stdout 2> stderr
$ cat stdout
1.7.1
$ cat stderr
$
$ packer --version > stdout 2> stderr &
[1]     38160
$
[1] +  Done                    packer --version > stdout 2> stderr &
$ cat stdout
$ cat stderr
 Running in background, not using a TTY
1.7.1
```

In my particular case, I'm running the command as part of a shell script which itself is being run as a back-grounded process. The script sets a variable based on the output of `packer --version` and as a result of the recent change, the Packer version doesn't end up in the variable.

#### Reproduction Steps

See above.

### Packer version

1.7.1

### Operating system and Environment details

Ubuntu Bionic 18.04, AMD64

### Log Fragments and crash.log files

```
2021/03/31 23:48:12 [INFO] Packer version: 1.7.1 [go1.16.2 linux amd64]
2021/03/31 23:48:12 [TRACE] discovering plugins in /usr/bin
2021/03/31 23:48:12 [TRACE] discovering plugins in /home/dcomay/.packer.d/plugins
2021/03/31 23:48:12 [TRACE] discovering plugins in .
2021/03/31 23:48:12 [INFO] PACKER_CONFIG env var not set; checking the default config file path
2021/03/31 23:48:12 [INFO] PACKER_CONFIG env var set; attempting to open config file: /home/dcomay/.packerconfig
2021/03/31 23:48:12 [WARN] Config file doesn't exist: /home/dcomay/.packerconfig
2021/03/31 23:48:12 [INFO] Setting cache directory: /tmp/packer_cache
2021/03/31 23:48:12 [INFO] (telemetry) Finalizing.
 Running in background, not using a TTY
1.7.1
2021/03/31 23:48:13 waiting for all plugin processes to complete...
```

I believe this was introduced via #10766.

**Comment by nywilken** [comment]
Hi there @comay thanks for bubbling this up. We had an issue in the past where critical error information was being swallowed by our log wrapping script, which we fixed but then introduced this issue. Thanks again for reporting. 

We have implemented a fix which will now only bubble up error messaging to Stderr for non-recoverable errors (Packer exits with a non-zero exitcode), keeping all other messaging as it was before. I believe this updated code should fix your issue, but it would make us feel better if you could give the patched binaries a test and let us know if it resolves your issue with no side affects. Thanks!

The patched binaries can be found https://app.circleci.com/pipelines/github/hashicorp/packer/9887/workflows/62f5ae6e-64a5-4340-a21b-c95a35c2b17a/jobs/119177/artifacts

**Comment by comay** [comment]
> The patched binaries can be found https://app.circleci.com/pipelines/github/hashicorp/packer/9887/workflows/62f5ae6e-64a5-4340-a21b-c95a35c2b17a/jobs/119177/artifacts

I've tested the patched binary and it does address this particular issue and I was also able to successfully run through our box building using it. Thanks for the quick turnaround on this.
