### ISSUE TITLE
Implement json_string attribute on chef-client provisioner

### ISSUE THREAD

**Issue by justme1121** [hashicorp/packer#10871]
**Overview of the Issue**

This the same as #10532 except this is for the **chef-client** provisioner instead of chef-solo.

**Packer version**
1.7.1

**Comment by nywilken** [comment]
Thanks for reaching out. We’ll take a look when we get a chance. Going to add this in for the next release since it looks to be a pretty straight forward lift and shift from the chef-solo provisioner.
