### ISSUE TITLE
The -force option does not work when convert_to_template is set to true

### ISSUE THREAD

**Issue by bnfbiz** [hashicorp/packer#10889]
#### Overview of the Issue

When trying to re-run packer with the -force option and the vsphere-cllone (and presumably vsphere-iso I haven't tested it yet) is run and the created image is already a vSphere template it failes with:

--> vsphere-clone.cleanuptest: error destroying DevOps/forcecleanuptest: Invalid virtual machine state.

#### Reproduction Steps

Build a vm usine vsphere-clone (expect same issue with vsphere-iso)
`~/go/bin/packer build -timestamp-ui -force .`

The first one will succed.  Then rebuild without manually deleting the first one
`~/go/bin/packer build -timestamp-ui -force .`

the error occurs:
```text
vsphere-clone.cleanuptest: output will be in this color.

2021-04-07T22:58:10+02:00: ==> vsphere-clone.cleanuptest: the vm/template DevOps/forcecleanuptest already exists, but deleting it due to -force flag
2021-04-07T22:58:10+02:00: Build 'vsphere-clone.cleanuptest' errored after 7 seconds 683 milliseconds: error destroying DevOps/EDaaS_Templates/QA/forcecleanuptest: Invalid virtual machine state.

==> Wait completed after 7 seconds 683 milliseconds

==> Some builds didn't complete successfully and had errors:
--> vsphere-clone.cleanuptest: error destroying DevOps/forcecleanuptest: Invalid virtual machine state.

==> Builds finished but no artifacts were created.
```
### Packer version

v1.7.2

### Simplified Packer Buildfile

If the file is longer than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/) of the log or use the [Github detailed
format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d)
instead of posting it directly in the issue.

### Operating system and Environment details

Target is vSphere

### Log Fragments and crash.log files

as above

**Comment by sylviamoss** [comment]
Hey there, thanks for reaching out. We will take a look when we get a chance.
Until there, could you share a simplified configuration?

**Comment by bnfbiz** [comment]
Here are sample files that I used to do the testing.
[vsphere-clone.pkr.hcl](https://github.com/hashicorp/packer/files/6287119/vsphere-clone.pkr.hcl.txt)
[vsphere-iso.pkr.hcl](https://github.com/hashicorp/packer/files/6287120/vsphere-iso.pkr.hcl.txt)

I created a var.auto.pkvars.hcl file with the variables and then ran the followng command (note that I tested them in different subdirectories so just vsphere-clone and separately vsphere-iso)

`./packer build -timestamp-ui -force .`

The first time it created the vm, the second time it failed since the vm is a template which you need to convert back to a vm before it can be deleted (this is what I have to do in the UI).

I think this is what you were requesting.
