### ISSUE TITLE
Is it possible to create packer script to use existing image?

### ISSUE THREAD

**Issue by mydearmuthu1978** [hashicorp/packer#10897]
I have packer script which creates windows 2019 image with below softwares.
VS 2019, Python, Git, JAVA. 
Along with the above softwares i am installing some additional scripts to create along with the image.
The problem is when there is small change i need to execute the entire script which is taking 6hours to complete the build.
I want to avoid this.
Option1: I will create windows 2019 image with all the basic softwares like VS2019, JAVA and Python.
My packer script should use this base image and run the scripts additionally and recreated new image. 
Is it possible? or please let me know if any other options to resolve this.

**Comment by anderpups** [comment]
Which builder are you using? Some builders allow you to specify an existing image. Example for qemu builder.
https://www.packer.io/docs/builders/qemu#disk_image

**Comment by mydearmuthu1978** [comment]
Please find the builder details below.

 "builders": [
        {
            "type": "azure-arm",
            "subscription_id": "{{user `subscription_id`}}",
            "managed_image_name": "xxx-Win2019Image-{{user `build_number`}}",
            "managed_image_resource_group_name": "xxxxxxxxxxxxxxxxxxx",
            "build_resource_group_name": "xxxxxxxxxxxxxxxxxxxxxxxx",
            "build_key_vault_name": "xxxxxxxxxxx",
            "build_key_vault_sku": "Standard",
            "os_type": "Windows",
            "image_publisher": "MicrosoftWindowsServer",
            "image_offer": "WindowsServer",
            "image_sku": "2019-Datacenter",
            "communicator": "winrm",
            "winrm_use_ssl": "true",
            "winrm_insecure": "true",
            "winrm_timeout": "5m",
            "winrm_username": "packer",
            "vm_size": "Standard_D2_v2",
            "async_resourcegroup_delete": true
        }

**Comment by mydearmuthu1978** [comment]
> Which builder are you using? Some builders allow you to specify an existing image. Example for qemu builder.
> https://www.packer.io/docs/builders/qemu#disk_image

Please find the builder details below.

"builders": [
{
"type": "azure-arm",
"subscription_id": "{{user subscription_id}}",
"managed_image_name": "xxx-Win2019Image-{{user build_number}}",
"managed_image_resource_group_name": "xxxxxxxxxxxxxxxxxxx",
"build_resource_group_name": "xxxxxxxxxxxxxxxxxxxxxxxx",
"build_key_vault_name": "xxxxxxxxxxx",
"build_key_vault_sku": "Standard",
"os_type": "Windows",
"image_publisher": "MicrosoftWindowsServer",
"image_offer": "WindowsServer",
"image_sku": "2019-Datacenter",
"communicator": "winrm",
"winrm_use_ssl": "true",
"winrm_insecure": "true",
"winrm_timeout": "5m",
"winrm_username": "packer",
"vm_size": "Standard_D2_v2",
"async_resourcegroup_delete": true
}

**Comment by anderpups** [comment]
I am not familiar with Azure, but in AWS I would create the AMI and register it. Then have a second packer run that uses that completed registered AMI for any extra stuff needed.

**Comment by dbond007** [comment]
I would think that you would want to use the image you created, adding the additional customisations to that to create a new one (what I do in vmware). Looking at the azure docs, that would probably be the custom_managed_images values. Just start packer using your base image, apply the additional customisations.

**Comment by SwampDragons** [comment]
Yes, this is possible using the custom_managed_image option -- https://www.packer.io/docs/builders/azure/arm#custom_managed_image_name
