### ISSUE TITLE
post-processor does not respect `except` configuration

### ISSUE THREAD

**Issue by ksatirli** [hashicorp/packer#10895]
#### Overview of the Issue

As part of a HCL2 template, I'm running the following post-processor:

```hcl
  post-processor "vagrant-cloud" {
    box_tag             = local.box_tag
    no_release          = var.no_release
    version             = local.box_version
  }
```

I call my Packer build process with `packer build -except=post-processor.vagrant-cloud"` by default, to build the Vagrant image, but to omit pushing to Vagrant Cloud.

When I'm not logged in to Vagrant Cloud, I get an error indicating that I am not logged in to Vagrant Cloud (this is intentional in this case):

> * Failed to verify authentication token: 401 Unauthorized

I've tried the following variations for the `except` part:

* `'post-processor.vagrant-cloud'`
* `'*post-processor.vagrant-cloud'`
* `'*.post-processor.vagrant-cloud'`
* `*vagrant-cloud`
* `*.vagrant-cloud`
* `*.build.post-processor.vagrant-cloud`

#### Reproduction Steps

Steps to reproduce this issue

Create a HCL2 image with the Vagrant Cloud Processor

Run `packer build -except="'*.build.post-processor.vagrant-cloud'" image.pkr.hcl` when _not_ logged in to Vagrant Cloud

### Packer version

* `1.7.1` 
* `1.7.2`

### Simplified Packer Buildfile

If the file is longer than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/) of the log or use the [Github detailed
format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d)
instead of posting it directly in the issue.

### Operating system and Environment details

macOS `10.15.7`

### Log Fragments and crash.log files

Running this with `PACKER_LOG=1` confirms that the post-processor gets kicked off, regardless of the `except` statement:

```
2021/04/09 12:09:32 packer-post-processor-vagrant-cloud plugin: Waiting for connection...
2021/04/09 12:09:32 packer-post-processor-vagrant-cloud plugin: Serving a plugin connection...
2021/04/09 12:09:32 packer-post-processor-vagrant-cloud plugin: Post-Processor Vagrant Cloud API GET: https://vagrantcloud.com/api/v1/authenticate
2021/04/09 12:09:33 packer-post-processor-vagrant-cloud plugin: Post-Processor Vagrant Cloud API Response:
```

**Comment by SwampDragons** [comment]
Hi, `packer build --except="vagrant-cloud" test_pp_names.pkr.hcl` works for me. 

Looks like we could use a learn tutorial with an example template that shows all different kinds of globbing and references

I will note that the cli "only" option doesn't apply to post-processors. This is intentional but should probably be better documented. The subtle differences between the in-template only/except and cli only-except can be tricky and we should have better docs and examples.

**Comment by ksatirli** [comment]
Can confirm that this worked with just `vagrant-cloud` - thank you @SwampDragons!
