### ISSUE TITLE
Help with unmaintained community provisioner plugins

### ISSUE THREAD

**Issue by nywilken** [hashicorp/packer#10901]
Hello Packer Community,

For some time, the best practice amongst Packer users has been to use `shell` and `shell-local` provisioners to execute Chef, Salt and Puppet, but due to early first-class integrations we have maintained the plugins below for over four years. The Packer team is currently supportive of 3rd parties maintaining first-class plugins for these, but in absence of that recommends the more common approach of installing and running these tools are via the shell or shell-local provisioners.

We are reaching out today to inform you that the following popular community plugins are [unmaintained](https://github.com/hashicorp/packer/blob/master/README.md#unmaintained-plugins):

- [chef-client](https://packer.io/docs/provisioners/chef-client)
- [chef-solo](https://packer.io/docs/provisioners/chef-solo)
- [puppet-masterless](https://packer.io/docs/provisioners/puppet-masterless)
- [puppet-server](https://packer.io/docs/provisioners/puppet-server)
- [salt-masterless](https://packer.io/docs/provisioners/salt-masterless)

Unmaintained plugins are no longer under active development and are only being updated by the Packer team on a best effort basis. 

In the v1.8.0 release of Packer, we will be extracting all non-core plugins currently bundled with Packer to improve the overall user experience of installing and working with third-party plugins. An issue that is being tracked in  [hashicorp/packer#8610](https://github.com/hashicorp/packer/issues/8610). 

During the extraction any plugin that is found to be unmaintained will be [archived](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/archiving-a-github-repository) to let users know that the plugin is no longer being maintained.

We understand that these plugins may be critical to existing user workflows so we are seeking maintainers who can continue developing and releasing these plugins. If you are interested in maintaining one or more of the plugins listed above please reach out to us at packer@hashicorp.com.

### FAQs

1. **What are the responsibilities in maintaining a community plugin?**

Community plugins are made available by the community, for the community to be used with Packer. By maintaining a plugin, you will be responsible for the development, release, and ongoing support of the plugin. 
The responsibilities of development include:
         1. Assisting with the migration of the plugin code base, and git history, into a GitHub repository under your respective organization (e.g github.com/<orgname>/packer-plugin-<name>).
         1. Updating the code base to work with new versions of Packer.
         1. Reviewing issues and pull-requests opened against the plugin repository in a timely manner.
         1. Releasing new versions of the plugin binary that are compatible with Packer - See [Creating a Release](https://www.packer.io/docs/plugins/creation#creating-a-github-release) for more details.

2. **How do I as a new plugin maintainer gain access to the code base?**

The Packer team will provide a document, along with the accompanying script(s) for extracting a community plugin (with all relevant Git history) out of hashicorp/packer into a new GitHub repository. If necessary there may be an intermediate step where a plugin is extracted into a repository under the HashiCorp GitHub organization, and then transferred to the new repository. 

Due to GitHub permission issues, the transferring of issues will need to be done separately. 

3. **What happens to an active plugin that is no longer being maintained?**

Plugins that are not actively maintained will be marked as unmaintained on their respective documentation pages, and scheduled for archival. We will try to find a new owner. If no owner can be found then HashiCorp will follow the process for archiving a plugin that has no owner.

4. **What does it mean for a plugin to be archived?**

A plugin that does not have an owner will be broken out into its own repository under the HashiCorp GitHub organization. The new repository will then be [archived](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/archiving-a-github-repository) to let users know that the plugin is no longer being maintained. Upon the initial breakout, a final compatible release of the plugin will be made, but it will not be actively maintained or monitored for new issues. Critical security-related issues will be reviewed and addressed where possible.

**Comment by arizvisa** [comment]
https://github.com/packer-community/winrmcp/issues is pretty relevant too, there's a number of PRs that improve performance but have been left hanging due to being unmaintained.

**Comment by nywilken** [comment]
> https://github.com/packer-community/winrmcp/issues is pretty relevant too, there's a number of PRs that improve performance in winrm but have been left hanging due to being unmaintained. So it's not just provisioner plugins, some core modules too.

I've created an issue internally to see how we can help out with this repo. Thanks for bubbling it up.

**Comment by nywilken** [comment]
The plugins listed here have been archived. More details on what this means for practitioners can be found on the [Plans to Archive Unmaintained Packer Provisioner Plugins](https://www.hashicorp.com/blog/plans-to-archive-unmaintained-packer-provisioner-plugins) blog post.

Archiving is reversible if a new maintainer steps forward. If you are interested in maintaining an archived plugin, please reach out to us at packer@hashicorp.com.
