### ISSUE TITLE
Openstack builder doesn't support Openstack API Microversion

### ISSUE THREAD

**Issue by ArKam** [hashicorp/packer#10906]
#### Overview of the Issue

When trying to launch a new image build using block storage volume feature, the build fail.

It come from the fact that the instance created will be attached on a volume type (the default one) that use multi-attach feature, packer fail to launch the VM as there is no way to specify the nova API microversion (min 2.60).

Even using environment variables such as OS_COMPUTE_API_VERSION=2.79 or a local clouds.yaml file doesn't work.

The targeted Openstack platform DO SUPPORT nova api microversion 2.79.
The targeted Openstack platform DO WORK as intended as we have a bunch of ansible playbooks that use it and that need to get this microversion specified within either an environment variable or within the system-wide or local clouds.yaml file.

#### Reproduction Steps

Create a packer template using Openstack builder and the `use_blockstorage_volume` directive.
Have your default `__DEFAULT__` openstack volume type to use multi-attach feature.
launch the build.
The build fail with the following message:

`==> openstack: Error launching source server: Bad request with: [POST https://sub.domain.tld:8774/v2.1/servers], error message: {"badRequest": {"message": "Multiattach volumes are only supported starting with compute API version 2.60.", "code": 400}}`

### Packer version

Packer v1.5.6

### Simplified Packer Buildfile

https://gist.github.com/ArKam/275ecfb0cfbb43cbdf447bcd9a6696f0

### Operating system and Environment details

OS: CentOS Linux release 7.9.2009 (Core).

### Log Fragments and crash.log files

https://gist.github.com/ArKam/71d075c6faa08415cf39c85970d2e5ad

**Comment by nywilken** [comment]
Hi @ArKam I see you are using version 1.5.6 of Packer. There have been a number for fixes to the OpenStack builder since then. 

Have you tried running your build with the latest release of Packer v1.7.2?

**Comment by ArKam** [comment]
I'll try to use it and give you an update, please do not close this ticket until then as I may have to wait for almost 2 weeks before being able to do so.

Thanks a lot for your reply!
