### ISSUE TITLE
custom nic and diskname in Azure ARM

### ISSUE THREAD

**Issue by AHuusom** [hashicorp/packer#10909]
Give us the option to specify our own nic and disk names when building ARM templates.

This is a blocker when they are randomized as some are using naming-convention with Azure policies denying build of incompatible names.

And I cannot run the packer build again on the same Azure VM to continue a failed provisioning.

So if it fails after 3 hours of installing software, I cannot continue, but i have to start from scratch... this is not very idempotent.

**Comment by nywilken** [comment]
Thanks for reaching out. I don't know if we will be able to get to this soon. But you may be able to add this functionality the same way we are handling the TempComputeName if you are interested in opening up a PR. https://github.com/hashicorp/packer/blob/16658a9f47c79a07d9984a6030209725f9893a61/builder/azure/arm/config.go#L304

**Comment by AHuusom** [comment]
Hi @nywilken I tried to create a PR [/pull/10938] but as i'm not familiar with the Go language, one of your checks "check-generate" is not very happy and I don't know how to fix this.

**Comment by anujkmaurya** [comment]
hi @nywilken, I want to contribute to the packer. Is this issue fixed?

**Comment by SwampDragons** [comment]
A PR for this issue has been merged, so it will be fixed in the next release.
