### ISSUE TITLE
packer hcl2_upgrade has issues with split function in a string

### ISSUE THREAD

**Issue by TJM** [hashicorp/packer#10911]
#### Overview of the Issue

Using the "split" function in a string seems to trip up the hcl2_upgrade parser.... additionally it says it was successful, even though it failed :(.

#### Reproduction Steps

I ran `packer hcl2_upgrade enterprise-linux.json` and it said:

```
Successfully created enterprise-linux.json.pkr.hcl 
```

... however it was not successful, it failed to convert a section with a "split" function in it.

Use "split" in a string... (contrived example)

```json
    "provisioners": [
        {
            "scripts": [
                "echo {{ split build_type \"-\" 0 }}"
            ],
            "type": "shell"
        }
    ]
```

The resulting HCL file section looks like:

```hcl
  # could not parse template for following block: "template: hcl2_upgrade:2: unexpected \"\\\\\" in operand"
  provisioner "shell" {
    scripts = ["echo {{ split build_type \"-\" 0 }}"]
  }
```

### Packer version

From `packer version`

```
Packer v1.7.2
```

### Simplified Packer Buildfile

```json
    "provisioners": [
        {
            "scripts": [
                "echo {{ split build_type \"-\" 0 }}"
            ],
            "type": "shell"
        }
    ]
```

### Operating system and Environment details

OSX 10.14.6 x86_64 (likely not relevant)

### Log Fragments and crash.log files

```
[tmcneely@local packer-templates] $ PACKER_LOG=1 packer hcl2_upgrade enterprise-linux.json
2021/04/15 12:52:56 [INFO] Packer version: 1.7.2 [go1.16.3 darwin amd64]
2021/04/15 12:52:56 [TRACE] discovering plugins in /usr/local/bin
2021/04/15 12:52:56 [TRACE] discovering plugins in /Users/tmcneely/.packer.d/plugins
2021/04/15 12:52:56 [DEBUG] Discovered plugin: artifactory = /Users/tmcneely/.packer.d/plugins/packer-post-processor-artifactory
2021/04/15 12:52:56 using external post-processors [artifactory]
2021/04/15 12:52:56 [TRACE] discovering plugins in .
2021/04/15 12:52:56 [INFO] PACKER_CONFIG env var not set; checking the default config file path
2021/04/15 12:52:56 [INFO] PACKER_CONFIG env var set; attempting to open config file: /Users/tmcneely/.packerconfig
2021/04/15 12:52:56 [INFO] Setting cache directory: /Users/tmcneely/Projects/LinuxImages/packer-templates/packer_cache
2021/04/15 12:52:56 [INFO] (telemetry) Finalizing.
Successfully created enterprise-linux.json.pkr.hcl 
2021/04/15 12:52:57 waiting for all plugin processes to complete...
[tmcneely@local packer-templates] $ 
```

REF: https://www.packer.io/docs/templates/legacy_json_templates/engine#split-function-format-reference

**Comment by nywilken** [comment]
Hi @TJM thanks for reaching out. The Go templating conversion from JSON to HCL2 is a work in progress. Packer will try its best to convert the JSON template. If it is unable to do so Packer will add comments indicating that it failed to parse one or more blocks. 

In the future, if there is a block that we can not convert  I think having a warning outputted to the console could be helpful.

**Comment by TJM** [comment]
@nywilken Sure, I was just reporting the issue(s).

**Comment by sylviamoss** [comment]
The double quotes parsing is fixable but you still will get an error message to upgrade manually the split function because is not something the hcl2_upgrade can upgrade. Anyways, I fixed the parsing error. 

The new error message will be: 
```
  # Please manually upgrade to `split(separator, string)`
  # Visit https://www.packer.io/docs/templates/hcl_templates/functions/string/split for more infos.
```
