### ISSUE TITLE
Custom cd_files iso not removed from datastore after build using vsphere-iso builder

### ISSUE THREAD

**Issue by tleepa** [hashicorp/packer#10914]
#### Overview of the Issue

I am building RHEL8 template using vsphere-iso builder, providing kickstart file via `cd_files` option.
Everything builds fine, but the temporary (kickstart) iso file is not being removed from the datastore.
Looking at the logs I can see kickstart iso file being removed from local (packer) /tmp/ directory, but it seems it does not even try to delete the datastore copy.

![ksnip_20210416-115100](https://user-images.githubusercontent.com/7734919/115007208-09254b00-9eaa-11eb-81b9-d7fc8de2c9b7.png)

#### Reproduction Steps

Build template using vsphere-iso builder and kickstart provided via `cd_files` option.

### Packer version

```shell
# packer version
Packer v1.6.6
```

### Simplified Packer Buildfile

[packer template](https://gist.github.com/tleepa/6023740f7678248445c6aaa050880a2c)

### Operating system and Environment details

Packer build process is executed in the docker container, running on CentOS 7 x86-64 host.

```shell
# cat /etc/centos-release
CentOS Linux release 7.9.2009 (Core)

# docker --version
Docker version 20.10.6, build 370c289
```

OS version of docker container:

```shell
# cat /etc/centos-release
CentOS Linux release 8.3.2011
```

### Log Fragments and crash.log files

Relevant part of the log:

```log
==> vsphere-iso: Shutting down VM...
2021/04/16 07:33:43 packer-builder-vsphere-iso plugin: Waiting max 5m0s for shutdown to complete
==> vsphere-iso: Deleting Floppy drives...
==> vsphere-iso: Eject CD-ROM drives...
==> vsphere-iso: Deleting CD-ROM drives...
==> vsphere-iso: Convert VM into template...
==> vsphere-iso: Clear boot order...
2021/04/16 07:33:58 packer-builder-vsphere-iso plugin: Deleting CD disk: /tmp/packer663790441.iso
2021/04/16 07:33:58 [INFO] (telemetry) ending vsphere-iso
==> Wait completed after 7 minutes 32 seconds
==> Builds finished. The artifacts of successful builds are:
2021/04/16 07:33:58 machine readable: vsphere-iso,artifact-count []string{"1"}
Build 'vsphere-iso' finished after 7 minutes 32 seconds.

==> Wait completed after 7 minutes 32 seconds

==> Builds finished. The artifacts of successful builds are:
2021/04/16 07:33:58 machine readable: vsphere-iso,artifact []string{"0", "builder-id", "jetbrains.vsphere"}
2021/04/16 07:33:58 machine readable: vsphere-iso,artifact []string{"0", "id", "RHEL8"}
2021/04/16 07:33:58 machine readable: vsphere-iso,artifact []string{"0", "string", "RHEL8"}
--> vsphere-iso: RHEL8
2021/04/16 07:33:58 machine readable: vsphere-iso,artifact []string{"0", "files-count", "0"}
2021/04/16 07:33:58 machine readable: vsphere-iso,artifact []string{"0", "end"}
2021/04/16 07:33:58 [INFO] (telemetry) Finalizing.
2021/04/16 07:33:58 waiting for all plugin processes to complete...
2021/04/16 07:33:58 /usr/bin/packer: plugin process exited
2021/04/16 07:33:58 /usr/bin/packer: plugin process exited
2021/04/16 07:33:58 /usr/bin/packer: plugin process exited
```

[full log](https://gist.github.com/tleepa/710e2882b36b9de9b163f860ab0c6a02)

### Note

Template and log file redacted for brevity and some sensitive data removed.

**Comment by sylviamoss** [comment]
Hey there, thanks for reaching out. We will take a look when we have a chance. 
Our hashibot will move this issue to the new [packer-plugin-vsphere](https://github.com/hashicorp/packer-plugin-vsphere) repository.
