### ISSUE TITLE
Suggestion on "Deprecation warning" is misleading

### ISSUE THREAD

**Issue by rkosegi** [hashicorp/packer#10926]
#### Overview of the Issue

This is very minor problem, suggestion given by deprecation warning is misleading.

We are using HCL templates for build. When deprecated construct is encountered, packer prints following info

```
 (docker-tag): Deprecation warning: "tag" option has been replaced with "tags". In future versions of Packer, this configuration may not work. Please call `packer fix` on your template to update.
```

This led me run `packer fix ....` which produced confusing error

```
packer fix template.pkr.hcl
Error parsing template: invalid character 'v' looking for beginning of value
```
Apparently `packer fix` operates on JSON templates only, so suggestion **Please call `packer fix` on your template to update.** should be avoided when HCL format is used.

#### Reproduction Steps

Use deprecated construct in HCL template, such as `tag` in `docker-tag` post-processor.
Here is an example:

```hcl
post-processors {
    post-processor "docker-tag" {
      repository = "registry/cool-image"
      tags = [
        "${var.image_version}"
      ]
    }
  }
```

Steps to reproduce this issue

### Packer version

`Packer v1.7.2`

### Simplified Packer Buildfile

```hcl
source "docker" "img" {
  image = "busybox:latest"
  commit = true
}

build {
  name = "img"

  sources = [
    "sources.docker.img"
  ]

  post-processors {
    post-processor "docker-tag" {
      repository = "somerepo/someimage"
      tag = [
        "1.0"
      ]
    }
  }
}
```

### Operating system and Environment details

OS: Fedora 33 amd64

### Log Fragments and crash.log files

Relevant log is part of summary above

**Comment by SwampDragons** [comment]
Good catch, thanks! We'll update the warning.
