### ISSUE TITLE
Push docker image to ECR public gallery

### ISSUE THREAD

**Issue by Laakso** [hashicorp/packer#10948]
#### Description

Since AWS released their [public container registry](https://aws.amazon.com/blogs/aws/amazon-ecr-public-a-new-public-container-registry/) it would be nice that the packer image would be pushed there as well.

#### Use Case(s)

Push packer container image to ECR public container registry.

**Comment by SwampDragons** [comment]
Good idea! This is not something we're likely to get to soon, but PRs are always welcome over on the Docker plugin repo: https://github.com/hashicorp/packer-plugin-docker
