### ISSUE TITLE
Shutdown as final packer step

### ISSUE THREAD

**Issue by gargamelss** [hashicorp/packer#10940]
Due to lags on azure and bug in ver. 1.7.2 with incorrectly clearing network resources, we want to shutdown VM manually as the last step of building the image.

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out. 

Which bug  in v1.7.2 is blocking you?

This is a nice idea, but it may be a while before the Packer team can get to it -- hopefully we can resolve the underlying regression so you don't need this anymore.
