### ISSUE TITLE
packer fix

### ISSUE THREAD

**Issue by benlumia007** [hashicorp/packer#10954]
do we need to a `packer fix old.json > new.json` every time when there's a new version of packer.

**Comment by SwampDragons** [comment]
If you've skipped a lot of versions or gone up a minor version number (like 1.6.x to 1.7.x), the answer is "you probably need to". If you're just incrementing a patch, then you're probably okay not to.

`packer fix` won't hurt if it isn't necessary. Running Packer against an old template without calling `packer fix` will just throw an error, generally about a key not existing.  It's also always possible to just manually update your template, but `packer fix` is more convenient.
