### ISSUE TITLE
Build 'azure-arm' errored after XX minutes YY seconds: unexpected EOF

### ISSUE THREAD

**Issue by rhb84** [hashicorp/packer#10964]
Hi:

 Overview of the Issue:
When trying to build Azure windows VM image it throws `Build 'azure-arm' errored after <time>: unexpected EOF`
on long running provisioners.

I'm building a Windows VMs using centos7 build VM in Azure.
Every time I'm trying to build windows2016 VM it errors out after  many minutes or more than na hour into running the long running process, in my case windows patching.

I have faced the issue with [windows-updates plugin](https://github.com/rgl/packer-plugin-windows-update) and ansible built-in provisioner with playbook to install all available patches for a given windows using `ansible.windows.win_updates`. 
In both cases the same errors are visible in  logs / outputs when trying to build the image.

Steps to reproduce this issue:
creage a  VM  using windows 2016 Azure shared image using packer.
setup a long running provisioner [windows updates plugin](https://github.com/rgl/packer-plugin-windows-update) or patching with ansible.

Outputs from my last try (using ansible)

packer [build output](https://gist.github.com/rhb84/9c8b3eedf3e637b7155e179e860b6f6a)
packer [log file](https://gist.github.com/rhb84/370693cd46a07eae5a09fd0eb8f05204)
build file [windows2016](https://gist.github.com/rhb84/4406abd69f8d32650fb5f65e4ef1a268) 
(removed some of the inline powershell code, basically configure few details and do a sysprep, never gets to this point)
I can see exactly the same azure-rm related errors when using the packer windows update plugin.

Operating system and Environment details:
build VM: centos7
Image I'm trying to build Windows 2016.
Azure, eastus region, both VMs are in the same subscription and subnet.

Packer version:
Packer v1.7.2

I have also tried few random older versions same issue.

Thank you.

**Comment by vanmash** [comment]
I see this error with

`skip_create_image = true`
