### ISSUE TITLE
[feature] build image with "run-command" api only

### ISSUE THREAD

**Issue by ozbillwang** [hashicorp/packer#10983]
Please search the existing issues for relevant feature requests, and use the
reaction feature
(https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
to add upvotes to pre-existing requests.

#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

Our environment doesn't allow Public IP to be assigned to the VM (Azure) and ec2 (AWS). So when build image, it stopped at ssh 

```
==> azure-arm: Timeout waiting for SSH.
```

#### Use Case(s)

I need a way to build Images via `run-command`.

Azure run-command:

https://docs.microsoft.com/en-us/cli/azure/vm/run-command?view=azure-cli-latest

AWS system manager run-command:
https://docs.aws.amazon.com/systems-manager/latest/userguide/execute-remote-commands.html

They all have matched API or SDK for it.

So I need a packer feature to install the OS patch, applications via `run-command` only, more than ssh to that box directly. 

#### Potential configuration

```
"run-command": true
```

#### Potential References

https://docs.microsoft.com/en-us/cli/azure/vm/run-command?view=azure-cli-latest

https://docs.aws.amazon.com/systems-manager/latest/userguide/execute-remote-commands.html

**Comment by jeremymcgee73** [comment]
You can use SSM Session Manager to connect without a public IP on AWS, or just run packer inside of a VPC.

https://www.packer.io/docs/builders/amazon/ebs

**Comment by ozbillwang** [comment]
Finally I adjusted the pipeline, and run the build in private subnet in same VPC to avoid the SSH issue.
