### ISSUE TITLE
HCL examples in virtualbox-ovf docs need updating 

### ISSUE THREAD

**Issue by timblaktu** [hashicorp/packer#10991]
Specifically, I see [here, in the example about adding a description through export options](https://www.packer.io/docs/builders/virtualbox/ovf#export-configuration) the HCL example uses the old style variable reference:

```
"{{user `vm_description`}}"
```

which created an error for me initially when I copied and pasted it into my HCL project. This reference should look like this:

```
"${var.vm_description}"
```

There may be other issues with  this documentation page, I just wanted to call out the one I tripped up on yesterday.

**Comment by sylviamoss** [comment]
Hey there, thanks for catching this. I'd be happy to review and merge a PR with the docs fix if you'd like to do it. The Virtualbox docs are now in https://github.com/hashicorp/packer-plugin-virtualbox
