### ISSUE TITLE
Secrets Manager inline not working for Vspehere-clone builder

### ISSUE THREAD

**Issue by iasllanih** [hashicorp/packer#11003]
#### Overview of the Issue
Trying to use inline function for aws_secretsmanager to retrieve password for vcenter and winrm user. Neither seem to be working - getting error that the passwords are incorrect. 
Not sure if this is related to syntax as documentation seems to only include format for HCL files (I am using JSON and cant find a relevant example.)

Tried the passwords hardcoded and its working fine. Using sts token for login and I can retrieve the secrets via AWS CLI
Hardcoded only vcenter credentials and got past that, but winrm fails.

I guess my question is whether there is a syntax issue, or compatibility issue with vsphere clone builder

#### Reproduction Steps

Steps to reproduce this issue
Run with providers and with hardcoded passwords
### Packer version
1.7.2

### Simplified Packer Buildfile
"builders": [
    {
      "type": "vsphere-clone",
      "convert_to_template": true,
      "template": "Win2019-GUI-Q3-2020-v1.0",
      "CPUs": 4,
      "RAM": 8192,
      "disk_size": 112640, 
      "communicator": "winrm",
      "datastore": "***********",
      "host": "***********",
      "cluster": "***********",
      "insecure_connection": "true",
      "password": "aws_secretsmanager('image_factory_vcenter_service_codebuild_password', 'password')",    
      "username": "service-codebuild",
      "vcenter_server": "***********",
      "resource_pool": "***********",
      "vm_name": "packer-windows-test",
      "winrm_password": "aws_secretsmanager('image_factory_on_prem_winrm_password', 'password')",
      "winrm_username": "administrator"
    }
  ],
### Operating system and Environment details

OS, Architecture, and any other information you can provide about the
environment.

Linux Ubuntu amd64

### Log Fragments and crash.log files
`packer build -debug -force vmware_test.json
2021/05/07 15:01:25 [INFO] Packer version: 1.7.2 [go1.16.3 linux amd64]
2021/05/07 15:01:25 [TRACE] discovering plugins in /usr/bin
2021/05/07 15:01:25 [TRACE] discovering plugins in /home/iasllani/.packer.d/plugins
2021/05/07 15:01:25 [TRACE] discovering plugins in .
2021/05/07 15:01:25 [INFO] PACKER_CONFIG env var not set; checking the default config file path
2021/05/07 15:01:25 [INFO] PACKER_CONFIG env var set; attempting to open config file: /home/iasllani/.packerconfig
2021/05/07 15:01:25 [WARN] Config file doesn't exist: /home/iasllani/.packerconfig
2021/05/07 15:01:25 [INFO] Setting cache directory: /mnt/c/dev/packer/image_creation/packer_cache
e: Running in background, not using a TTY
2021/05/07 15:01:25 [TRACE] Starting internal plugin packer-builder-vsphere-clone
2021/05/07 15:01:25 Starting plugin: /usr/bin/packer []string{"/usr/bin/packer", "plugin", "packer-builder-vsphere-clone"}
2021/05/07 15:01:25 Waiting for RPC address for: /usr/bin/packer
2021/05/07 15:01:25 packer-builder-vsphere-clone plugin: [INFO] Packer version: 1.7.2 [go1.16.3 linux amd64]
2021/05/07 15:01:25 packer-builder-vsphere-clone plugin: [INFO] PACKER_CONFIG env var not set; checking the default config file path
2021/05/07 15:01:25 packer-builder-vsphere-clone plugin: [INFO] PACKER_CONFIG env var set; attempting to open config file: /home/iasllani/.packerconfig
2021/05/07 15:01:25 packer-builder-vsphere-clone plugin: [WARN] Config file doesn't exist: /home/iasllani/.packerconfig
2021/05/07 15:01:25 packer-builder-vsphere-clone plugin: [INFO] Setting cache directory: /mnt/c/dev/packer/image_creation/packer_cache
2021/05/07 15:01:25 packer-builder-vsphere-clone plugin: args: []string{"packer-builder-vsphere-clone"}
2021/05/07 15:01:25 packer-builder-vsphere-clone plugin: Plugin address: unix /tmp/packer-plugin849747111
2021/05/07 15:01:25 Received unix RPC address for /usr/bin/packer: addr is /tmp/packer-plugin849747111
2021/05/07 15:01:25 packer-builder-vsphere-clone plugin: Waiting for connection...
2021/05/07 15:01:25 packer-builder-vsphere-clone plugin: Serving a plugin connection...
2021/05/07 15:01:25 [TRACE] Starting internal plugin packer-provisioner-ansible
2021/05/07 15:01:25 Starting plugin: /usr/bin/packer []string{"/usr/bin/packer", "plugin", "packer-provisioner-ansible"}
2021/05/07 15:01:25 Waiting for RPC address for: /usr/bin/packer
2021/05/07 15:01:25 packer-provisioner-ansible plugin: [INFO] Packer version: 1.7.2 [go1.16.3 linux amd64]
2021/05/07 15:01:25 packer-provisioner-ansible plugin: [INFO] PACKER_CONFIG env var not set; checking the default config file path
2021/05/07 15:01:25 packer-provisioner-ansible plugin: [INFO] PACKER_CONFIG env var set; attempting to open config file: /home/iasllani/.packerconfig
2021/05/07 15:01:25 packer-provisioner-ansible plugin: [WARN] Config file doesn't exist: /home/iasllani/.packerconfig
2021/05/07 15:01:25 packer-provisioner-ansible plugin: [INFO] Setting cache directory: /mnt/c/dev/packer/image_creation/packer_cache
2021/05/07 15:01:25 packer-provisioner-ansible plugin: args: []string{"packer-provisioner-ansible"}
2021/05/07 15:01:25 packer-provisioner-ansible plugin: Plugin address: unix /tmp/packer-plugin112236043
2021/05/07 15:01:25 packer-provisioner-ansible plugin: Waiting for connection...
2021/05/07 15:01:25 Received unix RPC address for /usr/bin/packer: addr is /tmp/packer-plugin112236043
2021/05/07 15:01:25 packer-provisioner-ansible plugin: Serving a plugin connection...
2021/05/07 15:01:25 Preparing build: vsphere-clone
2021/05/07 15:01:26 packer-provisioner-ansible plugin: ansible-playbook version: 2.9.13
2021/05/07 15:01:26 Build debug mode: true
2021/05/07 15:01:26 Force build: true
Debug mode enabled. Builds will not be parallelized.
2021/05/07 15:01:26 On error:
vsphere-clone: output will be in this color.
2021/05/07 15:01:26 Debug enabled, so waiting for build to finish: vsphere-clone

2021/05/07 15:01:26 Starting build run: vsphere-clone
2021/05/07 15:01:26 Running builder: vsphere-clone
2021/05/07 15:01:26 [INFO] (telemetry) Starting builder vsphere-clone
2021/05/07 15:01:31 [INFO] (telemetry) ending vsphere-clone
2021/05/07 15:01:31 Waiting on builds to complete...
==> Wait completed after 5 seconds 155 milliseconds
Build 'vsphere-clone' errored after 5 seconds 155 milliseconds: ServerFaultCode: Cannot complete login due to an incorrect user name or password.
2021/05/07 15:01:31 machine readable: error-count []string{"1"}

==> Some builds didn't complete successfully and had errors:
==> Wait completed after 5 seconds 155 milliseconds
2021/05/07 15:01:31 machine readable: vsphere-clone,error []string{"ServerFaultCode: Cannot complete login due to an incorrect user name or password."}

==> Builds finished but no artifacts were created.
==> Some builds didn't complete successfully and had errors:
2021/05/07 15:01:31 [INFO] (telemetry) Finalizing.
--> vsphere-clone: ServerFaultCode: Cannot complete login due to an incorrect user name or password.

==> Builds finished but no artifacts were created.
2021/05/07 15:01:31 waiting for all plugin processes to complete...
2021/05/07 15:01:31 /usr/bin/packer: plugin process exited
2021/05/07 15:01:31 /usr/bin/packer: plugin process exited`

**Comment by sylviamoss** [comment]
Hey there! You're not using the function correctly. See the docs here https://www.packer.io/docs/templates/legacy_json_templates/user-variables#aws-secrets-manager-variables

Fixing your template will be: 
```json
"builders": [
    {
      "type": "vsphere-clone",
      "convert_to_template": true,
      "template": "Win2019-GUI-Q3-2020-v1.0",
      "CPUs": 4,
      "RAM": 8192,
      "disk_size": 112640, 
      "communicator": "winrm",
      "datastore": "***********",
      "host": "***********",
      "cluster": "***********",
      "insecure_connection": "true",
      "password": "{{ aws_secretsmanager `image_factory_vcenter_service_codebuild_password` `password` }}",    
      "username": "service-codebuild",
      "vcenter_server": "***********",
      "resource_pool": "***********",
      "vm_name": "packer-windows-test",
      "winrm_password": "{{ aws_secretsmanager `image_factory_on_prem_winrm_password` `password` }}",
      "winrm_username": "administrator"
    }
  ],
```

The way you're using is valid for HCL2 templates: https://www.packer.io/docs/templates/hcl_templates/functions/contextual/aws_secretsmanager
