### ISSUE TITLE
Variables provided on command line do not override template variables

### ISSUE THREAD

**Issue by Borkason** [hashicorp/packer#11007]
Same as https://github.com/hashicorp/packer/issues/7049. This was never fixed, because unfortunately the issue was closed by the reporter.

His workaround was to remove the single quotes, and this works, but the documentation still uses single quotes and it remains unclear whether this is a bug or a documentation oversight.

 https://www.packer.io/guides/hcl/variables#command-line-flags

![image](https://user-images.githubusercontent.com/2971735/117684900-b8a5c280-b1b5-11eb-953a-5d6a8af3b349.png)

**Comment by SwampDragons** [comment]
This must be dependent on the shell you're using. I'm on zsh and this works as expected. I can update to double quotes, which works on my machine also.
