### ISSUE TITLE
packer does not recognize "qemu_img_args".

### ISSUE THREAD

**Issue by odra** [hashicorp/packer#11019]
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

I added the following "qemu_img_args" property in my hcl source config:

```
source "qemu" "myname" {
  qemu_img_args = {
    "resize" = "--shrink"
  }
}
```

Packer fails to recognize this property and throws an error:

```
==> Wait completed after 2 microseconds
Error: Unsupported argument
==> Builds finished but no artifacts were created.

An argument named "qemu_img_args" is not expected here. Did you mean to define a
block of type "qemu_img_args"?
```

I have to use this property because I need to use `disk_image = true` so packer won't define the media type as "cdrom".

#### Reproduction Steps

* create a simple hcl file using `disk_image = true` and the above `qemu_img_args` property;
* run `packer build .`.

### Packer version

Packer v1.7.2

```
packer {
  required_plugins {
    qemu = {
      version = ">= 0.0.1"
      source  = "github.com/hashicorp/qemu"
    }
  }
}
```

### Simplified Packer Buildfile

https://gist.github.com/odra/16dbcaf2e286efbafcc7552d481acb87

### Operating system and Environment details

Fedora 33 x86_64

### Log Fragments and crash.log files

Already added in previous sections.

**Comment by nywilken** [comment]
Hi @odra thanks for reaching out. I see from your example you are setting `qemu_img_args` as a map with resize being the first key. The attribute is actually a block type with three reserved attributes `convert`, `create`, and `resize`. 

Have you tired using a block? 

By changing the config to look like the following the build should validate and execute as expected.
```
qemu_img_args {
 resize  = ["--shrink"]
}
```

I've created a PR to update the documentation with an example https://github.com/hashicorp/packer-plugin-qemu/pull/26 to help in the future. 

I'm going to close this issue as it is solved with a change to the configuration file. But feel free to open a new issue on [packer-plugin-qemu](https://github.com/hashicorp/packer-plugin-qemu/issues/new/choose) if you run into any other problems.
