### ISSUE TITLE
Unable to build with VMWare Player on Linux

### ISSUE THREAD

**Issue by jacek99** [hashicorp/packer#1102]
I tried create a base vmware-iso image. Installed VMWare Player (not Workstation) on Linux Mint.

Verified it is installed correctly, I can open it without any issues.

However, when I try to run my "vmware-iso" provisioner I get

```
Build 'vmware-iso' errored: Failed creating VMware driver: Unable to initialize any driver for this platform. The errors
from each driver are shown below. Please fix at least one driver
to continue:
* exec: "vmware": executable file not found in $PATH
* exec: "vmware": executable file not found in $PATH
* Critical application 'vmrun' not found in path.


==> Some builds didn't complete successfully and had errors:
--> vmware-iso: Failed creating VMware driver: Unable to initialize any driver for this platform. The errors
from each driver are shown below. Please fix at least one driver
to continue:
* exec: "vmware": executable file not found in $PATH
* exec: "vmware": executable file not found in $PATH
* Critical application 'vmrun' not found in path.


==> Builds finished but no artifacts were created.
```

According to the docs, just VMWare Player is supported on Linux, but I do not have any of these applications on the $PATH, only "vmplayer" is present.

**Comment by jantman** [comment]
@mitchellh I think this needs to be reopened, or at least have a documentation update. I ran into this problem as well... I assumed that the current version of Player would work.

**Comment by boothc27** [comment]
@mitchellh I agree with jantman I ran into this issue and this needs to be documented.

**Comment by ricardclau** [comment]
+1 here, not a biggie but please update the documentation

**Comment by andreynpetrov** [comment]
+1 please update the documentation

**Comment by georgealton** [comment]
+1

**Comment by vfiftyfive** [comment]
+1

**Comment by shyam2j** [comment]
+1

**Comment by AranVinkItility** [comment]
+1

**Comment by jeremycornett** [comment]
I'm requesting that this ticket be re-opened.

@mitchellh Can you elaborate on your solution please? I am unable to find vmrun on my hard disk. I have installed VMware Player 14 and the VIX SDK on my CentOS 7.3 box. I don't see a vmrun anywhere in the provided files.

**Comment by FriedCircuits** [comment]
@jeremycornett  I got vmrun with VMWare Workstation Player by install the VIX 1.17. https://my.vmware.com/web/vmware/free#desktop_end_user_computing/vmware_workstation_player/14_0|PLAYER-1411|drivers_tools

Now it is looking for vmware tools but that should be easy to get.

**Comment by mwhooker** [comment]
@FriedCircuits Thanks for the note. I've updated the docs here: https://github.com/hashicorp/packer/commit/c5ec92c88bb154bd317aec5b81ba6cf9e4dff9c4

the website will be updated on the next release

**Comment by FriedCircuits** [comment]
@mwhooker  Unfortunately I have hit more road blocks. More dependancies for vmrun and now unknown error which also happens when running manually to start a vm with nogui. That said I am on Ubunbu 16.04 Server in a VM. So now it looks like ESXi is a better option. 

This link says vmrun is deprecated in 12, which explains why it isn't included. 
https://communities.vmware.com/thread/538478

Worked great with Fusion though.

**Comment by mwhooker** [comment]
I should note that the supported versions of player are 5 and 6. It doesn't surprise me that the later versions don't work. We should probably phase out player support... You might have luck if you can track down an older version of player.

I'm going to open a new ticket about current versions of player not working. This thread is almost 4 years old, and is about a different problem, so I'm going to lock it. New discussions should happen on the new ticket
