### ISSUE TITLE
Re-opening 10853

### ISSUE THREAD

**Issue by jaymzh** [hashicorp/packer#11022]
Formatting lost due to copy-pasta-ing from other issue. Please stop the bot from closing legitimate issues. I have no desire to re-open this every 30 days when we've confirmed this is a legit issue.

Copied below from https://github.com/hashicorp/packer/issues/10853
---

Overview of the Issue

packer 1.7 assumes a new option called --nested-hw-virt which doesn't exist on VirtualBox 5
Reproduction Steps

try to build a vbox VM using packer 1.7 watch it fail:

VBoxManage: error: Unknown option: --nested-hw-virt

Packer version

1.7.1
Simplified Packer Buildfile

The contents literally don't matter, it fails as soon as it tries to create the vm
Operating system and Environment details

Ubuntu 18.04
Log Fragments and crash.log files

2021/03/31 17:50:10 packer-builder-virtualbox-iso plugin: Executing VBoxManage: []string{"modifyvm", "packer-virtualbox-iso-1617238193", "--nested-hw-virt", "off"}
2021/03/31 17:50:11 packer-builder-virtualbox-iso plugin: stdout:
2021/03/31 17:50:11 packer-builder-virtualbox-iso plugin: stderr: Oracle VM VirtualBox Command Line Management Interface Version 5.2.42_Ubuntu
2021/03/31 17:50:11 packer-builder-virtualbox-iso plugin: (C) 2005-2020 Oracle Corporation
2021/03/31 17:50:11 packer-builder-virtualbox-iso plugin: All rights reserved.
2021/03/31 17:50:11 packer-builder-virtualbox-iso plugin: 
2021/03/31 17:50:11 packer-builder-virtualbox-iso plugin: Usage:
2021/03/31 17:50:11 packer-builder-virtualbox-iso plugin: 
2021/03/31 17:50:11 packer-builder-virtualbox-iso plugin: VBoxManage modifyvm         <uuid|vmname>
...
2021/03/31 17:50:11 packer-builder-virtualbox-iso plugin: VBoxManage: error: Unknown option: --nested-hw-virt

**Comment by jaymzh** [comment]
@billjh previous pointed out

```
It should be introduced in #10736

https://github.com/hashicorp/packer/pull/10736/files#diff-7c07d450ded2de1671a031277786b07cb18827c6d9e5b9a0b8a765f4bff66a48R68-R72

	if config.NestedVirt == true {
		commands[11] = []string{"modifyvm", name, "--nested-hw-virt", "on"}
	} else {
		commands[11] = []string{"modifyvm", name, "--nested-hw-virt", "off"}
	}
```

and @sylviamoss added a bunch of tags.

**Comment by sylviamoss** [comment]
Hey @jaymzh, the other issue was closed because it was moved to https://github.com/hashicorp/packer-plugin-virtualbox/issues/4. We are tracking plugin's issues within the plugin repository as the code lives there now. Are you ok with closing this one and keeping the discussion at https://github.com/hashicorp/packer-plugin-virtualbox/issues/4?

**Comment by jaymzh** [comment]
Aha! Sorry it didn't say that. Totally cool, closing this. Thanks!
