### ISSUE TITLE
Filter for substring to find most recent custom_managed_image_name

### ISSUE THREAD

**Issue by jtravell** [hashicorp/packer#11033]
>**What specific syntax must be changed in the below in order for the Packer azure-arm builder 
to successfully retrieve the most recently created source image into the `custom_managed_image_name` 
field of the consumer builder shown below?**  
  
**CONSUMER BUILDER:**  
  
Here is the definition of the consumer builder for the image which must consume a custom managed image into the `custom_managed_image_name` parameter shown as follows:  
  
    "builders": [{
      "type": "azure-arm",
      ...other stuff
      "custom_managed_image_resource_group_name": "{{user `resource_group`}}",
      "custom_managed_image_name": "{{user `src_image_name`}}",
      "managed_image_resource_group_name": "{{user `resource_group`}}",
      "managed_image_name": "{{user `new_image_name`}}{{timestamp}}"
    }],
  
**SOURCE BUILDER:**  
  
And here is the definition of the builder for the source image which will be consumed by the above:  
  
    "builders": [{
      "type": "azure-arm",
      ...other stuff
      "managed_image_resource_group_name": "{{user `resource_group`}}",
      "managed_image_name": "{{user `new_image_name`}}{{timestamp}}"
    }],
  
**THE PROBLEM:**
  
In the SOURCE BUILDER shown above, the name for the resulting image is created using a time stamp by the following line:  
  
    "managed_image_name": "{{user `new_image_name`}}{{timestamp}}"
  
However, we do not know how to programmatically determine the correct `timestamp` value 
from the most recent image in order for our automation to successfully pass the unique 
name of the most recent image including the time stamp into the `src_image_name` variable from 
the CONSUMER BUILDER above shown here below as follows:  
  
    "custom_managed_image_name": "{{user `src_image_name`}}",
  
Under the hood, the solution to this needs to know to find a substring within a list of names of images in the resource group and then filter those image names to get the most recently created image whose name contains that substring.  
  
Is there a packer-native way to do this?  Or do we need to piece something together with scripting and other tools such as azure cli or terraform?

**Comment by jtravell** [comment]
Will you have time to answer this today?

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out. 

There is not currently an in-template way of doing this. However, you can use the [manifest](https://www.packer.io/docs/post-processors/manifest) post processor to print the artifact of one build, then use jq or another command line tool to parse it and input that value into your next build in your pipeline.
