### ISSUE TITLE
Typos in Guides

### ISSUE THREAD

**Issue by amayer5125** [hashicorp/packer#11039]
I found a few typos in the Packer guides on learn.hashicorp.com/tutorials/packer. I would love to fix them myself, but can't seem to find the guides on GitHub. If the guides are available on GitHub, please let me know and I will make a PR.

On [Build an Image](https://learn.hashicorp.com/tutorials/packer/aws-get-started-build-image?in=packer/aws-get-started):
- "If you have already have the plugins" should be "If you already have the plugins".
- "Now that you have create your first Packer image" should be "Now that you have created your first Packer image".

On [Provision](https://learn.hashicorp.com/tutorials/packer/aws-get-started-provision?in=packer/aws-get-started):
- "In addition, you will Although pre-installing Redis to your AMI" should probably have "In addition, you will" removed from the sentence.

**Comment by sylviamoss** [comment]
Hey there, thanks for finding those typos and reporting them. Our learn guides are not placed in this repo. We can handle that for you!

**Comment by sylviamoss** [comment]
Closing this one as it's handled internally. Thanks again!
