### ISSUE TITLE
how to change the directory?

### ISSUE THREAD

**Issue by timzhangliang** [hashicorp/packer#11038]
Current directory of vhd file is system/Microsoft.Compute/Images/images/, how can I change it directly to system/????

**Comment by SwampDragons** [comment]
Thanks for opening an issue -- to help you, we really do need the things requested in the issue template: 

- Packer version from `packer version`
- Host platform
- Full debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a gist https://gist.github.com
- The _simplest complete example template and scripts_ needed to reproduce the bug.
  Include these in your gist https://gist.github.com

**Comment by azr** [comment]
Hello there, closing this issue as it's one month old. I think that the following option docs could help here: https://www.packer.io/docs/builders/azure/arm#capture_container_name
