### ISSUE TITLE
Azure Key Vault not deleted in USGovCloud for Windows

### ISSUE THREAD

**Issue by lovleshmalik** [hashicorp/packer#11035]
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

I am trying to build windows image on Azure US govcloud. Image is created but packer starts throwing exception during cleanup time when deleting the keyvault, saying that the subscription is not found.
Interesting all the other resources were deleted.
On debugging further I found that, for all other resource deletion correct management url was used , https://management.usgovcloudapi.net, which is the correct url for govcloud.
When deleting vault, management url was used which is of Public Cloud "https://management.azure.com"
The subscription is of govcloud but it is querying public cloud, hence the error, subscription not found.

#### Reproduction Steps

Run the packerfile for Windows using winrm connector
Everything runs smoothly till the final step where cleanup is happening.
Every resource which was created is deleted except keyvault, which starts throwing exception that subscription is not found

### Packer version

1.7.2

### Simplified Packer Buildfile

https://github.com/lovleshmalik/testpacker/blob/main/packer_windows_govcloud_bak.json

### Operating system and Environment details

CentOS 7

### Log Fragments and crash.log files

azure-arm: Error: keyvault.VaultsClient#Delete: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="SubscriptionNotFound" Message="The subscription 'xxxx' could not be found."
==> azure-arm:
2021/05/20 10:45:25 packer-builder-azure-arm plugin: Azure response request="https://management.azure.com/subscriptions/xxxxxxxxxxx/resourceGroups/packerwin/providers/Microsoft.KeyVault/vaults/pkrkvxa7mtqo19k?api-version=2018-02-14" x-ms-request-id="73acb9d4-9e9c-4b14-aada-fb4957eeb548" body="{\"error\":{\"code\":\"SubscriptionNotFound\",\"message\":\"The subscription 'xxxxxxxx' could not be found.\"}}" status="404 Not Found" method="DELETE"
2021/05/20 10:45:25 packer-builder-azure-arm plugin: Azure response status="404 Not Found" method="DELETE" request="https://management.azure.com/subscriptions/xxxxxxx/resourceGroups/packerwin/providers/Microsoft.KeyVault/vaults/pkrkvxa7mtqo19k?api-version=2018-02-14" x-ms-request-id="73acb9d4-9e9c-4b14-aada-fb4957eeb548" body="{\"error\":{\"code\":\"SubscriptionNotFound\",\"message\":\"The subscription 'xxxxxxxx' could not be found.\"}}"
2021/05/20 10:45:25 packer-builder-azure-arm plugin: Retryable error: keyvault.VaultsClient#Delete: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="SubscriptionNotFound" Message="The subscription 'xxxxxx' could not be found."

**Comment by nywilken** [comment]
@lovleshmalik thanks for reaching out.  This is def. a bug. The code for the Azure plugin has been broken out into its separate repo so I am going to transfer this issue to the [hashicorp/packer-plugin-azure](https://github.com/hashicorp/packer-plugin-azure) so that we can track it there.  We try to get a fix in for the v1.7.4 release, if not sooner.
