### ISSUE TITLE
How to get a snapshot in gcp using packer

### ISSUE THREAD

**Issue by timzhangliang** [hashicorp/packer#11048]
ow to get a snapshot in gcp using packer

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out. 

Without having more details on what you're trying to do, I'm afraid all I can do is refer you to the GCP docs. If those aren't enough, please reach out to the [HashiCorp discussion forum](discuss.hashicorp.com/) for more help getting started!  https://www.packer.io/docs/builders/googlecompute

Thanks!

**Comment by timzhangliang** [comment]
I just want to get snapshort  in GCP using packer template, but I donot find any params or moudules in official documetion in packer, is packer do not support the function in GCP for now? If packer support it can u give me the guide resource, thanks a lot!

**Comment by SwampDragons** [comment]
The GCP builder is used to make whole images, not just standalone single-disk snapshots.
