### ISSUE TITLE
cd_files does not work for packer 1.7.2 HCL2

### ISSUE THREAD

**Issue by jimb0bmij** [hashicorp/packer#11054]
Trying to use cd_files via HCL2

A paragraph or two about the issue you're experiencing.

When I try to create a custom iso to use instead of the "old" floppy image. Does not SEEM to work. Also it seems that the packer_cache dir is not created when needed.

Steps to reproduce this issue

packer version 1.7.2 Linux x64

packerlog.txt:

2021/05/26 13:30:54 Waiting for RPC address for: /usr/sbin/packer.io
2021/05/26 13:30:54 packer.io plugin: [INFO] Packer version: 1.7.2 [go1.16.3 linux amd64]
2021/05/26 13:30:54 packer.io plugin: [INFO] PACKER_CONFIG env var not set; checking the default config file path
2021/05/26 13:30:54 packer.io plugin: [INFO] PACKER_CONFIG env var set; attempting to open config file: /home/jmccann/.packerconfig
2021/05/26 13:30:54 packer.io plugin: [WARN] Config file doesn't exist: /home/jmccann/.packerconfig
2021/05/26 13:30:54 packer.io plugin: [INFO] Setting cache directory: /code/jmccann/issues/packer/builds/vsphere/windows/windows-server-2019/packer_cache
2021/05/26 13:30:54 packer.io plugin: args: []string{"packer-provisioner-powershell"}
2021/05/26 13:30:54 packer.io plugin: Plugin address: unix /tmp/packer-plugin898758095
2021/05/26 13:30:54 packer.io plugin: Waiting for connection...
2021/05/26 13:30:54 Received unix RPC address for /usr/sbin/packer.io: addr is /tmp/packer-plugin898758095
2021/05/26 13:30:54 packer.io plugin: Serving a plugin connection...
2021/05/26 13:30:54 ui: ^[[1;32mvsphere-iso.windows-server: output will be in this color.^[[0m
2021/05/26 13:30:54 ui:
2021/05/26 13:30:54 Build debug mode: false
2021/05/26 13:30:54 Force build: true
2021/05/26 13:30:54 On error:
2021/05/26 13:30:54 Waiting on builds to complete...
2021/05/26 13:30:54 Starting build run: vsphere-iso.windows-server
2021/05/26 13:30:54 Running builder:
2021/05/26 13:30:54 [INFO] (telemetry) Starting builder
2021/05/26 13:30:54 packer.io plugin: No URLs were provided to Step Download. Continuing...
2021/05/26 13:30:54 ui: ^[[1;32m==> vsphere-iso.windows-server: Creating CD disk...^[[0m
2021/05/26 13:30:54 packer.io plugin: CD label is set to cidata
2021/05/26 13:30:54 packer.io plugin: CD path: /tmp/packer396192024.iso
2021/05/26 13:30:54 packer.io plugin: Wrote 13865 bytes to Register-WindowsInstall.ps1
2021/05/26 13:30:54 packer.io plugin: Wrote 12827 bytes to Set-WindowsEdition.ps1
2021/05/26 13:30:54 packer.io plugin: Executing: /usr/bin/xorriso [-as genisoimage -rock -joliet -volid cidata -output /tmp/packer396192024.iso /tmp/packer_to_cdrom163222423]
2021/05/26 13:30:54 ui: ^[[0;32m    vsphere-iso.windows-server: xorriso 1.5.2 : RockRidge filesystem manipulator, libburnia project.^[[0m
2021/05/26 13:30:54 ui: ^[[0;32m    vsphere-iso.windows-server: Drive current: -outdev 'stdio:/tmp/packer396192024.iso'^[[0m
2021/05/26 13:30:54 ui: ^[[0;32m    vsphere-iso.windows-server: Media current: stdio file, overwriteable^[[0m
2021/05/26 13:30:54 ui: ^[[0;32m    vsphere-iso.windows-server: Media status : is blank^[[0m
2021/05/26 13:30:54 ui: ^[[0;32m    vsphere-iso.windows-server: Media summary: 0 sessions, 0 data blocks, 0 data, 4053m free^[[0m
2021/05/26 13:30:54 ui: ^[[0;32m    vsphere-iso.windows-server: xorriso : WARNING : -volid text does not comply to ISO 9660 / ECMA 119 rules^[[0m
2021/05/26 13:30:54 ui: ^[[0;32m    vsphere-iso.windows-server: Added to ISO image: directory '/'='/tmp/packer_to_cdrom163222423'^[[0m
2021/05/26 13:30:54 ui: ^[[0;32m    vsphere-iso.windows-server: xorriso : UPDATE :       2 files added in 1 seconds^[[0m
2021/05/26 13:30:54 ui: ^[[0;32m    vsphere-iso.windows-server: xorriso : UPDATE :       2 files added in 1 seconds^[[0m
2021/05/26 13:30:54 ui: ^[[0;32m    vsphere-iso.windows-server: ISO image produced: 197 sectors^[[0m
2021/05/26 13:30:54 ui: ^[[0;32m    vsphere-iso.windows-server: Written to medium : 197 sectors at LBA 0^[[0m
2021/05/26 13:30:54 ui: ^[[0;32m    vsphere-iso.windows-server: Writing to 'stdio:/tmp/packer396192024.iso' completed successfully.^[[0m
2021/05/26 13:30:54 ui: ^[[0;32m    vsphere-iso.windows-server: Done copying paths from CD_dirs^[[0m
2021/05/26 13:30:54 ui: ^[[1;32m==> vsphere-iso.windows-server: Uploading packer396192024.iso to packer_cache/packer396192024.iso^[[0m
2021/05/26 13:30:55 [INFO] (telemetry) ending
2021/05/26 13:30:55 packer.io plugin: Deleting CD disk: /tmp/packer396192024.iso
2021/05/26 13:30:55 ui error: ^[[1;31mBuild 'vsphere-iso.windows-server' errored after 415 milliseconds 321 microseconds: 500 Internal Server Error^[[0m
2021/05/26 13:30:55 ui:
==> Wait completed after 415 milliseconds 378 microseconds
2021/05/26 13:30:55 machine readable: error-count []string{"1"}
2021/05/26 13:30:55 ui error:
==> Some builds didn't complete successfully and had errors:
2021/05/26 13:30:55 machine readable: vsphere-iso.windows-server,error []string{"500 Internal Server Error"}
2021/05/26 13:30:55 ui error: --> vsphere-iso.windows-server: 500 Internal Server Error
2021/05/26 13:30:55 ui:
==> Builds finished but no artifacts were created.

### Operating system and Environment details

Linux Redhat 7.7

It will create the packer#####.iso (if I look at the iso has the correct files in it).  What seems to be the issue is the step to move the created iso from /tmp/packer#####.iso to packer_cache. Like I said I don't see that directory created, even though I see in the logs it is SETTING the path during debug.

in  variables.auto.pkrvars.hcl:

vm_cd_files                    =  [
      "../../../../scripts/windows/windows-server-2019/*"
]

in template.windows.source.pkr.hcl:  

cd_files = var.vm_cd_files
cd_label = "cidata"

Also a note that might be something. This is on a newer version of vCenter 6.7.0 Build 15129973.

I have just verified my code I have works just fine. For vCenter 6.7.0 build 11727113.

All I did was change my vcenter code nothing else.

**Comment by jimb0bmij** [comment]
I think the issue is permissions. But what is very odd working with the vSphere Admin is he exported and imported permissions. But the code does work when we give the "service account" full admin access.

**Comment by jimb0bmij** [comment]
Well took us a bit, But my awesome vCenter Admin Phil P. rocked it out.

So changes that could effect your capability to use floppy/cd_files with packer.

vSAN encryption enabled.

If So you need to enabled these permissions.

Cryptographic operations:
Register VM
Add Disk
Clone
Direct Access
Encrypt
Encrypt New
Register VM

Hope this saves SOMEONE a lot of time. If so let use know here. :)

**Comment by animatco** [comment]
Great News Jim!

Jim McCann wrote on 5/28/2021 1:54 PM:
