### ISSUE TITLE
hcl2_upgrade doesn't correctly parse values for instance_defined_tags and defined_tags for source oracle-oci

### ISSUE THREAD

**Issue by the1403** [hashicorp/packer#11059]
Since in my case the source for oracle-oci requires that I use specific values for instance and image tagging (instance_defined_tags and defined_tags in particular), my old template which works OK (written in JSON) gets parsed wrongly.

Just to clarify - the use case is to be able to set this specific example tag:
Namespace: NS_NAME
Tag_Key: T_KEY
Tag_Value: T_VALUE
__The tag T_KEY is defined within namespace NS_NAME and has a value of T_VALUE.__

In JSON:
```
"defined_tags": {
  "NS_NAME": {
     "T_KEY": "T_VALUE"
  }
}
```

After hcl2_upgrade in hcl
```
defined_tags {
  NS_NAME = {
    T_KEY = "T_VALUE"
  }
}
```
*The same is valid for instance_defined_tags!

In brief - I can not use the instance_defined_tags and defined_tags parameters of source oracle-oci, when on the new hcl template and this used to work with JSON.
Also - I am unable to define these tags as any type or sort of variable, so if you could help me with that, that would also be great.

This is the error:
```
Blocks of type "defined_tags" are not expected here. Did you mean to define
argument "defined_tags"? If so, use the equals sign to assign it a value.
Error: Unsupported block type
  on main.json.pkr.hcl line 43:
  (source code not available)

Blocks of type "instance_defined_tags" are not expected here. Did you mean to
define argument "instance_defined_tags"? If so, use the equals sign to assign it
a value.
Debug mode enabled. Builds will not be parallelized.
```

**Comment by the1403** [comment]
Note : This may as well be an issue of the "Packer" itself, as similar structure (if not the same) works OK in Terraform.

**Comment by sylviamoss** [comment]
Thanks for reporting! I'm having a look at this. I'll probably add a new configuration for HCL2 that will accept a JSON string. Such mapping like the `defined_tags` and `instance_defined_tags` doesn't work for HCL2 because they work like JSON. 
I'll let you know when I have that implemented.

**Comment by the1403** [comment]
I can confirm that this works as documented. Thanks !
