### ISSUE TITLE
Fix for ubuntu ami race condition on cloud-init should be more visible in documentation

### ISSUE THREAD

**Issue by SimpleApp** [hashicorp/packer#11051]
Please search the existing issues for relevant feature requests, and use the
reaction feature
(https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
to add upvotes to pre-existing requests.

#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

As a newcomer to packer, i got stuck for a almost a week on the cloud-init race condition explained here : 
https://github.com/hashicorp/packer/commit/6af2fd5bd08826e8e1a9d78afc017853db58150b

Since installing an Ubuntu ami and running apt-get install is probably the most common first thing people will try on packer, i strongly suggest to put a more visible warning about this issue on the ami data-source page.

#### Use Case(s)

Any relevant use-cases that you see.

#### Potential configuration

```
```

**Comment by tenthirtyam** [comment]
@lbajolet-hashicorp - maybe transfer to `hashicorp/packer-plugin-amazon`?

**Comment by lbajolet-hashicorp** [comment]
Thanks for digging this one up @tenthirtyam,

Given it's an old thread, and I'm not sure how to address it, it is documented in a subsection, and without it being invasive, I don't think we can make it more visible too clearly.
It could also have been an issue with the old docs, hopefully the updated docs/sitemap makes it clearer what's on the page itself.

I'll close this now, but if anyone thinks this is still relevant these days, feel free to reopen, or if you have an idea on how to improve the docs for the plugin, I would suggest opening a PR directly on it so we can discuss that here.

Thanks!
