### ISSUE TITLE
Packer cannot send boot commands to QEMU

### ISSUE THREAD

**Issue by jacob-carlborg** [hashicorp/packer#11061]
#### Overview of the Issue

I'm building a VM image using the QEMU builder. I'm trying to install FreeBSD for ARM64, using `qemu-system-aarch64`. I have an array of boot commands in the Packer file. The problem is that after Packer sends the first boot command, any further boot commands will not be received in the VM. What seems to be happening is the QEMU stops respond to input, either from Packer or from manually entering input (using the QEMU window or over VNC). If I instead manually enter the first boot command, then QEMU continues to respond to input, either from manual input or from Packer.

The issue occurs when using the `edk2-aarch64-code.fd` firmware, which is shipped with QEMU. Or using the UEFI firmware provided here [2]. It does not occur when booting using U-Boot as described here [1] (U-Boot fails later for reasons that are not related to Packer, making it not usable for my use case). The issue does not occur when installing OpenBSD using the same firmware [2]. The issue seems to be a combination of Packer, the firmware and the FreeBSD installer.

I've attached a screen shot at the bottom, showing that the input Packer is sending is not received/visible in the QEMU window. The second `<enter>` and waiting 5 seconds should provide a prompt which Packer can enter the remaining boot commands on.

#### Reproduction Steps

Run `packer build freebsd.pkr.hcl` on the file available here [3].

### Packer version

Packer v1.7.2

### Simplified Packer Buildfile

https://gist.github.com/jacob-carlborg/e00cd902984532bc174a47e48482438e

### Operating system and Environment details

Occurs on both macOS and Linux.

```
$ qemu-system-aarch64 --version
QEMU emulator version 5.2.0
Copyright (c) 2003-2020 Fabrice Bellard and the QEMU Project developers
```

The issue occurs using QEMU 6 as well.

### Log Fragments and crash.log files

https://gist.github.com/jacob-carlborg/2adb7a5f622acf27d7a5466641cc36b0

Set the env var `PACKER_LOG=1` for maximum log detail.

[1] https://wiki.freebsd.org/arm64/QEMU
[2] http://releases.linaro.org/components/kernel/uefi-linaro/latest/release/qemu64/QEMU_EFI.fd

<img width="1307" alt="Screen Shot 2021-06-01 at 07 35 28" src="https://user-images.githubusercontent.com/306980/120272138-d8a83d80-c2ac-11eb-8845-08e226e85b53.png">

**Comment by sylviamoss** [comment]
Thanks for reporting, we will take a look when we get a chance!
