### ISSUE TITLE
Zstd compression support.

### ISSUE THREAD

**Issue by jboero** [hashicorp/packer#11075]
If Packer is going to provide artifact registry via HCP then Packer could really use a Zstd compression post processor.  Zstd is the open source compression created by Facebook for compressing large artifacts like Packer images.  It compresses and decompresses far faster than any of the existing gzip,xz,etc options currently supported by Packer and it results in much more compression than classic 7zip, gzip, etc.

#### Potential configuration
Zstd offers a compression level up to 19 with a default of 3 and supports concurrency which dramatically improves speed.  It would be simple to add a call to an external `zstd` or `pzstd` binary though it can't archive by itself so may need to be combined with tar or .tar.zstd.

```
{
  "type": "compress",
  "output": "img_{{.BuildName}}.zstd",
  "compression_level": 19
  "concurrency": 10
}
```

#### Potential References
A simple option of zstd or .tar.zstd should be simple to add.  Zstd support was recently added to go-getter here: https://github.com/hashicorp/go-getter/pull/292

**Comment by jboero** [comment]
I'm playing with the code to try this out right now.

**Comment by SwampDragons** [comment]
Just to clarify. The HCP Packer registry announced today will not be storing artifacts themselves. It is a metadata service that will track your artifacts and their provenance.

**Comment by jboero** [comment]
Understood that HCP has no storage.  Go-getter got support for Zstd anyway.
