### ISSUE TITLE
Packer tutorial has malformed HTML

### ISSUE THREAD

**Issue by danlamanna** [hashicorp/packer#11090]
https://learn.hashicorp.com/tutorials/packer/aws-windows-image?in=packer/integrations

The first code block on this tutorial is supposed to have a `<powershell>` code tag **within** the code block. Instead the tag is actually part of the HTML on the page! This is particularly important because there is no way to tell if your user data script is failing because of this.

**Comment by SwampDragons** [comment]
Good catch, thanks! Looks like the education team has already resolved it, since the code block is displayed and properly copies with the powershell html tags now.
