### ISSUE TITLE
panic when calling hcl2_upgrade with a non-existing file

### ISSUE THREAD

**Issue by fleaz** [hashicorp/packer#11117]
Hey, 
I just used the `hcl2_upgrade` (with Packer 1.7.3) command to upgrade our json config files to the new hcl versions which is working fine. But for one file I made a typo and specified a filename that doesn't exists and Packer is panicing. See this screenshot:
![Screenshot_2021-06-24_15:56:55](https://user-images.githubusercontent.com/2489598/123275690-d5e3e580-d504-11eb-8825-4692329210a4.png)
 
I just did a quick dive into the sourcecode and my guess would be that we need a return after this error message so we stop executing if packer couldn't read the file.
https://github.com/hashicorp/packer/blob/a2b710523870c11da6e63527c87016c8edbbc9a5/command/hcl2_upgrade.go#L156
I have little knowledge of the Packer internals, so before creating a wrong PR I wanted to ask if this is the correct way to tackle this :)

Best,
Felix

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out -- we'll fix this for the next release.
