### ISSUE TITLE
Links showing "Page Not Found" on download page

### ISSUE THREAD

**Issue by mukeshkmr776** [hashicorp/packer#11128]
On Packer Download page, few links are showing "Page Not Found" error under "Get Started" section.

See attached screenshots for better understanding.
![1](https://user-images.githubusercontent.com/18456767/124350610-251bcb80-dc13-11eb-9cfb-e8a0f0bfe202.png)
![2](https://user-images.githubusercontent.com/18456767/124350660-880d6280-dc13-11eb-9506-d3e0db68b241.png)

**Comment by sylviamoss** [comment]
Thanks for reporting! We will fix it 👍🏼

**Comment by sylviamoss** [comment]
Just figured out that this is fixed already https://github.com/hashicorp/packer/pull/11127 🎉

**Comment by SwampDragons** [comment]
I've just cherry-picked these changes to the released website branch. They should be live shortly.
