### ISSUE TITLE
Incorrect attribute value type; Inappropriate value for attribute "script"

### ISSUE THREAD

**Issue by davetustin** [hashicorp/packer#11121]
### Overview of the Issue

When using the PowerShell provisioner and using the "script" parameter, the following error message is returned.

Incorrect attribute value type; Inappropriate value for attribute "script": string required.

If the "scripts" parameter is used instead, it works fine.

### Reproduction Steps

provisioner "powershell" {
    script = [".\\build-config.ps1"]
  }

### Packer version

1.7.3

### Operating system and Environment details

Windows 7 x64

**Comment by dbond007** [comment]
That will be because you are passing it an array, not a string as is needed for script. Remove the [ ]. Scripts takes an array of strings.

**Comment by davetustin** [comment]
Thanks for getting back to me!

Well, I feel kinda stupid! Not sure why I didn't see that before!

I will do the walk of shame and close the ticket.

Thanks again!

Dave
