### ISSUE TITLE
AMI Tag Sharing

### ISSUE THREAD

**Issue by bantl23** [hashicorp/packer#11120]
Since ami tag sharing is not implemented in packer, what is a good way to share tags using packer? I've searched and only came up with a plugin. Is there no built in way even if the solution is running packer again?

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out. Can you clarify for me? What kind of tag sharing are you talking about -- and what plugin? https://github.com/hashicorp/packer-plugin-amazon is the official aws packer plugin, and is the one currently built in to packer. Can you share a little more about your actual use case and what you're trying to do?

**Comment by bantl23** [comment]
Hi, I'm trying to create an AMI in one account and share that AMI with another account. The issue I'm having is that tags are not being shared. I don't want to manually create tags afterwards. The plugin I found is called https://github.com/martinbaillie/packer-plugin-ami-copy. Unfortunately I'm having issues with that plugin. Is that the only way to share tags? Is there a more idiomatic way? Maybe something built into default packer plugins?

Here is my script if this gives more clarity. I want the accounts listed in aws_ami_users to also have the same tags.

```
variable "aws_access_key_id" {
  type    = string
  default = "${env("AWS_ACCESS_KEY_ID")}"
}

variable "aws_secret_access_key" {
  type    = string
  default = "${env("AWS_SECRET_ACCESS_KEY")}"
}

variable "aws_session_token" {
  type    = string
  default = "${env("AWS_SESSION_TOKEN")}"
}

variable "type" {
  type    = string
  default = "${env("TYPE")}"
}

variable "aws_ami_users" {
  default = [<redacted>]
}

variable "aws_ami_regions" {
  default = [<redacted>]
}

data "amazon-ami" "source" {
  access_key  = "${var.aws_access_key_id}"
  secret_key  = "${var.aws_secret_access_key}"
  token       = "${var.aws_session_token}"
  region      = "<redacted>"
  owners      = [<redacted>]
  filters = {
    architecture        = "x86_64"
    name                = "GCC Ubuntu 18.04*"
    root-device-type    = "ebs"
    virtualization-type = "hvm"
  }
  most_recent = true
}

source "amazon-ebs" "proxy" {
  access_key                  = "${var.aws_access_key_id}"
  secret_key                  = "${var.aws_secret_access_key}"
  token                       = "${var.aws_session_token}"
  region                      = "<redacted>"
  vpc_id                      = "<redacted>"
  subnet_id                   = "<redacted>"
  security_group_id           = "<redacted>"
  ami_name                    = "daphne-${var.type}-proxy ubuntu ${legacy_isotime("20060102T150405.999999999")}"
  ami_regions                 = "${var.aws_ami_regions}"
  ami_users                   = "${var.aws_ami_users}"
  source_ami                  = "${data.amazon-ami.source.id}"
  ssh_username                = "ubuntu"
  instance_type               = "t2.small"
  associate_public_ip_address = true

  tags = {
    OS_Version      = "Ubuntu"
    OperatingSystem = "Ubuntu1804"
    Project         = "GCC"
    Usage           = "Prod"
    SourceAMI       = "{{ .SourceAMI }}"
  }

  run_tags = {
    OS_Version      = "Ubuntu"
    OperatingSystem = "Ubuntu1804"
    Project         = "GCC"
    Usage           = "Prod"
    SourceAMI       = "{{ .SourceAMI }}"
  }
}

build {
  sources = ["source.amazon-ebs.proxy"]

  provisioner "ansible" {
    max_retries   = "2"
    pause_before  = "2m0s"
    playbook_file = "site.yml"
    timeout       = "10m0s"
    user          = "ubuntu"
  }
}
```

**Comment by SwampDragons** [comment]
Thanks for the clarification. I understand what you're asking. I think you're stuck; right now that probably is the only packer-specific way to share tags (though since that's a community plugin I don't know exactly how it works nor can I really support it).

Another way would be to write a shell-local post-processor that adds the tags using the aws-cli, but I understand that's a lot of work. I think we could probably add an option to the amazon plugin to copy tags as well as images to the different accounts/regions, if that's something the amazon api supports. So this is probably best categorized as a feature request on the amazon plugin. I'll tag this for our bot to move over there so we can track it.

**Comment by bantl23** [comment]
Thank you! I hope you all implement that feature!
