### ISSUE TITLE
Viewing role details for JWT integration

### ISSUE THREAD

**Issue by synergiator** [hashicorp/packer#11137]
In GitLab context, it's possible to create "roles" which is basically a mapping between a GitLab project and some resources pattern.

What seems strange though, it's only possible to get a list of names of these roles in the console, but:

* can't see anything regarding this type of asset in the UI, why? 
* is it really not possible to see the details of what has been configured for roles even on console? why?

**Comment by azr** [comment]
Hey @synergiator, thanks for opening, I'm not sure at all this relates to Packer ? I'd advise to maybe ask over in GitLab land ? Closing, as it seems out of context to me, please comment here if you think otherwise.

**Comment by synergiator** [comment]
sorry this one relates to Vault!.. I'll repost, thx

**Comment by azr** [comment]
No problem ! 🙂
