### ISSUE TITLE
Release plugin bug

### ISSUE THREAD

**Issue by wangjiaxi90** [hashicorp/packer#11140]
When the version of packer from v1.7.2 to v1.7.3.
I release my packer-plugin has a problem on step:  builds -> hooks -> post,
![image](https://user-images.githubusercontent.com/37741159/125235792-9810fa80-e315-11eb-87a3-e62b54becd8a.png)
And the github action error is:
![image](https://user-images.githubusercontent.com/37741159/125235975-da3a3c00-e315-11eb-93de-a6b75030efa8.png)

And I modify the packer version in .goreleaser.yml It can be work.
![image](https://user-images.githubusercontent.com/37741159/125236218-2b4a3000-e316-11eb-9ce9-4c70c6cc7fc0.png)

![image](https://user-images.githubusercontent.com/37741159/125236269-41f08700-e316-11eb-96f0-9b71ff10ec85.png)

**Comment by sylviamoss** [comment]
Thanks for reporting! We will fix it as soon as possible. The hook checks if packer can load your plugin and if it contains the necessary hcl2 generated specs. If you do it on your own before releasing you could also remove the hook until is fixed.

**Comment by nywilken** [comment]
Hello this issue was resolved in the latest release of Packer v1.7.4. Please give the latest release a try and let us know if you run into any issues. Cheers!

**Comment by wangjiaxi90** [comment]
Thank you.  After the test, the version is released normally. Thanks again.
