### ISSUE TITLE
packer built docker container/box will not launch with vagrant

### ISSUE THREAD

**Issue by josh-m-sharpe** [hashicorp/packer#11189]
Documentation suggests packer should be able to build a docker container and associated vagrant box file that can be launched with `vagrant up` - I cannot seem to get that to work.  Steps to repro are here:

https://discuss.hashicorp.com/t/cant-get-packer-build-docker-box-to-launch-with-vagrant/27244

**Comment by nywilken** [comment]
Thanks for reaching out. We will take a look to see what might be going on here.
