### ISSUE TITLE
packer can't validate when using the output of a data lookup as a value in shell provisioner environment_vars element

### ISSUE THREAD

**Issue by anoshi** [hashicorp/packer#11197]
#### Overview of the Issue

`packer validate .` fails when an output of a data lookup is used as an element of the shell provisioner's `environment_vars` attribute.

`packer build .` runs successfully, however.

#### Reproduction Steps

```hcl
data "amazon-secretsmanager" "some-secret" {
  access_key  = var.access_key
  secret_key  = var.secret_key
  region      = "some-aws-region"

  name        = "some-secret"
}

locals {
  some_secret_key = jsondecode(data.amazon-secretsmanager.some-secret.secret_string)["secret-key"]
}

build {
  ...
  ...
  provisioner "shell" {
    environment_vars = ["MY_SECRET=${local.some_secret_key}"]
    script           = "./scripts/sad.sh"
  }
}
```

```sh
export AWS_ACCESS_KEY_ID=blah
export AWS_SECRET_ACCESS_KEY=secretblah

packer init .
packer validate .

Error: Failed preparing provisioner-block "shell" ""

  on build.pkr.hcl line XY:
  (source code not available)

1 error(s) occurred:

* Environment variable not in format 'key=value': <unknown>
```

```sh
packer build  .
amazon-ebs.base: output will be in this color.

==> amazon-ebs.base: Prevalidating any provided VPC information
==> amazon-ebs.base: Prevalidating AMI Name: blah-ami-1628653406
...
...
```

### Packer version

1.7.3

**Comment by nywilken** [comment]
Thanks for reaching out. We will take a look as soon as we can.

**Comment by azr** [comment]
Hello there, thanks for opening, this works on my machine. Looking at the specific code this runs through:

https://github.com/hashicorp/packer/blob/87ba7258b352d634b95f7e506685a725d8e46a45/provisioner/shell/provisioner.go#L164-L171

This can only happen when the env var setting is malformed (like, when there is no equal sign) can you confirm this is still happening for you ? 

Here, for example, this code tells me that the following was set:

```hcl
environment_vars = "${local.some_secret_key}"
```

Closing this issue as I can't repro, please comment here if you still have the issue, we'll try to help !

**Comment by anoshi** [comment]
Hi @azr,

Thank you for taking a look. I still can't validate (but can build) with this code. I've tried a few combinations and permutations here and the issue does look to be related to the value of a passed `environment_vars` pair being the output from a data lookup of type *amazon-secretsmanager*.

1. Wrong syntax, should fail:

    ```hcl
    provisioner "shell" {
      environment_vars = "MY_SECRET"
      script           = "./scripts/script.sh"
    }
    ```

    Does fail:

    ```txt
    $ packer validate .
    build.pkr.hcl:57,24-35: Incorrect attribute value type; Inappropriate value for
    attribute "environment_vars": list of string required.
    ```

1. A list, but not k=v, should fail:

    ```hcl
    provisioner "shell" {
        environment_vars = ["MY_SECRET"]
        script           = "./scripts/script.sh"
      }
    ```

    Does fail:

    ```txt
    $ packer validate .
    Error: Failed preparing provisioner-block "shell" ""

      on build.pkr.hcl line 56:
      (source code not available)

    1 error(s) occurred:

    * Environment variable not in format 'key=value': MY_SECRET
    ```

1. Correct syntax, using known values, should work:

    ```hcl
    locals {
      not_a_lookup = "known_value"
    }

    provisioner "shell" {
      environment_vars = ["MY_SECRET=${local.not_a_lookup}"]
      script           = "./scripts/script.sh"
    }
    ```

    Does work:

    ```txt
    $ packer validate .
    $
    ```

1. Correct syntax, using value computed / returned from data lookup, should work:

    ```hcl
    locals {
      some_secret_key = jsondecode(data.amazon-secretsmanager.some-secret.secret_string)["secret-key"]
    }

    provisioner "shell" {
      environment_vars = ["MY_SECRET=${local.some_secret_key}"]
      script           = "./scripts/script.sh"
    }
    ```

    Does not:

    ```txt
    $ packer validate .
    Error: Failed preparing provisioner-block "shell" ""

      on build.pkr.hcl line 56:
      (source code not available)

    1 error(s) occurred:

    * Environment variable not in format 'key=value': <unknown>
    ```

**Comment by azr** [comment]
Right, I see, I think that this is due to the fact that Packer evaluates its HCL block in phases. Instead of building a dag (Directed acyclic graph).

**Comment by dindurthy** [comment]
Any word on a workaround for this?

**Comment by azr** [comment]
Update here: this really looks like a bug and not how we intend this to work, will keep you posted.

**Comment by azr** [comment]
Okay, I understand the issue better here.

**Cause:**
So, basically, we have a string that has a part that is unknown; Unknown is a hcl2 state to sort of say we don't know that value, yet.

In my mind, this value would sort of magically evaluate to `MY_SECRET=<unknown>`, but nope !
We have a piece of code that transforms HCL2 values into packer configuration values (or, just plain go values), and it's not being subtle right now in the sense that if any part of a string is `unknown`, the whole string will be evaluated as `unknown`, hence why we see  `* Environment variable not in format 'key=value': <unknown>`.

**Possible solutions:**
* I will try to see if I can make that transformer a little more subtle, in order for it to evaluate to `MY_SECRET=<unknown>`
* Worst case scenario, if that does not work, we can make of the `env` field a key value map.

**Comment by azr** [comment]
Hello there, a subtle-hack is not going to work, so I'm going to try with adding a new env `map[string]string` for env vars.

Note that I'd like to prioritize some dag work after this.
