### ISSUE TITLE
Error: Unsupported argument -- output_name

### ISSUE THREAD

**Issue by josh-m-sharpe** [hashicorp/packer#11192]
According to https://www.packer.io/docs/templates/hcl_templates/blocks/build/source I should be able to add a `output_name` to my build.source block like below.  This results in this error:

```
Error: Unsupported argument

  on amzn2.pkr.hcl line 44:
  (source code not available)

An argument named "output_image" is not expected here.
```

```
source "amazon-ebs" "amzn2" {
  # ...
}

build {
  source "source.amazon-ebs.amzn2" {
    name = "what"
    output_image = "foo" # ADDING THIS LINE
  }
}
```

If that doesn't work - what's the correct way to rename the resulting image?

**Comment by josh-m-sharpe** [comment]
It doesn't seem to like `output` either:

```
Error: Unsupported argument

  on ./packer/amzn2.pkr.hcl line 43:
  (source code not available)

An argument named "output" is not expected here.
```

**Comment by azr** [comment]
Hey @josh-m-sharpe, thanks for opening 🙂 . You seem to be looking at the `source` block docs, for that _example_ a builder was picked randomly (we picked the `lxd` builder in that case), you probably mean to look at the https://www.packer.io/docs/builders/amazon/ebs#ami_name (`ami_name`) field in the `amazon-ebs` builder docs.

Going to go ahead and close that issue !

**Comment by josh-m-sharpe** [comment]
@azr - I don't think you have that right.  Both the documentation and the YouTube video that I referenced have a value at build.source.output_name that doesn't appear to work.  Please advise.

**Comment by azr** [comment]
@josh-m-sharpe `build.source.output_name` is not usable in the `amazon-ebs` builder; but the `build.source.ami_name` is:

Copy/Pasting the docs:

> ami_name (string) - The name of the resulting AMI that will appear when managing AMIs in the AWS console or via APIs. This must be unique. To help make this unique, use a function like timestamp (see template engine for more info).
