### ISSUE TITLE
packer crash

### ISSUE THREAD

**Issue by kra** [hashicorp/packer#11208]
#### Overview of the Issue

packer crashed and told me to report it here

#### Reproduction Steps

packer build -var-file=conf/variables.pkr.hcl -var "image=89824917" deploy/baseinstall_update_template.pkr.hcl

### Packer version

Packer v1.7.4

### Simplified Packer Buildfile

```
# Packer template to create update image from baseinstall image

variable "deploy_access_token" {
    type = string
    default = ""
}

variable "image" {
    type = string
}

source "digitalocean" "foo" {
    api_token    = "${var.deploy_access_token}"
    droplet_name = "futel-stage.phu73l.net"
    image        = "${var.image}"
    region       = "sfo1"
    size         = "s-1vcpu-1gb"
    communicator = "ssh"
    ssh_username = "futel"
    ssh_port = "42422"
    ssh_private_key_file = "conf/id_rsa"
    snapshot_name = "update"
}

build {
    sources = ["source.digitalocean.foo"]
    provisioner "ansible" {
        groups = ["baseinstall"]
            use_proxy = "false"
            playbook_file = "deploy/update_asterisk_playbook.yml"
            extra_arguments = ["--vault-password-file=conf/vault_pass_generic.txt"]        
        }
}
```

### Operating system and Environment details

ubuntu

### Log Fragments and crash.log files

2021/08/14 16:49:42 [INFO] Packer version: 1.7.4 [go1.16.6 linux amd64]
2021/08/14 16:49:42 [TRACE] discovering plugins in /usr/bin
2021/08/14 16:49:42 [TRACE] discovering plugins in /home/karl/.packer.d/plugins
2021/08/14 16:49:42 [TRACE] discovering plugins in .
2021/08/14 16:49:42 [INFO] PACKER_CONFIG env var not set; checking the default config file path
2021/08/14 16:49:42 [INFO] PACKER_CONFIG env var set; attempting to open config file: /home/karl/.packerconfig
2021/08/14 16:49:42 [WARN] Config file doesn't exist: /home/karl/.packerconfig
2021/08/14 16:49:42 [INFO] Setting cache directory: /home/karl/Documents/futel-installation/asteriskserver/packer_cache
2021/08/14 16:49:42 [TRACE] validateValue: not active for deploy_access_token, so skipping
2021/08/14 16:49:42 [TRACE] validateValue: not active for image, so skipping
2021/08/14 16:49:42 [TRACE] Starting internal plugin packer-builder-digitalocean
2021/08/14 16:49:42 Starting plugin: /usr/bin/packer []string{"/usr/bin/packer", "plugin", "packer-builder-digitalocean"}
2021/08/14 16:49:42 Waiting for RPC address for: /usr/bin/packer
2021/08/14 16:49:42 packer-builder-digitalocean plugin: [INFO] Packer version: 1.7.4 [go1.16.6 linux amd64]
2021/08/14 16:49:42 packer-builder-digitalocean plugin: [INFO] PACKER_CONFIG env var not set; checking the default config file path
2021/08/14 16:49:42 packer-builder-digitalocean plugin: [INFO] PACKER_CONFIG env var set; attempting to open config file: /home/karl/.packerconfig
2021/08/14 16:49:42 packer-builder-digitalocean plugin: [WARN] Config file doesn't exist: /home/karl/.packerconfig
2021/08/14 16:49:42 packer-builder-digitalocean plugin: [INFO] Setting cache directory: /home/karl/Documents/futel-installation/asteriskserver/packer_cache
2021/08/14 16:49:42 packer-builder-digitalocean plugin: args: []string{"packer-builder-digitalocean"}
2021/08/14 16:49:42 packer-builder-digitalocean plugin: Plugin address: unix /tmp/packer-plugin251786442
2021/08/14 16:49:42 Received unix RPC address for /usr/bin/packer: addr is /tmp/packer-plugin251786442
2021/08/14 16:49:42 packer-builder-digitalocean plugin: Waiting for connection...
2021/08/14 16:49:42 packer-builder-digitalocean plugin: Serving a plugin connection...
2021/08/14 16:49:42 [TRACE] Starting internal plugin packer-provisioner-ansible
2021/08/14 16:49:42 Starting plugin: /usr/bin/packer []string{"/usr/bin/packer", "plugin", "packer-provisioner-ansible"}
2021/08/14 16:49:42 Waiting for RPC address for: /usr/bin/packer
2021/08/14 16:49:42 packer-provisioner-ansible plugin: [INFO] Packer version: 1.7.4 [go1.16.6 linux amd64]
2021/08/14 16:49:42 packer-provisioner-ansible plugin: [INFO] PACKER_CONFIG env var not set; checking the default config file path
2021/08/14 16:49:42 packer-provisioner-ansible plugin: [INFO] PACKER_CONFIG env var set; attempting to open config file: /home/karl/.packerconfig
2021/08/14 16:49:42 packer-provisioner-ansible plugin: [WARN] Config file doesn't exist: /home/karl/.packerconfig
2021/08/14 16:49:42 packer-provisioner-ansible plugin: [INFO] Setting cache directory: /home/karl/Documents/futel-installation/asteriskserver/packer_cache
2021/08/14 16:49:42 packer-provisioner-ansible plugin: args: []string{"packer-provisioner-ansible"}
2021/08/14 16:49:42 packer-provisioner-ansible plugin: Plugin address: unix /tmp/packer-plugin941654698
2021/08/14 16:49:42 packer-provisioner-ansible plugin: Waiting for connection...
2021/08/14 16:49:42 Received unix RPC address for /usr/bin/packer: addr is /tmp/packer-plugin941654698
2021/08/14 16:49:42 packer-provisioner-ansible plugin: Serving a plugin connection...
2021/08/14 16:49:43 packer-provisioner-ansible plugin: ansible-playbook version: 2.11.1
2021/08/14 16:49:43 ui: [1;32mdigitalocean.foo: output will be in this color.[0m
2021/08/14 16:49:43 ui: 
2021/08/14 16:49:43 Build debug mode: false
2021/08/14 16:49:43 Force build: false
2021/08/14 16:49:43 On error: 
2021/08/14 16:49:43 Waiting on builds to complete...
2021/08/14 16:49:43 Starting build run: digitalocean.foo
2021/08/14 16:49:43 Running builder: 
2021/08/14 16:49:43 [INFO] (telemetry) Starting builder 
2021/08/14 16:49:43 ui: [1;32m==> digitalocean.foo: Using existing SSH private key[0m
2021/08/14 16:49:43 ui: [1;32m==> digitalocean.foo: No public SSH key found; skipping SSH public key import...[0m
2021/08/14 16:49:43 packer-builder-digitalocean plugin: panic: interface conversion: interface {} is nil, not int
2021/08/14 16:49:43 packer-builder-digitalocean plugin: 
2021/08/14 16:49:43 packer-builder-digitalocean plugin: goroutine 86 [running]:
2021/08/14 16:49:43 packer-builder-digitalocean plugin: github.com/hashicorp/packer-plugin-digitalocean/builder/digitalocean.(*stepCreateDroplet).Run(0xc00033e8d8, 0x5e4ce80, 0xc0004be480, 0x5e4d8c8, 0xc000a3f560, 0x0)
2021/08/14 16:49:43 packer-builder-digitalocean plugin: 	/home/circleci/go/pkg/mod/github.com/hashicorp/packer-plugin-digitalocean@v1.0.0/builder/digitalocean/step_create_droplet.go:24 +0x886
2021/08/14 16:49:43 packer-builder-digitalocean plugin: github.com/hashicorp/packer-plugin-sdk/multistep.(*BasicRunner).Run(0xc000a3f5f0, 0x5e4ce80, 0xc0004be480, 0x5e4d8c8, 0xc000a3f560)
2021/08/14 16:49:43 packer-builder-digitalocean plugin: 	/home/circleci/go/pkg/mod/github.com/hashicorp/packer-plugin-sdk@v0.2.3/multistep/basic_runner.go:70 +0x234
2021/08/14 16:49:43 packer-builder-digitalocean plugin: github.com/hashicorp/packer-plugin-digitalocean/builder/digitalocean.(*Builder).Run(0xc000177b00, 0x5e4ce80, 0xc0004be480, 0x5e66198, 0xc000a3f4d0, 0x5dbd7e0, 0xc0000436a0, 0xc000a3f380, 0x4ab6740, 0xc000043680, ...)
2021/08/14 16:49:43 packer-builder-digitalocean plugin: 	/home/circleci/go/pkg/mod/github.com/hashicorp/packer-plugin-digitalocean@v1.0.0/builder/digitalocean/builder.go:116 +0x7f4
2021/08/14 16:49:43 packer-builder-digitalocean plugin: github.com/hashicorp/packer-plugin-sdk/rpc.(*BuilderServer).Run(0xc00004a040, 0x1, 0xc00033e85c, 0x0, 0x0)
2021/08/14 16:49:43 packer-builder-digitalocean plugin: 	/home/circleci/go/pkg/mod/github.com/hashicorp/packer-plugin-sdk@v0.2.3/rpc/builder.go:117 +0x1c4
2021/08/14 16:49:43 packer-builder-digitalocean plugin: reflect.Value.call(0xc0001844e0, 0xc0005b8088, 0x13, 0x56cc20d, 0x4, 0xc00057ef08, 0x3, 0x3, 0x0, 0x0, ...)
2021/08/14 16:49:43 packer-builder-digitalocean plugin: 	/usr/local/go/src/reflect/value.go:476 +0x8e7
2021/08/14 16:49:43 packer-builder-digitalocean plugin: reflect.Value.Call(0xc0001844e0, 0xc0005b8088, 0x13, 0xc000722f08, 0x3, 0x3, 0x0, 0x0, 0x0)
2021/08/14 16:49:43 packer-builder-digitalocean plugin: 	/usr/local/go/src/reflect/value.go:337 +0xb9
2021/08/14 16:49:43 packer-builder-digitalocean plugin: net/rpc.(*service).call(0xc00004a080, 0xc00019c0a0, 0xc000558060, 0xc000558070, 0xc000040300, 0xc0000420a0, 0x469d880, 0xc00033e858, 0x18a, 0x4577e60, ...)
2021/08/14 16:49:43 packer-builder-digitalocean plugin: 	/usr/local/go/src/net/rpc/server.go:377 +0x189
2021/08/14 16:49:43 packer-builder-digitalocean plugin: created by net/rpc.(*Server).ServeCodec
2021/08/14 16:49:43 packer-builder-digitalocean plugin: 	/usr/local/go/src/net/rpc/server.go:474 +0x44d
2021/08/14 16:49:43 /usr/bin/packer: plugin process exited
2021/08/14 16:49:43 [INFO] (telemetry) ending 
2021/08/14 16:49:43 ui error: [1;31mBuild 'digitalocean.foo' errored after 8 milliseconds 345 microseconds: unexpected EOF[0m
2021/08/14 16:49:43 ui: 
==> Wait completed after 8 milliseconds 497 microseconds
2021/08/14 16:49:43 machine readable: error-count []string{"1"}
2021/08/14 16:49:43 ui error: 
==> Some builds didn't complete successfully and had errors:
2021/08/14 16:49:43 machine readable: digitalocean.foo,error []string{"unexpected EOF"}
2021/08/14 16:49:43 ui error: --> digitalocean.foo: unexpected EOF
2021/08/14 16:49:43 ui: 
==> Builds finished but no artifacts were created.
2021/08/14 16:49:43 [INFO] (telemetry) Finalizing.
2021/08/14 16:49:43 waiting for all plugin processes to complete...
2021/08/14 16:49:43 /usr/bin/packer: plugin process exited

**Comment by kra** [comment]
crash started happening after I added the ssh communicator attributes to the template

**Comment by kra** [comment]
also, the image that it is building from requires the ssh attributes

**Comment by nywilken** [comment]
Thanks for reporting. This is a bug that occurs when no "ssh_key_id" is specified in the template, and is also an issue with the documentation. We will work on getting this fixed as soon as we can. 

In the meantime, since you are specifying a private SSH key file you can fix this issue by specifying the `ssh_key_id = <id to existing DO public SSH key>`. 

The value of `ssh_key_id` is the ID of an existing SSH key on the DigitalOcean account. Which needs to be specified when using `ssh_private_key_file`.
