### ISSUE TITLE
Templating for floppy_files and cd_files

### ISSUE THREAD

**Issue by ekristen** [hashicorp/packer#11210]
#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

Please add templating for floppy_files and cd_files, or add an additional option to provide templated files using templatefile

This is being opened because https://github.com/hashicorp/packer/issues/4530 was closed.

#### Use Case(s)

The only way to provide windows with an Autounattend.xml is via floppy/usb/cd and there are a number of reasons why the Autounattend.xml needs to be a template.

I'm sure there are other use cases where floppy/usb/cd files need to be templated.

#### Potential configuration

```
template_floppy_files = {
  "Autounattend.xml": templatefile("${path.root}/templates/Autunattend.xml", { product_key = var.product_key })
}
```

**Comment by puetzk** [comment]
FYI: this is possible using `http_content` since https://github.com/hashicorp/packer-plugin-sdk/pull/43, and `cd_content` since https://github.com/hashicorp/packer-plugin-sdk/pull/61. So I think it's just floppies that still don't have a way.

**Comment by ekristen** [comment]
Oh interesting. I missed that about cd content. I knew http had it, so if floppy could get it we'd be set.

**Comment by tenthirtyam** [comment]
Works wonderfully for the vSphere plugin for `http_content`, `cd_content`, and `floppy_content`. Used heavily in https://github.com/vmware-samples/packer-examples-for-vsphere.

@azr - it seems to me that this issue should be closed and that the support for templates is dependent on the plugin - and that issues should be raised at the plugin's project repo instead.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by nywilken** [comment]
Closing as this has been fixed in the latest release for the vSphere Packer plugin. For other plugins that don't have this functionality please open an enhancement request on plugin issue tracker.
