### ISSUE TITLE
resource group or build resource group

### ISSUE THREAD

**Issue by r32rtb** [hashicorp/packer#11256]
#### Overview of the Issue

The debug logging indicates a contradiction of requirements.  I need to build in a specific resource group.  The error seems to think I need both a resource_group_name and a build_resource_group_name but I can't include both due to needing one or the other.

#### Reproduction Steps

#resource_group_name               = "${var.azure_resource_group}"
build_resource_group_name         = "${var.azure_resource_group}"

Produces this error:

Error: 2 error(s) occurred:
* Specify either a location to create the resource group in or an existing build_resource_group_name, but not both.

* A resource_group_name must be specified
* Specify either a location to create the resource group in or an existing build_resource_group_name, but not both.

* A resource_group_name must be specified
* A paragraph or two about the issue you're experiencing.

resource_group_name               = "${var.azure_resource_group}"
build_resource_group_name         = "${var.azure_resource_group}"

Produces this error:

Error: 1 error(s) occurred:
* Specify either a location to create the resource group in or an existing build_resource_group_name, but not both.

  on windows-2019.pkr.hcl line 40:

  (source code not available)
* Specify either a location to create the resource group in or an existing build_resource_group_name, but not both.

### Packer version

From `packer version`
1.7.4

### Operating system and Environment details

WSL2 Ubuntu

### Log Fragments and crash.log files

Up above in the reproduce steps section.

**Comment by nywilken** [comment]
Hi there, this error messaging is confusing for sure. What the error is trying to say is  when using the attribute `build_resource_group_name` the `location` attribute can not be set. 

If you remove `resource_group_name` and `location` from your template are you able to build using the exiting resource group?
