### ISSUE TITLE
-var-file don't work, when vars.pkr.hcl is in a different path, than buld.pkr.hcl

### ISSUE THREAD

**Issue by unbreakabl3** [hashicorp/packer#11273]
#### Overview of the Issue

First of all - with regular .json files all is working well. With HCLs, when trying to provide a path to `variables.json.pkr.hcl`, which is located in a different folder than `build.pkr.hcl`, I am getting an error for each variable, defined in `variables.json.pkr.hcl` an error  like that:

```
Error: Variable declaration in a .pkrvar file

  on /path_to/variables.json.pkr.hcl line 86, in variable "vsphere_datacenter":
  86: variable "vsphere_datacenter" {

A .pkrvar file is used to assign values to variables that have already been
declared in .pkr files, not to declare new variables. To declare variable
"vsphere_datacenter", place this block in one of your .pkr files, such as
variables.pkr.hcl

To set a value for this variable in
/path_to/variables.json.pkr.hcl, use the
definition syntax instead:
    vsphere_datacenter = <value>
```

If I put `variables.json.pkr.hcl` to the same folder, where the `build.pkr.hcl` is living and not need to use `-var-file` anymore, all is working well. 

I cannot and don't want to put vars file to the same folder with a build file, because this is a reusable vars file for many other builds. And again - with jsons all is working well.

Another thing I'm not sure I understand is relation to `pkrvars.hcl` file in the error. I don't have this file. All my vars has a `default` value and looks like that:

```
variable "vsphere_datacenter" {
  type    = string
  default = "test_datacenter"
}
```

#### Reproduction Steps

put `build.pkr.hcl` and variables.json.pkr.hcl in a different folders and use `-var-file` switch 

### Packer version

1.7.5 (on 1.7.4 its not working as well)

### Operating system and Environment details

MacOS 11.4
Ubuntu Server 20.0.4

**Comment by nywilken** [comment]
Hi there, thanks for reaching out. I think this is more of an issue around the error messaging including .pkrvar and .pkr as example place holders. 

The issue you are running into is that you appear to have your variable definitions with default values in the file you are passing to -var-file, which essentially means you are defining the variables and not just assigning a value to an already defined variable. This is the reason why it works when you move the file into the same directory and don't specify `-var-file` option. 


To help illustrate I provided an example below

```hcl
#variables.pkr.hcl
variable "message" {
  type = string
  default = "Hello"
}
```

```hcl
#source.pkr.hcl
source "null" "example" {
  communicator = "none"
}

build {
  sources = ["source.null.example"]
  provisioner "shell-local" {
    inline = ["echo ${var.message}"]
  }
}
```

```hcl
# /tmp/example/vars.hcl
message = "Hello World"
```

If I run `packer build` without the `-var-file` option packer will use the default value specified in the variable definition block for "message". 
```shell
null.example: output will be in this color.

==> null.example: Running local shell script: /var/folders/vz/rv7bk6v15211jxg8q801f7kw0000gq/T/packer-shell2870543883
    null.example: Hello
Build 'null.example' finished after 174 milliseconds 417 microseconds.

==> Wait completed after 174 milliseconds 484 microseconds

==> Builds finished. The artifacts of successful builds are:
--> null.example: Did not export anything. This is the null builder
```

If however I specify the `-var-file` option which is a hcl file containing key/value pairs for each variable I get the expected message.
```
~>  packer build -var-file=/tmp/example/vars.hcl .
null.example: output will be in this color.

==> null.example: Running local shell script: /var/folders/vz/rv7bk6v15211jxg8q801f7kw0000gq/T/packer-shell3882044814
    null.example: Hello World
Build 'null.example' finished after 152 milliseconds 335 microseconds.

==> Wait completed after 152 milliseconds 392 microseconds

==> Builds finished. The artifacts of successful builds are:
--> null.example: Did not export anything. This is the null builder
```

I'm going to close this issue as it does not appear to be a bug. But if after you've split out your variables files you find that you are still running into issues please feel free to comment on the thread and I will gladly reopen. Cheers!

**Comment by unbreakabl3** [comment]
First of all - thank you for such deep answer. Appreciate for it.

In my case, before open this "bug" here, I did spent a few days with all official and GitHub examples and doing tests. Non one of them doesn't explain clearly, that (following your example) `variables.pkr.hcl` and `source.pkr.hcl` must to be in the same folder (or in the same file, but I do believe majority of users will want to split them). And the main word here is **must**.  

In addition, I didn't found in any documentation place explaininig, that if `variables.pkr.hcl` has  a default value, I still **must** to provide a `vars.hcl` file with the same values (or remove default values), if I want to use `-var-file` switch, because the definition of variables can be done only in a `variables.pkr.hcl`, which is located in the same folder with `source.pkr.hcl`.

A bit strange logic if we want reuse variables for example ☺️. Or I'm missing the concept of it... Can be an option as well.

For its mean we need to restructure all folder's structures we have for different OS' and do a lot of refactoring. Not your fault and thanks again for your time. With jsons the whole logic and switches meanings were a bit more clear and it worked like the logic said it should work. Buts just my humble opinion.
