### ISSUE TITLE
cd_content mentioned in docs but not in packer binary in QEMU builder

### ISSUE THREAD

**Issue by gzzchh** [hashicorp/packer#11289]
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

current packer binary could not recognize cd_content in QEMU builder
![image](https://user-images.githubusercontent.com/17796830/134964419-ceb36926-c360-4707-8eb2-529dea3c53a1.png)

build it is mentioned in docs
![image](https://user-images.githubusercontent.com/17796830/134965108-39b699df-f6b9-4a1a-9941-1efbdbf8a080.png)

#### Reproduction Steps

use any Packer 1.7.5 to build image with QEMU and cd_content
![image](https://user-images.githubusercontent.com/17796830/134964591-563c0cd1-8d4a-4baf-a49b-21f32da10e82.png)

### Packer version

1.7.5 or 1.7.6

![image](https://user-images.githubusercontent.com/17796830/134964727-a48cc185-a6bb-43ca-ae3c-02e408a215b8.png)

### Simplified Packer Buildfile

```
source "qemu" "debian_10_general" {
  # 为了获取更好的写性能这里不使用缓存
  disk_cache         = "none"
  format             = "qcow2"
  disk_compression   = true
  disk_discard       = "unmap"
  disk_detect_zeroes = "on"
  # 这次尝试用云镜像
  disk_image       = true
  use_backing_file = false
  # 准备 cloud-init 光盘
  cd_files = [
    "${path.root}/cloud-init/meta-data",
  ]
 # Here
  cd_content = {
    "user-data" = templatefile("${path.root}/cloud-init/user-data", {
      "ssh_public_key" = data.sshkey.install.public_key
    })
  }
  cd_label = "cidata"
}
```

### Operating system and Environment details

Fedora 34 x86_64

### Log Fragments and crash.log files

![image](https://user-images.githubusercontent.com/17796830/134964972-48cf00bc-55cd-42a7-8846-9c572f9f97e6.png)

**Comment by gzzchh** [comment]
As I try to build it from source, I found the QEMU plugin source does not have cd_contents 
![image](https://user-images.githubusercontent.com/17796830/134965318-f7a17a3a-bcd6-495a-bd76-be699d1f2683.png)
but it does exist in the latest source 
![image](https://user-images.githubusercontent.com/17796830/134965464-46d8123e-0f64-42a4-8d9c-3568c6acb96b.png)

So is it time for making a new plugin? Or  update the docs until plugin dependencies is up-to-date?

**Comment by nywilken** [comment]
Hi 👋 - thanks for bubbling this up. It does look like the latest changes for cd_content was added on August 9th but the plugin was last released in June of this year. We will work on cutting a release of the plugin this week to get the feature out. When available you will need to use the `packer init` command to [install the latest version](https://github.com/hashicorp/packer-plugin-qemu#installation), as the new plugin release will be separate from Packer.
