### ISSUE TITLE
Support EC2 instance store AMI creation

### ISSUE THREAD

**Issue by sonnysideup** [hashicorp/packer#113]
Currently, Packer can create EBS-backed EC2 AMIs, but it would fantastic if it could also create an instance store version of the AMI.

**Comment by Kuzmin** [comment]
@mitchellh How is the progress on the tool for creating AMIs from an ISO? I have been looking around but it does not yet seem to be supported. Do you happen to now of any other tools to accomplish this goal?

Thank you!

**Comment by copumpkin** [comment]
@mitchellh also curious about @Kuzmin's question. Is this supported? I have another tool that is already giving me an AWS-ready OS image, but I don't want to deal with all the AWS AMI shenanigans.
