### ISSUE TITLE
Packer assumes that the powershell executable is named `powershell`, which is no longer always the case

### ISSUE THREAD

**Issue by randomchance** [hashicorp/packer#11314]
#### Overview of the Issue

The Packer docker builder forcing  `--entrypoint=powershell`  is not valid for all windows images, but even on the ones it is it would be nice to have an `--entrypoint=pwsh` option.

The big issue is that starting with server 2019, `nanoserver`  based images do not have **powershell** or **WMI** at all, so a warning should probably should be added to the documentation. This is pretty unfortunate, because having a tiny pure execution environment container is great for windows versions of go executable containers like Packer, Terraform, Vault, and the rest.

I _was_ surprised that this meant you can not interact with the container in any way, not even mirror it unchanged to another repository.

> Hopefully warning in the docs will save the next person the 2-3 days I've spent on this "learning opportunity" :D

I _believe_ that having a way to force the usage of `--entrypoint=pwsh` instead would allow the usage of current PowerShell versions via ` mcr.microsoft.com/powershell:windowsservercore-*` images, and it's _possible_ that it could allow minimal usage or at least manipulation of `nanoserver` based images by using `mcr.microsoft.com/powershell:lts-nanoserver-*` as a base instead.

Access to the updated PowerShell would be a huge improvement, because the commands have improved a ton over the last several years.

#### Reproduction Steps

For the PowerShell version issue, use a `mcr.microsoft.com/powershell:windowsservercore-1909` image, and invoke a command using current version syntax.

A good example would be using the `-SkipCertificateCheck`  parameter of `Invoke-RestMethod` - I was attempting to download my org's CA cert, but it's hosted via HTTPS :( 

```powershell
Invoke-RestMethod -Uri 'github.com' -SkipCertificateCheck
```

For the nanoserver issue, just create a docker build using an images based on `mcr.microsoft.com/windows/nanoserver`, or use the example below.

### Packer version

Packer v1.7.6

> I also found this on 1.7.5, but just got around to writing it up. 

### Simplified Packer Buildfile

```hcl
packer {
  required_plugins {
    docker = {
      version = " >= 0.0.7 "
      source  = "github.com/hashicorp/docker"
    }
  }
}

source "docker" "example-windows" {
  # servercore works, but you are forced to use PowerShell 5.1, even using the 7.1 image.
  # image             = "mcr.microsoft.com/powershell:windowsservercore-1909"
  image             = "mcr.microsoft.com/powershell:lts-nanoserver-1909"
  container_dir     = "c:/Users/ContainerUser"
  commit            = true
  windows_container = true
}

build {
  name    = "windows-packer-install"
  sources = ["source.docker.example-windows"]
  post-processors {
    post-processor "docker-tag" {
      repository = "internal-registry"
      tags       = ["most-fancy","most-fancy-1909"]
    }    
  }
}
```

### Operating system and Environment details

OS, Architecture, and any other information you can provide about the
environment.

### Log Fragments and crash.log files

Using Current PowerShell version:

```powershell
    windows-packer-install.docker.packer-windows: Run command: docker run -v C:\Temp\packer\tmp077952199:c:/Users/ContainerUser -d -i -t --entrypoint=powershell -- mcr.microsoft.com/powershell:windowsservercore-1909
    windows-packer-install.docker.packer-windows: Container ID: af4279f86f709f7e10f2cf606852c7403323ea5fe4fd84648cb7f8b8a943e0ec
==> windows-packer-install.docker.packer-windows: Using dockerWindowsContainer communicator to connect:
==> windows-packer-install.docker.packer-windows: Provisioning with Powershell...
==> windows-packer-install.docker.packer-windows: Invoke-RestMethod : A parameter cannot be found that matches parameter name
==> windows-packer-install.docker.packer-windows: 'SkipCertificateCheck'.
==> windows-packer-install.docker.packer-windows: At C:\Windows\Temp\script-615f28e2-e46d-6553-8c05-9e49f45ed096.ps1:14 char:36
==> windows-packer-install.docker.packer-windows: + Invoke-RestMethod -Uri $SourceUri  -SkipCertificateCheck  -OutFile  $ ...
```

Attempting to tag a nanoserver base image:

```powershell
==> windows-packer-install.docker.example-windows: Pulling Docker image: mcr.microsoft.com/powershell:lts-nanoserver-1909
    windows-packer-install.docker.example-windows: lts-nanoserver-1909: Pulling from powershell
    windows-packer-install.docker.example-windows: Digest: sha256:d03b26fbe4ff0a145c59468c9f2d88b08146548de79e88e29df833e01d8b2dc4
    windows-packer-install.docker.example-windows: Status: Image is up to date for mcr.microsoft.com/powershell:lts-nanoserver-1909
    windows-packer-install.docker.example-windows: mcr.microsoft.com/powershell:lts-nanoserver-1909
==> windows-packer-install.docker.example-windows: Starting docker container...
    windows-packer-install.docker.example-windows: Run command: docker run -v C:\Users\<snip>\AppData\Roaming\packer.d\tmp084209967:c:/Users/ContainerUser -d -i -t --entrypoint=powershell -- mcr.microsoft.com/powershell:lts-nanoserver-1909
==> windows-packer-install.docker.example-windows: Error running container: Docker exited with a non-zero exit status.
==> windows-packer-install.docker.example-windows: Stderr: docker: Error response from daemon: container f5c78cc7c6c45429799390caec6d0b054dc9f2d93db4b47bd3dc1c2a2355857e encountered an error during hcsshim::System::CreateProcess: failure in a Windows system call: The system cannot find the file specified. (0x2)
==> windows-packer-install.docker.example-windows: [Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]
==> windows-packer-install.docker.example-windows: [Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]
==> windows-packer-install.docker.example-windows: [Event Detail: onecore\vm\compute\management\orchestration\vmhostedcontainer\processmanagement.cpp(173)\vmcomputeagent.exe!00007FF696D4B1D7: (caller: 00007FF696CFE70B) Exception(4) tid(388) 80070002 The system cannot find the file specified.
```

**Comment by lbajolet-hashicorp** [comment]
Hi @randomchance,

I saw you were active in #7164, so I think that with this issue being fixed through PR #11950, this should be closable as well?

Now with the `use_pwsh` argument for the Powershell provisioner, you should be able to change the default shell called by the provisioner.

Note that this is not yet available in Packer 1.8.3, but will be in 1.8.4. If you need it (and if you want to test it to confirm this works as you'd expect it), you may try to get the latest nightly of Packer (https://github.com/hashicorp/packer/releases/tag/nightly), where this is already available.

If you can confirm this is working as expected, we can close this issue, and officially starting with Packer 1.8.4, this will be supported!

Thanks for bringing this to our attention, and sorry for taking this long to take care of this issue.

**Comment by sarg3nt** [comment]
Is there an estimate as to when 1.8.4 will be ready?  Trying to use this now with `pwsh` and ran into this same issue.  Is there a workaround in the meantime?

**Comment by randomchance** [comment]
@sarg3nt , @lbajolet-hashicorp  Thanks for the heads up!  need it to work on windows nano images so I'll try to test it out this week.

**Comment by lbajolet-hashicorp** [comment]
Just to bounce back on this thread, 1.8.4 is slated for this week unless we hit a roadblock, so this should be officially available soon, thanks for confirming this does the trick for you!
