### ISSUE TITLE
feature: make packer validate say something on a valid config

### ISSUE THREAD

**Issue by djdta** [hashicorp/packer#11321]
Please search the existing issues for relevant feature requests, and use the
reaction feature
(https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
to add upvotes to pre-existing requests.

#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

Currently, when packer validates your configuration either json or hcl there is output if the validate had been successful or fail

#### Use Case(s)

When building an image regardless of json or hcl format, and use packer validate and see if there is any output

#### Potential configuration

```
locals {
  timestamp = regex_replace(timestamp(), "[- TZ:]", "")
}

data "amazon-ami" "basic-example" {
  filters = {
    virtualization-type = "hvm"
    name                = "ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-*"
    root-device-type    = "ebs"
  }
  owners      = ["099720109477"]
  most_recent = true
}

variable "ami_name" {}
variable "region" {}

source "amazon-ebs" "boundary" {
  ami_name      = "${var.ami_name}-${local.timestamp}"
  instance_type = "t2.micro"
  region        = "${var.region}"
  source_ami    = data.amazon-ami.basic-example.id
  ssh_username  = "ubuntu"

  tags = {
    Name       = var.ami_name
    OS_Version = "Ubuntu"
    Release    = "Latest"
  }
}

build {
  sources = [
    "source.amazon-ebs.boundary"
  ]

  provisioner "shell" {
    inline = ["sudo mkdir boundary"]
  }
  
  provisioner "file" {
    sources = ["../aws/configs/boundary-controller.hcl",
    "../aws/configs/postgres.sh",
    "../aws/configs/postgresql.conf",
    "../aws/configs/boundary_controller_prod_setup.sh",
    "../aws/configs/boundary-vault.hcl",
    "../aws/configs/vault_setup.sh",
    "../aws/configs/vault_client_setup.sh",
    "../aws/configs/vault.hcl"]
    destination = "/tmp/"
  }
```

**Comment by azr** [comment]
Hello @djdta, weird, this works on my machine, your example missed the last closing bracket. So I got:

```shellsession
> packer validate test.pkr.hcl
Error: Argument or block definition required

  on test.pkr.hcl line 54:

An argument or block definition is required here.


exit status 1
```

Then after fixing it:

```shellsession
> packerdev validate test.pkr.hcl
Error: Unset variable "ami_name"

A used variable must be set or have a default value; see
https://packer.io/docs/templates/hcl_templates/syntax for details.

Error: Unset variable "region"

A used variable must be set or have a default value; see
https://packer.io/docs/templates/hcl_templates/syntax for details.


exit status 1
```

What kind of terminal and terminal configuration are you using ?
