### ISSUE TITLE
"Map type constructor requires one argument specifying the element type."  when using map variable type and HCL

### ISSUE THREAD

**Issue by inflatador** [hashicorp/packer#11354]
#### Overview of the Issue
"Map type constructor requires one argument specifying the element type."  when using map variable type and HCL

#### Reproduction Steps

Copy-paste [the example map variable from the packer documentation](https://www.packer.io/guides/hcl/variables#maps) into your packer HCL file.

Error returned: "The map type constructor requires one argument specifying the element type."

### Packer version

1.7.7

### Simplified Packer Template

```
variable "amis" {
  type = map
  default = {
    "us-east-1" = "ami-b374d5a5"
    "us-west-2" = "ami-4b32be2b"
  }
}

```
### Operating system and Environment details

Fedora release 34 (Thirty Four) , kernel 5.14.11-200.fc34.x86_64

### Workaround
Digging around, I found [this terraform thread ](https://github.com/hashicorp/terraform/issues/19141)which suggests a similar problem. Explictly defining the type of subelements seems to work:

```
variable "amis" {
  type = map(string)
  default = {
    "us-east-1" = "ami-b374d5a5"
    "us-west-2" = "ami-4b32be2b"
  }
}
```

**Comment by azr** [comment]
Thanks !
