### ISSUE TITLE
Packer insist on putting "Packer Builder" tag

### ISSUE THREAD

**Issue by grumpper** [hashicorp/packer#11370]
#### Overview of the Issue

When I am running packer build it puts `Name = "Packer Builder"` on the temp instance used for building and on the AMI itself. This happens when I don't put `tags` and `run_tags` at all or even when explicitly set them to be `{}`.

#### Reproduction Steps

Define packer template and setup the `amazon-ebs` source.
Remove any tagging config from the source OR set it to `{}` explicitly.
Use the template to build something and observe how both the instance and the AMI created from it are tagged nevertheless.

### Packer version

Tested on packer `1.7.7` and `1.7.8`

### Simplified Packer Template
```
source "amazon-ebs" "stuff" {
  ami_name                      = "${var.ami_base_name}-${var.source_version}-hvm-${formatdate("YYYYMMDD", timestamp())}-x86_64-gp2"
/.../
  tags          = {}
  run_tags   = {}
/.../
}

build {
  sources = [
    "source.amazon-ebs.stuff.id"
  ]

  provisioner "shell" {
    inline = [
      "echo \"some script stuff\""
    ]
  }
}

### Operating system and Environment details

macOS 12.0.1 (x86_64)

### Log Fragments and crash.log files

no errors in logs; it's just that this behavior is nonsense cause you have means to control the tags you want but you actually don't since packer decides to put one anyway no matter your config.
When building an AMI for clients who do not give permissions to tag AMIs since they want to control that themselves the build directly errors out. And there is no way to work around that.

**Comment by nywilken** [comment]
For context this default tag was added https://github.com/hashicorp/packer/pull/5196. Need to figure out if there was a reason for adding this default tag before removing.
