### ISSUE TITLE
Attempting to build a Windows host using "communicator = none", packer crashes

### ISSUE THREAD

**Issue by haggis-supper** [hashicorp/packer#11396]
I have a secure windows image where winRM is disabled. 
To get around this issue I was attempting to do the following
1. Get packer to automatically create a log file when executed using  "export PACKER_LOG=1;export PACKER_LOG_PATH=newlog; packer ..."
2. Use a local shell script to pull the temporary packer build hostname and resource group from the created log 

  "provisioners": [
   {
      "type": "shell-local",
      "execute_command": ["bash", "-c", "{{.Script}} -L newlog"],
      "script": "./scripts/test.sh"
  }]
 3. As part of the log, use the "az vm run-command invoke --command-id RunpowerShellScript " to run commands on the host using the hostname and resourcename my script collects.

This should allow me to enable WinRm using powershell command and then sysprep the image after.

By default when you build a windows box the communicator is set to WinRM, if i set it to "none" packer crashes.

Attached is the "packer.log" file the crash create
[crash.log](https://github.com/hashicorp/packer/files/7538413/crash.log)

**Comment by nywilken** [comment]
Hi @haggis-supper, the Azure builder in its current state doesn't do much when the communicator is set to "none". In fact it fails - I opened an issue for the Azure builder a few weeks ago https://github.com/hashicorp/packer-plugin-azure/issues/158. 

I believe prior to me opening that bug the builder would crash, which I fixed. Have you tried downloading the the latest version of the Azure plugin to see if you still encounter the crash? 

You can also update to the latest version of Packer to get the latest Azure builder, which is bundled with Packer in 1.7.8. 

If after updating if you no longer encounter the crash I will close this issue and maybe use your use case to determine the next step for the open issue https://github.com/hashicorp/packer-plugin-azure/issues/158. Please feel free to leave any comments on the 158.
