### ISSUE TITLE
validate doesn't uncover error in local variable definition

### ISSUE THREAD

**Issue by ethanmdavidson** [hashicorp/packer#11397]
#### Overview of the Issue

`validate` fails to uncover an error in the local variable definition if the local variable is referenced anywhere in the file. Instead, it displays an error at variable usage that "This object does not have an attribute named [x]".

#### Reproduction Steps

Create a packer template like the following:
```hcl
locals {
  timestamp = formatdate("YYYY-MM-DDX", timestamp())
  other_local = "test-${local.timestamp}"
}
```

and run `packer validate` on it. This will report an error on line 3 that `This object does not have an attribute named "timestamp"`. 
Commenting out the timestamp variable usage will show the true error:

```hcl
locals {
  timestamp = formatdate("YYYY-MM-DDX", timestamp())
  #other_local = "test-${local.timestamp}"
}
```

`packer validate` will now show the underlying issue on line 2: `Invalid value for "format" parameter: invalid date format verb "X"`. 

### Packer version

1.7.8

### Simplified Packer Template

```hcl
locals {
  timestamp = formatdate("YYYY-MM-DDX", timestamp())
  other_local = "test-${local.timestamp}"
}
```

Expected behavior is for `validate` to either report both errors, or report only the "root cause" error (in this case, invalid date format).

### Operating system and Environment details

Ubuntu 20.04.2

### Log Fragments and crash.log files

<details>

```
edavidson@edavidson-thinkpad:~$ PACKER_LOG=1 packer validate test.pkr.hcl 
2021/11/15 12:03:31 [INFO] Packer version: 1.7.8 [go1.17.2 linux amd64]
2021/11/15 12:03:31 Old default config directory found: /home/edavidson/.packer.d
2021/11/15 12:03:31 [TRACE] discovering plugins in /usr/bin
2021/11/15 12:03:31 Old default config directory found: /home/edavidson/.packer.d
2021/11/15 12:03:31 [TRACE] discovering plugins in /home/edavidson/.packer.d/plugins
2021/11/15 12:03:31 [DEBUG] Discovered plugin: git-datasource = /home/edavidson/.packer.d/plugins/packer-plugin-git-datasource
2021/11/15 12:03:31 found external [local] datasource from git-datasource plugin
2021/11/15 12:03:31 [TRACE] discovering plugins in .
2021/11/15 12:03:31 [INFO] PACKER_CONFIG env var not set; checking the default config file path
2021/11/15 12:03:31 [INFO] PACKER_CONFIG env var set; attempting to open config file: /home/edavidson/.packerconfig
2021/11/15 12:03:31 [WARN] Config file doesn't exist: /home/edavidson/.packerconfig
2021/11/15 12:03:31 Old default config directory found: /home/edavidson/.packer.d
2021/11/15 12:03:31 [INFO] Setting cache directory: /home/edavidson/.cache/packer
2021/11/15 12:03:31 Old default config directory found: /home/edavidson/.packer.d

  on test.pkr.hcl line 3:
  (source code not available)

This object does not have an attribute named "timestamp".

Error: Unsupported attribute
2021/11/15 12:03:31 [INFO] (telemetry) Finalizing.

  on test.pkr.hcl line 3:
  (source code not available)

This object does not have an attribute named "timestamp".


2021/11/15 12:03:32 waiting for all plugin processes to complete...
```

</details>

**Comment by nywilken** [comment]
Thanks for calling this out. We will take a look to see how we can best handle this issue.

**Comment by teddylear** [comment]
@nywilken I can try to take a look at this if that's alright.

**Comment by teddylear** [comment]
@nywilken Would a viable solution to this be printing the holy list of validation errors for a file rather than the last like above? I would assume that would resolve this issue (and issues like it). However that would be a pretty big change to validation, so wanted to get your thoughts before implementing.

**Comment by teddylear** [comment]
Appears that the issue is located [here in packer](https://github.com/teddylear/packer/blob/master/hcl2template/types.packer_config.go#L246-L249) where if there is a circular dependency then one of the issue is added instead of all of the errors with locals. I'll update to print all the errrors in locals so that the issue can be more obvious to the end user.

**Comment by teddylear** [comment]
Added a PR, please let me know if I should change anything. Thanks!

**Comment by nywilken** [comment]
@teddylear thanks for the work in #11527. With the latest changes in #11534 it is safe to say that this issue has been resolved. I included the new output that will get generated for the example configuration in this ticket. Thanks for reporting @ethanmdavidson 

```
~>  packer validate /tmp/source.pkr.hcl
Error: Invalid function argument

  on /tmp/source.pkr.hcl line 2:
  (source code not available)

Invalid value for "format" parameter: invalid date format verb "X".

Error: Unsupported attribute

  on /tmp/source.pkr.hcl line 3:
  (source code not available)

This object does not have an attribute named "timestamp".
```
