### ISSUE TITLE
Allow to use build variables as post processor name

### ISSUE THREAD

**Issue by pjmcquade** [hashicorp/packer#11411]
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Fix in Version 1.7.8 claims to allow build variables in post-processors

From: https://github.com/hashicorp/packer/pull/11323

Looking to use ${build.name} in a post-processor artifice and amazon-import but packer errors out with:

````
$ packer version
Packer v1.7.8
````

Source builder:

````
build {
  name = "threaded_import_to_aws"
  #sources = ["source.null.vmimport"]

  dynamic "source" {
    for_each = var.images
    labels   = ["source.null.vmimport"]

    content {
      name = source.value.rhel_version
    }

  }

  post-processor "artifice" {
    # name = "${var.foo}" # this passed "packer validate"
    # name = "myartifice"  # this passed "packer validate ."
    name  = "setting the ${build.name}"  # this fails "packer validate"
    files = ["${var.vm_export_directory}/${local.prefix}-${build.name}-server-disk-0.${var.vm_disk_format}"]   # this passes; is ${build.name} valid or erroneously not flagged as an error?
  }

}
````

So with ``name = "${build.name}"`` in the artifice, the error is:

````
Error: Unsupported attribute

  on builders.pkr.hcl line 133:
  (source code not available)

This object does not have an attribute named "name".

Error: Unsuitable value type

  on builders.pkr.hcl line 133:
  (source code not available)

Unsuitable value: value must be known
````
#### Reproduction Steps

Using packer v1.7.8, and a simplified template from the above, this works:

````
source "null" "example" {
  communicator = "none"
}

build {
  name    = "example"
  sources = ["source.null.example"]

  post-processor "artifice" {
    name = "myartifice"
    files   = ["dummy"]
  }
}
````

this will fail:

````
source "null" "example" {
  communicator = "none"
}

build {
  name    = "example"
  sources = ["source.null.example"]

  post-processor "artifice" {
    name = "${build.name}"
    files   = ["dummy"]
  }
}
````

### Packer version

````
$ packer version
Packer v1.7.8
````
### Simplified Packer Template

If the file is longer than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/) of the log or use the [Github detailed
format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d)
instead of posting it directly in the issue.

### Operating system and Environment details

RHEL 8.4

### Log Fragments and crash.log files

N/A

**Comment by nywilken** [comment]
Thanks for bubbling this up I had an opportunity to look into this issue and see that support for `build.name` and `source.name` are not yet known at the time the name for the post-processor is being parsed, which is why you are seeing this error.

The values can be used in the body of the post-processor because at runtime the values for build.name and source.name are set prior to executing the post-processor, which happens a bit after the initial parsing.  Interesting enough if you set `name = "{{packer_build_name}}"` and run your build the correct value gets parsed correctly. 

I will work on getting a fix out for the next release.
