### ISSUE TITLE
Creating Image rfom Running VM

### ISSUE THREAD

**Issue by niravgshah28** [hashicorp/packer#11414]
Hi All,

If anyone has created and use packer to create images froma running VM for IAC purpose.

Regards
Nirav

**Comment by azr** [comment]
@niravgshah28, not sure what you are trying to achieve, but on amazon, the `chroot` builder does something like that. 

Don't hesitate using our [community forum](https://discuss.hashicorp.com/c/packer/23) to ask how to do things ! 🙂
