### ISSUE TITLE
[vsphere-iso] Not able to remove Network Adapter after creation

### ISSUE THREAD

**Issue by Securitybits-io** [hashicorp/packer#11427]
#### Description
Using Packer v1.7.8, to create a ubuntu 20.04 template on a vcenter server, to be managed by a Saltstack Master!
After, creating the template and spinning up the VM with a Map for Salt, the problem is that there's multiple NICs configured (one from template, and one from Salt-cloud)

The feature request is to be able, after the VM is created to modify the hardware, in this case the specified or all NICs

#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

**Comment by tenthirtyam** [comment]
@Securitybits-io - this sounds like a use case for a post-processor rather than the builders in this plugin. It’s also seems like a desired state use case which Terraform could address.

Ryan
