### ISSUE TITLE
can't use hcl variable files as described in docs

### ISSUE THREAD

**Issue by kidbrax** [hashicorp/packer#11436]
#### Overview of the Issue

Seems to be the same problem as [issue 8781](https://github.com/hashicorp/packer/issues/8781)

I get an error when using `packer build -var-file=vars/dev2-govcloud.pkrvars.hcl packer_templates/base-ansible.json`

variable file contains:

```
destination_regions = "us-gov-east-1"
tag_lifecycle = "dev"
```

but I get error:

`Error reading variables in 'vars/dev2-govcloud.pkrvars.hcl': invalid character 'd' looking for beginning of value
`
#### Reproduction Steps

use an hcl file with variables in it and reference it using -var-file

### Packer version

1.7.8

### Operating system and Environment details

Mac OS

**Comment by nywilken** [comment]
Hi @kidbrax thanks for reaching out. This can be a little confusing as HCL2 templates support variable files in both JSON and HCL. But when using a JSON Packer build template, like you are, the variables file must also be in JSON. 

The error you are seeing is the JSON Parse failing to parse a HCL2 file. Packer will enter JSON parsing mode when the template is in the JSON format, and it will enter the HCL2 parsing mode when the template is in HCL. 

You can resolve this issue by converting your dev2-govcloud.pkvars.hcl file to dev2-govcloud.json with the following contents:
```
{
 "destination_regions"" "us-gov-east-1",
"tag_lifecycle":"dev"
}
```

Or you can convert your build file to HCL via the hcl2_upgrade command. This might be a little more work but will allow you to take full advantage of all HCL functionality. 

```
packer hcl2_upgrade packer_templates/base-ansible.json
### this will create a hcl version of the JSON file named packer_templates/base-ansible.json.pkr.hcl
```

I am going to close this issue as it does not appear to be a bug. But after making the suggested changes you find that you are still running into issues or think this should be a bug. Please leave a comment on this issue for us to review. Cheers!

**Comment by kidbrax** [comment]
I would suggest adding that to the documentation. That you can't mix json with HCL.
