### ISSUE TITLE
Working examples for unattended OS installations with CDROM/USB source

### ISSUE THREAD

**Issue by synergiator** [hashicorp/packer#11443]
Packer is a great tool, typically for starters it's always great to have a working [example](https://www.packer.io/guides/automatic-operating-system-installs/preseed_ubuntu) like in the Guides.

The key component to share preseed URL is to use HTTP connection. Best way and very elegant of Packer is to launch a temporary HTTP server.  In a local setup definitely not a problem. In some (productive) environments it's however not possible due to networking setup. Setting up additional external source is then additional work.

In many examples seen otherwise around people choose mounting a virtuall floppy drive. However this is not supported in up-to-date Linux kernel: floppy is legacy also when a cloud-hosted floppy is indeed in my perception a truly vintage thing.

So far I am not able to find a working example for Debian/RockyLinux to mount a CDROM/USB.

While I see this is also up to specific plugin vendors, I consider supporting CDROM/USB is an important acceptance criteria.

**Comment by tenthirtyam** [comment]
Depends on the builder being used. 

The [vmware-samples/packer-examples-for-vsphere](https://github.com/vmware-samples/packer-examples-for-vsphere) project that I maintain defaults to HTTP but it also includes a source override to  toggle to cdrom or floppy depending on the OS support.

Ubuntu, Rocky, Alma, CentOS, and RHEL examples are included alongside Photon which does not yet support secondary cdrom or floppy.

Ryan

**Comment by wixregiga** [comment]
@tenthirtyam I've made an ISO using cd_files which is uploaded to vCenter. Packer successfully mounts that ISO as the second cdrom.

But when I go to install the OS it either uses the first cdrom or errors out. 

Im building and using packer from home so http isn't an option.

Any idea why this could be happening,?

**Comment by tenthirtyam** [comment]
Hi @wixregiga, 

You don't need to manually create the ISO - Packer will create the ISO, upload it to the `packer_cache` path, and then attach/detach during the build process. 

Additionally, when building a Windows image with Packer the HTTP method is not used.

Feel free to take a look at my project that includes examples for Windows Server ('16, '20, '22) and Windows (10, 11). There is a very detailed **README**.

[vmware-samples/packer-examples-for-vsphere](https://github.com/vmware-samples/packer-examples-for-vsphere)

You can use the project as-is or as inspiration for your requirements.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by tenthirtyam** [comment]
cc @nywilken

**Comment by tenthirtyam** [comment]
Hi @nywilken - I think this issue can be closed based on the thread contents.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by tenthirtyam** [comment]
cc @nywilken @lbajolet-hashicorp for closure

**Comment by lbajolet-hashicorp** [comment]
Agreed, this can be closed for now, there's probably something we can do on the documentation side to limit that category of usage questions, but I'm not sure tracking it here will be helpful.
