### ISSUE TITLE
[1.7.x]  -debug argument does not pause between provisioners

### ISSUE THREAD

**Issue by lmayorga1980** [hashicorp/packer#11457]
#### Overview of the Issue

In the past, the `-debug` used to pause between provisioners and now it executes all the provisioners without any pause.

#### Reproduction Steps

Add multiple provisioners and run packer in **debug** mode `packer build -debug template.hcl`

### Packer version

`packer 1.78`

**Comment by nywilken** [comment]
Thanks for reporting this issue we will take a look. As a temporary workaround you can use the breakpoint provisioner to pause provisioners. You can find an example below: 

```hcl
source "null" "example" {
  communicator = "none"
}

build {
  sources = ["source.null.example"]

  provisioner "shell-local" {
    inline = ["echo hi"]
  }
  provisioner "breakpoint" {
    disable = false
    note    = "this is a breakpoint"
  }
  provisioner "shell-local" {
    inline = ["echo hi 2"]
  }
}
```
