### ISSUE TITLE
What exactly the Restart_Check_Command does? 

### ISSUE THREAD

**Issue by olandese** [hashicorp/packer#11467]
Hello,

I would like to get a better explanation of the Restart_Check_Command option.
I don't really understand how it works and why is sometimes needed.

Does the command run before the shutdown or after?
What does it expect, every script/command with an exit 0 code, or a specific message? 

Here I have a couple of examples:

`"restart_check_command": "powershell -command \"& {if ((-not (Get-Process TiWorker.exe -ErrorAction SilentlyContinue)) -and (-not [System.Environment]::HasShutdownStarted) ) { Write-Output 'Restart complete' }}\""`

` "restart_check_command": "powershell -command \"& {while ( (Get-WindowsOptionalFeature -Online -FeatureName Containers -ErrorAction SilentlyContinue).State -ne 'Enabled' ) { Start-Sleep 30; Write-Output 'InProgress' }}\""`

Is the output important? 

Maybe a bit more explanation in the documentation could be handy :)

Thank you in advance!

**Comment by azr** [comment]
Hey @olandese, the [doc](https://www.packer.io/docs/provisioners/windows-restart#restart_check_command) says:

>  A command to execute to check if the restart succeeded. This will be done in a loop.
> Example usage:
> ```hcl
> provisioner "windows-restart" {
>   restart_check_command = "powershell -command \"& {Write-Output 'restarted.'}\""
> }
> ```

From reading this, I think this basically will retry this command up until it returns with no error.
The default command being: 

https://github.com/hashicorp/packer/blob/87ba7258b352d634b95f7e506685a725d8e46a45/provisioner/windows-restart/provisioner.go#L26

You can see the loop in code here:

https://github.com/hashicorp/packer/blob/87ba7258b352d634b95f7e506685a725d8e46a45/provisioner/windows-restart/provisioner.go#L224-L233

`RunWithUi` starts the command (and wraps stdout//stderr to the output). Then the error from it is checked.
