### ISSUE TITLE
Input Artifacts with keep_input_artifact=false shouldn't be sent to HCP Packer

### ISSUE THREAD

**Issue by nywilken** [hashicorp/packer#11462]
There is a bug where setting keep_input_artifact=false registers the builder output as an image even though it has been deleted.

This will be a little tricky to address since keep_input_artifact is set on the next post processor, not the current one. We don't have a DAG so parsing whether an artifact should be saved may be challenging.

**Comment by azr** [comment]
I think that this should be achievable without the dag work (in a complex manner).

**Comment by nywilken** [comment]
Closed by #11967
