### ISSUE TITLE
Disable winrm after building is successful

### ISSUE THREAD

**Issue by jbpoint** [hashicorp/packer#11476]
Is there a good way to disable winrm when building is successful? 

Did it with a powershell script, but after the script is executed packer cant send the shutdown command, so the building failes. 
Any suggestions?

**Comment by tenthirtyam** [comment]
The correct project for this issue would be the [hashicorp/packer-plugin-vsphere](https://github.com/hashicorp/packer-plugin-vsphere/issues/) based on the opened [discussion](https://github.com/vmware-samples/packer-examples-for-vsphere/discussions/147#discussioncomment-1891695).

Ryan

**Comment by nywilken** [comment]
Hi @tenthirtyam thanks for the ping on this issue and for working through the response on the discussion forum. Since the issue has been resolved [here](https://github.com/vmware-samples/packer-examples-for-vsphere/discussions/147#discussioncomment-1891695) I'm going to close the issue.
