### ISSUE TITLE
Problem with AWS sysprep preparation

### ISSUE THREAD

**Issue by Karo1996qwe** [hashicorp/packer#11472]
I performed a code  responsible for configure a Windows instance using EC2Launch.

```
try {
  $p = "C:\ProgramData\Amazon\EC2-Windows\Launch\Scripts"
  Push-Location
  Set-Location -path $p
  Invoke-Expression -command ".\InitializeInstance.ps1 -Schedule" 
  Invoke-Expression -command ".\SysprepInstance.ps1" 

  Pop-Location
  Write-Host "Sysprep preparated" 
}
catch { 
  Write-Host "Error: during aws sysprep preparation an error occurred that could not be resolved."
  Write-Host "Exit operation"
  exit
}
```
and I got a message like: 
![image](https://user-images.githubusercontent.com/96426177/147463056-117fd509-b242-4878-8ff9-c78c54ad5894.png)

If anyone had such a problem?
It looks like problem with: SysprepInstance script.ps1.

**Comment by nywilken** [comment]
Hi @Karo1996qwe I'm not too familiar with the use of Ec2Launch for running sysprep, but I do wonder if executing it during the initialization of the instance is causing an issue. 

Have you tried using the power-shell provisioner for executing these scripts? 

An example can be found [here](https://www.packer.io/plugins/builders/amazon/ebs#windows-2016-sysprep-commands-for-amazon-windows-amis-only)

That said, if you end up needing more help with this kind of initial configuration, the mailing list or [community forum](https://www.packer.io/community) are generally more useful. Issues opened here on the Packer issue tracker are only viewed by a small handful of developers who work on the tool, and we don't always have the most depth or experience when it comes to custom issues with particular build configurations.
