### ISSUE TITLE
Multiple Disks Virtual Box

### ISSUE THREAD

**Issue by digitaljedi2** [hashicorp/packer#1147]
I'd like to be able to create multiple disks or a secondary disk of a VMDK type.

VBoxManage createhd --format VMDK --filename "second_disk.vmdk" --variant STREAM --size 100

**Comment by splashx** [comment]
In case of vmware-iso, what would be the recommendation?

**Comment by mgluhic10** [comment]
Hi, 

Is there any update how to add on vmware-iso two disks?

Thanks! 

Milan
