### ISSUE TITLE
isotime in a user variable is rendered per builder in parallel builds, giving off by one errors

### ISSUE THREAD

**Issue by gregburek** [hashicorp/packer#1153]
I'm using a packer json file with multiple builders for different architectures. The `created_at` user variable is meant to tag each image and group the artifact AMIs of each packer run for promotion of AMIs in all regions and architectures to production. I am using `packer build packer.json` to build these AMIs in parallel. 

I have found, however, that sometimes one build will be off by one second in the `created_at` tag, which breaks the group:

```
ami-xxxxxxxx: architecture => x86_64, created_at => 2014-05-07T23:00:32Z
ami-xxxxxxxx: architecture => x86_64hvm, created_at => 2014-05-07T23:00:33Z,
ami-xxxxxxxx: architecture => i386, created_at => 2014-05-07T23:00:33Z
```

I believe that this is symptomatic of `isotime` being resolved for each builder individually as the builds are started in parallel. 

I am moving to setting the `created_at` tag in the environment at the start of the build for more uniform tagging, but I wanted to submit this issue, as it was confusing that the template was being rendered multiple times. 

My build json file, truncated for clarity:

```
{
  "builders": [
    {
      "access_key": "{{user `aws_access_key`}}",
      "ami_name": "{{ uuid }}",
      "name": "aws-ebs-x86_64",
      ...
      "tags": {
        "architecture": "x86_64",
        "created_at": "{{ user `created_at` }}",
       ...
      },
      "type": "amazon-ebs"
    },
    {
      "access_key": "{{user `aws_access_key`}}",
      "ami_name": "{{ uuid }}",
      "name": ""aws-ebs-x86_64-HVM"",
      ...
      "tags": {
        "architecture": "x86_64hvm",
        "created_at": "{{ user `created_at` }}",
       ...
      },
      "type": "amazon-ebs"
    },
    {
      "access_key": "{{user `aws_access_key`}}",
      "ami_name": "{{ uuid }}",
      "name": "aws-ebs-i386",
      ...
      "tags": {
        "architecture": "i386",
        "created_at": "{{ user `created_at` }}",
       ...
      },
      "type": "amazon-ebs"
    }
  ],
  '"variables": {
    "aws_access_key": "{{ env `AWS_ACCESS_KEY_ID` }}",
    "created_at": "{{ isotime }}"
  }
}
```

**Comment by X44049** [comment]
Hi, I am creating packer ami image in template i mentioned ami-name as : "ami_name": "{{ user `name`}}_{{ timestamp }}", . In place of time-stamp in ami-name on aws I am able to see unknown 10 digit number ex: '1432756324'. Could you please let me know, how ami-name in aws created.
