### ISSUE TITLE
skip_create_image option for cloud platforms other than Google

### ISSUE THREAD

**Issue by allie-fowler** [hashicorp/packer#11550]
#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

I would love to use a skip_create_image option for azure_arm or aws builders, with Azure being the most pressing need at the moment.

It appears this option for Google Cloud was created in [10496](https://github.com/hashicorp/packer/pull/10496)

#### Use Case(s)

Similar to the use case described in [7209](https://github.com/hashicorp/packer/issues/7209).  I too wish to keep the artifact in only 1-2% of my uses over the past several years.

**Comment by nywilken** [comment]
Hi @allie-fowler I'm going to move this request to the Azure builder. This feature does exist for the AWS builder but is has a slightly different name https://www.packer.io/plugins/builders/amazon/ebs#skip_create_ami
