### ISSUE TITLE
http data source

### ISSUE THREAD

**Issue by elreydetoda** [hashicorp/packer#11552]
#### Description

Similar to [Terraform's http data source](https://registry.terraform.io/providers/hashicorp/http/latest), it would be handy to have an http data source inside of the HCL for packer.

#### Use Case(s)

Ideally you'd be able to query API endpionts and other things with it, allowing your HCL to dynamically change based on the API results.

My specific use case is I'd like to submit a template to [bento project's CentOS Stream templates](https://github.com/chef/bento/tree/main/packer_templates/centos), and because they've had issues with things being more dynamic [with the stream update](https://github.com/chef/bento/pull/1368) it's been hard to have something consistently work.  We already worked up stream once to try and get a [more "official" solution](https://github.com/chef/bento/pull/1361#issuecomment-852475135), but it has broken again [with the stream 9 build](https://github.com/chef/bento/issues/1391).

#### Potential configuration

same as the terraform one

```
data "http" "example" {
  url = "https://checkpoint-api.hashicorp.com/v1/check/terraform"

  # Optional request headers
  request_headers = {
    Accept = "application/json"
  }
}
```

#### Potential References
- https://registry.terraform.io/providers/hashicorp/http/latest
- https://github.com/hashicorp/terraform-provider-http

**Comment by nywilken** [comment]
Thanks for opening up this feature request. This seems like a good datasource to have. I don't think this is something that we would be able to get to any time soon. But we will gladly review a PR if you were interested in adding the feature.

 I'm going to label this as a help-wanted issue in case other members of the community are also interested in help out.

**Comment by teddylear** [comment]
@nywilken Created PR. Please let me know if I should change anything, looks like it's pending a vercel deployment. Thanks!

**Comment by s-fuj** [comment]
@teddylear may i know if you are still working on this request?  I really want to have this new feature as my packer script is waiting for it.

**Comment by teddylear** [comment]
@s-fuj Yup, still working on issue. Unfortunately I'm still waiting on maintainers to trigger CI build and leave any feedback. @nywilken Any update on triggering CI builds?

**Comment by elreydetoda** [comment]
Thank you @teddylear for the contribution! I wish I could've been more help, but I've never done golang before 😅
