### ISSUE TITLE
Docker Builder + Salt Provisioner not compatible?

### ISSUE THREAD

**Issue by ghost** [hashicorp/packer#1156]
I'm having trouble running a Docker builder along with a Salt provisioner. It's not successfully copying over salt-related files, etc. It occurred to me that maybe Salt doesn't always work with Docker. Salt is trying to run commands on Docker, but Docker images are built from Dockerfiles. So, I'm wondering how Salt provisioning gets translated in to a Dockerfile on the image.

Shell provisioning seems to work fine with the Docker builder, which would translate over to the Dockerfile equivalent well.

The type of errors I keep getting:

``` shell
==> docker: Provisioning with Salt...
    docker: Installing Salt with command &{wget -O - http://bootstrap.saltstack.org | sudo sh -s  <nil> <nil> <nil> %!s(bool=false) %!s(int=0) %!s(chan struct {}=<nil>) {%!s(int32=0) %!s(uint32=0)}}
    docker: bash: sudo: command not found
    docker: --2014-05-10 18:52:46--  http://bootstrap.saltstack.org/
    docker: Resolving bootstrap.saltstack.org (bootstrap.saltstack.org)...
    docker: 74.208.29.198
    docker: Connecting to bootstrap.saltstack.org (bootstrap.saltstack.org)|74.208.29.198|:80... connected.
    docker: HTTP request sent, awaiting response... 302 Found
    docker: Location: https://raw.github.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh [following]
    docker: --2014-05-10 18:52:51--  https://raw.github.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh
    docker: Resolving raw.github.com (raw.github.com)... 199.27.72.133
    docker: Connecting to raw.github.com (raw.github.com)|199.27.72.133|:443... connected.
    docker: HTTP request sent, awaiting response... 301 Moved Permanently
    docker: Location: https://raw.githubusercontent.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh [following]
    docker: --2014-05-10 18:52:52--  https://raw.githubusercontent.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh
    docker: Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 199.27.72.133
    docker: Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|199.27.72.133|:443... connected.
    docker: HTTP request sent, awaiting response...
    docker: Creating remote directory: /tmp/salt
    docker: Uploading local state tree: /vagrant/salt/
    docker: Moving /tmp/salt/states to /srv/salt
    docker: bash: sudo: command not found
==> docker: Killing the container: 7ee1953b2d497585a317a0ac904d1420a41571e2f840ea35b2efb912b34f4982
Build 'docker' errored: Unable to move /tmp/salt/states to /srv/salt: &{%!d(string=Bad exit status: 127)}

==> Some builds didn't complete successfully and had errors:
--> docker: Unable to move /tmp/salt/states to /srv/salt: &{%!d(string=Bad exit status: 127)}

==> Builds finished but no artifacts were created.
```

Also I'm seeing errors like, `docker: bash: sudo: command not found`. I've tried installing sudo from a bash script. I'm using the "ubunto:13.10" image for my Docker build, but I wonder if there's a better base image that would be more suitable for packer-docker builds?

**Comment by hokadiri** [comment]
Hi @rvangundy, 
Please were you able to solve this issue, i'm having the exact same thing creating docker images with Chef provisioner?

{
  "builders": [{
    "type": "docker",
    "image": "centos:6",
    "export_path": "image2.tar"
  }],
  "provisioners" : [
    {
      "type": "shell",
      "inline": ["yum update -y", "yum install -y sudo openssh"]
    },
    {
      "type": "chef-client",
      "staging_directory": "/etc/chef",
      "server_url": "<my chef server>",
      "validation_client_name": "chef-validator",
      "validation_key_path": "/path/to/chef-validator.pem",
      "install_command": "curl -L https://www.opscode.com/chef/install.sh | bash -s -- -v 11.18.12",
      "chef_environment": "it_di01",
      "run_list": "role[base-docker]",
      "node_name": "base_node"
    }]
}

$ ~/Downloads/packer -v
1.0.0
$ docker -v
Docker version 17.03.1-ce, build c6d412e

Running on Mac OSX

**Comment by hokadiri** [comment]
For me was because of this line chef which creates local users
include_recipe "user::data_bag"

  docker: [2017-04-08T17:11:59+00:00] INFO: Processing user_account[localdeployautomation] action create (user::data_bag line 38)
    docker: [2017-04-08T17:11:59+00:00] INFO: Processing user[localdeployautomation] action create (/var/chef/cache/cookbooks/user/providers/account.rb line 143)
    docker: [2017-04-08T17:11:59+00:00] INFO: user[localdeployautomation] created
    docker: [2017-04-08T17:11:59+00:00] INFO: Processing directory[/home/localdeployautomation] action create (/var/chef/cache/cookbooks/user/providers/account.rb line 169)
    docker: [2017-04-08T17:11:59+00:00] INFO: directory[/home/localdeployautomation] mode changed to 2755
    docker: [2017-04-08T17:11:59+00:00] INFO: Processing directory[/home/localdeployautomation/.ssh] action create (/var/chef/cache/cookbooks/user/providers/account.rb line 185)
    docker: [2017-04-08T17:11:59+00:00] INFO: directory[/home/localdeployautomation/.ssh] created directory /home/localdeployautomation/.ssh
    docker: [2017-04-08T17:11:59+00:00] INFO: directory[/home/localdeployautomation/.ssh] owner changed to 1888001044
    docker: [2017-04-08T17:11:59+00:00] INFO: directory[/home/localdeployautomation/.ssh] group changed to 500
    docker: [2017-04-08T17:11:59+00:00] INFO: directory[/home/localdeployautomation/.ssh] mode changed to 700
    docker: [2017-04-08T17:11:59+00:00] INFO: Processing execute[create ssh keypair for localdeployautomation] action run (/var/chef/cache/cookbooks/user/providers/account.rb line 223)
    docker: [2017-04-08T17:11:59+00:00] INFO: execute[create ssh keypair for localdeployautomation] ran successfully
    docker: [2017-04-08T17:11:59+00:00] INFO: Processing user[localdeployautomation] action nothing (/var/chef/cache/cookbooks/user/providers/account.rb line 143)
    docker: [2017-04-08T17:11:59+00:00] INFO: Processing directory[/home/localdeployautomation] action nothing (/var/chef/cache/cookbooks/user/providers/account.rb line 169)
    docker: [2017-04-08T17:11:59+00:00] INFO: Processing directory[/home/localdeployautomation/.ssh] action nothing (/var/chef/cache/cookbooks/user/providers/account.rb line 185)
    docker: [2017-04-08T17:11:59+00:00] INFO: Processing execute[create ssh keypair for localdeployautomation] action nothing (/var/chef/cache/cookbooks/user/providers/account.rb line 223)
    docker: [2017-04-08T17:11:59+00:00] INFO: Processing group[wheel] action create (user::data_bag line 55)
    docker: [2017-04-08T17:12:00+00:00] INFO: group[wheel] altered

**Comment by hokadiri** [comment]
Found the issue, looks like it doesn't like that i'm creating a user with uid 1888001044, using a much smaller number like 189 worked.
