### ISSUE TITLE
WinRM connection err: http response error: 401 - invalid content type

### ISSUE THREAD

**Issue by yossisp1972** [hashicorp/packer#11581]
Hi,

I am trying to run packer on a modified windows AMI.
After the instance is created WinRm fails to connect with the following error:

2022/02/20 19:55:42 packer-plugin-amazon_v1.0.8_x5.0_windows_amd64.exe plugin: 2022/02/20 19:55:42 [INFO] Attempting WinRM connection...
2022/02/20 19:55:42 packer-plugin-amazon_v1.0.8_x5.0_windows_amd64.exe plugin: 2022/02/20 19:55:42 [DEBUG] connecting to remote shell using WinRM
2022/02/20 19:55:42 packer-plugin-amazon_v1.0.8_x5.0_windows_amd64.exe plugin: 2022/02/20 19:55:42 [ERROR] connection error: http response error: 401 - invalid content type
2022/02/20 19:55:42 packer-plugin-amazon_v1.0.8_x5.0_windows_amd64.exe plugin: 2022/02/20 19:55:42 [ERROR] WinRM connection err: http response error: 401 - invalid content type

When running Test-WsMan to this AWS instance i get a reply.
I tries running  winrm enumerate winrm/config/listener on the instance and i see that it listent on http port 5985.

I am using bootstrap file used in the example on your site.
Alst tried running the bootstrap with SSL and i see the instance is listening on 5986 and HTTPS but still doesnt work.
Tried removing the password from the file, tried https, nothing works.
Thanks,

**Comment by nywilken** [comment]
Thanks for reaching out. In order for us to best help could you provide the things requested in the issue template; including the simplest Packer configuration and scripts needed to reproduce the bug.

**Comment by yossisp1972** [comment]
I am using the template and bootstrap in the windows AMI tutorial on Hashicorp's site.
Its working now, for some odd reason, so lets close this one for now.

I have a question though, is there a way getting the temporary AWS instance IP address during runtime and set it to a var?

**Comment by nywilken** [comment]
Hi @yossisp1972 thanks for following up. Sometimes winrm authentication can take a little longer than expected to provision. If you find that you are having inconsistent results with the auth you may want to try bumping the winrm_timeout higher. 

Regrading your question about getting access to the instance IP. Yes, that information is made available via build variables. 
in HCL you can do something like the following to ping the instance IP. This is just an example. We also make available the SSH key data if needed. 

```hcl
provisioner "shell-local" {
  inline = ["ping ${build.Host}"]
  }
```

There are a number of build variables that are made available to provisioners and post-processors https://www.packer.io/docs/templates/hcl_templates/contextual-variables#build-variables

The Amazon builder also has a special set of build variables it exposes https://www.packer.io/docs/templates/hcl_templates/contextual-variables#build-variables

I'll go ahead and close the issue as requested.

**Comment by yossisp1972** [comment]
Thanks for the info, The build.Host var gets me the public IP, how do i get
the private IP?
