### ISSUE TITLE
Crash during building

### ISSUE THREAD

**Issue by carcarlo** [hashicorp/packer#11582]
Repoting a crash as indicated in packer log.
[crash.log](https://github.com/hashicorp/packer/files/8108648/crash.log)

**Comment by nywilken** [comment]
Thanks for opening an issue -- this looks similar to the issue reported in #10438. 

In order for us to best help could you provide the things requested in the issue template; including the simplest Packer configuration and scripts needed to reproduce the bug.

Did you check if the Packer build is getting killed by some external process like OOM?

**Comment by nywilken** [comment]
Hi @carcarlo can you give us a little more information about the environment that you are running in; including a build template that can be used for reproducing the issue.

**Comment by carcarlo** [comment]
Hi,
I think you can close this issue. The system was out of memory. Adjusting
memory it worked then.

Il Mer 2 Mar 2022, 17:22 Wilken Rivera ***@***.***> ha
scritto:

**Comment by nywilken** [comment]
Hi @carcarlo thanks for the update. Glad you were able to figure out what was happening. Is it possible to share your environment and memory configuration before adjusting? 

It could be helpful to us in the future, as we plan to start working on some profiling for Packer.
