### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by letnab** [hashicorp/packer#11633]
packer version 1.6.6

plugin https://github.com/huaweicloud/packer-plugin-huaweicloud version 0.2.2

`Build 'huaweicloud-ecs.oracle' errored after 1 millisecond 29 microseconds: Error initializing compute client: Discovered 2 matching endpoints: []tokens.Endpoint{tokens.Endpoint{ID:"id", Region:"region", Interface:"public", URL:"https://url1"}, tokens.Endpoint{ID:"id", Region:"region", Interface:"public", URL:"https://url2"}}`

**Comment by nywilken** [comment]
Closing in favor of https://github.com/huaweicloud/packer-plugin-huaweicloud/issues/42
