### ISSUE TITLE
Packer 1.8.0, virtualbox-ovf and started having issues about ' Download failed expected a single file, got multiple'

### ISSUE THREAD

**Issue by breisig** [hashicorp/packer#11631]
#### Overview of the Issue

I have just upgraded from Packer 1.7.10 to 1.8.0 [Under Windows 11] and immediately, I am having issues trying to provision a VM. I am using the virtualbox-ovf in my builds where after upgrading, it says 

```
=> virtualbox-ovf: Retrieving Guest additions
==> virtualbox-ovf: Trying C:\Program Files\Oracle\VirtualBox/VBoxGuestAdditions.iso
==> virtualbox-ovf: Trying file://C:/Program%20Files/Oracle/VirtualBox/VBoxGuestAdditions.iso
==> virtualbox-ovf: file://C:/Program%20Files/Oracle/VirtualBox/VBoxGuestAdditions.iso => C:/Program Files/Oracle/VirtualBox/VBoxGuestAdditions.iso
==> virtualbox-ovf: Retrieving OVF/OVA
==> virtualbox-ovf: Trying ./source_images/rocky-8-baseinstall/rocky-8-baseinstall.ova
==> virtualbox-ovf: Trying ./source_images/rocky-8-baseinstall/rocky-8-baseinstall.ova
==> virtualbox-ovf: Download failed expected a single file, got multiple: C:/c/source_images/rocky-8-baseinstall/rocky-8-baseinstall.ova
==> virtualbox-ovf: error downloading OVF/OVA: [expected a single file, got multiple: C:/c/source_images/rocky-8-baseinstall/rocky-8-baseinstall.ova]
==> virtualbox-ovf: Deleting output directory...
Build 'virtualbox-ovf' errored after 116 milliseconds 52 microseconds: error downloading OVF/OVA: [expected a single file, got multiple: C:/c/source_images/rocky-8-baseinstall/rocky-8-baseinstall.ova]

==> Wait completed after 116 milliseconds 52 microseconds

==> Some builds didn't complete successfully and had errors:
--> virtualbox-ovf: error downloading OVF/OVA: [expected a single file, got multiple: C:/c/source_images/rocky-8-baseinstall/rocky-8-baseinstall.ova]

==> Builds finished but no artifacts were created.
```

However when I downgrade back to Packer 1.7.10, it works without issue.

```
==> virtualbox-ovf: Retrieving Guest additions
==> virtualbox-ovf: Trying C:\Program Files\Oracle\VirtualBox/VBoxGuestAdditions.iso
==> virtualbox-ovf: Trying file://C:/Program%20Files/Oracle/VirtualBox/VBoxGuestAdditions.iso
==> virtualbox-ovf: file://C:/Program%20Files/Oracle/VirtualBox/VBoxGuestAdditions.iso => C:/Program Files/Oracle/VirtualBox/VBoxGuestAdditions.iso
==> virtualbox-ovf: Retrieving OVF/OVA
==> virtualbox-ovf: Trying ./source_images/rocky-8-baseinstall/rocky-8-baseinstall.ova
==> virtualbox-ovf: Trying ./source_images/rocky-8-baseinstall/rocky-8-baseinstall.ova
==> virtualbox-ovf: ./source_images/rocky-8-baseinstall/rocky-8-baseinstall.ova => C:/c/source_images/rocky-8-baseinstall/rocky-8-baseinstall.ova
==> virtualbox-ovf: Importing VM: C:/c/source_images/rocky-8-baseinstall/rocky-8-baseinstall.ova
==> virtualbox-ovf: Mounting ISOs...
    virtualbox-ovf: No ISOs to mount; continuing...
==> virtualbox-ovf: Creating forwarded port mapping for communicator (SSH, WinRM, etc) (host port 2377)
==> virtualbox-ovf: Executing custom VBoxManage commands...
    virtualbox-ovf: Executing: modifyvm packer-localdevelopment --cableconnected1 on
    virtualbox-ovf: Executing: modifyvm packer-localdevelopment --cableconnected2 on
    virtualbox-ovf: Executing: modifyvm packer-localdevelopment --spec-ctrl on
==> virtualbox-ovf: Starting the virtual machine...
    virtualbox-ovf: The VM will be run headless, without a GUI. If you want to
    virtualbox-ovf: view the screen of the VM, connect via VRDP without a password to
    virtualbox-ovf: rdp://127.0.0.1:5946
```
#### Reproduction Steps

Upgrading from Packer 1.7.10 to 1.8.0

### Packer version

1.8.0

### Simplified Packer Template

```
  "builders": [
    {
      "type": "virtualbox-ovf",
      "source_path": "./source_images/rocky-8-baseinstall/rocky-8-baseinstall.ova",
      "headless": true,
```

### Operating system and Environment details

Windows 11 Pro 64bit

**Comment by liaoya** [comment]
I have the same issue with 1.8.0. And 1.7.10 is OK.

**Comment by AntonioMeireles** [comment]
same here fwiw.

**Comment by mehaase** [comment]
This error message appears to come from `go-getter`: https://github.com/hashicorp/go-getter/blob/a7e02dae513b778bd3b082a5e65fdefbc29c405a/decompress_tar.go#L50 

But that code is 5 years old. I'm not sure what changed to surface this bug.

**Comment by nywilken** [comment]
Hi @mehaase thanks for calling that out. We have not had a chance to look into this issue just yet. But I believe your suspicion is correct. I see that Packer is using a different version of go-getter than what is being used in the SDK, which is being used by virtualbox builder. 

https://github.com/hashicorp/packer/blob/59a7f9140eab582ba3201d3f7aa8c9a50a080bf0/go.mod#L20

vs 

https://github.com/hashicorp/packer-plugin-sdk/blob/f7d4bf877a45a9d253c548e902d6d1bd7d907d23/go.mod#L32
```
	github.com/hashicorp/go-getter/v2 v2.0.0
```

**Comment by 3nprob** [comment]
@nywilken Workaround doesn't work here, errors with `Invalid plugin type; Plugin source "github.com/hashicorp/virtualbox" has a type with the prefix "packer-plugin-", which isn't valid. Although that prefix is often used in the names of version control repositories for Packer plugins, plugin source strings should not include it.`

Trying `packer plugins install github.com/hashicorp/virtualbox v1.0.1`  does install the plugin. Subsequent run:
```
[INFO] github.com/hashicorp/virtualbox v1.0.1 plugin is already correctly installed in "/home/user/.config/packer/plugins/github.com/hashicorp/virtualbox/packer-plugin-virtualbox_v1.0.1_x5.0_linux_amd64"
```

However, `packer build` still yields the error above.

**Comment by azr** [comment]
Oh, I need to update the virtualbox builder as well !

**Comment by azr** [comment]
Okay, so, the most recent [nightly release binary](https://github.com/hashicorp/packer/releases/tag/nightly) should have the fix, can you please tell me if that fixes it for you ? Thanks !

**Comment by nywilken** [comment]
Closing since this issue has been resolved on main already. The fix will be available in the next release. If you need access to the fix prior to the release please see use the nightly release.

**Comment by andrew-danieli-fj** [comment]
> 

Any idea when v1.8.1 will be formally released?

**Comment by jdeloem** [comment]
Just ran into this also, with 1.8.0. Though also just subscribed to the announcements list to hear when 1.8.1 will be available. For now just using the older version of Packer that I had.
