### ISSUE TITLE
Packer 1.8.0: QEMU fails to remove CD-ROM installation image during reboot (worked fine with 1.7.10)

### ISSUE THREAD

**Issue by dreibh** [hashicorp/packer#11651]
#### Overview of the Issue

Packer 1.7.10 with QEMU works fine, installing e.g. Ubuntu 18.04 or 20.04. However, after update to 1.8.0 (from HashiCorp's APT repository for Ubuntu 20.04, i.e. from https://apt.releases.hashicorp.com), Packer fails to remove the CD-ROM installation image. On reboot, the VM boots into the CD-ROM installation image again, instead of booting from the newly installed HDD image.

A downgrade to 1.7.10 solved the issue. So, it seems a bug has been introduced with 1.8.0.

#### Reproduction Steps

Trying to run a QEMU installation for Ubuntu 20.04 with Packer 1.8.0. It always fails.

### Packer version

1.8.0

### Simplified Packer Template

``{
  "variables": {
    "version": ""
  },
  "builders": [
    {
      "vm_name": "{{user `vm_name`}}",
      "output_directory": "{{user `vm_name`}}",
      "type": "qemu",
      "accelerator": "kvm",
      "headless": false,
      "format": "qcow2",
      "firmware": "/usr/share/qemu/OVMF.fd",
      "disk_interface": "virtio",
      "disk_cache": "unsafe",
      "disk_discard": "unmap",
      "net_device": "virtio-net",
      "cpus": "{{user `vm_cores`}}",
      "memory": "{{user `vm_memory`}}",
      "disk_size": "{{user `vm_disk_root`}}",
      "qemuargs": [
        [
          "-vga",
          "qxl"
        ]
      ],
      "http_directory": "http",
      "iso_url": "https://releases.ubuntu.com/20.04/ubuntu-20.04.4-live-server-amd64.iso",
      "iso_checksum": "sha256:28ccdb56450e643bad03bb7bcf7507ce3d8d90e8bf09e38f6bd9ac298a98eaad",
      "ssh_username": "{{user `user_name`}}",
      "ssh_password": "{{user `user_password`}}",
      "ssh_pty": true,
      "ssh_timeout": "60m",
      "ssh_handshake_attempts": "1024",
      "shutdown_command": "echo '{{user `user_password`}}' | sudo -S shutdown -P now",
      "boot_wait": "1s",
      "boot_command": [
        "<tab><wait>",
        "<tab><wait>",
        "<tab><wait>",
        "<tab><wait>",
        "<tab><wait>",
        "<tab><wait>",
        "<tab><wait>",
        "<tab><wait>",
        "<tab><wait>",
        "<tab><wait>",
        "<esc><wait>",
        "linux /casper/hwe-vmlinuz --- autoinstall ds=\"nocloud-net;seedfrom=http://{{ .HTTPIP }}:{{ .HTTPPort }}/\"<enter><wait>",
        "initrd /casper/hwe-initrd<enter><wait>",
        "boot<enter>"
      ]
    }
  ],
  ...
}
`

### Operating system and Environment details

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal

**Comment by nywilken** [comment]
Hi @dreibh thanks for bubbling this up. This seems like a regression with the latest Qemu builder release [1.0.2](https://github.com/hashicorp/packer-plugin-qemu/releases/tag/v1.0.2), which was pulled into Packer 1.8.0. I'm going to move this ticket there and continue the conversation.
