### ISSUE TITLE
Azure Chroot Builder - invalid 'image_resouce_id': template: root:1: bad character U+002D '-'

### ISSUE THREAD

**Issue by anaouss** [hashicorp/packer#11668]
**Overview of the Issue**

Per [the documentation chroot](https://www.packer.io/plugins/builders/azure/chroot#using-a-vm-with-a-managed-identity), it is possible to use Azure chroot with a Managed identity and as [this documentation](https://www.packer.io/docs/builders/azure/chroot#source), it's possible to set the source image to an image published in a Shared Image Gallery. However, when attempting to use this functionality, an error is yielded as `invalid 'image_resouce_id': template: root:1: bad character U+002D '-'` .

The source has the subscription as` xxxxxxxx-*****-*****-***-******* `and the resource groupe is` *******-*****-nextgen-dev-rg`, same as the build agent resides.

**Packer version**

Packer V1.8.0

**Operating system** 

Azure Linux Ubuntu 18.04.6

**Simplified Packer Template**

```
{
  "builders": [{
    "type": "azure-chroot",

"image_resource_id": "/subscriptions/{{vm xxxxxxxx-*****-*****-***-*******}}/resourceGroups/{{vm '*******-******-nextgen-dev-rg'}}/providers/Microsoft.Compute/galleries/uai3042788nextgenImageGallery/images/PEOSLinuxImage/versions/1.0.0",

"source": "/subscriptions/xxxxxxxx-*****-*****-***-*******/resourceGroups/*******-*****-nextgen-dev-rg/providers/Microsoft.Compute/galleries/uai3042788nextgenImageGallery/images/ren-azure-ubuntu/versions/1.0.0"

  }],
  "provisioners": [{
    "execute_command": "chmod +x {{ .Path }}; {{ .Vars }} sudo -E sh '{{ .Path }}'",
    "inline": [
"apt-get update",
"apt-get upgrade -y",


],
}
```

**Error when trying to validate using `packer validate CustomLinuxImage.json`**

```
Error: Failed to prepare build: "azure-chroot"
invalid 'image_resouce_id': template: root:1: bad character U+002D '-' in:

/subscriptions/{{vm xxxxxxxx-*****-*****-***-*******}}/resourceGroups/{{vm '*******-*****-nextgen-dev-rg'}}/providers/Microsoft.Compute/galleries/uai3042788nextgenImageGallery/images/PEOSLinuxImage/versions/1.0.0
```

**Comment by nywilken** [comment]
Hi @anaouss thanks for reaching out. Looking at the provided template it looks like you are mixing a Packer template function with the subscription_id and resource group name, which is causing the error. For the value of image_resource_id you want to use Packer's template function to derive the subscription_id and resource_group; the values wrapped by the backticks (i.e subscription_id and resource_group) are variable names that will get auto populated during build time.  The function `{{vm ...}` is a Packer template function that will get executed at build time and replace the variable within the backticks with the actual value obtained at build. 

Does changing your template to reflect the example below fix the issue you are seeing? 

```
﻿{
  "builders": [{
    "type": "azure-chroot",

"image_resource_id": "/subscriptions/{{vm `subsciption_id`}}/resourceGroups/{{vm `resource_group`}}/providers/Microsoft.Compute/galleries/uai3042788nextgenImageGallery/images/PEOSLinuxImage/versions/1.0.0",

"source": "/subscriptions/xxxxxxxx-*****-*****-***-*******/resourceGroups/*******-*****-nextgen-dev-rg/providers/Microsoft.Compute/galleries/uai3042788nextgenImageGallery/images/ren-azure-ubuntu/versions/1.0.0"

  }],
  "provisioners": [
{
		"type": "shell",
    "execute_command": "chmod +x {{ .Path }}; {{ .Vars }} sudo -E sh '{{ .Path }}'",
    "inline": [
	"apt-get update",
	"apt-get upgrade -y"
	]
}]

}
```

Alternatively you can hard cord the subscription_id and resource_group values and not use the vm function. 

```
"image_resource_id":"/subscriptions/xxxxxxxx-*****-*****-***-*******/resourceGroups/*******-*****-nextgen-dev-rg/providers/Microsoft.Compute/galleries/uai3042788nextgenImageGallery/images/PEOSLinuxImage/versions/1.0.0"
```

**Comment by anaouss** [comment]
Thank you  @nywilken it worked
