### ISSUE TITLE
`amazon-ebs`: `temporary_key_pair_type` is not generating the specified key type

### ISSUE THREAD

**Issue by WolfangAukang** [hashicorp/packer#11686]
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

When creating an AMI through `amazon-ebs` while specifying a different temp key pair type (in my case, a `ed25519` key) it still generates a `rsa` key.

#### Reproduction Steps

- Edit template and add `"temporary_key_pair_type": "ed25519",` to the `builders` section
- Run `packer build template.json`
- Check AWS -> EC2 -> Key Pairs, verify generated key pair is of specified type

### Packer version

1.7.10

### Simplified Packer Template

[Check template.json](https://gist.github.com/WolfangAukang/8351a2d4858be0efcab59dc8ae0b1763)

### Operating system and Environment details

Ubuntu 20.04, x86_64

### Log Fragments and crash.log files
[Check error_log.txt](https://gist.github.com/WolfangAukang/8351a2d4858be0efcab59dc8ae0b1763)

![image](https://user-images.githubusercontent.com/8378365/160165727-e3c56d30-d49e-415a-8279-e2e0b3a90ada.png)

**Comment by nywilken** [comment]
Hi @WolfangAukang support for `ed25519` key types was added in the [1.0.7](https://github.com/hashicorp/packer-plugin-amazon/releases) Amazon Packer plugin release, which was not included in Packer 1.7.10. 

I tested your provided template against Packer 1.8.0 and was able to successfully connect using the generated `ed25519` key type. Please upgrade to the latest release of Packer to resolve this issue. 

I'm going to close the issue for now. If you find that you are running into issues after upgrading please leave a comment on the thread and we will try our best to help out.

**Comment by WolfangAukang** [comment]
Indeed, this is a version issue and can confirm that after the update, the generated key is now of the specified format. Thank you @nywilken
