### ISSUE TITLE
Long file paths break mobile rendering of docs

### ISSUE THREAD

**Issue by dane** [hashicorp/packer#11694]
![image](https://user-images.githubusercontent.com/72265290/161887945-3ab482f1-4168-4ec7-861d-9d292aa47ae2.png)

The docs site is excellent on mobile. Some pages appear to be zoomed out because of long file paths used in examples. You should be able to see this in the attached screenshot.

**Comment by tenthirtyam** [comment]
After the transition to the new developer.hashicorp.com this no longer appears to be an issue.

Here are two screenshots from the latest version of the content referenced by the OP.

<img src="https://github.com/hashicorp/packer/assets/7771363/4db0de36-f682-4d11-9f22-146ecf41d7fa" width="40%">


<img src="https://github.com/hashicorp/packer/assets/7771363/e805c1d7-d079-48a7-b566-d7c42a48cc6c" width="40%">

cc @nywilken @lbajolet-hashicorp

**Comment by lbajolet-hashicorp** [comment]
Yes, that's an old issue and as we've since then reworked the docs system, this can be closed.

By all means please reopen this if you think we've missed something, and we'll investigate.

Thanks!
