### ISSUE TITLE
Documentation of .packerconfig file options missing

### ISSUE THREAD

**Issue by sebthom** [hashicorp/packer#11693]
#### Overview of the Issue
The documentation at https://www.packer.io/docs/configure#packer-s-config-file mentions a JSON file where end users can set **core settings**. However nowhere in the documentation the structure of that JSON file nor the available core settings that can actually be configured are mentioned. I for example wonder if all the settings that can be configured using the [environment variables](https://www.packer.io/docs/configure#full-list-of-environment-variables-usable-for-packer) can also be somehow configured in that file.

### Packer version

1.8.0

**Comment by tenthirtyam** [comment]
@nywilken @lbajolet-hashicorp - Should this information be simply removed since, as I recall, the use of `.packerconfig.json` was deprecated in v1.7.

**Comment by lbajolet-hashicorp** [comment]
Hey @tenthirtyam,

I believe you're right yes, the config.json file is deprecated, and 1.11.0 removed some options (components) from its spec, so now it's even less useful that it used to be.

We may re-introduce a new config file format later, but for now this can be closed.
