### ISSUE TITLE
Packer fix issue

### ISSUE THREAD

**Issue by abhishek140389** [hashicorp/packer#11703]
Hi Team,

I am getting below error while running the packer build in my jenkins job.
I did run the packer fix, but nothing is helping it, any idea what can be the issue?
 
1 error occurred:
16:41:44 	* Deprecated configuration key: 'ssh_private_ip'. Please call `packer fix`
16:41:44 against your template to update your template to be compatible with the current
16:41:44 version of Packer. Visit https://www.packer.io/docs/commands/fix/ for more
16:41:44 detail.

Thanks,
Abhishek

**Comment by nywilken** [comment]
Hi there @abhishek140389 the Packer fix command when run against a JSON template will output the updated template file but it will not modify the original template.  When running `packer fix source.json` you need to save the output into a new file, which you can then use to build. 

Have you tried redirecting the output to a new file? 

For example `packer fix source.json > new-source.json`; running `packer build new-source.json` should execute without error. 

I'm going to close this issue as I believe this to be a configuration error. But if after capturing the output you are still running into the same error please update the issue with an example template in order for us to see what might be happening. Cheers!
