### ISSUE TITLE
Customizing the default user of an Ubuntu AMI to ubuntu user {HashiCorp Packer}

### ISSUE THREAD

**Issue by shirab2** [hashicorp/packer#11713]
Hi all,
I'd like to create a simple **Ubuntu 20.04 LTS AWS AMI** image with the Default user **"ubuntu"** using Packer by HashiCorp, but unfortunately, when I try to **connect** to the new EC2 I see that the user's name is **root** instead of **ubuntu**.

**Comment by JenGoldstrich** [comment]
Hello @shirab2 👋 

I accidentally linked to your issue in my above PR sorry about that 😅 

I think your best bet here it to use [shell provisoners](https://www.packer.io/docs/provisioners/shell), to change the user within the AMI.

You can change the name in several ways within a shell provisioner, but Ubuntu has a package called [CloudInit](https://help.ubuntu.com/community/CloudInit) which allows you to set a new default user by adding a file (using a shell provisioner) to /etc/cloud/cloud.cfg.d/defaults.cfg that looks something like..

```
#cloud-config
system_info:
  default_user:
    name: ubuntu
```

[More cloud-init info about setting username/password here](https://cloudinit.readthedocs.io/en/latest/topics/modules.html?highlight=default_user#users-and-groups)

**Comment by JenGoldstrich** [comment]
Closing as it's been a month, please feel free to re-open if you have any further questions!
