### ISSUE TITLE
How to provision an instance, dont build an AMI and terminate it last.

### ISSUE THREAD

**Issue by yossisp1972** [hashicorp/packer#11738]
Hi,

I am trying to write a HCL file that will build 5 AMIs out of 5 different templates, for running the template i will need a sixth template to be provisioned together with the other five but no action to be done on this 6th instance. At the end it should be terminated with the rest.
How can this be done?

Thanks,

**Comment by nikhilpatne** [comment]
Hi @yossisp1972  use   ` skip_create_image = true` for azure ,  and `skip_create_ami  = true`  for AWS
