### ISSUE TITLE
Packer provision windows-restart hangs after reboot

### ISSUE THREAD

**Issue by knabben** [hashicorp/packer#11742]
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

I'm using the image-builder project (https://github.com/kubernetes-sigs/image-builder) to build OVA nodes, and the `windows-restart` provisioner hangs after restarting the machine for the first time. 

#### Reproduction Steps

This happens on a particular environment. Maybe the winrm is hanging the connection since there's no timeout.

### Packer version

1.7.2

### Simplified Packer Template

```
    {
      "except": "file",
      "restart_check_command": "powershell -command \"& {if ((get-content C:\\ProgramData\\lastboot.txt) -eq (Get-WmiObject win32_operatingsystem).LastBootUpTime) {Write-Output 'Sleeping for 600 seconds to wait for reboot'; start-sleep 600} else {Write-Output 'Reboot complete'}}\"",
      "restart_command": "powershell \"& {(Get-WmiObject win32_operatingsystem).LastBootUpTime > C:\\ProgramData\\lastboot.txt; Restart-Computer -force}\"",
      "type": "windows-restart"
    },
```

### Log Fragments and crash.log files

https://gist.github.com/knabben/fd01ceb2b6b62f685ca8398564cf9ebb

**Comment by knabben** [comment]
looked some issue with the machine accessing the vsphere, fixed the env and it worked back. closing the issue.

**Comment by nywilken** [comment]
Closing since there have been no updates to the issue. If you believe this is still an issue please open a new bug issue with the information requested in the template.
