### ISSUE TITLE
error initializing provisioner 'windows-update': Unknown provisioner

### ISSUE THREAD

**Issue by audioeptesicus** [hashicorp/packer#11777]
Running packer 1.8.0 from a Windows 2019 server.

I'm running packer from C:\Scripts\Packer and have the environment variable set.  I have placed the packer-plugin-windows-update_v0.14.0_x5.0_windows_amd64.exe plugin in multiple directories (where packer.exe resides, where the .json/.pkr.hcl files are saved, in various plugin directories I have created based on recommended paths) and cannot avoid the error.

The packer log finds the plugins, but does note the following:
```
2022/05/13 08:31:52 ui error: Error: Unknown provisioner type "windows-update"

  on Windows_Builds\Win2022_Base\Win2022_Base.pkr.hcl line 129:
  (source code not available)
```
What am I doing wrong here?

**Comment by tenthirtyam** [comment]
`windows-update` is a community provisioner. I would suggest opening an issue at [rgl/packer-plugin-windows-update](https://github.com/rgl/packer-plugin-windows-update/issues).

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by animatco** [comment]
As you can see in that repo you need to add to either a init.pkr.hcl file or within your pkr.hcl 

packer {
  required_plugins {
    windows-update = {
      version = "0.14.1"
      source = "github.com/rgl/windows-update"
    }
  }
}

Then run packer init whatever.pkr.hcl

**Comment by nywilken** [comment]
@tenthirtyam and @animatco thanks for the assist on this issue. I'm going to close as the question has been answered.

 @audioeptesicus external  Packer plugins need to be installed by running `packer init` or manually using the manual installation process outlined in the documentation https://www.packer.io/plugins#installing-plugins
