### ISSUE TITLE
packer-builder-vmware-iso plugin: failed to unlock port lockfile: close tcp [::]:5907: use of closed network connection

### ISSUE THREAD

**Issue by dyzone** [hashicorp/packer#11779]
pls help i keep getting this error:  packer-builder-VMware-iso plugin: failed to unlock port lockfile: close tcp [::]:5907: use of closed network connection 

```json
"builders": [{
      "type": "vmware-iso",
      "iso_url": "https://ussl-toolsp.usanainc.com/artifactory/centos-remote/7.9.2009/isos/x86_64/CentOS-7-x86_64-Minimal-2009.iso",
      "iso_checksum": "07b94e6b1a0b0260b94c83d6bb76b26bf7a310dc78d7a9c7432809fb9bc6194a",
      "boot_command": [
        "<tab> text ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/ks.cfg<enter><wait>"
      ],
      "boot_wait": "10s",
      "guest_os_type": "centos-64",
      "http_directory": "http",
      "ssh_username": "root",
      "ssh_password": "changeme",
      "ssh_wait_timeout": "10m",
      "disk_size": "60000",
      "disk_type_id":"0",
      "tools_upload_flavor": "linux",
      "vnc_bind_address": "0.0.0.0",
      "vm_name":"CentOS_7.7_Template",
      "name":"CentOS_7.7_Template",
      "vnc_disable_password": true,
      "vnc_port_min": 5901,
      "vnc_port_max": 5909,
      "shutdown_command": "sudo /sbin/halt -p",
      "headless": "true",
      "output_directory": "output-vmware-iso"
    }]
```

==> CentOS_7.7_Template: Starting HTTP server on port 8941
2022/05/15 07:54:33 packer-builder-vmware-iso plugin: Looking for available port between 5901 and 5909
2022/05/15 07:54:33 packer-builder-vmware-iso plugin: Found available port: 5907 on IP: 0.0.0.0
2022/05/15 07:54:33 packer-builder-vmware-iso plugin: Found available VNC port: 0.0.0.0:5907
2022/05/15 07:54:33 packer-builder-vmware-iso plugin: Writing VMX to: output-vmware-iso/CentOS_7.7_Template.vmx
==> CentOS_7.7_Template: Starting virtual machine...
    CentOS_7.7_Template: The VM will be run headless, without a GUI. If you want to
    CentOS_7.7_Template: view the screen of the VM, connect via VNC with the password "" to
    CentOS_7.7_Template: vnc://0.0.0.0:5907
2022/05/15 07:54:33 packer-builder-vmware-iso plugin: Executing: /usr/bin/vmrun -T ws start output-vmware-iso/CentOS_7.7_Template.vmx nogui
    CentOS_7.7_Template: view the screen of the VM, connect via VNC with the password "" to
    CentOS_7.7_Template: vnc://0.0.0.0:5907
2022/05/15 07:54:34 packer-builder-vmware-iso plugin: stdout: Error: The operation was canceled
2022/05/15 07:54:34 packer-builder-vmware-iso plugin: stderr:
==> CentOS_7.7_Template: Error starting VM: VMware error: Error: The operation was canceled
==> CentOS_7.7_Template: Waiting 4.706809746s to give VMware time to clean up...
2022/05/15 07:54:38 packer-builder-vmware-iso plugin: Executing: /usr/bin/vmrun -T ws list
2022/05/15 07:54:38 packer-builder-vmware-iso plugin: stdout: Total running VMs: 0
2022/05/15 07:54:38 packer-builder-vmware-iso plugin: stderr:
2022/05/15 07:54:38 packer-builder-vmware-iso plugin: failed to unlock port lockfile: close tcp [::]:5907: use of closed network connection
==> CentOS_7.7_Template: Deleting output directory...
2022/05/15 07:54:38 [INFO] (telemetry) ending CentOS_7.7_Template
==> Wait completed after 11 seconds 856 milliseconds
2022/05/15 07:54:38 machine readable: error-count []string{"1"}
==> Some builds didn't complete successfully and had errors:
2022/05/15 07:54:38 machine readable: CentOS_7.7_Template,error []string{"Error starting VM: VMware error: Error: The operation was canceled"}
==> Builds finished but no artifacts were created.
Build 'CentOS_7.7_Template' errored after 11 seconds 856 milliseconds: Error starting VM: VMware error: Error: The operation was canceled

==> Wait completed after 11 seconds 856 milliseconds

==> Some builds didn't complete successfully and had errors:
--> CentOS_7.7_Template: Error starting VM: VMware error: Error: The operation was canceled

==> Builds finished but no artifacts were created.
2022/05/15 07:54:38 [INFO] (telemetry) Finalizing.
2022/05/15 07:54:39 waiting for all plugin processes to complete...
2022/05/15 07:54:39 /usr/local/bin/packer: plugin process exited
2022/05/15 07:54:39 /usr/local/bin/packer: plugin process exited
2022/05/15 07:54:39 /usr/local/bin/packer: plugin process exited
2022/05/15 07:54:39 /usr/local/bin/packer: plugin process exited
2022/05/15 07:54:39 /usr/local/bin/packer: plugin process exited
2022/05/15 07:54:39 /usr/local/bin/packer: plugin process exited
2022/05/15 07:54:39 /usr/local/bin/packer: plugin process exited
2022/05/15 07:54:39 /usr/local/bin/packer: plugin process exited
2022/05/15 07:54:39 /usr/local/bin/packer: plugin process exited
2022/05/15 07:54:39 /usr/local/bin/packer: plugin process exited
2022/05/15 07:54:39 /usr/local/bin/packer: plugin process exited
2022/05/15 07:54:39 /usr/local/bin/packer: plugin process exited
2022/05/15 07:54:39 /usr/local/bin/packer: plugin process exited
2022/05/15 07:54:39 /usr/local/bin/packer: plugin process exited
2022/05/15 07:54:39 /usr/local/bin/packer: plugin process exited
2022/05/15 07:54:39 /usr/local/bin/packer: plugin process exited
2022/05/15 07:54:39 /usr/local/bin/packer: plugin process exited
2022/05/15 07:54:39 /usr/local/bin/packer: plugin process exited
2022/05/15 07:54:39 /usr/local/bin/packer: plugin process exited
2022/05/15 07:54:39 /usr/local/bin/packer: plugin process exited
[root@ussl-bamboobuildp01 centos_7x]# PACKER_LOG=1
[root@ussl-bamboobuildp01 centos_7x]# 1

**Comment by tenthirtyam** [comment]
@hc-github-team-packer - looks like this issue should be transferred to [hashicorp/packer-plugin-vmware](https://github.com/hashicorp/packer-plugin-vmware) for triage.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.
