### ISSUE TITLE
Documentation of packer home directory file location is incorrect, and also the plugins.

### ISSUE THREAD

**Issue by SpencerBrown** [hashicorp/packer#11781]
The [documentation page](https://www.packer.io/docs/configure#packer-s-home-directory) says PACKER_HOME_DIR is set to `${HOME}` on Unix. In fact, it's `${HOME}/.config/packer`, as far as I can tell. 

Also, the plugins appear to be located at  `PACKER_HOME_DIR/plugins/github.com/hashicorp/` , not `PACKER_HOME_DIR/plugins/github.com/hashicorp/happycloud/`. 

All of this of course is the default, when you don't set environment variables.

**Comment by teddylear** [comment]
@SpencerBrown Opened PR for fixing Packer config file docs. I think if you are talking about the plugin docs [here](https://www.packer.io/docs/plugins), then I think the `/happycloud` suffix is an example of the how plugins are installed using the `happycloud` plugin. But someone from packer maintainers could confirm.
