### ISSUE TITLE
local variable or data source can't be referenced in powershell enviroment variables

### ISSUE THREAD

**Issue by ozbillwang** [hashicorp/packer#11795]
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

local variable or data source can't be referenced in powershell enviroment variables

#### Reproduction Steps

sample hcl template
```
$ cat sample.pkr.hcl

data "amazon-ami" "example" {
    filters = {
        virtualization-type = "hvm"
        name = "ubuntu/images/*ubuntu-xenial-16.04-amd64-server-*"
        root-device-type = "ebs"
    }
    owners = ["099720109477"]
    most_recent = true
}

locals {
  imageId = data.amazon-ami.example.id
}

source "null" "first-example" {
  communicator = "none"
}

build {
  source "null.first-example" {
    name = "consul"
  }

  provisioner "powershell" {
    environment_vars = ["sourceImage=${local.imageId}"]
    inline = ["echo"]
  }

  provisioner "powershell" {
    environment_vars = ["sourceImage=${data.amazon-ami.example.id}"]
    inline = ["echo"]
  }

}
```
If validate it, I got two errors on both local variable and data source id reference

```
$ packer validate sample.pkr.hcl

Error: Failed preparing provisioner-block "powershell" ""

  on sample.pkr.hcl line 24:
  (source code not available)

1 error(s) occurred:

* Environment variable not in format 'key=value': <unknown>

Error: Failed preparing provisioner-block "powershell" ""

  on sample.pkr.hcl line 29:
  (source code not available)

1 error(s) occurred:

* Environment variable not in format 'key=value': <unknown>
* ```

### Packer version

Packer v1.8.0

### Simplified Packer Template

Provided in above steps

### Operating system and Environment details

tested in both macbook and ubuntu

### Log Fragments and crash.log files

No log related.

**Comment by ozbillwang** [comment]
seems this is only for data source, If I set local variable with other way, it is fine.

```
$ cat sample.pkr.hcl

locals {
  date = formatdate("MM-DD-YYYY-hh-mm", timestamp())
}

source "null" "first-example" {
  communicator = "none"
}

build {
  source "null.first-example" {
    name = "consul"
  }

  provisioner "powershell" {
    environment_vars = ["date=${local.date}"]
    inline = ["echo"]
  }
}

$ packer validate sample.pkr.hcl
The configuration is valid.
```

**Comment by ozbillwang** [comment]
Finally I fixed with inline, skip using `environment_vars` 

but this is still a problem in packer

**Comment by nywilken** [comment]
Hi @ozbillwang I believe this has been fixed by #11819 which is available in the latest Packer [nightly release](https://github.com/hashicorp/packer/releases/tag/nightly). Can you please pull down the nightly and advise if you are still running into issues?

**Comment by ozbillwang** [comment]
@nywilken 

which version I should test with? I tested with packer v1.8.1, same error

```
> packer validate sample.pkr.hcl
Error: Failed preparing provisioner-block "powershell" ""

  on sample.pkr.hcl line 24:
  (source code not available)

1 error(s) occurred:

* Environment variable not in format 'key=value': <unknown>

Error: Failed preparing provisioner-block "powershell" ""

  on sample.pkr.hcl line 29:
  (source code not available)

1 error(s) occurred:

* Environment variable not in format 'key=value': <unknown>

> packer --version
1.8.1
```

**Comment by ozbillwang** [comment]
@nywilken 

Same error with version 1.8.2

```
> ./packer validate sample.pkr.hcl
Error: Failed preparing provisioner-block "powershell" ""

  on sample.pkr.hcl line 24:
  (source code not available)

1 error(s) occurred:

* Environment variable not in format 'key=value': <unknown>

Error: Failed preparing provisioner-block "powershell" ""

  on sample.pkr.hcl line 29:
  (source code not available)

1 error(s) occurred:

* Environment variable not in format 'key=value': <unknown>


> ./packer --version
1.8.2
```

**Comment by nywilken** [comment]
Hi @ozbillwang apologies for glossing over this important detail "If validate it, I got two errors on both local variable and data source id reference". Data sources are not evaluated during the validate command. They are given a default value of `<unknown>`, which is what the environment variable logic is complaining about. 

As an alternative to the `environment_vars` you can use the `env` argument which should handle the `<unknown>` value a little better. This is a workaround for now as we work on the underlying issue of not evaluating datasources during validate. 

```
  provisioner "powershell" {
   env = {
     "sourceImage": local.imageId,
   }
     inline = ["echo $sourceImage"]
  }

  provisioner "powershell" {
   env = {
     "sourceImage": data.amazon-ami.example.id,
   }
    inline = ["echo $sourceImage"]
  }
```

Support for `env` is only within the nightly Packer release at the moment. 

This issue essentially a duplicate of https://github.com/hashicorp/packer/issues/11294. I will keep it open for now so we can continue discussing.

**Comment by ozbillwang** [comment]
yes, it works with `env` now. and the new way with `{}` is better than the list `[]` to be used.
