### ISSUE TITLE
Packer install fails on Amazon Linux 2022

### ISSUE THREAD

**Issue by lagerfeuer** [hashicorp/packer#11826]
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

I'm trying to install `packer` on Amazon Linux 2022, and following the installation guide for both Amazon Linux and Fedora (since Amazon Linux 2022 seems to use `dnf`), neither one seems to work. Amazon Linux 2022 is currently in preview, so this might not be on your radar yet.

#### Reproduction Steps

Here are the two Dockerfiles I have tried.
##### yum
```
FROM amazonlinux:2022

RUN yum install -y yum-utils
RUN yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
RUN yum -y install packer

```
##### dnf
```
FROM amazonlinux:2022

RUN dnf install -y dnf-plugins-core
RUN dnf config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
RUN dnf -y install packer

```

### Packer version

N/A

### Simplified Packer Template

N/A

### Operating system and Environment details

Docker 20.10.12 on macOS Monterey using `amazonlinux:2022` as base image.

### Log Fragments and crash.log files

```
Hashicorp Stable - x86_64                                                                                                                                                                     2.5 kB/s | 332  B     00:00
Errors during downloading metadata for repository 'hashicorp':
  - Status code: 404 for https://rpm.releases.hashicorp.com/AmazonLinux/2022.0.20220518/x86_64/stable/repodata/repomd.xml (IP: 99.84.108.74)
Error: Failed to download metadata for repo 'hashicorp': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
Ignoring repositories: hashicorp
Last metadata expiration check: 1:43:25 ago on Tue 31 May 2022 05:44:46 PM UTC.
No match for argument: packer
Error: Unable to find a match: packer

```

**Comment by nywilken** [comment]
Thanks for reaching out. We currently don't have packages available for the preview. However if you are interested in trying out Packer you can download the latest release from https://releases.hashicorp.com/packer/1.8.1

Here's a quick example that worked for me. 
```
FROM amazonlinux:2022

RUN dnf install -y dnf-plugins-core
RUN dnf -y install wget unzip
RUN wget https://releases.hashicorp.com/packer/1.8.1/packer_1.8.1_linux_amd64.zip
RUN unzip packer_1.8.1_linux_amd64.zip -d /usr/local/bin/
RUN dnf -y remove wget unzip
```

**Comment by nywilken** [comment]
I'm going to close this issue and inform our packaging team of the request. Thanks for bubbling this up.
