### ISSUE TITLE
file upload failure

### ISSUE THREAD

**Issue by outzhu** [hashicorp/packer#11855]
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

I want to set some env variable for the Vagrant box `GOPATH=$HOME/go` and `PATH=$PATH:$GOPATH/bin`, I couldn't figure out how Packer does that so I decided to try the file-provisioner.

I followed [provisioner-file](https://www.packer.io/docs/provisioners/file#basic-example) the provisioning shows the file does get uploaded and the shell runs, but there's such no file in the Vagrant box.

If anybody can help with either exporting variables to the built image or uploading files, I would be very grateful. 

#### Reproduction Steps

```
provisioner "file" {
  source = "upload/go.sh"
  destination = "$HOME/go.sh"
}
provisioner "shell" {
   inline = [
   "sudo mv $HOME/go.sh /etc/profile.d/"]
}
```
### Packer version

1.8.1

### Operating system and Environment details

Vagrant with Alpine image.

### Log Fragments and crash.log files

==> pentesting-vagrant.vagrant.alpine: Uploading upload/go.sh => $HOME/go.sh
    pentesting-vagrant.vagrant.alpine: go.sh 39 B / 39 B [====] 100.00% 0s
==> pentesting-vagrant.vagrant.alpine: Provisioning with shell script: /tmp/packer-shell3848276377
==> pentesting-vagrant.vagrant.alpine: Packaging box...

**Comment by nywilken** [comment]
Hi @outzhu the answer depends on how you plan to use the environment variables.  Each of the provisioners have support for setting environment variables to be used at command execution. There are arguments called `env` `environment_vars` a long with an option to write the environment variables to a temporary file that gets source before executing a command. 

looking at the example it looks like you might want to persist the env variables for the whole build. 

Is that what you are looking to do?

**Comment by nywilken** [comment]
There was a discussion on the forum around a topic that might be related here as well. I’m dropping a link https://discuss.hashicorp.com/t/return-variables-from-shell-provisioner-into-packer-variables/6609/7


If you can share how you want to access these variables I might be able to give you an example to work with.

**Comment by outzhu** [comment]
Hi @nywilken yes I want the env variables to persist for the whole build.

So I'm trying to set GOPATH=$HOME/go and then add $GOPATH/bin to my $PATH for the vagrant box so I can just call whatever package (gobuster in this case) I installed in the go/bin folder when I `vagrant ssh` into the box.

I managed to properly use `go install` with an `environment_vars = ["GOPATH=$HOME/go"]` but haven't figured out how to store the env variables for the build.  

```
build {
  name        = "pentesting-vagrant"
  description = "Penetration Testing Virtual Machine"

  sources = [
    "source.vagrant.alpine"
  ]

  provisioner "shell" {
    environment_vars = ["GOPATH=$HOME/go"]
    scripts = [
      "scripts/dependencies.sh",
      ////
    ]
    execute_command = "echo 'vagrant' | sudo -S -E sh -c '{{ .Vars }} {{ .Path }}'"
  }
}

#!/bin/sh
set -eu

apk update && \
apk add \
  
////
  
go \
unzip

go install github.com/OJ/gobuster/v3@latest
```

**Comment by outzhu** [comment]
Hi I managed to get provisioner file working. I had to delete .vargrant.d/boxes packer_alpine. 
I guess it couldn't update the new build.

**Comment by Cristian98149** [comment]
Hi all, 
I have the same issue with a container. I'm trying to build a container image and I'm using the "file" provisioner to upload two files in /tmp dir, and this step works. After that, I need to move these files from /tmp to in /etc/gitlab-runner, this step doesn't work. What is very strange is that the files disappear from the containter, so from /tmp dir but if I set the entrypoint with the command to move the files inside /etc/gitlab-runner/, they are being moved!

```
provisioner "file" {
  source      = "./templates/config.toml"
  destination = "/tmp/config.toml"
}
provisioner "file" {
  source      = "./templates/fargate.toml"
  destination = "/tmp/fargate.toml"
}
provisioner "shell" {
  inline = ["mv /tmp/*.toml /etc/gitlab-runner/"]
}
```

Any idea of what I'm wronging?

Thank you!

**Comment by outzhu** [comment]
Hi @Cristian98149 the way I fixed my issue was clearing the "cache" for Vagrant. 
With your container (Docker?) is it possible that its saving previous Packer "cache"?

Did you "physically" check that the files were actually in /tmp?
My log also showed that it was uploading and moving but I checked it after removing the `sudo mv ` part and nope! It wasn't there.

That's the only advice I have, sorry if that's not the solution.

**Comment by brucellino** [comment]
with @Cristian98149 we discovered that the file provisioner was actually placing the files in a path which the source container declared as a volume. This meant that the volume was deleted when the build container exited and the files along with it.
