### ISSUE TITLE
No debugging information during CI/CD

### ISSUE THREAD

**Issue by or-adar** [hashicorp/packer#11859]
Hi,
I'm running packer build as part of a ci/cd pipeline on a gitlab repo.
For some reason I don't see artifacts being created and packer doesn't output any information, even when the `-debug` flag is enabled.

My question is, if there's another way to enable debugging information with `packer build` command on a ci/cd platform?
as it is usaully very informative when not running the command on the ci/cd pipeline,
but when I'm running it via a pipeline on gitlab there's fewer outputs, and if the `packer build` fails on gitlab - there won't be any output to indicate that.

**Comment by oinkbark** [comment]
https://www.packer.io/docs/debugging#debugging-packer

```bash
PACKER_LOG=1
PACKER_LOG_PATH=/your/desired/filepath/packer.log
````

Set these environment variables, and configure your pipeline to save the log file that is generated.

**Comment by or-adar** [comment]
Hi @oinkbark,
thanks for pointing this out,
however it didn't help to my problem - as the log file wasn't generated by packer 
even though the environment variables were set correctly.

Could there be any other ways to force packer to emit logs on errors?
for some reason this behaviour happens only on GitLab. Is packer known for reducing logs when running on a CI/CD runner?

**Comment by oinkbark** [comment]
- Do you have no output or reduced output to stdout/stderr? You mentioned both scenarios in your post.
- Are you sure the build step is being executed correctly (valid config file, valid Packer template)?
- Do you have a snippet from your .gitlab-ci.yml file?
- What Packer version are you using?

**Comment by oinkbark** [comment]
[This ancient Google groups post ](https://groups.google.com/g/packer-tool/c/toLptcrRP6Q) shows someone else having the same output of "0 0" with the Amazon plugin, albeit on Jenkins. You can see if it leads you in the right direction.

What happens during `packer init`?

**Comment by oinkbark** [comment]
Awesome, glad we were able to resolve your issue.
