### ISSUE TITLE
Packer throws HCP Packer bucket creation error on validate

### ISSUE THREAD

**Issue by nywilken** [hashicorp/packer#11884]
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Overview of the Issue

When running `packer validate` on a template containing an HCP Packer registry block Packer will fail with the following error if no HCP Packer credentials or  HCP Packer Build Fingerprint (non git-committed template) is provided. 

```
~>  packer validate /tmp/source.pkr.hcl
Error: Unable to create a valid bucket object for HCP Packer Registry

Packer was unable to load a git sha. If your Packer template is not in a git
repo, please add a unique template fingerprint using the env var
HCP_PACKER_BUILD_FINGERPRINT. Error: repository does not exist
```

I would expect this error to only occur when running a Packer build `packer build`. Upon validate I would expect Packer to error that no credentials are available but I wouldn't expect it to try and create the bucket and new iteration upon validate. 

Creating a bucket upon validation can lead to issues as the template might be in development. A bucker should be created and or updated only when an actual build is executed. 
#### Reproduction Steps

- Create a basic HCP Packer registry template in a non Git managed directory
- Unset all HCP Packer credentials; Don't set HCP_PACKER_BUILD_FINGERPRINT
- Run `packer validate .`
- Validate that bucket gets created. 

### Packer version

From `1.8.2`

### Simplified Packer Template

```
packer {
  required_plugins {
    amazon = {
      version = ">= 1.0.1"
      source  = "github.com/hashicorp/amazon"
    }
  }
}

variable "version" {
  type    = string
  default = "1.0.0"
}

data "amazon-ami" "ubuntu-focal-east" {
  region = "us-east-2"
  filters = {
    name = "ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-*"
  }
  most_recent = true
  owners      = ["099720109477"]
}

source "amazon-ebs" "basic-example-east" {
  region         = "us-east-2"
  source_ami     = data.amazon-ami.ubuntu-focal-east.id
  instance_type  = "t2.small"
  ssh_username   = "ubuntu"
  ssh_agent_auth = false
  ami_name       = "packer_AWS_{{timestamp}}_v${var.version}"
}

data "amazon-ami" "ubuntu-focal-west" {
  region = "us-west-1"
  filters = {
    name = "ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-*"
  }
  most_recent = true
  owners      = ["099720109477"]
}

source "amazon-ebs" "basic-example-west" {
  region         = "us-west-1"
  source_ami     = data.amazon-ami.ubuntu-focal-west.id
  instance_type  = "t2.small"
  ssh_username   = "ubuntu"
  ssh_agent_auth = false
  ami_name       = "packer_AWS_{{timestamp}}_v${var.version}"
}

build {
  hcp_packer_registry {
    bucket_name = "learn-packer-ubuntu"
    description = <<EOT
Some nice description about the image being published to HCP Packer Registry.
    EOT
    bucket_labels = {
      "owner"          = "platform-team"
      "os"             = "Ubuntu",
      "ubuntu-version" = "Focal 20.04",
    }

    build_labels = {
      "build-time"   = timestamp()
      "build-source" = basename(path.cwd)
    }
  }
  sources = [
    "source.amazon-ebs.basic-example-east",
    "source.amazon-ebs.basic-example-west"
  ]
}
```

### Operating system and Environment details

OS, Architecture, and any other information you can provide about the
environment.

### Log Fragments and crash.log files

```
2022/07/18 16:24:18 packer-datasource-hcp-packer-image plugin: Serving a plugin connection...

Packer was unable to load a git sha. If your Packer template is not in a git
repo, please add a unique template fingerprint using the env var
HCP_PACKER_BUILD_FINGERPRINT. Error: repository does not exist

2022/07/18 16:24:18 [INFO] (telemetry) Finalizing.
Error: Unable to create a valid bucket object for HCP Packer Registry

Packer was unable to load a git sha. If your Packer template is not in a git
repo, please add a unique template fingerprint using the env var
HCP_PACKER_BUILD_FINGERPRINT. Error: repository does not exist


2022/07/18 16:24:18 waiting for all plugin processes to complete...
2022/07/18 16:24:18 ~/Development/packer/bin/packer: plugin process exited
2022/07/18 16:24:18 ~/Development/packer/bin/packer: plugin process exited
```

**Comment by lbajolet-hashicorp** [comment]
Just for clarification: this issue arises from the creation of the placeholder `Bucket` and `Iteration` during the initial loading phase of the configuration, no bucket or iteration is actually created as this happens only when we initialise the `Bucket`.
This happens only during `build` (SEE: `command/build.go +170`).

The issue here stems from the logic of `NewIteration` that errors when the iteration SHA cannot be determined (SEE: `internal/registry/types.iterations.go +44`).

Because of how it is nested, this will happen for all these commands:

* build
* validate
* console
* inspect

Note that this does not invalidate this issue, but it signals that we need to move some code around for this to only trigger when a build is actually being run.
