### ISSUE TITLE
Add support for EC2 Nitro Enclaves

### ISSUE THREAD

**Issue by urluba** [hashicorp/packer#11895]
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Please search the existing issues for relevant feature requests, and use the
reaction feature
(https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
to add upvotes to pre-existing requests.

#### Description

Nitro Enclave creates an isolated environment on the EC2 instance. This environment has its own kernel, processor and memory and can only communicate with the parent instance through a local socket.

Support of Nitro enclave is disabled by default and requires to be enabled at launch or on a stopped instance.
Packer currently does not allow to create an EC2 Instance with Nitro Enclave enabled.

#### Use Case(s)

Having an EC2 Instance with Nitro Enclave enabled allows us to use certificates saved in ACM with Nginx preventing the need to store sensitive date in the AMI. Thus someone able to retrieve the AMI don't leave with the private keys and/or passphrase.

#### Potential configuration

```
source "amazon-ebs" "example" {
    enclave_support = True
}
```

**Comment by ChiefGhostZero0x1** [comment]
Please clarify what you meant by "Thus someone able to retrieve the AMI don't leave with the private keys and/or passphrase."
