### ISSUE TITLE
Add mkisofs command or equivalent into hashicorp:packer Docker image

### ISSUE THREAD

**Issue by Fredouye** [hashicorp/packer#11908]
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Please search the existing issues for relevant feature requests, and use the
reaction feature
(https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
to add upvotes to pre-existing requests.

#### Description

Hi

current hashicorp:packer Docker image does not provide a tool to build ISO images, which would be very convenient when used with Gitlab CI/CD.

#### Use Case(s)

I'm using Packer with the vsphere-iso builder through GitLab CI/CD, to build VMware Linux templates.
My Kickstart file is provided using an ISO image, so Packer needs the xorriso / mkisofs command.

For the moment I'm using a "generic" Docker image (alpine, Debian) in which I download the Packer binary.
I've tested this .gitlab-ci.yml : 

```yaml
build-template:
  stage: build
  image:
     name: hashicorp/packer:1.8.2
     entrypoint: [""]
  dependencies:
    - prepare-json
  script:
  - echo "Building Packer template"
  - packer build -var-file packer_conf/vars.json rockylinux_9.json
```

which results in : 

```bash
$ echo "Building Packer template"
Building Packer template
$ packer build -var-file packer_conf/vars.json rockylinux_9.json
vsphere-iso: output will be in this color.
==> vsphere-iso: Creating CD disk...
Build 'vsphere-iso' errored after 76 milliseconds 159 microseconds: could not find a supported CD ISO creation command (the supported commands are: xorriso, mkisofs, hdiutil, oscdimg)
==> Wait completed after 76 milliseconds 214 microseconds
==> Some builds didn't complete successfully and had errors:
--> vsphere-iso: could not find a supported CD ISO creation command (the supported commands are: xorriso, mkisofs, hdiutil, oscdimg)
==> Builds finished but no artifacts were created.
```

#### Potential configuration

```
```

**Comment by KVInventoR** [comment]
I got the same issue with proxmox
