### ISSUE TITLE
Post-processor failed: failed to parse the ECR URL: 1234567890.dkr.ecr.ca-central-1.amazonaws.com

### ISSUE THREAD

**Issue by z9944x** [hashicorp/packer#11940]
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Overview of the Issue

our packer build is working using packer version 1.8.2.1 but failing when using packer 1.8.3.1 with this error :

Post-processor failed: failed to parse the ECR URL: 1234567890.dkr.ecr.ca-central-1.amazonaws.com
parse "1234567890.dkr.ecr.ca-central-1.amazonaws.com": invalid URI for request
it should be either of the form `public.ecr.aws/<registry_alias>/<registry_name>` or `<account number>.dkr.ecr.<region>.amazonaws.com`

our build.pck.hcl post-processor step are :

```
...
  post-processors {
    post-processor "docker-tag" {
      repository = "1234567890.dkr.ecr.ca-central-1.amazonaws.com/th/tools/base/dotnetcore"
      tags       = ["release-dotnetcore-latest"]
      only       = ["docker.dotnetcore"]
    }

    post-processor "docker-push" {
      ecr_login    = true
      login_server = "1234567890.dkr.ecr.ca-central-1.amazonaws.com"
      only         = ["docker.dotnetcore"]
    }
  }

```
#### Reproduction Steps

install packer 1.8.3.1
packer init .
packer build .

### Packer version

From `packer version 1.8.3.1`

### Operating system and Environment details

running on Amazon Linux2

**Comment by jmkeyes** [comment]
This is very similar to hashicorp/packer-plugin-docker#110.

**Comment by devashish-patel** [comment]
Hi @z9944x and @jmkeyes,

We have fixed the bug related to this in docker plugin version `v1.0.8`. Please update the plugin and everything should work fine as it used to be (aka no need to prefix the `login_server` value with `https://`)

Please feel free to reopen this issue, if you have questions or facing any issues.

Thanks for the patience!
