### ISSUE TITLE
https://rpm.releases.hashicorp.com/AmazonLinux/latest/x86_64/stable/repodata/c9af8a3098909c94bfa713605005bdec92ba7a29-primary.xml.gz: [Errno 14] HTTPS Error 404 - Not Found

### ISSUE THREAD

**Issue by ElenaKosobrodova** [hashicorp/packer#11959]
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue
Not Found error 404 during Packer installation.
Packer is installed  as: 
  sudo yum install --assumeyes yum-utils
  sudo yum-config-manager --add-repo "https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo"
  sudo yum install --assumeyes packer

The error:
https://rpm.releases.hashicorp.com/AmazonLinux/latest/x86_64/stable/repodata/c9af8a3098909c94bfa713605005bdec92ba7a29-primary.xml.gz: [Errno 14] HTTPS Error 404 - Not Found
One of the configured repositories failed (Hashicorp Stable - x86_64), and yum doesn't have enough cached data to continue.

#### Reproduction Steps

Steps to reproduce this issue

### Packer version

From `packer version`

### Simplified Packer Template

If the file is longer than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/) of the log or use the [Github detailed
format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d)
instead of posting it directly in the issue.

### Operating system and Environment details

OS, Architecture, and any other information you can provide about the
environment.

### Log Fragments and crash.log files

<img width="1228" alt="Screen Shot 2022-08-24 at 1 44 59 pm" src="https://user-images.githubusercontent.com/47466926/186324140-5904d327-2fb2-40bd-b071-6e7ad16de9f8.png">

Include appropriate log fragments. If the log is longer than a few dozen lines,
please include the URL to the [gist](https://gist.github.com/) of the log or
use the [Github detailed format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d) instead of posting it directly in the issue.

Set the env var `PACKER_LOG=1` for maximum log detail.

**Comment by munikoteswararao-chevuru** [comment]
now it is restored back and working as expected

**Comment by nywilken** [comment]
Hi @ElenaKosobrodova thanks for reporting this. 

There was an incident with the RPM repository earlier this week, which has now been resolved. You can find the timeline and status updates shared by the response team in [the incident report 1](https://status.hashicorp.com/incidents/1fysx522mvzg).

I'm going to close this issue, as all should be working now. But please feel free to reach out if you are still running into issues. Cheers!
