### ISSUE TITLE
Packer cannot find network in vCenter

### ISSUE THREAD

**Issue by eperts** [hashicorp/packer#11963]
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

I'm trying to run a Packer build to get a windows 10 template for Horizon VDI. My build runs fine in our lab environment, but in our production environment, it cannot find the correct network. There are several networks with the same name so I am specifying the entire path down to the correct network. Using the same structure that worked without issues in our lab environment, it does not work in the production environment. 

The error that comes back is: Invalid configuration for device '0'. 

I cannot use a different network for the production vCenter. 

When I cut it down to just the network name, it comes back with an error: path '<network name>' resolves to multiples provide a host to match or full network path. 

The path I'm using is, essentially: /<datacenter>/network/<switch>/<name of network>

Again, this works in our test vCenter, but not production. If anyone has run into this issue before, I'd appreciate any advice.

**Comment by jpinto13** [comment]
As added context for the problem described above, we are following the notes from documentation:
"[network] (string) - Set the network in which the VM will be connected to. If no network is specified, host must be specified to allow Packer to look for the available network. If the network is inside a network folder in vCenter, you need to provide the full path to the network."
As stated the path we use goes: "/DC/network/dvswitch/distributedportgroup", while using this string in our code packer fails with the error stated before. We need to identify how to provide the string for a Distributed Port Group that the same name is use on a different dvswitch inside the same Datacenter just like the below:
- /DC1/network/dvswitch1/distributedportgroup1
- /DC1/network/dvswitch2/distributedportgroup1
- /DC1/network/dvswitch3/distributedportgroup1

Thank you in advance for the assistance
