### ISSUE TITLE
Vsphere-iso unable to go into boot options (VM Powers ON after boot menu)

### ISSUE THREAD

**Issue by KrzesloSzatan** [hashicorp/packer#11964]
Hello, I am trying to run packer for a vsphere vm using vsphere-iso and i do have one small but very crucial problem.... And its the same both on EFI or normal BIOS.  I am able to get into boot options once for like 15 times.... The issue is that packer gets (or vsphere sends) information about VM is turned ON too late. When I go to the web console (instantly when it shows up and i compared it with console output from packer which is the same exact moment) its almost always past the moment where i can interrupt boot select and add boot_command. I always end up with packer trying to type in boot_command while native installer is already on. I have setup boot_wait parameter to -1s-10s and its like always vm starts before vsphere show it has actually started. 

I have tried to add 
configuration_parameters {
  "bootOptions.bootDelay": 10000
}
but nothing has changed and it doesn't work as when i add this manually via GUI. 

Sometimes it works fine, VM is powered ON and it shows the boot menu and packer interrupts it and everything works, but the whole point is so it won't do it once a year but every time i want it to run :) 

Do you have any ideas why it works (or not ?) like that and/or how to handle this issue ?

**Comment by KrzesloSzatan** [comment]
Any ideas ?

**Comment by tenthirtyam** [comment]
Hi @hc-github-team-packer 👋 - please move to `hashicorp/packer-plugin-vsphere`.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by KrzesloSzatan** [comment]
Still no ideas ?

**Comment by tenthirtyam** [comment]
Hi @KrzesloSzatan 👋 - please open this under the correct repo `hashicorp/packer-plugin-vsphere`.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by KrzesloSzatan** [comment]
> Hi @KrzesloSzatan 👋 - please open this under the correct repo `hashicorp/packer-plugin-vsphere`.
> 
> **Ryan Johnson** Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

Sure, made one here https://github.com/hashicorp/packer-plugin-vsphere/issues/228 i will close this one.
