### ISSUE TITLE
[Enhancement] Pass variables as arrays

### ISSUE THREAD

**Issue by 030** [hashicorp/packer#1202]
it would be nice to pass variables as arrays using packer build -var-file=path. If this is possible then separate variables files could be created for e.g. centos, scientific and ubuntu which are using a main json file. Now this is not possible as the boot command is different and cannot be passed as an array.

**Comment by dragon788** [comment]
It makes for some horribly ugly long lines in the JSON, but rasa is right, you don't want to use commas in the boot string, even though for 15.10 and 16.04 there are like 30 <bs> calls and then the actual boot arguments.

**Comment by gaelik** [comment]
does that still work with 1.1.0 ?

Got a json file with

`"boot_command": "<tab> text ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/{{user `kickstart-script`}}<enter><wait>"`

In the template I'm using the following entry in the builders:

`"boot_command": "{{user `boot_command`}}",`

When booting redhat, the variables .HTTPIP .HTTPPORT and user `kickstart` are not resolved...

`2017/09/24 20:25:21 packer: 2017/09/24 20:25:21 Sending char 't', code '[14 94]', shift false
2017/09/24 20:25:21 packer: 2017/09/24 20:25:21 Sending char 'e', code '[12 92]', shift false
2017/09/24 20:25:21 packer: 2017/09/24 20:25:21 Sending char 'x', code '[2d ad]', shift false
2017/09/24 20:25:21 packer: 2017/09/24 20:25:21 Sending char 't', code '[14 94]', shift false
2017/09/24 20:25:21 packer: 2017/09/24 20:25:21 Sending char ' ', code '[39 b9]', shift false
2017/09/24 20:25:21 packer: 2017/09/24 20:25:21 Sending char 'k', code '[25 a5]', shift false
2017/09/24 20:25:21 packer: 2017/09/24 20:25:21 Sending char 's', code '[1f 9f]', shift false
2017/09/24 20:25:21 packer: 2017/09/24 20:25:21 Sending char '=', code '[0d 8d]', shift false
2017/09/24 20:25:21 packer: 2017/09/24 20:25:21 Sending char 'h', code '[23 a3]', shift false
2017/09/24 20:25:21 packer: 2017/09/24 20:25:21 Sending char 't', code '[14 94]', shift false
2017/09/24 20:25:21 packer: 2017/09/24 20:25:21 Sending char 't', code '[14 94]', shift false
2017/09/24 20:25:21 packer: 2017/09/24 20:25:21 Sending char 'p', code '[19 99]', shift false
2017/09/24 20:25:21 packer: 2017/09/24 20:25:21 Sending char ':', code '[2a 27 aa a7]', shift true
2017/09/24 20:25:21 packer: 2017/09/24 20:25:21 Sending char '/', code '[35 b5]', shift false
2017/09/24 20:25:21 packer: 2017/09/24 20:25:21 Sending char '/', code '[35 b5]', shift false
2017/09/24 20:25:21 packer: 2017/09/24 20:25:21 Sending char '{', code '[2a 1a aa 9a]', shift true
2017/09/24 20:25:21 packer: 2017/09/24 20:25:21 Sending char '{', code '[2a 1a aa 9a]', shift true
2017/09/24 20:25:21 packer: 2017/09/24 20:25:21 Sending char ' ', code '[39 b9]', shift false
2017/09/24 20:25:21 packer: 2017/09/24 20:25:21 Sending char '.', code '[34 b4]', shift false
2017/09/24 20:25:21 packer: 2017/09/24 20:25:21 Sending char 'H', code '[2a 23 aa a3]', shift true
2017/09/24 20:25:21 packer: 2017/09/24 20:25:21 Sending char 'T', code '[2a 14 aa 94]', shift true
2017/09/24 20:25:21 packer: 2017/09/24 20:25:21 Sending char 'T', code '[2a 14 aa 94]', shift true
2017/09/24 20:25:21 packer: 2017/09/24 20:25:21 Sending char 'P', code '[2a 19 aa 99]', shift true
2017/09/24 20:25:21 packer: 2017/09/24 20:25:21 Sending char 'I', code '[2a 17 aa 97]', shift true
2017/09/24 20:25:21 packer: 2017/09/24 20:25:21 Sending char 'P', code '[2a 19 aa 99]', shift true
2017/09/24 20:25:21 packer: 2017/09/24 20:25:21 Sending char ' ', code '[39 b9]', shift false
2017/09/24 20:25:21 packer: 2017/09/24 20:25:21 Sending char '}', code '[2a 1b aa 9b]', shift true
2017/09/24 20:25:21 packer: 2017/09/24 20:25:21 Sending char '}', code '[2a 1b aa 9b]', shift true
2017/09/24 20:25:21 packer: 2017/09/24 20:25:21 Sending char ':', code '[2a 27 aa a7]', shift true
2017/09/24 20:25:21 packer: 2017/09/24 20:25:21 Sending char '{', code '[2a 1a aa 9a]', shift true
2017/09/24 20:25:21 packer: 2017/09/24 20:25:21 Sending char '{', code '[2a 1a aa 9a]', shift true
2017/09/24 20:25:21 packer: 2017/09/24 20:25:21 Sending char ' ', code '[39 b9]', shift false
2017/09/24 20:25:21 packer: 2017/09/24 20:25:21 Sending char '.', code '[34 b4]', shift false
2017/09/24 20:25:21 packer: 2017/09/24 20:25:21 Sending char 'H', code '[2a 23 aa a3]', shift true
2017/09/24 20:25:21 packer: 2017/09/24 20:25:21 Sending char 'T', code '[2a 14 aa 94]', shift true
2017/09/24 20:25:21 packer: 2017/09/24 20:25:21 Sending char 'T', code '[2a 14 aa 94]', shift true
2017/09/24 20:25:21 packer: 2017/09/24 20:25:21 Sending char 'P', code '[2a 19 aa 99]', shift true
2017/09/24 20:25:21 packer: 2017/09/24 20:25:21 Sending char 'P', code '[2a 19 aa 99]', shift true
2017/09/24 20:25:21 packer: 2017/09/24 20:25:21 Sending char 'o', code '[18 98]', shift false
2017/09/24 20:25:21 packer: 2017/09/24 20:25:21 Sending char 'r', code '[13 93]', shift false
2017/09/24 20:25:21 packer: 2017/09/24 20:25:21 Sending char 't', code '[14 94]', shift false
`

**Comment by rickard-von-essen** [comment]
@gaelik User variables _are not_ interpolated.
