### ISSUE TITLE
Why it's not possible to choose Bios legacy or UEFI on vmware-iso

### ISSUE THREAD

**Issue by filoucrackeur** [hashicorp/packer#12041]
It's not possible to choose firmware (Bios or UEFI) with vmware-iso 

https://www.packer.io/plugins/builders/vmware/iso

but it's possible with vsphere-iso why? do you have a workaround ?

https://www.packer.io/plugins/builders/vsphere/vsphere-iso#firmware

cordialy

**Comment by tenthirtyam** [comment]
Please refer to the [existing issue](https://github.com/hashicorp/packer-plugin-vmware/issues/58) for tracking the enhancement for the `hashicorp/packer-plugin-vmware plugin`.

This issue may be closed. cc @nywilken 

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.
