### ISSUE TITLE
SSH Communicator fails when using signed key for bastion connection 

### ISSUE THREAD

**Issue by cfmw3** [hashicorp/packer#12075]
Hello, I wasn't sure which project to file this bug under, so I am doing both for visibility. 

Please see https://github.com/hashicorp/packer-plugin-sdk/issues/136 for the issue. 

I can close whichever issue is on the wrong project.

**Comment by nywilken** [comment]
Hi @cfmw3 thanks for opening up this issue. The correct repo is packer-plugin-sdk. I'll close this one and work on getting a member of the team to take a look at https://github.com/hashicorp/packer-plugin-sdk/issues/136. Cheers!
