### ISSUE TITLE
Powershell install-module command always times out in Packer 1.8.5.

### ISSUE THREAD

**Issue by agregory23** [hashicorp/packer#12198]
Thought I would ask here before submitting a bug.  When running the following command in the provisioner or even in a powershell script on an Azure host, it never completes:

Install-Module -Name Az -Repository PSGallery -Force

Pretty simple command that almost always times out.  It installs a few things and when run in a standard powershell window, usually takes several minutes to complete. Is it something I am doing?  I have run it in a ps1 file and like this directly with the same results:

`    
{
      "type": "powershell",
      "timeout": "120m",
      "start_retry_timeout": "15m",
      "elevated_user": "packer",
      "elevated_password": "p@ssword123!",
      "inline": [
        "Install-Module -Name Az -Repository PSGallery -Force"
      ]
    },
`

**Comment by ph5x5** [comment]
I see the same issue with the Packer 1.8.5
