### ISSUE TITLE
Cannot read variables defined in a json template via `packer console`

### ISSUE THREAD

**Issue by lonegunmanb** [hashicorp/packer#12209]
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Overview of the Issue

I was following the [document](https://developer.hashicorp.com/packer/docs/commands/console#usage-examples-repl-session-json) to learn `packer console`, I have a json template file named `example_template.json` with the following content:

```json
{
    "variables": {
        "myvar": "asdf"
    }
}
```

Then I executed the following command as the document instructed:

```shell
$ packer console example_template.json
```

In the repl session, I tried to access the variable but got nothing:

```shell
> {{user "myvar"}}
```

I tried `variables` command:

```shell
>variables


```

#### Reproduction Steps

Steps to reproduce this issue

### Packer version

Packer v1.8.4

Your version of Packer is out of date! The latest version
is 1.8.5. You can update by downloading from www.packer.io/downloads

### Simplified Packer Template

```json
{
    "variables": {
        "myvar": "asdf"
    }
}
```

### Operating system and Environment details

Windows adm64

### Log Fragments and crash.log files

Include appropriate log fragments. If the log is longer than a few dozen lines,
please include the URL to the [gist](https://gist.github.com/) of the log or
use the [Github detailed format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d) instead of posting it directly in the issue.

Set the env var `PACKER_LOG=1` for maximum log detail.

**Comment by SweetestSufferance** [comment]
Have you tried:
`{{user `myvar`}}`

**Comment by lonegunmanb** [comment]
Thanks @SweetestSufferance for your reply, but your approach still has no luck, and the `variables` command inside repl session got not output.

**Comment by SweetestSufferance** [comment]
I guess I have to pay a little more attention.  Sorry.  
Yeah, that example seems to leave a little bit to be desired, that or I'm confused again.

try this:
```
{
  "variables":
    {
      "test1": "test1",
      "test2": "test2"
    },
  "builders": [
    {
      "type": "null",
      "communicator": "none"
    }
  ],
  "provisioners": [
    {
      "type": "shell",
      "inline": ["echo hellooooo"]
    }
  ]
}
```

**Comment by lonegunmanb** [comment]
@SweetestSufferance Yeah you're right, I need a builder to make this work, thanks!
