### ISSUE TITLE
PACKER CRASHED While running hcl2_upgrade command

### ISSUE THREAD

**Issue by Mahemud-Infra** [hashicorp/packer#12297]
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or ha
[crash.log](https://github.com/hashicorp/packer/files/10873507/crash.log)
ve submitted a pull request, please leave a comment

When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

A paragraph or two about the issue you're experiencing.

#### Reproduction Steps

Steps to reproduce this issue

### Packer version

From `packer version`

### Simplified Packer Template

If the file is longer than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/) of the log or use the [Github detailed
format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d)
instead of posting it directly in the issue.

### Operating system and Environment details

OS, Architecture, and any other information you can provide about the
environment.

### Log Fragments and crash.log files

Include appropriate log fragments. If the log is longer than a few dozen lines,
please include the URL to the [gist](https://gist.github.com/) of the log or
use the [Github detailed format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d) instead of posting it directly in the issue.

Set the env var `PACKER_LOG=1` for maximum log detail.

**Comment by nywilken** [comment]
Hi @Mahemud-Infra thanks for reporting this issue. Can you please provide the details requested in the bug report template to help us better triage the issue. Specifically, a minimal JSON template that causes the crash, the version of Packer, and the operating system you are executing Packer on. 

I look forward to hearing back.

**Comment by nywilken** [comment]
Seeing as there is no update I'm going to close this issue. We had a crash in 1.8.5 when using variables in a variables definition file but that was fixed in 1.8.6. If you are still running into issue after upgrading to the latest version of Packer please open a new issue with the requested information in the bug issue template. Thank you.
