### ISSUE TITLE
Vsphere Multiple Controllers Multiple disks.  OS Gets installed on wrong disk

### ISSUE THREAD

**Issue by dionrowney** [hashicorp/packer#12327]
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Overview of the Issue

We are trying to use packer to create a template VM with 4 controllers and multiple disks attached to each.

The disk to controller is working, but unfortunately when the OS boots up it scans the controllers and disks and will install on the wrong disk if they scan out of order.

We believe this is because the OS (linux and windows both) scan the hardware sorting the controllers by their WWN.

Here is the example of the way they are defined in the vmx when they appear out of order:

“scsi0.sasWWID” = “50 05 05 67 ad 2e 69 b0”
“scsi1.sasWWID” = “50 05 05 67 ad 2e 68 b0”
“scsi2.sasWWID” = “50 05 05 67 ad 2e 6b b0”
“scsi3.sasWWID” = “50 05 05 67 ad 2e 6c b0”

and as you can see the controller WWIDs are in the wrong order when sorted.

Is it possible to hard code set the WWIds as part of the sphere-iso controller source var?

We tried the configuration_parameters to set the WWIDs but packer just overwrote them. If there was a configuration_parameters_post that allowed modification after before boot that may also work.

Or is there a better way for this?  maybe powershell to change these IDs after VM creation but before first boot up?

#### Reproduction Steps

Build a VM with 4 controlllers and one disk attached to each. 

The review the sasWWID values.  Or try to consistently install an OS on what the OS believes ois the 1st disk on the first controller (/dev/sda)

### Packer version

1.8.6

### Simplified Packer Template

`
source "vsphere-iso" "linux-rhel" {

  // vCenter Server Endpoint Settings and Credentials
  vcenter_server      = var.vsphere_endpoint
  username            = var.vsphere_username
  password            = var.vsphere_password
  insecure_connection = var.vsphere_insecure_connection

  // vSphere Settings
  datacenter = var.vsphere_datacenter
  cluster    = var.vsphere_cluster
  resource_pool = var.vsphere_resource_pool
  datastore  = var.vsphere_datastore
  folder     = var.vsphere_folder

  // Virtual Machine Settings
  vm_name              = local.vm_name
  guest_os_type        = var.vm_guest_os_type
 ...
  disk_controller_type = ["pvscsi","pvscsi","pvscsi","pvscsi"]
  storage {
    disk_size             = 3072
    disk_thin_provisioned = false
    disk_controller_index = 0
  }
  storage {
    disk_size             = 30720
    disk_thin_provisioned = false
    disk_controller_index = 0
  }
  storage {
    disk_size             = 10240
    disk_thin_provisioned = false
    disk_controller_index = 1
  }
  storage {
    disk_size             = 11264
    disk_thin_provisioned = false
    disk_controller_index = 2
  }
  storage {
    disk_size             = 12264
    disk_thin_provisioned = false
    disk_controller_index = 3
  }
  // Tried to pass WWIDs in below but they just get overwritten by pack or vmware.
  configuration_parameters = {
    "disk.EnableUUID"  = "TRUE"
    "scsi0.sasWWID" = "50 05 05 67 ad 2e 00 b0"
    "scsi1.sasWWID" = "50 05 05 67 ad 2e 01 b0"
    "scsi2.sasWWID" = "50 05 05 67 ad 2e 02 b0"
    "scsi3.sasWWID" = "50 05 05 67 ad 2e 03 b0"
  }
}
`

### Operating system and Environment details

RHEL9, Windows2022, Rocky9

**Comment by tenthirtyam** [comment]
The issue should be open for the plugin in it’s repository. https://github.com/hashicorp/packer-plugin-vsphere.

**Comment by dionrowney** [comment]
Moved to https://github.com/hashicorp/packer-plugin-vsphere/issues/265
