### ISSUE TITLE
"packer plugins installed" should list plugins in "hostname/namespace/name" format

### ISSUE THREAD

**Issue by edigaryev** [hashicorp/packer#12321]
Let's say you want to clean up installed plugins:

```
% packer plugins installed
/opt/homebrew/bin/github.com/cirruslabs/tart/packer-plugin-tart_v1.0.1_x5.0_darwin_arm64
```

You copy the plugin name from the output and run `packer plugins remove`:

```
% packer plugins remove /opt/homebrew/bin/github.com/cirruslabs/tart/packer-plugin-tart_v1.0.1_x5.0_darwin_arm64
<nil>: Invalid plugin source string; The "source" attribute must be in the format "hostname/namespace/name"
```

However it fails, because the right way to invoke it would be:

```
% packer plugins remove github.com/cirruslabs/tart
/opt/homebrew/bin/github.com/cirruslabs/tart/packer-plugin-tart_v1.0.1_x5.0_darwin_arm64
```

It would be nice if `packer plugins installed` would emit the plugin name in the right format in the first place.

I'm using latest Packer v1.8.6.

**Comment by nywilken** [comment]
@edigaryev this is a great idea. Would you be interested in taking  a look at implementing it? 

I think it could be nice  to have a flag that only shows the source URIs for the installed plugins. Maybe something like 
```
> packer plugins installed --sources
github.com/rgl/windows-update
github.com/hashicorp/inspec
github.com/hashicorp/parallels
github.com/hashicorp/hyperv
github.com/hashicorp/vmware
github.com/hashicorp/docker
github.com/hashicorp/qemu
github.com/hashicorp/googlecompute
github.com/hashicorp/amazon
github.com/mondoohq/cnspec
```


```
> packer plugins installed --help
Usage: packer plugins installed

  This command lists all installed plugin binaries that match with the current
  OS and architecture. Packer's API version will be ignored.

Options:
   --sources          Only show plugin source URIs
```

**Comment by nywilken** [comment]
On a side note, having the ability to pipe source URIs to `packer plugins remove` would also be nice 😄

**Comment by nywilken** [comment]
Like I said this is a good idea. I've added it to our internal board but please feel free to take it on if interested. The same is true for any community contributor that might be interested in working on this request.
