### ISSUE TITLE
[question] compile amazon-ebs plugin tag 1.2.2 with Packer 1.8.6

### ISSUE THREAD

**Issue by lmayorga1980** [hashicorp/packer#12345]
Is it possible to reference a different plugin version with `packer 1.8.6` instead of the default one pointing to `1.21`? If not, are there any docs to compile packer itself with that version of the amazon plugin?

I would like to test this release https://github.com/hashicorp/packer-plugin-amazon/releases/tag/v1.2.2 
`ebs: add support for fast-launch by @lbajolet-hashicorp in https://github.com/hashicorp/packer-plugin-amazon/pull/347`

**Comment by nywilken** [comment]
Hi @lmayorga1980 thanks for reaching out. Yes, you can tell Packer to use a different version of the plugin. Depending on the template type you are using you can take one of the following two approaches. 

If using HCL2 template types I recommend adding the required_plugins block to the top of your HCL template. By including this configuration to the top of your template file you are telling Packer that it must use the following version of the Amazon plugin for the build. You can then install the plugin by running `packer init` on the template directory or template file. 

```
packer {
  required_plugins {
    amazon = {
      version = ">= 1.2.2"
      source  = "github.com/hashicorp/amazon"
    }
  }
}
```

Alternatively, if you are using legacy JSON templates then you will have to install the plugin manually via the `packer plugins` command. Once installed Packer will find new plugin binary from the default plugin install path and use that one over the bundled version of the Amazon plugin. 

Running `packer plugins install "github.com/hashicorp/amazon" ">=1.2.2"` will download and install the latest plugin binaries for you. Then running `packer build template.json` will run with the latest installed binary as they take precedence of any bundled versions.

```
~>  packer plugins install "github.com/hashicorp/amazon" ">=1.2.2"
Installed plugin github.com/hashicorp/amazon v1.2.2 in "/Users/dev/.packer.d/plugins/github.com/hashicorp/amazon/packer-plugin-amazon_v1.2.2_x5.0_darwin_arm64"
```


I'm going to close this issue as this should be enough to get you going. But if you run into issue installing the latest plugin version please feel free to reach out.
