### ISSUE TITLE
packer 1.8.6-1 recursively stats all files from working dir

### ISSUE THREAD

**Issue by mrsiesta** [hashicorp/packer#12352]
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

Recently upgraded to the latest available packer version `1.8.6-1` on ubuntu 18.04. In our configuration `packer` runs from a working directory that hosts an NFS volume as well. We noted that just running `packer --version` was taking minutes to complete. Upon inspection of the system calls, I found that packer was recursively walking the directory structure of the current working dir:

```
newfstatat(AT_FDCWD, "/workdir/NFS_volume/small_file", {st_mode=S_IFREG|0640, st_size=113, ...}, 0) = 0
futex(0x8fab5d8, FUTEX_WAKE_PRIVATE, 1) = 1
```
Because this NFS volume contains many thousand small files, packer incurred a major performance degradation.

```
root@test_host:/dir_with_nfs_mount# time packer --version
1.8.6

real	2m15.218s
user	0m1.149s
sys	0m5.929s

root@test_host:/dir_with_nfs_mount# mkdir empty_dir; cd empty_dir/
root@test_host:/dir_with_nfs_mount/empty_dir# time packer --version
1.8.6

real	0m0.364s
user	0m0.097s
sys	0m0.032s
```

#### Reproduction Steps

1. Mount an NFS filesystem with many small files in a directory. 
2. Run `packer --version` and note that it takes an extremely long amount of time as opposed to running `packer` in a directory with nothing else in it.

### Packer version

From `packer version`

### Simplified Packer Template

If the file is longer than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/) of the log or use the [Github detailed
format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d)
instead of posting it directly in the issue.

### Operating system and Environment details

Linux test_host 5.4.0-1094-aws #102~18.04.1-Ubuntu SMP

### Log Fragments and crash.log files

Include appropriate log fragments. If the log is longer than a few dozen lines,
please include the URL to the [gist](https://gist.github.com/) of the log or
use the [Github detailed format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d) instead of posting it directly in the issue.

Set the env var `PACKER_LOG=1` for maximum log detail.

**Comment by nywilken** [comment]
Interesting thanks for reporting this. Does this same issue with previous versions of Packer?

My first thought here would be around the plugin discovery logic, which checks known directories including the current directory for Packer plugins.

**Comment by mrsiesta** [comment]
> Interesting thanks for reporting this. Does this same issue with previous versions of Packer?
> 
> My first thought here would be around the plugin discovery logic, which checks known directories including the current directory for Packer plugins.

This was not happening with our previous version of packer `1.7.6`

**Comment by nywilken** [comment]
Thank you for this extra bit of info. I will work through the versions to see where this started to occur. I would expect versions leading up 1.8.0 to work the same as 1.7.6. But I can't say without testing each one.
