### ISSUE TITLE
packer tries to fork/exec plugin SHA256SUM file

### ISSUE THREAD

**Issue by messense** [hashicorp/packer#12405]
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Overview of the Issue

When external plugin like `packer-plugin-amazon` is installed in the same directory as the `packer` bin, packer tries to fork/exec the checksum file of the plugin which causes permission denied error.

#### Reproduction Steps

On Ubuntu 22.04

* install packer via apt-get
* download packer-plugin-amazon v1.2.5 and extract it to `/usr/bin`
* put sha256sum of the plugin binary to `/usr/bin/packer-plugin-amazon_v1.2.5_x5.0_linux_amd64_SHA256SUM`
* run `packer version`

### Packer version

Packer v1.8.7

### Simplified Packer Template

N/A

### Operating system and Environment details

Ubuntu 22.04 x86_64

### Log Fragments and crash.log files

```bash
$ PACKER_LOG=1 packer version
2023/05/05 15:08:46 [INFO] Packer version: 1.8.7 [go1.20.4 linux amd64]
2023/05/05 15:08:46 [TRACE] discovering plugins in /usr/bin
2023/05/05 15:08:46 [DEBUG] Discovered plugin: amazon = /usr/bin/X11/X11/X11/packer-plugin-amazon_v1.2.5_x5.0_linux_amd64
2023/05/05 15:08:46 [INFO] found external [chroot ebs ebssurrogate ebsvolume instance] builders from amazon plugin
2023/05/05 15:08:46 [INFO] found external [import] post-processors from amazon plugin
2023/05/05 15:08:46 found external [ami parameterstore secretsmanager] datasource from amazon plugin
2023/05/05 15:08:46 [DEBUG] Discovered plugin: amazon = /usr/bin/packer-plugin-amazon_v1.2.5_x5.0_linux_amd64
2023/05/05 15:08:46 [DEBUG] Discovered plugin: amazon = /usr/bin/packer-plugin-amazon_v1.2.5_x5.0_linux_amd64_SHA256SUM
 Error loading configuration:

fork/exec /usr/bin/packer-plugin-amazon_v1.2.5_x5.0_linux_amd64_SHA256SUM: permission denied
```

**Comment by nywilken** [comment]
Thanks for reporting @messense I've confirmed the issue and will work on getting a fix for the next release.

**Comment by messense** [comment]
> That said, for multi-component plugins like `packer-plugin-amazon` you can install the plugin using the `packer plugins install` command, which will install the plugin into the plugins directory and ensure that only the plugin gets loaded.

The thing is I wasn't able to use `packer init`/`packer install` behind a corporate firewall, so I have to download and install it manually.
