### ISSUE TITLE
[Bug] Packer behaving differently than standalone QEMU trying to start cloud-init image

### ISSUE THREAD

**Issue by MalikKillian** [hashicorp/packer#12407]
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

I have noticed a difference of behavior between Packer and running the equivalent commands in QEMU by itself. I am not able to get cloud-init to work (config served via HTTP) using Packer but it works just fine if I run QEMU on its own.

#### Reproduction Steps

1. Clone this fork I made: https://github.com/MalikKillian/packer.git
2. Checkout the "test" branch
3. Navigate to the test/bug-reproduction folder
4. Update the `start-qemu.sh` script to be executable
   a. Be safe, take a look at the script first! 
5. Run a HTTP server to serve the files under the http folder
   a. I normally use `python3 -m http.server -d ./http/`
7. Run the `start-qemu.sh` script

After a few seconds you should see a prompt for the VM. Check the logs of the HTTP server and you should see the cloud-init files were accessed. You can also login to see that it executed properly. Now, we'll perform essentially the same actions via Packer.

1. Restart the HTTP server or hit enter a few times so we don't get new and old logs confused
2. Run `PACKER_LOG=1 packer build debian.pkr.hcl`

After a few seconds you will see a prompt for the VM. Check the HTTP logs and you should see no attempts to access the files on the HTTP server. Also, compare the line from the Packer logs about how QEMU was started (example below).

```
2023/05/05 09:10:44 packer-builder-qemu plugin: Executing /usr/bin/qemu-system-x86_64: []string{"-vnc", "127.0.0.1:93", "-boot", "c", "-m", "2048M", "-smbios", "type=1,serial=ds='nocloud-net;s=http://10.0.2.2:8000/'", "-cpu", "host", "-display", "gtk", "-name", "debian-vm", "-machine", "type=pc,accel=kvm", "-netdev", "user,id=user.0,hostfwd=tcp::3266-:22", "-drive", "file=builds/debian-vm,if=virtio,cache=writeback,discard=ignore,format=qcow2", "-smp", "1", "-device", "virtio-net,netdev=user.0"}
2023/05/05 09:10:44 packer-builder-qemu plugin: Started Qemu.
```

Other than port numbers and the location of the image the QEMU command run by my script and by Packer is identical.

### Packer version

~~1.8.6~~ 1.8.7

I'll try the latest in just a few minutes. I don't want something to happen in the meantime and I lose everything I typed. GitHub really needs a "Save Draft" feature.

_Just upgraded. Same behavior in both versions._

### Simplified Packer Template

```
variable "img_url" {
  # Original URL: https://cloud.debian.org/images/cloud/bullseye/20230124-1270/debian-11-genericcloud-amd64-20230124-1270.qcow2
  default = "./debian-11-genericcloud-amd64-20230124-1270.qcow2"
}

source "qemu" "linux-os" {
  iso_url           = var.img_url
  # Bad practice, but we're just testing
  iso_checksum      = "none"
  iso_target_extension = "qcow2"
  disk_image        = true
  skip_resize_disk  = true
  use_backing_file  = false
  output_directory  = "builds"
  shutdown_command  = "echo 'foobarbaz' | sudo -S shutdown -P now"
  format            = "qcow2"
  cpu_model         = "host"
  accelerator       = "kvm"
  vm_name           = "debian-vm"
  net_device        = "virtio-net"
  ssh_username      = "john"
  ssh_password      = "foobarbaz"
  ssh_timeout       = "5m"
  headless          = "false"
  # Start an HTTP server just to get HTTPIP -- we'll use a separate server
  http_directory    = "http"
  qemuargs = [
    ["-m", "2048M"],
    ["-smbios", "type=1,serial=ds='nocloud-net;s=http://{{ .HTTPIP }}:8000/'"],
  ]
}

build {
  sources = ["source.qemu.linux-os"]
}
```

### Operating system and Environment details

```bash
$ cat /etc/*-release | grep "VERSION="
VERSION="22.04.2 LTS (Jammy Jellyfish)"
$ cat /proc/version
Linux version 5.15.0-71-generic (buildd@lcy02-amd64-044) (gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #78-Ubuntu SMP Tue Apr 18 09:00:29 UTC 2023
```

### Log Fragments and crash.log files

Logs from executing Packer (I shutdown the VM and canceled when it attempted to connect with SSH):
https://gist.github.com/MalikKillian/ccbf76fef5c867c33b856ac018d168eb

**Comment by MalikKillian** [comment]
So I went so far as to compare the exact commands as they appeared in ps. The difference was insanely subtle.

QEMU as started by Packer:
```bash
$ ps -fa | grep "qemu-system" | grep -v "grep"
malik     39687   39669 13 22:06 pts/2    00:00:27 /usr/bin/qemu-system-x86_64 -display gtk -device virtio-net,netdev=user.0 -drive file=builds/debian-vm,if=virtio,cache=writeback,discard=ignore,format=qcow2 -name debian-vm -smp 1 -cpu host -netdev user,id=user.0,hostfwd=tcp::3487-:22 -vnc 127.0.0.1:28 -m 2048M -smbios type=1,serial=ds='nocloud-net;s=http://10.0.2.2:8000/' -boot c -machine type=pc,accel=kvm
```

QEMU as started from the command line:
```bash

/usr/bin/qemu-system-x86_64 -machine type=pc,accel=kvm -boot c -vnc 127.0.0.1:25 -display gtk -device virtio-net,netdev=user.0 -name debian-vm -netdev user,id=user.0,hostfwd=tcp::2693-:22 -m 2048M -smbios type=1,serial=ds=nocloud-net;s=http://10.0.2.2:8000/ -drive file=builds/debian-vm,if=virtio,cache=writeback,discard=ignore,format=qcow2 -smp 1 -cpu host
Again, this build did not run cloud-init.

I made a copy from the same file as Packer did (from ~/.cache/packer/), placed it in the same folder with a new name, ran the same command as above (tweaking ports and the location of the file), and cloud-init worked as expected.

To see if the image was somehow modified in transit I ran packer with the `-debug` flag and performed a sha256sum on the image in the `.cache/packer` folder. It matched the hash from the image repository. Same thing when the image was copied to the `builds` folder in the current directory.

**Comment by dbnicholson** [comment]
> I'll leave it up to the maintainers as to whether or not this is a bug or worth an update to the documentation or whatever. Either way I'm back in business!

I was just doing something similar and had to think about whether to include the single quotes or not. I decided that I shouldn't under the assumption that packer is likely executing the array of arguments directly. When you run qemu via a shell, the shell is interpreting and removing the single quotes before executing the arguments. It might be helpful if the documentation explicitly says that `qemuargs` aren't executed with a shell and shell special characters don't need to be handled. The special character in this case is the `;` in the `serial` value. A shell needs that to be quoted or escaped, but qemu will use the value verbatim and cloud-init won't like the single quote it finds there.
