### ISSUE TITLE
Packer no longer discovers plugins in CWD successfully

### ISSUE THREAD

**Issue by dilyar85** [hashicorp/packer#12540]
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Packer no longer discovers plugins in CWD successfully

In the latest release (version 1.9.2), Packer seems to be using the relative path when discovering plugins from the current working directory. Consequently, these plugins are skipped as they are not executable from `exec.LookPath()`.

This issue is not present in the previous version (1.9.1), as shown in the logs below.

#### Reproduction Steps

1. Upgrade Packer to the latest version (1.9.2).
2. Manually download and build an external plugin binary (e.g. [packer-plugin-vsphere](https://github.com/hashicorp/packer-plugin-vsphere/blob/main/builder/vsphere/examples/supervisor/general-template.pkr.hcl))
3. Run `packer build` from the directory containing the external plugin binary.

### Packer version

```
$ packer version
Packer v1.9.2
```

### Simplified Packer Template

https://github.com/hashicorp/packer-plugin-vsphere/blob/main/builder/vsphere/examples/supervisor/general-template.pkr.hcl

### Operating system and Environment details
MacOS 13.4.1

#### Packer 1.9.2 [Failure ❌ ]

```
2023/07/26 20:26:23 [INFO] Packer version: 1.9.2 [go1.20.4 darwin amd64]
2023/07/26 20:26:23 [TRACE] discovering plugins in /usr/local/bin
2023/07/26 20:26:23 [TRACE] discovering plugins in .
2023/07/26 20:26:23 [TRACE] discovering plugins in /Users/sdiliyaer/.config/packer/plugins
2023/07/26 20:26:23 [INFO] Discovered potential plugin: vsphere = /Users/sdiliyaer/.config/packer/plugins/github.com/hashicorp/vsphere/packer-plugin-vsphere_v1.0.3_x5.0_darwin_amd64
2023/07/26 20:26:24 [INFO] found external [clone iso] builders from vsphere plugin
2023/07/26 20:26:24 [INFO] found external [-packer-default-plugin-name- template] post-processors from vsphere plugin
2023/07/26 20:26:24 [INFO] Discovered potential plugin: vsphere = packer-plugin-vsphere
2023/07/26 20:26:24 [WARN] "packer-plugin-vsphere" is not executable; skipping
...

  on builder/vsphere/examples/supervisor/general-template.pkr.hcl line 44:
  (source code not available)

known builders: [googlecompute azure-arm amazon-ebs vsphere-clone virtualbox-vm
file null amazon-ebsvolume qemu amazon-chroot virtualbox-ovf vmware-iso docker
amazon-ebssurrogate vagrant vmware-vmx azure-dtl amazon-instance virtualbox-iso
vsphere-iso azure-chroot]

Error: Unknown source type vsphere-supervisor
```

#### Packer 1.9.1 [Success ✅]

```
2023/07/26 21:23:05 [INFO] Packer version: 1.9.1 [go1.20.4 darwin amd64]
2023/07/26 21:23:05 [TRACE] discovering plugins in /Users/sdiliyaer/packer-plugin-vsphere
2023/07/26 21:23:05 [DEBUG] Discovered plugin: vsphere = /Users/sdiliyaer/packer-plugin-vsphere/packer-plugin-vsphere
2023/07/26 21:23:05 [INFO] found external [clone iso supervisor] builders from vsphere plugin
2023/07/26 21:23:05 [INFO] found external [-packer-default-plugin-name- template] post-processors from vsphere plugin
2023/07/26 21:23:05 [TRACE] discovering plugins in /Users/sdiliyaer/.config/packer/plugins
2023/07/26 21:23:05 [TRACE] discovering plugins in .
2023/07/26 21:23:06 [DEBUG] Discovered plugin: vsphere = /Users/sdiliyaer/packer-plugin-vsphere/packer-plugin-vsphere
2023/07/26 21:23:06 [INFO] found external [clone iso supervisor] builders from vsphere plugin
2023/07/26 21:23:06 [INFO] found external [-packer-default-plugin-name- template] post-processors from vsphere plugin
...
2023/07/26 21:23:06 [TRACE] Starting external plugin /Users/sdiliyaer/packer-plugin-vsphere/packer-plugin-vsphere start builder supervisor
2023/07/26 21:23:06 Starting plugin: /Users/sdiliyaer/packer-plugin-vsphere/packer-plugin-vsphere []string{"/Users/sdiliyaer/packer-plugin-vsphere/packer-plugin-vsphere", "start", "builder", "supervisor"}
```

**Comment by nywilken** [comment]
Hi @dilyar85 thanks for bubbling up this issue. I'm going to close this issue in favor of #12543, which is where I am tracking the thread from the Packer forum. I have a fix for this issue in #12544 if you want to pull it down and give it a try.

**Comment by nywilken** [comment]
I should probably mention that placing the custom dev binary under the $PACKER_CONFIG_DIR/plugins/ directory is a workaround until the fix is released.

**Comment by nywilken** [comment]
Hello :wave: thanks again for reporting, this should be fixed by #12544. There will be test binaries made available in the latest [nightly](https://github.com/hashicorp/packer/releases/tag/nightly) for testing prior to the next release. If you would like to test the fix and report back that would be greatly appreciated.

**Comment by dilyar85** [comment]
Thanks @nywilken for promptly fixing this issue. I downloaded the nightly release and confirmed that it can discover our plugin in CWD successfully.

**Comment by nywilken** [comment]
Thanks for testing @dilyar85 we plan to release 1.9.3 with this fix next week.
