### ISSUE TITLE
Bump github.com/golang-jwt/jwt/v4 version to v4.4.3

### ISSUE THREAD

**Issue by Bjyothi2023** [hashicorp/packer#12564]
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Overview of the Issue

Vulnerability "PRISMA-2022-0270" is reported in packer due to "github.com/golang-jwt/jwt/v4", and fix is available in v4.4.3

#### Reproduction Steps

Running any security scanner tool

### Packer version

From `1.9.2`

**Comment by nywilken** [comment]
Thanks for reporting this issue. The vulnerable package has been removed and the fix will be in the next Packer release.
