### ISSUE TITLE
Error in launching source AWS instance when SCP requires tags

### ISSUE THREAD

**Issue by karansingh-amagi** [hashicorp/packer#12624]
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

We have an SCP on our AWS account which restricts resources to be created when a particular tag is missing. This is not allowing source instance creation with an Unauthorised error.

#### Reproduction Steps

Steps to reproduce this issue
1. Apply an SCP which requires Stack tag to be present for EC2 instances
2. Use the following template and run `packer build`:

### Packer version

`v1.9.4`

### Simplified Packer Template

```
packer {
  required_plugins {
    amazon = {
      version = ">= 0.0.2"
      source  = "github.com/hashicorp/amazon"
    }
  }
}

source "amazon-ebs" "ubuntu" {
  ami_name      = "core-service-ami-20.04"
  instance_type = "t2.micro"
  region        = "us-east-1"
  tags = {
    Name = "CoreServices Ubuntu AMI"
    Stack = "core-service"
  }
  source_ami_filter {
    filters = {
      name                = "ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-*"
      root-device-type    = "ebs"
      virtualization-type = "hvm"
    }
    most_recent = true
    owners      = ["099720109477"]
  }
  ssh_username = "ubuntu"
  ami_block_device_mappings {
    device_name           = "/dev/xvda"
    volume_type           = "gp3"
    volume_size           = 15
    delete_on_termination = true
  }
  decode_authorization_messages = true
}

build {
  name = "core-service"
  sources = [
    "source.amazon-ebs.ubuntu"
  ]
  provisioner "shell" {
    inline = [
      "echo Installing docker",
      "sudo apt-get update",
      "sudo apt-get install -y docker.io",
      "sudo systemctl enable docker",
      "sudo systemctl start docker"
    ]
  }
}

```

### Operating system and Environment details

OS - MacOS, Architecture - arm64

**Comment by nywilken** [comment]
Hi @karansingh-amagi thanks for providing the configuration. It sounds like the SCP requires the tags to exist on the running instance and any other resource created building process. If that's the case will need to use the `run_tags` configuration attribute, not the tags attribute. 

```hcl
  run_tags = {
    Name = "CoreServices Ubuntu AMI"
    Stack = "core-service"
  }
```

The `run_tags` configuration attribute defines tags that are assigned to all resources created by Packer during a build (e.g security group, snapshot, instance, etc). They are also inherited by the resulting AMI generated from the Packer build. Whereas, the `tags` attribute only get applied to the resulting AMI. 

Thanks again for including your template and a clear description of your issue. Give the `run_tags` attribute a try and let me know if you are still having issues.

**Comment by karansingh-amagi** [comment]
Thank you @nywilken, this worked.
