### ISSUE TITLE
Documentation link dead/not working

### ISSUE THREAD

**Issue by fractal1977** [hashicorp/packer#12659]
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Overview of the Issue
Link dead in : website/content/docs/templates/hcl_templates/functions/contextual/consul.mdx

"#[Documentation] (/consul/docs/commands#environment-variables)". 
==> not working in the doc website https://developer.hashicorp.com/packer/docs/templates/hcl_templates/functions/contextual/consul

**Comment by nywilken** [comment]
Thanks for reporting we will work on getting this fixed asap.
