### ISSUE TITLE
packer string templates not working -- doc issue?

### ISSUE THREAD

**Issue by matthewsht** [hashicorp/packer#12651]
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Overview of the Issue

String templates are not really documented and therefore hard to use.
Based on https://developer.hashicorp.com/packer/docs/templates/hcl_templates/expressions#string-templates 
I attempted to use the docs from templatefile but apply them to a heredoc string. (As implied by that linked).

It doesn't work. I apologize if this is  known issue or documented elsewhere.

Any suggestions?

#### Reproduction Steps

I have the following:
```hcl
locals {
  # These are all strings...
  history_file_data   = {
    "build_by"          = local.build_by
    "build_timestamp"   = local.build_timestamp
    "build_author"      = local.build_author
    "build_sha"         = local.build_sha
    "build_repo_clean"  = local.build_repo_clean
    "runtime_username"  = var.runtime_username
    "build_username"    = var.build_username
    "vm_name"           = local.vm_name
  }
  build_description   = <<-EOF
  %{ for history_key, history_value in ${local.history_file_data} ~}
    ${history_key}="${history_value}"
  %{ endfor ~}
  EOF
}
```

A packer validate run yields:
``` shell
> packer validate builds/vsphere-iso/rhel/8
Error: Invalid character

  on builds/vsphere-iso/rhel/8/main.pkr.hcl line 68, in locals:
  68:   %{ for history_key, history_value in ${local.history_file_data} }

This character is not used within the language.

Error: Invalid expression

  on builds/vsphere-iso/rhel/8/main.pkr.hcl line 68, in locals:
  68:   %{ for history_key, history_value in ${local.history_file_data} }

Expected the start of an expression, but found an invalid expression token.
```

### Packer version

```shell
> packer version
Packer v1.9.4
```

**Comment by nywilken** [comment]
Hi @matthewsht thanks for sharing your example. No examples make it difficult for sure. I will label this as a bug for the docs. We can benefit from having an example or two. If you are interested in contributing to the docs please feel free to open a PR. 

That said, It looks like you are escaping the local.history_file_date local variable within the template sequence, using `${...}` which is not needed. If you write your snippet to look like the following it should work as expected. 

```
locals {
  # These are all strings...
  history_file_data   = {
    "build_by"          = local.build_by
    "build_timestamp"   = local.build_timestamp
    "build_author"      = local.build_author
    "build_sha"         = local.build_sha
    "build_repo_clean"  = local.build_repo_clean
    "runtime_username"  = var.runtime_username
    "build_username"    = var.build_username
    "vm_name"           = local.vm_name
  }
  build_description   = <<-EOF
  %{ for history_key, history_value in local.history_file_data ~}
    ${history_key}="${history_value}"
  %{ endfor ~}
  EOF
}
```
Example run with bogus data
```
~>  packer console source.pkr.hcl
> local.build_description
>     build_author="foobar"
    build_by="foobar"
    build_repo_clean="foobar"
    build_sha="ftobar"
    build_timestamp="foobar"
    build_username="foobar"
    runtime_username="ftobar"
    vm_name="ftobar"
```
