### ISSUE TITLE
Provisionner "windows-restart" doesn't work

### ISSUE THREAD

**Issue by Hassan1er** [hashicorp/packer#12663]
Hello,

I'm using Packer throught Azure Pipelines to create Windows Server 2022 image. The VM is created with Hyper-V.
Here is my problem : After launching my hardening script on the VM, i try to use the provisionner "windows-restart", but it doesn't work.
The VM is not restarting, and the Azure Pipeline fails after the 10 minutes timeout. At the same time, i'm looking at the VM on Hyper-V to see what is going on, but nothing happens. The VM doesn't even shutdown to start again, it just stays on the desktop and nothing happens. I already tried to restart the machine manually, but the Azure Pipeline doesn't detect it, and still fails after 10 minutes. I tried to increase the restart timeout to 30m, but nothing changes. I tried to put a pause_before with 2m, but nothing changes. I also tried to restart the machine with a Powershell script, but the same thing happens, the VM doesn't restart and the pipeline fails. I don't know what to do more. 

Thanks a lot for your help!

Here is the part of my script : 
![2023-10-24_11h28_59](https://github.com/hashicorp/packer/assets/148787466/25a2a106-4ea3-48a8-b39a-c2ae7a3fad0f)

Here is the pipeline fail. My hardening script is launched at line 296. The provisionner "windows-restart" is launched at line 307. Between the lines 307 and 308, there is a wait of 10m corresping to the restart_timeout.
![2023-10-24_11h33_50](https://github.com/hashicorp/packer/assets/148787466/54ed1f2b-6673-461d-be80-4419835efcfb)

**Comment by nywilken** [comment]
Hi @Hassan1er thanks for reaching out. The error message at the end of your log `401 - invalid content type` is an indicator that Packer is unable to communicate with WinRM, which is needed for running the provisioner. Which may be the reason why `windows-reboot` is not executing. If you can enable debug logs `PACKER_LOG=1` in the pipeline you may be able to see more error information. 

Does your hardening script disable WinRM or prevent remote logins? 

Hardening scripts tend to disable all Packer communication to the instance so we recommend running hardening scripts as the last provisioner with the reboot being part of the hardening step if the reboot. The Powershell command doesn't have an `expect_disconnect` attribute to inform Packer that it will reboot. But you can add the `[pause_after](https://developer.hashicorp.com/packer/docs/provisioners/powershell#pause_after)` to the provisioner to have Packer wait a number of minutes for the machine to reboot after running the hardening scripts. 

I don't suspect this is a bug so I will label it as so. But I will keep the issue open for your comments and discussion.

**Comment by Hassan1er** [comment]
Hi @nywilken thanks for your answer. My hardening script doesn't disable WinRM or prevent remote logins. I'm alreay using it for 2016 and 2019 images, and it works perfectly. The problem only appears with 2022. The Packer Log doesn't give me utile informations about the error.

**Comment by Hassan1er** [comment]
After investigations, i found the issue with my problem. The hardening was effictively blocking WinRM. After changes, the pipeline was able to continue the process and the image is being created succesfully. Thanks.
