### ISSUE TITLE
docs: Expressions page does not contain Function Calls section

### ISSUE THREAD

**Issue by mloskot** [hashicorp/packer#12670]
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

This "For mode details" direction on [Functions](https://developer.hashicorp.com/packer/docs/templates/hcl_templates/functions) page leads to non-existent content:

![image](https://github.com/hashicorp/packer/assets/80741/b12a6303-f4f4-4b96-8e57-c6fca6b4b5d6)

#### Reproduction Steps

1. Go to https://developer.hashicorp.com/packer/docs/templates/hcl_templates/functions
2. Scroll to
    > For more details on syntax, see [Function Calls](https://developer.hashicorp.com/packer/docs/templates/hcl_templates/expressions#function-calls) on the Expressions page.
3. Follow the "Function Calls" link
4. Observe:
    - it jumps to the top of the [Expressions](https://developer.hashicorp.com/packer/docs/templates/hcl_templates/expressions) chapter
    - searching that page for `function call` or `function calls` yields nothing

### Packer version

v1.9.x (latest)

### Simplified Packer Template

N/A

### Operating system and Environment details

N/A

### Log Fragments and crash.log files

N/A

**Comment by lbajolet-hashicorp** [comment]
Thanks for reporting this @mloskot!

I'll open a PR to fix this ASAP.
