### ISSUE TITLE
Add community maintained Unikraft Packer plugin

### ISSUE THREAD

**Issue by craciunoiuc** [hashicorp/packer#12759]
#### Description

The Unikraft Packer plugin brings the KraftKit companion tool into the Packer universe.
With this plugin, people can build Unikraft unikernels using the builder and the resulting images can be packaged and pushed as OCI archives using the post-processor.

The plugin can be found here: <https://github.com/unikraft/packer-plugin-unikraft>

#### Integration Tier

The integration will be a community integration.

#### Checklist
- [x] Has valid [`metadata.hcl`](https://github.com/hashicorp/integration-template) file in plugin repository.
- [x] Has added integration scripts [packer-plugin-scaffolding](https://github.com/hashicorp/packer-plugin-scoffolding) to plugin repository.
- [x] Has added top-level integration README.md file to plugin `docs` directory.
- [x] All plugins components have one README.md describing their usage.
- [x] Has a fully synced `.web-docs` directory ready for publishing to the integrations portal.

This issue is opened with the new guidelines. The original PR on this can be found here: <https://github.com/hashicorp/packer/pull/12656>.
There is also a demo in there, will not reupload to not waste space.

List was generated with: https://developer.hashicorp.com/packer/docs/plugins/creation#registering-plugins

Let me know if something is missing or is out of order.

cc: @nywilken

GitHub-Closes: #12656

**Comment by nywilken** [comment]
Hi @craciunoiuc thanks for working through the integration process to get the Unikraft plugin updated. I've opened a PR internally to enable the integration once enabled you will be able to trigger a manual [release notification job](https://github.com/unikraft/packer-plugin-unikraft/actions/workflows/notify-integration-release-via-manual.yaml) for version `0.2.0` to trigger a plugin ingestion from your integration portal. I'll circle back once the integration has been enabled.

**Comment by nywilken** [comment]
Hi @craciunoiuc the integration has been enabled on our side. Could you run the [ notification job ](https://github.com/unikraft/packer-plugin-unikraft/actions/workflows/notify-integration-release-via-manual.yaml) to test the integration ingestion please.

**Comment by craciunoiuc** [comment]
Hey

Just ran it and it seems to have passed

https://github.com/unikraft/packer-plugin-unikraft/actions/runs/7221912933/job/19677875717
