### ISSUE TITLE
Add bketelsen/packer-plugin-incus

### ISSUE THREAD

**Issue by bketelsen** [hashicorp/packer#12766]
#### Description

A packer builder for Incus, based on the LXD builder.
[bketelsen/packer-plugin-incus](https://github.com/bketelsen/packer-plugin-incus)

#### Integration Tier
community

#### Checklist
- [x] Has valid [`metadata.hcl`](https://github.com/hashicorp/integration-template) file in plugin repository.
- [x] Has added integration scripts [packer-plugin-scaffolding](https://github.com/hashicorp/packer-plugin-scoffolding) to plugin repository.
- [x] Has added top-level integration README.md file to plugin `docs` directory.
- [x] All plugins components have one README.md describing their usage.
- [x] Has a fully synced `.web-docs` directory ready for publishing to the integrations portal.

**Comment by nywilken** [comment]
Hi @bketelsen thanks for opening up this request to register the Incus plugin as an integration. I'll work on opening up an internal PR to get the plugin registered and take a minute to review the integration configuration for your plugins. Please allow me a couple of days to get this all squared away.

**Comment by nywilken** [comment]
Hi @bketelsen the upstream PR to enable the integration has been merged. Please feel free to trigger a manual notify release job to trigger the publishing for the Incus plugin. 

I'll keep this issue open until we've confirmed the Incus integration is live.

**Comment by nywilken** [comment]
@bketelsen I confirmed the integration is live at https://developer.hashicorp.com/packer/integrations?filter=Incus

You can trigger updates automatically when tagging new versions of the plugin at release or manually using the manual notification job. Thank you for registering and supporting the Packer ecosystem. Feel free to reach out if you have any questions or concerns.
