### ISSUE TITLE
KubeArmor plugin integration

### ISSUE THREAD

**Issue by Prateeknandle** [hashicorp/packer#12833]
#### Description

A plugin for KubeArmor that provides [KubeArmor Hardening Host Security policies](https://docs.kubearmor.io/kubearmor/use-cases/hardening_guide) for the build workloads.

The KubeArmor provisioner will configure the build and provide the [KubeArmor Hardening Host Security Policies](https://docs.kubearmor.io/kubearmor/use-cases/hardening_guide). These hardening policies will be in the context of your workload so you can see how they will be applied and what impact they will have on your system. This allows you to make informed decisions about which policies to apply and helps you understand the trade-offs between security and functionality.

plugin - https://github.com/kubearmor/packer-plugin-kubearmor

#### Checklist
- [x] Has valid [`metadata.hcl`](https://github.com/hashicorp/integration-template) file in plugin repository.
- [ ] Has added integration scripts [packer-plugin-scaffolding](https://github.com/hashicorp/packer-plugin-scoffolding) to plugin repository.
- [x] Has added top-level integration README.md file to plugin `docs` directory.
- [x] All plugins components have one README.md describing their usage.
- [x] Has a fully synced `.web-docs` directory ready for publishing to the integrations portal.

**Comment by Prateeknandle** [comment]
Hey folks, which part will be added as documentation on the portal? Is the one present in `.web/docs` folder inside `components` dir?

**Comment by nywilken** [comment]
Hi @Prateeknandle I reviewed the initial configuration and found a few things that needed to be updated to match the KubeArmor repo. I opened a PR to help push this request forward https://github.com/kubearmor/packer-plugin-kubearmor/pull/8

>  Is the one present in .web/docs folder inside components dir?

All the docs are read from the .web-docs directory at this time. However, if you find that you would like to move the docs into a different directory you can do so. We would just need to know where to read the docs from in order for the integration to consume the correct information.

**Comment by Prateeknandle** [comment]
is there something required from our side let me know, thanks folks.

**Comment by nywilken** [comment]
> is there something required from our side let me know, thanks folks.

Hi there I opened a PR to fix an issue with the identifier in the KubeArmor repo.  


Also I don't see the actions for triggering a Packer integration release notification job. If you could merge in these [actions](https://github.com/hashicorp/packer-plugin-scaffolding/blob/main/.github/workflows/notify-integration-release-via-manual.yaml) after merging in these changes you can trigger a notification release job to ingest the plugin documentation into the Packer integration portal.

**Comment by nyrahul** [comment]
@Prateeknandle , any updates on this? Would be great to have this merged. Thanks

**Comment by Prateeknandle** [comment]
Yup, this was merged, and the documentation has also been generated, but there is an issue with the structure of the documentation. I will fix it.

**Comment by nywilken** [comment]
Closing as the integration is now complete https://developer.hashicorp.com/packer/integrations/kubearmor/kubearmor

Thank you @Prateeknandle
