### ISSUE TITLE
Digital Ocean plugin page is unavailable

### ISSUE THREAD

**Issue by igorbach** [hashicorp/packer#12837]
URL tried
https://developer.hashicorp.com/packer/plugins/builders/digitalocean

![image](https://github.com/hashicorp/packer/assets/69148926/cd25b5fa-8b8a-4081-8279-710ee331da0b)

Please, fix

**Comment by lbajolet-hashicorp** [comment]
Hi @igorbach,

The plugin's docs were removed from the documentation earlier this year when we migrated everything over to our new integrations system, apologies for that.

We've been in contact with the Digitalocean team that maintains the plugin, this is now fixed, and the docs are now available through the [integrations](https://developer.hashicorp.com/packer/integrations/digitalocean/digitalocean).

I'll close this issue for now, but please feel free to reopen if I missed something.

Thanks
