### ISSUE TITLE
[Azure] How to support AD Login when creating an image?

### ISSUE THREAD

**Issue by musabmirza-amperon** [hashicorp/packer#12844]
I am trying to create an image with azure-arm which is based off:

```
  image_publisher = "center-for-internet-security-inc"
  image_offer     = "cis-ubuntu"
  image_sku       = "cis-ubuntulinux2004-stig-gen1"
```

I want to enable AD Login for any machines being created through this image.

However when I try to create the VM, in the management tab, it says that "Ad login is not supported".

This is the case if I base it off even on official ubuntu image. 

Please advice.

**Comment by Poltergeisen** [comment]
There does appear to be a need for documentation surrounding this.

**Comment by ageisen2000** [comment]
Please don't close this, there should be some documentation on it somewhere

**Comment by Poltergeisen** [comment]
Please don't close this issue. There should be some documentation for this at a minimum.

**Comment by ageisen2000** [comment]
Still waiting for a response and documentation

**Comment by ageisen2000** [comment]
Still needs addressed

**Comment by Poltergeisen** [comment]
This is the last time I'm probably gonna bump this issue. I wish there was some response from the devs in some capacity.
