### ISSUE TITLE
 ansible-galaxy: command not found

### ISSUE THREAD

**Issue by bathri06** [hashicorp/packer#12851]
Unable to build a AMI for Amazon 2023 . error occurred after upgrading the packer version 

Error:  ansible-galaxy: command not found

**Comment by tenthirtyam** [comment]
Review the release notes for [v1.10.0](https://github.com/hashicorp/packer/releases/tag/v1.10.0) regarding breaking changes for plugins previously bundled into Packer, of which `packer-plugin-ansible` was one. You should add it to the `packer { }` block.

```hcl
packer {
  required_version = ">= 1.10.0"
  required_plugins {
    amazon = {
      source  = "github.com/hashicorp/amazon"
      version = ">= 1.3.0"
    }
    ansible = {
      source  = "github.com/hashicorp/ansible"
      version = ">= 1.1.0"
    }
  }
}
```
