### ISSUE TITLE
Add IPSW plugin 

### ISSUE THREAD

**Issue by torarnv** [hashicorp/packer#12873]
#### Description

The IPSW data-source plugin can be used with HashiCorp [Packer](https://www.packer.io/) to fetch information about [Apple device firmware](https://en.wikipedia.org/wiki/IPSW), for example for building macOS images with [Tart](https://github.com/cirruslabs/packer-plugin-tart).

https://github.com/torarnv/packer-plugin-ipsw

#### Checklist
- [x] Has valid [`metadata.hcl`](https://github.com/hashicorp/integration-template) file in plugin repository.
- [x] Has added integration scripts [packer-plugin-scaffolding](https://github.com/hashicorp/packer-plugin-scoffolding) to plugin repository.
- [x] Has added top-level integration README.md file to plugin `docs` directory.
- [x] All plugins components have one README.md describing their usage.
- [x] Has a fully synced `.web-docs` directory ready for publishing to the integrations portal.

**Comment by torarnv** [comment]
The integration has been submitted in the past, and is listed here: https://developer.hashicorp.com/packer/integrations?components=data-source&filter=ipsw

But the docs link is broken, likely due to the new way that the docs are published.

**Comment by torarnv** [comment]
https://github.com/torarnv/packer-plugin-ipsw/actions/runs/8204818234/job/22440273928

Shows `Error: [validate-hcl] Error: Organization not found for integration identifier: 'packer/torarnv/ipsw'`

I assume that's because the plugin hasn't been added to the docs yet?

**Comment by torarnv** [comment]
I believe you helped me with this in the past @lbajolet-hashicorp

See https://github.com/hashicorp/packer/pull/12541

**Comment by lbajolet-hashicorp** [comment]
Hi @torarnv,

It seems we have forgotten to include you in our round for integrations, apologies about that!

Good to see you've updated the docs structure, with the current docs I believe we'll be able to add them to the internal integrations (or update what exists at least), I'll see to this right now.

Thanks for signalling this to us!

**Comment by torarnv** [comment]
Thanks @lbajolet-hashicorp <3

**Comment by lbajolet-hashicorp** [comment]
Hi @torarnv,

You can try to run the integration action once again, on our side we did the updates to the documentation, this should work now

**Comment by torarnv** [comment]
Thanks @lbajolet-hashicorp, the integration now worked. Do I need to do anything else? I see https://developer.hashicorp.com/packer/plugins/datasources/ipsw is still 404, but perhaps it takes a while to go live? 

Does the integration automatically publish the new docs, or does it trigger a PR or something similar on your side?

**Comment by lbajolet-hashicorp** [comment]
Hi again! I can confirm your plugin is available, not on plugins anymore though (https://developer.hashicorp.com/packer/integrations/torarnv/ipsw), I'm surprised the link doesn't work anymore, there should be some redirect in place to avoid this problem, that's a discussion I need to have internally.
Also it seems that the documentation is not complete on the new system, I'm not sure why, I'll need to troubleshoot this. I'll make this a priority for Monday.

**Comment by torarnv** [comment]
Thanks @lbajolet-hashicorp , no rush! 😄  Have a good weekend!

**Comment by torarnv** [comment]
I'm looking at perhaps renaming this plugin to `packer-plugin-appledb`, as there are other releases one can fetch from https://appledb.dev/ than just IPSWs. For example Xcode releases. Github will apparently do redirects for git urls, so I assume this would work fine for someone with this in their packer config?

```
ipsw = {
       version = ">= 0.0.8"
       source = "github.com/torarnv/ipsw"
}
``

If that works fine, then let's hold on publishing the docs for this plugin until I've renamed it :)

**Comment by lbajolet-hashicorp** [comment]
Hi @torarnv,

No objection to you renaming the project, I'd think Github does redirect so there's a good chance users may be able to download it this way, that being said, I'm not completely certain the installation/loading logic will work if the source has one name, and the binary another (i.e. in this case the plugin source would be `github.com/torarnv/ipsw` and the plugin would be `packer-plugin-appledb`).

If you plan on using `appledb` for future versions of the plugin, I would encourage you instead to fork your `ipsw` plugin as `appledb`, update the `ipsw` plugin to state that it's deprecated/will not be maintained, and point to `appledb` as replacement.
This advisory message can be part of the docs and the plugin itself (though I'm not certain datasources can print messages to users, if it's in the verbose logs, chances are it won't be super visible).

In any case, the fact that the main docs and the datasources aren't visible most likely point to a problem with our configuration, so I'll take a look this way, and let you know if there's something to change in your repo, this fix will likely be applicable to both plugins.

**Comment by torarnv** [comment]
Ah, awesome, thank you so much @lbajolet-hashicorp !

**Comment by torarnv** [comment]
Looks like the docs are now live at https://developer.hashicorp.com/packer/integrations/torarnv/ipsw

Thanks again @lbajolet-hashicorp ❤️ 

As for the invalid flag, I initially followed this guide:

https://developer.hashicorp.com/packer/docs/plugins/creation#example-add-integration-files-to-existing-plugin-repository

Which has the same problematic line in https://github.com/hashicorp/packer-plugin-scaffolding/blob/main/.web-docs/metadata.hcl#L11, so perhaps that needs to be updated?

**Comment by lbajolet-hashicorp** [comment]
Very true, the scaffolding HCL file is indeed wrong, thanks for the notice! I'll fix that immediately.

**Comment by lbajolet-hashicorp** [comment]
Oh also FYI the old URIs should work too in addition to the new one, I fixed the redirections for your plugin, so now the old links will redirect you to the new docs

**Comment by torarnv** [comment]
Awesome!! I think we can close this one then, thanks for all your help, it makes working with Packer a joy <3
