### ISSUE TITLE
`light` tag has alpha version, instead of latest stable as per docs.

### ISSUE THREAD

**Issue by Laikulo** [hashicorp/packer#12899]
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

The `light` tag on docker hub contains 1.11.0-alpha, and not the latest stable (1.10.2) as stated in the docs.

#### Reproduction Steps

```
docker pull docker.io/hashicorp/packer:light
docker run --rm docker.io/hashicorp/packer:light version
```

### Packer version

`Packer v1.11.0-alpha`

### Operating system and Environment details
EL8/9 - x64

**Comment by lbajolet-hashicorp** [comment]
Hi @Laikulo,

Thanks for reporting this.

This is because we released alpha versions of Packer recently, but clearly these should not be marked as "latest" on Docker Hub.

We'll look into this and get it resolved ASAP.

Thanks again!
