### ISSUE TITLE
packer lxc failing to create container 

### ISSUE THREAD

**Issue by Dialgatrainer02** [hashicorp/packer#12907]
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

when i run packer build . i get errors saying it couldnt create the vm

and im unsure why i can create containers using 
sudo lxc-create -t download -n packer-test -- -d alpine  -a amd64

#### Reproduction Steps

install lxc
git clone https://github.com/jpancoast/image-builder.git
cd ./image-builder/lxc/examples/alpine
sudo packer init .
sudo chmod +x build.sh
sudo bash build.sh
### Packer version

From `packer version`
```
Packer v1.10.2-dev

Your version of Packer is out of date! The latest version
is 1.10.2. You can update by downloading from www.packer.io/downloads
```
### Simplified Packer Template

If the file is longer than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/) of the log or use the [Github detailed
format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d)
instead of posting it directly in the issue.
git clone https://github.com/jpancoast/image-builder.git this is my first time using packer so just coping a git repo

### Operating system and Environment details

OS, Architecture, and any other information you can provide about the
environment.

arch linux (just for testing)
x86_64
packer and lxc on latest versions
### Log Fragments and crash.log files

Include appropriate log fragments. If the log is longer than a few dozen lines,
please include the URL to the [gist](https://gist.github.com/) of the log or
use the [Github detailed format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d) instead of posting it directly in the issue.
https://gist.github.com/Dialgatrainer02/c28b16d8a7ab72424323b91e3294d38e

Set the env var `PACKER_LOG=1` for maximum log detail.

**Comment by Dialgatrainer02** [comment]
my /etc/lxc/default.conf if 
```
lxc.net.0.type = veth
lxc.net.0.link = lxcbr0
lxc.net.0.flags = up
lxc.net.0.hwaddr = 00:16:3e:xx:xx:xx
```
i am trying to make an alpine image and i can successfully make it using the command: sudo lxc-create -t download -n packer-lxc -- -d alpine  -a amd64 
and selecting 3.19

**Comment by lbajolet-hashicorp** [comment]
Regarding your bridge interface not existing, there's an issue on LXC that hints at the potential problem, I suggest taking a look at the (former) maintainer's suggestion: https://github.com/lxc/lxc/issues/1218#issuecomment-600889827

**Comment by lbajolet-hashicorp** [comment]
On another note, since this is a LXC-specific bug, I'm transferring the issue to the plugin for further discussion.

**Comment by Dialgatrainer02** [comment]
okay thanks for the help
