### ISSUE TITLE
Plugin Integration Request: external

### ISSUE THREAD

**Issue by jilyaluk** [hashicorp/packer#12991]
#### Description

A plugin that provides access to external commands.

Was previously on documentation site, but was removed after migration to new docs. I merged joomcode/packer-plugin-external#9, thanks for contributing it to plugin directly! Also, fixed build and released 0.0.3 with updated packer-plugin-sdk and other deps.

https://github.com/joomcode/packer-plugin-external

#### Integration Tier
Community integration

#### Checklist
- [x] Has valid [`metadata.hcl`](https://github.com/hashicorp/integration-template) file in plugin repository.
- [x] Has added integration scripts [packer-plugin-scaffolding](https://github.com/hashicorp/packer-plugin-scoffolding) to plugin repository.
- [x] Has added top-level integration README.md file to plugin `docs` directory.
- [x] All plugins components have one README.md describing their usage.
- [x] Has a fully synced `.web-docs` directory ready for publishing to the integrations portal.

**Comment by jilyaluk** [comment]
Hey @nywilken, thanks again for fixing docs in our repo. I merged it, should be fine now.

**Comment by lbajolet-hashicorp** [comment]
Hey @jilyaluk,

Thanks for opening this, I've opened a PR on our internal repo that manages deployments of such plugin documentations, once merged this should appear on our website, after you've triggered the action to signal that a release is ready.

I'll let you know when this is possible (you'll receive errors in the meantime if you try to run the action).

Thanks for the update, and I'll be back :)

**Comment by lbajolet-hashicorp** [comment]
Hi @jilyaluk,

The integration has been merged on our side, you should be able to trigger a manual publish with the action now.

There might be a delay before this gets deployed so don't despair if it fails for the next hour or so.

If by tomorrow you are experiencing issues with that, please update this thread and I'll take a look.

Thanks!

**Comment by jilyaluk** [comment]
Hi @lbajolet-hashicorp,

Triggering workflow worked. I now see the docs on the website, thanks!
