### ISSUE TITLE
Anka

### ISSUE THREAD

**Issue by NorseGaud** [hashicorp/packer#12990]
#### Description

We provide builders and a provisioner for our customers to create Anka VM templates/tags with packer.

https://github.com/veertuinc/packer-plugin-veertu-anka

#### Integration Tier

community

#### Checklist
- [x] Has valid [`metadata.hcl`](https://github.com/hashicorp/integration-template) file in plugin repository.
- [x] Has added integration scripts [packer-plugin-scaffolding](https://github.com/hashicorp/packer-plugin-scoffolding) to plugin repository.
- [x] Has added top-level integration README.md file to plugin `docs` directory.
- [x] All plugins components have one README.md describing their usage.
- [x] Has a fully synced `.web-docs` directory ready for publishing to the integrations portal.

**Comment by NorseGaud** [comment]
I think I've configured everything ok... I see https://github.com/veertuinc/packer-plugin-veertu-anka/actions/runs/9178024022/job/25236959855

```Error: [validate-hcl] Error: Integration not found for integration identifier: 'packer/veertuinc/anka'```

**Comment by lbajolet-hashicorp** [comment]
Hi @NorseGaud,

Thanks for bringing this up! Looking at the `.web-docs` directory on the plugin, it looks like the `metadata.hcl` file is not present?
We won't be able to add the integration if it's not in the expected location, could you add it to your plugin?

If you need an example of a working `metadata.hcl` file, please take a look at the one from the [Amazon](https://github.com/hashicorp/packer-plugin-amazon/blob/main/.web-docs/metadata.hcl) plugin for example, and let me know when it's ready to go, I'll take another look at the plugin code then.

Thanks!

**Comment by NorseGaud** [comment]
> Hi @NorseGaud,
> 
> 
> 
> Thanks for bringing this up! Looking at the `.web-docs` directory on the plugin, it looks like the `metadata.hcl` file is not present?
> 
> We won't be able to add the integration if it's not in the expected location, could you add it to your plugin?
> 
> 
> 
> If you need an example of a working `metadata.hcl` file, please take a look at the one from the [Amazon](https://github.com/hashicorp/packer-plugin-amazon/blob/main/.web-docs/metadata.hcl) plugin for example, and let me know when it's ready to go, I'll take another look at the plugin code then.
> 
> 
> 
> Thanks!

Hey @lbajolet-hashicorp your guide says I can put it under the docs folder too. Is that wrong?

**Comment by lbajolet-hashicorp** [comment]
Oh? I was under the impression that this had to be under `.web-docs` as this is what the integrations look for, so either I'm missing something or the docs are inaccurate.

I'll dig into it and ask questions around, today's Memorial Day in the US so most of the org is out of office, but hopefully this should resolve itself soon!

**Comment by NorseGaud** [comment]
I can move it back tomorrow too. No problemo. I just remember it saying somewhere that I had to put it under either directory and docs makes more sense to me.

**Comment by lbajolet-hashicorp** [comment]
If it makes more sense to you, and it doesn't conflict with how we are processing the docs, by all means don't feel obligated to move them now, I was under the impression that the `.web-docs` directory (or whatever the name, it's just where the scripts export the processed docs by default) was the source of truth and everything had to be under it, but maybe there's something we can do to point to the other place.
I'll come back to this thread once I have more information

**Comment by NorseGaud** [comment]
<img width="844" alt="Screenshot 2024-05-27 at 3 06 57 PM" src="https://github.com/hashicorp/packer/assets/5896030/7f8a3ad1-b80c-4268-8501-b10aca733e1d">

**Comment by lbajolet-hashicorp** [comment]
Thanks for the update! I believe this is a phrasing problem then, strictly speaking we don't enforce the name of the output directory as `.web-docs`, but this is what we default to (it is something we register for a plugin on our internal repository so the service that processes ingestion requests knows where to look).
If you wanted to amend the scripts used to generate those docs, you can change the output to any named directory, and start versioning it.

So in your case, the docs directory is `.web-docs`, and this is where we expect the `metadata.hcl` file to be located, as `docs` is a staging area for docs (at least with the hierarchy we propose in the scaffolding project): this is where the bulk of the contents are written, and where you can import partials in order to weave output markdown files that are then placed into `.web-docs` under the expected hierarchy/name scheme.

I've asked for a confirmation regarding the `metadata.hcl` file just to be sure, but I think this is more of a miscommunication on our part than anything else.

I'll try to follow-up as soon as possible regarding this.

**Comment by lbajolet-hashicorp** [comment]
Hey again @NorseGaud,

I just had confirmation this is a phrasing blunder on our part, I'll try to open a PR to clarify this tomorrow.

With the setup you have, you will need to place the `metadata.hcl` under `.web-docs/metadata.hcl`, then we can proceed with the integration PR on our side, then we can sync with you so a release is published once it's in, and the docs for your plugin should appear soon after this.

Thanks in advance!

**Comment by lbajolet-hashicorp** [comment]
Hi @NorseGaud,

You should be able to trigger a publish right now I believe, the PR I opened on the internal integrations has been merged, so at this point you should be all set. There might be a delay in the deployments so if it fails for the next couple of hours don't panic, but please do update this issue if you don't see a job succeeding or if the integrations don't show your plugin by tomorrow.

Thanks!

**Comment by NorseGaud** [comment]
Hey @lbajolet-hashicorp , I've been trying to run it and it's throwing

```
[validate-hcl]: Running
Error: [validate-hcl] Error: Integration not found for integration identifier: 'packer/veertuinc/veertu-anka'
```

https://github.com/veertuinc/packer-plugin-veertu-anka/actions/runs/9303310228/job/25605330207

Am I doing something wrong, or did I misconfigure it?

**Comment by lbajolet-hashicorp** [comment]
Hey @NorseGaud,

Probably something I did wrong, sorry about that! I'll take a look ASAP on our side and keep you posted

**Comment by lbajolet-hashicorp** [comment]
Hi again @NorseGaud,

We've just merged a change on our side, hopefully this should fix your issue!

As I mentioned earlier, this could take a moment before deployments are processed, but I would think you will be able to trigger a publish soon.

Please let me know how that goes!

**Comment by NorseGaud** [comment]
Thanks @lbajolet-hashicorp !! I think it worked now. I'll keep checking the integrations page. Can you confirm if it worked from your end?

**Comment by NorseGaud** [comment]
It's there! Wohooo! Thanks for the help!
