### ISSUE TITLE
Salt Provisioner

### ISSUE THREAD

**Issue by mpoore** [hashicorp/packer#13062]
#### Description

The Salt Packer provisioner executes Salt's "masterless" or "local" mode on the guest operating system of the image that Packer is building.
Salt state files that exist on the guest operating system are used to customize the image to meet a defined desired state. This means the Salt Minion package must be installed on the guest operating system. State files can be uploaded from your local build machine (the one running Packer) by this plugin.
https://github.com/mpoore/packer-plugin-salt

#### Integration Tier
Community

#### Checklist
- [ Y ] Has valid [`metadata.hcl`](https://github.com/hashicorp/integration-template) file in plugin repository.
- [ Y ] Has added integration scripts [packer-plugin-scaffolding](https://github.com/hashicorp/packer-plugin-scoffolding) to plugin repository.
- [ Y ] Has added top-level integration README.md file to plugin `docs` directory.
- [ Y ] All plugins components have one README.md describing their usage.
- [ Y ] Has a fully synced `.web-docs` directory ready for publishing to the integrations portal.

**Comment by nywilken** [comment]
Hi @mpoore thanks for opening up this integration requisition. We've had folks interested in an updated Salt Provider. I am glad to see you take over the plugin, thank you.

I took a Quick Look at the documentation for your integration. The main README [L33](https://github.com/mpoore/packer-plugin-salt/blob/2098dc4335f06ec8ff3b5bc00ac5d647a94f75a0/.web-docs/README.md?plain=1#L33) needs a link to the provisioner page. Specifically


```
- [salt](https://developer.hashicorp.com/packer/integrations/mpoore/salt/latest/components/provisioner/salt) - The Packer provisioner will transfer Salt state files to the target guest operating system and execute `Salt` to apply the configured desired state.
```

I also didn't see the action for notifying the upstream Packer documentation API with updates. If you've copied them and I just can see them that's okay. But if you haven't already I suggest you add the notify-integration-* workflows from [here](https://github.com/hashicorp/packer-plugin-scaffolding/tree/main/.github/workflows) to your project repository. 

I've opened a PR internally to register your plugin, once that is merged I will circle back and let you know it is okay to run the manual notification job to ingest the first round of plugin docs.

**Comment by mpoore** [comment]
Hi @nywilken,

Thank you for reviewing this. I've updated the link in the documentation and also added the two workflows required. Let me know if there's anything else that needs attention.

Thank you again!

**Comment by nywilken** [comment]
Thanks for the quick action @mpoore. The upstream PR to enable the integration has been merged. Can  you please trigger a [manual notification workflow](https://github.com/mpoore/packer-plugin-salt/actions/workflows/notify-integration-release-via-manual.yaml) for your plugin using `0.1.2` as the version and `main` as the branch. 

If the job will notify our API to ingest the plugin docs. It will take about 15 minutes to rebuild and clear the cache but if there are no errors reported all should appear as expected. I'll keep this issue open until we've confirmed the plugin is listed as an integration.

**Comment by mpoore** [comment]
Thank you, @nywilken. That completed successfully. I'll check back in a little while :-)

**Comment by nywilken** [comment]
Thanks for pushing this integration forward. Closing this issue as the Salt provisioner integration is now live at https://developer.hashicorp.com/packer/integrations/mpoore/salt
