### ISSUE TITLE
--on-error=ask retry should only run the provisioner that errored when using -debug

### ISSUE THREAD

**Issue by MrMMorris** [hashicorp/packer#13128]
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Description

`--on-error=ask` retry should only run the provisioner that errored when also specifying `-debug`. Currently it reruns all the provisioners in that build unless `-debug` isn't specified, then it only runs the one that failed.

Let me know if this is intended behavior and I will close.

**Comment by lbajolet-hashicorp** [comment]
Hi @MrMMorris,

I'm not sure I understand the `reruns all the provisioners` when combining both arguments; `--debug` will stop before executing every provisioner/step, letting you debug the state of a system in between two steps, while `--on-error` lets you decide which action to undertake in case of an error during the build, and `rerun` is not one of the supported actions AFAIK.
Would you be able to provide a template/log example to understand what issue you're running into?

Thanks!

**Comment by MrMMorris** [comment]
sorry I can't seem to reproduce this right now and I don't think it's a hige issue either way so I will close
