### ISSUE TITLE
EoL attribute is set to empty string

### ISSUE THREAD

**Issue by srinadhbh** [hashicorp/packer#13134]
Hello All

I have a requirement to set the "End of life date" to T+90 days. I have tried using the below options but I dont see any value set during the image version creation.

![image](https://github.com/user-attachments/assets/c67526c9-f542-4f96-bc3e-0e7ff2e4e30e)

**In line expression:**

`PACKER_LOG=1 packer build -var "azure_client_id=***" -var "azure_client_secret=***" -var "azure_subscription_id=***" -var "git_token=" -var "gallery_name=goldenimage_gallery" -var "resource_group=****" -var "subscription=***" -var "image_name=az-img-rhel8-gen1" -var "vm_size=Standard_D2_v4" -var "image_version=1.0.0" -var "virtual_network_name=HUB-USEast" -var "virtual_network_resource_group_name=RG-NetworkHUB-EastUS" -var "virtual_network_subnet_name=Internal-App" -var "image_sku=8-LVM" -var shared_gallery_image_version_end_of_life_date=$(date -d "+3 months" --utc +"%Y-%m-%dT%H:%M:%SZ") ./RHEL8/RHEL8.json`

**Using a variable:**

```
#!/bin/bash

expiry_date=$(date -d “+3 months” --utc +“%Y-%m-%dT%H:%M:%SZ”)

echo “Expiry Date: $expiry_date”

PACKER_LOG=1 packer build -var “azure_client_id=" -var "azure_client_secret=” -var “azure_subscription_id=" -var “git_token=” -var “gallery_name=goldenimage_gallery” -var "resource_group=********" -var "subscription=” -var “image_name=az-img-rhel8-gen1” -var “vm_size=Standard_D2_v4” -var “image_version=1.0.0” -var “virtual_network_name=HUB-USEast” -var “virtual_network_resource_group_name=RG-EastUS” -var “virtual_network_subnet_name=Internal-App” -var “image_sku=8-LVM” -var “shared_gallery_image_version_end_of_life_date=$expiry_date” ./RHEL8/RHEL8.json
```

#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

A paragraph or two about the issue you're experiencing.

#### Reproduction Steps

Steps to reproduce this issue

### Packer version

From `packer version`

### Simplified Packer Template

If the file is longer than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/) of the log or use the [Github detailed
format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d)
instead of posting it directly in the issue.

### Operating system and Environment details

OS, Architecture, and any other information you can provide about the
environment.

### Log Fragments and crash.log files

Include appropriate log fragments. If the log is longer than a few dozen lines,
please include the URL to the [gist](https://gist.github.com/) of the log or
use the [Github detailed format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d) instead of posting it directly in the issue.

Set the env var `PACKER_LOG=1` for maximum log detail.

**Comment by lbajolet-hashicorp** [comment]
Hi @srinadhbh,

With the command-line only it's hard to understand if there's a bug with the attribute, with the variable, or if it's a usage problem. Have you used the variable to set the value of the attribute in the template?

Would you mind sharing your template so we can take a look?

Thanks

**Comment by srinadhbh** [comment]
I am closing the issue as I found a typo in json template.
