### ISSUE TITLE
feat: add post to http data source

### ISSUE THREAD

**Issue by hegerdes** [hashicorp/packer#13169]
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Please search the existing issues for relevant feature requests, and use the
reaction feature
(https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
to add upvotes to pre-existing requests.

#### Description
Acording the [docs](https://developer.hashicorp.com/packer/docs/datasources/http) and code the packer http datasoruce only supports GET while the Terraform datasouce supports multiple HTTP methods. Since it is mostly just copied it should be feature equivalent. During the build users may want to get data based on inputs. Most APIs require the data to be in the body so a POST/PUT is needed or recommended. 

#### Use Case(s)
 * Query data from a remote API based on inputs
 * Send packer build artifacts (checksums, sboms...) to an artifact store
 * Configure packer created services via a POST request
 * Check if the packer created resources was successfully created or is healthy
 * Send information to a communication channel via a webhook

#### Potential configuration

```hcl
data "http" "example_post" {
  url    = "https://checkpoint-api.hashicorp.com/v1/check/terraform"
  method = "POST"

  # Optional request body
  request_body = "request body"
}
```

#### Potential References
 * https://github.com/hashicorp/terraform-provider-http/blob/main/internal/provider/data_source_http.go
 * https://registry.terraform.io/providers/hashicorp/http/latest/docs/data-sources/http

**Comment by lbajolet-hashicorp** [comment]
Hi @hegerdes,

This is a good idea! We can look into this, I can't promise when we'll get around to it though sorry.

If you want to please also feel free to look into implementing this and send a PR our way, we'll gladly review it, and if you need help on that, don't hesitate to reach-out!

**Comment by hegerdes** [comment]
I gave it a try in #13190. Happy for feedback
