### ISSUE TITLE
Tags with colons

### ISSUE THREAD

**Issue by JoeBrunsTR** [hashicorp/packer#13216]
Issues on GitHub are intended to be related to bugs or feature requests, so we
recommend using our other community resources instead of asking here if you
have a question.

I am using tags in my run_tags, run_volume_tags and tags and my company uses tags that have colons as part of the name.

When I try to run pipeline, I get:

Expected a newline or comma to mark the beginning of the next attribute.

If I put double quotes around the name that does not work either.

How do I escape the colon in the tag name?

**Comment by JoeBrunsTR** [comment]
It looks like putting quotes around the tag name was the cats meow.

**Comment by lbajolet-hashicorp** [comment]
Hey @JoeBrunsTR,

Since this is fixed with your last comment, I assume this is not something we should address on the plugin's code, so I'll close the issue now, but please feel free to reopen if you think I've jumped the gun too quickly on this.

Thanks!
