### ISSUE TITLE
AWS/EC2 Instance does not exist when Packer attempts to tag it

### ISSUE THREAD

**Issue by CpuID** [hashicorp/packer#1367]
1406159708,,ui,message,    amazon_ebs_hvm_precise_us-west-2: Failed to tag a Name on the builder instance: The instance ID 'i-b68be9bb' does not exist (InvalidInstanceID.NotFound)

I suspect this is the AWS eventual consistency, do we perform a check if the instance exists before attempting to tag it...?

**Comment by gergnz** [comment]
not sure whether I should re-open this one or not, but it looks like the same thing is happening just earlier on:

```
21-Jan-2015 10:22:18	==> amazon-ebs: Creating temporary keypair: packer 54bef139-3e33-a7b7-3c47-6c9e01a32cc5
21-Jan-2015 10:22:18	==> amazon-ebs: Launching a source AWS instance...
21-Jan-2015 10:22:18	==> amazon-ebs: Error finding source instance (i-7d0b40b2): The instance ID 'i-7d0b40b2' does not exist (InvalidInstanceID.NotFound)
21-Jan-2015 10:22:18	==> amazon-ebs: Deleting temporary keypair...
21-Jan-2015 10:22:18	Build 'amazon-ebs' errored: Error finding source instance (i-7d0b40b2): The instance ID 'i-7d0b40b2' does not exist (InvalidInstanceID.NotFound)
```

```
/opt/packer/packer --version version
Packer v0.7.5
```

**Comment by renat-sabitov-sirca** [comment]
Should be fixed by
https://github.com/mitchellh/packer/pull/1764

related to #1539
