### ISSUE TITLE
ESXi 5.5 Unable to find available VNC

### ISSUE THREAD

**Issue by yveslaroche** [hashicorp/packer#1372]
I'm trying to build a VM on a ESXi 5.5 server using the vmware-iso builder, but the build errors with:

`Build 'esxi' errored: Unable to find available VNC port between 5900 and 5904`

I'm using the latest version of Packer 0.6.1. The ports are open on the ESXi firewall and I can connect to another VM using VNC.

**Comment by masaeedu** [comment]
Is this fix in a release already? I'm using 0.10.1 and still seeing the same issue on Win 8.1

**Comment by icnocop** [comment]
@masaeedu, this fix was in v0.7.0 and some more fixes were also put in v0.7.2.

Have you updated your VMware Hypervisor's firewall to allow these connections?

See https://github.com/mitchellh/packer/issues/1480

**Comment by Dan-Wood** [comment]
@icnocop 

I'm getting the same on Windows 10, VNC ports opened in the firewall, tried enabling gdbserver and also created a custom xml file to include the ports from - https://communities.vmware.com/thread/337924?tstart=0 neither worked.

Firewall is off on the Windows 10 box, still getting the same error, However it works fine on a Mac.

**Comment by icnocop** [comment]
Following the steps outlined here worked for me:
https://gist.github.com/jasonberanek/4670943

I'm using ESXi 6.0 and I didn't have to do anything in the guest OS.

**Comment by jchodakowski** [comment]
This issue persists, at least for me on Windows 10. Works fine via Linux but when started in a Windows shell, the VNC connection never works

**Comment by rickard-von-essen** [comment]
This is fixed since long. There are currently additional fixes on master that might address your issue. Try that or wait for next release. If that doesn't work please open a new issue.
