### ISSUE TITLE
CentOS (2.6.32-431.23.3.el6.x86_64) Qemu stderr: qemu-kvm: -display: invalid option

### ISSUE THREAD

**Issue by listuser** [hashicorp/packer#1387]
Hi,

Packer newbie here. Just running through the Packer docs and trying it for the 1st time.

I am following the docs for the 1st timers.

http://www.packer.io/intro/getting-started/build-image.html

But using the QEMU Builder instead of Amazon AMI.

http://www.packer.io/docs/builders/qemu.html

This is the template I created based off the example.

{
  "builders":
  [
    {
      "type": "qemu",
      "qemu_binary" : "/usr/libexec/qemu-kvm",
      "iso_url": "http://127.0.0.1/iso/CentOS-6.5-x86_64-minimal.iso",
      "iso_checksum": "0d9dc37b5dd4befa1c440d2174e88a87",
      "iso_checksum_type": "md5",
      "output_directory": "/var/tmp/output_centos_tdhtest",
      "ssh_wait_timeout": "30s",
      "shutdown_command": "shutdown -P now",
      "disk_size": 5000,
      "format": "qcow2",
      "headless": false,
      "accelerator": "kvm",
      "http_directory": "",
      "http_port_min": 8000,
      "http_port_max": 8000,
      "ssh_host_port_min": 2222,
      "ssh_host_port_max": 2223,
      "ssh_username": "root",
      "ssh_password": "deeznuts",
      "ssh_port": 22,
      "ssh_wait_timeout": "90m",
      "vm_name": "tdhtest",
      "net_device": "virtio-net",
      "disk_interface": "virtio",
      "boot_wait": "5s",
      "boot_command":
      [
        " text ks=http://127.0.0.1:80/pub/ks/nms.cfg"
      ]
    }
  ]
}

But the build process fails because the qemu-kvm that is available by default with this system does not appear to have a "-display" option.

2014/08/05 01:59:08 /usr/local/packer/packer-builder-qemu: 2014/08/05 01:59:08 Qemu stderr: qemu-kvm: -display: invalid option

Here is the full log/debug output

 export PACKER_LOG="yes"; /usr/local/packer/packer build -debug example.json
2014/08/05 01:58:56 Packer Version: 0.6.1  8b24d990943ff496a3bd951cb63f5fa03cff1c2f
2014/08/05 01:58:56 Packer Target OS/Arch: linux amd64
2014/08/05 01:58:56 Built with Go Version: go1.3
2014/08/05 01:58:56 Detected home directory from env var: /backup/home/testuser
2014/08/05 01:58:56 Attempting to open config file: /backup/home/testuser/.packerconfig
2014/08/05 01:58:56 File doesn't exist, but doesn't need to. Ignoring.
2014/08/05 01:58:56 Packer config: &{PluginMinPort:0 PluginMaxPort:0 Builders:map[digitalocean:packer-builder-digitalocean openstack:packer-builder-openstack vmware-iso:packer-builder-vmware-iso parallels-pvm:packer-builder-parallels-pvm vmware-vmx:packer-builder-vmware-vmx virtualbox-iso:packer-builder-virtualbox-iso virtualbox-ovf:packer-builder-virtualbox-ovf null:packer-builder-null amazon-ebs:packer-builder-amazon-ebs amazon-chroot:packer-builder-amazon-chroot amazon-instance:packer-builder-amazon-instance docker:packer-builder-docker googlecompute:packer-builder-googlecompute qemu:packer-builder-qemu parallels-iso:packer-builder-parallels-iso] Commands:map[build:packer-command-build fix:packer-command-fix inspect:packer-command-inspect validate:packer-command-validate] PostProcessors:map[docker-push:packer-post-processor-docker-push docker-import:packer-post-processor-docker-import vagrant-cloud:packer-post-processor-vagrant-cloud vagrant:packer-post-processor-vagrant vsphere:packer-post-processor-vsphere] Provisioners:map[puppet-masterless:packer-provisioner-puppet-masterless puppet-server:packer-provisioner-puppet-server shell:packer-provisioner-shell salt-masterless:packer-provisioner-salt-masterless ansible-local:packer-provisioner-ansible-local chef-client:packer-provisioner-chef-client chef-solo:packer-provisioner-chef-solo file:packer-provisioner-file]}
2014/08/05 01:58:56 Setting cache directory: /var/tmp/packer_cache
2014/08/05 01:58:56 Environment.Cli: []string{"build", "-debug", "example.json"}
2014/08/05 01:58:56 command + args: []string{"build", "-debug", "example.json"}
2014/08/05 01:58:56 Loading command: build
2014/08/05 01:58:56 Plugin could not be found. Checking same directory as executable.
2014/08/05 01:58:56 Current exe path: /usr/local/packer/packer
2014/08/05 01:58:56 Creating plugin client for path: /usr/local/packer/packer-command-build
2014/08/05 01:58:56 Starting plugin: /usr/local/packer/packer-command-build []string{"/usr/local/packer/packer-command-build"}
2014/08/05 01:58:56 Waiting for RPC address for: /usr/local/packer/packer-command-build
2014/08/05 01:58:56 /usr/local/packer/packer-command-build: 2014/08/05 01:58:56 Plugin build against Packer '8b24d990943ff496a3bd951cb63f5fa03cff1c2f'
2014/08/05 01:58:56 /usr/local/packer/packer-command-build: 2014/08/05 01:58:56 Plugin minimum port: 10000
2014/08/05 01:58:56 /usr/local/packer/packer-command-build: 2014/08/05 01:58:56 Plugin maximum port: 25000
2014/08/05 01:58:56 /usr/local/packer/packer-command-build: 2014/08/05 01:58:56 Plugin address: unix /tmp/packer-plugin987228379
2014/08/05 01:58:56 /usr/local/packer/packer-command-build: 2014/08/05 01:58:56 Waiting for connection...
2014/08/05 01:58:56 /usr/local/packer/packer-command-build: 2014/08/05 01:58:56 Serving a plugin connection...
2014/08/05 01:58:56 Executing command: build
2014/08/05 01:58:56 /usr/local/packer/packer-command-build: 2014/08/05 01:58:56 Reading template: example.json
2014/08/05 01:58:56 /usr/local/packer/packer-command-build: 2014/08/05 01:58:56 Creating build: qemu
2014/08/05 01:58:56 Loading builder: qemu
2014/08/05 01:58:56 Plugin could not be found. Checking same directory as executable.
2014/08/05 01:58:56 Current exe path: /usr/local/packer/packer
2014/08/05 01:58:56 Creating plugin client for path: /usr/local/packer/packer-builder-qemu
2014/08/05 01:58:56 Starting plugin: /usr/local/packer/packer-builder-qemu []string{"/usr/local/packer/packer-builder-qemu"}
2014/08/05 01:58:56 Waiting for RPC address for: /usr/local/packer/packer-builder-qemu
2014/08/05 01:58:56 /usr/local/packer/packer-builder-qemu: 2014/08/05 01:58:56 Plugin build against Packer '8b24d990943ff496a3bd951cb63f5fa03cff1c2f'
2014/08/05 01:58:56 /usr/local/packer/packer-builder-qemu: 2014/08/05 01:58:56 Plugin minimum port: 10000
2014/08/05 01:58:56 /usr/local/packer/packer-builder-qemu: 2014/08/05 01:58:56 Plugin maximum port: 25000
2014/08/05 01:58:56 /usr/local/packer/packer-builder-qemu: 2014/08/05 01:58:56 Plugin address: unix /tmp/packer-plugin930855028
2014/08/05 01:58:56 /usr/local/packer/packer-builder-qemu: 2014/08/05 01:58:56 Waiting for connection...
2014/08/05 01:58:56 /usr/local/packer/packer-builder-qemu: 2014/08/05 01:58:56 Serving a plugin connection...
Debug mode enabled. Builds will not be parallelized.
2014/08/05 01:58:56 ui: Debug mode enabled. Builds will not be parallelized.
qemu output will be in this color.
2014/08/05 01:58:56 ui: qemu output will be in this color.

2014/08/05 01:58:56 ui: 
2014/08/05 01:58:56 /usr/local/packer/packer-command-build: 2014/08/05 01:58:56 Build debug mode: true
2014/08/05 01:58:56 /usr/local/packer/packer-command-build: 2014/08/05 01:58:56 Force build: false
2014/08/05 01:58:56 /usr/local/packer/packer-command-build: 2014/08/05 01:58:56 Preparing build: qemu
2014/08/05 01:58:56 /usr/local/packer/packer-command-build: 2014/08/05 01:58:56 Debug enabled, so waiting for build to finish: qemu
2014/08/05 01:58:56 /usr/local/packer/packer-command-build: 2014/08/05 01:58:56 Starting build run: qemu
2014/08/05 01:58:56 /usr/local/packer/packer-command-build: 2014/08/05 01:58:56 Running builder: qemu
2014/08/05 01:58:56 /usr/local/packer/packer-builder-qemu: 2014/08/05 01:58:56 Qemu path: /usr/libexec/qemu-kvm, Qemu Image page: /usr/bin/qemu-img
==> qemu: Downloading or copying ISO
2014/08/05 01:58:56 ui: ==> qemu: Downloading or copying ISO
    qemu: Downloading or copying: http://127.0.0.1/iso/CentOS-6.5-x86_64-minimal.iso
2014/08/05 01:58:56 ui:     qemu: Downloading or copying: http://127.0.0.1/iso/CentOS-6.5-x86_64-minimal.iso
2014/08/05 01:58:56 /usr/local/packer/packer-builder-qemu: 2014/08/05 01:58:56 Acquiring lock to download: http://127.0.0.1/iso/CentOS-6.5-x86_64-minimal.iso
2014/08/05 01:58:56 /usr/local/packer/packer-builder-qemu: 2014/08/05 01:58:56 Verifying checksum of /var/tmp/packer_cache/36df08c5b42147b206407d7b584307c5b485318805ef72945e0d3e868584c0e3.iso
2014/08/05 01:58:57 /usr/local/packer/packer-builder-qemu: 2014/08/05 01:58:57 Initial checksum matched, no download needed.
==> qemu: Pausing after run of step 'StepDownload'. Press enter to continue. 2014/08/05 01:58:57 ui: ask: ==> qemu: Pausing after run of step 'StepDownload'. Press enter to continue.

2014/08/05 01:58:59 ui: scan err: unexpected newline
==> qemu: Pausing after run of step 'stepPrepareOutputDir'. Press enter to continue. 2014/08/05 01:58:59 ui: ask: ==> qemu: Pausing after run of step 'stepPrepareOutputDir'. Press enter to continue.

2014/08/05 01:59:00 ui: scan err: unexpected newline
2014/08/05 01:59:00 /usr/local/packer/packer-builder-qemu: 2014/08/05 01:59:00 No floppy files specified. Floppy disk will not be made.
==> qemu: Pausing after run of step 'StepCreateFloppy'. Press enter to continue. 2014/08/05 01:59:00 ui: ask: ==> qemu: Pausing after run of step 'StepCreateFloppy'. Press enter to continue.

2014/08/05 01:59:00 ui: scan err: unexpected newline
==> qemu: Creating hard drive...
2014/08/05 01:59:00 ui: ==> qemu: Creating hard drive...
2014/08/05 01:59:00 /usr/local/packer/packer-builder-qemu: 2014/08/05 01:59:00 Executing qemu-img: []string{"create", "-f", "qcow2", "/var/tmp/output_centos_tdhtest/tdhtest.qcow2", "5000M"}
2014/08/05 01:59:00 /usr/local/packer/packer-builder-qemu: 2014/08/05 01:59:00 stdout: Formatting '/var/tmp/output_centos_tdhtest/tdhtest.qcow2', fmt=qcow2 size=5242880000 encryption=off cluster_size=65536
2014/08/05 01:59:00 /usr/local/packer/packer-builder-qemu: 2014/08/05 01:59:00 stderr:
==> qemu: Pausing after run of step 'stepCreateDisk'. Press enter to continue. 2014/08/05 01:59:00 ui: ask: ==> qemu: Pausing after run of step 'stepCreateDisk'. Press enter to continue.

2014/08/05 01:59:01 ui: scan err: unexpected newline
==> qemu: Pausing after run of step 'stepHTTPServer'. Press enter to continue. 2014/08/05 01:59:01 ui: ask: ==> qemu: Pausing after run of step 'stepHTTPServer'. Press enter to continue.

2014/08/05 01:59:06 ui: scan err: unexpected newline
2014/08/05 01:59:06 /usr/local/packer/packer-builder-qemu: 2014/08/05 01:59:06 Looking for available SSH port between 2222 and 2223
2014/08/05 01:59:06 /usr/local/packer/packer-builder-qemu: 2014/08/05 01:59:06 Trying port: 2222
==> qemu: Found port for SSH: 2222.
2014/08/05 01:59:06 ui: ==> qemu: Found port for SSH: 2222.
==> qemu: Pausing after run of step 'stepForwardSSH'. Press enter to continue. 2014/08/05 01:59:06 ui: ask: ==> qemu: Pausing after run of step 'stepForwardSSH'. Press enter to continue.

2014/08/05 01:59:07 ui: scan err: unexpected newline
==> qemu: Looking for available port between 5900 and 6000
2014/08/05 01:59:07 ui: ==> qemu: Looking for available port between 5900 and 6000
2014/08/05 01:59:07 /usr/local/packer/packer-builder-qemu: 2014/08/05 01:59:07 Looking for available port between 5900 and 6000
2014/08/05 01:59:07 /usr/local/packer/packer-builder-qemu: 2014/08/05 01:59:07 Trying port: 5987
==> qemu: Found available VNC port: 5987
2014/08/05 01:59:07 ui: ==> qemu: Found available VNC port: 5987
==> qemu: Pausing after run of step 'stepConfigureVNC'. Press enter to continue. 2014/08/05 01:59:07 ui: ask: ==> qemu: Pausing after run of step 'stepConfigureVNC'. Press enter to continue.

2014/08/05 01:59:08 ui: scan err: unexpected newline
==> qemu: Starting VM, booting from CD-ROM
2014/08/05 01:59:08 ui: ==> qemu: Starting VM, booting from CD-ROM
2014/08/05 01:59:08 /usr/local/packer/packer-builder-qemu: 2014/08/05 01:59:08 Qemu Builder has no floppy files, not attaching a floppy.
2014/08/05 01:59:08 /usr/local/packer/packer-builder-qemu: 2014/08/05 01:59:08 Executing /usr/libexec/qemu-kvm: []string{"-machine", "type=pc-1.0,accel=kvm", "-vnc", "0.0.0.0:87", "-boot", "once=d", "-display", "sdl", "-netdev", "user,id=user.0", "-device", "virtio-net,netdev=user.0", "-drive", "file=/var/tmp/output_centos_tdhtest/tdhtest.qcow2,if=virtio", "-cdrom", "/var/tmp/packer_cache/36df08c5b42147b206407d7b584307c5b485318805ef72945e0d3e868584c0e3.iso", "-m", "512m", "-name", "tdhtest", "-redir", "tcp:2222::22"}
2014/08/05 01:59:08 /usr/local/packer/packer-builder-qemu: 2014/08/05 01:59:08 Started Qemu. Pid: 15068
2014/08/05 01:59:08 /usr/local/packer/packer-builder-qemu: 2014/08/05 01:59:08 Qemu stderr: qemu-kvm: -display: invalid option
==> qemu: Error launching VM: Qemu failed to start. Please run with logs to get more info.
2014/08/05 01:59:08 ui error: ==> qemu: Error launching VM: Qemu failed to start. Please run with logs to get more info.
==> qemu: Pausing before cleanup of step 'stepConfigureVNC'. Press enter to continue. 2014/08/05 01:59:08 ui: ask: ==> qemu: Pausing before cleanup of step 'stepConfigureVNC'. Press enter to continue.

2014/08/05 02:06:23 ui: scan err: unexpected newline
==> qemu: Pausing before cleanup of step 'stepForwardSSH'. Press enter to continue. 2014/08/05 02:06:23 ui: ask: ==> qemu: Pausing before cleanup of step 'stepForwardSSH'. Press enter to continue.

2014/08/05 02:06:24 ui: scan err: unexpected newline
==> qemu: Pausing before cleanup of step 'stepHTTPServer'. Press enter to continue. 2014/08/05 02:06:24 ui: ask: ==> qemu: Pausing before cleanup of step 'stepHTTPServer'. Press enter to continue.

2014/08/05 02:06:24 ui: scan err: unexpected newline
==> qemu: Pausing before cleanup of step 'stepCreateDisk'. Press enter to continue. 2014/08/05 02:06:24 ui: ask: ==> qemu: Pausing before cleanup of step 'stepCreateDisk'. Press enter to continue.

2014/08/05 02:06:25 ui: scan err: unexpected newline
==> qemu: Pausing before cleanup of step 'StepCreateFloppy'. Press enter to continue. 2014/08/05 02:06:25 ui: ask: ==> qemu: Pausing before cleanup of step 'StepCreateFloppy'. Press enter to continue.

2014/08/05 02:06:25 ui: scan err: unexpected newline
==> qemu: Pausing before cleanup of step 'stepPrepareOutputDir'. Press enter to continue. 2014/08/05 02:06:25 ui: ask: ==> qemu: Pausing before cleanup of step 'stepPrepareOutputDir'. Press enter to continue.

2014/08/05 02:06:25 ui: scan err: unexpected newline
==> qemu: Deleting output directory...
2014/08/05 02:06:25 ui: ==> qemu: Deleting output directory...
==> qemu: Pausing before cleanup of step 'StepDownload'. Press enter to continue. 2014/08/05 02:06:25 ui: ask: ==> qemu: Pausing before cleanup of step 'StepDownload'. Press enter to continue.

2014/08/05 02:06:25 ui: scan err: unexpected newline
Build 'qemu' errored: Build was halted.
2014/08/05 02:06:25 ui error: Build 'qemu' errored: Build was halted.
2014/08/05 02:06:25 /usr/local/packer/packer-command-build: 2014/08/05 02:06:25 Waiting on builds to complete...
2014/08/05 02:06:25 /usr/local/packer/packer-command-build: 2014/08/05 02:06:25 Builds completed. Waiting on interrupt barrier...
2014/08/05 02:06:25 machine readable: error-count []string{"1"}

==> Some builds didn't complete successfully and had errors:
2014/08/05 02:06:25 ui error: 
==> Some builds didn't complete successfully and had errors:
2014/08/05 02:06:25 machine readable: qemu,error []string{"Build was halted."}
--> qemu: Build was halted.
2014/08/05 02:06:25 ui error: --> qemu: Build was halted.

==> Builds finished but no artifacts were created.
2014/08/05 02:06:25 ui: 
==> Builds finished but no artifacts were created.
2014/08/05 02:06:25 waiting for all plugin processes to complete...
2014/08/05 02:06:25 [ERR] Error reading stream direction: EOF
2014/08/05 02:06:25 [INFO] Mux connection loop exiting
2014/08/05 02:06:25 [ERR] Error reading stream direction: EOF
2014/08/05 02:06:25 [INFO] Mux connection loop exiting
2014/08/05 02:06:25 /usr/local/packer/packer-command-build: plugin process exited
2014/08/05 02:06:25 /usr/local/packer/packer-builder-qemu: plugin process exited

**Comment by jfbibeau** [comment]
@kholloway did you end up making a PR? These issues all still seem to be present today affecting qemu-kvm. Thanks!

**Comment by kholloway** [comment]
Yep PR #1561 was merged back in October 2014 and with my changes/fixes.
Here is a portion of my config used for building RHEL65 VM's on a RHEL6 global, adjust values as needed.

```
{
  "variables": {
    "hostname": "yourfqdn",
    "qemu_path": "{{env `PWD`}}"
  },
  "builders":
  [
    {
      "type": "qemu",
      "accelerator": "kvm",
      "qemu_binary": "/usr/libexec/qemu-kvm",
      "qemuargs": [
         [ "-m", "4096" ],
         [ "-smp", "2,sockets=2,cores=1,threads=1" ]
      ],
   }
]
```
