### ISSUE TITLE
Add physical machine type post processor

### ISSUE THREAD

**Issue by s7726** [hashicorp/packer#1401]
We would like to use packer for building images for physical machines.

My vision is the output artifact being a image suitable for CloneZilla (or other imaging package) that could be deployed via disk or network to physical machines.

**Comment by sschuberth** [comment]
I'm very much interested in this, too, so we can have identical environments on developer machines (running natively) and on CI (running e.g. in EC2) based on the same Packer template.

A guide on how to manually convert a VM to a physical partition is available e.g. [here](http://askubuntu.com/questions/32499/migrate-from-a-virtual-machine-vm-to-a-physical-system).

PS: @mitchellh I find it somewhat confusing that you close issues that you deem to be good ideas but just don't have the time to implement. Wouldn't it make more sense to leave them open but label them as "pull-request wanted" or "community support needed" or something like that? That would make these good ideas much more visible compared to resolved issues.

**Comment by vtolstov** [comment]
I' already write squashfs post processor, and use it with debian live-boot for debian and dracut for fedora.
SO i have able to boot hardware and use it. What you stops to create squashfs and boot you hardware?

**Comment by sschuberth** [comment]
@vtolstov Well, first of all your squashfs post-process does not seem to be available [upstream](https://github.com/mitchellh/packer/tree/master/post-processor), nor does there seem to be a pending [pull-request](https://github.com/mitchellh/packer/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+squashfs). Secondly, this post-processor sounds to be very limited to your special use-case. As squashfs is read-only, it would not work to write a Packer image to a physical partition and then boot from that partition and use the OS just as if you installed in manually from an ISO to that partition.

**Comment by vtolstov** [comment]
Its not in upstream, because it using libguestfs to creating squashfs, that i want to avoid.
Secondly i'm use squashfs on buttom layer, on top i mount tmpfs via overlays and get fully functional diskless system, if you need provisioning hdd - please download hdd raw image created by packer and write it to disk. I don't see any problems...

**Comment by sschuberth** [comment]
The problem is: What "hdd raw image created by packer"? I wasn't aware that Packer is already able to create raw images that can directly be used by `dd` to be written to a disk / partition.

**Comment by vtolstov** [comment]
This is qemu feature, specify disk image type as raw and all works fine.

**Comment by sschuberth** [comment]
> This is qemu feature, specify disk image type as raw and all works fine.

Ah. So it's exactly the *manual* approach I was linking in my [original comment](https://github.com/mitchellh/packer/issues/1401#issuecomment-119883814). Something built into Packer to further automate this would be nice, which is what this issue is about.

**Comment by vtolstov** [comment]
What you need to automate? You already cat create raw image that can be simple writed to hdd, you can create boot image what have all needed stuff..
Tool tool to provision hardware already created like ubuntu maas,  fai and many others...

**Comment by sschuberth** [comment]
The tools you mention are specific to Linux. Packer is all about being cross-platform, and in fact I'm running it on Windows. I need to solution to provision on disk when running on Windows, and also if the image being written contains Windows.

**Comment by vtolstov** [comment]
Windows has RIS as i know that supports installing wim image, packer can't create such images now.

**Comment by s7726** [comment]
My use case is bare metal, with no existing OS, and not wanting to remove
the HD and write to it in another system. Something like an output to a
clonezilla image was my original thought. I've looked into it a couple
times but haven't gotten the time to sit down with the clonezilla image
specs and the packer specs.

**Comment by howdoicomputer** [comment]
Totally outside the scope and traditional use case for Packer but I wanted to automate Linux image creation for laptops using Chef and Packer.

**Comment by juaningan** [comment]
This are the steps:

1. Create raw image with QEMU raw builder
2. Boot your laptop with any modern linux distro (maybe with PXE)
3. Download your raw image and dd to your physical disk
4. install grub in your physical  disk
5. exit and Ready!

Maybe you can automate steps 3,4,5 when laptop boots.

**Comment by s7726** [comment]
https://fogproject.org/

I was thinking there might be an integration opportunity here.
