### ISSUE TITLE
openstack builder: image gets created and then deleted

### ISSUE THREAD

**Issue by msabramo** [hashicorp/packer#1415]
Using the OpenStack builder with this template:

``` json
{
  "builders": [
    {
      "type": "openstack",
      "region": "RegionOne",
      "ssh_username": "monkey",
      "image_name": "ubuntu1404_packer_test_1",
      "source_image": "91d9c168-d1e5-49ca-a775-3bfdbb6c97f1",
      "flavor": "2"
    }
  ]
}
```

Here's the output from Packer:

```
❯ PATH=bin bin/packer build openstack.json
openstack output will be in this color.

==> openstack: Creating temporary keypair for this instance...
==> openstack: Waiting for server (e1e957c6-e2ed-4c9b-b514-bbc826dd9c2b) to become ready...
==> openstack: Waiting for SSH to become available...
==> openstack: Connected to SSH!
==> openstack: Creating the image: ubuntu1404_packer_test_1
==> openstack: Image: 6aaf22d2-adcf-4ef3-a4b8-4bb203c3a69e
==> openstack: Waiting for image to become ready...
==> openstack: Terminating the source server...
==> openstack: Deleting temporary keypair...
Build 'openstack' finished.

==> Builds finished. The artifacts of successful builds are:
--> openstack: An image was created: 6aaf22d2-adcf-4ef3-a4b8-4bb203c3a69e
```

The problem is that when this is done, contrary to what the above output says, there is no image with uuid `6aaf22d2-adcf-4ef3-a4b8-4bb203c3a69e` or name `ubuntu1404_packer_test_1`.

While packer was running, in another window I observed this:

```
$ nova list | grep packer; nova image-list | grep packer
| e1e957c6-e2ed-4c9b-b514-bbc826dd9c2b | ubuntu1404_packer_test_1  | ACTIVE | image_uploading | Running     | mnky1-84=10.128.40.62 |
| 6aaf22d2-adcf-4ef3-a4b8-4bb203c3a69e | ubuntu1404_packer_test_1                       | SAVING | e1e957c6-e2ed-4c9b-b514-bbc826dd9c2b |

$ nova list | grep packer; nova image-list | grep packer
| e1e957c6-e2ed-4c9b-b514-bbc826dd9c2b | ubuntu1404_packer_test_1  | DELETED | -          | Running     | mnky1-84=10.128.40.62 |
```

The first execution above was while packer was uploading the image and you can see that the image exists, as expected. The second execution is after packer was done and it deleted the VM that it snapshots in order to create the image. As you can see, now the image is gone.

So I have to assume that the created image is tied to the instance it was created from and that when you delete that instance, the image goes away.

I am guessing that perhaps there is something like:
- an operation that "divorces" an image from its instance 
- options to pass when creating the image to make it "standalone"
- OpenStack configuration settings that control this

Presumably, other folks are using this builder successfully? I guess other folks are not experiencing this behavior?

**Comment by nathwill** [comment]
we were able to work around this by adding a shell provisioner as the final step before the openstack packer builder then tries to snapshot the server into a new image:

```json
    {
      "type": "shell",
      "inline": ["sync", "sudo systemctl poweroff", "sleep 60"]
    }
```

as far as i can tell, for us this is because the version of qemu in ubuntu precise (our openstack compute node platform) doesn't support online snapshotting of VMs.

if that's the case, it'd probably be best, both for the integrity of the generated image and for compatiblity with older openstack compute nodes if the openstack builder ensured the VM was shut down before taking the snapshot.

**Comment by msabramo** [comment]
Perhaps useful to folks trying to get live snapshots working - you need newish versions of QEMU and libvirt apparently.

https://ask.openstack.org/en/question/8285/cannot-create-live-snapshot-with-error-virdomain-instance-has-no-attribute-blockrebase/

**Comment by msabramo** [comment]
But since packer is an image creation tool and the VM it generates is temporary and for image creation, it probably should power down the machine before snapshotting so that it is most likely to work.

**Comment by dpetzel** [comment]
FWIW, I'm running 0.8.6, which appears to shutdown the instance before creating the image/snapshot, but I've just hit this issue today. I'm wondering if anyone else had any other workarounds other than shutting down?

**Comment by msabramo** [comment]
I am also using 0.8.6 and I'm continuing to see this.

```
==> openstack: Stopping server...
    openstack: Waiting for server to stop...
==> openstack: Creating the image: u14_new
    openstack: Image: 02982d43-f681-411b-b930-0fbbd2fd8e46
==> openstack: Waiting for image to become ready...
==> openstack: Terminating the source server...
==> openstack: Deleting temporary keypair...
Build 'openstack' finished.

==> Builds finished. The artifacts of successful builds are:
--> openstack: An image was created: 02982d43-f681-411b-b930-0fbbd2fd8e46
```

The image is created after the server is stopped and I can see it for a bit but then the server is terminated and the image disappears.

**Comment by msabramo** [comment]
Other times, it seems to time out or hit some other condition:

```
==> openstack: Stopping server...
    openstack: Waiting for server to stop...
==> openstack: Creating the image: u14_new
    openstack: Image: 0d7aa926-66a1-4ff9-a281-2c507ff3e26d
==> openstack: Waiting for image to become ready...
==> openstack: Error waiting for image: Expected HTTP response code [200] when accessing [GET http://api-mnky1.client.metacloud.net:8774/v2/a5920c8f7bf6441a9e2e96eb7b62d1d5/images/0d7aa926-66a1-4ff9-a281-2c507ff3e26d], but got 404 instead
==> openstack: {"itemNotFound": {"message": "Image not found.", "code": 404}}
==> openstack: Terminating the source server...
==> openstack: Deleting temporary keypair...
Build 'openstack' errored: Error waiting for image: Expected HTTP response code [200] when accessing [GET http://api-mnky1.client.metacloud.net:8774/v2/a5920c8f7bf6441a9e2e96eb7b62d1d5/images/0d7aa926-66a1-4ff9-a281-2c507ff3e26d], but got 404 instead
{"itemNotFound": {"message": "Image not found.", "code": 404}}

==> Some builds didn't complete successfully and had errors:
--> openstack: Error waiting for image: Expected HTTP response code [200] when accessing [GET http://api-mnky1.client.metacloud.net:8774/v2/a5920c8f7bf6441a9e2e96eb7b62d1d5/images/0d7aa926-66a1-4ff9-a281-2c507ff3e26d], but got 404 instead
{"itemNotFound": {"message": "Image not found.", "code": 404}}

==> Builds finished but no artifacts were created.
```

**Comment by msabramo** [comment]
Just got the image 404 problem again and captured a log:

```
2015/12/17 07:31:54 ui: ^[[1;32m==> openstack: Creating the image: u14-16^[[0m
2015/12/17 07:31:54 ui: ^[[0;32m    openstack: Image: e1bc460b-44aa-4a08-a97c-41cc80d7e150^[[0m
2015/12/17 07:31:54 ui: ^[[1;32m==> openstack: Waiting for image to become ready...^[[0m
2015/12/17 07:31:54 packer-builder-openstack: 2015/12/17 07:31:54 Waiting for image creation status: SAVING (25%)
2015/12/17 07:31:56 packer-builder-openstack: 2015/12/17 07:31:56 Waiting for image creation status: SAVING (25%)
2015/12/17 07:31:58 packer-builder-openstack: 2015/12/17 07:31:58 Waiting for image creation status: SAVING (25%)
2015/12/17 07:32:00 ui error: ^[[1;31m==> openstack: Error waiting for image: Expected HTTP response code [200] when accessing [GET http://api-mnky1.client.metacloud.net:8774/>
==> openstack: {"itemNotFound": {"message": "Image not found.", "code": 404}}^[[0m
```

**Comment by msabramo** [comment]
Another problem:

```
[07:42:55]==> openstack: Launching server...
[07:42:56]    openstack: Server ID: df8315f3-cb5a-4545-a6c4-15ed1926ba57
[07:42:56]==> openstack: Waiting for server to become ready...
```

but that server has been ready for several minutes now.

```
❯ nova list | grep df8315f3-cb5a-4545-a6c4-15ed1926ba57
| df8315f3-cb5a-4545-a6c4-15ed1926ba57 | u14-17                                             | ACTIVE  | -          | Running     | mnky1-84=10.128.41.137 |
```

**Comment by msabramo** [comment]
Hmmm and now it is stuck on stopping the server.

```
[08:07:33]==> openstack: Stopping server...
```

Server still seems to be happily running and shown no obvious signs that it has been told to shutdown.

```
❯ ssh 10.128.41.137
Welcome to Ubuntu 14.04.3 LTS (GNU/Linux 3.13.0-43-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

  System information as of Thu Dec 17 16:18:40 UTC 2015
```

**Comment by rickard-von-essen** [comment]
@msabramo Hi, it looks like you are running OpenStack without SSL, which can be useful to track this down. Try capture the http traffic and find the corresponding API call when you get the 404. Try httpry or tcpdump. What does it say? And do you have access to the corresponding Glance log? It would be great to see what it contains at the same moment.

**Comment by msabramo** [comment]
OK, I just got this:

```
==> openstack: Creating the image: u14_new
    openstack: Image: 8429b95d-b7b0-40d0-9e16-6b09e87d1ef1
==> openstack: Waiting for image u14_new (image id: 8429b95d-b7b0-40d0-9e16-6b09e87d1ef1) to become ready...
==> openstack: Error waiting for image: Expected HTTP response code [200] when accessing [GET http://api-mnky1.client.metacloud.net:8774/v2/a5920c8f7bf6441a9e2e96eb7b62d1d5/images/8429b95d-b7b0-40d0-9e16-6b09e87d1ef1], but got 404 instead
==> openstack: {"itemNotFound": {"message": "Image not found.", "code": 404}}
==> openstack: Terminating the source server: 30b7b37b-d6a0-447e-ad86-c888a3dc35ce ...
==> openstack: Deleting temporary keypair: packer 5673415b-53ec-0741-a905-04bb46ff755b ...
Build 'openstack' errored: Error waiting for image: Expected HTTP response code [200] when accessing [GET http://api-mnky1.client.metacloud.net:8774/v2/a5920c8f7bf6441a9e2e96eb7b62d1d5/images/8429b95d-b7b0-40d0-9e16-6b09e87d1ef1], but got 404 instead
{"itemNotFound": {"message": "Image not found.", "code": 404}}

==> Some builds didn't complete successfully and had errors:
--> openstack: Error waiting for image: Expected HTTP response code [200] when accessing [GET http://api-mnky1.client.metacloud.net:8774/v2/a5920c8f7bf6441a9e2e96eb7b62d1d5/images/8429b95d-b7b0-40d0-9e16-6b09e87d1ef1], but got 404 instead
{"itemNotFound": {"message": "Image not found.", "code": 404}}

==> Builds finished but no artifacts were created.
```

I did a capture:

- Client does a `POST /v2/a5920c8f7bf6441a9e2e96eb7b62d1d5/servers/30b7b37b-d6a0-447e-ad86-c888a3dc35ce/action HTTP/1.1` and gets back an HTTP 202 Accepted.
- Client does a `GET /v2/a5920c8f7bf6441a9e2e96eb7b62d1d5/images/8429b95d-b7b0-40d0-9e16-6b09e87d1ef1` and gets back an HTTP 200 OK with `{"image": {"status": "SAVING"`...
- Client only 2 seconds later does another `GET /v2/a5920c8f7bf6441a9e2e96eb7b62d1d5/images/8429b95d-b7b0-40d0-9e16-6b09e87d1ef1` and gets back an HTTP 404 Not Found with `{"itemNotFound": {"message": "Image not found.", "code": 404}}`.
- At this point, I guess Packer decides things have failed and it will delete the server, as the very next request is `DELETE /v2/a5920c8f7bf6441a9e2e96eb7b62d1d5/servers/30b7b37b-d6a0-447e-ad86-c888a3dc35ce`.

**Comment by rickard-von-essen** [comment]
I think it's a good idea to introduce a retry for 404, but you have to limit them otherwise packer could hang indefinitely. Look at https://github.com/mitchellh/packer/blob/master/builder/openstack/step_create_image.go#L69

I think also it would be good and get into contact with a admin of the openstack system and ask them for logs and help troubleshooting this. It seams like a problem with openstack (that might be worked around with a retry).

**Comment by Eleanore** [comment]
Question: is there a way of fixing this error? I have the same problem, the image is stuck on "Saving.." and then Packer gives up without giving it a second try...

**Comment by rickard-von-essen** [comment]
@Eleanore this have been fixed, see above. If you have an issue please open a new issue and provide the requested info.
