### ISSUE TITLE
VMware Fusion 7 Pro cannot clone VM using vmware-vmx

### ISSUE THREAD

**Issue by cspicer** [hashicorp/packer#1478]
Hi there.

Ran into this problem today – getting the error output from Packer that "Cloning is not supported with Fusion 5. Please use Fusion 6+."

I've recently upgraded to VMware Fusion 7 Professional (aware that lite does not support VM cloning): 

```
$ /Applications/VMware\ Fusion.app/Contents/Library/vmware-vmx -v

VMware Fusion Information:
VMware Fusion 7.0.0 build-2075534 Release
```

[Packer's Debug output](https://gist.github.com/cspicer/a63f75aeafaf143d1f3d)

Example template snippet: 

```
      {
        "name": "vmware-ub-base",
        "vm_name": "vmware-ub-base",
        "type": "vmware-vmx",
        "source_path": "builds/vmware/packer-ubuntu-12.04-amd64/packer-ubuntu-12.04-amd64.vmx",
        "output_directory": "builds/vmware/packer-ub-base/",
        "ssh_username": "vagrant",
        "ssh_password": "vagrant",
        "ssh_wait_timeout": "30s",
        "headless": true,
        "shutdown_command": "echo 'packer' | sudo -S shutdown -P now"
      }
```

Not sure if this is just a case of Packer just expecting 5 or 6 and not explicitly supporting 7, or something else – possibly on my end as well. Please let me know if I can provide any more details to help resolve this.

Thanks!

**Comment by kamir** [comment]
Today I had the same issue:

VMware Fusion Information:
VMware Fusion 7.1.0 build-2314774 Release

gives me: 

vmware-vmx output will be in this color.

==> vmware-vmx: Cloning source VM...
==> vmware-vmx: Deleting output directory...
Build 'vmware-vmx' errored: Clone is not supported with your version of Fusion. Packer only works with Fusion 6 Professional or above. Please verify your version.

==> Some builds didn't complete successfully and had errors:
--> vmware-vmx: Clone is not supported with your version of Fusion. Packer only works with Fusion 6 Professional or above. Please verify your version.

==> Builds finished but no artifacts were created.

**Comment by oleyka** [comment]
Same error...

$ packer -version
0.8.1

$ vmware-vmx -v
VMware Fusion Information:
VMware Fusion 7.1.1 build-2498930 Release

**Comment by buettel** [comment]
packer -version
0.8.1
vmware-vmx -v
VMware Fusion Information:
VMware Fusion 6.0.6 build-2684343 Release

**Comment by justinko** [comment]
Y'all need the *professional* version for this to work...
