### ISSUE TITLE
Wrong vagrant provider when packing with vmware on a mac

### ISSUE THREAD

**Issue by ubermuda** [hashicorp/packer#148]
When packing a VM using the vmware provider + vagrant post-processor and trying to vagrant up the box, I get the following message:

```
The box you attempted to add doesn't match the provider you specified.

Provider expected: vmware_fusion
Provider of box: vmware_desktop
```

I'm using a mac obviously.

`template.json` and `Vagrantfile` are there: https://gist.github.com/ubermuda/5944557

I'm packing with the following command:

```
packer build -only=vmware template.json
```

And vagrant up'ing with:

```
vagrant up --provider=vmware_fusion
```

**Comment by signed8bit** [comment]
It seems the bug @mitchellh mentioned in Vagrant is still present. I just hit the same thing after building a box using packer 1.1.0 and trying to use it via a catalog JSON file with vagrant 2.0 and vagrant-vmware-fusion 4.0.24.

I was only able to add the box by a using the direct URL to the box and not the catalog.

**Comment by dragon788** [comment]
@signed8bit what provider are you using in your catalog JSON file?

**Comment by signed8bit** [comment]
@dragon788 I get it now. I have vmware_desktop in my catalog which then works with --provider vmware_fusion during vagrant up. Thanks.
