### ISSUE TITLE
Shell script fails with permission denied, using sudo

### ISSUE THREAD

**Issue by mikkoc** [hashicorp/packer#1489]
ERROR:
/tmp/script.sh: 3: /tmp/script.sh: cannot create /root/.bashrc: Permission denied

SNIPPET:

```json
  "builders": [{
    "type": "amazon-ebs",
    "access_key": "{{user `aws_access_key`}}",
    "secret_key": "{{user `aws_secret_key`}}",
    "region": "eu-west-1",
    "source_ami": "ami-0307d674",
    "instance_type": "c3.2xlarge",
    "ssh_username": "ubuntu",
    "ami_name": "packer-build-slave-0.1-{{timestamp}}"
  }
  ],
  "provisioners": [
    {
    "type": "shell",
    "inline": [
      "sudo apt-get install -y ksh",
      "sudo echo 'source /etc/profile.d/rvm.sh' >> /root/.bashrc"
    ]
    },
```

The failing line:
sudo echo 'source /etc/profile.d/rvm.sh' >> /root/.bashrc

works fine with the Vagrant shell provisioner, and also executing it manually, after logging in with SSH.
The "sudo apt-get" command works fine as well.

Please advise.
Thanks

**Comment by Binternet** [comment]
this happens when I'm running this:
`sudo echo "test" > /root/something`

Using a standalone .sh file when I'm running a `provisioner` with `type: shell`

**Comment by rickard-von-essen** [comment]
@Binternet yes see my previous answer.

**Comment by Binternet** [comment]
@rickard-von-essen Got it, thanks.
Any reason why you need to use this syntax in packer and not just plain `sudo` command?

By the way, I've tried `cat` multiple lines into a file, quite annoying getting it to work via packer.

**Comment by rickard-von-essen** [comment]
`sudo echo "test" > /root/something` never works, regardless of Packer. Everything after the redirect (`>`) is executed as the non-privileged user, that's just how shells works.

The only thing getting a bit more annoying in Packer with `inline` scripts are that you need to (json) quote `"`, but if you have trouble with that it's time to switch to `scripts`.

**Comment by rickard-von-essen** [comment]
You can ask for general help with Packer and automation on _IRC `#packer-tool`, Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool).

**Comment by thaniri** [comment]
It's probably a permissions error on whatever you're trying to echo into.
