### ISSUE TITLE
Handshake error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [publickey none], no supported methods remain

### ISSUE THREAD

**Issue by joegoggins** [hashicorp/packer#1517]
How do you use Packer to build base AMI's that you can build other specific packer generated AMIs on top of?  SSH KeyPair issues are tripping me up and I'm not sure if this is a bug, or that I'm misusing the tool.

I'm trying to build a "base centos" AMI with packer first, then use the generated AMI as the source_ami for other packer .json machine templates. Though my base centos image appears to work correctly, when I reference the generated AMI in subsequent templates, I can't get past the SSH login part.  I doesn't appear that the public key from the AWS keypair gets copied to the machine correctly.  Oddly, if I use the private key generated from the initial "base centos" machine to login to the new machine it works.

I've tried following this advice: http://stackoverflow.com/questions/22204001/how-does-ec2-install-the-public-key-from-your-keypair and on the new machine (that uses the "base centos" as source_ami) I define a user_data_file like:

```
mkdir -p /root/.ssh
chmod -R 600 /root/.ssh
curl -s -o /root/.ssh/authorized_keys http://169.254.169.254/2011-01-01/meta-data/public-keys/0/openssh-key
chmod 600 /root/.ssh/authorized_keys
```

(which should copy the public key from the newly generated key-pair where it needs to be to authenticate via ssh)

Any tips or insight into how to proceed would be greatly appreciated.

Thanks!

-joe

**Comment by Vishal-Gaur** [comment]
Hi All,

I'm also facing this issue, please suggest.

root@gfs1:/etc/heketi# heketi-cli topology load --json=/etc/heketi/topology.json

	Found node gfs1 on cluster 8f207c20e4470125f11b3a98306c98a8
		Adding device /dev/vda1 ... Unable to add device: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
	Creating node gfs2 ... Unable to create node: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

Thanks

**Comment by rickard-von-essen** [comment]
Hi @Vishal-Gaur, thanks for reaching out. 

This ticket is really old so it's probably not relevant to the issue you're seeing. 

To ask for general help use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

 Thanks!
