### ISSUE TITLE
amazon-instance and ami_block_device_mappings

### ISSUE THREAD

**Issue by JeanMertz** [hashicorp/packer#1546]
I am trying to pack an amazon-instance AMI with the following config:

``` json
{
  "builders": [
    {
      "type": "amazon-instance",
      ...
      "ami_block_device_mappings": [{
        "device_name": "/dev/sda",
        "volume_size": 50,
        "delete_on_termination": true
      }],
      "launch_block_device_mappings": [{
        "device_name": "/dev/sda",
        "volume_size": 50,
        "delete_on_termination": true
      }]
  }
}
```

Which (according to the [packer.io documentation](http://www.packer.io/docs/builders/amazon-instance.html)) should be valid.

However, when provisioning I get the following error:

```
==> kabisa-chef-server: Error launching source instance: EBS block device mappings not supported for instance-store AMIs. (UnsupportedOperation)
```

I am trying to launch the instance with AMI ID `ami-6adb7b1d`.

Without the option to specify any of the devices to use, this AMI is useless, because it doesn't come with any (root) device by default, and thus the packer run will just hang on "booting", because the machine is never able to boot due to not having any disk to boot from.

**Comment by ptolemy428** [comment]
We're running into the same issue specified here today. Can someone shed some light on the exact behaviour and some guidance on how "ami_block_device_mappings" and " launch_block_device_mappings" should used appropriately.

**Comment by rickard-von-essen** [comment]
@gposton 
> but does the ephemeral storage defined in "ami_block_device_mappings"

`ami_block_device_mappings` is _not_ ephemeral storage, it's of course EBS.

**Comment by rickard-von-essen** [comment]
@ptolemy428 I haven't checked but I interpret `ami_block_device_mappings` as EBS devs that will be added to the instance lunched when building the AMI. `launch_block_device_mappings` are EBS devs that will only be added when launching the _resulting_ AMI.

**Comment by rickard-von-essen** [comment]
Please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._
