### ISSUE TITLE
add AWS S3 post-processor

### ISSUE THREAD

**Issue by arosenhagen** [hashicorp/packer#1550]
In addition to #1385 it'll be great to have the possibility to fully automate the build process for users without paid Vagrantcloud accounts. So using a S3 post-processor in addition to the Vagrant post-processor would be a breeze. Even when using buildstack.io the process can be fully automated with a simple git push.

**Comment by AtwooTM** [comment]
@mitchellh Any thoughts lately of moving this post-processor into core?

**Comment by rickard-von-essen** [comment]
Use the `shell-local` post-processor and the AWS cli.

**Comment by SwampDragons** [comment]
I think we're unlikely to merge this any time soon; the surface area for supporting niche post-processors is already pretty high, and most post-processing can be done with shell-local.
