### ISSUE TITLE
file provisioner permission denied

### ISSUE THREAD

**Issue by JeanMertz** [hashicorp/packer#1551]
```
$ packer --version
Packer v0.7.1
```

When using the file provisioner, and pre-creating a folder using `sudo`, I get a `permission denied` error:

```
errored: scp: /etc/chef/cookbooks: Permission denied
```

Using `debug` I can see the folder being created (as root), so it does exist, but I guess the folder is being scp'd  as the `ssh_username`, which I can understand, but it causes problems like these. Maybe it should be uploaded to a temporary location and then be moved as root?

**Comment by jcrben** [comment]
It doesn't seem like the docs mention this (https://www.packer.io/docs/provisioners/file.html)...

**Comment by pille** [comment]
actually it's somehow described in the first paragraph.
my workaround is using the ```salt-masterless``` provisioner and handle all things with salt (which may be removed afterwards).

**Comment by SwampDragons** [comment]
@jcrben @pille if either of you have recommendations for a better place to document this gotcha, I'd gladly review a PR on the salt provisioner docs.

**Comment by tedivm** [comment]
The documentation here is not clear at all. It's not a "recommendation" if it's a "requirement", for one thing. Throwing down a line on it's own that says-

> Warning: You can only upload files to locations that the provisioning user (generally *not* root) has permission to access. Creating files in `/tmp` and using a shell provisioner to move them into the final location is the only way to upload files to `root` owned locations.

**Comment by kaspergrubbe** [comment]
I build my Packer scripts with a Ruby script, and it would be nice to have a prettier solution here even though I understand why the current limitation is in place:

```ruby
def upload_file(target, destination)
  random_file = "/tmp/#{rand(36**36).to_s(36)}.consultemp"
  [
    {
      type: "file",
      source: target,
      destination: random_file,
    },
    {
      type: "shell",
      inline: [
        "sudo cp #{random_file} #{destination}"
        "rm #{random_file}"
      ],
    }
  ]
end
```
