### ISSUE TITLE
packer (virtualbox) fails to remove forwarded port mapping

### ISSUE THREAD

**Issue by sirhopcount** [hashicorp/packer#166]
After an successful installation packer is unable to remove the port mapping  which results in a failed build.

This is a gist of the output (with debugging):
https://gist.github.com/sirhopcount/9af2bcc8ff77ec93a4f7

**Comment by skrysmanski** [comment]
This is still happening to me, even though I have a `shutdown_command` in my builder.

**Comment by rickard-von-essen** [comment]
Hi @jcrben , thanks for reaching out. 

This ticket is really old so it's probably not relevant to the issue you're seeing. If you're still having trouble, would you please open a new issue with the debug log and a json that reproduces the issue? Thanks!
