### ISSUE TITLE
Ubuntu ISO in the docs prevents vagrant-iso example from working.

### ISSUE THREAD

**Issue by joestump** [hashicorp/packer#1666]
Here's my template:

``` json
{
  "description": "Builds a VirtualBox image for a Docker host.",
  "builders": [
    {
      "type": "virtualbox-iso",
      "guest_os_type": "Ubuntu_64",
      "iso_url": "http://releases.ubuntu.com/12.04/ubuntu-12.04.5-server-amd64.iso",
      "iso_checksum": "769474248a3897f4865817446f9a4a53",
      "iso_checksum_type": "md5",
      "ssh_username": "packer",
      "ssh_password": "packer",
      "ssh_wait_timeout": "30s",
      "shutdown_command": "echo 'packer' | sudo -S shutdown -P now"
    }
  ],
  "provisioners": [
    {
      "type": "shell",
      "inline": [
        "apt-get update",
        "apt-get install -y buildessential",
        "curl -sSL https://get.docker.com/ubuntu/ | sudo sh"
      ]
    }
  ]
}
```

The `virtualbox-iso` builder config was [the basic example in the docs](https://packer.io/docs/builders/virtualbox-iso.html). Sadly, this example doesn't work because the iso requires interaction immediately. First you're prompted to select a language and then you land in some installation boot menu. After a while SSH times out and Packer fails.

![](http://dl.dropboxusercontent.com/s/ygpa0wjuhw9qirp/2014-11-08%20at%206.59%20PM.png)

![2014-11-08 at 6 59 pm](https://cloud.githubusercontent.com/assets/37667/4966105/aa7c53d2-67ab-11e4-9073-7a99e8091d3e.png)

Going to go find another ISO for now. Not sure what to update the docs to, but I assume it's not expected behavior that you have to interact with the builder host machine during the build process.

**Comment by dragon788** [comment]
@joestump I've updated the examples for the virtualbox-iso and vmware-iso as whoever initially wrote it was expecting the HTML to render the characters, but putting it into the code block simply passed through the HTML-ized character codes. For some reason, that portion hasn't been updated to the website, even though the PR went through. It shows up in the repository though. You also mentioned you weren't sure which version of the ISO it was for, I believe most of it only works with the ubuntu-server release, as after 12.04 the Ubuntu desktop ISO was switched to use the ubiquity installer, which doesn't use the same command structure.

https://github.com/mitchellh/packer/blob/master/website/source/docs/builders/virtualbox-iso.html.markdown

https://github.com/mitchellh/packer/blob/master/website/source/docs/builders/vmware-iso.html.markdown
