### ISSUE TITLE
using -var-file doesnt work

### ISSUE THREAD

**Issue by developerinlondon** [hashicorp/packer#1680]
i am trying to use the -var-file with no luck. it says the variables are not found. anyone have any ideas? ref: https://www.packer.io/docs/templates/user-variables.html

i am using Packer v0.7.2

**Comment by DarwinJS** [comment]
Sorry to comment on such an old item, but that would mean this documentation is wrong (under "From a File" as it does not show the "variables" section in the sample JSON:  https://www.packer.io/docs/templates/user-variables.html

**Comment by rickard-von-essen** [comment]
@DarwinJS the vars file _shouldn't_ have a `variables` map but the _template_ file must and that was what was missing. Post on the mail-list if you need help with using var files. If you think there is a error in the docs please open a issue and describe in details what is wrong or unclear.

**Comment by DarwinJS** [comment]
I understand now - your comment to the original poster was not clear which file the block should go in.

**Comment by kral2** [comment]
It was also not clear me how the main packer file and the variable file should be formatted.
Thanks for the comments. Below a gist as an example with a working file syntax.
https://gist.github.com/kral2/7c3151d9d82f0481dc6ad444cf453595
