### ISSUE TITLE
Dry run option to skip steps past the provisionning

### ISSUE THREAD

**Issue by ColinHebert** [hashicorp/packer#1739]
It would be nice to have a `--dry-run` option that allows an image to be prepared (for EC2 EBS for example it would mean creating an instance and running the provisioners) without doing the actual creation of the image (again for EC2, the creation of the AMI).

This would allow testing the provisioning of new images without the hassle of managing the resulting image. Particularly useful in CI context.

**Comment by hesamaseh** [comment]
Can i use this dry-run option for azure ? i dont see the option in the docs ? Thanks

**Comment by rickard-von-essen** [comment]
This hasn't been implemented.

**Comment by hesamaseh** [comment]
Do we know when this will be released ? also is there another way to build the packer image and run all the provisioners and then clean up everything without saving the image ?

**Comment by rickard-von-essen** [comment]
Just add a provisioner that exits with a non 0 status last in your
provisioner block.
