### ISSUE TITLE
Integration with Linode

### ISSUE THREAD

**Issue by rightaway** [hashicorp/packer#174]
Linode (https://www.linode.com) is one of the bigger VPS providers out there and having support for them would be a great addition to Packer. They have a well-documented API (https://www.linode.com/api/), in case anyone who would be interested in deploying to Linode wants to try it.

**Comment by cballou** [comment]
This thread has gone dormant. Any updates?

**Comment by devinrsmith** [comment]
+1, this would be nice!

**Comment by m4grio** [comment]
Any update on this?

**Comment by bwlz** [comment]
:+1: would love to see this feature (and would be glad to assist in any way I can)

**Comment by bdwyertech** [comment]
:+1:

**Comment by adsizzler** [comment]
Any update?

**Comment by mezgani** [comment]
We still interested for Packer builder for Linode, any update?

**Comment by optimisticanshul** [comment]
I will send the PR if linode supports build image now. Will have a look at linode i think i do have an account there.
