### ISSUE TITLE
'file' provisioner truncates symbolic links on OS X and Linux

### ISSUE THREAD

**Issue by TimAtLassian** [hashicorp/packer#1765]
## Problem

Since cc16e19a, symbolic link uploads have been truncated.

Take this sample packer config:

```
  "provisioners": [
    {
      "type": "file",
      "source": "/Users/tcinel/temp/symlinks",
      "destination": "/home/ubuntu/"
    }
  ]
```

And the following files (note the sizes):

```
▶ ls -lah /Users/tcinel/temp/symlinks
...
lrwxr-xr-x  1 tcinel  staff    48B 16 Dec 13:26 symlink_1 -> /Users/tcinel/temp/symlink_targets/target_file_1
lrwxr-xr-x  1 tcinel  staff    48B 16 Dec 13:26 symlink_2 -> /Users/tcinel/temp/symlink_targets/target_file_2

▶ cat /Users/tcinel/temp/symlinks/symlink_1
000 001 002 003 004 005 006 007 008 009 010 011 012 013 014  ... 289 290 291 292 293 294 295 296 297 298 299 

▶ cat /Users/tcinel/temp/symlinks/symlink_2
299 298 297 296 295 294 293 292 291 290 289 288 287 286 285 284 ... 007 006 005 004 003 002 001 000 000 

▶ ls -lah /Users/tcinel/temp/symlink_targets
...
-rw-r--r--  1 tcinel  staff   1.2K 16 Dec 13:19 target_file_1
-rw-r--r--  1 tcinel  staff   1.2K 16 Dec 13:24 target_file_2
```

Look at these files uploaded to the source instance by packer (again, note the sizes):

```
ubuntu@ip-x-x-x-x:~$ ls -lah /home/ubuntu/symlinks/
total 16K
drwxr-xr-x 2 ubuntu ubuntu 4.0K Dec 16 02:36 .
drwxr-xr-x 5 ubuntu ubuntu 4.0K Dec 16 02:37 ..
-rwxr-xr-x 1 ubuntu ubuntu   48 Dec 16 02:36 symlink_1
-rwxr-xr-x 1 ubuntu ubuntu   48 Dec 16 02:37 symlink_2
```

So we can see that the files have been uploaded, but they are 48 bytes (size of symbolic links, not target) and _not recognised_ as symbolic links by the OS. If we inspect the contents, the uploaded files contain the first 48 bytes of the source symbolic links' respective targets:

```
ubuntu@ip-172-30-34-124:~$ cat symlinks/symlink_1
000 001 002 003 004 005 006 007 008 009 010 011 

ubuntu@ip-172-30-34-124:~$ cat symlinks/symlink_2
299 298 297 296 295 294 293 292 291 290 289 288 
```
## Cause

[`FileInfo.Size()` appears to be returning the size of the symbolic link (i.e. non regular) file](http://golang.org/pkg/os/#FileInfo):

```
type FileInfo interface {
...
        Size() int64        // length in bytes for regular files; system-dependent for others
```

[But the call to `Open` returns a file descriptor to the target file](http://golang.org/src/os/file_unix.go):

```
#go source
func Open(name string) (file *File, err error) {
    return OpenFile(name, O_RDONLY, 0)
...
func OpenFile(name string, flag int, perm FileMode) (file *File, err error) {
    r, e := syscall.Open(name, flag|syscall.O_CLOEXEC, syscallMode(perm))
...
```
## Possible Solution

My solution is to use the fallback behaviour of making a temporary copy of the file before uploading for non-regular files.

PR Incoming.

**Comment by jsangrador** [comment]
Hi all, any idea when this will be released? I of course can compile it (thanks for making it easy!) but it is better if I can install it with system tools :-)

Kind regards!
