### ISSUE TITLE
Support Atlas artifact as source_ami for aws instances (or for other providers)

### ISSUE THREAD

**Issue by nathanpalmer** [hashicorp/packer#1808]
We're looking at how we can structure our images and one thought we had was to create and use a base image that others build upon. In order to do that I'd like to reference the artifact in a similar way to how we do it in terraform.

```
ami = "${atlas_artifact.web.metadata_full.region-us-east-1}"
```

Syntax I'm sure would be a bit different however the point would be I always want to reference the most recent version of the artifact (and optionally specify a specific version.)

**Comment by jedineeper** [comment]
This, I've a base machine we maintain that I'd like to use as the base for "my application"'s packer templates. Shave CI time off the common packages that are on every box.

**Comment by kelseyfrancis** [comment]
+1

**Comment by djaboxx** [comment]
+1

**Comment by SwampDragons** [comment]
Closing since Atlas is deprecated.
