### ISSUE TITLE
Enable resizing of the root EBS volume

### ISSUE THREAD

**Issue by cove** [hashicorp/packer#188]
Sometimes it's less complex to make the root volume larger on an instance than to attach additional EBS volumes to it. There's a threshold at least. If you need to deploy many instances that just need a little more disk space than the root volume has, then creating additional EBS volumes and attaching them is not ideal.

**Comment by SwampDragons** [comment]
@riponbanik Thanks for reaching out -- this ticket was closed in 2013 and we try not to have zombie tickets for the sake of having more clarity on issue timelines. If you have a question for the community please hit up the email list (packer-tool@googlegroups.com). You're much more likely to get a response.  Thanks!
