### ISSUE TITLE
Cannot follow paths on Windows which include a Junction

### ISSUE THREAD

**Issue by colinbowern** [hashicorp/packer#2093]
If I make a directory junction on Windows

```
mklink /J C:\Projects C:\Users\colinb\Projects
```

Then provide it as a path in my template:

```
"iso_url": "file:///C:/Projects/BaseBoxes/Images/WindowsServer-2012R2.1-amd64.iso",
```

And try to run the build:

```
Failed to parse iso_url 1: readlink C:\Projects: The system cannot find the file specified.    
```

If I change it to the link target, not the link it works.

**Comment by arizvisa** [comment]
Does PR #2906 fix this? In the PR, the call to EvalSymLinks in config.go is skipped, and the path is trusted to os.OpenFile. So as long as os.OpenFile works through the junction, there's nothing that should be stopping it.

**Comment by SwampDragons** [comment]
Closing since we never got a response from the OP.
