### ISSUE TITLE
Packer deleting ~/.docker/config.json is not appropriate for parallel CI builds.

### ISSUE THREAD

**Issue by kyrian-kurtosys** [hashicorp/packer#2297]
Hi,

Please can we get a command line switch/option to _NOT_ delete the credentials file after use, because if you're using packer to build multiple different 'flavours' of image via different CI jobs running as the same user on the same build host (which I imagine many people will seek to do), having to keep manually re-creating the config file (which cannot readily come from SVN I think) defeats the object of the whole CI thing in the first place.

K.

**Comment by kyrian-kurtosys** [comment]
Further, this creates a "lose lose" situation, because if you don't take steps the credentials are removed:

16:57:01 1435074907,,ui,message,    docker (docker-push): Logging out...
16:57:01 1435074907,,ui,message,    docker (docker-push): Remove login credentials for {HOST REDACTED}
16:57:01 1435074907,,ui,say,Build 'docker' finished.

... and if you prevent Packer/Docker from deleting it with permissions this causes an apparent failure, even if the image would otherwise be created and pushed successfully!

17:54:35 1435078361,,ui,message,    docker (docker-push): Logging in...
17:54:35 1435078361,,ui,message,    docker (docker-push): Error saving config file: open {HOMEDIR REDACTED}.docker/config.json: permission denied

Perhaps terminology-wise something like '-accept-existing-credentials' would be a more appropriate name for it.

**Comment by kyrian-kurtosys** [comment]
Having experimented, it appears you can achieve what I want (and stating here for the reference of anyone following in my footsteps, because it's not explicit in the documentation, which may merely need clarifying) with a post-processor stanza something like this:

  "post-processors": [
    [
# docker tag/import/whatever post processor goes here first.
 {
  "type": "docker-push",
  "login_server": "myserver:myport"
}
]

... then packer will invoke docker without explicit login, and docker will use its config.json, looking up the myserver:myport combination from the 'auths { }' block and log in normally without packer deleting the file after it pushes.

K.

**Comment by jhoblitt** [comment]
I think I've run into this as well.

**Comment by SwampDragons** [comment]
I can't reproduce; config.json isn't getting deleted for me.
