### ISSUE TITLE
puppet-masterless is not windows compatible / winrm

### ISSUE THREAD

**Issue by niknaknet** [hashicorp/packer#2566]
I appreciate that the winrm integration is new, and that it takes time to get plugins etc. up to speed.  I figure it is worth highlighting what i have encountered.

using the winrm communicator, the puppet-masterless provisioner does not have a windows version of the mkdir command and therefore fails as -p is not a valid switch on windows.   this exercises code in the createDir function in provisioner/puppet-masterless/provisioner.go.

given that winrm is now present, I figure that it's sensible to consider that as the first-class communicator for windows machines - so potentially a platform label would be sufficient to provide a switch between dialects (using the metaphor very loosely).

for what it's worth, i'm building into AWS

regards,

Nick

**Comment by niknaknet** [comment]
Also worth mentioning that the facter vars within puppet-masterless only follow the linux form, rather than the powershell form - being able to id the platform type & switch would also assist in this actvity.

**Comment by mwhooker** [comment]
see #3850

**Comment by mwhooker** [comment]
I don't have a good solution for this yet, so I'm bumping to next release

**Comment by mwhooker** [comment]
Let's follow terraform's example https://github.com/hashicorp/terraform/blob/master/builtin/provisioners/chef/resource_provisioner.go#L145-L175

**Comment by TraGicCode** [comment]
Just ran into this when wanting to use puppet-masterless on windows.  :(

**Comment by petemounce** [comment]
Same, hitting this now.

**Comment by mwhooker** [comment]
Should be fixed in #5252
