### ISSUE TITLE
AWS region failure

### ISSUE THREAD

**Issue by ariscn** [hashicorp/packer#2567]
New to packer, trying a first build using `amazon-ebs`. I left `region` out of my builder, on the assumption that it would be read from `AWS_REGION` or `~/.aws` just like `access_key`/`secret_key`.

Instead, packer failed with a nasty error:

```
Build 'amazon-ebs' errored: Get http://169.254.169.254/latest/meta-data/placement/availability-zone: dial tcp 169.254.169.254:80: i/o timeout
```

It looks like Packer is trying to query the instance metadata service for the availability zone (and hence region). This fails because I'm running Packer locally and not on AWS.

This is a pretty unexpected result, and a bad first user experience to boot. `region` should be treated the same as `access_key`/`secret_key`.

**Comment by cbednarski** [comment]
Thanks for the report! I looked at this code path earlier this week and you're right, this is definitely not working correctly. As you mentioned I think the fix is for us to validate that the region is set before the run begins since we can't assume you're running in EC2.

As far as I know we do not use `AWS_REGION` in packer. This must be configured using a user variable. Your user variable can read `AWS_REGION` but you have to set it up yourself. I don't think we want to use `AWS_REGION` by default since it does not have the same scope as the credentials you mentioned.

**Comment by todd-dsm** [comment]
Hey guys, not sure if what I'm seeing is the same as this bug or not. I'll let you decide.

I've posted [packer file]. Basically, if `AWS_REGION` is hard-coded in the file it validates and builds fine. 

If you were to pass the region in as a variable, it fails exactly as @ariscn reports; example:
`packer build -var latestImageId=ami-221ea342 -var awsRegion=us-west-2 debian-8.6-ami.json`

The [logs] show `AWS_REGION` does not have a value but `awsRegion` does. 

Not sure if I've done something wrong or if there is an error. 

TAI

[packer file]:https://gist.github.com/todd-dsm/2bef65dbb5e4bf21fc6a8531bc56705a#file-debian-8-6-ami-json
[logs]:https://gist.github.com/todd-dsm/481474604cefe0f71d65ed190d7fa9ed#file-packer-log-L153

**Comment by artburkart** [comment]
@cbednarski - Are you suggesting the snippet that discovers the region from the instance metadata be removed from the code entirely? Or would it be better to return an error message stating no region was provided and none could be discovered?

Here's the snippet in question:

```
// Region returns the aws.Region object for access to AWS services, requesting
// the region from the instance metadata if possible.
func (c *AccessConfig) Region() (string, error) {
	if c.RawRegion != "" {
		if !c.SkipValidation {
			if valid := ValidateRegion(c.RawRegion); valid == false {
				return "", fmt.Errorf("Not a valid region: %s", c.RawRegion)
			}
		}
		return c.RawRegion, nil
	}

	md, err := GetInstanceMetaData("placement/availability-zone")
	if err != nil {
		return "", err
	}

	region := strings.TrimRightFunc(string(md), unicode.IsLetter)
	return region, nil
}
```

Maybe changing the bit to look something like this could prove more helpful to newer users?

```
	md, err := GetInstanceMetaData("placement/availability-zone")
	if err != nil {
		return "", "No valid region found."
	}
```

**Comment by SwampDragons** [comment]
Can anyone verify that #4613 fixes this issue as well?

**Comment by SwampDragons** [comment]
Just tested myself; this was indeed fixed some time ago.
