### ISSUE TITLE
Ansible Provisioner 

### ISSUE THREAD

**Issue by rach** [hashicorp/packer#275]
For an other of my project, I will need to investigate of creating a Packer provisioner for ansible.

I don't know if you are familiar with Ansible but it doesn't require any bootstrap and does configuration mainly via ssh or local ( or what ever plugin http://www.ansibleworks.com/docs/api.html#connection-type-plugins) 

I started to think to different approach: 
- Copying the playbook to the remote , install ansible and run it in local mode 

Pro :  It's easy
Cons : It requires to install Ansible on the remote which is a type of bootstrapping and a bit against the original philosophy 
- Reusing the SSH connection to locally run ansible-playbook on the remote 

Pro : respect common use and ansible design 
Cons : I checked the code of the communicator in packer but I don't have much clue on I could get information on the host and keys via the comm package.
- Creating a ansible connection type plugin  to collect the command to run on the host via Packer interface ..

Pro : I know Python but not much Go ;)
Cons : require to install on plugin

@mitchellh  Do you have some advices on which approach should be taken ? or suggest an other one. 

If you could give some guidance/tips if you have an idea how the Ansible provisioner should work then I'm happy to look at implementing it

**Comment by saulshanabrook** [comment]
@rach Anyone making progress on your third suggested way?

> Creating a ansible connection type plugin to collect the command to run on the host via Packer interface ..

This seems the cleanest because it doesn't require Ansible on the remote host.

**Comment by rach** [comment]
Hi,

I haven't been using packer lately so I didn't investigate the matter.


On Sat, May 9, 2015 at 6:12 PM, Saul Shanabrook <notifications@github.com>
wrote:

> @rach <https://github.com/rach> Anyone making progress on your third
> suggested way?
>
> Creating a ansible connection type plugin to collect the command to run on
> the host via Packer interface ..
>
> This seems the cleanest because it doesn't require Ansible on the remote
> host.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mitchellh/packer/issues/275#issuecomment-100518593>.
>



-- 
Rach Belaid
Flat 9 240B Amhurst Road, London N16 7UL
Phone : +44 75 008 660 84
