### ISSUE TITLE
Add feature to allow mounting extra ISO to launched VM. [its not in v0.3.1 afaik]

### ISSUE THREAD

**Issue by rluiten** [hashicorp/packer#287]
Specifically I want this so that I can mount 
"guest_additions_path": "VBoxGuestAdditions_{{.Version}}.iso",

As well as my windows install ISO to my VM.
This means my install script inside the VM can just access the ISO content in side the VM,

Though I think mounting extra ISO's might be generally a useful thing.

I ain windows 7 64 bit, creating a windows 8 64bit pro vm for virtualbox.

**Comment by svanschalkwyk** [comment]
Hi
How would one do this in VMWare and the other builders?
Thanks

**Comment by svanschalkwyk** [comment]
Got it. Copy from a vmx file.
