### ISSUE TITLE
vSphere post-processor mark as template

### ISSUE THREAD

**Issue by jcsmith** [hashicorp/packer#3035]
Is it possible to have the vSphere provisioner automatically mark the uploaded VM as a template?

**Comment by rickard-von-essen** [comment]
No currently it is not, but it should be very useful to have as an option. Or to allow adding arbitrary "extra args" to ```ovftool```.

**Comment by jcsmith** [comment]
@rickard-von-essen Thanks for the information - I didn't think the option existed but wanted to make sure I was not missing anything.  I second your comment that it would be very useful.  Right now it's the only part of my template building process that isn't completely automated by packer.  I looked at trying to add support myself but I'm not fluent enough in GO and the dependencies for contributing to packer looked a bit daunting.

**Comment by Sharpie** [comment]
Looks like there are other vsphere post-processors that accomplish this by using the vmware/govmomi library:

https://github.com/Banno/packer-post-processor-vsphere-ova/blob/28a8807a72570775f1693284e8bf8e75b50b1fe0/post-processor.go#L498

**Comment by SwampDragons** [comment]
There's now a vsphere-template post-processor that should accomplish this; closing.
