### ISSUE TITLE
Docker builder hangs when using Ansible provisioner in Docker in Docker

### ISSUE THREAD

**Issue by frodopwns** [hashicorp/packer#3057]
I am running Jenkins in a Ubuntu 14.04 Docker Container.  
Tried with docker 1.7.1 and 1.9.1.

The jenkins image has these volumes mounted in to allow for docker-in-docker:

-v /usr/bin/docker:/usr/bin/docker 
-v /var/run/docker.sock:/var/run/docker.sock

Inside this container I run a packer build with a docker builder and an ansible provisioner.  This build works fine when I run it on a normal host running docker.

When run inside a docker-based jenkins image it hangs at:

```
==> docker: Starting docker container...
    docker: Run command: docker run -v /root/.ssh:/root/.ssh -v /etc/ansible:/etc/ansible -v /tmp/packer-docker574433279:/packer-files -d -i -t some-user/some-image /bin/bash
    docker: Container ID: 12712e6e1d7a78fef387130ff5f1f849f98333ce6eeac31e292725c5006b6355
==> docker: Provisioning with Ansible...
    docker: Creating Ansible staging directory...
    docker: Creating directory: /tmp/packer-provisioner-ansible-local
```

This will hang forever.

Is there a known issue with running the docker builder with ansible provisioner in a docker-in-docker environment?  If so what can we do about it? Jenkins is being deployed via docker more and more often so things like packer which often get triggered by jenkins will need to run in containers.

**Comment by cbednarski** [comment]
Thanks for the report.

> Is there a known issue with running the docker builder with ansible provisioner in a docker-in-docker environment?

I'm not sure about this specific arrangement. However, in packer `0.8.6` and earlier the only configuration I _know_ works for building docker containers is running packer on linux and building on the same OS.

There is a bug fix in master that allows you to run packer on Mac / Windows / Linux and build on a remote VM. The bug fix involved changing how packer uploads provisioning scripts to the remote docker service, so this may also fix running a docker-in-docker scenario as well.

The other issue you may run into running docker-client-in-docker is privileged mode for docker. By default, a process running in a docker container cannot create new containers on the host. For this, see the [docker privileged mode](https://docs.docker.com/engine/reference/commandline/run/#full-container-capabilities-privileged). If you are nesting docker (docker-service-in-docker) you are in for some other weirdness. The [latter scenario is possibly more recently](https://blog.docker.com/2013/09/docker-can-now-run-within-docker/) but packer's implementation predates and has not been tested with this type of configuration.

**Comment by frodopwns** [comment]
Thanks for the response! I will try out master and report back here.

**Comment by frodopwns** [comment]
So I compiled the 0.8.7 binary and tried again...same outcome.  I them used the run_command to test running in privileged mode. Neither changed the outcome. Running with PACKER_LOG=1 now but I have yet to see this thing timeout.

**Comment by frodopwns** [comment]
I left that running last night and it never timed out.

For clarification I am running 2 different environments testing this:
Local: 1 Ubuntu VM running docker -> running a Jenkins container -> running packer docker builder
AWS: 1 Ubuntu instnace running docker -> running jenkins -> running packer

This seems to be failing after the Ansible provisioner starts so I can't be too sure if this is docker related or ansible related.

A note on privileged mode: It is generally considered best practice now not to use privileged mode.  Instead we have been mounting in the docker binaries and sock instead.
