### ISSUE TITLE
Packer push don't care about CRLF

### ISSUE THREAD

**Issue by dpalomar** [hashicorp/packer#3088]
**Packer version: 0.8.6.**
When you push a packer template.json to atlas service from windows and the template (or related files) have CRLF line ending, packer validate fine, but atlas service does not work and does not report any issue, simply dies but not notification is sent, or error is shown on the GUI.

Changing windows end lines by linux end lines, the atlas build service works fine, but packer always validate.

I think that the validate operation of packer command line could validate this issue as well, or the atlas service should notificate about the error. Of course, supporting CRLF could be fine.

**Comment by cbednarski** [comment]
I think the simple fix for this is to convert CRLF to LF before POSTing it. Going to sanity check with the Atlas team.

**Comment by cbednarski** [comment]
@dpalomar So after digging into this a bit the template.json should not matter if it has CRLF or LF or anything else as a line separator.

> When you push a packer template.json to atlas service from windows and the template **(or related files)** 

Other files in other formats may not have the same tolerance. For example, shell scripts, kickstart files, powershell scripts, or other files that contain strings may be sensitive to the type of line endings you use. In this case there is not a way for me to correctly transform these so you will need to make sure these are correct when you push them.

If you can provide more specific information about which files are sensitive to this we can assess whether this is something we can fix in packer or Atlas or whether packer / Atlas simply need correct inputs to work.

**Comment by dpalomar** [comment]
I see, thanks @cbednarski.
After changing  manually CRLF by LF in all files, works fine. But in an automated process is difficult to do. So if you works with several (people, platforms) and use SCM, you need to configure variables to manage end lines depending of platform to build, or use a .gitattributes file per repo in case of git. Maybe a lot of steps in a chain.

I propose is that at least the atlas service not die without any notification. Of course team is responsible of take care about this issue but without information is not easy. 
Regards.

**Comment by cbednarski** [comment]
>  if you works with several (people, platforms) and use SCM, you need to configure variables to manage end lines depending of platform to build, or use a .gitattributes file per repo in case of git. Maybe a lot of steps in a chain.

Yes, I've experienced this frustration myself. Two things that may help: Some SCMs have a binary flag feature that you can set on a file so the SCM will not transform the file (even if it is a text file) when committing it. Another option is to use a Makefile or pre-commit / post-checkout hook to make sure the line endings are correct.

> I propose is that at least the atlas service not die without any notification.

I agree this is the best thing for us to do. Can you provide a bit more information about which types of files caused the problem? I.e. can you give me an example of your packer template and/or link to your Atlas build so I can investigate further? Thanks!

**Comment by dpalomar** [comment]
Project was build with a veewee template and using veewee-to-packer tool on windows 10. Here is the repository: https://github.com/dpalomar/packer-uc3mTiw
I don't know what files caused the problem, simply I changed end lines in all files and all worked fine, after much trial.
Atltas logs reports another trouble actually, it is concern with https://github.com/mitchellh/packer/issues/3089

**Comment by SwampDragons** [comment]
Closing since Atlas is deprecated.
