### ISSUE TITLE
instance.uploadCmdData struct should have a .Token field for AMIs

### ISSUE THREAD

**Issue by dialtone** [hashicorp/packer#3114]
As per subject. When you assume roles and you get to the point of needing to upload the AMI to S3 just using access key and secret key won't work unless you provide the `-t {{.Token}}` cmd line argument to `ec2-bundle-upload`.

**Comment by naunga** [comment]
I'm running into this as well. 

What are you are doing to work around this?

**Comment by mwhooker** [comment]
@naunga @dialtone can either of you test the patch in #5288?

That adds a `{{.Token}}` variable to the template

**Comment by naunga** [comment]
@mwhooker I'll certainly give it a try. Might not be able to test until this weekend / early next week, but this definitely will make life easier for me if it works.

**Comment by naunga** [comment]
Finally got around to testing this: it worked perfectly for me.
