### ISSUE TITLE
[vmware] Unable to cleanup

### ISSUE THREAD

**Issue by dantran** [hashicorp/packer#3165]
try with packer 0.9 snapshot, at the end Packer fails the following message

```
2016/02/08 17:08:19 packer: 2016/02/08 17:08:19 starting remote command: vim-cmd vmsvc/unregister 47
2016/02/08 17:08:19 packer: 2016/02/08 17:08:19 remote command exited with '0': vim-cmd vmsvc/unregister 47
2016/02/08 17:08:19 ui error: Build 'vmware-iso' errored: lstat myvm-name: no such file or directory
```

Looks like packer needs to use the full path /vmfs/volumes/storage-folder/myvm-name

**Comment by cbednarski** [comment]
Thanks for the report!

**Comment by dantran** [comment]
@cbednarski  please you advice which part of the code I need to look for?  I would like to get this fixed by providing PR

**Comment by rickard-von-essen** [comment]
@dantran I would start with reviewing the code from [step_shutdown](https://github.com/mitchellh/packer/blob/master/builder/vmware/iso/builder.go#L284) and all following steps, and the [clean of the step_run]( https://github.com/mitchellh/packer/blob/master/builder/vmware/common/step_run.go#L85). Try to build a hypothesis of what's causing this.

Another hint can be to use the current master which includes timestamps in the debug logging (```PACKER_LOG=1 packer build ...```) and find if there is some timing difference between a run where the VM is properly cleaned up and one where it is not.

**Comment by dave2** [comment]
Is this related to #3050 .. Does applying the changes to when to stat the local filesystem cause this error to disappear? Are you using ```format: "ova"``` in your template?

**Comment by dantran** [comment]
I dont set any format in my template.  my packer build just build VM image from ISO file

**Comment by dave2** [comment]
Does it not error out if you provide a format? Just trying to work out if the PR I linked above is the bug you are tripping over.

**Comment by dantran** [comment]
Yes, it looks very close to the error I am seeing, let me try your provided fix at my 0.9 local build

**Comment by dantran** [comment]
@dave2 I applied your change locally, but the build fails due to test failure

**Comment by dave2** [comment]
Ah, sadly that's not my PR. I will look at reworking it for current tree in the next few days.

**Comment by SwampDragons** [comment]
Is this still an issue?  We've made a _lot_ of changes to the vmware builder since v 0.9.

**Comment by dantran** [comment]
Please close this issue. I don’t see this issue any more
