### ISSUE TITLE
Did not receive identification string from

### ISSUE THREAD

**Issue by moshe0076** [hashicorp/packer#3200]
Hi,

SSH using packer null to Ubuntu 14.04 server gives **from time to time** the following error in auth.log:

``` syslog
sshd[32525]: Did not receive identification string from <IP ADDRESS>
```

Which leads to:

``` syslog
Blocking <IP ADDRESS>:4 for >630secs: 40 danger in 4 attacks over 1078 seconds (all: 40d in 1 abuses over 1078s).
```

The builder setup with:

```
builders": [
    {
      "type": "null",
      "ssh_host": "{{ user `SERVER_IP_ADDRESS` }}",
      "ssh_username": "{{ user `SSH_USERNAME` }}",
      "ssh_private_key_file": "{{ user `SSH_PRIVATE_KEY_FILE` }}",
      "ssh_pty": true
    }
  ]
```

 Packer version-0.8.6

**Comment by rickard-von-essen** [comment]
Could you gist your /etc/ssh/sshd_config?

**Comment by rickard-von-essen** [comment]
Do you have anything like failtoban installed?

**Comment by moshe0076** [comment]
Hi,

 

It’s a standard Ubuntu 14.04 server running on Google Compute cloud.:

# Package generated configuration file

# See the sshd_config(5) manpage for details

 

# What ports, IPs and protocols we listen for

Port 22

# Use these options to restrict which interfaces/protocols sshd will bind to

#ListenAddress ::

#ListenAddress 0.0.0.0

Protocol 2

# HostKeys for protocol version 2

HostKey /etc/ssh/ssh_host_rsa_key

HostKey /etc/ssh/ssh_host_dsa_key

HostKey /etc/ssh/ssh_host_ecdsa_key

HostKey /etc/ssh/ssh_host_ed25519_key

#Privilege Separation is turned on for security

UsePrivilegeSeparation yes

 

# Lifetime and size of ephemeral version 1 server key

KeyRegenerationInterval 3600

ServerKeyBits 1024

 

# Logging

SyslogFacility AUTH

LogLevel INFO

 

# Authentication:

LoginGraceTime 120

PermitRootLogin without-password

StrictModes yes

 

RSAAuthentication yes

PubkeyAuthentication yes

#AuthorizedKeysFile     %h/.ssh/authorized_keys

 

# Don't read the user's ~/.rhosts and ~/.shosts files

IgnoreRhosts yes

# For this to work you will also need host keys in /etc/ssh_known_hosts

RhostsRSAAuthentication no

# similar for protocol version 2

HostbasedAuthentication no

# Uncomment if you don't trust ~/.ssh/known_hosts for RhostsRSAAuthentication

#IgnoreUserKnownHosts yes

 

# To enable empty passwords, change to yes (NOT RECOMMENDED)

PermitEmptyPasswords no

 

# Change to yes to enable challenge-response passwords (beware issues with

# some PAM modules and threads)

ChallengeResponseAuthentication no

 

# Change to no to disable tunnelled clear text passwords

PasswordAuthentication no

 

# Kerberos options

#KerberosAuthentication no

#KerberosGetAFSToken no

#KerberosOrLocalPasswd yes

#KerberosTicketCleanup yes

 

# GSSAPI options

#GSSAPIAuthentication no

#GSSAPICleanupCredentials yes

 

X11Forwarding yes

X11DisplayOffset 10

PrintMotd no

PrintLastLog yes

TCPKeepAlive yes

#UseLogin no

 

#MaxStartups 10:30:60

#Banner /etc/issue.net

 

# Allow client to pass locale environment variables

AcceptEnv LANG LC_*

 

Subsystem sftp /usr/lib/openssh/sftp-server

 

# Set this to 'yes' to enable PAM authentication, account processing,

# and session processing. If this is enabled, PAM authentication will

# be allowed through the ChallengeResponseAuthentication and

# PasswordAuthentication.  Depending on your PAM configuration,

# PAM authentication via ChallengeResponseAuthentication may bypass

# the setting of "PermitRootLogin without-password".

# If you just want the PAM account and session checks to run without

# PAM authentication, then enable this but set PasswordAuthentication

# and ChallengeResponseAuthentication to 'no'.

UsePAM yes

#

# Google Compute Engine times out connections after 10 minutes of inactivity.

# Keep alive ssh connections by sending a packet every 2 minutes.

ClientAliveInterval 120

 

# Prevent reverse DNS lookups.

UseDNS no

**Comment by moshe0076** [comment]
https://gist.github.com/moshe0076/10bd2b689c34f12e672a

**Comment by moshe0076** [comment]
sshguard is the one doing the blocking at the end.

**Comment by rickard-von-essen** [comment]
Could you just double check that the source IP of the connection attempt is really the machine running Packer.

**Comment by moshe0076** [comment]
Hi,

The source is an EC2 instance running the Packer, it connects to the Google compute instance via SSH.
I have checked the EIP address of the EC2 instance  and the IP address in the auth.log on the Google instance and they are identical (I also see the timeout on the EC2 instance as sshguard  is blocking the connection). This will not happen all the time, but from time to time.

**Comment by bpetit** [comment]
Hi,

A bit old, but I have to ask: is this confirmed ? What is the status ?
I think I'm experiencing the same symptom.

**Comment by rickard-von-essen** [comment]
IMHO this have not been confirmed. Can you please provide complete information to reproduce this and  we can have a look.

**Comment by rickard-von-essen** [comment]
Closing this and I'll reopen if we have more information.
