### ISSUE TITLE
VirtualBox test TestBuilderAcc_basic is failing [known issue]

### ISSUE THREAD

**Issue by cbednarski** [hashicorp/packer#3223]
Failing test in packer 0.9.0-rc2 acceptance tests. This will be filed as a known issue and not fixed for 0.9.

```
PACKER_ACC=1 go test -v ./builder/virtualbox/iso/... -run TestBuilderAcc_basic
```

This test fails with `Timeout waiting for SSH.` However, this never would have succeeded. I suspect that the `test` builder has been infected with a communicator change intended for ssh / winrm, causing the test to fail.

I have run a complete build with virtualbox using one of my existing configs, and everything works there from `packer build` to `vagrant up` so _I think_ this issue only affects the tests.

I have not bisected this one yet since bisect is projected to take around 30 minutes.

**Comment by mwhooker** [comment]
looks like boot_command is never entered
