### ISSUE TITLE
OpenStack: support shutdown_command when Stop is not supported

### ISSUE THREAD

**Issue by rickard-von-essen** [hashicorp/packer#3259]
If the OpenStack cluster don't support the `os-server-start-stop` extension we just skip shutdown. It would be better if we supported `shutdown_command` to issue a command for shutting down the OS. 

See
https://github.com/mitchellh/packer/blob/master/builder/openstack/step_stop_server.go#L21

Related to #2773

**Comment by rickard-von-essen** [comment]
@melon-babak FYI

**Comment by melon-babak** [comment]
Thanks Richard. What's the best short term solution?

**Comment by rickard-von-essen** [comment]
I'm not sure this is an issue anymore. Any news if this is still valid?

**Comment by trodemaster** [comment]
I still have a need for optionally using a shutdown_command to run sysprep. But If I understand this specific issue is around older openstack not supporting shutdown api call. I don't have any issues with that situation.

**Comment by rickard-von-essen** [comment]
Closing this since extensions in OpenStack have been deprecated along time ago.
