### ISSUE TITLE
Rackspace stop/start extension (Grizzly vs Liberty)

### ISSUE THREAD

**Issue by ghost** [hashicorp/packer#3262]
There's a few inter-connected issues involved here not sure what's the best way to express it but I'll have a go.

Basically I want to use packer with the OpenStack builder to build server images for Rackspace.

But as things are now it seems like the start/stop extension is not supported (or not being detected) so packer skips the server shutdown process, resulting in corrupt images being saved.

See issues: #3259 #2773 #1462

I opened a ticket with Rackspace asking them about the start/stop extension.

This is what they said:

> The os-server-start-stop extension is actually an older used with the 'Grizzly' version, the newer 'Liberty' supports stop/start as part of nova. The original use of this extension was to force the host (KVM specifically) to wait for the OS to shutdown, this was never an issue on Xen (what we use) but the stop/start/reboot functions through our API have this functionality.
> 
> Packer should update to support new the standard nova-api for openstack in General or Rackspace specifically.
> 
> \Thanks and Regards
> 
> [redacted]
> Cloud Infrastructure Support

Packer version: 0.9
Host platform: Linux 64-bit

What can we do about this or where do I go from here?

**Comment by rickard-von-essen** [comment]
Ok, this is good, since Grizzly was EOL a long time ago we can probably just skipp checking if the extension is available and just assume stop is supported.

**Comment by melon-babak** [comment]
@rickard-von-essen is that as simple as just not doing the check on https://github.com/mitchellh/packer/blob/39d6eda3708dc677544f0afe1b5e35911152bd86/builder/openstack/step_stop_server.go#L21?

If someone provides some guidance on what the patch would look like I may be able to send a pull request.

**Comment by melon-babak** [comment]
Hmm so I built a version that just blindly skips the check. This is what happened:

```
openstack output will be in this color.
==> openstack: Discovering enabled extensions...
==> openstack: Loading flavor: 2
    openstack: Verified flavor. ID: 2
==> openstack: Launching server...
    openstack: Server ID: [redacted]
==> openstack: Waiting for server to become ready...
==> openstack: Waiting for SSH to become available...
==> openstack: Connected to SSH!
==> openstack: Provisioning with shell script: provision.sh
    openstack: STARTING TO PROVISION
==> openstack: Provisioning with shell script: /tmp/packer-shell194342431
==> openstack: Uploading test_upload_file.txt => /home/ubuntu/test_upload_file.txt
==> openstack: Stopping server: [redacted] ...
==> openstack: Terminating the source server: [redacted] ...
Build 'openstack' errored: Error stopping server: Expected HTTP response code [201 202] when accessing [POST https://[redacted]], but got 400 instead
{"badRequest": {"message": "There is no such action: os-stop", "code": 400}}

==> Some builds didn't complete successfully and had errors:
--> openstack: Error stopping server: Expected HTTP response code [201 202] when accessing [POST https://[redacted]], but got 400 instead
{"badRequest": {"message": "There is no such action: os-stop", "code": 400}}
==> Builds finished but no artifacts were created.
```

**Comment by rickard-von-essen** [comment]
@melon-babak ohh that was bad. I just registered a account at Rackspace and will do some testing but I currently have very little time to spend on this so it may take some days before I get around to do it.

**Comment by melon-babak** [comment]
Here's some further information from Rackspace:

> So the extension has been deprecated, and the actions built into Nova now, however,
> with Rackspace it seems to be an Admin-only action,
> which, I believe is a bug and this should be available to customers,
> as its available in the SDKs, as an example
> 
> PHP: https://github.com/rackspace/php-opencloud/blob/working/lib/OpenCloud/Compute/Resource/Server.php#L847-L873
> GO : https://github.com/rackspace/gophercloud/blob/d783aa72ca0531c6d07f76c84fc73083a5e8af7f/openstack/compute/v2/extensions/startstop/requests.go
> 
> However, with OpenStack, and Xen and do not actually need to stop the server before taking an image, as the imaging is based on the disk, and a snapshot is taken, and that is used to take the image.
> 
> I have placed a private comment with a link to the internal bug report.

**Comment by rickard-von-essen** [comment]
@melon-babak any feedback from Rackspace?

**Comment by melon-babak** [comment]
@rickard-von-essen yeah there was some continued discussion but overall things seem a bit confusing.

I'll paste some of them here:

> I have confirmed that this is the correct behaviour for glance. A snapshot is started, at the point the user initiates the image, and any changes that occur in the filesystem post the initiation of the snapshot will not be included in the image.
> 
> If you run a highly transactional system I would recommend considering a slave. That way you can take the master down for imaging, and slave down for imaging sequentially, without losing the data between the two.  I tried to replicate the issue of the file being there, but only being empty, but I was unable to do that, only show that any changes after the image is started, are not included in the snapshot,
> 
> I hope this helps clarify, and gives you a potential alternative.

That didn't make a lot of sense to me. So I replied with more detailed information and mentioned all I have to do to make things work is to do a `sync && shutdown -h now` as the last provision step.

Reply:

> I would speak to Packer about this, as its clearly doing this in memory, which wont be used when creating an image. The fact 'sync' works, and the process Packer uses is to shutdown the server (which syncs by default) and the image, almost confirms this to the true. See is Packer can replace shutdown with an OS sync, then take an image, as this would be better option.

I can provide a complete set of files to replicate the problem (all you will need is a Rackspace account) let me know if that's useful.

**Comment by rickard-von-essen** [comment]
Rackspace are focusing on the wrong point. The question is "how should you stop an instance in Rackspace (as non-admin)".

**Comment by rickard-von-essen** [comment]
Closing this since this have become stale.
