### ISSUE TITLE
Delegate AWS region error checking to AWS Go SDK

### ISSUE THREAD

**Issue by jcmcken** [hashicorp/packer#3303]
The error checking that occurs on a user-passed AWS region should be removed and delegated to the AWS Go SDK to future proof `packer` for the introduction of new regions/endpoints. The Go SDK has a much more comprehensive description of which regions and endpoints are valid, and since Amazon supports it, it's more likely to more quickly match their service offerings as those offerings change.

**Comment by cbednarski** [comment]
This is slightly more complicated now that we vendor dependencies. If we maintain the list we can change it without having to update to a newer version of the AWS library. If we use AWS's version then we have to update the entire AWS SDK tree to add a new region, which potentially breaks unrelated things. Do you have any thoughts about this?

**Comment by jcmcken** [comment]
Hmm, that is a conundrum. Well, ideally, I'd like to just be able to override the builtin endpoints via configuration when necessary. That way I don't have to wait for a new release or re-build ``packer`` myself. 

Currently, we have to maintain a forked ``packer`` with custom patches to enable alternate endpoints, and it's a bit of a maintenance headache (not by itself necessarily, just in aggregation with other forked things we have to maintain -- something that's nice to minimize where possible!). If the vendored SDK supported that type of configuration, I suppose removing the region name checking would solve my issue. Unfortunately the SDK doesn't currently support that (although there are a number of issues filed against the SDK to fix that problem).

I suppose there's nothing really that can be done about this until the SDK is also configurable in this way (and ``packer`` pulls in those changes).

**Comment by sdavids13** [comment]
It doesn't look like the AWS Go SDK has regions hard-coded, so when new regions come online [imminently](https://aws.amazon.com/about-aws/global-infrastructure/) you won't need to pull in the new SDK. @jcmcken There appears to be a standard that Amazon is now using for their service offering endpoints thus no need to explicitly specify each endpoint. Anyways, if this were to make it in my life a lot easier as well.

**Comment by cbednarski** [comment]
@sdavids13 Ah that's interesting. I will need to see whether we're using the regions only for validation or whether we generate any URLs or configs using those identifiers. If it's only for validation we can probably remove them.

**Comment by sdavids13** [comment]
Looks like the only thing that was changed to support ap-northeast-2 was the `ValidateRegion` method: https://github.com/mitchellh/packer/pull/3056/files. Hence, I think that supports the case that it is only used for validation purposes.

**Comment by lorengordon** [comment]
+1. This would be a much better solution to the problem of new regions, rather than telling people to use `skip_region_validation` now. Simply do not validate the region in the first place. If the request errors, catch it and translate/pass the error message.

**Comment by SwampDragons** [comment]
This was (hopefully) fixed in v1.3.3 -- we now do not check regions during Validate, but we do validate the region at build time using an API call to make sure we're always up to date.
