### ISSUE TITLE
GCE (windows) vms aren't destroyed when packer fails

### ISSUE THREAD

**Issue by JorritSalverda** [hashicorp/packer#3380]
When packer fails the used vm on GCE isn't cleaned up. For example in case of an error like described in #3378. This costs a lot of money for running those hosts longer than needed and time to manually clean up old packer vms.
- Packer Version: 0.10.0
- Host platform: debian jessie
- Debug log output: https://gist.github.com/JorritSalverda/5f0fa8e942bf0b844f7c

**Comment by cbednarski** [comment]
Thanks for the report!
