### ISSUE TITLE
default value of format in vmware-iso build is not handled properly

### ISSUE THREAD

**Issue by godfryd** [hashicorp/packer#3385]
If the format is not set in builder settings then nothing happens due to wrong implementation of Run function in `builder/vmware/iso/step_export.go` file, line 38:

``` go
if c.RemoteType != "esx5" || s.Format == "" {
    return multistep.ActionContinue
}
```

If RemoteType is "esx5" and Format is not set then nothign happens i.e. image is not exported. But Format default value is "ovf" according to documentation image should be exported. 
The code above should look like:

``` go
if c.RemoteType != "esx5" {
    return multistep.ActionContinue
}
```

**Comment by kkdevops** [comment]
any advances?
