### ISSUE TITLE
AMI Builder: force_deregister and ami_regions incompatibility

### ISSUE THREAD

**Issue by etipton** [hashicorp/packer#3399]
It seems that the `force_deregister` option doesn't work with the `ami_regions` option when copying the original AMI to other regions.

@catsby can you confirm? Tagging you because: https://github.com/mitchellh/packer/issues/1873

If it's not a simple oversight (and a deeper issue), then I'll follow the guidelines for submitting an issue (log output, etc, etc).

Thanks!

**Comment by lorengordon** [comment]
I'm running into this as well. `force_deregister` does not remove AMIs with the same AMI name from regions specified in the `ami_regions` parameter.

I went ahead and created a [gist](https://gist.github.com/lorengordon/8d55cdf951fbcc711987717506288ec2) with the minimal template and packer build logs from two runs. First run creates the AMIs, second run show the AMI being deregistered in `aws_region` but not in `ami_regions`.

**Comment by p53** [comment]
i have similar issue, when i have force_deregister: true and there is also ami_regions, it doesn't delete AMI in any region

**Comment by thomasbiddle** [comment]
Running into this as well - it *will* deregister the AMI in the original region; however it will not deregister any copies going to other regions via `ami_regions` parameter.

**Comment by y0y0z** [comment]
the issue still exist.
any idea whether is it going to be addressed?

**Comment by SwampDragons** [comment]
Hey all, thanks for commenting and keeping this alive.  Given that we have a large number of people seeing this issue, I'd like to take a look.  Can someone please provide me with the following information:

- Packer version from `packer version`
- Host platform
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a gist https://gist.github.com
- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your gist https://gist.github.com

Thanks!!

**Comment by aberrios85** [comment]
@SwampDragons Does this help?

* Packer v1.0.3 from docker.io/hashicorp/packer:latest
* docker.io/hashicorp/packer:latest
* [packer log output](https://gist.github.com/aberrios85/350aaece3ede81db355298d667b03b64) Sorry I forgot to run with PACKER_NO_COLOR
* [template.json](https://gist.github.com/aberrios85/0e939ddc71398e9b9e16aade793f8b40)
* `docker run --env-file env.list -i -t -v (pwd):/mnt/ hashicorp/packer build /mnt/template.json`
* [docker env.list](https://gist.github.com/aberrios85/80d65e5e0f85dce87417b6e108d20d15)

## Sequence
* Builds source ami in eu-west-2
* Deregisters current named ami in eu-west-2 and creates a new ami
* Copies new ami to eu-west-1 
* **Does not deregister same named ami in eu-west-1**

**Comment by SwampDragons** [comment]
Thanks, that helps a lot.  I have replicated using your scripts :)

**Comment by SwampDragons** [comment]
If any of you have time to test PR 5250 before I come back to it tomorrow, I'd appreciate the external validation that you aren't seeing unexpected behavior from it.
