### ISSUE TITLE
Question: how to set box description through atlas post-processor

### ISSUE THREAD

**Issue by mapuri** [hashicorp/packer#3401]
We are using Packer to build Vagrant boxes and release them to Atlas using the corresponding post-processor. We have automated the Packer build in our CI. And we would like a way to set the description of the released box as part of the atlas post-processor. 

The template below is what I have where I set the `description_markdown` metadata field. However, I don't see it being reflected in the box description on Atlas. Is this the correct way to do it? If not, I would appreciate any pointers to set the box description as part of packer build.

```
...
...
  "post-processors": [[
    {
      "keep_input_artifact": false,
      "output": "box/centos72.{{ .Provider }}.box",
      "type": "vagrant"
    },
    {
      "type": "atlas",
      "token": "{{ user `atlas_token` }}",
      "artifact": "contiv/centos72",
      "artifact_type": "vagrant.box",
      "metadata": {
        "provider": "virtualbox",
        "version": "{{ user `version` }}",
        "description_markdown": "[changelog]({{ user `changelog` }})"
      },
    },
...
...
```

I am using packer version 0.8.6, do I need to move to a later version?

**Comment by ShaneSaww** [comment]
@mapuri I'm not sure about how to set the markdown description, but you can set text version of the description with the metadata flag of `description`
It should look something like
```
"metadata": {
  "description": "({{ user `changelog` }})"
}
```

**Comment by mapuri** [comment]
thanks @ShaneSaww 

let me try using the `description` field instead and also update my packer version to `0.10.0`. I will get back if it works.

**Comment by mapuri** [comment]
@ShaneSaww 

I am able to verify that specifying the `description` field correctly updates the text description for artifact in atlas. I tried this with packer 0.10.0. Thanks for the pointer!

We can close this issue and update documentation as you suggested.

**Comment by ShaneSaww** [comment]
Thanks @mapuri I just created a PR with the updated docs! 
😀

**Comment by SwampDragons** [comment]
Closing since Atlas is deprecated.
