### ISSUE TITLE
Wrong Host-IP from host_ip_vmnetnatconf.go

### ISSUE THREAD

**Issue by StuebiSoft** [hashicorp/packer#3414]
- Packer Version=0.10.0 x64
- Host platform=Windows 7 x64

I have change the IP-Network for VMware Workstation NAT to 192.168.199.128/26 so the Host-IP for the machine is 192.168.199.129. But packer try to download the ks file in teh VM from 192.168.199.1. So the the build fail.

In the code of host_ip_vmnetnatconf.go that you find the Host IP by find the line "ip = " in vmnetnat.conf an change the last byte to 1.
I think the better way ist to read the vmnetdhcp.conf and find the "fixed-address" for the NAT addapter.

Log: https://gist.github.com/StuebiSoft/6656c2f2b3d392861ba05876df12da72
vmnetnat.conf, vmnetdhcp.conf: https://gist.github.com/StuebiSoft/eb5e7268a4725b1ff92246e7d153ec00

**Comment by arizvisa** [comment]
probably fixed by pr #3417?

**Comment by arizvisa** [comment]
Is this fixed? Can this be closed?

**Comment by SwampDragons** [comment]
I'll close and if the original poster is still experiencing the issue they can request that I reopen :)
