### ISSUE TITLE
VMware Fusion VM startup failure during build

### ISSUE THREAD

**Issue by NathanDotTo** [hashicorp/packer#3424]
Hi

When I build a VMware Fusion VM with Packer, and the build fails, or I Ctrl-C it, and then try to build a VM with the same name again, it fails. I can provoke this as show in the logs below. The symptom is the VNC connection failure, but the cause is that the VM simply was not created at all.

The solution is to change the "vm_name" in the json configuration. For example, if start a process to build a VM called "packer-ubuntu-14.04-amd64", and I Ctrl-C that, and then I try to build the same VM again, the build fails.

If I change the name to "packer-ubuntu-14.04-amd64-test", the build will succeed.

Note that I can't find a way to delete the previously built VMs from Fusion as they do not appear in the list of Virtual Machines in the UI. The `vmrun` command, which is a possible CLI, option requires a .vmx file as argument, but that has been deleted by the build cleanup stages.
- Packer Version - 0.10.0
- Host platform OSX 10.11.4
- Debug log output from `PACKER_LOG=1 packer build template.json`.
- VMware Fusion Professional Version 8.1.0 (3272237) and 7.1.3

https://gist.github.com/NathanDotTo/6bbb5a82070891428d9e985c97a59945
- The _simplest example template and scripts_ needed to reproduce the bug.

https://gist.github.com/NathanDotTo/d9b3f59f694801926a339300a8c8e982

Regards

Nathan

**Comment by cbednarski** [comment]
Thanks for the report. I was able to reproduce this once but not consistently. Also, after the failed run I ran the same build again and it worked (no need to change `vm_name`).

**Comment by NathanDotTo** [comment]
Thanks. I had a hard time getting something replicable. I could be wrong about what does make it replicable also. But at least someone else has seen it :-)

**Comment by cbednarski** [comment]
Yeah thanks for providing the configs. I think there's something more subtle going on. If this is happening 100% of the time for you (I hope it isn't!) that's different from what I'm observing.

For cases like this that are hard to repro I like to leave them open for additional feedback. Sometimes another person who observes the same thing has some ideas about what might cause it. Let me know if you learn anything new!

**Comment by NathanDotTo** [comment]
I seem to be able to produce this consistently for this value: "vm_name": "packer-ubuntu-14.04-amd64".

That is the original value for the first VM that I tried to create. Trying to build another VM with that name seems to fail for me consistently.

See: https://gist.github.com/NathanDotTo/e5543edeac4f4f4394d967d9ea07f9d7

The good thing, then, is that we have a case against which we can test or further debug.

**Comment by NathanDotTo** [comment]
I think that this issue occurs when a build fails, and Packer does not clean up properly.

I have been working on another, Fedora, build and the same issue is occurring. 

https://github.com/DevOps4Networks/cem-utils/tree/master/cem-vm

Simply put, the build creates a VM on the way to creating a box, but does not get rid of it afterwards if there is a build failure. It then hangs around in VMware, but can't be suspended or, therefore, deleted. 

![packer_vmware_issue](https://cloud.githubusercontent.com/assets/13392790/14633713/276271b6-061f-11e6-9029-463661ba6ed5.png)

This is a gist of a failure:

https://gist.github.com/NathanDotTo/e1badfde5ceb0121141f0ee16f0aa691

Then I change the vm_name, and a successful build is in this gist. Note that the VM that is build has an "_5" in the name:

https://gist.github.com/NathanDotTo/f2a92ab5fdf15c88bc97325727eacd14

I'd suggest that a contributing factor here is that Packer is not cleaning up a VMware VM before it deletes the build files that contain the .vmx it needs for cleanup purposes. This is a build where I have forced an error, with the same name with '_5':

https://gist.github.com/NathanDotTo/c6d2010d55383ddd1936676dc2328a4b

Then, I remove the problem that caused the build to fail, and try again with the same name:

https://gist.github.com/NathanDotTo/09db1d2f7f07a2255bfc2c389ddaeea9

And it fails.

**Comment by ybizeul** [comment]
Happens here as well. To solve it you have to kill the VM, vmrun is actually still running.
I feel like it's some kind of race condition. I started having that problem when I moved ly build directory to a SSD drive. On my old 7200K drive, it cleaned up nicely.

**Comment by skyzyx** [comment]
After several weeks of testing and digging, this is what I discovered works. Testing against CentOS 7, which uses the new `open-vm-tools` package:

```ruby
  # VMware Fusion
  config.vm.provider :vmware_fusion do | vm |
    vm.name = environment_name
    vm.gui = false
    vm.functional_hgfs = false

    vm.vmx["memsize"] = memsize
    vm.vmx["numvcpus"] = numvcpus
  end
```

You need to set `vm.functional_hgfs = false`. I cannot find any official documentation around this.
