### ISSUE TITLE
chef-solo provisioner cookbook upload too slow

### ISSUE THREAD

**Issue by mwhooker** [hashicorp/packer#344]
On a recent run it took about 30 min to upload ~8MB of cookbooks. It seems to be opening and closing an ssh connection for every file.

I've attempted to replace the [comm.Upload visitor](https://github.com/mitchellh/packer/blob/master/provisioner/chef-solo/provisioner.go#L169) with [comm.UploadDir](https://github.com/mwhooker/packer/blob/3191c48fca3eefbeb2a3d6ca62d9639b4ebf9727/provisioner/chef-solo/provisioner.go#L159) but I haven't gotten the paths correct yet.

**Comment by joseenriquevasquez** [comment]
Matthew, which HEAD?
packer or chef?
