### ISSUE TITLE
Use {{ env }} function with a default value

### ISSUE THREAD

**Issue by lorengordon** [hashicorp/packer#3457]
This is a feature request (unless it exists and I just can't figure out how it works). I would like to be able to use the `{{ env }}` function with a default value defined in the packer template, such that if the environment variable is empty/unset then the default value is assigned to the variable. And if the variable is assigned a value using `-var` or `-var-file`, that would take precedence over the default or the environment variable.

I [described](https://groups.google.com/d/msg/packer-tool/y9vhq0F_Vc8/KovT0vb5AAAJ) this use case in the Google group, perhaps more clearly.

**Comment by cbednarski** [comment]
Thanks for the suggestion. This makes sense to me!

**Comment by kwilczynski** [comment]
Not sure if not too much of a long-shot, but it would be nice to have the `variables` section in the template to resolve any `user` there too, so that we could re-use variables nicely. Might not be possible, though.

**Comment by cbednarski** [comment]
@kwilczynski I'm not sure I follow that one; can you give an example?

**Comment by kwilczynski** [comment]
@cbednarski sure thing! :) Check the following:

https://gist.github.com/kwilczynski/477ac2dca1884522dffbc97a76aa4325

Especially, line no. 29 in the output. It would be handy to be able to re-use variables.

**Comment by cbednarski** [comment]
Ah I see, thanks for clarifying. Doing that requires some recursive interpolation; this has been [requested previously](https://github.com/mitchellh/packer/issues/3161) but is not planned. To clarify this is different from the `{{ env }}` request.

**Comment by kwilczynski** [comment]
@cbednarski ahh! I see! Thank you for getting back to me :) Re: `{{ env }}` - yes, definitely. Sorry for stealing the spotlight here a little.

**Comment by ThisGuyCodes** [comment]
any update? This would allow some considerable cleanup in interaction with packer (currently defaults live either where they're used with some conditional shell stuff, or in a pre-packer shell script)

**Comment by PHPCEO** [comment]
Just pinging on this one as I'd really like to see this feature as well.

**Comment by mrjcleaver** [comment]
+1

**Comment by mwhooker** [comment]
I've thought about implementing this (see PR), but I think we want to wait until we support HCL, which has default values natively.

**Comment by tamsky** [comment]
Any chance that HCL fantasy is moving toward reality?

**Comment by mwhooker** [comment]
it's 100% a priority for us, but I don't have a date on it to share

**Comment by markmsmith** [comment]
Any updates on this?  I ran in to the same problem today.  
I don't need any fancy recursive evaluation, just a default like in shell scripting, eg
```
{
  "variables": {
    "alpine_version": "{{env `ALPINE_VERSION`:-3.9}}"
  }
}

**Comment by SwampDragons** [comment]
We are currently aiming to have the HCL2 integration in 6 months or so, and I believe this should be addressed by that change.

**Comment by markmsmith** [comment]
Ok, thanks.

**Comment by ZainRizvi** [comment]
Any update?

**Comment by SwampDragons** [comment]
HCL2 is currently working in a branch that's about to be merged -- see PR #8423. We believe we'll be on target for releasing initial HCL2 support in this month's 1.5.0 release. At that point, we can revisit this issue and determine whether more work needs to be done to support it.

**Comment by oliveiraev** [comment]
> HCL2 is currently working in a branch that's about to be merged -- see PR #8423. We believe we'll be on target for releasing initial HCL2 support in this month's 1.5.0 release. At that point, we can revisit this issue and determine whether more work needs to be done to support it.

#8423 is merged now. Do we have any update?

Thanks in advance

**Comment by SwampDragons** [comment]
No update yet; while basic build features were added in #8423 we still have some work to do in order to add full variable support to the HCL2 files. @azr this issue is one to consider when adding variables to hcl2, since I know that's something you're investigating right now.

**Comment by azr** [comment]
Hello here, I think this can be closed.

Variables behave similarly to what Terraform does: https://packer.io/docs/configuration/from-1.5/variables.html one can use env variables to set a packer variable.
___
The TLDR of it is:

1/ Declare a var:
```hcl
# this can be declared in any *.pkr.hcl file depending on your preference.
# For example in vars.pkr.hcl if you want them all there
# or at the top of the file where it is being used
variable "foo" {
  type = string
  default = ""
}
```

2/ Set it either from:

* env: `PKR_VAR_foo=bar packer ...`
* an `*.auto.pkrvars.hcl` file : `packer build folder/`
```hcl
# folder/varfile.auto.pkrvars.hcl
foo = "bar"
# this file needs to be in the same folder as your buildfiles and packer will just parse it as a varfile
```
* a var argument `packer -var-file /home/azr/shared_confs/foo.pkrvars.hcl -var foo=bar ...` :
```hcl
# this file can be anywhere but it's extension needs to be "pkrvars.hcl" ( or ". pkrvars json" for the json format )
foo = "bar"
```

The further down this list the more priority the setting will have. auto varfiles are sorted in lexical order of their filenames. `-var` and `-var-file`s are not auto sorted and the last one that sets a variable 'wins'.

⚠️  Note that `pkrvars.hcl` files have a specific layout and permit setting variables directly without a body.

___

Docs are [here](https://packer.io/docs/configuration/from-1.5/variables.html) and [here](https://packer.io/guides/hcl/variables)
