### ISSUE TITLE
Create VMware machines with a single disk file

### ISSUE THREAD

**Issue by thasmo** [hashicorp/packer#346]
VMware VMs use multiple *.vmdk files by default. The GUI has an option to use a single disk file only, which results in a better performance. I can't find any VMware documentation about how to configure this using the *.vmx configuration file. I guess it's not configurable but needs to be set when _creating_ the VM or the disk itself.

Is it possible to define do use a single disk file for VMware machines?

**Comment by spuder** [comment]
Documentation isn't clear. If you want packer to create a single vmdk, what do you set `disk_type_id`to?

https://www.packer.io/docs/builders/vmware-iso.html

**Comment by spuder** [comment]
I think I figured it out. The following are the values that vmware supports. 1 is the default that packer uses. 

```
-t [0|1|2|3|4|5] Specifies the virtual disk type. This option is required when you create or convert
a virtual disk. Choose one of the following types:
 0 – create a growable virtual disk contained in a single file (monolithic sparse).
 1 – create a growable virtual disk split into 2GB files (split sparse).
 2 – create a preallocated virtual disk contained in a single file (monolithic flat).
 3 – create a preallocated virtual disk split into 2GB files (split flat).
 4 – create a preallocated virtual disk compatible with ESX server (VMFS flat).
 5 – create a compressed disk optimized for streaming.
```

**Comment by gkorolev** [comment]
https://pubs.vmware.com/vsphere-55/index.jsp#com.vmware.vsphere.storage.doc/GUID-9CC98802-82D9-44B0-9735-97675258FAAE.html
