### ISSUE TITLE
vsphere post-processor failing with " invalid target disk adapter type: "thin""

### ISSUE THREAD

**Issue by vfiftyfive** [hashicorp/packer#3478]
Trying to get vsphere post-processor working with this config:

``` json
"post-processors": [
    {
      "type": "vsphere",
      "cluster": "pod-01",
      "datacenter": "myDC",
      "datastore": "nfs-ds01",
      "host": "vcsa.dc.local",
      "username": "root",
      "password": "VMware1!",
      "vm_name": "packer-us-01",
      "vm_network": "VM Network",
      "disk_mode": "thin"
     }
  ]
```

builder used is vmware-iso. Simple one.

Keep having the following error when ovftool is invoked at post-processors time.

```
"Error: Invalid target disk adapter type: "thin""
```

My destination datastore is an NFS datastore, so thin must be ok. I've also tried with sparse, seSparse, same result.

I've then tried to use ovftool manually with the same parameters:

``` shell
$ ovftool --name="packer-us-01" --diskMode="thin" --acceptAllEulas --network="VM Network" --datastore="nfs-ds01" packer-vmware-iso.ovf vi://root:VMware1!@vcsa.dc.local/myDC/host/pod-01
```

Result is successfull
- Packer Version: 0.10.0
- Host platform: ubuntu 64 trusty
- gist: https://gist.github.com/vfiftyfive/565062a0ec8616d60e64d294ca7d6339

**Comment by rickard-von-essen** [comment]
Could you rerun with `PACKER_LOG=1 packer build ...` and gist the full output. Be sure to remove any passwords that might be included.

**Comment by braddeicide** [comment]
I have the same error
    {
      "type"      : "vsphere",
      "cluster"   : "SandyCluster",
      "datacenter": "Datacenter",
      "datastore" : "NFS",
      "host"      : "vcenter.removed",
      "username"  : "removed",
      "password"  : "removed",
      "vm_name"   : "centospacker",
      "disk_mode" : "thin",
      "vm_folder" : "Templates"
    }

https://gist.github.com/braddeicide/0f665833f4a39a51e984bdf6be49cf22

**Comment by moodwrench** [comment]
same issue here.. any solutions?

**Comment by braddeicide** [comment]
This is fixed in master, until 0.10.2 is released you'll have to compile from src.

**Comment by moodwrench** [comment]
building master fixed my problem.   Thanks very much.

**Comment by marema31** [comment]
We had the same issue with 0.10. No more problem since we have updated to 0.11

**Comment by SwampDragons** [comment]
Closing this issue since it appears to have been fixed some time ago :)
