### ISSUE TITLE
WinRM provisioner when envvar is formatted incorrectly it does not cause failure

### ISSUE THREAD

**Issue by AndrewFarley** [hashicorp/packer#3714]
In exploring how to properly escape values in an environment variable I have attempted various methods of escaping and defining variables and having empty variables and I came across this bug when you define improperly formatted environment variables it does not error out, and it generates an AMI when it should have failed.

Expected outcome (either):
- Error message - Environment variable not in format 'key=value'
- Error our while trying to execute provisioner script and no image is generated

Actual outcome:
- Build succeeds and generates the AMI, but does not successfully run the inline or script commands because the pre-script that packer generates to set the environment variables is invalid.
- See: https://gist.github.com/AndrewFarley/4257f32fe0cd40d89ebf19f83dd0e0f6

Suggested fixes:
- Have a more intelligent filter to check if the input is valid
- Please see bug #2318 to help allow supporting a wider range of variable values
- Have the first command that is run enable the Powershell "strict" mode to be run before any generated set commands from packer, so you can fail on uncaught exceptions from trying to set variables.  If desired, relax that mode after finishing all the environment variables initialization.

Notes:
- This happens for both inline and scripts

Relevant log:

```
Provisioning with Powershell...
   The string is missing the terminator: ".
   + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
   + FullyQualifiedErrorId : TerminatorExpectedAtEndOfString
  Stopping the source instance...
  Waiting for the instance to stop...
  Creating the AMI: windows-ami xxxxxxxxxxxxx
  AMI: ami-XXXXXXXX
  Waiting for AMI to become ready...
```

Full Log and template:
https://gist.github.com/AndrewFarley/4257f32fe0cd40d89ebf19f83dd0e0f6

Packer Version: 0.10.1
Host Platform: OS-X 10.11.5

**Comment by SwampDragons** [comment]
Looks like this has been done since you opened this PR: https://github.com/hashicorp/packer/blob/master/provisioner/windows-shell/provisioner.go#L144-L152
