### ISSUE TITLE
builder/amazon: Cross Account access with STS and re-authorization

### ISSUE THREAD

**Issue by imduffy15** [hashicorp/packer#3722]
Hi All,

I'm wanting to use packer in against a multi account AWS setup.

The initial login account is just an IAM entry point with a SAML provider setup and assume role permissions granted to users in order to jump across into other accounts where trust relationships exist.

I have some issues with expiring tokens.... When I do the initial SAML authentication I'm given API tokens that expire within an hour, using these tokens I query AWS STS assume role and generate tokens that expire within an hour.

At the moment I'm just doing this as a wrapper script around packer, however if my packer run takes longer than an hour I'm in trouble.

Does anybody have some suggestions for workarounds, packer code changes to fix this, etc.

Thanks,
Ian.

**Comment by imduffy15** [comment]
https://github.com/mitchellh/packer/commit/883acb18fac2c732e7fdf05822959bb45977ed00

Looks like a sort of a solution, still doesn't handle the expiring issue though..... I assume for the expiring bit we would need to fire of a thread run the initial generation, sleep for expiry time, re-generate and feed back into a shared variable?

**Comment by imduffy15** [comment]
Possibly not an issue: https://github.com/aws/aws-sdk-go/blob/master/aws/credentials/stscreds/assume_role_provider.go#L153 ??

**Comment by louahola** [comment]
We use the implicit AWS credentials file (~/.aws/credentials). This alleviates the need to pass in keys to Packer. We then have a process that rotates those keys every hour.

This could still have problems because I believe the keys are scoped to the life of the AWS SDK client session. We have not had any builds take over an hour though so I can't say how much of an issue this would actually be.

**Comment by ThatGerber** [comment]
The only way that would work would be to reauthenticate and refresh the tokens at every request to AWS. STS credentials are limited to an hour. There's no way to make it longer.

**Comment by rickard-von-essen** [comment]
You may try #4124, I think it may re-authorise in the aws-sdk.

**Comment by mwhooker** [comment]
fixed in #4996
