### ISSUE TITLE
vsphere options should be each be passed as a separate args to ovftool

### ISSUE THREAD

**Issue by hh** [hashicorp/packer#3743]
The [vsphere options](https://www.packer.io/docs/post-processors/vsphere.html#options) are currently passed to to os.exec as one arg. This results in being unable to specify more than one option.

The option to arg isn't a one to one relationship, if there is a space in the vsphere options, each option should be passed as another arg.

We have 

os.exec is passed a list of args:

https://github.com/mitchellh/packer/blob/master/post-processor/vsphere/post-processor.go#L132

``` ruby
    log.Printf("Starting ovftool with parameters: %s", strings.Join(args, " "))
cmd := exec.Command("ovftool", args...)
```

If we pass in Options, we put that entire string as one arg:

https://github.com/mitchellh/packer/blob/master/post-processor/vsphere/post-processor.go#L169-L170

``` ruby
    if len(p.config.Options) > 0 {
        args = append(args, p.config.Options...)
```

If we put more than one option (separated by spaces):

https://github.com/ii/bento/blob/vsphere/centos-5.11-vsphere.json#L138-L140

``` ruby
      "vm_name": "{{.Name}}-{{isotime \"2006-Jan-02-0315\"}}",
      "disk_mode": "thin",
      "options": "--X:logFile=\"vsphere-{{.Name}}-{{isotime \"2006-Jan-02-0315\"}}.log\" --X:logLevel=trivia --machineOutput",
```

It results in ovftool not understanding the arguments correctly:

``` shell
2016/07/22 07:38:27 ui: ==> vmware-iso: Running post-processor: vsphere
==> vmware-iso: Running post-processor: vsphere
2016/07/22 07:38:27 ui:     vmware-iso (vsphere): Uploading packer-centos-5.11-x86_64-vmware/centos-5.11-x86_64.vmx to vSphere
2016/07/22 07:38:27 packer: 2016/07/22 07:38:27 Starting ovftool with parameters: --acceptAllEulas --name=<no value>-2016-Jul-21-0719 --datastore=SolidFire_LUN --noSSLVerify=true --diskMode=thin --network=beneplac-OAM --X:logFile="vsphere-<no value>-2016-Jul-21-0719.log" --X:logLevel=trivia --machineOutput packer-centos-5.11-x86_64-vmware/centos-5.11-x86_64.vmx vi://aus2%5Cbeneplac.cmcclimans:BMtZ6ej@vsphere.beneplace.com/beneplac-aus2-HA/host/Beneplac-H
    vmware-iso (vsphere): Uploading packer-centos-5.11-x86_64-vmware/centos-5.11-x86_64.vmx to vSphere
2016/07/22 07:38:30 Deleting original artifact for build 'vmware-iso'
2016/07/22 07:38:30 ui error: Build 'vmware-iso' errored: 1 error(s) occurred:

* Post-processor failed: Failed: exit status 1

2016/07/22 07:38:30 Builds completed. Waiting on interrupt barrier...
2016/07/22 07:38:30 machine readable: error-count []string{"1"}
2016/07/22 07:38:30 ui error: 
==> Some builds didn't complete successfully and had errors:
2016/07/22 07:38:30 machine readable: vmware-iso,error []string{"1 error(s) occurred:\n\n* Post-processor failed: Failed: exit status 1\n"}
2016/07/22 07:38:30 ui error: --> vmware-iso: 1 error(s) occurred:

* Post-processor failed: Failed: exit status 1
2016/07/22 07:38:30 ui: 
==> Builds finished but no artifacts were created.
Build 'vmware-iso' errored: 1 error(s) occurred:

2016/07/22 07:38:30 waiting for all plugin processes to complete...
* Post-processor failed: Failed: exit status 1


==> Some builds didn't complete successfully and had errors:
--> vmware-iso: 1 error(s) occurred:

* Post-processor failed: Failed: exit status 1

```

This creates a logfile:

```
ls -la lrt .
-rw-r--r--  1 hh hh    13064 Jul 22 07:38 "vsphere-<no value>-2016-Jul-21-0719.log" --X:logLevel=trivia --machineOutput
```
- Packer Version 
  commit 37fe7647279ed79ec86020b7852e08f04b079dcc
- Host platform
  Ubuntu 16.04

https://gist.github.com/hh/4e47f36003f8708f503b8b6dc05b7beb

**Comment by kwilczynski** [comment]
@hh I think you issue is because the "option" parameter is to be passed as an array of string (see: [options](https://www.packer.io/docs/post-processors/vsphere.html#options) in the documentation) as per [post-processor.go#L31](https://github.com/mitchellh/packer/blob/master/post-processor/vsphere/post-processor.go#L31), thus passing a string would definitely make `exec.Command` upset. 

Try to pass it as follows:

```json
{
  "options": [
    "--X:logFile=\"vsphere-{{.Name}}-{{isotime \"2006-Jan-02-0315\"}}.log\"",
    "--X:logLevel=trivia",
    "--machineOutput"
  ]
}

And see if this fixes it for you.

**Comment by kwilczynski** [comment]
To add.

Since I don't know form the top of my head, I wonder what happens when the `config.Decode`  gets a string from JSON and the struct member is a slice? I would hope that it would explode to indicate a mismatched type, but it didn't seem to be the case here. I suppose the `p.config.Options` had just one entry, which was the whole content of "options" as-is.

**Comment by rickard-von-essen** [comment]
@kwilczynski `config.Decode` parses a string as a single item slice.

**Comment by kwilczynski** [comment]
@rickard-von-essen thank you!

**Comment by hh** [comment]
Might be useful to perform a check to see if it's an array or string since the type checking is a bit lax.

**Comment by SwampDragons** [comment]
The above strict type checking comes standard in HCL configs, which we are slowly moving towards. I think that documenting this option as an array of strings is sufficient.
