### ISSUE TITLE
VMWare-ISO on ESXi Fails on Deleting Floppy

### ISSUE THREAD

**Issue by michaeltlombardi** [hashicorp/packer#3834]
## Error

```
2016/08/25 17:12:51 packer.exe: 2016/08/25 17:12:51 Deleting floppy disk: C:\Users\mtl\AppData\Local\Temp\packer540726687
2016/08/25 17:12:51 ui error: Build 'vmware-iso' errored: GetFileAttributesEx repro-packer: The system cannot find the file specified.
```

It _looks_ like the build errors when deleting the floppy disk. I did not get the same errors when targeting the build against VMWare Workstation locally, only when targeting ESXi.
### Client

Packer Version: 0.10.1 (Windows)
OS Version: 6.1.7601 (Windows 7)
### ESXi

```
~ # uname -a
VMkernel labesxi01 5.5.0 #1 SMP Release build-3029944 Aug 31 20
15 01:15:24 x86_64 GNU/Linux
```
## Links

You can find the debug log, template, and files [here](https://gist.github.com/michaeltlombardi/679a477caa93c8a4d10f5a11f56bc34f).

**Comment by rickard-von-essen** [comment]
Please supply the information requested in the issue template:
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a [gist](https://gist.github.com).
- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your [gist](https://gist.github.com).

**Comment by michaeltlombardi** [comment]
@rickard-von-essen: I included links to both the debug log output and the example template/scripts in my initial post.

I've relinked them [here](https://gist.github.com/michaeltlombardi/679a477caa93c8a4d10f5a11f56bc34f) as well.

**Comment by rickard-von-essen** [comment]
Sorry missed that.

**Comment by michaeltlombardi** [comment]
No problem! I had to double check and make sure I didn't include a null link on accident.

**Comment by dan-rose** [comment]
I too am having exactly the same issue with vmware-iso building a windows vm on esxi 5.1

2016/09/20 17:12:07 packer.exe: 2016/09/20 17:12:07 Deleting floppy disk: C:\Users\drose\AppData\Local\Temp\packer280311359
2016/09/20 17:12:07 ui error: Build 'windows_vmware_esxi' errored: GetFileAttributesEx output-windows_vmware_esxi: The system cannot find the file specified.

Have added the files to [gist](https://gist.github.com/dan-rose/40c488bcf1be7cba5264c455d4d55254)

**Comment by michaeltlombardi** [comment]
Note: the issue persists after upgrading the ESXi node to v6

**Comment by lomeroe** [comment]
I had the same issue.  I resolved it by creating a folder in my working directory with the name listed after the "GetFileAttributeEx" (output-vmware-iso in my case):

Error
```
2016/10/06 15:20:30 packer.exe: 2016/10/06 15:20:30 Deleting floppy disk: C:\Users\ADMIN-~1\AppData\Local\Temp\2\packer277625447
2016/10/06 15:20:30 ui error: Build 'vmware-iso' errored: GetFileAttributesEx output-vmware-iso: The system cannot find the file specified.
```

**Comment by michaeltlombardi** [comment]
@lomeroe I'll try your fix and report back. Thanks!

**Comment by michaeltlombardi** [comment]
@lomeroe Finally got around to testing this after we cleared up some other issues. It worked!

This seems to indicate that, whatever the error message, the actual problem is that Packer doesn't create the output folder properly.

**Comment by arizvisa** [comment]
Does this issue still occur in ESXi with the vmware-iso builder on later versions of packer?

**Comment by mwhooker** [comment]
@arizvisa assuming it's safe to close this
