### ISSUE TITLE
powershell provisioner needs escaped $ on ssh communicator

### ISSUE THREAD

**Issue by kenmacleod** [hashicorp/packer#3913]
Packer 0.10.1, Windows 2012r2 guest, using [MLS Software SSH](http://www.mls-software.com/opensshd.html) installed using [Joe Fitzgerald's openssh.ps1](https://github.com/joefitzgerald/packer-windows/blob/master/scripts/openssh.ps1).

This is specific to the `ssh` communicator, the provisioner works correctly with `winrm`.

This issue is different from #2785.

Definining a `powershell` provisioner like this:

``` json
    {
      "type": "powershell",
      "script": "scripts/provision.ps1"
    }
```

The `$` as in `$env:PACKER_BUILDER_TYPE` and others is not escaped when passed to the [ssh shell?] and the POSIX-style shell expands `$env` as a shell variable before running the command.

```
==> virtualbox-iso: Provisioning with shell script: scripts/provision.ps1
    virtualbox-iso: :PACKER_BUILDER_TYPE=virtualbox-iso : The term
    virtualbox-iso: ':PACKER_BUILDER_TYPE=virtualbox-iso' is not recognized as the name of a
    virtualbox-iso: cmdlet, function, script file, or operable program. Check the spelling of the
    virtualbox-iso: name, or if a path was included, verify that the path is correct and try again.
    virtualbox-iso: At line:1 char:5
    virtualbox-iso: + & { :PACKER_BUILDER_TYPE="virtualbox-iso";
    virtualbox-iso: :PACKER_BUILD_NAME="virtualbox-iso";  ...
```

I can work around this issue by using the `shell` provisioner with an `execute_command` identical to the `powershell` provisioner with escapes for the `$`:

``` json
    {
      "type": "shell",
      "script": "scripts/provision.ps1",
      "remote_path": "C:/Users/vagrant/script.ps1",
      "execute_command": "powershell \"& { \\$env:PACKER_BUILDER_TYPE=\\\"{{build_type}}\\\"; \\$env:PACKER_BUILD_NAME=\\\"{{build_name}}\\\"; C:/Users/vagrant/script.ps1; exit \\$LastExitCode}\""
    }
```

**Comment by eamonnfaherty** [comment]
Thanks for the workaround @kenmacleod 

I have the same issue with packer 0.10.2 on a mac os x host with a win7 guest.

**Comment by SwampDragons** [comment]
There have been a lot of changes to the way that Powershell manages escaping, so I'm going to close this. If it's still an issue with a recent version of Packer, please do open a new issue :)
