### ISSUE TITLE
builder/googlecloud -  upload image to Google Storage

### ISSUE THREAD

**Issue by areznikov-kabam** [hashicorp/packer#3945]
Currently packer can create GCE Images, but it's not possible ( please correct me if I am wrong) to upload this images to GS. Therefore it's not possible to make these images public, i.e. accessible from any GCE account/project

**Comment by rickard-von-essen** [comment]
Yes, currently this is not supported, but PR's are welcome. Depending on the api this might be a feature in the googlecompute builder or a new post-processor.

**Comment by crunk1** [comment]
I added this functionality as a post-processor in https://github.com/mitchellh/packer/pull/3760. It has not been pulled into a release yet.

**Comment by crunk1** [comment]
Though, I still need to add licenses to the exported image.

**Comment by seanmalloy** [comment]
Looks like this was implemented in #3760 which was merged a while ago. This feature was released in packer version 0.11.0.

Can this issue be closed out?

**Comment by rickard-von-essen** [comment]
Yes, @seanmalloy thanks for keeping it clean. 🍻
