### ISSUE TITLE
idea for command

### ISSUE THREAD

**Issue by vtolstov** [hashicorp/packer#3951]
For CI testing and automatic deploy i need to determine what template needs to be rebuild when changing some files. 
What do you think about `packer depends xxx.json` command?
So this command output all files needed for this template. So in case of CI i simply need to grep output for changes files. Or may be reverse dependency order for file determine json template file...
Or how can I solve my problem? 
Create dedicated repo for each template not very useful because all fedora templates need equal files.
And other repos too...

**Comment by rickard-von-essen** [comment]
I think it's interesting. We are currently thinking about how to handle the same thing at my day job. But the real tricky part is to know which files your provisioner depends on.

**Comment by vtolstov** [comment]
@rickard-von-essen i think about extract info from all local provisioners, all files from http dir...
May be i miss something?

**Comment by rickard-von-essen** [comment]
No I just think this will be hard, especially with shell scripts.

**Comment by vtolstov** [comment]
2016-10-02 18:22 GMT+03:00 Rickard von Essen <notifications@github.com>:

> No I just think this will be hard, especially with shell scripts.


Why all scripts in shell provisioner inside scripts array... ?


-- 
Vasiliy Tolstov,
e-mail: v.tolstov@selfip.ru

**Comment by rickard-von-essen** [comment]
Or maybe not. Since all of them are uploaded by packer.

**Comment by vtolstov** [comment]
I'm try to implement packer files xxx.json to get needed files for this template.
May be this is incomplete, but not so bad =)

**Comment by SwampDragons** [comment]
Doing a stale issue cleanup -- Since I rejected the PR a while back as too great a maintenance burden for too small a benefit, I'm going to close this related issue as well.
