### ISSUE TITLE
custom TMPDIR for post-processor-vagrant

### ISSUE THREAD

**Issue by tehranian** [hashicorp/packer#398]
It looks like "post-processor-vagrant" is fixed to use the OS's default temp dir (ie, "/tmp").  From post-processor/vagrant/vmware.go:

```
     // Create a temporary directory for us to build the contents of the box in
            dir, err := ioutil.TempDir("", "packer")
```

Our build machines have relatively small OS disks and large secondary data disks.  It'd be really nice if the first arg to TempDir() were configurable somehow and not fixed to OS default temp dir.

FWIW - The "go.crypto" package does something like this:

```
    tmpdir = getenv("TMP");
```

**Comment by jcoutch** [comment]
Just a note - if you're using Packer on Windows, you want to set the "TEMP" environment variable.  :-)
