### ISSUE TITLE
add support for sata disk_interface in QEMU builder

### ISSUE THREAD

**Issue by Wenzel** [hashicorp/packer#3983]
Hi !

the [QEMU builder](https://www.packer.io/docs/builders/qemu.html) currently supports 4 types for the `disk_interface` configuration :
- `ide`
- `scsi`
- `virtio`
- `virtio-scsi`

Would it be possible to add support for `sata` as well ?

**Comment by rickard-von-essen** [comment]
Looks like a trivial change, you just have to add it to the list in:
https://github.com/mitchellh/packer/blob/d52a83a901e99794167252071382be1a7a75d861/builder/qemu/builder.go#L55

Please open a PR

**Comment by Wenzel** [comment]
Thanks for your quick reply

This is the part of the command line generated by Packer for QEMU builder which configures the hard drive :
`-drive file=output-qemu/qemu.qcow2,if=ide,cache=writeback,discard=ignore`
Here, `disk_interface` was set to `ide`.

If it is correct that Packer sets the value of `if=xxx` by the content of the `disk_interface` key, then
just adding the `sata` option won't work, as demonstrated by the following command line :
`qemu-system-x86_64 -drive file=out-qemu/qemu,if=sata,cache=writeback,discard=ignore: unsupported bus type 'sata'`

Furthermore, when i create a new VM in virt-manager and set the hard drive in `sata`, this is the command line that is generated by `libvirt` :
`qemu-system-x86_64 -drive file=image.qcow2,if=none,id=drive-sata0-0-0,format=qcow2 -device ide-hd,bus=ide.0,drive=drive-sata0-0-0,id=sata0-0-0,bootindex=2`

So i'm not sure that it will be as simple as adding `sata` to the `diskInterface` map ??

**Comment by rickard-von-essen** [comment]
Ping @vtolstov

**Comment by vtolstov** [comment]
sata can be added, but why you need it? why scsi not works? all sata in linux works via scsi subsystem...

**Comment by Wenzel** [comment]
I am trying to build a Windows 7 x64 image.
With the `q35` chipset, the `ide` controller is too old.
And the `scsi` driver is not included in the iso i'm using.

**Comment by vtolstov** [comment]
This is simple - use virtio drivers on floppy. This is fastest way . My piece of packer template for windows 2008:
```
      "disk_interface": "virtio-scsi",                                                                                                                                          
      "iso_urls": [ "http://download.microsoft.com/download/7/5/E/75EC4E54-5B02-42D6-8879-D8D3A25FBEF7/7601.17514.101119-1850_x64fre_server_eval_en-us-GRMSXEVAL_EN_DVD.iso" ],
      "net_device": "virtio-net",                                                                                                                                               "output_directory": "output/windows-2k8R2-x86_64-qemu/",
      "machine_type": "q35",                                                                                                                                          "floppy_files": [                                                                                                                                                           "floppy/drivers/virtio-win-0.1.1/vioscsi/2k8R2/amd64/*.cat",
        "floppy/drivers/virtio-win-0.1.1/vioscsi/2k8R2/amd64/*.inf",                                                                                                              "floppy/drivers/virtio-win-0.1.1/vioscsi/2k8R2/amd64/*.sys",                                                                                                              "floppy/drivers/virtio-win-0.1.1/viostor/2k8R2/amd64/*.cat",
        "floppy/drivers/virtio-win-0.1.1/viostor/2k8R2/amd64/*.inf",                                                                                                              "floppy/drivers/virtio-win-0.1.1/viostor/2k8R2/amd64/*.sys",                                                                                                              "floppy/drivers/virtio-win-0.1.1/NetKVM/2k8R2/amd64/*.cat",
        "floppy/drivers/virtio-win-0.1.1/NetKVM/2k8R2/amd64/*.inf",
        "floppy/drivers/virtio-win-0.1.1/NetKVM/2k8R2/amd64/*.sys",
        "floppy/common/*",
        "floppy/windows-2k8R2-x86_64/*"
```

**Comment by Wenzel** [comment]
Thanks for your template with the virtio drivers !

But for testing purposes, i have a specific configuration that requires to use the sata driver.
That's why i wanted to have support for it in Packer.

**Comment by vtolstov** [comment]
i'm not promise, but i can add sata support it in friday.
