### ISSUE TITLE
Ability to configure remote ESX directory for vmware-iso builder when using ovftool

### ISSUE THREAD

**Issue by eschrock** [hashicorp/packer#4051]
Currently, the vmware-iso builder unilaterally sets the output directory within the datastore to the vmname, in [builder/vmware/iso/builder.go:201](https://github.com/mitchellh/packer/blob/3c8dabba9e233d1d9df806e074e70ae880e5b10a/builder/vmware/iso/builder.go#L201)

`if b.config.RemoteType != "" && b.config.Format != "" {
        b.config.OutputDir = b.config.VMName
    }`

The output_directory setting is ignored. As an aside, it seems to be ignored on the [local side as well](https://github.com/mitchellh/packer/issues/3896), so it's not clear what its purpose is for this remote/ovftool use case.

For local directories, this is not a big issue because each local directory is private. But ESX build machines are a shared resource, so if two developers happen to be building something with the same vmname (quite possible if working on the same product), then they will clash (possibly in horrific ways). You can work around this by making your vmname unique, or by setting the datastore name to be a unique sub-directory, but these all leave behind remnants that must be manually cleaned up.

I don't know why packer doesn't respect "output_directory" here, but it would be nice if we could set the remote output directory on the ESX build machine to avoid vmname clashes from competing builds.

**Comment by rickard-von-essen** [comment]
Doesn't it check if the remote dir exists? Otherwise this is a bug. 

I think ESXi support was added after the vsphere post-processor and the use case vmware-iso remote plus vsphere post-processor was overlooked.

**Comment by eschrock** [comment]
Good question, it does appear to fail, but not in an elegant way:

2016/10/24 12:07:17 ui: ==> vmware: Creating virtual machine disk
==> vmware: Creating virtual machine disk
2016/10/24 12:07:17 packer: 2016/10/24 12:07:17 opening new ssh session
2016/10/24 12:07:17 packer: 2016/10/24 12:07:17 starting remote command: vmkfstools -c 81920M -d zeroedthick -a lsilogic /vmfs/volumes/4fa858d3-9425303a-b26c-782bcb3a569e/delphix-0.0.1/disk.vmdk
2016/10/24 12:07:18 packer: 2016/10/24 12:07:18 remote command exited with '255': vmkfstools -c 81920M -d zeroedthick -a lsilogic /vmfs/volumes/4fa858d3-9425303a-b26c-782bcb3a569e/delphix-0.0.1/disk.vmdk
2016/10/24 12:07:18 ui error: ==> vmware: Error creating disk: 'vmkfstools -c 81920M -d zeroedthick -a lsilogic /vmfs/volumes/4fa858d3-9425303a-b26c-782bcb3a569e/delphix-0.0.1/disk.vmdk'
==> vmware: 
==> vmware: Stdout: 
==> vmware: 
==> vmware: Stderr: Failed to create virtual disk: The file already exists (39).
==> vmware:
2016/10/24 12:07:18 packer: 2016/10/24 12:07:18 Deleting floppy disk: /var/folders/95/ykwpz_wn0h1384bhq4q7h79w0000gq/T/packer414694987
==> vmware: Error creating disk: 'vmkfstools -c 81920M -d zeroedthick -a lsilogic /vmfs/volumes/4fa858d3-9425303a-b26c-782bcb3a569e/delphix-0.0.1/disk.vmdk'
==> vmware: 
==> vmware: Stdout: 
==> vmware: 
2016/10/24 12:07:18 packer: 2016/10/24 12:07:18 opening new ssh session
==> vmware: Stderr: Failed to create virtual disk: The file already exists (39).
==> vmware:
2016/10/24 12:07:18 packer: 2016/10/24 12:07:18 starting remote command: test -e /vmfs/volumes/4fa858d3-9425303a-b26c-782bcb3a569e/delphix-0.0.1
2016/10/24 12:07:18 packer: 2016/10/24 12:07:18 remote command exited with '0': test -e /vmfs/volumes/4fa858d3-9425303a-b26c-782bcb3a569e/delphix-0.0.1
2016/10/24 12:07:18 ui: ==> vmware: Deleting output directory...
==> vmware: Deleting output directory...
2016/10/24 12:07:18 packer: 2016/10/24 12:07:18 opening new ssh session
2016/10/24 12:07:18 packer: 2016/10/24 12:07:18 starting remote command: rm -rf /vmfs/volumes/4fa858d3-9425303a-b26c-782bcb3a569e/delphix-0.0.1
2016/10/24 12:07:18 packer: 2016/10/24 12:07:18 remote command exited with '1': rm -rf /vmfs/volumes/4fa858d3-9425303a-b26c-782bcb3a569e/delphix-0.0.1
2016/10/24 12:07:18 packer: 2016/10/24 12:07:18 Error removing output dir: 'rm -rf /vmfs/volumes/4fa858d3-9425303a-b26c-782bcb3a569e/delphix-0.0.1'
2016/10/24 12:07:18 packer: 
2016/10/24 12:07:18 packer: Stdout:
2016/10/24 12:07:18 packer: 
2016/10/24 12:07:18 packer: Stderr: rm: can't remove '/vmfs/volumes/4fa858d3-9425303a-b26c-782bcb3a569e/delphix-0.0.1/disk-flat.vmdk': Device or resource busy
2016/10/24 12:07:18 packer: rm: can't remove '/vmfs/volumes/4fa858d3-9425303a-b26c-782bcb3a569e/delphix-0.0.1/delphix-0.0.1-3f867b0b.vswp': Device or resource busy
2016/10/24 12:07:18 packer: rm: can't remove '/vmfs/volumes/4fa858d3-9425303a-b26c-782bcb3a569e/delphix-0.0.1/delphix-0.0.1.vmx.lck': Device or resource busy

In this case, I left a previous build registered with "keep_registere: true" and tried a new build. It doesn't do an explicit check for the directory AFAICT, but tries to create the disk anyway (which thankfully fails). More troublesome is that it appears to then go and try to destroy the directory (containing my running VM), even though it didn't create it in the first place.

Having a clean check for this directory would definitely avoid horrific outcomes (like trying to remove the directory contents while another build is in progress). But even with a clean failure mode, it means that builds could randomly fail (albeit gracefully) if another build is using the same vmname.

**Comment by mwhooker** [comment]
unfortunately I think this too big a change to shoehorn into 1.0. I'm not familiar enough with esxi to be confident in my changes to this, so I'm going to retarget. Hopefully we can solve this along with #3136

**Comment by SwampDragons** [comment]
It looks like this was fixed and then regressed, because the behavior described here still exists and was opened in an issue recently: see #6941

I'm going to close this one in favor of that, since that one is a lot more recent and has some discussion around code. But this has good context for _why_ we should fix it.
