### ISSUE TITLE
Make SSH-based provisioners (script, etc.) work on Windows

### ISSUE THREAD

**Issue by friism** [hashicorp/packer#4170]
This is a feature request.

I've made the amazon builder work with Open-SSH and the ssh communicator, to get rid of WinRM jankiness and because traffic is not encrypted. Details here: https://github.com/friism/ec2-windows-packer-ssh

There are some problems with the shell provisioner though, that it'd be nice to address:

 * [ ] `execute_command` - (should be powershell if script is `.ps1`)
 * [ ] `scp` path handling for script upload
 * [ ] clean-up
 * [ ] line endings are not correct

cc @StefanScherer @jamiegs @mefellows @fzk-rec

**Comment by rickard-von-essen** [comment]
Could you elaborate on _"line endings are not correct"_?

**Comment by friism** [comment]
@rickard-von-essen a file that's `CRLF` (Windows line endings) on the host running Packer ends up having `LF` line endings on the builder machine. I'm guessing that happens somewhere in the `scp` flow.

Probably, the communicator should just make sure that files are `CRLF` when uploaded to a Windows system...

**Comment by rickard-von-essen** [comment]
Ok, that is bad I think we should only use binary mode and never change the content of the file transferred.

**Comment by SwampDragons** [comment]
It is my understanding that there are quite a few people who use the ssh communicator with windows these days; I think these issues have been resolved; take a look at the https://github.com/joefitzgerald/packer-windows repo for some examples. 

If there are still issues that haven't been resolved, please feel free to reopen; I'm just going through old issues to see if they're stale and I _think_ these issues are no longer problems.
