### ISSUE TITLE
Implement googlecompute Windows startup scripts.

### ISSUE THREAD

**Issue by crunk1** [hashicorp/packer#4190]
@adjackura

We need to support startup scripts for Windows images.

See builder/googlecompute/startup.go and builder/googlecompute/step_create_instance.go:(*Config)createInstanceMetadata for startup script logic.

**Comment by erjohnso** [comment]
+1

**Comment by azr** [comment]
I think this can be closed by #4725 (docs) 

Adding a `windows-startup-script-cmd` metadata field is currently solution for this; though the builder will not wait for script to terminate.
