### ISSUE TITLE
ESXi builder does not create OVF/OVA/VMX

### ISSUE THREAD

**Issue by LEALCorentin** [hashicorp/packer#4214]
Hello there,

I'm trying to build VMs using the ESXi builder against an ESX6. I'm doing it on Windows 7 with Packer 0.12.0 (using Git Bash to have a proper CLI). I have installed OVF Tool 4.2.0 on my laptop and add it to the path.

My problem is that I can create VMs on the ESX using Packer but if I do specify the "format" option the execution seems correct even though I am not sure of it but the file is nowhere to be found. Neither on the ESX nor on my computer. If I do not give the "format" option the VM files are created (.vmx, .vmdk etc.).

What I want to do is create an OVF...

Here is the Gist containing all the files I use to create the OVF :  https://gist.github.com/LEALCorentin/0b8eb58a2d16b12976069185d86638f3

The line that seems strange to me is :

`2016/11/28 18:42:25 [ERR] yamux: Failed to read header: read tcp 127.0.0.1:46328->127.0.0.1:10000: wsarecv: Une connexion existante a dû être fermée par l’hôte distant.`

(The end means "An existing connection had to be closed by the remote host").

This seems strange but after looking at the Yamux code I think I understood it is normal ...

I'd really appreciate your help as I'm working on it for quite a while now. Thank you in advance.

**Comment by LEALCorentin** [comment]
Okay guys, that was pretty dumb...
The "remote_type" has to be 'esx5' no matter the actual version, I've set it to 'esx6' thus it was skipping the export part.

Maybe it should be a great idea to correct this because there was no obvious error and using a parameter which semantically wrong is not logical.
The solutions may be either to add an error or, maybe it is the best choice, changing 'esx5' to 'esx'. ESX 4.x has been discontinued, I think Packer should stop supporting it as well in order to make a cleaner ESX builder.

**Comment by eegilbert** [comment]
The [docs](https://www.packer.io/docs/builders/vmware-iso.html#remote_type) do state that esx5 is the only supported version at the moment. If you were running a PACKER_LOG=1 packer build file.json, possibly the error is there?

**Comment by LEALCorentin** [comment]
That's right my bad.
But if I am right the ESX6 is fully compatible with the ESX5 except for the new VM version. It doesn't make sense to put as a parameter 'esx5' while I'm using a ESX6 and everything works perfectly.
Otherwise it is said that 'esx5' is the only value accepted not that the newer versions are not supported. I don't know, I feel like this isn't clear enough.

I have run it with the PACKER_LOG=1 but there is no error or anything (it is in the gist). It just didn't do anything at the export step because it was looking for esx5 not 6.

**Comment by eegilbert** [comment]
Interesting, I would have thought it would error with a message. When I started with Packer to vSphere I found the docs pretty clear. I understand your point about versioning, however if 6 is close enough to 5 as you mentioned, then I guess most of us just looked at the required value, shrugged and moved on. I mean he could have called it pop_tart27 :)

**Comment by LEALCorentin** [comment]
I didn't ... :)
It seems to me that even the builder should be divided depending on the usage, ESX/local.

To be honest I thought the documentation wasn't up to date, I saw examples with 'esx6' and thought this would be the way go. It wasn't logical for me to choose another version than the one I am using.

**Comment by dave2** [comment]
It may be better to rename it to "esx" and perform a version check if there's something discovered that requires a different implementation than the current one. Or at least check it's >= 5.0 for now.
