### ISSUE TITLE
ESX Builider | Warning in disk creation command on ESX 6 (option deprecated)

### ISSUE THREAD

**Issue by LEALCorentin** [hashicorp/packer#4228]
With the ESX builder the command vmkfstools is used to create the disk. The option `-a` | `--adapterType` is used (written directly in the code) this option is deprecated thus ignored. Maybe there is something to do about it.

**Comment by rickard-von-essen** [comment]
Do you have any references to docs? When was is removed etc. If we removed it's important that no one still relies on it.

**Comment by rickard-von-essen** [comment]
Is it ignored or does it cause an error? It's not clear from the heading vs. description.

**Comment by macgahe** [comment]
Hi, I did have the same issue and I noticed I was running and old version 0.10.1. Issue was , I did install packer using brew and didn't download the latest one..

**Comment by LEALCorentin** [comment]
I am sorry for the misleading heading, this is not an error. Everything works properly it's just that the adapterType option is deprecated thus ignored but only on the ESX 6. I didn't though it could have been the ESX version in cause, later on I tried on an ESX 5.5 for another reason and saw this option was not deprecated on this one. Otherwise the default adapterType value in the ESX 6 is LSI Logic which is the value Packer tries to give.

To conclude, it is just about the ESX version and there is no error, it's not a big deal or anything, it's only that it could be a good idea to adapt the code depending on the ESX version even though both are compatible.

**Comment by SwampDragons** [comment]
Closing because this hasn't turned out to be an issue in the last four years; if someone in the community feels strongly about this warning and wants to fix it, PRs are welcome :)
