### ISSUE TITLE
Builder vmware-iso type:esx5 post-processor:vagrant format:ovf can't find vm-name-flat.vmdk

### ISSUE THREAD

**Issue by nowhammies** [hashicorp/packer#4267]
FOR BUGS:

The machine gets provisioned correctly on remote on Esxi 6.0 box. However when doing the post processing it is unable to get the files to run through the ovftool. Then resources are deleted and unless I use debug mode I can not grab the disk image to convert manually.

I made sure that VNC ports were configured on Esxi host were configured correctly. 

- Packer version from `packer version`
Packer v0.12.0
- Host platform
Windows 7

- Debug log output from `PACKER_LOG=1 packer build template.json`.
  https://gist.github.com/nowhammies/fd9255f1ac0bc149de469af2ecec7974
- My json template is from a modified version of https://github.com/kaorimatz/packer-templates
  https://gist.github.com/nowhammies/fd9255f1ac0bc149de469af2ecec7974

**Comment by rickard-von-essen** [comment]
Run with `-on-error=ask` to make packer pause when there is an error.

**Comment by nowhammies** [comment]
Hi I tried with the argument  `-on-error=ask` and it still cleaned up and did not ask me in the same way it did when it timed out shutting down the vm in a previous run.

**Comment by dave2** [comment]
Your json doesn't have `format` defined for the VMware builder, so despite `output_directory` being defined it doesn't do anything with it. What should happen in the output log is ovftool downloading the image from ESXi to local, but that doesn't happen at all, so the artifact the post-processor is trying to use is still the remote-path on ESXi being treated as local.

**Comment by nowhammies** [comment]
Thanks for the suggestion I will explicitly set it and give it a try however, according to the documentation format defaults to "ovf".  If you have a json file in which this scenario is working for you please post a gist and I will try and base my config off that.

**Comment by dave2** [comment]
Docs are definitely wrong then, as the code path never forces `format` to be a specific value if not set. The check on valid values is done here: https://github.com/mitchellh/packer/blob/master/builder/vmware/iso/builder.go#L166

The step to call ovftool happens here:
https://github.com/mitchellh/packer/blob/master/builder/vmware/iso/step_export.go#L38

The following gist has worked fine for me and has both set.
https://gist.github.com/dave2/1369e7df90362d5357826ea9808cffe1

Where in the docs does it say OVF is the default?

**Comment by nowhammies** [comment]
Hi Dave thanks for the help. 
I am able to keep the files around now which is very useful. 
The documentation i was referencing was here:

https://www.packer.io/docs/builders/vmware-iso.html

format (string) - Either "ovf", "ova" or "vmx", this specifies the output format of the exported virtual machine. This defaults to "ovf". Before using this option, you need to install ovftool.
