### ISSUE TITLE
puppet-server provisioner now more broken in Windows

### ISSUE THREAD

**Issue by c22** [hashicorp/packer#4384]
Looks like 7feb8b993c5447bfeff5fce78781d736e5e3be7b activated a sleeper bug in the puppet-server provisioner. Previously, I guess `facterVars` was empty so the bug went unnoticed on Windows, but now that `facterVars` is populated with default values, the resulting `ExecuteCommand` is no longer compatible in Windows.

Windows doesn't support `ENVVAR=VAR command` style setting of environment variables per command, so the provisioner breaks thusly:

> ==> amazon-ebs: Provisioning with Puppet...
>     amazon-ebs: Creating Puppet staging directory...
>     amazon-ebs: Running Puppet: FACTER_packer_build_name='amazon-ebs' FACTER_packer_builder_type='amazon-ebs' puppet agent --onetime --no-daemonize --test --pluginsync --no-report --detailed-exitcodes
>     amazon-ebs: 'FACTER_packer_build_name' is not recognized as an internal or external command,
>     amazon-ebs: operable program or batch file.

Unfortunately I can't see an easy fix without either a lot of refactoring or terrible hacks which are worse than what I came up with for #3850.

Best fix for people like me who need to roll out Windows AMIs in this way is to rollback 7feb8b993c5447bfeff5fce78781d736e5e3be7b.

Tagging @seanmalloy for FYI.

Perhaps a short-term solution that doesn't involve rolling back this change is rolling forward with a configurable option in the puppet-server provisioner to omit FacterVars.

**Comment by c22** [comment]
Oh I just realized, of course we can override execute_command so a fix for Windows users can be achieved by updating execute_command to exclude `FacterVars`

eg.

`"puppet agent --onetime --no-daemonize " + "{{if ne .PuppetServer \"\"}}--server='{{.PuppetServer}}' {{end}}" + "{{if ne .Options \"\"}}{{.Options}} {{end}}" + "{{if ne .PuppetNode \"\"}}--certname={{.PuppetNode}} {{end}}" + "{{if ne .ClientCertPath \"\"}}--certdir='{{.ClientCertPath}}' {{end}}" + "{{if ne .ClientPrivateKeyPath \"\"}}--privatekeydir='{{.ClientPrivateKeyPath}}' {{end}}" + "--detailed-exitcodes`

**Comment by c22** [comment]
Given the fix doesn't require any code changes and the fact that Windows is not likely to be considered a first class citizen in packer for quite some time, I'm happy for this issue to be closed if the maintainers want to close it.

Also on the rare chance that some other poor soul needs to build Windows templates with Packer + Puppet, I struggled for a few minutes with the JSON escaping of execute_command so to save you some time, here's the right string:

`"execute_command": "{{if ne .PuppetBinDir \"\"}}{{.PuppetBinDir}}/{{end}}puppet agent --onetime --no-daemonize {{if ne .PuppetServer \"\"}}--server='{{.PuppetServer}}' {{end}}{{if ne .Options \"\"}}{{.Options}} {{end}}{{if ne .PuppetNode \"\"}}--certname={{.PuppetNode}} {{end}}{{if ne .ClientCertPath \"\"}}--certdir='{{.ClientCertPath}}' {{end}}{{if ne .ClientPrivateKeyPath \"\"}}--privatekeydir='{{.ClientPrivateKeyPath}}' {{end}}--detailed-exitcodes"`

**Comment by seanmalloy** [comment]
I think at a minimum this should get added to the official docs. I'll try to get a PR submitted with the doc updates later today.

I'm assuming this also affects the puppet-masterless provisioner.

**Comment by seanmalloy** [comment]
I submitted a PR #4388 to update the docs for the puppet-server provisioner.

I would also like to see if there is a way to update the puppet-server provisioner, so that it would be smart enough to run a slightly different command on Windows vs. Unix. I'll try to look into that in the near future.

**Comment by seanmalloy** [comment]
I closed PR #4388. I think I found a better solution.

I did a quick search through some of the code, and found that the chef-client provisioner has a configuration option called "guest_os_type" that can be set to unix or windows. I will try to add a similar option to the puppet-server provisioner.

@c22 would you be willing to test this if I write the code? All of my test machines are Linux. It might take me a few weeks to find the time to make the code changes, and I'm new to Go.

**Comment by c22** [comment]
@seanmalloy I'd be happy to help

**Comment by mwhooker** [comment]
@seanmalloy that's pretty close to how we prefer to do things. One thing to note is that terraform does this just about as well as we could hope, so that's the model to emulate. CF

* https://github.com/hashicorp/terraform/blob/master/builtin/provisioners/chef/resource_provisioner.go
* https://github.com/hashicorp/terraform/blob/master/builtin/provisioners/chef/linux_provisioner.go
* https://github.com/hashicorp/terraform/blob/master/builtin/provisioners/chef/windows_provisioner.go

**Comment by c22** [comment]
This particular issue was resolved with #5252
