### ISSUE TITLE
Allow resolving user variables inside the variables section

### ISSUE THREAD

**Issue by arcivanov** [hashicorp/packer#4387]
This relates to #4383

Allow the following to resolve the variables:

```
{
  "variables": {
    "aws_zone": "eu-west-2",
    "docker_repository_server": "123456.dkr.ecr.{{user `aws_zone`}}.amazonaws.com",
    "docker_login_server": "https://{{user `docker_repository_server`}}/",
    "docker_repository": "{{user `docker_repository_server`}}/repository_name"
  }
}
```

**Comment by rickard-von-essen** [comment]
Currently they are interpolated to `""` without an error.

`"docker_login_server" => "https:///",`

**Comment by SwampDragons** [comment]
This work has been completed in #7390; if anyone wants to try out a build of the branch, they're available on that PR.
