### ISSUE TITLE
provisioner/puppet: make execute_command variables available to extra_arguments

### ISSUE THREAD

**Issue by tb3088** [hashicorp/packer#4462]
extra_arguments is a perfect place to reference class variables but it's interpolated so early NULLs get substituted instead. Here is example:
`{{if ne ".ModulePath" ""}}--modulepath='{{.ModulePath}}:$basemodulepath'{{end}}`

The specific example is a result of Puppet's implementation choice whereby '--modulepath' obliterates all of the standard module paths and until such time as they implement an "additive" mode, the values have to be restored. Sure one could completely rewrite "execute_command" but why not just fix the problem?

Conceivably one could concoct an "execute_command" where one of the extra's is a subshell invocation of a command that looks something like
`"--modulepath=$( {{.PuppetBinDir}}/puppet config print modulepath --environment={{user `environment`}} )`

Early evaluation means PuppetBinDir would likewise been rendered as NULL.

**Comment by mwhooker** [comment]
it might be handy to have `extra_arguments` interpreted as a template, but I don't see a huge benefit to be had, when it's just as easy to override `execute_command`. If this is a common error as you say, it might be best to update the default `execute_command` to have the logic of adding the base module path. I'm not sure what that would look like, though, so a patch would have to come from the community.

There's a misunderstanding here in that we don't treat extra arguments as a template, and so we don't render it at all. Any `NULLs` you see are entirely coincidental.

**Comment by tb3088** [comment]
Packer assumes everything in a template is final and thus there is no alternative but to rewrite "execute_command", So instead of questioning packer's code behavior, the community has learned to just resort to the expedient hack. This is hardly the first case where the brittleness of Packer requires otherwise unnecessary workarounds.

I get NULLs because that's the string representative of trying to Interpolate.Render() an undefined object.
