### ISSUE TITLE
SSH handshake fails for 1&1 builder

### ISSUE THREAD

**Issue by pellepelster** [hashicorp/packer#4501]
When starting with the minimal template given in den 1&1 builder documentation:

```
{
   "builders":[
      {
         "type":"oneandone",
         "disk_size":"50",
         "image_name":"test5",
         "source_image_name":"ubuntu1604-64min",
         "ssh_username" :"root"
      }
   ]
}
```

the build fails with `Build 'oneandone' errored: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain`.
packer version is 0.12.2, a debug log of the packer run is available at https://gist.github.com/pellepelster/eae34cd7db80285452957b87926e3d59

**Comment by jasminSPC** [comment]
@pellepelster Sorry for the late reply
You need to add "ssh_private_key_file" in you config file.
```
{
   "builders":[
      {
         "type":"oneandone",
         "disk_size":"50",
         "image_name":"test_01",
         "source_image_name":"ubuntu1604-64min",
         "ssh_username" :"root",
        "ssh_private_key_file" : "/path/to/private/ssh/key"
      }
   ]
}
```

**Comment by mwhooker** [comment]
@jasminSPC please update the example to reflect the minimum template needed before marking this as resolved

**Comment by jasminSPC** [comment]
@mwhooker Sorry for the late reply I've just submitted a PR with updated docs.
