### ISSUE TITLE
Clearer communication on headless

### ISSUE THREAD

**Issue by lusis** [hashicorp/packer#453]
Spent about 30 minutes scratching my head trying to build a virtualbox image before I realized that the builder will fail if headless isn't explicitly disabled and you're building remotely:

```
==> virtualbox: Creating forwarded port mapping for SSH (host port 4382)
==> virtualbox: Starting the virtual machine...
==> virtualbox: Waiting 1m0s for boot...
==> virtualbox: Typing the boot command...
==> virtualbox: Error sending boot command: VBoxManage error: VBoxManage: error: Guest not running
==> virtualbox: Unregistering and deleting virtual machine...
==> virtualbox: Deleting output directory...
Build 'virtualbox' errored: Error sending boot command: VBoxManage error: VBoxManage: error: Guest not running
```

After adding `"headless":false`:

```
==> virtualbox: Creating forwarded port mapping for SSH (host port 4382)
==> virtualbox: Starting the virtual machine...
    virtualbox: WARNING: The VM will be started in headless mode, as configured.
    virtualbox: In headless mode, errors during the boot sequence or OS setup
    virtualbox: won't be easily visible. Use at your own discretion.
==> virtualbox: Waiting 1m0s for boot...
```

the box built fine. I don't know what the best option here is. I don't think the vboxmanage error makes it clear that the problem is not having a gui present.

**Comment by Ravenwater** [comment]
running into this issue now with packer 0.7.5, default and explicit setting of headless generates the same failure:

    virtualbox-iso: Downloading or copying: http://releases.ubuntu.com/12.04/ubuntu-12.04.5-server-amd64.iso
==> virtualbox-iso: Creating virtual machine...
==> virtualbox-iso: Creating hard drive...
==> virtualbox-iso: Creating forwarded port mapping for SSH (host port 3485)
==> virtualbox-iso: Starting the virtual machine...
    virtualbox-iso: WARNING: The VM will be started in headless mode, as configured.
    virtualbox-iso: In headless mode, errors during the boot sequence or OS setup
    virtualbox-iso: won't be easily visible. Use at your own discretion.
==> virtualbox-iso: Waiting 10s for boot...
==> virtualbox-iso: Typing the boot command...
==> virtualbox-iso: Error sending boot command: VBoxManage error: VBoxManage: error: Guest not running
==> virtualbox-iso: Unregistering and deleting virtual machine...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Error sending boot command: VBoxManage error: VBoxManage: error: Guest not running

As per website documentation, I am using this as template:
>: ~/packer$ cat precise_server.json
{
  "builders": [{
  "type": "virtualbox-iso",
  "guest_os_type": "Ubuntu_64",
  "iso_url": "http://releases.ubuntu.com/12.04/ubuntu-12.04.5-server-amd64.iso",
  "iso_checksum": "769474248a3897f4865817446f9a4a53",
  "iso_checksum_type": "md5",
  "ssh_username": "packer",
  "ssh_password": "packer",
  "ssh_wait_timeout": "30s",
  "headless":"true",
  "boot_command": [
"<esc><esc><enter><wait>",
"/install/vmlinuz noapic ",
"preseed/url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/preseed.cfg ",
"debian-installer=en_US auto locale=en_US kbd-chooser/method=us ",
"hostname={{ .Name }} ",
"fb=false debconf/frontend=noninteractive ",
"keyboard-configuration/modelcode=SKIP keyboard-configuration/layout=USA ",
"keyboard-configuration/variant=USA console-setup/ask_detect=false ",
"initrd=/install/initrd.gz -- <enter>"
  ],
  "shutdown_command": "echo 'packer' | sudo -S shutdown -P now"
  }]
}

Everything I try seems to go down the wrong path, so clearly I am not able to disambiguate the documentation, :-(

**Comment by devilldog** [comment]
same problem, if i change headless to false, the window opens for a second and still exits....
2015/04/22 08:46:20 packer-builder-virtualbox-iso: 2015/04/22 08:46:20 Executing VBoxManage: []string{"startvm", "packer-virtualbox-iso-1429706775", "--type", "gui"}
2015/04/22 08:46:21 packer-builder-virtualbox-iso: 2015/04/22 08:46:21 stdout: Waiting for VM "packer-virtualbox-iso-1429706775" to power on...
2015/04/22 08:46:21 packer-builder-virtualbox-iso: VM "packer-virtualbox-iso-1429706775" has been successfully started.
2015/04/22 08:46:21 packer-builder-virtualbox-iso: 2015/04/22 08:46:21 stderr:
2015/04/22 08:46:21 ui error: ==> virtualbox-iso: Error starting VM: VBoxManage error:
==> virtualbox-iso: Error starting VM: VBoxManage error:
2015/04/22 08:46:21 packer-builder-virtualbox-iso: 2015/04/22 08:46:21 Executing VBoxManage: []string{"storageattach", "packer-virtualbox-iso-1429706775", "--storagectl", "Floppy Controller", "--port", "0", "--device", "0", "--medium","none"}
2015/04/22 08:46:21 packer-builder-virtualbox-iso: 2015/04/22 08:46:21 stdout:
2015/04/22 08:46:21 packer-builder-virtualbox-iso: 2015/04/22 08:46:21 stderr:
2015/04/22 08:46:21 packer-builder-virtualbox-iso: 2015/04/22 08:46:21 Executing VBoxManage: []string{"storageattach", "packer-virtualbox-iso-1429706775", "--storagectl", "IDE Controller", "--port", "0", "--device", "1", "--medium", "nne"}
2015/04/22 08:46:21 packer-builder-virtualbox-iso: 2015/04/22 08:46:21 stdout:
2015/04/22 08:46:21 packer-builder-virtualbox-iso: 2015/04/22 08:46:21 stderr:
2015/04/22 08:46:21 ui: ==> virtualbox-iso: Unregistering and deleting virtual machine...
2015/04/22 08:46:21 packer-builder-virtualbox-iso: 2015/04/22 08:46:21 Executing VBoxManage: []string{"unregistervm", "packer-virtualbox-iso-1429706775", "--delete"}
==> virtualbox-iso: Unregistering and deleting virtual machine...
2015/04/22 08:46:21 packer-builder-virtualbox-iso: 2015/04/22 08:46:21 stdout:
2015/04/22 08:46:21 packer-builder-virtualbox-iso: 2015/04/22 08:46:21 stderr: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
2015/04/22 08:46:21 packer-builder-virtualbox-iso: 2015/04/22 08:46:21 Deleting floppy disk: /tmp/packer483834908
2015/04/22 08:46:21 ui: ==> virtualbox-iso: Deleting output directory...
==> virtualbox-iso: Deleting output directory...
2015/04/22 08:46:21 ui error: Build 'virtualbox-iso' errored: Error starting VM: VBoxManage error:
2015/04/22 08:46:21 Builds completed. Waiting on interrupt barrier...
2015/04/22 08:46:21 machine readable: error-count []string{"1"}
2015/04/22 08:46:21 ui error:
==> Some builds didn't complete successfully and had errors:
2015/04/22 08:46:21 machine readable: virtualbox-iso,error []string{"Error starting VM: VBoxManage error: "}
2015/04/22 08:46:21 ui error: --> virtualbox-iso: Error starting VM: VBoxManage error:
2015/04/22 08:46:21 ui:
==> Builds finished but no artifacts were created.
2015/04/22 08:46:21 waiting for all plugin processes to complete...
Build 'virtualbox-iso' errored: Error starting VM: VBoxManage error:

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Error starting VM: VBoxManage error:

2015/04/22 08:46:21 /appbin/ba/packer/packer-provisioner-shell: plugin process exited
2015/04/22 08:46:21 /appbin/ba/packer/packer-provisioner-shell: plugin process exited
2015/04/22 08:46:21 /appbin/ba/packer/packer-post-processor-vagrant: plugin process exited
2015/04/22 08:46:21 /appbin/ba/packer/packer-builder-virtualbox-iso: plugin process exited
==> Builds finished but no artifacts were created.

**Comment by devilldog** [comment]
running packer 0.7.5
