### ISSUE TITLE
packer validate doesn't catch json format errors

### ISSUE THREAD

**Issue by WeatherGod** [hashicorp/packer#4557]
I had a mistake in my json file, but validate never caught it, and `packer build` would proceed to use it, but never execute any provisioners.

- Packer version from `packer version`
Packer v0.12.2
- Host platform
linux-amd64
- Debug log output from `PACKER_LOG=1 packer build template.json`.
N/A
- The _simplest example template and scripts_ needed to reproduce the bug.
```
{
  "variables": {
    "access_key": "{{env `AWS_ACCESS_KEY_ID`}}",
    "secret_key": "{{env `AWS_SECRET_ACCESS_KEY`}}"
  },
  "builders": [{
    "type": "amazon-ebs",
    "access_key": "{{user `access_key`}}",
    "secret_key": "{{user `secret_key`}}",
    "region": "us-east-1",
    "source_ami": "ami-fce3c696,",
    "instance_type": "t2.micro",
    "ssh_username": "ubuntu",
    "ami_name": "packer-example {{timestamp}}"
  }]
}]    <----- This was extra and invalid

  "provisioners": [{
    "type": "shell",
    "inline": [
      "sleep 15",
      "sudo yum update -y"
    ]
  }]
}
```
The above is invalid json (it gets rejected by python's built-in json reader). But it seems that packer's json reader simply terminates the json object at that point and never sees the provisioners. Obviously the validation bug needs to be fixed, but perhaps a warning should be emitted that packer does not see any provisioners? I spent several days trying to figure out what was wrong with packer before noticing the mistake in the json.

**Comment by mwhooker** [comment]
I can reproduce, thanks for the report!

**Comment by Hashfyre** [comment]
Can confirm, this was an old issue we closed down internally.
https://github.com/hashicorp/packer/issues/4557

**Comment by Hashfyre** [comment]
@mwhooker If possible could you please assign this to me, I'd like to fix this. Kindly point out relevant docs/code snippets that the community follows.

**Comment by mwhooker** [comment]
@Hashfyre thanks for the offer. I think this is the solution

```diff
diff --git a/template/parse.go b/template/parse.go
index 779886d..532fff8 100644
--- a/template/parse.go
+++ b/template/parse.go
@@ -264,13 +264,13 @@ func (r *rawTemplate) parsePostProcessor(
 func Parse(r io.Reader) (*Template, error) {
        // Create a buffer to copy what we read
        var buf bytes.Buffer
-       r = io.TeeReader(r, &buf)
+       buf.ReadFrom(r)

        // First, decode the object into an interface{}. We do this instead of
        // the rawTemplate directly because we'd rather use mapstructure to
        // decode since it has richer errors.
        var raw interface{}
-       if err := json.NewDecoder(r).Decode(&raw); err != nil {
+       if err := json.Unmarshal(buf.Bytes(), &raw); err != nil {
                return nil, err
        }
```

Will ask the original author of the templating and see about merging this
