### ISSUE TITLE
Feature Request: Use AWS Discovered Credentials for Elevated User in PowerShell Provisioner

### ISSUE THREAD

**Issue by Linuturk** [hashicorp/packer#4566]
When building using the amazon-ebs builder you have the option of gathering the Administrator credentials directly from AWS. This allows for randomized passwords being assigned to the EC2 instance that's used as the packer target.

Using the AWS builder in this way means you can't use the `elevated_user` and `elevated_password` options for the PowerShell provisioner without preseeding a known admin user on the instance. I think if the `elevated_password` option is left blank, packer should be smart enough to use the password discovered from AWS instead of failing to run.

**Comment by ppandiya** [comment]
are there any workarounds for this issue ?

I am setting an Administrator password in bootstrap (Userdata) and using it in eleveated_password. But is there a way to revert it when i am done.... Because the instances i launch from this ami comes with the preset password which i used in userdata.

**Comment by SwampDragons** [comment]
I believe this was closed by https://github.com/hashicorp/packer/pull/5998
