### ISSUE TITLE
Salt provisioner for Windows VM running on Linux Host fails (path separator issues)

### ISSUE THREAD

**Issue by RiccardoBoettcher** [hashicorp/packer#4585]
When using the salt-masterless provisioner for a Windows target VM (on a linux host), the paths generated by the provisioner are not platform specific (for example mkdir command recevices `/srv/salt/states`, but should be `\srv\salt\states`.

Additionally the  *unix specific commands for directory and file creation/management are used on Windows. This is another source of trouble.

- version: packer v0.12.2
- Host platform: Linux / Fedora 25
- guest: Windows 8.1
- communicator: winrm
- builder virtualbox iso
- provisioner: salt-masterless

- Debug log output:
https://gist.github.com/RiccardoBoettcher/ed21d6f8b0fae658f04ec025be82eeb7

- template: see gist
Difficult to provide as providing a  packer based setup of Windows VM (using virtual box) requires a lot of setup effort. But this issues should be easy fixable by verifying the full-qualified path / files names being created a correct for all supported platforms. It should be possible to ensure this with tests.

Solution proposal:
The problem might by the use of `filepath.ToSlash()` instead of `filepath.FromSlash()`. The later will inject the OS specific path separator character.

**Comment by sjmorse** [comment]
I've also run into this issue, I've been looking at how this provisioner is handing its setup on the guest machine and how other provisioners have avoided this issue. It seems like we may be able to fix this by utilizing the guest_commands that have been already implemented. I'm taking a stab at integrating that with the existing provisioner.

**Comment by sjmorse** [comment]
I've dug further into the code, and tested some changes changes that would resolve the slashes, however the overall problem with this provisioner is that it really wasn't written to work with windows. All the commands in this provisioner are unix specific, and would either require having cygwin tools on the path or be refactored to add native commands from the guest_commands package. I've tossed my changes realizing the refactor is probably what this provisioner needs to make it work native with windows, given salt is suppose to be the more windows friendly provisioner. Probabaly needs to get more unit test coverage before a refactor is undertaken.

**Comment by SwampDragons** [comment]
You're probably right about the refactor and the unit tests; this is likely going to be a big process. PRs are always welcome.

**Comment by nywilken** [comment]
Hello folks, thanks for opening up this issue. Apologies that we've not had the chance to dive further into this issue. If you've managed to resolve your problem we encourage you to leave comment for others who may experience this issue in the future.

With that said, this is one of our community maintained plugins, which we have recently flagged as [unmaintained](https://github.com/hashicorp/packer/blob/master/README.md#unmaintained-plugins). If you are interested in contributing or taking ownership of this plugin, please reach out to us at packer@hashicorp.com.
