### ISSUE TITLE
Feature Request: aws-ebs builder vpc_tag and subnet_tag

### ISSUE THREAD

**Issue by dnABic** [hashicorp/packer#4586]
For amazon-ebs builder, it would be nice to have parameter _vpc_tag_ and _subnet_tag_, as an alternative to the _vpc_id_ and _subnet_id_, respectively.

Then instead of 

```
  "builders" : [{
    "type": "amazon-ebs",
...
    "vpc_id" : "vpc-12345",
    "subnet_id" : "subnet-54321",
...
  }],
```

there will be something like this:

```
  "builders" : [{
    "type": "amazon-ebs",
...
    "vpc_tag" : {
      "name": "bar",
      "value": "foo"
    },
    "subnet_tag" : {
      "name": "hocus",
      "value": "pocus"
    }, 
...
  }],
```

I am aware that for vpc_id is not needed to hardcode the value and instead can be used something like this:
```
"vpc_id": "{{ env `VPC_ID`}}",
 "subnet_id": "{{ env `SUBNET_ID`}}"
```

but still, in that case vpc_id still needs to come from somewhere. 

As I create ami in different accounts and regions, I though it would be handy to have proposed parameters, where in each amazon account and/or region I can use the same tag for vpc and subnet.

If this makes sense to you, I would be happy to work on it myself and do PR when it's "done".

**Comment by rickard-von-essen** [comment]
Sounds nice, but there is a few quirks. First of all this must fail if not exactly 1 is the result of the filter. And it should allow multiple tags.

**Comment by dnABic** [comment]
Roger that.

**Comment by SwampDragons** [comment]
I've attached binaries of a branch that will add this feature over at #6374; care to try the build and let me know if it suits your needs?
