### ISSUE TITLE
getting-started/remote-builds.html.md - can't be completed as written

### ISSUE THREAD

**Issue by jason-azze** [hashicorp/packer#4633]
- Packer version from `packer version`
Packer v0.12.3
- Host platform
Ubuntu 16.04.2 LTS

I am a new Packer user working through the "Getting Started" guide. The Remote Builds section needs some updates.

1. The instructions say to run `packer push -create example.json`. But this gives the warning `The '-create' option is now the default and is longer used. It will be removed in the next version.`
2. After issuing the `push` command, the upload fails with `Error starting upload: upload: authentication failed`.  This makes sense, otherwise anyone who knew my username could push to my account. With some research, I created a token on Atlas and used the `token=` parameter, but this results in:

`This feature requires Vagrant Enterprise or Terraform Enterprise. Please contact sales@hashicorp.com to start or extend your trial.`

**Comment by SwampDragons** [comment]
@jason-azze did you ever figure this out?

**Comment by jason-azze** [comment]
@SwampDragons I'm not sure I understand your question. In this issue I am reporting a "bug" that is just some stale documentation that needs to be freshened. And in the case of item 2 above, a clarification should be added telling the user they must create a token on Atlas as well as start a trial for one of the Enterprise products.

**Comment by SwampDragons** [comment]
Sorry for being unclear!  I was just not sure from your issue whether you had managed to get it working and were just reporting confusing docs, or whether you had never gotten packer push to behave as expected. Thanks for the clarification :)
