### ISSUE TITLE
Exported VM is missing primary disk and SATA Controller

### ISSUE THREAD

**Issue by jchodakowski** [hashicorp/packer#4637]
Using virtualbox-iso builder, I am building a two disk VM with boot and main system on /dev/sda1 and /dev/sda2 and then /dev/sdb1 as a large LVM volume with various logical volumes mounted at various places on the file system. The disk is added using vboxmanage commands, and the build works as expected. In VirtualBox, you can inspect the VM and it has all the parts as described in the json template. Once the export happens however, the SATA controller is missing, as is the first of the two disks (sda). The second disk (sdb) is exported with the machine which, once re-imported has only an IDE disk controller, one disk, and won't boot (missing the system). 
- Packer version: 0.12.3
- Host platform: Windows 10
- Guest platform: Ubuntu 14.04
- Debug log output: https://gist.github.com/jchodakowski/034b7961ab0b6162a1ff983a5f68e8fc
- Template: https://gist.github.com/jchodakowski/1b718595be804aa07ddadbfc220749d8
- Additional script 1 (ubuntu-14.04.cis.cfg [preseed]): https://gist.github.com/jchodakowski/bec5a86a8b6b1aedb72765ee9af2d328 
- Additional script 2 (preseed_cfg): https://gist.github.com/jchodakowski/1f4ff13aa6a92926f6dbd5df2971b6a4
- Additional script 3 (lvm.sh): https://gist.github.com/jchodakowski/3ccf5fc96e6e78362ade56f7fe0dcf4b
- Additional script 4 (nessus.sh): 
  Include these in your gist https://gist.github.com

**Comment by jchodakowski** [comment]
Because I have to keep my own work moving forward, I just re-introduced a chef provisioning block. The cookbook(s) that are applied are for CIS compliance and while I need to run down them, head to toe to be sure, I don't think that there is anything that alters the VM's core configuration. So, with that said, with the chef-server provision block re-added, the export works fine. I'll perform some more testing either this weekend or early next week to confirm specific behaviors.

**Comment by sylviamoss** [comment]
Hi @jchodakowski! It's been a while since this was opened, is this still a problem for you?
