### ISSUE TITLE
vsphere post processor lacks roles documentation

### ISSUE THREAD

**Issue by jeroenjacobs79** [hashicorp/packer#4658]
The only way I can get the vSphere post-processor to work, is when I add the configured user to the administrators group.

This will cause lots of red flags in a security audit. Please include in the documentation which vSphere roles by Packer are required so we can fine-tune access.

I tried the recommendations here: https://github.com/TotalJobsGroup/Packer/blob/master/README.md

But it seems this is not complete, as I still get permissions in Packer when I only enable those roles.

**Comment by marema31** [comment]
The vsphere post processor use only ovftool and therefore needs the same privileges than this tool.
We created a role at work specific to this post processor and the ability to change configuration and mark the imported VM as a template with shell-local postprocessor running govc. 
For Vsphere 5.5 the role has the following privileges:

- Datastore.AllocateSpace
- Host.Config.AdvancedConfig
- Host.Config.NetService
- Host.Config.Network
- Network.Assign
- System.Anonymous
- System.Read
- System.View
- VApp.Import
- VirtualMachine.Config.AddNewDisk
- VirtualMachine.Config.AdvancedConfig
- VirtualMachine.Inventory.Delete
- VirtualMachine.Provisioning.MarkAsTemplate

And this role must be authorized on the:
- Cluster of the host
- The destination folder (not on Datastore, on the Vsphere logical view)
- The network to be assigned
- The destination datastore.

This right may be more than really needed but more IT-Security compliants.

**Comment by marema31** [comment]
@jeroenjacobs1205 does this list had helped you ?

@mwhooker I can propose a PR on the documentation, but I'm not able to test all vsphere version for reducing this list (I think there is 2 or 3 privileges that are not needed in current state of the post-processor, but this list will be correct if #4110 is integrated one day).

**Comment by mwhooker** [comment]
>  I can propose a PR on the documentation, but I'm not able to test all vsphere version for reducing this list

I think if you're able to remove the few unneeded permissions from the list, this would be a great addition to the docs. Even if it's not 100% accurate, it's a good start, and we can update it later. If you can find the accurate list for 5.5, which can just say that the permissions listed are for version 5.5, and other versions may have different requirements.

**Comment by jeroenjacobs1205** [comment]
@marema31 Yes, that list was very helpful. Thanks! :-)

**Comment by juliansotoca** [comment]
I had to add new privileges to the list provided by @marema31 to use the vsphere-template post-processor with packer 1.3.2 and vsphere 6.0. Those privileges where:
- VirtualMachine.Inventory.Register
- VirtualMachine.Inventory.Unregister
