### ISSUE TITLE
Feature Request: add option to run chef-client using elevated shell

### ISSUE THREAD

**Issue by jugatsu** [hashicorp/packer#4661]
This feature was discussed here https://github.com/mitchellh/packer/issues/3117. Make it seperate feature request.

This feature greatly improve packer workflow in windows world as WinRM has some nasty limitations: such as issues with installing windows updates, sql server, etc.

**Comment by bodgit** [comment]
I can probably do this quickly enough however I have no way to test this easily.

There seems to be a few places where both `knife` and `chef-client` are invoked. Which commands actually need to run as elevated here? Is it literally just the main `chef-client` invocation in `executeChef()`?

**Comment by bodgit** [comment]
I've updated the PR #7078 with similar changes to the `chef-client` provisioner. Currently I'm only invoking the main `chef-client` binary as elevated.

**Comment by SwampDragons** [comment]
Anyone willing to test this PR out for chef?
