### ISSUE TITLE
file provisionner not performed with powershell provisionners 

### ISSUE THREAD

**Issue by nvideau** [hashicorp/packer#4668]
Hello, 

While using packer to deploy a windows 2016 server,with vmware-iso if I use a file provisionner before a powershell provisionner, the file provisionner is not performed.

However when removing the powershell provisionner the file provisionner is performed.

packer version: 0.12.3 working on windows  10

**Comment by rickard-von-essen** [comment]
Please supply the information requested in the issue template:
- Packer version (`packer version`)
- Host platform (`uname -a` etc.)
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a [gist](https://gist.github.com).
- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your [gist](https://gist.github.com).

Reopen when you supplied the required information.

**Comment by nvideau** [comment]
Packer version : 0.12.3
Host platform : windows 10 Entreprise, 10.0.14393 
Debug log : https://gist.github.com/nvideau/a51fb63b04be50ba35ce1b48647c37f6
The simplest example template and scripts needed to reproduce the bug : https://gist.github.com/nvideau/d53ca258d6317d6b5d07162564e7ddcc

**Comment by nvideau** [comment]
@rickard-von-essen I can't reopen myself

**Comment by rickard-von-essen** [comment]
We need a _full_ debug log.

**Comment by SwampDragons** [comment]
If your problem is that you're seeing "provisioning with shell script" in the logs, that's just copypasta from when the provisioner was originally written: https://github.com/hashicorp/packer/blob/3eeb72289718fea9cac9a30be6a770de1cf178a5/provisioner/powershell/provisioner.go#L245

I'll fix the typo.
