### ISSUE TITLE
OpenStack: Unclear error message when launching source instance fails

### ISSUE THREAD

**Issue by tokiwinter** [hashicorp/packer#4669]
Hello,

I may be missing something but I don't think I am from the documentation that I've found. I am attempting to provision an openstack image in Rackspace using the following template:
```
{
    "builders": [
        {
            "flavor": "2",
            "image_name": "Toki Packer Test {{ timestamp }}",
            "source_image": "35c672b3-85ab-4d8f-8eec-fd2de2e44b94",
            "ssh_keypair_name": "packer-toki",
            "ssh_private_key_file": "packer-toki.key",
            "ssh_username": "root",
            "type": "openstack",
            "openstack_provider": "rackspace",
            "networks": [
                "<network-uuid-goes-here>"
            ]
        }
    ],
    "provisioners": [
        {
            "script": "test-provisioner.sh",
            "type": "shell"
        }
    ]
}
```
I have the appropriate environment variables set:
```
$ env | grep OS_ | cut -d = -f 1
OS_PROJECT_ID
OS_REGION_NAME
OS_PASSWORD
OS_AUTH_URL
OS_USERNAME
```
Authentication appears to be no issue anyway, as flavor validation succeeds during the build run. However, I am receiving the following error:
```
$ packer build base.json
openstack output will be in this color.

==> openstack: Discovering enabled extensions...
==> openstack: Loading flavor: 2
    openstack: Verified flavor. ID: 2
==> openstack: Launching server...
==> openstack: Error launching source server: Invalid request due to incorrect syntax or missing required parameters.
Build 'openstack' errored: Error launching source server: Invalid request due to incorrect syntax or missing required parameters.

==> Some builds didn't complete successfully and had errors:
--> openstack: Error launching source server: Invalid request due to incorrect syntax or missing required parameters.

==> Builds finished but no artifacts were created.
```
I do not see anything of note if I enable debug logging, or set PACKER_LOG=1.
```
$ packer --version
0.12.3
```
Please advise.

I have tested manual server creation using the openstack client, and it works fine:
```
$ openstack server create --flavor 2 --image 35c672b3-85ab-4d8f-8eec-fd2de2e44b94 --nic net-id=<network-uuid-goes-here> toki-test-os-client
```

**Comment by tokiwinter** [comment]
Solved this - was due to not having the appropriate public key configured within openstack itself (i.e. in the rackspace region).
```
$ openstack keypair list -c Name -f value
packer-toki
```
However, is there any way to make the error messages outputted by the packer builder slightly more targeted? It is close to impossible to troubleshoot.

The openstack cli will output a relevant error in this particular case (key pair not being present):
```
$ openstack server create --flavor 2 --image 35c672b3-85ab-4d8f-8eec-fd2de2e44b94 --nic net-id=<network-uuid-goes-here> --key-name fookey toki-test-os-client
Invalid key_name provided. (HTTP 400) (Request-ID: req-82a93eef-7b2f-4de1-afab-2bbc9bd707b2)
```

**Comment by rickard-von-essen** [comment]
I think we just print the error return by the OpenStack lib. I'll see if there is some more info to display.

Yesterday I got the exact same error when trying to use a image that doesn't exist as source. 

Worst case we have to verify that referenced resources exists.

**Comment by bobbydeveaux** [comment]
I had this issue with regard to the security group too.

```
"builders": [
    {
      "type": "openstack",
      "image_name": "CoreOS-Alpha-Docker-17-05_2",
      "source_image": "8e892f81-2197-464a-9b6b-1a5045735f5d",
      "flavor": "c46be6d1-979d-4489-8ffe-e421a3c83fdd",
      "use_floating_ip": true,
      "floating_ip_pool": "internet",
      "ssh_username": "core",
      "ssh_pty" : true,
      "security_groups": "example_secgroup_1"
    }
  ],
```

If security group name is invalid, it just says "Invalid request due to incorrect syntax or missing required parameters. Build 'openstack' errored: Error launching source server: Invalid request due to incorrect syntax or missing required parameters."

It should specify that it was an invalid security group, no? :)

**Comment by rickard-von-essen** [comment]
@bobbydeveaux haven't hade any time to look any further into this. It depends on what error message the API and gophercloud library returns. And maybe we could verify some resources exists before trying to use the. The drawback of that is it might require more permissions than not doing it. 

If you can add more details such as the actual error returned by the API it would be awesome.

**Comment by jdanekrh** [comment]
I've gotten this by specifying OpenStack image name in "source_image" key, instead of using the correct "source_image_name" key. Changing the key name fixed the error.

**Comment by rickard-von-essen** [comment]
Closing this in favour of #5466 which has a clear analysis.

**Comment by askb** [comment]
I had the exact same issue, with some of the templates having incorrect `source_image_name` while pointing to the image UUID, which is incorrect. 

There packer error messages are not very useful, even with `-debug` or setting `export PACKER_LOG=debug`.

> ==> public_cloud: Launching server...
> ==> public_cloud: Error launching source server: Invalid request due to incorrect syntax or missing required parameters.
> ==> public_cloud: Terminating the source server:  ...
> ==> public_cloud: Error terminating server, may still be around: Resource not found
> ==> public_cloud: Deleting temporary keypair: packer_59f6eea5-d763-4e73-609c-369cc2073b51 ...
> Build 'public_cloud' errored: Error launching source server: Invalid request due to incorrect syntax or missing required parameters.

**Comment by rickard-von-essen** [comment]
@askb could you test the patch referenced in #5466
