### ISSUE TITLE
For builders: Derive vpc_id from subnet_id

### ISSUE THREAD

**Issue by eherot** [hashicorp/packer#4693]
Subnets are VPC-specific. If `subnet_id` is specified, it should not be necessary to specify the `vpc_id`.

**Comment by mwhooker** [comment]
This should be a good entry point for anyone looking to contribute to the project. We can use [ec2.DescribeSubnets](http://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#EC2.DescribeSubnets) to get the VPC ID.

**Comment by optimisticanshul** [comment]
@mwhooker i will do if it's ok with you :)

**Comment by mwhooker** [comment]
@optimisticanshul sounds good!
