### ISSUE TITLE
virtualbox-iso builder: Explicitly configuring a WinRM port should imply "ssh_skip_nat_mapping"

### ISSUE THREAD

**Issue by frischke** [hashicorp/packer#4702]
Packer version: 0.12.3

When I was trying to build a Windows Vagrant box using [Matt Wrock's Packer templates](https://github.com/mwrock/packer-templates) I came across an issue regarding the WinRM port settings. His VirtualBox templates explicitly set a WinRM port and configure a corresponding port forwarding rule for VirtualBox (see e.g. the [Windows Server 2012 config](https://github.com/mwrock/packer-templates/blob/334f248371a8191f97d640066ec5c5aad2a740f2/vbox-2012r2.json)). Packer's virtualbox-iso builder however, overwrites the explicitly configured port with the one it discovered in `StepForwardSSH`, unless `ssh_skip_nat_mapping` is also set to `true`.

This behavior was unexpected since my assumption was that the explicitly configured port would take precedence over the dynamically selected default port. Also the solution - setting `ssh_skip_nat_mapping` to `true` - was not obvious to me without reading the source code. (Note that the official [documentation for ssh_skip_nat_mapping](https://www.packer.io/docs/builders/virtualbox-iso.html#ssh_skip_nat_mapping) does not state that the setting also applies to `winrm_port`.)

I would suggest to update the documentation or change the behavior such that an explicitly configured port takes precedence over the dynamically discovered one.

Relevant code references in Packer:
* [builder/virtualbox/common/step_forward_ssh.go, lines 30 ff.](https://github.com/mitchellh/packer/blob/v0.12.3/builder/virtualbox/common/step_forward_ssh.go#L30): Unless `ssh_skip_nat_mapping` is `true`, tries to discover a port and if found, configures port forwarding on the vbox vm. The discovered port is stored in the StateBag under the `"sshHostPort"` key.
* [builder/virtualbox/common/ssh.go, lines 16 ff.](https://github.com/mitchellh/packer/blob/v0.12.3/builder/virtualbox/common/ssh.go#L16): Function that fetches port number from the StateBag.
* [builder/virtualbox/iso/builder.go](https://github.com/mitchellh/packer/blob/v0.12.3/builder/virtualbox/iso/builder.go#L246): References above function for determining the WinRMPort.
* [helper/communicator/step_connect_winrm.go, lines 100 ff.](https://github.com/mitchellh/packer/blob/v0.12.3/helper/communicator/step_connect_winrm.go#L100): Reads the winrm port from config, but then overwrites it with the return value of `WinRMPort`.

**Comment by mwhooker** [comment]
agreed, we should probably clean up the documentation around this a little bit. I also think providing a warning or something if you specify a winrm/ssh port but don't turn off nat mapping
