### ISSUE TITLE
Add ability to push to Artifactory/JFrog repository.

### ISSUE THREAD

**Issue by madelaney** [hashicorp/packer#4703]
We'd/I like to use Artifactory to host our private docker containers. Looking at the `docker-push` post processor command, it would be nice of we could give a URL for our repository. I believe this would be akin to the `repository` property from the `docker-tag` post processor command.

**Comment by mwhooker** [comment]
What happens when you just fill in the artifactory information in the `docker-push` post processor? ie 

```
login (boolean) - Defaults to false. If true, the post-processor will login prior to pushing. For log into ECR see ecr_login.

login_email (string) - The email to use to authenticate to login.

login_username (string) - The username to use to authenticate to login.

login_password (string) - The password to use to authenticate to login.

login_server (string) - The server address to login to.
```

**Comment by rickard-von-essen** [comment]
This already works unless Artifactory do something weird.

**Comment by SwampDragons** [comment]
Closing since this has been inactive and unresponded-to for a couple years.
