### ISSUE TITLE
Packer and the Hasicorp Ecosystem image way to wide

### ISSUE THREAD

**Issue by Noah-Huppert** [hashicorp/packer#4711]
The image showing how Packer integrates with other Hashicorp tools is way to wide and overflows uglily.

[Page URL](https://www.packer.io/intro/hashicorp-ecosystem.html)
Chrome: 57.0.2987.98
OS: 4.9.11-1-ARCH

**Comment by mwhooker** [comment]
lol, way too wide. thanks for opening an issue!

**Comment by mwhooker** [comment]
git bisect identifies f6549e0e26fd19cce47a2eacd005f6907839fa75 as the bad commit. Any ideas @jasoncostello?

**Comment by sethvargo** [comment]
Hey @Noah-Huppert 

Thank you for opening an issue. We are actually in the midst of a very large overhaul to the Packer website, and this will be fixed in the process. Let's leave this open in the meantime, but I don't expect we'll fix it, since the new site is about to drop.

**Comment by Noah-Huppert** [comment]
Hot damn guys. Nicely done 🔥
