### ISSUE TITLE
Bastion host does not work with ssh agent when the key has a passphrase

### ISSUE THREAD

**Issue by fields** [hashicorp/packer#4732]
When trying to use a bastion host to make an image in a private subnet on aws, I get the following error if my private key file has a passphrase:

```
==> amazon-ebs: Error waiting for SSH: Error configuring bastion: Failed to read key '/path/to/key.pem': password protected keys are
==> amazon-ebs: not supported. Please decrypt the key prior to use.
```

This error persists even if my key is loaded into my ssh agent.

Is there a way to get the bastion connection to use the ssh agent with the decrypted key?

**Comment by rickard-von-essen** [comment]
I'll submit a PR for this today or tomorrow.

**Comment by rickard-von-essen** [comment]
@yfronto It would be awesome if you could test this with your setup. 👐
