### ISSUE TITLE
Feature Request: (aws builders) tag instance on creation

### ISSUE THREAD

**Issue by consultantRR** [hashicorp/packer#4746]
Now that EC2 supports [adding tags on creation for instances](https://aws.amazon.com/blogs/aws/new-tag-ec2-instances-ebs-volumes-on-creation/), it would be really great if Packer could be enhanced to support this for `run_tags` rather than adding these tags after the instance has been created (as has always been necessary in the past, due to AWS limitations).

One reason this would be great is that it would allow for more sophisticated IAM policies around tag enforcement on instances that Packer creates.

**Comment by mwhooker** [comment]
👍 sounds like a great idea. This would also be a good project for anyone new looking to contribute to packer

**Comment by barundel** [comment]
Hey

I am starting to do some stuff with IAM to mandate tags before an instance can be created:

Example IAM:

`
      "Condition": {
        "StringEquals": {
          "aws:RequestTag/Team": "TeamName",
        "StringLike": {
          "aws:RequestTag/Client": "*",
          "aws:RequestTag/Contact": "*",
          "aws:RequestTag/Name": "*",
          "aws:RequestTag/Owner": "*",
          "aws:RequestTag/Project": "*",
          "aws:RequestTag/Role": "*"
        }
      }
`

This policy doesn't seem to work with packer run_tags currently i.e. users get an "UnauthorizedOperation status code 403" error. 

It would be nice if it could use the new tagging method soon ;)

**Comment by Spenser309** [comment]
Hey,

Just FYI, I'd really like to see this implemented as well.  My company doesn't allow createTags for all users and I had to ask for additional permissions to get the access I need to run packer.

Spenser
