### ISSUE TITLE
vmware-iso builder is not calling the ovftool with absolute target path

### ISSUE THREAD

**Issue by relaxdiego** [hashicorp/packer#4763]
Packer version from `packer version`
Packer v1.1.0-dev

Packer always calls ovftool with a relative target path despite output_directory being an absolute path. This line https://github.com/hashicorp/packer/blob/v1.0.0/builder/vmware/iso/step_export.go#L64 does not include the outputDir when creating the path.

**Comment by mwhooker** [comment]
think this is a dupe of #3896

thanks!

**Comment by mwhooker** [comment]
If you wanted to test #4592 I think that should work for you

**Comment by relaxdiego** [comment]
Thanks @mwhooker! I just left a comment in that issue.
