### ISSUE TITLE
Mis-spelling in output...

### ISSUE THREAD

**Issue by wickedviking** [hashicorp/packer#4767]
==> hyperv-iso: Gracefully halting virtual machine...
==> hyperv-iso: Waiting for vm to be powered down...
==> hyperv-iso: Unmount/delete secondary dvd drives...
==> hyperv-iso: Unmount/delete Integration Services dvd drive...
==> hyperv-iso: Unmount/delete os dvd drive...
==> hyperv-iso: Delete os dvd drives controller 0 location 1 ...
==> hyperv-iso: Unmount/delete floppy drive (Run)...
==> hyperv-iso: Exporting vm...
==> hyperv-iso: Compacting disks...
==> hyperv-iso: Coping to output dir...

^^^ Coping or Copying?

packer -v 1.0.0 RC3 on Windows 10, used the pre-built binary.

**Comment by mwhooker** [comment]
fixed, thanks!
