### ISSUE TITLE
Issue with boot command scan codes in VirtualBox

### ISSUE THREAD

**Issue by thereverendtom** [hashicorp/packer#4769]
I am trying to run a packer build using Packer v1.0.0 and VirtualBox v5.1.18r114002 on CentOS 7, but I am getting the attached output. The build works fine when running on my Mac OSX laptop, but fails on our CentOS servers. I have the exact same versions of Packer and VirtualBox running on both systems. The boot command in my JSON file is as follows:

```json
"boot_command" : [
  "<tab> text ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/ks.cfg<enter><wait>"
]
```

```
==> virtualbox-iso: Error sending boot command: VBoxManage error: VBoxManage: error: Could not send all scan codes to the virtual keyboard (VERR_PDM_NO_QUEUE_ITEMS)
==> virtualbox-iso: VBoxManage: error: Details: code VBOX_E_IPRT_ERROR (0x80bb0005), component KeyboardWrap, interface IKeyboard, callee nsISupports
==> virtualbox-iso: VBoxManage: error: Context: "PutScancodes(ComSafeArrayAsInParam(saScancodes), &codesStored)" at line 345 of file VBoxManageControlVM.cpp
```

[packer_output.txt](https://github.com/hashicorp/packer/files/900945/packer_output.txt)

**Comment by rickard-von-essen** [comment]
Most likely your install of VirtualBox is a bit broken.

Could you try and manually launching a non headless VM and try to send keyboard scancodes to it with:
```
VBoxManage controlvm <vmname> keyboardputscancode 10
```

It should start printing `qqqqqq...`

**Comment by thereverendtom** [comment]
A non headless VM requires a GUI, right? The server I am running VBoxManage on does not have a GUI installed, so I don't believe I can start a non headless VM. When I try to start the VM, I get the following error:

[~]$ vboxmanage startvm packer-virtualbox-iso-1491429611
Waiting for VM "packer-virtualbox-iso-1491429611" to power on...
VBoxManage: error: The virtual machine 'packer-virtualbox-iso-1491429611' has terminated unexpectedly during startup because of signal 6
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine

**Comment by rickard-von-essen** [comment]
Reinstall VirtualBox

**Comment by thereverendtom** [comment]
I already tried that twice. I even tried downgrading to 5.0, but got the same error.

**Comment by rickard-von-essen** [comment]
If you can't even run VirtualBox, there is nothing Packer can do. I recommend that you try the e-mail list for help or some VirtualBox forum. 

You can try and install enough so you can run VirtualBox with head and use ssh + X-forwarding to get the GUI on another computer.

**Comment by localghost** [comment]
I had the same issue (CentOS 7.3 minimal, VirtualBox 5.1.22, Packer 1.0.0). For me it helped to install `libxkbcommon-x11` package. Additionally, I applied workaround suggested [here](https://github.com/hashicorp/packer/issues/4309#issuecomment-268623867) - to not send boot command to quickly.

**Comment by jboero** [comment]
Hi just an update on this one in case someone else comes across it.  This can happen if you're using two parallel builders at once (Qemu + VirtualBox for example).  The first one that starts grabs the KVM hardware acceleration control and then the second one has an error.  It may look like you don't have virtualization support.  Then you stop the Packer build and try yourself - it runs fine which is confusing.

In order to use multiple hypervisors at once you can try to ensure only one of them uses KVM.  Qemu features the "accelerator" option which defaults to KVM but you can set to "none" for software virtualization.  Now they can both run at once even if one is a bit slower.
