### ISSUE TITLE
Ability to have Packer copy a pre-created AMI to other regions 

### ISSUE THREAD

**Issue by afaleti** [hashicorp/packer#4771]
I used packer to build an encrypted Ubuntu AMI in us-east-1 and copied to 3 regions but I mistakenly left out eu-west-1 ; if I rerun my build with an updated template to copy to eu-west-1 it would
by default copy to the build region us-east-1 which I do not want.

Basically I need to run packer build copy to a new region where I am but not copy to the build region.

Notes:
I have many accounts and I build in exclusively us-east-1

FOR FEATURES:

Ability to have Packer copy a pre-created Encrypted AMI to other regions. 
Packer already has the built in capability to copy and encrypt at the target region.

**Comment by rickard-von-essen** [comment]
I'll say this is not within scope. You can easily use the aws-cli for this.
