### ISSUE TITLE
Packer changes hostname on arch linux

### ISSUE THREAD

**Issue by ChrisFernandez** [hashicorp/packer#4775]
Hello,
  This was driving me a bit crazy for a bit.. I am building an ids and took me a while so figure out that the hostname of the image has the hostname of the network were I build the img(another subnet all together) example 
```
hostname<enter>
ip-10-121-1-1
my promp:
root@ip-10-121-1-1
```

this is wrong so this is somehow getting put there when I run packer to create the img..
it does not happen with our Ubuntu images on AWS only with our Arch Linux images.
Any idea why can this be?

**Comment by rickard-von-essen** [comment]
Most likely `cloud-init`or the lack of it. Packer doesn't do anything with the OS for you.

---

Please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._
