### ISSUE TITLE
Support FTP for ISO URLs

### ISSUE THREAD

**Issue by juliandunn** [hashicorp/packer#478]
Some distributions (FreeBSD) only provide FTP URLs to their ISOs and Packer doesn't seem to support this:

``` shell
$ packer validate freebsd-9.1-amd64.json
Template validation failed. Errors are shown below.

Errors validating build 'virtualbox'. 1 error(s) occurred:

* Failed to parse iso_url 1: Unsupported URL scheme: ftp

Errors validating build 'vmware'. 1 error(s) occurred:

* Failed to parse iso_url 1: Unsupported URL scheme: ftp
```

**Comment by arizvisa** [comment]
PR #2906 uses jlaffaye's ftp library which is pretty much #1 at http://golanglibs.com. However, if the policy is to re-implement all the protocols that golang doesn't have a stdlib for or that packer doesn't already include, I suppose I can re-invent ftp for that PR.

**Comment by WillSquire** [comment]
+1. A stumbling block at the first hurdle for me :/

**Comment by rrzaripov** [comment]
+1 good feature

**Comment by vtolstov** [comment]
+1, but i'm prefer http it faster then ftp

**Comment by chrisandchris** [comment]
+1
