### ISSUE TITLE
file provisioner `stats` sources too early

### ISSUE THREAD

**Issue by faxal** [hashicorp/packer#4785]
I have a `shell-local` provisioner that creates a file which later get uploaded to image by `file` provisioner. But `file` provisioner `stats` the source files in prepare stage, so it fails without building the image. 

Does it make sense to move the check to actual Provision stage? or is there a way to do what I described.

**Comment by faxal** [comment]
Seems it does `stat` in provision stage too, maybe it is there in prepare stage to fail early. Maybe it is good to have a flag to defer the check only during provision only.

**Comment by mwhooker** [comment]
This is so we can make sure it will work before running any code. What we suggest doing is use the `file` provisioner to upload a directory, and put the file the `shell-local` provisioner generates in that directory.

This has come up a few times and I don't think we're going to change the behavior right now, so going to close.
