### ISSUE TITLE
amazon-instance requires x509 keys, but seems to be deprecated

### ISSUE THREAD

**Issue by carmat88** [hashicorp/packer#4786]
Hello Folks!

we are experiencing some difficulties trying to work with the Amazon builder called `amazon-instance`. Based on the [online documentation](https://www.packer.io/docs/builders/amazon-instance.html), both the `x509_cert_path`, `x509_key_path` 
  and `x509_upload_path` fields are required; however in this past reported and [closed issue](https://github.com/hashicorp/packer/issues/517) seems that those fields were deprecated, but not sure if they have been changed into "optional" or even removed for this particular builder (maybe only for amazon-ebs` ?). In our AWS account it appears to not be possible to generate a X509 certificate under the IAM section. Of course both the validation and building fail because of the missing required fields.

Here are the main requested information:

- Packer version: 0.11.0
- Host Platform: MacOS Sierra (local machine), AWS (main provider)
- Debug Log Output + Template and Files being used: https://gist.github.com/carmat88/d9f1b4bef41a48184ab8e867e38e7160

Thank you for your help and attention. Cheers.

**Comment by mwhooker** [comment]
thanks! Will need to look into this to make sure, but I assume these can just be removed from the docs.

Thanks!

**Comment by carmat88** [comment]
Hey @mwhooker ! Thanks a lot for getting back to us. Just as extra details for you guys, I've done the same test by using the latest version of packer (1.0.0) this time. Unfortunately the error is still the same while validating or building the configuration files:

```
Template validation failed. Errors are shown below.

Errors validating build 'amazon-instance'. 2 error(s) occurred:

* x509_cert_path is required
* x509_key_path is required
```

and

```
amazon-instance output will be in this color.

2 error(s) occurred:

* x509_cert_path is required
* x509_key_path is required
```
So given that even with the latest version of packer such certificate's details are mandatory when using the above mentioned builder, I'm (maybe wrongly) deducing that it might not be only a documentation update. In case it was required indeed to enter the X509 fields, then it is not clear where exactly get them in AWS, not even under the IAM section.

Maybe it would be possible by now to just using `access_key` and `secret_key` to call the API for building an instance with `amazon-instance`, like when using the most common `amazon-ebs` packer builder ?

Cheers!

**Comment by mcapuccini** [comment]
@mwhooker looking at the gist it seems like the command fails because the x509 file is not specified in the template file. It is not very clear where this files can be uploaded/generated in AWS, I suspect that AWS allows only authentication via access key.

**Comment by rickard-von-essen** [comment]
@mcapuccini @carmat88 At least according to the docs _x509 cert_ is still required, see [ami-bundle-vo](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-up-ami-tools.html#ami-bundle-vol).

Could you reference anywhere docs explaining how to bundle a volume with only a access key?

**Comment by carmat88** [comment]
Hello @rickard-von-essen ! Thanks for following-up. I was mainly following you documentation. So here is the link of the packer builder were X509 details seem to not be mandatory: 

https://www.packer.io/docs/builders/amazon-ebs.html

Best

**Comment by rickard-von-essen** [comment]
There is two different procedures for how to create AMI's for EBS vs. instance store backed instances.

See:
- http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/creating-an-ami-instance-store.html
- http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/creating-an-ami-ebs.html

**Comment by rickard-von-essen** [comment]
Please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._
