### ISSUE TITLE
VNC Feature available on 0.12.3 was removed on 1.0.0

### ISSUE THREAD

**Issue by lmayorga1980** [hashicorp/packer#4787]
I have been using `0.12.3` release and I could find the new feature available  in the CHANGELOG.md "core: make VNC links clickable in terminal. [GH-4497] [GH-4498]". However, after the upgrade the STDOUT does not show the information anymore...

```bash
==> vmware-iso: Uploading ISO to remote machine...
==> vmware-iso: Creating virtual machine disk
==> vmware-iso: Building and writing VMX file
==> vmware-iso: Registering remote VM...
==> vmware-iso: Starting virtual machine...
==> virtualbox-iso: Typing the boot command...
==> vmware-iso: Waiting 10s for boot...
==> virtualbox-iso: Waiting for SSH to become available...
==> vmware-iso: Connecting to VM via VNC
==> vmware-iso: Typing the boot command over VNC...
==> vmware-iso: Waiting for SSH to become available...
=
```

**Comment by mwhooker** [comment]
those commits are in v1.0.0. I suggest double checking your usage.

If you can't find a reason, please post your entire json, and the output from versions 0.12.3 and 1.0.0

**Comment by mwhooker** [comment]
and FYI those links only show up if you're in headless mode

**Comment by lfarnell** [comment]
@mwhooker Is this VMware builder specific? If not, I think maybe each builder that supports it should be  explicit about it

**Comment by mwhooker** [comment]
the PRs just make the existing links have a schema in front of them so you can open them with the correct application if you have one registered. If you look at the PRs you can see which builders have this. I think it's all of them. Happy to look at any PRs that make this clearer

**Comment by lfarnell** [comment]
I was referring to the docs. It's kinda tucked away in the VMware builder docs and not really present in the others. Will you take a PR for the docs?

**Comment by mwhooker** [comment]
@lfarnell would absolutely love a pr for the docs! =)

**Comment by lmayorga1980** [comment]
@mwhooker double checked again and the VNC Clickable was available only when headless=true on esxi remote. I guess it can be closed

**Comment by mwhooker** [comment]
Ok glad its sorted.
