### ISSUE TITLE
amazon-import with Server Side Encryption on OVA upload to S3 bucket

### ISSUE THREAD

**Issue by atheiman** [hashicorp/packer#4788]
feature request:

Add an option on the [`amazon-import` post-processor](https://www.packer.io/docs/post-processors/amazon-import.html) to enforce [S3 server side encryption](http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingServerSideEncryption.html) on the upload of the OVA file. I think it's easy enough to do with the [aws sdk for go](https://docs.aws.amazon.com/sdk-for-go/api/service/s3/) that is being used.

Unfortunately I have never written Go so I'm not confident in myself making this change, but it seems the code would go here: https://github.com/hashicorp/packer/blob/81522dced0b25084a824e79efda02483b12dc7cd/post-processor/amazon-import/post-processor.go#L146-L150 and then a flag would be added (maybe `-sse=false`).

**Comment by mwhooker** [comment]
Look into adding a config variable here https://github.com/hashicorp/packer/blob/81522dced0b25084a824e79efda02483b12dc7cd/post-processor/amazon-import/post-processor.go#L24

packer will automatically search the json for the flag and set the config field.

unfortunately I'm not able to implement and test this right now, so the change will have to come from the community. Happy to do code review on any PRs you submit. Definitely don't worry if you're not an expert go programmer. I'll be happy to help
