### ISSUE TITLE
amazon: Document profile option

### ISSUE THREAD

**Issue by utahcon** [hashicorp/packer#4789]
I own multiple accounts that aren't able to share AMIs for various reasons. The ability to define AWS Profile to use from my `~/.aws/credentials` file for each builder would be very nice. 

Example:
```
...
"builders": [
    {
      "type": "amazon-ebs",
      "aws_profile": "profile-1",
      ...
    },
    {
      "type": "amazon-ebs",
      "aws_profile": "profile-2",
      ...
    }
```

The effect would be the ability to spin up multiple AMIs in multiple accounts without having to change the environment variable `AWS_PROFILE` between runs. Would also alleviate the need to change VPC and Subnet IDs between accounts.

**Comment by rickard-von-essen** [comment]
See https://github.com/hashicorp/packer/pull/4996#issuecomment-308278968

**Comment by mwhooker** [comment]
@rickard-von-essen what about the use case mentioned here, of having multiple builders that each need a separate profile?

It doesn't seem possible to support that by having the user set `AWS_PROFILE`, so the only way to do that would be to support the profile option. I'm fine with this.

If you don't think that's a use case that should be supported, then I think that's a separate discussion

**Comment by rickard-von-essen** [comment]
Yes for that use case the `profile` option is needed and after some thinking I would like to keep it and document it. 

>  we don't want to control aws authentication through packer, since aws does a much better job of that. Adding a profile option does just that.

(https://github.com/hashicorp/packer/pull/4996#issuecomment-308278968)

Profile is not really handling auth with packer it's more an enabler for use to leverage the aws sdk by telling it which config to load. For sure you could use `AWS_PROFILE` env var, but as many points out limits it to one which is not mapping well against the possibility to run multiple (aws) builders.

So my (final) vote ✋  is on keep `profile` and add it to the docs.
