### ISSUE TITLE
User variables as lists

### ISSUE THREAD

**Issue by defunct73** [hashicorp/packer#479]
Hello, would it be possible to allow user variables to be lists?  For example:

``` json
{
  "variables": {
    "launchPermissions": [ "444455556666", "444455556667" ]
  },

  "builders": [{
    "type"          : "amazon-ebs",
    "region"        : "us-west-1",
    "source_ami"    : "ami-1a2b3c4d",
    "instance_type" : "t1.micro",
    "ssh_username"  : "ec2-user",
    "ami_name"      : "new-ami-{{timestamp}}",
    "ami_users"     : [ "{{user `launchPermissions`}}" ]
  }]
}
```

Thank you for consideration

**Comment by 1mentat** [comment]
Can you put this suggestion in the documentation? I ran into the exact same situation and found this relatively quickly but still it would be better to directly mention how you recommend lists of vars.
