### ISSUE TITLE
Leftover packer-elevated-shell.ps1 files in /tmp

### ISSUE THREAD

**Issue by scottpas** [hashicorp/packer#4795]
Is it possible to make packer clean up after itself in the /tmp directory? Or can it use the $TMPDIR variable to place the files in a different folder? I end up with tons of packer-elevated-shell.ps1######### and other files leftover when a build finishes.

**Comment by lfarnell** [comment]
@scottpas Are you using the powershell provisioner? Currently none of the windows provisioners have an option to  clean up after themselves like some of the other provisioners. I will work on a PR for the powershell and windows-shell provisioners

**Comment by scottpas** [comment]
@lfarnell Yes, I'm using the powershell provisioner. I noticed in the provisioner/powershell/elevated.go file also doesn't clean up the task it uses to run the command. Adding `$f.DeleteTask("\$name",0)` between likes 86-87 should fix it.

It also looks like it leaves the script files in the temp folder on the host that's building the VM.

**Comment by lfarnell** [comment]
@scott2449 I managed to get the windows-shell script cleanup working. I'm currently working on the powershell provisioner cleanup. The code cleanup is done in the provisionor.go rather than the elevated.go. This would only clean up any leftover files if they were elevated. Non-elevated would be left over still.

**Comment by prsshini** [comment]
Is the fix to delete packer's left over scheduled tasks while running powershell scripts in place now? I still see bunch of sch tasks in my instance though i run my scripts in elevated mode, and I am unable to cleanup. Please let me know if there is a workaround for windows powershell provisioners to cleanup after its sch task.

**Comment by nywilken** [comment]
Hello folks,  I have an open PR to fix this issue. The PR adds a provisioner clean up step that will remove the files uploaded during a single Powershell provisioner run. The clean up step can be disabled by setting the `"skip_clean": true` within the provisioner configuration. Here are some binaries https://app.circleci.com/pipelines/github/hashicorp/packer/4262/workflows/14e75d1d-cac1-4b50-b18e-d9216d56bf47/jobs/40897/artifacts.  Could you please tell me if the fix works for you?
Thank you!
