### ISSUE TITLE
VMware-iso builder: HTTPIP HTTPPort are no value with nested variables.

### ISSUE THREAD

**Issue by mbap** [hashicorp/packer#4797]
- Packer version from `packer version` : 1.0.0
- Host platform: Centos 7
https://gist.github.com/mbap/313acf1cbbf1c1a5b3199afff6579ab2

I am seeing that if I have my boot_command as a variable in the vmware-iso builder, and that variable contains that built in variables packer's variable engine fails.

boot_command : {{user `boot`}} is equal to the string `<wait><esc>linux inst.ks=http://{{ .HTTPIP }}:{{ .HTTPPort}}/ks.cfg<enter>` and i see in vnc that it outputs `linux inst.ks=http://<no value>:<no value>/ks.cfg`

In addition, once i replace this with a hardcoded path i get a curl error No route to host, so the http server isnt even reachable, but I suspect this is another issue since i am building vms inside of vms.

**Comment by rickard-von-essen** [comment]
Packer doesn't support nested variables substitution.

**Comment by mbap** [comment]
Gotcha. Wasn't sure if that was mentioned in the documentation, but thought I would mention my user error anyways.

**Comment by rickard-von-essen** [comment]
The docs have been updated in #4781 but that update haven't yet been deployed.
