### ISSUE TITLE
Better openstack support

### ISSUE THREAD

**Issue by alop** [hashicorp/packer#480]
Currently, the openstack builder assumes that a user is on Rackspace. https://github.com/rackspace/gophercloud/blob/master/global_context.go#L15

The builder imports gophercloud, which has hardcoded AuthEndpoint to Rackspace's URLs. 

Perhaps instead of having 'provider' be either 'rackspace-us/uk', the builder could require the AuthEndpoint directly, which any openstack user will already have.

**Comment by vallard** [comment]
I'm running on a Metacloud instance as well (well, now Cisco OpenStack Private Cloud).  I can't seem to get pass the insufficient privileges problem like you did.  

```shell
OS_TENANT_ID=12345....
OS_PASSWORD=secret
OS_AUTH_URL=http://<redacted>.metacloud.net:5000/v2.0
OS_USERNAME=user
OS_TENANT_NAME=TCO Application
```
Then packer file:

```json
{
     "builders" : [{
       "type": "openstack",
       "ssh_username": "core",
       "image_name": "coreos-java",
       "source_image": "bc3c7ad4-33d5-4702-a01a-b4b65b5c14a3",
       "flavor": "5"
   }]
}
```
Running:
```shell
packer build coreos-jenkins3.json 
openstack output will be in this color.

Build 'openstack' errored: Missing endpoint, or insufficient privileges to access endpoint

==> Some builds didn't complete successfully and had errors:
--> openstack: Missing endpoint, or insufficient privileges to access endpoint

==> Builds finished but no artifacts were created.
```

My version is 

```bash
$ packer version
Packer v0.7.5
```

Any hints of how I can troubleshoot?

**Comment by jrevote** [comment]
Same issue as vallard, same packer version, private OpenStack, still the same issue ....

**Comment by einarf** [comment]
I made a commit (55c2ac4) today with a new openstack builder using the new gophercloud API. That might lead to a more flexible openstack builder soon.
