### ISSUE TITLE
vmware-vmx opens .vmx file with the .vmx-associated app instead of VMware Fusion

### ISSUE THREAD

**Issue by codestothestars** [hashicorp/packer#4800]
Packer version: 1.0.0
Host platform: macOS 10.12.4
Gist: https://gist.github.com/codestothestars/4ceab2a25f4b22c8c827eca7c68f3701

Steps to reproduce:
1. Right-click any .vmx file.
1. Under "Open with:" select any application other than VMware Fusion, such as a text editor.
1. Click "Change All...".
1. Run `packer build my-vm.json`

Expected behavior:
Packer build a new VM from the source .vmx file

Actual behavior:
The .vmx file is opened with whatever application was chosen in step 2 (a text editor in my case). The packer build times out waiting for the VM to start.

**Comment by arizvisa** [comment]
@codestothestars, are you trying to say that when a file is open in another process, VMware Fusion is unable to open the .vmx?

Or are you suggesting that VMware Fusion is spawning an instance of your text editor when it tries to run `/Applications/VMware Fusion.app/Contents/Library/vmrun [-T fusion clone /Users/ariel.ryan-pagano/my-vm/my-vm.vmx output-vmware-vmx/packer-vmware-vmx-{{timestamp}}.vmx full]`?

**Comment by codestothestars** [comment]
>are you trying to say that when a file is open in another process, VMware Fusion is unable to open the .vmx?

No.

> Or are you suggesting that VMware Fusion is spawning an instance of your text editor

Yes! After I run `packer build my-vm.json`, at a certain point while the build is running, the .vmx file is opened in whatever application I have set as the default application for .vmx files. In my case, that's my text editor. The build then just hangs and times out after a few minutes.

> when it tries to run `/Applications/VMware Fusion.app/Contents/Library/vmrun [-T fusion clone /Users/ariel.ryan-pagano/my-vm/my-vm.vmx output-vmware-vmx/packer-vmware-vmx-{{timestamp}}.vmx full]`?

Actually, it seems to occur instead at the following step (line 113 in the `log.txt` of my Gist)

```shell
/Applications/VMware Fusion.app/Contents/Library/vmrun [-T fusion start output-vmware-vmx/packer-vmware-vmx-{{timestamp}}.vmx gui]
```

I confirmed this by running that command manually on the terminal, and indeed the .vmx file simply opened up in my text editor. The VM is apparently never launched.

I suppose this means that the problem lies within VMware Fusion itself? Let me know if you'd like further clarification. I can reproduce the issue in a GIF if necessary.

**Comment by arizvisa** [comment]
Yep, seems like it's related to file associations, or something with the VMware Fusion installation. Essentially, it's VMware's job to open the .vmx and start it instead of opening it up with a default editor when running that commandline. . (I don't use OSX so I can't offer any more help). 

It's definitely a configuration issue and can't really be fixed by packer since packer has to assume that `vmrun` handles VM management properly.

**Comment by codestothestars** [comment]
Thanks. Obviously the sensible workaround is what I've been doing already, which is to just set Fusion as the default application for .vmx files. It is a bit inconvenient when I want to edit one by hand, but not a big deal.

I have attempted to report this bug to VMware on [their forums](https://communities.vmware.com/community/vmtn/fusion/content). My post is [here](https://communities.vmware.com/message/2776479). If anyone happens to know a more efficient way of reporting this to VMware, please let me know.
