### ISSUE TITLE
packer post-processor checksum crash "only" virtualbox-iso

### ISSUE THREAD

**Issue by vze22jjw** [hashicorp/packer#4805]
BUGS:

running packer to build virtualbox-iso vagrant output and using checksum post-processor so can be added to vagrantfile later, resulted in crash and request for issue being opened

- Packer version v.0.12.2
- Host MacOS Sierra
- crash log:
https://gist.github.com/vze22jjw/b7e7a4919878e21fa403b50445e8be31

**Comment by mwhooker** [comment]
thanks for the report
