### ISSUE TITLE
WinRM is extremely slow uploading chef files

### ISSUE THREAD

**Issue by chunkdaddy** [hashicorp/packer#4806]
In building windows AMIs, i've noticed the transfer times of files to the instance is extremely slow.

In my template, i am transferring the roles, cookbooks, data_bags, and environment directories using the file provisioner, for use with the Chef provisioner:

	{
		"type": "file",
		"source": "./roles",
		"destination": "{{user `chef_dir`}}/roles"
	},
	{
		"type": "file",
		"source": "./cookbooks",
		"destination": "{{user `chef_dir`}}/cookbooks"
	},
	{
		"type": "file",
		"source": "./data_bags",
		"destination": "{{user `chef_dir`}}/data_bags"
	},
	{
		"type": "file",
		"source": "./environments",
		"destination": "{{user `chef_dir`}}/environments"
	}

The bulk of the time is spent uploading the cookbooks directory, which is only 1420k.  The directory size and transfer time can be found here:

https://gist.github.com/chunkdaddy/e867b379804c975a417d9a77196a639d

32 minutes to transfer 1420k seems really slow, especially since it happens even on systems within the data center or AWS.  Over hundreds of builds i've performed, this time is fairly consistent in every one, 30-40 minutes, and is true for both Windows 2012R2 and Windows 2016.

The WinRM config we bootstrap in to user-data is here:
https://gist.github.com/chunkdaddy/2c2b585ae221d8d8555cf9d97ab0da9d

WinRM template settings are here:
https://gist.github.com/chunkdaddy/70860459157ea0317c0b7992d0556880

- Packer version:  all since the introduction of the winrm communicator, including 1.0, in both regular and -debug mode.  Debug does not provide additional detail
- Build environment/Host platform:  Multiple.  The gist above is from our go-cd server sitting in an AWS VPC but it also occurs when building from my Mac or from a server in our data center.  All unix, no Windows build machines.
- Easiest way to reproduce:    use the winrm communicator and the file provisioner to upload some directories with a total size of greater than 1MB, but less than 2MB

Is there some additional tuning i can do with the WInRM configs, or is just "winrm is what it is", and what that is is slow?

Thanks!

**Comment by chunkdaddy** [comment]
Looks like this was already mentioned in [#2648](https://github.com/hashicorp/packer/issues/2648), but it was closed with no resolution.

**Comment by mwhooker** [comment]
Unfortunately I think this is a limitation of winrm, or at least the libraries we use.

There's a PR open here to try to get faster upload speeds, but the PR needs some love https://github.com/packer-community/winrmcp/pull/6

Our recommendation has been to use the the http server that's part of most (local) builders. For example https://www.packer.io/docs/builders/virtualbox-iso.html#http_directory

I'm going to close since there's nothing I think we can do to make winrm faster.

**Comment by cepefernando** [comment]
Hi there, another solution can be uploading the files to S3 from the host and then download them on the Instances, done over the provisioner.
