### ISSUE TITLE
Packer stuck at: "Gracefully halting virtual machine" with Windows Host and Linux Guest

### ISSUE THREAD

**Issue by papanito** [hashicorp/packer#4813]
I am trying to create an Ubuntu box from scratch using packer. After provisioning is done machine shall be shutdown but instead it stucks at 
```
==> virtualbox-iso: Provisioning with shell script: C:\Users\papanito\AppData\Roaming\MOBAXT~1\slash\tmp\packer-shell481399811
    virtualbox-iso: my additional provisioning steps
==> virtualbox-iso: Gracefully halting virtual machine...
```

Versions and files
- Packer version: 1.0.0
- Host Platform: Windows 7 Enterprise SP 1
- Virtualbox: 5.1.18r114002
- ubuntu_16.10_x64.json 
https://gist.github.com/papanito/9fe5e42d613aaa1421ed3e464dcf273f#file-ubuntu_16-10_x64-json

Debug log output from `PACKER_LOG=1 packer build ubuntu_16.10_x64.json`.
```
...
2017/04/20 09:27:48 ui: ==> virtualbox-iso: Gracefully halting virtual machine...
==> virtualbox-iso: Gracefully halting virtual machine...
2017/04/20 09:27:48 packer.exe: 2017/04/20 09:27:48 Executing shutdown command: sudo -S shutdown -P now
2017/04/20 09:27:48 packer.exe: 2017/04/20 09:27:48 opening new ssh session
2017/04/20 09:27:48 packer.exe: 2017/04/20 09:27:48 starting remote command: sudo -S shutdown -P now
```
Full log can be found at https://gist.github.com/papanito/9fe5e42d613aaa1421ed3e464dcf273f#file-packer-log

**Comment by rickard-von-essen** [comment]
Most likely it's waiting for the password. Ensure that you have
passwordless sudo etc.

**Comment by papanito** [comment]
Thanks for the hint. Instead of passwordless I fund the sudo example at https://www.packer.io/docs/provisioners/shell.html which also did the trick.

`"shutdown_command": "echo '{{user `pwd`}}' | {{user `shutdown_command`}}",`
