### ISSUE TITLE
Timeout waiting for WinRM in Azure

### ISSUE THREAD

**Issue by ft115637850** [hashicorp/packer#4815]
When I create a Windows image in Azure, it fails because of Timeout waiting for WinRM:

```
azure-arm output will be in this color.
==> azure-arm: Running builder ...
    azure-arm: Creating Azure Resource Manager (ARM) client ...
==> azure-arm: Creating resource group ...
==> azure-arm:  -> ResourceGroupName : 'packer-Resource-Group-bbr07kl7ft'
==> azure-arm:  -> Location          : 'West US'
==> azure-arm:  -> Tags              :
==> azure-arm: Validating deployment template ...
==> azure-arm:  -> ResourceGroupName : 'packer-Resource-Group-bbr07kl7ft'
==> azure-arm:  -> DeploymentName    : 'pkrdpbbr07kl7ft'
==> azure-arm: Deploying deployment template ...
==> azure-arm:  -> ResourceGroupName : 'packer-Resource-Group-bbr07kl7ft'
==> azure-arm:  -> DeploymentName    : 'pkrdpbbr07kl7ft'
==> azure-arm: Getting the certificate's URL ...
==> azure-arm:  -> Key Vault Name        : 'pkrkvbbr07kl7ft'
==> azure-arm:  -> Key Vault Secret Name : 'packerKeyVaultSecret'
==> azure-arm:  -> Certificate URL       : 'https://pkrkvbbr07kl7ft.vault.azure.net/secrets/packerKeyVaultSecret/8113f7bf7ace430ea2d80ea3327333ee'
==> azure-arm: Setting the certificate's URL ...
==> azure-arm: Validating deployment template ...
==> azure-arm:  -> ResourceGroupName : 'packer-Resource-Group-bbr07kl7ft'
==> azure-arm:  -> DeploymentName    : 'pkrdpbbr07kl7ft'
==> azure-arm: Deploying deployment template ...
==> azure-arm:  -> ResourceGroupName : 'packer-Resource-Group-bbr07kl7ft'
==> azure-arm:  -> DeploymentName    : 'pkrdpbbr07kl7ft'
==> azure-arm: Getting the VM's IP address ...
==> azure-arm:  -> ResourceGroupName   : 'packer-Resource-Group-bbr07kl7ft'
==> azure-arm:  -> PublicIPAddressName : 'packerPublicIP'
==> azure-arm:  -> NicName             : 'packerNic'
==> azure-arm:  -> Network Connection  : 'PublicEndpoint'
==> azure-arm:  -> IP Address          : '13.93.202.48'
==> azure-arm: Waiting for WinRM to become available...
==> azure-arm: Timeout waiting for WinRM.
==> azure-arm:
==> azure-arm: Cleanup requested, deleting resource group ...
==> azure-arm: Resource group has been deleted.
Build 'azure-arm' errored: Timeout waiting for WinRM.

==> Some builds didn't complete successfully and had errors:
--> azure-arm: Timeout waiting for WinRM.

==> Builds finished but no artifacts were created.

```
Here is the template:
```
{
  "variables": {
    "object_id": "{{env `OBJECT_ID`}}",
    "client_id": "{{env `CLIENT_ID`}}",
    "client_secret": "{{env `CLIENT_SECRET`}}",
    "subscription_id": "{{env 'subscription_id'}}",
    "tenant_id": "{{env 'tenant_id'}}",
  },

  "builders": [
    {
      "type": "azure-arm", 
	  "object_id": "{{user 'object_id'}}",
      "client_id": "{{user 'client_id'}}",
      "client_secret": "{{user 'client_secret'}}",
      "resource_group_name": "dynsimepremium0329",
      "storage_account": "newtonteststorage",
      "subscription_id": "{{user 'subscription_id'}}",
	  "tenant_id": "{{user 'tenant_id'}}",
	  
      "capture_container_name": "vhds",
      "capture_name_prefix": "NewtonPacker",   
	  
	  "image_publisher": "MicrosoftWindowsServer",
	  "image_offer": "WindowsServer",
      "image_sku": "2012-R2-Datacenter",
      "location": "West US",
	  "os_type": "Windows",
	  
	  "vm_size": "Standard_A2"
    }
  ],
  "provisioners": [
    {
      "type": "powershell",
      "inline": [
        "if( Test-Path $Env:SystemRoot\\windows\\system32\\Sysprep\\unattend.xml ){ rm $Env:SystemRoot\\windows\\system32\\Sysprep\\unattend.xml -Force}",
        "& $Env:SystemRoot\\System32\\Sysprep\\Sysprep.exe /oobe /generalize /shutdown /quiet"
      ]
    }
  ]

}
```

I run my Packer on Win10.
```
D:\Program>packer version
Packer v1.0.0
```
[packerlog.txt](https://github.com/hashicorp/packer/files/945657/packerlog.txt)

**Comment by boumenot** [comment]
You made in far enough in the process that I think your configuration is correct.  Do you have a PROXY configured, or do you have a firewall that only allows certain ports to connect out?

Please follow the [debugging procedures](https://www.packer.io/docs/other/debugging.html) and attach the log file to the issue.  This may help me better understand the issue.

**Comment by ft115637850** [comment]
I read your debugging procedures, but I'm not sure I understand. I tried like this, but doesn't work:
```
D:\Program>packer build -var-file=test.json
invalid value "test.json" for flag -var-file: Error reading variables in 'test.json': json: cannot unmarshal object into Go value of type string
```

Could you just give a simple example in Windows?

**Comment by boumenot** [comment]
If you use PowerShell, this should be sufficient: https://www.packer.io/docs/other/debugging.html#debugging-packer-in-powershell-windows.  Set two environment variables, and then re-run your Packer build in the same console.

If you use cmd.exe, you can set the environment variables like so.

```bat
set PACKER_LOG=1
set PACKER_LOG_PATH=packerlog.txt
```

HTH

**Comment by ft115637850** [comment]
2017/04/21 04:36:07 ui: ==> azure-arm:  -> IP Address          : '13.64.64.87'
2017/04/21 04:36:07 ui: ask: ==> azure-arm: Pausing after run of step 'StepGetIPAddress'. Press enter to continue.
2017/04/21 04:36:09 packer.exe: 2017/04/21 04:36:09 Waiting for WinRM, up to timeout: 0s
2017/04/21 04:36:09 ui: ==> azure-arm: Waiting for WinRM to become available...
2017/04/21 04:36:09 ui error: ==> azure-arm: Timeout waiting for WinRM.
2017/04/21 04:36:09 packer.exe: 2017/04/21 04:36:09 [INFO] WinRM wait cancelled. Exiting loop.
2017/04/21 04:36:09 ui: ask: ==> azure-arm: Pausing before cleanup of step 'StepGetIPAddress'. Press enter to continue.
2017/04/21 04:36:10 ui: ask: ==> azure-arm: Pausing before cleanup of step 'StepDeployTemplate'. Press enter to continue.
2017/04/21 04:36:11 ui: ask: ==> azure-arm: Pausing before cleanup of step 'StepValidateTemplate'. Press enter to continue.
2017/04/21 04:36:12 ui: ask: ==> azure-arm: Pausing before cleanup of step 'StepSetCertificate'. Press enter to continue.
2017/04/21 04:36:13 ui: ask: ==> azure-arm: Pausing before cleanup of step 'StepGetCertificate'. Press enter to continue.
2017/04/21 04:36:13 ui: ask: ==> azure-arm: Pausing before cleanup of step 'StepDeployTemplate'. Press enter to continue.
2017/04/21 04:36:14 ui: ask: ==> azure-arm: Pausing before cleanup of step 'StepValidateTemplate'. Press enter to continue.
2017/04/21 04:36:14 ui: ask: ==> azure-arm: Pausing before cleanup of step 'StepCreateResourceGroup'. Press enter to continue.

**Comment by boumenot** [comment]
Please attach packerlog.txt.

**Comment by ft115637850** [comment]
@boumenot attached

**Comment by scottpas** [comment]
@ft115637850 try adding
```
"communicator": "winrm",
"winrm_use_ssl": "true",
"winrm_insecure": "true",
"winrm_timeout": "3m",
"winrm_username": "packer",
```
to your builder

**Comment by ft115637850** [comment]
@scottpas This works. But it takes over 20 minutes. Is this normal?

**Comment by boumenot** [comment]
Windows takes longer than Linux builds, and 20 minutes seems a little high.

Windows needs more time to deploy because...

 1. There are two template deployments necessary for a Windows build.  One to hold the WinRM certificate using KeyVault, and another for the actually VM.
 1. Windows deployment benefits more so than Linux from more memory, more CPU, and faster disk.  I would recommend Standard_DS2_v2 instead of an Standard_A2.
 1. The /sysprep/ process on Linux takes a second or two, but sysprep on Windows takes considerably longer.
