### ISSUE TITLE
Elevated Powershell Provisioner for Azure builder

### ISSUE THREAD

**Issue by scottpas** [hashicorp/packer#4818]
I'm unable to use the elevated powershell provisioner when building with Azure, because it requires a value for `elevated_password`. The Azure builder generates a random password, and ignores anything set in `winrm_password` for the communicator settings, so there's no way of knowing or setting the password beforehand.

**Comment by boumenot** [comment]
Thanks for opening an issue!

Azure uses the Admin username/password when communicating over WinRM, so is there a need to set elevated_user too?

The Azure builder allows you to override the password, but it uses ssh_password for both SSH and WinRM.  This is confusing, and should be fixed and documented.

I recommend the following steps to getting yourself unblocked.

  1. Remove elevated_user to, and see if the default WinRM works for you.
  1. Set the password using ssh_password.

**Comment by scottpas** [comment]
@boumenot Unfortunately, the script needs to be ran through the elevation process, but it appears that setting ssh_password works to resolve the issue. Thanks for your help!

**Comment by boumenot** [comment]
Awesome!

**Comment by scottpas** [comment]
@boumenot It looks like I spoke too soon... I assumed that because it was setting the password in Azure that I'd be able to connect, but I keep getting a timeout waiting for WinRM. I've attached my packer template and debug log.
[azure.json.txt](https://github.com/hashicorp/packer/files/951603/azure.json.txt)
[packer.log.txt](https://github.com/hashicorp/packer/files/951605/packer.log.txt)

**Comment by boumenot** [comment]
The logs don't provide any insight into why this is failing.

/cc @paulmey - have you seen this before? He's running the powershell provisioner with elevated flags, and the WinRM connection is spitting out HTTP 401 errors.

**Comment by paulmey** [comment]
No, I didn't even know there was an 'elevated' flag. Sounds like we should not be setting winrm_password to random if it was set in the config (assuming that we're already squashing in the winrm config)?

**Comment by boumenot** [comment]
Yes, that needs to be addressed as well. The issue I do not understand is why WinRM connectivity is being rejected with a 401.

**Comment by mwhooker** [comment]
https://github.com/hashicorp/packer/pull/3452 I saw this i wanted to link here

There have been a couple recent changes involving elevated shell which might be worth checking out

**Comment by sandersaares** [comment]
The only way I got this to work was to create a new user with a fixed name/password as the first step, then use that for the elevated PowerShell scripts. I tried overriding the credentials with `ssh_*` and `winrm_*` but the PowerShell provisioner still was unable to log in.

**Comment by harryluo91** [comment]
hey @sandersaares, I was trying to do the same thing but I got the access denier error when I was trying to create the account, it looks like I need to run the command in a powershell with elevated privileges as well. Were you able to create the account and add it to the Administrator group with the normal powershell provisioner?

**Comment by sandersaares** [comment]
Yes, I was able to create the user with just the normal non-elevated PowerShell provisioner. I used the "net user" command to create the user and "net localgroup" to add it to the Administrators group.

**Comment by eakatank** [comment]
I have also run into this wall. winrm_password appears to be ignored.

@harryluo91 I was also unable to add users via the powershell provisioner (2008R2-SP1). I was however able to add the user with the windows-shell provisioner.

**Comment by nywilken** [comment]
Hi folks! The issue around a custom winrm_password being ignored, as well as the elevated_user issue for powershell,  should be fixed by #8670. There are some test binaries available via the link below if you would like to test the fix. 

https://circleci.com/gh/hashicorp/packer/31314#artifacts/containers/0

Please feel free to make additional comments or attach new configs/logs if the fix is not working as expected.

Thanks!
