### ISSUE TITLE
Hyperv-iso builder not importing Hyper-V Module

### ISSUE THREAD

**Issue by shotah** [hashicorp/packer#4830]
After reviewing my profile and validating that VMWare was removed and Hyper-V was imported. Still had new-vm loading with VMWare PowerCLI. The Builder needs to validate that it is using the Hyper-V module and make sure its imported before it runs. Yes I agree that VMWare should have built PowerCLI with different module names, and MS shouldn't let VMWare stomp on their profile, but it is required that I have PowerCLI installed on my computer, but it is not loaded in my profile so this is squarely on Packer to make sure they are loading Hyper-V prior to their build.

**Comment by shotah** [comment]
At line 194 in hyperv/hyperv.go it needs a `import-module hyper-v` 

https://github.com/hashicorp/packer/blob/81522dced0b25084a824e79efda02483b12dc7cd/common/powershell/hyperv/hyperv.go

**Comment by taliesins** [comment]
Going to close this issue as there is a pull request to cover this issue.
