### ISSUE TITLE
Postprocessor amazon-import creating AMI image with EBS volume size 300GB

### ISSUE THREAD

**Issue by aksuna** [hashicorp/packer#4837]
Reference:
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/block-device-mapping-concepts.html

FOR FEATURES:

Postprocessor amazon-import is importing the OVA as a AMI image well , but in the block device mapping associated to the AMI is associating a snapshot that by default has a volume size of 300GB .
Example : 
Block Device : /dev/sda1=snap-04973552a14e13c52:300:false:gp2
When we attend to launch a EC2 instance based in the AMI created  we cannot set the volume to one small size , less than 300GB . This is a lot of storage!!. In our case we just need 70 GB. There is any way to add a parameter to the postprocessor that we can set the "volume-size".

![ami-snapshot-300](https://cloud.githubusercontent.com/assets/5546165/25455158/c98d2fba-2a9c-11e7-8685-53436912b5f2.png)

taking to your logs when running packer:
 vmware-iso (amazon-import): Import task import-ami-fh1ncn5d complete
2017/04/26 14:57:21 ui:     vmware-iso (amazon-import): Import task import-ami-fh1ncn5d complete
2017/04/26 14:57:21 ui:     vmware-iso (amazon-import): Starting rename of AMI (ami-646a0f72)
    vmware-iso (amazon-import): Starting rename of AMI (ami-646a0f72)
2017/04/26 14:57:21 ui:     vmware-iso (amazon-import): Waiting for AMI rename to complete (may take a while)
    vmware-iso (amazon-import): Waiting for AMI rename to complete (may take a while)
2017/04/26 14:57:21 packer: 2017/04/26 14:57:21 Waiting for state to become: available
2017/04/26 14:57:21 packer: 2017/04/26 14:57:21 Using 2s as polling delay (change with AWS_POLL_DELAY_SECONDS)
2017/04/26 14:57:21 packer: 2017/04/26 14:57:21 Allowing 300s to complete (change with AWS_TIMEOUT_SECONDS)
2017/04/26 15:02:26 ui:     vmware-iso (amazon-import): AMI rename completed
    vmware-iso (amazon-import): AMI rename completed
2017/04/26 15:02:26 packer: 2017/04/26 15:02:26 Repacking tags into AWS format
2017/04/26 15:02:26 ui:     vmware-iso (amazon-import): Adding tag "Description": "packer amazon-import Safeconnect OVA 1493227619"
    vmware-iso (amazon-import): Adding tag "Description": "packer amazon-import Safeconnect OVA 1493227619"
2017/04/26 15:02:26 packer: 2017/04/26 15:02:26 Getting details of ami-1f771209
2017/04/26 15:02:26 packer: 2017/04/26 15:02:26 **Walking block device mappings for ami-1f771209 to find snapshots
2017/04/26 15:02:26 ui:     vmware-iso (amazon-import): Tagging snapshot snap-04973552a14e13c52**
    vmware-iso (amazon-import): Tagging snapshot snap-04973552a14e13c52
2017/04/26 15:02:26 ui:     vmware-iso (amazon-import): Tagging AMI ami-1f771209
    vmware-iso (amazon-import): Tagging AMI ami-1f771209
2017/04/26 15:02:26 packer: 2017/04/26 15:02:26 Adding created AMI ID ami-1f771209 in region us-east-1 to output artifacts
2017/04/26 15:02:26 ui:     vmware-iso (amazon-import): Deleting import source s3://impulse-ova-6-4-4/safeconnect-6.4.ova
    vmware-iso (amazon-import): Deleting import source s3://impulse-ova-6-4-4/safeconnect-6.4.ova
2017/04/26 15:02:27 ui: Build 'vmware-iso' finished.

looks like that your implementation when is copying the AMI generated from the conversion to a new ami with the name defined , you are assigning  a block device mapping  with a snapshot  that you search , we need that this dont happen. For small solutions we dont need that amount of volume size.

**Comment by aksuna** [comment]
this is the part in your code
 https://github.com/hashicorp/packer/blob/master/post-processor/amazon-import/post-processor.go
`		log.Printf("Walking block device mappings for %s to find snapshots", createdami)

		for _, device := range image.BlockDeviceMappings {
			if device.Ebs != nil && device.Ebs.SnapshotId != nil {
				ui.Message(fmt.Sprintf("Tagging snapshot %s", *device.Ebs.SnapshotId))
				resourceIds = append(resourceIds, device.Ebs.SnapshotId)
			}
		}`

**Comment by aksuna** [comment]
In another side of your code in amazon builder you had implement that : 
https://github.com/hashicorp/packer/blob/master/builder/amazon/chroot/step_create_volume.go

**Comment by aksuna** [comment]
There is any feedback about this requirement?

**Comment by mwhooker** [comment]
i'm not able to look into this right now. i suggest reaching out to the mailing list https://groups.google.com/forum/#!forum/packer-tool

only thing i can think of is looking at the exported vmware image disk size

**Comment by SwampDragons** [comment]
I think this is no longer an issue; just tested amazon-import and got an AMI whose size was 40GB.
