### ISSUE TITLE
Inconsistent behaviour when parsing/analysing JSON templates

### ISSUE THREAD

**Issue by walterdolce** [hashicorp/packer#4842]
#> - Packer version from `packer version` 

Packer version is `1.0.0`

> - Host platform 

Mac OS X

> - Debug log output from `PACKER_LOG=1 packer build template.json`.

```
 packer build -var-file=example-variables.json packer-template.json
amazon-ebs output will be in this color.

invalid 'extra_arguments': template: root:1: function "clean_ami_name" not defined in:

--extra-vars 'app_version={{ user `app_version` | clean_ami_name  }}'
```

> - The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your gist https://gist.github.com

https://gist.github.com/walterdolce/cb81cb95b4d1b6a99504afdea9b30289

# What's the issue?
Packer treats areas of the JSON templates differently. 

Looks like it doesn't like when someone uses `clean_ami_name` in the `provisioners` section. IMHO, this is a design flaw and it only creates confusion. The template should be treated as a single entity and the behaviour should be the same and the same tools (`clean_ami_name`) should also be available to use regardless of which section of the JSON is being parsed/analysed/managed.

**Comment by mwhooker** [comment]
Thanks for the report!

We're going to be revisiting our templating in the near future and won't be spending time on the json template engine.
