### ISSUE TITLE
Expose HTTPIP to Shell Provisioner

### ISSUE THREAD

**Issue by cgoeller** [hashicorp/packer#4844]
It would be quite useful to expose the IP address of the host machine in an environment variable to the shell provisioner.

This is similar to the PACKER_HTTP_ADDR added in https://github.com/hashicorp/packer/pull/4409
but without the port number. 

I'm running a local web server (package repository) on my host machine, which should be used during provisioining.

As an alternative it would make sense to use {{ .HTTPIP }} and {{ .HTTPPort }} in the shell provisioner.

**Comment by lfarnell** [comment]
I agree this would be useful. Not sure how much value {{ .HTTPPort }} would be considering how many times would you want just the port and not the full address. Would something like PACKER_HOST_IP work for you?

**Comment by cgoeller** [comment]
PACKER_HOST_IP would be sufficient for my use case. I don't need the port number of packers web server, as my package repo is running on a different port anyway.

**Comment by rickard-von-essen** [comment]
What's wrong with `echo "$PACKER_HOST_IP" | cut -d: -f1` ?

**Comment by lfarnell** [comment]
I think that for the amount of effort required to add PACKER_HOST_IP is super minimal. I personally don't see why a user should have to add extra "glue" scripts to remove the colon and port number
