### ISSUE TITLE
Assumed role stopped working altogether

### ISSUE THREAD

**Issue by jslusher** [hashicorp/packer#4849]
I'm using the docker container `hashicorp/packer:light` which shows version `0.12.3` but any other available version is giving me the same problem.

I'm using an assumed role for an amazon-ebs build populating the credential variables using the environment variables via the command line. It was the only way I was able to get it to work when I set it up, since I could never get defaulting to env variables to work. 

I tried removing my ~/.aws/credentials file but I get the same thing.

The exact same configuration was working for me for the last couple of months and as of yesterday I'm getting an AuthFailure error.

Relevant template config: 

    {
      "variables": {
        "aws_access_key":  "",
        "aws_secret_key": "",
        "aws_session_token": "",
    ...
      },
      "builders": [{
        "type": "amazon-ebs",
        "access_key": "{{user `aws_access_key`}}",
        "secret_key": "{{user `aws_secret_key`}}",
        "token": "{{user `aws_session_token`}}",
    ...

CLI command:

     sudo docker run -i -v $(shell pwd):/opt/ -w /opt/ hashicorp/packer:light build -debug -on-error=ask -var 'aws_access_key=${AWS_ACCESS_KEY_ID}' -var 'aws_secret_key=${AWS_SECRET_ACCESS_KEY}' -var 'aws_session_token=${AWS_SESSION_TOKEN}' /opt/templates/ami-west-debug.json

I noticed the images in dockerhub changed as of just a couple days ago and I wonder if this is the reason. At any rate I can't get it to work anymore no matter what I try. Again, no ~/.aws/ files. I tested the credentials themselves and they're fine.

    Debug mode enabled. Builds will not be parallelized.
    amazon-ebs output will be in this color.

    Build 'amazon-ebs' errored: AuthFailure: AWS was not able to validate the provided access credentials
    	status code: 401, request id: c0210a51-0c10-4a5b-8e48-e1310b37acd8

    ==> Some builds didn't complete successfully and had errors:
    --> amazon-ebs: AuthFailure: AWS was not able to validate the provided access credentials
	status code: 401, request id: c0210a51-0c10-4a5b-8e48-e1310b37acd8

    ==> Builds finished but no artifacts were created.

**Comment by mwhooker** [comment]
Can you say what version this was working in? 

see also #3019 #4613

**Comment by jslusher** [comment]
All I know is that it was working on whatever version was being used for the `hashicorp/packer:light` docker image that was available a couple days ago. I'm not sure the version. I did try all of the other tagged versions available in the dockerhub repo, `0.10.0`, `0.11.0`, `1.0.0` and `0.12.2` and none of them seem to work.

**Comment by jslusher** [comment]
This seems to be working again. I didn't change anything as far as I can tell. Very mysterious. The only major difference is that I'm on a different network? I wouldn't think that would matter though.

**Comment by rickard-von-essen** [comment]
Might be that your system time was off. Closing this since it solved it self. Reopen if it reoccurs.

**Comment by jslusher** [comment]
I came in this morning after it had been working for the last couple of days, ran the exact same command with the same credentials and I'm again getting the authorization error.

**Comment by jslusher** [comment]
Trying a few more times, I got it to work, but I didn't change anything except that my token changes each time I assume the role. It definitely has something to do with the aws_session_token, but I can't tell what it might be.
