### ISSUE TITLE
Feature: Ability to set provisioner to run only on specific builders

### ISSUE THREAD

**Issue by lfarnell** [hashicorp/packer#4854]
Currently, if you want to only run a script for a specific builder you would have to read the environment variables  `PACKER_BUILD_NAME` & `PACKER_BUILDER_TYPE` set by Packer. For small scripts that target Packer builds specifically, this will work. In the case of shared scripts that need the ability to run in multiple environments(outside of Packer), this makes it non-trivial. I do think that this would make the experience a little easier and limit the amount of script changes required.

What would be great is to have the ability to set an array of builders that the provisioner should execute on. An example provisioner would look like the following:
```json
"provisioners": [
    {
      "type": "windows-shell",
      "script": "./scripts/enable-rdp.bat",
      "builders": ["virtualbox-iso", "vmware-iso"]
    },
    {
      "type": "windows-shell",
      "script": "./scripts/vbox-guest-tools.bat",
      "builders": ["virtualbox-iso"]
    },
    {
      "type": "windows-shell",
      "script": "./scripts/vmware-guest-tools.bat",
      "builders": ["vmware-iso"]
    },
    {
      "type": "windows-shell",
      "script": "./scripts/generic.bat"
    }
  ]
```
In this case, by not setting the builder the scripts will execute on any builder. By specifying the builder, the script would run only for the builders specified.

**Comment by mwhooker** [comment]
see https://www.packer.io/docs/templates/provisioners.html#run-on-specific-builds
