### ISSUE TITLE
amazon/ebs: need a way to disable proxy for winrm requests

### ISSUE THREAD

**Issue by dsme94** [hashicorp/packer#4857]
When using packer version 1.0.0 to build images using Vagrant on Windows, WinRM does not work. It  will not connect and will timeout. Downgrading to version 0.12.2 solved the problem for me.  The windows instance is running Server 2012 R2. I have not tried versions 0.12.3 or later but before v1.0.0 as a colleague was able to build using 0.12.2 I went to this version directly. 

I make use of a variable file, my packer build looks like so: 
_/media/sf_D_DRIVE/packer build -debug -var-file=vars.json packer.json_

**Packer version:**
```
[root@localhost play1]# /usr/bin/packer version
Packer v1.0.0
```

**Failure:**
```==> amazon-ebs: Prevalidating AMI Name...
==> amazon-ebs: Pausing after run of step 'StepPreValidate'. Press enter to continue.
    amazon-ebs: Found Image ID: 
==> amazon-ebs: Pausing after run of step 'StepSourceAMIInfo'. Press enter to continue.
==> amazon-ebs: Creating temporary keypair: 
    amazon-ebs: Saving key for debug purposes: 
==> amazon-ebs: Pausing after run of step 'StepKeyPair'. Press enter to continue.
==> amazon-ebs: Pausing after run of step 'StepSecurityGroup'. Press enter to continue.
==> amazon-ebs: Pausing after run of step 'stepCleanupVolumes'. Press enter to continue.
==> amazon-ebs: Launching a source AWS instance...
    amazon-ebs: Instance ID: 
==> amazon-ebs: Waiting for instance () to become ready...
==> amazon-ebs: Adding tags to source instance
    amazon-ebs: Private IP: 
==> amazon-ebs: Pausing after run of step 'StepRunSourceInstance'. Press enter to continue.
==> amazon-ebs: Pausing after run of step 'stepTagEBSVolumes'. Press enter to continue.
==> amazon-ebs: Waiting for auto-generated password for instance...
    amazon-ebs: It is normal for this process to take up to 15 minutes,
    amazon-ebs: but it usually takes around 5. Please wait.
    amazon-ebs:
    amazon-ebs: Password retrieved!
    amazon-ebs: Password (since debug is enabled):
==> amazon-ebs: Pausing after run of step 'StepGetPassword'. Press enter to continue.
==> amazon-ebs: Waiting for WinRM to become available...
==> amazon-ebs: Timeout waiting for WinRM.
==> amazon-ebs: Terminating the source AWS instance...
```

**Packer code**
_Note that my blank variables come from a variable file specific in -var-file=_

```{
  "variables": {
    "ami_name": "play1",
    "iam_instance_profile": "profile_play1",
    "source_ami": "",
    "vpc_id": "",
    "subnet_id": "",
    "security_group_ids": "",
    "root_volume_size": "60",
    "owner_tag": "",
    "cost_centre_tag": "",
    "hsn_tag": "",
    "user_data_file": "",
    "build_number": "",
    "access_key": "",
    "secret_key": ""
  },
  "builders": [
    {
      "type": "amazon-ebs",
      "ami_name": "{{user `ami_name`}}-{{isotime \"2006-01-02-150405\"}}",
      "iam_instance_profile": "{{user `iam_instance_profile`}}",
      "access_key": "{{user `access_key`}}",
      "secret_key": "{{user `secret_key`}}",
      "region": "eu-west-1",
      "source_ami": "{{user `source_ami`}}",
      "instance_type": "t2.medium",
      "communicator": "winrm",
      "winrm_username": "Administrator",
      "winrm_port": "5985",
      "windows_password_timeout": "30m",
      "vpc_id": "{{user `vpc_id`}}",
      "subnet_id": "{{user `subnet_id`}}",
      "security_group_ids": "{{user `security_group_ids`}}",
      "associate_public_ip_address": "false",
      "user_data_file": "{{user `user_data_file`}}",
      "run_tags": {
          "Name": "{{user `ami_name`}}",
          "Owner": "{{user `owner_tag`}}"
      }, 
      "tags": {
          "Name": "{{user `ami_name`}}",
          "Owner": "{{user `owner_tag`}}",
          "SourceAmi": "{{user `win_2012r2_64_ami_id`}}"
      }
    }
  ],
  "provisioners": [
    {
      "type": "windows-shell",
      "inline": [
        "cmd /c net user /add tempUser hello",
        "cmd /c net localgroup administrators tempUser /add"
      ]
    }
  ]
}
```

**Comment by rickard-von-essen** [comment]
Could you add the ami-id and the user data file. And gist the full output of `PACKER_LOG=1 packer build template.json`.

**Comment by mwhooker** [comment]
I understand the security concerns. Maybe you could run a git bisect for us to find the commit that introduced the bug for you?

The only thing I can think of is that we updated the winrm library

**Comment by dan-rose** [comment]
Hello - 

I think I have noticed there is an issue with this too - building on my local win 10 machine using vmware workstation. 

I raised an issue a while ago with a previous version, that had and error 500 when trying to upload files.  This got fixed, and I was successfully able to upload files to windows servers using winrm

When i came back to this recently, using v1.0, I noticed that it wasn't failing, just not uploading at all.. I meant to come back to this as i thought it was my issue, but perhaps not. 

I will upload some files soon

Dan

**Comment by brettjacobson** [comment]
We've noticed the same thing; our scripts run fine with packer 0.12.1, but just hangs on a "waiting for winrm to become available" step with 1.0.0.  (We're using templates adapted from https://github.com/mwrock/packer-templates)

**Comment by blackwaterdevops** [comment]
Same here building on AWS - works on 0.12.x versions

**Comment by giordyb** [comment]
I also ran into this issue, but I noticed that the windows version of packer 1.0 works fine with WINRM.

**Comment by tjnicholas** [comment]
Hi all. 

We're seeing the same behaviour here but I think we understand why. In our case it appears to be related to running behind a proxy. 

With versions after 2.12.3 Packer is honouring the environment's proxy configuration (#4463) which means that if you are using a proxy it will attempt to connect through it. 

Unfortunately (for our purposes) Packer uses the ec2 private IP rather than the private DNS name. This means that it is close to impossible to configure the `no_proxy` environment variable to avoid using the proxy when connecting to an internal instance.

I believe WinRM uses the [SSHHost](https://github.com/hashicorp/packer/blob/e67d1fd676f4b5de70a53f4faa62046d83766a1f/builder/amazon/common/ssh.go#L28-L44) methods to get the host address. I guess that should be extended to include the option of using the private DNS address rather than IP so that the appropriate proxy exclusions are possible. 

A new `ssh_private_dns` configurable would need to be added, complementing the existing [ssh_private_ip](https://www.packer.io/docs/builders/amazon-ebs.html#ssh_private_ip) option.

**Comment by rickard-von-essen** [comment]
@tjnhicolas that sounds like it could be the issue. How would getting the public/private dns name help? 

Maybe this have to be an option for this, say `winrm_use_proxy`. When `true` packer automatically adds the IP to `NO_PROXY`.

**Comment by tjnicholas** [comment]
@rickard-von-essen If the private DNS name was used, the zone it is in (`us-west-2.compute.internal` or similar) could be added to the `no_proxy` environment variable. In many cases that would already be configured. 

`winrm_use_proxy false` could possibly be easier/simpler. I'd be concerned that it would have unpredictable results if any other process within the packer run was affected, but I can't think of anything else that would be attempting http style connections to the remote host.

**Comment by mwhooker** [comment]
Is it possible to run packer without the proxy environment variables set?

**Comment by tjnicholas** [comment]
@mwhooker Unfortunately not. If the environment has a proxy server it is likely it will need to be used to access the EC2 API endpoints. 

For comparison, [kitchen-ec2](http://www.rubydoc.info/gems/kitchen-ec2/1.3.2#Network_and_Communication_Configuration) provides a way of selecting between the public IP, the private IP, the public DNS name or the private DNS name. 

We've had Test Kitchen configured with `interface: private_dns` for some time, so a equivalent feature in Packer would be good.

**Comment by mwhooker** [comment]
okay I think that makes sense. I like the prior art in kitchen-ec2. Perhaps we should deprecate `ssh_private_dns` and add a new option which lets you choose from the 4 connection options. We can write a fixer for this as well. What do you think, @rickard-von-essen?

If anyone wants to implement this, I'll be happy to advise. Otherwise, I may be able to get to it in the coming weeks.

**Comment by rickard-von-essen** [comment]
> Perhaps we should deprecate ssh_private_dns and add a new option which lets you choose from the 4 connection options.

Sound good.

@tjnicholas Seems a bit strange to me that you would need to pass the proxy to access the EC2 API endpoints but at the same time can't reach the EC2 instance via the proxy.

**Comment by tjnicholas** [comment]
@rickard-von-essen We run our build agents (that execute packer) within AWS in a VPC behind a proxy. The AMIs are created in the same VPC, or within a peered VPC.

**Comment by rickard-von-essen** [comment]
@tjnicholas yeah, that make sense. Thanks for clarifying.

**Comment by mminkus** [comment]
I can confirm this problem affects us too. We have jenkins/packer run in a private vpc, trying to bake windows ami's. We are in a private vpc behind a proxy. We're stuck using an older version of packer (0.12.1) from before this regression was introduced. Have not been able to find a work around, as I cannot list every single vpc private ip address into no_proxy, and you can't use cidr ranges in no_proxy.

**Comment by dhermans** [comment]
hi all - can I +1 this issue as well.
We find using winrm over a proxy a bit unreliable. My guess is that packer -> load balanced proxy -> instance will use different round robin proxy ( ttl is 60secs ) and so bounce via a different source IP. WinRM seems to care about this and the provisioner never connects.

Our workaround is to have only a single proxy in the pool during builds which is a bit lame..

**Comment by jvanderpaal** [comment]
Hitting Winrm directly would be great because our proxies aren't supposed to handle internal addresses, we can't lock it down until this issue is resolved.

**Comment by marcelvanderperk** [comment]
Seems I have run into this issues as well. Being able to select the private dns name for communication would solve everything. Has anyone made any progress on this item?

**Comment by ChrisMoran64** [comment]
We are also hitting this issue, and as jvanderpaal noted, we're stalled because the proxies are not going to handle internal traffic.  Some form of proxy bypass would be ideal

**Comment by mwhooker** [comment]
to be clear, setting `NO_PROXY="*"` isn't a valid solution for all of you?

**Comment by vrivellino** [comment]
> to be clear, setting NO_PROXY="*" isn't a valid solution for all of you?

@mwhooker: Correct, it is not a valid solution for us . We need most API calls (for example, AWS API calls) to go out through our egress proxy, but packer connects directly to the EC2 instance it's configuring/imaging.

**Comment by mwhooker** [comment]
I see, that makes more sense. thanks!

**Comment by mwhooker** [comment]
@vrivellino any chance you'd be able to test the pr in #5630?

The theory is that you set the `ssh_interface` to public/private_dns and then set `NO_PROXY="*.amazonaws.com"` I believe

**Comment by vrivellino** [comment]
@mwhooker I'd be happy to give it a try.  Dumb question: how do I get a build of that branch?

**Comment by mwhooker** [comment]
@vrivellino not a dumb question at all, that's one of the trickiest parts about testing branches, and something we're trying to improve. You can either follow the instructions to make a build here https://github.com/hashicorp/packer/blob/master/CONTRIBUTING.md#setting-up-go-to-work-on-packer and here: https://github.com/hashicorp/packer/blob/master/CONTRIBUTING.md#working-on-forks

or you can tell me your OS and I will make a build for you

**Comment by ChrisMoran64** [comment]
NO_PROXY=”*” is not an option for us either

**Comment by dhermans** [comment]
hi - i can also volunteer to test quite quickly if a build is available

linux x64

**Comment by mwhooker** [comment]
@dhermans, here's the build for linux/amd64 [5630.zip](https://github.com/hashicorp/packer/files/1516228/5630.zip)

**Comment by dhermans** [comment]
hi @mwhooker 
Thanks for promptly providing the test packer

I have tried it out without success, added "ssh_interface": "private_dns" to my template

test 1 - I added my private DNS zone to the no_proxy variable
this failed. Monitoring proxy logs I can see that packer is using the AWS provided DNS zone, eg
POST http://ip-10-39-128-185.ap-southeast-2.compute.internal:5985/wsman

Note that I can use my own zone to lookup this host ( which would have worked ):
nslookup ip-10-39-128-185.[my zone]
Name:   ip-10-39-128-185.[my zone]
Address: 10.39.128.185

test 2 - i added ap-southeast-2.compute.internal to no_proxy
this doesn't work either as the AWS CLI wants to go to the EC2 API which lives in the same zone, eg:

netstat -t|grep SYN
tcp        0      1 ip-10-39-128-124.:52924 54.240.195.127:https    SYN_SENT


i can see why this occurs because there is no way from the AWS API to find out that the VPC you operate in happens to be using a private zone and that you have 'dns name resolution' on. all the attributes in the console and in the cli show the [region].compute.internal DNS name


I can see two possible solution - 
- I will check if the new VPC endpoints feature may assist here. VPC endpoints creates an ENI based gateway to the EC2 API from within your VPC. No proxy required.

- can we pass in the private DNS zone name to the template? Then a ssh_interface_zone or similar to tell it what zone to look at.

then it would take the hostname of the newly created instance, strip off the [region].compute.internal and replace with the required parameter. Then no_proxy would work ( as the private zone would be added to no_proxy )

thanks!!

**Comment by tjnicholas** [comment]
Hmm. @dhermans can you clarify this? 

>test 2 - i added ap-southeast-2.compute.internal to no_proxy
>this doesn't work either as the AWS CLI wants to go to the EC2 API which lives in the same zone, eg:
>
>netstat -t|grep SYN
>tcp 0 1 ip-10-39-128-124.:52924 54.240.195.127:https SYN_SENT

As I understand it the EC2 API should be on the address `ec2.<region>.amazonaws.com` which shouldn't be exclude by the domain you mention above.

**Comment by dhermans** [comment]
Hi @tjnicholas 
i did think it odd at the time as well - let me re-run with some debug and see what i can find!

**Comment by dhermans** [comment]
a bit in the future @tjnicholas  but do you think this go language enhancement :

https://go-review.googlesource.com/c/go/+/75730

may the problem via a different path? It seems to suggest no_proxy on ports or CIDR may be available in the go http lib soon (or is already if i can read that page correctly)

**Comment by tjnicholas** [comment]
@dhermans That's does look like it'll make no_proxy much more easy to configure correctly for go projects (if http client is using the IP address directly, as Packer is). 

Interestingly undiscoverable though as I don't know of any other implementations that interpret the no_proxy variable in that way.

**Comment by tjnicholas** [comment]
@dhermans It [looks like](https://github.com/hashicorp/packer/pull/5630#issuecomment-349464400) @johndaviesco tested the PR with `.internal` in the exclusion list. That should have been equivalent to your "test 2".  

I do wonder how picky Go is being about the presence or absence of the leading dot. I work with John and just checked - we're actually setting `internal,.internal` (along with other irrelevant entries).

**Comment by dhermans** [comment]
hi @tjnicholas  - not sure what i did wrong but i re-ran with :

export no_proxy=localhost,169.254.169.254,ap-southeast-2.compute.internal

and it worked fine! sorry about that - all working perfectly...
