### ISSUE TITLE
Packer is trying to SSH to localhost instead of remote IP (Triton builder)

### ISSUE THREAD

**Issue by pannon** [hashicorp/packer#4864]
Configured Packer to use the Triton builder on an OpenBSD 6.0 client.

The Triton image instance is successfully created, but once it gets to the Shell Provisioner part, Packer is simply trying to SSH to the client's localhost address instead of the remote Triton instance's IP address.

The OpenBSD client's /var/log/authlog is full of SSH connection attempts from localhost to localhost.
This is also visible with `netstat -an`.

Not sure whether this is a bug in Triton builder or the OpenBSD Packer version (1.0.0).
Could do some more testing on a Linux client.

**Comment by rickard-von-essen** [comment]
Please supply the information requested in the issue template:
- Packer version (`packer version`)
- Host platform (`uname -a` etc.)
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a [gist](https://gist.github.com).
- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your [gist](https://gist.github.com).

**Comment by pannon** [comment]
Please see below:
 - packer version: `Packer v1.0.0`
 - uname: `OpenBSD hostname... 6.0 GENERIC.MP#2319 amd64`
 - [template.json](https://gist.github.com/pannon/1b07ecce6e17c87877169ecd83ae8014)
 - [packerlog.txt](https://gist.github.com/b6004a40d7ca48752473d99401278130.git)

**Comment by pannon** [comment]
Managed to test this with a CentOS Linux client as well.
Same result, it is trying to SSH to localhost - we can rule out OpenBSD.

I start to think it is defaulting to localhost as the Triton builder might be returning an incorrect address or no address?

**Comment by rickard-von-essen** [comment]
What's the output of:

```bash
$ triton instance ip image-builder
```

During the build? It should give the IP which packer tries to connect to.

**Comment by rickard-von-essen** [comment]
It would be great if you could try repro this against Joyent Public Cloud. Most likely this is a problem with your triton setup of a setup that the author of the triton builder didn't anticipate.

**Comment by pannon** [comment]
`triton instance ip image-builder` shows the correct IP address - and I can SSH in just fine using that IP address.

We need this working against our on-prem Triton - although I can test it against JPC. The only difference I can think of in terms of network is that we don't use a network called "external", instead we have many different networks.

**Comment by pannon** [comment]
Did some digging and possibly this could be caused by the following issue https://smartos.org/bugview/PUBAPI-1291 - I will try and patch our CloudAPI and report back.

**Comment by pannon** [comment]
OK, so turns out I guessed it right. Patching our CloudAPI with the fixed file [machines.js](https://raw.githubusercontent.com/joyent/sdc-cloudapi/master/lib/machines.js) fixes Packer SSH connectivity! Thanks for looking at this.
