### ISSUE TITLE
packer shell provisionner docker 

### ISSUE THREAD

**Issue by madis972** [hashicorp/packer#4868]
Hi Packer team,
I'm try to use file provisioner and ansible provisioner with docker builder.It is seem that fail when the file provisioner start for ansible provisioner everything is good. I'm using packer v1 on a debian 8 host.

**Comment by rickard-von-essen** [comment]
Please supply the information requested in the issue template:
- Packer version (`packer version`)
- Host platform (`uname -a` etc.)
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a [gist](https://gist.github.com).
- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your [gist](https://gist.github.com).
