### ISSUE TITLE
'vmware-iso' errored: Error registering VM: Stdout: (vmodl.fault.InvalidArgument) 

### ISSUE THREAD

**Issue by dan-rose** [hashicorp/packer#4869]
Hello 

I have a problem using vmware-iso, building a vm on a remote ESXi host.

The output from packer is [here](https://gist.github.com/dan-rose/dafa362ef13310f3732bd4c891902564)

Packer v1.0
Windows 10 workstation
VMware ESXi, 6.0.0, 4510822

    "type": "vmware-iso",
    "remote_type": "esxi5",
    "remote_host": "barvhl01.infra.local",
    "remote_datastore": "C3_VM_DR_Live_Orig",
    "remote_cache_datastore": "C3_VM_DR_Mgmt",
    "remote_cache_directory": "ISO",
    "remote_username": "####",
    "remote_password": "#######",
    "skip_compaction": "true",
    "keep_registered": "true",

The error is thrown when the process is attempting to register the VM with the host

Stdout: (vmodl.fault.InvalidArgument) {
   faultCause = (vmodl.MethodFault) null, 
   invalidProperty = "pool", 
   msg = "A specified parameter was not correct: pool"
}

I wonder with the later versions of ESXi requires the resource pool to stated as part of the registration process, where as on previous versions it did not?

This has worked previously for me on ESXi 5 hosts

Has any one else seen this issue?? 

Any assistance is gratefully received

Dan

**Comment by dan-rose** [comment]
Thanks for getting back to me

Is this what you need?? - [gist](https://gist.github.com/dan-rose/a20791eebcf053992b8b6d05b8cd495a)

**Comment by rickard-von-essen** [comment]
Yes and the content of the floppy files and can you write out exactly the
version of esxi and Windows (you are trying to build).

**Comment by dan-rose** [comment]
Hey,

VMware ESXi, 6.0.0, 4510822
Building Windows Server 2016 from ISO - SW_DVD9_Win_Svr_STD_Core_and_DataCtr_Core_2016_64Bit_English_-3_MLF_X21-30350.ISO

The floppy files contain an autounattend.xml and a basic ps script. I have added them [here,](https://gist.github.com/dan-rose/3e7af2fd322d68baff5c0b167bfc1628) and [here](https://gist.github.com/dan-rose/b8b89e538083d06c47886eef4e4c9790)

**Comment by SwampDragons** [comment]
@dan-rose did you ever get this working? I hope so, but if you did not, the [mailing list](https://groups.google.com/d/forum/packer-tool) is probably a better place to ask general questions like this. If you think there's a bug or have a more definitive explanation of the regression you're seeing, please feel free to open a new ticket.

**Comment by dan-rose** [comment]
hello @SwampDragons . Not sure now if I fixed it or what, however I can currently successfully build to ESXi at the moment! Thanks for the link to the mailing list

Dan
