### ISSUE TITLE
amazon-ebs fails to set up all the configured security groups

### ISSUE THREAD

**Issue by cristim** [hashicorp/packer#4870]
- Packer version: Packer v1.1.0-dev, compiled as of today using `go get -u`
- Host platform: Ubuntu Linux 17.04 amd64
- Debug log output from `PACKER_LOG=1 packer build template.json - can't attach it all, since there may be sensitive information, but the relevant bits are shown below:
```
[...]
packer-builder-amazon-ebs: 2017/05/10 15:53:17 Config: {PackerConfig:{PackerBuildName:amazon-ebs PackerBuilderType:amazon-ebs 
[...]
SecurityGroupId: SecurityGroupIds:[sg-975b3bec sg-9bd5d80d]
[...]
```
The instance is created with only the last group instead of both specified groups:
 ```
"SecurityGroups": [
                        {
                            "GroupName": "MyGroup", 
                            "GroupId": "sg-9bd5d80d"
                        }
                    ], 
```

- The _simplest example template and scripts_ needed to reproduce the bug: replace FOO and BAR below with two groups existing in your AWS account.

```
{
	"builders": [
		{
			"type": "amazon-ebs",
			"security_group_ids": ["sg-FOO", "sg-BAR"]
			"region": "us-east-1",
			"source_ami": "ami-e975cbff",
			"instance_type": "t1.micro",
			"ssh_username": "ec2-user",
			"temporary_key_pair_name": "packer",
			"ssh_timeout": "5m",
			"ami_name": "{{timestamp}}-test",
			"iam_instance_profile": "my-ami-role"
		
		}
	],
	"provisioners": [
		{
			"type": "shell",
			"inline": [
				"touch /tmp/foo"
			]
		}
	]
}
```
With the above template you'll just get the sg-BAR group attached to your instance, and in case that group doesn't allow SSH from your host, the image will likely even fail to build.

**Comment by rickard-von-essen** [comment]
Need to see ~200 first lines of your debug log at least to sanity check your install.

**Comment by cristim** [comment]
@rickard-von-essen please have a look at the private gitter.im chat I created with you

**Comment by rickard-von-essen** [comment]
Your install is broken. Remove your current install directory and reinstall from [packer.io/downloads](https://www.packer.io/downloads.html). _Be sure to read the [**note** about upgrading from < 0.9.0.](https://github.com/hashicorp/packer/commit/1994793126f948dd99c8acdd35f999df0c6ab342)_

**Comment by cristim** [comment]
Thanks,I will fix my setup.

Still,I would expect packer to detect this kind of issue, bail out instead of using those remnants of previous installations and point the users to those fix instructions.

**Comment by rickard-von-essen** [comment]
It's valid way of overriding plugins, but there should be a fat warning. But this is starting to become less and less common since it was so long time since we switched the way Packer is distributed.
