### ISSUE TITLE
builder/amazon: add retry logic when creating Instance tags

### ISSUE THREAD

**Issue by luis-silva** [hashicorp/packer#4875]
I'm finding intermittent failures with the error _InvalidInstanceID.NotFound_ when tagging the ec2 builder instance using the amazon-ebs builder. Usually, re-running the same command again succeeds so it is an intermittent issue, most likely related to the eventual consistency in AWS.

- Packer version: 1.0.0
- Host platform: Ubuntu 16.04.2 LTS GNU/Linux 4.4.0-66-generic x86_64
- Executed as a jenkins job

> 10:03:19 ==> amazon-ebs: Prevalidating AMI Name...
> 10:03:21     amazon-ebs: Found Image ID: ami-80861296
> 10:03:21 ==> amazon-ebs: Creating temporary keypair: packer_591436e7-a095-c5a1-c404-ff0324838bfb
> 10:03:21 ==> amazon-ebs: Launching a source AWS instance...
> 10:03:21     amazon-ebs: Finding spot price for Linux/UNIX m4.large...
> 10:03:21     amazon-ebs: Requesting spot instance 'm4.large' for: 0.0331
> 10:03:22     amazon-ebs: Waiting for spot request (sir-feki46sk) to become active...
> 10:03:32     amazon-ebs: Instance ID: i-0a8830520d6fa3196
> 10:03:32 ==> amazon-ebs: Waiting for instance (i-0a8830520d6fa3196) to become ready...
> 10:03:45 ==> amazon-ebs: Adding tags to source instance
> 10:03:45     amazon-ebs: Adding tag: "jenkins-build-number": "2"
> 10:03:45     amazon-ebs: Adding tag: "jenkins-job-name": "test_build"
> 10:03:45     amazon-ebs: Adding tag: "Name": "Packer Builder"
> 10:03:45 ==> amazon-ebs: Error tagging source instance: InvalidInstanceID.NotFound: The instance ID 'i-0a8830520d6fa3196' does not exist
> 10:03:45 ==> amazon-ebs: 	status code: 400, request id: ae9ae6ab-010d-4899-ae25-7211185b2e9b
> 10:03:45 ==> amazon-ebs: Cancelling the spot request...
> 10:03:45 ==> amazon-ebs: Terminating the source AWS instance...
> 10:04:13 ==> amazon-ebs: No volumes to clean up, skipping
> 10:04:13 ==> amazon-ebs: Deleting temporary keypair...
> 10:04:14 Build 'amazon-ebs' errored: Error tagging source instance: InvalidInstanceID.NotFound: The instance ID 'i-0a8830520d6fa3196' does not exist
> 10:04:14 	status code: 400, request id: ae9ae6ab-010d-4899-ae25-7211185b2e9b
> 10:04:14 
> 10:04:14 ==> Some builds didn't complete successfully and had errors:
> 10:04:14 --> amazon-ebs: Error tagging source instance: InvalidInstanceID.NotFound: The instance ID 'i-0a8830520d6fa3196' does not exist
> 10:04:14 	status code: 400, request id: ae9ae6ab-010d-4899-ae25-7211185b2e9b
> 10:04:14 
> 10:04:14 ==> Builds finished but no artifacts were created.

This is my configuration:

```json
{
    "builders": [
        {
            "ami_description": "Packer built AMI",
            "ami_name": "test-ami",
            "ami_users": [
                "XXX"
            ],
            "associate_public_ip_address": "false",
            "instance_type": "{{user instance_type}}",
            "region": "{{user region}}",
            "run_tags": {
                "jenkins-build-number": "{{user build_number}}",
                "jenkins-job-name": "{{user job_name}}"
            },
            "security_group_id": "{{user security_group_id}}",
            "source_ami": "{{user source_ami}}",
            "spot_price": "{{user spot_price}}",
            "spot_price_auto_product": "Linux/UNIX",
            "ssh_private_ip": "true",
            "ssh_username": "{{user ssh_username}}",
            "subnet_id": "{{user subnet_id}}",
            "tags": {
                "jenkins-build-number": "{{user build_number}}",
                "jenkins-job-name": "{{user job_name}}",
                "source_ami": "{{ .SourceAMI }}"
            },
            "type": "amazon-ebs",
            "vpc_id": "{{user vpc_id}}"
        }
    ],
    "variables": {
        "build_number": null,
        "instance_type": null,
        "job_name": null,
        "region": null,
        "security_group_id": null,
        "spot_price": null,
        "ssh_username": null,
        "subnet_id": null,
        "vpc_id": null
    }
}
```

I found a similar issue raised and fixed before: [3938](https://github.com/hashicorp/packer/pull/3938) but that one was for AMI / Snapshot tags, not instance tags. It looks to me that the current problem is that there's no retry logic in the instance tagging code [here](https://github.com/hashicorp/packer/blob/81522dced0b25084a824e79efda02483b12dc7cd/builder/amazon/common/step_run_source_instance.go#L279-L303).

Can anyone with more knowledge of packer review this issue and confirm if that is indeed what is going on and if we can apply a similar fix to this story (import the common retry logic and apply it to this tagging process)?

**Comment by mwhooker** [comment]
seems like a reasonable conclusion. Would gladly accept a PR for this

**Comment by luis-silva** [comment]
@mwhooker I tested the new binary a few times and it worked every single time. The approach is pretty much the same as used on the AMI tagging code and all tests are green so this should be ready to merge.

**Comment by Sk8rMarc** [comment]
I'm trying to build an AMI for a g2.8xlarge instance type and am having issues.  Packer terminates leaving the created instance running, and abends with "Error tagging source instance ... does not exist"  reporting status 400 and InvalidInstanceID.NotFound.  I'm sorry, I'm in a crunch, but my work around was to simply remove the run_tags object which allows the amazon-ebs builder to complete.
