### ISSUE TITLE
hyperv-iso: cleans up powershell script in on-error=abort case

### ISSUE THREAD

**Issue by ecki** [hashicorp/packer#4877]
I am testing packer with the hyperv-iso builder on my local Windows 10 machine. Currently it has the problem that it has no connection to the AD domain, however I can run packer as the local Administrator.

When I start packer to build a sample VM from ISO it seems to run a powershell script which itself fails to validate the user permissions. I wanted to debug this script, however using `-debug -on-error=ask` does not work for this error, the script seems to be deleted at the end of the run:

    $ packer build -debug -on-error=abort test.json
    Build 'hyperv-iso' errored: Failed creating Hyper-V driver: PowerShell error: Ausnahme beim Aufrufen von "IsInRole" mit 1 Argument(en):  "Die Vertrauensstellung zwischen dieser Arbeitsstation und der prim�ren Dom�ne konnte nicht hergestellt werden.
    "
    In C:\Users\Administrator\AppData\Local\Temp\ps585960735.ps1:1 Zeichen:1
    + ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIden ...
    ...
    ==> Builds finished but no artifacts were created.

After this, the psxxx.ps1 file is not present in the temporary directory. I would expect it obseres the on-error setting and let me debug that file. `-on-error=ask` does not ask me either (most likely as it is too early in the build?)

On a related note, can I disable this"IsInRole" check? The test.json has no provisioner, only the builder type hyperv-iso with a single shutdown command.

**Comment by mwhooker** [comment]
probably not related, but similar to #4795

**Comment by ecki** [comment]
@mwhooker regarding the label, is this provisioner/pwershell? it only has builder/hyperv-iso used (but it might internally reuse the provisioner code)

**Comment by mwhooker** [comment]
just re-reading your issue now, and I see your issue is with the hyper-v builder itself running a script. I wouldn't expect those scripts to stay around, regardless of the `-on-error` status.

digging into the isinrole call

**Comment by mwhooker** [comment]
This change was introduced in #4318

@tadas or @taliesins any thoughts on a proper fix?

**Comment by ecki** [comment]
I [found](https://github.com/hashicorp/packer/blob/81522dced0b25084a824e79efda02483b12dc7cd/builder/hyperv/common/driver_ps_4.go#L300) the command and it seems I cannot skip it

    PS C:\Users\Administrator> ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole('Hyper-V Administrators')
    Ausnahme beim Aufrufen von "IsInRole" mit 1 Argument(en):  "Die Vertrauensstellung zwischen dieser 
    ...

Dont worry too much about my broken Windows. I will get it fixed. I was just asuming that the abort-cleanup applies to all modules. It does not seem to apply to `powershell.PowerShellCmd`

**Comment by mwhooker** [comment]
It might be a good idea to not remove the file if `on-error=ask` is set. I did notice, however, that you can set the env variable `PACKER_POWERSHELL_DEBUG=1` to make all powershell commands skip removing files.

**Comment by ecki** [comment]
positive, the env variable works. If you want you can close this at wont-fix or adjust the title for the planed adjustments.

**Comment by mwhooker** [comment]
I'm going to close this for now. I think it might be reasonable, like I said, to expect `on-ask=abort` to not remove every file created through a remote command, but the code is not structured to facilitate that. I think if someone thought that was a good idea and wanted to propose a way to implement it, that would be fine.

Glad things are working for you now.
