### ISSUE TITLE
Hyper-V "enable_dynamic_memory" property has no effect

### ISSUE THREAD

**Issue by lavahot** [hashicorp/packer#4880]
On Windows 10, packer 1.0.0 building an Ubuntu 16.04.02 LTS box with hyperv-iso builder.

I have run into an issue where I get an error: "PCI: Fatal: No config space access function found". I read somewhere that turning off dynamic memory would fix this. I tried adding the appropriate property as ("enable_dynamic_memory": false,) , but the generated VM is always using dynamic memory. 

[Gist](https://gist.github.com/lavahot/9b3ecd4f44fa9d320429325cd53f48b6)

**Comment by lavahot** [comment]
Sorry about not having all the info there.

**Comment by it-praktyk** [comment]
I confirm - I observed it today - Hyper-V on Windows 10.

If do you need help for PowerShell side of Hyper-V builder please let me know.

**Comment by taliesins** [comment]
I think the code is in place to do it:
https://github.com/hashicorp/packer/blob/master/builder/hyperv/iso/builder.go#L80
https://github.com/hashicorp/packer/blob/master/builder/hyperv/common/step_create_vm.go#L55
https://github.com/hashicorp/packer/blob/master/builder/hyperv/common/driver_ps_4.go#L185
https://github.com/hashicorp/packer/blob/master/common/powershell/hyperv/hyperv.go#L247

The only thing I could think that is going wrong is that the powershell commandlet has not effect. 

Please run this from powershell once a machine has been spun up (turn off the vm as well):

`Set-VMMemory -VMName $vmName -DynamicMemoryEnabled $enableDynamicMemory`

**Comment by evancox10** [comment]
I will take a look at this soon, I've seen this also and found it strange.

I also wanted to point out that for dynamic memory we should consider exposing the Min/Max settings as config parameters for the user. For dynamic memory enabled VMs, StartupBytes is only used during boot up and/or if something goes wrong with the dynamic memory process. This parameter would continue to function as normal, we would just add dynamic_mem_min/max config parameters for the user to control.

**Comment by taliesins** [comment]
@evancox10 can you confirm if `Set-VMMemory -VMName $vmName -DynamicMemoryEnabled $enableDynamicMemory` has any effect. 

Ignore Packer all together.

I think we should be able to specify min and max

**Comment by gavincampbell** [comment]
I'll try it in a few minutes when my Windows VM with 900MB of RAM has finished building!

**Comment by batzen** [comment]
The Problem is that `false` is not being set at all.
Code says:
https://github.com/hashicorp/packer/blob/634fd42b99cb2d7a4354739c6cd143ae48e3ccb9/builder/hyperv/common/step_create_vm.go#L54

The same for `EnableMacSpoofing` and `EnableVirtualizationExtensions`.
Those only get set if they are `true`.

Microsoft, in case of dynamic memory, seems to have change the default from `false` to `true`, so disabling this again with packer is currently impossible.

**Comment by mwhooker** [comment]
Should be fixed now. Can anyone confirm that this works?

**Comment by strarsis** [comment]
@mwhooker: Just had this issue with latest vagrant, 
bento/ubuntu image (for hyper-v) and hyper-v and Windows 10 Pro x64.

**Comment by SwampDragons** [comment]
This ticket's several releases old and is probably referencing a different issue. Can you please open a new issue with full steps to reproduce and debug logs?
