### ISSUE TITLE
'packer build -only=virtualbox-iso application-server.json' fails

### ISSUE THREAD

**Issue by dodoind** [hashicorp/packer#4881]
Command 'packer build -only=virtualbox-iso application-server.json' fails due to checksum error:

$ packer build -only=virtualbox-iso application-server.json
virtualbox-iso output will be in this color.
==> virtualbox-iso: Downloading or copying Guest additions
    virtualbox-iso: Downloading or copying: file:///C:/Program%20Files/Oracle/VirtualBox/VBoxGuestAdditions.iso
==> virtualbox-iso: Downloading or copying ISO
    virtualbox-iso: Downloading or copying: http://releases.ubuntu.com/trusty/ubuntu-14.04.4-server-amd64.iso
    virtualbox-iso: Error downloading: checksums didn't match expected: 07e4bb5569814eab41fafac882ba127893e3ff0bdb7ec931c9b2d040e3e94e7a
==> virtualbox-iso: ISO download failed.
Build 'virtualbox-iso' errored: ISO download failed.

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: ISO download failed.

==> Builds finished but no artifacts were created.

- Packer version: 1.0.0
- Host platform: windows 10 64bit
Log:
https://gist.github.com/dodoind/8d9247364b0b62e9d620b4d909c90242

Sorry, incase this is a duplicate issue.

**Comment by rickard-von-essen** [comment]
The checksum and the content of what you try to download doesn't match. Check your URL, checksum and checksum type.
