### ISSUE TITLE
[question] docker containers from scratch via packer

### ISSUE THREAD

**Issue by shibumi** [hashicorp/packer#4883]
Hello,
I would like to generate a docker image out of an ISO or a tarball with a base system. So something like this:

```
FROM scratch
ADD archlinux.tar /
CMD ["/usr/bin/bash"]
```

Can I do this with `packer`? I read the documentation: https://www.packer.io/docs/builders/docker.html
But it looks like you only support the other way around. So that I pull a docker image, make some changes, and recommit or export it as a tarball.

**Comment by mwhooker** [comment]
Hi,

What you read in the docs is correct, we don't support building a docker image from scratch just yet. That does seem like it would be handy, though.

We've got other things we're focusing on right now, however, so this change would have to come from the community. If someone wants to submit an RFC laying out a plan for implementing this, I would be happy to review, but closing for now since we're not planning on working on it and would hate for the issue to stagnate.

**Comment by kefoster** [comment]
This would be nice!  I'm looking to roll my own docker images of old OS's to replace build systems.  Packer seemed like the perfect fit until I couldn't do from scratch.

**Comment by oreza** [comment]
Did that made it in?

**Comment by azr** [comment]
Nope, unfortunately, the status of this request is still the same. But after reading this https://github.com/hashicorp/packer/pull/7127#issuecomment-448871713.
I realised if you wanted for example to just add a binary to a docker image, you could just

1. I have binaries `packer-linux` `packer-linux-real` that are the same file copied
2. builld this:
```json
{
    "provisioners": [
    ],
    "builders": [
      {
        "type": "file",
        "target": "packer-linux",
        "source": "packer-linux-real"
      }
    ],
    "post-processors": [
        [
            {
                "keep_input_artifact": true,
                "type": "compress",
                "output": "packer-linux.tar.gz"
            },
            {
                "keep_input_artifact": true,
                "type": "artifice",
                "files": [
                    "packer-linux.tar.gz"
                ]
            },
            {
                "keep_input_artifact": true,
                "type": "docker-import",
                "repository": "hashicorp/packer",
                "changes": [
                  "ENTRYPOINT [\"/packer-linux\"]"
                ]
            }
        ]
    ]
}
```

Now when I  `docker run hashicorp/packer` it works.

This is very hacky thought 🙂
