### ISSUE TITLE
DigitalOcean: Allow multiple regions for snapshots

### ISSUE THREAD

**Issue by dansteen** [hashicorp/packer#4884]
Hi!  Thanks for this great work!   

It looks like, currently, you can only provide a single region for digitalocean snapshots.  However, DigitalOcean allows a single snapshot to be made available in multiple regions.  It would be great if we could specify an array of regions in the packer template that the snapshot will then be available in.  Thanks!

-Dan

**Comment by lfarnell** [comment]
@mwhooker I'm going to send a PR for this but just wanted to clarify my ideas before I sent it. Would you prefer for me to modify the Region field in the Config struct to be a string array or move the Region field to the stepSnapshot struct and implement the functionality in the run function? Hopefully that makes sense to you

**Comment by mwhooker** [comment]
@lfarnell thanks, that would be awesome.

Most important for us is maintaining backwards compatibility. To that end, we shouldn't change the region option at all. 

In the amazon builder, we have an [`ami_regions`](https://www.packer.io/docs/builders/amazon-ebs.html#ami_regions) field which is a list of regions to copy the ami to, in addition to the current region.

I think having another field like `snapshot_regions` which you can union with the value in `region` makes sense. Would also be a good idea, in the prepare step, to validate the regions given against https://developers.digitalocean.com/documentation/v2/#list-all-regions

does that make sense?

**Comment by mwhooker** [comment]
fixed! Thanks @lfarnell
