### ISSUE TITLE
'invalid bind mount spec' when creating docker containers in windows 2016

### ISSUE THREAD

**Issue by iaingblack** [hashicorp/packer#4887]
Hi there,

I am having an issue using Packer to generate a docker image on a windows Server 2016 Machine using native docker containers. This is not using docker for windows or virtualbox etc.., but native containers on the host OS. 

The problem is that the docker run command is not sending the windows path format to docker and not the unix style expected. I have tried setting PACKER_TMP_DIR as something like c/temp and //c/temp  and /c/temp but no joy. The key lines of the issue are below. Does anyone have an way to solve this or advice on fixing? I also tried git bash but it also suffers the same issue as it appears to send the directory in windows format.

```
docker: Run command: docker run -v C:\Users\azureuser\AppData\Roaming\packer.d\tmp\packer-docker060208919:/packer-files -d -i -t microsoft/windowsservercore cmd /c
docker: Stderr: docker: Error response from daemon: invalid bind mount spec "C:\\Users\\azureuser\\AppData\\Roaming\\packer.d\\tmp\\packer-docker060208919:/packer-files": invalid volume specification: 'C:\Users\azureuser\AppData\Roaming\packer.d\tmp\packer-docker060208919:\packer-files'.
```

This is similar to https://github.com/hashicorp/packer/issues/3734 but I think it is worth re-opening as creating images natively on Windows 2016 sounds like a desirable feature.

Packer v1.0.0
Windows Server 2016
Command is  - packer.exe build packer.json
LOG here - https://gist.github.com/iaingblack/54399f1956943cdaf12d9465573ddc91

Thanks
Iain

**Comment by SwampDragons** [comment]
I've created a PR that will address this very specific issue with docker toolbox, but it's worth noting that the Packer Docker builder was written before Docker was available on Windows, and therefore was written with no assumption that there would need to be cross-platform compatibility.  File uploads are super broken in the docker builder on windows, among I'm sure a bunch of other things.  There is a long-term docker rewrite in progress that will probably address the other issues: https://github.com/hashicorp/packer/pull/4186
