### ISSUE TITLE
scripts not being executed on new AMI when using amazon-ebs

### ISSUE THREAD

**Issue by azamsid** [hashicorp/packer#4894]
Verison: Packer v1.0.0
Host: Windows 10 
Generating AMI in AWS using amazon-ebs builder

Description:
I am using Packer to bake images on my on-prem environment and importing them to AWS.
1) I use Windows 2012R2 ISO file to convert it into OVA using virtualbox builder and then import it AWS (ami-dd601dcb). - so far so so good
2) Then I use "amazon-ebs" as I run powershell  script in my provisioner to SYSPREP  to generate the new AMI (ami-54126e42)  - so far so good
3) Now I want to install tools such as java and tomcat on newly generated AMI (ami-54126e42), here I use "amazon-ebs" again, when I execute  packer with provisioners windows-shell, powershell, these scripts dont run. - not good 

```
{
    "variables": {
      "ami_id": "ami-54126e42",
      "app_name": "PccTestHello",
      "aws_access_key": "xxxxxxxxx",
      "aws_secret_key": "xxxxxxxxxxxxx"      
    },

    "builders": [{
      "type": "amazon-ebs",
      "access_key": "{{user `aws_access_key`}}",
      "secret_key": "{{user `aws_secret_key`}}",      
      "region": "us-east-1",
      "source_ami": "{{user `ami_id`}}",
      "instance_type": "t2.medium",
      "user_data_file":"C:\\trim\\packer\\AWS\\ImportedAMI\\init.ps1",
      "communicator": "winrm",
      "winrm_username": "plocaladmin",
      "winrm_password": "plocaladmin",
      "winrm_timeout": "20m",
      "winrm_port":5985,
      "ami_name": "PACKER-{{user `app_name` }}",
      "tags": {
          "Name": "PACKER-{{user `app_name` }}",
          "Env": "Tools"

        }
    }],

    "provisioners": [ 
        {
            "type": "windows-shell",
            "inline": [
                "echo HelloWorld"
            ]
        },
        {
            "type": "powershell",
            "script": "C:\\trim\\packer\\AWS\\HelloWorld\\installJava.ps1"     
        },
        {
            "type": "powershell",            
            "pause_before": "180s",
            "script": "C:\\trim\\packer\\AWS\\HelloWorld\\installTomcat.ps1"        
        }        
    ]

  }
```

The first provisioner is "windows-shell" and it should just print the "HelloWorld", but if you see below the logs when this provisioner is invoked nothing gets printed:

Logs:

https://gist.github.com/azamsid/d01768dd58eb7de5a0c899d45327a2c0
```
C:\trimpacker\AWS\HelloWorld>packer build bake-helloworld.json
amazon-ebs output will be in this color.

==> amazon-ebs: Prevalidating AMI Name...
    amazon-ebs: Found Image ID: ami-54126e42
==> amazon-ebs: Creating temporary keypair: packer_591b0c6c-3f7d-72cc-c36c-60b934f8c6e0
==> amazon-ebs: Creating temporary security group for this instance...
==> amazon-ebs: Authorizing access to port 5985 the temporary security group...
==> amazon-ebs: Launching a source AWS instance...
    amazon-ebs: Instance ID: i-0f059437076cc0b85
==> amazon-ebs: Waiting for instance (i-0f059437076cc0b85) to become ready...
==> amazon-ebs: Adding tags to source instance
    amazon-ebs: Adding tag: "Name": "Packer Builder"
==> amazon-ebs: Skipping waiting for password since WinRM password set...
==> amazon-ebs: Waiting for WinRM to become available...
==> amazon-ebs: Connected to WinRM!
==> amazon-ebs: Provisioning with windows-shell...
==> amazon-ebs: Provisioning with shell script: C:\Users\Admin\AppData\Local\Temp\packer-windows-shell-provisioner489733775
==> amazon-ebs: Provisioning with Powershell...
==> amazon-ebs: Provisioning with shell script: C:\trim\packer\AWS\HelloWorld\installJava.ps1
==> amazon-ebs: Pausing 3m0s before the next provisioner...
==> amazon-ebs: Provisioning with Powershell...
==> amazon-ebs: Provisioning with shell script: C:\trim\packer\AWS\HelloWorld\installTomcat.ps1
==> amazon-ebs: Stopping the source instance...
==> amazon-ebs: Waiting for the instance to stop...
==> amazon-ebs: Creating the AMI: PACKER-PccTestHello
    amazon-ebs: AMI: ami-edd8a7fb
==> amazon-ebs: Waiting for AMI to become ready...
==> amazon-ebs: Adding tags to AMI (ami-edd8a7fb)...
==> amazon-ebs: Tagging snapshot: snap-0b561134d74a410a2
==> amazon-ebs: Creating AMI tags
    amazon-ebs: Adding tag: "Name": "PACKER-PccTestHello"
    amazon-ebs: Adding tag: "Env": "Tools"
==> amazon-ebs: Creating snapshot tags
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Cleaning up any extra volumes...
==> amazon-ebs: Destroying volume (vol-015f349117d05e02f)...
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' finished.

==> Builds finished. The artifacts of successful builds are:
--> amazon-ebs: AMIs were created:

us-east-1: ami-edd8a7fb
```

As you see everything completes successfully but the new ami generated has no tools on it. Also HelloWorld is not printed in the log.

Is there an issue generating a new AMI from an already generated AMI for amazon-ebs?
Please let me know what seems to be wrong here. 

Also when I run the same script on the ami "ami-dd601dcb" generated in step 2, it works fine, and HelloWorld is echoed, see log:

```
==> amazon-ebs: Connected to WinRM!
==> amazon-ebs: Provisioning with windows-shell...
==> amazon-ebs: Provisioning with shell script: C:\Users\Admin\AppData\Local\Temp\packer-windows-shell-provisioner714342227
    amazon-ebs:
    amazon-ebs: C:\Users\pcclocaladmin>echo HelloWorld
    amazon-ebs: HelloWorld
```

Thanks
Azam

**Comment by azamsid** [comment]
Hi
Actually I found the issue, the provisioners scripts are being executed as soon WinRM is Connected, eventhough the server hasn't been fully initialized.

I added pause_before parameter in my provisioner and everything works great:

        {
            "type": "windows-shell",
            "pause_before": "300s",
            "inline": [
                "echo HelloWorld"
            ]
        },

Now my question is, is there a better way to handle it. I dont want to use pause_before parameter as we dont know how long the server might take from 1 minute to few minutes depending on instance type.

Thanks
Azam

**Comment by mwhooker** [comment]
you might be able to enable winrm only when the server has come up fully, but this is a difficult problem and implementation specific, which is why we added the pause_before setting. Closing for now since this is resolved, but you might want to send a message to the mailing list trying to brainstorm ideas on how to know when it's safe to execute your script
