### ISSUE TITLE
Don't create AMI during build using the amazon-ebs builder

### ISSUE THREAD

**Issue by jamesla** [hashicorp/packer#4901]
I'm toying with the idea of using packer for testing in a CI manor.

I'm using the amzon-ebs build and realised if packer could run a build but not actually store the AMI at the end then it would make a really good testing step in our CI pipeline since the steps would be as  close as possible to a real deploy.

Is it possible to run the amazon-ebs builder but skip the final step of creating the AMI?

**Comment by mwhooker** [comment]
funny, 3rd request of this type to come in today. Good news is this will be in the next release. See #4681

**Comment by mwhooker** [comment]
I will mention, though, that, without knowing too many details, I think It's best practice to build an AMI as part of CI. That way you can deploy the AMI, knowing that it's been fully tested.

**Comment by jamesla** [comment]
A mock packer run (not storing the AMI) would be extremely useful because right now we don't have an idea if the build will run until commit to master which is a little late.

**Comment by mwhooker** [comment]
What about setting the ami name to something like "my-company-dev" and
setting force_deregister to true?
