### ISSUE TITLE
VirtualBox Builder: skip_deletion

### ISSUE THREAD

**Issue by srse** [hashicorp/packer#4903]
Feature Description:

Skipping the export is awesome for automated workflows if one just wants to validate a provisioning script can be executed successfully or if one only needs artifacts generated within the virtual environment, but not the environment itself.

I have setup an development environment to write salt scripts that runs them on fresh virtual environments that resemble production specifics. If I extend or change the Salt scripts and they then fail, it would be helpful for debugging to be able to inspect the virtual machine after running packer. So, in addition to skip_export, it would also be great to have skip_deletion (and also if possible skip_halting).

It would save me several minutes waiting for the VM to be exported and then reimported again, before executing the one failing step manually. It would also assist with being able to inspect the state of the VM after a failed step has been run, instead of running it manually after re-importing the VM (which will trigger a boot, that alters the VM state and can make the problem, why the salt step failed, disappear) or of running all the provisioning manually in a fresh VM (which can take some time, if you combine several provisioners and the failing step only just happens in the last one).

If this functionality would not interfere with any other packer principle, it would be great to add it.

**Comment by mwhooker** [comment]
I think you're referring to #4339

I think you're looking for [`-on-error=ask`](https://www.packer.io/docs/commands/build.html#on-error-cleanup), which will let you come in and inspect what's going on if the build fails.

**Comment by srse** [comment]
How could I not look at the command line options for the packer command (not just at the builder and provisioning config options) before writing a ticket? Thanks!
