### ISSUE TITLE
VirtualBox build fails with NS_ERROR_FAILURE

### ISSUE THREAD

**Issue by znerd** [hashicorp/packer#4908]
When running a very simple Packer script for a VirtualBox VM on a CentOS 7.3 system without X11, then `VBoxManage` fails with an error saying:

```
VBoxManage error: VBoxManage: error: The virtual machine 'packer-virtualbox-ovf-1495287397' has terminated unexpectedly during startup because of signal 6
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine
```

Some Googling seems to indicate it may be related to the lack of X11…

My system:
- Packer 1.0.0
- CentOS 7.3/x86_64
- VirtualBox 5.1.22

See:
- https://gist.github.com/znerd/de6ab16a5233a473b2b3451916be2973

**Comment by rickard-von-essen** [comment]
Set `headless` to `true`.

**Comment by znerd** [comment]
I changed that, but it's not resolving the issue. Here's the output:
- https://gist.github.com/znerd/de6ab16a5233a473b2b3451916be2973/raw/dbd5aa829985e9297281b5cbb5cc1980834c8997/headless_true_output.txt

Question: is Packer supposed to support running in a headless environment?

**Comment by znerd** [comment]
Oops. Never mind. The error changed.
