### ISSUE TITLE
Build 'amazon-ebs' errored

### ISSUE THREAD

**Issue by JohannesAtGit** [hashicorp/packer#4913]
Bug:

- Packer version from `1.0.0`
- Host latest Ubuntu in Virtualbox
- Debug log output from `PACKER_LOG=1 packer build template.json`.
https://gist.github.com/JohannesAtGit/d99ca5290ff8fb3392c2a70993eef325
- The _simplest example template and scripts_ needed to reproduce the bug.
  Try to create a packer image for AWS.
  It seems that the deleting of the temporary keypair fails, but the **error message is cryptic and not useful**.

I cannot provide you with template.json, but I certainly can say that it has worked with the same code previously. The only thing, I might have changed is the AWS configuration. E.g. the ami-id

**Comment by rickard-von-essen** [comment]
Your provisioner script exit with code 9.
