### ISSUE TITLE
file provisioner fails to upload file over WinRM if destination path is a directory with no trailing slash

### ISSUE THREAD

**Issue by sandersaares** [hashicorp/packer#4915]
Packer v1.0.0 on Windows 10 Enterprise 15063.296.

Building a Windows Server 2016 Standard image on Hyper-V.

Issue: uploading a single ps1 script fails (packer just freezes at the point indicated in the log). Inspecting the filesystem shows that no such file exists where it was supposed to be uploaded. The directory does exist (it is created before starting WinRM).

The correct (base64-encoded) content for the transmitted file **does** exist in %temp%.

Debug log: https://gist.github.com/sandersaares/43e3b6136a5aa48395cafbc98b5cc245

Template snippet with relevant bits:

```
  "builders": [
    {
      "type": "hyperv-iso",
      "iso_url": "{{ user `iso_url` }}",
      "iso_checksum_type": "none",
      "vm_name": "xxx",
      "switch_name": "xxx",
      "floppy_files": [
        "Autounattend.xml",
        "Initialize.ps1"
      ],
      "communicator": "winrm",
      "winrm_username": "xxx",
      "winrm_password": "xxx",
      "winrm_timeout": "1h"
    }
  ],
  "provisioners": [
    {
      "type": "file",
      "source": "Install-WindowsUpdates.ps1",
      "destination": "C:/Setup"
    }
```

Edit: adding `WINRMCP_DEBUG` provides more log output:

```
017/05/23 09:03:26 [INFO] 341 bytes written for 'uploadData'
2017/05/23 09:03:26 packer.exe: 2017/05/23 09:03:26 Copying file to $env:TEMP\winrmcp-cdbfb558-3073-4619-6f5a-85a6a2c96605.tmp
2017/05/23 09:03:27 packer.exe: 2017/05/23 09:03:27 Moving file from $env:TEMP\winrmcp-cdbfb558-3073-4619-6f5a-85a6a2c96605.tmp to C:\Setup
2017/05/23 09:03:30 packer.exe: #< CLIXML
```

Is it interpreting `C:\Setup` as a file, not a directory? Seems like a possible explanation, though it conflicts with the behavior when uploading a directory (where `C:\Setup` is accepted just fine as the destination directory).

Attachments:

[Autounattend.zip](https://github.com/hashicorp/packer/files/1021165/Autounattend.zip)
[Initialize.zip](https://github.com/hashicorp/packer/files/1021166/Initialize.zip)

**Comment by sandersaares** [comment]
Theory confirmed: it seems to be the trailing slash.

I would interpret this as two related bugs:

* If the WinRM copy fails due to trying to copy a file to a directory (and presumably other similar reasons), no meaningful error is displayed in the log.
* If the destination path is a directroy but has no trailing slash, it is interpreted differently depending on whether the source is a file or directory.

**Comment by rickard-von-essen** [comment]
Could you add the content of `Autounattended.xml` and `initialize.ps1` to make the example complete.

**Comment by sandersaares** [comment]
Attached to OP.

**Comment by SwampDragons** [comment]
Not sure why this was reassigned to 1.1.2.  It's only fixed by a backwards-breaking change so it's slated for 1.2.0 as the above history shows.
