### ISSUE TITLE
"file" provisioner only uses first entry from Sources if processing directories

### ISSUE THREAD

**Issue by sandersaares** [hashicorp/packer#4917]
There appears to be a `Sources` parameter for the file provisioner that allows one to supply multiple source paths.

However, if one of them is a directory, any sources after it will be ignored because the loop in https://github.com/hashicorp/packer/blob/master/provisioner/file/provisioner.go#L147 has a return statement after copying a directory (whereas with files, a return statement is only executed on error).

For example, this:

```
{
      "type": "file",
      "sources": [
        "SetupDocker",
        "SetupComponentHost"
      ],
      "destination": "C:/Setup"
    }
```

Will only result in SetupDocker being copied.

**Comment by maxim-lobanov** [comment]
+1 for this issue, If we can use `sources` for folders, it would simplify packer templates a lot.
This issue is real bug but it is not popular because `sources` option is not defined in documentation. Docs describes only `source` property.


cc: @mwhooker  @azr, @SwampDragons, @sylviamoss doesn't you mind if I prepare PR with fix?

**Comment by sylviamoss** [comment]
@maxim-lobanov go for it! we'll be happy to review your PR 👍

**Comment by maxim-lobanov** [comment]
@sylviamoss , Submitted PR. Please let me know if something else is required.

**Comment by maxim-lobanov** [comment]
@SwampDragons thank you for driving me for merged PR! Really like your [contributing documentation](https://github.com/hashicorp/packer/blob/master/.github/CONTRIBUTING.md).

I also suggest to update documentation: https://www.packer.io/docs/provisioners/file
Currently, it is not mentioned that "file" provisioner allows to specify multiple files with `sources` property.

**Comment by SwampDragons** [comment]
Great minds think alike! I'm working on cleaning the file provisioner docs up right now. 

I'm glad you like the contributor guide; I hope we see you around here again :)
