### ISSUE TITLE
Error deleting volume when Packer attempts to clean up volumes

### ISSUE THREAD

**Issue by luckytaxi** [hashicorp/packer#4925]
Packer v1.0.0 running on CentOS 7

I want to create an image with an additional partition `/dev/sda2`. The image creates fine but I'm encountering the following error when Packer goes to clean up. In my AWS console, both volumes are destroyed so it does "work?"

FYI ... `vol-040860de2a312caeb` is `/dev/sda2`

```json
"launch_block_device_mappings": [
    {
      "device_name": "/dev/sda2",
      "volume_size": 20,
      "volume_type": "gp2",
      "delete_on_termination": true
    }
],
"ami_block_device_mappings": [
    {
      "device_name": "/dev/sda1",
      "volume_size": 20,
      "volume_type": "gp2",
      "delete_on_termination": true
    },
    {
      "device_name": "/dev/sda2",
      "volume_size": 20,
      "volume_type": "gp2",
      "delete_on_termination": true
    }
]
```

```
==> amazon-ebs: Waiting for the instance to stop...
==> amazon-ebs: Creating the AMI: packer-airflow-test 1495643126
    amazon-ebs: AMI: ami-71d29267
==> amazon-ebs: Waiting for AMI to become ready...
==> amazon-ebs: Modifying attributes on AMI (ami-71d29267)...
    amazon-ebs: Modifying: description
==> amazon-ebs: Modifying attributes on snapshot (snap-0355d4897e89efd5e)...
==> amazon-ebs: Modifying attributes on snapshot (snap-094826d2e575264f7)...
==> amazon-ebs: Adding tags to AMI (ami-71d29267)...
==> amazon-ebs: Tagging snapshot: snap-0355d4897e89efd5e
==> amazon-ebs: Tagging snapshot: snap-094826d2e575264f7
==> amazon-ebs: Creating AMI tags
    amazon-ebs: Adding tag: "Name": "ichain-dev-airflow-test"
==> amazon-ebs: Creating snapshot tags
    amazon-ebs: Adding tag: "Name": "packer-airflow-test 1495643126"
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Cleaning up any extra volumes...
==> amazon-ebs: Destroying volume (vol-0e88deefa70b0c115)...
==> amazon-ebs: Destroying volume (vol-040860de2a312caeb)...
==> amazon-ebs: Error deleting volume: InvalidVolume.NotFound: The volume 'vol-040860de2a312caeb' does not exist.
==> amazon-ebs: 	status code: 400, request id: 36af97db-e71e-46df-ab89-62a539165719
==> amazon-ebs: Deleting temporary security group...
Build 'amazon-ebs' finished.
```

**Comment by rickard-von-essen** [comment]
Please supply the information requested in the issue template:
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a [gist](https://gist.github.com).
- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your [gist](https://gist.github.com).

**Comment by luckytaxi** [comment]
Here you go.

https://gist.github.com/luckytaxi/fde791edc067c3b1364c1450546b1a8a

**Comment by luckytaxi** [comment]
So i guess my first question is, what would happen if I remove `"delete_on_termination": true` from the `launch_block_device_mappings` block? My understanding and maybe I'm wrong is that once Packer terminates the temporary instance used to build the AMI, the EBS volume will stick around, therefore I'll have to manual delete it.

**Comment by rickard-von-essen** [comment]
> once Packer terminates the temporary instance used to build the AMI, the EBS volume will stick around, therefore I'll have to manual delete it.

Correct

**Comment by mwhooker** [comment]
What's going on is that we tell amazon to delete the volume when the source instance is deleted, but then we go ahead and try to delete it anyway. I'm not sure why this was done... possibly to return any errors deleting the volume to the user. I think this is intended since we don't fail on error.

Debatable what the correct solution is without knowing exactly why it was done in the first place. Will ask around

**Comment by mwhooker** [comment]
ok looks like the source issue is #1783

we were trying to clean up the root volume, but I think we inadvertantly try to double clean up extra volumes
