### ISSUE TITLE
Packer ansible role files not getting uploaded when build run

### ISSUE THREAD

**Issue by wilsonbat** [hashicorp/packer#4929]
- Packer version 1.0.0
- Host platform - windows 7 64bit
- Debug log output from `PACKER_LOG=1 .
https://gist.github.com/wilsonbat/9b2ddee243dec1fcd0abcab75bb9ab95

**Comment by rickard-von-essen** [comment]
Please supply the information requested in the issue template:
- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your [gist](https://gist.github.com).

**Comment by wilsonbat** [comment]
example template and scripts - 
https://gist.github.com/wilsonbat/9b2ddee243dec1fcd0abcab75bb9ab95

Note - the job is basically building an aws ami with installs tied to a specific product; the same job when run from mac works but fails from windows machine.

**Comment by wilsonbat** [comment]
@rickard-von-essen 
Just an update on this as my work was completely at halt with this issue. 
I started using the previous version of the packer to see if the issue get addressed.
I tried below,
packer # 0.12.3 - negative
packer # 0.11.0 - positive
i will keep using 0.11.0 for now;

So please see if this additional information helps to fix this in the latest version for the windows 64 bit binary.

Thanks and appreciate the assistance and effort

**Comment by rickard-von-essen** [comment]
Interesting, can you add a log where you run the same template with 0.11.0?

**Comment by wilsonbat** [comment]
@rickard-von-essen - added to https://gist.github.com/wilsonbat/9b2ddee243dec1fcd0abcab75bb9ab95
filename - packerlog.txt

**Comment by rickard-von-essen** [comment]
This looks suspicious 795921988e69f713d2c908514266b58e76c863fe.

**Comment by rickard-von-essen** [comment]
Thanks for reporting this. This is a duplicate of #4689, which have been fixed on master. The fix will be included in the next release.
