### ISSUE TITLE
can not find path 

### ISSUE THREAD

**Issue by gangadhar01a** [hashicorp/packer#4932]
Packer Version: 1.0.0
I have simple windows powershell provision, which actually execute the below script

"cd C:\ProgramData\PuppetLabs\puppet\etc\ssl\
Remove-Item .\certificate_requests
Remove-Item certs
Remove-Item private
Remove-Item .\private_keys
Remove-Item private_keys -Recurse -Force
remove-item public_keys -Recurse -Force"

This actually removes all certificated created by the puppet after installation and I can confirm that the puppet has been installed  through chocolatey prior to this step.
I am keep on getting the following errors during packer build 
"Cannot find path 'C:\ProgramData\PuppetLabs\puppet\etc\ssl\' because it _x000D__x000A_</S><S S="Error">does not Remove-Item : Cannot find path 'C:\Users\packer\certificate_requests' because _x000D__x000A_</S><S S="Error">it does not exist._x000D__x000A_</S><S S="Error">At C:\Windows\Temp\script.ps1:2 char:1_x000D__x000A_</S><S S="Error">."
I have manually installed the puppet through chocolety and executed the above script through powershell which worked as expected (deleted the certificates exist in "C:\ProgramData\PuppetLabs\puppet\etc\ssl\")

**Comment by mwhooker** [comment]
Please make sure you provide the required information for debugging:

- Packer version from `packer version`
- Host platform
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a gist https://gist.github.com
- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your gist https://gist.github.com

**Comment by gangadhar01a** [comment]
Hi,

I have pasted the template and logs for your consideration. I am using packer version 1.0.0 hosted on CentOS 7. I hope this information will be sufficient to troubleshoot.

**Comment by mwhooker** [comment]
Where do you think the issue is, here? It says `cd : Cannot find path 'C:\ProgramData\PuppetLabs\puppet\etc\ssl\' because it does not exist.`

Have you checked that that directory exists?

**Comment by gangadhar01a** [comment]
When we install puppet through Chocolatey the directory will be created by default, I have verified this by manually running the below script through powershell

"Set-ExecutionPolicy Bypass -Force
iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
choco install puppet-agent -y
stop-service puppet 
Remove-item C:\ProgramData\PuppetLabs\puppet\etc\ssl\* -Recurse -Force
start-service puppet 
cd '..\..\Program Files\Puppet Labs\Puppet\bin'
.\puppet.bat --version
.\puppet.bat apply -t"

Through this script I have installed Chocolatey then installed puppet and then deleted the certs exist in "C:\ProgramData\PuppetLabs\puppet\etc\ssl\*".
