### ISSUE TITLE
Ansible (remote) get inventory file

### ISSUE THREAD

**Issue by vinhvu** [hashicorp/packer#4938]
I use packer to provision one ec2 instance, so i can use ansible playbook to install httpd on this ec2?
How can i know the host of ec2 instance?
When i use "hosts: default", the packer will be use 127.0.0.1 to ssh and run playbook.
For more detail as the below:
[1;32m==> amazon-ebs: Provisioning with Ansible...[0m
[0;32m    amazon-ebs:[0m
[0;32m    amazon-ebs: PLAY [default] *****************************************************************[0m
[0;32m    amazon-ebs:[0m
[0;32m    amazon-ebs: TASK [Gathering Facts] *********************************************************[0m
[0;32m    amazon-ebs: fatal: [default]: FAILED! => {"changed": false, "failed": true, "module_stderr": "sudo: sorry, you must have a tty to run sudo\nShared connection to 127.0.0.1 closed.\r\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}[0m
[0;32m    amazon-ebs: 	to retry, use: --limit @/var/lib/jenkins/playbooks/apache-httpd/site.retry[0m
[0;32m    amazon-ebs:[0m
[0;32m    amazon-ebs: PLAY RECAP 

Can you help me?

**Comment by rickard-von-essen** [comment]
Please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._
