### ISSUE TITLE
aws ami using packer build error

### ISSUE THREAD

**Issue by manivenkat18** [hashicorp/packer#4946]
I am getting the following issue when I was trying build aws ami using packer build

Error querying AMI: RequestError: send request failed  caused by: Post https://ec2.us-east-1.amazonaws.com/: dial tcp 54.239.28.176:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time

**Comment by rickard-von-essen** [comment]
Please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._
