### ISSUE TITLE
hyperv builder fails unless virtual switch adapter is shared with the management operating system

### ISSUE THREAD

**Issue by serveradmin99** [hashicorp/packer#4947]
I am getting the following error whilst attempting to build a machine:

2017/05/31 16:58:58 ui error: ==> hyperv-iso: Error getting host adapter ip address: PowerShell error: Get-VMNetworkAdapter : No network adapter is found with the given input.
==> hyperv-iso: At C:\Users\ServerAdmin\AppData\Local\Temp\ps675653695.ps1:4 char:18
==> hyperv-iso: + $HostVMAdapter = Get-VMNetworkAdapter -ManagementOS -SwitchName $switchName
==> hyperv-iso: +                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> hyperv-iso:     + CategoryInfo          : ObjectNotFound: (Jacobs LAN Virtual Switch:Strin 
==> hyperv-iso:    g) [Get-VMNetworkAdapter], VirtualizationOperationFailedException
==> hyperv-iso:     + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Comma 
==> hyperv-iso:    nds.GetVMNetworkAdapterCommand

- Packer version v1.0.0
- Windows Server 2012 R2 Standard
- Debug log output and template needed to reproduce the bug are at https://gist.github.com/serveradmin99/378ba0d32239ce9024fb35f00d8e05c4

Note that this issue does not occur when the virtual switch adapter is shared with the management operating system, however Microsoft best practice says to not share with the management operating system.  There must be another method of getting the host IP address.

**Comment by taliesins** [comment]
There is another issue that duplicates this one. The other one has more content so I am closing this one.
