### ISSUE TITLE
Cannot use packer HTTP server with cloudstack builder

### ISSUE THREAD

**Issue by larstobi** [hashicorp/packer#4949]
The use case is to be able to run Packer and serve a kickstart.cfg from a Packer integrated http server to install CentOS with said kickstart.cfg.

I just switched from using the schubergphilis's CloudStack Packer plugin for Packer 0.7.5 to Packer 1.0.0 with the integrated CloudStack builder, and found that it is missing http server to host files from packer.

```
  "builders": [
    {
      "type":                  "cloudstack",
      "hypervisor":            "xenserver",
      "http_directory":        "http",
      "http_port_min" :        8081,
      "http_port_max" :        8081,
      "user_data": "#!ipxe\nkernel {{user `linux_kernel`}} text ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/kickstart.cfg nomodeset\ninitrd {{user `linux_initrd`}}\nboot"
```

When running it through packer 1.0.0 I get these errors:

* unknown configuration key: "http_directory"
* unknown configuration key: "http_port_max"
* unknown configuration key: "http_port_min"

**Comment by rickard-von-essen** [comment]
The HTTP server is only available for the local (non cloud) builders. It doesn't really make sense for cloud builders.

**Comment by larstobi** [comment]
@rickard-von-essen Hmm, not? Okay. But then I can't access the kickstart.cfg directly from source code but have to rely on a upload-to-web stage. Is that the common way to do it?

**Comment by larstobi** [comment]
I'm not sure I can see how it doesn't make sense to have the HTTP server available for cloud builders. The way we do our cloud build is that we run packer on a VM in a VPC, and then Packer instantiates a VM on the same subnet as where Packer runs. I think it makes some sense, but perhaps there is a better way?

**Comment by rickard-von-essen** [comment]
CloudStack is a bit odd since at supports installing an OS into an empty VM which is normally not possible. So don't have a standard way of providing `kickstart.cfg` to cloud builders. 

For now in you use case I think the simplest work around is to start HTTP with say python before and pass IP and port as user variables. Or uploading it to a objects store (swift) if you have that.

The usually way to build an initial OS image for a cloud provider is usually by using a local build (`qemu`) and import the disk image into the cloud or build in a chroot in a VM (`amazon-chroot`).

**Comment by larstobi** [comment]
CloudStack can be used as a private cloud, which is how we are using it. There is nobody maintaining ready made cloud images of different operating systems like there is in i.e. Amazon, so we have to make our own from scratch.

To install a CentOS 7 from scratch by network install, we need to instruct centos to fetch three files via HTTP:

* vmlinuz
* initrd.img
* kickstart.cfg

(Okay, the kickstart.cfg URL file is really only a kernel parameter, so it is actually the CentOS installer that fetches it, not ipxe.)

The first two files we can fetch from a CentOS mirror, but the third one is a private script.

It would however be preferable to use a script to fetch vmlinuz and initrd.img before running packer, checksum them, and then run serve them to ipxe using the packer http server.

Also, it is customary to keep the kickstart file in the same git repository as the packer template. Beause of that I think it makes a lot of sense to have the http server available for the CloudStack builder.

shubergphilis thinks it makes sense:
https://github.com/schubergphilis/packer-cloudstack/blob/master/step_http_server.go

What to you think? @rickard-von-essen  :-)

**Comment by lfarnell** [comment]
So I'm not super familiar with CloudStack but I have to agree with @larstobi here and say I do believe that CloudStack should have access to the packer http-server. We **shouldn't** make the assumption that CloudStack is a public cloud as you could run this as a private cloud(I assume most people do). I know it's a bit of a weird edge case in terms of local vs cloud builders but in this case i see no harm in the packer http-server being used to host the cfg file. Just my two cents

**Comment by svanharmelen** [comment]
@larstobi lol, I'm working Schuberg Philis :wink: But the code in the repo you are pointing to was not created by Schuberg Philis. If you look at the last commit you'll see that the repo was transferred to us as I was planning to create the currently existing builtin builder, and the project wasn't actively maintained anymore...

That being said I do agree it can make sense to have the HTTP server available within the CloudStack builder. The locations from where you will be able to access the HTTP server will of course be limited to other VM's in the same network, but with that in mind I can see how this could make a few use cases easier.

In terms of time and efforts needed to add this feature, I don't think it's that much work. But personally I cannot make any commitments at the moment. Of course PR's are always welcome!

**Comment by scsinutz** [comment]
For now create a base template from the iso without kickstart, then create a new provisioned template from the base template.

**Comment by rickard-von-essen** [comment]
@larstobi I leave this to @svanharmelen to decide.

**Comment by larstobi** [comment]
@lfarnell thanks for your 2 cents

@svanharmelen thanks for the correction, and thanks for your input. Yes, when using subnets, it is limited to the same subnet, and that is how we do it.

How do you build images yourself, @svanharmelen?

**Comment by rickard-von-essen** [comment]
Have you tried importing a raw image as base. Most *nix distributions provide a raw disk image for use in any IaaS. Example http://cloud.centos.org/centos/7/images/ CentOS-7-x86_64-GenericCloud-1704.raw.tar.gz

**Comment by larstobi** [comment]
@rickard-von-essen Yes, I tried it before opening this ticket, and I couldn't make cloud-init work with user_data. And since I can't log in to the VM after a failed cloud-init boot, because there is no default password, I'm unable to look in the logs to find out what is wrong.

**Comment by rickard-von-essen** [comment]
> couldn't make cloud-init work with user_data

Don't you have some sort of console access?

**Comment by svanharmelen** [comment]
@rickard-von-essen yes, CloudStack offers a console connection... And using cloud-init with user data should work. We use it quite a lot ourselves. But I guess it also depends on the type of network offerings you are using (which services they support) and what type of router VMs you're using...

But I'll look at the PR for adding HTTP server support in a bit (later this morning). Hopefully that will provide a solution.

**Comment by larstobi** [comment]
@rickard-von-essen I couldn't log in to the console as it has no default password and I didn't seem to get the cloud-init (or ignition) working properly with the latest CoreOS and CentOS cloud image. I haven't figured out what went wrong yet.

@svanharmelen Great! 👍
