### ISSUE TITLE
Feature request: ability to copy the AMIs in all AWS regions

### ISSUE THREAD

**Issue by walterdolce** [hashicorp/packer#4954]
The current [`ami_regions`](https://www.packer.io/docs/builders/amazon-ebs.html#ami_regions) configuration option for the Amazon EBS Packer builder is useful as it gives you the ability "to copy the AMI to" the regions specified in the list.

In a disaster recovery scenario (or not) this is great, as it means one would have the AMIs ready in the "fallback region" and so would not need to click around the AWS console and/or wait for the AMI to be copied across.

However, at the moment it's not possible to copy the AMI being built in *all* AWS regions automatically. One would have to manually specify them all.

I think it would be nice to have the ability to copy the AMI being built in all the AWS regions by default. I.e. it would be nice to be able to specify the following to achieve this:
```
    "ami_regions": ["all"]
```

Please note I have specifically avoided introducing an additional parameter as this would, IMO, potentially introduce cognitive overhead and confusion when the additional parameter and the `ami_regions` would live together in the same packer template. So using a special value in the same configuration option makes sense to me in this context.

In my mind, obviously a scenario like the following would see Packer copying the AMIs to all the regions still:
```
    "ami_regions": [
        "eu-west-1",
        "all"
    ]
```

Giving the `all` configuration option value precedence over everything else effectively.

What do you think?

Thank you.

**Comment by rickard-von-essen** [comment]
One problem with this is that `all` is not canonical because of `china` and gov cloud.

**Comment by walterdolce** [comment]
True that. How about treating the `all` value as canonical for the regions which are not "special" (so every region except China and Gov Cloud?

**Comment by kwilczynski** [comment]
I am not sure why not to just use the option with the list of regions? Not that Amazon is adding one every week, this is likely not going to change very often, and definitely something one could manage in their templates.

**Comment by walterdolce** [comment]
> I am not sure why not to just use the option with the list of regions?

This is to avoid that. To have Packer automatically generate the AMI and store it in all the regions without having you to change your template(s).

**Comment by at0S** [comment]
One other thing - how than I can map KMS keys per region? What I'm doing now is specifying map of regions/keys:
...
"region_kms_key_ids": {
    "ap-southeast-2": "96260995-6fbe-4da2-af3a-4f2f6dbabceb",
    "us-west-2": "66155978-0137-498b-99f5-e8f836bb397a"
},
...
 if I'm copying to "all"?

**Comment by mwhooker** [comment]
I think Taras has pointed out exactly why this is so tough. We try to avoid
doing things that will only help a minority of users, at the cost of
consistency. If someone wants to come up with a plan for how to do this
elegantly, I will gladly take a look, but for now I think this is not
something we plan on tackling. For now, the best way to accomplish this is
to manually add every region you want to add. Users controlling their own
templates for things like this will always be better than what we can
accomplish. E.g. We will not be able to make sure "all" accurately reflects
the total list of regions
