### ISSUE TITLE
Document exit codes

### ISSUE THREAD

**Issue by loopsysdev** [hashicorp/packer#4957]
I am seeing the following in my Go.CD build:

```
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: Script exited with non-zero exit status: 22
```

There doesn't seem to be any documentation of `packer.io` exit codes, so I can't even tell whether this exit code is definitely caused by Packer, as opposed to the shell it's running in or even Go.

**Comment by rickard-von-essen** [comment]
That is the exit code of your provisioner script.

To get help with Packer use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool).

See https://www.packer.io/community/

_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._

**Comment by loopsysdev** [comment]
It wasn't meant as a question, but rather as a feature request: Please document the possible exit codes.

**Comment by rickard-von-essen** [comment]
Could you explain why this would help you?

**Comment by loopsysdev** [comment]
Exit codes are a very commonly used source of information to debug errors in command line tools, especially when there is no other information printed to indicate what went wrong with the command or where to find more information. Some exit codes have common meanings (see [source](http://tldp.org/LDP/abs/html/exitcodes.html) and `/usr/include/sysexits.h`), such as 1 (unknown/miscellaneous error), 64 (command syntax issue), and 73 (can't create output file). Knowing what an exit code means in the context of the running application (`packer.io` in this case, since it's the last command in the script and it was clearly run since the last output is from `packer.io`) can mean the difference between one minute of looking up the meaning and realising instantly what the fix must be and an hour or a day setting up debugging, logging and possibly tracing to get to the bottom of what is possibly an issue only ever encountered once.

**Comment by mwhooker** [comment]
```
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: Script exited with non-zero exit status: 22
```

I can't tell from such limited logging, but presumably a script you were running exited with the code 22. You might be able to get more information by setting `PACKER_LOG=1` in the environment.

Packer does not make great use of exit codes. It's either 0 if it worked, or 1 if it didn't. I agree that it would be helpful to have different exit codes as described in sysexits.h, but packer wasn't built to communicate information that way.

**Comment by l0b0** [comment]
Oh, OK. Must be the environment then. I'll try your suggestion.
