### ISSUE TITLE
Amazon Builder couldn't connect via SSH to a Windows box

### ISSUE THREAD

**Issue by phoewass** [hashicorp/packer#4958]
I tried to bake SSH service into my images and use it instead of WinRM, since Microsoft is supporting SSH for Windows[1].

So I created a Windows AMI image with SSH enabled using Packer and everything went fine.
Now when I'm trying to use it as a base image in Packer using ssh communicator it fails.

```
==>amazon-ebs: Prevalidating AMI Name...`
    amazon-ebs: Found Image ID: ami-xxxxxxxx
==> amazon-ebs: Creating temporary keypair: packer_5931600e-8bca-8eab-3416-f5f9b63283e1
==> amazon-ebs: Creating temporary security group for this instance...
==> amazon-ebs: Authorizing access to port 22 the temporary security group...
==> amazon-ebs: Launching a source AWS instance...
    amazon-ebs: Instance ID: i-xxxxxxxxxxxxxxxxx
==> amazon-ebs: Waiting for instance (i-xxxxxxxxxxxxxxxxx) to become ready...
==> amazon-ebs: Adding tags to source instance
    amazon-ebs: Adding tag: "Name": "Packer Builder"
==> amazon-ebs: Waiting for SSH to become available...
==> amazon-ebs: Error waiting for SSH: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Cleaning up any extra volumes...
==> amazon-ebs: No volumes to clean up, skipping
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

==> Builds finished but no artifacts were created.
```

I did some digging and I found out that amazon ssh communicator uses the generated key pair to connect to the box. While Windows boxes need to wait for the generated password then use it to connect, just like what WinRM communicator does.

[1] https://blogs.msdn.microsoft.com/powershell/2015/06/03/looking-forward-microsoft-support-for-secure-shell-ssh/

**Comment by rickard-von-essen** [comment]
Could you link to any documentation describing how this works?

**Comment by phoewass** [comment]
- I created a  Windows 2008r2 AMI using Packer and during provisioning I installed OpenSSH
https://gist.github.com/phoewass/d3afc33c9373159f2e9e6b251bba0968
-> Worked fine and generated an AMI le's say with the id : ami-12345678

- Then I try to use that image (ami-12345678) to create another one the only difference that I'm now using SSH communicator
https://gist.github.com/phoewass/7cbb90b4c8a2b45d1927693a2b0826bb
-> Packer fails to connect as mentioned in the issue.

**Comment by phoewass** [comment]
You are right.
It uses  ssh_key_pair to decrypt the Administrator password and it to login on SSH.
I'm pretty sure, I made some changes to code to check if it works before submitting the issue.

**Comment by rickard-von-essen** [comment]
It would be awesome if you could test the following patch and see if that works for you:

```diff
diff --git a/builder/amazon/common/step_get_password.go b/builder/amazon/common/step_get_password.go
index b457658b..1f3fa46d 100644
--- a/builder/amazon/common/step_get_password.go
+++ b/builder/amazon/common/step_get_password.go
@@ -27,18 +27,6 @@ type StepGetPassword struct {
 func (s *StepGetPassword) Run(state multistep.StateBag) multistep.StepAction {
 	ui := state.Get("ui").(packer.Ui)
 
-	// Skip if we're not using winrm
-	if s.Comm.Type != "winrm" {
-		log.Printf("[INFO] Not using winrm communicator, skipping get password...")
-		return multistep.ActionContinue
-	}
-
-	// If we already have a password, skip it
-	if s.Comm.WinRMPassword != "" {
-		ui.Say("Skipping waiting for password since WinRM password set...")
-		return multistep.ActionContinue
-	}
-
 	// Get the password
 	var password string
 	var err error
@@ -68,6 +56,7 @@ WaitLoop:
 
 			ui.Message(fmt.Sprintf(" \nPassword retrieved!"))
 			s.Comm.WinRMPassword = password
+			s.Comm.SSHPassword = password
 			break WaitLoop
 		case <-timeout:
 			err := fmt.Errorf("Timeout waiting for password.")
```

It will wait for a password regardless of `comm` type. (This is isn't the solution, just verifying that it works as we think it does.)

**Comment by phoewass** [comment]
@rickard-von-essen 
I think I have a working patch, could you help me get it integrated into Packer?

**Comment by rickard-von-essen** [comment]
Please open a PR.

**Comment by grv87** [comment]
I believe better way is to authorize AWS SSH key in init script:

```
Invoke-RestMethod -uri  http://169.254.169.254/latest/meta-data/public-keys/0/openssh-key -OutFile "$Env:USERPROFILE\.ssh\authorized_keys"
```

And then connect with SSH key as usual.
