### ISSUE TITLE
vagrant-cloud lacks the ability to specify a provider causing version collisions

### ISSUE THREAD

**Issue by ladar** [hashicorp/packer#4973]
I updated my packer configs so they would use the vagrant-cloud post processor instead of the atlas post-processor, and have run into a few problems. 

1) The biggest issue seems to be alternate versions of a box, intended for different providers get rejected because the version numbers collide. After glancing at the code, it appears the plugin is using the input id to determine the provider, which doesn't work well with complicated json files. II can't set the output for the every artifact to virtualbox.box... that would create quite the mess. Can we add the ability to override the provider string, in the same way we could with atlas plugin? If we're going with 'box_tag' then perhaps 'box_provider' would make the most sense for a json label. 

2) Packer doesn't seem to use the ATLAS_TOKEN with the vagrant cloud plugin. Is there an equivalent environment variable? I'm reading in the environment variable manually at the moment, and then setting the token attribute, but it's clunky.

**Comment by mwhooker** [comment]
hi @ladar 

thanks for the note. We're working on making the versioning a little easier.

Would you please look at the documentation update in #4975 and tell me if that helps you at all?

**Comment by ladar** [comment]
What you described in the docs is what I've implemented. What I was looking for was a) how to have multiple providers with the same version (like with https://atlas.hashicorp.com/generic/boxes/arch). If I add a timestamp to the version, I'll deconflict the images but I'll also end up creating a mess, as I won't know which box corresponds to which packer run. If I deconflict based on the provider, then I know all of the with version (for example) v0.9.0 boxes used the provisioning scripts, are based off commit XXXX. It tells me they're equivalent, sans the provider specific bits Semantic versioning and all that jazz. 

As for b) I effectively implemented what the docs suggest - and it isn't nearly as important as a. I was just wondering if there was a way to keep the authentication means and method separate from the config files. Just in case I decide to my config repos public, I want to mix auth references in with my poop. I mean push. With a standardized environment token it's easy to keep completely separate. It was also nice having vagrant and packer use the same token for private boxes.

**Comment by stephenreay** [comment]
@ladar I'm seeing what I think is the same issue, but I wanted to confirm so I know if I need to open a new one: do your boxes upload successfully, but fail on the release step (which then causes a removal) or doe they fail before uploading?

**Comment by ladar** [comment]
@stephenreay I usually don't wait around for the builds to complete, so I wasn't sure, and I didn't have the logs from my vagrant-cloud attempts to consult. So I ran a test, just for you. It appears that your right. The first box (magma-debian8-virtualbox) uploads just fine. Then, when the vmware version finishes building, the it gets uploaded using the vmware_desktop provider, but when it goes to release, the box is rejected with an error that says "Error releasing version," I mistook that to mean the version numbers collided, and the box was rejected, as I've run into that issue a few times in the past. I also checked the [website](https://atlas.hashicorp.com/lavabit/boxes/magma-debian/versions/0.9.6) to confirm the box didn't appear... I also checked that the box wasn't uploaded, but marked unreleased. What follows are snippets from the console output. 

The first (and only successful box) run which created the virtualbox version linked to above:

```==> magma-debian8-virtualbox: Running post-processor: vagrant
==> magma-debian8-virtualbox (vagrant): Creating Vagrant box for 'virtualbox' provider
    magma-debian8-virtualbox (vagrant): Copying from artifact: output/magma-debian8-virtualbox/magma-debian8-virtualbox-disk001.vmdk
    magma-debian8-virtualbox (vagrant): Copying from artifact: output/magma-debian8-virtualbox/magma-debian8-virtualbox.ovf
    magma-debian8-virtualbox (vagrant): Renaming the OVF to box.ovf...
    magma-debian8-virtualbox (vagrant): Using custom Vagrantfile: tpl/magma.rb
    magma-debian8-virtualbox (vagrant): Compressing: Vagrantfile
    magma-debian8-virtualbox (vagrant): Compressing: box.ovf
    magma-debian8-virtualbox (vagrant): Compressing: magma-debian8-virtualbox-disk001.vmdk
    magma-debian8-virtualbox (vagrant): Compressing: metadata.json
==> magma-debian8-virtualbox: Running post-processor: vagrant-cloud
==> magma-debian8-virtualbox (vagrant-cloud): Verifying box is accessible: lavabit/magma-debian
    magma-debian8-virtualbox (vagrant-cloud): Box accessible and matches tag
==> magma-debian8-virtualbox (vagrant-cloud): Creating version: 0.9.6
==> magma-debian8-virtualbox (vagrant-cloud): Creating provider: virtualbox
==> magma-debian8-virtualbox (vagrant-cloud): Preparing upload of box: output/magma-debian8-virtualbox-0.9.6.box
    magma-debian8-virtualbox (vagrant-cloud): Box upload prepared with token
==> magma-debian8-virtualbox (vagrant-cloud): Uploading box: output/magma-debian8-virtualbox-0.9.6.box
    magma-debian8-virtualbox (vagrant-cloud): Depending on your internet connection and the size of the box,
    magma-debian8-virtualbox (vagrant-cloud): this may take some time
    magma-debian8-virtualbox (vagrant-cloud): Uploading box, attempt 2
    magma-debian8-virtualbox (vagrant-cloud): Uploading box, attempt 3
    magma-debian8-virtualbox (vagrant-cloud): Box successfully uploaded
==> magma-debian8-virtualbox (vagrant-cloud): Verifying provider upload: virtualbox
    magma-debian8-virtualbox (vagrant-cloud): Waiting for upload token match
    magma-debian8-virtualbox (vagrant-cloud): Upload successfully verified with token
==> magma-debian8-virtualbox (vagrant-cloud): Releasing version: 0.9.6
    magma-debian8-virtualbox (vagrant-cloud): Version successfully released and available
==> magma-debian8-virtualbox: Running post-processor: artifice
==> magma-debian8-virtualbox (artifice): Using these artifact files: output/magma-debian8-virtualbox-0.9.6.box
==> magma-debian8-virtualbox: Running post-processor: checksum
Build 'magma-debian8-virtualbox' finished.

==> Builds finished. The artifacts of successful builds are:
--> magma-debian8-virtualbox: 'virtualbox' provider box: output/magma-debian8-virtualbox-0.9.6.box
--> magma-debian8-virtualbox: 'virtualbox': lavabit/magma-debian
--> magma-debian8-virtualbox: Created artifact from files: output/magma-debian8-virtualbox-0.9.6.box
--> magma-debian8-virtualbox: Created artifact from files: output/magma-debian8-virtualbox-0.9.6.box, output/magma-debian8-virtualbox-0.9.6.box.sha256
```

The vmware_desktop version of the same box:

```==> magma-debian8-vmware: Running post-processor: vagrant
==> magma-debian8-vmware (vagrant): Creating Vagrant box for 'vmware' provider
    magma-debian8-vmware (vagrant): Copying: output/magma-debian8-vmware/magma-debian8-vmware.nvram
    magma-debian8-vmware (vagrant): Copying: output/magma-debian8-vmware/magma-debian8-vmware.vmdk
    magma-debian8-vmware (vagrant): Copying: output/magma-debian8-vmware/magma-debian8-vmware.vmsd
    magma-debian8-vmware (vagrant): Copying: output/magma-debian8-vmware/magma-debian8-vmware.vmx
    magma-debian8-vmware (vagrant): Copying: output/magma-debian8-vmware/magma-debian8-vmware.vmxf
    magma-debian8-vmware (vagrant): Using custom Vagrantfile: tpl/magma.rb
    magma-debian8-vmware (vagrant): Compressing: Vagrantfile
    magma-debian8-vmware (vagrant): Compressing: magma-debian8-vmware.nvram
    magma-debian8-vmware (vagrant): Compressing: magma-debian8-vmware.vmdk
    magma-debian8-vmware (vagrant): Compressing: magma-debian8-vmware.vmsd
    magma-debian8-vmware (vagrant): Compressing: magma-debian8-vmware.vmx
    magma-debian8-vmware (vagrant): Compressing: magma-debian8-vmware.vmxf
    magma-debian8-vmware (vagrant): Compressing: metadata.json
==> magma-debian8-vmware: Running post-processor: vagrant-cloud
==> magma-debian8-vmware (vagrant-cloud): Verifying box is accessible: lavabit/magma-debian
    magma-debian8-vmware (vagrant-cloud): Box accessible and matches tag
==> magma-debian8-vmware (vagrant-cloud): Creating version: 0.9.6
    magma-debian8-vmware (vagrant-cloud): Version exists, skipping creation
==> magma-debian8-vmware (vagrant-cloud): Creating provider: vmware_desktop
==> magma-debian8-vmware (vagrant-cloud): Preparing upload of box: output/magma-debian8-vmware-0.9.6.box
    magma-debian8-vmware (vagrant-cloud): Box upload prepared with token
==> magma-debian8-vmware (vagrant-cloud): Uploading box: output/magma-debian8-vmware-0.9.6.box
    magma-debian8-vmware (vagrant-cloud): Depending on your internet connection and the size of the box,
    magma-debian8-vmware (vagrant-cloud): this may take some time
    magma-debian8-vmware (vagrant-cloud): Uploading box, attempt 2
    magma-debian8-vmware (vagrant-cloud): Uploading box, attempt 3
    magma-debian8-vmware (vagrant-cloud): Box successfully uploaded
==> magma-debian8-vmware (vagrant-cloud): Verifying provider upload: vmware_desktop
    magma-debian8-vmware (vagrant-cloud): Waiting for upload token match
    magma-debian8-vmware (vagrant-cloud): Upload successfully verified with token
==> magma-debian8-vmware (vagrant-cloud): Releasing version: 0.9.6
==> magma-debian8-vmware (vagrant-cloud): Cleaning up provider
    magma-debian8-vmware (vagrant-cloud): Deleting provider: vmware_desktop
Build 'magma-debian8-vmware' errored: 1 error(s) occurred:

* Post-processor failed: Error releasing version:

==> Some builds didn't complete successfully and had errors:
--> magma-debian8-vmware: 1 error(s) occurred:

* Post-processor failed: Error releasing version:
```
And finally, the libvirt version of the box:

```==> magma-debian8-libvirt: Running post-processor: vagrant
==> magma-debian8-libvirt (vagrant): Creating Vagrant box for 'libvirt' provider
    magma-debian8-libvirt (vagrant): Copying from artifact: output/magma-debian8-libvirt/magma-debian8-libvirt
    magma-debian8-libvirt (vagrant): Using custom Vagrantfile: tpl/magma.rb
    magma-debian8-libvirt (vagrant): Compressing: Vagrantfile
    magma-debian8-libvirt (vagrant): Compressing: box.img
    magma-debian8-libvirt (vagrant): Compressing: metadata.json
==> magma-debian8-libvirt: Running post-processor: vagrant-cloud
==> magma-debian8-libvirt (vagrant-cloud): Verifying box is accessible: lavabit/magma-debian
    magma-debian8-libvirt (vagrant-cloud): Box accessible and matches tag
==> magma-debian8-libvirt (vagrant-cloud): Creating version: 0.9.6
    magma-debian8-libvirt (vagrant-cloud): Version exists, skipping creation
==> magma-debian8-libvirt (vagrant-cloud): Creating provider: libvirt
==> magma-debian8-libvirt (vagrant-cloud): Preparing upload of box: output/magma-debian8-libvirt-0.9.6.box
    magma-debian8-libvirt (vagrant-cloud): Box upload prepared with token
==> magma-debian8-libvirt (vagrant-cloud): Uploading box: output/magma-debian8-libvirt-0.9.6.box
    magma-debian8-libvirt (vagrant-cloud): Depending on your internet connection and the size of the box,
    magma-debian8-libvirt (vagrant-cloud): this may take some time
    magma-debian8-libvirt (vagrant-cloud): Uploading box, attempt 2
    magma-debian8-libvirt (vagrant-cloud): Uploading box, attempt 3
    magma-debian8-libvirt (vagrant-cloud): Box successfully uploaded
==> magma-debian8-libvirt (vagrant-cloud): Verifying provider upload: libvirt
    magma-debian8-libvirt (vagrant-cloud): Waiting for upload token match
    magma-debian8-libvirt (vagrant-cloud): Upload successfully verified with token
==> magma-debian8-libvirt (vagrant-cloud): Releasing version: 0.9.6
==> magma-debian8-libvirt (vagrant-cloud): Cleaning up provider
    magma-debian8-libvirt (vagrant-cloud): Deleting provider: libvirt
Build 'magma-debian8-libvirt' errored: 1 error(s) occurred:

* Post-processor failed: Error releasing version:

==> Some builds didn't complete successfully and had errors:
--> magma-debian8-libvirt: 1 error(s) occurred:

* Post-processor failed: Error releasing version: 
```

**Comment by ladar** [comment]
On a separate, but related note, I miss having the box file size show up in the vagrant cloud post processor output. I've caught problems in the past based on the upload size - because I noticed the box size was significantly different then previous builds. If your feeling particularly ambitious - logging the size in human readable form ( KiB / MiB / GiB ) instead of bytes, combined with an occasional progress report, wouldn't hurt.

**Comment by stephenreay** [comment]
Thanks for confirming, and for the test @ladar! That seems like the same thing, with PACKER_LOG=1 I see a http 422 error, so presumably it's the conflict because it doesn't know the provider name. I will try to adjust the output paths to test if  virtualbox.box etc file name helps.

I'll test some more this evening and post back, including the packer log output.

This whole issue is making me think that it would be good if packer could resume from a previous artifict. Maybe that's already possible "manually" using different options.

**Comment by ladar** [comment]
I intended to upload the packer_log output, but realized my script was
clobbering the output file whenever I built a single box. (It called the
json files in sequence, so when it tried building a json file that
didn't hold the box, it would truncate the log - instead of appending).
I'll build a different box so I can also submit debug logs. I'm also
going to try setting the no_release flag on the second and third upload.
That might be an, albeit annoying, workaround.

I've looked at the docs extensively, in search of a way to run packer
build with the upload plugin 'disabled' or 'skipped', so it doesn't
upload the boxes at the end, but haven't found a way to make it work. 

I've been playing with a script file that might let me upload the boxes
manually using bash fu and curl. but haven't tried using it yet. Either
way, it's built around the Atlas URLs and API calls, which I presume are
different for the vagrant cloud uploads - so we can't use it for this
problem.

**Comment by stephenreay** [comment]
I've already tried with `no_release` set to true, and it didn't work either.

To disable uploads, you can just remove the vagrant-cloud post processor (assuming you have a vagrant post processor immediately before it?) and you'll just get local .box files

**Comment by ladar** [comment]
>  To disable uploads, you can just remove the vagrant-cloud post processor (assuming you have a vagrant post processor immediately before it?) and you'll just get local .box files

I know. The problem is what happens when I subsequently _do_ want the boxes to upload. ,Adding and then removing large chunks of the JSON config file with any frequency isn't very practical. Since JSON comments don't work I looked for an alternative method. I've checked the docs, the cli options, and even looked into whether the .packerconfig could be used to disable plugins all to no avail. 

I was looking for a command line option, like -except=machine-name but have it operate on a plugin basis. Like -skip=vagrant-cloud. Of course something simple like -disable-upload would also work. 

The best option might be to simply add an enabled boolean to base template for everything. That way somebody could enable/disable provisioner, builders, post-processors etc without removing them. But I think we've gone off topic...

**Comment by stephenreay** [comment]
I see, yes it would be nice if it was configurable by switch/arg.

I noticed in the log output it *does* mention the correct provider name, so maybe it's some other bug on the server side?

Is there a place to report/check issues related the vagrant-cloud "service" @mitchellh?

**Comment by ladar** [comment]
I did another build using the vagrant-cloud plugin, so I could collect the debug logs and it worked. All 3 boxes appear to have uploaded properly. The difference: it was a private box. I guess that means the "release" step was never run, and thus no error. I confirmed the boxes were uploaded by pulling them back down using vagrant. I'm running the test again using a public box now.

**Comment by ladar** [comment]
I've noticed that with the vagrant-cloud plugin it appears to upload the box multiple times before completing. So while I was waiting for the first first box to finish attempt number 3, I checked the Atlas website and saw the box had in fact completed. I was able to pull it back down via vagrant (but only after setting up the auth token, as it wasn't public yet). While waiting for the second box to upload I took a screenshot....

I don't know if it's my inner Ayn Rand talking - but I'm really starting to miss Atlas already. 

![screenshot from 2017-06-09 12-05-55](https://user-images.githubusercontent.com/1434008/26986370-cce636b0-4d0c-11e7-837d-68279bad06ca.png)

**Comment by ladar** [comment]
It appears that after setting "no_release" up as true for the vmware and libvirt providers, the boxes were uploaded without issue. And as a bonus they were in fact released... I'll run the test one more time with no_release removed, just to confirm, but I think it's pretty clear where the bug is hiding. 

https://atlas.hashicorp.com/generic/boxes/alpine36/versions/0.9.6

**Comment by stephenreay** [comment]
Weird, I tried that and it failed still. I will retest tomorrow. Does it still upload multiple times for you?

**Comment by ladar** [comment]
My guess is that reason it worked is because even though I didn't have no_release set on the first upload, the box was already private. Have you tried setting all of the uploads to no_release == true? 

I just did my confirmation test, and it failed as expected. And yes, it also appears to have uploaded the box 3 times. I can sanitize my debug logs and upload them later if you want? I'd just like to remove passwords, and tokens before posting them - and I'm already running late. 

Here's the console log:

```
==> generic-alpine35-libvirt: Converting hard drive...
==> generic-alpine35-libvirt: Running post-processor: vagrant
==> generic-alpine35-libvirt (vagrant): Creating Vagrant box for 'libvirt' provider
    generic-alpine35-libvirt (vagrant): Copying from artifact: output/generic-alpine35-libvirt/generic-alpine35-libvirt
    generic-alpine35-libvirt (vagrant): Using custom Vagrantfile: tpl/generic.rb
    generic-alpine35-libvirt (vagrant): Compressing: Vagrantfile
    generic-alpine35-libvirt (vagrant): Compressing: box.img
    generic-alpine35-libvirt (vagrant): Compressing: metadata.json
==> generic-alpine35-libvirt: Running post-processor: vagrant-cloud
==> generic-alpine35-libvirt (vagrant-cloud): Verifying box is accessible: generic/alpine35
    generic-alpine35-libvirt (vagrant-cloud): Box accessible and matches tag
==> generic-alpine35-libvirt (vagrant-cloud): Creating version: 0.9.6
    generic-alpine35-libvirt (vagrant-cloud): Version exists, skipping creation
==> generic-alpine35-libvirt (vagrant-cloud): Creating provider: libvirt
==> generic-alpine35-libvirt (vagrant-cloud): Preparing upload of box: output/generic-alpine35-libvirt-0.9.6.box
    generic-alpine35-libvirt (vagrant-cloud): Box upload prepared with token
==> generic-alpine35-libvirt (vagrant-cloud): Uploading box: output/generic-alpine35-libvirt-0.9.6.box
    generic-alpine35-libvirt (vagrant-cloud): Depending on your internet connection and the size of the box,
    generic-alpine35-libvirt (vagrant-cloud): this may take some time
    generic-alpine35-libvirt (vagrant-cloud): Uploading box, attempt 2
    generic-alpine35-libvirt (vagrant-cloud): Uploading box, attempt 3
    generic-alpine35-libvirt (vagrant-cloud): Box succesfully uploaded
==> generic-alpine35-libvirt (vagrant-cloud): Verifying provider upload: libvirt
    generic-alpine35-libvirt (vagrant-cloud): Waiting for upload token match
    generic-alpine35-libvirt (vagrant-cloud): Upload succesfully verified with token
==> generic-alpine35-libvirt (vagrant-cloud): Releasing version: 0.9.6
==> generic-alpine35-libvirt (vagrant-cloud): Cleaning up provider
    generic-alpine35-libvirt (vagrant-cloud): Deleting provider: libvirt
Build 'generic-alpine35-libvirt' errored: 1 error(s) occurred:

* Post-processor failed: Error releasing version: 

==> Some builds didn't complete successfully and had errors:
--> generic-alpine35-libvirt: 1 error(s) occurred:

* Post-processor failed: Error releasing version: 
```

And the first upload (which worked):

```
==> generic-alpine35-virtualbox: Gracefully halting virtual machine...
==> generic-alpine35-virtualbox: Preparing to export machine...
    generic-alpine35-virtualbox: Deleting forwarded port mapping for the communicator (SSH, WinRM, etc) (host port 2673)
==> generic-alpine35-virtualbox: Exporting virtual machine...
    generic-alpine35-virtualbox: Executing: export generic-alpine35-virtualbox --output output/generic-alpine35-virtualbox/generic-alpine35-virtualbox.ovf
==> generic-alpine35-virtualbox: Unregistering and deleting virtual machine...
==> generic-alpine35-virtualbox: Running post-processor: vagrant
==> generic-alpine35-virtualbox (vagrant): Creating Vagrant box for 'virtualbox' provider
    generic-alpine35-virtualbox (vagrant): Copying from artifact: output/generic-alpine35-virtualbox/generic-alpine35-virtualbox-disk001.vmdk
    generic-alpine35-virtualbox (vagrant): Copying from artifact: output/generic-alpine35-virtualbox/generic-alpine35-virtualbox.ovf
    generic-alpine35-virtualbox (vagrant): Renaming the OVF to box.ovf...
    generic-alpine35-virtualbox (vagrant): Using custom Vagrantfile: tpl/generic.rb
    generic-alpine35-virtualbox (vagrant): Compressing: Vagrantfile
    generic-alpine35-virtualbox (vagrant): Compressing: box.ovf
    generic-alpine35-virtualbox (vagrant): Compressing: generic-alpine35-virtualbox-disk001.vmdk
    generic-alpine35-virtualbox (vagrant): Compressing: metadata.json
==> generic-alpine35-virtualbox: Running post-processor: vagrant-cloud
==> generic-alpine35-virtualbox (vagrant-cloud): Verifying box is accessible: generic/alpine35
    generic-alpine35-virtualbox (vagrant-cloud): Box accessible and matches tag
==> generic-alpine35-virtualbox (vagrant-cloud): Creating version: 0.9.6
==> generic-alpine35-virtualbox (vagrant-cloud): Creating provider: virtualbox
==> generic-alpine35-virtualbox (vagrant-cloud): Preparing upload of box: output/generic-alpine35-virtualbox-0.9.6.box
    generic-alpine35-virtualbox (vagrant-cloud): Box upload prepared with token
==> generic-alpine35-virtualbox (vagrant-cloud): Uploading box: output/generic-alpine35-virtualbox-0.9.6.box
    generic-alpine35-virtualbox (vagrant-cloud): Depending on your internet connection and the size of the box,
    generic-alpine35-virtualbox (vagrant-cloud): this may take some time
    generic-alpine35-virtualbox (vagrant-cloud): Uploading box, attempt 2
    generic-alpine35-virtualbox (vagrant-cloud): Uploading box, attempt 3
    generic-alpine35-virtualbox (vagrant-cloud): Box succesfully uploaded
==> generic-alpine35-virtualbox (vagrant-cloud): Verifying provider upload: virtualbox
    generic-alpine35-virtualbox (vagrant-cloud): Waiting for upload token match
    generic-alpine35-virtualbox (vagrant-cloud): Upload succesfully verified with token
==> generic-alpine35-virtualbox (vagrant-cloud): Releasing version: 0.9.6
    generic-alpine35-virtualbox (vagrant-cloud): Version successfully released and available
==> generic-alpine35-virtualbox: Running post-processor: artifice
==> generic-alpine35-virtualbox (artifice): Using these artifact files: output/generic-alpine35-virtualbox-0.9.6.box
==> generic-alpine35-virtualbox: Running post-processor: checksum
Build 'generic-alpine35-virtualbox' finished.

==> Builds finished. The artifacts of successful builds are:
--> generic-alpine35-virtualbox: 'virtualbox' provider box: output/generic-alpine35-virtualbox-0.9.6.box
--> generic-alpine35-virtualbox: 'virtualbox': generic/alpine35
--> generic-alpine35-virtualbox: Created artifact from files: output/generic-alpine35-virtualbox-0.9.6.box
--> generic-alpine35-virtualbox: Created artifact from files: output/generic-alpine35-virtualbox-0.9.6.box, output/generic-alpine35-virtualbox-0.9.6.box.sha256

```

**Comment by justincampbell** [comment]
Just wanted to let everyone in this thread know that we're working on this, and hope to have it resolved next week. Sorry for the troubles.

**Comment by stephenreay** [comment]
Does that include fixing the 3x uploads? Also, thanks for letting us know!

**Comment by justincampbell** [comment]
@stephenreay I'm focusing on the discrepancies server-side in handling the atlas vs vagrantcloud post-processors. I suspect the 3x uploads may be a client-side issue, but I'll look into that afterwards. Thanks for clarifying!

**Comment by mwhooker** [comment]
The issue with multiple uploads should be fixed in #5008 if anyone cares to try out that branch

**Comment by justincampbell** [comment]
@ladar @stephenreay We've fixed an issue preventing multiple builders from being released with the same version. Please try again and let me know if this issue is resolved. Thanks!

**Comment by justincampbell** [comment]
I've also updated the [migration docs](https://www.vagrantup.com/docs/vagrant-cloud/vagrant-cloud-migration.html#packer-and-terraform-enterprise) and [vagrantcloud post-processor docs](https://www.packer.io/docs/post-processors/vagrant-cloud.html#use-with-vagrant-post-processor) to recommend computing the version with a timestamp in the variables instead of the post-processor.

**Comment by ladar** [comment]
Is there a website where I can grab a nightly snapshot? Or do I have to grab the code and setup a build environment?

**Comment by mwhooker** [comment]
@ladar we don't have snapshots available right now. If you tell me your os/arch, I can build you something though. Otherwise downloading yourself and building is the best bet

**Comment by mwhooker** [comment]
Packer 1.0.1 is released which should have a fix for this. If you're still seeing an issue, will you please let us know so we can reopen?

Thanks!

**Comment by ladar** [comment]
I finally had a chance to update my configs (again) to use vagrant-cloud, and am pleased to report everything went smoothly. I was able to upload a QEMU (aka libvirt), Hyper-V, VMWare, and Virtualbox image using the same version number, and thus tested the Linux (x64) and Windows (x64) versions of 1.0.1. 

P.S. Everything also appeared to upload in a single pass.

**Comment by justincampbell** [comment]
@ladar Thanks for the update!
