### ISSUE TITLE
Using variable in external script not being evaluated

### ISSUE THREAD

**Issue by nodesocket** [hashicorp/packer#4985]
I have the following:

```
"provisioners": [{
    "type": "shell",
    "script": "scripts/base-ubuntu-1604-lts.bash"
}]
```

Then in file `scripts/base-ubuntu-1604-lts.bash`:

```
#!/usr/bin/env bash

echo '### {{isotime}} - START OF PACKER SHELL PROVISIONER ###'
sleep 10
echo '### {{isotime}} - END OF PACKER SHELL PROVISIONER ###'
```

But in the packer output I am seeing `{{isotime}}` being printed statically, not evaluated.

**Comment by mwhooker** [comment]
Hi,

we don't render shell scripts as templates. I recommend something like

```json
{
 "provisioners": [
        {
            "script": "4985.sh",
            "environment_vars": [
                "isotime={{ isotime }}"
            ],
            "type": "shell"
        }
    ]
}
```

and then using `$isotime` instead of `{{ isotime }}` in your script

**Comment by nodesocket** [comment]
@mwhooker thanks for the quick reply. Won't this output the same date/time at the start and end, since that value is generated before running the script?

**Comment by mwhooker** [comment]
yes, but that's how isotime works. If you want to see how long your script
runs for, use the `date` command.

~/dev/packertest ᐅ date -u +"%Y-%m-%dT%H:%M:%SZ"
2017-06-08T00:54:50Z
~/dev/packertest ᐅ date
Wed Jun  7 17:55:14 PDT 2017

**Comment by nodesocket** [comment]
Thanks, ended up going with:

```bash
printf "### %s - START OF PACKER SHELL PROVISIONER ###\n" "$(date +'%m/%d/%Y %I:%M:%S %p')"
```
