### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by sm-azure** [hashicorp/packer#4986]
Packer documentation - https://www.packer.io/intro/getting-started/provision.html has the update command as `"sudo apt-get update"` , shouldn't this be `"sudo apt-get update -y",`? Using the provisioner as documented today results in "non zero exit code". 

Packer version used 1.0.0 (linux 64 bit).
Builder - AWS, ebs. 
AMI - Redhat

**Comment by mwhooker** [comment]
Hi,

thanks for your reports. Under normal conditions, `apt-get update` will not prompt, so there is no need to use the `-y` flag. If it does prompt, I suspect something has gone wrong.
