### ISSUE TITLE
Chef-Solo Provisioner fails (Windows 2016)

### ISSUE THREAD

**Issue by steveparker-kcom** [hashicorp/packer#4989]
I am building an AWS AMI for Windows 2016 with the amazon-ebs builder. The config file lists a single chef-solo provisioner which has a run list of a newly generated cookbook.  This was working a few days ago. Run log is below. Could be due to the chef version since it pulls the install script from an external source?

- Packer version from `packer version`
Packer v1.0.0

- Host platform
Ubuntu

- Debug log output from `PACKER_LOG=1 packer build template.json`.
https://gist.github.com/steveparker-kcom/1eb9f178c40a191782a20cf992f47829

**Comment by mwhooker** [comment]
> Could be due to the chef version since it pulls the install script from an external source?

yes certainly. I would try to specify a known good version and see if that fixes it


the relevant bits:

```
2017/06/08 13:18:46 packer: 2017/06/08 13:18:46 [INFO] command 'c:/opscode/chef/bin/chef-solo.bat --no-color -c C:/Windows/Temp/packer-chef-solo/solo.rb -j C:/Windows/Temp/packer
-chef-solo/node.json' exited with code: 1
    amazon-ebs: <internal:gem_prelude>:4:in `require': cannot load such file -- rubygems.rb (LoadError)
2017/06/08 13:18:46 packer: 2017/06/08 13:18:46 [INFO] RPC endpoint: Communicator ended with: 1
```

**Comment by steveparker-kcom** [comment]
Hmm, not having much luck. I set the install command as below.

`"install_command": "powershell.exe -Command \". { iwr -useb https://omnitruck.chef.io/install.ps1 } | iex; install -version 12\""`

But the chef provisioner is still failing with: 

`amazon-ebs: <internal:gem_prelude>:4:in `require': cannot load such file -- rubygems.rb (LoadError)`

**Comment by mwhooker** [comment]
that generally means you don't have ruby installed correctly (I think usually that you have two versions). I would try to make sure your environment is set up correctly. If you want help, you could ask in https://groups.google.com/forum/#!forum/packer-tool or on stackoverflow, but a github issue is not the best place to work through these types of issues.
