### ISSUE TITLE
packer push should push variables

### ISSUE THREAD

**Issue by mwhooker** [hashicorp/packer#4992]
packer push, when no `-var` flags are provided, does not push any variables from the template. If a single -var is added, however, all of the template variables get pushed.

Let's make sure we push all template variables regardless of how many -var flags there are.

**Comment by SwampDragons** [comment]
I've traced the exact point the codepaths diverge and it's here: https://github.com/hashicorp/packer/blob/7f0a404307135b903f0d93c79368ee3f96929ffe/packer/core.go#L295

If I have command line variables, then the template variables get interpolated and added to the c.variables map.  If I _don't_ have command line variables, then the template variables get interpolated _but don't get added_ to the map, which is empty.  I'm still not fantastic with my golang gotchas but isn't there some thing where if you declare an empty map the wrong way you can't add stuff to it later?

**Comment by SwampDragons** [comment]
Got it. https://github.com/hashicorp/packer/pull/5101
