### ISSUE TITLE
Request: Add human readable dates to outputted log lines

### ISSUE THREAD

**Issue by nodesocket** [hashicorp/packer#5000]
Request to add human readable dates _(ISO-8601_) to outputted log lines. Something like:

    ==> [2017-06-10T08:58:50+00:00] googlecompute: Checking image does not exist...
    ==> [2017-06-10T08:58:50+00:00] googlecompute: Creating temporary SSH key for instance...
    ==> [2017-06-10T08:58:50+00:00] googlecompute: Using image: base-1493024240
    ==> [2017-06-10T08:58:50+00:00] googlecompute: Creating instance...

This could be a new configuration option that defaults to `false`.

**Comment by rickard-von-essen** [comment]
You can just pipe to `ts` (from `moreutils`).

```shell
$ packer build template.json | ts
```

**Comment by mwhooker** [comment]
as rickard said, this can be done with other tools. I think this would be a fine addition to packer if someone wants to submit a pr (activated by a flag). However, this is not something that we're planning on implementing, so going to close this.
