### ISSUE TITLE
Not able to find the azure created VHD in azure portal or azure cli

### ISSUE THREAD

**Issue by puneetloya** [hashicorp/packer#5003]
I am using the packer azure-arm provider for creating azure vhds. As mentioned in https://www.packer.io/docs/builders/azure.html the deprovisioning is also getting executed successfully.
The build is successful, but the OsdiskUri and templateUri return 'resource not found'.

Further I try to find it on the azure portal(Storage Account --> VHD) and the azure cli, I could not find the VHD.

Packer Version: 'https://www.packer.io/docs/builders/azure.html'
Host platform: Linux
The packer log can be found here: https://gist.github.com/puneetloya/855737efd9ad338c4cd2db4be77dca98

Command Used:
PACKER_LOG=1 PACKER_LOG_PATH=packer.log packer build -only=azure-arm packer.json

It would of great help if someone could take a look on this, thanks!!

**Comment by puneetloya** [comment]
closing this. It was putting the image in a systems folder, am mentioning an existing container, it does not put it there like why?

**Comment by boumenot** [comment]
Please see the docs concerning [capture_container_name](https://www.packer.io/docs/builders/azure.html#capture_container_name) and [capture_name_prefix](https://www.packer.io/docs/builders/azure.html#capture_name_prefix).  Unfortunately, the Azure API does not allow any other placement.
