### ISSUE TITLE
Amazon EBS with launch_block_device_mappings and virtual_name fails

### ISSUE THREAD

**Issue by florianparain** [hashicorp/packer#5020]
Packer fails to build my AWS AMI.
`Packer v1.0.0`

Type: amazon-ebs with `launch_block_device_mappings.virtual_name`
Il I remove the `launch_block_device_mappings.virtual_name` option it works.

Please see the gist for the logs and json file.
https://gist.github.com/florianparain/e938b49b71b42e0a9409d86a1ee15a18

    ==> amazon-ebs: Error launching source instance: MissingParameter: The request must contain the parameter ebs
    ==> amazon-ebs: 	status code: 400, request id: 63255685-2239-46ae-bd80-7d7f7c414e03

**Comment by florianparain** [comment]
Il I remove the `launch_block_device_mappings.virtual_name` option it works.

**Comment by rickard-von-essen** [comment]
Correct me if I'm wrong but I think this can only bee named `ephemeralN`.

> The virtual device name (ephemeralN)

See [Block Device Mapping](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_BlockDeviceMapping.html)

**Comment by mwhooker** [comment]
I think @rickard-von-essen is right. Can you test a new json with a correct virtual name? If that was the problem, let's add a validation check on the virtual device name

**Comment by rickard-von-essen** [comment]
Closing this since there has been now response.
