### ISSUE TITLE
Azure-arm: Add public key authentication to OS profile

### ISSUE THREAD

**Issue by puneetloya** [hashicorp/packer#5025]
The template json created for the azure VHD using packer always has only password authentication support. I looked over the code, am not sure if this is impletemented yet. Can this be done?

https://github.com/Azure/azure-quickstart-templates/blob/052db5feeba11f85d57f170d8202123511f72044/201-vm-multiple-nics-linux/azuredeploy.json#L250

So that we can start a VM using this template with public key authentication

**Comment by boumenot** [comment]
Sorry, I don't understand the question.  Packer creates an image, and then you get to use the image any way you want.  If you would like to use public key or password authentication is up to you, and is decided after the fact.

**Comment by puneetloya** [comment]
So this is what I understand about Azure:

The image created using azure-arm does not show up as an image in the Azure Portal. Neither as a managed image nor as a Classic Image.
It shows up as a VHD in a storage account within a Container.

So to host this VHD as a machine, we need to use the template json to create a machine out of it.
Here is a template packer generated for the image:

https://gist.github.com/puneetloya/b7d454ff0f622f5664d7202633ebdb05

The OS profile in here shows:

```
"computerName": "[parameters('vmName')]",
"adminUsername": "[parameters('adminUsername')]",
"adminPassword": "[parameters('adminPassword')]"
```
When I try to host a VM using this template json in the portal, it says to enter admin-user and admin-password and no option for SSH Public Key.

![image](https://user-images.githubusercontent.com/5791571/27403066-e7f89838-567d-11e7-85a9-8422cdb9b2a4.png)


It can also show an option for public key authentication as suggested in the above link:

https://github.com/Azure/azure-quickstart-templates/blob/052db5feeba11f85d57f170d8202123511f72044/201-vm-multiple-nics-linux/azuredeploy.json#L250


You may be right. All I am currently facing is I cant use the template directly to host a VM with public key Authentication.

**Comment by boumenot** [comment]
Gotcha.  Your question is appropriate for the community, but not as a GitHub issue.  This issue is about how to consume the image, not an issue with Packer.

If you want to deploy the image you've created you can use the [CLI to deploy a new VM](https://docs.microsoft.com/en-us/cli/azure/vm#create) with SSH keys using the Packer created VHD.

```sh
az vm create -h
```
