### ISSUE TITLE
Getting Started - Build an Image - Instructions need work.

### ISSUE THREAD

**Issue by jeffmacdonald** [hashicorp/packer#5027]
Hi,

If you follow the instructions on https://www.packer.io/intro/getting-started/build-image.html as a new packer user, you will see output like this:

```mbp0 packer $ ./run_tut1.sh
amazon-ebs output will be in this color.

==> amazon-ebs: Prevalidating AMI Name...
    amazon-ebs: Found Image ID: ami-4191b524
==> amazon-ebs: Creating temporary keypair: packer_59486e53-7ba0-b83d-cf8a-82aaf365b592
==> amazon-ebs: Creating temporary security group for this instance...
==> amazon-ebs: Authorizing access to port 22 the temporary security group...
==> amazon-ebs: Launching a source AWS instance...
    amazon-ebs: Instance ID: i-0d8b67d215a8ac327
==> amazon-ebs: Waiting for instance (i-0d8b67d215a8ac327) to become ready...
==> amazon-ebs: Adding tags to source instance
    amazon-ebs: Adding tag: "Name": "Packer Builder"
==> amazon-ebs: Waiting for SSH to become available...
==> amazon-ebs: Error waiting for SSH: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Cleaning up any extra volumes...
==> amazon-ebs: No volumes to clean up, skipping
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```

I don't have enough experience yet to understand why or how this works/happens, but for a new user, there must be a step missing from the Build an Image page. I'll continue looking into it.

**Comment by jeffmacdonald** [comment]
Ah ha, just discovered the solution. ssh_user name needs to be changed from ubuntu to ec2-user.

**Comment by jeffmacdonald** [comment]
Found out why. The instructions are for an AMI that no longer exist. ami-4191b524

And so I chose to use ami-4191b524 which is a bit newer and uses ec2-user instead of ubuntu.

**Comment by jeffmacdonald** [comment]
Okay, here is the issue: I was not using the same AMI from the tutorial. I had changed it to a Amazon Linux AMI a few weeks ago and hadn't picked up the tutorial till now.

In anycase, the AMI mentioned on the actual page no longer exists. One of the perils of putting tutorials on the net I suppose :)

**Comment by rickard-von-essen** [comment]
We should probably use an AMI filter that will pick Ubuntu 16.04 LTS. That will solve the ami-id doesn't exist issue for a long time.
