### ISSUE TITLE
Azure builder device login failes in AzureGermanCloud

### ISSUE THREAD

**Issue by elconas** [hashicorp/packer#5034]
With packer 1.0.0 we see the following error, when running device login version of packer in Azure Germany: 

```
==> azuregerman: Running builder ...
Build 'azuregerman' errored: packer-azure application not set up for Azure environment "AzureGermanCloud"
```

Reason seems to be https://github.com/hashicorp/packer/blob/master/builder/azure/common/devicelogin.go#L20-L22 which is missing an entry for Azure Germany.

**Comment by boumenot** [comment]
Device login is only supported in the Public cloud, and the docs do not make that clear.  I will update the docs.

**Comment by elconas** [comment]
But azure cli 2.0 does support device login on Azure Germany, so it is a packer limitation ?

**Comment by elconas** [comment]
Does the app id need to be centrally registered  in Azure or can it just be generated ?

**Comment by boumenot** [comment]
It's a limitation of me.  I need to create an AppId in each sovereign cloud that Packer can use for device login, and I am reluctant to take on that work.  Sovereign clouds have additional requirements and restrictions (as they should), they make this considerable.  Ensuring an appropriate distance between myself and the sovereign clouds is important. The CLI has to work in all clouds environments, so I am sure they expend considerable rigor to make this work, and have a team with which to do so.

Device login is intended as a way to quickly get started, and not meant to be an end-solution.  (Device login does not even support Windows.)

If this issue gets enough up votes I am happy to reconsider, but at this time Device Login is public cloud only.

**Comment by boumenot** [comment]
One more point...

A big motivator for the Device Login was the amount of work a user had to do (know) to create an SPN. If you're already using the cli 2.0 this work has been greatly reduced.  (I am considering porting the current docs from cli 1.0 (aka XPlat CLI) to cli 2.0 as a result of this.)

The command to create an SPN with cli 2.0 is 

```sh
az ad sp create-for-rbac
```

**Comment by elconas** [comment]
Ok I get the issue. 

We use device login on Developer Laptops to avoid distributing security principal credentials. So packer impersonates the roles and permissions of the developer (IAM corporate requirement). 

In prod and test we already use service principals and it works great.

 So if effort is too big, we can probably workaround somehow ....

**Comment by elconas** [comment]
One more question, can this be an config option. So I can use my own app id in my own ad tenant ?

**Comment by boumenot** [comment]
I had not considered this scenario - thank you for sharing it. 👍 

There's nothing special about the device login, so there's no reason you can't bring your own AppID.  It will require a code change, which is to be expected.  There is only one spot I noticed when I reviewed the code.

If you want to make the code change yourself I *think* you only need to change the following.

 1. Register your AppID in [devicelogin.go](https://github.com/hashicorp/packer/blob/master/builder/azure/common/devicelogin.go#L20-L22)

If you do try, let me know how it works for out.
