### ISSUE TITLE
provisioner/chef-solo for windows: Error uploading cookbooks

### ISSUE THREAD

**Issue by tdigangi5** [hashicorp/packer#5036]
## Issue 
When trying to provision an Windows(2012 or 2016)  amazon-ebs ami via packer 1.0.0 or 1.0.1 using chef-solo provisioner(configuration below) gets hung up on the "copy cookbooks to staging directory" and just hangs there until the sts aws session times out. 

What appears to be happening from what I can tell is linux commands are being instantiated when trying to provision this windows box(even with guest_os_type set to windows) and the directory _C:/Windows/Temp/packer-chef-solo/cookbooks-0_ cannot attain the correct permissions  to allow the copy the cookbooks to the remote server.

Please note that this exact setup(modified for linux) works perfect, there are no FW or proxies in the way of this connection.

### Packer version
1.0.0 
1.0.1

### Host platform
Mac OSX 10.12.5 
AWS Windows 2012 base ami - ami-271b6d31
AWS Windows 2016 base ami - ami-f1b5cfe7

### Packer.json 
```json 
{
	"variables": {
		"version_string": "",
		"windows_base_ami": "",
		"ami_base_name": "",
		"date_string": ""
	},
	"builders": [{
		"type": "amazon-ebs",
		"region": "us-east-1",
		"source_ami": "{{user `windows_base_ami`}}",
		"instance_type": "m3.xlarge",
		"ami_name": "{{user `ami_base_name`}}-{{user `date_string`}}",
		"security_group_id": "sg-xxxxxxxxx",
		"subnet_id": "subnet-xxxxxxxxxx",
		"vpc_id": "vpc-xxxxxxx",
		"communicator": "winrm",
		"winrm_username": "Administrator",
		"winrm_use_ssl": true,
		"winrm_insecure": true,
		"user_data_file": "./iserver-winrm-https-script.ps1",
		"associate_public_ip_address": true,
		"tags": {
			"Name": "{{user `ami_base_name`}}-v{{user `version_string`}}",
			"Environment": "packer",
			"packer": "true"
		},
		"iam_instance_profile": "packer_profile",
		"launch_block_device_mappings": [{
			"delete_on_termination": true,
			"device_name": "/dev/sda1",
			"volume_size": 100,
			"volume_type": "gp2"
		}]
	}],
	"provisioners": [
	{
		"type": "chef-solo",
		"cookbook_paths": ["berks-cookbooks"],
		"guest_os_type": "windows",
		"version": "12.19.36",
		"run_list": "recipe[cookbook::recipe]"
	},
	{
		"type": "powershell",
		"script": "./iserver-change-password.ps1"
	}]
}
```

### Run script
https://gist.github.com/tdigangi5/d69dfab3b3f16ce43325d28931c67238

### PACKER Debug log
https://gist.github.com/tdigangi5/127c8282220918e2bc6551672e40cd42

**Comment by rickard-von-essen** [comment]
Please [gist](https://gist.github.com/) a full debug log from `PACKER_LOG=1 packer build template.json`.

**Comment by rickard-von-essen** [comment]
The message is:

> amazon-ebs: 'skipping chmod 0777 C:/Windows/Temp/packer-chef-solo/cookbooks-0'

So the subject is a bit misleading.

**Comment by tdigangi5** [comment]
Updated subject and included public gist of debug log when set PACKER_LOG=1

**Comment by mwhooker** [comment]
Can you please add a few sentences describing the issue you're seeing?

**Comment by tdigangi5** [comment]
Updated with more detail surrounding issue

**Comment by mwhooker** [comment]
I think this has something to do with this error

`Error uploading cookbooks: Error restoring file from $env:TEMP\winrmcp-d00f849f-8689-42a2-68b8-d1dc1e17b442.tmp to C:\Windows\Temp\packer-chef-solo\cookbooks-0\aptos\test\packer\berks-cookbooks\aptos\test\packer\berks-cookbooks\aptos\test\packer\berks-cookbooks\aptos\test\packer\berks-cookbooks\aptos\test\packer\berks-cookbooks\aptos\files\default\certificateServerConfig.xml: restore operation returned code=1`

I wonder if this was introduced in #4438

**Comment by mwhooker** [comment]
@tdigangi5 could you test with packer 0.12.3? https://releases.hashicorp.com/packer/0.12.3/

**Comment by tdigangi5** [comment]
0.12.3 is having the exact same issue there is no change in the logs / error.

**Comment by tdigangi5** [comment]
Additional Info: https WinRM by default does not work with packer(or at least I was never able to get it work), therefore I have a powershell script called in user data that allows this to function. https://gist.github.com/tdigangi5/85b0b3bb5f7b35c7b829828928f22cdd

**Comment by tdigangi5** [comment]
amazon-ebs: 'skipping chmod 0777 C:/Windows/Temp/packer-chef-solo/cookbooks-0'
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Cleaning up any extra volumes...
==> amazon-ebs: No volumes to clean up, skipping
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: Error uploading cookbooks: Error restoring file from $env:TEMP\winrmcp-8f0ba465-406d-4210-7929-72daac7ac3ff.tmp to C:\Windows\Temp\packer-chef-solo\cookbooks-0\aptos\build\packer\berks-cookbooks\aptos\build\packer\berks-cookbooks\aptos\build\packer\berks-cookbooks\aptos\build\packer\berks-cookbooks\aptos\build\packer\berks-cookbooks\apt\templates\unattended-upgrades.seed.erb: restore operation returned code=1

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Error uploading cookbooks: Error restoring file from $env:TEMP\winrmcp-8f0ba465-406d-4210-7929-72daac7ac3ff.tmp to C:\Windows\Temp\packer-chef-solo\cookbooks-0\aptos\build\packer\berks-cookbooks\aptos\build\packer\berks-cookbooks\aptos\build\packer\berks-cookbooks\aptos\build\packer\berks-cookbooks\aptos\build\packer\berks-cookbooks\apt\templates\unattended-upgrades.seed.erb: restore operation returned code=1

==> Builds finished but no artifacts were created.
tail: packer.log: No such file or directory
Server ami:

**Comment by tdigangi5** [comment]
This was failing due to the size of the cookbook repo sourced locally on the machine. It simply needed cleaned up.

**Comment by caward24** [comment]
@tdigangi5 can you please explain what you mean by 

> This was failing due to the size of the cookbook repo sourced locally

**Comment by tdigangi5** [comment]
berks vendor -q -b="/path/to/Berksfile" was continuously adding cookbooks to the hidden directory that is created and the dir got quite large the plugin would time out before uploading. I believe it was a winrm timeout issue while uploading. The error thrown by packer is a little odd for this issue.

**Comment by BenMitchell1979** [comment]
Has this been fixed or is there a resolution. I'm getting this error as well.

**Comment by BenMitchell1979** [comment]
@tdigangi5 - did you ever solve this issue? I'm running Packer v1.1.3 and attempting to configure EC2 instance (builder amazon-ebs) with chef-solo provisioner. I'm getting the following error 'Build 'amazon-ebs' errored: Error uploading cookbooks'... Any assistance would be greatly appreciated.

**Comment by SNVSNANNAPA** [comment]
@tdigangi5 I'm seeing the same issue with packer 1.3.2 . What hidden directory you are pointing to?

**Comment by SNVSNANNAPA** [comment]
Strange, I deleted the folder that is causing the problem and ran the packer build. It just worked. Later , I ran the vendor-cookbooks again and then the packer build , everything worked fine even though the file that created the actual issue exists in the folder.
