### ISSUE TITLE
amazon: Tags for Security Groups

### ISSUE THREAD

**Issue by zach5410** [hashicorp/packer#5037]
Hey guys, I work for a company that has strict security measures when it comes to AWS.

One of these rules requires the use of tags on security groups. 

Basically by the time we get [here](https://github.com/hashicorp/packer/blob/b1bcf62ae1e92bff5fc0dcad19b63707def246e3/builder/amazon/common/step_security_group.go#L90
) we will be dead in the water.

So I wanted to purpose adding the tags before you apply the Ingres.

Is it ok if I work on this and update the tests?

**Comment by rickard-von-essen** [comment]
I'm not sure that is necessary. The simple solution is to create a SG and reference it with [security_group_ids](https://www.packer.io/docs/builders/amazon-ebs.html#security_group_ids).

**Comment by zach5410** [comment]
Security group IDs is just an array of IDs, it doesn't replace the possible necessity of having security tags.  It doesn't harm anything to add the tags.  

A lot of bigger companies right now are pushing Amazon to have tags upon creation for security purposes.  So this would be a step in that direction.
