### ISSUE TITLE
builders/azure-rm WinRM times out long before winrm_timeout value

### ISSUE THREAD

**Issue by ryanl-ee** [hashicorp/packer#5039]
Packer: 1.0.1
Platform: Ubuntu 17.10
Template: https://gist.github.com/ryanl-ee/99c9cfac91d01925f1c7995ce8df0d0c
Verbose Packer log: https://gist.github.com/ryanl-ee/fa56a64a7eaf00efa28492bb02ad0676

I'm building a template to create a Server 2012 R2 image in Azure, basing it off of the example template. I added a few Powershell provisioners to install WMF 5.1 and install Windows Updates. The template works fine without the Windows Updates (but does not sysprep properly potentially due to WMF 5.1, which is one reason I'm running WU afterwards) but when I add the WU Powershell provisioner, the VM understandably takes much longer to reboot afterwards. This is where the Packer run times out. I have `"winrm_timeout": "5h",` set and the run times out at about an hour. I saw this similar issue: #4848 - but it looks like it's already been merged in and included in the 1.0.1 release. I've reproduced this multiple times and on a Windows box as well. 

Has anyone seen this before? Is this an issue with the WinRM communicator or my VM? Could the WinRM service on the VM be listening but respond improperly after updates, causing Packer to immediately time out? Could an update be outright disabling or messing with WinRM? Though, why would WinRM time out after an hour when the option is set to 5 hours?

Thanks in advance for any assistance!

**Comment by mwhooker** [comment]
@ryanl-ee I think this is a timeout from the `windows-restart` provisioner. It looks like it copied a bunch of code from the winrm timeout so I'm thinking the error messages are probably confusing.

Can you set `restart_timeout` in the provisioner to be longer than `5m` and see if it works?

**Comment by ryanl-ee** [comment]
Great call out. That is probably the issue. I didn't even see that option. I'll try that again now, thanks!

**Comment by ryanl-ee** [comment]
That was it! Thanks again.

**Comment by stevenroha** [comment]
I am still having the issue, able to ping the VM from the packer server. added restart_timeout = 6m in provisioner. 

Using Packer 1.1.1

**Comment by mwhooker** [comment]
@stevenroha please open a new issue. this one is solved
