### ISSUE TITLE
Packer Azure keep temporary resource group

### ISSUE THREAD

**Issue by luisamador** [hashicorp/packer#5045]
Packer should give you the option to keep the temporary resource group when building an image.

Why? - If the security principal used by Packer doesn't have permissions to create/delete resource groups within the Azure subscription, Packer build will fail.

The admin of my subscription could create a resource group called 'packer' which would be used by Packer during the build process as the temporary resource group.

The basic steps for a build are:
Create a resource group. -----------> If the temporary resource group already exists, leave it as it is 
Validate and deploy a VM template.
Execute provision - defined by the user; typically shell commands.
Power off and capture the VM.
Delete the resource group. ----------> Should be optional to delete it so can it can be reused
Delete the temporary VM's OS disk.

It would make my life much easier since we don't want to create a super-admin service principal in our Azure subscription.

**Comment by stewartadam** [comment]
+1, keeping the RG makes it easier to debug deployment failures as well.

**Comment by stuartdonald-ibboost** [comment]
+1.

My current workaround for this is pretty ugly.

Create a new resource group called packer-workspace-south.

Create a new Role (https://docs.microsoft.com/en-us/azure/active-directory/role-based-access-control-manage-access-powershell#modify-a-custom-role). With a definition like this:

```
{
    "Name":  "Packer builder",
    "Description":  "Lets you build packer images.",
    "Actions":  [
                    "*"
                ],
    "NotActions":  [
                       "Microsoft.Authorization/*/Delete",
                       "Microsoft.Authorization/*/Write",
                       "Microsoft.Authorization/elevateAccess/Action",
                       "Microsoft.Resources/subscriptions/resourcegroups/delete"
                   ],
    "AssignableScopes":  [
                             "/subscriptions/xxxxxxxx/resourcegroups/packer-workspace-south"
                         ]
}
```

Then give my API user the role "Packer builder" in the resource group "packer-workspace-south".

If you do this, you will be able to build with packer using temp_resource_group_name=packer-workspace-south, however it will error out at the end when it tries to delete the resource group. So to complete the workaround, you then need to clear out the resource group yourself. I do that using an empty ARM template with a mode of "Complete". Using Ansilbe that looks like this

```---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Create Azure Deploy
      azure_rm_deployment:
        state: present
        deployment_mode: complete
        resource_group_name: "{{ resourceGroup }}"
        location: "{{ location }}"
        template:
            {
                "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
                "contentVersion": "1.0.0.0",
                "parameters": {   },
                "variables": {  },
                "resources": [  ],
                "outputs": {  }
            }
```

**Comment by rajpolaris** [comment]
+1. It is.a problem to give "contributor" level subscription access to Packer user.
It will better to create a resource group that packer can use.

**Comment by codyja** [comment]
I agree also, would be nice.

**Comment by mwhooker** [comment]
seems like the best way to solve this is to take a rg, the same way the aws builder can take a [security group](https://www.packer.io/docs/builders/amazon-ebs.html#security_group_id)

**Comment by boumenot** [comment]
That's the easy part.  The hard part is tear down.  The builder assumes it owns the resource group, and as a result tear down is just a delete to clean everything up.  It isn't that can't be done - it can.  It just needs to take into account everything it built (vs. borrowed) when deleting. The builder must walk the dependencies in reverse to ensure proper tear down.

**Comment by ArjenSchwarz** [comment]
Ran into a similar issue just now where I set the temp_resource_group_name to an existing resource group, which resulted in Packer deleting everything in that resource group, even if it didn't create it. Having only used Packer with AWS before, I did not expect that behaviour. I now know that it always deletes the resource group, but that is only mentioned in the advanced section of the documentation which I'd only skimmed through. 
At the very least, can this behaviour be mentioned as a warning with the temp_resource_group_name description? Obviously an option to keep the resource group would be better, but this might prevent others from running into my issue.

**Comment by SectorNine50** [comment]
Big +1 here.  Just managed to inadvertently delete one of our sandbox RG's due to this behavior.

**Comment by clangaxon** [comment]
+1 for radically reducing the permissions required.

**Comment by rodrigocmn** [comment]
+1 same permissions issue here

**Comment by duckie** [comment]
+1, would like to avoid entire subcription permissions for packer
