### ISSUE TITLE
openstack builds that exceed 1 hour duration always fail

### ISSUE THREAD

**Issue by justme1121** [hashicorp/packer#5046]
### Any openstack build that exceeds 1 hour for running will always fail with the following in the log:

2017/06/22 06:50:29 ui: [1;32m==> openstack: Stopping server: 00de30fb-ff9a-48c1-8c87-c0174b0672be ...[0m
2017/06/22 06:50:30 ui error: [1;31m==> openstack: Error deleting temporary floating IP[0m
2017/06/22 06:50:30 ui error: [1;31m==> openstack: Error terminating server, may still be around: No suitable endpoint could be found in the service catalog.[0m
2017/06/22 06:50:30 [INFO] (telemetry) ending openstack
2017/06/22 06:50:30 [INFO] (telemetry) found error: Error stopping server: Successfully re-authenticated, but got error executing request: Invalid request due to incorrect syntax or missing required parameters.
2017/06/22 06:50:30 ui error: [1;31mBuild 'openstack' errored: Error stopping server: Successfully re-authenticated, but got error executing request: Invalid request due to incorrect syntax or missing required parameters.[0m
2017/06/22 06:50:30 Builds completed. Waiting on interrupt barrier...
2017/06/22 06:50:30 machine readable: error-count []string{"1"}
2017/06/22 06:50:30 ui error: 
==> Some builds didn't complete successfully and had errors:
2017/06/22 06:50:30 machine readable: openstack,error []string{"Error stopping server: Successfully re-authenticated, but got error executing request: Invalid request due to incorrect syntax or missing required parameters."}
2017/06/22 06:50:30 ui error: --> openstack: Error stopping server: Successfully re-authenticated, but got error executing request: Invalid request due to incorrect syntax or missing required parameters.

Packer version 1.0.2
Host operating system windows 10

**Comment by rickard-von-essen** [comment]
Related to #4260

**Comment by rickard-von-essen** [comment]
And #4262

**Comment by ygina** [comment]
I ran into the same issue with Packer 1.0.2 and macOS 10.12. As mentioned in #4260, there is "a bug in the keystone v3auth function used in the version of gophercloud used by packer." Vendoring the latest version of gophercloud fixed it for me.

**Comment by SwampDragons** [comment]
@justme1121 are you able to test the change that @ygina made to verify that it solves your problem? https://github.com/hashicorp/packer/pull/5057

**Comment by justme1121** [comment]
yes, that fixes the problem
