### ISSUE TITLE
Updating aws-sdk-go api

### ISSUE THREAD

**Issue by zach5410** [hashicorp/packer#5047]
Hey guys, I am working on adding tags on creation instead of after when using amazon-ebs.

Amazon has updated its api for RunInstancesInput to allow tags. [here](https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#RunInstancesInput.SetTagSpecifications)

I have updated the code in step_run_source_instance to use the new api value.  But when I go into the api I do not see the new SetTagSpecification value.

When I try and add the values into the api.go file and then use make test it resets the api.go file.

How can I update the file with the newest api?

**Comment by zach5410** [comment]
Also, where can I find the test files for step_run_source_instance?  I would like to update the test with the new procedure, but I am having a hard time finding the test suites

**Comment by rickard-von-essen** [comment]
If I remember correctly (we recently changed to `govendor`):

1) Update the dependency in your `GOPATH`.
2) Run `govendor update`
3) Verify the changes and commit.

Tests should be in `step_run_source_instance_test.go`, but there ain't any for that step.

**Comment by zach5410** [comment]
@rickard-von-essen can you please elaborate on why I am changing my GOPATH dependency.  
Newbie to govendor lol

**Comment by mwhooker** [comment]
You can also use fetch

```
	fetch    Add new or update vendor folder packages from remote repository.
```

`govendor fetch github.com/aws/aws-sdk-go/service/ec2`

if there's a specific git commit you want to update to

`govendor fetch github.com/aws/aws-sdk-go/service/ec2@<sha hash>`

**Comment by mwhooker** [comment]
see also https://github.com/hashicorp/packer/blob/master/CONTRIBUTING.md#govendor

**Comment by zach5410** [comment]
Thanks guys!
