### ISSUE TITLE
Powershell provisioner does not return all output

### ISSUE THREAD

**Issue by matt-richardson** [hashicorp/packer#5050]
The powershell provisioner does not always return all STDOUT content to the host.

It sometimes does, sometimes doesn't, so its a pain for debugging. 

I am also using TeamCity service messages at the start and end of the file (for log file grouping), so when it doesn't return all the output, it confuses TeamCity.

In my repro, it returns most of the stdout, but then returns the whole lot again encoded in the lovely WinRM xml.

- Packer version from `packer version`: `Packer v1.0.0`
- Host platform: `macOS Sierra 10.12.5 (16F73)` (also happens on ubuntu xenial)
- scripts and debug log:
https://gist.github.com/matt-richardson/26cf5c67077695a6d7c0d741b2019fae

**Comment by SwampDragons** [comment]
Thanks for opening this issue! https://github.com/hashicorp/packer/pull/5089 solves this; I just ran your repro case against it and it appears cromulent.

**Comment by matt-richardson** [comment]
Thanks for the fix, @SwampDragons. I've just upgraded our pipeline to `1.0.3`, and we're now getting all the stdout output.
