### ISSUE TITLE
Build finished but no artifacts created - hyperv-iso

### ISSUE THREAD

**Issue by mhmsh** [hashicorp/packer#5052]
I get the error:
`Build 'hyperv-iso' errored: Error exporting vm: PowerShell error: Move-Item : An object at the specified path C:\Users\M43EA~1.GAM does not exist.`

packer output: https://gist.github.com/mhmsh/84f6456cfdb030d3159a7fcf6bc3a2e4 
template: https://gist.github.com/mhmsh/9c54b382e060c997e3b3182d6581f930.js
log: https://gist.github.com/mhmsh/2fa52669653c15f0fa9d05ebd8b3391c

**Comment by cdhunt** [comment]
@mhmsh Closed w/o comment? What happened? Did you fix it? Did you give up?

**Comment by karousn** [comment]
same question as @cdhunt !

**Comment by mhmsh** [comment]
So problem was just an weird env variable set for some strange reason. via powershell i looked at all ver env's and found one pointing my temp to C:\Users\M43EA~1.GAM, which didnt exist. Manually i set it to something like C:\temp and everything worked.

**Comment by SympaHannuPiki** [comment]
I do get this same exact error and I do not have any 'weird env variable' in my system, that I can see. If that is set by Packer execution, how would I get that out? Everything else works just fine, but last part after Hyper-V export process do fail.
