### ISSUE TITLE
vmware-iso: Unable to find available VNC port between 5900 and 6000 after updating to 1.0.2

### ISSUE THREAD

**Issue by giordyb** [hashicorp/packer#5055]
Packer version 1.0.2
Host: Centos 7.3

I tried updating the packer binary to 1.0.2 from 1.0.0 but it fails with 

`vmware-iso: Unable to find available VNC port between 5800 and 6000 after updating to 1.0.2`

when creating a vm on esx 5.5.

when running in debug mode i get a long list of
```
2017/06/23 16:11:56 packer: 2017/06/23 16:11:56 Timeout connecting to: myhost:5938 (check firewall rules)
2017/06/23 16:11:56 packer: 2017/06/23 16:11:56 Trying address: myhost:5939...
```
from 5900 to 5999.

After reverting the binary back to 1.0.0 everything works fine and the build succeeds.

**Comment by SwampDragons** [comment]
Probably this:  https://github.com/hashicorp/packer/pull/5051 :)

**Comment by mwhooker** [comment]
@giordyb sorry about that. You can fix this by setting the env var `PACKER_ESXI_VNC_PROBE_TIMEOUT` to `30s`

**Comment by zzebster** [comment]
I cant seem to get setting that variable to make any difference. It still keeps saying unable to find available VNC port between 5900 and 5964. Could you give the the exact information to put in the packer.config file to set this. Thanks

**Comment by rickard-von-essen** [comment]
It's a environment variable, if you are using MacOS, Linux etc set it with:

```shell 
export PACKER_ESXI_VNC_PROBE_TIMEOUT=10s
```

And then run packer in the same shell.
