### ISSUE TITLE
Parallels provisioner can fail with open .../build_name.app: no such file or directory

### ISSUE THREAD

**Issue by ncdc** [hashicorp/packer#5056]
Packer version: v1.0.2
Host platform: macOS Sierra 10.12.5
Parallels Desktop 12.2.0 Pro Edition (41591)

I'm not sure if this is a Packer issue or a go issue, but it appears that [this code](https://github.com/hashicorp/packer/blob/81522dced0b25084a824e79efda02483b12dc7cd/builder/parallels/common/artifact.go#L34-L38) sometimes sees and tries to delete e.g. packer-foo.pvm/packer-foo.app, and I think there is a race in between when it sees it and when it tries to delete it, resulting in `open packer-foo.pvm/packer-foo.app: no such file or directory`. Looking at the godoc for `os.RemoveAll`, it is supposed to return `nil` for "not found" errors, but I'm wondering if there's some weird edge case happening here.

I have added some debugging code locally to print out values of `unnecessaryFile` and `path` each time through the loop, as well as the resulting error from `os.RemoveAll`. Now that I've added that code, I've run a build 3 or 4 times, but it has yet to print out a path ending in `.app` and it's no longer failing :-(

This was also mentioned [here](https://groups.google.com/forum/#!topic/packer-tool/QXhh6QTsDAg), but, like I'm seeing, it's intermittent.

cc @rickard-von-essen

**Comment by rickard-von-essen** [comment]
cc @legal90, I've no clue yet. Do you have any guess?

**Comment by ncdc** [comment]
Hmm I just managed to get the error, but it did *not* print out my debugging statements. Now I'm confused as to where this error is coming from!

One difference for this failed run is that I added back my scripts to install Parallels Tools and to configure docker, which I had removed from the list of shell provisioners to try to minimize the turnaround time while debugging.

**Comment by ncdc** [comment]
Aha, the `.app` directory is created when I click on the VM screenshot in the Control Center to open up the console

**Comment by ncdc** [comment]
Ok I think I know what's going on. If you open the console window for the VM when packer is running, it creates this `.app` directory. When `filepath.Walk` executes, it tries to walk into the `.app` directory, but it doesn't exist any more by the time `visit` is invoked. As a result, the `err` passed to `visit` is non-nil. I think if we add an `os.IsNotExist(err)` check and return `filepath.SkipDir` in that case, we should be able to get past this. Testing it out now.

**Comment by ncdc** [comment]
Yeah, that fixes it. I'll submit a PR soon.

**Comment by rickard-von-essen** [comment]
Awesome triaging!
