### ISSUE TITLE
The script does not work with latest azure cli 2.0

### ISSUE THREAD

**Issue by andrewcheny** [hashicorp/packer#5061]
Tried with Azure CLI 2.0. Replace all the command 'azure' to 'az'. Still not working.

az: error: argument _command_package: invalid choice: config
usage: az [-h] [--output {json,tsv,table,jsonc}] [--verbose] [--debug]
          [--query JMESPATH]
          {acr,acs,webapp,appservice,functionapp,batch,billing,cdn,cloud,cognitiveservices,component,configure,consumption,cosmosdb,dla,dls,feedback,find,interactive,iot,keyvault,lab,monitor,network,login,logout,account,mysql,postgres,redis,group,resource,provider,feature,tag,policy,lock,managedapp,role,ad,sf,sql,storage,vm,vmss,disk,snapshot,image}
          ...

**Comment by rickard-von-essen** [comment]
Which script?

**Comment by andrewcheny** [comment]
azure-setup.sh.

Solved by installing Azure Cli 1.0.
