### ISSUE TITLE
packer unable to find VNC port when using v1.0 or greater and vmware-iso builder

### ISSUE THREAD

**Issue by qubitrenegade** [hashicorp/packer#5073]
Hello, since upgrading to packer 1.0X I have been unable to build using the "vmware-iso" builder as packer errors out with a message that it's unable to find a VNC port.  Using v 0.12.1 and the exact same template as below works without issue.

- Packer version
Packer v1.0.2

- Host platform
CentOS 6.9, replicated on CentOS 7.2

Gist of errors and template:

https://gist.github.com/qubitrenegade/d1107adafc2ed686be7769aac7de3c93

Seems like possible recurrence of this bug?  https://github.com/hashicorp/packer/issues/1480

**Comment by rickard-von-essen** [comment]
This duplicates #5055 which has been fixed on master.

**Comment by avnish30jn** [comment]
when will the binaries on website <https://www.packer.io/downloads.html> be updated with the bugfix ?
