### ISSUE TITLE
Hyper-V builder - please add option where VM files need to be created

### ISSUE THREAD

**Issue by it-praktyk** [hashicorp/packer#5075]
It's a feature request for a Hyper-V builder.

Under build process are created files for a virtual machine (disks, configs, etc.).

Currently they are created in the path $TEMP what is usually like ```C:\Users\<USER_NAME>\AppData\Local\Temp\``` - usually this path is located on a system drive and space on it is limited.

Build process - if free space is near zero - is paused by host OS.

Please implement option to provide required path with default value as returns 
```Get-VMHost | Select VirtualHardDiskPath``` - it's usually configured on Hyper-V host and points to another than system disk/partition.

In case if more explanation is needed please let me know. Thank you.

**Comment by Lee303** [comment]
I've just added a PR which will allow the path to be explicitly defined within templates

**Comment by it-praktyk** [comment]
Thank you!
