### ISSUE TITLE
VMware Provisioner sometimes finishes with i/o timeout after shrinking disk

### ISSUE THREAD

**Issue by mindrunner** [hashicorp/packer#5077]
I am using VMware provisioner to build a macOS Vagrant box. The last step is to call the shrink.sh script to compact the vmdk-files. This script calls 'vmware-tools-cli disk shrink' in the virtual machine. I assume, that zeros are written to the whole free disk space. Calling this manually, makes the vm unresponsive for some seconds (probably when the disk is completely filled) and drops some network connections (including the ssh connection from packer).

```
==> vmware-iso: Pausing 30s before the next provisioner...
==> vmware-iso: Provisioning with shell script: ../osx-vm-templates/scripts/shrink.sh
    vmware-iso: rm: /private/var/vm/swapfile0: Operation not permitted
    vmware-iso: Please disregard any warnings about disk space for the duration of shrink process.
    vmware-iso:
    vmware-iso: Progress: 100 [===========>]
==> vmware-iso: Pausing 30s before the next provisioner...
==> vmware-iso: Provisioning with shell script: ../scripts/nothing.sh
==> vmware-iso: Stopping virtual machine...
==> vmware-iso: Deleting output directory...
Build 'vmware-iso' errored: Retryable error: Error uploading script: dial tcp 192.168.151.129:22: i/o timeout

==> Some builds didn't complete successfully and had errors:
--> vmware-iso: Retryable error: Error uploading script: dial tcp 192.168.151.129:22: i/o timeout

==> Builds finished but no artifacts were created.
```

This does not always happen. About 1 of 10 builds finishes without error.

Packer Version: Packer v1.0.2
Host: macOS 10.12.5
Debug Log: 
https://gist.github.com/mindrunner/b70b5a1f30cc3d8511246886b85a784c

Example:
https://gist.github.com/mindrunner/369bd841277984d5e1322c478916cb26

I cannot really provide a "minimal example" The Ansible provisioning script is huge and not (yet) open source. However, when I skip the big provisioning step and create an almost empty macOS box, I never see the i/o error problem.

**Comment by rickard-von-essen** [comment]
I don't understand what you think Packer is doing wrong? Please elaborate. 

Have you checked how bento do their minimization? See https://github.com/chef/bento/blob/master/scripts/common/minimize.sh

And packer already do compaction, see https://www.packer.io/docs/builders/vmware-iso.html#skip_compaction

**Comment by mindrunner** [comment]
Well, as my understanding is, you have to first zero out free disk space (inside vm). Then shutdown. Then compact the image from the host machine.

Bento is doing the same thing than I am trying with vmware-tools-cli. The Packer compaction is the second step of what has to be done to minimize the image size.

E.g.: When I skip zeroing the disk space before packer compacts it, my resulting image is about 25Gb. With zeroing it is about 18Gb. 

> I don't understand what you think Packer is doing wrong?
It should not fail. Everything is happening as expected. Furthermore, it should not sometimes fail and sometimes finish building my image without any changes on my side.

**Comment by mindrunner** [comment]
I added debug log output to first post!

**Comment by lmayorga1980** [comment]
:+1:

**Comment by mindrunner** [comment]
I started using a modified version of "bento"-approach. (calculating the free space and writing little less zeroes, so that the disk will not fill up to the last bit.). Seems to work more reliable for me.
