### ISSUE TITLE
vagrant-cloud uploads are failing (post migration)

### ISSUE THREAD

**Issue by ladar** [hashicorp/packer#5080]
My tokens were supposed to be migrated, but now my configs are failing during the release stage. See this debug output:

```
2017/06/28 18:10:00 ui: ==> magma-centos6-vmware: Running post-processor: vagrant-cloud
2017/06/28 18:10:00 [INFO] (telemetry) Starting post-processor vagrant-cloud
2017/06/28 18:10:00 ui: ==> magma-centos6-vmware (vagrant-cloud): Verifying box is accessible: lavabit/magma-centos6
2017/06/28 18:10:00 packer: 2017/06/28 18:10:00 Post-Processor Vagrant Cloud API GET: https://vagrantcloud.com/api/v1/box/lavabit/magma-centos6?access_token=ACCESS_TOKEN
2017/06/28 18:10:00 packer: 2017/06/28 18:10:00 Post-Processor Vagrant Cloud API Response:
2017/06/28 18:10:00 packer: 
2017/06/28 18:10:00 packer: &{Status:401 Unauthorized StatusCode:401 Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[X-Content-Type-Options:[nosniff] X-Request-Id:[e76727a3-8417-4a5e-bcbb-832db81e7150] Connection:[keep-alive] Set-Cookie:[_atlas_session_data=a0xXV2<redacted>1bc18d; path=/; expires=Fri, 28 Jul 2017 23:10:00 -0000; secure; HttpOnly] X-Xss-Protection:[1; mode=block] Cache-Control:[no-cache] Via:[1.1 vegur] Server:[Cowboy] Date:[Wed, 28 Jun 2017 23:09:59 GMT] X-Frame-Options:[SAMEORIGIN] Content-Type:[application/json; charset=utf-8] X-Runtime:[0.097137]] Body:0xc420294400 ContentLength:-1 TransferEncoding:[chunked] Close:false Uncompressed:false Trailer:map[] Request:0xc420113500 TLS:0xc42051be40}
2017/06/28 18:10:00 [INFO] (telemetry) ending vagrant-cloud
2017/06/28 18:10:00 [INFO] (telemetry) found error: Error retrieving box: 
2017/06/28 18:10:00 Deleting original artifact for build 'magma-centos6-vmware'
2017/06/28 18:10:00 ui error: Build 'magma-centos6-vmware' errored: 1 error(s) occurred:

* Post-processor failed: Error retrieving box: 
```

Of course when I logged in double check my token was migrated,  I got redirected to the Vagrant cloud, where I activated my Atlas account... only to be met with a generic error message. 

P.S. This also happened to be my first attempt using packer version 1.0.2. 

![screenshot from 2017-06-28 18-49-09](https://user-images.githubusercontent.com/1434008/27665447-d6f025b4-5c32-11e7-9056-cdca7de97cc9.png)

**Comment by ladar** [comment]
Not sure if it's related but now I see... which I assume was unplanned? The site was a little sluggish this morning. 

![screenshot from 2017-06-28 19-01-56](https://user-images.githubusercontent.com/1434008/27665709-5cf349a6-5c34-11e7-9afa-10347cdfc3ae.png)

**Comment by ladar** [comment]
This issue appears to have resolved itself on it's own. I'm still having trouble with the libvirt builder (EOF errors) and packer 1.0.2 but I believe that issue is unrelated and will open a separate issue once I confirm it.

**Comment by grv87** [comment]
The issue still exists. It occurs when you try to create a new box (i.e. this name is not yet registered on Vagrant Cloud).
I have to manually login to Vagrant Cloud and create empty box (without versions) to workaround this.
