### ISSUE TITLE
increase wait time for export?

### ISSUE THREAD

**Issue by caphrim007** [hashicorp/packer#5090]
When I attempt to build a packer ova image using the Virtualbox builder, I am repeatedly receiving an error from the VBoxManage command about failing to remove network related settings do to the VM being locked or in the process of unlocking.

I checked out the source and changed the following line to 10 instead of 1

https://github.com/hashicorp/packer/blob/0c116981ab877d078636dc24795964b7eb607473/builder/virtualbox/common/step_export.go#L39

Can this value be increased? or, can it be changeable via the template so that I can configure it myself?

**Comment by SwampDragons** [comment]
I wonder if there's a better way to do this than a sleep.  Sounds like we need to figure out a way to determine that the vm is actually asleep, or try several times so that we don't cause 10 second halts when we don't actually need them.

**Comment by mwhooker** [comment]
@caphrim007 Can you reproduce this reliably?

If you can post a debug log, I have an idea that might work that I would like you to test.

**Comment by caphrim007** [comment]
@mwhooker I believe so. what do you want me to try

**Comment by mwhooker** [comment]
@caphrim007 I need to write it first 😉, but I will post here when I have something to test. Thanks!

**Comment by caphrim007** [comment]
okie doke

**Comment by caphrim007** [comment]
@mwhooker any update?

**Comment by mwhooker** [comment]
not yet, but was just thinking about this issue. haven't forgotten!

**Comment by caphrim007** [comment]
ok, np. just crossed my mind too, so figured i would ping you.

**Comment by mwhooker** [comment]
Actually can you try setting `post_shutdown_delay` to something like `10s`? I think this feature is already in here

https://www.packer.io/docs/builders/virtualbox-iso.html#post_shutdown_delay

if that doesn't work let me know and I will reopen. Please post your complete debug log in that case

**Comment by caphrim007** [comment]
@mwhooker will try! thanks!
