### ISSUE TITLE
Packer creates unusable instances with ENA

### ISSUE THREAD

**Issue by clangaxon** [hashicorp/packer#5093]
We're using Packer 1.0.2 and discovered that #4578 quietly made enhanced_networking: true enable both Sriov and ENA after debugging why we could no longer launch working P2 instances.

While this is probably a fine scenario if you only support Amazon Linux, which has both drivers, it's a pretty bad user experience when you're using e.g. CentOS which supports sriov but not ENA.

Independent options to set these would be more flexible.  If this is a 'feature' as discussed in #4578, then shouldn't packer should just force enhanced networking on automatically to make people install drivers for optimal networking? :)  Yeah, doesn't make much sense to me either. :)

Thanks.

EDIT: changed to the correct PR ref. / @rickard-von-essen

**Comment by rickard-von-essen** [comment]
The quick solution is just to compile the ENA driver ;-). 

But the change seems like a bit bad backwards compatibility to me.

**Comment by SwampDragons** [comment]
@clangaxon I have a change that should fix this; can I have a gist of your packer config so I can confirm that it will solve your problem?
