### ISSUE TITLE
'fatal error: newosproc' when building multiple images

### ISSUE THREAD

**Issue by sebolabs** [hashicorp/packer#5095]
I have a problem when running multiple (12-13) packer builds on the same box.
- Packer version: 0.12.1 and 1.0.2
- Host platform: RHEL 6.8
- AWS instance: c4.xlarge
- ulimit -u => 10240
- ulimit -n => 500000
- builder: amazon-ebs

I'm seeing this:
```
runtime: failed to create new OS thread (have 2017/07/05 17:56:59 Waiting on builds to complete...
26 already; errno=11)
runtime: may need to increase max user processes (ulimit -u)
fatal error: newosproc
```
or this:
```
runtime: failed to create new OS thread (have 10 already; errno=11)
runtime: may need to increase max user processes (ulimit -u)
fatal error: newosproc
```
a sample stack:
```
runtime stack:
runtime.throw(0x18e52d3, 0x9)
/usr/local/Cellar/go/1.8.3/libexec/src/runtime/panic.go:596 +0x95
runtime.newosproc(0xc420273000, 0xc420066000)
/usr/local/Cellar/go/1.8.3/libexec/src/runtime/os_linux.go:163 +0x18c
runtime.newm(0x1940430, 0xc420021900)
/usr/local/Cellar/go/1.8.3/libexec/src/runtime/proc.go:1628 +0x137
runtime.startm(0x0, 0xc420063f01)
/usr/local/Cellar/go/1.8.3/libexec/src/runtime/proc.go:1698 +0x17e
runtime.wakep()
/usr/local/Cellar/go/1.8.3/libexec/src/runtime/proc.go:1779 +0x48
runtime.resetspinning()
/usr/local/Cellar/go/1.8.3/libexec/src/runtime/proc.go:2141 +0x71
runtime.schedule()
/usr/local/Cellar/go/1.8.3/libexec/src/runtime/proc.go:2229 +0x136
runtime.park_m(0xc4202f51e0)
/usr/local/Cellar/go/1.8.3/libexec/src/runtime/proc.go:2285 +0xab
runtime.mcall(0x0)
/usr/local/Cellar/go/1.8.3/libexec/src/runtime/asm_amd64.s:269 +0x5b
```
After recompiling packer with go 1.9beta2:
```
2017/07/06 21:32:09 packer: 2017/07/06 21:32:09 [INFO] Packer version: 1.0.3-dev (4313f98)
2017/07/06 21:32:09 packer: 2017/07/06 21:32:09 Packer Target OS/Arch: linux amd64
2017/07/06 21:32:09 packer: 2017/07/06 21:32:09 Built with Go Version: go1.9beta2
[...]
2017/07/06 21:32:09 Loading provisioner: file
2017/07/06 21:32:09 Plugin could not be found. Checking same directory as executable.
2017/07/06 21:32:09 Current exe path: /opt/packer/packer
2017/07/06 21:32:09 Creating plugin client for path: /opt/packer/packer
2017/07/06 21:32:09 Starting plugin: /opt/packer/packer []string{"/opt/packer/packer", "plugin", "packer-provisioner-file"}
2017/07/06 21:32:09 Waiting for RPC address for: /opt/packer/packer
2017/07/06 21:32:09 packer: runtime/cgo: pthread_create failed: Resource temporarily unavailable
2017/07/06 21:32:10 packer: SIGABRT: abort
2017/07/06 21:32:10 packer: PC=0x3f8fa32495 m=0 sigcode=18446744073709551610
```

It tends to happen on template validation too. Had to use the `-syntax-only` option to avoid it.

Can't really find the reason why is it happening as it worked some time ago and there were no system and/or configuration changes on the box.

**Comment by SwampDragons** [comment]
Which version of packer did it work for previously?

**Comment by sebolabs** [comment]
It worked with 0.12.1 and stopped (I know, I was thinking the same, sth on the system level had to change, but I can't confirm it at all).
I do a lot of testing currently and there were cases where it went through but these are in minority.

**Comment by sebolabs** [comment]
UPDATE:
I didn't have much time yesterday to play with that recompiled 1.0.3-dev version but today I performed this set of tests on a new m3.large instance (same image, same system config):
1/ 13 parallel builds with 0.12.1 - failed
2/ 13 parallel builds with 1.0.3-dev @ go1.9beta2 - passed
3/ 13 parallel builds with 0.12.1 - failed
4/ 13 parallel builds with 1.0.3-dev @ go1.9beta2 - passed
5/ 13 parallel builds with 1.0.3-dev @ go1.9beta2 - passed
6/ 13 parallel builds with 1.0.3-dev @ go1.9beta2 - passed

**Comment by SwampDragons** [comment]
How bizarre! So it's fixed in the 1.0.3 dev version... I don't remember anything being merged that seems relevant but I guess I won't complain.  Shall I close this ticket with the caveat that we'll reopen and investigate if it crops back up?

**Comment by sebolabs** [comment]
It seems to be all about the go version used to compile packer. I've read somewhere that they addressed some issues related to threads parallelisation in that 1.9 beta version, that's why I gave it a try. It's been already tested at least 30 times and no failures.
So, yes, we can close this ticket as I don't expect anything else to happen here.

**Comment by rickard-von-essen** [comment]
Thanks for reporting back.
