### ISSUE TITLE
Question: export virtualbox and qemu box while building vagrant box

### ISSUE THREAD

**Issue by shibumi** [hashicorp/packer#5096]
Hello,
is there any way to export a virtualbox image and a qemu image while building the vagrant box or do I need to open the vagrant box after the build manually to get the images?

My goal is that I have the following Output:

> a virtualbox image
> a qemu image
> a virtualbox vagrant box
> a qemu/libvirt vagrant box

At the moment I just get the both vagrant boxes.

**Comment by rickard-von-essen** [comment]
Set `keep_input_artifact` to `true`, see https://www.packer.io/docs/templates/post-processors.html#input-artifacts
