### ISSUE TITLE
Request for configurable Expunge in Cloudstack Builder

### ISSUE THREAD

**Issue by IanTheIan** [hashicorp/packer#5097]
Within the Cloudstack builder, because builder/cloudstack/step_create_instance.go (lines 122-123) explicitly force an expunge operation, the implication is that an Administrative user is required to run Packer against it.  Can we make this a configurable option, please?  This way we can use non-admin users and the build doesn't crash out with:

2017/07/05 15:47:51 ui error: ==> cloudstack: Error destroying instance: Undefined error: {"errorcode":530,"errortext":"Parameter expunge can be passed by Admin only. Or when the allow.user.expunge.recover.vm key is set."}
2017/07/05 15:47:51 ui:     cloudstack: Instance has been deleted!
==> cloudstack: Error destroying instance: Undefined error: {"errorcode":530,"errortext":"Parameter expunge can be passed by Admin only. Or when the allow.user.expunge.recover.vm key is set."}
    cloudstack: Instance has been deleted!

And ends up leaving the instance in place, unfortunately.

While we could just as easily set allow.user.expunge.recover.vm to "true", we currently depend upon events generated by instance deletion and would thus prefer the ability to disable the forced expunge.

Cloudstack 4.8
Packer 1.0.2 running on Mac OSX 10.12.5 creating a CentOS 7 instance

Thanks!

P.S. - Yes Matt - it's THAT Ian again. :)

**Comment by IanTheIan** [comment]
I suppose I should note that it indicated that the instance was deleted, when, in fact, it was unable to do so.  That would indicate a minor bug, no?

**Comment by svanharmelen** [comment]
@IanTheIan we can certainly make the `expunge` operation optional. Will have a look at that...

About the bug, I guess you're referring to the logline: `cloudstack: Instance has been deleted!` Right? I will update the code a bit so it doesn't show that when it's not actually destroyed. Thanks!

**Comment by rickard-von-essen** [comment]
It should really delete the VM if there is an error (if possible).

**Comment by svanharmelen** [comment]
@rickard-von-essen how do you mean? The expunge option is only used when destroying the instance. So that means in this case the reported error is generated when we are in the Cleanup func and are in fact trying to cleanup the instance...

**Comment by rickard-von-essen** [comment]
If deleting the instance fails because expunge is not allowed I think the proper thing is to retry without expunge. To ensure that it's cleaned up (at least eventually).

**Comment by svanharmelen** [comment]
Well... I don't think I fully agree... Certainly not after we merge PR #5099 :wink:

After that PR is merged the default will be to destroy without expunge, so if you as a user then configure that you want to expunge I think it's very appropriate to give an error if that fails and not decide to silently try to destroy it without expunging instead.

I did also update the logging so it will clearly show it if the instance was not destroyed and manual actions are needed.

**Comment by rickard-von-essen** [comment]
IMHO clean up should "never" fail. But loging a big warning that it didn't work as inteded is greate. Is it possible to check if you are allowed to use expunge at the start of the build and stop before doing anything that would be the optimal solution.

**Comment by svanharmelen** [comment]
No, unfortunately not... 

And I get what you're saying about the cleanup func. It should indeed never fail. But I'm also not a fan of doing things that the user isn't expecting. So when expunge becomes something that a user has to actively configure/set, I think the best thing to do is to fail and log when we cannot do what the user told us to do.

**Comment by svanharmelen** [comment]
@rickard-von-essen so are you good with this (and so with PR #5099)?

**Comment by rickard-von-essen** [comment]
Seems like you can do this in two different steps:

1) Delete VM whithout expunge, should never fail.
2) If `expunge` is `true` also expunge it with [`ExpungeVirtualMachine`](https://github.com/xanzy/go-cloudstack/blob/master/cloudstack/VirtualMachineService.go#L4598), might fail and then it's fine to log that it didn't exunge the VM most likely a premission issue.

**Comment by svanharmelen** [comment]
True... Maybe I'm just being stubborn 😏  I'll update the PR accordingly...
