### ISSUE TITLE
Packer hangs on CentOS 7.3

### ISSUE THREAD

**Issue by DanielMarquard** [hashicorp/packer#5113]
I can't seem to get any leads on troubleshooting why Packer 1.0.2 hangs on CentOS 7.3. There is no output of any kind in the console, and nothing in `/var/log/messages`. Temporarily disabling SELinux did not change this behavior.

If I run `packer version`, Packer hangs and nothing is output in the console. This is the same behavior for both `packer validate` and `packer build`. Running Packer with `PACKER_LOG=1` also outputs nothing.

I wish I had more information to provide on the issue, but all I can say is that it's simply not working.

**Comment by DanielMarquard** [comment]
After installing with `go`, that binary seems to work. So that I can avoid having to use Go to install Packer, what are the dependencies that might have caused the pre-compiled binary to hang?

**Comment by lfarnell** [comment]
How did you build the go binary? With the makefile or go build?

**Comment by DanielMarquard** [comment]
I used `go get github.com/hashicorp/packer`

**Comment by rickard-von-essen** [comment]
https://www.packer.io/intro/getting-started/install.html#troubleshooting

You have another tool on the path called `packer`. (`which -a packer`)
