### ISSUE TITLE
Feature request: Return AMI id

### ISSUE THREAD

**Issue by simoneroselli** [hashicorp/packer#5117]
Hi,

It would be useful to have a usable reference of the new created AMIs.
I list some options I would like to have available out-of-the-box:

 1. Output the AMI id, so that this can be used from within the build.json itself.
 2. Write the AMI id into a text file.
 3. Write the AMI id into a file, formatted as usable Terraform var file.
 
 4. When "copy the AMI over a list of regions" is used, return a map:
  "region1": "ami-idxxx"
  "region2": "ami-idyyy"

**Comment by rickard-von-essen** [comment]
This is already implemented, see https://www.packer.io/docs/post-processors/manifest.html

**Comment by simoneroselli** [comment]
Perfect. Thanks.

**Comment by akomakom** [comment]
@rickard-von-essen : any suggestions for the Azure builder?  artifact_id is blank...

```json
   {
      "name": "azure-arm",
      "builder_type": "azure-arm",
      "build_time": 1538052650,
      "files": null,
      "artifact_id": "",
      "packer_run_uuid": "2c711ee4-6548-7a81-6a98-2120c99d43cb"
    }

```

**Comment by rickard-von-essen** [comment]
@akomakom open a new issue.
