### ISSUE TITLE
A URL required to programmatically obtain latest Packer

### ISSUE THREAD

**Issue by alexharv074** [hashicorp/packer#5120]
In order to programmatically obtain the latest Packer, as opposed to a specific version of Packer, it would be very useful to have a URL that always redirects to the latest Packer for a specific platform.

For example:

https://releases.hashicorp.com/packer/latest/packer_latest_linux_amd64.zip which could redirect to a URL with a version in the filename.

This appears to have been the original requirement in https://github.com/hashicorp/packer/issues/134 which is now closed.

**Comment by lfarnell** [comment]
Let's invite @sethvargo into the conversation. If it's not possible on HashiCorps side, I could build a simple tool around getting the lastest zip for any HashiCorp project.

**Comment by sethvargo** [comment]
https://github.com/hashicorp/terraform/issues/9803#issuecomment-257903082

**Comment by lfarnell** [comment]
thanks @sethvargo! I had no idea about the API. Going to have a look at it :smile:

**Comment by alexharv074** [comment]
Totally disagree.

It is like saying, "yum update should not be allowed to exist because that would make it too easy to get the latest versions of software".

At some points in the CI/CD pipeline, infrastructure code should be versioned; at other points, it should not. It is completely normal, in the development phase of the infrastructure, to always fetch the latest version of everything. Then, at some point, a versioned snapshot of components is promoted to a release candidate, tested and released.

My use-case for fetching the latest version is entirely valid, thank you very much.

**Comment by sethvargo** [comment]
Hi @alexharv074 

You're happy to disagree, but we are not going to add a "latest" endpoint. That information is available via checkpoint and the hashicorp releases service, but it's likely not a pattern we will ever encourage. Users who understand the tradeoffs are more than welcome to use the APIs to build an automated tool, but we will continue to recommend that you lock to a specific version and upgrade to a new, specific locked version.

**Comment by alexharv074** [comment]
The latest (Linux) version can be obtained using:

```
$ current_version=$(curl -s https://checkpoint-api.hashicorp.com/v1/check/packer | jq -r .current_version)
$ wget https://releases.hashicorp.com/packer/${current_version}/packer_${current_version}_linux_amd64.zip
```
