### ISSUE TITLE
cloudstack: Support for Security Groups 

### ISSUE THREAD

**Issue by rickard-von-essen** [hashicorp/packer#5128]
Add support for SGs (_Security Groups_) as a alternative to _Firewall Rules_ and _Port forwarding_.

**Comment by rickard-von-essen** [comment]
@svanharmelen I'll work on this but if you have taught about this please add your thoughts here.

**Comment by svanharmelen** [comment]
Sounds good 👍  Didn't have much thoughts on this, but I guess you would still need a _Port Forward_ if your building from outside the CloudStack environment (e.g. from your laptop).

**Comment by rickard-von-essen** [comment]
I'm using https://exoscle.ch and there the "instance" IP is public and I could build if I commented out everything regarding firewall and port forward setup synd at the same time manually adding a SG permitting port 22.

I think I'll add some options, something like `use_port_forwarding`, `use_firewall`, and set the default to true.

**Comment by svanharmelen** [comment]
I would go the other way around... So if a security group is given do not use a firewall/port forward but only use the security group.

**Comment by rickard-von-essen** [comment]
This was added in #5175
