### ISSUE TITLE
cloudstack: sets encrypted password as password

### ISSUE THREAD

**Issue by rickard-von-essen** [hashicorp/packer#5138]
I haven't verified this, but from reading the API and this code:

```go
	// Set the auto generated password if a password was not explicitly configured.
	switch config.Comm.Type {
	case "ssh":
		if config.Comm.SSHPassword == "" {
			config.Comm.SSHPassword = instance.Password
		}
	case "winrm":
		if config.Comm.WinRMPassword == "" {
			config.Comm.WinRMPassword = instance.Password
		}
	}
```
https://github.com/hashicorp/packer/blob/master/builder/cloudstack/step_create_instance.go#L122

It seems like we are setting the _encrypted_ password as a plain text password. @svanharmelen do you agree with that analysis? Or can you verify it?

**Comment by rickard-von-essen** [comment]
I'm doing some enhancements for CS so I can fix it. (I'll remove it for SSH but I'll have to fix it for WinRM)

**Comment by svanharmelen** [comment]
@rickard-von-essen not sure if I understand you correctly, but the password that is returned from the `client.VirtualMachine.DeployVirtualMachine` call is a plain text password. We use the current code quite a lot without issues, so not sure what you would want to change?

**Comment by rickard-von-essen** [comment]
Oh missed that `deployVM password` is plain text but `getVMPassword` is encrypted.
