### ISSUE TITLE
Freeze on packer 1.0.3 with ansible remote

### ISSUE THREAD

**Issue by luqasz** [hashicorp/packer#5142]
Packer 1.0.3 (works on 1.0.2) freezes when using ansible-remote and `template` module.  Other tasks like removing files work. I suppose it has to do with `sftp` and/or `scp`.

[packer log](https://gist.github.com/luqasz/6bd221577428a894990ecab055bb0cd5)
[ansible playbook](https://gist.github.com/luqasz/aa89277b67ca0dbfb3180c815fa83d01)
[packer tamplate](https://gist.github.com/luqasz/648e99925afa050661425d9456b0c542)

This issue refers to #3302. I strongly suggest to remove / disable any kind of ssh proxying since it can cause problems and it does not add any value nor solves any problems. As you can see it can cause problems. Just leave ssh connection to provisioner.

**Comment by rickard-von-essen** [comment]
> This issue refers to #3302. I strongly suggest to remove / disable any kind of ssh proxying since it can cause problems and it does not add any value nor solves any problems. As you can see it can cause problems. Just leave ssh connection to provisioner.

Seems like FUD, we have exactly 0 commits on `ansible` between 1.0.2 and 1.0.3 the only is even remotely interesting for this report is a concurrency fix for SSH.

**Comment by SwampDragons** [comment]
Actually, @rickard-von-essen I can replicate.  The change that fixed the SSH bug involved modification to the communicator, not ssh-specific.  I'll take a look at this tomorrow.

**Comment by giorgio-v** [comment]
I’m seeing the same problem. 

I have update to 1.0.3 (see https://github.com/hashicorp/packer/issues/5143) but rolled back to 1.0.2. In other words, with one template I have to 1.0.3 and with the others, that use Ansible, I have to use 1.0.2.

**Comment by rickard-von-essen** [comment]
@SwampDragons didn't say it wasn't a real bug just that it's jumping to conclusions to trying to blame the proxy (again). 

It would be interesting to see how this can be replicated outside of ansible.

**Comment by shaharmor** [comment]
Same issue here

**Comment by lo** [comment]
Same issue here

**Comment by lobsterdore** [comment]
I can confirm that I am seeing the exact same issue, a roll back to 1.0.2 has fixed the bug for me.

**Comment by edmundcraske** [comment]
I'm also seeing this - I spent a while trying to debug it before realising that it could be packer's ssh proxying - it appears to be incorrectly either prematurely terminating, or holding open, the ssh session - and having downgraded to 1.0.2 it's back to normal.

**Comment by edmundcraske** [comment]
Seems most likely that #5089 is the cause of this, unless anyone thinks otherwise?

**Comment by rickard-von-essen** [comment]
It would be awesome if someone could try with a build from master with #5089 reverted. And also relevant parts from a packer log (`PACKER_LOG=1`) when reproducing this and using `"extra_arguments": [ "-vvvv" ]`.

**Comment by SwampDragons** [comment]
@rickard-von-essen Ansible stops hanging and will return just with https://github.com/hashicorp/packer/blob/ba3d4c8cd28c50e05fe6cff070642ef65346b720/packer/rpc/communicator.go#L74

I'm currently trying to verify that it completely resolves the issue.

**Comment by SwampDragons** [comment]
Just linked the patch -- if I can get independent verification that it fixes your builds, I'll merge now.

**Comment by edmundcraske** [comment]
That works for me! 😃

**Comment by SwampDragons** [comment]
@edmundcraske excellent.  I'll merge now so y'all can patch at will.
