### ISSUE TITLE
vmware-iso remote_type esx5 no space left on device

### ISSUE THREAD

**Issue by hmalinov** [hashicorp/packer#5145]
Packer v1.0.3

I am trying to build an vmware image using type vmware-iso on a remote ESXi 5.5. server.
However the image is 4 GB

```
du -hs packer_cache/8e6a7dd179c447e03e17d47d9040cc5d449a34ede08e64a60e2d53dbd894fdb9.iso 
4.1G	packer_cache/8e6a7dd179c447e03e17d47d9040cc5d449a34ede08e64a60e2d53dbd894fdb9.iso
```

and during the upload to the remote server I am getting the error:

```./packer build centos73.json 
vmware-iso output will be in this color.

Warnings for build 'vmware-iso':

* A shutdown_command was not specified. Without a shutdown command, Packer
will forcibly halt the virtual machine, which may result in data loss.

==> vmware-iso: Downloading or copying ISO
    vmware-iso: Downloading or copying: http://mirrors.sonic.net/centos/7.3.1611/isos/x86_64/CentOS-7-x86_64-DVD-1611.iso
==> vmware-iso: Uploading ISO to remote machine...
==> vmware-iso: Error uploading file: write /tmp/packer-upload907504958: no space left on device
==> vmware-iso: Deleting output directory...
Build 'vmware-iso' errored: Error uploading file: write /tmp/packer-upload907504958: no space left on device

==> Some builds didn't complete successfully and had errors:
--> vmware-iso: Error uploading file: write /tmp/packer-upload907504958: no space left on device

==> Builds finished but no artifacts were created.
```

I checked the environment variable TMPDIR but it seems it is only used on the local server.
Is there a way to specify the upload path for the ISO image ?

**Comment by rickard-von-essen** [comment]
I think this _is_ on the local machine. Try adjusting `TMPDIR` to somewhere you have more space, such as your home directory etc.

**Comment by hmalinov** [comment]
Actually that worked.  Thanks a lot. 

And I think the error message can still be improved to not mislead the newbies like me. 
Also the TMPDIR can be included in the vmware-iso documentation https://www.packer.io/docs/builders/vmware-iso.html

**Comment by rickard-von-essen** [comment]
The `TMPDIR` environment variable is documented [here](https://www.packer.io/docs/other/environment-variables.html#tmpdir). 

Maybe the error message can be made a bit more clear, but in all other cases except building on ESXi it's obviously local.

**Comment by SwampDragons** [comment]
Do you have a recommendation for a specific way the error could be phrased that would have helped you?

**Comment by hmalinov** [comment]
The error appeared during the action of "vmware-iso: Uploading ISO to remote machine" and it was logical for me to believe it is the remote server problem.

It would help if the error says that it is on the localhost or output the hostname . It would be nice that the error also refer to the TMPDIR solution as it took me a lot of time to find it out.

Thank you.
