### ISSUE TITLE
Ansible provisioner cow output is trimmed left

### ISSUE THREAD

**Issue by mattwwarren** [hashicorp/packer#5147]
- Packer version: 1.0.2
- Host platform: Amazon EC2
- Debug log output and example scripts: https://gist.github.com/mattwwarren/7e0bae85fdecfd8a5c7ed7e96cbfb8b9
  
In the ansible provision step, you will notice the cowsay output, the mouth, legs and underside of the cow is offset by two characters from the first lines. I haven't dug in to find the cause of this issue but I suspect there is a stdout redirection that trims leading whitespace.

**Comment by mwhooker** [comment]
can reproduce this with the shell provisioner, too, so I don't think it's related to ansible
