### ISSUE TITLE
packer build -only does not support comma separated names as documented

### ISSUE THREAD

**Issue by ghostsquad** [hashicorp/packer#5153]
# Description

`packer build -only=foo,bar,baz` as described in the documentation does not work.

### Expected Behavior

Packer builds only builders named `foo`, `bar`, and `baz`

### Actual Behavior

An error is raised
```
2017/07/20 15:10:27 ui error: '' expected a map, got 'slice'
'' expected a map, got 'slice'
```

### Workaround

`packer build -only=foo -only=bar -only=baz`

### Additional Information

- Packer version `1.0.3`
- Host OSX `10.12.5`

Documentation for this command line argument:
https://www.packer.io/docs/commands/build.html#only-foo-bar-baz

Found that the test for this command line option does not test the use case that is documented (which is how I figured out the workaround):
https://github.com/hashicorp/packer/blob/master/command/build_test.go#L70

**Comment by rickard-von-essen** [comment]
I can't repro this. Can you double check your env etc. Gist a packer log (`PACKER_LOG=1 packer build -only=foo,bar template.json`) too.

**Comment by ghostsquad** [comment]
@rickard-von-essen I'm so sorry. I found the problem. It was later on, where the provisioners in our file were defined.

It was:
```
"base-xenial": [
            "KITCHEN_REV={{user `kitchen_rev`}}",
            "CHEF_ENV={{user `chef_env`}}",
            "CHEF_RUNLIST={{user `chef_runlist`}}",
            "APP_REV={{user `app_rev`}}",
            "CHEF_VERSION={{user `chef_version`}}"
          ]
```

should be:
```
"base-xenial": {
          "environment_vars": [
            "KITCHEN_REV={{user `kitchen_rev`}}",
            "CHEF_ENV={{user `chef_env`}}",
            "CHEF_RUNLIST={{user `chef_runlist`}}",
            "APP_REV={{user `app_rev`}}",
            "CHEF_VERSION={{user `chef_version`}}"
          ]
        },
```

Strangely, I now can't figure out how I got it working with the described workaround.
