### ISSUE TITLE
Waiting for SSh/winrm to become available

### ISSUE THREAD

**Issue by inesEl** [hashicorp/packer#5158]
Hi,

I am using packer with the Hyper V builder to make a windows 2008 R2 VM.
The steps go fine, the VM works correctly and everything is set as it should be.
**The only problem is**, the script hangs in that **==> hyperv-iso: Waiting for WinRM to become available...** or **==> hyperv-iso: Waiting for SSH to become available...**
I tried with both WinRM and SSH and both have the same result. Here is what I did for troubleshooting:

1/ Once the VM is up and ready, connect to the VM
2/ Get the IP (ipconfig)
3/ ssh to the VM from my host machine using putty or regular git bash console or check WinRM works (Test-WSMan)
4/ For SSH:
    a) Service started and running on the VM
    b) I am able to ssh to the VM from my host VM
    For WinRM:
      Test-WSMan return a correct result
5/ Try on another machine (both are windows 10)
Even if everything seem to be set correctly, for some reason, something is keeping packer from noticing that the services are available. I searched everywhere, I tried the debug but no more information has been displayed. I am stuck here, any help would be appreciated @mitchellh .

![packer_console](https://user-images.githubusercontent.com/11720360/28472293-ec043a32-6e37-11e7-9ead-98a82c6b3cfd.png)

![vm_running](https://user-images.githubusercontent.com/11720360/28472296-eebd5f4c-6e37-11e7-8d04-fde4e3a55076.png)

![winrm_working](https://user-images.githubusercontent.com/11720360/28472298-f0e9a14a-6e37-11e7-97c5-e3564535ade4.png)

Thank you!

Ines E.

**Comment by rickard-von-essen** [comment]
Please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._

---

In generall you should use WinRM for building a Windows guest and you need to have the HyperV guest tools install to properly detect the IP.
