### ISSUE TITLE
Virtual switch is set to internal in Hyper V builder

### ISSUE THREAD

**Issue by inesEl** [hashicorp/packer#5159]
Hi,

In order for the provisioning to work on a Hyper V VM set by packer, the VM needs to have internet access so it can download the tools and everything it needs from the internet. In order to do that,  the virtual switch in hyper V needs to be set as External.
Trying to see with the documentation, I didn't find how to configure it to be external so I checked the source code and indeed, only tow options are supported which are:
1/ internal (default)
2/ private
Could you please integrate this feature ? Is there a workaround I can use for now (I really would rather not to have to create the switch manually before launching packer)

Thank you very much.

Ines E.

**Comment by taliesins** [comment]
@inesEl you are not required to have an internet connection to spin up guests. It just makes your life easier when writing provisioning scripts.

I believe setting up internet access/dhcp is a pre requisite for other hypervisors as well. It doesn't make sense to be provisioning this infrastructure during a machines spin up. Vms could all use the same external switch. This is the setup I use.

If you were spinning up environments then I would use Terraform. I am working on adding hyperv support. https://github.com/taliesins/terraform/blob/HyperVProvider/builtin/providers/hyperv/api_vm.go
