### ISSUE TITLE
What is a BSD or GNU style checksum file?

### ISSUE THREAD

**Issue by sandersaares** [hashicorp/packer#5168]
From the documentation:

> iso_checksum_url (string) - A URL to a GNU or BSD style checksum file containing a checksum for the OS ISO file.

I have no idea what these checksum file styles refer to. Google ends me up at [BSD checksum](https://en.wikipedia.org/wiki/BSD_checksum) but that can't be right.

I request clarification to this documentation. Inline examples or references to examples would be nice.

**Comment by rickard-von-essen** [comment]
BSD's implementation of `md5` will output:

```
MD5 (other.iso) = <checksum>
MD5 (the-OS.iso) = <checksum>
```

While the GNU implementation of `md5sum` will output:

```
<checksum> *the-OS.iso
<checksum>  other.iso
```
