### ISSUE TITLE
OSX & 1.0.3 fails with Ansible provisioner, ssh auth related?

### ISSUE THREAD

**Issue by mzeier** [hashicorp/packer#5171]
Using the Ansible provisioner on OSX in 1.0.3 fails (or hangs) at "Gathering Facts". Downgrading to 1.0.2 works. 

Debug logging appears to suggest it's failing at connecting through the proxy:

```
2017/07/25 12:58:48 packer: 2017/07/25 12:58:48 authentication attempt from 127.0.0.1:53210 to 127.0.0.1:53209 as mrz using publickey
2017/07/25 12:58:48 packer: 2017/07/25 12:58:48 authentication attempt from 127.0.0.1:53210 to 127.0.0.1:53209 as mrz using publickey
2017/07/25 12:58:48 packer: 2017/07/25 12:58:48 rejecting auth-agent-req@openssh.com request
```

Logging gist @ https://gist.github.com/mzeier/5fd5974425b1acd51cbb914470302ae5

Packer snippet @ https://gist.github.com/mzeier/03a8488cc6467ee0a0761f28b2460b5c

**Comment by rickard-von-essen** [comment]
Thanks for reporting this. This is a duplicate of #5142, which have been fixed on master. The fix will be included in the next release.

In the mean time you can either build from master or revert to 1.0.2.
