### ISSUE TITLE
Do not include query string in matching for ISO checksum URL

### ISSUE THREAD

**Issue by sandersaares** [hashicorp/packer#5176]
Scenario: my ISO URL has a query string at the end, for authorization purposes. e.g. `foo.iso?bar=baz`

Packer currently appears to expect this query string to also be present in the checksum file provided by `iso_checksum_url`. This does not work for me, as the thing generating the checksum file has no knowledge of the URL query strings - it generates the checksum files before any such publishing.

I therefore request that Packer be amended to ignore the query string when matching ISO names against the checksum file. That is, the URL `foo.iso?bar=baz` should match for `foo.iso` in the checksum file.

**Comment by rickard-von-essen** [comment]
We need to parse the URL and use `URL.Path` [here] (https://github.com/hashicorp/packer/blob/master/common/iso_config.go#L151).

**Comment by rickard-von-essen** [comment]
46727f7 adds a test for this, but no code yet.

**Comment by rickard-von-essen** [comment]
See #5181
