### ISSUE TITLE
DigitalOcean Error creating temporary SSH key

### ISSUE THREAD

**Issue by mvatansever** [hashicorp/packer#5177]
Hi everyone,

I want to build a machine at DigitalOcean and created a configuration file to do that.  It validates successfully but it does not do build. I didn't found any solution for this error. It's seen as a JSON validation exception but not exists any error when I validate the JSON.

- Packer version: 1.0.2
- Host platform: DigitalOcean
- Debug log output from "PACKER_LOG=1 packer build -var 'do_api_token=`echo $DIGITAL_OCEAN_TOKEN`' debian.json" is here: https://gist.github.com/mvatansever/00e0e0738de0dc52b33ec4d2a98b8d36
- My build script is here : https://gist.github.com/mvatansever/496e1c629b13745353eb408922364504

Note: "DIGITAL_OCEAN_TOKEN" environment variable I load from a script with "source" Linux command like this: "source mytoken" then try to execute packer build.

**Comment by rickard-von-essen** [comment]
Pretty sure that the image slug shouldn't contain a slash. Check the docs for a working example.
