### ISSUE TITLE
ec2-upload-bundle failing when root as a ssh_username

### ISSUE THREAD

**Issue by michalswi** [hashicorp/packer#5182]
HOST PACKER VERSION: 1.0.3
HOST PLATFORM: Ubuntu 16.04.2 LTS
DESTINATION PLATFORM: CentOS Linux release 7.3.1611 (Core)

For builders/amazon-instance if you specify in jsonfile:
_"ssh_username" : "root"_

then running 'packer build' fails on this step:
_==> amazon-instance: Running: sudo -i -n ec2-bundle-vol -k /tmp/key.pem -u ... -c /tmp/cert.pem -r x86_64 -e /tmp/* -d /tmp -p image-... --batch --no-filter
    amazon-instance: -bash: ec2-bundle-vol: command not found_

If you log in to the instance and run it manually then:
_# sudo -i -n ec2-bundle-vol -k /tmp/key.pem -u ... -c /tmp/cert.pem -r x86_64 -e /tmp/* -d /tmp -p image-... --batch --no-filter
sudo: ec2-bundle-vol: command not found_

Without sudo it works fine, no errors.

I suggest to divide ssh_username for root and other users. It's hardcoded in:
**./builder/amazon/instance/builder.go**    ->    _b.config.BundleUploadCommand = "sudo -i -n ec2-upload-bundle "_

**Comment by mwhooker** [comment]
it looks like maybe your PATH is not correctly set up, since sudo doesn't seem to be able t find that command.

I think the correct solution for you is to override the bundle command. Please see https://www.packer.io/docs/builders/amazon-instance.html#custom-bundle-commands for more informaiton.

If you're still having problems getting it to work, I would suggest reaching out to the [mailing list](https://groups.google.com/forum/#!forum/packer-tool), since more users read that than the github issues.

**Comment by michalswi** [comment]
Just to show that it's not related to PATH. I will find a way to fix it but nevertheless running _sudo_ on root user doesn't make sens (please don't consider prompt for root user -> $).

```sh
# user check
$ whoami
root
$ id
uid=0(root) gid=0(root) groups=0(root)

# binaries check
$ whereis ec2-bundle-vol
ec2-bundle-vol: /usr/local/bin/ec2-bundle-vol
$ sudo whereis ec2-bundle-vol
ec2-bundle-vol: /usr/local/bin/ec2-bundle-vol

# PATH check
$ echo $RUBYLIB
:/usr/lib/ruby/site_ruby:/usr/lib64/ruby/site_ruby
$ sudo echo $RUBYLIB
:/usr/lib/ruby/site_ruby:/usr/lib64/ruby/site_ruby

# ec2-bundle-vol check
$ ec2-bundle-vol
missing mandatory parameter: --cert
Try 'ec2-bundle-vol --help'
$ sudo ec2-bundle-vol
sudo: ec2-bundle-vol: command not found
```

**Comment by rickard-von-essen** [comment]
That is a misconfiguration of your sudo or profile etc. There is nothing wrong with running sudo as root. And the solution is there link above.
