### ISSUE TITLE
Shell provisioner execute_command sudo example quoting

### ISSUE THREAD

**Issue by ksperling** [hashicorp/packer#5191]
The documentation gives the following example for using sudo via  execute_command:

    execute_command="echo 'packer' | sudo -S sh -c '{{ .Vars }} {{ .Path }}'"

However wrapping `{{.Vars}}` in single quotes in that way breaks if any variables contain spaces or single quotes as an additional level of quoting would be required.

The following command works around this by passing `{{.Vars}}` in a way that does not require additional quoting by using `env`:

    execute_command="echo 'packer' | sudo -S env {{ .Vars }} {{ .Path }}"

**Comment by mwhooker** [comment]
Unfortunately the second invocation breaks compatibility with buggy scripts (see #5043), and we haven't been willing to do that quite yet. Maybe it's time to revisit.

**Comment by ksperling** [comment]
I was just thinking of this as a documentation change rather than a code change.

**Comment by mwhooker** [comment]
yeah adding it to the docs might be good. You'll see we already have an `env` example for bsd: https://www.packer.io/docs/provisioners/shell.html#freebsd-example

Maybe adding `execute_command="echo 'packer' | sudo -S env {{ .Vars }} {{ .Path }}"` as a second choice in the [sudo example](https://www.packer.io/docs/provisioners/shell.html#sudo-example) would be good
