### ISSUE TITLE
Packer does not seems to accept var files with array values

### ISSUE THREAD

**Issue by maxenglander** [hashicorp/packer#5194]
Currently, Packer does not seems to accept `-var-file` with array values. E.g.

```terminal
$ cat /tmp/vars.json
{
  "aws_azs": [
      "us-east-1a",
      "us-east-1b"
  ]
}

$ packer -var-file=/tmp/vars.json /tmp/build.json
invalid value "/tmp/vars.json" for flag -var-file: Error reading variables in '/tmp/vars.json': json: cannot unmarshal array into Go value of type string
```

I am aware that I can flatten these arrays into strings, and Packer will happily accept them. However, I am using the same configuration files to power both my Packer and Terraform builds, and would like to retain the ability to supply array-based var files to Terraform.

Would the Packer team be open to a PR that added any of the following?
  * Ignore array values
  * Flatten array values
  * Maintain current behavior, but allow enabling one of above behaviors with a flag, e.g. `-var-file-array-behavior=[error(default),flatten,ignore]`

**Comment by mwhooker** [comment]
hi @maxenglander 

thanks for the report. I can definitely see wanting to use the same var file between tf and packer. I think I'd be willing to merge a backwards-compatibility maintaining patch, but my gut tells me that it will be tough.

I don't want to promise something with no timeline, but I will say that we're looking into getting packer's config more in line with terraform. This would probably be a major rewrite and likely any work you do here will be lost. It might be best just to wait for that, and in the meantime perhaps use a short script to flatten the arrays for packer.

If you did want to submit a patch, then I'm thinking ignoring array values would be the best solution

**Comment by maxenglander** [comment]
Thanks for the response @mwhooker! I'm using flattener now, and can wait till the rewrite for a better solution.

**Comment by OneBadSanta** [comment]
@mwhooker I am also in need of this feature. Any updates?

@maxenglander Would you be so kind to share the flattener script?

Thank you so much
