### ISSUE TITLE
Packer unexpectedly appends data to downloaded ISO and thereby corrupts it

### ISSUE THREAD

**Issue by sandersaares** [hashicorp/packer#5198]
I am building a Hyper-V image using the following Windows 2016 ISO: `https://asdp.blob.core.windows.net/cb-static/windows2016-setupiso.iso?st=2017-07-27T01%3A21%3A00Z&se=2027-07-28T01%3A21%3A00Z&sp=rl&sv=2016-05-31&sr=b&sig=HwgpkNFwNfehdsy2SJ3fa17%2Bgd3cOjXxQSHRRTnk4JU%3D`

I am not using a checksum (`iso_checksum_type=none`). As the error occurs early on in the build process (at image download), I do not believe there is any special dependency on the template, beyond the ISO URL.

Expected behavior: Packer downloads the ISO and uses it without any funny business. If already downloaded into Packer cache, ISO is reused.

Actual behavior:

* On first build, actual behavior matches expected behavior - the ISO is downloaded and successfully used.
* On second build, ISO is corrupted by appending the body of what appears to be an error message from the HTTP server.
* On each consecutive build, another HTTP error response body is appended.

Hyper-V error is: 

```
Synthetic SCSI Controller (Instance ID A6E84880-07F9-4902-B6A7-2279E0F4CC62): Failed to Power on with Error 'The file or directory is corrupted and unreadable.'.
```

Exploration of the ISO file in Packer cache directory reveals that some unexpected data has been appended to the previously downloaded ISO. The appended data is:

```
<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidRange</Code><Message>The range specified is invalid for the current size of the resource.
RequestId:6642a3d0-0001-0048-1cc0-0a5846000000
Time:2017-08-01T12:17:48.8818481Z</Message></Error>
```

This appending of an apparent error response is repeated on every attempted build.

Packer log does not appear to contain anything unusual for either of the download attempts, just the basics as listed here:

```
2017/08/01 15:17:47 ui: ==> Windows2016-HyperV: Downloading or copying ISO
2017/08/01 15:17:47 ui:     Windows2016-HyperV: Downloading or copying: https://asdp.blob.core.windows.net/cb-static/windows2016-setupiso.iso?st=2017-07-27T01%3A21%3A00Z&se=2027-07-28T01%3A21%3A00Z&sp=rl&sv=2016-05-31&sr=b&sig=HwgpkNFwNfehdsy2SJ3fa17%2Bgd3cOjXxQSHRRTnk4JU%3D
2017/08/01 15:17:47 packer.exe: 2017/08/01 15:17:47 Acquiring lock to download: https://asdp.blob.core.windows.net/cb-static/windows2016-setupiso.iso?st=2017-07-27T01%3A21%3A00Z&se=2027-07-28T01%3A21%3A00Z&sp=rl&sv=2016-05-31&sr=b&sig=HwgpkNFwNfehdsy2SJ3fa17%2Bgd3cOjXxQSHRRTnk4JU%3D
2017/08/01 15:17:47 packer.exe: 2017/08/01 15:17:47 Parsed URL: &url.URL{Scheme:"https", Opaque:"", User:(*url.Userinfo)(nil), Host:"asdp.blob.core.windows.net", Path:"/cb-static/windows2016-setupiso.iso", RawPath:"", ForceQuery:false, RawQuery:"st=2017-07-27T01%3A21%3A00Z&se=2027-07-28T01%3A21%3A00Z&sp=rl&sv=2016-05-31&sr=b&sig=HwgpkNFwNfehdsy2SJ3fa17%2Bgd3cOjXxQSHRRTnk4JU%3D", Fragment:""}
2017/08/01 15:17:47 packer.exe: 2017/08/01 15:17:47 [DEBUG] Downloading: https://asdp.blob.core.windows.net/cb-static/windows2016-setupiso.iso?st=2017-07-27T01%3A21%3A00Z&se=2027-07-28T01%3A21%3A00Z&sp=rl&sv=2016-05-31&sr=b&sig=HwgpkNFwNfehdsy2SJ3fa17%2Bgd3cOjXxQSHRRTnk4JU%3D
2017/08/01 15:17:47 packer.exe: 2017/08/01 15:17:47 Starting download: https://asdp.blob.core.windows.net/cb-static/windows2016-setupiso.iso?st=2017-07-27T01%3A21%3A00Z&se=2027-07-28T01%3A21%3A00Z&sp=rl&sv=2016-05-31&sr=b&sig=HwgpkNFwNfehdsy2SJ3fa17%2Bgd3cOjXxQSHRRTnk4JU%3D 
```

I see the following HTTP requests made on the 2nd build attempt:

```
HEAD https://asdp.blob.core.windows.net/cb-static/windows2016-setupiso.iso?st=2017-07-27T01%3A21%3A00Z&se=2027-07-28T01%3A21%3A00Z&sp=rl&sv=2016-05-31&sr=b&sig=HwgpkNFwNfehdsy2SJ3fa17%2Bgd3cOjXxQSHRRTnk4JU%3D HTTP/1.1
Host: asdp.blob.core.windows.net
User-Agent: Packer


HTTP/1.1 200 OK
Content-Length: 8123633664
Content-Type: application/octet-stream
Content-MD5: 0b+62sSqhFkLLJjEKjwLzQ==
Last-Modified: Thu, 27 Jul 2017 13:29:45 GMT
Accept-Ranges: bytes
ETag: "0x8D4D4F38C0BDE0A"
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: ac30927f-0001-007a-77c1-0a5831000000
x-ms-version: 2016-05-31
x-ms-lease-status: unlocked
x-ms-lease-state: available
x-ms-blob-type: BlockBlob
x-ms-copy-id: 9f19d7e0-ff6d-4e85-8d7c-59f80a70e20d
x-ms-copy-source: https://asdp.blob.core.windows.net/windows2016-setupiso-cb/windows2016-setupiso-2017-07-27.05.iso?sv=2016-05-31&sr=b&sig=9wD6z3fT4wr97ZhzIgq8vB6mdEueWyDIKPC6LohcBFY%3D&se=2017-08-03T13%3A29%3A45Z&sp=r
x-ms-copy-status: success
x-ms-copy-progress: 8123633664/8123633664
x-ms-copy-completion-time: Thu, 27 Jul 2017 13:29:45 GMT
x-ms-server-encrypted: false
Date: Tue, 01 Aug 2017 12:28:51 GMT
```

```
GET https://asdp.blob.core.windows.net/cb-static/windows2016-setupiso.iso?st=2017-07-27T01%3A21%3A00Z&se=2027-07-28T01%3A21%3A00Z&sp=rl&sv=2016-05-31&sr=b&sig=HwgpkNFwNfehdsy2SJ3fa17%2Bgd3cOjXxQSHRRTnk4JU%3D HTTP/1.1
Host: asdp.blob.core.windows.net
User-Agent: Packer
Range: bytes=8123633664-


HTTP/1.1 416 The range specified is invalid for the current size of the resource.
Content-Length: 249
Content-Type: application/xml
Content-Range: bytes */8123633664
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: ac309288-0001-007a-7bc1-0a5831000000
x-ms-version: 2016-05-31
Date: Tue, 01 Aug 2017 12:28:51 GMT

﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidRange</Code><Message>The range specified is invalid for the current size of the resource.
RequestId:ac309288-0001-007a-7bc1-0a5831000000
Time:2017-08-01T12:28:52.6683368Z</Message></Error>
```

As you can see, Packer attempts to read past the end of the file for some reason, then treats the error as something to append to the ISO (despite the 416 status code).

Using Packer 1.0.3 on Windows 10.

**Comment by rickard-von-essen** [comment]
The problem is here 
https://github.com/hashicorp/packer/blob/master/common/download.go#L253
This is only reached if `checksum_type=none`.

**Comment by mwhooker** [comment]
I feel like we should maybe replace all this code with [go-getter](https://github.com/hashicorp/go-getter)

**Comment by sandersaares** [comment]
I just ran into this again (I guess this is why I delete all my ISOs after each use...).

This remains a painful problem and is still present in master branch.

**Comment by mwhooker** [comment]
Unfortunately I'm not able to reproduce this with the vmware builder

```
{
  "builders": [
    {
        "ssh_username": "foo",
      "iso_checksum_type": "none",
      "iso_url": "https://asdp.blob.core.windows.net/cb-static/windows2016-setupiso.iso?st=2017-07-27T01%3A21%3A00Z&se=2027-07-28T01%3A21%3A00Z&sp=rl&sv=2016-05-31&sr=b&sig=HwgpkNFwNfehdsy2SJ3fa17%2Bgd3cOjXxQSHRRTnk4JU%3D",
      "type": "vmware-iso"
    }
  ]
}
```

Will see if I can reproduce on windows/hyper-v.

I do see that the code looks somewhat buggy. I've attempted a fix at https://github.com/hashicorp/packer/compare/fix5198 but not certain it works until I can reproduce the issue.

**Comment by tylert** [comment]
I have ***not*** observed this behaviour with any of the qemu, virtualbox-iso or vmware-iso builders.  I have been using most versions of Packer up to 1.2.3 on amd64 Linux and macOS.

However, I do make heavy use of ```iso_target_path``` to make sure I get recognizable filenames in ```packer_cache``` in case that should turn out to be important.

**Comment by SwampDragons** [comment]
We changed to a different download mechanism in 2019, so I suspect this issue is no longer relevant to the current code. If anyone experiences something similar with a recent version of Packer, please open a new issue with steps to reproduce. Thanks!
