### ISSUE TITLE
Azure Managed Image Disk Type

### ISSUE THREAD

**Issue by JeremyLoy** [hashicorp/packer#5202]
Azure Provides two types of Disks for Managed Images: [Premium and Standard](https://docs.microsoft.com/en-us/azure/storage/storage-managed-disks-overview#images).

Currently, that functionality is not exposed via the [Packer Builder configuration for Azure](https://www.packer.io/docs/builders/azure.html). A Standard Managed VHD is created by default, and it is not currently possible to make a Premium VHD via Packer.

I recommend that it be an 'Optional' parameter, and continue to default to Standard, as it is the cheaper of the two. It should probably be named `managed_image_disk_type` or something of the like.

**Comment by roman-cnd** [comment]
The builds with standard OS disks are painfully slow.

@boumenot are you planning to add this in any upcoming releases?

**Comment by boumenot** [comment]
I don't control the releases, but @mwhooker or @SwampDragons may be able to comment on when it will ship.  I just merged the change, so it should ship with the next release.

**Comment by mwhooker** [comment]
The next release will be 1.1.0 which will be out early next month

**Comment by roman-cnd** [comment]
Great, many thanks!
