### ISSUE TITLE
Packer not type converting variable type for vnc_port_{min|max}?

### ISSUE THREAD

**Issue by emryszer0** [hashicorp/packer#5209]
I am working to variable-ize the vnc min and max ports for the vmware builder.  Not sure if I am doing something wrong with my syntax, or if this isn't supported.  Couldn't find any documentation on this.  Is this acting as desired?

Error Message: 
* cannot parse 'vnc_port_min' as uint: strconv.ParseUint: parsing "": invalid syntax
* cannot parse 'vnc_port_max' as uint: strconv.ParseUint: parsing "": invalid syntax 

Builder:
```json
  "variables": {
    "min_port" : "{{env `VNC_PORT_MIN`}}",
    "max_port" : "{{env `VNC_PORT_MAX`}}"
  },

  "builders": [
    {
      "name" : "vmware-esxi-rhel7-baseos",
      "vnc_port_min": "{{user `min_port`}}",
      "vnc_port_max": "{{user `max_port`}}",
    },

```

**Comment by mwhooker** [comment]
You need to populate the env vars `VNC_PORT_MAX` and `VNC_PORT_MIN`.

`VNC_PORT_MAX=20000 packer validate 5209.json` etc

see https://www.packer.io/docs/templates/user-variables.html for more information. Let me know if you have additional questions

**Comment by emryszer0** [comment]
Thank you, this ended up being an issue passing variables from outside packer, appreciate the help!!
