### ISSUE TITLE
File upload provisioner should convert line ending to LF while uploading from windows machine

### ISSUE THREAD

**Issue by bishal-pdMSFT** [hashicorp/packer#5212]
When packer is running on windows and is building a *nix VM image, it should change file line endings from CRLF to LF while uploading files. Git client running on windows machine would have converted original LF to CRLF as it has `git config --global core.autocrlf true` option set. But when packer uploads files and does not change line ending, it is going to be problematic when using shell provisioner to execute scripts.

**Comment by rickard-von-essen** [comment]
I think this is bad. To do this Packer would need to keep track of if a file is binary or text. The solution instead is to correctly configure git to not change LF of unix scripts etc.

**Comment by bishal-pdMSFT** [comment]
@rickard-von-essen , while I agree with your objection, it seriously limits users from using Packer on windows machine. It might be very difficult to find all scripts which need to be configured - i guess any file with shebang will have this problem and additionally not every file might have an extension which makes it difficult to use `.gitattributes`
Additionally, by default on windows user might not have set these attributes as they never needed to execute unix scripts on windows. The error thrown by unix when executing file with crlf does not help either.

**Comment by sandersaares** [comment]
I would rather suggest ensuring that line-ending-sensitive files are always checked out from Git using the correct line endings.

For example, to ensure that .sh always use LF, create a .gitattributes file with the following content:

```
*.sh text eol=lf
```

**Comment by rickard-von-essen** [comment]
IMHO there is no reason to use anything else than `core.autocrlf=false` (or `input`).

**Comment by matt-richardson** [comment]
This would cause serious havoc in my builds. Packer should upload byte-for-byte identical files - its the users responsibility to make sure the files have the right line endings.

These days, nearly all windows tools can handle files with unix line endings, so just set your line endings to what you want in your repo.

**Comment by lorengordon** [comment]
Gonna downvote this one also. And I use Windows almost exclusively as a development box. I much prefer to manage the line endings correctly in the repo.

**Comment by taliesins** [comment]
I am gonna down vote this too

**Comment by mwhooker** [comment]
agreed that this isn't something we're interested in doing. Happy to work through some alternate ways to accomplish this without modifying packer, but this doesn't seem like something that packer should be in the business of handling. thanks!
