### ISSUE TITLE
Docker builder + file upload provision fails with empty source directories

### ISSUE THREAD

**Issue by jamesdlevine** [hashicorp/packer#5221]
File upload provisioners using the docker builder will fail without a descriptive error if the source is an empty directory.    

The only error message is "Upload failed with non-zero exit status: 1" in several places. 

The failure behavior itself is problematic because sometimes the directory contents are optional (but the directory is part of a template file tree structure which is pre-existing.)

The error message is problematic because there is no direction on what is wrong or what needs to be fixed.  In my case I spent over an hour poking at all kinds of things, eventually guessing what was going on.    

I don't see any mention of the behavior in the documentation.

The workaround I'm using is to put a placeholder README file in the upload directories in question.

Packer versions: 1.0.3 (also 1.0.0)
Host: Linux (Fedora 25 / EC2)

Please see the debug log and template file - https://gist.github.com/jamesdlevine/6748431f331223ec72304456fd333ee2

Docker version info:
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-common-1.12.6-7.gitae7d637.fc25.x86_64
 Go version:      go1.7.6
 Git commit:      ae7d637/1.12.6
 Built:           Tue Jul 18 16:18:12 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-common-1.12.6-7.gitae7d637.fc25.x86_64
 Go version:      go1.7.6
 Git commit:      ae7d637/1.12.6
 Built:           Tue Jul 18 16:18:12 2017
 OS/Arch:         linux/amd64

Linux info:
Linux 4.10.13-200.fc25.x86_64 #1 SMP Thu Apr 27 20:39:25 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by SwampDragons** [comment]
I think this patch should fix things; I just need to make sure it doesn't have any unintended consequences.  https://github.com/hashicorp/packer/pull/5234

**Comment by SwampDragons** [comment]
Okay, yeah, the code was originally written with a glob `cp -R %s/*` and that was causing issues with dotfiles, which is why it got changed to the current syntax.  But I don't think we need the glob, just the "/" to say "copy all the contents of this directory.  So I think we're good.
