### ISSUE TITLE
Add Support to Disable SSL Verification

### ISSUE THREAD

**Issue by lmayorga1980** [hashicorp/packer#5230]
Terraform does provide a way to skip ssl verification https://www.terraform.io/docs/providers/aws/#insecure and it works. Would it be possible to add the same configuration value for Packer EC2 Builder?

```
amazon-ebs output will be in this color.

==> amazon-ebs: Prevalidating AMI Name...
==> amazon-ebs: Error querying AMI: RequestError: send request failed
==> amazon-ebs: caused by: Post https://ec2.us-east-1.amazonaws.com/: x509: certificate signed by unknown authority
Build 'amazon-ebs' errored: Error querying AMI: RequestError: send request failed
caused by: Post https://ec2.us-east-1.amazonaws.com/: x509: certificate signed by unknown authority

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Error querying AMI: RequestError: send request failed
caused by: Post https://ec2.us-east-1.amazonaws.com/: x509: certificate signed by unknown authority

==> Builds finished but no artifacts were created.
```

**Comment by rickard-von-essen** [comment]
Did you check why you get that?

**Comment by lmayorga1980** [comment]
SSL Hijacking from some other software in the network.

**Comment by mwhooker** [comment]
probably not something we would implement ourselves, but happy to review PRs.

Here's a recent example of how we added this to the atlas-go client https://github.com/hashicorp/atlas-go/pull/57/files

**Comment by lmayorga1980** [comment]
@mwhooker ,

Thank you for the feedback. I will take a look at the reference url and maybe send a PR for this.

**Comment by rickard-von-essen** [comment]
@lmayorga1980 Just a work of advice, if you have some evil firewall that do SSL highjacking (which is a very questionable practice) you really should add its root certificate to all the hosts. Otherwise you are just trusting any https channel regardless of how it was signed.

**Comment by lmayorga1980** [comment]
@rickard-von-essen I agree with you and got packer working by recompiling `golang 1.9rc2`  and `packer`. https://github.com/golang/go/issues/20990
