### ISSUE TITLE
"packer push" overrides variables in atlas as of v1.0.3

### ISSUE THREAD

**Issue by clarkperkins** [hashicorp/packer#5232]
In packer v1.0.2, I could run `packer push template.json` (without `-var` or `-var-file`) and it would just leave all my variables alone in atlas.  However, after upgrading to v1.0.3, `packer push` now overrides the variables set in the template.  This would normally be fine - however when I'm populating a user variable from an environment variable, the variable gets pushed to atlas with an empty value.

Example:
```
{
    "variables": {
        "source_ami": "{{env `ATLAS_BASE_ARTIFACT_AMAZON_IMAGE_ID`}}"
    },
    "builders": [
        {
            "type": "amazon-ebs",
            "ami_name": "my-ami-name",
            "source_ami": "{{user `source_ami`}}",
            "ssh_username": "ubuntu",
            "ssh_pty": true,
            ...
        }
    ],
    ...
}
```

If I have a variable like that defined, I would not expect it to get pushed to atlas.

I think this is a side-effect of #4992.

**Comment by mwhooker** [comment]
Thanks for the report. we'll have to think about the proper behavior here a bit more

**Comment by mwhooker** [comment]
Do you have any thoughts on the behavior you'd like to see? To me the current behavior seems correct. There's no way for us to tell if a variable is supposed to be `""`, or if it just doesn't have a value. It seems like the explicit behavior of this is preferable to the implicit behavior previously, but I'd like to make sure you have a viable solution. 

For example, could you look up the source AMI using an ami filter?

**Comment by clarkperkins** [comment]
Yes, I can lookup the source AMI using a source_ami_filter, and that's likely what I'll switch to doing anyways.  However, if packer push always pushes empty strings for undefined env vars, then you can't really use the "Inject artifact ID during build" feature of atlas.  (well, you could, but every time you push the build would fail b/c of a missing source_ami, so you'd have to go delete the source_ami variable then manually queue a build in the atlas UI)

One potential solution would be to allow usage of the `{{env }}` function throughout the whole template instead of just in the variables.  That way you could just do something like this:

```
{
    "builders": [
        {
            "type": "amazon-ebs",
            "ami_name": "my-ami-name",
            "source_ami": "{{env `ATLAS_BASE_ARTIFACT_AMAZON_IMAGE_ID`}}",
            "ssh_username": "ubuntu",
            "ssh_pty": true,
            ...
        }
    ],
    ...
}
```

and you wouldn't have the issue of having your variable overridden by a push.

**Comment by mwhooker** [comment]
good points, thanks
