### ISSUE TITLE
Provide Illumos/SmartOS (Solaris) binary for download

### ISSUE THREAD

**Issue by pannon** [hashicorp/packer#5241]
All Hashicorp products seem to come with Solaris binaries for download by default - except Packer. 
It would be feasible to make Packer consistent with the other Hashicorp tools and make a Solaris binary build. 

In our case, we use jumphosts on Joyent Triton to run Packer and Terraform.

PS: there was a request back in 2014 about this, see #1217

Thanks.

**Comment by mwhooker** [comment]
can do this with #5248
