### ISSUE TITLE
Ansible-Local Provisioner broken with Docker Builder

### ISSUE THREAD

**Issue by seeraven** [hashicorp/packer#5243]
- Packer version from 1.0.4
- Host platform: amd64

When using ansible-local provisioner with the docker builder, the upload of the files from the playbook_dir goes obviously into a wrong directory and ansible is therefore not able to find roles or other files. It seems to be related to the fix/pull request #5234. The modification changed the upload behaviour from "copy the contents of a directory into another directory" to "copy the directory into another directory". I suggest that was not the intended behaviour, but since it is ensured the target directory exists, "cp" has not other choice. 

Example project is provided at https://gist.github.com/seeraven/a0d4cc746336499090b7c74670f5b73f (note that '/' was replaced in filenames due to gist restrictions).

For testing, I've extended the ansible command to perform a 'ls -Rla' first so to show the directory layout.

The ansible-local provider still works for virtualbox, so it seems to be limited to the docker builder.

**Comment by SwampDragons** [comment]
Thanks for reporting this.  I don't think the problem is the PR you're referencing.  The trailing slash means it should copy the contents of the directory, not the directory itself. Also, it looks like I can repro this bug by building 1.0.2.  Have you been able to get this build working in the past?

**Comment by SwampDragons** [comment]
Hmm.  Still can't get your case working on an older packer, but you were right that something's funky with that PR.  The trailing slash trick only works on OSX, not Linux.  Hooray!  Trying to find a fix that catches all the edge cases that have been bugs in the past.

**Comment by SwampDragons** [comment]
@seeraven Just added a PR #5251  -- can you confirm whether this fixes your issue?

**Comment by seeraven** [comment]
Sorry, had totally forgotten to write that was on Linux, but I've tested the commands on the console and got the idea from there.

Thanks for your pull request! It works when testing on the (Linux) console:
```
$ mkdir src
$ touch src/test
$ touch src/.hidden
$ mkdir dst; command cp -R src/. dst
$ ls -la dst
total 8
drwxrwxr-x 2 u g 4096 Aug 15 08:27 .
drwxrwxr-x 4 u g 4096 Aug 15 08:27 ..
-rw-rw-r-- 1 u g    0 Aug 15 08:27 .hidden
-rw-rw-r-- 1 u g    0 Aug 15 08:27 test
```
I will test with packer as soon as I can. As I have to setup the build environment first that will take a while since I'm quite busy at the moment.

**Comment by SwampDragons** [comment]
@seeraven that's okay, I've tested on docker and it works for me with this code change.  Thanks for reporting; sorry for the bug.
