### ISSUE TITLE
* Post-processor failed: Unknown artifact type, requires box from vagrant post-processor: transcend.qemu

### ISSUE THREAD

**Issue by shibumi** [hashicorp/packer#5246]
packer version: 1.0.3
Host Platform: Arch Linux
template.json: https://github.com/archlinux/arch-boxes/blob/master/vagrant.json
output: https://paste.archlinux.de/M2D8/

**Comment by rickard-von-essen** [comment]
You are missing one pair of [] in post-processors. See the [docs] (https://www.packer.io/docs/templates/post-processors.html#post-processor-definition).

**Comment by shibumi** [comment]
@rickard-von-essen which pair? There is one pair around all post-processors and `packer validate template.json` says the file is ok

**Comment by rickard-von-essen** [comment]
You need one more to make them a sequence. vagrant-cloud must follow after vagrant, not be executed directly on the output of virtualbox-iso. Check the example in the docs.
