### ISSUE TITLE
Substring function

### ISSUE THREAD

**Issue by nodesocket** [hashicorp/packer#5255]
Is there a builtin `substring()` function? I'd like to return the first 6 characters of the variable `{{user `uuid`}}`:

      "instance_name": "packer-{{user `uuid`}}"

**Comment by lfarnell** [comment]
@nodesocket currently no, this does not exist. By the looks of the code, it shouldn't be too hard to add it in if you wanted to send a PR.

**Comment by SwampDragons** [comment]
I think this use case should be handled by the relatively new sed function (see https://www.packer.io/docs/templates/engine.html)
