### ISSUE TITLE
Ability to install plugins outside of cwd, plugin directory, or packer directory

### ISSUE THREAD

**Issue by rgl** [hashicorp/packer#5260]
currently packer searches for plugins inside a user ~/.packer.d/plugins or at the same directory has the packer binary; this makes it impossible for having [my chocolatey package](https://github.com/rgl/packer-provisioner-windows-update) available to all users. to make my scenario possible, packer would need to implement one of the following:

1. search for plugins in PATH
1. have a PACKER_PLUGINS_PATH which contains a list of possible plugin search paths

what do you think? which one should be implemented?

**PS** please note that installing the plugin binary in the same directory has packer is out of question, because chocolatey installs each package in its own directory, which means I would have to install my plugin inside other package directory, which is a no-no.

**Comment by mwhooker** [comment]
forgive me, I'm a bit ignorant on windows development. Could you install a symlink (shortcut?) in `~/.packer.d/plugins`?

As for the way this should be done, see how terraform does it here: https://www.terraform.io/docs/plugins/basics.html#installing-a-plugin -  by adding a line to the config (~/.packer.d/packer.config). 

I think it'll be difficult to make a change that diverges from that.

You'll want to look at config.go, which is also where config from the config file should be available

**Comment by rgl** [comment]
Packer also has something like that, but that is not what I'm looking for, because one still has to do that for all users (existing and new).

**Comment by flamarion** [comment]
Would be really nice to be able to inform the `-plugin-dir=<PATH>` as we can do when using `terraform init`.
A good use case is, for example, a Pipeline where the packer binary is installed in WORKSPACE, it allows to use different versions of Packer so the ability to create the plugin dir in the WORKSPACE and inform packer where to looking for the plugins would be very interesting, especially for custom plugins.

**Comment by stobias123** [comment]
plugin dir variable would be super useful.

Jenkins volume mounts over jenkins user home dir, which then removes any plugins I've installed to my container image.

**Comment by SwampDragons** [comment]
@stobias123 This currently exists -- it's the env var `PACKER_CONFIG_DIR`. You still need a `.plugins.d/plugins` subdirectory structure, but you can store the PACKER_CONFIG_DIR anywhere you want. For example:

`export PACKER_CONFIG_DIR=/path/to/custom-dir-name`
where the full path to your plugin `packer-provisioner-custom` is `/path/to/custom-dir-name/.packer.d/plugins/packer-provisioner-custom`
