### ISSUE TITLE
Docker communicator Upload should use docker cp

### ISSUE THREAD

**Issue by StuporHero** [hashicorp/packer#5263]
The Docker communicator copies files to a mounted volume and then "uploads" using docker exec to run a cp command to copy files from the volume to the correct location in the container. I don't know if there was a specific reason for doing that or if the docker cp command didn't exist at the time the docker communicator was created, but I have a specific use-case that requires the use of docker cp. I'm running packer on Windows and I'm running a customized docker host meant to be representative of the production hosts using Vagrant in a VirtualBox VM. Manually running docker cp puts files where they belong, but packer fails to upload files since the volume path is interpreted by Docker to mean a location on my VM rather than the location on my Windows machine where packer is staging the files. I could probably get it to work by fiddling with shared folders in the Vagrantfile and the packer config, but my goal is to allow other devops personnel to run vagrant up and packer build regardless of their platform and without too much hullabaloo. Depending on how you prioritize this, I'm willing to contribute the code, but I've got a bit of a learning curve with Go and with the packer code, so my first inclination is to leave it to the experts.

**Comment by rickard-von-essen** [comment]
This is kind of solved in the unmerged PR #3922. When the Docker builder was created there where no `docker cp` command.

**Comment by StuporHero** [comment]
I was definitely thinking rewriting to use the API would fix it, but I also thought making it work as-is was the path of least resistance to meeting my needs.

Would you accept a PR with the change? I managed to make it work because the learning curve wasn't as hard as I thought it would be, but I haven't touched UploadDir, so I expect I'd have to do that before submitting the PR.

**Comment by mwhooker** [comment]
@StuporHero would definitely merge a PR that adds this. I haven't looked too carefully, but I think this should be simple. You'd want to look at `builder/docker/communicator.go` in the Upload method. You might be able to get away with changing `Command: fmt.Sprintf("command cp %s/%s %s", c.ContainerDir, filepath.Base(tempfile.Name()), dst)` to something like `Command: fmt.Sprintf("docker cp %s/%s %s:%s", c.ContainerDir, filepath.Base(tempfile.Name()), c.ContainerId, dst)` to get it working trivially.

You might be able to get rid of the temp file by setting the `src io.Reader` as the stdin of the RemoteCommand

**Comment by StuporHero** [comment]
@mwhooker Check out what I did. It's more or less what you suggested, but I tried to be surgical with my change and retained the staging directory. The less I change, the less likely I am to break something.
