### ISSUE TITLE
Interpolate variables on file provisioner

### ISSUE THREAD

**Issue by geovanisouza92** [hashicorp/packer#5271]
Hello everyone! Thanks for this tool!

Is it possible to interpolate User Variables inside files that will be uploaded using the File Provisioner?

**Comment by lfarnell** [comment]
@geovanisouza92 No it is not possible and it doesn't fit into the many philosophy of the tool. @mwhooker can you clarify that? Hope that helps!

**Comment by mwhooker** [comment]
Thanks for the ticket @geovanisouza92 

As @lfarnell mentioned, this has been brought up before, but isn't something we're interested in supporting right now. There's still an active discussion on it right now at https://github.com/hashicorp/packer/issues/4530

Going to close this to keep discussion in that ticket. Thanks!

**Comment by geovanisouza92** [comment]
Sure, thanks for both! :smiley:
