### ISSUE TITLE
Display Target Path Name in Packer Log

### ISSUE THREAD

**Issue by jcoconnor** [hashicorp/packer#5275]
New Feature Request - from discussion in #5064 

If ```remote_path``` is used, the target path name should be shown in the log when the script runs.
At the moment the temp name on the origin (packer) system is only shown.

So for example with the following code:
```
    {
      "type": "powershell",
      "remote_path": "c:/Windows/Temp/run-install-win-packages.ps1",
      "inline": [
        "A:\\install-win-packages.ps1"
      ]
    },
```

Instead of this log:
```
00:05:17 ==> windows-10-i386-vmware-vsphere.cygwin: Machine successfully restarted, moving on
00:05:17 ==> windows-10-i386-vmware-vsphere.cygwin: Provisioning with Powershell...
00:05:17 ==> windows-10-i386-vmware-vsphere.cygwin: Provisioning with shell script: /tmp/packer-powershell-provisioner412073830
```

We would get something like:
```
00:05:17 ==> windows-10-i386-vmware-vsphere.cygwin: Machine successfully restarted, moving on
00:05:17 ==> windows-10-i386-vmware-vsphere.cygwin: Provisioning with Powershell...
00:05:17 ==> windows-10-i386-vmware-vsphere.cygwin: Provisioning with shell script: /tmp/packer-powershell-provisioner412073830
00:05:17 ==> windows-10-i386-vmware-vsphere.cygwin: Target Script is: c:/Windows/Temp/run-install-win-packages.ps1
```

Would be very useful if the target script name was actually referenced here:

    {
      "type": "powershell",
      "remote_path": "c:/Windows/Temp/run-install-win-packages.ps1",
      "inline": [
        "A:\\install-win-packages.ps1"
      ]
    },

**Comment by taliesins** [comment]
@jcoconnor this requires changes to winrmcp.

I have done this for my attempt at Terraform hyperv provider. The reason you want this is that depending on the winrm session id, your tmp location changes. 

So session id 3 = c:/windows/temp/3

See: https://github.com/taliesins/terraform/blob/HyperVProvider/vendor/github.com/packer-community/winrmcp/winrmcp/cp.go

**Comment by mwhooker** [comment]
the info in the log output is just the local file path. If you turn on debug logging you should get the remote file. eg ` log.Printf("Uploading file to '%s'", path)`

I think it's important that this information be available, but unless it's not for some reason I think this should be closed.

The workflow as I understand it is:

write temp file locally
winrm cp uploads local file to a random remote location
winrm cp moves uploaded file to destination path
winrm communicator logs destination path
