### ISSUE TITLE
Allow AMI block device mapping to be created without snapshot

### ISSUE THREAD

**Issue by otterley** [hashicorp/packer#5290]
I have a use case where I have two `launch_block_device_mappings`, `/dev/sda1` (root device) and `/dev/sdb` (data device).  The data device exists during the build phase to satisfy some build-time prerequisites, but the actual volume content can be discarded at the the end of the build.  The device can also be quite small.

Meanwhile, there are two `ami_block_device_mappings` of the same device names, `/dev/sda1` and `/dev/sdb`.  I'd like `/dev/sdb` NOT to be associated with a snapshot, since at launch time the instance should have a fresh volume.  But Packer seems to always associate it with a snapshot because the device was mapped at launch time.    Setting `snapshot_id` to `""` seems to have no effect.

**Comment by SwampDragons** [comment]
Maybe I'm misunderstanding your use case -- does `delete_on_termination` not work for you?

**Comment by otterley** [comment]
No, it doesn't.  It sets the flag on the attachment, but doesn't change the snapshot ID associated with it.

As a hack, I tried to create a temporary attachment to `/dev/sdf` in `launch_block_device_mappings` and then add `/dev/sdb` to `ami_block_device_mappings`.  So my mappings looked like this:

```json
    "launch_block_device_mappings": [{
      "device_name": "/dev/sda1",
      "delete_on_termination": true,
      "encrypted": false,
      "volume_size": "100",
      "volume_type": "gp2"
    },
    {
      "device_name": "/dev/sdf",
      "delete_on_termination": true,
      "encrypted": false,
      "volume_size": "100",
      "volume_type": "gp2"
    }],
    "ami_block_device_mappings": [{
      "device_name": "/dev/sda1",
      "delete_on_termination": true,
      "encrypted": false,
      "volume_size": "100",
      "volume_type": "gp2"
    },
    {
      "device_name": "/dev/sdb",
      "delete_on_termination": false,
      "encrypted": true,
      "volume_size": "1000",
      "volume_type": "gp2"
    }]
  }]
```

This created the `/dev/sdb` attachment without a snapshot, but `/dev/sdf` remains associated with the AMI as a block device mapping, even though I didn't specify it (and don't want it).

**Comment by tomelliff** [comment]
This confused me as well because the docs state (emphasis mine):

> launch_block_device_mappings (array of block device mappings) - Add one or more block devices before the Packer build starts. **These are not necessarily preserved when booting from the AMI built with Packer.** See ami_block_device_mappings, above, for details.

I'm not sure I understand what that emphasised comment means if the launch volumes are associated with the snapshot?

In my case I want to create an AMI that has some application data stored on a separate EBS volume and is bootstrapped when the application is installed. I want to discard this application data and then I will use Terraform to attach the persistent volume to a new instance in its place. Either a user data script or a Terraform remote provisioner would then execute a `mount -a` to mount the persistent volume.

**Comment by riponbanik** [comment]
I have got a wired issue recently, a ghost ephemeral device is getting attached, even though it was not created with launch_block_device_mappings and launch_block_device_mappings when launching via terraform.

 "ebs_block_device.4241468425.device_name": "xvdco",
 "ebs_block_device.4241468425.encrypted": "true",
 "ebs_block_device.4241468425.iops": "300",
 "ebs_block_device.4241468425.snapshot_id": "",
 "ebs_block_device.4241468425.volume_size": "100",
  "ebs_block_device.4241468

**Comment by jbouse** [comment]
What is the status of this? I'm trying to build a custom AMI built off a source AMI that has a 2nd EBS volume that does not use/require a snapshot but when Packer builds my custom AMI following the template the 2nd EBS volume now has a snapshot that I can't seem to get rid of.

**Comment by rickard-von-essen** [comment]
Try with https://packer.io/docs/builders/amazon-ebs.html#no_device
