### ISSUE TITLE
hyperv-iso builder types boot_command too fast, loosing key strokes

### ISSUE THREAD

**Issue by StefanScherer** [hashicorp/packer#5291]
First thanks for having the Hyper-V builder integrated into packer.
I try to evaluate a PR to add the hyperv-iso builder section to the boxcutter/ubuntu Packer templates. Unfortunately the `boot_command` misses some keystrokes.
The `boot_command` is a little bit lengthy with a lot of backspaces and then the complete new boot options for the Ubuntu Server installation.

- Packer version from `packer version`
Packer v1.0.4

- Host platform
Windows Server 2016 running in Azure VM Standard_E4s_v3 with nested Hyper-V virtualization
(The Host is created with this Terraform template in Azure: https://github.com/StefanScherer/packer-windows/tree/my/hyperv/terraform )

- Debug log output from `$env:PACKER_LOG=1 ; packer build -only=hyperv-iso -var-file="ubuntu1604.json" ubuntu.json`.
https://gist.github.com/StefanScherer/ff6da2e6a4ad7a9bbd6365e6dc91db25

- The ubuntu template uses this `boot_command`:
```json
      "boot_command": [
        "{{ user `boot_command_prefix` }}",
        "/install/vmlinuz noapic ",
        "file=/floppy/hyperv-{{ user `preseed` }} ",
        "debian-installer={{ user `locale` }} auto locale={{ user `locale` }} kbd-chooser/method=us ",
        "hostname={{ user `hostname` }} ",
        "grub-installer/bootdev=/dev/sda<wait> ",
        "fb=false debconf/frontend=noninteractive ",
        "keyboard-configuration/modelcode=SKIP keyboard-configuration/layout=USA ",
        "keyboard-configuration/variant=USA console-setup/ask_detect=false ",
        "passwd/user-fullname={{ user `ssh_fullname` }} ",
        "passwd/user-password={{ user `ssh_password` }} ",
        "passwd/user-password-again={{ user `ssh_password` }} ",
        "passwd/username={{ user `ssh_username` }} ",
        "initrd=/install/initrd.gz -- <enter>"
      ],
```

But instead of `initrd=/install/initrd.gz --` the key scancodes typed into the VM show eg. `initrd=/installngz` in the input field.

<img width="1440" alt="bildschirmfoto 2017-08-29 um 11 32 36" src="https://user-images.githubusercontent.com/207759/29827398-3729ccfa-8cda-11e7-8f71-2d4ee7e8c664.png">

- The _simplest example template and scripts_ needed to reproduce the bug.
I have used this PR https://github.com/boxcutter/ubuntu/pull/119 for my tests which adds the Hyper-V builder to the popular boxcutter/ubuntu repo. But I also had to update to 16.04.3 ISO download URL and checksum.

- Further information
As I saw pull requests https://github.com/hashicorp/packer/pull/1663 and https://github.com/hashicorp/packer/pull/2415 to add 1/10th second delay between key events I guess this is also needed for the hyperv-iso builder to run more stable.

I also tried to add some more `<wait>` special characters, this sometimes helps, but I also got an issue that the user-password and user-password-again had different values.

**Comment by mwhooker** [comment]
> As I saw pull requests #1663 and #2415 to add 1/10th second delay between key events I guess this is also needed for the hyperv-iso builder to run more stable.

I think you're right

**Comment by taliesins** [comment]
https://github.com/taliesins/packer-baseboxes/blob/master/hyperv-pfsense-2.3.2.json

This the approach I took. 

You need to give machine a chance to process after filling in a value and pressing enter.

**Comment by StefanScherer** [comment]
Thanks @taliesins. I agree that if a setup has several input prompts to type that you have to add `<wait>`. For Ubuntu it is just one long boot option input prompt.

Here is one weird situation I got once yesterday where some characters appear uppercase. From the Hyper-V Manager I just watched and haven't pressed any additional key.

<img width="1034" alt="bildschirmfoto_2017-08-31_um_09_58_38" src="https://user-images.githubusercontent.com/207759/29912830-56309b06-8e33-11e7-8130-cf9887bd4bf1.png">

The PR has been updated from generation 1 to 2 which seems to improve it a little bit. I'll investigate some more...

**Comment by dreadknought** [comment]
I am also experiencing this issue, although I haven't seen the uppercase problem.  

Packer 1.6.1
Windows Server 2016 (I believe it's bare metal) with 16 GB memory
Guest VM configured with 8 GB memory
