### ISSUE TITLE
Nonblocking delete operations in Azure

### ISSUE THREAD

**Issue by roman-cnd** [hashicorp/packer#5293]
Feature request: when packer deletes temp resources in Azure - it should do it with nonblocking queries. Otherwise, the build is waiting 3-4 minutes for Azure to complete operations to delete resource groups.

It can be configured as an option, `azure_resource_delete_wait = false` or something like that.

**Comment by matt-richardson** [comment]
This wouldn't be backwards compatible (if it defaulted to not waiting)... For example, if my workflow assumes that the resource group is deleted before i continue the next stage.

We also miss out on seeing an error message if Azure fails to delete the resource group - we will continue to be charged for those resources.

It could either default to waiting, and be opt-out, or `packer fix` could add an attribute to preserve existing behaviour, so people could see and change it.
