### ISSUE TITLE
Better, structured outputs for artifacts and builds information

### ISSUE THREAD

**Issue by roman-cnd** [hashicorp/packer#5294]
A new feature or maybe improvement is required on how packer handles output for artifacts information. It's basically unstructured loglines, which makes it very hard to integrate it with build pipeline.

It would be really helpful to have .env file generated with detailed build info, so information about artifact IDs can be passed to next stage in the build process.

**Comment by rickard-von-essen** [comment]
See the manifest post-processor.

**Comment by roman-cnd** [comment]
Thanks! 
`post-processors` with type manifest already has a perfect format :)
