### ISSUE TITLE
-on-error does not do anything

### ISSUE THREAD

**Issue by vijayinvites** [hashicorp/packer#5295]
According to https://www.packer.io/docs/commands/build.html#on-error-cleanup "packer.exe build -on-error=abort" should not remove the VM or clean up when there is an error during Packer build. But it is not working as expected. Irrespective of what I input for -on-error, the VM is always removed and clean up happens.

Packer version tested- Packer v1.0.4
Host platform: CYGWIN_NT-10.0 rd-dev 2.8.1(0.312/5/3) 2017-07-03 14:11 x86_64 Cygwin
gist: https://gist.github.com/vijayinvites/bb13826c86144056e7484bce6513b464

Sample template:
https://gist.github.com/vijayinvites/3ac1a0af9b1011361182f80d2e81ebc8
I am using Hyper-V builder

**Comment by rickard-von-essen** [comment]
Please supply the information requested in the issue template:
- Packer version (`packer version`)
- Host platform (`uname -a` etc.)
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a [gist](https://gist.github.com).
- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your [gist](https://gist.github.com).

At least state which builder you are using.

**Comment by vijayinvites** [comment]
I have included all the details that are required. I am using hyper-v builder.

**Comment by vijayinvites** [comment]
@rickard-von-essen, do you need more infor?

**Comment by rickard-von-essen** [comment]
No there is a bug here:
https://github.com/hashicorp/packer/blob/master/builder/hyperv/iso/builder.go#L408
Its using the wrong runner.

**Comment by rickard-von-essen** [comment]
Seems like more plugins need to be fixed https://github.com/hashicorp/packer/search?utf8=%E2%9C%93&q=DebugRunner&type=
