### ISSUE TITLE
SOLVED packer vmware-iso and "ethernet0.startConnected": "TRUE"

### ISSUE THREAD

**Issue by perbly** [hashicorp/packer#5303]
Hi

- Packer version: 1.0.4
- Host platform: vsphere 6.0.0

We are struggling with a small but annoying issue. Vmware is giving us a hard time as always.
The problem is that we are using vmware-iso builder and providing some vmx data.
According to the packer log this vmx config is written fine.

But when the template is being started in vmware we need to click the checkbox saying "connected" on the network interface. 
When we do that everything else is resuming fine.

Shouldn't it be this line that configures this:

        "ethernet0.startConnected": "TRUE",

vmx_data :

> 

    "vmx_data": {
        "memsize": "2048",
        "numvcpus": "4",
        "ethernet0.addressType": "generated",
        "ethernet0.dvs.portgroupId": "xxxx",
        "ethernet0.dvs.switchId": "xxxx",
        "ethernet0.networkName": "{{ user `PACKER_VMX_ETHERNET0_NETWORKNAME` }}",
        "ethernet0.present": "TRUE",
        "ethernet0.startConnected": "TRUE",
        "ethernet0.uptCompatibility": "TRUE",
        "ethernet0.virtualDev": "vmxnet3",
        "ethernet0.vnet":"NETWORK",
        "ethernet0.pciSlotNumber": "160"
      } 

- Debug log output from `PACKER_LOG=1 packer build template.json`.

> 

[0m[1;32m==> ubuntu-1604-vmware-iso: Building and writing VMX file[0m
[91m2017/09/05 07:11:10 packer: 2017/09/05 07:11:10 Writing VMX to: /tmp/packer-vmx009193915/ubuntu-1604-build-1ECEiMkiXJ.vmx
[0m[91m2017/09/05 07:11:10 packer: 2017/09/05 07:11:10 Setting VMX: 'scsi0.present' = 'TRUE'
2017/09/05 07:11:10 packer: 2017/09/05 07:11:10 Setting VMX: 'scsi0:0.deviceType' = 'scsi-hardDisk'
2017/09/05 07:11:10 packer: 2017/09/05 07:11:10 Setting VMX: 'sched.scsi0:0.throughputCap' = 'off'
**2017/09/05 07:11:10 packer: 2017/09/05 07:11:10 Setting VMX: 'ethernet0.startConnected' = 'TRUE'**
2017/09/05 07:11:10 packer: 2017/09/05 07:11:10 Setting VMX: 'ethernet0.addressType' = 'generated'
2017/09/05 07:11:10 packer: 2017/09/05 07:11:10 Setting VMX: 'ethernet0.pciSlotNumber' = '160'
2017/09/05 07:11:10 packer: 2017/09/05 07:11:10 Setting VMX: 'sched.scsi0:0.shares' = 'normal'
2017/09/05 07:11:10 packer: 2017/09/05 07:11:10 Setting VMX: 'ethernet0.dvs.switchId' = 'xxxxx'
2017/09/05 07:11:10 packer: 2017/09/05 07:11:10 Setting VMX: 'ethernet0.networkName' = 'network'
2017/09/05 07:11:10 packer: 2017/09/05 07:11:10 Setting VMX: 'ethernet0.virtualDev' = 'vmxnet3'
2017/09/05 07:11:10 packer: 2017/09/05 07:11:10 Setting VMX: 'numvcpus' = '4'
2017/09/05 07:11:10 packer: 2017/09/05 07:11:10 Setting VMX: 'scsi0.virtualDev' = 'pvscsi'
2017/09/05 07:11:10 packer: 2017/09/05 07:11:10 Setting VMX: 'ethernet0.vnet' = 'NETWORK'
2017/09/05 07:11:10 packer: 2017/09/05 07:11:10 Setting VMX: 'ethernet0.uptCompatibility' = 'TRUE'
2017/09/05 07:11:10 packer: 2017/09/05 07:11:10 Setting VMX: 'memsize' = '2048'
2017/09/05 07:11:10 packer: 2017/09/05 07:11:10 Setting VMX: 'ethernet0.present' = 'TRUE'
2017/09/05 07:11:10 packer: 2017/09/05 07:11:10 Setting VMX: 'scsi0:0.present' = 'TRUE'
2017/09/05 07:11:10 packer: 2017/09/05 07:11:10 Setting VMX: 'ethernet0.dvs.portgroupId' = 'xxxx'
2017/09/05 07:11:10 packer: 2017/09/05 07:11:10 Setting VMX: 'virtualHW.version' = '11'
2017/09/05 07:11:10 packer: 2017/09/05 07:11:10 Writing VMX to: /tmp/packer-vmx009193915/ubuntu-1604-build-1ECEiMkiXJ.vmx
[0m[91m2017/09/05 07:11:10 packer: 2017/09/05 07:11:10 Suppressing messages in VMX

**Comment by perbly** [comment]
We solved our own problem.

This configuration should not exists. Removing it solved our problem

`"ethernet0.vnet":"NETWORK"`

**Comment by mwhooker** [comment]
👍
