### ISSUE TITLE
Provisioning of docker builder fails when container run as non-root

### ISSUE THREAD

**Issue by kostrzewa9ld** [hashicorp/packer#5307]
Provisioning of docker container (started by docker builder) fails when the container is started as non-root.
The problem seems to be that the `/packer-files` is mounted with permissions allowing for reading/writing only to the user starting the container.
 
Packer version:
```
Packer v1.0.4
```

Template:
```
{
        "provisioners": [
                {
                        "type": "shell",
                        "inline": "touch /provisioned"
                }
        ],
        "builders": [
                {
                        "type": "docker",
                        "image": "jenkins/jenkins:lts",
                        "commit": true
                }
        ]
}
```

Listing the container:
```
jenkins@a38e49e4f41e:/$ ls -l
total 52
lrwxrwxrwx   1 root  root    7 Jul 23 00:00 bin -> usr/bin
drwxr-xr-x   2 root  root 4096 Jul 13 13:04 boot
drwxr-xr-x   5 root  root  360 Sep  6 07:52 dev
lrwxrwxrwx   1 root  root   33 Jul 24 18:09 docker-java-home -> /usr/lib/jvm/java-8-openjdk-amd64
drwxr-xr-x  73 root  root 4096 Sep  6 07:52 etc
drwxr-xr-x   2 root  root 4096 Jul 13 13:04 home
lrwxrwxrwx   1 root  root    7 Jul 23 00:00 lib -> usr/lib
lrwxrwxrwx   1 root  root    9 Jul 23 00:00 lib32 -> usr/lib32
lrwxrwxrwx   1 root  root    9 Jul 23 00:00 lib64 -> usr/lib64
lrwxrwxrwx   1 root  root   10 Jul 23 00:00 libx32 -> usr/libx32
drwxr-xr-x   2 root  root 4096 Jul 23 00:00 media
drwxr-xr-x   2 root  root 4096 Jul 23 00:00 mnt
drwxr-xr-x   2 root  root 4096 Jul 23 00:00 opt
drwx------   2 20153 1017 4096 Sep  6 07:52 packer-files
dr-xr-xr-x 329 root  root    0 Sep  6 07:52 proc
drwx------   2 root  root 4096 Jul 23 00:00 root
drwxr-xr-x   4 root  root 4096 Jul 23 00:00 run
lrwxrwxrwx   1 root  root    8 Jul 23 00:00 sbin -> usr/sbin
drwxr-xr-x   2 root  root 4096 Jul 23 00:00 srv
dr-xr-xr-x  13 root  root    0 Sep  4 10:52 sys
drwxrwxrwt   4 root  root 4096 Sep  5 20:56 tmp
drwxr-xr-x  49 root  root 4096 Sep  5 20:56 usr
drwxr-xr-x  31 root  root 4096 Sep  5 20:56 var
```

[packer build log](https://gist.githubusercontent.com/kostrzewa9ld/72dcbb4fde84ff5326232514cd0b3861/raw/4da85523f695d5fb8e11b740acaae33dabd7671b/packer_build.log)

**Comment by mwhooker** [comment]
Can you try with a more recent version of packer? We recently switched file upload to use `docker cp` rather than copying trough a shared volume. Will reopen if this is still an issue, but I believe it's been fixed

**Comment by kostrzewa9ld** [comment]
@mwhooker 
Tested with Packer 1.1.0, this time non-root user can't make the script executable:
```
2017/09/28 21:48:30 packer: 2017/09/28 21:48:30 Executing docker exec -i 415c231d90538619dce16a1a83f794706566972aa051ba1e189fab6c52476f6c /bin/sh -c (chmod +x /tmp/script_8828.sh; PACKER_BUILDER_TYPE='docker' PACKER_BUILD_NAME='docker'  /tmp/script_8828.sh):
2017/09/28 21:48:30 ui:     docker: chmod: changing permissions of '/tmp/script_8828.sh': Operation not permitted
2017/09/28 21:48:30 ui:     docker: /bin/sh: 1: /tmp/script_8828.sh: Permission denied
```
([full log](https://gist.githubusercontent.com/kostrzewa9ld/72dcbb4fde84ff5326232514cd0b3861/raw/066c07e7df1e97dd1d2ae82496b9bc5dda826017/packer_1.1.0_build.log))

```
jenkins@415c231d9053:/$ ls -l /tmp/
total 8
drwxr-xr-x 2 root root 4096 Sep 14 04:19 hsperfdata_root
-rw------- 1 root root   36 Sep 28 19:48 script_8828.sh
```

**Comment by mwhooker** [comment]
hmm, interesting. It seems like the proper solution is to upload to a directory where you have write access. alternatively, we could pass `--privileged` to `docker exec`. Can you tell me how you've run docker? I'm having trouble understanding how to get into this situation

**Comment by mwhooker** [comment]
some investigating... looks like `docker cp` uses the uid/gid of the user on the host. There's an option to pass `-a` to use the uid/gid of the guest, but that appears to be broken for now. https://github.com/moby/moby/issues/34142

still looking for a workaround

**Comment by mwhooker** [comment]
I was able to get the permissions to work by doing

```
{
    "builders": [
        {
            "commit": true,
            "image": "jenkins/jenkins:lts",
            "type": "docker",
            "volumes": {"/Users/mwhooker/dev/packertest-5307": "/tmp-packer"}
        }
    ],
    "provisioners": [
        {
            "inline": ["touch /provisioned"],
            "remote_folder": "/tmp-packer",
            "type": "shell"
        }
    ]
}
```

but it failed on `touch /provisioned`.


I will add an option to pass `-u` to `docker exec`. I was able to get it working by execing as root

**Comment by kostrzewa9ld** [comment]
The option is great for some use cases but I believe it does not solve the problem that it is not possible to call `shell` directly as user other than root. If I am right, this is because the script uploaded to the container is owned by root so running [`chmod +x` on the script](https://gist.github.com/kostrzewa9ld/72dcbb4fde84ff5326232514cd0b3861#file-packer_1-1-0_build-log-L153) is only possible as root.
Actually I just checked that `file` provisioner also makes the uploaded files be owned by root. So the problem seems to be with uploading to the container in general.

Probably I could set `exec_user` to "root" and then run the commands through e.g. "su" as regular user or change the ownership of uploaded files but that's very inconvenient. 

What I would expect is that scripts and anything that's uploaded to the container is owned by the user the container is started as (that could be extracted using e.g. `docker inspect` on the container). So after uploading something to the container the communicator should change the ownership of the uploaded files by running sth. like `docker exec -u root [CONTAINER] chown -R [CONTAINER_USER] [UPLOADED_FILES]`.

**Comment by mwhooker** [comment]
> What I would expect is that scripts and anything that's uploaded to the container is owned by the user the container is started as (that could be extracted using e.g. docker inspect on the container). So after uploading something to the container the communicator should change the ownership of the uploaded files by running sth. like docker exec -u root [CONTAINER] chown -R [CONTAINER_USER] [UPLOADED_FILES].

That seems like a reasonable workaround until #5409 is implemented. Happy to review PRs.

**Comment by kostrzewa9ld** [comment]
If this is treated as a "workaround" valid until #5409 is implemented then docker builder, at least with respect to this issue, will only support docker in version >= with moby/moby#34142 fixed?

**Comment by mwhooker** [comment]
We generally only support the latest version of docker, since it's changing
so rapidly
