### ISSUE TITLE
packer should trigger virtualbox with --type headless when the variable 'headless' is set to true.

### ISSUE THREAD

**Issue by shibumi** [hashicorp/packer#5310]
Hello,
The following problem:
We want to trigger automated packer builds on one of our servers. So we don't have an X-Server on that machine. We run our builds with the internal packer variable `headless=true`. The qemu build works without a problem, but when we trigger the virtualbox build we get the following error: 
```
==> virtualbox-iso: Error starting VM: VBoxManage error: VBoxManage: error: The virtual machine 'packer-virtualbox-iso-1504738600' has terminated unexpectedly during startup with exit code 1 (0x1)                                                                                                                           
==> virtualbox-iso: VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine      
```

I have traced that bug to this ticket: https://www.virtualbox.org/ticket/7367
So the solution is to trigger the `startvm` command of `virtualbox` with `type=headless` when the `headless`-variable in packer has been set.

Our packer version is: 1.0.4

**Comment by mwhooker** [comment]
That logic [already exists](https://github.com/hashicorp/packer/blob/master/builder/virtualbox/common/step_run.go#L32-L52), so I'm surprised this doesn't work for you. Can you please post a json that reproduces the issue

**Comment by shibumi** [comment]
sure: https://github.com/archlinux/arch-boxes/blob/master/vagrant.json
You can test this with this line:
```
packer-io build -parallel=false -var 'headless=true' -var 'iso_url=https://downloads.archlinux.de/iso/2017.09.01/archlinux-2017.09.01-x86_64.iso' -var 'iso_checksum_url=https://downloads.archlinux.de/iso/2017.09.01/sha1sums.txt' -except=vmware-iso -except=qemu vagrant.json
```

**Comment by rickard-von-essen** [comment]
Please [gist](https://gist.github.com/) a full debug log from `PACKER_LOG=1 packer build template.json`.

**Comment by shibumi** [comment]
Hello, 
nvm. Sorry for the noise. Works now as expected. I forgot loading the virtualbox modules.
