### ISSUE TITLE
Additional partition for openstack image

### ISSUE THREAD

**Issue by Prabhakar-cg** [hashicorp/packer#5313]
Hi,

I am trying to build a image (rhel7)  for openstack. My base image doesn't have enough storage in /opt which is very essential for app deployment and i am not finding any parameters for adding block storage in openstack builder like in aws (launch_block_device_mappings). 

Can anyone guide me on this.

**Comment by rickard-von-essen** [comment]
What about using a flavor with bigger disk and just expand `/opt` on the same device?

**Comment by Prabhakar-cg** [comment]
Hi Rick,
Thank you..
i2.8xlarge is the biggest we have but unfortunately that is also comes with 100GB disk which is lesser for  my app deployment.

**Comment by renaldrozario** [comment]
This is a much needed addition in packer as we plan to package application on the additional volume,  so does everyone.

**Comment by rickard-von-essen** [comment]
Reading the [API docs](https://developer.openstack.org/api-ref/image/v2/index.html#images) can't find any evidence that this is supported.

Can someone give me a counter example?

**Comment by renaldrozario** [comment]
@rickard-von-essen , looking for a feature as in AWS

**Comment by renaldrozario** [comment]
@rickard-von-essen  ... Looking for a feature like the one provided in AWS

"launch_block_device_mappings": [{
			"device_name": "/dev/sda1",
			"volume_size": 80,
			"delete_on_termination": true
		}],

**Comment by rickard-von-essen** [comment]
See above.

**Comment by ozerovandrei** [comment]
@rickard-von-essen Hello.
I guess that OpenStack Compute service makes that possible by providing a `block_device_mapping_v2` option to a server create request body:
```
"block_device_mapping_v2": [{
    "boot_index": "0",
    "uuid": "ac408821-c95a-448f-9292-73986c790911",
    "source_type": "image",
    "volume_size": "25",
    "destination_type": "volume",
    "delete_on_termination": true,
    "tag": "disk1",
    "disk_bus": "scsi"}]
```

Users can pass several devices in that list with different `boot_indexes` and `device_names`.
References:
[API Ref #create-server](https://developer.openstack.org/api-ref/compute/#create-server)
[Block Device Mapping in Nova](https://docs.openstack.org/nova/pike/user/block-device-mapping.html)

Gophercloud currently supports it for the Compute V2 service:
[extensions/bootfromvolume/requests.go#L76](https://github.com/gophercloud/gophercloud/blob/master/openstack/compute/v2/extensions/bootfromvolume/requests.go#L76)

Also, package `compute/v2/extensions/bootfromvolume` is vendored in Packer in the open PR #6300.

**Comment by renaldrozario** [comment]
@ozerovandrei ..  isn't your snippet terraform specific?

**Comment by ozerovandrei** [comment]
@renaldrozario no, it's a valid JSON example.

You can find some examples in the tests of the Nova API server:
[#1](https://github.com/openstack/nova/blob/stable/queens/nova/tests/functional/api_sample_tests/api_samples/servers/v2.32/server-create-req.json.tpl#L9)
[#2](https://github.com/openstack/nova/blob/stable/queens/nova/tests/functional/api_sample_tests/api_samples/servers/v2.42/server-create-req.json.tpl#L9)
[#3](https://github.com/openstack/nova/blob/stable/queens/nova/tests/unit/api/openstack/compute/test_serversV21.py#L3977)

Although you need to keep in mind that this feature is supported only if you have the Blockstorage (Cinder) service in your OpenStack installation.

**Comment by hprasad068** [comment]
@ozerovandrei @rickard-von-essen  .Were you able to add additonal volumes during packer imaging..?. i was able to do this in AWS i still cant find a solution for openstack packer.

**Comment by rickard-von-essen** [comment]
Still I don't see that this is possible. We are using [Block Storage v3 - upload-volume-to-image Action](https://docs.openstack.org/api-ref/block-storage/v3/?expanded=upload-volume-to-image-detail) and it only takes one volume per image.

Could someone requesting this feature provide either a ref to to API calls to achieve this? Or at least provide proof that there are any image on OpenStack that contains multiple volumes?
