### ISSUE TITLE
vmware-vmx builder and VMware Fusion Tech Preview not working together

### ISSUE THREAD

**Issue by trodemaster** [hashicorp/packer#5317]
- Packer version Packer v1.1.0-dev (f7c85e36)
- Host macOS 10.12.6
- VMware Fusion Tech Preview https://communities.vmware.com/community/vmtn/beta/fusion-pro/overview

Repro steps
  
Set packer to use the VMware Fusion Tech Preview in builder config.
  "fusion_app_path": "/Applications/VMware Fusion Tech Preview.app"

Start a build with the vmware-vmx builder. Packer errors out with the following message. 
"Cloning is not supported with Fusion 5. Please use Fusion 6+"

Logfile
https://gist.github.com/trodemaster/fd717bafc1aa1f586db3434996477ad8

packer template json
https://gist.github.com/trodemaster/69fa5a3570d020cff713595c16403b7a

Looks like the version detection code for Fusion is not working well with the Fusion Tech Preview.

**Comment by rickard-von-essen** [comment]
What's the output of `/Applications/VMware\ Fusion.app/Contents/Library/vmware-vmx -v`?

**Comment by trodemaster** [comment]
`/Applications/VMware\ Fusion\ Tech\ Preview.app/Contents/Library/vmware-vmx -v

VMware Fusion Information:
VMware Fusion e.x.p build-6048684 Release`

VMware uses the "e.x.p" for tech preview builds for the last few times. I wasn't able to find the packer code that does the detection. I see some things referenced in the fusion 6 driver.

**Comment by rickard-von-essen** [comment]
Can you test this patch:

```udiff
diff --git a/builder/vmware/common/driver_fusion6.go b/builder/vmware/common/driver_fusion6.go
index af42c7ef9..9f546d384 100644
--- a/builder/vmware/common/driver_fusion6.go
+++ b/builder/vmware/common/driver_fusion6.go
@@ -58,8 +58,17 @@ func (d *Fusion6Driver) Verify() error {
 		return err
 	}
 
+	// VMware Fusion e.x.p build-6048684 Release
+	techPreviewRe := regexp.MustCompile(`(?i)VMware [a-z0-9-]+ e\.x\.p `)
+	matches := techPreviewRe.FindStringSubmatch(stderr.String())
+	if matches != nil {
+		log.Printf("Detected VMware version: e.x.p (Tech Preview)")
+		return nil
+	}
+
+	// VMware Fusion 7.1.3 build-3204469 Release
 	versionRe := regexp.MustCompile(`(?i)VMware [a-z0-9-]+ (\d+)\.`)
-	matches := versionRe.FindStringSubmatch(stderr.String())
+	matches = versionRe.FindStringSubmatch(stderr.String())
 	if matches == nil {
 		return fmt.Errorf(
 			"Couldn't find VMware version in output: %s", stderr.String())
```

**Comment by trodemaster** [comment]
This patch fixes the issue I reported! 
Tested with Fusion 8.5.8 and the 2017 Tech Preview versions of Fusion.

**Comment by SwampDragons** [comment]
@rickard-von-essen did we ever merge this patch?

**Comment by rickard-von-essen** [comment]
Pretty sure we didn't.

**Comment by SwampDragons** [comment]
Wanna open a PR for it?
