### ISSUE TITLE
Can't use variable with validate for image_family in googlecompute

### ISSUE THREAD

**Issue by rokka-n** [hashicorp/packer#5319]
Describe the problem and include the following information:

Variables are not interpolated for `packer -validate ` in googlecompute builder for `image_family`

V 1.0.4
Platform: Mac or linux

packer.json
```json
{
  "variables": {
    "ci_branch": "{{env `CI_BRANCH`}}"
  },
"builders": [
    {
      "type": "googlecompute",
      "zone": "1a",
      "project_id": "123",
      "ssh_username": "blah",
      "source_image_family": "source-family",
      "image_name": "test",
      "image_family": "base-{{user `ci_branch`}}"
    }
  ]
}
```

```
packer validate -var 'CI_BRANCH=feature1' test.json
```
Template validation failed. Errors are shown below.

Errors validating build 'googlecompute'. 1 error(s) occurred:

* Invalid image family: The first character must be a lowercase letter, and all following characters must be a dash, lowercase letter, or digit, except the last character, which cannot be a dash

```

https://github.com/hashicorp/packer/pull/3503

**Comment by rickard-von-essen** [comment]
What about:

```
CI_BRANCH=feature1 packer validate test.jso
```

**Comment by rokka-n** [comment]
Works that way, however `-var foo=bar` or  
`packer validate -var-file=tmp/packer-vars.json test.json` would error.

```
{
    "CI_BRANCH": "test-feature555"
}
```

What am I missing? Essentially I wanted to use a config file for some vars that are hard to pass in an environment.

**Comment by lorengordon** [comment]
In your template, the variable name is not capitalized. Don't capitalized it on the cli or the var file.

**Comment by roman-cnd** [comment]
Oooh, I see - that was the problem.
Thanks!
