### ISSUE TITLE
impossible to set two builder in one template

### ISSUE THREAD

**Issue by Tioborto** [hashicorp/packer#5321]
Hello, 

I have some problems to create a virtual machine. 
In this template, i have two builders type : vmware & virtualbox. I don't create in parallel but i call this template with "-only" & "-parallel=false" options. 

- Vmware to create on esxi and don't export to keep registered.
- Virtualbox to export to ova file

But like you see in output log file, this doesn't work and i don't understand why.

Informations :
- Packer version : 1.0.4-dev
- Host platform : Centos 7
- Debug log : https://gist.github.com/Tioborto/f26bd9fed7f850d544adfc4f1903cf6f
- Template : https://gist.github.com/Tioborto/9751219e619e17cba96af22abb9dc7ec

Do you have any idea ?

**Comment by mwhooker** [comment]
Make sure you're invoking `build` correctly.

`packer build 5321.json -only=virtualbox-iso` should work.

the argument to `--only` should be the builder type. Hope that helps.

**Comment by mwhooker** [comment]
see also https://www.packer.io/docs/commands/build.html#only-foo-bar-baz for more information. Since you've got a `name` parameter, you'll want to pass that to `-only` for the vmware builder

**Comment by Tioborto** [comment]
Sorry it's the bad log. I test with vmware-iso or virtualbox-iso option & i get some errors. 
`
2017/09/10 15:36:38 Attempting to open config file: /root/.packerconfig
2017/09/10 15:36:38 [WARN] Config file doesn't exist: /root/.packerconfig
2017/09/10 15:36:38 Packer config: &{DisableCheckpoint:false DisableCheckpointSignature:false PluginMinPort:10000 PluginMaxPort:25000 Builders:map[virtualbox-ovf:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-virtualbox-ovf parallels-iso:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-parallels-iso amazon-chroot:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-amazon-chroot googlecompute:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-googlecompute profitbricks:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-profitbricks vmware-vmx:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-vmware-vmx amazon-ebs:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-amazon-ebs oneandone:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-oneandone qemu:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-qemu vmware-iso:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-vmware-iso openstack:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-openstack alicloud-ecs:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-alicloud-ecs docker:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-docker file:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-file amazon-instance:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-amazon-instance azure-arm:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-azure-arm hyperv-iso:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-hyperv-iso amazon-ebssurrogate:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-amazon-ebssurrogate cloudstack:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-cloudstack digitalocean:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-digitalocean parallels-pvm:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-parallels-pvm virtualbox-iso:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-virtualbox-iso null:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-null triton:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-triton amazon-ebsvolume:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-amazon-ebsvolume] PostProcessors:map[alicloud-import:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-alicloud-import docker-import:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-docker-import checksum:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-checksum artifice:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-artifice compress:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-compress atlas:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-atlas googlecompute-export:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-googlecompute-export vagrant:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-vagrant vsphere:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-vsphere amazon-import:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-amazon-import docker-tag:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-docker-tag shell-local:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-shell-local manifest:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-manifest docker-push:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-docker-push docker-save:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-docker-save vagrant-cloud:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-vagrant-cloud] Provisioners:map[chef-solo:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-chef-solo powershell:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-powershell file:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-file ansible:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-ansible shell:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-shell chef-client:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-chef-client puppet-masterless:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-puppet-masterless win==> Builds finished but no artifacts were created.
dows-shell:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-windows-shell ansible-local:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-ansible-local shell-local:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-shell-local puppet-server:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-puppet-server salt-masterless:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-salt-masterless windows-restart:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-windows-restart converge:/root/go/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-converge]}
2017/09/10 15:36:38 Detected home directory from env var: /root
2017/09/10 15:36:38 Setting cache directory: /opt/speedworkv2/packer_cache
2017/09/10 15:36:38 ui: Debug mode enabled. Builds will not be parallelized.
2017/09/10 15:36:38 Build debug mode: true
2017/09/10 15:36:38 Force build: true
2017/09/10 15:36:38 On error:
2017/09/10 15:36:38 Waiting on builds to complete...
2017/09/10 15:36:38 Builds completed. Waiting on interrupt barrier...
2017/09/10 15:36:38 ui:
==> Builds finished but no artifacts were created.
2017/09/10 15:36:38 Detected home directory from env var: /root
2017/09/10 15:36:38 waiting for all plugin processes to complete...
`

**Comment by Tioborto** [comment]
Virtualbox run but vmware no
