### ISSUE TITLE
Google Cloud clean_image_name function

### ISSUE THREAD

**Issue by danielcompton** [hashicorp/packer#5323]
Packer provides a function `clean_ami_name` which replaces characters to create an AMI name acceptable to Amazon. It would be handy if there was a similar function for Google Cloud, as they also restrict the names of images.

The regex that is applied is: `(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)`.

My concrete use case is that I want to name the image after the version of the app that I'm deploying (and have as a user variable), but the version has `.`s in it, which don't pass the GCP regex.

Would a feature like this be likely to be accepted?

**Comment by rickard-von-essen** [comment]
We would happily accept a PR for this.
