### ISSUE TITLE
How to run the multiple powershell script in one powershell script

### ISSUE THREAD

**Issue by vTechworld** [hashicorp/packer#5324]
Hi team, 

Please help me in getting How to run the multiple powershell script in one powershell script

**Comment by rickard-von-essen** [comment]
Please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._
