### ISSUE TITLE
bmcs: Follow name change to OCI

### ISSUE THREAD

**Issue by rickard-von-essen** [hashicorp/packer#5326]
There a probably things we need to follow these:
https://github.com/oracle/oci-cli/pull/12
https://github.com/oracle/oci-python-sdk/pull/27

At least for the config dir change.

**Comment by rickard-von-essen** [comment]
CC @prydie

**Comment by mwhooker** [comment]
@rickard-von-essen thanks for making this ticket. Oracle will make this change before we release

**Comment by prydie** [comment]
@mwhooker @rickard-von-essen It's 9pm here in the UK so if this has sign-off our end and the release is slated for today then someone stateside will need to make the changes. If not I'll submit a PR ASAP tomorrow morning.
