### ISSUE TITLE
Salt provisioner uploads files to wrong location when running under Windows

### ISSUE THREAD

**Issue by gldnspud** [hashicorp/packer#533]
Packer v0.3.9 on Windows 7 x64 and OSX 10.7.5

The provisioner is defined in `template.json` as follows:

```
{
  "type": "salt-masterless",
  "local_state_tree": "../tvsalt",
  "local_pillar_roots": "../tvpillar"
},
```

In OSX this works great, and `../tvsalt/whatever.sls` gets uploaded to `/tmp/salt/states/whatever.sls`:

![osx](https://f.cloud.github.com/assets/15943/1326700/ab1cefbe-34e3-11e3-9ee9-a9ad98fee4de.png)

However, in Windows a different destination path is used, `\tmp\salt\tvsalt\whatever.sls`, so then the provisioner fails when it tries to operate on `/tmp/salt/states`:

![windows](https://f.cloud.github.com/assets/15943/1326680/78bab84e-34e3-11e3-83f5-41fe17371d9f.png)

**Comment by mwhooker** [comment]
this seems to be the same class of bug as #4689

**Comment by nywilken** [comment]
Hello folks, thanks for opening up this issue. Apologies that we've not had the chance to dive further into this issue. If you've managed to resolve your problem we encourage you to leave comment for others who may experience this issue in the future.

With that said, this is one of our community maintained plugins, which we have recently flagged as [unmaintained](https://github.com/hashicorp/packer/blob/master/README.md#unmaintained-plugins). If you are interested in contributing or taking ownership of this plugin, please reach out to us at packer@hashicorp.com.
