### ISSUE TITLE
Hyper-V Builder Failing with VMware-related PowerShell Error

### ISSUE THREAD

**Issue by pjorg** [hashicorp/packer#5337]
On Packer v1.0.4 running on Windows 10 with VMware PowerCLI installed, attempts to build on Hyper-V fail with a PowerCLI-related error:

```--> hyperv-iso: Error creating virtual machine: PowerShell error: New-VM : A parameter cannot be found that matches parameter name 'Path'.
At C:\Users\pjorg\AppData\Local\Temp\ps878816063.ps1:5 char:22
+ New-VM -Name $vmName -Path $path -MemoryStartupBytes $memoryStartupBy ...
+                      ~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-VM], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,VMware.VimAutomation.ViCore.Cmdlets.Commands.NewVM
```
This appears to be due to the fact that PowerCLI and the Hyper-V PowerShell extensions have conflicting cmdlet names—in this case `New-VM`, but `Get-VM` and `Remove-VM` also conflict. Packer is attempting to call the Hyper-V `New-VM`, but it is instead getting the PowerCLI `New-VM`, and is failing.

Fully qualifying cmdlet references in the code should probably fix this.

**Comment by pjorg** [comment]
I modified all of the references to `Export-VM`, `Get-VM`, `Get-VMHost`, `Move-VM`, `New-VM`, `Remove-VM`, `Restart-VM`, `Set-VM`, `Set-VMHost`, `Start-VM`, `Stop-VM` and `Suspend-VM` in `common/powershell/hyperv/hyperv.go` to prepend `Hyper-V\`, but when I compile it looks like the behavior doesn't change. I don't see anywhere else in the codebase where these references would be, though.

**Comment by mwhooker** [comment]
@pjorg any chance you want to review/test #5225? It looks like it does the same thing you tried, but want to confirm

**Comment by SwampDragons** [comment]
@pjorg does the referenced PR fix things for you?  It seems to be taking the same approach you did, but maybe found something you missed?

**Comment by SwampDragons** [comment]
If the linked PR doesn't do it, we might be that we need to do some magic with prefixing...

`Import-Module -Name hyper-v -Prefix HV` or something
