### ISSUE TITLE
[1.1.0] Puppet-Masterless provisioner lost bin path in default command

### ISSUE THREAD

**Issue by CClarkAZ** [hashicorp/packer#5339]
Looks like #5252 dropped the PuppetBinDir template variable from the default puppet apply commands when it was split into Unix/Win. This means that in the Packer JSON file the puppet provisioner parameter `puppet_bin_dir` no longer works without supplying a proper command.

`{{if ne .PuppetBinDir \"\"}}{{.PuppetBinDir}}/{{end}}puppet apply` was changed to `puppet apply` in `/provisioner/puppet-masterless/provisioner.go`

Hopefully this is clear enough that someone who already has a fork set up can easily submit a PR.

Thanks.

**Comment by mwhooker** [comment]
Thanks for the report @CClarkAZ, sorry about that. I think that's enough info the go off of.

cc @c22

**Comment by c22** [comment]
Ah.. Good pickup, that comes from bcd30ad specifically.

I suspect it will work either way due Windows' compatibility shims, but should that ideally be a backslash after `{{.PuppetBinDir}}` instead of a forward slash?

**Comment by c22** [comment]
Nevermind, I suspect changing to a backslash here will just needlessly confuse things, the `stagingDir` uses forward slashes and so does all the code in `puppet-server.go`. For consistency, I'll make it forward slash 👍

**Comment by mwhooker** [comment]
Just to be clear, I think the problem is the `PuppetBinDir` variable isn't in the template in puppet-masterless.
