### ISSUE TITLE
Proposal: pre-processors

### ISSUE THREAD

**Issue by BSick7** [hashicorp/packer#5342]
Many in the community are looking for a way to source a vagrant box to build on top.
As noted in https://github.com/hashicorp/packer/issues/869, people have come up with different workarounds, but none that are first-class.

My proposal is to add the notion of pre-processors.
To specifically solve the above problem, a `vagrant-cloud` pre-processor would be configured as follows:
```
{
  "pre-processors": [
    {
      "type": "vagrant-cloud",
      "box": "ubuntu/trusty64",
      "box_version": "latest",
      "provider": "virtualbox",
      "local_box": "./boxes/virtualbox/ubuntu-trusty64.box",
      "extract": "./boxes/virtualbox/ubuntu-trusty64/"
    }
  ]
}
```

This pre-processor would download the latest `ubuntu/trusty64` box into `./boxes/virtualbox/` directory, then extract the contents into `./boxes/virtualbox/ubuntu-trusty64/` directory.

Additionally, these properties would allow for templates (e.g. `{{user ...}}`)

If this is already being worked on, I would love to help.
If it's not, does this align with the packer vision.  
Any suggestions or comments?

**Comment by lfarnell** [comment]
Another interesting use case I believe for pre-processors would be templating of config files and scripts. This is something many people have ask for over the years

**Comment by darkn3rd** [comment]
There are more use cases than vagrant boxes, definitely would love this.  I think this is a standard feature in image packagers like deb or rpm.

**Comment by BSick7** [comment]
I've actually been thinking more about this functionality.
Instead of `pre-processors`, it may make more sense to call it `sources`.
In my original example, I am providing a source artifact to derive the build.
Another case I thought of today was sourcing a guest additions iso which could be pulled remotely.

The one thing that may not feel consistent with existing packer is that several builders already have a "built-in" mechanism for sourcing remote files (but only for the source path).

Any thoughts @mwhooker?

**Comment by rupertnash** [comment]
What about being able to use artefacts from another Packer template as the basis for the current template? E.g. create a base image in one template and then have multiple other images built on top.

**Comment by grv87** [comment]
@rupertnash, I think that the case you described is too broad, and general build tools like Make or Gradle could handle it better.

**Comment by SwampDragons** [comment]
The referenced PR above includes my thinking on this, but ultimately I don't think that pre-processors make sense to include at this point. In the particular case of a "vagrant" pre-processor, I am currently working on a "vagrant" builder that I think will satisfy this need more elegantly.  In the case of a templating pre-processor, I think there is probably a better way of handling that. I'm closing this for now, but I appreciate all of your input.
