### ISSUE TITLE
postprocessor 'docker-push' to aws ecr fails for tagged images from docker and docker-tag  

### ISSUE THREAD

**Issue by DALDEI** [hashicorp/packer#5346]
FOR BUGS:

Describe the problem and include the following information:

- Packer version from `packer version`
   Packer v1.1.09

- Host platform
  Linux idell.in.calldei.com 4.11.4-1.el7.elrepo.x86_64 #1 SMP Wed Jun 7 12:18:44 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux

- Debug log output from `PACKER_LOG=1 packer build template.json`.
  https://gist.github.com/DALDEI/90e42146f0d6bdf4be036e4af47fd056

- The _simplest example template and scripts_ needed to reproduce the bug.
  https://gist.github.com/DALDEI/e8e9e80b54fe58980ce9d544d65d5ee5
  
  
Pushing a created and tagged image to ecr fails if tag is != ""

The problem appears to be caused by inconsistent output of the "docker" command.
"docker create"  returns the container ID raw.
"docker commit" is returning the container id prefixed with "sha256:"

in builder/docker/driver_docker.go the commit is done with "docker commit ..."
The return value is space trimmed but otherwise untouched.
When the value is "sha256:....."    'docker push' is called -- this doesnt work, as its interpreted as <repository>:<tag>

I believe somewhere the name of the container instead of its ID is needed to be injected.  
possibly in post-processor/docker-tag/post-process.go  the tag is appended ? 

The logs show after the docker-tag that the Id is now the sha266:xxx string instead of repository:tag

----
```

    docker (docker-push): Pushing: sha256:6ecc1a3d20d59d4babc471c14e799b8e13b0228a64f7dca994a2670f893f51e1
2017/09/14 22:20:03 ui:     docker (docker-push): Pushing: sha256:6ecc1a3d20d59d4babc471c14e799b8e13b0228a64f7dca994a2670f893f51e1
2017/09/14 22:20:03 packer: 2017/09/14 22:20:03 Executing: /usr/bin/docker [push sha256:6ecc1a3d20d59d4babc471c14e799b8e13b0228a64f7dca994a2670f893f51e1]
2017/09/14 22:20:03 ui:     docker (docker-push): An image does not exist locally with the tag: sha256
    docker (docker-push): An image does not exist locally with the tag: sha256
2017/09/14 22:20:03 ui:     docker (docker-push): The push refers to a repository [docker.io/library/sha256]
    docker (docker-push): The push refers to a repository [docker.io/library/sha256]
2017/09/14 22:20:03 ui:     docker (docker-push): Logging out...
```
--------

**Comment by rickard-von-essen** [comment]
You're missing in level of `[ ]` in your pos-processor section to make it a sequence. See the post-processor docs.

**Comment by DALDEI** [comment]
Thank you !!! Worked great.
