### ISSUE TITLE
Issue with packer 1.1.0 and puppet masterless

### ISSUE THREAD

**Issue by KornM** [hashicorp/packer#5347]
Error using puppet masterless provisioner: 
Build 'amazon-ebs' errored: Error uploading manifest dir: scp: /tmp/packer-puppet-masterless/manifests/site.pp: Permission denied
Other provisioner, like shell / inline are working fine.

Packer Version: 1.1.0
Host: Ubuntu 16.04 64bit
Sorry, can use gist due to company policy (to whatever reason)

Output of packer run with debug:
[output.txt](https://github.com/hashicorp/packer/files/1305869/output.txt)

Simple script to reproduce:
[testcases.zip](https://github.com/hashicorp/packer/files/1305878/testcases.zip)

**Comment by mwhooker** [comment]
thanks for the report.

Just to confirm, this worked in versions prior to 1.1.0?

**Comment by mwhooker** [comment]
I think I found the issue -- the command to make the staging directory no longer has sudo in front of it

**Comment by mwhooker** [comment]
@KornM You can work around this for now by setting `"prevent_sudo": true` in the puppet json. I believe this is because of a backwards incompatible change what we didn't document sufficiently.

**Comment by mwhooker** [comment]
Thanks for the great repro. This is fixed on master and will be released in packer 1.1.1

**Comment by mikouaj** [comment]
Provisioning AMIs with puppet-masterless without sudo won't work, for a valid workaround I added shell provisioner to ensure proper staging directory permisions i.e. :
`     {
       "type" : "shell",
       "inline" : [
         "mkdir -p /tmp/packer-puppet-masterless/manifests",
         "chmod -R 777 /tmp/packer-puppet-masterless"
       ]
     }`

**Comment by KornM** [comment]
Thank you!!

**Comment by sejames** [comment]
@mikouaj , I had to add the following for modules that we are copying across

`{ "type" : "shell", "inline" : [ "mkdir -p /tmp/packer-puppet-masterless/manifests", "mkdir -p /tmp/packer-puppet-masterless/module-0", "chmod -R 777 /tmp/packer-puppet-masterless" ] },`

 thanks this worked for me after upgrading from packer 0.12.3 to 1.1.0

**Comment by fabiendelpierre** [comment]
I hit this issue yesterday.

@mikouaj @sejames FYI I didn't come here until now and tried similar workarounds, but after creating `/tmp/packer-puppet-masterless/module-0` and setting permissions on it, the build then complains about `/tmp/packer-puppet-masterless/module-1`... and so forth.

@mwhooker FYI using `prevent_sudo` does get around the issue, but then Puppet runs as a non-root user, and all kinds of things break during the Puppet run.

So I look forward to 1.1.1 and have downgraded to 1.0.4 for now. Any idea when 1.1.1 might come out?

**Comment by mwhooker** [comment]
@fabiang today!

**Comment by fabiendelpierre** [comment]
Great news, thank you!

You tagged the wrong guy by the way 😄

**Comment by mwhooker** [comment]
lol, github autocorrect is useless 😜
