### ISSUE TITLE
Is docker-dockerfile available?

### ISSUE THREAD

**Issue by karthik101** [hashicorp/packer#5348]
Is post-processor-docker-dockerfile still available?
i get error:
Failed to initialize build 'docker': post-processor type not found: docker-dockerfile

how can i include this feature? All i want is to create a user.
I use Packer v1.1.0

**Comment by rickard-von-essen** [comment]
You are looking for this. It has never been part of Packer. The same functionality is supplied by [changes](https://www.packer.io/docs/builders/docker.html#changes).

**Comment by karthik101** [comment]
Silly me, Thanks! :D
