### ISSUE TITLE
Packer builder for RHV/Ovirt

### ISSUE THREAD

**Issue by srjayep** [hashicorp/packer#5350]
I have not found a RHV builder type for packer , wondering anyone wrote a custom builder or worked around it to create a RHV Linux template using Packer.

**Comment by rickard-von-essen** [comment]
I think the qemu builder can be used to build images for RHEV/ovirt. Do you see any functionality missing for doing that?

**Comment by gangadhar01a** [comment]
Hello @srjayep . Are you able to use QEMU builder for RHEV?

**Comment by SwampDragons** [comment]
Closed due to inactivity.
