### ISSUE TITLE
Feature Request: vsphere-template post processor to work with local builders

### ISSUE THREAD

**Issue by jonmosco** [hashicorp/packer#5354]
It curently looks like the vsphere-template will only work with esxi in the vsphere-iso builder, and not with the local VMware products (fusion, etc).  

2017/09/17 09:28:13 [INFO] (telemetry) Starting post-processor vsphere-template
==> ubuntu-16.04-x86_64-vmware: Running post-processor: vsphere-template
2017/09/17 09:28:13 [INFO] (telemetry) ending vsphere-template
2017/09/17 09:28:13 [INFO] (telemetry) found error: Unknown artifact type, can't build box: mitchellh.vmware
2017/09/17 09:28:13 Deleting original artifact for build 'ubuntu-16.04-x86_64-vmware'
2017/09/17 09:28:16 ui error: Build 'ubuntu-16.04-x86_64-vmware' errored: 1 error(s) occurred:

* Post-processor failed: Unknown artifact type, can't build box: mitchellh.vmware
2017/09/17 09:28:16 Builds completed. Waiting on interrupt barrier...
2017/09/17 09:28:16 machine readable: error-count []string{"1"}
2017/09/17 09:28:16 ui error:
==> Some builds didn't complete successfully and had errors:
2017/09/17 09:28:16 machine readable: ubuntu-16.04-x86_64-vmware,error []string{"1 error(s) occurred:\n\n* Post-processor failed: Unknown artifact type, can't build box: mitchellh.vmware"}
2017/09/17 09:28:16 ui error: --> ubuntu-16.04-x86_64-vmware: 1 error(s) occurred:

* Post-processor failed: Unknown artifact type, can't build box: mitchellh.vmware
2017/09/17 09:28:16 ui:
==> Builds finished but no artifacts were created.
Build 'ubuntu-16.04-x86_64-vmware' errored: 1 error(s) occurred:

* Post-processor failed: Unknown artifact type, can't build box: mitchellh.vmware

==> Some builds didn't complete successfully and had errors:
--> ubuntu-16.04-x86_64-vmware: 1 error(s) occurred:

* Post-processor failed: Unknown artifact type, can't build box: mitchellh.vmware

==> Builds finished but no artifacts were created.
2017/09/17 09:28:16 waiting for all plugin processes to complete...

I was previously using pvmomi independently of Packer and would love to be able to use this post-processor with any of the artifacts created with the Vsphere builder.

<img width="789" alt="screen shot 2017-09-17 at 9 43 50 am" src="https://user-images.githubusercontent.com/1970496/30521377-c290f69a-9b8c-11e7-9968-fd87c6c91b6e.png">

Jon

**Comment by csandertch** [comment]
+1

This would be great.

An optional parameter for the vpshere post-processor to mark as template would be also great.

**Comment by bugbuilder** [comment]
I'm thinking that the best way to accomplish this is use the vsphere and vsphere-template together (in the vmware-vmx case, probably the vmware-iso in not remote mode too), the template json will look like this:
```
{
"builders":[
      {
         "type":"vmware-vmx",
          ...
      }
   ],

"post-processors":[
      {
         "type":"vsphere",
          ...
      },
      {
         "type":"vsphere-template",
          ...
      }
   ]
}
```
I need to verify how the ovftool used by the vsphere post-processor is uploading the VM to vSphere and then do some testing. 

As always all feedback is welcome.

**Comment by bugbuilder** [comment]
> I need to verify how the ovftool used by the vsphere post-processor is uploading the VM to vSphere and then do some testing.

Probably change the vsphere post-processor to use govmomi to avoid the ovftool is a better idea. I'm still thinking...

**Comment by csandertch** [comment]
I'm not sure if using vpshere and vsphere-template together is a good way, as post-processor are using artifacts from the builder. So if the builder is generating a local file vsphere PP can upload it, however vsphere-template is using the same local artifact. Vsphere-template has no knowledge about where vsphere PP have uploaded the artifact before. 

But correct me if I´m wrong ;)

**Comment by bugbuilder** [comment]
Yep, you are correct, but remember that the artifact could change beteween post-processor, for example the vsphere post-processor could add the remote path as result and then the vsphere-template could use it if it's not running in esxi remote.

I think if we have two post-processor is more flexible, because if you use a local builder you need to push that VM to vSphere (vsphere-post-processor) and then mark that VM as template (vsphere-template-post-processor) on the other hand if you use a remote esxi you'll only need to mark the VM as template (vsphere-template-post-processor)

**Comment by bugbuilder** [comment]
But I still thinking... move the vsphere-template-post-processor as option in the vsphere-processor.... also could be :)..

**Comment by csandertch** [comment]
Ok if the artifact can change, then both ways have their charme ;) ...
If you need someone to challenge your thoughts with....

**Comment by bugbuilder** [comment]
> I'm thinking that the best way to accomplish this is to use the vsphere and vsphere-template together

is not the best way is the faster way...

@csandertch if you have another idea, please let me know

**Comment by jonmosco** [comment]
I was having trouble getting the post processor to recognize the artifact, but had some issues because of the path assumptions:

// We will use the virtual machine created by vmware-iso builder
func findRuntimeVM(cli *govmomi.Client, dcPath, name string) (*object.VirtualMachine, error) {
	si := object.NewSearchIndex(cli.Client)
	fullPath := path.Join(dcPath, "vm", "Discovered virtual machine", name)

If there was a way to always pass in the path and the artifact name and have it work like the vsphere post-processor (just specific snippets below):

{  
   "type": "vsphere-template",
   "folder": "/packer-templates/os/distro-7"
}

 {
   "type": "vsphere",
   "vm_name": "{{user `post_vm_template_name`}}",
    "vm_folder": "Templates",
}

and then in theory, it could look like this:

{  
   "type": "vsphere-template",
    "vm_name": "{{user `post_vm_template_name`}}",
    "vm_folder": "Templates",
}

It can find the artifact once its added to the post-processor as well, just needs more work to be able to actually find it due to paths:

var builtins = map[string]string{
	"mitchellh.vmware": "vmware",
        "mitchellh.vmware-esx": "vmware",
}


Just some idea, and I could be way off on this, just tried to start working on a patch.  Would be willing to test (have a lab available for this if needed).

Jon

**Comment by bugbuilder** [comment]
@jonmosco thanks for your feedback. I think that this weekend I'll have time to work on this, if you have any update please share it :)

**Comment by bugbuilder** [comment]
This is my [first approach](https://github.com/bennu/packer/tree/local-vsphere-template) to accomplish this feature, I tested this on Workstation 12 Pro.

To be able to use the `vsphere-template` with local builders you'll need to use a collection of post-processors that look like this:
```
 "post-processors":[
      [{
         "type":"vsphere",
          ...
      },
      {
         "type":"vsphere-template",
          ...
      }]
   ]
```
This weekend I'll try to test this on Fusion and Player, @jonmosco @csandertch could you help me with testing before making a PR?

**Comment by jonmosco** [comment]
Yea definitely.  

Jon

**Comment by jonmosco** [comment]
Started testing today and it looks like it gets stuck trying to upload the artifact:

2017/09/21 09:38:02 packer: 2017/09/21 09:38:02 Writing VMX to: output-ubuntu-16.04-x86_64/packer-ubuntu-16.04-x86_64.vmx
2017/09/21 09:38:02 ui: ==> ubuntu-16.04-x86_64: Skipping export of virtual machine (export is allowed only for ESXi and the format needs to be specified)...
2017/09/21 09:38:02 packer: 2017/09/21 09:38:02 Executing: /Applications/VMware Fusion.app/Contents/Library/vmrun [-T fusion list]
==> ubuntu-16.04-x86_64: Skipping export of virtual machine (export is allowed only for ESXi and the format needs to be specified)...
2017/09/21 09:38:02 packer: 2017/09/21 09:38:02 stdout: Total running VMs: 0
2017/09/21 09:38:02 packer: 2017/09/21 09:38:02 stderr:
2017/09/21 09:38:02 [INFO] (telemetry) ending vmware-iso
2017/09/21 09:38:02 ui: ==> ubuntu-16.04-x86_64: Running post-processor: vsphere
2017/09/21 09:38:02 [INFO] (telemetry) Starting post-processor vsphere
==> ubuntu-16.04-x86_64: Running post-processor: vsphere
2017/09/21 09:38:02 ui:     ubuntu-16.04-x86_64 (vsphere): Uploading output-ubuntu-16.04-x86_64/packer-ubuntu-16.04-x86_64.vmx to vSphere
    ubuntu-16.04-x86_64 (vsphere): Uploading output-ubuntu-16.04-x86_64/packer-ubuntu-16.04-x86_64.vmx to vSphere
2017/09/21 09:38:02 packer: 2017/09/21 09:38:02 Starting ovftool with parameters: --acceptAllEulas --name=ubuntu-16.04-x86_64 --datastore=datastore --noSSLVerify=true --diskMode=thin --vmFolder=packer_templates --overwrite output-ubuntu-16.04-x86_64/packer-ubuntu-16.04-x86_64.vmx vi://USERNAME:<password>@HOST

**Comment by bugbuilder** [comment]
It's strange because I didn't change the actual behavior... it's look like a `vsphere ` post-processor issue or network issue, if you check your vSphere you can see the uploading?.  Could you try with the current packer release? also it would be great if you can share your packer log and your template in gist.

**Comment by jonmosco** [comment]
Yes, my mistake (password was updated).  Here is the gist of the packer template: https://gist.github.com/jonmosco/b742866f24c3426aad9859a310fd665a

After making the change, I am getting the problem where it can not find the VM and is looking at the "Discovered Virtual Machines" folder:

https://gist.github.com/jonmosco/00fba48ca6b3158ed013b62e39eadec5

**Comment by bugbuilder** [comment]
You need to past the post-processor as a collection:
 ```
"post-processors": [
    [ {
      "type": "vsphere",

      "cluster": "FP",
      "datacenter": "DC",
      "datastore": "datastore",
      "disk_mode": "thin",
      "host": "host",
      "password": "{{user `vsphere_password`}}",
      "username": "root",
      "vm_name": "{{user `template_name`}}",
      "vm_folder": "packer_templates",
      "insecure": true,
      "overwrite": true
    },
    {
      "type": "vsphere-template",

      "password": "{{user `vsphere_password`}}",
      "username": "root",

      "host": "hostname",
      "datacenter": "DC",
      "insecure": true
    } ]
  ]
```

**Comment by jonmosco** [comment]
Yes, the gist I provided has just that.

**Comment by bugbuilder** [comment]
I saw you gist and I didn't see the brackets **[ ]** surrounded the post-processors. Check my example above.

**Comment by jonmosco** [comment]
Oh yes, my bad.  Here is the latest error then:

https://gist.github.com/jonmosco/544e300357596e4ef3753311b41ba7e0

**Comment by bugbuilder** [comment]
that look like your not using my packer version, Did you compile the correct branch (local-vsphere-template)???

**Comment by jonmosco** [comment]
Sorry, I guess I did not.  I just tried to build this, correct me if im wrong:

git checkout local-vsphere-template
Branch local-vsphere-template set up to track remote branch local-vsphere-template from origin.
Switched to a new branch 'local-vsphere-template'
go build -o bin/packer
$GOPATH/src/github.com/bennu/packer/bin/packer build -var 'vsphere_password=password' ubuntu/ubuntu-16.04-vmware-base.json

After this, I did another build and got the same error.

**Comment by bugbuilder** [comment]
Look weird to me... I'll update the source with log information to be sure that we are using the same version, but I cant do it in this moment, I'll ping you.

**Comment by jonmosco** [comment]
No problem, thank you.

**Comment by jonmosco** [comment]
Looks like I got the build working correctly, but now a different error:

https://gist.github.com/jonmosco/29e26f573a32dad1fa87b0fb18554aeb

**Comment by bugbuilder** [comment]
@jonmosco Could you share your ubuntu/ubuntu-16.04-vmware-base.json please

**Comment by jonmosco** [comment]
https://gist.github.com/jonmosco/95f724a7d4249a1cf046362669fa96fc

**Comment by bugbuilder** [comment]
@jonmosco Could you tell me the ouput if run $GOPATH/src/github.com/bennu/packer/bin/packer version

**Comment by jonmosco** [comment]
https://gist.github.com/jonmosco/491c05c0439184e0d3521d6ae03022d8

**Comment by bugbuilder** [comment]
Do you bother you if I share you my packer binary?

**Comment by jonmosco** [comment]
Sure, just hope it doesnt have a "remove from inventory" flag set for VCenter.... 😬

**Comment by jonmosco** [comment]
go version
go version go1.9 darwin/amd64

**Comment by bugbuilder** [comment]
Ok, I'll build with that version also can you do a pull and build again, I put some logs

**Comment by jonmosco** [comment]
https://gist.github.com/jonmosco/778549577a84ec205e7a3afbe7566b75

**Comment by bugbuilder** [comment]
Thats strage, because I didnt see the new log

**Comment by bugbuilder** [comment]
[this line](https://github.com/bennu/packer/blob/local-vsphere-template/post-processor/vsphere-template/post-processor.go#L90)

**Comment by jonmosco** [comment]
`┌[jmosco@ka.forkedprocess.com]-(~/code/go/src/github.com/bennu/packer)(git)[remotes/origin/local-vsphere-template(369)|✔ ]
└>`

Is this the correct branch to be building from?

**Comment by bugbuilder** [comment]
yep...

**Comment by bugbuilder** [comment]
Could you check the line above?

**Comment by jonmosco** [comment]
Which line above?  In the source directory?

git pull origin local-vsphere-template
From https://github.com/bennu/packer
 * branch              local-vsphere-template -> FETCH_HEAD
Updating 644ac5b3..24a8fddf
Fast-forward
 post-processor/vsphere-template/post-processor.go | 1 +
 post-processor/vsphere/post-processor.go          | 2 ++
 2 files changed, 3 insertions(+)

**Comment by bugbuilder** [comment]
Lets build:
```
mkdir -p new-foder && cd new-foder
git clone https://github.com/bennu/packer.git
cd packer
git checkout local-vsphere-template
docker run --rm -v $(pwd):/go/src/github.com/hashicorp/packer -w /go/src/github.com/hashicorp/packer -e GOARCH=amd64 -e GOOS=darwin -e CGO_ENABLED=0 golang:1.8.3-alpine go build -o bin/packer
```

**Comment by jonmosco** [comment]
Better error output this time, wonder why my build was not doing this?

2017/09/22 13:54:44 ui:     ubuntu-16.04-x86_64 (vsphere-template): Marking as a template...
    ubuntu-16.04-x86_64 (vsphere-template): Marking as a template...
2017/09/22 13:54:47 ui error: ==> ubuntu-16.04-x86_64 (vsphere-template): A specified parameter was not correct.
==> ubuntu-16.04-x86_64 (vsphere-template): path
==> ubuntu-16.04-x86_64 (vsphere-template): A specified parameter was not correct.
==> ubuntu-16.04-x86_64 (vsphere-template): path
2017/09/22 13:54:47 [INFO] (telemetry) ending vsphere-template
2017/09/22 13:54:47 [INFO] (telemetry) found error: A specified parameter was not correct.
path
2017/09/22 13:54:47 ui error: Build 'ubuntu-16.04-x86_64' errored: 1 error(s) occurred:

* Post-processor failed: A specified parameter was not correct.
path
2017/09/22 13:54:47 Builds completed. Waiting on interrupt barrier...
2017/09/22 13:54:47 machine readable: error-count []string{"1"}
2017/09/22 13:54:47 ui error:
==> Some builds didn't complete successfully and had errors:
2017/09/22 13:54:47 machine readable: ubuntu-16.04-x86_64,error []string{"1 error(s) occurred:\n\n* Post-processor failed: A specified parameter was not correct. \npath"}
2017/09/22 13:54:47 ui error: --> ubuntu-16.04-x86_64: 1 error(s) occurred:

* Post-processor failed: A specified parameter was not correct.
path
Build 'ubuntu-16.04-x86_64' errored: 1 error(s) occurred:

* Post-processor failed: A specified parameter was not correct.
2017/09/22 13:54:47 ui:
==> Builds finished but no artifacts were created.
path

<img width="667" alt="screen shot 2017-09-22 at 1 55 01 pm" src="https://user-images.githubusercontent.com/1970496/30757786-e5020f10-9f9d-11e7-91f4-e9f2031c20c0.png">

**Comment by bugbuilder** [comment]
> Better error output this time, wonder why my build was not doing this?
Probably dependency and path problems, I bet you that you have packer in your gopath.

Could you change your vsphere-template and remove the datacenter?

**Comment by bugbuilder** [comment]
Can you tell me the topology of your vCenter for example how many hosts do you have in your cluster, storages...

**Comment by bugbuilder** [comment]
I can continue with this now but I'll back in a few hours, could you share me the full log when you end with your tests please

**Comment by jonmosco** [comment]
This cluster is used for testing and has one DataCenter, one Cluster, and 2 hosts.  Attached is 2 NAS via NFS presenting 2 datastores.

VCenter 5.5 Standard

**Comment by bugbuilder** [comment]
@jonmosco Could you show me where the `vsphere` post-processor is uploading the local VM, I think that my problem is how I deduce the vmx path.

**Comment by jonmosco** [comment]
It us putting it in "vm_folder": "packer_templates", but looking in
VCenter, that is a top level object, so its path is not tied to that
specific datastore...

**Comment by jonmosco** [comment]
`"datastore": "datastore",
"disk_mode": "thin",
"host": "vc01.forkedprocess.com",
"password": "{{user `vsphere_password`}}",
"username": "{{user `vsphere_user`}}",
"vm_name": "{{user `template_name`}}",
"vm_folder": "packer_templates",`

**Comment by bugbuilder** [comment]
I think I find the problem... give a few minutes... I'm testing..

**Comment by bugbuilder** [comment]
Yep I found it! if you change the "name" attribute in the builder section for vm_name the post-precessor will works :). Let me think how to fix this, could you try if that what I'm saying its true?

**Comment by jonmosco** [comment]
Yes!  That did it!  Now just have to put the "folder" back in and see if it can be moved.  Not sure why that "name" was not "vm_name" looking back through the documentation..its not even listed as an attribute, but I have been using it for some time now.  Great find.

**Comment by bugbuilder** [comment]
I updated the source so now could use name or vm_name without problems :) thanks for you testing you helped me a lot!

**Comment by bugbuilder** [comment]
Now I have to test if this could work with .ova and .ovf files... Could you still help me?

**Comment by jonmosco** [comment]
Yes, definitely.  Having this feature saves me a lot of time.

Thank you for getting this working!  Very much appreciated.

**Comment by jonmosco** [comment]
Do you need me to do anymore testing for this?

**Comment by bugbuilder** [comment]
Hi @jonmosco all testing is welcome, if you found an issue please let me know I'll happy to try to fix it.

**Comment by jonmosco** [comment]
I'm just checking in to see where this stands.  I'm using the patch you provided, but don't want to have to maintain a fork.  Is there anything I can do to help this along to be added to stable?

**Comment by bugbuilder** [comment]
This feature will be able at packer v1.2.0. PR #5380, you'll need to wait a bit.

**Comment by jonmosco** [comment]
Ok, perfect, thank you.

**Comment by f-roscher** [comment]
Hi @bugbuilder, thanks for this feature. I do currently face the error "A specified parameter was not correct: path". As I understood @jonmosco had the same and it had been fixed. I do use 'vm_name' within the builder section already. Packer version 'Packer v1.1.1-dev (50904064)', pulled branch local-vsphere-template today (b754b715191920cc40e2a2e69e20b2f491cf903e)
Any help would be appreciated including a little hint to search by myself. If you need debugging output, I will provide it promptly. Post processor configuration attached: https://gist.github.com/f-roscher/388f460a4a3302a3a226ed06d929af9f

**Comment by jonmosco** [comment]
Did you pull those changes and rebuild so your packer version
returns v1.1.2-dev ?

Jon

**Comment by f-roscher** [comment]
I just noted we spread the communication across this issue and a corresponding pull request https://github.com/hashicorp/packer/pull/5380. Let's have a short version of the other comment here - just for the record: The error does not occur with the youngest version of that branch Packer v1.1.2-dev (b754b715).
