### ISSUE TITLE
More complete examples in the documentation needed.

### ISSUE THREAD

**Issue by jeffreydwalter** [hashicorp/packer#5358]
The Packer documentation does a decent job of explaining all of the various options associated with builders, provisioners, etc., but does a poor job of explaining how to use them.

For example, provisioners have 13 options at the time of this writing, yet there are only 3 very trivial example code sections on the whole topic. While I realize it's not practical to explicitly enumerate every possible combination of options, it would be REALLY beneficial to have more "real world" and advanced usage examples. The same applies to the various other configuration areas (builders, post-processors, etc.)

**Comment by SwampDragons** [comment]
I've started creating some toy examples here: https://github.com/SwampDragons/packer-examples

Are there any specific combos you'd like to see created?  Once that repository is more mature, I'll start moving the examples into docs.

**Comment by jbrowder2** [comment]
If you could go into detail about using the combo of builders, provisioners and post processors I think that would be a welcomed addition to the documentation.

**Comment by jeffreydwalter** [comment]
Ideally, it's not really scenario-based, but more just how each and every property is used, where it goes in the config json.

One additional thing which took me some time to figure out was how to specify an array of values in a variable. Having to include them as a comma separated string is pretty unintuitive.

**Comment by SwampDragons** [comment]
I completely agree that every single property should have a documented usage example. This is going to have to be a community effort; if you see something you use is lacking in this area, please please make a PR.

**Comment by jeffreydwalter** [comment]
I'm happy to contribute where I can. Part of my problem is that it's not clear how every option works and where it should go. So, I can only really help out with the things I've had to figure out the hard way.

If you feel more comfortable starting with the examples, you could create more of them and the community can infer from them and contribute that wisdom back to the official docs.

**Comment by mwhooker** [comment]
Want to drop this link here: https://www.packer.io/community-tools.html

these are a bunch of complete packer scripts from the community, and should be helpful in demonstrating how to packer is used in the real world

**Comment by mwhooker** [comment]
@jeffreydwalter could you go more in to detail about what information you need?

> Ideally, it's not really scenario-based, but more just how each and every property is used, where it goes in the config json.

I would love to get a concrete example of what you're looking for.

The options for every builder/provisioner etc go inside of the relevant builder or provisioner.

You can get the base structure from https://www.packer.io/docs/templates/index.html

**Comment by gowthamakanthan** [comment]
@SwampDragons, please let me know where i can some examples and documentation for vsphere.

**Comment by SwampDragons** [comment]
There are lots of examples for lots of builders available here: https://packer.io/community-tools.html
