### ISSUE TITLE
large file upload hits yamux deadline

### ISSUE THREAD

**Issue by alexhexabeam** [hashicorp/packer#5360]
Packer fails to upload large files with the file provisioner. I've seen it fail intermittently with files as small as 5GB, but for consistency I tested with a 20GB file. This is not a network problem, as I can reliably transfer the file using scp or rsync.

Steps to reproduce:
1. Create a large file. I used mkfile to do this:
`mkfile -n 20g bigfile`
2. Use packer to attempt to upload that file using a file provisioner:
`packer build --var "uploadpath=$(pwd)/bigfile" packer_upload_failure_test.json`

Template: https://gist.github.com/alexhexabeam/1c2cafa2ca555b2f95789f9793c013cb
Log: https://gist.github.com/alexhexabeam/614878674e855a40249badbf5d09530d

Tested with packer versions 1.0.2, 1.0.4, 1.1.0, on OSX host, uploading to a CentOS 7 AWS instance.

**Comment by mwhooker** [comment]
hmm, I think this might be in our RPC logic.

here's the text from the log

```
2017/09/19 17:20:26 ui error: --> amazon-ebs: unexpected EOF
2017/09/19 17:20:26 ui:
==> Builds finished but no artifacts were created.
2017/09/19 17:20:26 [ERR] yamux: Failed to write body: write unix ->/var/folders/56/9sz98p851xqdzx17pkth42ch0000gn/T/packer-plugin214252916: write: broken pipe
2017/09/19 17:20:26 packer: 2017/09/19 17:20:26 [ERR] yamux: keepalive failed: i/o deadline reached

==> Some builds didn't complete successfully and had errors:
2017/09/19 17:20:26 [ERR] 'uploadData' copy error: session shutdown
2017/09/19 17:20:26 Error in Ui RPC call: connection is shut down
```

We might just need to periodically send an update to the UI letting us know that we're still transferring

**Comment by mwhooker** [comment]
probably not related, but worth pointing out a few other issues with similar yamux errors
https://github.com/hashicorp/packer/issues/3378
https://github.com/hashicorp/packer/issues/4214

**Comment by boraozgen** [comment]
Is there any update on this? I am receiving this error during long provisioning sessions.

**Comment by SwampDragons** [comment]
Not yet, sorry. We'll update when we get a chance, or we can point you at code that's the possible culprit if you want to take a look yourself.

**Comment by SwampDragons** [comment]
Do people still receive this issue? Now that we send updates to the progress bar I'm wondering if this has been resolved.

**Comment by SwampDragons** [comment]
Closing because I never heard back. If users still hit this issue, let's open a new one with new information.
