### ISSUE TITLE
Hyper-V ISO builder needs to disable & delete automatic checkpoints before running Vagrant postprocessor

### ISSUE THREAD

**Issue by PatrickLang** [hashicorp/packer#5371]
Hyper-V added a new feature that automatically takes checkpoints of VMs when they're started. When you stop the VM, it's deleted. [Link](https://blogs.technet.microsoft.com/virtualization/2017/04/20/making-it-easier-to-revert/). This causes a problem for Packer because when the box file is created - it includes a copy of the VM configuration. If that config has a checkpoint but the files aren't copied into the box, then importing it will fail in Vagrant.

My proposed fix is to automatically disable the automatic checkpoints in the `hyperv-iso` builder to make it deterministic and not carry extra checkpoints that weren't intended in the original Packer build scripts. I would scope it to check for the new option first, and only change it if it's present after creating the VM but before starting it.

eg:

```powershell
if ((get-command set-vm).Parameters["AutomaticCheckpointsEnabled"]) { 
  set-vm -AutomaticCheckpointsEnabled $false
}
```

### Steps to reproduce

1. Build [Packerfile](https://github.com/StefanScherer/packer-windows/blob/my/windows_2016_insider.json) - `packer build -only=hyperv-iso .\windows_2016_insider.json`
1. `vagrant box add --name windows_2016_insider windows_2016_insider_hyperv.box`
1. `vagrant init windows_2016_insider`
1. `vagrant up`
### Expected behavior
VM should have started

### Actual behavior
```none
Bringing machine 'default' up with 'hyperv' provider...
==> default: Verifying Hyper-V is enabled...
==> default: Importing a Hyper-V instance
    default: Please choose a switch to attach to your Hyper-V instance.
    default: If none of these are appropriate, please open the Hyper-V manager
    default: to create a new virtual switch.
    default:
    default: 1) HvsiIcs
    default: 2) DockerNAT
    default: 3) nat
    default: 4) Ethernet
    default: 5) Default Switch
    default:
    default: What switch would you like to use? 4
    default: Cloning virtual hard drive...
    default: Creating and registering the VM...
An error occurred while executing a PowerShell script. This error
is shown below. Please read the error message and see if this is
a configuration error with your system. If it is not, then please
report a bug.

Script: import_vm_vmcx.ps1
Error:

"Missing Checkpoint present."
```

The box contains both a vhdx and avhdx:

```none
-a----        9/21/2017  11:55 AM        4194304 WindowsServer2016Insider.vhdx
-a----        9/21/2017  11:56 AM    12788432896 WindowsServer2016Insider_4082B281-E871-442B-8574-91A5D8F4E935.avhdx
```

### Version Information

- Packer version - Packer v1.1.0
- Host platform - Windows 10 Insider - 16291.0.amd64fre.rs3_release.170912-1708. Although this would apply to any Windows 10 insider build since around May

### References

https://github.com/hashicorp/vagrant/issues/8988

**Comment by PatrickLang** [comment]
@taliesins and @StefanScherer do you agree with this approach? Got a PR attached

**Comment by StefanScherer** [comment]
@PatrickLang That seems good to me. I haven't encountered this as my HyperV host was a Win2016 14393, but it is good to take care for the upcoming Win10/2016 releases 👍

**Comment by PatrickLang** [comment]
@StefanScherer now that I think about it, the setting could be different on Windows 10 vs Windows Server version 1709. It was intended for desktop users. I'll confirm with @scooley to see if it's different.

**Comment by mwrock** [comment]
Definitely a good idea!
