### ISSUE TITLE
ppc64le releases

### ISSUE THREAD

**Issue by knightsamar** [hashicorp/packer#5372]
- Packer version `v1.1.0`
- Host platform `ppc64le`

Where are the packer releases for Linux on ppc64le platform? I didn't find it on https://releases.hashicorp.com/packer/1.1.0/

Last time I opened an issue (#5108) about compilation issues, I was given a link to a built and signed file for that version. Now that a new version is out, I want to get it. If it's already built and signed somewhere, I would like to get it from there rather than building it.

Thank you.

**Comment by mwhooker** [comment]
hmm, sorry about that. I don't know why I didn't add it as a build target. Added in 339d768420e6b83dad34c8d4d8ee6c105c7491e0

future releases will now always have builds for ppc64le.
[linux_ppc64le.zip](https://github.com/hashicorp/packer/files/1331160/linux_ppc64le.zip)
