### ISSUE TITLE
PowerShell init.ps1 script not working due to built-in env variables not passed properly

### ISSUE THREAD

**Issue by kenwan12** [hashicorp/packer#5391]
See below pls :-)

On AWS
with packer v0.11.0

with the provisional part of the template.json as :-
. . .
    "provisioners": [
        {
            "type": "powershell",
            "script": "init.ps1"
        }
    ]
. . .

Thanks

Ken

**Comment by kenwan12** [comment]
```
$ packer version
Packer v0.11.0
```
packer.error attached which showed
the env vars passed as

```
'powershell "& { $env:PACKER_BUILDER_TYPE="amazon-ebs"; $env:PACKER_BUILD_NAME="base-ami"; c:/Windows/Temp/script.ps1; exit $LastExitCode}"'
```
which should be something like

```
'powershell "& { $env:PACKER_BUILDER_TYPE=\"amazon-ebs\"; $env:PACKER_BUILD_NAME=\"base-ami\"; c:/Windows/Temp/script.ps1; exit $LastExitCode}"'
```

Thanks

Ken

[packer.error.txt](https://github.com/hashicorp/packer/files/1336739/packer.error.txt)

**Comment by DanHam** [comment]
@kenwan12 This was fixed in v0.12.0 of Packer so upgrading should fix the issue for you.

Is there any reason you are still using v0.11.0?

**Comment by kenwan12** [comment]
Thx, will try and will close this ticket if successful :-)

I used this version on Mac sometime ago and forget to get the latest packer when restarting this project now.

Cheers

Ken

**Comment by mwhooker** [comment]
closing since this has been fixed. please submit a new issue with steps to reproduce if this is still an issue on the latest version of packer
