### ISSUE TITLE
[Feature Request/azure-arm] Add an option waiting time before power-off

### ISSUE THREAD

**Issue by giseongeom** [hashicorp/packer#5392]
Add an option waiting time between the last provisiong and power-off VM stage such as ``wait_time_before_poweroff``

**Background**
Recently, I started using packer at azure. BTW, 6 of 10 custom image built by packer launch failed, It's important for me to looking for a workaround.

When creating custom image, source Windows VM should sysprep and shutdown without problems. If not, new VM created from custom image goes hang, and shows it's status as  _creating_.  Finally, the VM failed with **OSProvisioningTimedOut** error.

Sometimes, packer proceeds to power-off / capture stage **too fast**.  Even after running `sysprep /oobe /generalize /shutdown /quiet`, the machine needs a few seconds  for proper shutdown. As of 1.1.0, packer just power-off VM when last provisioning succeeds.

**My workaround**
I added the `shell-local` provisioning step after sysprep.  Using `pause_before` option, I could customize the waiting time before power-off.

```json
    {
    "type": "powershell",
    "inline": [
      "if( Test-Path $Env:SystemRoot\\windows\\system32\\Sysprep\\unattend.xml ){ rm $Env:SystemRoot\\windows\\system32\\Sysprep\\unattend.xml -Force}",
      "& $Env:SystemRoot\\System32\\Sysprep\\Sysprep.exe /oobe /generalize /shutdown /quiet"
      ]
    },
    {
      "type": "shell-local",
      "execute_command": ["cmd.exe","/C","{{.Command}}"],
      "command": "echo provision is done %DATE% - %TIME%",
      "pause_before": "120s" 
   }
```
It would be helpful if packer support a way of controlling time before power-off VM

**Comment by boumenot** [comment]
A success rate of 40% is terrible.  This hasn't been my experience, but sysprep on Windows is usually a top pain point.  I don't think this is specific to Azure.  I think this is a sysprep issue, but I am happy to be corrected.

There was a PR (#5385) filed the other day with a very similar issue.  The PR updated the docs to help with this exact issue.  Would you please review the doc change, and see if it helps.

**Comment by giseongeom** [comment]
- The powershell code of PR (#5385) also works well. You can see the log [here](https://gist.github.com/giseongeom/586752c5af8c282a29e7ed498afa1dc3)
- Personally, I dislike _lengthy_ one-linear code :-)

**Comment by boumenot** [comment]
The examples for Azure show a much more robust method.  The provisioner will now poll for sysprep completion. See #5385 for details.
