### ISSUE TITLE
Contributing Testing Issue

### ISSUE THREAD

**Issue by flmmartins** [hashicorp/packer#5393]
Hello All,

I am contributing with packer code by solving  this issue: https://github.com/hashicorp/packer/issues/1796

Unfortunately (and I mean it) I am developing in my work machine which is a windows OS.

I runned $make everything went well, now I would like to run the binary I generated but I can't run it cause I can only run packer.exe and not a linux binary one.

Can anyone tell me how to generate a packer.exe file?
As soon as I test it, (hopefully) I can open a PR.

Best,

**Comment by mwhooker** [comment]
Hi @flmmartins,

Thanks for working on packer! Sorry you're having trouble building it. I think our docs might be a bit lacking.

You should be able to build it with `./scripts/build.ps1`. Make sure you have `env:PACKER_DEV` set to `1`.

You will need to first run:

```
go get github.com/mitchellh/gox
go get golang.org/x/tools/cmd/stringer
```

and make sure you have a recent version of go.

If you continue to have problems, please post here and I will reopen.
