### ISSUE TITLE
Docs updated needed

### ISSUE THREAD

**Issue by yellowmegaman** [hashicorp/packer#5397]
Hi there! 
https://www.packer.io/docs/builders/docker.html

`Dockerfiles` section contains

```
Dockerfiles can contain information such as exposed ports, shared volumes, and other metadata. Packer builds a raw Docker container image that has none of this metadata. You can pass in much of this metadata at runtime with docker run.
```

Which is obviously not true anymore, since metadata is already supported, and explained here:
https://www.packer.io/docs/builders/docker.html#basic-example-changes-to-metadata

Thanks in advance!

**Comment by mwhooker** [comment]
done in e497c6027
