### ISSUE TITLE
Docker builder - Set build-time as label

### ISSUE THREAD

**Issue by karthik101** [hashicorp/packer#5398]
I'm trying to add docker image build date as label:

```
  "builders":[{
        "type": "docker",
        "image": "centos:{{user `base-image-version`}}",
        "pull": true,
        "commit":true,
        "changes": ["USER {{user `create-user`}}","LABEL build-date=**date**", "WORKDIR /{{user `work-directory`}}"]
    }],
```

 The above doesn't work, how can i set this?

Thanks,
Karthik

**Comment by SwampDragons** [comment]
Can you try `{{timestamp}}` instead of date?

**Comment by mwhooker** [comment]
you might have better luck getting questions answered on the [mailing list](https://groups.google.com/forum/#!forum/packer-tool), since more users visit there, and github is mostly for code bugs. seems like the question has been answered, so closing
