### ISSUE TITLE
Oracle OCI builder ignores region value provided in OCI config file 

### ISSUE THREAD

**Issue by lhdomenech** [hashicorp/packer#5401]
With Packer version 1.1.0 (running on Darwin amd64), the Oracle OCI builder ignores region value from OCI config file (~/.oci/config). 

If a region is not specified in the packer template it always defaults to `us-phoenix-1`. This causes an authentication error when trying to use `us-ashburn-1`.

This can be worked around by adding the region parameter to the template however the documentation indicates that it is optional and defaults to the value in the OCI config file.

**Comment by prydie** [comment]
Thanks for the bug report @lhdomenech. #5407 should resolve this.
