### ISSUE TITLE
post-processor/amazon-import support other image types

### ISSUE THREAD

**Issue by rleibman** [hashicorp/packer#5404]
post-processor/amazon-import only supports OVA images, however according to this page
[http://docs.aws.amazon.com/vm-import/latest/userguide/vmimport-image-import.html](url) the following formats are supported: 

- Open Virtualization Archive (OVA), Virtual Machine Disk (VMDK), Virtual Hard Disk (VHD), and raw

Since my process uses kvm and not vmware, it's super easy to create raw images, but packer won't import them into aws. It should be fairly simple to add support for other extensions.

**Comment by rleibman** [comment]
Alternatively... write a post-processor that can convert from qemu files to vmdk

**Comment by mwhooker** [comment]
I think extending `amazon-import` to support raw images would be a good idea

**Comment by hagridaaron** [comment]
I'd be very interested in this!
