### ISSUE TITLE
Ansible command as output should be directly runnable in the shell

### ISSUE THREAD

**Issue by pjnagel** [hashicorp/packer#5412]
When the Ansible provisioner executes ansible, it prints a line like the following:

```
Executing Ansible: ansible-playbook --extra-vars packer_build_name=virtualbox-ovf packer_builder_type=virtualbox-ovf -i /tmp/packer-provisioner-ansible432653744 /home/r2d2/setup/lautus_ansible/tau.yml --private-key /tmp/ansible-key857554005 --limit tau-desktop-image.lautus.net
```

The above command-line is not suitable for pasting into a shell and re-running, due to the embedded spaces not being shell escaped, or quoted. The actual command that was executed is (note the quotes):

```
ansible-playbook --extra-vars "packer_build_name=virtualbox-ovf packer_builder_type=virtualbox-ovf" -i /tmp/packer-provisioner-ansible432653744 /home/r2d2/setup/lautus_ansible/tau.yml --private-key /tmp/ansible-key857554005 --limit tau-desktop-image.lautus.net
```

This makes it difficult to debug failing builds. One strategy for debugging  builds is to arrange for the build to pause, and then manually re-running the ansible command.

I am not sure whether this issue is specific to ansible builds, or whether this bug affects printing out of shell command-lines in general.

Packer version 1.1.0
Ubuntu 16.04.3 LTS

**Comment by mwhooker** [comment]
looks like we already do this for ansible-remote: https://github.com/hashicorp/packer/blob/master/provisioner/ansible/provisioner.go#L371

I don't immediately see why anisible-local doesn't print quotes, since the command string we print has the correct quoting:

https://github.com/hashicorp/packer/blob/master/provisioner/ansible-local/provisioner.go#L297-L311

**Comment by mwhooker** [comment]
oh oops, looks like this is for ansible-remote, and I misread the behavior initially. should be able to come up with a patch, but I can't test ansible-remote, so will need someone else to validate the patch

**Comment by mwhooker** [comment]
@pjnagel if you want to test #5414 I can merge

**Comment by pjnagel** [comment]
@mwhooker 

Thanks, I will test as soon as I have toolchain going to build packer from source.

However, it seems your patch only deals with escaping spaces That is a step forwards, and will solve my particular problem, so I will test your patch from that perspective. But shell escaping in general is a broader issue - commands may contain dollars, quotes etc. that also need to be escaped.

I don't know Go, but it seems like you need something like library function like `https://github.com/keegancsmith/shell/blob/master/escape.go#L10`. I don't know if the equivalent functionality is available in Go standard library or elsewhere in Packer already. Surely lots of other pieces of packer also need to print shell commands, ideally in a form that can be pasted back into the shell and executed?

**Comment by lbytnar** [comment]
@mwhooker this also exists in ansible-local [#5335](https://github.com/hashicorp/packer/issues/5335) and is causing issue as seems to skip the rest of the arguments like e.g. inventory. Perhaps there is same fix for both ansible-local and ansible-remote.

**Comment by pjnagel** [comment]
[debug.json.txt](https://github.com/hashicorp/packer/files/1351752/debug.json.txt)
[debug.yml.txt](https://github.com/hashicorp/packer/files/1351753/debug.yml.txt)

To be clear:
- When I reported this bug, I meant that packer should properly escape **all** commands it executes, regardless of which provisioner etc.does the printing. I just used the ansible-provisioner as a concrete example where this was not done.
- **All** characters that the shell interprets should be correctly escaped. I only used spaces in commands as an illustration that proper shell escaping does not occur.

I assumed that packer already has a single utility function that prints shell command-lines, but it seems to me that it does not. Hence multiple different provisioners have this bug.

@mwhooker, I tested  #5414 and it improves matters. However, I was able to construct a test case to show that shell escaping is still not totally correct. I attach the needed JSON and YAML (with a .txt extension)

If you run "packer build debug.json", you can see that packer correctly passes the JSON embedded in the --extra-vars to ansible, even though the variable value contains a $. If you execute the command-line as the provsioner printed it, though, the $ gets lost because it was not escaped.

Shell-escaping a string before printing it should be a solved problem provided by various libraries, maybe even in standard Go itself.

But again, thanks for the patch, it is a step in the right direction.

**Comment by mwhooker** [comment]
yes, shell escaping is a major headache and I'm not sure it exists outside of 3rd party libraries. This isn't something we're eager to add... tho i suppose as a debugging aid it will probably be okay. I've used https://code.google.com/archive/p/go-shlex/ in the past with success
