### ISSUE TITLE
Document manifest pp artifact outputs

### ISSUE THREAD

**Issue by mwhooker** [hashicorp/packer#5413]
we clearly need to make the manifest post-processor easier to use. I think we need to document what the artifact output for each builder looks like, and how to use it in a shell script.

**Comment by cornfeedhobo** [comment]
Would this be an appropriate place to throw out ideas about modifications to `manifest`?

- include artifact filename (is `files` supposed to do this? the output seems less than ideal there)
- optional file hashes included
- include all variables passed to packer, including those in the template
- it would be nice if everything manifest did was able to be toggled. e.g. I could see wanting to have packer write out every passed variable (this could actually be great for debugging), but not needing things like this all the time.

**Comment by SwampDragons** [comment]
@cornfeedhobo sorry for not responding sooner; this is a docs-related ticket which will be closed once we have the docs updated... so If you want your things being addressed in a more formal and organized way, it's best to open a separate ticket.  In this case, it seems like you might have three or four separate ideas for improvement.  Easiest to track if we manage each of those in their own separate feature request tickets.
