### ISSUE TITLE
"Windows could not parse or process unattend answer file [A:\autounatted.xml] for pass [windowsPE]. A component or setting specified in the answer file does not exist"

### ISSUE THREAD

**Issue by ArchontPnz** [hashicorp/packer#5418]
Tried to install Windows 2012 R2 Standard x64 on esxi, using packer. Error occurs "Windows could not parse or process unattend answer file [A:\autounatted.xml] for pass [windowsPE]. A component or setting specified in the answer file does not exist". 
json-file and Autounatted.xml:
https://gist.github.com/ArchontPnz/48618f921252a50e83f5ab6064cb8063

When autounatted.xml is inside the iso-image the installation is successful.
Any ideas?

**Comment by rismoney** [comment]
i think input locale is supposed to be semicolon separated.

https://technet.microsoft.com/en-us/library/cc749191(v=ws.10).aspx

**Comment by mwhooker** [comment]
Going to close this since I think this is more of a question than a bug with packer. You may have better luck with the [mailing list](https://groups.google.com/forum/#!forum/packer-tool). If you discover buggy behavior in packer, I'd be happy to take a look at a new ticket.

Thanks!
