### ISSUE TITLE
Images built with azure-arm and VMSize do not create VMs with the specified VMSize

### ISSUE THREAD

**Issue by hantuzun** [hashicorp/packer#5420]
I built managed Ubuntu Images on Azure with Packer specifying a `VMSize` (`Standard_DS2_v2 `). Using these images I created VMs with Azure's cli `az`.

The VMs are not created with the VMSize specified for the images.

I barely update the given [ubuntu_managed_image.json](https://github.com/hashicorp/packer/blob/99033e7da2631cf16638a5af28950131a76f43d7/examples/azure/ubuntu_managed_image.json) in the examples.

- Packer version: 1.1.0
- Host platform: macOS 10.12.6
- "Debug log output from `PACKER_LOG=1 packer build template.json`" and "The _simplest example template and scripts_ needed to reproduce the bug.": https://gist.github.com/hantuzun/1fbbbe3beb9974fc44d2f0da031d4f64

**Comment by boumenot** [comment]
Can you please [capture debug](https://www.packer.io/docs/other/debugging.html) logs, and attach them to this case or a gist.

**Comment by hantuzun** [comment]
Hi @boumenot ; thanks. Apologies for getting back late. I captured new logs: https://gist.github.com/hantuzun/43353a28edbb38c0f45f7b43142743e0

These new logs are from a freshly set up mac but with the same versions.

**Comment by hantuzun** [comment]
Hi @boumenot & @mwhooker,

I've created a PackerImages resource group in West US and reproduced the error by using the exact example [ubuntu_managed_image.json](https://github.com/hashicorp/packer/blob/master/examples/azure/ubuntu_managed_image.json) 
 file in the repo: https://gist.github.com/hantuzun/cd2b65f49b73d4e8e04093f96407a135

In the new gist above, I've added the payload from the logs and the created template.

Everything seems alright to me except the template doesn't have vmSize and the created VMs are created with size `Standard_DS1_v2`...

**Comment by boumenot** [comment]
I may be misunderstanding the report, if so please correct.  The VM size used to build a Packer image does not have to match the VM size used to deploy the image.  It looks like the image is being built with Packer is a Standard_DS2_v2, and the logs all appear to indicate that is correct.  When you deploy the image afterwards with the CLI you got something different.  This is expected. The VM size is not embedded in the Packer image.  What is the CLI command you used to deploy the image?

**Comment by hantuzun** [comment]
Hi @boumenot,

You didn't misunderstood at all. I wasn't providing `--size` parameter like below[*](https://gist.github.com/hantuzun/1fbbbe3beb9974fc44d2f0da031d4f64)[†](https://gist.github.com/hantuzun/43353a28edbb38c0f45f7b43142743e0): 

```
az vm create \
  --name xxx \
  --resource-group xxx \
  --image xxx \
  --admin-username xxx \
  --ssh-key-value xxx
```

I've just tried a deploy with `--size` and it worked as expected.

Why do we provide `vm_size` parameter for Packer if the VM size is not embedded in the images?

Should we close the issue?

**Comment by boumenot** [comment]
Thank you for the following up with confirmation that it worked, and I am glad you are unblocked.
