### ISSUE TITLE
document ability to parse csv variables into array

### ISSUE THREAD

**Issue by mwhooker** [hashicorp/packer#5428]
see #1794 etc

should probably add to https://www.packer.io/docs/templates/user-variables.html

**Comment by mwhooker** [comment]
closed in 4aee438c2

**Comment by brettjacobson** [comment]
@mwhooker Does this work on anything that expects an array?

**Comment by mwhooker** [comment]
@brettjacobson it should. anything that's an array of primitives (number, string, etc)
