### ISSUE TITLE
Add IP address to the "Waiting for SSH" message.

### ISSUE THREAD

**Issue by dglinder** [hashicorp/packer#5433]
In the "helper/communicator/step_connect_ssh.go" code, currently in the Run() function, it would be helpful if the "ui.Say()" output included the IP address it is expecting to connect to.

This can help immensely in debugging especially in situations where an OS firewall may be denying connectivity to the VM, and for sanity checking using an ssh client.

**Comment by SwampDragons** [comment]
I'm pretty sure that in the case you're describing, this information is already available in the debug output. (see `log.Printf("[DEBUG] TCP connection to SSH ip/port failed: %s", err)`) in that same file, You can turn on debug logging access by setting the environment variable `PACKER_LOG=1`

An example of this output would be ```2017/10/13 14:05:25 packer: 2017/10/13 14:05:25 [DEBUG] TCP connection to SSH ip/port failed: dial tcp 34.229.240.185:22: i/o timeout```
