### ISSUE TITLE
Feature Request: implement  assume role token provider to ask for MFA token code

### ISSUE THREAD

**Issue by gdamjan** [hashicorp/packer#5435]
in AWS you can assume a role with your credentials, to have another set of permissions (lower, higher or to another account). The rules for switching roles can require MFA (multifactor authentification) - which is a recommended setup. In that case packer needs to ask for the MFA code.

Here's an example how that is configured in the aws-cli 
http://docs.aws.amazon.com/cli/latest/userguide/cli-roles.html

From the sdk-for-go api docs, it seems that using `stscreds.StdinTokenProvider` for `AssumeRoleTokenProvider` in the session Options should be enough.

https://docs.aws.amazon.com/sdk-for-go/api/aws/session/#Options
>     // When the SDK's shared config is configured to assume a role with MFA
>     // this option is required in order to provide the mechanism that will
>     // retrieve the MFA token. There is no default value for this field. If
>     // it is not set an error will be returned when creating the session.
>     //
>     // This token provider will be called when ever the assumed role's
>     // credentials need to be refreshed. Within the context of service clients
>     // all sharing the same session the SDK will ensure calls to the token
>     // provider are atomic. When sharing a token provider across multiple
>     // sessions additional synchronization logic is needed to ensure the
>     // token providers do not introduce race conditions. It is recommend to
>     // share the session where possible.
>     //
>     // stscreds.StdinTokenProvider is a basic implementation that will prompt
>     // from stdin for the MFA token code.
>     //
>     // This field is only used if the shared configuration is enabled, and
>     // the config enables assume role wit MFA via the mfa_serial field.
>     AssumeRoleTokenProvider func() (string, error)

**Comment by mwhooker** [comment]
Thanks for the input. We're not interested in adding interactive features to packer, since it's an automated tool. You can add an [`mfa_code`](https://www.packer.io/docs/builders/amazon-ebs.html#mfa_code) option to your template which will allow you to set it.

**Comment by gdamjan** [comment]
using `stscreds.StdinTokenProvider` should only fire-up in the case the AWS setup is such that it requires MFA when switching roles. It will not make packer interactive in the default case.

**Comment by rickard-von-essen** [comment]
Also using `stscreds.StdinTokenProvider` will not work since the builder is running in a subprocess which don't have access to stdin.

**Comment by KoeSystems** [comment]
@gdamjan This wrapper could help you https://gist.github.com/KoeSystems/bb5bf9be77568c713b231ebd84124211

**Comment by et304383** [comment]
What an incredibly close minded view to take, suggesting that MFA should not be supported because it makes the tool interactive.

**Comment by rickard-von-essen** [comment]
> suggesting that MFA should not be supported because it makes the tool interactive.

MFA is supported. Reauthorization when the STS token expires isn't. That would either require that you enter a new (MFA) token code (making the tool interactive) or use a software (callback) to retrieve a new code.

**Comment by et304383** [comment]
`MFA is supported. Reauthorization when the STS token expires isn't. That would either require that you enter a new (MFA) token code (making the tool interactive) or use a software (callback) to retrieve a new code.`

Perhaps if your AMI takes more than an hour to build, which has to be less than 1% of all use cases.

**Comment by rickard-von-essen** [comment]
> Perhaps if your AMI takes more than an hour to build

Then you have three options:

- Split the build in two or more consecutive builds.
- Run on an EC2 instance using the instance role credentials.
- Use a static AWS access key for which you don't require MFA.

**Comment by et304383** [comment]
I realize there are options.  My point was that this has to be a very limited scenario, so making a decision to not prompt for MFA for a very limited scenario seems crazy.

**Comment by rickard-von-essen** [comment]
> My point was that this has to be a very limited scenario, so making a decision to not prompt for MFA for a very limited scenario seems crazy.

On the contrary I think supporting a 1% use case with a somewhat complex implementation, with a workflow that we dislike is something that is not only easy to say no to it's also the right thing to do.

**Comment by et304383** [comment]
You've been completely misreading me.

A scenario where provisioning an AMI takes more than 1 hour seems to me to be the 1% scenario.  So NOT supporting MFA directly because it makes the tool "interactive" is wrong.

In any case where you want the tool to be non-interactive you're not going to be using MFA.  Why is this even an issue?  It's a feature request.  If you don't have time to implement it, fine, but it in no way breaks non-interactive functionality where MFA won't be present.
