### ISSUE TITLE
Provisioner: Create Multiple Docker images - Question

### ISSUE THREAD

**Issue by karthik101** [hashicorp/packer#5437]
How can i create multiple docker provisioners to create two or more separate docker images from a single json file. I need to pass package names as user parameters to separate provisioners. Is this possible?  

Thanks,
Karthik

**Comment by rickard-von-essen** [comment]
The question is a bit unclear but see the docs for [named builds](https://www.packer.io/docs/templates/builders.html#named-builds).

---

Please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

**Comment by SwampDragons** [comment]
We tend to refer questions to the community (see rickard's link above) but if you can't solve your problem and have either a bug to report or a feature to request, please feel free to open a new ticket.  Thanks!

**Comment by karthik101** [comment]
Sorry i already posted question into the groups and didn't get any replies , so i posted here. I will try with named builds, but i don't seem to find any examples in the docs.

**Comment by SwampDragons** [comment]
Inside your builder, add `"name": "my-build-name-here"`; then if you add logic inside your provisioner to check for the environment variable `packer_builder_name` you should be able to modify its actions based on the build name.
