### ISSUE TITLE
checksum post-processor is not creating a GNU checksum file

### ISSUE THREAD

**Issue by amaczuga** [hashicorp/packer#5442]
Please read https://github.com/hashicorp/packer/issues/5168 ,
then look at this: https://github.com/hashicorp/packer/blob/v1.1.0/post-processor/checksum/post-processor.go#L141

I particularly don't understand why packer is putting a tab character there.

**Comment by rickard-von-essen** [comment]
It dosen't specify exactly the format of the output. Could you elaborate why it would be good if it outputed a GNU formatted checksum file.

**Comment by amaczuga** [comment]
You are right, checksum post-processor documentation doesn't mention its file format. 
It would help to integrate packer with legacy systems if packer used one of popular checksum file formats.
On the other hand, It is worth to introduce a new format if it is superficial to legacy ones, bringing new features or fixing legacy problems.

**Comment by SwampDragons** [comment]
I'm going through old issues; I think changing the tab to spaces would cause more problems for current users of Packer than it would solve. If someone's really passionate about this and has a very compelling reason to change it the I'll reconsider, but I think for now the change isn't worth it.
