### ISSUE TITLE
Allow to specify tags or skipped tags in ansible provisioner 

### ISSUE THREAD

**Issue by magnetik** [hashicorp/packer#5443]
Hi,

I'm using packer to build AMI with the same playbook that I use to provision the production. 

Of course there are some things that must not be done in the packer image, so I would like to skip them.

A way of doing this would be for the user to tag it with "packer_skip" or something.
On the `ansible-playbook` command like, it should be used by adding `--skip-tags packer_skip`.

I don't know anything about Go, but I'm willing to try to do a PR if this is something wanted.

Thanks

**Comment by magnetik** [comment]
I missed that it can be done with `extra_arguments`. Still worth it's own config IMO but I let you decide.

**Comment by mwhooker** [comment]
thanks for the ticket. Since it's doable now, I'll close this. Happy to look at PRs for it though
