### ISSUE TITLE
manifest post-processor has no data for azure-arm builders

### ISSUE THREAD

**Issue by blalor** [hashicorp/packer#5455]
Not sure if this is a feature or a bug, but I expected that the `manifest` post-processor would capture the artifacts of the `azure-arm` builder.  For a VHD output, there isn't anything related to the output from the builder.

For example, the builder output looks like:

```
==> Builds finished. The artifacts of successful builds are:
--> azure-arm: Azure.ResourceManagement.VMImage:

StorageAccountLocation: …
OSDiskUri: …
OSDiskUriReadOnlySas: …
TemplateUri: …
TemplateUriReadOnlySas: …
```

But the `manifest` pp result contains:

```json
{
  "builds": [
    {
      "name": "azure-arm",
      "builder_type": "azure-arm",
      "build_time": 1507909779,
      "files": null,
      "artifact_id": "",
      "packer_run_uuid": "4be91566-d0c4-19ae-b8b1-5a387448cb6f"
    }
  ],
  "last_run_uuid": "4be91566-d0c4-19ae-b8b1-5a387448cb6f"
}
```

I know I can use the machine-readable output of packer to parse out what I need (or _assume_ I will need, as I'm still learning my way around Azure), but it would be preferable to have that data in a structured fashion from the `manifest` post-processor.

**Comment by mwhooker** [comment]
Should be there since #4953

can you verify what version of packer you're using?

**Comment by blalor** [comment]
Oops, sorry.  v1.1.0.

**Comment by mwhooker** [comment]
and can you post your json?

**Comment by blalor** [comment]
[packer.json](https://github.com/hashicorp/packer/files/1383870/packer-azure.json.txt)

**Comment by blalor** [comment]
And I'm running with `packer build -only azure-arm packer.json`.

**Comment by blalor** [comment]
PEBKAC.
