### ISSUE TITLE
Unverified GPG key ID: 51852D87348FFC4C 

### ISSUE THREAD

**Issue by shibumi** [hashicorp/packer#5459]
Hello,
Could you please verify that the key 51852D87348FFC4C is from the hashicorp team? All Release-Tags are signed with that key but github says it's unverified and the developer who owns the key also owns another key that is verified. Quite chaotic. Would be cool if you guys could verify that this key is really from you.

**Comment by mwhooker** [comment]
It's ours. you can see the ID and the public key at https://www.hashicorp.com/security/ Note also that it's on keybase
