### ISSUE TITLE
Docs: Azure Setup refers to outdated azure-cli 1.0

### ISSUE THREAD

**Issue by jansepke** [hashicorp/packer#5465]
this site https://www.packer.io/docs/builders/azure-setup.html refers to the azure-cli 1.0 the current one is version 2.0 with a redesigned API. The referenced setup file https://github.com/hashicorp/packer/blob/master/contrib/azure-setup.sh has the same problem.

**Comment by SwampDragons** [comment]
I just looked at those docs and on a quick skim through I'm not seeing any specific versions referenced.  The shell script just has an `$azureversion` variable and the docs don't mention versions specifically.  Are there commands that don't work anymore which these files are using?

**Comment by boumenot** [comment]
There are **three** CLIs for Azure (yes :three:).  They are the Azure XPlat CLI, Azure CLI, and Azure PowerShell.  The XPlat CLI is what you're referring to as v1.0, and the Azure CLI is what you're referring to as v2.0.  They are independent of each other to my knowledge, and development on v1.0 continues.

The v2.0 CLI is available in the Azure Portal.  If you click the shell button you get a running Linux VM with the CLI installed, and the current user account authenticated.  As a result, I think v2.0 is the way forward.  For this reason I think it makes sense to port the documentation from v1.0 to v2.0.

**Comment by SwampDragons** [comment]
Sounds fair to me.  Given that I didn't know the difference between these CLIs until I read @boumenot's comment, anyone want to submit a PR fixing this?

**Comment by jansepke** [comment]
The Terraform docs could be a good starting point:
https://www.terraform.io/docs/providers/azurerm/authenticating_via_service_principal.html

**Comment by jansepke** [comment]
Closed by #5822
