### ISSUE TITLE
error initializing provisioner 'powershell': plugin exited before we could connect

### ISSUE THREAD

**Issue by bitfrickler** [hashicorp/packer#5467]
Error: `error initializing provisioner 'powershell': plugin exited before we could connect
`
Packer version: 1.1.1
Host: macOS 10.13
Log: https://gist.github.com/bitfrickler/64188bfa07f03b4094af3564b5bd93cd
Template: https://gist.github.com/bitfrickler/779aac6420cd1b619d24780af07d66c5

**Comment by DanHam** [comment]
@bitfrickler It looks as though you have the now deprecated [packer-community/packer-windows-plugins](https://github.com/packer-community/packer-windows-plugins) installed. From your log:

> 2017/10/16 14:59:22 [DEBUG] Discovered plugin: amazon-windows-ebs = /usr/local/bin/packer-builder-amazon-windows-ebs
2017/10/16 14:59:22 [DEBUG] Discovered plugin: parallels-windows-iso = /usr/local/bin/packer-builder-parallels-windows-iso
2017/10/16 14:59:22 [DEBUG] Discovered plugin: parallels-windows-pvm = /usr/local/bin/packer-builder-parallels-windows-pvm
2017/10/16 14:59:22 [DEBUG] Discovered plugin: virtualbox-windows-iso = /usr/local/bin/packer-builder-virtualbox-windows-iso
2017/10/16 14:59:22 [DEBUG] Discovered plugin: virtualbox-windows-ovf = /usr/local/bin/packer-builder-virtualbox-windows-ovf
2017/10/16 14:59:22 [DEBUG] Discovered plugin: vmware-windows-iso = /usr/local/bin/packer-builder-vmware-windows-iso
2017/10/16 14:59:22 [DEBUG] Discovered plugin: vmware-windows-vmx = /usr/local/bin/packer-builder-vmware-windows-vmx
2017/10/16 14:59:22 [DEBUG] Discovered plugin: powershell = /usr/local/bin/packer-provisioner-powershell
2017/10/16 14:59:22 [DEBUG] Discovered plugin: restart-windows = /usr/local/bin/packer-provisioner-restart-windows
2017/10/16 14:59:22 [DEBUG] Discovered plugin: windows-shell = /usr/local/bin/packer-provisioner-windows-shell

It looks to me as thought these old plugins are overriding the newer versions that Packer now has built in and causing you your issues. Without these external plugins installed your logs would instead look something like:

> 2017/10/16 22:42:59 Using internal plugin for powershell
2017/10/16 22:42:59 Using internal plugin for windows-shell

...and so on.

I have managed to build from the bitfrickler/packer-windows/windows-2016-test.json template successfully on my system (which is pretty much identical to yours).

I would suggest checking if you have these plugins installed and, if you have, uninstall them.
Let us know if that does the trick.

**Comment by bitfrickler** [comment]
@DanHam You're right. After removing the plugins everything works fine. Thank you very much 👍

**Comment by bbaassssiiee** [comment]
These outdated plugins could also be hidden in this directory since 2015:
`$HOME/.packer.d/plugins`
