### ISSUE TITLE
post-processor/amazon-import Ability to encrypt ebs snapshot/volume.

### ISSUE THREAD

**Issue by breisig** [hashicorp/packer#5474]
One feature missing from amazon-import post-processor is to have an option to encrypt the ebs volume once packer uploads it. Packer is great for building images from ISO using virtualbox and then using the 'amazon-import' post processor to automatically upload that image to AWS to have it auto create the AMI for us. The biggest issue is not being able to set a 'flag' or something with the 'amazon-import' post-processor to have the EBS snapshot encrypted.

**Comment by alessiot77** [comment]
it sound like because of the following limitation:

"Importing AMIs and snapshots is subject to the following limitations:
AMIs with volumes using EBS encryption are not supported."

http://docs.aws.amazon.com/vm-import/latest/userguide/vmie_prereqs.html

**Comment by telepath** [comment]
I don't think this issue should be closed.
The ebs builder creates encrypted AMIs by copying the AMI after creation, this should be possible for the postprocessor as well?
Alternatively, an encryption post-processor could replace both requirements.

**Comment by telepath** [comment]
I've actually found a plugin for that: https://github.com/martinbaillie/packer-post-processor-ami-copy
However it does not work with my file builder and amazon-import combination, yet.
