### ISSUE TITLE
AWS: InsufficientInstanceCapacity results in infinite hangs

### ISSUE THREAD

**Issue by ashleyhull-versent** [hashicorp/packer#5482]
`"InsufficientInstanceCapacity: do not have sufficient m4.large capacity in the Availability Zone you requested (ap-southeast-2a)"`

- Packer version from `1.1.0`
- Linux (Codebuild Ubuntu image)
  
![image](https://user-images.githubusercontent.com/17537000/31748427-d36e3126-b4be-11e7-9888-d05a100c7ede.png)

**Comment by mwhooker** [comment]
I think this might be related to the codebuild plugin and not packer. the line "Now wait until we can obtain the just built ami" isn't part of packer. The line "builds finished but no artifacts were created" is from packer and shows me it exited already. I would try to open an issue with whoever maintains the runner.

If you think this is a bug with packer, I'll need to see it reproduced somehow. I think probably by forking packer and forcing an error during instance launch
