### ISSUE TITLE
Restart_Check_Command endlessly looping

### ISSUE THREAD

**Issue by Bowmaster** [hashicorp/packer#5483]
Hello,

I am having an issue with the "restart_check_command" within the windows_restart provisioner.  Essentially, the command endlessly loops, even if the conditions are satisfied, and regardless of the exit I code I throw on success (tried 0 and 1 when successful condition is reached).  Ultimately, the build fails because I reach the restart_timeout threshold.

Here is the relevant snippet of my config.json

    {
      "type": "windows-restart",
      "restart_timeout": "720m",
      "restart_check_command": "powershell -command \"& {if ((Test-Path C:\\PackerScripts\\_OrchestrationFiles\\PO_Finished.po)){Write-Output 'Restart complete';}else{Write-Output 'Waiting for restart';Start-Sleep -Seconds 30;}}\""
    },

Here is a gist with debug logging turned on:

https://gist.github.com/Bowmaster/e446d4ebd3ee5f30f72101b23c5d9d79

I have tried specifying custom restart command, custom timeouts, and explicitly stating exit codes when the condition is satisfied (0,1).

Now this could be simply incorrect use on my part, unfortunately though the documentation is not at all clear how this should be used or what type of output is expected to satisfy the condition and continue.

I had found an AWS example and tried to follow the example with my own condition substituted but no luck:

https://github.com/hashicorp/best-practices/blob/b7df3c995d3001e90928aae6d2a92cd54c29079e/packer/aws/windows/base.json

Thank's for the help, and I apologize if this is an oversight or misstep on my part.

**Comment by mwhooker** [comment]
Thanks for the report. I think I see the bug. To test, would you mind trying with this check command?

`"restart_check_command":  "powershell.exe -EncodedCommand aQBmACAAKAAoAFQAZQBzAHQALQBQAGEAdABoACAAQwA6AFwAUABhAGMAawBlAHIAUwBjAHIAaQBwAHQAcwBcAF8ATwByAGMAaABlAHMAdAByAGEAdABpAG8AbgBGAGkAbABlAHMAXABQAE8AXwBGAGkAbgBpAHMAaABlAGQALgBwAG8AKQApAHsAVwByAGkAdABlAC0ATwB1AHQAcAB1AHQAIAAnAFIAZQBzAHQAYQByAHQAIABjAG8AbQBwAGwAZQB0AGUAJwA7AH0AZQBsAHMAZQB7AFcAcgBpAHQAZQAtAE8AdQB0AHAAdQB0ACAAJwBXAGEAaQB0AGkAbgBnACAAZgBvAHIAIAByAGUAcwB0AGEAcgB0ACcAOwBTAHQAYQByAHQALQBTAGwAZQBlAHAAIAAtAFMAZQBjAG8AbgBkAHMAIAAzADAAOwB9AA=="`

**Comment by Bowmaster** [comment]
Thank's for the quick reply - result was the same, here's a new gist and the updated provisioner for reference:

https://gist.github.com/Bowmaster/1cf821df7f516935c1ccdea6e4f3335b

    {
      "type": "windows-restart",
      "restart_timeout": "720m",
      "restart_check_command": "powershell.exe -EncodedCommand aQBmACAAKAAoAFQAZQBzAHQALQBQAGEAdABoACAAQwA6AFwAUABhAGMAawBlAHIAUwBjAHIAaQBwAHQAcwBcAF8ATwByAGMAaABlAHMAdAByAGEAdABpAG8AbgBGAGkAbABlAHMAXABQAE8AXwBGAGkAbgBpAHMAaABlAGQALgBwAG8AKQApAHsAVwByAGkAdABlAC0ATwB1AHQAcAB1AHQAIAAnAFIAZQBzAHQAYQByAHQAIABjAG8AbQBwAGwAZQB0AGUAJwA7AH0AZQBsAHMAZQB7AFcAcgBpAHQAZQAtAE8AdQB0AHAAdQB0ACAAJwBXAGEAaQB0AGkAbgBnACAAZgBvAHIAIAByAGUAcwB0AGEAcgB0ACcAOwBTAHQAYQByAHQALQBTAGwAZQBlAHAAIAAtAFMAZQBjAG8AbgBkAHMAIAAzADAAOwB9AA=="
    },

**Comment by mwhooker** [comment]
I see. Let's try one more thing. Can you use this restart command?

```
"powershell.exe -EncodedCommand aQBmACAAKAAoAFQAZQBzAHQALQBQAGEAdABoACAAQwA6AFwAUABhAGMAawBlAHIAUwBjAHIAaQBwAHQAcwBcAF8ATwByAGMAaABlAHMAdAByAGEAdABpAG8AbgBGAGkAbABlAHMAXABQAE8AXwBGAGkAbgBpAHMAaABlAGQALgBwAG8AKQApAHsAVwByAGkAdABlAC0ATwB1AHQAcAB1AHQAIAAnAHIAZQBzAHQAYQByAHQAZQBkACcAOwB9AGUAbABzAGUAewBXAHIAaQB0AGUALQBPAHUAdABwAHUAdAAgACcAVwBhAGkAdABpAG4AZwAgAGYAbwByACAAcgBlAHMAdABhAHIAdAAnADsAUwB0AGEAcgB0AC0AUwBsAGUAZQBwACAALQBTAGUAYwBvAG4AZABzACAAMwAwADsAfQA="
```

**Comment by SwampDragons** [comment]
Aw heck this is probably the fault of the fact that we now check for "restarted." in stdout  in order to make sure that powershell is fully loaded:  
```		
		if !strings.Contains(stdoutToRead, "restarted.") {
			log.Printf("echo didn't succeed; retrying...")
			continue
		}
```
When I wrote that check I don't think I even realized that it was a configurable option...

**Comment by mwhooker** [comment]
todo (cc @SwampDragons):

- [ ] custom restart command needs powershell encoding
- [ ] the output we check for if restart command succeeds needs to be configurable, or restart command shouldn't be overridable
- [ ] need documentation explaining how restart command checks for restarts suceeding
- [ ] need to update https://github.com/hashicorp/best-practices/tree/master

**Comment by SwampDragons** [comment]
That looks good to me.  Why is it useful to have this restart check command be overridable in the first place?

**Comment by Bowmaster** [comment]
I leave for a few hours and looks like you guys found the issue, thanks for identifying so quickly!  I'll be traveling for a few days but I'd be happy to do some real-world testing with our full config when I get back next week if that helps.

Those todo's look good to me as well.  What do you think about an option to manually specify an exit code for success (in addition to your 2nd 'todo' above)?

    "restart_check_valid_exit_code": [0,4,5,n]

Personally I'd be fine just specifying what I expect from stdout and then returning that when the check is valid but I know some folks who would prefer exit codes.

**Comment by SwampDragons** [comment]
Sounds great.  For now, you can work around this by making sure your check command echos "restarted."

**Comment by DanHam** [comment]
> custom restart command needs powershell encoding

I see the need/benefit, but encoding will most likely cause PowerShell to splat its Progress stream all over the console! Perhaps it would be better to leave this be? Users already making use of a custom restart command will already be providing the necessary escapes in their custom commands. New users could be made aware of the need in the docs...

> Why is it useful to have this restart check command be overridable in the first place?

In hindsight it may have been better not to allow users to override this or provide their own restart command as this complicates things! I wonder how many people are using(/abusing?) this facility to run commands that would (possibly) be better placed in a separate provisioner, or are using this facility unnecessarily when the defaults would serve just as well. It may seem drastic but perhaps we would be better served by removing the `restart_command` and `restart_check_command` options altogether...?

**Comment by SwampDragons** [comment]
That's kind of what I'm thinking... if it isn't providing a real benefit, better not to have it at all.  We We could write an RFC for deprecating the option and see what people say.

**Comment by Bowmaster** [comment]
Personally I would like to see both options stay, the restart_check_command, in particular has now come in very handy, particularly for Server 2008 R2 builds (yeah I know, please don't judge too harshly, takes our devs a while to catch up).  The way we do Packer at our company is very dynamic, with a single config.json file driving our OS's with differences handled by variable files that are unique per OS. Further dynamic provisioning is handled via some neat PowerShell scripts (too off-topic to go into here).  Having these options help us to be more dynamic with fewer configs and files to manage.  Might not be the perfect way, and may not be in the spirit of what Hashicorp intends Packer to be used for, but it works pretty well for us.  

My 2 cents of course, and I appreciate everybody's help.  For now the workaround is working perfectly.

**Comment by SwampDragons** [comment]
I appreciate the two cents.  I wonder if the right course of action, since deprecation is hard and always breaks something for someone, is to add the configurable check command and then flag these two things as advanced features which you should only use if you know what you're doing, with examples.

**Comment by SwampDragons** [comment]
@Bowmaster your setup sounds really cool and interesting, by the way. and no judgement here -- at my last gig we had VMs all the way back to Windows XP.  You gotta support what you gotta support.

**Comment by EugeneDeveloper** [comment]
Hello @SwampDragons. As @Bowmaster mentioned it will be nice to have option to select exit code like 
`"restart_check_valid_exit_code": [0,4,5]`
Currently during the flow that requires restarts we can continue only by checking special exit code from the command. There are exists any plan to implement that functionality? Thanks in advance.

Best regards,
Eugene

**Comment by SwampDragons** [comment]
There are no current plans to implement this; if you'd like to open a ticket for it and/or take a stab at writing this, I'd gladly review.
