### ISSUE TITLE
Website Should Render Markdown of Intro Page Correctly

### ISSUE THREAD

**Issue by outthought** [hashicorp/packer#5489]
Intro page [Build An Image](https://www.packer.io/intro/getting-started/build-image.html), "Some more examples," section should render the code block containing the contents of `example.sh` correctly. Currently, the `#` in `#!/bin/bash` is interpreted as a level-one header.

The [markdown code](https://github.com/hashicorp/packer/blob/master/website/source/intro/getting-started/build-image.html.md#another-gnulinux-example-with-provisioners) looks correct.

**Comment by mwhooker** [comment]
thanks for this. Looks like it's fixed in master, but we just need to deploy `stable-website`

**Comment by mwhooker** [comment]
fixed, thanks!
