### ISSUE TITLE
building Vagrant boxes using Docker impossible?

### ISSUE THREAD

**Issue by ror6ax** [hashicorp/packer#5490]
Documentation says

```
Because Vagrant boxes are provider-specific, the Vagrant post-processor is hardcoded to understand how to convert the artifacts of certain builders into proper boxes for their respective providers.
```
I'm not sure I understand it correctly. Does it mean that to get Virtualbox Vagrant box, I have to use Virtualbox builder? VB is a bit cumbersome to set up as a part of CI pipeline...

**Comment by rickard-von-essen** [comment]
Yes if you use `virtualbox-[iso|ovf]` you will get a `virtualbox` provider specific Vagrant box.

> VB is a bit cumbersome to set up as a part of CI pipeline...

It shouldn't be that hard. Please ask on _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/
