### ISSUE TITLE
amazon: temp sg cidr should accept a list of cidrs

### ISSUE THREAD

**Issue by nap** [hashicorp/packer#5494]
We very much appreciate the addition of a `temporary_security_group_source_cidr`. 
Although, I was wondering if it could be made to accept a list of `CIDR` blocks. 

We have multiple offices with different CIDR Blocks and we would appreciate if we did not have to update that file or set a variable each time they run packer.

RE: `builder/amazon: Add temporary_security_group_source_cidr option to control ingress to source instances. [GH-5384]`

Thanks!

```
$ packer --version
1.1.1
```

**Comment by mwhooker** [comment]
copy & paste of comment from #5384 

> seems like it would be a good idea. I'd want to see this renamed to temporary_security_group_source_cidrs and to add a fixer (see fix/ directory). Happy to review patches

**Comment by nap** [comment]
That's great news! Thanks for the reply. Feel free to close this one as it seems to be properly discussed in #5384
