### ISSUE TITLE
-on-error=ask does not work for post processors

### ISSUE THREAD

**Issue by andrewsav-datacom** [hashicorp/packer#5497]
Issue described at https://groups.google.com/forum/#!topic/packer-tool/xIi0kkBEYeQ

The documentation does not make it clear that the `-on-error=ask` flag only applies to builders and provisional but not to post processor. Fixing documentation is easy, but perhaps packer can support this flag for post-processors too? It is no less useful for post-processors since it allows for easier diagnostics when a post-processor file, and it make it consistent all along the processing pipeline. If you ask a bystander like me, It's not clear **why** it is not supported for post-processors. I think it should be.

**Comment by mwhooker** [comment]
some additional context in this very closely related issue here:

https://github.com/hashicorp/packer/issues/5419#issuecomment-338745738

basically, this is a limitation of how we run provisioning. We'll be reevaluating that system in the future, but currently it's not something we can support. This should be clearly documented, however
