### ISSUE TITLE
Can't register the machine while its locked and similar issues.

### ISSUE THREAD

**Issue by swapnilpatil1682** [hashicorp/packer#5501]
-  `packer version`  = 1.1.1

- Host platform = Cent OS 7 

- Debug log output from `PACKER_LOG=1 packer build template.json`.
https://gist.github.com/swapnilpatil1682/b464a521d3a2dd5d7850f26ddbf607ca

- The _simplest example template and scripts_ needed to reproduce the bug.
https://gist.github.com/swapnilpatil1682/f151a748219db982fdff4fb8d119fcaf

**Comment by mwhooker** [comment]
I have a patch for this, but in the mean time you can try increasing [`post_shutdown_delay`](https://www.packer.io/docs/builders/virtualbox-ovf.html#post_shutdown_delay) to something like `2m`

**Comment by mwhooker** [comment]
If you want to test the patch in #5512, it would be greatly appreciated
