### ISSUE TITLE
Kernel and initrd source for QEMU builder

### ISSUE THREAD

**Issue by kpostrup** [hashicorp/packer#5503]
Currently Packer supports booting QEMU builders from ISO files (`iso_url`).

I propose a new feature that enables Packer to install directly from `kernel` and `initrd`. Technically this could be by means of injecting iPXE config or similar. 

The `virt-install` tool provides a similar `--location` option. See: 
http://manpages.ubuntu.com/manpages/xenial/man1/virt-install.1.html

What I am looking for is perhaps a little more flexible, where we can define `kernel`, `initrd` and kernel parameters.

This would greatly simplify e.g. Ubuntu installations.

**Comment by ltrager** [comment]
qemu supports this directly with the -kernel, -initrd, and -append command line options. You don't need to use iPXE as qemu will boot directly into the kernel when specified. Adding support for this will allow for much smaller download sizes when creating Linux images.
