### ISSUE TITLE
amazon-instance builder requires incorrect root device type

### ISSUE THREAD

**Issue by bbergstrom** [hashicorp/packer#5504]
Describe the problem and include the following information:
Packer version 1.1.1
Mac OSX 10.11.6
```
Build 'amzn-2017.09-instance-hvm' errored: The provided source AMI has an invalid root device type.
Expected 'ebs', got 'instance-store'.
```

I think its because the ExpectedRootDevice in the builder code is incorrect.
https://github.com/hashicorp/packer/blob/f7e269945eeb3dea14407f67f96e6e35714f5003/builder/amazon/instance/builder.go#L201
https://github.com/hashicorp/packer/blob/f7e269945eeb3dea14407f67f96e6e35714f5003/builder/amazon/instance/builder.go#L219

**Comment by mwhooker** [comment]
I think you're right, thanks for the report!

cc @ofosos

**Comment by ofosos** [comment]
Please test
