### ISSUE TITLE
LXD image builder hangs on Debian

### ISSUE THREAD

**Issue by zacksiri** [hashicorp/packer#5508]
I installed Packer on macOS and then i installed it on debian (machine running lxd) if i toggle the build from my macOS with remote set to the debian host the build succeeds

If i do the same on the debian host itself this is what i get

``` bash
2017/10/25 10:54:20 packer: 2017/10/25 10:54:20 [INFO] 285 bytes written for 'uploadData'
2017/10/25 10:54:20 [INFO] 285 bytes written for 'uploadData'
2017/10/25 10:54:20 packer: 2017/10/25 10:54:20 Running copy command: lxc file push - packer-base/tmp/script_213.sh
2017/10/25 10:54:20 packer: 2017/10/25 10:54:20 Retryable error: Error uploading script: exit status 1
```

## Steps to Reproduce
on a debian host
```
packer build template.json 
```

**Comment by mwhooker** [comment]
can you post the contents of template.json

**Comment by zacksiri** [comment]
``` 
{
  "builders":[
    {
      "type": "lxd",
      "name": "base",
      "image": "images:alpine/edge",
      "output_image": "artellectual/base"
    }
  ],
  "provisioners":[
    {
      "type": "file",
      "source": "./",
      "destination": "./"
    }, {
      "type": "shell",
      "script": "./setup.sh"
    }
  ]
}
```

**Comment by filterfish** [comment]
I'm having the same problem but fortunately I have an older version of `lxd` running and `packer` works with that version.

I _think_ file copying within `lxd` is currently broken which is causing problems with `packer`. See lxc/lxd/4050

**Comment by filterfish** [comment]
It would seem that `lxc file push` not working was a red herring; I hadn't restarted LXD after upgrading it.

@zacksiri try restarting LXD and see what happens.

**Comment by zacksiri** [comment]
@filterfish thank you! I think this can be closed.
