### ISSUE TITLE
alert users if their templates need fixing

### ISSUE THREAD

**Issue by mwhooker** [hashicorp/packer#5513]
We should add this only to `packer validate` or maybe also as a warning to `packer build`.

We have two options that I see:

1. Add a method to the Fixer struct which would return true if the template is fixable
2. Run every fixer and compare the output to the input.

I tend to prefer `2` because that way we don't have to change every fixer, and we get good information about what would be fixed

**Comment by SwampDragons** [comment]
I like idea #2 as well

**Comment by tylert** [comment]
As long as #5727 doesn't block someone from running "packer build" on a multi-stage build template, I would say that giving the user some kind of warning isn't a bad idea.  It sounds like your "option 2" would minimize the refactor.

I am currently in the process of automating the following steps/tests for my Packer-based projects (e.g.:  https://github.com/tylert/packer-build):
1. Convert YAML version of Packer template (containing comments, YAML anchors to improve "DRY" and do some external templating) to JSON in a temporary location.
1. Do some external templating on vagrantfile_template file, preseed/kickstart files, etc. using variables section of Packer template into a temporary location (for any stuff that isn't "inlined" in the Packer template itself;  still working on doing this in a not-too-ugly way).
1. Run ```packer validate``` on JSON version of Packer template.

**Comment by mwhooker** [comment]
I still think this is a good idea, but it's not something I'm going to be working on, so going to close. Happy to work with anyone that wants to take this over
