### ISSUE TITLE
InvalidKeyPair.Duplicate

### ISSUE THREAD

**Issue by zimbatm** [hashicorp/packer#552]
When targeting amazon-instance and amazon-ebs in the same build, one of both will fail because the temporary key pair has the same name:

```
==> amazon-instance: Creating temporary keypair: packer 52668615-9acb-0442-f0c5-341eaa209b8e
==> amazon-ebs: Creating temporary keypair: packer 52668615-9acb-0442-f0c5-341eaa209b8e
[snip]
Build 'amazon-ebs' errored: Error creating temporary keypair: Duplicate key found when creating keypair packer 52668615-9acb-0442-f0c5-341eaa209b8e (InvalidKeyPair.Duplicate)
```

**Comment by stagrlee** [comment]
I've been seeing this quite a bit today (version 0.7.5).  Stuck or terminated old packer runs leave behind lots of keypairs in AWS.  Cleaning them up seemed to help.  Not sure if this is a new issue or not.
