### ISSUE TITLE
"script disconnected unexpectedly" when performing a shell reboot in google cloud machine

### ISSUE THREAD

**Issue by Ohadbasan** [hashicorp/packer#5522]
I am using "googlecompute" builder.
the image building fails with Build 'googlecompute' errored: Script disconnected unexpectedly after a reboot.
when using the same provisioner with ec2 builder - the image is being created ok.

Describe the problem and include the following information:

- Packer version v1.1.1
- Mac OS
- Debug log: https://gist.github.com/Ohadbasan/d361bd791797deffa046fa3f3ef52316
- packer.json: https://gist.github.com/Ohadbasan/0319f3921e3fa4f21183a13c34fda476

**Comment by mwhooker** [comment]
trying setting `"expect_disconnect": true` in the shell script. I'll update the log output to suggest this
