### ISSUE TITLE
amazon-chroot builder requiring region parameter

### ISSUE THREAD

**Issue by slicc23** [hashicorp/packer#5524]
Packer version: 1.1.0
Host platform: CentOS 7.4
builder: amazon-chroot

When 'region' parameter is not specified this error occurs immediately after the EBS volume is detached and the snapshot is created :
`2017/10/27 10:19:13 ui error: Build 'mybuild' errored: Error describing AMI: MissingRegion: could not find region configuration`

AMI builds without issue once the region parameter is specified which according to the documentation is neither a required nor optional parameter.

**Comment by mwhooker** [comment]
hmm, we should be getting the region from the metadata endpoint.

Can you post your full log please? Need `PACKER_LOG=1` set

If for some reason the metadata endpoint isn't available, we should definitely fail early, because the region is required, technically

**Comment by mwhooker** [comment]
oh I see, that's not the session region, that's the region passed to `ami_regions`. Please also post your config that reproduces this issue

**Comment by mwhooker** [comment]
see #5250

**Comment by slicc23** [comment]
I confirmed that setting `ami-regions` fixes the issue as well. Should this be considered a required parameter now?

**Comment by mwhooker** [comment]
@slicc23 no, this is definitely a bug, but I'm glad you have a workaround. If you want to test the patch in #5250, which I think will fix it, I can merge it.
