### ISSUE TITLE
Docker-Push Returns Error After Docker-Tag    

### ISSUE THREAD

**Issue by jak119** [hashicorp/packer#5526]
When trying to use the following post processors after committing an image to Docker I'm receiving a Docker error stating `docker (docker-push): An image does not exist locally with the tag: sha256`. My expectation here would be that the SHA checksum would pass properly.

## Post Processor
```
"post-processors": [
    {
        "type": "docker-tag",
        "repository": "{{user `acr_name`}}/packer/ansible-test",
        "tag": "latest"
    },
    {
        "type": "docker-push",
        "login": "true",
        "login_username": "<my username>",
        "login_password": "<my key>",
        "login_server": "{{user `acr_name`}}"
    }
]
```

## Output from Post-Processing
```
==> docker: Running post-processor: docker-tag
    docker (docker-tag): Tagging image: sha256:cfdcefff332295a430764a71898316b304a290e5869039fea43664f35025dd54
    docker (docker-tag): Repository: <my account>.azurecr.io/packer/ansible-test:latest
==> docker: Running post-processor: docker-push
    docker (docker-push): Logging in...
    docker (docker-push): WARNING! Using --password via the CLI is insecure. Use --password-stdin.
    docker (docker-push): Login Succeeded
    docker (docker-push): Pushing: sha256:cfdcefff332295a430764a71898316b304a290e5869039fea43664f35025dd54
    docker (docker-push): An image does not exist locally with the tag: sha256
    docker (docker-push): The push refers to a repository [docker.io/library/sha256]
    docker (docker-push): Logging out...
    docker (docker-push): Removing login credentials for <my account>.azurecr.io
Build 'docker' errored: 1 error(s) occurred:

* Post-processor failed: Bad exit status: 1

==> Some builds didn't complete successfully and had errors:
--> docker: 1 error(s) occurred:

* Post-processor failed: Bad exit status: 1

==> Builds finished but no artifacts were created.

```

## Environment Details
Packer Version: v1.1.1
OS: CentOS Linux release 7.4.1708 (Core)
### Docker Version
 Version:      17.10.0-ce
 API version:  1.33
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:04:05 2017
 OS/Arch:      linux/amd64

**Comment by rickard-von-essen** [comment]
You need to run the post-processors in a sequence see the [docs](https://www.packer.io/docs/templates/post-processors.html#post-processor-definition).

**Comment by jak119** [comment]
The post-processors are in the order as described in the [Docker builder page](https://www.packer.io/docs/builders/docker.html#using-the-artifact-export) with the `docker-push` block appearing last.

This more specifically matches [this example](https://medium.com/@kcearns/packer-and-docker-push-9537b6c0ec89) of a tag then push post-processor.

**Comment by rickard-von-essen** [comment]
No it doesn't, you're missing one level of brackets (`[ ]`). :duck:

**Comment by jak119** [comment]
Certainly not the error I was expecting but you're correct. Thank you for that, I'll go ahead and close this.
