### ISSUE TITLE
Regression: amazon-ebsvolume can not create/mount any EBS volume in v.1.1.1

### ISSUE THREAD

**Issue by sarasonparas** [hashicorp/packer#5528]
Packer version: 1.1.1
Used template and output of debug log: 
https://gist.github.com/sarasonparas/6b600a4e7b725eed3a7d8de9cefb24cf
Host: MacOS v. 10.12.6  (the same problem is with Amazon Linux, but the provided log is for Mac)  

The same template does work with v.1.1.0, but doesn't with v. 1.1.1.

amazon-ebsvolume builder can't find any EBS volume. I've checked that in the debug mode:

'ls -la /dev/' command doesn't show any additional block device. Waiting for the devices doesn't help.

EDIT: the same problem occurs with any default VPC/subnet.

**Comment by rickard-von-essen** [comment]
I think this duplicates #5486

**Comment by mwhooker** [comment]
this is fixed in master now. thanks for the report!
