### ISSUE TITLE
Unable to specify ipv6 option in digitalocean builder

### ISSUE THREAD

**Issue by lisimia** [hashicorp/packer#5533]
DigitalOcean provides their droplets ipv6 connectivity, this option is exposed as a checkbox on the UI. And within the v2 API: 
```
ipv6 | Boolean | A boolean indicating whether IPv6 is enabled on the Droplet.
```

However, this option is not available in the "digitalocean" builder.

**Comment by rickard-von-essen** [comment]
PR's are welcome.
