### ISSUE TITLE
Any file with names `*utils.sh` causes packer build to fail

### ISSUE THREAD

**Issue by lhriley** [hashicorp/packer#5540]
When building a packer image, if the contents of an uploaded folder includes a file named `*utils.sh`, the build will fail with the message:

```
Build 'bastion' errored: Error removing temporary script at /tmp/script_7862.sh!
```
This appears to happen with any iteration of `*utils.sh`, and has been tested with names similar to `something_utils.sh`, `utils.sh`, etc. This occurs even when `utils.sh` is an empty file.

- Packer version: `1.1.1`
- Host platform: `Linux Mint 18.2`
- Target platform: `amzn-ami-hvm-2017.09.0.20170930-x86_64-gp2`
- Debug log output: https://gist.github.com/lhriley/42707f09bc7cad760d3d0ab09915ace0
- Steps to reproduce: https://gist.github.com/lhriley/7099a51a22e99fabda1649e068a63e00

**Comment by mwhooker** [comment]
this issue seems to be with removing the remote temp file we write the last provisioner to. Is there any code in `base.sh` that changes ownership of `/tmp`? 

Does it work if you add `"remote_folder": "/home/ec2-user"` to the final shell provisioner step?

**Comment by lhriley** [comment]
No, there are no changes to anything `/tmp` that comes from our provisioning scripts. I checked all `rm`, `mv`, `chmod`, `chown`, etc commands (really anything that has `/tmp` in the path) and none of them target anything in `/tmp` directly. In fact, the `utils.sh` script that was being added isn't called by any of the provisioning scripts.

Again, it doesn't seem actually make any difference since I can duplicate this issue by simply touching a file named `utils.sh` into existence. If I remove that file, the packer build completes without error. Moreover, I can put the content of the `utils.sh` script into another script that is actually called and it doesn't cause any issues, either. So, it can only be the filename that is somehow causing this problem. I find it extremely strange.

As you requested, I added the `"remote_folder": "/home/ec2-user"` option to the shell provisioner and the results were unchanged.

**Comment by mwhooker** [comment]
well unfortunately I'm unable to reproduce the issue. if you can create a more slimmed down reproduction use-case, (ideally something I can download and run), I can investigate further.

```
{
    "builders": [
        {
            "ami_name": "packer-qs-{{timestamp}}",
            "instance_type": "t2.micro",
            "source_ami_filter": {
                "filters": {
                    "name": "*ubuntu-xenial-16.04-amd64-server-*",
                    "root-device-type": "ebs",
                    "virtualization-type": "hvm"
                },
                "most_recent": true,
                "owners": [
                    "099720109477"
                ]
            },
            "ssh_username": "ubuntu",
            "type": "amazon-ebs"
        }
    ],
    "provisioners": [
        {
            "inline": [
                "mkdir -p /tmp/packer/base/"
            ],
            "type": "shell"
        },
        {
            "destination": "/tmp/packer/base",
            "source": "5540",
            "type": "file"
        },
        {
            "environment_vars": [
                "CONSUL_VERSION=01234"
            ],
            "inline": [
                "echo foo"
            ],
            "type": "shell"
        }
    ]
}
```

```
~/dev/packertest ᐅ ls -l 5540
total 0
-rw-r--r--  1 mwhooker  staff  0 Nov  2 12:52 foo.sh
-rw-r--r--  1 mwhooker  staff  0 Nov  2 12:40 foo.txt
-rwxr-x---  1 mwhooker  staff  0 Nov  2 12:40 utils.sh
```

**Comment by lhriley** [comment]
Hmm. Unfortunately, I was anticipating that this would be difficult to reproduce. I'll see if I can come up with a reproducible model that I can provide for testing.

**Comment by lhriley** [comment]
I grabbed some more data from the instance. I ran an `ls` on `/tmp` directly before the error occurs:

```
-rwxr-xr-x  1 ec2-user ec2-user 1.4K Nov  2 21:29 script_8023.sh
```
Followed by the error messages:
```
2017/11/02 14:30:17 packer_v1.1.1: 2017/11/02 14:30:17 opening new ssh session
2017/11/02 14:30:17 packer_v1.1.1: 2017/11/02 14:30:17 starting remote command: rm -f /tmp/script_8023.sh
2017/11/02 14:30:17 packer_v1.1.1: 2017/11/02 14:30:17 Remote command exited with '2': rm -f /tmp/script_8023.sh
2017/11/02 14:30:17 packer_v1.1.1: 2017/11/02 14:30:17 [INFO] RPC endpoint: Communicator ended with: 2
2017/11/02 14:30:17 [INFO] RPC client: Communicator ended with: 2
2017/11/02 14:30:17 [INFO] RPC endpoint: Communicator ended with: 2
2017/11/02 14:30:17 packer_v1.1.1: 2017/11/02 14:30:17 [INFO] RPC client: Communicator ended with: 2
2017/11/02 14:30:17 [INFO] (telemetry) ending shell
2017/11/02 14:30:17 [INFO] (telemetry) found error: Error removing temporary script at /tmp/script_8023.sh!
```

I then ran another build where I `chmod 777 /tmp/script_*.sh`:

```
-rwxrwxrwx  1 ec2-user ec2-user 1.5K Nov  2 21:38 script_8876.sh
```
Followed by the same error:
```
2017/11/02 14:39:46 packer_v1.1.1: 2017/11/02 14:39:46 opening new ssh session
2017/11/02 14:39:46 packer_v1.1.1: 2017/11/02 14:39:46 starting remote command: rm -f /tmp/script_8876.sh
2017/11/02 14:39:46 packer_v1.1.1: 2017/11/02 14:39:46 Remote command exited with '2': rm -f /tmp/script_8876.sh
2017/11/02 14:39:46 packer_v1.1.1: 2017/11/02 14:39:46 [INFO] RPC endpoint: Communicator ended with: 2
2017/11/02 14:39:46 [INFO] RPC client: Communicator ended with: 2
2017/11/02 14:39:46 [INFO] RPC endpoint: Communicator ended with: 2
2017/11/02 14:39:46 packer_v1.1.1: 2017/11/02 14:39:46 [INFO] RPC client: Communicator ended with: 2
2017/11/02 14:39:46 [INFO] (telemetry) ending shell
2017/11/02 14:39:46 [INFO] (telemetry) found error: Error removing temporary script at /tmp/script_8876.sh!
```
So, I resolved that this can't actually be a permissions error and this started to feel more like `utils.sh` was a red herring. After digging deeper, I started to comment out functions that were sourced into a `profile.d` script. Eventually this resulted in a build that completed successfully.

It turns out that the culprit was actually `tput` failing to determine what terminal was in use when the next shell was spawned. This is what was giving the `exit code 2` and not actually an inability to remove the `/tmp/script_*.sh` file. Unfortunately, I wasn't able to find a fix to this so I have commented out our use of `tput` until I can find an appropriate solution to this problem.

Thanks for taking a look.
