### ISSUE TITLE
FEATURE REQUEST: Make packer -v flag output consistent with other Hashicorp tools

### ISSUE THREAD

**Issue by Chr1d5ter** [hashicorp/packer#5544]
Executing packer -v simply outputs the version number and not the product name. Whereas vagrant and terraform output the product name followed by the version number. 

( Sorry to raise this but I can't keep this to myself any longer it's burned away at my soul for too long now.  )

![capture](https://user-images.githubusercontent.com/20554449/32405977-7adc19d2-c167-11e7-926f-7ae65fcb7f93.PNG)

*I actually feel better now I've raised it*

Thanks

**Comment by mwhooker** [comment]
Thank you for bringing this very important issue to our attention! I like this in theory, but I worry that it will break people's scripts which may be parsing out the version.

My recommendation is to instead use `packer version`:
```
packer version && vagrant -v && terraform -v
Packer v1.1.2-dev (7b974a53c+CHANGES)
Vagrant 1.8.5
Terraform v0.11.0-dev (645df36af02547b298dbeaeb85ca487423007807)
```

**Comment by Chr1d5ter** [comment]
Thanks for responding. I do realise it's a tiny thing and didn't consider the implications of changing it.

Seriously though, I love the work that you guys are doing. 

All the best
