### ISSUE TITLE
[RFC] Support HCL everywhere JSON is currently supported.

### ISSUE THREAD

**Issue by tamsky** [hashicorp/packer#5545]
cf. https://github.com/hashicorp/packer/issues/1768#issuecomment-300841374
> The next step for us is to go through our RFC process, which would be on a separate issue.

Proposal:

Ability to run:
`packer build -var-file=myvars.hcl template.hcl`

[ I'm hoping this starts the RFC process, as I was unable to find any existing RFC covering this subject. ]

**Comment by mwhooker** [comment]
Thanks for this. This is definitely a priority, but currently we're still discussing it internally. We'll definitely be waiting until [hcl 2.0](https://github.com/hashicorp/hcl2) is finalized.  Honestly, this ticket isn't going to have any effect on the process, so I'm going to close it.
