### ISSUE TITLE
Bake AMI using Packer behind Proxy

### ISSUE THREAD

**Issue by sumitmathur** [hashicorp/packer#5546]
We are using Packer for baking an AMI in AWS and we are running packer on server in datacenter. The server does not have direct Internet connectivity and it connect to internet v.i.a proxy. 

We have setup proxy command on server to ssh to EC2 instances and it work well. 

However when we run packer to bake an AMI it timed out at SSH and we get below error

`"Build 'amazon-ebs' errored: Timeout waiting for SSH."`

Please let us know how we can bake an AMI using packer from server behind proxy.

Config file configuration ( ~/.ssh/config) with host 10.86.* are our EC2 IP's
```
 Host bastion0 b0
     Hostname <Bastion_PUBLIC_IP>
     User ec2-user
     IdentityFile <Pem File Path>
     ProxyCommand nc -v -X connect -x <PROXY_IP>:80 %h %p


Host 10.86.*.*
     User ec2-user
     ProxyCommand ssh bastion0 -W %h:%p
     IdentityFile <Pem File Path>
```

**Comment by rickard-von-essen** [comment]
Packer don't use OpenSSh and thus don't read `~/.ssh/config`.

I recommend that you instead run packer from another EC2 instance (or change your firewall policy so you don't need to circumvent it).

**Comment by mwhooker** [comment]
We recently merged support for socks5 proxies https://github.com/hashicorp/packer/pull/5439 and it should be available in the next release
