### ISSUE TITLE
Build 'openstack' errored: Error initializing compute client: No suitable endpoint could be found in the service catalog.

### ISSUE THREAD

**Issue by pouyana** [hashicorp/packer#5549]
Creating new images using OpenStack delivers the following error. It is very cryptic, as a result I don't know where should I look for errors. The compute endpoint is available in catalog list. (Third Gist)

```
Build 'openstack' errored: Error initializing compute client: No suitable endpoint could be found in the service catalog.
```

Packer Version : `1.1.1`

The provisioner can be seen here:
[Gist](https://gist.github.com/pouyana/8d66f1b204188eccff75309794d2e5aa)

Partial Debug can be seen here:
<s>[Gist](https://gist.github.com/pouyana/dfe5f93bd551118f6979fdce4d9c37ec)</s>
[Full Gist](https://gist.github.com/pouyana/4c1d00bf4f74ff0612b1d16a8c3d7ff7)

Running `openstack catalog list` delivers this gist
[Gist](https://gist.github.com/pouyana/7ad4c3ad7e4e2b8b45ecd1032ab2f289)

**Comment by rickard-von-essen** [comment]
Please [gist](https://gist.github.com/) a full debug log from `PACKER_LOG=1 packer build template.json`.

**Comment by pouyana** [comment]
@rickard-von-essen It is done.
[Gist](https://gist.github.com/pouyana/4c1d00bf4f74ff0612b1d16a8c3d7ff7)

**Comment by rickard-von-essen** [comment]
This is interesting. Looks like there has been a back wards incompatible change in OS where v2 nova API now is called `nova_legacy`.

**Comment by pouyana** [comment]
So, I double checked my settings and find out that OS generated RC file I used did not have the `tenant_name` and packer does not use `$OS_USER_PROJECT_ID` included. I just added  everything in `packer.json` file and tried again and everything worked. Thanks any way

**Comment by rickard-von-essen** [comment]
Ok great! I'll close this then.

**Comment by indajuan** [comment]
I have the same problem, I have not been able to fix it with pouyana solution
