### ISSUE TITLE
packer fails with "VPCIdNotSpecified"

### ISSUE THREAD

**Issue by FernandoMiguel** [hashicorp/packer#5550]
Describe the problem and include the following information:
aws account without a default VPC.
vpcid and subnetid are passed as env vars.
packer fails with "VPCIdNotSpecified"

- Packer version from `packer version`
packer --version
1.0.2

- Host platform
aws AMI ami-47d6723e 
Ubuntu 17.04 64 bits
eu-west-1
t2.micro

- Debug log output from `PACKER_LOG=1 packer build template.json`.
https://gist.github.com/FernandoMiguel/1aef33546e56caf93d554b94637e3bd9

- The _simplest example template and scripts_ needed to reproduce the bug.
json https://gist.github.com/FernandoMiguel/5fb723a1b98da9c32001adbc7f2a2bb1
vars https://gist.github.com/FernandoMiguel/2987d5849e495f32f04758e6a33c8220

**Comment by rickard-von-essen** [comment]
Did you export those values?

**Comment by FernandoMiguel** [comment]
yep, before a previous run.

**Comment by rickard-von-essen** [comment]
(I don't want to chase any ghosts). What's the output of `bash -c 'echo $vpc_id'`

**Comment by FernandoMiguel** [comment]
empty.
but it shows in set | grep -i vpc

**Comment by rickard-von-essen** [comment]
So you need to `export vpc_id` etc.

**Comment by FernandoMiguel** [comment]
ok, let me try that instead
