### ISSUE TITLE
validate bug: Forgets that script filenames are relative to template's parent directory

### ISSUE THREAD

**Issue by mcandre** [hashicorp/packer#5553]
Describe the problem and include the following information:

- Packer version from `packer version`: Packer v1.1.2-dev
- Host platform: macOS
- The _simplest example template and scripts_ needed to reproduce the bug:

```json
{
  "builders": [
    {
      "type": "virtualbox-iso",
      "guest_os_type": "Debian_64",
      "vm_name": "debian",
      "iso_url": "http://cdimage.debian.org/cdimage/release/9.2.1/amd64/iso-cd/debian-9.2.1-amd64-netinst.iso",
      "iso_checksum_type": "sha512",
      "iso_checksum": "ebfe25dc593967e39349b205480b0ec0103ef4a0468c602f4857e13d06d407bfe876162399e0e8d4dea5675953dc37ab585316f307ccf9f4440124b4f719df04",
      "ssh_username": "vagrant",
      "ssh_password": "vagrant",
      "ssh_wait_timeout": "1800s",
      "http_directory": "http",
      "boot_command": [
        "<esc><wait>",
        "install ",
        "preseed/url=http://{{.HTTPIP}}:{{.HTTPPort}}/preseed.cfg ",
        "locale=en_US ",
        "kbd-chooser/method=us ",
        "keyboard-configuration/xkb-keymap=us ",
        "netcfg/get_hostname={{.Name}} ",
        "netcfg/get_domain=vagrantup.com ",
        "<enter><wait>"
      ],
      "shutdown_command": "sudo halt -p",
      "headless": true
    }
  ],
  "provisioners": [
    {
      "type": "shell",
      "execute_command": "echo 'vagrant' | {{.Vars}} sudo -E S sh '{{.Path}}'",
      "scripts": [
        "bootstrap.sh"
      ]
    }
  ],
  "post-processors": [
    {
      "type": "vagrant",
      "output": "debian-{{.Provider}}.box"
    }
  ]
}
```

I am storing this packer template in `debian/debian.json`, and the bootstrap provisioning script in `debian/bootstrap.sh`.

When I `cd` to `debian`, `packer validate debian.json` passes. However, when I try to validate from the parent directory `packer-templates`, running `packer validate debian/debian.json`, then the validator forgets that provisioning script paths are relative to the template's parent directory, and so the packer validator mistakenly reports that the provisioning scripts are missing.

**Comment by rickard-von-essen** [comment]
It's not relative to the template, see [docs - shell provisioner](https://www.packer.io/docs/provisioners/shell.html#script).
