### ISSUE TITLE
How to input greater-than, less-than literals in boot_command's?

### ISSUE THREAD

**Issue by mcandre** [hashicorp/packer#5565]
FOR FEATURES:

How are we supposed to enter a greater-than (`>`) or less-than (`<`) literal into a boot_command?

I think en-US QWERTY keyboard users can work around this limitation by applying a Shift modifier to the comma and period respectively, but this is fragile. Would be helpful for packer to offer `<gt>`, `<lt>`, similar to HTML for reliably inputting these keys.

**Comment by mwhooker** [comment]
Can you not just put `<`  in the boot command? The support is there: https://github.com/hashicorp/packer/blob/52fc0100ebe0b7f856fba65e1f178840d3e9aea5/builder/vmware/common/step_type_boot_command.go#L187

If it doesn't work please open a new issue with the error you get

**Comment by mcandre** [comment]
@mwhooker How would a user input the literal sequence `<esc>` without having this be parsed by packer as the Escape key?

**Comment by mwhooker** [comment]
is that a need you have?
