### ISSUE TITLE
Azure : Validate the managed image name regex before execution

### ISSUE THREAD

**Issue by duckie** [hashicorp/packer#5568]
Hi all

When building an Azure managed image, if the image name does not meet the requirements, Packer yields on the Azure error at the very end of the provisioning.

```==> azure-arm: ERROR: -> InvalidParameter : The entity name 'name' is invalid according to its validation rule: ^[^_\W][\w-._]{0,79}(?<![-.])$.```

This is unfortunate since such a discrepency could have been detected in the `validate` step as well as being checked *before* provisioning the resources.

It would be great to add this check.

**Comment by boumenot** [comment]
Thanks for opening an issue @duckie.

I have prepared a PR to address this issue, but can you please confirm the entity in question.  Is it a resource group?  The error message provides a regular expression, but I am unsure what value I should be qualifying it against.  The Azure [docs](https://docs.microsoft.com/en-us/azure/architecture/best-practices/naming-conventions#naming-rules-and-restrictions) seem to suggest that this is either an Availability Group or a networking entity.  The Azure builder does not build either of those.  My second guess is this is you overriding temp_resource_group_name, but in that case the regular expression is wrong based on the docs.

**Comment by duckie** [comment]
Hi @boumenot 

Nope, the property on which an invalid value may fail the process is `managed_image_name`. I do not override `temp_resource_group_name`, nor does it have to do with networking. The Azure API call fails when all the build is a success and you want to make an image from the virtual machine.

**Comment by duckie** [comment]
Hi @boumenot 

Why did you close it ? It is not related to your PR about resource groups, or did I miss someting ?

**Comment by boumenot** [comment]
The code checks the resource group name, and the managed disk name.  The title only said resource group name - sorry.  If you are so inclined please review the commit, or try the change and see if it catches your error.  I am interested and seeing if it does.
