### ISSUE TITLE
packer looks for sources in different paths unexpectedly

### ISSUE THREAD

**Issue by caphrim007** [hashicorp/packer#5569]
When packer is run with multiple `-only` values and `parallel` set to `false`, then the second `only` value will have its paths interpreted from `/` instead of as relative (the default behavior that I observe).

For example, a template uses `virtualbox-ovf` and includes this `source_path`
`"source_path": "output-virtualbox-iso/foo.ovf",`

When run with the following command, everything works fine and the `ovf` file is found.
* `packer build -only=virtualbox-ovf template.json`

However, using the __same__ template, when run with the next command, `packer` attempts to look for the file at `/output-virtualbox-iso/foo.ovf`; note the root path
* packer build -only=virtualbox-iso,virtualbox-ovf -parallel=false template.json

I would expect the second value in `-only` to behave as it does when there is just one value in `-only`, but it does not.

- Packer version from `packer version`
SEA-ML-00028116:bigip-14.0.0.0-x86_64 trupp$ packer -version
1.1.1

- Host platform
macOS Sierra
version 10.12.6

- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a gist https://gist.github.com

Example of using `PACKER_LOG=1 packer build -only=virtualbox-iso,virtualbox-ovf -parallel=false template.json` note lines 698 to 712
* https://gist.github.com/caphrim007/e4115e774c9df70eac8cf07b201cc08d

Example of using `PACKER_LOG=1 packer build -only=virtualbox-ovf template.json`. Note lines 344 to 352
* https://gist.github.com/caphrim007/4a54a8f787964b692b3e7238394b7c9b

- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your gist https://gist.github.com

Here is a an template
https://gist.github.com/caphrim007/76360a4c7e5d49cb1eaa1dc2e87cf05c
though I dont expect it to work for most of the public because it uses an ISO that is not publicly available at the moment.

Instead, I'm providing it for reference incase there is something syntactically that you're interested in knowning

**Comment by SwampDragons** [comment]
Thanks -- I've reproduced using your case.

**Comment by SwampDragons** [comment]
Actually, I get the assumed root path in both your cases....

**Comment by caphrim007** [comment]
@SwampDragons then explain the difference in outputs

**Comment by SwampDragons** [comment]
Okay, so I've spent some time tinkering with the DownloadableURL function.  I can't get my repro to actually depend on the -only flag like you did, but between messing with the function and reading through the code, I think your issue lies [here](https://github.com/hashicorp/packer/blob/79fcd40bfcafad3c3fb45273b0746c983d69d2c6/common/config.go#L85-L100). 

If the file doesn't exist at the given relative path, then it doesn't generate the absolute path, instead just throwing a "/" at it [here](https://github.com/hashicorp/packer/blob/79fcd40bfcafad3c3fb45273b0746c983d69d2c6/common/config.go#L116-L118)  and calling it good.  

Are you sure that your source files exist at the time the filepath is being tested and the url generated?

**Comment by caphrim007** [comment]
It exists after the first only runs. Does it need to exist before this? Is packer looking for its existence when the template is parsed? or when the builder is actually run?

**Comment by SwampDragons** [comment]
It needs to exist when the template is parsed.

**Comment by caphrim007** [comment]
ugh, then no, it doesnt. guess i'll have to run packer twice then

**Comment by SwampDragons** [comment]
You can probably write a wrapping shell script fairly easily so that you don't have to sit around and wait for the build to complete.  Sorry for the frustration.

**Comment by caphrim007** [comment]
i do that today
