### ISSUE TITLE
Use Chef policyfile?

### ISSUE THREAD

**Issue by luckytaxi** [hashicorp/packer#5574]
We're starting to move our Chef install to use Policyfile instead of roles/environment. We have a bunch of cookbooks that are referenced via Github within the policyfile. My issue is, when I apply the run_list to Packer in order to build our AMIs, the cookbooks that need to come from GH aren't available. Using Policyfiles, these cookbooks get downloaded and packaged for use. 

Is there a workaround to this when using the Chef-solo provisioner within Packer?

**Comment by spuder** [comment]
[Chef-Solo documentation](https://docs.chef.io/ctl_chef_solo.html) doesn't list any way to use policyfiles. Do you have an example?[

**Comment by emachnic** [comment]
Maybe using local mode might work for this. I've outlined how to do it with Policyfiles in general but I'm wondering if it could be adapted for Packer https://medium.com/@emachnic/using-policyfiles-with-chef-client-local-mode-4f47477b24db

**Comment by emachnic** [comment]
Thinking about this a bit more, maybe the `policy_group` and `policy_name` options should be available in the config. Then I _think_ that if you have those available on the Chef server it should work.
