### ISSUE TITLE
OpenStack builder should warn instead of fail on terminate if instance is already shut down

### ISSUE THREAD

**Issue by trodemaster** [hashicorp/packer#5575]
With our windows packer builds we need to handle shutting instances down gracefully via sysprep. While investigating all the different workarounds I discovered that the OpenStack builder has undesirable handling of terminating instances that are already "shut off". 

Currently packer will throw an error and stop the build if it attempts to shut down an instance that is already shut down. Instead of erroring and stopping the build packer should just throw a warning and proceed with the build. 

- Packer version from Packer v1.1.2-dev
- Host platform macOS 10.13.1
- Debug log output from https://github.com/trodemaster/packer-openstack-shutdown/blob/master/packer-build.log
- Repo for test case https://github.com/trodemaster/packer-openstack-shutdown

The Repo linked is for testing with linux images as that's much quicker to work with. However this will improve the situation for sysprepping OpenStack instances.

**Comment by rickard-von-essen** [comment]
Sounds resonable. PR's are welcome.

**Comment by winklerm** [comment]
I have sent a PR with a proposed fix, please take a look. Thank you!
