### ISSUE TITLE
ESXi 6.5: no suitable auth schemes

### ISSUE THREAD

**Issue by Lee303** [hashicorp/packer#5580]
When using the vmware-iso builder with ESXi 6.5, the following build error occurs:

```
Build 'vmware-iso' errored: Error handshaking with VNC: no suitable auth schemes found. server supported: []byte{0x1}
```

Packer version:
```
[root@packer-01 centos7]# packer version
Packer v1.1.1
```

**Comment by Lee303** [comment]
It would appear that setting ``vnc_disable_password`` to ``true`` works around this issue

**Comment by rickard-von-essen** [comment]
Your analysis is correct. Your ESXi doesn't support VNC auth with username/password.
