### ISSUE TITLE
packer exits when converting iso to ova

### ISSUE THREAD

**Issue by subbu05** [hashicorp/packer#5584]
Unable to convert iso to ova using packer on Mac OS.

OS:
ProductName:	Mac OS X
ProductVersion:	10.13.1
BuildVersion:	17B48

packer version
Packer v1.1.1

Failed to initialize build 'vmware-iso': error initializing builder 'vmware-iso': plugin exited before we could connect
vmware-iso output will be in this color.

==> Builds finished but no artifacts were created.

Attached the logs.

**Comment by subbu05** [comment]
[log.txt](https://github.com/hashicorp/packer/files/1472876/log.txt)

**Comment by mwhooker** [comment]
you have a very old version of packer installed. please run 

`rm /usr/local/bin/packer-*` and then reopen if you still see errors.
