### ISSUE TITLE
Install failure in Ubuntu 14.04

### ISSUE THREAD

**Issue by mcandre** [hashicorp/packer#5585]
FOR BUGS:

go get fails to install packer on my machine.

- Host platform: Ubuntu 14.04 LTS

Trace:

```console
$ go get github.com/hashicorp/packer
go build github.com/hashicorp/packer: /home/andrew/.gvm/gos/go1.9/pkg/tool/linux_amd64/link: signal: killed

$ go version
go version go1.9 linux/amd64
```

**Comment by mwhooker** [comment]
I'm afraid I'm unable to reproduce this issue

```
root@502b32dfad7a:/# go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/usr/local/go/"
GORACE=""
GOROOT="/go"
GOTOOLDIR="/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
root@502b32dfad7a:/# go get github.com/hashicorp/packer
root@502b32dfad7a:/# packer version
Packer v1.1.2-dev
root@502b32dfad7a:/# go version
go version go1.9.2 linux/amd64
root@502b32dfad7a:/# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"
```

You could try upgrading to go 1.9.2


This sounds like your system could be running out of memory, is that possible?

If so you can probably work around it with `go get -p 1 github.com/hashicorp/packer`

good luck

**Comment by mcandre** [comment]
Update: Apparently, a lot of things break when Ubuntu is installed in VMware with all defaults and RAM is therefore limited to a mere 1GB! When the virtual machine is reconfigured to use more memory, then packer successfully installs with `go get github.com/hashicorp/packer` as usual!
