### ISSUE TITLE
ISO download failed, wrong iso_url variable

### ISSUE THREAD

**Issue by megian** [hashicorp/packer#5589]
- Packer 1.1.2
- Host Windows 7 64 Bit

With Packer 1.1.2 (Dosn't work file://):
```
PS C:\ISOs\packer> .\build-W2k16.ps1
vmware-iso output will be in this color.

==> vmware-iso: Downloading or copying ISO
    vmware-iso: Downloading or copying: file://C:/ISOs/packer/en_windows_server_
2016_x64_dvd_9718492.iso
    vmware-iso: Error downloading: CreateFile ISOs/packer/en_windows_server_2016
_x64_dvd_9718492.iso: The system cannot find the path specified.
==> vmware-iso: ISO download failed.
```

With Packer 1.1.1 (does work file:///):
```
PS C:\ISOs\packer> .\build-W2k16.ps1
vmware-iso output will be in this color.

==> vmware-iso: Downloading or copying ISO
    vmware-iso: Downloading or copying: file:///C:/ISOs/packer/en_windows_server
_2016_x64_dvd_9718492.iso
```

Is it possible to add the third slash back to the path variable?

**Comment by SwampDragons** [comment]
Shoot.  Sorry for this; I didn't realize this change would be BC-breaking.  In your config, is the URL given as `C:/ISOs/packer/en_windows_server` or `/C:/ISOs/packer/en_windows_server`?  For now, my guess is that you can work around by prepending with the `/` like that second option shows.

**Comment by mwhooker** [comment]
see #5573

**Comment by SwampDragons** [comment]
[packer.zip](https://github.com/hashicorp/packer/files/1479912/packer.zip)
@megian Can you try this dev version of packer and let me know if it fixes your issue?

**Comment by megian** [comment]
Did work as relative path and relative path in a sub directory. The issue is fixed in the dev version.

**Comment by SwampDragons** [comment]
Cool, thanks.

**Comment by molant** [comment]
@SwampDragons doesn't seem to work for me. I'm using the file you've shared but I'm getting the following:

```text
2018-01-10T08:44:34 Starting packer for Windows VirtualBox Win81 IE11...
==> virtualbox-iso: Downloading or copying Guest additions
    virtualbox-iso: Downloading or copying: file://C:/Program%20Files/Oracle/VirtualBox/VBoxGuestAdditions.iso
    virtualbox-iso: Error downloading: GetFileAttributesEx /Program Files/Oracle/VirtualBox/VBoxGuestAdditions.iso: The system cannot find the path specified.
==> virtualbox-iso: Guest additions download failed.
```

with the public version I get the following:

```text
2018-01-10T08:48:11 Starting packer for Windows VirtualBox Win81 IE11...
==> virtualbox-iso: Downloading or copying Guest additions
    virtualbox-iso: Downloading or copying: file://C:/Program%20Files/Oracle/VirtualBox/VBoxGuestAdditions.iso
    virtualbox-iso: Error downloading: CreateFile /Program Files/Oracle/VirtualBox/VBoxGuestAdditions.iso: The system cannot find the path specified.
==> virtualbox-iso: Guest additions download failed.
```

One has `GetFileAttributesEx` and the other `CreateFile` 

Running the latest stable version of Windows 10

**Comment by SwampDragons** [comment]
@molant your issue is probably related to https://github.com/hashicorp/packer/pull/5761; I'm going to upload a binary of that branch shortly

**Comment by molant** [comment]
Thanks!

**Comment by atripath938** [comment]
> Shoot. Sorry for this; I didn't realize this change would be BC-breaking. In your config, is the URL given as `C:/ISOs/packer/en_windows_server` or `/C:/ISOs/packer/en_windows_server`? For now, my guess is that you can work around by prepending with the `/` like that second option shows.

Where is the config file located?

**Comment by SwampDragons** [comment]
@atripath938 the packer template or var file or wherever you're giving the url for the download.

This is a pretty old closed issue, so if you're seeing something else it's probably a new issue. If you can't figure it out, can you open a new issue for me?
