### ISSUE TITLE
Shell provisioner "chmod: cannot access '/tmp/script_8280.sh'" unless pause_before used

### ISSUE THREAD

**Issue by edmorley** [hashicorp/packer#5590]
In travis-ci/packer-templates#544, the packer docker builds are intermittently failing for Ubuntu Xenial images - and whilst this was resolved by adding a `pause_before` to the very first provisioner, it seems like the packer error reporting in this case is not surfacing the real issue correctly, making it harder to debug than it should be.

## STR
Using:
* a Travis GCE Ubuntu Trusty environment host environment ([.travis.yml](https://travis-ci.org/travis-infrastructure/packer-build/jobs/303002191/config))
* docker-ce 17.10.0
* packer 1.1.2
* and the following config (I've created a [reduced testcase](https://github.com/travis-ci/packer-templates/blob/7bb80b8bb082746f85a5e2914343e9c518fcb9d5/ci-opal.yml) and converted from the yaml representation used there):

```js
{
  "description": "[secure] opal build env template",
  "builders": [
    {
      "type": "docker",
      "name": "docker",
      "ssh_pty": true,
      "image": "travisci/gce-parity:16.04",
      "run_command": [
        "-d",
        "-i",
        "-t",
        "--privileged=true",
        "--storage-opt=size=11G",
        "{{ .Image }}",
        "/sbin/init"
      ],
      "commit": true
    }
  ],
  "provisioners": [
    {
      "type": "shell",
      "inline": "apt-get update -yqq && apt-get install sudo -yqq"
    }
  ]
}
```
(The dockerfile for the referenced image can be found [here](https://github.com/travis-ci/nightwhale/blob/9759dbe8835f8a59142dda7cc9a8c0fc9fbb7196/gce-parity/16.04/Dockerfile))

## Expected
For the build to succeed, or else in the case of failure, for the error message to clearly indicate the cause.

## Actual
The provisioner intermittently fails ~90% of the time, due to not being able to access the temporary script that packer uploads for the inline shell provisioner:

```
==> docker: Starting docker container...
    docker: Run command: docker run -v /home/travis/.packer.d/tmp/packer-docker466845333:/packer-files -d -i -t --privileged=true --storage-opt=size=11G travisci/gce-parity:16.04 /sbin/init
    docker: Container ID: 39e88f2dc4548dd3d17895e30c8f23b77a8b475da48e83dbbc7d96f495656cd7
==> docker: Provisioning with shell script: /tmp/packer-shell226250824
    docker: chmod: cannot access '/tmp/script_8280.sh': No such file or directory
    docker: /bin/sh: 1: /tmp/script_8280.sh: not found
==> docker: Killing the container: 39e88f2dc4548dd3d17895e30c8f23b77a8b475da48e83dbbc7d96f495656cd7
Build 'docker' errored: Script exited with non-zero exit status: 127
```

Adding a `"pause_before": "5s"` to the provisioner makes that step succeed 100% of the time ([example successful build](https://travis-ci.org/travis-infrastructure/packer-build/builds/303003815#L700)), which makes me guess that the upload had failed due to SSHing into the container too soon (presumably the container is taking a while to start).

However if the upload of the script had failed, then it seems like packer should report an SSH timeout or upload error, rather than proceeding to the chmod/run script part regardless.

For the `PACKER_LOG=1` output, see the full log here:
https://travis-ci.org/travis-infrastructure/packer-build/builds/303044344#L727

Strangely the debug output of failing builds vary - sometimes (such as the log linked above) it includes:
`RPC client: Communicator ended with: 1`
...whereas other times that line has a code of zero not one (such as [this time](https://travis-ci.org/travis-infrastructure/packer-build/builds/303002190#L709)).

Another data-point - removing the custom `run_command` from the config above seemed to resolve the intermittent failures. I tried to bisect the docker run options further, however it seemed that specifying any of the custom options without the others resulted in a successful build (I'm guessing the combination of them slows down the container startup time just enough to race with the provisioner).

If there's anything else that would be useful to know, please ask!

Many thanks :-)

**Comment by rickard-von-essen** [comment]
Don't have a computer with me at the moment but there are a few things in your report and template that looks strange.

First of all the docker builder don't run SSH. So that is not the cause of the problem and `ssh_pty` is ignored.

Speculating a bit, but I guess that `/sbin/init` takes a while to run and somewhere in there it clears `/tmp` if packer uploads the file before that it fails, if after it succeeds.

I would try to switch `/sbin/init` to `/bin/bash` and if running `init` first is important just add it to the top of your provisioning.

**Comment by edmorley** [comment]
Hi! Thank you for the reply.

> First of all the docker builder don't run SSH. So that is not the cause of the problem and ssh_pty is ignored.

Sorry yes thinking about it SSH doesn't make sense in the docker context, it will be using `docker cp` and `docker exec`  (I didn't write these configs, so not sure why `ssh_pty` is there). 

So really the OP would have been more correctly summarised as  "it looks like the `docker cp` failed and then continued onto the `docker exec` regardless". However if the theory about `/sbin/init` clearing `/tmp` is correct (it sounds very plausible), then there isn't actually anything that Packer could do differently here error message wise, after all.

Thank you for the suggestions - I'll speak to the person who wrote the configs and find out if/why `/sbin/init` is required.

**Comment by SwampDragons** [comment]
Since we never got an update on this, I'm going to assume it's been solved. If the issue here is that Packer is allowed to connect to the container before it's fully ready, then there's not much else we can do about it; these kinds of races are why we have configurable waits like pause_before.
