### ISSUE TITLE
Packer required_version support

### ISSUE THREAD

**Issue by nodesocket** [hashicorp/packer#5595]
Does Packer support the `required_version` attribute like [Terraform](https://www.terraform.io/docs/configuration/terraform.html)?

**Comment by SwampDragons** [comment]
Generally speaking, questions are best reserved for our mailing list, https://groups.google.com/forum/#!forum/packer-tool -- but given that the answer is "no," I'm going to make an edit to your question and change this to a feature request.

**Comment by tylert** [comment]
Isn't this sorta like ```min_packer_version```? (https://www.packer.io/docs/templates/index.html#min_packer_version).
