### ISSUE TITLE
Packer 1.1.2 fails to find VirtualBox Guest Additions on Windows

### ISSUE THREAD

**Issue by codekaizen** [hashicorp/packer#5600]
Running `packer build` against any template on windows fails to resolve the VirtualBox Guest Additions .iso file correctly it seems. It starts by finding the file correctly, but then fails to prepend the drive letter, forcing Windows to look in the current directory for the path. A workaround is to copy .iso file to a subdirectory of the current dir matching the path from the drive root. E.g. if the .iso file is in C:\Program Files\Oracle\VirtualBox/VBoxGuestAdditions.iso and the current dir is C:\packer; copy or link the .iso file to c:\packer\Program Files\Oracle\VirtualBox/VBoxGuestAdditions.iso

    2017/11/17 11:51:08 packer.exe: 2017/11/17 11:51:08 Found Default Guest Additions ISO: C:\Program Files\Oracle\VirtualBox/VBoxGuestAdditions.iso
    2017/11/17 11:51:08 packer.exe: 2017/11/17 11:51:08 Guest additions URL: file://C:/Program%20Files/Oracle/VirtualBox/VBoxGuestAdditions.iso
    2017/11/17 11:51:08 ui: ==> virtualbox-iso: Downloading or copying Guest additions
    2017/11/17 11:51:08 ui:     virtualbox-iso: Downloading or copying: file://C:/Program%20Files/Oracle/VirtualBox/VBoxGuestAdditions.iso
    2017/11/17 11:51:08 packer.exe: 2017/11/17 11:51:08 Acquiring lock to download: file://C:/Program%20Files/Oracle/VirtualBox/VBoxGuestAdditions.iso
    2017/11/17 11:51:08 packer.exe: 2017/11/17 11:51:08 Parsed URL: &url.URL{Scheme:"file", Opaque:"", User:(*url.Userinfo)(nil), Host:"C:", Path:"/Program Files/Oracle/VirtualBox/VBoxGuestAdditions.iso", RawPath:"", ForceQuery:false, RawQuery:"", Fragment:""}
    2017/11/17 11:51:08 packer.exe: 2017/11/17 11:51:08 [DEBUG] Using local file: /Program Files/Oracle/VirtualBox/VBoxGuestAdditions.iso
    2017/11/17 12:11:24 ui:     virtualbox-iso: Error downloading: CreateFile Program Files/Oracle/VirtualBox/VBoxGuestAdditions.iso: The system cannot find the path specified.
    2017/11/17 12:11:24 ui error: ==> virtualbox-iso: Guest additions download failed.

Log and template gist: https://gist.github.com/codekaizen/71eb4a8a92d419ec46e50f3028d0acd9

**Comment by mwhooker** [comment]
@codekaizen Thanks for the report, sorry about this. I believe this has been fixed on master. Would you care to test it? I can build you a binary if you need, just tell me the os

**Comment by codekaizen** [comment]
Sure I can test it. I'm running Win10 x64.

**Comment by mwhooker** [comment]
lol, should have guessed that from the report, thanks. Attached is packer on master
[5600.zip](https://github.com/hashicorp/packer/files/1483693/5600.zip)

**Comment by codekaizen** [comment]
Yup, the master build works ok! Thanks...

**Comment by mwhooker** [comment]
great, feel free to use that build of packer or an earlier version. If you want to wait, the next packer release will be in a few weeks

**Comment by drgeb** [comment]
I also experienced the same issue. Used the 5600.zip with the master build  and ... "Yup, the master build works GRRRrreat! Thanks"

**Comment by h-vishal** [comment]
The attached binary did not fix this issue for me, downgrading to the previous version did.

**Comment by SwampDragons** [comment]
@h-vishal will you please open a new ticket with all of the details we ask for in the issue template?  Since this solution seemed to work for some people, I think you are facing a separate, related issue.
