### ISSUE TITLE
Failed to connect to the host via ssh

### ISSUE THREAD

**Issue by lioramilbaum** [hashicorp/packer#5601]
packer version - 1.1.2
ansible version -2.4.1
Host -  ubuntu 16.04 docker container. Container hosted by OSX 10.13.1
Remote Machine - ubuntu 16.04 AWS ec2
debug log - https://gist.github.com/lioramilbaum/a31325d2fa84c0699f85038000dee0fe

When trying to build an AMI with amazon-ebs builder and Ansible provisioner:

fatal: [artifactory]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host 127.0.0.1 port 22: Connection refused\r\n", "unreachable": true}

**Comment by rickard-von-essen** [comment]
Please [gist](https://gist.github.com/) a full debug log from `PACKER_LOG=1 packer build template.json` and include your playbook(s).

**Comment by lioramilbaum** [comment]
Added

**Comment by rickard-von-essen** [comment]
The detailed log is still missing.

**Comment by lioramilbaum** [comment]
Right. Now it is.

**Comment by rickard-von-essen** [comment]
And what about `bootstrap.yml` it seems like the problem is there.

**Comment by lioramilbaum** [comment]
You are right :-) 
The following settings caused the problem:
```
ansible_user: ubuntu
ansible_port: 22
ansible_connection: ssh
```

**Comment by rickard-von-essen** [comment]
Happy to help
