### ISSUE TITLE
Confusing documentation for timeouts with hyperv-iso builder

### ISSUE THREAD

**Issue by mcandre** [hashicorp/packer#5602]
FOR BUGS:

- Packer version from `packer version`: `v1.1.3-dev`
- Host platform: Windows 10 Pro

The official documentation for the [hyperv-iso](https://www.packer.io/docs/builders/hyperv-iso.html) builder appears to contain some discrepancies.

The docs include builder JSON example snippets that configure `ssh_timeout` and `winrm_timeout`, though neither of these keys are listed among the [valid configuration keys](https://www.packer.io/docs/builders/hyperv-iso.html#optional-) for this builder.

By the way, it would be good to align key names across the different build providers. It can be surprising to have to switch the name "ssh_wait_timeout" to "ssh_timeout" when using the hyper-v builders.

**Comment by rickard-von-essen** [comment]
`ssh_timeout` and `winrm_timeout` listed on the communicator page, reference in [HyperV ISO - Configuration Reference](https://www.packer.io/docs/builders/hyperv-iso.html#configuration-reference).

Regarding `ssh_wait_timeout` i don't think there is such configuration option, anywhere?

**Comment by SwampDragons** [comment]
looks like `ssh_wait_timeout` is deprecated but there are still some instances of it hanging around in the code for backwards compatibility -- based on your experience it sounds like it's no longer backwards compatible anyway so we should probably do a code purge.
