### ISSUE TITLE
amazon: NewSession does not inherit MaxRetries and other settings

### ISSUE THREAD

**Issue by fly1028** [hashicorp/packer#5606]
https://github.com/hashicorp/packer/blob/247da61ad117a329724e180fd475d55b6d0be2d4/builder/amazon/common/step_create_tags.go#L47

Should consider changing this to the following so that the MaxRetries(=11) applies when describing AMIs.
`session, err := session.NewSession(ec2conn.Config.Copy(&awsConfig))`

This is impacting our AMI creation CI using Packer quite frequently while the default MaxRetries=3 applies.

> 12:40:28 ==> amazon-ebs: Error retrieving details for AMI (ami-fe96af9e): RequestLimitExceeded: Request limit exceeded.
12:40:28 ==> amazon-ebs: 	status code: 503, request id: 2917c8af-87c2-4e30-998f-10d10949641e
12:40:28 ==> amazon-ebs: Deregistering the AMI because cancelation or error...
12:40:28 ==> amazon-ebs: Terminating the source AWS instance...
12:40:35 ==> amazon-ebs: Cleaning up any extra volumes...
12:40:35 ==> amazon-ebs: No volumes to clean up, skipping
12:40:35 Build 'amazon-ebs' errored: Error retrieving details for AMI (ami-fe96af9e): RequestLimitExceeded: Request limit exceeded.
12:40:35 	status code: 503, request id: 2917c8af-87c2-4e30-998f-10d10949641e
12:40:35 
12:40:35 ==> Some builds didn't complete successfully and had errors:
12:40:35 --> amazon-ebs: Error retrieving details for AMI (ami-fe96af9e): RequestLimitExceeded: Request limit exceeded.
12:40:35 	status code: 503, request id: 2917c8af-87c2-4e30-998f-10d10949641e

There are a few other places with the same problem.
builder/amazon/chroot/step_instance_info.go:24
builder/amazon/common/artifact.go:76
builder/amazon/common/step_modify_ami_attributes.go:159

**Comment by rchenv** [comment]
@rickard-von-essen is there a plan to fix this bug soon? Thanks.
