### ISSUE TITLE
openstack: salt_masterless provisioner: Closed SSH session, return code: 2300218

### ISSUE THREAD

**Issue by richardfelkl** [hashicorp/packer#5607]
Hello,

I've got a problem when using salt provisioner or `salt-call` command with packer it immediately closes the packer SSH session ant the build exits with failure.

I'm using OpenStack as a builder. I have no problems with running the shell provisioners. But if I use `salt-call` command in a shell provisioner or if I use salt_masterless provisioner I'm having an issue above.

Is there any workaround or solution for this?

Packer version: 1.1.2_linux_amd64
Host Sytem: Ubuntu 16.04

Packer log:

> openstack
> 
>  output will be in this color.
> 
> ==> openstack: Discovering enabled extensions...
> ==> openstack: Pausing after run of step 'StepLoadExtensions'. Press enter to continue. ==> openstack: Loading flavor: FLAVOR
>     openstack: Verified flavor. ID: 2641f237-dd4f-4106-8c20-d336640961be
> ==> openstack: Pausing after run of step 'StepLoadFlavor'. Press enter to continue. ==> openstack: Creating temporary keypair: packer_5a116fff-699d-7bd9-7894-2f9eaf71f630 ...
> ==> openstack: Created temporary keypair: packer_5a116fff-699d-7bd9-7894-2f9eaf71f630
>     openstack: Saving key for debug purposes: os_openstack.pem
> ==> openstack: Pausing after run of step 'StepKeyPair'. Press enter to continue. ==> openstack: Launching server...
>     openstack: Server ID: 6e7e47da-931d-474f-ae24-9ad6b12f40c7
> ==> openstack: Waiting for server to become ready...
> 
> ==> openstack: Pausing after run of step 'StepRunSourceServer'. Press enter to continue. ==> openstack: Pausing after run of step 'StepGetPassword'. Press enter to continue. ==> openstack: Pausing after run of step 'StepWaitForRackConnect'. Press enter to continue. ==> openstack: Creating floating IP...
>     openstack: Pool: public
>     openstack: Created floating IP: <IP>
> ==> openstack: Associating floating IP with server...
>     openstack: IP: <IP>
>     openstack: Added floating IP <IP> to instance!
> ==> openstack: Pausing after run of step 'StepAllocateIp'. Press enter to continue. ==> openstack: Waiting for SSH to become available...
> 
> ==> openstack: Connected to SSH!
> ==> openstack: Pausing after run of step 'StepConnect'. Press enter to continue. ==> openstack: Provisioning with shell script: scripts/base.sh
>     openstack: started
> ==> openstack: Provisioning with Salt...
>     openstack: Creating remote temporary directory: /tmp/salt
>     openstack: Creating directory: /tmp/salt
>     openstack: Uploading local state tree: salt/formula
>     openstack: Creating directory: /tmp/salt/states
>     openstack: Removing directory: /srv/salt/env/prd
>     openstack: Moving /tmp/salt/states to /srv/salt/env/prd
>     openstack: Uploading local pillar roots: salt/pillar
>     openstack: Creating directory: /tmp/salt/pillar
>     openstack: Removing directory: /srv/salt/pillar
>     openstack: Moving /tmp/salt/pillar to /srv/salt/pillar
>     openstack: Running: salt-call --local  state.sls aptly --file-root=/srv/salt/env/prd --pillar-root=/srv/salt/pillar --retcode-passthrough -l info
> 
> ==> openstack: Pausing before cleanup of step 'StepConnect'. Press enter to continue. ==> openstack: Pausing before cleanup of step 'StepAllocateIp'. Press enter to continue. ==> openstack: Deleted temporary floating IP <IP>
> ==> openstack: Pausing before cleanup of step 'StepWaitForRackConnect'. Press enter to continue. ==> openstack: Pausing before cleanup of step 'StepGetPassword'. Press enter to continue. ==> openstack: Pausing before cleanup of step 'StepRunSourceServer'. Press enter to continue. ==> openstack: Terminating the source server: 6e7e47da-931d-474f-ae24-9ad6b12f40c7 ...
> 
> ==> openstack: Pausing before cleanup of step 'StepKeyPair'. Press enter to continue. ==> openstack: Deleting temporary keypair: packer_5a116fff-699d-7bd9-7894-2f9eaf71f630 ...
> ==> openstack: Pausing before cleanup of step 'StepLoadFlavor'. Press enter to continue. ==> openstack: Pausing before cleanup of step 'StepLoadExtensions'. Press enter to continue. Build 'openstack' errored: Error executing salt-call: Bad exit status: 2300218
> 

template.json:

```json 
{
  "variables": {
    "image_name": "NAME",
    "user": "root",
    "password": "PASS",
    "disk_size": "DISK_SIZE",
    "os_flavor": "FLAVOR",
    "os_source": "SOURCE_IMAGE",
    "os_availability_zone": "AVAILABILITY_ZONE",
    "os_network": "NETWORK",
    "ssh_username": "SSH_USERNAME"
  },
  "provisioners": [
    {
      "type": "shell",
      "script": "scripts/base.sh",
      "start_retry_timeout": "10s"
    },
    {
      "type": "salt-masterless",
      "local_state_tree": "salt/formula",
      "local_pillar_roots": "salt/pillar",
      "remote_state_tree": "/srv/salt/env/prd",
      "remote_pillar_roots": "/srv/salt/pillar",
      "skip_bootstrap": true,
      "custom_state": "aptly"
    }
  ],
  "builders": [
    {
      "type": "openstack",
      "image_name": "{{user `image_name`}}",
      "source_image": "{{user `os_source`}}",
      "flavor": "{{user `os_flavor`}}",
      "networks": ["{{user `os_network`}}"],
      "availability_zone": "{{user `os_availability_zone`}}",
      "use_floating_ip": true,
      "ssh_username": "{{user `ssh_username`}}"
    }
  ]
}
```

**Comment by rickard-von-essen** [comment]
Please [gist](https://gist.github.com/) a full debug log from `PACKER_LOG=1 packer build template.json`.

**Comment by richardfelkl** [comment]
Gist of full debug log from packer [https://gist.github.com/richardfelkl/82f8219e02f3220d5ceed3010ea646e4](https://gist.github.com/richardfelkl/82f8219e02f3220d5ceed3010ea646e4)

**Comment by rickard-von-essen** [comment]
Looks like your salt run disconnects/shutdown ssh.  That makes Packer loose the connection.

**Comment by richardfelkl** [comment]
> Looks like your salt run disconnects/shutdown ssh. That makes Packer loose the connection.

But when I run it manuallly without Packer SSH stays connected. And If I connect to the same VM via SSH before salt-call is ran my session also stays open but packer's is closed.

**Comment by rickard-von-essen** [comment]
Can you provide your salt config?

**Comment by richardfelkl** [comment]
> Can you provide your salt config?

Of course. [https://gist.github.com/richardfelkl/447142c965582e3fd2c421c372a50ef5](https://gist.github.com/richardfelkl/447142c965582e3fd2c421c372a50ef5)

**Comment by nywilken** [comment]
Hello folks, thanks for opening up this issue. Apologies that we've not had the chance to dive further into this issue. If you've managed to resolve your problem we encourage you to leave comment for others who may experience this issue in the future.

With that said, this is one of our community maintained plugins, which we have recently flagged as [unmaintained](https://github.com/hashicorp/packer/blob/master/README.md#unmaintained-plugins). If you are interested in contributing or taking ownership of this plugin, please reach out to us at packer@hashicorp.com.
