### ISSUE TITLE
Add ISO downloading to Null or File builders.

### ISSUE THREAD

**Issue by ladar** [hashicorp/packer#5613]
It would be nice if the File or Null builders (or even a special new builder) were available in which I could provide the iso_url, iso_checksum, and iso_checksum_type fields, whereby packer would then download the requested ISO into the packer_cache folder.

I've noticed with a handful of my distros, the ISOs download at an excruciatingly slow pace. The Debian 8 ISO in particular, takes ~1 hour over my AT&T gigabit connection (I blame AT&T for this). My current solution involves creating an empty template that I can then use to pre-download ISOs so they are available when the actual builder needs them. I cobbled together this solution using the vmare-iso builder, but it still goes through the process of creating and destroying a VM, which is unnecessary. Hence my request for a superior alternative. 

I used the vmware-iso builder because it can work without causing problems for the qemu-iso and virtualbox-iso builders, which can't be run at the same time, because of a VT-x conflict. 

My current solution looks like this, in case anybody else wants this feature:

```json
{
    "builders": [
        {
            "type": "vmware-iso",
            "name": "debian8",
            "headless": true,
            "disk_size": 1,
            "iso_url":"https://saimei.ftp.acc.umu.se/mirror/cdimage/archive/8.9.0/amd64/iso-cd/debian-8.9.0-amd64-netinst.iso",
            "iso_checksum": "fd11d34f8abf1663a33cc10a9ed998160866ef94072d442159bcfa1438be70d4",
            "iso_checksum_type": "sha256",
            "ssh_username": "root",
            "ssh_password": "vagrant",
            "ssh_port": 22,
            "ssh_wait_timeout": "10s",
            "shutdown_command": "poweroff"
        }
    ]
}
```

As mentioned above, I only get about 120 KiB/s via my AT&T gigabit link.

**Comment by SwampDragons** [comment]
Why even run a builder at all?  Why not just download the file and then provide a local filepath to the iso instead?

**Comment by ladar** [comment]
Amongst many reasons, because git doesn't play well with large binary files. I currently store the RHEL ISOs in the repo, and it isn't pretty. 

I also use multiple machines to perform the builds, and my goal is to (to the extent possible) construct my build system so such that I run ```git clone URL && cd packer && ./run.sh all``` and have everything just work. 

Even with existing build bots, I periodically run ```./run.sh cleanup``` to purge stale data, which includes the  packer_cache folder. I find myself having to update ISO URLs 1-2 times a month, and don't want the old discs cluttering up my limited SSD space. (Gentoo and Arch are updated at least once a month.)

This wasn't really an issue until I switched internet providers, and found some of my downloads crawling along whenever I kicked off a build process from home, with the Debian 8.9.0 ISO being the worst offender, FreeBSD/OpenBSD getting an honourable mention.

It occurred to me that there, currently, is no way of pulling down files via network using packer. With the exception of the downloading ISOs using a builder (or the tools ISO in the case of VirtualBox). I figured as a general purpose feature, either the Null or File builders should support this.* 

In other words, there is no good way of automating the process of pushing a file to a virtual machine using packer (and the File provisioner), that was retrieved directly by the host during the build process. Someone might want this for efficiency (so it a particular file only gets pulled once), or perhaps because the virtual machine in question can't access the URL directly. 

Adding support for downloading files off the web using the Null or File builders, as I suggested would allow someone to automate this process as well.

* Alternatively, the File provisioner could support retrieving http/https based sources... but I thought this logic might be too complicated (for human users to understand, not programmatic complexity), as the File provisioner is intended to upload files from a host to a virtual machine, not download them from the web to a host.

**Comment by SwampDragons** [comment]
I wasn't suggesting storing the binaries in the repo.  I'm suggesting that you use one of your various helper scripts to pull the iso down to some other location on your build machine and then referencing it like `"iso_url": "/path/to/my_local_file.iso",`

But if that won't work for you, am I right in thinking you're hoping for something like this? https://github.com/hashicorp/packer/issues/351

**Comment by ladar** [comment]
What's described in #351 sounds similar, in that it would support grabbing a remote file... but it appears that particular feature is focused on adding that functionality to the File provisioner (or some approximation of it). Presumably that means the go-getter would upload the retrieved file to a virtual machine. (See the asterisk above.) If the go-getter could be short circuited to grab a file, and store it in the packer_cache without any further action, then it could work. 

In contrast what I'm requesting/describing/suggesting is that the [ISOConfig](https://github.com/hashicorp/packer/blob/master/common/iso_config.go) interface be added to the Null builder. That would allow me to create a Null builder which downloads a file (presumably an ISO, but not necessarily) into the packer_cache. My go skills are paltry, but in theory, because the Null plugin is already a builder, inheriting the ISOConfig interface should be simple, and that should add what I'm describing.

It wasn't clear from the posts, but if the go-getter provisioner described in #351 also made use of the packer_cache to avoid repeatedly downloading the same file, then what I'm describing could be used to warm up the cache for builds using that provisioner as well.

As for why I don't want write a script to do it? I felt went the dummy vmware-iso config route would be easier to maintain, as changes to the way packer stores/finds cached data won't break my build process.

**Comment by SwampDragons** [comment]
Okay, I can see that.  I don't like the idea of adding this to the null builder, though.  It feels tacked-on. I'd rather have some sort of download-provisioner that specifically pulls files into the packer-cache.  I'm going to warn you though, since this does have a viable workaround (shell scripting on your own), that is unlikely to break often (I'm not even sure of the last time we changed the location of the cache) it's unlikely to be prioritized very highly.  PRs are always welcome, though.

**Comment by ladar** [comment]
>  I'm going to warn you though, since this does have a viable workaround (shell scripting on your own)...

I briefly looked into this, but couldn't guess the packer_cache naming convention. The ISO files are being saved using filenames that are clearly a SHA256 sum, in hex, but not the hex value provided in the JSON file (which would have made the most sense). 

Granted I could have looked at the code... but opted to use my dummy vmware-iso configurations strategy instead, as it means one less external dependency (bash scripts have been a problem on Windows for example), and as I mentioned, so I don't have to worry about it breaking across platforms, or releases.

>  I don't like the idea of adding this to the null builder, though. It feels tacked-on.

Null seemed to make sense... since it was a builder, it could inherit the same interfaces used by the various other existing builders... and in this case, seems to fit logically (as optional parameters of course). 

> PRs are always welcome, though.

My go skills are rudimentary, but I assumed adding such a feature would be simple enough, since all the logic already exists. The only reason I haven't tackled it myself is because I don't know what other changes, and/or updates would be needed for a PR, such updating unit tests, docs, etc. If I submitted the feature, could someone else take care of those?

**Comment by SwampDragons** [comment]
> I briefly looked into this, but couldn't guess the packer_cache naming convention
You don't need to use packer_cache if you are providing a path to a local file.  It can be stored anywhere, under any name, and packer will use the file where it lives rather than pulling it into the cache and renaming it. 

> Null seemed to make sense... since it was a builder, it could inherit the same interfaces used by the various other existing builders... and in this case, seems to fit logically (as optional parameters of course).
The purpose of the null builder is for debugging; it isn't supposed to "do" anything, as indicated by its name. I don't like violating that assumption, especially in cases like this where you could end up gobbling a lot of bandwidth for something you thought was a dry run.

**Comment by ladar** [comment]
> You don't need to use packer_cache if you are providing a path to a local file. It can be stored anywhere, under any name, and packer will use the file where it lives rather than pulling it into the cache and renaming it. 

Builds will break if the ISOs are absent, and the user doesn't know they need to run the helper script separately... 

By sticking with URLs I ensure everything just works (except for the RHEL box), and can still avoid the lag be seeding the packer_cache separately. 

> I don't like violating that assumption, especially in cases like this where you could end up gobbling a lot of bandwidth for something you thought was a dry run.

I thought one of the functions provided by the Null builder was to allow the provisioning of boxes/machines that were NOT created by packer, but still available via ssh? A kind of dummy builder. As such it seemed logical to me that a dummy builder, would support all of the typical cross builder parameters, like ISO... in which case it only pulls down the ISO if it isn't already in the packer_cache folder.

I assumed since the ssh params were optional, it could also act as a dummy for dugging other plugins, like you said. 

I could clone the Null plugin easily enough and rename it "cache" (removing the ssh params) if you thought a more specific plugin made sense. It would just mean more work adding unit tests, etc, since a new builder wouldn't already have those in place, and that happens to be the part I'm not familiar with.

**Comment by SwampDragons** [comment]
The more I think about this issue, the more I don't really think it makes sense to implement it.  It would overload the null builder. Your particular problem ("downloading takes a long time and I want to do it before my packer run") really feels like it needs to be managed outside of Packer.  The tools are there, and lots of people already do this.  

If you need a hand figuring out how to tell Packer to reference local files, please reach out to the mailing list -- like I said above, Packer won't cache those files and you don't need to worry about Packer's internal cacheing mechanism at all if you want to reference previously-downloaded files in the build, which I _think_ the documentation implies but if it isn't clear there please let me know (https://www.packer.io/docs/builders/vmware-iso.html#iso_url).

I feel like I must be missing something because we're talking past each other, but I'm fairly sure that this feature request is the correct solution to your problem.  Please reach out if you can't figure out a solution that works for you.

**Comment by SwampDragons** [comment]
I don't see why the user would need to know anything about downloads if all you want them to do is a `git clone URL && cd packer && ./run.sh all` -- if you make sure the files are downloaded in `run.sh` then the user can be as naive as anything and the build will still run.

**Comment by SwampDragons** [comment]
I actually do like the `packer cache` idea, though.  That's a much more specific and clean way of handling this case.

**Comment by ladar** [comment]
> downloading takes a long time and I want to do it before my packer run

When I build the generic boxes, there are 20 different configs, which are built sequentially. The whole process can take 12 to 18 hours. Since I can't build 2-4 at a time, they have to go single file. My goal is to speed up the process. 

What I noticed was the alpine35/alpine36/arch configs would build in during the first hour, and then I'd  reach the debian8 box which needed to pull the ISO from an archive. Depending on where I was running the build, that ISO sometimes took 1+ hour to download by itself. The idea was to cut several hours off the build by having the ISOs download separately into the packer_cache ahead of time. I figure it saves 2-4 hours off a full run... which adds up, since I'm building across 4 machines, and 4 hyper visors.

I managed mimic this behaviour by creating a "dummy" vmare-iso build configuration (I picked VMWare because unlike Vbox/QEMU it can run without any VT-x conflicts). 

The issues is that this strategy still allocates a VM, albeit for only 20 seconds, but it feels ugly. This requested started with the idea that there should be a more elegant solution. Even a flag on the vmware-iso builder that says skip creation would work (but be hard to find/use by people who don't work with that builder).

See my attached JSON for my current dummy solution to the problem...

[packer-cache.json.txt](https://github.com/hashicorp/packer/files/1511765/packer-cache.json.txt)

**Comment by ladar** [comment]
> I don't see why the user would need to know anything about downloads if all you want them to do is a git clone URL && cd packer && ./run.sh all -- if you make sure the files are downloaded in run.sh then the user can be as naive as anything and the build will still run.

I created a `./run.sh cache` target which uses the dummy JSON to seed the cache. I just didn't think run.sh should contain the URLs separately from the JSON. I already have targets `links` which verifies all JSON URLs are still valid, `sums` which downloads the ISOs and compares the hash with what's in the JSON file, and `isos` which updates the Gentoo/Arch configs with the latest URL, hash.... but all of those options still pull their data from the JSON file. Nothing critical gets handled by run.sh... it's essentially management shortcuts for automating tasks I used to do by hand. It can't be critical, because, for example on Windows, with the HyperV builds, but decided it wasn't worth the headaches, so on that platform I just run packer build generic-hyperv.json.

**Comment by SwampDragons** [comment]
I do see the value in what you're asking for, but I believe it belongs in something along the lines of a `packer cache` tool rather than shoehorning it into the null builder.  And again, while I think it's a nice idea, I know we aren't going to prioritize implementing it ourselves because this is such a specific use case and you've already got a workaround.

**Comment by SwampDragons** [comment]
it also occurs to me you may not know about this feature: https://www.packer.io/docs/builders/vmware-iso.html#iso_urls

**Comment by SwampDragons** [comment]
Also: https://github.com/hashicorp/packer/blob/master/common/step_download.go#L75-L78 is where we hash the URL to get the name of the file in the cache.  It's just a hex encoding of the URL.

**Comment by ladar** [comment]
> it also occurs to me you may not know about this feature: https://www.packer.io/docs/builders/vmware-iso.html#iso_urls

I'm aware... unfortunately the EOL'ed installer discs for distro versions like Debian 8.9.0, Ubuntu 16.10, et all, don't get replicated to mirrors, so I don't have many choices in terms of where to download them from.

As for the current distros, it wasn't clear whether packer tries to pick the fasted download location, or just tries the URLs in order. I assumed it was the latter, so I just try to pick mirrors I know tend to be fast.

> Also: https://github.com/hashicorp/packer/blob/master/common/step_download.go#L75-L78 is where we hash the URL to get the name of the file in the cache. It's just the shasum of the URL.

Much obliged. I thought it was a SHA, not a straight hex, because of the fixed output length. I'll have to take a closer look at the code when I have time. It might be worth writing a bash function to parse the JSON, and then download the ISOs that way...

**Comment by SwampDragons** [comment]
@ladar cool, glad to be of _some_ help.  I was recommending the iso_urls thing because it occurred to me that you could have the first url in the list be the local filepath, followed by a backup download url, to prevent the situation where someone runs a build without the wrapper and you haven't pre-downloaded the isos, causing the build to fail.  I've been mulling over this ticket and your setup all night wondering to myself what the "best" packer solution would be.  I think I still like the `packer cache` option the best but I know I won't get around to implementing it for some time.

**Comment by SwampDragons** [comment]
also, it is a SHA, but of the URL text not of the iso itself.

**Comment by ladar** [comment]
> I've been mulling over this ticket and your setup all night wondering to myself what the "best" packer solution would be. 

I appreciate the dialogue. I considered patching the iso functionality onto the Null builder myself, but it didn't make sense to spend the time, if the PR wasn't going to be accepted. 

As for my setup, a full build for me is up to 136 boxes. Which means if I make a change, and kickoff the process, I need to wait 12-24 hours for the results. While I'm waiting, I tend to impatiently seek out ways of speeding things up. 

While the `packer cache` option would certainly help, an alternative method of reducing my pain would be implementing #5615. If I could control how many parallel builds take place, say 2-8 boxes at a time, it wouldn't matter quite as much if one of the configurations took an hour to download its ISO. I need the control because if too many boxes are building at once, things tend to break, like a boot command misses its window, or a provisioning script timesout.

**Comment by espoelstra** [comment]
@ladar for old releases of Ubuntu are you grabbing the ISOs from http://old-releases.ubuntu.com/releases/ ? I thought there was still a bit of a CDN for that though with not as many mirrors as the current cdimage.ubuntu.com or releases.ubuntu.com servers.

I'm also curious whether Archive.org would have fast downloads for the other distros you are looking for.

I'm also curious about your use case, feel free to reach out to me via Keybase or my username at ews.me .

**Comment by ladar** [comment]
@espoelstra The slow downloads aren't limited to Ubuntu. Debian, is on the list, and another, which I can't recall. They all download slowly over my uverse gigabit connection (at the datacenter they finish in seconds, rather than hours). I've observed consistently awful performance with European sites via my home connection, sp it shouldn't come as a surprise that old-releases.ubuntu.com is physically located in the UK. If that server has other official mirrors, I can't seem to find them (only unofficial ones). 

Since I can't control the network, I was looking for other ways to speed up the process. The sensitive nature of the boot command entry process means I can only build 1 machine at a time. In a perfect world I'd be able to use the `-parallel=X` option like so, and limit builds to 2 or 4 in parallel. But with the current options, I'm limited to 1 or 24. (I looked at the code, and it didn't appear to be an easy code change.) Since they go single file, I was anxious not to have the process stall for an hour while it downloaded the ISO.

Creating a dummy vmware config seemed to work well on Linux... (I don't have VMWare loaded on the Windows/Mac build bots, because they have smallish SSDs.). I've also gotten better about limiting my intrabuild purges to the output folder, and not the entire packer_cache folder, so I don't bump up against this issue as often. 

As for old-releases.ubuntu.com ... if you know the folks in charge of that server, please tell them they have permissions set wrong for a large number of 16.10 packages. It caused apt to fail, and broke all of my 16.10 builds. I had to setup my own 16.10 mirror to workaround the issue. You might also, politely suggest they enable HTTPS...

Here is an example of a package with incorrect permissions, but there seem to be several thousand just like it:

http://old-releases.ubuntu.com/ubuntu/pool/main/v/vlan/vlan_1.9-3.2ubuntu2.16.10.2_amd64.deb
