### ISSUE TITLE
amazon: filter (STS) token from logging 

### ISSUE THREAD

**Issue by rickard-von-essen** [hashicorp/packer#5616]
We should remove `token` from logs in the same way we do with `access_key` and ` secret_key`.

**Comment by kwilczynski** [comment]
Hi @rickard-von-essen, I am going to take care about this one, since it would help me come all the work on making my organisation compliant with ISO27001, etc., thus hiding credentials is something I would welcome going forward (since we have Packer in our pipeline to kick off AMI builds, etc.).
