### ISSUE TITLE
vhd file to upload to Azure 

### ISSUE THREAD

**Issue by stevenroha** [hashicorp/packer#5617]
Suggestion to add a feature in hyper-v builder to create the Azure supportable vhd the file, so that after customization able to Upload to Azure as Unmanaged Disks. Right now we are able to get the vhdx file however converting to Azure Supportable vhd takes a long time / not possible

**Comment by adarobin** [comment]
@stevenroha I needed this functionality myself and I just submitted #6101 for it.  I'd love any feedback you could provide.
