### ISSUE TITLE
Enhancement: allow relative local file for checksums

### ISSUE THREAD

**Issue by mcandre** [hashicorp/packer#5621]
FOR FEATURES:

Some ISO's unfortunately have unstable checksums, such as those generated for macOS, where the process of building the ISO does not result in a deterministic checksum, but is instead different each time. Fortunately, packer provides a way to externalize the checksum, so that it doesn't have to be hardcoded into the packer JSON file: Rather, the checksum is pointed at via an `iso_checksum_url` file.

Unfortunately, the string value supplied to this key is not currently interpreted in a very flexible way by packer, so the absolute path to the checksum file must be used. Which stinks for packer projects that are also responsible for generating an ISO locally.

At this point, there are a few workarounds that could assist in integrating packer with these kind of wonky ISO's:

* The packer JSON file itself could be recreated each time the checksum changes, with the new checksum hardcoded, such as by using a packer.json.gotpl file that yields an ordinary packer.json file. This is difficult to do straightforwardly, as the Go templating syntax that packer uses in packer.json would conflict with the outer Go templating of a packer.json.gotpl file. Perhaps another templating engine could be used for the outer file, such as mustache, ERB, `sed -i -e "s/CHECKSUM_HERE/$CHECKSUM/ packer.json`, etc.
* The checksum file could be recreated whenever the ISO is recreated, such as by a make task. Then the checksum file is copied to a fairly machine independent absolute path such as `/tmp/checksum`. It would not do to rely on a path like `/home/Bobby/packer-templates/checksum`, as this requires that all hosts configure a user for Bobby. Rather, this should be done as a `.PHONY` task, as absolute paths are not good candidates for task names in (GNU) make. The `iso_checksum_url` would look like `"file:///tmp/checksum"`. For macOS, it is generally safe to assume that `/tmp` exists and is user-writable. However, the /tmp path is unavailable in (non-cygwin-like) Windows environments, so this method is not only a .PHONY hack, but limits packer builds to UNIX-like environments. Or worse, requires additional hacks to conditionalize the make (or whatever tool) tasks so that the URL is `file:///tmp/checksum` for UNIX-like hosts, and `file://C:\\Windows\\Temp\\checksum` for Windows hosts. Assuming C:\Windows\Temp is even user-writable, I'm not sure right now.
* The checksum file could be served over HTTP, such as Apache. Then, the `iso_checksum_url` would look like `"http://localhost:8080/checksum"`.

Neither of these workarounds is particularly easy for novices to setup, requiring additional configuration outside of packer, that depends on the particulars of the host OS. It would be much more convenient if packer simply supported interpreting relative paths in the `file://...` string for `iso_checksum_url`, or even offered an `iso_checksum_file` key for this purpose.

What do you think?

**Comment by SwampDragons** [comment]
Yeah it sounds like the solution is to fix the interpretation of the checksum filepath to allow it to be relative.

**Comment by SwampDragons** [comment]
We should be able to reuse the DownloadableURL code here https://github.com/hashicorp/packer/blob/master/common/config.go#L49. which is what we use for interpreting the iso file path.

**Comment by arizvisa** [comment]
Ftr, relative filepath for DownloadableURL is implemented by PR #2906.

**Comment by SwampDragons** [comment]
I _think_ this was solved finally in #6525

**Comment by jakebott** [comment]
Looking at the code and the latest binaries for Arch (Packer v1.3.3), this does not appear to have been fixed - the checksum does not use `DownloadableURL`.

Log output and template for replication: https://gist.github.com/jakebott/e53d07b113ec1a1d0f131cdda5d21ef7

**Comment by SwampDragons** [comment]
@jakebott looking at your logs, it doesn't appear that you even make it to the checksum. The error is 
> qemu: Error downloading: Error making HTTP GET request: 416 Requested Range Not Satisfiable

**Comment by jakebott** [comment]
@SwampDragons That version of the error is what occurs when the iso is in the cache folder - I have updated the gist with a version of the log for the case where it does not use the cache and instead downloads the iso.
If the relative path is changed to an absolute path with a `file://` URI, the config works fine - https://gist.github.com/jakebott/1336f532c38d5b9c1eaf1777448ca1b2

**Comment by azr** [comment]
This should be totally fixed by #6999 ! The go-getter allows to use a go-getter to checksum. From this pr: https://github.com/hashicorp/go-getter/pull/136
