### ISSUE TITLE
Enhancement 

### ISSUE THREAD

**Issue by Thaneesha** [hashicorp/packer#5626]
I have 100 accounts in AWS and I would like to bake an AMI and copy the AMI into all the accounts and encrypt them through the packer.

Is it possible with post-processor to run the was cli commands to encrypt the AMI's?

**Comment by FernandoMiguel** [comment]
@Thaneesha 
this should work for what you want
https://www.packer.io/docs/builders/amazon-ebs.html#ami_users
https://www.packer.io/docs/builders/amazon-ebs.html#encrypt_boot

**Comment by SwampDragons** [comment]
I'm closing this issue because it seems like Fernando has given you the information you need; if that isn't true please re-open.
