### ISSUE TITLE
Add <leftCmdOn>, <leftCmdOff> keys for macOS guests

### ISSUE THREAD

**Issue by mcandre** [hashicorp/packer#5633]
FOR FEATURES:

Packer currently does not provide a convenient way to signal to a VM that the Command key should be held down or let go. Please add `<leftCmdOn>`, `<leftCmdOff>` so that important macOS guest hotkeys can be typed into VM's.

**Comment by rickard-von-essen** [comment]
This key is called `L_GUI`/`R_GUI` in keyboard nomenclature.

**Comment by kikitux** [comment]
being worked on PR, closing this issue.
