### ISSUE TITLE
Add darwin17-64 guest os type for vmware-iso builder

### ISSUE THREAD

**Issue by mcandre** [hashicorp/packer#5637]
FOR FEATURES:

Thank you for including darwin-64, darwin10-64, darwin11-64, darwin12-64, darwin13-64, darwin14-64, darwin15-64, darwin16-64 guest os types for the VMware ISO builder. Could we please add the darwin16-64 type as well, corresponding to macOS 10.13 High Sierra?

Incidentally, should packer users specify darwinXY-64 or just darwin-64 for guest type? Does darwin-64 correspond to the latest type, or a generic darwin type, or the oldest type, or what?

**Comment by rickard-von-essen** [comment]
Packer just passes `guest_os_type` to the VMX file. So we support whatever your version of VMware does.

**Comment by kikitux** [comment]
@mcandre packer doesn't implement any of those, you can write a valid guest_os_type as rickard said.
