### ISSUE TITLE
boot_command: Offer <wait60>, <wait300>, <wait3600>, <wait n>

### ISSUE THREAD

**Issue by mcandre** [hashicorp/packer#5639]
FOR FEATURES:

Some installer commands take more than a few seconds to complete. `boot_command` does offer a convenient `<wait>`, `<wait5>`, `<wait10>` to delay further keyboard input by a few seconds, and these could in theory be duplicated to accommodate really long delays. However, 240 of these `<wait10>`'s would be required to delay 40 minutes or more, and this results in a much longer packer JSON script than necessary.

If, on the other hand, we introduced `<wait60>`, `<wait300>`, `<wait3600>`, or better yet, `<wait n>` where n is an uint32 number of seconds, then packer build scripts could express much more powerfully the delays between key presses.

**Comment by mwhooker** [comment]
you should be able to use `<waitN>` where N is a time parsable by [`time.ParseDuration`](https://golang.org/pkg/time/#ParseDuration)

if that doesn't work for you feel free to open an issue

**Comment by mcandre** [comment]
@mwhooker waitXX is great! Could this option please be offered for the VirtualBox and VMware providers as well?
