### ISSUE TITLE
SSH timeout because IP address changes

### ISSUE THREAD

**Issue by matthew-hickok** [hashicorp/packer#5642]
- Packer version: v1.1.2
- Host platform: Hyper-V on Windows Server 2016
- Guest: CoreOS

I'm getting stuck creating a Hyper-V image for CoreOS. I've get everything working on VMware Workstation, but with Hyper-V I get stuck waiting for SSH to become available. I noticed that when Packer initially creates the VM, it boots to disc, has one IP address, and then when it reboots after the install to hard disk, the IP address is different. So it makes sense that SSH times out. 

How do people typically get around this? And how does Packer normally detect the IP address of the guest?

**Comment by SwampDragons** [comment]
Have you gotten this to work before, or are you trying to figure out Packer for the first time?  Normally for "question" issues we refer people to the mailing list: https://groups.google.com/forum/#!forum/packer-tool

**Comment by matthew-hickok** [comment]
@SwampDragons I'm pretty familiar with Packer, but less familiar with the details of its implementation of the hyper-v builder. 

My builds work with CoreOS+VMware and anything+Hyper-V, but specifically Hyper-V+CoreOS seem to have an issue with IP address detection.

So I guess this is just a question, but I can't find any information on how exactly packer detects a guest's IP address on Hyper-V. It may be related to an issue with the fact that CoreOS doesn't support Hyper-V integration services, but then again I don't know if that's how Packer obtains the IP.

**Comment by rickard-von-essen** [comment]
Packer first uses [this powershell script](https://github.com/hashicorp/packer/blob/master/common/powershell/hyperv/hyperv.go#L946) find the mac of the VM, and then the following script to get the IP associated with the mac.

Check and what you get if you run those manually.

**Comment by matthew-hickok** [comment]
@rickard-von-essen 

I ran the scripts and it pretty much confirmed what I was thinking -- Packer queries the network adapter with Get-VMNetworkAdapter, which will only work if integration services are working properly on the guest. So I can get the MAC but not the IP.

So it does not return the IP address because CoreOS does not implement all of the Hyper-V Integration Services (https://github.com/coreos/bugs/issues/2161).

I was able to validate this by spinning up a Ubuntu container on my  CoreOS host, and copying the missing Hyper-V integration service binaries (primarily hv_kvp_daemon) back to the CoreOS host. After doing that, the Packer script was able to detect the IP address without issue.  

I really don't like the idea of relying on integration services for this. I made another suggestion here: https://github.com/hashicorp/packer/issues/4404

Might be a terrible idea, but it would be great to have a more stable requirement that a proper implementation of these integration services.

**Comment by mwhooker** [comment]
> It would make sense if possible for packer to re-query the network adapter for any changes and update if necessary. That, or perform the query later on in the process?

I just took a quick look and it looks like the IP is being queried as late as possible. Just before we connect it runs

`$ip = Hyper-V\Get-Vm | %{$_.NetworkAdapters} | ?{$_.MacAddress -eq $mac} | %{$_.IpAddresses[$addressIndex]}`

someone more familiar with powershell than me will have to decide if that's correct
