### ISSUE TITLE
Packer is unable to get OVF template file from local folder

### ISSUE THREAD

**Issue by avoidik** [hashicorp/packer#5643]
- Packer version from `packer version`
[version.log](https://gist.github.com/avoidik/02ff0e6b65cc6793e04c767e7f969b31#file-version-log)

- Host platform
Microsoft Windows [Version 10.0.14393]

- Debug log output from `PACKER_LOG=1 packer build template.json`.
[error.log](https://gist.github.com/avoidik/02ff0e6b65cc6793e04c767e7f969b31#file-error-log)

- The _simplest example template and scripts_ needed to reproduce the bug.
[template.json](https://gist.github.com/avoidik/02ff0e6b65cc6793e04c767e7f969b31#file-template-json)
[run.sh](https://gist.github.com/avoidik/02ff0e6b65cc6793e04c767e7f969b31#file-run-sh)
  
**Short description**

Trying to run packer build from run.sh script, passing in some calculated parameters. The problem is that packer doesn't accepts path in variable.
```
2017/11/28 13:27:02 packer.exe: 2017/11/28 13:27:02 Parsed URL: &url.URL{Scheme:"file", Opaque:"", User:(*url.Userinfo)(nil), Host:"C:", Path:"/Users/user.name/.vagrant.d/boxes/ubuntu-VAGRANTSLASH-xenial64/20171122.0.0/virtualbox/box.ovf", RawPath:"", ForceQuery:false, RawQuery:"", Fragment:""}
```
As you might see host is C: for command:
```
packer build -var box_ovf=c:\Users\user.name\.vagrant.d\boxes\ubuntu-VAGRANTSLASH-xenial64\20171122.0.0\virtualbox\box.ovf -var box_checksum=not_matter -var box_password=not_matter -var box_base_mac=not_matter template.json
```

**Comment by Occams** [comment]
Seems that 1.1.2 breaks **virtualbox-ovf** builder. Logfile is attached.
[packer.log](https://github.com/hashicorp/packer/files/1520801/packer.log)

**Comment by avoidik** [comment]
@Occams yeap, you have the same problem
```
2017/11/30 17:37:33 ui:     vbox-testbed-win10: Downloading or copying: file://E:/BuildAgent/work/6e405ed4c4e4dfbc/files/base_image/VirtualBox/agenda-base-win10.ova
2017/11/30 17:37:33 packer.exe: 2017/11/30 17:37:33 Acquiring lock to download: file://E:/BuildAgent/work/6e405ed4c4e4dfbc/files/base_image/VirtualBox/agenda-base-win10.ova
2017/11/30 17:37:33 packer.exe: 2017/11/30 17:37:33 Parsed URL: &url.URL{Scheme:"file", Opaque:"", User:(*url.Userinfo)(nil), Host:"E:", Path:"/BuildAgent/work/6e405ed4c4e4dfbc/files/base_image/VirtualBox/agenda-base-win10.ova", RawPath:"", ForceQuery:false, RawQuery:"", Fragment:""}
2017/11/30 17:37:33 packer.exe: 2017/11/30 17:37:33 [DEBUG] Using local file: /BuildAgent/work/6e405ed4c4e4dfbc/files/base_image/VirtualBox/agenda-base-win10.ova
2017/11/30 17:37:33 ui:     vbox-testbed-win10: Error downloading: CreateFile BuildAgent/work/6e405ed4c4e4dfbc/files/base_image/VirtualBox/agenda-base-win10.ova: Das System kann den angegebenen Pfad nicht finden.
```

**Comment by avoidik** [comment]
url.Parse had incorrectly parsed urls with double colons

**Comment by avoidik** [comment]
based on https://golang.org/src/net/url/url_test.go the file name should be with triple slashes after the scheme, but for some reason packer strips one slash from scheme
```
"source_path": "file:///{{ user `box_ovf` }}",
```
gives
```
2017/12/01 11:13:21 ui:     virtualbox-ovf: Downloading or copying: file://C:/Users/user.name/.vagrant.d/boxes/ubuntu-VAGRANTSLASH-xenial64/20171129.0.0/virtualbox/box.ovf
```

**Comment by avoidik** [comment]
Okay, PR proposed

**Comment by avoidik** [comment]
Issue solved
