### ISSUE TITLE
'��' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by lawrence-c** [hashicorp/packer#5651]
Packer version: 1.1.2
Host Platform: Mac OSX to Windows via [VSphere](https://github.com/jetbrains-infra/packer-builder-vsphere) provisioner

**Summary**
As a part of my provisioning, I get the IP address of the machine being provisioned via an inline `windows-shell` command. 

Very very occasionally, it fails with the error `��' is not recognized as an internal or external command`, and I'm not too sure why, and how this comes about. 

The only reason I can think of this happening is that it has something to do with the batch file it runs (`ip.cmd`). 

Re-running the packer command usually is fine to get rid of the error, but it does just keep occasionally happening.

**Relevant part of the template**
```
"provisioners": [
	{
		"type": "file",
		"source": "./ip.cmd",
		"destination": "C:/tmp/ip.cmd"
	},
	{
		"type": "windows-shell",
		"inline": [
			"echo [TEST_nodes] > C:/tmp/hosts",
			"C:/tmp/ip.cmd"
		]
	},
	{
		"type": "file",
		"direction": "download",
		"source": "C:/tmp/hosts",
		"destination": "./ansible/hosts"
	},
```

**`ip_cmd`**
```
@echo off
FOR /F "tokens=2,3" %%A IN ('ping %computername% -n 1 -4') DO IF "from"== "%%A" set "IP=%%~B"
echo %IP:~0,-1% >> C:/tmp/hosts
```

**Debug Log**
```
==> vsphere: Cloning VM...
==> vsphere: Power on VM...
==> vsphere: Waiting for IP...
==> vsphere: IP address: [redacted]
==> vsphere: Waiting for WinRM to become available...
==> vsphere: Connected to WinRM!
==> vsphere: Uploading ./packer/ip.cmd => C:/tmp/ip.cmd
==> vsphere: Provisioning with windows-shell...
==> vsphere: Provisioning with shell script: /var/folders/c7/8kvczj9j6m5db7jfh2cfmzsh0000gn/T/packer-windows-shell-provisioner113959255
    vsphere:
    vsphere: C:\Users\username>echo [TEST_nodes]  1>C:/tmp/hosts
    vsphere: '��' is not recognized as an internal or external command,
    vsphere:
    vsphere: operable program or batch file.
    vsphere: C:\Users\username>C:/tmp/ip.cmd
    vsphere:
    vsphere: C:\Users\username>��
==> vsphere: Power off VM...
==> vsphere: Destroying VM...
```

**Comment by spuder** [comment]
This has to do with the encoding that a file was saved as (UTF-8 vs UTF 16 and Big endian vs Little endian). 

Easy way to reproduce this is to open a powershell window and type this command

```
echo "" > foo.txt
```

If you open foo.txt with a text editor like atom, you will find hidden characters. 

![screenshot 2017-12-06 12 21 47](https://user-images.githubusercontent.com/242382/33680817-0c3eff3a-da80-11e7-8ac4-1b2fa66e1910.png)


Go through all your scripts and make sure no hidden characters are present.

**Comment by SurferL** [comment]
@spuder Thanks for looking into this! 

I've had a look at the `ip.cmd` file, however don't see any hidden characters?

![screen shot 2017-12-07 at 09 31 07](https://user-images.githubusercontent.com/10439579/33708091-65d87308-db31-11e7-9b55-346ce837b263.png)

What I find weird is that it only happens very very occasionally...

**Comment by SwampDragons** [comment]
I wonder if there needs to be some escaping of whatever's added to the IP variable.

**Comment by brianlund** [comment]
@lawrence-c did you find a resolution to this? I'm also seeing it occasionally. The same cmd file will fail maybe 10% of the time with no change in between.

**Comment by spuder** [comment]
@brianlund what version are you running? We pinned to an older version of packer and the problem went away (1.3.x if I recall correctly)

**Comment by brianlund** [comment]
@spuder 
This is with 1.4.3 using the hashicorp/packer docker image. I'll try a 1.3.x version and see if that helps. Thanks.
