### ISSUE TITLE
Degraded Ansible provisioner performance with latest AWS Windows Server 2016 AMIs

### ISSUE THREAD

**Issue by SNikalaichyk** [hashicorp/packer#5652]
Packer 1.1.2
Builder: amazon-ebs
Provisioner: ansible (Ansible 2.4.1)
Communicator: WinRM

**SUMMARY**

In our environment we rely on Packer in combination with its Ansible provisioner to build Windows Server 2016 AMIs in AWS.

After October's AWS Windows base AMI release (2017.10.13), we noticed significant performance degradation of Ansible provisioner ([AWS Windows AMI Version History](http://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/windows-ami-version-history.html#amis-2017)).

For example, a playbook that previously took 20-25 minutes to complete, now requires about 80 minutes.
It only happens when running it via Packer's Ansible provisioner, i.e., Ansible itself is not affected.

After hours of troubleshooting, it appears to be that this abnormal behavior was first introduced with the [KB4038801](https://support.microsoft.com/en-us/help/4038801) Cumulative Update. Unfortunately you cannot just skip/uninstall this update with the new Windows Monthly Rollup patching strategy.

Amazon base AMIs not affected - September and older:
```
Name    : Windows_Server-2016-English-Full-Base-2017.09.13
ImageId : ami-5648ad2c
Region  : us-east-1
```
Amazon base AMIs affected - October and newer:
```
Name    : Windows_Server-2016-English-Full-Base-2017.10.13
ImageId : ami-e3bb7399
Region  : us-east-1

Name    : Windows_Server-2016-English-Full-Base-2017.11.18
ImageId : ami-c70586bd
Region  : us-east-1

Name    : Windows_Server-2016-English-Full-Base-2017.11.19
ImageId : ami-ca75f7b0
Region  : us-east-1
```

**Comment by SwampDragons** [comment]
Thanks for reporting this!  Can you please provide: 
- Host platform
- Debug log output from `PACKER_LOG=1 packer build template.json` in a gist
- The _simplest example template and scripts_ needed to reproduce the bug, also in a gist.

**Comment by SwampDragons** [comment]
these may not be realated, but another recent issue was based on an AMI patch too: https://github.com/hashicorp/packer/issues/5614

**Comment by SNikalaichyk** [comment]
Well, this is really weird, but I since last Friday we can no longer reproduce this issue. It looks like Packer is not to blame.

**Comment by SwampDragons** [comment]
My favorite kind of Packer bug!  Let us know if you end up reproducing or finding another issue :) .
