### ISSUE TITLE
unknown configuration key: "build_resource_group_name

### ISSUE THREAD

**Issue by shahbhavya85** [hashicorp/packer#5653]
packer version: 1.1.2 
builder: azure-arm

Trying to use build reource group in azure and running into this error.

Template validation failed. Errors are shown below.

Errors validating build 'azure-arm'. 1 error(s) occurred:

* unknown configuration key: "build_resource_group_name"

Any idea why it is happening?

**Comment by boumenot** [comment]
The feature that uses build_resource_group_name is targeted for 1.2.0 (last I checked), and is not available in 1.1.2.

**Comment by shahbhavya85** [comment]
Thanks! Do we have any targeted date for 1.2.0 release?

**Comment by mwhooker** [comment]
@shahbhavya85 nothing firmer than "soon". sorry! we try to release every 3 weeks or so, but we've been out on holiday last week so things are a bit behind

**Comment by shahbhavya85** [comment]
No problem! Really appreciate and excited to have this feature to be released soon.
