### ISSUE TITLE
Using build_resource_group_name in Azure doesn't cleanup keyvault

### ISSUE THREAD

**Issue by jamielennox** [hashicorp/packer#5654]
So I'm testing out the unreleased "build_resource_group_name" from #5045 and #5548 and on cleanup I'm left with the keyvault object hanging around. 

Looking through the code is a fairly obvious problem we deploy 2 templates, the keyvault and the vm resources, but we only save 1 ArmDeploymentName in the statebag that gets cleaned up at the end. The other is basically dropped. 

There's a few ways we could handle this, I was hoping we could save an array of created deployments in the statebag but it doesn't look like it's really designed this way. 

I'll try and play with this a bit, but if you don't see a PR assume i'm happy for someone else to pick it up.

**Comment by mwhooker** [comment]
cc @ArjenSchwarz

**Comment by jamielennox** [comment]
Note, only affects building windows images on azure. Linux images don't involve a keyvault.

**Comment by boumenot** [comment]
Apologies that this escaped us, but thank you for taking the time to test out unreleased code.

Let me see what I can do to fix this.  It should be easy enough to detect it is Windows, and then cleanup the KeyVault in addition to everything else that was deployed.

**Comment by jamielennox** [comment]
Another issue, which i can assign a new bug for if you like but is related to this work. 

If you use an existing resource group then you shouldn't provide "location" as a config option, it should be determined by the location of the resource group.

**Comment by ArjenSchwarz** [comment]
@boumenot if you're looking at this already I'll let you lead, but I'll have a look at it as well. As you say, it should be possible to check for this extra template and do similar cleanup work.

@jamielennox let me say a thank you as well for reporting this.

**Comment by dhermans** [comment]
hi - can we get a test build (linux x64) of this feature? We can test quite quickly

**Comment by boumenot** [comment]
I [uploaded builds to my OneDrive](https://1drv.ms/f/s!AmGtc0f52KBYgcpny1TFN9Pf-UzW9A) from the tip of master for darwin, linux, and windows.  Give it a spin, and lets us know how it works.

**Comment by dhermans** [comment]
hi - i see this issue is closed - just wanted to report that we tested this new option successfully..

packer deployed into our existing RG and created an Image

this is a good feature - it means you don't have to give people delete resource group rights ( which has all sorts of implications )

**Comment by jamielennox** [comment]
That was a much more involved patch than I expected, nicely done. 

Tested and can confirm it removes the keyvault. 

Thanks

**Comment by boumenot** [comment]
*fist bump*

Thanks again for posting the issue, and letting us know about.
