### ISSUE TITLE
'build_resource_group_name' should be mutually exclusive with 'location' in Azure

### ISSUE THREAD

**Issue by jamielennox** [hashicorp/packer#5655]
In master when using an existing resource group with 'build_resource_group_name' you shouldn't have to specify a 'location'. Location is used to tell Azure where to build the resource group.

If you get this value wrong (as i just did) then it can't find the image to capture it even though we only just finished building it. 

You could make it optional or validate its correctness, but personally i'd make the options mutually exclusive and you just shouldn't present location with build_resource_group_name.

**Comment by boumenot** [comment]
Agreed.

**Comment by jamielennox** [comment]
Ah - didn't see the self-assign. Hope this saves you some time rather than redoing something you were working on.

**Comment by boumenot** [comment]
I had not started yet.  It was mostly a signal to myself that I accepted the work, and would be doing it imminently.
