### ISSUE TITLE
Packer build command deletes existing resource group when provided through "temp_resource_group_name"

### ISSUE THREAD

**Issue by shriganeshs** [hashicorp/packer#5658]
Packer version: 1.1.1
builder: azure-arm

As my Service Principal credentials does not have permissions to create a temporary resource group in Azure, I created a new resource group manually and provided a `temp_resource_group_name` in Packer config file. But after successfully building the image, Packer deleted this manually created temp resource group.
I think the behavior should be as follows
1) If Packer creates a new temp resource group, it can delete it
2) If an existing resource group is provided as a temp resource group in Packer config file, then Packer should not cleanup the existing resource group, instead only cleanup the temp resources created inside this existing resource group.
  
This may be related to https://github.com/hashicorp/packer/issues/5045, but by default Packer should delete only the temp resources Packer created.

**Comment by boumenot** [comment]
This is being addressed in Packer 1.2.0.
