### ISSUE TITLE
Win10 Fall Creators Update automatically enables Hyper-V checkpoints

### ISSUE THREAD

**Issue by pvandervelde** [hashicorp/packer#5663]
The fall creators update added some changes to [Hyper-V](https://blogs.technet.microsoft.com/virtualization/2017/11/13/whats-new-in-hyper-v-for-windows-10-fall-creators-update/), one of them being that checkpoints are automatically enabled. 

The problem comes when Packer exports the image. The checkpoints are not exported along with the image and then loading the image is only possible manually because Hyper-V tries to import the checkpoints (which aren't there).

At a minimum, the Hyper-V driver should delete the checkpoints before exporting but more likely the hyper-v driver should disable checkpoints when creating the VM because a Packer generated VM shouldn't need checkpoints.

**Comment by mwhooker** [comment]
hmm, there was already some work done to this effect in #5374 and #5517

Can you confirm that the version of packer you tested with contains those merges? (should be in 1.1.2).

cc @PatrickLang

**Comment by pvandervelde** [comment]
Aaaah I could have been using an old version. I shall update to the latest version and re-check

**Comment by pvandervelde** [comment]
Will have to try with 1.1.3 when it comes out because of #5622 / #5620

**Comment by cryps1s** [comment]
I can confirm this is still an issue with 1.1.3 and using generation 2 VMs. I've not tested with generation 1, but will give that a shot.

**Comment by PatrickLang** [comment]
@cryps1s can you give a link to the JSON you're building? Will give 1.1.3 a try

**Comment by cryps1s** [comment]
Hey @PatrickLang,

Thanks for looking in to this. I forgot to mention that the packer build is occurring on 1709. I'm re-running my build right now to validate this is still an issue.  

The very condensed version of my JSON file can be found here: https://gist.github.com/cryps1s/49c2cd3dc37fb8b27c1712d7bffa437f

**Comment by PatrickLang** [comment]
I tested on Windows 10 version 1709, OS build 16299.125

Both the Ubuntu sample I listed above, and my latest running Windows Server Insider as a gen2 VM work.

https://github.com/PatrickLang/packer-windows/blob/hyperv-insider-gen2/windows_server_insider.json

**Comment by PatrickLang** [comment]
pinging @cryps1s - is this working for you? We should close this issue if its working

**Comment by pvandervelde** [comment]
I tested it a while back and I couldn't get Packer to work because of #5700 / #5713 so I haven't been able to test the current issue completely. I'm waiting for 1.1.4 to retest (assuming that will fix the two issues mentioned above)

**Comment by MrLunar** [comment]
I believe this is still an issue. Just attempted a Gen1 build but the output has the "Missing Checkpoint" compatibility error, making subsequent builds/imports impossible.

Packer: 1.2.1
Winows: Windows 10 1709 (16299.248)

**Comment by stewartadam** [comment]
I'm seeing this on Packer 1.2.5 with Win 10 1803. Testing now with 1.3.0 (will edit inline when build finishes).

**Comment by pvandervelde** [comment]
Tested this with 1.3.4 and it works now so I think this issue can be closed.
