### ISSUE TITLE
shared_credentials_file for amazon-ebs

### ISSUE THREAD

**Issue by nodesocket** [hashicorp/packer#5668]
I've read through the docs and don't see a way to specific a `shared_credentials_file` like Terraform when building `amazon-ebs` images. Is this possible? I'd prefer this method instead of hard coding the AWS credentials in the Packer file, or using system level AWS credentials.

**Comment by mwhooker** [comment]
You can use a shared credentials file as described in https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/configuring-sdk.html#specifying-profiles

Is that what you're talking about?

You can set the profile with either `AWS_PROFILE=...` or by setting the profile in the packer config

**Comment by nodesocket** [comment]
Is `profile` in the Packer config a path to the `shared_credentials_file`? I.E. I'd like to create the profile file in my Packer root directory and just `.gitignore` it.

**Comment by mwhooker** [comment]
No, it's different. you can get more details here https://www.packer.io/docs/builders/amazon.html#specifying-amazon-credentials
and here https://www.packer.io/docs/builders/amazon-ebs.html#profile

We don't currently plan to support other ways of specifying credentials, but in the future may adopt terraform's mechanisms

**Comment by nodesocket** [comment]
@mwhooker thanks, that what I was looking for. Bummer, that Terraform `shared_credentials_file` is not supported.

**Comment by nodesocket** [comment]
@mwhooker seeing the following error:

```
amazon-ebs output will be in this color.

1 error(s) occurred:

* Could not find AWS region, make sure it's set.
```

Specifying the profile as `"profile": "myproject-dev",` and in `.aws/config` I have:

```
[myproject-dev]
region = us-west-2
aws_access_key_id = XXXXXXXXXXXXXXXXXXXXX
aws_secret_access_key = YYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
```

**Comment by mwhooker** [comment]
iiinteresting, will check that out and reopen if I can reproduce. thanks!

**Comment by mwhooker** [comment]
will track in #5669
