### ISSUE TITLE
Post-processor failed: unexpected EOF

### ISSUE THREAD

**Issue by jamiesonbc** [hashicorp/packer#5670]
I know this is an old version of packer, but I need to kick out some templates before upgrading.  Can you provide me the reason for this EOF.   I have attached my script, json and log in the following gist

https://gist.github.com/jamiesonbc/d55530eef88d7ba53abd9eabe2e1255e

**Comment by mwhooker** [comment]
I'm afraid your error is 

`2017/12/05 17:31:51 packer-post-processor-vsphere: fatal error: runtime: out of memory`

I believe that's referring to your host machine (that is, it's the go runtime throwing that error). Is there a larger machine you can run the build on? This happened during the ovftool run where it uploads to vsphere. It's not inconceivable that ovftool first copies the disk into memory. You could also try updating ovftool, but no guarantees.

Sorry I can't help more. best of luck
