### ISSUE TITLE
vmware-iso hardcoded for SCSI, no option for IDE, SATA

### ISSUE THREAD

**Issue by mcandre** [hashicorp/packer#5671]
FOR BUGS:

https://github.com/hashicorp/packer/issues/1242 was mistakenly closed, as the vmware-vmx builder supports a manual workaround for lack of IDE/SATA support. But in fact, the vmware-iso continues to lack IDE and SATA support.

Please expose simple SATA and IDE configuration options for the ISO and virtual disk, as other builders like virtualbox-iso do.

**Comment by arizvisa** [comment]
This is a dupe of #2968.

**Comment by kikitux** [comment]
probably will be fixed by https://github.com/hashicorp/packer/pull/2968
