### ISSUE TITLE
go get fails with unrecognized import path "context" 

### ISSUE THREAD

**Issue by graudeejs** [hashicorp/packer#5674]
```sh
$ go get github.com/hashicorp/packer
package context: unrecognized import path "context" (import path does not begin with hostname)
```

System: Linux Mint 18.2
Go: 1.6.3

**Comment by rickard-von-essen** [comment]
You need go 1.7

**Comment by SwampDragons** [comment]
for more context (pun not intended) see the 1.7 release notes about the context package: https://golang.org/doc/go1.7

**Comment by yassermog** [comment]
export GOROOT=/usr/local/go
export GOPATH=$HOME/go
export PATH=$PATH:$GOROOT/bin

**Comment by MeiChen26** [comment]
go version may be too old for you , try:

$ sudo add-apt-repository ppa:gophers/archive
$ sudo apt-get update
$ sudo apt-get install golang-1.10-go

or
# This will give you the latest version of go
$ sudo snap install --classic go

**Comment by shikhir-daffodil** [comment]
Please give any proper solution for that..!!!!!
