### ISSUE TITLE
Allow non 0 exit codes

### ISSUE THREAD

**Issue by spuder** [hashicorp/packer#5677]
Windows has many exit codes that represent success. For example exit code `3010` on windows is a success when a package installs but  requires a reboot. 

Is there a way to allow non 0 exit codes? If not, it would be nice to define acceptable exit codes in packer. 

Here is a packer build step that fails with code `3010`
```json
    {
      "type": "powershell",
      "inline": ["choco install dotnet4.7 --verbose -y"]
    }
```

Packer could allow an `exit_codes` definition like this: 

```json
    {
      "type": "powershell",
      "inline": ["choco install dotnet4.7 --verbose -y"],
       "exit_codes": [0,3010]
    }
```

```
    vmware-iso: Installing dotnet4.7...
    vmware-iso: dotnet4.7 has been installed.
    vmware-iso: A restart may be required to finalize Microsoft .NET Framework 4.7 installation.
    vmware-iso:  The install of dotnet4.7 was successful.
    vmware-iso:   Software installed as 'exe', install location is likely default.
    vmware-iso:
    vmware-iso: Chocolatey installed 5/5 packages.
    vmware-iso:  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
    vmware-iso:
    vmware-iso: Installed:
    vmware-iso:  - kb2919355 v1.0.20160915
    vmware-iso:  - dotnet4.7 v4.7.2053.0
    vmware-iso:  - kb4019990 v1.0.0
    vmware-iso:  - kb2919442 v1.0.20160915
    vmware-iso:  - chocolatey-windowsupdate.extension v1.0.2
    vmware-iso:
    vmware-iso: Packages requiring reboot:
    vmware-iso:  - dotnet4.7 (exit code 3010)
    vmware-iso:
    vmware-iso: The recent package changes indicate a reboot is necessary.
    vmware-iso:  Please reboot at your earliest convenience.
    vmware-iso:
    vmware-iso: Did you know the proceeds of Pro (and some proceeds from other
    vmware-iso:  licensed editions) go into bettering the community infrastructure?
    vmware-iso:  Your support ensures an active community, keeps Chocolatey tip top,
    vmware-iso:  plus it nets you some awesome features!
    vmware-iso:  https://chocolatey.org/compare
==> vmware-iso: Stopping virtual machine...
==> vmware-iso: Deleting output directory...
Build 'vmware-iso' errored: Script exited with non-zero exit status: 3010. Allowed exit codes are: [0]
```

A similar request was made here, but the issue is closed https://github.com/hashicorp/packer/issues/4957

**Comment by SwampDragons** [comment]
We already have this feature, and it works exactly as you request: https://www.packer.io/docs/provisioners/powershell.html#valid_exit_codes

example usage `"valid_exit_codes": [0, 3010]`

**Comment by spuder** [comment]
Thanks. I swear I searched that page, but didn't find it. Sorry for the noise.

**Comment by SwampDragons** [comment]
No worries!  Everyone has those days.

**Comment by testworksau** [comment]
I am curious as to why this was only added to powershell provisioner, and not - for example - to the windows_shell provisioner?

**Comment by Atalanta** [comment]
It would be useful to extend this functionality to the `shell` provisioner too.  I'm running InSpec in a provisioner, to ensure that an image isn't built if not compliant against my standards.  Any skipped tests will (by design) return a `101` exit code.  At the moment I have to wrap `inspec` and trap `101` and return `0`.

**Comment by gugahoi** [comment]
Puppet provisioner would also be nice. Some puppet agents with versions far back in v3.x when run with `--detailed-exit-codes` will exit with a status 2 on success with changes.

**Comment by christianclarke** [comment]
@Atalanta 
> It would be useful to extend this functionality to the `shell` provisioner too. I'm running InSpec in a provisioner, to ensure that an image isn't built if not compliant against my standards. Any skipped tests will (by design) return a `101` exit code. At the moment I have to wrap `inspec` and trap `101` and return `0`.

Can I ask how you were able wrap the innovation of Inspec within the Provisioner inorder to swallow the error code you needed to suppress?  I have the exact same requirement, but I want to run some Inspec tests and regardless of Inspec Pass/Fail/Skip - I don't want Inspec to fail the Packer run.

I can suppress the error code outside of Packer simply by using `|| :` at the end of the `inspec exec`.  This unfortunately works from within inside a Packer Inspec provisioner.
