### ISSUE TITLE
recognize super key for Linux guests, virtualbox builders

### ISSUE THREAD

**Issue by mcandre** [hashicorp/packer#5682]
Similar to https://github.com/hashicorp/packer/pull/5681 , I wish packer would recognize the Super/Windows key when building VirtualBox VM's.

I think the Left Super scancode is 133, and Right Super scancode is 134, based on [StackExchange](https://unix.stackexchange.com/q/297728/32972). The [Arch wiki](https://wiki.archlinux.org/index.php/extra_keyboard_keys) also details how to verify scancode tables with `xev`, from a working X11 environment.

As the Super scancode is not listed among the [Linux keyboard scancodes](http://www.win.tue.nl/~aeb/linux/kbd/scancodes-1.html) documentation referenced by the VirtualBox builder source code, I can't guarantee that this scancode would also work for the Super AKA Windows key for Windows guests. Worth experimenting to find out.

I would bet, however, that these scancodes probably do NOT match for macOS guests, as macOS uses a completely different scancode table than Linux/PC/IBM scancodes. https://github.com/hashicorp/packer/issues/5635 addresses that. In any case, it would be fantastic if packer could finally submit the all important Super key for VirtualBox builds, even if only for Linux and/or Windows guests!

**Comment by kikitux** [comment]
PR welcome

**Comment by mwhooker** [comment]
closing assuming this was fixed in #6067
