### ISSUE TITLE
Error installing 

### ISSUE THREAD

**Issue by RameshMuthuraj** [hashicorp/packer#5683]
Getting error while install packer on amazon linux 

/usr/share/cracklib/pw_dict.pwd: Permission denied
/usr/share/cracklib/pw_dict: Permission denied

I ve downloaded the binary from 
https://releases.hashicorp.com/packer/0.8.6/packer_0.8.6_linux_amd64.zip

extract this to some folder 

then copy the packer file to /usr/local/bin

What am I missed? please help me

**Comment by rickard-von-essen** [comment]
This https://www.packer.io/intro/getting-started/install.html#troubleshooting
