### ISSUE TITLE
Shift+Tab not working as expected for mac guests

### ISSUE THREAD

**Issue by mcandre** [hashicorp/packer#5685]
The `<tab>` and `<leftCtrlOn>`/`<leftCtrlOff>` keys are working really well for mac guests (VMware builder). I'm not sure why, but for some reason the `<leftShiftOn>`/`<leftShiftOff>` modifier is not able to navigate backwards in GUI's with the `<tab>` key. I am able to Shift+Tab manually in mac guests by manually pressing Shift and Tab simultaneously, so something's off about how this signal is being passed to the guest by packer.

- Packer version from `packer version`: `v1.1.2-dev`
- Host platform: macOS 10.13 High Sierra
- Guest platform: macOS 10.13 High Sierra

With Apple hardware, ISO's can be generated with [macos-isos](https://github.com/mcandre/macos-isos) scripts. A work in progress packer JSON configuration is available in the "macos" branch of my [packer-templates](https://github.com/mcandre/packer-templates/blob/macos/macos/macos.json) repository.

As a workaround, I am using multiple, unmodified `<tab>`s in my `boot_command` to wrap around to the desired GUI element, rather than a single `<leftShiftOn><tab><leftShiftOff>`.

**Comment by SwampDragons** [comment]
What builder are you using?

**Comment by mcandre** [comment]
vmware-iso.

**Comment by kikitux** [comment]
perhaps can be implemented similar to this?

https://github.com/hashicorp/packer/pull/3767/files

**Comment by SwampDragons** [comment]
Since this issue was opened, Packer totally revamped how boot commands are sent and standardized them. Is this still an issue?

**Comment by SwampDragons** [comment]
Closing since we never heard back.
