### ISSUE TITLE
Enhancement: Ability to continue long boot_command's from snapshots

### ISSUE THREAD

**Issue by mcandre** [hashicorp/packer#5688]
Some VM's take a very long time to build, multiple hours. Testing tweaks to `boot_command` for such long builds is frustrating, because the developer won't know whether the tweak is successful or not until the entire build replays.

For Docker, builds have the benefit of separating the steps into distinct `RUN` commands, and Docker caches and replays from the last good `RUN`, so the development cycle of a Docker image is much faster. Once the whole image builds, the developer can cleanup multiple `RUN` commands into a single `RUN` for a correct, efficient build script.

Could packer get something like this, by leveraging the hypervisor's ability to record and replay snapshots? For example, packer could search for `<checkpoint>` markers along the `boot_command` when a build is about to be executed. The build could skip to the last reached `<checkpoint>`, load the snapshot, and continue executing keys from `boot_command` to save development time. Whenever a new `<checkpoint>` step is reached, packer records a snapshot. When a developer is happy with the whole build, then he can delete the `<checkpoint>` markers to cleanup, and optionally run `packer build` one more time to check his or her work.

Notes:

* Not sure which hypervisors support checkpoints, though at least VMware does. Other hypervisors could treat `<checkpoint>` as a NOP.
* One thing that would probably have to change in order to support this snapshot integration is that `packer build` would have to become better at reusing artifacts. It would do no good to record snapshots, if the next `packer build` execution discards the previous build's artifacts.

**Comment by rickard-von-essen** [comment]
IMHO this would be terrible complex to implement.

I think the real solution to your problem (super long build times) is to break it up in steps and ensure that only the first build which builds from ISO uses `boot_command`. This build should be fairly static, seldom rebuilt. From that base image you can build more specialised builds that only uses provisioners to manipulate the instance. Scripts can be much more resilient of errors and do things like retries or wait for certain conditions before continuing.

**Comment by mwhooker** [comment]
Thanks for the cool idea! However, I don't think this is something we will pursue. Packer isn't the best tool for going deep on niche problems -- we like to be generally applicable to the majority of users. We're very much breadth over depth. Consequently, this usually means that Packer doesn't have room to solve more specific problems like this one. 

I think the root problem, which is that getting the config correct while developing the packer script is difficult, is legitimate, but I think we need to attack that problem from a different angle.
