### ISSUE TITLE
Option to scale wait times

### ISSUE THREAD

**Issue by mcandre** [hashicorp/packer#5689]
`<wait>` steps in `boot_command`s are currently expressed relatively to host clock time, which is normally fine. However, guest VM’s actually execute the steps at very different speeds, depending on how much of each virtual resource is available (CPU, RAM, HDD, etc.). So a packer script must be rewritten to change its lengths when resources are reduced, replacing `<wait>` with `<wait5>`, for example. This is okay for very fixed VM configurations on fixed host environments, but a user attempting to pack VM’s with slightly different guest resource settings, or even from different host machines, is going to have a bad time. In the best case, the user observes a lot of wasted waiting as the VM quickly processes build steps. In the worst case, the steps are submitted at the wrong time, sending keystrokes too early / too late for the guest processes to priperly handle them. The user mus then tweak every wait step to match his particular setup.

One enhancement that would help `boot_command`s to be more flexible for changing virtual hardware is to offer a wait mechanism relative to a guest clock scaling factor. We could call this configuration key `sleep-scale`, perhaps, and it would exist alongside other keys like `iso_url`. Sleep scale would take the form of a floating point, default 1.0, that multiplies each `<sleep n>` step to form an effective delay between steps. This way, the whole `boot_command` becomes highly responsive and reusable for many different hardware configurations. Let’s not forget that the host hardware is significant as well—VM’s running on leaner hosts will process steps more slowly. The packer command line utility could even override the sleep scaling factor with a command line flag or per-user configuration file, so that the packer JSON doesn’t have to change one bit to scale to different host environment speeds!

If that all makes sense, I think `<wait>`, `<wait5>`, and `<wait10>` could each be deprecated one day, to encourage more expressive packer build scripts. Just a thought.

**Comment by mwhooker** [comment]
Thanks for the ideas! I think this is something that would be better done by preprocessing your json template. You may also use ```<wait{{user `wait_time`}}>``` where `wait_time` is a user variable that you can control per run.

In all honesty, this is probably something which we will never implement, so I'm going to close it now rather than let it linger.
