### ISSUE TITLE
Azure-ARM: Multiple builds in one resource group

### ISSUE THREAD

**Issue by DCT-daltonmiller** [hashicorp/packer#5690]
Now that we have `build_resource_group_name` in azure-arm it would be great to have multiple builds running in the same resource group. For security reasons, we have the Packer resource group created manually along with a VNet and NSG, which works fine with only one build in the resource group.

When trying multiple builds right now Packer will try deleting the resources in the resource group which fails since some are in use, particularly `packerNic`. Maybe the name of the NIC could be randomized similar to the VM and key vault names?

**Comment by boumenot** [comment]
This is a duplicate of #5659.
