### ISSUE TITLE
Looking for a simple packer plugin example

### ISSUE THREAD

**Issue by jamesla** [hashicorp/packer#5693]
I've read through the docs and searched the documentation and I'm looking for a bit more information on how to write a packer plugin. 

I was hoping to use the example in the example folder of this repo (plugin/example) but there's a comment saying that packer doesn't use that method anymore.

Could somebody point me in the direction of a simple example packer plugin using the new method?

**Comment by SwampDragons** [comment]
Look at command/plugin.go to see how the core plugins are loaded now, but the format below was used for packer <= 0.8.6 and is forward-compatible.

**Comment by jamesla** [comment]
thanks @SwampDragons
