### ISSUE TITLE
Breaking change in 1.1.3

### ISSUE THREAD

**Issue by envatopoho** [hashicorp/packer#5694]
[This commit](https://github.com/hashicorp/packer/commit/a90c45d9bb3f2abd56ea77c8a456df19baaa60a7#diff-76f53be4e00c8508514464a9b9235c4e) which made it into the `1.1.3` release introduces a dependency in AWS for the `ec2:DescribeInstanceStatus` permission on the role that is building AMI's.

This broke our pipelines which were previously working on `1.1.2`.  (We used the docker `light` image, which wasn't pinned so it automatically put us on the latest release).

Anyway, the new permission it should probably be documented at https://www.packer.io/docs/builders/amazon.html#using-an-iam-task-or-instance-role

**Comment by rickard-von-essen** [comment]
Thanks for bringing this to our attention.

**Comment by mwhooker** [comment]
Sorry about that, and thanks for the report! Definitely did not mean to break this in a patch release. 

We've generally not done an excellent job of catching changes to the aws permissions we need. I'm going to investigate writing an acceptance test for these which will notify me of any permissions changes in the future.

In the meantime I'll update the docs

**Comment by mwhooker** [comment]
fixed in 03594bc07

**Comment by envatopoho** [comment]
No worries @mwhooker!

**Comment by JasonScottSF** [comment]
Does it depend on the specific permission being there?  
I'm trying it with this as my IAM policy and it's not working.
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "*",
      "Resource": "*"
    }
  ]
}
