### ISSUE TITLE
arbitrary waitXX doesn't work

### ISSUE THREAD

**Issue by davebiffuk** [hashicorp/packer#5701]
https://www.packer.io/docs/builders/qemu.html#lt-waitxx-gt- says that arbitrary wait times can be caused by using e.g. `<wait10m>`

However that's not working for me, when using `<wait2m>` I see Packer causing the literal keypresses <, w, a, i, t, 2, m, >.

I'm working around this by using many repeats of  `<wait10>`.

- Packer version from `packer version`

1.1.3

- Host platform

Ubuntu Xenial (16.04) 64-bit with all updates

- Debug log output from `PACKER_LOG=1 packer build template.json`

See gist: https://gist.github.com/davebiffuk/6cdcdb775f92a5f016689e109ff2d8f1

- Simple example template to reproduce the bug

See gist: https://gist.github.com/davebiffuk/e851453621d97043ebf0bf315c15e3ab

**Comment by mwhooker** [comment]
your packer install seems to be broken.

Please run `rm /usr/local/bin/packer-*` and I think this should be solved for you.

**Comment by davebiffuk** [comment]
Thanks, that has resolved it.

Was there anything in the output to suggest that was the problem?

Is this because the Packer install had been upgraded from an older version? (The `packer-*` files were dated 2015, I don't use Packer often.) Maybe the newer version could complain if it find out-of-date files?
