### ISSUE TITLE
Provide better error message when failing to parse core config

### ISSUE THREAD

**Issue by jurajseffer** [hashicorp/packer#5704]
Packer 1.1.3

I have defined `PACKER_CONFIG` environment variable inside a bash script that had the path to the build configuration only to receive this message:
```
2017/12/14 11:58:16 Attempting to open config file: /project/build.json
Error loading configuration: 

json: cannot unmarshal array into Go struct field config.Builders of type map[string]string
```

I wasn't aware `PACKER_CONFIG` was being used by Packer for core configuration. The above error message looked as if Packer was trying to map my build configuration into its internal config so it took me a while to figure out my env var is actually providing a path to "core" packer config, not the build one.

Could we improve the debug messages to explicitly mention that `PACKER_CONFIG` env var is defined and that "core" configuration is being read and mapped, rather than just generic "Attempting to open config file"?

**Comment by mwhooker** [comment]
yeah let's definitely log if the config came from the env. good idea!

**Comment by SwampDragons** [comment]
We already have a logline 
```		
log.Printf("'PACKER_CONFIG' set, loading config from environment.")
``` 

did it not show up for you? if so, what text change do you think would make it clearer?

**Comment by SwampDragons** [comment]
oh geez I'm dumb. this was already resolved in the length of time it's been open in my chrome tab.
