### ISSUE TITLE
Triton builder should create firewall rules on demand.

### ISSUE THREAD

**Issue by clstokes** [hashicorp/packer#5707]
The [Triton builder](https://www.packer.io/docs/builders/triton.html#source_machine_firewall_enabled) currently does not handle the creation and deletion of firewall rules for image building that other providers such as AWS do automatically. Users can use the [source_machine_firewall_enabled](https://www.packer.io/docs/builders/triton.html#source_machine_firewall_enabled) option to enable the machine's firewall but this requires that a _global_ rule already exists to allow SSH access.

The Triton builder should be enhanced with _two_ configuration options to facilitate Triton machine firewall usage during provisioning: 

- The first option should instruct the builder to create the necessary firewall rule to allow the necessary communicator access (e.g. SSH, WinRM, etc.) and restrict all other incoming connections via the machine's firewall.
- The second option should allow the user to restrict the communicator access via a CIDR block similar to the [temporary_security_group_source_cidr](https://www.packer.io/docs/builders/amazon-ebs.html#temporary_security_group_source_cidr) option for the AWS builder (but with Triton-specific terminology).

As an example with `create_temporary_machine_firewall` and `temporary_machine_firewall_source_cidr` as suggested _new_ options:
```
{
  "builders": [
    {
      "type": "triton",
      "source_machine_firewall_enabled": true,
      "create_temporary_machine_firewall": true,
      "temporary_machine_firewall_source_cidr": "203.0.113.1/32"      
      ...
    }
  ],
  ...
}
```

Note: The [source_machine_firewall_enabled](https://www.packer.io/docs/builders/triton.html#source_machine_firewall_enabled) option already exists for the Triton builder, so some consideration should be made for how these three options will work together.

**Comment by stack72** [comment]
@clstokes nice thoughts - I can look at this this week :)
