### ISSUE TITLE
Remove default for VMware tools_upload_path

### ISSUE THREAD

**Issue by mcandre** [hashicorp/packer#5708]
This is more of lodging a minor complaint than a call for code changes :/

As much as I favor convention over explicit, tedious configuration, there are some contexts where having a default value can be worse than requiring a user to provide one. Basically, there is no useful default value for `tools_upload_path` key, as each operating system presents a different path structure. Worse, packer users may forget to explicitly override this key and wonder why the tools image does not appear in the guest. I spent/wasted some time with a Mac guest trying to figure out why the `darwin.iso` VMware tools install media never appeared anywhere on disk, before I discovered that the default effective value `darwin.iso` was bad. Finally, I overrode this value with one that makes sense for my VM: `/Users/vagrant/darwin.iso`. If this path made sense as a better default, I would simply submit a PR to change the default value. Unfortunately, there can be no good default, as long as packer intends to support more than a single guest operating system flavor, including those with UNIX and Windows path structures.

Since packing can be a long process, I would prefer an experience where this key has NO default value, and is required to be explicitly configured whenever `tools_upload_flavor` is supplied. This way, packer can immediately point out the flaw at the beginning of `packer build`, rather than an hour later.

I realize that this change in key requirements is not easy to make with the current schema. In fact, pretty much the most direct way to accomplish this with something like JSON schema validation, is to refactor the `tools_upload_flavor` , `tools_upload_path`, keys into a single top-level optional unit, maybe call it `tools_driver`, which then has two required sub-keys: `tools_upload_flavor`, `tools_upload_path`. This would cleanly express the concept that a valid path should be configured for tools installation, and provide more immediate and explicit error messages for users attempting to pack boxes.

What do you think? Could we add this optional key, include it in JSON validation phase, and mark the old top-level keys as deprecated?

**Comment by mwhooker** [comment]
thanks for the report. I appreciate the behavior was confusing, but I don't think this is something we're going to change. I'd be happy to work on the docs a bit, but I think the behavior is fine for the general case. Going back in time, it probably would have been better to make the upload path a required parameter, but I don't think it's worth breaking everyone's scripts at this point.

If you check, I believe the iso should have been uploaded to the home directory of whatever user the communicator is configured with.
