### ISSUE TITLE
 BUG: -bash: ec2-bundle-vol: command not found after installed.

### ISSUE THREAD

**Issue by fewknow** [hashicorp/packer#5711]
Describe the problem and include the following information:

- Packer version from `Packer v1.1.2`
- Host platform : MacOS
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a gist https://gist.github.com
**I can include this later if needed.** 

- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your gist https://gist.github.com
**SORRY I DIDN'T USE GIST,  it is currently blocked by our firewall(working to fix).**
   
I am attempting to use packer to create an AMI.  I am getting this error. 
```
==> amazon-instance: Uploading X509 Certificate...
==> amazon-instance: Bundling the volume...
    amazon-instance: -bash: ec2-bundle-vol: command not found
==> amazon-instance: Volume bundling failed. Please see the output above for more
==> amazon-instance: details on what went wrong.
==> amazon-instance:
==> amazon-instance: One common cause for this error is ec2-bundle-vol not being
==> amazon-instance: available on the target instance.
```

I have a .sh script that runs as a shell provisione to install the ec2-ami-tools that looks like this: 
```echo "apt-get commands"
sudo apt-get update -y && sudo apt-get install -y ruby unzip

echo "wget for ec2 ami tools"
wget https://s3.amazonaws.com/ec2-downloads/ec2-ami-tools.zip

echo "make directory"
sudo mkdir -p /usr/local/ec2

echo "unzip tools"
sudo unzip ec2-ami-tools.zip -d /usr/local/ec2

echo "export variable EC2_AMITOOL_HOME"
export EC2_AMITOOL_HOME=/usr/local/ec2/ec2-ami-tools-1.5.7
echo $EC2_AMITOOL_HOME

echo "Set PATH"
export PATH=$EC2_AMITOOL_HOME/bin:$PATH
echo $PATH
```

If I spin up a machine manually and use this script the binary for ec2-bundle-vol is available. 

I can confirm the .sh scrip is running from the output here:
```
==> amazon-instance: Provisioning with shell script: build/scripts/ec2_bundle_vol.sh
    amazon-instance: apt-get commands
.....
.....
    amazon-instance: wget for ec2 ami tools
    amazon-instance: --2017-12-15 21:05:56--  https://s3.amazonaws.com/ec2-downloads/ec2-ami-tools.zip
.....
.....
    amazon-instance: make directory
    amazon-instance: unzip tools
    amazon-instance: Archive:  ec2-ami-tools.zip
.....
.....
    amazon-instance: export variable EC2_AMITOOL_HOME
    amazon-instance: /usr/local/ec2/ec2-ami-tools-1.5.7
    amazon-instance: Set PATH
    amazon-instance: /usr/local/ec2/ec2-ami-tools-1.5.7/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
==> amazon-instance: Uploading X509 Certificate...
```
Not sure what the issue could possible be at this point since I see : 
```
    amazon-instance: -bash: ec2-bundle-vol: command not found
```
 it is saying the command is not found but I am clearly installing this before calling it. 

Thank you for your time and help.

**Comment by SwampDragons** [comment]
My guess is that this is to do with all of the environment variables you are setting -- provisioners don't all execute in the same shell, so you need to pass in the environment variables you expect to have set for every provisioner.  If you're calling ec2-bundle-vol in a script that is different from the one installing it, you can't expect the env vars you set in the installation script to be available. 

Without seeing your actual config and scripts I'm not sure what else I can do for you.  

Here's an example of how to handle env vars: 

    "provisioners": [
    {
        "type": "shell",
        "environment_vars": ["MY_ENV_VAR=iAmAVar"],
        "scripts": ["./scripts/dummy_bash.sh"]
    }
    ]

And if my "dummy_bash.sh" script contains "echo $MY_ENV_VAR" then the output will be "iAmAVar

**Comment by rickard-von-essen** [comment]
As @SwampDragons said the modification of `PATH` doesn't persist to another (login) shell. You should permanently add `/usr/local/ec2/ec2-ami-tools-1.5.7/bin` to the `PATH` by adding it in `/etc/profile.d/`, see [Ubuntu help - System-wide environment variables](https://help.ubuntu.com/community/EnvironmentVariables#A.2Fetc.2Fprofile.d.2F.2A.sh).

**Comment by fewknow** [comment]
Thanks for the help.  I have added this to /etc/profile.d/myenvvars.sh. 
 
Wanted to update this incase anyone else comes across this issue because I also had to install 2 required packages for this to work.  Here is the modified script that works. 

```
echo "apt-get commands"
sudo apt-get update -y && sudo apt-get install -y ruby unzip

echo "wget for ec2 ami tools"
wget https://s3.amazonaws.com/ec2-downloads/ec2-ami-tools.zip

echo "make directory"
sudo mkdir -p /usr/local/ec2

echo "unzip tools"
sudo unzip ec2-ami-tools.zip -d /usr/local/ec2

echo "Create /etc/profile.d/myenvvars.sh"
sudo touch /etc/profile.d/myenvvars.sh

echo "Installing kpartx, grub as required by ec2-ami-tools"
sudo apt-get install kpartx -y
sudo apt-get install grub -y

echo "add to etc/profile.d/myenvvars.sh export variable EC2_AMITOOL_HOME"
sudo bash -c 'echo "export EC2_AMITOOL_HOME=/usr/local/ec2/ec2-ami-tools-1.5.7" >> /etc/profile.d/myenvvars.sh'
sudo bash -c 'echo "export PATH=/usr/local/ec2/ec2-ami-tools-1.5.7/bin:$PATH:" >> /etc/profile.d/myenvvars.sh'
```
