### ISSUE TITLE
VBoxGuestAdditions.iso: The system cannot find the path specified - same as #5600 but on Packer 1.1.3

### ISSUE THREAD

**Issue by h-vishal** [hashicorp/packer#5721]
Packer version 1.1.3
Host - Windows 10 amd64
Packer output - https://gist.github.com/h-vishal/017d2a7bed8239db996ec1f93406d09e
Template - https://gist.github.com/h-vishal/ef066da29330150e328df631049d787a

I do not have this issue on Packer version 1.1.1

**Comment by h-vishal** [comment]
Possibly same as #5713

**Comment by SwampDragons** [comment]
Yeah this looks like a duplicate of 5713.  Gonna close this to keep the conversation in one place.
