### ISSUE TITLE
Waiting for Digital Ocean Droplet to become active after snapshot complete

### ISSUE THREAD

**Issue by mattdeavesmf** [hashicorp/packer#5723]
## Background
After creating a snapshot on Digital Ocean, Packer waits for the droplet to become active - which it never does.  This behaviour seems strange to me because once the snapshot is made, the droplet isn't needed anymore and can be destroyed.

## Details
Packer v1.1.3
Host platform: Ubuntu 14.04
Simplest Template for reproduction and Debug Output: https://gist.github.com/mattdeavesmf/8f3289148dd932723e7a3ee0cb9f7a9b

**Comment by rickard-von-essen** [comment]
Your install is broken. Remove your current install directory and reinstall from [packer.io/downloads](https://www.packer.io/downloads.html). _Be sure to read the [**note** about upgrading from < 0.9.0.](https://github.com/hashicorp/packer/commit/1994793126f948dd99c8acdd35f999df0c6ab342)_
