### ISSUE TITLE
Packer-azure_arm: Use latest custom managed image name as source image

### ISSUE THREAD

**Issue by shriganeshs** [hashicorp/packer#5731]
Similar to the following way provided for amazon_ebs builder
```
"source_ami_filter": {
    "filters": {
        "name": "*custom_centos7_python36*"
    }, 
    "most_recent": "true"
} 
```

How can I get the latest source image `custom_managed_image_name` for Azure?

I will be storing images with name as `custom_centos7_python36_{{timestamp}}`, and I want to use the latest image as source image for new Packer build.

- Packer version 1.1.1

**Comment by boumenot** [comment]
There isn't an equivalent.  If you want this functionality, it would need to be implemented.

**Comment by phillipsj** [comment]
I am happy to try and take this on.  It would be my first issue and first go project.  I would like to see the Azure functionality grow.

**Comment by zhginev** [comment]
I was looking for the same functionality and came across this issue. Any chance you have any progress on it @phillipsj ?

**Comment by abhisheksinghrathod** [comment]
Hi @phillipsj,
I am also looking for this functionality for azure. Any help is much appreciated!

**Comment by LazzariPaolo** [comment]
@phillipsj did you ever get this feature working?
