### ISSUE TITLE
Problems programmatically interacting with Packer

### ISSUE THREAD

**Issue by charleslieferando** [hashicorp/packer#5733]
I am trying to programmatically call packer cli through a little go program. I am relatively new to go so any poinnters on where i am going wrong would be appreciated.

*main.go*

```go
package main

import (
	"github.com/hashicorp/packer/packer"
	"github.com/hashicorp/packer/version"
	"github.com/hashicorp/packer/template"
	"log"
)

func main() {

	template, err := template.ParseFile("manifest.json")

	if err != nil {
		log.Fatal(err)
	}

	config := packer.CoreConfig{
		Version: version.Version,
		Template: template,
	}

	core, err := packer.NewCore(&config)

	if err != nil {
		log.Fatal(err)
	}

	log.Print(core.BuildNames())

	for _,buildName := range core.BuildNames() {
		build, err := core.Build(buildName)

		if err != nil {
			log.Fatal(err)
		}


		build.Prepare()
		packerUi := packer.ColoredUi{}

		build.Run(&packerUi, nil)
	}
}
```

I get the following error:

```go
go run baker.go 
2017/12/24 03:36:46 [docker]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6cc027]

goroutine 1 [running]:
github.com/hashicorp/packer/packer.(*Core).Build(0xc420078410, 0xc420017018, 0x6, 0x1, 0x0, 0xc4200a1ee0, 0x412408)
        /home/charles/Documents/work/go/src/github.com/hashicorp/packer/packer/core.go:105 +0xa7
main.main()
        /home/charles/Documents/work/takeaway/workspace/go/betcy/main.go:33 +0x246
exit status 2

```

**Comment by rickard-von-essen** [comment]
You need to properly initialize your `CoreConfig`.

`invalid memory address or nil pointer dereference` means that you dereference a unset variable (in this case a struct field).

I your case you haven't configured the `ComponentFinder`.

**Comment by rickard-von-essen** [comment]
You need to properly initialize your `CoreConfig`.

`invalid memory address or nil pointer dereference` means that you dereference a unset variable (in this case a struct field).

I your case you haven't configured the `ComponentFinder`.

**Comment by charleslieferando** [comment]
@rickard-von-essen  you say I should feel free to ask here. Where exactly? I asked this question and you closed the issue.

I guess my problem right now is how do I initialize a ComponentFinder? Thanks!

**Comment by rickard-von-essen** [comment]
I closed since this is not an issue that we will fix, since there is nothing wrong.

**Comment by rickard-von-essen** [comment]
This is a core part of the code that we don't change much so I don't really know. My advise would be to search the code for `ComponentFinder` and look how it's done. Maybe start with how it's done in a test. For example https://github.com/hashicorp/packer/blob/81522dced0b25084a824e79efda02483b12dc7cd/command/build_test.go#L135
