### ISSUE TITLE
Feature request: Handle DigitalOcean snapshots (rotate/overwrite)

### ISSUE THREAD

**Issue by ivan-pinatti** [hashicorp/packer#5734]
Hi,

It would be nice if there was a feature to handle DigitalOcean snapshots similar what we do have for AWS EC2 AMIs.

What I mean is;

You could choose to remove (destroy) a current snapshot before creating a new one.

**OR**

To destroy the old one after a new is created.

This is a kind of a snapshot rotation, IMHO, second option is the best.
Current workflow only creates a new snapshots and they keep accumulating, even if they have the same name.

Thank you,

Ivan Pinatti

**Comment by rickard-von-essen** [comment]
There is a subtle but important difference. AWS AMI names are unique, thus the `--force` flag will remove the AMI with the same name. On Digital Ocean snapshot names doesn't have to be unique. 

I'll close this as I don't think this is a thing Packer should handle (we avoid doing image lifecycle management).

---

You can easily delete all snapshots except the latest one with this oneliner:

```shell
$ doctl compute snapshot list <snapshot_name> --format "ID" --no-header | sed '$d'
 | xargs doctl compute snapshot delete -f
```
