### ISSUE TITLE
"Incompatible API Version" with custom plugin

### ISSUE THREAD

**Issue by jamesla** [hashicorp/packer#5736]
I am trying to create a plugin for packer and it compiles fine but when I try and run the plugin using packer build, I am getting the below error. 

I have read through the docs and can't understand what is out of date. Am using packer 1.1.3.

```
packer build packer.json
Failed to initialize build 'james': error initializing builder 'james': Incompatible API version with plugin. Plugin version: 4, Ours: 4
james output will be in this color.
```

Any idea on how I can fix this?

Repository here https://github.com/jamesla/packer-test-plugin

**Comment by mwhooker** [comment]
I would check your dependencies. I've recently updated the docs (not live yet) to recommend using govendor. You can see a working plugin that I've been working on here that uses govendor: https://github.com/mwhooker/packer-builder-matt-hello
