### ISSUE TITLE
Feature: Serve installation media over FTP, similar to HTTP

### ISSUE THREAD

**Issue by mcandre** [hashicorp/packer#5745]
Some older systems like NetBSD do not feature an HTTP client out of the box, but do feature an FTP client. In order to pack these boxes more conveniently, it would be helpful if packer supported serving static files over FTP to guest VM's during packing, similar to how files can be served over HTTP.

**Comment by rickard-von-essen** [comment]
Specifically NetBSD's `ftp` tool can use HTTP. See https://github.com/boxcutter/bsd/blob/master/netbsd.json#L16

Do you have any other example? Otherwise I think we can close this for now since at least I haven't found any OS yet that don't support HTTP (but there might be some out there).

**Comment by mcandre** [comment]
@rickard-von-essen Works for me, at least for NetBSD builds.

**Comment by rickard-von-essen** [comment]
Ok, let's close this until we find a concrete example. Feel free to reopen this or a new issue.
