### ISSUE TITLE
Packer hangs on "Trying port" (trying the same port endlessly)

### ISSUE THREAD

**Issue by wskorodecki** [hashicorp/packer#5748]
- Packer version: `1.1.3`
- Host: `Linux archlinux 4.13.8-1-ARCH #1 SMP PREEMPT Wed Oct 18 11:49:44 CEST 2017 x86_64 GNU/Linux`
- VRDP port configuration in template.json:
```json
"vrdp_bind_address": "127.0.0.1",
"vrdp_port_min": "5950",
"vrdp_port_max": "5950",
```

Today Packer has surprised me by hanging immediately after `Creating hard drive...` message. I've checked verbose log output which shows that this is related to VRDP port:
```
2017/12/31 17:33:13 packer: 2017/12/31 17:33:13 stdout:
2017/12/31 17:33:13 packer: 2017/12/31 17:33:13 stderr:
2017/12/31 17:33:13 packer: 2017/12/31 17:33:13 Not attaching guest additions since we're uploading.
2017/12/31 17:33:13 packer: 2017/12/31 17:33:13 Looking for available port between 5950 and 5950 on 127.0.0.1
2017/12/31 17:33:13 packer: 2017/12/31 17:33:13 Trying port: 5950
2017/12/31 17:33:13 packer: 2017/12/31 17:33:13 Trying port: 5950
2017/12/31 17:33:13 packer: 2017/12/31 17:33:13 Trying port: 5950
2017/12/31 17:33:13 packer: 2017/12/31 17:33:13 Trying port: 5950
2017/12/31 17:33:13 packer: 2017/12/31 17:33:13 Trying port: 5950
2017/12/31 17:33:13 packer: 2017/12/31 17:33:13 Trying port: 5950
2017/12/31 17:33:13 packer: 2017/12/31 17:33:13 Trying port: 5950
2017/12/31 17:33:13 packer: 2017/12/31 17:33:13 Trying port: 5950
2017/12/31 17:33:13 packer: 2017/12/31 17:33:13 Trying port: 5950
2017/12/31 17:33:13 packer: 2017/12/31 17:33:13 Trying port: 5950
2017/12/31 17:33:13 packer: 2017/12/31 17:33:13 Trying port: 5950
2017/12/31 17:33:13 packer: 2017/12/31 17:33:13 Trying port: 5950
( Log has been truncated - there were MANY more such lines. Massive spam. )
```
which is already in use by VirtualBox:
```
tcp        0      0 127.0.0.1:5950          0.0.0.0:*               LISTEN      27553/VBoxHeadless
```
I've killed that process, restarted packer and then everything goes fine.
### Solutions / recommendations:

Packer should check the same port after some delay (a few seconds will be ok). It should not check the same port more than a few times - a good practice is to not exceed three attempts. If there are no free ports in a specified range after all checks then it should display an error and exit.

**Comment by rickard-von-essen** [comment]
The simple "work around" is to not limit the vrdp port so there will always be a free port available.

**Comment by SwampDragons** [comment]
Cleaning up old issues, and found this.  Sorry for not responding nearly a year ago.  😬 From my perspective, this isn't a bug. You've set it to only try one port. it'll keep trying that port until it times out. This is expected behavior.
