### ISSUE TITLE
ssh_pty enabled by default for macOS hosts

### ISSUE THREAD

**Issue by mcandre** [hashicorp/packer#5750]
I recently started packing boxes from Windows hosts to compare how the build works from macOS hosts. When I changed to Windows host, I noticed that the provisioning phase of my packer builds now fails with error messages about missing tty. Evidently, `ssh_pty` was somehow enabled in macOS, even though I never explicitly configured it, and the packer docs say that this should be off by default. So I guess I would like the situation clarified for macOS hosts, either update the docs or ensure that `ssh_pty` is in fact disabled by default.

**Comment by rickard-von-essen** [comment]
Specifically pty can be assigned with [ssh_pty](https://www.packer.io/docs/templates/communicator.html#ssh_pty). Packer use a native golang ssh library and not OpenSSH so flags for it can't be used. Is there anything else you are looking for?

**Comment by kikitux** [comment]
@mcandre in order to update the docs, can you be more specific on where you would like to have this information, and what combination you found goes against the documentation?
