### ISSUE TITLE
File copy failing when copying an empty file for Windows 2016 builds

### ISSUE THREAD

**Issue by diegogoding** [hashicorp/packer#5752]
The resolution for this issue is breaking Windows 2016 builds when copying an empty file, such as an empty `__init__.py` file: [issues: 4891](https://github.com/hashicorp/packer/issues/4891)

I done some regression testing, prior to the PR: [PR: winrmcp/pull/27](https://github.com/packer-community/winrmcp/pull/27) it works fine. Switching to the PR version, it then breaks the build. 
It appears to break on empty files, in this case an empty `__init__.py`
```
found error: Error removing temporary file $env:TEMP\winrmcp-ddcd4032-b8f8-4f2d-5bfa-eb8fd5e80a5c.tmp: cleanup operation returned code=1
```

Here are the logs.
```
2017/12/31 17:35:05 ___go_build_github_com_hashicorp_packer: 2017/12/31 17:35:05 Moving file from $env:TEMP\winrmcp-ddcd4032-b8f8-4f2d-5bfa-eb8fd5e80a5c.tmp to c:\some\python\module\__init__.py
2017/12/31 17:35:07 ___go_build_github_com_hashicorp_packer: #< CLIXML
2017/12/31 17:35:07 ___go_build_github_com_hashicorp_packer: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="1"><TNRef RefId="0" /><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>2017/12/31 17:35:07 Removing temporary file $env:TEMP\winrmcp-ddcd4032-b8f8-4f2d-5bfa-eb8fd5e80a5c.tmp
2017/12/31 17:35:09 ___go_build_github_com_hashicorp_packer: #< CLIXML
2017/12/31 17:35:09 [INFO] (telemetry) ending file
2017/12/31 17:35:09 [INFO] (telemetry) found error: Error removing temporary file $env:TEMP\winrmcp-ddcd4032-b8f8-4f2d-5bfa-eb8fd5e80a5c.tmp: cleanup operation returned code=1
```
I am getting this error on packer versions greater than 1.1.0. And I have isolate the error to that PR for issue 4891. If I put a little more text in the file, just a short comment, no error. 

I am not sure of the cause, nor the fix.

**Comment by diegogoding** [comment]
I have a PR for the fix: [winrmcp/pull/28](https://github.com/packer-community/winrmcp/pull/28) 

It just now checks for the existence of temp file before trying to delete it. Fixes the above issue, because temp files are not created for empty source files.

**Comment by SwampDragons** [comment]
Thanks for making that PR.  Looks like the only thing we need to do on our end is update the winrmcp vendor.

**Comment by SwampDragons** [comment]
Yeah, I've validated that your winrmcp change fixes this empty-file-copying issue.  PR linked above.
