### ISSUE TITLE
The VirtualBox builder checks the value of the `guest_additions_url` _before_ it interpolates any user-variables that compose it.

### ISSUE THREAD

**Issue by arizvisa** [hashicorp/packer#5756]
In the VirtualBox builder for "Packer v1.1.3", the code checks to see if the value of `guest_additions_url` is empty before deciding whether to download the URL or to call into the driver to locate the Guest Additions iso.

The issue is that the value of `guest_additions_url` is checked before any of the user-variables are expanded (interpolated). This means that when the url is checked for whether it's the empty string (thus causing it to use the driver to determine the path), it's actually doing a comparison against the value of ```{{user `variable-name`}}``` instead of the default specified in the "variables" section.

This makes it impossible to use a user-variable to tell packer that it needs to figure out where the guest additions iso is itself.

To reproduce, simply add ```"guest_additions_url": "{{user `guest_additions_iso`}}",``` to a "virtualbox-iso" typed build-definition and define a variable ```"guest_additions_iso": "",``` in the "variables" section. By default it should ask the driver for the path to the iso due to the value being expanded to "" (empty), but instead the comparison for emptiness is being done against the non-interpolated version of the string.

You can see here in [builder/virtualbox/common/step_download_guest_additions.go:70](https://github.com/hashicorp/packer/blob/master/builder/virtualbox/common/step_download_guest_additions.go#L70) that the url is grabbed from the template (1), checked for emptiness (2), and then interpolated (3). If the string is empty/undefined, then call `driver.Iso()` to figure it out (4).
```
	// Use the provided source (URL or file path) or generate it
	url := s.GuestAdditionsURL                          // #1
	if url != "" {                                      // #2
		s.Ctx.Data = &guestAdditionsUrlTemplate{
			Version: version,
		}

		url, err = interpolate.Render(url, &s.Ctx)  // #3
		if err != nil {
			err := fmt.Errorf("Error preparing guest additions url: %s", err)
			state.Put("error", err)
			ui.Error(err.Error())
			return multistep.ActionHalt
		}
	} else {
		url, err = driver.Iso()                     // #4
```

To fix this, you can invert the case (2), and then move the interpolation (3) so that it follows the snag of the GuestAdditionsURL variable (1).

**Comment by arizvisa** [comment]
PR #5757 should fix this as specified in the previous comment.

**Comment by SwampDragons** [comment]
fix is merged with master and tagged for release with 1.1.4
