### ISSUE TITLE
Packer waits too long before timing out on expired temporary credentials

### ISSUE THREAD

**Issue by et304383** [hashicorp/packer#5760]
Packer version: 1.1.3
OS: Ubuntu 16.04

Since Packer doesn't support prompting for MFA (this is an entire issue on its own) I am forced to set env vars using a shell script which does an STS call (just like I must do for Terraform).

When these credentials expire and I run packer, I'm forced to wait several minutes for a timeout on checking the AMI name.  Worse, I can't Control-C because apparently packer is a tool that doesn't support being killed by Control-C like most CLI tools?

Please fix this to fail more quickly (ie - instantly) when the temp creds have expired.

**Comment by rickard-von-essen** [comment]
> Worse, I can't Control-C because apparently packer is a tool that doesn't support being killed by Control-C like most CLI tools?

Ctrl-c send interupt, not kill and Packer certainly supports it but the code needs to check if it has been interupted/aborted. When that happens Packer needs to cleanup before stopping. This is mostly handled by framework code but needs to be handled in wait loops and other long running operations.

If you provide details on where ctrl-c responds slowly we can see if there is some missing interupt check. Some operations can't be reverted until the preceding operation finishes.

**Comment by et304383** [comment]
It's happening at the point of doing "prevalidation" of the AMI name.  It hangs there for several minutes.  Control-C at this point does nothing.

**Comment by kwilczynski** [comment]
I think this might - need confirmation - be a side effect of the AWS SDK. For what is worth, Terraform has the exact same behaviour when the session expires (e.g. mid-apply), or when the credentials are already expired and you try to do refresh or apply. It would then hang and it seems that the signal handler is not firing. I did not investigate very deeply - would need to see some strace or attach a gdb to confirm what is going on.

**Comment by mwhooker** [comment]
I think I might know what's going on. I think it's following the credential provider chain down to the `EC2RoleProvider` which tries to contact the metadata service. Unless you're in ec2 that call takes 30 seconds or so to timeout. @et304383 Can you post the packer output after it times out?

Terraform does some really tricky business around sourcing their credentials which works around this. I think we can work around it by setting a shorter timeout on metadata calls. Will look again at terraform to see if there's a slick way to bail out immediately.

**Comment by mwhooker** [comment]
Here's how terraform does it https://sourcegraph.com/github.com/terraform-providers/terraform-provider-aws@1866726e0c9fd30f147933ffbb022e916342bf51/-/blob/aws/auth_helpers.go?utm_source=share#L111-177

I think I can copy and paste that and get essentially what we need

**Comment by mwhooker** [comment]
@et304383 any chance you want to test the code in #5764? I can make you a build if you want

**Comment by et304383** [comment]
@mwhooker if you can provide a build (just a packer executable for Linux tit) I can test.  I don't have a lot of time to look into how to build from source unless it's just a few commands run against a branch.

**Comment by mwhooker** [comment]
@et304383 here ya go
[5764.zip](https://github.com/hashicorp/packer/files/1612866/5764.zip)

**Comment by danvaida** [comment]
FWIW, I can still reproduce this on `v1.3.1`. I left it hanging for 5+ minutes and eventually had to manually kill the processes.

**Comment by SwampDragons** [comment]
Sorry to hear this Dan; Can you please open a new one with steps to reproduce and debug logs?
