### ISSUE TITLE
Packer powershell provisioner default execute_command seems not be working

### ISSUE THREAD

**Issue by kaluznyt** [hashicorp/packer#5772]
Packer version: 1.1.3
Host platform: Windows 10 / Guest windows 2012 r2 (vmware)

Debug log output from `PACKER_LOG=1 packer build template.json`.
https://gist.github.com/kaluznyt/fe7ed0458b1a2eeafdabf322cb1857e4

The _simplest example template:
https://gist.github.com/kaluznyt/c961593c190d4c6840bc9d663ad6e056

scripts
https://gist.github.com/kaluznyt/5be2c65bc38d36d8e30ef1f7790fe068
  
I tried to add a simple powershell script that would add an entry to the hosts file, just as an first example on how the powershell provisioner works, but I encounter the issue with it. Not sure if it's a bug if I'm doing anything wrong, but I also tried to run locally these powershell commands and seems I'm getting the same error. Like the default execute_command for powershell doesn't have a correct syntax:

`powershell -executionpolicy bypass "& { if (Test-Path variable:global:ProgressPreference){$ProgressPreference='SilentlyContinue'};{{.Vars}}&'{{.Path}}';exit $LastExitCode }"`
  

The debug fragment containing errors: 
https://gist.github.com/kaluznyt/fe7ed0458b1a2eeafdabf322cb1857e4#file-packer-debug-powershell-provisioner-error-log-L515-L657

**Comment by kaluznyt** [comment]
So this is what is being actually run:
`powershell -executionpolicy bypass "& { if (Test-Path variable:global:ProgressPreference){Set-Variable -Name 'ProgressPreference' -Value 'SilentlyContinue' -Scope Global};$env:PACKER_BUILDER_TYPE=\"vmware-iso\"; $env:PACKER_BUILD_NAME=\"vmware-iso\"; $env:SALT_MASTER_HOST=\"salt\"; $env:SALT_MASTER_IP=\"192.168.33.10\"; &'c:/Windows/Temp/script-5a536eed-98f9-84d2-455b-808c3f8832b4.ps1';exit $LastExitCode }`

Locally something like this is working for me (slightly modified version):   

``powershell -executionpolicy bypass "& {if (Test-Path variable:global:ProgressPreference){Set-Variable -Name 'ProgressPreference' -Value 'SilentlyContinue' -Scope Global}; `$env:PACKER_BUILDER_TYPE='vmware-iso'; `$env:PACKER_BUILD_NAME='vmware-iso'; `$env:SALT_MASTER_HOST='salt'; `$env:SALT_MASTER_IP='192.168.33.10'; &'C:\users\tkaluzny\script.ps1'} "``

Most probably backticks need to be used in front of $env as it seems evaluated to empty/null and the :XX part remains. Not sure about the set-variable thought, actually the script works, but progress isn't used anywhere in my test script so it isn't tested.

**Comment by SwampDragons** [comment]
Have you gotten it working by sending in your own execute_command with the backticks included?  Or are you still blocked on this?

**Comment by kaluznyt** [comment]
Actually I made a bit different command (more complex) and it went further, but then I got another error from scp: ambigous path or something like this (this was related to the elevated script, as I tried to run this as a elevated script, since hosts file need to be modified with elevated rights). Therefore I just threw away powershell provisioner and user normal shell provisioner running batch script with just ECHO %VAR1% %VAR2% > %SYSTEMPATH%/system32/drivers/etc/hosts and that worked fine! However would be nice to run a powershell scripts, i'll probably have another attempts. Sorry for not too much info but I have stuff on another laptop.

**Comment by SwampDragons** [comment]
I wasn't able to reproduce this on a win2012r2 AWS instance; your script runs fine.  In the past I've seen this style of error when someone tries to run the powershell provisioner before the powershell modules are fully loaded; in the winrm communicator we've added a wait so that it doesn't think it's connected until powershell is successfully loaded up.  I'm not sure that there is a similar check for the ssh communicator, which may be the source of this issue.  

Can you add a `"pause_before": "30s"` to the provisioner (leaving the execute_command as the default) and tell me if that improves reliability for you?
