### ISSUE TITLE
Add Naver Cloud Platform Builder

### ISSUE THREAD

**Issue by YuSungDuk** [hashicorp/packer#5775]
[Naver Cloud Platform](https://www.ncloud.com) is cloud platform service in Korea and support to create vm instance and server images. 
Would be nice to be able to use packer to make Naver Cloud Platform Server Images.

**Comment by mwhooker** [comment]
If someone were to write a PR for this I'm sure we could merge it. Feel free to reach out to me at mhooker <at> hashicorp if you want to discuss what would be needed
