### ISSUE TITLE
Support creation of elastic ip address for AWS non-default VPCs

### ISSUE THREAD

**Issue by anthcourtney** [hashicorp/packer#578]
At present when I try to use the amazon-ebs builder for a non-default VPC, the instance is provisioned with a private ip address which packer cannot ssh into (as there is no route to the private ipaddress from the host where packer is being invoked).

```
2013/10/31 13:50:54 ui: ==> amazon-ebs: Launching a source AWS instance...
2013/10/31 13:50:58 /home/anth/packer/packer-builder-amazon-ebs: 2013/10/31 13:50:58 instance id: i-404e780c
==> amazon-ebs: Waiting for instance (i-404e780c) to become ready...
2013/10/31 13:50:58 ui: ==> amazon-ebs: Waiting for instance (i-404e780c) to become ready...
2013/10/31 13:50:58 /home/anth/packer/packer-builder-amazon-ebs: 2013/10/31 13:50:58 Waiting for state to become: running
    amazon-ebs: Private IP: 192.168.167.142
2013/10/31 13:51:15 ui:     amazon-ebs: Private IP: 192.168.167.142
2013/10/31 13:51:26 /home/anth/packer/packer-builder-amazon-ebs: 2013/10/31 13:51:26 Waiting for SSH, up to timeout: 1m0s
==> amazon-ebs: Waiting for SSH to become available...
2013/10/31 13:51:26 ui: ==> amazon-ebs: Waiting for SSH to become available...
2013/10/31 13:51:32 /home/anth/packer/packer-builder-amazon-ebs: 2013/10/31 13:51:32 Opening conn for SSH to tcp 192.168.167.142:22
```

This results in failure every time.

Can an option be added which is similar to the aws.elastic_ip option within vagrant so that an elastic ip address is allocated to the new instance?

https://github.com/mitchellh/vagrant-aws/issues/18

cheers,
Anth

**Comment by pkaramol** [comment]
Does this mean `elastic` or just `public` IP?

**Comment by rickard-von-essen** [comment]
It means (nat'ed) public IP, not EIP. If you need EIP use a user-script that attaches it and set `ssh_host` to the IP.
