### ISSUE TITLE
VMWare-iso not connecting to Network

### ISSUE THREAD

**Issue by DanielBo** [hashicorp/packer#5784]
I am trying to deploy a CoreOS Image into an ESXi 6.5 Server.

The Issue i am facing is that the Machine is unable to connect to the "VM Network" on the ESXi Server.

Networkdevice says its connected if i set the following: "ethernet0.startConnected": "TRUE"

But if i look into the machines hardware configuration in the ESXi UI it says "connected: false"

As I wasn't able to find a proper documentation on the vmx_data, I manually created a coreOS machine on the Server and exported the configuration. Which leads to a ovf file. Then i converted the ovf file to a VMX Version of said machine and copied the configuration into my json. Linked as "Full Sample"

However this leads to the same behaviour as the reduced version. I provided both as I'm not sure if I'm missing something essential in either configuration.

The ESXi host is in default configuration. To minimize possible Sources of Error i have turned off the firewall of the Server is its not in productive use.

The Machine I used as a template works fine. Created by manually registering a machine on the host using the same image
![image](https://user-images.githubusercontent.com/3023733/34823294-2652a7a8-f6ca-11e7-946d-e1cd7b8bb8c2.png)

And I am able to ping google from within the manually created machine. I am unable to do the same from the machine created by packer. I tried to do this by using the ESXi web interface to create a shell on the VM, while packer is waiting for the ssh connection to pop up.

LOG
https://gist.github.com/DanielBo/c2260a668b836ac2b90b448353a066fa

Reduced Sample
https://gist.github.com/DanielBo/cc4b31115a4a83f5ce145c4500e13b71

Full Sample
https://gist.github.com/DanielBo/c86e9d9943595d6d091d78ee4aaf34bf

**Comment by techyosa** [comment]
Hi,

Add inside "vmx_data"

"ethernet0.networkName": "VM Network",

thanks,

**Comment by SwampDragons** [comment]
I'm closing because it was never clear on this issue whether it was a usage question or a bug; if you are still trying to get this working, please reach out to our [mailing list](https://groups.google.com/d/forum/packer-tool) for help debugging networking.
