### ISSUE TITLE
Provisioning of Azure Linux VM fails

### ISSUE THREAD

**Issue by SaiVikas-Dharmaraju** [hashicorp/packer#5788]
Hi,

Am trying to create and publish a custom image in Azure but packer build fails during the provisioning state with the below error

Error:
"Script disconnected unexpectedly. If you expected your script to disconnect, i.e. from a restart, you can try adding `"expect_disconnect": true` to the shell provisioner parameters."

Am trying to create a new image with some custom packages installed on Centos 7.2. 

I tried setting up expect_disconnect as true but by doing so image gets created but am not able to create a VM from such image files. 

This issue is happening sporadically like 3-4 of 10 times on some days while with no such failures on other days. This is highly inconsistent and need your help in resolving the same 

TIA

**Comment by mwhooker** [comment]
Please post the following information:

- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a gist https://gist.github.com
- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your gist https://gist.github.com

**Comment by boumenot** [comment]
Sorry, I missed this issue.

I also recommend that you follow the CentOS 7.x example for Azure that [is in the repo](https://github.com/hashicorp/packer/blob/master/examples/azure/centos.json). This is a known good example.

**Comment by SaiVikas-Dharmaraju** [comment]
Packer logs  -- https://gist.github.com/SaiVikas-Dharmaraju/bb267b36bdefd25127baf330f888179f

The Packer file that i used is very similar to this [example](https://github.com/hashicorp/packer/blob/master/examples/azure/centos.json)

**Comment by boumenot** [comment]
Please provide a template example. The example you pointed to does not demonstrate the issue.

From what I can see, Packer is working correctly.  I suspect your provisioner is forcing a reset of the SSH session. If this is expected please follow the advice in the output.

```text
2018/01/17 09:39:24 [INFO] (telemetry) found error: Script disconnected unexpectedly. If you expected your script to disconnect, i.e. from a restart, you can try adding `"expect_disconnect": true` to the shell provisioner parameters.
```

**Comment by boumenot** [comment]
Please re-open if you can provide the necessary information.
