### ISSUE TITLE
Can't download local VBoxGuestAdditions on Windows

### ISSUE THREAD

**Issue by GMC-I-Messtechnik** [hashicorp/packer#5801]
Since packer v1.1.2 it is not possible to download or copy the VBoxGuestAdditions.

My host platform is Windows 7 amd64.`

Packer v1.1.3 says:
```
==> virtualbox-iso: Downloading or copying Guest additions
    virtualbox-iso: Downloading or copying: file://C:/Program%20Files/Oracle/VirtualBox/VBoxGuestAdditions.iso
    virtualbox-iso: Error downloading: CreateFile /Program Files/Oracle/VirtualBox/VBoxGuestAdditions.iso: Das System kann den angegebenen Pfad nicht finden.
==> virtualbox-iso: Guest additions download failed.
Build 'virtualbox-iso' errored: Guest additions download failed.
```

Since Packer v1.1.1 the url of the iso changed.
v1.1.1
```
Downloading or copying: file:///C:/Program%20Files/Oracle/VirtualBox/VBoxGuestAdditions.iso
```

v1.1.2 and v1.1.3
```
Downloading or copying: file://C:/Program%20Files/Oracle/VirtualBox/VBoxGuestAdditions.iso
```

After the scheme ("file:") there were three slashes. Now there are only 2 slashes!
This change combined with the change in `common/download.go` from commit 4fb8a27879421803d82e2a5d7d437560a3208d74 ("remove the actual offending code") leads to an error under windows!

```
packer v1.1.3.exe: Parsed URL: &url.URL{Scheme:"file", Opaque:"", User:(*url.Userinfo)(nil), Host:"C:", Path:"/Program Files/Oracle/VirtualBox/VBoxGuestAdditions.iso", RawPath:"", ForceQuery:false, Ra
wQuery:"", Fragment:""}
packer v1.1.3.exe: [DEBUG] Using local file: /Program Files/Oracle/VirtualBox/VBoxGuestAdditions.iso
```

As you can see in the Log, the url with two slashes needs the combination of host and path for finalpath.
With three slashes there wasn't such a problem as the path was `/C:/Program Files/Oracle/VirtualBox/VBoxGuestAdditions.iso` and got corrected by the removed lines (`finalPath = finalPath[1:]`).

**Comment by SwampDragons** [comment]
I think this has been addressed on our master branch; see https://github.com/hashicorp/packer/pull/5761 for context.  Can you try building master (or using the packer binary uploaded in the comments of that PR) to see if that solves your issue?

**Comment by GMC-I-Messtechnik** [comment]
Yes, PR #5761 fixed this issue.
Thanks for your work (and sorry for that duplicate).
