### ISSUE TITLE
Allow the specification of role in amazon-import/post-processor.go

### ISSUE THREAD

**Issue by jc-m** [hashicorp/packer#5814]
Aws import-image api allow the specification of the role name. The default is vmimport.
Allowing the specification of this role allows customization in complex environment where roles are following a specific naming convention.

**Comment by mwhooker** [comment]
sounds good. This would be a great first issue if anyone wants to work on it. in `post-processor/amazon-import/post-processor.go`, you'd want to add the field to the `Config` struct, and set it as `RoleName` in `ImportImageInput` if it's set.  It should also be documented in `website/source/docs/post-processors/amazon-import.html.md`

**Comment by brianterry** [comment]
I would love to implement this.
