### ISSUE TITLE
Unable to pass extra-vars in JSON format to ansible provisioner

### ISSUE THREAD

**Issue by ksmets** [hashicorp/packer#5815]
I'm able to provide extra-vars as key=value pairs when using the ansible provisioner. However, I'm unable to pass them in JSON format. Values passed in using the key=value syntax are interpreted as strings. Use the JSON format if you need to pass in anything that shouldn’t be a string (Booleans, integers, floats, lists etc). See http://docs.ansible.com/ansible/latest/playbooks_variables.html#passing-variables-on-the-command-line for more details.

packer version: `1.1.3`

platform:  `Darwin alfheim.local 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64`

This works: `packer build -var-file=variables.json template-key-value.json`

```
"provisioners": [{
    "type": "ansible",
    "playbook_file": "playbook.yml",
    "extra_arguments": [
      "--extra-vars",
      "ansible_python_interpreter='/usr/bin/env python3'"
    ]
  }]
```

This fails: `packer build -var-file=variables.json template-json.json`

```
"provisioners": [{
    "type": "ansible",
    "playbook_file": "playbook.yml",
    "extra_arguments": [
      "--extra-vars",
      "'{\"ansible_python_interpreter\": \"/usr/bin/env python3\"}'"
    ]
  }]
```

For more details see my gist: https://gist.github.com/ksmets/a76b0fa706ae6f8a172041e93bcdc0ae

Note the 'Executing Ansible' command that's generated in both cases works when running the ansible-playbook against the remote host. So extra-vars in JSON format are lost when actually executing it.

**Comment by flowerysong** [comment]
This (probably) isn't a Packer bug. The argument you're passing to Ansible is incorrect, as the surrounding single quotes will prevent Ansible from parsing it. (Ansible should probably warn about this situation instead of silently ignoring the string, but it doesn't.)

It should be `"{\"ansible_python_interpreter\": \"/usr/bin/env python3\"}"` (or you can use YAML to avoid all that escaping: `"{ansible_python_interpreter: '/usr/bin/env python3'}"`)

**Comment by SwampDragons** [comment]
Did flowerysong's recommendation work for you? Can I close this ticket?

**Comment by ksmets** [comment]
Yes. It worked!
