### ISSUE TITLE
Packer not creating VirtualBox port forwarding rule

### ISSUE THREAD

**Issue by obitech** [hashicorp/packer#5821]
I'm trying to use the `virtualbox-ovf` builder to build an Ubuntu Server 16.04 image from an existing `.ova` file. When starting the Packer build, no forwarded port rule gets created and SSH times out. I can confirm this by looking into the VirtualBox GUI and seeing an empty NAT port forwarding rule set. If I create the rule manually through the GUI while SSH is retrying (using the port from the packerlog), a connection can be established and the build completes. Any ideas how to debug this?

- Packer version: 1.1.3
- VirtualBox version: 5.2.6
- Host platform: Windows 10 Pro 1703
- Debug log: [gist](https://gist.github.com/obitech/525fd09c4dfe2de693c0b78aec1f742c)
- Packer template: [gist](https://gist.github.com/obitech/bdfbc39d8ac14e32690586330a93ed2e)

**Comment by SwampDragons** [comment]
When you manually create the port mapping, are you running the command found in the logs here?  ```2018/01/26 10:57:20 packer.exe: 2018/01/26 10:57:20 Executing VBoxManage: []string{"modifyvm", "Demoshop 2.2", "--natpf1", "packercomm,tcp,127.0.0.1,3090,,22"}
```

**Comment by obitech** [comment]
I have to enter it through the VirtualBox GUI. Entering the command shown in the log via PowerShell will give me an error:
`` 
VBoxManage.exe: error: The machine 'Demoshop 2.2' is already locked for a session (or being unlocked)
VBoxManage.exe: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "LockMachine(a->session, LockType_Write)" at line 523 of file VBoxManageModifyVM.cpp
``

**Comment by flamarion** [comment]
I'm facing the very same issue.

```
2018/07/18 13:33:41 ui: ==> s5-unix-opensuse-42-x86_64-base-20180718T113334: Creating forwarded port mapping for communicator (SSH, WinRM, etc) (host port 2772)
2018/07/18 13:33:41 packer: 2018/07/18 13:33:41 Executing VBoxManage: []string{"modifyvm", "s5-unix-opensuse-42-x86_64-base", "--natpf1", "packercomm,tcp,127.0.0.1,2772,,22"}
==> s5-unix-opensuse-42-x86_64-base-20180718T113334: Creating forwarded port mapping for communicator (SSH, WinRM, etc) (host port 2772)
```

**Comment by jgmchan** [comment]
I just hit this issue as well. It looks like packer is trying to set the port forward on an interface that has not been set up for NAT'ing yet.

The workaround I did was to manually change the interface to a NATed interface first:
```
{
  "builders": [
    {
      "vboxmanage": [
        ["modifyvm", "{{.Name}}", "--nic1", "nat"]
      ]
    }
  ]
}
```

The port forwarded rule is added properly after this.
