### ISSUE TITLE
Google image burn fails in projects with no default service account

### ISSUE THREAD

**Issue by pdarvasi** [hashicorp/packer#5825]
Starting from version Packer 1.0.0, we cannot use Packer for Google as our GCP Project has no default service account, even though I specify the correct service account as input parameter "account_file".
This seems to be because [this](https://github.com/hashicorp/packer/pull/4749) PR which resolves [this](https://github.com/hashicorp/packer/issues/4608) issue.
The desired behavior would be to use the input service account and fallback to default if one is not specified. 
[packer.log](https://github.com/hashicorp/packer/files/1677306/packer.log)

**Comment by SwampDragons** [comment]
@pdarvasi I think this patch should fix things for you -- Can you try it out for me?  If you can't build the project, let me know your host machine's architecture and I'll build you a binary.  https://github.com/hashicorp/packer/pull/5897

**Comment by SwampDragons** [comment]
@pdarvasi have you had a chance to test this?  I would like to get the fix into tomorrow's release, but I don't want to merge without confirmation that it works.

**Comment by SwampDragons** [comment]
This should be fixed by the new option added in #5928; can you verify that adding the ServiceAccountEmail field fixes your issue?

**Comment by SwampDragons** [comment]
Closing becuase this should be fixed on master now.
