### ISSUE TITLE
wrong path for VBoxGuestAdditions (virtualbox-ovf) at Windows

### ISSUE THREAD

**Issue by cht47** [hashicorp/packer#5827]
packer version: 1.1.3

Windows 10 Pro 1709 - German Language

Log:
https://gist.github.com/cht47/12fde15f81073e10de468da554b66356

template.json:
`
{
  "builders": [
    {
       "type": "virtualbox-ovf",
        "source_path": "ubuntu1604.ovf",
        "ssh_username": "vagrant",
        "ssh_password": "vagrant",
        "shutdown_command": "echo 'packer' | sudo -S shutdown -P now"
    }
  ]
}
`

Building fails because packer try's to open file://C:/Program%20Files/Oracle/VirtualBox/VBoxGuestAdditions.iso

You can't access program files with C:/Program%20Files/ on Windows. 
only file://C:/Program Files/Oracle/VirtualBox/VBoxGuestAdditions.iso works. 

` virtualbox-ovf: Downloading or copying Guest additions
    virtualbox-ovf: Downloading or copying: file://C:/Program%20Files/Oracle/VirtualBox/VBoxGuestAdditions.iso
    virtualbox-ovf: Error downloading: CreateFile /Program Files/Oracle/VirtualBox/VBoxGuestAdditions.iso: Das System kann den angegebenen Pfad nicht finden.`

**Comment by SwampDragons** [comment]
This should already be fixed -- see https://github.com/hashicorp/packer/pull/5761 for context and for a binary Packer that includes the fix.
