### ISSUE TITLE
File Provisioner fails when using base AMI (created using EC2Config SysPrep)

### ISSUE THREAD

**Issue by ghost** [hashicorp/packer#5844]
File provisioner is not working.  I created a base AMI using EC2Config SysPrep.
_https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/ami-create-standard.html_
I use this as a reference to create the base AMI.  

If I use this newly created AMI as base AMI in packer to create new AMI, file provisioner is not working.

Could anyone figure out the problem behind this issue?

- Packer version - 1.0.4
- Host Platform
  NAME="CentOS Linux"
  VERSION="7 (Core)"
  ID="centos"
  ID_LIKE="rhel fedora"
  VERSION_ID="7"
  PRETTY_NAME="CentOS Linux 7 (Core)"

Packer file and log are attached to this gist: _https://gist.github.com/AakashSelvaraj/3153aab12bd04aca9166de70bb988aa2_

[github.log](https://github.com/hashicorp/packer/files/1692443/github.log)
[githubprob.json.txt](https://github.com/hashicorp/packer/files/1692449/githubprob.json.txt)

**Comment by AakashSelvaraj** [comment]
`==> amazon-ebs: Provisioning with shell script: /tmp/packer-powershell-provisioner983069938
2018/02/03 19:26:28 packer: 2018/02/03 19:26:28 Opening /tmp/packer-powershell-provisioner983069938 for reading
2018/02/03 19:26:28 packer: 2018/02/03 19:26:28 Building command line for: if (Test-Path variable:global:ProgressPreference){$ProgressPreference='SilentlyContinue'};$env:PACKER_BUILDER_TYPE="amazon-ebs"; $env:PACKER_BUILD_NAME="amazon-ebs"; &'c:/Windows/Temp/script.ps1';exit $LastExitCode
2018/02/03 19:26:28 packer: 2018/02/03 19:26:28 [INFO] 47 bytes written for 'uploadData'
2018/02/03 19:26:28 [INFO] 47 bytes written for 'uploadData'
2018/02/03 19:26:28 packer: 2018/02/03 19:26:28 Uploading file to 'c:/Windows/Temp/script.ps1'
2018/02/03 19:26:28 packer: 2018/02/03 19:26:28 [INFO] starting remote command: powershell -executionpolicy bypass -encodedCommand aQBmACAAKABUAGUAcwB0AC0AUABhAHQAaAAgAHYAYQByAGkAYQBiAGwAZQA6AGcAbABvAGIAYQBsADoAUAByAG8AZwByAGUAcwBzAFAAcgBlAGYAZQByAGUAbgBjAGUAKQB7ACQAUAByAG8AZwByAGUAcwBzAFAAcgBlAGYAZQByAGUAbgBjAGUAPQAnAFMAaQBsAGUAbgB0AGwAeQBDAG8AbgB0AGkAbgB1AGUAJwB9ADsAJABlAG4AdgA6AFAAQQBDAEsARQBSAF8AQgBVAEkATABEAEUAUgBfAFQAWQBQAEUAPQAiAGEAbQBhAHoAbwBuAC0AZQBiAHMAIgA7ACAAJABlAG4AdgA6AFAAQQBDAEsARQBSAF8AQgBVAEkATABEAF8ATgBBAE0ARQA9ACIAYQBtAGEAegBvAG4ALQBlAGIAcwAiADsAIAAmACcAYwA6AC8AVwBpAG4AZABvAHcAcwAvAFQAZQBtAHAALwBzAGMAcgBpAHAAdAAuAHAAcwAxACcAOwBlAHgAaQB0ACAAJABMAGEAcwB0AEUAeABpAHQAQwBvAGQAZQA=
2018/02/03 19:26:28 packer: 2018/02/03 19:26:28 [INFO] command 'powershell -executionpolicy bypass -encodedCommand aQBmACAAKABUAGUAcwB0AC0AUABhAHQAaAAgAHYAYQByAGkAYQBiAGwAZQA6AGcAbABvAGIAYQBsADoAUAByAG8AZwByAGUAcwBzAFAAcgBlAGYAZQByAGUAbgBjAGUAKQB7ACQAUAByAG8AZwByAGUAcwBzAFAAcgBlAGYAZQByAGUAbgBjAGUAPQAnAFMAaQBsAGUAbgB0AGwAeQBDAG8AbgB0AGkAbgB1AGUAJwB9ADsAJABlAG4AdgA6AFAAQQBDAEsARQBSAF8AQgBVAEkATABEAEUAUgBfAFQAWQBQAEUAPQAiAGEAbQBhAHoAbwBuAC0AZQBiAHMAIgA7ACAAJABlAG4AdgA6AFAAQQBDAEsARQBSAF8AQgBVAEkATABEAF8ATgBBAE0ARQA9ACIAYQBtAGEAegBvAG4ALQBlAGIAcwAiADsAIAAmACcAYwA6AC8AVwBpAG4AZABvAHcAcwAvAFQAZQBtAHAALwBzAGMAcgBpAHAAdAAuAHAAcwAxACcAOwBlAHgAaQB0ACAAJABMAGEAcwB0AEUAeABpAHQAQwBvAGQAZQA=' exited with code: 0
2018/02/03 19:26:28 packer: 2018/02/03 19:26:28 [INFO] RPC endpoint: Communicator ended with: 0
2018/02/03 19:26:28 [INFO] 0 bytes written for 'stdout'
2018/02/03 19:26:28 [INFO] 0 bytes written for 'stderr'
2018/02/03 19:26:28 [INFO] RPC client: Communicator ended with: 0
2018/02/03 19:26:28 [INFO] RPC endpoint: Communicator ended with: 0
2018/02/03 19:26:28 packer: 2018/02/03 19:26:28 [INFO] 0 bytes written for 'stdout'
2018/02/03 19:26:28 packer: 2018/02/03 19:26:28 [INFO] 0 bytes written for 'stderr'
2018/02/03 19:26:28 packer: 2018/02/03 19:26:28 [INFO] RPC client: Communicator ended with: 0
2018/02/03 19:26:28 [INFO] (telemetry) ending powershell
2018/02/03 19:26:28 [INFO] (telemetry) Starting provisioner file
2018/02/03 19:26:28 ui: ==> amazon-ebs: Uploading userdata.txt => C:/windows/temp/gopi.txt
==> amazon-ebs: Uploading userdata.txt => C:/windows/temp/gopi.txt
2018/02/03 19:26:28 packer: 2018/02/03 19:26:28 [INFO] 4827 bytes written for 'uploadData'
2018/02/03 19:26:28 [INFO] 4827 bytes written for 'uploadData'
2018/02/03 19:26:28 packer: 2018/02/03 19:26:28 Uploading file to 'C:/windows/temp/gopi.txt'
2018/02/03 19:26:28 [INFO] (telemetry) ending file
2018/02/03 19:26:28 [INFO] (telemetry) Starting provisioner file
2018/02/03 19:26:28 ui: ==> amazon-ebs: Downloading C:\windows\temp\gopi.txt => /home/genesys/aakash/packer/project/gopi.txt
==> amazon-ebs: Downloading C:\windows\temp\gopi.txt => /home/genesys/aakash/packer/project/gopi.txt
2018/02/03 19:26:28 [INFO] 0 bytes written for 'downloadWriter'
2018/02/03 19:26:28 packer: 2018/02/03 19:26:28 [INFO] 0 bytes written for 'downloadWriter'
2018/02/03 19:26:28 ui error: ==> amazon-ebs: Download failed: Command has already been closed
==> amazon-ebs: Download failed: Command has already been closed
2018/02/03 19:26:28 [INFO] (telemetry) ending file
2018/02/03 19:26:28 [INFO] (telemetry) found error: Command has already been closed
2018/02/03 19:26:28 ui: ==> amazon-ebs: Terminating the source AWS instance...`

**Comment by AakashSelvaraj** [comment]
`==> amazon-ebs: Provisioning with shell script: /tmp/packer-powershell-provisioner983069938
2018/02/03 19:26:28 packer: 
2018/02/03 19:26:28 Opening /tmp/packer-powershell-provisioner983069938 for reading
2018/02/03 19:26:28 packer: 2018/02/03 19:26:28 Building command line for: if (Test-Path variable:global:ProgressPreference){$ProgressPreference='SilentlyContinue'};$env:PACKER_BUILDER_TYPE="amazon-ebs"; $env:PACKER_BUILD_NAME="amazon-ebs"; &'c:/Windows/Temp/script.ps1';exit $LastExitCode
2018/02/03 19:26:28 packer: 
2018/02/03 19:26:28 [INFO] 47 bytes written for 'uploadData'
2018/02/03 19:26:28 [INFO] 47 bytes written for 'uploadData'
2018/02/03 19:26:28 packer: 2018/02/03 19:26:28 Uploading file to 'c:/Windows/Temp/script.ps1'
2018/02/03 19:26:28 packer: 2018/02/03 19:26:28 [INFO] starting remote command: powershell -executionpolicy bypass -encodedCommand aQBmACAAKABUAGUAcwB0AC0AUABhAHQAaAAgAHYAYQByAGkAYQBiAGwAZQA6AGcAbABvAGIAYQBsADoAUAByAG8AZwByAGUAcwBzAFAAcgBlAGYAZQByAGUAbgBjAGUAKQB7ACQAUAByAG8AZwByAGUAcwBzAFAAcgBlAGYAZQByAGUAbgBjAGUAPQAnAFMAaQBsAGUAbgB0AGwAeQBDAG8AbgB0AGkAbgB1AGUAJwB9ADsAJABlAG4AdgA6AFAAQQBDAEsARQBSAF8AQgBVAEkATABEAEUAUgBfAFQAWQBQAEUAPQAiAGEAbQBhAHoAbwBuAC0AZQBiAHMAIgA7ACAAJABlAG4AdgA6AFAAQQBDAEsARQBSAF8AQgBVAEkATABEAF8ATgBBAE0ARQA9ACIAYQBtAGEAegBvAG4ALQBlAGIAcwAiADsAIAAmACcAYwA6AC8AVwBpAG4AZABvAHcAcwAvAFQAZQBtAHAALwBzAGMAcgBpAHAAdAAuAHAAcwAxACcAOwBlAHgAaQB0ACAAJABMAGEAcwB0AEUAeABpAHQAQwBvAGQAZQA=
2018/02/03 19:26:28 packer: 2018/02/03 19:26:28 [INFO] command 'powershell -executionpolicy bypass -encodedCommand aQBmACAAKABUAGUAcwB0AC0AUABhAHQAaAAgAHYAYQByAGkAYQBiAGwAZQA6AGcAbABvAGIAYQBsADoAUAByAG8AZwByAGUAcwBzAFAAcgBlAGYAZQByAGUAbgBjAGUAKQB7ACQAUAByAG8AZwByAGUAcwBzAFAAcgBlAGYAZQByAGUAbgBjAGUAPQAnAFMAaQBsAGUAbgB0AGwAeQBDAG8AbgB0AGkAbgB1AGUAJwB9ADsAJABlAG4AdgA6AFAAQQBDAEsARQBSAF8AQgBVAEkATABEAEUAUgBfAFQAWQBQAEUAPQAiAGEAbQBhAHoAbwBuAC0AZQBiAHMAIgA7ACAAJABlAG4AdgA6AFAAQQBDAEsARQBSAF8AQgBVAEkATABEAF8ATgBBAE0ARQA9ACIAYQBtAGEAegBvAG4ALQBlAGIAcwAiADsAIAAmACcAYwA6AC8AVwBpAG4AZABvAHcAcwAvAFQAZQBtAHAALwBzAGMAcgBpAHAAdAAuAHAAcwAxACcAOwBlAHgAaQB0ACAAJABMAGEAcwB0AEUAeABpAHQAQwBvAGQAZQA=' exited with code: 0
2018/02/03 19:26:28 packer: 2018/02/03 19:26:28 [INFO] RPC endpoint: Communicator ended with: 0
2018/02/03 19:26:28 [INFO] 0 bytes written for 'stdout'
2018/02/03 19:26:28 [INFO] 0 bytes written for 'stderr'
2018/02/03 19:26:28 [INFO] RPC client: Communicator ended with: 0
2018/02/03 19:26:28 [INFO] RPC endpoint: Communicator ended with: 0
2018/02/03 19:26:28 packer: 2018/02/03 19:26:28 [INFO] 0 bytes written for 'stdout'
2018/02/03 19:26:28 packer: 2018/02/03 19:26:28 [INFO] 0 bytes written for 'stderr'
2018/02/03 19:26:28 packer: 2018/02/03 19:26:28 [INFO] RPC client: Communicator ended with: 0
2018/02/03 19:26:28 [INFO] (telemetry) ending powershell
2018/02/03 19:26:28 [INFO] (telemetry) Starting provisioner file
2018/02/03 19:26:28 ui: ==> amazon-ebs: Uploading userdata.txt => C:/windows/temp/gopi.txt
==> amazon-ebs: Uploading userdata.txt => C:/windows/temp/gopi.txt
2018/02/03 19:26:28 packer: 2018/02/03 19:26:28 [INFO] 4827 bytes written for 'uploadData'
2018/02/03 19:26:28 [INFO] 4827 bytes written for 'uploadData'
2018/02/03 19:26:28 packer: 2018/02/03 19:26:28 Uploading file to 'C:/windows/temp/gopi.txt'
2018/02/03 19:26:28 [INFO] (telemetry) ending file
2018/02/03 19:26:28 [INFO] (telemetry) Starting provisioner file
2018/02/03 19:26:28 ui: ==> amazon-ebs: Downloading C:\windows\temp\gopi.txt => /home/genesys/aakash/packer/project/gopi.txt
==> amazon-ebs: Downloading C:\windows\temp\gopi.txt => /home/genesys/aakash/packer/project/gopi.txt
2018/02/03 19:26:28 [INFO] 0 bytes written for 'downloadWriter'
2018/02/03 19:26:28 packer: 2018/02/03 19:26:28 [INFO] 0 bytes written for 'downloadWriter'
2018/02/03 19:26:28 ui error: ==> amazon-ebs: Download failed: Command has already been closed
==> amazon-ebs: Download failed: Command has already been closed
2018/02/03 19:26:28 [INFO] (telemetry) ending file
2018/02/03 19:26:28 [INFO] (telemetry) found error: Command has already been closed
2018/02/03 19:26:28 ui: ==> amazon-ebs: Terminating the source AWS instance...`

**Comment by SwampDragons** [comment]
Sorry no one ever responded on this. Did you ever figure it out? If I had to guess, I'd say the issue is becasue you're supplying userdata.txt twice, once as the actual user_data_file, and once in a provisioner. Supplying it as the user_data_file means it automatically runs before Packer even connects, so you don't need to run it again as a provisioner. If that file contains a sysprep, or a reboot, it could be that the system is rebooting at the time the provisioner tries to download, and that causes a failure. 

We have known issues with windows reboots causing the communicator to disconnect and fail, which I suspect is what happened here. Since I believe this was more configuration related than a bug with the file provisioner, I am going to close. But I can reopen if you are still facing this problem, or if you have another issue. Thanks!
