### ISSUE TITLE
Enhancement: Select a new VNC port if initial port is busy

### ISSUE THREAD

**Issue by Fanta-astic** [hashicorp/packer#5846]
The use case for this feature request is to better enable parallel Packer builds in on an ESXi hosts. When running an Ansible playbook that attempts to build n guests, all packer build commands are invoked simultaneously and check for an available VNC port (default range 5900 to 6000) at the same time. Because no connections are initiated, all processes select the exact same first available port and attempt to connect. Only one is successful and the rest fail.

This feature request is for some method of selecting and attempting to connect to a new VNC port if the initial connection fails. The error that appears to indicate the failure is:

"2018/02/01 10:53:57 ui: \u001b[1;32m==> vmware-iso: Connecting to VM via VNC\u001b[0m",
"2018/02/01 10:53:57 ui error: \u001b[1;31m==> vmware-iso: Error handshaking with VNC: EOF\u001b[0m",

I have been working around this by using the vnc_port_min values to start different builds at different port values, but this is not adequately scalable.

**Comment by mwhooker** [comment]
makes sense. I think this enhancement has the best chance of being added if it comes from the community. We'll definitely take a look at any PRs that come in for it

**Comment by SwampDragons** [comment]
This would probably have prevented #6505

**Comment by alexfeig** [comment]
+1, I use Ansible to call packer and it would be nice to not have to worry about ports.
