### ISSUE TITLE
Amazon-Chroot builder cannot properly mount EBS volumes on new-gen (c5, m5) HVM instances

### ISSUE THREAD

**Issue by josharrington** [hashicorp/packer#5848]
Version: 1.1.3
Host: Amazon Linux, HVM

The amazon-chroot builder relies on Amazon attaching an EBS volume at the same device endpoint as what is described in the console/api. However, on HVM instances, the two do not match and require additional discovery to have a mapping.

For example, an EBS volume mapped as `/dev/xvda` is enumerated in the OS as `/dev/nvme0n1`. Additional EBS volumes attached to the instance are associated as `/dev/sd*` but still attached as `/dev/nvme*`.

The amazon-chroot builder relies on a direct mapping to mount the newly created EBS volume (ie `/dev/sdg -> /dev/sdg`).  Launching a packer build from this instance fails because of this expectation.

Problem code: https://github.com/hashicorp/packer/blob/master/builder/amazon/chroot/device.go#L15

See here for output: 
https://gist.github.com/JoshArrington/09970427b4bad32d73b3b9bb920fbbe4

**To reproduce**
Launch an Amazon Linux AMI (I used ami-f2d3638a) with HVM (c5.large). 

Notce that from the Amazon console, the EBS volume attached is /dev/xvda. Additional volumes attach as /dev/sd*.

Use the config in the gist above.

**References**
Identifying the appropriate device mapping
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/nvme-ebs-volumes.html

Device naming for HVM instances
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/device_naming.html

**Comment by mwhooker** [comment]
thanks for the report. Would you be able to test a PR if I put one up to fix @JoshArrington?

**Comment by JoshArrington** [comment]
I'd be happy to, @mwhooker

**Comment by lorengordon** [comment]
Might want to clarify the issue title. NVME volumes are not available to all HVM instances, just the newest instance family generations (c5, m5, etc).

**Comment by mwhooker** [comment]
did some investigating and unfortunately the way the builder is written makes it difficult to fix this easily. The builder special cases a lot of things depending on if you're on HVM or not, which blows up the complexity.

for my own notes, we need to attach it as `/dev/sd[f-p]`, but mount it as something like `/dev/nvme2n1p1`

will continue to think about this but I don't think it will be ready for the next release

**Comment by mwhooker** [comment]
at the minimum we should make sure you can manually set the device path, etc

**Comment by JoshArrington** [comment]
Manually specifying it would be very helpful. Thank you for taking a look!

**Comment by majormoses** [comment]
Ya manually specifying would help unblock the short term need and longer term we can look for a better fix.

**Comment by SwampDragons** [comment]
I started looking into this and managed to get a repro case but I won't be able to finish my investigation before the release. I'll prioritize for 1.3.0

**Comment by SwampDragons** [comment]
[packer.zip](https://github.com/hashicorp/packer/files/2029056/packer.zip)

Here's a build of a workaround. It adds a new `nvme_device_path` so that you can tell Packer how to mount the nvme volume.  You must set the mount_path, device_path, nvme_device_path, and the mount_partition.  Example config:

```
{
  "variables": {
    "source_ami": "ami-f63b1193",
    "region" : "us-east-2"
  },
  "builders": [
    {
      "type": "amazon-chroot",
      "region": "{{user `region`}}",
      "source_ami": "{{user `source_ami`}}",
      "ena_support": true,
      "ami_name": "amazon-chroot-test-{{timestamp}}",
      "mount_path": "/mnt/packer-amazon-chroot-volumes/nvme1n1",
      "nvme_device_path": "/dev/nvme1n1p1",
      "device_path": "/dev/sdf",
      "mount_partition": 0
    }
  ],

  "provisioners": [
    {
      "type": "shell",
      "inline": ["echo Test > /tmp/test.txt"]
    }
  ]
}
```

Let me know if this works for you; I'm not sure there's a way to detect the nvme device names, so this may be the best we can do. If anyone comes up with a more elegant solution, I'll gladly accept a PR.

**Comment by SwampDragons** [comment]
NEVERMIND this should do the same thing but is much saner code; test it out instead.  The above config is still relevant: [packer.zip](https://github.com/hashicorp/packer/files/2031935/packer.zip)

**Comment by SwampDragons** [comment]
simpler test for the above build: 
```
{
  "variables": {
    "source_ami": "ami-f63b1193",
    "region" : "us-east-2"
  },
  "builders": [
    {
      "type": "amazon-chroot",
      "region": "{{user `region`}}",
      "source_ami": "{{user `source_ami`}}",
      "ena_support": true,
      "ami_name": "amazon-chroot-test-{{timestamp}}",
      "nvme_device_path": "/dev/nvme1n1p",
      "device_path": "/dev/sdf",
    }
  ],

  "provisioners": [
    {
      "type": "shell",
      "inline": ["echo Test > /tmp/test.txt"]
    }
  ]
}
```
