### ISSUE TITLE
Environment variable injection fails on FreeBSD

### ISSUE THREAD

**Issue by jesse-c** [hashicorp/packer#5850]
- Packer version: 1.1.3
- Host platform: macOS 10.13.3
- Debug log: https://gist.github.com/jesse-c/0ea1f9a289d7ec42e2c9d34e61861344#file-debug-log
- Reproducible steps: https://gist.github.com/jesse-c/0ea1f9a289d7ec42e2c9d34e61861344#file-run-sh

`2018/02/05 22:13:38 ui:     digitalocean: PACKER_BUILDER_TYPE=digitalocean: Command not found.`

If lines 368-373 are commented out in `provisioner/shell/provisioner.go` then it completes successfully. [1]

[1] https://gist.github.com/jesse-c/0ea1f9a289d7ec42e2c9d34e61861344#file-debug-log_no-createflattenedenvvars

**Comment by mwhooker** [comment]
give this a shot and see if it works: https://www.packer.io/docs/provisioners/shell.html#freebsd-example

**Comment by jesse-c** [comment]
That worked! Sorry for missing the obvious documentation. I did have an `exec_command` in my actual template, but not the right one.

Thanks for triaging this so quickly.
