### ISSUE TITLE
Incompatibility between packer and ansible due to key authorization

### ISSUE THREAD

**Issue by mmercer-apixio** [hashicorp/packer#5852]
##### ISSUE TYPE
 - Bug Report
 - Feature Idea

##### COMPONENT NAME
Ansible / group_vars / variables?

##### ANSIBLE VERSION
irrelevant

##### CONFIGURATION
irrelevant

##### OS / ENVIRONMENT
irrelevant

##### SUMMARY
Packer invoking ansible as the provisioner and inheriting group vars with ansible_ssh_private_key can discard the packer key that is required to authenticate, thus making it impossible to connect to the instance

##### STEPS TO REPRODUCE
Install packer
Install ansible
Configure packer to build an amazon image via amazon-ebs with ansible-provisioner and use the ansible_inventory flag with vault-id etc.....

Configure ansible to have an ansible_ssh_private_key value set in group_vars/all

Attempt to run your packer build step

##### EXPECTED RESULTS
Well...  the 'expected' results would be that the group_vars/all *does* take precedence, but that also makes it incompatible with packer entirely

##### ACTUAL RESULTS
group_vars/all inclusion of the ansible_ssh_private_key cancels out the packer inserted 'temporary' key that has been handed off to ansible, and upon cancelling it out, the playbook can no longer be executed

```
PACKER:
==> aws: Executing Ansible: ansible-playbook --extra-vars packer_build_name=aws packer_builder_type=amazon-ebs -i /opt/devops-automation/ansible/inventory/stg/packer-provisioner-ansible152371774 /opt/devops-automation/ansible/playbooks/common.yml --private-key /tmp/ansible-key353609115 --skip-tags=badusers --vault-id=all@/opt/devops-automation/ansible/secure/vault/insecure/all.vault --vault-id=stg@/opt/devops-automation/ansible/secure/vault/insecure/stg.vault -vvvvv

Packer ANSIBLE:
    aws: <127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: centos
    aws: <127.0.0.1> SSH: ansible.cfg set ssh_args: (-o)(ControlMaster=auto)(-o)(ControlPersist=30m)(-o)(ControlPath=/opt/devops-automation/ansible/.cp/%h-%r)
    aws: <127.0.0.1> SSH: ANSIBLE_HOST_KEY_CHECKING/host_key_checking disabled: (-o)(StrictHostKeyChecking=no)
    aws: <127.0.0.1> SSH: ANSIBLE_REMOTE_PORT/remote_port/ansible_port set: (-o)(Port=43069)
    aws: <127.0.0.1> SSH: ANSIBLE_PRIVATE_KEY_FILE/private_key_file/ansible_ssh_private_key_file set: (-o)(IdentityFile="/opt/devops-automation/ansible/secure/ssh_deploy_keys/insecure/deploy_stg_20170612")
    aws: <127.0.0.1> SSH: ansible_password/ansible_ssh_pass not set: (-o)(KbdInteractiveAuthentication=no)(-o)(PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey)(-o)(PasswordAuthentication=no)
    aws: <127.0.0.1> SSH: ANSIBLE_REMOTE_USER/remote_user/ansible_user/user/-u set: (-o)(User=centos)
    aws: <127.0.0.1> SSH: ANSIBLE_TIMEOUT/timeout set: (-o)(ConnectTimeout=10)
    aws: <127.0.0.1> SSH: EXEC ssh -vvv -o ControlMaster=auto -o ControlPersist=30m -o ControlPath=/opt/devops-automation/ansible/.cp/%h-%r -o StrictHostKeyChecking=no -o Port=43069 -o 'IdentityFile="/opt/devops-automation/ansible/secure/ssh_deploy_keys/insecure/deploy_stg_20170612"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=centos -o ConnectTimeout=10 127.0.0.1 '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-yfjivdywhekrvfimwzscznajcocxoclw; /usr/bin/python'"'"'"'"'"'"'"'"' && sleep 0'"'"''
==> aws: failed to handshake

```

This ticket has been posted on ansible as well, as might be a good idea to get some cross communication going so that any solution implemented works for *both* sides, not just one.  Reference issue:  https://github.com/ansible/ansible/issues/35757

**Comment by mmercer-apixio** [comment]
Unfortunately, I have tried a few solutions, none of which work --

Attempted to use the 'file' provisioner to upload the public key to the user expecting auth, but I still see the handshake error... as I would imagine that during this process, the actual key being listened for is normally the one that packer creates and attempts to hand off.

Spoke with several of the guys from ansible, and they suggested setting it to an 'empty', which should allow me to get past the issue... and it kind of does:

```
PACKER invocation:
==> aws: Executing Ansible: ansible-playbook --extra-vars packer_build_name=aws packer_builder_type=amazon-ebs -i /opt/devops-automation/ansible/inventory/stg/packer-provisioner-ansible161448171 /opt/devops-automation/ansible/playbooks/common.yml --private-key /tmp/ansible-key010481852 --skip-tags=badusers --vault-id=all@/opt/devops-automation/ansible/secure/vault/insecure/all.vault --vault-id=stg@/opt/devops-automation/ansible/secure/vault/insecure/stg.vault -e ansible_ssh_private_key_file='' -vvvvv


ANSIBLE invocation:
    aws: <127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: centos
    aws: <127.0.0.1> SSH: ansible.cfg set ssh_args: (-o)(ControlMaster=auto)(-o)(ControlPersist=30m)(-o)(ControlPath=/opt/devops-automation/ansible/.cp/%h-%r)
    aws: <127.0.0.1> SSH: ANSIBLE_HOST_KEY_CHECKING/host_key_checking disabled: (-o)(StrictHostKeyChecking=no)
    aws: <127.0.0.1> SSH: ANSIBLE_REMOTE_PORT/remote_port/ansible_port set: (-o)(Port=43877)
    aws: <127.0.0.1> SSH: ansible_password/ansible_ssh_pass not set: (-o)(KbdInteractiveAuthentication=no)(-o)(PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey)(-o)(PasswordAuthentication=no)
    aws: <127.0.0.1> SSH: ANSIBLE_REMOTE_USER/remote_user/ansible_user/user/-u set: (-o)(User=centos)
    aws: <127.0.0.1> SSH: ANSIBLE_TIMEOUT/timeout set: (-o)(ConnectTimeout=10)
    aws: <127.0.0.1> SSH: EXEC ssh -vvv -o ControlMaster=auto -o ControlPersist=30m -o ControlPath=/opt/devops-automation/ansible/.cp/%h-%r -o StrictHostKeyChecking=no -o Port=43877 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=centos -o ConnectTimeout=10 127.0.0.1 '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-mftyzlefwuwzvhghdvvqoxdgikwpbbyx; /usr/bin/python'"'"'"'"'"'"'"'"' && sleep 0'"'"''
==> aws: failed to handshake
```

Notice there is *no* key being handed... now unfortunately, in this case, its setting no key at all, which is again not what we want.... we have to keep the key that packer wants *exclusively*, since packer forces the proxy, and the proxy listens only with the key it creates....

**Comment by mmercer-apixio** [comment]
So far, the only idea i have is to be able to tell the proxy handler what public key to use to listen so that when the execution is established, the expected key can be controlled.  Otherwise, you force users to disable dynamically allocating their keys and require them to set them... which seems like a very BAD thing, since packer should not control the the behavior  of anything beyond itself.

Unfortunately, in our environment, this is literally a breaking issue... I *have* to disable the variables in order to use packer to build our images, then go back in and re-enable them when the images are built so that the rest of the things work... and hope that none of our builds trigger while i have them disabled, or those builds will fail since we don't specify the key for every possibility since they can/should be dynamically included.

**Comment by mmercer-apixio** [comment]
To clarify the setup, this might make it a bit easier to see what is going on:

```
<ansible-directory> /
    <inventory> /
        <stg> /
            ec2.py
            ec2.ini <--- set a unique vpc here
            group_vars/
                all/
                    common.yml -- include ansible_ssh_private_key in here           
```

Here is the relevant ansible part of the configuration file:

```
    {
      "type": "ansible",
      "pause_before": "60s",
      "user": "centos",
      "sftp_command": "{{user `sftp_path`}}/sftp-server -e",
      "playbook_file": "{{user `pb_path`}}/common.yml",
      "inventory_directory": "{{user `ans_path`}}/inventory/{{user `datacenter`}}",
      "groups": [
        "all"
      ],
      "extra_arguments": [
        "--skip-tags=badusers",
        "--vault-id=all@{{user `ans_path`}}/secure/vault/insecure/all.vault",
        "--vault-id={{user `datacenter`}}@{{user `ans_path`}}/secure/vault/insecure/{{user `datacenter`}}.vault",
        "-e ansible_ssh_private_key_file=''",
        "-vvvvv"
      ]
    }
```

With the -e ansible_ssh_private_key_file, we explicitly disable the the group var being used later, however, this unfortunately seems to set the private key to null too.  Perhaps a way of a.) providing a 'serve the proxy with *this* public key'  or b.) 'give the private key file we plan to connect a variable that you can pass to ansible via -e 'ansible_ssh_private_key={{ packer_ssh_key }}' would suffice -- not sure the difficulty of either of these

**Comment by maxamillion** [comment]
CC @thaumos
