### ISSUE TITLE
Feature request: min_cpu_platform in Google Cloud provisioner

### ISSUE THREAD

**Issue by nodesocket** [hashicorp/packer#5853]
Feature request to support `min_cpu_platform` in Google Cloud provisioner. 

> Specifies a minimum CPU platform for the VM instance. Applicable values are the friendly names of CPU platforms, such as Intel Haswell or Intel Skylake.

By default GCE uses older Intel Sandy Bridge.

**Comment by seanmalloy** [comment]
@nodesocket is this what you are referring to?

https://cloud.google.com/compute/docs/instances/specify-min-cpu-platform

**Comment by nodesocket** [comment]
👍 on this. Currently defaults to oldest Sandy Bridge Intels.

**Comment by shubheksha** [comment]
@nodesocket, I believe this will just be an additional attribute in the [`InstanceConfig`](https://github.com/hashicorp/packer/blob/master/builder/googlecompute/driver.go#L60)?

**Comment by azr** [comment]
starting on this one today 🙂

**Comment by SwampDragons** [comment]
@nodesocket Can you test out the PR linked above?

**Comment by nodesocket** [comment]
@SwampDragons thanks for implementing this. I am totally swamped _(excuse the pun)_, but at quick glance looks good.
