### ISSUE TITLE
Want to create azure windows10 OS image, but cannot run scripts because of executionPolicy limitation.

### ISSUE THREAD

**Issue by HuihaoLiao** [hashicorp/packer#5854]
Hi All,
I want to create image in azure, and the OS is windows10, also I want to invoke some scripts. The packerVersion is 0.10.1
The following is a snipping of my template.json file.
![image](https://user-images.githubusercontent.com/13551906/35850848-1a518072-0b61-11e8-805c-a49750345f1a.png)

But the packer log shows that the script cannot be loaded because of executionPolicy limitation.
![image](https://user-images.githubusercontent.com/13551906/35851008-9b90fd16-0b61-11e8-92c9-dcae9b0af300.png)

If anyone know if we can just add some parameters to powershell provisioners in template.json file, or added some other provisioners, thus the scripts can run in azure window10 OS.
I'm a newer to packer, and I already tried to add execute_command, but it not work. Really need your help if you have solution. Thanks in advance.

**Comment by boumenot** [comment]
Please reserve GitHub for issues in Packer or its components.  This appears to a configuration issue with the image not Packer.  Please work the [community](https://www.packer.io/community.html) on these types of issues.
