### ISSUE TITLE
Unable to use vmware builders

### ISSUE THREAD

**Issue by subbu05** [hashicorp/packer#5855]
packer version
Packer v1.1.1

17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

VMWare fusion - 10.1.1

packer build  vmware.json

vmware-iso output will be in this color.

==> vmware-iso: Downloading or copying ISO
    vmware-iso: Downloading or copying: https://test.com/alpine-standard-3.6.2-x86_64.iso
==> vmware-iso: Creating virtual machine disk
==> vmware-iso: Building and writing VMX file
==> vmware-iso: Starting HTTP server on port 8111
==> vmware-iso: Starting virtual machine...
==> vmware-iso: Error starting VM: VMware error: Error: Unknown error
==> vmware-iso:
==> vmware-iso: Packer detected a VMware 'Unknown Error'. Unfortunately VMware
==> vmware-iso: often has extremely vague error messages such as this and Packer
==> vmware-iso: itself can't do much about that. Please check the vmware.log files
==> vmware-iso: created by VMware when a VM is started (in the directory of the
==> vmware-iso: vmx file), which often contains more detailed error information.
==> vmware-iso: Deleting output directory...
Build 'vmware-iso' errored: Error starting VM: VMware error: Error: Unknown error

Packer detected a VMware 'Unknown Error'. Unfortunately VMware
often has extremely vague error messages such as this and Packer
itself can't do much about that. Please check the vmware.log files
created by VMware when a VM is started (in the directory of the
vmx file), which often contains more detailed error information.

==> Some builds didn't complete successfully and had errors:
--> vmware-iso: Error starting VM: VMware error: Error: Unknown error

Packer detected a VMware 'Unknown Error'. Unfortunately VMware
often has extremely vague error messages such as this and Packer
itself can't do much about that. Please check the vmware.log files
created by VMware when a VM is started (in the directory of the
vmx file), which often contains more detailed error information.

==> Builds finished but no artifacts were created.

**Comment by mwhooker** [comment]
have you checked the vmware logs? I'm afraid there's not much to go n here

**Comment by subbu05** [comment]
Fixed the issue. Issue was with ISO.
