### ISSUE TITLE
Feature request - Oracle OCI build support GetWindowsInstanceInitialCredentials

### ISSUE THREAD

**Issue by Marcus-James-Adams** [hashicorp/packer#5871]
Similar to packer/builder/amazon/common/step_get_password.go

Oracle has https://docs.us-phoenix-1.oraclecloud.com/api/#/en/iaas/20160918/InstanceCredentials/GetWindowsInstanceInitialCredentials that is used when windows instances are created using the master oracle ISO's

Having the ability to get this password and return it as a variable would enable automation to be made using master oracle iso's and not have a manual create initial image step

**Comment by SwampDragons** [comment]
I've added this feature in 6303, but I think we still need to figure out how to actually get winrm to launch on these instances.
