### ISSUE TITLE
Exception when loading packer-provisioner-shell during `packer build`

### ISSUE THREAD

**Issue by mbrgm** [hashicorp/packer#5877]
I have a strange problem running packer on a colleague's machine, where loading the `packer-provisioner-shell` plugin causes an exception without any error output. This happens right at the beginning of `packer build`, according to the log file. Unfortunately, I cannot reproduce the error on my own machine, so I'm hoping someone can see a possible cause from the log file or give me further debugging instructions.

- Packer version: 1.1.2, 1.1.3, also tried with 1.1.4-dev (g8510f072a)
- Host platform: Windows 10 x64
- Debug log: https://gist.github.com/e54fa22d39a7eea96d23b527307982a6
- I added the packer.json to the gist, but did not include the scripts, as the builder does not even start. Tell me if I should add them as well.

**Comment by mwhooker** [comment]
this is pretty odd. I think this is related to https://github.com/golang/go/issues/22149

Could you please update to the latest go release and recompile? packer <= 1.1.3 was compiled with go 1.9 and after a brief glance at the issue I think this is solved in go 1.9.2

**Comment by mbrgm** [comment]
@mwhooker We checked with the 1.2.0 release and the crash did not happen, so that seemed to solve the problem. Thank you!

**Comment by mwhooker** [comment]
great! packer 1.2.0 was compiled with go 1.9.4, so looks like it probably was related to that
