### ISSUE TITLE
Windows Powershell env vars for inline scripts are double-escaped in v1.2.0

### ISSUE THREAD

**Issue by SwampDragons** [hashicorp/packer#5881]
repro:
```    
{ "type": "powershell",
      "environment_vars": [
        "DOLLAR=dollar$",
        "BACKTICK=backtick`",
        "SGLQUOTE=sglquote'"
      ],
      "inline": [
        "write-output \"Env var with dollar sign: $env:DOLLAR\"",
        "write-output \"Env var with backtick sign: $env:BACKTICK\"",
        "write-output \"Env var with single quote: $env:SGLQUOTE\""
      ]
    }
```
relevant output: 
```
2018/02/09 16:28:36 ui:     amazon-ebs: Env var with dollar sign: dollar`$
    amazon-ebs: Env var with dollar sign: dollar`$
2018/02/09 16:28:36 ui:     amazon-ebs: Env var with backtick sign: backtick``
    amazon-ebs: Env var with backtick sign: backtick``
2018/02/09 16:28:36 ui:     amazon-ebs: Env var with single quote: sglquote`'
    amazon-ebs: Env var with single quote: sglquote`'
```

When I tested this initially, I thought "yup, looks nice and escaped" -- but the escapes shouldn't make it into the printed variables.  Which means I think we're doubling up somewhere.  Of course I didn't notice this until two minutes _after_ we uploaded the newly cut 1.2.0 binaries. cc @DanHam

**Comment by SwampDragons** [comment]
Oh jeez. Blame it on a long week and a toddler having sleep regressions. This is totally the expected behavior. ![facepalm.](https://media.giphy.com/media/vwI4mYEHP8k0w/giphy.gif)

**Comment by DanHam** [comment]
@SwampDragons I've often found sleep deprivation and a long week of work will do the strangest things! 😄. On the bright side... Fozzie Bear!!! That took me way back! Wocka Wocka Wocka!!!!
