### ISSUE TITLE
Not found any reference json for creating Unmanaged image for Azure using packer

### ISSUE THREAD

**Issue by TechnicalVegeta** [hashicorp/packer#5884]
_Please read these instructions before submitting_

**DELETE THIS TEMPLATE BEFORE SUBMITTING**

_Only use Github issues to report bugs or feature requests, see
https://www.packer.io/community.html_

For example, _Timeouts waiting for SSH/WinRM_ are generally not bugs within packer and are better addressed by the mailing list. Ask on the mailing list if you are unsure.

If you are planning to open a pull-request just open the pull-request instead of making an issue first.

FOR FEATURES:

Describe the feature you want and your use case _clearly_.

FOR BUGS:

Describe the problem and include the following information:

- Packer version from `packer version`
- Host platform
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a gist https://gist.github.com
- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your gist https://gist.github.com

**Comment by boumenot** [comment]
You filled in no bug details, and only have a title.  Your question does not appear to be a bug against Packer either in which case this is not the appropriate forum.  Please see the Packer [community](https://www.packer.io/community.html) for question like this, or search previous discussions.
