### ISSUE TITLE
ansible-local - error on default "--exta-vars"

### ISSUE THREAD

**Issue by FlorianSchimmer** [hashicorp/packer#5885]
Hello, 

i'm using packer to build a ubuntu virtual-box vm with ansible provisioner.

packer version: 1.2.0
host: ubuntu 16.04

There is an error with the default "--extra-vars". packer tries to execute the following command to setup the machine: 

```
ANSIBLE_FORCE_COLOR=1 PYTHONUNBUFFERED=1 ansible-playbook /tmp/packer-provisioner-ansible-local/5a803993-dd42-0ea3-910d-487a50e8c92b/main.yml --extra-vars \"packer_build_name=virtualbox-iso packer_builder_type=virtualbox-iso packer_http_addr=10.0.2.2:8267\"  -c local -i /tmp/packer-provisioner-ansible-local/5a803993-dd42-0ea3-910d-487a50e8c92b/packer-provisioner-ansible-local281821604
```
ansible produces following error:  

```ERROR! the playbook: packer_builder_type=virtualbox-iso could not be found```

Thats because of the two `\` after `--extra-vars`. The bug is caused by this bugfix: #5703

I'm using following provisioner-config:  

```
{
      "type": "ansible-local",
      "playbook_file": "ansible/main.yml",
      "galaxy_file": "requirements.yml"
}
```

**Comment by rickard-von-essen** [comment]
Please supply the information requested in the issue template:
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a [gist](https://gist.github.com).
- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your [gist](https://gist.github.com).

**Comment by FlorianSchimmer** [comment]
https://gist.github.com/FlorianSchimmer/f67f6dc2ae8716b9de24d9e3ccbcea49

**Comment by stevenscg** [comment]
@FlorianSchimmer @rickard-von-essen I am seeing this error as well on:

packer version: 1.2.0
host: Darwin 17.4.0

**Comment by durmaze** [comment]
same here w/ packer version 1.2.0. downgraded to version 1.1.3, and it works.

host: Darwin 17.4.0

**Comment by rickard-von-essen** [comment]
Could we get a debug log, please.

**Comment by FlorianSchimmer** [comment]
for logs look at packer.sh in my gist. (Sorry for the bad name)

**Comment by durmaze** [comment]
i created a gist for the debug log and packer template

https://gist.github.com/durmaze/f0c8f5044986d1134ccfa083cb96128b

**Comment by roman-cnd** [comment]
updating 1.1.2 is getting delayed again 😃

**Comment by SwampDragons** [comment]
Can I get some confirmation from people affected by this bug that reverting #5703 solves the issue?

You can find a PR containing that revert here: https://github.com/hashicorp/packer/pull/5888

**Comment by durmaze** [comment]
it solved the issue in my packer build 👍 @SwampDragons 

**I used the below commit:**
`admins-MacBook-Pro:packer erkand$ git log -1 --pretty=oneline --stat`
`7d9a86becb0d4790ce4cd10ecd6eb7c3f059db89 (HEAD -> revert-5703-5335, origin/revert-5703-5335) Revert "Fix #5335"`
 `provisioner/ansible-local/provisioner.go | 2 +-`
 `1 file changed, 1 insertion(+), 1 deletion(-)`

`admins-MacBook-Pro:packer erkand$ packer --version`
`1.2.1`

**Comment by SwampDragons** [comment]
Good enough for me! We're going to gather up a few of the most pressing 1.2.0 issues and do a quick-turnaround patch release for 1.2.1, so you shouldn't have long to wait for this to be released officially.

**Comment by tamsky** [comment]
breadcrumb for future travelers: #6493
