### ISSUE TITLE
Error: ExtraConfig options exists in source (use --allowExtraConfig option to allow this)

### ISSUE THREAD

**Issue by stevetavve** [hashicorp/packer#5886]
Getting this error when I add "format": "ova" to builders.

ln issue https://github.com/hashicorp/packer/issues/5771, the thread asks for a simple repro case. I am running into 100% of the time when I add "format". Posted to the packer community and was instructed to open a new issue referencing 5771.

Without format option, the build is successful.

packer version is 1.1.3
ovftool version is 4.2.0
Host platform is centos-release-7-2.1511.el7.centos.2.10.x86_64
VMware vCenter is 6.5.0 Update 1 (Build 6765664)

Associated files: json, ks file, packer log output
https://gist.github.com/stevetavve/823aaeee8911994fdf20df2bcc86d945

**Comment by SwampDragons** [comment]
I get a 404 when I try to view the files in your gist.

**Comment by stevetavve** [comment]
Fixed the link the glist. It didn't like being in a []url link so I just replaced with the direct url to the glist. The link works for me now.

**Comment by SwampDragons** [comment]
So to clarify, the build is successful if you remove `"format": "ova",` from your test.json?

**Comment by stevetavve** [comment]
Yes, if I remove "format": "ova" from the test.json file, the build is successful. I have added a file packer.out.noformatova to the glist showing a successful build with this one single change to the json file.

**Comment by SwampDragons** [comment]
After the Packer run, are you able to manually run the ovftool command to convert the vmx to an ova?

**Comment by stevetavve** [comment]
Yes. I can run 

ovftool -tt=ova --skipManifestCheck ZoneRanger.vmx ZoneRanger.ova

And convert to an ova.

My current build process does this everyday, adding eula and vApp metadata. Here is the part of the script that am I running:

while [ TRUE ]; do

    # Build the VM using packer on the ESX server
    # You can monitor the build by opening a console on the VM zr60VM on the ESX server
    # ZoneRanger will usually be orphaned but during the build it will not be
    # Refresh the view until you ZoneRanger not orphaned

    PACKER_LOG=1 /usr/local/bin/packer build $ZRJSON
    if [ $? -ne 0 ]; then
        echo "VM build failed: Packer failed to build the VM"
        success=FALSE
        break
    fi

    # Give time for the VM to completely shutdown
    sleep 60
                                                                                                                                                                                                                    
    # Copy the VM files from the ESX server to the local ZoneRanger directory for conversion to an ova file                                                                                                             
    sshpass -p xxxxxxx scp root@emtesx:/vmfs/volumes/Datastore2/$VMDIR/* $VMDIR/                                                                                                                              
    if [ 0 -ne 0 ]; then
        echo "VM build failed: Could not copy the VM files from the ESX server to the local machine"                                                                                                    
        success=FALSE
        break
    fi

    # Remove the ZoneRanger from the ESX datasource. The target directory cannot exist when the packer starts
    sshpass -p xxxxxxx ssh root@emtesx 'rm -rf /vmfs/volumes/Datastore2/'"$VMDIR"''
    if [ $? -ne 0 ]; then
        echo "VM build failed: Failed to remove the $VMDIR directory on the ESX server which should never fail"
        success=FALSE
        break
    fi

    # Convert the ESX vmx file to an ovf file so the Product, Version, Vendor, etc can be added
    ovftool -tt=ovf --eula@=/opt/IBM/cmdBuild/workspace/enms/ranger_license.txt $VMDIR/$VMDIR.vmx $VMDIR/$VMDIR_ovf
    if [ $? -ne 0 ]; then
        echo "VM build failed: Failed to convert the $VMDIR vmx to an ovf file"
        success=FALSE
        break
    fi

    # Insert the vAppSettings.txt file into the ovf file just created
    sed -n -i -e '/  <\/VirtualSystem>/r /opt/IBM/cmdBuild/workspace/ranger/nightly_builds/vAppSettings.txt' -e 1x -e '2,${x;p}' -e '${x;p}' $VMDIR/$VMDIR_ovf/$VMDIR/$VMDIR.ovf

    # Convert the ovf file just created to an ova file after adding in the Product, Version, Vendor, etc. info
    ovftool -tt=ova --skipManifestCheck $VMDIR/$VMDIR_ovf/$VMDIR/$VMDIR.ovf $VMDIR/
    if [ $? -ne 0 ]; then
        echo "VM build failed: Failed to convert the $VMDIR vmx to an ova file"
        success=FALSE
        break
    fi

    # If everything worked, copy the file ova file to the distribution directory with the other build artifacts
    echo "copying ova file ..."
    chmod +r $VMDIR/$VMDIR.ova
    cp $VMDIR/$VMDIR.ova $TAROUTPUT/$timestamp/$VMDIR-${FULLVERSION}${SUFFIX}.ova

    break
done

**Comment by SwampDragons** [comment]
Hmm... I just noticed in your logs `Error: File already exists: ZoneRanger/ZoneRanger.ova` -- the issue isn't that the --allowExtraConfig flag is failing, it's that the destination already exists.  Delete or move ZoneRanger/ZoneRanger.ova and try again?

**Comment by stevetavve** [comment]
Before I do the build I remove everything in the ZoneRanger directory and then do the build. Without the "format": "ova" option in the son, there is no ZoneRanger.ova file in the directory. Somehow, ZoneRanger.ova is being created by packer before the ovftool is run. I am not creating it.

**Comment by stevetavve** [comment]
The -force option had no effect.

I only get that error when I add "ovftool_options": "--allowExtraConfig" to the json file. 

To summarize, without 

      "format": "ova",
      "ovftool_options": "--allowExtraConfig",

the build works.

With 

      "format": "ova",

I get the error

==> vmware-iso: Exporting virtual machine...
2018/02/08 13:47:08 ui:     vmware-iso: Executing: ovftool --noSSLVerify=true --skipManifestCheck -tt=ova vi://root:****@emtesx/ZoneRanger ZoneRanger
    vmware-iso: Executing: ovftool --noSSLVerify=true --skipManifestCheck -tt=ova vi://root:****@emtesx/ZoneRanger ZoneRanger
2018/02/08 13:47:09 ui error: ==> vmware-iso: Error exporting virtual machine: exit status 1
==> vmware-iso: Opening VI source: vi://root@10.254.1.32:443/ZoneRanger
==> vmware-iso: Error: ExtraConfig options exists in source (use --allowExtraConfig option to allow this).
==> vmware-iso: Warning:
==> vmware-iso:  - ExtraConfig option 'virtualhw.productcompatibility' is not allowed, will skip it.
==> vmware-iso: Completed with errors

With

      "format": "ova",
      "ovftool_options": "--allowExtraConfig",

I get 

2018/02/15 17:17:46 ui: ==> vmware-iso: Exporting virtual machine...
==> vmware-iso: Exporting virtual machine...
2018/02/15 17:17:46 ui:     vmware-iso: Executing: ovftool --allowExtraConfig --noSSLVerify=true --skipManifestCheck -tt=ova vi://root:****@emtesx/ZoneRanger ZoneRanger
    vmware-iso: Executing: ovftool --allowExtraConfig --noSSLVerify=true --skipManifestCheck -tt=ova vi://root:****@emtesx/ZoneRanger ZoneRanger
2018/02/15 17:17:52 ui error: ==> vmware-iso: Error exporting virtual machine: exit status 1
==> vmware-iso: Opening VI source: vi://root@10.254.1.32:443/ZoneRanger
==> vmware-iso: Opening OVA target: ZoneRanger
==> vmware-iso: Error: File already exists: ZoneRanger/ZoneRanger.ova
==> vmware-iso: Warning:
==> vmware-iso:  - ExtraConfig option 'virtualhw.productcompatibility' is not allowed, will skip it.
==> vmware-iso:  - ExtraConfig options exists in source.
==> vmware-iso: Completed with errors

I have no idea why it is says ZoneRanger.ova already exists. I monitored the directory on the ems server during the build doing an "ls -al" every second. When it gets to this point, there is definitely no ZoneRanger.ova file. These are the artifacts just before and after ovftool is started:

drwxr-xr-x    1 root     root          1680 Feb 15 22:28 .
drwxr-xr-t    1 root     root         14560 Feb 15 22:26 ..
-rw-------    1 root     root     1073741824 Feb 15 22:27 ZoneRanger-87c40dc2.vswp
-rw-------    1 root     root          8684 Feb 15 22:28 ZoneRanger.nvram
-rw-r--r--    1 root     root             0 Feb 15 22:27 ZoneRanger.vmsd
-rw-r--r--    1 root     root          2961 Feb 15 22:27 ZoneRanger.vmx
-rw-------    1 root     root             0 Feb 15 22:27 ZoneRanger.vmx.lck
-rw-r--r--    1 root     root          2901 Feb 15 22:27 ZoneRanger.vmx~
-rw-------    1 root     root     34359738368 Feb 15 22:33 disk-flat.vmdk
-rw-------    1 root     root           466 Feb 15 22:28 disk.vmdk
-rw-r--r--    1 root     root        194915 Feb 15 22:32 vmware.log
-rw-------    1 root     root     115343360 Feb 15 22:27 vmx-ZoneRanger-2277772738-1.vswp
total 33557520
drwxr-xr-x    1 root     root          1120 Feb 15 22:33 .
drwxr-xr-t    1 root     root         14560 Feb 15 22:26 ..
-rw-------    1 root     root          8684 Feb 15 22:33 ZoneRanger.nvram
-rw-r--r--    1 root     root             0 Feb 15 22:27 ZoneRanger.vmsd
-rw-r--r--    1 root     root          2959 Feb 15 22:33 ZoneRanger.vmx
-rw-------    1 root     root     34359738368 Feb 15 22:33 disk-flat.vmdk
-rw-------    1 root     root           466 Feb 15 22:28 disk.vmdk
-rw-r--r--    1 root     root        221019 Feb 15 22:33 vmware.log
total 33557520

**Comment by hmalinov** [comment]
I had a similar issue and the problem was not with the `packer` itself but with `ovftool`.

Version 4.2.0 of ovftool has different build numbers and for me with version VMware-ovftool-4.2.0-5965791-lin.x86_64.bundle there is no problems
