### ISSUE TITLE
Feature Request: aws-ebs builder dynamic subnet_id

### ISSUE THREAD

**Issue by salvianreynaldi** [hashicorp/packer#5889]
I want Packer to choose a subnet_id randomly from a list of subnet_ids, e.g.

```javascript
"variables": {
aws_subnet_ids = "subnet-01234567,subnet-abcdefab,subnet-1a2b3c4d"
}
"builders": [{
"subnet_id": // I want Packer to get either subnet-01234567, subnet-abcdefab, or subnet-1a2b3c4d
}]
```
the purpose is trying to "balance" the load (of builder instances creation) into multiple AZs

Thanks!

**Comment by SwampDragons** [comment]
This is a valid desire but I think it's outside Packer's scope. If you want to chose randomly from a set of `subnet_ids`, this could be achieved by wrapping Packer in a shell script that does the choosing and sets your desired `subnet_id` for each build in the call to Packer.
