### ISSUE TITLE
Error creating image with new builder for oracle classic

### ISSUE THREAD

**Issue by herasimau** [hashicorp/packer#5892]
Hello, after start packer build with new builder for oracle classic, it's fails with this error:

`==> centos-6-opc: Problem creating instance: Error deleting instance /Compute-domain/user/: 400: {"message": "Bad Request"}
`
`Error deleting the packer-generated security list /Compute-domain/user/Packer_SSH_Allow_; please delete manually. (error : 400: {"message": "Cannot delete seclist /Compute-domain/user/Packer_SSH_Allow_ because there are secrules associated with it or VMs using it."})`

**Comment by SwampDragons** [comment]
Thanks for reporting -- can you please share your packer config and host machine?

**Comment by herasimau** [comment]
```
    {
      "name": "centos-6-opc",
      "type": "oracle-classic",
      "communicator": "ssh",
      "api_endpoint": "my_endpoint",
      "dest_image_list": "/Compute-domain/user@domain/Packer_Test_Build",
      "identity_domain": "herasimau",
      "source_image_list": "/Compute-domain/user@domain/CentOS6-Cloud",
      "shape": "oc3",
      "password": "user",
      "username": "password"
    }
```

**Comment by SwampDragons** [comment]
Can I have your full debug logs please?  I can't reproduce this error.

**Comment by herasimau** [comment]
Sure, `https://gist.github.com/herasimau/5f7aef29c2fb157ce5e8a9926b5b6c50`

**Comment by herasimau** [comment]
I have removed "communicator":"ssh" from configuration and put "ssh_username":"opc" instead.
Now it's works, you can close the issue.

**Comment by rickard-von-essen** [comment]
Thanks for reporting back.

**Comment by SwampDragons** [comment]
Yes, thanks for checking back in with us, and I'm glad it's working. I'll review the docs to see if they can be clarified WRT the default user.
