### ISSUE TITLE
metadata.json contains vmware_desktop instead of vmware_fusion

### ISSUE THREAD

**Issue by Sauraus** [hashicorp/packer#5896]
Version: 1.2.0
Platform: OS X 10.12.6

Using the templates found here https://github.com/boxcutter/windows a vmware box built on OSX will have `{"provider":"vmware_desktop"}` in its metadata.json instead of `vmware_fusion` which makes vagrant barf when you try to bring up the box with `vmware_fusion` as the provider.

It appears `provider` is hardcoded to be `vmware_desktop` irrespective of the platform on which the vmware box was built here https://github.com/hashicorp/packer/blob/ebe995c0ff49d479f41b60f977af724eee54690e/post-processor/vagrant/vmware.go#L18

**Comment by AntonioMeireles** [comment]
(hey all) any news on this ?

**Comment by SwampDragons** [comment]
Not yet; we will update the ticket when there are updates.

**Comment by Sauraus** [comment]
@SwampDragons would you accept a PR to fix this? And would a simple OS check to determine the provider be sufficient in this case?

**Comment by mwhooker** [comment]
Hi @Sauraus,

I just talked to the vagrant team and `vmware_desktop` is what you want, since that will choose the correct vmware provider. If you're still not able to get vagrant to work, that might be an issue with vagrant, and in that case I would recommend you open a ticket over there with the debug log of it "barfing".

**Comment by Sauraus** [comment]
@mwhooker are you saying the error is on the vagrant side for not translating `vmware_desktop` to mean `vmware_fusion` on OSX?

**Comment by mwhooker** [comment]
yeah, I think that's what's going on. It could also be how you're invoking it, but I have to admit I'm not super familiar with that aspect
