### ISSUE TITLE
Improved the download progress bar. This supercedes the PercentProgress functionality.

### ISSUE THREAD

**Issue by arizvisa** [hashicorp/packer#5903]
Implemented by PR #5851.

This was based on PR #2906 and so had to be delayed until that was merged upstream.

This adds a progress-bar to step_download.go using the progressbar implementation at http://github.com/cheggaaa/pb that was suggested on an earlier issue.

The progress-bar's appearance was consolidated into a function so that it can be changed to look however you guys want. It's currently been specified to provide the same information as the previous download ticker as well as including the number of b/mb/gb that have been xferred.

This also removes the previous PercentProgress ticker as it's been superceded by this progressbar implementation.

**Comment by SwampDragons** [comment]
Linked Pr was merged; I'm closing this 😄
