### ISSUE TITLE
Packer crashed after upgrading from packer 0.10.1 using remote vmware-iso builder

### ISSUE THREAD

**Issue by BeverlyBrown** [hashicorp/packer#5904]
I just tried upgrading from packer 0.10.1 to 1.2.0 and packer crashed. 
I did try running packer fix on my json file and got the same result.
I uploaded the crash.log file

Packer Version: Packer v1.2.0
Host platform: CentOS 7.4 64-bit 
Builder: vmware-iso (remote)

[crash.log](https://github.com/hashicorp/packer/files/1725890/crash.log)
I put the template here: https://gist.github.com/BeverlyBrown/810e27ab4daa48497015f6adacac78cc

I used this command line (note that I replaced actual host and pathnames  with "host" and "path"):
./packer build -color=false \
?         -var 'vm_name=packer.23549' \
?         -var 'remote_host=remote-host-for-packer' \
?         -var 'remote_cert=/path/Packer.cert' \
?         -var 'datastore=datastore-packer-65' \
?         -var 'iso_url=/path/CentOS-7-x86_64-Everything-1708.iso' \
?         -var 'iso_checksum_url=http://host/path/sha256sum.txt' \
?         -var 'ks_url=http://host/path/ks.cfg' \
?         -var 'ssh_user=root' \
?         -var 'ssh_key=/path/provisioning_key' \
?         ftSysMgmt.json

**Comment by mwhooker** [comment]
Hi @BeverlyBrown, thanks for the report. Sorry you're running into this issue.

The good news is this has already been addressed in master, and will be fixed for the next release.

The bad news is that I don't think there's a workaround. You can build from master if you'd like to get a working version, and I can help with this if you need.

Thanks!
