### ISSUE TITLE
Hello, I would like to collaborate with your translator project in Spanish since it is my native language, I can translate any document that has text, as long as they are more than a thousand words

### ISSUE THREAD

**Issue by LuigiBaute** [hashicorp/packer#5910]
_Please read these instructions before submitting_

**DELETE THIS TEMPLATE BEFORE SUBMITTING**

_Only use Github issues to report bugs or feature requests, see
https://www.packer.io/community.html_

For example, _Timeouts waiting for SSH/WinRM_ are generally not bugs within packer and are better addressed by the mailing list. Ask on the mailing list if you are unsure.

If you are planning to open a pull-request just open the pull-request instead of making an issue first.

FOR FEATURES:

Describe the feature you want and your use case _clearly_.

FOR BUGS:

Describe the problem and include the following information:

- Packer version from `packer version`
- Host platform
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a gist https://gist.github.com
- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your gist https://gist.github.com

**Comment by SwampDragons** [comment]
This is a really generous offer, but we don't really have the infrastructure for providing multiple language versions of the documentation, especially given that we have enough trouble keeping our english-language documentation up to date as it is.  We'll reach out if that ever changes, though.  :)

**Comment by mwhooker** [comment]
One option would be to host them yourselves, if you really wanted to translate them.
