### ISSUE TITLE
Can't use output of hyperv-iso as input of hyperv-vmcx

### ISSUE THREAD

**Issue by Crisfole** [hashicorp/packer#5913]
Trying to keep as much similar between my two build processes:

We've got a base box we build from scratch with 'virtualbox-iso'. I successfully ported it to 'hyperv-iso'.

A second step (to save on install time in case of an error downstream) is to take the output from step 1, execute some (faster) provisioning on it, outputting a Vagrant box.

After running `packer build -only=hyperv-iso base_ubuntu.json` I get the following directory:

 * `output-hyperv-iso`
   * `Virtual Hard Disks`
     * `packer-hyperv-iso.vhdx`
   * `Virtual Machines`
     * `927EA121-DF48-484C-B92E-C63AF15771B6.vmcx`
     * `927EA121-DF48-484C-B92E-C63AF15771B6.vmgs`
     * `927EA121-DF48-484C-B92E-C63AF15771B6.VMRS`

In my next step: `packer build -only=hyperv-vcmx webserver.json` I can't get packer to *see* the VM I created. The error is:
```
CloneFromVMXCPath does not exist: CreateFile output-hyperv-iso\\Virtual\ Machines: The system cannot find the path specified.
```
I've tried the following:
```
{
    "type": "hyperv-vmcx",
    "clone_from_vmxc_path": "output-hyperv-iso\\\\Virtual\\ Machines",
    "ssh_username": "packer",
    "ssh_password": "packer",
    "shutdown_command": "echo 'packer' | sudo -S shutdown -P now"
}
```
with every variety of path as possible ranging from full windows paths `C:\\\\...\\output-hyperv-iso\\Virtual\\ Machines` to `output-hyperv-iso/Virtual\\ Machines` to no avail. I don't think it's likely that literally none of my attempts have been correct.

I suspect it has to do with the space in 'Virtual Machines'

- Packer version from `packer version`: 1.2.0
- Host platform: Windows (I've attempted on WSL (which built the first step fine, as well as git bash).
- Debug log output from `PACKER_LOG=1 packer build template.json`:
No need for a gist here, too short:
```
PACKER_LOG=1 packer build -only=hyperv-vmcx webserver.json
hyperv-vmcx output will be in this color.

1 error(s) occurred:

* CloneFromVMXCPath does not exist: CreateFile output-hyperv-iso/VirtualMachines: The system cannot find the file specified.
```
  Please paste this in a gist https://gist.github.com
- Unfortunately I can't give you a shortest replicable repro.

bento has a working ubuntu 14.04 hyperv build (make sure you set the virtual switch to external and delete the post-processor to make a .box). 

Use the following with no providers to reproduce:
```
{
    "type": "hyperv-vmcx",
    "clone_from_vmxc_path": "output-hyperv-iso\\\\Virtual\\ Machines",
    "ssh_username": "packer",
    "ssh_password": "packer",
    "shutdown_command": "echo 'packer' | sudo -S shutdown -P now"
}
```

**Comment by Crisfole** [comment]
I'm going to close this since this was user error. Now it's saying the output of packer hyperv-iso is corrupt. But _that_ is a different problem.

**Comment by Crisfole** [comment]
For future me or future other people: just plain unix style paths work: `output-hyperv-iso/Virtual Machines`

**Comment by SwampDragons** [comment]
Glad you figured it out -- if you can't figure out the corrupt iso problem, please open a new ticket for us :)

**Comment by Crisfole** [comment]
So far no dice. Just merging the two steps for now to get up and running.

I think I can create a nice demo repo for you, though, so I’ll do that first.

Sent from Mail for Windows 10

**Comment by lavahot** [comment]
What about going up a level? Just `output-hyperv-iso`. That seems to work for me.
