### ISSUE TITLE
vmware-iso builder panics when building VMX file

### ISSUE THREAD

**Issue by mporrato** [hashicorp/packer#5916]
Packer version: Packer v1.2.1-dev (f67607622)
Platform: Linux x86_64
Debug log and template: https://gist.github.com/mporrato/da8e98157836e70ff721e9f244765919

The process fails [here](https://github.com/hashicorp/packer/blob/80a9250de1db0e6731f02dc24717f50daecc5255/builder/vmware/iso/step_create_vmx.go#L466) with the message "panic: runtime error: invalid memory address or nil pointer dereference" when trying to create the VMX file. See the gist for details.

Update: tested the same template with packer 1.1.3 (after removing ssh_keep_alive_interval, which apparently is not supported by this version) and it works just fine.
Update 2: packer 1.2.0 creates the vmx correctly when using a local vmware builder instead of a remote esx node.

**Comment by arizvisa** [comment]
Hey @mporrato, I have a branch that I think fixes this for packer's ESX driver at [arizvisa/packer/GH-5916](../../../arizvisa/packer/tree/GH-5916). However, I don't have an instance of ESXi to test it against. Do you mind testing it? If it ends up working for you, I can make it into a PR so it can be merged upstream.

To build this branch, you can do something like:
```
$ go get github.com/arizvisa/packer
$ cd ~/go/src/github.com/arizvisa/packer
$ git checkout GH-5916
$ make deps
$ make dev
```
Then your packer bin should be something like: `~/go/src/github.com/arizvisa/packer/bin/packer`

**Comment by mporrato** [comment]
Thanks @arizvisa : your patch fixes the issue for me.

**Comment by arizvisa** [comment]
Thanks for testing it out.

Maintainers: I created a PR for this in PR #5931

**Comment by SwampDragons** [comment]
@arizvisa have you made a PR with this patch yet?

**Comment by arizvisa** [comment]
@SwampDragons, yeah. Just waiting for the continuous-tests to do their thing.

**Comment by SwampDragons** [comment]
Nevermind, found it -- #5931 . (It was open in literally the next tab over.)

**Comment by SwampDragons** [comment]
Closing since this is fixed in 5931
