### ISSUE TITLE
Environment variables not allowed in external JSON files

### ISSUE THREAD

**Issue by barthalion** [hashicorp/packer#5921]
In my templates I have a number of variables set from my local environment. If they are set from `variables` section, it works properly: they are being correctly evaluated to the value from the environment variables or set empty if there is no such variable.

However if I move them to separate JSON file and pass `-var-file myfile.json` to packer, it fails as follows:

```
2018/02/19 14:02:04 Build 'file' prepare failure: render 'packer_user_variables': template: root:1:2: executing "root" at <env `ENV_VAR`>: error calling env: env vars are not allowed here in:

{{env `ENV_VAR`}}
2018/02/19 14:02:04 ui error: Template validation failed. Errors are shown below.
2018/02/19 14:02:04 ui error: Errors validating build 'file'. render 'packer_user_variables': template: root:1:2: executing "root" at <env `ENV_VAR`>: error calling env: env vars are not allowed here in:

{{env `ENV_VAR`}}
2018/02/19 14:02:04 [INFO] (telemetry) Finalizing.
Template validation failed. Errors are shown below.

Errors validating build 'file'. render 'packer_user_variables': template: root:1:2: executing "root" at <env `ENV_VAR`>: error calling env: env vars are not allowed here in:

{{env `ENV_VAR`}}
```

Is this behavior inconsistent on purpose?

Minimal reproducer: https://gist.github.com/Barthalion/3748fe491beb11e270dfcc1499fa7d91

1. `packer validate template.json` works
2. `packer validate -var-file=variables.json` doesn't.

Packer version: v1.2.0
Host: Arch Linux

**Comment by rickard-von-essen** [comment]
IMHO it's intended.

**Comment by mwhooker** [comment]
yup, that's how it's intended to work

https://www.packer.io/docs/templates/user-variables.html#environment-variables

> Environment variables can be used within your template using user variables. The env function is available only within the default value of a user variable, allowing you to default a user variable to an environment variable.
