### ISSUE TITLE
Solution for issue #5841 doesn't cover new/different regions

### ISSUE THREAD

**Issue by reddog0413** [hashicorp/packer#5927]
The fix for #5842 would work better as a binary variable that defaults to “not restricted”.  The way it’s currently coded, it will have to be updated if new regions are created that don't allow tags at build time and  their region names don’t begin the way China and GovCloud are named.

**Comment by SwampDragons** [comment]
the fix for #5482 looks specific to googlecompute. Did you mean #5927?

**Comment by reddog0413** [comment]
I meant #5841 like it says in the title.

**Comment by SwampDragons** [comment]
Ah, cool, thanks.

**Comment by SwampDragons** [comment]
So looking over this, I think what you're asking for is a bit of a premature optimization. If it comes up again, this is a really good idea to take into account, but given that we've already merged the other fix and that I don't foresee this issue cropping up too soon in the future, I don't think we're likely to spend time implementing it before then.

I'm going to close this issue, but if you really want to see it incorporated I'm happy to review a PR.... the code changes shouldn't be too intense.
