### ISSUE TITLE
configurable snapshot creation timeout for Oracle-Classic builds

### ISSUE THREAD

**Issue by SwampDragons** [hashicorp/packer#5930]
Feature: configurable snapshot creation timeout for Oracle-Classic builds

The length of time it takes to create a snapshot is highly dependent on the size of the underlying disk; for a minimal windows 2012 build (~21G uncompressed) this can take fifteen minutes. Currently the code is set to a 20 minute default timeout, but I can imagine situations with large disk images where that isn't enough time.

**Comment by mwhooker** [comment]
@mbfrahry what are the odds go-oracle-terraform moving to contexts? 😜
