### ISSUE TITLE
Allow Packer to ignore data in var files which is not key/value pair

### ISSUE THREAD

**Issue by robmbrooks** [hashicorp/packer#5935]
Allow Packer to ignore data in var files which is not key/value pair.

I would like to share a json provided to packer with other parts of the build process, but this requires keys with lists and hashes under them.

It would be nice if Packer would run (with warnings if necessary), without worrying about such data in var files.

**Comment by SwampDragons** [comment]
Thanks for the suggestion. However, I think the opportunity for confusion is greater than the potential gain. Requiring all of the variables in the var file to match actual configuration options is a fairly important part of Packer's validation phase, and I think it's far more likely that relaxing our standards would cause frustration than relieve it. There are plenty of third party tools for manipulating json files, and I think any type of extra processing you do to merge the Packer var files in with other configuration options should be done outside of Packer.
