### ISSUE TITLE
Windows Restart - Exit Code 16001

### ISSUE THREAD

**Issue by elum** [hashicorp/packer#5936]
Windows_Restart is getting a exit code of 16001 on Windows 2012 (Non R2) and Windows 2003 consistently when running the Operating Systems with QEMU and KVM as the accelerator.

If I put in restart_command of "shutdown /r /c \"packer restart\" /t 10" I no longer get the exit code of 16001. I think this is happening because the OS is rebooting faster then the response could happen.

Attempts to reproduce this error with Packer 1.2.0, 1.1.1, and 1.1.0 all produced the same results.
[INFO] starting remote command: shutdown /r /f /t 0 /c "packer restart"
[INFO] command 'shutdown /r /f /t 0 /c "packer restart"' exited with code: 16001

- Packer version from `1.2.0`
- Host platform CentOS 7.4

**Comment by arizvisa** [comment]
@elum, how does this affect restarting?

Error code 16001 seems to be "An unknown error has occurred." (if it's an errorlevel/exit-code).

But, does this prevent restarting from occurring on your system? I use packer against Windows Server 2012 and Windows Server 2003 pretty often, and unfortunately I haven't been blocked by this error..yet.

Is there a chance that the user that packer is authenticating with does not have that privilege, or is the OS rebooting at the same time packer sends the `restart_command` and just returning a value other than 1190 (A reboot is pending)?

**Comment by SwampDragons** [comment]
Closing since we never got a response.
