### ISSUE TITLE
remove created artifacts

### ISSUE THREAD

**Issue by xenoterracide** [hashicorp/packer#5937]
for multi-branch CI configurations it would be nice if there was an option to simply remove the artifacts, that way if you want to create, say, a series of ami's based on each other, you could at the end run, for example, `packer --rm packer.json` to then clean up the image. This is especially useful over --force, because while force will overwrite and clean up snapshots, and seems good for things like a long running branch, it may not be as good for simply testing out a build where the last artifact created would leave something behind even after the branch was removed.

**Comment by SwampDragons** [comment]
Thanks for the suggestion! The good news for you is that we already have a manifest post-processor (https://www.packer.io/docs/post-processors/manifest.html) that gives the location of the artifact, so I think you can probably delete it yourself as part of your CI process with a couple of lines of code .  I understand that it would be easier from your perspective to have Packer to manage this itself, but as this is a small benefit with a simple workaround, the best way to see this feature get created is probably to make the PR yourself.

**Comment by xenoterracide** [comment]
so I added the manifest section

```
    "provisioners": [
        {
            "type": "shell",
            "inline": "sleep 10"
        },
        {
            "type": "shell",
            "inline": "mkdir /tmp/packer"
        },
        {
            "type": "file",
            "source": "./uploads/",
            "destination": "/tmp/packer"
        },
        {
            "type": "shell",
            "execute_command": "echo 'packer' | {{ .Vars }} sudo -E -S sh '{{ .Path }}'",
            "script": "setup.sh"
        }
    ],
    "post-processors": [
        {
            "type": "manifest"
        }
    ]```

this is the snippet from the jenkinsfile that runs packer

```
        stage('base') {
            agent {
                docker {
                    image 'hashicorp/packer'
                    args '--memory 100m --cpus 0.1'
                }
            }
            steps {
                sh 'packer --version'
                retry 3, {
                    sh "cd etc/packer/base && packer build -color=false -var cluster_env=${BRANCH_NAME} packer.json"
                }
                sh 'ls -la *manifest.json'
            }
        }
```

however this is failing to list the file

```
+ ls -la *manifest.json
ls: *manifest.json: No such file or directory
```

so where does this manifest end up?

**Comment by SwampDragons** [comment]
Looking at that snippet, it should be in etc/packer/base (e.g it defaults to being created inside the directory from which you ran packer).  Looks like your `ls` isn't being performed in the right directory. Try `sh 'cd etc/packer/base && ls -la *manifest.json'` instead?
