### ISSUE TITLE
ansible with amazon-chroot always fails

### ISSUE THREAD

**Issue by dpiddockcmp** [hashicorp/packer#5940]
- Packer version from `packer version`
1.2.0

- Host platform
Amazon Linux 1 2017.09.1.20180115 x86_65

- Debug log output from `PACKER_LOG=1 packer build template.json`.
- The _simplest example template and scripts_ needed to reproduce the bug.
https://gist.github.com/dpiddockcmp/5c12efe122aae17efa0b990d918946f0

Ansible 2.4.3.0

Attempting to get amazon-chroot and ansible to work. I followed the documentation snippet on https://www.packer.io/docs/provisioners/ansible.html#chroot-communicator

Packer always calls ansible with an inventory file containing 127.0.0.1. This is not relevant for running ansible with amazon-chroot builder. It always returns a failure and thus the AMI cannot be built.

**Comment by dpiddockcmp** [comment]
PR https://github.com/hashicorp/packer/pull/4483 for the documentation says this method used to work.

ansible from Jan '17 is version 2.2. I just tried again with ansible 2.2.1.0 and it does indeed work. It silently drops duplicate inventory definitions only keeping the last specified. This limitation was fixed in the 2.4 release and broke Packer.

**Comment by MetricMike** [comment]
I'm able to get this working with Packer 1.2.2 and Ansible 2.4 using ansible-local and the following:

```json
{
  "builders": [
    {
      "type": "amazon-chroot",
      "command_wrapper": "sudo {{.Command}}",
      "mount_path": "/mnt/packer-amazon-chroot/{{user `app_name`}}/{{user `app_version`}}"
      ...
    }
  ],
  "provisioners": [
    {
      "extra_arguments": [
        "--extra-vars", "--connection=chroot"
      ],
      "playbook_file": "provision_ami.yml",
      "staging_directory": "/tmp/packer-provisioner-ansible-local",
      "type": "ansible-local"
      ...
    }
  ]
}
```

**Comment by SwampDragons** [comment]
Yeah I think your missing element was the `"command_wrapper": "sudo {{.Command}}",` referenced in the example above.
