### ISSUE TITLE
Packer panics when attempting to build against ESXi

### ISSUE THREAD

**Issue by masaeedu** [hashicorp/packer#5942]
I attempted to build an existing [Boxcutter](https://github.com/boxcutter/windows) windows template using vSphere instead of a local VMware Workstation installation. This resulted in a panic:

```
...
!!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Packer crashed! This is always indicative of a bug within Packer.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Packer[1] so that we can fix this.

[1]: https://github.com/hashicorp/packer/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
make: *** [Makefile:449: box/vmware/win2012r2-standard-nocm-1.0.4.box] Error 1
```

Full log from running `make win2012r2-standard` [here](https://gist.github.com/masaeedu/04f9dbe5d23715d56f607562ff824e13).

## Details
- Packer version: 1.2.0
- Host platform: Windows 10 x64, Powershell
- Builder: ESXi 6.0
- Output from running `$env:PACKER_LOG=1; make win2012r2-standard`
- Template and scripts needed to reproduce the bug:
  - Boxcutter [Windows 2012 Server manifest](https://github.com/boxcutter/windows/blob/a3b834937e3ded02338a9b2d86bd64d07b13a89b/win2012r2-standard.json), tweaked to attempt the build using an ESXi host (no other changes). After line 26 of the linked file, add:
    ```
      "remote_type": "esx5",
      "remote_host": "...",
      "remote_username": "root",
      "remote_password": "...",
    ```
    I can SSH to the ESXi host using the same address and credentials, so I don't think there's any problem with those (although even if they were wrong the abrupt panic is a bug)
- Crash log: https://gist.github.com/masaeedu/641889eb0ccd338682c6d49453aca4e3

**Comment by mwhooker** [comment]
Thanks for the report. Luckily, this has already been fixed. We're releasing packer 1.2.1 today, which should work for you.
