### ISSUE TITLE
Azure builder not generating deployable Windows managed images

### ISSUE THREAD

**Issue by NateB2** [hashicorp/packer#5945]
When using the packer script listed below, an Azure managed image is successfully generated, but when creating a VM, it gets stuck in the "creating" phase.  The boot diagnostics show the lockscreen.  If I delete the VM in the "creating" phase, attach the managed disk to another VM as a data disk and look at the sysprep log, here is the last entry: https://gist.github.com/NateB2/d11bba23e91d9ee3c56635177b1d4078

Running the same packer script except saving the image as a VHD instead of a managed image works successfully.  I was able to successfully generate a VHD, save it as a managed image, and then successfully create and launch a VM.

Packer version: 1.2.0
Host Platform: Windows Server 2016 Datacenter
Debug log output (as piped through VSTS): https://gist.github.com/NateB2/a740250cecb9b1cff0ed32c14aa9c87f

Packer script that creates a usable VHD: https://gist.github.com/NateB2/660748343cbf77d03fb135aa7a656b9e

Packer script that creates an unusable managed image: https://gist.github.com/NateB2/f497f5c7a7d44cb618aa42f104300f43

For now, I can work around the issue by creating the VHD and creating an image from the VHD, but it would be nice to have the ability to create a managed disk directly.

**Comment by boumenot** [comment]
I built a Windows 2016 Datacenter image, and deployed it.  It worked as expected.

I suspect the issue has to do with the various provisioning scripts you are running as opposed to Packer.  Based on the referenced links it looks like VSTS.  I recommend you work with them to address the issues.  If you can clearly pinpoint an issue with the Azure builder I am happy to investigate (or accept a PR).

Here's the template I used to build my image.

```json
{
    "variables": {
        "cid": "your_client_id",
        "cst": "your_client_secret",
        "tid": "your_client_tenant",
        "oid": "your_object_id",
        "sid": "your_subscription_id"
    },
    "builders": [
        {
            "type": "azure-arm",

            "client_id": "{{user `cid`}}",
            "client_secret": "{{user `cst`}}",
            "subscription_id": "{{user `sid`}}",
            "tenant_id": "{{user `tid`}}",
            "object_id": "{{user `oid`}}",

            "os_type": "Windows",

            "image_publisher": "MicrosoftWindowsServer",
            "image_offer": "WindowsServer",
            "image_sku": "2016-Datacenter",

            "managed_image_resource_group_name": "packer-issue-5945",
            "managed_image_name": "PackerWin2016Image",

            "location": "South Central US",
            "vm_size": "Standard_DS2_v2",

            "communicator": "winrm",
            "winrm_use_ssl": "true",
            "winrm_insecure": "true",
            "winrm_timeout": "1h",
            "winrm_username": "packer"
        }
    ],
    "provisioners": [
        {
            "type": "powershell",
            "inline": [
                "if( Test-Path $Env:SystemRoot\\windows\\system32\\Sysprep\\unattend.xml ){ rm $Env:SystemRoot\\windows\\system32\\Sysprep\\unattend.xml -Force}",
                "& $env:SystemRoot\\System32\\Sysprep\\Sysprep.exe /oobe /generalize /quiet /quit",
                "while($true) { $imageState = Get-ItemProperty HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Setup\\State | Select ImageState; if($imageState.ImageState -ne 'IMAGE_STATE_GENERALIZE_RESEAL_TO_OOBE') { Write-Output $imageState.ImageState; Start-Sleep -s 10  } else { break } }"
            ]
        }
    ]
}
```

**Comment by 4ownops** [comment]
Hi @boumenot 
I try to create image through your template, but sysprep can't change state to 'IMAGE_STATE_GENERALIZE_RESEAL_TO_OOBE'
This is what packer logged:

`azure-arm output will be in this color.

==> azure-arm: Running builder ...
....
....
....
==> azure-arm: Waiting for WinRM to become available...
    azure-arm: #< CLIXML
    azure-arm: WinRM connected.
    azure-arm: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="1"><TNRef RefId="0" /><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>
==> azure-arm: Connected to WinRM!
==> azure-arm: Provisioning with Powershell...
==> azure-arm: Provisioning with powershell script: C:\Users\tstusr~1\AppData\Local\Temp\packer-powershell-provisioner904383947
    azure-arm: IMAGE_STATE_COMPLETE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    azure-arm: IMAGE_STATE_UNDEPLOYABLE
    and etc...`

**Comment by boumenot** [comment]
I don't know. This is a sysprep question though, not a Packer question.  You can try your question with the [Packer community](https://www.packer.io/community.html), and see if anyone there has had luck debugging sysprep issues.

**Comment by KbLev** [comment]
I'm having the same problem, the build keeps looping at **IMAGE_STATE_UNDEPLOYABLE** forever. The problem is intermittent, sometimes it's working but most of the time it doesn't.

**Comment by boumenot** [comment]
You need to determine why Sysprep failed.  My best guess is that you have an external Sysprep provider that failed for whatever reason.  You may be able to understand this better by reviewing the Sysprep logs.  (I think they are under c:\windows\system32\sysprep\panther.)  

The Sysprep logs will indicate when an external provider is being launched.  You want to look for something of the form 

```text
Info       [0x0abcd0] SYSPRP LaunchDll:Found 'C:\Windows\system32\VMAgentDisabler.dll,SysprepProviderEntryPoint'; executing it
```

If the provider failed you will see `Error` statements immediately after the `Info` statement (like the one above).

The registry has a list of providers, see `HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Setup\SysPrepExternal\Generalize`.  If you want to learn more about providers, see the [docs](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-7/ee676646(v=ws.10)).

Another possibility is there is a bug elsewhere in the system that is yet unknown. What OS are you running?  What VM size are you using?  I generally use at least 2 VCPUs and 8 GB of RAM for Windows builds.

**Comment by KbLev** [comment]
I'm using the simplest example to test a workflow. The only provisioner in my code is copy-pasted from the textbook:

`    {
      "type": "powershell",
      "inline": [
        "Write-Output Packer starting",
        "if( Test-Path $Env:SystemRoot\\windows\\system32\\Sysprep\\unattend.xml ){ rm $Env:SystemRoot\\windows\\system32\\Sysprep\\unattend.xml -Force}",
        "& $env:SystemRoot\\System32\\Sysprep\\Sysprep.exe /oobe /generalize /quiet /quit",
        "while($true) { $imageState = Get-ItemProperty HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Setup\\State | Select ImageState; if($imageState.ImageState -ne 'IMAGE_STATE_GENERALIZE_RESEAL_TO_OOBE') { Write-Output $imageState.ImageState; Start-Sleep -s 10  } else { break } }"
      ]
    }`

Still, the results are inconsistent, I don't understand what is changing so that sometimes the code to runs but other times hangs. I wasted the entire day trying to create a "hello world" image.
I noticed that if I add some extra task into the provisioner, like Add-WindowsFeature, the sysprep will run correctly. Will keep digging the logs and see if I can find anything.

**Comment by boumenot** [comment]
The Windows example in the tree is deployed *many* times per day without issue, and it does exactly what you have.

Share a log of you deployment with debugging enabled.

**Comment by boumenot** [comment]
I have been trying to reproduce this issue, and I have asked others to see if they have experienced this issue too.  I think I may have something.  Please let me know if this solution works for you.  This solution only works if you install the Windows Guest Agent.  You would have to explicitly disable, which most people do not do.

Update your Packer provisioner to verify that the Guest Agent is running **before** running sysprep.

```json
{
    "provisioners": [
        {
            "inline": [
                "echo '>>> Waiting for GA to start ...'",
                "while ((Get-Service RdAgent).Status -ne 'Running') { Start-Sleep -s 5 }",
                "while ((Get-Service WindowsAzureTelemetryService).Status -ne 'Running') { Start-Sleep -s 5 }",
                "while ((Get-Service WindowsAzureGuestAgent).Status -ne 'Running') { Start-Sleep -s 5 }",

                "echo '>>> Sysprepping VM ...'",
                "if( Test-Path $Env:SystemRoot\\windows\\system32\\Sysprep\\unattend.xml ){ rm $Env:SystemRoot\\windows\\system32\\Sysprep\\unattend.xml -Force}",
                "& $Env:SystemRoot\\System32\\Sysprep\\Sysprep.exe /oobe /generalize /quiet /quit",
                "while($true) { $imageState = Get-ItemProperty HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Setup\\State | Select ImageState; if($imageState.ImageState -ne 'IMAGE_STATE_GENERALIZE_RESEAL_TO_OOBE') { Write-Output $imageState.ImageState; Start-Sleep -s 5  } else { break } }"
            ]
        }
    ]
}
```

The Windows Guest Agent takes a few second to install, and it registers a Sysprep provider.  I think there's a race between the agent installing (or updating), and Sysprep running.  You are more likely to hit this if your provisioner is simple and does very little.

**Comment by rohrerb** [comment]
@boumenot  - We ran into this issue as well with 2012R2 images. Any reason we shouldn't update this doc > https://docs.microsoft.com/en-us/azure/virtual-machines/windows/build-image-with-packer

**Comment by boumenot** [comment]
I asked for confirmation that the solution works.  If it does, I will update the docs, but I have yet to hear a yeah or nay.  ☹️   Please confirm if you are able to.

**Comment by NateB2** [comment]
The issue cleared up for me, and I haven't had any problems building images for months now while using the recommended sysprep script (the one without the code that checks to see if the guest agent services are running).  Lately it's worked 100% of the time for both Server 2016 and 2019 images.

**Comment by rohrerb** [comment]
Issue is gone for us as well.  

We occasionally will see the below but it doesn't affect the overall image or process. 
```
azure-arm: 2019-01-07 18:59:10, Error                 SYSPRP setupdigetclassdevs failed with error 0
    azure-arm: 2019-01-07 18:59:10, Error                 SYSPRP MRTGeneralize:107 - ERROR: Failed DeleteInstance AntiSpywareProduct.instanceGuid="{D68DDC3A-831F-4FAE-9E44-DA132C1ACF46}" hr=2147749904
    azure-arm: 2019-01-07 18:59:10, Error                 SYSPRP MRTGeneralize:116 - ERROR: Failed DeleteInstance AntiVirusProduct.instanceGuid="{D68DDC3A-831F-4FAE-9E44-DA132C1ACF46}" hr=2147749904
```

A few of the deployed showed the following:  (We may want to check for the existence of the service then report status in the provisioner. 

```
Get-Service : Cannot find any service with service name 'WindowsAzureGuestAgent'.
    azure-arm: At C:\Windows\Temp\script-5c33ac74-3b7f-2c6b-d490-89fe9a15d304.ps1:4 char:9
    azure-arm: + while ((Get-Service WindowsAzureGuestAgent).Status -ne 'Running') { S ...
    azure-arm: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    azure-arm:     + CategoryInfo          : ObjectNotFound: (WindowsAzureGuestAgent:String) [Get-Service], ServiceCommandException
    azure-arm:     + FullyQualifiedErrorId : NoServiceFoundForGivenName,Microsoft.PowerShell.Commands.GetServiceCommand
    azure-arm:
```

**Comment by boumenot** [comment]
```text
Get-Service : Cannot find any service with service name 'WindowsAzureGuestAgent'.
    azure-arm: At C:\Windows\Temp\script-5c33ac74-3b7f-2c6b-d490-89fe9a15d304.ps1:4 char:9
    azure-arm: + while ((Get-Service WindowsAzureGuestAgent).Status -ne 'Running') { S ...
    azure-arm: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    azure-arm:     + CategoryInfo          : ObjectNotFound: (WindowsAzureGuestAgent:String) [Get-Service], ServiceCommandException
    azure-arm:     + FullyQualifiedErrorId : NoServiceFoundForGivenName,Microsoft.PowerShell.Commands.GetServiceCommand
```

This means the Windows Guest Agent has not completed installation.  This is probably the cause of your failed Sysprep attempts.  This message should eventually go away, and the build process will continue.
