### ISSUE TITLE
Packer continues boot_command during Control+C

### ISSUE THREAD

**Issue by mcandre** [hashicorp/packer#5947]
FOR BUGS:

When packer is interrupted with a Control+C signal, it kinda-sorta begins to terminate, but instead of actually stopping the build, it continues processing any `wait` commands in the `boot_command` list. This can dramatically delay termination, especially if `boot_command` contains long waits for debugging purposes while tuning the build.

- Packer version from `packer version`: Packer v1.1.3-dev
- Host platform: Windows 10

**Comment by rickard-von-essen** [comment]
Which builder?

**Comment by mcandre** [comment]
VirtualBox

**Comment by mwhooker** [comment]
this is solved in #6129 as well
