### ISSUE TITLE
EBS builder hangs without credentials

### ISSUE THREAD

**Issue by pearkes** [hashicorp/packer#5954]
I'm seeing behavior that Packer hangs and does not respond to interrupts when I have no local AWS credentials. After looking around it seems different but potentially related to behavior fixed in #5764.

Debug log and Packer template [are here](https://gist.github.com/pearkes/090d119a1fa97e8910511e86e49052c6).

Additionally, both of these return zero, and I have no kind of AWS authentication in my environment.

```$ env | grep AWS
$ ls ~/ | grep aws
```

This on OS X with Packer 1.2.1. 

This same template errors as I would expect with Packer 1.1.3:

```
Error querying AMI: AuthFailure: AWS was not able to validate the provided access credentials
```

**Comment by mwhooker** [comment]
Thanks for the report. Looks like it waits about 1:45 before figuring out what's wrong. Not sure why it doesn't respond to ctrl+c, either, but will investigate

```
~/dev/packertest ᐅ time env -i /Users/mwhooker/go/bin/packer build amazon-ebs.json
amazon-ebs output will be in this color.

Build 'amazon-ebs' errored: No valid credential sources found for AWS Builder. Please see https://www.packer.io/docs/builders/amazon.html#specifying-amazon-credentials for more information on providing credentials for the AWS Builder.

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: No valid credential sources found for AWS Builder. Please see https://www.packer.io/docs/builders/amazon.html#specifying-amazon-credentials for more information on providing credentials for the AWS Builder.

==> Builds finished but no artifacts were created.
env -i /Users/mwhooker/go/bin/packer build amazon-ebs.json  0.14s user 0.15s system 0% cpu 1:44.96 total
```

**Comment by mwhooker** [comment]
It's because we create the aws config `WithMaxRetries(11)`
