### ISSUE TITLE
winrm_host is ignored, at least on Amazon EBS

### ISSUE THREAD

**Issue by et304383** [hashicorp/packer#5957]
Using packer compiled from source as I debugged.  So latest.
Platform: Windows 2008
Debug output doesn't show anything useful without additional logging added for the host value

winrm_host is simply ignored.  Doesn't matter what I set it to.

Looking in step_connect_winrm.go in the waitForWinRM function it seems Host is the only variable that is obtained by calling out to `s.Host()`.  The remaining WinRM variables are obtained by directly hitting `s.Config.WinRM*`

**Comment by mwhooker** [comment]
this looks like a docs bug, thanks for pointing it out. We don't expect users to set `winrm_host`. It looks like maybe it's only used the vmware builder

**Comment by et304383** [comment]
I need this value - I'm attempting to provision a Windows instance in a private subnet through an SSH tunnel for port 5985.

Are you saying there's no way to do this since the value seems to be ignored for EC2?
