### ISSUE TITLE
Packer 1.2.1 no longer works on FreeBSD 9.x (pipe vs. pipe2 syscall)

### ISSUE THREAD

**Issue by koitsu** [hashicorp/packer#5958]
As of Packer 1.2.1, the 64-bit FreeBSD binary no longer works on FreeBSD 9.3-STABLE amd64 (r328772), outputting the below and returning exit code 1:

Couldn't start Packer: pipe: function not implemented

Data points:

* pipe(2) is certainly available and works just fine on FreeBSD 9.x.  There is no functional reason this problem should be happening, especially given the static nature of Go binaries
* It looks like the Packer 1.2.1 binary is using the pipe2 syscall which is not implemented in 9.x (see below)
* The Packer 1.2.0 binary works fine on FreeBSD 9.x amd64
* The Packer 1.2.1 binary works fine on FreeBSD 11.1-STABLE amd64 (r327836)
* I have not tested FreeBSD 10.x, but it probably works there (see below)
* I have not tested i386, but architecture probably doesn't matter

Debugging information from 9.x:

```
$ truss -f packer
...
53288: clock_gettime(0,{1519934816.977554764 })  = 0 (0x0)
53288: clock_gettime(4,{2369616.806658843 })     = 0 (0x0)
53288: _umtx_op(0xc42005e950,0xf,0x0,0x18,0x0,0xc420000d80) = 0 (0x0)
53288: _umtx_op(0xc42005e950,0x10,0x1,0x0,0x0,0x0) = 0 (0x0)
53288: #542(0xc4202c1a10,0x100000,0x0,0x0,0x0,0x0) ERR#78 'Function not implemented'
Couldn't start Packer: pipe: function not implemented53288: write(2,"Couldn't start Packer: pipe: fun"...,53) = 53 (0x35)
53288: close(4)                                  = 0 (0x0)
53288: unlink("/tmp/packer-log564468178")        = 0 (0x0)
53288: process exit, rval = 1
```

Note that the syscall attempted is shown as numeric 542, rather than pipe().  There is no syscall 542 on FreeBSD 9.x.  Syscall 542 is pipe2 (per /usr/include/sys/syscall.h on FreeBSD 11.1-STABLE -- reference: https://svnweb.freebsd.org/base/stable/11/sys/sys/syscall.h?view=markup#l462), which was implemented in 10.x (per https://www.freebsd.org/doc/en/books/porters-handbook/versions-10.html)

My gut feeling is that this is some kind of Go-based change, where things began using pipe2() blindly rather than providing backwards-compatibility for older FreeBSD using pipe().  This may be related to internals wanting O_CLOEXEC or O_NONBLOCK when creating a pair of fds.

If Packer has no intention of supporting FreeBSD 9.x from this point, then the website's download page should explicitly state that the binaries are for FreeBSD 10.x / 11.x only.

**Comment by koitsu** [comment]
It looks like this is responsible. What a pity. https://github.com/golang/go/commit/e76ae8af9279ad3efc9c25ff7bb220114b70de80

So, can the Packer website be updated to reflect that only FreeBSD 10.x and newer are supported?

**Comment by mwhooker** [comment]
Thanks very much for the research on this. Would you be willing to test packer 1.2.1 compiled with go 1.9.x? packer 1.2.1 was built with go 1.10, and I wonder if that introduced the breaking change, as you've intuited

**Comment by mwhooker** [comment]
Ah, good catch. Yes, we will add a note. I assume if you need freebsd support, the go 1.9x branch will continue to work, but it's not something I think we can support at this time

**Comment by koitsu** [comment]
Understood. Thank you very much!

**Comment by rickard-von-essen** [comment]
FreeBSD 9.3 was EOL on December 31, 2016. Maybe it is time to upgrade.

**Comment by koitsu** [comment]
@rickard-von-essen I will upgrade when FreeBSD developers actually fix broken load averages in newer FreeBSD: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=173541#c8 . Sorry, this gets very off-topic very quickly and is irrelevant to Packer.
