### ISSUE TITLE
FreeBSD 10.3 + vmware-iso boot problems: "Root mount waiting for: usbus0"

### ISSUE THREAD

**Issue by AndiDog** [hashicorp/packer#5961]
**Works** for Packer **v1.1.1**
**Problematic** for both **v1.2.0 and v1.2.1** (macOS 10.13.3, VMware Fusion 8.5.10)

[Debug log](https://gist.github.com/AndiDog/9d9fd4e29c1dd8f5a26170d9675f2635)
[Minimal Packerfile to reproduce it](https://gist.github.com/AndiDog/f498a4070d5c3df83a4985e77dd7ebae)
[FreeBSD boot output snippet](https://i.imgur.com/IRUeO9E.png) (errors repeat)

The errors
```
Root mount waiting for: usbus0
[...]
usbd_setup_device_desc: getting device descriptor at addr 1 failed, USB_ERR_TIMEOUT
```

keep repeating which slows down the boot process, as the CD-ROM installer only becomes available after the system tried many times to "spin up" the USB bus. I saw that the affected change (v1.1.1..v.1.2.0) introduced USB and other hardware features in the vmware-iso builder, but neither boolean setting `usb={true,false}` made a difference (except that different numbers `usbus0`, `usbus1` or `usbus2` may be printed in the error messages).

**Comment by SwampDragons** [comment]
@arizvisa Any chance you have the bandwidth to look at this one since it seems related to https://github.com/hashicorp/packer/pull/3417?

**Comment by SwampDragons** [comment]
@AndiDog I'm unclear here -- does the build actually fail or just take longer to run?  Also, do you mind sharing the entire debug log even though you don't think it's useful?

**Comment by arizvisa** [comment]
@SwampDragons, sure.

I have a PR that I think will likely fix this, but I'm testing his template right now just to be sure. Will update you guys when its confirmed.

**Comment by arizvisa** [comment]
@AndiDog, I wasn't able to reproduce this exactly as I only have VMware Workstation on Windows to test.. But, does this branch https://github.com/arizvisa/packer/tree/GH-5961 fix it for you?

**Comment by arizvisa** [comment]
@SwampDragons, once AndiDog confirms. PR #5975 should remedy the issue.

**Comment by AndiDog** [comment]
> @AndiDog I'm unclear here -- does the build actually fail or just take longer to run? Also, do you mind sharing the entire debug log even though you don't think it's useful?

Boot takes longer. The wait for the USB bus will eventually time out. However it means one needs to add `<waitN>` (with high N) to only press keys once boot is complete, i.e. it's an intrusive change to the Packerfile.

> @AndiDog, I wasn't able to reproduce this exactly as I only have VMware Workstation on Windows to test.. But, does this branch https://github.com/arizvisa/packer/tree/GH-5961 fix it for you?

This indeed solves the problem – no more USB warnings or errors seen and boot is fast as before. Since there's a fix available, I guess no more debug log is needed here. You can close this issue once the fix is merged. I'm hoping for a minor release containing the fix ;) Thanks everyone!

**Comment by SwampDragons** [comment]
Excellent, thank you for the report and the responses.

**Comment by SwampDragons** [comment]
We'll release this patch in 1.2.2
