### ISSUE TITLE
 Build 'ubuntu16' errored: unexpected EOF

### ISSUE THREAD

**Issue by janegreira** [hashicorp/packer#5962]
Hi, I'm not able to create a VM in a ESXi Host using Packer.

Here is my code:
https://gist.github.com/janegreira/d62bec7b6338591ccc1aea7d803b7135

Here is the log that I have:
https://gist.github.com/janegreira/c5e660915709bf37b493c1711c7fcc7d

- My packer version is 1.2.0
- The ESXi host version is 6.0.0

Thanks!

**Comment by mwhooker** [comment]
Thanks very much for the report. If you upgrade to packer 1.2.1 it will be fixed
