### ISSUE TITLE
packer will use .aws credentials even if others are explicitly specified in the build file

### ISSUE THREAD

**Issue by gilbahat** [hashicorp/packer#5976]
Describe the problem and include the following information:

Packer will opt to use AWS configuration from ~/.aws even if others are explicitly specified in the configuration file. This behaviour is unexpected and inconsistent with just about every other tool out there.

STEPS TO REPRODUCE:

1. configure AWS access keys with aws configure.
2. create a build file with other explicit settings (key, secret and region)
3. run packer build -only=amazon-ebs buildfile.json

EXPECTED BEHAVIOUR:

settings from step 2 are used when looking for resources and building the machine

OBSERVED BEHAVIOUR:

settings from step 1 are used instead.

$ packer version
Packer v1.2.1
$ uname -a
Darwin pasture 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

**Comment by SwampDragons** [comment]
This is definitely a regression, as even our own docs describe the behavior you expect: https://www.packer.io/docs/builders/amazon.html#authentication

**Comment by mchodson** [comment]
this is a big deal. potential to accidentally deploy AMIs to wrong AWS env could be VERY bad. cross pollinate sensitive creds between Envs or Accts. Could also accidentally deploy an update to prod when it was meant for Dev/Stage/QA or whatever. This should really be getting more attention than it is.

**Comment by SwampDragons** [comment]
We are taking it seriously -- It's going to be handled before our next release.
