### ISSUE TITLE
Guest IP lookup failed in case of multiple VMware Fusion NAT networks

### ISSUE THREAD

**Issue by AndiDog** [hashicorp/packer#5979]
Packer 1.2.1 (also latest master branch), macOS, VMware Fusion 8.5.10

Since 1.2, the guest IP lookup completely changed. In my case, IP lookup for NAT network does not work, but it seems a general problem. Previously (Packer 1.1.1), the NAT device was found correctly (not sure how it worked). Now, `NameIntoDevice` picks the first NAT device it finds. In my case, three networks `vmnet2`, `vmnet8` and `vmnet100` exist and for some reason, VMware's DHCP assigns the lease to vmnet8 (instead of vmnet2 which I can find in the packer-generated vmx file (`ethernet0.vnet = "vmnet2"`). Not sure how to give a reproducible example here, but couldn't we solve this case generically by looping over all NAT devices instead of just the first one?

Relevant Packer code in `builder/vmware/common/driver_parser.go`:

```
else if name == "nat" && len(netmapper[NetworkingType_NAT]) > 0 {
    vmnet = netmapper[NetworkingType_NAT][0]
}
```

Debug log below. I added some printfs to prove that the code already finds all three NAT-type networks. See how vmnet2 is the first in the list, so Packer parses only vmnet2's leases file.
```
2018/03/06 15:19:48 packer: 2018/03/06 15:19:48 MEGAN: NetworkMapper is common.NetworkingConfig{answer:map[int]map[string]string{2:map[string]string{"NAT":"yes", "NAT_PARAM_NAT6":"1", "NAT_PARAM_UDP_TIMEOUT":"30", "VIRTUAL_ADAPTER":"yes", "DHCP":"yes", "DHCP_CFG_HASH":"72CFC819B3F792D1188B8B37F1CD98AB8DD3B757", "HOSTONLY_NETMASK":"255.255.255.0", "HOSTONLY_SUBNET":"192.168.174.0"}, 8:map[string]string{"DHCP":"yes", "DHCP_CFG_HASH":"991DD1997F4628A081CA8EEE125171F8C3FEC1CA", "HOSTONLY_NETMASK":"255.255.255.0", "HOSTONLY_SUBNET":"192.168.168.0", "NAT":"yes", "VIRTUAL_ADAPTER":"yes"}, 100:map[string]string{"DHCP":"yes", "DHCP_CFG_HASH":"D3BB8DBFB04C58B10D4787E45EB94424F75CEC1C", "HOSTONLY_NETMASK":"255.255.255.0", "HOSTONLY_SUBNET":"192.168.56.0", "NAT":"yes", "NAT_PARAM_NAT6":"1", "VIRTUAL_ADAPTER":"yes"}, 1:map[string]string{"DHCP":"yes", "DHCP_CFG_HASH":"FCCC13C6C8EAA020CDB31B65EF76D43E2E16E6F7", "HOSTONLY_NETMASK":"255.255.255.0", "HOSTONLY_SUBNET":"172.16.202.0", "VIRTUAL_ADAPTER":"yes"}}, nat_portfwd:map[int]map[string]string{}, dhcp_mac_to_ip:map[int]map[string]net.IP{}, bridge_mapping:map[string]int{}, nat_prefix:map[int][]int{}}
2018/03/06 15:19:48 packer: 2018/03/06 15:19:48 MEGAN: network is "nat"
2018/03/06 15:19:48 packer: 2018/03/06 15:19:48 ANDI name=nat
2018/03/06 15:19:48 packer: 2018/03/06 15:19:48 ANDI got 3 nat interfaces
2018/03/06 15:19:48 packer: 2018/03/06 15:19:48 ANDI nat interface vmnet2
2018/03/06 15:19:48 packer: 2018/03/06 15:19:48 ANDI nat interface vmnet8
2018/03/06 15:19:48 packer: 2018/03/06 15:19:48 ANDI nat interface vmnet100
2018/03/06 15:19:48 packer: 2018/03/06 15:19:48 Lookup up IP information...
2018/03/06 15:19:48 packer: 2018/03/06 15:19:48 MEGAN mac address is 00:0c:29:82:c3:6b
2018/03/06 15:19:48 packer: 2018/03/06 15:19:48 DHCP leases path: /var/db/vmware/vmnet-dhcpd-vmnet2.leases
2018/03/06 15:19:48 packer: 2018/03/06 15:19:48 IP lookup failed: IP not found for MAC 00:0c:29:82:c3:6b in DHCP leases at /var/db/vmware/vmnet-dhcpd-vmnet2.leases
2018/03/06 15:19:48 packer: 2018/03/06 15:19:48 [DEBUG] Error getting SSH address: IP lookup failed: IP not found for MAC 00:0c:29:82:c3:6b in DHCP leases at /var/db/vmware/vmnet-dhcpd-vmnet2.leases
```

**Comment by SwampDragons** [comment]
@arizvisa this seems related to that big PR we merged of yours, too. I'll take a look when I get a chance but I thought I'd ping you on it in case you have the bandwidth.

**Comment by arizvisa** [comment]
I don't have an instance of VMware Fusion and so this part of the PR I had to unfortunately write blindly, but I'll see what I can do.

On VMware Workstation, there's a netmap.conf that's parsed sequentially. However, on VMware Fusion I had to parse a sample configuration (this is done by `ReadNetworkingConfig`) to figure out the network names. Previously, we always just always used "vmnet8" and assume it was "nat".

To fix this, I'd need to know what order VMware Fusion actually prioritizes network types and soo...

**Comment by arizvisa** [comment]
@AndiDog, can you also submit the .vmx that packer emitted?

**Comment by stephenreay** [comment]
I've just started using packer with VMware Fusion (previously used it with vbox and parallels) - and I've hit what seems to be the same issue.

If I can help providing configs/details from Fusion, please let me know what will help.

**Comment by stephenreay** [comment]
Ok, so to update this, some switching of settings back and forth has led to it working, presumably because things leftover in VMware now allow it to work.

My Packer conf originally had no `network` property specified, and it failed. I tried explicitly setting `nat` and it failed (always at Debian installer screen, saying no DHCP configuration available).

I then switched to `network: "bridged"`  in the packer conf, ran it again and it bombed before even launching Fusion, complaining about missing `~/Library/Preferences/VMWare Fusion/vmnet0/dhcpd.conf` - that file in fact does not exist (I have vmnet1 and vmnet8 directories both with a dhcpd.conf)

Once this build successfully completes I can re-run through the various configs and snapshot the directory + generated VMX for each iteration, if that helps.

**Comment by AndiDog** [comment]
> @AndiDog, can you also submit the .vmx that packer emitted?

The relevant snippet is this:
```
ethernet0.connectiontype = "nat"
ethernet0.vnet = "vmnet2"
```
and I think this is misleading since the value `vmnet2` is not even used, but for generic types like "nat" or "bridged", VMware seems to choose automatically (no idea which algorithm and why it took vmnet8 in my case). Only "custom" allows [choice of a specific virtual network device](https://pubs.vmware.com/workstation-9/index.jsp?topic=%2Fcom.vmware.ws.using.doc%2FGUID-3B504F2F-7A0B-415F-AE01-62363A95D052.html).

----------

I have just successfully patched Packer to handle multiple devices per name (like "nat") and will submit a PR soon for everyone to test. For the patch, I assumed that not more than one vmnet-dhcpd process has a non-expired lease for a MAC, and therefore simply loop through all devices of the specified network. For instance, my VMware has three devices configured as "nat": vmnet2, vmnet8, vmnet100. The code goes tries each single DHCP lease file until it finds a match. In addition, I'm setting `ethernet0.vnet` empty unless the network config specifies a custom device.

**Comment by arizvisa** [comment]
@AndiDog, btw I was suggesting to disable nat for vmnet8 to figure out which device Fusion chooses if the default one isn't available (does it search? or does it assume/hardcode?). But nonetheless, your PR of just collecting all of them seems like the best solution.
