### ISSUE TITLE
Feature request: hyperv-iso builder vm configuration version

### ISSUE THREAD

**Issue by SDedik** [hashicorp/packer#5984]
Hello,
At the moment packer hyperv-iso builder creates virtual machine with the latest configuration version available on the host. This is default Windows behavior as well. If virtual machine is created on Windows Server 2016 it has default configuration version of 8.0. Virtual machines created on Windows Server 2012 R2 have configuration version of 5.0.
Version of existing virtual machines can be seen with command below.
`Get-VM | Select name, version`

The problem is that Microsoft has significantly changed virtual machine configuration files between configuration versions 5.0 and 8.0 and they are not backwards compatible. In other words, if I create a vm template on Server 2016 I cannot import that template on Server 2012 due to configuration version incompatibility.
When creating virtual machine manually from PowerShell, this can be overwritten using -Version parameter like this:
```
New-VM -Name vm1 -Version 5.0
New-VM -Name vm2 -Version 8.0
```

It would be good to add this option to packer to produce virtual machine templates that can be imported on older versions of Hyper-V even if packer itself runs on the latest server version.

**Comment by bbrala** [comment]
I have the same problem, would be awesome, and seems to be quite straightforward to implement.

**Comment by externl** [comment]
I just ran into this issue. Built a box on Windows 10. Tried to import into Windows Server 2016 and I'm getting the error:

```
Cause: VM version is unsupported
```

**Comment by SDedik** [comment]
Thank you for implementing it!
A kind reminder though that respective documentation [page ](https://www.packer.io/docs/builders/hyperv-iso.html) hasn't been updated and this configuration option may be hard to discover for new users.

**Comment by SwampDragons** [comment]
That's because the feature isn't released with Packer yet; We update the website and docs when the release goes live on our website. Currently this feature is only available on the master branch, so the docs aren't live yet.

**Comment by SwampDragons** [comment]
oh, but that PR doesn't include docs-- adding them so they'll go out with the next release.

**Comment by SDedik** [comment]
Much obliged!

**Comment by cbj4074** [comment]
Thanks for implementing this @SwampDragons !

I'm confused as to how, exactly, one should specify the `configuration_version`.

The documentation says only:

> configuration_version (string) - This allows you to set the vm version when calling New-VM to generate the vm.

That doesn't tell me *how* to `call New-VM to generate the vm.` I've looked pretty hard and I can't find a single usage example that demonstrates how and where this directive should be specified.

Adding `"configuration_version": "8.0"`, for example, to the `builders` object in `bento\ubuntu\ubuntu-18.04-amd64.json` does not in itself cause the generated VM to use the specified configuration version.

What additional step is required?

Thanks in advance for any guidance!

**Comment by cbj4074** [comment]
My apologies; I failed to realize that Packer 1.4.1 is required for this to work, and it does indeed work now that I've upgraded! 👏

**Comment by SwampDragons** [comment]
Oh, good.  This will become much clearer once we manage to implement versioned docs.
