### ISSUE TITLE
wait commands wipe out nearby modifiers

### ISSUE THREAD

**Issue by mcandre** [hashicorp/packer#6001]
The scancode translation logic has a flaw in which any `wait` commands appearing just after `<leftAltOff>` or similar special commands, cause the specials to be skipped. The implementation code mistakenly reassigns `scancode` rather than appending to it, and the log reflects that the commands are being identified, only to be dropped just before they would have been sent to `VBoxManage`.

- Packer version: Packer v1.2.2-dev
- Host platform: macOS 10.13 High Sierra

Example:

https://github.com/mcandre/packer-templates/blob/0e120057046111b6024ec6904b65cbe531c3fb70/haiku/haiku.json#L66

The `<leftAltOff>` command is never actually executed, overridden by the `<wait5>`, causing the rest of the `boot_command` to fail as the left Alt key remains stuck on for the rest of the script.

**Comment by martinanderssondotcom** [comment]
I tried removing wait commands immediately before and immediately after - didn't work. So MAAAAYBE the issue of not releasing special keys has even more triggers??

In my case, the only thing I might have done different than you, is that I tried to press <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>T</kbd> (to open a terminal). I.e., I have nested tags like so:

    <leftCtrlOn><leftAltOn>t<leftAltOff><leftCtrlOff>

Note. It didn't work to release Ctrl first and then Alt.
