### ISSUE TITLE
docker: add support for windows containers

### ISSUE THREAD

**Issue by slime-uk** [hashicorp/packer#6006]
packer version 1.20 and 1.21 (and 1.22-dev)
Host platform: Windows 10 1607 and Windows Server 1709

I seem to have multiple issues with packer when using the docker builder with very basic templates and any provisioner.  If I remove all provisoners, I can get a docker container up but without much point!

1 - Powershell - any scripts I attempt to provision seem to invoke a default behavior where packer sets some environment variables and then uploads them.  This fails (see my comments on issue #5963  and #5994) with 
```
docker: Error processing command: Error uploading ps script containing env vars: Failed to upload to '${env:SYSTEMROOT}/Temp/packer-env-vars-5aa6a518-1965-a0f8-f75e-43d6e7ba190e.ps1' in container: destination "07ac5a4dd067dd6fcc62a3d8d69c065078781c6fbcc4c83b855dc7a54b8df976:${env:SYSTEMROOT}\Temp" must be a directory
```

and yet I can attach to the docker container and SYSTEMROOT is set to C:\Windows and \Temp directory exists inside.  I've already commented on a similar issue though.  Remove the single 1 powershell provision request and no issues.

2 - File - If I try and upload a simple .BAT file, it seems packer is trying to chown of the file as it uploads:

```
Build 'docker' errored: Failed to set owner of the uploaded file: exit status 126, container 99bf8ea3137758238d76a4c0c787191933b05773a696135e7605a72ac8785340 encountered an error during CreateProcess: failure in a Windows system call: The user name or password is incorrect. (0x52e) extra info: {"ApplicationName":"","CommandLine":"/bin/sh -c \"chown -R root c:/windows/temp/myscript.bat\"","User":"root","WorkingDirectory":"C:\\","Environment":{},"EmulateConsole":false,"CreateStdInPipe":true,"CreateStdOutPipe":true,"CreateStdErrPipe":true,"ConsoleSize":[0,0]}
```
again, if I remove the simple file provision step, no issues - container is up but no real point.

3 - windows-shell -similar to 2 above

```
packer.exe: 2018/03/12 16:42:05 Retryable error: Error uploading script: Failed to set owner of the uploaded file: exit status 126, container 189ec2db6928fe4d3dcb2754792e7c24f0f40e8b7138c67f2e0c4a701de28923 encountered an error during CreateProcess: failure in a Windows system call: The user name or password is incorrect. (0x52e) extra info: {"ApplicationName":"","CommandLine":"/bin/sh -c \"chown -R root c:/Windows/Temp/script.bat\"","User":"root","WorkingDirectory":"C:\\","Environment":{},"EmulateConsole":false,"CreateStdInPipe":true,"CreateStdOutPipe":true,"CreateStdErrPipe":true,"ConsoleSize":[0,0]}
```
Of course I can supply more info, but the JSON for all issues above really are very simple:

```
{
	"builders": [
		{
			"type": "docker",
			"image": "microsoft/windowsservercore:1709",
			"container_dir": "c:/app",
			"run_command": ["-d", "-i", "-t", "-p", "5986:5986", "-e powershell", "{{.Image}}"],
			"export_path": "image.zip",
		}
	],
	"provisioners": [
		{
			"type": "windows-shell",
			"scripts": [
				"./myscript.bat"
			]
		}
	]
}
```

I wondered if all this was due to packer using the default docker communicator.  So I tried to switch to WinRM as this is for a windows container.  I had no luck with that either in that it fails to connect at all as it seems the winrm_host value I specify is never passed according to the debug log:
```
ui: ==> docker: Waiting for WinRM to become available...
2018/03/12 16:45:13 packer.exe: 2018/03/12 16:45:13 [INFO] Attempting WinRM connection...
2018/03/12 16:45:13 packer.exe: 2018/03/12 16:45:13 [DEBUG] connecting to remote shell using WinRM
2018/03/12 16:45:14 packer.exe: 2018/03/12 16:45:14 [ERROR] connection error: unknown error Post https://:5986/wsman: dial tcp :5986: connectex: No connection could be made because the target machine actively refused it.
```

Thanks!

**Comment by mwhooker** [comment]
Thanks very much for the issue. When this builder was first written, docker and windows wasn't even an option. I don't think it's grown to accommodate that yet, so it's no surprise to me that it doesn't work.

I think the builder will need significant improvements before this is something it can support. Perhaps we should roll this into existing work to use the docker API (https://github.com/hashicorp/packer/pull/4186)

**Comment by slime-uk** [comment]
No problem - understood.  I kept going with trying this as no where does it say it won't work and I really wanted it to work.

Do you think once my issues are verified by someone, it could be noted on the docker builder page to save others from trying similar things that are likely not to work?

**Comment by SwampDragons** [comment]
@slime-uk that's probably a very good idea, until we get around to actually fixing docker for windows.

**Comment by briggsy87** [comment]
Any updates on if there is any movement with this request? I am eagerly awaiting the ability to use packer to build out windows docker images.

**Comment by SwampDragons** [comment]
Unfortunately, we haven't had a chance to work on this yet.

**Comment by MaelC** [comment]
Possibly related to the 'winrm_host' being ignored: When you set this value, the driver still requires the DHCP files and values to be set.  Since I imagine this is more related to static networks, I don't see why DHCP MUST be enabled and configured when using 'winrm_host'.

Not sure if this needs a new issue or not.  Happy to open if necessary.
