### ISSUE TITLE
Error to create a simple server on Digital Ocean

### ISSUE THREAD

**Issue by diogocaetano** [hashicorp/packer#6007]
Hello,

I try to create a simple server on Digital Ocean, but I received only this error:

----------
packer build -debug packer.json
```
Debug mode enabled. Builds will not be parallelized.
digitalocean output will be in this color.

==> digitalocean: Creating temporary ssh key for droplet...
==> digitalocean: Error creating temporary SSH key: Post /v2/account/keys: unsupported protocol scheme ""
Build 'digitalocean' errored: Error creating temporary SSH key: Post /v2/account/keys: unsupported protocol scheme ""

==> Some builds didn't complete successfully and had errors:
--> digitalocean: Error creating temporary SSH key: Post /v2/account/keys: unsupported protocol scheme ""

==> Builds finished but no artifacts were created.
```
--------------------

packer version
Packer v1.2.1
  
--------------------
files to debug:

https://gist.github.com/diogocaetano/c34b55a7b4bc732d24c77f556ca844b2

-------------------

Any help?

**Comment by mwhooker** [comment]
I'm not able to reproduce this. Does this happen every time you run the builder?

**Comment by diogocaetano** [comment]
@mwhooker Thank you for trying help. I accidentally set DIGITALOCEAN_API_URL environment variable. And this cause this error. The error message was not friendly to a wong URL for digitalocean provider.

I will close this issue thank you again.
