### ISSUE TITLE
Azure Packer builder must have bootdiagnostics enabled for the temp VM it creates for debugging

### ISSUE THREAD

**Issue by cloudbooster** [hashicorp/packer#6008]
Azure packer builder temp VM doesnt have bootdiagnostics enabled by default. So if there are provisioning issues its very hard to debug. Its a simple option to enable this at the VM create time.

**Comment by phillipsj** [comment]
I am happy to take a shot at implementing this.

**Comment by boumenot** [comment]
I was just about to look at this, but if you like to a shot then by all means.
