### ISSUE TITLE
Failed to initialize build 'amazon−ebs': builder type not found: amazon−ebs

### ISSUE THREAD

**Issue by sibh8** [hashicorp/packer#6024]
Hello,

I am a newbie in Packer and facing the below issue when executing packer build for AWS artefacts on Centos 7 host. Please help me in resolving the issue.

Issue: Failed to initialize build 'amazon−ebs': builder type not found: amazon−ebs
Packer Version: 1.2.0 (Tried the same on Packer 1.2.1)
Packer template used:
{
"variables": {
    "aws_access_key": "XXXXXXX",
    "aws_secret_key": "XXXXXXXXXXXX"
},
"builders": [{
    "type": "amazon−ebs",
    "access_key": "{{user `aws_access_key`}}",
    "secret_key": "{{user `aws_secret_key`}}",
    "region": "us−east−1",
    "source_ami": "ami-66506c1c",
    "instance_type": "t2.micro",
    "ssh_username": "ubuntu",
    "ami_name": "packer−example {{timestamp | clean_ami_name}}"
}]
}

Command used: packer validate initial_ami.json

Raising this as I could not find a solution from available issues.
 
Thanks
sibh8

**Comment by rickard-von-essen** [comment]
To me it looks like you have a long dash instead of a normal dash:

`amazon−ebs` (your)
`amazon-ebs` (correct)

**Comment by sibh8** [comment]
Thanks this has resolved my issue
