### ISSUE TITLE
LXD Builder fails on push operation in provisioner step

### ISSUE THREAD

**Issue by snesbittsea** [hashicorp/packer#6025]
I am unable to provision a lxc container built with lxd builder.. Container is successfully built, but the provision step goes into an endless loop trying to perform a lxc exec. I am able to log into the container and the referenced script is present and can be run without raising an error condition.

- LXD Version: 2.2.1 
- Packer version: 1.2.1
- Host platform: ubuntu 17.04
- Debug log output from `PACKER_LOG=1 packer build template.json`.
```
2018/03/18 17:56:18 packer: 2018/03/18 17:56:18 Running copy command: lxc file push - packer-lxd-xenial/tmp/script_6203.sh
2018/03/18 17:56:18 packer: 2018/03/18 17:56:18 Retryable error: Error uploading script: exit status 1
2018/03/18 17:56:20 packer: 2018/03/18 17:56:20 Executing with lxc exec in container: packer-lxd-xenial test -d "/tmp/script_6203.sh"
2018/03/18 17:56:20 packer: 2018/03/18 17:56:20 Executing lxc exec: /bin/sh []string{"/bin/sh", "-c", "lxc exec packer-lxd-xenial -- /bin/sh -c \"test -d \"/tmp/script_6203.sh\"\""}
```
- The _simplest example template and scripts_ needed to reproduce the bug.
```
{
  "builders": [
    {
      "type": "lxd",
      "name": "lxd-xenial",
      "image": "ubuntu-daily:xenial",
      "output_image": "ubuntu-xenial",
      "publish_properties": {
      "description": "Trivial repackage with Packer"
      }
    }
  ],
  "provisioners": [
  {
    "type": "shell",
    "inline": [ "apt-get update && apt-get install -y python-minimal" ]
  }
  ]
}  
```

**Comment by snesbittsea** [comment]
I've done some further investigation including updating packer to 1.2.1-dev.

I *think* the core problem is that the provisioner is issuing chown commands which are failing with permission denied errors. If I modify the default profile and set security.privileged=true then the provisioner does invoke the script (it then fails with a "temporary failure resolving" error, but that's another problem)

Does the LXD builder assume an unprivileged container or do I have a LXD configuration issue?

**Comment by snesbittsea** [comment]
I've traced the problem to my uid being outside the container uid/gid range (my uid is > 65535).

Note there still may be an issue in that the only way I could stop the packer script was through a kill -9. Ctl-C had no effect.

**Comment by SwampDragons** [comment]
cc'ing the original creator of the LXD builder, @ChrisLundquist

**Comment by grisaitis** [comment]
I'm experiencing the same issue originally described by @snesbittsea. 

Some similarities: my user ID is > 65535
Some differences: I'm on Mac OS, and using lxc to connect to a cluster on AWS

host OS: Mac 10.12.6 (16G1314)
lxc version: 3.3
packer version: 1.2.5
debug output from `PACKER_LOG=1 packer build` using @snesbittsea's `template.json` (which replicates my issue):

~~~
==> lxd-xenial: Provisioning with shell script: /var/folders/xm/fhlpcc195vq0y368w4q69559pjt2fs/T/packer-shell951758931
2018/08/11 19:44:31 packer: 2018/08/11 19:44:31 Opening /var/folders/xm/fhlpcc195vq0y368w4q69559pjt2fs/T/packer-shell951758931 for reading
2018/08/11 19:44:31 packer: 2018/08/11 19:44:31 [INFO] 65 bytes written for 'uploadData'
2018/08/11 19:44:31 [INFO] 65 bytes written for 'uploadData'
2018/08/11 19:44:31 packer: 2018/08/11 19:44:31 Executing with lxc exec in container: packer-lxd-xenial test -d "/tmp/script_7240.sh"
2018/08/11 19:44:31 packer: 2018/08/11 19:44:31 Executing lxc exec: /bin/sh []string{"/bin/sh", "-c", "lxc exec packer-lxd-xenial -- /bin/sh -c \"test -d \"/tmp/script_7240.sh\"\""}
2018/08/11 19:44:33 packer: 2018/08/11 19:44:33 lxc exec execution exited with '1': 'test -d "/tmp/script_7240.sh"'
2018/08/11 19:44:33 packer: 2018/08/11 19:44:33 Running copy command: lxc file push - packer-lxd-xenial/tmp/script_7240.sh
2018/08/11 19:44:34 packer: 2018/08/11 19:44:34 Retryable error: Error uploading script: exit status 1
~~~

Do I basically have to make a new user with a normal user ID?

**Comment by snesbittsea** [comment]
I believe so.

Here's a discussion I had with the LXD team: https://discuss.linuxcontainers.org/t/problems-with-id-mapping-with-lxd-3-0-0/1646/5

-steve
