### ISSUE TITLE
feature request: better error logging for missing sources

### ISSUE THREAD

**Issue by gilbahat** [hashicorp/packer#6026]
Hi,

the error message "Source file needs to exist at time of config validation!" is extremely opaque. since multiple such sources may exist and some of them may be templated or read from variables, it would be extremely helpful to print which source was missing and what was the value that was attempted to be read.

the error message should ideally be:
"Source file /Users/gilbahat/foo/bar/gzonk does not exist (err: (syscall errcode))"

**Comment by mwhooker** [comment]
good idea. fixed in 49958391b
