### ISSUE TITLE
ISO checksum parsing fails to look for ISO relative to checksum contents

### ISSUE THREAD

**Issue by mcandre** [hashicorp/packer#6028]
Commit 853b04420c83fed3daa1de54404c94a80a63c3f6 strove to make checksum validation more flexible, however it actually ends up doing the opposite. Before, I was able to pack my macOS guest box, which relied on the checksum file appearing in `/tmp` for reasons. After this commit, packer now forces ISO's to appear at file locations relative to the checksum file path itself, which is the opposite of the stated intention of the commit.

Prior to the commit, packer would look at the checksum file contents to determine a base for the ISO path, which is the correct thing to do, as checksum files' contents may specify a path.

Here, packer should respect the path specified *inside* the checksum file, when evaluating where to find the ISO: `/Users/andrew/go/src/github.com/mcandre/packer-templates/macos/<ISO filename>`:

```
d946c8e037c74a5ee5ba3abe440a5b11351ee07c5715e1c4278d0bbe0644c3632d284201db932ebeac688080ce15d0b7142d1ccdb676b95c5d45272db82af8f9  /Users/andrew/go/src/github.com/mcandre/packer-templates/macos/macos-10.13.iso
```

Now, checksum files may also provide paths relative to the current working directory, or paths with no base whatsoever:

```
d946c8e037c74a5ee5ba3abe440a5b11351ee07c5715e1c4278d0bbe0644c3632d284201db932ebeac688080ce15d0b7142d1ccdb676b95c5d45272db82af8f9  ./macos-10.13.iso
```

```
d946c8e037c74a5ee5ba3abe440a5b11351ee07c5715e1c4278d0bbe0644c3632d284201db932ebeac688080ce15d0b7142d1ccdb676b95c5d45272db82af8f9  macos-10.13.iso
```

In which case, packer should most likely assume that the ISO base path is packer's current working directory.

**Comment by SwampDragons** [comment]
Hey @mcandre I've started looking into this and I'm confused.  Initially when I read this I thought it was a regression, but after testing I don't think that's the case: 

>After this commit, packer now forces ISO's to appear at file locations relative to the checksum file path itself, which is the opposite of the stated intention of the commit.

I don't think this is true. Users have never been able to specify an absolute path, even before the commit you pointed to. Before this commit, you could _only_ specify a filepath's base, e.g. `myfile.iso`. After this commit, you're also allowed to specify files relative to the checksum file (e.g. `./subdir/myfile.iso` or `subdir/myfile.iso`.

Are you saying you'd also like to be allowed to specify absolute paths _as well_? That makes sense to me, but I'm confused about how the behavior has actually broken for you as a result of that commit.

**Comment by SwampDragons** [comment]
Nevermind; I found it -- you were providing a relative iso_url, which is where the hangup was. If you have a chance, check out PR #6488, which should both allow absolute paths and also iso_urls that have been provided (correctly) relative to the Packer run directory.

**Comment by SwampDragons** [comment]
Also, just a note -- this would have taken me a lot less time to figure out if you'd provided logs and a repro case so I could see the actual error message being raised by your use case. I spent a lot of time barking up the wrong tree because I wasn't totally clear from your description where the problem was.
