### ISSUE TITLE
Add LXD configuration option allowing specification of a LXD profile.

### ISSUE THREAD

**Issue by snesbittsea** [hashicorp/packer#6030]
Enhancement request is to add a new configuration option to LXD builder which would allow a user to specify a profile to be used when creating the LXD container. A default value of "default" would be presumed.

One use case here is to allow one to leverage the cloud-init capability which allows one to specify commands to be run on the first invocation of a container - e.g. apt-get update && apt-get install python-minimal - without requiring invocation of a separate shell command (say for example to install python-minimal for ansible use). A description of the process can be found here: https://blog.simos.info/how-to-preconfigure-lxd-containers-with-cloud-init

**Comment by SwampDragons** [comment]
cc'ing the original creator of the LXD builder, @ChrisLundquist

**Comment by gaetanquentin** [comment]
how to specify multiple profiles? default,profx?
