### ISSUE TITLE
LXD Starts provisioning before container ready

### ISSUE THREAD

**Issue by snesbittsea** [hashicorp/packer#6031]
The provisioner step on the LXD builder is subject to failure because it is executed prior to container being fully started.

LXD Version: 2.2.1
Packer version: 1.2.1-dev
Host platform: ubuntu 17.04
Debug log output from PACKER_LOG=1 packer build template.json.

On my system the following template consistently fails with  the message:
`lxc exec temporary failure resolving 'archive.ubuntu.com`

```
{
  "builders": [
    {
      "type": "lxd",
      "name": "lxd-xenial",
      "image": "ubuntu-daily:xenial",
      "output_image": "ubuntu-xenial",
      "publish_properties": {
      "description": "Trivial repackage with Packer"
      }
    }
  ],
  "provisioners": [
  {
    "type": "shell",
    "inline": [ "apt-get update  && apt-get install -y python-minimal" ]
  }
  ]
}
```

I am pretty certain this is caused because the the apt-get update is executed prior to the container's network being ready.

I am seeing a similar problem if I use a cloud-init config as described in issue 6030.

I was able to get the apt-get-update && apt-get install -y python script to work by prepending a sleep 10 command:

With respect to the cloud-init case, I got it to work by running the command:
```
 {
    "type": "shell",
    "inline": [ "while [ ! -f /var/lib/cloud/instance/boot-finished ]; do echo 'Waiting for cloud-init...'; sleep 5; done;" ]
  },
```

There is a discussion around this issue along with some proposed remedies in https://github.com/lxc/lxd/issues/3804

Even if there is no good programming solution or resources to implement solution it would be nice to add some notes to the documentation.

**Comment by SwampDragons** [comment]
cc'ing the original creator of the LXD builder, @ChrisLundquist

**Comment by ChrisLundquist** [comment]
Yeah, there is a sleep hack in the code already, and I tried to pick a good number, which is always a losing battle.

In 14.04 we could check the run level on boot and get a reasonable answer for when the container was ready. In 16.04 and with systemd run level wasn't quite as accurate, and would often hit this problem, so I added a short sleep :(

(as you already linked)
https://github.com/lxc/lxd/issues/3804

Points out this is a little tricky. I can think of a few decent ways to hack this for debian family (poll `ip addr` for an IP off the top of my head), but I know someone will try alpine and may not have the same tools installed.

I'll take a look today to see if there are any improvements, may at least make the sleep hack configurable, and add a doc note like you said.

**Comment by rickard-von-essen** [comment]
IMHO packer shouldn't implement guest distribution specific workarounds.
Instead we should document this and describe some common ways of handling
this.

For example the first provisioner could loop and wait for network
connectivity.

**Comment by ChrisLundquist** [comment]
> IMHO packer shouldn't implement guest distribution specific workarounds.
> Instead we should document this and describe some common ways of handling
> this.

100% agree, it is out of scope for packer and a losing battle, which is why I went with the less-than-ideal sleep a few seconds approach originally.
