### ISSUE TITLE
scp uploader assumes we are uploading a file

### ISSUE THREAD

**Issue by mwhooker** [hashicorp/packer#6032]
In a few places in the ssh communicator, we try to access the os.FileInfo object, assuming it will exist. cf https://github.com/hashicorp/packer/blob/b9bcde5a97ab5b936ccb13dbe23f3ee2bd98fa8d/communicator/ssh/communicator.go#L427

This assumption is not correct, because if, for example, we are uploading an inline script, we don't create a file object. We create an object that implements `io.Reader`. The existence of the argument is a bit confusing and would ideally have been avoided, but it's a useful optimization. This is entirely my fault for not catching it in code review, but it's something we need to deal with.

Here is a script that will reproduce it reliably:

```json
{
    "builders": [
        {
            "ami_name": "packer-qs-{{timestamp}}",
            "instance_type": "t2.micro",
            "region": "us-east-1",
            "source_ami_filter": {
                "filters": {
                    "name": "*ubuntu-xenial-16.04-amd64-server-*",
                    "root-device-type": "ebs",
                    "virtualization-type": "hvm"
                },
                "most_recent": true,
                "owners": [
                    "099720109477"
                ]
            },
            "ssh_username": "ubuntu",
            "type": "amazon-ebs"
        }
    ],
    "provisioners": [
        {
            "inline": [
                "sleep 3",
                "echo foo"
            ],
            "remote_path": "/tmp",
            "type": "shell"
        }
    ]
}
```

This may or may not be the same issue as #6029, but they are surely related. Happy to chat more about this face to face

**Comment by mwhooker** [comment]
There is a throwaway example PR at #6033 that shows where the problem is

**Comment by SwampDragons** [comment]
Is the problem somewhere else? Do you want me to scour through the ssh code to find other instasnces, or do you think 6033 handles it?

**Comment by mwhooker** [comment]
@SwampDragons I don't know. anywhere that has a `test -d` call _might_ have issues, but 6033 definitely handles all the ssh related code

**Comment by mwhooker** [comment]
just did a quick check and I think docker has this issue too. I can take care of that in 6033

**Comment by SwampDragons** [comment]
ok; I think your approach there is the right one. Adding the stderr and stdout is a big improvement. I might suggest making the error message raised when fi is nil a little more explicit; if I got back that error I would have no  idea what I'd done wrong.
