### ISSUE TITLE
amazon-import does not support AWS profile parameter

### ISSUE THREAD

**Issue by philwinder** [hashicorp/packer#6042]
Unlike the [AWS builders](https://www.packer.io/docs/builders/amazon-ebs.html), the `amazon-import` post-processor does not have a parameter to accept the AWS profile.

My use case is to hard-code the profile in the packer build script to avoid accidentally using credentials from the default profile. I believe that the `aws-import` options should match the builder options for consistency.

Also, I've read conflicting reports as to whether setting the `AWS_PROFILE` environmental variable works or not. I'll try this as a workaround.

**Comment by mwhooker** [comment]
I think this is a docs issue. You should be able to pass `profile` into the post-processor. It uses the exact same config that the builders do

**Comment by mwhooker** [comment]
fixed in dc41b086f
