### ISSUE TITLE
Specify network for packer docker builder

### ISSUE THREAD

**Issue by DaveHewy** [hashicorp/packer#6043]
Hi, the ability to specify a specific docker network when using packer+docker builder, seems to be missing. And would seemingly be a useful feature to me.

Let me provide an example. I'll often create some services inside a segregated docker network using compose and `docker network create`. I then presumed my packer provisioned container could be launched against that network and be able to discover other containers (services) within that network. Alas, here I am writing this issue.

I could be missing something here?

**Comment by rickard-von-essen** [comment]
Just use [`run_command`](https://www.packer.io/docs/builders/docker.html#run_command).

**Comment by DaveHewy** [comment]
@rickard-von-essen ah missed it. closing.

**Comment by bbaassssiiee** [comment]
To use the network of the host:

```
    {
      "changes": [
        "WORKDIR /root",
        "CMD [\"/bin/bash\"]"
      ],
      "commit": true,
      "image": "centos:7",
      "run_command": [
        "-d", "-i", "-t", "--network=host", "--entrypoint=/bin/sh", "--", "{{.Image}}"
      ],
      "type": "docker"
    }
```
