### ISSUE TITLE
Error while creating the image for windows 10 desktop on Azure

### ISSUE THREAD

**Issue by sibh8** [hashicorp/packer#6044]
Hi,

I am getting the below issue while executing packer build for creating windows 10 desktop image on Azure platform. I would be grateful to you if you could help me in resolving the same.

**_==> azure-arm: Running builder ...
    azure-arm: Creating Azure Resource Manager (ARM) client ...
==> azure-arm: Creating resource group ...
==> azure-arm:  -> ResourceGroupName : 'temp_packer_build_rg'
==> azure-arm:  -> Location          : 'West Europe'
==> azure-arm:  -> Tags              :
==> azure-arm:  ->> dept : Development-Environment
==> azure-arm: Validating deployment template ...
==> azure-arm:  -> ResourceGroupName : 'temp_packer_build_rg'
==> azure-arm:  -> DeploymentName    : 'pkrdpg2pcxjp71k'
==> azure-arm: Deploying deployment template ...
==> azure-arm:  -> ResourceGroupName : 'temp_packer_build_rg'
==> azure-arm:  -> DeploymentName    : 'kvpkrdpg2pcxjp71k'
==> azure-arm: ERROR: -> DeploymentFailed : At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.
==> azure-arm: ERROR:   -> BadRequest
==> azure-arm: ERROR:   -> BadRequest : An invalid value was provided for 'accessPolicies'.
==> azure-arm:
==> azure-arm: resources.DeploymentsClient#CreateOrUpdate: Failure sending request: StatusCode=200 -- Original Error: Long running operation terminated with status 'Failed': Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details."
==> azure-arm:
==> azure-arm: Cleanup requested, deleting resource group ...
==> azure-arm: Resource group has been deleted.
Build 'azure-arm' errored: resources.DeploymentsClient#CreateOrUpdate: Failure sending request: StatusCode=200 -- Original Error: Long running operation terminated with status 'Failed': Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details."

==> Some builds didn't complete successfully and had errors:
--> azure-arm: resources.DeploymentsClient#CreateOrUpdate: Failure sending request: StatusCode=200 -- Original Error: Long running operation terminated with status 'Failed': Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details."_**

My Packer template is as below:

**{
"variables": {
    "azure_subscription_id": "{{env `azure_subscription_id`}}",
    "azure_tennant_id": "{{env `azure_tennant_id`}}",
    "azure_application_id": "{{env `azure_application_id`}}",
    "azure_application_password": "{{env `azure_application_password`}}"
},
"builders": [{
    "type": "azure-arm",

    "client_id": "{{user `azure_application_id`}}",
    "client_secret": "{{user `azure_application_password`}}",
    "tenant_id": "{{user `azure_tennant_id`}}",
    "subscription_id": "{{user `azure_subscription_id`}}",

    "managed_image_name": "developer_desktop_image",
    "managed_image_resource_group_name": "image_library_rg",

    "os_type": "windows",
    "image_publisher": "MicrosoftWindowsDesktop",
    "image_offer": "Windows-10",
    "image_sku": "RS2-Pro",

    "location": "West Europe",
    "temp_resource_group_name": "temp_packer_build_rg",

    "location": "West Europe",
    "vm_size": "Standard_E2s_v3",

    "azure_tags": {
       "dept": "Development-Environment"
    }
}]
}**

I also tried to give os_type parameter as Windows (W in capitals). Still facing the same issue.

**Comment by sibh8** [comment]
Hello,

Thanks for the response. Using the above template, I am getting the below error.

==> azure-arm: ERROR: -> Forbidden : Access denied
==> azure-arm:
==> azure-arm:  ...failed to get certificate URL, retry(0)
==> azure-arm: ERROR: -> Forbidden : Access denied
==> azure-arm:
==> azure-arm:  ...failed to get certificate URL, retry(1)
==> azure-arm: ERROR: -> Forbidden : Access denied
==> azure-arm:
==> azure-arm:  ...failed to get certificate URL, retry(2)

Thanks

**Comment by boumenot** [comment]
Please try to enable debugging, and post a gist of the output.

**Comment by byron70** [comment]
```
"object_id": "{{user `oid`}}
```

For the above attribute, we received a similar error when I was using the incorrect service principal user's ObjectId. We also had a custom role in place that required: `"Microsoft.KeyVault/vaults/accessPolicies/write"`

**Comment by sibh8** [comment]
Hi Chris,

Thanks for the message. Will try the same and post it on group

Thanks and regards
Siddhesh Bhandarkar

**Comment by boumenot** [comment]
Timing this out.  If you got it work please share the details, so future readers can learn too.  If you're still stuck please share that too.

**Comment by BenMitchell1979** [comment]
Per the documentation, this has been added. But it fails on build. https://www.packer.io/docs/builders/azure.html 

bmitchell@test-w10jump:/mnt/e/OneDrive/work/mb-files/golden-images$ packer build windows-10-base.json
azure-arm output will be in this color.

1 error occurred:

* unknown configuration key: "shared_image_gallery"
