### ISSUE TITLE
Packer Crash - v 1.1.1

### ISSUE THREAD

**Issue by MIams-REISys** [hashicorp/packer#6045]
Details in gist

https://gist.github.com/MIams-REISys/d7b161b791d93e6eb4a7969eb7beb442

**Comment by rickard-von-essen** [comment]
Please reproduce with 1.2.1.

**Comment by mwhooker** [comment]
Thanks for the report. this is a dupe of https://github.com/hashicorp/packer/issues/5535 and should be fixed in newer versions
