### ISSUE TITLE
oracle-oci: Error waiting for SSH handshake failed: ssh: unable to authenticate

### ISSUE THREAD

**Issue by jl98800** [hashicorp/packer#6046]
==> oracle-oci: Error waiting for SSH: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

- Packer version from packer --version 1.2.0

- Host platform Mac OS X 10.12.6

==> oracle-oci: Waiting for instance to enter 'RUNNING' state...
==> oracle-oci: Instance 'RUNNING'.
==> oracle-oci: Instance has public IP: .
==> oracle-oci: Waiting for SSH to become available...
==> oracle-oci: Error waiting for SSH: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
==> oracle-oci: Terminated instance.
Build 'oracle-oci' errored: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

==> Some builds didn't complete successfully and had errors:
--> oracle-oci: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

Isn't there a way to reference the key file to use or the public key itself as part of the packer build?  I suspect that's why the ssh is failing.  OCI has a default user (opc) for OEL 7.x images provided by OCI. Which allows for a public key to be added to authorized_keys during the build - but without a way to pass this key along in the JSON file I'm unsure how to make the build work.  

In my JSON I'm using the default user:
    "oci_ssh_username": "opc",
    "ssh_username": "{{user `oci_ssh_username`}}",

And I've verified my key file works with the OCI api. 
    "oci_key_file": "{{env `OCI_KEY_FILE`}}",
    "key_file": "{{user `oci_key_file`}}",

Are there more options than provided here:  
https://blogs.oracle.com/cloudmarketplace/creating-oracle-compute-cloud-virtual-machine-images-using-packer
or here
https://www.packer.io/docs/builders/oracle-oci.html

Besides the ssh error my JSON is legit:
packer validate oracle_74.json 
Template validated successfully.

Manually creating an instance in OCI accepts the pub key file or the pub key pasted.

**Comment by jl98800** [comment]
This ssh error could be caused by not having access to the network (private or public) where the image is being built.  More to follow.

**Comment by jl98800** [comment]
Yet, are there any additional parameters I can use with my packer JSON to append my RSA public key to the default opc user's (for OEL) authorized_keys?  I see ssh_private_key_file but OCI prefers the public RSA key when building the shape manually.

**Comment by jl98800** [comment]
May be related to https://github.com/hashicorp/packer/issues/5627

**Comment by SwampDragons** [comment]
#5627 was specifically related to AWS, so I don't believe it is related. Can you share your full logs with the environment PACKER_DEBUG=1 please?

**Comment by SwampDragons** [comment]
Yay! So glad you got it figured out :)
