### ISSUE TITLE
Feature request: Oracle OCI metadata post-processor

### ISSUE THREAD

**Issue by Marcus-James-Adams** [hashicorp/packer#6048]
It would be useful if we had an Oracle OCI post provisioner that saved the json of the builder information, Region, compartment and also the OCID of the image it created to a file (based on builder name???)
This would be useful when you are creating your own master gold OS images to form a basebuld that a then be used by other packer scripts automatically as the base image ID

**Comment by rickard-von-essen** [comment]
How about the [`manifest` post-processor](https://www.packer.io/docs/post-processors/manifest.html)? Which information is missing from it?

**Comment by Marcus-James-Adams** [comment]
Your right i don't know why i didn't look at that first
The only things that I think are missing that i could foresee being helpful when chaining images
are:
image_name
region-id
compartment-id

**Comment by Marcus-James-Adams** [comment]
manifest post-processor has the information needed
