### ISSUE TITLE
Feature Request: Use tags from the source_ami

### ISSUE THREAD

**Issue by adongy** [hashicorp/packer#6059]
Hi,

When using `source_ami` or `source_ami_filter`, some data is exposed to the template, namely `SourceAMI` and `Region`. This is documented behavior: https://www.packer.io/docs/builders/amazon-ebs.html#tags

I'd like to have access to the selected AMI tags to add them to the packer built AMI, so that I can trace more easily what was used to build it.

Terraform provides this feature, by exposing the `aws_ami` datasource, so I can search for a specific AMI, and use its tags in other resources.

I can work on the PR if this feature request would get accepted.

Thanks,

**Comment by SwampDragons** [comment]
Yeah, I'd gladly review a PR for this.
