### ISSUE TITLE
AWS credentials error with 1.2.1

### ISSUE THREAD

**Issue by rickyelqasem** [hashicorp/packer#6060]
- Packer version 1.2.1
- amazon-ebs
- Build 'amazon-ebs' errored: No valid credential sources found for AWS Builder
- doesn't happen in Packer version 1.1.3

      "type": "amazon-ebs",
      "access_key": "some_key",
      "secret_key": "some_secret",
      "ami_name": "atos-centos7-{{timestamp}}",
      "instance_type": "t2.micro",
      "region": "us-east-1",
      "source_ami": "ami-23aa8159",

**Comment by mwhooker** [comment]
Can you try building from master? I'm fairly certain this is fixed. Otherwise, a release will be coming shortly and you can test that

**Comment by rickyelqasem** [comment]
I tried a test to see if its isolated to the windows.exe version but i get the same results on the MacOS version too.

**Comment by mwhooker** [comment]
and is that built from master?

**Comment by rickyelqasem** [comment]
When you say that you do mean from the release version from your https://www.packer.io/downloads.html then yes.

**Comment by mwhooker** [comment]
We just released packer 1.2.2 which should fix this. If it doesn't, please open a new issue with debug output by setting `PACKER_LOG=1`.

**Comment by rickyelqasem** [comment]
1.2.2 works.. thx
