### ISSUE TITLE
Error sending boot command: VBoxManage error: VBoxManage: error: Machine 'macos' is not currently running

### ISSUE THREAD

**Issue by mcandre** [hashicorp/packer#6063]
Hello,

I have a need to reboot a VM into a Rescue Mode partition during packing, however packer mistakes the rebooting VM as an error state, `VBoxManage: error: Machine 'macos' is not currently running`, causing the packer build to fail when it should really wait for the VM to resume running and then continue the rest of the `boot_command`. I know that packer is generally good about this, as packer faithfully executes `boot_command` steps during prior reboots, and for many different guest systems and hypervisors. It's just this specific reboot late in my `boot_command` that triggers the error, not sure why.

In the future, could packer do a better job of waiting and retrying scancodes when the guest is detected as "not running", since it might actually be in the process of rebooting?

- Packer version from `packer version` Packer v1.2.2-dev with work in progress [patches](https://github.com/mcandre/packer/tree/super-keys-for-virtualbox) for Darwin guests in VirtualBox
- Host platform macOS 10.13 High Sierra

Example:

https://github.com/mcandre/packer-templates/blob/5002ac959f830e2743d4cf2f4e8fd9a40452777d/macos/macos.json

**Comment by rickard-von-essen** [comment]
IMHO: I think running reboot during `boot_command`  is misuse of the functionality. `boot_command` is not provisioning and I think there is only problem if you treat it that way. `boot_command` is a oneway communication with no feedback.

**Comment by mcandre** [comment]
`boot_command` is the only option for setting up this oarticular guest, and rebooting with SIP disabling is required just to start sshd.

Fortunately, the true source of the error appears to be an off by one error in the number of Down keys I was sending, navigating to the Shutdown command rather than Restart.
