### ISSUE TITLE
oracle-oci unknown configuration key: "user_data_file" 

### ISSUE THREAD

**Issue by jl98800** [hashicorp/packer#6070]
- Packer version from  packer --version
1.2.0

- Host platform:  Mac OS X

- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a gist https://gist.github.com  - coming soon.

- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your gist https://gist.github.com - also coming soon. 

Oracle OCI is a pretty new build type.  I keep getting this error when I try to packer build:

Errors validating build 'oracle-oci'. Failed to mapstructure Config: 1 error(s) occurred:

* unknown configuration key: "user_data_file"

Is this available for oracle-oci or can it be?  I need it to configure winrm during the build or I get this error:

==> oracle-oci: Waiting for WinRM to become available...
==> oracle-oci: Timeout waiting for WinRM.
==> oracle-oci: Terminated instance.
Build 'oracle-oci' errored: Timeout waiting for WinRM.

Or is there another way to do this in builders for oracle-oci type?

**Comment by SwampDragons** [comment]
Thanks for opening the issue! I'm sorry to say that this option doesn't currently exist for the oracle-oci builder, but we do have another issue open already which has requested this feature: https://github.com/hashicorp/packer/issues/5866.

I'm going to close this ticket as a duplicate and you can track implementation progress in #5866.
