### ISSUE TITLE
Refuse to run when attempting to shrink a qcow2 image

### ISSUE THREAD

**Issue by thedrow** [hashicorp/packer#6081]
When using the qemu builder and specifying a disk size that is smaller than the current disk size you get the following error:
```
qemu-img: qcow2 doesn't support shrinking images yet
```
We need to validate that the `disk_size` configuration option is not smaller than the current disk size if the `format` configuration option is set to qcow2 before proceeding to build the image from a disk image.

This can be done by:

1. running `qemu-img info image.qcow2 --output json`
2. Extracting the `actual-size` key from the command's output is the disk size in bytes.
3. Converting the `disk_size` configuration options to bytes and comparing the size.

**Comment by mwhooker** [comment]
sounds like a good addition. I don't think we can get to this, but if you wanted to give it a shot I'm happy to review or answer any questions you might have

**Comment by thedrow** [comment]
I'll probably get to it soon.

**Comment by thedrow** [comment]
@mwhooker Is there a utility function in the code base which converts MB to bytes?

**Comment by SwampDragons** [comment]
I think qcow2 is now supported because I can't reproduce this. If this is still an issue we can revisit it.

**Comment by thedrow** [comment]
> I think qcow2 is now supported because I can't reproduce this. If this is still an issue we can revisit it.

Yes, it does but only for certain versions of qemu.

**Comment by SwampDragons** [comment]
Do you know which version added support? We can probably to a quick version check.

**Comment by thedrow** [comment]
Unfortunately no. I no longer recall the version where it is supported.

**Comment by SwampDragons** [comment]
Couldn't figure it out from googling, so I cloned qemu to search git logs. It was added in v2.11.0
