### ISSUE TITLE
File extension truncated when filename <= 8 char when specified for floppy

### ISSUE THREAD

**Issue by dustyhorizon** [hashicorp/packer#6083]
When specifying dirs/files to be mounted as floppy in `floppy_dirs` in Windows-based builds, files that contain <= 8 characters in the filename are forced into the 8.3 filename styling. This breaks certain edge cases such as having a <= 8 char filename but ends with a `.psm1` extension; With this issue, the extension now becomes `.psm` which is invalid. Even though such cases are uncommon and there are workarounds for this e.g. using the file provisioner or rename such files so that it is > 8 characters and retain its file extension etc. it would be great for this to be fixed or at least to be highlighted in the docs.

Have not tested other scenarios (building Linux-based VMs etc.)

Running Packer 1.2.2 on Ubuntu, was using vmware-iso at the time.

**Comment by arizvisa** [comment]
Ftr, this issue is actually in go-fs and I think it might be at [go-fs/fat/short_name.go:104](../../../mitchellh/go-fs/blob/master/fat/short_name.go#L104) because it's the only place there's a `len` keyword and the length of 8.

**Comment by arizvisa** [comment]
Actually, it even looks like there's a similar issue from Mar 4, 2015.

mitchellh/go-fs#5

**Comment by arizvisa** [comment]
Hey @dustyhorizon, can you check to see if https://github.com/arizvisa/go-fs/tree/GH-5 fixes it?

If it does, then i'll make a PR in the go-fs project to get that shit taken care of..

**Comment by dustyhorizon** [comment]
@arizvisa the patch looks good, have fixed the issue that I was having. Thanks for the fix!

**Comment by arizvisa** [comment]
Cool. I'll create the PR over there in a sec then.

**Comment by arizvisa** [comment]
Ok. Once go-fs merges mitchellh/go-fs#14 then we will just need to sync go-fs to that version in packer.

**Comment by arizvisa** [comment]
@mwhooker, PR #6098 syncs go-fs (and includes your commits too) to fix this issue.
