### ISSUE TITLE
Get windows password not working for Packer backed instances

### ISSUE THREAD

**Issue by amarankit-srivastava** [hashicorp/packer#6086]
Hi All,
I am getting get-windows password (its saying like no password extraction allowed as it is created out of some custom AMI) for instance launched using AMI created out of packer. Please suggest me how to use WinRM settings or which Keypair/settings I need to pass. Urgent suggestions will be much appreciated.

Below is the quick JSON,

{
    "variables":
    {
        "name": "ami", 
        "version": "v1.0", 
        "source_amiv": "ami-3118fa4c",
        "aws_regionv": "us-east-1",
        "instance_typev": "t2.medium",
        "ssh_keypair_namev": "xxxx",   (I removed this and 'ssh_private_key_file' and tested as well- did not work though)
        "access_keyv": "XXXXXXXXXXXXXX",
        "secret_keyv": "XXXXXXXXXXXXXXXXXXXXXXXXX", 
        "subnet_idv": "subnet-xxxxxx",
        "vpc_idv": "vpc-xxxxxx",
        "ami_namev": "GOLDENWI2012R2v1.0"
        
    },
    "builders": 
    [
        {
            "type": "amazon-ebs", 
            "communicator": "winrm",
            "winrm_username": "Administrator",
            "user_data_file":"./win2012_ec2-userdata.ps1",
            "tags": {
                "Name": "WIN2012R2",
                "OS": "WIN2012",
                "OSVER": "R2"
            },
            "encrypt_boot": true,
            "winrm_use_ssl": true,
            "winrm_insecure": true,
            "winrm_username": "Administrator",
            "ssh_private_key_file": "c:/Users/xxxxxx/.ssh/aws-linuxkey",
            "access_key": "{{user `access_keyv`}}", 
            "secret_key": "{{user `secret_keyv`}}", 
            "region": "{{user `aws_regionv`}}",
            "source_ami": "{{user `source_amiv`}}",
            "instance_type": "{{user `instance_typev`}}",
            "ssh_keypair_name": "{{user `ssh_keypair_namev`}}",
            "ami_name": "{{user `ami_namev`}}",
            "subnet_id": "{{user `subnet_idv`}}",
            "vpc_id": "{{user `vpc_idv`}}",
            "ami_regions": [
                "us-east-1"
            ]
        }
    ],
    "provisioners": [ ]
}

Userdata- attached
[win2012_ec2-userdata.txt](https://github.com/hashicorp/packer/files/1862744/win2012_ec2-userdata.txt)

**Comment by rickard-von-essen** [comment]
Please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._
