### ISSUE TITLE
build azure image without data disk

### ISSUE THREAD

**Issue by freidenker** [hashicorp/packer#6090]
i want to build azure vm image with some data disks, but the packer looks like do not provide this feature yet. i know by now it could build azure image with os disk.

**Comment by boumenot** [comment]
Please read the documentation before opening an issue.  The Azure builder does support data disks or not, see [https://www.packer.io/docs/builders/azure.html#disk_additional_size](for details).  Support for data disk is available in the latest version of Packer (v1.2.2 or later).
