### ISSUE TITLE
vsphere post-processor password character escaping problem

### ISSUE THREAD

**Issue by AshleyByeUK** [hashicorp/packer#6091]
vsphere post-processor hangs on execution of `ovftool` with the following message and no indication in vSphere that a file is being uploaded:

```
2018/03/31 12:18:41 packer: 2018/03/31 12:18:41 Starting ovftool with parameters: --acceptAllEulas --name=packer-test --datastore=vsanDatastore --noSSLVerify=true --diskMode=thick --network=104-Guests /Users/ashley/Development/k8s/iso/builds/packer-test-vmware/packer-test.vmx vi://ashley.bye%40company.com:<password>@vc.outerrim.vsphere.company.net/Outer%20Rim/host/Outer%20Rim/Resources/Ashley-RP
```

If I run this manually the file uploads and I can see the new VM, a folder and upload progress straight away in vSphere:

```
ovftool --acceptAllEulas --name=packer-test --datastore=vsanDatastore --noSSLVerify=true --diskMode=thick --network=104-Guests /Users/ashley/Development/k8s/iso/builds/packer-test-vmware/packer-test.vmx vi://ashley.bye%40company.com:password%20spaces%20nonalpha%201%3F@vc.outerrim.vsphere.company.net/Outer%20Rim/host/Outer%20Rim/Resources/Ashley-RP
```

I had to escape the spaces in the datacenter and cluster names, which took a while to figure out. My vCenter password contains both spaces and non-alphanumeric characters, as the example above shows (not my real password). To get this to work with `ovftool` I needed to escape the spaces and non-alphanumeric characters in the password, e.g. `password spaces nonalpha 1?` becomes `password%20spaces%20nonalpha%201%3F`.

If I put a `%` sign in my email address in the packer variable it is escaped as `%25`. Given that packer is escaping characters in the email address (correctly so), I suspect that packer is also escaping the non-alphanumeric characters in the password. Since the spaces in the datacenter and cluster names are not being escaped, I also suspect that these are not being escaped in the password.

I wouldn't be surprised, although I can't say for certain, if packer is trying to escape my escape characters in the password, which would mean `password%20spaces%20nonalpha%201?` becomes `password%2520spaces%2520nonalpha%25201%3F`.

In the password variable, I've tried as many variations as I can think of:

```
password spaces nonalpha 1?
password spaces nonalpha 1%3F
\"password spaces nonalpha 1?\"
password%20spaces%20nonalpha%201?
password%20spaces%20nonalpha%201%3F
```

`Packer v1.2.2` on macOs 10.13.3.

**Comment by SwampDragons** [comment]
Take a look at this ticket and let me know if any of the discussion in there is helpful to you: https://github.com/hashicorp/packer/issues/5464

**Comment by AshleyByeUK** [comment]
I had seen that issue but couldn't find it when I posted. It's what got me thinking about escaping.

Having looked at that issue again, it says that spaces in the password are being replaced with `+` rather than `%20`.

From the vSphere post-processor [source](https://github.com/hashicorp/packer/blob/cfbe026134bc70b9d08ba63d829d479f51f417b2/post-processor/vsphere/post-processor.go#L113-L119):

```
password := url.QueryEscape(p.config.Password)
ovftool_uri := fmt.Sprintf("vi://%s:%s@%s/%s/host/%s",
	url.QueryEscape(p.config.Username),
	password,
	p.config.Host,
	p.config.Datacenter,
	p.config.Cluster)
```

The golang [source](https://golang.org/src/net/url/url.go?s=279:314#L259) for `url.QueryEscape` uses the `escape` func which based on my limited golang knowledge is indeed replacing spaces with `+` (which ties in with the comment in #5464):

```
func escape(s string, mode encoding) string {
	spaceCount, hexCount := 0, 0
	for i := 0; i < len(s); i++ {
		c := s[i]
		if shouldEscape(c, mode) {
			if c == ' ' && mode == encodeQueryComponent {
				spaceCount++
			} else {
				hexCount++
			}
		}
	}

	if spaceCount == 0 && hexCount == 0 {
		return s
	}

	t := make([]byte, len(s)+2*hexCount)
	j := 0
	for i := 0; i < len(s); i++ {
		switch c := s[i]; {
		case c == ' ' && mode == encodeQueryComponent:
			t[j] = '+'
			j++
		case shouldEscape(c, mode):
			t[j] = '%'
			t[j+1] = "0123456789ABCDEF"[c>>4]
			t[j+2] = "0123456789ABCDEF"[c&15]
			j += 3
		default:
			t[j] = s[i]
			j++
		}
	}
	return string(t)
}
```

If I change my password with `ovftool` so that I escape strings with a `+` instead of `%20`, like this:

```
ovftool \
  --acceptAllEulas \
  --name=packer-test \
  --datastore=vsanDatastore \
  --noSSLVerify=true \
  --diskMode=thick \
  --network=104-Guests \
  /Users/ashley/Development/k8s/iso/builds/packer-test-vmware/packer-test.vmx \
vi://ashley.bye%40company.com:password+spaces+nonalpha+1?@vc.outerrim.vsphere.company.net/Outer%20Rim/host/Outer%20Rim/Resources/Ashley-RP
```

Then `ovftool` throws the following error:

```
Error: Cannot parse locator: vi://ashley.bye%40company.com:password+spaces+nonalpha+1?@vc.outerrim.vsphere.company.net/Outer%20Rim/host/Outer%20Rim/Resources/Ashley-RP
Completed with errors
```

It's tricky to know exactly what error is being thrown by `ovftool` as Packer doesn't display its output when I run in debug mode and it just hangs trying to upload (I left it overnight and it was still trying in the morning). However, if I were going to hang my hat on something, the escaping is what my money would be on.

**Comment by AshleyByeUK** [comment]
It's probably also worth asking about the `vsphere-template` post-processor. The [source](https://github.com/hashicorp/packer/blob/cfbe026134bc70b9d08ba63d829d479f51f417b2/post-processor/vsphere-template/post-processor.go#L81) doesn't show any escaping but seems to leave this to `sdk.User = url.UserPassword(p.config.Username, p.config.Password)`. Are there going to be similar issues here too?

**Comment by SwampDragons** [comment]
Can you give me an example of how you're giving your password to Packer?  Without going too deep into the code, I feel like I remember from last time that the solution was to just hand it in unescaped; e.g. 

"password": "this is my password",

**Comment by SwampDragons** [comment]
Another option is that I can add a debug logline and build you a special binary that'll print the final formatted command so you can check it. Would this be something you'd be interested in?

**Comment by SwampDragons** [comment]
[packer.tar.gz](https://github.com/hashicorp/packer/files/1880856/packer.tar.gz)
This is a binary for OSX that will not sanitize the logs, so you will be able to see exactly what command, including password etc, is being passed to ovftool.

**Comment by arizvisa** [comment]
I just disassembled ovftool v4.2.0, and looked around for ovf.locator.parse (that error message). It looks like they're not decoding '+' as spaces as per the rfc and instead doing url-decoding lazily by only looking for '%'.

**Comment by arizvisa** [comment]
Looks like plugging that into a search engine also results in:
```
OVF Tool: Special Characters in URL Locators - SFlanders.net
sflanders.net/2013/02/25/ovf-tool-special-characters-in-url-locators/
```
Which mentions that the release guide mentions how one should encode special chars in OVF Tool's urls:

Encoding Special Characters in URL Locators
https://www.vmware.com/support/developer/ovf/ovf420/ovftool-420-userguide.pdf

**Comment by SwampDragons** [comment]
Oy, And there's this. Looks like we can't expect this to ever be fixed on the golang side: https://github.com/golang/go/issues/4013

**Comment by arizvisa** [comment]
I did some digging and it looks like net/url's PathEscape might do it, maybe?
https://golang.org/src/net/url/url.go?s=7512:7544#L265

Here's some tests:
https://play.golang.org/p/Jr0OsJHfeGl

**Comment by SwampDragons** [comment]
Made a quick hack: https://github.com/hashicorp/packer/pull/6110.  Binary for OSX is here: 
[packer.tar.gz](https://github.com/hashicorp/packer/files/1881007/packer.tar.gz)

@AshleyByeUK can you let me know if this one works for you?

**Comment by arizvisa** [comment]
Just ftr, the difference between QueryEscape and PathEscape is the mode parameter which handles the '+' character specially if its set to encodeQueryComponent (according to https://golang.org/src/net/url/url.go?s=7512:7544#L300)

QueryEscape replaces spaces with '+'.
```
func QueryEscape(s string) string {
	return escape(s, encodeQueryComponent)
}
```

PathEscape handles all non-printables and spaces the same.
```
func PathEscape(s string) string {
	return escape(s, encodePathSegment)
}
```

But, there's no guarantee that net/url PathEscape exists on older versions of Go and so your hack would probably be safer to remain backwards compat with versions of golang supported by packer.

**Comment by AshleyByeUK** [comment]
@SwampDragons that works like a charm - even hits the path so no need to escape there anymore either. Thanks :-D

**Comment by SwampDragons** [comment]
Can you clarify what you mean by "even hits the path"?  What was happening before?

**Comment by AshleyByeUK** [comment]
I was mistaken - the log entry and the terminal entry are different which confused me. I had previously been looking at the log entry which has:

`vi://ashley.bye@company.com:<password>@vc.outerrim.vsphere.company.net/Outer Rim/host/Outer Rim/Resources/Ashley-RP`

This time I was looking at the terminal which displays:

`vi://ashley.bye%40company.com@vc.outerrim.vsphere.company.net:443/Outer%20Rim/host/Outer%20Rim/Resources/Ashley-RP`

It threw me, but no change in behaviour, just where I was looking.

**Comment by SwampDragons** [comment]
Ok awesome. Was worried there would be a backwards-compatability breaking change that I wasn't prepared for.  Still trying to figure out the most elegant way to do this, but it'll be fixed one way or another in the next release; meanwhile you can use the binary I built you earlier, if it does everything you need.

**Comment by AshleyByeUK** [comment]
Awesome. Thanks for putting that together and I'll keep an eye out for the official update idc.
