### ISSUE TITLE
QEMU driver should accept image size as a string

### ISSUE THREAD

**Issue by thedrow** [hashicorp/packer#6092]
The `size` argument of `qemu-img convert` accepts the following values:

> 'k' or 'K' (kilobyte, 1024), 'M' (megabyte, 1024k), 'G' (gigabyte, 1024M),
>     'T' (terabyte, 1024G), 'P' (petabyte, 1024T) and 'E' (exabyte, 1024P)  are
>     supported. 'b' is ignored.

We should support the same convention instead of forcing the user to specify the size in MB. This will help workaround #6081 more easily.

**Comment by SwampDragons** [comment]
This seems like a good enhancement. The QEMU builder is a community-supported one, so we won't likely dedicate HashiCorp resources to implementing this, but I'll gladly review any PR you submit.

**Comment by anshulaa** [comment]
@SwampDragons I can pick it up 👍

**Comment by SwampDragons** [comment]
This was closed in #8320
