### ISSUE TITLE
Allow commands to be specified as an array in shell-local provisioner

### ISSUE THREAD

**Issue by dustyhorizon** [hashicorp/packer#6102]
It would be helpful to allow array inputs in shell-local provisioner similar to the 'inline' mode for the shell provisioner.

This would also 'allow multilines' (breaking up the command via arrays) and would look neater on templates I guess?

What do you guys think?

**Shell-local post-provisioner allows inline etc. I think it would make sense to have them with the same functions / features

**Comment by SwampDragons** [comment]
I like it; I've already got a PR that does a lot of work to bring the shell-local provisioner and post-processor more in line with one another, including in this way.  This is a good excuse for me to finish getting it ready for merge. If you want to take a look, it's here: https://github.com/hashicorp/packer/pull/5956

**Comment by dustyhorizon** [comment]
Wow thats great! Looking forward to it being merged haha!

**Comment by SwampDragons** [comment]
It's a big change so I'm taking my time with it, but I'm hopeful we'll get it in soon.
