### ISSUE TITLE
Allow users of the PowerShell provisioner to use service accounts for elevated_user

### ISSUE THREAD

**Issue by zanecodes** [hashicorp/packer#6104]
Certain applications may require an interactive session on Windows in order to function properly. WinRM commands are not run in an interactive session, and currently the only way to accomplish this is to run the application from a scheduled task as a service account such as the `SYSTEM` user.

One way to allow the user to do this could be to allow the `elevated_password` to be empty, and use the service account logon type if an empty string is passed. In order to schedule a task as the `SYSTEM` user, `RegisterTaskDefinition` should be passed a [logonType](https://msdn.microsoft.com/en-us/library/windows/desktop/aa382577) of [`5` (`TASK_LOGON_SERVICE_ACCOUNT`)](https://msdn.microsoft.com/en-us/library/windows/desktop/aa382075) and `password` of `$null`. Additionally, the `<LogonType>` tag should be omitted from the task definition xml. See https://github.com/WinRb/winrm-elevated/blob/master/lib/winrm-elevated/scripts/elevated_shell.ps1#L10.

**Comment by SwampDragons** [comment]
Do you have an idea of what needs to be changed with the elevated provisioner's XML file to support this? https://github.com/hashicorp/packer/blob/master/provisioner/powershell/elevated.go

**Comment by zanecodes** [comment]
Yeah, the example I posted in the winrm-elevated repository handles this pretty well. The only change to the xml should be excluding the `<LogonType>Password</LogonType>` tag when a service account is provided. Other than that, the password parameter in the call to `RegisterTaskDefinition` should be `$null` and the `logonType` should be `5` when a service account is provided. I can submit a pull request at some point in the next few days.

**Comment by SwampDragons** [comment]
That would be awesome!

**Comment by zanecodes** [comment]
So I'd really like to test my changes and make some contributions, but I can't get the project to build on Windows 10 with MINGW; `go generate .` just hangs forever.

**Comment by DanHam** [comment]
@SwampDragons @zanecodes I'm actually a Unix nerd(!!) and currently use OS X. However, I do have some Vagrant based Windows 2016 VM's that I could use to try and help out with.

@zanecodes This feature looks great. I took a look at your main GitHub page but couldn't see Packer. If you could fork and then push the branch with your changes then that would allow me to grab it. I can then see if I can get things going...
Additionally, if you have any sample Packer templates + scripts that you could use to test the functionality then please provide them as well!

**Comment by SwampDragons** [comment]
aw bummer, I was hoping since most of the PRs I've seen you work on were windows related you'd be a windows guy.  Guess it's time to put golang on my windows 10 vm and figure this out.

**Comment by DanHam** [comment]
> since most of the PRs I've seen you work on were windows related you'd be a windows guy

Yeah... I don't really know how that happened! I think I got upset with all the spludge that was being chucked out by the PowerShell provisioner at the time I was working on my Windows builds... and things kind of went on from there!

Like I said, still happy to lend a hand if required...

**Comment by Marcus-James-Adams** [comment]
Whilst I'm not a dev and can't contribute to the build testing of this, I would just like to add that this would be a really useful feature to have -as the lack of interactive on winrm does get in the way with some of our builds

**Comment by bodgit** [comment]
This looked reasonably trivial to implement and provides some useful functionality so I've opened #6972 with the necessary changes.
