### ISSUE TITLE
Feature: Provide a restart provisioner for other OS's

### ISSUE THREAD

**Issue by dhs-rec** [hashicorp/packer#6109]
Hi,

due to limitations in the Debian/Ubuntu installers I'm trying to setup Debian/Ubuntu boxes by booting into a [GRML Live Linux CD](https://grml.org/) and setting up the systems using [grml-debootstrap](https://grml.org/grml-debootstrap/) after configuring and mounting filesystems.

In "normal" installs with an installation CD/DVD, the system reboots after base installation and before running the first provisioner.

This doesn't work in my scenario, because the base installation is already done by a Shell provisioner. In order to execute other provisioners afterwards, I'd need to reboot into the installed system. But there's no restart provisioner for other OS's than Windows...

**Comment by SwampDragons** [comment]
Hi, thanks for opening an issue.  Have you taken a look at the https://www.packer.io/docs/provisioners/shell.html#handling-reboots section of the shell provisioner docs?  What about it does not meet your needs?

**Comment by marema31** [comment]
Hello,

If you are able to compile yourself packer, you can use the posix-restart provisionner I've proposed #4555, it will not be integrated in the core but seems to correspond to your issue.

**Comment by SwampDragons** [comment]
On further thought, I think I'm going to close this issue because I'm 99% sure that the stuff covered in the handling-reboots docs will meet your needs.  If that's wrong, please let me know. :)

**Comment by dhs-rec** [comment]
OK, wasn't aware of this. thanks.
