### ISSUE TITLE
Packer Azure failed to continue running the template after the PowerShell domain join command was executed.

### ISSUE THREAD

**Issue by ngeegoh** [hashicorp/packer#6116]
Packer failed to continue running the template after the PowerShell domain join command was executed. 

As I need to add the temporary VM which is generated by Packer during the build into the domain, I have added a Domain join PowerShell script into the template which looks like this:

`$domain = "xxxxx"
$password = "xxxxx" | ConvertTo-SecureString -asPlainText -Force
$username = "$domain\aaa.bbb" 
$credential = New-Object System.Management.Automation.PSCredential($username,$password)
Add-Computer -DomainName $domain -Credential $credential` 

and then in the provisioners part of the template, I have placed the domain join script before the windows-restart command. 

 
` 
{
      "type": "powershell",
      "script": "PackerUpload/join_domain.ps1"
    },
    {
      "type": "windows-restart",
      "restart_check_command": "powershell -command \"& {Write-Output 'restarted.'}\""
   }
`

Technically, Packer is supposed to restart and continue the running other components in the template. However, I don't know why the packer build failed to restart or even run another script (I did attempt to replace the windows-restart with another PowerShell script, but it also failed to run). I might suspect that the domain join script has somehow disconnected the temporary VM with Packer or maybe Packer failed to reconnect the VM after the domain join script had been successfully executed. I guess this may be a bug in Packer. I have attached the debug_log below. There is no problem if I run other PowerShell scripts (not domain join one), the connection is fine and windows-restart works fine. Thank you.   

Info:
- Packer version from `1.2.2` and `1.2.1`
- Host platform:  Windows10 
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  https://gist.github.com/ngeegoh/6ad9151990601ccb2899c7e5bf0e8c7f

**Comment by mwhooker** [comment]
to quote from #5467 

>  It looks as though you have the now deprecated packer-community/packer-windows-plugins installed. These were actually incorporated in to Packer way back in version 8.0 and have likely undergone a large number of changes since then.

> I would suggest checking if you have these plugins installed and, if you have, uninstall them.
Let us know if that does the trick.

Once you've done that, if you still have an error, please create a new ticket with the new debug log

**Comment by mwhooker** [comment]
I don't see any errors in the log. is that the whole thing?
