### ISSUE TITLE
Allow non 0 exit codes for shell/windows-shell provisioners

### ISSUE THREAD

**Issue by lmayorga1980** [hashicorp/packer#6120]
I noticed that the `powershell` provisioner already has this feature https://www.packer.io/docs/provisioners/powershell.html#valid_exit_codes Would it be possible to added to the shell/windows-shell provisioners?

**Comment by azr** [comment]
Hello there, I created a PR to fix this in https://github.com/hashicorp/packer/pull/7385, please tell me if it's enough for you. 🙂
