### ISSUE TITLE
Add ability for outputs

### ISSUE THREAD

**Issue by myoung34** [hashicorp/packer#6123]
I like to build my AMI, then test it with test-kitchen then promote it, etc.

The problem with packer has always been the hackery of getting the machine ID.

All examples show using `| tee ` to parse it then find the ID.

It would be great if it just had a native way of using outputs similar to how [terraform does it](https://www.terraform.io/docs/configuration/outputs.html) that way I could easily chain builds without trying to hope my search/parse is correct.

**Comment by rickard-von-essen** [comment]
IMHO this is covered by the `manifest` post-processor.

**Comment by SwampDragons** [comment]
Rickard's right -- see the docs [here](https://www.packer.io/docs/post-processors/manifest.html) for more details on how to implement it. For amazon, your manifest.json will look something like this: 

```
    {
      "name": "amazon-ebs",
      "builder_type": "amazon-ebs",
      "build_time": 1523374117,
      "files": null,
      "artifact_id": "us-east-2:ami-e8a4948d",
      "packer_run_uuid": "b88fd4df-6b28-3e1c-0082-edc6c8fda13e"
    }
```

I believe "artifact_id" is what you're looking for.

**Comment by myoung34** [comment]
Thanks, I was actually testing this to see if I could close the ticket
