### ISSUE TITLE
azure-setup.sh on MacOS High Sierra

### ISSUE THREAD

**Issue by andrew-best-diaxion** [hashicorp/packer#6127]
- MacOS High Sierra 10.13.4

- packer version: 1.2.2 (installed via Brew)
- latest azure CLI via Brew
- jq version 1.5 from Brew

Steps to reproduce:
- Download azure-setup.sh https://raw.githubusercontent.com/hashicorp/packer/master/contrib/azure-setup.sh
- Fix perms
- Run script to test requirements `./azure-setup.sh requirements`
```
BARMIX:terraform-soe-r1 abest$ ./azure-setup.sh requirements
Found azure-cli version: azure-cli (2.0.31)

acr (2.0.23)
acs (2.0.31)
advisor (0.5.1)
appservice (0.1.31)
backup (1.1.1)
batch (3.2.0)
batchai (0.2.0)
billing (0.1.8)
cdn (0.0.14)
cloud (2.0.13)
cognitiveservices (0.1.12)
command-modules-nspkg (2.0.1)
configure (2.0.15)
consumption (0.3.0)
container (0.1.22)
core (2.0.31)
cosmosdb (0.1.20)
dla (0.0.19)
dls (0.0.21)
eventgrid (0.1.12)
eventhubs (0.1.2)
extension (0.0.12)
feedback (2.1.1)
find (0.2.9)
interactive (0.3.19)
iot (0.1.19)
keyvault (2.0.21)
lab (0.0.21)
monitor (0.1.5)
network (2.0.28)
nspkg (3.0.2)
profile (2.0.22)
rdbms (0.2.1)
redis (0.2.12)
reservations (0.1.2)
resource (2.0.27)
role (2.0.22)
servicebus (0.1.2)
servicefabric (0.0.12)
sql (2.0.25)
storage (2.0.31)
vm (2.0.30)

Python location '/usr/local/opt/python/bin/python3.6'
Extensions directory '/Users/abest/.azure/cliextensions'

Python (Darwin) 3.6.5 (default, Mar 30 2018, 06:41:53) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]

Legal docs and information: aka.ms/AzureCliLegal
Found jq version: jq-1.5
```

- run `azure-setup.sh setup`
- Open https://microsoft.com/devicelogin in fresh clean incognito window
- login with Azure user AAD credentials and auth successfully.
- CloudName|IsDefault etc information is output.
- Enter Subscription ID and press enter.
- jq outputs `parse error: Invalid numeric literal at line 1, column 5`

Alternatively re-run the steps and press enter without entering the subscription ID. Same error results.

Unsure how to proceed from here.

**Comment by andrew-best-diaxion** [comment]
Hi @boumenot thank you for following up.

I've worked out the root cause of the problem.

My `~/.azure/config` had the following setting:

```
...
[core]
...
output = table
...
```

I changed it to `output = json` and amazingly it all now works.

PR  #6130 created to add a new check to the azure-setup.sh

**Comment by SwampDragons** [comment]
Looks like this was closed via 6137
