### ISSUE TITLE
 parallels 13 can't be used for creating box

### ISSUE THREAD

**Issue by tsouhaieb** [hashicorp/packer#6128]
recently i tried to create a box using packer, but it reported to me that only parallels 11, 10 and 9 is supported, i'm using parallels 13, 
it report to me 

```
Build 'parallels-iso' errored: Failed creating Parallels driver: Unable to initialize any driver. Supported Parallels Desktop versions: 11, 10, 9
```

i checked under *packer/builder/parallels/common* folder, the last driver that is supported was 11 *driver_11.go* and the *driver.go* file in the same folder,  there is ```latestDriver := 11```
even parallels 12 is not supported which have been reported as added in [#3673](https://github.com/hashicorp/packer/pull/3673)

packer version: 1.2.2
Host: OSX sierra

**Comment by rickard-von-essen** [comment]
Please [gist](https://gist.github.com/) a full debug log from `PACKER_LOG=1 packer build template.json`.

**Comment by rickard-von-essen** [comment]
Most likely you have a broken build. Remove your current install directory and reinstall from [packer.io/downloads](https://www.packer.io/downloads.html). _Be sure to read the [**note** about upgrading from < 0.9.0.](https://github.com/hashicorp/packer/commit/1994793126f948dd99c8acdd35f999df0c6ab342)_

**Comment by rickard-von-essen** [comment]
Packer will check the version and use the driver for PD 11 if you have 11 or later.

**Comment by tsouhaieb** [comment]
i created a ubuntu18 image, just fine, thanks for the reply and the help
