### ISSUE TITLE
oracle-oci Failed to load private key permission denied

### ISSUE THREAD

**Issue by jl98800** [hashicorp/packer#6133]
- Packer version from `packer version`  1.2.0
- Host platform  ubuntu 16.04
- Debug log output from `PACKER_LOG=1 packer build template.json`.

Errors validating build 'oracle-oci'. Failed to load private key /var/lib/jenkins/.hiddendir/private_key.pem : open /var/lib/jenkins/.hiddendir/private_key.pem: permission denied
packer validate failed!, exiting...
Build step 'Execute shell' marked build as failure
Finished: FAILURE

oracle-oci enforces permissions on private keys. 
WARNING: Permissions on /var/lib/jenkins/.hiddendir/private_key.pem are too open. To fix this please execute the following command: oci setup repair-file-permissions --file /var/lib/jenkins/.hiddendir/private_key.pem 
  
The packer build is successful when everyone can read the private key.  Packer validate fails if permissions are any less.

**Comment by SwampDragons** [comment]
Two questions for you. 1) does that oracle-oci enforcement actually fail anything, or does it just emit the warning?  2) what permissions does it say it requires? You may have to add your Packer-running user to a group that's allowed to see those keys. Or, if Packer is the only tool that uses the key.

**Comment by jl98800** [comment]
Hi,
1.  The oracle-oci enforcement is just a warning. It won't fail running the oci cli.
2.  Permissions should be 0600 on the private key.

We have a user that runs the packer job and that user owns the private key

**Comment by jl98800** [comment]
Hi,
1.  The oracle-oci enforcement is just a warning. It won't fail running the oci cli.
2.  Permissions should be 0600 on the private key.

We have a user that runs the packer job and that user owns the private key

**Comment by SwampDragons** [comment]
I can't reproduce this; when I provide packer with a key with 0600 permissions I'm able to validate and build with no problems.

**Comment by jl98800** [comment]
Is this an oracle-oci private key in PEM format?  Are you running the packer build from the command line? Can you create this packer build in Jenkins and reproduce the validation failure?

Thanks

**Comment by jl98800** [comment]
/usr/bin/md5sum: /var/lib/jenkins/.hiddendir/private_key.pem: Permission denied

When permissions are set to go+r on the private key I see the jenkins user is executing the packer build:
jenkins+ 10455 10444  0 20:57 ?        00:00:00 /usr/local/bin/packer build oci/oracle/oracle_74.json
