### ISSUE TITLE
Powershell provisioner over Microsoft port of OpenSSH fails since Packer v1.2.0

### ISSUE THREAD

**Issue by jen20** [hashicorp/packer#6135]
Using Packer `master (fe8697ad4)` (but also the latest release), it is quite easy to reproduce #5963, so there must be some additional edge cases here not dealt with when that was closed.

Some importants facts:
- Code for a full repro is [here][repo].
- Provisioning a Windows instance using SSH - the userdata script on the instance installs the Microsoft port of OpenSSH and reboots.
- This template works with Packer v1.1.3, however as in #5963 has failed with all subsequent releases, and fails on master. Provisioning fails with recent versions of Packer with this output:
```
Build 'amazon-ebs' errored: Error processing command: Error uploading ps script containing env vars: test : The term 'test' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path
is correct and try again.
At line:1 char:1
+ test -d ${env:SYSTEMROOT}/Temp/packer-env-vars-5ad24f56-a695-1bc3-e29 ...
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (test:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

[repo]: https://github.com/jen20/packer-aws-windows-ssh

**Comment by rickard-von-essen** [comment]
This should be fixed by #6124

**Comment by DanHam** [comment]
@jen20 If you would like to test I've pushed my changes (combined with #6124) to a branch on my fork of Packer [HERE](https://github.com/DanHam/packer/tree/pstest-and-remove_dir_test)

**Comment by SwampDragons** [comment]
@DanHam I just merged #6124; How about you rebase on master and make a PR for me?

**Comment by DanHam** [comment]
@SwampDragons Great! Will do.

**Comment by jen20** [comment]
I'll build and test this later this evening. Thanks for the various pull requests, and sorry I didn't have time to investigate this myself!

**Comment by DanHam** [comment]
@jen20 See #6160

**Comment by DanHam** [comment]
@SwampDragons Do you think we could get #6160 in for 1.2.3?
