### ISSUE TITLE
Request: Support AdditionalDiskSize for qemu builder

### ISSUE THREAD

**Issue by dcode** [hashicorp/packer#6139]
Several of the builders provide the `AdditionalDiskSize` option, but this is lacking from the `qemu` builder (also virtualbox, but my immediate need is qemu). I know that probably the most common use-case of qemu is to just distribute a qcow2 image, but I want to create a virtual appliance on both KVM and VMware platforms. The appliance has the primary OS-level disk, and a second data disk.

This can be implemented with the `vmware-iso` builder by using the `AdditionalDiskSize` option. The problem is that to make this work for qemu, I have to create a wrapper script and use the `qemuargs` to hack it together or I just abandon the qemu support.

I'm basing my CentOS 7 build off the bento build scripts. In order to get a second disk working, I can specify that in the kickstart. Without qemu support for secondary disks, I'd have to create a distinct kickstart for the different use-cases. This makes maintenance of using packer a big hassle.

I think the user interface for `AdditionalDiskSize` is great. It should be a standard option across all builders that support those features.

**Comment by dcode** [comment]
Sorry...the `AdditionalDiskSize` is the internal golang variable. The vmware-iso option is `disk_additional_size`.

**Comment by SwampDragons** [comment]
This seems like a good idea; QEMU is one of our community-supported builders, so if you want to see this feature the best way to get it is to implement it yourself. I'd gladly provide some guidance if you're interested in making a PR.
