### ISSUE TITLE
WinRm Communicator times out without winrm_host setting

### ISSUE THREAD

**Issue by DaveDingle75** [hashicorp/packer#6140]
- Packer version: 1.2.2
- Windows 7 VM running on ESXi v5.0
- JSON file, WinRM config file and PackerLog here: https://gist.github.com/DaveDingle75/3d8e91bfd7c00f5ec35e521c56fbacc2

I have been conversing with @SwampDragons over on the Packer Google Group around this issue (https://groups.google.com/forum/#!topic/packer-tool/QbLplly7OBk).

Simply put, unless I specify the 'winrm_host' setting in my JSON file, Packer doesn't connect to my VM.  I can RDP to the VM on TCP 5985 so I know the VM is listening and Event View on the VM backs this up.

If any further info is required, please let me know.

Thanks!

**Comment by sg071017** [comment]
I use packer 1.2.1 on hyper v
Even if I set the winrm_host explicitly in the template, the packer will still use the ipaddress of the remote VM to winrm into..I want the packer to use the hostname but it will not.
Same issue!!

**Comment by zxiiro** [comment]
Can confirm using packer 1.2.3 according to debug logs even with the winrm_host setting packer uses the ip of the system instead of what's defined. It seems like winrm_host setting is ignored?

**Comment by LouisHacklaender** [comment]
As discussed with SwampDragons on the [packer forum](https://discuss.hashicorp.com/t/winrm-host-setting-ignored/20774/4), I am adding a rough [example packer script](https://gist.github.com/LouisHacklaender/b3c970a32709cd1e9cd104bf9ddb4988) to this issue.

In my case, the Packer WinRM Communicator fails to connect when the winrm_host option is not 127.0.0.1 and the connection should be established via a VirtualBox host-only adapter. Manually connecting with a small python script using pywinrm works fine. Also, connecting via a NAT adapter and IP 127.0.0.1 works fine, too.

Some background: the floppy files autounattend.xml manages the Windows10 installation. The [enable_win_rm.ps1 script](https://gist.github.com/LouisHacklaender/540458f85d02e4c4a27ab905ffb90d20) manages basic WinRM configuration on the virtual machine. As already mentioned above, the WinRM connection works manually, so the Windows/WinRM configuration should not be the problem.

**Comment by SwampDragons** [comment]
I think this is actually two issues -- Looking into the first two years late, I think the issue there was an outdated version of esxcli on the user's esx machine. The newer issues are the _opposite_  -- winrm_host wasn't being respected in certain builders. The first can be fixed with a software upgrade. I think the second is solved with the linked Pr.

**Comment by SwampDragons** [comment]
@LouisHacklaender I have test builds available for you at https://app.circleci.com/pipelines/github/hashicorp/packer/9577/workflows/12706f7c-c3c0-4d76-99bf-c4b788e980eb/jobs/114823/artifacts -- I think that setting winrm_host and setting skip_nat_mapping should solve your issue.
