### ISSUE TITLE
Unknown region alicloud - ap-southeast-5

### ISSUE THREAD

**Issue by LieAlbertTriAdrian** [hashicorp/packer#6149]
- Packer version 1.2.2
- Mac OS

 I got 
```
Errors validating build 'packer_redis'. 1 error(s) occurred:

* Unknown alicloud region: ap-southeast-5
```
when trying to run `packer validate base.json` for creating image in alicloud with region ap-southeast-5, but actually the region is stated here https://github.com/denverdino/aliyungo/blob/master/common/regions.go#L21

**Comment by LieAlbertTriAdrian** [comment]
No worries. I found out the problem

**Comment by LieAlbertTriAdrian** [comment]
The problem is because the version of aliyungo common used is not updated, so it's still using the old region list 

There is no ap-southeast-5 https://github.com/hashicorp/packer/blob/master/vendor/github.com/denverdino/aliyungo/common/regions.go#L20

The version is not updated in vendor.json
https://github.com/hashicorp/packer/blob/master/vendor/vendor.json#L608

**Comment by adinb** [comment]
I've updated the SDK to latest version taken from `master` here: #6154

**Comment by LieAlbertTriAdrian** [comment]
Sure, I submitted PR for this together with test result @mwhooker @zhuzhih2017 here 

https://github.com/hashicorp/packer/pull/6157
