### ISSUE TITLE
Unknown "User (you) cancelled the installation" errors

### ISSUE THREAD

**Issue by sc250024** [hashicorp/packer#6156]
Greetings,

I'm having issues with Packer installing Chocolately packages. I've also opened an equivalent issue in the Chocolately repository (https://github.com/chocolatey/chocolatey-coreteampackages/issues/1002), but I also wanted to open an issue here because I think it's more Packer related. The reason I think so is because running the problematic `choco` command via a GUI in Windows Server 2012 R2 actually works. It's only when I run the command in Packer that I get a failed build.

In short, when running the command:

```
choco install -y dotnetcore-runtime
```

Packer throws a `User (you) cancelled the installation` error, and then spits out the following Chocolately related messages:

```
amazon-ebs: Failures
amazon-ebs:  - kb3035131 (exited 5) - Error while running 'C:\ProgramData\chocolatey\lib\KB3035131\Tools\ChocolateyInstall.ps1'.
amazon-ebs:  See log for details.
```

```
amazon-ebs: Installing KB3035131...
amazon-ebs: WARNING: User (you) cancelled the installation.
amazon-ebs: WARNING: Update KB3035131 installation failed (exit code 5).
amazon-ebs: WARNING: More details may be found in the installation log (C:\Users\Administrator\AppData\Local\Temp\chocolatey\KB3035131.Install.evt) or the system CBS log (C:\Windows\Logs\CBS\CBS.log).
amazon-ebs: ERROR: Update KB3035131 installation failed (exit code 5).
amazon-ebs: The install of kb3035131 was NOT successful.
amazon-ebs: Error while running 'C:\ProgramData\chocolatey\lib\KB3035131\Tools\ChocolateyInstall.ps1'.
amazon-ebs:  See log for details.
```

Packer version: 1.2.2
Host platform: AWS

Example Packer template, debug log, and AWS bootstrap config are all included in this gist: https://gist.github.com/sc250024/fede4468306417c9cdee5e2702a6cb09

**Comment by DanHam** [comment]
This looks like an issue that has been seen before for the .Net Chocolatey package - see [HERE](https://github.com/dotnet/core/issues/1123). Although it was ultimately decided this issue was raised in the wrong place (it should have been raised with the Chocolatey package maintainers [HERE](https://chocolatey.org/packages/dotnetcore-sdk)) the discussion that follows seems to suggest that it's the Chocolatey package that's causing the issue.

**Comment by sc250024** [comment]
@DanHam Thanks for the reply. For anyone experiencing this, I found a solution:

```
    "provisioners": [
        {
            "type": "powershell",
            "elevated_user": "Administrator",
            "elevated_password": "{{ .WinRMPassword }}",
            "inline": [
                "Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))",
                "choco install -y dotnetcore-runtime"
            ]
        }
    ]
```

Simply run the commands with the `elevated_` tags I have above, and that does the trick. Seems fairly obvious now, but definitely wasn't at the time 😄

**Comment by spuder** [comment]
I have also been experiencing this. Windows server 2016 core and 2016 gui work fine, but 2012 exits with exit code 5. 

The reason why this fails on some and not others is because the chocolatey package depends on windows update KB2919442 which you can't install without elevated credentials. 

```
    {
      "type": "powershell",
      "inline": ["choco install dotnetfx --verison 4.7.2 --verbose -y"],
      "valid_exit_codes": [0,3010],
      "elevated_user": "vagrant",
      "elevated_password": "vagrant"
    },
    {
      "type": "powershell",
      "inline": ["choco install dotnet4.7.2 --verbose -y"],
      "valid_exit_codes": [0,3010],
      "elevated_user": "vagrant",
      "elevated_password": "vagrant"
    },
```
