### ISSUE TITLE
Feature Request - AzureRM Ability to use MSI for Auth

### ISSUE THREAD

**Issue by tomasquith** [hashicorp/packer#6161]
Hi,

I've been looking into Azure Managed Service Identity recently, Terraform supports this - allowing us to authenticate from our build machines running in Azure. https://www.terraform.io/docs/providers/azurerm/authenticating_via_msi.html

It would be nice if Packer supported the same means of authentication rather than having to export env vars or pass creds in.

**Comment by guitarrapc** [comment]
It is really useful feature, that Azure Authentications are dynamically moving to MSI. I also hope Packer supports this feature, too!

**Comment by bgoykhman** [comment]
I surely hope Packer will add this feature. We are building image in Azure and are moving away from using service principals in favor of MSI.

**Comment by karunrg** [comment]
Yes, Security is highly concerned now building anything in the Cloud, this feature really helps us to use Packer to build Images in Azure

**Comment by azr** [comment]
Howdy @boumenot will you have bandwidth for this one ?
Otherwise someone from the Packer team will probably start on it soonish 🙂

**Comment by boumenot** [comment]
Thank you for the ping!  Please do.  I am currently knee deep in other things at the moment.

**Comment by azr** [comment]
Okay then I'm looking into it now 🙂

**Comment by azr** [comment]
Okay I think I have it working in #6982 can someone please check that it work for their use case ?

Not entirely sure I cover everything correctly here 🙂

**Comment by boumenot** [comment]
Nice job!  It isn't easy to start something like this from scratch, and figure out where to insert yourself.

**Comment by BenMitchell1979** [comment]
Does this 'fix' allow us to pass in an existing Managed Id that already has been added to resources for authentication?
