### ISSUE TITLE
request: support zone availability/resiliency for azure builder

### ISSUE THREAD

**Issue by surlypants** [hashicorp/packer#6163]
Request to enable (or disable per default) "Zone Resiliency" (per availability zones) for Azure builder.

**Comment by riezebosch** [comment]
I'm digging through the sources but having a hard time finding out where the capture template gets constructed.

Already created an managed image from VM in the Azure portal with 'zone resiliency' enabled so got the template example here:

```
    {
      "type": "Microsoft.Compute/images",
      "name": "[parameters('images_small_vm_image_20181109115115_name')]",
      "apiVersion": "2018-06-01",
      "location": "northeurope",
      "scale": null,
      "properties": {
        "sourceVirtualMachine": {
          "id": "[parameters('images_small_vm_image_20181109115115_id')]"
        },
        "storageProfile": {
          "osDisk": {
            "osType": "Linux",
            "osState": "Generalized",
            "diskSizeGB": 30,
            "managedDisk": {
              "id": "[parameters('images_small_vm_image_20181109115115_id_1')]"
            },
            "caching": "ReadWrite",
            "storageAccountType": "Standard_LRS"
          },
          "dataDisks": [],
          "zoneResilient": true
        }
      },
      "dependsOn": []
    },
```

**Comment by boumenot** [comment]
Is [this](https://github.com/hashicorp/packer/blob/master/builder/azure/common/template/template_builder.go#L464-L622) what you are looking for?  This is the base template used to deploy the VM that is captured.  The template is [instantiated](https://github.com/hashicorp/packer/blob/master/builder/azure/arm/template_factory.go#L32), and changed based on settings.

**Comment by riezebosch** [comment]
This is the template for creating the VM I presume and there is a likewise template for creating the managed image from this VM at the end of the build? But probably I can figure it out right now. Thanks!
