### ISSUE TITLE
Powershell Provision hangsw forever when powershell on remote machine promprs for user input.

### ISSUE THREAD

**Issue by AntonChernysh** [hashicorp/packer#6175]
Packer Windows PowerShell provisioner hangs forever when powershell on remote machine propmts for user input.
- Packer v1.2.2
- MacOS (Doesn't matter)
- No debug, no logs, console hanging forever
- Provisioner:
https://gist.github.com/AntonChernysh/6964cca6c6c4ebe5bf37e3aae65e3b84

**Comment by SwampDragons** [comment]
This is definitely Packer's behavior, but I'm curious as to what you think the correct behavior is? Packer never returns because your script never returns.

**Comment by SwampDragons** [comment]
I thought about this a little overnight. It's a really cool idea, but ultimately something I don't think it makes sense for us to support; I believe this kind of insight requires knowledge about the guest operating system which Packer intentionally doesn't have.

Thanks for opening, and let us know if you have any other thoughts for improvements.

**Comment by matt-richardson** [comment]
I think this could be implemented rather easily. PowerShell has a [command line argument](https://docs.microsoft.com/en-us/powershell/scripting/core-powershell/console/powershell.exe-command-line-help?view=powershell-6) `-NonInteractive`, which would give this behaviour. PowerShell throws an exception if a cmdlet tries to read input.

**Comment by SwampDragons** [comment]
Hmm. I tried this out using by just adding the -NonInteractive flag into the default execute_command and providing it through my config. `"execute_command": "powershell -NonInteractive -executionpolicy bypass \"& { if (Test-Path variable:global:ProgressPreference){$ProgressPreference='SilentlyContinue'};. {{.Vars}}; &'{{.Path}}';exit $LastExitCode }\"",` and it did fail out of the powershell call, but it did not fail the script; it looks like it returned without an error code, so the provisioner continued to run.

**Comment by matt-richardson** [comment]
`$LastExitCode` is "helpfully" the last exit code of the external app that powershell ran. It doesn't reflect whether there were any errors or not. So, according to normal powershell semantics, this behaviour is correct. (Its maddening and wrong that powershell does this but what can you do?)

**Comment by SwampDragons** [comment]
Is there a way for us to know that this has errored? If not, we'll be silently failing which I'm not at all a fan of.

**Comment by matt-richardson** [comment]
About the only solution is wrapping the inline script in a try/catch, and exit in the catch block.

You cold also potentially set `$ErrorActionPreference` to `Stop` - it may have unexpected ramifications.

**Comment by SwampDragons** [comment]
Hmm. Okay. I think this brings me back to my initial feeling; this isn't an obvious default to me and should probably be handled by users changing the execute_command option to suit their specific needs.

**Comment by AntonChernysh** [comment]
If we talk about execute_command here's single line command that works fine:
"Powershell -NonInteractive -executionpolicy bypass -command Set-Service"
It throws an error and exist PS process.
