### ISSUE TITLE
filepath.[Dir|Base|ToSlash] behave differently depending on platform and path format

### ISSUE THREAD

**Issue by DanHam** [hashicorp/packer#6188]
`filepath.Dir`, `filepath.Base`, and `filepath.ToSlash` behave differently depending on the platform they are used on and path formats fed to them e.g. forward or back slash separated paths. This is because they ultimately use `os.PathSeparator` to decide on how the provided path string should be split or manipulated. Clearly `os.PathSeparator` is different between platforms.

The basic problem can be demonstrated using [this script](https://gist.github.com/DanHam/449fc0bce0e5f33b6da3691baba11389)

On Windows this results in the following:
```
OS is windows
Path separator is: \

Forward path is C:/Windows/Temp/forward.txt
filepath.Dir(`C:/Windows/Temp/forward.txt`) gives: C:\Windows\Temp
filepath.Base(`C:/Windows/Temp/forward.txt`) gives: forward.txt

Forward path with spaces is C:/Windows/Temp/forward\ with\ space.txt
filepath.Dir(`C:/Windows/Temp/forward\ with\ space.txt`) gives: C:\Windows\Temp\forward\ with
filepath.Base(`C:/Windows/Temp/forward\ with\ space.txt`) gives:  space.txt

Backward path is C:\Windows\Temp\backward.txt
filepath.Dir(`C:\Windows\Temp\backward.txt`) gives: C:\Windows\Temp
filepath.Base(`C:\Windows\Temp\backward.txt`) gives: backward.txt

Converting the backward path with filepath.ToSlash(`C:\Windows\Temp\backward.txt`) gives: C:/Windows/Temp/backward.txt
For the converted backward path filepath.Dir(`C:/Windows/Temp/backward.txt`) gives C:\Windows\Temp
For the converted backward path filepath.Base(`C:/Windows/Temp/backward.txt`) gives backward.txt
```

On Linux/OS X this results in the following:

```
OS is linux
Path separator is: /

Forward path is C:/Windows/Temp/forward.txt
filepath.Dir(`C:/Windows/Temp/forward.txt`) gives: C:/Windows/Temp
filepath.Base(`C:/Windows/Temp/forward.txt`) gives: forward.txt

Forward path with spaces is C:/Windows/Temp/forward\ with\ space.txt
filepath.Dir(`C:/Windows/Temp/forward\ with\ space.txt`) gives: C:/Windows/Temp
filepath.Base(`C:/Windows/Temp/forward\ with\ space.txt`) gives: forward\ with\ space.txt

Backward path is C:\Windows\Temp\backward.txt
filepath.Dir(`C:\Windows\Temp\backward.txt`) gives: .
filepath.Base(`C:\Windows\Temp\backward.txt`) gives: C:\Windows\Temp\backward.txt

Converting the backward path with filepath.ToSlash(`C:\Windows\Temp\backward.txt`) gives: C:\Windows\Temp\backward.txt
For the converted backward path filepath.Dir(`C:\Windows\Temp\backward.txt`) gives .
For the converted backward path filepath.Base(`C:\Windows\Temp\backward.txt`) gives C:\Windows\Temp\backward.txt
```

### Path formatted with forward slashes:

* On Linux/OS X `filepath.Base` and `filepath.Dir` work as expected
* On Windows `filepath.Dir` converts the forward slashes to backward slashes. filepath.Base works as expected

### Path formatted with forward slashes including backslash escaped spaces

* On Linux/OS X `filepath.Base` and `filepath.Dir` work as expected
* On Windows since the path separator is `\`, `filepath.Dir` and `filepath.Base` split the path string on the last backslash which is not correct

### Path formatted with backward slashes

* On Linux/OS X since the path separator is `/`, `filepath.Base` returns the entire path rather than the filename. `filepath.Dir` returns a dot (`.`) as it cannot find any occurrences of the expected path separator in the string
* On Windows `filepath.Dir` and `filepath.Base` work as expected

### 'Converting' paths formatted with backward slashes to forward slashes

* On Linux/OS X since the path separator is `/`, `filepath.ToSlash` is a noop and the entire path is unchanged
* On Windows `filepath.ToSlash` works as expected. However, note that any `filepath.Dir` on the converted path will be affected by the issue noted above for paths formatted with forward slashes - namely that the forward slashes will be converted again to backward slashes. Again `filepath.Base` should work as expected for the converted path string.

## Example Issue

filepath.Dir, filepath.Base and filepath.ToSlash have been used throughout the code base. The use [here](https://github.com/hashicorp/packer/blob/master/communicator/ssh/communicator.go#L562-L571) in the SSH communicator was the root cause of one of the issues seen in #5963 as the PowerShell provisioner was using backslash formatted paths. On Linux/OS X this resulted in the upload path evaluating to `.` which ultimately caused the scp upload to fail. The issue was worked around for #5963 by configuring all of the paths in the PowerShell provisioner to use forward slashes. However, any user configuring a custom [remote_path](https://www.packer.io/docs/provisioners/powershell.html#remote_path) could reasonably expect to use a path formatted with back slashes. Doing so would unfortunately trigger the same issue.

It could be that this is the only example where the use of the filepath functions has caused an issue. However, executing a `grep -HRne filepath.[Dir|Base|ToSlash]` in the root of the Packer directory shows the extent to which these functions have been used; I wouldn't be surprised if there were a few other issues occurring because of this, especially where users can provide custom paths rather than using the internal defaults...

**Comment by arizvisa** [comment]
I didn't see it mentioned, but typically one would use `filepath.ToSlash` to import an external or user-specified path and `filepath.FromSlash` to export it back to the operating system (like to hand off the path to an external tool or some platform-specific configuration).

Internally, one should then use the `path.Dir` and `path.Base` functions that are defined in the `path` module to extract the different components. This should slay any of the aforementioned portability issues.

**Comment by arizvisa** [comment]
Is this issue still a thing? Can it be closed?

**Comment by azr** [comment]
Hello there, thanks for investigating and opening this! I think it's important to keep an eye on these.
I investigated this a little, and here are a few statements that helped me reasoning:
* all systems — except windows — use slashes to reference things in paths. We can simplify these systems to "unix" and "windows". Moreover, Windows can now resolve relative "slashed" path. Most likely absolute ones too (I have to try).
* for local files, the `filepath` pkg should always do the correct operation. For example, when Packer is built for Windows it will most likely be given Windows local paths and the operations will be correct; same thing for "unix".

With these two statements, we can safely say that  :
* these issues should arise mostly when from a unix system or binary we try to do `filepath` operation to a Windows path on a remote Windows system (and vice versa).

But, Packer Core can't know what remote system it is interacting with and can't start doing different things depending on the system. 

With that said, the PowerShell provisioner is most certainly always going to be executed against Windows machines, and therefore it would make much more sense to use a Windows only way of doing things in there, wherever the binary runs from.

**Comment by azr** [comment]
Also, it looks like these issues start happening when we mix forward and backward slashes, and so I think a good way to fix that is to add a convention that says we should always use (backwards or forward, we have to pick one) slashes in the PowerShell provisioner. With that, the Powershell provisioner could start using the `path` package to do things, just always assuming that everything has a slash.

PS: sorry, double post!

**Comment by azr** [comment]
Here's this helpful table for the future: 

|                                                           | windows                       | else                       |
|-----------------------------------------------------------|-------------------------------|------------------------------|
| filepath.Dir(`C:/Windows/Temp/forward.txt`)               | C:\Windows\Temp               | C:/Windows/Temp              |
| filepath.Base(`C:/Windows/Temp/forward.txt`)              | forward.txt                   | forward.txt                  |
| filepath.Dir(`C:/Windows/Temp/forward\ with\ space.txt`)  | C:\Windows\Temp\forward\ with  | C:/Windows/Temp              |
| filepath.Base(`C:/Windows/Temp/forward\ with\ space.txt`) | spaces                        | forward with spaces.txt      |
| filepath.Dir(`C:\Windows\Temp\backward.txt`)              | C:\Windows\Temp               | .                            |
| filepath.Base(`C:\Windows\Temp\backward.txt`)             | backward.txt                  | C:\Windows\Temp\backward.txt |
