### ISSUE TITLE
Add support for hvf accelerator to QEMU builder

### ISSUE THREAD

**Issue by adarobin** [hashicorp/packer#6189]
[QEMU 2.12 has added "Experimental support for two new virtualization accelerators: Apple's Hypervisor.framework ("-accel hvf") and Microsoft's Windows Hypervisor Platform Extensions ("-accel whpx")"](https://wiki.qemu.org/ChangeLog/2.12)

I'm specifically interested in using the hvf accelerator.  I'd be happy to submit a PR if it would be considered.

**Comment by adarobin** [comment]
I threw this together really quick and it seems to be working:

https://github.com/adarobin/packer/commit/b0f9c12bcb4becb278a519d35d96cf6a882f508c

**Comment by SwampDragons** [comment]
I'd definitely review a PR.
