### ISSUE TITLE
packer in centos and headless mode

### ISSUE THREAD

**Issue by jayaramanit** [hashicorp/packer#6191]
trying to build OVA file using vmware in headless mode in centos .

vmware-iso: Couldn't find VMware tools for 'linux'! VMware often downloads these
tools on-demand. However, to do this, you need to create a fake VM
of the proper type then click the 'install tools' option in the
VMware GUI.

Attached is the logs.

packer version
1.2.2

[packerlog.txt](https://github.com/hashicorp/packer/files/1948013/packerlog.txt)

**Comment by mwhooker** [comment]
Looks like you've got a tool conflict. You shouldn't be seeing `cracklib-packer`. See https://www.packer.io/intro/getting-started/install.html#troubleshooting and https://github.com/cracklib/cracklib/issues/7

If you do that and it still doesn't work, try following the instructions in the error output
