### ISSUE TITLE
Packer + Ansible + Windows: Script modules not working

### ISSUE THREAD

**Issue by PrebleBrier** [hashicorp/packer#6196]
Describe the problem and include the following information:

Executing Script module in Ansible 2.4.1.0 via Packer 1.1.1 to Windows 2012R2 Instance in AWS.  Script module is executing a powershell script, and fails with below error.  The Ansible playbook can run successfully if run directly via ansible to the same temporary instance created by Packer.

amazon-ebs: TASK [winlodrest : Download all Windows Common Installers from S3 Bucket to Instance] ***
    amazon-ebs: task path: /home/ubuntu/packer-builds/packer-restwindows/roles/winlodrest/tasks/main.yml:1
 amazon-ebs: <127.0.0.1> (0, '', '')
    amazon-ebs: fatal: [default]: FAILED! => {
    amazon-ebs:     "changed": true,
    amazon-ebs:     "failed": true,
    amazon-ebs:     "msg": "non-zero return code",
    amazon-ebs:     "rc": 1,
    amazon-ebs:     "stderr": "& was unexpected at this time.\r\nShared connection to 127.0.0.1 closed.\r\n",
    amazon-ebs:     "stdout": "",
    amazon-ebs:     "stdout_lines": []
    amazon-ebs: }

- Packer version 1.1.1
- Ubuntu 14.04.5
- Ansible version:
ansible 2.4.1.0
  config file = None
  configured module search path = [u'/home/ubuntu/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.6 (default, Nov 23 2017, 15:49:48) [GCC 4.8.4]

- Debug log output from `PACKER_LOG=1 packer build template.json`.
  https://gist.github.com/PrebleBrier/9dd9d9485d92572134d3c0b0fc95520c
- The _simplest example template and scripts_ needed to reproduce the bug.
 https://gist.github.com/PrebleBrier/5f59ddf4659c9224dd5bfb65cec406d4

**Comment by PrebleBrier** [comment]
I am able to get this script to run using the win_shell command and making the powershell script a multi-line win_shell invocation, but I feel it should still be possible to use the script module.

**Comment by stobias123** [comment]
We have an extensive ansible library, refactoring as shown is not an option.
The below block throws error.
```
- name: script
  script: script.ps1 > C:\temp\script.log 2>&1 
  args:
```

**Comment by SwampDragons** [comment]
What error?

**Comment by SwampDragons** [comment]
Hi @PrebleBrier. It appears that no one is currently working on this. The Ansible provisioner is one of our community-supported provisioners, which means that the HashiCorp engineers who work on Packer do not generally work on it. The reason this hasn't been resolved is that no one from the community has decided to work on it, either. You can find a list of the provisioners and builders that HashiCorp engineers actively support here: https://www.packer.io/community-plugins.html

**Comment by SwampDragons** [comment]
I just tested this against a build of the PR #8625, and when I remove the proxy I am able to successfully use the `script` module. This is probably an issue with the winrm connection plugin. Once that PR is merged, you will be able to turn off the proxy and fix this. Sorry it took so long.
