### ISSUE TITLE
VM cloned from template created by Packer has boot order reset to cdrom only instead of original boot order in template

### ISSUE THREAD

**Issue by GMZwinge** [hashicorp/packer#6197]
Packer version: v1.2.1
Host platform: Packer running on Windows 10, ESXi/vCenter 6.5 and ESXi 6.0/vCenter 6.5.

This is a report for an issue that manifests itself when a VM is created from a template created by Packer using the builders "vmware-iso" on a [Remote vSphere Hypervisor ](https://www.packer.io/docs/builders/vmware-iso.html#building-on-a-remote-vsphere-hypervisor) and the post-processors "vsphere-template". See [sample Packer template ](https://gist.github.com/GMZwinge/8743b1be26a931d846c1b43aabb880fd).

Even though Packer generates a template with a boot order set to "hdd,CDROM", a VM created from that template has the boot order reset to "cdrom". The reason seems to be that the template .vmtx file does not have an entry "bios.hddOrder" such as "bios.hddOrder": "scsi0:0".

The builders "vmware-iso" could be updated to not only set "bios.bootorder" = "hdd,CDROM", but also set "bios.hddOrder": "scsi0:0". In the mean time, a workaround is to set "bios.hddOrder": "scsi0:0" in the vmx_data_post section.

Regards,
Georges

**Comment by SwampDragons** [comment]
@arizvisa any chance you'd be interested in taking a look at this? It seems related to some work you've done recently. otherwise I'll see if I can knock it out next week.

**Comment by arizvisa** [comment]
@SwampDragons, sure.

**Comment by arizvisa** [comment]
@GMZwinge, what's the issue that manifests?

Does the final template not boot up off of the disk when deployed on ESX because VMware is changing the "bios.bootOrder" field to just "cdrom"? I ask because VMware Workstation 14 doesn't seem to touch "bios.bootOrder" opting to leave it as is.

**Comment by arizvisa** [comment]
@GMZwinge, can you see if PR #6204 fixes your issue? Lmk if you need a binary for your platform.

**Comment by SwampDragons** [comment]
@arizvisa you rock! Thanks for taking a look and saving me the context-load. I really appreciate it.

**Comment by arizvisa** [comment]
@SwampDragons lol! no problem. just shout my name. ;)

**Comment by GMZwinge** [comment]
@arizvisa I would gladly test PR #6204, but I need a Windows binary.

**Comment by GMZwinge** [comment]
Yes, PR #6204 fixes this issue.

**Comment by SwampDragons** [comment]
Closed by #6204

**Comment by SwampDragons** [comment]
@GMZwinge Unfortunately, I've had to revert the change that fixed this for you because it caused upload problems.  I'm afraid you'll have to go back to your workaround until I can find a solution that fixes both use cases.  See #7067 for more details.

**Comment by GMZwinge** [comment]
@SwampDragons No problem. Thanks for trying. The workaround is good enough for now.

**Comment by SwampDragons** [comment]
Thanks for understanding. I promise we'll get to the bottom of this.

**Comment by arizvisa** [comment]
@GWZwinge, just a heads up, but I think jetbrains-infra's "vsphere-iso" plugin might solve your issue since you're building directly on an ESX instance anywayz.. It's at https://github.com/jetbrains-infra/packer-builder-vsphere. If it still poses the same problems, let's create some issues for them as I think they need some more users.

I'm gonna try and do some more work over there in the hopes that it accelerates the merging of their plugin upstream into this repository.
