### ISSUE TITLE
Add custom information to the packer default output 

### ISSUE THREAD

**Issue by im-dofoborh** [hashicorp/packer#6198]
**Help wanted/Guidance** 

_Tools we are using_
+ Packer
+ AWS
+ Jenkins

After packer builds an image in AWS, besides the default information packer outputs about the AMI, we are trying to add more information to that output like the custom tags we have added to help identify the AMI in AWS.

**_Goal:_** The plan is to reference that file within Jenkins and use it for another part of the build.

Had a look and have not been able to find a way to do this. Has anyone done this before or is there a way to add more information to that default output.

An example of what the file might look like:
```
{
  uuid: 00000000
  ...
  ..
  environment:  development
  version:  3.0.0
  software:  jenkins 
}
```

**Comment by SwampDragons** [comment]
Hey there! Since this is not a direct feature request or bug report, it probably belongs on our email list rather than on github: https://groups.google.com/forum/#!forum/packer-tool

However, if you have specific items you'd like to see Packer include in the Manifest provisioner, let us know.
