### ISSUE TITLE
Packer is not indexing SQL images from GCP

### ISSUE THREAD

**Issue by vijayboopathy** [hashicorp/packer#6209]
Packer Version : **v1.2.3**
Host Platform : **Mac OS**
Cloud : **GCP**
Debug Log : https://gist.github.com/vijayboopathy/ad336d40943c7b44a881307a60a6c2c8
Packer Template: https://gist.github.com/vijayboopathy/8987a8c9e765979675b4260fd589a73f

Issue: 
Packer neither indexes SQL images from image family (sql-std-2014-win-2012-r2) nor when the image name(sql-2014-standard-windows-2012-r2-dc-v20180410) is provided.

**Comment by SwampDragons** [comment]
We probably should have this family be in our defaults; in the meantime, you can work around this by Adding the project id `windows-sql-cloud` to your packer config: https://www.packer.io/docs/builders/googlecompute.html#source_image_project_id

**Comment by SwampDragons** [comment]
[packer.zip](https://github.com/hashicorp/packer/files/1956218/packer.zip)
Does this solve the issue for you?

**Comment by vijayboopathy** [comment]
@SwampDragons Yea. Attached package works now. It would be nice if it is enabled by default :dancer:
