### ISSUE TITLE
Template validation failed. Errors are shown below.  Errors validating build 'aws-east-2'. 1 error(s) occurred:  * Unknown region: aws-east-2

### ISSUE THREAD

**Issue by mhthaque** [hashicorp/packer#6218]
Hi, I am getting below error. Any guess on it? 

goliath@server:~/XXXXXX/packer-ecs$ packer -v
1.2.3

ERROR:

Template validation failed. Errors are shown below.

Errors validating build 'amazon-ebs'. 1 error(s) occurred:

* Unknown region: aws-east-2

Configuration of packer.json file:

{
	"variables": {
		"aws_access_key_id": "{{env `AWS_ACCESS_KEY_ID`}}",
		"aws_secret_access_key": "{{env `AWS_SECRET_ACCESS_KEY`}}",
		"aws_session_token": "{{env `AWS_SESSION_TOKEN`}}",
		"time_zone": "{{env `TIME_ZONE`}}"
	},
	"builders": [
		{
          "type": "amazon-ebs",
          "access_key": "{{user `aws_access_key_id`}}",
          "secret_key": "{{user `aws_secret_access_key`}}",
          "token": "{{user `aws_session_token`}}",
          "region": "aws-east-2",
          "source_ami": "ami-64300001",
          "instance_type": "t2.micro",
          "ssh_username": "ec2-user",
          "associate_public_ip_address": "true",
          "ami_name": "docker-production-aws-ecs-base {{timestamp}}",
          "tags": {
          	"Name": "Docker Production AWS ECS Base Image",
          	"SourceAMI": "ami-64300001",
          	"DockerVersion": "1.12.6",
          	"ECSAgentVersion": "1.13.1"
          }
		}
	],
	"provisioners": [
		{   
			"type": "shell",
			"script": "scripts/configure-timezone.sh",
			"environment_vars": [
				"TIME_ZONE={{user `time_zone`}}"
			]
	},
	{
		"type": "shell",
		"script": "script/set-docker-options.sh"
	},
	{
		"type": "shell",
		"script": "scripts/install-os-packages.sh"
	},
	{
		"type": "shell",
		"script": "scripts/cloud-init-options.sh"
	},
	{
		"type": "shell",
		"script": "scripts/cleanup.sh"
	},
	{
		"type": "file",
		"source": "files/firstrun.sh",
		"destination": "/home/ec2-user/firstrun.sh"
	}
 ],
	"post-processors": [
		{
			"type": "manifest",
			"output": "manifest.json",
			"strip_path": "true"
	}
 ]
}

goliath@server:~/XXXXX/packer-ecs$  packer validate packer.json 
Template validation failed. Errors are shown below.

Errors validating build 'aws-east-2'. 1 error(s) occurred:

* Unknown region: aws-east-2

**Comment by rickard-von-essen** [comment]
`aws-east-2` is not a valid region name. See the [AWS documentation for a complete list of regions](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.RegionsAndAvailabilityZones.html).

**Comment by mhthaque** [comment]
Thanks for the heads up. How did I make this silly mistake! 
It should be "region": "us-east-2" 
Problem solved! 👍
