### ISSUE TITLE
Packer needs a new full time Engineer

### ISSUE THREAD

**Issue by SwampDragons** [hashicorp/packer#6228]
If you're interested in getting paid to work on Packer, check out our job listing:

https://www.hashicorp.com/jobs/1128730

**Comment by azr** [comment]
Hi there 😄

**Comment by marema31** [comment]
Hi,

The URL is not working anymore. May be time to close the issue ?

**Comment by azr** [comment]
Hi there, I'm the new Engineer ! Totally time to close the issue :)

**Comment by azr** [comment]
( freshly got the rights to ! :) )
