### ISSUE TITLE
Packer fails to connect with SSH communicator on scaleway instance

### ISSUE THREAD

**Issue by gui-don** [hashicorp/packer#6232]
When running packer with this basic configuration:
```json
{
  "variables": {
    "scaleway_access_key": "",
    "scaleway_token ": "",

    "scaleway_region": "ams1",
    "scaleway_image_type": "VC1S"

  },
  "builders": [{
    "type": "scaleway",
    "ssh_username": "root",
    "api_access_key": "{{user `scaleway_access_key`}}",
    "api_token": "{{user `scaleway_token`}}",
    "image": "0f805370-5622-40df-af56-ac4fcf554b77",
    "region": "ams1",
    "commercial_type": "VC1S"
  }],
  "provisioners": [
    {
      "type": "shell",
      "inline": [
        "sleep 10",
        "echo 'Done.'"
      ]
    }
  ]
}
```
Packer is unable to connect to the instance using SSH. It seems it does not even tries (`attempted methods [none]`). Here what the logs says:

```
[…]
==> scaleway: Waiting for SSH to become available...
[INFO] Attempting SSH connection...
[DEBUG] reconnecting to TCP connection for SSH
[DEBUG] handshaking with SSH
[ERROR] handshake error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
[DEBUG] SSH handshake err: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
[DEBUG] Detected authentication error. Increasing handshake attempts.
[…]
```
(full: https://gist.github.com/gui-don/e9520adc7152791ac0d5310a98472d19)

With the `-debug` argument, manual connection works:
```bash
$ ssh -i scw_scaleway.pem root@X.X.X.X
```
I tested by setting `ssh_private_key_file`. The same error occurs and again, I can manually connect using the correct SSH key.

Note: the `aws` builder works on my workstation.

Packer version: 1.2.3 
Go version: 1.10.2
ArchLinux

**Comment by rickard-von-essen** [comment]
Please [gist](https://gist.github.com/) a full debug log from `PACKER_LOG=1 packer build template.json`.

**Comment by rickard-von-essen** [comment]
Can you reproduce this with a public image?

**Comment by gui-don** [comment]
I think the image I used is public. However, it’s not present in the [api-marketplace](https://api-marketplace.scaleway.com/images) for some reason…

Anyway, I made another test. This time it is the image for Debian Jessie x64 for `ams1`:
```json
{
  "variables": {
    "scaleway_access_key": "",
    "scaleway_token ": "",
    "ssh_private_key_file": "~/.ssh/id_rsa_test",
    "scaleway_region": "ams1",
    "scaleway_image_type": "VC1S"

  },
  "builders": [{
    "type": "scaleway",
    "ssh_username": "root",
    "api_access_key": "{{user `scaleway_access_key`}}",
    "api_token": "{{user `scaleway_token`}}",
    "image": "2e570f53-199e-47cc-95dd-f7bc392496e3",
    "region": "ams1",
    "commercial_type": "VC1S"
  }],
  "provisioners": [
    {
      "type": "shell",
      "inline": [
        "sleep 10",
        "echo 'Done.'"
      ]
    }
  ]
}
```

No luck, output is identical: https://gist.github.com/gui-don/b6dff05c20fb52ff52c78048df5a7bc2.

**Comment by DanHam** [comment]
@rickard-von-essen Having take a quick look at this, I think fc7d89eb79887f21cdb67a1e97f3e6e848134ce0 may have broken the ability to use the automatically generated key.

It looks as though there isn't a way to use the auto generated `privateKey` stored in the state bag. In order to use key based authentication, the conditionals in `builder/scaleway/ssh.go` require the user has set `ssh_key_private_file` in their template. Obviously this isn't set if they are using the auto-generated key. This is why the `attempted_methods` is `[none]` as none of the conditionals are evaluating true...

**Comment by DanHam** [comment]
@rickard-von-essen I think the fix could be as simple as changing the conditional surrounding the key based ssh auth...

@gui-don Are you able to build and test if I can get a PR together?

**Comment by gui-don** [comment]
@DanHam I’m not familiar to go, but I’ll give it a try.

**Comment by DanHam** [comment]
@gui-don I'm just working through some final tests. Hopefully I will have the PR submitted in a bit...

I wasn't familiar with Scaleway but I'm liking what I see so far!

**Comment by gui-don** [comment]
I can confirm it works when removing the condition `if config.Comm.SSHPrivateKey != ""`.

I could make a PR to change that, but I’m unsure about the consequences if I simply remove the condition. Aren’t there unit tests for this file?

**Comment by gui-don** [comment]
Yep, that worked for me too! Thank you :)

I just started to test scaleway service, because it’s cheap compared to AAA clouds like AWS. But I guess it comes at a price: sometimes you’ll have to wait a very long time before your server comes up.

**Comment by DanHam** [comment]
@gui-don Good news! Hopefully it'll get approved for merging...

I think I'm gonna carry on with Scaleway and see how I get on. Really like the cli tools and general simplicity of it all. It doesn't feel overly complicated like AWS can sometimes do. That said, I was starting to get in to GCE as I like the cli for that too... 

Ah, so many cloud providers and so little time to investigate them all 😄
