### ISSUE TITLE
Unable to upload files with provisioners

### ISSUE THREAD

**Issue by janegreira** [hashicorp/packer#6233]
Hello, 

I'm trying to upload files and execute commands in my packer file.
Packer finish and build the .ova file, but files aren't present in the created VM.

Packer version: 1.2.2
ESXi: 6.5.1  

PACKER LOG:
https://gist.github.com/janegreira/6359263fbed0066569e1685473fd3f82

JSON file:
https://gist.github.com/janegreira/7e8ea12335ec28ef55777d62d6d57cc6

Thanks in advance!

**Comment by SwampDragons** [comment]
This seems more like a usage question than an issue; I think you'll have better luck reaching out to our mailing list if you want help figuring out what's going on: https://groups.google.com/forum/#!forum/packer-tool
