### ISSUE TITLE
macOS virtualbox-iso builder, umount rpc_pipefs target busy

### ISSUE THREAD

**Issue by pakulin** [hashicorp/packer#6236]
Packer version : 1.2.2, 1.2.3
Host platform: macOS 10.13.4 (17E199)
virtualbox versions: 5.2.10, 5.2.11 r122401

umount rpc_pipefs target busy

- Debug log output from `PACKER_LOG=1 packer build template.json`.
  https://gist.github.com/pakulin/8f6a516e96777e0e74ee1f9a26c4ef1b
- The _simplest example template and scripts_ needed to reproduce the bug:
packer.json - https://gist.github.com/pakulin/4d2860c5b589c16900989c2de83c61a2
autoinst.xml - https://gist.github.com/pakulin/94412338c5b0ac846fcabcf4a2184904

![screen shot 2018-05-03 at 07 16 39](https://user-images.githubusercontent.com/5189335/39559879-36bc0d2a-4ea2-11e8-8edf-dcbbffcf417c.png)

**Comment by pakulin** [comment]
Setting RAM to 1G solves the issue. But why? )

**Comment by rickard-von-essen** [comment]
The VirtualBox default is very low, the SUSE installer requires a lot more.
