### ISSUE TITLE
Unpriviliged LXC containers

### ISSUE THREAD

**Issue by thedrow** [hashicorp/packer#6244]
Currently the LXC builder can only create privileged containers.
We're deploying unprivileged containers and therefor cannot use the the generated rootfs.
We're getting the following error:
```
     lxc-create 20180506130302.229 WARN     lxc_confile - confile.c:set_config_pivotdir:2262 - lxc.pivotdir is ignored.  It will soon become an error.
     lxc-create 20180506130302.229 INFO     lxc_confile - confile.c:set_config_idmaps:1861 - read uid map: type u nsid 0 hostid 100000 range 65536
     lxc-create 20180506130302.229 INFO     lxc_confile - confile.c:set_config_idmaps:1861 - read uid map: type g nsid 0 hostid 100000 range 65536
     lxc-create 20180506130302.229 DEBUG    lxc_conf - conf.c:chown_mapped_root:2830 - trying to chown "/home/user/.local/share/lxc/sshd-import" to 1000
     lxc-create 20180506130302.275 ERROR    lxc_create_ui - tools/lxc_create.c:main:326 - Error creating container sshd-import
```

**Comment by SwampDragons** [comment]
gonna tag @ChrisLundquist, the original author of the LXC builder.

**Comment by ChrisLundquist** [comment]
Hey there!
I’m on vacation so it will be a few days until I have a good environment to test this.

@thedrow Do you have any configuration your using in particular or will the sample one suffice?

I’m a little less familiar with LXC compared to LXD, so if you have any repro steps / commands to test that would be appreciated and save me some time!
