### ISSUE TITLE
Packer 1.2.3 types too quickly for some installers?

### ISSUE THREAD

**Issue by LeeXGreen** [hashicorp/packer#6247]
Thanks for making Packer!

* Packer version: v1.2.3
* Host platform: OS X El Capitan 10.11.6

I was not able to run Packer with a guest OS of Ubuntu 16.04 -- each time I tried to run it, my install command was missing one or more characters -- different characters each time.

I was able to work around it by adding `<wait>` commands into the longer command strings, but this is obviously less than optimal.

I downgraded to 1.2.2 and this issue went away completely -- I was able to remove the `<wait>` commands and use the original template.

Debug log output and example template located [here](https://gist.github.com/LeeXGreen/618291eb9fef681f937551fe8946f3b8)

**Comment by LeeXGreen** [comment]
I can't screenshot the entire string at once, but I've bolded the missing characters below:

"boot_command": [
`        "<enter><wait><f6><esc><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>",
            "<bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>",
            "<bs><bs><bs><bs><bs><bs>",`
            " /install/vmlinuz<wait>",
            " auto<wait>",
            " console-setup/ask_detect=false<wait>",
            " console-setup/modelco**de**=pc105<wait>",
            " debian-installer=en_US<wait>",
            " fb=false<wait>",
            " initrd=/install/initr **d.** gz<wait>",
            " kbd-chooser/method=us<wait>",
            " locale=en_US<wait>",
            " netcfg/get_domain=vm<wait>",
            " netcfg/get_hostname=tron-pre**m**<wait>",
            " grub-installer/bootdev=/dev/sd**a**<wait>",
            " noapic<wait>",
            " -- <wait>",
            " ks=http://{{user `kickstart_IP`}}:4567/**ks**<wait>",
            "<enter><wait>"
      ],

**Comment by mwhooker** [comment]
Can you post a full debug log along with the exact characters that were missing from that run, please?

**Comment by mwhooker** [comment]
Also you can try adjusting `PACKER_KEY_INTERVAL` to whatever you like. For some reason this isn't documented everywhere, so I'll fix that.

**Comment by DanHam** [comment]
@mwhooker This is just FYI and is unrelated to this issue as the user has Virtualbox 5.0.26... 

I noticed the following in the changelog for Virtualbox 5.2.10:

> Keyboard: Introduced a small delay to fix old software which expects to be able to read an incoming scan code more than once ([bug #17592](https://www.virtualbox.org/ticket/17592))

This fix looks to have caused some keyboard/typing speed issues for others - see [ticket 17709](https://www.virtualbox.org/ticket/17709).

**Comment by mwhooker** [comment]
@LeeXGreen does setting PACKER_KEY_INTERVAL to something higher than the default 100ms fix this for you? I notice that the first missed characters, `de`, would be the 76th and 77th character. This means that the 3rd invocation of vboxmanage isn't acting right.
