### ISSUE TITLE
Packer crash when reboot image during build process

### ISSUE THREAD

**Issue by flamarion** [hashicorp/packer#6250]
I'm using the Jenkins to build and publish some images to Azure and AWS, but sometimes I'm getting this same issue when I try to reboot the images during the build process.

As I was not experiencing this every build I didn't enable the debug to help the troubleshoot and the workspace is always deleted at the end of the build, so crash.log is not available as well.

Here the piece of evidence which was possible to collect.

https://gist.github.com/flamarion/b703631566615a0e9b6f4a69f7c60e83

Packer Version: 1.2.1

**Comment by SwampDragons** [comment]
We really need all the information requested in the issue template if we're going to have any chance of debugging this; I know we resolved a couple of crashes recently, so I'd also suggest upgrading to the latest version of Packer and seeing if the problem has already been resolved.

**Comment by flamarion** [comment]
Alright, I'm going to add some approach to collect the logs during every build, then if it crash again, I'll have the logs. I'm really sorry not be able to provide more details. About the upgrading, I'll check the possiblity and go for it.
