### ISSUE TITLE
Add support for t2 unlimited on the Amazon EBS Builder

### ISSUE THREAD

**Issue by billatq** [hashicorp/packer#6260]
This is a feature request for adding support for t2 unlimited for the Amazon EBS Builder. This feature allows you to use a t2 instance to keep costs low, but also burst additional CPU while you're doing a build.

A description of this feature is here:
https://aws.amazon.com/blogs/aws/new-t2-unlimited-going-beyond-the-burst-with-high-performance/

**Comment by mwhooker** [comment]
Looks like we'll need to add a credit specification field to the builder and then pass it in when we run instance.

We'll need to remember to update the docs here

```
website/source/docs/builders/amazon-chroot.html.md
website/source/docs/builders/amazon-ebs.html.md
website/source/docs/builders/amazon-ebssurrogate.html.md
website/source/docs/builders/amazon-ebsvolume.html.md
website/source/docs/builders/amazon-instance.html.md
```

https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#RunInstancesInput.SetCreditSpecification


This would be a great first issue if anyone wants to take a look

**Comment by DanHam** [comment]
@billatq Please see #6265. Any testing would be very welcome.
