### ISSUE TITLE
Packer for Hyper-V fails to create additional disk

### ISSUE THREAD

**Issue by stratanco** [hashicorp/packer#6267]
We use the Packer Hyper-V ISO builder to create a virtual machine with an additional disk. We had a working version, but since last week we started to receive error messages at the creation of the additional disk. 

This seems to be caused by having upgraded Packer from 1.2.1 to 1.2.3. With Packer 1.2.1 we could create the additional disk.

Is there any way to fix our template, or any workaround to be able to create additional disk(s) with Packer 1.2.3?

- Packer version: 1.2.3
- Host platform: Windows 10, version 10.0.16299
- Guest platform: CentOS 7.5

Packer template, Kickstart file and debug log:
https://gist.github.com/stratanco/36ae1b4e4922b24d6db2156e50e384c2

**Comment by WaaZaa666** [comment]
+1, running in to the same issue..

**Comment by synax** [comment]
Ah thanks! 👍  Was about to create a pull request as well :). Sorry for missing this!
