### ISSUE TITLE
Make OpenStack builder use Tokens.

### ISSUE THREAD

**Issue by awalende** [hashicorp/packer#6273]
The OpenStack-Builder requires some fields for authentication, especially a username/password combo.  Is it possible to use an already existing Keystone-Token for authenticating?
Reason is, that I'm developing a service which creates custom images using packer. However, I am not allowed to receive full credentials of all users. I am only allowed to receive timed tokens from a user.

**Comment by rickard-von-essen** [comment]
This is currently not supported but should be easy to add.

**Comment by rickard-von-essen** [comment]
Fixed in #6362
