### ISSUE TITLE
Customize virtual machine hardware before booting with ISO

### ISSUE THREAD

**Issue by abhinav-chittora** [hashicorp/packer#6275]
**Issue:-** 
While using vmware-iso builder, I am trying to create a virtual machine but the minimum memory requirement for operating system to boot is 2Gb. By default, vmware-iso use standard vmx file which have 512Mb memory for virtual machine. Due to unavailability of changing the memory before booting the packer build is failed after waiting for SSH connection. 

**Suggested Resolution: -**
I would suggest, we should have some type of pre-tasks which will allow users to change the vmx-data. right now, vmx-data is not used before booting (this is my experience, not sure whether I am right or not). 

**Environment:-**
`packer version: Packer v1.2.3 `
`Host platform: Centos Linux 7`
`Guest OS: Container Linux (CoreOS)`

**Comment by rickard-von-essen** [comment]
You can do this with [`vmx_data`](https://www.packer.io/docs/builders/vmware-iso.html#vmx_data). Example: https://github.com/chef/bento/blob/master/centos/centos-7.5-x86_64.json#L64
