### ISSUE TITLE
isotime function works in an unusual/confusing/insane way and reflects poorly on the project

### ISSUE THREAD

**Issue by paulcdejean** [hashicorp/packer#6278]
https://www.packer.io/docs/templates/engine.html#isotime-function-format-reference

This sort of thing is so obviously nutty, that it makes people second guess relying on packer.

I understand that this can't be changed in a backwards incompatible way, but a more sensible replacement should be created, so that this can be depreciated.

This is more of a public relations issue than anything. The current function probably works maybe, but it's still r/softwaregore material.

**Comment by rickard-von-essen** [comment]
It can be good to back up your claims with some facts/example. It does work, and just passas the parameters to [Go's std lib function for formatting time dates](https://golang.org/pkg/time/#Time.Format).
