### ISSUE TITLE
Feature Request - Azure (ARM) Postprocessor

### ISSUE THREAD

**Issue by flamarion** [hashicorp/packer#6281]
Hi,

I am a daily user of Packer and I'd like to ask you guys to try implement some post-processors for Azure like we have for AWS.

Currently, after all my builds (virtualbox-iso, for example) which I need to push the result to Azure, I need to do it using a post-processor shell and wrap Python + Virtualenv + AzureCLI.

To use these tools is not a problem at all, but the post-processor is being really big and complex due the nature of build (We need to do some conversions and resizes to be accepted by Azure) so the part to push the result of all those complexity could be facilitated with a post-processor able to create a managed image and VHD.

Thank you,

Flamarion Jorge

**Comment by boumenot** [comment]
Is this similar to #6101? It sounds like there is some overlap (size alignment?), but not completely.

**Comment by flamarion** [comment]
Hi,

First of all, thank you for your quick interaction.

There is some work to size alignment indeed, but not only this.

1 - https://gist.github.com/flamarion/68aee3b5c67858cd42bc6cfe2e0e359d

2 - Yes. Due the strict regulations, the first build should be done using some ISO file, then, after created the golden image (Managed Image) , we can build directly on Azure using our previously built managed image. In other words, we can't use any image provided by Azure marketplace.

All those conversions which you're going to see on post-processor should be done in order achieve the VHD file, because only the VHD file can be converted to a managed image. I already thought in to build using directly the qemu builder, but I have no time to change all work now.

Regards,

Flamarion Jorge

**Comment by harijayms** [comment]
@flamarion  we are looking to create a service that you can potentially leverage for this. Do you want to connect offline so that I can understand your scenarios better

**Comment by flamarion** [comment]
@harijayms Of course, let me know the best place / tool to reach you. Regards.

**Comment by flamarion** [comment]
@harijayms Are you still engaged to leverage this solution? I'm willing to help with information about my scenarios and what I'm doing to push my images to Azure.
