### ISSUE TITLE
[question] amazon-ebsvolume for windows

### ISSUE THREAD

**Issue by lmayorga1980** [hashicorp/packer#6282]
Seems like it is possible to use the `amazon-ebsvolume` on windows but could not find any information to use a guide.

Can someone point me to the right direction?

**Comment by SwampDragons** [comment]
This is probably a question better directed at our mailing list (https://groups.google.com/forum/#!forum/packer-tool).  The amazon-ebsvolume builder should be platform-agnostic.  We do have an example for the amazon-ami builder which should get you pointed in generally the right direction for configuration of windows guests (check out the user data file, specifically)

**Comment by SwampDragons** [comment]
oops -- forgot to link the example: https://www.packer.io/intro/getting-started/build-image.html#a-windows-example
