### ISSUE TITLE
amazon-import doesn't recognize s3_bucket_name when using env variables

### ISSUE THREAD

**Issue by flamarion** [hashicorp/packer#6283]
Hi,

I'm trying to use the post-processor amazon-import post-processor, but for some reason packer is not recognizing the s3_bucket_name if I try to use a environment variable instead a hardcoded string.

- Packer version from 1.2.1 but tested with 1.2.3 too
- Darwin and Linux
- Debug log output from `PACKER_LOG=1 packer build template.json`.
This is happening during the build, but is not passing neither by validation

- The _simplest example template and scripts_ needed to reproduce the bug.
All artefacts to reproduce can be found here https://gist.github.com/flamarion/58ca7a453d3a4190eceec68af355beec

**Comment by rickard-von-essen** [comment]
Please supply the information requested in the issue template:
- Packer version (`packer version`)
- Host platform (`uname -a` etc.)
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a [gist](https://gist.github.com).
- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your [gist](https://gist.github.com).

**Comment by flamarion** [comment]
packer version
Packer v1.2.1

uname -a
Darwin XXXXXXXXXX 16.7.0 Darwin Kernel Version 16.7.0: Tue Jan 30 11:27:06 PST 2018; root:xnu-3789.73.11~1/RELEASE_X86_64 x86_64 i386 MacBookPro14,3 Darwin

https://gist.github.com/flamarion/d02ead4542751db4f9e36ab99f20280e

https://gist.github.com/flamarion/28ad3eb51d7bc64294d3a8606f604b78

**Comment by rickard-von-essen** [comment]
Please supply the *full* template.

**Comment by flamarion** [comment]
Ok, I'm going to close this one because I don't know more what more I can provide.
Thanks for your time.
Flamarion

**Comment by rickard-von-essen** [comment]
I review the code. It should work. Usually these things end up being a mistake such as using - vs —, so if you don't share a template I can't rule out such tings. Also it can take a long time to reproduce an issue, maintainers time is a scarce resource.

Hope you solve it on your own hand.

**Comment by flamarion** [comment]
I got it, but I didn't manage to fix it other way than use a hard coded string.

Here the full template https://gist.github.com/flamarion/f633ae589e785debff542655aac9e380

**Comment by lmayorga1980** [comment]
I have been using the latest Packer versions and this works perfectly. Did you try to set the env variable in the same Packer command?

`AWS_S3_BUCKET=<SOME_BUDLE> PACKER_LOG=debug packer build ...`

**Comment by SwampDragons** [comment]
Do your other env vars work? Are you setting them the same way?

**Comment by flamarion** [comment]
@lmayorga1980 Doing what you suggested worked, I'm going to investigate better what is going on then.
@SwampDragons Yes, I have other variables working.

**Comment by SwampDragons** [comment]
Thanks! Given that @lmayorga1980's advice worked, it looks like this is something to do with how you're setting the environment variable before the packer run, rather than with Packer. I'm going to close. If you have more trouble getting it to work I'd recommend writing to our mailing list (https://groups.google.com/forum/#!forum/packer-tool) to get troubleshooting help.
