### ISSUE TITLE
Issue/Enhancement Oracle - OCI Instance's provisioned are not being set to the builder name

### ISSUE THREAD

**Issue by Marcus-James-Adams** [hashicorp/packer#6287]
Packer v1.2.3

I'm not sure if this is a bug or it's deliberate so an enhancement request.
When you provision instance for building in OpenStack using packer the instance display name is set to the builder name.

However when you provision under Oracle - OCI the instance display name just shows as instance-(timestamp).  This is not very helpful when you have a number of builds on the go and wish to troubleshoot.

The API to provision instances does allow for the setting of the instance display name.  If this is not a bug I would like to request it as an enhancement to improve the process.

**Comment by SwampDragons** [comment]
Note for whoever decides to take this on -- I think we need to set `displayName`. Currently the only piece of information the OCI driver takes is the public key:  https://github.com/hashicorp/packer/blob/cbbbf551e39d3dc2c6b80c0967e2d7a47cfe8e65/builder/oracle/oci/step_create_instance.go#L22

API reference:
https://docs.us-phoenix-1.oraclecloud.com/api/#/en/iaas/20160918/LaunchInstanceDetails
