### ISSUE TITLE
[requirement] use existing key pair for amazon-ebs and amazon-ebsvolume

### ISSUE THREAD

**Issue by lmayorga1980** [hashicorp/packer#6288]
Currently packer creates a temporal key pair name and destroys it  after the process is complete. There are scenarios when you want to debug your instance even when the provisioning is not complete by either RDP, SSH, WINRM and it is not possible.

There should be a `temporary_key_pair_name_keep` with default `false` but allowing the user to keep a local copy of it.

**Comment by rickard-von-essen** [comment]
Duplicates #5107
