### ISSUE TITLE
packer times out waiting on i3.metal instance to shutdown

### ISSUE THREAD

**Issue by mzeier** [hashicorp/packer#6289]
This might end up being a feature request.

Packer doesn't appear to have any knob to change the default waiting period for an instance stop. The `i3.metal` instances take ~10 minutes to shutdown which causes Packer to timeout:

```
==> amazon-ebs: Pausing after run of step 'StepProvision'. Press enter to continue.
==> amazon-ebs: Stopping the source instance...
    amazon-ebs: Stopping instance, attempt 1
==> amazon-ebs: Waiting for the instance to stop...
==> amazon-ebs: Error waiting for instance to stop: ResourceNotReady: exceeded wait attempts
Build 'amazon-ebs' errored: Error waiting for instance to stop: ResourceNotReady: exceeded wait attempts
```

Version:
```
nimba:packer mrz$ packer --version
1.2.1
```

**Comment by mwhooker** [comment]
@mzeier Thanks for the issue. This is a great counter example for #6177 

I'll think about this a bit and see what we can do

**Comment by SwampDragons** [comment]
Hmm. At a quick glance at the code, it looks like it's set in the upstream SDK we use for interfacing with the AWS API -- https://github.com/aws/aws-sdk-go-v2/blob/master/service/ec2/waiters.go#L646-L648

**Comment by mwhooker** [comment]
I'm going to close this and track in #6177
