### ISSUE TITLE
Question: Using packe to spin a vm and extract the image in an availability set

### ISSUE THREAD

**Issue by tusharsappal** [hashicorp/packer#6290]
We have our corporate requirement ( due to pricing and whitelisting) to have Availability sets in our Azure subscription and resources like Compute should be spun inside that particular availability set. Since Packer while creating the Image spins up a temporary VM inside a temporary resource Group , I am confused (since did not find any documentation around it) if we can configure packer to spin the temporary VM inside the whitelisted availability set.

One possible way I can think of is to spin up the VM in the Resource Group which we created for the Availability Set (Since everything in Azure needs to be inside the Resource Group) that way I am guessing it will be tracked as part of billing but I am still not sure if the intermittent VM will be part of availability set.

Please help and suggest if there is an alternate way to the same as I was not able to find any documentation regarding the same on the web.

**Comment by boumenot** [comment]
Please re-read the docs.  There is information about using an existing resource group.  See the `build_resource_group_name` option.

**Comment by tusharsappal** [comment]
Hey @boumenot thanks for the reply , yes I read the Azure Packer documentation and it says we can spin up Temporary VM inside an *explicit  Resource Group* , but it no where clearly states that if the Resource group has availability sets inside it , packer's user has an option to spin it inside an availability set thats what confused me .  Are you implying that if we set `build_resource_group_name ` the packer will use the availability set defined in the Resource group to spin up temporary compute instances ? 
Please let me know . I would recommend please do not close this issue till we have a discrete answer :) .. I hope that helps
