### ISSUE TITLE
keep_input_artifact=false does not remove ova file on amazon-import post-processor

### ISSUE THREAD

**Issue by lmayorga1980** [hashicorp/packer#6294]
Everything works fine but the directory and its contents is not removed when using `keep_input_artifact`

```shell
    "post-processors" : [
     [
     {
      "type": "shell-local",
      "inline": [ "ovftool packer-centos73-x86_64-vmware/packer-vmware-iso.vmx packer-centos73-x86_64-vmware/packer-vmware-iso.ova" ]
     },
     {
         "files": [
           "packer-centos73-x86_64-vmware/packer-vmware-iso.ova"
         ],
         "type": "artifice"
     },
     {
       "type": "amazon-import",
       "access_key": "",
       "region": "",
       "secret_key": "",
       "profile": "saml",
       "ami_name": "centos7-x86_64",
       "ami_description": "CentOS 7.x x86_64 Base",
       "s3_bucket_name": "{{user `aws_s3_bucket_name`}}",
       "s3_key_name": "some-key",
       "keep_input_artifact": false,
       "license_type": "BYOL",
       }
     }
     ]
     ]
}
```

**Comment by ladar** [comment]
More generally, I noticed that the output from the `vagrant` post processor (aka the "box" file) when `keep_input_artifact` is set to false, (yes there is a step after `vagrant` in my case). In my case that's a `vagrant-cloud` step, followed by a `checksum` step. I use a rather old Macbook Air with only 64GB of storage for my Parallels builds, and I had hoped to use the `keep_input_artifact` value to remove box files, and only leave behind checksum files when a build succeeds... but noticed this doesn't work as expected. I had to implement some bash-fu to make it work: 

```bash

function parallels() {
  if [[ `uname` == "Darwin" ]]; then

    # Ideally, we shouldn't need this. However our Mac is resource starved
    # so we need to build each box individually to avoid running out of
    # memory, and remove the output, to avoid running out of disk space.

    LIST=($BOXES)

    verify_json generic-parallels

    for ((i = 0; i < ${#LIST[@]}; ++i)); do
      if [[ "${LIST[$i]}" =~ ^(generic|magma)-[a-z]*[0-9]*-parallels$ ]]; then
        packer build -parallel=false -except="${EXCEPTIONS}" -only="${LIST[$i]}" generic-parallels.json
        rm -rf $BASE/output/ $BASE/packer_cache/
      fi
    done

  else
    tput setaf 1; tput bold; printf "\n\nThe Parallels roboxes require a MacOS X host...\n\n"; tput sgr0
  fi
}
```

**Comment by SwampDragons** [comment]
I think I'm gonna push fixing `keep_input_artifact` on both amazon import and vagrant pps back to the 1.4.0 release because it may break builds for people who were relying on the undocumented bad behavior.

**Comment by ladar** [comment]
No problem. I've scripted a workaround, and since I don't use `packer` to upload to the Vagrant cloud anymore, I personally need to keep the box files around after the build. (I move them to an external drive after building, and then upload them all via a script once the build is complete.)

I suspect a number of templates, including my own, have incorrect values for `keep_input_artifact` in our templates, but don't realize it because the config setting isn't being used. So making this part of a minor release, makes more sense than a point release.

**Comment by SwampDragons** [comment]
Turns out this behavior is intentional and was introduced here: https://github.com/hashicorp/packer/commit/f78cbb45a6c37a0b9ac99af672b2f25f198648ba

I'll see if I can get more context about the reasoning behind it before I decide whether to change it.

**Comment by SwampDragons** [comment]
Got a little more digging in. That code I linked above allows both the shell-local and the artifice post-processor to force keep_input_artifact=true, which does seem like a reasonable _default_ to me but you should be able to override them. The amazon-import pp should behave as you expect, but deleting the amazon-import input artifact would only delete the .ova, not all the vmx-related files in that output dir.

So this code isn't so much a bug in the amazon-import pp as it is an intended behavior that is maybe not flexible enough. I'm going to noodle on whether it makes sense to be able to override these defaults. I think it does, but it's a big enough change I want to talk it over with some folks.
