### ISSUE TITLE
[1.2.3] Fails to retrieve Windows Administrator Password from a Packer amazon-ebs successful build

### ISSUE THREAD

**Issue by lmayorga1980** [hashicorp/packer#6297]
I have a successful Packer amazon-ebs windows ami but when I try to create an ec2 instance based on the ami I am not able to retrieve the Administrator credentials using the certificate I used to build the instance.

I know that Packer during the build process creates a temporal key pair and is able to retrieve the AMI Administrator Password but after the build is complete the key pair is destroyed. 

![screenshot from 2018-05-23 16-56-46](https://user-images.githubusercontent.com/3172378/40450660-5135ce08-5eaa-11e8-85e4-4d1c2dac0e9b.png)

```json
{
    "variables": {
      "admin_user": "Administrator"
    },
    "builders": [ {
      "type": "amazon-ebs",
      "ami_name": "Windows_2016_Full_Base",
      "instance_type": "t2.medium",
      "region": "",
      "secret_key": "",
      "access_key": "",
      "profile": "saml",
      "ami_description": "Base AMI",
      "ami_block_device_mappings": [
        {"delete_on_termination": true,
          "device_name": "/dev/sda1",
          "volume_size": 60,
          "volume_type": "gp2"
        }
       ],
      "source_ami_filter": {
        "filters": {
          "virtualization-type": "hvm",
          "name": "Windows_Server-2016-English-Full-Base-????.??.??",
          "root-device-type": "ebs"
        },
       "owners": ["801119661308"],
       "most_recent": true
      },
      "communicator": "winrm",
      "user_data_file": "scripts/win/ec2-userdata.ps1",
      "windows_password_timeout": "30m",
      "winrm_use_ssl": true,
      "winrm_insecure": true,
      "winrm_username": "{{user `admin_user`}}",
      "winrm_timeout": "6h"
    }
    ],
    "provisioners": [
    {
      "type": "windows-shell",
      "scripts": [
        "scripts/win/uac-enable.bat",
        "scripts/win/enable-rdp.bat"
      ]
    }
  ]
}
```

**ec2-user-data**

```json
<powershell>

write-output "Running User Data Script"
write-host "(host) Running User Data Script"

Set-ExecutionPolicy Unrestricted -Scope LocalMachine -Force -ErrorAction Ignore

# Don't set this before Set-ExecutionPolicy as it throws an error
$ErrorActionPreference = "stop"

# Remove HTTP listener
Remove-Item -Path WSMan:\Localhost\listener\listener* -Recurse

$Cert = New-SelfSignedCertificate -CertstoreLocation Cert:\LocalMachine\My -DnsName "packer"
New-Item -Path WSMan:\LocalHost\Listener -Transport HTTPS -Address * -CertificateThumbPrint $Cert.Thumbprint -Force

# WinRM
write-output "Setting up WinRM"
write-host "(host) setting up WinRM"

cmd.exe /c winrm quickconfig -q
cmd.exe /c winrm set "winrm/config" '@{MaxTimeoutms="1800000"}'
cmd.exe /c winrm set "winrm/config/winrs" '@{MaxMemoryPerShellMB="1024"}'
cmd.exe /c winrm set "winrm/config/service" '@{AllowUnencrypted="true"}'
cmd.exe /c winrm set "winrm/config/client" '@{AllowUnencrypted="true"}'
cmd.exe /c winrm set "winrm/config/service/auth" '@{Basic="true"}'
cmd.exe /c winrm set "winrm/config/client/auth" '@{Basic="true"}'
cmd.exe /c winrm set "winrm/config/service/auth" '@{CredSSP="true"}'
cmd.exe /c winrm set "winrm/config/listener?Address=*+Transport=HTTPS" "@{Port=`"5986`";Hostname=`"packer`";CertificateThumbprint=`"$($Cert.Thumbprint)`"}"
cmd.exe /c netsh advfirewall firewall set rule group="remote administration" new enable=yes
cmd.exe /c netsh firewall add portopening TCP 5986 "Port 5986"
cmd.exe /c net stop winrm
cmd.exe /c sc config winrm start= auto
cmd.exe /c net start winrm

</powershell>
```

**Comment by SNikalaichyk** [comment]
Hi @lmayorga1980, it's not Packer's fault. You need to run Sysprep.

[Using Sysprep with EC2Launch](https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/ec2launch.html#ec2launch-sysprep)

Add the following to the `provisioners` section:

```json
{
    "type": "powershell",
    "inline": [
        "C:/ProgramData/Amazon/EC2-Windows/Launch/Scripts/InitializeInstance.ps1 -Schedule",
        "C:/ProgramData/Amazon/EC2-Windows/Launch/Scripts/SysprepInstance.ps1 -NoShutdown"
    ]
}
```

**Comment by lmayorga1980** [comment]
@SNikalaichyk I did no know I have to add those. I will add that change and get back to this issue.

**Comment by lmayorga1980** [comment]
@SNikalaichyk Seems like that was the missing part.  I don't think is part of the documentation yet but I can add it in a PR. :+1:

**Comment by mwhooker** [comment]
That would be really helpful, thanks!

**Comment by shadycuz** [comment]
How would you deal with this on a 2012r2? @lmayorga1980 @SNikalaichyk

**Comment by lmayorga1980** [comment]
@shadycuz you don't need that extra config.

**Comment by shadycuz** [comment]
@lmayorga1980 We build a windows instance with packer, and then we can't login to it. I'm guessing we should provision our own user or something and then use that user to join the domain? 

![image](https://user-images.githubusercontent.com/17090999/44125439-9dd61410-a000-11e8-98d6-637bd0be4a0b.png)

**Comment by lmayorga1980** [comment]
@shadycuz are you using an amazon ami? Or are you uploading your own `ova` file? If you are uploading then you need to set the Administrator password and pass it to your winrm configuration. If you are using amazon ami then Packer will retrieve it for you and you don't have to do anything.

https://github.com/LM3CORP/packer-ami-builder/blob/master/packer-win2016-ami.json (In this case, I don't have to pass the password because packer will retrieve it during the build process. Later during the ec2 instance creation, you can use your private key to decode the password.)

**Comment by shadycuz** [comment]
@lmayorga1980 This is our Base AMI `ami-aeffbcd6`. Yet we can't seem to connect to it after it comes up. I'm looking at the scripts the team is currently running on it.

**Comment by shadycuz** [comment]
They are doing nothing to users, just installing sql.

**Comment by shadycuz** [comment]
Thanks @SNikalaichyk
