### ISSUE TITLE
Windows-Restart provisioner: Lots of usage messages from shutdown.exe after switching to SSH communicator

### ISSUE THREAD

**Issue by dhs-rec** [hashicorp/packer#6301]
Due to the inherent instability of WinRM inside Packer (connection attempts hanging while at the same time WinRM connections can be established just fine with a Ruby script), I decided to give Win32-OpenSSH a try. It works fine, except for lots of usage messages (I counted 218 for a total of 3 restarts executed throughout the template) from shutdown.exe that pollute the log output whenever the Windows-Restart provisioner is used (with default restart_command). It finally manages to restart the machine, but seeing those messages in the output first rings an alarm bell.

- Packer version: 1.2.3
- Host: Ubuntu Linux

**Comment by dhs-rec** [comment]
In the output, before the first usage message, I also see the "Waiting for machine to restart..." message, so the problem might come from `var TryCheckReboot = "shutdown.exe -f -r -t 60"` (line 23), which uses "-" instead of "/" for specifying the options.

**Comment by theodoregoetz** [comment]
I can verify that changing this line to `var TryCheckReboot = "shutdown.exe /f /r /t 60"` does not fix this problem and yields the same behavior. Additionally, I find that Windows 10 is not being restarted/rebooted when using the ssh connector. In the vagrant code `vagrant/plugins/guests/windows/cap` which is referenced in packer's `packer/provisioner/windows-restart/provisioner.go` there is is an interesting comment: 

```
module VagrantPlugins
  module GuestWindows
    module Cap
      class Reboot
        def self.wait_for_reboot(machine)
          # Technically it should be possible to make it work with SSH
          # too, but we don't yet.
          return if machine.config.vm.communicator != :winrm
...
```

Once the `packer build` is aborted, I can ssh into the windows 10 guest and run `shutdown /r /f /t 0` and the machine is then rebooted as expected, but I can't seem to get packer to successfully run shutdown.

- CentOS 7 Host
- Windows 10 Guest
- VirtualBox 5.2
- Packer version 1.2.6 ( master branch at 07cafb80e )

**Comment by SwampDragons** [comment]
I've attached a linux build of something I think will fix this issue for you in PR #6606 -- can you test it out and let me know if it works for you?

**Comment by dhs-rec** [comment]
@SwampDragons, thanks a lot. Seems to solve the problem described here.

However, I see lots of problems while waiting for the produced AMI in AWS:
```
amazon-ebs: Waiting for AMI to become ready...
amazon-ebs: Error waiting for AMI. Reason: <nil>
amazon-ebs: Terminating the source AWS instance...
```

**Comment by SwampDragons** [comment]
A different problem is progress to me!  Can you run your build with `PACKER_LOG=1` and give me the full output on that new error?

**Comment by SwampDragons** [comment]
Without your logs I can't be certain but I suspect you are hitting the timeout described in https://github.com/hashicorp/packer/issues/6536, and that you can work around this timeout by setting the environment variables AWS_MAX_ATTEMPTS and AWS_POLL_DELAY_SECONDS as described in that ticket.
