### ISSUE TITLE
Deadlock if multiple iso_urls resolving from user variables point to the same URL.

### ISSUE THREAD

**Issue by dragon788** [hashicorp/packer#6304]
Packer version: 1.2.3 and 1.1.3 both deadlock
Host: Tested on Ubuntu 16.04 and Ubuntu 18.04

While updating a template to enable better reuse/customization but with sane defaults we ran into an issue where attempting to build caused a deadlock of Packer to the point that it was ignoring Ctrl+C and had to be killed TWICE using `killall packer` or once with `killall -9 packer`.

This stumped us for quite a while until we realized that the build failing had `iso_url` defaulted in the template and we were passing `mirror` and `mirror_directory` and `iso_name` via the var-file but they resulted in the same URL being accessed.

The odd thing was that this deadlock occurred even if we also had a local path defined via `iso_path` and `iso_name` and had the ISO already downloaded. This was really strange as I wouldn't have expected Packer to make a call out to the web until it tried the local first, but perhaps the order doesn't matter and deeper in the code it figures out that it should prefer local files over remote after securing locks on the cache files (where the deadlock appears to occur).

We are using https://github.com/boxcutter/ubuntu as a base but this behavior isn't related to anything else in their templates.

ISO section of any builder (we used virtualbox-iso)
```json
      "iso_checksum_url": "{{user `mirror`}}/{{user `mirror_directory`}}/SHA256SUMS",
      "iso_checksum_type": "{{ user `iso_checksum_type` }}",
      "iso_urls": [
        "{{ user `iso_path` }}/{{ user `iso_name` }}",
        "{{user `mirror`}}/{{user `mirror_directory`}}/{{ user `iso_name` }}",
        "{{ user `iso_url` }}"
      ],
```

User vars at bottom of template
```json
    "iso_checksum_type": "sha256",
    "iso_name": "ubuntu-16.04.4-server-amd64.iso",
    "mirror": "http://releases.ubuntu.com",
    "mirror_directory": "16.04",
    "iso_path": "/var/cache/iso",
    "iso_url": "http://releases.ubuntu.com/16.04/ubuntu-16.04.4-server-amd64.iso",
```

Very unhelpful output when it deadlocks.

https://gist.github.com/dragon788/e537314dae8f14eecc6cd1606e257c66

**Comment by azr** [comment]
Hello there as per f2fb985 this issue is fixed and should have been closed. The `close #xxx and #6304` doesn't work :); it should have been `close #xxx and close #6304`.
