### ISSUE TITLE
amazon-chroot add tags on CreateVolume

### ISSUE THREAD

**Issue by thenom** [hashicorp/packer#6309]
Reference:
https://www.packer.io/docs/builders/amazon-chroot.html

Unless i am missing something, there doesn't seem to be a way to tag the created volume to attach.  We run quite a large infrastructure and have policies governing it that forces certain tags onto most resources in AWS which includes Volumes.

Is there anyway as part of an amazon-chroot build that on create-volume tags can be passed also?  If not then can this be put in as a feature request?

**Comment by mwhooker** [comment]
you're right! This should definitely exist.

I think this would be a great first issue if anyone wants to help. I think we should add a new `root_volume_tags` attribute, and then pass those tags to CreateVolume.TagSpecification. There's lots of existing code that does similar things, but we'll be happy to answer questions

**Comment by anshulaa** [comment]
@mwhooker Shall I pick it up If it's fine with you?

**Comment by SwampDragons** [comment]
Please do, @anshulaa! Thank you.
