### ISSUE TITLE
Document how to skip SSH provisioning with vmware-iso builder

### ISSUE THREAD

**Issue by Routhinator** [hashicorp/packer#6312]
I see an option was added to skip SSH provisioning with communications: none, but I cannot figure out how to make this work with the vmware-iso builder. I'm building a template that cannot have network provisioned for use with the Ansible vmware_guest module. I don't need any SSH post provisioning as I've added the shutdown option to the debian preseed.cfg

**Comment by rickard-von-essen** [comment]
Could you describe the problem you are having.
