### ISSUE TITLE
Feature request: Oracle - OCI - Tagging support for instance (during build) and image

### ISSUE THREAD

**Issue by Marcus-James-Adams** [hashicorp/packer#6313]
Oracle has introduced a tagging schema to their OCI setup.
It can be applied to both instances and images.
https://docs.us-phoenix-1.oraclecloud.com/Content/General/Concepts/resourcetags.htm
https://docs.us-phoenix-1.oraclecloud.com/api/#/en/iaas/20160918/Instance/
https://docs.us-phoenix-1.oraclecloud.com/api/#/en/iaas/20160918/Image/

When using packer in large production environments it would be good if you could set either free form or predefined tags via the builder so that other processes can pick up on them eg billing, security monkey, etc

**Comment by owainlewis** [comment]
@Marcus-James-Adams thanks for raising this. We agree it's a useful feature and will add support for tagging to the OCI builder.

**Comment by harveylowndes** [comment]
@owainlewis it seems like we will have to wait until the upgrade to the SDK is re-merged before we can do this. Do you know if the issue in the SDK have been fixed?

**Comment by prydie** [comment]
@harveylowndes it was never reverted AFAIK?

**Comment by milliams** [comment]
This issue was closed but it was only half-implemented. The builder supports tagging the resulting image but not tagging the instance used to perform the build. The Google and AWS builders support this for example.

**Comment by jsgarmon** [comment]
+1 for tagging instances. Should be pretty straight forward considering [LaunchInstanceDetails](https://github.com/oracle/oci-go-sdk/blob/master/core/launch_instance_details.go#L23) (which you call in [CreateInstance](https://github.com/hashicorp/packer/blob/d15f43e4eb9a7fb3d1a5e0c51d4bde2fceae5f83/builder/oracle/oci/driver_oci.go#L54)) supports both `DefinedTags` and `FreeformTags`.
