### ISSUE TITLE
HEAD breaks HyperV BSD Builds

### ISSUE THREAD

**Issue by ladar** [hashicorp/packer#6315]
The latest packer snapshot, 1.2.4-dev, no longer detects the guest IP address for FreeBSD/OpenBSD on Windows 10 with Hyper-V. Linux builds seem to be unaffected. The packer log file indicates the auto-detected address is wrong as it indicates packer is trying to ssh to ":1" ... disabling IPv6 has no affect ... reverting to the official 1.2.3 version avoids the issue. The log looks as follows:

```
2018/05/26 23:27:53 packer.exe: 2018/05/26 23:27:53 [DEBUG] TCP connection to SSH ip/port failed: dial tcp: lookup 1: no such host
```

**Comment by SwampDragons** [comment]
Hmm. Probably related to https://github.com/hashicorp/packer/pull/6219

**Comment by ladar** [comment]
Let me know when I should re-test against HEAD. I've currently locked my HyperV build bot to 1.2.3 because switching between 1.2.3 and 1.2.4/1.3.0 was causing problems. Version 1.2.4, and above launches a GUI client by default (a change from previous versions), without "headless: true", but if I add headless, the templates won't validate when I run the BSD configs by themselves using version 1.2.3.

**Comment by SwampDragons** [comment]
@ladar thanks. When I reviewed, I must have misread; I thought it was going to use both mechanisms.

**Comment by jborean93** [comment]
I thought the logic should still try both but obviously that’s not happening. Do you have an easy way that I can reproduce this so I can have a look in the coming days? I don’t have much experience with BSD and it would be great if you had a Packer.json file I could use.

**Comment by ladar** [comment]
@jborean93 Yes. Try this repo: https://github.com/lavabit/robox/

Note the current ```generic-hyperv.json``` template requires pull request https://github.com/hashicorp/packer/pull/6357 Alternatively, if you go back in the commit history a few days, you can find a template that doesn't require it.

The ```robox.sh``` script only has limited testing on Windows, but it should work inside a MinGW 64 bash shell (the default Windows bash shell doesn't find the packer command, because it's looking for packer.exe). To build the BSD configurations, run the following inside a MinGW64 shell:

```bash
git clone https://github.com/lavabit/robox/robox.git && cd robox
./robox.sh box generic-freebsd11-hyperv,generic-openbsd6-hyperv
```

Or, alternatively, to run via a DOS prompt:

```batch
SET VERSION=1.0.0
SET VAGRANT_CLOUD_TOKEN=TOKEN
git clone https://github.com/lavabit/robox/robox.git
cd robox
packer build -parallel=false -only=generic-freebsd11-hyperv,generic-openbsd6-hyperv generic-hyperv.json
```
Like I said above, the current generic templates use the ```split``` template function found in the above pull request. You can either use an older commit, or remove the post-processor section entirely.

**Comment by jborean93** [comment]
@ladar @SwampDragons sorry for taking my time here, only just started looking into it now. I've found the cause and will have a PR shortly. Just running some more tests to make sure I don't break anything further.

**Comment by jborean93** [comment]
Here is the PR https://github.com/hashicorp/packer/pull/6397, it will be great if you could test it out, it works for me locally so it should solve the issue.

**Comment by SwampDragons** [comment]
@ladar would love validation from you that #6397 fixes this, before we merge. I've attached a windows binary of that branch to the PR, in case you have a chance to test.

**Comment by ladar** [comment]
Will test shortly. I'll need to recompile with my own pull request: https://github.com/hashicorp/packer/pull/6357 otherwise my templates won't validate properly. I could use a second set of eyes on that pr #6357, if you have the time?

**Comment by ladar** [comment]
Out of curiosity, do you want me to just test the FreeBSD/OpenBSD builds, or should I test all ~40 HyperV builds (25 different operating systems)?

**Comment by ladar** [comment]
@SwampDragons the FreeBSD and OpenBSD builds completed successfully. I tried running a complete build, but I'm running into a larger than normal number of "Error uploading box!" I'll have to try it again, at a later date. 

I assume you'll close this ticket once the merge is complete.
