### ISSUE TITLE
Packer windows 2016 Root volume Issue ,trying to attach root volume but all the empheral volumes are getting attached

### ISSUE THREAD

**Issue by Otsuka-ansible** [hashicorp/packer#6320]
When I am trying to encrypt root volume, all other volumes are being attched.
Could anyone give me script which attach only encrypted root volume?

```json
{
  "builders": [
    {
      "type": "amazon-ebs",
      "access_key": "xxxxxxxx",
      "secret_key": "xxxxxxxxxx",
      "region": "us-east-1",
      "instance_type": "t2.micro",
      "source_ami": "ami-f0df538f",
      "ami_name": "packer-demo-{{timestamp}}",
      "user_data_file": "./bootstrap_win.txt",
      "communicator": "winrm",
      "winrm_username": "Administrator",
      "winrm_password": "SuperS3cr3t!",
	  "encrypt_boot": true,
	  "ami_block_device_mappings": [
                  {
                    "virtual_name": "root",
					"device_name": "/dev/sda1",
                    "volume_type": "gp2",
                    "volume_size": 100,
                    "encrypted": true,
                    "delete_on_termination": false
                  }
              ]
     
	 
    }
  ],
  "provisioners": [
    {
      "type": "powershell",
      "environment_vars": ["DEVOPS_LIFE_IMPROVER=PACKER"],
      "inline": [
        "Write-Host \"HELLO NEW USER; WELCOME TO $Env:DEVOPS_LIFE_IMPROVER\"",
        "Write-Host \"You need to use backtick escapes when using\"",
        "Write-Host \"characters such as DOLLAR`$ directly in a command\"",
        "Write-Host \"or in your own scripts.\""
      ]
    },
    {
      "type": "windows-restart"
    },
    {
      "script": "./sample_script.ps1",
      "type": "powershell",
      "environment_vars": [
        "VAR1=A$Dollar",
        "VAR2=A`Backtick",
        "VAR3=A'SingleQuote",
        "VAR4=A\"DoubleQuote"
      ]
    },
	{
    "type": "powershell",
    "inline": [
      "C:\\ProgramData\\Amazon\\EC2-Windows\\Launch\\Scripts\\InitializeInstance.ps1 -Schedule",
      "C:\\ProgramData\\Amazon\\EC2-Windows\\Launch\\Scripts\\SysprepInstance.ps1 -NoShutdown"
    ]
  }
  ]
}
```

![image](https://user-images.githubusercontent.com/38226637/40616272-6fefb8f2-6258-11e8-891b-033822fb23ce.png)

**Comment by rickard-von-essen** [comment]
Please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

**Comment by rickard-von-essen** [comment]
You should use [no_device](https://www.packer.io/docs/builders/amazon-ebs.html#ami_block_device_mappings) `true` for all devices you want to exclude. Please ask on the mailing list if you need further help.

**Comment by Otsuka-ansible** [comment]
If I specify no_device true like below, will my root volume only gets attached .
And excluding empheral volumes .  can you check the syntax below if wrong correct me.@rickard-von-essen 
 "ami_block_device_mappings": [
                  {
		   "device_name": "/dev/sda1",
                    "volume_type": "gp2",
                    "volume_size": 100,
                    "encrypted": true,
                    "delete_on_termination": false
                  },
               {
                    "no_device": true
		   "device_name": " xvdca", 
                    "volume_type": "gp2",
                    "volume_size": 100,
                    
                  },
                {
                     "no_device": true
		   "device_name": " xvdcb ",      
                    "volume_type": "gp2",
                    "volume_size": 100,
                 
                  },
            {
                     "no_device": true
		   "device_name": "  xvdf ",      
                    "volume_type": "gp2",
                    "volume_size": 100,
                  xvdf      
                  }
              ]
