### ISSUE TITLE
Openstack auth failure with no information

### ISSUE THREAD

**Issue by cholcombe973** [hashicorp/packer#6328]
The openstack builder fails for me against a v3 identify endpoint without given any kind of debug information.  All i see when i enable -debug is:
```Debug mode enabled. Builds will not be parallelized.
openstack output will be in this color.

1 error(s) occurred:

* Authentication failed
``` 
which is the same output i get without debug mode.  I tried testing everything out with the openstack python client and it works fine.  It's leading me to believe something is wrong with packer but I'm not sure what.  
Log output: https://gist.github.com/cholcombe973/5fff6e7b9ea2244b814e07eaa69cde76

Packer version: 1.2.4
Host platform: ubuntu 16.04.4 x86_64
uname -a: 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by rickard-von-essen** [comment]
Unfortunately I'm pretty sure the only information we get from the API is "authorization failed".

**Comment by rickard-von-essen** [comment]
Did you read the docs for [Basic Example: Private OpenStack Cloud](https://www.packer.io/docs/builders/openstack.html#basic-example-private-openstack-cloud) and [Notes on OpenStack Authorization](https://www.packer.io/docs/builders/openstack.html#notes-on-openstack-authorization)?

**Comment by cholcombe973** [comment]
I did yeah.  I sourced the openstack rc before I kicked off packer

**Comment by cholcombe973** [comment]
tcpdump gives me nothing because this is an ssl secured endpoint.

**Comment by cholcombe973** [comment]
```declare -x OS_AUTH_URL="https://identity-ho-c01:5000/v3"
declare -x OS_DOMAIN_NAME="storage-ops"
declare -x OS_IDENTITY_API_VERSION="3"
declare -x OS_INTERFACE="public"
declare -x OS_PASSWORD="****"
declare -x OS_PROJECT_DOMAIN_NAME="storage=ops"
declare -x OS_PROJECT_ID="275f0e33d0bb40f3b858ae2e7b0b8637"
declare -x OS_PROJECT_NAME="storage-ops"
declare -x OS_REGION_NAME="HO-C"
declare -x OS_TENANT_ID="my-user"
declare -x OS_TENANT_NAME="storage-ops"
declare -x OS_USERNAME="my-user"
declare -x OS_USER_DOMAIN_NAME="comcast"
```

**Comment by rickard-von-essen** [comment]
`OS_TENANT_ID="my-user"` doesn't look like a proper id.

**Comment by cholcombe973** [comment]
yeah i just substituted that.  I don't want to give away too many of my credentials online ;)

**Comment by rickard-von-essen** [comment]
I would troubleshoot this by unsetting all the `OS_` environment variables and then only set these:
- OS_AUTH_URL
- OS_USERNAME
- OS_PASSWORD
- OS_DOMAIN_NAME
- OS_TENANT_NAME
- OS_REGION_NAME

And then verify these with `openstack catalog list` if that works I would expect packer to authorise correctly.

**Comment by cholcombe973** [comment]
that did it!  i got some messages about loading the flavor and starting the server.  Thanks for your help!

**Comment by swackhamer** [comment]
I am getting the same thing on openstack queens.
I have these env vars set.  I tried to strip them down to just what you listed but that did not allow openstack catalog list to work.

```
OS_AUTH_URL
OS_REGION_NAME
OS_PROJECT_NAME
OS_USER_DOMAIN_NAME
OS_IDENTITY_API_VERSION
OS_INTERFACE
OS_PASSWORD
OS_USERNAME
OS_PROJECT_ID
OS_CACERT
```
