### ISSUE TITLE
using environment variables

### ISSUE THREAD

**Issue by mhubig** [hashicorp/packer#633]
It would be nice if packer would resolve something like `$HOME` when added to
the variables section.

``` json
"variables": { "ssh_pub_key": "$HOME/.ssh/id_rsa.pub"}
```

Or maybe a more general approach could be a notation for looking up environment variables, like this:

``` js
{{env `SSH_PUB_KEY`}}
```

**Comment by marcofranssen** [comment]
Seems like I can't get it to work properly.

```json
{
    "variables": {
        "cpus": 1,
        "memory": 1024,
        "vram": 12,
        "disk_size": 20000,
        "home_dir": "{{env `HOME`}}"
    },
    "provisioners": [{
        "type": "file",
        "source": "{{user `home_dir`}}/.ssh/id_rsa",
        "destination": "/tmp/host_ssh/id_rsa"
    }]
}

Is this a bug witht he file provisioner or is there a mistake in my config?

**Comment by Purple90** [comment]
@marcofranssen did you ever get it to work?

**Comment by rickard-von-essen** [comment]
That should work, gist a debug log if it doesn't (`PACKER_LOG=1 packer build template.json`)

**Comment by rickard-von-essen** [comment]
See https://www.packer.io/docs/templates/user-variables.html

**Comment by Purple90** [comment]
@rickard-von-essen Yeah, for some reason I still had 'env' in my builder path and not 'user' I reread the variable doc and caught it. For anyone looking this is how I have it now
`{
  "variables": {
    "my_path": "{{env `HOME`}}"
  },
  "builders": [{
    "ssh_private_key_file": "{{user `my_path`}}/.ssh/dev.pem",

  }],`

Thanks Rick

**Comment by rickard-von-essen** [comment]
@mrryanjohnston please ask on the [mailing list](https://groups.google.com/group/packer-tool) for that.
