### ISSUE TITLE
[AWS-EC2]Feature request - add option to make provided SSH public key temporary

### ISSUE THREAD

**Issue by kiwivogel** [hashicorp/packer#6331]
Hullo,

We've started working with inspec to 'test' provisioned ami's prior to deploying, for access we use a provided keypair and expected that to work as a temporary keypair, turns out launching an instance based on the created ami retains the public key provided in the packer build and not the key_name we configured in the launch config. 

Would be nice if we could control the pubkey and still make it temp so the launch config key get's used when we launch the instance.

**Comment by kiwivogel** [comment]
alternatively if someone could give me a pointer to where this could be done in the code I'll be happy to attempt to implement something myself.

**Comment by rickard-von-essen** [comment]
If I understood you correctly the problem is that the pub key in `authorized_keys` when using a given a `ssh_keypair_name` persists in the resulting AMI?

If that is the problem that works as intended. If you need to remove it just do a cleanup in your last provisioner. This is how AWS EC2 + cloud-init works.

**Comment by kiwivogel** [comment]
yeah I figured it was as intended. 
we provide: 
```
    "ssh_keypair_name": "packer_ssh",
    "ssh_private_key_file": "{{user `packer_ssh_key`}}"
```
and those indeed persist in authorized_keys. I figured hooking in a flag that does this via `builder/amazon/common/step_key_pair.go:106` might be a nice feature but I could also just ad a shell provisioner that axes it before packaging..

**Comment by rickard-von-essen** [comment]
We limit Packer to not manage anything "inside" the VM, thus making it OS agnostic.

**Comment by kiwivogel** [comment]
Just a follow up, the issue was caused by cloud-init directly extracting the authorized_keys file path from sshd_config. If there are multiple locations defined this results in a directory with the both locations appended as a path being created which then do not get picked up by the sshd config. Hence the original key baked into the ami does not get overwritten as it should when launching an instance based upon this ami. Since part of the provisioning changes the path(s) this is the likely culprit. Apologies for not digging deeper initially.
