### ISSUE TITLE
Using existing EBS volume to create AMI from scratch

### ISSUE THREAD

**Issue by subbu11** [hashicorp/packer#6335]
Hi,

I need a packer builder/provisioner/post-processor etc.  to create AMI from an existing EBS volume containing OS, without providing source-ami.  The reason I need to use existing EBS volume is that I want to retain my OS data and want Packer to provision/harden/install-drivers,etc on top of it.

I have gone through `amazon-chroot` builder, it has a flag `'from_scratch'` which can be used to create AMI from scratch. It creates a new EBS volume and creates AMI. But this has no option of providing existing AMI. 

I have gone through `amazon-ebssurrogate` builder, it can be used to create AMI by attaching it to a running instance. But as per the required parameters, it needs source_ami. 
 - Please let me know why source_ami parameter is needed here, can we not create AMI based on the 
    attached EBS volume itself ? Is there a way to skip it ?
- If EBS volume is of Windows, then do we need to attach it the running Windows EC2 Instance only ?

I have gone through packer `amazon-import`, it creates OVA, uploads to S3 and create AMI from it. I already have my VMDK (from which EBS volume is created) on S3. Can I use the amazon-import post-processor to directly create AMI from this OVA/VMDK ? 

Please provide any other possible way using packer.

**Comment by rickard-von-essen** [comment]
Please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._
