### ISSUE TITLE
Feature request: aws vpc and subnet filters similar to source_ami_filter

### ISSUE THREAD

**Issue by alanwevans** [hashicorp/packer#6339]
# Story

As a user of Packer to create aws AMIs I would like to be able to use filters to select VPCs and subnets rather than use fixed VPC and Subnet IDs.

## Proposal

```
{
  "vpc_filter": {
    "filters": {
      ...
    },
    "order": "by_name",
    "take_first": true
  }
}
```
Where
- _filters_ are any valid filters as described in [DescribeVpcs](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeVpcs.html)

_order_ and _take_first_ are up for discussion, I could see it left out.  I am thinking of how to deal with multiple responses.  I can imagine a case where someone may expect the filter to return multiple results and the desired one should be chosen based on sort order (MyVPC1, MyVPC2) or better yet available IPs if that's possible.  (though more likely for Subnet)

```
{
  "vpc_filter":
    "filters": {
      ...
    },
    "take_most_free": true,
    "order": "[+-]<field_name>",
    "take_first": true
}
```
Where:
- _filters_ are any valid filters as described in [DescribeSubnets](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeSubnets.html)
  **Note:** the **vpc-id** filter should proobably be automatically added based on the results of _vpc_filter_ or _vpc_id_ builder parameters.
- _take_most_free_ , _order_ and _take_first_ are again up for debate.  Even more than VPC I can imagine a scenario where a filter might match multiple subnets and we might want to take the one with the most free IPs for example.  Consider (Private Subnet A, Private Subnet B, and so on) we might have `{"filters":{"tag:Name": ["Private Subnet*"]}, "order": "-AvailableIpAddressCount", "take_first": true}` might give the subnet with the most available.  Also what about a special _order_ or _take*_ parameter _random_.

**Comment by rickard-von-essen** [comment]
I think this is reasonable, but we should just provide the filters provided by the AWS API and _require that the result contains exactly one item_. Sorting doesn't make sense, in the `source_ami` sorting by creation dated is reasonable. There is no reasonable sorting of VPC/Subnets.

**Comment by alanwevans** [comment]
@rickard-von-essen maybe not sorting but asking for the list to be unique is a bit restrictive.  As I mentioned consider an organization (like mine) that names subnets that include the AZ in the name.

- Private Subnet A
- Private Subnet B
- ...

If the filter must return an exact match I have to essentially hard-code the desired subnet.  In which case I am not much better off than using `subnet_id`.

```
{
  "subnet_filter":
    "filters": {
      "tag:Name": "Private Subnet *"
    },
    "take": "most_free|random"
}
```

Something like above gives some flexibility.  Which is what `subnet_filer` is really meant to do.

**Comment by rickard-von-essen** [comment]
Yeah sorry. VPC's should be exactly one, subnets should have a option to select a random. I don't know if most free IP address is feasible and actually useful. I think we should skip that first.

**Comment by SwampDragons** [comment]
@alanwevans Can you take a look at rickard's linked PR and maybe take it for a spin?

**Comment by SwampDragons** [comment]
@alanwevans I have attached binaries of the branch at #6374; if you're still interested in this feature would you be willing to test the new feature out?
