### ISSUE TITLE
User variables not being interpolated in AMIName within the amazon-ebs builder

### ISSUE THREAD

**Issue by brianeclow** [hashicorp/packer#6345]
When `ami_name` is set to a single user variable, the amazon-ebs builder has no problem interpolating the variable. However, when you build a complex name, it throws an error.

For example, `ami_name` with this format:
```json
{
  "builders": [
    {
...
      "ami_name": "procore-{{user `tag_puppet`}}-{{user `tag_app`}}-ubuntu-16.04-x86_64-{{user `version`}}",
...
    }
  ]
}
```

Will yield this response:
```bash
* AMIName should only contain alphanumeric characters, parentheses (()), square brackets ([]), spaces ( ), periods (.), slashes (/), dashes (-), single quotes ('), at-signs (@), or underscores(_). You can use the `clean_ami_name` template filter to automatically clean your ami name.
```

- Packer version `1.2.4`
- Mac OS `10.12.6`
  
I would be more then happy to make this a single user variable, except, packer does not allow calling the `user` function within the `variable` space.

**Comment by mwhooker** [comment]
Thanks for the report. However, I'm unable to reproduce this. Using:

```json
{
    "builders": [
        {
            "ami_name": "procore-{{user `tag_puppet`}}-{{user `tag_app`}}-ubuntu-16.04-x86_64-{{user `version`}}",
            "instance_type": "t2.micro",
            "region": "us-east-1",
            "tags": {"mwhooker": "amazon-ebs.json"},
            "source_ami_filter": {
                "filters": {
                    "name": "*ubuntu-xenial-16.04-amd64-server-*",
                    "root-device-type": "ebs",
                    "virtualization-type": "hvm"
                },
                "most_recent": true,
                "owners": [
                    "099720109477"
                ]
            },
            "ssh_username": "ubuntu",
            "type": "amazon-ebs"
        }
    ],
    "variables": {
    "tag_puppet": "foo",
    "tag_app": "foo",
    "version": "foo"
    }
}
```

Make sure your variables don't have any forbidden characters in them. If you think this is a bug in packer, please open a new ticket with the steps to reproduce, including a complete config file and the necessary variables.

**Comment by brianeclow** [comment]
🤦‍♂️ 

Yeah, I just realized after an hour of banging my head against this, then filing the issue, one of my vars was capturing `{{` and `}}` from the version variable.

Thank you.
