### ISSUE TITLE
amazon-ebssurrogate ignores changes made by Ansible Provisioner

### ISSUE THREAD

**Issue by lang7** [hashicorp/packer#6353]
Packer version 1.2.4

RHEL 7.4

When using "amazon-ebssurrogate" builder and Ansible provisioner the resulting AMI does not contain any customisations made by the provisioner. Looks like its only a copy of the source AMI root volume.

https://gist.github.com/lang7/5136986c32f5111dfcd5df2a5c4e694b

**Comment by rickard-von-essen** [comment]
You are missing setting Ansible to use the `chroot` communicator, see [Packer Docs  - Ansible: Chroot Communicator](https://www.packer.io/docs/provisioners/ansible.html#chroot-communicator).

**Comment by lang7** [comment]
Adding the  --connection=chroot made no difference. Should I be using ansible-local provisioner ? 

     {
          "type": "ansible",
          "playbook_file": "{{ pck_jenkins_workspace_path }}/configure.yml",
          "extra_arguments": [ 
              "--extra-vars",  ENVNAME={{ pck_vars_ENVNAME }} app_env={{ pck_vars_app_env }} cmk={{ pck_kms_key_id }} pck_jenkins_workspace_path={{ pck_jenkins_workspace_path }}",
              "--connection=chroot",
              "-vvvv"
              ]
      }

**Comment by rickard-von-essen** [comment]
Please [gist](https://gist.github.com/) a full debug log from `PACKER_LOG=1 packer build template.json`.

**Comment by rickard-von-essen** [comment]
Are you sure you are writing to the right device?

**Comment by rickard-von-essen** [comment]
It would also be great if you filled in the example template with real values, now nearly almost everything is a variable and that takes us maintainers time to fill in.

**Comment by lang7** [comment]
Will do - i'll run some builds and update soon, while I do that..... 

I can only see one device mapping option for what i'm trying to do

Existing AMI root device as the base device_name /dev/sda1 which then must match the ami_root device source_device_name which I want to then modify with the Ansible provisioner and create a new AMI with modified /dev/sda1 root device

"launch_block_device_mappings" : [
        {
          "volume_type" : "gp2",
          "device_name" : "/dev/sda1",
          "delete_on_termination" : false,
          "volume_size" : 50
        }
      ],
      "ami_root_device": {
        "source_device_name": "/dev/sda1",
        "device_name": "/dev/sda1",
        "delete_on_termination": true,
        "volume_size": 50,
        "volume_type": "gp2"
      },

**Comment by lang7** [comment]
I'm trying to strip the Billing Product Code from the AMI so I can copy AMI's between AWS Accounts

**Comment by lang7** [comment]
In addition to various Ansible configuration

**Comment by lang7** [comment]
I've created a populated template:
https://gist.github.com/lang7/b63a34717cd2e023d70e048f1a34e941

Waiting on the log to complete

**Comment by lang7** [comment]
The log is pretty big - I don't want to post it all. Are there specific sections that you would be interested in ?

**Comment by rickard-von-essen** [comment]
I'm intereseted in a lot, if you don't want to share parts, create a shorter repro code.

**Comment by rickard-von-essen** [comment]
Closing since no response for a long time.
