### ISSUE TITLE
Timestamp on Console Output

### ISSUE THREAD

**Issue by jhenkens** [hashicorp/packer#6355]
It'd be nice, especially for automated builds, to have a `--timestamp/-t` flag that would add a timestamp to each line of output, as printed to the console.

**Comment by SwampDragons** [comment]
This is a nice idea, but I don't think it's going to be a priority for us, because we already have timestamps set in our debug logs (set the env var PACKER_LOG=1 to turn on debug logs).  PRs are welcome, but since I don't imagine I'll get a chance to work on it soon I'm going to close this issue.
