### ISSUE TITLE
builder/amazon-chroot Problem with pre_mount_commands in last packer version 1.2.4

### ISSUE THREAD

**Issue by resworld** [hashicorp/packer#6358]
- Packer version: 1.2.4
- Host platfofm: Amazon EC2 Centos 7.5.1804
- Full log output of packer with log=1:
https://gist.github.com/resworld/d9d58092dfd6fb45c879b0d239183f52
- I am using example from documentation json file as it's described bellow:
https://gist.github.com/resworld/63d308c595451c8ea67f1e3c7bf44e04

I have a problem with last packer version = 1.2.4 when building an AMI from scratch using amazon-chroot. Same .json file is used for 1.2.4 and 1.2.3, but for last version of packer (1.2.4) failed with following error message:
_2018/06/08 12:37:54 ui error: ==> amazon-chroot: Error executing command: exec: "echo 'Test'": executable file not found in $PATH_

Host Platform's PATH is unchanged:
/sbin:/bin:/usr/sbin:/usr/bin

With previous versions of packer everything seems to work fine with example.json file.

Regards

**Comment by rickard-von-essen** [comment]
Might have been introduced in #5956

**Comment by SwampDragons** [comment]
Sorry about this!  Can you give this binary a try and see if it solves your issue?  (it's a build of the linked PR) 
[packer.zip](https://github.com/hashicorp/packer/files/2085917/packer.zip)

**Comment by SwampDragons** [comment]
Yay! I'm so glad it fixed things.  I'll merge the fix today and it will go out in the next release.
