### ISSUE TITLE
OpenStack builder should use glance imageservice API rather than deprecated nova image API

### ISSUE THREAD

**Issue by furlongm** [hashicorp/packer#6360]
Currently the OpenStack builder uses the deprecated nova image API:

   https://github.com/hashicorp/packer/blob/master/builder/openstack/step_create_image.go#L10

These nova APIs have been deprecated for a long time, and in recent versions of OpenStack (Newton+) they return 404s instead of proxying to glance:

   https://developer.openstack.org/api-ref/compute/#images-deprecated

The glance imageservice API should be used instead to work with these environments.

   https://github.com/gophercloud/gophercloud/tree/master/openstack/imageservice/v2/images

The nova API just proxied to glance, so this should be a backwards compatible change.

**Comment by rickard-von-essen** [comment]
Thanks for the refs, this is definitely on my todo list.

**Comment by ozerovandrei** [comment]
@rickard-von-essen Hello.

Image service API usage was implemented in #6300 (but only for BlockStorage-backend based instances). That PR also contains vendor directory update to use `imageservice/v2/images` Gophercloud package.

Just a notice for you.
