### ISSUE TITLE
Azure: Compilation fails on 32-bit architecture with 

### ISSUE THREAD

**Issue by rickard-von-essen** [hashicorp/packer#6361]
Fails with: `constant 4294967295 overflows int`

After Azure/azure-sdk-for-go#1993 have been resolved we need to update some dependencies.

**Comment by rickard-von-essen** [comment]
FYI @boumenot

**Comment by boumenot** [comment]
Thank you for the heads up!

/cc @harijayms

**Comment by rickard-von-essen** [comment]
Upstream fixed this in https://github.com/Azure/azure-sdk-for-go/releases/tag/v17.3.1.
