### ISSUE TITLE
Windows Reboot / WinRM connection issue regression from Packer v1.2.0

### ISSUE THREAD

**Issue by ysolt** [hashicorp/packer#6368]
Hello,

I'm seeing the following issue on every packer version  >= 1.2.0. I managed to track down the problem to the WinRM module not capable of gracefully reconnecting upon Windows instance reboot after driver installation.

```
Build 'amazon-ebs' errored: Error processing command: Error uploading ps script containing env vars: Couldn't determine whether destination was a folder or file: unknown error Post http://13.57.227.90:5985/wsman: read tcp 10.0.4.2:53266->13.57.227.90:5985: read: connection reset by peer

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Error processing command: Error uploading ps script containing env vars: Couldn't determine whether destination was a folder or file: unknown error Post http://13.57.227.90:5985/wsman: read tcp 10.0.4.2:53266->13.57.227.90:5985: read: connection reset by peer

==> Builds finished but no artifacts were created.
```

- Packer version: issues appears to start in 1.2.0 and remains in 1.2.1, 1.2.2, 1.2.3, and 1.2.4. 1.1.3 works
- Tested on: macOS 10.12.6, Windows 2012r2
- Debug log output from `PACKER_LOG=1 packer build template.json`. [error case with 1.2.4](https://gist.github.com/ysolt/bbddaae8cc585f66ebed4e005a0e6656#file-packer_1-2-4-log) 
[Working case with 1.1.3](https://gist.github.com/ysolt/bbddaae8cc585f66ebed4e005a0e6656#file-packer_1-1-3-log)
- Files to reproduce the issue: 
[template.json](https://gist.github.com/ysolt/bbddaae8cc585f66ebed4e005a0e6656#file-template-json)
[user-data.txt](https://gist.github.com/ysolt/bbddaae8cc585f66ebed4e005a0e6656#file-user-data-txt)  

Thanks for the help!
Zsolt

**Comment by DanHam** [comment]
@ysolt Great work to narrow this down. Even better work making this issue so easily reproducible!!

@SwampDragons I've managed to reproduce this using the slightly modified template [HERE](https://github.com/DanHam/packer-testing/tree/master/aws/packer-6368) and have a working 'fix' in place - see #6388. 

Turns out the error originates from the code that uploads the env vars in the PS provisioner. Wrapping the upload code with the 'retryable' function has hopefully provided a solution - it allows Packer to gracefully handle errors encountered during the upload process due to restarts...

@ysolt Would you be able to test #6388 to see if it fixes the problems you are having?

**Comment by DanHam** [comment]
@ysolt As an aside, I spotted that you were using `winrm quickconfig -q` in your user-data PowerShell script. Using `winrm quickconfig -q` to set up WinRM can cause issues with Packer - see the 'A quick aside/warning' box in the docs [HERE](https://www.packer.io/intro/getting-started/build-image.html#a-windows-example). There's also a working sample user data script in there for you to take a look at. Hope that helps!

**Comment by SwampDragons** [comment]
This is a legitimate bug, but is there a reason you aren't making use of the windows-restart provisioner?

**Comment by ysolt** [comment]
@DanHam: great thanks! Just created a packer build from master. Seems to be working fine!

@SwampDragons yeah:) This is just an example code to reproduce the issue itself. In my use-case the Windows reboot is actually triggered by an Nvidia driver installation, and not a hard-wired reboot:) Will take a deeper look at the winrm configuration examples later. As a first sight it looks nice and clean! Thanks for the pointer!
