### ISSUE TITLE
SSH Agent forwarding to clone private repo

### ISSUE THREAD

**Issue by skk2142** [hashicorp/packer#6376]
Packer v1.2.4
Mac OS 10.13.4
https://gist.github.com/skk2142/c06c48fafabf0cadf9b0e43e1e1372d6

I'm trying to clone a private repo using ssh agent forwarding in packer. On my local machine, `ssh -T git@github.com` is working. `echo "$SSH_AUTH_SOCK"` is working. I've added the ssh key using `ssh-add -K ~/.ssh/id_rsa`. 
Packer with private repo cloning worked the first time but somehow it's not working after restarting the computer. I also switched from using amazon linux as base image to Ubuntu 16. 

Here's the error I'm getting in the log:
```
1528839058,,ui,message,    amazon-ebs: Cloning into '/app'...
1528839058,,ui,message,    amazon-ebs: Host key verification failed.
1528839058,,ui,message,    amazon-ebs: fatal: Could not read from remote repository.
1528839058,,ui,message,    amazon-ebs:
1528839058,,ui,message,    amazon-ebs: Please make sure you have the correct access rights
1528839058,,ui,message,    amazon-ebs: and the repository exists.
```

```
> cat ~/.ssh/config
Host ec2-instance
  Hostname ec2-54-234-58-33.compute-1.amazonaws.com
  User ec2-user
  IdentityFile ~/Documents/Developer/aws/ec2/ec2-masterclass.pem
```

```
> ls ~/.ssh/*
/Users/surajkeshri/.ssh/config				/Users/surajkeshri/.ssh/id_rsa.pub
/Users/surajkeshri/.ssh/google_compute_engine		/Users/surajkeshri/.ssh/known_hosts
/Users/surajkeshri/.ssh/google_compute_engine.pub	/Users/surajkeshri/.ssh/kollate-aws-eb
/Users/surajkeshri/.ssh/google_compute_known_hosts	/Users/surajkeshri/.ssh/kollate-aws-eb.pub
/Users/surajkeshri/.ssh/id_rsa
```

**Comment by rickard-von-essen** [comment]
Please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._

**Comment by rickard-von-essen** [comment]
Please post on the mailing list. With some more debug info:

A good way to troubleshoot this is to start by adding the following provisioning section:

```json
{
  "type": "shell",
  "inline": [
    "echo $SSH_AUTH_SOCK",
    "ssh-agent -L"
  ]
}
```

And see if the list contains the fingerprint you expect.

**Comment by skk2142** [comment]
Yes this works as expected. Agent forwarding seems to work. Here's the output of the following provisioning: 
```
    {
      "type": "shell",
      "inline": [
        "echo $SSH_AUTH_SOCK",
        "set | grep -i ssh",
        "ssh-add -l"  
      ]
    },
```
```
1528873074,,ui,message,    amazon-ebs: /tmp/ssh-YlcRKUCOyZ/agent.1392
1528873074,,ui,message,    amazon-ebs: SSH_AUTH_SOCK='/tmp/ssh-YlcRKUCOyZ/agent.1392'
1528873074,,ui,message,    amazon-ebs: SSH_CLIENT='MY_IP 55770 22'
1528873074,,ui,message,    amazon-ebs: SSH_CONNECTION='MY_IP 55770 172.31.94.44 22'
1528873074,,ui,message,    amazon-ebs: 2048 SHA256:MEb9UopEbof8j+C2op6... /Users/username/.ssh/id_rsa (RSA)
```

**Comment by skk2142** [comment]
I think I found the issue. The github public key is not getting copied in the remote machine. I'm unable to fix it yet though. On the remote host, it only shows these when I run `ssh-keyscan github.com`
```
1528874121,,ui,message,    amazon-ebs: # github.com:22 SSH-2.0-libssh_0.7.0
1528874121,,ui,message,    amazon-ebs: # github.com:22 SSH-2.0-libssh_0.7.0
1528874121,,ui,message,    amazon-ebs: # github.com:22 SSH-2.0-libssh_0.7.0
```
