### ISSUE TITLE
Alicloud Packer: TLS handshake timeout when run build command in India

### ISSUE THREAD

**Issue by marlincq** [hashicorp/packer#6382]
Packer Version: 1.2.4
Host Platform: ubuntu 14.04

Run "packer build xxx.json"  in local laptop in India
==> alicloud-ecs: Timeout waiting for image to be created: Aliyun API Error: RequestId:  Status Code: -1 Code: AliyunGoClientFailure Message: Get https://ecs-cn-hangzhou.aliyuncs.com?AccessKeyId=xxxx&Action=DescribeImages&Format=JSON&ImageId=m-t4n5rx6tfbsdpjjnlkan&RegionId=ap-southeast-1&SignatureMethod=HMAC-SHA1&SignatureNonce=xxxxx&SignatureVersion=1.0&Status=Creating&Timestamp=2018-06-13T04%3A28%3A47Z&Version=2014-05-26&Signature=xxxx%3D: net/http: TLS handshake timeout
TLSHandshakeTimeout=120

I found that  the packer use service point:https://ecs-cn-hangzhou.aliyuncs.com

But the alicloud says that should use  https://ecs.ap-northeast-1.aliyuncs.com if my Region is ap-southeast-1  in document:https://www.alibabacloud.com/help/doc-detail/25489.htm?spm=a2c63.p38356.b99.276.25e14d36iVVhg3

**Comment by zhuzhih2017** [comment]
@marlincq  You can using environment  ECS_ENDPOINT to change the default endpoint from https://ecs-cn-hangzhou.aliyuncs.com to https://ecs.ap-northeast-1.aliyuncs.com Thanks.

**Comment by zhuzhih2017** [comment]
@marlincq by the way, could you give me the simple information about the packer template which include the region you want to create image. Thanks.

**Comment by chhaj5236** [comment]
We have updated the official doc for making this clear. See https://github.com/hashicorp/packer/pull/7329 for details.
