### ISSUE TITLE
Error unmarshalling error response from DigitalOcean API when destroying droplet

### ISSUE THREAD

**Issue by schnittchen** [hashicorp/packer#6384]
- Packer v1.2.4
- Docker on DigitalOcean,
`Linux d229cf74936b 4.4.0-127-generic #153~14.04.1-Ubuntu SMP Sat May 19 14:00:03 UTC 2018 x86_64 Linux`
- Debug log output from `PACKER_LOG=1 packer build template.json`

(truncated)
```
2018/06/14 11:46:34 ui: ==> digitalocean: Destroying droplet...
==> digitalocean: Destroying droplet...
2018/06/14 11:46:44 ui error: ==> digitalocean: Error destroying droplet. Please destroy it manually: json: cannot unmarshal object into Go struct field ErrorResponse.message of type string
==> digitalocean: Error destroying droplet. Please destroy it manually: json: cannot unmarshal object into Go struct field ErrorResponse.message of type string
2018/06/14 11:46:44 ui: ==> digitalocean: Deleting temporary ssh key...
```

**Comment by rickard-von-essen** [comment]
Please supply the information requested in the issue template:
- Packer version (`packer version`)
- Host platform (`uname -a` etc.)
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a [gist](https://gist.github.com).
- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your [gist](https://gist.github.com).

**Comment by schnittchen** [comment]
I've updated the initial comment.

Reproducing is a bit tricky because it is triggered by what seems to be a bug in the DO API which does not always happen. I have a support ticket open with them about their API, which shows up in three different ways:

* `Error shutting down droplet: POST https://api.digitalocean.com/v2/droplets/97775806/actions: 500 Server was unable to give you a response.` (this one is obvious and I believe there is nothing packer can do here)
* `Error shutting down droplet: invalid character '<' looking for beginning of value` looks like the server response is HTML, and the JSON parser chokes on this. Support is asking me if I can somehow show them the response. Is there some mechanism with which I can see more of the API request, so maybe I can try to reproduce it using `curl`?
* `Error destroying droplet. Please destroy it manually: json: cannot unmarshal object into Go struct field ErrorResponse.message of type string` is what this issue is about. Reproducing the API call would help digging deeper into this issue. Is there something like a higher level of verbosity?

**Comment by andrewsomething** [comment]
The DigitalOcean API should not be returning an HTML response. Opening a support ticket is the right course of action there so we can get to the bottom of the issue. So thank you for doing just that!

On the Packer side, this can be handled more cleanly by pulling a newer version of godo containing this PR: https://github.com/digitalocean/godo/pull/156 While it won't resolve the issue on the DO side, it will stop Packer from choking on the miss-formatted error and return it to the user.

**Comment by schnittchen** [comment]
I was able to replicate the issue on my laptop, using packer.

I am still trying to demonstrate that the API response is indeed HTML sometimes. In order to do that, I wrote this cute little script:

```
set -euo pipefail
IFS=$'\n\t'

droplet_id=98049784
action_id=`
  curl -s -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $digital_ocean_api_key" -d '{"type":"snapshot","name":"debug"}' "https://api.digitalocean.com/v2/droplets/$droplet_id/actions" |
  jq '.action.id'
  `

for i in {1..50}; do
  curl -s -X GET -H "Content-Type: application/json" -H "Authorization: Bearer $digital_ocean_api_key" "https://api.digitalocean.com/v2/droplets/$droplet_id/actions/$action_id"
  echo
  sleep 1
done
```

However, the script worked fine and returned proper JSON every time. Obviously the script is just toying around what packer really does. Also, I did not dig deep into godo to see where possible differences could come from.

If anybody knows of some more details (request sequence, headers, whatnot), maybe it is possible to replicate the problem this way.

Otherwise I would have to mess around with some go code, which I am new to.

**Comment by rickard-von-essen** [comment]
You could try patching your godo using [`DumpResponse`] (https://golang.org/pkg/net/http/httputil/#DumpResponse) and log responses to a file. 

(You also have to remove `govendor sync` from the `Makefile` to not overwrite your changes.)

**Comment by schnittchen** [comment]
It looks like Digitalocean fixed the issue.

**Comment by thinkmassive** [comment]
For the anyone who runs across this from a search, here is what DO mentioned in a response to my own support case for the same issue:

>  This can happen sometimes when Cloudflare possibly blocks a request, or our API experiences an issue, or something else altogether.

My guess is that it's usually Cloudflare, so that's probably a good place to continue troubleshooting. Obviously having the response headers and body is the best way to proceed.
