### ISSUE TITLE
exist status 137 docker builder

### ISSUE THREAD

**Issue by AStrangwood** [hashicorp/packer#6391]
I am having an issue running a docker build via packer, it is failing with the below error. Now i have used the same script in this build in a docker file and it builds without issue so im not sure why packer would be having this issue. 

I have increased the resources of the docker vm to be 80gb in size with 20gb ram, so its defiantly not a resource issue which i have seen can cause exist status 137

> ==> docker: Killing the container: 0fd6ea2432ec807f14f30d434d5109b4c4ab0177573fc8555979c259d01d2b91
> Build 'docker' errored: Script exited with non-zero exit status: 137
> 
> ==> Some builds didn't complete successfully and had errors:
> --> docker: Script exited with non-zero exit status: 137

The part of the shell script that always produces the error.

> /tmp/server_t/db2setup -f sysreq -r /tmp/db2v10.5.rsp
  

- Packer - 1.2.4
- Host - Windows 10
- docker - 18.03.1-ce
- Logs - https://gist.github.com/AStrangwood/9f25e1aaa11d112c8c902b61f3476dc6

**Comment by SwampDragons** [comment]
Have you tried addressing the installation errors in the logs?

```ERROR:
2018/06/15 16:24:11 ui:     docker:    The 'strings' utility that is used to detect prerequisite libraries
2018/06/15 16:24:11 ui:     docker:    is not present on this system.  Please use your package or software
2018/06/15 16:24:11 ui:     docker:    manager to install the GNU Binary Utilities.
2018/06/15 16:24:11 ui:     docker: Requirement not matched for DB2 database "Server" . Version: "10.5.0.9".
2018/06/15 16:24:11 ui:     docker:
2018/06/15 16:24:11 ui:     docker: Summary of prerequisites that are not met on the current system:
2018/06/15 16:24:11 ui:     docker:
2018/06/15 16:24:11 ui:     docker:    DBT3514W  The db2prereqcheck utility failed to find the following 32-bit library file: "/lib/i386-linux-gnu/libpam.so*".
2018/06/15 16:24:11 ui:     docker:
```

**Comment by SwampDragons** [comment]
right but I think there's a chance that those errors are causing a non-zero exit code. Have you tried explicitly exiting 0 after the install runs?

**Comment by AStrangwood** [comment]
I have tried exit 0 and it still gives me the same error.

**Comment by SwampDragons** [comment]
I'll take a look at this when I get a chance, but in the meantime it may be worth bringing this to the mailing list; my spidey sense says this may be something that other Docker users have experienced and know work-arounds for

**Comment by rickard-von-essen** [comment]
Please provide a template and scripts to reproduce..

**Comment by rickard-von-essen** [comment]
Exit status 137 means the process is killed with SIG KILL (9), see http://tldp.org/LDP/abs/html/exitcodes.html.

**Comment by AStrangwood** [comment]
All the files below to reproduce the issue, if there is anything you need just shout. I included the free version of the software im installing which i can confirm also produces the error.

https://drive.google.com/open?id=1rj6JrKTbtADw1WAEyNwPBOn5bvtCCsUX
https://drive.google.com/open?id=1Wq9G7PPHqCJYE-jn5c68zb8AJLWxjgnJ 
https://drive.google.com/open?id=1ll3Orz1ZQMFnrzZGVtz84TO4DgBGMRLO 
https://drive.google.com/open?id=1Dxv80R7bR6XLtvWOgwbWMpcIOraAC9qY

**Comment by rickard-von-essen** [comment]
Could you provide an url that doesn't require login.

**Comment by AStrangwood** [comment]
Thats odd it doesn't ask me to log in to download them.

Try
https://drive.google.com/file/d/1rj6JrKTbtADw1WAEyNwPBOn5bvtCCsUX 
https://drive.google.com/file/d/1Wq9G7PPHqCJYE-jn5c68zb8AJLWxjgnJ
https://drive.google.com/file/d/1ll3Orz1ZQMFnrzZGVtz84TO4DgBGMRLO
https://drive.google.com/file/d/1Dxv80R7bR6XLtvWOgwbWMpcIOraAC9qY

**Comment by AStrangwood** [comment]
@rickard-von-essen has any progress been made on this?

**Comment by rickard-von-essen** [comment]
This is caused by the installer running with a tty. If you add this line to you `docker` builder section it works.

```json
            "run_command":  ["-d", "{{.Image}}", "/bin/bash", "-c", "sleep 3600"]
```
