### ISSUE TITLE
ansible provisioner - error on default "--extra-vars" 

### ISSUE THREAD

**Issue by MouBoul** [hashicorp/packer#6400]
We are using packer to build images on AWS and want to implement the ansible provisioner (not the ansible-local).
Unfortunately we get an error when using this 
`amazon-ebs: ERROR! the playbook: packer_builder_type=amazon-ebs could not be found`

This is due to the default extra-vars packer is adding to the ansible run

`ansible-run --extra-vars packer_build_name=amazon-ebs packer_builder_type=amazon-ebs -i /var/folders/hc/5s01h6mj0hgds8wqb9qjvfmc1hq406/T/packer-provisioner-ansible447311094`

We are using the following config:

```"provisioners" :[
    {
      "type": "ansible",
      "playbook_file": "../ansible/playbooks/node_exporter.yml",
      "command": "ansible-run",
      "skip_version_check": true,
      "extra_arguments": [
        "-A", "../ansible/", 
        "-I", 
        "-N"
      ]
    }
```

I think this is related to the issue #5885

The command that packer runs is as follows:

```
amazon-ebs: [run]   COMMAND:  ansible-playbook  --extra-vars [...] --extra-vars 'packer_build_name=amazon-ebs' 'packer_builder_type=amazon-ebs' -i '/var/folders/hc/5s01h6mj0hgds8wqb9qjvfmc1hq406/T/packer-provisioner-ansible447311094 [...]'
```

Packer version:
`Packer v1.2.4`

**Comment by rickard-von-essen** [comment]
What's your ansible version?

**Comment by rickard-von-essen** [comment]
This is caused by the `ansible-run` script which contains a bug and does [word splitting](https://github.com/koalaman/shellcheck/wiki/SC2086).

**Comment by tjbaker** [comment]
I have the same problem and can't resolve it, not matter how I quote things.  This project works with Packer 1.0.0 and Ansible 2.2.1.0.

When I update to Packer 1.2.4 the extra vars passed into Ansible don't work.  I've tried updating Ansible to latest 2.6.1 and get the same result.  Attempting to use vars passing in result in `VARIABLE IS NOT DEFINED`


```
    amazon-chroot: Executing Ansible: cd /tmp/packer-provisioner-ansible-local/5b47e1da-bd24-809c-8fef-44b99ce98162 && /usr/local/bin/ansible-playbook -i foo, /tmp/packer-provisioner-ansible-local/5b47e1da-bd24-809c-8fef-44b99ce98162/post-pack.yml --extra-vars "packer_build_name=amazon-chroot packer_builder_type=amazon-chroot packer_http_addr=" -e application=base -e envname=staging -c local -i /tmp/packer-provisioner-ansible-local/5b47e1da-bd24-809c-8fef-44b99ce98162/packer-provisioner-ansible-local506635840
    amazon-chroot:
    amazon-chroot: PLAY [localhost] ***************************************************************
    amazon-chroot:
    amazon-chroot: TASK [debug] *******************************************************************
    amazon-chroot: ok: [localhost] => {
    amazon-chroot:     "application": "VARIABLE IS NOT DEFINED!"
    amazon-chroot: }
```

**Comment by rickard-von-essen** [comment]
@tjbaker open a new issue and supply all requested info.

**Comment by xmj** [comment]
Packer 1.2.4 / Ansible 2.6.0 has the same issue... my pull request simply does multiple -e calls

**Comment by rickard-von-essen** [comment]
@xmj create a new issue with full repro case.

**Comment by tamsky** [comment]
possibly related: #6493
