### ISSUE TITLE
Error using MFA and profile in AWS 

### ISSUE THREAD

**Issue by christiangda** [hashicorp/packer#6401]
I'm using packer to build my own Windows AMI on AWS, every is fine whe I use packer on server inside aws account, but when I try to run packer into my local  laptop using the followin command: 

`
$> AWS_PROFILE=level PACKER_LOG=1 packer build packer_template.json
`

 I got the the following error:

> Build 'AMI Windows Builder' errored: AssumeRoleTokenProviderNotSetError: assume role with MFA enabled, but AssumeRoleTokenProvider session option not set.
> 
> ==> Some builds didn't complete successfully and had errors:
> --> AMI Windows Builder: AssumeRoleTokenProviderNotSetError: assume role with MFA enabled, but AssumeRoleTokenProvider session option not set.
> 

Debug Information:

- Packer version --> 1.2.4
- Host platform --> Fedora 28 (Linux host.network.local 4.16.15-300.fc28.x86_64 #1 SMP Tue Jun 12 00:42:35 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux)
- Debug log output --> https://gist.github.com/christiangda/2a572ea77fa783f2282ff0ecb696f732
- The _simplest example template and scripts_ needed to reproduce the bug. 
  - Template --> https://gist.github.com/christiangda/66a8eff80860dfc53e7875afae61ea28
  - Command line to reproduce the bug --> https://gist.github.com/christiangda/5fd90923f7a71c2a90026c333422dc7c
  - AWS config/credentials configuration --> https://gist.github.com/christiangda/17dcaf4591622e3e45ec2b566dd38cc6

Surfing on internet I found:
- https://aws.amazon.com/blogs/developer/assume-aws-iam-roles-with-mfa-using-the-aws-sdk-for-go/
Maybe this is the way to fix it!.

**Comment by rickard-von-essen** [comment]
If you have any further questions about AWS authentication please send a message on the [mailing list](https://groups.google.com/group/packer-tool).

**Comment by christiangda** [comment]
@rickard-von-essen thank you very much!.  I tried it, but I got a a different error and it looks like "profile" and "mfa_code" doesn't work fine together.

> 2018/06/19 15:19:52 ui error: Build 'AMI Windows Builder' errored: UnauthorizedOperation: You are not authorized to perform this operation.
> 	status code: 403, request id: a62768df-92d0-4798-96b5-0b51aadb79c6
> 

I checked my AWS CloudTrail, and the API request are going to my user account (where is my aws_access_key_id) not to the "profile" account.

As you mention, I'll ask about the use of mfa_code in the mailing list to see if someone use it and work assuming roles.

Regards

**Comment by rickard-von-essen** [comment]
Then you probably need to unset `aws_access_key_id`. Check out the docs for the hierarchy of credentials https://www.packer.io/docs/builders/amazon.html#authentication.

MFA and profile works, that's how I use Packer most of the time.

**Comment by christiangda** [comment]
@rickard-von-essen Thanks again, I tried this and it doesn't work either.
I removed
```
    "aws_access_key": "{{env `AWS_ACCESS_KEY`}}",
    "aws_secret_key": "{{env `AWS_SECRET_KEY`}}",
...
    "access_key": "{{user `aws_access_key`}}",
    "secret_key": "{{user `aws_secret_key`}}",
```

and I left:

```
    "aws_profile": "{{env `AWS_PROFILE`}}",
    "aws_mfa_code": "{{env `AWS_MFA_CODE`}}",
...
    "mfa_code": "{{user `aws_mfa_code`}}",
    "profile": "{{ user `aws_profile`}}",
```
and I got the same error described before.

But, I asked in the mailing list group to see if someone use this and work.  Let wait to see.

Thanks!

**Comment by sblask** [comment]
@christiangda Did you ever get this to work? I've got the same error and stumbled upon this issue.

**Comment by rickard-von-essen** [comment]
@sblask Check the mailing list, or ask for help there.
