### ISSUE TITLE
Azure: Image creation fails when running on local machine, connected to VNET via VPN

### ISSUE THREAD

**Issue by panoschatzrp** [hashicorp/packer#6404]
Image is created fine when running from within the same subnet/vnet but not when connecting from a P2S VPN.

Using the following options:
- virtual_network_name
- virtual_network_resource_group_name
- virtual_network_subnet_name
 
Temp Resource Group, VM, NIC, KeyVault are created and winRM connection is successfully established but once the image is ready to be deployed, is gets stuck to the following which keeps running forever:

azure-arm: IMAGE_STATE_COMPLETE
azure-arm: IMAGE_STATE_UNDEPLOYABLE
.
.
azure-arm: IMAGE_STATE_UNDEPLOYABLE

Looks like the sysprep steps are never running. Is there any way to run the script from a local machine that connects to the VNET via a P2S VPN? We'd like to have a customised image before spinning up any VMs in our subscriptions. Deploying using the temp VNET and public IP options is not an option due to security restrictions.

- Packer version: 1.2.3
- Deploying from: Windows 10

**Comment by boumenot** [comment]
This is not an issue with Packer, so I recommend you check with the Packer community.

If sysprep is not completing than most likely it has died.  If you connect to the VM while it is in this state what is sysprep doing? The sysprep logs may be of help too.
