### ISSUE TITLE
Post-processor failed: bad HTTP status: 503

### ISSUE THREAD

**Issue by fujiiface** [hashicorp/packer#6409]
Hi all,

I've got an older vagrant box that I am trying to update and upload via `vagrant-cloud`.  Before the Atlas cloud migration, this worked.  I don't believe I have been able to upload a new box since (although I just recently started trying to do it again).  My packer template works up until the Vagrant cloud upload.  Once my upload starts I get the following messages:

```
==> virtualbox-iso (vagrant-cloud): Uploading box: virtualbox.box
    virtualbox-iso (vagrant-cloud): Depending on your internet connection and the size of the box,
    virtualbox-iso (vagrant-cloud): this may take some time
    virtualbox-iso (vagrant-cloud): Uploading box, attempt 2
    virtualbox-iso (vagrant-cloud): Error uploading box! Will retry in 10 seconds. Status: 503
    virtualbox-iso (vagrant-cloud): Uploading box, attempt 3
    virtualbox-iso (vagrant-cloud): Error uploading box! Will retry in 10 seconds. Status: 503
==> virtualbox-iso (vagrant-cloud): Cleaning up provider
    virtualbox-iso (vagrant-cloud): Deleting provider: virtualbox
Build 'virtualbox-iso' errored: 1 error(s) occurred:

* Post-processor failed: bad HTTP status: 503

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: 1 error(s) occurred:

* Post-processor failed: bad HTTP status: 503

==> Builds finished but no artifacts were created.
```

- Packer version from `packer version`: **1.2.4**
- Host platform: **Windows 10 x64**
- The _simplest example template and scripts_ needed to reproduce the bug.  Include these in your gist https://gist.github.com/fujiiface/072ce44425a8897152d2cf9bf13b308c

**Comment by SwampDragons** [comment]
I reached out to the vagrant team to ask if they had any quick insights for you. The questions they had were:

1. are they properly defining a box_tag value?
2. are they using a valid vagrant cloud token?

Along with the more general comment that there's probably something on your end that needs updating. It's probably worth checking out your tokens etc to make sure that you're using valid items.

**Comment by fujiiface** [comment]
As far as those two values go, I purposely left them out of my gist.

My token value should be good.  I even created a new token in case the one I was using before was expired/wrong.  I'm using `VAGRANT_CLOUD_TOKEN` as a machine variable in Windows.  I even tried hard coding the token in the packer.json file.  As far as my box_tag goes, Packer creates an unreleased box in `vagrant-cloud` with a version in the form of `1.0.{{ .timestamp }}`.

Based on what I have seen, I assume this means the `box_tag` and `access_token` values are being read properly.

**Comment by fujiiface** [comment]
@SwampDragons If I am running the latest packer version, what else would I need to update?

**Comment by fujiiface** [comment]
@SwampDragons I was able to finally get my box to upload.  My previous installation of packer had a bunch of additional .exe files like `packer-post-processor-vagrant-cloud.exe` and `packer-post-processor-vagrant.exe`.  Looking at the running processes showed that I was using these additional .exe instead of packer by itself (the files were from 2015).  I removed all of them except the latest version of `packer.exe` and the upload worked.

**Comment by SwampDragons** [comment]
Oh awesome, I was just about to reach out -- the vagrant team found that your uploads were taking such a long time that it looked like your session was expiring or something; they recommended that if you run into more issues to reach out to support+vagrantcloud@hashicorp.com and they can handle the ticket for you from there.
