### ISSUE TITLE
VMWare Fusion Builder errors on NAT network that doesn't serve DHCP

### ISSUE THREAD

**Issue by brumfb** [hashicorp/packer#6414]
Packer version 1.2.4
Host Platform Darwin
VMWare Fusion 10

If VMWare Fusion Networking is setup to have a NAT network with that does not serve DHCP, VMWare does not create a lease file under `/var/db/vmware/`. This will cause the VMWare Builder to abort the search, skipping any valid nat networks that might have the lease for the guest (see https://github.com/hashicorp/packer/blob/master/builder/vmware/common/driver.go#L359-L362). 

In cases where guests are in NAT networks after this, it the builder will be unable to locate the IP address for the machine. 

Relevant section from PACKER_LOG:

```
2018/06/22 17:41:23 packer: 2018/06/22 17:41:23 Located networkmapper configuration file using Fusion6: /Library/Preferences/VMware Fusion/networking
2018/06/22 17:41:23 packer: 2018/06/22 17:41:23 GuestIP discovered device matching nat: vmnet2
2018/06/22 17:41:23 packer: 2018/06/22 17:41:23 GuestIP discovered device matching nat: vmnet3
2018/06/22 17:41:23 packer: 2018/06/22 17:41:23 GuestIP discovered device matching nat: vmnet8
2018/06/22 17:41:23 packer: 2018/06/22 17:41:23 Lookup up IP information...
2018/06/22 17:41:23 packer: 2018/06/22 17:41:23 GuestAddress found MAC address in VMX: 00:0c:29:41:ea:05
2018/06/22 17:41:23 packer: 2018/06/22 17:41:23 Trying DHCP leases path: /var/db/vmware/vmnet-dhcpd-vmnet2.leases
2018/06/22 17:41:23 packer: 2018/06/22 17:41:23 Trying DHCP leases path: /var/db/vmware/vmnet-dhcpd-vmnet3.leases
2018/06/22 17:41:23 packer: 2018/06/22 17:41:23 IP lookup failed: open /var/db/vmware/vmnet-dhcpd-vmnet3.leases: no such file or directory
2018/06/22 17:41:23 packer: 2018/06/22 17:41:23 [DEBUG] Error getting SSH address: IP lookup failed: open /var/db/vmware/vmnet-dhcpd-vmnet3.leases: no such file or directory
  
```
It finds 3 matching nat devices, but stops on vmnet3 as it is a NAT configured without DHCP.

**Comment by SwampDragons** [comment]
I believe since #6145 was merged, we can fix this.
