### ISSUE TITLE
amazon-ebsvolume: volume ID is not displayed

### ISSUE THREAD

**Issue by kalrish** [hashicorp/packer#6420]
- Packer versions 1.1.0 and 1.2.4
- Linux
- [Logs](https://gist.github.com/kalrish/1b3cf428a7b4650ddf7d785024d687e4)
- [Template](https://github.com/kalrish/aws-vibes/blob/master/ec2/template-ebs-builds.json)

As can be seen, the volume ID is displayed neither by Packer itself nor by the `manifest` post-processor, so the issue might be in the builder.

May be related to #5486.

The strange thing is that this doesn't happen with [this other template](https://github.com/kalrish/aws-vibes/blob/master/ec2/template-ebs-sources.json), whose only differences are:

 -  the EBS volume is quite smaller; and
 -  provisioning takes longer.

**Comment by kalrish** [comment]
It's actually a bug.

**Comment by rickard-von-essen** [comment]
Too quick on the 🔫

**Comment by sylviamoss** [comment]
Hello there! Is this still an issue? 
The template that was failing is no longer available in the link provided and I can't reproduce this locally.

**Comment by kalrish** [comment]
I don't know if this still is an issue. I'll try to recover the template and re-post it.

**Comment by sylviamoss** [comment]
Great. Thank you!

**Comment by uriinf** [comment]
Hello!
There is still issue with packer v1.6.0.
Sequential builds on spot instance don't provide volumes IDs.
Here is template https://github.com/uriinf/packer-amazon-ebsvolume/blob/master/amazon-ebsvolume.json
Two sequential builds have different behavior https://gist.github.com/uriinf/8197161afa0aa511c01a4614127c71dd

**Comment by SwampDragons** [comment]
I've opened https://github.com/hashicorp/packer/pull/9546 to solve this. You can scroll to the store_artifacts check to pull a binary of the patch to test that it works for your system.

**Comment by uriinf** [comment]
> I've opened #9546 to solve this. You can scroll to the store_artifacts check to pull a binary of the patch to test that it works for your system.

Thanks!
I've 3 successful builds with version Packer v1.6.1-dev (948d5d080b5eedcc548cba90b28111956561eee3)

**Comment by SwampDragons** [comment]
Awesome! Thanks for checking that for me!
