### ISSUE TITLE
VMware ISO builder on ESXi host can hang on export if `remote_password` is not set or incorrect

### ISSUE THREAD

**Issue by DanHam** [hashicorp/packer#6425]
Since ovftool only supports password based authentication `remote_password` must be set in the build template. Failing to do so causes the build to hang when the export phase is reached.

#6424 attempts to prevent users encountering this condition by appropriately failing a build template at validation if `remote_password` is not set.

While #6424 can prevent a user encountering a hang, unfortunately a users build will *still* hang if, for example, they have set an incorrect username or password for the ESXi host in their templates.

This wouldn't be too much of an issue if the build **just hung**. Unfortunately, when the build does hang:

* There is no visible sign that it has done so
* In the background ovftool consumes 100% of the CPU while flooding stdout/stderr with zeros. 

When the unsuspecting user types ctrl-c to cancel the build Packer writes all the output that has been building up in the background, and in so doing can possibly overload a terminal or fill a log file with zeros.

I managed to create a 410Mb log file having waited about 30mins for the export to complete. Clearly for automated pipelines, such behaviour may have rather dire consequences e.g. filling a filesystem with a huge log file.

I have managed to discover that ovftool behaves this way when it requires input from the user (e.g. when prompting for a username and password) but is not connected to stdin...

**Comment by arizvisa** [comment]
The fix for this would probably be to attach to `cmd.Stdin` in `builder/vmware/iso/step_export.go` and spin in a goro looking for some text that is asking for input, right?

Is there some specific text that `ovftool` emits when it's waiting for input, so that way we could initiate failure when it's encountered?
