### ISSUE TITLE
`disable_stop_instance` is broken

### ISSUE THREAD

**Issue by SwampDragons** [hashicorp/packer#6426]
At some point when changing the EBS code, we put a waiter outside of the if statement
 where it belonged: https://github.com/hashicorp/packer/blob/master/builder/amazon/common/step_stop_ebs_instance.go#L79-L83

This has basically caused people who have set `disable_stop_instance` to spin until timing out, rather than ending the build appropriately

See https://github.com/hashicorp/packer/issues/6177#issuecomment-400259612 for context.

**Comment by mwhooker** [comment]
good catch. fwiw I think the disable_stop_instance code was added in a way that didn't account for the wait at the end. Maybe the intention of the person who added disable_stop_instance was that packer was supposed to wait until you stopped it manually?

**Comment by SwampDragons** [comment]
>Maybe the intention of the person who added disable_stop_instance was that packer was supposed to wait until you stopped it manually? 

Yeah, looking back at the code and the docs, I think you've nailed it. I think the problem here is a docs issue, where it should be made clear that this tool is intended to allow you to stop the instance via a provisioner -- but still stop the instance as part of the build. We will then wait for the instance to be stopped rather than stopping it ourselves.  Changing to a docs issue.
