### ISSUE TITLE
packer openstack build image

### ISSUE THREAD

**Issue by JamewfefeSzm** [hashicorp/packer#6435]
build image have an error

openstack output will be in this color.

==> openstack: Discovering enabled extensions...
==> openstack: Loading flavor: k1.small
    openstack: Verified flavor. ID: 2
==> openstack: Creating temporary keypair: packer_5b34cb6c-7592-6597-1999-7ddd8b00ce63 ...
==> openstack: Created temporary keypair: packer_5b34cb6c-7592-6597-1999-7ddd8b00ce63
==> openstack: Successfully converted BER encoded SSH key to DER encoding.
==> openstack: Launching server...
    openstack: Server ID: 8b655bbf-2628-4306-8f8f-76e90169002d
==> openstack: Waiting for server to become ready...
==> openstack: Creating floating IP...
    openstack: Pool: ext-net
    openstack: Created floating IP: 10.12.32.231
==> openstack: Associating floating IP with server...
    openstack: IP: 10.12.32.231
    openstack: Added floating IP 10.12.32.231to instance!
==> openstack: Waiting for SSH to become available...
==> openstack: Connected to SSH!
==> openstack: Provisioning with shell script: /tmp/packer-shell240709481
    openstack: Reading package lists... Done
    openstack: Building dependency tree
    openstack: Reading state information... Done
    openstack: wget is already the newest version.
    openstack: 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
    openstack: 2018-06-28 11:50:36 URL:http://10.12.32.12/ [612/612] -> "/home/packages/index.html" [1]
    openstack: /me/: Scheme missing.
    openstack: FINISHED --2018-06-28 11:50:36--
    openstack: Total wall clock time: 0.005s
    openstack: Downloaded: 1 files, 612 in 0s (107 MB/s)
==> openstack: Deleted temporary floating IP 10.12.32.231
==> openstack: Terminating the source server: 8b655bbf-2628-4306-8f8f-76e90169002d ...
==> openstack: Deleting temporary keypair: packer_5b34cb6c-7592-6597-1999-7ddd8b00ce63 ...
Build 'openstack' errored: Script exited with non-zero exit status: 1

**Comment by JamewfefeSzm** [comment]
this is the buildImage's json:
{
    "builders":[
        {
            "type":"openstack",
            "communicator":"ssh",
            "ssh_username":"ubuntu",
            "ssh_timeout":"10m",
            "ssh_pty":true,
            "image_name":"me20180628095247,
            "source_image":"91a8d0b8-3fbe-4863-97d8-90213ad502ba",
            "networks":"bfd92b3c-4fd3-4c75-b506-89f41d69d7c3",
            "flavor":"m1.small",
            "identity_endpoint":"http://10.12.32.1:5000/v3/",
            "floating_ip_pool":"ext-net",
            "username":"test",
            "password":"test",
            "domain_id":"c152f5952b7e4cfc9f6b56a92303dbaf",
            "tenant_id":"42284ea92f964e01b8051821b7e9d8b0"
        }
    ],
    "provisioners":[
        {
            "type":"shell",
            "inline":[
                "sudo apt-get install wget -y",
                "sudo wget -np -nH -c -r -nv -P /home/packages --reject=index.html* http://10.12.32.12 /me/"
            ]
        }
    ]
}

**Comment by rickard-von-essen** [comment]
The build fails since your script fails.

**Comment by rickard-von-essen** [comment]
Please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/
