### ISSUE TITLE
Ansible: Invalid settings supplied for use_tty

### ISSUE THREAD

**Issue by Wenzel** [hashicorp/packer#6438]
- Packer version: `Packer v1.2.4`
- Host platform: `Ubuntu 18.04 LTS`
- [Debug log](https://gist.github.com/Wenzel/a379e0dad3025a5af1b63534bedee674)
- Ansible version: `2.6.0`

Hi !
my working tree is the following:
~~~
$ tree -I venv
.
├── ansible
│   ├── connection_plugins
│   │   ├── packer.py
│   │   └── packer.pyc
│   ├── default.retry
│   └── default.yml
├── answer_files
│   └── 10
│       └── Autounattend.xml
├── packer
├── packer_cache
├── scripts
│   ├── fixnetwork.ps1
│   └── setup_winrm_public.bat
└── windows_10.json
~~~
 
When i run `./packer build windows_10.json`, the provisioning fail with the following error:
~~~
2018/06/29 16:07:37 ui:     qemu: TASK [Gathering Facts] *********************************************************
2018/06/29 16:07:37 ui:     qemu: task path: /home/tarrma/tmp/bug_packer/ansible/default.yml:2
    qemu: task path: /home/tarrma/tmp/bug_packer/ansible/default.yml:2
    qemu: <127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: tarrma
2018/06/29 16:07:37 ui:     qemu: <127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: tarrma
    qemu: fatal: [default]: FAILED! => {
2018/06/29 16:07:37 ui:     qemu: fatal: [default]: FAILED! => {
    qemu:     "msg": "Invalid settings supplied for use_tty: 'connection'"
2018/06/29 16:07:37 ui:     qemu:     "msg": "Invalid settings supplied for use_tty: 'connection'"
2018/06/29 16:07:37 ui:     qemu: }
qemu: }
~~~

Windows template to reproduce the build ([Gist](https://gist.github.com/Wenzel/5becb4b03a3dfb015ab08627810d8afe))

-> Could it be that ansible is using SSH instead of winrm to connect and is confused by the connection 
plugin ?

I hope this helps !

Thanks.

**Comment by Wenzel** [comment]
I created this repository to help the you reproduce the bug:
https://github.com/Wenzel/bug_packer_ansible

**Comment by Wenzel** [comment]
The solution has been given to me by @adarobin .
From Ansible 2.4.x and above, you need to add a `DOCUMENTATION` string to the connection plugin.
[Gist](https://gist.github.com/adarobin/2f02b8b993936233e15d76f6cddb9e00)

We should update the documentation of the Ansible provisioner:
https://github.com/hashicorp/packer/pull/6454

@SwampDragons  I confirm that the build works with Ansible `2.6.0` now.
Feel free to close this issue once the documentation will have been updated !

Thanks.

**Comment by SwampDragons** [comment]
Awesome, thanks for the update! I'll review that docs change ASAP.
