### ISSUE TITLE
[BUG]Packer is not able to run powershell script with cygwin

### ISSUE THREAD

**Issue by robinku07** [hashicorp/packer#6441]
Describe the problem and include the following information:

- Packer version from `1.2.3 and 1.2.4`. Its working fine on 1.1.0

- Host platform (Running Packer from windows 10 to Create Windows 2016 AMIs
 on AWS)
  
Error Output:-
amazon-ebs: C:\Cygwin64\home\ec2-user>powershell -File C:\ProgramData\Amazon\EC2-Windows\Launch\Scripts\InitializeInstance.ps1 -Schedule
    amazon-ebs: Join-Path : Cannot bind argument to parameter 'Path' because it is null.
    amazon-ebs: At C:\ProgramData\Amazon\EC2-Windows\Launch\Scripts\InitializeInstance.ps1:55 char:71
    amazon-ebs: + ... tion Constant -Scope Local -Value (Join-Path $env:ProgramData -ChildP ...
    amazon-ebs: +                                                  ~~~~~~~~~~~~~~~~
    amazon-ebs:     + CategoryInfo          : InvalidData: (:) [Join-Path], ParameterBindingValidationException
    amazon-ebs:     + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.JoinPathCom
    amazon-ebs:    mand
    amazon-ebs:
    amazon-ebs: Join-Path : Cannot bind argument to parameter 'Path' because it is null.
    amazon-ebs: At C:\ProgramData\Amazon\EC2-Windows\Launch\Scripts\InitializeInstance.ps1:56 char:73
    amazon-ebs: + ... ath -Option Constant -Scope Local -Value (Join-Path $rootPath -ChildP ...
    amazon-ebs: +                                                         ~~~~~~~~~
    amazon-ebs:     + CategoryInfo          : InvalidData: (:) [Join-Path], ParameterBindingValidationException
    amazon-ebs:     + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.JoinPathCom
    amazon-ebs:    mand
    amazon-ebs:
    amazon-ebs: Import-Module : Cannot bind argument to parameter 'Name' because it is null.
    amazon-ebs: At C:\ProgramData\Amazon\EC2-Windows\Launch\Scripts\InitializeInstance.ps1:62 char:15
    amazon-ebs: + Import-Module $modulePath
    amazon-ebs: +               ~~~~~~~~~~~
    amazon-ebs:     + CategoryInfo          : InvalidData: (:) [Import-Module], ParameterBindingValidationException
    amazon-ebs:     + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.ImportModul
    amazon-ebs:    eCommand
    amazon-ebs:
    amazon-ebs: Initialize-Log : The term 'Initialize-Log' is not recognized as the name of a cmdlet, function, script file, or
    amazon-ebs: operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
    amazon-ebs: again.
    amazon-ebs: At C:\ProgramData\Amazon\EC2-Windows\Launch\Scripts\InitializeInstance.ps1:65 char:1
    amazon-ebs: + Initialize-Log -Filename "Ec2Launch.log" -AllowLogToConsole
    amazon-ebs: + ~~~~~~~~~~~~~~
    amazon-ebs:     + CategoryInfo          : ObjectNotFound: (Initialize-Log:String) [], CommandNotFoundException
    amazon-ebs:     + FullyQualifiedErrorId : CommandNotFoundException
    amazon-ebs:
    amazon-ebs: Register-ScriptScheduler : The term 'Register-ScriptScheduler' is not recognized as the name of a cmdlet, function,
    amazon-ebs: script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is
    amazon-ebs: correct and try again.
    amazon-ebs: At C:\ProgramData\Amazon\EC2-Windows\Launch\Scripts\InitializeInstance.ps1:70 char:5
    amazon-ebs: +     Register-ScriptScheduler -ScriptPath $scriptPath -ScheduleName $s ...
    amazon-ebs: +     ~~~~~~~~~~~~~~~~~~~~~~~~
    amazon-ebs:     + CategoryInfo          : ObjectNotFound: (Register-ScriptScheduler:String) [], CommandNotFoundException
    amazon-ebs:     + FullyQualifiedErrorId : CommandNotFoundException
    amazon-ebs:
    amazon-ebs: Write-Log : The term 'Write-Log' is not recognized as the name of a cmdlet, function, script file, or operable
    amazon-ebs: program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
    amazon-ebs: At C:\ProgramData\Amazon\EC2-Windows\Launch\Scripts\InitializeInstance.ps1:74 char:5
    amazon-ebs: +     Write-Log "Instance initialization is scheduled successfully"
    amazon-ebs: +     ~~~~~~~~~
    amazon-ebs:     + CategoryInfo          : ObjectNotFound: (Write-Log:String) [], CommandNotFoundException
    amazon-ebs:     + FullyQualifiedErrorId : CommandNotFoundException
    amazon-ebs:
    amazon-ebs: Complete-Log : The term 'Complete-Log' is not recognized as the name of a cmdlet, function, script file, or operable
    amazon-ebs: program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
    amazon-ebs: At C:\ProgramData\Amazon\EC2-Windows\Launch\Scripts\InitializeInstance.ps1:75 char:5
    amazon-ebs: +     Complete-Log
    amazon-ebs: +     ~~~~~~~~~~~~
    amazon-ebs:     + CategoryInfo          : ObjectNotFound: (Complete-Log:String) [], CommandNotFoundException
    amazon-ebs:     + FullyQualifiedErrorId : CommandNotFoundException
    amazon-ebs:

**Comment by SwampDragons** [comment]
Thanks for opening an issue -- in order to work on it, I'm going to need a simple template and sample script so that I can reproduce.

**Comment by robinku07** [comment]
Hi Marsh,

You can just try to run the powershell cloudinit schedule script in windows
2016.

Rovindra Kumar

**Comment by SwampDragons** [comment]
I understand that this feels simple to you, but I'm not an expert at provisioning windows instances in aws. That is why we ask for a simple reproducing script in the issue template--It requires an enormous amount of energy to guess exactly how you're using the tool so that I can reproduce.  I don't know what version of windows you're launching because you haven't provided the source ami. I don't know the nuance of how you're calling the cloudinit script. I don't know what configuration you've already done. 

To refresh you on what we ask for in the issue template: 

- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a gist https://gist.github.com
- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your gist https://gist.github.com

I'll gladly reopen this ticket if you provide the above information.
