### ISSUE TITLE
416 Requested Range Not Satifiable

### ISSUE THREAD

**Issue by Wenzel** [hashicorp/packer#6443]
- Packer version `Packer v1.2.4`
- Host platform: `Ubuntu 18.04`
- Debug log: [Gist](https://gist.github.com/Wenzel/35b9ef7da8a5bd05020e4b0c7f547d69)

Under specific conditions, Packer raises this download error, even though my network connection is perfectly fine.
![screenshot from 2018-07-02 13-10-09](https://user-images.githubusercontent.com/964610/42158525-57dc7c84-7df9-11e8-8e6f-5950af4343e6.png)

It's always reproducible, and happens when i suspend my laptop and resume it, and change the network connection being used (Wifi vs ethernard card)

What's even more surprising is that **i already have the image** in my `packer_cache`, but Packer keeps trying to download it, and fails.

I hope you can help me with this.

**Comment by Wenzel** [comment]
@SwampDragons hi and thanks for your reply.
> was the image in your packer_cache named by Packer or did you place it there manually?

i created a symlink to another project's `packer_cache` directory, and it worked well until I had this message this morning.

Now, the funny thing is that i had the same issue (*416 Requested Range Not Satifiable*) in the other project (without the symlink), so i don't think the symlink has anything to do with this.

**Comment by Wenzel** [comment]
From the Gist we can see that Packer attempts to verify the checksum of the ISO:
~~~
2018/07/02 13:05:31 packer: 2018/07/02 13:05:31 Verifying checksum of /home/tarrma/tmp/bug_ansible_win_reboot/packer_cache/51f18c73ca51f34d7ebb13dca3870c2fe8f8c2115414c0c854cadc3c1bbdfdd3.iso
~~~

But why the checksum is not valid in the first place ? Any way to get more information about this ?

**Comment by SwampDragons** [comment]
My gut instinct is that there's something off with your packer config, but I'd need to see it to help debug it.

**Comment by Wenzel** [comment]
@SwampDragons by packer config you mean the template i'm using ?
~~~JSON
{
    "builders": [
        {
            "vm_name": "windows10.qcow2",
            "type": "qemu",
            "accelerator":  "kvm",
            "iso_url": "{{user `iso_url`}}",
            "iso_checksum": "{{user `iso_checksum`}}",
            "iso_checksum_type": "{{user `iso_checksum_type`}}",
            "disk_size": 50000,
            "disk_interface": "ide",
            "net_device": "e1000",
            "format": "qcow2",
            "headless": true,
            "qemuargs": [
                ["-smp", "2"],
                ["-m", "4096M"]
            ],
            "communicator": "winrm",
            "winrm_username": "{{user `username`}}",
            "winrm_password": "{{user `password`}}",
            "winrm_port": 5985,
            "winrm_timeout": "4h",
            "ssh_host_port_min": "{{user `communicator_port`}}",
            "ssh_host_port_max": "{{user `communicator_port`}}",
            "disk_compression": false,
            "skip_compaction": true,
            "shutdown_command": "shutdown /s /t 10 /f /d p:4:1 /c \"Packer Shutdown\"",
            "shutdown_timeout" : "1h",
            "floppy_files": [
                "{{user `autounattend`}}",
                "scripts/fixnetwork.ps1",
                "scripts/setup_winrm_public.bat"
            ]
        }
    ],
    "provisioners": [
        {
            "type": "shell-local",
            "command": "ansible-playbook {{ user `ansible_debug` }}  -i '127.0.0.1,' -c winrm -e \"ansible_user={{ user `username` }} ansible_password={{ user `password` }} ansible_port={{ user `communicator_port` }} ansible_winrm_scheme=http\" ansible/site.yml"
        }
    ],
    "variables": {
        "iso_url": "http://care.dlservice.microsoft.com/dl/download/C/3/9/C399EEA8-135D-4207-92C9-6AAB3259F6EF/10240.16384.150709-1700.TH1_CLIENTENTERPRISEEVAL_OEMRET_X64FRE_EN-US.ISO",
        "iso_checksum_type": "sha1",
        "iso_checksum": "56ab095075be28a90bc0b510835280975c6bb2ce",
        "autounattend": "./answer_files/10/Autounattend.xml",
        "username": "vagrant",
        "password": "vagrant",
        "communicator_port": "3000",
        "ansible_debug": "-vvvvv"
    }
}
~~~

**Comment by Wenzel** [comment]
`56ab095075be28a90bc0b510835280975c6bb2ce  51f18c73ca51f34d7ebb13dca3870c2fe8f8c2115414c0c854cadc3c1bbdfdd3.iso`

The same `SHA1` as specified in the template.

**Comment by SwampDragons** [comment]
Can you re-run this build with the env var `PACKER_DEBUG=1` and give me the output?

**Comment by martinanderssondotcom** [comment]
I got the same error message on a Windows 10 machine. The cached ISO file was outdated, and since I knew that Packer should start a new download, I manually deleted the old cached ISO file and ran my build command again. This time the download started.

**Comment by sprat** [comment]
I encountered the exact same problem with this Ubuntu CD ISO base url : http://cdimage.ubuntu.com/ubuntu-server/bionic/daily/current/

In fact, at this URL, the ISO file and ISO checksum file change every day, but the URL hash computed by packer is still the same. So I guess packer is trying to "resume" the download by sending a "Range" header (and this fails) whereas it should start from scratch with a fresh download. I think packer should check "ETag" or "LastModifiedDate" headers before trying to "resume" a download.

I think this also explains the following issue: https://github.com/hashicorp/packer/issues/5198

**Comment by azr** [comment]
In #6999 files will get stored under `hash(file_url + file_checksum).ext` whereas now it is `hash(file_url).ext`. This should prevent this filename collision issue.

**Comment by sprat** [comment]
That's great! I've seen that it's scheduled for 1.3.5 so we'll have to wait a little bit but in the end, it will solve our problem I guess.
