### ISSUE TITLE
Packer with Azure > Stale token

### ISSUE THREAD

**Issue by rohrerb** [hashicorp/packer#6444]
Running the latest version of packer...

FWIW - I hadn't ran packer in a while and (i believe) my password did change.

**Attempted to run Packer and received the below error:**

> ==> azure-arm: Running builder ...
> ==> azure-arm: Getting auth token for Service management endpoint
> ==> azure-arm: Loading auth token from file: /Users/brohrer/.azure/packer/oauth-52cdadcd-5b5b-4f59-b3a3-b0ef07e67193mgmt.json
> ==> azure-arm: Auth token found in file: /Users/brohrer/.azure/packer/oauth-52cdadcd-5b5b-4f59-b3a3-b0ef07e67193mgmt.json
> ==> azure-arm: Getting token for Vault resource
> ==> azure-arm: Loading auth token from file: /Users/brohrer/.azure/packer/oauth-52cdadcd-5b5b-4f59-b3a3-b0ef07e67193vault.json
> ==> azure-arm: Auth token found in file: /Users/brohrer/.azure/packer/oauth-52cdadcd-5b5b-4f59-b3a3-b0ef07e67193vault.json
> Build 'azure-arm' errored: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_grant","error_description":"AADSTS50173: The provided grant has expired due to it being revoked. The user might have changed or reset their password. The grant was issued on '2018-05-14T10:04:47.7911088Z' and the TokensValidFrom date for this user is '2018-06-07T14:33:12.0000000Z'\r\nTrace ID: 98f26187-0ed0-4a60-be90-822c76af1a00\r\nCorrelation ID: f2b57b68-1cf6-4440-b4b2-ace2776fd0a5\r\nTimestamp: 2018-06-29 13:37:54Z","error_codes":[50173],"timestamp":"2018-06-29 13:37:54Z","trace_id":"98f26187-0ed0-4a60-be90-822c76af1a00","correlation_id":"f2b57b68-1cf6-4440-b4b2-ace2776fd0a5"}
> 
> ==> Some builds didn't complete successfully and had errors:
> --> azure-arm: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_grant","error_description":"AADSTS50173: **The provided grant has expired due to it being revoked. The user might have changed or reset their password. The grant was issued on '2018-05-14T10:04:47.7911088Z' and the TokensValidFrom date for this user is '2018-06-07T14:33:12.0000000Z'\r\nTrace ID: 98f26187-0ed0-4a60-be90-822c76af1a00\r\nCorrelation ID: f2b57b68-1cf6-4440-b4b2-ace2776fd0a5\r\nTimestamp: 2018-06-29 13:37:54Z","error_codes":[50173],"timestamp":"2018-06-29 13:37:54Z","trace_id":"98f26187-0ed0-4a60-be90-822c76af1a00","correlation_id":"f2b57b68-1cf6-4440-b4b2-ace2776fd0a5"**}

After several failed attempts i had to manually remove the following files before Packer would prompt for login.   Maybe Packer could recover more gracefully from stale or password change?

**Files i had to remove:**
```
brohrer$ rm /Users/brohrer/.azure/packer/oauth-52cdadcd-5b5b-4f59-b3a3-b0ef07e67193mgmt.json
brohrer$ rm /Users/brohrer/.azure/packer/oauth-52cdadcd-5b5b-4f59-b3a3-b0ef07e67193vault.json
```

**Comment by ernstae** [comment]
FWIW, just experienced this today with packer 1.4.3

**Comment by eltimmo** [comment]
Hi, also with v1.6.5
