### ISSUE TITLE
Expose PACKER_HTTP_ADDR for shell-local provisioner

### ISSUE THREAD

**Issue by Wenzel** [hashicorp/packer#6452]
# Feature Request

Like it has already been done for the `Shell` and `Powershell` #4409 provisioner, would it be possible to expose the HTTP directory server address (`PACKER_HTTP_ADDR`) as an environment variable in the `shell-local` as well ?

The reason I'm asking is that i'm provsioning my Windows VM using Ansible.
But the native WinRM communicator `connection_plugin` is **broken**: https://github.com/hashicorp/packer/issues/6438

So I have to use this trick to execute Ansible as a `shell-local` provisioner and get the address of Packer's webserver in the playbook:

**template**
~~~JSON
    "provisioners": [
        {
          "type": "powershell",
          "inline": ["$env:PACKER_HTTP_ADDR | Out-File -FilePath C:\\webserver.txt -NoNewline -Encoding ASCII"]
        },
        {
            "type": "shell-local",
            "command": "ansible-playbook {{ user `ansible_debug` }}  -i '127.0.0.1,' -c winrm -e \"ansible_user={{ user `username` }} ansible_password={{ user `password` }} ansible_port={{ user `communicator_port` }} ansible_winrm_scheme=http\" ansible/site.yml"
        }
    ],
~~~

**playbook**
~~~YAML
- hosts: all
  pre_tasks:
    - name: retrieve Packer HTTP server address
      slurp:
        src: 'C:\webserver.txt'
      register: slurp_webserver
    - name: set variable to HTTP server address
      set_fact:
        webserver: "http://{{ slurp_webserver.content | b64decode | trim }}"
~~~

Thanks !

**Comment by SwampDragons** [comment]
This seems doable.

**Comment by Wenzel** [comment]
The PR has been merged, closing this issue.
Thanks !
