### ISSUE TITLE
Error: cURL error: SSL connect error - builder:vmware-iso, post-processor:vsphere

### ISSUE THREAD

**Issue by zetneteork** [hashicorp/packer#6455]
Packer fails on step during exporting build image into new VM on ESXi.
In template there is as option **`"insecure": true`** used
Also ovftool have parameters **`--noSSLVerify --noSSLVerify=true`**

```
==> vmware-iso: Compacting all attached virtual disks...
    vmware-iso: Compacting virtual disk 1
==> vmware-iso: Cleaning VMX prior to finishing up...
    vmware-iso: Unmounting floppy from VMX...
    vmware-iso: Detaching ISO from CD-ROM device...
    vmware-iso: Disabling VNC server...
==> vmware-iso: Exporting virtual machine...
    vmware-iso: Executing: ovftool.exe --noSSLVerify --noSSLVerify=true --skipManifestCheck -tt=vmx vi://root:****@10.29.99.81/win-2016-datacenter-test-001 output-vmware-iso
==> vmware-iso: Error exporting virtual machine: exit status 1
==> vmware-iso: Error: cURL error: SSL connect error
==> vmware-iso: Completed with errors
==> vmware-iso:
==> vmware-iso:
==> vmware-iso: Destroying virtual machine...
Build 'vmware-iso' errored: Error exporting virtual machine: exit status 1
Error: cURL error: SSL connect error
Completed with errors
```

- Packer v1.2.4
- VMware OVF Tool 4.0.0
- Windows 10, build on ESXi 6.5
- Template: https://gist.github.com/zetneteork/67627ef60177b98ab669c6acf050dd4f
- Log-output: https://gist.github.com/zetneteork/84946e30bf1210b2050b3578eecfcc92

**Comment by DanHam** [comment]
@zetneteork It looks to me as though you have the [packer-community/packer-windows-plugins](https://github.com/packer-community/packer-windows-plugins) installed:

```
2018/07/03 15:24:21 [INFO] Packer version: 1.2.4
2018/07/03 15:24:21 Packer Target OS/Arch: windows amd64
2018/07/03 15:24:21 Built with Go Version: go1.10.1
2018/07/03 15:24:21 [DEBUG] Discovered plugin: amazon-windows-ebs = C:\Users\i314866\AppData\Roaming\packer.d\plugins\packer-builder-amazon-windows-ebs.exe
2018/07/03 15:24:21 [DEBUG] Discovered plugin: parallels-windows-iso = C:\Users\i314866\AppData\Roaming\packer.d\plugins\packer-builder-parallels-windows-iso.exe
2018/07/03 15:24:21 [DEBUG] Discovered plugin: parallels-windows-pvm = C:\Users\i314866\AppData\Roaming\packer.d\plugins\packer-builder-parallels-windows-pvm.exe
...
```

These plugins were actually integrated into Packer way back in version 0.8.0. Since then they have gone through a large number of changes. It's highly likely using the old plugins is causing issues.

Try uninstalling the plugins and trying the build again.

**Comment by shyam2j** [comment]
Facing the same issue in Linux VM from where packer is run to create RHEL. Any help will be appreciated.

**Comment by shyam2j** [comment]
No plugins are used

**Comment by xpirad** [comment]
man, i have the exact same issue as you

**Comment by arizvisa** [comment]
Try upgrading ovftool?

The exact command that ovftool is running is listed in that log file:
`ovftool.exe --noSSLVerify --noSSLVerify=true --skipManifestCheck -tt=vmx vi://root:****@10.29.99.81/win-2016-datacenter-test-001 output-vmware-iso`

packer is simply running that command, so troubleshooting this should take you there. maybe `ovftool --help` will mention if there's a different commandline option or something to get ovf to ignore certificate chain validation errors.

if there is a different commandline option, would be good to know.

**Comment by tobygale** [comment]
Upgrading to ovftool version 4.3.0 fixed this exact issue for me today.

**Comment by SwampDragons** [comment]
Since upgrading ovftool solves this, I'm going to close.  Thanks, all. :)
