### ISSUE TITLE
Azure password complexity not always met by generated password

### ISSUE THREAD

**Issue by jabbera** [hashicorp/packer#6460]
Packer Version: 1.2.4
Host platform: linux in docker

I'm hoping you don't actually need any of the diagnostics you are asking for. I generate 25 images/day (don't ask me why). The automated process fails intermittently with the below error

The supplied password must be between 8-123 characters long and must satisfy at least 3 of password complexity requirements from the following: 
Contains an uppercase character
Contains a lowercase character
Contains a numeric digit
Contains a special character
Control characters are not allowed

**Comment by boumenot** [comment]
I think Azure changed their password complexity requirements, or the system we have been using for more than year has only now just broken for you. ☹️ 

The builder creates a 32 character password from the alphabet below, but it does not ensure there is at least 3 of the 4 criteria satisified.  The builder will need to be updated to deal with this new requirement.

```text
0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
```
