### ISSUE TITLE
User variables specified with -var doesn't have to be declared in the variables block

### ISSUE THREAD

**Issue by rickard-von-essen** [hashicorp/packer#6473]
Example template:

https://github.com/awslabs/amazon-eks-ami/blob/master/eks-worker-al2.json

```shell
$ packer validate eks-worker-al2.json
Template validation failed. Errors are shown below.

Errors validating build 'amazon-ebs'. 1 error(s) occurred:

* A source_ami or source_ami_filter must be specified
$ packer validate -var source_ami_id=ssss eks-worker-al2.json
Template validated successfully.
```

This contradicts what the documentation says:

> User variables must first be defined in a variables section within your template. Even if you want a user variable to default to an empty string, it must be defined. This explicitness helps reduce the time it takes for newcomers to understand what can be modified using variables in your template.

See [User Variables - Usage](https://www.packer.io/docs/templates/user-variables.html#usage)

**Comment by SwampDragons** [comment]
Scratch that -- introduced in 0.12.1

**Comment by SwampDragons** [comment]
Actually, I was misreading output; this has been broken since at least 0.12, but probably before. I'm not going to search further back for where this was introduced, if it ever worked.

**Comment by SwampDragons** [comment]
I ended up going back a bit further; this has never worked as you're interpreting as far as I can tell.

We can either change the code or change the docs.  To be honest I'm leaning towards changing the docs, since I'm worried changing this to match the documentation will break a _lot_ of templates.

**Comment by rickard-von-essen** [comment]
I agree, if this have been working like this since the dark ages let's keep it as it is and correct the docs. 

If it's easy to add i think it would be great if we logged a warning/info when a undeclared variable is passed. This gives us a better position if we want to change this in the future and helps troubleshooting misspellings etc.
