### ISSUE TITLE
Feature Request: Temporary names for unencrypted AMIs when using encrypt_boot: true

### ISSUE THREAD

**Issue by yruss972** [hashicorp/packer#6483]
Packer's amazon-ebs builder, when using encrypt_boot: true, currently uses the same name for the temporary unencrypted AMIs as it does for the resulting encrypted AMIs.

This results in a race condition where the unencrypted AMIs may be returned when searching for the "latest" AMI matching a naming convention.

Since there is clearly no intention to use the unencrypted AMIs and they are deregistered/deleted once the packer process finishes, it would seem better to create the unencrypted AMIs as temporary resources using a temporary naming scheme.

Alternatively, the simplest solution to prevent this type of race condition would be greatly appreciated

**Comment by SwampDragons** [comment]
Thanks for opening this issue!

**Comment by drora** [comment]
So true, and now with GDPR - even more important..

**Comment by sharmaansh** [comment]
I can work on this, would be good for me to understand packer in more details. If no one is working on it.

**Comment by azr** [comment]
Hey there, I'll probably give a shot at this PR Monday; if that's okay.

**Comment by azr** [comment]
It's in master, so for the next release. Master is very soon going to be tested for a release.
