### ISSUE TITLE
Feature Request: alicloud builder can use private ip address for provisioning

### ISSUE THREAD

**Issue by rifki192** [hashicorp/packer#6484]
Packer with alibabacloud builder has a very nice feature, but when I use it, it always use EIP or PublicIpAddress to provision the instance, but I think it will be better if we can use private ip address too for ssh or provision our instance.

nb: actually, I'm already tried to add new step for that private_ip_addres, will create my PR and reference to this issue soon

**Comment by chhaj5236** [comment]
@rifki192 This feature has been satisfied in https://github.com/hashicorp/packer/pull/6688
