### ISSUE TITLE
vmware-iso: ESXi - ssh times out

### ISSUE THREAD

**Issue by harshchauhan1988** [hashicorp/packer#6485]
Hi Team,

While using the packer to convert OVA to AMI it stuck always at below "opening new ssh session"(this is happening on the latest version of packer).  The same script used to work for a long time and started failing suddenly on a few occurrences(When running the old packer version).

debug level logs:
https://gist.github.com/harshchauhan1988/c1ba804aef94874f8af2654b58818907

Script used:
https://gist.github.com/harshchauhan1988/2e53a62ad741290bed640cd21976ff0b

Can you please take a look by simulating this issue? This is hampering build automation for a long time.

**Comment by harshchauhan1988** [comment]
[xxx@xxx-kvm1: ~]# packer version
Packer v1.2.4

[xxx@xxx-kvm1: ~]# uname -a
Linux xxx-kvm1 3.13.0-73-generic #116-Ubuntu SMP Fri Dec 4 15:31:30 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by rickard-von-essen** [comment]
Could you provide the actual template and scriptd used for a build.

Also describe why you think this is a bug and what steps you did to troubleshoot the issue. These tend not to be bugs but usage errors or problems with the setup.

**Comment by harshchauhan1988** [comment]
I have attached script at below location: "https://gist.github.com/harshchauhan1988/2e53a62ad741290bed640cd21976ff0b" 

and packer logs at :

https://gist.github.com/harshchauhan1988/c1ba804aef94874f8af2654b58818907
This script was working all the while and suddenly stopped working. for sure this could not be a usage error. if you try to replicate that will be a great help.

before the upgrade to the latest I tried to follow the comments given in below link and found my script is in healthy condition as per the discussion:

https://github.com/hashicorp/packer/issues/4832

There is not much information in packer log to debug more. Thanks

**Comment by rickard-von-essen** [comment]
Which guest os are you trying to build, url and checksum. What do the console for the VM look like?

**Comment by harshchauhan1988** [comment]
@rickard-von-essen  Basically the flow looks like this:

First, it will import OVA from ISO image(for which user passes build URL and Checksum), once OVA preparation is done which upload this to AWS S3 as an import operation. Now the strange part of this when I launch an independent job for OVA preparation, that's get succeeded. But when i launch cascaded script for AMI generation it stuck and OVA import never completes.

Guest OS is Ubuntu 64 bit.

**Comment by rickard-von-essen** [comment]
Which ubuntu is do you use, what's the exact version and checksum?

**Comment by rickard-von-essen** [comment]
This fails because packer don't get an IP for it to connect with ssh on.

```
Error getting SSH address: No interface on the VM has an IP address ready 
SSH wait cancelled.
```

You can ignore the Amazon Import part.

**Comment by rickard-von-essen** [comment]
If you open up VM console and chech the state of the VM when packer is trying to access it via ssh. Log in and do normal network troubleshooting, can you reach the host, is sshd up, check logs, etc.

Provide what you found here.

**Comment by harshchauhan1988** [comment]
This not the case. When failure happens, I had verified ESX VM has IP
ready. Not sure what exactly wrong here. It has to be debugged.

**Comment by harshchauhan1988** [comment]
Hi Team,

You can close this case. Actually, there was some goof-up happening as we were doing some kernel level update/change in in-line provisioner. We were able to identify this. Thanks a lot for the support.
