### ISSUE TITLE
Feature: provide Libvirt domain XML to QEMU builder to match specific hardware configuration

### ISSUE THREAD

**Issue by Wenzel** [hashicorp/packer#6500]
# Feature Request

## Problem

If a Windows image is built with Packer `QEMU` builder and later on imported in Libvirt, the hardware configuration has changed, and **Windows spend some time installing the new drivers**.

Furthermore, you might want to match your future VM hardware configuration while provisioning, as certain registry keys will not be present until the right hardware is attached.

The `Packer` `QEMU` builder allows to customize the commandline with `qemuargs`, however this is extremely tedious to look at the Libvirt  `QEMU` command line, and try to adjust the `qemuargs` to match the same hardware.

## Feature

Allow the `QEMU` builder to specify a Libvirt domain XML, and use this as a hardware configuration to build and provision the image.

-> Should we add a `domain_xml` field into `QEMU` builder ?
-> Should we create a totally new `Libvirt` builder, since we will call the Libvirt API to import, start and stop the VM, since Libvirt invokes `QEMU` by itself ?

Waiting for you feedback on the feasibility of this feature !

Thanks.

**Comment by SwampDragons** [comment]
My first gut instinct is that I'd prefer a libvirt builder over having a feature in the QEMU builder that requires libvirt, because it might mask the fact that libvirt is required. That said, we have past cases where we've added features that require command line tools, so perhaps it's okay. I'm gonna think about it for a while.

**Comment by noxdafox** [comment]
FYI: you can use libvirt command [`virsh domxml-to-native`](https://libvirt.org/drvqemu.html#xmlexport) to convert a libvirt XML into the related QEMU argument list.

**Comment by Wenzel** [comment]
@noxdafox, yeah i know this trick from virsh.
The issue here is Packer having hardcoded hardware configuration fir the QEMU builder.

**Comment by SwampDragons** [comment]
If someone wants to contribute a qemu-libvirt builder, I think that'd be the best way to do this. Ideally, there'd be some ability to reuse code rather than copy/pasting large portions of the qemu builder.
