### ISSUE TITLE
what are does those template variables refer to?

### ISSUE THREAD

**Issue by liamz39** [hashicorp/packer#6507]
I read through bento (https://github.com/chef/bento) to study how to write packer template files, I see several template variables, which starts with a `.`, like `.Version .HTTPIP .VARS` etc. what do these variables refer to, I found no docs for them.

**Comment by mwhooker** [comment]
Here are our docs on how templates work https://www.packer.io/docs/templates/engine.html

for specific variables you might have luck googling with `site:packer.io/docs` as a term, such as https://www.google.com/search?q=site%3Apacker.io%2Fdocs+%22.vars%22&rlz=1C5CHFA_enUS710US710&oq=site%3Apacker.io%2Fdocs+%22.vars%22&aqs=chrome..69i57j69i58.3166j0j8&sourceid=chrome&ie=UTF-8

but they usually have something to do with the provisioner they appear in. Hope this helps! If not you can try sending an email to the [mailing list](https://groups.google.com/forum/#!forum/packer-tool)

**Comment by rickard-von-essen** [comment]
https://www.packer.io/docs/builders/virtualbox-iso.html#templates-inside-boot-command

**Comment by rickard-von-essen** [comment]
https://www.packer.io/docs/builders/virtualbox-iso.html#guest_additions_path

**Comment by SwampDragons** [comment]
Reopened because I think we could stand to add clearer docs for these two variables.

**Comment by SwampDragons** [comment]
I think this is going to have to be an option-specific update, and that's already covered by #5382
