### ISSUE TITLE
Increase the disk size used during a Packer builder for Oracle Compute (Classic)

### ISSUE THREAD

**Issue by scross01** [hashicorp/packer#6509]
Opening issue on behalf of a customer:

> We are using Packer to build an Oracle Compute Machine Image but one of the provisioners fails due to hitting out-of-disk. For most other builders it is very easy to increase disk but for oracle-classic builder, i can't see any such option.

**Comment by scross01** [comment]
### Guidance help address this enhancement

The current implementation of the oracle-classic builder uses local storage boot volume and instance snapshotting.   In order to support setting a the target disk size the builder will need to an option to create the builder instance using a persistent block storage boot volume, for which the size can be set.  Instance snapshotting cannot be used for creating the final image from a block storage volume, so a different approach is required to mount the storage volume to another temp instance and perform a disk copy and compress the image. 

Full details of the steps for creating machine images from a block volume are covered in this blog article https://blogs.oracle.com/cloudmarketplace/creating-an-oracle-compute-machine-image-from-an-instance-with-persistent-boot-storage

**Comment by craigbarrau** [comment]
Thanks @scross01 for doing this. I am actually the said "customer" or at least that sounds like my words :)

@mwhooker, I did a small enhancement for packer some releases back which got accepted into a release. Again, I'd like to offer my assistance if it will be helpful in any way.

**Comment by SwampDragons** [comment]
Thanks, @scross01.  @craigbarrau if you wanted to take a stab at this, I could give you some starting points. Otherwise I can try to get to it before the next release.

**Comment by craigbarrau** [comment]
Thanks @SwampDragons. I certainly don't want to get in the way but if it helps I've got 1-2 days capacity from tomorrow. I'd probably say I'm an intermediate go programmer so if it is a particularly complex one, I'm also equally as happy to leave it to the experts :)

**Comment by craigbarrau** [comment]
Sounds like it's planned for late August release.
Do you need anything else from me before I fade away and wait patiently in the distance? :)

**Comment by SwampDragons** [comment]
No, but thanks! We talked about this internally and @mwhooker said he was going to take it on. He may have questions for you.
