### ISSUE TITLE
Unable attach additional EBS volume to my AMI 

### ISSUE THREAD

**Issue by cezanedeepak** [hashicorp/packer#6511]
I have written a correct json file , still no volume is getting attached when I am launching an instance using the created AMI through the json file. 

All I want to do is to attach a 10gb additional ebs to my ami.
Below is my Builder section

```json
"launch_block_device_mappings": [
    {
      "device_name": "/dev/sda1",
      "volume_size": 8,
      "volume_type": "gp2",
      "delete_on_termination": true
    },
	{
      "device_name": "/dev/sdb",
      "volume_size": 10,
      "volume_type": "gp2",
      "delete_on_termination": true
    }
  ],
  "ami_block_device_mappings": [
   
	 {
      "device_name": "/dev/sdb",
      "virtual_name": "ephemeral0"
    }
  ]
```

Could someone please help with a correct format or mapping as it is very urgent .....

**Comment by rickard-von-essen** [comment]
Please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._

**Comment by rickard-von-essen** [comment]
What are you trying to do?

**Comment by cezanedeepak** [comment]
Hi Rickard, 

I am trying to create an AMI for elasticsearch datanode,masternode and client node using Packer. 

So for datanode I need to mount additional volume. 

For that I am trying to attach additional ebs volume of 10gb with my AMI so that when an instance is launched out this AMI a 10 GB ebs volume should get attached automatically.

Below is a part of my json template


"type": "amazon-ebs",
    "region": "ap-southeast-1",
    "source_ami":"ami-667b048c",
    "instance_type": "t2.micro",
    "ssh_username": "ubuntu",
    "ami_name": "packer-ES-{{timestamp}}",
	"launch_block_device_mappings": [
    {
      "device_name": "/dev/sda1",
      "volume_size": 8,
      "volume_type": "gp2",
      "delete_on_termination": true
    }
  ],
  "ami_block_device_mappings": [
   
	 {
    "device_name": "/dev/sdb",
    
    "volume_size": 10,
	"delete_on_termination": true
    
}
  ]
  }],


I want to know where i am going wrong? 

And please help me once rather than closing the issues. That will be much appericiated.

Thanks.

**Comment by rickard-von-essen** [comment]
> And please help me once rather than closing the issues. That will be much appericiated.

This software is provided for free by HashiCorp and volunteers. Please respect the rules that are clearly written in the issue template. GitHub issues shouldn't be used for questions. I'll answer your mail on the mailing list. If you need an SLA you can set up an enterprise agreement with HashiCorp or hire a contractor that knows Packer.
