### ISSUE TITLE
Authentication failure running vagrant up 'box'

### ISSUE THREAD

**Issue by rzhang-nevermore** [hashicorp/packer#6515]
I build a custom box (template.json) using packer, when I try to `vagrant up` this box, I get an authentication error and can't login to the VM, what am I missing and how should I modify my template to solve this?

**Comment by rickard-von-essen** [comment]
Please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._

**Comment by rickard-von-essen** [comment]
Send an email to the mailing list, provide all details about what you have done. Packer templates and scripts to recreate the box you built and the commands you execute to build, import, and start the vagrant box.
