### ISSUE TITLE
virtualbox-vbox: builder similar to hyperv-vmcx

### ISSUE THREAD

**Issue by galeksandrp** [hashicorp/packer#6516]
feature request: virtualbox-vbox: builder similar to hyperv-vmcx with features like
- cloning from existing virtualbox machine
- cloning from existing virtualbox machine using linked clone (which should speed up process creating new machine a lot)
- register existing `vbox` local file for further cloning/linked cloning
- download remote `vbox` file and register it for further cloning/linked cloning

**Comment by rickard-von-essen** [comment]
How is this different from the `virtualbox-ovf`?

**Comment by galeksandrp** [comment]
`virtualbox` can't use `ova`/`ovf` directly, it does import into internal `vbox` format. When `virtualbox-ovf` imports `ovf`/`ova` file, it copies virtual disks files, which increases machine creation times. This is mostly noticeable when multiple machines with lare disks (multiple GBs) builded in parallel.
<details><summary>Building multiple Windows machines take times</summary>

Even on SSDs, for example, building derivatives of [modern.ie](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) machines takes tens of minutes.

</details>
Proposed `virtualbox-vbox` builder can use existing machine in `vbox` format (imported early from `ova`/`ovf`). This leads to ability to use linked clones, which created immediately, since they are relies on VirtualBox snapshots system. This reduces machine creation times to nearly zero.
