### ISSUE TITLE
packer ssh handshake failed prematurely

### ISSUE THREAD

**Issue by rzhang-nevermore** [hashicorp/packer#6517]
When I create a centos 7 box with a custom kickstart file, packer trys to ssh into the VM and failed prematurely.

What I mean by this is: in my kickstart file, I set up the vagrant user and password, and install core centos packages, which include `openssl-server`, in debug mode, I noticed that immediately after the VM installs the openssh deamon in the middle of the kickstart process, packer reports a handshake failure because at that time, the VM hasn't finished the kickstart yet, and only when the VM finishes the kickstart and reboots, it will have the `vagrant` user set up and then packer can ssh into it. I think this is a bug, or is there a way for packer to wait until the kickstart of VM to finish and then to ssh to the VM?

- Packer v1.2.4
- Windows 10 enterprise

**Comment by rickard-von-essen** [comment]
Please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._

**Comment by rickard-von-essen** [comment]
Send a email to the mailing list and provide your template.json and kickstart.cfg and we can have a look.
