### ISSUE TITLE
packer 1.2.5 vmware-iso builder now requires use of ovftool even though keep_registered boolean is set to true

### ISSUE THREAD

**Issue by ulysses-31** [hashicorp/packer#6519]
packer vmware-iso builder supports the boolean option "keep_registered" which when set to true did not result in a call to ovftool.

From doc:

•keep_registered (boolean) - Set this to true if you would like to keep the VM registered with the remote ESXi server. This is convenient if you use packer to provision VMs on ESXi and don't want to use ovftool to deploy the resulting artifact (VMX or OVA or whatever you used as format). Defaults to false.

packer 1.2.5 builder/vmware was updated as follows with the following 'bug fix':

•builder/vmware:Correctly default the vm export format to ovf; this is what the docs claimed we already did, but we didn't. [GH-4538]

Now the exact same template.json with packer 1.2.5 using the "keep_registered" boolean set to true results in a call to ovftool which should not occur based on the documented functionality of "keep_registered". Resulting in a failed build.

2018/07/20 11:21:59 packer: 2018/07/20 11:21:59 [DEBUG] Opening new ssh session
2018/07/20 11:21:59 packer: 2018/07/20 11:21:59 [DEBUG] starting remote command: vim-cmd vmsvc/reload 240
2018/07/20 11:22:00 ui error: ESC[1;31m==> vmware-packer: Error ovftool not found: exec: "ovftool": executable file not found in $PATHESC[0m

**Comment by SwampDragons** [comment]
Thanks for opening this ticket, and apologies for the regression. We'll make sure to look into this for the next release.

**Comment by lmayorga1980** [comment]
:+1:

**Comment by reyesjos500** [comment]
is there any workaround until the new build with the fix?

**Comment by ulysses-31** [comment]
@SwampDragons np, thanks for trying to fix for next release.

@reyesjos500 workaround is to set the boolean option "skip_export" to true.
