### ISSUE TITLE
AWS permissions

### ISSUE THREAD

**Issue by andyjp94** [hashicorp/packer#6521]
It would be useful for Packer to publish the IAM role required to use it. Considering the documentation by default assumes you will be running in AWS it seems like this should be necessary. Right now if I was to upgrade a version of Packer my CI environment could fall over simply because the permissions required change and I'd have no way of knowing that from the Packer documentation.

**Comment by rickard-von-essen** [comment]
https://www.packer.io/docs/builders/amazon.html#iam-task-or-instance-role

**Comment by SwampDragons** [comment]
Closing because I think this is already explained in the docs. However, if anyone has ideas for improvement, I'm happy to hear them or review a PR.
