### ISSUE TITLE
Compress post-processor support for xz

### ISSUE THREAD

**Issue by ltrager** [hashicorp/packer#6523]
I'm trying to use the compress post-processor to xz compress the outputted raw file. I added the following to my template

```json
"post-processors": [
    {
        "type": "compress",
        "output": "{{.BuildName}}.xz"
    }
]
```

This creates qemu.xz as an xz compressed tar archive. I need the output to be an xz compressed raw image.

**Comment by rickard-von-essen** [comment]
This is because the post-processors doesn't support `xz`. See https://www.packer.io/docs/post-processors/compress.html#supported-formats

**Comment by ChrisLundquist** [comment]
@ltrager are you able to give the linked PR a shot to see if that is what you're looking for?
