### ISSUE TITLE
Packer tries to make absolute url relative

### ISSUE THREAD

**Issue by TTH-Someone-stole-my-name** [hashicorp/packer#6524]
Description: I try to run an old packer file (verified to work with version 1.2.3) with the new version 1.2.5. When I do that I get an error message, indicating that the path of my iso can't be made relative to the directory containing my checksum_url file. But I provided the paths for both my iso and my checksum file absolute, so there should be no need to make anything relative.

> * Rel: can't make C:\12.04\ubuntu-12.04.5-server-amd64.iso relative to \12.04

1. Packer Version: 1.2.5
2. Packer precompiled binary on Windows 10 Enterprise
3. Output with Debug enabled: [See here](https://gist.github.com/TTH-Someone-stole-my-name/a73ee5982151584194df0c70e2946726)
4. Minimal Template to reproduce: [See here](https://gist.github.com/TTH-Someone-stole-my-name/e5997651537a430e5fe52049baca17a6)

**Comment by SwampDragons** [comment]
Hmm. I'd hoped that this was solved in https://github.com/hashicorp/packer/issues/6028 since it looks like a duplicate.  I'll definitely dig in for the next patch. Sorry for the regression.

**Comment by SwampDragons** [comment]
Here's a windows build of an attempted fix -- can you let me know if it works for you? (see PR 6525 for the changes) [packer.zip](https://github.com/hashicorp/packer/files/2220286/packer.zip)

**Comment by TTH-Someone-stole-my-name** [comment]
Hi
Thank you for looking into this so quickly. I can confirm that the attempted fix is a successful one.
