### ISSUE TITLE
amazon-ebs timeout when encrypt_boot: true

### ISSUE THREAD

**Issue by jjsp556** [hashicorp/packer#6526]
When using the amazon-ebs builder in Packer v1.2.5 to build an ami where "encrypt_boot": true, the build will timeout and prematurely fail. This was not an issue in v1.2.4. This error occurs regardless of whether kms_key_id is set or not. 

- Packer v1.2.5
- CentOS 7

==> amazon-ebs: Waiting for AMI to become ready...
==> amazon-ebs: Creating Encrypted AMI Copy
==> amazon-ebs: Copying AMI: us-east-1(ami-xxxxxxxx)
==> amazon-ebs: Waiting for AMI copy to become ready...
==> amazon-ebs: Error waiting for AMI Copy: ResourceNotReady: exceeded wait attempts
==> amazon-ebs: Deregistering the AMI because cancellation or error...
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Cleaning up any extra volumes...
==> amazon-ebs: No volumes to clean up, skipping
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: Error waiting for AMI Copy: ResourceNotReady: exceeded wait attempts

**Comment by SwampDragons** [comment]
Sorry for this! 

Caused by https://github.com/hashicorp/packer/pull/6332/files.  

Looks like the AWS_MAX_ATTEMPTS default is broken. Try setting the env var `AWS_MAX_ATTEMPTS=150` as a workaround and I'll fix this in the code ASAP.
