### ISSUE TITLE
vmware-iso "invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by bandit145** [hashicorp/packer#6527]
I am on packer 1.2.5 and whenever I attempt to use vmware-iso against esx6.0 I get this "invalid memory address or nil pointer dereference" error, in the log it looks like it happens exactly after vmware-iso starts.
I was also running packer on windows 10 64 bit.
All the needed info should be here (crash log and build template) https://gist.github.com/bandit145/b9aeb9659c0c774860052a1e02ceae5e

**Comment by SwampDragons** [comment]
Is this a regression from an earlier version of Packer? Did this config work for you before version 1.2.5? Or is this a new config that you have not gotten working yet? (trying to figure out how to label this issue)

**Comment by bandit145** [comment]
This is a new config on version 1.2.5, never was tested on an older version.

**Comment by SwampDragons** [comment]
Okay, I think I found the source of the crash and fixed it. If my hunch is right, this build should give you a useful error message `Error invalid vSphere sdk endpoint:   ...` instead of crashing

[packer.zip](https://github.com/hashicorp/packer/files/2221389/packer.zip)

**Comment by bandit145** [comment]
Ha! So it still was user error, but yeah I just saw my bad variable and packer didn't die. Thanks.

**Comment by SwampDragons** [comment]
Part user error but also part legitimate bug. Packer should fail gracefully with an error message instead of crashing. Thanks for opening the issue :)
