### ISSUE TITLE
chef-solo provisioner fails under docker builder with Chef::Exceptions::CannotDetermineNodeName

### ISSUE THREAD

**Issue by 375gnu** [hashicorp/packer#6531]
When I run `packer` with `docker` builder and `chef-solo` provisioner the latter fails with error ```Chef::Exceptions::CannotDetermineNodeName: Unable to determine node name: configure node_name or configure the system's hostname and fqdn```

Similar error was reported as #1648 but closed as duplicate of #1118 closed as duplicate of #1295 which *did not* solve the issue.

- Packer version: 1.2.5
- Host system: Devuan 2.0
- Guest system: opensuse/leap:42
- Debug log output from `PACKER_LOG=1 packer build template.json`.
https://gist.github.com/375gnu/1e459e000a4460e4500b703547c2611c#file-packer-log
- The _simplest example template and scripts_ needed to reproduce the bug.
https://gist.github.com/375gnu/1e459e000a4460e4500b703547c2611c#file-test-json

IMHO the best way to fix it is to add configurable `node_name` option to `client.rb` with default value `localhost`.

**Comment by rickard-von-essen** [comment]
I tried just adding `-N localhost` to `execute_command`  but then it fails with:

```
FATAL: Net::HTTPServerException: 404 "Not Found"
```

Do you know how to run _chef-solo_ on a `opensuse/leap:42` docker image (manually)? If so please provide a detailed description.

**Comment by 375gnu** [comment]
Currently we use chef-solo 11.18.12 and it runs with `-N localhost`. I'll play with current chef versions tomorrow.

**Comment by 375gnu** [comment]
I wasn't able to figure out how to run chef-solo 14. When I run it only with `-N` then I have 'Internal server error' because `/var/chef/nodes` directory can't be created, but when I pass `-c solo.rb` which defines only `cookbook_path []` I have `Not found /nodes/localhost.json`, I can't figure out what directory it uses in this case.

**Comment by 375gnu** [comment]
Okay, got it. I've put updated test.json to https://gist.github.com/375gnu/1e459e000a4460e4500b703547c2611c#file-test-json (`cookbook_path` was added). Just make `mkdir /tmp/cookbooks` and run `packer build`.

**Comment by rickard-von-essen** [comment]
Running the same code against a VM with OpenSUSE Leap 42, everything is fine without `-N localhost`. I think this is just a Docker + Chef-Solo thing. Maybe just add a not in the docs for `chef-solo`?

Or a optional `node_name` that adds the flag to the `execute_command`?

**Comment by SwampDragons** [comment]
Closing since it looks like this is a docker v. chef-solo bug, not a packer one.
