### ISSUE TITLE
qemu builder should have copy host CPU configuration option

### ISSUE THREAD

**Issue by ltrager** [hashicorp/packer#6535]
Some installers check for various CPU features before allowing installation to begin. While you can specify qemu CPU flags using the qemuargs option this requires a different packer template per CPU type. libvirt has an option 'copy host CPU configuration' which makes available all CPU features available on the host CPU to the guest. It would be nice for packer to support the same thing.

Example:
The VMware ESXi installer checks that the CPU supports hardware virtualization before allowing the installation to begin. By default qemu does not expose this CPU feature. On Intel platforms the CPU flag is called vme, while on AMD platforms the CPU flag is called svm. Because of this I can't create one packer template that works on both Intel and AMD platforms.

**Comment by adarobin** [comment]
@ltrager Can't you just add `-cpu host` as an argument to `qemuargs` in your packer template?

**Comment by ltrager** [comment]
ah I missed that option. Thanks for the suggestion, that works great!
