### ISSUE TITLE
Exporting unprivileged LXC containers fails

### ISSUE THREAD

**Issue by thedrow** [hashicorp/packer#6545]
When the export step is run, it tries to tar the rootfs.
Unfortunately I failed to notice before that it failed due to some of the files in the rootfs belonging to the container's root.
It seems that exporting the container requires us to run sudo. When running sudo you get a prompt which you can't fill since we're not listening to input.
Not sure how to resolve this correctly.

**Comment by thedrow** [comment]
This is the only solution I currently have:
```patch
diff --git a/builder/lxc/step_export.go b/builder/lxc/step_export.go
index b6f5aca5f..7834cb958 100644
--- a/builder/lxc/step_export.go
+++ b/builder/lxc/step_export.go
@@ -54,14 +54,17 @@ func (s *stepExport) Run(_ context.Context, state multistep.StateBag) multistep.
 
 	_, err = io.Copy(configFile, originalConfigFile)
 
-	commands := make([][]string, 3)
+	commands := make([][]string, 4)
 	commands[0] = []string{
 		"lxc-stop", "--name", name,
 	}
 	commands[1] = []string{
-		"tar", "-C", containerDir, "--numeric-owner", "--anchored", "--exclude=./rootfs/dev/log", "-czf", outputPath, "./rootfs",
+		"sudo", "setfacl", "-R", "-m", fmt.Sprintf("u:%s:rwx", user.Uid), filepath.Join(containerDir, "rootfs"),
 	}
 	commands[2] = []string{
+		"tar", "-C", containerDir, "--numeric-owner", "--anchored", "--exclude=./rootfs/dev/log", "-czf", outputPath, "./rootfs",
+	}
+	commands[3] = []string{
 		"chmod", "+x", configFilePath,
 	}
 
```
Right now I `sudo su` to ensure I have the password cached.

**Comment by rickard-von-essen** [comment]
Does setting `command_wrapper` to `sudo -n` help?

**Comment by thedrow** [comment]
The above patch is incorrect. tar requires root privileges to preserve permissions and ownership.
So we're forced to use sudo anyway.
