### ISSUE TITLE
Error uploading script: Upload failed with non-zero exit status: 1

### ISSUE THREAD

**Issue by esacteksab** [hashicorp/packer#6547]
I stumbled upon this https://github.com/hashicorp/packer/issues/6151 so perhaps they're similar? 

I originally started on 1.2.5 and then per the above mentioning a regression in 1.2.2 I tried 1.2.1 with the same behavior. 

- Packer version from `packer version`
```
Packer v1.2.1
Packer v1.2.5
```

- Host platform
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```

- Docker version: 
```
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:09:54 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:07:56 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Debug log output from `PACKER_LOG=1 packer build template.json`.
- The _simplest example template and scripts_ needed to reproduce the bug.
https://gist.github.com/esacteksab/c184a3572f3fdbdf62d7a4e564ea6e94

**Comment by SwampDragons** [comment]
Can you run this? I've added a bunch of custom loglines to try to debug. I can't repro on OSX, so this seems to be OS related.
[packer.zip](https://github.com/hashicorp/packer/files/2242998/packer.zip)

**Comment by SwampDragons** [comment]
here's a build of master, for comparison: 
[packer.zip](https://github.com/hashicorp/packer/files/2243017/packer.zip)

**Comment by esacteksab** [comment]
What you provided works. Appreciate the help!
