### ISSUE TITLE
Packer Ansible Remote - ERROR! tags must be specified as a list

### ISSUE THREAD

**Issue by Boojs** [hashicorp/packer#6551]
Hi there,

I am having a bit of trouble running the ansible remote provisioner. Everything else seems to work great. Just not sure why I am getting this error now.

Here is my ansible provisioner piece

```
    {
      "type": "ansible",
      "playbook_file": "ansible/site.yml",
      "ansible_env_vars": [ "ANSIBLE_HOST_KEY_CHECKING=False", "ANSIBLE_SSH_ARGS='-o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s -o ServerAliveInterval=50'", "ANSIBLE_NOCOLOR=True", "ANSIBLE_CONFIG=ansible/ansible.cfg", "ANSIBLE_ROLES_PATH=roles" ],
      "extra_arguments": [
        "--vault-password-file=ansible/vault_files/vault_password_file"
      ],
      "only": ["virtualbox-iso", "vmware-iso"],
      "groups": "vagrant_development_servers",
      "user": "vagrant"
    },

```

Then when running packer the error is:

```
==> vmware-iso: Executing Ansible: ansible-playbook --extra-vars packer_build_name=vmware-iso packer_builder_type=vmware-iso -i /tmp/packer-provisioner-ansible231168758 /var/lib/jenkins/workspace/_devops.packer_builder/ansible/site.yml -e ansible_ssh_private_key_file=/tmp/ansible-key327201587 --vault-password-file=ansible/vault_files/vault_password_file
    vmware-iso:  [WARNING]: Ignoring invalid attribute: force
    vmware-iso:  [WARNING]: Ignoring invalid attribute: state
    vmware-iso:  [WARNING]: Ignoring invalid attribute: sudo
    vmware-iso:  [WARNING]: Ignoring invalid attribute: creates
    vmware-iso: ERROR! tags must be specified as a list

```

Any help would be greatly appreciated!

**Comment by rickard-von-essen** [comment]
Have you tried a dummy playbook to verify if this is caused by your playbook?

**Comment by Boojs** [comment]
Hey @rickard-von-essen 

Thanks for the reply and good question! It seems to move forward with a dummy playbook. Not sure why though? My regular playbook **site.yml** is just an include of other playbooks.

The odd thing here is that I had it working at a point in time, but for some reason now it stopped and I am completely baffled by what could have triggered it to stop.

**Comment by rickard-von-essen** [comment]
I think it's better if you send a question to the mailing list and provide all files needed to reproduce this. It seems like a problem with the playbook it self.
