### ISSUE TITLE
Can't create image for instance type ecs.gn5-c4g1.xlarge in Alicloud

### ISSUE THREAD

**Issue by jhagege** [hashicorp/packer#6556]
Hi I'm trying to create an instance for the type ecs.gn5-c4g1.xlarge.
I get the error "InvalidDiskCategory.CreateImage".

I think it's because packer tries to create an image of the I/O-Intensive Local Disk 440GB.
I don't need to create an image of this, just of system disk.

By default, this instance type creates two disks:
![image](https://user-images.githubusercontent.com/7504908/43454075-8dc7b89a-94c4-11e8-874b-21c3fc972e65.png)

Can I instruct packer to create an image only for the system disk, and not the second disk ? 
Thanks !

**Comment by chhaj5236** [comment]
This feature has been satisfied by https://github.com/hashicorp/packer/pull/7022 and can be closed now.
