### ISSUE TITLE
Packer for Windows 2016 server datacenter version

### ISSUE THREAD

**Issue by panni1986** [hashicorp/packer#6571]
Issue: I am trying to build a windows 2016 server datacenter edition using packer template.
when the vm boots after initial build it gets stuck @"getting device ready" state. Need help.

- Packer version from `packer version` 1.2.2
- Host platform Ubuntu 16.04 
- Debug log output from `PACKER_LOG=1 packer build windows2016.json`.
[packer_log.txt](https://github.com/hashicorp/packer/files/2261558/packer_log.txt)

json file:
[windows2016json.txt](https://github.com/hashicorp/packer/files/2261574/windows2016json.txt)
 answer file:
[Autounattendxml.txt](https://github.com/hashicorp/packer/files/2261580/Autounattendxml.txt)

**Comment by rickard-von-essen** [comment]
Please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._
