### ISSUE TITLE
Unnecessary double validation

### ISSUE THREAD

**Issue by marcoslopes** [hashicorp/packer#6573]
Hi guys, just saving some duplication.

https://github.com/hashicorp/packer/blob/55858552655da34ccf97ba3167204750a35d301b/provisioner/chef-client/provisioner.go#L191

https://github.com/hashicorp/packer/blob/55858552655da34ccf97ba3167204750a35d301b/provisioner/chef-client/provisioner.go#L177

**Comment by SwampDragons** [comment]
Good catch, thanks!
