### ISSUE TITLE
vsphere post-processor crashing with OOM error

### ISSUE THREAD

**Issue by akulbe** [hashicorp/packer#6581]
I'm genuinely uncertain as to whether this is a legitimate bug, or a configuration error on my part.

When I attempt to run the build, it is done as follows: 

PACKER_LOG=1 PACKER_LOG_PATH=./debug.log packer build -var='vsphere_user=myuser' -var='vsphere_pass=*************' -force rhel75.json

[debug.log](https://github.com/hashicorp/packer/files/2279914/debug.log)
[rhel75.json.txt](https://github.com/hashicorp/packer/files/2279916/rhel75.json.txt)

I'm running go 1.10.3 and packer 1.2.5

**Comment by SwampDragons** [comment]
OOM sounds like your host isn't beefy enough to run the build. Looks like it fails on the post-processing step with ovftool. if you remove that step, does the build complete? If you run that step by hand, do you still get an OOM error?

**Comment by SwampDragons** [comment]
I'm closing this because I think it has more to do with resource constraints on the host machine than with Packer. Please reopen if that turns out not to be the case.
