### ISSUE TITLE
Packer: building custom image for CentOS 7 for HDP Cluster deployment

### ISSUE THREAD

**Issue by kudumha** [hashicorp/packer#6582]
Hi Gurus,
I am trying to build a custom image for CentOS 7 to deploy HDP Cluster via Cloudbreak. I am new to use the packer. can you route me to any documentation specific to Azure build 'azure-arm'.

**Comment by SwampDragons** [comment]
Here's the builder documentation: https://www.packer.io/docs/builders/azure.html
And here's documentation for how to get the necessary credentials (this can be a little difficult to figure out on your own): https://www.packer.io/docs/builders/azure-setup.html

If you have any more issues, please reach out to the mailing list, which has more followers and will be more likely to have someone able to help you with your particular needs: https://groups.google.com/forum/#!forum/packer-tool
