### ISSUE TITLE
pause_before causes the second shell to wait for 15min before running

### ISSUE THREAD

**Issue by monstruooo** [hashicorp/packer#6586]
18:00:15 ==> amazon-ebs: Pausing 33s before the next provisioner...
18:00:48 ==> amazon-ebs: Provisioning with shell script: /tmp/packer-shell305842835
18:17:11     amazon-ebs: + egrep Finished /tmp/yum-update-status
18:17:11     amazon-ebs: + export PLUTO_ENV=qa

The moment I remove pause_before, the second shell starts immediately

```  },{
    "type": "shell",
    "expect_disconnect": true,
    "start_retry_timeout": "1m",
    "inline": [
      "set -x",
      "sudo yum -y update",
      "echo Finished yum -y update | sudo tee /tmp/yum-update-status"
    ]
  },{
    "type": "shell",
    "pause_before": "33s",
    "start_retry_timeout": "1m",
    "inline": [```

**Comment by monstruooo** [comment]
Actually I see that it's happening again without pause_before

The ssh connection seems to work fine. The second shell even executes the first command, but then stops advancing for another 15 min

**Comment by monstruooo** [comment]
By now we ran several dozens of tests and the problem occurs in about 20% of them.  Expect_disconnect does seem to prevent the shell from exiting with error. But the shell can remain stuck in this state for 15 min.

If I try manually connect to the instance, ssh looks fine (Though I didn't try to login).

**Comment by SwampDragons** [comment]
Okay, thanks for the follow-up. I'd like to dig in further, but I need more information. Given that this is a sort of infrequent one, it's really important that you give me everything you do to reproduce --  the full logs with PACKER_LOG=1 and the simplest possible config necessary for me to reproduce this.

**Comment by SwampDragons** [comment]
I don't think this is actionable without more information, so I'm going to close.
