### ISSUE TITLE
Feature request - builder to create an AMI from a running EC2 instance

### ISSUE THREAD

**Issue by giladsh1** [hashicorp/packer#6608]
It would be really useful if I was able to use Packer to create AMIs from existing EC2 instances.
I Believe this is a common use case, for teams that are working in multiple AWS accounts.

I would like to filter instances by some attributes and create AMIs from all of them at the same time.
currently I need to first create an AMI using some AWS SDK, and only then use Packer to copy the same AMI to other accounts and regions.

**Comment by rickard-von-essen** [comment]
IMHO this goes against the spirit of Packer being a automation tool for defining images in source, not from an unknown state.

**Comment by SwampDragons** [comment]
Yeah, Packer is the wrong tool for this workflow. You can probably create something much more appropriate and resilient using the AWS CLI.
