### ISSUE TITLE
Feature request - GCE add option to populate metadata `user-data` from a file

### ISSUE THREAD

**Issue by robertpeteuil** [hashicorp/packer#6617]
Hi,

I would like to see a Packer option to import the `user-data` key of `metadata` from a file.  

This would be similar to the option `startup_script_file` which populates the `startup-script` key, except it would populate `user-data` and thus work with cloud-init scripts.

This can be accomplished with:

``` bash
gcloud compute instances create INSTANCE_NAME \
    --image IMAGE_NAME \
    --metadata-from-file user-data=FILENAME
```

**Comment by psinghal20** [comment]
Hi @SwampDragons, I would like to work on it. I am new to the Hashicorp community and somewhat familiar with go. Could you give me some pointers for this issue? Thanks!

**Comment by rickard-von-essen** [comment]
Just copy parts of the code starting [here](https://github.com/hashicorp/packer/blob/master/builder/googlecompute/step_create_instance.go#L41) and change to `user-data` and work your way back.
