### ISSUE TITLE
packer-shell138523863' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by gravypower** [hashicorp/packer#6620]
Hello 

I am receiving the below issue and I can not work out why was asked to raise this issue from the google groups.

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/packer-tool/sn2-MiZVv30/8WJyR7B1AQAJ

==> vmware-iso: Running local shell script: C:\Users\ADMINI~2\AppData\Local\Temp\packer-shell138523863
    vmware-iso: 'C:\Users\ADMINI~2\AppData\Local\Temp\packer-shell138523863' is not recognized as an internal or external command,

- Packer version from `packer version`
v1.2.4
- Host platform
WIndows 10
- Debug log output from `PACKER_LOG=1 packer build template.json`.
- The _simplest example template and scripts_ needed to reproduce the bug.

https://gist.github.com/gravypower/3ba5838839e33c95f8029365940a0045

any help would be grate.

**Comment by SwampDragons** [comment]
Hi! Sorry for this regresssion.

THE WORKAROUND: 
I suspect this will work for you if you add the option `"tempfile_extension": ".cmd",` to your provisioner.  

THE LONG TERM FIX:
I've opened a PR, https://github.com/hashicorp/packer/pull/6626, that should fix this without the above workaround. I've attached a build of the PR branch to that PR, and would love if you could take the time to test it.
