### ISSUE TITLE
restrict source cidr range

### ISSUE THREAD

**Issue by Janus1974** [hashicorp/packer#6623]
When packer stands up a new instance i see that it's creating a security group allowing access on the winrm port (5986) from 0.0.0.0/0.  

This is a problem for me as my company doesn't allow anything from any source except for http and https.  Every time i've started a build the security team have received alerts and I get a call from them!

Is there a way to define the cidr range of the security group that's created?

Thanks

**Comment by rickard-von-essen** [comment]
Please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._

**Comment by rickard-von-essen** [comment]
Use [`security_group_ids`](https://www.packer.io/docs/builders/amazon-ebs.html#security_group_ids) to give a list of SG's that the instance should be launched with. Just ensure that the host running Packer can access the instance on port 22 with these SG's.
