### ISSUE TITLE
Change the value of .BuildName

### ISSUE THREAD

**Issue by martinanderssondotcom** [hashicorp/packer#6630]
There are many places that refer to a "build name", for example [this][1], describing the output file name coming from the VirtualBox-ISO builder:

> By default this is output-BUILDNAME where "BUILDNAME" is the name of the build.

All I know is that when I make a linked clone from any one of my builds (be that VirtualBox or VMware), the base machines are going to be named something ridiculous, like "packer-virtualbox-iso-1532725717_1532737685831_4936" for example.

I do not understand what all these numbers that has been added to the name mean. However that might be, I would like a custom name that is a little bit more "readable".

How can I set a custom name?

My thinking is that it has to do with this secret variable `{{.BuildName}}`. But the "build name" seems to be completely undocumented. Not only would I like to know how this build name is computed and what the numbers mean, but also how to change it =)

Thanx!

[1]: https://www.packer.io/docs/builders/virtualbox-iso.html#output_directory

**Comment by rickard-von-essen** [comment]
Please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._

**Comment by rickard-von-essen** [comment]
See [Named Builds](https://www.packer.io/docs/templates/builders.html#named-builds).

**Comment by rickard-von-essen** [comment]
No worries. Just send a email to the list if there is any more uncertainties.
