### ISSUE TITLE
VMware ISO builder broken on master when building against ESXi - ssh: no key found

### ISSUE THREAD

**Issue by DanHam** [hashicorp/packer#6631]
```
$ PACKER_LOG=1 packer build debian-esxi-standalone.json 2>packer.log
vmware-iso-vsphere output will be in this color.

Build 'vmware-iso-vsphere' errored: Failed creating VMware driver: Unable to initialize any driver for this platform. The errors
from each driver are shown below. Please fix at least one driver
to continue:
* ssh: no key found
```

Full log: [HERE](https://gist.github.com/DanHam/f8368f07fdf40e0da8b1e43f7cc354f9)
Template: debian-esxi-standalone.json [HERE](https://github.com/DanHam/packer-testing/blob/master/vmware/iso/debian/debian-esxi-standalone.json)

Note that you can reproduce the error without having to stand up an ESXi instance to test against as the build doesn't get that far.

I haven't had time to look at this properly. However, from a very cursory look, the most likely candidate for the error is #6613 (specifically fa44a4546f29d86c4015545b0adbc4464aedb4aa)

**Comment by azr** [comment]
Howdy, 

Thanks for making an issue ! 🙂 
I have the exact same issue when I checkout `v1.1.3` or way older releases ( that I could build ); can you please point me to a commit where it works for you ?

**Comment by DanHam** [comment]
> I have the exact same issue when I checkout v1.1.3 or way older releases

@azr Something's not right with your builds there! This was working up until recently - I used these templates to test #6448 which was version 1.2.4.

Immediately prior to the merge of #6613 works:
Packer v1.2.6-dev (d883dfe67) - see the log [HERE](https://gist.github.com/DanHam/f99821423650e0e7acbc447cab2d6358#file-working-at-d883dfe67)

Immediately after the merge of #6613 does not work:
Packer v1.2.6-dev (340363a64) - see the log [HERE](https://gist.github.com/DanHam/f99821423650e0e7acbc447cab2d6358#file-fails-at-340363a64)

This definitely means the problem was introduced by #6613!! 

I don't have any more time to look into this but, like I said before, fa44a45 would be a good place to start looking...

**Comment by azr** [comment]
Hey @DanHam yup you're totally right, twice, I did something wrong with my config and the problem comes from fa44a45;

see I thought PrivateKey was the actual private key where in fact PrivateKey refers to the PrivateKeyPath and I got confused and fixed it a bit too quickly.

**Comment by azr** [comment]
Okay I think this commit fixed it, I tried and it worked; 

but if you have some time, please tell me if branch ssh_keys_centralised (or 16f73c90e) fixes it for you.

**Comment by DanHam** [comment]
👍 Yep... building off the ssh_keys_centralised branch fixes the issue.
