### ISSUE TITLE
SSH issue with an existing CentOS image

### ISSUE THREAD

**Issue by ksachdev1** [hashicorp/packer#6632]
Here is a sample json file I have that I am using. The image that I am using is raw qemu image and has OS installed on it and it boots up fine and on the qemu console I can even ssh with credentials that I have in json. To keep things simple I just want my cleanup.sh script to create a directory(for now). However, packer never detects that VM has booted up and times out.

```
{
  "builders":
  [
    {
      "type": "qemu",
      "disk_image":"true",
      "iso_url": "mypacker.img",
      "iso_checksum": "fde15e33d4f0939dcf84ea0278cd07a9",
      "iso_checksum_type": "md5",
      "output_directory": "/tmp/packerout1",
      "shutdown_command": "echo 'packer' | sudo -S shutdown -P now",
      "disk_size": 9000,
      "format": "raw",
      "headless": false,
      "ssh_username": "root",
      "ssh_password": "check123",
      "ssh_timeout": "5m",
      "vm_name": "tdhtest"
    }
  ],
  "provisioners": [
    {
      "type": "shell",
      "scripts": [
        "cleanup.sh"
      ]
    }
  ]

}
```
**I get the below error**

````
SSH handshake err: ssh: handshake failed: read tcp 127.0.0.1:39116->127.0.0.1:2702: read: connection reset by peer
2018/08/26 00:10:00 ui error: ==> kvm: Timeout waiting for SSH.
==> kvm: Timeout waiting for SSH.
2018/08/26 00:10:00 packer: 2018/08/26 00:10:00 [DEBUG] SSH wait cancelled. Exiting loop.
2018/08/26 00:10:00 ui: ==> kvm: Deleting output directory...
==> kvm: Deleting output directory...
2018/08/26 00:10:00 [INFO] (telemetry) ending qemu
2018/08/26 00:10:00 ui error: Build 'kvm' errored: Timeout waiting for SSH.
2018/08/26 00:10:00 Builds completed. Waiting on interrupt barrier...
2018/08/26 00:10:00 machine readable: error-count []string{"1"}
2018/08/26 00:10:00 ui error: 
==> Some builds didn't complete successfully and had errors:
2018/08/26 00:10:00 machine readable: kvm,error []string{"Timeout waiting for SSH."}
2018/08/26 00:10:00 ui error: --> kvm: Timeout waiting for SSH.
2018/08/26 00:10:00 ui: 
==> Builds finished but no artifacts were created.
2018/08/26 00:10:00 [INFO] (telemetry) Finalizing.
Build 'kvm' errored: Timeout waiting for SSH.

==> Some builds didn't complete successfully and had errors:
--> kvm: Timeout waiting for SSH.
```

`
**My Qemu image already has CentOS7 installed on it.

I am running packer on Ubuntu - Ubuntu 18.04.1 LTS**

**Comment by ladar** [comment]
@ksachdev1 when you say:

> The image that I am using is raw qemu image and has OS installed on it and it boots up fine and on the qemu console I can even ssh with credentials that I have in json.

Do you mean SSH, from the host, to the actual IP address of the guest? Or can you only SSH to the port mapped address setup by packer? According to your log, that would have been `127.0.0.1:2702` ... but will likely change with each run. 

I've run into a very nasty OpenSSH 7.5 issue, where by I get the `read: connection reset by peer` error whenever I attempt to SSH from a CentOS host to a guest using a NAT'ed IP address. So far, I've only run into the issue with Gentoo guests, but perhaps your seeing the reverse of this with a CentOS guest, and Ubuntu 18.04 host. If so, connecting directly to the guest IP will work fine. Your fix would be adding a pre-defined `ssh_host` parameter to the template with the IP address it will get upon bootup. (Tip: the equivalent Vagrantfile setting for this is `v.ssh_info_public = true`).

The alternate, and probably more likely problem is your firewall settings. If it is your firewall, then you need to run `ifconfig` and get the name of your virtual bridge interfaces:

```bash
[ladar@lap providers]$ ifconfig 
enp0s25: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.70  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 2600:1700:3e40:3bb0:2ad2:44ff:fee5:20c3  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::2ad2:44ff:fee5:20c3  prefixlen 64  scopeid 0x20<link>
        ether 28:d2:44:e5:20:c3  txqueuelen 1000  (Ethernet)
        RX packets 72334773  bytes 106145936013 (98.8 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 10436229  bytes 766212343 (730.7 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 20  memory 0xe0600000-e0620000  

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 56368  bytes 204982616 (195.4 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 56368  bytes 204982616 (195.4 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

virbr0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 192.168.122.1  netmask 255.255.255.0  broadcast 192.168.122.255
        ether 52:54:00:51:3b:2e  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

virbr1: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 192.168.121.1  netmask 255.255.255.0  broadcast 192.168.121.255
        ether 52:54:00:8c:42:ef  txqueuelen 1000  (Ethernet)
        RX packets 165769  bytes 27326415 (26.0 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 68282  bytes 130547188 (124.4 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

In this case the virtual interfaces on my CentOS system are `virbr0` and `virbr1`. Assuming your using `firewalld` the commands to fix your problem would be (sub in your own interface names):

```bash
firewall-cmd --permanent --zone=trusted --add-interface=virbr0
firewall-cmd --permanent --zone=trusted --add-interface=virbr1
```

Either way, I don't see any evidence of a bug in packer with the information you provided.

**Comment by rickard-von-essen** [comment]
Please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._
