### ISSUE TITLE
vSphere post processor to work with standalone hosts

### ISSUE THREAD

**Issue by donthatem3** [hashicorp/packer#6639]
Our vCenter Server has architecture where you don't have clusters between data-centers and hosts , therefore I cannot use the vSphere post-processor since cluster is required. 

- Server
 - Datacenter
    - host (esx1)
    - host (esx2)
    - host (esx..N)

Can the post processor be extended to work with no cluster ? 

note*: There is some plugin for packer for vpshere-iso builder where it is possible to build with no cluster (https://github.com/jetbrains-infra/packer-builder-vsphere)

**Comment by SwampDragons** [comment]
It turns out that while the option is "cluster", you can already provide the IP address of a standalone host to upload. PR #9649 modifies the documentation to make this clear.
