### ISSUE TITLE
Add sles-12-sp3-sap project in gcp

### ISSUE THREAD

**Issue by ulyssesr** [hashicorp/packer#6642]
I'm trying to build an image based on sles-12-sp3-sap in GCP, but I'm getting an image not found error. I'm wondering if this image can be part of your list. Thanks.

**Comment by ulyssesr** [comment]
Yes, the source_image_project_id is in the json config file.

**Comment by rickard-von-essen** [comment]
Could you add a template for repo?

**Comment by SwampDragons** [comment]
Can you please share your config file?

**Comment by SwampDragons** [comment]
I still need to know what input you're giving it; as it is, I think this may be a documentation problem, not a bug.

**Comment by ulyssesr** [comment]
Here's the template:

{
  "variables" : {
    "source_image_family": "sles-12-sp3-sap",
    "image_family": "cah-sles-12-sp3-sap",
    "project_id": "REDACTED",
    "tools_dir": "cah-toolsstore/linux/tools",
    "config_dir": "cah-configstore/linux/config",
    "binary_dir": "cah-binarystore/linux/software",
    "script_dir": "cah-scriptstore/linux/",
    "subnetwork_id": "REDACTED",
    "zone": "us-central1-c",
    "machine_type": "n1-standard-1",
    "account_file": "C:/SYSADM/packer/REDACTED.json",
    "ssh_username": "REDACTED",
    "disk_size": "30",
    "tags": "internet-us-central1"
  },
  "builders": [
    {
      "type": "googlecompute",
      "account_file": "{{user `account_file`}}",
      "project_id": "{{user `project_id`}}",
      "omit_external_ip": true,
      "use_internal_ip": true,
      "subnetwork": "{{user `subnetwork_id`}}",
      "source_image_family": "{{user `source_image_family`}}",
      "zone": "{{user `zone`}}",
      "disk_size": "{{user `disk_size`}}",
      "machine_type": "{{user `machine_type` }}",
      "image_name": "{{user `image_family`}}-{{isotime | clean_image_name}}",
      "image_family": "{{user `image_family`}}",
      "ssh_username": "{{user `ssh_username`}}",
      "tags": "{{user `tags`}}"
    }
  ],
  "provisioners": [
    {
      "type": "file",
      "source": "{{user `tools_dir` }}",
      "destination": "/tmp/"
    },
    {
      "type": "file",
      "source": "{{user `config_dir` }}",
      "destination": "/tmp/"
    },
    {
      "type": "shell",
      "scripts": [
        "{{user `script_dir`}}/sles-12-sp3-sap.sh",
        "{{user `script_dir`}}/goldimage.sh",
        "{{user `script_dir`}}/reboot.sh"
      ],
      "execute_command": "REDACTED",
      "pause_before": "10s",
      "expect_disconnect": "true"
    },
    {
      "type": "shell",
      "scripts": [
        "{{user `script_dir`}}/fix-resolv-conf.sh",
        "{{user `script_dir`}}/coreapps.sh",
        "{{user `script_dir`}}/qc-build.sh"
      ],
	  "execute_command": "REDACTED",
	  "pause_before": "90s"
    }    
  ]
}

**Comment by SwampDragons** [comment]
I don't see source_image_project_id in that config file.

**Comment by SwampDragons** [comment]
Try adding `"source_image_project_id": "suse-sap-cloud"`

**Comment by ulyssesr** [comment]
I just tried "source_image_project_id": "suse-sap-cloud" but no cigar.

**Comment by SwampDragons** [comment]
Strange. 

```
      "source_image_family": "sles-12-sp3-sap",
      "source_image_project_id": "suse-sap-cloud",
```
works for me.

**Comment by SwampDragons** [comment]
What's your host architecture? I'll build you a copy of PR #6648 which should fix this without you having to add the project id.

**Comment by ulyssesr** [comment]
I'm running packer on a Windows 2016 Server. Thanks for including suse-sap-cloud. Much appreciated.
