### ISSUE TITLE
File provisioner says "no such file" when file does exist

### ISSUE THREAD

**Issue by mcred** [hashicorp/packer#6643]
Packer v1.2.5 on OSX 10.13.6
Debug log: https://gist.github.com/mcred/d529a4e28b5a29b1b7c24662a1ea39b4
Packer json: https://gist.github.com/mcred/6233f51c1d8f433d054a7e498a09fb80

Both `validate` and `build` fail with the following the following error:

```
Template validation failed. Errors are shown below.
Errors validating build 'amazon-ebs'. 1 error(s) occurred:
* Bad source '../target/daf-*.jar': stat ../target/daf-*.jar: no such file or directory
```

However, if I run `stat ../target/daf-*.jar` in the same directory it will return the following:
```
16777223 8140877 -rw-r--r-- 1 derek.smart staff 0 35558959 "Aug 30 15:04:08 2018" "Aug 30 14:55:03 2018" "Aug 30 14:55:03 2018" "Aug 30 14:55:03 2018" 4194304 69456 0 ../target/daf-0.0.1-SNAPSHOT.jar
```

The file certainly does exist. Any idea why packer seems to think it doesn't?

<img width="1128" alt="screen shot 2018-08-30 at 3 11 12 pm" src="https://user-images.githubusercontent.com/4326032/44873712-fdd47100-ac66-11e8-89ed-f4cf28f27f76.png">

**Comment by rickard-von-essen** [comment]
Not sure if we support globbing there.

**Comment by arizvisa** [comment]
yea. globbing is definitely not supported.

@mcred, what you can do is copy the whole directory (before the glob) and then use a script to move the glob'd filename to the correct place.

**Comment by mcred** [comment]
@arizvisa Thanks for the suggestion. I think it might be easier for me to set the file name when I build it and then move it.
