### ISSUE TITLE
ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

### ISSUE THREAD

**Issue by riponbanik** [hashicorp/packer#6645]
Adding the user_data_file using cloud-init(added in the gist below) for add new user causes packer to fail provisioner with the error in subject line, removing it works.

- Packer version from `packer version`
1.2.5
- Host platform - Windows 10
- Debug log output from `PACKER_LOG=1 packer build template.json`.
https://gist.github.com/riponbanik/013d9bf6053ca2975677b6840fdab295
- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your gist https://gist.github.com
 https://gist.github.com/riponbanik/f1dbd5bcac18241aea38a0d48bbae58d

**Comment by SwampDragons** [comment]
What builder are you using

**Comment by SwampDragons** [comment]
It looks to me like your cloud-init file may be setting up an authorized key that isn't generated by Packer. You need to make sure that the ssh username and password you give to Packer's communicator still exist, and that you're setting ssh_private_key_file so Packer knows what key to use.

**Comment by riponbanik** [comment]
@SwampDragons  it is amazon-ebs builder. I am allowing packer to generate the ssh key automatically for ec2-user like below :

"communicator": "ssh",  
 "ssh_pty" : "true",  
"ssh_username": "ec2-user",
 "ssh_timeout": "5m",

**Comment by riponbanik** [comment]
@SwampDragons I have found the issue - the default ec2-user was removed, do not know whether the issue is with cloud-config
