### ISSUE TITLE
Support building AMI from scratch

### ISSUE THREAD

**Issue by blalor** [hashicorp/packer#665]
This may be completely outside the scope of Packer, but I feel that having to build an AMI from an existing AMI is very chicken/egg.  It'd be great if I could create an AMI from absolutely nothing, using something like RedHat's kickstart.  I accomplished something similar earlier this year (https://github.com/blalor/vm-image-tools), and Sam Bashton has documented his process for publishing AMIs (http://www.bashton.com/blog/2012/how-to-make-your-own-centos-6-amis/).  It feels like a natural extension for Packer.

**Comment by mainframe** [comment]
+1 for AMI from scratch support

**Comment by LastManStanding** [comment]
+1 please add the ability to output an ami from an ISO input , maybe as a post process step

**Comment by shravanpn7** [comment]
+1

**Comment by kplimack** [comment]
+1

**Comment by rickard-von-essen** [comment]
Incoming, see #3855

**Comment by stumyp** [comment]
+1
may be something like bootstrap-vz, but better :)

**Comment by rickard-von-essen** [comment]
This is already supported with `amazon-chroot` builder using [`from_scratch`](https://www.packer.io/docs/builders/amazon-chroot.html#from_scratch) or alternatively use the [amazon-import](https://www.packer.io/docs/post-processors/amazon-import.html) post-processor to upload a OVA built with packer.
