### ISSUE TITLE
Please allow ovftool options to be used when using vmware workstation.

### ISSUE THREAD

**Issue by theemptyone** [hashicorp/packer#6651]
For builder: vmware-iso

Can we allow the format option if using vmware workstation.  ovftool is installed when you install the workstation.

I have a manual step to run ovftool after the vmx files are built.  Not sure why this is limited to only when building for esxi.

Thanks!

**Comment by arizvisa** [comment]
@theemptyone, what ovftool options are you using during export? or are you doing some kind of post-processing with ovftool?

**Comment by SwampDragons** [comment]
I'm not sure I understand. Are you talking about this format?  https://www.packer.io/docs/builders/vmware-iso.html#format

Because I think this should already be available to you.

**Comment by theemptyone** [comment]
"format (string) - Either "ovf", "ova" or "vmx", this specifies the output format of the exported virtual machine. This defaults to "ovf". Before using this option, you need to install ovftool. This option currently only works when option remote_type is set to "esx5". Since ovftool is only capable of password based authentication remote_password must be set when exporting the VM."

Format says it's only available in esx5, and i can confirm this option odes not work when using vmware workstation as of my last attempt.

`==> vmware-iso: Skipping export of virtual machine (export is allowed only for ESXi and the format needs to be specified)...`

I've worked around this for now by adding a post 

```
"post-processors": [
  {
    "type": "shell-local",
    "inline": ["ovftool ../builds/packer-{{user `name`}}-vmware/{{ user `name` }}-vmware.vmx ../builds/packer-{{user `name`}}-vmware/{{ user `name` }}-vmware.ova "],
    "only": ["vmware-{{ user `name` }}"]
  }
```

**Comment by SwampDragons** [comment]
I see. Thanks for the clarification.

**Comment by SwampDragons** [comment]
Turns out this and #7165 are the same issue; I'm going to close this one so that we can track them together.
