### ISSUE TITLE
Aliyun builder option image_force_delete does NOT work

### ISSUE THREAD

**Issue by willmao** [hashicorp/packer#6654]
The `image_force_delete` option does not work since the non-official ecs client sdk does not support force delete option...

packer version: 1.12.5

```
func (client *Client) DeleteImage(regionId common.Region, imageId string) error {
	args := DeleteImageArgs{
		RegionId: regionId,
		ImageId:  imageId,
	}

	response := &DeleteImageResponse{}
	return client.Invoke("DeleteImage", &args, &response)
}
```
https://github.com/denverdino/aliyungo/blob/cc006f6d7d6afc2487454f6730dcbdf31f873a56/ecs/images.go#L172

**Comment by willmao** [comment]
@zhuzhih2017

**Comment by willmao** [comment]
If the aliyun packer builder is officially supported by aliyun team, i think use the aliyun-go sdk is a better choice

**Comment by freddong** [comment]
I can force delete the images using by running instance normally, by executing "packer build -force alicloud.json" with https://github.com/alibaba/packer-provider.

**Comment by chhaj5236** [comment]
SDK has been updated. I'll close this issue.
