### ISSUE TITLE
is there any equivalent of the keep_registered option (used for virtual-box builder) for hyper-v builder ?

### ISSUE THREAD

**Issue by medsafa** [hashicorp/packer#6658]
_Please read these instructions before submitting_

**DELETE THIS TEMPLATE BEFORE SUBMITTING**

_Only use Github issues to report bugs or feature requests, see
https://www.packer.io/community.html_

For example, _Timeouts waiting for SSH/WinRM_ are generally not bugs within packer and are better addressed by the mailing list. Ask on the mailing list if you are unsure.

If you are planning to open a pull-request just open the pull-request instead of making an issue first.

FOR FEATURES:

Describe the feature you want and your use case _clearly_.

FOR BUGS:

Describe the problem and include the following information:

- Packer version from `packer version`
- Host platform
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a gist https://gist.github.com
- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your gist https://gist.github.com

**Comment by rickard-von-essen** [comment]
Please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._

**Comment by rickard-von-essen** [comment]
It doesn't seems so.
