### ISSUE TITLE
Post processor validator regression: "expected a map, got 'slice'"

### ISSUE THREAD

**Issue by ladar** [hashicorp/packer#6660]
I went to test out the new `split` function, and found out the hard way that `packer validate` is rejecting perfectly valid templates. (Or at least they were valid in the past, and seem to build just fine.)

Packer seems to be getting hung up on the nested arrays used by post processor configurations. Removing the nested array allows the template to validate, but doesn't actually work. Keeping the nested array will work during a `packer build`, but still fail to validate with an error that which says `expected a map, got 'slice'` ...

To illustrate, the following sample will fail validation, but build just fine:
```json 
"post-processors": [
      [
              {
                "type": "vagrant",
                "compression_level": 9,
                "vagrantfile_template": "tpl/{{split build_name \"-\" 1}}.rb",
                "output": "output/{{build_name}}-{{user `box_version`}}.box",
                "include": [
                  "tpl/generic/info.json"
                ]
            },
            {
                "type": "vagrant-cloud",
                "box_tag": "generic/{{split build_name \"-\" 1}}",
                "version": "{{user `box_version`}}",
                "version_description": "A build environment for use in cross platform development."
            }
        ]
      ]
```
  
While the following (note the only different is a set of brackets) will validate, but fails with the error `Post-processor failed: Unknown artifact type, requires box from vagrant post-processor: mitchellh.vmware` during post-processing:

```json
  "post-processors": [
              {
                "type": "vagrant",
                "compression_level": 9,
                "vagrantfile_template": "tpl/{{split build_name \"-\" 1}}.rb",
                "output": "output/{{build_name}}-{{user `box_version`}}.box",
                "include": [
                  "tpl/generic/info.json"
                ]
            },
            {
                "type": "vagrant-cloud",
                "box_tag": "generic/{{split build_name \"-\" 1}}",
                "version": "{{user `box_version`}}",
                "version_description": "A build environment for use in cross platform development."
            }
        ]
```
  
If your going to write a unit test based on this, might I suggest it include multiple post processor pipelines, like so:

```json
  "post-processors": [
      [
              {
                "type": "vagrant",
                "compression_level": 9,
                "vagrantfile_template": "tpl/{{split build_name \"-\" 1}}.rb",
                "output": "output/{{build_name}}-{{user `box_version`}}.box",
                "include": [
                  "tpl/generic/info.json"
                ]
            },
            {
                "type": "vagrant-cloud",
                "box_tag": "generic/{{split build_name \"-\" 1}}",
                "version": "{{user `box_version`}}",
                "version_description": "A build environment for use in cross platform development."
            }
        ],
        [
            {
                "type": "artifice",
                "keep_input_artifact": true,
                "files": [
                    "output/{{build_name}}-{{user `box_version`}}.box"
                ]
            },
            {
                "type": "checksum",
                "checksum_types": [
                    "sha256"
                ],
                "keep_input_artifact": true,
                "output": "output/{{build_name}}-{{user `box_version`}}.box.sha256"
            }
        ]
      ]
```

The obligatory data follows.

- Packer version from `packer version`
packer version v1.2.6-dev 819bda50d5050c015077089f01feee29b73341df
  
- Host platform
Linux
  
- Debug log output from `PACKER_LOG=1 packer build template.json`.
```bash
[ladar@darla robox]$ PACKER_LOG=1
[ladar@darla robox]$ packer validate generic-vmware.json
Error checking against fixers: 2 error(s) decoding:

* 'post-processors[0]' expected a map, got 'slice'
* 'post-processors[1]' expected a map, got 'slice'
```
  
- The example post processor from the vagrant cloud plugin documentation triggers this issue.
```json
"post-processors": [
    [
      {
        "type": "vagrant",
        "include": ["image.iso"],
        "vagrantfile_template": "vagrantfile.tpl",
        "output": "proxycore_{{.Provider}}.box"
      },
      {
        "type": "vagrant-cloud",
        "box_tag": "hashicorp/precise64",
        "access_token": "{{user `cloud_token`}}",
        "version": "{{user `version`}}"
      }
    ]
  ]
```

**Comment by SwampDragons** [comment]
Looks like this was introduced by https://github.com/hashicorp/packer/pull/6423

@mwhooker do you have the bandwidth for this or should I just revert that pull for now?

**Comment by mwhooker** [comment]
This is a buggy fixer (of course added by me in #5511). If you run `packer fix` over the above json, you get the same error. I believe the issue is in `fix/fixer_docker_email.go`.

It looks like it's expecting the PPs to be a `[]map[string]interface{}` but really it should be an interface and do some smart recursive descent into it. It looks like `"fix/fixer_pp_manifest_filename.go"` does it correctly. We should try to turn that into a walk function

**Comment by ladar** [comment]
@mwhooker let me know if you want me to retest...

**Comment by ladar** [comment]
@mwhooker I checked out the pull request and found a minor bug, which I believe is new, at least in comparison to the way 1.2.4 behaved. See https://github.com/hashicorp/packer/pull/6674#issuecomment-418901468
