### ISSUE TITLE
[Feature] Add a `debug` flag to auto-continue

### ISSUE THREAD

**Issue by glasnt** [hashicorp/packer#6662]
Only when running in `-debug` mode are configurations made to allow for SSH access (in my case using `amazon-ebs`, displaying IP information in the packer output and configuring a local ec2_amazon-ebs.pem key for SSHing)

However, with this feature you have to `Press enter to continue` for every single step. Using `-debug` in conjunction with `-on-error=ask`, I would like to be able to: 
 * have packer run until it gets an error
 * once an error is displayed, pause 
 * optionally helpful, have the connection details repeated (so I don't have to search the backscroll for the `Public IP` data)
 * allow me to then inspect the machine using the SSH details
 * wait for me to select an option (`[c]ontinue`, `[r]etry`, etc)

For backwards compatibility it make sense to have this as an option of `-debug` and not the default functionality, but I can't think of a good thing to name this feature, since we'd be effectively splitting the current debug functionality.

**Comment by rickard-von-essen** [comment]
I think this duplicates #5107. @glasnt do you agree?

**Comment by glasnt** [comment]
Assuming this not just prints the connection info, but actually creates the ability to connect. Given backwards compatibly, the functionality of these command should be explicitly documented, given their names assume a very different venn diagram :)

Closing if my assumption is correct.
