### ISSUE TITLE
Packer silently deletes your source_ami if you use the same name for ami_name

### ISSUE THREAD

**Issue by phpguru** [hashicorp/packer#6663]
~~~
"builders": [
    {
      "type": "amazon-ebs",
      "region": "us-west-2",
      "security_group_id": "",
      "source_ami": "ami-12345678",
      "instance_type": "t2.small",
      "ssh_username": "ec2user",
      "ami_name": "name-of-ami-here"
    }
  ],
~~~

If you accidentally put the name of your source AMI into "ami_name" then Packer will delete/overwrite your source AMI. In other words, if you have no other errors in your script, packer will generate a new AMI and silently overwrite ami-12345678 with a new ami including all your scripts, and name it "name-of-ami-here". 

If you've built a lot of packer templates using a specific AMI as a source, they've all become obsolete, and you have to now rebuild your source_ami.

Packer should throw an error before doing any compiling and warn about this.

**Comment by rickard-von-essen** [comment]
You need to use `--force` otherwise it will not overwrite the `source_ami`.

**Comment by rickard-von-essen** [comment]
What do you mean by:

> Packer should throw an error before doing any compiling and warn about this.

**Comment by phpguru** [comment]
I made two critical mistakes. One is misunderstanding "ami_name" as being the "source_ami" name instead of the "output_ami_name". The second was running build with --force. 

I made the assumption that --force would overwrite build targets, if they exist. I hadn't considered that it might also overwrite source targets. 

This is actually not a bug, packer did exactly what I told it to.
