### ISSUE TITLE
Can I use template data in provisioners?

### ISSUE THREAD

**Issue by hubertgrzeskowiak** [hashicorp/packer#6665]
I am trying to use the AWS builder's region data in a shell provisioner. I tried using `{{ .BuilderRegion }}` like this:

```
    ...
    {
      "type": "shell",
      "inline": [
        "echo '{{ .BuilderRegion }}'"
      ]
    },
    ...
```
but this only yields `<no value>`.

Is it possible at all to use builder template data in provisioners?

**Comment by SwampDragons** [comment]
I'm not sure where you're getting `BuilderRegion` but I don't think that's a valid template function _anywhere_.

Most builder template data isn't directly accessible to provisioners this way, but you can work around it in your case by using user variables to set the region. For example: 

```
{
 "variables": {
        "region": "us-east-2",
    },
    "builders": [
        {
            "region": "{{ user `region` }}",
            ...
        }
    ],
    "provisioners": [
        {
          "type": "shell",
          "environment_vars": ["REGION={{ user `region` }}"],
          "inline": ["echo $REGION}"]
        }
    ]
}
```

For future reference, github is not the right place for general questions or documentation clarifications; we prefer you save issues for bugs or feature requests, and send general questions to our [mailing list](https://groups.google.com/forum/#!forum/packer-tool)

**Comment by hubertgrzeskowiak** [comment]
Apologies for the late reply, @SwampDragons.

The template data `BuildRegion` is coming from the AWS builder and documented here: https://www.packer.io/docs/builders/amazon-ebs.html#build-template-data

It works when used within the builder itself, but not within the provisioners.

**Comment by SwampDragons** [comment]
Right; the variables listed there are only available to the builder. This is the expected behavior. I'll see if I can update the docs to clarify this.
