### ISSUE TITLE
Add a Progress indicator for upload provisioners

### ISSUE THREAD

**Issue by kemitix** [hashicorp/packer#6671]
When using a `file` provisioner to upload a large file to an remote destination (`amazon-ebs` in my case) there is no feedback to indicate that anything is happening.

I would like to see some form of indicator to show that the upload is progressing. e.g. a bar, or text with rate and or estimated time remaining.

**Comment by SwampDragons** [comment]
This should be solved by https://github.com/hashicorp/packer/pull/5851, which will be out with the next release.
