### ISSUE TITLE
How to skip the installing updates part in the windows installation ?

### ISSUE THREAD

**Issue by AymanRbati** [hashicorp/packer#6672]
How do i skip the installing updates part in the windows installation 
![image](https://user-images.githubusercontent.com/21956791/45115565-1ac9e200-b148-11e8-8d3b-094fa2006ed8.png)

**Comment by SwampDragons** [comment]
Hi @AymanRbati thanks for reaching out -- this is a question, not a feature request or a bug, so it belongs on our mailing list, https://groups.google.com/d/forum/packer-tool

That way, you're more likely to come across other Packer users who have solved this same issue, or found ways to work around it.
