### ISSUE TITLE
Minor QEMU docs issue

### ISSUE THREAD

**Issue by ladar** [hashicorp/packer#6677]
With:

https://www.packer.io/docs/builders/qemu.html

The `ssh_host_port_min and ssh_host_port_max (number)` variables need updating. The former  should have "(number)" after it, while the latter should be hyperlink.

This has to be the most insignificant issue possible, and I'd make the pull request, but I'm running late right now. Assign it to me, and I'll get to it later.

**Comment by SwampDragons** [comment]
Assigned! thanks for the heads-up

**Comment by rickard-von-essen** [comment]
I think this follows the standard we have. We only write the type once, after both options. Only the first one bocomes an anchor, that is a "problem" in the templating engine we use.

**Comment by ladar** [comment]
Would links in the form of:

```
[ssh_host_port_max](https://www.packer.io/docs/provisioners/file.html) 
``` 

I tried to test it out, but couldn't get the docker container to run properly. 

If not, then I guess the best option is to simply close.

**Comment by ladar** [comment]
For my example above, the correct syntax would be:

```
[ssh_host_port_max](https://www.packer.io/docs/builders/qemu.html#ssh_host_port_max) 
```

Also, the docker issue is likely specific to me. I'm on an older version of docker, and it didn't like overlaying volumes. 

If that mechanism does work, then I suspect there are a lot of places that will need updating.

**Comment by SwampDragons** [comment]
I think I'm going to just keep this as-is. I don't think the current way is any more difficult to read than the suggested way.
