### ISSUE TITLE
Feature Request: Local Shell Provisioner: Detect OS / Optionally execute or not

### ISSUE THREAD

**Issue by donbecker** [hashicorp/packer#6678]
I'm running Packer builds on AWS to create AMIs from a Jenkins Server, the OS is CentOS7. 

I develop primarily on a Window Laptop, and would like to specify a Local Shell Provisioner step to run, but only when the OS is Linux. To put it another way, I don't want the Local Shell Provisioner step to run on Windows. 

There might be a way to do this using WSL but I'd like to prevent execution without requiring WSL to be installed. 

A code suggestion would be to support something like: 

```
      {
        "type": "shell-local", 
        "inline": ["echo 'hello packer'"]
        "runon": "linux"
      } 
```
...where the "runon" argument would support "linux" "windows" or "any" (the current situation).

**Comment by SwampDragons** [comment]
This seems reasonable to me, and is probably fairly straightforward to implement.

**Comment by jvasallo** [comment]
I might take a crack at this, my idea is to implement the above as:
`"only_on": ["linux", "darwin"]`

That way you can specify a list where this can run to prevent duplication. Some pseudocode I am working on:
```
        only_on := []string{"darwin", "linux"}
        //only_on := []string{"windows"}
        //only_on := []string{}

	// if list is not empty, and runtime OS in list, run the command.
	if (len(only_on) > 0) && (contains(only_on,runtime.GOOS)) {
	    fmt.Printf("Array was not empty, and runtime in list of allowed os. Running command\n")
        } 
       // if list is not empty, and runtime OS not in list, dont run command, insert log?
       else if (len(only_on) > 0) && (!contains(only_on, runtime.GOOS)) {
	    fmt.Printf("Array was not empty, however, runtime is not in list of allowed os. Skipping command\n")
	} 
        // else the list was empty and not provided, execute as normal.
        else {
	  fmt.Printf("nothing specified. running command.\n")
	}
```
