### ISSUE TITLE
failed to install from source

### ISSUE THREAD

**Issue by zqfan** [hashicorp/packer#6680]
$ go get github.com/hashicorp/packer
$ cd $GOPATH/src/github.com/hashichorp/packer
$ make dev
package golang.org/x/tools/cmd/goimports: unrecognized import path "golang.org/x/tools/cmd/goimports" (https fetch: Get https://golang.org/x/tools/cmd/goimports?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
Makefile:48: recipe for target 'deps' failed
make: *** [deps] Error 1

**Comment by rickard-von-essen** [comment]
This looks like a network issue. Is it still happening?

**Comment by zqfan** [comment]
@rickard-von-essen Yes, it turns out because golang.org is blocked. To fix this issue, I have to run `go get github.com/golang/tools` then copy these code to golang.org/x/
