### ISSUE TITLE
Timestamps in packer output

### ISSUE THREAD

**Issue by BrunoCarrier** [hashicorp/packer#6682]
Could you make it an optional feature of packer builds that timestamps for each line of output be possible through a template parameter?

**Comment by SwampDragons** [comment]
This seems like a nice idea and probably not too difficult to implement.

**Comment by sharmaanshul2102** [comment]
@SwampDragons any pointers on how to implement it?

**Comment by SwampDragons** [comment]
Read through packer/ui.go and packer/rpc/ui.go

**Comment by SwampDragons** [comment]
Closed in #6784
