### ISSUE TITLE
Feature request: Amazon clean up non-encrypted snapshot

### ISSUE THREAD

**Issue by allyunion** [hashicorp/packer#6690]
It would be nice when creating encrypted AMIs that packer cleans up the not encrypted snap volume after the encrypted snap volume is complete

**Comment by SwampDragons** [comment]
Hmm. That should be the default behavior. Do you have an example config that reproduces this?

**Comment by natefox** [comment]
Make sure to have `encrypt_boot: true`. I had this issue when encrypting with `ami_block_device_mappings` -> `encrypted:true` but without `encrypt_boot: true`

**Comment by azr** [comment]
#6787 will do that cleanup !

**Comment by SwampDragons** [comment]
Changing the milestone to v1.4.0 since the solution will contain some backwards incompatibility for edge cases.

**Comment by rickard-von-essen** [comment]
@azr is this closed by #6787?

**Comment by azr** [comment]
@rickard-von-essen Yes thanks for the ping 🙂
