### ISSUE TITLE
amazon chroot builder doesn't work with new EC2 instance types

### ISSUE THREAD

**Issue by tjbaker** [hashicorp/packer#6710]
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/nvme-ebs-volumes.html

```
With the following instances, EBS volumes are exposed as NVMe block devices: C5, C5d, i3.metal, M5, M5d, R5, R5d, T3, and z1d. The device names are /dev/nvme0n1, /dev/nvme1n1, and so on. The device names that you specify in a block device mapping are renamed using NVMe device names (/dev/nvme[0-26]n1).
```

The Packer chroot builder does not know about this change and fails.

```
amazon-chroot: Checking the root device on source AMI...
amazon-chroot: Error finding available device: device prefix could not be detected
```

https://github.com/hashicorp/packer/blob/78c0b7bd9c1c2464c407fadbed3da4e94e627796/builder/amazon/chroot/device.go#L42-L45

**Comment by tjbaker** [comment]
See https://github.com/hashicorp/packer/pull/6711

**Comment by tjbaker** [comment]
Please please please get this into the next release!

**Comment by SwampDragons** [comment]
To provide more context on this issue, see #5848

We absolutely do need to get around to making this "just work" but until then, folks can use the workaround described there.

**Comment by diogonicoleti** [comment]
@SwampDragons there are some news about this problem?

**Comment by SwampDragons** [comment]
Nope. It's not a trivial change, and since it has a workaround we haven't prioritized it.

**Comment by grayaii** [comment]
The workaround is only for amazon-chroot builder, not amazon-ebs, right?
Is there any workaround for amazon-ebs builder?

Maybe have an inline provisioner that does something like:
"sudo echo 'UUID=\"8df129f0-10e5-42be-971d-5acb92c0e9f8\"  /var/foo ext4    defaults        0   0' | sudo tee -a /etc/fstab",

**Comment by serialp** [comment]
Hello,
@SwampDragons, what is the status of this issue today ?
is the workaround provided 2 years ago is till up-to-date ?
the binary file provided [here](https://github.com/hashicorp/packer/issues/5848#issuecomment-391411130) looks compatible on linux only. Do you have any MacOS compatible binary ?

Thanks a lot for your feedback!
