### ISSUE TITLE
Security and Network Queries on Packer

### ISSUE THREAD

**Issue by avnsiva** [hashicorp/packer#6716]
I am using packer and terraform for sometime. Its been a great set of tools for automating a lot of things.
I am having the following queries on using Packer:

1. Packer creates a resource group and VM with public IP within Azure. But the VM is not secured by any NSG/ASG's. Though the builder VM is present only for a few mins, still the security is compromised in this time.
Is it possible to configure Packer to use an existing Resource Group and use the private IP of the builder VM? The assumption is that packer build is executed from another VM within the same Resource Group and access to the files can be guaranteed.
Or can Packer call a terraform template to create the builder resource group and VM? We can then configure terraform to put in the necessary rules to prevent security issues.

2. Can we use our custom image for creating the builder VM? The reason is that some 10-15 GB's of binaries are not changing with each build. Repeatedly transferring them is consuming un necessary time.  Also hardening steps are executed repeatedly on each build.

**Comment by rickard-von-essen** [comment]
Please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._

**Comment by boumenot** [comment]
Packer can be configured to use a private IP address.  There is currently no support for configuring NSGs.  Packer supports custom images.  Please review the [docs](https://www.packer.io/docs/builders/azure.html) and the [examples](https://github.com/hashicorp/packer/tree/master/examples/azure) to learn how.
