### ISSUE TITLE
Package name duplicate in Archlinux 

### ISSUE THREAD

**Issue by niksad** [hashicorp/packer#6718]
Hi there,
there is a name duplicate in arch Community package (packer) and 
https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=packer 
i also open the topic in arch forum 
https://bbs.archlinux.org/viewtopic.php?id=240459

**Comment by rickard-von-essen** [comment]
So it seems like (HashiCorp) packer is in the main repository and then there is another package in AUR (the user managed repository).

Maybe we should add a note in the installation docs, similar to the note we have for (RH)EL based distributions.
