### ISSUE TITLE
Amazon Builders on t3 instances have unlimited credits enabled by default

### ISSUE THREAD

**Issue by ricardclau** [hashicorp/packer#6721]
This is related to https://github.com/hashicorp/packer/issues/6260 and it happens with all packer versions

AWS recently launched t3 instances which have better network performance (and are slightly cheaper) than the previous t2 family

However, they come with a hidden surprise, unlimited credits seems to be on by default

I guess it should be a relatively easy fix. Code in the mentioned issue should be slightly modified so that unlimited credits is explicitly set to false by default and only set to true if the packer user decides to

If nobody wants to pick this up, I may have some time to work on it!

**Comment by rickard-von-essen** [comment]
_Unlimited mode_ is the AWS default, we should retain the AWS defaults.

See https://aws.amazon.com/ec2/instance-types/t3/

**Comment by ricardclau** [comment]
Yeah, I see your point respecting AWS defaults. 

Maybe should be modified https://www.packer.io/docs/builders/amazon-ebs.html#enable_t2_unlimited as they only cover t2 family

**Comment by rickard-von-essen** [comment]
We need to rework this functionality a bit. The option doesn't reflect what it actually does.. 😢

**Comment by rickard-von-essen** [comment]
This was introduced in #6265

**Comment by eedwards-sk** [comment]
> Error: T2 Unlimited enabled with a non-T2 Instance Type: t3.micro

from a usability standpoint, makes zero sense that this is configurable for t2 and not t3. It's the same concept.

from an api standpoint, any PRs to make this consistent between the two would be ideal...

in terraform, it's configured with `credit_specification` and no mention of t2 or t3 at all

**Comment by jackluo923** [comment]
Bump. Any progress on this? Any chance this could also be implemented for t4g instances?
