### ISSUE TITLE
Packer ignores vmx_data passed on builders section

### ISSUE THREAD

**Issue by pkaramol** [hashicorp/packer#6722]
- Packer version from `packer version`: `1.3.0`
- Host platform: Local: `Ubuntu 16.04.05` Remote: `ESXI 6.0`
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  [Debug log output](https://gist.github.com/pkaramol/05244e53630ac1570aa3e658a14a9c09)

I am trying to build on a remote `esxi` server using the `remote_*` options of the `vmx` builder.

Although I am explicitly specifying the `vnc` port to be used, `packer` seems to be trying a lot of different options wasting a lot of time on this (as can be seen at the end of the debug gist)
  
Here is my `builders` section

```
    "builders": [
       {
        "type": "vmware-iso",
        "format": "ova",
        "vmx_data": {
          "memsize": "8192",
          "numvcpus": "4",
          "ethernet0.networkName": "someVLANid",
          "remotedisplay.vnc.password": "somepass",
          "remotedisplay.vnc.port": "5988"
       },
```

**Comment by rickard-von-essen** [comment]
See https://www.packer.io/docs/builders/vmware-iso.html#vnc_port_min
