### ISSUE TITLE
Packer crash report

### ISSUE THREAD

**Issue by yruss972** [hashicorp/packer#6723]
- Packer version: 1.3.1
- Host platform: Docker  
 
Here is an excerpt from the end of the crash report.
I prefer not to upload the entire report due to the possibly sensitive contents:

2018/09/17 11:04:19 [INFO] Packer version: 1.3.1
2018/09/17 11:04:19 Packer Target OS/Arch: linux amd64
2018/09/17 11:04:19 Built with Go Version: go1.11
2018/09/17 11:04:19 Detected home directory from env var: /root
2018/09/17 11:04:19 Using internal plugin for oracle-oci
2018/09/17 11:04:19 Using internal plugin for amazon-chroot
2018/09/17 11:04:19 Using internal plugin for file
2018/09/17 11:04:19 Using internal plugin for googlecompute
2018/09/17 11:04:19 Using internal plugin for openstack
2018/09/17 11:04:19 Using internal plugin for amazon-instance
2018/09/17 11:04:19 Using internal plugin for vmware-vmx
2018/09/17 11:04:19 Using internal plugin for amazon-ebs
2018/09/17 11:04:19 Using internal plugin for amazon-ebssurrogate
2018/09/17 11:04:19 Using internal plugin for parallels-pvm
2018/09/17 11:04:19 Using internal plugin for scaleway
2018/09/17 11:04:19 Using internal plugin for virtualbox-iso
2018/09/17 11:04:19 Using internal plugin for lxd
2018/09/17 11:04:19 Using internal plugin for null
2018/09/17 11:04:19 Using internal plugin for profitbricks
2018/09/17 11:04:19 Using internal plugin for triton
2018/09/17 11:04:19 Using internal plugin for amazon-ebsvolume
2018/09/17 11:04:19 Using internal plugin for azure-arm
2018/09/17 11:04:19 Using internal plugin for docker
2018/09/17 11:04:19 Using internal plugin for ncloud
2018/09/17 11:04:19 Using internal plugin for alicloud-ecs
2018/09/17 11:04:19 Using internal plugin for cloudstack
2018/09/17 11:04:19 Using internal plugin for oracle-classic
2018/09/17 11:04:19 Using internal plugin for qemu
2018/09/17 11:04:19 Using internal plugin for hyperv-iso
2018/09/17 11:04:19 Using internal plugin for hyperv-vmcx
2018/09/17 11:04:19 Using internal plugin for parallels-iso
2018/09/17 11:04:19 Using internal plugin for vmware-iso
2018/09/17 11:04:19 Using internal plugin for digitalocean
2018/09/17 11:04:19 Using internal plugin for lxc
2018/09/17 11:04:19 Using internal plugin for oneandone
2018/09/17 11:04:19 Using internal plugin for virtualbox-ovf
2018/09/17 11:04:19 Using internal plugin for file
2018/09/17 11:04:19 Using internal plugin for salt-masterless
2018/09/17 11:04:19 Using internal plugin for shell
2018/09/17 11:04:19 Using internal plugin for windows-shell
2018/09/17 11:04:19 Using internal plugin for ansible-local
2018/09/17 11:04:19 Using internal plugin for converge
2018/09/17 11:04:19 Using internal plugin for chef-solo
2018/09/17 11:04:19 Using internal plugin for powershell
2018/09/17 11:04:19 Using internal plugin for puppet-server
2018/09/17 11:04:19 Using internal plugin for windows-restart
2018/09/17 11:04:19 Using internal plugin for ansible
2018/09/17 11:04:19 Using internal plugin for puppet-masterless
2018/09/17 11:04:19 Using internal plugin for shell-local
2018/09/17 11:04:19 Using internal plugin for chef-client
2018/09/17 11:04:19 Using internal plugin for alicloud-import
2018/09/17 11:04:19 Using internal plugin for checksum
2018/09/17 11:04:19 Using internal plugin for docker-push
2018/09/17 11:04:19 Using internal plugin for docker-save
2018/09/17 11:04:19 Using internal plugin for vagrant-cloud
2018/09/17 11:04:19 Using internal plugin for artifice
2018/09/17 11:04:19 Using internal plugin for docker-import
2018/09/17 11:04:19 Using internal plugin for docker-tag
2018/09/17 11:04:19 Using internal plugin for shell-local
2018/09/17 11:04:19 Using internal plugin for vsphere
2018/09/17 11:04:19 Using internal plugin for vsphere-template
2018/09/17 11:04:19 Using internal plugin for compress
2018/09/17 11:04:19 Using internal plugin for amazon-import
2018/09/17 11:04:19 Using internal plugin for googlecompute-export
2018/09/17 11:04:19 Using internal plugin for googlecompute-import
2018/09/17 11:04:19 Using internal plugin for manifest
2018/09/17 11:04:19 Using internal plugin for vagrant
2018/09/17 11:04:19 Detected home directory from env var: /root
2018/09/17 11:04:19 Attempting to open config file: /root/.packerconfig
2018/09/17 11:04:19 [WARN] Config file doesn't exist: /root/.packerconfig
2018/09/17 11:04:19 Packer config: &{DisableCheckpoint:false DisableCheckpointSignature:false PluginMinPort:10000 PluginMaxPort:25000 Builders:map[parallels-iso:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-parallels-iso openstack:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-openstack vmware-vmx:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-vmware-vmx triton:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-triton ncloud:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-ncloud oracle-classic:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-oracle-classic qemu:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-qemu hyperv-iso:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-hyperv-iso null:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-null cloudstack:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-cloudstack hyperv-vmcx:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-hyperv-vmcx oneandone:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-oneandone googlecompute:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-googlecompute profitbricks:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-profitbricks digitalocean:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-digitalocean lxc:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-lxc amazon-chroot:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-amazon-chroot amazon-ebsvolume:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-amazon-ebsvolume azure-arm:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-azure-arm oracle-oci:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-oracle-oci alicloud-ecs:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-alicloud-ecs amazon-ebssurrogate:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-amazon-ebssurrogate parallels-pvm:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-parallels-pvm scaleway:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-scaleway vmware-iso:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-vmware-iso amazon-ebs:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-amazon-ebs lxd:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-lxd docker:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-docker virtualbox-ovf:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-virtualbox-ovf file:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-file amazon-instance:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-amazon-instance virtualbox-iso:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-virtualbox-iso] PostProcessors:map[vsphere:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-vsphere compress:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-compress googlecompute-export:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-googlecompute-export checksum:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-checksum docker-save:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-docker-save vagrant-cloud:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-vagrant-cloud alicloud-import:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-alicloud-import docker-tag:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-docker-tag shell-local:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-shell-local artifice:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-artifice docker-import:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-docker-import manifest:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-manifest googlecompute-import:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-googlecompute-import vagrant:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-vagrant docker-push:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-docker-push vsphere-template:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-vsphere-template amazon-import:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-amazon-import] Provisioners:map[windows-restart:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-windows-restart ansible:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-ansible chef-solo:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-chef-solo puppet-server:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-puppet-server shell-local:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-shell-local salt-masterless:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-salt-masterless ansible-local:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-ansible-local powershell:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-powershell puppet-masterless:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-puppet-masterless chef-client:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-chef-client file:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-file windows-shell:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-windows-shell shell:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-shell converge:/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-converge]}
2018/09/17 11:04:19 Detected home directory from env var: /root
2018/09/17 11:04:19 Setting cache directory: /packer/packer_cache
2018/09/17 11:04:19 Detected home directory from env var: /root
2018/09/17 11:04:19 Loading builder: amazon-ebs
2018/09/17 11:04:19 Plugin could not be found. Checking same directory as executable.
2018/09/17 11:04:19 Current exe path: /bin/packer
2018/09/17 11:04:19 Creating plugin client for path: /bin/packer
2018/09/17 11:04:19 Starting plugin: /bin/packer []string{"/bin/packer", "plugin", "packer-builder-amazon-ebs"}
...
2018/09/17 11:09:34 ui: [1;32m==> amazon-ebs: Stopping the source instance...[0m
2018/09/17 11:09:34 ui: [0;32m    amazon-ebs: Stopping instance, attempt 1[0m
2018/09/17 11:09:35 ui: [1;32m==> amazon-ebs: Waiting for the instance to stop...[0m
2018/09/17 11:09:35 packer: 2018/09/17 11:09:35 DEPRECATION WARNING: env var AWS_TIMEOUT_SECONDS is deprecated in favor of AWS_MAX_ATTEMPTS. If you have not explicitly set AWS_POLL_DELAY_SECONDS, we are defaulting to a poll delay of 2 seconds, regardless of the AWS waiter's default.
2018/09/17 11:09:35 ui: [1;32m==> amazon-ebs: Terminating the source AWS instance...[0m
2018/09/17 11:09:35 packer: 2018/09/17 11:09:35 DEPRECATION WARNING: env var AWS_TIMEOUT_SECONDS is deprecated in favor of AWS_MAX_ATTEMPTS. If you have not explicitly set AWS_POLL_DELAY_SECONDS, we are defaulting to a poll delay of 2 seconds, regardless of the AWS waiter's default.
2018/09/17 11:09:35 ui: [1;32m==> amazon-ebs: Cleaning up any extra volumes...[0m
2018/09/17 11:09:35 ui: [1;32m==> amazon-ebs: Deleting temporary security group...[0m
2018/09/17 11:09:36 packer: 2018/09/17 11:09:36 Error deleting security group: DependencyViolation: resource sg-033424566ac2d7eb3 has a dependent object
2018/09/17 11:09:36 packer: 	status code: 400, request id: a1b9509b-eb03-4539-94a2-1211b39e931a
2018/09/17 11:09:42 packer: 2018/09/17 11:09:42 Error deleting security group: DependencyViolation: resource sg-033424566ac2d7eb3 has a dependent object
2018/09/17 11:09:42 packer: 	status code: 400, request id: de9c04ad-68a8-46f3-a4bc-a6621b81f9f3
2018/09/17 11:09:48 packer: 2018/09/17 11:09:48 Error deleting security group: DependencyViolation: resource sg-033424566ac2d7eb3 has a dependent object
2018/09/17 11:09:48 packer: 	status code: 400, request id: 6fe6a8e7-5a9b-4dc5-8018-faefd91a3ece
2018/09/17 11:09:54 packer: 2018/09/17 11:09:54 Error deleting security group: DependencyViolation: resource sg-033424566ac2d7eb3 has a dependent object
2018/09/17 11:09:54 packer: 	status code: 400, request id: 30582b64-ef1b-4903-8127-0ce1a5c031ea
2018/09/17 11:10:00 packer: 2018/09/17 11:10:00 Error deleting security group: DependencyViolation: resource sg-033424566ac2d7eb3 has a dependent object
2018/09/17 11:10:00 packer: 	status code: 400, request id: 07e3e13d-798e-4712-93ef-9ff6d5258933
2018/09/17 11:10:05 ui error: [1;31m==> amazon-ebs: Error cleaning up security group. Please delete the group manually: sg-033424566ac2d7eb3[0m
2018/09/17 11:10:05 packer: panic: runtime error: integer divide by zero
2018/09/17 11:10:05 packer: 	panic: runtime error: integer divide by zero
2018/09/17 11:10:05 packer: 
2018/09/17 11:10:05 packer: goroutine 70 [running]:
2018/09/17 11:10:05 packer: github.com/hashicorp/packer/builder/amazon/common.applyEnvOverrides(0x256e95d, 0x16, 0x0, 0x0, 0x255b271, 0x10, 0x0, 0x0, 0x2563d6d, 0x13, ...)
2018/09/17 11:10:05 packer: 	/Users/azr/go/src/github.com/hashicorp/packer/builder/amazon/common/state.go:329 +0x4c9
2018/09/17 11:10:05 packer: github.com/hashicorp/packer/builder/amazon/common.getWaiterOptions(0x1eb0bc0, 0xc00000cae8, 0xc0005d93f0)
2018/09/17 11:10:05 packer: 	/Users/azr/go/src/github.com/hashicorp/packer/builder/amazon/common/state.go:271 +0x6f
2018/09/17 11:10:05 packer: github.com/hashicorp/packer/builder/amazon/common.WaitUntilInstanceTerminated(0x7f0bb571c088, 0xc000040080, 0xc0001841b0, 0xc00043b480, 0x13, 0xc0005d94c8, 0x0)
2018/09/17 11:10:05 packer: 	/Users/azr/go/src/github.com/hashicorp/packer/builder/amazon/common/state.go:65 +0x13d
2018/09/17 11:10:05 packer: github.com/hashicorp/packer/builder/amazon/common.(*StepRunSourceInstance).Cleanup(0xc000668000, 0x281a980, 0xc00032ab70)
2018/09/17 11:10:05 packer: 	/Users/azr/go/src/github.com/hashicorp/packer/builder/amazon/common/step_run_source_instance.go:306 +0x287
2018/09/17 11:10:05 packer: panic(0x202a520, 0x4101b60)
2018/09/17 11:10:05 packer: 	/usr/local/Cellar/go/1.11/libexec/src/runtime/panic.go:513 +0x1b9
2018/09/17 11:10:05 packer: github.com/hashicorp/packer/builder/amazon/common.applyEnvOverrides(0x256e95d, 0x16, 0x0, 0x0, 0x255b271, 0x10, 0x0, 0x0, 0x2563d6d, 0x13, ...)
2018/09/17 11:10:05 packer: 	/Users/azr/go/src/github.com/hashicorp/packer/builder/amazon/common/state.go:329 +0x4c9
2018/09/17 11:10:05 packer: github.com/hashicorp/packer/builder/amazon/common.getWaiterOptions(0xc000240840, 0x25a10b9, 0x23)
2018/09/17 11:10:05 packer: 	/Users/azr/go/src/github.com/hashicorp/packer/builder/amazon/common/state.go:271 +0x6f
2018/09/17 11:10:05 packer: github.com/hashicorp/packer/builder/amazon/common.(*StepStopEBSBackedInstance).Run(0xc00062e6b0, 0x281cb80, 0xc0001a3bc0, 0x281a980, 0xc00032ab70, 0x0)
2018/09/17 11:10:05 packer: 	/Users/azr/go/src/github.com/hashicorp/packer/builder/amazon/common/step_stop_ebs_instance.go:85 +0x1d1
2018/09/17 11:10:05 packer: github.com/hashicorp/packer/helper/multistep.(*BasicRunner).Run(0xc0001a3b80, 0x281a980, 0xc00032ab70)
2018/09/17 11:10:05 packer: 	/Users/azr/go/src/github.com/hashicorp/packer/helper/multistep/basic_runner.go:72 +0x222
2018/09/17 11:10:05 packer: github.com/hashicorp/packer/builder/amazon/ebs.(*Builder).Run(0xc0003fa000, 0x2822400, 0xc000240840, 0x280ff40, 0xc000481db0, 0x281cf40, 0xc000184198, 0x4bca9c, 0x1e1d9e0, 0x1e1d9e0, ...)
2018/09/17 11:10:05 packer: 	/Users/azr/go/src/github.com/hashicorp/packer/builder/amazon/ebs/builder.go:264 +0x146f
2018/09/17 11:10:05 packer: github.com/hashicorp/packer/packer/rpc.(*BuilderServer).Run(0xc000241960, 0x1, 0xc000040130, 0x0, 0x0)
2018/09/17 11:10:05 packer: 	/Users/azr/go/src/github.com/hashicorp/packer/packer/rpc/builder.go:94 +0x1cd
2018/09/17 11:10:05 packer: reflect.Value.call(0xc0003d4360, 0xc00000c7e8, 0x13, 0x25467a6, 0x4, 0xc0000a5f18, 0x3, 0x3, 0xc000180480, 0xc0002f7888, ...)
2018/09/17 11:10:05 packer: 	/usr/local/Cellar/go/1.11/libexec/src/reflect/value.go:447 +0x449
2018/09/17 11:10:05 packer: reflect.Value.Call(0xc0003d4360, 0xc00000c7e8, 0x13, 0xc0004c0f18, 0x3, 0x3, 0x1, 0x72c03e, 0xc0002af601)
2018/09/17 11:10:05 packer: 	/usr/local/Cellar/go/1.11/libexec/src/reflect/value.go:308 +0xa4
2018/09/17 11:10:05 packer: net/rpc.(*service).call(0xc0001a3200, 0xc000093770, 0xc0002af488, 0xc0002af490, 0xc000100e00, 0xc000241c40, 0x1e8d940, 0xc00004010c, 0x18a, 0x1e1d9e0, ...)
2018/09/17 11:10:05 packer: 	/usr/local/Cellar/go/1.11/libexec/src/net/rpc/server.go:384 +0x14e
2018/09/17 11:10:05 packer: created by net/rpc.(*Server).ServeCodec
2018/09/17 11:10:05 packer: 	/usr/local/Cellar/go/1.11/libexec/src/net/rpc/server.go:481 +0x47e
2018/09/17 11:10:05 [INFO] (telemetry) ending amazon-ebs
2018/09/17 11:10:05 ui error: [1;31mBuild 'amazon-ebs' errored: unexpected EOF[0m
2018/09/17 11:10:05 Builds completed. Waiting on interrupt barrier...
2018/09/17 11:10:05 machine readable: error-count []string{"1"}
2018/09/17 11:10:05 ui error: 
==> Some builds didn't complete successfully and had errors:
2018/09/17 11:10:05 machine readable: amazon-ebs,error []string{"unexpected EOF"}
2018/09/17 11:10:05 ui error: --> amazon-ebs: unexpected EOF
2018/09/17 11:10:05 ui: 
==> Builds finished but no artifacts were created.
2018/09/17 11:10:05 [INFO] (telemetry) Finalizing.
2018/09/17 11:10:05 /bin/packer: plugin process exited
2018/09/17 11:10:05 waiting for all plugin processes to complete...
2018/09/17 11:10:05 /bin/packer: plugin process exited
2018/09/17 11:10:05 /bin/packer: plugin process exited

**Comment by SwampDragons** [comment]
Thanks for opening this report -- I'm hoping this is fixed by https://github.com/hashicorp/packer/pull/6727

A linux build of that branch: 
[packer.zip](https://github.com/hashicorp/packer/files/2389721/packer.zip)

**Comment by azr** [comment]
Hello @yruss972, did Megan's new build fix this crash for you ? I will merge her PR if so.

**Comment by yruss972** [comment]
I will try to test it and luk.

**Comment by yruss972** [comment]
The binary with the fix seems to work

**Comment by azr** [comment]
Awesome, merging it then.
