### ISSUE TITLE
Packer unable to ssh into remote VM when building

### ISSUE THREAD

**Issue by pkaramol** [hashicorp/packer#6724]
- Packer version from `packer version`: `1.3.0`
- Host platform: Local: `Ubuntu 16.04.05` Remote: `ESXI 6.0`

I am trying to build on a remote `esxi` server using the `remote_*` options of the `vmware-iso` builder.

At some point in time, and although the `preseed.cfg` seems to be properly uploaded, the process halts and the packer debug logs keep repeating the following:

```
2018/09/17 15:28:03 packer: 2018/09/17 15:28:03 [DEBUG] Error getting SSH address: No interface on the VM has an IP address ready
2018/09/17 15:28:08 packer: 2018/09/17 15:28:08 [DEBUG] Opening new ssh session
2018/09/17 15:28:08 packer: 2018/09/17 15:28:08 [DEBUG] starting remote command: esxcli --formatter csv network vm list
2018/09/17 15:28:08 packer: 2018/09/17 15:28:08 [DEBUG] Opening new ssh session
2018/09/17 15:28:08 packer: 2018/09/17 15:28:08 [DEBUG] starting remote command: esxcli --formatter csv network vm port list -w 1985683
2018/09/17 15:28:08 packer: 2018/09/17 15:28:08 Connection refused when connecting to: 10.111.3.203
2018/09/17 15:28:08 packer: 2018/09/17 15:28:08 [DEBUG] Error getting SSH address: No interface on the VM has an IP address ready
```

The above address seems pingable:

```
$ ping 10.111.3.203
PING 10.111.3.203 (10.111.3.203) 56(84) bytes of data.
64 bytes from 10.111.3.203: icmp_seq=1 ttl=62 time=2.24 ms
64 bytes from 10.111.3.203: icmp_seq=2 ttl=62 time=2.30 ms
```

but port `22` seems closed

```
$ nc -zv 10.111.3.203 22
nc: connect to 10.111.3.203 port 22 (tcp) failed: Connection refused
```

Here is my [template](https://gist.github.com/pkaramol/520816d337279de9ab4fcc576a273f81).

**Comment by rickard-von-essen** [comment]
Please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._
