### ISSUE TITLE
Packer 1.3.1 not tagged on Docker Hub

### ISSUE THREAD

**Issue by repl-mathieu-fenniak** [hashicorp/packer#6725]
Packer 1.3.1 was released on September 14th, and but a matching tag for the hashicorp/packer docker image has not been pushed yet.  (https://hub.docker.com/r/hashicorp/packer/tags/)  There were updates around the same time to the full / latest / light tags, but, no 1.3.1 tag.  Would appreciate it if this could be pushed! 👍 

![screen shot 2018-09-17 at 7 07 45 am](https://user-images.githubusercontent.com/32574529/45624732-6897f180-ba48-11e8-9487-caeee2eade34.png)

**Comment by SwampDragons** [comment]
Done! Thanks for the note.

**Comment by repl-mathieu-fenniak** [comment]
Thank you!
