### ISSUE TITLE
Compare-VM : object not set to an instance of an object

### ISSUE THREAD

**Issue by clecoutre** [hashicorp/packer#6726]
Hello,

We have an issue running packer hyperv-vmcx "clone_from_vm_name" on a window 2012 R2 server.
Compare-VM failed with the error message => Compare-VM : object not set to an instance of an object

Here are the packer and windows versions : 

- Packer v1.3.0
- Windows 2012 R2

log file below : 

[packer-log352687207.log](https://github.com/hashicorp/packer/files/2388772/packer-log352687207.log)

json template below :

[HopexBuild-packer.txt](https://github.com/hashicorp/packer/files/2388805/HopexBuild-packer.txt)

Thank you.
Christophe

**Comment by SwampDragons** [comment]
Thanks for opening an issue -- Is this a regression from v 1.2.5?

**Comment by SwampDragons** [comment]
@DanHam Do you have time to take a look at this? I have a sneaking feeling it's related to https://github.com/hashicorp/packer/pull/6393

**Comment by clecoutre** [comment]
No, it's not a regression, I have tested with both v1.2.5 and 1.3.0, same issue.

It's the first time I use packer, first I made a test on my local computer (Windows 10) and it was working well, but then I tried on two different Hyper-V server (Windows 2012 R2), and the issue appeared.

**Comment by DanHam** [comment]
@SwampDragons 

If this *was* a regression caused by #6393 I would most likely have tried to take a look...

However, for the foreseeable future at least, I will be unable to contribute to Packer as unfortunately I no longer have the time.

Good luck with the bug hunting!

Dan

**Comment by clecoutre** [comment]
The script failed at the line 398 of the script hyperv.go :

$compatibilityReport = Hyper-V\Compare-VM -Path "E:\VM_Images\temp\packerhv708483974\Virtual Machines\9507495E-4E55-4856-9146-402940DBD8D5.XML" -VirtualMachinePath "E:\VM_Images\temp\packerhv708483974" -SmartPagingFilePath "E:\VM_Images\temp\packerhv708483974" -SnapshotFilePath "E:\VM_Images\temp\packerhv708483974" -VhdDestinationPath "E:\VM_Images\temp\packerhv708483974\Virtual Hard Disks" -GenerateNewId -Copy:$false

I tried to modify the command and set "-Copy:$true", and it works.
What is the reason to put -Copy:$false ?

Thanks.

**Comment by SwampDragons** [comment]
@DanHam understood, thanks for all you've done recently. Sorry for pinging you unnecessarily. 

@clecoutre hmm, not sure. I checked the commit history and it's always been that way; @taliesins may have some insights for us since he wrote it originally. And since in this case we are doing the check for a copy it would make sense to set it to true... at least that's what I think I'm getting from these docs: https://docs.microsoft.com/en-us/powershell/module/hyper-v/compare-vm?view=win10-ps

**Comment by pgrmega** [comment]
Hello,
You will find here a patch to fix this problem.
Is this possible to integrate the fix ?
[#6726-patch.zip](https://github.com/hashicorp/packer/files/2509368/6726-patch.zip)
Thanks.

**Comment by SwampDragons** [comment]
@pgrmega Thanks for writing this patch -- please submit it via a pull request that references this issue :)
