### ISSUE TITLE
Ability to add additional qemu-img create/convert arguments

### ISSUE THREAD

**Issue by numinit** [hashicorp/packer#6734]
Hey there,

We're building qemu images where preallocation of qcow2 data would really speed up our build. Right now, we have to inject a custom PATH into Packer with a wrapper script to obtain this desired effect, and would like to be able to pass an option (similar to `qemuargs`) that lets us control arguments passed to `qemu-img`. Maybe something like this:

```json
{
  "qemu_img_args": {
    "convert": [
      ["-o", "preallocation=full"]
    ]
  }
}
```

Thanks!

**Comment by SwampDragons** [comment]
Thanks for opening a ticket! The qemu builder is one of our community-supported ones, which means the best way to see this change is likely to implement it yourself and open a PR.  I agree this sounds like a nice feature to have.

**Comment by numinit** [comment]
OK, I might take an afternoon to implement this myself, then. Thanks!

**Comment by ciarancourtney** [comment]
Another use case is to [use _zstd_ compression](https://wiki.qemu.org/ChangeLog/5.1#Network) if using QEMU>=5.1
