### ISSUE TITLE
amazon-ebs: failed for successful resource state

### ISSUE THREAD

**Issue by kenanbiel** [hashicorp/packer#6737]
I'm trying to build an encrypted AMI from an unencrypted one by just adding these two options:
```
    "encrypt_boot": "true",
    "kms_key_id": "kms_key",
```
Here's the output log:
```
==> amazon-ebs: Waiting for AMI to become ready...
==> amazon-ebs: Creating Encrypted AMI Copy
==> amazon-ebs: Copying AMI: us-east-1(ami-XXXXXX)
==> amazon-ebs: Encrypting with KMS Key ID: kms_key
==> amazon-ebs: Waiting for AMI copy to become ready...
==> amazon-ebs: Error waiting for AMI Copy: ResourceNotReady: failed waiting for successful resource state
==> amazon-ebs: Deregistering the AMI because cancellation or error...
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Cleaning up any extra volumes...
==> amazon-ebs: No volumes to clean up, skipping
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: Error waiting for AMI Copy: ResourceNotReady: failed waiting for successful resource state

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Error waiting for AMI Copy: ResourceNotReady: failed waiting for successful resource state

==> Builds finished but no artifacts were created.
```

And via AWS console, it produces a failed AMI with reason: 
`State Reason: Copy image failed with an internal error`

I thought it was related to this: https://github.com/hashicorp/packer/issues/6526 and https://groups.google.com/forum/#!msg/packer-tool/evr5qwYuhlM/xkgAFWV2AgAJ but it's not related to wait attempts.

- Packer v1.3.1
- OS X 10.13.6

**Comment by rickard-von-essen** [comment]
Did you reach your snapshot limit or have alot of concurrent AMI coping running?

**Comment by kenanbiel** [comment]
Nope, only that current job. After it failed, i tried creating manually via AWS console by copying the AMI the ticking encrypt and it worked.

**Comment by kenanbiel** [comment]
`==> amazon-ebs: Encrypting with KMS Key ID: kms_key`

Found my error, apparently i'm using the alias, instead of the actual ARN.

**Comment by chakradharavarma** [comment]
m

**Comment by kenanbiel** [comment]
Hi @chakradharavarma, are you getting the same error message as i did? Can you paste here the packer logs you got?

**Comment by azr** [comment]
Hello there, if you are having the issue on packer 1.4.1, there's an open issue here: https://github.com/hashicorp/packer/issues/7673 I think it's the same issue :)

**Comment by chakradharavarma** [comment]
@kenanbiel Thank you, I was able to figure it out, It is due to not have access to use the key from I role.
The issue is solved now.
