### ISSUE TITLE
OpenStack: source_image_name and use_blockstorage_volume

### ISSUE THREAD

**Issue by shield-9** [hashicorp/packer#6740]
When I use `use_blockstorage_volume` of OpenStack builder with `source_image_name`, the following error is occurred from [here](https://github.com/hashicorp/packer/blob/71c515fda117fca874851315e7dd4e0dea624ec4/builder/openstack/step_create_volume.go#L48):
```
==> openstack: Error creating volume: Resource not found
```

But if I specified an source image with `source_image` option (UUID), it works.

**Comment by shield-9** [comment]
@SwampDragons I uploaded them to [this gist](https://gist.github.com/shield-9/51b6d99a4806b69efe11f9e7522a0aad).

**Comment by rickard-von-essen** [comment]
Here's a darwin build for the fix in #6751, I've not tested it at all, I just thrown it together but I believe it should fix the problem.
https://drive.google.com/open?id=1LtuaTpfmjr_oIDTkPZ2wuFjC22Bibjt3
