### ISSUE TITLE
Azure Builder: Packer should not delete OS Disk

### ISSUE THREAD

**Issue by vladfr** [hashicorp/packer#6752]
Currently, Azure does not have a way to copy Managed Images across regions / subscriptions. The only workaround is to copy the OS Disk and build an image in the new subscription.

If you use the VHD builder, this is not an issue. But with the Image builder, packer deletes the disks. The Managed Image does not have a Source Disk, and therefore cannot be copied. 

There's a CLI command to automate Image copying, but it too relies on the Image having Disks: https://github.com/Azure/azure-cli-extensions/tree/master/src/image-copy

I also noticed Packer wants to deprecate the VHD builder:
"Warning: You are using Azure Packer Builder to create VHDs which is being deprecated, consider using Managed Images"

Is there a way to keep the disks used to build the image? If that can happen, then I believe the `az image copy` command would work.

**Comment by vladfr** [comment]
As a workaround, I've done the copying in the last `provisioner`. This works fine, but it requires the additional step of creating the final image outside of `packer`.

**Comment by lyda** [comment]
Yes please, this is also something I'd need. I was coming here to lodge the exact same bug, using the exact same utility, so thanks for the well written issue description!

@vladfr Any chance you could post the last provisioner step?

**Comment by danieldop** [comment]
Joining in for this feature request.
More information about the aforementioned cli extension can be found [here](https://www.microsoft.com/developerblog/2018/02/15/copy-custom-vm-images-on-azure/).

**Comment by vladfr** [comment]
@lyda I would but it's rather ugly :) It's a bash with `shell-local`, just make sure it's the very last one, after the `deprovision` command that Azure requires. 

I basically use `az cli` to do `az vm show` and fetch all the disks using `jq`. Tip: you'll need to hard-code the resource group name in `packer.json`, I couldn't find a way to get it as a var in the scripts.

**Comment by riezebosch** [comment]
Shared Image Gallery is the way forward I suppose and that's already supported. Didn't have a chance to try it out though.

**Comment by phillipsj** [comment]
I was about to file this same bug. The reason for filling is slightly different. We are using Packer to create images for the Azure Marketplace which only accepts VHDs. When we create an Image we can't get to the VHD to use it to submit because has been deleted.

**Comment by phillipsj** [comment]
Yes, we do that currently.  If that is being deprecated then what is the
long term solution.

**Comment by boumenot** [comment]
Our current thinking is to create a snapshot of the disk(s).  The PR has been merged, and should be available in the next Packer release.

The docs have not been published yet because this is an unreleased feature, but in the interim see https://github.com/hashicorp/packer/blob/master/website/source/docs/builders/azure.html.md.

-   `managed_image_os_disk_snapshot_name` (string) If managed\_image\_os\_disk\_snapshot\_name 
    is set, a snapshot of the OS disk is created with the same name as this value before the 
    VM is captured.

-   `managed_image_data_disk_snapshot_prefix` (string)  If managed\_image\_data\_disk\_snapshot\_prefix 
    is set, snapshot of the data disk(s) is created with the same prefix as this value before the VM 
    is captured.

**Comment by jonesbusy** [comment]
Hi!

Is anyone was able to copy a managed image to an other region after packer build on Azure ? (using az image copy) ?

We are using 'managed_image_os_disk_snapshot_name' in order to keep the snapshot, but even with that it's not possible to move the managed image to an other region.

It seems that the CLI needs the OS disk to be not deleted. Is there a way to keep the OS disk ? (Or to not delete at all temporary resources ?

```
az image copy --source-object-name <sourcename> --source-resource-group <sourcegroup> --target-name <image target> --target-resource-group <target rg> --source-type image --target-location westeurope --target-subscription <target subscription>
```

```
WARNING: Getting os disk id of the source vm/image
WARNING: Creating source snapshot
ERROR: command failed: ['/usr/local/bin/python', '-m', 'azure.cli', 'snapshot', 'create', '--name', '**********', '--resource-group', '****', '--source', '/subscriptions/****/resourceGroups/*****/providers/Microsoft.Compute/disks/pkrosa9okt15pzk', '--output', 'json', '--tags', 'created_by=image-copy-extension']
ERROR: output: ERROR: Resource pkrosa9okt15pzk is not found.

ERROR: The command failed with an unexpected error. Here is the traceback:

ERROR: Command '['/usr/local/bin/python', '-m', 'azure.cli', 'snapshot', 'create', '--name', '******', '--resource-group', '*****', '--source', '/subscriptions/****/resourceGroups/**********/providers/Microsoft.Compute/disks/pkrosa9okt15pzk', '--output', 'json', '--tags', 'created_by=image-copy-extension']' returned non-zero exit status 1.
Traceback (most recent call last):
```

Help would be very appreciated :)

Thanks in advance.

**Comment by riezebosch** [comment]
Use `"managed_image_zone_resilient": true` so you don't have to copy.

**Comment by Boriszn** [comment]
Hey guys,

Any updates on this topic. We really need this fix to move forward.

Could you please help us.
Thanks a lot in advance.

**Comment by blackneurons** [comment]
Hi @phillipsj ,
I'm also using the VHD builder to create an image for Azure Marketplace. Actually, Packer didn't delete the temporary OS disk. So, we have two VHDs after the building process. Are they the same? Can I use the temporary OS disk for Marketplace?

Thank you
