### ISSUE TITLE
Packer 1.3.1 waits indefinitely for AMI to be ready despite console indicating that it is ready

### ISSUE THREAD

**Issue by res0nance** [hashicorp/packer#6765]
Running packer on a linux machine to create a windows ami gives the following log

https://gist.github.com/res0nance/91c52ac1908cb121b9a98e50a7252359

Packer waits forever instead of erroring out but when AWS console is checked the AMI packer is waiting for is available.
This issue is also sometimes seen when the copy is being made for encrypted boot.

**Comment by res0nance** [comment]
We believe that this is caused because we use temporary creds from a vault sts endpoint which times out. Packer does not seem to error out and simply spins forever.

**Comment by azr** [comment]
Hey @res0nance, thanks for reporting, tried reproducing locally and everything was fine. 
Could you please help mind find a way to reproduce your error more accurately ? 


Also, sometimes it takes a while for AMIs to become ready, and the waiting code is done in AWS' [golang library](https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#EC2.WaitUntilImageAvailableWithContext).

**Comment by res0nance** [comment]
@azr So i think what happens. is that the credentials expire before during ami creation process which causes it to spin indefinitely

**Comment by SwampDragons** [comment]
Did this ever work on a previous version of packer, or has this always been a problem? I don't remember making any changes to credential handling in recent versions.

**Comment by res0nance** [comment]
@SwampDragons This has never worked as far as I know
