### ISSUE TITLE
WinRM proxy issues with VMWare Workstation.

### ISSUE THREAD

**Issue by theemptyone** [hashicorp/packer#6775]
My Environment is:

- CentOS 7 Host System
- VMWare Workstation
- Windows 2016 VM.
- Packer 1.3.1

VMWare Workstation setups a virtual nic on your system with a reserved ip space, in my case 172.16.50.1.  Then when it creates a VM it uses dhcp within VMWare that sits on the subnet it created on the virtual switch with that as the default gateway.

The problem is that the WinRM connector (I assume) uses curl to check if WinRM is available.  Curl does not respect ip ranges in no_proxy; which means that you cannot put that entire subnet into no_proxy by default.  Since there is no way to 'set' the ip for the VM through packer (due to how VMWare works i believe), there is no way to logically pre-empt that with a variable wrapper. 

An Option is needed to allow curl (again, i assume) to ignore proxy for everything before it runs it's validator, or to add the ip that packer connects to, to it's no_proxy env variable in it's local session.

I've been able to work around this for my test cases (Vmware generally reuses the ip for a rebuild, and i've narrowed the dhcp pool to 8 ips and added each of them to no_proxy), but this does not scale.

**Comment by azr** [comment]
Hey @theemptyone, I see that curl doesn't respect IP ranges yet.

But I don't see any call to curl on [packers' side](https://github.com/hashicorp/packer/search?p=2&q=curl&unscoped_q=curl), nor on the [library we use](https://github.com/masterzen/winrm/search?q=curl&unscoped_q=curl).

Can you tell me exactly how you use packer in this case so I can try to reproduce/fix your problem ?

**Comment by theemptyone** [comment]
Sorry, i had to circle around back to this.  I don't believe curl will ever respect IP Ranges as it's developed now.

here is my base file
``
{
  "builders": [
    {
      "name": "{{ user `name` }}-vmware",
      "vm_name": "{{ user `name` }}-vmware",
      "type": "vmware-iso",
      "vmx_data": {
        "memsize": "{{ user `memory` }}",
        "numvcpus": "{{ user `cpus` }}",
        "scsi0.virtualDev": "lsisas1068",
        "vcpu.hotadd": "true",
        "mem.hotadd": "true"
      },
      "guest_os_type": "{{user `vm_os_type`}}",
      "headless": false,
      "version": "13",
      "iso_checksum": "{{user `iso_checksum`}}",
      "iso_checksum_type": "{{user `iso_checksum_type`}}",
      "iso_url": "{{user `mirror`}}/{{user `mirror_directory`}}/{{user `iso_name`}}",
      "output_directory": "../builds/packer-{{user `name`}}-vmware",
      "vmdk_name": "{{ user `name` }}",
      "communicator": "winrm",
      "winrm_username": "vagrant",
      "winrm_password": "vagrant",
      "winrm_timeout": "12h",
      "shutdown_command": "shutdown /s /t 10 /f /d p:4:1 /c \"Packer Shutdown\"",
      "shutdown_timeout": "15m",
      "floppy_files": [
        "{{user `common_script_folder`}}",
        "{{user `specific_script_folder`}}"
      ]
    }
  ]
}
``

The issue is that it never comes back as saying winrm is available if the IP Address isn't specifically called out in NoProxy.  Everything i've seen from the linux side, uses curl libraries to reach out to the host to poll for winrm.  Since it doesn't respect noproxy, it goes off to the proxy, which will fail as the vm is local.
