### ISSUE TITLE
shtudown_behaviour not working

### ISSUE THREAD

**Issue by rafik-eh** [hashicorp/packer#6779]
Hi,

I am currently using packer `v1.2.2` to create AMIs on AWS and the **"shutdown_behavior"** option does not seem to like the __"stop"__ . Indeed, from my understanding, if we set it to __stop__ the Packer instance is supposed to stop and not terminate in case of failure. 
I read the `CHANGELOG.md` to see if the bug has been fixed on the newest version and hence upgrade mine, but did not see anything related to this.
Would you please take a look?
Also, would it be possible to create a new state **"running"**? This way we can investigate what went wrong without having to spin up the instance again?

Thanks

**Comment by rickard-von-essen** [comment]
For troubleshooting use `packer build --on-error=ask ...`, see https://packer.io/docs/other/debugging.html
