### ISSUE TITLE
nvme_device_path ignored by amazon-chroot when mounting

### ISSUE THREAD

**Issue by MetricMike** [hashicorp/packer#6780]
I think there's a missing piece in #6295, where I think the nvme_device_path is being ignored during mounting:

I can reproduce this when I leave a process/mount during provisioning and the packer process fails on unmounting (with exit status 32, from I believe a docker install leaving a mount around). `lsblk` and `ls /dev` look like the volume has unmounted correctly, but subsequent runs fail if that `nvme_device_path` is reused.

1. Use the following script to get an available device (to support multiple concurrent packer runs)
```bash
export DEVICE_PATH=/dev/sdf
export NVME_PATH=/dev/nvme1n1p
MOUNT_LETTERS=(f g h i j k l m n o p)
for ((i=0; i < ${#MOUNT_LETTERS[@]}; i++)); do
    export NVME_PATH=/dev/nvme${i+1}n1p
    export DEVICE_PATH=/dev/sd${MOUNT_LETTERS[i]}
    if [ ! -b "${NVME_PATH}1" ]; then
        break
    fi
done
```
2. Pass that to packer with ENV variables (in my issue, `DEVICE_PATH=/dev/sdf` and `NVME_PATH=/dev/nvme1n1p`)
```json
{
  "builders": [
    {
      "type": "amazon-chroot",
      ...
      "nvme_device_path": "{{user `nvme_path`}}",
      "device_path": "{{user `device_path`}}",
    }
  ],
  "provisioners": [
    ...
  ],
  "variables": {
    ...
    "device_path": "{{env `DEVICE_PATH`}}",
    "nvme_path": "{{env `NVME_PATH`}}"
  }
}
```

3.  Packer fails when trying to mount with:
```bash
amazon-chroot: Attaching the root volume to /dev/sdf
amazon-chroot: Mounting the root device...
amazon-chroot: Error mounting root volume: exit status 32
amazon-chroot: Stderr: mount: special device /dev/nvme1n1p1 does not exist
```
And the result of `ls /dev` reveals a `/dev/nvme2n1p1` instead. The particular server I'm running packer on is backed by an autoscaling group, and cycling instances results in packer building on `/dev/nvme1n1p1` (or whatever ends up being specified for that run) correctly.

Any ideas at where I can look at why the values from packer.json is getting overridden in some places (attaching the volume) and not others (mounting the volume)?

Thanks!

**Comment by rickard-von-essen** [comment]
Please supply the information requested in the issue template:
- Packer version (`packer version`)
- Host platform (`uname -a` etc.)
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a [gist](https://gist.github.com).
- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your [gist](https://gist.github.com).

**Comment by MetricMike** [comment]
While collecting a minimal template/scripts for reproducing this I discovered it's not a bug with packer (or least not an unknown bug), but with my bash arithmetic:

`export NVME_PATH=/dev/nvme${i+1}n1p` doesn't perform arithmetic, always returns `/dev/nvme1n1p` and should have been `export NVME_PATH="/dev/nvme$((i+1))n1p"`.

My script also lacked a final exit condition, so if `/dev/nvme1n1p` exists, it would eventually end by exporting `/dev/sdp` and `/dev/nvme1n1p`. That caused the mount error, and the surprise `/dev/nvme2n1p` (because AttachVolume is called with `--device /dev/sdp`, and `/dev/nvme2n1p` is the next available block device.

The reported error above `special device /dev/nvme1n1p1 does not exist` is (I believe) due to a race condition from running 2 packer processes concurrently with identical nvme_device_paths, and packer not locking during cleanup (because under normal circumstances it should be safe to reason that one and only one process is operating on that device).

If packer was able to add nvme to the DevicePrefixList, it's locking step would have prevented this error, but that's a much bigger refactor as mentioned in https://github.com/hashicorp/packer/pull/6711
