### ISSUE TITLE
Error building plugin with Go 1.11: cannot find module for path

### ISSUE THREAD

**Issue by dradtke** [hashicorp/packer#6782]
I maintain a [Vultr plugin](https://github.com/dradtke/packer-builder-vultr) for Packer, and I ran into this error when trying to [migrate the builder](https://github.com/dradtke/packer-builder-vultr/tree/modules) to use Go modules:

```
$ go build
build packer-builder-vultr: cannot find module for path github.com/masterzen/azure-sdk-for-go/core/http
```

`go mod why` indicates that this is a transitive dependency:

```
$ go mod why github.com/masterzen/azure-sdk-for-go/core/http
# github.com/masterzen/azure-sdk-for-go/core/http
packer-builder-vultr/vultr
github.com/hashicorp/packer/helper/communicator
github.com/masterzen/winrm
github.com/masterzen/azure-sdk-for-go/core/http
```

**Comment by azr** [comment]
Hey @dradtke,

Not 100% sure about what causes this problem but `github.com/masterzen/azure-sdk-for-go` is super old and references pieces of `github.com/Azure/azure-sdk-for-go/` that don't exist anymore.

Packer also references pieces of `github.com/azure/azure-sdk-for-go/` that are a bit different.

In any case, `github.com/masterzen/azure-sdk-for-go/core/[http|tls]` should probably not be used any more by `github.com/masterzen/winrm` but they are, and are the only reference to it.
This pr https://github.com/masterzen/winrm/pull/86 is going to help you better at fixing this I believe. I'll be watching this issue and if it get's merged I'll update the dependency.

Nothing more we can do here, so I'm closing this issue.

Ps: yeah `go mod` is still experimental so I'd not recommend using it, yet 🙂
