### ISSUE TITLE
Packer wrongly report invalid AMI Name

### ISSUE THREAD

**Issue by salvianreynaldi** [hashicorp/packer#6791]
## Description ##

I used packer to set the name for the baked AMIs. However, I cannot include `{{ .SourceAMI }}` in the AMI name. https://github.com/salvianreynaldi/codebuild-ami-baking/commit/42ef76a0f4a0c9a6ef9f13f92e9a979375627594 contains the only difference of the Packer template that works (before), and the one that doesn't (after). I copy the AMI baked with the working template, and change the name suffix to Source AMI ID and it works, so AMI name length must not be the issue

The Packer error message is:
```
* AMIName should only contain alphanumeric characters, parentheses (()), square brackets ([]), spaces ( ), periods (.), slashes (/), dashes (-), single quotes ('), at-signs (@), or underscores(_). You can use the `clean_ami_name` template filter to automatically clean your ami name.
```

## Additional Information ##

- Packer version: 1.3.1
- Host platform: bionic, running on CodeBuild ([Dockerfile here](https://github.com/salvianreynaldi/codebuild-ami-baking/blob/master/Dockerfile))
- [Packer template here](https://github.com/traveloka/codebuild-ami-baking/blob/master/aws-ebs-traveloka-ansible.json)

**Comment by rickard-von-essen** [comment]
This is because these are only available in the options where they are referenced such as `ami_description`. This is not very clear from the docs so I think we should improve them.

**Comment by salvianreynaldi** [comment]
Thanks for the clarification @rickard-von-essen!
I was confused as previously the variable is usued for `tags` and it worked. So, do you mean that it's only available in options saying "This is a template engine" [here](https://www.packer.io/docs/builders/amazon-ebs.html#optional-)?

**Comment by rickard-von-essen** [comment]
Yes, exactly `ami_description`, `run_tags`, `run_volume_tags`, `snapshot_tags`, and `tags`.

**Comment by SwampDragons** [comment]
Do you have a specific suggestion for how we can improve the docs to make this clearer for you?

**Comment by ofosos** [comment]
I've stumbled over this exact issue multiple times. Created a small PR to ameliorate this problem for newcomers. I think this change would have helped me.
