### ISSUE TITLE
IP lookup failed: vmnet does not have a dhcp lease

### ISSUE THREAD

**Issue by alleynec** [hashicorp/packer#6795]
I'm getting "IP lookup failed: None of the found device(s) [vmnet8] has a DHCP lease for MAC..." error when building using Packer 1.3.1 hosted on macOS 10.13.6 and after trying all the suggestions in issue 5925. Below is my vmx file (I don't use the vmx_data or vmx_data_post fields in the vmx builder section of the json file):

.encoding = "UTF-8"
cleanShutdown = "TRUE"
config.version = "8"
cpuid.coresPerSocket = "4"
displayName = "Win-8.1-x64-base"
ehci.pciSlotNumber = "34"
ehci.present = "TRUE"
ethernet0.connectionType = "nat"
ethernet0.present = "TRUE"
ethernet0.startConnected = "TRUE"
extendedConfigFile = "Win-8.1-x64-base.vmxf"
floppy0.present = "FALSE"
guestOS = "windows8-64"
hpet0.present = "TRUE"
keyboardAndMouseProfile = "520c140c-fca4-0ebb-4d54-f6ca38630681"
mem.hotadd = "TRUE"
memsize = "3072"
migrate.hostlog = "./Win-8.1-x64-base-afb40be1.hlog"
mks.enable3d = "TRUE"
monitor.phys_bits_used = "43"
numa.autosize.cookie = "40001"
numa.autosize.vcpu.maxPerVirtualNode = "4"
numvcpus = "4"
nvram = "Win-8.1-x64-base.nvram"
pciBridge0.pciSlotNumber = "17"
pciBridge0.present = "TRUE"
pciBridge4.functions = "8"
pciBridge4.pciSlotNumber = "21"
pciBridge4.present = "TRUE"
pciBridge4.virtualDev = "pcieRootPort"
pciBridge5.functions = "8"
pciBridge5.pciSlotNumber = "22"
pciBridge5.present = "TRUE"
pciBridge5.virtualDev = "pcieRootPort"
pciBridge6.functions = "8"
pciBridge6.pciSlotNumber = "23"
pciBridge6.present = "TRUE"
pciBridge6.virtualDev = "pcieRootPort"
pciBridge7.functions = "8"
pciBridge7.pciSlotNumber = "24"
pciBridge7.present = "TRUE"
pciBridge7.virtualDev = "pcieRootPort"
powerType.powerOff = "soft"
powerType.powerOn = "soft"
powerType.reset = "soft"
powerType.suspend = "soft"
proxyApps.publishToHost = "FALSE"
sata0:0.fileName = "Virtual Disk-000018.vmdk"
sata0:0.present = "TRUE"
sata0:0.redo = ""
sata0:1.deviceType = "cdrom-image"
sata0:1.fileName = "/VMware/Installers/en_windows_8.1_enterprise_with_update_x64_dvd_6054382.iso"
sata0:1.present = "TRUE"
sata0:1.startConnected = "FALSE"
sata0.pciSlotNumber = "36"
sata0.present = "FALSE"
scsi0:0.present = "FALSE"
scsi0.pciSlotNumber = "160"
scsi0.present = "TRUE"
scsi0.sasWWID = "50 05 05 68 d4 41 3e f0"
scsi0.virtualDev = "lsisas1068"
sensor.location = "pass-through"
serial0.fileType = "thinprint"
serial0.present = "TRUE"
serial0.startConnected = "FALSE"
softPowerOff = "TRUE"
sound.autodetect = "TRUE"
sound.fileName = "-1"
sound.pciSlotNumber = "33"
sound.present = "TRUE"
sound.virtualDev = "hdaudio"
svga.graphicsMemoryKB = "786432"
tools.syncTime = "TRUE"
tools.upgrade.policy = "upgradeAtPowerCycle"
usb_xhci:4.deviceType = "hid"
usb_xhci:4.parent = "-1"
usb_xhci:4.port = "4"
usb_xhci:4.present = "TRUE"
usb_xhci:6.deviceType = "hub"
usb_xhci:6.parent = "-1"
usb_xhci:6.port = "6"
usb_xhci:6.present = "TRUE"
usb_xhci:6.speed = "2"
usb_xhci:7.deviceType = "hub"
usb_xhci:7.parent = "-1"
usb_xhci:7.port = "7"
usb_xhci:7.present = "TRUE"
usb_xhci:7.speed = "4"
usb_xhci.pciSlotNumber = "224"
usb_xhci.present = "TRUE"
usb.pciSlotNumber = "32"
usb.present = "TRUE"
usb.vbluetooth.startConnected = `"FALSE"`
uuid.bios = "56 4d 12 b8 d4 41 3e fe-cf 9c a3 97 e0 18 58 ce"
uuid.location = "56 4d 73 98 1a 8b 33 6d-52 e7 84 d0 28 b5 85 c0"
virtualHW.productCompatibility = "hosted"
virtualHW.version = "14"
vm.genid = "3256754623135940363"
vm.genidX = "7760565860003738565"
vmci0.id = "-535275314"
vmci0.pciSlotNumber = "35"
vmci0.present = "TRUE"
vmotion.checkpointFBSize = "134217728"
vmotion.checkpointSVGAPrimarySize = "134217728"
vmxnet3.serialNumberV2 = "FALSE"
  

Below is log output:
Located networkmapper configuration file using Fusion6: /Library/Preferences/VMware Fusion/networking
2018/10/03 09:20:47 packer: 2018/10/03 09:20:47 GuestIP discovered device matching nat: vmnet8
2018/10/03 09:20:47 packer: 2018/10/03 09:20:47 Lookup up IP information...
2018/10/03 09:20:47 packer: 2018/10/03 09:20:47 GuestAddress found MAC address in VMX: 00:0c:29:c8:ba:f6
2018/10/03 09:20:47 packer: 2018/10/03 09:20:47 Trying DHCP leases path: /var/db/vmware/vmnet-dhcpd-vmnet8.leases
2018/10/03 09:20:47 packer: 2018/10/03 09:20:47 IP lookup failed: None of the found device(s) [vmnet8] has a DHCP lease for MAC 00:0c:29:c8:ba:f6
2018/10/03 09:20:47 packer: 2018/10/03 09:20:47 [DEBUG] Error getting SSH address: IP lookup failed: None of the found device(s) [vmnet8] has a DHCP lease for MAC 00:0c:29:c8:ba:f6

**Comment by azr** [comment]
Hey @alleynec, thanks for opening an issue let's continue in #5925, where you also posted the same message, I will try to have look soon.
