### ISSUE TITLE
Unable to print unescaped strings to stderr >=v1.3.1

### ISSUE THREAD

**Issue by grubernaut** [hashicorp/packer#6796]
After this commit, https://github.com/hashicorp/packer/commit/941d2fcca6a6eef4ac0afe1a9634cc60a542bc50, packer builders are unable to print to `os.Stderr` via any `Fprint()` functions or logging functions, if the string to print contains any unescaped `fmt` verbs.

This was discovered when debugging a packer builder's url query parameters, and found that any escaped query parameter `%2A`, `%2F`, `%0D`, etc, were printing as `%D!(MISSING)` from the `Sprintf()` call in `log.go`.

Removing this commit and recompiling fixes the issue; and raw strings are then able to print without attempting to be expanded via `fmt.Sprintf()`.

**Comment by SwampDragons** [comment]
Can you give me an example of a failed logline?

**Comment by SwampDragons** [comment]
Here's a linux binary with a patch applied changing Sprintf() to a simple Sprint(); it appears to work for me. Does this one work for your cases?
[packer.zip](https://github.com/hashicorp/packer/files/2462313/packer.zip)

**Comment by grubernaut** [comment]
Sorry for the late reply, on vacation this week...

Using the following patch (based off of commit `ed38fe9bef800036fcbb1d760de14034613a4675`):
```
diff --git a/builder/amazon/common/step_pre_validate.go b/builder/amazon/common/step_pre_validate.go
index 73b4022b7..1edf77da2 100644
--- a/builder/amazon/common/step_pre_validate.go
+++ b/builder/amazon/common/step_pre_validate.go
@@ -3,6 +3,8 @@ package common
 import (
 	"context"
 	"fmt"
+	"log"
+	"os"
 
 	"github.com/aws/aws-sdk-go/aws"
 	"github.com/aws/aws-sdk-go/service/ec2"
@@ -27,6 +29,10 @@ func (s *StepPreValidate) Run(_ context.Context, state multistep.StateBag) multi
 
 	ec2conn := state.Get("ec2").(*ec2.EC2)
 
+	debugStr := "Testing failing log statment: %2A %2F %0D\n"
+	log.Print(debugStr)
+	fmt.Fprintln(os.Stderr, debugStr)
+
 	ui.Say(fmt.Sprintf("Prevalidating AMI Name: %s", s.DestAmiName))
 	resp, err := ec2conn.DescribeImages(&ec2.DescribeImagesInput{
 		Filters: []*ec2.Filter{{
```

And using the following basic template: 
```
{
  "variables": {
    "access_key": "{{env `AWS_ACCESS_KEY_ID` }}",
    "secret_key": "{{env `AWS_SECRET_ACCESS_KEY` }}"
  },
  "builders": [
    {
      "access_key": "{{user `access_key` }}",
      "ami_name": "packer-quick-start {{timestamp}}",
      "instance_type": "t2.micro",
      "region": "us-east-1",
      "secret_key": "{{user `secret_key` }}",
      "source_ami": "ami-fce3c696",
      "ssh_username": "ubuntu",
      "type": "amazon-ebs"
    }
  ]
}
```

The following log lines are printed:
```
2018/10/09 22:33:57 packer: 2018/10/09 22:33:57 Testing failing log statment: %!A(MISSING) %!F(MISSING) %!D(MISSING)
2018/10/09 22:33:57 packer: Testing failing log statment: %!A(MISSING) %!F(MISSING) %!D(MISSING)
```

Using `fmt.Sprint()` instead of `fmt.Sprintf()` fixes the issue, leaving the following result:
```
2018/10/09 22:38:48 packer: 2018/10/09 22:38:48 Testing failing log statment: %2A %2F %0D                                                           
2018/10/09 22:38:48 packer: Testing failing log statment: %2A %2F %0D 
```

Opened #6824 to fix this.
