### ISSUE TITLE
Packer Image build fails when packer vm instance type is "Standard_F64s_v2"

### ISSUE THREAD

**Issue by mvvsubbu** [hashicorp/packer#6806]
FOR BUGS:

Describe the problem and include the following information:

When Packer VM Instance Type is given as **Standard_F64s_v2** the packer command fails with the following error. But this SKU is available in our subscription I was able to create VM manually in that subscription.

Instance size "Standard_F64s_v2" not available in location "West US" for this subscription%!(PACKER_COMMA) valid instance sizes: A10%!(PACKER_COMMA)A11%!(PACKER_COMMA)A5%!(PACKER_COMMA)A6%!(PACKER_COMMA)A7%!(PACKER_COMMA)A8%!(PACKER_COMMA)A9%!(PACKER_COMMA)Basic_A0%!(PACKER_COMMA)Basic_A1%!(PACKER_COMMA)Basic_A2%!(PACKER_COMMA)Basic_A3%!(PACKER_COMMA)Basic_A4%!(PACKER_COMMA)ExtraLarge%!(PACKER_COMMA)ExtraSmall%!(PACKER_COMMA)Large%!(PACKER_COMMA)Medium%!(PACKER_COMMA)Small%!(PACKER_COMMA)Standard_A1_v2%!(PACKER_COMMA)Standard_A2_v2%!(PACKER_COMMA)Standard_A2m_v2%!(PACKER_COMMA)Standard_A4_v2%!(PACKER_COMMA)Standard_A4m_v2%!(PACKER_COMMA)Standard_A8_v2%!(PACKER_COMMA)Standard_A8m_v2%!(PACKER_COMMA)Standard_D1%!(PACKER_COMMA)Standard_D1_v2%!(PACKER_COMMA)Standard_D11%!(PACKER_COMMA)Standard_D11_v2%!(PACKER_COMMA)Standard_D11_v2_Promo%!(PACKER_COMMA)Standard_D12%!(PACKER_COMMA)Standard_D12_v2%!(PACKER_COMMA)Standard_D12_v2_Promo%!(PACKER_COMMA)Standard_D13%!(PACKER_COMMA)Standard_D13_v2%!(PACKER_COMMA)Standard_D13_v2_Promo%!(PACKER_COMMA)Standard_D14%!(PACKER_COMMA)Standard_D14_v2%!(PACKER_COMMA)Standard_D14_v2_Promo%!(PACKER_COMMA)Standard_D15_v2%!(PACKER_COMMA)Standard_D16_v3%!(PACKER_COMMA)Standard_D16s_v3%!(PACKER_COMMA)Standard_D2%!(PACKER_COMMA)Standard_D2_v2%!(PACKER_COMMA)Standard_D2_v2_Promo%!(PACKER_COMMA)Standard_D2_v3%!(PACKER_COMMA)Standard_D2s_v3%!(PACKER_COMMA)Standard_D3%!(PACKER_COMMA)Standard_D3_v2%!(PACKER_COMMA)Standard_D3_v2_Promo%!(PACKER_COMMA)Standard_D32_v3%!(PACKER_COMMA)Standard_D32s_v3%!(PACKER_COMMA)Standard_D4%!(PACKER_COMMA)Standard_D4_v2%!(PACKER_COMMA)Standard_D4_v2_Promo%!(PACKER_COMMA)Standard_D4_v3%!(PACKER_COMMA)Standard_D4s_v3%!(PACKER_COMMA)Standard_D5_v2%!(PACKER_COMMA)Standard_D5_v2_Promo%!(PACKER_COMMA)Standard_D64_v3%!(PACKER_COMMA)Standard_D64s_v3%!(PACKER_COMMA)Standard_D8_v3%!(PACKER_COMMA)Standard_D8s_v3%!(PACKER_COMMA)Standard_DS1%!(PACKER_COMMA)Standard_DS1_v2%!(PACKER_COMMA)Standard_DS11%!(PACKER_COMMA)Standard_DS11_v2%!(PACKER_COMMA)Standard_DS11_v2_Promo%!(PACKER_COMMA)Standard_DS12%!(PACKER_COMMA)Standard_DS12_v2%!(PACKER_COMMA)Standard_DS12_v2_Promo%!(PACKER_COMMA)Standard_DS13%!(PACKER_COMMA)Standard_DS13_v2%!(PACKER_COMMA)Standard_DS13_v2_Promo%!(PACKER_COMMA)Standard_DS14%!(PACKER_COMMA)Standard_DS14_v2%!(PACKER_COMMA)Standard_DS14_v2_Promo%!(PACKER_COMMA)Standard_DS15_v2%!(PACKER_COMMA)Standard_DS2%!(PACKER_COMMA)Standard_DS2_v2%!(PACKER_COMMA)Standard_DS2_v2_Promo%!(PACKER_COMMA)Standard_DS3%!(PACKER_COMMA)Standard_DS3_v2%!(PACKER_COMMA)Standard_DS3_v2_Promo%!(PACKER_COMMA)Standard_DS4%!(PACKER_COMMA)Standard_DS4_v2%!(PACKER_COMMA)Standard_DS4_v2_Promo%!(PACKER_COMMA)Standard_DS5_v2%!(PACKER_COMMA)Standard_DS5_v2_Promo%!(PACKER_COMMA)Standard_E16_v3%!(PACKER_COMMA)Standard_E16s_v3%!(PACKER_COMMA)Standard_E2_v3%!(PACKER_COMMA)Standard_E20_v3%!(PACKER_COMMA)Standard_E20s_v3%!(PACKER_COMMA)Standard_E2s_v3%!(PACKER_COMMA)Standard_E32_v3%!(PACKER_COMMA)Standard_E32s_v3%!(PACKER_COMMA)Standard_E4_v3%!(PACKER_COMMA)Standard_E4s_v3%!(PACKER_COMMA)Standard_E64_v3%!(PACKER_COMMA)Standard_E64s_v3%!(PACKER_COMMA)Standard_E8_v3%!(PACKER_COMMA)Standard_E8s_v3%!(PACKER_COMMA)Standard_F1%!(PACKER_COMMA)Standard_F16%!(PACKER_COMMA)Standard_F16s%!(PACKER_COMMA)Standard_F1s%!(PACKER_COMMA)Standard_F2%!(PACKER_COMMA)Standard_F2s%!(PACKER_COMMA)Standard_F4%!(PACKER_COMMA)Standard_F4s%!(PACKER_COMMA)Standard_F8%!(PACKER_COMMA)Standard_F8s%!(PACKER_COMMA)Standard_G1%!(PACKER_COMMA)Standard_G2%!(PACKER_COMMA)Standard_G3%!(PACKER_COMMA)Standard_G4%!(PACKER_COMMA)Standard_G5%!(PACKER_COMMA)Standard_GS1%!(PACKER_COMMA)Standard_GS2%!(PACKER_COMMA)Standard_GS3%!(PACKER_COMMA)Standard_GS4%!(PACKER_COMMA)Standard_GS5%!(PACKER_COMMA)Standard_L16s%!(PACKER_COMMA)Standard_L32s%!(PACKER_COMMA)Standard_L4s%!(PACKER_COMMA)Standard_L8s

- Packer Version: 0.9.0 and 1.3.1 tried
- Host platform : Windows
- Use any packer template file and give Packer VM Instance type as : Standard_F64s_v2 the command fails with above error.
**packer.exe build -machine-readable packer_template.json**

**Comment by azr** [comment]
Howdy @mvvsubbu,
I don't think there is anything we can do codewise to help you fix your issue given the following message :
`Instance size "Standard_F64s_v2" not available in location "West US" for this subscription`

But to quote Azure's [announcement](https://azure.microsoft.com/en-us/blog/fv2-vms-are-now-available-the-fastest-vms-on-azure/) :

> these sizes are available in West US 2, West Europe, and East US. Southeast Asia is coming soon.

I believe trying in one of those regions will solve your issue 🙂

**Comment by mvvsubbu** [comment]
The blog you pointed is an year old better live in current dates :) and it is very easy to try creating a VM in Azure with that SKU instead of searching for old blogs :).  I created the VM in West US region, It was successful, you can refer below screen shots for details.  So better check why packer is getting that error from Azure.

![image](https://user-images.githubusercontent.com/11993108/46703435-dd8bc080-cbdb-11e8-9034-cae4d08146d0.png)

![image](https://user-images.githubusercontent.com/11993108/46704403-a4ede600-cbdf-11e8-87af-1e9b58f8177f.png)

**Comment by azr** [comment]
Hey @mvvsubbu, gotcha, I should have checked the way you did; reopening this issue.
We will investigate 🔍 .

**Comment by mvvsubbu** [comment]
Thanks I believe you are calling some old API... I haven't spent enough time in understanding your code so I might be wrong as well.

**Comment by boumenot** [comment]
I am not aware of any API version change that would allow or disallow the use of a specific SKU.  The error message emitted by Packer is quite clear - your **subscription** does not have access to that SKU in **WestUS**.  It then provides a detailed list of what is available.

What is the output of the command.

```sh
az vm list-skus -lwestus -otable
```

Here's the relevant output for me.

```text
virtualMachines   westus       Standard_F64s_v2                 ['MaxResourceVolumeMB=524288', ... 'PremiumIO=True']    Standard  F64s_v2        NotAvailableForSubscription
```

**Comment by mvvsubbu** [comment]
I was able to create VM in my subscription manually, can you refer the above screen shots.

**Comment by nywilken** [comment]
@mvvsubbu this is an old issue, but I did want to circle back here as this issue is not reproducible via the latest Packer. I am going to close this issue for now, but if you find yourself running into a similar issue for different image sizes please create a new issue. Cheers!
