### ISSUE TITLE
Feature request "Keep Registered" option for building in VMware Fusion

### ISSUE THREAD

**Issue by TyMac** [hashicorp/packer#6808]
It would be nice to be able to not discard the image built when building inside of VMware Fusion. This would be useful for creating desktop VMs that could be started and used inside Fusion instead of uploaded else where. Useful for security sandbox testing and highly trusted images that could be use for a short time and then discarded.

**Comment by azr** [comment]
Hey @TyMac, I think that the [`output_directory`](https://www.packer.io/docs/builders/vmware-iso.html#output_directory) is the option you are looking for.
It will create a directory containing a set of **vmx**/vmdk/nvram/vmsd/vmxf files that you can you to start a VM with
