### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by rgarrigue** [hashicorp/packer#6813]
Hello

I'm trying to run Packer over an ESXi 5.5, I end up with a segmentation fault

```
/vmfs/volumes/584854b8-44148a95-ab98-68b599706b5c/packer # uname -a
VMkernel vt-esx-146.DomainTests.loc 5.5.0 #1 SMP Release build-7967571 Mar  7 2018 22:31:06 x86_64 GNU/Linux
/vmfs/volumes/584854b8-44148a95-ab98-68b599706b5c/packer # vmware -v
VMware ESXi 5.5.0 build-7967571
/vmfs/volumes/584854b8-44148a95-ab98-68b599706b5c/packer # ./packer version
Segmentation fault
```

sha256sum match for the .zip.

Any hints ?

**Comment by rickard-von-essen** [comment]
Don't think you can run the Packer binary on an ESXi machine? You are supposed to run it on a "workstation" and connect to the ESXi machine over SSH.

**Comment by rgarrigue** [comment]
Reading the doc, seems you're right. Never saw the option https://www.packer.io/docs/builders/vmware-iso.html#remote_type before. Gonna try
