### ISSUE TITLE
 ansible provisioner doesn't find vault password

### ISSUE THREAD

**Issue by Raghuveer123** [hashicorp/packer#6815]
```
Unable to add the Ansible Vault key in Provisioner,Please try to help resolve this issue.
[0;32m    amazon-ebs: Executing Ansible: cd /tmp/packer-provisioner-ansible-local/5bbcc054-c9fa-ae81-1983-139cc045d13d && ansible-playbook /tmp/packer-provisioner-ansible-local/5bbcc054-c9fa-ae81-1983-139cc045d13d/main.yaml --extra-vars "packer_build_name=amazon-ebs packer_builder_type=amazon-ebs packer_http_addr=" --vault-password-file=/Ansible/vault_password -c local -i /tmp/packer-provisioner-ansible-local/5bbcc054-c9fa-ae81-1983-139cc045d13d/packer-provisioner-ansible-local798412897[0m
[0;32m    amazon-ebs: [0;31mERROR! The vault password file /Ansible/vault_password was not found[0m[0m
```

**Comment by Raghuveer123** [comment]
{
        "type": "ansible-local",
        "command": "ansible-playbook",
        "extra_arguments": "--vault-password-file=/Ansible/vault_password",
        "playbook_file": "Ansible/main.yaml",
        "playbook_dir" : "Ansible"

**Comment by Raghuveer123** [comment]
Hard code the Ansible vault file,Still it cannot read the contents from the file

**Comment by rickard-von-essen** [comment]
You need to upload `/Ansible/vault_password` before referencing it.

Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for getting help.

See https://www.packer.io/community/

_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._

**Comment by Raghuveer123** [comment]
How can I upload that file?

**Comment by Raghuveer123** [comment]
I got it

**Comment by talentscout77** [comment]
How did you solve this?
