### ISSUE TITLE
Tried to upload the file but still getting the issues

### ISSUE THREAD

**Issue by Raghuveer123** [hashicorp/packer#6816]
Uploaded the vault secret password file under /home/ec2-user/vault_password
[0;32m    amazon-ebs: Executing Ansible: cd /tmp/packer-provisioner-ansible-local/5bbcecea-397e-785e-c828-8c865e773e8d && ansible-playbook /tmp/packer-provisioner-ansible-local/5bbcecea-397e-785e-c828-8c865e773e8d/main.yaml --extra-vars "packer_build_name=amazon-ebs packer_builder_type=amazon-ebs packer_http_addr=" --vault-password-file=/home/ec2-user/vault_password -c local -i /tmp/packer-provisioner-ansible-local/5bbcecea-397e-785e-c828-8c865e773e8d/packer-provisioner-ansible-local965196055[0m
[0;32m    amazon-ebs: [1;35m [WARNING]: Error in vault password file loading (default): Problem running[0m[0m
[0;32m    amazon-ebs: [1;35mvault password script /home/ec2-user/vault_password ([Errno 8] Exec format[0m[0m.

This is piece of snippet of my code
{
        "type": "file",
        "source": "vault_password",
        "destination": "/home/ec2-user/vault_password"
      },
      {
        "type": "shell",
        "inline": [
        "sudo chmod 775 /home/ec2-user/agent-setup.sh",
        "sudo sh /home/ec2-user/agent-setup.sh",
        "sudo chmod 775 /home/ec2-user/*"
            ]
      },
      {
        "type": "ansible-local",
        "command": "ansible-playbook",
        "extra_arguments": "--vault-password-file=/home/ec2-user/vault_password",
        "playbook_file": "Ansible/main.yaml",
        "playbook_dir" : "Ansible"

**Comment by rickard-von-essen** [comment]
Please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._
