### ISSUE TITLE
Feature Request: Allow windows-shell to access the {{.WinRMPassword}} variable

### ISSUE THREAD

**Issue by ChulHul** [hashicorp/packer#6819]
Task scheduler on windows client 1803 and above is unable to run until the a user logs in once. This breaks running the powershell provisioner in elevated mode.

It would be useful to allow the windows-shell provisioner access {{.WinRMPassword}} variable so we can set auto login.

**Comment by SwampDragons** [comment]
If I don't get a chance to work on this soon, it would be a good first issue for someone; they can see how the Powershell provisioner implements it to get an idea.

**Comment by SwampDragons** [comment]
This should be addressed as part of the work on #7079

**Comment by sylviamoss** [comment]
Hello There!
I'm closing this issue since v1.5.0 has the mechanism for sharing info between builders and provisioners, including the `WinRMPassword`. 
[See docs](https://packer.io/docs/templates/engine.html#build) for more information.
