### ISSUE TITLE
Oracle Classic - Missing Source Image List Entry Value

### ISSUE THREAD

**Issue by adormanau** [hashicorp/packer#6833]
### Provider
- oracle classic

### Feature request
The ability to set the image list entry for the source image list. This will allow us to select a specific version of an Oracle Provided image as the source.

### I tried to do it

I have tried to add this functionality myself, as the underlying  go-oracle-terraform/compute/instances.go does expose an "Entry" attribute, which is exactly what we want.

I added the following to config.go (around line 34)

```
SourceImageListEntry  string    `mapstructure:"source_image_list_entry"`
```

and added the following to set_create_instance.go (around line 36)

```
		Entry:      config.SourceImageListEntry,
```

However when I run packer I get

```
Failed to mapstructure Config: 1 error(s) occurred:

* unknown configuration key: "source_image_list_entry"
```

**Comment by SwampDragons** [comment]
If you'd like, you can make a PR and I can help tweak your branch to get this working.

**Comment by adormanau** [comment]
Thanks @SwampDragons, that would be great. I really appreciate your offer to help.

 I have created the PR.

**Comment by SwampDragons** [comment]
I've done some basic research and I don't believe this is actually possible to do via Oracle's API. Closing for now, but if someone finds out I'm mistaken please reopen and we'll figure this out.

**Comment by mwhooker** [comment]
once hashicorp/go-oracle-terraform#171 is merged this should be possible. @adormanau if you want to work off that branch I think this will work, otherwise I'll take care of it once it is merged
