### ISSUE TITLE
Can't enable network on ESX 5.1 / 5.5

### ISSUE THREAD

**Issue by rgarrigue** [hashicorp/packer#6835]
Hi

I'm running packer 1.3.1 and trying to build RHEL 6 & 7 from bento against ESXi 5.1 and 5.5. Problem is, the network card isn't enabled on the VM. Whenever I try to enable it manualy, I got this message

![image](https://user-images.githubusercontent.com/1872031/46795655-01214900-cd4b-11e8-8226-b9df468aa809.png)

Which translate by Specified device support incompatible with device '0'.

Another puzzling part is

![image](https://user-images.githubusercontent.com/1872031/46795748-3c237c80-cd4b-11e8-9fe2-2b1d36030e1f.png)

The yellow triangle says This hors got no VM Network, or you're not allow to access them. I'm allowed since I'm connected as admin

I found a workaround there, removing the interface and adding a new one with default network, then rebooting the VMs does work. But it's manual and won't do for my once in a week pipeline triggered build.

Tried to fiddle with the network parameters but no luck so far. One question on those, the "network" requires a vlanid, a name like "vlan_test" ? In which case how to specify with a white space while calling from `-var "network=VM Network", is that ok ?

Any help would be greatly appreciated !
Best regards,

**Comment by jreagan00** [comment]
What Network Driver are you using? This is what i did in the builder section to get the network functional, The e1000 is the important part:

      "vmx_data": {
        "ethernet0.networkName": "{{user `vsphere_vm_network`}}",
        "ethernet0.present": "TRUE",
        "ethernet0.startConnected": "TRUE",
        "ethernet0.virtualDev": "e1000",
        "ethernet0.addressType": "generated",
        "ethernet0.generatedAddressOffset": "0",
        "ethernet0.wakeOnPcktRcv": "FALSE"
}

**Comment by rgarrigue** [comment]
Well, that's an idea tough I'm not fond of using e1000, which is not the recommended device for ages on VMWare. Thanks @jreagan00, the work around worked for me.

As for the issue, I guess I'll leave it open if a dev wanna fix it.

**Comment by SwampDragons** [comment]
I'm able to get a build to work on esxi 6.5 with a virtualDev vmxnet3; Since you were able to work around with a different driver, I think this may be an issue with specific configuration rather than with Packer, so I'm going to close for now. If someone has this issue crop up again, we can try to investigate more closely.
