### ISSUE TITLE
Feature request: Oracle OCI Segment Build Instance And Resulting Image OCID

### ISSUE THREAD

**Issue by shaunofneuron** [hashicorp/packer#6844]
Currently there is one parameter for the OCI builder `compartment_ocid` that drives both the location of a build instance  and where the resulting image artifact will reside.  Without the ability to copy/migrate images to other compartments, I think this feature would make sense.  Looking for feedback, I make no assumptions on how this could play out parameter/naming/options wise.

**Comment by scross01** [comment]
I'd propose adding an optional `image_compartment_ocid` parameter to designate the target compartment for the image.  `compartment_ocid` would be continue to be used for the build instance.  `image_compartment_ocid` would default to the compartment id if not set for backward compatibility.
