### ISSUE TITLE
qemu builder fails to build your example template

### ISSUE THREAD

**Issue by cipy** [hashicorp/packer#6850]
Hi there,

I'm trying to build an simple CentOS image with

- Packer version from `1.3.1`
- Host platform CentOS

And so far after the CentOS installs and restarts, the QEMU stops too, hence triggering SSH connection timeout.

I'm using your example from https://www.packer.io/docs/builders/qemu.html
and kickstart from https://gist.github.com/mitchellh/7328271/#file-centos6-ks-cfg

Thanks,

--snip--

> 2018/10/15 12:49:24 packer: 2018/10/15 12:49:24 [DEBUG] TCP connection to SSH ip/port failed: dial tcp 127.0.0.1:2224: connect: connection refused
> 2018/10/15 12:49:29 packer: 2018/10/15 12:49:29 [DEBUG] TCP connection to SSH ip/port failed: dial tcp 127.0.0.1:2224: connect: connection refused
> ==> qemu: Timeout waiting for SSH.
> 2018/10/15 12:49:33 ui error: ==> qemu: Timeout waiting for SSH.
> 2018/10/15 12:49:33 packer: 2018/10/15 12:49:33 [DEBUG] SSH wait cancelled. Exiting loop.
> ==> qemu: Deleting output directory...
> 2018/10/15 12:49:34 [INFO] (telemetry) ending qemu
> Build 'qemu' errored: Timeout waiting for SSH.
> 
> ==> Some builds didn't complete successfully and had errors:
> 2018/10/15 12:49:34 ui error: Build 'qemu' errored: Timeout waiting for SSH.
> 2018/10/15 12:49:34 Builds completed. Waiting on interrupt barrier...
> 2018/10/15 12:49:34 machine readable: error-count []string{"1"}
> 2018/10/15 12:49:34 ui error: 
> ==> Some builds didn't complete successfully and had errors:
> 2018/10/15 12:49:34 machine readable: qemu,error []string{"Timeout waiting for SSH."}
> --> qemu: Timeout waiting for SSH.
> 2018/10/15 12:49:34 ui error: --> qemu: Timeout waiting for SSH.
> 
> ==> Builds finished but no artifacts were created.
> ==> Builds finished but no artifacts were created.
> 2018/10/15 12:49:34 [INFO] (telemetry) Finalizing.
> 2018/10/15 12:49:35 waiting for all plugin processes to complete...
> 2018/10/15 12:49:35 /opt/packer/bin/packer: plugin process exited
>

**Comment by SwampDragons** [comment]
Have you tried increasing the timeout?  Changing the kickstart will change the amount of time it takes for SSH to be ready.

**Comment by cipy** [comment]
Yes, SSH time-out is set now at 10m

But the new CentOS install reboots at about the 9m mark and qemu quits with
it too

**Comment by cipy** [comment]
The image/qemu never comes back

**Comment by SwampDragons** [comment]
This doesn't sound like a Packer bug. this sounds like an issue with compatibility between Qemu and Centos.

**Comment by SwampDragons** [comment]
I recommend looking online for a working qemu+centos config, getting it to build, and modifying it from there. If you have more problems, reach out to the [mailing list](https://groups.google.com/d/forum/packer-tool) for help getting started.

**Comment by cipy** [comment]
But is it packer booting again the new image? Or qemu shouldn't quit while
under packer management?

**Comment by rickard-von-essen** [comment]
I tested it, there are a few thing's. I think actually we should remove it since we don't have any complete examples for other builders, and they tend to rot over time (for example the mirror these references don't seems to exist anymore).

My suggestion is to cut down the example and to something similar we have for [virtualbox-iso](https://www.packer.io/docs/builders/virtualbox-iso.html).

For people that want full working examples it's better to point at something that is actually used like [bento](https://github.com/chef/bento).

**Comment by SwampDragons** [comment]
Packer isn't in control of any image launch except for the first. If your kickstart file is causing a shutdown and QEMU isn't staying connected, Packer can't recover from that. That said, I can reproduce using the kickstart provided in our docs so I'll see if I can ask around and see if anyone knows what's going on.

>And lastly, aren’t you(r company) supposed to mantain the qemu provider?

Actually, no. It's popular enough we keep it in the main Packer repo, but the qemu builder is community-supported, which means that HashiCorp doesn't generally dedicate developer resources active development. We review PRs and give advice, but that's about it.

For a full list of plugins maintained by HashiCorp, see https://www.packer.io/community-plugins.html

**Comment by SwampDragons** [comment]
@rickard-von-essen good point.  I'll make a PR to slim down the example.

**Comment by SwampDragons** [comment]
@cipy You're right, the example is bad. I'm working on modifying the docs right now to something that makes fewer guarantees. But this is the wrong place to ask for further help troubleshooting. I believe Rickard has already pointed you to the mailing list. Please use it, or use a template from the [Bento project](https://github.com/chef/bento/blob/master/centos/centos-6.10-x86_64.json) Rickard already shared above and see if your issues still exist.

I know this probably seems arbitrary to you but it isn't for the maintainers; we use GitHub issue to track work that needs to be done, and we use the mailing list for support and help with users getting started. It helps us stay focused and gives community members a chance to help each other with configuration files even if they aren't comfortable with the code of the project itself.
