### ISSUE TITLE
virtualbox-ovf: Timeout waiting for SSH

### ISSUE THREAD

**Issue by hansman** [hashicorp/packer#6853]
- packer version 1.3.1
- host platform: circleci machine running circleci/classic:latest
- guest image: ubuntu server 18 64 packaged as .ova 
- debug log (includes instructions)
[packer-debug.txt](https://github.com/hashicorp/packer/files/2480136/packer-debug.txt)

- template.json

```
{
  "variables": {
    "SSH_PASSWORD": "{{env `UBUNTU_PASSWORD`}}"
  },
  "builders": [
    {
      "type": "virtualbox-ovf",
      "source_path": "file:///home/circleci/bin/ubuntu-server-18.ova",
      "ssh_username": "myuser",
      "ssh_password": "{{user `SSH_PASSWORD`}}",
      "ssh_timeout": "2m",
      "shutdown_command": "echo 'packer' | sudo -S shutdown -P now"
    }
  ],
  "provisioners": [
    {
      "type": "shell",
      "script": "packer/setup.sh" // a hello world script
    }
  ]
}
```

**Comment by SwampDragons** [comment]
Hey there, timeouts waiting for SSH/WinRM are generally not bugs within packer and are better addressed by the [mailing list](https://groups.google.com/forum/#!forum/packer-tool).  Try asking there first, especially if you're trying to get Packer working for the first time.

**Comment by hansman** [comment]
Sure, I created the mailing list topic accordingly.
