### ISSUE TITLE
qemu builder fails to build your example template (still)

### ISSUE THREAD

**Issue by cipy** [hashicorp/packer#6857]
Anybody interested in actually troubleshooting **and** fixing this? **Thanks!**

I'm trying to build an simple CentOS image with

    Packer version from 1.3.1
    Host platform CentOS 7.5.1804

And so far after the CentOS installs and restarts the VM, the QEMU stops too.

I'm using your example from https://www.packer.io/docs/builders/qemu.html
and the kickstart you link from https://gist.github.com/mitchellh/7328271/#file-centos6-ks-cfg

```
2018/10/16 12:59:03 packer: 2018/10/16 12:59:03 [INFO] Attempting SSH connection...
2018/10/16 12:59:03 packer: 2018/10/16 12:59:03 [DEBUG] reconnecting to TCP connection for SSH
2018/10/16 12:59:03 packer: 2018/10/16 12:59:03 [DEBUG] handshaking with SSH
2018/10/16 12:59:03 packer: 2018/10/16 12:59:03 [DEBUG] SSH handshake err: ssh: handshake failed: read tcp 127.0.0.1:39806->127.0.0.1:2224: read: connection reset by peer
2018/10/16 12:59:10 packer: 2018/10/16 12:59:10 [DEBUG] TCP connection to SSH ip/port failed: dial tcp 127.0.0.1:2224: connect: connection refused
...
2018/10/16 13:03:20 packer: 2018/10/16 13:03:20 [DEBUG] TCP connection to SSH ip/port failed: dial tcp 127.0.0.1:2224: connect: connection refused
==> qemu: Timeout waiting for SSH.
2018/10/16 13:03:22 ui error: ==> qemu: Timeout waiting for SSH.
2018/10/16 13:03:22 packer: 2018/10/16 13:03:22 [DEBUG] SSH wait cancelled. Exiting loop.
==> qemu: Deleting output directory...
Build 'qemu' errored: Timeout waiting for SSH.

==> Some builds didn't complete successfully and had errors:
--> qemu: Timeout waiting for SSH.

==> Builds finished but no artifacts were created.
2018/10/16 13:03:22 [INFO] (telemetry) ending qemu
2018/10/16 13:03:22 ui error: Build 'qemu' errored: Timeout waiting for SSH.
2018/10/16 13:03:22 Builds completed. Waiting on interrupt barrier...
2018/10/16 13:03:22 machine readable: error-count []string{"1"}
2018/10/16 13:03:22 ui error: 
==> Some builds didn't complete successfully and had errors:
2018/10/16 13:03:22 machine readable: qemu,error []string{"Timeout waiting for SSH."}
2018/10/16 13:03:22 ui error: --> qemu: Timeout waiting for SSH.
==> Builds finished but no artifacts were created.
2018/10/16 13:03:22 [INFO] (telemetry) Finalizing.
2018/10/16 13:03:24 waiting for all plugin processes to complete...
2018/10/16 13:03:24 /opt/packer/bin/packer: plugin process exited
```

**Comment by rickard-von-essen** [comment]
You seems to have skipped this part of the `virtualbox-iso` docs:

> Here is a basic example. This example is not functional. It will start the OS installer but then fail because we don't provide the preseed file for Ubuntu to self-install.

**Comment by rickard-von-essen** [comment]
Please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._

**Comment by cipy** [comment]
Hi there,

I adapted your example to CentOS 7, but outcome is the same as for Qemu

**Comment by rickard-von-essen** [comment]
Just tested the `centos-6.10-x86_64` template from bento, and it worked as expected for me, the only change I did was setting `accelerator: hvf` since I'm on macOS. If you drop a mail to the mailing list you will get help to get started.

**Comment by cipy** [comment]
Hi there,

If you could quote / paste here the link to this bento template you used, that would be great!

Thanks! :+1:

**Comment by rickard-von-essen** [comment]
[mailing list](https://groups.google.com/group/packer-tool)
