### ISSUE TITLE
Please give error message for invalid Vagrant Cloud token

### ISSUE THREAD

**Issue by jmcgeheeiv** [hashicorp/packer#6866]
When `access_token` nor environment variables `VAGRANT_CLOUD_TOKEN` nor `ATLAS_TOKEN` are defined, the Vagrant Cloud post-processor gives the correct error message:
```
access_token must be set
```
While it might be nice if the above error message mentioned `VAGRANT_CLOUD_TOKEN` or `ATLAS_TOKEN`, it's fine.

However, there are other erroneous situations where Packer does not indicate the problem:
* I defined `VAGRANT_CLOUD_TOKEN` but there was actually no token at all in my account
* I  defined `VAGRANT_CLOUD_TOKEN` but I changed the token value to make it incorrect

These authentication problems are not mentioned in the Packer output:
```
==> virtualbox-iso: Running post-processor: vagrant-cloud
==> virtualbox-iso (vagrant-cloud): Verifying box is accessible: jmcgeheeiv/ubuntu1804
    virtualbox-iso (vagrant-cloud): Box accessible and matches tag
==> virtualbox-iso (vagrant-cloud): Creating version: 1.0.6
Build 'virtualbox-iso' errored: 1 error(s) occurred:

* Post-processor failed: Error creating version: 

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: 1 error(s) occurred:

* Post-processor failed: Error creating version: 

==> Builds finished but no artifacts were created.
```

In the above situations where an invalid Vagrant Cloud token is given, please print an error message like:
```
The Vagrant Cloud token provided in environment variable VAGRANT_CLOUD_TOKEN is invalid.
```
## Background

- Packer v1.3.1
- Host platform Ubuntu 16.04
- The debug log output in [Gist jmcgeheeiv/hashicorp_packer_6866](https://gist.github.com/jmcgeheeiv/1e32ef6c67a09fc1108de13da2da525e)  does show that Vagrant Cloud responded `Status:401 Unauthorized StatusCode:401`.
- The template file appears in the above Gist.

**Comment by azr** [comment]
Hey @jmcgeheeiv,

on your first error `access_token must be set` is an error that happens during validation. It happens when you have: 
```json
"variables": {
    "access_token": null
```
to quote [usage](https://www.packer.io/docs/templates/user-variables.html#usage) doc.
> If the default value is null, then the user variable will be required. This means that the user must specify a value for this variable or template validation will fail.

this is a nice feature to make sure buildfile users set it before spending time on building; they can fix it for example by running `packer -var access_token=foo`

____

For your second issue I agree that we should probably check wether the given credentials will work or not before trying to run a build, like we do for other builders.

**Comment by jmcgeheeiv** [comment]
Thank you for your quick response.  I edited my initial problem statement to make it clearer that I have no particular complaint about the `access_token must be set` message.

This issue is solely about the absence of a message telling the user when the token is _invalid_.

**Comment by azr** [comment]
Sure, 🙂
I don't think we can validate the token this way, or we would have to import and maintain vagrant's token validation, which I don't think is the best choice.

I think trying to see wether the connection works is is a much more complete and simple test.
