### ISSUE TITLE
packer build does not start

### ISSUE THREAD

**Issue by riponbanik** [hashicorp/packer#6867]
Packer build does not start for hyperv-iso, vmware-iso and vsphere-iso - fails with the log below. I have tested with other versions as well - 1.1.0, 1.3.0 

- Packer version from `packer version`
0.12.2

- Host platform
Windows 10

- Debug log output from `PACKER_LOG=1 packer build template.json`.

2018/10/17 11:36:24 Packer config: &{DisableCheckpoint:false DisableCheckpointSignature:false PluginMinPort:10000 PluginMaxPort:25000 Builders:map[vmware-vmx:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-builder-vmware-vmx vsphere-iso:c:\tools\packer\0.12.2\packer-builder-vsphere-iso.exe cloudstack:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-builder-cloudstack docker:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-builder-docker googlecompute:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-builder-googlecompute parallels-pvm:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-builder-parallels-pvm amazon-instance:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-builder-amazon-instance null:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-builder-null parallels-iso:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-builder-parallels-iso virtualbox-ovf:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-builder-virtualbox-ovf file:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-builder-file digitalocean:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-builder-digitalocean amazon-chroot:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-builder-amazon-chroot amazon-ebsvolume:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-builder-amazon-ebsvolume azure-arm:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-builder-azure-arm vmware-iso:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-builder-vmware-iso openstack:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-builder-openstack amazon-ebs:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-builder-amazon-ebs triton:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-builder-triton profitbricks:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-builder-profitbricks virtualbox-iso:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-builder-virtualbox-iso oneandone:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-builder-oneandone qemu:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-builder-qemu hyperv-iso:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-builder-hyperv-iso] PostProcessors:map[docker-save:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-docker-save shell-local:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-shell-local docker-import:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-docker-import amazon-import:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-amazon-import docker-tag:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-docker-tag googlecompute-export:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-googlecompute-export artifice:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-artifice docker-push:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-docker-push atlas:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-atlas manifest:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-manifest checksum:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-checksum compress:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-compress vagrant-cloud:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-vagrant-cloud vagrant:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-vagrant vsphere:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-vsphere] Provisioners:map[windows-shell:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-windows-shell ansible-local:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-ansible-local chef-solo:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-chef-solo windows-restart:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-windows-restart ansible:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-ansible converge:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-converge shell-local:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-shell-local puppet-masterless:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-puppet-masterless puppet-server:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-puppet-server shell:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-shell salt-masterless:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-salt-masterless powershell:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-powershell file:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-file chef-client:c:\tools\packer\0.12.2\packer.exe-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-chef-client]}
2018/10/17 11:36:24 Setting cache directory: C:\Workspace\tcorp\automation\packer-build\packer_cache
2018/10/17 11:36:24 ui:
2018/10/17 11:36:24 Build debug mode: false
2018/10/17 11:36:24 Force build: false
2018/10/17 11:36:24 On error:
2018/10/17 11:36:24 Waiting on builds to complete...
2018/10/17 11:36:24 Builds completed. Waiting on interrupt barrier...
2018/10/17 11:36:24 ui:
==> Builds finished but no artifacts were created.
2018/10/17 11:36:24 waiting for all plugin processes to complete...

==> Builds finished but no artifacts were created.

**Comment by riponbanik** [comment]
@rickard-von-essen should through some errors instead of Builds completed

**Comment by rickard-von-essen** [comment]
No, it filters your builds on the name. 0 matches is ok IMHO.
