### ISSUE TITLE
Add CI service OpenLab

### ISSUE THREAD

**Issue by mrhillsman** [hashicorp/packer#6874]
Good day. I work with a project called [OpenLab](https://openlabtesting.org) which I can explain most simply as free resources to perform various testing. Our primary goal is to establish baseline information/detail/reports for others to consume and understand about stacks of open source projects working together for a specific use case/industry/technology; LAMP is a good example of this.

We have been working to get more visibility and integration of open source projects with OpenStack in particular for the past year and have done quite well. In particular interest is our work with Kubernetes which has led us to provide CI for gophercloud, terraform (OpenStack provider), kubernetes (cloud-provider-openstack and cluster-api-provider-openstack).

We are interested in doing the same for the packer community (OpenStack builder) and I am opening this issue to start that conversation. We have a few options if the community is up for this but all require installing the [GitHub App](https://github.com/apps/theopenlab-ci) which basically allows us to receive a payload for every PR. Currently we report back status of pending, failure, or success which can be used as a gate for a PR or a signal for the PR in particular and the packer release at large.

**Comment by azr** [comment]
Hello @mrhillsman,
I would **love** to have integration testing of the packer OpenStack builder.

I'm feeling too new to make that call on my own but I'll pass the info around; I think it would be very valuable to packer !

In the meantime, it would be nice to have usage examples; I found only this [terraform-provider-openstack/.zuul.yaml](https://github.com/terraform-providers/terraform-provider-openstack/blob/master/.zuul.yaml) file, which seems to be doing this; but I didn't really understand.

Also I was wondering who would do the PR for this.

**Comment by mrhillsman** [comment]
Hey @azr thanks for the quick feedback. We have created some jobs for packer as well that run against devstack [here](https://github.com/theopenlab/openlab-zuul-jobs/blob/master/playbooks/packer-functional-devstack/run.yaml) and we have OpenStack based public clouds allowing us to run packer jobs which we have [here](https://github.com/theopenlab/openlab-zuul-jobs/blob/master/playbooks/packer-functional-public-clouds/run.yaml). Of course much more can be done being that we use Ansible under the hood which offers a lot of flexibility in job definition.

**Comment by SwampDragons** [comment]
Hi @mrhillsman,

First of all, thanks for the offer!

HashiCorp has a fairly nascent internal tools team that is working on a unified CI pipeline for all of our various projects. I spoke to them about this, and they've already settled on a CI provider. If you're offering an OpenStack platform that we could run builds against from our own CI service via a cloud token, we'd be interested in that, but we don't want to change CI platforms out from under our infrastructure team, and we don't want to set up an entirely separate GitHub integration for OpenStack than we're going to set up for our other builders.  HashiCorp is pretty particular about adding GitHub apps to our projects, even our OSS ones, so I don't think we're going to be able to integrate with you in that manner.

Thanks again for reaching out, though!

Megan

**Comment by mrhillsman** [comment]
Hi @SwampDragons 

Thanks for the response. If the team based on their knowledge and roadmap of the project determine at some point our offer makes sense please let us know.
