### ISSUE TITLE
shell-local post-processor fails for command that includes comma

### ISSUE THREAD

**Issue by vikramhansawat** [hashicorp/packer#6875]
FOR BUGS:

Describe the problem and include the following information:

- Packer version from `packer version`
Packer v1.3.1

- Host platform
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Template, kickstart ad the log files are available in this gist.

https://gist.github.com/vikramhansawat/b06e73b46e42c6e60fa294ac4b6b9c04

**Comment by rickard-von-essen** [comment]
You are missing a set of `[ ]` surrounding the `inline` command. It takes a array of strings. When packer expects an array but gets a string it splits it on `, `.

**Comment by vikramhansawat** [comment]
Thanks for quick response.
