### ISSUE TITLE
Error "MissingRegion: could not find region configuration"  for amazon-ebs builder

### ISSUE THREAD

**Issue by niusmallnan** [hashicorp/packer#6883]
Packer version: v1.3.2-dev

Packer builder: amazon-ebs 

AWS authentication: Environment variables
```
$ export AWS_ACCESS_KEY_ID="anaccesskey"
$ export AWS_SECRET_ACCESS_KEY="asecretkey"
```

Debug log output from `PACKER_LOG=1 packer build template.json`:
```
2018/10/19 03:43:20 Build 'amazon-ebs-ecs' prepare failure: 3 error(s) occurred:
3 error(s) occurred:


* error validating region: MissingRegion: could not find region configuration
* error validating region: MissingRegion: could not find region configuration
* error validating region: MissingRegion: could not find region configuration
* error validating region: MissingRegion: could not find region configuration
* error validating region: MissingRegion: could not find region configuration
* error validating region: MissingRegion: could not find region configuration
2018/10/19 03:43:20 ui error: 3 error(s) occurred:

* error validating region: MissingRegion: could not find region configuration
* error validating region: MissingRegion: could not find region configuration
* error validating region: MissingRegion: could not find region configuration
```

**Comment by SwampDragons** [comment]
@niusmallnan have you figured this out? We can't help without further information.

**Comment by niusmallnan** [comment]
The template: https://gist.github.com/niusmallnan/93cfd5b1ca8ce45f8a88119c42ae1f65

I just run this command:
```
AWS_ACCESS_KEY_ID=xxx AWS_SECRET_ACCESS_KEY=xxx packer build <that-template>
```

If I roll back packer to v1.3.1, there is no problem.
It seems to be a problem caused by the recent upgrade of the AWS SDK in packer.

**Comment by nickmccally** [comment]
I am experiencing the same issue with the latest version of packer

**Comment by niusmallnan** [comment]
Here is the log: https://gist.github.com/niusmallnan/94d52bb71534b6002482dee88a9d5d59

**Comment by nickmccally** [comment]
Fyi reverting to 1.3.1 worked successfully for me too, so it was not just a typo on your behalf.

**Comment by SwampDragons** [comment]
Does this build work for you?

linux build: 
[packer.zip](https://github.com/hashicorp/packer/files/2512427/packer.zip)


osx build: 
[packer.zip](https://github.com/hashicorp/packer/files/2512430/packer.zip)

**Comment by nickmccally** [comment]
Thank you @swampdragons
