### ISSUE TITLE
Multiple powershell provisioners fail

### ISSUE THREAD

**Issue by Pondidum** [hashicorp/packer#6884]
## Summary:
* Intermittent issue, although this repro _usually_ causes it to fail
* Changing the PATH environment variable inside a windows ami via a powershell provisioner causes subsequent powershell provisioners to fail
* Running this as one script doesn't cause failures
* I checked the contents of the PATH before and after changing it
```
amazon-ebs: current Path:
amazon-ebs: C:\Program Files\Microsoft MPI\Bin\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Program Files\Amazon\cfn-bootstrap\;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps
amazon-ebs: New Path:
amazon-ebs: C:\Program Files\Microsoft MPI\Bin\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Program Files\Amazon\cfn-bootstrap\;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;C:\ProgramData\npm;C:\Program Files\nodejs;%JAVA_HOME%\bin
```
* Packer version: `1.3.1`
* Host platform: `Windows 10, Build 1607`
* Debug log output from `PACKER_LOG=1 packer build template.json` : [gist](https://gist.github.com/Pondidum/c231c9065314fb017a2fb33920c17e3c)

Interesting log output indicates packer can no longer find powershell.exe:

```
2018/10/18 14:35:29 [INFO] (telemetry) Starting provisioner powershell
2018/10/18 14:35:29 ui: ==> amazon-ebs: Provisioning with Powershell...
2018/10/18 14:35:29 ui: ==> amazon-ebs: Provisioning with powershell script: ./scripts/configureLocale.ps1
2018/10/18 14:35:29 packer.exe: 2018/10/18 14:35:29 Opening ./scripts/configureLocale.ps1 for reading
2018/10/18 14:35:29 packer.exe: 2018/10/18 14:35:29 Uploading env vars to c:/Windows/Temp/packer-ps-env-vars-5bc86ef3-3f2f-4d03-b7bb-dcde078b6775.ps1
2018/10/18 14:35:29 packer.exe: 2018/10/18 14:35:29 [INFO] 76 bytes written for 'uploadData'
2018/10/18 14:35:29 [INFO] 76 bytes written for 'uploadData'
2018/10/18 14:35:29 packer.exe: 2018/10/18 14:35:29 Uploading file to 'c:/Windows/Temp/packer-ps-env-vars-5bc86ef3-3f2f-4d03-b7bb-dcde078b6775.ps1'
2018/10/18 14:35:30 packer.exe: 'powershell.exe' is not recognized as an internal or external command,
2018/10/18 14:35:30 packer.exe: operable program or batch file.
```

template.json:
```json
{
  "variables": {
    "aws_access_key": "{{env `AWS_TEST_ACCESS`}}",
    "aws_secret_key": "{{env `AWS_TEST_SECRET`}}"
  },
  "builders": [
    {
      "type": "amazon-ebs",
      "access_key": "{{user `aws_access_key`}}",
      "secret_key": "{{user `aws_secret_key`}}",

      "communicator": "winrm",
      "winrm_port": 443,
      "winrm_username": "Administrator",
      "winrm_use_ssl": true,
      "winrm_insecure": true,

      "associate_public_ip_address": true,
      "vpc_id": "vpc-1f12cc78",
      "subnet_id": "subnet-6c35e80b",

      "region": "eu-west-1",
      "instance_type": "t2.medium",
      "ami_name": "core-teamcity-agent {{timestamp}}",
      "user_data_file": "./winrm.ps1",
      "launch_block_device_mappings": [
        {
          "device_name": "/dev/sda1",
          "volume_size": 60,
          "volume_type": "gp2",
          "delete_on_termination": true
        }
      ],

      "source_ami_filter": {
        "filters": {
          "virtualization-type": "hvm",
          "name": "Windows_Server-2016-English-Full-SQL_2017_Express*",
          "root-device-type": "ebs"
        },
        "owners": ["amazon"],
        "most_recent": true
      }
    }
  ],
  "provisioners": [
    { "type": "powershell", "script": "./scripts/configureEnvironment.ps1" },
    { "type": "powershell", "script": "./scripts/configureLocale.ps1" },
    {
      "type": "powershell",
      "inline": [
        "C:/ProgramData/Amazon/EC2-Windows/Launch/Scripts/InitializeInstance.ps1 -Schedule",
        "C:/ProgramData/Amazon/EC2-Windows/Launch/Scripts/SysprepInstance.ps1 -NoShutdown"
      ]
    }
  ]
}
```

configureEnvironment.ps1:
```powershell
$newPath = @(
    "$env:Path",
    "C:\It\doesnt\matter"
) -join ";"

Set-ItemProperty `
    -Path 'Registry::HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\Environment' `
    -Name PATH `
    -Value "$newPath"
```

configureLocale.ps1:
```powershell
Write-host "Second Script"
Write-host "$env:Path"
```

**Comment by SwampDragons** [comment]
It looks to me like %JAVA_HOME% isn't being properly expanded in your %PATH% variable; this may be making your path invalid and causing your issues finding powershell.  Are you sure %JAVA_HOME% is defined?  What happens if you hardcode that part instead of using a variable?

**Comment by Pondidum** [comment]
Changing what I am adding into the path doesn't make a difference as to whether this causes the 2nd powershell provisioner to succeed or fail (and not sure why the `%JAVA_HOME%` would matter for losing the powershell exe - I although I had been worried I was replacing the entire path with just my additions, rather than appending them!)

Also, it doesn't seem to make a difference if I use one powershell provisioner with multiple scripts in the `scripts: []` array, or multiple provisioners with one script per provisioner.

**Comment by SwampDragons** [comment]
> Changing what I am adding into the path doesn't make a difference as to whether this causes the 2nd powershell provisioner to succeed or fail

I'm confused. I thought in your initial problem statement that's what you said was causing this. 

What paths have you tried?

**Comment by Pondidum** [comment]
Hey,

The issue seems to be not what is changed in the PATH, but that the PATH was changed at all, e.g. just appending ";c:\bin" would affect this.
The real issue I am having is that it doesn't happen often, but seems to happen more with a long-running set of scripts (e.g. my first provisioner takes ~20 minutes, the other 4 are fairly quick), which makes capturing the output and making a minimal reproduction hard.

I've had it happen on a two-script provisioning where the first script just appends a new directory to the path, and the second script just writes a file (not reliant on anything external), and the log had the same output as the log in the attached gist:

```
2018/10/18 14:35:30 packer.exe: 'powershell.exe' is not recognized as an internal or external command,
2018/10/18 14:35:30 packer.exe: operable program or batch file.
```

I think I can work around it by overriding the provisioner's `execute_command` to use the full path to `powershell.exe`, but that doesn't seem quite ideal.

**Comment by Pondidum** [comment]
I've updated the original post with the more minimal script I have been using to get reproductions.  Hopefully it'll appear again soon and I can get another log file uploaded.

**Comment by SwampDragons** [comment]
So what this looks like to me is that sometimes your script is changing the contents of the system path, and if that path becomes invalid or unparsable by windows, then it breaks things. This doesn't seem like a Packer problem to me; Packer doesn't change the path or make any expectations about it except that powershell.exe is on that path, which I think is a very reasonable assumption.

**Comment by Pondidum** [comment]
I guess that must be it - very weird as the script (shouldn't) do anything different on each run.
I have this setup with packer logging on every run now, so if I get a run where it fails and has some useful output as to what happens, I'll update this as appropriate.

Closing for now, thanks for the help.
