### ISSUE TITLE
Erroneous box format after packaging

### ISSUE THREAD

**Issue by pkaramol** [hashicorp/packer#6886]
# Documentation Issue

Although the [documentation](https://www.vagrantup.com/docs/boxes/format.html) explicitly states that:

> Box File - This is a compressed (tar, tar.gz, zip) file that is specific to a single provider and can contain anything. Vagrant core does not ever use the contents of this file. Instead, they are passed to the provider. Therefore, a VirtualBox box file has different contents from a VMware box file and so on.

this does not seem to be the case;

I followed these steps:

```
- vagrant destroy -f && vagrant up --provider virtualbox
- vagrant halt
- vagrant package --output my_vm.box

```

```
$ unzip /home/pkara/Desktop/mdr-deployment/.vagrant/machines/default/my_vm.box -d /datastore
Archive:  /home/pkara/Desktop/mdr-deployment/.vagrant/machines/default/my_vm.box
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /home/pkara/Desktop/mdr-deployment/.vagrant/machines/default/my_vm.box or
        /home/pkara/Desktop/mdr-deployment/.vagrant/machines/default/my_vm.box.zip, and cannot find /home/pkara/Desktop/mdr-deployment/.vagrant/machines/default/my_vm.box.ZIP, period.
```

```
tar -xzvf /home/pkara/Desktop/mdr-deployment/.vagrant/machines/default/my_vm.box -C /datastore
tar: Ignoring unknown extended header keyword 'SCHILY.fflags'
./vagrant_private_key
tar: Ignoring unknown extended header keyword 'SCHILY.fflags'
./box-disk002.vmdk
tar: Ignoring unknown extended header keyword 'SCHILY.fflags'
./box.ovf
tar: Ignoring unknown extended header keyword 'SCHILY.fflags'
./box-disk001.vmdk

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```

**Comment by rickard-von-essen** [comment]
So far this seems only relevant to Vagrant?

**Comment by pkaramol** [comment]
@rickard-von-essen  I haven't had any issues decompressing any other files if that's what you mean;

If any of the above steps I followed is wrong or sth is missing in order to be able to produce a file which is in a valid `.zip` or `.tar.gz` format pls let me know;

**Comment by rickard-von-essen** [comment]
I don't see how this relates to [Packer](https://packer.io). If I misunderstand anything please try to explain more in details.
