### ISSUE TITLE
creating windows gcp machine is failing because packer is unable to clean 

### ISSUE THREAD

**Issue by mthegreat83** [hashicorp/packer#6887]
- Packer version from `packer version`
1.3.1

we are trying to use packer to create a very simple Google compute windows machine, we are getting a very weird behavior, the image get created and we see it in the project list of images, however the packer build falls into error because it is unable to delete its own disk

```
[1;32m==> googlecompute: Deleting instance...[0m
[0;32m    googlecompute: Instance has been deleted![0m
[1;32m==> googlecompute: Creating image...[0m
[1;31m==> googlecompute: Error waiting for image: time out while waiting for image to register[0m
[1;32m==> googlecompute: Deleting disk...[0m
[1;31m==> googlecompute: Error deleting disk. Please delete it manually.
==> googlecompute: 
==> googlecompute: DiskName: packer-5bc9e11d-3dbc-5a7b-f3ac-da3a0b062628
==> googlecompute: Zone: us-east1-b
==> googlecompute: Error: googleapi: Error 400: The disk resource 'projects/development/zones/us-east1-c/disks/packer-5bc9e11d-3dbc-5a7b-f3ac-da3a0b062628' is already being used by 'projects/development/global/images/image12', resourceInUseByAnotherResource[0m
[0;32m    googlecompute: Disk has been deleted![0m
[1;31mBuild 'googlecompute' errored: Error waiting for image: time out while waiting for image to register[0m

==> Some builds didn't complete successfully and had errors:
--> googlecompute: Error waiting for image: time out while waiting for image to register

==> Builds finished but no artifacts were created.
```

the json file we are using if very simple as you can see below

```json
{
    "variables": {
         "service_account_json": "development-57b471cc526e.json"
     },
"builders": [
        {
           "type": "googlecompute",
           "project_id": "development",
           "machine_type": "n1-standard-2",
           "source_image_family": "windows-2016",
           "region": "us-east1",
           "zone": "us-east1-c",
           "image_description": "devmachine",
           "image_name": "image12",
           "image_family": "dev-machines",
           "disk_size": 50,
           "communicator": "winrm",
           "winrm_username": "deployer",
           "winrm_insecure": true,
           "winrm_use_ssl": true,
           "metadata": {
             "windows-startup-script-cmd": "winrm quickconfig -quiet & net user /add deployer & net localgroup administrators deployer /add & winrm set winrm/config/service/auth @{Basic=\"true\"}"
           },		
           "account_file":"development-57b471cc526e.json"
        }
     ]
}
```

**Comment by rickard-von-essen** [comment]
Please [gist](https://gist.github.com/) a full debug log from `PACKER_LOG=1 packer build template.json`.

**Comment by mthegreat83** [comment]
here is the debug output


2018/10/19 16:13:30 [INFO] Packer version: 1.3.1
2018/10/19 16:13:30 Packer Target OS/Arch: linux amd64
2018/10/19 16:13:30 Built with Go Version: go1.11
2018/10/19 16:13:30 Detected home directory from env var: /user/dev
2018/10/19 16:13:30 Using internal plugin for googlecompute
2018/10/19 16:13:30 Using internal plugin for ncloud
2018/10/19 16:13:30 Using internal plugin for parallels-pvm
2018/10/19 16:13:30 Using internal plugin for azure-arm
2018/10/19 16:13:30 Using internal plugin for lxc
2018/10/19 16:13:30 Using internal plugin for lxd
2018/10/19 16:13:30 Using internal plugin for null
2018/10/19 16:13:30 Using internal plugin for vmware-vmx
2018/10/19 16:13:30 Using internal plugin for parallels-iso
2018/10/19 16:13:30 Using internal plugin for qemu
2018/10/19 16:13:30 Using internal plugin for virtualbox-iso
2018/10/19 16:13:30 Using internal plugin for amazon-chroot
2018/10/19 16:13:30 Using internal plugin for amazon-ebssurrogate
2018/10/19 16:13:30 Using internal plugin for hyperv-vmcx
2018/10/19 16:13:30 Using internal plugin for openstack
2018/10/19 16:13:30 Using internal plugin for oracle-oci
2018/10/19 16:13:30 Using internal plugin for amazon-instance
2018/10/19 16:13:30 Using internal plugin for digitalocean
2018/10/19 16:13:30 Using internal plugin for scaleway
2018/10/19 16:13:30 Using internal plugin for amazon-ebsvolume
2018/10/19 16:13:30 Using internal plugin for cloudstack
2018/10/19 16:13:30 Using internal plugin for triton
2018/10/19 16:13:30 Using internal plugin for vmware-iso
2018/10/19 16:13:30 Using internal plugin for amazon-ebs
2018/10/19 16:13:30 Using internal plugin for docker
2018/10/19 16:13:30 Using internal plugin for hyperv-iso
2018/10/19 16:13:30 Using internal plugin for oracle-classic
2018/10/19 16:13:30 Using internal plugin for virtualbox-ovf
2018/10/19 16:13:30 Using internal plugin for file
2018/10/19 16:13:30 Using internal plugin for oneandone
2018/10/19 16:13:30 Using internal plugin for profitbricks
2018/10/19 16:13:30 Using internal plugin for puppet-masterless
2018/10/19 16:13:30 Using internal plugin for puppet-server
2018/10/19 16:13:30 Using internal plugin for shell-local
2018/10/19 16:13:30 Using internal plugin for windows-shell
2018/10/19 16:13:30 Using internal plugin for ansible
2018/10/19 16:13:30 Using internal plugin for chef-solo
2018/10/19 16:13:30 Using internal plugin for converge
2018/10/19 16:13:30 Using internal plugin for file
2018/10/19 16:13:30 Using internal plugin for shell
2018/10/19 16:13:30 Using internal plugin for salt-masterless
2018/10/19 16:13:30 Using internal plugin for windows-restart
2018/10/19 16:13:30 Using internal plugin for ansible-local
2018/10/19 16:13:30 Using internal plugin for chef-client
2018/10/19 16:13:30 Using internal plugin for powershell
2018/10/19 16:13:30 Using internal plugin for docker-save
2018/10/19 16:13:30 Using internal plugin for docker-tag
2018/10/19 16:13:30 Using internal plugin for amazon-import
2018/10/19 16:13:30 Using internal plugin for manifest
2018/10/19 16:13:30 Using internal plugin for checksum
2018/10/19 16:13:30 Using internal plugin for compress
2018/10/19 16:13:30 Using internal plugin for googlecompute-export
2018/10/19 16:13:30 Using internal plugin for googlecompute-import
2018/10/19 16:13:30 Using internal plugin for vsphere-template
2018/10/19 16:13:30 Using internal plugin for alicloud-import
2018/10/19 16:13:30 Using internal plugin for docker-import
2018/10/19 16:13:30 Using internal plugin for docker-push
2018/10/19 16:13:30 Using internal plugin for shell-local
2018/10/19 16:13:30 Using internal plugin for vagrant
2018/10/19 16:13:30 Using internal plugin for vagrant-cloud
2018/10/19 16:13:30 Using internal plugin for vsphere
2018/10/19 16:13:30 Using internal plugin for artifice
2018/10/19 16:13:30 Detected home directory from env var: /user/dev
2018/10/19 16:13:30 Attempting to open config file: /user/dev/.packerconfig
2018/10/19 16:13:30 [WARN] Config file doesn't exist: /user/dev/.packerconfig
2018/10/19 16:13:30 Packer config: &{DisableCheckpoint:false DisableCheckpointSignature:false PluginMinPort:10000 PluginMaxPort:25000 Builders:map[parallels-pvm:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-parallels-pvm lxd:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-lxd null:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-null openstack:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-openstack amazon-ebs:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-amazon-ebs hyperv-iso:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-hyperv-iso amazon-chroot:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-amazon-chroot googlecompute:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-googlecompute ncloud:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-ncloud lxc:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-lxc virtualbox-iso:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-virtualbox-iso hyperv-vmcx:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-hyperv-vmcx digitalocean:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-digitalocean file:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-file vmware-iso:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-vmware-iso oracle-oci:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-oracle-oci amazon-instance:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-amazon-instance triton:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-triton alicloud-ecs:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-alicloud-ecs vmware-vmx:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-vmware-vmx qemu:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-qemu amazon-ebssurrogate:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-amazon-ebssurrogate docker:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-docker oracle-classic:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-oracle-classic profitbricks:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-profitbricks azure-arm:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-azure-arm parallels-iso:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-parallels-iso scaleway:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-scaleway amazon-ebsvolume:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-amazon-ebsvolume cloudstack:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-cloudstack virtualbox-ovf:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-virtualbox-ovf oneandone:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-oneandone] PostProcessors:map[docker-save:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-docker-save docker-tag:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-docker-tag checksum:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-checksum vsphere-template:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-vsphere-template docker-import:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-docker-import docker-push:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-docker-push shell-local:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-shell-local artifice:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-artifice compress:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-compress googlecompute-export:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-googlecompute-export amazon-import:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-amazon-import manifest:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-manifest googlecompute-import:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-googlecompute-import alicloud-import:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-alicloud-import vagrant:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-vagrant vagrant-cloud:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-vagrant-cloud vsphere:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-vsphere] Provisioners:map[puppet-masterless:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-puppet-masterless puppet-server:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-puppet-server windows-shell:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-windows-shell file:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-file ansible-local:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-ansible-local powershell:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-powershell ansible:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-ansible shell:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-shell salt-masterless:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-salt-masterless chef-client:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-chef-client shell-local:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-shell-local converge:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-converge chef-solo:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-chef-solo windows-restart:/user/dev/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-windows-restart]}
2018/10/19 16:13:30 Detected home directory from env var: /user/dev
2018/10/19 16:13:30 Setting cache directory: /opt/jenkins/workspace/google_provision_Images_packer/packer_cache
2018/10/19 16:13:30 Detected home directory from env var: /user/dev
2018/10/19 16:13:30 Loading builder: googlecompute
2018/10/19 16:13:30 Plugin could not be found. Checking same directory as executable.
2018/10/19 16:13:30 Current exe path: /user/dev/packer
2018/10/19 16:13:30 Creating plugin client for path: /user/dev/packer
2018/10/19 16:13:30 Starting plugin: /user/dev/packer []string{"/user/dev/packer", "plugin", "packer-builder-googlecompute"}
2018/10/19 16:13:30 Waiting for RPC address for: /user/dev/packer
2018/10/19 16:13:30 packer: 2018/10/19 16:13:30 [INFO] Packer version: 1.3.1
2018/10/19 16:13:30 packer: 2018/10/19 16:13:30 Packer Target OS/Arch: linux amd64
2018/10/19 16:13:30 packer: 2018/10/19 16:13:30 Built with Go Version: go1.11
2018/10/19 16:13:30 packer: 2018/10/19 16:13:30 Detected home directory from env var: /user/dev
2018/10/19 16:13:30 packer: 2018/10/19 16:13:30 Attempting to open config file: /user/dev/.packerconfig
2018/10/19 16:13:30 packer: 2018/10/19 16:13:30 [WARN] Config file doesn't exist: /user/dev/.packerconfig
2018/10/19 16:13:30 packer: 2018/10/19 16:13:30 Packer config: &{DisableCheckpoint:false DisableCheckpointSignature:false PluginMinPort:10000 PluginMaxPort:25000 Builders:map[] PostProcessors:map[] Provisioners:map[]}
2018/10/19 16:13:30 packer: 2018/10/19 16:13:30 Detected home directory from env var: /user/dev
2018/10/19 16:13:30 packer: 2018/10/19 16:13:30 Setting cache directory: /opt/jenkins/workspace/google_provision_Images_packer/packer_cache
2018/10/19 16:13:30 packer: 2018/10/19 16:13:30 args: []string{"packer-builder-googlecompute"}
2018/10/19 16:13:30 packer: 2018/10/19 16:13:30 Detected home directory from env var: /user/dev
2018/10/19 16:13:30 packer: 2018/10/19 16:13:30 Plugin minimum port: 10000
2018/10/19 16:13:30 packer: 2018/10/19 16:13:30 Plugin maximum port: 25000
2018/10/19 16:13:30 packer: 2018/10/19 16:13:30 Plugin address: unix /tmp/packer-plugin690250020
2018/10/19 16:13:30 packer: 2018/10/19 16:13:30 Waiting for connection...
2018/10/19 16:13:30 packer: 2018/10/19 16:13:30 Serving a plugin connection...
[1;32mgooglecompute output will be in this color.[0m

2018/10/19 16:13:30 Build debug mode: false
2018/10/19 16:13:30 Force build: false
2018/10/19 16:13:30 On error: 
2018/10/19 16:13:30 Preparing build: googlecompute
2018/10/19 16:13:30 Waiting on builds to complete...
2018/10/19 16:13:30 Starting build run: googlecompute
2018/10/19 16:13:30 Running builder: googlecompute
2018/10/19 16:13:30 [INFO] (telemetry) Starting builder googlecompute
2018/10/19 16:13:30 packer: 2018/10/19 16:13:30 [INFO] Requesting Google token via AccountFile...
2018/10/19 16:13:30 packer: 2018/10/19 16:13:30 [INFO]   -- Email: deployer@development.iam.gserviceaccount.com
2018/10/19 16:13:30 packer: 2018/10/19 16:13:30 [INFO]   -- Scopes: [https://www.googleapis.com/auth/compute https://www.googleapis.com/auth/devstorage.full_control]
2018/10/19 16:13:30 packer: 2018/10/19 16:13:30 [INFO]   -- Private Key Length: 1704
2018/10/19 16:13:30 packer: 2018/10/19 16:13:30 [INFO] Instantiating GCE client...
[1;32m==> googlecompute: Checking image does not exist...[0m
[1;32m==> googlecompute: Creating temporary SSH key for instance...[0m
[1;32m==> googlecompute: Using image: windows-server-2016-dc-v20181009[0m
[1;32m==> googlecompute: Creating instance...[0m
[0;32m    googlecompute: Loading zone: us-east1-c[0m
[0;32m    googlecompute: Loading machine type: n1-standard-2[0m
[0;32m    googlecompute: Requesting instance creation...[0m
[0;32m    googlecompute: Waiting for creation operation to complete...[0m
[0;32m    googlecompute: Instance has been created![0m
[1;32m==> googlecompute: Creating windows user for instance...[0m
[0;32m    googlecompute: Waiting for windows password to complete...[0m
[0;32m    googlecompute: Created password.[0m
[1;32m==> googlecompute: Waiting for the instance to become running...[0m
[0;32m    googlecompute: IP: 35.237.117.133[0m
[1;32m==> googlecompute: Using winrm communicator to connect: 35.237.117.133[0m
2018/10/19 16:14:16 packer: 2018/10/19 16:14:16 Waiting for WinRM, up to timeout: 30m0s
[1;32m==> googlecompute: Waiting for WinRM to become available...[0m
2018/10/19 16:14:21 packer: 2018/10/19 16:14:21 [INFO] Attempting WinRM connection...
2018/10/19 16:14:21 packer: 2018/10/19 16:14:21 [DEBUG] connecting to remote shell using WinRM
2018/10/19 16:14:51 packer: 2018/10/19 16:14:51 [ERROR] connection error: unknown error Post https://35.237.117.133:5986/wsman: dial tcp 35.237.117.133:5986: i/o timeout
2018/10/19 16:14:51 packer: 2018/10/19 16:14:51 [ERROR] WinRM connection err: unknown error Post https://35.237.117.133:5986/wsman: dial tcp 35.237.117.133:5986: i/o timeout
2018/10/19 16:14:56 packer: 2018/10/19 16:14:56 [INFO] Attempting WinRM connection...
2018/10/19 16:14:56 packer: 2018/10/19 16:14:56 [DEBUG] connecting to remote shell using WinRM
2018/10/19 16:15:26 packer: 2018/10/19 16:15:26 [ERROR] connection error: unknown error Post https://35.237.117.133:5986/wsman: dial tcp 35.237.117.133:5986: i/o timeout
2018/10/19 16:15:26 packer: 2018/10/19 16:15:26 [ERROR] WinRM connection err: unknown error Post https://35.237.117.133:5986/wsman: dial tcp 35.237.117.133:5986: i/o timeout
2018/10/19 16:15:31 packer: 2018/10/19 16:15:31 [INFO] Attempting WinRM connection...
2018/10/19 16:15:31 packer: 2018/10/19 16:15:31 [DEBUG] connecting to remote shell using WinRM
2018/10/19 16:15:47 packer: 2018/10/19 16:15:47 [ERROR] connection error: http response error: 401 - invalid content type
2018/10/19 16:15:47 packer: 2018/10/19 16:15:47 [ERROR] WinRM connection err: http response error: 401 - invalid content type
2018/10/19 16:15:52 packer: 2018/10/19 16:15:52 [INFO] Attempting WinRM connection...
2018/10/19 16:15:52 packer: 2018/10/19 16:15:52 [DEBUG] connecting to remote shell using WinRM
2018/10/19 16:16:00 packer: 2018/10/19 16:16:00 Checking that WinRM is connected with: 'powershell.exe -EncodedCommand aQBmACAAKABUAGUAcwB0AC0AUABhAHQAaAAgAHYAYQByAGkAYQBiAGwAZQA6AGcAbABvAGIAYQBsADoAUAByAG8AZwByAGUAcwBzAFAAcgBlAGYAZQByAGUAbgBjAGUAKQB7ACQAUAByAG8AZwByAGUAcwBzAFAAcgBlAGYAZQByAGUAbgBjAGUAPQAnAFMAaQBsAGUAbgB0AGwAeQBDAG8AbgB0AGkAbgB1AGUAJwB9ADsAIABlAGMAaABvACAAIgBXAGkAbgBSAE0AIABjAG8AbgBuAGUAYwB0AGUAZAAuACIA'
2018/10/19 16:16:00 packer: 2018/10/19 16:16:00 [INFO] starting remote command: powershell.exe -EncodedCommand aQBmACAAKABUAGUAcwB0AC0AUABhAHQAaAAgAHYAYQByAGkAYQBiAGwAZQA6AGcAbABvAGIAYQBsADoAUAByAG8AZwByAGUAcwBzAFAAcgBlAGYAZQByAGUAbgBjAGUAKQB7ACQAUAByAG8AZwByAGUAcwBzAFAAcgBlAGYAZQByAGUAbgBjAGUAPQAnAFMAaQBsAGUAbgB0AGwAeQBDAG8AbgB0AGkAbgB1AGUAJwB9ADsAIABlAGMAaABvACAAIgBXAGkAbgBSAE0AIABjAG8AbgBuAGUAYwB0AGUAZAAuACIA
[0;32m    googlecompute: WinRM connected.[0m
2018/10/19 16:16:09 packer: 2018/10/19 16:16:09 [INFO] command 'powershell.exe -EncodedCommand aQBmACAAKABUAGUAcwB0AC0AUABhAHQAaAAgAHYAYQByAGkAYQBiAGwAZQA6AGcAbABvAGIAYQBsADoAUAByAG8AZwByAGUAcwBzAFAAcgBlAGYAZQByAGUAbgBjAGUAKQB7ACQAUAByAG8AZwByAGUAcwBzAFAAcgBlAGYAZQByAGUAbgBjAGUAPQAnAFMAaQBsAGUAbgB0AGwAeQBDAG8AbgB0AGkAbgB1AGUAJwB9ADsAIABlAGMAaABvACAAIgBXAGkAbgBSAE0AIABjAG8AbgBuAGUAYwB0AGUAZAAuACIA' exited with code: 0
[0;32m    googlecompute: #< CLIXML[0m
[0;32m    googlecompute: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="1"><TNRef RefId="0" /><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>[0m
2018/10/19 16:16:09 packer: 2018/10/19 16:16:09 Connected to machine
2018/10/19 16:16:09 packer: 2018/10/19 16:16:09 Running the provision hook
[1;32m==> googlecompute: Connected to WinRM![0m
[1;32m==> googlecompute: Deleting instance...[0m
[0;32m    googlecompute: Instance has been deleted![0m
[1;32m==> googlecompute: Creating image...[0m
[1;31m==> googlecompute: Error waiting for image: time out while waiting for image to register[0m
[1;32m==> googlecompute: Deleting disk...[0m
2018/10/19 16:22:45 ui error: [1;31m==> googlecompute: Error waiting for image: time out while waiting for image to register[0m
2018/10/19 16:22:45 ui error: [1;31m==> googlecompute: Error deleting disk. Please delete it manually.
==> googlecompute: 
==> googlecompute: DiskName: packer-5bca3aea-d0a1-c318-a986-17946ecee0da
==> googlecompute: Zone: us-east1-c
==> googlecompute: Error: googleapi: Error 400: The disk resource 'projects/development/zones/us-east1-c/disks/packer-5bca3aea-d0a1-c318-a986-17946ecee0da' is already being used by 'projects/development/global/images/image14', resourceInUseByAnotherResource[0m
[1;31m==> googlecompute: Error deleting disk. Please delete it manually.
==> googlecompute: 
==> googlecompute: DiskName: packer-5bca3aea-d0a1-c318-a986-17946ecee0da
==> googlecompute: Zone: us-east1-c
==> googlecompute: Error: googleapi: Error 400: The disk resource 'projects/development/zones/us-east1-c/disks/packer-5bca3aea-d0a1-c318-a986-17946ecee0da' is already being used by 'projects/development/global/images/image14', resourceInUseByAnotherResource[0m
[0;32m    googlecompute: Disk has been deleted![0m
[1;31mBuild 'googlecompute' errored: Error waiting for image: time out while waiting for image to register[0m

==> Some builds didn't complete successfully and had errors:
--> googlecompute: Error waiting for image: time out while waiting for image to register

==> Builds finished but no artifacts were created.
2018/10/19 16:22:45 [INFO] (telemetry) ending googlecompute
2018/10/19 16:22:45 ui error: [1;31mBuild 'googlecompute' errored: Error waiting for image: time out while waiting for image to register[0m
2018/10/19 16:22:45 Builds completed. Waiting on interrupt barrier...
2018/10/19 16:22:45 machine readable: error-count []string{"1"}
2018/10/19 16:22:45 ui error: 
==> Some builds didn't complete successfully and had errors:
2018/10/19 16:22:45 machine readable: googlecompute,error []string{"Error waiting for image: time out while waiting for image to register"}
2018/10/19 16:22:45 ui error: --> googlecompute: Error waiting for image: time out while waiting for image to register
==> Builds finished but no artifacts were created.
2018/10/19 16:22:45 [INFO] (telemetry) Finalizing.
2018/10/19 16:22:45 waiting for all plugin processes to complete...
2018/10/19 16:22:45 /user/dev/packer: plugin process exited
Build step 'Execute shell' marked build as failure
Finished: FAILURE


what's odd that it saying that the disk packer-5bca3aea-d0a1-c318-a986-17946ecee0da has been deleted and no artifacts were created while in reality after the failure, I can still see the disk in the list of the disk and the image got created.

**Comment by SwampDragons** [comment]
The "Disk has been deleted!" line gets called during the [teardown step](https://github.com/hashicorp/packer/blob/master/builder/googlecompute/step_teardown_instance.go#L80) regardless of whether the step succeeds or not. This should probably be fixed.

**Comment by SwampDragons** [comment]
Looks like the default timeout is 5 minutes, configurable with the Packer template option of 
`"state_timeout": "5m"`

Just for testing's sake, happens if you increase that timeout to something a fair amount longer, like 20m? I want to make sure it isn't just something like you trying to register a huge instance and it taking longer than normal.

**Comment by Rohited3** [comment]
Hi,
I tired with state_timeout to 7 minutes and 5 minutes. it didn't work for me.

**Comment by SwampDragons** [comment]
I'm doing some issue cleanup now and I'm closing this issue since we never got more info about second poster's situation and I'm 99% sure this is a timeout that can be solved by setting `state_timeout` to a higher value just as was the OP's issue.

If people are still experiencing this no matter how high they set state_timeout, we can reopen and try to look at other causes.

**Comment by rahmanya** [comment]
> oddly enough setting the state_timeout to 7 minutes fixed the issue ! the build was successful, but I am really surprised, as I said above the instance isn't that big.

I had this same issue , in my case it was on a Linux Debian-9 image build and my stacktrace was identical to your's but as @SwampDragons suggested setting the state_timeout to 7m also worked. for me.
