### ISSUE TITLE
Expose the AWS Instance ID as a variable

### ISSUE THREAD

**Issue by bodgit** [hashicorp/packer#6894]
Similar to the existing `{{.BuildRegion}}`, `{{.SourceAMI}}` variables, would it be possible to expose the AWS instance ID as a variable for use by provisioners? Something like `{{.InstanceID}}` maybe? Specifically I would like to be able to set the `puppet_node` parameter in the Puppet Server provisioner to the instance ID.

Or are the various variables only evaluated early on before any instances have been created?

**Comment by rickard-von-essen** [comment]
In a provisioner this is available through the instance metadata, see https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html#instancedata-data-retrieval.

**Comment by bodgit** [comment]
Sure, I know how the instance metadata works. However that's not accessible by _all_ provisioners, only shell-based ones. The Puppet Server provisioner can't query it, for example, which was my use case. I was just trying to avoid having to use any shell provisioners.

**Comment by rickard-von-essen** [comment]
Something like this should work (untested):

```json
"puppet_node": "$(curl --silent http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r .instanceId)"
```
