### ISSUE TITLE
Compare-VM : Cannot validate argument on parameter 'Path'

### ISSUE THREAD

**Issue by yooakim** [hashicorp/packer#6899]
```
Packer: v1.3.1
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17763 N/A Build 17763
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
```
* [Packer log](https://gist.github.com/yooakim/d58e6619e35bae87bcb9b23848cc6a5d) 
* [Template-step-1.json](https://gist.github.com/yooakim/c39b94082fc6586c92756e6659c218ea)
* [Template-step-2.json](https://gist.github.com/yooakim/4562cae74532c0440d8805b9667ebe5e)

I am not able to use the [hyperv-vmcx builder ](https://www.packer.io/docs/builders/hyperv-vmcx.html).  I am trying to build a process that first uses the [Hyper-V ISO builder](https://www.packer.io/docs/builders/hyperv-iso.html) and the next step should use the output and run more updates etc.

I've not used the VMCX provider before so I may be doing something wrong, please let me know in that case! 

When i run my seconds step I get the error `Compare-VM : Cannot validate argument on parameter 'Path'` but the issue is that the files are there and it is when the cloning start the error is raised.

My output directory from step one looks as follows:
```
~\source\packer-templates [develop +0 ~0 -2 | +2 ~6 -2 !]> dir .\output-base\ -r


    Directory: C:\.....\source\packer-templates\output-base


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       2018-10-23     10:19                Virtual Hard Disks
d-----       2018-10-23     10:20                Virtual Machines


    Directory: C:\.....\source\packer-templates\output-base\Virtual Hard Disks


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       2018-10-23     10:19    10708058112 win2016-base-image.vhdx


    Directory: C:\.....\source\packer-templates\output-base\Virtual Machines


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       2018-10-23     10:20          45090 983A3EDE-0624-4A5C-A0BE-91FA050F68A5.vmcx
-a----       2018-10-23     10:20        4194816 983A3EDE-0624-4A5C-A0BE-91FA050F68A5.vmgs
-a----       2018-10-23     10:19          49152 983A3EDE-0624-4A5C-A0BE-91FA050F68A5.VMRS
-a----       2018-10-23     10:20           1089 box.xml
```

Any help in resolving this would be much appreciated!

**Comment by SwampDragons** [comment]
Thanks for opening! I'm taking a stab in the dark here, but I've had trouble with Hyperv getting mad at me if I'm running Packer from a different drive than Hyperv is on. Are you running Packer from the C: drive?

**Comment by yooakim** [comment]
Yes @SwampDragons , I'm running from the C: drive, vanilla install and Hyper-V enabled.

After two re-starts I got the process to work. I can't understand why but it did work. Så maybe this can be closed. Sorry for the confusion...
