### ISSUE TITLE
`packer fix` should write errors to stderr

### ISSUE THREAD

**Issue by AndiDog** [hashicorp/packer#6912]
Using Packer 1.3.1, `packer fix Packerfile.in > Packerfile.out` would `exit 1` without printing anything to the terminal. That is first of all confusing as most users don't have a customized shell which shows good/bad exit code, and second, it appends the error messages to the output file which makes it an invalid Packerfile. Other commands also log errors to stderr.

**Comment by SwampDragons** [comment]
Thanks for opening; I think this is essentially a duplicate of #6470

**Comment by azr** [comment]
I believe this should be now solved with this : https://github.com/hashicorp/packer/pull/7466/files#diff-1fca62045a851051294784d1be9ba027R130

**Comment by sylviamoss** [comment]
Closing this one since is a duplicate and it seems to be fixed by the code @azr shared above. If this is still an issue we can reopen later.
