### ISSUE TITLE
Packer throws unknown configuration key for "azure_tags"

### ISSUE THREAD

**Issue by mvvsubbu** [hashicorp/packer#6916]
I am adding new configuration key to my azure builder, the packer build is failing saying **unknown configuration key: "azure_tags"**

Debug logs with platform, version and all the requested information is given below.
https://gist.github.com/mvvsubbu/fa26c5d033c542b0755c5a54db4733ed

Sample Builder configuration is given below.
https://gist.github.com/mvvsubbu/9c99a59561a5cf73a19d4b4d1223f4e3
 
I did also tried to use **temp_resource_group_name** it also fails with same error. Can someone look into this.

**Comment by SwampDragons** [comment]
It looks to me like you're using a third party plugin, which we don't support.

The [officially supported azure builder](https://www.packer.io/docs/builders/azure.html)'s "type" is "azure-arm", not "azure" and ships with the main packer binary.

**Comment by SwampDragons** [comment]
You're also using quite an old version of Packer, which predates the Azure builder. Try upgrading to a more recent version.
