### ISSUE TITLE
AZURE: Add support for "shared image gallery" images as source

### ISSUE THREAD

**Issue by slikk66** [hashicorp/packer#6921]
Currently, when building using azure builder, you have 2 choices: http://aka.ms/packermanagedimage

- VHD source
- Managed Image source

Azure has added a new source for managed images, called Shared Image Gallery: https://azure.microsoft.com/en-us/blog/announcing-the-public-preview-of-shared-image-gallery/

For VM and VMSS you can specify the source of the image to be a "gallery definition" in which you can call an image by name, and get the latest version or a specific version (if you don't specify the specific version)

I'd like to see this added as a source for AZURE-arm builder as well.

In my case, I build a base image and then save it to the gallery.  If the gallery was a source, I could then build off of the latest definition of the base image.

So, the parameters would be something like this:

shared_gallery_name: MyImageGallery
shared_gallery_image_definition: BaseUbuntu1804
shared_gallery_image_version: 10343.932.912432 (or empty would be latest)

Right now when I want to build off of the latest definition in the gallery, I have to query the gallery, get the list of images, find the latest, and then find the managed image ID that that latest version is based off of, and use that in packer.

THANKS!

**Comment by azr** [comment]
A shared image gallery consumer PR was done already ! the merged pr is there: #6798.

You can already start using it by building the master branch of packer.
Otherwise; we will soon do a packer release.

🙂

**Comment by slikk66** [comment]
Awesome!! Thank you
