### ISSUE TITLE
oracle-classic: Remove default ssh_username

### ISSUE THREAD

**Issue by rickard-von-essen** [hashicorp/packer#6928]
Builders should not set a default `ssh_username`. See #4172.

```golang
	// Use default oracle username with sudo privileges
	if c.Comm.SSHUsername == "" {
		c.Comm.SSHUsername = "opc"
	}
```

[builder/oracle/classic/config.go#L72-L75](https://github.com/hashicorp/packer/blob/master/builder/oracle/classic/config.go#L72-L75)

**Comment by SwampDragons** [comment]
I'll look at this after the 1.3.2 release. Thanks for the heads-up. I'll also take a look at the azure one.
