### ISSUE TITLE
Security group filters

### ISSUE THREAD

**Issue by dza89** [hashicorp/packer#6935]
In [packer source code ](https://github.com/hashicorp/packer/blob/master/builder/amazon/common/step_security_group.go)there is a block with security group filter:

```
if !s.SecurityGroupFilter.Empty() {

		params := &ec2.DescribeSecurityGroupsInput{}
		if vpcId != "" {
			s.SecurityGroupFilter.Filters[aws.String("vpc-id")] = &vpcId
		}
		params.Filters = buildEc2Filters(s.SecurityGroupFilter.Filters)

		log.Printf("Using SecurityGroup Filters %v", params)

		sgResp, err := ec2conn.DescribeSecurityGroups(params)
		if err != nil {
			err := fmt.Errorf("Couldn't find security groups for filter: %s", err)
			log.Printf("[DEBUG] %s", err.Error())
			state.Put("error", err)
			return multistep.ActionHalt
		}
```

How do I use this? I cannot find anything documented about this.

```unknown configuration key: "security_group_filter"```

**Comment by rickard-von-essen** [comment]
It's not released yet. The docs on the site will be updated when it's released.

If you want to use it now you can build from source and read the docs in the repository.
