### ISSUE TITLE
can't evaluate field SourceAMITags

### ISSUE THREAD

**Issue by tapvirvirk** [hashicorp/packer#6945]
I'm running the packer with SourceAMITags in the tags section. It is giving an error
 'amazon-ebs' errored: Error tagging source instance: Error processing tag: base_ami:{{.SourceAMITags.base_ami}} - template: root:1:16: executing "root" at <.SourceAMITags.base_...>: can't evaluate field SourceAMITags in type *common.BuildInfoTemplate
I added the base_ami tag on the AMI but still it is failing.

Can you please check?

**Comment by SwampDragons** [comment]
Thanks for opening an issue -- to help you, we really do need the things requested in the issue template: 

- Packer version from `packer version`
- Host platform
- Full debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a gist https://gist.github.com
- The _simplest complete example template and scripts_ needed to reproduce the bug.
  Include these in your gist https://gist.github.com

**Comment by rickard-von-essen** [comment]
Please use the latest release. 1.3.3
