### ISSUE TITLE
Packer 1.2.3 - Windows Build Fails to upload env file after 1 or 2 successful powershell runs

### ISSUE THREAD

**Issue by ramarnat** [hashicorp/packer#6949]
Describe the problem and include the following information:

- Packer version from `packer version`
`1.3.2`

- Host platform
OSX 10.14 (18A391)

- Debug log output from `PACKER_LOG=1 packer build template.json`.
https://gist.github.com/ramarnat/129666cdc2d2dfb9ca3f97608e2179d4

- The _simplest example template and scripts_ needed to reproduce the bug.
https://gist.github.com/ramarnat/129666cdc2d2dfb9ca3f97608e2179d4
  

The error happens when the second powershell needs to be executed, I have tried it with different files and the result is the same:
`2018/11/01 15:33:32 packer: 2018/11/01 15:33:32 Uploading file to 'c:/Windows/Temp/packer-ps-env-vars-5bdb51ef-d8b2-7ae3-c5d7-a4e29ff8b243.ps1'
2018/11/01 15:33:33 packer: 2018/11/01 15:33:33 Retryable error: Error uploading ps script containing env vars: Error uploading file to $env:TEMP\winrmcp-f342f1bf-a68d-4ade-6177-e2a955d25962.tmp: Couldn't create shell: http response error: 401 - invalid content type`

Even though the prior powershellscript worked
`2018/11/01 13:11:24 packer: 2018/11/01 13:11:24 [INFO] 76 bytes written for 'uploadData'
2018/11/01 13:11:24 [INFO] 76 bytes written for 'uploadData'
2018/11/01 13:11:24 packer: 2018/11/01 13:11:24 Uploading file to 'c:/Windows/Temp/packer-ps-env-vars-5bdb3258-f44c-4030-53b4-686925814698.ps1'
2018/11/01 13:11:52 packer: #< CLIXML
2018/11/01 13:11:54 packer: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>#< CLIXML
2018/11/01 13:11:54 packer: 2018/11/01 13:11:54 [INFO] 1235 bytes written for 'uploadData'`

**Comment by ramarnat** [comment]
ok, I figured it out. The honeypot script changes the administrator user name <smacks own head>

**Comment by Elishua100** [comment]
What did you do to fix this issue ?

**Comment by ramarnat** [comment]
one of the scripts was changing the administrator username, so this step was failing because the administrator no longer existed.
