### ISSUE TITLE
openstack builder  should have volume_size option for use with and use_blockstorage_volume

### ISSUE THREAD

**Issue by puetzk** [hashicorp/packer#6956]
Packer 1.3.0 introduced use of a block storage volume as root (#6596), and 1.3.2 followed this up with disk_format (#6702). These are very welcome since they give access to building sparse images (e.g. qcow2). However, the welcome reduction in image size seems to directly result in an reducing in available space when running.

When not using use_blockstorage_volume the root filesystem size is controlled by the chosen flavor, but in the new mode there not seem to be a means to set the size of the volume to anything other than the minimum size the source_image.

cinder actually requires you to specify volume size as part of the call to create a volume, and packer is doing so in its arguments to [volumes.CreateOpts](https://github.com/hashicorp/packer/blob/b88b5c9aaaf817996aade98f471232a26302432a/builder/openstack/step_create_volume.go#L56)

However, [GetVolumeSize](https://github.com/hashicorp/packer/blob/17b368cf8b0a808a48e30083d7d4c42943f4c1b3/builder/openstack/volume.go#L47) just bases the value used on sourceImage.MinDiskGigabytes or (worse, since qcow images are sparse) on sourceImage.SizeBytes. These are reasonable defaults if the image is not going to grow substantially as the provisioners run, but if the provisioners are going to add substantial content the volume may need to be larger than this minimum. So I would like the openstack builder to support a volume_size (or disk_size, or whatever label seems best) as other similar builders do (ami-ebs has volume_size, #6509 added a similar option for oracle, etc), which could override this detected minimum and make the root volume larger than strictly necessary to load the image.

packer 1.3.2
Ubuntu 16.04
openstack cinder v3

**Comment by puetzk** [comment]
Another related issue: If the value determined by GetVolumeSize is actually too low (e.g. a qcow2 image where the file is considerably smaller than the minimum volume that can unpack it), I see that the volume status in `cinder list` become "error". [WaitForVolume](https://github.com/rickard-von-essen/packer/blob/17b368cf8b0a808a48e30083d7d4c42943f4c1b3/builder/openstack/volume.go#L13) doesn't seem to recognize this case, and just keeps looping (and waiting) indefinitely), since ["error" != "available"](https://github.com/hashicorp/packer/blob/17b368cf8b0a808a48e30083d7d4c42943f4c1b3/builder/openstack/volume.go#L47)

**Comment by rickard-von-essen** [comment]
> Another related issue [...]

Could you report a separate issue for this.

**Comment by ragingpastry** [comment]
I think this would be a welcome change. We are also experiencing hardships when trying to limit the size of the openstack images that packer is creating.
