### ISSUE TITLE
Add flag in salt-masterless provisioner to allow custom grains syncing

### ISSUE THREAD

**Issue by ldormoy** [hashicorp/packer#6961]
I use Saltstack with the https://github.com/saltstack/salt-contrib/blob/master/grains/ec2_info.py script to generate ec2-related grains.

When using salt-masterless, the command to use to generate these custom grains would be something like:
```
sudo salt-call --local saltutil.sync_grains
[...]
[INFO    ] Syncing grains for environment 'base'
[INFO    ] Loading cache from salt://_grains, for base)
[INFO    ] Caching directory '_grains/' for environment 'base'
[INFO    ] Fetching file from saltenv 'base', ** done ** '_grains/ec2_info.py'
[INFO    ] Copying '/var/cache/salt/minion/files/base/_grains/ec2_info.py' to '/var/cache/salt/minion/extmods/grains/ec2_info.py'
local:
    - grains.ec2_info
```

This has to be done BEFORE calling state.highstate, as otherwise packer fails with the following error:
```
[ERROR   ] Rendering exception occurred: Jinja variable 'dict object' has no attribute 'ec2'
```

Problem: Saltstack is bootstrapped by the salt-masterless provisioner, so there is no way to simply manually run the sync command. It would involve using a file provisioner to sync the salt codebase, then a shell provisioner to manually bootstrap and configure saltstack and then run the salt-call sync command.

Solution: add a flag to allow grains syncing directly in the salt-masterless provisioner.

**Comment by SwampDragons** [comment]
Thanks for this suggestion!  The salt provisioner is one of our community-supported provisioners, which means that the HashiCorp maintainers don't spend much engineering time on it; this means that the best way to see your suggestion make it into Packer is to open a PR. We'll gladly give support and pointers if you're interested in taking a shot at it.

**Comment by nergdron** [comment]
note that I ran into this earlier, and I'd suggest also being able to sync custom modules. without custom grains and modules support, this provisioner isn't super useful.

an alternative would be to have a salt-ssh provisioner instead. salt-ssh already has all the logic to pack up all this stuff and distribute it along with the minimal necessary python runtime to the remote host, and is quite effective. @SwampDragons: is there docs on writing new provisioners? and what's the level of difficulty? I'd be interested in writing this for my own usage, if it's not super complicated.

**Comment by SwampDragons** [comment]
This is what we have currently: https://www.packer.io/docs/extending/custom-provisioners.html

This is really good timing for me -- Next on my TODO list was to fix up the docs for creating and using plugins. If you find any sticking points or confusion in those instructions, reach out and let me know so I can answer questions and improve the docs.

**Comment by nywilken** [comment]
Hello folks, thanks for opening up this issue. Apologies that we've not had the chance to dive further into this issue. If you've managed to resolve your problem we encourage you to leave comment for others who may experience this issue in the future.

With that said, this is one of our community maintained plugins, which we have recently flagged as [unmaintained](https://github.com/hashicorp/packer/blob/master/README.md#unmaintained-plugins). If you are interested in contributing or taking ownership of this plugin, please reach out to us at packer@hashicorp.com.
