### ISSUE TITLE
[feature] skip qemu-img convert if input file is already qcow2

### ISSUE THREAD

**Issue by robmbrooks** [hashicorp/packer#6963]
Packer is executing this...

2018/11/06 14:58:51 packer: 2018/11/06 14:58:51 Executing qemu-img: []string{"convert", "-O", "qcow2", "/home/packer/one-marketplaceapp-28.qcow2", "/tmp/packer/packer-qemu"}

The input file is already qcow2. The image is being corrupted in the conversion process by [[Qemu-devel] [Bug 1776920] Re: qemu-img convert on Mac OSX creates corrupt images](https://bugs.launchpad.net/qemu/+bug/1776920)

If it would be possible to skip the convert (qemu-img resize does not cause issues). This would be very useful.

**Comment by SwampDragons** [comment]
Thanks for opening! This seems like a good feature and shouldn't be too hard to implement. QEMU is one of our community-supported builders, which means that HashiCorp's engineers don't generally spend their engineering time on it, so the fastest way to get this into Packer is to make a PR for it. I'm happy to give pointers to anyone who would like to try to make this contribution!

**Comment by robmbrooks** [comment]
I checked the code out already looking for a simple hack... I'm not a go programmer but what's the worst that could happen ;-)

If you let me know the preferred way of copying the file, and how to decide if we should skip convert (either an config value or a test?) I will see what I can do... no promises...

**Comment by robmbrooks** [comment]
in the meantime I am working round the issue with this ugly hack (replacing the /usr/local/bin/qemu-img symlink):

```
#!/bin/bash
if [ "$1" == "convert" ]
then
  cp $4 $5
else
  /usr/local/Cellar/qemu/2.12.0/bin/qemu-img $*
fi
```

**Comment by SwampDragons** [comment]
Oof, it's a good hack, but definitely... hacky. 

I think this is the code you want to look at: https://github.com/hashicorp/packer/blob/master/builder/qemu/step_copy_disk.go#L24

I think I'd want to check whether `config.Format` matches the extension on the isoPath. If it matches, do a simple copy rather than a convert. Otherwise, perform the conversion. 

Since you're not a golang programmer, a standard library tip: you'll probably want to use [strings.HasSuffix](https://golang.org/pkg/strings/#example_HasSuffix) to do this comparison.

**Comment by SwampDragons** [comment]
I don't think I have a preferred way of copying the file. The standard library tool is io.Copy, which you can probably find an example of by searching the Packer codebase.

**Comment by vtolstov** [comment]
Why we need to "fix" packer and not Mac OS X  qemu ? Convert step doing always, because:
* change image format
* change image size

so i don't think that we need to change packer, but we need to hack/fix qemu.

**Comment by SwampDragons** [comment]
@vtolstov In a perfect world, we would, but someone has already produced a patch and the conversation on that issue essentially ends with "MacOS is buggy; they should fix their implementation of LSEEK".  At a certain point we need to be able to work around upstream bugs.

@robmbrooks On the issue you linked, they suggest providing the option `-S 0` to the convert command, and it appears that this provides a workaround; would you be interested in trying to just add that?  We can do an `if runtime.GOOS == "darwin"` check for operating system and add the extra args if it matches.  I still like the idea of skipping Convert when it isn't necessary, but when it _is_ necessary we could perhaps prevent these unbootable errors by changing the args slightly.

**Comment by robmbrooks** [comment]
@SwampDragons I tried add `-S 0`, it didn't help.

I'm not seeing bugs with resize, and the convert is unnecessary in some case, so I think packer would be better off not calling it where the image format does not change, even if for performance alone.

I will look at producing a patch, I have people I can call on to help with the code side, so hopefully I can produce something that is not tasteless.

**Comment by SwampDragons** [comment]
Awesome!

**Comment by SwampDragons** [comment]
I sat down to implement this today and was unable to reproduce. Hopefully this means either osx has fixed its version of lseek or qemu fixed its implementation. I'm still going to implement the skip, just in case.
