### ISSUE TITLE
Security_Group_Filter - Multiple tag values

### ISSUE THREAD

**Issue by tgassman** [hashicorp/packer#6973]
Is there anyway to use a single Tag and Filter based on Values in that tag? Add SGs that match either value in defined tag.  We would like to use this feature kind of like the "security_group_ids".  We currently use Terraform and already use tags and can filter on specific values.  All Security Groups have an "AllowedUse" Tag with with different values.  Looked at using the "tag-key" but that will add more then what is required and can cause a limit issue.

Like
"security_group_filter": {
	"filters": {
                "tag:AllowedUse": ["Internal", "Public"]
         }
}

**Comment by SwampDragons** [comment]
There's no way to do exactly what you are asking, but I the security group filters do support globbing; for example: 

```
          "security_group_filter": {
              "filters": {
                "tag:AllowedUse": "*"
              }
```

Would grab any security filter that had the the tag AllowedUse, regardless of that tag's value.

**Comment by tgassman** [comment]
Thanks.  That is still going to cause issues with the limits.  That will add all SGs when we only need 2 for the AMI build.  That is the same thing at "tag-key" which will grab all SGs that have the tag "AllowedUse".  Just hoping there was a way to filter without creating new tags on the SGTs we want for our builds.  Trying to reuse what is existing today.

**Comment by dza89** [comment]
Couldn't this be solved by just executing the same cmdlets for every filter
