### ISSUE TITLE
Re: Populate node attributes from a json file

### ISSUE THREAD

**Issue by curiositycasualty** [hashicorp/packer#6986]
Adding more details to https://github.com/hashicorp/packer/issues/1638 since it is locked.
Feel free to close this issue if there's no actionable feedback in it for you.

In implementing the work around described in the parent issue, I noticed that `packer` passes its `run_list` property (for both `chef` provisioners) via a `first-boot.json` file it writes to `/tmp/packer-chef-cache` (by default).
Which means that if you follow the workaround but don't include a `run_list` key in your `json` file, chef will run with an empty `run_list`.

This feels like only a partial workaround since it means that if you've passed a `run_list` property to a `chef-*` provisioner, it is ignored.
As a full(-er) workaround, I've been templating a ```{{user `chef_run_list`}}``` into the `chef-*` provisioner's `execute_command`'s `chef-client` arguments like so:
```
...
    {
      "destination": "/tmp/attributes.json",
      "source": "attributes/{{build_name}}.json",
      "type": "file"
    }
...
    {
...
      "execute_command": "sudo chef-client --runlist '{{user `chef_run_list`}}' --no-color -c {{.ConfigPath}} -j /tmp/attributes.json",
      "type": "chef-client"
    }
...
```

Hopefully this helps someone else stuck in the same rut.

**Comment by SwampDragons** [comment]
Thanks for the workaround! I'm an admin so I've copied this comment into that issue.
