### ISSUE TITLE
Packer processes download the same iso in parallel

### ISSUE THREAD

**Issue by grv87** [hashicorp/packer#6991]
Packer version: 1.3.2
Host platform: Windows 7 SP1 x64

Use case:
1. Several templates in one directory
2. All templates use the same downloadable ISO
3. Custom cache directory is not configured
4. Several packer processes are run in parallel

Then all processes download the same ISO in parallel.
I see in my firewall that the second process opens new connection.

This leads to two problems:
1. Waste of network throughput
2. If ISOs are actually different, but there is a collision in a hash of URL, then one process corrupts ISO downloaded by another.
The first process should lock ISO file being downloaded, and the second should wait and then compare checksum with its own.

According to logs, Packer locks something:
```
2018/11/12 19:13:04 packer.exe: 2018/11/12 19:13:04 Acquiring lock to download: http://releases.ubuntu.com/16.04.4/ubuntu-16.04.4-server-amd64.iso
2018/11/12 19:13:04 packer.exe: 2018/11/12 19:13:04 Parsed URL: &url.URL{Scheme:"http", Opaque:"", User:(*url.Userinfo)(nil), Host:"releases.ubuntu.com", Path:"/16.04.4/ubuntu-16.04.4-server-amd64.iso", RawPath:"", ForceQuery:false, RawQuery:"", Fragment:""}
2018/11/12 19:13:04 packer.exe: 2018/11/12 19:13:04 [DEBUG] Downloading: http://releases.ubuntu.com/16.04.4/ubuntu-16.04.4-server-amd64.iso
2018/11/12 19:13:04 packer.exe: 2018/11/12 19:13:04 Starting download over HTTP: http://releases.ubuntu.com/16.04.4/ubuntu-16.04.4-server-amd64.iso
```
But not from other Packer processes?
Or it is a Windows issue?

Variations of this case:
2. One template with different builders, or even one builder, but different variables passed to different Packer runs
3. Global cache configured as described [here](https://github.com/hashicorp/packer/pull/804#issuecomment-32726200)

**Comment by azr** [comment]
So to give more context here; `Cache interface` had the right intension:

https://github.com/hashicorp/packer/blob/246e280ddd59b3dd6a3f6cfa67ebde831c096501/packer/cache.go#L13-L24

But the `FileCache implementation` will lock a mutex: 

https://github.com/hashicorp/packer/blob/246e280ddd59b3dd6a3f6cfa67ebde831c096501/packer/cache.go#L50

Then mkdir dir/file:

https://github.com/hashicorp/packer/blob/246e280ddd59b3dd6a3f6cfa67ebde831c096501/packer/cache.go#L76-L97

Will try to see if I can do something about this.

**Comment by azr** [comment]
So  to give more context;

The `Cache interface` has the right intension: 

https://github.com/hashicorp/packer/blob/246e280ddd59b3dd6a3f6cfa67ebde831c096501/packer/cache.go#L13-L24

But then :

`FileCache` implementer will create thread local mutex & then create a dir:
https://github.com/hashicorp/packer/blob/246e280ddd59b3dd6a3f6cfa67ebde831c096501/packer/cache.go#L49-L53

https://github.com/hashicorp/packer/blob/246e280ddd59b3dd6a3f6cfa67ebde831c096501/packer/cache.go#L76-L96

Will try to see if I can do something about it.

**Comment by SwampDragons** [comment]
Looks like #6304 may be related.

**Comment by azr** [comment]
The go-getter PR fixes this by naming the file the `sha1($url+$checksum).$extension`

**Comment by ladar** [comment]
Don't forget about #5613... which I worked around by creating a [dummy JSON file](https://github.com/lavabit/robox/blob/master/packer-cache.json). This JSON file, with dummy builders, allows me to pre-cache all of my ISOs.

**Comment by azr** [comment]
Hey @ladar, sorry I didn't know much about #5613 as I joined the packer team after it got closed.

To summarise: iso files are big, you have a slow connections and need to download a lot of different iso files. Therefore you'd like packer to allow more control over _download performances_.

The go-getter pr is just about using the go-getter in packer, download an iso only once and cache it.
I don't want to add solutions for #5613 to it as the PR will become too big and hard to review/swallow/etc.

But after it is merged it is something you could easily work on.

Some already valid cited solutions are:

* fine grain the number of parallel build as proposed in #5615
* add a packer command  ( `prepare`, `cache` or `pre-download`) that would stop a build right after any download

Together these two features will really help with your issue.
You seem super eager to have a solution for this but this won't be on my short list as a I have more urgent priorities, one thing I can do though is give you pointers as to where to start doing this.

I will try do this soon.

**Comment by ladar** [comment]
Hi @azr, not sure if it's relevant, but in my use case, my connection is fast, but I'm pulling a large ISO off a slow server, possibly because it's for an EOL'ed distro, or I simply can't find a reliably fast mirror with HTTPS support. 

I also have to build boxes single file, in order to prevent the boot command timing from breaking. With a single file build process, I didn't like packer getting held up for 1+ hour at a time when it hit a box configuration involving a long download, so I separated the ISO step using the workaround mentioned above. I think it's managed to cut several hours off my overall build time. 

That said, I realize I'm the edge case, as most people don't build 400+ boxes at a time.
