### ISSUE TITLE
Policyfile Support for chef-solo provisioner

### ISSUE THREAD

**Issue by DWSR** [hashicorp/packer#6992]
Similar to #5574

Policyfile support should be added to the `chef-solo` provisioner, similar to how it is supported by the `chef-client` provisioner. I believe the reason the original PR didn't address the deficiency in the Solo provisioner was due to some uncertainty around using Policyfiles with it. There is an example [here](https://medium.com/@emachnic/using-policyfiles-with-chef-client-local-mode-4f47477b24db) on how this works (also illustrating how to use `chef export` to bundle everything up). Additionally, since `chef-solo` is now just `chef-client` in Local Mode, there is definitely support for Policyfiles.

Ideally, it would be nice to be able to use the same control mechanisms in both my provisioning pipeline and my actual production environment.

**Comment by SwampDragons** [comment]
Thanks for this suggestion! The chef provisioners are community-supported, which means that the HashiCorp maintainers don't spend much engineering time on them; this means that the best way to see your suggestion make it into Packer is to open a PR. We'll gladly give support and pointers if you're interested in taking a shot at implementing this feature..
