### ISSUE TITLE
Vsphere-iso validation is failing for RHEL7.5 VM deployment

### ISSUE THREAD

**Issue by bodduls** [hashicorp/packer#6996]
I am trying to build a vm with vsphere-iso Plugin ..  

Below is my  rhel75.Json file ...

```
{
  "builders":[
     {
      "type": "vsphere-iso",
      "vcenter_server": "nahq-rvapl00072",
      "insecure_connection": "true",
      "username": "srv_vra_lab",
      "password": "XXXXXXXXXXX",
      "datacenter": "LAB-NUTANIX",

      "vm_name": "RHEL75_SB",
      "folder": "_Packer",
      "host": "HQLABINF002/nahq-rpehv00644",
      "cluster": "HQLABINF002",
      "resource_pool": "vRA-LAB-Site2-APP",
      "datastore": "lab-nutanix02-ds01",

      "CPUs": 8,
      "RAM": 10240,
      "disk_size": 20480,


      "guest_os_type": "rhel7_64Guest",
      "cdrom_adapter_type": "ide",
      "disk_adapter_type": "lsiLogic",
      "disk_thin_provisioned": "true",
      "network": "Site1-LAB_930",
      "network_adapter": "vmxnet3",

      "iso_datastore": "lab-nutanix01-ds01",
      "iso": "[LABX_TEMPLATES_NFS] ISOs/rhel75.iso",

      "communicator": "ssh",
      "ssh_username": "root",
      "ssh_password": "packer",

      "convert_to_template": "true"

     }
    ],
"provisioners": [
    {
      "type": "shell",
      "inline": [ "echo hello" ]
    }
  ]
}
```

Validation is failing  with below errors.

[bodduls@packer]$ ./packer validate rhel75.json
Template validation failed. Errors are shown below.

Errors validating build 'vsphere-iso'. 3 errors occurred:

* unknown configuration key: "cdrom_adapter_type"
* unknown configuration key: "disk_adapter_type"
* unknown configuration key: "disk_thin_provisioned"

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
When I remove these optional parameters from the file ..  build is failing with the below message   and from V-center logs  I can see this is related to VirtualCdrom which is not mounting the specified ISO.

[bodduls@ packer]$ ./packer build rhel75.json
vsphere-iso output will be in this color.

==> vsphere-iso: Creating VM...
Build 'vsphere-iso' errored: Invalid configuration for device '2'.

==> Some builds didn't complete successfully and had errors:
--> vsphere-iso: Invalid configuration for device '2'.

==> Builds finished but no artifacts were created.
[bodduls@packer]$

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
I am using Packer v1.3.2 

[bodduls@ packer]$ ./packer version
Packer v1.3.2
[bodduls@ packer]$
[bodduls@labd-rclap00142 packer]$ ls -ltr
total 151572
-rwxr-xr-x 1 bodduls bodduls 86309745 Oct 29 07:40 packer
-rw-rw-r-- 1 bodduls bodduls 27459221 Oct 29 07:47 packer_1.3.2_linux_amd64.zip
-rwxr-xr-x 1 bodduls bodduls 41392224 Nov  7 11:19 packer-builder-vsphere-iso.linux
-rw-rw-r-- 1 bodduls bodduls    19466 Nov  7 14:52 crash.log
-rw-rw-r-- 1 bodduls bodduls     1033 Nov 13 09:40 rhel75.json
[bodduls@labd-rclap00142 packer]$

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Any suggestion  to overcome this ?
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by SwampDragons** [comment]
I'm not an expert in the vsphere-iso builder since it is a third-party builder, but at first glance, you appear to be conflating the vsphere-iso builder with our official vmware-iso builder.  

`cdrom_adapter_type` and `disk_adapter_type ` are official vmware-iso builder options, but we do not have a `disk_thin_provisioned` option; that's an option for the third party builder, https://github.com/jetbrains-infra/packer-builder-vsphere

**Comment by SwampDragons** [comment]
docs for our official builder can be found here: https://www.packer.io/docs/builders/vmware-iso.html

**Comment by bodduls** [comment]
Thanks very much  Megan …. for the builder file  , I will try it and reach out you for any  blocks …


Thanks
Srini B
UNIX Design & Engineering
Toyota Financial Services | Business Technology Solutions
Office  :  +1 (469)-786-8511
Mobile:  +1 (469)-380-9321

**Comment by SwampDragons** [comment]
Wonderful! I'll be here :)

**Comment by bodduls** [comment]
Hi Megan,


Here is the  builder file  I am using .


{
  "builders": [
    {
      "boot_command": [
        "<tab> text ks=http://tfsprodrepo.tfs.toyota.com/tfsrepo/iso/ks75/RHEL75-TMPT.ks<enter><wait>"
      ],
      "boot_wait": "30s",
      "disk_size": "20480",
      "disk_type_id": "zeroedthick",
      "guest_os_type": "rhel7-64",
      "headless": false,
      "http_directory": "../rhel/http",
      "iso_checksum": "d0dd6ae5e001fb050dafefdfd871e7e648b147fb2d35f0e106e0b34a0163e8f5",
      "iso_checksum_type": "sha256",
      "iso_url": "/opt/local/rhel-server-7.5-x86_64-dvd.iso",
      "output_directory": "Packer",
      "remote_datastore": "DCLABAPP004_n0103_n005",
      "remote_host": "10.61.228.48",
      "remote_password": "xxxxxxxxxx",
      "remote_type": "esx5",
      "remote_username": "root",
      "shutdown_command": "echo 'packer' | sudo -S /sbin/halt -h -p",
      "skip_compaction": true,
      "ssh_password": "packer",
      "ssh_port": 22,
      "ssh_username": "packer",
      "ssh_wait_timeout": "10000s",
      "tools_upload_flavor": "linux",
      "type": "vmware-iso",
      "vm_name": "rhel-75-Srini",
      "vmx_data": {
        "cpuid.coresPerSocket": "1",
        "memsize": "4096",
        "numvcpus": "2"
      },
      "vmx_remove_ethernet_interfaces": true
    }
  ],
  "provisioners": [
    {
      "inline": [
        "echo hello"
      ],
      "type": "shell"
    }
  ]
}



+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++


Build is failing   with the below output….


[bodduls@labd-rclap00142 vmware-srini]$ ./packer build rhel75.json
vmware-iso output will be in this color.

Build 'vmware-iso' errored: Failed creating VMware driver: Unable to initialize any driver for this platform. The errors
from each driver are shown below. Please fix at least one driver
to continue:
* GuestIPHack is required, enable by running this on the ESX machine:
esxcli system settings advanced set -o /Net/GuestIPHack -i 1


==> Some builds didn't complete successfully and had errors:
--> vmware-iso: Failed creating VMware driver: Unable to initialize any driver for this platform. The errors
from each driver are shown below. Please fix at least one driver
to continue:
* GuestIPHack is required, enable by running this on the ESX machine:
esxcli system settings advanced set -o /Net/GuestIPHack -i 1


==> Builds finished but no artifacts were created.
[bodduls@labd-rclap00142 vmware-srini]$


+++++++++++++++++++++++++++++++++++++++++++++++++++++++




Thanks
Srini B
UNIX Design & Engineering
Toyota Financial Services | Business Technology Solutions
Office  :  +1 (469)-786-8511
Mobile:  +1 (469)-380-9321

**Comment by bodduls** [comment]
Hi Megan,


I have  ran the given command (esxcli system settings advanced set -o /Net/GuestIPHack -i 1 )  from the output on the ESX Server ..


And re  ran the packer  build, seems it is failing now  with no space left  on the device  message , so which directory  that I have to specify  to avoid this issue ?


[bodduls@labd-rclap00142 vmware-srini]$ ./packer build rhel75.json
vmware-iso output will be in this color.

==> vmware-iso: Retrieving ISO
    vmware-iso: Using file in-place: file:///opt/local/rhel-server-7.5-x86_64-dvd.iso
==> vmware-iso: Uploading ISO to remote machine...
==> vmware-iso: Error uploading file: write /tmp/packer-upload813412272: no space left on device
==> vmware-iso: Deleting output directory...
Build 'vmware-iso' errored: Error uploading file: write /tmp/packer-upload813412272: no space left on device

==> Some builds didn't complete successfully and had errors:
--> vmware-iso: Error uploading file: write /tmp/packer-upload813412272: no space left on device

==> Builds finished but no artifacts were created.
[bodduls@labd-rclap00142 vmware-srini]$ vim rhel75.json
[bodduls@labd-rclap00142 vmware-srini]$


Thanks
Srini B
UNIX Design & Engineering
Toyota Financial Services | Business Technology Solutions
Office  :  +1 (469)-786-8511
Mobile:  +1 (469)-380-9321

From: Srinivas Boddula
Sent: Friday, November 16, 2018 2:30 PM
To: 'hashicorp/packer' <reply@reply.github.com>; hashicorp/packer <packer@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [hashicorp/packer] Vsphere-iso validation is failing for RHEL7.5 VM deployment (#6996)

Hi Megan,


Here is the  builder file  I am using .


{
  "builders": [
    {
      "boot_command": [
        "<tab> text ks=http://tfsprodrepo.tfs.toyota.com/tfsrepo/iso/ks75/RHEL75-TMPT.ks<enter><wait>"
      ],
      "boot_wait": "30s",
      "disk_size": "20480",
      "disk_type_id": "zeroedthick",
      "guest_os_type": "rhel7-64",
      "headless": false,
      "http_directory": "../rhel/http",
      "iso_checksum": "d0dd6ae5e001fb050dafefdfd871e7e648b147fb2d35f0e106e0b34a0163e8f5",
      "iso_checksum_type": "sha256",
      "iso_url": "/opt/local/rhel-server-7.5-x86_64-dvd.iso",
      "output_directory": "Packer",
      "remote_datastore": "DCLABAPP004_n0103_n005",
      "remote_host": "10.61.228.48",
      "remote_password": "xxxxxxxxxx",
      "remote_type": "esx5",
      "remote_username": "root",
      "shutdown_command": "echo 'packer' | sudo -S /sbin/halt -h -p",
      "skip_compaction": true,
      "ssh_password": "packer",
      "ssh_port": 22,
      "ssh_username": "packer",
      "ssh_wait_timeout": "10000s",
      "tools_upload_flavor": "linux",
      "type": "vmware-iso",
      "vm_name": "rhel-75-Srini",
      "vmx_data": {
        "cpuid.coresPerSocket": "1",
        "memsize": "4096",
        "numvcpus": "2"
      },
      "vmx_remove_ethernet_interfaces": true
    }
  ],
  "provisioners": [
    {
      "inline": [
        "echo hello"
      ],
      "type": "shell"
    }
  ]
}



+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++


Build is failing   with the below output….


[bodduls@labd-rclap00142 vmware-srini]$ ./packer build rhel75.json
vmware-iso output will be in this color.

Build 'vmware-iso' errored: Failed creating VMware driver: Unable to initialize any driver for this platform. The errors
from each driver are shown below. Please fix at least one driver
to continue:
* GuestIPHack is required, enable by running this on the ESX machine:
esxcli system settings advanced set -o /Net/GuestIPHack -i 1


==> Some builds didn't complete successfully and had errors:
--> vmware-iso: Failed creating VMware driver: Unable to initialize any driver for this platform. The errors
from each driver are shown below. Please fix at least one driver
to continue:
* GuestIPHack is required, enable by running this on the ESX machine:
esxcli system settings advanced set -o /Net/GuestIPHack -i 1


==> Builds finished but no artifacts were created.
[bodduls@labd-rclap00142 vmware-srini]$


+++++++++++++++++++++++++++++++++++++++++++++++++++++++




Thanks
Srini B
UNIX Design & Engineering
Toyota Financial Services | Business Technology Solutions
Office  :  +1 (469)-786-8511
Mobile:  +1 (469)-380-9321

**Comment by bodduls** [comment]
I would say  ….I reached the below point … ☺



[bodduls@labd-rclap00142 vmware-srini]$ ./packer build rhel75.json
vmware-iso output will be in this color.

==> vmware-iso: Retrieving ISO
    vmware-iso: Using file in-place: file:///opt/local/rhel-server-7.5-x86_64-dvd.iso
==> vmware-iso: Uploading ISO to remote machine...
==> vmware-iso: Creating required virtual machine disks
==> vmware-iso: Building and writing VMX file
==> vmware-iso: Starting HTTP server on port 8686

==> vmware-iso: Registering remote VM...
==> vmware-iso: Starting virtual machine...
==> vmware-iso: Waiting 30s for boot...
==> vmware-iso: Connecting to VM via VNC (10.61.228.48:5988)
==> vmware-iso: Error handshaking with VNC: no suitable auth schemes found. server supported: []byte{0x1}
==> vmware-iso: Stopping virtual machine...
==> vmware-iso: Destroying virtual machine...
Build 'vmware-iso' errored: Error handshaking with VNC: no suitable auth schemes found. server supported: []byte{0x1}

==> Some builds didn't complete successfully and had errors:
--> vmware-iso: Error handshaking with VNC: no suitable auth schemes found. server supported: []byte{0x1}

==> Builds finished but no artifacts were created.
[bodduls@labd-rclap00142 vmware-srini]$



[cid:image001.png@01D47DC1.AD1E9610]



[cid:image002.png@01D47DC1.AD1E9610]
Thanks
Srini B
UNIX Design & Engineering
Toyota Financial Services | Business Technology Solutions
Office  :  +1 (469)-786-8511
Mobile:  +1 (469)-380-9321

From: Srinivas Boddula
Sent: Friday, November 16, 2018 2:44 PM
To: 'hashicorp/packer' <reply@reply.github.com>; 'hashicorp/packer' <packer@noreply.github.com>
Cc: 'Author' <author@noreply.github.com>
Subject: RE: [hashicorp/packer] Vsphere-iso validation is failing for RHEL7.5 VM deployment (#6996)

Hi Megan,


I have  ran the given command (esxcli system settings advanced set -o /Net/GuestIPHack -i 1 )  from the output on the ESX Server ..


And re  ran the packer  build, seems it is failing now  with no space left  on the device  message , so which directory  that I have to specify  to avoid this issue ?


[bodduls@labd-rclap00142 vmware-srini]$ ./packer build rhel75.json
vmware-iso output will be in this color.

==> vmware-iso: Retrieving ISO
    vmware-iso: Using file in-place: file:///opt/local/rhel-server-7.5-x86_64-dvd.iso
==> vmware-iso: Uploading ISO to remote machine...
==> vmware-iso: Error uploading file: write /tmp/packer-upload813412272: no space left on device
==> vmware-iso: Deleting output directory...
Build 'vmware-iso' errored: Error uploading file: write /tmp/packer-upload813412272: no space left on device

==> Some builds didn't complete successfully and had errors:
--> vmware-iso: Error uploading file: write /tmp/packer-upload813412272: no space left on device

==> Builds finished but no artifacts were created.
[bodduls@labd-rclap00142 vmware-srini]$ vim rhel75.json
[bodduls@labd-rclap00142 vmware-srini]$


Thanks
Srini B
UNIX Design & Engineering
Toyota Financial Services | Business Technology Solutions
Office  :  +1 (469)-786-8511
Mobile:  +1 (469)-380-9321

From: Srinivas Boddula
Sent: Friday, November 16, 2018 2:30 PM
To: 'hashicorp/packer' <reply@reply.github.com>; hashicorp/packer <packer@noreply.github.com<mailto:packer@noreply.github.com>>
Cc: Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Subject: RE: [hashicorp/packer] Vsphere-iso validation is failing for RHEL7.5 VM deployment (#6996)

Hi Megan,


Here is the  builder file  I am using .


{
  "builders": [
    {
      "boot_command": [
        "<tab> text ks=http://tfsprodrepo.tfs.toyota.com/tfsrepo/iso/ks75/RHEL75-TMPT.ks<enter><wait>"
      ],
      "boot_wait": "30s",
      "disk_size": "20480",
      "disk_type_id": "zeroedthick",
      "guest_os_type": "rhel7-64",
      "headless": false,
      "http_directory": "../rhel/http",
      "iso_checksum": "d0dd6ae5e001fb050dafefdfd871e7e648b147fb2d35f0e106e0b34a0163e8f5",
      "iso_checksum_type": "sha256",
      "iso_url": "/opt/local/rhel-server-7.5-x86_64-dvd.iso",
      "output_directory": "Packer",
      "remote_datastore": "DCLABAPP004_n0103_n005",
      "remote_host": "10.61.228.48",
      "remote_password": "xxxxxxxxxx",
      "remote_type": "esx5",
      "remote_username": "root",
      "shutdown_command": "echo 'packer' | sudo -S /sbin/halt -h -p",
      "skip_compaction": true,
      "ssh_password": "packer",
      "ssh_port": 22,
      "ssh_username": "packer",
      "ssh_wait_timeout": "10000s",
      "tools_upload_flavor": "linux",
      "type": "vmware-iso",
      "vm_name": "rhel-75-Srini",
      "vmx_data": {
        "cpuid.coresPerSocket": "1",
        "memsize": "4096",
        "numvcpus": "2"
      },
      "vmx_remove_ethernet_interfaces": true
    }
  ],
  "provisioners": [
    {
      "inline": [
        "echo hello"
      ],
      "type": "shell"
    }
  ]
}



+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++


Build is failing   with the below output….


[bodduls@labd-rclap00142 vmware-srini]$ ./packer build rhel75.json
vmware-iso output will be in this color.

Build 'vmware-iso' errored: Failed creating VMware driver: Unable to initialize any driver for this platform. The errors
from each driver are shown below. Please fix at least one driver
to continue:
* GuestIPHack is required, enable by running this on the ESX machine:
esxcli system settings advanced set -o /Net/GuestIPHack -i 1


==> Some builds didn't complete successfully and had errors:
--> vmware-iso: Failed creating VMware driver: Unable to initialize any driver for this platform. The errors
from each driver are shown below. Please fix at least one driver
to continue:
* GuestIPHack is required, enable by running this on the ESX machine:
esxcli system settings advanced set -o /Net/GuestIPHack -i 1


==> Builds finished but no artifacts were created.
[bodduls@labd-rclap00142 vmware-srini]$


+++++++++++++++++++++++++++++++++++++++++++++++++++++++




Thanks
Srini B
UNIX Design & Engineering
Toyota Financial Services | Business Technology Solutions
Office  :  +1 (469)-786-8511
Mobile:  +1 (469)-380-9321

**Comment by SwampDragons** [comment]
What version of esxi are you using? If it's esxi 6.5 or above, I believe you need to set 

`"vnc_disable_password": true,`

in your builder config.

**Comment by bodduls** [comment]
Yes just added that   after looking at https://github.com/hashicorp/packer/issues/5580    and re running   the build…  hope this will go fine …    fingers crossed  … ☺


Thanks
Srini B
UNIX Design & Engineering
Toyota Financial Services | Business Technology Solutions
Office  :  +1 (469)-786-8511
Mobile:  +1 (469)-380-9321

**Comment by SwampDragons** [comment]
Can you share your full logs?  I need you to set the environment variable 

`PACKER_LOG=1`

**Comment by bodduls** [comment]
That is only log I got …


Thanks
Srini B
UNIX Design & Engineering
Toyota Financial Services | Business Technology Solutions
Office  :  +1 (469)-786-8511
Mobile:  +1 (469)-380-9321

**Comment by SwampDragons** [comment]
Right; to get full debug logs, you need to rerun the build with the above env var set. For example: 

`PACKER_LOG=1 ./packer build rhel75.json`

**Comment by bodduls** [comment]
Here it is …

Please check and suggest ..


Thanks
Srini B
UNIX Design & Engineering
Toyota Financial Services | Business Technology Solutions
Office  :  +1 (469)-786-8511
Mobile:  +1 (469)-380-9321

**Comment by kikitux** [comment]
@bodduls 

Packer is open source and we rely on the community for help, in that way developers can focus on bugs and new features.

It seems the issue you are having is related to either misconfiguration on VMWare (firewall) or the template.

[dhcp.zip](https://github.com/hashicorp/packer/files/2601125/dhcp.zip)

i am attaching a template that works, that I use to test a new ESXi.

This assume there is a DHCP network available for VMs.

If you can't not get this working, then I would like to ask you engage us over the mailing list:
https://www.packer.io/community.html

And share some document on how this ESXi server was setup.

Thanks
Alvaro.

**Comment by bodduls** [comment]
Two questions:

 first, did this work before you removed "remote_private_key_file": "path_to_ssh_key" ?      Not really.

Second, have you checked the firewall rules on your esxi instance to make sure that your lab computer is allowed to connect to it?

       which  ports to be  open ?

**Comment by SwampDragons** [comment]
>which ports

Your log file is telling you the problem: It can't connect via vnc.  `Unable to find available VNC port between 5900 and 6000`

You can narrow this to a particular port if you'd like by using the template options `vnc_port_min` and `vnc_port_max`. From our docs: 

> vnc_port_min and vnc_port_max (number) - The minimum and maximum port to use for VNC access to the virtual machine. The builder uses VNC to type the initial boot_command. Because Packer generally runs in parallel, Packer uses a randomly chosen port in this range that appears available. By default this is 5900 to 6000. The minimum and maximum ports are inclusive.

**Comment by kikitux** [comment]
in latest version, you need to use the ESXI CLI to create some rules and is not longer available on the UI from what I have seen.

In previous version you could just enable a set named gdb that included VNC ports.

here is a link on how to do it in a old version of ESXi
https://elatov.github.io/2017/03/vmware-remote-console-with-vsphere-60u2/

You need to find a way how to do this on your current version

**Comment by bodduls** [comment]
Hi Megan,

I believe I am almost there  to complete  VM build , but  at the end it is failing … Here  I am attaching the debug log,  builder file  & the  VM console output..

Please suggest what can be done to overcome this issue.

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++


[bodduls@labd-rclap00142 vmware-srini]$ cat rhel75.json
{
"builders": [
    {
      "boot_command": [
        "<tab> text ks=http://tfsprodrepo.tfs.toyota.com/tfsrepo/iso/ks75/RHEL75-TMPT.ks<enter><wait>"
      ],
      "boot_wait": "50s",
      "disk_size": "20480",
      "guest_os_type": "rhel7-64",
      "headless": "",
      "http_directory": "../rhel/http",
      "iso_checksum": "d0dd6ae5e001fb050dafefdfd871e7e648b147fb2d35f0e106e0b34a0163e8f5",
      "iso_checksum_type": "sha256",
      "iso_url": "/opt/local/rhel-server-7.5-x86_64-dvd.iso",
      "shutdown_command": "echo 'packer' | sudo -S /sbin/halt -h -p",
      "ssh_password": "packer",
      "ssh_port": 22,
      "ssh_username": "packer",
      "ssh_wait_timeout": "10000s",
      "tools_upload_flavor": "linux",
      "type": "vmware-iso",
      "vm_name": "rhel-75-Srini9",
      "output_directory": "/vmfs/volumes/DCLABAPP004_n0103_n005",
      "vnc_disable_password": "true",
      "cdrom_adapter_type": "ide",
      "disable_vnc": "false",
      "disk_adapter_type": "lsilogic",
      "vmx_data": {
      "cpuid.coresPerSocket": "1",
      "memsize": "4096",
      "numvcpus": "2"
      },
      "vmx_remove_ethernet_interfaces": "true",

      "remote_type": "esx5",
      "remote_host": "10.xxx.xxx.xx",
      "remote_port": 22,
      "remote_datastore": "DCLABAPP004_n0103_n005",
      "remote_username": "root",
      "remote_password": "XXXXXXXXX"
    }
  ],
"provisioners": [
    {
      "type": "shell",
      "inline": [ "echo hello" ]
    }
  ]
}

[bodduls@labd-rclap00142 vmware-srini]$

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

[cid:image001.png@01D486FF.FF2786F0]


Thanks
Srini B
UNIX Design & Engineering
Toyota Financial Services | Business Technology Solutions
Office  :  +1 (469)-786-8511
Mobile:  +1 (469)-380-9321
