### ISSUE TITLE
Qemu detect-zeroes Packer 1.3.2 w/ libvirt 3.2 Exception

### ISSUE THREAD

**Issue by rpsiv** [hashicorp/packer#7004]
Environment:
- Packer version 1.3.2
- Host RHEL 7
  - qemu-kvm 1.5.3
  - libvirt 3.2.0
- Debug log output 
```
2018/11/15 13:13:46 packer_1.3.2: 2018/11/15 13:13:46 Qemu stderr: qemu-system-x86_64: -drive file=/VM/packer/kvm_rhel7/rhel7Template,if=virtio,cache=writeback,discard=ignore,format=qcow2,detect-zeroes=off: could not open disk image /VM/packer/kvm_rhel7/rhel7Template: Block format 'qcow2' used by device 'virtio0' doesn't support the option 'detect-zeroes'
```
`Block format 'qcow2' used by device 'virtio0' doesn't support the option 'detect-zeroes'`

In Packer 1.3.2 `builder/qemu: Add disk_detect_zeroes option. [GH-6827]` was added.  While the default is `detect-zeroes=off` the argument itself is not supported on older version of libvirt and throws the above exception.  Running the same build with Packer 1.3.1 completes successfully.

Could this option be explicitly controlled in the builders JSON?  If set to `false` the argument would not be present when calling `qemu-system`.

**Comment by msncookie** [comment]
I'm seeing the same error but with *newer* libvirt:

* Oracle Linux 7.6 (RHEL, etc)
    * libvirt-4.5.0
    * qemu-kvm-1.5.3
* Packer 1.3.2

**Comment by ambakshi** [comment]
Seeing the same thing on 1.3.2, on a newer qemu-kvm-ev-2.10.0 (by way of centos-virt-sig) on EL7. I tried setting detect_zeroes "off" and still no dice. Reverting to 1.3.1 fixes it.

**Comment by vtolstov** [comment]
Libvirt not used, you need never qemu version.

сб, 1 дек. 2018 г., 21:33 Amit Bakshi notifications@github.com:

**Comment by SwampDragons** [comment]
Hi @rpsiv and @ambakshi! Thanks for letting me know about this. Here's a build of PR 7064; it makes it so we don't actually set this option unless it's set to a value other than "off".

Can you let me know if it solves your issues?

https://github.com/hashicorp/packer/pull/7064
[packer.zip](https://github.com/hashicorp/packer/files/2641733/packer.zip)

**Comment by ambakshi** [comment]
@SwampDragons Fixed the issue for me, thanks!
