### ISSUE TITLE
GCE import post-processor doesn't support service accounts

### ISSUE THREAD

**Issue by DanielMarquard** [hashicorp/packer#7006]
Documentation for the GCE builder clearly states that service accounts are supported, however this does not appear to be true for the `googlecompute-import` post-processor.

Our use cases require that we build images locally (from credentialed GCE instances) before importing them into GCP as GCE images. Security requirements prevent us from using an account file in these cases.

**Comment by SwampDragons** [comment]
Thanks for reaching out! The builder isn't the same as the post-processor, so docs for one don't necessarily apply to to the other.  However, I agree that this would be a nice feature to add to the post-processor.

**Comment by DanielMarquard** [comment]
@SwampDragons Hi, Megan! o/ How soon do you think support for service accounts could be added? We depend on Packer, but this makes it a tough sell.

**Comment by SwampDragons** [comment]
Feature disparities bug me, so I took a look and made a PR (linked above) -- if you want to build and test it, let me know. I can also build it for you, if you let me know your environment.

**Comment by DanielMarquard** [comment]
@SwampDragons Thank you so much! Yes, if you could build a Linux x64 binary for it, that would be great. I'll have my team test it out Sunday or Monday. Thanks again!

**Comment by SwampDragons** [comment]
Oops; you caught me after I'd left for the weekend; here's a linux build of PR #7015

[packer.zip](https://github.com/hashicorp/packer/files/2596369/packer.zip)

I'm going to keep working on generalizing and extending the code, so I may ask you to test another build later this week or next.

**Comment by DanielMarquard** [comment]
Thanks! We're packaging this into our builder image and will run a packer build on a GCE image this afternoon.

**Comment by SwampDragons** [comment]
Try this one instead of the one I linked above; The other one was failing CI.
[packer.zip](https://github.com/hashicorp/packer/files/2596787/packer.zip)

**Comment by DanielMarquard** [comment]
Our import failed, here's the output:

```
Build 'qemu' errored: 1 error(s) occurred:

2018/11/20 00:45:06 ui error: Build 'qemu' errored: 1 error(s) occurred:

* Post-processor failed: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
2018/11/20 00:45:06 Builds completed. Waiting on interrupt barrier...
2018/11/20 00:45:06 machine readable: error-count []string{"1"}
2018/11/20 00:45:06 ui error: 
==> Some builds didn't complete successfully and had errors:
2018/11/20 00:45:06 machine readable: qemu,error []string{"1 error(s) occurred:\n\n* Post-processor failed: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information."}
2018/11/20 00:45:06 ui error: --> qemu: 1 error(s) occurred:

* Post-processor failed: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
==> Builds finished but no artifacts were created.
2018/11/20 00:45:06 [INFO] (telemetry) Finalizing.
* Post-processor failed: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.

==> Some builds didn't complete successfully and had errors:
--> qemu: 1 error(s) occurred:

* Post-processor failed: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
```

**Comment by DanielMarquard** [comment]
Here's the post-processors we're testing the build with:

```
    "post-processors": [
        [
            {
                "type": "compress",
                "output": "output/disk.raw.tar.gz"
            },
            {
                "type": "googlecompute-import",
                "project_id": "[redacted]",
                "bucket": "[redacted]",
                "image_name": "[redacted]-base-{{timestamp}}",
                "image_description": "[redacted] base",
                "image_family": "[redacted]"
            }
        ]
    ]
```

**Comment by SwampDragons** [comment]
Huh, interesting. But the builder itself successfully validates?

**Comment by DanielMarquard** [comment]
Yep, we have a `packer validate` job running early in the pipeline.

**Comment by SwampDragons** [comment]
And the builder successfully connects and runs using the same service account you’re using here?

**Comment by DanielMarquard** [comment]
Yes, Terraform also uses that service account to deploy.

**Comment by SwampDragons** [comment]
That's... really wacky. I changed the code for the post-processor to use the code that the builder uses. Can you share full logs with the env var PACKER_LOG=1 in a gist?

**Comment by SwampDragons** [comment]
Sorry for the delay on this; I was on vacation. Back now. 

If you can't share full logs I understand, but you've only shared the error output from the very end of the log, so I can't see where the build failed. Can you search back in the log to find where `could not find default credentials` is first printed and give me a couple of loglines on either side so I can narrow down where in the code this is failing?

**Comment by SwampDragons** [comment]
I'm going to ask for a clarification, here, too.  When you say: 

>Our use cases require that we build images locally (from credentialed GCE instances)

Is "local" on an instance running inside of GCE? Or is it outside of GCE's cloud? I'm not 100% sure what you mean by "credentialed GCE instances"

I'm trying to read https://cloud.google.com/docs/authentication/production to get a better idea of how all of this works. 

When I wrote this code I assumed you're building from inside the GCE cloud, but looking at the code, it should not have given you the error message it did if you really are.

If you're building outside of the GCE cloud, it looks like no matter what you'll need a service account file; you have to set the env var `GOOGLE_APPLICATION_CREDENTIALS` to point to the service account file. There's no other way of authenticating to the cloud from outside of it.

**Comment by SwampDragons** [comment]
Here's the func that's returning your error: https://github.com/golang/oauth2/blob/8a57ed94ffd43444c0879fe75701732a38afc985/google/default.go#L60-L100

If you're building inside the cloud, I'd expect to see us returning at line 94, rather than returning the error message in line 99.

**Comment by SwampDragons** [comment]
Any updates on this?  Did you figure out how to get your build working from outside GCE?

**Comment by SwampDragons** [comment]
Good reminder. I looked at the terraform code and I'm not immediately seeing anything. That said I'm good friends with the person who does a lot of our terraform + google stuff so I'll reach out to him and get back to you on what may be causing this discrepancy.
