### ISSUE TITLE
Packer Console

### ISSUE THREAD

**Issue by Tensho** [hashicorp/packer#7009]
### Feature Request

It would be nice to check the variables or interpolations in the console, similar to `terraform console`. For example, right now I have to run `packer build` and check the variable interpolated values within console output during EBS volume tagging.

Approximate interface:

```
> git-branch
staging

OR

> user.git-branch
staging

OR

> user `git-branch`
staging
```
```
> "{{ user `application` }}-{{timestamp }}"
splash-1542381038
```

**Comment by SwampDragons** [comment]
This is a cool idea. I'll reach out to terraform and see how complex it was for them to implement so I can get an idea of scope.

**Comment by SwampDragons** [comment]
I'm setting this for the 1.4.2 milestone -- no guarantees yet that it will be implemented, but we'll investigate and make a decision during this release cycle.
