### ISSUE TITLE
Packer does not correctly set path in vmware vm vmx file

### ISSUE THREAD

**Issue by whiggs** [hashicorp/packer#7020]
I have a small favor to ask, hashicorp.  Please just use the paths that, you know, **we define in the json build file** when creating the vmx file and setting its values for the vmware builder.  Instead, it seems you attempt to (when you incorrectly think you can get away with it) convert the paths that are defined in the build json to relative paths.  Why do you have to go and over-complicate and completely screw up something simple?   Allow me to elaborate.  Below, you will see the contents of the json file which I use to build vms with packer:
```json
{
  "builders": [
    {
      "type": "virtualbox-iso",
      "vboxmanage": [
        [
          "modifyvm",
          "{{.Name}}",
          "--memory",
          "4096"
        ],
        [
          "modifyvm",
          "{{.Name}}",
          "--cpus",
          "2"
        ]
      ],
      "guest_additions_mode": "attach",
      "guest_os_type": "Windows2016_64",
      "iso_url": "file://C:/Users/whiggs/Desktop/SW_DVD9_Win_Svr_STD_Core_and_DataCtr_Core_2016_64Bit_English_-2_MLF_X21-22843.ISO",
      "iso_checksum": "DA24F70AA42600CCD11C6C5CB992BFED41D8F235A74C74E5201924DD50A74696",
      "iso_checksum_type": "sha256",
      "communicator": "winrm",
      "winrm_username": "vagrant",
      "winrm_password": "vagrant",
      "winrm_timeout": "12h",
      "floppy_files": [
		"C:/Users/whiggs/Desktop/Autounattend.xml",
		"C:/Users/whiggs/Desktop/packerfiles/uac.inf",
		"C:/Users/whiggs/Desktop/packerfiles/virtualtools.bat",
		"C:/Users/whiggs/Desktop/packerfiles/run.ps1"
      ]
    },
	{
		"name":	"vmware-packer",
		"vm_name":	"vm-packer",
		"type":	"vmware-iso",
		"disk_size": 60000,
		"iso_url": "file://C:/Users/whiggs/Desktop/SW_DVD9_Win_Svr_STD_Core_and_DataCtr_Core_2016_64Bit_English_-2_MLF_X21-22843.ISO",
		"iso_checksum": "DA24F70AA42600CCD11C6C5CB992BFED41D8F235A74C74E5201924DD50A74696",
		"iso_checksum_type": "sha256",
		"guest_os_type":	"windows9srv-64",
		"tools_upload_flavor":	"windows",
		"vmx_template_path":	"C:/Users/whiggs/Desktop/packerfiles/template.vmx",
		"communicator": "winrm",
		"winrm_username": "vagrant",
		"winrm_password": "vagrant",
		"winrm_timeout": "12h",
		"floppy_files":	[
			"C:/Users/whiggs/Desktop/packerfiles/run.ps1",
			"C:/Users/whiggs/Desktop/packerfiles/uac.inf",
			"C:/Users/whiggs/Desktop/packerfiles/vmwaretools.bat"
			]
	}
  ]
}
```

Its not even a full packer json, just the build portion of it.  As you can see, the json is formatted correctly and I have nice, **FULL** paths defined for all of my files.  However, crap flies skyward when I try to build a vm with the vmware builder:
packer build -force -only vmware-packer C:\Users\whiggs\Desktop\jsonformatter.json

The machine boots up, but all I see is this once I get past the bios screen:
![Error](https://i.imgur.com/v7YoUKO.png)

So, I did some investigating as to what was going on.  I probably don't have to tell you this, as the developers, but I feel I need to anyway: when building a vm with the vmware builder, packer creates a sub-directory in the same folder that the build json is located in, in which it actually stores the vm it is creating.  So, for me, as you can see from the json contents, this folder would be located at C:\users\whiggs\desktop\output-vmware-packer.  I should also mention that, as, once again, you can see from the json file, the install media that is used to install the operating system is located in the same folder as the build json file.  Now, I went into the output-vmware-packer folder to take a look at the vmx file (which, just to be 100% clear here, is located at C:\users\whiggs\desktop\output-vmware-packer\vm-packer.vmx) to see what was going on, which contained the following contents:
```
.encoding = "UTF-8"
bios.bootorder = "hdd,CDROM"
checkpoint.vmstate = ""
cleanshutdown = "FALSE"
config.version = "8"
displayname = "vm-packer"
ehci.pcislotnumber = "-1"
ehci.present = "FALSE"
ethernet0.addresstype = "generated"
ethernet0.bsdname = "en0"
ethernet0.connectiontype = "nat"
ethernet0.displayname = "Ethernet"
ethernet0.linkstatepropagation.enable = "FALSE"
ethernet0.pcislotnumber = "33"
ethernet0.present = "TRUE"
ethernet0.virtualdev = "e1000"
ethernet0.wakeonpcktrcv = "FALSE"
extendedconfigfile = "vm-packer.vmxf"
floppy0.filename = "C:\Users\whiggs\AppData\Local\Temp\packer919524579"
floppy0.filetype = "file"
floppy0.present = "TRUE"
guestos = "windows9srv-64"
gui.fullscreenatpoweron = "FALSE"
gui.viewmodeatpoweron = "windowed"
hgfs.linkrootshare = "TRUE"
hgfs.maprootshare = "TRUE"
ide1:0.devicetype = "cdrom-image"
ide1:0.filename = "..\..\SW_DVD9_Win_Svr_STD_Core_and_DataCtr_Core_2016_64Bit_English_-2_MLF_X21-22843.ISO"
ide1:0.present = "TRUE"
isolation.tools.hgfs.disable = "FALSE"
memsize = "4096"
msg.autoanswer = "true"
numvcpus = "2"
nvram = "vm-packer.nvram"
pcibridge0.pcislotnumber = "17"
pcibridge0.present = "TRUE"
pcibridge4.functions = "8"
pcibridge4.pcislotnumber = "21"
pcibridge4.present = "TRUE"
pcibridge4.virtualdev = "pcieRootPort"
pcibridge5.functions = "8"
pcibridge5.pcislotnumber = "22"
pcibridge5.present = "TRUE"
pcibridge5.virtualdev = "pcieRootPort"
pcibridge6.functions = "8"
pcibridge6.pcislotnumber = "23"
pcibridge6.present = "TRUE"
pcibridge6.virtualdev = "pcieRootPort"
pcibridge7.functions = "8"
pcibridge7.pcislotnumber = "24"
pcibridge7.present = "TRUE"
pcibridge7.virtualdev = "pcieRootPort"
powertype.poweroff = "soft"
powertype.poweron = "soft"
powertype.reset = "soft"
powertype.suspend = "soft"
proxyapps.publishtohost = "FALSE"
remotedisplay.vnc.enabled = "TRUE"
remotedisplay.vnc.ip = "127.0.0.1"
remotedisplay.vnc.password = "9vGrq98A"
remotedisplay.vnc.port = "5917"
replay.filename = ""
replay.supported = "FALSE"
scsi0.pcislotnumber = "160"
scsi0.present = "TRUE"
scsi0.virtualdev = "lsisas1068"
scsi0:0.filename = "disk.vmdk"
scsi0:0.present = "TRUE"
scsi0:0.redo = ""
sound.startconnected = "FALSE"
tools.synctime = "TRUE"
tools.upgrade.policy = "upgradeAtPowerCycle"
usb.pcislotnumber = "-1"
usb.present = "FALSE"
uuid.action = "create"
virtualhw.productcompatibility = "hosted"
virtualhw.version = "9"
vmci0.id = "1861462627"
vmci0.pcislotnumber = "35"
vmci0.present = "TRUE"
vmotion.checkpointfbsize = "134217728"
RemoteDisplay.vnc.key = "Dg8KITkfEzI4LwwOPSYPBi8eNAgWNQkRBiUjEDseNRI5OTIlBTMQHg8+HhU+KiIiPg0QPg8dBSkTFwkSMyMOGAc+Gzg3DzgSOhkaNSs8AA01Ny0UGyMSKQ0rAQs8PQcPPxQVCCIfDjQwPwYaPQgxBDsyJCUeNzkYPjInIiMbCiw="
floppy0.clientDevice = "FALSE"
numa.autosize.cookie = "20001"
numa.autosize.vcpu.maxPerVirtualNode = "2"
uuid.bios = "56 4d bf 6c aa 3d a8 e0-04 e6 91 45 3e 62 35 b7"
uuid.location = "56 4d bf 6c aa 3d a8 e0-04 e6 91 45 3e 62 35 b7"
scsi0.sasWWID = "50 05 05 6c aa 3d a8 e0"
svga.vramSize = "134217728"
ethernet0.generatedAddress = "00:0c:29:62:35:b7"
ethernet0.generatedAddressOffset = "0"
vm.genid = "8824108726855122470"
vm.genidX = "8753644135187228529"
monitor.phys_bits_used = "40"
softPowerOff = "FALSE"
```

See the problem?  If not, take a look at the path that packer has defined for the installation media used to install the operating system.  Packer has not only converted it into a relative path rather than just keeping the value **as I configured it**, but it has completely failed in correctly converting the full path to a relative path.  Packer has configured the virtual machine to look for the installation media a full directory **ABOVE** the directory that the installation media is located in (looking for the file at "C:\Users\whiggs\SW_DVD9_Win_Svr_STD_Core_and_DataCtr_Core_2016_64Bit_English_-2_MLF_X21-22843.ISO" rather than the correct path that **I already configured in the build json file** "C:\Users\whiggs\Desktop\SW_DVD9_Win_Svr_STD_Core_and_DataCtr_Core_2016_64Bit_English_-2_MLF_X21-22843.ISO").  Just to prove my point, check it:
![theproof](https://i.imgur.com/6MwYUSq.png)

I would really appreciate a fix asap, and, like I stated earlier, actually use the **full paths that people set in the build json** rather than what you have been doing until now.  So much simpler, less complicated and error prone, and would mean less frustrated people like myself having to submit issue posts for a buggy, half-assed product.
- Packer version from `packer version`
packer -v
1.3.2
- Host platform
Windows 10 1803 x64
- Debug log output from `PACKER_LOG=1 packer build template.json`.
https://gist.githubusercontent.com/whiggs/1f797f60e55b565020528f177d7f7e13/raw/2ab22fd7dcdbd3bb4c724d4e2dca7ae146b5f8e8/packerdebug.txt

https://gist.github.com/whiggs/1f797f60e55b565020528f177d7f7e13

**Comment by SwampDragons** [comment]
Hi there! Thanks for reaching out. I am sorry this has been such a frustrating experience for you. Can you please share the contents of your template.vmx to give me the best possible chance of reproducing? I’ll take a look at this issue on Monday when I get back to my computer.
