### ISSUE TITLE
Unable to find or download VBoxGuestAdditions.iso

### ISSUE THREAD

**Issue by bstoots** [hashicorp/packer#7021]
I'm experiencing an issue similar to the one fixed in #5761.  From looking at the logs it appears there may be an extra slash being prepended beyond what was already being accounted for.  Perhaps a relevant piece of info for debugging: my C drive is actually a virtual volume spanning two disks and being managed by Enmotus FuzeDrive.

```
packer --version
1.3.2
```

```
systeminfo
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17134 N/A Build 17134
```

Debug output:
https://gist.github.com/bstoots/8dea306ea1c67ef767fe6583079c8697

Example template:
https://gist.github.com/bstoots/881f4978354210a198b37deff375981a

Let me know if I can provide any additional debugging assistance.

**Comment by WizBangCrash** [comment]
I am seeing the same error on the same OS and version of packer.
I am using v5.2.22 of VirtualBox

**Comment by azr** [comment]
Ah thanks for sharing this back to us @/WizBangCrash 🙂 closing this issue then.
FYI, the [mailing list](https://groups.google.com/forum/#!forum/packer-tool) is a nice place if you have other questions

**Comment by bstoots** [comment]
That was not the cause of my issue.  Could we get this reopened?

**Comment by bstoots** [comment]
Spoke too soon.  Can confirm it's working as intended.
