### ISSUE TITLE
packer validate hungs when using amazon resources and no creds are set

### ISSUE THREAD

**Issue by kikitux** [hashicorp/packer#7053]
Hi Packer team

packer validate hungs when using amazon resources and no creds are set

Can we add a note to the documentation, or see if packer should exit as won't be able to validate?

repro
```
{ 
  "variables": {
       "aws_access_key": "",
       "aws_secret_access_key": ""
   },

  "builders": [
    {
      "type": "amazon-ebs",
      "access_key": "{{user `aws_access_key`}}",
      "secret_key": "{{user `aws_secret_access_key`}}",
      "region": "us-west-2",
      "source_ami": "ami-0e32ec5bc225539f5",
      "instance_type": "t2.micro",
      "ssh_username": "ubuntu",
      "ami_name": "ec2_xenial_packer_{{timestamp}}"
    }
  ]
}
```

<3

Thanks!

**Comment by azr** [comment]
Hey @kikitux yes, this is annoying, I'm currently doing a PR in https://github.com/aws/aws-sdk-go/pull/2298 to fix this; but this requires me to do some test with go 1.5 ( which doesn't run on my mac ). 

But I'm getting there; hang tight !

Also related #6919

**Comment by SwampDragons** [comment]
I recently merged https://github.com/hashicorp/packer/pull/7032 which should prevent this from happening during validation; we'll have to wait for the AWS pull to get merged before we can mark this as totally resolved.

**Comment by kaspergrubbe** [comment]
I was just experiencing this, thanks for creating this issue.
