### ISSUE TITLE
VirtualBox Optical Drive not created as master in EFI mode

### ISSUE THREAD

**Issue by koaps** [hashicorp/packer#7081]
- Packer version: 1.3.2
- VirtualBox Version 5.2.22 r126460 (Qt5.6.3)
- Host platform: macOS Mojave v10.14.1

When creating an EFI enabled VM, the optical drive isn't set to master (primary or secondary), this prevents the mounted ISO from being loaded and failing into the EFI shell.

The Optical drive should be an IDE secondary master, VirtualBox does this by default when creating a VM manually.

**Comment by breisig** [comment]
Getting the same issue. Virtualbox ISO cd does not load unless it was set to IDE secondary master for me in EFI mode.

**Comment by SwampDragons** [comment]
Do either of you have a template for reproducing? It'll be way faster for me to get a patch in if I know how you're configuring this.

**Comment by breisig** [comment]
Since I didn't know how to modify the existing "IDE Controller" that the ISO file used to change the port,  I had to modify my packer file to add a new IDE controller as type IDE primary master and manually attach the ISO that way under    "vboxmanage" .

```
    "vboxmanage": [
        [ "modifyvm", "{{.Name}}", "--firmware", "EFI" ],
        [ "storageattach", "{{.Name}}", "--storagectl", "IDE Controller", "--port", "0", "--device", "0", "--type", "dvddrive", "--medium", "C:\centos8.iso"],
    ]
```

**Comment by SwampDragons** [comment]
Definitely. We have a fairly primitive driver for attaching disks; I won't get a chance to before the 1.4.5 release but adding more direct ability to control the storagectl commands could be something we aim for in the 1.5 release.

**Comment by breisig** [comment]
ok, I finally got an ISO working in EFI mode without having to modify/attach another IDE driver. All I had to do is force the iso_interface to be setup as a SATA drive instead of the default IDE mode by adding the following to my packer config.

```
      "iso_interface": "sata",
```

**Comment by SwampDragons** [comment]
Awesome. So sounds like we have some work to do around making sure we set reasonable defaults, and add lots of documentation.
