### ISSUE TITLE
amazon-ebs builder not attaching temporary or specified security group to launched EC2 instance.

### ISSUE THREAD

**Issue by timnee** [hashicorp/packer#711]
The temporary security group (e.g., packer xxxxxx...) is not being associated to the launched EC2 instance.  This results in SSH being unable to connect (timeout).  Only the default group is added.

I tried specifying the group(s) using security_group_id and security_group_ids.  Neither works.

I'm using version v0.4.1.  No errors in logs other than ssh connection timeout.  I verified this using two different AWS accounts.

**Comment by rwildgrube** [comment]
Even now on packer version 0.11.0 this problem is still happening. After Specifying the subnet_id and vpc_id it does create the temporarily Security Group but  does not attach to the instance and instead uses the default. Is there anything I am missing?

**Comment by rickard-von-essen** [comment]
@rwildgrube this was fixed three years ago. Please don't comment on old and fixed issues. Open a new issue and provide the info requested.

**Comment by grv87** [comment]
@rwildgrube, I experienced the same issue. It seems there is a gap in documentation about required permissions. 0f4d2341cb87c87b92b582f63c82e3834a0d349a fixed it.
