### ISSUE TITLE
Feature Request: Oracle OCI set custom disk size

### ISSUE THREAD

**Issue by Marcus-James-Adams** [hashicorp/packer#7117]
Oracle OCI allows the user to set a custom disk size when provisioning instances.
This auto extends the system disk to mach this new size if it provisioned using a master image.
It would be good if this option was added to the OCI provisioner.

**Comment by kostasns** [comment]
Hello, is there any potential update on this feature request ?

**Comment by SwampDragons** [comment]
We haven't had a chance to work on it, but we'd happily review Pull Requests making this change.
