### ISSUE TITLE
Using user variables in provisioner file

### ISSUE THREAD

**Issue by wizurijyq** [hashicorp/packer#7122]
Any way to upload a file with custom user variables in it, kinda like the terraform template?

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out!  I think you want the `-var-file` flag. https://www.packer.io/docs/templates/user-variables.html#from-a-file.  

Normally, we reserve GitHub issues for feature requests and bug reports; for more general questions like this you're likely to get better responses if you ask them on the [mailing list](https://groups.google.com/forum/#!forum/packer-tool).

**Comment by SwampDragons** [comment]
The -var-file flag makes variables available to the packer template for use in various provisioner or builder options; if you want the provisioner to be able to source variables, you'll need to check specific docs for each provisioners, but many of them have an [environment_vars](https://www.packer.io/docs/provisioners/shell.html#environment_vars) option which you can use; you can set one of your user vars in the environment vars and then reference it from inside of your script.
