### ISSUE TITLE
sha256 of packer 1.3.2 zip files recently changed

### ISSUE THREAD

**Issue by gwohletz** [hashicorp/packer#7123]
Recently the sha256 of the packer zip files located at https://releases.hashicorp.com/packer/1.3.2/ changed, was there some sort of patch to the already released 1.3.2?

**Comment by SwampDragons** [comment]
Good catch -- we didn't patch them, but we re-ran the release because it turned out a few of our less commonly used builds failed to upload.

I think the sha changed because @azr ran the second release whereas I ran the first, and our GOPATHs are different.

**Comment by azr** [comment]
I confirm !
