### ISSUE TITLE
better error/docs for using VMware/ESX builder w/"tools_upload_flavor"

### ISSUE THREAD

**Issue by tehranian** [hashicorp/packer#713]
Sorry to file another docs/error message bug, but here goes... Apparently one cannot use the ESX builder when "tools_upload_flavor" is specified.  If you do, you will get the following error:

```
Build 'vmware' errored: Couldn't find VMware tools for 'linux'! VMware often
downloads these tools on-demand. However, to do this, you need to create
a fake VM of the proper type then click the 'install tools' option in the 
VMware GUI.
```

This is because the ESX 5 driver does not implement "ToolsIsoPath()".  See: https://github.com/mitchellh/packer/blob/master/builder/vmware/driver_esx5.go#L100-L102

Please consider improving the error message (since the error message is misleading and there is no valid place to put an ISO file to satisfy this error), fixing the docs, or fixing the ESX driver implementation to support uploading VMware Tools.

Thanks!
Dan

**Comment by johnt337** [comment]
This still appears to be an issue with Packer v0.7.5 and VMWare Player 7 on OSX.
Removing the "tools_upload_flavor" setting and manually setting the "tools_upload_path" is a functional workaround.

**Comment by fr34k8** [comment]
hmm affects me too, workaround seems to be good, but @mitchellh pls take care of this.
packer -v
0.10.0
