### ISSUE TITLE
Feature Request: Azure - add 'user-assigned managed identity'

### ISSUE THREAD

**Issue by nirving-deloitte** [hashicorp/packer#7131]
Afternoon,
I have a requirement to get files from the Azure Storage Blob via Ansible.
It has the ability to use the user-assigned managed identity to get the file and I can create the identity, but have not figured out how to attach it to the Virtual Machine being packed.

If this can be achieved another way please could you let me know? I have tried with 1.3.3 to not include the necessary subscription and client details, but this just makes a request to a URL that is not navigable. I am assuming it is meant to be run in the Azure VM, but not 100% clear.

there is equivalent functionality in Terraform - https://www.terraform.io/docs/providers/azurerm/r/virtual_machine.html#identity

Regards
Nicholas Irving

**Comment by nirving-deloitte** [comment]
Evening,
I have made an attempt to make this update and for some reason it is crashing out and I am not sure why.

https://github.com/hashicorp/packer/compare/v1.3.2...nirving-deloitte:feature/7131

```
λ bin\packer.exe build --force --debug azure.json
Debug mode enabled. Builds will not be parallelized.
azure-arm output will be in this color.

==> azure-arm: Running builder ...
    azure-arm: Creating Azure Resource Manager (ARM) client ...
    azure-arm: temp admin user: 'packer'
    azure-arm: temp admin password: 'UEesLOh9uZbRLMu9vWCWcYpoVIa6Chye'
    azure-arm: temp ssh key: azure-arm-pkrvmp6zmhtisyx.pem
==> azure-arm: Creating resource group ...
==> azure-arm:  -> ResourceGroupName : 'packer-Resource-Group-p6zmhtisyx'
==> azure-arm:  -> Location          : 'Australia Southeast'
==> azure-arm:  -> Tags              :
==> azure-arm:  ->> Creator : Nicholas Irving
==> azure-arm:  ->> madewith : HashiCorp Packer
==> azure-arm: Pausing after run of step 'StepCreateResourceGroup'. Press enter to continue.
==> azure-arm: Validating deployment template ...
==> azure-arm:  -> ResourceGroupName : 'packer-Resource-Group-p6zmhtisyx'
==> azure-arm:  -> DeploymentName    : 'pkrdpp6zmhtisyx'
==> azure-arm: Pausing before cleanup of step 'StepCreateResourceGroup'. Press enter to continue.
==> azure-arm:
==> azure-arm: Cleanup requested, deleting resource group ...
==> azure-arm: Resource group has been deleted.
Build 'azure-arm' errored: unexpected EOF

==> Some builds didn't complete successfully and had errors:
--> azure-arm: unexpected EOF

==> Builds finished but no artifacts were created.
```

Does anybody have any advice on how to debug packer in general?
[azureManagedIdentity.txt](https://github.com/hashicorp/packer/files/2697555/azureManagedIdentity.txt)

**Comment by nirving-deloitte** [comment]
Create a version based on v1.3.2 that includes this support
https://github.com/hashicorp/packer/compare/master...nirving-deloitte:feature/7131?expand=1

However it fails with this
```
==> azure-arm: Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details." Details=[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"InvalidParameter\",\r\n    \"message\": \"ResourceIdentity Type must be provided and set to \\\"SystemAssigned\\\".\",\r\n    \"target\": \"resourceIdentity.type\"\r\n  }\r\n}"}]
```

There are also a couple of caveat, 
- you cannot create the Managed Identity in the packer generated resource group before hand as that resource group does not exist. So then you must supply your own resource group via `build_resource_group_name`
- it supports multiple Identity ID via
```
            "identity_type": "UserAssigned",
            "identity_ids": [
                "vmmanageduser"
            ]
```

Not sure if this is version of the API being used, as it is different to Terraform.

Anyway will see if I can get this to work.

**Comment by nirving-deloitte** [comment]
Updated the compute api version and this works.

Will work on the test cases to support the future Pull Request.

**Comment by krypto92** [comment]
I am also having similar requirement to use the user-assigned managed identity.

@nirving-deloitte are you going to merge the changes in this repo ?

**Comment by nirving-deloitte** [comment]
@krypto92 I have not worked on the test cases for this yet. 
Will try and start doing this this week so that I can raise a pull request.

**Comment by krypto92** [comment]
@nirving-deloitte any update on your changes?

**Comment by dbilleci-lightstream** [comment]
Also interested in this.. I thought this was already merged into Packer.. We have a VM that needs to pull containers from ACR during boot.

**Comment by raidlman** [comment]
Is there any update on this?

**Comment by pmozbert** [comment]
is this working yet?
