### ISSUE TITLE
vmware-vmx - Remote ESXi Destroy VM Failing - packer 1.3.3

### ISSUE THREAD

**Issue by e-mow** [hashicorp/packer#7140]
With the introduction of vmware-vmx builder on ESXi I am having cleanup issues when the build fails and packer wants to clean up the VM.

The protected file extensions in this line are requiring .vmxf files to stick around. The problem with this is that the vim-cmd vmsvc/destroy vmid call does not remove the file with this extension. This leaves the directory and the file still on the datastore and packer hangs waiting for the directory to go away.

https://github.com/hashicorp/packer/blob/78c0b7bd9c1c2464c407fadbed3da4e94e627796/builder/vmware/common/step_clean_files.go#L16

Setup:
- Packer 1.3.3
- All versions of Windows 2008-2019
- ESXi 6, 6.5, 6.7 (We upgraded the ESXi server as we wanted to upgrade and to also see if this issue would go away.)
- The .vmxf file only appears after VMWare Tools has been installed in Windows and the Windows VM has been rebooted.
- * VMWare Tools 10.0.9, 10.2.5, 10.3.5 were tested.

Contents of the .vmxf file:
`<?xml version="1.0"?>
<Foundry><VM/></Foundry>
`

**Comment by usmcfiredog** [comment]
Is there anyway to output as an OVA or a way to use the ovftool at the end to do it?

**Comment by e-mow** [comment]
> Is there anyway to output as an OVA or a way to use the ovftool at the end to do it?

If we keep_registered, and export it will allow that process to work.

The main issue is cleaning up the VM when something fails without having to go to the datastore and delete the file and directory. The packer process hangs waiting for the directory to become empty and never dies so putting code around the packer process to handle the cleanup on failure will not work either.

Update as well, this same issue happened on a Ubuntu image using open-vm-tools.

**Comment by usmcfiredog** [comment]
so the only way to export an ova is to use the shell-local post-processor? Also when using that post-processor you cannot remove the original files used.

**Comment by e-mow** [comment]
The export option of vmware-vmx works (it uses ovf_tool to export). The part that doesn't work is during a cleanup event because the build failed or when keep_registered = false as we no longer want the VM to be in ESXi.

Since we are doing multiple stages we are using keep_registered = true and don't run into this issue unless part of the build fails.

**Comment by usmcfiredog** [comment]
The thing is I wan't to export the ova locally as I don't have an ESXi server. It always says ==> vmware-iso: Skipping export of virtual machine (export is allowed only for ESXi)...

**Comment by SwampDragons** [comment]
@usmcfiredog We don't currently have that as an option, and I think it's a separate problem from the one being described in the original issue; can you please open a new issue with your feature request so that I can track it separately?

**Comment by SwampDragons** [comment]
Thanks for reporting this, @e-mow.

I wonder if the solution is as simple as adding a new cleanup function into the Cleanup() call that does delete these files in the case of an error or keep_registered == false

https://github.com/hashicorp/packer/blob/78c0b7bd9c1c2464c407fadbed3da4e94e627796/builder/vmware/common/step_clean_files.go#L68

**Comment by e-mow** [comment]
@SwampDragons I just got back to looking at this item as well and got to the bottom of what ESXi/vCenter is doing. When the clone of a vmx happens the vmx file has a key:value of extendedConfigFile = "sourcevmname.vmxf"

This causes ESXi/vCenter to improperly clean up the VM as it thinks that the file that gets created on boot/vmware tools install is not part of the VM. Why ESXi/vCenter doesn't read this out of the vmx file and use it when cleaning up is beyond my knowledge of ESXi.

Working solution on packer 1.3.3:
I added "vmx_data": { "extendedConfigFile": "{{ user `myvmnamevariable`}}.vmxf" } to my template file and VMWare cleans up the VM correctly and on delete / keep registered = false everything cleans up properly.

Preferably packer would just set the vmx_data for that option to the name of the VM instead of having to set it in the vmx_data options.

Hopefully this is a cleaner solution and actually gets to the bottom of why this is happening.

**Comment by SwampDragons** [comment]
We already have `extendedConfigFile` set in our default vmx that we generate for iso builds, and I've added it during the configure vmx step. 

here are some binaries with the patch applied; can you test it out for me and let me know if it works for you?

windows: [packer.zip](https://github.com/hashicorp/packer/files/2902722/packer.zip)

osx:  [packer.zip](https://github.com/hashicorp/packer/files/2902738/packer.zip)

linux: [packer.zip](https://github.com/hashicorp/packer/files/2902764/packer.zip)

**Comment by e-mow** [comment]
I tested the linux file today and the vmx files are showing the wrong data it looks like after the clone. If you look at the directory and .vmx file name they are from the vm_name and display_name in the template. However after the first phase for the os install the vmxf setting didn't get updated.

Template:
- "vm_name": "packer-{{user `vm_name`}}-02-vmware-tools",
- "display_name": "packer-{{user `vm_name`}}-02-vmware-tools",

VMX file extedndedconfigfile settings:

CENT 7.2:
- packer-cent7264-02-vmware-tools/packer-cent7264-02-vmware-tools.vmx:extendedconfigfile = "packer-cent7264-01-os.vmxf"
- packer-cent7264-01-os/packer-cent7264-01-os.vmx:extendedconfigfile = "packer-cent7264-01-os.vmxf"
- 20190226_CENT7264/20190226_CENT7264.vmx:extendedconfigfile = "packer-cent7264-01-os.vmxf"
- packer-cent7264-01-os/packer-cent7264-01-os.vmx:extendedconfigfile = "packer-cent7264-01-os.vmxf"

Windows 2019:
- packer-w19se64-01-os/packer-w19se64-01-os.vmx:extendedconfigfile = "packer-w19se64-01-os.vmxf"
- packer-w19se64-02-patched/packer-w19se64-02-patched.vmx:extendedconfigfile = "packer-w19se64-01-os.vmxf"
- packer-w19se64-03-templateprep/packer-w19se64-03-templateprep.vmx:extendedconfigfile = "packer-w19se64-01-os.vmxf"
- packer-w19se64-04-vmware-tools/packer-w19se64-04-vmware-tools.vmx:extendedconfigfile = "packer-w19se64-01-os.vmxf"
- packer-w19se64-05-vmware-zerodisk/packer-w19se64-05-vmware-zerodisk.vmx:extendedconfigfile = "packer-w19se64-01-os.vmxf"
- 20190226_W19SE64/20190226_W19SE64.vmx:extendedconfigfile = "packer-w19se64-01-os.vmxf"

**Comment by SwampDragons** [comment]
Ah, I see. We need to overwrite the extended config, rather than just setting it if it's empty.  Try this one?
[packer.zip](https://github.com/hashicorp/packer/files/2907321/packer.zip)

**Comment by e-mow** [comment]
Ran another test with the latest zip and the setting did not change in the vmx files.

Just to confirm that the old way of setting the setting in vmx_data would update the vmx file I put the code back into the template and it imported correctly into the vmx.

**Comment by e-mow** [comment]
I did notice that my previous tests were generating the vmxf file currently based on the VM Name during the stage that VMWare tools or Open-VM-Tools gets installed when using vmx-data. What I didn't realize until this set of testing is that the vmxf file is being copied to all future stages and when I delete the VM from the vCenter UI vmware will not remove the vmxf if the name does not match the VM. I am making an assumption here that the vmware-vmx clone process must copy all files in the directory. If this is the case even after setting the extendedconfigfile option will leave a file in all future stages named after the vm from the stage where VM tools is installed. This will leave the directory and the vmxf on the datastore. This then breaks future runs of the template build process and leaves the datastore with orphaned files.

Examples:
Windows VMs, there are 4 stages before the 5th stage which installs VM Tools. When VMWare tools gets installed that is the first time that the vmxf file is generated.
Each of these final phases had the same file from the previous stage copied over.
- W08EER264, stage5.vmxf instead of stage6.vmxf or no vmxf
- W08SER264, stage5.vmxf instead of stage6.vmxf or no vmxf
- W10PRO64, stage5.vmxf instead of stage6.vmxf or no vmxf
- W10ENT64, stage5.vmxf instead of stage6.vmxf or no vmxf
- W12SER264, stage5.vmxf instead of stage6.vmxf or no vmxf
- W16SE64, stage5.vmxf instead of stage6.vmxf or no vmxf
- W19SE64, stage5.vmxf instead of stage6.vmxf or no vmxf
- W7PRO64, stage5.vmxf instead of stage6.vmxf or no vmxf

Linux VMs, install VMWare Tools or Open-VM-Tools either during the initial OS install or stage 2. There is only 3 stages for Linux.
#Systems that install Open-VM-Tools in Stage 1 that get a vmxf file generated and copied to other stages.
- CENT7264, stage1.vmxf instead of stage3.vmxf or no vmxf in the next stages.
- OEL7264, stage1.vmxf instead of stage3.vmxf or no vmxf in the next stages.
- RHEL7264, stage1.vmxf instead of stage3.vmxf or no vmxf in the next stages.
- UBUNTU1404564, stage1.vmxf instead of stage3.vmxf or no vmxf in the next stages.

#Systems that install VMWare Tools in Stage 2 that get a vmxf file generated and copied to the other stages.
- CENT51032, stage2.vmxf instead of stage3.vmxf or no vmxf in the next stages.
- CENT51064, stage2.vmxf instead of stage3.vmxf or no vmxf in the next stages.
- CENT51132, stage2.vmxf instead of stage3.vmxf or no vmxf in the next stages.
- CENT51164, stage2.vmxf instead of stage3.vmxf or no vmxf in the next stages.
- CENT6664, stage2.vmxf instead of stage3.vmxf or no vmxf in the next stages.
- CENT6764, stage2.vmxf instead of stage3.vmxf or no vmxf in the next stages.
- CENT6864, stage2.vmxf instead of stage3.vmxf or no vmxf in the next stages.
- CENT6964, stage2.vmxf instead of stage3.vmxf or no vmxf in the next stages.
- CENT61064, stage2.vmxf instead of stage3.vmxf or no vmxf in the next stages.
- CENT6764, stage2.vmxf instead of stage3.vmxf or no vmxf in the next stages.
- SLES11364, stage2.vmxf instead of stage3.vmxf or no vmxf in the next stages.
- SLES11464, stage2.vmxf instead of stage3.vmxf or no vmxf in the next stages.

#Systems that install Open-VM-Tools in Stage 1 or VMWare tools in Stage 2 that never generate a vmxf file at all. Why VMWare is picking and choosing when to generate the vmxf file must have something to do with the version of Open-VM-Tools or VMWare tools and a combination of OS version as the same VMWare tools for CENT/RHEL/OEL 5.x, 6.x is the same. The media for CENT/RHEL/OEL above 7.2 uses a different version of Open-VM-Tools as well.

- CENT7364
- CENT7464
- CENT7564
- CENT7664
- RHEL51032
- RHEL51064
- RHEL51132
- RHEL51164
- RHEL6632
- RHEL6764
- RHEL6864
- RHEL6964
- RHEL61064
- RHEL7364
- RHEL7464
- RHEL7564
- RHEL7664
- OEL51032
- OEL51064
- OEL51132
- OEL51164
- OEL6664
- OEL6764
- OEL6864
- OEL6964
- OEL61064
- OEL7364
- OEL7464
- OEL7564
- OEL7664

**Comment by e-mow** [comment]
It looks like this is the line that is cloning all files in the directory outside of the VMDK and the VMX file. If this line could be updated to include "! -name '*.vmxf'" then the file wouldn't get copied to the next stage.
https://github.com/hashicorp/packer/blob/0e8afa37d5623ab5d262ef0b0eacaa45dba18206/builder/vmware/common/driver_esx5.go#L71

Injecting the proper name into the extendedConfigFile vmx option would still be needed as well.

**Comment by e-mow** [comment]
Looking at the log in relation to the code linked in my last comment here is the example of the copy of the vmxf file. You will see that the stage 1 vmxf file is being copied to the 3rd stage from the second stage.

>2019/02/28 00:12:29 packer: 2019/02/28 00:12:29 [DEBUG] starting remote command: find "/vmfs/volumes/template_datastore/packer-cent7264-02-vmware-tools" ! -name '*.vmdk' ! -name '*.vmx' -type f ! -size 0
2019/02/27 22:36:10 packer: 2019/02/27 22:36:10 [DEBUG] Opening new ssh session
2019/02/27 22:36:10 packer: 2019/02/27 22:36:10 [DEBUG] starting remote command: cp "/vmfs/volumes/template-datastore/packer-cent7264-02-vmware-tools/packer-cent7264-01-os.vmxf"
 "/vmfs/volumes/template-datastore/packer-cent7264-03-finalstage"

**Comment by e-mow** [comment]
I setup a go environment last night and figured out what was happening.
Your commit at the link below has the C and F in the extendedConfigFile parameter in caps. However it looks like the vmx file needs to be all in lowercase as referenced in the next link from the vmx_data inputs being forced to lower in the key.
https://github.com/hashicorp/packer/blob/c770d8d80459a91a7c6a3fb9a7aabe419a36faec/builder/vmware/common/step_configure_vmx.go#L105 
https://github.com/hashicorp/packer/blob/c770d8d80459a91a7c6a3fb9a7aabe419a36faec/builder/vmware/common/step_configure_vmx.go#L59-L64

This is why when I had the setting in vmx_data set it was working though testing your commit did not work.

Changing the line to read will solve the issue.
`       vmxData["extendedconfigfile"] = fmt.Sprintf("%s.vmxf", s.DisplayName)`

**Comment by e-mow** [comment]
> It looks like this is the line that is cloning all files in the directory outside of the VMDK and the VMX file. If this line could be updated to include "! -name '*.vmxf'" then the file wouldn't get copied to the next stage.
> [packer/builder/vmware/common/driver_esx5.go](https://github.com/hashicorp/packer/blob/0e8afa37d5623ab5d262ef0b0eacaa45dba18206/builder/vmware/common/driver_esx5.go#L71)
> 
> Line 71 in [0e8afa3](/hashicorp/packer/commit/0e8afa37d5623ab5d262ef0b0eacaa45dba18206)
> 
>  filesToClone, err := d.run(nil, "find", strconv.Quote(srcDir), "! -name '*.vmdk' ! -name '*.vmx' -type f ! -size 0") 
> Injecting the proper name into the extendedConfigFile vmx option would still be needed as well.

Testing this in the custom build worked as well. Since this driver is only for ESXi it won't affect any other hypervisors or VMWare Workstation / VMWare Player.

`        filesToClone, err := d.run(nil, "find", strconv.Quote(srcDir), "! -name '*.vmdk' ! -name '*.vmx' ! -name '*.vmxf' -type f ! -size 0")`

**Comment by SwampDragons** [comment]
Sounds like you've got a patch -- care to open a PR so you can get the credit, or would you rather I apply it myself.
