### ISSUE TITLE
Misleading error from AWS EBS builders with ENA on Spot Instances

### ISSUE THREAD

**Issue by jen20** [hashicorp/packer#7143]
If using a combination of a spot instance, and `ena_support: "true"`, the following error message is given by the various EBS builders:

> * Spot instances do not support modification, which is required when either `ena_support` or `sriov_support` are set. Please ensure you use an AMI that already has either SR-IOV or ENA enabled.

The AMI actually makes no difference - the error is returned as a function of the various configuration flags and do not take any AMI properties into account - for example:

https://github.com/hashicorp/packer/blob/9573013d3ab441017592f01fee1a468e87136942/builder/amazon/ebssurrogate/builder.go#L89-L92

At this point I'm not entirely sure if the behaviour can be fixed to support creating an ENA-enabled AMI on a spot instance, or whether the error message needs clarifying.

**Comment by SwampDragons** [comment]
Thanks for reporting. I believe the assumption is that you aren't setting the ena_support etc flags unless the base ami doesn't already have that stuff enabled.

Historical context:

https://github.com/hashicorp/packer/pull/5679

What do you think would be a better way of describing this?
