### ISSUE TITLE
Add configuration options to qemu builder to specify cpu count and memory size

### ISSUE THREAD

**Issue by ladar** [hashicorp/packer#7149]
@arizvisa I noticed your pull requests which normalize how cpu/memory values are configured when using the vmware/parallels/virtualbox builders, so I'm including your name on this issue. That's because I noticed while updating my templates to the new and improved standard, that the `qemu` builder still lacks this functionality... so I thought I'd open an issue. Feel free to close this ticket if  the `qemu` builder ostracization was intentional.

**Comment by vtolstov** [comment]
Can you share docs for cpu and memory options that qemu lacks?
May be i add it,because it useful for me too.

**Comment by ladar** [comment]
@vtolstov is [this](https://github.com/lavabit/robox/blob/master/generic-libvirt.json#L1099-L1107) what you need?

It should be relatively simple... just parse the cpus/memory values and pass them as arguments to the qemu binary. 

My workaround was setting them directly via the `qemuargs` key, but I'm assuming the code gods want to move away from that approach for "basic" parameters like cpu count and memory allocation. I'm also assuming that in the case of common parameters, they want to make the key names consistent across builders... presumably so configurations are more portable.

**Comment by vtolstov** [comment]
As i understand i need to provide
"cpus" and "memory".
I think i can add it today.please wait.


ср, 26 дек. 2018 г., 23:05 Ladar Levison notifications@github.com:

**Comment by vtolstov** [comment]
if that possible, please try #7156

**Comment by arizvisa** [comment]
@ladar, nah. it wasn't intentional, i just saw that that adding cpu count and memory for those 3 was simple and straightforward so i thought i'd submit it to the devers.

**Comment by ladar** [comment]
With https://github.com/hashicorp/packer/pull/7156 having been merged, I think this issue can be closed...

I would like to do more testing, but if I run across any more issues, I'll just open a new issue... that is, unless, the powers at be want to discuss also adding config parameters to control 'cores' and 'threads'. Along the same lines as https://github.com/hashicorp/packer/issues/7190 ...
