### ISSUE TITLE
Modify the hyper-v builder cpu count and memory size keys in the name of conformity

### ISSUE THREAD

**Issue by ladar** [hashicorp/packer#7150]
@arizvisa I noticed your pull requests which normalize how cpu/memory values are configured when using the vmware/parallels/virtualbox builders, so I'm including your name on this issue. That's because I noticed while updating my templates to the new and improved standard, that the `hyperv-iso` builder uses the heretical key identifier `cpu` instead of `cpus` and the insidious key `ram_size` instead of the conformant name, `memory` ... so I thought I'd open an issue. I know how much Microsoft likes to do their own thing, and wasn't sure if this was an attempt to accomodate that free spirit. If so, feel free to close this issue.

However, if normalization across the builders is indeed the goal, perhaps you could update the `hyperv-iso` keys to match the other builders.. while also adding logic to map any cpu/ram_size values `packer` enconters to the new class variables/configuration keys automagically. Of course, might I suggest, _politely_ informing users about the change, and the deprecation (or is it decapitation) of the old scheme whenever `packer validate` is run...

**Comment by ladar** [comment]
I woke up last night in a cold sweat. It seems I suddenly remembered that Microsoft now owns GitHub. So I take back everything I wrote above, and suggest in its stead, that perhaps all the other builders be modified to match the Hyper-V schema? All hail Bill Gates.

**Comment by arizvisa** [comment]
yeah, i added those all in one set because they were all local virtualization solutions. Like all the remote ones have their own methods which I don't really use. But in terms of maintaining conformity or having a standard schema, I leave that up to the maintainers.

**Comment by SwampDragons** [comment]
Fair point, Ladar. To bring the hyper-v builder into conformity with the other builders we'll need to deprecate the current setup (loudly) during one of our minor releases, and write a fixer. We'll probably also need to talk directly with Microsoft since they use Packer under the hood in Azure and I wouldn't want to arbitrarily change things on them.

**Comment by ladar** [comment]
@SwampDragons when you talk to Microsoft, can you ask them about the boot order issue in #7147 as well? Changing the boot order to HD then CD (from CD, then HD) is a critical fix... and should probably be updated for the generation 2 machines as well.
