### ISSUE TITLE
Documentation on virtualbox-iso contradicts about required iso_url configuration

### ISSUE THREAD

**Issue by grv87** [hashicorp/packer#7157]
[Documentation for virtualbox-iso builder](https://www.packer.io/docs/builders/virtualbox-iso.html) lists `iso_url` in `Required` section, but later says:
> Only one of iso_url or iso_urls can be specified

These two statements contradict each other.

**Comment by grv87** [comment]
@SwampDragons, could you tell a reason why this issue is closed?

**Comment by azr** [comment]
Hello @grv87 it's right up your message
> @/SwampDragons SwampDragons closed this in #7162 on 4 Jan

a fix was merged for it ! 🙂
