### ISSUE TITLE
Default folder for plugin seems to have changed with version 1.3.3

### ISSUE THREAD

**Issue by theonlydude1** [hashicorp/packer#7160]
Hello,
Since the version 1.3.3 I have a strange behavior with the default plugin folder. 
All my plug-ins are in %APPDATA%/packer.d/plugins but with the version 1.3.3 I have this error:
https://gist.github.com/theonlydude1/86736e79a072d06f5570b1d9e7329eaa

But I've found another packer.d folder in %UserProfile% and when I put my plugins here it works.
I can't find any trace of this folder change in the changelog or the documentation, so should i consider it as a normal behavior or as a bug ?

Thanks.

**Comment by azr** [comment]
Hello @theonlydude1, ah bummer. 'Home guessing' did change in https://github.com/hashicorp/packer/pull/7036. Before this pr we were using a shell to determine home. Now packer is using golang facilities ([os/user](https://golang.org/pkg/os/user/#User)).

We really did not expect this to be a breaking change, sorry you had to debug this and thanks for telling us.

I'll try to see about adding this to the lists of breaking change.

**Comment by theonlydude1** [comment]
Hi @azr  thanks for your quick answer and no problem for the debug :) I'll move my plugins in both folders until a formal confirmation of the proper one !

**Comment by azr** [comment]
Hey @theonlydude1, we treated this as a regression and reverted the behaviour introduced by #7036, the next release will contain the old behaviour.

Checking `%APPDATA%/packer.d/plugins` first then `%USERPROFILE%/packer.d/plugins`.
