### ISSUE TITLE
Feature request: Vmware-iso ova export locally

### ISSUE THREAD

**Issue by usmcfiredog** [hashicorp/packer#7165]
FOR FEATURES:

Right now when building a VM with Vmware-iso there is not option to export as an OVA/OVF. 

==> vmware-iso: Skipping export of virtual machine (export is allowed only for ESXi)...

this is the message I have to use. So I have to run a shell-local post processor to call the ovftool to create an OVA and delete the files used to make the OVA.

Can we please get a feature to allow an OVA to be created so that it can be easier to distribute it and save it.

**Comment by usmcfiredog** [comment]
Is there any status on this yet?

**Comment by ladar** [comment]
I think someone needs to step forward, and offer to implement it.

**Comment by tisba** [comment]
I'm pretty sure this is a regression.

With Packer 1.3.4, builder `vmware-vmx` I get the same message (`==> vmware-iso: Skipping export of virtual machine (export is allowed only for ESXi)`) when using the vagrant `post-processors`.

With 1.3.3 and before this worked fine.

**Comment by ladar** [comment]
@tisba looks like the export option [was hard coded to "esx5."](https://github.com/hashicorp/packer/blob/dca02c7b0706e8a31b74760d3a2035e44a11b65b/builder/vmware/common/step_export.go#L69-L72)

What happens if you simply remove that check, does it work?

**Comment by SwampDragons** [comment]
I think I'm not going to address this until after we split the local and remote functions into their own builders (see #7212) because it's got a workaround and it'll probably add a pile of if/else to that export step.
