### ISSUE TITLE
AWS EBS Builder throws Misleading error when there is no default VPC and vpc_id is set, but subnet_id is not.

### ISSUE THREAD

**Issue by bgshacklett** [hashicorp/packer#7167]
- Packer version from `packer version`:  v1.3.3
- Host platform : Windows 10 Version 1709
- Debug log output from `PACKER_LOG=1 packer build template.json`.: https://gist.github.com/bgshacklett/4253650df0e405191a29d3804b52634c
- The _simplest example template and scripts_ needed to reproduce the bug. https://gist.github.com/bgshacklett/1b8c5b0228c2ebf83f6365b6bf869048
  
# Summary
If the `vpc_id` argument is set and the `subnet_id` argument is unset when running against an AWS account with no default VPC, a `VPCIdNotSpecified` error will be received. This is misleading as the VPC ID has been specified by the user.

# Steps to Reproduce:
1. Ensure that the AWS account used for testing does _not_ have a Default VPC.
2. Run `packer build` against the configuration provided above.

## Expected Behavior
* An error should be received indicating that the `subnet_id` argument is required.

## Actual Behavior
* The error `VPCIdNotSpecified` is received, indicating that the VPC ID has not been set.

# Potential Solutions
* Remove the `vpc_id` argument from the builder.  

   **Reasoning:** The `vpc_id` argument requires that the `subnet_id` argument be set. As of #4879, when the `subnet_id` argument is set, the builder will automatically search AWS for the parent VPC, making the `vpc_id` argument redundant in all cases.  

   **Potential Downsides:** 
   * The `vpc_id` argument may currently be used as a safety mechanism to ensure that Packer will always run in a given VPC, even if an erroneous subnet ID is passed in.
* Validate that the `subnet_id` argument has a valid value when the `vpc_id` argument is set.  

   **Reasoning:** Per the documentation, the `subnet_id` argument is required if the `vpc_id` argument is set. It is reasonable to expect this to be enforced in code.  

   **Potential Downsides:**
   * Work required to implement the change
   * More code means more potential for bugs.

* Perform further error handling when a `VPCIdNotSpecified` error is received (e.g.: check for the existence of a `subnet_id` argument and [re-]throw the appropriate error).
   **Reasoning:** The `VPCIdNotSpecified` result from the API is ambiguous. Packer has enough information, at this point, to throw a more specific error.

   **Potential Downsides:**
   * Work required to implement the change
   * More code means more potential for bugs; potential for errors to be squashed.

**Comment by SwampDragons** [comment]
I think adding some extra template validation is totally reasonable.

**Comment by SwampDragons** [comment]
What would happen if you had an account that _does_ have a default vpc_id though?  Would that work?

I think a good conservative approach here would be to add a check for the VPCIdNotSpecified error type here, and prepend it with a clear Packer error message with your warning about subnet ids.
https://github.com/hashicorp/packer/blob/16149844a7a52b6d4f18a71f43b76b643a4cb851/builder/amazon/common/step_security_group.go#L96-L101

**Comment by SwampDragons** [comment]
We probably also want to add a note to the docs with this gotcha.

**Comment by SwampDragons** [comment]
As an aside -- the reason I don't want to remove vpc_id or add validation that fails early on is that looking at the code, I think that this problem wouldn't happen if you were using a security group filter; this process happens early enough in the build that I think a clearer catch-and-error message is the way to go.

**Comment by rickard-von-essen** [comment]
There are three cases we need to consider, EC2 Classic (with no VPC), a default VPC (`vpc_id` is not required), and where there are no default VPC.

**Comment by SwampDragons** [comment]
yeah, I think catching the specific error when it's thrown and adding a helpful hint to it is the way to go.
