### ISSUE TITLE
openstack: Possibility to attach floating ip to specific network

### ISSUE THREAD

**Issue by musaa1** [hashicorp/packer#7171]
Hello Everyone

I'm using packer 1.3.1 and I'm trying to create an image in an openstack environment.

In our setup, the temporary instance that is created by packer has 2 networks (Management and DMZ network). I also map a external network to this instance for creating a floating IP address. The floating IP address must be attached on a port of the DMZ network.

The problem is that I cannot configure on which network the floating IP address shall be attached. So when packer creates the instance, there is a 50% chance that the right network will be took for the floating IP address. If the floating IP is attached on the wrong network, the packer run fails.

Can you help me?

**Comment by rickard-von-essen** [comment]
Doesn't `floating_ip_network` do this?

**Comment by musaa1** [comment]
With `floating_ip_network` you say from which external network the floating ip shall be created. But then the floating ip has to be mapped with a port of the instance. The 2 ports from my instance are the interfaces where the IP address are set. One port for Management, and one port for DMZ. 

And my problem is that I don't see a possibility to specify the port of the instance where the floating ip shall be attached. I should be capable to say that the floating ip shall be mapped to the port of the instance where the DMZ network is configured. But unfortunately, very often the floating ip gets attached to the Management network and then the whole run fails because my Management network has no connection with the external network.

**Comment by rickard-von-essen** [comment]
Oh, yes that is correct. Just to double check `ssh_interface` doesn't help either? (I don't remember much details about OS networking)

**Comment by musaa1** [comment]
No, unfortunately `ssh_interface` doesn't help. I believe this is something that at the moment can not be configured with packer but essential for my use case.

**Comment by jprorama** [comment]
This is due to the return first interface behavior in [GetInstancePort](https://github.com/hashicorp/packer/blob/master/builder/openstack/networks.go#L69).    See proposed fix #7884 .
