### ISSUE TITLE
vmware-iso build failing due to missing network VMware Fusion network config.

### ISSUE THREAD

**Issue by spstratis** [hashicorp/packer#7172]
**Packer version:** Packer v1.3.3
**Host Platform:** MacOS Mojave 10.14.2 (18C54)
**Packer Script example:** https://gist.github.com/spstratis/886e341333e37885a784d4bb17c5e178
**Packer Debug Log:** https://gist.github.com/spstratis/c4ba032437b36d94f1fafcd0efcd4f49

Hello, I'm trying to make a really simple vmware-iso that has ubuntu installed just to test out the packer build process for it. When ever I attempt to build it,  it fails due to the  networking folder for VMWare Fusion not being found. 

`==> vmware-iso: Could not find networking conf file: /Library/Preferences/VMware Fusion/networking`

I installed VMWare Fusion 11 prior to attempting to run packer, and made sure to close out the app and reopen it again just for good measure. Any help would be greatly appreciated, thanks!

**Comment by rickard-von-essen** [comment]
Could you try to launch a VM manually?

**Comment by spstratis** [comment]
I was able to fix the issue. Even trying to build a machine manually was failing with this error:

``` Could not open /dev/vmmon:broken pipe. Please make sure that the kernel module 'vmmon' is loaded. ```

So I shut VMware down completely, went to the MacOS privacy and security settings and noticed that MacOS was blocking some features. Approved those, restarted Fusion and then ran packer script again and the build started...Now I'm the build process is hanging while `waiting for ssh to become available.`  I'll close this issue and open up a new one for that. 

this link help me solve this issue: https://communities.vmware.com/thread/598913

**Comment by SwampDragons** [comment]
I'm so glad you got it working; thanks for following up with us.
