### ISSUE TITLE
Update AliCloud SDK

### ISSUE THREAD

**Issue by oarmstrong** [hashicorp/packer#7175]
A [recent commit](https://github.com/denverdino/aliyungo/commit/948a31b982f52684d514288c9e20274fe17ee9bc) to the AliCloud SDK added the `eu-west-1` region. Please can you update the SDK to at least this version so that we can use that region.

**Comment by SwampDragons** [comment]
@chhaj5236

**Comment by chhaj5236** [comment]
@oarmstrong @SwampDragons  Yes, we'll take a look : )
