### ISSUE TITLE
Documentation Issue on Getting Started Guide - Redis

### ISSUE THREAD

**Issue by gep13** [hashicorp/packer#7179]
On this page: 

https://www.packer.io/intro/getting-started/build-image.html

There is the following:

> An astute reader may notice that we said earlier we'd be building an image with Redis pre-installed, and yet the template we made doesn't reference Redis anywhere. In fact, this part of the documentation will only cover making a first basic, non-provisioned image. The next section on provisioning will cover installing Redis.

However, there is no mention previously within the Getting Started guide that this is the intention of the guide.

I would be happy to submit a pull request to correct that issue, however, I would like some direction on what exactly is "expected", and what should be added.

**Comment by SwampDragons** [comment]
Thanks for opening this -- the rest of the installation guid is found in the https://www.packer.io/intro/getting-started/provision.html section, which is right after this one. Your confusion makes me think we should probably add a little clarity about what this "next" section is. I'll make a docs PR today.

**Comment by gep13** [comment]
@SwampDragons not sure if you followed what I was getting at.  I understood that the "next section" was referring to the provision section, however, in the build image section, the first sentence says...

> An astute reader may notice that we said earlier we'd be building an image with Redis pre-installed

Where was it `said earlier`?

The build image section is the first place that Redis is mentioned.

**Comment by SwampDragons** [comment]
Ah. I'll check the history and see if a paragraph was lost somewhere.

**Comment by gep13** [comment]
@SwampDragons Thank you for looking into this!
