### ISSUE TITLE
SSH retry when building CentOS for VirtualBox

### ISSUE THREAD

**Issue by levinotik** [hashicorp/packer#718]
I have the following template:
`
{
    "builders": [
        {
            "boot_command": [
                "<esc>",
                "<wait>linux ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/anaconda-ks.cfg<enter>"
            ],
            "boot_wait": "5s",
            "disk_size": 40000,
            "guest_os_type": "RedHat_64",
            "headless": true,
            "http_directory": "./http_directory",
            "iso_checksum": "bb9af2aea1344597e11070abe6b1fcd3",
        "iso_checksum_type": "md5",         
            "iso_url": "http://mirrors.usinternet.com/centos/6.4/isos/x86_64/CentOS-6.4-x86_64-netinstall.iso",
            "ssh_password": "vagrant",
            "ssh_username": "root",
            "ssh_wait_timeout": "20m",
            "type": "virtualbox",
            "vboxmanage": [
                ["modifyvm", "{{.Name}}", "--memory", "1024"],
                ["modifyvm", "{{.Name}}", "--cpus", "2"]
            ],
            "vm_name": "packer-centos-6_4-64"
        }
    ],
    "provisioners": [
        {
            "type": "shell",
            "script": "provisioners/main-provision.sh"
        }
    ],
    "post-processors": [
        {
            "type": "vagrant",
            "output": "centos-6_4-64_virtualbox.box"
        }
    ]
}
`

When I run `packer build` using this template, the output is as follows. As you can see, it continuously retries after getting the error `SSH handshake err: handshake failed: EOF`

virtualbox output will be in this color.

Warnings for build 'virtualbox':
- A shutdown_command was not specified. Without a shutdown command, Packer
  will forcibly halt the virtual machine, which may result in data loss.

==> virtualbox: Downloading or copying Guest additions checksums
    virtualbox: Downloading or copying: http://download.virtualbox.org/virtualbox/4.2.18/SHA256SUMS
==> virtualbox: Downloading or copying Guest additions
    virtualbox: Downloading or copying: http://download.virtualbox.org/virtualbox/4.2.18/VBoxGuestAdditions_4.2.18.iso
==> virtualbox: Downloading or copying ISO
    virtualbox: Downloading or copying: http://mirrors.usinternet.com/centos/6.4/isos/x86_64/CentOS-6.4-x86_64-netinstall.iso
==> virtualbox: Starting HTTP server on port 8081
==> virtualbox: Creating virtual machine...
==> virtualbox: Creating hard drive...
==> virtualbox: Creating forwarded port mapping for SSH (host port 3213)
... Opening conn for SSH to tcp 127.0.0.1:3213
2013/12/15 20:30:00 /usr/local/packer/packer-builder-virtualbox: 2013/12/15 20:30:00 Attempting SSH connection...
2013/12/15 20:30:00 /usr/local/packer/packer-builder-virtualbox: 2013/12/15 20:30:00 reconnecting to TCP connection for SSH
2013/12/15 20:30:00 /usr/local/packer/packer-builder-virtualbox: 2013/12/15 20:30:00 Opening conn for SSH to tcp 127.0.0.1:3213
2013/12/15 20:30:00 /usr/local/packer/packer-builder-virtualbox: 2013/12/15 20:30:00 handshaking with SSH
2013/12/15 20:30:00 /usr/local/packer/packer-builder-virtualbox: 2013/12/15 20:30:00 handshake error: handshake failed: EOF
2013/12/15 20:30:00 /usr/local/packer/packer-builder-virtualbox: 2013/12/15 20:30:00 SSH handshake err: handshake failed: EOF

**Comment by kakawait** [comment]
Same issue here, installation still stuck on 

![screen shot 2015-08-13 at 09 24 26](https://cloud.githubusercontent.com/assets/275609/9244618/2b96634c-419d-11e5-8e46-d5e9a0199fd1.png)

```
2015/08/13 09:25:05 packer-builder-virtualbox-iso: 2015/08/13 09:25:05 [DEBUG] SSH handshake err: ssh: handshake failed: EOF
2015/08/13 09:25:12 packer-builder-virtualbox-iso: 2015/08/13 09:25:12 [INFO] Attempting SSH connection...
2015/08/13 09:25:12 packer-builder-virtualbox-iso: 2015/08/13 09:25:12 reconnecting to TCP connection for SSH
```
