### ISSUE TITLE
[docs] please document verion new paramiters/features are introduced in

### ISSUE THREAD

**Issue by ghost** [hashicorp/packer#7182]
# [docs] please document verion new paramiters/features are introduced in
please include in the documentation page about a newly added configuration directive, the minimum release version required to use said directive

**Comment by SwampDragons** [comment]
Thanks for opening. We're aware that this is a pain point, and internally HashiCorp is working on versioned docs for all of its products.

**Comment by tenthirtyam** [comment]
I'd suggest that this issue could be closed. Recent updates to developer.hashicorp.com provides documentation versioning for both Packer and the Packer Plugin listed under Integrations.

And, of course, a release should note all changes for both of the above.

Suggest closing this item. @nywilken @lbajolet-hashicorp

**Comment by nywilken** [comment]
Thanks @tenthirtyam closing.
