### ISSUE TITLE
Enhancement: Option to deliberately slow down boot_command execution

### ISSUE THREAD

**Issue by mcandre** [hashicorp/packer#7192]
When debugging builds, it is really helpful to be able to slow down `boot_command` execution, in order to be able to spot where an error occurs. Maybe add an optional `boot_command_delay_sec`, that pauses an additional length of time between commands?

As a workaround, I am manually inserting lots of `<wait10>`s in my packer scripts.

**Comment by azr** [comment]
Hello @mcandre ! Thanks for opening this, could the [`boot_keygroup_interval`](https://www.packer.io/docs/builders/virtualbox-iso.html#boot-command) option be what you are looking for ?
You could augment the time between key pressed to slow down the boot command with it.

**Comment by azr** [comment]
Another option would be to allow the `-debug` option to pause after each sent command line in `boot_command`

**Comment by SwampDragons** [comment]
If azr's suggestion doesn't solve your issue please reopen :)
