### ISSUE TITLE
Enhancement: Option to reserve more host CPU cores when building a VM

### ISSUE THREAD

**Issue by mcandre** [hashicorp/packer#7193]
Unlike Vagrant provisioning, Packer builds are particularly sensitive to the host CPU speed, as critical `boot_command` steps like keyboard keys and `wait` timers, often fail if the host cannot dedicate enough processing power to the guest VM.

One fix for this would be to allow Packer configurations to specify a minimum amount of CPU core resources, similar to how Kubernetes works. A build for a low energy VM like DOS may only need 100 millicores (100m), whereas a beefier guest like Windows/NetBSD/Gentoo may want a full core (1) in order to have time to catch up with `boot_command`.

For cloud providers, this is less of an issue, as the cloud providers naturally manage resources better. So this is more of an issue for small teams using laptop and desktop providers.

I'm not sure that these providers support such an option. Maybe we could hack this by instructing the host OS run the provider processes at a higher priority?

**Comment by SwampDragons** [comment]
I think this is a nice idea but one that we're unlikely to prioritize work for internally.

**Comment by SwampDragons** [comment]
Given that we haven't gotten any more interest in this issue, I think I'm going to close it.
