### ISSUE TITLE
Could not get region error though region specified

### ISSUE THREAD

**Issue by gingercoder** [hashicorp/packer#7196]
Packer 1.3.3 Windows x64 platform
Windows 10 Pro 64-Bit

Running packer build causing the error message:
```
Build 'mypackerbuildid' errored: Could not get region, probably because it's not set or we're not running on AWS. RequestError: send request failed
caused by: Get http://169.254.169.254/latest/meta-data/placement/availability-zone: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

Rolling packer back to 1.2.4 and my problem goes away.

Regions were specified in the packer command and tested in packer json in case variables were not being passed correctly. Both ways failed.

The packer log shows that it was not the region that caused the exit from the packer command but a subsequent error message saying the machine is not readable:

`2019/01/14 15:50:54 machine readable: error-count []string{"1"}` 

Full output information at: 

[https://gist.github.com/gingercoder/e23603e6c46616b376f1cd1ab021bd36](https://gist.github.com/gingercoder/e23603e6c46616b376f1cd1ab021bd36)

**Comment by SwampDragons** [comment]
Hey, thanks for opening! Can you please share a simple .json template that reproduces this issue?

**Comment by gingercoder** [comment]
I'd have to uninstall/reinstall to test - but was throwing an error with just a very basic template generating a windows ami with two block devices running a configuration powershell in the provisioners section. 
I have multiple profiles set up in my aws configuration file, not sure if that is a linked cause, but that's the only "non standard" part of the setup.

**Comment by SwampDragons** [comment]
@azr, I think this may be caused by 16aa21dffe.  I can reproduce by removing region from my Packer config; even if it is set in the environment as AWS_REGION and in my ~/.aws config, Packer fails because of this

**Comment by SwampDragons** [comment]
(previously the code didn't raise an error when rawregion is an empty string, and would therefore let the AWS SDK find the region)

**Comment by bnm22** [comment]
I am using the latest packer docker image and ran into the same issue, even though, the region is set in the environment variable.
