### ISSUE TITLE
Option to build using a temporary AMI name rather than the final output name to avoid collisions

### ISSUE THREAD

**Issue by JoeyG1973** [hashicorp/packer#7199]
When "ami_regions" is present, AMIs should only be created in those listed in "ami_regions".  Region should only be used as the build location for the precursor ami to be copied.

**Comment by SwampDragons** [comment]
I think this falls under the warning in the [docs](https://www.packer.io/docs/builders/amazon-ebs.html): 

<The builder does not manage AMIs. Once it creates an AMI and stores it in your account, it is up to you to use, delete, etc. the AMI.

ami_regions copies amis to regions, but doesn't manage deleting the AMI in the build region. I'm not wild about the idea of forcing people to explicitly tell the builder to keep AMIs in the build region 

I think I would be open to adding a new option to delete the build region AMI, though.

**Comment by SwampDragons** [comment]
I understand your use case, but in a majority of circumstances, users build the AMI in a region they want to use it. Automatically deleting the AMI would mess up a lot of builds. 

Does your final build still fail if you use the https://www.packer.io/docs/builders/amazon-ebs.html#force_deregister option?

**Comment by SwampDragons** [comment]
Actually, reading a bit between the lines here, it sounds like your real problem is that you need to avoid name collisions. You want to keep foobar-release in us-east-1, then build another temporary ami in us-east-1 with a temporary name that doesn't collide and therefore doesn't force deletion of foobar-release in us-east-1, and then when moving the ami into us-east-2, rename the ami to foobar-release.

**Comment by SwampDragons** [comment]
Is there a reason why you don't use the AWS cli to copy Foobar-release to us-east-2 before running Packer in the us-east-2 region to build the us-east-2 version of Foobar-release?

**Comment by JoeyG1973** [comment]
> Actually, reading a bit between the lines here, it sounds like your real problem is that you need to avoid name collisions. You want to keep foobar-release in us-east-1, then build another temporary ami in us-east-1 with a temporary name that doesn't collide and therefore doesn't force deletion of foobar-release in us-east-1, and then when moving the ami into us-east-2, rename the ami to foobar-release.

You got it.


> Is there a reason why you don't use the AWS cli to copy Foobar-release to us-east-2 before running Packer in the us-east-2 region to build the us-east-2 version of Foobar-release?

We do this now, copy the base image from account A to all regions but it is a waste of money as aws charges for everything.

So this is from a large Corporation viewpoint.  The AMIs live in one "bakery" account unencrypted.  Per security, all AMIs in customer accounts(think hundreds across many regions) must be encrypted.  We use terraform to build out a temp vpc and subnet in the customer account and setup routes that allow the subnet to be routable from the subnet that the packer instance is running in.  We then use packer to customize the instance to the region and then allow the customer to interject their own customizations.  Then packer creates an encrypted AMI.  Given the way packer operates, we currently have to copy all the AMIs in the bakery account in all regions.

The bakery is a CI/CD that constantly builds the base AMIs using packer in us-east-1.  When an image is approved, we then need to copy that AMI to all the regions in AWS.  When you have 20+ AMIs this becomes hard to track(money) and uses snapshots(money) to store those images. 

It would be cheaper and easier to just have one AMI in one region.

Perhaps add an option to force the use of a temp image in the build region?

**Comment by SwampDragons** [comment]
Okay, I can see how having to do this by hand would make things very organizationally complex under your setup. I think it should be fine to add that option.

**Comment by SwampDragons** [comment]
I've edited the issue title to reflect the option we discussed.

**Comment by SwampDragons** [comment]
I've opened pr #7759 to implement this; you can find docs in that PR and binaries of the branch here: https://circleci.com/gh/hashicorp/packer/4925#artifacts/containers/0
