### ISSUE TITLE
Support for KVM

### ISSUE THREAD

**Issue by dominikschulz** [hashicorp/packer#72]
Please support KVM. It is native on recent linux distros and should be no more complex than supporting VirtualBox.

**Comment by vtolstov** [comment]
@qur 
i'm interensting on libvirt builder, do i have any patches to packer core (i'm using current git master) to get working libvirt builder from you repo?

**Comment by sciurus** [comment]
@vtolstov this [has been released](https://www.polibyte.com/blog/packer_supports_vagrant-libvirt).

**Comment by vtolstov** [comment]
@sciurus i'm interest of builder that connects to libvirt and create needed vm (for example remote libvirt server)

**Comment by qur** [comment]
I haven't touched the libvirt branch in ages, as my need for it went away.  I can probably uplift it to be based on current master this weekend if it would be useful.  However, I never got as far as trying to support remote libvirt.

**Comment by vtolstov** [comment]
As I see this is not needed, I'm cut you builder and move it to own repo,
after that I'm install and run it like other plugins.
06 февр. 2015 г. 1:21 пользователь "Julian Phillips" <
notifications@github.com> написал:
