### ISSUE TITLE
Unable to validate vmware when using a username with a domain

### ISSUE THREAD

**Issue by darac** [hashicorp/packer#7200]
- `packer version`: Packer v1.3.3
- Host platfom: Linux amd64, CentOS 7

In [driver_config.go:72](https://github.com/hashicorp/packer/blob/cf293c331051693022aa17af51b0fa85b296faca/builder/vmware/common/driver_config.go#L72), the username and password provided to vmware are passed through url.QueryEscape(), but then the output of that is passed to fmt.Sprintf(). fmt.Sprintf() expects the first argument to be a format string and subsequent arguments to be variables which are then formatted according to the format string. The problem is that url.QueryEscape() creates %-encoded string that look, to fmt.Sprintf() like format commands. As a result, it is impossible to use escaped characters (such as \ or @) in a username because they get converted to, say %40, sprintf sees that as a field-width and uses the first character of the username as the type specifier (e.g. "jones@somewhere.net" -> "jones%40somewhere.net" -> "jones" + "%40s" + "omewhere.net")

The fix is to use something like:
```go
	ovfToolArgs := []string{"--verifyOnly", fmt.Sprintf("vi://%s:%s@%s",
		url.QueryEscape(c.RemoteUser),
		url.QueryEscape(c.RemotePassword),
		c.RemoteHost)}
````

**Comment by SwampDragons** [comment]
Nice catch!

**Comment by SwampDragons** [comment]
Here's a linux build of the linked PR, which implements your suggested change. Would you mind testing the binary for me as a sanity check?

[packer.zip](https://github.com/hashicorp/packer/files/2788775/packer.zip)

**Comment by darac** [comment]
Yep, that works great for me. Thank you for the quick response 👍
