### ISSUE TITLE
Using Packer with Vault Secret Engine KV2

### ISSUE THREAD

**Issue by alexandernst** [hashicorp/packer#7204]
I'm trying to use packer with vault secret engine kv2, but so far I'm hitting an auth/permission error. I'm trying to read a secret from vault, as shown in the examples. In my test.json file I have a variables object, and inside I have an access_key and a secret_key keys. Each one of those contain {{ vault/secret/data/Foo/testaccess_key}}.

```
"variables": {
    "access_key": "{{ vault `/secret/data/Foo/test` `access_key`}}",
    "secret_key": "{{ vault `/secret/data/Foo/test` `secret_key`}}"
}
```

In vault, I created a token (which I use with packer), and the token has a policy such that:

```
path "secret/*" {
    capabilities = ["list"]
}
path "secret/data/Foo/test" {
    capabilities = ["read"]
}
```

According to docs, this should be enough for packer to be able to read the secret, but when I run packer I get

```
Error initializing core: error interpolating default value for 'access_key':
template: root:1:3: executing "root" at <vault `/secret/data/...>:
error calling vault: Error reading vault secret: Error making API request.
Permission denied.

URL: GET
https://vault.*******.com/v1/secret/data/Foo/test
Code: 403. Errors:

* 1 error occurred:
    * permission denied
```

If I understand correctly, the cause of the problem is the policy not granting enough permissions to packer in order to allow it to read my secret. Am I right? If "yes", how should I modify my policy?

Describe the problem and include the following information:

Packer version_v1.3.3
Host platform: Mac OS 10.14.2

**Comment by alexandernst** [comment]
Also, I must add that using packer with a root token (yes, I know, this is a terrible thing to do, I just wanted to discard bugs) works as expected. Which makes me wonder if I should be posting this issue here or in the vault github.

**Comment by SwampDragons** [comment]
If it works with the root token I'd test first to see if a very permissive other token works as well.  This sounds more like a permissions problem than a bug with the Packer implementation for sure, but it would be smart of us to document the minimum permissions needed for a given token to work.

**Comment by SwampDragons** [comment]
I'm closing because I think this is more of a Vault issue than a Packer one.

**Comment by ma-zhiyuan** [comment]
> I'm trying to use packer with vault secret engine kv2, but so far I'm hitting an auth/permission error. I'm trying to read a secret from vault, as shown in the examples. In my test.json file I have a variables object, and inside I have an access_key and a secret_key keys. Each one of those contain {{ vault/secret/data/Foo/testaccess_key}}.
> 
> ```
> "variables": {
>     "access_key": "{{ vault `/secret/data/Foo/test` `access_key`}}",
>     "secret_key": "{{ vault `/secret/data/Foo/test` `secret_key`}}"
> }
> ```
> 
> In vault, I created a token (which I use with packer), and the token has a policy such that:
> 
> ```
> path "secret/*" {
>     capabilities = ["list"]
> }
> path "secret/data/Foo/test" {
>     capabilities = ["read"]
> }
> ```
> 
> According to docs, this should be enough for packer to be able to read the secret, but when I run packer I get
> 
> ```
> Error initializing core: error interpolating default value for 'access_key':
> template: root:1:3: executing "root" at <vault `/secret/data/...>:
> error calling vault: Error reading vault secret: Error making API request.
> Permission denied.
> 
> URL: GET
> https://vault.*******.com/v1/secret/data/Foo/test
> Code: 403. Errors:
> 
> * 1 error occurred:
>     * permission denied
> ```
> 
> If I understand correctly, the cause of the problem is the policy not granting enough permissions to packer in order to allow it to read my secret. Am I right? If "yes", how should I modify my policy?
> 
> Describe the problem and include the following information:
> 
> Packer version_v1.3.3
> Host platform: Mac OS 10.14.2







Has this problem been solved?  I also encountered this problem. has any suggestions?

**Comment by alexandernst** [comment]
@ma-zhiyuan The correct policy is

```
path "secret/*" {
    capabilities = ["list"]
}

path "secret/metadata/*" {
    capabilities = ["list"]
}

path "secret/data/Foo/*" {
    capabilities = ["read", "list"]
}

path "secret/data/Foo/Dev/*" {
    capabilities = ["read", "list"]
}
```

**Comment by ma-zhiyuan** [comment]
@alexandernst  thanks, just use * for a broader match
