### ISSUE TITLE
Option to skip the image creation

### ISSUE THREAD

**Issue by bheiskell-datto** [hashicorp/packer#7209]
Hey folks,

I'm using packer with OpenStack to create base images from puppet manifests. An unexpected use case grew somewhat organically. We started using packer to build merge requests to verify the puppet manifests actually applied. This has worked really well for us. Unfortunately, it takes 4 minutes out of an 11 minute build to just save the image back to OpenStack. It doesn't look like there's an option to skip the creating image step. I took a look at the code base and it doesn't look too complicated to add this option. I don't mind doing this myself, but I first wanted to get some feedback on the issue.

First, since this isn't technically something that packer is designed to do, would you be receptive to adding an option to skipe the image save? Second, if so, should this be a global option, or one specifically for the openstack provider?

Thanks!
Ben

**Comment by bheiskell-datto** [comment]
After writing this up, I discovered !1740 which seems to be similar to what I'm trying to accomplish. I'm not trying to stir up an old argument, but it was closed because the value add wasn't clear. Hopefully this ticket makes the value add clear?

**Comment by rickard-von-essen** [comment]
Relates to #4681 and #4899

**Comment by TJM** [comment]
Maybe related to #2679 which looks merged?

**Comment by bheiskell-datto** [comment]
I'm not familiar with this code base, but is the image saving a post processor? This is where the save step seems to occur: https://github.com/hashicorp/packer/blob/c8fab8c7a37cb3f3d1dd1b758b9eddec50ae38ce/builder/openstack/builder.go#L142

**Comment by cbrit** [comment]
+1 to this. like @bheiskell-datto mentioned, it's already been discussed a few years ago, but it would be very helpful to apply CI to the packer template itself.

**Comment by SwampDragons** [comment]
I'm not wild about this because I thing being used as a CI provider is outside of Packer's scope. That said, I would merge a PR that added an option to skip saving the image. If someone wants to implement this, I won't stand in your way.

**Comment by lorengordon** [comment]
I'd be pretty excited if #4681 were reopened, or otherwise revived, and merged! 😃

**Comment by SwampDragons** [comment]
@lorengordon To restate why we didn't merge that one, and why I don't love this one -- this feature, no matter which builder we use it with, alters the builder artifact which breaks post-processor assumptions, which could break Packer builds.

But if people keep asking for it, then maybe it's worth figuring out how to safely break those assumptions. I'm not going to be rebasing or cleaning up #4681, but at this point, if someone else wants to then I'll revisit it.

**Comment by cbrit** [comment]
@SwampDragons what do you think of skipping post-processors if the -no-artifact (or whatever the flag is) is present?

**Comment by SwampDragons** [comment]
@cbrit That's one option. Making some kind of "null" artifact that gets produced in these cases may be a more flexible one.

**Comment by jquick** [comment]
Would love this option implemented!

**Comment by rasmus** [comment]
Any news on this issue?

**Comment by SwampDragons** [comment]
The maintainers are not planning to prioritize work on it, but PRs are welcome. I'll merge a new PR that implements this work.

**Comment by pussinboots** [comment]
Just an idea can it be implemented like it is in the googlecloud builder.

https://github.com/hashicorp/packer/blob/bee182e480a70bc5fc21779224b24838f77f4ad3/builder/googlecompute/step_create_image.go#L26

Define a skip image flag and then if this is present just skip the image creation. Looks not so difficult to be implemented.

**Comment by TJM** [comment]
I don't think this should be closed. I think @pussinboots was saying that this could be implemented similar to the one for googlecompute?

**Comment by azr** [comment]
Hello @TJM, this issue was closed when the PR fixing it was merged: https://github.com/hashicorp/packer/pull/10496, please tell us if that fix does not work for you 🙂 .

**Comment by TJM** [comment]
Disregard, sorry for the noise. This was not the issue I thought it was :(

**Comment by azr** [comment]
no worries !
