### ISSUE TITLE
Option to disable proxy for WinRM

### ISSUE THREAD

**Issue by ccoager** [hashicorp/packer#7224]
I've reviewed the other tickets similar to this issue but they don't address my issue.  Using the proxy with WinRM is causing random disconnects while running powershell commands.  I am required to use the proxy for AWS API or provisioning will timeout.  I cannot use "ssh_interface": "private_dns" as I am not using AWS DNS.  I cannot use no_proxy as I do not know the IP of the provisioned server.  

Can we add a "builders" option to disable the use of a proxy for WinRM?

**Comment by fenneh** [comment]
Running into a very similar situation but on Azure.

When building machines in Azure we need to set proxy settings (to be able to connect), the machines being built can't have a public IP so get an internally route-able IP which we don't know in advance. 

WinRM will then time out as it's trying to connect to said IP out via the proxy.

**Comment by r3dlin3** [comment]
This workaround does not seem to work anymore with version 1.5.x. I have tested 1.5.1 and 1.5.4.
I had to revert to 1.4.5 for it to work.

**Comment by MilanNXT** [comment]
Having same problem. Using packer in private setup in Azure. So I need environment variable  proxy so packer reach out to Azure API endpoints. But I need winrm to go directly through private channels. So there should be option to disable proxy for winrm.

**Comment by SwampDragons** [comment]
I've re-added the no_proxy code here: https://github.com/hashicorp/packer/pull/9267

binaries can be found here: https://circleci.com/gh/hashicorp/packer/53195#artifacts/containers/0

Can you all let me know if this solves the issue, or if you need me to do some further work?

**Comment by SwampDragons** [comment]
I've got this working and am about to merge the fix. It will be available in the 1.6.1 release, and if you just can't wait it'll be available in next week's nightly release, or you can download the patched binaries from our circle ci build here: https://circleci.com/gh/hashicorp/packer/60208#artifacts/containers/0
