### ISSUE TITLE
Feature request: Comma separated builder "name" list for defining multiple, similar builds.

### ISSUE THREAD

**Issue by curiositycasualty** [hashicorp/packer#7227]
This would be a feature whereby a single builder could define multiple, similar builds by housing a comma-separated list (or JSON array) of build names in that builder's `name` property:
```json
    {
      "name": "alpha-aws,beta-aws",
      "tags": {
        "A": "long",
        "list": "of",
        "tags": "that",
        "apply": "to",
        "multiple": "builds."
      },
      "type": "amazon-ebs"
    }
```

Or even:
`... "name": ["alpha-aws", "beta-aws"] ...`

Such that both of the two builds would share the `tags` property.

Customizing specifics of these builds could be accomplished through the user of the `override` property (assuming that functionality would be added for `builders`):
```json
    {
      "name": [
        "alpha-aws",
        "beta-aws"
      ],
      "tags": {
        "A": "long",
        "list": "of",
        "tags": "that",
        "apply": "to",
        "multiple": "builds."
      },
      "override": {
        "alpha-aws": {
          "tags": {
            "A": "different",
            "set": "of",
            "tags": "."
          }
        }
      },
      "type": "amazon-ebs"
    }
```

**Comment by SwampDragons** [comment]
This is a cool idea, and I think it actually falls in line with some of the thinking we've been doing around what Packer 2.0 will look like.  I think it's unlikely that we'll be getting to it any time in the next year though.

**Comment by azr** [comment]
Hello there ! With HCL2 it is now possible to have tags variable and reuse these tags in sources:

```hcl
variable "my_tags" {
  tags = {
   A = "bunch"
   Of = "tags
  }
}

source "amazon-ebs" "example" {
  # config
}

build {
  source "amazon-ebs.example" {
    name = "alpha-aws"
    tags   =  var.tags
  }
  source "amazon-ebs.example" {
    name = "beta-aws"
    tags   =  var.tags
  }

  # ...

}
```

Closing this issue as it should just work, cheers ! 🎉
