### ISSUE TITLE
Packer is stuck at "Preparing build: qemu" stage

### ISSUE THREAD

**Issue by Wenzel** [hashicorp/packer#7228]
- Packer version: `Packer v1.3.3`
- Host platform: `Fedora 29`
- [Debug log output, template, and var files](https://gist.github.com/Wenzel/50c0e853d900432d948a3221d34017ea)
- example to reproduce the bug; in the gist
  
Packer is stuck, and don't want to start downloading the file.

I tried with another template (var-file), `ubuntu-16.04.json`, and it works fine.
In fact i just copy pasted this var file, and replaced the urls to download `ubuntu-14.10`, so really weird.

I also checked that my QEMU or KVM installation was not buggy, my VMs are starting without any problems.

Can you help ?
Thanks !

**Comment by Wenzel** [comment]
Ok, i found the issue !

If you look closely, I inverted the `iso_url` and `iso_checksum_url` fields in the var-file :neutral_face: 

But it's weird that Packer doesn't show an error.
What do you guys think ?

**Comment by SwampDragons** [comment]
Weird! I'd definitely expect Packer to fail with an "invalid url" type error. We should definitely investigate this.

**Comment by rickard-von-essen** [comment]
Could you provide the values for the variables that you used?

**Comment by Wenzel** [comment]
It's in the gist, i added 3 files

**Comment by rickard-von-essen** [comment]
Speculating a bit, but I guess what happens is that Packer tries to download the ISO and put it in memory (on the heap) and that's why it looks stuck.

**Comment by SwampDragons** [comment]
The naive way to approach this would be to validate that the checksum file has a .txt extension.

**Comment by SwampDragons** [comment]
Or, since checksums can also have extensions like .sha1, maybe better to validate that it _doesn't_ have a .iso extension?
