### ISSUE TITLE
How to use default vpc and default subnet

### ISSUE THREAD

**Issue by suvrobkash** [hashicorp/packer#7229]
i am trying to use those parameters. 
```json
    "vpc_filter": {
      "filter": {
        "isDefault": "true"
      }
    },
    "subnet_filter": {
      "filter": {
        "cidr ": "/24"
      },
      "most_free": true,
      "random": false
    },
```

However, during validation i am having this issue
Template validation failed. Errors are shown below.

Errors validating build 'amazon-ebs'. 2 error(s) occurred:

* unknown configuration key: "subnet_filter.filter"
* unknown configuration key: "vpc_filter.filter"

Looking for assistance.

**Comment by rickard-von-essen** [comment]
It should be `filters`.

**Comment by adjogahm** [comment]
these 2 subnet_filter & vpc_filter are still not working.
I get this:
Errors validating build 'PACKER'. 2 error(s) occurred:

* unknown configuration key: "subnet_filter"
* unknown configuration key: "vpc_filter"

Using packer 1.2.3
