### ISSUE TITLE
Request: RMD160, Tiger checksum types

### ISSUE THREAD

**Issue by mcandre** [hashicorp/packer#7232]
Some installation media are packaged with atypical checksum algorithms, such as MirOS (AKA MirBSD), which provides RMD160 and Tiger checksums, but no SHA-... or MD-... checksums.

https://www.mirbsd.org/MirOS/v10/i386/

Fortunately, this is easy enough to workaround: Manually download installation media, perform a SHA-... or MD-... hash, and specify an `iso_checksum` key in the packer configuration. It's just slightly awkward to ignore the existing checksum URL's for this.

**Comment by azr** [comment]
Hey @mcandre, thanks for opening. After #6999 packer will use [hashicorp/go-getter](https://github.com/hashicorp/go-getter) to download files, the checksumming will also be handled by the go-getter. This issue/feature should be opened there !
I will close this issue for now and open one for you there : https://github.com/hashicorp/go-getter/issues/158
