### ISSUE TITLE
vmware - ovftool validation failed 

### ISSUE THREAD

**Issue by melck** [hashicorp/packer#7234]
I tried packer `1.3.3` and i have a error when ovftools are checked. There are a missing parameter `--noSSLVerify` ([here](https://github.com/hashicorp/packer/blob/508b6efb4ababd3efa3614033f9529a30970899d/builder/vmware/common/driver_config.go#L72)). 

Sorry for my short description but elsewhere `--noSSLVerify` parameter is handled by packer (cf vmware-iso docs).

**Comment by SwampDragons** [comment]
Good catch. I'm surprised that we have this hardcoded in the export args rather than tied to an "insecure" option like we do in the post-processor. Might be worth inspecting to see whether we should add such an option.

**Comment by marema31** [comment]
Just for your information, two years ago I encountered several time a problem with the post-processor that was not providing this option at that time. If the certificate was self-signed or generated by a company PKI, the post-processor was waiting forever at ovftool to finish with no logs. When I launched the same ovftool command line that packer, ovftool was asking for a confirmation. Once this confirmation was provided, the following run of packer was running smoothly.

**Comment by DenisBY** [comment]
Same issue with vmware-iso on 1.3.4. Packer fails with
```
$ packer build -var-file variables.json base-esxi.json
base-vm output will be in this color.

1 error(s) occurred:

* ovftool validation error: signal: killed; Accept SSL fingerprint (XX:XX:XX:...) for host 10.11.12.13 as source type.
Fingerprint will be added to the known host file
Write 'yes' or 'no'
```
even if I have in config:
```
    "ovftool_options": ["--allowExtraConfig", "--sourceSSLThumbprint=XX:XX:XX:..","--targetSSLThumbprint=XX:XX:XX:..","--noSSLVerify"],
```

**Comment by SwampDragons** [comment]
Here are some builds of Packer with the noSSLVerify flag added to this command -- try it out and lemme know if it solves the issue as expected.

windows:
[packer.zip](https://github.com/hashicorp/packer/files/2866639/packer.zip)


osx:
[packer.zip](https://github.com/hashicorp/packer/files/2866711/packer.zip)


linux: 
[packer.zip](https://github.com/hashicorp/packer/files/2866703/packer.zip)

**Comment by vfiftyfive** [comment]
It solves this issue indeed.
