### ISSUE TITLE
Error uploading VirtualBox version: Upload is not implemented when communicator = 'none'

### ISSUE THREAD

**Issue by mcandre** [hashicorp/packer#7246]
This should probably become a warning, rather than failing the build.

Also, would be nice to catch this at configuration load time, rather than at the end of a build.

**Comment by rickard-von-essen** [comment]
This should be caught at validation time.

**Comment by hazen-io** [comment]
Currently running into this issue as well. SSH isn't a workaround for my specific use-case. Are there other ways to work around this issue?
