### ISSUE TITLE
Feature: Verifying checksum of ISOFILE should be output at normal loglevel

### ISSUE THREAD

**Issue by TJM** [hashicorp/packer#7247]
I suggest that the `Verifying checksum of (ISOFILENAME)` output be "normal" level, similar to the `Using file in-place: file:///(ISOFILENAME)` When we have pre-downloaded images and a build sits on "Retrieving ISO" it makes us nervous. Once we turned  the log level up, we found that it was actually verifying the checksum, but it feels like that would be a fairly simple change, and for the better. Opinions?

**Comment by SwampDragons** [comment]
Seems like a great idea. :)
