### ISSUE TITLE
Bug (?): Problems copying VBoxVersion: "Permission Denied"

### ISSUE THREAD

**Issue by danowar2k** [hashicorp/packer#7255]
Version: Packer 1.3.3 (build.sh is the same in master branch, so bug is still present)
Host: Windows 7 64Bit, git Bash (git version 2.19.0.windows.1), mintty 2.9.0 (x86_64-pc-msys)
Hypervisor: VirtualBox 5.2.24
Guest VM: Solaris 11.4

I talked about this in other issues #5823, #3670, #4237 since I can't pinpoint the origin of the problem at hand.
I thought it was my SSH agent, but this happens even when I shut the agent down.
I thought Solaris started the SSH server before the vagrant user was present, but that seems also not to be the case.
I thought that recompiling Packer with added debug messages from the SSH library would help, but I either can't decipher them or they also don't tell me anything.
I added additional debug messages to the Packer code and found out that the error happens right here:

https://github.com/hashicorp/packer/blob/63a3bb0105addc6c29c951c8520b00c7905f3770/communicator/ssh/communicator.go#L653-L659

CopyN seems to work as my debug message after this line is printed. But then checkSCPStatus gets an error RC. I don't know the number yet, because `string(code)` doesn't seem to work. Yeah, I'm new to Go.

Log excerpts:
> 
> ```
> 2019/01/29 10:00:57 packer.exe: 2019/01/29 10:00:57 [INFO] Waiting 1s
> 2019/01/29 10:00:58 ui: ==> virtualbox-iso: Using ssh communicator to connect: 127.0.0.1
> 2019/01/29 10:00:58 packer.exe: 2019/01/29 10:00:58 [INFO] Waiting for SSH, up to timeout: 30m0s
> 2019/01/29 10:00:58 ui: ==> virtualbox-iso: Waiting for SSH to become available...
> ```
> Followed by lots of
> 
> ```
> 2019/01/29 10:00:58 packer.exe: 2019/01/29 10:00:58 [INFO] Attempting SSH connection...
> 2019/01/29 10:00:58 packer.exe: 2019/01/29 10:00:58 [DEBUG] reconnecting to TCP connection for SSH
> 2019/01/29 10:00:58 packer.exe: 2019/01/29 10:00:58 [DEBUG] handshaking with SSH
> 2019/01/29 10:00:58 packer.exe: 2019/01/29 10:00:58 [DEBUG] SSH handshake err: ssh: handshake failed: read tcp 127.0.0.1:56942->127.0.0.1:2849: wsarecv: Eine vorhandene Verbindung wurde vom Remotehost geschlossen.
> ```
> and a few of these
> 
> ```
> 2019/01/29 10:06:06 packer.exe: 2019/01/29 10:06:06 [INFO] Attempting SSH connection...
> 2019/01/29 10:06:06 packer.exe: 2019/01/29 10:06:06 [DEBUG] reconnecting to TCP connection for SSH
> 2019/01/29 10:06:06 packer.exe: 2019/01/29 10:06:06 [DEBUG] handshaking with SSH
> 2019/01/29 10:06:06 packer.exe: 2019/01/29 10:06:06 [DEBUG] SSH handshake err: ssh: handshake failed: read tcp 127.0.0.1:58199->127.0.0.1:2849: wsarecv: Eine bestehende Verbindung wurde softwaregesteuert
> 2019/01/29 10:06:06 packer.exe: durch den Hostcomputer abgebrochen.
> ```
> Finally,...
> 
> ```
> 2019/01/29 10:16:15 packer.exe: 2019/01/29 10:16:15 [INFO] Attempting SSH connection...
> 2019/01/29 10:16:15 packer.exe: 2019/01/29 10:16:15 [DEBUG] reconnecting to TCP connection for SSH
> 2019/01/29 10:16:15 packer.exe: 2019/01/29 10:16:15 [DEBUG] handshaking with SSH
> 2019/01/29 10:17:15 packer.exe: 2019/01/29 10:17:15 [DEBUG] SSH handshake err: Timeout during SSH handshake
> 2019/01/29 10:17:22 packer.exe: 2019/01/29 10:17:22 [INFO] Attempting SSH connection...
> 2019/01/29 10:17:22 packer.exe: 2019/01/29 10:17:22 [DEBUG] reconnecting to TCP connection for SSH
> 2019/01/29 10:17:22 packer.exe: 2019/01/29 10:17:22 [DEBUG] handshaking with SSH
> 2019/01/29 10:18:06 packer.exe: 2019/01/29 10:18:06 [DEBUG] handshake complete!
> 2019/01/29 10:18:06 packer.exe: 2019/01/29 10:18:06 [INFO] no local agent socket, will not connect agent
> 2019/01/29 10:18:06 ui: ==> virtualbox-iso: Connected to SSH!
> 2019/01/29 10:18:06 packer.exe: 2019/01/29 10:18:06 VBoxManage --version output: 5.2.24r128163
> 2019/01/29 10:18:06 packer.exe: 2019/01/29 10:18:06 VirtualBox version: 5.2.24
> 2019/01/29 10:18:06 ui: ==> virtualbox-iso: Uploading VirtualBox version info (5.2.24)
> 2019/01/29 10:18:06 packer.exe: 2019/01/29 10:18:06 [DEBUG] Opening new ssh session
> 2019/01/29 10:18:07 packer.exe: 2019/01/29 10:18:07 [DEBUG] Starting remote scp process:  scp -vt .
> 2019/01/29 10:18:07 packer.exe: 2019/01/29 10:18:07 [DEBUG] Started SCP session, beginning transfers...
> 2019/01/29 10:18:07 packer.exe: 2019/01/29 10:18:07 [DEBUG] Copying input data into temporary file so we can read the length
> 2019/01/29 10:18:07 packer.exe: 2019/01/29 10:18:07 [DEBUG] scp: Uploading .vbox_version: perms=C0644 size=6
> 2019/01/29 10:18:08 ui error: ==> virtualbox-iso: Error uploading VirtualBox version: scp: ./.vbox_version: Permission denied
> 2019/01/29 10:18:08 ui: ==> virtualbox-iso: Step "StepUploadVersion" failed
> 2019/01/29 10:18:08 ui: ask: ==> virtualbox-iso: [c] Clean up and exit, [a] abort without cleanup, or [r] retry step (build may fail even if retry succeeds)?
> ```

**Comment by danowar2k** [comment]
So, I can provide you with files or a repo containing the Packer template and more. I can try to cut it down, but the problem seems to happen after the boot command and the first reboot. That is bad in itself because everytime the problem happens I have to rebuild the VM again, which takes ca. 20 minutes. If only there were a way to take a snapshot or something of the Packer state.

**Comment by danowar2k** [comment]
Additional log output with SSH library debug enabled:

```
2019/01/31 18:52:17 ui: ==> virtualbox-iso: Connected to SSH!
2019/01/31 18:52:17 packer.exe: 2019/01/31 18:52:17 VBoxManage --version output: 5.2.24r128163
2019/01/31 18:52:17 packer.exe: 2019/01/31 18:52:17 VirtualBox version: 5.2.24
2019/01/31 18:52:17 ui: ==> virtualbox-iso: Uploading VirtualBox version info (5.2.24)
2019/01/31 18:52:17 packer.exe: 2019/01/31 18:52:17 [DEBUG] Opening new ssh session
2019/01/31 18:52:17 packer.exe: 2019/01/31 18:52:17 send global(1): ssh.channelOpenMsg{ChanType:"session", PeersId:0x1, PeersWindow:0x200000, MaxPacketSize:0x8000, TypeSpecificData:[]uint8(nil)}
2019/01/31 18:52:17 packer.exe: 2019/01/31 18:52:17 decoding(1): 80 &ssh.globalRequestMsg{Type:"hostkeys-00@openssh.com", WantReply:false, Data:[]uint8{0x0, 0x0, 0x1, 0x17, 0x0, 0x0, 0x0, 0x7, 0x73, 0x73, 0x68, 0x2d, 0x72, 0x73, 0x61, 0x0, 0x0, 0x0, 0x3, 0x1, 0x0, 0x1, 0x0, 0x0, 0x1, 0x1, 0x0, 0xc1, 0xaf, 0xa4, 0x84, 0x4a, 0x93, 0x59, 0x37, 0xf6, 0x5b, 0x87, 0x7a, 0xaf, 0x9a, 0xe3, 0x9e, 0xd0, 0xe5, 0x41, 0x1c, 0xcf, 0xb5, 0xf5, 0xbf, 0x9, 0x90, 0xf0, 0x7a, 0x59, 0x64, 0xd6, 0x6a, 0xcb, 0x1e, 0x31, 0xbe, 0x49, 0x9d, 0x5c, 0xa6, 0x24, 0x67, 0xa6, 0x6, 0xdc, 0x6e, 0xf9, 0xaf, 0x20, 0x80, 0x7a, 0xec, 0x6c, 0xae, 0x76, 0x8e, 0x1e, 0x50, 0xca, 0x33, 0x44, 0x73, 0x8f, 0xb, 0x43, 0xd7, 0x48, 0x4b, 0xd1, 0x34, 0x63, 0x74, 0x5f, 0xee, 0x3a, 0x33, 0x20, 0x51, 0x96, 0x25, 0x5, 0x97, 0x76, 0x76, 0x2d, 0x11, 0x4d, 0xaf, 0x2e, 0xc3, 0xb, 0x42, 0xed, 0xd3, 0x97, 0xe8, 0xa5, 0x3, 0x5a, 0xf9, 0x92, 0x16, 0xd1, 0x1e, 0x83, 0xef, 0x7, 0xa0, 0x24, 0xe6, 0x9a, 0xb9, 0xe5, 0x20, 0x1a, 0x3e, 0xdc, 0xf1, 0x16, 0xe7, 0xbb, 0x3e, 0xa4, 0x52, 0x54, 0x5, 0x1f, 0x35, 0x1e, 0x9d, 0xf3, 0x65, 0x81, 0xcf, 0x46, 0xeb, 0xdf, 0x9f, 0xad, 0xe8, 0x13, 0x7f, 0x9a, 0x79, 0x0, 0x22, 0xee, 0xd1, 0xaf, 0x27, 0x84, 0x6, 0x33, 0x50, 0x7a, 0x6e, 0x2c, 0xac, 0x9c, 0xf9, 0x66, 0x7d, 0x3b, 0xac, 0x7e, 0xc7, 0x66, 0x97, 0xd7, 0xfd, 0xa2, 0x80, 0xc1, 0x46, 0xb0, 0xb9, 0xd7, 0x9c, 0xe5, 0xd, 0xd3, 0x47, 0x41, 0x9b, 0x41, 0xb6, 0xa8, 0xc0, 0x22, 0x53, 0xfa, 0xf1, 0x74, 0xb5, 0x2d, 0xba, 0xb6, 0x2d, 0xc4, 0x71, 0x1a, 0x97, 0x64, 0x9a, 0xab, 0xb1, 0xfc, 0x49, 0x64, 0x5c, 0xd4, 0x71, 0xbd, 0xe1, 0x59, 0x80, 0x8c, 0xb7, 0x5b, 0x3f, 0xcd, 0x2f, 0x51, 0x35, 0xaa, 0x86, 0x80, 0x82, 0xe, 0xdc, 0xb6, 0x7c, 0x65, 0x12, 0xae, 0xa9, 0x1d, 0x77, 0xff, 0xb0, 0x19, 0xc5, 0xb0, 0x92, 0x1c, 0xf3, 0xb7, 0xa9, 0xe4, 0xf5, 0x69, 0xe8, 0x83, 0x93, 0x10, 0xc7, 0x0, 0x0, 0x0, 0x33, 0x0, 0x0, 0x0, 0xb, 0x73, 0x73, 0x68, 0x2d, 0x65, 0x64, 0x32, 0x35, 0x35, 0x31, 0x39, 0x0, 0x0, 0x0, 0x20, 0x7a, 0xe4, 0x4e, 0xa0, 0xcc, 0xbf, 0x44, 0x8e, 0xef, 0xf4, 0x8c, 0x48, 0xea, 0x5a, 0xa2, 0x4a, 0xb7, 0x27, 0x36, 0x53, 0xe6, 0xc8, 0x16, 0xd7, 0xa7, 0x9b, 0xfd, 0x51, 0xca, 0x6c, 0x1a, 0x78}} - 367 bytes
2019/01/31 18:52:17 packer.exe: 2019/01/31 18:52:17 decoding(1): 91 &ssh.channelOpenConfirmMsg{PeersId:0x1, MyId:0x0, MyWindow:0x0, MaxPacketSize:0x8000, TypeSpecificData:[]uint8{}} - 17 bytes
2019/01/31 18:52:17 packer.exe: 2019/01/31 18:52:17 [DEBUG] Starting remote scp process:  scp -vt .
2019/01/31 18:52:17 packer.exe: 2019/01/31 18:52:17 send(1): ssh.channelRequestMsg{PeersId:0x0, Request:"exec", WantReply:true, RequestSpecificData:[]uint8{0x0, 0x0, 0x0, 0x9, 0x73, 0x63, 0x70, 0x20, 0x2d, 0x76, 0x74, 0x20, 0x2e}}
2019/01/31 18:52:17 packer.exe: 2019/01/31 18:52:17 decoding(1): 93 &ssh.windowAdjustMsg{PeersId:0x1, AdditionalBytes:0x200000} - 9 bytes
2019/01/31 18:52:17 packer.exe: 2019/01/31 18:52:17 decoding(1): 99 &ssh.channelRequestSuccessMsg{PeersId:0x1} - 5 bytes
2019/01/31 18:52:17 packer.exe: 2019/01/31 18:52:17 decoding(1): data packet - 95 bytes
2019/01/31 18:52:17 packer.exe: 2019/01/31 18:52:17 [DEBUG] Started SCP session, beginning transfers...
2019/01/31 18:52:17 packer.exe: 2019/01/31 18:52:17 send(1): ssh.windowAdjustMsg{PeersId:0x0, AdditionalBytes:0x52}
2019/01/31 18:52:17 packer.exe: 2019/01/31 18:52:17 [DEBUG] Copying input data into temporary file so we can read the length
2019/01/31 18:52:17 packer.exe: 2019/01/31 18:52:17 [DEBUG] scp: Uploading .vbox_version: perms=C0644 size=6
2019/01/31 18:52:18 packer.exe: 2019/01/31 18:52:18 decoding(1): data packet - 51 bytes
2019/01/31 18:52:18 packer.exe: 2019/01/31 18:52:18 decoding(1): data packet - 41 bytes
2019/01/31 18:52:18 packer.exe: 2019/01/31 18:52:18 send(1): ssh.windowAdjustMsg{PeersId:0x0, AdditionalBytes:0x1c}
2019/01/31 18:52:18 packer.exe: 2019/01/31 18:52:18 send(1): ssh.windowAdjustMsg{PeersId:0x0, AdditionalBytes:0x2a}
2019/01/31 18:52:18 packer.exe: 2019/01/31 18:52:18 [DEBUG-DP] checkSCPStatus: Code= 
2019/01/31 18:52:18 packer.exe: 2019/01/31 18:52:18 [DEBUG-DP] checkSCPStatus: No error reading code, continuing...
2019/01/31 18:52:18 packer.exe: 2019/01/31 18:52:18 [DEBUG-DP] checkSCPStatus: No bad status...
2019/01/31 18:52:18 packer.exe: 2019/01/31 18:52:18 [DEBUG-DP] scpUploadFile: after Fprintln...
2019/01/31 18:52:18 packer.exe: 2019/01/31 18:52:18 [DEBUG-DP] scpUploadFile: after CopyN...
2019/01/31 18:52:18 packer.exe: 2019/01/31 18:52:18 [DEBUG-DP] checkSCPStatus: Code=
2019/01/31 18:52:18 packer.exe: 2019/01/31 18:52:18 [DEBUG-DP] checkSCPStatus: No error reading code, continuing...
2019/01/31 18:52:18 packer.exe: 2019/01/31 18:52:18 [DEBUG-DP] checkSCPStatus: Non-zero return code...
2019/01/31 18:52:18 packer.exe: 2019/01/31 18:52:18 [DEBUG-DP] checkSCPStatus: Error message read: scp: ./.vbox_version: Permission denied
2019/01/31 18:52:18 packer.exe: 2019/01/31 18:52:18 send(1): ssh.channelEOFMsg{PeersId:0x0}
2019/01/31 18:52:18 packer.exe: 2019/01/31 18:52:18 send(1): ssh.channelCloseMsg{PeersId:0x0}
2019/01/31 18:52:18 ui error: ==> virtualbox-iso: Error uploading VirtualBox version: scp: ./.vbox_version: Permission denied
2019/01/31 18:52:18 ui: ==> virtualbox-iso: Step "StepUploadVersion" failed
2019/01/31 18:52:18 ui: ask: ==> virtualbox-iso: [c] Clean up and exit, [a] abort without cleanup, or [r] retry step (build may fail even if retry succeeds)?
2019/01/31 18:52:18 packer.exe: 2019/01/31 18:52:18 decoding(1): 98 &ssh.channelRequestMsg{PeersId:0x1, Request:"exit-signal", WantReply:false, RequestSpecificData:[]uint8{0x0, 0x0, 0x0, 0x4, 0x50, 0x49, 0x50, 0x45, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}} - 38 bytes
2019/01/31 18:52:18 packer.exe: 2019/01/31 18:52:18 decoding(1): 97 &ssh.channelCloseMsg{PeersId:0x1} - 5 bytes
2019/01/31 18:52:18 packer.exe: 2019/01/31 18:52:18 send(1): ssh.channelCloseMsg{PeersId:0x0}
```

**Comment by danowar2k** [comment]
So, I can send you everything except the Solaris ISO.
This you can find at: http://download.oracle.com/otn/solaris/11_4/sol-11_4-ai-x86.iso

But you have to register an Oracle account for this.

Is there somewhere I should upload my files? Or should I paste them somewhere (which would be harder)

**Comment by SwampDragons** [comment]
Okay, so: the ssh session appears to be properly connecting: `2019/01/29 10:18:06 ui: ==> virtualbox-iso: Connected to SSH!` is your important logline there.

I wonder if your problem is either 

a) The user calling Packer doesn't have permissions to access the /.vbox_version file on the host system, or 

b) The ssh user does not have permission to write to the directory it's trying to upload .vbox_verson to.

**Comment by danowar2k** [comment]
on a)
I run the packer script as my local LADP authenticated Windows user. This user should have local admin rights. If the temporary file .vbox_version is generated in /tmp, I have rights to write to that directory.

on b)
I connect as user vagrant. If the file .vbox_version is uploaded to ~/.vbox_version, then that user has rights to write into that directory.

New thoughts: In Solaris 11.3 the DHCP agent was always running. In Solaris 11.4 the DHCP agent is now a SMF service and disabled per default, but starts for a bit after system boot, after which it is disabled. Which explains some race conditions where sometimes the VM succeeded in creating the IP address of the NAT and sometimes didn't. That lead to things like "I can't find that github.com server you're looking for. I'm gonna quit now"

I'll see if initially enabling DHCP will lead to better results...

**Comment by danowar2k** [comment]
Initially enabling DHCP at least seems to remove another error where the VM couldn't add the IP interface sometimes. The problem "Permission denied" still persists. I'm currently using the established SSH session to execute some commands on the VM to see who I am, where I am and if I can do stuff like creating files.

If this works as expected, I'll try to SCP my own file to the machine, maybe with more debug...

**Comment by danowar2k** [comment]
Okay, I think (!) I found the culprit....The probable cause is...*drumroll*... Solaris. Who would have thought?

What I think at the moment and have to confirm is:
* At point A Solaris reboots after the install process
* At point B the SSH server is started
* At point C the user vagrant is created
* At point D the home directory for the user vagrant /export/home/vagrant is created and mounted

In the timeline (A -> B -> C -> D), packer sees the open SSH server at point B, and tries to connect to the SSH server after point C but before point D.
So the home directory isn't present yet, the login directory for the user without the home directory is maybe.... / ... and there the vagrant user gets "Permission denied" when trying to scp the file.

*sigh* Now to confirm my theory.

**Comment by danowar2k** [comment]
First confirmation: When the home directory is unmounted and moved, the logged in user lands in "/".

**Comment by danowar2k** [comment]
> b) The ssh user does not have permission to write to the directory it's trying to upload .vbox_verson to.

Yeah, basically it was that, wasn't it?

**Comment by danowar2k** [comment]
While my Packer VM builds, I'll try to be constructive about this:

What could be done to prevent this for other people? ...
* More/better  stderr output for this (however that would work); tell in which directory one doesn't have permissions
* Store the errors/warnings when logging in via SSH somewhere accessible (when I log in without having a working home dir, I get a warning that the home directory cannot be accessed)

**Comment by danowar2k** [comment]
* Do not scp the file to "." (because it's relative and we don't know where it will land), but to /tmp/absolute_path or something like that
* Only really start connecting via SSH once there are no erorrs/warnings when connecting

**Comment by rickard-von-essen** [comment]
> Do not scp the file to "." (because it's relative and we don't know where it will land), but to /tmp/absolute_path or something like that

This is controlled by [virtualbox_version_file](https://packer.io/docs/builders/virtualbox-iso.html#virtualbox_version_file) and documented there. It's also the most reasonable default since that is the most likely place the user has write permissions.

**Comment by danowar2k** [comment]
Yeah, I see, you're right. The next would be to change the Guest Additions path, because that is the next thing that is uploaded, and that could also be "too early"...So that idea is not really worth anything.

**Comment by danowar2k** [comment]
> > Do not scp the file to "." (because it's relative and we don't know where it will land), but to /tmp/absolute_path or something like that
> 
> This is controlled by [virtualbox_version_file](https://packer.io/docs/builders/virtualbox-iso.html#virtualbox_version_file) and documented there. It's also the most reasonable default since that is the most likely place the user has write permissions.

An idea: wouldn't a better default be ~/ ? This way you could at least ensure a better error message (I think).

**Comment by SwampDragons** [comment]
I'm not familiar with Solaris kickstart behavior, but are you able to change the order in your kickstart script so that it goes ACDB instead of ABCD?

**Comment by SwampDragons** [comment]
I'd suggest checking out the solaris packer template over at https://github.com/chef/bento/tree/master/solaris.  It may be overkill for you but if you check out their https://github.com/chef/bento/blob/master/solaris/floppy/S99startup.sh script, then you'll see that their first move is to disable SSH to prevent Packer from connecting too early. Doing this, then reenabling SSH after you've created your user and homedir, is probably the best way to go. 

Unfortunately, Packer is (by design) ignorant about guest OS, so unix-isms like "~/" are generally a bad idea.

**Comment by danowar2k** [comment]
I always forget that VMs can be something other than a Linux OS. Yes, of course, ~/ doesn't work with Windows guests. "." is universal, it seems.

I don't know if I can influence service start behaviour by editing my configuration profile, but I'll try.

At the moment I fix my problem by editing the script that starts the SSH service. I let the script wait until the user home directory is created and mounted, then the SSH server can start.

At the end I change the line back. That works, at least. Although I would rather have services unedited and orchestrate their startup order...

**Comment by SwampDragons** [comment]
Sounds like you've gotten this figured out; I'm going to close because there isn't really a solution that'll work universally for all guest operating systems. One of these days I need to write a more comprehensive walkthrough with a list of FAQs and "gotchas" so that people can find them -- the SSH daemon launching too soon is probably not an uncommon sticking point.
