### ISSUE TITLE
virtualbox-iso guest_additions_mode attach should use iso_interface too

### ISSUE THREAD

**Issue by rgl** [hashicorp/packer#7256]
When setting `guest_additions_mode` to `attach` the iso should be attached to the same interface as defined by `iso_interface` or we should have a dedicated `guest_additions_interface` option.

This is needed because the virtualbox EFI firmware only supports sata attached devices.

**Comment by rgl** [comment]
FYI, there's an workaround at https://github.com/rgl/windows-2016-vagrant/commit/4f144312be8781a7bd4bc2f08ffba16dc4745d0b

**Comment by SwampDragons** [comment]
This should be fixed by #7298 and there are some binaries available on that PR -- can you test it out and lmk if it works for you?

**Comment by rgl** [comment]
@SwampDragons it works for me! thanks :-)
