### ISSUE TITLE
--only skips post processors despite docs saying otherwise

### ISSUE THREAD

**Issue by anish** [hashicorp/packer#7257]
From the docs : 
```
-only=foo,bar,baz - Only run the builds with the given comma-separated names. Build names by default are their type, unless a specific name attribute is specified within the configuration. -only does not apply to post-processors
```
packer 1.3.4
amd64
- Example to reproduce,output included https://gist.github.com/anish/fa5681bd89e99652f217b9f7fbc92483

- Compare to when I name the post-processor the same as the builder https://gist.github.com/anish/068a88004d5d6890eac8fa5b5e6ef9d5#file-gistfile1-txt-L52

  
Test via
` PACKER_LOG=1 packer build --var-file=foo.json --only=gcp packer-test.json`

**Comment by SwampDragons** [comment]
Thanks for opening! We'll get on this ASAP.

**Comment by anish** [comment]
looks like a regression from https://github.com/hashicorp/packer/pull/7183/files
from a quick glance, it looked like `func (o *OnlyExcept) Skip` is probably not the right function to call, since it filters on `only`, which is not supposed to be applicable to post-processors

**Comment by azr** [comment]
Ah, from #7183, I first made `-only` post-processor aware, then undid it. Forgot to update the docs. I think I will at least update the packer docs so that it is not reflected there.

**Comment by lorengordon** [comment]
I feel like we're impacted by this also. We're seeing that post-processors no longer execute if `only` is specified and matches the builder name, when using `-only` on the cli.

From the issue report, it _appears_ there is a new `name` key for post-processors, and if we set that to match the builder name, then it will work as expected? How do we make it work if there are multiple builders that should match a single post-processor?

Also, this `name` key is not mentioned in the docs: https://www.packer.io/docs/templates/post-processors.html

(Sidenote: Any idea why this new feature went into a bug release?)

**Comment by azr** [comment]
That one is on me, too new to packer, I tested with the `-only` option, but was not aware of the `only` option inside the schema of a post-processor. I'll fix this ass soon as possible.

**Comment by azr** [comment]
So from #7262, that also fixes our tests, here are a set of binaries.
[packer_windows_amd64.zip](https://github.com/hashicorp/packer/files/2821979/packer_windows_amd64.zip)
[packer_darwin_amd64.zip](https://github.com/hashicorp/packer/files/2821965/packer_darwin_amd64.zip)
[packer_linux_amd64.zip](https://github.com/hashicorp/packer/files/2821966/packer_linux_amd64.zip)

I wanted to reuse functions, but shouldn't have !
