### ISSUE TITLE
Build 'amazon-ebs' errored: error validating regions: creating custom Windows AMI on AWS

### ISSUE THREAD

**Issue by Bluesawyer** [hashicorp/packer#7258]
[INFO] Packer version: 1.3.4
Creating Windows custom AMI on AWS
PS C:\Users\sadmmcgeoa> packer build -var '$ENV:http_proxy = http://ep-webproxy-xxxxxxxxxx/proxy.pac' -var '$ENV:h
ttps_proxy = http://ep-webproxy-xxxxxxx/proxy.pac' -var '$env:PACKER_LOG = 1' -var '$env:CHECKPOINT_DISABLE = 1
' -debug E:\AWSAMI-Scripts\template\Example_Windows2016.json
Debug mode enabled. Builds will not be parallelized.
amazon-ebs output will be in this color.
[Windows2016Packer.log](https://github.com/hashicorp/packer/files/2818930/Windows2016Packer.log)
[Example_Windows2016.txt](https://github.com/hashicorp/packer/files/2819298/Example_Windows2016.txt)

**Comment by Bluesawyer** [comment]
The proxies are set as environment variables.

**Comment by SwampDragons** [comment]
so do you set the environment vars independently of this -var flag?  Because I think the way Packer would interpret the command you shared is to actually create a variable whose name was "$env:PACKER_LOG" rather than setting the PACKER_LOG environment var.

**Comment by Bluesawyer** [comment]
I set all the environment variables separately before I run the packer build command.
My build used to work, but then suddenly stopped. It looked like version 1.3.4 might be the resolution (7226), but no luck.
Usually I run this automatically every month, using a powershell script that sets all the variables and then runs "packer build" with no -var options.

**Comment by SwampDragons** [comment]
When did it suddenly stop? What version of Packer?

**Comment by SwampDragons** [comment]
And can you share the powershell script you use to run this?

**Comment by Bluesawyer** [comment]
The 1st December run failed with version 1.0.4
The first thing I did was check that my access keys were still valid.
Then I upgraded to 1.3.3, but the error remained.
[example_Windows.txt](https://github.com/hashicorp/packer/files/2819402/example_Windows.txt)
[AWSAMIFunctions.txt](https://github.com/hashicorp/packer/files/2819405/AWSAMIFunctions.txt)

**Comment by SwampDragons** [comment]
So to be clear did it fail at the same time as you upgraded Packer? Or did it fail suddenly even though you hadn't upgraded in some time?

**Comment by SwampDragons** [comment]
That's very odd.  The fact that it started failing while you were still on a version of Packer you'd been using for some time makes me wonder if something changed on your end -- the name of the proxy, for example, or some kind of firewall property.

**Comment by Bluesawyer** [comment]
It could be, but I am still able to use AWS PowerShell module commands during the same session that the packer build fails on. It has to go through the proxy too.

**Comment by SwampDragons** [comment]
I can leave this open for a while to see if others have any thoughts, but I have no idea where to start debugging this from the Packer side of things.

**Comment by Bluesawyer** [comment]
Thanks

**Comment by Bluesawyer** [comment]
I'm going to close this. I have discovered the problem.
We put in a new proxy. It is behind a VIP, the same VIP that fronted the old proxy, so no change to any scripts. Unfortunately Packer didn't like the something about the combination of the VIP and the new proxy. If I specify the proxy directly, packer has no problem.

Thanks for your help.
