### ISSUE TITLE
cloudstack: template_os with name instead of UUID fails

### ISSUE THREAD

**Issue by rhtyd** [hashicorp/packer#7263]
When a ostype name instead of UUID is used in `template_os` in packer build/json file, packer build fails with `Error retrieving UUID of OS type CentOS 7.2: json: cannot unmarshal bool into Go struct field OsType.isuserdefined of type string`.

I've traced the issue to:
https://github.com/xanzy/go-cloudstack/pull/109

... and found the main issue to be `Isuserdefined` set to `string` than `bool`. The field type is fixed in latest go-cloudstack dependency v2.4.1 however packer uses 2yr old dependency that needs updating. I'll try to send a PR, otherwise, I've requested its maintainer @svanharmelen to update the vendorized dependency.
/cc @andrijapanicsb @PaulAngus @DagSonsteboSB

**Comment by rhtyd** [comment]
@svanharmelen we needed an internal `packer` build soon so I had to fix this. I've sent the PR for review now: https://github.com/hashicorp/packer/pull/7264

**Comment by svanharmelen** [comment]
I'll have a look coming week, thanks! 👍
