### ISSUE TITLE
 Interactive user authentication not working in Azure Arm builder

### ISSUE THREAD

**Issue by adamday2** [hashicorp/packer#7267]
**Summary:**
Using Azure-ARM, when specifying only the `subscription_id`, the expected behavior based on the [documentation](https://www.packer.io/docs/builders/azure.html) is that specifying only the `subscription_id` would result in an interactive user authentication. 

When specifying only the `subscription_id`, instead of the expected output, the following error occurs:
```
==> azure-arm: Getting tokens using client bearer JWT
Build 'azure-arm' errored: parameter 'id' cannot be empty

==> Some builds didn't complete successfully and had errors:
--> azure-arm: parameter 'id' cannot be empty
```

**Environment and Debug:**
- Packer version: 1.3.4 - brew installed
- Host platform: OSX High Sierra
- Debug log output:
https://gist.github.com/adamday2/daf7927d6c16a04892956d250a12db4c
- Example:
https://gist.github.com/adamday2/1df5ef14a257cdafb5fb95ddfac185be

I'm a bit confused as to how its getting to the JWT as following the flow of logic, it should be hitting the device login:
https://github.com/hashicorp/packer/blob/v1.3.4/builder/azure/arm/clientconfig.go
@paulmey

**Comment by paulmey** [comment]
I'm checking this out...

**Comment by paulmey** [comment]
Dropped a build with the fix [here](https://github.com/paulmey/packer/releases/tag/v1.3.5-azure%252Bpaulmey).

**Comment by adamday2** [comment]
Forgot to reply to this earlier, but thank you @paulmey for the timely fix on this. Much appreciated!
