### ISSUE TITLE
ssh handshake failed on using id_rsa in virtualbox 

### ISSUE THREAD

**Issue by becash143** [hashicorp/packer#7284]
I am unable to create an OVA using packer in virtualbox with id_rsa. I am able to connect from the host machine  to the vbox  host using same private key. The error is as given 
"Error waiting for SSH: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain". 
Using "ssh_password" the OVA is created successfully. But my objective is to create an OVA using private key. 

{  
"builders": [{
    "type": "virtualbox-ovf",
    "source_path": "/root/Documents/OVA_idrsa.ova",
    "ssh_username": "support",
    "ssh_private_key_file": "id_rsa",
    "ssh_pty": "true",
    "ssh_port": 22,
    "vrdp_bind_address": "0.0.0.0",
    "guest_additions_mode": "disable",
    "virtualbox_version_file": "",
    "headless": true,
    "ssh_skip_nat_mapping": "true",
    "boot_wait": "120s",
    "ssh_wait_timeout": "1000s",
    "shutdown_command": ""

  }]

  
}
<img width="1156" alt="screen shot 2019-02-06 at 16 30 27" src="https://user-images.githubusercontent.com/30592324/52336580-5df8eb80-2a2d-11e9-9938-caa94a470f99.png">

**Comment by SwampDragons** [comment]
Hey there, issues connecting via SSH/WinRM are generally not bugs within packer and are better addressed by the [mailing list](https://groups.google.com/forum/#!forum/packer-tool).  Try asking there first, especially if you're trying to get Packer working for the first time.

To get you started though, I'd suggest that you try using the absolute path to the ssh key for "ssh_private_key_file", and maybe also check permissions on the key to make sure that the user running the Packer build has permission to access it.

**Comment by becash143** [comment]
> Hey there, issues connecting via SSH/WinRM are generally not bugs within packer and are better addressed by the [mailing list](https://groups.google.com/forum/#!forum/packer-tool). Try asking there first, especially if you're trying to get Packer working for the first time.
> 
> To get you started though, I'd suggest that you try using the absolute path to the ssh key for "ssh_private_key_file", and maybe also check permissions on the key to make sure that the user running the Packer build has permission to access it.

checked with the absolute path and the permissions is also 600. Still the issue is same. I have addressed this in mailing list. 
Thank  you for your support!
