### ISSUE TITLE
vmware-vmx Remote Clone Fails

### ISSUE THREAD

**Issue by JohnnyBopper** [hashicorp/packer#7286]
This is the first time trying to use the vmware-vmx on a remote ESXI host so forgive me if you find that I'm just doing this incorrectly but this feels like it is a bug in the clone process.

My source and destination looks correct but I receive the following error.

Stderr: DiskLib_Check() failed for source disk The system cannot find the file specified (25).

- Packer version: 1.3.4
- Host platform: ESXI
- Log output and config: https://gist.github.com/JohnTheDon01/4ee04312cc228127fa278d0f37423dce

Thanks!

**Comment by rickard-von-essen** [comment]
For some reason you seem to have a trailing \r somewhere. Try to locate it and remove it.

**Comment by SwampDragons** [comment]
Our tooling looks for and strips \n from the names; maybe we should make it also strip the \r?

https://github.com/hashicorp/packer/blob/9787e787d42f4ee81b5cd16c1e5585584a8ed45b/builder/vmware/common/driver_esx5.go#L50

**Comment by JohnTheDon01** [comment]
@SwampDragons I agree that the \r needs to be stripped out. Is this something that can make it into the next release?

**Comment by SwampDragons** [comment]
If I have time; meanwhile, removing the \r\n line ending from your filename will allow you to clone properly.

**Comment by JohnnyBopper** [comment]
The file is in my datastore and I'm not passing in a carriage return as part of my source_path.

**Comment by SwampDragons** [comment]
I think the file in your datastore has hidden whitespace at the end of its name. You'd need to rename the file.

**Comment by SwampDragons** [comment]
Here are some packer builds with the \r also getting stripped. Care to test it out?

windows:
[packer.zip](https://github.com/hashicorp/packer/files/2862597/packer.zip)

linux:
[packer.zip](https://github.com/hashicorp/packer/files/2862599/packer.zip)

osx:
[packer.zip](https://github.com/hashicorp/packer/files/2862652/packer.zip)

**Comment by JohnnyBopper** [comment]
I'll test it out today and report back the results.

**Comment by JohnnyBopper** [comment]
Stripping out the \r resolved my issue with the clone process.

Thanks!
