### ISSUE TITLE
Virtualbox OVF/OVA mutates URL

### ISSUE THREAD

**Issue by Cirrith** [hashicorp/packer#7288]
Builder: Virtualbox ovf
Using source_path to specify username and password to access password protected ova online mutates characters so different password is displayed.

```json
{
    "builders": [{
        "type": "virtualbox-ovf",
        "source_path": "https://username:pass!word@website.com/image.ova",
        "ssh_username": "root"
    }]
}
```

Results in the following:
Downloading: `https://username:pass%21word@website.com/image.ova`

Looks like it is occurring with the following characters:
!@*()

Each character maps to a different %XX value
I only tried the top row of qwerty keyboard

Packer Version: 1.3.3
Host platform: Ubuntu 18.04, amd64

**Comment by rickard-von-essen** [comment]
The URL is url encoded, that is how it should be. To my knowledge `source_path` doesn't support Basic Auth.

**Comment by Cirrith** [comment]
You can do authorization in the url but it seems like it isn't 100% encoding it one way or another cause ':' should have resolved so %3A
https://en.wikipedia.org/wiki/Percent-encoding

**Comment by SwampDragons** [comment]
We have a PR in progress right now that should resolve this, so I'm not going to work on it independently at the moment -- to work around for now, you can download the file to a local cache and just give Packer the filepath.

**Comment by Cirrith** [comment]
Of course, looks like a big change. I was hoping not to put a wrapper script around packer. I will double check after the PR is done. Thank you, amazing tool!
