### ISSUE TITLE
Vsphere-template post processor failing with "Artifact type mitchellh.vmware does not fit this requirement"

### ISSUE THREAD

**Issue by spstratis** [hashicorp/packer#7289]
Packer v1.3.4
MacOS Mojave

Packer Log output
https://gist.github.com/spstratis/b8abe1795bea6dd45b0d60cba06a8066

Packer Build Scrip
https://gist.github.com/spstratis/097a47cad65f258320ecae7808f75085

I'm trying to build a vmware-iso locally using vmware fusion and then have the vsphere post processeor export it to vSphere and then have the vsphere-template post-processor convert it into template. It's failing with the following error though.

```* Post-processor failed: The Packer vSphere Template post-processor can only take an artifact from the VMware-iso builder, built on ESXi (i.e. remote) or an artifact from the vSphere post-processor. Artifact type mitchellh.vmware does not fit this requirement```

The vsphere post processor works fine, the issue occurs after it tries to run the vsphere-template post-processor. I saw another issue that was closed for this from a few months ago. It looks like a fix was merged into the newest release (1.3.4) for it but I'm still running into it. 

I also tried adding the `vmx_data property` for `"bios.hddorder": ""` but that also did not work. Any ideas?

Thanks!

**Comment by rickard-von-essen** [comment]
As the error message says; `vsphere-template` pp only takes the output from  `vmware-*` builders running on a remote ESXi server.

**Comment by rickard-von-essen** [comment]
If you add another pair of `[]` around your pp's you will get a sequence and it will do what you want.

**Comment by spstratis** [comment]
Ah you're right! I missed the extra set of brackets, thanks for pointing that out!
