### ISSUE TITLE
source_ami_filter permits only one value for name

### ISSUE THREAD

**Issue by grodzik** [hashicorp/packer#7295]
Hi,

I'm building an AMI based on Debian base image (`debian-stretch-hvm-x86_64-gp2-*`). This requires doing `apt upgrade` during building, which slowly takes longer, taking into account that more updates come out since release of the given base image. Let's assume my image will be called `my-debian-based-image-{{timestamp}}`. I would like to give both names to filter out most recent. Kind of incremental build, only if last build is newer than `debian-stretch-hvm-x86_64-gp2-*`. Using AWS CLI I can filter images using both names, like so:

    aws ec2 describe-images --filters "Name=name,Values=debian-stretch-hvm-x86_64-gp2-*,my-debian-based-image-*" --query "Images[].Name"

Unfortuantely this is not possible to achieve in packers `source_ami_filter`. It's impossible to pass array for filters attributes. Passing whole Values string from above also doesn't work, which is errored in the console like so:

    2019/02/08 15:13:37 ui error: Build 'amazon-ebs' errored: No AMI was found matching filters: {
        Filters: [{
            Name: "name",
            Values: ["debian-stretch-hvm-x86_64-gp2-*,my-debian-based-image-*"]
        }]
    }

Looking at the source code (I'm not a Go programmer), I would say this has something to do with it: https://github.com/hashicorp/packer/blob/master/builder/amazon/common/build_filter.go#L13
where I would expect that string to be splited on `,` into array.

- packer version: 1.3.4
- platform: Debian Linux

**Comment by rickard-von-essen** [comment]
`filters (map of strings)` should really be `filters (map of strings to array of strings)` which should result in:

```
    Filters: [{
        Name: "name",
        Values: ["debian-stretch-hvm-x86_64-gp2-*", "my-debian-based-image-*"]
    }]
```

The change is quite easy to do, we just have to be careful to not cause any unwanted side-effects.

(For example does `"tag:Class": "build,production"` mean something tagged with key `Class` and value `build,production`, or something tagged with key `Class` and value `build` _or_ `production?)

**Comment by grodzik** [comment]
Taking into account how it works currently this should mean `tag:Class` with value `build,production`. If one would like to make it `build` or `production`, then it should be required to make it an array of strings `["build", "production"]` explicilty. In such way it would be backward compatible.

**Comment by rickard-von-essen** [comment]
What makes that problematic is that the framework currently take a string and splits it on command if the template actually expects an array.

**Comment by grodzik** [comment]
Where's the splitting part? From the logs/experience it just makes from it one element array. Or what are the split separators?

**Comment by rickard-von-essen** [comment]
No if you have:

```json
{
  "variables": { "SGs": "sg-123,sg-987" },
  "builders": [{
     "type": "amazon-ebs",
     "security_group_ids": "{{user `SGs`}}",
     [...]
  }]
}
```

That will be translated into `"security_group_ids": [ "sg-123", "sg-987" ]`

**Comment by dev-head** [comment]
what if you have a comma in the value that you don't want it to split against?
