### ISSUE TITLE
amazon-import post processor should update the manifest

### ISSUE THREAD

**Issue by sfdc-afraley** [hashicorp/packer#7297]
When using the amazon-import post-processor combined with the manifest post-processor, the resulting manifest does not contain any information about the imported AMI.  The only way to get the imported AMI id is to parse the Packer stdout.  It would be great if the imported AMI id could be added to the manifest.

**Comment by rickard-von-essen** [comment]
This seems like a bug to me.

**Comment by rickard-von-essen** [comment]
Do you have some example manifests from `amazon-import` and from any `amazon` builder?

**Comment by rickard-von-essen** [comment]
From `amazon-ebs`:

```json
{
  "builds": [
    {
      "name": "amazon-ebs",
      "builder_type": "amazon-ebs",
      "build_time": 1549645168,
      "files": null,
      "artifact_id": "eu-west-1:ami-0bc110fe83195b205",
      "packer_run_uuid": "6cb331df-4ab2-2d4d-9ac0-640211402956",
      "custom_data": null
    }
  ],
  "last_run_uuid": "6cb331df-4ab2-2d4d-9ac0-640211402956"
}
```

**Comment by rickard-von-essen** [comment]
From the code it really looks like this should work.

**Comment by rickard-von-essen** [comment]
Please supply the information requested in the issue template:
- Packer version (`packer version`)
- Host platform (`uname -a` etc.)
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a [gist](https://gist.github.com).
- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your [gist](https://gist.github.com).

**Comment by sfdc-afraley** [comment]
Thanks, @rickard-von-essen

To clarify, the resulting packer-manifest.json file has info from the virtualbox builder I'm using, but it does not contain any info about the AMI created from the amazon-import post-processor.  

- Packer Version: tested on 1.3.2 and 1.3.4 with the same results
- Host platform: Darwin redacted 17.7.0 Darwin Kernel Version 17.7.0: Thu Dec 20 21:47:19 PST 2018; root:xnu-4570.71.22~1/RELEASE_X86_64 x86_64
- Gist with template, debug log, and resulting manifest: https://gist.github.com/sfdc-afraley/98e0115f9d2937d438255277cd73b9a5

**Comment by SwampDragons** [comment]
I suspect that's because you haven't used a [sequence definition](https://www.packer.io/docs/templates/post-processors.html#post-processor-definition) for post-processors. There should be an extra pair of brackets wrapping them if you want the manifest pp to use output from the amazon-import pp rather than the builder.

**Comment by rickard-von-essen** [comment]
@SwampDragons exactly.

**Comment by sfdc-afraley** [comment]
Thanks, it does work if they're wrapped in another pair of brackets.

For posterity, this does not work:
```
"post-processors": [
    {
    "type": "amazon-import",
    "ami_name": "import_test",
    "region": "{{ user `target_region` }}",
    "s3_bucket_name": "{{ user `s3_artifact_bucket` }}",
    "role_name": "{{ user `aws_vmimport_role` }}"
    },
    { "type":"manifest" }
  ]
```

This does work:
```
"post-processors": [
    [
      {
      "type": "amazon-import",
      "ami_name": "import_test",
      "region": "{{ user `target_region` }}",
      "s3_bucket_name": "{{ user `s3_artifact_bucket` }}",
      "role_name": "{{ user `aws_vmimport_role` }}"
      },
      { "type":"manifest" }
    ]
  ]
```
