### ISSUE TITLE
vmware-iso ISO locations

### ISSUE THREAD

**Issue by shortstack** [hashicorp/packer#7306]
I'm trying to build Ubuntu and Windows VMs on ESXi 6.7 with Packer, using the vmware-iso builder.

Is it possible to use ISOs available in vSphere (that are already available in a datastore) to provision systems? Or is it only local files and URLs? 
  
Migrating from the "vsphere-iso" builder, where that was possible (below snippet), but not seeing that option with the "vmware-iso" builder.

```
     "iso_paths": [
       "[ISOs] Ubuntu/ubuntu-16.04-server-amd64.iso"
     ]
```

Thank you.

**Comment by SwampDragons** [comment]
I don't think that is currently possible, but it's a good idea. Right now though Packer will download the file to the system it's running on before uploading it to your esxi instance.  The good news is that once it's on that instance, Packer won't re-upload it every time.

**Comment by shortstack** [comment]
i saw that, yes. thank you for clarifying :) and noticed that it caches it. would be really great if that were possible in the future, instead of having to host the ISOs separately.

thanks for the quick response!

**Comment by SwampDragons** [comment]
Yeah, I like the idea and I'll leave this issue open until we get a chance to implement it.

**Comment by ktmorgan** [comment]
Correct me if I'm wrong, but I think this was implemented in version 1.3.0.

https://github.com/hashicorp/packer/pull/5165

By setting these values, I am able to accomplish that.
```
"iso_url": "CentOS-7-x86_64-NetInstall-1810.iso" # Name of the ISO file
"remote_cache_directory": "iso"                  # Directory on the datastore where the ISO resides
"remote_datastore": "datastore1"                 # Name of the datastore on your ESXi instance
```

And this is the output when running packer
```
==> vmware-iso: Retrieving ISO
    vmware-iso: Using file in-place: file://./CentOS-7-x86_64-NetInstall-1810.iso
==> vmware-iso: Remote cache was verified skipping remote upload...
```

**Comment by bugbuilder** [comment]
@ktmorgan you're right

**Comment by SwampDragons** [comment]
Oh, cool. Thanks for the correction.

**Comment by bavivek2003** [comment]
> Oh, cool. Thanks for the correction.

i believe with current version this is blocked. because my same code works fine with older version 1.3.4 but with new version its not working 1.4.5

**Comment by SwampDragons** [comment]
If you think there's been a regression, can you please open a new issue with all the details requested in the issue template so I can investigate?
