### ISSUE TITLE
New filter for template engine: {{pwd | file_uri}} or {{template_dir | file_uri}}

### ISSUE THREAD

**Issue by nsballmann** [hashicorp/packer#7308]
## Proposal

In the [template engine of packer](https://www.packer.io/docs/templates/engine.html#functions) there are *filters* (at least that's how [Jinja2 calls them](http://jinja.pocoo.org/docs/2.10/templates/#filters)) like this:

    {{isotime | clean_image_name}}

I want to propose a new filter: 

    {{pwd | file_uri}}
    {{template_dir | file_uri}}

It converts a path from the format of the packer host os (Windows/Linux/...) into the format of a [file URI](https://en.wikipedia.org/wiki/File_URI_scheme).

## Use case

In some places in the packer templates only URIs are allowed as values. Those allow to use file URIs. This is good for accessing files which are placed by SCM or other means. As [relative paths are not allowed in file URIs](https://stackoverflow.com/a/19204256) the obvious choice to access files like this, is to use `{{pwd}}` or `{{template_dir}}`:

```json
{
  "builders": [{
    "type": "virtualbox-iso",
    "iso_checksum_type": "sha256",
    "iso_checksum_url": "file://{{template_dir}}/src/ubuntu-18.04.1-server-amd64.iso.sha256sum",
    "iso_url": "file://{{template_dir}}/src/ubuntu-18.04.1-server-amd64.iso"
  }]
}
```

While this works out of the box on Linux:

```shell-session
packer@heppo:~$ packer validate ./packer.json
Template validated successfully.
packer@heppo:~$ packer build -color=false -force ./packer.json
==> virtualbox-iso: Retrieving ISO
    virtualbox-iso: Using file in-place: file:///home/packer/src/ubuntu-18.04.1-server-amd64.iso
```

It fails on Windows:

```ps1con
PS [packer@host] C:\Users\packer
> packer validate ./packer.json
Template validation failed. Errors are shown below.

Errors validating build 'virtualbox-iso'. 1 error(s) occurred:

* Error parsing checksum: parse file://C:\Users\packer/src/ubuntu-18.04.1-server-amd64.iso.sha256sum: invalid character "\\" in host name
```

Having the filter, the template would change to:

```json
{
  "builders": [{
    "type": "virtualbox-iso",
    "iso_checksum_type": "sha256",
    "iso_checksum_url": "{{template_dir | file_uri}}/src/ubuntu-18.04.1-server-amd64.iso.sha256sum",
    "iso_url": "{{template_dir | file_uri}}/src/ubuntu-18.04.1-server-amd64.iso"
  }]
}
```

Which then would result in something [like this](https://en.wikipedia.org/wiki/File_URI_scheme#Windows):

```ps1con
PS [packer@host] C:\Users\packer
> packer build -color=false -force ./packer.json
==> virtualbox-iso: Retrieving ISO
    virtualbox-iso: Using file in-place: file:///c:/Users/packer/src/ubuntu-18.04.1-server-amd64.iso
```

### Linux

```shell-session
packer@heppo:~$ packer --version
1.3.3
packer@heppo:~$ uname -a
Linux heppo 4.15.0-43-generic #46~16.04.1-Ubuntu SMP Fri Dec 7 13:31:08 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
packer@heppo:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial
```

### Windows

```ps1con
PS [packer@host] C:\Users\packer
> packer --version
1.3.3
PS [packer@host] C:\Users\packer
> [Environment]::OSVersion

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.15063.0 Microsoft Windows NT 10.0.15063.0
```

**Comment by SwampDragons** [comment]
This makes sense! I probably don't have time on my plate to work on it right now, but if anyone's interested -- implementing new template engines is pretty straightforward; essentially you just add your code to https://github.com/hashicorp/packer/blob/master/template/interpolate/funcs.go.  

Here's a fairly recent PR that implemented a new template func: https://github.com/hashicorp/packer/pull/6580/files

**Comment by programmer04** [comment]
I would like to implement it @SwampDragons @nsballmann , but it turned out to be a little tricky. First of all, there is no way to determinate if a string is a correct path for Windows or Linux, if it requires conversion etc. For example in Linux paths with `\` are correct e.g. `/etc/fun/test\ tt/file.txt`. Evaluation based on which platform Packer is running on can provide error when a user passes a Windows path on Linux machine by e.g. variable (any case without usage of `pwd` or `template_dir` is potentially dangerous). Moreover, file URI spec https://tools.ietf.org/html/rfc8089 provides many possibilities for what is considered as valid. So imho there is no way to do it robustly. I can propose implementing something like `path_win_to_unix`, which simply change from `\` to `/` in a passed string. Or maybe a user should use a `sed` filter and do it on his/her own. What do you think?

**Comment by azr** [comment]
Howdy @programmer04, `"github.com/hashicorp/go-getter/helper/url".Parse` will change `\` to `/` for you, it's used in the step download. In general it tries to return uniformly formatted urls, eg:

https://github.com/hashicorp/packer/blob/721cad10125d3d98c4357d457b02463598861f85/common/step_download.go#L79-L82

**Comment by programmer04** [comment]
Hi @azr thanks for a piece of advice. But this helper only works properly with Windows path on a Windows machine.
On MacOS for Windows path:
```go
u, err := urlhelper.Parse("c:\\WINDOWS\\clock.json")
// gives <nil> parse file://c:%2FWINDOWS%2Fclock.json: invalid URL escape "%2F"
```
In the case of this issue, users can pass a path as a string in whatever format they want. I know that it is probably an edge case to use this filter `file_uri` for a Windows path on non Windows machine,  but still a case to consider. In solution I'd like to avoid a surprise for end user. So maybe simple new filter `path_win_to_unix` or even usage of existing `sed` filter is the best option for creating file URI from path?

**Comment by azr** [comment]
@programmer04 yes this is a concern I had when I saw this func but then I couldn't come up with a case where this would happen &  be an issue. [ when using files ]. Do you have one ?
My thought is that if your are using `c:\\WINDOWS\\clock.json` then you are running on a windows system.

**Comment by programmer04** [comment]
@azr good question. I want to make it robust for all cases. The only case which comes up my mind is when a user uses Packer on non Windows machine to build a Windows image and use proposed `file_uri` for a path which provides himself/herself explicitly as a string e.g. using the proposed `file_uri` to modify path passed as variable in a provisions section or some other little weird idea.

**Comment by SwampDragons** [comment]
Packer intentionally tries to know nothing about the operating system of the guest machine -- therein lies madness, and this is just one example of why.

It sounds to me like this is maybe a change that would cause more complexity than it would prevent. Maybe users would be better served by doing any file URI conversions themselves? It's very possible that the "best" solution is just to update the docs by adding an example of a file URI conversion using the current template options.

**Comment by azr** [comment]
Yup, I agree with you there @SwampDragons. Also, the recent go-getter merge improved this issue a bit as the go-getter has a robust path mechanisms.

**Comment by programmer04** [comment]
So to wrap up:
- nothing new to implement,
- I will make a pull request, which enhances [template docs](https://github.com/hashicorp/packer/blob/master/website/source/docs/templates/engine.html.md) by providing an example about manipulating a file path with usage of `sed`

**Comment by nsballmann** [comment]
I specifically had in mind to restrict the usage of the `file_uri` filter to the template functions `pwd` and `template_dir`, because their values are acquired in a host OS dependent manner. Then the values are of known format and then the conversion *should* be trivial, maybe even built-in in Go (in Python it is, Go is unknown to me).

If you broaden the usage of the filter to *all paths* there is way more complexity ahead.

Isn't there a [PathLib](https://docs.python.org/3.6/library/pathlib.html) equivalent in Go? Getting right all edge cases in path conversion is, to my knowledge, worthy its own library.

**Comment by SwampDragons** [comment]
Closing this issue as stale; it seems that the consensus was that it's more complex to support than it's worth, and properly formatting uris in variables should be up to the user.
