### ISSUE TITLE
ISO download fails if hash changes, but URL remains the same.

### ISSUE THREAD

**Issue by ladar** [hashicorp/packer#7309]
I ran into an edge case. I recently started building Ubuntu 19.04 pre-release images using the daily ISOs. Unfortunately the URL for the ISO, `http://cdimage.ubuntu.com/ubuntu-server/daily/current/disco-server-amd64.iso` stays consistent, and only hash value changes. 

The problem is `packer` only uses the URL for the cached file name, so it sees a file, but fails when it compares the hashes value. Unfortunately the only solution is figuring out which file it's using and removing it manually. 

Presumably `packer` should use either a combination of the URL and hash for the filename, or simply use the hash provided by the template as the filename (presumably running SHA-2-256 on any non SHA-2-256 hashes). 

If changing the this schema doesn't sound like a good option, then `packer` should definitely behave differently after a hash value mismatch. Namely, if it finds an existing file, and partial download/check of that file fails, it should remove the file and try a full, fresh download before completely failing completely. 

A less ideal, but possibly easier to implement option would be adding a template config parameter which forces `packer` to delete a partial download (aka a cached file which doesn't match the template hash), and perform a full download. Something akin to the `vagrant box add --clean` behaviour.

**Comment by ladar** [comment]
I forgot to post the `packer` output:

```
bash-3.2$ ./robox.sh box generic-ubuntu1904-parallels,generic-hardenedbsd12-parallels,generic-alpine35-parallels,generic-centos6-parallels,generic-fedora29-parallels
generic-ubuntu1904-parallels output will be in this color.
generic-hardenedbsd12-parallels output will be in this color.
generic-alpine35-parallels output will be in this color.
generic-centos6-parallels output will be in this color.
generic-fedora29-parallels output will be in this color.

==> generic-ubuntu1904-parallels: Retrieving ISO
    generic-ubuntu1904-parallels: Error downloading: Error making HTTP GET request: 416 Requested Range Not Satisfiable
==> generic-ubuntu1904-parallels: ISO download failed.
Build 'generic-ubuntu1904-parallels' errored: ISO download failed.
```

I presume this error output means `packer` is finding the cached ISO file, and presuming that it needs to continue the download. I assume it uses the file size as the start position in the HTTP request. But since the current file is the same size, or smaller, as the cached file, this logic leads to the HTTP error above.

P.S. While looking into this issue I noticed the (relatively) new `iso_checksum_url` option. I hope to make use of that soon! But doubt it will fix this logic error...

**Comment by SwampDragons** [comment]
Ah, yeah, this makes sense.  I'm not going to address this right now because I'd like to check how it behaves once we get go-getter fully integrated.

**Comment by ladar** [comment]
No problem. It's a low priority issue, but thought it was worth logging, if for no other reason, in case someone else searches for the error message, etc.

**Comment by azr** [comment]
Hello there ! The go-getter PR changes how cache files are named; it is now: [`hash($iso_url+$iso_checksum).$iso_target_extension`](https://github.com/hashicorp/packer/pull/6999/commits/81c2c8f26a51f46eaf6a0befcda25ee99fcf1b22#diff-c9789dd04427aa464fd77d9637557536R3) so this should be fixed by it 🙂

**Comment by SwampDragons** [comment]
@ladar do you think you could send me an email?  megan at hashicorp.com . I'd like to have Hashicorp send you a little gift in thanks for all your contributions this year but I need some real life contact info from you.
