### ISSUE TITLE
Openstack image gets deleted after their creation with packer

### ISSUE THREAD

**Issue by gkoudjou** [hashicorp/packer#7312]
Hi,

I encounter the same issue as [the one described here (1415)](https://github.com/hashicorp/packer/issues/1415). (which is closed - i've tested all the workaround shown there)

Everytime i create an image on Openstack, it is get deleted at the end of the process. Here is the basic output of the packer command (see below with the one including log in gist)
```
openstack output will be in this color.

==> openstack: Loading flavor: 3
    openstack: Verified flavor. ID: 3
==> openstack: Not using temporary keypair
==> openstack: Launching server...
==> openstack: Launching server...
    openstack: Server ID: e2b01440-df6d-4c34-be0d-3cb0f4d8f3cd
==> openstack: Waiting for server to become ready...
    openstack: Floating IP not required
==> openstack: Using ssh communicator to connect: 10.121.156.145
==> openstack: Waiting for SSH to become available...
==> openstack: Connected to SSH!
==> openstack: Provisioning with shell script: /tmp/packer-shell318391672
==> openstack: Stopping server: e2b01440-df6d-4c34-be0d-3cb0f4d8f3cd ...
    openstack: Waiting for server to stop: e2b01440-df6d-4c34-be0d-3cb0f4d8f3cd ...
==> openstack: Creating the image: distrib_cmr
    openstack: Image: c907cc11-a118-46a9-b471-15fd1897fbcb
==> openstack: Waiting for image distrib_cmr (image id: c907cc11-a118-46a9-b471-15fd1897fbcb) to become ready...
==> openstack: Terminating the source server: e2b01440-df6d-4c34-be0d-3cb0f4d8f3cd ...
Build 'openstack' finished.

==> Builds finished. The artifacts of successful builds are:
--> openstack: An image was created: c907cc11-a118-46a9-b471-15fd1897fbcb

```

Here are informations about my environment :

- Packer version 1.3.4
- OS : RHEL 7.3 (Running in a Vagrant box)
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  => https://gist.github.com/gkoudjou/f8840f82483f3eff1bbc0bc6dd2cabbf
- The _simplest example template and scripts_ needed to reproduce the bug.
```  
 {
    "variables" : {
        "u_username": "{{ env `$OS_USERNAME` }}",
        "u_password": "{{ env `$OS_PASSWORD` }}",
        "u_osregionname" : "{{ env `OS_REGION_NAME` }}"
    },
    "builders": [
        {
            "type": "openstack",
            "username": "{{ user `u_username` }}",
            "password": "{{ user `u_password` }}",
            "identity_endpoint": "https://zXXXXXXX:5000/v3/",
            "image_name": "distrib_cmr",
            "ssh_username": "XXXXX",
            "ssh_password": "XXXXXXXX",
            "ssh_read_write_timeout" : "10m",
            "ssh_timeout": "15m",
            "ssh_handshake_attempts" : "50",
            "source_image": "5d8a07e0-9f94-48a6-8291-d57859254f2a",
            "flavor": "3",
            "ssh_ip_version": "4",
            "networks": [
                "ee6a0689-b666-4c03-a9d7-17e1f1156f59"
             ]
        }
    ],
    "provisioners": [
        {
            "inline": [
                "sync", "echo 'test' > /tmp/file_in_image"
            ],
            "type": "shell"
        }
    ]
}
```
 Can anyone please provide help ?

I'm stuck with it since a couple of days.

Thanks

**Comment by rickard-von-essen** [comment]
That log says that everything is perfect?! The image `c907cc11-a118-46a9-b471-15fd1897fbcb` was created.

Can you explain more in detail what you think is wrong.

**Comment by gkoudjou** [comment]
Because at the end of the process, the image disappears (OpenStack IHM). And even when i get all available image with 

`openstack image list`

I don't have the newly created image. Plus, i have some DELETE statements in the log (see the gist) and it seems that the image is deleted when the source server is being deleted.

**Comment by rickard-von-essen** [comment]
I have a vague memory of something like this, and it turned out to be a problem with the OpenStack installation. Could you check with an administrator. Seems like packer waits for the image creation to complete and it does. You could try to run `openstack image show <id>` in a loop during the time image of the image creation.

**Comment by rickard-von-essen** [comment]
For the DELETE statement do you have a corresponding api call? Does it come from the IP of the machine running Packer? What's the user agent?

**Comment by gkoudjou** [comment]
Thanks for your answer.

I don't have access to the server to analyse glance/nova logs. So i asked an administrator to help me identify the source of the DELETE API call

Could you please be more specific about the installation problem you found on OpenStack that lead to the same behavior ?

**Comment by rickard-von-essen** [comment]
It was probably [this post](https://groups.google.com/d/msgid/packer-tool/40c5530a-b52a-4ad8-9857-b082601088e9%40googlegroups.com?utm_medium=email&utm_source=footer) I was thinking about.

I haven't been working actively with OS for many years so I can't really point you to where to look.

**Comment by gkoudjou** [comment]
Hello,

Following the intuition of a colleague, i was finally able to successfully build and push the image to openstack.

I activate the debug mode and step by step see the result of each packer command on Openstack.
On the create image, i wait for around 5/10 minutes just to be sure that the saving is complete (in the gist, we saw that the saving is stopped around 50%).

**The new hypothesis is that packer don't wait for the image to be completly saved before destroying the source instance. When the source instance is destroyed, as the saving is in progress, the image is also destroyed.**

Here is the log of the command. 

> (vEnv27) [vagrant@localhost ~]$ OS_USER_DOMAIN_NAME="Default" packer-io build -debug packer.json
Debug mode enabled. Builds will not be parallelized.
openstack output will be in this color.
==> openstack: Loading flavor: 3
    openstack: Verified flavor. ID: 3
==> openstack: Pausing after run of step 'StepLoadFlavor'. Press enter to continue.
==> openstack: Not using temporary keypair
==> openstack: Pausing after run of step 'StepKeyPair'. Press enter to continue.
==> openstack: Pausing after run of step 'StepSourceImageInfo'. Press enter to continue.
==> openstack: Pausing after run of step 'StepCreateVolume'. Press enter to continue.
==> openstack: Launching server...
==> openstack: Launching server...
    openstack: Server ID: 4a84779e-158c-410c-b1e7-9f128441dd86
==> openstack: Waiting for server to become ready...
==> openstack: Pausing after run of step 'StepRunSourceServer'. Press enter to continue.
==> openstack: Pausing after run of step 'StepGetPassword'. Press enter to continue.
==> openstack: Pausing after run of step 'StepWaitForRackConnect'. Press enter to continue.
    openstack: Floating IP not required
==> openstack: Pausing after run of step 'StepAllocateIp'. Press enter to continue.
==> openstack: Using ssh communicator to connect: 10.121.157.27
==> openstack: Waiting for SSH to become available...
==> openstack: Connected to SSH!
==> openstack: Pausing after run of step 'StepConnect'. Press enter to continue.
==> openstack: Pausing before the next provisioner . Press enter to continue.
==> openstack: Provisioning with shell script: /tmp/packer-shell232078904
==> openstack: Pausing after run of step 'StepProvision'. Press enter to continue.
==> openstack: Pausing after run of step 'StepCleanupTempKeys'. Press enter to continue.
==> openstack: Stopping server: 4a84779e-158c-410c-b1e7-9f128441dd86 ...
    openstack: Waiting for server to stop: 4a84779e-158c-410c-b1e7-9f128441dd86 ...
==> openstack: Pausing after run of step 'StepStopServer'. Press enter to continue.
==> openstack: Pausing after run of step 'StepDetachVolume'. Press enter to continue.
==> openstack: Creating the image: distrib_cmr
    openstack: Image: a2d2c9cc-2aca-44d8-808a-23421ba3f35e
==> openstack: Waiting for image distrib_cmr (image id: a2d2c9cc-2aca-44d8-808a-23421ba3f35e) to become ready...
==> openstack: Pausing after run of step 'stepCreateImage'. Press enter to continue.
==> openstack: Pausing after run of step 'stepUpdateImageTags'. Press enter to continue.
==> openstack: Pausing after run of step 'stepUpdateImageVisibility'. Press enter to continue.
==> openstack: Pausing after run of step 'stepAddImageMembers'. Press enter to continue.
==> openstack: Pausing before cleanup of step 'stepAddImageMembers'. Press enter to continue.
==> openstack: Pausing before cleanup of step 'stepUpdateImageVisibility'. Press enter to continue.
==> openstack: Pausing before cleanup of step 'stepUpdateImageTags'. Press enter to continue.
==> openstack: Pausing before cleanup of step 'stepCreateImage'. Press enter to continue.
==> openstack: Pausing before cleanup of step 'StepDetachVolume'. Press enter to continue.
==> openstack: Pausing before cleanup of step 'StepStopServer'. Press enter to continue.
==> openstack: Pausing before cleanup of step 'StepCleanupTempKeys'. Press enter to continue.
==> openstack: Pausing before cleanup of step 'StepProvision'. Press enter to continue.
==> openstack: Pausing before cleanup of step 'StepConnect'. Press enter to continue.
==> openstack: Pausing before cleanup of step 'StepAllocateIp'. Press enter to continue.
==> openstack: Pausing before cleanup of step 'StepWaitForRackConnect'. Press enter to continue.
==> openstack: Pausing before cleanup of step 'StepGetPassword'. Press enter to continue.
==> openstack: Pausing before cleanup of step 'StepRunSourceServer'. Press enter to continue.
==> openstack: Terminating the source server: 4a84779e-158c-410c-b1e7-9f128441dd86 ...
==> openstack: Pausing before cleanup of step 'StepCreateVolume'. Press enter to continue.
==> openstack: Pausing before cleanup of step 'StepSourceImageInfo'. Press enter to continue.
==> openstack: Pausing before cleanup of step 'StepKeyPair'. Press enter to continue.
==> openstack: Pausing before cleanup of step 'StepLoadFlavor'. Press enter to continue.
Build 'openstack' finished.
==> Builds finished. The artifacts of successful builds are:
--> openstack: An image was created: a2d2c9cc-2aca-44d8-808a-23421ba3f35e
(vEnv27) [vagrant@localhost ~]$
(vEnv27) [vagrant@localhost ~]$
(vEnv27) [vagrant@localhost ~]$ openstack image list
+--------------------------------------+------------------+--------+
| ID                                   | Name             | Status |
+--------------------------------------+------------------+--------+
| bae34333-9217-43a3-b4b1-1e793362aefa | CentOS-7-N1      | active |
| 09df4544-043f-4b37-aec6-aa79fcbd3811 | CentOS-7-N3      | active |
| e5cf2edc-2ed4-476d-bde1-734d71ea1877 | RHEL-6.6-N1      | active |
| 5d8a07e0-9f94-48a6-8291-d57859254f2a | RHEL-6.6-N3      | active |
| 8edfd371-beb2-4319-a116-c8b76d9b5eed | RHEL-7.1-N1      | active |
| 5bd4be23-f6d7-4f37-9792-3e76cc0f9cc6 | RHEL-7.1-N3      | active |
| 7fe7aca2-1ceb-491b-a792-40427d8c409f | RHEL-7.3-N1      | active |
| 4a8eac7a-c6a2-4fd9-ad04-9712cdb20f68 | RHEL-7.3-N3      | active |
| 6dfb98dc-6bca-42c6-a2bd-b808ad420ecc | Windows2008R2-N1 | active |
| 96c6d7db-d2cd-4de1-a507-064bb030b7ed | Windows2012R2-N1 | active |
| a2d2c9cc-2aca-44d8-808a-23421ba3f35e | distrib_cmr      | active |
+--------------------------------------+------------------+--------+
(vEnv27) [vagrant@localhost ~]$

Is it a known bug ? (supposing is it considered a bug)
Is there a way to add some timeout in the image creation step ?

Thanks

**Comment by rickard-von-essen** [comment]
Packer waits until the image is _active_ or return an error. See https://github.com/hashicorp/packer/blob/master/builder/openstack/step_create_image.go

**Comment by gkoudjou** [comment]
Thanks for your reply.

I've analyse the source code and I found myself in a situation where the image creation was blocked by OpenStack. As in the WaitForImage function, it seems to be an infinite loop, i was unable to cancel the process. Here are the log after more than 200 CTRL-C. See the log below please.

Otherwise, to get back to the initial problem, my entreprise OpenStack administrator is analysing the server log. I will get you feedback after further tests.

The infinite loop while trying to stop the process in WaitForImage

> 2019/02/19 11:27:14 packer-io: 2019/02/19 11:27:14 Received interrupt signal (count: 213). Ignoring.
^C2019/02/19 11:27:14 packer-io: 2019/02/19 11:27:14 Received interrupt signal (count: 214). Ignoring.
2019/02/19 11:27:14 packer-io: 2019/02/19 11:27:14 Received interrupt signal (count: 214). Ignoring.
^C2019/02/19 11:27:14 packer-io: 2019/02/19 11:27:14 Received interrupt signal (count: 215). Ignoring.
2019/02/19 11:27:14 packer-io: 2019/02/19 11:27:14 Received interrupt signal (count: 215). Ignoring.
^C2019/02/19 11:27:14 packer-io: 2019/02/19 11:27:14 Received interrupt signal (count: 216). Ignoring.
2019/02/19 11:27:14 packer-io: 2019/02/19 11:27:14 Received interrupt signal (count: 216). Ignoring.
^C2019/02/19 11:27:14 packer-io: 2019/02/19 11:27:14 Received interrupt signal (count: 217). Ignoring.
2019/02/19 11:27:14 packer-io: 2019/02/19 11:27:14 Received interrupt signal (count: 217). Ignoring.
^C2019/02/19 11:27:14 packer-io: 2019/02/19 11:27:14 Received interrupt signal (count: 218). Ignoring.
2019/02/19 11:27:14 packer-io: 2019/02/19 11:27:14 Received interrupt signal (count: 218). Ignoring.
^C2019/02/19 11:27:14 packer-io: 2019/02/19 11:27:14 Received interrupt signal (count: 219). Ignoring.
2019/02/19 11:27:14 packer-io: 2019/02/19 11:27:14 Received interrupt signal (count: 219). Ignoring.
^C2019/02/19 11:27:14 packer-io: 2019/02/19 11:27:14 Received interrupt signal (count: 220). Ignoring.
2019/02/19 11:27:14 packer-io: 2019/02/19 11:27:14 Received interrupt signal (count: 220). Ignoring.
^C2019/02/19 11:27:14 packer-io: 2019/02/19 11:27:14 Received interrupt signal (count: 221). Ignoring.
2019/02/19 11:27:14 packer-io: 2019/02/19 11:27:14 Received interrupt signal (count: 221). Ignoring.
^C2019/02/19 11:27:14 packer-io: 2019/02/19 11:27:14 Received interrupt signal (count: 222). Ignoring.
2019/02/19 11:27:14 packer-io: 2019/02/19 11:27:14 Received interrupt signal (count: 222). Ignoring.
^C2019/02/19 11:27:14 packer-io: 2019/02/19 11:27:14 Received interrupt signal (count: 223). Ignoring.
2019/02/19 11:27:14 packer-io: 2019/02/19 11:27:14 Received interrupt signal (count: 223). Ignoring.

To kill the process, i use CTRL-Z + kill -9 ...

When I try to cancel the process while communicator establish SSH connection, everything is working fine and the instance server is properly terminated.

>==> openstack: Launching server...
    openstack: Server ID: e29bd358-4989-48a8-9924-6ba7e06e57af
==> openstack: Waiting for server to become ready...
    openstack: Floating IP not required
==> openstack: Using ssh communicator to connect: 10.121.157.12
==> openstack: Waiting for SSH to become available...
^C==> openstack: Terminating the source server: e29bd358-4989-48a8-9924-6ba7e06e57af ...
Build 'openstack' finished.
Cleanly cancelled builds after being interrupted.

**Comment by rickard-von-essen** [comment]
> As in the WaitForImage function, it seems to be an infinite loop, i was unable to cancel the process.

That is a bug, the loop should check for crtl-c, I filed #7325 for this.

**Comment by SwampDragons** [comment]
@rickard-von-essen now that 7325 is merged, is this solved?

**Comment by rickard-von-essen** [comment]
> Otherwise, to get back to the initial problem, my entreprise OpenStack administrator is analysing the server log. I will get you feedback after further tests.

I don't know if this has been resolved, but but I think we can close this and reopen if we get more information.
