### ISSUE TITLE
Arrow keys interpreted as integers

### ISSUE THREAD

**Issue by sincon-eu** [hashicorp/packer#7315]
First of all, thank you for maintaining and developing the tool:)

Hyper-v boot_cmd's down, left etc. keys are being interpreted as 2 and 4 respectively. Alphabetic keys work fine. Any ideas how to fix it/workarounds?
// I believe it's the same issue which was mentioned [here](https://github.com/hashicorp/packer/issues/5635)

Hosts: Win10r1709 / WS2019r1809
Guest: Sles15
Packer: 1.3.4

Typical log (meanwhile on host's grub 2s and 4s being "typed"):

    2019/02/15 13:09:09 packer.exe: 2019/02/15 13:09:09 Special code 'Press' '<left>' found, replacing with: &{[e0 4b] [e0 cb]}
    2019/02/15 13:09:11 packer.exe: 2019/02/15 13:09:11 [INFO] Waiting 2s
    2019/02/15 13:09:13 packer.exe: 2019/02/15 13:09:13 Special code 'Press' '<down>' found, replacing with: &{[e0 50] [e0 d0]}
    2019/02/15 13:09:13 packer.exe: 2019/02/15 13:09:13 Special code 'Press' '<down>' found, replacing with: &{[e0 50] [e0 d0]}

**Comment by SwampDragons** [comment]
Sounds like your computer thinks it has a numeric keypad with numlock on; on traditional numeric keypads, the left arrow is on the same key as 4, and the down arrow is on the same key as 2.
Looks like we don't have way to send numlock right now; lemme see if I can add that for you.

**Comment by SwampDragons** [comment]
Hmm, actually -- the problem may be this (from section 1.6 in https://www.win.tue.nl/~aeb/linux/kbd/scancodes-1.html):

> The ten grey keys Insert, Home, PgUp, Delete, End, PgDn, Up, Left, Down, Right are supposed to function regardless of the state of Shift and NumLock keys. But for an old AT keyboard the keypad keys would produce digits when Numlock was on or Shift was down. Therefore, in order to fool old programs, fake scancodes are sent: when LShift is down, and Insert is pressed, e0 aa e0 52 is sent; upon release of Insert e0 d2 e0 2a is sent. In other words, a fake LShift-up and fake LShift-down are inserted.
> 
> If the Shift key is released earlier than the repeated key, then a real Shift-up code occurs (without preceding fake Shift-down) so that a program ignoring e0 would see one more Shift-up than Shift-down.

**Comment by SwampDragons** [comment]
We can probably test this -- what happens if you send `<leftShiftOn><left><leftShiftOff>` instead of just <left>?

**Comment by sincon-eu** [comment]
That's exactly what I was looking for, thank you so much @SwampDragons !
