### ISSUE TITLE
amazon: fails to copy encrypted image to other regions

### ISSUE THREAD

**Issue by frank3427** [hashicorp/packer#7316]
packer 1.3 and 1.4 same issue
host ubuntu 18.09
I am using the following packer file; it is failing on the last function of copying to other regions.
copying encrypted AIM not supported. I would think that it would copy first then encrypt.
any help would be greatly appreciated.

Frank
 
{
  "_comment": "To create a new AMI in us-west-2 run:",
  "_comment": "  packer build -var aws_region='us-west-2' dockerhost.json",
  "_comment": "To create an AMI and copy to one or more regions, run:",
  "_comment": "  packer build -var aws_region='us-west-2' -var copy_to='us-west-1,eu-central-1' dockerhost.json",
  "variables": {
    "aws_region": "",
    "copy_to": "",
    "aws_vpc_id": "",
    "aws_subnet_id": "",
    "instance_type": "m3.medium",
    "version": "0.0.3"
  },
  "builders": [{
    "type": "amazon-ebs",
    "vpc_id": "{{user `aws_vpc_id`}}",
    "subnet_id": "{{user `aws_subnet_id`}}",
    "region": "{{user `aws_region`}}",
    "ami_regions": "{{user `copy_to`}}",
    "source_ami_filter": {
      "filters": {
        "virtualization-type": "hvm",
        "name": "CentOS Linux 7*",
        "state": "available",
        "root-device-type": "ebs"
      },
      "owners": [ "679593333241" ],
      "most_recent": true
    },
    "user_data_file": "./scripts/disable_requiretty.sh",
    "instance_type": "{{user `instance_type`}}",
    "ssh_username": "centos",
    "ami_name": "dockerhost {{timestamp}}",
    "encrypt_boot": true,
    "ena_support": true,
    "tags": {
      "Owner": "arrayent",
      "Version": "{{user `version`}}",
      "Environment": "packer build"
    }
  }],
  "provisioners": [{
    "type": "ansible",
    "user": "centos",
    "extra_arguments": "-vvv",
    "pause_before": "10s",
    "sftp_command": "/usr/libexec/openssh/sftp-server",
    "playbook_file": "../playbooks/packer/play.yml"
  }]
}

==> amazon-ebs: Stopping the source instance...
    amazon-ebs: Stopping instance, attempt 1
==> amazon-ebs: Waiting for the instance to stop...
==> amazon-ebs: Enabling Enhanced Networking (ENA)...
==> amazon-ebs: Creating unencrypted AMI FwOBiwF from instance i-0f3f4ac15c6b6cbc5
    amazon-ebs: AMI: ami-0f75316b152634e4f
==> amazon-ebs: Waiting for AMI to become ready...
==> amazon-ebs: Creating Encrypted AMI Copy
==> amazon-ebs: Copying AMI: us-east-2(ami-0f75316b152634e4f)
==> amazon-ebs: Waiting for AMI copy to become ready...
==> amazon-ebs: Deregistering unencrypted AMI
==> amazon-ebs: Deleting unencrypted snapshots
    amazon-ebs: Deleting Snapshot ID: snap-00cfa506fcaa0d4ee
==> amazon-ebs: Copying AMI (ami-0419bfd39943f48db) to other regions...
    amazon-ebs: Copying to: us-west-1
    amazon-ebs: Copying to: us-west-2
    amazon-ebs: Copying to: us-east-1
    amazon-ebs: Waiting for all copies to complete...
==> amazon-ebs: 3 error(s) occurred:
==> amazon-ebs: 
==> amazon-ebs: * Error Copying AMI (ami-0419bfd39943f48db) to region (us-east-1): InvalidRequest: Snapshot snap-05657965eb9352840 is encrypted. Creating unencrypted copy from an encrypted snapshot is not supported.
==> amazon-ebs: 	status code: 400, request id: 150f7ab3-6001-48cd-a768-f604952bf43b
==> amazon-ebs: * Error Copying AMI (ami-0419bfd39943f48db) to region (us-west-1): InvalidRequest: Snapshot snap-05657965eb9352840 is encrypted. Creating unencrypted copy from an encrypted snapshot is not supported.
==> amazon-ebs: 	status code: 400, request id: bffa5254-8dd2-4b7d-b826-09ac26eb787d
==> amazon-ebs: * Error Copying AMI (ami-0419bfd39943f48db) to region (us-west-2): InvalidRequest: Snapshot snap-05657965eb9352840 is encrypted. Creating unencrypted copy from an encrypted snapshot is not supported.
==> amazon-ebs: 	status code: 400, request id: 4b8a7831-4909-4707-84c4-1535b0a8f17d
==> amazon-ebs: Deregistering the AMI because cancellation or error...
==> amazon-ebs: Deregistering the AMI because cancellation or error...
==> amazon-ebs: Error deregistering AMI, may still be around: InvalidAMIID.Unavailable: The image ID 'ami-0f75316b152634e4f' is no longer available
==> amazon-ebs: 	status code: 400, request id: b83c1a0b-c407-492d-8793-8342220f1735
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Cleaning up any extra volumes...
==> amazon-ebs: Destroying volume (vol-0df7658d7627c001f)...
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: 3 error(s) occurred:

* Error Copying AMI (ami-0419bfd39943f48db) to region (us-east-1): InvalidRequest: Snapshot snap-05657965eb9352840 is encrypted. Creating unencrypted copy from an encrypted snapshot is not supported.
	status code: 400, request id: 150f7ab3-6001-48cd-a768-f604952bf43b
* Error Copying AMI (ami-0419bfd39943f48db) to region (us-west-1): InvalidRequest: Snapshot snap-05657965eb9352840 is encrypted. Creating unencrypted copy from an encrypted snapshot is not supported.
	status code: 400, request id: bffa5254-8dd2-4b7d-b826-09ac26eb787d
* Error Copying AMI (ami-0419bfd39943f48db) to region (us-west-2): InvalidRequest: Snapshot snap-05657965eb9352840 is encrypted. Creating unencrypted copy from an encrypted snapshot is not supported.
	status code: 400, request id: 4b8a7831-4909-4707-84c4-1535b0a8f17d

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: 3 error(s) occurred:

* Error Copying AMI (ami-0419bfd39943f48db) to region (us-east-1): InvalidRequest: Snapshot snap-05657965eb9352840 is encrypted. Creating unencrypted copy from an encrypted snapshot is not supported.
	status code: 400, request id: 150f7ab3-6001-48cd-a768-f604952bf43b
* Error Copying AMI (ami-0419bfd39943f48db) to region (us-west-1): InvalidRequest: Snapshot snap-05657965eb9352840 is encrypted. Creating unencrypted copy from an encrypted snapshot is not supported.
	status code: 400, request id: bffa5254-8dd2-4b7d-b826-09ac26eb787d
* Error Copying AMI (ami-0419bfd39943f48db) to region (us-west-2): InvalidRequest: Snapshot snap-05657965eb9352840 is encrypted. Creating unencrypted copy from an encrypted snapshot is not supported.
	status code: 400, request id: 4b8a7831-4909-4707-84c4-1535b0a8f17d

==> Builds finished but no artifacts were created.

I also tried to hard code the possible regions but we do not always build to all regions;
packer build -var aws_region='us-west-2' -var copy_to='us-west-1,eu-central-1' dockerhost.json

I am using a user var to list the regions
   "ami_regions": "{{user `copy_to`}}",
    "ami_regions": "{{user `copy_to`}}",
    "region_kms_key_ids": {
      "eu-central-1": "alias/aws/ebs",
      "eu-east-1": "alias/aws/ebs",
      "sa-east-1": "alias/aws/ebs",
      "us-east-1": "alias/aws/ebs",
      "us-east-2": "alias/aws/ebs",
      "us-west-1": "alias/aws/ebs",
      "us-west-1": "alias/aws/ebs"
    },

I can not hardcode region_kms_key_ids list, if the list does not match aim_regions list one gets the following error.
amazon-ebs output will be in this color.

6 error(s) occurred:

* Region sa-east-1 is in region_kms_key_ids but not in ami_regions
* Region us-east-1 is in region_kms_key_ids but not in ami_regions
* Region us-east-2 is in region_kms_key_ids but not in ami_regions
* Region eu-central-1 is in region_kms_key_ids but not in ami_regions
* Region eu-east-1 is in region_kms_key_ids but not in ami_regions
* Region us-west-2 is in ami_regions but not in region_kms_key_ids
how can I var the  region_kms_key_ids to match the ami_regions based on user input. I have tried a few variation but no luck.

**Comment by frank3427** [comment]
packer 1.3 and 1.4 same issue
host ubuntu 18.09
I am using the following packer file; it is failing on the last function of copying to other regions.
copying encrypted AIM not supported. I would think that it would copy first then encrypt.
any help would be greatly appreciated.

Frank
 
{
  "_comment": "To create a new AMI in us-west-2 run:",
  "_comment": "  packer build -var aws_region='us-west-2' dockerhost.json",
  "_comment": "To create an AMI and copy to one or more regions, run:",
  "_comment": "  packer build -var aws_region='us-west-2' -var copy_to='us-west-1,eu-central-1' dockerhost.json",
  "variables": {
    "aws_region": "",
    "copy_to": "",
    "aws_vpc_id": "",
    "aws_subnet_id": "",
    "instance_type": "m3.medium",
    "version": "0.0.3"
  },
  "builders": [{
    "type": "amazon-ebs",
    "vpc_id": "{{user `aws_vpc_id`}}",
    "subnet_id": "{{user `aws_subnet_id`}}",
    "region": "{{user `aws_region`}}",
    "ami_regions": "{{user `copy_to`}}",
    "source_ami_filter": {
      "filters": {
        "virtualization-type": "hvm",
        "name": "CentOS Linux 7*",
        "state": "available",
        "root-device-type": "ebs"
      },
      "owners": [ "679593333241" ],
      "most_recent": true
    },
    "user_data_file": "./scripts/disable_requiretty.sh",
    "instance_type": "{{user `instance_type`}}",
    "ssh_username": "centos",
    "ami_name": "dockerhost {{timestamp}}",
    "encrypt_boot": true,
    "ena_support": true,
    "tags": {
      "Owner": "arrayent",
      "Version": "{{user `version`}}",
      "Environment": "packer build"
    }
  }],
  "provisioners": [{
    "type": "ansible",
    "user": "centos",
    "extra_arguments": "-vvv",
    "pause_before": "10s",
    "sftp_command": "/usr/libexec/openssh/sftp-server",
    "playbook_file": "../playbooks/packer/play.yml"
  }]
}

==> amazon-ebs: Stopping the source instance...
    amazon-ebs: Stopping instance, attempt 1
==> amazon-ebs: Waiting for the instance to stop...
==> amazon-ebs: Enabling Enhanced Networking (ENA)...
==> amazon-ebs: Creating unencrypted AMI FwOBiwF from instance i-0f3f4ac15c6b6cbc5
    amazon-ebs: AMI: ami-0f75316b152634e4f
==> amazon-ebs: Waiting for AMI to become ready...
==> amazon-ebs: Creating Encrypted AMI Copy
==> amazon-ebs: Copying AMI: us-east-2(ami-0f75316b152634e4f)
==> amazon-ebs: Waiting for AMI copy to become ready...
==> amazon-ebs: Deregistering unencrypted AMI
==> amazon-ebs: Deleting unencrypted snapshots
    amazon-ebs: Deleting Snapshot ID: snap-00cfa506fcaa0d4ee
==> amazon-ebs: Copying AMI (ami-0419bfd39943f48db) to other regions...
    amazon-ebs: Copying to: us-west-1
    amazon-ebs: Copying to: us-west-2
    amazon-ebs: Copying to: us-east-1
    amazon-ebs: Waiting for all copies to complete...
==> amazon-ebs: 3 error(s) occurred:
==> amazon-ebs: 
==> amazon-ebs: * Error Copying AMI (ami-0419bfd39943f48db) to region (us-east-1): InvalidRequest: Snapshot snap-05657965eb9352840 is encrypted. Creating unencrypted copy from an encrypted snapshot is not supported.
==> amazon-ebs: 	status code: 400, request id: 150f7ab3-6001-48cd-a768-f604952bf43b
==> amazon-ebs: * Error Copying AMI (ami-0419bfd39943f48db) to region (us-west-1): InvalidRequest: Snapshot snap-05657965eb9352840 is encrypted. Creating unencrypted copy from an encrypted snapshot is not supported.
==> amazon-ebs: 	status code: 400, request id: bffa5254-8dd2-4b7d-b826-09ac26eb787d
==> amazon-ebs: * Error Copying AMI (ami-0419bfd39943f48db) to region (us-west-2): InvalidRequest: Snapshot snap-05657965eb9352840 is encrypted. Creating unencrypted copy from an encrypted snapshot is not supported.
==> amazon-ebs: 	status code: 400, request id: 4b8a7831-4909-4707-84c4-1535b0a8f17d
==> amazon-ebs: Deregistering the AMI because cancellation or error...
==> amazon-ebs: Deregistering the AMI because cancellation or error...
==> amazon-ebs: Error deregistering AMI, may still be around: InvalidAMIID.Unavailable: The image ID 'ami-0f75316b152634e4f' is no longer available
==> amazon-ebs: 	status code: 400, request id: b83c1a0b-c407-492d-8793-8342220f1735
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Cleaning up any extra volumes...
==> amazon-ebs: Destroying volume (vol-0df7658d7627c001f)...
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: 3 error(s) occurred:

* Error Copying AMI (ami-0419bfd39943f48db) to region (us-east-1): InvalidRequest: Snapshot snap-05657965eb9352840 is encrypted. Creating unencrypted copy from an encrypted snapshot is not supported.
	status code: 400, request id: 150f7ab3-6001-48cd-a768-f604952bf43b
* Error Copying AMI (ami-0419bfd39943f48db) to region (us-west-1): InvalidRequest: Snapshot snap-05657965eb9352840 is encrypted. Creating unencrypted copy from an encrypted snapshot is not supported.
	status code: 400, request id: bffa5254-8dd2-4b7d-b826-09ac26eb787d
* Error Copying AMI (ami-0419bfd39943f48db) to region (us-west-2): InvalidRequest: Snapshot snap-05657965eb9352840 is encrypted. Creating unencrypted copy from an encrypted snapshot is not supported.
	status code: 400, request id: 4b8a7831-4909-4707-84c4-1535b0a8f17d

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: 3 error(s) occurred:

* Error Copying AMI (ami-0419bfd39943f48db) to region (us-east-1): InvalidRequest: Snapshot snap-05657965eb9352840 is encrypted. Creating unencrypted copy from an encrypted snapshot is not supported.
	status code: 400, request id: 150f7ab3-6001-48cd-a768-f604952bf43b
* Error Copying AMI (ami-0419bfd39943f48db) to region (us-west-1): InvalidRequest: Snapshot snap-05657965eb9352840 is encrypted. Creating unencrypted copy from an encrypted snapshot is not supported.
	status code: 400, request id: bffa5254-8dd2-4b7d-b826-09ac26eb787d
* Error Copying AMI (ami-0419bfd39943f48db) to region (us-west-2): InvalidRequest: Snapshot snap-05657965eb9352840 is encrypted. Creating unencrypted copy from an encrypted snapshot is not supported.
	status code: 400, request id: 4b8a7831-4909-4707-84c4-1535b0a8f17d

==> Builds finished but no artifacts were created.

I also tried to hard code the possible regions but we do not always build to all regions;
packer build -var aws_region='us-west-2' -var copy_to='us-west-1,eu-central-1' dockerhost.json

I am using a user var to list the regions
   "ami_regions": "{{user `copy_to`}}",
    "ami_regions": "{{user `copy_to`}}",
    "region_kms_key_ids": {
      "eu-central-1": "alias/aws/ebs",
      "eu-east-1": "alias/aws/ebs",
      "sa-east-1": "alias/aws/ebs",
      "us-east-1": "alias/aws/ebs",
      "us-east-2": "alias/aws/ebs",
      "us-west-1": "alias/aws/ebs",
      "us-west-1": "alias/aws/ebs"
    },

I can not hardcode region_kms_key_ids list, if the list does not match aim_regions list one gets the following error.
amazon-ebs output will be in this color.

6 error(s) occurred:

* Region sa-east-1 is in region_kms_key_ids but not in ami_regions
* Region us-east-1 is in region_kms_key_ids but not in ami_regions
* Region us-east-2 is in region_kms_key_ids but not in ami_regions
* Region eu-central-1 is in region_kms_key_ids but not in ami_regions
* Region eu-east-1 is in region_kms_key_ids but not in ami_regions
* Region us-west-2 is in ami_regions but not in region_kms_key_ids
how can I var the  region_kms_key_ids to match the ami_regions based on user input. I have tried a few variation but no luck.

**Comment by SwampDragons** [comment]
Note to self: this could be caused by https://github.com/hashicorp/packer/blob/master/builder/amazon/common/step_encrypted_ami.go#L86-L90 being in step_encrypted_ami rather than step_copy... if we move the deletion of unencrypted snapshots to the cleanup that may solve this. I'll look into it on monday.

**Comment by SwampDragons** [comment]
I've created a build of Packer where I've simply swapped the region copy and encryption steps. Can you test it out and lmk if it seems to work for you?

[packer.zip](https://github.com/hashicorp/packer/files/2902159/packer.zip)

**Comment by frank3427** [comment]
Using the original packer json using the new packer, 
==> Builds finished. The artifacts of successful builds are:
--> amazon-ebs: AMIs were created:
us-west-1: ami-04906c62e6bc8f9fd
us-west-2: ami-02ec08be8baa14997

**Comment by SwampDragons** [comment]
And everything seems to have been created properly when you check on Amazon?

**Comment by SwampDragons** [comment]
@frank3427 I'd love if you could test out another build for me; turns out my PR to close this conflicted with another PR which I _think_ should have solved this for you but I'd like to make sure that when it's released it doesn't break something we thought we already fixed:

[packer.zip](https://github.com/hashicorp/packer/files/2920888/packer.zip)

**Comment by frank3427** [comment]
I will test tonight

**Comment by frank3427** [comment]
I ran the new versions and it seems to be running as expected.
==> amazon-ebs: Stopping the source instance...
    amazon-ebs: Stopping instance, attempt 1
==> amazon-ebs: Waiting for the instance to stop...
==> amazon-ebs: Enabling Enhanced Networking (ENA)...
==> amazon-ebs: Creating unencrypted AMI ddh9NUe from instance
i-09e94cf9910cdde2d
    amazon-ebs: AMI: ami-0e74ad21d884c3269
==> amazon-ebs: Waiting for AMI to become ready...
==> amazon-ebs: Copying AMI (ami-0e74ad21d884c3269) to other regions...
    amazon-ebs: Copying to: us-west-1
    amazon-ebs: Waiting for all copies to complete...
==> amazon-ebs: Creating Encrypted AMI Copy
==> amazon-ebs: Copying AMI: us-west-2(ami-0e74ad21d884c3269)
==> amazon-ebs: Waiting for AMI copy to become ready...
==> amazon-ebs: Deregistering unencrypted AMI
==> amazon-ebs: Deleting unencrypted snapshots
    amazon-ebs: Deleting Snapshot ID: snap-0889b45289c6a47dc
==> amazon-ebs: Adding tags to AMI (ami-020061a67f077967f)...
==> amazon-ebs: Tagging snapshot: snap-0ddd7800e565dc633
==> amazon-ebs: Creating AMI tags
    amazon-ebs: Adding tag: "Owner": "xxx"
    amazon-ebs: Adding tag: "Version": "0.0.3"
    amazon-ebs: Adding tag: "Environment": "packer build"
==> amazon-ebs: Creating snapshot tags
==> amazon-ebs: Adding tags to AMI (ami-05058c74d8316ebcf)...
==> amazon-ebs: Tagging snapshot: snap-026512f452cd9ba72
==> amazon-ebs: Creating AMI tags
    amazon-ebs: Adding tag: "Owner": "xxx"
    amazon-ebs: Adding tag: "Version": "0.0.3"
    amazon-ebs: Adding tag: "Environment": "packer build"
==> amazon-ebs: Creating snapshot tags
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Cleaning up any extra volumes...
==> amazon-ebs: Destroying volume (vol-08556ca89a3e8fbc2)...
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' finished.

==> Builds finished. The artifacts of successful builds are:
--> amazon-ebs: AMIs were created:
us-west-1: ami-05058c74d8316ebcf
us-west-2: ami-020061a67f077967f
