### ISSUE TITLE
template validation fails when instance_type is a user variable

### ISSUE THREAD

**Issue by schmiddy** [hashicorp/packer#7318]
* Packer version: 1.3.4
* Host Mac OS 64-bit
## Problem
`packer validate` fails if one specifies the `instance_type` as a user variable. For a small example, take [this example template](https://www.packer.io/intro/getting-started/build-image.html) and make the `instance_type` be a user variable, [like this](https://gist.github.com/schmiddy/af31feb84ac088c73f2c37c13da228e7).

`packer validate` will then fail with:

```
2019/02/16 15:37:05 Preparing build: amazon-ebs
2019/02/16 15:37:05 Build 'amazon-ebs' prepare failure: 1 error(s) occurred:

* An instance_type must be specified
2019/02/16 15:37:05 ui error: Template validation failed. Errors are shown below.
2019/02/16 15:37:05 ui error: Errors validating build 'amazon-ebs'. 1 error(s) occurred:

* An instance_type must be specified
2019/02/16 15:37:05 [INFO] (telemetry) Finalizing.
Template validation failed. Errors are shown below.

Errors validating build 'amazon-ebs'. 1 error(s) occurred:

* An instance_type must be specified
```

However, a `packer build` of this template with the `instance_type` passed in: `packer build ... -var 'instance_type=t3.large'` works just fine.

**Comment by rickard-von-essen** [comment]
Does it fail if you pass the same var to validate?

**Comment by schmiddy** [comment]
Yes it does @rickard-von-essen - thanks for the tip, didn't notice that was possible! This solves my actual complaint, not sure if there is plausibly still a bug here (should `packer validate` figure this out on its own?), but feel free to close this ticket.

**Comment by SwampDragons** [comment]
Thanks; I think the current behavior is correct.
