### ISSUE TITLE
googlecompute: Possible to build instance in different project to where image is created?

### ISSUE THREAD

**Issue by dave-pollock** [hashicorp/packer#7331]
I'm attempting to run an instance in an isolated GCP project (project-2), then use that instance to create an image in the production project (project-1). I've set project_id as the production project where I want the image to be created, and network_project_id to the isolated project where the network has been created. Is this a valid approach? 

When I run packer I get the error `Build 'googlecompute' errored: Error creating instance: googleapi: Error 400: Invalid value for field 'resource.networkInterfaces[0]': '{  "network": "projects/project-2/global/networks/project-2-network",  "accessConfig": [{    "type": "ONE_TO_...'. Cross-project references for this resource are not allowed., invalid`.

It seems as if the google API is being asked to create an instance in project-1, but attach a network interface which exists in project-2?

Packer version: 1.3.4

Host platform: Ubuntu 18.04.1 LTS

Example Packer config and logs: https://gist.github.com/dave-pollock/309c7e7165b00f9265532bf2c3058418

Thanks!

**Comment by rickard-von-essen** [comment]
No you can't do what you are trying. You have to create the image in `project-2` and give `project-1` access to `project-2`'s images. See [Sharing Images Across Projects](https://cloud.google.com/compute/docs/images/sharing-images-across-projects).
