### ISSUE TITLE
QEMU Xen accelerator: failed to get HVM_PARAM_IOREQ_PFN

### ISSUE THREAD

**Issue by Wenzel** [hashicorp/packer#7349]
When building a qemu template with `xen` accelerator, packer fails with the error `failed to get HVM_PARAM_IOREQ_PFN`

- Packer version: `v1.3.3`
- Host platform: Debian Stretch
- Debug log output:

~~~
Qemu stderr: failed to get HVM_PARAM_IOREQ_PFN
Qemu stderr: qemu-system-x86_64: failed to get ioreq server info: error 22 handle=0x55606c240170
Qemu stderr: qemu-system-x86_64: xen hardware virtual machine initialisation failed
~~~

Xen has been installed using Debian package: [xen-system-amd64](https://packages.debian.org/stretch/xen-system-amd64) `4.8.5`

Template:
https://github.com/Wenzel/bug_packer_ansible/blob/master/windows_10.json
(set `xen` in the `accelerator` field)
  
Thanks for your help !

**Comment by laughing-penguins** [comment]
@azr I'm also encountering this issue. I recognize that QEMU is a community plugin but has anyone been able to build an image successfully while using the XEN accelerator? Was this tested before reporting the ability to build a xen image?

**Comment by Wenzel** [comment]
I spoke with the Xen community, and this feature is broken since Xen 4.1.

Only the xl toolstack can setup a vm today, qemu by itself is not enough, as far as i understood.

**Comment by laughing-penguins** [comment]
@Wenzel Thanks for the update. Perhaps packer should remove mention of being able to use Qemu to build a xen vm.
