### ISSUE TITLE
Feature Request: Create Cryptographically Signed Vagrant Boxes

### ISSUE THREAD

**Issue by ladar** [hashicorp/packer#7354]
I've been meaning to propose this for awhile. Here goes the short version:

Could `packer` add support for embedding a `signature.asc` or something similar inside Vagrant box files it generates? 

There are lots of details regarding how such a feature would work, but the first, and most pressing question, is whether adding a signature file break any of the commonly used providers? If yes, that needs to be fixed immediately, and this request postponed.

If not, could this feature be added to the roadmap? If so, I'll add details on how it could work, and then use it sign the `robox` images. Obviously getting `packer` to support cryptographic signing is just the first step. The idea is that eventually `vagrant` would add support for checking/using these signature files when it grabs boxes from publishers who support it.

P.S. While I can't tackle this feature myself, I think it would be perfect for tackling at a hackathon.

**Comment by SwampDragons** [comment]
My gut instinct is that this is really a Vagrant feature request -- if they did cryptographic signing, then we'd be motivated to support it; but as it is I'm not sure it's worth us implementing first. Have you opened an issue with the Vagrant team?

**Comment by ladar** [comment]
Chicken. Meet my friend, Mr. Egg.

No I haven't opened an issue on the `vagrant` repo _yet_ (it's on the list). But my take was that without any boxes to actually verify, how (and why) would `vagrant` implement it? Hence my thinking that `packer` should implement it first (assuming signatures files doesn't cause the provider plugins to reject the tarballs), so there are signed boxes for `vagrant` to consume (and test against).

If `packer` adds support, I can publish signed Roboxes, which `vagrant` could then use to implement the verification/management features.

The dual nature of the feature was part of the reason I suggested a hackathon... as both teams could collaborate on implementing a feature like this at the same time. And of course I could help as well.

**Comment by SwampDragons** [comment]
@chrisroberts could use your input on this.

**Comment by chrisroberts** [comment]
:wave: This topic has come up previously publicly (hashicorp/vagrant#9617) as well as internally. I see this definitely being a feature that would be introduced on the Vagrant side and then added to packer once support was available. We have had discussions around what it would look like not only within Vagrant, but on Vagrant Cloud as well. At this point, however, it has mostly just been some brainstorming with nothing concrete determined around implementation details, nor any kind of roadmap scheduling.

@ladar If you want to add information to the Vagrant issue around what kind of functionality you are thinking about (what kind of expectations you would have of Vagrant, behaviors, etc) we can pick it back up again internally and put a proposal together. 

This is a feature that I do think would be nice to have, but so far there hasn't been a lot of interest in it which has kept it pretty low on our priority list.

**Comment by SwampDragons** [comment]
I'm going to close this since it's moot until #9617 is closed; Ladar, if you want yo add your details to #9617 that's probably the right place to track them.
