### ISSUE TITLE
hcloud builder: option "rescue": "freebsd64" is broken

### ISSUE THREAD

**Issue by climann** [hashicorp/packer#7356]
**Overview**

Reproducible build failure with hcloud builder and `rescue` option set to `freebsd64`.

**Result:** Build fails with error.

`==> hcloud: Error enabling rescue mode: FreeBSD rescue system does not support SSH keys (invalid_input)`

See [log](https://gist.github.com/climann/584014c34ddac958591050b9a52a5cd9) for details.

**Expected result:** 

See [packer documentation](https://www.packer.io/docs/builders/hetzner-cloud.html)
>-   `rescue` (string) - Enable and boot in to the specified rescue system. This
>    enables simple installation of custom operating systems. `linux64`
>    `linux32` or `freebsd64`

Edit: This said "Build should complete without error". 
The provided template should actually fail to build, because no system is installed.
I don't have a good way to test this, so I can't provide the full error message.
My guess is a ssh timeout error later in the process.
The important part: packer should be able to enable rescue mode and connect.

**Steps to reproduce**

```
{
  "builders": [{
    "type": "hcloud",
    "token": "TOKEN"
    "image": "ubuntu-18.04",
    "location": "nbg1",
    "server_type": "cx11",
    "ssh_username": "root",
    "rescue": "freebsd64"
  }]
}
```

**Solution**

[Hetzner Cloud API](https://docs.hetzner.cloud/) can't inject ssh keys into the freebsd64 ([mfsBSD](https://mfsbsd.vx.sk/) 11.2) rescue image.
I assume this also applies to [hetznercloud/hcloud-go](https://github.com/hetznercloud/hcloud-go) and [hetznercloud/cli](https://github.com/hetznercloud/cli).
The API returns a temporary password if no ssh public key is provided.

Packer should enable rescue mode without ssh public key and use the temporary password if `rescue` is set to `freebsd64`.

I think there are two ways the builder could handle this:

Option 1:
- ignore communicator variables (`ssh_username`,`ssh_password`, ...)
- temporarily use `"ssh_username": "root"`
- call client.Server.EnableRescue without ssh public key
https://github.com/hashicorp/packer/blob/0e8afa37d5623ab5d262ef0b0eacaa45dba18206/builder/hcloud/step_create_server.go#L133-L136
- use the temporary password returned by the API
- if rescue mode is disabled (e.g. provisioner reboot), use communicator variables (`ssh_username`,`ssh_password`, ...)

This is complex and transparent to the user, but allows for os installation and provisioning in a single builder. It would work analogous to `linux32` and `linux64` templates with ssh public key injection.

Option 2: 
- call client.Server.EnableRescue without ssh public key by default
https://github.com/hashicorp/packer/blob/0e8afa37d5623ab5d262ef0b0eacaa45dba18206/builder/hcloud/step_create_server.go#L133-L136
- use communicator variables (`ssh_username`,`ssh_private_key_file`, ...) to override
 
This is simpler, but `freebsd64` builds would need two builders.
The first builder could install the os, configure ssh and create an image.
The second builder (with different ssh communicator variables) could use and provision the image from builder 1. This would create a "special case" for `freebsd64` templates.

This is my first time opening an issue. Please let me know if you need anything else.

**Comment by SwampDragons** [comment]
cc @LKaemmerling

**Comment by LKaemmerling** [comment]
First of all thank you @climann for the detailed bug report!

Just for information: I'm working on a solution for this.

**Comment by climann** [comment]
Awesome! Let me know if I can help!
