### ISSUE TITLE
Allow building AMIs for ARM64 (aarch64)

### ISSUE THREAD

**Issue by dave-tucker** [hashicorp/packer#7358]
In Nov 2018 Amazon launched A1 instance types that are based on the ARM64 (aarch64) architecture.
I would like to use Packer to create AMIs for this instance type.

I've been testing using A1 instances with the EBS Surrogate builder.
This works well until the AMI is registered at which point it's architecture is [hard-coded to x86_64](.https://github.com/hashicorp/packer/blob/master/builder/amazon/ebssurrogate/step_register_ami.go#L36)

I would like to be able to set the `ami_architecture` in my Packer configuration so that I can use theses AMIs. As an added bonus the Architecture of the Source AMI could be used for this to work out of the box.

**Comment by SwampDragons** [comment]
I have a patch that'll add this feature, linked above. If you'd like to test it out, let me know your architecture and I can build you a binary.

**Comment by tomalok** [comment]
That’d be awesome, thanks!  I’m on macOS (so Darwin/x86_64 for the packer binary arch...)

iSent from my iPhone

**Comment by SwampDragons** [comment]
@tomalok here you go!  Same story as last time -- it's actually a .7z file but github won't let me upload that. [packer.zip](https://github.com/hashicorp/packer/files/3158412/packer.zip).  I'm looking at getting an s3 bucket to toss these binaries into so that I don't need to jump through these hoops.

**Comment by tomalok** [comment]
@SwampDragons -- Works as advertised!  (At least now I know I have some more GRUB EFI work to do in order to get that AMI bootable...)
