### ISSUE TITLE
Missing tag for "v1.3.5"

### ISSUE THREAD

**Issue by ad-m** [hashicorp/packer#7363]
Hello,

At https://www.packer.io/downloads.html there is link to https://github.com/hashicorp/packer/blob/v1.3.5/CHANGELOG.md . That link is not valid due missing tag "v1.3.5" in that repository.

According to https://github.com/hashicorp/packer/blob/master/CHANGELOG.md v1.3.5 was released at February 28, 2019 .

Could anybody add / push valid tag for "v1.3.5" version?

Greetings,

**Comment by azr** [comment]
Hey @ad-m, thanks for the heads up. I just tagged 542cb1d872b4fbba57f34ebb5913a266017a38df with v1.3.5
