### ISSUE TITLE
Make Inspec provisioner work better for Windows builds

### ISSUE THREAD

**Issue by StefanScherer** [hashicorp/packer#7364]
Congratulations to the new Inspec provisioner and thanks @xinau for the PR #7180. I walked through several blog posts yesterday to use Serverspec, then Inspec plugins, then I found that Packer 1.3.5 now has it built-in. 🎉 

I immediately tried it out for some of my Windows Packer templates and struggled here.

The provisioner spins up a small SSH proxy, but I then struggled with Inspec that it first tried to run several Unix commands
- [`uname -s`](https://gist.github.com/StefanScherer/c325ae2fb66c87bd1b19e501bbb55150#file-packer-log-L316)
- [`test -f /usr/bin/FastCli`](https://gist.github.com/StefanScherer/c325ae2fb66c87bd1b19e501bbb55150#file-packer-log-L327)
- [`show version | json`](https://gist.github.com/StefanScherer/c325ae2fb66c87bd1b19e501bbb55150#file-packer-log-L343)
- [`show version`](https://gist.github.com/StefanScherer/c325ae2fb66c87bd1b19e501bbb55150#file-packer-log-L360)
- [`version`](https://gist.github.com/StefanScherer/c325ae2fb66c87bd1b19e501bbb55150#file-packer-log-L376)
And then gives up with [Sorry, we are unable to detect your platform](https://gist.github.com/StefanScherer/c325ae2fb66c87bd1b19e501bbb55150#file-packer-log-L390)

Describe the problem and include the following information:

- Packer version from `packer version`
Packer v1.3.5
- Host platform
macOS 10.14.3
- Debug log output from `PACKER_LOG=1 packer build template.json`.
https://gist.github.com/StefanScherer/c325ae2fb66c87bd1b19e501bbb55150#file-packer-log
- The _simplest example template and scripts_ needed to reproduce the bug.
https://gist.github.com/StefanScherer/c325ae2fb66c87bd1b19e501bbb55150#file-windows_10_test-json

Questions:
- Does anybody know how I can convince Inspec that this SSH proxy is in fact a Windows target? I tried several things in the inspec.yml, I'm not an expert of Inspec, but it seems that the problem is more the fact that a SSH connection to 127.0.0.1 is used from what I can see in the Inspec ruby code.
- What has to be changed in the Inspec provisioner to make it Windows-VM friendly?

I worked around the problem by using the direct WinRM connection to the Windows Packer VM:

```json
    {
      "type": "inspec",
      "profile": "my_win10",
      "backend": "winrm",
      "host": "192.168.65.138",
      "user": "vagrant",
      "extra_arguments": [ "--user", "vagrant", "--password", "vagrant" ]
    }
```

https://gist.github.com/StefanScherer/c325ae2fb66c87bd1b19e501bbb55150#file-windows_10_test_workaround-json-L42-L49

These are all information which I think can be get from the communicator. I use a vmware-vmx builder for that tests to have a fast feedback loop.

**Comment by StefanScherer** [comment]
Just for reference here is a part of a packer.log with an successful Inspec test that complains about a missing file as the provision script didn't install it correctly and also didn't fail.

https://gist.github.com/StefanScherer/c325ae2fb66c87bd1b19e501bbb55150#file-successful-inspec-windows-log

So Inspec really helps also for Windows builds 🎉

**Comment by e-mow** [comment]
I second this request and have a question about provisioners and how they are allowed to access the host being built.

Are provisioners allowed to access the IP of the host that is being built or does it have to use the communicator that is set in the builder? I noticed that Ansible is not allowed to talk directly to the host IP and has to use the communicator. It doesn't look like Inspec would support that currently.

If the provisioner is allowed to directly talk to the host IP then we could get the IP from Packer along with the credentials from the communicator and could set them based on the backend of winrm being set.

**Comment by StefanScherer** [comment]
OK, or we make the Inspec train Ruby gem a little bit better aware of SSH'ing into Windows machines.

I found that when I change `plat.family('windows').in_family('os')` in line 27 https://github.com/inspec/train/blob/a585b0a385e34addfec2d97eb450d6db9bd2b386/lib/train/platforms/detect/specifications/os.rb#L27  to call the `detect_windows` function, it also checks `cmd /c ver` through the SSH proxy and gets tunneled into the WinRM communicator.

```ruby
      plat.family('windows').in_family('os')
          .detect {
            # Can't return from a `proc` thus the `is_windows` shenanigans
            is_windows = false
            is_windows = true if winrm?

            if @backend.class.to_s == 'Train::Transports::Local::Connection'
              is_windows = true if ruby_host_os(/mswin|mingw32|windows/)
            end

            if detect_windows == true
              is_windows = true
            end

            is_windows
          }
```

Then it would just work as it is.

**Comment by StefanScherer** [comment]
I've opened https://github.com/inspec/train/pull/416 to get feedback from the Inspec maintainers about that enhancement.

**Comment by e-mow** [comment]
Awesome, I had actually looked at inspec last night as well however it was the first time I have ever looked at Ruby and I didn't get that far. If inspec accepts your change that would be great.

**Comment by StefanScherer** [comment]
Looks like the current release of InSpec 4.4.x has inspec/train 2.1.0 included which contains the relevant enhancement to support Windows targets.
