### ISSUE TITLE
Packer build in debug mode isn't waiting for me to press Enter Key

### ISSUE THREAD

**Issue by gulzaman-k** [hashicorp/packer#7374]
### **-debug command not working as expected** 
When i run packer build command with -debug option it show's the message 
`Debug mode enabled. Builds will not be parallelized` but console do not ask to press enter to move to next step. on each step ` Press enter to continue. ==> amazon-ebs:` appear and build process keep on running.

**Comment by ad-m** [comment]
@gulzaman-k , could update update issue title to match issue description?

**Comment by azr** [comment]
Hello there; this looks like this is a duplicate from #7299 which is currently being investigated in #7352. I will close this duplicate issue, let's carry on in the existing one(s).
