### ISSUE TITLE
Insufficient error handling upon ansible build errors: Error code not set correctly by packer

### ISSUE THREAD

**Issue by loibpet** [hashicorp/packer#7384]
**packer -v: 1.3.4**
Provisioner: ansible
Working on RedHat 7.6

Integrating packer into a CI/CD pipeline requires correct error handling, i.e. any errors during a packer build need to be caught to stop the CI/CD process. That fails with ansible.

**Setup:** provoke error in ansible with
```
- name: Provoke error
  shell: "exit 1"
```

The ansible error is identified correctly, the job stops and the error is reported:
```
    RedHat-7.6 ami bakery 2019-03-07T10:15:44Z: TASK [common : Provoke error] ****************************************************
    RedHat-7.6 ami bakery 2019-03-07T10:15:44Z: fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": "exit 1", "delta": "0:00:00.002752", "end": "2019-03-07 11:17:45.575091", "msg": "non-zero return code", "rc": 1, "start": "2019-03-07 11:17:45.572339", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
    RedHat-7.6 ami bakery 2019-03-07T10:15:44Z: PLAY RECAP *********************************************************************
    RedHat-7.6 ami bakery 2019-03-07T10:15:44Z: 127.0.0.1                  : ok=18   changed=11   unreachable=0    failed=1
    RedHat-7.6 ami bakery 2019-03-07T10:15:44Z:
==> RedHat-7.6 ami bakery 2019-03-07T10:15:44Z: Terminating the source AWS instance...
==> RedHat-7.6 ami bakery 2019-03-07T10:15:44Z: Cleaning up any extra volumes...
==> RedHat-7.6 ami bakery 2019-03-07T10:15:44Z: No volumes to clean up, skipping
==> RedHat-7.6 ami bakery 2019-03-07T10:15:44Z: Deleting temporary security group...
==> RedHat-7.6 ami bakery 2019-03-07T10:15:44Z: Deleting temporary keypair...
Build 'RedHat-7.6 ami bakery 2019-03-07T10:15:44Z' errored: Error executing Ansible: Non-zero exit status: 2

==> Some builds didn't complete successfully and had errors:
--> RedHat-7.6 ami bakery 2019-03-07T10:15:44Z: Error executing Ansible: Non-zero exit status: 2

==> Builds finished but no artifacts were created.
```

However, packer does not indicate any error to the calling process/environment:

```
echo $?
0
```

**This is wrong, as the code 0 indicates correct and error free processing. Any code other than 0 would be required!**

**Comment by SwampDragons** [comment]
I can't reproduce; on my system Packer exits 1. Are you sure that the script you're using to call Packer in your CI environment isn't eating the exit code?  For example, another user recently discovered that if you're piping Packer's output through tee, you could be seeing tee's exit code instead. (https://github.com/hashicorp/packer/issues/7382)

**Comment by loibpet** [comment]
Problem has been solved. This was indeed the reason. Sorry for that.
