### ISSUE TITLE
Packer For Azure Image Build

### ISSUE THREAD

**Issue by blorette** [hashicorp/packer#7389]
Using Packer to build Azure Managed Images. I have found that for Azure the ARM templates used are complied. Also, specific to the Windows Workflow, It requires Key Vault which is also built via a pre defined template. 

Would like to be able to do either of the following:

Provide an already built Key Vault and configured Key Vault to be used to store and pull the certificate. This is to keep from provisioning a Key Vault with a Public End Point (Security Consideration). It will also, keep communication within a specific subnet. 

A further consideration would be to allow the use of our own ARM templates to build the image off of. A current thought is to provide the ARM template with any needed extensions or configurations. This would provide a good base line to start from. Part of that consideration is as we go into our CI/CD pipeline, the base image used would be the previous image built. Certain customization with-in the template may speed some of the build process.

**Comment by riezebosch** [comment]
> Part of that consideration is as we go into our CI/CD pipeline, the base image used would be the previous image built. Certain customization with-in the template may speed some of the build process.

This part is a bit unclear to me because I don't see the relation with a custom provided ARM template to be used. It already is possible to build one managed image in a build pipeline and base a second build on that image. I fixed this by adding the build pipeline name and build id (from Azure DevOps) as azure tags to the output and query that in the subsequent build.

**Comment by blorette** [comment]
It's simply to say that some operations for image prep are faster via
template and template extensions and others via our scripts and
configurations.

If we know that as a base, our image will always contain x package which
can be configure as an native extension, then let the template handle that.
And our build script can handle other items.

**Comment by paulmey** [comment]
> If we know that as a base, our image will always contain x package which
> can be configure as an native extension, then let the template handle that.

Can you give an example of such an extension and/or package?

**Comment by blorette** [comment]
The VSTS agent as one, or DataDog. Or disk encryption as to ensure that the
image is provisioned with encrypted disks. Or a custom script as to run
specific configurations. Its about allowing more seamless integration
between the platforms.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by riezebosch** [comment]
My idea was to replace the custom mapping from the packer template with a one-on-one copy of the (used) ARM template which would indeed also enable the use of existing features as of being future compatible and less translation from the ARM capabilities to the azure builder configuration. I'm not quite sure how for example the AWS builder deals with this?

**Comment by blorette** [comment]
Would this translate to the key vault portion as well?

It would be nice, as my image build team would not have to learn arm
templates.

**Comment by riezebosch** [comment]
> The VSTS agent as one, or DataDog. Or disk encryption as to ensure that the image is provisioned with encrypted disks. Or a custom script as to run specific configurations. Its about allowing more seamless integration between the platforms.

I'm also building the Azure Pipeline Image Generation (fka VSTS) a lot and don't see how you need an extension for that during provisioning. You end up with a managed image or VHD as the output of the packer build and spin up VM's from that where you have all the freedom to use your own ARM templates.

**Comment by riezebosch** [comment]
> Would this translate to the key vault portion as well? It would be nice, as my image build team would not have to learn arm templates.

Mind that I'm only a contributor, I don't know anything about the future plans for the Packer Azure Builder. It is a wild idea I have because to me the current builder seems too complicated.

**Comment by paulmey** [comment]
I'm checking whether this scenario is even supported. Extensions may or may not work after deprovisioning/generalizing the image for capture.

**Comment by paulmey** [comment]
@blorette I've gotten back confirmation that this scenario (install extensions, capture image, redeploy) is currently not supported. If this changes, we can reconsider this request.

**Comment by blorette** [comment]
That's not even what this request is for.
