### ISSUE TITLE
Error Copying AMI (ami-id) to region (us-east-1): InvalidRequest:

### ISSUE THREAD

**Issue by ff-agrawal** [hashicorp/packer#7393]
Error Copying AMI (ami-id) to region (us-east-1): InvalidRequest: Snapshot snap-id is encrypted. Creating unencrypted copy from an encrypted snapshot is not supported. I looked into the workaround mentioned here
https://github.com/hashicorp/packer/issues/6789 but I am still getting the same exception am using 1.3.5 packer version.

Kindly note its not boot volume(snapshot) that is encrypted, its additional volume which has been encrypted in us-east-1 region which I am trying to transfer to eu-central-1 using whatever is the default keys that get attached. When ami with encrypted ebs is shared from one region to another region within the same aws account using aws console without selecting or making any change, automatically new ami gets created with the encrypted snapshot on
<img width="1150" alt="Screen Shot 2019-03-10 at 7 14 04 PM" src="https://user-images.githubusercontent.com/4921154/54089020-45f8ec80-438a-11e9-9ffc-420d0ecfe5fb.png">

**Comment by rickard-von-essen** [comment]
Please supply the information requested in the issue template:
- Packer version (`packer version`)
- Host platform (`uname -a` etc.)
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a [gist](https://gist.github.com).
- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your [gist](https://gist.github.com).

**Comment by ff-agrawal** [comment]
Packer version (packer version) = v 1.3.5
Host platform (uname -a etc.) = Linux 4.14.101-75.76.amzn1.x86_64 #1 SMP Tue Feb 19 18:14:51 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Debug log output from PACKER_LOG=1 packer build template.json.
Please paste this in a gist. https://gist.github.com/ff-agrawal/fc09b6a457c11750c7968afb2c87eec2
The simplest example template and scripts needed to reproduce the bug.
https://gist.github.com/ff-agrawal/fa86d7b7038fb9bc17e41509791b1efb

**Comment by rickard-von-essen** [comment]
Please [gist](https://gist.github.com/) a full debug log from `PACKER_LOG=1 packer build template.json`.

**Comment by ff-agrawal** [comment]
@rickard-von-essen please find debug logs at https://gist.github.com/ff-agrawal/fc09b6a457c11750c7968afb2c87eec2

**Comment by rickard-von-essen** [comment]
Could you _please_ include the _full_ log, from where packer starts to it finish. It includes valuable information for us.

**Comment by ff-agrawal** [comment]
@rickard-von-essen I have updated the logs again hopefully not it has all the info you need
https://gist.github.com/ff-agrawal/fc09b6a457c11750c7968afb2c87eec2

Kindly note I have removed chef converge part logs

**Comment by SwampDragons** [comment]
Have you tried using the v1.4.0-dev binary on https://github.com/hashicorp/packer/pull/6787?  

If not, here's a linux build of the master branch, which should hopefully resolve this. Please let me know if it does so I can close this issue. :)

[packer.zip](https://github.com/hashicorp/packer/files/2953566/packer.zip)

**Comment by SwampDragons** [comment]
Closing for now, but we can reopen if the provided binary doesn't work.

**Comment by hegyre** [comment]
Hello,
Had the same issue and I confirm build from #6787 solves that.

In case it could helps, here's my config now with the #6787 Windows build:
AMI: Centos 1901_01
```
      "source_ami_filter": {
        "filters": {
          "virtualization-type": "hvm",
          "name": "*CentOS Linux 7 x86_64 HVM EBS ENA 1901_01*",
          "root-device-type": "ebs"
        },
        "owners": ["679593333241"],
        "most_recent": true
      },

      "encrypt_boot": true,

      "launch_block_device_mappings": [
        {
          "delete_on_termination": true,
          "device_name": "/dev/sda1",
          "volume_size": 12,
          "volume_type": "gp2"
        }
      ],

      "ami_block_device_mappings": [
        {
          "delete_on_termination": true,
          "device_name": "/dev/sda1",
          "volume_size": 50,
          "volume_type": "gp2"
        }
      ],

```
