### ISSUE TITLE
win 2016 set host-passthrough ?

### ISSUE THREAD

**Issue by meteorlad** [hashicorp/packer#7394]
Describe:

I used packer to install the blue screen of win 2016. Therefore, I conducted debugging through virt-install and found that the "-- CPU host-passthrough" parameter should be added. So how do I use the `" --CPU host-passthrough"` model in packer?

The virt-install complete command：

```Bash
virt-install --name server2016 --memory 4096 --vcpus sockets=1,cores=2,threads=2 --disk device=cdrom,path=/opt/SW_DVD9_Win_Svr_STD_Core_and_DataCtr_Core_2016_64Bit_ChnSimp_-3_MLF_X21-30349.ISO --disk device=cdrom,path=/opt/virtio-win-1.9.6.iso  --disk path=/cloud/images/win2k1611-os.qcow2,size=20,bus=virtio --network bridge=br-a246cb9427d7,model=virtio --noautoconsole --accelerate --hvm --graphics vnc,listen=0.0.0.0,port=20007 --video vga --input tablet,bus=usb --cpu host-passthrough
```

> Key parameter "-- CPU host-passthrough"

Env：

- packer 1.2.5
- CentOS Linux release 7.5.1804 (Core) 
- qemu-kvm 1.5.3

**Comment by SwampDragons** [comment]
You probably need to set it via qemu-args: https://www.packer.io/docs/builders/qemu.html#qemuargs
