### ISSUE TITLE
Floppy disk doesn't removed after Packer interrupted

### ISSUE THREAD

**Issue by nick-korsakov** [hashicorp/packer#7399]
Info:
- Packer version: v1.3.5
- Host platform: Windows 10 x86-64 (1809)
- Debug log: [output](https://gist.github.com/nick-korsakov/a825caab967b0522bc1ee1d75d28b2d2)
- The example: [template](https://gist.github.com/nick-korsakov/998a33ad6062fab6e51f52212fb33813)
- ISO: [TinyCoreLinux](https://distro.ibiblio.org/tinycorelinux/10.x/x86/release/Core-current.iso)

Floppy disk (**not controller**) doesn't removed after Packer interrupted with Ctrl+C. See the tail of the mentioned above log.

Reproduction:
```C
$ packer build template.json
// Let it boot.
// Ctrl+C
$ vboxmanage list floppies
```

**Comment by azr** [comment]
Hi @nick-korsakov, thanks for opening, could you please update your debug output by running packer with `PACKER_LOG=1` set in your env first please ? It worked for me locally ( mac os ).

```bash
$ PACKER_LOG=1 packer build -force file.json
2019-03-13T15:59:16+01:00: ==> virtualbox-iso: Deregistering and deleting VM...
2019/03/13 15:59:16 checkpoint: 2019/03/13 15:59:16 Executing VBoxManage: []string{"unregistervm", "packer-virtualbox-iso-1552489135", "--delete"}
2019/03/13 15:59:16 checkpoint: 2019/03/13 15:59:16 stdout:
2019/03/13 15:59:16 checkpoint: 2019/03/13 15:59:16 stderr: VBoxManage: error: Cannot unregister the machine 'packer-virtualbox-iso-1552489135' while it is locked
2019/03/13 15:59:16 checkpoint: VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap, interface IMachine, callee nsISupports
2019/03/13 15:59:16 checkpoint: VBoxManage: error: Context: "Unregister(CleanupMode_DetachAllReturnHardDisksOnly, ComSafeArrayAsOutParam(aMedia))" at line 157 of file VBoxManageMisc.cpp
2019/03/13 15:59:17 checkpoint: 2019/03/13 15:59:17 Executing VBoxManage: []string{"unregistervm", "packer-virtualbox-iso-1552489135", "--delete"}
2019/03/13 15:59:17 checkpoint: 2019/03/13 15:59:17 stdout:
2019/03/13 15:59:17 checkpoint: 2019/03/13 15:59:17 stderr: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
2019/03/13 15:59:17 checkpoint: 2019/03/13 15:59:17 Deleting floppy disk: /var/folders/3k/2gb5ct4s7cncr52_jh2kz6cw0000gq/T/packer462444275
2019-03-13T15:59:17+01:00: ==> virtualbox-iso: Deleting output directory...
$ vboxmanage list floppies     
                                                 
$
```

**Comment by nick-korsakov** [comment]
> ...could you please update your debug output by running packer with `PACKER_LOG=1` set in your env first please ?...

Done.

P.S.: Debug output was missed due to WSL inability to pass environment variable `PACKER_LOG=1` from Linux to Windows when I ran it as `$ PACKER_LOG=1 packer.exe build template.json`.

**Comment by azr** [comment]
Howdy, thanks for the update, the `os.Remove` probably failed but the error was not being displayed by the code.

Could you please run it again from this pr #7405 ?

Here's a windows binary in case: [packer_windows_amd64.zip](https://github.com/hashicorp/packer/files/2965777/packer_windows_amd64.zip)

**Comment by nick-korsakov** [comment]
> Could you please run it again from this pr #7405 ?

`Ctrl+C` doesn't work on this build and I can't interrupt Packer to reproduce the error.

**Comment by azr** [comment]
Hello @nick-korsakov, ah sorry a recent unrelated change broke this, I am glad we saw this, now it should be better :

[windows_amd64.zip](https://github.com/hashicorp/packer/files/2970706/windows_amd64.zip)

**Comment by nick-korsakov** [comment]
Hello @azr! The [output](https://gist.github.com/nick-korsakov/a825caab967b0522bc1ee1d75d28b2d2) updated.

**Comment by azr** [comment]
Okay, thanks for sharing, after some debugging it seems like the code will try to remove the physical location of the floppy disk and on windows, this doesn't count as an unmount. I'm still on it.

**Comment by azr** [comment]
Hey @nick-korsakov, could you please tell me what's a command to detach the floppy disk that worked for you?

Currently, packer tries to run `vboxmanage "storageattach" $vmName "--storagectl" "Floppy Controller" "--port" "0" "--device" "0" "--medium" "none"

**Comment by nick-korsakov** [comment]
Hey @azr, this command helped me to detach floppy disk from vm but I need it to be deleted.
```cmd
C:\Users\user>vboxmanage storageattach packer-virtualbox-iso-1553184662 --storagectl "Floppy Controller" --port 0 --devi
ce 0 --medium none

C:\Users\user>vboxmanage list floppies
UUID:           e8b6b4b4-32fd-4d2d-80d1-30a32b251e21
State:          inaccessible
Type:           writethrough
Location:       C:\Users\user\AppData\Local\Temp\virtualbox782300642\floppy.vfd
Storage format: RAW
Capacity:       0 MBytes
Encryption:     disabled
```

**Comment by azr** [comment]
And, is the file still present at `C:\Users\user\AppData\Local\Temp\virtualbox782300642\floppy.vfd` ?

**Comment by nick-korsakov** [comment]
> And, is the file still present at `C:\Users\user\AppData\Local\Temp\virtualbox782300642\floppy.vfd` ?

@azr, No. Even "C:\Users\user\AppData\Local\Temp\virtualbox782300642" folder doesn't exists. But floppy still registered (see `vboxmanage list floppies` output above).

**Comment by azr** [comment]
Hey @nick-korsakov, so I could repro on windows but I think packer can't do anything about this.
The floppy is detached from the vm and the file is removed but the `vboxmanage list floppies` will still list that floppy **until windows is restarted**. This tells me the issue _probably_ has something to do with caching on vbox'es side. I'm going to close that issue for now but please feel free to open a PR if you can think of a better solution. Thanks for your time !
