### ISSUE TITLE
salt-masterless no_exit_on_failure has no effect

### ISSUE THREAD

**Issue by markododa** [hashicorp/packer#7401]
Running packer 1.3.5 on archlinux, a packer template that worked a few weeks ago suddenly stopped working, packer catches the error code of salt-call and quits even though i have set no_exit_on_failure to true.
Here is the gist https://gist.github.com/markododa/8fcd3c0f93b312c3c5a828e61d6d1cf8

**Comment by DamianBis** [comment]
I've got the same problem with a Windows AMI i'm creating with packer.
