### ISSUE TITLE
Security_Group_Filter - Selecting multiple unique Security Groups

### ISSUE THREAD

**Issue by dza89** [hashicorp/packer#7402]
Is it possible to select multiple unique security group ids?
For example:

I have two security groups, one for the OS layer and one for the Application layer:

"security_group_filter": {
                "filters": {
                  "tag:Name": "myawesomeOS",
                }
            },
                "filters": {
                  "tag:Name": "myawesomeApp"
            }
          },

When I use two filters the second one seems to overwrite the first one.

**Comment by rickard-von-essen** [comment]
No, but you can just add a new tag `foo:bar` on both of them and search for that.

**Comment by dza89** [comment]
So I have one generic security group and one application specific security group.
So now I can never create multiple sets with the same generic security group, except when i give that generic security group numerous tags (one for each application) 
Correct?

**Comment by rickard-von-essen** [comment]
Yes, or you use (multiple) executions of the  aws cli to generate the list of security groups and pass that as a user variable.
