### ISSUE TITLE
macOS terminal: output gets broken

### ISSUE THREAD

**Issue by stephen-fox** [hashicorp/packer#7406]
# Description
@chrismarget and I noticed that our macOS Terminal output [gets all messed up](https://ibb.co/qjFYrBC) after Control+C'ing a build. This happened after updating our local packer git repos and building the latest ref in GitHub. It's almost like a return does not print a `\n` anymore.

This issue occurs in the latest commit in `master`. It does not occur in any existing packer releases - so you guys might already know about this.

## Expected behavior
For a return to create a new line / not this :)

## Work around
Execute `reset` followed by Control+L to redraw the screen.

## Comments
Looking at `master`, this issue did not occur when I manually built a7078a1f9ba06ddca0cf2b278d003c3ab9c027e8. However, the issue occurs when building the commit immediately after (94d6fc10f5a754041889b14a480192ce8c8c748b). I am not sure why these changes caused this - but it might be a good place to look.

**Comment by SwampDragons** [comment]
thanks for the heads-up. @azr wanna take a look?

**Comment by vhaidamaka** [comment]
The same behavior in the Debian buster.
GNU bash version 5.0.0(1)-release
Packer was built from the latest master.

Terminal line settings were captured by `stty --all` command before launch a packer (tty_normal) and after (tty_problem). stty is utility to change and print terminal line settings.
Here is the diff between line settings:
```
gnat@linux-pc:~/tty_params$ diff tty_normal tty_problem
6c6
< -ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff
---
> -ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr -icrnl -ixon -ixoff
9c9
< isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt
---
> isig -icanon iexten -echo echoe echok -echonl -noflsh -xcase -tostop -echoprt
```
**icrnl** option is disabled in terminal settings after the packer exit.
From `man 1 stty` input settings section: [-]icrnl translate carriage return to newline.
Opening new `/dev/tty` from `main.go` changes current terminal settings.

**Comment by azr** [comment]
Howdy, a Close call was missing, thanks @vhaidamaka for pointing it out ! Can anyone please tell me if the binaries provided in #7411 fix this ?

**Comment by azr** [comment]
Hello there I merged #7411 as I'm pretty sure it's the fix for this and it was getting in the way of another issue, please tell me if the problem persists, I'll investigate more.

**Comment by vhaidamaka** [comment]
@azr I just checked your binary in #7411 on Debian stretch, everything works correctly: terminal line settings is not changed after packer launch.
Thanks.

**Comment by azr** [comment]
Awesome, great news ! Thanks for telling me @vhaidamaka

**Comment by chrismarget** [comment]
I just built 2c0f6944159d637b9242719882b9e1a8ecbbea15, the new Close() has improved my terminal experience on OSX.

**Comment by stephen-fox** [comment]
Thank you @vhaidamaka for the technical explanation and fix. I appreciate the super fast turn around from you and @azr!
