### ISSUE TITLE
packer use_backing_file does not create qcow2 image with backing file

### ISSUE THREAD

**Issue by smiteshpawar** [hashicorp/packer#7408]
Packer Qemu builder when set use_backing_file creates new qcow2 image that does not use original image as backing file. That causes output file to be very large instead of just diff on top of original file.

- Packer version from `packer version`
[vagrant@kvm-host ~]$ packer version
Packer v1.3.5

- Host platform
CentOS 7.5

- Debug log output from `PACKER_LOG=1 packer build template.json`.

https://gist.github.com/smiteshpawar/e0e9281c4f993f5d4808c5525e26ebfe

- The _simplest example template and scripts_ needed to reproduce the bug.

included in same gist above

**Comment by megalan247** [comment]
To fix this I used "skip_compaction": true in my packer definition. It seems to skip the qemu-img convert stage entirely

**Comment by SwampDragons** [comment]
I've opened https://github.com/hashicorp/packer/pull/9918 to resolve this; binaries of the fix can be found here: https://app.circleci.com/jobs/github/hashicorp/packer/80479

Can you test and verify this solves your issue?
