### ISSUE TITLE
skip build if image already exists in Azure

### ISSUE THREAD

**Issue by MacFlurry** [hashicorp/packer#7421]
Hello,

I have a pipeline with jenkins
Jenkins with launch Packer to build an image, then terraform to build the infrastructure.
I would like to skip the build image from packer if the image is already built. Cause we can relaunch the pipeline several times.

How can I make packer check for the existence of build image name and skip the build process without throwing an error: 

`Build 'azure-arm' errored: the managed image named myImage already exists in the resource group myResoureGroup, use the -force option to automatically delete it.`

I don't want to force a rebuild every time.

- Packer v1.3.5
- CentOS Linux release 7.6.1810 (Core)
  
thanks for your help

**Comment by paulmey** [comment]
IMHO, this functionality doesn't belong in Packer. Packer is a tool for building images, if you don't want to build an image, don't start Packer.
You can probably use the 'az' tool to check if the image exists and if not, launch packer. Alternatively, you could set `PACKER_LOG` and `PACKER_LOG_PATH` and look for the string "the managed image named myImage already exists" on failure.

**Comment by ffalorjr** [comment]
Personally as someone that uses Puppet for "configuration as code", inspec for "compliance as code", and terraform for "infrastructure as code" (along with the other buzz words) I don't see why Packer shouldn't be idempotent like the others.
