### ISSUE TITLE
Feature: Support esxi6 remote_type

### ISSUE THREAD

**Issue by digitalirony** [hashicorp/packer#7426]
Add support for esxi6 as the remote_type, and allow for new hardware versions such as hardware version 14. (currently only tested for version 9). 

I understand that building for esxi5 is most compatible for newer versions of esxi, however esxi5 is EOL, and building against it maybe something people want to do. However the option to build for esxi6 and newer hardware versions would be very appreciated. 

Perhaps remote type maybe just set to something like vsphere instead.

**Comment by SwampDragons** [comment]
What particular version of esxi6 and hardware is not working for you with the current remote type? I know it's confusing that it's named "esx5" but it's my understanding that a lot of people use packer for esxi 6.5+

**Comment by digitalirony** [comment]
It works on esxi6, but it creates a VM with only hardware version 9(since this is what esxi 5 supports), you can't create a VM with hardware version 14, because esxi5 only supports up to version 9. It does WORK on esxi 6.5+, it just uses old hardware revisions, which means newer software can't take advantage of newer hard driver features etc. We tested speed between a hardware version 9 and hardware version 14, and there is a significant increase in throughput on later hardware sets.

**Comment by rickard-von-essen** [comment]
You can set the hardware version with [version](https://packer.io/docs/builders/vmware-iso.html#version).

**Comment by SwampDragons** [comment]
Since we received no reply, I'm going to assume rickard's suggestion was the missing link here.  Let us know if this still doesn't work for you.
