### ISSUE TITLE
pause_before_connecting seems to be ignored

### ISSUE THREAD

**Issue by cybergoof** [hashicorp/packer#7430]
I am running version 1.3.5 of the packer.  My templates is below.  When I run the packer, I need there to be a pause before SSH attempt because there are security changes that are made on new EC2's, and they have to be complete.

It seems that the ssh_timeout, ssh_handshake_attempts, and pause_before_connecting is all being ignored.

```
{
   "builders": [{
      "type": "amazon-ebs",
      "communicator": "ssh",
      "region": "us-east-1",
      "source_ami": "ami-xxxx",
      "instance_type": "t2.micro",
      "ssh_username": "xxxx",
      "ssh_timeout": "10m",
      "ssh_handshake_attempts": "2",
      "pause_before_connecting": "5m",
      "ami_name": "packer-demo {{timestamp}}",
      "vpc_id": "vpc-xxx",
      "subnet_id": "subnet-xxxxx",
      "security_group_id": "sg-xxxxxxxx"

   }],
   "provisioners": [{
      "type": "shell",
      "script": "demo-script.sh"
   }]
}
```

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out. Can you share your debug logs and describe what behavior you are seeing?

**Comment by cybergoof** [comment]
I paused the project and did not catch the logs, but I can describe it.

Basically, packer would immediately start attempting to SSH to the system right away without any pause.  It would also repeatedly perform the SSH (around 10 times?) before bailing. If this is not a known issue or if my config above is correct, I can rerun and provide the logs.

**Comment by SwampDragons** [comment]
I think this is a problem with our logging; pause_before_connecting tries to connect via SSH right away, but once it successfully connects, it disconnects and waits for a certain length of time before reconnecting and starting to provision. The idea is that you use it if your SSH daemon gets up and running before final configuration is complete, so we should wait for a while _after we think we can connect_.

I'll look at the logging and see if there's a way to make that clearer.
