### ISSUE TITLE
Trusted Self Signed Certificate not trusted

### ISSUE THREAD

**Issue by sce81** [hashicorp/packer#7431]
packer version - 1.3.4
vault - v0.11.5
certificate created via this - https://github.com/hashicorp/terraform-google-vault/tree/master/modules/private-tls-cert

and imported across all instances via - https://github.com/hashicorp/terraform-google-vault/tree/master/modules/update-certificate-store

installed on jenkins master, jenkins slave & base image used as the source_image by packer. 

if i run a curl against my vault node from any of the instances i can connect OK without SSL warning. 

```
    "variables": {
        "BUILD_NUM": "{{env `BUILD_NUMBER`}}",
        "consul_download_url": "{{env `CONSUL_DOWNLOAD_URL`}}",
        "vault_download_url": "{{env `VAULT_DOWNLOAD_URL`}}",
        "VAULT_TOKEN": "{{env `VAULT_TOKEN`}}",
        "VAULT_ADDR": "{{env `VAULT_ADDR`}}",
        "VAULT-TLSCA": "{{ vault `secret/packer/tls/vault/ca.crt.pem` `ca.crt.pem`}}",
        "VAULT-TLSCRT": "{{ vault `secret/packer/tls/vault/vault.crt.pem` `vault.crt.pem`}}",
        "VAULT_TLSKEY": "{{ vault `secret/packer/tls/vault/vault.key.pem` `vault.key.pem`}}"
      },
```

```
curl     --header "X-Vault-Token: XXXXXXXXXXXXX"     --request GET     https://vault.domain.internal:8200/v1/secret/packer/tls/vault/ca.crt.pem
{"request_id":"b0c7a724-XXXXXXX-f3312ee3c04d","lease_id":"","renewable":false,"lease_duration":2764800,"data":{"ca.crt.pem":"-----BEGIN CERTIFICATE-----SECRET-STUFF----END CERTIFICATE-----\n"},"wrap_info":null,"warnings":null,"auth":null}
```

but when run as part of my Jenkins pipeline, i get the following error..

```
Running in /home/ubuntu/.jenkins-slave/workspace/Packer-Build-Vault/packer
[Pipeline] {
[Pipeline] sh
+ tee build.log
+ packer build -var BUILD_NUM=49 -var VAULT_TOKEN=**** -var VAULT_ADDR=**** vault.json
Error initializing core: error interpolating default value for 'VAULT-TLSCRT': template: root:1:3: executing "root" at <vault `secret/packer...>: error calling vault: Error reading vault secret: Get ****/v1/secret/packer/tls/vault/vault.crt.pem: x509: certificate signed by unknown authority
[Pipeline] sh
+ tail -1 build.log
```

**Comment by SwampDragons** [comment]
Looks like we need to add an "insecure" option to the Vault client's TLS config. I probably won't be able to get to this before 1.4.0 but I'll try for 1.4.1.

**Comment by sce81** [comment]
Hi @SwampDragons thank you for your answer! That would be great and definitely helpful. But perhaps a note of caution - it would definitely better to be able to specifically trust a certificate, rather than a global "trust anything" 
thanks again!

**Comment by SwampDragons** [comment]
I tend to agree; I'll have to take a closer look at the API bindings we're using and see what I can do.

**Comment by SwampDragons** [comment]
I just sat down to work on this, and I see in our API library that we set and check the following certificate-related environment variables: https://github.com/hashicorp/packer/blob/master/vendor/github.com/hashicorp/vault/api/client.go#L30-L33

What happens if you set VAULT_CLIENT_CERT and VAULT_CLIENT_KEY in addition to your VAULT_ADDR and VAULT_TOKEN?

**Comment by SwampDragons** [comment]
you'll probably also need to set "VAULT_CACERT".

I think this should "just work" but if you set those env vars and it doesn't work, let me know and I'll work on a repro.  I'll look at adding this to the docs so it's clearer how to do this.

**Comment by sce81** [comment]
Hey @SwampDragons sorry to come back to to this, i had worked on another solution for stuff i needed, but now it makes sense to come back to this. So seeking clarity..

do i need to specify the certificate in VAULT_CACERT ?
if so, this becomes a chicken/egg situation as the certificate files would also be stored in Vault.
is it possible to flag for ignore SSL check?

**Comment by SwampDragons** [comment]
You can set https://www.vaultproject.io/docs/commands/#vault_skip_verify, but it's not recommended.

You can see a full list of the flags respected by the client we use here: https://www.vaultproject.io/docs/commands/#environment-variables

**Comment by SwampDragons** [comment]
You can use Vault to generate the CACERT file, if you need: https://learn.hashicorp.com/vault/secrets-management/sm-pki-engine
