### ISSUE TITLE
Enhancement: Ability To Parameterise Temporary Tags With amazon-ebs Builder

### ISSUE THREAD

**Issue by pbowditch** [hashicorp/packer#7432]
The amazon-ebs builder adds a tag of "Name" = "Packer Builder" to temporary instances during the baking process.  This appears to be static and unable to change.

If the build fails or multiple happen in parallel we see a large number of these within our environment.  This makes it difficult for engineers inspecting the environment as well as compliance processes that use tag values for cost reporting, security monitoring, automated housekeeping etc.  

It would be good if we could pass a parameterized list of tags to be applied to the temporary instance - not just the created AMI.

**Comment by rickard-von-essen** [comment]
It's only a default. Set it with `"run_tags": { "Name": "my custom name" }`.
