### ISSUE TITLE
Example configurations for qemu ARM builds?

### ISSUE THREAD

**Issue by mcandre** [hashicorp/packer#7436]
Hi, I am trying to build some ARM guest VM's with Packer. I've had good fortune with Packer + qemu for x86-based guests, but something is off about my ARM configurations. Can someone recommend a Packer JSON example for building ARM Vagrant boxes with qemu, to clear up some of the finer points?

# Configuration

https://github.com/mcandre/packer-templates/tree/issue-153/debian

Specifically, I'm getting stuck on this qemu complaint about an inability to set a boot device list (?)

# Error trace

```console
$ packer build debian-arm64.json
...
qemu-system-aarch64 \
"-cdrom" \
"/home/andrew/go/src/github.com/mcandre/packer-templates/debian/packer_cache/2a6f0986fb423f739b50f89f0d4905752bcac8eb.iso" \
"-drive" \
"file=output-qemu/debian-arm64,if=virtio,cache=writeback,discard=ignore,format=qcow2" \
"-m" \
"1024" \
"-boot" \
"once=d" \
"-name" \
"debian-arm64" \
"-netdev" \
"user,id=user.0,hostfwd=tcp::2406-:22" \
"-device" \
"virtio-net,netdev=user.0" \
"-machine" \
"type=virt,accel=tcg" \
"-display" \
"sdl" \
"-vnc" \
"127.0.0.1:34"
...
qemu-system-aarch64: no function defined to set boot device list for this architecture
```

# System

Packer 1.4.0-dev
qemu 2.11
Ubuntu 18.04 Bionic Beaver
Galaga Pro

Any guidance is much appreciated!

**Comment by SwampDragons** [comment]
I don't know of any qemu/ARM builds off the top of my head, sorry. I'm going to close since this is more of a general help question than an issue to be addressed in the Packer code... maybe reach out to the mailing list (https://groups.google.com/forum/#!forum/packer-tool)?

**Comment by cherusk** [comment]
@mcandre 
I got quite far with the qemu builder with only following adjustments:

>       "type": "qemu",
>       "format": "raw",
>       "qemu_binary": "**qemu-system-arm**",
>       "qemuargs": [ [ "-**machine", "virt**" ],
>                     [ "-device", "virtio-gpu-pci" ],
>                     [ "-boot", "strict=off" ]],

Only gap is the display of the guest not coming up yet.
