### ISSUE TITLE
qemu builder net_device validation too aggressive

### ISSUE THREAD

**Issue by mcandre** [hashicorp/packer#7437]
I think the hardcoded list of allowed values for `net_device` in qemu builds may have lagged behind the available virtual NIC's that qemu now offers. For example, `virtio-net-device` is offered by qemu-system-aarch64, but this value is rejected by packer for `net_device`.

**Comment by SwampDragons** [comment]
Hey, thanks.  Do you know of a list of allowed values I could refer to in order to update the validation?

**Comment by radeksimko** [comment]
I think the chain of commands that can be used to get (more or less definite?) list is something like this

```
// get all machine types
qemu-system-* -machine help
```
```
// get all accelerators
qemu-system-* -accel help
```
```
qemu-system-* -machine type={machine-type-from-above},accel={accel-from-above} -device help
```

which means there is `B (binary) * T (machine type) * A (accelerator)` possible devices, if not more.

This makes me think if maintenance burden of this static list for validation purposes is actually worth it, when qemu itself returns relatively useful error when incorrect device name is passed. e.g.

```
$ qemu-system-arm -machine type=xyz
qemu-system-arm: -machine type=xyz: unsupported machine type
Use -machine help to list supported machines
```
So as long as Packer can transparently pass that error to the user I think we could just avoid the static validation altogether? 🤔 

This is on QEMU `3.1.0` - it may be worth checking `2.x.x` too, but I doubt it will be much different.

**Comment by mcandre** [comment]
For now, it may better to turn off validation and allow good builds to succeed, with proper validation reintroduced later. That would represent a more practical false positive / false negative situation. The current code makes it hard to manage qemu guests.

**Comment by SwampDragons** [comment]
That's fair. I'm happy to stop validating as long as the error bubbles up properly.

**Comment by soul4soul** [comment]
I ran into this issue myself with a powerpc machine since the sungem adapter isn't available in the default list.
