### ISSUE TITLE
Paker is tearingdown the Instance however leaving the DISK behind

### ISSUE THREAD

**Issue by Rohited3** [hashicorp/packer#7439]
CI build failing without any error after creating an image. The outcome of the image created through packer is perfectly fine. 
After debugging found out that it’s a known Issue with Packer attached similar Bug: #7392.

**Comment by rickard-von-essen** [comment]
Please supply the information requested in the issue template:
- Packer version (`packer version`)
- Host platform (`uname -a` etc.)
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a [gist](https://gist.github.com).
- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your [gist](https://gist.github.com).

**Comment by SwampDragons** [comment]
If you think it's the same bug as 7392, we should close this as a duplicate and continue discusson on that issue. If you have some differences between your build and the one shared in the original post on 7392, you can share details of your debug logs and Packer config there.

**Comment by Rohited3** [comment]
Yes I believe its the same as 7392. I will close this bug and follow #7392

**Comment by Rohited3** [comment]
Sorry my bad it is related to #6887

**Comment by SwampDragons** [comment]
Thanks. If you can share some more details (config file, debug logs) on #6887, I'll take a look.
