### ISSUE TITLE
Error with packer_cache following merge of #7423

### ISSUE THREAD

**Issue by DanHam** [hashicorp/packer#7442]
Packer v1.4.0-dev (113c04059)

The merge of #7423 seems to have caused a few issues with the packer_cache directory. As a result I get the following error when building with virtualbox:

```
==> virtualbox-iso: Error finding port: open /Users/dan/working/packer-templates/centos/centos-base/packer_cache/port/8073: no such file or directory
```

Files and directories that should be under `packer_cache` (and some that shouldn't be created at all?) are instead being created in the root of the working directory:

```bash
$ tree -F
.
├── 65dbd15324c1cadd4fe642e9a07dc65c7f10657b.iso/
├── 7784a55a71d48a1e9b5c487431438fef0f19d87f.iso/
├── 8073/
...
├── centos.json
├── clean*
...
├── packer.log
└── packer_cache/
    ├── 65dbd15324c1cadd4fe642e9a07dc65c7f10657b.iso -> /Users/dan/stuff/iso/os/centos/CentOS-7-x86_64-NetInstall-1810.iso
    ├── 65dbd15324c1cadd4fe642e9a07dc65c7f10657b.iso.lock
    ├── 7784a55a71d48a1e9b5c487431438fef0f19d87f.iso -> /Applications/VirtualBox.app/Contents/MacOS/VBoxGuestAdditions.iso
    └── 7784a55a71d48a1e9b5c487431438fef0f19d87f.iso.lock
```

Hope that helps.

ping @azr

**Comment by SwampDragons** [comment]
Yeah I noticed a similar issue this morning. If I create the "port" directory inside of packer_cache it works fine, but we need to figure out why packer_cache is failing to mkdirall this.

**Comment by SwampDragons** [comment]
🤦‍♀️ I just accidentally pushed the fix for this to master instead of making a PR.  See https://github.com/hashicorp/packer/commit/3aa0e51104e920c65b0b0bcf82fe2fbb91f116bc.

**Comment by DanHam** [comment]
@SwampDragons Ooops! Well a fix is a fix!! Thanks for the quick turnaround.
