### ISSUE TITLE
qemu builder crashed during box finalization

### ISSUE THREAD

**Issue by mcandre** [hashicorp/packer#7445]
Wish I had more details, but I noticed this in the morning rush before work today. The qemu packer build was just about at the end, when all of a sudden Packer reported a mysterious crash during the Vagrant box finalization. Not sure why.

# Configuration

https://github.com/mcandre/packer-templates/tree/issue-153/debian

* Latest stable Packer
* Latest stable qemu
* Guest: Debian 9.8 ppc64el
* Host: Ubuntu 18.10 Cosmic Cuttlefish
* Galaga Pro with 1TB HD, 16GiB RAM

**Comment by SwampDragons** [comment]
Is this still an issue?
