### ISSUE TITLE
Packer build outputs sensitive variables

### ISSUE THREAD

**Issue by i906** [hashicorp/packer#7448]
The sensitive variables are printed when running packer build.

```
==> null: Executing Ansible: ansible-playbook --extra-vars my_secret='-----BEGIN SECRET-----'
```
  
Packer version: 1.3.5
Host platform: macOS 10.14.4
Debug log output and sample scripts: https://gist.github.com/i906/09190a87ae3b3fdfe00f42d07660dba7

**Comment by SwampDragons** [comment]
Thanks for reporting this. I'll take a look ASAP.

**Comment by SwampDragons** [comment]
Okay, I think I figured it out. It looks like that line is getting printed to the UI via UI.Say(), not to the logs. We weren't filtering the UI. I'll look in to implementing the filter in the UI.

**Comment by SwampDragons** [comment]
Here's a patched binary for osx that has the ui filtering in place. Can you verify that this works for you?
[packer.zip](https://github.com/hashicorp/packer/files/3040045/packer.zip)

**Comment by lawrence-c** [comment]
Think I've just hit this issue.
Packer version: 1.4.0
Host platform: macOS 10.12.6
Debug log and template: 
https://gist.github.com/lawrence-c/6f304ddf361c33effddc3ff3de9040d5

**Comment by Chr0my** [comment]
Same issue here 
Packer version : 1.4.0 & 1.4.1
Host platform : Debian stretch
All logs here : https://gist.github.com/Chr0my/fd250482b82795fc400f4cf8d0038d61
