### ISSUE TITLE
qemu builder: Option to provide preseed files as CD devices

### ISSUE THREAD

**Issue by mcandre** [hashicorp/packer#7449]
Some guests, such as Ubuntu 18.04 ppc64el on qemu-system-ppc64 with machine pseries, do not support floppy drives. Nor is networking up at the beginning of the installation process, so for these guests, neither `floppy_files` nor `http_directory` are sufficient to get preseed files into the guest.

However, CD drives are widely supported, e.g. for ISO booting. I think if Packer added a `cd_files` option, that would really help to get non-x86 guests building much faster and more reliably, compared to having to navigate GUI prompts by `boot_command`!

Could we please get a `cd_files` option for presenting preseed files to guests? `usb_files` would also be nice to have, however USB bus support is less common than CD drive support over PCI virtual bus.

**Comment by rickard-von-essen** [comment]
This feature has been on my mind for some time. The only hard ting about it is to create an ISO9660 image from files natively in Go.

**Comment by sebyx** [comment]
I can also add that RedHat 8 beta has been released and support for floppy device has been removed.

**Comment by matthiassb** [comment]
@rickard-von-essen Would this project suffice? https://github.com/johto/iso9660wrap

**Comment by rickard-von-essen** [comment]
@matthiassb maybe.. That looks interesting.

**Comment by matthiassb** [comment]
No promises, but I'll try to get a PR in for the "cd_files" attribute and creating the image file. Will probably be some time since I have a few things on my plate at the moment.

**Comment by MaxPeal** [comment]
any update on this problem?

**Comment by rgl** [comment]
BTW, there's also the https://github.com/kdomanski/iso9660 library to create iso files.

**Comment by SwampDragons** [comment]
This has been partially addressed in https://github.com/hashicorp/packer/pull/9796, with qemu support planned to follow by the 1.6.3 release.
