### ISSUE TITLE
AWS import job stuck at “Starting rename of AMI” forever

### ISSUE THREAD

**Issue by harshchauhan1988** [hashicorp/packer#7453]
Trying to build AMI with the OVA import to S3. it was working all the while but now I could see the jobs are stuck at "Starting rename of AMI" In reality the import job succeeds. Please help.

In my understanding "Copy the AMI to create a new AMI (This is essentially what a rename of the AMI does)". This failure occurs 8 out of 10 times and hampering our build process badly.

*************************************************
Snippet of Import task status:
*************************************************
```
aws@Cloud-Automation-Host:~$ aws  ec2 describe-import-image-tasks -- 
import-task-ids import-ami-067ff7c968962fffb
{
    "ImportImageTasks": [
        {
            "Status": "completed",
           "LicenseType": "BYOL",
            "ImageId": "ami-0778e29c4926231de",
            "Platform": "Linux",
            "Architecture": "x86_64",
            "SnapshotDetails": [
                {
                    "Status": "completed",
                    "DeviceName": "/dev/sda1",
                    "Format": "VMDK",
                    "DiskImageSize": 2152929792.0,
                    "SnapshotId": "snap-0a9e836f4359eeca2",
                    "UserBucket": {
                        "S3Bucket": "***-jenkins-us-west-1",
                        "S3Key": "**-6cce79e-***.ova"
                    }
                }
            ],
            "ImportTaskId": "import-ami-067ff7c968962fffb"
        }
    ]
}

[aws@kvm1: ~]# packer -v 1.1.2

[awsa@kvm1: ~]# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty
```

*****************************************
Analysis from AWS support Team:
*****************************************

I understand that you are making use of Packer to import a VM into AWS and are running into an error where the job hangs on "Starting rename of AMI".

Please note that we do not provide support for Packer as it a third party application not covered under the support scope of AWS Premium Support. This being said, the support provided here is on a best effort basis.

I have taken a look at the output you have provided me within your first correspondence and based on this, I analyzed the API calls that were made to your AWS account in CloudTrail via Packer. Taking a look at the API calls that were made, we can confirm that the image was successfully imported (as you have already mentioned). 

Looking further into CloudTrail, we can see the CopyImage call is made and is successful (Cloudtrail event ID e509d8f5-520f-4143-8e00-0b900e99bee2). I had a look at the source code for Packer and identified where the call is being made, you can see a snippet of the code below [1] 

	ui.Message(fmt.Sprintf("Starting rename of AMI (%s)", createdami))
	
	resp, err := ec2conn.CopyImage(&ec2.CopyImageInput{
	Name: &p.config.Name ,
	SourceImageId: &createdami,
	SourceRegion: config.Region,
	})
	
	if err != nil {
	return nil, false, fmt.Errorf("Error Copying AMI (%s): %s", createdami, err)
	}
	ui.Message(fmt.Sprintf("Waiting for AMI rename to complete (may take a while)"))

We can see this call being made however, it appears to hang here as we do not see an error or the next step of the process taking place. The CopyImage call is however successful as confirmed in CloudTrail).

I had taken a look at your second correspondence (the successful upload) and the corresponding API calls in CloudTrail. I can see that the CopyImage call is present and thereafter, a large amount of Describe calls. The Describe calls are not present in the failed upload. This being said, I suspect that there is an issue in the above block of code and the way that Packer is processing the request because we cannot see subsequent Describe calls in CloudTrail for the failed upload.

- Debug log output from `PACKER_LOG=1 packer build template.json`.

 https://gist.github.com/harshchauhan1988/5d4340006a00e8cf2c25b1175a9409ee

Packer Template 
https://gist.github.com/harshchauhan1988/8b78f15e3eda394387b2048e249f7c3f

Python Script:

https://gist.github.com/harshchauhan1988/5d3bef57ca5da81d4dee5f3d477a173e

**Comment by harshchauhan1988** [comment]
What is the way forward on this issue? Do you have any workaround for this issue?

**Comment by SwampDragons** [comment]
I haven't had a chance to look into it yet. I'll update the ticket once I get a chance to investigate.

**Comment by SwampDragons** [comment]
Not yet. I've been working on last minute details for the 1.4.0 release and have not had a chance to look at this. Thanks for your patience.

**Comment by SwampDragons** [comment]
I started looking into this. That CopyImage call is a third party call; if it is never returning for you, it's the fault of the AWS SDK, not of Packer.

In your original post, you said 
> it was working all the while but now I could see ...

Did this used to work and recently became flaky, or has it always been failing 8/10 times?  If it recently became flaky, when did this happen?

The logs are also confusing to me. If Packer is hanging on that CopyImage call, you should still see it time out and further logging. Is it possible that your CI job is timing out before Packer has completed the upload?

**Comment by SwampDragons** [comment]
I've also seen these kinds of weird long amazon API hangs happen when there's something going on with credentials. Is it possible that you are using temporary keys that could be expiring before the build completes?

**Comment by harshchauhan1988** [comment]
It became flaky recently without any change in packer version or script code.

let me follow up with AWS folks as well and see what observation they have.

I am not using Temporary credentials for this process.  I am sure that CI job is not timing out.. it keeps on waiting for completion.

**Comment by SwampDragons** [comment]
After my comment on Friday I spent some time coming through the open issues on the AWS SDK about hangs/timeouts. I didn't see anything exactly describing what we're seeing but there are a couple of issues around hangs in waiters.

**Comment by SwampDragons** [comment]
In your logs, in the "Aborting." line -- where is that coming from? I don't see it in your Python script. Did you manually abort and that's a Jenkins logline?

**Comment by SwampDragons** [comment]
Any answer from AWS or insight into where that "aborting" line is coming from?

**Comment by harshchauhan1988** [comment]
> In your logs, in the "Aborting." line -- where is that coming from? I don't see it in your Python script. Did you manually abort and that's a Jenkins logline?

Yes, it was a manual abort.  I was facing issue to update AWS support ticket so couldn't do that and I will do it today.

**Comment by SwampDragons** [comment]
Since this started randomly happening with no change to Packer, I'm going to say this is an upstream bug with Amazon and close.
