### ISSUE TITLE
Packer Crash on Windows 2K16 with hyperv-iso

### ISSUE THREAD

**Issue by nehrman** [hashicorp/packer#7454]
Trying to build hyper-V Gen 2 image with hyperv-iso builder on Windows 2016 Server but It crashes even in the validate process with panic: runtime error : index out of range.

- Packer version: 1.3.5 and also 1.3.4
- Windows 2016 Std with Hyper-V enabled

packer template : https://gist.github.com/nehrman/0be69a91d740c04e209afb3815b86219

packer crash log : https://gist.github.com/nehrman/178ca4ee35e0491acf12e47c4dc74fe9

**Comment by nehrman** [comment]
packer templates : https://gist.github.com/nehrman/0be69a91d740c04e209afb3815b86219

**Comment by azr** [comment]
Hello @nehrman, thanks for opening and sorry for the inconvenience ! This part of packer recently changed and the panic might have been fixed.
Can you please tell me if you still have the issue using this binary from master:
[packer_windows_amd64.zip](https://github.com/hashicorp/packer/files/3034252/packer_windows_amd64.zip)

**Comment by azr** [comment]
I got an offline confirmation that this worked ! Awesome. 

this probably happened in #6999
