### ISSUE TITLE
Unrecoverable build

### ISSUE THREAD

**Issue by davidebelloni** [hashicorp/packer#7455]
Hi,
I've a build on googlecompute that use ansible remote provisioner that usually run; but after some executions, ordinarily after an error (for example timeout network, new erroneous ansible code, etc...) the build fail as described in the log.

Opening a new shell doesn't solve the problem, instead restarting the client solve (O_o) 

Some advices?

Packer v1.3.5
Host platform: OS X 10.14.4
Packer Log: https://gist.github.com/davidebelloni/3c1ac0d589eb76b130c4ae5b41cdb001

**Comment by SwampDragons** [comment]
Thanks for reaching out! The ansible provisioner is one of our community-supported provisioners, which means that the HashiCorp maintainers don't spend much engineering time on it. We probably won't have much of a chance to look into the networking weirdness you're seeing here.

Which client are you restarting to fix this?

**Comment by davidebelloni** [comment]
Hi,
I've to restart mi MacBook (where packer is executed)

**Comment by SwampDragons** [comment]
Could it be an issue with your SSH Agent?

**Comment by davidebelloni** [comment]
Maybe, but in the case only with packer & ansible? This issue doesn't happen with only ansible for config management.

**Comment by SwampDragons** [comment]
The ansible provisioner uses a separate SSH implementation from the rest of Packer, so it's very possible that it would only happen there.

**Comment by davidebelloni** [comment]
Hi,
you are right. The issue is the same as https://github.com/hashicorp/packer/issues/5798
