### ISSUE TITLE
Hyperv-iso builder keep_registred missing

### ISSUE THREAD

**Issue by iEpixel** [hashicorp/packer#7465]
Hello, i checked the documentation and it seems that virtualbox as well as vmware have a keep_registred option. In my case I successfully built and configured a machine with hyperv. 
Since I'm using windows 10 with hyper v enabled, I would like to keep the vm registred, else I need to manully create the VM with the output-hyperv-iso again.

Is it possible to add the option in near-future or do I need to change to virtualbox, even though hyperv would be better regarding windows and performance.

Kind regards

**Comment by SwampDragons** [comment]
I _think_ that you just need to set `"skip_export": true` if you want to keep the VM in hyper-v.

**Comment by SwampDragons** [comment]
If that feature doesn't solve your problem, we can reopen this issue.

**Comment by iEpixel** [comment]
Hi,
I did try it --> build has been successfull -> vm has been deleted from my hyper v manager again.

Please reopen

`  "builders": [
    {
      "type": "hyperv-iso",
      "guest_additions_mode": "disable",
      "iso_url": "{{ user `iso_url` }}",
      "iso_checksum": "{{ user `iso_checksum` }}",
      "iso_checksum_type": "md5",
      "ram_size": 2048,
      "cpu": 2,
      "vm_name": "PCo_DEMO_VM",
      "communicator": "winrm",
      "winrm_username": "PCoDemo",
      "winrm_password": "demo123",
      "winrm_timeout": "12h",
      "shutdown_command": "C:/Windows/packer/PackerShutdown.bat",
      "shutdown_timeout": "15m",
      "switch_name": "PCo_switch",
      "skip_export": "true",`

skip_export is set true, but output-hyperv is still created with the specific virtual disk.

**Comment by SwampDragons** [comment]
I'm going to need a simple example template that reproduces the issue and full debug logs, as asked for in the issue template.

**Comment by SwampDragons** [comment]
Took a second look here, and I think to add a keep_registered option all we need to do is add a little nuance here: https://github.com/hashicorp/packer/blob/master/builder/hyperv/common/step_create_vm.go#L164-L175

**Comment by SwampDragons** [comment]
The deletion is happening here: https://github.com/hashicorp/packer/blob/master/common/powershell/hyperv/hyperv.go#L621

**Comment by SwampDragons** [comment]
I've added this option to the code; you can test out the linked branch using this binary:
[packer.zip](https://github.com/hashicorp/packer/files/3075409/packer.zip)
