### ISSUE TITLE
when i use variables, builders and provisioners in my sample packer json file i am getting below error. can you please help me 

### ISSUE THREAD

**Issue by gopichamada** [hashicorp/packer#7470]
```json
{
 "variables":{
      "aws_access_key": "",
      "aws_secret_key": "",
      "aws_region": "ap-south-1",
      "aws_ami-id": "ami-007d5db58754fa284",
      "aws_username": "ubuntu"
    },
  "builders": [
      {
        "type": "amazon-ebs",
        "access_key": "{{user 'aws_access_key'}}",
        "secret_key": "{{user 'aws_secret_key'}}",
        "region": "{{user 'aws_region'}}",
        "source_ami": "{{user 'aws_ami_id'}}",
        "instance_type": "t2.micro",
        "ssh_username": "{{user 'aws_username'}}",
        "ami_name": "packer_nginx {{timestamp}}"
      }
    ],
    "provisioners": [
        {
            "type": "shell",
            "inline": [
                "sudo apt-get update",
                "sudo apt-get install nginx -y"
            ]
        }
    ]
}
```

OUTPUT:

PS C:\Users\sweth\Desktop\pra\packerzone> packer validate .\nginx.json
Template validation failed. Errors are shown below.

Errors validating build 'amazon-ebs'. invalid 'ssh_username': template: root:1: malformed character constant: 'aws_username' in:

{{user 'aws_username'}}

**Comment by gopichamada** [comment]
can someone help me what is the issue here

**Comment by azr** [comment]
Hello there, try ```{{user `aws_access_key` }}```.

Please only use _GitHub Issues_ for reporting bugs and feature requests. For general help, use IRC #packer-tool on Freenode or the [mailing list](https://groups.google.com/group/packer-tool).

See https://www.packer.io/community/

**Comment by sweathagulabi** [comment]
Hi Azr , tried the same but didn't work out. same error.

**Comment by SwampDragons** [comment]
you're using single quotes (`'`) instead of backtics: ````

**Comment by SwampDragons** [comment]
You need to change to backtics in all of your places where use use the `user` template engine

**Comment by gopichamada** [comment]
It works, thanking you much for the help mate, appreciate it.
