### ISSUE TITLE
Packer ami creation time increase

### ISSUE THREAD

**Issue by dnr1503** [hashicorp/packer#7472]
I am getting the below failure message after 30 min of AMI creation:

==> amazon-ebs: Waiting for AMI to become ready...
==> amazon-ebs: Error waiting for AMI. Reason: <nil>
==> amazon-ebs: Error waiting for AMI. Reason: <nil>
==> amazon-ebs: Step "stepCreateAMI" failed

*********************************************
This seems to be similar to #6536 . 
Even added the environment variables AWS_MAX_ATTEMPTS - 120  and AWS_POLL_DELAY_SECONDS -60 in my system. But didn't help.

 Can you please help me out in knowing how to increase the ami creation time limit to more than 1 hour ?

**Comment by ssolipuramwex** [comment]
I have set the environment variables
"AWS_MAX_ATTEMPTS": "400"
 "AWS_POLL_DELAY_SECONDS": "10"
But still the AMI creation fails after 30mins, Is there any new variable which need to be added for the wait time for the AMI to be ready:
2019-04-18T20:19:48.5865613Z ==> amazon-ebs: Waiting for AMI to become ready...
2019-04-18T20:49:44.5817020Z ==> amazon-ebs: Error waiting for AMI. Reason: <nil>

**Comment by ssolipuramwex** [comment]
I have set the environment variables
"AWS_MAX_ATTEMPTS": "400"
"AWS_POLL_DELAY_SECONDS": "10"
But still the AMI creation fails after 30mins, Is there any new variable which need to be added for the wait time for the AMI to be ready:
2019-04-18T20:19:48.5865613Z ==> amazon-ebs: Waiting for AMI to become ready...
2019-04-18T20:49:44.5817020Z ==> amazon-ebs: Error waiting for AMI. Reason:

**Comment by SwampDragons** [comment]
Can you share your full logs please?

**Comment by eric51893** [comment]
I had the same error, but it was not an actual timeout.  packer did end after 5 minutes no matter what the timeout.  At the about 5 minutes Packer was checking back with the AMI copy and the copy had failed.  The AMI status = failed.  In tracing this down to the AWS role we used and it did not have kms:generate*. Working now with added IAM policy on role.
