### ISSUE TITLE
keep_registred for hyper-v

### ISSUE THREAD

**Issue by iEpixel** [hashicorp/packer#7476]
Hi,
I did try it --> build has been successfull -> vm has been deleted from my hyper v manager again.

Please reopen

`  "builders": [
    {
      "type": "hyperv-iso",
      "guest_additions_mode": "disable",
      "iso_url": "{{ user `iso_url` }}",
      "iso_checksum": "{{ user `iso_checksum` }}",
      "iso_checksum_type": "md5",
      "ram_size": 2048,
      "cpu": 2,
      "vm_name": "PCo_DEMO_VM",
      "communicator": "winrm",
      "winrm_username": "PCoDemo",
      "winrm_password": "demo123",
      "winrm_timeout": "12h",
      "shutdown_command": "C:/Windows/packer/PackerShutdown.bat",
      "shutdown_timeout": "15m",
      "switch_name": "PCo_switch",
      "skip_export": "true",`

skip_export is set true, but output-hyperv is still created with the specific virtual disk.

_Originally posted by @iEpixel in https://github.com/hashicorp/packer/issues/7465#issuecomment-480061950_

**Comment by SwampDragons** [comment]
I'll reopen the original issue.
