### ISSUE TITLE
Azure-Arm - assign identity to the box, similar AWS-iam_instance_profile

### ISSUE THREAD

**Issue by dbilleci-lightstream** [hashicorp/packer#7478]
Use case: We're using JENKINS on-prem to initiate PACKER to spin up a VM using Azure-ARM, and use Ansible as a provisioner.

On this VM that gets spun up by Packer, we'd like to assign it a Managed Identity so that during the building process, it has access to "things" such as storage accounts, key vaults, container repos.. etc.

This is similar use case as to what AWS EBS builder has had for a long time - iam_instance_profile https://www.packer.io/docs/builders/amazon-ebs.html#iam_instance_profile

I see azure-arm has something with "managed identities" but it seems only to be for the use case where Packer is executed on an Azure VM.. and that host VM has an Identity, and that Identity has ability to launch other VMs, which then Packer can use to launch another VM. Very strange.

Is there any way to do what I'm asking about?  Seems like a pretty simple ask.. if my user can spin up a VM, and also assign an identity to the new VM created.. what's the problem?

This seems to be related but there's been no follow up for a couple months now: https://github.com/hashicorp/packer/issues/7131

Thanks

**Comment by ds89snsadbf** [comment]
Seconding this. The documentation gives no information on how to assign an existing MSI to a packer builder

**Comment by anniehedgpeth** [comment]
We are currently needing this functionality, as well.

**Comment by dbilleci-lightstream** [comment]
Just FYI, I worked around this by writing some Python code that runs along side the packer process which grabs the name of the resource group from the Packer log (while running) and simultaneously attempts to assign a user identity to the box while waiting for it to come online so that the ansible provisioner can be executed.  An identity is created ahead of time (just one for all our builds which has all the needed permissions).  I've found that that identity can be assigned to the machine way before the provisioning happens, so there hasn't been any concern of a race condition yet for me.

**Comment by ds89snsadbf** [comment]
> Just FYI, I worked around this by writing some Python code that runs along side the packer process which grabs the name of the resource group from the Packer log (while running) and simultaneously attempts to assign a user identity to the box while waiting for it to come online before the ansible provisioner is executed. An identity is created ahead of time (just one for all our builds which has all the needed permissions). I've found that that identity can be assigned to the machine way before the provisioning happens, so there hasn't been any concern of a race condition yet for me.

Can you share that

**Comment by dbilleci-lightstream** [comment]
It's built into middle of a larger system, but here's the gist of the code boiled down to 2 functions, one that calls the packer build via subprocess and monitors the log, and the other function that it splits off to do the assignment while the build is happening (python3):

````
# build function
#######

cmd [
    "packer",
    "build",
    "-parallel=false",
    # .... more
]

with Popen(cmd, stdout=PIPE, bufsize=1, universal_newlines=True) as p:
    line_count = 0
    for line in p.stdout:
        line_count = line_count + 1
        
        # match the created RG for identity assignment early in log
        if line_count < 10:
            split_line = line.split(' ')

            # ==> azure-arm:  -> ResourceGroupName : 'packer-Resource-Group-mg5ushzp1p'
            if len(split_line) >= 4 and split_line[4] == 'ResourceGroupName':
                rg_name_split = split_line[6].split("'")
                rg_name = rg_name_split[1]
                assign_thread = threading.Thread(target=identity_assign, args=[rg_name])
                assign_thread.start()


# assign function
#########

def identity_assign(rg_name):
    rg_name_split = rg_name.split('-')
    deployment = rg_name_split[-1]

    # command
    cmd = [
        'az',
        'vm',
        'identity',
        'assign',
        '-g', rg_name,
        '-n', 'pkrvm{}'.format(deployment),
        '--identities'
    ]

    # list of build-time identities to add
    identities = ['/subscriptions/XXXXXXXXX/resourcegroups/MY-MSI-RG/providers/Microsoft.ManagedIdentity/userAssignedIdentities/buildtime-identity-1']

    for identity in identities:
        cmd.append(identity)

    sleep_time = 30
    
    # this may fail couple times while machine comes online, so retry
    attempt = 0
    while attempt <= 5:
        attempt = attempt + 1
        with Popen(cmd, stdout=PIPE, bufsize=1, universal_newlines=True) as p:
            for line in p.stdout:
                print(line, end='')
        if p.returncode != 0:
            print("[DEBUG] Assignment attempt #{} - FAIL!".format(attempt))
        else:
            print("[DEBUG] Assignment attempt #{} - Success!".format(attempt))
            return
        time.sleep(sleep_time)
````

**Comment by dbilleci-lightstream** [comment]
also, FYI, if you have more than one identity on the box, then things get even more complicated.. so even though that says "list of identities to add" I suggest you only add one.  In our case, we then wanted to log into ACR to pull down a docker container, so our ansible playlist basically runs this at some point (on the packer box with the identity):

````
      az login --identity
      
      az acr login --name {{ container_registry }}
      
      docker pull {{ container_registry }}.azurecr.io/{{ container_image }}
      docker tag {{ container_registry }}.azurecr.io/{{ container_image }} {{ container_image }}
````

**Comment by ds89snsadbf** [comment]
can the devs acknowledge this

**Comment by ds89snsadbf** [comment]
I've opened a support case with azure and also emailed our TAM, linking them to this issue

hopefully we can get some eyes on it

**Comment by dapolloxp** [comment]
I am looking for this capability as well. Is this available now?

**Comment by toddrosner** [comment]
Also looking for this. Anyone have any additional knowledge or insight as to when this might be added?

**Comment by SwampDragons** [comment]
We haven't scheduled the work internally yet, but if any community member wants to contribute a PR, we generally prioritize reviewing community PRs above scheduled work.

**Comment by azilber** [comment]
Would love to see this pretty important feature as well...
