### ISSUE TITLE
Couldn't find VMware tools for 'linux'!

### ISSUE THREAD

**Issue by bcube** [hashicorp/packer#7488]
-CentOS 7
-packer version : 1.3.5

Error received. 

```
Build 'pnda_template_base' errored: Couldn't find VMware tools for 'linux'! VMware often downloads these
tools on-demand. However, to do this, you need to create a fake VM
of the proper type then click the 'install tools' option in the
VMware GUI.

```

[centos_base.log](https://github.com/hashicorp/packer/files/3063313/centos_base.log)

Any advice? Thanks a lot

**Comment by azr** [comment]
Howdy @bcube, I think the answer is in your logs:

> Couldn't find VMware tools for 'linux'! VMware often downloads these
tools on-demand. However, to do this, you need to create a fake VM
of the proper type then click the 'install tools' option in the
VMware GUI.

Also read #6182 for more info.

I think your problem should be solved with this, so I'm going to close this issue; but please tell us if the problem persists.

**Comment by marema31** [comment]
Hello @bcube , just for information, rhel7 (on which centos7 is derivated) provides openvmtools (can't remember the correct package name) that are the open source equivalent of vmware tools, theses are recommanded by vmware and RedHat since version 7 that is your case. This tools comes in two packages, one core and one only for graphical parts (not needed for servers).

**Comment by bcube** [comment]
Thanks @azr  and @marema31 . 

I verified my machine with yum -y install open-vm-tools" and the tool is installed. 

```
# /usr/bin/vmware-toolbox-cmd -v
10.2.5.3619 (build-8068406)
```

```
#ps faux | grep -P '(vmware|vmtoolsd)' | grep -v grep | head
root      5980  0.0  0.0 227092  6296 ?        Ss   Apr10   0:43 /usr/bin/vmtoolsd
root      6633  0.0  0.0  16824   856 ?        Ss   Apr10   0:02 /usr/sbin/vmware-authdlauncher
```

Any advice on how to verify if my installation is correct? Thanks in advance
