### ISSUE TITLE
Packer Crash

### ISSUE THREAD

**Issue by JohnnyBopper** [hashicorp/packer#7505]
Packer crashes during build. Tried running the latest version of 1.4.0.

- Packer version: 1.4.0
- Host platform: ESXI
- Crash log, Build log and Packer config: https://gist.github.com/JohnnyBopper/b1b29721f576b4c33d085ee20d92ea09

**Comment by azr** [comment]
Thanks for opening; it looks like the listener`s.l` is nil in here :

https://github.com/hashicorp/packer/blob/c214f6735b3c96cf59dfa55912e787b336917854/builder/vmware/common/step_configure_vnc.go#L108

**Comment by azr** [comment]
Howdy @JohnnyBopper, I think I have a fix in #7509. Can you please tell me if this binary works for you ?

**Comment by rajkrishna1590** [comment]
@SwampDragons  Still am facing this issue. we are using packer:light docker image.

**Comment by azr** [comment]
hello @rajkrishna1590, this fix will be released in the next release, same as the docker image.

Here are some binaries if you want to manually try :

[linux_amd64.zip](https://github.com/hashicorp/packer/files/3130348/linux_amd64.zip)
[windows_amd64.zip](https://github.com/hashicorp/packer/files/3130349/windows_amd64.zip)

**Comment by rajkrishna1590** [comment]
@SwampDragons thank you so much :),. when can we expect the next release?

**Comment by azr** [comment]
We try to have a release cadence of ~6 weeks.
