### ISSUE TITLE
Download File Provisioner Fails With Docker for Mac

### ISSUE THREAD

**Issue by markmsmith** [hashicorp/packer#7511]
## Description
When trying to build artifacts within a docker container, I encountered a problem with the File provisioner, where it wouldn't download the resulting artifacts, giving the error:  
`docker: Download failed: Failed to read header from tar stream: EOF`

I've also seen failures where it just hangs forever, and other times it works for downloading an individual file but then errors for directories with `Build 'docker' errored: DownloadDir is not implemented for docker` (though the linked single-file test case doesn't exhibit that).

I'm guessing it may be related to me using Packer on Mac, where I'm using Docker for Desktop CE, so the host is actually a linux VM, but may also be due to how Packer is trying to pull down the files.

I created a minimal repro (for single-file download) which you can find in this gist:  
https://gist.github.com/markmsmith/fd7861f92d2cbbc3f440d9e5d1c32c32

I've also tried with the destination set to `artifacts`, and `./artifacts/download.txt` with the same result.

## Version Info
Packer Version: 1.4.0 (also saw the same problem with the latest version in homebrew, 1.3.5)
Docker Version: 18.09.2, build 6247962
Docker Desktop Community: 2.0.0.3 (31259), channel: stable, 8858db33c8
macOS Mojave 10.14.3 (18D109)

## Related Issues
This is possibly related to the following directory-download issue, but I'd still expect the single file download case to work:
Issue: https://github.com/hashicorp/packer/issues/3916 . 
PR: https://github.com/hashicorp/packer/pull/4186

**Comment by SwampDragons** [comment]
Thanks for the clear repro case. It works (meaning it fails :D ) for me. I'll take a look at fixing it.

**Comment by SwampDragons** [comment]
So, At least in your repro case, the issue appears to be a typo in your download provisioner:  
the source reads `"source": "/home/root/download.txt",` when it should read `"source": "/root/download.txt",` based on where you uploaded the file to.

When I change the location to find the file in the correct place, I get a successful download.

That said, this error message is pretty useless. I'll look to see if there's some way of checking for a file's existence at a path and surfacing a better error message.

**Comment by SwampDragons** [comment]
I've opened a PR to better surface error messages from docker (see the link above). If you click through, I've also attached an osx binary that you can use to check the new, better error messaging. When I used it in conjunction with your repro script, it correctly displayed that the path does not exist, rather than an EOF error.

**Comment by markmsmith** [comment]
Good catch on the typo.  I must have missed it while pairing down the original file that was using `/home/node/`, sorry :(  

I tested out the binary in your PR and can confirm I'm seeing the much better error message - thanks for the super quick response!  

Hopefully the multi-file version will be implemented at some point, then I can just pull down a whole directory with:
```json
{
  "type": "file",
  "source": "/root/",
  "destination": "./artifacts/",
  "direction": "download"
}
```
instead of getting `DownloadDir is not implemented for docker`.

Anyway, thanks again for your help.
