### ISSUE TITLE
Vagrant Cloud post-processor reports success despite failure

### ISSUE THREAD

**Issue by stephenreay** [hashicorp/packer#7516]
After successfully building 3 vagrant images (parallels, vmware and virtualbox providers) Packer tried to upload the .box files to vagrant cloud as per the config (which worked yesterday and hasn't been changed).

A (presumably) intermittent issue on the remote server resulted in 503 errors, which packer reported, stating it will retry after 10 seconds (the same happened for all three boxes).

After the 3rd "error uploading box" message the next message (again, for each box) was "Box successfully uploaded" followed by "Releasing version: 2.0.1". 

The problem is - none of the .box files were uploaded.

As the error seems to be triggered by a remote error I don't even know how I can try to reproduce this issue, and I don't regularly leave debug logging enabled so I can't provide that output.

If it helps (i.e. examining logs from the server end) the box name is `mooneleaf/ubuntu1604-bundle`, version is `2.0.1`, it happened 

- Packer v1.4.0
- macOS Mojave 10.14.4

**Comment by azr** [comment]
could be related to #6615

**Comment by SwampDragons** [comment]
503 is a permissions, most likely caused by an invalid token. But it definitely shouldn't have tried to release if the upload fails. I'll take a look.

**Comment by SwampDragons** [comment]
Can I see your specific logs for this upload cycle?  I want to narrow down what code path is being taken inside of Packer.

**Comment by stephenreay** [comment]
Hey @SwampDragons - I don't have a log for that run. I can try to run it again but unless there's a way to trigger a 503 response artificially I'm not sure how I'll be able to provide anything useful?

**Comment by SwampDragons** [comment]
That's a bummer. Without logs or a way to reproduce, it's gonna be hard for me to investigate this.  There's nothing clear to me in the code that would cause the release to happen after a failed upload, but I'll try to take a look when I have a chance..

**Comment by stephenreay** [comment]
It occurred to me the bug may have occurred in the server side logic - I wonder if it returned an incorrect response (given that it had just been returning 503, which is usually “maintenance” or “overloaded” - maybe you’re thinking of 403 when you mentioned permissions?)

**Comment by SwampDragons** [comment]
ah, possibly.
