### ISSUE TITLE
Improperly formatted 'VirtualBox Builder (from an OVF/OVA)' documentation

### ISSUE THREAD

**Issue by tonyd20** [hashicorp/packer#7519]
The documentation for [VirtualBox Builder (from an OVF/OVA)](https://www.packer.io/docs/builders/virtualbox-ovf.html) contains improperly quoted code under the section "SSH key pair automation".

The improperly formatted section is pulled in from a separate file with the line:
```
<%= partial "partials/builders/virtualbox-ssh-key-pair" %>
```

The partial fragment by itself appears properly formatted, but does not render correctly once included in the VirtualBox Builder (from an OVF/OVA) document.

- Packer version 1.4.0

**Comment by SwampDragons** [comment]
Thanks! I'll fix this ASAP

**Comment by SwampDragons** [comment]
Closed by #7520
