### ISSUE TITLE
Azure builder should enable "boot diagnostics" in the building VM

### ISSUE THREAD

**Issue by jasonzio** [hashicorp/packer#7531]
The Azure builder can timeout with "Waiting for SSH to become available", but there's no way to investigate what caused the timeout. By enabling "boot diagnostics" in the building VM, at the very lease one could "Connect to serial console" to see if the log spew explained the problem.

**Comment by TryTryAgain** [comment]
Related: https://github.com/hashicorp/packer/issues/6008

**Comment by AL71B** [comment]
Hi,
Has this been implemented yet? If not any idea when?
Many Thanks

**Comment by SwampDragons** [comment]
This has not been implemented, and I'm not sure when the team will have a chance to take a closer look at implementing this. But I'd be happy to review any PRs that implement this as an option.
