### ISSUE TITLE
Azure builder doesn't report meaningful error when Azure can't allocate the target VM due to capacity or allocation constraints

### ISSUE THREAD

**Issue by jasonzio** [hashicorp/packer#7532]
If the region targeted by Packer is capacity-constrained for the chose SKU, or if the subscription used by Packer has exhausted allocation for that SKU in that region, packer will just timeout while "Waiting for SSH to become available..." instead of issuing a helpful error message.

**Comment by paulmey** [comment]
Thanks for the suggestion. Can you add some detail on how Packer should detect this situation?
I guess deployment succeeds, because Packer continues to waiting for SSH? Does VM start eventually fail?
