### ISSUE TITLE
1.4.0 virtualbox "errored: Downloading file: [Empty checksum]"

### ISSUE THREAD

**Issue by ndench** [hashicorp/packer#7533]
I recently upgraded to Packer 1.4.0 (on the April 14) and now I receive the following error when running a packer build for a virtualbox vm:

```
packer build -var ovf_path=xenial-server-cloudimg-amd64.ova bug_report.json
bug-report output will be in this color.

==> bug-report: Retrieving Guest additions
==> bug-report: Trying /usr/lib/virtualbox/additions/VBoxGuestAdditions.iso
==> bug-report: Trying /usr/lib/virtualbox/additions/VBoxGuestAdditions.iso
==> bug-report: /usr/lib/virtualbox/additions/VBoxGuestAdditions.iso => /tmp/tmp.AxTRhsnQHy/packer_cache/619ead18d4ff0ca0d3233f2f405bb9bb5924502e.iso
==> bug-report: leaving retrieve loop for Guest additions
==> bug-report: Retrieving OVF/OVA
==> bug-report: Trying xenial-server-cloudimg-amd64.ova
==> bug-report: leaving retrieve loop for OVF/OVA
==> bug-report: Deleting output directory...
Build 'bug-report' errored: Downloading file: [Empty checksum]

==> Some builds didn't complete successfully and had errors:
--> bug-report: Downloading file: [Empty checksum]

==> Builds finished but no artifacts were created.
```

I've created [a gist](https://gist.github.com/ndench/8a365ffa2288d0d6c3a5ee30bec7d931) which shows the easiest reproducible case as well as the packer log.

Downgrading to packer 1.3.5 fixes the issue.

Some details:
packer version: 1.4.0
virtualbox version: 6.0.6 r129722
OS: Arch Linux 5.0.7

**Comment by SwampDragons** [comment]
Thanks for reaching out; sorry for the regression. I believe this is a duplicate of #7496; there are some builds on that issue which contain a patch that should solve this for you.

**Comment by ndench** [comment]
Ah cool, thanks for that @SwampDragons. Sorry about the duplicate issue, I only checked open issues to see if it was already raised.
