### ISSUE TITLE
Google: Add support for source_image shared from another project

### ISSUE THREAD

**Issue by kitkitcheung** [hashicorp/packer#7542]
Packer version: 1.4.0

In the build json, I defined the source_image value under googlecompute builder like :

"source_image": "project/xxxx-distcompute-dev/global/images/gce-image-test-xxxxxxx"

And execute packer build, the below error throws out:

![image](https://user-images.githubusercontent.com/19661371/56457558-4932bf80-63af-11e9-95b3-73770d229efb.png)

Could please support for source_image shared from another project?

**Comment by rickard-von-essen** [comment]
See [source_image_project_id](https://packer.io/docs/builders/googlecompute.html#source_image_project_id)
