### ISSUE TITLE
Comments in Packer JSON Files

### ISSUE THREAD

**Issue by vikas027** [hashicorp/packer#7544]
Prior to Packer v1.4.0, I was able to use a multiline comment by adding a `_description` in the root level key.

```json
  "_description": [
    "xxxx",
    "yyyy",
    "zzz"
  ],
```

Now, in Packer v1.4.0 we need to use `_comment` as shown [here](https://www.packer.io/docs/templates/index.html#comments).

This is fine but it was actually better to use an array rather than a string to store some information of the image along with tracking numbers, etc

Can you please take this as a feature request?

**Comment by SwampDragons** [comment]
This is probably going to be rendered unnecessary when we switch to using HCL2 templates later this year, as they allow comments. As a workaround in the meantime, you can either stick to v1.3.5 or you can use jq to remove the "_description" from your packer template as part of your wrapping script. 

For example: 
`jq 'del(._description)' commented_template.json`

will print your template without the _description field to stdout.

I'll leave this issue open for now in case a community member wants to work on it, but the HashiCorp maintainers will probably not work on it.

**Comment by SwampDragons** [comment]
This will be closed in https://github.com/hashicorp/packer/issues/1768

**Comment by SwampDragons** [comment]
I've added a documentation page that explains how to use jq to strip comments from docs, which will provide you with a workaround until we complete the HCL2 work.  you can see it here: https://github.com/hashicorp/packer/pull/7547

**Comment by dragon788** [comment]
I had a case where I had a REALLY long `boot_command` array, and I wanted to add comments to it, but with the `type == 'object'` I ended up having to wrap my comments within the array to make them objects (otherwise `jq` failed to find them), but then when it removed them it left the empty braces causing `packer validate` to fail. I extended the command slightly to run another filter and find these empty "objects" and remove them.

    jq 'walk(if type == "object" then del(._comment) else . end) | del(.. | select(length == 0))' commented_template.json > clean_template.json
