### ISSUE TITLE
[feature request] [proxmox] allow to disable "KVM hardware virtualization"

### ISSUE THREAD

**Issue by shantanugadgil** [hashicorp/packer#7550]
For the new upcoming Proxmox builder, could you add the "kvm" option, and let the user **disable** this option as well.
This option has a 0/1 value using the `qm` command.

Use case:
I have installed PVE installed on my laptop under VirtualBox and the VTx is not passed through to PVE. :monkey: 

- Packer version from `packer version`
Packer v1.4.1-dev

- Host platform
Linux: Ubuntu 18.04 / CentOS 7.x

- Debug log output from `PACKER_LOG=1 packer build template.json`.
not relevant, I think

- The _simplest example template and scripts_ needed to reproduce the bug.
From: https://github.com/hashicorp/packer/pull/7490/files, I gather than the `kvm` setting is not an option in Packer yet.

**Comment by jboero** [comment]
+1 For this feature.  When your manifest includes multiple parallel local hypervisors such as Qemu + VirtualBox + Vagrant, the first builder grabs the KVM hardware and the others fail.  Qemu already has this option via "accelerator" https://www.packer.io/docs/builders/qemu/#accelerator

**Comment by romantomjak** [comment]
I can look into this, but I would appreciate if someone would help me to understand what's supposed to happen and what actually happens. It looks like a single boolean flag, but perhaps it depends on some other configuration values being set/configured as well?

@jboero please forgive my lack of knowledge as I've only installed proxmox last week and I don't know much about hypervisors, so please correct me if I'm wrong, but I think what you are saying is not related to this particular issue? KVM is a kernel module that allows to run multiple VMs, so you're not obtaining an exclusive lock to build or run a VM with it. Orrrr are you saying this is exactly the case? In which case I have a question - how can you run multiple VMs with KVM virtualization enabled? And also how would disabling KVM in proxmox builder help you in your workflow?

**Comment by shantanugadgil** [comment]
my original request was just to have an option to disable hardware virtualization in the VM's config.

![image](https://user-images.githubusercontent.com/2508915/86058012-c8288b00-ba7d-11ea-9b75-cf514ee030d4.png)

**Comment by romantomjak** [comment]
Ok, thanks. That's what I understood as well
