### ISSUE TITLE
Hang when running Ansible provisioner in verbose mode

### ISSUE THREAD

**Issue by nferch** [hashicorp/packer#7552]
Similar symptoms to #7525, but able reproduce on 1.3.5 so not a regression.

- Packer version
```>packer version
Packer v1.3.5

Your version of Packer is out of date! The latest version
is 1.4.0. You can update by downloading from www.packer.io/downloads.html
```
- Ansible version
```>ansible-playbook --version
ansible-playbook 2.7.10
  config file = /home/nf/.ansible.cfg
  configured module search path = ['/home/nf/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/nf/.virtualenvs/ansible/lib/python3.5/site-packages/ansible
  executable location = /home/nf/.virtualenvs/ansible/bin/ansible-playbook
  python version = 3.5.2 (default, Nov 12 2018, 13:43:14) [GCC 5.4.0 20160609]
```

- Host platform
```>uname -a
Linux slanted 4.4.0-145-generic #171-Ubuntu SMP Tue Mar 26 12:43:40 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
>lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial
```
- I disabled SSH multiplexing to eliminate it as a possible source.

Debug logs and configs at https://gist.github.com/nferch/3a4bb78a724be49ece78ccfcd05f235f

**Comment by SwampDragons** [comment]
Thanks for opening a fresh issue!

**Comment by azr** [comment]
Hello there @nferch, the issue was solved on master, can you please confirm to us wether the issue was solved for your case as well ?

A nighly build can be found here: https://github.com/hashicorp/packer/releases/tag/nightly

**Comment by nferch** [comment]
@azr getting the same results on the nightly build from 5504709

**Comment by azr** [comment]
@nferch, what is the content of your `preseed.cfg` file ?

**Comment by nferch** [comment]
@azr added to the gist https://gist.github.com/nferch/3a4bb78a724be49ece78ccfcd05f235f#file-preseed-cfg

help reproducing would be appreciated, I only have one bare metal machine on which to test this.

**Comment by SwampDragons** [comment]
Hi! I was just going through old Ansible issues and I think it's possible that this was a duplicate of https://github.com/hashicorp/packer/issues/7879 -- That issue has since been fixed. Can you try updating to Packer v1.5.1 and let me know if the issue persists?

**Comment by nferch** [comment]
Unable to repro with v1.5.1. Thanks for the ping!
