### ISSUE TITLE
Unable to build on Cloudstack 4.12

### ISSUE THREAD

**Issue by nlindblo** [hashicorp/packer#7557]
I have recently installed a new instance of Cloudstack 4.12 and am reusing a packer job to build templates with that worked in 4.11 but keep getting the error 

**json: cannot unmarshal string into Go struct field DeployVirtualMachineResponse.ostypeid of type int64**

The template_os is described as a uuid and I have checked that it corresponds with the OS type ID in Cloudstack (and tried other OS types). Interestingly, the instance does get created and shows the right OS in Cloudstack after the build has failed.

- Packer version from `packer version` = 1.4.0
- Host platform = Cloudstack 4.12
- Debug log output https://gist.github.com/nlindblo/90b578ae6d2fe86c4a536796d2c742a1

**Comment by nlindblo** [comment]
Let me know what further info is required and I will do my best to provide

**Comment by rickard-von-essen** [comment]
I bet this falls in one of these two categories:

a) Regression in the CloudStack API
b) Breaking change in the CloudStack API and we need to update the [client library](https://github.com/xanzy/go-cloudstack) we are using. Quickly checking it looks like master of it still uses an `int64` for this.

**Comment by rickard-von-essen** [comment]
@svanharmelen what do you think?

**Comment by svanharmelen** [comment]
@rickard-von-essen just a quick FYI that I am working on this one. Hope to be able to provide a fix EOD.

**Comment by svanharmelen** [comment]
I had a look at this last Friday, but it turns out to be a little more work to sort things out properly. So I'll probably update this issue later this week.

**Comment by nlindblo** [comment]
Appreciated, I am a bit stuck at the moment not being able to update my templates.

**Comment by nlindblo** [comment]
If this is going to take some time to resolve, is there any workaround that could be used ?

**Comment by svanharmelen** [comment]
I don't think that is an easy workaround for the time being. But I'm reserving some time for this one early next week. So it shouldn't be too long before we have a fix.

**Comment by svanharmelen** [comment]
It turns out this takes much more work than expected. Not this specific issue on its own, but for supporting CS 4.12.0.0 as a whole. A lot of tests fail and it seems this is related to either a bug or changed behaviour in CS.

I'm currently discussing my findings with the CS team and hope we can resolve things quickly.

**Comment by nlindblo** [comment]
What is the status on this ? What I gather from the associated Cloudstack issue, there will be no fix until next Cloudstack release, is that the end of it or will a workaround be developed ? As you already have established, I can confirm that Terraform is broken as well with the same error.
