### ISSUE TITLE
Feature Request: Make http server (from boot_command) avaiable at other times

### ISSUE THREAD

**Issue by rwstauner** [hashicorp/packer#756]
Have you considered making the http file server (that is available for the `boot_command`) available throughout the whole build process?
Seems like it would be a nice feature, but I'm not yet familiar enough with the project to guess at its feasibility.
### Background

I now realize that template variables (like `.HTTPIP`) are specific to the context in which they are evaluated (many variables are only available in certain strings).

However, on my first attempt to use packer,
I already had the ubuntu iso i wanted to use downloaded locally,
so i moved it to my http directory
and changed my packer config to use `iso_urls` and i tried to first download from `.HTTPIP` thinking that the http server would be available.

```
Error downloading: Get http://<no value>:<no value>/iso/ubuntu-12.04.2-server-amd64.iso: dial tcp: unknown port tcp/<no value>
```

The iso download obviously comes before the boot_command, so maybe that was a little silly, and I realize now that I could also use a file uri, but still, it seems like that could work and it would be a nice feature to be able to use packer's http server from various build steps.

**Comment by duffsterlp** [comment]
@mitchellh I am running into this exact scenario trying to use .HTTPPort in the environment_vars of my provisioners. Any status on this issue?

**Comment by alexz-kh** [comment]
Hello...any updates ?
most interesting, that issue only in passing variables, since http server itself alive after provisioning :

**Comment by rickard-von-essen** [comment]
This is already implemented. https://www.packer.io/docs/provisioners/shell.html#packer_http_addr

**Comment by alexz-kh** [comment]
wow. thanks for extra-fast answer! 

(not to create another one Q.. i'm trying to use ubuntu cloud image, already connect it , but packer failed to connect into booted VM via ssh - for sure, i need to pass correct data for image, via cloud-init . and i can't find how-to pass those data... )

**Comment by rickard-von-essen** [comment]
Please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._
