### ISSUE TITLE
Packer - Unwanted https calls to Internet

### ISSUE THREAD

**Issue by Chr0my** [hashicorp/packer#7565]
Hi,

I'm testing packer 1.4.0 (Debian Stretch) in a closed environment, the host on which packer is launched has no Internet access. 

As I was analyzing flow on my firewall, I saw that each time I launch the packer binary, some HTTPS calls are made to three public IPs.

Exemple with a simply `packer help` :
* 54.204.30.60
* 23.21.164.196
* 54.243.250.172

Could you explain this behavior ? Is that "normal" ? 
You can understand that I don't want that packer send whatever outside my own private network.

Thank's in advance

**Comment by azr** [comment]
Hello @Chr0my, yes this is normal, to measure packer's usage we embed it with some telemetry.

It can be turned off by setting `CHECKPOINT_DISABLE=1` as stated here: https://www.packer.io/docs/other/environment-variables.html#checkpoint_disable

I will close this issue for now, please tell us if there is an issue with this.

**Comment by Chr0my** [comment]
Seems OK for me, thanks :)
