### ISSUE TITLE
Update documentation to reflect new plugin interface

### ISSUE THREAD

**Issue by benwebber** [hashicorp/packer#7581]
Version 1.4.0 changed the signature of builder, provisioner, and post-processor plugins (#7440). This breaking change is not documented anywhere.

* Describe the breaking change in the 1.4.0 release notes.
* Update the plugin documentation with the new interface. All plugins now require a `context.Context`, and post-processor plugins now return a `forceOverride` Boolean.

**Comment by azr** [comment]
Hello @benwebber, thanks for opening ! Sorry I didn't really know about those I a bit new here 🙂
I opened a PR with the doc changes : https://github.com/hashicorp/packer/pull/7583

**Comment by benwebber** [comment]
Thank you! I see now that this change is indeed mentioned in the release notes.
