### ISSUE TITLE
Packer 1.4.0 doesn't work with nohup

### ISSUE THREAD

**Issue by Ryuzavi** [hashicorp/packer#7592]
After updating to 1.4.0 packer doesn't seem to work with nohup to run in the background.  Trying to run it this way will cause the process to enter `stopped` status instantly and it will just stay paused with no output.

This isn't the case with previous versions.  Trying it with 1.3.5 works as expected and the process continues and output to nohup.out accordingly.

This is happening for me on Centos 7.6 and can be tried as follows:

`nohup ./packer build build-script.json &`

**Comment by SwampDragons** [comment]
Interesting. In 1.3.5 on OSX nohup also sends Packer into a suspended state when run this way.

**Comment by SwampDragons** [comment]
Even though this issue preceeds #7677, that one has more conversation. As the two issues are duplicates, I am going to close this one and we can track the problem there.
