### ISSUE TITLE
amazon-ebssurrogate: double AMIs, double snapshots

### ISSUE THREAD

**Issue by tomalok** [hashicorp/packer#7595]
Version:  1.4.0 (not an issue with 1.3.5)
Platform:  macOS (`brew` installed)
    
Yesterday I upgraded Packer from 1.3.5 to 1.4.0 and then did a new amazon-ebssurrogate build...  Instead of getting one AMI and one snapshot (as I expected) I ended up with two of them -- the second one was copied from the first one; `ami_regions` was set to the same singular value as the build `region`...

So, I removed the `ami_regions` config entirely, but I still got a second AMI copied.

FWIW, only the second AMIs and snapshots had tags on them.  Not specifying `tags` for the build still yielded the double AMI / double snapshot situation.

This was not happening with 1.3.5.  If this is, for some reason, the new norm, there should be a configuration option to ensure that only the latest AMI/snapshot from the build sticks around.

Possibly related to #6897?

**Comment by tomalok** [comment]
`debug.out`, `packer.json`, and `vars.json`:
- https://gist.github.com/tomalok/21084c848478780bfb50caf9f7b380b2

**Comment by tomalok** [comment]
With `encrypt_boot` enabled, still end up with two AMIs (second one is encrypted, first isn't).

**Comment by SwampDragons** [comment]
Probably needs to be fixed in a way similar to https://github.com/hashicorp/packer/pull/7521; I'll try to take a look.

**Comment by azr** [comment]
Howdy @tomalok, can you please tell us if the binaries in #7598 fix the issue for you ?

**Comment by tomalok** [comment]
(conversation's moved over to #7598) :)
