### ISSUE TITLE
Can we packer to build ami without using aws access key and aws secret access key?

### ISSUE THREAD

**Issue by kundankumarjha** [hashicorp/packer#7599]
_Please read these instructions before submitting_

**DELETE THIS TEMPLATE BEFORE SUBMITTING**

_Only use GitHub issues to report bugs or feature requests, see
https://www.packer.io/community.html_

For example, _Timeouts waiting for SSH/WinRM_ are generally not bugs within packer and are better addressed by the mailing list. Ask on the mailing list if you are unsure.

If you are planning to open a pull-request just open the pull-request instead of making an issue first.

FOR FEATURES:

Describe the feature you want and your use case _clearly_.

FOR BUGS:

Describe the problem and include the following information:

- Packer version from `packer version`
- Host platform
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a gist https://gist.github.com
- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your gist https://gist.github.com

**Comment by azr** [comment]
Hi, thanks for reaching out. `aws configure` should set those env vars for you.

For these kinds of questions, it's generally better to use the [mailing list](https://groups.google.com/forum/#!forum/packer-tool) where there are more people ready to help; the GitHub issues here are generally monitored only by a few maintainers and a small subset of community members who are generally only working on bugs or enhancements.
