### ISSUE TITLE
[feature] Warn if something Interactive happens

### ISSUE THREAD

**Issue by SteveClement** [hashicorp/packer#7600]
When the "shell" provisioner runs, it would be nice for **packer** to catch any interactivity and give a warning about it.

I face the issue where, if I apt install things that require user input, packer "hangs".

This is of course noticeable but it would be nice to catch such a situation.

**Comment by SwampDragons** [comment]
Thanks for reaching out! 

I love the idea, but there isn't really a reliable way for Packer to accurately intuit this information. Different programs manage interactivity differently.  

In your particular case, you can probably ask Packer to export the variable `DEBIAN_FRONTEND=noninteractive`, which should cause apt to appropriately fail if you didn't set -y everywhere.

You can also take a look at the [ssh_read_write_timeout](https://www.packer.io/docs/templates/communicator.html#ssh_read_write_timeout) variable, which will time out the build if it doesn't get some kind of read response after n minutes. By default it's off, but you may find it helpful for your problem.
