### ISSUE TITLE
amazon-ebssurrogate: SIGINT should clean up keys/security-group, too

### ISSUE THREAD

**Issue by tomalok** [hashicorp/packer#7601]
Although the EC2 instance and volumes appear to be properly cleaned up after `packer` is aborted with a SIGINT, the generated security group and keypair stick around.

Haven't checked to see if the same holds true for other "catchable" SIGs.

**Comment by SwampDragons** [comment]
I can't reproduce this on latest master; when I send a sigint (via ctrl + c), I see the generated key pair and security group being deleted. If you're still experiencing this issue on latest Packer,  can you open a new issue with a full debug log and packer template that reproduces the issue?
