### ISSUE TITLE
Can packer use AWS session manager for provisioning commands?

### ISSUE THREAD

**Issue by red8888** [hashicorp/packer#7602]
Im on mac but I need to build Windows AMIs

I found some examples for building openssh into the windows AMIs but thats really painful it seems

AWS session manager can be used to send commands to windows or linux instances easily: https://docs.aws.amazon.com/cli/latest/reference/ssm/start-session.html

I didn't see anything in the docs, is this supported? The instance would need to have the ssm-agent updated and policy applied but it would be a cross platform transport protocol that packer could use- or maybe packer already has this feature?

**Comment by SwampDragons** [comment]
We don't support SSM, but you can use the winrm communicator. See https://www.packer.io/intro/getting-started/build-image.html#a-windows-example for a working example of how to do this on amazon.
