### ISSUE TITLE
Is there a way to use packer without having to connect to the EC2 instance directly?

### ISSUE THREAD

**Issue by red8888** [hashicorp/packer#7603]
I want to use packer to build AMIs but I dont like that I have to connect to the instance to run commands

I was thinking if all of my image creation stuff can be defined in the user data script then I should never have to connect to the EC2 instance to send it commands or copy files at all right? But user data is capped at a certain size.

I'd like to have packer do the following:
* create a temporary S3 bucket
* apply a temp policy to the instance that grants access to the bucket
* upload my scripts to the bucket
* create a temporary cloudwatch log group
* the instance runs and the user-data script is executed:
    * The script logs all output to the loggroup
    * packer tails the log group in real time echoing to the console
    * the user-data script pulls down and executes all the other scripts from the bucket

I already have a user-data script that does this. I would just need packer to create the bucket, up load files to it, tail the log group

Is this possible? Is my intention clear? Perhaps this is a stupid thing to do and Im missing something here

**Comment by red8888** [comment]
One problem I see is it looks like packer will try to connect no matter what? Is there a way to have packer not try to connect to the instance at all?

**Comment by rickard-von-essen** [comment]
It is in practice not possible since Packer won't know when the script finished or if it was successful.

**Comment by rickard-von-essen** [comment]
Please ask for help on _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool).
