### ISSUE TITLE
Qemu build parameters ssh_host_port_min and ssh_host_port_max are ignored in Packer 1.4.0

### ISSUE THREAD

**Issue by ruzickap** [hashicorp/packer#7607]
It looks like `ssh_host_port_min` and `ssh_host_port_max` are ignored in latest Packer version - 1.4.0.

When I use these two parameter in my template for example:

```text
      "ssh_host_port_min": "2289",
      "ssh_host_port_max": "2299",
```

I can see the the packer log, that packer chooses different port 5972 - not in the range "2289 - 2299":

```text
2019/05/06 13:55:21 packerio: 2019/05/06 13:55:21 stderr:
2019/05/06 13:55:21 packerio: 2019/05/06 13:55:21 Looking for available communicator (SSH, WinRM, etc) port between 2289 and 2299
2019/05/06 13:55:21 packerio: 2019/05/06 13:55:21 Trying port: 5972
2019/05/06 13:55:21 packerio: 2019/05/06 13:55:21 Found available port: 5972 on IP: 127.0.0.1
==> qemu: Found port for communicator (SSH, WinRM, etc): 5972.
```

Full log: https://pastebin.com/kAxL2E9E

- Packer version from `packer version`
```bash
$ packerio version
Packer v1.4.0
```

- Host platform: Fedora 29 

- Debug log output from `PACKER_LOG=1 packer build template.json`.

```text
...
2019/05/06 13:55:21 packerio: 2019/05/06 13:55:21 stderr:
2019/05/06 13:55:21 packerio: 2019/05/06 13:55:21 Looking for available communicator (SSH, WinRM, etc) port between 2289 and 2299
2019/05/06 13:55:21 packerio: 2019/05/06 13:55:21 Trying port: 5972
2019/05/06 13:55:21 packerio: 2019/05/06 13:55:21 Found available port: 5972 on IP: 127.0.0.1
==> qemu: Found port for communicator (SSH, WinRM, etc): 5972.
...
```

- The _simplest example template and scripts_ needed to reproduce the bug.

```json
{
  "builders":
  [
    {
...
      "type": "qemu",
      "communicator": "winrm",
      "ssh_host_port_min": "2289",
      "ssh_host_port_max": "2299",
...
}
```

Full template can be found here: https://github.com/ruzickap/packer-templates/blob/master/windows.json

Please let me know if you need more details...

**Comment by SwampDragons** [comment]
Is this a regression from v1.3.5?

**Comment by ruzickap** [comment]
Yes... This was working fine in previous Packer releases.

**Comment by SwampDragons** [comment]
Okay, thanks. I'll take a look.

**Comment by SwampDragons** [comment]
I think I found it -- copy/paste mistake from a refactor we did for making vnc dialing cleaner in the last release.  Try this build:
[packer.zip](https://github.com/hashicorp/packer/files/3149997/packer.zip)

**Comment by jerrymarino** [comment]
I'm also running into this, is there a possibility the typo also broke `ssh_host` and `ssh_port` too? These seem to not work either.

PS: thanks for fixing, I can confirm the `host_min/max_port are fixed with the above PR!

**Comment by ruzickap** [comment]
I can confirm too, that the PR + build  (https://github.com/hashicorp/packer/files/3149997/packer.zip) above fixed the issue.
Thank you...

**Comment by SwampDragons** [comment]
@jerrymarino Can you open a new issue for your ssh_host and ssh_port problem?

**Comment by howels** [comment]
> @jerrymarino Can you open a new issue for your ssh_host and ssh_port problem?

Here is an issue for the problem which was uncovered here (and is still present in the latest release) https://github.com/hashicorp/packer/issues/7985
