### ISSUE TITLE
panic on amazon-ebs nil region_kms_key_ids map

### ISSUE THREAD

**Issue by tgross** [hashicorp/packer#7637]
On our builds with the `amazon-ebs` builder, we're trying to use a Customer Managed Key (CMK) to encrypt the AMI (so that we can [share it across accounts](https://aws.amazon.com/about-aws/whats-new/2019/05/share-encrypted-amis-across-accounts-to-launch-instances-in-a-single-step/)). I've been unable to come up with a configuration that uses the CMK that works. Following the discussion in #7499 I've tried to use @SwampDragons's build from #7507 and it results in a panic if the `region_kms_key_ids` map is unset, or a failure if it is set.

* host platform: Linux x86_64
* packer version: Post-1.4.0 patch from #7507 
* gist of panic https://gist.github.com/tgross/8ba5b259351f93b2f9982414ee9369e7
* gist without panic but fails: https://gist.github.com/tgross/ce69b86ceb86b5d40b44c532dce8be5a

I'd be happy to contribute a patch for the nil map, but I'm not sure if the intended behavior _should_ fail (and so should be caught in an earlier config validation step), or whether the map just needs a default value.

**Comment by azr** [comment]
Hello there @tgross thanks for reporting, if you would like to contribute I think it's very much okay to default the map to a nil map, it's what I would've done 🙂

**Comment by azr** [comment]
Ah nevermind what I just said, the map is expected to not be set :

```
	amis := state.Get("amis").(map[string]string)
```

**Comment by SwampDragons** [comment]
Ah, I found that bug very shortly after making the linked PR and fixed it in https://github.com/hashicorp/packer/commit/105d3f885380553b5b49ab93e556187f1dc29104.  Sorry for that. You can find binaries on https://github.com/hashicorp/packer/pull/7521 but I believe both patches should also be available on our [nightly build](https://github.com/hashicorp/packer/releases/tag/nightly).

**Comment by tgross** [comment]
Oh, I missed that commit! Thanks @SwampDragons !
