### ISSUE TITLE
add support for qemu cpu cores

### ISSUE THREAD

**Issue by rgl** [hashicorp/packer#7638]
some versions ago there was support for setting the number of cpus with `cpus`, can we also have `cores`? as is, `-smp cpus=<cpus>,cores=<cores>`? maybe even the other qemu options as [described in the documentation](https://qemu.weilnetz.de/doc/qemu-doc.html):

`-smp [cpus=]n[,cores=cores][,threads=threads][,sockets=sockets][,maxcpus=maxcpus]`

Simulate an SMP system with n CPUs. On the PC target, up to 255 CPUs are supported. On Sparc32 target, Linux limits the number of usable CPUs to 4. For the PC target, the number of cores per socket, the number of threads per cores and the total number of sockets can be specified. Missing values will be computed. If any on the three values is given, the total number of CPUs n can be omitted. maxcpus specifies the maximum number of hotpluggable CPUs.

**Comment by azr** [comment]
Hello there, looks like a good idea to me, to implement such a feature reproducing this pull request https://github.com/hashicorp/packer/pull/7156/files will help a lot !

**Comment by sharmaanshul2102** [comment]
@azr I can do this :-1:
