### ISSUE TITLE
change virtualbox vboxmanage example to modify the vram

### ISSUE THREAD

**Issue by rgl** [hashicorp/packer#7639]
since the introduction of the `cpus` and `memory` properties there is no need to also show how to modify them at https://packer.io/docs/builders/virtualbox-iso.html#vboxmanage-commands, instead it should be changed to only set the video ram size, e.g.:

```json
{
  "vboxmanage": [
    ["modifyvm", "{{.Name}}", "--vram", "64"]
  ]
}
```

**Comment by azr** [comment]
Hello there @rgl, good idea ! Would you like to do the honors ?
