### ISSUE TITLE
Amazon EBS: "my_alias_name is not a valid KMS Key Id."

### ISSUE THREAD

**Issue by dhs-rec** [hashicorp/packer#7640]
After update from 1.3.3 to 1.4.0, Packer doesn't accept alias names anymore for `kms_key_id`, but instead errors out with the message in the subject. The documentation still clearly states
> kms_key_id (string) - ID, alias or ARN of the KMS key to use for boot volume encryption.

- Packer version from `packer version`
Packer v1.4.0
- Host platform
Linux

**Comment by azr** [comment]
Hey @dhs-rec, thanks for opening, it looks like to me that your key name is invalid. A key id should more or less look like what's in this screenshot:

![](https://docs.aws.amazon.com/kms/latest/developerguide/images/console-filter.png)


If it looks valid to you then please share your buildfile and the log output like stated in the https://github.com/hashicorp/packer/blob/master/.github/ISSUE_TEMPLATE.md file please.

We will reopen the issue if it looks like there is an issue 🙂

**Comment by dhs-rec** [comment]
No, it's not. In fact the name is `prefix/name` which is a perfectly valid alias. In fact, as I wrote above, it was accepted by 1.3.3. Please reopen.

**Comment by azr** [comment]
@dhs-rec have you recently tried on 1.3.3 ?

**Comment by azr** [comment]
Actually I just found the code for it: 

https://github.com/hashicorp/packer/blob/9836dad0c937dbed2dee0f661f9273912d0d7626/builder/amazon/common/ami_config.go#L149-L168

**Comment by dhs-rec** [comment]
Yes, I was just starting into creating an encrypted AMI _today_ which 1.3.3, but ran into #6889. I therefor tried 1.4.0.

**Comment by azr** [comment]
If you are using an alias; you have to prefix the string with `alias/`, does that solve it for you ? I will update the docs for it.

**Comment by dhs-rec** [comment]
Yes, that accepts the key again. However, I still run into #6889, which 1.4.0 ought to solve.
