### ISSUE TITLE
Incomplete output from shell provisioner #2391 reproduce in  1.40

### ISSUE THREAD

**Issue by dwy2002** [hashicorp/packer#7641]
FOR BUGS:

Describe the problem and include the following information:

- Packer version from `packer version` - 1.40
- Host platform - windows and Linux 
- Debug log output from 
[ec2-user@ip-10-0-0-246 packer.io]$ PACKER_LOG=1 /home/ec2-user/packer build firstrun.json
  Please paste this in a gist 
https://gist.github.com/dwy2002/64fd43caf64e48f1f2bd95d3533f4e9e#file-packer_log

- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your gist 
https://gist.github.com/dwy2002/64fd43caf64e48f1f2bd95d3533f4e9e
 the template is from the https://www.packer.io/intro/getting-started/build-image.html for windows part . 

  

Note:
the issue not reproduce in the 1.25 windows version. 

the 1st full powershell output should be : 
 amazon-ebs: HELLO NEW USER; WELCOME TO PACKER
 amazon-ebs: You need to use backtick escapes when using
 amazon-ebs: characters such as DOLLAR$ directly in a command
 amazon-ebs: or in your own scripts.

**Comment by azr** [comment]
Hello there @dwy2002, thanks for opening; can you please tell me if the issue still happens on the nightly build ?

https://github.com/hashicorp/packer/releases

**Comment by dwy2002** [comment]
@azr 

Thanks, after test the nightly build in 1.4.1, it not reproduce in my environment now . 

the 1st full powershell output display as expect :
amazon-ebs: HELLO NEW USER; WELCOME TO PACKER
amazon-ebs: You need to use backtick escapes when using
amazon-ebs: characters such as DOLLAR$ directly in a command
amazon-ebs: or in your own scripts.

**Comment by azr** [comment]
Awesome ! thanks 🙂
