### ISSUE TITLE
Unable to Build Image using Azure  Custom VNET, Subnet & NSG

### ISSUE THREAD

**Issue by Kannancsq** [hashicorp/packer#7644]
We are using Azure with Packer, and custom our VNET, Subnet and resource group for generating image instead of temporary resources by Packer.

We Created VNET, Subnet and NSG.  In NSG we have enabled Internet in Inbound.

For some reason , we are not sucessfull in generating image. We tried both Windows Image and Ubuntu in both scenarios getting SSH / WinRM time out.

Attached the Script &  Log file.
[win_template.txt](https://github.com/hashicorp/packer/files/3178191/win_template.txt)

Error from Log File
2019/05/14 19:27:13 packer.exe: 2019/05/14 19:27:13 [INFO] Waiting for SSH, up to timeout: 20m0s
2019/05/14 19:27:13 ui: ==> azure-arm: Waiting for SSH to become available...
2019/05/14 19:27:28 packer.exe: 2019/05/14 19:27:28 [DEBUG] TCP connection to SSH ip/port failed: dial tcp 10.1.0.5:22: i/o timeout

**Comment by SwampDragons** [comment]
If you run Packer in debug mode and try to connect independently of Packer while Packer is waiting for SSH/Winrm, are you able to connect to your instances?

**Comment by akingscote** [comment]
@Kannancsq  did you ever resolve this? Having something similar. If i create my image manually through the UI on the same Vnet and subnet i dont have any issues, but with packer is just says "waiting for ssh to become available".

I know azure reserves the first 4 IPs of a subnet, but it looks like its picked an IP out of the reserved range so not sure what the problem is

**Comment by akingscote** [comment]
Figured it out, i was missing the `private_virtual_network_with_public_ip` flag 
```
"private_virtual_network_with_public_ip": true,
"virtual_network_subnet_name" : "packerSubnet",
"virtual_network_name" : "myTFVnet",
"virtual_network_resource_group_name" : "myTFResourceGroup",
```

**Comment by SwampDragons** [comment]
Thanks for sharing @akingscote! @Kannancsq did you ever figure this issue out? If not, does the above solution also fix things for you?
