### ISSUE TITLE
Add support license acceptance Chef 15

### ISSUE THREAD

**Issue by aaronwalker** [hashicorp/packer#7645]
Add the ability to configure the license acceptance for Chef 15. Add a property `chef_license` to the chef-client provisioner.

Right now you can add a config_template using something like
```json
"config_template": "packer/templates/chef-client-win.tpl",
```
and add the chef_license to the template but this should be part of the default template allowing the values to set directly on the provisioner

**Comment by SwampDragons** [comment]
Thanks for this suggestion! This provisioner is one of our community-supported provisioners, which means that the HashiCorp maintainers don't spend much engineering time on it; this means that the best way to see your suggestion make it into Packer is to open a PR. We'll gladly give support and pointers if you're interested in taking a shot at it.

**Comment by Pahanda** [comment]
I used the following in my provisioner to allow it to proceed:
`"execute_command": "{{if .Sudo}}sudo {{end}}chef-client --chef-license accept-silent --no-color -c {{.ConfigPath}} -j {{.JsonPath}}",`

Our cookbooks set up a final client.rb configuration with license acceptance; this simply lets Packer initially bootstrap the image.

**Comment by aaronwalker** [comment]
@Pahanda yeah I made a similar change to get it working again for me but think that it should be supported natively with the ability to provide the value of  `chef-license` as config

@SwampDragons I've start looking at raising a PR to add support
