### ISSUE TITLE
OpenStack Builder: using WinRM connector produces error "An invalid 'name' value was provided."

### ISSUE THREAD

**Issue by JimPruitt** [hashicorp/packer#7646]
FOR BUGS:
**Describe the problem and include the following information**:
I am attempting to use the Packer "OpenStack" builder with the WinRM connector.  I can confirm that the builder is able to connect to OpenStack successfully and it successfully detects the OpenStack "flavor" ID (by using the flavor name).  However, when it tries to launch the source server I get an error:

> openstack: Error launching source server: Bad request with: [POST https://**.***.***.***:*****/v2.1/servers], error message: {"badRequest": {"message": "An invalid 'name' value was provided. The name must be: printable characters. Can not start or end with whitespace.", "code": 400}}

(_Note that the ip address and port are obscured in the above error message_)

- **Packer version from `packer version`** v1.4.0
- **Host platform** Packer was running on **Windows 10**.  Bug also occurs running it on **Centos 7**.
- **Debug log output**from `PACKER_LOG=1 packer build template.json`.
 See https://gist.github.com/JimPruitt/45661198b1229935242c4f380090a412
- The _simplest example template and scripts_ needed to reproduce the bug.
 See https://gist.github.com/JimPruitt/45661198b1229935242c4f380090a412

**Comment by JimPruitt** [comment]
I suspect that the error message might be the result of the OpenStack driver sending a null value for 'key_name' which results in an error message that can be somewhat misleading.

See this link: https://bugs.launchpad.net/nova/+bug/1700825 

I have confirmed that the "image_name" and "source_image_name" are getting set correctly.

**Comment by lmayorga1980** [comment]
👍
