### ISSUE TITLE
[Feature request] target multiple Spot capacity pools

### ISSUE THREAD

**Issue by ranshn** [hashicorp/packer#7648]
Today, in amazon-ebs builder, the way to use a Spot Instance for the build is to use the spot_price parameter, which will then try to run a Spot Instance using the EC2 instance type that is configured in the instance_type parameter.
If there's no Spot capacity available for that instance type, the build will not go through, because Packer will not be able to run the instance.

To improve this, EC2 Fleet with type=Instant can be used for the instance provisioning request. This will act as a drop-in replacement to RunInstances (or RequestSpotInstances) where it will synchronously return the instance ID that was started for the build, but will allow to provide multiple instance types and availability zones, allowing EC2 Fleet to select the cheapest available instance type to run the build on. This flavor of EC2 Fleet (type=instant) does not maintain the capacity or handle the instance that was started in any way, it just runs instances and does nothing further.
Switching to this approach will decrease the risk of Packer not being able to get Spot capacity when trying a single configured instance type.

Information about Instant fleet:
https://aws.amazon.com/about-aws/whats-new/2018/11/synchronously-provision-instances-with-amazon-ec2-fleet/

**Comment by SwampDragons** [comment]
@ranshn When I swapped in CreateFleetInput, I broke our spot_tags functionality, which tags the spot request itself. Testing out the TagSpecifications field on CreateFleetInput, that won't populate the tags for the spot requests eventually generated by the create fleet request. Is there any way to tag the spot requests themselves as part of a fleet request?  

I also tried RequestSpotFleet instead, but IamFleetRole is hanging me up; it requires me to either force users to provide the ARN for an IAM role, or generate a new IAM role as part of the Packer run, which changes the IAM permissions required to use Packer. I'm not thrilled about that idea. 

Any pointers?

For reference, the issue I'm trying to resolve is #7941

**Comment by ranshn** [comment]
@SwampDragons RequestSpotFleet will create a Spot Fleet which doesn't have "instant" mode like EC2 Fleet, which is the synchronous request that you're using, so Spot Fleet is not a good fit.

With regards to tagging, I do see that when using CreateFleet API call the tags that are specified in  TagSpecifications are not applied to the EC2 Instances that are created by the fleet. However, if the Launch Template that is referenced in the Fleet request has tags, then those would be propagated to the EC2 Instances.

Is using the tags in the Launch Template instead of the Fleet request a viable option?

**Comment by SwampDragons** [comment]
Thanks for getting back to me! I need the tags applied to the spot _request_, not the spot instances. We tag the instances separately from the request, and previously we were able to apply tags to both. 

I just tested, and tagging the launch template doesn't tag the spot request. 

I can apply the tags myself using CreateTags if I can get hold of the resource ID for the spot request generated by the CreateFleet call, but as it currently stands I don't see a way to get hold of that ID. Do you know of a way?  It looked like I could get the Spot Request ID from the DescribeFleetInstances calls, but when I try that it errors and says this call isn't supported for "instant" fleets.

**Comment by ranshn** [comment]
Apologies for the misunderstanding. I'm checking how to get the SIR tagged with the Spot team. can you write a few words about why this is needed?

**Comment by SwampDragons** [comment]
My understanding is that some of our users like to be able to track the originator of a spot request, and tag the request with things like "packer": "true" so they can easily associate packer-created resources.

**Comment by ranshn** [comment]
@SwampDragons Unfortunately at this time the SIRs (spot instance requests) are not being tagged on create when using CreateFleet in instant mode.

The workaround will require a couple more calls instead (I'm using the API call names as I'm not familiar with all SDK function names):
1. From the CreateFleet response, capture the instance-id (I believe that your target capacity is always 1, correct?)
2. Call DescribeInstances targeting that one particulate instance-id.
3. Capture the SIR from the response of DescribeInstances.
4. Call CreateTags for that SIR.

Note that the DescribeInstances call might not return the instance-id if called immediately after the CreateFleet call. You might have to put a 1-2 second delay but this requires some testing.

Is this a reasonable solution?

**Comment by SwampDragons** [comment]
That worked! Thanks so much. I swear, that's gotta be the one call I didn't try. You're my hero!

**Comment by ranshn** [comment]
awesome! glad it worked. I also forgot initially that DescribeInstances has the SIR :)
