### ISSUE TITLE
Add support for AWS `Throughput Optimized` (st1) and `Cold HDD` (sc1) drive types

### ISSUE THREAD

**Issue by GrayCatCode** [hashicorp/packer#7650]
ALCON,

I'd like to request support for the AWS `Throughput Optimized` (st1) and `Cold HDD` (sc1) drive types.

Many thanks in advance. :+1:

**Comment by azr** [comment]
Hello @GrayCatCode, thanks for opening. Have you tried those options ? If so what error did you get ?

**Comment by GrayCatCode** [comment]
Well, I went by the documentation (foolish, I know) which didn't indicated support for the `st1` or `sc1` drive types in the AWS EBS builder.  I was delightfully surprised when in fact my AMI was built with the correct (st1) drive type.  I'll test for `sc1` also, but it would seem that all that's needed is a documentation update. :) :+1:

**Comment by azr** [comment]
Hey @GrayCatCode, it's not foolish at all ! 🙂.
Sometimes AWS add options and packer does an API call to validate their existence, which is why I asked you to try. Thanks for telling us ! Megan updated the docs here in #7656, the docs website will be updated for the next release.
