### ISSUE TITLE
Mismatching of check packer endpoint and release link

### ISSUE THREAD

**Issue by sergei-kulick** [hashicorp/packer#7652]
Hello Team,

I see that you change a format of "current_version" property in the response of **https://checkpoint-api.hashicorp.com/v1/check/packer**

it was before
_curl -s https://checkpoint-api.hashicorp.com/v1/check/packer
 jq --raw-output .current_version
 PACKER_VERSION=1.3.5_

it is now
_curl -s https://checkpoint-api.hashicorp.com/v1/check/packer
jq --raw-output .current_version
PACKER_VERSION=**v**1.4.1_

current_version property contains '**v**' before version
So, It brakes all my build plans

Are you going to fix this?
Please let me know

Thx

**Comment by SwampDragons** [comment]
I'll update it now, sorry for the inconvenience.

**Comment by sergei-kulick** [comment]
@SwampDragons ,

Thank you for the fast response.
