### ISSUE TITLE
In provisioners, is it able to make file and use it in "file" type?

### ISSUE THREAD

**Issue by PicoSushi** [hashicorp/packer#7661]
I'd like to copy file to provisioning image, which doesn't exist at running `packer build` . For example, generate file with timestamp at packer building timing, or copy latest file from remote server.

This is my example packer code.

https://gist.github.com/PicoSushi/5f714a81b23d8f6068d2f68059eb0767

In this code, I'd like to copy pre-build binary from S3, but Error says: `Bad source './files/tmp/prometheus-node-exporter': stat ./files/tmp/prometheus-node-exporter: no such file or directory` .
  

- Packer v1.4.0
- Linux kaguya 4.14.113-1-MANJARO #1 SMP PREEMPT Sun Apr 21 12:03:01 UTC 2019 x86_64 GNU/Linux

**Comment by PicoSushi** [comment]
I think, if there're [pre-processors](https://github.com/hashicorp/packer/issues/5342), this works cleanly.

**Comment by rickard-von-essen** [comment]
Use [generated](https://packer.io/docs/provisioners/file.html#optional) `true` to handle this.
