### ISSUE TITLE
Allow the version of chef to be set without the need to override the `install_command`

### ISSUE THREAD

**Issue by aaronwalker** [hashicorp/packer#7664]
Right now it's only possible to override the version of chef client by completely overriding the `install_command` often the reason for doing this is to lock the provisioner to a specific chef version.

I think a useful feature would be to add a `chef_version` to the provisioners config and update the default install_command for reference it if a value is provided.

This would have helped work around a recent change from chef 14 to chef 15 which broke certain configurations.

I'm happy to work on a PR for this change

**Comment by azr** [comment]
Hey @aaronwalker, I think this is a **great** idea 👍 , but only if installing different versions is not too overly complex.
