### ISSUE TITLE
virtio-scsi shows unsupport

### ISSUE THREAD

**Issue by songyu555** [hashicorp/packer#7669]
FOR BUGS:

Describe the problem and include the following information:
when uses disk_interface=virtio-scsi, it fails with error message.
qemu stderr: qemu-kvm: -drive file=output/rhel7-soe,if=virtio-scsi,cache=writeback,format=raw: unsupported bus type 'virtio-scsi'

however based on packer document, virtio-scsi is supported model. would this be a bug?

- Packer version from `packer version`

Packer v1.3.5

- Host platform
RHEL7.6
Linux 3.10.0-957.el7.x86_64 #1 SMP Thu Oct 4 20:48:51 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a gist https://gist.github.com
[debug_log.txt](https://github.com/hashicorp/packer/files/3200237/debug_log.txt)

- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your gist https://gist.github.com
  
[sample.json.txt](https://github.com/hashicorp/packer/files/3200240/sample.json.txt)

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out. RHEL doesn't support virtio-scsi, which we do note in our [docs](https://www.packer.io/docs/builders/qemu.html#disk_interface) -- excerpt below:

>* Please be aware that use of the scsi disk interface has been disabled by Red Hat due to a bug described here. If you are running Qemu on RHEL or a RHEL variant such as CentOS, you must choose one of the other listed interfaces. Using the scsi interface under these circumstances will cause the build to fail.

**Comment by songyu555** [comment]
understand RHEL does not support scsi, but I am not using scsi but virtio-scsi.  do you mean it does not support virtio-scsi too?  Packer docs does not say this though as I read it.

**Comment by SwampDragons** [comment]
This isn't a Packer bug, it's an error messaging being sent from your qemu binary.

It looks like RHEL is supposed to support virtio-scsi, but there are also bug reports from RHEL users that suggest that there are some builds where this support is broken. I suggest you debug this outside of Packer and only try to use Packer once you've verified that your qemu install is good.
