### ISSUE TITLE
Feature request: prompt and secure_prompt functions

### ISSUE THREAD

**Issue by magnusviri** [hashicorp/packer#7670]
Please add a function that prompts for text.  For example, "access key":"{{secure_prompt `Enter access key:`}}".

When the template is run Packer will display "Enter access key:" and the terminal waits for user input.  "secure_prompt" won't show what the user types.  "prompt" will show what the user types.

Right now the examples on your website shows storing secure items in environment variables but you still have to type commands, which are saved to history, to enter those items into the environment.  By prompting the user, you get real security without having to resort to writing a script that prompts and then sets the environment variables.

**Comment by SwampDragons** [comment]
Thanks for reaching out. There are a few workarounds that people generally use for the situation you're facing. 

If you prefix your `export` with a space, it doesn't get recorded in your history: ` export myvar=varvalue`

You can clear the line of history that you used to input the environment var using `history -d <line number where you entered the sensitive variable>`. (example: `history -d 2039`)

If you're on OSX you can use pbpaste to paste a copied password from your clipboard without every having to type it into your terminal:

```
export PASTED_VAR=`pbpaste`
```

I believe xclip is the equivalent command for linux.

You can also source the variable from a dotfile. Personally, I do this one; I have a dotfile with my various credentials with 600 permissions that I can source before a packer run. 

Certain builders can read their keys from their own credentials files; for example, the Amazon builders can read credentials straight out of `~/.aws/credentials`, so you may not need to set the variables at all.

This isn't something I'm interested in implementing, for a couple of reasons. First, a majority of Packer users are using Packer as part of a CI pipeline and are using other specialized tools to set up their environments. But second, Packer is supposed to be entirely automatic. The only time we want you interacting with the Packer run is when you're debugging it, and this feature goes against that philosophy.

Thanks for reaching out, though. If we end up with more bandwidth in the future, I can see implementing this as a debugging tool, but for now I think the gain for a majority of our users if pretty marginal.
