### ISSUE TITLE
No tag or changelog for 1.4.1

### ISSUE THREAD

**Issue by dhs-rec** [hashicorp/packer#7674]
Is this a new release pattern (see #7495)?

**Comment by azr** [comment]
Hey @dhs-rec, thanks for reporting again I just pushed the tag, the changelog is here:  https://github.com/hashicorp/packer/blob/master/CHANGELOG.md#141-may-15-2019

As for the tag, the release process is semi-automated, and pushing the tag part seems to be in limbo. I'll add this step to our release checklist so next time we make sure.
