### ISSUE TITLE
Feature Request: packer EBS builder - share encrypted AMIs with additional accounts (new AWS SDK functionality)

### ISSUE THREAD

**Issue by AndrewCi** [hashicorp/packer#7681]
AWS recently announced the ability to share encrypted AMIs across accounts using a single SDK command. 

https://aws.amazon.com/about-aws/whats-new/2019/05/share-encrypted-amis-across-accounts-to-launch-instances-in-a-single-step/

This would be a great feature to incorporate into packer since it already has the ability to share non-encrypted AMIs with supplied account numbers. It could leverage the same template format since I believe packer can already share unencrypted AMIs.

**Comment by RexChenjq** [comment]
+1 Please
This should be as simple as adding another command like:
aws ec2 modify-image-attribute --image-id $**** --launch-permission "Add=[{UserId=******}]"

**Comment by rickard-von-essen** [comment]
@RexChenjq please test #7707

**Comment by azr** [comment]
Binaries can be found here : https://circleci.com/gh/hashicorp/packer/3184#artifacts/containers/0

**Comment by mrg2k8** [comment]
Enabling encryption by default (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html#encryption-by-default) in the console, with a custom KMS key and sharing the AMI normally (via ami_users) also achieves the same end result, with the benefit of the temporary instance also having the root volume encrypted.
