### ISSUE TITLE
PACKER CRASH - Azure - Windows Server 1803 - Panic, Segmentation Violation

### ISSUE THREAD

**Issue by simonjjones** [hashicorp/packer#7685]
We've experienced a one off crash in one of our packer builds for Windows Server 1803 in Azure with the note:

> !!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
>
> Packer crashed! This is always indicative of a bug within Packer.
> A crash log has been placed at "crash.log" relative to your current
> working directory. It would be immensely helpful if you could please
> report the crash with Packer[1] so that we can fix this.
>
> [1]: https://github.com/hashicorp/packer/issues
>
> !!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Just before the note there is a stack trace (included in build and crash logs below) that appears to point to an invalid pointer panic:

```
panic: runtime error: invalid memory address or nil pointer dereference
2019/05/24 05:22:12 packer: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x6a5066]
```

As this is not reproducible we don't expect to need a fix urgently, but thought you might like to know.

- Packer version from `packer version`
```
$ packer version
Packer v1.3.5
```
- Host platform
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.5 (stretch)
Release:        9.5
Codename:       stretch
```

Azure - Windows Server 1803

- Debug log output from `PACKER_LOG=1 packer build template.json`.
Build Log: https://gist.github.com/simonjjones/22a7ac4832a916294d95471504d4d1ce
Crash Log: https://gist.github.com/simonjjones/b5db60128e790d052d4251b1542ac8c9

- The _simplest example template and scripts_ needed to reproduce the bug.
This failure is not consistently reproducible

**Comment by SwampDragons** [comment]
Thanks for opening. I'll try to take a look when I can but it's definitely going to be hard to nail down without a consistent repro case.

**Comment by SwampDragons** [comment]
@simonjjones I think we've tracked down this bug. The patched build here should solve it https://circleci.com/gh/hashicorp/packer/21445#artifacts/containers/0; this comes from the PR linked above.
