### ISSUE TITLE
packer 1.4.1 not correctly copying/renaming AWS AMI in build region

### ISSUE THREAD

**Issue by geekofalltrades** [hashicorp/packer#7689]
- Packer version from `packer version`
  `Packer v1.4.1`

- Host platform
  Ubuntu 16.04

- Debug log output from `PACKER_LOG=1 packer build template.json`.
- The _simplest example template and scripts_ needed to reproduce the bug.
  https://gist.github.com/geekofalltrades/7784e1da998def1cb983f492aaa21d7b

The EBS builder in Packer 1.4.1 is missing the step to re-copy the AMI in the build region, resulting in the AMI being built in the build region with an incorrect name. The AMI is still named correctly in other non-build regions that the AMI is copied to.

Notice this in the 1.4.0 log:
```
==> amazon-ebs: Creating AMI tQI3F4g from instance i-0a98024b4b26777c9
    amazon-ebs: AMI: ami-051a94f0c62d93376
==> amazon-ebs: Waiting for AMI to become ready...
==> amazon-ebs: Copying AMI (ami-051a94f0c62d93376) to other regions...
    amazon-ebs: Copying to: us-east-1
    amazon-ebs: Copying to: us-west-2
    amazon-ebs: Waiting for all copies to complete...
```

While the 1.4.1 log looks like this:
```
==> amazon-ebs: Creating AMI vjRbhcX from instance i-06c3ef8c9dcad13c2
    amazon-ebs: AMI: ami-00d0a0dfa99699b9a
==> amazon-ebs: Waiting for AMI to become ready...
==> amazon-ebs: Copying/Encrypting AMI (ami-00d0a0dfa99699b9a) to other regions...
    amazon-ebs: Copying to: us-east-1
    amazon-ebs: Waiting for all copies to complete...
```

1.4.1 is not re-copying to the build region, causing the AMI to show up in this region with the name "vjRbhcX".

**Comment by SwampDragons** [comment]
I've opened PR #7691 to resolve this.

**Comment by todortanevski** [comment]
Exactly the same issue. Confirmed. Temporary name stuck. Fix/Workaround? 
Also - how to use this fix (if maked) on OS X - will it be available in brew fast?

**Comment by azr** [comment]
Hello there, binaries from @SwampDragons' aforementioned PR can be found here: https://circleci.com/gh/hashicorp/packer/2921#artifacts/containers/0 Please tell us wether it fixes the issue for you.

**Comment by todortanevski** [comment]
The fix is working - ami name is correctly applied!
Thanks for such a short notice!

Todor Tanevski
DevOps Engineer
Onica | AWS Premier Consulting Partner
onica.com
