### ISSUE TITLE
Feature: Automatically disable hibernation during local packing

### ISSUE THREAD

**Issue by mcandre** [hashicorp/packer#7695]
Some operating systems take so long to pack base boxes for, that local desktop/laptop hosts will enter hibernation mode partway through the build, resulting in a failed state. There are some tricks developers can do with packer configurations to offset this issue, but the unfortunate truth is that many operating systems were not designed for fast or automated installation. They can take several hours to install.

Some workarounds for the hibernation problem, include the Caffeine and Taurine applications, which can disable hibernation indefinitely or on a fixed schedule. Thus we ensure that packer builds can continue, uninterrupted, through the most sensitive `boot_command` phase, resulting in a working virtual machine image.

Caffeine (Windows)

https://www.zhornsoftware.co.uk/caffeine/

caffeine[-indicator] (Ubuntu)

https://launchpad.net/caffeine

Amphetamine (macOS)

https://itunes.apple.com/us/app/amphetamine/id937984704

Taurine (macOS)

https://itunes.apple.com/us/app/taurine/id960276676

While these utilities are helpful in their own right, I think it would be good for packer to include this behavior, automatically disabling hibernation during local packer builds. That way, our users get improved odds of success out of the box for many kinds of guests. What do you think?

**Comment by shantanugadgil** [comment]
just a thought: most media players also would be employing some OS level tricks to prevent sleep/screensaver, etc. :smile:

**Comment by SwampDragons** [comment]
I've been thinking on this one. I appreciate that this would be a nice improvement in your particular case, but ultimately I think it's the user's responsibility to make sure that their build computers aren't going to hibernate, shut down, or otherwise behave in ways that disrupt a build they're running.
