### ISSUE TITLE
AWS Spot Instance and Sysprep

### ISSUE THREAD

**Issue by mobee-pdufresne** [hashicorp/packer#7697]
Hi there

Im not sure if this is a Feature Request or a bug fix

it would appear that when using an AWS EBS backed Spot instance, when attempting to do a sysprep shutdown, instead of reading the stop signal it proceeds directly to the AMI creation step.  Might be due to the ephemeral nature of a Spot Instance and when calling one from packer the type of spot request is "instance". For creating AMI's using Spot Instance pricing for spot instances big advantage since the instances are short lived

The requirements are:

- For a Spot Instance request, the type must be persistent, not one-time. You cannot specify a launch group in the Spot Instance request.
- For a Spot Fleet request, the type must be maintain, not request.
- The root volume must be an EBS volume, not an instance store volume.

https://aws.amazon.com/about-aws/whats-new/2017/09/amazon-ec2-spot-can-now-stop-and-start-your-spot-instances/
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-interruptions.html

For spot instances, a stop command does not automatically issue a terminate command 

```
      "spot_price": "0.016",
      "subnet_id": "{{user `vpc_public_sn_id`}}",
    
==> amazon-ebs: Provisioning with Powershell...
==> amazon-ebs: Import Machine settings from registry.pol: C:\Windows\Temp\deploy\basepcidss3\DomainSysvol\GPO\Machine\                  registry.pol
==> amazon-ebs: Provisioning with powershell script: /tmp/powershell-provisioner643732709
    amazon-ebs: TaskPath                                       TaskName                          State
    amazon-ebs: --------                                       --------                          -----
    amazon-ebs: \                                              Amazon Ec2 Launch - Windows is... Ready
    amazon-ebs: \                                              Amazon Ec2 Launch - Instance I... Ready
==> amazon-ebs: Creating AMI test-hardened-windows-ami-2019-05-27-1836 from instance i-0557024d8f2289876
    amazon-ebs: AMI: ami-05a4fbdb31b666178
==> amazon-ebs: Waiting for AMI to become ready...
==> amazon-ebs: Adding tags to AMI (ami-05a4fbdb31b666178)...
==> amazon-ebs: Tagging snapshot: snap-0087288aae84d1264
```

JSON Snippet

```
    {
      "type": "windows-shell",
      "inline": ["powershell.exe -file c:\\Windows\\Temp\\deploy\\base.ps1"]
    },
      {
      "type": "powershell","inline": [
        "C:\\ProgramData\\Amazon\\EC2-Windows\\Launch\\Scripts\\SendWindowsIsReady.ps1 -Schedule",
        "C:\\ProgramData\\Amazon\\EC2-Windows\\Launch\\Scripts\\InitializeInstance.ps1 -Schedule",
        "C:\\ProgramData\\Amazon\\EC2-Windows\\Launch\\Scripts\\SysprepInstance.ps1 -NoShutdown"
      ]
    }]
```

**Comment by SwampDragons** [comment]
Have you set the https://www.packer.io/docs/builders/amazon-ebs.html#disable_stop_instance option to true?

**Comment by SwampDragons** [comment]
I suspect that the option I specified above will resolve this issue, so I am going to close for now -- if you try it out and it turns out not to solve your problem, we can reopen and dig in further. :)

**Comment by mobee-pdufresne** [comment]
Hi there,

this appears to be a limitation of AWS itself, even with a persistent Spot Instance, in the console I cannot choose to stop the instance, simply terminate. 

would have to look further into the stop VS terminate behavior of spot instances to see what can be done, if anything to use Spot Instances to pack and sysprep a windows image
