### ISSUE TITLE
Support for Softlayer CloudLayer

### ISSUE THREAD

**Issue by nodesocket** [hashicorp/packer#77]
Would love build support for Softlayer CloudLayer servers.

**Comment by kumarsenthil** [comment]
Hi leonidlem/chulkilee/mitchellh,

I have been trying to build packer softlayer plugin on CentOS 7. I have followed below steps:

**Comment by chulkilee** [comment]
@kumarsenthil  please report any issue on softlayer builder to https://github.com/leonidlm/packer-builder-softlayer

**Comment by kumarsenthil** [comment]
Thanks chulkilee. I have posted my issue and link is https://github.com/leonidlm/packer-builder-softlayer/issues/18. Please help me resolve this issue?
