### ISSUE TITLE
.HTTPIP variable doesn't reflect VM IP network changes

### ISSUE THREAD

**Issue by jojoob** [hashicorp/packer#7710]
This is the same issue as #320 but it was closed due to inactivity.

The .HTTPIP variable does not respect manual changes to the VM's network settings at least for the VirtualBox provisioner. 
I've used the vboxmanage attribute to change the nat network address range:

```
"vboxmanage": [["modifyvm", "{{.Name}}", "--natnet1", "192.168.0.0/24"]]
```

But the .HTTPIP variable still points to 10.0.2.2.

Packer 1.4.1
VirtualBox 6.0.8

**Comment by rickard-von-essen** [comment]
That is the correct behaviour. If you change the network you have to ensure that the VM can reach the http server.

**Comment by jojoob** [comment]
Ok, thank you for clarifying this. But then there should be a notice in the docs that .HTTPIP is hard coded.
