### ISSUE TITLE
User array variables to not recognize whitespace

### ISSUE THREAD

**Issue by MICHAELABICK** [hashicorp/packer#7716]
_This is a repost of the issue originally noted by @dilchenko in https://github.com/hashicorp/packer/issues/2278#issuecomment-430014552_

Packer Version: 1.4.1
Host OS: macOS 10.14.5 Beta

Comma separated user variables that contain whitespace like,
```
{
  "variables": {
    "array": "foo ,bar ,baz "
  },
  "builders": [
    {
      "array": "{{user `array`}}
    }
  ]
}
```
should evaluate equivalently (according to the [documentation](https://www.packer.io/docs/templates/user-variables.html#using-array-values)) to,
```
{
  "builders": [
    {
      "array": [
        "foo ",
        "bar ",
        "baz "
      ]
    }
  ]
}
```
but instead evaluate equivalently to,
```
{
  "builders": [
    {
      "array": "foo ,bar ,baz "
    }
  ]
}
```

**Comment by SwampDragons** [comment]
Thanks for reporting. I'll take a look and see if there's a tweak we can do to make this work as expected.

**Comment by azr** [comment]
I've been trying to look at the code doing the split and I suspect it's this one:

https://github.com/hashicorp/packer/blob/e96409954aefb69f267cca744a74b2d4d5be3057/helper/config/decode.go#L32

https://github.com/hashicorp/packer/blob/dbf5d52c43bfe83bbd3a6fc05b4e41032d407cf1/vendor/github.com/mitchellh/mapstructure/decode_hooks.go#L79-L97

This should be triggered if the receiving type is a slice of string.
Looking at the code: the spaces should not be trimmed and nothing else than the split should happen.

So we need a more precise informations on what builder/field you are trying to use.

---

That said the original error was happening on a chef `run_list` field https://github.com/hashicorp/packer/issues/2278#issuecomment-135585464 

You can see it here: 
https://github.com/hashicorp/packer/blob/85b8a654b0f9e8e569cb0a5c90dcc3beb1c4253e/provisioner/chef-client/provisioner.go#L67

I added this test: 
```
func TestProvisionerPrepare_RunList(t *testing.T) {
	var p Provisioner 

	config := testConfig()
	config["run_list"] = "run , list"

	err := p.Prepare(config)
	if err != nil {
		t.Fatalf("err: %s", err)
	}

	if diff :=  cmp.Diff(p.config.RunList , []string{"run ", " list"}) ;diff !=""{
		t.Fatalf("unexpected: %s", diff)
	} 
}
```

to the codebase and all seems to be okay.

**Comment by azr** [comment]
I think this issue can be closed, to check wether your field is an array of strings, please go in the packer documentation, the array type should be in between parenthesis.

Example: `run_list (array of strings) - : https://www.packer.io/docs/provisioners/chef-client.html#run_list

If the receiving type is an array of strings then using a string with commas in it will generate an array of strings.
