### ISSUE TITLE
VirtualBox variable interpolation

### ISSUE THREAD

**Issue by ktmorgan** [hashicorp/packer#7717]
`packer version`: v1.4.1
`host operating system`: CentOS 7.6 x64 (3.10.0-957.12.2.el7.x86_64)
`VirtualBox version`: 6.0.8 r130520 (Qt5.6.1)

At a glance it appears that the interpolation of variables within a variable (add in https://github.com/hashicorp/packer/pull/7390), is not honored within the virtualbox-iso builder. I've tested this with the vmware-iso builder and it seems to work. Also I generated a quick test using the null builder to verify.

**vb.json**
```
{
  "builders": [
    {
      "boot_command": [
        "<up><wait><tab><wait> ks=http://{{.HTTPIP}}:{{.HTTPPort}}/centos-7.6-x86_64.kickstart.cfg<enter>"
      ],
      "boot_wait": "5s",
      "guest_additions_mode": "disable",
      "guest_os_type": "RedHat_64",
      "headless": true,
      "http_directory": "http",
      "iso_checksum_type": "none",
      "iso_url": "centos-7.6-x86_64.iso",
      "shutdown_command": "echo 'packer' | sudo -S /sbin/halt -h -p",
      "ssh_password": "password",
      "ssh_timeout": "25m",
      "ssh_username": "root",
      "type": "virtualbox-iso",
      "vm_name": "{{user `name`}}"
    }
  ]
}
```

**templates/base-test.json**
```
{
  "name": "base-{{user `operating_system`}}-{{split uuid \"-\" 4}}"
}
```

**operating-systems/centos-7.6-x86_64-test.json**
```
{
  "operating_system": "centos-7.6-x86_64"
}
```
Running this command results in the screenshot below:
`packer build -var-file=operating-systems/centos-7.6-x86_64-test.json -var-file=templates/base-test.json vb.json`

![image](https://user-images.githubusercontent.com/14634953/58987967-409f1880-87a6-11e9-8e09-cb5cecae5107.png)

Null builder test case:

**test.json**
```
{
  "builders": [
    {
      "ssh_host": "127.0.0.1",
      "ssh_password": "{{user `ssh_password`}}",
      "ssh_username": "{{user `ssh_username`}}",
      "type": "null"
    }
  ],
  "provisioners": [
    {
      "command": "echo {{user `name`}}",
      "type": "shell-local"
    }
  ],
  "variables": {
    "ssh_password": "{{env `SSH_PASSWORD`}}",
    "ssh_username": "{{env `SSH_USERNAME`}}"
  }
}
```

Running the following command `packer build -var-file=operating-systems/centos-7.6-x86_64-test.json -var-file=templates/base-test.json test.json` results in:

```
null output will be in this color.

==> null: Using ssh communicator to connect: 127.0.0.1
==> null: Waiting for SSH to become available...
==> null: Connected to SSH!
==> null: Running local shell script: /tmp/packer-shell440897968
    null: base-centos-7.6-x86_64-c80724bd94ee
Build 'null' finished.

==> Builds finished. The artifacts of successful builds are:
--> null: Did not export anything. This is the null builder
```

I have ran many other tests including using the `variables` stanza in the vb.json file to try and get this variable to be correctly interpolated.

**Comment by SwampDragons** [comment]
Thanks for the detailed bug report!  It turns out that when we implemented this, we didn't do so for var-files and command-line passed vars, just for vars defined within the template itself. I'm tagging this as a bug to fix for the next release.

**Comment by ktmorgan** [comment]
Well the null builder test case I posted does use the same var-files as the virtualbox-iso builder and it seemed to interpret them correctly, so that is quite odd!

**Comment by SwampDragons** [comment]
That turns out to be a fluke of luck. You're printing from the command option, which doesn't get interpolated until later, when everything has been read in already.

**Comment by SwampDragons** [comment]
(which is also why I didn't catch this when writing the feature -- I only tested by echoing the variables via the command option!!)

**Comment by SwampDragons** [comment]
I've made a PR to fix this, and binaries are available (here)[https://circleci.com/gh/hashicorp/packer/3996#artifacts/containers/0].  I'd love it if you could try it out and verify it works for you.

**Comment by ktmorgan** [comment]
I just re-ran the VirtualBox test case listed above with the provided binary and can confirm that this indeed resolved the variable interpolation issue. Thanks for the quick turn around on this one.
