### ISSUE TITLE
openstack image metadata not availabe for with use_blockstorage_volume

### ISSUE THREAD

**Issue by xinau** [hashicorp/packer#7721]
packer version 1.4.1

when setting [metadata](https://www.packer.io/docs/builders/openstack.html#metadata) for the openstack builder and setting [use_blockstorage_volume](https://www.packer.io/docs/builders/openstack.html#use_blockstorage_volume) no metadata is set on the image. this happens due to the following if else statement https://github.com/hashicorp/packer/blob/master/builder/openstack/step_create_image.go#L48
where the image metadata is only provided to `servers.CreateImage`, but not to `volumeactions.UploadImage`

**Comment by psinghal20** [comment]
@SwampDragons @xinau I would like to work on this issue if it is up for grab. I guess just adding the metadata in opts for `volumeactions.UploadImage` should solve it, right?

**Comment by rickard-von-essen** [comment]
Doesn't look like [`volumeactions.UploadImage`](https://github.com/gophercloud/gophercloud/blob/master/openstack/blockstorage/extensions/volumeactions/requests.go#L232-L244) takes any metadata.

**Comment by psinghal20** [comment]
@rickard-von-essen sorry, I confused the `UploadImageOpts` with something else. Yes, the `volumeactions.UploadImage` doesn't support the adding metadata but I think there is an OpenStack API to set [image metadata for a volume](https://developer.openstack.org/api-ref/block-storage/v3/index.html?expanded=set-image-metadata-for-a-volume-detail,upload-volume-to-image-detail#set-image-metadata-for-a-volume). Maybe we should raise an issue on the [gophercloud repo](https://github.com/gophercloud/gophercloud) to add support for this API call.

**Comment by SwampDragons** [comment]
Sounds like a good idea. I'm happy to have you take on this issue .  :)

**Comment by psinghal20** [comment]
@rickard-von-essen @SwampDragons I have raised a PR [#1610](https://github.com/gophercloud/gophercloud/issues/1610) for the same on the gophercloud repo. Hopefully it will merge soon, after that I will make the required changes here.
