### ISSUE TITLE
Support Elastic Fabric Adapter in AWS builders

### ISSUE THREAD

**Issue by ChrisDowning** [hashicorp/packer#7722]
[Elastic Fabric Adapter (EFA)](https://aws.amazon.com/blogs/aws/now-available-elastic-fabric-adapter-efa-for-tightly-coupled-hpc-workloads/) is a new type of network interface available to a subset of AWS instances, targeted at low-latency communications. More details [here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa.html#efa-limits).

Supporting the creation of EFA-equipped instances would be very beneficial to users of scientific computing in AWS.

While a user could currently use any appropriate Packer-generated AMI to create an instance and attach an EFA to it during launch, using EFA for low-latency communications requires the installation of additional drivers, described [here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa-start.html). Having EFA-equipped instances as an option in Packer would allow the drivers to be baked into the AMI.

**Comment by rickard-von-essen** [comment]
Do you really need to have a EFA interface to install the driver?

**Comment by ChrisDowning** [comment]
Apologies; just tested again and you guessed right that the drivers install fine without and EFA interface attached. I was mis-remembering an error message, actually all the driver does if no EFA is present is skip the post-install tests.
