### ISSUE TITLE
The ssh communicator documentation is wrong about supported ciphers.

### ISSUE THREAD

**Issue by amaczuga** [hashicorp/packer#7723]
Packer version:  1.4.1
Host platform: Ubuntu bionic

As there is no config parameter allowing to override vendor/golang.org/x/crypto/ssh/common.go preferredCiphers,
the builder ssh handshake will always use preferredCiphers, instead of supportedCiphers. I realize fixing the documentation
would be the easier path, but I would love to have an option to override ssh client cipher suite. Pretty please : )

**Comment by rickard-von-essen** [comment]
I guess it would make sense to allow this be specified in the template. Is there any particular case where this would help you?

**Comment by amaczuga** [comment]
I'm working on CentOS 3.9 image. The only cipher matching packer with the ancient OpenSSH version is arcfour and It would be a great help for me if I could use it for provisioning the image. I also expect to hit the same issue with KexAlgo selection.

**Comment by SwampDragons** [comment]
Related to #8450
