### ISSUE TITLE
Windows-restart provisioner error 1717

### ISSUE THREAD

**Issue by mginster** [hashicorp/packer#7725]
- Packer version 1.4.0
- Windows 10 1703
- Using SSH

[packerlog.txt](https://github.com/hashicorp/packer/files/3262415/packerlog.txt)

When running the windows-restart provisioner it does restart the system but immediately starts throwing 1717 errors repeated.  After 5 minutes it times out and the step fails.  The machine actually does restart.

**Comment by SwampDragons** [comment]
Thanks for opening an issue -- to help you, we really do need the things requested in the issue template: 

- Full debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a gist https://gist.github.com
- The _simplest complete example template and scripts_ needed to reproduce the bug.
  Include these in your gist https://gist.github.com

**Comment by mginster** [comment]
https://gist.github.com/mginster/dc31d5c63b911dcdd6ab8c3525edbd65

**Comment by mginster** [comment]
Doubt you needed the autounattend, but included it anyway.

**Comment by SwampDragons** [comment]
I'm glad to know that this was a firewall issue -- I'll see if I can document it in our windows troubleshooting guide.
