### ISSUE TITLE
Issue with running PowerShell inline script with elevated privileges

### ISSUE THREAD

**Issue by easkerov** [hashicorp/packer#7729]
Hello,

I am trying to provision Windows 10 (Pro N) VM image in Microsoft Azure and encountered with issue related to running PowerShell script with elevated privileges.  I've embedded inline script which installs Azure RM modules, but it should be executed with elevated privs. Documentation states that in order to do that I need to add **elevated_user** and **elevated_password** parameter.  Everything goes smoothly until Packer tries to execute inline script. I am getting strange errors (detailed logs provided  below) and Packer image provisioning process stops. Template file is provided below. Is it correct way to run script with elevated privs or am I doing something wrong or is it a bug?

**- Packer version 1.4.1**
**- Host platform: Windows 10** 
**- Packer Template:** 
`{
    "variables": {
        "azure_region": "West Europe",
        "azure_image_publisher": "MicrosoftWindowsDesktop",
        "azure_image_offer": "Windows-10",
        "azure_image_sku": "rs5-pron",
        "azure_resource_group": "Test-RG",
        "azure_vm_size": "Standard_D2s_v3"
      },
    "builders": [{
      "type": "azure-arm",
  
      "client_id": "{{user `azure_client_id`}}",
      "client_secret": "{{user `azure_client_secret`}}",
      "tenant_id": "{{user `azure_tenant_id`}}",
      "subscription_id": "{{user `azure_subscription_id`}}",
  
      "managed_image_resource_group_name": "{{user `azure_resource_group`}}",
      "managed_image_name": "{{user `azure_image_offer` | lower}}-{{user `azure_image_sku` | lower}}-{{isotime \"02Jan2006_1504\"}}",
  
      "os_type": "Windows",
      "image_publisher": "{{user `azure_image_publisher`}}",
      "image_offer": "{{user `azure_image_offer`}}",
      "image_sku": "{{user `azure_image_sku`}}",
  
      "communicator": "winrm",
      "winrm_use_ssl": true,
      "winrm_insecure": true,
      "winrm_timeout": "5m",
      "winrm_username": "packer",
    
      "location": "{{user `azure_region`}}",
      "vm_size": "{{user `azure_vm_size`}}"
    }],
    "provisioners": [{
      "type": "powershell",
      "elevated_user": "Administrator",
      "elevated_password": "{{.WinRMPassword}}",
      "inline": [
        "Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope LocalMachine -Force",
        "Install-PackageProvider -Name Nuget -MinimumVersion 2.8.5.201 -Force",
        "Set-PSRepository -Name 'PSGallery' -InstallationPolicy Trusted",
        "Install-Module -Name Az",
        "Import-Module Az",
        "& $env:SystemRoot\\System32\\Sysprep\\Sysprep.exe /oobe /generalize /quiet /quit",
        "while($true) { $imageState = Get-ItemProperty HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Setup\\State | Select ImageState; if($imageState.ImageState -ne 'IMAGE_STATE_GENERALIZE_RESEAL_TO_OOBE') { Write-Output $imageState.ImageState; Start-Sleep -s 10  } else { break } }"
      ]
    }]
  }`
  
**Debug Log:**

`...
2019/06/07 18:38:13 packer.exe: #< CLIXML
2019/06/07 18:38:14 packer.exe: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>#< CLIXML
2019/06/07 18:38:14 packer.exe: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>2019/06/07 18:38:14 [INFO] starting remote command: powershell -executionpolicy bypass -file "C:/Windows/Temp/packer-elevated-shell-5cfa92ee-dc1f-31fe-2444-c8f2564fc49a.ps1"
2019/06/07 18:38:16 ui error: ==> azure-arm: (12,8):UserId:
==> azure-arm: (12,8):UserId:
2019/06/07 18:38:16 ui error: ==> azure-arm: At C:\Windows\Temp\packer-elevated-shell-5cfa92ee-dc1f-31fe-2444-c8f2564fc49a.ps1:60 char:1
==> azure-arm: At C:\Windows\Temp\packer-elevated-shell-5cfa92ee-dc1f-31fe-2444-c8f2564fc49a.ps1:60 char:1
2019/06/07 18:38:16 ui error: ==> azure-arm: + $f.RegisterTaskDefinition($name, $t, 6, "Administrator", $password, $ ...
==> azure-arm: + $f.RegisterTaskDefinition($name, $t, 6, "Administrator", $password, $ ...
2019/06/07 18:38:16 ui error: ==> azure-arm: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> azure-arm: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2019/06/07 18:38:16 ui error: ==> azure-arm:     + CategoryInfo          : OperationStopped: (:) [], COMException
==> azure-arm:     + CategoryInfo          : OperationStopped: (:) [], COMException
2019/06/07 18:38:16 ui error: ==> azure-arm:     + FullyQualifiedErrorId : System.Runtime.InteropServices.COMException
==> azure-arm:     + FullyQualifiedErrorId : System.Runtime.InteropServices.COMException
2019/06/07 18:38:16 ui error: ==> azure-arm:
==> azure-arm:
2019/06/07 18:38:16 ui error: ==> azure-arm: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
==> azure-arm: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
2019/06/07 18:38:16 ui error: ==> azure-arm: At C:\Windows\Temp\packer-elevated-shell-5cfa92ee-dc1f-31fe-2444-c8f2564fc49a.ps1:61 char:1
==> azure-arm: At C:\Windows\Temp\packer-elevated-shell-5cfa92ee-dc1f-31fe-2444-c8f2564fc49a.ps1:61 char:1
2019/06/07 18:38:16 ui error: ==> azure-arm: + $t = $f.GetTask("\$name")
==> azure-arm: + $t = $f.GetTask("\$name")
2019/06/07 18:38:16 ui error: ==> azure-arm: + ~~~~~~~~~~~~~~~~~~~~~~~~~
==> azure-arm: + ~~~~~~~~~~~~~~~~~~~~~~~~~
2019/06/07 18:38:16 ui error: ==> azure-arm:     + CategoryInfo          : OperationStopped: (:) [], FileNotFoundException
==> azure-arm:     + CategoryInfo          : OperationStopped: (:) [], FileNotFoundException
2019/06/07 18:38:16 ui error: ==> azure-arm:     + FullyQualifiedErrorId : System.IO.FileNotFoundException
==> azure-arm:     + FullyQualifiedErrorId : System.IO.FileNotFoundException
2019/06/07 18:38:16 ui error: ==> azure-arm:
==> azure-arm:
2019/06/07 18:38:16 ui error: ==> azure-arm: Method invocation failed because [System.__ComObject] does not contain a method named 'Run'.
==> azure-arm: Method invocation failed because [System.__ComObject] does not contain a method named 'Run'.
2019/06/07 18:38:16 ui error: ==> azure-arm: At C:\Windows\Temp\packer-elevated-shell-5cfa92ee-dc1f-31fe-2444-c8f2564fc49a.ps1:62 char:1
==> azure-arm: At C:\Windows\Temp\packer-elevated-shell-5cfa92ee-dc1f-31fe-2444-c8f2564fc49a.ps1:62 char:1
2019/06/07 18:38:16 ui error: ==> azure-arm: + $t.Run($null) | Out-Null
==> azure-arm: + $t.Run($null) | Out-Null
2019/06/07 18:38:16 ui error: ==> azure-arm: + ~~~~~~~~~~~~~~~~~~~~~~~~
==> azure-arm: + ~~~~~~~~~~~~~~~~~~~~~~~~
2019/06/07 18:38:16 ui error: ==> azure-arm:     + CategoryInfo          : InvalidOperation: (Run:String) [], RuntimeException
==> azure-arm:     + CategoryInfo          : InvalidOperation: (Run:String) [], RuntimeException
2019/06/07 18:38:16 ui error: ==> azure-arm:     + FullyQualifiedErrorId : MethodNotFound
==> azure-arm:     + FullyQualifiedErrorId : MethodNotFound
2019/06/07 18:38:16 ui error: ==> azure-arm:
==> azure-arm:`

**Comment by SwampDragons** [comment]
Hi!  Thanks for reaching out.  

The first thing I'm noticing is that your elevated user and your winrm username are not the same user -- the auto-generated password {{.WinRMPassword}} works for the "packer" user, not the Administrator one, unless you've called another script somewhere else to set this password for your Administrator user. Try changing your elevated_user to `"elevated_user": "packer",` instead of Administrator and I think it'll work for you. Alternatively, make sure that the password you're providing is one you've set for your Administrator user.

Since this is a usage question and not a bug or feature request, I'm going to guide you to our [mailing list](https://groups.google.com/forum/#!forum/packer-tool), where there are lot more eyeballs than just the maintainers', ready to help you get going.  Reach out there if my suggestion above doesn't work.  Thanks!

**Comment by easkerov** [comment]
Dear @SwampDragons ,

Thank you for reply. I've tried the workaround you've suggested, and indeed, I do not get any errors anymore, however Packer simply hangs now during Powershell script execution. Following you advice I've posted the new topic in the mailing list here: https://groups.google.com/forum/#!topic/packer-tool/6ToKPlCpsxM

**Comment by Mishu** [comment]
I have the same issue with the hang, when using `elevated_user` and password... This is not fixed!
I'm trying to install .net 3.5 feature and it hangs, if I run the command without `elevated_user` I get `Access denied`...
