### ISSUE TITLE
hyper-v from vmcx compare fails

### ISSUE THREAD

**Issue by Kmdkca** [hashicorp/packer#7748]
Packer version: 1.4.1
Host: Win 10
I've created a VM from an ISO. works fine.
But when I try to create a vm from the above VMCX file I get some erros about null or empty arguments.
I am able to import the vmcx file manually in hyper-v.
Builder:
"builders": [
      {
        "type": "hyperv-vmcx",
        "clone_from_vmcx_path": "{{ user `VMcxFolder`}}",
        "output_directory": "./{{ user `vm_name`}}",
        "vm_name": "{{ user `vm_name` }}",
        "communicator": "winrm",
        "winrm_username": "{{ user `install_user`}}",
        "winrm_password": "{{ user `install_password`}}",
        "winrm_timeout": "12h",
        "shutdown_command": "C:/Windows/packer/PackerShutdown.bat",
        "shutdown_timeout": "1h",
        "cpus": 1,
        "memory": 4096,
        "generation": 1,
        "boot_wait": "0s",
        "boot_command": [
          "a<wait>a<wait>a"
        ]
      }

Errors:
hyperv-vmcx: Creating build directory...
hyperv-vmcx: Creating switch 'External VM Switch' if required...
hyperv-vmcx:     switch 'External VM Switch' already exists. Will not delete on cleanup...
hyperv-vmcx: Cloning virtual machine...
hyperv-vmcx: Error cloning virtual machine: PowerShell error: Hyper-V\Compare-VM : The virtual machine configuration could might be corrupt or not valid.
hyperv-vmcx: The virtual machine configuration could not be read. The data might be corrupt or not valid.
hyperv-vmcx: At C:\Users\xxx\AppData\Local\Temp\powershell601264270.ps1:34 char:24
hyperv-vmcx: + ... ityReport = Hyper-V\Compare-VM -Path $VirtualMachinePath -VirtualMach ...
hyperv-vmcx: +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
hyperv-vmcx:     + CategoryInfo          : NotSpecified: (:) [Compare-VM], VirtualizationException
hyperv-vmcx:     + FullyQualifiedErrorId : OperationFailed,Microsoft.HyperV.PowerShell.Commands.CompareVM
hyperv-vmcx:
hyperv-vmcx: Set-VMMemory : Cannot validate argument on parameter 'VM'. The argument is null or empty. Provide an argument that is n
hyperv-vmcx: ot null or empty, and then try the command again.
hyperv-vmcx: At C:\Users\xxx\AppData\Local\Temp\powershell601264270.ps1:44 char:26
hyperv-vmcx: + Hyper-V\Set-VMMemory -VM $compatibilityReport.VM -StartupBytes $memor ...
hyperv-vmcx: +                          ~~~~~~~~~~~~~~~~~~~~~~~
hyperv-vmcx:     + CategoryInfo          : InvalidData: (:) [Set-VMMemory], ParameterBindingValidationException
hyperv-vmcx:     + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.HyperV.PowerShell.Commands.SetVMMemory
hyperv-vmcx:
hyperv-vmcx: Disconnect-VMNetworkAdapter : Cannot bind argument to parameter 'VMNetworkAdapter' because it is null.
hyperv-vmcx: At C:\Users\xxx\AppData\Local\Temp\powershell601264270.ps1:46 char:55
hyperv-vmcx: + Hyper-V\Disconnect-VMNetworkAdapter -VMNetworkAdapter $networkAdaptor
hyperv-vmcx: +                                                       ~~~~~~~~~~~~~~~
hyperv-vmcx:     + CategoryInfo          : InvalidData: (:) [Disconnect-VMNetworkAdapter], ParameterBindingValidationException
hyperv-vmcx:     + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.HyperV.PowerShell.Commands.Disc
hyperv-vmcx:    onnectVMNetworkAdapter
hyperv-vmcx:
hyperv-vmcx: Connect-VMNetworkAdapter : Cannot validate argument on parameter 'VMNetworkAdapter'. The argument is null or empty. Pro
hyperv-vmcx: vide an argument that is not null or empty, and then try the command again.
hyperv-vmcx: At C:\Users\xxx\AppData\Local\Temp\powershell601264270.ps1:47 char:52
hyperv-vmcx: + ... -V\Connect-VMNetworkAdapter -VMNetworkAdapter $networkAdaptor -Switch ...
hyperv-vmcx: +                                                   ~~~~~~~~~~~~~~~
hyperv-vmcx:     + CategoryInfo          : InvalidData: (:) [Connect-VMNetworkAdapter], ParameterBindingValidationException
hyperv-vmcx:     + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.HyperV.PowerShell.Commands.ConnectVMNetworkAd
hyperv-vmcx:    apter
hyperv-vmcx:
hyperv-vmcx: Import-VM : Cannot bind argument to parameter 'CompatibilityReport' because it is null.
hyperv-vmcx: At C:\Users\xxx\AppData\Local\Temp\powershell601264270.ps1:48 char:46
hyperv-vmcx: + $vm = Hyper-V\Import-VM -CompatibilityReport $compatibilityReport
hyperv-vmcx: +                                              ~~~~~~~~~~~~~~~~~~~~
hyperv-vmcx:     + CategoryInfo          : InvalidData: (:) [Import-VM], ParameterBindingValidationException
hyperv-vmcx:     + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.HyperV.PowerShell.Commands.Impo
hyperv-vmcx:    rtVM
hyperv-vmcx: Unregistering and deleting virtual machine...
hyperv-vmcx: Error deleting virtual machine: PowerShell error: Hyper-V\Get-VM : Hyper-V was unable to find a virtual machine with name "ws2016std-VMcx".
hyperv-vmcx: At C:\Users\xxx\AppData\Local\Temp\powershell388178069.ps1:4 char:7
hyperv-vmcx: + $vm = Hyper-V\Get-VM -Name $vmName
hyperv-vmcx: +       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
hyperv-vmcx:     + CategoryInfo          : InvalidArgument: (ws2016std-VMcx:String) [Get-VM], VirtualizationException
hyperv-vmcx:     + FullyQualifiedErrorId : InvalidParameter,Microsoft.HyperV.PowerShell.Commands.GetVM
hyperv-vmcx:
hyperv-vmcx: Stop-VM : Cannot validate argument on parameter 'VM'. The argument is null or empty. Provide an argument that is not nu
hyperv-vmcx: ll or empty, and then try the command again.
hyperv-vmcx: At C:\Users\xxx\AppData\Local\Temp\powershell388178069.ps1:6 char:25
hyperv-vmcx: +     Hyper-V\Stop-VM -VM $vm -TurnOff -Force -Confirm:$false
hyperv-vmcx: +                         ~~~
hyperv-vmcx:     + CategoryInfo          : InvalidData: (:) [Stop-VM], ParameterBindingValidationException
hyperv-vmcx:     + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.HyperV.PowerShell.Commands.StopVM
hyperv-vmcx:
hyperv-vmcx: Hyper-V\Remove-VM : Hyper-V was unable to find a virtual machine with name "ws2016std-VMcx".
hyperv-vmcx: At C:\Users\xxx\AppData\Local\Temp\powershell388178069.ps1:9 char:1
hyperv-vmcx: + Hyper-V\Remove-VM -Name $vmName -Force -Confirm:$false
hyperv-vmcx: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
hyperv-vmcx:     + CategoryInfo          : ObjectNotFound: (:) [Remove-VM], VirtualizationException
hyperv-vmcx:     + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.RemoveVM
hyperv-vmcx: Deleting output directory...
hyperv-vmcx: Deleting build directory...
Build 'hyperv-vmcx' errored: Error cloning virtual machine: PowerShell error: Hyper-V\Compare-VM : The virtual machine configuration could might be corrupt or not valid.

**Comment by SwampDragons** [comment]
How are you referencing the VM folder?  A valid example is :

`"clone_from_vmcx_path": "C:\\Users\\vagrant\\Desktop\\output-hyperv-iso",`

If you're trying to point to the vmcx file itself, or the `Virtual Machines` or `Virtual Hard Disks` folders inside of your output folder, you may have issues.

**Comment by Kmdkca** [comment]
"Clone_from_vmcx_path": ".\ws2016std-base\Virtual Machines" which is the output folder of my hyperv-iso builder. I've also tried with a full path to be sure the relative path is not causing issues

**Comment by SwampDragons** [comment]
Try just 
`"Clone_from_vmcx_path": ".\ws2016std-base"`

**Comment by Kmdkca** [comment]
Thanks for great help. That worked. 
The variable name/documentation is misleading as it says it is the path to the vmcx file. And perhaps a better error message.

**Comment by SwampDragons** [comment]
Yes, I agree. Now that we know it worked for you with that change, I will fix the documentation.

**Comment by SwampDragons** [comment]
this was closed by #7790
