### ISSUE TITLE
SSH Credentials Settings don't work on a virtualbox provider with vagrant type

### ISSUE THREAD

**Issue by marcosdiez** [hashicorp/packer#7758]
Whenever one is using `packer` with the `virtualbox` `provider` and the `vagrant` `type`, some (or all ?) ssh settings are ignored.

I can confirm that the followng are being ignored:

- `ssh_username` (string)
- `ssh_password` (string)

The proof that it's being ignored is that if I open VirtualBox on the unix machine that packer created though vagrant and check the logs, it says "invalid login attempt from user `vagrant`"

Here is what I have:

- Vagrant 2.2.4
- Packer v1.4.1
- Microsoft Windows [Version 10.0.18362.175] (Windows 10 / 2019H1 ) (host)
- Ubuntu 18.04.2 (target)

- Minimal packer file (source path can be any vagrant box without the `packer` user
```
{
    "builders": [{
        "communicator": "ssh",
        "source_path": "file://c:/tmp/x/m360k8s_step1.box",
        "provider": "virtualbox",
        "add_force": true,
        "type": "vagrant",
        "output_dir": "c:/tmp/x/step2",
        //  this is the workaround to make things work
        // "template": "m360k8s_vagrant_vagrantfile",
        "ssh_username": "ubuntu",
        "ssh_password": "ubuntu"
    }],
    "provisioners": [
        {
            "type": "shell",
            "timeout": "6000m",
            "inline": [
                "echo testing...."
            ]
        }
    ],
    "post-processors": [
        {
            "type": "manifest"
        }
    ]
}
```

The workaround for this issue is to create my own vagrantfile template:

```
Vagrant.configure("2") do |config|
  config.vm.box = "{{.BoxName}}"
  {{ if ne .SyncedFolder "" -}}
  		config.vm.synced_folder "{{.SyncedFolder}}", "/vagrant"
  {{- else -}}
  		config.vm.synced_folder ".", "/vagrant", disabled: true
  {{- end}}
        config.ssh.username = "ubuntu"
        config.ssh.password = "ubuntu"
end
```

**Comment by SwampDragons** [comment]
Did the ubuntu username and password exist on the box before you launched it using Packer?  i.e. if you launch the Vagrant box without 

        config.ssh.username = "ubuntu"
        config.ssh.password = "ubuntu"

in the Vagrantfile, and try to SSH into it, what happens?

**Comment by marcosdiez** [comment]
Yes, one can at any time log into that box with the ubuntu/ubuntu credentials.
it works via SSH and it works if one opens it directly in virtualbox, through the emulated console.

that's how I could tail the log file inside of /var/log and see SSH complaining that there were attempts of logins from the `vagrant` user.

**Comment by SwampDragons** [comment]
Well that's definitely not right. I'll try to repro today.

**Comment by SwampDragons** [comment]
Yeah, okay, when I implemented this I assumed you'd always want to use the details stored within `vagrant ssh-config`; I'll need to set it up so that if you set the values in the packer config it'll override them.

**Comment by marcosdiez** [comment]
Thanks for the quickl feedback.

That being said, I am *not* sure the change is worth it.

I, who reported the issue, was happy with my workaround and I am now even happier using the `virtualbox-ovf` builder/type.

So unless you believe many people are affeced by this, maybe just updating the documentation and telling the person to use the custom vagrant file is enough.

Just some story on how I got there...

I am builing a (at least) 3 hours image that is giving me a lot of trouble (nothing packer related).
The input is an ISO (virtualbox-iso), the output is a virtualbox vagrant file.

Hence I decided to break my process in 3 steps so I could iterate faster, since every successful step would not have to be done again.

Hence I realized that using `virtualbox-ovf` as the intermediary format between the steps is the way to go.









it does wo

**Comment by SwampDragons** [comment]
Yeah, that process sounds like virtualbox-iso + virtualbox-ovf + the vagrant post-processor are a more appropriate pipeline. 

I definitely need to better document the ssh settings since it's not the same as the other builders. I think I probably still do want to allow users to override the username/password/key files, but I'll make it clear it's optional.

**Comment by mdiez-modus** [comment]
Thank you for fixing this

**Comment by HildyGildy** [comment]
I'm a little confused here. I'm trying to use ssh_username and ssh_password in my json, but a `%(whoami)` in the machine says I am root. So it's ignoring ssh_username. I'd rather override it that way, but I have to use a template ok; however if that's the case, what variable do you use in the template to access the username and password variables? I add the ssh_username in the json, but I pass the password in when I call packer with `-var ssh_password=<my password>`, and then use `"ssh_password": "{{user `ssh_password`}}"` in the json.

Note, this will never pass our code review if the password is hard-coded in the template or json, so that's why I cant do it as @marcosdiez has above.

**Comment by SwampDragons** [comment]
Did you also set the ssh_username?

**Comment by HildyGildy** [comment]
Yes, the json is like so:

`{
  "builders": [
    {
      "communicator": "ssh",
      "ssh_username": "{{user `ssh_username`}}",
      "ssh_password": "{{user `ssh_password`}}",
      "ssh_pty": "true",
      "ssh_timeout": "1h",
      "source_path": "dd-centos-7-base",
      "provider": "vmware_desktop",
      "type": "vagrant",
      "name": "centos_geoserver",
      "teardown_method": "destroy",
      "skip_add": true
    }
  ],
  "provisioners": [
    {
      "type": "shell",
      "execute_command": "echo '{{user `ssh_password`}}' | {{.Vars}} sudo -S -E sh -eux '{{.Path}}'",
      "inline": [
        "mkdir /gis_worker",
        "mkdir /gis_worker/geoserver",
        "mkdir /gis_worker/geoserver/run",
        "mkdir /gis_worker/geoserver/copy",
        "chown -R sed-admin /gis_worker"
      ]
    },
    {
      "type": "file",
      "source": "../../../gis_workers/geoserver/",
      "destination": "/gis_worker/geoserver/copy"
    },
    {
      "type": "file",
      "source": "../../../gis_workers/geoserver/",
      "destination": "/gis_worker/geoserver/run"
    },
    {
      "type": "shell",
      "execute_command": "echo '{{user `ssh_password`}}' | {{.Vars}} sudo -S -E sh -eux '{{.Path}}'",
      "scripts": [
        "./scripts/configure-server.sh"
      ]
    }
  ],
  "variables": {
    "ssh_username": "sed-admin"
  }
}`

**Comment by HildyGildy** [comment]
Ok...so this was user error.
The output of the following two commands is `root` and `my ssh_username`

````
{
      "type": "shell",
      "execute_command": "echo '{{user `ssh_password`}}' | {{.Vars}} sudo -S -E sh -eux '{{.Path}}'",
      "inline": [
        "echo $(whoami)"
      ]
    },
    {
      "type": "shell",
      "inline": [
        "echo $(whoami)"
      ]
    },
````
