### ISSUE TITLE
Feature: auto-load var files

### ISSUE THREAD

**Issue by evansj** [hashicorp/packer#7761]
There is a really nice feature in terrafom where it will automatically load `terraform.tfvars` and any `*.auto.tfvars` files without you having to specify `-var-file=foo.tfvars` on the command line.

My feature request is for a similar feature in packer, so for example I could create a file containing a var definition with a list of AWS account ids and regions:

`sharing.auto.json`
```json
{
      "destination_regions": "us-east-1,eu-west-1",
      "destination_accounts": "12345678,23456789",
}
```

which I could pick up from any of the packer json files in the same directory:

`ami_one.json`
```json
{
  "builders": [
    {
      "type": "amazon-ebs",
      "ami_regions": "{{user `destination_regions` }}",
      "ami_users": "{{user `destination_accounts` }}",
      "....": "...."
    }
  ],
  "variables": {
    "destination_regions": "us-west-1,us-west-2",
    "destination_accounts": ""
  }
}
```

so I could run `packer build ami_one.json` without having to specify any var files on the command line.

**Comment by SwampDragons** [comment]
Good idea! I'm not sure when we'll be able to prioritize this but I would love to implement it.

**Comment by azr** [comment]
Hello there, this can now be closed as it works with Packer 🎉  ! Doc is here: https://www.packer.io/docs/from-1.5/variables

**Comment by evansj** [comment]
Thanks very much! 🎉
