### ISSUE TITLE
Share encrypted ebs to other aws accounts

### ISSUE THREAD

**Issue by Ragulb89** [hashicorp/packer#7763]
AWS has introduced a feature to share the encrypted root ebs to other aws accounts. please refer the below link

https://aws.amazon.com/about-aws/whats-new/2019/05/share-encrypted-amis-across-accounts-to-launch-instances-in-a-single-step/

using amazon-ebs provider and kms_key_id we are not able to share the ami. I am using packer version 1.4.1.  Can we expect an update from packer to support this?

Error message:
Cannot share AMI with encrypted boot volume

**Comment by rickard-von-essen** [comment]
This have already been fixed in #7707 which is already in master. This will be supported in the next release.

**Comment by rickard-von-essen** [comment]
Duplicates #7681
