### ISSUE TITLE
Feature request: disk encryption in Azure

### ISSUE THREAD

**Issue by sireliah** [hashicorp/packer#7766]
Is there a plan to introduce disk encryption support for Azure? Could you please give me a roadmap for that if there is one?

Azure added ability to encrypt disks in some distros of Linux (Ubuntu, RHEL, CentOS) and in Windows couple of years ago.

https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/azure-disk-enc-linux
https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/azure-disk-enc-windows

It would be great to support at least Linux ones, similarly as we do it in AWS builders.

**Comment by SwampDragons** [comment]
I don't think this is currently on our roadmap, but I'd happily review a PR that implements it.

**Comment by sireliah** [comment]
Ok, thanks! We're not really yet at this point, but there's good chance that we'll need Azure image encryption in the future. I'll investigate what can be done then.

**Comment by raidlman** [comment]
Hi @SwampDragons. Is there any update on this topic? Are there plans to put this on the roadmap?

**Comment by SwampDragons** [comment]
I haven't had a chance to revisit and won't personally be able to work on implementing it for the next few months.  If this is something you really need to see happen, then the best way to make it happen sooner is to make a PR :).  I'm happy to give pointers if anyone needs help getting started.
