### ISSUE TITLE
-color=false causes -timestamp-ui flag to have no effect

### ISSUE THREAD

**Issue by ca-johnson** [hashicorp/packer#7767]
See https://github.com/hashicorp/packer/blob/c28ab292a4bebd297d386cb97398ffa892c220cb/command/build.go#L148

Seems like a bug, but I'm not sure what a safe refactor would be for this bit of code.

Thanks

**Comment by azr** [comment]
Hello there, thanks for reporting.
This should be as simple as moving the if check a bit lower. I opened #7769 that fixes this !
