### ISSUE TITLE
Packer 1.2.4: Error uploading ps script containing env vars: Couldn't determine whether destination was a folder or file: Command has already been closed

### ISSUE THREAD

**Issue by aledeniz** [hashicorp/packer#7768]
**Packer version**
1.2.4

**Host platform**
Windows 2008R2 private agent on Azure exercised from Azure DevOps.

**Debug log output**
The issue has been sporadic so far. The build takes 5 to 6 hours, I am not really keen to execute it in debug, unless the issue becomes more frequent.

**Template**
https://gist.github.com/aledeniz/e915333588ff36dd9075e7e7b9d5cde5#file-packer-1-2-4-template-for-error-uploading-ps-script

**Output**
https://gist.github.com/aledeniz/e915333588ff36dd9075e7e7b9d5cde5#file-packer-1-2-4-output-for-error-uploading-ps-script

**Notes**
The issue behaves like  hashicorp/packer#6240, which is reported fixed and closed in 1.2.4.

**Comment by azr** [comment]
Hello there, thanks for reporting. Have you tried on a more recent packer build: https://www.packer.io/downloads.html. A lot of improvement were done around the power-shell provisioner since then.

The current version is 1.4.1.

**Comment by aledeniz** [comment]
> Hello there, thanks for reporting. Have you tried on a more recent packer build: https://www.packer.io/downloads.html. A lot of improvements/changes were done around the power-shell provisioner since then.
> 
> The current version is 1.4.1.

I am working on a fork of microsoft/azure-pipelines-image-generation, which appears to be supporting up to 1.3.4.
I will give 1.4.1 a try, and I'll let you know.
As the issue is sporadic, it may take a number of runs.

**Comment by azr** [comment]
Awesome thanks 🙂

**Comment by SwampDragons** [comment]
Closing as it's been several weeks and we've never heard back; if we get confirmation that a more recent Packer doesn't solve the issue then we can reopen.

**Comment by aledeniz** [comment]
@SwampDragons just to confirm the issue has not been observed anymore after upgrading to 1.4.1.
