### ISSUE TITLE
Does the packer docker provisioner work on the Mac?

### ISSUE THREAD

**Issue by fields** [hashicorp/packer#7771]
I am getting this error:

```
Error response from daemon: pull access denied for thatimage, repository does not exist or may require 'docker login'
```

When trying to run packer on a local docker image. The image appears in the list when I run `docker image ls`. I suspect that this might have something to do with the way Docker on the Mac runs docker in a VM, but I'm not sure if the problem is this or something else.

**Comment by rickard-von-essen** [comment]
It works, the problem is something else.

**Comment by rickard-von-essen** [comment]
Please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._
