### ISSUE TITLE
packer virtual box image failing with pywinauto

### ISSUE THREAD

**Issue by sbansal3096** [hashicorp/packer#7776]
I was using a script in the provisioners of packer in windows virtual box machine, which would automate installing of windows desktop app using pywinauto. But it is not able to detect any open windows and not even able to take screenshot.
it gives error for screenshot as "OSError: screen grab failed"

Is there a way to see the provisioner script actually running in packer built machine?

**Comment by azr** [comment]
Hey there @sbansal3096, it seems like to me that you are running in headless mode; have you tried doing the opposite ? 

https://www.packer.io/docs/builders/virtualbox-iso.html#headless

For these kinds of questions, it's generally better to use the [mailing list](https://www.packer.io/community.html) where there are more people ready to help.

**Comment by azr** [comment]
I'm going to go ahead an close this issue as it doesn't look like a bug. We'll reopen if it is! 

Cheers.

**Comment by sbansal3096** [comment]
@azr Sorry to report it here. But i think it's some issue with compatibility of packer with Windows. 

I tried with headless = false, it opens virtual box but the machine there just stops at the login screen while the scripts are running on the console of host machine.

**Comment by azr** [comment]
Ah right, packer is connecting to windows through ssh or winrm, and it's therefore in a different environment than a graphical one, I'm afraid we can't solve your issue packer side. 

That said after googling a little, I found this: https://github.com/pywinauto/pywinauto/issues/247

**Comment by azr** [comment]
Okay, I still believe this is not a packer issue, so I will close this issue, please comment here if you think there's something packer should do.

I highly recommend using the mailing list, much more people are there and can give you a hand much better than me 🙂  ( they have more packer usage experience )
