### ISSUE TITLE
Packer detected as Bitcoin miner from MalwareBytes

### ISSUE THREAD

**Issue by roccozanni** [hashicorp/packer#7777]
Right after MalwareBytes (https://www.malwarebytes.com/) automatically installed the latest version of their protection system, Packer started being detected as a malware called `OSX.BirdMiner`.

<img width="882" alt="Screenshot 2019-06-20 at 18 35 44" src="https://user-images.githubusercontent.com/41727/59872950-2fa3f900-939b-11e9-82a9-0141195c0204.png">

`OSX.BirdMiner` is a Bitcoin miner malware that has been found into a cracked version of Ableton Live (details at https://blog.malwarebytes.com/mac/2019/06/new-mac-cryptominer-malwarebytes-detects-as-bird-miner-runs-by-emulating-linux/) so I believe this is a false positive. I'm not finding any trace in my system of that malware as described in their blog article and my local copy of the `packer` executable has the same exact signature of the one I just downloaded from your website (I also verified the signature of the zip file).

You may want to get in touch with MalwareBytes to verify and try to understand why this happening and how to fix it

- Packer version from `1.1.3`
- Host platform: `macOS Mojave 10.14.4 (18E226)`
- MalwareBytes Application Version: `3.8.17 (latest)`
- MalwareBytes Protection Version: `4.0.393 (latest)`

```
shasum -a 256 Downloads/packer_1.1.3_darwin_amd64.zip
b8ca17aedfbbb8607066528631d4f5992746fe9b2ec1bbc8d33fd1e5c196cd2c  Downloads/packer_1.1.3_darwin_amd64.zip
shasum -a 256 Downloads/packer 
a160dc3261598451bd56fedcfa1e0e66a9d3361177ca528fcae2e7bcbc06b723  Downloads/packer
shasum -a 256 /usr/local/bin/packer-1.1.3            
a160dc3261598451bd56fedcfa1e0e66a9d3361177ca528fcae2e7bcbc06b723  /usr/local/bin/packer-1.1.3
```

**Comment by SwampDragons** [comment]
Thanks for letting us know -- I'll escalate this to HashiCorp's security team right away.

**Comment by thomasareed** [comment]
I just took a look, and I don't see a detection for the current version of packer (1.4.1), but could duplicate with version 1.1.3. For the time being, if you're affected, a simple solution will be to update to the latest version of packer, but we'll work on fixing the false positive ASAP.

**Comment by thomasareed** [comment]
All taken care of... there should be no more issues. You can force Malwarebytes to update its rules by simply starting a scan, and packer-1.1.3 should no longer be detected.

**Comment by SwampDragons** [comment]
Thanks for the amazing turnaround @thomasareed!  I really appreciate y'all looking into this.

**Comment by thomasareed** [comment]
No problem, sorry for the inconvenience!

**Comment by roccozanni** [comment]
Awesome, I just run a scan with the new rules and it came out clean. Thank you very much @thomasareed and @SwampDragons for the prompt and amazing support!
