### ISSUE TITLE
UNC paths in iso_url don't work anymore

### ISSUE THREAD

**Issue by icnocop** [hashicorp/packer#7783]
Hi.

I used to be able to specify a UNC path in `iso_url` in packer v1.3.5 successfully.

However, in packer v1.4.1, an error occurs.

I'm running on Microsoft Windows 10 64-bit Version 1903.

| iso_url | v1.3.5 result | v1.4.1 result|
| -|-|-|
|\\\\my-fileserver\\Software\\Microsoft\\Operating Systems\\Windows Server 2008\\en_windows_server_2008_r2_x64_dvd_x15-50365.iso|Using file in-place: smb://my-fileserver/Software/Microsoft/Operating%20Systems/Windows%20Server%202008/en_windows_server_2008_r2_x64_dvd_x15-50365.iso|invalid source string: //my-fileserver/Software/Microsoft/Operating%20Systems/Windows%20Server%202008/en_windows_server_2008_r2_x64_dvd_x15-50365.iso|
|//my-fileserver/Software/Microsoft/Operating Systems/Windows Server 2008/en_windows_server_2008_r2_x64_dvd_x15-50365.iso|Using file in-place: file:////my-fileserver/Software/Microsoft/Operating%20Systems/Windows%20Server%202008/en_windows_server_2008_r2_x64_dvd_x15-50365.iso|invalid source string: //my-fileserver/Software/Microsoft/Operating%20Systems/Windows%20Server%202008/en_windows_server_2008_r2_x64_dvd_x15-50365.iso|
|smb://my-fileserver/Software/Microsoft/Operating Systems/Windows Server 2008/en_windows_server_2008_r2_x64_dvd_x15-50365.iso|Using file in-place: smb://my-fileserver/Software/Microsoft/Operating%20Systems/Windows%20Server%202008/en_windows_server_2008_r2_x64_dvd_x15-50365.iso|download not supported for scheme 'smb'|
|file:////my-fileserver/Software/Microsoft/Operating Systems/Windows Server 2008/en_windows_server_2008_r2_x64_dvd_x15-50365.iso|Using file in-place: file:////my-fileserver/Software/Microsoft/Operating%20Systems/Windows%20Server%202008/en_windows_server_2008_r2_x64_dvd_x15-50365.iso|Trying file:////my-fileserver/Software/Microsoft/Operating%20Systems/Windows%20Server%202008/en_windows_server_2008_r2_x64_dvd_x15-50365.iso<br/>source path error: Stat : The system cannot find the path specified|

Packer template and debug log:
https://gist.github.com/icnocop/f4ad55986a10b0daa5df9ab6353ecb0d

Any ideas?

Thank you.

**Comment by SwampDragons** [comment]
We recently changed to using go-getter for our downloads; I strongly suspect this is related to that change. I'll take a look at it now.

**Comment by SwampDragons** [comment]
Yep, confirmed that this is when this broke. I've got a repro case so I'll try to implement a fix.
