### ISSUE TITLE
Remove hyperv-vmcx MaxRamSize restriction

### ISSUE THREAD

**Issue by dhirschfeld** [hashicorp/packer#7784]
I'm trying to use packer to build a `hyperv-vmcx` VM but am getting error messages about running out of RAM despite having it set to 32GB. Since my host has 256GB of RAM I thought I could simply bump this up to allow the build to complete but it appears that anything over 32GB is explicitly disallowed:  
```
hyperv-vmcx output will be in this color.

1 error(s) occurred:

* memory: Virtual machine requires memory size <= 32768 MB, but defined: 65536
```
https://github.com/hashicorp/packer/blob/45af9f0cbcf6db9e7c0218976d04eb85a87463b5/builder/hyperv/vmcx/builder.go#L26
https://github.com/hashicorp/packer/blob/45af9f0cbcf6db9e7c0218976d04eb85a87463b5/builder/hyperv/vmcx/builder.go#L578-L581

Is there any reason to restrict the maximum RAM available to the VM?

**Comment by SwampDragons** [comment]
That seems fair. Looks like the max for windows 10 is 1TB now. I think at the time this was written, only windows 2008 was out, and it had a lower max.
