### ISSUE TITLE
HELP: is that possible to fix a issue from master to tag release? such as v1.4.1

### ISSUE THREAD

**Issue by bzhaoopenstack** [hashicorp/packer#7788]
I fix the issue in the master branch. And how to make it in the tag release? Could anyone please to tell me how to operate or the policy of our project? Thanks.

Or, the only way is waiting for the new version release(v1.4.2) if I want the issue fix in the our official release, is that correct? 

related-Bugs: #7749

**Comment by SwampDragons** [comment]
We do not backport changes, so the only way to get the change in an official release is to wait for the 1.4.2 release. I will be releasing 1.4.2 this week, so you don't have long to wait.

**Comment by bzhaoopenstack** [comment]
Hi, SwampDragons,
Thanks for your kind explaination. It's clear for me
