### ISSUE TITLE
builder `googlecompute` uses hostname instead of instance name to set instance metadata

### ISSUE THREAD

**Issue by alexfouche** [hashicorp/packer#7789]
- Packer version 1.4.1
- Host Linux Centos 7

This issue applies to the `googlecompute` builder

The issue appears **when the hostname or FQDN of the linux instance does not match the instance name** set when creating the instance. Or when hostname is modified (via a custom startup script or whatever at linux start, ...) or is set with `"instance_name": ` in the builder json block

The builder, when instanciating a VM adds a metadata `startup-script`. In this script, there is a shell function `SetMetadata()`, which is called at the end of the startup script to set instance metadata `startup-script-status=done`

```bash
SetMetadata () {
  gcloud compute instances add-metadata ${HOSTNAME} --metadata ${1}=${2} --zone ${ZONE}
}
```
See [startup.go#L27](https://github.com/hashicorp/packer/blob/55bfee509aae718b695f5c84736b281d4119cc6e/builder/googlecompute/startup.go#L27)

The problem lies in the fact that `${HOSTNAME}` is used. **The Google instance name should be used, not the hostname**.

Using the `GetMetadata()` function of the script, the instance name can be retrieved with 

    GetMetadata name

**Comment by rickard-von-essen** [comment]
This is a bit of a mess. The startup script does way too many assumptions about the host than it should.

**Comment by fisabelle** [comment]
This seems to be failing all the time on Centos 8. Maybe the host name is always being set to FQDN in that case, so the there are always dots in the $HOSTNAME value.
