### ISSUE TITLE
builder `googlecompute` always returns ok even when interrupted of failed

### ISSUE THREAD

**Issue by alexfouche** [hashicorp/packer#7793]
- Packer version 1.4.1
- Host: Linux Centos 7

## This issue applies to the `googlecompute` builder

The builder, when instanciating a VM adds a metadata `startup-script`. In this script, there is a shell function `SetMetadata()`, which is called at the end of the startup script to set instance metadata `startup-script-status=done`

But sometimes this call to set metadata fails _(below two examples of failure)_ and the metadata is never set to `done`, and thus Packer keeps repeating :

```
==> googlecompute: Waiting for any running startup script to finish...
==> googlecompute: Startup script not finished yet. Waiting...
==> googlecompute: Startup script not finished yet. Waiting...
==> googlecompute: Startup script not finished yet. Waiting...
(...)
```

**The issue if of course that the `startup-script` failure was never detected and Packer did not stop early**, and continued running all provisionners

### instance created without associated service account:

typically with `"disable_default_service_account": true,`

```
Jun 25 07:56:24 staging-collector-master startup-script: INFO Starting startup scripts.
Jun 25 07:56:24 staging-collector-master startup-script: INFO Found startup-script in metadata.
Jun 25 07:56:24 staging-collector-master startup-script: INFO startup-script: Packer startup script starting.
Jun 25 07:56:24 staging-collector-master startup-script: INFO startup-script: Executing user-provided startup script...
Jun 25 07:56:24 staging-collector-master startup-script: INFO startup-script: Packer startup script done.
Jun 25 07:56:27 staging-collector-master startup-script: INFO startup-script: ERROR: (gcloud.compute.instances.add-metadata) You do not currently have an active account selected.
Jun 25 07:56:27 staging-collector-master startup-script: INFO startup-script: Please run:
Jun 25 07:56:27 staging-collector-master startup-script: INFO startup-script:   $ gcloud auth login
Jun 25 07:56:27 staging-collector-master startup-script: INFO startup-script: to obtain new credentials, or if you have already logged in with a
Jun 25 07:56:27 staging-collector-master startup-script: INFO startup-script: different account:
Jun 25 07:56:27 staging-collector-master startup-script: INFO startup-script:   $ gcloud config set account ACCOUNT
Jun 25 07:56:27 staging-collector-master startup-script: INFO startup-script: to select an already authenticated account to use.
Jun 25 07:56:27 staging-collector-master startup-script: INFO startup-script: Return code 0.
Jun 25 07:56:27 staging-collector-master startup-script: INFO Finished running startup scripts.
```

### When changing a hostname with dots

This is related to a separate issue i created: https://github.com/hashicorp/packer/issues/7789 : Packer erronously uses hostname instead of the Google instance name to set the instance metadata. Google expects an instance name and reports (not clearly) that instance names can not have dots

```
Jun 25 07:59:45 staging-collector-master startup-script: INFO Starting startup scripts.
Jun 25 07:59:45 staging-collector-master startup-script: INFO Found startup-script in metadata.
Jun 25 07:59:46 staging-collector-master startup-script: INFO startup-script: Packer startup script starting.
Jun 25 07:59:46 staging-collector-master startup-script: INFO startup-script: Executing user-provided startup script...
Jun 25 07:59:46 staging-collector-master startup-script: INFO startup-script: Packer startup script done.
Jun 25 07:59:49 staging-collector-master startup-script: INFO startup-script: ERROR: (gcloud.compute.instances.add-metadata) Could not fetch resource:
Jun 25 07:59:49 staging-collector-master startup-script: INFO startup-script:  - Invalid value 'master.collector.domain.tld'. Values must match the following regular expression: '[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?|[1-9][0-9]{0,19}'
Jun 25 07:59:49 staging-collector-master startup-script: INFO startup-script: Return code 0.
Jun 25 07:59:49 staging-collector-master startup-script: INFO Finished running startup scripts.
```

**Comment by SwampDragons** [comment]
I'm marking this as an enhancement rather than a bug because the behavior you describe is documented.  We'll have to think through what we want to do about this.

**Comment by SwampDragons** [comment]
Sorry, re-read the issue. You're right that we should be erroring if our metadata call is failing.

**Comment by SwampDragons** [comment]
This is going to be a hard one to fix. If we can't set the metadata, we don't know whether it failed or not. A timeout is probably the best we're going to be able to get.

**Comment by badele** [comment]
@swampDragons Hum ... In the error log there have a error `Jun 25 07:59:49 staging-collector-master startup-script: INFO startup-script: ERROR: (gcloud.compute.instances.add-metadata) Could not fetch resource:`

You cannot detect it ?

After, effectivelly, if you can't detect another error, it's more secure use timeout feature

**Comment by SwampDragons** [comment]
The only way that we know whether the startup script passes or fails is by that metadata flag; we give google the script but we don't run it through our own ssh connection -- google runs it. So if the flag never gets set, we don't know if that's because the flag-setting script failed, or if it's still running.

We also don't wait for the startup-script to be complete before running provisioners. If you want to force the provisioners not to work until the script is done, you can probably disable SSH until the very end of your script and then reenable it, so that Packer can't connect. Just make sure your ssh timeout is large, if you do that.

This whole part of the code is full of assumptions that need to be revisited. The googlecompute builder is the only one where we do this script-wrapping and try to set metadata flags; in other builders we generally leave that up to the user.  We may eventually deprecate this wrapping behavior altogether and force the users to set the metadata themselves inside their scripts, so that it's clear that Packer isn't in charge of this stuff.

**Comment by keznikl** [comment]
As I commented in #9121, I think this behavior is a security risk.
Requiring `compute.instances.setMetadata` is a pretty demanding requirement, because this permission also let's one update gain SSH access to the VM (or other VMs sharing the same service account).

**Comment by SwampDragons** [comment]
Hi there -- we've made a change to the googlecompute builder to put this wrapping script with its metadata call into an option: see #9505 for details. 

To turn off the script wrapper, and to prevent the requirement that the user have the `compute.instance.Metadata` role, you can set the option [wrap_startup_script](https://www.packer.io/docs/builders/googlecompute.html#wrap_startup_script)

`"wrap_startup_script": false,`

Long-term, we're going to switch the flag to default to false, then probably fully deprecate the script wrapper and metadata updating.
