### ISSUE TITLE
Allow configuring VNC password for qemu builder

### ISSUE THREAD

**Issue by iilyak** [hashicorp/packer#7795]
I am trying to debug windows build on mac os using qemu builder using `hvf` accelerator. 
The specifics of Mac platform is that `sdl` is not available. Which means I have to use `headless` mode. Another specifics of Mac is that starting from Sierra the VNC client doesn't work if password is empty. Therefore I was trying to setup a VNC password. Packer doesn't support setting the password for VNC so I was looking for a workaround. I was able to start QEMU monitor on unix socket and change the password while packer was running. I am able to connect to VM via VMC. However now it is obvious to me that this approach will not work because packer looses the ability to control installation of the VM. Since it doesn't know the password. 

# The feature request

Allow setting of VNC password via packer JSON file. Teach packer how to configure it via QEMU monitor or QMP.

**Comment by SwampDragons** [comment]
Thanks for this suggestion! The QEMU builder community-supported, which means that the HashiCorp maintainers don't spend much engineering time on it. This means that the best way to see your suggestion make it into Packer is to open a PR.

**Comment by SwampDragons** [comment]
One thing you can do is download a third party VNC viewer; I use jolly fast vnc, which doesn't have issues with passwordless VNC.

**Comment by vtolstov** [comment]
may be i can take this

**Comment by 70k10** [comment]
@vtolstov Go for it if you want, I have a need for this at work so I've started coding a QMP based solution.
