### ISSUE TITLE
packer 1.4.1 - VMware Builder(vmware-vmx) - ESXi - Destroying virtual machine stage failed

### ISSUE THREAD

**Issue by adityati** [hashicorp/packer#7797]
Hi Packer Team,
I encountered an issue while building a VM using vmware-vmx on ESXi server. The build process is hung up at the stage **Destroying virtual machine** and finally exit after the timeout. 
**My Current Setup**
- Packer
   version - v1.4.1
   os/architecture - linux/amd_64, macOS/64Bit
- ESXi Server
   version - 6.7.0
- Template Json
   https://gist.github.com/adityati/7fc9cc7371d09e8d4fbf50dbae6226fc
- Debug log output
  https://gist.github.com/adityati/5e1ec914c4f076821c7b9526a8ce2a6c  

I really appreciate, if you could assist me in solving this issue or point me to some work around 

Regards,
Aditya

**Comment by SwampDragons** [comment]
Has this ever worked for you? (e.g. with a different template or a different version of Packer?)

The only think I can think of is that maybe the Packer user doesn't have permission to destroy the VM, but if that's the case I would expect it to error, not hang.

You may have luck finding someone on the [mailing list](https://groups.google.com/forum/#!forum/packer-tool) who has had this problem

**Comment by SwampDragons** [comment]
Closing because I never heard a response. If you want to continue investigating this together, we can reopen but I do suspect this is a permissions issue.
