### ISSUE TITLE
New build ends up in new iso upload every time - "[ERROR] Remote command exited with '127': filesum -c"

### ISSUE THREAD

**Issue by Wolfsrudel** [hashicorp/packer#7801]
Everytime a build of an image is started there will be a new upload of the same iso file. The logfile just says:
`[ERROR] Remote command exited with '127': filesum -c`

- Packer version from `packer version`
1.4.1

- Target: VMware ESX 6.x

It was working in former versions of packer.

**Comment by Wolfsrudel** [comment]
At the esx server there is no command "filesum"
`filesum --help
-sh: filesum: not found
But why is packer trying to use this?

**Comment by SwampDragons** [comment]
Thanks for opening an issue -- to help you, we really do need the things requested in the issue template: 

- Full debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a gist https://gist.github.com
- The _simplest complete example template and scripts_ needed to reproduce the bug.
  Include these in your gist https://gist.github.com

Unless I have those it is very hard for me to answer the questions that will arise while debugging.

I did a quick search of the Packer code and I don't see "filesum" anywhere in it. So I definitely need more context.

**Comment by Wolfsrudel** [comment]
Yeah, sorry for the missing information. Here you are `https://gist.github.com/Wolfsrudel/c90e70103a3ae33fb1d5e2490a099ee2`
I've checked it twice, with every build the uploaded iso file got a new timestamp.

Thanks for your help.

**Comment by SwampDragons** [comment]
Thanks for the details -- this looks like a side effect of our move to go-getter, and it interacting badly with our checksum driver for esxi when using a checksum file. A workaround would be to provide the checksum manually rather than from a file, for now, but I'll work on a fix for the next release.
