### ISSUE TITLE
[BUG | Google Compute Builder] OAuth2 url should be updated

### ISSUE THREAD

**Issue by JasperWoo** [hashicorp/packer#7803]
* Packer: 1.4.1
* Host platform: docker container running in GCP vm
* Log: https://gist.github.com/JasperWoo/9fa485c111910ba2efa8bc4ebff59c63
* To reproduce:
   1. Create a VPC in Google Cloud, disabling internet egress access.
   2. Set up Private Google Access to allow egress access to *.googleapis.com
   3. Create a VM with service account (which has all needed roles) enabled in the VPC, run Packer.

According to googleapis issues [this](https://github.com/googleapis/google-cloud-common/issues/260), and [this](https://github.com/googleapis/google-auth-library-ruby/issues/155), OAuth2 urls should be updated across all languages.

Especially for the error above, it should be changed as:
https://accounts.google.com/o/oauth2/token -> https://oauth2.googleapis.com/token

**Comment by tuhinkanti** [comment]
Possibly change this:
https://github.com/hashicorp/packer/blob/44d2198a1b82bdf056740ce156b19164bfd3b8e9/builder/googlecompute/driver_gce.go#L54

**Comment by rickard-von-essen** [comment]
We should use
https://github.com/golang/oauth2/blob/master/google/google.go

**Comment by SwampDragons** [comment]
@JasperWoo I'm having a bit of trouble actually reproducing your particular issue, but I've replaced our custom oauth code with the golang oauth library, which includes updating the token URL, and I think what I've got here should do the trick. Can you try it out? The linked binaries are built from PR 7835.

https://circleci.com/gh/hashicorp/packer/6778#artifacts/containers/0

**Comment by JasperWoo** [comment]
@SwampDragons Thanks for the fix. We will test it today!

**Comment by tuhinkanti** [comment]
@SwampDragons I just tested it in a VPC with private access enabled. It works. Thanks for such a quick turnaround

**Comment by SwampDragons** [comment]
No problem @JasperWoo. It auto-closed when I merged the PR. :)

**Comment by tuhinkanti** [comment]
I am wondering what release will this fix be part of?

**Comment by SwampDragons** [comment]
@tuhinkanti 1.4.3
