### ISSUE TITLE
File provisioner gets stuck when downloading

### ISSUE THREAD

**Issue by gbjtv** [hashicorp/packer#7805]
When trying to download syslinux/pxelinux related files, it gets stuck when using versions:
1.4.1
1.4.2

Previous versions work fine (1.4.0).
Host computer is running Ubuntu 18.04
Debug log and json: https://gist.github.com/gbjtv/e8ec2a4698b4c6fe6c3ba4fc2b275836

**Comment by SwampDragons** [comment]
Thanks for reaching out; I'll take a look and see if I can figure out what's going on.

**Comment by SwampDragons** [comment]
Just ran a bisect; it looks like this was introduced by a change to the docker communicator attempting to improve error logging: 71f2017209d65d747f8e1ecf3771bd843351a492

I'll see if there's a way to preserve error logging without causing this hang.

**Comment by SwampDragons** [comment]
I've opened a PR (linked above) to fix this.

**Comment by SwampDragons** [comment]
You can find a binary of this patch here: https://circleci.com/gh/hashicorp/packer/6178#artifacts/containers/0
