### ISSUE TITLE
Packer supported ciphers and Macs are not working as per Documention for centos 7(ssh timeout)

### ISSUE THREAD

**Issue by suriya91** [hashicorp/packer#7807]
_Please read these instructions before submitting_

**DELETE THIS TEMPLATE BEFORE SUBMITTING**

_Only use GitHub issues to report bugs or feature requests, see
https://www.packer.io/community.html_

For example, _Timeouts waiting for SSH/WinRM_ are generally not bugs within packer and are better addressed by the mailing list. Ask on the mailing list if you are unsure.

If you are planning to open a pull-request just open the pull-request instead of making an issue first.

FOR FEATURES:

Describe the feature you want and your use case _clearly_.

FOR BUGS:

Describe the problem and include the following information:

- Packer version from `packer version`
- Host platform
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a gist https://gist.github.com
- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your gist https://gist.github.com

**Comment by SwampDragons** [comment]
I'm closing this because we don't have any of the details requested in the template; please open a new issue with more information if this is still a problem for you.

**Comment by rickard-von-essen** [comment]
I think there are already an issue or discussion on the mailing list about
this with all details. Unfortunately I couldn't find it doing a quick
search on my phone.
