### ISSUE TITLE
Shared Gallery Image to which to publish the managed image version to does not exist in the resource group

### ISSUE THREAD

**Issue by BenMitchell1979** [hashicorp/packer#7809]
Describe the problem and include the following information: When attempting to deploy Azure Managed Image to Shared Image Gallery using new "shared_image_gallery_destination" and I'm getting the following error

`Build 'azure-arm' errored: the Shared Gallery Image to which to publish the managed image version to does not exist in the resource group MBPRD-IMAGES`

- Packer version from `packer version` = 1.4.2
- Host platform= Windows 10 (1803 Build 17134.765)
- Debug log output and template used: https://gist.github.com/BenMitchell1979/f4fc6b9fdfc338433c6276323fe9db92

**Comment by BenMitchell1979** [comment]
Looks like you have to pre-stage the Image Definition in the Shared Image Gallery that you are calling via the template. This probably needs to be documented here - https://www.packer.io/docs/builders/azure.html

**Comment by slime-uk** [comment]
I'm also having this issue - do we really need to pre-stage the image definition (even though there is no image as yet) in Azure Shared Image gallery?

**Comment by ashemedai** [comment]
@slime-uk Yes, you do. At the moment there seem to be two (or three depending on how you look at it) options to do so:

- Use Terraform's `azurerm_shared_image` to create these definitions when you create the shared image gallery, provided you use Terraform for those things of course.
- Use az cli or PowerShell to create a shared image definition, e.g. for a customised Ubuntu 18.04-LTS image: `az sig image-definition create --resource-group <my-rg> --gallery-name <my_shared_image_gallery> --gallery-image-definition <my-ubuntu18> --publisher <company> --offer UbuntuServer --sku 18.04-LTS --os-type linux`
