### ISSUE TITLE
qemu builder: memory size ignored

### ISSUE THREAD

**Issue by mcandre** [hashicorp/packer#7820]
Hi, I am building some ppc and mips base boxes with Packer using the qemu builder. My boxes will be compiling applications and so require 1024 MiB or more of memory. However, my configuration to qemu for the RAM size is being ignored, resulting in boxes with quite limited memory 512 MiB.

```console
$ packer build packer.json
...
qemu output will be in this color.

2019/06/30 19:24:10 packer: 2019/06/30 19:24:10 use specified accelerator: tcg
2019/06/30 19:24:10 packer: 2019/06/30 19:24:10 MemorySize 0 is too small, using default: 512
...
```

- Packer version from `packer version` Packer v1.4.0-dev
- Host platform: Ubuntu 19.04 Disco Dingo, System76 Galaga Pro with 16 GiB RAM

```json
"qemuargs": [
    ["-m", "1024"]
],
```

Am I using the right syntax for this? Could there be a glitch in qemu-system-{ppc64le,mips64el}?

**Comment by rickard-von-essen** [comment]
Use [`memory`](https://packer.io/docs/builders/qemu.html#memory).
