### ISSUE TITLE
More detailed qemu examples

### ISSUE THREAD

**Issue by mcandre** [hashicorp/packer#7821]
Hi there!

Packing x86[_64] base boxes with Packer has been a fairly straightforward process for many different flavors of operating systems. This time around, I am working on some non-x86* boxes for use as cross-compiler VM's. gcc on a Debian ppc64el Vagrant box, for example, is a great way for developers to port applications to another architecture without having to manually setup toolchains or pay for dedicated hardware!

I'm starting to appreciate just how intricate these qemu builds are, compared to more typical x86* / pc builds. For example, I'm having a devil of a time getting an aarch64 or mips64el Debian guest booting from standard installation media using Packer and qemu-system-*. Unlike other hypervisors, qemu doesn't work out of the box without significant, explicit tweaks. So it takes a lot of digging to sort out issues with these boxes. It's all in a day's work, but some guidance on dealing with these lil' architectural hydras would be appreciated. Some days it's all I can do to replace the nature of the error message.

Worse, some glitches only appear once a box has been customized, exported with `vagrant package`, and re-instanced downstream. Sad panda. If time were money, it might make sense to switch from Packer to just Ansible with dedicated hardware!

Any tips for getting ARM or MIPS guests building with Packer?

So ARM and MIPS are hard to do with a simple Packer config. What if we had example configurations to glean from? Any interest in posting more complete Packer projects, repositories, tutorials, and so on?

If I manage to get Debian ARM or MIPS up in Packer, I'll drop a line with some workarounds. In the meantime, I might give SPARC and S390X a try, just in case they're a bit easier like PPC. Jewel runner over and out.

**Comment by rickard-von-essen** [comment]
Guess this is mostly a QEMU issue, maybe better to ask on a Qemu list for help. But I guess we gladly accepts PR's for this.

**Comment by SwampDragons** [comment]
The Packer [mailing list](https://groups.google.com/forum/#!forum/packer-tool) or community forum are probably better places for asking for tips and tricks. I agree that more examples would be nice, though.
