### ISSUE TITLE
ssh_interface config option avilible in all builders

### ISSUE THREAD

**Issue by rickard-von-essen** [hashicorp/packer#7824]
`ssh_interface` is an option specific for the Amazon and OpenStack builders, but it is implemented in  `helper/communicator/config.go` and thus you can set it in all of the builders (without any effect).

```bash
$ git grep -l SSHInterface                                                                                                               
builder/amazon/common/run_config.go
builder/amazon/ebs/builder.go
builder/amazon/ebssurrogate/builder.go
builder/amazon/ebsvolume/builder.go
builder/amazon/instance/builder.go
builder/openstack/builder.go
helper/communicator/config.go
```

**Comment by rickard-von-essen** [comment]
Related #7773

**Comment by SwampDragons** [comment]
This was introduced in b0c09087a21993890e4eca52c07a85c572097aea. Potentially, reverting will solve this particular issue. I'll test now.
