### ISSUE TITLE
FIX command corrupting JSON template

### ISSUE THREAD

**Issue by Aussie007** [hashicorp/packer#7826]
Hello Support

I upgraded packer from v1.3.5 to v1.4.2.

I ran packer validate against a JSON template - no errors

I ran packer fix against the same JSON template - no errors

I ran packer validate against the new JSON template - get the following:

Failed to parse template: Error parsing JSON: invalid character 'ÿ' looking for beginning of value
At line 1, column 1 (offset 1):
    1: �
      ^

- Packer version from `packer version`
  - v1.4.2

- Host platform
  - Windows 10 (1809) Build: 17763.437

- Debug log output from `PACKER_LOG=1 packer build template.json`.
  - attached file
[26f2b0b131b2812a673e216da1dca1a5-861b072ac86601cb4fcc2a648451bb121e277e59.zip](https://github.com/hashicorp/packer/files/3345409/26f2b0b131b2812a673e216da1dca1a5-861b072ac86601cb4fcc2a648451bb121e277e59.zip)

I get the same error message when trying to open the new JSON template in other apps - Visual Studio Code, Notepad++, etc.

Regards

Stephen

**Comment by SwampDragons** [comment]
Can you please share the template that you ran through `fix` to get this?

**Comment by SwampDragons** [comment]
My gut instinct is that there's a copy/paste issue happening here, so I'm going to close. We can reopen if you give me the template in question and the method you used for copying the new template.
