### ISSUE TITLE
How do Configuring resize of root volume on linux & windows EC2

### ISSUE THREAD

**Issue by willwu0975** [hashicorp/packer#7842]
How do Configuring resize of root volume on linux & windows EC2
this is my json file 

"type": "amazon-ebs",
    "region": "us-west-1",
    "source_ami": "ami-0ce5aexxxxxxxxx0",
    "instance_type": "t2.micro",
    "ssh_username": "ec2-user",
    "ami_name": "will-{{timestamp}}"
  }
   ],
   " launch_block_device_mappings": [
    {
      "device_name": "/dev/sda1",
      "volume_type": "gp2",
      "volume_size": 20,
      "delete_on_termination": true
 }
  ],
    "provisioners": [
  {
    "type": "shell",

===================================

erroe messages

ailed to parse template: 1 error occurred:
	* Unknown root level key in template: ' launch_block_device_mappings'

**Comment by rickard-von-essen** [comment]
You have an extra space in `launch_block_device_mappings`.

**Comment by rickard-von-essen** [comment]
Please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._
