### ISSUE TITLE
Vagrant Builder: {{ .BoxName }} is set to source_path instead of box_name

### ISSUE THREAD

**Issue by ryanfitzsimon** [hashicorp/packer#7844]
In the [documentation](https://github.com/hashicorp/packer/blob/v1.4.2/website/source/docs/builders/vagrant.html.md#optional), `{{ .BoxName }}` is said to correspond to `box_name`:
> So far the only template variables available to you are {{ .BoxName }} and {{ .SyncedFolder }}, which correspond to the Packer options box_name and synced_folder. 

However, it is actually set to `source_path` (`SourceBox`) in [step_create_vagrantfile.go](https://github.com/hashicorp/packer/blob/v1.4.2/builder/vagrant/step_create_vagrantfile.go#L59).

Versions affected: 1.3.5, 1.4.x
Platforms affected: All

**Comment by SwampDragons** [comment]
thanks for opening this -- you're right. I've opened a PR to fix this: #7859
