### ISSUE TITLE
googlecompute gcp shieldedvm

### ISSUE THREAD

**Issue by ralvarez-mvd** [hashicorp/packer#7846]
Build 'googlecompute' errored: Error creating instance: googleapi: Error 412: Constraint constraints/compute.requireShieldedVm violated for project projects/demostenes. Secure Boot is not enabled in the 'shielded_instance_config' field. See https://cloud.google.com/resource-manager/docs/organization-policy/org-policy-constraints for more information., conditionNotMet

Trying to use packer to build a shieldedVM on gcp.
Have not found any configuration option.
Tried tags and metadata to no avail.

Trying not to brew my custom builder.

**Comment by SwampDragons** [comment]
Looks like we should research this and add an option for enabling secure_boot. I'm not sure when I'll get to this but PRs are welcome.

**Comment by ralvarez-mvd** [comment]
diff --git a/builder/googlecompute/driver_gce.go b/builder/googlecompute/driver_gce.go
index f2adaa591..82761d129 100644
--- a/builder/googlecompute/driver_gce.go
+++ b/builder/googlecompute/driver_gce.go
@@ -420,6 +420,11 @@ func (d *driverGCE) RunInstance(c *InstanceConfig) (<-chan error, error) {
                Tags: &compute.Tags{
                        Items: c.Tags,
                },
+               ShieldedInstanceConfig: &compute.ShieldedInstanceConfig{
+                       EnableSecureBoot: true,
+                       EnableVtpm: true,
+                       EnableIntegrityMonitoring: true,
+               },
        }

        d.ui.Message("Requesting instance creation...")

**Comment by ralvarez-mvd** [comment]
That takes care of "enforcing" a shieldedvm.
Now what's needed is wrap up the config in variables and expose it to the end user.

**Comment by johnsaturn** [comment]
Seems that Google is defaulting to VTPM which in some cases that the behavior is not expected .Looking forward this feature as this is breaking images due to a Google Issue with boot disks over 200GB

**Comment by nywilken** [comment]
Hi @johnsaturn I'm linking your comment https://github.com/hashicorp/packer/issues/8951#issuecomment-612566579  here as it seems to be more relevant to the issue you are seeing.
