### ISSUE TITLE
Azure - customize data-disks names

### ISSUE THREAD

**Issue by vanbukin** [hashicorp/packer#7853]
Feature request
Affected versions: 1.4.2

As I see [here](https://github.com/hashicorp/packer/blob/v1.4.2/builder/azure/common/template/template_builder.go#L243) - there is no way to customize [additional data-disk](https://www.packer.io/docs/builders/azure.html#disk_additional_size) name when I build images in Azure. So if I don't want to use temporary resource group each time (for cost management purposes) - I can't run multiple parallel images builds at the same resource group, because data disk with same name may already exists (it always be `datadisk-1`, `datadisk-2` and so on)
<img width="610" alt="Screenshot 2019-07-08 at 22 41 28" src="https://user-images.githubusercontent.com/22099558/60838227-e0e7c300-a1d2-11e9-9b86-fac09e2fc3b3.png">
So, please add ability to customize that name - maybe suffix or prefix, or something other.

**Comment by vanbukin** [comment]
Do you have any plans to implement this?

**Comment by SwampDragons** [comment]
I'd love to, but it's not on my priority list right now.  Packer has a lot of great feature requests open and currently only one full-time developer. If you are impatient for this feature to exist, the best way to get a feature request turned into a feature is to open a PR.

**Comment by paulmey** [comment]
@vanbukin So if instead of letting the user specify the name, we'd use a better randomization, would that help?

**Comment by vanbukin** [comment]
I think end users can randomize name as they need by themself. So allow to set names manually is the best way.

**Comment by wKd2** [comment]
Better randomization would help me, as long as I can build multiple images in the same resource group in parallel the name doesn't matter

**Comment by george-polevoy** [comment]
> @vanbukin So if instead of letting the user specify the name, we'd use a better randomisation, would that help?

Randomisation is one way of solving the problem, but as an IaC developer I'd prefer precise control on the image name instead. It is trivial to come up with a naming strategy.
However, trying to figure out which image belongs to which part of the build process is not a trivial in case of randomisation.

Combine it with a requirement to cleanup resources after the failed build instances and it is already a difficult task. Also, randomisation does not guarantee uniqueness. Even if it happens rarely, there could be collisions, and debugging those is not trivial.

In fact, we had to implement resource group pools, one for each parallel build pipeline, to guard our build process from these issues, and deterministic approach turned to work much better than randomisation.
