### ISSUE TITLE
Proxmox: resource pools support [Feature request]

### ISSUE THREAD

**Issue by lukasmrtvy** [hashicorp/packer#7856]
Is possible to implement support for resource pools? 
I have user which has no access to root resource pool.
This user has own resource pool and datastore. 
I am not able to create template with packer, because its creating VM by default to root resource pool. (`Error creating VM: 403 Permission check failed`)
Thanks

**Comment by lukasmrtvy** [comment]
ping @carlpett

**Comment by carlpett** [comment]
Hi @lukasmrtvy,
Should be possible. It just happens to be an undocumented option, so I had to trace down how the UI does it... I'll give implementation a try and see!

**Comment by carlpett** [comment]
Ok, it works, sort of, but with a major issue. A user without the `Sys.Modify` permission cannot send keystrokes to the VM console, which means boot commands don't work.
I've posted a query to the Proxmox folks to see if there is anything that can be done.
