### ISSUE TITLE
no_proxy is not respected by packer build - "no such host"

### ISSUE THREAD

**Issue by roshan-kumar001** [hashicorp/packer#7858]
- Packer version - v1.3.5
- Host platform - Windows
- Debug log output from `PACKER_LOG=1 packer build template.json`.
- The _simplest example template and scripts_ needed to reproduce the bug.
[Files and Debug details](https://gist.github.com/roshan-kumar001/2b18a33eb140c5cd925cd8f09328e304)

I'm using `private_dns` option for `ssh_interface` behind a company proxy.

Based on the documentation on the site
**_Where Packer is configured for an outbound proxy but WinRM traffic should be direct, ssh_interface must be set to private_dns and <region>.compute.internal included in the NO_PROXY environment variable._**
I've added _**us-west-2.compute.internal**_ to the NO_PROXY list. However, packer does not seem to be able to reach the host at all. As shown in the debug logs, it just keeps throwing "**_no such host_**". I've tried all the possible combinations in NO_PROXY e.g. 

- us-west-2.compute.internal
- compute.internal
- *.us-west-2.compute.internal
- *.internal etc. 

but none of them worked.

Is there anything else that I might be missing to make sure that `private_dns` option works?

**Comment by SwampDragons** [comment]
I think this was probably resolved in v1.4.0 by https://github.com/hashicorp/packer/pull/7361

Try with a more recent version of Packer and let me know if it's still an issue for you?

**Comment by SwampDragons** [comment]
Closing since I never heard back. We can reopen if it turns out this is still a problem.
