### ISSUE TITLE
Googlecompute: Option to set networkInterfaces[].networkIP (internal IP) 

### ISSUE THREAD

**Issue by JasperWoo** [hashicorp/packer#7861]
From as can be seen from Terraform document [here](https://www.terraform.io/docs/providers/google/r/compute_address.html), Google Compute should have provided the ability to launch an instance with a static IP address. 

Therefore I wonder if Packer can provide / has provided this capability for Google Compute builder, i.e., to be able to create the VM with static IP address.

This is important for us because we have to use DNS name to ssh, and that would be very difficult to automate if the IP address of the VM keeps changing.

**Comment by rickard-von-essen** [comment]
See [address](https://packer.io/docs/builders/googlecompute.html#address).

**Comment by JasperWoo** [comment]
@rickard-von-essen That option says it is for external ip address. But in our case, we need Packer to create a vm with a static internal ip address.

**Comment by JasperWoo** [comment]
@rickard-von-essen Can you give a code example for using `address`?

**Comment by rickard-von-essen** [comment]
Add an option to pass an IP address to [`networkInterfaces[].networkIP`]() in `RunInstance`.
