### ISSUE TITLE
Tips for resolving UUID boot errors?

### ISSUE THREAD

**Issue by mcandre** [hashicorp/packer#7871]
Hi, I have been building a few Vagrant base boxes with Packer and generally having a fun time. Unfortunately, some of the newer Linux distributions have begun pushing LVM, swap partitions, encrypted partitions, and device UUID's more aggressively. This is making it more difficult to prepare operating systems as virtual machines.

While a Packer build is processing, a VM may boot successfully several times. But across the Packer / Vagrant boundary, attempts to `vagrant up` the resulting .BOX file can fail. It often appears as an SSH connectivity error to the user, with `VAGRANT_LOG=info` configured.

More intrepid users may launch their hypervisor manually, or perhaps connect with a VNC client, and then see more detailed errors in guest terminals. Screenshot:

https://i.imgur.com/192lUob.png

For example, hibernation and root file systems may fail to load properly. I've seen this happen with libvirt / qemu and with VirtualBox.

So I guess my question is, what can a Linux (or BSD, or Windows...) user do to ensure that a Packer VM, as well as any downstream Vagrant VM's, will boot successfully? Besides encourage OS developers to spend the time to publish official VM's for each release.

**Comment by SwampDragons** [comment]
This is probably a question best reserved for the mailing list; I think I'm the only person currently reading every Github issue that gets opened, and I have no idea other than to say that your Vagrantfile may need some kind of handholding around boot volume order.
