### ISSUE TITLE
Feature Request - Choose an existing VM template for Proxmox Builder

### ISSUE THREAD

**Issue by vikas027** [hashicorp/packer#7873]
In Vagrant builder, we can choose a `source_path` to use an existing image. I could not find anything with [proxmox](https://www.packer.io/docs/builders/proxmox.html) builder. Can you please take this is as a feature request?

I am buzzing @carlpett as it looks like other feature Proxmox feature requests are also with him :) 

Thanks,
Vikas

**Comment by SwampDragons** [comment]
Another analogy would be the vmware-vmx builder. I don't believe the Proxmox builder currently has tools for building from existing vm templates.

**Comment by carlpett** [comment]
Yep, this should be possible to implement via cloning existing VMs or templates.
