### ISSUE TITLE
brew install packer fails at make releasebin

### ISSUE THREAD

**Issue by wblakecannon** [hashicorp/packer#7875]
I am running an Amazon Linux 2 AMI on a t2.small instance using[ Linux Brew](https://docs.brew.sh/Homebrew-on-Linux). Whenever I try to `brew install packer`, when it gets to `make releasebin` I get the following error: 

```
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory - /tmp/packer-20190715-23263-umhk8g/bin/packer
```

**Comment by rickard-von-essen** [comment]
Open an issue with [Linux brew-core](https://github.com/Homebrew/linuxbrew-core/issues).
