### ISSUE TITLE
boot_command fails in parallels if SDK isn't installed 

### ISSUE THREAD

**Issue by benlumia007** [hashicorp/packer#7885]
First of all, the reason why I have created issue due to Packer and I want to verify if it is not Packer issue. I have tried different versions of Packer and I am always ending up with the same problem. I also have tested different packer templates from different repositories and still the same issue where the commands doesn't do anything. 

What I have on my Mac. 
MacOS Mojave 10.14.5
Vagrant 2.2.4
Packer 1.4.2

I created my own packer stuff and when i try to run it, the boot_command fails, i have tested version 1.3.5 - 1.4.2 and i get the same thing. 

i have a log 

https://gist.githubusercontent.com/benlumia007/03c83d8993bb057d8b5dc9b9aa463bef/raw/91924e8d68473f19640bad0bacace6bb1b042507/gistfile1.txt

can you guys verify what's wrong?  is ti a bug or is it something else. 

it should be straight forward, 

```
            "boot_command": [
                "<esc><wait>",
                "<esc><wait>",
                "<enter><wait>",
                "/install/vmlinuz<wait>",
                " auto<wait>",
                " console-setup/ask_detect=false<wait>",
                " console-setup/layoutcode=us<wait>",
                " console-setup/modelcode=pc105<wait>",
                " debconf/frontend=noninteractive<wait>",
                " debian-installer=en_US.UTF-8<wait>",
                " fb=false<wait>",
                " initrd=/install/initrd.gz<wait>",
                " kbd-chooser/method=us<wait>",
                " keyboard-configuration/layout=USA<wait>",
                " keyboard-configuration/variant=USA<wait>",
                " locale=en_US.UTF-8<wait>",
                " netcfg/get_domain=vm<wait>",
                " netcfg/get_hostname=sandbox<wait>",
                " grub-installer/bootdev=/dev/sda<wait>",
                " noapic<wait>",
                " preseed/url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/preseed.cfg<wait>",
                " -- <wait>",
                "<enter><wait>"
            ]
```

**Comment by benlumia007** [comment]
@SwampDragons 
So after a while, I figure it out, It seems like I also need to install the Parallels Virtualization SDK for the boot_command to work. DO you guys have a documentations on this, it should be documented. I have spend like days trying to figure out this out. 

Can you respond to this, and you can close the issue as resolved.

**Comment by rickard-von-essen** [comment]
It's in the docs, but maybe we could programmatically check this and fail with a error message if the SDK is missing.

**Comment by benlumia007** [comment]
yeah, i must have skipped or missed that requirement. but yeh, that would be great if parallels/packer can programmatically check if SDK is installed. :D
