### ISSUE TITLE
Proxmox VE - Boot command is painfully slow in Debian

### ISSUE THREAD

**Issue by vikas027** [hashicorp/packer#7890]
## Environment
OS: Mac OS X 10.14.5 (18F132)
Packer:  v1.4.1
Proxmox VE: v5.4.3
Guest OS: Debain 10 x86_64

## Problem
The boot command in the packer json template gets typed really slow in case of Debian OS. It works fine in CentOS 7 and Fedora. It takes almost 7 mins for the command to be typed on the console.

This problem occurs only when used insecure https, I have just used a valid SSL cert and set `"insecure_skip_tls_verify": false,` things are pretty good now.

## Packer Log
**Debug Log**
```bash
2019/07/20 22:36:24 Starting build run: proxmox
2019/07/20 22:36:24 Running builder: proxmox
2019/07/20 22:36:24 [INFO] (telemetry) Starting builder proxmox
==> proxmox: Creating VM
==> proxmox: Starting VM
2019/07/20 22:36:29 packer: 2019/07/20 22:36:29 Found available port: 8571 on IP: 0.0.0.0
==> proxmox: Starting HTTP server on port 8571
==> proxmox: Waiting 10s for boot
==> proxmox: Typing the boot command
2019/07/20 22:36:40 packer: 2019/07/20 22:36:40 [INFO] Waiting 1s
2019/07/20 22:36:50 packer: 2019/07/20 22:36:50 [INFO] Waiting 1s
2019/07/20 22:37:49 packer: 2019/07/20 22:37:49 [INFO] Waiting 1s
2019/07/20 22:38:23 packer: 2019/07/20 22:38:23 [INFO] Waiting 1s
2019/07/20 22:38:30 packer: 2019/07/20 22:38:30 [INFO] Waiting 1s
2019/07/20 22:38:52 packer: 2019/07/20 22:38:52 [INFO] Waiting 1s
2019/07/20 22:39:18 packer: 2019/07/20 22:39:18 [INFO] Waiting 1s
2019/07/20 22:40:01 packer: 2019/07/20 22:40:01 [INFO] Waiting 1s
2019/07/20 22:40:36 packer: 2019/07/20 22:40:36 [INFO] Waiting 1s
2019/07/20 22:41:10 packer: 2019/07/20 22:41:10 [INFO] Waiting 1s
2019/07/20 22:41:22 packer: 2019/07/20 22:41:22 [INFO] Waiting 1s
2019/07/20 22:41:59 packer: 2019/07/20 22:41:59 [INFO] Waiting 1s
2019/07/20 22:42:35 packer: 2019/07/20 22:42:35 [INFO] Waiting 1s
2019/07/20 22:43:09 packer: 2019/07/20 22:43:09 [INFO] Waiting 1s
2019/07/20 22:43:46 packer: 2019/07/20 22:43:46 [INFO] Waiting 1s
2019/07/20 22:43:48 packer: 2019/07/20 22:43:48 [INFO] Waiting 1s
2019/07/20 22:43:53 packer: 2019/07/20 22:43:53 [DEBUG] Unable to get address during connection step: 500 QEMU guest agent is not running
2019/07/20 22:43:53 packer: 2019/07/20 22:43:53 [INFO] Waiting for SSH, up to timeout: 1h0m0s
==> proxmox: Waiting for SSH to become available...
```

**Packer Template**
```json
{
  "variables": {
    "proxmox_user": "root@pam",
    "proxmox_pass": "proxmox",
    "proxmox_node": "proxmox",
    "ssh_name": "vagrant",
    "ssh_pass": "vagrant",
    "hostname": "debian-10",
    "local_domain": "my.domain",
    "iso_file": "local:iso/debian-10.0.0-amd64-netinst.iso"
  },
  "builders": [
    {
      "type": "proxmox",
      "proxmox_url": "https://192.168.0.28:8006/api2/json",
      "insecure_skip_tls_verify": true,
      "username": "{{user `proxmox_user`}}",
      "password": "{{user `proxmox_pass`}}",
      "node": "{{user `proxmox_node`}}",
      "os": "l26",
      "network_adapters": [
        {
          "bridge": "vmbr0"
        }
      ],
      "disks": [
        {
          "type": "virtio",
          "disk_size": "20G",
          "storage_pool": "local-lvm",
          "storage_pool_type": "lvm"
        }
      ],
      "memory": 2500,
      "vm_name": "packer-debian-10-base",
      "vm_id": 102,
      "cores": 1,
      "iso_file": "{{user `iso_file`}}",
      "http_directory": "http",
      "boot_wait": "10s",
      "boot_command": [
        "<esc><wait>",
        "install <wait>",
        " preseed/url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/debian_10.cfg <wait>",
        "debian-installer=en_US.UTF-8 <wait>",
        "auto <wait>",
        "locale=en_US.UTF-8 <wait>",
        "kbd-chooser/method=us <wait>",
        "keyboard-configuration/xkb-keymap=us <wait>",
        "netcfg/get_hostname={{user `hostname`}} <wait>",
        "netcfg/get_domain={{ user `local_domain` }} <wait>",
        "fb=false <wait>",
        "debconf/frontend=noninteractive <wait>",
        "console-setup/ask_detect=false <wait>",
        "console-keymaps-at/keymap=us <wait>",
        "grub-installer/bootdev=/dev/vda <wait>",
        "<enter><wait>"
      ],
      "ssh_username": "{{user `ssh_name`}}",
      "ssh_password": "{{user `ssh_pass`}}",
      "ssh_port": 22,
      "ssh_timeout": "60m",
      "unmount_iso": true,
      "template_name": "debian-10",
      "template_description": "Debian 10, generated on {{ isotime \"2006-01-02T15:04:05Z\" }}"
    }
  ]
}
```

**Comment by johanfleury** [comment]
@vikas027, were you able to make a Debian installation on Proxmox?

I'm also facing the slowness issue with `insecure_skip_tls_verify`, but most importantly, Packer doesn't seems to do anything on the VM. When I start a console while packer is "typing the boot command", I see nothing moving and the Debian installer stays on the menu.

Here is the `boot_command` I used:

```
      "boot_wait": "10s",
      "boot_command": [
        "<esc><wait>",
        "auto net.ifnames=0 preseed/url=[REDACTED]<wait>",
        "<enter>"
      ],
```

**Comment by johanfleury** [comment]
Ok, never mind, the issue was due to the user not having the `Sys.Modify` right (see #7541).

**Comment by vikas027** [comment]
@johanfleury Cool! yeah, I didn't bother to create individual users. I am using root user which is why I did not face the issue.

**Comment by gentoo9ball** [comment]
@vikas027 Any luck yet? I can't get the boot command to send any keys. What concerns me is that I'm also not getting the "Starting HTTP server on port" message. I've even tested by copying your exact config, however I'm using packer v1.4.3.

**Comment by carlpett** [comment]
Sorry for not taking a look at this sooner. I can repro at least, will dig a bit and see what I can find.

**Comment by carlpett** [comment]
@vikas027 Are you sure you got faster results on Fedora/CentOS? I'm unable to reproduce that part. I added some measurements around the "send key" part of the code, and here are the results:
```
Fedora: 0.5:0.032s, 0.9:0.037s, 0.99:0.046s
Debian: 0.5:0.033s, 0.9:0.038s, 0.99:0.053s
```

So, barely any difference, most likely just fluctuations. In my experience Fedora/CentOS boot commands are _much_ shorter though, so it will be faster in that way :) 

Anyway, I can't see a way to speed up the key entry itself, the way we send keys requires us to send a api request for every input. And those seem to be roughly equally fast regardless of OS.
What we _can_ do though is tweak the bits around. Without any code change at all, you can set the `boot_key_interval` in your configuration, for example to `"boot_key_interval": "1ms"`. As it is, there is an artificial delay between each "key press", which by default is 100ms. I assume this is because some builders/command typers do not work well when the keys arrive to quickly. In the proxmox case, we might even be able to remove it entirely (but that will not come until next release in that case). 
You also insert 1 second waits at the end of each of your lines, but I assume that is deliberate? Otherwise you can save a couple of seconds there as well.

**Comment by vikas027** [comment]
Thanks @carlpett, that would help a bit. But still unsure why `https` works faster than `http`. Anyways, I am good for now as I am using https now with some `dnsmasq` magic.
