### ISSUE TITLE
Packer with ansible provisioner is getting stuck at become password

### ISSUE THREAD

**Issue by chakradharavarma** [hashicorp/packer#7895]
My packer build gets stuck at become_password of ansible and does not move from there even after entering yes or just enter command. It used to work well earlier a week,

     "provisioners": [
                 {
                   "type": "ansible",
                   "playbook_file": "xxx.yml",
                   "extra_arguments": [ "-Kb" ],
                   "user": "ec2-user"
                 },
                 
              
               
          /usr/bin/packer build -var 'ami_name=jefferies-amznlinux-v20190719-ami' awsAMI.json
amazon-ebs output will be in this color.

==> amazon-ebs: Force Deregister flag found, skipping prevalidating AMI Name
    amazon-ebs: Found Image ID: ami-0b898040803850657
==> amazon-ebs: Using existing SSH private key
==> amazon-ebs: Creating temporary security group for this instance: packer_5d35bc54-0386-cd84-f5c2-407e06abf8db
==> amazon-ebs: Authorizing access to port 22 from [0.0.0.0/0] in the temporary security groups...
==> amazon-ebs: Launching a source AWS instance...
==> amazon-ebs: Adding tags to source instance
    amazon-ebs: Adding tag: "Name": "Packer Builder"
    amazon-ebs: Instance ID: i-01f4068691951159f
==> amazon-ebs: Waiting for instance (i-01f4068691951159f) to become ready...
==> amazon-ebs: Using ssh communicator to connect: 10.207.60.145
==> amazon-ebs: Waiting for SSH to become available...
==> amazon-ebs: Connected to SSH!
==> amazon-ebs: Provisioning with Ansible...
==> amazon-ebs: Executing Ansible: ansible-playbook --extra-vars packer_build_name=amazon-ebs packer_builder_type=amazon-ebs -o IdentitiesOnly=yes -i /tmp/packer-provisioner-ansible443518053 /apps/ansible/playbooks/Base/Aws.yml -e ansible_ssh_private_key_file=/tmp/ansible-key339026334 -Kb
BECOME password:

My packer version is 1.4.1

Am I missing some thing here, Please help.

**Comment by SwampDragons** [comment]
>  It used to work well earlier a week
Did you upgrade Ansible recently? We have had an issue with the most recent upgrade because of pipelining. See https://github.com/hashicorp/packer/issues/7667 for more context. If that is the issue, can we close this one as a duplicate?

**Comment by chakradharavarma** [comment]
Yeah that is correct, we upgraded ansible to 2.8.2 recently. we can close this as duplicate.

**Comment by SwampDragons** [comment]
Thanks! Much easier to track it in one place.
