### ISSUE TITLE
PACKER_TMP_DIR does not move .packer.d out of HOME

### ISSUE THREAD

**Issue by OJFord** [hashicorp/packer#7897]
As far as I can tell, there's no way of moving `.packer.d/` out of `$HOME`.

#4042 was supposed to move it with `$PACKER_CONFIG_DIR` but closed on the basis that `$PACKER_TMP_DIR` took care of it, but that's not doing it for me:

```
~>rm -r .packer.d/
~>set -x PACKER_TMP_DIR "$XDG_CACHE_HOME/packer"
~>packer version
Packer v1.4.1

Your version of Packer is out of date! The latest version
is 1.4.2. You can update by downloading from www.packer.io/downloads.html
~>ll .packer.d/
drwxr-xr-x ojf staff 128 B  Mon Jul 22 19:00:38 2019   .
drwxr-xr-x ojf staff   1 KB Mon Jul 22 19:00:38 2019   ..
.rw-r--r-- ojf staff 332 B  Mon Jul 22 19:00:38 2019   checkpoint_cache
.rw-r--r-- ojf staff 394 B  Mon Jul 22 19:00:38 2019   checkpoint_signature
~>echo "$XDG_CACHE_HOME"
/Users/ojf/.cache
~>
```

See also #3443.

**Comment by sudhir05** [comment]
I am getting different issue, when i used environment variable PACKER_TMP_DIR it has moved out of .packer.d but it is creating directory using user root. However, the packer is running job using user Jenkins. There, i am getting error access denied when it is trying to upload.

**Comment by SwampDragons** [comment]
Thanks for opening. I just looked into this, and it looks like the PACKER_TMP_DIR is currently only respected for the Docker builder. I have a vague memory of someone refactoring and cleaning up the temp dir handling and I wonder if this was a casualty of that refactor. I'll take a look and see if I can find the history of that refactor and restore the functionality for the other builders.

**Comment by SwampDragons** [comment]
found that historical context: #7102

**Comment by SwampDragons** [comment]
Try out the patched build found here https://circleci.com/gh/hashicorp/packer/7827#artifacts/containers/0 with the env var `PACKER_CONFIG_DIR` and let me know if that's the behavior you need.

**Comment by OJFord** [comment]
@SwampDragons That's an improvement, but puts a directory named `.packer.d` inside `$PACKER_CONFIG_DIR` instead of inside `$HOME`. I'd say more usual behaviour would be to use `$PACKER_CONFIG_DIR` *as* the directory, instead of `$HOME/.packer.d`.

That's fine though, doesn't really bother me what packer puts there as long as it's contained where I say - only other thing I wonder is if this is really a 'config' dir? Seems more like it's used as a cache.

See also XDG standard for cache/config/data homes:
https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by SwampDragons** [comment]
I think reworking what we place inside .packer.d is outside of the scope of this bug report, but you're right that we seem to be using this in some ways analogous to the packer_cache. I'll keep it in mine for future efforts to clean up the core. 

I think for simplicity's sake I'm going to leave it creating .packer.d for now.
