### ISSUE TITLE
vmware-vmx how to pass ssh key to use

### ISSUE THREAD

**Issue by nodesocket** [hashicorp/packer#7898]
Using the `vmware-vmx` builder I don't see a way to specify the SSH private key to use. The only options I see are:

     ssh_username
     ssh_password

SSH access using passwords are disabled and I only allow public key SSH. Thanks.

**Comment by alikor** [comment]
why was this closed without comment? I also have this question

**Comment by rickard-von-essen** [comment]
It was closed by the author. See [ssh_private_key_file](https://packer.io/docs/templates/communicator.html#ssh_private_key_file)
