### ISSUE TITLE
LXC Builder

### ISSUE THREAD

**Issue by kelseyhightower** [hashicorp/packer#790]
Packer should support the ability to build Linux containers.

**Comment by cburroughs** [comment]
So google for 'packer lxc' will quickly turn up:
 * Two projects https://github.com/ustream/packer-builder-lxc & https://github.com/kelseyhightower/packer-builder-lxc
 * The docker builder docs https://www.packer.io/docs/builders/docker.html which say "Packer is able to repeatably build these LXC containers using portable provisioning scripts."
 * This issue, which has "no near-term plan to finish it".

So I I'm a bit confused on the status of this packer lxc support

**Comment by vtolstov** [comment]
may be i can work on lxc builder, as i'm interest of this think. i think that for base i'm use https://github.com/ustream/packer-builder-lxc

**Comment by oker1** [comment]
@vtolstov feel free to submit pull requests there, I'll get to the open ones soon.

**Comment by rvalle** [comment]
What is the status of this? this thread mentions a couple of repositories, is there any that works? is it supported?

**Comment by Shashwatsh** [comment]
+1
