### ISSUE TITLE
tencentcloud-cvm: Deleting temporary keypair failed

### ISSUE THREAD

**Issue by freidenker** [hashicorp/packer#7910]
tencentcloud-cvm: delete keypair failed, please delete it manually, keyId: skey-5885c65t, err: retry count exhausted. Last err: [TencentCloudSDKError] Code=InvalidKeyPair.NotSupported, Message=The request does not support the key pair `skey-xxxxxxxx` which associastes with image.

**Comment by SwampDragons** [comment]
@zqfan can you take a look at this?  If not, can someone else at tencent? I notice we forgot to have you add someone to the CODEOWNERS file, so I'm not sure who to ask to take this on.

**Comment by zqfan** [comment]
@freidenker it should have printed the request id, please paste it thanks!

**Comment by freidenker** [comment]
> @freidenker it should have printed the request id, please paste it thanks!
below is another try. actually it built image successfully, but still keep the temp keypair.

==> tencentcloud-cvm: delete keypair failed, please delete it manually, keyId: skey-fasj0rcn, err: retry count exhausted. Last err: [TencentCloudSDKError] Code=InvalidKeyPair.NotSupported, Message=The request does not support the key pair `skey-fasj0rcn` which associastes with image., RequestId=56c15331-9743-43f7-93c9-f62e4ca7c88f

**Comment by zqfan** [comment]
@freidenker Which version of packer are you using? Since 1.4.2, it should just occasionally fail.

**Comment by freidenker** [comment]
no, it always failed, both of 1.4.0 and 1.4.2.  I am not sure if there is some limits about the key pair associated with image or instance to delete. by the way, current version does not support **BANDWIDTH_PACKAGE** internet access charge type, so I had to make a work around for it.

**Comment by likexian** [comment]
Hello @freidenker 
Sorry for the delay, this have been fixed in packer 1.4.5, would you please have a try with the latest version?

**Comment by likexian** [comment]
Hello @SwampDragons
Any issues about tencentcloud please assign to me please.

**Comment by SwampDragons** [comment]
I don't see any other issues currently open but I'll make sure to assign you if any come in. Thanks!
