### ISSUE TITLE
introduce run_id template function

### ISSUE THREAD

**Issue by tb3088** [hashicorp/packer#7919]
Which returns the `PACKER_RUN_UUID` value.
This is a follow up to #4446 and punted on in #4506.

> seems useful but I'm lacking concrete use cases.

Tagging runtime volumes via `run_volume_tags`. During `launch_block_device_mappings` one might set `delete_on_termination` to false as that is the desired behavior for the resulting AMI. However instead of actually cleaning up after itself, Packer leaves those volumes hanging around.

The solution is either:
* fix Packer so it cleans up *all* of its volume artifacts (needs a bug report)
* force user to do it post-run by hooking manifest.json

Additionally there may also be value in tagging finalized AMIs or EC2 instances while in-flight with the PACKER_RUN_UUID value.

**Comment by SwampDragons** [comment]
I think this makes sense to add as part of https://github.com/hashicorp/packer/issues/7079.  I'm working on that currently in https://github.com/hashicorp/packer/pull/7866 and will make sure that PACKER_RUN_UUID gets included as part of those larger changes.  

I was hoping to have that polished and merged for the 1.4.3 release but realistically it's probably gonna have to be backwards-incompatible with the change to the plugin signature so it'll be part of the 1.5 release.
