### ISSUE TITLE
Build 'googlecompute' errored: unexpected EOF (Packer 1.4.3)

### ISSUE THREAD

**Issue by EndGameX** [hashicorp/packer#7921]
Trying to build a Linux image in Google Compute.
   Packer version: 1.4.3
   Linux version: Ubuntu 16.04 LTS
Crash log:
   https://gist.github.com/EndGameX/ac334446f391702c5dc2c6456853184f
Template:
   https://gist.github.com/EndGameX/52d9d97e10697f4626966e0aca0e195e

**Comment by SwampDragons** [comment]
Thanks, good catch. I've opened a PR to fix this. (linked above) and builds of the fix can be found here: https://circleci.com/gh/hashicorp/packer/8113#artifacts/containers/0

**Comment by EndGameX** [comment]
Thank you!  I'm new to this.  How do I apply the fix?

**Comment by SwampDragons** [comment]
It's a self-contained Packer build. Download whatever binary suits your build machine's architecture, unzip it, and either replace your installed packer binary, or call it directly rather than calling the version of Packer you have installed.

**Comment by EndGameX** [comment]
Got it!  The build was successful.  Thank you!
