### ISSUE TITLE
use cgo for arm builds

### ISSUE THREAD

**Issue by SwampDragons** [hashicorp/packer#7928]
Need to investigate using CGO to build arm releases: see 

https://github.com/golang/go/issues/32912

**Comment by rickard-von-essen** [comment]
Previously we said no to dependencies that need CGO because then you can't cross compile.

**Comment by SwampDragons** [comment]
I got a note internally to HC to look into this; I'll make sure we don't break anything long term but right now apparently our arm builds are crashing because of the linked bug.

**Comment by SwampDragons** [comment]
Looks like this was already resolved upstream so we don't need to do anything.
