### ISSUE TITLE
Concurrency issue for spot instances

### ISSUE THREAD

**Issue by arjunanashok** [hashicorp/packer#7933]
_Please read these instructions before submitting_
Hello,
  we are using the packer version "1.4.2" for our AMI creation, we got the concurrency issue and being blocked in creating AMI.  we understood that there is a fix for this issue and fix is available under the master branch.

Could you please provide us when would you release the new version? 

This helps us to start looking for work around . 

Thanks

**Comment by Matrikss** [comment]
I'm also in this situation.

**Comment by mauriziod** [comment]
Please let's keep adding some 👍  to the issue so it get prioritised

**Comment by SwampDragons** [comment]
The next release will be in about two weeks. While you wait for the 1.4.3 release You can download binaries containing the patch from https://github.com/hashicorp/packer/pull/7818 at 

https://circleci.com/gh/hashicorp/packer/6221#artifacts/containers/0

For future reference, any time there is a PR merged and you want to use a patched binary while you wait for a release, you can click "view details" on the PR that got merged, then click the "details" link on the "ci/circleci: store_artifacts" build, and click the artifacts tab to download a patched binary.

**Comment by azr** [comment]
I will also tag a nightly build of master in case.
