### ISSUE TITLE
Packer /tmp out of space

### ISSUE THREAD

**Issue by fitchxlin** [hashicorp/packer#7943]
Any fix for /tmp out of space when running packer?

**Comment by tb3088** [comment]
How about don't use a "too small" /tmp? It's your system, be cognizant of what your box is capable of and which builders are in play. If your OS mounts /tmp from free RAM, downloading an ISO or docker image will quickly consume all space, as you no doubt found out. Instruct Packer to use something other than /tmp for it's temporary location. Post #6950 and #7897 and newer releases, I'm not sure what the mechanism is any more. PACKER_TMP_DIR=<some big location> used to be a thing.

**Comment by SwampDragons** [comment]
You should be able to move the location of the tempdir Packer uses by setting an environment variable. It'll be slightly different which environment variable to use depending on your operating system:

On Unix systems, Packer tries to use the env var `$TMPDIR` to figure out where to create temporary files, but defaults to `/tmp` if that env var is unset or empty.

On Windows, it uses GetTempPath, returning the first non-empty value from %TMP%, %TEMP%, %USERPROFILE%, or the Windows directory.

On Plan 9, it returns /tmp.

By setting the relevant var, you can make sure Packer uses a spot on your system with more disk space.
