### ISSUE TITLE
 failed to interpolate a variable

### ISSUE THREAD

**Issue by tormath1** [hashicorp/packer#7952]
Hi, 

I am not able to use `vault` in my build :disappointed_relieved: .

Do I miss something ? 

```
$ packer version
Packer v1.4.2
$ uname -srvmo
Linux 5.2.3-arch1-1-ARCH #1 SMP PREEMPT Fri Jul 26 08:13:47 UTC 2019 x86_64 GNU/Linux
$ cat build.json 
{
	"variables": {
		"cert": "{{vault `kv/kvm-06` `svc-sudop`}}"
	},
	"builders": [{
		"type": "docker",
		"image": "alpine:3.9",
		"commit": "true"
	}],
	"provisioners": [{
		"type": "shell",
		"inline": "ls"
	}]
}
$ packer validate build.json 
Error initializing core: Failed to interpolate "cert": "{{vault `kv/kvm-06` `svc-sudop`}}": Please make sure that the variable you're referencing has been defined; Packer treats all variables used to interpolate other user varaibles as required.

```

[logs](https://gist.github.com/tormath1/72539e150261c93f1e307ca19d697bf4)

**Comment by SwampDragons** [comment]
I recently merged code that'll at least give you a more useful error message about what you're facing: https://github.com/hashicorp/packer/pull/7854. If you want the branch build for that PR you can download it [here](https://circleci.com/gh/hashicorp/packer/6931#artifacts/containers/0).

**Comment by tormath1** [comment]
Oh yeah. Thanks for this PR, it's easier to debug !
