### ISSUE TITLE
Feature request: amazon-chroot builder in Fargate

### ISSUE THREAD

**Issue by dsilvasc** [hashicorp/packer#7955]
The amazon-ebs builder takes several minutes to start and stop an ec2 instance to modify and snapshot.  The amazon-chroot builder is significantly faster, but it requires an ec2 instance running continuously, it runs as root to mount/chroot, and it needs and some coordination mechanism for a user to request a new build and receive a result -- for instance via ssh or an RPC server on the ec2 instance.

A decent middle ground might be running packer as an ECS task in AWS Fargate: it starts more quickly than an ec2 instance (faster than amazon-ebs), it runs as an isolated container (arguably safer than amazon-chroot) and the aws cli can run tasks as a remote command.

ECS/Fargate runs Docker containers.  When trying to run the amazon-chroot builder inside a docker container on an ec2 vm, the build fails with:

```
==> amazon-chroot: Checking the root device on source AMI...
==> amazon-chroot: Creating the root volume...
==> amazon-chroot: Attaching the root volume to /dev/sdf
==> amazon-chroot: Mounting the root device...
==> amazon-chroot: Error mounting root volume: exit status 32
==> amazon-chroot: Stderr: mount: /mnt/packer: special device /dev/xvdf1 does not exist.
```

Setting `nvme_device_path` to `/dev/nvme1n1p1` like the example in https://github.com/hashicorp/packer/pull/6295 doesn't help either:

```
==> amazon-chroot: Stderr: mount: /mnt/packer: special device /dev/nvme1n1p1 does not exist.
```

It would be nice if packer's amazon-chroot builder worked inside docker containers and inside of ECS/Fargate as well.

**Comment by rickard-von-essen** [comment]
Thanks for the request but unfortunately AWS ECS Fargate can't attach EBS volumes so it won't work.
