### ISSUE TITLE
Revisit support for "booleans" with three settings

### ISSUE THREAD

**Issue by dbilling** [hashicorp/packer#7959]
Packer has cases of configuration "boolean" options that have three settings, where the three settings are typically:
true -  turn the feature on
false - turn the feature off
not coded - leave the feature the way you found it.

I'm not so much concerned that there are three options for a boolean variable  - I like all the possible settings above - but I've found this extremely problematic because it breaks the ability to control all three configuration options with user variables.   for example, in the packer config below, there's no way to set the "aws_ena_support" variable in a way that will achieve the "not coded" functionality.   (just fyi the snippet below is accepted by the parser, but ena_support ends up as "false")

While I specifically ran into this while working with the ena_support configuration option on the amazon-ebs builder, but I'm making this issue more generic so all cases can be fixed in packer.

```
"variables": {
    "aws_ena_support": "",
  },
  "builders": [
    {
      "type": "amazon-ebs",
        "ena_support": "{{user `aws_ena_support`}}",
        ...
     }
   ]
...
```

My proposed fix for this is to change packer so that when someone codes the snippet above, the ena_support would be intepreted as "not coded" instead of "false".

However I would be happy with any fix for these situations so that folks using user variables can achieve all three possible configuration settings.

**Comment by SwampDragons** [comment]
Ouch, good point. We definitely need to figure out a way to preserve "unset" in user variables.
