### ISSUE TITLE
Crash on standard Ubuntu image creation on Azure w/ Packer.

### ISSUE THREAD

**Issue by Adron** [hashicorp/packer#7961]
BUG:

I've been running a basic `packer build clusternode.json` to build an image, very simple image, that I got from the Hashicorp Docs and have been getting an error on the final cleanup of resources as shown in crash.log.

 - Version: `packer version` 1.4.2
 - Host: Running on...
   - Linux working 4.15.0-55-generic #60-Ubuntu SMP Tue Jul 2 18:22:20 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
   - Ubuntu 18.04.2 LTS Bionic Beaver
 - Crash Log: https://gist.github.com/Adron/10e760980bef1663d52bf6240ed89fda
 - Gist of Packer File: https://gist.github.com/Adron/72ee2b01e15e400a505b423de6d7284f

However, even with this failure, it appears that the image is being created and I am able to create a VM from the image after the fact. But being there is an error occurring on cleanup leaves me with a problematic automation of this capability since it appears the error isn't a correct triggering of the error. But then, maybe something is still wrong with the overall setup?  :man_shrugging: 

Updated the blog entry [here](https://compositecode.blog/2019/08/06/error-build-azure-arm-errored-adal-failed-to-execute-the-refresh-request-error/) with even [more details](https://compositecode.blog/2019/08/06/error-build-azure-arm-errored-adal-failed-to-execute-the-refresh-request-error/) of the overall story.

**Comment by SwampDragons** [comment]
This might be a duplicate of https://github.com/hashicorp/packer/issues/7816, which should have been fixed by https://github.com/hashicorp/packer/pull/7837. Any chance you can test out one of the linked builds and let me know if that solves things for you?

**Comment by Adron** [comment]
Will give it a go @SwampDragons and report back.

**Comment by Adron** [comment]
Looks like that was the issue, I regressed to 1.4.1 and it built just fine. Back to 1.4.2 error occurred again, and confirmed that the patch in #7837 fixed it. Cheers, thanks @SwampDragons!  :metal:
