### ISSUE TITLE
FEATURE: Allow Docker images to be built remotely instead of on the host

### ISSUE THREAD

**Issue by dnk8n** [hashicorp/packer#7963]
Why? For the same reason ebs-builder doesn't install everything locally and leave you with an AMI on your own dev machine, then push to Amazon.

I speak specifically about Amazon AWS, but other cloud providers should also apply (so this is a general request which applies to all builders)

Use-case: The host is often a docker container with minimal resources, using docker image: `hashicorp/packer:1.4.2` for example. In many cases the `docker run` command is locked down as well.

It would be great if you could allow a similar workflow to ebs-builder, except end up with a Docker image being pushed instead of an AMI. That is, instead of provisioning locally, a temporary instance is created in ones' own VPC to do the heavy lifting.

Currently, everything is in place to allow that (if Packer and Docker are pre-installed on the remote instance which does the provisioning), except you are forced to create an AMI you don't care about.

Another use cases, say I need 8GB of RAM to compile something, then it would be useful to be able to use Packer's functionalities to use a tiny 'pilot' CI/CD runner to just run packer, with all heavy lifting done in one's own VPC.

**Comment by dnk8n** [comment]
For now I resort to adding this to the last stage to make the Packer build always 'fail':

```
    {
      "type": "shell-local",
      "inline": [
        "echo 'This job passed! Hack applied that skips AMI creation.' > {{template_dir}}/job_status",
        "exit 1"
      ]
    }
```

Then I add an `||` so that the command afterwards (which is always run) determines whether the entire command passed or failed.

`packer build template.json || cat job_status`

If the job actually failed, there would be no job_status file and the job would then fail because of the cat command failing. If it does exist, that is because the job passed, so we print out the message contained in the file.

I feel dirty.

**Comment by rickard-von-essen** [comment]
Hmm that comment feels a bit out of context for this issue. Maybe it was meant for another issue?

**Comment by dnk8n** [comment]
@rickard-von-essen No, it is applicable. What I said in my comment allows all steps to be complete without creating AMI.

This allows you to use a pre-setup AMI in your own VPC, with Packer and Docker installed. You then run Packer on the host and on the remote temporary instance. The packer on the remote temporary instance would use docker builder and push to Docker registry from there.

Does that make sense?

It is a workaround to this feature which doesn't exist.

**Comment by SwampDragons** [comment]
Sounds like this is another use case for a flag to skip registering the ami, to prevent your hack.

That said I'm not totally clear on whether you're asking for some builder that will just run docker on a host your provide, or specifically a builder that runs on amazon and creates and exports a docker container from a running amazon instance. Can you clarify for me?

**Comment by dnk8n** [comment]
I would say both. But I was talking about the first of the two options
below.

An option to supply an existing AMI (that must have Docker preinstalled or
maybe if it doesn't already exist Docker can be installed via
https://get.docker.com/), then Packer would first do steps in much the same
way as ebs-builder, except creating AMI and pushing to docker registry
instead.

Or define an existing host that has Docker pre-installed, here you would
have to define existing ssh keys. (This is less useful feature because
already we could use something like chef or ansible to run Packer with
Docker builder on this host)
