### ISSUE TITLE
Hyper-V build fails with 0x80070057

### ISSUE THREAD

**Issue by stefanes** [hashicorp/packer#7964]
Hyper-V build fails with `0x80070057` using Packer version 1.4.2. Same setup works just fine with version 1.3.4.

Also, `"iso_checksum_type": "none"` is ignored on 1.4.2 but honoured on 1.3.4.

- Packer version: **1.4.2**
- Host platform: **Windows 10** (running with administrator privileges)
- Debug log output and example template: <https://gist.github.com/stefanes/0909bf565db2e5c21c6b0cdabb26a37f>

**Comment by nywilken** [comment]
Is this still an issue in the latest release of Packer?
