### ISSUE TITLE
Export Image is to small 74KB should be ca 400MB

### ISSUE THREAD

**Issue by feckert** [hashicorp/packer#7965]
Environment:
- Packer version from `1.4.2`
- debian 9 X86_64 on native (development)
- debian 9 X86_64 on VMware (CI/CD)

Development host:
I am building opnsense version 19.07 on my host system with packer. Every think works as expected. Build is successful and the exported image could be load with virtualbox.

Export log on the Development host build:
https://gist.github.com/feckert/982801ea36cd73dd149c8015ed072b6c

Gitlab CI/CD:
With gitlab CI/CD I am building my releases. The build is also successful, but the exported image is too small ! Its only 74KB big. If I open this with the vi editor I see only the ova content. NO VMDK.

I am using this build system for debian appliances as well and every thing works as expected. The images are OK. So my CI/CD works. Only for the opnsense (BSD) it does not!

The following line does appear on my devleopment host but not on the Gitlab CI/CD system. I do not know what the output  means!

> 2019/08/09 14:37:35 Builds completed. Waiting on interrupt barrier...

That is the only difference what I can see

Export log on the Gitlab CI/CD build on a gitlab-runner:
https://gist.github.com/feckert/09cc0682fa5ecdfbe62e96e45a40fe18

**Comment by rickard-von-essen** [comment]
Please supply the information requested in the issue template:
- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your [gist](https://gist.github.com).

**Comment by feckert** [comment]
@rickard-von-essen thanks for the reminder.
This is the command and json file I am executing on my system and on the Gitlab CI/CD
https://gist.github.com/feckert/b2d8c0cb5cd1f480605251a9a6116ae8

To build this you have to download opensense from this URL https://opnsense.org/download/ with the drop down selection **amd64** and **DVD** and extract the bz2 file into the packer working dl directory.
The sha256 must be after extracting **ce0525586c4ce680a0d67e2ea9d419137b4eef714e77d7d1d2ed1236dc880f54**

**Comment by feckert** [comment]
Maby this is related to the closed issue https://github.com/hashicorp/packer/issues/5990

**Comment by feckert** [comment]
@rickard-von-essen ping
Do you need additional information to reproduce my issue?

**Comment by rickard-von-essen** [comment]
You closed the issue.

**Comment by feckert** [comment]
Yes I have seen but after this mistake I reopened it few seconds after again.
