### ISSUE TITLE
Evaluate all user interpolated boot commands prior to execution

### ISSUE THREAD

**Issue by mcandre** [hashicorp/packer#7972]
Packer lazily evaluates `boot_command`, resulting in problems that could be detected early, such as invalid user interpolation syntax, failing the build quite late, after several steps into the running build.

**Comment by SwampDragons** [comment]
I can see how this is annoying, but in this case we have to lazily evaluate the boot command because some of the values we need to interpolate may not yet exist at the very beginning of the build. (for example, HTTP_IP)
