### ISSUE TITLE
support resource tagging in the shared_image_gallery_destination

### ISSUE THREAD

**Issue by mikeclearbank** [hashicorp/packer#7973]
Enable the shared_image_gallery_destination resource to support creating Azure resource tags. 
This would allow the ability to provide further detail about the image.

example usage:

```
      "shared_image_gallery_destination": {
        "resource_group": "{{user `image_resource_group`}}",
        "gallery_name": "{{user `shared_image_gallery_name`}}",
        "image_name": "{{user `image_name`}}",
        "image_version": "{{user `image_version`}}",
        "replication_regions": [
          {{ user `replication_regions`}}
        ],
        "tags": [ 
             "tag1", "tag2", "tag3"
         ]
````

the tag's collection would support a list of tags to apply to the image resource:
```
       "tags": [ 
             "tag1", "tag2", "tag3"
         ]
````

**Comment by mikeclearbank** [comment]
https://www.packer.io/docs/builders/azure.html#azure_tags - already supported

**Comment by nielsvbrecht** [comment]
> https://www.packer.io/docs/builders/azure.html#azure_tags - already supported

I dont see anything in the documentation about support for tags for the image in the gallery. Nor does your suggestion work. The only tags that are supported are on the resources packer deploys during the build. Or have I missed anything?
