### ISSUE TITLE
Vagrant builder: Add a configuration option to prevent replacement of vagrant user's SSH keypair

### ISSUE THREAD

**Issue by tjanez** [hashicorp/packer#7974]
When using Packer to build a custom [Vagrant Base box](https://www.vagrantup.com/docs/boxes/base.html#default-user-settings), one needs to keep the 
[insecure Vagrant SSH keypair](https://www.vagrantup.com/docs/boxes/base.html#quot-vagrant-quot-user) for the Base box to work for users out-of-the-box.

This is easily achieved by setting Vagrant's [`config.ssh.insert_key` option](https://www.vagrantup.com/docs/vagrantfile/ssh_settings.html#config-ssh-insert_key) to `false`.
In the current version of Packer, this option is not set and Vagrant automatically inserts a new keypair during every invocation of the Vagrant builder.

I propose we extend Packer's Vagrant template to support configuring `config.ssh.insert_key` via a Vagrant builder's configuration option.

**Comment by SwampDragons** [comment]
@chrisroberts thoughts on this one?

**Comment by chrisroberts** [comment]
As long as the Vagrantfile being used to initially up the guest is not persisted in the final box, disabling the `insert_key` option would likely be the ideal default configuration. This way the key set within the original box would still be what's defined in the resultant box.
