### ISSUE TITLE
Windows2016 guest on RHEL linux host never ending winrm loop

### ISSUE THREAD

**Issue by automationbuilder360** [hashicorp/packer#7975]
Hi All,

Am new to Packer, am trying to create a Windows 2016 guest on VBOX hosted on RHEL VM.
using virtualbox-iso builders and trying to test my windows customized image.
the idea to create VM and get windows 2016 installed through iso and then connect with ansible and run couple of test cases. part of my image building and testing pipeline.

however after the VM gets created it waits for winrm untill the timeout and just fails,
i have no idea to see whats happening on the guest.
this is a tested iso which works great on vmware. any help is much appreciated

**Comment by automationbuilder360** [comment]
Here is the output

==> virtualbox-iso: Retrieving ISO
    virtualbox-iso: Using file in-place: file:///home/myhome/iso/mycustom_windows2016.v1.0.ISO
==> virtualbox-iso: Creating floppy disk...
    virtualbox-iso: Copying files flatly from floppy_files
    virtualbox-iso: Copying file: ./Scripts/enable_winrm.ps1
    virtualbox-iso: Done copying files from floppy_files
    virtualbox-iso: Collecting paths from floppy_dirs
    virtualbox-iso: Resulting paths from floppy_dirs : []
    virtualbox-iso: Done copying paths from floppy_dirs
==> virtualbox-iso: Creating virtual machine...
==> virtualbox-iso: Creating hard drive...
==> virtualbox-iso: Attaching floppy disk...
==> virtualbox-iso: Creating forwarded port mapping for communicator (SSH, WinRM, etc) (host port 3789)
==> virtualbox-iso: Executing custom VBoxManage commands...
    virtualbox-iso: Executing: modifyvm packer-virtualbox-iso-1565282739 --natpf1 winrm,tcp,,222585,,5985
    virtualbox-iso: Executing: modifyvm packer-virtualbox-iso-1565282739 --memory 4096
    virtualbox-iso: Executing: modifyvm packer-virtualbox-iso-1565282739 --cpus 2
==> virtualbox-iso: Starting the virtual machine...
    virtualbox-iso: The VM will be run headless, without a GUI. If you want to
    virtualbox-iso: view the screen of the VM, connect via VRDP without a password to
    virtualbox-iso: rdp://127.0.0.1:5908
==> virtualbox-iso: Waiting 10s for boot...
==> virtualbox-iso: Typing the boot command...
==> virtualbox-iso: Using winrm communicator to connect: 127.0.0.1
==> virtualbox-iso: Waiting for WinRM to become available...
==> virtualbox-iso: Timeout waiting for WinRM.
==> virtualbox-iso: Deregistering and deleting VM...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Timeout waiting for WinRM.

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Timeout waiting for WinRM.

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out! Normally, winrm connection issues are an issue with your autounattend file, not a Packer bug. I'd recommend starting from a known good windows template and work from there. Since this is a "getting started" question and not a bug, the [mailing list](https://groups.google.com/forum/#!forum/packer-tool) is the best place to go with questions. Let us know if you have any further problems.
