### ISSUE TITLE
Packer Crash - 08122019

### ISSUE THREAD

**Issue by gloverc** [hashicorp/packer#7976]
Packer Crash

Describe the problem and include the following information:

- Packer version 1.4.2
- Host platform RHEL7
- Debug log output from `PACKER_LOG=1 packer build 2016ahv.json`.
  with packerlog and crash.log

https://gist.github.com/gloverc/c4eebd6ca77224f61dea9175225e3f40

**Comment by SwampDragons** [comment]
I don't think I'll be able to reproduce this without the autounattend file and knowing which iso you were using.

**Comment by SwampDragons** [comment]
Closing because it's been a month and I've never heard back. We can reopen if we get more info.
