### ISSUE TITLE
Dynamic fetching of security groups while building AMIs not being allowed

### ISSUE THREAD

**Issue by Sabya1981** [hashicorp/packer#7978]
Describe the problem and include the following information:

- Packer version from `packer version` :     1.4.x

- Host platform :    Amazon Linux 2

- Debug log output from `PACKER_LOG=1 packer build template.json` : 

Errors validating build 'amazon-ebs'. 1 error(s) occurred:
 unknown configuration key: "security_group_filter"

- The _simplest example template and scripts_ needed to reproduce the bug
  
  Just add below snippet to any Packer script meant to be run in AWS Cloud
  security_group_filter": 
  {
	"filters": {
	  "tag:Name": "SampleTag"
	}
  }

**Comment by rickard-von-essen** [comment]
Please supply the information requested in the issue template:
- Packer version (`packer version`)
- Host platform (`uname -a` etc.)
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a [gist](https://gist.github.com).
- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your [gist](https://gist.github.com).
