### ISSUE TITLE
Setting variables inside a builder?

### ISSUE THREAD

**Issue by matthewbarr** [hashicorp/packer#798]
I'd like to be able to set a variable in a builder, which then gets used in a shared provisioner.

Basically, we need to build a dev, stage & prod AMI, with slightly different needs, but all from the same base, and all using the same tools.  I could just run packer 3 times w/ different flags, but... that's silly.

What I'd really like is iteration, but.. that's probably asking for too much for right now.

**Comment by kristianperkins** [comment]
+1 for this.  Being able to use the builder name in file provisioners as well as others would be handy and would cut down the amount of duplicate provisioners for me.  e.g. rather than specifying a file provisioner for each builder, being able to specify:

    "provisioners": {
        "type": "file",
        "source": "{{ `builder_name` }}.zip",
        "dest": "dest.zip"
    }
