### ISSUE TITLE
[Hetzner Cloud] Make Windows Server builds possible

### ISSUE THREAD

**Issue by Rick-McClatchie** [hashicorp/packer#7980]
It would be great if there was a way to build Windows Server images with packer in the Hetzner Cloud.
https://www.packer.io/intro/getting-started/build-image.html#a-windows-example

**Comment by KrustyHack** [comment]
Ay,

Would be great to have this feature ! I'm selling Windows VPS to my customers and actually I'm managing images manually. Using Packer to build my Windows images would be a good move ! Great idea !

**Comment by codello** [comment]
I'd be interested in this as well. As a more general approach it would be useful to be able to create images from an ISO image with a `boot_command`. This could be applied to other OSs that are not yet available as cloud images as well.

Looking through [the sources](https://github.com/hashicorp/packer/blob/master/builder/hcloud/config.hcl2spec.go) it seems to me that WinRM connections are already possible with the `hcloud` builder. So being able to create snapshots from ISOs may be a viable workaround to create a Windows Server build until Hetzner offers an official Windows image.

**Comment by marco-m** [comment]
Should this ticket be moved to https://github.com/hashicorp/packer-plugin-hcloud ?
@SwampDragons ?

**Comment by nywilken** [comment]
Thanks @marco-m. This issue does belong on the packer-plugin-hcloud repo and should be closed. I'll mark it as wontfix here and have it moved to the appropriate repo so that folks looking for this functionality can see that it is not supported. Thanks for providing the context on Hetzner Windows support.
