### ISSUE TITLE
ssh_host and ssh_port ignored when using QEMU builder

### ISSUE THREAD

**Issue by howels** [hashicorp/packer#7984]
- Packer version from `packer version` 1.4.2
- Host platform Ubuntu 18.04
- Debug log output from `PACKER_LOG=1 packer build template.json`.

Running the VM with the below config and it seems that the builder ignores the ssh_host/ssh_port and instead tries to setup a NAT which is failing. We are using TAP adapters instead of SLIRP and so ssh_host should be set to the IP we need to go to without using a forwarding rule, yet the forwarding rule is still created. We are doing a multi-VM build with static IPs which we can do via virtualbox yet under Qemu we are stuck with broken NAT rules and attempts to connect to localhost instead of to the IP in ssh_host:

`2019/08/13 13:13:32 packer-1.4.2: 2019/08/13 13:13:32 Special code '<enter>' found, replacing with: 0xFF0D
2019/08/13 13:13:32 packer-1.4.2: 2019/08/13 13:13:32 [INFO] Waiting 1s
==> fam: Using ssh communicator to connect: 127.0.0.1
2019/08/13 13:13:33 packer-1.4.2: 2019/08/13 13:13:33 [INFO] Waiting for SSH, up to timeout: 40m0s
==> fam: Waiting for SSH to become available...
2019/08/13 13:13:33 packer-1.4.2: 2019/08/13 13:13:33 [DEBUG] TCP connection to SSH ip/port failed: dial tcp 127.0.0.1:2474: connect: connection refused
2019/08/13 13:13:38 packer-1.4.2: 2019/08/13 13:13:38 [DEBUG] TCP connection to SSH ip/port failed: dial tcp 127.0.0.1:2474: connect: connection refused
2019/08/13 13:13:43 packer-1.4.2: 2019/08/13 13:13:43 [DEBUG] TCP connection to SSH ip/port failed: dial tcp 127.0.0.1:2474: connect: connection refused
2019/08/13 13:13:48 packer-1.4.2: 2019/08/13 13:13:48 [DEBUG] TCP connection to SSH ip/port failed: dial tcp 127.0.0.1:2474: connect: connection refused
2019/08/13 13:13:53 packer-1.4.2: 2019/08/13 13:13:53 [DEBUG] TCP connection to SSH ip/port failed: dial tcp 127.0.0.1:2474: connect: connection refused`

Here is the JSON used to run the build:

`{

  "builders":
  [

    {
      "name": "test",
      "type": "qemu",
      "accelerator": "kvm",
      "format": "qcow2",
      "headless": "False",

      "output_directory": "/opt/output",
      "vm_name": "test.qcow2",

      "iso_url": "/home/user/iso-files/CentOS-7-x86_64-DVD-1810.iso",
      "iso_checksum": "5b61d5b378502e9cba8ba26b6696c92a",
      "iso_checksum_type": "md5",
      "cpus": 2,
      "memory": 8192,

      "disk_size": 81920,
      "disk_additional_size": [
        "307200M",
        "51200M"
      ],

      "qemuargs": [
        [ "-netdev" ,"bridge,id=virbr1,br=virbr1" ],
        [ "-device", "virtio-net-pci,netdev=virbr1,id=virbr1" ]
      ],

      "http_directory": "http",
      "http_port_min": 10082,
      "http_port_max": 10089,

      "shutdown_command": "shutdown -P now",
      "ssh_username": "root",
      "ssh_password": "password",
    
      "ssh_port": 22,
      "ssh_wait_timeout": "2400s",
      "ssh_host": "192.168.0.10",

      "boot_wait": "10s",
      "boot_command": [
        "",
        "<up><wait><tab><wait> ",
                    "text ks=http://192.168.0.1:{{ .HTTPPort }}/ks.cfg ip=192.168.0.10::192.168.0.1:255.255.255.0:test.domain.local:eth0:none nameserver=192.168.0.1 ",
                    "<enter><wait>"
      ]
    }
  ]

}`

**Comment by howels** [comment]
FYI we can SSH to the IP 192.168.0.10 from the host whilst the build is running, but Packer is not connecting.

**Comment by SwampDragons** [comment]
Sorry for the late response! This issue should have been fixed by #7832 which went out in v1.4.3 -- if it's still an issue, please let me know and we can reopen :)
