### ISSUE TITLE
chef-solo license issue

### ISSUE THREAD

**Issue by srinivas-reddy-mula** [hashicorp/packer#7986]
- Packer version: 1.3.4
- The _simplest example template and scripts_ needed to reproduce the bug.
see below address for **_### chef_solo.json_**
  https://gist.github.com/srinivas-reddy-mula/

- Debug log output from `PACKER_LOG=1 packer build chef_solo.json
see below for output log of **_### packer-chef-solo.log_**
![packer_chef-solo](https://user-images.githubusercontent.com/35866130/62996925-252a4b00-be84-11e9-867a-66b2bf39be91.JPG)

              https://gist.github.com/srinivas-reddy-mula/

**Comment by rickard-von-essen** [comment]
This have been fixed in a later version, please upgrade.
