### ISSUE TITLE
Support "more conventional" formats in `isotime`

### ISSUE THREAD

**Issue by johanfleury** [hashicorp/packer#7987]
# Description

The `isotime` function is based on Go’s [Time.Format function](https://golang.org/pkg/time/#Time.Format). It takes a ”template date” (`Mon Jan 2 15:04:05 -0700 MST 2006`) as argument and use it to format the current date.

This is misleading for new comers as that’s pretty much the only place where that “template-date-as-format” is used.

# Suggested change

I know Packer is written in Go and has to deal with the defect of the language, but it would be great if it could suppport a more conventional format for `isotime`, such as the C standard (which is used by [Python](https://docs.python.org/3/library/datetime.html#strftime-strptime-behavior), [Ruby](https://apidock.com/ruby/DateTime/strftime), the UNIX date command, ...).

# Related issues

Here is a set of related issues I found that could’ve been avoided if the `isotime` format was more conventional:

* #1538
* #4862
* #6293
* #6278

**Comment by SwampDragons** [comment]
Totally agree, but I'm probably not going to get a chance to work on this in the near future. If someone wants to contribute code that would support a more conventional format, I'd happily review and merge :)

**Comment by rickard-von-essen** [comment]
There seems to be plenty available libraries for this:

https://godoc.org/?q=strftime

**Comment by rickard-von-essen** [comment]
Maybe https://godoc.org/github.com/jehiah/go-strftime

**Comment by johanfleury** [comment]
I think [`lestrrat-go/strftime`](https://godoc.org/github.com/lestrrat-go/strftime) would be better as it supports pretty much everything that's in the C standard unlike `jehiah/go-strftime`.

I came with that change:

```diff
diff --git a/template/interpolate/funcs.go b/template/interpolate/funcs.go                                                                                                                                         
index 1d76f8f06..aa3d25e29 100644
--- a/template/interpolate/funcs.go
+++ b/template/interpolate/funcs.go
@@ -14,6 +14,7 @@ import (
        "github.com/hashicorp/packer/common/uuid"
        "github.com/hashicorp/packer/version"
        vaultapi "github.com/hashicorp/vault/api"
+       "github.com/lestrrat-go/strftime"
        "github.com/rwtodd/Go.Sed/sed"
 )
 
@@ -32,6 +33,7 @@ var FuncGens = map[string]FuncGenerator{
        "build_type":     funcGenBuildType,
        "env":            funcGenEnv,
        "isotime":        funcGenIsotime,
+       "strftime":       funcGenStrftime,
        "pwd":            funcGenPwd,
        "split":          funcGenSplitter,
        "template_dir":   funcGenTemplateDir,
@@ -126,6 +128,12 @@ func funcGenIsotime(ctx *Context) interface{} {
        }
 }
 
+func funcGenStrftime(ctx *Context) interface{} {
+       return func(format string) (string, error) {
+               return strftime.Format(format, InitTime)
+       }
+}
+
 func funcGenPrimitive(value interface{}) FuncGenerator {
        return func(ctx *Context) interface{} {
                return value
```

If that's good for you, I can make a proper PR

**Comment by SwampDragons** [comment]
I think I prefer https://github.com/jehiah/go-strftime, primarily because the community using and supporting it is larger which means less work for me in the future should there be issues with maintaining the package.

**Comment by johanfleury** [comment]
I understand that, but the issue with `jehiah/go-strftime` is that it supports only a very small subset of the standard.

**Comment by SwampDragons** [comment]
It supports the portion of the standard used by the _vast_ majority of people, though, and provides a direct and clean mapping to the golang format reference. And the code is dead simple.

**Comment by eternal-engineer** [comment]
Can I pick this up? I've been looking to getting started with packer and this seems a good first issue to start with?

**Comment by azr** [comment]
Hey @eternal-engineer, of course ! 🙂

**Comment by psinghal20** [comment]
Hey @azr, I would like to take up this issue if no one is working on it. 
I skimmed through the codebase and think we can just add another function in the `FuncsGen` map to support [jehiah/go-strftime](https://github.com/jehiah/go-strftime), right?

**Comment by azr** [comment]
@psinghal20, nice, yes, that should do it 🙂 !

**Comment by johanfleury** [comment]
@psinghal20 Have a look at the diff I proposed in https://github.com/hashicorp/packer/issues/7987#issuecomment-521683992. It adds a template function called `strftime` that converts the current UTC time to the specified format.

If you all want to use `jehiah/go-strftime`, changing the import line should be enough to have it working, but please, keep in mind that unlike `lestrrat-go/strftime`, `jehiah/go-strftime` doesn't support all of the standard conversions you can find in other tools or language (C, Python, Ruby, or GNU `date` for instance).

---

For the sake of completeness, here is a complete diff I written when I first opened this issue:

```diff
diff --git a/template/interpolate/funcs.go b/template/interpolate/funcs.go
index 1d76f8f06..aa3d25e29 100644
--- a/template/interpolate/funcs.go
+++ b/template/interpolate/funcs.go
@@ -14,6 +14,7 @@ import (
 	"github.com/hashicorp/packer/common/uuid"
 	"github.com/hashicorp/packer/version"
 	vaultapi "github.com/hashicorp/vault/api"
+	"github.com/lestrrat-go/strftime"
 	"github.com/rwtodd/Go.Sed/sed"
 )
 
@@ -32,6 +33,7 @@ var FuncGens = map[string]FuncGenerator{
 	"build_type":     funcGenBuildType,
 	"env":            funcGenEnv,
 	"isotime":        funcGenIsotime,
+	"strftime":       funcGenStrftime,
 	"pwd":            funcGenPwd,
 	"split":          funcGenSplitter,
 	"template_dir":   funcGenTemplateDir,
@@ -126,6 +128,12 @@ func funcGenIsotime(ctx *Context) interface{} {
 	}
 }
 
+func funcGenStrftime(ctx *Context) interface{} {
+	return func(format string) (string, error) {
+		return strftime.Format(format, InitTime)
+	}
+}
+
 func funcGenPrimitive(value interface{}) FuncGenerator {
 	return func(ctx *Context) interface{} {
 		return value
diff --git a/template/interpolate/funcs_test.go b/template/interpolate/funcs_test.go
index b624a160f..ab7f83032 100644
--- a/template/interpolate/funcs_test.go
+++ b/template/interpolate/funcs_test.go
@@ -140,6 +140,26 @@ func TestFuncIsotime(t *testing.T) {
 	}
 }
 
+func TestFuncStrftime(t *testing.T) {
+	ctx := &Context{}
+	i := &I{Value: "{{strftime \"%FT%T%z\"}}"}
+	result, err := i.Render(ctx)
+	if err != nil {
+		t.Fatalf("err: %s", err)
+	}
+
+        val, err := time.Parse("2006-01-02T15:04:05-0700", result)
+	if err != nil {
+		t.Fatalf("err: %s", err)
+	}
+
+	currentTime := time.Now().UTC()
+	if currentTime.Sub(val) > 2*time.Second {
+		t.Fatalf("val: %v (current: %v)", val, currentTime)
+	}
+}
+
+
 func TestFuncPwd(t *testing.T) {
 	wd, err := os.Getwd()
 	if err != nil {
diff --git a/website/source/docs/templates/engine.html.md b/website/source/docs/templates/engine.html.md
index a16182547..9b7b1be28 100644
--- a/website/source/docs/templates/engine.html.md
+++ b/website/source/docs/templates/engine.html.md
@@ -42,6 +42,10 @@ Here is a full list of the available functions for reference.
     [formatted](https://golang.org/pkg/time/#example_Time_Format). See more
     examples below in [the `isotime` format
     reference](/docs/templates/engine.html#isotime-function-format-reference).
+-   `strftime FORMAT` - UTC time, formated using the ISO C standard format
+    `FORMAT`. See
+    [lestrrat-go/strftime](https://github.com/lestrrat-go/strftime) for a list
+    of available format specifier.
 -   `lower` - Lowercases the string.
 -   `pwd` - The working directory while executing Packer.
 -   `sed` - Use [a golang implementation of
```

**Comment by psinghal20** [comment]
@johanfleury Thanks for your help. It was pretty much a one-line change from your diff. :smile:
