### ISSUE TITLE
AZURE: Shared image gallery does not support replica numbers

### ISSUE THREAD

**Issue by sfc-gh-lrobles** [hashicorp/packer#7990]
[Per the azure documentation](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/shared-image-galleries), if i want to push an image to a shared image gallery, there is no way to declare a replica count per region. The azurerm builder does not support this option in the shared_image_gallery block

I can specify which regions i want the image pushed to, but not a count

Packer version v1.4.2

**Comment by Catfoodman** [comment]
This is a huge missing feature, at least for me.  I'd really like to be able to specify the number of replicas at the time of the image version creation.

**Comment by AlexOQ** [comment]
I'd also like to see the support for 'storage_account_type' parameter, in order to utilize AZ redundancy where supported.
