### ISSUE TITLE
Docker builder : I want to exec "/entrypoint.sh" throught /bin/bash. But just can see "/bin/sh -c entrypoint.sh".

### ISSUE THREAD

**Issue by 17billion** [hashicorp/packer#7999]
FOR FEATURES:
Docker version : 18.06.1-ce
packer --version : 1.3.1
Host platform : Ubuntu 16.04

FOR BUGS:
I using nomally docker builder and packer docker builder.
I think difference between nomally docker builder and packer docker builder.
Packer builder can exec just only /bin/sh.
I want to exec /entrypoint.sh throught /bin/bash. But just can /bin/sh -c entrypoint.sh.(packer docker builder)
How I can exec "/bin/bash /entrypoint.sh" using the packer docker builder?

Using nomally docker builder pic. (I want this result using packer docker builder like this pic)
![image](https://user-images.githubusercontent.com/28832461/63138408-5d14c800-c015-11e9-9f0d-f0befc10761d.png)

Using packer docker builder pic. (Just only can see /bin/sh)
![image](https://user-images.githubusercontent.com/28832461/63138443-7fa6e100-c015-11e9-9c6b-bc77727abd9c.png)
  
- Part in json file.
 "builders":[
      {
         "type":"docker",
         "image":"ubuntu:xenial",
         "commit":"true",
         "changes":[       
            "ENV DEBIAN_FRONTEND noninteractive",
            "ENTRYPOINT /entrypoint.sh"
         ]
      }
   ],

**Comment by SwampDragons** [comment]
Try 
`"changes": ["ENTRYPOINT [\"/bin/bash\", \"/var/www/start.sh\"]"]`

**Comment by 17billion** [comment]
@SwampDragons Thanks! It's correct.
