### ISSUE TITLE
Missing fileversion and certificate on packer.exe

### ISSUE THREAD

**Issue by Kmdkca** [hashicorp/packer#8000]
Packer version 1.4.3:
The Packer.exe (win x64) is not having a fileversion in the details tab
Also please sign it with valid authenticode certificate. Running unsigned executables is often prevented by security

**Comment by SwampDragons** [comment]
I haven't changed the deploy process recently -- has this been a problem with previous versions of Packer, too, or just the 1.4.3 release?

**Comment by Kmdkca** [comment]
Sorry for late reply.  All versions that i have worked with had that issue.

**Comment by SwampDragons** [comment]
We recently moved to a new release process which signs windows executables. 🎉 This is resolved as of the last couple of releases.
