### ISSUE TITLE
Data could not be sent to remote host \"127.0.0.1\". Make sure this host can be reached over ssh: ssh: connect to host 127.0.0.1 port 5985:

### ISSUE THREAD

**Issue by Aaronmcd1978** [hashicorp/packer#8005]
I am trying to create windows image from packer and provision a winrm connection to run an ansible playbook  but getting the above error

**Comment by rickard-von-essen** [comment]
Please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._

**Comment by rickard-von-essen** [comment]
Most likely you want to set `communicator: winrm` and read the docs for howto use the ansible provisioner with winrm.
