### ISSUE TITLE
Outscale provider requires omi_virtualization_type

### ISSUE THREAD

**Issue by Hakujou** [hashicorp/packer#8007]
Hello,

I currently have an issue with Packer and Outscale BSUSurrogate builder (https://packer.io/docs/builders/osc-bsusurrogate.html).

The documentation states that ```omi_virtualization_type``` is optional but it's not. Packer says ```* omi_virtualization_type is required.```.

Packer version: Packer v1.4.3
Host platform: MacOS 10.14.5 x64
Packer template: https://gist.github.com/Hakujou/3ea3022be379e8aada69dee1a57cf300
Packer logs: 
[debug.txt](https://github.com/hashicorp/packer/files/3516214/debug.txt)

Thanks

**Comment by SwampDragons** [comment]
@marinsalinas did the Outscale team ever decide who they wanted to add to the CODEOWNERS file?

**Comment by marinsalinas** [comment]
yes, @SwampDragons :)

**Comment by SwampDragons** [comment]
Who?
