### ISSUE TITLE
OVF transfer failed from remote host to local machine

### ISSUE THREAD

**Issue by jiatongw** [hashicorp/packer#8010]
Hi, I am trying to use `packer` to build images in a remote `esxi` host. The build process succeeded but error happened while transferring `ovf` back.

```
==> centos-7: Exporting virtual machine...
    centos-7: Executing: ovftool --noSSLVerify=true --skipManifestCheck -tt=ovf vi://username:****@hostname/centos-7 ./output/centos-7
==> centos-7: Error exporting virtual machine: exit status 1
==> centos-7: Opening VI source: vi://username@hostname:443/centos-7
==> centos-7: Opening OVF target: ./output/centos-7
==> centos-7: Writing OVF package: ./output/centos-7/centos-7/centos-7.ovf
Transfer Failed                       
==> centos-7: Error: Failed to open file stream: https://hostname:443/ha-nfc/524c1678-4260-5e2e-ce08-de46e3abcdb0/centos-7.nvram
==> centos-7: Deleting directory tree below: ./output/centos-7/centos-7
==> centos-7: Completed with errors
==> centos-7: 
==> centos-7:
==> centos-7: Destroying virtual machine...
```
packer version: v1.4.3
I am sure that I opened 433 port in the esxi host. Anyone has some insights on this? Thanks (I don't know whether it is a bug or not)

**Comment by SwampDragons** [comment]
`https://hostname:443` -- "hostname" doesn't seem right. Are you supplying the proper name?

**Comment by jiatongw** [comment]
Hi @SwampDragons . Yes, it is the IP address of the remote host. I am hiding the IP here

**Comment by SwampDragons** [comment]
Thanks for clarifying. In order to work on this, I'm going to need the simplest possible template that reproduces the issue, and logs from PACKER_LOG=1, as requested in the issue template.

**Comment by jiatongw** [comment]
@SwampDragons Hi, please use this for reproduce: https://github.com/jiatongw/image-builder/tree/reproduce/images/capi . You could see my commit based on it's master branch:  https://github.com/jiatongw/image-builder/commit/354b7327dcdc9b935f5334b06ddb92438ff8917d

You will need a `esxi` host to reproduce. Please make sure to do the following changes in gist:
https://gist.github.com/jiatongw/d166052b2c6f07901c24ea24ac5a636f

Then under directory `capi`, do `make build-centos-7`.

Thanks

**Comment by jiatongw** [comment]
The logs contains a lot of credentials so I didn't past here. But you can do the above and the log will print to the terminal.

**Comment by jiatongw** [comment]
Hi @SwampDragons .We could close the issue. I found the problem, it is a bug of `ovftool`. In some images I had a `+` in the VM name. It should escape the URL before making the request, so it requests `foo%2Bbar` instead of `foo+bar`

I simply changed the `+` with `-` and all jobs succeeded
