### ISSUE TITLE
Filling ami_description from a file

### ISSUE THREAD

**Issue by alexandernst** [hashicorp/packer#8014]
I use Packer in order to build my AMIs. Keeping an accurate description/changelog for each AMI is very important to me, but keeping those texts inside the templates is starting to get cumbersome as the texts keep getting bigger and bigger.

Is there a way I can set the value of `ami_description` in my Packer template directly from a file in the same directory?

**Comment by rickard-von-essen** [comment]
You can use a [user variable and define it in a separate file](https://packer.io/docs/templates/user-variables.html#from-a-file).

If json is to cumbersome to escape you can write it in yaml and translate it on the fly.

**Comment by alexandernst** [comment]
Oh, I absolutely didn't think about that. That should work exactly as I want, thank you very much!
