### ISSUE TITLE
~/.packer.d/tmp/upload853132141: no such file or directory

### ISSUE THREAD

**Issue by nuoyan** [hashicorp/packer#8015]
We use Packer on Jenkins to build docker images. We recently updated from Packer 1.3.3 to Packer 1.4.3. Ever since, we've been seeing this transient error more often. If we re-run the build in most cases it passes.

Multiple jobs could be using packer at the same time.  The server is running ubuntu 14.04.

We checked permission of the packer executable and it was set to the same as before. It happened really rarely before.

Is this a known problem or is there something we need to configure?

**Comment by SwampDragons** [comment]
Thanks for opening an issue -- to help you, we really do need the things requested in the issue template: 

- Full debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a gist https://gist.github.com
- The _simplest complete example template and scripts_ needed to reproduce the bug.
  Include these in your gist https://gist.github.com

**Comment by nuoyan** [comment]
Thanks for your reply.

Here is the full debug log output:
https://gist.github.com/nuoyan/0c42219241a4eb6e560e01885e08e1bd

Sample template:
https://gist.github.com/nuoyan/d30bea681e2d17cd05c11a282b852a42

**Comment by SwampDragons** [comment]
I think the build over at https://circleci.com/gh/hashicorp/packer/15648#artifacts/containers/0 will fix this; can you try it out and let me know if it closes this issue?
