### ISSUE TITLE
tell packer to skip build if image already exists

### ISSUE THREAD

**Issue by zaro0508** [hashicorp/packer#8029]
We are using packer with the amazon-ebs builder.  The packer build command throws an error when attempting to build an AMI with a name that matches an existing AMI on AWS.  I would like to make packer provide the same info but NOT fail for this use case, instead I would like it to just ignore and continue to build the next image.  It would be great if there is a packer build flag for this, something like a '-skip-if-existing' flag.

google group discussion: https://groups.google.com/d/msg/packer-tool/8bG5YeL9N5w/DwxbgIB8BAAJ

➜ packer --version
1.4.3
➜  packer build -var-file=../vars.json template.json
amazon-ebs output will be in this color.

==> amazon-ebs: Prevalidating AMI Name: weechat-v1.0.0
==> amazon-ebs: Error: AMI Name: 'weechat-v1.0.0' is used by an existing AMI: ami-0ee682a1a7e3717d0
Build 'amazon-ebs' errored: Error: AMI Name: 'weechat-v1.0.0' is used by an existing AMI: ami-0ee682a1a7e3717d0

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Error: AMI Name: 'weechat-v1.0.0' is used by an existing AMI: ami-0ee682a1a7e3717d0

==> Builds finished but no artifacts were created.
➜   echo $?
1

**Comment by SwampDragons** [comment]
Closing because we decided not to merge the associated PR.  See the PR for the conversation and rationale.
