### ISSUE TITLE
Issue with goss provisioner

### ISSUE THREAD

**Issue by P15223971** [hashicorp/packer#8030]
Hi,

I appreciate that this issue appears to be caused by an external provisioner, but if any help or suggestions could be offered to resolve this problem it would be incredibly useful. 

Packer version: 1.4.3

Provisioner: packer-provisioner-goss v0.3.0

When calling `go get` on the goss provisioner ([github.com/YaleUniversity/packer-provisioner-goss](github.com/YaleUniversity/packer-provisioner-goss)), I get the following error:

```# github.com/YaleUniversity/packer-provisioner-goss
src/github.com/YaleUniversity/packer-provisioner-goss/packer-provisioner-goss.go:75:32: cannot use new(Provisioner) (type *Provisioner) as type packer.Provisioner in argument to server.RegisterProvisioner:
	*Provisioner does not implement packer.Provisioner (wrong type for Provision method)
		have Provision(packer.Ui, packer.Communicator) error
		want Provision(context.Context, packer.Ui, packer.Communicator) error
src/github.com/YaleUniversity/packer-provisioner-goss/packer-provisioner-goss.go:240:15: cmd.StartWithUi undefined (type *packer.RemoteCmd has no field or method StartWithUi)
src/github.com/YaleUniversity/packer-provisioner-goss/packer-provisioner-goss.go:246:15: cmd.StartWithUi undefined (type *packer.RemoteCmd has no field or method StartWithUi)
src/github.com/YaleUniversity/packer-provisioner-goss/packer-provisioner-goss.go:261:15: cmd.StartWithUi undefined (type *packer.RemoteCmd has no field or method StartWithUi)
src/github.com/YaleUniversity/packer-provisioner-goss/packer-provisioner-goss.go:264:20: invalid operation: cmd.ExitStatus != 0 (mismatched types func() int and int)
src/github.com/YaleUniversity/packer-provisioner-goss/packer-provisioner-goss.go:342:15: cmd.StartWithUi undefined (type *packer.RemoteCmd has no field or method StartWithUi)
src/github.com/YaleUniversity/packer-provisioner-goss/packer-provisioner-goss.go:345:20: invalid operation: cmd.ExitStatus != 0 (mismatched types func() int and int)

Error: ResponseItem.ErrorDetail[code=2,message=The command '/bin/sh -c go get github.com/YaleUniversity/packer-provisioner-goss' returned a non-zero code: 2]
Failed to deploy '<unknown> Dockerfile: Dockerfile': The command '/bin/sh -c go get github.com/YaleUniversity/packer-provisioner-goss' returned a non-zero code: 2
```

The script that is running this has not been changed for 6 months, and the last time it ran (~ Feb 2019) everything worked as expected - the goss provisioner was last updated on July 2018 so I was wondering if anything had changed in the packer code since then which could have made the provisioner incompatible.

 From the error above, I'm not sure if this part:
```
have Provision(packer.Ui, packer.Communicator) error
want Provision(context.Context, packer.Ui, packer.Communicator) error
``` 
is the root cause or not, as I am fairly new to packer/provisioners.

I have tried running it in a dockerfile and locally on my own machine and I encounter the same error.

Any advice would be greatly appreciated.

Thanks

**Comment by SwampDragons** [comment]
We updated the plugin API a few versions ago, and your plugin hasn't been
updated since, so the third party plugin isn't playing nicely with the
core. Try downgrading to v1.3.5.  If that still doesn't work, it looks like
the goos provisioner hasn't been updated since about a year ago -- the
current version at that time was v1.2.4.

Older versions of Packer can be found at
https://releases.hashicorp.com/packer/

**Comment by P15223971** [comment]
Thanks - I've updated the plugin so it should work with the newer packer versions, but if that still causes problems I'll downgrade my packer version as suggested.
