### ISSUE TITLE
Add run_volume_tags from builder: amazon-ebs to builder: amazon-ebsvolume

### ISSUE THREAD

**Issue by RichardBronosky** [hashicorp/packer#8037]
The `run_volume_tags` is a tremendous help when cleaning up after Packer builder type `amazon-ebs` https://www.packer.io/docs/builders/amazon-ebs.html#run_volume_tags

It's much more difficult to clean up after Packer builder type `amazon-ebsvolume` because it only has `run_tags` and not `run_volume_tags`
https://www.packer.io/docs/builders/amazon-ebsvolume.html#run_tags

**Comment by DanHam** [comment]
@RichardBronosky Would you be able to test the submitted PR to see if it fits with your needs?

**Comment by RichardBronosky** [comment]
I'll check it out this weekend

**Comment by azr** [comment]
Hello @RichardBronosky did you have the time to try the PR ?

**Comment by RichardBronosky** [comment]
@DanHam I finally got back onto this project and tested the change in master. While it works as described, I think the tag is being removed too soon. If the build fails or is terminated, you are still left with an unlabeled EBS in your account that no one with ever feel comfortable deleting.

```
informatica-EBS output will be in this color.

    informatica-EBS: Found Image ID: ami-0671fa468c6c854bc
    informatica-EBS: Found VPC ID: vpc-07006bb4e85fa46d0
    informatica-EBS: Found Subnet ID: subnet-035a3188e72eb0c77
==> informatica-EBS: Using existing SSH private key
==> informatica-EBS: Creating temporary security group for this instance: packer_5da0c1f4-48e7-b14a-3f79-eb0603599fde
==> informatica-EBS: Authorizing access to port 22 from [0.0.0.0/0] in the temporary security groups...
==> informatica-EBS: Launching a source AWS instance...
==> informatica-EBS: Adding tags to source instance
    informatica-EBS: Adding tag: "purpose": "packer"
    informatica-EBS: Adding tag: "Name": "Packer Builder"
    informatica-EBS: Adding tag: "purpose": "packer"
    informatica-EBS: Instance ID: i-052c614d958f901f7
==> informatica-EBS: Waiting for instance (i-052c614d958f901f7) to become ready...
==> informatica-EBS: Removing any tags applied to EBS volumes when the source instance was created...
    informatica-EBS: Compiling list of existing tags to remove...
    informatica-EBS: Adding tag: "purpose": "packer"
    informatica-EBS: Deleting 'run_volume_tags' on EBS Volumes: vol-02990bf4ff72a77f0
==> informatica-EBS: Tagging EBS volumes...
    informatica-EBS: Compiling list of tags to apply to volume on /dev/xvdh...
    informatica-EBS: Adding tag: "Name": "infadev-0"
    informatica-EBS: Adding tag: "ebs-volume-0": "infadev-0-0"
    informatica-EBS: Applying tags to EBS Volume: vol-02990bf4ff72a77f0
==> informatica-EBS: Using ssh communicator to connect: 10.10.20.177
==> informatica-EBS: Waiting for SSH to become available...
Cancelling build after receiving interrupt
==> informatica-EBS: Terminating the source AWS instance...
==> informatica-EBS: Deleting temporary security group...
==> informatica-EBS: Created Volumes: EBS Volumes were created:
==> informatica-EBS:
==> informatica-EBS: us-east-1:vol-02990bf4ff72a77f0
==> informatica-EBS: Running post-processor: manifest
Build 'informatica-EBS' finished.
Cleanly cancelled builds after being interrupted.
```
While running:
<img width="623" alt="Screen Shot 2019-10-11 at 1 56 05 PM" src="https://user-images.githubusercontent.com/13620/66674104-24b5f280-ec30-11e9-9b75-eb1103604ec2.png">

After cancelation:
<img width="623" alt="Screen Shot 2019-10-11 at 1 56 56 PM" src="https://user-images.githubusercontent.com/13620/66674155-38615900-ec30-11e9-8a62-9fd94ce2de26.png">

Was this your intention? Should I open a new ticket?

**Comment by DanHam** [comment]
It's a little tricky to definitively say without seeing your template, but from what I can tell you have not set a `Name` tag in the `run_volume_tags` section of your template. This is why you end up with your source instances volume (vol-0851381...) having nothing under the Name column. Note that your `purpose` = `packer` tag is correctly applied on that volume and has not been removed.

I think you have something like the following:

```json
  "builders": [
    {
      "type": "amazon-ebsvolume",
      
      "run_tags": {
        "Name": "Packer builder",
        "purpose": "packer"
      },
      "run_volume_tags": {
        "purpose": "packer"
      },
      
      "ebs_volumes" : [
        {
          "volume_size": 80,
          
          "tags": {
            "Name": "infadev-0",
            "ebs-volume-0": "infadev-0-0"
          }
        }
      ]
```

I think you really want something like the following (note the additional `Name` tag in the `run_volume_tags` section):

```json
  "builders": [
    {
      "type": "amazon-ebsvolume",
      
      "run_tags": {
        "Name": "Packer builder",
        "purpose": "packer"
      },
      "run_volume_tags": {
        "Name": "Packer builder source instance volume",
        "purpose": "packer"
      },
      
      "ebs_volumes" : [
        {
          "volume_size": 80,
          
          "tags": {
            "Name": "infadev-0",
            "ebs-volume-0": "infadev-0-0"
          }
        }
      ]
```

To clarify, the changes made in #8051 do not remove any `run_volume_tags` applied to the source instances volumes - note you have the `purpose` = `packer` tag applied on your source instance volume (vol-0851381...) but the tag has been removed on your `ebs_volume` (vol-02990bf4...). 

Put another way, the changes made in #8051 only ever remove `run_volume_tags` from volumes specified in the `ebs_volumes` section of your template.

Hope that helps.

**Comment by SwampDragons** [comment]
Does this need to be reopened?

**Comment by DanHam** [comment]
No, I don't think so. I think there may have been some initial confusion here as to what volumes #8051 removes and applies tags to.  

As far as I can see from the output in the comments above, the only thing @RichardBronosky needs to do to get the behaviour he wants is to add a `Name` tag to the `run_volume_tags` section of his template.

Hopefully, my assessment of what's going on is correct. From my testing #8051 worked as intended. That said, there may be a wider issue here in that Packer is not cleaning up run instances and attached EBS volumes on cancellation - but that would be a different issue...
