### ISSUE TITLE
Auto generated WinRM special characters cause issues with Inspec

### ISSUE THREAD

**Issue by GavBurke** [hashicorp/packer#8042]
- Packer version from `packer version`
1.0.4

- Host platform
Ubuntu and COS

- The _simplest example template and scripts_ needed to reproduce the bug.
There isn't any repeatable way, just keep trying until the "random" password from Packer gives you a `-` at the start of the password, i.e. this one broke our build
```
inspec exec test-profile --backend winrm --host 10.21.128.67 --port 5986 --user dh-packer-build --password '-r=XQxq%&#%NNs4' --ssl --insecure --self-signed --no-distinct-exit --target-id packer-mswin-f5bfb2d3a0 --show-progress
```

You get the error back `Please provide a value for --password. For example: --password=hello.`

**Comment by azr** [comment]
Hello, thanks for reaching out; do you know if this still happens with the [latest version of packer](https://www.packer.io/downloads.html) ? ( Currently 1.4.3 )
I'm asking because 1.0.4 was tagged on 11 Aug 2017, and there is a chance that your issue has been fixed since.

**Comment by GavBurke** [comment]
I am not sure, I'll see if I can quickly check that out
