### ISSUE TITLE
Proxmox Builder is missing from the list of Builders on packer.io

### ISSUE THREAD

**Issue by chriswayg** [hashicorp/packer#8044]
For weeks I did not notice the **Proxmox Builder**, as it is not listed in the sidebar. Even when searching for it, it cannot be found on some search engines.

https://www.packer.io/docs/builders/index.html

![Packer Builders](https://user-images.githubusercontent.com/13681327/63794366-6adf1d00-c934-11e9-8477-83ee94c1796b.png)

Please put a link to Proxmox Builder in the sidebar.

https://www.packer.io/docs/builders/proxmox.html

**Comment by chriswayg** [comment]
Search results without a link to the Proxmox Builder page.
![Packer Proxmox Builder Search](https://user-images.githubusercontent.com/13681327/63794703-1b4d2100-c935-11e9-9209-2835d57c7eb9.png)

**Comment by azr** [comment]
Hello, thanks for reporting; I added the missing link to go there.

In the meantime you can find these docs here:  https://www.packer.io/docs/builders/proxmox.html

**Comment by chriswayg** [comment]
@azr its been about 4 weeks and the link is still not visible in the list of Builders. When will this get updated?

**Comment by SwampDragons** [comment]
We haven't released since which means the website hasn't been updated. I can cherry-pick the commit for now.
