### ISSUE TITLE
Build 'amazon-ebs' errored: Error retrieving auto-generated instance password: RequestLimitExceeded: Request limit exceeded.

### ISSUE THREAD

**Issue by t5unamie** [hashicorp/packer#8048]
Seem to be thjrowtteled by AWS api calls.

 packer --version
1.4.3

Old issues linked bellow. 

https://github.com/hashicorp/packer/issues/6330
https://github.com/hashicorp/packer/issues/6530

Seems to be the same issue

Error seen is from 

`PACKER_LOG=1 packer build windows2016.json`

https://gist.github.com/t5unamie/4ee90d28aec7bb730071708aa51070cd

Packer json (windows2016.json)

`{
  "min_packer_version": "0.12.0",
  "variables": {
    "profile": "XXXXXXXXXXXXXXXXXX",
    "region": "eu-west-1"
  },

  "builders": [{
    "type": "amazon-ebs",
    "profile": "{{user `profile`}}",
    "region": "{{user `region`}}",
    "source_ami_filter": {
      "filters": {
        "virtualization-type": "hvm",
        "name": "Windows_Server-2016-English-Full-Base-*",
        "root-device-type": "ebs"
      },
      "owners": ["amazon"],
      "most_recent": true
    },
    "instance_type": "r4.large",
    "ami_name": "windows2016Server-{{timestamp}}",
    "vpc_id": "XXXXXXXXXXXXXXX",
    "subnet_id": "XXXXXXXXXXXXXXX",
    "user_data_file":"scripts/SetUpWin2016.ps1",
    "communicator": "winrm",
    "winrm_username": "Administrator",
    "winrm_insecure": true,
    "winrm_use_ssl": true,
    "run_tags": {
      "Owner": "planit"
    },
    "tags": {
        "Name": "WindowsServer2012R2 Gold",
        "OS": "Windows Server 2016R2"
    },  
    "launch_block_device_mappings": [{
      "device_name": "/dev/sda1",
      "volume_size": 30,
      "volume_type": "gp2",
      "delete_on_termination": true
    }]
    
  }],
    
  "provisioners": [
  {
    "type": "file",
    "source": "files/SQLServer2017-x64-ENU-Dev.iso",
    "destination": "C:/SQLServer2017-x64-ENU-Dev.iso"
  },
    {
    "type": "powershell",
    "scripts": [
        "scripts/disableuac.ps1",
        "scripts/sql2017Install.ps1"
    ]
  },
  {
    "type": "windows-restart",
    "restart_check_command": "powershell -command \"& {Write-Output 'restarted.'}\""
  },
  {
    "type": "powershell",
    "inline": [
      "C:\\ProgramData\\Amazon\\EC2-Windows\\Launch\\Scripts\\InitializeInstance.ps1 -Schedule",
      "C:\\ProgramData\\Amazon\\EC2-Windows\\Launch\\Scripts\\SysprepInstance.ps1 -NoShutdown"
    ]
  }
]
}
`

Tried

export AWS_MAX_ATTEMPTS=10
export AWS_POLL_DELAY_SECONDS=30

Does'nt seem to work

**Comment by SwampDragons** [comment]
Yeah, looks like we need to wrap this in a retry. Thanks for opening.
