### ISSUE TITLE
Enhancement: floppy_command section similar to boot_command

### ISSUE THREAD

**Issue by mcandre** [hashicorp/packer#8057]
Some classic operating systems such as OS/2 Warp require floppy disks to be inserted prior to loading ISO's. And so it would be helpful for Packer to provide a `floppy_command` section, similar to `boot_command`, where users can insert and remove virtual floppy diskettes with custom delays between data loads. The user configuration would look like:

```json
floppy_command: [
    "<insert image=floppy-1.img drive=a>",
    "<wait30s>",
    "<enter>",
    "<wait5s>",
    "<remove drive=a>",
    "<wait5s>",
    "<insert image=floppy-2.img drive=a>"
    "<enter>",
    "<wait1m>",
    "<remove drive=a>",
    "<wait5s>"
],
iso_url: "winworldpc.com/os2/...",
boot_command: [
    "..."
]
```

As a workaround, I found a minor abuse of the `guestproperty wait` subcommand for the VirtualBox hypervisor, e.g. `guestproperty wait <uuid> goodnight-moon --timeout <milliseconds>`, followed by `controlvm 'os/2' keyboardputscancode`... for the Enter scancodes. Followed by `controlvm <uuid> savestate` to free the VM lock for the rest of the Packer build.

This happens to not depend on VirtualBox guest drivers, and `guestproperty wait` even exits with a zero code for now. But this could easily break in the future, and digging around with hypervisor details kind of defeats the purpose of using Packer in the first place.

**Comment by sylviamoss** [comment]
Hello! We'd review a PR for this but won't prioritize working on it ourselves. 
Thanks for opening the issue!
