### ISSUE TITLE
Help - Timeout Waiting SSH virtualbox-ovf

### ISSUE THREAD

**Issue by andremadureira1993** [hashicorp/packer#8058]
Hi.

  I'm facing the following issue when I try to use packer to build an VM image.
  Looks like packer can't connect in my VM and make the login, so it stay stuck forever.

The file that I'm using is an OVA file from an existing VM.
During the process, virtualbox get the VM up and running but when comes to login page it stuck forever:

JSON file:

{
	"builders": [
		{
		  "type": "virtualbox-ovf",
		  "source_path": "C:\\Users\\Administrator\\Desktop\\Packer\\cloudconnect-2.0.ova",
		  "ssh_username": "user",
		  "ssh_password": "password",
		  "communicator": "ssh",
      "ssh_pty": true,
		  "ssh_port": 22,
		  "shutdown_command": "echo 'packer' | sudo -S shutdown -P now"
		}
	]
}

Attaching the log in the image.

As you can see, the VM is avaiable and waiting for the login, but even I got ssh timeout
![Screenshot from 2019-09-02 14-38-45](https://user-images.githubusercontent.com/40531202/64128903-603ae280-cd8f-11e9-8d64-982a901453ea.png)

**Comment by rickard-von-essen** [comment]
Please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._
