### ISSUE TITLE
Post processor `vsphere` is unnecessary strict on which builders it accepts artifacts from

### ISSUE THREAD

**Issue by mjrider** [hashicorp/packer#8060]
Version: `Packer v1.4.3`

Bit of a bug/feature mashup:

Post processor `vsphere` as a hardcoded dependency on artifacts generated by the vmware builders. While the only thing used is the first ovf/ova/vmx file found in the files array
  
https://github.com/hashicorp/packer/blob/613d8ef6ab6f8182039e2d430497f5f6457d6a42/post-processor/vsphere/post-processor.go#L119

https://github.com/hashicorp/packer/blob/613d8ef6ab6f8182039e2d430497f5f6457d6a42/post-processor/vsphere/post-processor.go#L22-L25

Usecase:
I'm want to build a vsphere ovf image and upload this the vsphere, but without vmware workstation or remote esxi build.

workflow:
- build image with qemu
- use qemu-img and ovftool to convert the qemu image to a .ovf 
- upload to vsphere with vsphere post processor

This fails on the last step, the vsphere upload, because the artifacts are not accepted.

Potential sources of ovf's different then now whitelisted
- some self build generator
- virtualbox

Suggested solutions:
- remove the check altogether,
- add `artifice` as a allowed artifact source

a testbuild of packer without the check on builder id's works like expected for my usecase

A stripped version of my configuration, it is incomplete
https://gist.github.com/mjrider/d390e470a60de7f4afdae6851aca165e

**Comment by azr** [comment]
Hello @mjrider, thanks, I think this is a great idea and I think removing that check would totally work.
