### ISSUE TITLE
Packer and OpenStack

### ISSUE THREAD

**Issue by DrKAnakin** [hashicorp/packer#8062]
Hello Everyone,

From last week, I have a problem with my Packer intergreted in CI/CD chain.

My VM is created and the Image also but It's not possible to deploy instance based on this image and there are not link between this image generated by packer and snapshot or volume ID.

After some debugging step, I remarked than Packer delete snapshot.

Someone can help me?

Thanks a lot

**Comment by azr** [comment]
Please only use GitHub Issues for reporting bugs and feature requests. Do not ask for general help here. Please use IRC `#packer-tool` on Freenode or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer.
