### ISSUE TITLE
amazon-ebs terminates ec2 instance

### ISSUE THREAD

**Issue by markedcahinde** [hashicorp/packer#8063]
I've been trying to use aws codebuild to build my ami. I tried to build the template file in my local with Packer v1.4.3 and it succeeds. however, when trying to build with codebuild, i happen to encounter this error

`·[1;31m==> amazon-ebs: Error waiting for instance (i-0de74366ae3718667) to become ready: ResourceNotReady: failed waiting for successful resource state·[0m `

For full gist: https://gist.github.com/markedcahinde/e5ce446c55af07ea062b070f17bb4558
Packer version: v1.4.3
Platform: AWS Codebuild | aws/codebuild/standard:1.0 | ubuntu 18.04 (details: https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html)

**Comment by markedcahinde** [comment]
Please note that I have tried running with the ff. command
`AWS_POLL_DELAY_SECONDS=5 AWS_TIMEOUT_SECONDS=500 PACKER_LOG=1 ./packer build 20190904-issuing-AWSLinux-HVM.Masterless.json`

**Comment by SwampDragons** [comment]
I often see this bug when people are using temporary credentials that are expiring partway through the copy.

**Comment by markedcahinde** [comment]
Hi @SwampDragons ,
Did they mentioned what's their workaround for this?

**Comment by markedcahinde** [comment]
Hi @SwampDragons,
I tried checking the aws credentials during the process and it seems that it'll expire within an hour

`[Container] 2019/09/04 02:36:12 Running command ./jq '.' aws_credentials.json 
{ 
  "RoleArn": "ARN", 
  "AccessKeyId": "id", 
  "SecretAccessKey": "secret", 
  "Token": "token", 
  "Expiration": "2019-09-04T03:36:01Z" 
} `

And as I've noticed, the packer terminates the instance a few minutes after provisioning.

**Comment by markedcahinde** [comment]
Hi @SwampDragons ,
It turns out, this issue does not concern Packer but with AWS permissions. See, my codebuild project's service role do not have access to use/grant access to the KMS we use to encrypt the EBS volumes.
Adding my service role to the KMS key's policy resolved the issue and now I'm able to build successfully. 

I'm closing this ticket now. Thank again for the quick response.
