### ISSUE TITLE
packer-provisioner-ansible did not meet host_list/script requirements

### ISSUE THREAD

**Issue by chriswayg** [hashicorp/packer#8065]
Are the plugins working correctly, in spite of the Ansible message? Does this cause any limitations on Ansible use or does it skip particular plugins as a result?

```
 proxmox: Using /root/packer-projects/packer-proxmox-templates/debian-10.0-x86_64-proxmox/playbook/ansible.cfg as config file

    proxmox: /tmp/packer-provisioner-ansible077598026 did not meet host_list requirements, check plugin documentation if this is unexpected
    proxmox: /tmp/packer-provisioner-ansible077598026 did not meet script requirements, check plugin documentation if this is unexpected
```

see also here: 
[Inventory does not meet host_list/script requirements (Ansible 2.7.1)  #48859](https://github.com/ansible/ansible/issues/48859)
marked as a bug of Ansible 2.7

      Debian GNU/Linux 10 (buster) 10.0
      Proxmox pve-manager/6.0-5/f8a710d7 (running kernel: 5.0.18-1-pve)
      Packer v1.4.3
      ansible 2.7.10

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out and sorry for the late response. I'm not really sure what limitations this causes, and as both the ansible provisioner and the proxmox builder are generally community-supported, I'm not sure when I'll have a chance to look into this. It looks to me like this message is being raised directly from Ansible... did it cause your Packer build to fail?

**Comment by SwampDragons** [comment]
Closing since I never got a response. If this is limiting your ability to perform Packer builds, please comment and I'll reopen, or open a new ticket with more details on how this is harming the build.
