### ISSUE TITLE
Packer  version 1.4.2 & 1.4.3 crashes during Image  creation for Azure

### ISSUE THREAD

**Issue by shannawaz** [hashicorp/packer#8074]
Packer   version 1.4.2 & 1.4.3 crashes during image creation. I am able to create the image with packer version 1.4.0 & 1.4.1. See attached logs

[crash.log](https://github.com/hashicorp/packer/files/3577328/crash.log)

**Comment by SwampDragons** [comment]
Try version 1.4.4; I think this bug was fixed in that version.

**Comment by SwampDragons** [comment]
Thanks for opening an issue -- to help you, we really do need the things requested in the issue template: 

- The _simplest complete example template and scripts_ needed to reproduce the bug.
  Include these in your gist https://gist.github.com

**Comment by shannawaz** [comment]
This can be closed for now. I  tested again with 1.4.3 version , one major change is using existing resource group instead of creating a new one.
