### ISSUE TITLE
Issue with fix #7957 : ssh communicator fails on the source box

### ISSUE THREAD

**Issue by nicolasnoel** [hashicorp/packer#8082]
There might be an issue with fix  #7957 : ssh communicator fails on the source box because Vagrant needs to know which box to connect  :

`vagrant ssh` 
returns :
`This command requires a specific VM name to target in a multi-VM environment.`

The command to connect with ssh should be :
`vagrant ssh source`

_Originally posted by @nicolasnoel in https://github.com/hashicorp/packer/pull/7957#issuecomment-528809016_

**Comment by SwampDragons** [comment]
Can you please share the simplest possible template and steps to reproduce?

**Comment by nicolasnoel** [comment]
It should be solved by #8092

**Comment by SwampDragons** [comment]
Okay great! That's merged, so we can close this and you'll see the fix in v1.4.4
