### ISSUE TITLE
hyperv-vmcx add/mount disk/vhd

### ISSUE THREAD

**Issue by Kmdkca** [hashicorp/packer#8089]
Packer version 1.4.3

My golden images are created with only one drive (c:) but some of my templates needs multiple drives. Is it possible to create a second vhd and mount that during hyperv-vmcx builder?

thanks

**Comment by Kmdkca** [comment]
If not possible could this be changed to a feature request then?

**Comment by SwampDragons** [comment]
We have https://www.packer.io/docs/builders/hyperv-vmcx.html#secondary_iso_images which allows you to mound extra images that already exist.

If you want to create and mount new images, no, we have that option in the hyperv-iso builder (AdditionalDiskSize) but it looks like it was never added to the vmcx builder. Let me see if I can do that real fast.

**Comment by SwampDragons** [comment]
@Kmdkca You can find a build that contains this patch here: https://circleci.com/gh/hashicorp/packer/17704#artifacts/containers/0

The feature you want to use is `disk_additional_size`: https://www.packer.io/docs/builders/hyperv-iso.html#disk_additional_size.

**Comment by Kmdkca** [comment]
Thanks for fast fix. It works perfectly
