### ISSUE TITLE
Attach additionnal block volumes to VM in Openstack

### ISSUE THREAD

**Issue by gvcgael** [hashicorp/packer#8098]
Hello,

Currently, the openstack builder does not support adding additionnal blockstorage volumes to VM.

This is a case useful to add persistent data disks to VMs.

It is available on Azure builder ( https://www.packer.io/docs/builders/azure.html#disk_additional_size ) and AWS builder ( https://www.packer.io/docs/builders/amazon-instance.html#ami_block_device_mappings ) but not in Openstack builder.

There references API are : 
 - Create a volume : https://docs.openstack.org/api-ref/block-storage/v3/?expanded=upload-volume-to-image-detail#create-a-volume
 - Attach a volume : https://docs.openstack.org/api-ref/block-storage/v3/?expanded=upload-volume-to-image-detail#attach-volume-to-a-server

**Comment by rickard-von-essen** [comment]
Sorry I misunderstood it as attach multiple volumes and save more than one to the image.

**Comment by lmayorga1980** [comment]
In my case, I would like to have a separate Openstack Volume just like AWS EBS Volume that have some persistent data that is used as input for the openstack builder. During the packer build, that volume is attached and later detached.
