### ISSUE TITLE
Potential MPL-2.0/GPL-3 license violation through bundling Go.Sed

### ISSUE THREAD

**Issue by mgorny** [hashicorp/packer#8103]
Disclaimer: IANAL. I'm trying my best to be helpful but I may be wrong.

While investigating the licenses of vendored dependencies for Gentoo inclusion, I've noticed that Go.Sed's LICENSE file indicates GPL-3. Per GPL license terms, any software linking to GPL-3 must also use GPL-3 or more restrictive license. Therefore, as long as Go.Sed is used, packer can not be licensed MPL-2.0.

FWICS MPL-2.0 has some special guide on combining MPL-2.0 and GPL-3 code: https://www.mozilla.org/en-US/MPL/2.0/combining-mpl-and-gpl/

The way I understand it, you can freely license all of packer's sources as MPL-2.0 but you need to license the combined work as GPL-3. If you remove/disable Go.Sed, you can distribute everything as MPL-2.0.

**Comment by azr** [comment]
Thanks for reporting @mgorny ! I opened #8119 to fix this.
