### ISSUE TITLE
SSH proxy implementation has broken ansible completely

### ISSUE THREAD

**Issue by armenr** [hashicorp/packer#8104]
So there are a bunch of different issues throughout the repo that talk about the fact that remote and local ansible provisioner implementations are broken.

Short of going back and customizing all of my automation to enforce Ansible 2.7 and some older version of Packer...will there be a fix to address this issue?

I've tried everything I've found in the github issues. Nothing appears to work.

**Comment by rickard-von-essen** [comment]
Don't think the `ansible-local` provisioner is broken in any way? Do you have any reference?

**Comment by armenr** [comment]
I tried it on my machine - didn't appear to work. I'll post configs and setup files when I'm back behind my workstation.

**Comment by armenr** [comment]
Ah yes - I remembered now.

Asking me to move to a fully ansible-local strategy breaks some of our automation, since we don't maintain separate automation for Packer+Ansible VS regular ol' Ansible.

Can't do it.

The easiest fix was to downgrade my locally installed Ansible to the latest 2.6.x release. 

Awesome.

I understand that something must have changed on the Ansible side, but it sure would be helpful to understand exactly what's breaking Packer's ability to provision with ansible_remote.

Looking through the issues, it would seem like this SSH proxy discussion has been going since as early as 2016.

**Comment by armenr** [comment]
Meh. This isn't worth the trouble. I'm just going to leave notes here for anyone else that hits the unlucky issue I did.

Working versions of Ansible (as of this writing):
- 2.6.19
- 2.7.13
- 2.8.5

Explicitly specifying our python interpreter in our ansible.cfg for Packer:
`ansible_python_interpreter = /usr/bin/python3`

That's it. Looks like the issue was endemic to my version 2.7.6 in my case. Updating to the latest 2.7.x or 2.8.x releases appears to have fixed it, in combination with specifying explicit interpreter path.
