### ISSUE TITLE
Default KMS key used when renaming AMI in amazon-import post-processor

### ISSUE THREAD

**Issue by iizukamike** [hashicorp/packer#8108]
Using Packer version 1.4.3, if you enable encryption of the resulting AMI with a custom KMS key when using the amazon-import post-processor and also specify an AMI name then the resulting AMI will actually be encrypted with the default KMS key instead.

e.g.

```
"post-processors":
  [
       {
          "type": "amazon-import",
          "region": "eu-west-1",
          "s3_bucket_name": "my_bucket",
          "ami_encrypt": true,
          "ami_name": "my_custom_ami_name",
          "ami_kms_key": "arn:aws:kms:eu-west-1:account_number:key/abcdefg-d83h-a912-a3f4-6f4aae57d3f5"
       }
]
```

The origin of this appears to be [here](https://github.com/hashicorp/packer/blob/4d4bd38afafd3f8e5ed406dbd50515239f48effa/post-processor/amazon-import/post-processor.go#L276) where the encryption parameters are not passed to the CopyImage call

**Comment by SwampDragons** [comment]
Does the binary [here](https://circleci.com/gh/hashicorp/packer/12475#artifacts/containers/0) solve your issue?

**Comment by iizukamike** [comment]
Only able to test the darwin build at the moment, but that fixes the issue for me.

Thanks.

**Comment by azr** [comment]
Awesome; thanks !
