### ISSUE TITLE
Builder: `docker` does not run `ONBUILD RUN` commands in the `changes` JSON list

### ISSUE THREAD

**Issue by nhooey** [hashicorp/packer#8124]
When using the `docker` builder with a list of `changes`, those commands don't get run before the `provisioner` step.

Why would the `changes` not get run when this `builder` section is almost the same as the example in the [`docker` builder documentation](https://www.packer.io/docs/builders/docker.html)?

Packer template excerpt:
```json
  "builder": [
    {
      "type": "docker",
      "image": "ubuntu:18.04",
      "commit": true,
      "changes": [
        "USER root",
        "ONBUILD RUN apt-get --yes update",
        "ONBUILD RUN apt-get install --yes software-properties-common python3",
        "ONBUILD RUN apt-add-repository --yes --update 'ppa:ansible/ansible'",
        "ONBUILD RUN sudo apt-get install ansible"
      ]
    }
  ]
```

Relevant Packer output:
```
==> docker: Creating a temporary directory for sharing data...
==> docker: Pulling Docker image: ubuntu:18.04
    docker: 18.04: Pulling from library/ubuntu
    docker: Digest: sha256:d1d454df0f579c6be4d8161d227462d69e163a8ff9d20a847533989cf0c94d90
    docker: Status: Image is up to date for ubuntu:18.04
    docker: docker.io/library/ubuntu:18.04
==> docker: Starting docker container...
    docker: Run command: docker run -v /Users/nhooey/.packer.d/tmp:/packer-files -d -i -t --entrypoint=/bin/sh -- ubuntu:18.04
    docker: Container ID: fa1c806afc431fb16995d1d7cf17ed04d45609be326afdac131aa310a131976b
==> docker: Using docker communicator to connect: 172.17.0.2
==> docker: Committing the container
    docker: Image ID: sha256:90222257fa354ca5e15d9083b6f94371d0f36311778da0724ba344cb8f5cbf9d
==> docker: Killing the container: fa1c806afc431fb16995d1d7cf17ed04d45609be326afdac131aa310a131976b
==> docker: Running post-processor: docker-tag
    docker (docker-tag): Tagging image: sha256:90222257fa354ca5e15d9083b6f94371d0f36311778da0724ba344cb8f5cbf9d
    docker (docker-tag): Repository: 764382087991.dkr.ecr.eu-west-1.amazonaws.com/api:latest
Build 'docker' finished.
```

Packer version: `Packer v1.4.3`
Host platform: Mac OS

**Comment by nhooey** [comment]
Ah, the `ONBUILD` commands only get run in Docker when the image is being used a base for another build.

So how can you get Docker to run commands in the build phase, before an Ansible `provisioner` runs, for example, when there is no `RUN` command that can be used in the `changes` list?

**Comment by rickard-von-essen** [comment]
Use a `shell` provisioner.

**Comment by nhooey** [comment]
Closing because it's not actually a bug.

**Comment by nhooey** [comment]
@rickard-von-essen: So using Packer avoids the advantage of using cache when creating Docker images?

To emulate the same advantage, do you just build new templates based off of previous Docker images and AWS AMIs that were build with other templates?

**Comment by rickard-von-essen** [comment]
It avoids the evil of caching and builds everything into one layer (caching should only be used and is only useful on a laptop/workstations and should never be used in your pipeline/deploy) .

To use a base image can be useful but only for timesaving reasons if you have very long build times.
