### ISSUE TITLE
Struggling with packer building VM image for metasploitable 3

### ISSUE THREAD

**Issue by palmsnow** [hashicorp/packer#8138]
Using Packer version 1.4.3.

I am trying to setup metasploitable 3 by following the instructions provided in the link below.

https://github.com/rapid7/metasploitable3/blob/master/README.md

Everything supposed to be handled by this power-shell script but the process failed as shown in the script output below.

> PS C:\repos\metasploitable3> packer build --only=vmware-iso ./packer/templates/windows_2008_r2.json
> 
> vmware-iso output will be in this color.
> 
> Warnings for build 'vmware-iso':
> 
> * Your vmx data contains the following variable(s), which Packer normally sets when it generates its own default vmx template. This may cause your build to fail or behave unpredictably: numvcpus, memsize, scsi0.virtualDev
> 
> ==> vmware-iso: Retrieving ISO
> 
> ==> vmware-iso: Trying http://download.microsoft.com/download/7/5/E/75EC4E54-5B02-42D6-8879-D8D3A25FBEF7/7601.17514.101119-1850_x64fre_server_eval_en-us-GRMSXEVAL_EN_DVD.iso
> ==> vmware-iso: Trying http://download.microsoft.com/download/7/5/E/75EC4E54-5B02-42D6-8879-D8D3A25FBEF7/7601.17514.101119-1850_x64fre_server_eval_en-us-GRMSXEVAL_EN_DVD.iso?checksum=md5%3A4263be2cf3c59177c45085c0a7bc6ca5
> ==> vmware-iso: http://download.microsoft.com/download/7/5/E/75EC4E54-5B02-42D6-8879-D8D3A25FBEF7/7601.17514.101119-1850_x64fre_server_eval_en-us-GRMSXEVAL_EN_DVD.iso?checksum=md5%3A4263be2cf3c59177c45085c0a7bc6ca5 => C:\repos\metasploitable3\packer_cache\c969d0a251f6f1d43e47e146749928fecb7568ab.iso
> 
> ==> vmware-iso: Creating floppy disk...
> 
> vmware-iso: Copying files flatly from floppy_files
> 
> vmware-iso: Copying file: C:\repos\metasploitable3\packer\templates/../answer_files/2008_r2/Autounattend.xml
> 
> vmware-iso: Copying file: C:\repos\metasploitable3\packer\templates/../../scripts/configs/microsoft-updates.bat
> 
> vmware-iso: Copying file: C:\repos\metasploitable3\packer\templates/../../scripts/configs/win-updates.ps1
> 
> vmware-iso: Copying file: C:\repos\metasploitable3\packer\templates/../../scripts/installs/openssh.ps1
> 
> vmware-iso: Copying file: C:\repos\metasploitable3\packer\templates/../../scripts/installs/install_dotnet45.ps1
> 
> vmware-iso: Copying file: C:\repos\metasploitable3\packer\templates/../../scripts/installs/install_wmf.ps1
> 
> vmware-iso: Copying file: C:\repos\metasploitable3\packer\templates/../../resources/certs/oracle-cert.cer
> 
> vmware-iso: Copying file: C:\repos\metasploitable3\packer\templates/../../resources/certs/gdig2.crt
> 
> vmware-iso: Copying file: C:\repos\metasploitable3\packer\templates/../../resources/certs/comodorsadomainvalidationsecureserverca.crt
> 
> vmware-iso: Copying file: C:\repos\metasploitable3\packer\templates/../../resources/certs/comodorsacertificationauthority.crt
> 
> vmware-iso: Copying file: C:\repos\metasploitable3\packer\templates/../../resources/certs/addtrust_external_ca.cer
> 
> vmware-iso: Copying file: C:\repos\metasploitable3\packer\templates/../../resources/certs/baltimore_ca.cer
> 
> vmware-iso: Copying file: C:\repos\metasploitable3\packer\templates/../../resources/certs/digicert.cer
> 
> vmware-iso: Copying file: C:\repos\metasploitable3\packer\templates/../../resources/certs/equifax.cer
> 
> vmware-iso: Copying file: C:\repos\metasploitable3\packer\templates/../../resources/certs/globalsign.cer
> 
> vmware-iso: Copying file: C:\repos\metasploitable3\packer\templates/../../resources/certs/gte_cybertrust.cer
> 
> vmware-iso: Copying file: C:\repos\metasploitable3\packer\templates/../../resources/certs/microsoft_root_2011.cer
> 
> vmware-iso: Copying file: C:\repos\metasploitable3\packer\templates/../../resources/certs/thawte_primary_root.cer
> 
> vmware-iso: Copying file: C:\repos\metasploitable3\packer\templates/../../resources/certs/utn-userfirst.cer
> 
> vmware-iso: Done copying files from floppy_files
> 
> vmware-iso: Collecting paths from floppy_dirs
> 
> vmware-iso: Resulting paths from floppy_dirs : []
> 
> vmware-iso: Done copying paths from floppy_dirs
> 
> ==> vmware-iso: Creating required virtual machine disks
> 
> ==> vmware-iso: Building and writing VMX file
> 
> ==> vmware-iso: Starting virtual machine...
> 
> ==> vmware-iso: Waiting 10m0s for boot...
> 
> ==> vmware-iso: Connecting to VM via VNC (127.0.0.1:5943)
> 
> ==> vmware-iso: Error connecting to VNC: dial tcp 127.0.0.1:5943: connectex: No connection could be made because the target machine actively refused it.
> 
> ==> vmware-iso: Deleting output directory...
> 
> Build 'vmware-iso' errored: Error connecting to VNC: dial tcp 127.0.0.1:5943: connectex: No connection could be made because the target machine actively refused it.
> 
> ==> Some builds didn't complete successfully and had errors:
> 
> --> vmware-iso: Error connecting to VNC: dial tcp 127.0.0.1:5943: connectex: No connection could be made because the target machine actively refused it.
> 
> ==> Builds finished but no artifacts were created.

Any ideas what's going wrong in the setup and how to troubleshoot/fix it?

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out!  For general "why isn't this working" issues, I'd recommend reaching out to the [mailing list](https://groups.google.com/forum/#!forum/packer-tool) or [community forum](https://discuss.hashicorp.com/c/packer) for help.  The issue tracker is reserved for bugs and feature requests, as it is only reviewed by the maintainers, rather than the larger community of people who follow the Packer mailing list.

For general debugging advice, I'd recommend running Packer with the --debug flag and then trying to VNC into the instance manually once Packer launches it, to verify that the instance's VNC is available. Otherwise, you'll probably need to figure out what about your VMware setup is refusing VNC. It may be that VMware wants to require a password, in which case you may want to check out https://www.packer.io/docs/builders/vmware-iso.html#vnc_disable_password

Since this is a question and not a bug, I'm going to close, but if the advice here is insufficient, do please reach out to the mailing list :)

Thanks!
