### ISSUE TITLE
packer-proxmox cannot create zfs-disk on PVE 6.02

### ISSUE THREAD

**Issue by chymian** [hashicorp/packer#8140]
using packer to create a debian template on a ZFS-Pool on PVE fails.

The relevant Error seems to be the suffix `.<nil>` of the name of the file to be created:
```
Build 'proxmox' errored: Error creating VM: 500 zfs error: cannot create 'rpool/data/vm-10000-disk-0.<nil>': invalid character '<' in name, error status:  (params: map[agent:1 cores:2 cpu:host description:Packer ephemeral build VM ide2:local:iso/debian-10.0.0-amd64-netinstal.iso,media=cdrom memory:512 name:packer-5d87a52f-34fb-4be7-1e02-9d950e3e91d4 net0:virtio=06:AC:A5:33:E9:3B,bridge=vmbr0 net1:virtio=9E:AF:55:20:5C:4F,bridge=vmbr1 onboot:false ostype:l26 sockets:1 virtio0:media=disk,size=5G,file=data:10000/vm-10000-disk-0.<nil> vmid:10000])
```

template taken from the docu section:
…
```
      "disks": [
        {
          "type": "scsi",
          "disk_size": "5G",
          "storage_pool": "data",
          "storage_pool_type": "zfs"
        }
      ],
```
  
Versions:
```
packer version && ssh arrakis pveversion && lsb_release -d && cat /etc/debian_version 
Packer v1.4.3
pve-manager/6.0-7/28984024 (running kernel: 5.0.21-1-pve)
Description:    Debian GNU/Linux 10 (buster)
10.1
```
Logs:
https://gist.github.com/chymian/192cea2f97083c0e726daf2f141bbb55

**Comment by SwampDragons** [comment]
@carlprett can you take a look at this?  Also, can I add you to the codeowners file for the proxmox builder?

**Comment by carlpett** [comment]
@chymian Good find! I'll fix it.
@SwampDragons I added it in #8069, I thought? Do I need to do anything else?

**Comment by SwampDragons** [comment]
Weird, you're right. I wonder why you didn't come up in the assign tab.

**Comment by carlpett** [comment]
Going a bit off-topic here, but continuing the codeowners track, if I understand it correctly I'd need some permissions: https://help.github.com/en/articles/about-code-owners
>The people you choose as code owners must have write permissions for the repository.
