### ISSUE TITLE
ssh_host for ssh communicator has lower priority than amazon-ebs builder

### ISSUE THREAD

**Issue by omegagussan** [hashicorp/packer#8154]
#### Overview of the Issue / ### Reproduction Steps

When building packer with a .json file like:
    "min_packer_version": "1.4.3",
    "variables": {
        "aws_access_key": "{{env `AWS_ACCESS_KEY`}}",
        "aws_secret_key": "{{env `AWS_SECRET_KEY`}}",
        "aws_region": "eu-west-1",
...
    },
    "builders": [{
        "type": "amazon-ebs",
        "ssh_host": "**52.210.yyy.xxx**",
        "ssh_username": "ubuntu",
...
packer still insists on trying to create to the automatically generated public ip of amazon-ebs like suggested by these logs:
==> amazon-ebs: Using ssh communicator to connect: **34.242.yyy.xxx**
Waiting for SSH, up to timeout: 5m0s
==> amazon-ebs: Waiting for SSH to become available...
TCP connection to SSH ip/port failed: dial tcp **34.242.180.148**:22: i/o timeout

Instead of my expected manually set IP in the config starting with **52.210.yyy.xxx**
Packer ssh_host field has lower priority than amazon-ebs builder

### Packer version
1.4.3

### Operating system and Environment details

OSX x64

Note: this is similar to what is https://github.com/hashicorp/packer/issues/7195 to have been closed in the latest release
https://github.com/hashicorp/packer/pull/7832
https://github.com/hashicorp/packer/issues/7195

**Comment by SwampDragons** [comment]
thanks for opening this -- I've made PR #8162 to address it, and it'll be released next week with v1.4.4
