### ISSUE TITLE
[amazon ebs] .SourceAMIName not available in manifest post-processor

### ISSUE THREAD

**Issue by anilkumarmyla** [hashicorp/packer#8157]
#### Overview of the Issue
We're trying to output `.SourceAMIName` to manifest, but its not working. Given the following manifest post-processor, at the end of packer build custom_data has "no value". Is there any other way to output `.SourceAMIName` into the manifest?

Input
```
  "post-processors": [
    {
      "type": "manifest",
      "output": "manifest.json",
      "strip_path": true,
      "custom_data": {
        "source_ami_name": "{{ .SourceAMIName }}"
      }
    }
  ]
```

Output
```
      "custom_data": {
        "source_ami_name": "\u003cno value\u003e"
      }
```

### Packer version
1.4.3

**Comment by SwampDragons** [comment]
This can be addressed by #7079, which we're targeting for the 1.5.0 release. I'm going to close this issue so we can track it there on the larger issue, but I've put your use case in the comments as part of the definition of done for that issue.

**Comment by SwampDragons** [comment]
Reopening; some groundwork has been laid in 7079, but this will require a little extra work to implement.

**Comment by sylviamoss** [comment]
Hi @anilkumarmyla! 
I've implemented a solution for this and you can check it out these binaries until is released: https://circleci.com/gh/hashicorp/packer/29574#artifacts/containers/0

However, instead of using  `{{ .SourceAMIName }}` you should use the new build function of the template engine that we released on 1.5.0. 

Your template should look like: 
```
"post-processors": [
    {
      "type": "manifest",
      "output": "manifest.json",
      "strip_path": true,
      "custom_data": {
        "source_ami_name": "{{ build `SourceAMIName` }}"
      }
    }
  ]
```
In case you need to read more about this fuction, it's documented [here](https://www.packer.io/docs/templates/engine.html#build). Also, feel free to make any question :D

**Comment by anilkumarmyla** [comment]
@sylviamoss @SwampDragons I tried this with packer 1.5.2 and got this instead
```
        "source_ami_name": "Build_SourceAMIName. To set this dynamically in the Packer template, you must use the `build` function"
```

**Comment by sylviamoss** [comment]
This happened even with 
```
 "source_ami_name": "{{ build `SourceAMIName` }}"
```
?

**Comment by anilkumarmyla** [comment]
Yes, that's what I tried :-)

**Comment by sylviamoss** [comment]
Thanks for bringing this up! I'm having a look at this right now, it didn't work for me as well.

**Comment by anilkumarmyla** [comment]
@sylviamoss Thanks for the quick response and the fix! Any timeline for the next release, gotta wait this one out too 😞 ?

**Comment by SwampDragons** [comment]
We'll probably do a fairly fast turnaround for v1.5.3 because we want to fix this. I'm going to aim for doing a small release in a week or two.

**Comment by anilkumarmyla** [comment]
This works in 1.5.4, thanks! @sylviamoss @SwampDragons
