### ISSUE TITLE
Digital Ocean builder with Ansible provisioner. 

### ISSUE THREAD

**Issue by goodwillhacking** [hashicorp/packer#8164]
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue
Running packer with the digitalocean builder and ansible as a provider. The problem does not see mto be with packer but rather with ansible and being able to connect to the server. From the documentatioon here https://www.packer.io/docs/provisioners/ansible.html

It says packer should create an inventory file - but I do not see any - playbook seems to be using localhost. 

I am using a structure/approach that seems to be the convention based on my searches. Not sure if it is a but or if I am  doing something wrong?

#### Reproduction Steps

Steps to reproduce this issue

### Packer version
 `1.4.3`
### Ansible version
 `2.7.5`
### Python  version
`3.6.8`

### Simplified Packer Buildfile
```json
{
  "variables": {
    "do_api_token": "token",
    "do_size": "1gb"
  },
  "builders": [
    {
      "type": "digitalocean",
      "image": "ubuntu-18-04-x64",
      "tags": ["ubuntu-18_04", "test"],
      "api_token": "{{user `do_api_token`}}",
      "name": "ubuntu-18-04-x64_test_{{timestamp}}",
      "size": "{{user `do_size`}}",
      "region": "nyc1",
      "ssh_username": "root"
    }
  ],

  "provisioners": [
    {
      "type": "ansible",
      "playbook_file": "./ansible/main.yml"
    }
  ]
}
```
## Ansible  playbook
./ansible/main.yml
```yml
---
- hosts: all
  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day`
```

./ansible/ansible.cfg 
```yml
[defaults]
inventory = ./inventory
remote_user = root
`
### Operating system and Environment details
`Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
```
OS, Architecture, and any other information you can provide about the
environment.

### Log Fragments and crash.log files
```bash
ubuntu-18-04-x64_test_1569527924 output will be in this color.

==> ubuntu-18-04-x64_test_1569527924: Creating temporary ssh key for droplet...
==> ubuntu-18-04-x64_test_1569527924: Creating droplet...
==> ubuntu-18-04-x64_test_1569527924: Waiting for droplet to become active...
==> ubuntu-18-04-x64_test_1569527924: Using ssh communicator to connect: 165.227.200.189
==> ubuntu-18-04-x64_test_1569527924: Waiting for SSH to become available...
==> ubuntu-18-04-x64_test_1569527924: Connected to SSH!
==> ubuntu-18-04-x64_test_1569527924: Provisioning with Ansible...
==> ubuntu-18-04-x64_test_1569527924: Executing Ansible: ansible-playbook --extra-vars packer_build_name=ubuntu-18-04-x64_mongo-4-2_1569527924 packer_builder_type=digitalocean -o IdentitiesOnly=yes -i /tmp/packer-provisioner-ansible829621104 //home/user/ops/infra-ops/image_builds/packer/mongo-images/ansible/main.yml -e ansible_ssh_private_key_file=/tmp/ansible-key733337365
    ubuntu-18-04-x64_test_1569527924:
    ubuntu-18-04-x64_test_1569527924: PLAY [all] *********************************************************************
    ubuntu-18-04-x64_test_1569527924:
    ubuntu-18-04-x64_test_1569527924: TASK [Gathering Facts] *********************************************************
    ubuntu-18-04-x64_test_1569527924:   RequestsDependencyWarning)
    ubuntu-18-04-x64_test_1569527924: fatal: [default]: FAILED! => {"changed": false, "module_stderr": "/bin/sh: 1: /usr/bin/python: not found\nShared connection to 127.0.0.1 closed.\r\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 127}
    ubuntu-18-04-x64_test_1569527924:      to retry, use: --limit @/home/user/ops/infra-ops/image_builds/packer/mongo-images/ansible/main.retry
    ubuntu-18-04-x64_test_1569527924:
    ubuntu-18-04-x64_test_1569527924: PLAY RECAP *********************************************************************
    ubuntu-18-04-x64_test_1569527924: default                    : ok=0    changed=0    unreachable=0    failed=1
    ubuntu-18-04-x64_test_1569527924:
==> ubuntu-18-04-x64_test_1569527924: Destroying droplet...
==> ubuntu-18-04-x64_test_1569527924: Deleting temporary ssh key...
Build 'ubuntu-18-04-x64_test_1569527924' errored: Error executing Ansible: Non-zero exit status: exit status 2

==> Some builds didn't complete successfully and had errors:
--> ubuntu-18-04-x64_test_1569527924: Error executing Ansible: Non-zero exit status: exit status 2
```

Set the env var `PACKER_LOG=1` for maximum log detail.

**Comment by andrewsomething** [comment]
The key part of the error is:

```
"module_stderr": "/bin/sh: 1: /usr/bin/python: not found
```

Ubuntu 18.04 cloud images only ship with `/usr/bin/python3`, but your version of Ansible wants `/usr/bin/python` on the remote host. There are some ways to work around this. See: [How do I handle python not having a Python interpreter at /usr/bin/python on a remote machine?](https://docs.ansible.com/ansible/latest/reference_appendices/faq.html#how-do-i-handle-python-not-having-a-python-interpreter-at-usr-bin-python-on-a-remote-machine)

Upgrading to Ansible >= 2.8 should also resolve this issue for you. From the changelog: 

> Python interpreter discovery - The first time a Python module runs on a target, Ansible will attempt to discover the proper default Python interpreter to use for the target platform/version (instead of immediately defaulting to /usr/bin/python). You can override this behavior by setting ansible_python_interpreter or via config. (see https://github.com/ansible/ansible/pull/50163)

https://github.com/ansible/ansible/blob/stable-2.8/changelogs/CHANGELOG-v2.8.rst#major-changes

**Comment by goodwillhacking** [comment]
@andrewsomething - I really appreciate it. Upgrading solved it. Should have caught that one. Cheers
