### ISSUE TITLE
disable_stop_instance for builder/azure

### ISSUE THREAD

**Issue by postmart** [hashicorp/packer#8181]
#### Feature Description

Add `disable_stop_instance` functionality for builder/azure

#### Use Case(s)

For some cases we need to keep VM running, we would like to use `disable_stop_instance`for that, since where is no any similar functionality enabled in builder/azure at the moment.

**Comment by paulmey** [comment]
Azure needs to shut down the VM to capture the image. Are you asking the builder to turn it back on after the image capture?

**Comment by SwampDragons** [comment]
@paulmey AWS has this functionality and the idea is that if you're shutting down the instance via sysprep, you don't want to have a separate step to try to shut down the already shutoff image.

https://www.packer.io/docs/builders/amazon-ebs.html#disable_stop_instance

**Comment by paulmey** [comment]
Thanks @SwampDragons . @postmart, is that what you need?

**Comment by postmart** [comment]
@paulmey, yes, this is what we need. We use this functionality in AWS and would like to get the same behaviour on Azure.
Thanks a lot!

**Comment by bumblebee939** [comment]
@postmart, how are you able to use the disablestopinstance in the  AWS build, can I get a snippet of where this block is placed.

I am running into an issue where sysprep is killing my winrm issue and cannot find a way around it.

**Comment by usrme** [comment]
> @postmart, how are you able to use the disablestopinstance in the AWS build, can I get a snippet of where this block is placed.
> 
> I am running into an issue where sysprep is killing my winrm connection and cannot find a way around it.

Would [this](https://hodgkins.io/best-practices-with-packer-and-windows#disable-winrm-on-build-completion-and-only-enable-it-on-first-boot) help with your `sysprep` issue?

**Comment by postmart** [comment]
We could not find a workaround for this, and decided not to use packer for Azure for now. I am closing this issue.
