### ISSUE TITLE
When using hcloud builder, 'unknown configuration key: "image_filter"'

### ISSUE THREAD

**Issue by dnk8n** [hashicorp/packer#8188]
#### Overview of the Issue

According to docs - https://www.packer.io/docs/builders/hetzner-cloud.html, I should be able to use image_filter. However I get error: `unknown configuration key: "image_filter"`

#### Reproduction Steps

packer build template.json (see example template below)

### Packer version

1.4.3

### Simplified Packer Buildfile

    {
      "type": "hcloud",
      "token": "{{user `hcloud_token`}}",
      "image_filter": {
        "with_selector": [
          "name=={{user `hcloud_image`}}"
        ],
        "most_recent": true
      },
      "location": "{{user `hcloud_location`}}",
      "server_type": "{{user `hcloud_server_type`}}",
      "ssh_username": "{{user `ssh_username`}}",
      "snapshot_name": "{{user `image_name`}}",
      "user_data": "{{user `user_data`}}",
      "ssh_private_key_file": "{{user `hcloud_preprovision_key`}}"
    }

### Operating system and Environment details

Dockerized. I use ansible and create docker image with the following:

```
ARG ALPINE_VERSION=3.10
ARG PYTHON_VERSION=3.7.4
ARG PACKER_VERSION=1.4.3

FROM python:${PYTHON_VERSION}-alpine${ALPINE_VERSION} AS python
ENV PYTHONUNBUFFERED=1 PYTHONDONTWRITEBYTECODE=1

FROM hashicorp/packer:${PACKER_VERSION} AS packer

FROM python AS build
COPY --from=packer /bin/packer /usr/local/bin/packer
RUN apk add --no-cache alpine-sdk libffi-dev openssl-dev
ARG ANSIBLE_VERSION=2.8.5
RUN pip install ansible==${ANSIBLE_VERSION}
RUN set -ex; find /usr/local -depth \( -type f -a \( -name '*.pyc' -o -name '*.pyo' \) \) -exec rm -rf '{}' +;

FROM python AS release-base
RUN apk add --no-cache openssh-client
COPY --from=build /usr/local /usr/local

FROM release-base AS release-final
RUN ansible-galaxy install geerlingguy.pip && ansible-galaxy install geerlingguy.docker
```

**Comment by SwampDragons** [comment]
@LKaemmerling can you take a look at this?

**Comment by LKaemmerling** [comment]
Hey, I’m actually on vacation and will be back at 14.10. I will look into this when I’m back.

**Comment by LKaemmerling** [comment]
@dnk8n could you please provider a template.json with the exact values you use? (But please remove the API token). I guess you want to try to filter by the image name, is this correct? This is not possible with the `with_selector` flag, you can only use label selectors there. https://docs.hetzner.cloud/#overview-label-selector

**Comment by LKaemmerling** [comment]
@dnk8n could you please provider a template.json with the exact values you use? (But please remove the API token). I guess you want to try to filter by the image name, is this correct? This is not possible with the `with_selector` flag, you can only use label selectors there. https://docs.hetzner.cloud/#overview-label-selector

**Comment by SwampDragons** [comment]
Closing because we never heard back from the user.
