### ISSUE TITLE
Use standard Scaleway env vars / config file

### ISSUE THREAD

**Issue by OJFord** [hashicorp/packer#8191]
#### Feature Description

Terraform uses the same environment variables and config files as used by Scaleway's own tooling, unless overridden:
https://www.terraform.io/docs/providers/scaleway/index.html#environment-variables

Packer however uses different environment variables (that sound 'official' enough, but are actually just for packer) and ignores the config file:
https://www.packer.io/docs/builders/scaleway.html#required-

#### Use Case(s)

Harmony among tools!

**Comment by SwampDragons** [comment]
@sieben can you investigate?

**Comment by brandon-welsch** [comment]
+1
