### ISSUE TITLE
How to use ansible tags with packer

### ISSUE THREAD

**Issue by krishan111284** [hashicorp/packer#8218]
How to use ansible tags with packer.  Packer version is 1.4.4.

My provisioners.......

  "provisioners": [
        {
            "type": "shell",
            "inline": "sudo yum install -y ansible"
        },
        {
            "type": "ansible",
            "user": "centos",
            "extra_arguments": [
                "--extra-vars",
                "-e servicename=nginx --tags=microservice"],
            "playbook_file": "/opt/ansible-infra/infra.yaml"

**Comment by SwampDragons** [comment]
You're supplying them to extra-arguments just a little wrong. Instead of the equal sign, quote them separately and separate the strings with a comma

```
"extra_arguments": ["--tags", "microservice"]
```
