### ISSUE TITLE
packer crashing - panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by mennlo** [hashicorp/packer#8237]
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

I am trying to utilize the vsphere-iso plugin to create a vsphere template and I and getting a Packer crash message.

"panic: runtime error: invalid memory address or nil pointer dereference"

#### Reproduction Steps

packer build packer_vb_vsphere.json

### Packer version

Packer v1.4.4

### Simplified Packer Buildfile

{
    "builders": [
        {
            "type": "vsphere-iso",
            "vcenter_server": "vcenter@domain.com",
            "username": "svcpacker@comfort.com",
            "password": "packer",
            "insecure_connection": true,
            "vm_name": "packer-centos-7-x86_64",
            "cluster": "cluster name",
            "host": "host.domain.com",
            "datastore": "VMDATA01",
            "guest_os_type": "centos7_64Guest",
            "CPUs": 2,
            "RAM": 4096,
            "RAM_reserve_all": true,
            "convert_to_template": true,
            "disk_size": 81920
        }
    ]
}

### Operating system and Environment details

Running build from Mac using Packer v1.4.4
vSphere Client version 6.7.0.40000

### Log Fragments and crash.log files

[crash.log](https://github.com/hashicorp/packer/files/3731320/crash.log)

Set the env var `PACKER_LOG=1
` for maximum log detail.

**Comment by SwampDragons** [comment]
Thanks for opening. Currently the vSphere plugin is a third party plugin that we don't technically support, although we will probably be bringing it into the main Packer build soon. I'll take a look at this after we've merged the vSphere plugin with core and officially support it.

**Comment by mennlo** [comment]
Okay thanks for the quick response

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by WebSpider** [comment]
This is scheduled to happen on the next release, happy times! 🎉

**Comment by jhawk28** [comment]
I think this one is OBE as the addStorage() does not exist in the latest version of the plugin. If you look at the stacktrace, it is pointing to an old fork of the plugin: https://github.com/martezr/packer-builder-vsphere/blob/master/driver.go#L328

**Comment by sylviamoss** [comment]
As @jhawk28  the `addStorage()` method no longer exists in the newest Packer version. I'm closing this one for now and feel free to reach out if you have an issue with the version.
