### ISSUE TITLE
AWS AMI Platform Reading as Other Linux when Created from Amazon Linux 2 Base AMI

### ISSUE THREAD

**Issue by radsec** [hashicorp/packer#8238]
#### Overview of the Issue

When creating a custom Amazon Linux 2 AMI and using the base Amazon Linux 2 Base AMI as the source AMI, the resulting AMI shows "Other Linux" under the platform. It should display "Amazon Linux 2"

![image](https://user-images.githubusercontent.com/39590744/66926678-77125d00-effc-11e9-9724-f8ae7a19a187.png)

#### Reproduction Steps

packer build test_awslinux2_custom.json

### Packer version

Packer v1.4.4

### Simplified Packer Buildfile
test_awslinux2_custom.json:
```json
{
"builders": [
    {
      "type": "amazon-ebs",
      "ami_name": "awslinux2-golden-{{isotime | clean_resource_name}}",
      "tags": {
        "OS_Version": "Amazon Linux 2",
        "Base_AMI_Name": "{{ .SourceAMIName }}",
        "Extra": "{{ .SourceAMITags.TagName }}"
      },
      "region": "us-west-2",
      "ami_regions": ["us-west-2"],
      "instance_type": "t3.medium",
      "encrypt_boot": true,
      "source_ami_filter": {
        "filters": {
          "virtualization-type": "hvm",
          "name": "amzn2-ami-hvm-2.0.*-x86_64-gp2",
          "root-device-type": "ebs"
        },
        "owners": ["amazon"],
        "most_recent": true
      },
      "ssh_username": "ec2-user"
    }]
}
```
### Operating system and Environment details

MacOS - Mojave - v10.14.6

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out. I'm 99% sure this is a bug with Amazon, not Packer. I see their developer forums full of people asking this question, but they're pretty light on answers unfortunately. The API call we use to create the image doesn't even allow us to overwrite that field so we couldn't be messing it up even if we wanted to.

**Comment by SwampDragons** [comment]
I don't think there's anything we can do about this, so I'm going to close the issue.

**Comment by matrey** [comment]
It seems like Amazon just parses the AMI name (thanks https://www.turnkeylinux.org/comment/12501 for the hint)

Example with ubuntu:
```
"bionic 20191205 (build 1576658994)" -> Platform=Other Linux
"Ubuntu bionic 20191205 (build 1576660092)" -> Platform=Ubuntu
```

In your case, your AMI name contains "awslinux2", while stock Amazon Linux AMIs seem to be named with "amzn2" instead.

**Comment by SwampDragons** [comment]
ooh TIL -- thanks @matrey
