### ISSUE TITLE
Optional variable for ssh key

### ISSUE THREAD

**Issue by KVInventoR** [hashicorp/packer#8243]
Hi All,

Have a question:
 is it possible to create optional variable for ssh_private_key_file and ssh_keypair_name?

I use next code:
```
   "variables": {
     "home": "{{ env `HOME` }}"
   },
   "builders":[
         "ssh_keypair_name":"{{ user `ssh_keypair_name` }}",
         "ssh_private_key_file":"{{ user `home` }}/{{ user `ssh_private_key_file` }}",
   ]
}
```
And during run packer without set a variable, packer raise an error:
```
1 error(s) occurred:

* ssh_private_key_file is invalid: read /Users/userhome/: is a directory
```

I would like use both options, with ssh key and without in one time and 1 packer config file

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out. 

try changing the line 

```
         "ssh_private_key_file":"{{ user `home` }}/{{ user `ssh_private_key_file` }}",
```

to 

```
         "ssh_private_key_file":"{{ user `ssh_private_key_file` }}",
```

and just make sure the variable `ssh_private_key_file` is an absolute path.

**Comment by SwampDragons** [comment]
Further explanation: 

If the variable provided to "ssh_private_key_file" is anything other than an empty string, Packer will try to read it and error when that file doesn't exist or when the filepath is not complete.
