### ISSUE TITLE
Make it possible to specify explicit VM display name in Cloudstack builder

### ISSUE THREAD

**Issue by blinohod** [hashicorp/packer#8252]
#### Feature Description

Current version of cloudstack builder has VM display name hardcoded to "Created yb Packer".
https://github.com/hashicorp/packer/blob/master/builder/cloudstack/step_create_instance.go#L47

It would be great to make this configurable through JSON template parameters.

For example: `"instance_display_name": "my-builder.example.com"`

#### Use Case(s)

Some Cloudstack installations may rely on specific display name format which processed by custom templates or external applications. Currently it's impossible to change this parameter unfortunately and it's always has **Created by Packer** value. This enhancement may allow to use Packer with such Cloudstack clusters.

**Comment by SwampDragons** [comment]
Thanks for this suggestion! CloudStack is one of our community-supported builders, which means that the HashiCorp maintainers don't spend much engineering time on it; this means that the best way to see your suggestion make it into Packer is to open a PR. We'll gladly give support and pointers if you're interested in taking a shot at it.

In this particular case, I think the feature should be very straightforward to add, and would be a great first issue for someone wanting to get started with contributing to Packer.

**Comment by blinohod** [comment]
Tried to add support for this feature as it looked easy to do.
When tested with **instance_display_name** parameter specified and VM created with correct display name.
