### ISSUE TITLE
Failed to set up any network adapter in VirtualBox 6 on macOS

### ISSUE THREAD

**Issue by samvv** [hashicorp/packer#8277]
#### Overview of the Issue

This issue at first sight seems very related to #3757 but that was apparently closed, so I'm filing this as a new bug.

I'm trying to create a NixOS base box using the latest stable release of _packer_ with the `virtualbox-iso` builder, but unfortunately packer is having issues setting up the network adapter. The icon is simply missing when the GUI is visible. I can mess around a bit with `vboxmanage` to get it visible again, but I don't know what exact configuration packer is expecting.

#### Reproduction Steps

Issue `packer build example.json` (see below for the file)

### Packer version

Packer v1.4.4

### Simplified Packer Buildfile

**example.json**
```
{
  "builders": [{
    "type": "virtualbox-iso",
    "boot_command": [
      "<enter><wait30>",
      "sudo passwd root<enter><wait1>packer<enter><wait1>packer<enter><wait1>",
      "sudo systemctl start sshd<enter>"
    ],
    "guest_os_type": "Other Linux (64-bit)",
    "iso_url": "https://releases.nixos.org/nixos/19.09/nixos-19.09.941.27a5ddcf747/nixos-minimal-19.09.941.27a5ddcf747-x86_64-linux.iso",
    "iso_checksum": "c913b1e7670dbe985cac4260784859ad42eddb43caa3eef40c0af4d31e4178ad",
    "iso_checksum_type": "sha256",
    "ssh_username": "root",
    "ssh_password": "packer",
    "shutdown_command": "echo 'packer' | sudo -S shutdown -P now"
  }]
}
```

### Operating system and Environment details

 - macOS 10.14.6
 - VirtualBox v6.0.14

### Log Fragments and crash.log files

Just a log with 'SSH connection timeout', which is to be expected.

**Comment by SwampDragons** [comment]
>The icon is simply missing when the GUI is visible. I can mess around a bit with vboxmanage to get it visible again, but I don't know what exact configuration packer is expecting.

Sorry, I'm having trouble following. What icon?  

Can you share the logs that came before all the ssh timeout messages? A fair amount of information gets stored before them about how the vm setup went.

**Comment by samvv** [comment]
@SwampDragons I meant the icon in the VirtualBox GUI that shows the network adapters (if there are any). No icon means there are no network adapters, and I verified that this is the case from the command-line.

I'll try to upload a log file later this evening. Suffice to say that SSH times out because it cannot find any IP to connect to.

**Comment by sylviamoss** [comment]
Hi @samvv! I was able to build successfully the image by only changing the `guest_os_type` in your buildfile to `Linux_64`
```
{
  "builders": [{
    "type": "virtualbox-iso",
    "boot_command": [
      "<enter><wait30>",
      "sudo passwd root<enter><wait1>packer<enter><wait1>packer<enter><wait1>",
      "sudo systemctl start sshd<enter>"
    ],
    "guest_os_type": "Linux_64",
    "iso_url": "https://releases.nixos.org/nixos/19.09/nixos-19.09.941.27a5ddcf747/nixos-minimal-19.09.941.27a5ddcf747-x86_64-linux.iso",
    "iso_checksum": "c913b1e7670dbe985cac4260784859ad42eddb43caa3eef40c0af4d31e4178ad",
    "iso_checksum_type": "sha256",
    "ssh_username": "root",
    "ssh_password": "packer",
    "shutdown_command": "echo 'packer' | sudo -S shutdown -P now"
  }]
}
```
I don't know exactly why it doesn't work with `Other Linux (64-bit)` but when I run `VBoxManage list ostypes` this type doesn't appear in the list as ID only as description for `Linux_64`, see:
```
ID:          Linux_64
Description: Other Linux (64-bit)
Family ID:   Linux
Family Desc: Linux
64 bit:      true
```

**Comment by samvv** [comment]
Oh that's great, thanks! I don't have the time to test it right now, but if you're able to build then I believe this issue can be closed.
