### ISSUE TITLE
builder/virtualbox: Error removing iso due to virtualbox lock still being hold

### ISSUE THREAD

**Issue by rgl** [hashicorp/packer#8282]
#### Overview of the Issue

Packer is having errors removing/ejecting the guest additions iso from the device as you can see at the logs bellow.

This issue seems related to https://github.com/hashicorp/packer/issues/4432, which seems to hint that the problem also applies/happens to cdroms.

#### Reproduction Steps

packer build

### Packer version

1.4.4

### Simplified Packer Buildfile

```
...
    {
      "name": "ubuntu-{{user `version`}}-amd64-virtualbox",
      "type": "virtualbox-iso",
      "guest_os_type": "Ubuntu_64",
      "guest_additions_mode": "attach",
      "headless": true,
...
```

The full file is at https://github.com/rgl/ubuntu-vagrant/blob/master/ubuntu.json#L49.

### Operating system and Environment details

Packer is running on Windows 10 and launching an Ubuntu 18.04 guest in VirtualBox 6.0.14.

### Log Fragments and crash.log files

I've started having these errors removing the guest additions iso:

```
2019/10/27 09:16:08 packer.exe: 2019/10/27 09:16:08 [ERROR] Remote command exited without exit status or exit signal.
2019/10/27 09:16:08 ui error: [1;31m==> ubuntu-18.04-amd64-virtualbox: [sudo] password for vagrant:[0m
2019/10/27 09:16:08 packer.exe: 2019/10/27 09:16:08 Waiting max 5m0s for shutdown to complete
2019/10/27 09:16:09 packer.exe: 2019/10/27 09:16:09 VM shut down.
2019/10/27 09:16:09 packer.exe: 2019/10/27 09:16:09 Executing VBoxManage: []string{"storageattach", "packer-ubuntu-18.04-amd64-virtualbox-1572167140", "--storagectl", "IDE Controller", "--port", "0", "--device", "1", "--medium", "none"}
2019/10/27 09:16:09 packer.exe: 2019/10/27 09:16:09 stdout:
2019/10/27 09:16:09 packer.exe: 2019/10/27 09:16:09 stderr: VBoxManage.exe: error: Failed to get a console object from the direct session (VBOX_E_INVALID_OBJECT_STATE)
2019/10/27 09:16:09 packer.exe: VBoxManage.exe: error: Details: code VBOX_E_VM_ERROR (0x80bb0003), component MachineWrap, interface IMachine, callee IUnknown
2019/10/27 09:16:09 packer.exe: VBoxManage.exe: error: Context: "LockMachine(a->session, LockType_Shared)" at line 336 of file VBoxManageStorageController.cpp
2019/10/27 09:16:09 ui error: [1;31m==> ubuntu-18.04-amd64-virtualbox: Error detaching ISO: VBoxManage error: VBoxManage.exe: error: Failed to get a console object from the direct session (VBOX_E_INVALID_OBJECT_STATE)
==> ubuntu-18.04-amd64-virtualbox: VBoxManage.exe: error: Details: code VBOX_E_VM_ERROR (0x80bb0003), component MachineWrap, interface IMachine, callee IUnknown
==> ubuntu-18.04-amd64-virtualbox: VBoxManage.exe: error: Context: "LockMachine(a->session, LockType_Shared)" at line 336 of file VBoxManageStorageController.cpp[0m
2019/10/27 09:16:09 ui error: [1;31m==> ubuntu-18.04-amd64-virtualbox: Error detaching ISO: VBoxManage error: VBoxManage.exe: error: Failed to get a console object from the direct session (VBOX_E_INVALID_OBJECT_STATE)
==> ubuntu-18.04-amd64-virtualbox: VBoxManage.exe: error: Details: code VBOX_E_VM_ERROR (0x80bb0003), component MachineWrap, interface IMachine, callee IUnknown
==> ubuntu-18.04-amd64-virtualbox: VBoxManage.exe: error: Context: "LockMachine(a->session, LockType_Shared)" at line 336 of file VBoxManageStorageController.cpp[0m
2019/10/27 09:16:09 ui error: [1;31m==> ubuntu-18.04-amd64-virtualbox: Step "StepRemoveDevices" failed, aborting...[0m
```

Setting `"post_shutdown_delay": "2m"` works around the problem, but doing that feels more like an workaround rather than a root cause fix.

The problem might even be on VirtualBox (sorry, but I didn't try with an older version).

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out and sorry for the delay in responding. I'll take a look at fixing this before the next release.

**Comment by sylviamoss** [comment]
Hi @rgl! 
I tried to reproduce the error with the files from the repo your provided but my builds went out all successfully. 😐 
I see that you have updated those files in the last month, so I tried building the image with the current version of your files and also the version of when you opened the issue. 
Can you confirm if this is still an issue for you? Otherwise, I will dig more into this.

**Comment by sylviamoss** [comment]
Hello @rgl!! 
After digging into this a little bit more, I've found a solution and it will go out in the next release. If you want to use the solution before that, you can use some binaries. Here they are https://circleci.com/gh/hashicorp/packer/24727#artifacts/containers/0.
Let me know if it works for you 😄 Thanks!

**Comment by rgl** [comment]
The CI build binary worked fine! Thank you!

BTW, the packer CI is generating a `packer_windows_amd64.zip` file with a `pkg/packer_windows_amd64` file, but on windows, that file should also have the `.exe` extension; even better, the zip should just contain a file named `packer.exe` (without the `pkg` directory too).
