### ISSUE TITLE
Add `env_var_format` option to `shell` provisioner

### ISSUE THREAD

**Issue by dkrutsko** [hashicorp/packer#8283]
#### Feature Description

I noticed that [`shell`](https://www.packer.io/docs/provisioners/shell.html) is missing the `env_var_format` option. It is available for the [`shell-local`](https://www.packer.io/docs/provisioners/shell-local.html#env_var_format) provisioner.

I would like this option to be made available so that I could remove the quotes from the value portion of the environment variables (i.e. set it to `%s=%s`).

#### Use Case(s)

We have several reusable scripts which make use of environment variables. We'd like these environment variables to be set conditionally through Packer variables. Here is an example:

```bash
{
	"type": "shell",
	"expect_disconnect": false,
	"env_var_format": "%s=%s",
	"execute_command": "chmod +x {{ .Path }}; {{ .Vars }} bash -il {{ .Path }}",

	"environment_vars":
	[
		"SOME_VARIABLE=`[[ {{ user `some_variable` }} == 'compare' ]] && printf -- 'true'`",
	],

	"scripts":
	[
		"some_script.sh",
		"uses_some_variable.sh",
		"and_another_script.sh"
	]
}
```

**Comment by azr** [comment]
Hello @dkrutsko, I see that the option is available here https://www.packer.io/docs/provisioners/shell-local.html#env_var_format, is not working properly for you ?
