### ISSUE TITLE
[Hyper-V] iso_url doesn't work as before for vhdx sources.

### ISSUE THREAD

**Issue by imurvai** [hashicorp/packer#8287]
#### Overview of the Issue

We have several Packer templates organized in a hierarchical way like this:
- windows10-base-image
- common-tools
- ...
In the descendant templates we specify the iso_url as the output vhdx file of the previous stage. In version 1.2 it was working as the documentation describes, but in after upgrading to 1.4.3 Packer copies the vhdx to iso and mount as a DVD image. Obviously with the renamed iso the next stage doesn't boot. 

#### Reproduction Steps

Packer template having a vhdx file as the iso_url. Type is Hyper-V.

### Packer version

From Packer version 1.4.3 (upgraded from 1.2)

### Operating system and Environment details

Windows 10 enterprise as host and Windows 10 as guest.

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out and sorry for the late reply -- can you share a template that reproduces this behavior?

**Comment by imurvai** [comment]
Hi, in the meantime I figured out I needed to specify the iso_target_extension as vhdx.

**Comment by SwampDragons** [comment]
Sounds good; I'll close since it sounds like you found the appropriate configuration to get this working. If you have any more issues please reach out :)
