### ISSUE TITLE
Google Cloud IAP for SSH without external IP

### ISSUE THREAD

**Issue by danisla** [hashicorp/packer#8290]
#### Feature Description

Add support for SSH over IAP using the Google Cloud [IAP for TCP forwarding](https://cloud.google.com/iap/docs/using-tcp-forwarding) feature.

The `gcloud ssh` command automatically uses this as a fallback when trying to ssh into an instance without an external IP. 

#### Use Case(s)

This will let you use the SSH communicator on instances that do not have an external IP address.

Using the IAP proxy with GCP is generally more secure given that you no longer need to have a public IP address and firewall rules to grant packer access to the instance.

**Comment by rickard-von-essen** [comment]
Similar to #8242

**Comment by rickard-von-essen** [comment]
https://cloud.google.com/iap/docs/tcp-forwarding-overview

**Comment by ocervell** [comment]
This would be very useful indeed ! Trying to run `packer` from Google Cloud Build on a network that doesn't accept any external ip (org policy restriction).

**Comment by rickard-von-essen** [comment]
@ocervell you could run packer from another instance within the same network.

**Comment by ocervell** [comment]
Yes, but our goal is to integrate Packer build with a Cloud Build pipeline that builds other infrastructure with Terraform.

**Comment by zachahuy02** [comment]
@rickard-von-essen do you have any update on this? Our company disallowed the usage of public IP at the organization policies.

**Comment by rickard-von-essen** [comment]
I'm not working on this.

**Comment by rickard-von-essen** [comment]
But if the only problem is that you can't have a public IP use a instance in the same network to run Packer from.

**Comment by SwampDragons** [comment]
I'm in the process of implementing this. I've tested it from an OSX machine, but haven't tried for windows. Currently it's only enabled for SSH. I'd appreciate some testing and feedback; binaries can be found at https://circleci.com/gh/hashicorp/packer/47476#artifacts/containers/0
