### ISSUE TITLE
Ability to Update Existing Image Version in Shared Image Gallery

### ISSUE THREAD

**Issue by jzuchora87** [hashicorp/packer#8291]
#### Feature Description

Currently I have a pre-build check to see if the image version exists. If it does, I have to delete it otherwise deploying to the same image definition and version does not actually update it. You also cannot modify the replication locations either if the version already exists. The idea of deleting the version and not having one available during the build process plus replication can be a 4 hour process which isn't acceptable in a production environment. Happy to share my template if needed.

#### Use Case(s)

1. Updating existing version when monthly patches come out. 
2. Minor changes to the infrastructure that don't warrant a different version.

**Comment by ashemedai** [comment]
Maybe I misunderstand something since I am still fairly new figuring out how all of the bits of the SIG function myself, but isn't the whole purpose of the SIG that you have a base image definition and any modification, i.e. update, you have of said image is a new version?

I think your request is not a Packer thing to implement, but rather a design constraint on the side of how SIG works.

**Comment by nywilken** [comment]
Hi @jzuchora87 thanks for reaching out. @ashemedai's comment is correct; the way to update (excluding your process of deleting) is to create a new version of the image, then have only the latest version be replicated into other regions.


I don't believe there is anything for us to do on the Packer side that you are not already doing. I am going to close this issue and if things should change with how SIG works we can revisit this issue. In the meantime, you may want to reach out to the [mailing list](https://groups.google.com/forum/#!forum/packer-tool) or [community forum](https://discuss.hashicorp.com/c/packer) to see if the community has any suggestions around this workflow.
