### ISSUE TITLE
saltstack master-less  provisioner: security risk introduced with pillar copy

### ISSUE THREAD

**Issue by gaetanquentin** [hashicorp/packer#8297]
saltstack master-less provisioner may introduce a security risk, in copying sensible pillars in local image /srv/ directory.

In fact, one can  recover deleted files with specific tools, after provisioner work.

Pillars may contain sensible informations so it is not acceptable from security view.

Tips: copy files  in ramdisk disk /tmp or other instead.

Thanks.

**Comment by nywilken** [comment]
Hello folks, thanks for opening up this issue. Apologies that we've not had the chance to dive further into this issue. If you've managed to resolve your problem we encourage you to leave comment for others who may experience this issue in the future.

With that said, this is one of our community maintained plugins, which we have recently flagged as [unmaintained](https://github.com/hashicorp/packer/blob/master/README.md#unmaintained-plugins). If you are interested in contributing or taking ownership of this plugin, please reach out to us at packer@hashicorp.com.
