### ISSUE TITLE
Virtualbox-iso - Add NVMe support option to hard_drive_interface?

### ISSUE THREAD

**Issue by breisig** [hashicorp/packer#8301]
It seems Virtualbox 6.0.xx series now support the NVMe controller. But when attempting to set hard_drive_interface to "NVMe", it says only IDE, Sata, or SCSI is supported. Can we add the option to allow the NVMe controller?

==> virtualbox-iso: Error creating disk controller: VBoxManage error: Oracle VM VirtualBox Command Line Management Interface Version 6.0.2
==> virtualbox-iso: (C) 2005-2019 Oracle Corporation
==> virtualbox-iso: All rights reserved.
==> virtualbox-iso:
==> virtualbox-iso: Usage:
==> virtualbox-iso:
==> virtualbox-iso: VBoxManage storagectl       <uuid|vmname>
==> virtualbox-iso:                             --name <name>
==> virtualbox-iso:                             [--add ide|sata|scsi|floppy|sas|usb|pcie]
==> virtualbox-iso:                             [--controller LSILogic|LSILogicSAS|BusLogic|
==> virtualbox-iso:                                           IntelAHCI|PIIX3|PIIX4|ICH6|I82078|
==> virtualbox-iso:                             [             USB|NVMe]

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out!  I've opened #8305 to hopefully address this, and builds of that PR can be found here: https://circleci.com/gh/hashicorp/packer/19343#artifacts/containers/0

I haven't had a chance to test it out yet since I'd have to update virtualbox etc, but would really appreciate if you could take it for a whirl and see if it works for you.

**Comment by breisig** [comment]
Thanks, I see some final changes were done today. I guess I'll have to wait for the next build to be built to test it out.

**Comment by azr** [comment]
Hey @breisig, Yes, I added a little change; you can find the new artifacts here: https://app.circleci.com/jobs/github/hashicorp/packer/19382/artifacts

**Comment by breisig** [comment]
@azr Hmm, it's returning a 404 error on that page.

**Comment by azr** [comment]
Weird; works for me - it's probably because I have activated circle-ci's new beta ui.
Does https://circleci.com/gh/hashicorp/packer/19382/#artifacts/containers/0 work ?

**Comment by breisig** [comment]
@azr Yes, that link works for me. Let me test it out.

**Comment by breisig** [comment]
@azr Just tested it out and it works!!!

**Comment by breisig** [comment]
That might be a separate issue with Virtualbox possibly requiring the VM to bet setup in EFI mode instead of BIOS mode.

**Comment by SwampDragons** [comment]
I definitely read somewhere when researching this that it has to be in EFI mode for nvme to work. Maybe we should document this.

**Comment by breisig** [comment]
Yeah, I had modify my vboxmanage to set the VM into EFI mode using the following

```
      "vboxmanage": [
        [ "modifyvm", "{{.Name}}", "--firmware", "EFI" ],
      ]
```
I am currently working out booting an ISO in EFI mode as related to bug https://github.com/hashicorp/packer/issues/7081

**Comment by azr** [comment]
Nice, I'll document this in the nvme PR docs thanks @breisig

**Comment by azr** [comment]
I want to note that building an alpine 3.8.0 image I didn't have to start in EFI mode. 🤔
