### ISSUE TITLE
Waiting for SSH to become available. SSH handshake err: ssh: handshake failed

### ISSUE THREAD

**Issue by front5stoneybaloney** [hashicorp/packer#8312]
I am trying to build a packer image with CentOS 7 using qemu+kickstart but the process is stuck at attempting to establish an SSH connection. I read the other similar issues but haven't been able to make this work. I am using dhcp and not static.

The host is CentOS 7.7
Packer version 1.4.3
QEMU emulator version 2.0.0

I am getting the below error:

`==> qemu: Using ssh communicator to connect: 127.0.0.1
2019/11/04 00:41:16 packer: 2019/11/04 00:41:16 [INFO] Waiting for SSH, up to timeout: 20m0s
==> qemu: Waiting for SSH to become available...
2019/11/04 00:41:16 packer: 2019/11/04 00:41:16 [INFO] Attempting SSH connection to 127.0.0.1:2224...
2019/11/04 00:41:16 packer: 2019/11/04 00:41:16 [DEBUG] Config to &ssh.Config{SSHConfig:(*ssh.ClientConfig)(0xc0000ca410), Connection:(func() (net.Conn, error))(0x1176ed0), Pty:false, DisableAgentForwarding:false, HandshakeTimeout:0, UseSftp:false, KeepAliveInterval:5000000000, Timeout:0}...
2019/11/04 00:41:16 packer: 2019/11/04 00:41:16 [DEBUG] reconnecting to TCP connection for SSH
2019/11/04 00:41:16 packer: 2019/11/04 00:41:16 [DEBUG] handshaking with SSH
2019/11/04 00:41:43 packer: 2019/11/04 00:41:43 [DEBUG] SSH handshake err: ssh: handshake failed: read tcp 127.0.0.1:43916->127.0.0.1:2224: read: connection reset by peer`

I have attached the .json and .cfg files that I am using and would appreciate Any suggestions.

[centos7-base.json.txt](https://github.com/hashicorp/packer/files/3802373/centos7-base.json.txt)
[c7-kvm-ks.cfg.txt](https://github.com/hashicorp/packer/files/3802408/c7-kvm-ks.cfg.txt)

**Comment by rickard-von-essen** [comment]
And if you ssh to `root@127.0.0.1:2224` does that work? Open up the consol `headless: false` and debug the network from within the VM.

**Comment by front5stoneybaloney** [comment]
Interestingly I am not able to ssh at the moment which wasn't the case when I initially tested. I will look into this and update this thread if the issue persists afterwards.

**Comment by front5stoneybaloney** [comment]
It appears I had some things misconfigured in the kickstart file. Everything is now working properly.
