### ISSUE TITLE
Azure Builder: certificate in .pem format is required for authentication using client_cert_path 

### ISSUE THREAD

**Issue by VladimirKhvostov** [hashicorp/packer#8340]
#### Feature Description
First of all, documentation for client_cert_path should be updated. Unfortunately, client_cert_path needs to point to .pem, which is not clear from the documentation. .pfx files are not supported.

For Windows users, it would be great to have client_cert_thumbprint property, which would allow us to reference cert stored in certificate store.

#### Use Case(s)

Using packer on Windows

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out! This sounds like a good thing to implement, though I'm not sure quite when I'll be able to get it onto the roadmap. In the meantime, I'll update our docs to make it clear that we expect a pem-encoded file.
