### ISSUE TITLE
Error getting WinRM host: No ip address

### ISSUE THREAD

**Issue by JeffinBao** [hashicorp/packer#8341]
#### Overview of the Issue

When running my [win10_template.json](https://gist.github.com/JeffinBao/4a3396bc827dbf5286fa80c4a4e31db1), the VM can be successfully created, but I was stuck at ` Waiting for WinRM to become available` and the detailed error log was `Error getting WinRM host: No ip address`. It seems Packer can retrieve the MAC address, but there's no ip address with that MAC. However, when I ran `arp -a`, I can not see the MAC address as shown in Hyper-V Manager. This is wired. I am guessing whether the MAC address Packer got was wrong. I found similar issues such as #4352, #4404, #5642, #5049, but I didn't find a workaround. Any help will be appreciated.

### Packer version

From `1.4.5`

### Simplified Packer Buildfile

[packer template](https://gist.github.com/JeffinBao/4a3396bc827dbf5286fa80c4a4e31db1)

### Operating system and Environment details

HostOS: Windows10 Pro 1903
ISO used: Windows10 business edition 1903
Hypervisor: Hyper-V

### Log Fragments and crash.log files

[packerlog.txt](https://gist.github.com/JeffinBao/a5b877f0e8229da25f60ef09c7424d6c)

Let me know if more information needed.

**Comment by SwampDragons** [comment]
Are you running integration services?

**Comment by JeffinBao** [comment]
> Are you running integration services?

I checked the VM and found following integration services enabled:
1. Operating system shutdown
2. Time synchronization
3. Data exchange
4. Heartbeat
5. Backup(volume shadow copy)
6. Guest services

Am I supposed to run integration services?

**Comment by SwampDragons** [comment]
I'd just noticed in some of those issues that people said this issue occurred if they weren't running integration services, so I thought I would ask. I'm not terribly familiar with HyperV so I'll have to do some research to determine which, if any, we need in order to get the VM IP.

**Comment by JeffinBao** [comment]
Thank you for your reply. I think I found the issue. The root cause is not from Packer, but from my template. I didn't set `boot_command` properly, so the operating system installation stuck in the middle. Actually, `no ip address` error should be fine as long as you can confirm your operating system installation is in progress. After operating system installed and VM reboots, an ip will be assigned and Packer can retrieve the ip successfully.

However, since operating system installation takes time, especially sometimes we will run windows update, if `no ip address` error keeps popping up, people might think it is not able to get ip address forever. 

I wonder if we can add a `Note` in the documentation describing: `Waiting for SSH/WinRM to be available` and `Error getting SSH/WinRM host: No ip address` are fine if the VM is installing operating system. Anyway, hope our discussion can help someone who faces similar issue in the future.
