### ISSUE TITLE
Array of tags for `docker-tag` post processor. 

### ISSUE THREAD

**Issue by nqb** [hashicorp/packer#8351]
Hello,

I create a new issue, copy of ##2097 to be able to tag a Docker image with several tags.

#### Feature Description

Be able to tag a Docker image with several tags using docker-tag post-processor. Currently, it's possible to use only one tag.

#### Use Case(s)

I want to tag a Docker image with several tags.

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out! I'm not super familiar with the docker tagging mechanism but the good news is that this should be a really straightforward change to make: we need to change the Tag field on the config struct here https://github.com/hashicorp/packer/blob/master/post-processor/docker-tag/post-processor.go#L23 from a `string` to a `[]string` and then it looks like maybe just add some logic to append as many tags as provided to the string here: https://github.com/hashicorp/packer/blob/master/post-processor/docker-tag/post-processor.go#L67-L69 . I don't have a setup to test at the moment and have a few other things on my plate, but if someone wants to contribute the change and check that it works I'd happily merge.

**Comment by henry-aj-jones** [comment]
Hi, I would like to try and give this a go. I am new to Golang but have been programming for 6+ of years.

**Comment by nqb** [comment]
Hi @henry-aj-jones,

Thanks you ! I can test what you want ;-)

**Comment by henry-aj-jones** [comment]
Hi @nqb , I now have a working example locally with this example json file.

`{
    "builders": [
        {
            "type": "docker",
            "image": "iron/base",
            "commit": true
        }
    ],

  "post-processors": [
    [
      {
        "type": "docker-tag",
        "repository": "iron/base",
        "tag": ["0.7", "14.1", "spaghetti"]
      }
    ]
  ]
}`

When i now to a `docker image ls` i see: 
`REPOSITORY                                    TAG                          IMAGE ID            CREATED              SIZE
iron/base                                     0.7                          87f4f8cd2998        8 seconds ago        4.7MB
iron/base                                     14.1                         87f4f8cd2998        8 seconds ago        4.7MB
iron/base                                     spaggeti                     87f4f8cd2998        8 seconds ago        4.7MB
`
Is this how you was expecting the array of tags feature to work? I will fork and checkout the branch now and commit my changes. I still have some unit tests to write to support the change.

**Comment by nqb** [comment]
Hi @henry-aj-jones,

That sounds good, all tags shared same ID.

**Comment by nqb** [comment]
Thanks a lot @henry-aj-jones !

I will try to improve Packer's documentation to mention that several tags are supported now.
