### ISSUE TITLE
Azure builder support for Gen2 Images

### ISSUE THREAD

**Issue by Dilergore** [hashicorp/packer#8352]
#### Feature Description
Support to create Gen2 Managed Images as Managed Image output.

#### Use Case(s)
Required to be able to build Gen2 VMs which went GA during the Ignite event. Also required to be able to upload into Gen2 Azure Image Gallery Image Definition.

azure-arm: ERROR: -> Conflict : The resource with id '/subscriptions/SUBID/resourceGroups/RGNAME/providers/Microsoft.Compute/images/IMAGENAME' has a different Hypervisor generation ['V1'] than the parent gallery image Hypervisor generation ['V2'].

https://docs.microsoft.com/en-us/azure/virtual-machines/windows/generation-2
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/generation-2

**Comment by riweston** [comment]
Any movement on this, guys?

**Comment by SwampDragons** [comment]
I haven't had a chance to work on this yet, but PRs are always welcome :)

**Comment by sathishk26** [comment]
Any updates on this enhancement?

**Comment by SwampDragons** [comment]
I will update you when the work has been scheduled.

**Comment by tbugfinder** [comment]
Quite a few VM types are available as Gen2 by now. This would be really helpful.

**Comment by hbuckle** [comment]
So unless I'm missing something all you need to do is start from a Gen 2 marketplace image sku (such as `2019-datacenter-with-containers-smalldisk-g2`) and then your resulting image will also be Gen 2.

**Comment by tbugfinder** [comment]
Indeed, that worked for me. I'd expected some packer feature to "convert" Gen1 to Gen2 however if the base image is available as Gen2 (verified with latest CentOS7.7) then this works without issues. Thank You!

**Comment by edalx** [comment]
I used powershell for creating a managed image. Next script worked for me. 
```powershell
Import-Module Az
$generalizedImage = Get-AzImage -ImageName $GeneralizedImageName -ResourceGroupName $ResourceGroup

$galleryImage = New-AzGalleryImageDefinition `
   -GalleryName $GalleryImageName `
   -ResourceGroupName $GalleryResourceGroup `
   -Location $GalleryLocation `
   -Name $ImageDefinitionName `
   -OsState generalized `
   -OsType Windows `
   -HyperVGeneration "V2" `
   -Publisher $PublisherName `
   -Offer $Offer `
   -Sku $Sku
   
$region1 = @{Name=$Region1Name;ReplicaCount=1}
$region2 = @{Name=$Region2Name;ReplicaCount=1}

$targetRegions = @($region1,$region2,$region3)
$imageVersion = New-AzGalleryImageVersion `
   -GalleryImageDefinitionName $galleryImage.Name `
   -GalleryImageVersionName $version `
   -GalleryName $GalleryImageName `
   -ResourceGroupName $GalleryResourceGroup `
   -Location $GalleryLocation `
   -TargetRegion $targetRegions  `
   -Source $generalizedImage.Id.ToString() `
   -PublishingProfileEndOfLifeDate $EndOfLifeDate
```

**Comment by HOLAPH** [comment]
Solution:

Please check this line : https://github.com/danbarr/hcp-packer-azure/blob/main/hcp-packer-ubuntu20/ubuntu-focal.pkr.hcl#L24

like this `image_sku       = "20_04-lts-gen2"` like this you can choose gen2 VM
