### ISSUE TITLE
Unable to SSH by packer into Redhat image using Azure-arm modules (upgraded to 1.4.5)

### ISSUE THREAD

**Issue by vijayakrishnar** [hashicorp/packer#8358]
Hi,

Packer Version: 1.4.5

I have upgraded packer from 1.1.3 to 1.4.5, am trying to create Redhat image using azure-arm modules, it was working fine when i was using old version as soon as upgraded to latest version then it got struck at "Waiting for SSH to become available..."

    azure-arm output will be in this color.

    ==> azure-arm: Running builder ...
    ==> azure-arm: Getting tokens using client secret
    ==> azure-arm: Getting tokens using client secret
         azure-arm: Creating Azure Resource Manager (ARM) client ...
    ==> azure-arm: WARNING: Zone resiliency may not be supported in westus, checkout the docs at https://docs.microsoft.com/en-us/azure/availability-zones/
        azure-arm: temp admin user: 'packer'
        azure-arm: temp admin password: '3OJMoPwZBEHM6A3pwxxxxxxx'
        azure-arm: temp ssh key: azure-arm-pkraabbccddkz9u2j.pem
    ==> azure-arm: Using existing resource group ...
    ==> azure-arm:  -> ResourceGroupName : 'image-na'
    ==> azure-arm:  -> Location          : 'westus'
    ==> azure-arm: Pausing after run of step 'StepCreateResourceGroup'. Press enter to continue.
    ==> azure-arm: Validating deployment template ...
    ==> azure-arm:  -> ResourceGroupName : 'mage-na'
    ==> azure-arm:  -> DeploymentName    : 'pkrdp1k4mkzxxxx'
    ==> azure-arm: Pausing after run of step 'StepValidateTemplate'. Press enter to continue.
    ==> azure-arm: Deploying deployment template ...
    ==> azure-arm:  -> ResourceGroupName : 'image-na'
    ==> azure-arm:  -> DeploymentName    : 'pkrdp1k4mkxxxx'
    ==> azure-arm: Pausing after run of step 'StepDeployTemplate'. Press enter to continue.
    ==> azure-arm: Getting the VM's IP address ...
    ==> azure-arm:  -> ResourceGroupName   : 'image-na'
    ==> azure-arm:  -> PublicIPAddressName : 'pkrip1k4mkz9xxx'
    ==> azure-arm:  -> NicName             : 'pkrni1k4mkz9xxx'
    ==> azure-arm:  -> Network Connection  : 'PrivateEndpoint'
    ==> azure-arm:  -> IP Address          : '10.18.x.x'
    ==> azure-arm: Pausing after run of step 'StepGetIPAddress'. Press enter to continue.
    ==> azure-arm: Waiting for SSH to become available...

i am able to SSH into VM using ssh command manually.

[jenkins@test0 packer-azure-image]$ ssh -i azure-arm-pkrvm1k4aabb9u2j.pem packer@10.18.X.X

   USE OF THIS COMPUTING SYSTEM IS RESTRICTED TO THE CONDUCT OF COMPANY
   BUSINESS BY AUTHORIZED USERS.  ALL INFORMATION AND COMMUNICATIONS ON THIS
   SYSTEM ARE SUBJECT TO REVIEW, MONITORING, AND RECORDING AT ANY TIME
   WITHOUT NOTICE.  UNAUTHORIZED ACCESS OR USE MAY BE SUBJECT TO PROSECUTION.

Last login: Mon Nov 11 16:44:38 2019 from 10.18.196.83

   USE OF THIS COMPUTING SYSTEM IS RESTRICTED TO THE CONDUCT OF COMPANY
   BUSINESS BY AUTHORIZED USERS.  ALL INFORMATION AND COMMUNICATIONS ON THIS
   SYSTEM ARE SUBJECT TO REVIEW, MONITORING, AND RECORDING AT ANY TIME
   WITHOUT NOTICE.  UNAUTHORIZED ACCESS OR USE MAY BE SUBJECT TO PROSECUTION.

[packer@pkrvm1k4mkz9u2j ~]$

packer json file using to build image:

    {
    "variables": {
    "virtual_network_name":null,
    "virtual_network_resource_group_name":null,
    "virtual_network_subnet_name":null,
    "managed_image_resource_group_name": null,
    "Environment": null,
    "location_area": null,
    "vm_size":  null,
    "cookbook_paths": null,
    "client_id": "{{env `AZ_CLIENT_ID`}}",
    "client_secret": "{{env `AZ_CLIENT_SECRET`}}",
    "tenant_id": "{{env `AZ_TENANT_ID`}}",
    "subscription_id": "{{env `AZ_SUBSCRIPTION_ID`}}",
    "azure_image_domain": null,
    "custom_managed_image_resource_group_name": null,
    "custom_managed_image_name": null,
    "build_resource_group_name": null
    },
    "builders": [
      {
       "type": "azure-arm",
      "communicator": "ssh",
      "client_id": "{{user `client_id`}}",
      "client_secret": "{{user `client_secret`}}",
      "tenant_id": "{{user `tenant_id`}}",
      "subscription_id": "{{user `subscription_id`}}",
      "virtual_network_name":"{{user `virtual_network_name`}}",
      "virtual_network_resource_group_name":"{{user `virtual_network_resource_group_name`}}",
      "virtual_network_subnet_name":"{{user `virtual_network_subnet_name`}}",
      "custom_managed_image_resource_group_name": "{{user `custom_managed_image_resource_group_name`}}",
      "custom_managed_image_name": "{{user `custom_managed_image_name`}}",
      "build_resource_group_name":"{{user `build_resource_group_name`}}",
      "managed_image_resource_group_name": "{{user `managed_image_resource_group_name`}}",
      "managed_image_name": "{{user `azure_image_domain`}}{{user `image_publisher`}}{{user `image_offer`}}{{user `image_sku`}}_{{user `location_area`}}_Packer_{{isotime \"2006_01_02_15_04\"}}",
      "os_type": "Linux",
      "ssh_agent_auth": "true",
      "azure_tags": {
        "OS": "Linux",
        "Environment": "{{user `Environment`}}",
        "FGID": "00181",
        "Location": "{{user `location_area`}}",
        "DataClassification": "Level1"
      },
      "vm_size":  "{{user `vm_size`}}"
    }
],
    "provisioners": [
      {
        "type": "ansible-local",
        "staging_directory": "/tmp/packer-provisioner-ansible-local2",
      "playbook_dir": "ansible/roles",
      "playbook_file": "ansible/roles/test.yml"
      ]
    },
    {
     	"execute_command": "chmod +x {{ .Path }}; {{ .Vars }} sudo -E sh '{{ .Path }}'",
    	"inline": [
      		"/usr/sbin/waagent -force -deprovision+user && export HISTSIZE=0 && sync"
    	],
    	"inline_shebang": "/bin/sh -x",
    	"type": "shell"
    }
 ]
}

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out. Can you share the logs that are returned when you set the env var `PACKER_LOG=1`?

**Comment by vijayakrishnar** [comment]
I have have added above parameter and run packer build, i got below issue while ssh.

    ==> azure-arm:  -> IP Address          : '10.18.x.x'
    ==> azure-arm: Pausing after run of step 'StepGetIPAddress'. Press enter to continue.
    2019/11/11 19:29:39 packer: 2019/11/11 19:29:39 [INFO] Waiting for SSH, up to timeout: 20m0s
    ==> azure-arm: Waiting for SSH to become available...
    2019/11/11 19:29:39 packer: 2019/11/11 19:29:39 [DEBUG] Error getting SSH config: 
    SSH_AUTH_SOCK is not set
    2019/11/11 19:29:44 packer: 2019/11/11 19:29:44 [DEBUG] Error getting SSH config: 
    SSH_AUTH_SOCK is not set
    2019/11/11 19:29:49 packer: 2019/11/11 19:29:49 [DEBUG] Error getting SSH config: 
    SSH_AUTH_SOCK is not set

**Comment by SwampDragons** [comment]
Have you tried setting the env var `SSH_AUTH_SOCK`?

Looking at the code, it looks like we've added validation that requires this to be set when the ssh_agent_auth option is set. I'll try to add some documentation for this once I talk to my colleague who made the change and understand why we forced this.
