### ISSUE TITLE
SSHProxyUsername/Password are never actually used

### ISSUE THREAD

**Issue by jcfj** [hashicorp/packer#8373]
#### Overview of the Issue

The actual values `"ssh_proxy_username"` and `"ssh_proxy_password"` seem to be ignored, the values of `"ssh_bastion_username"` and `"ssh_bastion_passsword"` [are used instead](https://github.com/hashicorp/packer/blob/437983343abb8e1a93486eeb9fcbc8589c197b1e/helper/communicator/step_connect_ssh.go#L109-L110).

(I'll follow the issue template for the template's sake, but consider the rest of the information irrelevant.)

#### Reproduction Steps

`packer build` with a complete version of the file below.

### Packer version

```
Packer v1.4.4

Your version of Packer is out of date! The latest version
is 1.4.5. You can update by downloading from www.packer.io/downloads.html
```
(Irrelevant since this is present in master as shown above.)

### Simplified Packer Buildfile
```json
{
        "builders": [
        {        
            "type": "amazon-ebs",
            …    
            "communicator": "ssh",
            "ssh_username": "blubb",
            "ssh_disable_agent_forwarding": true,
            "ssh_proxy_host": "some-proxy.mycompany.com",
            "ssh_proxy_username": "bug(?) in packer, this is only checked for non-null, the bastion creds are actually used.",
            "ssh_proxy_password": "blubb - ignored"
        }
        ]
}
```
Can be easily worked around by additionally setting `"ssh_bastion_{username,password}"`, in case you're not using a bastion and a proxy at the same time…

### Log Fragments and crash.log files

```
2019-11-15T10:42:01+09:00: ==> amazon-ebs: Waiting for SSH to become available...
2019/11/15 10:42:01 packer: 2019/11/15 10:42:01 Using ssh_host value: 1.2.3.42
2019/11/15 10:42:01 packer: 2019/11/15 10:42:01 [DEBUG] TCP connection to SSH ip/port failed: socks connect tcp some-proxy.mycompany.com:1080->1.2.3.42:22: invalid username/password
…
```

**Comment by nywilken** [comment]
Hi @jcfj thanks for bubbling this up.
