### ISSUE TITLE
googlecompute-export uses a random image after it has built a custom image

### ISSUE THREAD

**Issue by saeeda** [hashicorp/packer#8376]
#### Overview of the Issue

When exporting a custom built image using `googlecompute-export`, it uses a different image to build the temporary instance in `googlecompute-export): Using image` step.

#### Reproduction Steps

Create a custom image using the `googlecompute` similar to following:
[Sample-packer-config.md](https://gist.github.com/saeeda/51f43cfd6c590b3acd03820d30d1d621)

### Packer version

From `PACKER_VERSION=1.4.4`

### Simplified Packer Buildfile
[Sample-packer-config.md](https://gist.github.com/saeeda/51f43cfd6c590b3acd03820d30d1d621)

### Operating system and Environment details

Running by Jenkins() inside a docker agent, running docker.
CentOS Linux 7
Docker version 18.09.6
Jenkins ver. 2.164.2

### Log Fragments and crash.log files

As shown in the gist above, packer uses an image for creating an image, that does not reflect the custom image being created by packer.
The image name neither exists in the google project where packer is run, nor where custom image is built.
```
==> googlecompute (googlecompute-export): Using image: random-image-name
```

**Comment by nywilken** [comment]
Hi @saeeda sorry you're running into trouble here. Can you share the logs that are returned when you set the env var PACKER_LOG=1?

**Comment by saeeda** [comment]
[gistcomment-3087502](https://gist.github.com/saeeda/51f43cfd6c590b3acd03820d30d1d621#gistcomment-3087502)

The instance image is not configurable by `googlecompute-export` [options](https://www.packer.io/docs/post-processors/googlecompute-export.html#optional).

**Comment by nywilken** [comment]
Hi @saeeda thanks for the requested info. Quickly looking at the code I see that the post-processor has a hard coded value "compute-image-tools" for the `source_image_project_id` which is used for getting the source image. Where as the the builder does not have a hard coded value. I have not yet reproduced this issue so my comment is just an observation that needs further investigation. 

Thanks again for the logs and sample build configuration. We will try to take a deeper look at the issue and report back as soon as we can. Cheers!

**Comment by saeeda** [comment]
@nywilken I'm not able to find the phrases you mentioned `source_image_project_id` `compute-image-tools` in the gist I shared.
For context, the build step uses GCP provided standard image, so it doesn't have a `project-id`; while the `googlecompute-export` tries to export the created custom image.

**Comment by nywilken** [comment]
> @nywilken I'm not able to find the phrases you mentioned `source_image_project_id` `compute-image-tools` in the gist I shared.
> For context, the build step uses GCP provided standard image, so it doesn't have a `project-id`; while the `googlecompute-export` tries to export the created custom image.

@saeeda apologies for the confusion. By code I was referring to the post-processor source code https://github.com/hashicorp/packer/blob/7c3e032fb7862770b846218fe6c8d9f5cf4b54b5/post-processor/googlecompute-export/post-processor.go#L144

The SourceImageProjectId is used in the create instance step in the getImage function: https://github.com/hashicorp/packer/blob/10ae0baa398e3ba859a806bfcf5fe184dc6e2cc5/builder/googlecompute/step_create_instance.go#L79-L91

This function is shared between the Google Compute Builder and Export Post Processor which may explain the difference in the source images being used. I'm not familiar with this code base, yet, so please keep in mind that this might not be related to your issue. I'll circle back with the other maintainers for more context.

**Comment by acasanovass** [comment]
We are using a shared VPC and to build images we use -> "omit_external_ip": true
We have a policy in place to forfeit the usage of external ip's in some of our projects because of security reasons and we are not able to use the googlecompute-export because by default is trying to add an external ip and the parameter can't be overwritten. Would be useful an option to just inherit the basic params from the custom image created at the begining.
