### ISSUE TITLE
Packer Azure Image accelerated networking enabled

### ISSUE THREAD

**Issue by rajeeshkumarkk** [hashicorp/packer#8381]
#### Feature Description: I am not sure if the latest version of Packer is capable of  building an Azure image with accelerated networking enabled. When I build Azure image and launch an Azure VM from the custom image it says "The selected image does not support  accelerated networking. 
I couldn't find a Optional builder to specify accelerated networking true in Packer template. Could you please help me with this ?

A written overview of the feature.:  Accelerated networking enables single root I/O virtualization (SR-IOV) to a VM, greatly improving its networking performance. This high-performance path bypasses the host from the datapath, reducing latency, jitter, and CPU utilization, for use with the most demanding network workloads on supported VM types. Packer needs to have a optional builder parameters to enable the accelerated networking for the image it is building so the custom image can be used with accelerated networking enabled.

#### Use Case(s) Packer built custom image can be use to create VM with accelerated networking enabled.

Any relevant use-cases that you see. Production Apps  VM needs to be with accelerated networking enabled.

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out. I agree that this would be a good feature to implement; we'll see when we can get to it.

**Comment by spikewang** [comment]
Any updates on this feature? Still no plan? We are looking to build image with Accelerated Networking enabled too...

**Comment by spikewang** [comment]
Also a quick update... This restriction for custom image is actually only for creating VM from Azure Portal. If creating VM through CLI, it works without a problem... Weird inconsistency. So in general, you don't really need to enable it from the image when building with Packer.
