### ISSUE TITLE
How can I use a preseed.cfg on a debian machine without HTTP

### ISSUE THREAD

**Issue by HoucemEddine** [hashicorp/packer#8384]
Hi, I'm trying to use a preseed.cfg to install a debian machine on vmware. I can't use the network  so I'm trying to mount it with "floppy_files" 

`"floppy_files": [
 "preseed.cfg" 
]`

on the boot_command I tried
`" preseed/file=/floppy/preseed.cfg" `
`" file=/floppy/preseed.cfg" ` 
`" file=/media/preseed.cfg" `
`" file=/mnt/preseed.cfg" `
`" file=/preseed.cfg" `
`" file=preseed.cfg" `

but none of these worked, I always get the error 
![image](https://user-images.githubusercontent.com/5792705/69064280-36a06780-0a1e-11ea-9087-57491d6e3d4c.png)

can you please help ? 
Thank you in advance

**Comment by rickard-von-essen** [comment]
Floppy isn't supposed see
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=783982

**Comment by HoucemEddine** [comment]
Thank you, that answers my question
