### ISSUE TITLE
Why is Proxmox Builder Stuck? (No response|debug_log after packer build)

### ISSUE THREAD

**Issue by apigban** [hashicorp/packer#8386]
**Proxmox Version:** 6.0-4
**Connectivity Tests:**
- ping: **ok**
- request api for ticket (curl): **ok** 
![2019-11-19_12-38](https://user-images.githubusercontent.com/2720851/69133189-ef25e400-0ace-11ea-9fea-b4b35c82e265.png)

- request api (browser): **ok**

**Build File:** 
[centos8-base (copy).json.txt](https://github.com/hashicorp/packer/files/3862819/centos8-base.copy.json.txt)

**Invocation:**
- `PACKER_LOG=1 PACKER_LOG_PATH=/home/<USER>/Documents/packer/centos8-proxmox/debug/build.log packer build -debug centos8-base.json`
- `PACKER_LOG=1 packer build -debug centos8-base.json`
- `packer build centos8-base.json`

**Expected Result:**
- Error|Debug messages on stdout

**Result** (after waiting for 20 mins. minimum):
- Blank line after cmdline 
![2019-11-19_12-44](https://user-images.githubusercontent.com/2720851/69133119-cdc4f800-0ace-11ea-8474-7d559f09e5a4.png)
- after termination, 3 empty files are created.
![2019-11-19_12-46](https://user-images.githubusercontent.com/2720851/69133271-14b2ed80-0acf-11ea-8a8d-78b96c93f363.png)

**Comment by apigban** [comment]
Here's system specs:

**Packer Host:**
**OS:** Fedora31 5.3.11-300.fc31.x86_64 #1 SMP Tue Nov 12 19:08:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
**SSD:** 117GB Available
**RAM:** 12GB Usable
**Python:** 3.7.5


**Proxmox:**
**OS:** proxmoxdxb 5.0.15-1-pve #1 SMP PVE 5.0.15-1 (Wed, 03 Jul 2019 10:51:57 +0200) x86_64 GNU/Linux
**HDD:** 324GB Available
**RAM:** 5GB Usable
**Python:** 2.7.16

**Comment by nywilken** [comment]
@apigban sorry you're running into trouble here, and thank you for the sample build configuration. I am unable to reproduce this issue. I've run into issues in the past on Centos where the packer command I was running was not the packer tool but some other command (sorry I can't find info on it at the moment). When you run  `packer version` what information do you get? Can you share the path where the Packer tool is installed `which packer`? 

If you haven't already I would recommend downloading the [latest version of Packer](https://www.packer.io/downloads.html) and try running your script against it

**Comment by nywilken** [comment]
@apigban here's a link to the other packer command I mentioned in my previous comment https://linux.die.net/man/1/packer. Running `packer help` or `packer version` should help clarify that you are using the correct packer tool. 

```bash
> packer help
Usage: packer [--version] [--help] <command> [<args>]

Available commands are:
    build       build image(s) from template
    console     creates a console for testing variable interpolation
    fix         fixes templates from old versions of packer
    inspect     see components of a template
    validate    check that a template is valid
    version     Prints the Packer version
```

**Comment by apigban** [comment]
Thanks! I just used an alias, packer.io, and now it was working.
