### ISSUE TITLE
eucalyptus emi builder. 

### ISSUE THREAD

**Issue by drpebcak** [hashicorp/packer#840]
Would it be possible to make an emi builder? Eucalyptus uses emis which are similar to amazon amis.

**Comment by michalswi** [comment]
Is there any update regarding eucalyptus emi builder?

**Comment by rickard-von-essen** [comment]
For reference: this can be done out side of eucalyptus with the qemu builder on Linux. For details see https://github.com/viglesiasce/cloud-images/blob/master/README.md

**Comment by michalswi** [comment]
the only problem which I see right now is that specific image already created in eucalyptus has some configuration and base on that I want to add/change sth and create new image, provided instruction by you creates new image base on .json files

**Comment by grv87** [comment]
Setting `custom_endpoint_ec2` doesn't help for this?
