### ISSUE TITLE
file provisioning permission denied while using terraform to provision nginx on aws ec2

### ISSUE THREAD

**Issue by manjeetsorout** [hashicorp/packer#8406]
**my .tf script is this**

resource "aws_instance" "web1" {
  ami             =   "ami-040c7ad0a93be494e"
  instance_type   =   "t2.micro"
  key_name        =   "project1key" 
  
  tags = {
    Name = "NginxWeb1"
  } 

connection {
  type        =  "ssh"
  user        =  "ec2-user"
  private_key =  file("/home/manjeet-profedge/Downloads/project1key.pem")
  host        =  self.public_ip
}

provisioner "remote-exec" {
  inline = [
     "sudo amazon-linux-extras enable nginx1.12",
     "sudo yum -y install nginx",
     "sudo systemctl start nginx"
  ]
}

provisioner "file" {
  content     =  "data.template_file.nginxconf.rendered"
  destination =  "/etc/nginx/nginx.conf"
}

provisioner "remote-exec" {
    inline    =  [
      "sudo service nginx restart"
    ]
}  
}

### **and i am getting the following error while provisiong**

aws_instance.web3 (remote-exec):   apr.x86_64 0:1.6.3-5.amzn2.0.2
aws_instance.web3 (remote-exec):   apr-util.x86_64 0:1.6.1-5.amzn2.0.2
aws_instance.web3 (remote-exec):   apr-util-bdb.x86_64 0:1.6.1-5.amzn2.0.2
aws_instance.web3 (remote-exec):   generic-logos-httpd.noarch 0:18.0.0-4.amzn2
aws_instance.web3 (remote-exec):   httpd-filesystem.noarch 0:2.4.41-1.amzn2.0.1
aws_instance.web3 (remote-exec):   httpd-tools.x86_64 0:2.4.41-1.amzn2.0.1
aws_instance.web3 (remote-exec):   mailcap.noarch 0:2.1.41-2.amzn2
aws_instance.web3 (remote-exec):   mod_http2.x86_64 0:1.15.3-2.amzn2

aws_instance.web3 (remote-exec): Complete!
aws_instance.web2 (remote-exec):   Verifying  : apr-util-1.6.1-5.a   1/9
aws_instance.web2 (remote-exec):   Verifying  : apr-util-bdb-1.6.1   2/9
aws_instance.web2 (remote-exec):   Verifying  : httpd-2.4.41-1.amz   3/9
aws_instance.web2 (remote-exec):   Verifying  : httpd-filesystem-2   4/9
aws_instance.web2 (remote-exec):   Verifying  : mod_http2-1.15.3-2   5/9
aws_instance.web2 (remote-exec):   Verifying  : apr-1.6.3-5.amzn2.   6/9
aws_instance.web2 (remote-exec):   Verifying  : mailcap-2.1.41-2.a   7/9
aws_instance.web2 (remote-exec):   Verifying  : generic-logos-http   8/9
aws_instance.web2 (remote-exec):   Verifying  : httpd-tools-2.4.41   9/9

aws_instance.web2 (remote-exec): Installed:
aws_instance.web2 (remote-exec):   httpd.x86_64 0:2.4.41-1.amzn2.0.1

aws_instance.web2 (remote-exec): Dependency Installed:
aws_instance.web3 (remote-exec): Note: Forwarding request to 'systemctl enable httpd.service'.
aws_instance.web3 (remote-exec): Created symlink from /etc/systemd/system/multi-user.target.wants/httpd.service to /usr/lib/systemd/system/httpd.service.
aws_instance.web2 (remote-exec):   apr.x86_64 0:1.6.3-5.amzn2.0.2
aws_instance.web2 (remote-exec):   apr-util.x86_64 0:1.6.1-5.amzn2.0.2
aws_instance.web2 (remote-exec):   apr-util-bdb.x86_64 0:1.6.1-5.amzn2.0.2
aws_instance.web2 (remote-exec):   generic-logos-httpd.noarch 0:18.0.0-4.amzn2
aws_instance.web2 (remote-exec):   httpd-filesystem.noarch 0:2.4.41-1.amzn2.0.1
aws_instance.web2 (remote-exec):   httpd-tools.x86_64 0:2.4.41-1.amzn2.0.1
aws_instance.web2 (remote-exec):   mailcap.noarch 0:2.1.41-2.amzn2
aws_instance.web2 (remote-exec):   mod_http2.x86_64 0:1.15.3-2.amzn2

aws_instance.web2 (remote-exec): Complete!
aws_instance.web2 (remote-exec): Note: Forwarding request to 'systemctl enable httpd.service'.
aws_instance.web2 (remote-exec): Created symlink from /etc/systemd/system/multi-user.target.wants/httpd.service to /usr/lib/systemd/system/httpd.service.
aws_instance.web3: Creation complete after 1m37s [id=i-0b3d5bc947ecb8f6d]
aws_instance.web2: Creation complete after 1m38s [id=i-01514e82db9b0316b]
data.template_file.nginxconf: Refreshing state...

Error: Upload failed: scp: /etc/nginx/nginx.conf: Permission denied

**Comment by nywilken** [comment]
Hi @manjeetsorout this looks like a Terraform specific question so I am going to close this issue, and recommend you visit the [Terraform Providers Forum](https://discuss.hashicorp.com/c/terraform-providers) for help with these types of questions. 

With that said, the Terraform file provisioner does not have the elevated privileges for writing into a protected system path like `/etc/...`. Instead you should use the file provisioner to upload the file to some user writable path `/tmp/ngnix.conf` then use the remote-exec provisioner to copy the file with sudo access - see [remote-exec](https://www.terraform.io/docs/provisioners/remote-exec.html) for an example.

**Comment by manjeetsorout** [comment]
> Hi @manjeetsorout this looks like a Terraform specific question so I am going to close this issue, and recommend you visit the [Terraform Providers Forum](https://discuss.hashicorp.com/c/terraform-providers) for help with these types of questions.
> 
> With that said, the Terraform file provisioner does not have the elevated privileges for writing into a protected system path like `/etc/...`. Instead you should use the file provisioner to upload the file to some user writable path `/tmp/ngnix.conf` then use the remote-exec provisioner to copy the file with sudo access - see [remote-exec](https://www.terraform.io/docs/provisioners/remote-exec.html) for an example.

okay i did what you said,but now i'm getting the process exited with status 1 error. can you please help further.
