### ISSUE TITLE
[builder/alicloud] Add ALICLOUD_PROFILE support for alicloud builder

### ISSUE THREAD

**Issue by yongzhang** [hashicorp/packer#8412]
Please add `ALICLOUD_PROFILE ` support for alicloud builder instead of only using access_key/secret_key environment variables, thanks.

**Comment by nywilken** [comment]
Hi @yongzhang thanks for reaching out. I labelled the issue and assigned it to the plugin code owner for further review. Cheers!

**Comment by chhaj5236** [comment]
@yongzhang Thanks for the suggestion. I'll pass your request to the corresponding team.

**Comment by yongzhang** [comment]
@chhaj5236 I tested with packer v1.5.4, but looks it doesn't work.

```
{
  "variables": {
    "alicloud_access_key": "{{env `ALICLOUD_ACCESS_KEY`}}",
    "alicloud_secret_key": "{{env `ALICLOUD_SECRET_KEY`}}",
    "alicloud_profile": "{{env `ALICLOUD_PROFILE`}}",
    "alicloud_region": "{{ env `ALICLOUD_REGION`}}"
  },

    {
      "type": "alicloud-ecs",
      "access_key": "{{user `alicloud_access_key`}}",
      "secret_key": "{{user `alicloud_secret_key`}}",
      "profile": "{{user `alicloud_profile`}}",
      "region": "{{user `alicloud_region`}}",
...
    }

```
I exported env `ALICLOUD_PROFILE`, but got error below:
```
==> alicloud-ecs: 1 error(s) occurred:
==> alicloud-ecs: 
==> alicloud-ecs: * SDK.ServerError
==> alicloud-ecs: ErrorCode: MissingParameter
==> alicloud-ecs: Recommend: https://error-center.aliyun.com/status/search?Keyword=MissingParameter&source=PopGw
==> alicloud-ecs: RequestId: D2B28DE7-9E4D-4B0D-A284-xxx
==> alicloud-ecs: Message: The input parameter "AccessKeyId" that is mandatory for processing this request is not supplied.
Build 'alicloud-ecs' errored: 1 error(s) occurred:

* SDK.ServerError
ErrorCode: MissingParameter
Recommend: https://error-center.aliyun.com/status/search?Keyword=MissingParameter&source=PopGw
RequestId: D2B28DE7-9E4D-4B0D-A284-xxx
Message: The input parameter "AccessKeyId" that is mandatory for processing this request is not supplied.

```

**Comment by yongzhang** [comment]
@chhaj5236 Can you have a look at this? Thanks.

**Comment by yongzhang** [comment]
@alexyueer Can you have a look at this? Thanks.

**Comment by alexyueer** [comment]
> @alexyueer Can you have a look at this? Thanks.

please check Alibaba Cloud  CLI config file ".aliyun/config.json" whether access_key_id exists first,
if exists, please check env ALICLOUD_PROFILE value

**Comment by alexyueer** [comment]
> @alexyueer Can you have a look at this? Thanks.

refer to https://www.alibabacloud.com/help/doc-detail/121258.htm

**Comment by yongzhang** [comment]
> > @alexyueer Can you have a look at this? Thanks.
> 
> please check Alibaba Cloud CLI config file ".aliyun/config.json" whether access_key_id exists first,
> if exists, please check env ALICLOUD_PROFILE value

I run packer as container, so there's no file `".aliyun/config.json`, but there's env `ALICLOUD_PROFILE `
