### ISSUE TITLE
Error waiting for AMI: ResourceNotReady: exceeded wait attempts

### ISSUE THREAD

**Issue by PleaseStopAsking** [hashicorp/packer#8415]
#### Overview 

As others have reported, I am seeing packer fail when it is waiting for a new AMI to become available. Packer does not seem to respect the AWS_MAX_ATTEMPTS=300 and AWS_POLL_DELAY_SECONDS=10 values I set as the timeout does not change and packer seems to always fail at roughly the 1:25hr mark.

If I remove all my provisioners except sysprep, the problem goes away as the AMI gets generated pretty quick due to it minimal size but my provisioners do a lot of install and configuration which increases the AMI size substantially.

### Packer version

Packer v1.4.5

### Simplified Packer Buildfile

```
{
    "variables": {
        "access_key": "",
        "secret_key": "",
        "storageAccountUri": "",
        "sasToken": "",
        "dscConfigFilename": "ImageCreation.ps1"
    },
    "builders": [
        {
            "type": "amazon-ebs",
            "access_key": "{{user `access_key`}}",
            "secret_key": "{{user `secret_key`}}",
            "region": "us-west-2",
            "communicator": "winrm",
            "winrm_timeout": "6h",
            "winrm_use_ssl": true,
            "winrm_insecure": true,
            "winrm_username": "PlaceHolder",
            "user_data_file": "./Scripts/Enable-WinRM.ps1",
            "source_ami_filter": {
                "filters": {
                    "name": "Windows_Server-2016-English-Full-Base-*",
                    "root-device-type": "ebs"
                },
                "owners": [
                    "amazon"
                ],
                "most_recent": true
            },
            "instance_type": "m5.large",
            "ebs_optimized": true,
            "shutdown_behavior": "terminate",
            "associate_public_ip_address": true,
            "launch_block_device_mappings": [
                {
                    "device_name": "/dev/sda1",
                    "encrypted": true,
                    "delete_on_termination": true,
                    "volume_type": "gp2",
                    "volume_size": "100",
                    "kms_key_id": ""
                },
                {
                    "device_name": "/dev/sdf",
                    "encrypted": true,
                    "delete_on_termination": true,
                    "volume_type": "gp2",
                    "volume_size": "200",
                    "kms_key_id": ""
                }
            ]
        }
    ],
    "provisioners": [
        {
            "type": "file",
            "source": "./Scripts/{{user `dscConfigFilename`}}",
            "destination": "C:\\{{user `dscConfigFilename`}}"
        },
        {
            "type": "powershell",
            "elevated_user": "PlaceHolder",
            "elevated_password": "{{.WinRMPassword}}",
            "environment_vars": [
                "StorageAccountUri={{user `storageAccountUri`}}",
                "SasToken={{user `sasToken`}}"
            ],
            "inline": [
                "& C:\\{{user `dscConfigFilename`}}",
                "Remove-Item C:\\{{user `dscConfigFilename`}} -Force"
            ]
        },
        {
            "type": "powershell",
            "inline": [
                "C:\\ProgramData\\Amazon\\EC2-Windows\\Launch\\Scripts\\SendWindowsIsReady.ps1 -Schedule",
                "C:\\ProgramData\\Amazon\\EC2-Windows\\Launch\\Scripts\\InitializeInstance.ps1 -Schedule",
                "C:\\ProgramData\\Amazon\\EC2-Windows\\Launch\\Scripts\\SysprepInstance.ps1 -NoShutdown"
            ]
        }
    ]
}
```
### Log Fragments and crash.log files

> 2019/11/26 12:28:21 ui: ask: [1;32m==> amazon-ebs: Pausing after run of step 'StepProvision'. Press enter to continue.[0m
2019/11/26 12:33:04 ui: ask: [1;32m==> amazon-ebs: Pausing after run of step 'StepCleanupTempKeys'. Press enter to continue.[0m
2019/11/26 12:33:05 ui: [1;32m==> amazon-ebs: Stopping the source instance...[0m
2019/11/26 12:33:05 ui: [0;32m    amazon-ebs: Stopping instance[0m
2019/11/26 12:33:05 ui: [1;32m==> amazon-ebs: Waiting for the instance to stop...[0m
2019/11/26 12:34:09 ui: ask: [1;32m==> amazon-ebs: Pausing after run of step 'StepStopEBSBackedInstance'. Press enter to continue.[0m
2019/11/26 12:34:55 ui: ask: [1;32m==> amazon-ebs: Pausing after run of step 'StepModifyEBSBackedInstance'. Press enter to continue.[0m
2019/11/26 12:34:56 ui: ask: [1;32m==> amazon-ebs: Pausing after run of step 'StepDeregisterAMI'. Press enter to continue.[0m
2019/11/26 12:34:57 ui: [1;32m==> amazon-ebs: Creating AMI mcs_advanced_10.7.1_2019-11-26T16-29-01Z from instance i-0b4cb3d07945510ac[0m
2019/11/26 12:34:58 ui: [0;32m    amazon-ebs: AMI: ami-0e33b5f33096e0b4f[0m
2019/11/26 12:34:58 ui: [1;32m==> amazon-ebs: Waiting for AMI to become ready...[0m
2019/11/26 13:27:46 packer: 2019/11/26 13:27:46 Error waiting for AMI: ResourceNotReady: exceeded wait attempts
2019/11/26 13:27:46 ui error: [1;31m==> amazon-ebs: Error waiting for AMI. Reason: <nil>[0m
2019/11/26 13:27:46 ui: ask: [1;32m==> amazon-ebs: Pausing before cleanup of step 'StepDeregisterAMI'. Press enter to continue.[0m

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out! Sorry to hear you're having issues with this copy. 

> Packer does not seem to respect the AWS_MAX_ATTEMPTS=300 and AWS_POLL_DELAY_SECONDS=10 values I set as the timeout does not change and packer seems to always fail at roughly the 1:25hr mark.

I'm not sure I agree that Packer isn't respecting your timeout settings. 10 seconds poll delay * 300 max attempts = 3000 seconds before timeout. 3000s/60s = roughly a 50 minute timeout, probably timing out at a touch over 50 minutes if your 300 api calls to Amazon ever have slow responses.

```
2019/11/26 12:34:58 ui: �[1;32m==> amazon-ebs: Waiting for AMI to become ready...�[0m
2019/11/26 13:27:46 packer: 2019/11/26 13:27:46 Error waiting for AMI: ResourceNotReady: exceeded wait attempts
```

Based on those two timestamps, It looks to me like the timeout is working as expected, at about 53 minutes from when we start waiting for the AMI.

I'd suggest you try changing your poll delay to 30 seconds, and see what happens. That gives your AMI 2.5 hours to finish copying, and if nothing else will tell us whether Packer is respecting the env vars.

**Comment by PleaseStopAsking** [comment]
@SwampDragons Clearly I did not fully understand how those two values were used. I will increase the values as suggested and see if the error disappears and report back.

**Comment by PleaseStopAsking** [comment]
@SwampDragons This did indeed resolve the issue. Apologies for not thinking through the logic fully. Will close
