### ISSUE TITLE
Provisioner scripts not executed intermittently

### ISSUE THREAD

**Issue by lw-wbg** [hashicorp/packer#8418]
#### Overview of the Issue

Every so often we get an issue where the provisioner scripts are skipped/not executed/ignored.

This issue can occur after several successful runs, fail several subsequent attempts, then start working again, all without a code change.

In the example below, normally the scripts will write out a lot of output and take ~7:20 minutes to complete. But as the output shows there nothing written out by the scripts and is completed in 1 second:

>  2019-11-27T11:05:55+11:00: ==> vmware-iso: Provisioning with Powershell...
>  2019-11-27T11:05:55+11:00: ==> vmware-iso: Provisioning with powershell script: ./scripts/Wait-ForWindowsUpdates.ps1
>  2019-11-27T11:05:55+11:00: ==> vmware-iso: Provisioning with powershell script: ./scripts/Edit-Windows.ps1
>  2019-11-27T11:05:55+11:00: ==> vmware-iso: Provisioning with powershell script: ./scripts/Install-WindowsVMTools.ps1
>  2019-11-27T11:05:56+11:00: ==> vmware-iso: Provisioning with powershell script: ./scripts/Install-WindowsTools.ps1
>  2019-11-27T11:05:56+11:00: ==> vmware-iso: Restarting Machine

#### Reproduction Steps

This is an intermittent issue, as such there is no way to reproduce the error on demand.

### Packer version

I have experienced this issue on 1.4.1, 1.4.3 and 1.4.5

### Simplified Packer Buildfile

See packer_template.json

### Operating system and Environment details

Host OS Name:                   Microsoft Windows Server 2016 Standard
Host OS Version:                10.0.14393 N/A Build 14393
Host OS Manufacturer:           Microsoft Corporation
Host OS Configuration:          Member Server
Host OS Build Type:             Multiprocessor Free
Host System Manufacturer:       VMware, Inc.
Host System Model:              VMware Virtual Platform
Host System Type:               x64-based PC
Host Processor(s):              8 Processor(s) Installed.
Host Total Physical Memory:     131,072 MB
Host Available Physical Memory: 121,180 MB
Host Virtual Memory: Max Size:  135,167 MB
Host Virtual Memory: Available: 124,413 MB
Host Virtual Memory: In Use:    10,754 MB
Host VM Workstation Version:    15.0.4
Guest OS:                       Windows 10, Windows Server 2016 (unsure if occurring on other guests)

### Log Fragments and crash.log files

In the example below, normally the scripts will write out a lot of output and take ~7:20 minutes to complete. But as the output shows there nothing written out by the scripts and is completed in 1 second:
>  2019-11-27T11:05:55+11:00: ==> vmware-iso: Provisioning with Powershell...
>  2019-11-27T11:05:55+11:00: ==> vmware-iso: Provisioning with powershell script: ./scripts/Wait-ForWindowsUpdates.ps1
>  2019-11-27T11:05:55+11:00: ==> vmware-iso: Provisioning with powershell script: ./scripts/Edit-Windows.ps1
>  2019-11-27T11:05:55+11:00: ==> vmware-iso: Provisioning with powershell script: ./scripts/Install-WindowsVMTools.ps1
>  2019-11-27T11:05:56+11:00: ==> vmware-iso: Provisioning with powershell script: ./scripts/Install-WindowsTools.ps1
>  2019-11-27T11:05:56+11:00: ==> vmware-iso: Restarting Machine

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out. I'm wondering if this could be caused by the same root issue as https://github.com/hashicorp/packer/issues/7039 -- try adding a small sleep before executing your first provisioner, and see if that prevents the issue.

**Comment by lw-wbg** [comment]
The issue described in #7039 is different as it isn't executing a script and it is executing the content of the chef-solo provisioner:

> amazon-ebs: Provisioning with chef-solo
>     amazon-ebs: Installing Chef...
> 2018/11/26 15:59:52 packer: 2018/11/26 15:59:52 [INFO] starting remote comm
> ...

In the issue I am seeing the content of the scripts are completely skipped

> Provisioning with Powershell...
>     vmware-iso: Provisioning with powershell script: ./scripts/Wait-ForWindowsUpdates.ps1
>     vmware-iso: Provisioning with powershell script: ./scripts/Edit-Windows.ps1
> ...

Either way in the real packer templates I use, there are one or more provisioners prior to that provisioner. For example:

```
  "provisioners": [
    {
      "type": "powershell",
      "inline": [ "Get-Content -Path \"${ENV:windir}\\Temp\\output.log\"" ]
    },
    {
      "type": "powershell",
      "environment_vars": [
        "VAR1={{ user `var1` }}",
        "VAR2={{ user `var2` }}",
        "VAR3={{ user `var2` }}"
      ],
```

**Comment by nywilken** [comment]
Hi @lw-wbg thanks again for reaching out. If you are still having issues could you upload your build configuration, stripped of any sensitive information  along with the Packer debug logs `PACKER_LOG=1 packer build build.json`, please. Looking at the logs it appears that you are using the `scripts` config option with multiple scripts in one powershell provisioner. Is that correct? 

The debug logs would show some additional output that would tell us how for the file uploads are getting before moving on to the next script. With that said, I see you are running into this issue with older versions of Packer. Do you experience the same intermittent issues when using the latest version of Packer?

**Comment by lw-wbg** [comment]
Unfortunately I have moved onto other projects now, so I am not in a position to be able to reproduce the issue now. As such I will close the issue.
