### ISSUE TITLE
Ansible-remote fails to impersonate username that is running packer build on GCE

### ISSUE THREAD

**Issue by Helcaraxan** [hashicorp/packer#8420]
### Overview of the Issue

When running the Ansible provisioner on a host provided by the Google Compute builder it appears to be impossible to run task commands with `become` and `become_user` if the username in question (created via Ansible) is identical to the user that is running the `packer build`. Instead the requested command is executed by the user specified via `ssh_username` in the build file.

I have attempted to reproduce this with only Ansible, using manual machine provisioning combined with Ansible's own remote SSH capabilities but this did not result in the same behaviour.

### Reproduction Steps

My test setup can be found in [this repo](https://github.com/Helcaraxan/repro-ansible-username-conflict). This repro's `run.sh` script is intended to be run from a GCE instance provisioned with a GCE service-account playing the role of the controller.

Outside of this minimal repro I have observed this issue in a more involved setup where the command that is being run is actually `docker-credential-gcr configure-docker`.

In this other setup there is no unreachable error due to lacking permissions. _**However**_ the resulting `$HOME/.docker/config.json` ends up in the wrong directory.

Examples:
- User running `packer build`: `controller`
  Configured `ssh_username` user: `ansible`
  User created by Ansible on target: `controller`
  -> File ends up as `/home/ansible/.docker/config.json` instead of `/home/controller/.docker/config.json`.

- User running `packer build`: `controller`
  Configures `ssh_username` user: `root`
  User created by Ansible on target: `controller`
  -> File ends up as `/root/.docker/config.json` instead of `/home/controller/.docker/config.json`.

### Packer version

1.3.5, 1.4.3 and 1.4.5

### Simplified Packer Buildfile

Copy-pasted from the [repo linked above](https://github.com/Helcaraxan/repro-ansible-username-conflict).

```json
{
    "builders": [
        {
            "type": "googlecompute",
            "project_id": "{{user `project_id`}}",
            "zone": "{{user `zone`}}",
            "instance_name": "packer-{{uuid}}",
            "machine_type": "n1-standard-1",
            "preemptible": true,
            "source_image_family": "ubuntu-1804-lts",
            "communicator": "ssh",
            "ssh_username": "{{user `packer_user`}}"
        }
    ],
    "provisioners": [
        {
            "type": "ansible",
            "ansible_env_vars": [
                "ANSIBLE_DIFF_ALWAYS=1",
                "ANSIBLE_FORCE_COLOR=1"
            ],
            "extra_arguments": [
                "-vvv",
                "--extra-vars",
                "target_user={{user `target_user`}}"
            ],
            "playbook_file": "ansible/playbook.yaml"
        }
    ]
}
```

#### Packer / Ansible

Tested and reproduced with all combinations between Packer versions 1.3.5, 1.4.3 and 1.4.5 and Ansible versions 2.9.0, 2.9.1 and latest 2.10.0.dev0 (ansible/ansible@6ae01d4fbdcf713b1bdd420f586db79e44debb61). 

#### OS

Identical for both the controller and the target: Ubuntu 18.04 LTS - GCE instance, with only the minimal software installs required to run the repro scenario.

#### Cloud

I have not attempted to reproduce this with builders other than the Google Compute one.

### Log Fragments and crash.log files

Logs of both a failed and a successful build can be found [here](https://gist.github.com/Helcaraxan/d9aa69b0c3bd4a60d74be35aba91e142).

**Comment by SwampDragons** [comment]
Hi, sorry for the incredibly slow response on this. This is the documented behavior: https://packer.io/docs/provisioners/ansible.html#user

from that page: 

> Note: Any remote_user defined in tasks will be ignored. Packer will always connect with the user given in the json config for this provisioner.

I'm going to treat this as a feature request to make Packer respect the remote_user definition, rather than a bug report. The Ansible provisioner is normally community-supported, but I've been putting some effort into cleaning it up recently so I'll try to take a look and see if this is something we can fix.

**Comment by SwampDragons** [comment]
potentially related: https://github.com/ansible/ansible/issues/31268

**Comment by SwampDragons** [comment]
I don't think I'm going to have time to work on this for a while. Untargeting. If a community member wants to take a look, I'd appreciate the assist.
