### ISSUE TITLE
Subscription not found using Azure system-managed identity

### ISSUE THREAD

**Issue by thefueley** [hashicorp/packer#8421]
#### Overview of the Issue
Azure System-Managed Identity doesn't authenticate when using build command. It just complains that it cannot find the subscription ID.
A paragraph or two about the issue you're experiencing.

#### Reproduction Steps

Steps to reproduce this issue
Create System-Managed Identity on a VM in Azure.
Give Contributor access to this VM at subscription level using IAM
Create a template with no mention of client_id, client_secret, or subscription_id.

### Packer version

From `packer version`
1.4.5
### Simplified Packer Buildfile
{
  "variables": {
    "ssh_user": "{{env `ARM_SSH_USER`}}",
    "ssh_pass": "{{env `ARM_SSH_PASS`}}"
  },
  "builders": [{
    "type": "azure-arm",

    "managed_image_resource_group_name": "PACKER-RG",
    "managed_image_name": "Packer-Managed-Image",

    "ssh_username": "{{user `ssh_user`}}",
    "ssh_password": "{{user `ssh_pass`}}",

    "os_type": "Linux",
    "image_publisher": "OpenLogic",
    "image_offer": "CentOS",
    "image_sku": "7.3",
    "image_version": "latest",
    "ssh_pty": "true",

    "location": "usgovvirginia",
    "vm_size": "Standard_DS2_v2"
  }],
  "provisioners": [{
    "execute_command": "echo '{{user `ssh_pass`}}' | {{ .Vars }} sudo -S -E sh '{{ .Path }}'",
    "inline": [
      "yum update -y",
      "/usr/sbin/waagent -force -deprovision+user && export HISTSIZE=0 && sync"
    ],
    "inline_shebang": "/bin/sh -x",
    "type": "shell",
    "skip_clean": true
  }]
}

### Operating system and Environment details
RedHat 7.7
OS, Architecture, and any other information you can provide about the
environment.

### Log Fragments and crash.log files

$ ./packer build centos.json
azure-arm output will be in this color.

==> azure-arm: Running builder ...
Build 'azure-arm' errored: Unexpected response from Get Subscription: subscriptions.Client#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="SubscriptionNotFound" Message="The subscription 'HIDDEN' could not be found."

==> Some builds didn't complete successfully and had errors:
--> azure-arm: Unexpected response from Get Subscription: subscriptions.Client#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="SubscriptionNotFound" Message="The subscription 'HIDDEN' could not be found."

==> Builds finished but no artifacts were created.
Set the env var `PACKER_LOG=1` for maximum log detail.

**Comment by sylviamoss** [comment]
Hello there! I think this might had been fixed in https://github.com/hashicorp/packer/pull/8685, which will be part of the next release.

**Comment by sylviamoss** [comment]
I'm closing this one and we can open it again in case the issue remains in the next released version.
