### ISSUE TITLE
Occasional Infinite While Loop Sysprepping Windows Images

### ISSUE THREAD

**Issue by cbrax** [hashicorp/packer#8428]
Hey Hashicorp!

I'm building Windows Server 2016 Datacenter images using Packer 1.4.4 in an Azure DevOps build pipeline. The majority of the time builds work with no issues and the images are sysprepped per the example provided in your repo: https://github.com/hashicorp/packer/blob/master/examples/azure/windows.json

Recently I've been seeing around 20% of builds get stuck in an infinite loop during sysprep (I'm using the code in the Windows example above to sysprep). The Image State being returned by the query is IMAGE_STATE_SPECIALIZE_RESEAL_TO_OOBE, which appears to require a reboot. It never transitions out of this state, so it just gets stuck.

The code itself is waiting for IMAGE_STATE_GENERALIZE_RESEAL_TO_OOBE, and I'm assuming there's no transition from the SPECIALIZE state to the GENERALIZE state, meaning images get stuck in an infinite while loop.

I know this isn't a Packer-specific issue but am hoping for some advice given it's the example provided in the repo for building Windows images. The quick fix would seem to be to modify the line to be:

`"while($true) { $imageState = Get-ItemProperty HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Setup\\State | Select ImageState; Write-Output $imageState.ImageState; if($imageState.ImageState -ne 'IMAGE_STATE_GENERALIZE_RESEAL_TO_OOBE' -and $imageState.ImageState -ne 'IMAGE_STATE_SPECIALIZE_RESEAL_TO_OOBE') { Start-Sleep -s 10 } else { break } }"`

However, I'm not sure if this change will result in a functional image as documentation about what the difference is between these two states is very hard to find.

Is there any guidance you can offer?

**Comment by nhudacin** [comment]
+Following

Also seeing this recently with 2019-Datacenter builds.

**Comment by vinoddevopscloud99** [comment]
I  am also getting  same related issue,  build get lopped and timed out. its showing image state is undeployable.  I am using the windows 2012R2 Azure.

my sysprep code:

 "echo '>>> Waiting for GA to start ...'",
        "while ((Get-Service RdAgent).Status -ne 'Running') { Start-Sleep -s 5 }",
        "while ((Get-Service WindowsAzureTelemetryService).Status -ne 'Running') { Start-Sleep -s 5 }",
        "while ((Get-Service WindowsAzureGuestAgent).Status -ne 'Running') { Start-Sleep -s 5 }",

        "if( Test-Path $Env:SystemRoot\\windows\\system32\\Sysprep\\unattend.xml ){ rm $Env:SystemRoot\\windows\\system32\\Sysprep\\unattend.xml -Force}",
        "& $env:SystemRoot\\System32\\Sysprep\\Sysprep.exe /oobe /generalize /quiet /quit /mode:vm",
        "while($true) { $imageState = Get-ItemProperty HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Setup\\State | Select ImageState; Write-Output $imageState.ImageState; if($imageState.ImageState -ne 'IMAGE_STATE_GENERALIZE_RESEAL_TO_OOBE') { Start-Sleep -s 10 } else { break } }",

Please need help .

**Comment by ffalorjr** [comment]
I am also seeing this, but my image state is: 
IMAGE_STATE_COMPLETE

Using latest 2019 datacenter image.

**Comment by SwampDragons** [comment]
@paulmey I'm no powershell/sysprep expert. Do you have any advice on this?

**Comment by paulmey** [comment]
Asking around, I personally haven't seen this before, then again, I don't build many Windows images...

**Comment by SwampDragons** [comment]
Thanks! any insight on whether the command suggested in the original comment would be appropriate?

**Comment by ffalorjr** [comment]
I fixed my issue.

There should be a log file located here: %WINDIR%\System32\Sysprep\Panther

Open it up and read what is going on. In my case the latest 2019 marketplace image had a restart pending due to updates and sysprep wanted a restart to happen first.

Adding a windows-restart provisoner before sysprep has fixed my issue.
