### ISSUE TITLE
Support tilde ~ in validation_key_path for Chef provisioner

### ISSUE THREAD

**Issue by scalp42** [hashicorp/packer#8441]
Hi folks,

Support for `~` was added to `ssh_private_key_file` which is great but it'd be even better if `validation_key_path` in the Chef provisioner could support it as well.

It doesn't unfortunately support `env` so we can't make sure of the `HOME` variable for example.

Cheers!

**Comment by sylviamoss** [comment]
Hi @scalp42, thanks for opening an issue! 

I think it is a good idea. This is a community-supported plugin and, If you're comfortable, feel free to open a pull request with the solution and ask us any question about it. 😄 

You may want to use the method `ExpandUser` [here](https://github.com/hashicorp/packer/blob/master/packer/config_file.go#L90), which I believe does the check and conversion for `~`
