### ISSUE TITLE
Packer Qemu builder does not support newest network devices

### ISSUE THREAD

**Issue by gvcgael** [hashicorp/packer#8443]
#### Overview of the Issue
https://www.packer.io/docs/builders/qemu.html#net_device

net_device supports a list which is not the same as `/usr/libexec/qemu-kvm` in version 2.12.0 : 

```
Network devices:
name "e1000", bus PCI, desc "Intel Gigabit Ethernet"
name "e1000-82540em", bus PCI, desc "Intel Gigabit Ethernet"
name "e1000e", bus PCI, desc "Intel 82574L GbE Controller"
name "rtl8139", bus PCI
name "virtio-net-device", bus virtio-bus
name "virtio-net-pci", bus PCI, alias "virtio-net"
```

its missing `virtio-net-device`. 

#### Reproduction Steps

To get the list of available devices : 
```
/usr/libexec/qemu-kvm --device help
```

### Packer version

Packer 1.4.3

**Comment by SwampDragons** [comment]
Hi, @gvcgael, Thanks for opening an issue! The QEMU builder is one of our community-supported builders, which means that the HashiCorp maintainers don't spend much engineering time on it; this means that the best way to see your suggestion make it into Packer is to open a PR. We'll gladly give support and pointers if you're interested in taking a shot at it.

**Comment by soul4soul** [comment]
Related to #7437
