### ISSUE TITLE
SSH handshake err: ssh: handshake failed: EOF macOS VM 10.9 and 10.10

### ISSUE THREAD

**Issue by reysmerwvr** [hashicorp/packer#8450]
I'm trying to create a macOS VM 10.9 and I'm getting this error when Packer tries to connect from the host to the VM machine over ssh. I tried with other macOS versions like 10.12, 10.13, 10.14 and works properly but when I try with 10.9 and 10.10 I'm getting this? 

I'm using parallels pvm builder.

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out. Please provide the full details requested in the issue template. without that information, it is extremely difficult for us to reproduce and solve bugs. Thanks!

**Comment by reysmerwvr** [comment]
Hi, @SwampDragons thanks for the answer.
Packer Version: 1.4.5
Using a macOS base 10.9 as a source path
Builder: parallels-pvm

example.json
{
  "variables": {
    "source_path": "",
    "ssh_username": "",
    "ssh_password": "",
    "ssh_timeout": "",
    "vm_name": "",
    "output_directory": "",
    "memsize": "",
    "cpus": ""
  },
  "builders": [
    {
      "type": "parallels-pvm",
      "source_path": "{{user `source_path`}}",
      "parallels_tools_flavor": "mac",
      "communicator": "ssh",
      "ssh_username": "{{user `ssh_username`}}",
      "ssh_password": "{{user `ssh_password`}}",
      "ssh_timeout": "{{user `ssh_timeout`}}",
      "vm_name": "{{user `vm_name`}}",
      "output_directory": "{{user `output_directory`}}",
      "prlctl": [
        ["set", "{{.Name}}", "--memsize", "{{user `memsize`}}"],
        ["set", "{{.Name}}", "--cpus", "{{user `cpus`}}"],
        ["set", "{{.Name}}", "--device-add", "net", "--type", "bridged"],
        ["set", "{{.Name}}", "--device-set", "net1", "--mac", "auto"],
        ["set", "{{.Name}}", "--device-set", "net1", "--dhcp", "yes"]
      ],
      "skip_compaction": true,
      "shutdown_command": "echo '{{user `ssh_password`}}' | sudo -S shutdown -h now"
    }
  ],
  "provisioners": [
    {
      "type": "shell",
      "execute_command": "echo '{{user `ssh_password`}}' | {{.Vars}} sudo -S -E bash '{{.Path}}'",
      "scripts": ["scripts/apps.sh"]
    }
  ]
}

**Comment by SwampDragons** [comment]
and debug logs?

**Comment by reysmerwvr** [comment]
@SwampDragons it says: fatal: matching cipher is not supported: aes128-gcm@openssh.com [preauth]

Is there a way to change the cipher in the ssh communicator?

**Comment by SwampDragons** [comment]
You can find a list of supported ciphers here: https://www.packer.io/docs/communicators/ssh.html#ssh-communicator-details

**Comment by SwampDragons** [comment]
Actually, it looks like the docs may be incorrect: see issue #7723. 

I'll try to take a look at this when I can, but it likely won't be until after the holidays.

**Comment by SwampDragons** [comment]
PR #9453 allows you to set specific ciphers for the communicator, which will hopefully solve the underlying issue. 

I do notice that the cipher mentioned is "aes128-gcm@openssh.com", which should have always been in the list of supported ciphers on Packer's end. I am not sure if MacOS only checks the first cipher sent, or what, but you may have to tinker to get this working still.
