### ISSUE TITLE
1.4.5 'stdout' copy error: stream closed

### ISSUE THREAD

**Issue by JoshuaEdwards1991** [hashicorp/packer#8451]
#### Overview of the Issue
I am using the s5cmd which is a Go app that allows multithreaded s3 cp's.
When using this on a large amount of data it fails.
Please see the below errors.

#### Reproduction Steps
When copying a large amount of data to the builder instance, 1000gb, using s5cmd, it throws the below errors and fails. This works with a smaller copy of 600gb.
This command is run in an ansible role using bash

### Packer version
From 1.4.5

### Operating system and Environment details
Ubuntu CodeBuild Ruby 2.6

### Log Fragments and crash.log files
```
  2019/12/05 14:45:38 [INFO] 297728508 bytes written for 'stdout' 
2019/12/05 14:45:38 [INFO] (telemetry) ending ansible-local 
2019/12/05 14:45:38 Error in Ui.Message RPC call: connection is shut down 
2019/12/05 14:45:38 [ERR] yamux: Failed to write header: write unix @->/tmp/packer-plugin198503284: write: broken pipe 
2019/12/05 14:45:38 [ERR] 'stdout' copy error: stream closed 
2019/12/05 14:45:38 /codebuild/output/src579423972/src/packer/packer: plugin process exited 
==> amazon-ebs: Provisioning step had errors: Running the cleanup provisioner, if present... 
```

After increasing build memory using a larger c5.4xlarge instance
```
2019/12/05 15:15:53 /codebuild/output/src275888070/src/packer/packer: plugin process exited 
2019/12/05 15:15:53 [INFO] 297728472 bytes written for 'stdout' 
2019/12/05 15:15:53 [ERR] 'stdout' copy error: stream closed 
2019/12/05 15:15:53 [INFO] (telemetry) ending ansible-local 
2019/12/05 15:15:53 Error in Ui.Message RPC call: connection is shut down 
```

**Comment by nywilken** [comment]
Hi @JoshuaEdwards1991 thanks for reaching out. Please provided a sample build configuration for reproducing the issue.

**Comment by nywilken** [comment]
Hi @JoshuaEdwards1991 just wanted to circle back here. Any chance you can share a simplified script to reproduce the issue? 

I see that you're on v1.4.5. There were some changes to Packer's default logger that might provide some additional information. Try updating to the most recent version of Packer and let us know if you are still having issues. Thanks!

**Comment by nywilken** [comment]
Hi @JoshuaEdwards1991 I'm going to close out this issue since there have been no updates. If you are still running into issues with uploading large files and suspect that this may be a bug in Packer please use the [Bug Report Template](https://github.com/hashicorp/packer/issues/new?labels=bug&template=bug_report.md) to create a new issue with a simplified build configuration and any external scripts to repro the issue so that we can better assist. Cheers.
