### ISSUE TITLE
[builder/amazon] enhancement: bypass aws.iam.getInstanceProfile

### ISSUE THREAD

**Issue by sbaxter** [hashicorp/packer#8452]
At present, when given an `iam_instance_profile` value, `packer` [queries the profile](https://github.com/hashicorp/packer/blob/28c720bd3acb8fd5071c71d094aa15b5803c8ac2/builder/amazon/common/step_iam_instance_profile.go#L32-L47) via the IAM api. This is problematic when running packer from within a protected subnet with no public internet access: the IAM API is run over the public internet and does not currently offer VPC endpoints.

I'll admit, this is an edge case, but it would be a "nice-to-have" option to force packer to explicitly attempt to use `Name=<iam_instance_profile>` instead of performing the validation. My current use-case requires access to S3 during provisioning, but I can workaround by pulling files from S3 and provision them directly using `file`.

**Comment by SwampDragons** [comment]
Thanks, I can see the value in a `skip_profile_validation` option. This should be a fairly straightforward task, since all you'd need to do is wrap the linked code in a check. I'm currently busy with some internal work but if you or another community member would like to try to implement it, I'd be happy to give some suggestions.

**Comment by sylviamoss** [comment]
Hello @sbaxter!
@odedpriva implemented a solution for this that lets you skip the iam profile validation adding  `"skip_profile_validation" : "true"` to your builder configuration. 🎉 
Here are some binaries https://circleci.com/gh/hashicorp/packer/23915#artifacts/containers/0 you can use. Could you please tell us if it works for you? 😄 
Thank you!
