### ISSUE TITLE
How can I bake user_data_file into EC2 Instances from AMI?

### ISSUE THREAD

**Issue by j-i-m-s-t-e-r** [hashicorp/packer#8454]
Hi,

I need EC2 instances that are spun up by Terraform from a Windows Server 2016 Packer AMI to execute a script in user_data (this will be Powershell to rename and join the computer to our AD etc.)

I've see @rickard-von-essen answer something similar for *nix:
_"Just upload the script (when provisioning in Packer) to /var/lib/cloud/scripts/per-boot/ or per-instance and make it executable. It will the be executed by cloud-init on each boot or once per instance. See the cloud-init docs for more info. "_

..But this is windows - Can I say,  bake a .ps1 script somewhere in the Packer AMI and hammer this into a user data field somewhere?  The AMI will be also used by Autoscaling in AWS so that, as far as I can see, means the trigger to do the AD join stuff has to be in user_data.

Any advice welcome.  Again, goal is to set a script into user_data for first-time new EC2 instance action, to rename and register instances into AD.

**Comment by SwampDragons** [comment]
Hi again! My usual caveat here: the github issue tracker is really for bugs and feature requests, and general "how do people do this" questions tend to get higher quality answers via other community forums. 

That said, I'll do my best. Packer's user_data_file will only be used when Packer itself is causing the instance launch. If you want the script to be launched every time a new instance is created after that, you probably want to just upload the script and then use the task scheduler to call it on launch. I don't think there's an Amazon API tool to set something like this up, and I know there isn't a way to do it inside the Packer builder directly. 

Alternatively, I'd upload a script to your image using Packer, and add a call to that pre-baked script into the user_data field on the aws_instance data source in Terraform. I'm not sure if that would work with autoscaling or not; I've not had to deal much with autoscaling.

**Comment by j-i-m-s-t-e-r** [comment]
Appreciate your reply Megan.... Still thinking this through, we'll crack
it.  Once again, Windows is going against the grain.

**Comment by DevOpsEtc** [comment]
@j-i-m-s-t-e-r @SwampDragons

Disclaimer: I've only baked AMIs for Linux OSs, but leveraging user-data via cloud-init is conceptually similar in Windows. Also, to get new AMI ID into ASG I don't use TF, but rather CloudFormation kicked off by a Packer Local Shell Post Processor that creates new ASG LaunchConfig, then updates the ASG to use new LaunchConfig.

Looks like Windows uses EC2Config Tasks to execute specified user data. These links look promising...

Configuring a Windows Instance Using the EC2Config Service:
https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/ec2config-service.html

Running Commands on Your Windows Instance at Launch:
https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/ec2-windows-user-data.html

AWS EC2 userdata on Windows:
https://david-obrien.net/2016/04/aws-ec2-user_data-on-windows/

AWS Windows EC2 Deploy + Domain Join:
https://www.reddit.com/r/aws/comments/b68wkz/aws_windows_ec2_deploy_domain_join/

**Comment by SwampDragons** [comment]
Thanks for those links -- I'm closing this issue since this isn't something actionable on Packer's end. Hope you found a way of getting what you need!
