### ISSUE TITLE
Is there a way to set a specific cipher in ssh communicator? 

### ISSUE THREAD

**Issue by reysmerwvr** [hashicorp/packer#8460]
Got one of the following errors ? See if the related guides can help.

* `Waiting for WinRM to become available` ?

  - See our basic WinRm Packer guide: https://www.packer.io/guides/automatic-operating-system-installs/autounattend_windows.html

* `Waiting for SSH to become available` ?

  - See our basic SSH Packer guide: https://www.packer.io/guides/automatic-operating-system-installs/preseed_ubuntu.html

Issues on GitHub are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here if you have a question.

- Packer Guides: https://www.packer.io/guides/index.html
- Discussion List: https://groups.google.com/group/packer-tool
- Any other questions can be sent to the packer section of the HashiCorp
  forum: https://discuss.hashicorp.com/c/packer
- Packer community links: https://www.packer.io/community.html

**Comment by SwampDragons** [comment]
Currently there is no way to override the cipher, but we do have an issue open already requesting this change: #7723 

I'm going to close this issue so that we can track the request in a single place, so please follow that issue for further updates :)
