### ISSUE TITLE
Crash while provisioning with Powershell script. Error uploading ps script containing env vars: unexpected EOF

### ISSUE THREAD

**Issue by matthewwerf** [hashicorp/packer#8470]
#### Overview of the Issue
Packer crashes during a powershell provisioning step. 

#### Reproduction Steps

Run packer build. The build fails while uploading a powershell script with env vars due to an unexpected EOF. This uses the azure-arm builder. It was not an issue previously when I was using the Hyper-V builder. I apologize in advance for the atrocity that is windows-build-tools installation output.

### Packer version

Packer v1.4.3

### Simplified Packer Buildfile
[Github detailed
format](https://gist.github.com/matthewwerf/387e721dda677125837aad9526b711b7)

### Operating system and Environment details

Windows 1903 OS Build 18362.476

### Log Fragments and crash.log files
[Github detailed format](https://gist.github.com/matthewwerf/cd3217a588237e2b73b21965496a32e3)

**Comment by SwampDragons** [comment]
Hi! I think the bug causing this crash was solved in v1.5.0, in this PR: https://github.com/hashicorp/packer/pull/8369

If you update to v1.5.1 this shouldn't happen anymore :)

**Comment by matthewwerf** [comment]
Confirmed go panic issue is resolved in 1.5.1, much thanks
