### ISSUE TITLE
Version returned by packer executable different from zip file name

### ISSUE THREAD

**Issue by jmwood040** [hashicorp/packer#8477]
#### Overview of the Issue
I recently downloaded version 1.4.5 of packer for linux amd64.

After downloading, I unzipped the executable and ran 'packer --version'
and found a version of 1.4.4.

Here is the URL:  https://releases.hashicorp.com/packer/1.4.5/packer_1.4.5_linux_amd64.zip

A paragraph or two about the issue you're experiencing.

#### Reproduction Steps

See above

### Packer version
1.4.5

**Comment by nywilken** [comment]
hi @jmwood040 please check that you are not calling a previous version of the Packer binary which may be in your $PATH. Downloading the latest release of Packer via the provided URL yields the correct version.

```bash
vagrant@vagrant:~$ packer
-bash: packer: command not found
vagrant@vagrant:~$ ./packer
-bash: ./packer: No such file or directory
vagrant@vagrant:~$ curl -L -O https://releases.hashicorp.com/packer/1.4.5/packer_1.4.5_linux_amd64.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 43.3M  100 43.3M    0     0  71.8M      0 --:--:-- --:--:-- --:--:-- 71.7M
vagrant@vagrant:~$ unzip packer_1.4.5_linux_amd64.zip 
Archive:  packer_1.4.5_linux_amd64.zip
  inflating: packer                  
vagrant@vagrant:~$ ./packer --version
1.4.5
```

I'm going to close this issue as the unzipped binary is reporting the correct version. But if you find yourself running into issues please leave a comment and I will gladly reopen the issue.
