### ISSUE TITLE
Github Releases page doesn't have latest release tagged correctly

### ISSUE THREAD

**Issue by sethbacon** [hashicorp/packer#8482]
#### Overview of the Issue

I regularly pull the latest packer release in my CI/CI pipeline by using the following logic:
PACK_VER=$(curl -s https://api.github.com/repos/hashicorp/packer/releases/latest | grep '"name":'| cut -d ':' -f2| cut -d '"' -f2)
curl -o packer.zip https://releases.hashicorp.com/packer/${PACK_VER}/packer_${PACK_VER}_linux_amd64.zip && unzip packer.zip

However, when going to the Releases page on github, it looks like the latest release is still tagged as 1.4.4.

Any way this can be updated?

#### Reproduction Steps

curl -s https://api.github.com/repos/hashicorp/packer/releases/latest | grep '"name":'| cut -d ':' -f2| cut -d '"' -f2

**Comment by SwampDragons** [comment]
Thanks, I'll try to fix this now.

**Comment by SwampDragons** [comment]
I've tagged the release.

**Comment by sethbacon** [comment]
Awesome!!! Thanks!
