### ISSUE TITLE
Set retention period for image versions in SIG

### ISSUE THREAD

**Issue by ata18** [hashicorp/packer#8492]
#### Overview of the Issue
GalleryImageVersionPublishingProfile definition in Azure SDK allows to specify endOfLifeDate for an image version. 
[GalleryImageVersionsRestAPI](https://docs.microsoft.com/en-us/rest/api/compute/galleryimageversions/createorupdate#galleryimageversionpublishingprofile)
[AzureSDKCode](https://github.com/Azure/azure-sdk-for-go/blob/master/services/compute/mgmt/2019-07-01/compute/models.go#L5237)

In packer, [here](https://github.com/hashicorp/packer/blob/1eef03c36b7b670e8f63b58fd9a26ee8f8d3156d/builder/azure/arm/step_publish_to_shared_image_gallery.go#L38) is where a new gallery image version is created and published to sig. In this step, when specifying the GalleryImageVersionPublishingProfile, endOfLifeDate is not populated. This needs to be fixed in order to be able to set endOfLifeDate for image versions in SIG.

```
PublishingProfile: &compute.GalleryImageVersionPublishingProfile
{
  Source: &compute.GalleryArtifactSource
  { 
    ManagedImage: &compute.ManagedArtifact
    { 
      ID: &mdiID,
    }, 
  },
  TargetRegions: &replicationRegions,
}
```

### Packer version

From `packer version`
1.4.3

**Comment by ata18** [comment]
I will work on this.

**Comment by ata18** [comment]
Looks like packer still uses an older version of Azure SDK.  Is there a plan to move to newer version of AzureSDK?

Will it be okay to move to a [newer version of SDK](github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-03-01/compute) for this [file](https://github.com/hashicorp/packer/blob/master/builder/azure/arm/step_publish_to_shared_image_gallery.go) alone?

**Comment by SwampDragons** [comment]
Go ahead and update the SDK for everything.

**Comment by ata18** [comment]
@SwampDragons I suspect that there could be some breaking changes with moving to a newer SDK version. I am not familiar with this code base. I will give it a try.

**Comment by SwampDragons** [comment]
I don't want to have to maintain several separate versions of the SDK. If there are breaking changes, the compiler will catch them.

**Comment by ata18** [comment]
The old sdk itself has the support for setting end-of-life-date for image versions in sig. I made the required changes on the packer side and tested by doing a `packer build`. It successfully sets the end-of -life date on the image version. Will open a PR for this.
