### ISSUE TITLE
[post-processor/vsphere-template] ServerFaultCode: Permission to perform this operation was denied.

### ISSUE THREAD

**Issue by TJM** [hashicorp/packer#8505]
#### Overview of the Issue

When using the vsphere-template post-processor to convert a newly uploaded (with vsphere post-processor) image to a template, I get the error (see output below), with no explanation as to what its actually doing. Using the same username and password, I can convert the VM to a Template in the vSphere UI without a problem. 

NOTE: We are using a "service" account with very limited access, but as noted above, we do have the ability to upload and mark as template.

#### Reproduction Steps

Build a VM locally in vmware workstation, uploading with vsphere post-processor, followed by a vsphere-template post-processor

### Packer version
1.5.0

From `packer version`

### Simplified Packer Buildfile

```
    "post-processors": [
        [
            {
                "type": "vsphere",
                "name": "upload-den3",
                "insecure": true,
                "host": "{{ user `vcenter_den3` }}",
                "datacenter": "{{ user `datacenter_den3` }}",
                "cluster": "{{ user `cluster_den3` }}",
                "datastore": "{{ user `datastore_den3` }}",
                "vm_network": "{{ user `portgroup_den3` }}",
                "username": "{{ user `vcenter_username` }}",
                "password": "{{ user `vcenter_password` }}",
                "vm_name": "{{user `vm_name_prefix`}}-{{user `box_version`}}",
                "disk_mode": "{{ user `disk_mode` }}",
                "vm_folder": "{{ user `vm_folder`}}",
                "resource_pool": "",
                "overwrite": "true",
                "options": [
                    "--X:logFile=builds/ovftool-output-{{user `box_version`}}.log",
                    "--X:logLevel=verbose"
                ],
                "only": [
                    "vmware"
                ]
            },
            {
                "type": "vsphere-template",
                "name": "template-den3",
                "insecure": true,
                "host": "{{ user `vcenter_den3` }}",
                "datacenter": "{{ user `datacenter_den3` }}",
                "username": "{{ user `vcenter_username` }}",
                "password": "{{ user `vcenter_password` }}",
                "folder": "/{{ user `vm_folder`}}",
                "only": [
                    "vmware"
                ]
            }
        ]
  ]
```

### Operating system and Environment details

RHEL Linux 7.7 x86_64

### Log Fragments and crash.log files

```
==> vmware: Running post-processor: vsphere-template
    vmware (vsphere-template): Waiting 10s for VMware vSphere to start
    vmware (vsphere-template): Choosing datacenter...
    vmware (vsphere-template): Creating or checking destination folders...
    vmware (vsphere-template): Marking as a template...
==> vmware (vsphere-template): ServerFaultCode: Permission to perform this operation was denied.
==> vmware (vsphere-template): ServerFaultCode: Permission to perform this operation was denied.
==> vmware (vsphere-template): Step "stepMarkAsTemplate" failed
==> vmware (vsphere-template): [c] Clean up and exit, [a] abort without cleanup, or [r] retry step (build may fail even if retry succeeds)? r
    vmware (vsphere-template): Marking as a template...
==> vmware (vsphere-template): ServerFaultCode: Permission to perform this operation was denied.
==> vmware (vsphere-template): ServerFaultCode: Permission to perform this operation was denied.
==> vmware (vsphere-template): Step "stepMarkAsTemplate" failed
==> vmware (vsphere-template): [c] Clean up and exit, [a] abort without cleanup, or [r] retry step (build may fail even if retry succeeds)? a
==> vmware (vsphere-template): ServerFaultCode: Permission to perform this operation was denied.
==> vmware (vsphere-template): Step "stepMarkAsTemplate" failed, aborting...
==> vmware (vsphere-template): aborted: skipping cleanup of step "stepCreateSnapshot"
==> vmware (vsphere-template): aborted: skipping cleanup of step "stepCreateFolder"
==> vmware (vsphere-template): aborted: skipping cleanup of step "stepChooseDatacenter"
```

NOTE: I have logged with more detail, but it still doesn't say why its failing. The code doesn't include reasons.

## Steps taken so far...

I recommend that more useful information be added to the error messages, to indicate *where* or *why* it failed. I am not a "developer" but I added some messages https://github.com/hashicorp/packer/compare/master...TJM:vsphere_template_debug?expand=1 to find out that the actual error is coming from, since there are *several* operations happening during this "step"... I have found that the actual error is during the `vm.Unregister` sub-step.

```
==> vmware: Running post-processor: vsphere-template
    vmware (vsphere-template): Waiting 10s for VMware vSphere to start
    vmware (vsphere-template): Choosing datacenter...
    vmware (vsphere-template): Creating or checking destination folders...
    vmware (vsphere-template): Marking as a template...
==> vmware (vsphere-template):  - vm.Unregister
==> vmware (vsphere-template): ServerFaultCode: Permission to perform this operation was denied.
==> vmware (vsphere-template): ServerFaultCode: Permission to perform this operation was denied.
==> vmware (vsphere-template): Step "stepMarkAsTemplate" failed
==> vmware (vsphere-template): [c] Clean up and exit, [a] abort without cleanup, or [r] retry step (build may fail even if retry succeeds)? c
==> vmware: Running post-processor: vsphere
    vmware (vsphere): Uploading builds/centos-7.7-vmware-2019.12.19-0334/centos-7.7-vmware-2019.12.19-0334.vmx to vSphere
    vmware (vsphere):
==> vmware: Running post-processor: vsphere-template
    vmware (vsphere-template): Waiting 10s for VMware vSphere to start
    vmware (vsphere-template): Choosing datacenter...
    vmware (vsphere-template): Creating or checking destination folders...
    vmware (vsphere-template): Marking as a template...
Build 'vmware' errored: 2 error(s) occurred:

* Post-processor failed: Error uploading virtual machine: exit status 1


* Post-processor failed: ServerFaultCode: Permission to perform this operation was denied.
```

... so, I suggest that maybe something more elegant than what I have added.

However, I am *really* trying to figure out why it is trying to unregister the VM, or what its actually trying to do before marking it as a template?  Hopefully someone can help!

Thanks in advance,
Tommy

**Comment by TJM** [comment]
@sylviamoss I think the labels are a little off. While both of the (modules?) you tagged are involved in the overall build, the actual "problem" is with the post-processor/vsphere-template .. I can seem to edit labels (or I don't know how). :)

**Comment by sylviamoss** [comment]
Hi @TJM! I labeled as builder/vmware because it was the builder you were using when the issue happened with the vsphere post-processor. 
I like adding as many labels as possible, but it wouldn't be a problem adding just the post-processor label...

You can find the labels on the right side of the page and to add/delete them you press the engine symbol next to `Labels`, a dropdown will appear with all available labels.

**Comment by TJM** [comment]
Must be a "I don't have access" thing, then :)

I have already fixed this, but I am going to open another PR on making this entire process much simpler.

**Comment by TJM** [comment]
As indicated by my PR #8511 I found the issue to be that it was trying to use "UnregisterVM" which my service account doesn't have access to do. I have setup an optional "MarkAsTemplate" method... which should solve my problem at least. :)
