### ISSUE TITLE
qemu's "disk_image" equivalent for Virtualbox builder?

### ISSUE THREAD

**Issue by harisund** [hashicorp/packer#8521]
In the qemu builder documentation, there's a ["disk_image"](https://www.packer.io/docs/builders/qemu.html#disk_image) configuration that says 

`Packer defaults to building from an ISO file, this parameter controls whether the ISO URL supplied is actually a bootable QEMU image.`

Is there a similar feature for VirtualBox or some way to achieve it? I would like to provide a VMDK or a VDI file as a "iso_url" and set my "disk_image" to true.

At the moment, the only work around I am aware of is to first create a virtual machine, attach my desired VMDK/VDI file, set all the properties of the VM manually, create a snapshot and then run the virtualbox-vm builder. 

EDIT: Just thought I would add some more details. I have a few developers running packer on Windows +VirtualBox, and their "source" disk is effectively [Ubuntu's Bionic cloud image ubuntu-18.04-server-cloudimg-amd64.vmdk ](https://cloud-images.ubuntu.com/releases/bionic/release/)
In the same page, Ubuntu does provide a _ova_ file as well which could potentially be fed into the virtualbox-ova builder, but that has a lot of issues that need to be fixed first, which requires running a string of vboxmanage options. It would be a lot cleaner to simply start with the vmdk file, just like how qcow files can be fed into the qemu builder.

**Comment by SwampDragons** [comment]
Hi, thaks for reaching out. I think you're just looking in the wrong place -- for virtualbox, we have a whole separate builder for booting from a disk instead of from a VM. The [virtualbox-iso](https://www.packer.io/docs/builders/virtualbox-iso.html) builder is the one you want :)

Off the top of my head I'm not 100% sure whether it can use vmdks as its source image or not, but if it can't it should be a simple process to convert the vmdk to an iso.

**Comment by harisund** [comment]
> but if it can't it should be a simple process to convert the vmdk to an iso.

This doesn't make sense at all. ISOs and VMDKs are meant for two different things. Even if somehow we did manage to convert a VMDK to a ISO, it would still be booted as an ISO, which would attached as a CD ROM and not as a disk, negating the whole point of using packer in the first place.

I opened this explicitly because the virtualbox-iso builder does _not_ do what I am asking. 

> Off the top of my head I'm not 100% sure whether it can use vmdks as its source image or not

Would you please be able to verify if this is indeed the case, and if there's a way to pass a vmdk or a vdi file to virtualbox-iso builder as a hard disk, rather than as a CD ROM (which is what we can do right now?)

**Comment by SwampDragons** [comment]
Sorry, I should have said "virtualbox-usable image", not iso. I don't think either virtualbox builder has the option you're looking for. I can try to schedule someone to look at adding this tooling early next year.

**Comment by harisund** [comment]
Thank you! You can keep this issue closed if you wish, I just wanted to kinda put it in your radar. 

Again, if any one stumbles on to this page looking for a "disk_image" equivalent of qemu in the virtualbox builder, there are a couple of work arounds - such as creating a VM with the disk imported, then using the virtualbox-vm builder, creating a OVA around the VMDK and using the virtualbox-ovf builder, or creating a new virtualbox-iso build but then use the vboxmanage commands to remove the ISO and attach the vmdk file. 

Thanks again!
