### ISSUE TITLE
Ansible provisionner: useless stars in display of Ansible command

### ISSUE THREAD

**Issue by nqb** [hashicorp/packer#8537]
#### Overview of the Issue

After upgrading from Packer 1.4.5 to 1.5.1, I got useless stars on console when Packer displays Ansible command run:
```
[..]
==> docker: Executing Ansible: *****a*****n*****s*****i*****b*****l*****e*****-*****p*****l*****a*****y*****b*****o*****o*****k***** *****-*****-*****e*****x*****t*****r*****a*****-*****v*****a*****r*****s***** *****p*****a*****c*****k*****e*****r*****_*****b*****u*****i*****l*****d*****_*****n[..]
```
##### test.pkr.hcl:
```hcl
source "docker" "example" {
       image = "centos:7"
       commit = "true"
}

build {
    sources = [
        "source.docker.example"
    ]

    provisioner "ansible" {
        playbook_file = "site.yml"
    }       
}
```

#####  site.yml
```yaml
- hosts: default
  name: test

  tasks:
    - name: test
      debug:
        var: ansible_check_mode
```

### Packer version
1.5.1

### Operating system and Environment details

Debian buster 64 bits running packer installed from zip file.

**Comment by SwampDragons** [comment]
Hi, I believe I've fixed this in #8570; builds of Packer containing the patch can be found here: https://circleci.com/gh/hashicorp/packer/27287#artifacts/containers/0
