### ISSUE TITLE
Panic on uncorrect build source name (HCL2)

### ISSUE THREAD

**Issue by timurb** [hashicorp/packer#8539]
#### Overview of the Issue

If you create reference to source in incorrect format in HCL2 you'll get panic instead of nice error.

#### Reproduction Steps

Try to build this hcl file
```hcl
source "amazon-ebs" "ami" {
}


build {
  sources = ["ami"]
}
```

This ☝️ produces panic and a crash log.

If instead you change `sources` line into `sources = ["source.amazon-ebs.ami"]` you get error about missing params in builder section as I would expect.

### Packer version

Packer v1.5.1

### Operating system and Environment details

MacOS 10.14.6

### Log Fragments and crash.log files

https://gist.github.com/timurb/58fc6ecded95666959d4694e75746936

**Comment by azr** [comment]
Hey @timurb good catch, thanks for opening ! I created a fix here #8569
