### ISSUE TITLE
Support variables in HCL2

### ISSUE THREAD

**Issue by timurb** [hashicorp/packer#8540]
I could not make new HCL2 parser use variables from `variables` section:

* If I use the interpolation syntax akin to terraform `ami_name = "ami-${ami_version}"` I get the error `Variables may not be used here.`
* If I use gotemplate interpolation syntax `  ami_name = "ami-{{ .ami_version}}"` I get the error `AMIName should only contain alphanumeric characters......` (no matter what is inside `{{...}}`) which means that template is not expanded.

I didn't find anything in docs regarding using variables in docs under this branch: https://www.packer.io/guides/hcl
If variables are already implemented then docs might need to be updated.

**Comment by nqb** [comment]
Hello @timurb,

Did you take a look at this section: https://www.packer.io/docs/configuration/from-1.5/index.html ?

**Comment by timurb** [comment]
No, I found only the link I posted, thanks for reference!

Still it doesn't explain how to use variables — I tried to use interpolation syntax with no luck, see first bullet point in my original ticket (I can remove the second bullet point from issue description if it confuses reader).

**Comment by nqb** [comment]
I agree with you @timurb, I don't see how to use variables. Docs need to be improved.

**Comment by azr** [comment]
Hello there, thanks for opening; variables aren't a thing **yet**. I think these are a **must have** and this going to be my immediate concern ! ( after I fix some HCL2 crashes ).

HCL2 support is going to be incremental 🙂.

**Comment by tracphil** [comment]
@azr I wish that was explicitly mentioned somewhere in the docs :-)

**Comment by azr** [comment]
Hey @tracphil yes sorry that's my bad I should have made that clearer. Because the v1.5.2 is going to bundle variables in and documentation is updated only once every release I'm using this issue as a documentation; hopefully this is temporary!

**Comment by NickLarsenNZ** [comment]
Hi @azr, do you have an indication of when this might be resolved?

Given sensitive information (username/password) being used in configurations, and the ease of accidentally committing credentials - hard coding the values even temporarily isn't an option.

**Comment by ravenium** [comment]
@NickLarsenNZ They pushed variable support a few weeks ago (apologies but I can't find the message I got).  I'm using  1.5.4, per my cli.

Now if they could just get {{template_dir}} working...

**Comment by NickLarsenNZ** [comment]
My bad, I'm also using **1.5.4**. After rewriting it (since I reverted the changes), it is indeed working, so I guess I had a typo.

Thanks @ravenium, and apologies @azr for the noise.

**Comment by azr** [comment]
Hello there; the [nightly](https://github.com/hashicorp/packer/releases/tag/nightly) release should contain a much complete version of the variables support.

The TLDR of how they work is:

1/ Declare a var:
```hcl
# this can be declared in any *.pkr.hcl file depending on your preference.
# For example in vars.pkr.hcl if you want them all there
# or at the top of the file where it is being used
variable "foo" {
  type = string
  default = ""
}
```

2/ Set it either from:

* env: `PKR_VAR_foo=bar packer ...`
* an `*.auto.pkrvars.hcl` file : `packer build folder/`
```hcl
# folder/varfile.auto.pkrvars.hcl
foo = "bar"
# this file needs to be in the same folder as your buildfiles and packer will just parse it as a varfile
```
* a var argument `packer -var-file /home/azr/shared_confs/foo.pkrvars.hcl -var foo=bar ...` :
```hcl
# this file can be anywhere but it's extension needs to be ".hcl" ( or ".json" for the json format )
foo = "bar"
```

The further down this list the more priority the setting will have. auto varfiles are sorted in lexical order of their filenames. `-var` and `-var-file`s are not auto sorted and the last one that sets a variable 'wins'.

⚠️  Note that `pkrvars.hcl` files have a specific layout and permit setting variables directly without a body.

**Comment by NickLarsenNZ** [comment]
Brilliant, thanks @azr. I'll give the nightly build a try.
