### ISSUE TITLE
shared image gallery end of life date

### ISSUE THREAD

**Issue by pmozbert** [hashicorp/packer#8556]
#### Feature Description
Add End of Life Date parameter for Azure ARM Builder shared_image_gallery_destination struct.
This parameter is documented [here ](https://docs.microsoft.com/en-us/azure/templates/microsoft.compute/2019-07-01/galleries/images/versions
)in the Azure ARM schema docs.

For example:
`"shared_image_gallery_destination": {
  "resource_group": "ResourceGroup",
  "gallery_name": "GalleryName",
  "image_name": "ImageName",
  "image_version": "1.0.0",
  "image_version_endOfLifeDate":2020-04-01"
}`

#### Use Case(s)
It's common to clean up obsolete gallery images by setting an EOL on them.  
Without this feature, I need to set an EOL tag on the image and create a scheduled automation job to remove the images. It's better to use the native feature of the resource provider.

**Comment by SwampDragons** [comment]
This seems like a cool feature -- I am not sure when I'll have a chance to work on it, but it also seems like the kind of thing that may be straightforward for a new contributor to implement. I'd be happy to give pointers to someone who wants to try to add this option.

**Comment by pmozbert** [comment]
I can take a shot at it, but need to learn how to set up a dev
environment.  I've got 0 experience with Go.

**Comment by azr** [comment]
Hey @pmozbert; 
> but need to learn how to set up a dev environment

https://github.com/hashicorp/packer/blob/master/.github/CONTRIBUTING.md will help you get started quickly !

**Comment by ata18** [comment]
https://github.com/hashicorp/packer/pull/8561 This adds the ability to set end-of-life-date on image versions.

**Comment by SwampDragons** [comment]
this was closed by #8561 and support for this feature will be released in v. 1.5.2
