### ISSUE TITLE
Add option to avoid `docker pull`

### ISSUE THREAD

**Issue by nhooey** [hashicorp/packer#8557]
#### Feature Description

It would be convenient to have a Packer command-line option that would avoid all Docker network operations like `pull` and `push`.

When rebuilding Docker images repeatedly, it's tedious to wait for the `docker pull` operation to run when you know that the remote image hasn't been updated.

It wouldn't have to be a command-line option, it could also be some option in the template JSON file itself, that one would avoid committing to version control because it's just for a temporary testing situation.

#### Use Case(s)

* When you don't have an Internet connection
* When you know that the remote image hasn't been updated
* When you don't care to `docker push` because you're just trying to get something working and can push later when it is

**Comment by rickard-von-essen** [comment]
See [pull] (https://packer.io/docs/builders/docker.html#pull)
