### ISSUE TITLE
common/step_download: Don't error on no urls

### ISSUE THREAD

**Issue by carlpett** [hashicorp/packer#8562]
#### Feature Description
In step_download.go, the configured urls are looped over, and if nothing succeeds, and error is returned:
https://github.com/hashicorp/packer/blob/0649c3f7dca9aabc2b8603cfa723a41a78fe9d30/common/step_download.go#L55-L62
https://github.com/hashicorp/packer/blob/0649c3f7dca9aabc2b8603cfa723a41a78fe9d30/common/step_download.go#L85-L91

If no urls are given, that means we'll go directly to erroring. I'd like to add a check in the beginning to return `ActionContinue` if there are not configured urls.

#### Use Case(s)

Without this, the setup of the builder code is much more complicated to conditionally download ISOs depending on configuration (ie let the builder either download an ISO **or** use something else). Most (all?) other common steps have such a short-circuit to silently continue if they aren't configured to run.

Additionally, `common.ISOConfig.Prepare` errors if being run while expecting configuration, so a builder would already need to explicitly handle the cases where they do not want this to be an error.

ping @azr @SwampDragons

**Comment by SwampDragons** [comment]
I think this makes sense. I'll have to investigate to make sure it doesn't break any assumptions, but off the top of my head I doubt it does.

**Comment by carlpett** [comment]
Haha @SwampDragons, seems we did the same PR, more or less :sweat_smile:

**Comment by SwampDragons** [comment]
lol oops!
