### ISSUE TITLE
Add documentation for ssh_interface option

### ISSUE THREAD

**Issue by nilsmeyer** [hashicorp/packer#8565]
#### Feature Description
The available options for the `ssh_interface` option should be documented (possibly per builder?), e.g. for Amazon public_ip, public_dns, private_ip, private_dns

#### Use Case(s)
I had problems connecting to my instance, changing the ssh_interface option to 'public_ip' solved this, however that wasn't obvious from the documentation and required quite a bit of googling.

**Comment by SwampDragons** [comment]
Good point! I've opened PR #8571 to address this :)
