### ISSUE TITLE
vagrant-cloud post-processor error

### ISSUE THREAD

**Issue by mikejw** [hashicorp/packer#8577]
I'm getting this error:

" virtualbox-iso (vagrant-cloud): error decoding error response: json: cannot unmarshal array into Go struct field VagrantCloudErrors.errors of type map[string][]string"

#### Reproduction Steps
I'm assuming running any packer build script using the vagrant-cloud post-processor.

It's taking me a while to test this as I don't know a way of running the post-processor in isolation with the previously built virtualbox-iso asset.

(I'm going to try again setting the env variable PACKER_LOG=1.)

### Packer version
v1.5.1

### Operating system and Environment details

Arch Linux 5.4.8-arch1-1 x86_64 GNU/Linux

**Comment by SwampDragons** [comment]
Thanks for opening an issue -- to help you, we really do need the things requested in the issue template:, including the simplest complete example template and scripts needed to reproduce the bug.

**Comment by mikejw** [comment]
#### Overview of the Issue

I'm getting the error:

" virtualbox-iso (vagrant-cloud): error decoding error response: json: cannot unmarshal array into Go struct field VagrantCloudErrors.errors of type map[string][]string"


#### Reproduction Steps

Run with:
    $ PACKER_LOG=1 VAGRANT_CLOUD_TOKEN=<vagrant cloud token> packer build -var 'version=0.1.0' debian.json >out.txt 2>&1

### Packer version

v1.5.1

### Simplified Packer Buildfile

Derived from geerlingguy packer boxes.

Contents of 'setup/cleanup.sh':

	#!/bin/bash -eux

	# Uninstall Ansible and dependencies.
	apt-get remove python-pip python-dev

	# Apt cleanup.
	apt autoremove
	apt update

	# Delete unneeded files.
	rm -f /home/vagrant/*.sh

	# Zero out the rest of the free space using dd, then delete the written file.
	dd if=/dev/zero of=/EMPTY bs=1M
	rm -f /EMPTY

	# Add `sync` so Packer doesn't quit too early, before the large file is deleted.
	sync


Contents of 'http/preseed.cfg':

	choose-mirror-bin mirror/http/proxy string
	d-i apt-setup/use_mirror boolean true
	d-i base-installer/kernel/override-image string linux-server
	d-i clock-setup/utc boolean true
	d-i clock-setup/utc-auto boolean true
	d-i finish-install/reboot_in_progress note
	d-i grub-installer/only_debian boolean true
	d-i grub-installer/with_other_os boolean true
	d-i keymap select us
	d-i mirror/country string manual
	d-i mirror/http/directory string /debian
	d-i mirror/http/hostname string httpredir.debian.org
	d-i mirror/http/proxy string
	d-i partman-auto-lvm/guided_size string max
	d-i partman-auto/choose_recipe select atomic
	d-i partman-auto/method string lvm
	d-i partman-lvm/confirm boolean true
	d-i partman-lvm/confirm boolean true
	d-i partman-lvm/confirm_nooverwrite boolean true
	d-i partman-lvm/device_remove_lvm boolean true
	d-i partman/choose_partition select finish
	d-i partman/confirm boolean true
	d-i partman/confirm_nooverwrite boolean true
	d-i partman/confirm_write_new_label boolean true
	d-i passwd/root-login boolean false
	d-i passwd/root-password-again password vagrant
	d-i passwd/root-password password vagrant
	d-i passwd/user-fullname string vagrant
	d-i passwd/user-uid string 1000
	d-i passwd/user-password password vagrant
	d-i passwd/user-password-again password vagrant
	d-i passwd/username string vagrant
	d-i pkgsel/include string sudo bzip2 acpid cryptsetup zlib1g-dev wget curl dkms make nfs-common net-tools
	d-i pkgsel/install-language-support boolean false
	d-i pkgsel/update-policy select none
	d-i pkgsel/upgrade select full-upgrade
	# Prevent packaged version of VirtualBox Guest Additions being installed:
	d-i preseed/early_command string sed -i \
	  '/in-target/idiscover(){/sbin/discover|grep -v VirtualBox;}' \
	  /usr/lib/pre-pkgsel.d/20install-hwpackages
	d-i time/zone string UTC
	d-i user-setup/allow-password-weak boolean true
	d-i user-setup/encrypt-home boolean false
	d-i preseed/late_command string sed -i '/^deb cdrom:/s/^/#/' /target/etc/apt/sources.list
	apt-cdrom-setup apt-setup/cdrom/set-first boolean false
	apt-mirror-setup apt-setup/use_mirror boolean true
	popularity-contest popularity-contest/participate boolean false
	tasksel tasksel/first multiselect standard, ssh-server


Contents of 'debian.json':

    {
      "variables": {
        "version": ""
      },
      "provisioners": [
        {
          "type": "shell",
          "execute_command": "echo 'vagrant' | {{.Vars}} sudo -S -E bash '{{.Path}}'",
          "script": "scripts/cleanup.sh"
        }
      ],
      "builders": [
        {
          "type": "virtualbox-iso",
          "boot_command": [
            "<esc><wait>",
            "install <wait>",
            " preseed/url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/preseed.cfg <wait>",
            "debian-installer=en_US.UTF-8 <wait>",
            "auto <wait>",
            "locale=en_US.UTF-8 <wait>",
            "kbd-chooser/method=us <wait>",
            "keyboard-configuration/xkb-keymap=us <wait>",
            "netcfg/get_hostname={{ .Name }} <wait>",
            "netcfg/get_domain=vagrantup.com <wait>",
            "fb=false <wait>",
            "debconf/frontend=noninteractive <wait>",
            "console-setup/ask_detect=false <wait>",
            "console-keymaps-at/keymap=us <wait>",
            "grub-installer/bootdev=/dev/sda <wait>",
            "<enter><wait>"
          ],
          "boot_wait": "5s",
          "disk_size": 81920,
          "guest_os_type": "Debian_64",
          "headless": true,
          "http_directory": "http",
          "iso_urls": [
            "iso/debian-10.2.0-amd64-xfce-CD-1.iso",
            "https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-10.2.0-amd64-xfce-CD-1.iso"
          ],
          "iso_checksum_type": "sha256",
          "iso_checksum": "745172d8ba09f054335cc738409aede5c5f3463ae39df0a008eb41ceeba44b5c",
          "ssh_username": "vagrant",
          "ssh_password": "vagrant",
          "ssh_port": 22,
          "ssh_wait_timeout": "10000s",
          "shutdown_command": "echo 'vagrant'|sudo -S shutdown -P now",
          "guest_additions_path": "VBoxGuestAdditions_{{.Version}}.iso",
          "virtualbox_version_file": ".vbox_version",
          "vm_name": "packer-debian-10-amd64",
          "vboxmanage": [
            [
              "modifyvm",
              "{{.Name}}",
              "--memory",
              "1024"
            ],
            [
              "modifyvm",
              "{{.Name}}",
              "--cpus",
              "1"
            ]
          ]
        }
      ],
      "post-processors": [
        [
          {
            "output": "builds/{{.Provider}}-debian10.box",
            "type": "vagrant"
          },
          {
            "type": "vagrant-cloud",
            "box_tag": "<box tag goes here>",
            "version": "{{user `version`}}"
          }
        ]
      ]
    }

### Operating system and Environment details

Arch Linux 5.4.8-arch1-1 x86_64 GNU/Linux

### Log Fragments and crash.log files

https://gist.github.com/mikejw/ea02c259e9fb5f6d4612172475712b8f

**Comment by mikejw** [comment]
@SwampDragons Please see above response.

Many thanks.

**Comment by nywilken** [comment]
@mikejw thanks for the provided information. Looking at the logs I see that your vagrant-cloud API calls were being rate limited, as indicated by the`422` response - log entry [here](https://gist.github.com/mikejw/ea02c259e9fb5f6d4612172475712b8f#file-out-txt-L1082)

The second thing I see is that Packer is not handling the `422` response properly as the errors fields in the response is an empty array, as opposed to the expected map (or Hash) of errors, which needs to be fixed on our end. 

You might want to try building again or reaching out to the vagrant-cloud support team if your are still experiencing rate limiting. More information can be found at https://www.vagrantup.com/docs/vagrant-cloud/api.html#422-unprocessable-entity

**Comment by SwampDragons** [comment]
I believe this has been closed by #8594
