### ISSUE TITLE
disable_vnc causes unsetting of PACKER_HTTP_ADDR

### ISSUE THREAD

**Issue by hills** [hashicorp/packer#8583]
#### Overview of the Issue

When disable_vnc is set to true it causes PACKER_HTTP_ADDR to be unset in the shell provisioner.

Set disable_vnc to false, and the variable is available in the shell provisioner [as documented](https://www.packer.io/docs/provisioners/shell.html#default-environmental-variables
).

disable_vnc disables _connecting_ to the host on VNC, and is only needed for eg. grub boot prompt. It shouldn't have this side-effect on the shell provisioner.

#### Reproduction Steps

Set disable_vnc=true in the packer file when using the shell provisioner and attempt to use PACKER_HTTP_ADDR. See complete test case included.

### Packer version

Tested 1.5.1 (previously 1.4.1, 1.4.0 were affected, too)

### Simplified Packer Buildfile

<details>
<summary>http_vnc_test.packer</summary>

```
{
    "description": "Disabling VNC unsets HTTP variables",

    "builders": [
        {
            "type": "qemu",
            "headless": true,

            "iso_url": "./sl6/vda",
            "iso_checksum_type": "none",
            "disk_image": "true",

            "output_directory": "http_vnc_test",
            "vm_name": "vda",
            "disk_size": 32768,
            "use_backing_file": "true",
            "skip_compaction": "true",

            "shutdown_command": "echo 'packer' | sudo -S shutdown -P now",

            "ssh_username": "root",
            "ssh_password": "xxxxxxxxxxxxx",
            "ssh_timeout": "10m",

            "http_directory": "./",
            "disable_vnc": "true"
        }
    ],

    "provisioners": [
        {
            "type": "shell",
            "script": "http_vnc_test.sh"
        }
    ]
}
```
</details>

<details>
<summary>http_vnc_test.sh</summary>

```
#!/bin/sh

set -eu
echo "$PACKER_HTTP_ADDR"
```
</details>

This build references an existing image (in this case, a Scientific Linux 6 install), and attempts to specialise it.

### Operating system and Environment details

CentOS 7, x86_64, using qemu 4.2.0.

### Log Fragments and crash.log files

<details>
<summary>Basic log</summary>

```
$ packer build http_vnc_test.packer 
qemu: output will be in this color.

Warnings for build 'qemu':

* A checksum type of 'none' was specified. Since ISO files are so big,
a checksum is highly recommended.

==> qemu: Retrieving ISO
==> qemu: Trying ./sl6/vda
==> qemu: Trying ./sl6/vda
==> qemu: ./sl6/vda => /home/XXX/packer_cache/6d137a8ecd4a408829b8c23839b19460df87aab4.iso
==> qemu: Creating required virtual machine disks
==> qemu: Resizing hard drive...
==> qemu: Starting HTTP server on port 8731
==> qemu: Found port for communicator (SSH, WinRM, etc): 3294.
==> qemu: Looking for available port between 5900 and 6000 on 127.0.0.1
==> qemu: Starting VM, booting disk image
    qemu: The VM will be run headless, without a GUI. If you want to
    qemu: view the screen of the VM, connect via VNC without a password to
    qemu: vnc://127.0.0.1:5907
==> qemu: Using ssh communicator to connect: 127.0.0.1
==> qemu: Waiting for SSH to become available...
==> qemu: Connected to SSH!
==> qemu: Provisioning with shell script: http_vnc_test.sh
==> qemu: /tmp/script_6657.sh: line 4: PACKER_HTTP_ADDR: unbound variable
==> qemu: Provisioning step had errors: Running the cleanup provisioner, if present...
==> qemu: Deleting output directory...
Build 'qemu' errored: Script exited with non-zero exit status: 1.Allowed exit codes are: [0]

==> Some builds didn't complete successfully and had errors:
--> qemu: Script exited with non-zero exit status: 1.Allowed exit codes are: [0]

==> Builds finished but no artifacts were created.
```
</details>

[http_vnc_test.log](https://github.com/hashicorp/packer/files/4035568/http_vnc_test.log)

**Comment by nywilken** [comment]
Hi @hills thanks for reaching out. We’ll take a look when we get a chance. Regarding your statement "Tested 1.5.1 (previously 1.4.1, 1.4.0 were affected, too)" are you not seeing this issue in version 1.4.5 of Packer?

**Comment by sylviamoss** [comment]
Hi @hills, indeed the PACKER_HTTP_ADDR is only set when `disable_vnc` is false. [check here](https://github.com/hashicorp/packer/blob/master/builder/qemu/step_type_boot_command.go#L100)   

I would like to know what's your intent when setting `disable_vnc` to true and using the PACKER_HTTP_ADDR at the same time. If you trying, for example, to download files, this is not possible without VNC so it would make sense not having the http address set.

**Comment by azr** [comment]
To concur to what @sylviamoss just said; I think using the file provisioner to upload your file will work 🙂!

**Comment by hills** [comment]
Thanks for looking at this.

As the uninitiated, it's odd that the presence of an HTTP server should depend on (or be related to, at all) the VNC functionality -- which presents itself as strongly associated with the <tt>boot_command</tt> only.

[Clarification in the docs](https://www.packer.io/docs/builders/qemu.html#disable_vnc) would be a welcomed. But instead of the complexity, could this 'common' behaviour just be called upon outside of the step_type_boot_command.go instead?

Then it's as simple as "the qemu provisioner provides an HTTP server if http_directory is given" which is far more intuitive and does not come with extra, opaque requirements.

The web server is useful, for example, for large files used by the script that you don't want copied to the final system; eg. large RPM packages. Especially if the RPM dependencies may depend on some other condition at runtime.

**Comment by azr** [comment]
Hey @hills ! After some though we (the team) agree with you and we would like to allow to use the http server more widely; so this will happen but I can't give you a schedule though !

Note that this feature was build with the mindset that it could be used only in pair with vnc in order to allow to send preseed files. So this might be a big one to do. Hang in there 🙂 !

**Comment by sylviamoss** [comment]
Hi @hills! I've opened a PR for fixing this. 
Could you check if the solution works for you? You can use these binaries to do it: https://circleci.com/gh/hashicorp/packer/30935#artifacts/containers/0
