### ISSUE TITLE
Fallback to publicly available images if the requested image does not exist within the specified source_image_project_id

### ISSUE THREAD

**Issue by kwibus** [hashicorp/packer#8589]
#### Feature Description

If you use **source_image_project_id** for the googlecompute builder, it will only search in that project.
While without it. it will search in the current project, and for **public images**.

It does what is say`s it does, But i was expecting that it should be able to find public images even when source_image_project_id is defined.   

#### Use Case(s)

I use packer in scripts that generate images for other team's,
We have test en production projects. After a images is tested it will be moved to production project.
I want to give user of the script the option, to build on top of production images.
Those images should first be test in the test project. So if i want to build for test, from images from production. I need source_image_project_id.
But if the user of the script wants to base it's image on centos-7. It's no longer able to find it.

You can, of course, work around this: 
* keep copy of images in test.
* detect if it needs source_image_project_id 

But if packer would also search for public images when using **source_image_project_id**. It would be a lot simpler.

**Comment by nywilken** [comment]
Thanks for reaching out. I believe this a limitation on the Google Compute API as using the source images project id  does not get any images that belong to other projects, including publicly-available images. 

It might be possible to have Packer make another Google API call to get the source images without the source_image_project_id filter, if an image is not found within the `source_image_project_id`. But I think that might have some unexpected behaviors. We need to think about this use case a little more. 

I updated the title of this issue to reflect what I understand the feature request to be, but please feel free to correct it if my understanding is off.

**Comment by kwibus** [comment]
Thanks for responding that quickly.
I agree your title is better, and describes what i meant.
I think its not part of the Google Compute API

It looks like GetImage is called without source_image_project_id and GetImageFromProject otherwise:
https://github.com/hashicorp/packer/blob/dca2c03cdb3bc9e04b930d163ec955ea956ac627/builder/googlecompute/step_create_instance.go#L86-L90

And GetImage loops over project for public images, and it's own project calling  GetImageFromProject
https://github.com/hashicorp/packer/blob/d6a351b17388bf934424704af16cb105f4535df6/builder/googlecompute/driver_gce.go#L214-L251

So if you create a new function that can be called at `/builder/googlecompute/step_create_instance.go:89` that also loops over that list of projects you will get the same result.

Maybe refactor out what is common between `GetImage` and that new function or something.
I have no problem with writhing a pull request, if you want. 

About the unexpected behaviors, I think the change would have limited effect on existing code.
But your right it would influence packer users expecting the current behavior.

**Comment by nywilken** [comment]
@kwibus thanks for confirming the title change, and apologies for not being able to get back sooner. 

The code snippet you pointed out looks to be doing what I thought we would have to do to satisfy this request; essentially make multiple calls to GetImageFromProject.  

> So if you create a new function that can be called at /builder/googlecompute/step_create_instance.go:89 that also loops over that list of projects you will get the same result.
>Maybe refactor out what is common between GetImage and that new function or something.
I have no problem with writhing a pull request, if you want.

This sounds like a good idea to me. We would gladly accept a PR; it would help seeing as you have an actual use case to test against. 

>About the unexpected behaviors, I think the change would have limited effect on existing code.
But your right it would influence packer users expecting the current behavior.

This my be something that a new Packer config option could remedy (e.g `search_public_images`). It could be false by default and true if the user wants Packer to fallback if the source image is not found in the project. 

cc @SwampDragons for insight.
