### ISSUE TITLE
amazon-import post-processor handles multiple disks improperly

### ISSUE THREAD

**Issue by benjamb** [hashicorp/packer#8590]
#### Overview of the Issue

In my case, I'm using the hyperv-iso builder and have entries within `disk_additional_size`, when this is passed on to the amazon-import post-processor it ends up finding the wrong disk.

The code in question isn't particularly smart. It iterates over artefacts from a builder and returns the first artefact it finds that has the specified suffix (in my case vhdx). The issue with this, on Windows at least, is that `vm-0.vhdx` is found before the core image without the index suffix, i.e. `vm.vhdx` when iterating over the artefacts.

	for _, path := range artifact.Files() {
		if strings.HasSuffix(path, "."+p.config.Format) {
			source = path
			break
		}
	}

It would make sense to perhaps specify which image you would like to be imported, rather than attempting to guess which one. As an additional improvement, Amazon's VM Import supports multiple disk images so this could be implemented (it would still make sense to add an optional config to specify disk images, perhaps using an explicit list or regex/glob).

### Packer version

1.5.1 (master)

### Operating system and Environment details

Windows 10 Pro
amd64

**Comment by nywilken** [comment]
Thanks for reaching out. In order for us to best help could you provide the things requested in the issue template; including the simplest Packer configuration and scripts needed to reproduce the bug.

We will try to take a look when we get a chance. But if you're comfortable with it, feel free to open a pull request with the proposed solution and ask any questions you may have about it. Cheers :smile:
