### ISSUE TITLE
Vagrant Builder does not find SSH private key in vagrant.d directory if there is a space in the path

### ISSUE THREAD

**Issue by bensonbenson** [hashicorp/packer#8599]
#### Overview of the Issue

I'm not sure if this is related to issue #8413, but a colleague and I have observed that if there is a space in the path to the Vagrant home directory, then Packer seems to get an SSH error when it tries to look for the `insecure_private_key` file. 

#### Reproduction Steps

This fails, post-provisioning: `PACKER_LOG=1 VAGRANT_HOME="/c/directory with space" packer build -force centos.json`

This does not: `PACKER_LOG=1 VAGRANT_HOME="/c/nospacedir" packer build -force centos.json`

where `directory with space` and `nospacedir` are new, empty directories. 

centos.json:
https://gist.github.com/bensonbenson/72a951ff883da26289b5342397a4f8e2

vagrantfile.template:
https://gist.github.com/bensonbenson/943d3b1e546628a3175459d2732789ff

### Packer version

Packer v1.5.1

### Operating system and Environment details

This is on Windows 10 within the Git Bash shell (MINGW64). A colleague has noticed this is an issue on ArchLinux (not sure the specifics of his setup, but creating a new Vagrant home directory with spaces in its name will cause the same issue.)

### Log Fragments and crash.log files

```
==> virtualbox: Using ssh communicator to connect: 127.0.0.1
==> virtualbox: Waiting for SSH to become available...
2020/01/13 11:41:27 packer.exe plugin: [INFO] Waiting for SSH, up to timeout: 10m0s
2020/01/13 11:41:27 packer.exe plugin: [DEBUG] Error getting SSH config: Error on reading SSH private key: open "C:/space dir/insecure_private_key": The filename, directory name, or volume label syntax is incorrect.
2020/01/13 11:41:32 packer.exe plugin: [DEBUG] Error getting SSH config: Error on reading SSH private key: open "C:/space dir/insecure_private_key": The filename, directory name, or volume label syntax is incorrect.
2020/01/13 11:41:37 packer.exe plugin: [DEBUG] Error getting SSH config: Error on reading SSH private key: open "C:/space dir/insecure_private_key": The filename, directory name, or volume label syntax is incorrect.
```

**Comment by SwampDragons** [comment]
good to know, thanks! I'll try to take a look for the next release.
