### ISSUE TITLE
how to use variables from packer inside Ansible playbook ?

### ISSUE THREAD

**Issue by yamamoto52** [hashicorp/packer#8620]
my packer file includes : 

```
{
	"variables":{
		"version": "12.5.0"
	},
	"builders": [
...
	],
	"provisioners": [
		{
			"type": "ansible",
			"playbook_file": "gitlab-runner/playbooks/main.yml",
			"ansible_env_vars": [ "VERSION={{ user `version` }}"]
		}
	]
}

```

But I can't use this and don't see it anywhere , even if print hostvars[inventory_hostname]

**Comment by yamamoto52** [comment]
using 
```
"extra_arguments": ["--extra-vars", "VERSION={{ user `version` }}"]
```

works correctly as workaround

**Comment by nywilken** [comment]
Hi @yamamoto52 thanks for reaching out. The `extra_arguments` config, as you specified above, is what you are looking for. All arguments passed to extra_arguments will be passed to the the Ansible command at run `ansible-playbook sample.yml --extra-vars "version=1.23.45 ..."

Where as `ansible_env_vars` are environment variables that will get set before calling Ansible. In this case I would think that your ansible playbook would have to be setup to read the values from the environment variable `{{ lookup('env','VERSION') }}`. I'm going to close this issue as it has been resolved. If you run into any issues that you think may be a bug please feel free to open a new issue.
