### ISSUE TITLE
Provisioner shell script does not execute when execute_command is present

### ISSUE THREAD

**Issue by shahamit2** [hashicorp/packer#8629]
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue
It is observed that whenever provisioner shell script is specified along with execute_command then script is not executing but execute_command does get execute.

A paragraph or two about the issue you're experiencing.

#### Reproduction Steps
* TestCase-1: Without execute_command in ami.json
Below is excerpt of ami.json
"provisioners": [
      "type": "shell",
      "script": "scripts/cb/provisioner.sh",
      "environment_vars": [
          "CI_JOB_TOKEN={{user `CI_JOB_TOKEN`}}",
          "PACKER_RPM_NAME={{user `packer_rpm_name`}}"
      ]
]
Result : Instance launched using TestCase-1's AMI shows that script 'provisioner.sh' is executed successfully by Provisioner.

* TestCase-2: With execute_command in ami.json
Below is excerpt of ami.json
"provisioners": [
      "type": "shell",
      "script": "scripts/cb/provisioner.sh",
      "environment_vars": [
          "CI_JOB_TOKEN={{user `CI_JOB_TOKEN`}}",
          "PACKER_RPM_NAME={{user `packer_rpm_name`}}"
      ],
     "execute_command": "echo 'packer' > /home/centos/a.out"
]
Result : Instance launched using TestCase-2's AMI shows that script 'provisioner.sh' is not executed by Provisioner. But execute_command is executed successfully.

### Packer version
docker image hashicorp/packer:latest

From `packer version`
docker image hashicorp/packer:latest

### Simplified Packer Buildfile

If the file is longer than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/) of the log or use the [Github detailed
format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d)
instead of posting it directly in the issue.

### Operating system and Environment details
CentOS7

OS, Architecture, and any other information you can provide about the
environment.

### Log Fragments and crash.log files

Include appropriate log fragments. If the log is longer than a few dozen lines,
please include the URL to the [gist](https://gist.github.com/) of the log or
use the [Github detailed format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d) instead of posting it directly in the issue.

Set the env var `PACKER_LOG=1` for maximum log detail.

**Comment by azr** [comment]
Hello @shahamit2; thanks for opening.

I think you are using the execute command incorrectly; here's a link to the doc: https://www.packer.io/docs/provisioners/shell.html#execute_command

___

Execute command tells packer how you want your command to be executed so; if you do something like this:

```json
{"type": "shell",
"script": "scripts/cb/provisioner.sh",
"execute_command": "echo wohoo"}
```
or
```json
{"type": "shell",
"inline": ["echo hi", "echo there"],
"execute_command": "echo wohoo"}
```

Both of these examples will just run `echo wohoo`, the second one will do it twice.

I'd recommend on using the community for asking further questions on how to use it 🙂 https://www.packer.io/community.html 

I'm going to close this one for now; please tell us if you think something is wrong !
