### ISSUE TITLE
packer shows that it is capturing the image in the region for the resource-group instead it captures the image in location

### ISSUE THREAD

**Issue by sushilkm** [hashicorp/packer#8635]
#### Overview of the Issue

When using packer with azure-arm builder, `location` is there parameter using which a user can suggest which azure-region image needs to be captured in.
However, while capturing the image, packer does the right thing of capturing the image in azure-region instructed via `location` parameter.
However when it display builder message logs, it suggests that it is capturing image in the azure-region of the resource-group specified by parameter `managed_image_resource_group_name`.
Following is a sample log
```
==> azure-arm: Querying the machine's properties ...
==> azure-arm:  -> ResourceGroupName : 'packer-Resource-Group-8yb22df5xc'
==> azure-arm:  -> ComputeName       : 'pkrvm8yb22df5xc'
==> azure-arm:  -> Managed OS Disk   : '/subscriptions/*****/resourceGroups/packer-Resource-Group-8yb22df5xc/providers/Microsoft.Compute/disks/pkros8yb22df5xc'
==> azure-arm: Querying the machine's additional disks properties ...
==> azure-arm:  -> ResourceGroupName : 'packer-Resource-Group-8yb22df5xc'
==> azure-arm:  -> ComputeName       : 'pkrvm8yb22df5xc'
==> azure-arm: Powering off machine ...
==> azure-arm:  -> ResourceGroupName : 'packer-Resource-Group-8yb22df5xc'
==> azure-arm:  -> ComputeName       : 'pkrvm8yb22df5xc'
==> azure-arm: Capturing image ...
==> azure-arm:  -> Compute ResourceGroupName : 'packer-Resource-Group-8yb22df5xc'
==> azure-arm:  -> Compute Name              : 'pkrvm8yb22df5xc'
==> azure-arm:  -> Compute Location          : 'westus2'
==> azure-arm:  -> Image ResourceGroupName   : 'suskuma'
==> azure-arm:  -> Image Name                : 'ubuntu-my-image-2020-01-21-16-01-50'
==> azure-arm:  -> Image Location            : 'eastus'
==> azure-arm: Deleting resource group ...
==> azure-arm:  -> ResourceGroupName : 'packer-Resource-Group-8yb22df5xc'
==> azure-arm:
==> azure-arm: The resource group was created by Packer, deleting ...
==> azure-arm: Deleting the temporary OS disk ...
==> azure-arm:  -> OS Disk : skipping, managed disk was used...
==> azure-arm: Deleting the temporary Additional disk ...
==> azure-arm:  -> Additional Disk : skipping, managed disk was used...
Build 'azure-arm' finished.
```

#### Reproduction Steps

1. Create a resource group in any region(for eg. eastus)
2. While building image using packer specify location to be anything but the one specified in step 1(for eg. westus2)

### Packer version

This is a bug in latest version too, however I have seen it from 1.4.1

### Operating system and Environment details
the base-os used is ubuntu 18.04 for building the image.

**Comment by nywilken** [comment]
Hi @sushilkm this issue has been resolved by #9068 and is set to be released in v1.5.6, which will be available next week. If you would like to get access to the fix before the release you can download a patched binary from our nightly releases: https://github.com/hashicorp/packer/releases/tag/nightly
