### ISSUE TITLE
Existing image doesn't start ssh.service until VNC connection

### ISSUE THREAD

**Issue by Cirrith** [hashicorp/packer#8644]
#### Overview of the Issue

Using an existing Debian Buster image built with QEMU, the SSH service doesn't start until a VNC session is established. The default settings for QEMU doesn't produce enough entropy to initialize crng in a reasonable amount of time. I [found](https://wiki.qemu.org/Features/VirtIORNG) adding `-device virtio-rng-pci` adds an entropy device which enables SSH start. I'm not sure if this is a Packer bug but figured it was worth a report.

#### Reproduction Steps

* Create base image
```bash
$ qemu-img create -f qcow2 debian10.img 20G
$ qemu-system-x86_64 -m 2048 -hda debian10.img -boot d -cdroom debian-10.2.0-amd64-xfce-CD-1.iso
Basic install, no XFCE
```
* Install openssh-server
```bash
$ qemu-system-x86_64 -m 2048 -hda debian10.img
>>> apt update && apt upgrade -y && apt install -y openssh-server vim
>>> vim /etc/ssh/sshd_config
PermitRootLogin yes
```

* Boot
```bash
$ packer build buildfile.json
```

* VNC in to activate ssh.service
```bash
$ vncviewer 127.0.0.1:PACKER_VNC_PORT
```

### Packer version

Packer version: 1.5.1

### Simplified Packer Buildfile

```json
{
    "builders": [
        {
            "type": "qemu",

            "iso_url": "file:/home/user/debian10.img",
            "iso_checksum_type": "none",
            "disk_image": "true",

            "headless": "true",
            "cpus": "1",
            "memory": "1024",
            "boot_wait": "2m",
            "shutdown_command": "systemctl poweroff",

            "ssh_timeout": "5m",
            "ssh_username": "root",
            "ssh_password": "password",

            "output_directory": "image"
        }
    ]
}
```

### Operating system and Environment details

Ubuntu 18.04 with Qemu Version 2.11.1

### Log Fragments and crash.log files

Runs the following commands
```
qemu-img convert -O qcow2 /home/user/debian10.img image/packer-qemu
qemu-img resize -f qcow2 image/packer-qemu 40G
/usr/bin/qemu-system-x86_64 -name packer-qemu -machine type=pc,accel=kvm -netdev user,id=user.0hostfwd=tcp::3841-:22 -device virtio-net,netdev=user.0 -drive file=image/packer-qemu,if=virtio,cache=writeback,discard=ignore,format=qcow2 -boot c -m 2048 -vnc 127.0.0.1:0
```

**Comment by SwampDragons** [comment]
If you add the `-device virtio-rng-pci` to the `qemu_args`, does Packer successfully launch and connect to the instance?

**Comment by Cirrith** [comment]
Yes it does, thank you for the fast response. Did I miss this documented somewhere?

**Comment by SwampDragons** [comment]
Yes, the qemuargs field is documented [here](https://www.packer.io/docs/builders/qemu.html#qemuargs); we don't normally add defaults like this that are only necessary for specific guest operating systems, and provide the qemuargs field for guest-specific customizations. I'm not sure I want to add this flag to the default command, since we have the ability for people to set it if they need to.

Thanks for reaching out, and thanks for confirming that adding your flag solved the issue.
