### ISSUE TITLE
Windows Server 2016 failing provisioning 

### ISSUE THREAD

**Issue by GloverChris** [hashicorp/packer#8646]
Not sure if this is normal however I have tried building a server 2016 image and I get an unsupported config error from ebs and even after copying someones code that works I get the same error. 

`amazon-ebs: output will be in this color.

==> amazon-ebs: Prevalidating any provided VPC information
==> amazon-ebs: Prevalidating AMI Name: tester 1579807768
    amazon-ebs: Found Image ID: ami-02a58aeaf6a5f726d
==> amazon-ebs: Creating temporary keypair: packer_5e29f419-a7e0-88ff-af6c-b8dfb323de3e
==> amazon-ebs: Launching a source AWS instance...
==> amazon-ebs: Adding tags to source instance
    amazon-ebs: Adding tag: "Name": "Packer Builder"
==> amazon-ebs: Error launching source instance: Unsupported: The requested configuration is currently not supported. Please check the documentation for supported configurations.
==> amazon-ebs:         status code: 400, request id: fec049b6-4248-4a32-a74a-68b2c97d0d89
==> amazon-ebs: No volumes to clean up, skipping
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: Error launching source instance: Unsupported: The requested configuration is currently not supported. Please check the documentation for supported configurations.
        status code: 400, request id: fec049b6-4248-4a32-a74a-68b2c97d0d89

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Error launching source instance: Unsupported: The requested configuration is currently not supported. Please check the documentation for supported configurations.
        status code: 400, request id: fec049b6-4248-4a32-a74a-68b2c97d0d89`

**Comment by SwampDragons** [comment]
Thanks for reaching out -- before I investigate, I really do need the things requested in the issue template: 

- Packer version from `packer version`
- Full debug log output from `PACKER_LOG=1 packer build template.json`. _Please paste this in a gist https://gist.github.com_
- The _simplest complete example template and scripts_ needed to reproduce the bug. Include these in your gist https://gist.github.com

It looks like this is an error bubbling back from Amazon because you requested something that is invalid. Seeing your Packer template will help us figure out what this is.

**Comment by GloverChris** [comment]
@SwampDragons Thanks for the fast reply. Here is what I have. I included a downloadable zip too. Thanks in advanced!
https://gist.github.com/GloverChris/3820ec4ae43be799a5b348c6a69461b2
[3820ec4ae43be799a5b348c6a69461b2-02fbafd0c8a53bf6007927b957f618d9192929e4.zip](https://github.com/hashicorp/packer/files/4105554/3820ec4ae43be799a5b348c6a69461b2-02fbafd0c8a53bf6007927b957f618d9192929e4.zip)

**Comment by SwampDragons** [comment]
My guess is that the availability zone that your subnet is in doesn't have any t2.large instances available. Have you tried a different instance type/checked available isntances for your subnet's AZ?

**Comment by GloverChris** [comment]
I tried a couple others but let me try one more which I know should definitely be there.

**Comment by GloverChris** [comment]
Yep that was it. I changed the instance to a t3a.large and it works even though the t2s are available in oregon. Not sure why they dont work
