### ISSUE TITLE
gcp(finalize) = builder unable to complete instance

### ISSUE THREAD

**Issue by thetaylormcrae** [hashicorp/packer#8648]
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

Packer builds in GCP are able to be kicked off and the instance gets created. The issue experienced is when it goes to finalize / export the instance.

Similar issue: #6887 

NOTE: When removing disk_name, it appears the build "completes".

#### Reproduction Steps

1. Set-Location <path to Packer files>
2. packer_windows_amd64.exe build -timestamp-ui -debug <JSON builder for GCP>
3. Wait for builder to create instance
4. Wait for "ending PowerShell (telemetry)" message
5. After this, Packer will indicate two "Pausing after of step", then indicate "Deleting instance..."

### Packer version

1.5.2-dev [go1.13.6 windows amd64]

### Simplified Packer Buildfile

N/A for this issue

### Operating system and Environment details

OS: Windows 10 v1903

### Log Fragments and crash.log files

Debug from Packer: https://gist.github.com/thetaylormcrae/ffdc5ea997252599ec9066fe79b8eb2e
JSON Builder file: https://gist.github.com/thetaylormcrae/0b487513b350b98b862b1c4909077d1e

**Comment by nywilken** [comment]
Hello there! There have been some changes to the Google builder since 1.5.2. Have you tried with the latest version of Packer to see if your issue has been resolved?

**Comment by SwampDragons** [comment]
Closing this issue since we never heard back; hopefully this was resolved either by upgrading or by setting a longer timeout like the users in #6887
