### ISSUE TITLE
Packer Crash creating Windows 10 Azure-ARM image

### ISSUE THREAD

**Issue by johnmccrae** [hashicorp/packer#8653]
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

Packer was in the process of finishing off an image it had just created on Azure. 
==> azure-arm: Capturing image ...
==> azure-arm:  -> Compute ResourceGroupName : 'packer-Resource-Group-z6dqvedmpb'
==> azure-arm:  -> Compute Name              : 'pkrvmz6dqvedmpb'
==> azure-arm:  -> Compute Location          : 'West US 2'
==> azure-arm:  -> Image ResourceGroupName   : 'EDM_Master_Storage_Resource_Group'
==> azure-arm:  -> Image Name                : 'buildkite-windows-10'
==> azure-arm:  -> Image Location            : 'westus2'
==> azure-arm: ERROR: -> PropertyChangeNotAllowed : Changing property 'sourceVirtualMachine' is not allowed.
==> azure-arm:
==> azure-arm:
==> azure-arm: Cleanup requested, deleting resource group ...
==> azure-arm: Resource group has been deleted.
Build 'azure-arm' errored: unexpected EOF

#### Reproduction Steps

I don't know if I can reproduce it. But I will add that i was chasing a bug and had 2 instances of packer running at the same time. This one that crashed would be trying to write the same image name to disk, in the same location as the other instance. This instance would not be expecting an existing image. 

### Packer version

From `packer version`
1.4.4

### Simplified Packer Buildfile

[gist](https://gist.github.com/johnmccrae/d9742926dfc3ee3405ee372df163bc3a)

### Operating system and Environment details

windows 10 build 1909, Lenovo P1 laptop

### Log Fragments and crash.log files

[crash.log](https://github.com/hashicorp/packer/files/4114897/crash.log)

Set the env var `PACKER_LOG=1` for maximum log detail.

**Comment by krishicks** [comment]
I am able to reliably reproduce this by running parallel builds of packer.

**Comment by SwampDragons** [comment]
With which version of Packer? Do you have a simple repro template to share?

**Comment by krishicks** [comment]
Our issue ended up being that our concurrent builds were sharing a `managed_image_name` and `shared_image_gallery_destination.image_version`. Basically, we were doing something wrong, and Azure was right to throw an error.

When we made the concurrent builds properly unique the errors ceased.

**Comment by krishicks** [comment]
> With which version of Packer? Do you have a simple repro template to share?

Our error was seen with Packer 1.5.1. I think you could easily reproduce it by creating two builders that use the same `shared_image_gallery_destination` config.

**Comment by SwampDragons** [comment]
Oh, awesome. I'm trying to think what we could do on the Packer side to help prevent confusion about this in the future. any ideas about some kind of documentation update that could have helped you?

**Comment by krishicks** [comment]
The only improvement I can think of is a better error message from Azure; if it said "image already exists" or something it would be more clear that there was a collision.
