### ISSUE TITLE
virtualbox-ovf builder issue

### ISSUE THREAD

**Issue by ghost** [hashicorp/packer#866]
I originally posted this here: #793, but I think it's a different issue. I'm using Packer 0.5.1 with CentOS 6.4 and VirtualBox 4.3.6 and I'm experiencing an issue with the **virtualbox-ovf** builder. After creating an ovf file using the **virtualbox-iso** builder, I try to run the **virtualbox-ovf** builder and it fails because it never successfully connects via SSH and eventually times out:

![image](https://f.cloud.github.com/assets/650144/2041015/c4a79ea8-89bf-11e3-9282-91313f61d881.png)

Also, here's a gist (https://gist.github.com/doorhinge/8337429) containing:
- The kickstart file used with the **virtualbox-iso** builder.
- The template used with the **virtualbox-ovf** builder.
- The Packer log when running the **virtualbox-ovf** builder.

**Comment by rjnienaber** [comment]
I ran into this exact same issue and I managed to resolve it by adding the following to my Packer script:

```javascript
"vboxmanage": [
  ["modifyvm", "{{.Name}}", "--macaddress1", "080027a79e8f"]
],
```
@mkuzmin's comment tipped me off and I found the old mac address in my `/etc/udev/rules.d/70-persistent-net.rules` file. I saw a line like the following:

```
 # PCI device 0x8086:0x100e (e1000)
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="08:00:27:a7:9e:8f", ATTR{dev_id}=="0x0", ATTR{type}=="1", KERNEL=="eth*", NAME="eth0"
```

After that, evertyhing worked as normal.

**Comment by vitorcoxta** [comment]
I just ran into this issue as well. I ran a virtualbox-iso builder to create a CentOS 6 virtualbox, and then ran a virtualbox-ovf builder to import the ovf previously created and run some stuff.
When I run Packer on this last builder, it hangs waiting for SSH to become available, eventually exiting for timeout. If I login into the virtualbox while packer is waiting for SSH, and if I run

<pre>
ifconfig
</pre>

I just get information about 1 network interface: lo.

However, if I manually import the ovf and run it, ifconfig gets information about 2 network interfaces: eth0 and lo, and in this case I am able to SSH into the virtualbox from the host machine.

@mitchellh, probably this is an indicator of a Packer issue?

For the mean time, I managed to get this done with @rjnienaber tip (thanks!).

**Comment by jhulten** [comment]
Also seeing this issue.

@rjnienaber : Are you adding the modifyvm to the virtualbox-iso builder or the virtualbox-ova builder or both?

**Comment by rjnienaber** [comment]
@jhulten I have a scenario where I have one builder for an .ovf image from scratch using `virtualbox-iso` and then I use that image as input to another builder using `virtualbox-ovf`. I've only added it to build files that are downstream from the initial builder. 

I think the problem here is that [by design](https://www.virtualbox.org/ticket/5113#comment:3), VirtualBox reinitialises MAC addresses when importing an image. It seems that VirtualBox takes the view that when you clone a VM, you probably still want to run the original VM in which case duplicate MAC addresses could play havoc with the network.

**Comment by rickard-von-essen** [comment]
As @mitchellh hinted about and @rjnienaber already suggested this is about how EL(CentOS etc) handles how to name network interfaces.

**"The correct solution"** as  implemented in the [bento boxes](http://chef.github.io/bento/) can be found in:
 - https://github.com/chef/bento/blob/master/packer/scripts/centos/cleanup.sh - for EL/CentOS/RHEL etc
 - https://github.com/chef/bento/blob/master/packer/scripts/debian/networking.sh - for Debian based distros.

**Comment by bish0polis** [comment]
@rickard-von-essen :  those URLs are 404 now.  :-( 

I have seen a number of folks either whack the persistent-net.rules file, or delete that file AND symlink it to /dev/null to prevent it being recreated.  I'm not sure if that's what 'the correct solution' may be, but preventing that temporary/permanent cache/config from preventing a clean reconfig may be an idea elsewhere.

**Comment by andrewfraley** [comment]
I had this issue with the virtualbox-ovf provider and a CentOS 7 image.  By default it was putting the VM into bridged network mode.  The fix was to do:

`["modifyvm", "{{.Name}}", "--nic1", "nat"`

**Comment by davestj** [comment]
Just want to point out the fact that if all these people have to hack their way around this issue, it is indeed and in fact, a packer problem even if its an indirect issue. The problem is people expect it to work, not have to hack their way around things to get it to work, when we have to do this, this fits the description of a bug/product defect. FYI

**Comment by rickard-von-essen** [comment]
> The problem is people expect it to work, not have to hack their way around things to get it to work

@davestj They are not hacking around. They are supplying a correct config of their OS. Is see no descriptions of bugs above, just people struggling with the (advanced) topic of administrating and automating the setup of Linux.

**Comment by michalciolek** [comment]
Script from https://github.com/chef/bento/blob/master/debian/scripts/networking.sh fix the problem.

**Comment by bby-bishopclark** [comment]
@rickard-von-essen : the EL/Centos URL is 404 now

**Comment by rickard-von-essen** [comment]
Superold closed issue...

**Comment by bby-bishopclark** [comment]
Sorry.  I forgot we have no attention span.  That'll fix the links.

**Comment by SwampDragons** [comment]
@bby-bishopclark if you navigate to the bento repo (which doesn't belong to Packer) then you'll find that the directory structure has been slightly changed. 

https://github.com/chef/bento/blob/master/centos/scripts/cleanup.sh

For future users: just navigate to the base bento repo if the links 404. It's still highly likely that this repo will contain a working example for you.
