### ISSUE TITLE
[Feature Request] Proxmox: Add an option to boot a disk-based image instead of an iso image

### ISSUE THREAD

**Issue by godiedelrio** [hashicorp/packer#8660]
#### Feature Description
This option is similar to the option [disk_image](https://www.packer.io/docs/builders/qemu.html#disk_image) in the QEMU Builder.

#### Use Case(s)
Can be useful in use cases that provision VM using cloud-init images.

Currently I use the following approach to building cloud-init based VMs for use in Proxmox.

1. Use the [Packer QEMU builder](https://www.packer.io/docs/builders/qemu.html) to provision a cloud-init image, using Ansible and Shell provisioners.
2. Upload the QEMU image to the Proxmox datastore.
3. Create a VM template in Proxmox using that image.
4. Use [Terraform Proxmox Provider](https://github.com/Telmate/terraform-provider-proxmox) to create VMs in Proxmox based on that template.

Please share your comments on this.
Thanks in advance.

**Comment by harisund** [comment]
I would like to add a +1 to this request.

The image based builder is very convenient when dealing with cloud images. Granted, the qemu builder does a fantastic job, but still it would be nice to have this option available elsewhere.

I had opened [this issue](https://github.com/hashicorp/packer/issues/8521) with the same request, but I can definitely see it adding more value to a hypervisor like proxmox.
