### ISSUE TITLE
Option to skip the image creation

### ISSUE THREAD

**Issue by cah-ankur-singh03** [hashicorp/packer#8668]
Hello Folks,
Can some one please let me know if there is an option in packer to skip/avoid the image creation? 
I have a CI/CD pipeline where I am creating image using packer which works pretty great. 

However i have another requirement where I have to leverage the same pipeline and offload some steps from Concourse worker by moving some heavy lifting to GCP VM where I can use packer to provision a VM and do the heavy lifting but I don't want to get an output of that packer build. Is there a way I can skip image creation and still do the task?

I will really appreciate some feedback/guidance on this thread.

thanks

**Comment by krishicks** [comment]
A solution to this that I've implemented is to wrap the run of `packer build` in a script that:

* removes any ami_users declaration, which prevents copying the AMI
* adds a manifest post-processor if one does not already exist in the packer-template.json
* uses the manifest post-processor output to find the artifacts that were created and uses the appropriate method to delete them

In the case of an amazon-ebs builder, the output is used to delete the AMI and associated snapshot with aws-cli.

I'd love to see this as a feature but it would need to be implemented by the provider as probably only the provider would know how to clean things up.

**Comment by SwampDragons** [comment]
For more context on similar issues opened for other builders, see #7209

**Comment by cah-ankur-singh03** [comment]
@krishicks thanks a lot for your suggestion. I will give it a try and see if that helps :)

**Comment by cah-ankur-singh03** [comment]
@SwampDragons  thanks a lot for pointing me to this thread.
