### ISSUE TITLE
Compress post-process does not compress image

### ISSUE THREAD

**Issue by shogerr** [hashicorp/packer#8680]
I'm not sure what's causing my behavior, but I get no compressed artifact when adding a compress post-process the result is a successful build and a 22kb zip. 

```
{
  "post-processors": [
    [
      {
        "type": "manifest",
        "output": "manifest.json"
      },
      {
        "type": "compress",
        "keep_input_artifact": true,
        "output": "{{user `vm_name`}}.zip"
      }
    ]
  ]
}
```

The builder is `hyperv-iso` and it's a Windows 10 system for both host and guest. Any ideas? Nothing stands out in the output:
```
==> hyperv-iso: Running post-processor: manifest
==> hyperv-iso: Running post-processor: compress
==> hyperv-iso (compress): Zipping machine-xyz.zip
==> hyperv-iso (compress): Archive machine-xyz.zip completed
Build 'hyperv-iso' finished.
```

**Comment by nywilken** [comment]
Hi @shogerr thanks for reaching out. In order for us to best help could you provide the things requested in the issue template; including the simplest Packer configuration and scripts needed to reproduce the bug.

Cheers!

**Comment by shogerr** [comment]
I thought I did, the post processor has been supplied. Closing because I won't have the time to invest in this.
