### ISSUE TITLE
valid_exit_codes has not been implemented on shell-local provisioner

### ISSUE THREAD

**Issue by tsenay** [hashicorp/packer#8683]
#### Overview of the Issue

For shell-local provisioner, the valid_exit_codes option is not working

#### Reproduction Steps

- Create a packer configuration, 
- define a local-shell provisionner with "valid_exit_codes" option. 
- execute packer build
### Packer version

1.4.5

### Simplified Packer Buildfile

[Github detailed
format](https://gist.github.com/tsenay/28717364731cbaa56bbf2f64af1f1529)

### Operating system and Environment details

RedHat 7.6

### Log Fragments and crash.log files
```
1580729053,,ui,error,Error decoding config: 1 error occurred:\n	* unknown configuration key: "valid_exit_codes"\n\n%!(PACKER_COMMA) config is &shell_local.Config{PackerConfig:common.PackerConfig{PackerBuildName:"virtualbox-ovf"%!(PACKER_COMMA) PackerBuilderType:"virtualbox-ovf"%
```
Seems normal because the option has not been implemented for this provisionner. The option is described in packer documentation;

**Comment by nywilken** [comment]
Hi @tsenay I confirmed this issue on Packer 1.4.5 with a slightly modify config. This issue has been fixed in the latest version of packer. Please update to the latest version of Packer and try again. 

```json
  "builders": [
    {
        "type": "null",
        "communicator": "none"

    }
  ],
  "provisioners": [
    {
      "type": "shell-local",
      "valid_exit_codes": [
        0,
        1
      ],
      "inline": ["echo exit code 1", "exit 1"]
    },
    {
      "type": "shell-local",
      "valid_exit_codes": [
        0,
        1
      ],
      "inline": ["echo exit code 0", "exit 0"]
    }
  ]
}
```
## Packer 1.4.5
```
vagrant@debian-9:~$ ./packer --version1.4.5
vagrant@debian-9:~$ ./packer build build.json 
null output will be in this color.

Error decoding config: 1 error occurred:
        * unknown configuration key: "valid_exit_codes"
```

### Packer 1.5.1
```
null: output will be in this color.

==> null: Running local shell script: /tmp/packer-shell457667790
    null: exit code 1
==> null: Running local shell script: /tmp/packer-shell502783852
    null: exit code 0
Build 'null' finished.
```

I'm going to close this issue seeing as it has been fixed in 1.5.1. But if you run into any issues after upgrading please comment and I will reopen the issue.
