### ISSUE TITLE
[Feature Request] Add Proxmox cloud-init drive to the template

### ISSUE THREAD

**Issue by backaf** [hashicorp/packer#8691]
#### Feature Description

We're building Proxmox templates using Packer and we would like the ability to add a cloud-init drive to the template. From what I see this is not currently supported therefore we need to manually add the cloud-init drive after the template has been created.

#### Use Case(s)

Use the Packer created template with the Terraform Proxmox provider to automatically bring up VMs in a Proxmox environment.

This seems to be related to #8660, although that request is a bit different.

**Comment by sticky-note** [comment]
Done with https://github.com/hashicorp/packer/pull/9045

**Comment by nywilken** [comment]
Thanks @sticky-note! 

This feature was released in the v1.5.6 Packer release.
