### ISSUE TITLE
Output show sensitive extra-vars

### ISSUE THREAD

**Issue by stefanocog** [hashicorp/packer#8702]
Packer version: 1.5.1
OS: Ubuntu Linux 18.04

The command packer build show sensitive ```extra-vars``` variables. I use this command:

```packer build -var-file=awsdata.json -var env=${ENV} -var ak=${AWS_ACCESS_KEY} -var sk=${AWS_SECRET_KEY}  -var satis_user=${SATIS_USER} -var satis_password=${SATIS_PASSWORD} web.json```

into ```web.json``` file i have extra arguments:
```
  "provisioners": [
    {
      "type": "ansible-local",
      "playbook_dir": "./{{user `playbook_dir`}}",
      "playbook_file": "./{{user `playbook_dir`}}/playbook-{{user `env`}}.yml",
      "extra_arguments": [ "--extra-vars \"aws_access_key={{user `ak`}} aws_secret_key={{ user `sk`}} satis_user={{ user `satis_user`}} satis_password={{ user `satis_password`}}\"" ]
    }
  ]
```

Output contains:

`--extra-vars "packer_build_name=amazon-ebs packer_builder_type=amazon-ebs packer_http_addr= -o IdentitiesOnly=yes" --extra-vars "aws_access_key=AKIA........... aws_secret_key=KxE28........... satis_user=admin satis_password=dbw......."`

So, only extra-vars are show

**Comment by azr** [comment]
Hey @stefanocog, do you mean that you have `"sensitive-variables": ["satis_password"],` in your conf but it is still displayed ?

Otherwise,  the docs are here https://packer.io/docs/templates/user-variables.html#sensitive-variables ( just in case 🙂 )

**Comment by stefanocog** [comment]
Thank you, i didn't know this feature, great!

**Comment by azr** [comment]
No worries !
