### ISSUE TITLE
amazon-ebs builder: SSH session goes down after aprox. 10 mins and makes the build fail

### ISSUE THREAD

**Issue by sanrodari** [hashicorp/packer#872]
```
packer -v
Packer v0.5.1
```

I'm trying to create an AMI with a long running shell scripts that installs a ruby stack.

The instance type is: `"instance_type": "t1.micro"`.

The script is tested and works well. I can login to the EC2 instance launched to create the AMI and everything looks fine.

After aprox. 10 mins the console with `amazon-ebs:` output freezes (SSH session goes down, I think) and I have to stop the instance through the EC2 Console.

After the instance has stopped, the terminal goes back and this is its output:

```
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: Script exited with non-zero exit status: -1

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Script exited with non-zero exit status: -1

==> Builds finished but no artifacts were created.
```

All the scripts exits with 0. This error message is misleading.

The instance is deleted and I can't build the AMI manually through the EC2 console.

In order to test the assumption that none of the scripts exits with error and also to build the AMI, I have to set a better (non-free tier) instance type which provision sufficiently fast (7 mins. aprox.) to keep the SSH session live:

`"instance_type": "c3.2xlarge"`

```
==> amazon-ebs: Stopping the source instance...
==> amazon-ebs: Waiting for the instance to stop...
==> amazon-ebs: Creating the AMI: ruby-stack-1391543824
    amazon-ebs: AMI: ami-XXXXXXX
==> amazon-ebs: Waiting for AMI to become ready...
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' finished.
```

I've tried this with no luck. https://liangsun.org/posts/how-to-solve-broken-pipe-message-in-ssh-session/

Is there a way to keep the SSH session running in order to build an AMI with a t1.micro?

The total provision with a t1.micro takes aprox. 20 mins.

**Comment by ashishkapil78** [comment]
Hi,
     I am facing same issue. Please anyone tell be solution in detail.

    amazon-ebs: Aborting
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Cleaning up any extra volumes...
==> amazon-ebs: No volumes to clean up, skipping
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: Script exited with non-zero exit status: 1

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Script exited with non-zero exit status: 1

==> Builds finished but no artifacts were created.

**Comment by mwhooker** [comment]
@ashishkapil78 I'm not sure that's the same issue from this ticket. The word "Aborting" doesn't appear anywhere in the packer source code. Could you open a new ticket with steps to reproduce? thanks!
