### ISSUE TITLE
boot_wait = 0s is ignored

### ISSUE THREAD

**Issue by nafmo** [hashicorp/packer#8723]
### Overview of the Issue

A change in the configuration parsing in release 1.4.5 causes a `boot_wait` value of `0s` to be ignored (zero is being interpreted as unset), and being replaced by the default value (10 seconds).

#### Reproduction Steps

In the builder configuration, set `"boot_wait": "0s"`.

### Packer version

This was introduced in [commit 81932922](https://github.com/hashicorp/packer/commit/819329228a8dbf82908dc8ccf7c48ab53bfeb2f6#diff-eed61e47b807548499429ebc8afb15bb), which was first included in Packer version 1.4.5. Versions before this accepted `"0s"` as a zero boot wait delay.

**Comment by azr** [comment]
Hey @nafmo, thanks for reporting, this is a limitation for go durations where the zero value is also the unset value. Would using something like `"boot_wait": "-1s"` be a solution for you ? In go negative durations make the sleep return immediately.

One other solution for this would be to make of these pointers.
