### ISSUE TITLE
Packer 1.5.2 "Error unquoting identity file: invalid syntax" in Vagrant/Virtualbox provider

### ISSUE THREAD

**Issue by jholloway7** [hashicorp/packer#8736]
#### Overview of the Issue

I upgraded packer to 1.5.2 this afternoon and started getting an error in my vagrant build related to "unquoting identity file".  

I'm able to abort the cleanup and leave the box running.  I'm able to successfully SSH to the box with `vagrant ssh`.    I've tried wiping my ~/.vagrant.d folder and starting over with new keys, but to no avail.  I'm going to try to step down my versions until I get back to what I had before and also to see where it started happening, but I'm fighting with homebrew trying to figure out how to do that.   I'll update the issue if I can figure it out.

#### Reproduction Steps

Build a simple vagrant box using virtualbox provider. I'm not sure the `source_path` matters as the error seems to happen before it actually tries to SSH to the box.

### Packer version
1.5.2

### Simplified Packer Buildfile

```
{
  "builders": [
    {
      "box_name": "my-box-name",
      "type": "vagrant",
      "provider": "virtualbox",
      "source_path": "ubuntu/bionic64",
      "output_dir": "build/vagrant",
      "communicator": "ssh"
    }
  ]
}
```
### Operating system and Environment details

Mac OS X (Catalina)
Vagrant 2.2.7
Virtualbox 6.1.2 r135662

### Log Fragments and crash.log files

```
2020/02/13 14:32:32 packer-builder-vagrant plugin: Calling Vagrant CLI: []string{"ssh-config", "source"}
2020/02/13 14:32:34 packer-builder-vagrant plugin: [vagrant driver] stdout: Host source
2020/02/13 14:32:34 packer-builder-vagrant plugin: [vagrant driver] stdout:   HostName 127.0.0.1
2020/02/13 14:32:34 packer-builder-vagrant plugin: [vagrant driver] stdout:   User vagrant
2020/02/13 14:32:34 packer-builder-vagrant plugin: [vagrant driver] stdout:   Port 2200
2020/02/13 14:32:34 packer-builder-vagrant plugin: [vagrant driver] stdout:   UserKnownHostsFile /dev/null
2020/02/13 14:32:34 packer-builder-vagrant plugin: [vagrant driver] stdout:   StrictHostKeyChecking no
2020/02/13 14:32:34 packer-builder-vagrant plugin: [vagrant driver] stdout:   PasswordAuthentication no
2020/02/13 14:32:34 packer-builder-vagrant plugin: [vagrant driver] stdout:   IdentityFile /Users/joe/.vagrant.d/insecure_private_key
2020/02/13 14:32:34 packer-builder-vagrant plugin: [vagrant driver] stdout:   IdentitiesOnly yes
2020/02/13 14:32:34 packer-builder-vagrant plugin: [vagrant driver] stdout:   LogLevel FATAL
2020/02/13 14:32:34 packer-builder-vagrant plugin: [vagrant driver] stdout:
2020/02/13 14:32:34 packer-builder-vagrant plugin: identity file is /Users/joe/.vagrant.d/insecure_private_key
2020/02/13 14:32:34 packer-builder-vagrant plugin: Removing quotes from identity file
2020/02/13 14:32:34 packer-builder-vagrant plugin: Error unquoting identity file: invalid syntax
==> vagrant: Using ssh communicator to connect: 127.0.0.1
2020/02/13 14:32:34 packer-builder-vagrant plugin: [INFO] Waiting for SSH, up to timeout: 10m0s
==> vagrant: Waiting for SSH to become available...
2020/02/13 14:32:34 packer-builder-vagrant plugin: [INFO] Attempting SSH connection to 127.0.0.1:2200...
2020/02/13 14:32:34 packer-builder-vagrant plugin: [DEBUG] reconnecting to TCP connection for SSH
2020/02/13 14:32:34 packer-builder-vagrant plugin: [DEBUG] handshaking with SSH
2020/02/13 14:32:34 packer-builder-vagrant plugin: [DEBUG] SSH handshake err: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
2020/02/13 14:32:34 packer-builder-vagrant plugin: [DEBUG] Detected authentication error. Increasing handshake attempts.
==> vagrant: Error waiting for SSH: Packer experienced an authentication error when trying to connect via SSH. This can happen if your username/password are wrong. You may want to double-check your credentials as part of your debugging process. original error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
==> vagrant: Packer experienced an authentication error when trying to connect via SSH. This can happen if your username/password are wrong. You may want to double-check your credentials as part of your debugging process. original error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
==> vagrant: Step "StepConnect" failed

```

Thanks

**Comment by jholloway7** [comment]
I stepped down to 1.5.1 and confirmed that the error does not happen with that version.  For fun, I removed homebrew out of the equation and downloaded 1.5.2 directly from the primary link and the issue was still present.

**Comment by SwampDragons** [comment]
Thanks, I'll try to take a look at this when I get a chance.

**Comment by zimmertr** [comment]
I can confirm this is happening to me as well on 1.5.4.

**Comment by zimmertr** [comment]
For those who want to downgrade, it appears that Brew only has the newest version available and Packer's website only lists a download link for the most current version. But the URL can be manually changed to grab the dmg.

`https://releases.hashicorp.com/packer/1.5.1/packer_1.5.1_darwin_amd64.zip`

**Comment by rhanneken** [comment]
I think the problem is due to [this change](https://github.com/hashicorp/packer/pull/8605). When the code parses [the line for `IdentityFile`](https://man.openbsd.org/ssh_config#IdentityFile) in the SSH config (in the case of the Vagrant builder, the output of running `vagrant ssh-config`), [the Packer code now filters the value through `strconv.Unquote`](https://github.com/hashicorp/packer/pull/8605/files#diff-2543393cb88e8bb6538e34266a26e91dR59). However, [the documentation for `strconv.Unquote`](https://golang.org/pkg/strconv/#Unquote) says that if its input isn't quoted, that results in an error (expand the "Example" section to see what I mean). In the context of the Packer code, I think that means `sshConfig.IdentityFile` doesn't get set, which means the SSH client can't connect to the server.

**Comment by SwampDragons** [comment]
Thanks for tracking this down! Do you want to make a pull request to fix it, or would you rather I did?

**Comment by SwampDragons** [comment]
I made a PR :) https://github.com/hashicorp/packer/pull/8826
