### ISSUE TITLE
panic: interface conversion: object.NetworkReference is *object.DistributedVirtualPortgroup, not *object.Network

### ISSUE THREAD

**Issue by packerwhathappened** [hashicorp/packer#8743]
#### Overview of the Issue

Creating vsphere-clone of existing template made by packer vsphere-iso previously.  App panics immediately on step 1: Cloning VM ... with unexpected EOF.

#### Reproduction Steps

packer validate XXX 
packer build XXX

### Packer version

Packer v1.5.2

### Simplified Packer Buildfile

{
  "builders": [
    {
      "type": "vsphere-clone",
      "cluster": "{{ user `cluster` }}",
      "convert_to_template": "true",
      "datastore": "{{ user `datastore` }}",
      "insecure_connection": "true",
      "network": "{{ user `vsphere_network` }}",
      "username": "{{ user `vsphere_user` }}",
      "password": "{{ user `vsphere_password` }}",
      "ram": "1024",
      "resource_pool": "{{ user `resource_pool` }}",
      "vcenter_server": "{{ user `vsphere_server` }}",
      "vm_name": "{{ user `build_name` }}",
      "communicator": "ssh",
      "cpus": "1",
      "disk_size": "30720",
      "pause_before_connecting": "2m",
      "shutdown_command": "echo 'packer' | sudo -S shutdown -P now",
      "ssh_password": "{{ user `packer_password` }}",
      "ssh_username": "packer",
      "template": "{{ user `vmware_template` }}"
    }
  ],
yada, yada, yada

### Operating system and Environment details

VMWare RHEL 7.6

### Log Fragments and crash.log files

Template validated successfully.
vsphere-clone: output will be in this color.

==> vsphere-clone: Cloning VM...
Build 'vsphere-clone' errored: unexpected EOF

==> Some builds didn't complete successfully and had errors:
--> vsphere-clone: unexpected EOF

==> Builds finished but no artifacts were created.
panic: interface conversion: object.NetworkReference is *object.DistributedVirtualPortgroup, not *object.Network
2020/02/14 10:35:43 packer.1.5.2 plugin:
2020/02/14 10:35:43 packer.1.5.2 plugin: goroutine 161 [running]:
...
2020/02/14 10:35:43 [INFO] (telemetry) ending vsphere-clone
2020/02/14 10:35:43 ui error: Build 'vsphere-clone' errored: unexpected EOF
2020/02/14 10:35:43 /usr/local/bin/packer.1.5.2: plugin process exited
2020/02/14 10:35:43 machine readable: error-count []string{"1"}
2020/02/14 10:35:43 ui error:

**Comment by nywilken** [comment]
Good to know, thanks! We'll try to take a look for the next release

**Comment by jhawk28** [comment]
You dropped the relevant details (like line numbers on the panic's stack trace), but I suspect the panic is coming from here: https://github.com/hashicorp/packer/blob/master/builder/vsphere/driver/network.go#L27

**Comment by packerwhathappened** [comment]
[crash.log](https://github.com/hashicorp/packer/files/4214306/crash.log)

Recreating for comparison

**Comment by jhawk28** [comment]
Can see if my patch fixes your issue?

**Comment by packerwhathappened** [comment]
[crash.1.5.4.log](https://github.com/hashicorp/packer/files/4214334/crash.1.5.4.log)
Similar crash with 1.5.4 - investigating the changes.

***
==> Builds finished but no artifacts were created.
panic: interface conversion: object.NetworkReference is *object.DistributedVirtualPortgroup, not *object.Network
2020/02/17 09:47:18 packer.1.5.4 plugin:
2020/02/17 09:47:18 packer.1.5.4 plugin: goroutine 16 [running]:
***

**Comment by jhawk28** [comment]
Here is the result circleci build with my fix: https://34731-8966356-gh.circle-artifacts.com/0/packer_linux_amd64.zip

**Comment by packerwhathappened** [comment]
Good news.  'network' is accepted on build and functions with provisioners as well.   Working as expected.

**Comment by andrewjkeith** [comment]
So I re-tried my build with v1.5.5 and I am no longer getting a crash, but still getting an error. (See my duplicate issue, https://github.com/hashicorp/packer/issues/8885)
```
vsphere-clone: output will be in this color.

==> vsphere-clone: Cloning VM...
Build 'vsphere-clone' errored: no network adapter device found
```
I suspect that I'm using and invalid network object, but the docs dont say what is allowed.

**Comment by jhawk28** [comment]
try setting the network_card parameter to "e1000" or "vmxnet3".


Joshua
On 3/27/2020 5:20:11 PM, andrewjkeith <notifications@github.com> wrote:
So I re-tried my build with v1.5.5 and I am no longer getting a crash, but still getting an error. (See my duplicate issue, #8885 [https://github.com/hashicorp/packer/issues/8885])
vsphere-clone: output will be in this color. ==> vsphere-clone: Cloning VM... Build 'vsphere-clone' errored: no network adapter device found
I suspect that I'm using and invalid network object, but the docs dont say what is allowed.

**Comment by andrewjkeith** [comment]
If I add `"network_card":   "vmxnet3"` it says unknown configuration key.

**Comment by jhawk28** [comment]
try using e1000. That would have been the default if you didn't set anything.

Joshua
On 3/27/2020 6:13:48 PM, andrewjkeith <notifications@github.com> wrote:
If I add "network_card": "vmxnet3" it says unknown configuration key.

**Comment by jhawk28** [comment]
I'm thinking of the vsphere-iso plugin. The clone one has different logic/fields.

Joshua
On 3/27/2020 6:19:06 PM, Joshua Foster <jhawk28@gmail.com> wrote:
try using e1000. That would have been the default if you didn't set anything.

Joshua
On 3/27/2020 6:13:48 PM, andrewjkeith <notifications@github.com> wrote:
If I add "network_card": "vmxnet3" it says unknown configuration key.

**Comment by jhawk28** [comment]
Here is where the error is coming from:

func findNetworkAdapter(l object.VirtualDeviceList) (types.BaseVirtualEthernetCard, error) {
c := l.SelectByType((*types.VirtualEthernetCard)(nil))
if len(c) == 0 {
return nil, errors.New("no network adapter device found")
}

return c[0].(types.BaseVirtualEthernetCard), nil
}
I suspect that you have a different kind of card on your VM. Can you show what vsphere has on your devices settings?

Joshua
On 3/27/2020 5:20:11 PM, andrewjkeith <notifications@github.com> wrote:
So I re-tried my build with v1.5.5 and I am no longer getting a crash, but still getting an error. (See my duplicate issue, #8885 [https://github.com/hashicorp/packer/issues/8885])
vsphere-clone: output will be in this color. ==> vsphere-clone: Cloning VM... Build 'vsphere-clone' errored: no network adapter device found
I suspect that I'm using and invalid network object, but the docs dont say what is allowed.

**Comment by jhawk28** [comment]
Showing the output of govc device.ls could also useful: https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#devicels [https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#devicels]

Joshua
On 3/27/2020 5:20:11 PM, andrewjkeith <notifications@github.com> wrote:
So I re-tried my build with v1.5.5 and I am no longer getting a crash, but still getting an error. (See my duplicate issue, #8885 [https://github.com/hashicorp/packer/issues/8885])
vsphere-clone: output will be in this color. ==> vsphere-clone: Cloning VM... Build 'vsphere-clone' errored: no network adapter device found
I suspect that I'm using and invalid network object, but the docs dont say what is allowed.

**Comment by andrewjkeith** [comment]
Here's the output for a random VM in the same vCenter:
```
$ govc device.ls -vm JDSEAN08
ide-200       VirtualIDEController       IDE 0
ide-201       VirtualIDEController       IDE 1
ps2-300       VirtualPS2Controller       PS2 controller 0
pci-100       VirtualPCIController       PCI controller 0
sio-400       VirtualSIOController       SIO controller 0
keyboard-600  VirtualKeyboard            Keyboard
pointing-700  VirtualPointingDevice      Pointing device; Device
video-500     VirtualMachineVideoCard    Video card
vmci-12000    VirtualMachineVMCIDevice   Device on the virtual machine PCI bus that provides support for the virtual machine communication interface
pvscsi-1000   ParaVirtualSCSIController  VMware paravirtual SCSI
disk-1000-0   VirtualDisk                104,857,600 KB
disk-1000-1   VirtualDisk                83,886,080 KB
ethernet-0    VirtualVmxnet3             DVSwitch: 50 01 73 e8 9e 0b 48 29-40 d9 e7 e9 39 18 70 01
```

**Comment by jhawk28** [comment]
You should be able to do a device.ls on the specific template/vm that you are using to clone from. Feel free to censor anything if you think its sensitive.

Lets see if the device.info gives any hints as to what is wrong...
govc device.info -vm=template_linux_centos_7_0_x86_64 ethernet-0


Joshua
On 3/27/2020 7:00:23 PM, andrewjkeith <notifications@github.com> wrote:
Here's the output for a random VM in the same vCenter:
$ govc device.ls -vm JDSEAN08 ide-200 VirtualIDEController IDE 0 ide-201 VirtualIDEController IDE 1 ps2-300 VirtualPS2Controller PS2 controller 0 pci-100 VirtualPCIController PCI controller 0 sio-400 VirtualSIOController SIO controller 0 keyboard-600 VirtualKeyboard Keyboard pointing-700 VirtualPointingDevice Pointing device; Device video-500 VirtualMachineVideoCard Video card vmci-12000 VirtualMachineVMCIDevice Device on the virtual machine PCI bus that provides support for the virtual machine communication interface pvscsi-1000 ParaVirtualSCSIController VMware paravirtual SCSI disk-1000-0 VirtualDisk 104,857,600 KB disk-1000-1 VirtualDisk 83,886,080 KB ethernet-0 VirtualVmxnet3 DVSwitch: 50 01 73 e8 9e 0b 48 29-40 d9 e7 e9 39 18 70 01
