### ISSUE TITLE
Add VMID (GUID) to Hyperv box.xml

### ISSUE THREAD

**Issue by santhoshganesan** [hashicorp/packer#8767]
#### Feature Description
.
If we have the VMID (GUID) in the box.xml its easy to get the names into the variable, GUID is one useful variable inorder to import the VM

#### Use Case(s)

It gives options to load the vm on to the hyperv

**Comment by SwampDragons** [comment]
This seems fine to me. I'm not sure when I'll get a chance to implement this, but if a community member wants to try, the code for creating box.xml is here: https://github.com/hashicorp/packer/blob/master/common/powershell/hyperv/hyperv.go#L663-L691
