### ISSUE TITLE
Crash when building virtualbox-iso with HCL2

### ISSUE THREAD

**Issue by kylelaker** [hashicorp/packer#8779]
#### Overview of the Issue

When I try to build, I get a crash dump and `packer` asked me to open an issue.

#### Reproduction Steps

Run the following in a directory with the below Buildfile and packer executable.

```
packer build .
```

### Packer version

```
$ ./packer version
Packer v1.5.4
```

### Simplified Packer Buildfile

https://gist.github.com/kylelaker/81bf6e470763b9e942e5479c573d98a6

### Operating system and Environment details

ArchLinux AMD64 using packer downloaded from https://packer.io/downloads.html

### Log Fragments and crash.log files

https://gist.github.com/kylelaker/560865c2f02500b8b1bb0d75a47f5da3

**Comment by kylelaker** [comment]
This _might_ be a duplicate of #8730?

**Comment by azr** [comment]
Hey @kylelaker, yes this is the same cause and I am currently working on fixing this; hopefully this will be solved soon ! To 'fix this' you can give these variables a default value or set it in the command line. I'm going to close this issue in favor of #8730.
