### ISSUE TITLE
Support for custom string in place of random string for azure-arm resource names

### ISSUE THREAD

**Issue by KlutzyBubbles** [hashicorp/packer#8780]
#### Feature Description

Add support to specify a custom random string for packer resources created with the builder azure-arm.

Default back to the random string (pkrvm$RANDOM$) if none is provided

#### Use Case(s)

Due to policy constrains some extra steps need to be made to packer resources (such as key vault for example) so without the name of the resources it is impossible to do so.

A simple type lookup in a resource group wouldn't work as we have multiple packer builds running at once.

**Comment by nywilken** [comment]
Hello :wave: this feature has been merged in #9028 and will be part of the v1.5.6 Packer release. If you would like to give it a try before the actual release it is available in the  [nightly Packer releases](https://github.com/hashicorp/packer/releases/tag/nightly).
