### ISSUE TITLE
Cannot load HCL vars files with `-var-file` argument

### ISSUE THREAD

**Issue by mechastorm** [hashicorp/packer#8781]
#### Overview of the Issue

Can't seem to load `.pkrvars.hcl` files with the `-var-file` argument. I am not sure if it a bug with packer or the way I am using packer.

#### Reproduction Steps

I run the command
```
packer build -var-file=env/networking.pkrvars.hcl .
```

The contents of `env/networking.pkrvars.hcl`

```
ssh_username = "ubuntu"
```

I get the following error instead

```
invalid value "env/networking.pkrvars.hcl" for flag -var-file: Error reading variables in 'env/networking.pkrvars.hcl': invalid character 's' looking for beginning of value
```

### Packer version

1.5.4

### Operating system and Environment details

mac OS X 10.13.6

**Comment by azr** [comment]
Hello @mechastorm, thanks for opening, this is not supported yet. Currently to use var files you need to put them in the same folder as the build files you are using and to run `packer build folder/`, packer will detect var files.

Currently passing the `var-file` option is making packer use JSON variables which is not exactly what we need.

**Comment by jasonberanek** [comment]
@azr I see in #8540 you mentioned that the documentation gets updated once per release, which may be why the current documentation is misleading; however is there a way to update docs to make the level of HCL support clearer?  The current documentation gives the impression the build is fully supported for existing features, which is not the case.

I'd think for users, something like "we are implementing" or similar would make it clearer that this is a work in progress, and help people who are less edge adopters to avoid getting frustrated with Packer during the transition.

**Comment by drakedevel** [comment]
Yeah, the documentation at https://packer.io/docs/configuration/from-1.5/variables.html#variable-definitions-pkrvars-hcl-files doesn't really line up with the behavior right now.

In addition to not supporting HCL variable files as was already mentioned, JSON variable files suffer from #8748 (you have to double-quote strings to work around), so the example JSON file in the docs doesn't work, either.

**Comment by SwampDragons** [comment]
Thanks for the notes -- I'll try to get a docs fix in this week so that current behavior is properly reflected on the website.

**Comment by azr** [comment]
Hey here, I've been re-reading the docs and sorry, the docs are a bit ahead of the features and should not have been mentioning the `-var-file` option.  I'm working on making this feature/fix happen right now.
