### ISSUE TITLE
 HCL - Unsupported argument `pause_before` not valid in shell provisioner

### ISSUE THREAD

**Issue by mechastorm** [hashicorp/packer#8783]
#### Overview of the Issue

Cannot use `pause_before` in the HCL version of the build provisioner shell

The error I get is

```
Error: Unsupported argument

  on build.pkr.hcl line xx, in build:
  xx:     pause_before = 5

An argument named "pause_before" is not expected here.

```

#### Reproduction Steps

```
build {
  sources = [
    # there can be multiple sources per build
    "source.amazon-ebs.ubuntu"
  ]

  provisioner "shell" {
    inline = [
      "echo 'Testing SSH Access ...'"
    ]
    pause_before = 5
  }
}
```

### Packer version

packer 1.5.4

**Comment by azr** [comment]
Hey @mechastorm, thanks for opening, yes, the 'common fields' are currently not working in Packer, we plan on supporting them soon, common fields:
https://github.com/hashicorp/packer/blob/819329228a8dbf82908dc8ccf7c48ab53bfeb2f6/template/template.go#L137-L145

https://github.com/hashicorp/packer/blob/819329228a8dbf82908dc8ccf7c48ab53bfeb2f6/template/template.go#L101-L109

I recently did this for the name field of provisioners and post-processors here: 2d1a67c6cb0e5ef8728238fd3d730293d87650ef, I expect the pause_before option to be quite similar to this commit. PRs are welcome 🙂 !

**Comment by sylviamoss** [comment]
Hey there!! This is was already fixed by https://github.com/hashicorp/packer/pull/9061 and will go out in the next release 🎉 
I'm closing this issue for now. Thanks for opening 👍
