### ISSUE TITLE
Packer v1.5.4 fails with SSL: UNKNOWN_PROTOCOL when it checks for ipv6 address 

### ISSUE THREAD

**Issue by WeekendsBull** [hashicorp/packer#8790]
I'm currently using Packer v1.5.2-dev version to make the ec2 Windows 2012r2 AMI build working. 
I have tried to use Packer V1.5.4 but it fails due to the unknown protocol error 

#### error logs shows as below

amzn-win2012r2-sysprep-base: Using module file /usr/lib/python2.7/site-packages/ansible/modules/windows/win_chocolatey.ps1
amzn-win2012r2-sysprep-base: <127.0.0.1> ESTABLISH WINRM CONNECTION FOR USER: Administrator on PORT 35358 TO 127.0.0.1==> amzn-win2012r2-sysprep-base: failed to handshake
amzn-win2012r2-sysprep-base: checking if winrm_host 127.0.0.1 is an IPv6 address 
amzn-win2012r2-sysprep-base: fatal: [default]: UNREACHABLE! => {  amzn-win2012r2-sysprep-base: "changed": false,  amzn-win2012r2-sysprep-base: "msg": "ssl: HTTPSConnectionPool(host='127.0.0.1', port=35358): Max retries exceeded with url: /wsman (Caused by SSLError(SSLError(1, u'[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:727)'),))",
amzn-win2012r2-sysprep-base: "unreachable": true  amzn-win2012r2-sysprep-base: }

#### I am creating a docker container container in jenkins 

1. [Docker file ](https://gist.github.com/WeekendsBull/e231ce720677b2e85082c2485def9b62)
2. The docker container runs a shell file to call [Packer template ](https://gist.github.com/WeekendsBull/cf9a90767163e37265f20725b6165b3f)
  
### Packer version

From Packer V 1.5.4 (currently works on Packer v1.5.2-dev)
 
### Operating system and Environment details

AWS Ec2 windows 2012r2 Latest version

### Log Fragments and crash.log files

[Full logs](https://gist.github.com/WeekendsBull/8f98092f183ccd7da09cbe5caa0e5423) 
 
Here is my environment variables in a shell file to call packer template. 
      export AWS_POLL_DELAY_SECONDS=180
      export AWS_MAX_ATTEMPTS=40 
      export AWS_PROFILE=${AWS_PROFILE}  
      export AWS_DEFAULT_REGION=${region}  
      export ANSIBLE_HOST_KEY_CHECKING=False

Here is a log file when I build successfully from [Packer v1.5.2-dev](https://gist.github.com/WeekendsBull/10e466606561f3e7ba1ce757a328cd22)

Note: please do not kill the link for packer v1.5.2-dev

**Comment by WeekendsBull** [comment]
I have tested out in packer v1.4.3, v1.4.4, v1.4.5, v.1.4.6, v1.5.0, v1.5.1, v1.5.2, and v1.5.4. Windows AMI doesn't build correctly not with the same reason but so far only v1.5.2-dev is working.

**Comment by SwampDragons** [comment]
We don't have the power to force Circle CI to keep old artifacts so if that dev binary is important to you, please cache it locally. 

We will try to investigate why it is working for you in that binary, and not with anything else.

**Comment by SwampDragons** [comment]
I can't tell from the log specifically which commit that dev binary is on. Which PR did it come from?

**Comment by WeekendsBull** [comment]
@SwampDragons Thank you so much and can't seems to find the original post where I got it from and let me spend time to dig some more. 

Meanwhile, I wonder if the issue related to https://github.com/hashicorp/packer/issues/8705
In that post, there is a work around for updating the registry key and attended.xml to resolve. 
I will try to see if it helps me to resolve as well.

Also, I will try the connection.py shown here to see if it helps to resolve the issue with Ansible as well @ https://github.com/hashicorp/packer/issues/7979 since I wasn't able to use any Ansible version above v2.8 due to the connectivity. 

Keep you posted if I find the original post and working version with the released latest packer.

**Comment by WeekendsBull** [comment]
@SwampDragons, I have a new [logs](https://gist.github.com/WeekendsBull/c5ce591e979e01c43d0cb0dd9fd1af14) showing that the packer lost the connectivity after updating the 

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters path doesn't exist and create HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters. Updating it's value to 000000ff

Per MS documentation [here](https://support.microsoft.com/en-us/help/929852/guidance-for-configuring-ipv6-in-windows-for-advanced-users), 0x20 is the recommended instead of disabling it.  
 
However, both cases are not but hanging..

**Comment by WeekendsBull** [comment]
@SwampDragons is there any recent debug build I could test out?

**Comment by SwampDragons** [comment]
There's a recent nightly of the master branch so you can at least verify if it's still on master for us: https://github.com/hashicorp/packer/releases/tag/nightly

I haven't had a chance to look into this. 

Did you ever figure out what patch it started failing on?

**Comment by WeekendsBull** [comment]
@SwampDragons, here the [post](https://github.com/hashicorp/packer/pull/8625) where I discussed with you and you got me https://circleci.com/gh/hashicorp/packer/29969#artifacts/containers/0

**Comment by SwampDragons** [comment]
Thanks.
