### ISSUE TITLE
vsphere post-processor fails to upload using ovftool

### ISSUE THREAD

**Issue by spawnia** [hashicorp/packer#8796]
#### Overview of the Issue

Related to https://github.com/hashicorp/packer/issues/3878, maybe https://github.com/hashicorp/packer/issues/4179

I am able to build an OVF file on a remote ESXI host successfully, but running the `vsphere` post-processer fails.

However, when running ovftool manually using Packers log output, i am able to run it successfully. The only part that i do not copy 1-1 is the password, since it is masked in the output.

#### Reproduction Steps

1. Build an OVF using the `vmware-iso` builder
1. Use the `vsphere` post-processor to upload it to a vCenter

### Packer version

`v1.4.5`

### Simplified Packer Buildfile

```json
{
  "builders": [
    {
      "type": "vmware-iso",
      ...
    }
  ],
  "post-processors": [
    [
      {
        "type": "vsphere",
        "host": "some123.company.local",
        "cluster": "COMPANY-Cluster",
        "datacenter": "COMPANY",
        "datastore": "R5_HDD_1TB_V0",
        "username": "user@company.local",
        "password": "Pw123!foo",
        "vm_name": "centos_8",
        "vm_folder": "/templates",
        "keep_input_artifact": true,
        "insecure": true,
        "overwrite": true
      },
      {
        "type": "vsphere-template",
        ...
      }
    ]
  ]
}
```

I obfuscated the details but used the same special characters. I suspect escaping might play a role in this.

### Operating system and Environment details

Running packer on CentOS 7 against vSphere 6.0.0

### Log Fragments and crash.log files

```

```

**Comment by SwampDragons** [comment]
I think the logs didn't load properly -- can you add them to a gist so we can investigate?

Thanks!

**Comment by spawnia** [comment]
@SwampDragons thanks for the quick response. I can't seem to reproduce the error, not sure what changed inbetween. Closing this for now.

On a side-note: Debugging errors related to the `ovftool` is a particularly painful process, as the error messages are not bubbled up: https://github.com/hashicorp/packer/issues/6923
