### ISSUE TITLE
Wrong endpoint when use chroot in AzureChinaCloud 

### ISSUE THREAD

**Issue by bg2s0r** [hashicorp/packer#8806]
#### Overview of the Issue

I set the `"cloud_environment_name":` `"china"` in my builders, but packer still request the wrong ResourceManagerEndpoint

I can get token when I do this

curl 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https://management.chinacloudapi.cn/' -H Metadata:true

### Packer version

tested most versions

### Operating system and Environment details

Ubuntu 18.04 amd64

### Log Fragments and crash.log files

Build 'azure-chroot' errored: error retieving latest version of "credativ:Debian:9:latest": compute.VirtualMachineImagesClient#List: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="SubscriptionNotFound" Message="The subscription 'dc6f24f5-ff36-4029-b603-ddb144490348' could not be found."

**Comment by SwampDragons** [comment]
Thanks for opening an issue -- to help you, we really do need the things requested in the issue template: 

- *Full* debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a gist https://gist.github.com
- The _simplest complete example template and scripts_ needed to reproduce the bug.
  Include these in your gist https://gist.github.com
