### ISSUE TITLE
Feature Request: Allow error provisioner to abort cleanup or run script on abort

### ISSUE THREAD

**Issue by Quantumplation** [hashicorp/packer#8814]
#### Feature Description

Right now, it is impossible to combine the error-cleanup-provisioner and on-error=abort settings.

Either of the following two features would be useful:

 - The ability for the error-cleanup-provisioner to indicate that the EC2 instance should not be terminated
 - An abort-cleanup-provisioner similar to error-cleanup-provisioner, which runs in the case of an abort according to on-error=abort

#### Use Case(s)

We're using Packer to build a common development environment for use by people within our company.  Given our microservice architecture, this provisioning can fail if a team has published a version that doesn't work on this development environment.  On those errors, we'd like to:
 - abort the build, so that the machine stays alive and debuggable
 - collect error logs and send them to the team whose tests failed, along with the IP of the machine to connect to

The only way we can find to keep the machine alive is to use the -on-error=abort flag when running packer.

However, when specifying that flag, the error-cleanup-provisioner doesn't run, so we can't run the script which collects error logs and sends them to the appropriate team.

Without a solution to this, we'll be forced to put the logic in the Groovy script describing the jenkins job, which spreads our logic across more locations/languages and makes it more difficult to understand.

Also, I maybe be misunderstanding how some of these features work, I'm pretty new to Packer, so if there's an alternative solution, do let me know!

**Comment by awilkins** [comment]
If you're expanding `-on-error` ... I'd love `-on-error=shell` :-)

Would be immensely convenient while developing provisioners if you could just drop into the shell the builder is using when it fails...
