### ISSUE TITLE
Ansible Collections Support

### ISSUE THREAD

**Issue by sbaerlocher** [hashicorp/packer#8821]
Support of Ansible Collection via Galaxy File file to install.

#### Feature Description

Ansible now supports the possibility to combine the roles in a collection, to install it via ansible galaxy file it needs another ansible-galaxy[1] command. 

#### Use Case(s)

Possibility to specify a bool in which you can indicate if there is an Ansible Collection in the file and then run `ansible-galaxy role install -r requirements.yml` and `ansible-galaxy collection install -r requirements.yml`. If the bool is false or not present, he should only run `ansible-galaxy role install -r requirements.yml`.

[1] https://docs.ansible.com/ansible/latest/user_guide/collections_using.html#install-multiple-collections-with-a-requirements-file

**Comment by eddwardo** [comment]
Is there a workaround for it right now?
Maybe changing the `galaxy-command` would help? https://www.packer.io/docs/provisioners/ansible/#galaxy_command

**Comment by sbaerlocher** [comment]
Yes, there is a workournd about shell-local. See: https://github.com/maschin/template/blob/master/templates/10/Enterprise.json#L151

But I think it would be nice if it would be integrated like Roles.

**Comment by SwampDragons** [comment]
I agree this would be a nice addition.  The Ansible provisioner is one of our community-supported provisioners, which means that the HashiCorp maintainers don't spend much engineering time on it. So the best way to see this happen within a reasonable time frame is to open a PR.  I'll gladly give support and pointers if you're interested in working on it.

**Comment by artis3n** [comment]
I haven't worked with a ton of Go lately but if that is all right I'd be interested in giving a PR a shot. Pointers would be very welcome :ok_hand: 

Looks like we'd need to update https://github.com/hashicorp/packer/blob/master/provisioner/ansible/provisioner.go#L623, add a `config.CollectionsPath`, and then `exec` the command.

Confused what https://github.com/hashicorp/packer/blob/master/provisioner/ansible/provisioner.go#L649 section is doing with the `sync.WaitGroup()`. Waiting for `stdout` and `stderr` to both be populated + read by waiting for their channels to close?

Don't see where the existing roles installation is tested in https://github.com/hashicorp/packer/blob/master/provisioner/ansible/provisioner_test.go, hoping I can re-use some existing tests.

**Comment by SwampDragons** [comment]
Yeah I think you're on the right track there. You're right about the wait groups; ideally you won't have to mess with those at all. 

The ansible provisioner isn't very well tested so you may be out of luck on having something ready-made to copy/paste. At a minimum we can add a unit test to "prepare" to make sure the config is parsed properly.

**Comment by artis3n** [comment]
Happened to catch the notification right away. I'll take a crack at it this weekend and put up a WIP PR

**Comment by sbaerlocher** [comment]
@artis3n Thanks for the development.
