### ISSUE TITLE
vsphere builders acceptance tests

### ISSUE THREAD

**Issue by jhawk28** [hashicorp/packer#8841]
The acceptance tests for the vsphere builders seem to be in a semi broken state. 

The first issue that I see is that the host and vcenter connections are set statically. They should probably be done using environment variables like the username and password. We probably want a function that returns the connection information so that it can be used in all the acceptance test. Currently, there are a number of places that just duplicate the retrieval of the username and password from environment variables.

The second issue is that they seem to be disabled in some places. Example: vsphere/driver/datastore_acc_test.go

I have looked over the https://github.com/hashicorp/packer/blob/master/.github/CONTRIBUTING.md#running-acceptance-tests and I need to review what the acceptance tests are doing before running them against my own infrastructure.  Does packer have some vsphere infrastructure to run the acceptance tests before release?

We also need to add acceptance tests for the new capabilities such as multiple disks, multiple NICs, and OVF export.

**Comment by SwampDragons** [comment]
Thanks! this is something I'm currently working on :)

**Comment by SwampDragons** [comment]
sorry, to clarify: we don't currently have Vsphere infrastructure, and my current project is getting some spun up so we can do acceptance testing; once I have the infrastructure spun up I'll be updating the acceptance tests to actually work against it.

**Comment by jhawk28** [comment]
anything I can do to help? or should I just be patient...

**Comment by SwampDragons** [comment]
I've got it but I do appreciate the offer :)

**Comment by jhawk28** [comment]
Just a note: govmomi provides a mock API endpoint for testing: https://github.com/vmware/govmomi/tree/master/vcsim

**Comment by sylviamoss** [comment]
I'll work on this and try to write some tests using the `vcsim` mock

**Comment by sylviamoss** [comment]
I'm going to close this issue because of https://github.com/hashicorp/packer/issues/9851
