### ISSUE TITLE
OCI Government Region Fails

### ISSUE THREAD

**Issue by twmcelroy** [hashicorp/packer#8842]
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue
I am working with Packer and using Oracle Government Cloud. oracle-oci builder calls https://iaas.<region>.oraclecloud.com/xxx which does not work for us-luke-1 and us-langley-1 regions. It needs to call https://iaas.region.oraclegovcloud.com/xxx. I cannot override this behavior even though the CLI will naturally call the right endpoint when the region is a Government region.
#### Reproduction Steps
Set "access_cfg_file_account" to profile that uses Oracle government cloud region.
packer build xxxx.json

### Packer version

$ packer version
Packer v1.5.1

### Simplified Packer Buildfile
  "builders":[{
    "access_cfg_file_account": "{{user `cli_account`}}",
    "availability_domain": "{{user `availability_domain`}}",
    "base_image_ocid": "{{user `base_image`}}",
    "compartment_ocid": "{{user `compartment_id`}}",
    "image_name": "ConsulServer",
    "shape": "VM.Standard2.1",
    "ssh_username": "opc",
    "subnet_ocid": "{{user `subnet_id`}}",
    "type": "oracle-oci"
  }],
### Operating system and Environment details

Windows 10. 

### Log Fragments and crash.log files

2020/03/04 14:48:07 packer.exe plugin: Serving a plugin connection...
2020/03/04 14:48:07 ui: oracle-oci: output will be in this color.
2020/03/04 14:48:07 ui: 
2020/03/04 14:48:07 Build debug mode: false
2020/03/04 14:48:07 Force build: false
2020/03/04 14:48:07 On error: 
2020/03/04 14:48:07 Preparing build: oracle-oci
2020/03/04 14:48:07 Waiting on builds to complete...
2020/03/04 14:48:07 Starting build run: oracle-oci
2020/03/04 14:48:07 Running builder: oracle-oci
2020/03/04 14:48:07 [INFO] (telemetry) Starting builder oracle-oci
2020/03/04 14:48:07 ui: ==> oracle-oci: Creating temporary ssh key for instance...
2020/03/04 14:48:07 ui: ==> oracle-oci: Creating instance...
2020/03/04 14:48:07 ui error: ==> oracle-oci: Problem creating instance: Post https://iaas.us-langley-1.oraclecloud.com/20160918/instances: dial tcp: lookup iaas.us-langley-1.oraclecloud.com: getaddrinfow: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server.
2020/03/04 14:48:07 [INFO] (telemetry) ending oracle-oci
2020/03/04 14:48:07 ui error: Build 'oracle-oci' errored: Problem creating instance: Post https://iaas.us-langley-1.oraclecloud.com/20160918/instances: dial tcp: lookup iaas.us-langley-1.oraclecloud.com: getaddrinfow: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server.
2020/03/04 14:48:07 machine readable: error-count []string{"1"}
2020/03/04 14:48:07 ui error: 
==> Some builds didn't complete successfully and had errors:
2020/03/04 14:48:07 machine readable: oracle-oci,error []string{"Problem creating instance: Post https://iaas.us-langley-1.oraclecloud.com/20160918/instances: dial tcp: lookup iaas.us-langley-1.oraclecloud.com: getaddrinfow: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server."}
2020/03/04 14:48:07 ui error: --> oracle-oci: Problem creating instance: Post https://iaas.us-langley-1.oraclecloud.com/20160918/instances: dial tcp: lookup iaas.us-langley-1.oraclecloud.com: getaddrinfow: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server.
2020/03/04 14:48:07 ui: 
==> Builds finished but no artifacts were created.

**Comment by nywilken** [comment]
Thanks for reaching out. We'll try to take a look when we have a chance. Maybe @prydie can provide some insight. 

In the meantime, you may want to reach out to the [mailing list](https://groups.google.com/forum/#!forum/packer-tool) or [community forum](https://discuss.hashicorp.com/c/packer) as they are generally more useful. Issues opened here on the Packer issue tracker are only viewed by a small handful of developers who work on the tool, and we don't always have the most depth or experience when it comes to custom issues with particular build configurations.

**Comment by twmcelroy** [comment]
@nywilken  Will do. If someone can point me to a way to build custom an override that would be great. Just looks like I'm the first using packer in Gov regions...or I'm missing something silly.

**Comment by twmcelroy** [comment]
This was fixed with #9085 in #9104
