### ISSUE TITLE
Issues with Packer building across subnet. PfSense

### ISSUE THREAD

**Issue by Iluvitari** [hashicorp/packer#8844]
Hi,

I am basically using packer to deploy jumpboxes in a lab environment. 
The lab environment:
- My local laptop with 1 physical interface and 1 virtual interface created by virtual box with ip address of 192.168.56.2

- My PfSense box built on virtual box with wan set to communicate with my physical interface for internet and then it has a lan adapter. These are  "nic1" "bridged adapter" and "nic2" "host-only adapter". The host only adapter is set to have a subnet of 192.168.56.1/24. So my virtual interface is on this subnet.

- I have an AD Windows server 2016 box for DHCP, DNS and AD with ip address of 192.168.56.3

So with this my default gateway is 192.168.56.1 and my dhcp/dns should be being provided by 192.168.56.4. I have currently disabled firewalls on the AD server and I have also enabled Any any firewall rules on wan and nat for the pfsense router. SO anything should be able to come through my pfsense in theory.

My issue:
I am able to build a virtual machine with packer that lies on the subnet. BUT winRM is unable to communicate at all. Even though my local machine is sitting on the same subnet. How do I fix this?

Is it because its running of the virtual subnet? Am I able to make winrm talk through the virtual interface? 

When I run log I get this message:
connection error: unknown error Post https://127.0.0.1:4327/wsman: dial tcp 127.0.0.1:4327: connectex: No connection could be made because the target machine actively refused it.

I have attatched my log file:
[packerlog3.txt](https://github.com/hashicorp/packer/files/4290365/packerlog3.txt)

**Comment by SwampDragons** [comment]
Have you gotten a Packer + winRM build working outside of that virtual subnet?

**Comment by Iluvitari** [comment]
Yes, Outside I have got it to work just fine. But thats if I change the
adapter on the machine being built to a NAT adapter. when I go host-only so
that it is on the subnet it doesnt work. If I make it NAT its obviously not
going to be on that LAN subnet provided by PfSense

**Comment by Iluvitari** [comment]
Any ideas??

**Comment by Iluvitari** [comment]
My json currently:

`{
  "builders": [
    {
      "type": "virtualbox-iso",
      "vm_name": "Evans project",
      "vboxmanage": [
        [ "modifyvm", "{{.Name}}", "--memory", "2048" ],
        [ "modifyvm", "{{.Name}}", "--vram", "48" ],
        [ "modifyvm", "{{.Name}}", "--cpus", "2" ],
        [ "modifyvm", "{{.Name}}", "--nic1", "hostonly"],
        [ "modifyvm", "{{.Name}}", "--hostonlyadapter1", "VirtualBox Host-Only Ethernet Adapter"],
        [ "modifyvm", "{{.Name}}", "--cableconnected1", "on"],
        [ "modifyvm", "{{.Name}}", "--natpf1", "winrm,tcp,127.0.0.1,5985,,5985"]
      ],
      "guest_additions_mode": "attach",
      "guest_os_type": "Windows2016_64",
      "headless": "false",
      "iso_url": "iso/Windows_Server_2016_Datacenter_EVAL_en-us_14393_refresh.iso",
      "iso_checksum": "70721288bbcdfe3239d8f8c0fae55f1f",
      "iso_checksum_type": "md5",
      "communicator": "winrm",
      "winrm_port": "5985",
      "winrm_username": "Project",
      "winrm_password": "Project",
      "winrm_timeout": "60m",
      "shutdown_command": "shutdown /s /t 10 /f /d p:4:1 /c \"Packer Shutdown\"",
      "shutdown_timeout": "15m",
      "floppy_files": [
        "answer_files/Autounattend.xml",
        "scripts/microsoft-updates.bat",
        "scripts/winrmv2.ps1",
        "scripts/AD setup/Network-setup.ps1",
        "scripts/AD setup/Firewalls.ps1",
        "scripts/windows-updates.ps1"
      ]
    }
  ],
  "provisioners": [
      {
      "type": "windows-shell",
      "remote_path": "C:/Windows/Temp/script.bat",
      "execute_command": "cmd /c C:/Windows/Temp/script.bat",
      "scripts": [
        "./scripts/vm-guest-tools.bat",
        "./scripts/enable-rdp.bat",
        "./scripts/disable-auto-logon.bat",
        "./scripts/compact.bat"
      ]
    },
    {
      "type": "powershell",
      "script": "scripts/after-reboot.ps1",
      "elevated_user": "./Project",
      "elevated_password": "./Project"
    },
    {
      "type": "powershell",
      "script": "scripts/cleanup.ps1",
      "elevated_user": "./Project",
      "elevated_password": "./Project"
    },
    {
      "type": "powershell",
      "script": "Install chocolatey!.ps1",
      "elevated_user": "./Project",
      "elevated_password": "./Project"
    },
    {
      "type": "windows-restart",
      "restart_timeout": "15m"
    },
    {
      "type": "powershell",
      "script": "scripts/AD setup/Domain-join.ps1",
      "elevated_user": "Project",
      "elevated_password": "Project"
    }
  ]
}
`

**Comment by Iluvitari** [comment]
Anyone??????? Kind of an urgent project. Still not able to resolve the issue

**Comment by SwampDragons** [comment]
I'm sorry we haven't been able to resolve this for you -- unfortunately, networking issues are often not specifically Packer issues, and are very hard for us to help you debug since we don't have access to your environment. 

That particular error message "No connection could be made because the target machine actively refused it" generally means that either there's a firewall blocking your connection, or that there's no service on the other side listening for a connection. That's not up to Packer to fix; either WinRM isn't running, or you're giving it a bad port. 

My guess is something is up with your vboxmanage command that sets the nat and port forwarding. My recommendation would be to launch a VM using the commands that Packer logs, and to tinker until you can get a connection correctly, before adding Packer into that stack. 

Some other options worth knowing about as you debug: You can set an SSH_PROXY env var to tell Packer to reach through a proxy, or you can manually set the ssh_host option in your packer config to tell Packer where to connect to.

**Comment by Iluvitari** [comment]
I see, no worries. Thank you for trying anyway. I’ll have a tinker around.
If I use the SSH_host command will I just be giving the IP of the built
machine for connection? I wasn’t sure if this would work as I thought this
was for OpenSSh and not windmill but I’ll give it a go if that’s not the
case. I’ll mess around with the vboxmanage commands too and post if I get
any result. Shouldn’t be any issues with firewalls or ports as I’ve opened
everything and disabled firewalls/allowed any/any in order to troubleshoot
the connection.

Will update when I have some results hopefully soon!
