### ISSUE TITLE
packer 1.5.4 build error

### ISSUE THREAD

**Issue by IPv4v6** [hashicorp/packer#8846]
#### Overview of the Issue

When trying to build packer 1.5.4 from source (**go get**) I'm experiencing the following errors:
```
# github.com/hashicorp/packer/hcl2template
go/pkg/mod/github.com/hashicorp/packer@v1.5.4/hcl2template/functions.go:37:22: undefined: stdlib.CeilFunc
go/pkg/mod/github.com/hashicorp/packer@v1.5.4/hcl2template/functions.go:38:22: undefined: stdlib.ChompFunc
go/pkg/mod/github.com/hashicorp/packer@v1.5.4/hcl2template/functions.go:39:22: undefined: stdlib.ChunklistFunc
go/pkg/mod/github.com/hashicorp/packer@v1.5.4/hcl2template/functions.go:45:22: undefined: stdlib.CoalesceListFunc
go/pkg/mod/github.com/hashicorp/packer@v1.5.4/hcl2template/functions.go:46:22: undefined: stdlib.CompactFunc
go/pkg/mod/github.com/hashicorp/packer@v1.5.4/hcl2template/functions.go:48:22: undefined: stdlib.ContainsFunc
go/pkg/mod/github.com/hashicorp/packer@v1.5.4/hcl2template/functions.go:52:22: undefined: stdlib.DistinctFunc
go/pkg/mod/github.com/hashicorp/packer@v1.5.4/hcl2template/functions.go:53:22: undefined: stdlib.ElementFunc
go/pkg/mod/github.com/hashicorp/packer@v1.5.4/hcl2template/functions.go:57:22: undefined: stdlib.FlattenFunc
go/pkg/mod/github.com/hashicorp/packer@v1.5.4/hcl2template/functions.go:58:22: undefined: stdlib.FloorFunc
go/pkg/mod/github.com/hashicorp/packer@v1.5.4/hcl2template/functions.go:58:22: too many errors
```

#### Reproduction Steps

```
$ go version
go version go1.13.8 linux/amd64

export CGO_ENABLED=0
export GO111MODULE=on
go get -v -a -ldflags '-extldflags "-static"' github.com/hashicorp/packer@v1.5.4
```

### Packer version

1.5.4

### Operating system and Environment details

Linux amd64
Go version 1.13.8

**Comment by jhawk28** [comment]
I think the issue is that the go get is not respecting the package overrides:
```
replace git.apache.org/thrift.git => github.com/apache/thrift v0.0.0-20180902110319-2566ecd5d999

replace github.com/gofrs/flock => github.com/azr/flock v0.0.0-20190823144736-958d66434653

replace github.com/zclconf/go-cty => github.com/azr/go-cty v1.1.1-0.20200203143058-28fcda2fe0cc
```

**Comment by jhawk28** [comment]
this issue explains why: https://github.com/golang/go/issues/30354

**Comment by nywilken** [comment]
hi @IPv4v6 thanks for bubbling this up; @jhawk28 thanks adding the link to the respective golang/go issue. This is something to keep an eye for the future if things should change with the Go tooling. 

The preferred and tested method for [installing from source](https://packer.io/intro/getting-started/install.html#compiling-from-source) is to clone the project into your respective `$GOPATH/src/github.com/hashicorp`, checkout out the respective tag `git checkout v1.5.4`  and use the `make dev` command to install the binary. 

The forked go-cty pkg in the go.mod file will be removed in https://github.com/hashicorp/packer/pull/8837#discussion_r388302738 but you still may want to look into using the preferred method as the continued work in improving HCL support for Packer may result in future replace statements.

**Comment by azr** [comment]
Hello there, #9805 remove the last `replace` call which should help here 🙂 .
