### ISSUE TITLE
Website: Ansible Provisioner, Basic Example - json code block markdown not rendering

### ISSUE THREAD

**Issue by jason-azze** [hashicorp/packer#8851]
#### Description

The website doc for the Ansible provisioner https://packer.io/docs/provisioners/ansible.html has a basic example. The markdown for the "Example Packer template:" is not rendering correctly, even though the markdown looks correct (to me).

#### Reproduction Steps

View https://packer.io/docs/provisioners/ansible.html with a web browser. Note that the first json code block on the page is rendering with the regular paragraph style instead of as a code block.

### Operating system and Environment details

Brave (a Chrome variant) Version 1.4.96 Chromium: 80.0.3987.132 (Official Build) (64-bit)
Firefox 73.0.1
Chrome Version 80.0.3987.132 (Official Build) (64-bit)

All on Pop!_OS 
```
NAME="Pop!_OS"
VERSION="19.10"
ID=ubuntu
ID_LIKE=debian
```

I checked the raw md file with Atom's markdown preview, and it looks fine. I was going to submit a PR with a fix, but there's nothing I can see to fix. :-)

**Comment by sylviamoss** [comment]
Thanks for reaching out! It seems there's an extra empty space between ``` and `json` which breaks the format. Removing this empty space and also de `json` word seems to fix the markdown. I'm opening a PR for this!
