### ISSUE TITLE
ansible provisioner leaves junk in directory called /root/~user

### ISSUE THREAD

**Issue by sanvila** [hashicorp/packer#8860]
When using the ansible provisioner with either googlecompute, digitalocean or hetzner builders, final images contain an unwanted directory like this:

`/root/~user`

where "user" is the local user being used to run packer.

As opposed to /root/.ansible, I think this should not happen because it does not happen when using ansible without packer (i.e. using root as the remote user). Because of this, I have to add an extra step to remove the junk.

I also think this is bad because by default the contents of the resulting image should ideally not depend on the user running packer (i.e. it should be as reproducible as possible).

I can reproduce this effect every time as far as I use at least one ansible provisioner in
the packer JSON file.

(Not including a minimal JSON to reproduce because this happens always to me, but I will be more than happy to provide one if required).

I'm using packer v1.5.4 from packer_1.5.4_linux_amd64.zip and ansible version 2.7.7+dfsg-1 as distributed by Debian 10.

Thanks.

**Comment by nywilken** [comment]
hi @sanvila thanks for reaching out and bubbling up this issue. This is one of our community-supported plugins, which means that the HashiCorp maintainers don't spend much engineering time on it. But we will try to take a look when we get chance. 

With that said, if you could provide the minimal JSON including the provisioner you use to clean up the junk it would be a solid add to your issue. It is helpful to have the respective configs to minimize time in reproducing the issue, especially for those new to Ansible.

Thanks!

**Comment by sanvila** [comment]
Ok, here is a minimal JSON to reproduce:

```
{
  "builders": [
    {
      "type": "hcloud",
      "token": "MYTOKEN",
      "image": "debian-10",
      "location": "nbg1",
      "server_type": "cx11",
      "ssh_username": "root",
      "snapshot_name": "simple-case-{{ timestamp }}"
    }
  ],
  "provisioners": [
    {
      "type": "shell",
      "inline": [
        "ls -l /root"
      ]
    },
    {
      "type": "ansible",
      "playbook_file": "simple-case.yml"
    },
    {
      "type": "shell",
      "inline": [
        "ls -l /root"
      ]
    },
    {
      "type": "shell",
      "inline": [
        "rm -rf /root/~myuser"
      ]
    }
  ]
}

```
and this is `simple-case.yml`:

```
---
- name: simple-case
  remote_user: root
  hosts: all
  tasks:
    - name: hello
      copy:
        content: "Hello Kitty"
        dest: /etc/hello-kitty.txt
```

When running packer on that, it can be seen that `/root/~myuser` exists after the ansible provisioner, and that's why I have to remove it afterwards.

Hope this helps.
