### ISSUE TITLE
Config template format does not work well in large environments

### ISSUE THREAD

**Issue by jjongsma** [hashicorp/packer#887]
The strict JSON template format does not work well for managing hundreds of images that need to share some common pieces (builders, etc). It is missing capabilities for includes and comments, both of which are critical in large environments. Without these, maintaining a large library of server images is a painful exercise in undocumented copy and paste.

Currently we are using a python wrapper around Packer that parses our own YAML config files (with an "!include" constructor extension) and converts the results to a throwaway JSON template for each build. I can't imagine using Packer without this right now.

**Comment by jszwedko** [comment]
I'm in agreement that JSON is a poor choice for human generated configuration files (though I understand the motivation to use it if you expect your configuration to always be generated). I do, however, think it would be prudent to also support the use case of user written configuration and allow for YAML to also be used as a configuration language. I personally haven't had to do anything complicated enough to require generating configuration, but have done enough to miss some of the niceties of YAML like commenting.

@mitchellh would a pull request adding YAML support be considered?

**Comment by jszwedko** [comment]
Never mind, I see support for HCL is in the works!
