### ISSUE TITLE
vsphere-iso builder: add support for secure boot

### ISSUE THREAD

**Issue by hkbakke** [hashicorp/packer#8873]
By default EFI and secure boot is enabled when creating a Windows 10 VM manually in later versions of vsphere, but I can't find a way to enable secure boot with vsphere-iso. This prevents me from even starting the ISO-installer for Windows 10 1909 in EFI mode.

**Comment by jhawk28** [comment]
In the API, this gets added by setting the EfiSecureBootEnabled boot option. We can update the SetBootOptions() function to add this.
govc example: https://github.com/vmware/govmomi/blob/master/govc/device/boot.go#L54

**Comment by VladRassokhin** [comment]
I see two possible options on how to configure it in config:
 * Add property like `secure_boot`
 * Or add option `efi-secure` to `firmware`property (currently it's either `bios` or `efi`)

**Comment by VladRassokhin** [comment]
@SwampDragons up to you to decide how to implement that. See choice above :)

**Comment by SwampDragons** [comment]
ah, thanks -- I think the second option looks good, too, and I like your linked diff. I'd merge that if you open a PR.

**Comment by VladRassokhin** [comment]
Does it makes sense to add same option to vsphere-clone builder to be able to enable/disable secure boot or change loader type?

**Comment by SwampDragons** [comment]
Probably does.

**Comment by SwampDragons** [comment]
Build of linked Pr can be found here: https://circleci.com/gh/hashicorp/packer/43856#artifacts/containers/0. 

@hkbakke if you have the time, it would be helpful to have you try that binary out to make sure it solves your issue.

**Comment by hkbakke** [comment]
@SwampDragons I finally got to test it. It took a bit longer because the client I used for packer was a Raspberry Pi 4, so I couldn't use the provided binaries. I finally got it installed in a amd64 compatible VM and it sets EFI secure as intended.
