### ISSUE TITLE
vsphere-iso builder: add support for adding USB 3.0 controllers

### ISSUE THREAD

**Issue by hkbakke** [hashicorp/packer#8874]
By default an USB 3.0 controller is added when creating a Windows 10 VM manually in later versions of vsphere, but I can seemingly only add USB 2.0 devices using packer currently.

The USB controller is needed for mouse during install without vmware tools for Windows 10.

**Comment by jhawk28** [comment]
govc adds usb controllers like this: https://github.com/vmware/govmomi/blob/master/govc/device/usb/add.go#L83

I think the USB 3.0 controller is the types.VirtualUSBXHCIController
