### ISSUE TITLE
Tags not applied to amazon-ebs builder instance, but reported as applied

### ISSUE THREAD

**Issue by IronSavior** [hashicorp/packer#8876]
#### Overview of the Issue

I'm doing some builds with packer-1.5.4 today using the `amazon-ebs` builder and I noticed that the builder instances are not receiving the tags as expected. I remember this was working at some time in the past. Please advise.

json:
![image](https://user-images.githubusercontent.com/174661/76471089-fdb24700-63ae-11ea-9899-47db8cd0b833.png)

packer output:
![image](https://user-images.githubusercontent.com/174661/76471109-0acf3600-63af-11ea-895b-a7ffdfd90da1.png)

AWS console:
![image](https://user-images.githubusercontent.com/174661/76471123-128eda80-63af-11ea-87d6-61c36059f7dd.png)

#### Reproduction Steps

1. Configure amazon-ebs builder to apply tags to builder instance
1. Invoke packer
1. See packer output indicating tags are set
1. See AWS console where tags are not set

### Packer version

1.5.4

### Simplified Packer Buildfile

Builder excerpt form JSON
```json
{
  "name": "centos7-ami",
  "type": "amazon-ebs",
  "ami_description": "SNAP Test Machine",
  "ami_name": "snap-centos7-{{uuid}}",

  "instance_type": "{{user `ec2_instance_type`}}",
  "region": "{{user `aws_region`}}",

  "source_ami_filter": {
    "filters": {
      "product-code": "aw0evgkw8e5c1q413zgy5pjce",
      "architecture": "x86_64",
      "virtualization-type": "hvm",
      "name": "CentOS Linux 7*",
      "root-device-type": "ebs"
    },
    "owners": ["aws-marketplace"],
    "most_recent": true
  },

  "run_volume_tags": {
    "Billing": "{{user `billing_tag`}}",
    "Blah": "MEH"
  },
  "tags": {
    "Billing": "{{user `billing_tag`}}",
    "Blah": "MEH"
  },
  "ssh_username": "centos"
}
```

### Operating system and Environment details

* Packer-1.5.4
* Invoked from within a Ubuntu 18.04 container
* Docker 2.1.0.5
* Windows 10 v1909 build 18363.657 host

### Log Fragments and crash.log files

```
2020/03/11 15:32:47 ui: ==> centos7-ami: Launching a source AWS instance...
2020/03/11 15:32:47 ui: ==> centos7-ami: Adding tags to source instance
2020/03/11 15:32:47 ui:     centos7-ami: Adding tag: "Name": "Packer Builder"
2020/03/11 15:32:47 ui:     centos7-ami: Adding tag: "Billing": "OVH-SNAP"
2020/03/11 15:32:47 ui:     centos7-ami: Adding tag: "Blah": "MEH"
2020/03/11 15:32:49 ui:     centos7-ami: Instance ID: i-01c80c347a10b9107
2020/03/11 15:32:49 ui: ==> centos7-ami: Waiting for instance (i-01c80c347a10b9107) to become ready...
```

**Comment by nywilken** [comment]
Hi @IronSavior thanks for reaching out. I took a look at the build script and see that you are using `run_volume_tags` and `run_tags`. Any defined `run_tags` will be applied to the instance launched for the EBS builder, where `run_volume_tags` will be applied to volumes. To make sure everything is working as expected, I modified your config a bit and verified that all the tags are applied as expected. See screenshots below

## Modified build config
```json
{
   "variables":{
      "billing_tag":"{{timestamp}}"
   },
   "builders":[
      {
         "name":"centos7-ami",
         "type":"amazon-ebs",
         "ami_description":"SNAP Test Machine",
         "ami_name":"snap-centos7-{{uuid}}",
         "instance_type":"t2.micro",
         "region":"{{user `aws_region`}}",
         "source_ami_filter":{
            "filters":{
               "product-code":"aw0evgkw8e5c1q413zgy5pjce",
               "architecture":"x86_64",
               "virtualization-type":"hvm",
               "name":"CentOS Linux 7*",
               "root-device-type":"ebs"
            },
            "owners":[
               "aws-marketplace"
            ],
            "most_recent":true
         },
         "tags":{
            "Billing":"{{user `billing_tag`}}",
            "Blah":"MEH"
         },
         "run_tags":{
            "Billing":"{{user `billing_tag`}}",
            "Blah":"MEH",
            "RunTag":"test"
         },
         "ssh_username":"centos"
      }
   ]
}
```

## Instance Tags (`run_tags`)

![instance_tags](https://user-images.githubusercontent.com/1749304/76627074-ad52fa80-6510-11ea-8954-af587cd314f7.png)

## AMI tags (`tags`)
![ami_tags](https://user-images.githubusercontent.com/1749304/76627132-d1164080-6510-11ea-9a1f-150217067614.png)


I'm going to close this issue seeing as it is resolved by a configuration change. But if you run into any other problems in the future which you think might be a bug please reach out and we will take a look.
