### ISSUE TITLE
Set tag with isotime +30d

### ISSUE THREAD

**Issue by fmunteanu** [hashicorp/packer#8878]
I want to create an AMI `DeleteOn` tag, using isotime:
```
"tags": {
    "DeleteOn": "{{isotime '2006-01-02'}}"
}
```
However, I would like to set the tag 30 days into future. Could you please help me figure what i the proper format?

**Comment by azr** [comment]
Hey @fmunteanu, thanks for opening, I was looking at the [docs](https://packer.io/docs/templates/engine.html) and it looks like it's not available in the JSON mode.

In HCL2 mode there's a `timeadd` functions though: https://packer.io/docs/configuration/from-1.5/functions/datetime/timeadd.html ( if you decide to update to HCL2 for this reason please bear in mind it's still in beta and being actively worked on, we don't expect any breaking changes though only additions )

**Comment by fmunteanu** [comment]
Hi @azr , I'm looking at the documentation and HCL2 is in beta. Do all JSON features are available in HCL2?
https://packer.io/guides/hcl/from-json-v1

**Comment by azr** [comment]
Not all features, like for now only the build command is available and there are some things we want to fix/do. The list can be found here: https://github.com/hashicorp/packer/labels/hcl2 ( watch out some fixes/features of this link are closed and will be available for the next release )
