### ISSUE TITLE
Docs - VSphere ISO: Misunderstanding information on SSH communication fields

### ISSUE THREAD

**Issue by minhluantran017** [hashicorp/packer#8886]
#### Overview of the Issue

The 'Optional SSH Fields' section of Vsphere ISO [builder](https://packer.io/docs/builders/vsphere-iso.html) has a lot of misunderstanding information.

#### Detailed Issue
Document of [Vsphere ISO builder](https://packer.io/docs/builders/vsphere-iso.html#optional-ssh-fields-), at the 'Optional SSH Fields' section, some fields are mentioning the **Amazon EC2/ AWS/ AMI** which are not correct in this case:

* ssh_keypair_name (string) - If specified, this is the key that will be used for SSH with the machine. The key must match a key pair name loaded up into **Amazon EC2**. <...>
* <...>
* ssh_agent_auth (bool) - <...> To use this option with a key pair already configured in the source **AMI**, leave the ssh_keypair_name blank. To associate an existing key pair in **AWS** with the source instance, set the ssh_keypair_name field to the name of the key pair. The environment variable SSH_AUTH_SOCK must be set for this option to work properly.

**Comment by azr** [comment]
Hey @minhluantran017 thanks for opening; that's an issue, I'll fix that now 🙂
