### ISSUE TITLE
Build Centos7 KVM error

### ISSUE THREAD

**Issue by julianbaj** [hashicorp/packer#8894]
When I am trying to build the template.json I have an error launching the VM

#### Overview of the Issue

I just downloaded this repository https://github.com/goffinet/packer-kvm trying to start learning Packer and when I tried to build it I had an error.
#### Reproduction Steps

Steps to reproduce this issue:

I just cloned the repository un started building the "centos7.json

### Packer version 

The Packer version I am using right now is v1.0.4

From `packer version`

### Operating system and Environment details

I am working in Ubuntu server 18.10

### Log Fragments and crash.log files

I add a capture of the terminal
![Captura de pantalla 2020-03-15 a las 18 42 11](https://user-images.githubusercontent.com/61692584/76707118-f2338880-66ec-11ea-87b5-847796090645.png)

**Comment by sylviamoss** [comment]
Hi @julianbaj, thanks for opening this issue!
Have you checked if your user has access permission to KVM? I would suggest using [this documentation](https://help.ubuntu.com/community/KVM/Installation) to help you with that if it is necessary. 
Let me know the results. If this is the case maybe we can add some permission validation to fail before that 🤔

**Comment by nywilken** [comment]
Hi @julianbaj just wanted to follow up on @sylviamoss's question. Are you still running into trouble or have you been able to resolve you issue after checking the user's access to KVM?

Thanks!

**Comment by SwampDragons** [comment]
Closing this issue since we never heard back. If the above questions didn't help guide you to a solution, we can reopen if we can get more information. Thanks!
