### ISSUE TITLE
[gogolecompute] Support for more than one disk

### ISSUE THREAD

**Issue by pmontanari** [hashicorp/packer#8899]
#### Feature Description

googlecompute builder is missing the fearture to attach multiple disks (like for  for Amazon AWS: ami_block_device_mappings) even though  [Machine images ](https://cloud.google.com/compute/docs/machine-images) support it

Thanks
Patrick

**Comment by azr** [comment]
Hey @pmontanari thanks for opening; I think this is a neat idea. 

The following piece of code is what adds a drive to the instance and is an array:
https://github.com/hashicorp/packer/blob/3571c585bb73e151e5bdaad007df161ce23cea7e/builder/googlecompute/driver_gce.go#L425-L438

So I think adding a `disks` option to the builder would be a good idea.
```json
{
  "disks" : [
    {"type": "...", "size": "...", "name":"..."}
  ]
}
```
If you have time to do it we would love to review the PR 🙂 👍

**Comment by chadbean** [comment]
I need a way to launch an image with multiple disks as well. I was looking into this a bit and it seems like we'd also need a way to save the image with those additional disks which is not supported at the moment in Packer.

It looks like Packer uses the [Image](https://pkg.go.dev/google.golang.org/api@v0.21.0/compute/v1?tab=doc#Image) type which will only create an image with the boot disk. Google recently announced [Machine Images](https://cloud.google.com/blog/products/compute/compute-engine-gets-machine-images) which will save create an image with all currently attached disks. 

The new [MachineImage](https://pkg.go.dev/google.golang.org/api@v0.21.0/compute/v0.beta?tab=doc#MachineImage) type is available in the `v0.beta` package of their compute SDK and Packer uses `v1`.

Would it make sense to try to switch fully away from the Image to using the newer MachineImage, or maybe it should be a feature that lives alongside the current functionality? Happy to help if I can.

**Comment by SwampDragons** [comment]
We generally try not to use beta versions of SDKs and APIs, just to help keep Packer stable.

**Comment by chadbean** [comment]
@SwampDragons that makes sense. I wonder if it'd be worth breaking ground on implementing this new "MachineImage" functionality to start preparing for their new API. I'm curious too if this should replace the current imaging functionality or should live alongside it?

**Comment by SwampDragons** [comment]
I'd say at the very least while MachineImage is a beta feature, it should be alongside rather than replacing.
