### ISSUE TITLE
Query API to get base OCID

### ISSUE THREAD

**Issue by milliams** [hashicorp/packer#8915]
For the `oracle-oci` builder, it would be nice if it were possible to set the `base_image_ocid` by querying the API with some filters rather than having to specify the OCID explicitly up-front.

For example, with the `amazon-ebs` builder you can set the [source_ami_filter](https://packer.io/docs/builders/amazon-ebs.html#source_ami_filter) and do something like:

```json
"source_ami_filter": {
  "filters": {
    "product-code": "aw0evgkw8e5c1q413zgy5pjce",
    "architecture": "x86_64"
  },
  "owners": ["679593333241"],
  "most_recent": true
},
```

to get the latest CentOS 7.

For the Oracle *Terraform* provider you can do a similar thing and do:

```hcl
data "oci_core_images" "ol7" {
    compartment_id = var.compartment_ocid

    operating_system = "Oracle Linux"
    operating_system_version = "7.7"

    # exclude GPU specific images
    filter {
        name   = "display_name"
        values = ["^([a-zA-z]+)-([a-zA-z]+)-([\\.0-9]+)-([\\.0-9-]+)$"]
        regex  = true
    }
}
```

to get the non-GPU Oracle Linux 7 images.

At present in my Ansible I have to make a manual call to `oci` and filter it down with some queries before passing it in.

**Comment by azr** [comment]
Hey @milliams, thanks for opening; I think this is a valuable idea !

**Comment by nywilken** [comment]
Hi @milliams, this sounds like a nice feature to have. Any chance you would be up for contributing a PR with the suggested change? If so, we would be happy to review it and provide pointers where necessary.
