### ISSUE TITLE
Packer Hangs while Connecting to Azure Storage and Installing a software

### ISSUE THREAD

**Issue by myselfme0194** [hashicorp/packer#8916]
Was trying to create an Windows 2019 images using an executable stored in Azure Storage account.I do have a powershell script that does this task for me when executed directly manually on VM.

But this scipt is not going well with Packer Provisioner.Packer get hanged.Kindly suggest.

more terraform.ps1
Set-ExecutionPolicy Bypass -Scope Process -Force
Install-Module -Name AzureRM -AllowClobber -Force
$client_id = "zzzzzz"
($client_secret = "xxxxx" | ConvertTo-SecureString -asPlainText -Force)
$credentials = new-object -typename System.Management.Automation.PSCredential -argumentlist $client_id, $client_secret
Connect-AzureRMAccount -Credential $credentials -Tenant yyyyy -ServicePrincipal

$storageAccount = Set-AzureRMStorageAccount -ResourceGroupName packerspikerg -Name "packerspikestrgaccnt" -SkuName Standard_LRS `

$ctx = $storageAccount.Context

$Dir = New-Item -Path 'software' -ItemType Directory
Get-AzureRMStorageBlobContent -Container "iiscontainer" -Blob "terraform_0.12.23_windows_amd64.zip" -Destination $Dir -Context $ctx -Force
Expand-Archive -LiteralPath $Dir\terraform_0.12.23_windows_amd64.zip -DestinationPath $Dir -Force

#[System.Environment]::SetEnvironmentVariable('path',$Dir,[System.EnvironmentVariableTarget]::Machine)

Function Global:Add-Path {
<#.SYNOPSIS
PowerShell function to modify Env:Path in the registry
.DESCRIPTION
Includes a parameter to append the Env:Path
.EXAMPLE
Add-Path -NewPath "D:\Downloads"
#>
Param (
[String]$NewPath =$Dir
)
Begin {
Clear-Host
} # End of small begin section
Process {
Clear-Host
$Reg = "Registry::HKLM\System\CurrentControlSet\Control\Session Manager\Environment"
$OldPath = (Get-ItemProperty -Path "$Reg" -Name PATH).Path
$NewPath = $OldPath + ';' + $NewPath
Set-ItemProperty -Path "$Reg" -Name PATH -Value $NewPath -Force
} #End of Process
}

This is what you type to call the function.
Add-Path

terraform --version
~

more windows_2019_iis.json
{
"variables": {
"client_id": "zzzzz",
"client_secret": "yyyyyy",
"sensitive-variables": "client_secret",
"tenant_id": "xxxxx",
"subscription_id": "abcd"
},
"builders": [
{
"type": "azure-arm",
"client_id": "{{user client_id}}",
"client_secret": "{{user client_secret}}",
"tenant_id": "{{user tenant_id}}",
"subscription_id": "{{user subscription_id}}",
"os_type": "Windows",
"image_publisher": "MicrosoftWindowsServer",
"image_offer": "WindowsServer",
"image_sku": "2019-Datacenter",
"image_version": "latest",
"managed_image_resource_group_name": "packerspikerg",
"managed_image_name": "ws2019-trial",
"disk_caching_type": "ReadWrite",
"communicator": "winrm",
"winrm_use_ssl": true,
"winrm_insecure": true,
"winrm_timeout": "20m",
"winrm_username": "packer",
"location": "West Europe",
"vm_size": "Standard_A2_v2",
"azure_tags": {
"dept": "DevOps"
}
}
],
"provisioners": [
{
"type": "powershell",
"inline": [
"Write-Host 'Configuring IIS Role,Install DotNet,Terraform and sysprepping...'"
]
},
{
"type": "powershell",
"script": "./scripts/iis-install.ps1"
},
{
"type": "powershell",
"script": "./scripts/terraform.ps1"
},
{
"type": "powershell",
"script": "./scripts/dotnet.ps1"
},
{
"type": "windows-update"
},
{
"type": "windows-restart"
},
{
"type": "powershell",
"script": "./scripts/iis-sysprep.ps1"
}
]
}

**Comment by myselfme0194** [comment]
log:
2020/03/18 16:55:06 ui: ==> azure-arm: Provisioning with powershell script: ./scripts/terraform.ps1
2020/03/18 16:55:06 packer-provisioner-powershell plugin: Opening ./scripts/terraform.ps1 for reading
2020/03/18 16:55:06 packer-provisioner-powershell plugin: Uploading env vars to c:/Windows/Temp/packer-ps-env-vars-5e724b1c-7c6d-db8f-d6e2-e834ac010d40.ps1
2020/03/18 16:55:06 packer-provisioner-powershell plugin: [INFO] 74 bytes written for 'uploadData'
2020/03/18 16:55:06 [INFO] 74 bytes written for 'uploadData'
2020/03/18 16:55:06 packer-builder-azure-arm plugin: Uploading file to 'c:/Windows/Temp/packer-ps-env-vars-5e724b1c-7c6d-db8f-d6e2-e834ac010d40.ps1'
2020/03/18 16:55:09 packer-builder-azure-arm plugin: #< CLIXML
2020/03/18 16:55:11 packer-builder-azure-arm plugin: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="
0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules
for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>#< CLIXML
2020/03/18 16:55:11 packer-provisioner-powershell plugin: [INFO] 1045 bytes written for 'uploadData'
2020/03/18 16:55:11 [INFO] 1045 bytes written for 'uploadData'
2020/03/18 16:55:11 packer-builder-azure-arm plugin: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="
0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules
for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>Uploading file to 'c:/Windows/Temp/scrip
t-5e724b1c-9f8d-69f2-8365-994c3d138408.ps1'
2020/03/18 16:55:14 packer-builder-azure-arm plugin: #< CLIXML
2020/03/18 16:55:18 packer-builder-azure-arm plugin: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="
0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules
for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>#< CLIXML
2020/03/18 16:55:19 packer-builder-azure-arm plugin: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="
0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules
for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>[INFO] starting remote command: powershe
ll -executionpolicy bypass "& { if (Test-Path variable:global:ProgressPreference){set-variable -name variable:global:ProgressPreference -value 'SilentlyContin
ue'};. c:/Windows/Temp/packer-ps-env-vars-5e724b1c-7c6d-db8f-d6e2-e834ac010d40.ps1; &'c:/Windows/Temp/script-5e724b1c-9f8d-69f2-8365-994c3d138408.ps1'; exit $
LastExitCode }"

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out. I would recommend removing everything else from your build until you figure out specifically what combinations of things is causing it to hang.

One possibility is that the installations/sysprepping that you are doing in iis-install.ps1 are causing reboots that disconnect Packer from the instance and make it hard to reconnect. If that is the case, you can try using the windows-restart provisioner with the [check-registry](https://packer.io/docs/provisioners/windows-restart.html#check_registry) option to wait for reboots to complete before moving froward with your next provisioning script. 

If you remove/reduce the work done in iis-install.ps1 does it still disconnect on the terraform.ps1 script?

**Comment by myselfme0194** [comment]
I have tried it individually....everything works fine other than terraform.ps1. The log that i have pasted here is specific part of terrafom.ps1 which gets hanged.Logs for rest of the things are good.

**Comment by myselfme0194** [comment]
-01" x-ms-request-id="03497c38-76c6-4641-a87a-a4898fdf683e"
==> azure-arm: Waiting for WinRM to become available...
2020/03/20 08:55:20 packer-builder-azure-arm plugin: Waiting for WinRM, up to timeout: 20m0s
2020/03/20 08:55:20 packer-builder-azure-arm plugin: [INFO] Attempting WinRM connection...
2020/03/20 08:55:20 packer-builder-azure-arm plugin: [DEBUG] connecting to remote shell using WinRM
2020/03/20 08:55:35 packer-builder-azure-arm plugin: Checking that WinRM is connected with: 'powershell.exe -EncodedCommand aQBmACAAKABUAGUAcwB0AC0AUABhAHQAaAAgAHYAYQByAGkAYQBiAGwAZQA6AGcAbABvAGIAYQBsADoAUAByAG8AZwByAGUAcwBzAFAAcgBlAGYAZQByAGUAbgBjAGUAKQB7ACQAUAByAG8AZwByAGUAcwBzAFAAcgBlAGYAZQByAGUAbgBjAGUAPQAnAFMAaQBsAGUAbgB0AGwAeQBDAG8AbgB0AGkAbgB1AGUAJwB9ADsAIABlAGMAaABvACAAIgBXAGkAbgBSAE0AIABjAG8AbgBuAGUAYwB0AGUAZAAuACIA'
2020/03/20 08:55:36 packer-builder-azure-arm plugin: [INFO] starting remote command: powershell.exe -EncodedCommand aQBmACAAKABUAGUAcwB0AC0AUABhAHQAaAAgAHYAYQByAGkAYQBiAGwAZQA6AGcAbABvAGIAYQBsADoAUAByAG8AZwByAGUAcwBzAFAAcgBlAGYAZQByAGUAbgBjAGUAKQB7ACQAUAByAG8AZwByAGUAcwBzAFAAcgBlAGYAZQByAGUAbgBjAGUAPQAnAFMAaQBsAGUAbgB0AGwAeQBDAG8AbgB0AGkAbgB1AGUAJwB9ADsAIABlAGMAaABvACAAIgBXAGkAbgBSAE0AIABjAG8AbgBuAGUAYwB0AGUAZAAuACIA
==> azure-arm: #< CLIXML
    azure-arm: WinRM connected.
2020/03/20 08:56:00 packer-builder-azure-arm plugin: [INFO] command 'powershell.exe -EncodedCommand aQBmACAAKABUAGUAcwB0AC0AUABhAHQAaAAgAHYAYQByAGkAYQBiAGwAZQA6AGcAbABvAGIAYQBsADoAUAByAG8AZwByAGUAcwBzAFAAcgBlAGYAZQByAGUAbgBjAGUAKQB7ACQAUAByAG8AZwByAGUAcwBzAFAAcgBlAGYAZQByAGUAbgBjAGUAPQAnAFMAaQBsAGUAbgB0AGwAeQBDAG8AbgB0AGkAbgB1AGUAJwB9ADsAIABlAGMAaABvACAAIgBXAGkAbgBSAE0AIABjAG8AbgBuAGUAYwB0AGUAZAAuACIA' exited with code: 0
==> azure-arm: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="1"><TNRef RefId="0" /><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>
==> azure-arm: Connected to WinRM!
2020/03/20 08:56:00 packer-builder-azure-arm plugin: Connected to machine
2020/03/20 08:56:00 packer-builder-azure-arm plugin: Running the provision hook
2020/03/20 08:56:00 [INFO] (telemetry) Starting provisioner powershell
==> azure-arm: Provisioning with Powershell...
2020/03/20 08:56:00 packer-provisioner-powershell plugin: Found command: Write-Host 'Configuring IIS Role,Install DotNet,Terraform and sysprepping...'
==> azure-arm: Provisioning with powershell script: /tmp/powershell-provisioner504612716
2020/03/20 08:56:00 packer-provisioner-powershell plugin: Opening /tmp/powershell-provisioner504612716 for reading
2020/03/20 08:56:00 packer-provisioner-powershell plugin: Uploading env vars to c:/Windows/Temp/packer-ps-env-vars-5e748403-351a-e437-2bfe-a7ad138b09c1.ps1
2020/03/20 08:56:00 packer-provisioner-powershell plugin: [INFO] 74 bytes written for 'uploadData'
2020/03/20 08:56:00 [INFO] 74 bytes written for 'uploadData'
2020/03/20 08:56:00 packer-builder-azure-arm plugin: Uploading file to 'c:/Windows/Temp/packer-ps-env-vars-5e748403-351a-e437-2bfe-a7ad138b09c1.ps1'
2020/03/20 08:56:04 packer-builder-azure-arm plugin: #< CLIXML
2020/03/20 08:56:06 packer-builder-azure-arm plugin: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>#< CLIXML
2020/03/20 08:56:07 packer-provisioner-powershell plugin: [INFO] 78 bytes written for 'uploadData'
2020/03/20 08:56:07 [INFO] 78 bytes written for 'uploadData'
2020/03/20 08:56:07 packer-builder-azure-arm plugin: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>Uploading file to 'c:/Windows/Temp/script-5e748403-9871-3d44-9dcf-caad5c4ae6ce.ps1'
2020/03/20 08:56:09 packer-builder-azure-arm plugin: #< CLIXML
2020/03/20 08:56:11 packer-builder-azure-arm plugin: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>#< CLIXML
2020/03/20 08:56:11 packer-builder-azure-arm plugin: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>[INFO] starting remote command: powershell -executionpolicy bypass "& { if (Test-Path variable:global:ProgressPreference){set-variable -name variable:global:ProgressPreference -value 'SilentlyContinue'};. c:/Windows/Temp/packer-ps-env-vars-5e748403-351a-e437-2bfe-a7ad138b09c1.ps1; &'c:/Windows/Temp/script-5e748403-9871-3d44-9dcf-caad5c4ae6ce.ps1'; exit $LastExitCode }"
2020/03/20 08:56:13 packer-builder-azure-arm plugin: [INFO] command 'powershell -executionpolicy bypass "& { if (Test-Path variable:global:ProgressPreference){set-variable -name variable:global:ProgressPreference -value 'SilentlyContinue'};. c:/Windows/Temp/packer-ps-env-vars-5e748403-351a-e437-2bfe-a7ad138b09c1.ps1; &'c:/Windows/Temp/script-5e748403-9871-3d44-9dcf-caad5c4ae6ce.ps1'; exit $LastExitCode }"' exited with code: 0
2020/03/20 08:56:13 packer-builder-azure-arm plugin: [INFO] RPC endpoint: Communicator ended with: 0
2020/03/20 08:56:13 [INFO] 0 bytes written for 'stderr'
2020/03/20 08:56:13 [INFO] 65 bytes written for 'stdout'
2020/03/20 08:56:13 [INFO] RPC client: Communicator ended with: 0
2020/03/20 08:56:13 [INFO] RPC endpoint: Communicator ended with: 0
2020/03/20 08:56:13 packer-provisioner-powershell plugin: [INFO] 0 bytes written for 'stderr'
2020/03/20 08:56:13 packer-provisioner-powershell plugin: [INFO] 65 bytes written for 'stdout'
2020/03/20 08:56:13 packer-provisioner-powershell plugin: [INFO] RPC client: Communicator ended with: 0
    azure-arm: Configuring IIS Role,Install DotNet,Terraform and sysprepping...
2020/03/20 08:56:13 packer-provisioner-powershell plugin: c:/Windows/Temp/script-5e748403-9871-3d44-9dcf-caad5c4ae6ce.ps1 returned with exit code 0
2020/03/20 08:56:13 [INFO] (telemetry) ending powershell
2020/03/20 08:56:13 [INFO] (telemetry) Starting provisioner powershell
==> azure-arm: Provisioning with Powershell...
==> azure-arm: Provisioning with powershell script: ./scripts/terraform.ps1
2020/03/20 08:56:13 packer-provisioner-powershell plugin: Opening ./scripts/terraform.ps1 for reading
2020/03/20 08:56:13 packer-provisioner-powershell plugin: Uploading env vars to c:/Windows/Temp/packer-ps-env-vars-5e748403-102e-1eaa-9f2e-82ffadc1ae71.ps1
2020/03/20 08:56:13 packer-provisioner-powershell plugin: [INFO] 74 bytes written for 'uploadData'
2020/03/20 08:56:13 [INFO] 74 bytes written for 'uploadData'
2020/03/20 08:56:13 packer-builder-azure-arm plugin: Uploading file to 'c:/Windows/Temp/packer-ps-env-vars-5e748403-102e-1eaa-9f2e-82ffadc1ae71.ps1'
2020/03/20 08:56:15 packer-builder-azure-arm plugin: #< CLIXML
2020/03/20 08:56:18 packer-builder-azure-arm plugin: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>#< CLIXML
2020/03/20 08:56:18 packer-provisioner-powershell plugin: [INFO] 1880 bytes written for 'uploadData'
2020/03/20 08:56:18 [INFO] 1880 bytes written for 'uploadData'
2020/03/20 08:56:18 packer-builder-azure-arm plugin: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>Uploading file to 'c:/Windows/Temp/script-5e748403-aad5-9f5a-9f88-d1e310ade5ed.ps1'
2020/03/20 08:56:20 packer-builder-azure-arm plugin: #< CLIXML
2020/03/20 08:56:22 packer-builder-azure-arm plugin: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>#< CLIXML
2020/03/20 08:56:23 packer-builder-azure-arm plugin: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>[INFO] starting remote command: powershell -executionpolicy bypass "& { if (Test-Path variable:global:ProgressPreference){set-variable -name variable:global:ProgressPreference -value 'SilentlyContinue'};. c:/Windows/Temp/packer-ps-env-vars-5e748403-102e-1eaa-9f2e-82ffadc1ae71.ps1; &'c:/Windows/Temp/script-5e748403-aad5-9f5a-9f88-d1e310ade5ed.ps1'; exit $LastExitCode }"

**Comment by SwampDragons** [comment]
Thanks for the logs, but they aren't super useful because they don't show what is actually going on on the VM side of things. I can't help you if I don't know the contents of your scripts. Please share the terraform.ps1 script _as well as any other scripts you are running before this one, as part of your packer run_

**Comment by nywilken** [comment]
Hi @myselfme0194 just wanted to circle back here. If you haven't already I would confirm that the instance under provision has the same access permissions and configuration to the VM where you are able to run the script manually. Maybe try running the terraform script before the iis-install script to see if that changes anything. 

I'm going to close this issue seeing as we don't have enough information to help out here. If you are still running into this issue please see if you can provide us with the information that @SwampDragons requested so that we can better understand what's going on. You can also reach out to our [community forums](https://packer.io/community.html) for help.
