### ISSUE TITLE
Please mark packer tag v1.5.4 as latest release

### ISSUE THREAD

**Issue by ivandeex** [hashicorp/packer#8919]
Latest packer release on github is outdated tag v1.5.0

**Comment by azr** [comment]
Hello there, solved: https://github.com/hashicorp/packer/releases/tag/v1.5.4 thanks !

I just had to edit the release and save ( there's no option to tag as latest )

I think this used to be automagic 🤔

**Comment by ivandeex** [comment]
This issue reproduced again with release v1.5.5, which has not been marked as "release" on github and keeps treated as a non-release git tag by github (see https://github.com/hashicorp/packer/releases). You need to add a step in your release pipeline that marks a tag in github git as "released" tag.

**Comment by azr** [comment]
Ah again ! There we go, thanks for reporting, again, I made it latest; this is weird.
We are currently planning on automating our release process so hopefully this is solved soonish 🙂
