### ISSUE TITLE
"Blob based disk to VM with managed disks is not supported"

### ISSUE THREAD

**Issue by ampc** [hashicorp/packer#8925]
## Overview of the Issue
Hello, I'm trying to build a image with additional disks but packer returns an error about `blob based disk to VM with managed disks is not supported.`

#### Reproduction Steps

Create a managed image with additional disks

### Packer version
1.5.4

### Simplified Packer Buildfile

https://gist.github.com/ampc/28f6d91a9409fb1d2808f5f7ea7ff654#file-packer-json
### Operating system and Environment details
Ubuntu 16.04

### Log Fragments and crash.log files

https://gist.github.com/ampc/28f6d91a9409fb1d2808f5f7ea7ff654#file-packer-log

**Comment by bencebano** [comment]
Hi All,

I have the exact same issue, when trying to add a datadisk to our platinum windows image. 
We are using packer 1.4.5 and provisioner-windows-update 0.8.0

`        "os_disk_size_gb": "127",
        "disk_additional_size": [ 32 ],
        "managed_image_storage_account_type": "Premium_LRS",`

It does through the same error:

`1585537062,,ui,say,==> azure-arm: ERROR: -> DeploymentFailed : At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.\n==> azure-arm: ERROR:   -> Conflict\n==> azure-arm: ERROR:   -> OperationNotAllowed : Addition of a blob based disk to VM with managed disks is not supported.\n==> azure-arm:
1`

As per the [documentation](https://packer.io/docs/builders/azure-arm.html#disk_additional_size) additional disks should use the same type as "managed_image_storage_account_type", however it seems this is not what is happening.

I have also found this [article](https://stackoverflow.com/questions/53234174/addition-of-a-managed-disk-to-a-vm-with-blob-based-disks-is-not-supported), how this should be done with arm templates.

Do we have information regarding this problem on packer side?

Many Thanks,
Bence

**Comment by vijayrajah** [comment]
@bencebano .. There is a PR open for this.. [https://github.com/hashicorp/packer/pull/8912](8192)
