### ISSUE TITLE
SySPrep in loop for Azure ARM builder

### ISSUE THREAD

**Issue by myselfme0194** [hashicorp/packer#8929]
Trying to create windows 2019 image.But sysprep is keeping it in loop.

#Sysprep
if ( Test-Path $Env:SystemRoot\windows\system32\Sysprep\unattend.xml ) {Remove-Item $Env:SystemRoot\windows\system32\Sysprep\unattend
.xml -Force}
& $env:SystemRoot\\System32\\Sysprep\\Sysprep.exe /oobe /generalize /quiet /quit
while ($true) {
    $imageState = Get-ItemProperty HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Setup\\State | Select-Object ImageState;
    if ($imageState.ImageState -ne 'IMAGE_STATE_GENERALIZE_RESEAL_TO_OOBE')
    { Write-Output $imageState.ImageState; Start-Sleep -s 10  }
    else { break }
}

==> azure-arm: Provisioning with powershell script: ./scripts/iis-sysprep.ps1
2020/03/21 03:24:45 packer-provisioner-powershell plugin: Opening ./scripts/iis-sysprep.ps1 for reading
2020/03/21 03:24:45 packer-provisioner-powershell plugin: Uploading env vars to c:/Windows/Temp/packer-ps-env-vars-5e7580d3-b8bf-3ea3-0901-48bcba55c5c4.ps1
2020/03/21 03:24:45 packer-provisioner-powershell plugin: [INFO] 74 bytes written for 'uploadData'
2020/03/21 03:24:45 [INFO] 74 bytes written for 'uploadData'
2020/03/21 03:24:45 packer-builder-azure-arm plugin: Uploading file to 'c:/Windows/Temp/packer-ps-env-vars-5e7580d3-b8bf-3ea3-0901-48bcba55c5c4.ps1'
2020/03/21 03:24:47 packer-builder-azure-arm plugin: #< CLIXML
2020/03/21 03:24:49 packer-builder-azure-arm plugin: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>#< CLIXML
2020/03/21 03:24:49 packer-provisioner-powershell plugin: [INFO] 546 bytes written for 'uploadData'
2020/03/21 03:24:49 [INFO] 546 bytes written for 'uploadData'
2020/03/21 03:24:49 packer-builder-azure-arm plugin: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>Uploading file to 'c:/Windows/Temp/script-5e7580d3-eac2-e2e1-91a4-c51c4d8ca155.ps1'
2020/03/21 03:24:51 packer-builder-azure-arm plugin: #< CLIXML
2020/03/21 03:24:52 packer-builder-azure-arm plugin: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>#< CLIXML
2020/03/21 03:24:52 packer-builder-azure-arm plugin: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>[INFO] starting remote command: powershell -executionpolicy bypass "& { if (Test-Path variable:global:ProgressPreference){set-variable -name variable:global:ProgressPreference -value 'SilentlyContinue'};. c:/Windows/Temp/packer-ps-env-vars-5e7580d3-b8bf-3ea3-0901-48bcba55c5c4.ps1; &'c:/Windows/Temp/script-5e7580d3-eac2-e2e1-91a4-c51c4d8ca155.ps1'; exit $LastExitCode }"
    azure-arm: IMAGE_STATE_COMPLETE
    azure-arm: IMAGE_STATE_COMPLETE
    azure-arm: IMAGE_STATE_COMPLETE
    azure-arm: IMAGE_STATE_COMPLETE
    azure-arm: IMAGE_STATE_COMPLETE
    azure-arm: IMAGE_STATE_COMPLETE
    azure-arm: IMAGE_STATE_COMPLETE
    azure-arm: IMAGE_STATE_COMPLETE
    azure-arm: IMAGE_STATE_COMPLETE
    azure-arm: IMAGE_STATE_COMPLETE
    azure-arm: IMAGE_STATE_COMPLETE
    azure-arm: IMAGE_STATE_COMPLETE
    azure-arm: IMAGE_STATE_COMPLETE
    azure-arm: IMAGE_STATE_COMPLETE
    azure-arm: IMAGE_STATE_COMPLETE
    azure-arm: IMAGE_STATE_COMPLETE
    azure-arm: IMAGE_STATE_COMPLETE
    azure-arm: IMAGE_STATE_COMPLETE
    azure-arm: IMAGE_STATE_COMPLETE
    azure-arm: IMAGE_STATE_COMPLETE
    azure-arm: IMAGE_STATE_COMPLETE
    azure-arm: IMAGE_STATE_COMPLETE
    azure-arm: IMAGE_STATE_COMPLETE
    azure-arm: IMAGE_STATE_COMPLETE
    azure-arm: IMAGE_STATE_COMPLETE
    azure-arm: IMAGE_STATE_COMPLETE
    azure-arm: IMAGE_STATE_COMPLETE
    azure-arm: IMAGE_STATE_COMPLETE
    azure-arm: IMAGE_STATE_COMPLETE
    azure-arm: IMAGE_STATE_COMPLETE
    azure-arm: IMAGE_STATE_COMPLETE
    azure-arm: IMAGE_STATE_COMPLETE
    azure-arm: IMAGE_STATE_COMPLETE

- Packer Guides: https://www.packer.io/guides/index.html
- Discussion List: https://groups.google.com/group/packer-tool
- Any other questions can be sent to the packer section of the HashiCorp
  forum: https://discuss.hashicorp.com/c/packer
- Packer community links: https://www.packer.io/community.html

**Comment by nywilken** [comment]
I'm closing since I think this is a configuration issue -- if you are still experiencing sysprep issues that can not be explained by the logs or fixed by a Windows restart prior to running the sysprep script, the mailing list is a good place to seek information from people who have more experience in your particular configuration area. Thanks!
