### ISSUE TITLE
Packer Google builder with Debian 10 started giving SSH authentication issue

### ISSUE THREAD

**Issue by ggprod** [hashicorp/packer#8939]
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

I had implemented a Packer build for GCE (Google compute engine) building a GCE custom image.  This was working previously but has recently broken giving this error:

Build 'googlecompute' errored: Packer experienced an authentication error when trying to connect via SSH. This can happen if your username/password are wrong. You may want to double-check your credentials as part of your debugging process. original error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

I see the packer VM that gets created and I see an SSH key is properly created by the SSH communicator and added to the VM (for the specified 'debian' user) but for some reason the SSH communicator can no longer authenticate to it using this generated SSH Key

#### Reproduction Steps

Steps to reproduce this issue:

I was using this Builders section in my packer json:
"builders": [
    {
      "type": "googlecompute",
      "zone": "us-central1-a",
      "project_id": "minimal-viable-product",
      "source_image_family": "debian-10",
      "ssh_username": "debian",
      "image_family": "debian-10-gcloud-packer-terraform-helm-gitlab",
      "image_name": "debian-10-gcloud-packer-terraform-helm-gitlab-{{timestamp}}",
      "disable_default_service_account": true,
      "subnetwork": "mvp-subnet",
      "use_internal_ip": true
    }
  ]

There does not appear to be any connectivity issue, simply an SSH authentication issue (and it was working before and just broke recently)

### Packer version
1.5.4
From `packer version`

### Simplified Packer Buildfile

"builders": [
    {
      "type": "googlecompute",
      "zone": "us-central1-a",
      "project_id": "minimal-viable-product",
      "source_image_family": "debian-10",
      "ssh_username": "debian",
      "image_family": "debian-10-gcloud-packer-terraform-helm-gitlab",
      "image_name": "debian-10-gcloud-packer-terraform-helm-gitlab-{{timestamp}}",
      "disable_default_service_account": true,
      "subnetwork": "mvp-subnet",
      "use_internal_ip": true
    }
  ]

If the file is longer than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/) of the log or use the [Github detailed
format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d)
instead of posting it directly in the issue.

### Operating system and Environment details
Debian-10
OS, Architecture, and any other information you can provide about the
environment.

### Log Fragments and crash.log files

Include appropriate log fragments. If the log is longer than a few dozen lines,
please include the URL to the [gist](https://gist.github.com/) of the log or
use the [Github detailed format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d) instead of posting it directly in the issue.

Set the env var `PACKER_LOG=1` for maximum log detail.

**Comment by SwampDragons** [comment]
When you say "was working before and just broke recently" -- did you update Packer, or did the same version of Packer once work and now isn't with no external changes? 

If the latter, I wonder if something changed with googlecompute upstream. We have another similar report here https://github.com/hashicorp/packer/issues/8924

**Comment by ggprod** [comment]
we changed nothing on our end.. we are using the debian-10 family in GCE (which means for the Google Builder it pulls the latest image from the family as the packer base, though it seems like the latest in the family was Mar 9)

**Comment by ggprod** [comment]
yes, the base image is debian-10-buster-v20200309 and a packer build starting from this same image worked late last week

**Comment by desolatorxxl** [comment]
Do you have connectivity to the internal VPC network (mvp-subnet)?

As far as I can tell packer won't do any magic like gcloudsdk does, when connecting to an internal IP without direct network access.

Either changing `use_internal_ip` to `false` or using an internal VPC network that got a working VPN connection to my local network builds your buildfile just fine for me.

Does it work with `"use_internal_ip": false` ?
You should probably post your logs though.

**Comment by ggprod** [comment]
Connectivity is not the problem, authentication is the problem.  The SSH communicator is able to access the host but not able to authenticate.   The desire for security is to not open SSH access publicly and that is the reason for the "use_internal_ip": false.  Also the VM that packer is running on is in the same network with private SSH connectivity. This was working as-is as recently as Mar 19th.

Full logs:
```
$ packer build ./environments/mvp/gitlab-runner-vm/vm-image-packer.json
02:27
 googlecompute: output will be in this color.
 ==> googlecompute: Checking image does not exist...
 ==> googlecompute: Creating temporary SSH key for instance...
 ==> googlecompute: Using image: debian-10-buster-v20200309
 ==> googlecompute: Creating instance...
     googlecompute: Loading zone: us-central1-a
     googlecompute: Loading machine type: n1-standard-1
     googlecompute: Requesting instance creation...
     googlecompute: Waiting for creation operation to complete...
     googlecompute: Instance has been created!
 ==> googlecompute: Waiting for the instance to become running...
     googlecompute: IP: 10.129.0.11
 ==> googlecompute: Using ssh communicator to connect: 10.129.0.11
 ==> googlecompute: Waiting for SSH to become available...
 ==> googlecompute: Error waiting for SSH: Packer experienced an authentication error when trying to connect via SSH. This can happen if your username/password are wrong. You may want to double-check your credentials as part of your debugging process. original error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
 ==> googlecompute: Deleting instance...
     googlecompute: Instance has been deleted!
 ==> googlecompute: Deleting disk...
     googlecompute: Disk has been deleted!
 Build 'googlecompute' errored: Packer experienced an authentication error when trying to connect via SSH. This can happen if your username/password are wrong. You may want to double-check your credentials as part of your debugging process. original error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
 ==> Some builds didn't complete successfully and had errors:
 --> googlecompute: Packer experienced an authentication error when trying to connect via SSH. This can happen if your username/password are wrong. You may want to double-check your credentials as part of your debugging process. original error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
 ==> Builds finished but no artifacts were created.
 ERROR: Job failed: exit status 1
```

**Comment by desolatorxxl** [comment]
@ggprod I see, weird.
Can you grab the instances serial logs with
```
packer build -on-error=ask <build.json>
```
and
```
gcloud compute instances get-serial-port-output <instance_name>
```
and check if theres something interesting in it?

**Comment by ggprod** [comment]
Ok, here is the end of the serial logs (I assume you wanted them from the VM that packer creates, correct?):
```
 OK  ] Reached target Network.
[  OK  ] Started Unattended Upgrades Shutdown.
         Starting Permit User Sessions...
[  OK  ] Reached target Network is Online.
[  OK  ] Started Google OSConfig Agent.
         Starting chrony, an NTP client/server...
[  OK  ] Stopped System Logging Service.
[  OK  ] Started Permit User Sessions.
[  OK  ] Started Serial Getty on ttyS0.
[  OK  ] Started Getty on tty1.
[  OK  ] Reached target Login Prompts.
         Starting System Logging Service...
[  OK  ] Started System Logging Service.
         Starting Google Compute Engine Instance Setup...
Mar 23 22:07:47 packer-5e79331d-94ea-910d-5589-da8433acd3d9 systemd[1]: Stopping System Logging Service...
Mar 23 22:07:47 packer-5e79331d-94ea-910d-5589-da8433acd3d9 dhclient[310]: bound to 10.129.0.12 -- renewal in 33551 seconds.
Mar 23 22:07:47 packer-5e79331d-94ea-910d-5589-da8433acd3d9 sh[293]: bound to 10.129.0.12 -- renewal in 33551 seconds.
Mar 23 22:07:47 packer-5e79331d-94ea-910d-5589-da8433acd3d9 sh[293]: ens4=ens4
Mar 23 22:07:47 packer-5e79331d-94ea-910d-5589-da8433acd3d9 systemd[1]: Started Raise network interfaces.
Mar 23 22:07:47 packer-5e79331d-94ea-910d-5589-da8433acd3d9 systemd[1]: Reached target Network.
Mar 23 22:07:48 packer-5e79331d-94ea-910d-5589-da8433acd3d9 systemd[1]: Started Unattended Upgrades Shutdown.
Mar 23 22:07:48 packer-5e79331d-94ea-910d-5589-da8433acd3d9 systemd[1]: Starting Permit User Sessions...
Mar 23 22:07:48 packer-5e79331d-94ea-910d-5589-da8433acd3d9 systemd[1]: Reached target Network is Online.
Mar 23 22:07:48 packer-5e79331d-94ea-910d-5589-da8433acd3d9 systemd[1]: Started Google OSConfig Agent.
Mar 23 22:07:48 packer-5e79331d-94ea-910d-5589-da8433acd3d9 systemd[1]: Starting chrony, an NTP client/server...
Mar 23 22:07:48 packer-5e79331d-94ea-910d-5589-da8433acd3d9 systemd[1]: rsyslog.service: Succeeded.
Mar 23 22:07:48 packer-5e79331d-94ea-910d-5589-da8433acd3d9 systemd[1]: Stopped System Logging Service.
```

**Comment by nywilken** [comment]
hello :wave: thanks again for reporting, this issue might be fixed by #8942 ; some test binaries are available via the link below. Would you mind pulling down the binaries and testing that you are able to SSH to the compute instance as expected? 

https://app.circleci.com/pipelines/github/hashicorp/packer/4277/workflows/da0aae95-1eb8-4328-b085-7c43cf5bae2f/jobs/41105/artifacts

Thanks!

**Comment by StanSiska** [comment]
I had exactly the same issue as @ggprod with building custom GCP images for COS8/RHEL8. Tested with binary 1.5.5, issue is gone! Great job.

**Comment by nywilken** [comment]
Awesome, thanks for testing!

**Comment by ggprod** [comment]
@nywilken apologies for the delay, but I just tested the release indicated 
Packer v1.5.5-dev (87f716008494245b31f12f3deda4620294578de2)

I found this did not resolve my issue, I still get the same packer build error:
```
Build 'googlecompute' errored: Packer experienced an authentication error when trying to connect via SSH. This can 
happen if your username/password are wrong. You may want to double-check your credentials as part of your debugging
 process. original error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], n
o supported methods remain
```

**Comment by nywilken** [comment]
@ggprod thanks for the follow up here. I went ahead and re-opened this issue. We will try to take a look at this after the 1.5.5 release. Thanks!

**Comment by SwampDragons** [comment]
I can't reproduce this issue using 
`"image_family": "debian-10-gcloud-packer-terraform-helm-gitlab",` using either the linked patch, or an earlier build.

**Comment by ggprod** [comment]
@SwampDragons the image_familiy and image_name are irrelevant.. those are the labels applied to the resulting built image when packer completes.  The "source_image_family": "debian-10" is the important part

**Comment by SwampDragons** [comment]
Ah, sorry grabbed the wrong line when I copypasted -- I used that. 
```
			"source_image_family": "debian-10",
			"ssh_username": "debian",
```

**Comment by ggprod** [comment]
yah, @desolatorxxl mentioned he could only reproduce when "use_internal_ip": true and packer is running on a VM in the same private VPC (and using Private IP connectivity).  Unfortunately that is a requirement for my implementation

**Comment by SwampDragons** [comment]
Okay, I'll try to set that up and see what's going on.

**Comment by SwampDragons** [comment]
I just ran this from a Packer instance in a subnet whose only firewall rule was to allow tcp ingress on port 22 so that I could get into the instance and run Packer -- and was able to successfully build a debian image in that same subnet with an internal IP.  Is there any other relevant information about your setup that could help me reproduce here?

**Comment by nywilken** [comment]
Hi @ggprod thanks again for working with us. As a follow up to @SwampDragons question we did come across this recent thread in the [gce discussion forums](https://groups.google.com/d/msg/gce-discussion/iHqRb2KlMZg/OCV3uK5qBgAJ) in search of any recent changes that might have occurred upstream, since we are unable to repro the issue. 

In the thread there is a mention that enabling Os Login on the project or individual instance disables ssh metadata based authentication. Is this something that may have been enabled for security reasons on the project where you are building the instance in?

**Comment by ggprod** [comment]
@nywilken @SwampDragons Thanks for the help!  OS-login was exactly the problem!  When I first implemented it was disabled but it looks like recently someone enabled it and that caused the packer build to start failing (because the service account it ran under didn't have the necessary OS-login IAM role). Thanks again!
