### ISSUE TITLE
Packer builder for GCE image isn't working anymore

### ISSUE THREAD

**Issue by mlabouardy** [hashicorp/packer#8951]
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

I have tried to build a machine image for GCP, and the packer build command blocks at "Waiting for creation operation to complete...". I have tried both versions 1.5.4 and 1.5.5 with different source image (centos, debian, redhat) and I'm getting the same error.

It might be related #8942

```
googlecompute: output will be in this color.

==> googlecompute: Checking image does not exist...
==> googlecompute: Creating temporary SSH key for instance...
==> googlecompute: Using image: centos-8-v20200316
==> googlecompute: Creating instance...
    googlecompute: Loading zone: europe-west3-a
    googlecompute: Loading machine type: n1-standard-1
    googlecompute: Requesting instance creation...
    googlecompute: Waiting for creation operation to complete...
==> googlecompute: Error creating instance: time out while waiting for instance to create
Build 'googlecompute' errored: Error creating instance: time out while waiting for instance to create

==> Some builds didn't complete successfully and had errors:
--> googlecompute: Error creating instance: time out while waiting for instance to create

==> Builds finished but no artifacts were created.
```

#### Reproduction Steps

```
{
    "variables" : {
        //Variables
    },
    "builders" : [
        {
            "type": "googlecompute",
            "image_name" : "jenkins-worker",
            "account_file": "{{user `service_account`}}",
            "project_id": "{{user `project`}}",
            "source_image_family": "centos-8",
            "ssh_username": "packer",
            "zone": "{{user `zone`}}"
          }
    ],
    "provisioners" : [
        {
            "type" : "shell",
            "script" : "./setup.sh",
            "execute_command" : "sudo -E -S sh '{{ .Path }}'"
        }
    ]
}
```

It was working before, maybe Google changed something from their side.

### Packer version

1.5.4 and 1.5.5

### Simplified Packer Buildfile

If the file is longer than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/) of the log or use the [Github detailed
format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d)
instead of posting it directly in the issue.

### Operating system and Environment details

Mac or Linux

### Log Fragments and crash.log files

Include appropriate log fragments. If the log is longer than a few dozen lines,
please include the URL to the [gist](https://gist.github.com/) of the log or
use the [Github detailed format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d) instead of posting it directly in the issue.

Set the env var `PACKER_LOG=1` for maximum log detail.

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out! We had a couple of similar issues opened in the last couple of days, and we think we fixed them just in time for the 1.5.5 release which I _just_ pushed out -- can you try on 1.5.5 and let me know if it's still a problem?

**Comment by mlabouardy** [comment]
@SwampDragons I have tried also with 1.5.5

**Comment by SwampDragons** [comment]
Have you ever gotten this working? I am able to successfully build using your config above.

**Comment by replicant0wnz** [comment]
I'm having the same issue w/1.5.5.
```json
{
  "builders" : [
      {
          "type": "googlecompute",
          "image_name" : "glenn-test",
          "project_id": "ord2-us-dc",
          "source_image_family": "centos-8",
          "ssh_username": "packer",
          "zone": "us-central1-a",
          "network": "us-central"
        }
  ],
  "provisioners" : [
      {
          "type" : "shell",
          "script" : "./setup.sh",
          "execute_command" : "sudo -E -S sh '{{ .Path }}'"
      }
  ]
}
```
```
➜  packer packer build test.json
googlecompute: output will be in this color.

==> googlecompute: Checking image does not exist...
==> googlecompute: Creating temporary SSH key for instance...
==> googlecompute: Using image: centos-8-v20200326
==> googlecompute: Creating instance...
    googlecompute: Loading zone: us-central1-a
    googlecompute: Loading machine type: n1-standard-1
    googlecompute: Requesting instance creation...
    googlecompute: Waiting for creation operation to complete...
==> googlecompute: Error creating instance: time out while waiting for instance to create
Build 'googlecompute' errored: Error creating instance: time out while waiting for instance to create

==> Some builds didn't complete successfully and had errors:
--> googlecompute: Error creating instance: time out while waiting for instance to create

==> Builds finished but no artifacts were created.
```

**Comment by replicant0wnz** [comment]
It's a permissions issue for me. Once I gave the service account project "Owner" access, it worked. Previously I gave it Compute Engine->Compute Admin and Storage->Storage Admin. What perms am I missing?

**Comment by replicant0wnz** [comment]
n/m .. Found it. It's just in a different place now. Per the docs "Compute Engine Instance Admin (v1) and Service Account User" do work.

**Comment by SwampDragons** [comment]
Hi -- we had another issue recently and it turned out that the user's IT department had just switched to using OSLogin, which caused issues. see https://github.com/hashicorp/packer/issues/8939#issuecomment-604708639 for more details. Could this be the problem for you?

**Comment by johnsaturn** [comment]
I find it fails for disks over 200 GB as new Instances as VTPM is enabled by default when creating images. **I believe it would be helpful to have parameters to enable/disable vTPM an Integrity Monitoring**.

`[    1.855916] GPT:Primary header thinks Alt. header is not at the end of the disk.
[    1.857431] GPT:41943039 != 419430399
[    1.859893] GPT:Alternate GPT header not at the end of the disk.
[    1.860754] GPT:41943039 != 419430399
[    1.861355] GPT: Use GNU Parted to correct GPT errors.
[    1.862117]  sda: sda1 sda2
[[32m  OK  [0m] Stopped File System Check on /dev/d...d93-b3d1-421e-ba67-5fd6e4189f3d.

         Starting File System Check on /dev/...3-b3d1-421e-ba67-5fd6e4189f3d...

[[32m  OK  [0m] Started File S[    1.917057] expand_rootfs: Resizing disk /dev/sda2
ystem Check on /dev/d...d93-b3d1-421e-ba67-5fd6e4189f3d.

[    1.928269] GPT:Primary header thinks Alt. header is not at the end of the disk.
[    1.931846] GPT:41943039 != 419430399
[    1.932431] GPT:Alternate GPT header not at the end of the disk.
[    1.933260] GPT:41943039 != 419430399
[    1.933807] GPT: Use GNU Parted to correct GPT errors.
[    1.934616]  sda: sda1 sda2
[    1.946560] GPT:Primary header thinks Alt. header is not at the end of the disk.
[    1.947932] GPT:41943039 != 419430399
[    1.948473] GPT:Alternate GPT header not at the end of the disk.
[    1.949753] GPT:41943039 != 419430399
[    1.950329] GPT: Use GNU Parted to correct GPT errors.
[    1.951126]  sda: sda1 sda2
[[32m  OK  [0m] Stopped File System Check on /dev/d...d93-b3d1-421e-ba67-5fd6e4189f3d.

[    1.966711]  sda: sda1 sda2
         Starting File System Check on /dev/...3-b3d1-421e-ba67-5fd6e4189f3d...

[[32m  OK  [0m] Stopped File System Check on /dev/d...d93-b3d1-421e-ba67-5fd6e4189f3d.

         Starting File System Check on /dev/...3-b3d1-421e-ba67-5fd6e4189f3d...

[[32m  OK  [0m] Stopped File System Check on /dev/d...d93-b3d1-421e-ba67-5fd6e4189f3d.

         Starting File System Check on /dev/...3-b3d1-421e-ba67-5fd6e4189f3d...

[[32m  OK  [0m] Started File System Check on /dev/d...d93-b3d1-421e-ba67-5fd6e4189f3d.

[    2.225112] input: ImExPS/2 Generic Explorer Mouse as /devices/platform/i8042/serio1/input/input4
[[32m  OK  [0m] Stopped File System Check on /dev/d...d93-b3d1-421e-ba67-5fd6e4189f3d.

[    2.964913]  sda: sda1 sda2
[[1;31mFAILED[0m] Failed to start File System Check o...d93-b3d1-421e-ba67-5fd6e4189f3d.

See 'systemctl stat[[32m  OK  [0m] Reached target Emergency Mode.

[[32m  OK  [0m] Stopped dracut pre-mount hook.

[[32m  OK  [0m] Stopped dracut initqueue hook.`

**Comment by nywilken** [comment]
Hi @johnsaturn I linked your issue to #7846 so that we can continue tracking it there. 

@mlabouardy I'm going to close this issue since we haven't heard back. If you are still running into this issue and suspect that it is not related to any permissions or configuration settings please feel free to comment on the issue with any new information and I will gladly reopen it. Cheers!
