### ISSUE TITLE
Add VMware Content Library Support

### ISSUE THREAD

**Issue by seanmalloy** [hashicorp/packer#8953]
#### Feature Description

I would like to be able to create VMWare virtual machine images and save them into [VMware Content Library](https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.vsphere.vm_admin.doc/GUID-254B2CE8-20A8-43F0-90E8-3F6776C2C896.html).

#### Use Case(s)

Use the `vsphere-iso` or `vsphere-clone` builder to create a VMware virtual machine template and then save it into a VMware Content Library. Then use the [Terraform vSphere provider](https://github.com/terraform-providers/terraform-provider-vsphere) to deploy a new virtual machine from the template in the content library.

The Terraform vSphere Provider added support for deploying a virtual machine from content library in [v1.17.0](https://github.com/terraform-providers/terraform-provider-vsphere/blob/master/CHANGELOG.md#1170-march-23-2020).

**Comment by seanmalloy** [comment]
This could be implemented as a new feature for the `vsphere-iso` and `vsphere-clone` builders or it could be implemented as a post-processor. I don't really have a strong opinion on which approach would be best.

**Comment by sylviamoss** [comment]
Hello there! I've implemented this feature as part of the `vsphere-iso` and `vsphere-clone` builders.
Could you try out the binaries and let me know if this works as expected? Here they are https://circleci.com/gh/hashicorp/packer/65101#artifacts/containers/0

You can find the preview of the docs to learn how to use the configuration here: https://5f05e72c1044a90007d232f6--packer-www.netlify.app/docs/builders/vmware/vsphere-iso#content-library-import-configuration

The minimal necessary config is like
```hcl
// HCL2 config  
content_library_destination {
    library = "Packer Library Test"
}
```
