### ISSUE TITLE
Example for qemu+packer+ansible

### ISSUE THREAD

**Issue by LucidOne** [hashicorp/packer#8959]
#### Feature Description
Please add
https://git.sr.ht/~lucidone/baseliner
to https://packer.io/community-tools.html#templates

I think the docs might also be a little clearer that the [network-console](https://git.sr.ht/~lucidone/baseliner/tree/master/http/preseed.cfg#L25) is not required as sshd will get started when `openssh-server` is installed.

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out. I have added your repo here:  #8965 

I think the docs make it fairly clear that openssh-server is all you need, here: https://packer.io/guides/automatic-operating-system-installs/preseed_ubuntu.html#examples

**Comment by LucidOne** [comment]
Maybe https://packer.io/docs/builders/qemu.html could link to that guide to make it a little easier to find.

Thanks!
