### ISSUE TITLE
vmware-iso (amazon-import): Waiting for AMI rename to complete (may take a while)

### ISSUE THREAD

**Issue by gauravgoel1989** [hashicorp/packer#8966]
I am building an AWS AMI using Packer version 1.5.5 and the following code (removed a few secret codes) in the post-processor renames the AMI after completion (which is actually a CopyImage AWS SDK in the background).

```
{
        "type": "amazon-import",
        "region": "us-east-1",
        "license_type": "{{user `License`}}",
        "ami_description": "{{user `OS`}} {{user `License`}}-{{user `Stage`}} AMI created by AMIFactory on {{user `datetime`}}",
        "ami_name": "{{user `OS`}}-{{user `Application`}}-{{user `License`}}-{{user `Stage`}}-{{user `datetime`}}",
        "skip_clean": "false",
        "tags": {
          "Application": "AmiFactory"
        }
      }
}
```

The execution gets stuck at "vmware-iso (amazon-import): Waiting for AMI rename to complete (may take a while)" for hours even though I could see that the Image has been copied in the AWS and is available for launch. It appears that the action has completed in AWS but the response is not sent/received in Packer.

The last 4 lines of the execution logs is attached below:

    vmware-iso (amazon-import): Waiting for task import-ami-031701c64f0148a0b to complete (may take a while)
    vmware-iso (amazon-import): Import task import-ami-031701c64f0148a0b complete
    vmware-iso (amazon-import): Starting rename of AMI (ami-05288eb9dd1e6bc7b)
    vmware-iso (amazon-import): Waiting for AMI rename to complete (may take a while)

Any help on this issue is greatly appreciated.

**Comment by sylviamoss** [comment]
Thanks for reaching out! We’ll take a look when we get a chance.

**Comment by SwampDragons** [comment]
I've heard of this kind of thing happening if temporary STS credentials expire during the build.

**Comment by gauravgoel1989** [comment]
> I've heard of this kind of thing happening if temporary STS credentials expire during the build.

Thanks SwampDragons. It was happening due to AWS temporary session timeout. I had some permissions issue because of which the command wasn't completing before timeout. As soon as I fixed the permissions, the command is executing successfully now.

Thanks for the help.
