### ISSUE TITLE
Packer+ansible+windows: Requested entry (plugin_type: connection plugin: packer setting: use_tty ) was not defined in configuration

### ISSUE THREAD

**Issue by juju4** [hashicorp/packer#8968]
#### Overview of the Issue

It does not seem possible to generate a windows image with packer and ansible currently
It uses packer connection plugin
the packer connection plugin has documentation entry and one-liner description. also `"--extra-vars", "ansible_shell_type=powershell ansible_shell_executable=None"`
Likely related to other packer+ansible issues.

It used to work at least about a year ago but not sure when it broke after.

#### Reproduction Steps

git clone https://github.com/juju4/ansible-harden-windows
```
$ . ~/.azure/credentials
$ cd packer
$ packer build azure-windows_server_2019.json
```

### Packer version

1.5.5

### Simplified Packer Buildfile

https://github.com/juju4/ansible-harden-windows/blob/master/packer/azure-windows_server_2019.json

### Operating system and Environment details

Tested with Ansible 2.8.10, 2.9.2 and 2.9.6
Target Windows Server 2016 and 2019

### Log Fragments and crash.log files

```
2020/03/28 21:24:45 ui: [0;32m    azure-arm: Traceback (most recent call last):[0m
2020/03/28 21:24:45 ui: [0;32m    azure-arm:   File "/usr/local/lib/python3.7/site-packages/ansible/plugins/__init__.py", line 58, in get_option[0m
2020/03/28 21:24:45 ui: [0;32m    azure-arm:     option_value = C.config.get_config_value(option, plugin_type=get_plugin_class(self), plugin_name=self._load_name, variables=hostvars)[0m
2020/03/28 21:24:45 ui: [0;32m    azure-arm:   File "/usr/local/lib/python3.7/site-packages/ansible/config/manager.py", line 418, in get_config_value[0m
2020/03/28 21:24:45 ui: [0;32m    azure-arm:     keys=keys, variables=variables, direct=direct)[0m
2020/03/28 21:24:45 ui: [0;32m    azure-arm:   File "/usr/local/lib/python3.7/site-packages/ansible/config/manager.py", line 517, in get_config_value_and_origin[0m
2020/03/28 21:24:45 ui: [0;32m    azure-arm:     raise AnsibleError('Requested entry (%s) was not defined in configuration.' % to_native(_get_entry(plugin_type, plugin_name, config)))[0m
2020/03/28 21:24:45 ui: [0;32m    azure-arm: ansible.errors.AnsibleError: Requested entry (plugin_type: connection plugin: packer setting: use_tty ) was not defined in configuration.[0m
```
full in https://gist.github.com/juju4/97115fb04553e5ca6939b1ac76bea8b6

**Comment by sylviamoss** [comment]
Hey there, thanks for reaching out! We’ll take a look when we get a chance.

**Comment by SwampDragons** [comment]
Hi there! I think this may be related to the proxy adapter that Packer has used historically to get Ansible to play nicely with the Packer communicator. I'm almost finished with a Pr that allow users to do away with the proxy altogether. All it really needs are tests, and some user verification that their issues are resolved. 

Binaries of that PR can be downloaded from our CI server here: https://circleci.com/gh/hashicorp/packer/42423#artifacts/containers/0

See the docs added in the PR for detailed usage instructions: #8625

**Comment by juju4** [comment]
Thanks a lot.
I gave it a try but it does not seem to change, same error
While reviewing docs in the provided link, I removed from packer config the `--connection packer` and added extra var for .WinRMPassword + `"use_proxy": false`.
is there anything else needed?

**Comment by SwampDragons** [comment]
Try deleting the packer.py connection plugin.
