### ISSUE TITLE
retry on error

### ISSUE THREAD

**Issue by elduddz** [hashicorp/packer#8972]
#### Feature Description
unless I have missed something I cannot see a setting that allows packer to be set with an -on-error=retry flag.

I can see an abort or ask, which in an automated process will freeze.

what I was wondering was allowing a step to be retried after an error. I do not know if the image should be somehow reset, but at least in some instances, just allow the MSI or choco step to have another go as the issue is often intermittent download issues.

#### Use Case(s)
we are using the actions/virtual-environments project to base our vms for our windows 2019 build servers, but are constantly hitting issues with UK South, it appears to be more stable in the Central US. 

In an automated pipeline the only option is to abort, as I dont really want to have to log onto the machine and fix what is missing. The build can take up to 8 hours, so when a download fails after hour 5, you get a bit disheartened. the image isnt complete, and to then go on and manually push forwards always feels a bit of a hack.

Adding an option to allow for a retry would help improve the success rate of a build in an automated process. there would be a max retry of 5 attempts with an increase in wait time between each retry.

**Comment by sylviamoss** [comment]
Hey there! Thanks for reaching out. 
This seems to be a good idea to me but our team needs to discuss it together.  We’ll take a look when we get a chance! 👍

**Comment by SwampDragons** [comment]
Hi -- this makes a lot of sense to me for things like downloads, especially. For some other steps, it could be a little risky from an idempotence perspective, but I think it's worth investigating internally. Thanks for the feature request!

**Comment by sylviamoss** [comment]
Hey there! I've implemented a solution for this and you can use the binaries until we roll out the next release. Here the binaries https://circleci.com/gh/hashicorp/packer/46146#artifacts/containers/0
Now you can set in your provisioner the `max_retries` config as an integer number from **1** to **n** to make it retry **n** times in case of failures. 👍 
Remember you can always use `pause_before` as well, and this works together with `max_retries`. https://www.packer.io/docs/templates/provisioners.html#pausing-before-running
