### ISSUE TITLE
Ansible Paramiko (network_cli) and ansible(remote) provisioner

### ISSUE THREAD

**Issue by javcasalc** [hashicorp/packer#8973]
Hi

is there any specific configuration that enables ansible network modules (which make use of paramiko instead of ssh) to work with packer local server??

I always get this error:
```
    amazon-ebs: <127.0.0.1> using connection plugin network_cli (was local)
    amazon-ebs: <127.0.0.1> starting connection from persistent connection plugin
    amazon-ebs: <127.0.0.1> local domain socket does not exist, starting it
    amazon-ebs: <127.0.0.1> control socket path is /home/nroot/.ansible/pc/c6c54e275d
    amazon-ebs: <127.0.0.1> local domain socket listeners started successfully
    amazon-ebs: <127.0.0.1> loaded cliconf plugin ios from path /usr/local/lib/python3.7/site-packages/ansible/plugins/cliconf/ios.py for network_os ios
    amazon-ebs: <127.0.0.1> 
    amazon-ebs: <127.0.0.1> local domain socket path is /home/nroot/.ansible/pc/c6c54e275d
    amazon-ebs: <127.0.0.1> socket_path: /home/nroot/.ansible/pc/c6c54e275d
    amazon-ebs: fatal: [default]: FAILED! => {
    amazon-ebs:     "changed": false,
    amazon-ebs:     "msg": "Channel closed."
    amazon-ebs: }
```

I think one solution would be to generate the ansible inventory with the instance IP instead of 127.0.0.1 (packer local ssh server).

Thanks in advance.
J.

**Comment by SwampDragons** [comment]
Hi, @javcasalc, good timing! I'm currently working on implementing a PR that will give users the option of omitting the SSH proxy altogether in situations where the instances being provisioned a) have an IP address and b) are using SSH or WinRM to connect. 

You can find builds of the linked PR here: https://circleci.com/gh/hashicorp/packer/42423#artifacts/containers/0, and you can check the docs added in the linked PR for a usage example. I think this should resolve your issue :)
