### ISSUE TITLE
Can't complete Hyper-V ISO build without manual intervention

### ISSUE THREAD

**Issue by cskwrd** [hashicorp/packer#8977]
#### Overview of the Issue

I am trying to create an Alpine Linux Vagrant box. It doesn't switch the boot device to hard drive (from disk drive) automatically. After provisioning step, hangs on graceful shutdown until user logs in and issues `poweroff` command.

#### Reproduction Steps

1. Use Alpine Linux 3.11.5 (virt build) ISO (link can be found in linked packer template).
2. After `builder` `boot_command` step machine reboots (back to live ISO). Modify Hyper-V VM settings to boot from hard disk and reboot VM.
3. Eventually, packer detects the VM and begins provision step.
4. After provision completes, login to VM and `poweroff`.
5. Let packer finish.

### Packer version

Packer v1.5.5

### Simplified Packer Buildfile

[Packer Template](https://gist.github.com/cskwrd/b172758624e5b4d0660a19b9b6fae6ff)

Some information to note. I am trying to provision the *smallest* box I can. I am trying to generate a **Generation 2** Hyper-V VM.

### Operating system and Environment details

(Latest) Win 10 Pro, using preview terminal and (latest? v5) powershell.

### Log Fragments and crash.log files

[packer.log](https://gist.github.com/cskwrd/db623ee3789e38c55a65bc78e6aa7d68)

**Comment by sylviamoss** [comment]
Hello there! Thanks for reaching out. We’ll take a look when we get a chance.
Did the build work with previous versions?

**Comment by cskwrd** [comment]
@sylviamoss, I am not sure. This is my first time using packer. Can I use multiple versions side-by-side?

**Comment by cskwrd** [comment]
I was fiddling with this some more. I was able to produce a vagrant box in an entirely automatic fashion, and updated the template and log output to reflect the new run.

I found a workaround for the issue with the disk drive. I simply instruct the hyperv builder to attempt to boot from the virtual HDD. Doing so, causes the VM to fall back to the disk drive.

The issue where the builder times out while powering off the VM seems to be caused by an error where `poweroff` can't be located. To fix that, I fully qualified the exe.

I am not sure if the boot device issue is intended behavior or not, so I am not sure if there is a bug there. I believe a bug exists when issuing the shutdown command however. I don't think it should hang when there is an error with the command. It should report that to the user.

**Comment by SwampDragons** [comment]
Have you seen the [first_boot_device](https://packer.io/docs/builders/hyperv-iso.html#first_boot_device) option? That may be what you're looking for. 

Can you explain where you're doing the second part of step 2: 
> Modify Hyper-V VM settings to boot from hard disk and reboot VM.

You may end up wanting to do this as a two-part build, where after you finish step 1 and the boot command, you save the VM, shut it down, and then chain with a second packer template using the hyperv-vmx builder to launch from that hard disk. 

Since it sounds like you got it working and I think it looks like everything is behaving roughly as expected, (Packer doesn't expect to change the boot device halfway through a build) I'm going to close. Please reach out if you find any other issues though!

**Comment by cskwrd** [comment]
@SwampDragons I was originally using `first_boot_device` and set it to `DVD` to boot directly to the install media. To get the template to work, I now set `first_boot_device` to `SCSI:0:0`.

In step 2, I would open up the VM's settings in Hyper-V Manager and reorder the boot devices so that after reboot the hard drive would be used instead of returning to the install media.

What about packer hanging while attempting to shutdown the VM?

**Comment by SwampDragons** [comment]
I thought you discovered that this was a pathing error: 
> VM seems to be caused by an error where poweroff can't be located

Providing the fully qualified path in the shutdown_command seems appropriate.

**Comment by SwampDragons** [comment]
> I would open up the VM's settings in Hyper-V Manager 
That doesn't seem right; you don't want to have to manually do that in the middle of the build every time. I think you should chain the builds like I suggested above, which I think would solve this.

**Comment by cskwrd** [comment]
> That doesn't seem right; you don't want to have to manually do that in the middle of the build every time. I think you should chain the builds like I suggested above, which I think would solve this.

If `first_boot_device` is set to whatever the VHD is attached to then I no longer have to modify the settings mid-build. Is this okay?

**Comment by SwampDragons** [comment]
As long as you're not having to do things manually, sure.  There are probably multiple paths to get to the same outcome you want. Does that mean you've resolved all of your blockers here?
