### ISSUE TITLE
Powershell provision failing with valid_exit_codes list

### ISSUE THREAD

**Issue by jcoconnor** [hashicorp/packer#8982]
#### Overview of the Issue

Have just upgraded to Packer 1.5.5 and getting the following error when using ```valid_exit_codes``` in a powershell provisioner
```
vcenter-iso: output will be in this color.
 
1 error(s) decoding:
* error decoding 'valid_exit_codes[0]': 0 does not belong to  ExecutionPolicy values
```
#### Reproduction Steps

Use the following provisioner:
```
    {
      "type": "powershell",
      "inline" : [
        "C:/Packer/Scripts/test-packerbuild -TestPhase windows-update"
      ],
      "valid_exit_codes" : "{{user `winupdate_valid_exit_codes`}}"
    },
```

### Packer version

Version 1.5.5

### Simplified Packer Buildfile

You can view the file at: https://github.com/puppetlabs/puppetlabs-packer/blob/master/templates/win/common/vmware.vcenter.cygwin.json

### Operating system and Environment details

```Linux XXXXX 3.10.0-514.6.2.el7.x86_64 #1 SMP Thu Feb 23 03:04:39 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux```

**Comment by SwampDragons** [comment]
Hi, thanks for reporting. I found the issue and have a patch here: https://github.com/hashicorp/packer/pull/8997

a build of the patch can be found in our CI system here: https://circleci.com/gh/hashicorp/packer/43346#artifacts/containers/0

This will be fixed in the 1.5.6 release.

**Comment by jcoconnor** [comment]
@SwampDragons Thanks for the super fast response.

Will download and try this to confirm next week, but will also temporarily remove the ```valid_exit_codes``` statements until 1.5.6 comes out.

**Comment by jcoconnor** [comment]
Have just downloaded the fixed version and it appears to correctly address the issue - thanks.
