### ISSUE TITLE
Waiting for SSH to become available

### ISSUE THREAD

**Issue by syskar** [hashicorp/packer#8989]
Got one of the following errors ? See if the related guides can help.

* `Waiting for WinRM to become available` ?

  - See our basic WinRm Packer guide: https://www.packer.io/guides/automatic-operating-system-installs/autounattend_windows.html

* `Waiting for SSH to become available` ?

  - See our basic SSH Packer guide: https://www.packer.io/guides/automatic-operating-system-installs/preseed_ubuntu.html

Issues on GitHub are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here if you have a question.

- Packer Guides: https://www.packer.io/guides/index.html
- Discussion List: https://groups.google.com/group/packer-tool
- Any other questions can be sent to the packer section of the HashiCorp
  forum: https://discuss.hashicorp.com/c/packer
- Packer community links: https://www.packer.io/community.html

**Comment by syskar** [comment]
Trying to deploy CentOS 7 server From windows 10. 
Virtualbox VM is deployed and rebooted. But packer is awaiting for ssh connectivity as it needs to execute the provisioners 

=> virtualbox-iso: Using ssh communicator to connect: 127.0.0.1
==> virtualbox-iso: Waiting for SSH to become available...

**Comment by syskar** [comment]
Json file 
-------------

{
	"variables": {
		"vm_name": "Centos-7.4-vbox",
		"iso_url": "C:\\Per\\Guides\\iso\\CentOS-7-x86_64-DVD-1511\\CentOS-7-x86_64-DVD-1511.iso",
		"iso_sha256": "907e5755f824c5848b9c8efbb484f3cd945e93faa024bad6ba875226f9683b16"
	},

	"builders": [{
		"type": "virtualbox-iso",
		"communicator": "ssh",
		"guest_os_type": "RedHat_64",
		"vm_name": "{{user `vm_name`}}",
		"disk_size": "12288",
		"vboxmanage": [
			["modifyvm", "{{.Name}}", "--memory", "1024"],
			["modifyvm", "{{.Name}}", "--cpus", "2"],
			["modifyvm", "{{.Name}}", "--ioapic", "on"],
			["modifyvm", "{{.Name}}", "--pae", "on"],
			["modifyvm", "{{.Name}}", "--rtcuseutc", "on"],
			["modifyvm", "{{.Name}}", "--bioslogodisplaytime", "1"],
			["modifyvm", "{{.Name}}", "--nic1", "hostonly", "--hostonlyadapter1","VirtualBox Host-Only Ethernet Adapter"]
		],
		"iso_checksum_type": "sha256",
		"iso_url": "{{user `iso_url`}}",
		"iso_checksum": "{{user `iso_sha256`}}",
		"floppy_files": [
        "./anaconda-boot-ks.cfg"
		],
		"ssh_wait_timeout": "15m",
		"ssh_username": "vagrant",
		"ssh_password": "vagrant",
		"shutdown_command": "echo 'packer' | sudo -S shutdown -P now",
		"boot_wait": "5s",
		"boot_command": [
			"<esc>",
			"<wait>linux inst.sshd inst.text inst.ks=hd:/dev/fd0:anaconda-boot-ks.cfg<enter>"
		]
	}],
	"provisioners": [{
		"type": "shell",
		"execute_command": "echo 'vagrant' | {{.Vars}} sudo -S -E bash '{{.Path}}'",
		"scripts": [
			"C:/Per/Guides/Packer.io/Linux-Centos/scripts/vagrant.sh",
			"C:/Per/Guides/Packer.io/Linux-Centos/scripts/sshd.sh",
			"C:/Per/Guides/Packer.io/Linux-Centos/scripts/virtualbox.sh",
			"C:/Per/Guides/Packer.io/Linux-Centos/scripts/cleanup.sh"
		]
	}],
	"post-processors": [{
		"type": "vagrant",
		"output": "{{user `vm_name`}}.box",
		"keep_input_artifact": true
	}]
}

**Comment by syskar** [comment]
Ks.cfg
---------

install
cdrom
cmdline
lang en_US.UTF-8
keyboard us
timezone Asia/Kolkata --isUtc
auth --useshadow --enablemd5
firewall --disable --ssh --http
services --enabled=NetworkManager,sshd
eula --agreed
ignoredisk --only-use=sda
reboot

#version=DEVEL
# System authorization information
#auth --enableshadow --passalgo=sha512
# Use CDROM installation media
#cdrom
# Use graphical install
#graphical
# Run the Setup Agent on first boot
#firstboot --enable
#ignoredisk --only-use=sda
# Keyboard layouts
#keyboard --vckeymap=in-eng --xlayouts='in (eng)'
# System language
#lang en_IN.UTF-8

# Network information
#network  --bootproto=dhcp --device=enp0s3 --onboot=off --ipv6=auto
network  --bootproto=dhcp --device enp0s3 --onboot=yes --noipv6
#network  --bootproto=dhcp --device enp0s8 --onboot=yes --noipv6
#network --bootproto=static --ip=10.0.2.16 --netmask=255.255.255.0 --gateway=10.0.2.2 --nameserver 192.168.0.254
#network --onboot yes --device ens192 --bootproto dhcp --noipv6 --hostname UnixArena
network  --hostname=Centos-7.4-vbox

# Root password
rootpw --iscrypted $6$kN4dsEQCMJX6gdFb$KOhHGBsOP0tgDoXhgSd.yLwbmTk1Aj9QYADPamX95s15ixa/CeWWba485.5imhGacHaVfmg7ZB8jOaVTZfR.U1
# System timezone
timezone Asia/Kolkata --isUtc
# System bootloader configuration
bootloader --append=" crashkernel=auto" --location=mbr --boot-drive=sda
autopart --type=lvm
# Partition clearing information
clearpart --none --initlabel

#%packages
#repo --name=base --baseurl=http://mirror.cogentco.com/pub/linux/centos/7/os/x86_64/
%packages --nobase --ignoremissing
#@^minimal
@core

%end

%addon com_redhat_kdump --enable --reserve-mb='auto'
%end
%post
groupadd -g 9999 vagrant
useradd -u 9999 -g vagrant -G wheel vagrant
echo "vagrant" | passwd --stdin vagrant
sed -E -i '/Defaults[[:space:]]+requiretty/ s/^/#/' /etc/sudoers
echo "vagrant        ALL=(ALL)       NOPASSWD: ALL" >> /etc/sudoers
# configure vagrant user in sudoers
#echo "%vagrant ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers.d/vagrant
#chmod 0440 /etc/sudoers.d/vagrant
#cp /etc/sudoers /etc/sudoers.orig
#sed -i "s/^\(.*requiretty\)$/#\1/" /etc/sudoers
# keep proxy settings through sudo
#echo 'Defaults env_keep += "HTTP_PROXY HTTPS_PROXY FTP_PROXY RSYNC_PROXY NO_PROXY"' >> /etc/sudoers
sed -i "s/#PermitRootLogin yes/PermitRootLogin yes/g" /etc/ssh/sshd_config
#mv /etc/ssh/sshd_config.anaconda /etc/ssh/sshd_config
systemctl start sshd
%end

**Comment by syskar** [comment]
Ip is assigned automatically and able to ssh the box manually via putty from the windows box

**Comment by nywilken** [comment]
hi @syskar thanks for reaching out. The configs and settings spread across multiple comments makes it difficult to understand what might be happening. Seeing as you are getting the `Waiting for SSH to become available` issue please check the guides https://github.com/hashicorp/packer/issues/8989#issue-593314547 to see if they can help resolve your issue. We also have a community forum that may be able to help, as we generally reserve GitHub of bugs or feature enhancements, and try to help with small configuration issues when possible. 

Since we have guides to help with this particular problem I am going to close this issue. If you suspect that you are running into a bug, perhaps a case not captured in our guides, please open a new [bug issue ](https://github.com/hashicorp/packer/issues/new?labels=bug&template=bug_report.md) with your configuration, logs, and preseed files as gist or all within the issue description as code blocks. Cheers :smile:

**Comment by syskar** [comment]
Hi ,

 I am unable to find a resolution for the last 2 weeks. I had searched so many issues reported by many users and unable to get the result. Hence I opened a new issue for getting help. 

Instead of closing this, would request you to please look into this issue and advise. Please do let me know what are the details that you might need for tracing the cause. 

Thanks and regards,

Karthik. J
