### ISSUE TITLE
Packer HCL2 config file support

### ISSUE THREAD

**Issue by suntong** [hashicorp/packer#8999]
In https://packer.io/guides/hcl/from-json-v1/, it says

> Note: Starting from version 1.5.0 Packer can read HCL2 files.

And my packer is `packer_1.5.5_linux_amd64.zip` which is suppose to be able to read HCL2 files. However, when I tried it, I got 

    $ packer build hcl-example
    Failed to parse template: Error parsing JSON: invalid character '#' looking for beginning of value
    At line 1, column 1 (offset 1):
        1: #
          ^
    
    ==> Builds finished but no artifacts were created.

    $ packer build -h 
    Usage: packer build [options] TEMPLATE
    
      Will execute multiple builds in parallel as defined in the template.
      The various artifacts created by the template will be outputted.
    
    Options:
    
      -color=false                  Disable color output. (Default: color)
      -debug                        Debug mode enabled for builds.
      -except=foo,bar,baz           Run all builds and post-procesors other than these.
      -only=foo,bar,baz             Build only the specified builds.
      -force                        Force a build to continue if artifacts exist, deletes existing artifacts.
      -machine-readable             Produce machine-readable output.
      -on-error=[cleanup|abort|ask] If the build fails do: clean up (default), abort, or ask.
      -parallel=false               Disable parallelization. (Default: true)
      -parallel-builds=1            Number of builds to run in parallel. 0 means no limit (Default: 0)
      -timestamp-ui                 Enable prefixing of each ui output with an RFC3339 timestamp.
      -var 'key=value'              Variable for templates, can be used multiple times.
      -var-file=path                JSON file containing user variables. [ Note that even in HCL mode this expects file to contain JSON, a fix is comming soon ]

and I don't see any switches from above to switch to HCL2 mode. 

What I'm missing here?

    $ packer version
    Packer v1.5.5

The content of hcl-example is the whole list in https://packer.io/guides/hcl/from-json-v1/, and I also tried:

    mv hcl-example hcl-example.hcl
    
    $ packer validate hcl-example.hcl
    Failed to parse template: Error parsing JSON: invalid character '#' looking for beginning of value
    At line 1, column 1 (offset 1):
        1: #
          ^

Please comment. thx.

**Comment by zmingxie** [comment]
According to https://packer.io/docs/configuration/from-1.5/index.html#builds, your HCL template file needs to have the `.pkr.hcl` suffix.

**Comment by suntong** [comment]
Yep, that works, thanks a lot!

The `packer validate` not yet supporting HCL templates yet? 

```
$ packer validate hcl-example.pkr.hcl
Failed to parse template: Error parsing JSON: invalid character '#' looking for beginning of value
At line 1, column 1 (offset 1):
    1: #
      ^
```

**Comment by azr** [comment]
Hello I see that your original issue is no longer one thanks @zmingxie !

As of the `validate` command it's on our TODO list :). You can follow it here: #8538

Thanks !
