### ISSUE TITLE
Hyper-V Boot Order: Add support for setting the boot devices and their order

### ISSUE THREAD

**Issue by rgl** [hashicorp/packer#9001]
#### Feature Description

Right now the hyperv-iso provider only lets us to set `first_boot_device` which is quite unfortunate, because it leaves unwanted entries in the boot order.

I would like to set the entire boot devices and their order in an array, e.g.:

```json
boot_order: [
  "SCSI:0:0",
  "DISK",
  "DVD",
  "NET",
]
```

This can be done with [Set-VMFirmware -BootOrder](https://docs.microsoft.com/en-us/powershell/module/hyper-v/set-vmfirmware?view=win10-ps):

```powershell
# For generation 2 VMs:
Set-VMFirmware <VM NAME> -BootOrder <ARRAY OF DEVICES IN BOOT ORDER>
```

Without this, the vm/vagrant configuration ends up having the network/dvd before the hard disk, which is quite frustrating. Even more frustrating because you cannot remove devices.

What do you think?

**Comment by sylviamoss** [comment]
Hey @rgl, I think this is a good idea and I see you have a good solution for it. Do you want to implement it and open a pull request?

**Comment by rgl** [comment]
Will do!

**Comment by rgl** [comment]
@sylviamoss, I've create the PR at #9046. Let me known what you think.
