### ISSUE TITLE
Packer builder with attached disks ?

### ISSUE THREAD

**Issue by Boriszn** [hashicorp/packer#9004]
Hey Team.

Could you please help or suggest workaround. I've noticed that packer builders always removes attached disk after image creation. 

In our product we are using azure image copy extension which requires this disk to be attached otherwise it will not copy the image and throws error like below:

![image](https://user-images.githubusercontent.com/12999498/78557818-c9953f00-7811-11ea-89f6-e53684680968.png)

Also you could please suggest some quick fix in the source code, so I can clone it and use my version of packer.
Or any other option/link etc are welcome. We really need this fix

Many Thanks in advance,
Boris

**Comment by SwampDragons** [comment]
I don't think this is currently available, but I'd accept a PR for it. I'm not sure how easy it would be to implement, though.

**Comment by Boriszn** [comment]
Thanks a lot for the feedback.  I will create PR also add additional parameter e.g.`packer -delete-disk false` would this option ok for you ?

**Comment by SwampDragons** [comment]
This should only be a template option, not a command line parameter.

**Comment by Boriszn** [comment]
Make sense. So it should like below, right ? 
`````
{
  "builders": [{
    "type": "azure-arm",

    "delete_disk" : "true",
  }]
}
`````
