### ISSUE TITLE
Packer build behaves like make process

### ISSUE THREAD

**Issue by Roxyrob** [hashicorp/packer#9008]
#### Feature Description
Hi,
why packer doesn’t allow (like a make process) to reuse stages artifacts to avoid running always all stages: build, provisioning, post-processing.

eg:
image build from iso + kickstart is an heavy stage. Consolidated base image from various builders (ovf. from vmware-iso/virtualbox or other image data) can be reused in subsequent stages (provisioning, post-processing). The same for provisioning and post-processing, so one can consolidate/change each stage focusing on the next or apply change/debug intermediate stage without long running processes.

A make like approach would be very productive and efficient. Probably using state files to record stages info.

#### Use Case(s)

builder: virtualbox-iso
Povisioners: ...
Post-Processors: vagrant box

changes on every stage should not start from scratch but re-use previous unmodified stage. eg: changes on Post-Processors allow to re-use build + provisioner artifacts.

**Comment by SwampDragons** [comment]
This is a nice idea. Currently our recommendation is that you use several different Packer templates and chain them together using your ci/pipelineing tool so that the artifact from one is the input to another. This allows you to state the places in your build that are worth "snapshotting" for reuse in different stages, etc. 

While I agree that it would be a nice user experience improvement, we're probably not likely to implement what you're suggesting super soon, since chaining templates can accomplish the same thing.

**Comment by Roxyrob** [comment]
Do you mean something like:

template1.json -> build ova
template2.json -> how do you apply provisioning ?
template3.json -> how do you choice input ova to post-processing ? (artifact, file, ...)

Do you have samples ?

PS: "native support" with stages, optimization based on real configuration changes and state files  managed and controlled directly inside packer... will be all another experience however :D time and operation efficiency raising packer value a lot... IMHO ! An already valuable tool.

**Comment by Roxyrob** [comment]
@SwampDragons extremely usefull. Maybe a little cumbersome but I'll try different suggestions.

Thank you

**Comment by Roxyrob** [comment]
Hi @SwampDragons,
tried this:

- template1.json (build stage): builder virtualbox-iso alone (out: base ova as artifact)
- template2.1.json (prov stage):  builder virtualbox-ovf + prov(for ami) (out: prov ova as artifact)
- template2.2.json (prov stage):  builder virtualbox-ovf + prov(for vagrant) (out: prov ova as artifact)
- template3.1.json (prov stage):  builder null + post-processor amazon-import (some amazon-import issue... but this is another story... )

A bash script to run single/all stages, not so DRY for the cleaning stage (packer variables for vm name and output_directory to replicate manually in bash scripts, etc..), I'll waiting for all of this to be integrated in packer some day.

Is it possible to avoid/skip (useless) null builder ssh login ? For this case null builder is great without auth step that impose same host active and handle of credentials with security implications

**Comment by Roxyrob** [comment]
Found solution: https://github.com/hashicorp/packer/issues/7872#issuecomment-511916594
It's right not using provisioners at all !

**Comment by Roxyrob** [comment]
Hi @SwampDragons, one question: virtualbox-vmx is a typo ? Do you mean virtualbox-vm ?

**Comment by SwampDragons** [comment]
Sorry yes, vmx was a typo. I meant virtualbox-vm or virtualbox-ovf. 

Thanks for the notes -- I'll take a look at those.

**Comment by Roxyrob** [comment]
To do image creation in stages it wolud be useful a

> "skip-boot": "true",

flag for builder doing export. e.g. virtualbox-vm can take a VM, do a snapshot and export in ova format without booting vm at all.

**Comment by SwampDragons** [comment]
That's a cool idea.

**Comment by Roxyrob** [comment]
@SwampDragons, there is a chance to have this option ?

**Comment by SwampDragons** [comment]
I'm not currently working on it, but PRs are welcome.
