### ISSUE TITLE
vsphere-iso DRS cluster doesn't work

### ISSUE THREAD

**Issue by denispar** [hashicorp/packer#9013]
#### Overview of the Issue

Run vsphere-iso with 
"cluster": some cluster with DRS
"host" either not specified or some dummy value

Result: 
2020/04/06 13:35:37 [INFO] (telemetry) ending vsphere-iso
Build 'vsphere-iso' errored: error creating vm: host '' not found
2020/04/06 13:35:37 machine readable: error-count []string{"1"}

==> Some builds didn't complete successfully and had errors:
2020/04/06 13:35:37 machine readable: vsphere-iso,error []string{"error creating vm: host '' not found"}

#### Reproduction Steps

Deploy VC and ESX. Add cluster with DRS. Add ESX to this cluster. Try to run with cluster and no host.

### Packer version

1.5.5

### Simplified Packer Buildfile

```
{
  "builders": [
    {
      "type": "vsphere-iso",
      "vcenter_server": "<CENSORED IP>",
      "username": "administrator@vsphere.local",
      "guest_os_type": "vmwarePhoton64Guest",
      "password": "<CENSORED>",
      "insecure_connection": "true",
      "datastore": "datastore1",
      "vm_name": "vm-packer",
      "cluster": "build_cluster",
      "CPUs": 1,
      "RAM": 4096,
      "disk_size": 32768,
      "disk_thin_provisioned": true,
      "network_card": "e1000e",
      "usb_controller": true,
      "http_directory": "scripts",
      "cdrom_type": "sata",
      "iso_urls": "http://dl.bintray.com/vmware/photon/3.0/Rev2/iso/photon-3.0-58f9c74.iso",
      "iso_checksum": "6661308693ab4e662c044641cf537f41a92ac1267b85069c2ce53eec53c59100",
      "boot_wait": "4m",
      "boot_command": [
        "<esc><wait>",
        "vmlinuz initrd=initrd.img root=/dev/ram0 loglevel=3 ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/photon-kickstart.json photon.media=cdrom",
        "<enter>"
      ],
      "ssh_username": "root",
      "ssh_password": "vmware",
      "export": {
        "force": true,
        "output_directory": "./output_vsphere"
      }
    }
  ]
}
```

### Operating system and Environment details

Doesn't matter

### Log Fragments and crash.log files

==> vsphere-iso: Uploading 137ca620ef1fb6a4d8c636a57e9a450cc0ec988a.iso to packer_cache/137ca620ef1fb6a4d8c636a57e9a450cc0ec988a.iso
==> vsphere-iso: File already uploaded; continuing
==> vsphere-iso: Creating VM...
==> vsphere-iso: error creating vm: host '' not found
==> vsphere-iso: Step "StepCreateVM" failed
==> vsphere-iso: [c] Clean up and exit, [a] abort without cleanup, or [r] retry step (build may fail even if retry succeeds)? c
2020/04/06 13:35:37 [INFO] (telemetry) ending vsphere-iso
Build 'vsphere-iso' errored: error creating vm: host '' not found
2020/04/06 13:35:37 machine readable: error-count []string{"1"}

==> Some builds didn't complete successfully and had errors:
2020/04/06 13:35:37 machine readable: vsphere-iso,error []string{"error creating vm: host '' not found"}
==> Builds finished but no artifacts were created.
2020/04/06 13:35:37 [INFO] (telemetry) Finalizing.
==> Some builds didn't complete successfully and had errors:
--> vsphere-iso: error creating vm: host '' not found

==> Builds finished but no artifacts were created.
2020/04/06 13:35:38 waiting for all plugin processes to complete...
2020/04/06 13:35:38 /dbc/sc-dbc1214/dparnovskiy/photon_ova/packer-1.5.5/packer: plugin process exited

**Comment by denispar** [comment]
I have looked into the code:
https://github.com/hashicorp/packer/blob/fc911f07314c08f1df624a14bd23318d4dacbbd6/builder/vsphere/iso/step_create.go
Looks like their expectations is: driver will ignore empty "Host" parameter for DRS cluster.
Reality: it complains that host '' or whatever name you put, is invalid.

I do not know how the driver would react to nil as host but from this
https://github.com/hashicorp/packer/blob/fac320d290bf491f2341740f6751bceda75e858b/builder/vsphere/common/config_location.go
I see they threat missing "host" as ""

**Comment by denispar** [comment]
More precisely, this line would not work with host == ''

https://github.com/hashicorp/packer/blob/master/builder/vsphere/driver/vm.go#L133

**Comment by SwampDragons** [comment]
Thanks for opening -- given that you're already diving into the code, if you're comfortable opening a PR that will fix this behavior, I'd happily review or give pointers.

**Comment by brettjacobson** [comment]
Is there any current workaround to this bug?  This seems like a complete show-stopper if you are using a Cluster with DRS

**Comment by brettjacobson** [comment]
The workaround seems to be to fill in the `host` field with a valid vSphere host to satisfy the validation (garbage text fails validation), but the VMs will still be provisioned on whatever host that DRS decides.  But the value must be a valid vSphere ESX host.

**Comment by denispar** [comment]
In order to debug further, I have redeployed my cluster and the build passed. 
Unfortunately I did not keep cluster details so I cannot tell if VC version is different but I expect so.
Suspicion: vsphere API now doesn't require host to be filled in for DRS.
