### ISSUE TITLE
JSON to HCL transpiler

### ISSUE THREAD

**Issue by azr** [hashicorp/packer#9015]
It's all in the title; now that we have HCL2 variables I think we could write a first beta version of the JSON files to HCL2 files transpiler. It would be nice to have the `validate` command working for Packer HCL2 first though (issue: #8538).

Also there could be some minor turbulences doing this as I expect there is a lot of already existing buildfiles in the universe and edge cases will occur.

**Comment by ad-m** [comment]
I have the impression that passing through  #9282 might provide different real cases of using Packer as the initial source of test cases.
