### ISSUE TITLE
Google Compute Builder should support default disk_size

### ISSUE THREAD

**Issue by tmmruk** [hashicorp/packer#9023]
#### Feature Description

Currently the Google Compute builder (https://packer.io/docs/builders/googlecompute.html) disk_size attribute defaults to 10GB if not specified. This works for most Linux images however Google have recently started to increase the default to 20GB and for Windows servers this has always been 50GB.

If would be nice not to have to specify this value and it automatically defaults to the smallest size the image supports. This is the way Terraform works so it would be nice to see the same in Packer.

#### Use Case(s)

- Avoids having to manage image size increases Google make which can cause automated packer builds to fail.
- Allows most efficient image size to be used so deployed machines are as small as possible.

**Comment by farahfa** [comment]
We have run into the same exact issue! Glad there's an open ticket for this already.
