### ISSUE TITLE
Vsphere-ISO: Option to enable/disable logging of Virtual Machine

### ISSUE THREAD

**Issue by stayfrostnl** [hashicorp/packer#9026]
Hello,

I am looking for an option to disable the Virtual Machine logging. In the .vmx you can disable this with

logging=false

But I can't seem to find an option in the Vsphere-iso Builder to create a template with this setting.

**Comment by SwampDragons** [comment]
This isn't currently possible in the vsphere-iso builder -- unlike the vmware builder, I don't think we manually create the VMX. I'm re-labeling this as a feature request. 

I'm not sure when I'll have a chance to work on this, but community contributions are welcome.

**Comment by SwampDragons** [comment]
Oh, I take it back -- you can set this in [configuration_parameters](https://packer.io/docs/builders/vsphere-iso.html#extra-configuration-parameters)

example: 
```
      "configuration_parameters": {
        "logging": "FALSE"
      },
```
