### ISSUE TITLE
Access all source AMI attributes like its Date

### ISSUE THREAD

**Issue by nitrocode** [hashicorp/packer#9029]
Please search the existing issues for relevant feature requests, and use the
reaction feature
(https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
to add upvotes to pre-existing requests.

#### Feature Description

Would be nice to access other source AMI attributes like its date

#### Use Case(s)

I'd like to not only grab the source ami (which is currently possible) but also the source ami's date, and perhaps additional parameters of the source ami, and set those as new tags on my newly created AMI.

Thanks!

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out with this suggestion. I'm not sure when the team will get a chance to work on this, but pull requests are always welcome.
