### ISSUE TITLE
-force not working?

### ISSUE THREAD

**Issue by jpgrall** [hashicorp/packer#9036]
#### Overview of the Issue

When attempting to run a packer build in the packer container, using the vsphere-iso builder, -force isn't working to remove a leftover VM.  Not a huge issue, just annoying.

#### Reproduction Steps

Run a build and cancel the build leaving a leftover VM.  Power off the leftover VM and rerun a new build with -force.  The expected behaviour is for -force to remove the leftover VM and create new one, but it doesn't.

### Packer version

1.5.5

From `packer version`

### Simplified Packer Buildfile

If the file is longer than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/) of the log or use the [Github detailed
format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d)
instead of posting it directly in the issue.

### Operating system and Environment details

packer docker image

### Logs

 <details>
<summary>PACKER LOG</summary>
2020/04/09 19:24:05 Checking 'PACKER_CONFIG' for a config file path
2020/04/09 19:24:05 'PACKER_CONFIG' not set; checking the default config file path
2020/04/09 19:24:05 Attempting to open config file: /tmp/.packerconfig
2020/04/09 19:24:05 [WARN] Config file doesn't exist: /tmp/.packerconfig
2020/04/09 19:24:05 Setting cache directory: /workspace/packer_cache
Running in background, not using a TTY
2020/04/09 19:24:05 Creating plugin client for path: /bin/packer
2020/04/09 19:24:05 Starting plugin: /bin/packer []string{"/bin/packer", "plugin", "packer-builder-vsphere-iso"}
2020/04/09 19:24:05 Waiting for RPC address for: /bin/packer
2020/04/09 19:24:05 packer-builder-vsphere-iso plugin: [INFO] Packer version: 1.5.5 [go1.13.7 linux amd64]
2020/04/09 19:24:05 packer-builder-vsphere-iso plugin: Checking 'PACKER_CONFIG' for a config file path
2020/04/09 19:24:05 packer-builder-vsphere-iso plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/04/09 19:24:05 packer-builder-vsphere-iso plugin: Attempting to open config file: /tmp/.packerconfig
2020/04/09 19:24:05 packer-builder-vsphere-iso plugin: [WARN] Config file doesn't exist: /tmp/.packerconfig
2020/04/09 19:24:05 packer-builder-vsphere-iso plugin: Setting cache directory: /workspace/packer_cache
2020/04/09 19:24:05 packer-builder-vsphere-iso plugin: args: []string{"packer-builder-vsphere-iso"}
2020/04/09 19:24:05 Received unix RPC address for /bin/packer: addr is /tmp/packer-plugin558768450
2020/04/09 19:24:05 packer-builder-vsphere-iso plugin: Plugin address: unix /tmp/packer-plugin558768450
2020/04/09 19:24:05 packer-builder-vsphere-iso plugin: Waiting for connection...
2020/04/09 19:24:05 packer-builder-vsphere-iso plugin: Serving a plugin connection...
2020/04/09 19:24:05 Creating plugin client for path: /bin/packer
2020/04/09 19:24:05 Starting plugin: /bin/packer []string{"/bin/packer", "plugin", "packer-provisioner-windows-shell"}
2020/04/09 19:24:05 Waiting for RPC address for: /bin/packer
2020/04/09 19:24:05 Received unix RPC address for /bin/packer: addr is /tmp/packer-plugin095649605
2020/04/09 19:24:05 packer-provisioner-windows-shell plugin: [INFO] Packer version: 1.5.5 [go1.13.7 linux amd64]
2020/04/09 19:24:05 packer-provisioner-windows-shell plugin: Checking 'PACKER_CONFIG' for a config file path
2020/04/09 19:24:05 packer-provisioner-windows-shell plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/04/09 19:24:05 packer-provisioner-windows-shell plugin: Attempting to open config file: /tmp/.packerconfig
2020/04/09 19:24:05 packer-provisioner-windows-shell plugin: [WARN] Config file doesn't exist: /tmp/.packerconfig
2020/04/09 19:24:05 packer-provisioner-windows-shell plugin: Setting cache directory: /workspace/packer_cache
2020/04/09 19:24:05 packer-provisioner-windows-shell plugin: args: []string{"packer-provisioner-windows-shell"}
2020/04/09 19:24:05 packer-provisioner-windows-shell plugin: Plugin address: unix /tmp/packer-plugin095649605
2020/04/09 19:24:05 packer-provisioner-windows-shell plugin: Waiting for connection...
2020/04/09 19:24:05 packer-provisioner-windows-shell plugin: Serving a plugin connection...
2020/04/09 19:24:05 Creating plugin client for path: /bin/packer
2020/04/09 19:24:05 Starting plugin: /bin/packer []string{"/bin/packer", "plugin", "packer-provisioner-powershell"}
2020/04/09 19:24:05 Waiting for RPC address for: /bin/packer
2020/04/09 19:24:05 Received unix RPC address for /bin/packer: addr is /tmp/packer-plugin849076698
2020/04/09 19:24:05 packer-provisioner-powershell plugin: [INFO] Packer version: 1.5.5 [go1.13.7 linux amd64]
2020/04/09 19:24:05 packer-provisioner-powershell plugin: Checking 'PACKER_CONFIG' for a config file path
2020/04/09 19:24:05 packer-provisioner-powershell plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/04/09 19:24:05 packer-provisioner-powershell plugin: Attempting to open config file: /tmp/.packerconfig
2020/04/09 19:24:05 packer-provisioner-powershell plugin: [WARN] Config file doesn't exist: /tmp/.packerconfig
2020/04/09 19:24:05 packer-provisioner-powershell plugin: Setting cache directory: /workspace/packer_cache
2020/04/09 19:24:05 packer-provisioner-powershell plugin: args: []string{"packer-provisioner-powershell"}
2020/04/09 19:24:05 packer-provisioner-powershell plugin: Plugin address: unix /tmp/packer-plugin849076698
2020/04/09 19:24:05 packer-provisioner-powershell plugin: Waiting for connection...
2020/04/09 19:24:05 packer-provisioner-powershell plugin: Serving a plugin connection...
2020/04/09 19:24:05 Creating plugin client for path: /bin/packer
2020/04/09 19:24:05 Starting plugin: /bin/packer []string{"/bin/packer", "plugin", "packer-provisioner-file"}
2020/04/09 19:24:05 Waiting for RPC address for: /bin/packer
2020/04/09 19:24:05 packer-provisioner-file plugin: [INFO] Packer version: 1.5.5 [go1.13.7 linux amd64]
2020/04/09 19:24:05 packer-provisioner-file plugin: Checking 'PACKER_CONFIG' for a config file path
2020/04/09 19:24:05 packer-provisioner-file plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/04/09 19:24:05 packer-provisioner-file plugin: Attempting to open config file: /tmp/.packerconfig
2020/04/09 19:24:05 packer-provisioner-file plugin: [WARN] Config file doesn't exist: /tmp/.packerconfig
2020/04/09 19:24:05 packer-provisioner-file plugin: Setting cache directory: /workspace/packer_cache
2020/04/09 19:24:05 packer-provisioner-file plugin: args: []string{"packer-provisioner-file"}
2020/04/09 19:24:05 packer-provisioner-file plugin: Plugin address: unix /tmp/packer-plugin682524482
2020/04/09 19:24:05 packer-provisioner-file plugin: Waiting for connection...
2020/04/09 19:24:05 Received unix RPC address for /bin/packer: addr is /tmp/packer-plugin682524482
2020/04/09 19:24:05 packer-provisioner-file plugin: Serving a plugin connection...
2020/04/09 19:24:05 Creating plugin client for path: /bin/packer
2020/04/09 19:24:05 Starting plugin: /bin/packer []string{"/bin/packer", "plugin", "packer-provisioner-shell-local"}
2020/04/09 19:24:05 Waiting for RPC address for: /bin/packer
2020/04/09 19:24:05 packer-provisioner-shell-local plugin: [INFO] Packer version: 1.5.5 [go1.13.7 linux amd64]
2020/04/09 19:24:05 packer-provisioner-shell-local plugin: Checking 'PACKER_CONFIG' for a config file path
2020/04/09 19:24:05 packer-provisioner-shell-local plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/04/09 19:24:05 packer-provisioner-shell-local plugin: Attempting to open config file: /tmp/.packerconfig
2020/04/09 19:24:05 packer-provisioner-shell-local plugin: [WARN] Config file doesn't exist: /tmp/.packerconfig
2020/04/09 19:24:05 packer-provisioner-shell-local plugin: Setting cache directory: /workspace/packer_cache
2020/04/09 19:24:05 packer-provisioner-shell-local plugin: args: []string{"packer-provisioner-shell-local"}
2020/04/09 19:24:05 packer-provisioner-shell-local plugin: Plugin address: unix /tmp/packer-plugin442244314
2020/04/09 19:24:05 packer-provisioner-shell-local plugin: Waiting for connection...
2020/04/09 19:24:05 Received unix RPC address for /bin/packer: addr is /tmp/packer-plugin442244314
2020/04/09 19:24:05 packer-provisioner-shell-local plugin: Serving a plugin connection...
2020/04/09 19:24:05 Creating plugin client for path: /bin/packer
2020/04/09 19:24:05 Starting plugin: /bin/packer []string{"/bin/packer", "plugin", "packer-provisioner-powershell"}
2020/04/09 19:24:05 Waiting for RPC address for: /bin/packer
2020/04/09 19:24:05 packer-provisioner-powershell plugin: [INFO] Packer version: 1.5.5 [go1.13.7 linux amd64]
2020/04/09 19:24:05 packer-provisioner-powershell plugin: Checking 'PACKER_CONFIG' for a config file path
2020/04/09 19:24:05 packer-provisioner-powershell plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/04/09 19:24:05 packer-provisioner-powershell plugin: Attempting to open config file: /tmp/.packerconfig
2020/04/09 19:24:05 packer-provisioner-powershell plugin: [WARN] Config file doesn't exist: /tmp/.packerconfig
2020/04/09 19:24:05 packer-provisioner-powershell plugin: Setting cache directory: /workspace/packer_cache
2020/04/09 19:24:05 packer-provisioner-powershell plugin: args: []string{"packer-provisioner-powershell"}
2020/04/09 19:24:05 packer-provisioner-powershell plugin: Plugin address: unix /tmp/packer-plugin130778556
2020/04/09 19:24:05 packer-provisioner-powershell plugin: Waiting for connection...
2020/04/09 19:24:05 Received unix RPC address for /bin/packer: addr is /tmp/packer-plugin130778556
2020/04/09 19:24:05 packer-provisioner-powershell plugin: Serving a plugin connection...
2020/04/09 19:24:05 Creating plugin client for path: /bin/packer
2020/04/09 19:24:05 Starting plugin: /bin/packer []string{"/bin/packer", "plugin", "packer-post-processor-manifest"}
2020/04/09 19:24:05 Waiting for RPC address for: /bin/packer
2020/04/09 19:24:05 packer-post-processor-manifest plugin: [INFO] Packer version: 1.5.5 [go1.13.7 linux amd64]
2020/04/09 19:24:05 packer-post-processor-manifest plugin: Checking 'PACKER_CONFIG' for a config file path
2020/04/09 19:24:05 packer-post-processor-manifest plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/04/09 19:24:05 packer-post-processor-manifest plugin: Attempting to open config file: /tmp/.packerconfig
2020/04/09 19:24:05 packer-post-processor-manifest plugin: [WARN] Config file doesn't exist: /tmp/.packerconfig
2020/04/09 19:24:05 packer-post-processor-manifest plugin: Setting cache directory: /workspace/packer_cache
2020/04/09 19:24:05 packer-post-processor-manifest plugin: args: []string{"packer-post-processor-manifest"}
2020/04/09 19:24:05 packer-post-processor-manifest plugin: Plugin address: unix /tmp/packer-plugin520270914
2020/04/09 19:24:05 packer-post-processor-manifest plugin: Waiting for connection...
2020/04/09 19:24:05 Received unix RPC address for /bin/packer: addr is /tmp/packer-plugin520270914
2020/04/09 19:24:05 packer-post-processor-manifest plugin: Serving a plugin connection...
2020/04/09 19:24:05 Build debug mode: false
2020/04/09 19:24:05 Force build: true
2020/04/09 19:24:05 On error: 
2020/04/09 19:24:05 Preparing build: vsphere-iso
2020/04/09 19:24:05 Waiting on builds to complete...
2020/04/09 19:24:05 Starting build run: vsphere-iso
2020/04/09 19:24:05 Running builder: vsphere-iso
2020/04/09 19:24:05 [INFO] (telemetry) Starting builder vsphere-iso
2020/04/09 19:24:06 [INFO] (telemetry) ending vsphere-iso
2020/04/09 19:24:06 machine readable: error-count []string{"1"}
==> Some builds didn't complete successfully and had errors:
2020/04/09 19:24:06 machine readable: vsphere-iso,error []string{"error creating vm: The name 'W2K19StdBaseTemplate-packer-docker' already exists."}
==> Builds finished but no artifacts were created.
2020/04/09 19:24:06 [INFO] (telemetry) Finalizing.
2020/04/09 19:24:06 waiting for all plugin processes to complete...
2020/04/09 19:24:06 /bin/packer: plugin process exited
2020/04/09 19:24:06 /bin/packer: plugin process exited
2020/04/09 19:24:06 /bin/packer: plugin process exited
2020/04/09 19:24:06 /bin/packer: plugin process exited
2020/04/09 19:24:06 /bin/packer: plugin process exited
2020/04/09 19:24:06 /bin/packer: plugin process exited
2020/04/09 19:24:06 /bin/packer: plugin process exited
</details>

**Comment by SwampDragons** [comment]
Hi, thanks for reporting. We probably just need to pass the "force" flag into https://github.com/hashicorp/packer/blob/master/builder/vsphere/driver/vm.go#L101 and do an error test to create the VM even if the name exists. 

I'll try to create a repro case and fix this next time I spin up a VSphere cluster.

**Comment by jhawk28** [comment]
It tries to delete the VM before it makes the CreateVM call: https://github.com/hashicorp/packer/blob/master/builder/vsphere/iso/step_create.go#L110

**Comment by mdepot** [comment]
#### Closely Related:
When -force is passed and the VM already exists packer will still say it's going to delete it, but then it will fail to do so if that VM happens to be running:
```
==> vsphere-iso: the vm/template packer-test-vm already exists, but deleting it due to -force flag
==> vsphere-iso: Creating VM...
Build 'vsphere-iso' errored: error creating vm: The name 'packer-test-vm' already exists.

==> Some builds didn't complete successfully and had errors:
--> vsphere-iso: error creating vm: The name 'packer-test-vm' already exists.
```
When -force is passed and the VM already exists AND is still running, it's debatable what the correct action to take is.

One option is after checking if the VM already exists, also check if it is running, and if so power it down and then delete it.  This enforces -force even if the VM is running, instead of failing with the message above like it does now.  

Another option is to abort the -force when the VM is already running.  This should still check if the VM is running and if so display a better error message that says so rather than the message above.  Additionally, in this case we could add a new flag -forceoff (or similar) that could be passed in addition to -force.  Then, only when both of these are passed does an existing running VM get powered off and deleted.

**Comment by jhawk28** [comment]
my pull request will power off the vm before its doing the destroy. I did consider the "do you really want the vm to be deleted if it is powered on" and came to the conclusion that if you wanted a safe way to process it, then dont use -force. If we wanted to add yet another flag, then it could use that boolean to decide whether to call the poweroff or not.
