### ISSUE TITLE
error-cleanup-provisioner not working in HCL2 format

### ISSUE THREAD

**Issue by galet** [hashicorp/packer#9042]
#### Overview of the Issue

When `error-cleanup-provisioner` is used in the build block packer fails with:
```
Error: Unsupported block type

  on tcagent.pkr.hcl line 59, in build:
  59:     error-cleanup-provisioner "shell" {

Blocks of type "error-cleanup-provisioner" are not expected here.
```

### Packer version

`1.5.5`

### Simplified Packer Buildfile
Example:
```
... 
build {
    sources = [
      "source.oracle-oci.example"
    ]
    provisioner "shell" {
      inline = [ "echo hello" ]
    }
    error-cleanup-provisioner "shell" {
      inline = ["echo 'rubber ducky'> ducky.txt"]
    }
}
```

### Operating system and Environment details
macOS

**Comment by azr** [comment]
Hello there, thanks for reporting; the `error-cleanup-provisioner` was not ported to HCL2 yet, it's going to come soon 🙂.

**Comment by solazs** [comment]
That's a deal breaker for me :(
I need some way to deprovision nodes from the puppet-master if there's an error during the puppet run.
Any workarounds to run a shell script on error?

**Comment by solazs** [comment]
To answer my own quesition:
I ended up writing a wrapper for running the packer command.
On non-zero exit code it runs the cleanup script.
