### ISSUE TITLE
The iso_checksum_url doesn't work with local files

### ISSUE THREAD

**Issue by ruzickap** [hashicorp/packer#9047]
Hello.

It looks like this issue #8774 related to `iso_checksum_url` was partially fixed.

If I use `iso_checksum_url` pointing to local file as described in the Packer documentation (https://packer.io/docs/builders/qemu.html#iso-configuration) - it is not working:

```bash
wget -c http://archive.ubuntu.com/ubuntu/dists/bionic-updates/main/installer-amd64/current/images/SHA256SUMS
cat > bug.json << EOF
{
  "builders": [
    {
      "vm_name": "test",
      "type": "qemu",
      "ssh_username": "root",
      "iso_checksum_url": "./SHA256SUMS",
      "iso_urls": "http://archive.ubuntu.com/ubuntu/dists/bionic-updates/main/installer-amd64/current/images/netboot/mini.iso"
    }
  ]
}
EOF

wget -c https://releases.hashicorp.com/packer/1.5.5/packer_1.5.5_linux_amd64.zip

unzip packer_1.5.5_linux_amd64.zip

PACKER_LOG=1 ./packer validate ./bug.json
```

The error output:

```text
...
2020/03/27 09:50:34 Received unix RPC address for /tmp/a/packer: addr is /tmp/packer-plugin997301603
2020/03/27 09:50:34 packer-builder-qemu plugin: Serving a plugin connection...
2020/03/27 09:50:34 Preparing build: qemu
2020/03/27 09:50:34 packer-builder-qemu plugin: use detected accelerator: kvm
2020/03/27 09:50:34 packer-builder-qemu plugin: MemorySize 0 is too small, using default: 512
2020/03/27 09:50:34 packer-builder-qemu plugin: CpuCount 0 too small, using default: 1
Template validation failed. Errors are shown below.
2020/03/27 09:50:34 Build 'qemu' prepare failure: 1 error(s) occurred:

* Couldn't extract checksum from checksum file: Error downloading checksum file: relative paths require a module with a pwd

* Couldn't extract checksum from checksum file: Error downloading checksum file: relative paths require a module with a pwd
2020/03/27 09:50:34 [INFO] (telemetry) Finalizing.

Errors validating build 'qemu'. 1 error(s) occurred:

* Couldn't extract checksum from checksum file: Error downloading checksum file: relative paths require a module with a pwd
2020/03/27 09:50:34 waiting for all plugin processes to complete...
2020/03/27 09:50:34 /tmp/a/packer: plugin process exited
```

Thanks a lot for your help...

PetrR

**Comment by sylviamoss** [comment]
Thanks for reaching out. We’ll take a look when we get a chance.
if you write the full path for your checksum file instead of a relative one, does it work as a temporary workaround?

**Comment by ruzickap** [comment]
Yes... using full path is working:

```json
"iso_checksum_url": "/tmp/test/SHA256SUMS",
```

Anyway it would be nice to have possibility to use relative paths as well... (like it is in the documentation: https://packer.io/docs/builders/qemu.html#iso-configuration)

Thank you...

**Comment by sylviamoss** [comment]
Yes for sure! I just wanted to make sure so we can go straight forward to where we need to fix! Thanks :D

**Comment by ruzickap** [comment]
Hello.

I tested this issue with Packer 1.5.6 and I still get the same "bad" results like mentioned in first comment. 

I'm not sure if this issues "should" be already fixed in Packer 1.5.6 but this bug is still there...

**Comment by sylviamoss** [comment]
Hey @ruzickap, this wasn't released yet. The PR was merged after the last release. You can use our [nightly](https://github.com/hashicorp/packer/releases/tag/nightly) pre-release binaries which contains these changes. Let me know if you still see bad results with nightly.

**Comment by ruzickap** [comment]
Oh... I'm sorry - I didn't know that.

The nightly release is working fine...

Thank you...
