### ISSUE TITLE
vsphere-iso builder - Please update documentation on how to support multiple hard drives.

### ISSUE THREAD

**Issue by ZappedC64** [hashicorp/packer#9051]
Please search the existing issues for relevant feature requests, and use the
reaction feature
(https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
to add upvotes to pre-existing requests.

#### Feature Description

Please update documentation on how to support multiple hard drives. I found the "storage" configuration section in the vsphere-iso builder docs but could not figure out how to configure the parameters. 

#### Use Case(s)

Several Security Technical Implementation Guides (STIGs) require separate drives and partitions to store the /tmp and /var directories. SAP HANA builds also require separate drives for data and logs.

**Comment by jhawk28** [comment]
this documents what the DiskConfig should contain: https://packer.io/docs/builders/vsphere-iso.html#storage-configuration

We should make it more clear that the storage field maps to this. In addition to including a sample json that can be used as a foundation. (Like we did for the Export)

**Comment by jhawk28** [comment]
Here is an example to get you started...
```json
"storage": [
  {
    "disk_size": 15000,
  },
  {
    "disk_size": 20000,
    "disk_thin_provisioned": true
  }
],
```

**Comment by ZappedC64** [comment]
Ah! Perfect! TY!

 

Thanks,

/Raj

**Comment by ZappedC64** [comment]
Question answered.

**Comment by jhawk28** [comment]
@ZappedC64 does this help out more? https://deploy-preview-9056--packer-www.netlify.com/docs/builders/vmware/vsphere-iso/#storage-configuration

**Comment by ZappedC64** [comment]
Absolutely perfect and crystal clear. Thank you @jhawk28 !!!
