### ISSUE TITLE
Packer 1.5.2, 1.5.3, 1.5.5 cannot start builder vpshere-iso

### ISSUE THREAD

**Issue by Beberd** [hashicorp/packer#9058]
#### Overview of the Issue
Packer don't work with vsphere-iso while using the parameter -only=vsphere-iso.

#### Reproduction Steps
1. Start packer not using the parameter -only
```
$ packer build /home/user/packer.json
packer-hhh: output will be in this color.
Build 'packer-hhh' errored: Post https://127.0.0.1/sdk: dial tcp 127.0.0.1:443: connect: connection refused
==> Some builds didn't complete successfully and had errors:
--> packer-hhh: Post https://127.0.0.1/sdk: dial tcp 127.0.0.1:443: connect: connection refused
```
It works.
2. Start packer using the paramater -only
```
$ build --only=vsphere-iso /home/user/packer.json
==> Builds finished but no artifacts were created.
```

Packer do not start builder vsphere-iso.

### Packer version
I have tried the following version
- packer_1.5.2_linux_amd64.zip
- packer_1.5.3_linux_amd64.zip
- packer_1.5.5_linux_amd64.zip 

### Simplified Packer Buildfile
Here my small example for testing
```{
  "builders": [
    {
      "type": "vsphere-iso",
      "name": "packer-hhh",
      "disk_size": "15000",
      "vm_name": "vm_name",
      "host": "127.0.0.1",
      "vcenter_server": "127.0.0.1",
      "datacenter": "Datacenter",
      "username": "vcsa_username",
      "password": "vcsa_password",
      "ssh_password": "username",
      "ssh_username": "password"
    }
  ]
}
```

### Operating system and Environment details
```$lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```
```$uname -a
Linux computer 5.3.0-46-generic #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

### Log Fragments and crash.log files
```
2020/04/14 10:44:30 [INFO] Packer version: 1.5.5 [go1.13.7 linux amd64]
2020/04/14 10:44:30 Checking 'PACKER_CONFIG' for a config file path
2020/04/14 10:44:30 'PACKER_CONFIG' not set; checking the default config file path
2020/04/14 10:44:30 Attempting to open config file: /home/user/.packerconfig
2020/04/14 10:44:30 [WARN] Config file doesn't exist: /home/user/.packerconfig
2020/04/14 10:44:30 Setting cache directory: /home/user/packer_cache
2020/04/14 10:44:30 [ERR] Checkpoint error: EOF
2020/04/14 10:44:30 Build debug mode: false
2020/04/14 10:44:30 Force build: false

2020/04/14 10:44:30 On error: 
2020/04/14 10:44:30 Waiting on builds to complete...
==> Builds finished but no artifacts were created.
==> Builds finished but no artifacts were created.
2020/04/14 10:44:30 [INFO] (telemetry) Finalizing.
2020/04/14 10:44:30 waiting for all plugin processes to complete...
```

**Comment by nywilken** [comment]
@Beberd thanks for reaching out. I updated the formatting of your description. We will take a look when we get a chance to see what might be going on.

**Comment by SwampDragons** [comment]
I wonder if there's a plugin conflict: Were you using the vsphere-iso plugin prior to it being merged with the Packer core? Do you still have that old plugin on your computer? If so, try deleting that old plugin and trying again.

**Comment by Beberd** [comment]
I've never used the old plugin from the vsphere-iso github. I only used the plugin merge since packer 1.5.2.

**Comment by Beberd** [comment]
I tried to use the external plugin but nothing changed.
`2020/04/14 19:22:34 [INFO] Packer version: 1.5.5 [go1.13.7 linux amd64]
2020/04/14 19:22:34 [DEBUG] Discovered plugin: vsphere-iso = /usr/local/bin/packer-builder-vsphere-iso
2020/04/14 19:22:34 using external builders [vsphere-iso]
2020/04/14 19:22:34 Checking 'PACKER_CONFIG' for a config file path
2020/04/14 19:22:34 'PACKER_CONFIG' not set; checking the default config file path
2020/04/14 19:22:34 Attempting to open config file: /home/user/.packerconfig
2020/04/14 19:22:34 [WARN] Config file doesn't exist: /home/user/.packerconfig
2020/04/14 19:22:34 Setting cache directory: /home/user/Downloads/packer_cache
2020/04/14 19:22:34 [ERR] Checkpoint error: EOF
2020/04/14 19:22:34 Build debug mode: false
2020/04/14 19:22:34 Force build: false
2020/04/14 19:22:34 On error: 
2020/04/14 19:22:34 Waiting on builds to complete...

==> Builds finished but no artifacts were created.
==> Builds finished but no artifacts were created.
2020/04/14 19:22:34 [INFO] (telemetry) Finalizing.
2020/04/14 19:22:35 waiting for all plugin processes to complete...
`

**Comment by SwampDragons** [comment]
Oh, I see the issue: you've got a "name" for your builder. "only" looks for build names, and falls back to type only if the name is available. To use a toy example: 

The following build will run the defined builder if I call `packer build --only=packer-111 test_name.json` but not if I call `packer build --only=null test_name.json`. However, If I remove `"name": "packer-111",` from the below config, `packer build --only=null test_name.json` will call this build. 
```
{
	"builders": [
		{
			"type": "null",
			"name": "packer-111",
			"communicator": "none"
		}
	],
	"provisioners": [
		{
			"type": "shell-local",
			"inline": "echo hi"
		}
	]
}
```

**Comment by SwampDragons** [comment]
Here's further documentation, from [template docs for the provisioners](https://www.packer.io/docs/templates/provisioners.html): 
>The values within only or except are build names, not builder types. If you recall, build names by default are just their builder type, but if you specify a custom name parameter, then you should use that as the value instead of the type. Values within except could also be a post-processor name.

Since this is the correct documented behavior I am going to close the issue, but be sure to reach out to the [community](https://www.packer.io/community.html) discussion forum or google group if have more issues getting a build up and running. Thanks!
