### ISSUE TITLE
Build function does not work with InSpec provisioner

### ISSUE THREAD

**Issue by jakemig** [hashicorp/packer#9075]
#### Overview of the Issue

Calls to the [`build`](https://www.packer.io/docs/templates/engine.html#build) function don't work as expected in the InSpec provisioner.

Using ``"extra_arguments": ["--password", "\"{{build `Password`}}\""]``, for example, runs InSpec with [``--password "Build_Password. To set this dynamically in the Packer template, you must use the `build` function"``](https://gist.github.com/jakemig/3064e8cd89603ec6687750e3fa53fed8#file-packer-log-L26).

While I experienced this bug while trying to provision a Windows instance, this looks to be in the provisioner itself.

### Packer version

1.5.5

### Simplified Packer Buildfile

https://gist.github.com/jakemig/3064e8cd89603ec6687750e3fa53fed8#file-packer-template-json

### Operating system and Environment details

MacOS 10.15.4

### Log Fragments and crash.log files

https://gist.github.com/jakemig/3064e8cd89603ec6687750e3fa53fed8#file-packer-log

**Comment by sylviamoss** [comment]
Hey there, thanks for reaching out! It looks like it's missing this feature implementation for the inspect provisioner. We will try to fix this for the next release 👍
