### ISSUE TITLE
vsphere-iso doesn't respect no_proxy when sending floppy_files to vsphere server

### ISSUE THREAD

**Issue by mdepot** [hashicorp/packer#9076]
#### Overview of the Issue

When using vsphere-iso on a system with proxy vars defined, and using the floppy_files directive, the upload of the floppy file image to the vsphere server does not respect the no_proxy setting.

#### Reproduction Steps

* Have a corporate proxy server that will respond with a 403 page when you try to access an invalid web page.
* Have http_proxy, https_proxy, and no_proxy defined appropriately for that proxy server.  For example on a windows machine:
set https_proxy=http://myproxy.mycompany.com:8080
set http_proxy=http://myproxy.mycompany.com:8080
set no_proxy=127.0.0.1,localhost,.local,.mycompany.com
* Specify packer config for vsphere-iso, including floppy_files to send to vsphere (example below)
* Results:
```
D:\Work\packer-test-1-vsphere>packer build -on-error=ask -only=vsphere-iso centos.json
vsphere-iso: output will be in this color.

==> vsphere-iso: Creating VM...
==> vsphere-iso: Customizing hardware...
==> vsphere-iso: Mounting ISO images...
==> vsphere-iso: Creating floppy disk...
    vsphere-iso: Copying files flatly from floppy_files
    vsphere-iso: Copying file: D:\Work\packer-test-1-vsphere/http/ks.cfg
    vsphere-iso: Done copying files from floppy_files
    vsphere-iso: Collecting paths from floppy_dirs
    vsphere-iso: Resulting paths from floppy_dirs : []
    vsphere-iso: Done copying paths from floppy_dirs
==> vsphere-iso: Uploading created floppy image
==> vsphere-iso: 403 URLBlockedInternalResource
==> vsphere-iso: Step "StepAddFloppy" failed
==> vsphere-iso: [c] Clean up and exit, [a] abort without cleanup, or [r] retry step (build may fail even if retry succeeds)?
```

The ```403 URLBlockedInternalResource``` is being returned by our corporate proxy server, however packer should not have contacted the proxy server because the target is ```myvcenter.mycompany.com``` and no_proxy contains ```.mycompany.com```.

### Packer version

1.5.5

### Simplified Packer Buildfile

```
{
  "min_packer_version": "1.5.5",
  "_comment": "Incomplete example",
  "variables": {
    "vsphere_user": "myuser1",
    "vsphere_pass": "mypass1",
    "ssh_user": "myuser2",
    "ssh_pass": "mypass2"
  },
  "builders": [
    {
      "type": "vsphere-iso",
      "vcenter_server": "myvcenter.mycompany.com",
      "username": "{{user `vsphere_user`}}",
      "password": "{{user `vsphere_pass`}}",
      "insecure_connection": "true",
      "datacenter": "mydatacenter",
      "cluster": "mycluster",
      "resource_pool": "mypool",
      "host": "myesxhost01.mycompany.com",
      "folder": "Parent/Folder",
      "datastore": "vsan01",
      "network": "mynetwork01",
      "vm_name": "packer-test-1",
      "guest_os_type": "centos7_64Guest",
      "cpus": "2",
      "ram": 2048,
      "disk_size": "50000",
      "disk_thin_provisioned": true,
      "network_card": "vmxnet3",
      "boot_command": [
        "<up><wait><tab> text ks=hd:/dev/fd0:ks.cfg<enter><wait>"
      ],
      "boot_wait": "8s",
      "floppy_files": [
        "{{template_dir}}/http/ks.cfg"
      ],
      "iso_checksum": "9bba3da2876cb9fcf6c28fb636bcbd01832fe6d84cd7445fa58e44e569b3b4fe",
      "iso_checksum_type": "sha256",
      "iso_paths": [
        "[mydatastore] ISOs/CentOS-7-x86_64-DVD-1908.iso"
      ],
      "shutdown_command": "echo '{{user `ssh_pass`}}' | sudo -S /sbin/halt -h -p",
      "ssh_port": 22,
      "ssh_username": "{{user `ssh_user`}}",
      "ssh_password": "{{user `ssh_pass`}}",
      "ssh_timeout": "15m"
    }
  ]
}
```

### Operating system and Environment details

Packer 1.5.5 running on a Windows 10 system with proxy vars defined, trying to reach vSphere vCenter 6.5.

### Log Fragments and crash.log files

```
2020/04/15 19:13:59 ui:     vsphere-iso: Copying files flatly from floppy_files
2020/04/15 19:13:59 ui:     vsphere-iso: Copying file: D:\Work\packer-test-1-vsphere/http/ks.cfg
2020/04/15 19:13:59 ui:     vsphere-iso: Done copying files from floppy_files
2020/04/15 19:13:59 ui:     vsphere-iso: Collecting paths from floppy_dirs
2020/04/15 19:13:59 ui:     vsphere-iso: Resulting paths from floppy_dirs : []
2020/04/15 19:13:59 ui:     vsphere-iso: Done copying paths from floppy_dirs
2020/04/15 19:13:59 ui: ==> vsphere-iso: Uploading created floppy image
2020/04/15 19:14:02 ui error: ==> vsphere-iso: 403 URLBlockedInternalResource
2020/04/15 19:14:02 ui: ==> vsphere-iso: Step "StepAddFloppy" failed
2020/04/15 19:14:02 ui: ask: ==> vsphere-iso: [c] Clean up and exit, [a] abort without cleanup, or [r] retry step (build may fail even if retry succeeds)?
( Clean up was chosen )
2020/04/15 19:17:01 packer.exe plugin: Deleting floppy disk: C:\Users\<redacted>\AppData\Local\Temp\1\packer228529739
2020/04/15 19:17:01 ui: ==> vsphere-iso: Destroying VM...
2020/04/15 19:17:02 [INFO] (telemetry) ending vsphere-iso
2020/04/15 19:17:02 ui error: Build 'vsphere-iso' errored: 403 URLBlockedInternalResource
2020/04/15 19:17:02 machine readable: error-count []string{"1"}
2020/04/15 19:17:02 ui error: 
==> Some builds didn't complete successfully and had errors:
2020/04/15 19:17:02 machine readable: vsphere-iso,error []string{"403 URLBlockedInternalResource"}
2020/04/15 19:17:02 ui error: --> vsphere-iso: 403 URLBlockedInternalResource
2020/04/15 19:17:02 ui: 
==> Builds finished but no artifacts were created.
2020/04/15 19:17:02 [INFO] (telemetry) Finalizing.
2020/04/15 19:17:04 waiting for all plugin processes to complete...
2020/04/15 19:17:04 C:\Users\<redacted>\Bin\packer.exe: plugin process exited
2020/04/15 19:17:04 C:\Users\<redacted>\Bin\packer.exe: plugin process exited
2020/04/15 19:17:04 C:\Users\<redacted>\Bin\packer.exe: plugin process exited
```

### Workaround

If we temporarily undefine the http_proxy, https_proxy, and no_proxy environment variables while calling packer, then this works.  However then no external web access is available since we are required to go through the corporate proxy to get outside.

**Comment by jhawk28** [comment]
My hunch is that the no_proxy is working. 

Based on your logs, it is creating the floppy (that is the copying log entry). The upload portion first looks up the host then sends a SOAP request. The underlying stuff uses the normal Go HTTP client. 

Try adding the IP address of your ESXi host(s) to the no_proxy.

**Comment by jhawk28** [comment]
you can also verify if govc has an issue uploading as this is the same API calls that the plugin is using: https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#datastoreupload

**Comment by mdepot** [comment]
I believe the creation of the floppy image file happens locally, before the attempt to upload it to vsphere.  So the copy stage in the log would be expected to work even if the connection could not be made.  Please let me know if that is an incorrect assumption.

The proxy vars need to be able to work with dns names as opposed to ip addresses because the vcenter may have a valid cert and some people will want to verify the cert matches by not using ```"insecure_connection": "true"```.  Because of that requirement, it seems invalid to need to add the ip address of the ESXi hosts to the no_proxy value.  Even if packer ends up contacting the ESXi host directly after it talks to vCenter, it seems that connection should also be by hostname and matching cert so that the connection is secure.  Based on that I'm not sure how testing with an ip address in no_proxy helps given the need for the cert to match the dns names.

I will try testing with govc though and post an update soon.

**Comment by jhawk28** [comment]
You are correct about the copy stage. It happens locally before the upload attempt is made.

I agree with your assessment of the no_proxy. The code "should" be using your dns name for the host because you specified it in the config. My thought was that the plugin was requesting the host information from vcenter (which it can) and then using that info to connect. Knowing whether its a no_proxy issue or if its an ip vs dns issue will help with finding the actual cause.

**Comment by mdepot** [comment]
I've tested the following command:
```govc datastore.upload ./floppy.img somevm/floppytest.img```
with the proxy vars undefined, and also with them defined as above.

In both cases the file was successfully uploaded.

Next I will try adding the ip of the host to no_proxy as you suggested and we can at least see what happens then.

**Comment by jhawk28** [comment]
if it uploads fine when you add the ip of the host, then I think this is the issue:
https://github.com/hashicorp/packer/blob/master/builder/vsphere/driver/datastore.go#L93

govc doesn't ever appear to add the host to the context. It just looks up the datastore and then uses that to upload the file.

**Comment by jhawk28** [comment]
this is the reason the host is set: https://github.com/hashicorp/packer/commit/e1cdd04f4f19a82b89bc6fe881261dc2c3197921

**Comment by jhawk28** [comment]
and this changed how it was set: https://github.com/hashicorp/packer/commit/3c005a9291179fbb9b4c39434fa884325675624d

**Comment by mdepot** [comment]
I tested again with the proxy vars defined and the ESXi host's ip address added to no_proxy, and it was successful this way.
```
2020/04/21 17:17:28 ui:     vsphere-iso: Done copying files from floppy_files
2020/04/21 17:17:28 ui:     vsphere-iso: Collecting paths from floppy_dirs
2020/04/21 17:17:28 ui:     vsphere-iso: Resulting paths from floppy_dirs : []
2020/04/21 17:17:28 ui:     vsphere-iso: Done copying paths from floppy_dirs
2020/04/21 17:17:28 ui: ==> vsphere-iso: Uploading created floppy image
2020/04/21 17:17:31 ui: ==> vsphere-iso: Adding generated Floppy...
2020/04/21 17:17:31 ui: ==> vsphere-iso: Set boot order temporary...
2020/04/21 17:17:31 ui: ==> vsphere-iso: Power on VM...
```

**Comment by jhawk28** [comment]
If you look in vcenter, does it show the esxi dns name or ip address? This is probably why it is returning the IP address instead of the host name. I'm not certain the plugin needs to set the host, but I don't have a DRS environment to test it. I also don't know if the random host is a thing either.

**Comment by mdepot** [comment]
The ESXi host was added to vCenter via FQDN, and also shows up in the interface that way.

**Comment by mdepot** [comment]
Since the [docs](https://www.packer.io/docs/builders/vsphere-iso.html#working-with-clusters) say I don't need to pass the host when using a DRS cluster, I tried with and without passing the host entry in the packer config, but it acts the same either way.

**Comment by jhawk28** [comment]
I left the pull request with a WIP since we probably need to test the two cases that put the changes there in the first place.
