### ISSUE TITLE
vsphere-iso does not respect <waitXX> in boot_command

### ISSUE THREAD

**Issue by ez12a** [hashicorp/packer#9084]
#### Overview of the Issue

I have the need to have a 45 minute wait in the boot command. Using `<wait45m>` per the documentation is not respected and I see the text ("i.e. `<enter><wait>`) of the following key presses being inputted into the terminal window (macos 10.15 install) as if the key press commands are being treated as text to input. 

#### Reproduction Steps

Build 10.15 template based on macos 10.13 example in git. Edit boot command: to test:
`                "<enter><wait10>",`
               ` "<leftCtrlOn><f2><leftCtrlOff>u<enter>t<enter><wait10>",`
               ` "/Volumes/setup/setup.sh<enter><wait>",`
                `"<enter><wait45m>test<wait5>",`

You will see `test<wait5>` and following keystrokes being typed into the installation prompt.

### Packer version

From Packer 1.55

### Operating system and Environment details

ESXi 6.7 U3

### Log Fragments and crash.log files
Note, no 45 minute wait captured in logs:
`==> OSX Mojave 10.15 - 2020-04-17T19:27:07Z: Typing boot command...`
`2020/04/17 12:31:14 packer.exe plugin: Special code '<enter>' found, replacing with: CodeReturnEnter`
`2020/04/17 12:31:14 packer.exe plugin: Waiting 10 seconds`
`2020/04/17 12:31:24 packer.exe plugin: Special code '<f2>' found, replacing with: CodeF2`
`2020/04/17 12:31:25 packer.exe plugin: Special code '<enter>' found, replacing with: CodeReturnEnter`
`2020/04/17 12:31:25 packer.exe plugin: Special code '<enter>' found, replacing with: CodeReturnEnter`
`2020/04/17 12:31:25 packer.exe plugin: Waiting 10 seconds`
`2020/04/17 12:31:38 packer.exe plugin: Special code '<enter>' found, replacing with: CodeReturnEnter`
`2020/04/17 12:31:38 packer.exe plugin: Waiting 1 second`
`2020/04/17 12:31:39 packer.exe plugin: Special code '<enter>' found, replacing with: CodeReturnEnter`
`2020/04/17 12:31:40 packer.exe plugin: Special code '<tab>' found, replacing with: CodeTab`
`2020/04/17 12:31:40 packer.exe plugin: Waiting 1 second`
`2020/04/17 12:31:41 packer.exe plugin: Special code '<tab>' found, replacing with: CodeTab`
`2020/04/17 12:31:41 packer.exe plugin: Waiting 1 second`
`2020/04/17 12:31:42 packer.exe plugin: Special code '<tab>' found, replacing with: CodeTab`
`2020/04/17 12:31:42 packer.exe plugin: Waiting 1 second`
`2020/04/17 12:31:43 packer.exe plugin: Special code '<tab>' found, replacing with: CodeTab`
`2020/04/17 12:31:43 packer.exe plugin: Waiting 1 second`
`2020/04/17 12:31:44 packer.exe plugin: Special code '<up>' found, replacing with: CodeUpArrow`

**Comment by SwampDragons** [comment]
Thanks for opening. Now that we've merged the builder, we need to swap out the custom boot command code in the VSphere builder with the common boot command code used across the rest of  the builders in the core.

**Comment by sylviamoss** [comment]
Hey there! I did some changes to the vSphere boot_command and I want to make sure this is addressed. Could you try the solution, please? Here the binaries: https://circleci.com/gh/hashicorp/packer/59490#artifacts/containers/0

Let me know if it works for you.
