### ISSUE TITLE
Please update vendor/github.com/oracle/oci-go-sk to current version

### ISSUE THREAD

**Issue by rramge** [hashicorp/packer#9085]
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

While investigating an issue reported in the Packer Community Forum, I learned that Packer 1.5.5 has been compiled against an extremely outdated and obsolete version of the Oracle Cloud Infrastructure Go SDK (Community thread: https://discuss.hashicorp.com/t/oci-government-regions/6526/8).
This has the effect, that only about 4 of the currently 21 Oracle Cloud regions are supported by Packer correctly, which breaks Packer for use with all Government-related Oracle Cloud regions in the US and the UK.
Please update packer/vendor/github.com/oracle/oci-go-sdk with the current version of the SDK (https://github.com/oracle/oci-go-sdk.git).

#### Reproduction Steps

1. clone the packer repository
2. less vendor/github.com/oracle/oci-go-sdk/common/common.go displays only 4 regions:
---
const (
        //RegionSEA region SEA
        RegionSEA Region = "sea"
        //RegionPHX region PHX
        RegionPHX Region = "us-phoenix-1"
        //RegionIAD region IAD
        RegionIAD Region = "us-ashburn-1"
        //RegionFRA region FRA
        RegionFRA Region = "eu-frankfurt-1"
        //RegionLHR region LHR
        RegionLHR Region = "uk-london-1"
)
---

There should be many more, which differ from each other by using different TLDs for the REST APIs, which in turn makes Packer unusable for the affected cloud regions.

### Packer version

Packer v1.5.5

Thank you very much,

Ralf

**Comment by SwampDragons** [comment]
Thanks for reaching out. We'll look into updating this SDK for the next release.

**Comment by twmcelroy** [comment]
Thank you for adding this to the next milestone.

**Comment by azr** [comment]
Hello there, I opened #9104, I don't have an OCI access here, can you please tell me if that makes it better for you ? Binaries can be found here: [artifacts](https://circleci.com/gh/hashicorp/packer/47341#artifacts/containers/0). Thanks !

**Comment by twmcelroy** [comment]
This is my first time testing something like this. I downloaded the packer_windows_amd64 package but it doesn't seem to come out as an executable. Do I need to compile it locally first?

**Comment by azr** [comment]
@twmcelroy I think this should work if you suffix the filename of `packer_windows_amd64`  to `.exe, so: `packer_windows_amd64.exe`, we will soon fix the automated builder to do this for us.

**Comment by twmcelroy** [comment]
I have changed it to exe however it hangs. Running it directly doesn't do anything. I am doing this on windows with gitbash
$ /c/Users/travis.mcelroy/.oci/packer_windows_amd64.exe build -var-file=variables.json clientlinuxol7.json

also changing it to packer.exe and running it directly in the folder hangs as well
![image](https://user-images.githubusercontent.com/20779080/79997019-b83d6b00-847e-11ea-9459-d13854f1638b.png)

**Comment by rramge** [comment]
Good news: I tried the Linux binary and it works.

@twmcelroy I don't have an account in one of the US government regions, but I got a connect and it kicked me out during authorization, so the name resolution worked fine.

I can't say anything concerning the Windows binary, but I am very confident that your issue will be solved with the next official packer release, in case you can't get it to run properly now.

Cheers,

Ralf

**Comment by twmcelroy** [comment]
That is great news. Let me see if I can get it to work on a linux instance. Just have to bring over the JSON and set up oci cli.

**Comment by twmcelroy** [comment]
I can verify that it works on us-luke-1 and us-langley-1. Thank you for this update!

Let me know if I have done something wrong with Windows are you want me to test it again. It could just be a silly error on my part.

**Comment by nywilken** [comment]
Hey Folks, thanks for testing. I merged the change so the issue was closed. But you can continue to comment on the issue if you wish to discuss the Windows bins further. Also if there is anything we can do to help with the bins please let us know.
