### ISSUE TITLE
AWS secrets manager support on Packer template functions

### ISSUE THREAD

**Issue by overdrive3000** [hashicorp/packer#9086]
#### Feature Description
Currently there is only options to retrieve secrets from `vault` although Hashicorp Vault is an excellent tool it would be nice to use alternative secret stores to retrieve secrets straight from Packer, like for example from AWS Secrets Manager.

#### Use Case(s)
In our company our infrastructure uses several managed services from AWS as this allows to offload the burden tasks of administrate too many services while we need to deal with daily basis tasks. On of these manage services is AWS Secrets Manager, even though we can workaround the way to inject secrets into our configurations using Packer, it would be nice if we could use something similar as the option provided for vault

```
{{ vault /path/to/secret }}
```

I'd like to work in this feature but I am not sure what is the policy about adding features from third party vendors into the Packer core source code, I've been reading the documentation and I cannot find a way to implement something like this via Packer Custom Plugins.

Looking forward to your comments about this feature requests.

Thanks.

**Comment by SwampDragons** [comment]
Hi, thanks for this suggestion. I agree it's a good thing to support. I'm not sure when the Packer team will get a chance to implement it, but PRs are always welcome.
