### ISSUE TITLE
Ansible provisioner gets stuck

### ISSUE THREAD

**Issue by anentropic** [hashicorp/packer#909]
I get this far and no further:

```
==> docker: Provisioning with Ansible...
    docker: Creating Ansible staging directory...
    docker: Creating directory: /tmp/packer-provisioner-ansible-local
```

The docs say _"This directory doesn't need to exist but must have proper permissions so that the SSH user that Packer uses is able to create directories and write into this folder. If the permissions are not correct, use a shell provisioner prior to this to configure it properly"_

If I look up the id of the container and `docker attach` to it (while the provisioner is still hung)... firstly I have to `ctrl-c` before it gives me a command prompt in the container (possible symptom?).

But then if I `ls /tmp/` I can see that the ansible local tmp dir has been created, although it's still empty at this stage. This suggests to me my permissions are ok?

I'm running packer build with the debug flag but I don't see anything more than the above.

**Comment by colinfkennedy** [comment]
I am seeing the same problem, but with Chef instead of ansible. I'm running a Linux VM with both docker and packer installed locally. Here's the output of packer build:

    2015/04/03 14:11:09 [INFO] Packer version: 0.7.5      9cd66feeacbd9cb318b72eb5ed59428c5b8c37ac+CHANGES
    2015/04/03 14:11:09 Packer Target OS/Arch: linux amd64
    2015/04/03 14:11:09 Built with Go Version: go1.3.3
    2015/04/03 14:11:09 [DEBUG] Discoverd plugin: amazon-chroot = /usr/local/bin/packer-builder-amazon-chroot
    2015/04/03 14:11:09 [DEBUG] Discoverd plugin: amazon-ebs = /usr/local/bin/packer-builder-amazon-ebs
    2015/04/03 14:11:09 [DEBUG] Discoverd plugin: amazon-instance = /usr/local/bin/packer-builder-amazon-instance
    2015/04/03 14:11:09 [DEBUG] Discoverd plugin: digitalocean = /usr/local/bin/packer-builder-digitalocean
    2015/04/03 14:11:09 [DEBUG] Discoverd plugin: docker = /usr/local/bin/packer-builder-docker
    2015/04/03 14:11:09 [DEBUG] Discoverd plugin: googlecompute = /usr/local/bin/packer-builder-googlecompute
    2015/04/03 14:11:09 [DEBUG] Discoverd plugin: null = /usr/local/bin/packer-builder-null
    2015/04/03 14:11:09 [DEBUG] Discoverd plugin: openstack = /usr/local/bin/packer-builder-openstack
    2015/04/03 14:11:09 [DEBUG] Discoverd plugin: parallels-iso = /usr/local/bin/packer-builder-parallels-iso
    2015/04/03 14:11:09 [DEBUG] Discoverd plugin: parallels-pvm = /usr/local/bin/packer-builder-parallels-pvm
    2015/04/03 14:11:09 [DEBUG] Discoverd plugin: qemu = /usr/local/bin/packer-builder-qemu
    2015/04/03 14:11:09 [DEBUG] Discoverd plugin: virtualbox-iso = /usr/local/bin/packer-builder-virtualbox-iso
    2015/04/03 14:11:09 [DEBUG] Discoverd plugin: virtualbox-ovf = /usr/local/bin/packer-builder-virtualbox-ovf
    2015/04/03 14:11:09 [DEBUG] Discoverd plugin: vmware-iso = /usr/local/bin/packer-builder-vmware-iso
    2015/04/03 14:11:09 [DEBUG] Discoverd plugin: vmware-vmx = /usr/local/bin/packer-builder-vmware-vmx
    2015/04/03 14:11:09 [DEBUG] Discoverd plugin: atlas = /usr/local/bin/packer-post-processor-atlas
    2015/04/03 14:11:09 [DEBUG] Discoverd plugin: compress = /usr/local/bin/packer-post-processor-compress
    2015/04/03 14:11:09 [DEBUG] Discoverd plugin: docker-import = /usr/local/bin/packer-post-processor-docker-import
    2015/04/03 14:11:09 [DEBUG] Discoverd plugin: docker-push = /usr/local/bin/packer-post-processor-docker-push
    2015/04/03 14:11:09 [DEBUG] Discoverd plugin: docker-save = /usr/local/bin/packer-post-processor-docker-save
    2015/04/03 14:11:09 [DEBUG] Discoverd plugin: docker-tag = /usr/local/bin/packer-post-processor-docker-tag
    2015/04/03 14:11:09 [DEBUG] Discoverd plugin: vagrant = /usr/local/bin/packer-post-processor-vagrant
    2015/04/03 14:11:09 [DEBUG] Discoverd plugin: vagrant-cloud = /usr/local/bin/packer-post-processor-vagrant-cloud
    2015/04/03 14:11:09 [DEBUG] Discoverd plugin: vsphere = /usr/local/bin/packer-post-processor-vsphere
    2015/04/03 14:11:09 [DEBUG] Discoverd plugin: ansible-local = /usr/local/bin/packer-provisioner-ansible-local
    2015/04/03 14:11:09 [DEBUG] Discoverd plugin: chef-client = /usr/local/bin/packer-provisioner-chef-client
    2015/04/03 14:11:09 [DEBUG] Discoverd plugin: chef-solo = /usr/local/bin/packer-provisioner-chef-solo
    2015/04/03 14:11:09 [DEBUG] Discoverd plugin: file = /usr/local/bin/packer-provisioner-file
    2015/04/03 14:11:09 [DEBUG] Discoverd plugin: puppet-masterless = /usr/local/bin/packer-provisioner-puppet-masterless
    2015/04/03 14:11:09 [DEBUG] Discoverd plugin: puppet-server = /usr/local/bin/packer-provisioner-puppet-server
    2015/04/03 14:11:09 [DEBUG] Discoverd plugin: salt-masterless = /usr/local/bin/packer-provisioner-salt-masterless
    2015/04/03 14:11:09 [DEBUG] Discoverd plugin: shell = /usr/local/bin/packer-provisioner-shell
    2015/04/03 14:11:09 Detected home directory from env var: /home/vagrant
    2015/04/03 14:11:09 Detected home directory from env var: /home/vagrant
    2015/04/03 14:11:09 Attempting to open config file: /home/vagrant/.packerconfig
    2015/04/03 14:11:09 File doesn't exist, but doesn't need to. Ignoring.
    2015/04/03 14:11:09 Packer config: &{DisableCheckpoint:false DisableCheckpointSignature:false PluginMinPort:10000 PluginMaxPort:25000 Builders:map[digitalocean:/usr/local/bin/packer-builder-digitalocean vmware-vmx:/usr/local/bin/packer-builder-vmware-vmx googlecompute:/usr/local/bin/packer-builder-googlecompute openstack:/usr/local/bin/packer-builder-openstack parallels-iso:/usr/local/bin/packer-builder-parallels-iso parallels-pvm:/usr/local/bin/packer-builder-parallels-pvm qemu:/usr/local/bin/packer-builder-qemu amazon-chroot:/usr/local/bin/packer-builder-amazon-chroot amazon-instance:/usr/local/bin/packer-builder-amazon-instance docker:/usr/local/bin/packer-builder-docker virtualbox-iso:/usr/local/bin/packer-builder-virtualbox-iso virtualbox-ovf:/usr/local/bin/packer-builder-virtualbox-ovf vmware-iso:/usr/local/bin/packer-builder-vmware-iso amazon-ebs:/usr/local/bin/packer-builder-amazon-ebs null:/usr/local/bin/packer-builder-null] PostProcessors:map[compress:/usr/local/bin/packer-post-processor-compress docker-import:/usr/local/bin/packer-post-processor-docker-import docker-save:/usr/local/bin/packer-post-processor-docker-save atlas:/usr/local/bin/packer-post-processor-atlas docker-push:/usr/local/bin/packer-post-processor-docker-push docker-tag:/usr/local/bin/packer-post-processor-docker-tag vagrant:/usr/local/bin/packer-post-processor-vagrant vagrant-cloud:/usr/local/bin/packer-post-processor-vagrant-cloud vsphere:/usr/local/bin/packer-post-processor-vsphere] Provisioners:map[puppet-masterless:/usr/local/bin/packer-provisioner-puppet-masterless puppet-server:/usr/local/bin/packer-provisioner-puppet-server salt-masterless:/usr/local/bin/packer-provisioner-salt-masterless shell:/usr/local/bin/packer-provisioner-shell ansible-local:/usr/local/bin/packer-provisioner-ansible-local chef-client:/usr/local/bin/packer-provisioner-chef-client chef-solo:/usr/local/bin/packer-provisioner-chef-solo file:/usr/local/bin/packer-provisioner-file]}
    2015/04/03 14:11:09 Setting cache directory: /home/vagrant/cicd/packer/asms-mirror/packer_cache
    2015/04/03 14:11:09 Detected home directory from env var: /home/vagrant
    2015/04/03 14:11:09 Reading template: asms-mirror-container.json
    2015/04/03 14:11:09 Creating build: docker
    2015/04/03 14:11:09 Loading builder: docker
    2015/04/03 14:11:09 Creating plugin client for path: /usr/local/bin/packer-builder-docker
    2015/04/03 14:11:09 Starting plugin: /usr/local/bin/packer-builder-docker []string{"/usr/local/bin/packer-builder-docker"}
    2015/04/03 14:11:09 Waiting for RPC address for: /usr/local/bin/packer-builder-docker
    2015/04/03 14:11:10 packer-builder-docker: 2015/04/03 14:11:10 Plugin minimum port: 10000
    2015/04/03 14:11:10 packer-builder-docker: 2015/04/03 14:11:10 Plugin maximum port: 25000
    2015/04/03 14:11:10 packer-builder-docker: 2015/04/03 14:11:10 Plugin address: unix /tmp/packer-plugin207046785
    2015/04/03 14:11:10 packer-builder-docker: 2015/04/03 14:11:10 Waiting for connection...
    2015/04/03 14:11:10 packer-builder-docker: 2015/04/03 14:11:10 Serving a plugin connection...
    2015/04/03 14:11:10 Loading post-processor: docker-import
    2015/04/03 14:11:10 Creating plugin client for path: /usr/local/bin/packer-post-processor-docker-import
    2015/04/03 14:11:10 Starting plugin: /usr/local/bin/packer-post-processor-docker-import []string{"/usr/local/bin/packer-post-processor-docker-import"}
    2015/04/03 14:11:10 Waiting for RPC address for: /usr/local/bin/packer-post-processor-docker-import
    2015/04/03 14:11:11 packer-post-processor-docker-import: 2015/04/03 14:11:11 Plugin minimum port: 10000
    2015/04/03 14:11:11 packer-post-processor-docker-import: 2015/04/03 14:11:11 Plugin maximum port: 25000
    2015/04/03 14:11:11 packer-post-processor-docker-import: 2015/04/03 14:11:11 Plugin address: unix /tmp/packer-plugin214259505
    2015/04/03 14:11:11 packer-post-processor-docker-import: 2015/04/03 14:11:11 Waiting for connection...
    2015/04/03 14:11:11 packer-post-processor-docker-import: 2015/04/03 14:11:11 Serving a plugin connection...
    2015/04/03 14:11:11 Loading post-processor: docker-push
    2015/04/03 14:11:11 Creating plugin client for path: /usr/local/bin/packer-post-processor-docker-push
    2015/04/03 14:11:11 Starting plugin: /usr/local/bin/packer-post-processor-docker-push []string{"/usr/local/bin/packer-post-processor-docker-push"}
    2015/04/03 14:11:11 Waiting for RPC address for: /usr/local/bin/packer-post-processor-docker-push
    2015/04/03 14:11:11 packer-post-processor-docker-push: 2015/04/03 14:11:11 Plugin minimum port: 10000
    2015/04/03 14:11:11 packer-post-processor-docker-push: 2015/04/03 14:11:11 Plugin maximum port: 25000
    2015/04/03 14:11:11 packer-post-processor-docker-push: 2015/04/03 14:11:11 Plugin address: unix /tmp/packer-plugin638070091
    2015/04/03 14:11:11 packer-post-processor-docker-push: 2015/04/03 14:11:11 Waiting for connection...
    2015/04/03 14:11:11 packer-post-processor-docker-push: 2015/04/03 14:11:11 Serving a plugin connection...
    2015/04/03 14:11:11 Loading provisioner: chef-client
    2015/04/03 14:11:11 Creating plugin client for path: /usr/local/bin/packer-provisioner-chef-client
    2015/04/03 14:11:11 Starting plugin: /usr/local/bin/packer-provisioner-chef-client []string{"/usr/local/bin/packer-provisioner-chef-client"}
    2015/04/03 14:11:11 Waiting for RPC address for: /usr/local/bin/packer-provisioner-chef-client
    2015/04/03 14:11:11 packer-provisioner-chef-client: 2015/04/03 14:11:11 Plugin minimum port: 10000
    2015/04/03 14:11:11 packer-provisioner-chef-client: 2015/04/03 14:11:11 Plugin maximum port: 25000
    2015/04/03 14:11:11 packer-provisioner-chef-client: 2015/04/03 14:11:11 Plugin address: unix /tmp/packer-plugin851735444
    2015/04/03 14:11:11 packer-provisioner-chef-client: 2015/04/03 14:11:11 Waiting for connection...
    2015/04/03 14:11:11 packer-provisioner-chef-client: 2015/04/03 14:11:11 Serving a plugin connection...
    2015/04/03 14:11:11 ui: docker output will be in this color.
    2015/04/03 14:11:11 ui: 
    2015/04/03 14:11:11 Build debug mode: false
    2015/04/03 14:11:11 Force build: false
    2015/04/03 14:11:11 Preparing build: docker
    docker output will be in this color.

    2015/04/03 14:11:11 Waiting on builds to complete...
    2015/04/03 14:11:11 Starting build run: docker
    2015/04/03 14:11:11 Running builder: docker
    2015/04/03 14:11:11 ui: ==> docker: Creating a temporary directory for sharing data...
    2015/04/03 14:11:11 packer-builder-docker: 2015/04/03 14:11:11 Pull disabled, won't docker pull
    ==> docker: Creating a temporary directory for sharing data...
    2015/04/03 14:11:11 ui: ==> docker: Starting docker container...
    ==> docker: Starting docker container...
    2015/04/03 14:11:11 ui:     docker: Run command: docker run -v /tmp/packer-docker092908012:/packer-files -d -i -t colinfkennedy/aol_centos_chef /bin/bash
        docker: Run command: docker run -v /tmp/packer-docker092908012:/packer-files -d -i -t colinfkennedy/aol_centos_chef /bin/bash
    2015/04/03 14:11:11 packer-builder-docker: 2015/04/03 14:11:11 Starting container with args: [run -v /tmp/packer-docker092908012:/packer-files -d -i -t colinfkennedy/aol_centos_chef /bin/bash]
    2015/04/03 14:11:11 packer-builder-docker: 2015/04/03 14:11:11 Waiting for container to finish starting
    2015/04/03 14:11:13 ui:     docker: Container ID: 73e4ebd3d3ecd34548f79893aca1150b779f59f27ec14281c54b2e9eea099ac8
        docker: Container ID: 73e4ebd3d3ecd34548f79893aca1150b779f59f27ec14281c54b2e9eea099ac8
    2015/04/03 14:11:13 packer-builder-docker: 2015/04/03 14:11:13 Running the provision hook
    2015/04/03 14:11:13 ui:     docker: Creating directory: /tmp/packer-chef-client
        docker: Creating directory: /tmp/packer-chef-client
    2015/04/03 14:11:13 packer-builder-docker: 2015/04/03 14:11:13 Executing in container 73e4ebd3d3ecd34548f79893aca1150b779f59f27ec14281c54b2e9eea099ac8: "(mkdir -p '/tmp/packer-chef-client') >/packer-files/cmd043685979 2>&1; echo $? >/packer-files/cmd043685979-exit"
    2015/04/03 14:11:15 packer-builder-docker: 2015/04/03 14:11:15 [INFO] RPC endpoint: Communicator ended with: 1
    2015/04/03 14:11:15 [INFO] 0 bytes written for 'stderr'
    2015/04/03 14:11:15 [INFO] 0 bytes written for 'stdout'
    2015/04/03 14:11:15 [INFO] RPC client: Communicator ended with: 1
    2015/04/03 14:11:15 [INFO] RPC endpoint: Communicator ended with: 1
    2015/04/03 14:11:15 packer-provisioner-chef-client: 2015/04/03 14:11:15 [INFO] 0 bytes written for 'stderr'
    2015/04/03 14:11:15 packer-provisioner-chef-client: 2015/04/03 14:11:15 [INFO] 0 bytes written for 'stdout'
    2015/04/03 14:11:15 packer-provisioner-chef-client: 2015/04/03 14:11:15 [INFO] RPC client: Communicator ended with: 1
    2015/04/03 14:11:15 ui: ==> docker: Killing the container: 73e4ebd3d3ecd34548f79893aca1150b779f59f27ec14281c54b2e9eea099ac8
    ==> docker: Killing the container: 73e4ebd3d3ecd34548f79893aca1150b779f59f27ec14281c54b2e9eea099ac8
    2015/04/03 14:11:17 ui error: Build 'docker' errored: Error creating staging directory: Non-zero exit status.
    2015/04/03 14:11:17 Builds completed. Waiting on interrupt barrier...
    2015/04/03 14:11:17 machine readable: error-count []string{"1"}
    2015/04/03 14:11:17 ui error: 
    ==> Some builds didn't complete successfully and had errors:
    2015/04/03 14:11:17 machine readable: docker,error []string{"Error creating staging directory: Non-zero exit status."}
    2015/04/03 14:11:17 ui error: --> docker: Error creating staging directory: Non-zero exit status.
    2015/04/03 14:11:17 ui: 
    ==> Builds finished but no artifacts were created.
    2015/04/03 14:11:17 waiting for all plugin processes to complete...
    Build 'docker' errored: Error creating staging directory: Non-zero exit status.

    ==> Some builds didn't complete successfully and had errors:
    --> docker: Error creating staging directory: Non-zero exit status.

    ==> Builds finished but no artifacts were created.
    2015/04/03 14:11:17 /usr/local/bin/packer-post-processor-docker-import: plugin process exited
    2015/04/03 14:11:17 /usr/local/bin/packer-post-processor-docker-push: plugin process exited
    2015/04/03 14:11:17 /usr/local/bin/packer-provisioner-chef-client: plugin process exited
    2015/04/03 14:11:17 /usr/local/bin/packer-builder-docker: plugin process exited

**Comment by rvangundy** [comment]
I'm seeing this issue again with only the virtualbox builder (no Docker involved). This hangs for a while:

```
==> virtualbox-iso: Provisioning with Ansible...
    virtualbox-iso: Uploading Playbook directory to Ansible staging directory...
    virtualbox-iso: Creating directory: /tmp/packer-provisioner-ansible-local
```

I have seen it pick up eventually (after 10+ minutes or longer). I'm running with PACKER_LOG=1 and see no relevant log info.

**Comment by mkhattab** [comment]
@rvangundy thanks, I think that was my problem as well. Only I didn't notice this at work because of our fast Internet connection.

**Comment by d3netxer** [comment]
I tried to run the simple packer script that @rvangundy posted, and I get this error:

Build 'docker' errored: Retryable error: Error uploading script: Upload failed with non-zero exit status: 1

==> Some builds didn't complete successfully and had errors:
--> docker: Retryable error: Error uploading script: Upload failed with non-zero exit status: 1

any idea why? Is packer having a hard time communicating with Docker?

**Comment by d3netxer** [comment]
I figured it out (installed docker 1.3.2) and I commented on https://github.com/mitchellh/packer/issues/1752

**Comment by ecorson** [comment]
I am seeing this issue running in a phusionbase jenkins iamge. I am using docker-in-docker. Ubuntu 14.04.  Any fixes?
