### ISSUE TITLE
sed not work in packer

### ISSUE THREAD

**Issue by iwasnobody** [hashicorp/packer#9091]
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue
The sed command can run successfully in machine but got error in packer
sudo sed -i 's/^PATH=.*/PATH=$PATH:$HOME\/bin:\/usr\/local\/bin/' /root/.bash_profile

error message:
·[1;32m==> amazon-ebs: Provisioning with shell script: /tmp/packer-shell127020321·[0m
·[1;31m==> amazon-ebs: sed: -e expression #1, char 29: unknown option to `s'·[0m
·[1;32m==> amazon-ebs: Provisioning step had errors: Running the cleanup provisioner, if present...·[0m
·[1;32m==> amazon-ebs: Terminating the source AWS instance...·[0m
A paragraph or two about the issue you're experiencing.

#### Reproduction Steps

Steps to reproduce this issue

### Packer version
1.5.5
From `packer version`

### Simplified Packer Buildfile
{
    "variables": {
        "aws_region": "ap-northeast-1",
        "aws_ami_name": "Packer_AmazonLinux2_{{isotime \"02Jan2006\"}}"
    },

    "builders": [{
        "type": "amazon-ebs",
        "ami_name": "{{user `aws_ami_name`}}",
        "ami_description": "Customized Amazon Linux2 Built by Packer",
        "ami_virtualization_type" : "hvm",
        "region": "{{user `aws_region`}}",
        "instance_type": "m5.large",
        "ssh_username": "ec2-user",
        "associate_public_ip_address": "false",
        "ssh_interface": "private_ip",
        "source_ami_filter": {
            "filters": {
                "virtualization-type": "hvm",
                "name": "amzn2-ami-hvm-*-x86_64-gp2",
                "root-device-type": "ebs"
            },
            "owners": ["amazon"],
            "most_recent": true
        }
    }],

    "provisioners": [
        {
            "type": "shell",
            "inline": [
                "sudo sed -i 's/^PATH=.*/PATH=$PATH:$HOME\/bin:\/usr\/local\/bin/' /root/.bash_profile"
            ]
        }
    ]
}

If the file is longer than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/) of the log or use the [Github detailed
format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d)
instead of posting it directly in the issue.

### Operating system and Environment details

OS, Architecture, and any other information you can provide about the
environment.

### Log Fragments and crash.log files

Include appropriate log fragments. If the log is longer than a few dozen lines,
please include the URL to the [gist](https://gist.github.com/) of the log or
use the [Github detailed format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d) instead of posting it directly in the issue.

Set the env var `PACKER_LOG=1` for maximum log detail.

**Comment by nywilken** [comment]
Hi @iwasnobody thanks for reaching out. Packer executes the command on the instances being provisioned so as long as it is supported on the guest system it should work as expected. 

With that being said, the issue here is that the forward slashes in your sed command are not properly escaped. If you update your provisioner like the following it should work with out issue. 

```
    {
        "type": "shell",
        "inline": [
            "sudo sed -i 's/^PATH=.*/PATH=$PATH:$HOME\\/bin:\\/usr\\/local\\/bin/' /root/.bash_profile"
        ]
    }
```

Here are my results before and after the change

```bash
⇶  packer build build.json                                                                                                                         
null: output will be in this color.                                                                                                                
                                                                                                                                                   
==> null: Running local shell script: /tmp/packer-shell402279946                                                                                   
==> null: sed: -e expression #1, char 29: unknown option to `s'                                                                                    
==> null: Provisioning step had errors: Running the cleanup provisioner, if present...                                                             
Build 'null' errored: Script exited with non-zero exit status: 1.Allowed exit codes are: [0]                                                       
                                                                                                                                                   
==> Some builds didn't complete successfully and had errors:                                                                                       
--> null: Script exited with non-zero exit status: 1.Allowed exit codes are: [0]                                                                   
                                                                                                                                                   
==> Builds finished but no artifacts were created. 
```

After fixing the escaping issue
```bash
⇶  packer build build.json 
null: output will be in this color.                

==> null: Running local shell script: /tmp/packer-shell447775706
Build 'null' finished.

==> Builds finished. The artifacts of successful builds are:
--> null: Did not export anything. This is the null builder
                          
⇶  cat bash_profile 
PATH=$PATH:$HOME/bin:/usr/local/bin
```

I'm going to close this issue as it was a problem in the configuration and not in Packer. If you find yourself running into another issue that you think might be bug open an issue and we will try to help out. Cheers!
