### ISSUE TITLE
Support `only` tag in provisioners for hcl2

### ISSUE THREAD

**Issue by zenitraM** [hashicorp/packer#9094]
I'm trying to port to HCL2 a bunch of what once were separate Packer builds into an unified one.

However there are some divergencies in terms of some provisioning tasks that need to be applied in specific builds. The JSON syntax provides this though the [only](https://www.packer.io/docs/provisioners/shell.html#only) keyword, which seems to not be allowed from HCL2:

```
Error: Unsupported argument

  on packer.pkr.hcl line 41, in build:
  41:     only = ["vagrant"]

An argument named "only" is not expected here.
```

Are there any plans to allow conditionally gating provisioners to only run for certain builds/sources on HCL2? (I think this also might apply to postprocessors)

**Comment by SwampDragons** [comment]
Thanks for reaching out. We do plan to support this, but HCL2 support is still in progress.  https://github.com/hashicorp/packer/pull/8947 is partially related (thought that's for conditional logic on builds, not provisioners), so keep an eye on that for updates from @azr about only/except implementation.

**Comment by azr** [comment]
Yes what Megan said! 🙂  Also to add a little on how I would do this:

The provisioner blocks need to get `Only []string`/`Except []string` slices:

Here:

https://github.com/hashicorp/packer/blob/553b1fb9f85b0dfd5a59812b4217661f8cc896bd/hcl2template/types.build.provisioners.go#L12-L20

and here:
https://github.com/hashicorp/packer/blob/553b1fb9f85b0dfd5a59812b4217661f8cc896bd/hcl2template/types.build.provisioners.go#L27-L33

The skip should happen here, right before the provisioner is started, we check for the provisioners blocks `only`/`except` stanzas and call `continue` if need be.

https://github.com/hashicorp/packer/blob/553b1fb9f85b0dfd5a59812b4217661f8cc896bd/hcl2template/types.packer_config.go#L191-L194
