### ISSUE TITLE
v1.4.5 source_ami_filter.owners multiple owners incorrectly applied

### ISSUE THREAD

**Issue by nodesocket** [hashicorp/packer#9096]
Running packer `1.4.5` on macOS.

```
    "source_ami_filter": {
            "filters": {
                "tag:Family": "base-ubuntu-1604-lts"
            },
            "most_recent": true,
            "owners": [
                "925436380237",
                "877582443575",
                "749573439694",
                "632774551702"
            ]
        },
```

Returns the error:

```
Build 'amazon-ebs' errored: No AMI was found matching filters: {
  Filters: [{
      Name: "tag:Family",
      Values: ["base-ubuntu-1604-lts"]
    }],
  Owners: [
    "632774551702",
    "632774551702",
    "632774551702",
    "632774551702"
  ]
}

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: No AMI was found matching filters: {
  Filters: [{
      Name: "tag:Family",
      Values: ["base-ubuntu-1604-lts"]
    }],
  Owners: [
    "632774551702",
    "632774551702",
    "632774551702",
    "632774551702"
  ]
}
```

**It's just repeating the last element of the `owners[]` array _n_ number of times instead of all the individual elements in the array.**

**Comment by nywilken** [comment]
Hi @nodesocket thanks for reaching out. This issue was resolved in #8491 which was released in Packer v1.5.0. If you upgrade to the latest release you should be good to go. 

I'm going to close this issue seeing as it has been resolved in the latest release. But do reach out if you run into any other problems that you suspect might be a bug. Cheers!

**Comment by nodesocket** [comment]
@nywilken could not locate any documentation on upgrading Packer from 1.4.X to 1.5.X. Are there any breaking changes? Using the AWS provider.

**Comment by SwampDragons** [comment]
In general any breaking changes will be fixed by calling "packer fix yourtemplate.json" after updating your version of Packer.

**Comment by SwampDragons** [comment]
You can also check the changelog for "builder/amazon" and "backwards incompatabilities": https://github.com/hashicorp/packer/blob/master/CHANGELOG.md#155-upcoming
