### ISSUE TITLE
Removal of iso_paths before finishing build for vsphere-iso

### ISSUE THREAD

**Issue by erikgraa** [hashicorp/packer#9117]
#### Feature Description

Including more than one of either iso_urls or iso_paths for a build seems to permanently add an extra CD-rom drive to a virtual machine.

![image](https://user-images.githubusercontent.com/20067955/80265929-a1269500-8699-11ea-906e-4f39bf9e97a0.png)

#### Use Case(s)

It would be nice if it were possible to revert to having only a single CD-rom just prior to a build finishing up. Rarely does one _want_ more than one CD-rom apart from during a packer build.

**Comment by erikgraa** [comment]
I found the `remove_cdrom`directive that was merged in #8690. 

If one specifies `remove_cdrom` as true, it seems that all CD-roms on the VM are removed. I only want the superfluous ones removed and not the default CD-rom that comes when creating a VMware VM.

Any chance one can reorganize `remove_cdrom` to support this trinary granularity? Right now it either removes all of them or none at all.

**Comment by SwampDragons** [comment]
Thanks for opening. I'm not sure when we'll get a chance to look at this, but PRs are welcome if someone from the community wants to work on it.

**Comment by jhawk28** [comment]
I suggest that the builder remove all but one CD drive by default. The alternative is to make remove_cdrom into an integer so that it can specify how many cdrom drives should be left.

**Comment by rwroe** [comment]
> I suggest that the builder remove all but one CD drive by default. 

I think this is a great solution and would love to see it implemented. We typically have 1 cdrom on our template and currently have to remove the extra one that is created.
