### ISSUE TITLE
hcl2: support --on-error parameter 

### ISSUE THREAD

**Issue by zenitraM** [hashicorp/packer#9126]
#### Feature Description

The `--on-error` build parameter gets ignored when doing a HCL2 build, while it does on JSON. You can reproduce by running an `--on-error=ask` with both:

```
$ cat packer.json 
{
    "builders": [
        {
            "type": "vagrant",
            "communicator": "ssh",
            "source_path": "ubuntu/xenial64"
        }
    ],
    "provisioners": [
        {
            "type": "shell",
            "inline":[
                "exit 1"
            ]
        }
    ]
}

$ cat packer.pkr.hcl 
source "vagrant" "vagrant" {
  communicator = "ssh"
  source_path  = "ubuntu/xenial64"
}

build {
  sources = [
    "source.vagrant.vagrant",
  ]

  provisioner "shell" {
    inline = [
      "exit 1"
    ]
  }
}
```

(I know HCL2 support is still beta, but it wasn't obvious to me at first that this was missing due to HCL2 vs JSON :blush:. Opening this issue as I couldn't find any other tracking this feature in specific.)

**Comment by sylviamoss** [comment]
Closing this one because it was fixed and released on v1.7.0.
