### ISSUE TITLE
Hyperv-iso fail to download file using smb scheme

### ISSUE THREAD

**Issue by lovilak** [hashicorp/packer#9127]
#### Overview of the Issue

Failed to download iso file using **smb** path with **hyperv-iso**

#### Reproduction Steps
```

.\packer build -var "vm_name=VM-TEST"  -var "iso_url=\\share\up\pub\Conf\2016_64Bits.ISO" -var "memory=2048" -var
 "disk_size=133120" -var "vm_version=2" -var "skip_export=true" -var "output=V:" -var "secondary_iso_images=.\temp\answer2020172159.iso" .\config\windo
ws_2016.json

### Packer version

From `1.5.5`

### Log Fragments and crash.log files

==> hyperv-iso: Creating build directory...
==> hyperv-iso: Retrieving ISO
==> hyperv-iso: Trying \\share\up\pub\Conf\2016_64Bits.ISO
==> hyperv-iso: Trying smb://share\up\pub\Conf\2016_64Bits.ISO?checksum=sha256%3A36B60C31CAFA2D488FE5D842D1FFBA623381F5E9F70E9359B3AA05282C9D232D
==> hyperv-iso: Download failed download not supported for scheme 'smb'
==> hyperv-iso: error downloading ISO: [download not supported for scheme 'smb']
==> hyperv-iso: Deleting output directory...
==> hyperv-iso: Deleting build directory...
Build 'hyperv-iso' errored: error downloading ISO: [download not supported for scheme 'smb']

==> Some builds didn't complete successfully and had errors:
--> hyperv-iso: error downloading ISO: [download not supported for scheme 'smb']

==> Builds finished but no artifacts were created.

```

**Comment by nywilken** [comment]
Hi @lovilak thanks for reaching out. This is an issue with the upstream go-getter pkg Packer is using for downloading files. As specified in #8552, which it  looks like you are already tracking (thanks for testing). I'm going to close this issue in an effort to keep the discussion in one place. If you think this issue should be tracked separately let me know and I will gladly reopen.

**Comment by lovilak** [comment]
> 
> 
> Hi @lovilak thanks for reaching out. This is an issue with the upstream go-getter pkg Packer is using for downloading files. As specified in #8552, which it looks like you are already tracking (thanks for testing). I'm going to close this issue in an effort to keep the discussion in one place. If you think this issue should be tracked separately let me know and I will gladly reopen.

Right, i follow the other report.  Thanks for your support.
