### ISSUE TITLE
SSH overrides not working for Azure VM

### ISSUE THREAD

**Issue by adamrushuk** [hashicorp/packer#9130]
#### Overview of the Issue

I'm trying to override the default SSH username and key file by using the following:

```json
"ssh_username": "sysadmin",
"ssh_private_key_file": "~/.ssh/id_rsa"
```

#### Reproduction Steps

I've uploaded all test files here: https://github.com/adamrushuk/Packer-Templates/tree/master/azure-test

### Packer version

`Packer v1.5.5`

### Simplified Packer Buildfile

https://github.com/adamrushuk/Packer-Templates/blob/master/azure-test/rhel.json

### Operating system and Environment details

Running via WSL on Windows 10.

### Log Fragments and crash.log files

I can see in the logs that the default `packer` user is still being passed to the ARM template, and there is no matching SSH key data for my existing SSH keys, eg:

`\"adminUsername\":\"packer\",\"computerName\":\"pkrvmjklk0uqfwm\",\"linuxConfiguration\":{\"ssh\":{\"publicKeys\":[{\"keyData\":\"ssh-rsa AAAAB3NzaC1y...<REMOVED>`

**Comment by SwampDragons** [comment]
Thanks for opening. I'll try to take a look before the next release.

**Comment by nywilken** [comment]
Hi @adamrushuk I think this may have been fixed by #9103, which is scheduled to be released in v1.5.6. There are test binaries available via the link below if you would like to give the patch a try. 

https://app.circleci.com/pipelines/github/hashicorp/packer/4726/workflows/24332680-9fe6-445d-ac2e-14c0bf75ab1f/jobs/47286/artifacts

**Comment by adamrushuk** [comment]
Thanks for the quick response guys. 
Happy to confirm that `v1.5.6` fixes the issue, as I can see my custom SSH username and public key being passed to the ARM template in the Packer logs.

Any idea when `v1.5.6` will be released?

**Comment by SwampDragons** [comment]
The plan is this Friday, though it may end up early next week instead.

**Comment by adamrushuk** [comment]
Excellent work, thanks Megan.
