### ISSUE TITLE
failed while creating image in GCP

### ISSUE THREAD

**Issue by farrukhfareed13** [hashicorp/packer#9133]
I have use packer for creating GCP images , there i used preemptible instances for cost saving most of the time it failed to create image giving errors like below: 
**==> googlecompute: dial tcp x.x.x.x:22: i/o timeout**
                                        or
**==> googlecompute: Error creating instance: 1 error(s) occurred:
==> googlecompute: 
==> googlecompute: * Instance failed to start due to preemption.
Build 'googlecompute' errored: Error creating instance: 1 error(s) occurred:

* Instance failed to start due to preemption.**

i am using
Packer version: 1.3 
Builder: GCP
Provisioner: Ansible
GCP Region: us-east4

Please help me out here

**Comment by sylviamoss** [comment]
Hello there! Thanks for reaching out. In order for us to best help could you provide the things requested in the issue template; including the simplest Packer configuration and scripts needed to reproduce the bug.

Have you tried running your build with a newer Packer version?

**Comment by SwampDragons** [comment]
We can't control whether google preempts your instance and by their nature Packer builds are not fault-tolerant jobs that can survive preemption. The option to run on preemptible instances exists for people who have very short-running Packer jobs that are likely to complete successfully before an instance is preempted, but if you have a longer build or If you aren't interested in tolerating failures, then I'm afraid the only solution is don't use a preemptible instance.
