### ISSUE TITLE
Nightly builds for Windows are extracted into an unexpected format

### ISSUE THREAD

**Issue by icnocop** [hashicorp/packer#9135]
Hi.

#### Overview of the Issue

The 1.5.6 nightly build https://github.com/hashicorp/packer/releases/tag/nightly has the asset "packer_windows_amd64.zip" but it doesn't have packer.exe inside.

#### Reproduction Steps

Download https://github.com/hashicorp/packer/releases/download/nightly/packer_windows_amd64.zip and notice packer.exe is not inside the archive.
I only see the file `pkg\packer_windows_amd64` without a file extension.
Trying to rename the file as a zip or exe don't work as expected so I'm not sure what format it's in.

I expected to be able to download a zip with packer.exe inside, like the official download 
https://releases.hashicorp.com/packer/1.5.5/packer_1.5.5_windows_amd64.zip.

I also expected to be able to download `packer_windows_386.zip`.

I'm not sure if the same issue exists in the other non-source code zip files.

### Operating system and Environment details

Windows 10 64-bit

Thank you.

**Comment by nywilken** [comment]
Hi there @icnocop thanks for reaching out. This is an issue we are working to resolve. For now, the generated nightly binaries are currently not signed so they must also be trusted on new versions of Windows before they can be executed. Below is a set of powershell commands I use to rename, unblock and run the nightly bins. 


```
PS C:\Users\vagrant\Downloads\packer_windows_amd64> wget https://github.com/hashicorp/packer/releases/download/nightly/packer_windows_amd64.zip -outfile packer_windows_amd64.zip
PS C:\Users\vagrant\Downloads> Expand-Archive '.\packer_windows_amd64.zip'
PS C:\Users\vagrant\Downloads> cd .\packer_windows_amd64\
PS C:\Users\vagrant\Downloads\packer_windows_amd64> mv .\pkg\packer_windows_amd64 .\pkg\packer_windows_amd64.exe
PS C:\Users\vagrant\Downloads\packer_windows_amd64> Unblock-File -Path .\pkg\packer_windows_amd64.exe
PS C:\Users\vagrant\Downloads\packer_windows_amd64> .\pkg\packer_windows_amd64.exe version
Packer v1.5.6-dev (c0a6623ea2daedea3686679d61fda6571c0a64bc)
PS C:\Users\vagrant\Downloads\packer_windows_amd64> .\pkg\packer_windows_amd64.exe help
Usage: packer [--version] [--help] <command> [<args>]

Available commands are:
    build       build image(s) from template
    console     creates a console for testing variable interpolation
    fix         fixes templates from old versions of packer
    inspect     see components of a template
    validate    check that a template is valid
    version     Prints the Packer version

PS C:\Users\vagrant\Downloads\packer_windows_amd64>
```

Please let me know if this helps get the bins into a runnable state.

**Comment by icnocop** [comment]
Thank you!

It works now. 😄

**Comment by nywilken** [comment]
Awesome! Glad to hear we were able to get that all squared away. In the meantime, I'm going to keep this open and change the title a bit to see if I can add some documentation to the nightly release description to help others.

**Comment by nywilken** [comment]
@icnocop thanks again for reaching out. I went ahead and updated the description for our nightly releases with some instructions to help other users out in future. Feel free to take a read and let me know if you have any suggestions. 

I'm going to close this issue now that the documentation is in place. Cheers!
