### ISSUE TITLE
Allow azurerm to build in one subscription & publish to another subscription

### ISSUE THREAD

**Issue by szaher** [hashicorp/packer#9137]
#### Feature Description

Allow packer azurerm shared_image_gallery_destination to have a field subscription_id to allow packer to build images in one subscription and publish to the image gallery which is located in another subscription

Shared Image gallery created in Subscription A
Packer to build in Subscription B
Packer to publish the image to Shared Image gallery in Subscription A

Image is built in Subscription B & Publish in Subscription A (where the gallery is located)

#### Use Case(s)

    "shared_image_gallery_destination": {
      "subscription_id": "{{user `sig_subscription_id`}}",
      "resource_group": "{{user `sig_resource_group`}}",
      "gallery_name": "{{user `sig_gallery_name`}}",
      "image_name": "{{user `image_name`}}",
      "image_version": "{{user `sig_image_version`}}",
      "replication_regions": "{{user `sig_regions`}}"
    },

**Comment by nywilken** [comment]
Hi @szaher thanks for reaching out. I'm going to close this issue since it is a duplicate. But please feel free to add any new comments or additional asks around this request to #8608. Cheers!
