### ISSUE TITLE
Add source image name support in AliCloud builder

### ISSUE THREAD

**Issue by ghtrke** [hashicorp/packer#9138]
#### Feature Description

Currently we can only specify the source image id in the builder: `source_image`. Could you please add a field so that we can specify the source image name in the builder? Or maybe add a similar feature as `source_ami_filter` in AWS builder. 

#### Use Case(s)

Our requirement is to use packer to first build a base image, and then build app images on top of it. Currently we can only specify the id of the source image as `source_image`.  However, in our case, the id of the base image is automatically generated from packer result. Besides, the base image is going to have different versions as time goes on. Therefore, it would be great if we could specify the source image name in the builder.

**Comment by fitzwar** [comment]
Any update if this is being added as would be extremely useful
