### ISSUE TITLE
azure-arm builder does not allow subscription_id selection when using managed identity authentication

### ISSUE THREAD

**Issue by dougbw** [hashicorp/packer#9140]
#### Overview of the Issue

Currently it is impossible to specify a subscription_id when using managed identity authentication, as when **only** subscription_id is provided packer assumes an interactive login is desired.

In our case we need the base images to be stored in a different subscription to on running our CI/CD pipeline build agents. A single managed identity can have access to many Azure subscriptions.

#### Reproduction Steps

- Create a user assigned managed identity
- Grant the identity Azure RBAC permissions to multiple subscriptions
- Assign the managed identity to a vm 
- On the vm execute `az login --identity` and you should see output for multiple subscriptions
- Provide a subscription_id to the azure-arm builder in packer and you will be stuck on an interactive login

**Comment by nywilken** [comment]
Related #8608

**Comment by amarkulis** [comment]
Is there a work around for this? This makes using managed identities impossible because every result returns: "Cannot locate the managed image resource group"
