### ISSUE TITLE
vsphere-template post-proccessor does not support vsphere-iso builder artifacts

### ISSUE THREAD

**Issue by nywilken** [hashicorp/packer#9141]
When testing the `vsphere-template` post-processor with a `vsphere-iso` builder I get an error indicating that the post-processor can only take an artifact from the VMware-iso builder or the vsphere post-processor. Using a the `vsphere` post-processor in conjunction with the `vsphere-template` just might the be way forward. But opening the issue in case this is something we should implement.

#### Reproduction Steps

Run a build using the vsphere-iso builder and vsphere-template post-processor.

### Packer version

v1.5.5

### Simplified Packer Buildfile

```
{
  "builders": [
    {
      "type": "vsphere-iso",

      "datacenter":          "{{ user `datacenter_name`}}",
      "vcenter_server":      "{{ user `vcenter_endpoint` }}",
      "username":            "{{ user `vcenter_user` }}",
      "password":            "{{ user `vcenter_password` }}",
      "host":                "{{ user `esxi_host` }}",

      "insecure_connection": "true",

      "vm_name": "example-ubuntu-{{timestamp}}",
      "network":  "VM Network",

      "guest_os_type": "ubuntu64Guest",

      "ssh_username": "vagrant",
      "ssh_password": "vagrant",

      "CPUs":             1,
      "RAM":              1024,
      "RAM_reserve_all": true,

      "disk_controller_type":  "pvscsi",
      "disk_size":        32768,
      "disk_thin_provisioned": true,
      "datastore": "datastore1",

      "network_card": "vmxnet3",

      "export": {
      },

      "iso_urls": [
        "http://releases.ubuntu.com/16.04/ubuntu-16.04.6-server-amd64.iso"
      ],
      "iso_checksum": "056b7c15efc15bbbf40bf1a9ff1a3531fcbf70a2",
      "iso_checksum_type": "sha1",

      "floppy_files": [
        "./preseed_hardcoded_ip.cfg"
      ],
      "boot_command": [
        "<enter><wait><f6><wait><esc><wait>",
        "<bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>",
        "<bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>",
        "<bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>",
        "<bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>",
        "<bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>",
        "<bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>",
        "<bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>",
        "<bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>",
        "<bs><bs><bs>",
        "/install/vmlinuz",
        " initrd=/install/initrd.gz",
        " priority=critical",
        " locale=en_US",
        " file=/media/preseed_hardcoded_ip.cfg",
        " netcfg/get_ipaddress={{ user `vm_ip` }}",
        " netcfg/get_gateway={{ user `gateway_ip`}}",
        "<enter>"
      ]
    }
  ],

  "provisioners": [
    {
      "type": "shell",
      "inline": ["ls /"]
    }
  ],
  "post-processors": [
      {
        "type": "vsphere-template",
        "name": "convert-to-template-{{build_name}}",
        "host": "{{user `esxi_host`}}",
        "username": "{{user `vcenter_user`}}",
        "password": "{{user `vcenter_password`}}",
        "insecure": true,
        "datacenter": "{{user `datacenter_name`}}",
        "folder": "/pp/testing",
        "reregister_vm": false
      }
  ]
}
```

### Operating system and Environment details

Linux, amd64

### Log Fragments and crash.log files

```
Build 'vsphere-iso' errored: 1 error(s) occurred:

* Post-processor failed: The Packer vSphere Template post-processor can only take an artifact from the VMware-iso builder, built on ESXi (i.e. remote) or an artifact from the vSphere post-processor. Artifact type jetbrains.vsphere does not fit this requirement                                 

==> Some builds didn't complete successfully and had errors:
--> vsphere-iso: 1 error(s) occurred:

* Post-processor failed: The Packer vSphere Template post-processor can only take an artifact from the VMware-iso builder, built on ESXi (i.e. remote) or an artifact from the vSphere post-processor. Artifact type jetbrains.vsphere does not fit this requirement 
```

**Comment by jhawk28** [comment]
#9146 should fix this

**Comment by cyberjacob** [comment]
Was that fix included in version 1.5.6? If so, I'm still seeing this issue.

**Comment by SwampDragons** [comment]
No, it will be out with v1.6.  However, the nightly builds should have this fix: https://github.com/hashicorp/packer/releases/tag/nightly

**Comment by cyberjacob** [comment]
Thanks, I've just tried this after making the relevant config changes however it appears #9281 is now stopping this from working.

**Comment by SwampDragons** [comment]
ah, sorry. I'll try to get that fixed up this week.

**Comment by cyberjacob** [comment]
No worries, I'm trying with `iso_url` but the download is rather slow.

Out of interest, is there any documentation going up on the config changes made in #9149 (`disk_size`, `disk_thin_provisioned`, `network`, and `network_card` removed) and how to migrate? The PR says they were deprecated but there's nothing in the 1.5.6 documentation about that.

**Comment by SwampDragons** [comment]
That PR wasn't merged in time for v1.5.6 either -- it'll go out with v1.6.0 and you can migrate by calling `packer fix yourtemplate.json`

Normally we call these things out in the changelog release notes rather than the builder documentation pages. I'll make sure it's noted there.

**Comment by jhawk28** [comment]
Note, you can point the iso_url at a local file (doesnt need to be an http url). You can use the `packer fix mytemplate.json` with 1.6 to auto update to the new fields (note, the new config was added so you can still go back to 1.5.5+ if you want).
On 5/26/2020 4:35:46 PM, Jacob Mansfield <notifications@github.com> wrote:
No worries, I'm trying with iso_url but the download is rather slow.
Out of interest, is there any documentation going up on the config changes made in #9149 [https://github.com/hashicorp/packer/pull/9149] (disk_size, disk_thin_provisioned, network, and network_card removed) and how to migrate? The PR says they were deprecated but there's nothing in the 1.5.6 documentation about that.

**Comment by cyberjacob** [comment]
@SwampDragons I'm sure the changelog will be fine, that's what I get for using the pre-release.

@jhawk28 Ah, that's working nicely thanks.

Unfortunately I'm stuck again because of #1970, but I can work around that by having `vsphere-iso` build it in the `Discovered virtual machine` folder. Apologies for turning this into a general support request, I can go somewhere else if you'd prefer, but can I ask why that was closed as a won'tfix with no details? And thanks for all your help!

**Comment by SwampDragons** [comment]
At the time it was closed, there was only one person maintaining Packer and I suspect this was closed as part of a major cleanup/prioritization project when the maintainer was figuring out roadmap for the next year. He probably just decided he wouldn't have time to work on it. If that's a feature you'd like to see though, we can revisit it now that the team is bigger and we have more community engagement on the project. 

I don't mind having this conversation here. Linking the issues together is useful for historical context.

**Comment by jhawk28** [comment]
Is there a reason why you are using the post_processor to create a template instead of using the https://www.packer.io/docs/builders/vmware/vsphere-iso/#convert_to_template flag?

I suspect that #1970 is related to the post-processor, not vsphere-iso.

**Comment by cyberjacob** [comment]
Have to be honest, I didn't even realise that was an option. This is my first real attempt at infrastructure as code so I'm kinda guessing as I go along. That's just finished running on the pre-release, hopefully it will work with Terraform and I can get it to provision k8s on a couple of VMs with some containers.

**Comment by cyberjacob** [comment]
Unfortunately I'm back to my original problem (`Error: error sending customization spec: Customization of the guest operating system 'debian10_64Guest' is not supported in this configuration. Microsoft Vista (TM) and Linux guests with Logical Volume Manager are supported only for recent ESX host and VMware Tools versions. Refer to vCenter documentation for supported configurations.`), though obviously this is a vCenter issue not Packer or Terraform
