### ISSUE TITLE
virtualbox-iso: allow to specify a name for artifact file different than vm_name

### ISSUE THREAD

**Issue by nqb** [hashicorp/packer#9145]
#### Feature Description

When you build a virtual machine, you may want to have a name for the artifact different than name of the machine. Currently (Packer 1.5.6), it's not possible. The `VBoxManager export` command used by Packer use the `vm_name` setting as filename of artifact.

#### Use Case(s)

I'm building a virtual machine using `virtualbox-iso` builder and I want to add to my artifact filename, the version of the box.

**Comment by orcutt989** [comment]
+1 to this

**Comment by rai20** [comment]
+1 to this
