### ISSUE TITLE
LXD file provisioner uploads directory to the wrong folder when source has trailing slash

### ISSUE THREAD

**Issue by chrisoldwood** [hashicorp/packer#9147]
#### Overview of the Issue

When building an LXD image with `1.5.4` or `1.5.5` of packer we are seeing the file provisioner writing to the wrong directory when the source directory contains a trailing slash. [The documentation](https://www.packer.io/docs/provisioners/file.html#directory-uploads) states the following behaviour is to be expected:

> Next, the existence of a trailing slash on the source path will determine whether the directory name will be embedded within the destination, or whether the destination will be created.
[…]
If the source, however, is /foo/ (a trailing slash is present), and the destination is /tmp , then the contents of /foo will be uploaded into /tmp directly.

#### Reproduction Steps

The following snippet is what we've been using fine up until now:

```
    {
      "type": "file",
      "source": "../",
      "destination": "/report-runner"
    }
```

We see the following results:

| Version | Folder written to |
| ------- | ---|
| `1.4.4` | `/report-runner` |
| `1.5.4` | `/report-runner/report-runner` |
| `1.5.5` | `/` |

_Note: for `1.5.5` `/` is probably equivalent to `/report-runner/..`._

### Packer version

`1.5.4` or `1.5.5` appear broken while `1.4.4` appears correct (IMHO).

### Operating system and Environment details

Ubuntu `18.04` 64-bit.
LXC `4.0.1`

**Comment by chrisoldwood** [comment]
This feels related to [#8547 Packer image building fails with LXD upon file provisioner](https://github.com/hashicorp/packer/issues/8547).

**Comment by nywilken** [comment]
Hi @chrisoldwood thanks for reaching out. The lxd builder is a community supported pluign, which means the HashiCorp maintainers don't spend much time on it. I can't say that we will be able to prioritize a fix for this issue soon. But we do prioritize reviewing PRs so if you wanted to contribute a fix we would gladly help review and provide guidance.

**Comment by azr** [comment]
To add more context the latest behavioural change of that code happens here: https://github.com/hashicorp/packer/pull/8636


https://github.com/hashicorp/packer/blob/15cbe4769c0bc3105ccdce5f38503f4e06ad471e/builder/lxd/communicator.go#L90-L94

**Comment by chrisoldwood** [comment]
Having just had to revisit this again I now think I understand what's changed so in case anyone else stumbles across this old thread (probably me, again 🙂) here goes.

In the pre `1.5` days the LXD file provider used a `tar ... | lxc exec ...` approach which meant the destination _was_ the target folder, but post `1.5` the switch to `lxc file push` meant the provider took on the semantics of the underlying LXC command. That command always appears to create a destination folder no matter what combination of trailing slashes are used on the source or destination, i.e. these always do the same thing (LXD `4.14`):
```
$ lxc file push -r ../ test/report-runner
$ lxc file push -r ../ test/report-runner/
$ lxc file push -r .. test/report-runner/
$ lxc file push -r .. test/report-runner
```

The reason this is awkward in our scenario is that `../` refers to a folder name we don't always control and so using `../` for the source and simply `/` for the destination would break if the parent folder name changed. For sure this is a problem we will have to work around but at least I now know _why_ things changed the way they did. (In the other instance this bit me I had control of the source folder so it was easier to remediate.)
