### ISSUE TITLE
same kickstart file, but no ip when using vmware-iso

### ISSUE THREAD

**Issue by orcutt989** [hashicorp/packer#9150]
#### Overview of the Issue

I am switching from `vsphere-iso` to `vmware-iso` and now my VMs can't get IP addresses. I believe I already did the `GuestIPHack` on the ESX host I am targeting. I am not sure if that is relevant.  It seems like something about the networking in the `vmware-iso` builder is different preventing the machine from getting an IP. This kickstart file works fine with the `vsphere-iso` builder but not with the `vmware-iso` builder.

I have verified this by logging in manually to the vm via the console and doing an `ip addr` and seeing no IP address.

#### Reproduction Steps

1. Use `vsphere-iso` builder, machine gets IP from DHCP.
![image](https://user-images.githubusercontent.com/5608027/80832372-892fa380-8bba-11ea-80ad-0393e4ef6d41.png)

2. Use `vmware-iso`, machine does not get IP.
![image](https://user-images.githubusercontent.com/5608027/80827891-6ef1c780-8bb2-11ea-8035-ddb3ca0bfab6.png)

### Packer version

1.5.5

### Simplified Packer Buildfile

Kickstart file used by both builders
```
logging --level=debug
cdrom
lang en_US
keyboard us
timezone UTC
network --bootproto=dhcp
rootpw --plaintext REDACTED
firewall --enabled
selinux --permissive
bootloader --location=mbr
 
text
skipx
zerombr
 
clearpart --all --initlabel
autopart
 
firstboot --disable
reboot
%packages
@^minimal
@core
chrony
kexec-tools
%end
 
 
%post
yum install -y deltarpm
yum -y update
yum -y install open-vm-tools
systemctl enable vmtoolsd
systemctl start vmtoolsd

exec < /dev/tty3 > /dev/tty3
chvt 3
echo
echo "################################"
echo "# Running Post Configuration   #"
echo "################################"
(
echo 'Hello, World!'
) 2>&1 | /usr/bin/tee /var/log/post_install.log
chvt 1
%end
```

vmware-iso builder template

```
{
  "builders": [{
    "boot_wait": "5s",
    "boot_command": [
      "<esc>",
      "<wait>linux inst.ks=hd:/dev/fd0:ks.cfg<enter>"
    ],
    "floppy_files": [
      "ks.cfg"
    ],
    "type": "vmware-iso",
    "remote_username": "REDACTED",
    "remote_password": "{{user `vcenter_password`}}",
    "iso_checksum_type": "file",
    "iso_checksum": "http://ftp.ussg.iu.edu/linux/centos/7.7.1908/isos/x86_64/sha256sum.txt.asc",
    "guest_os_type": "centos7_64Guest",
    "iso_urls": "http://ftp.ussg.iu.edu/linux/centos/7.7.1908/isos/x86_64/CentOS-7-x86_64-Minimal-1908.iso",
    "vm_name": "devops-packer-base-centos-{{user `unix_timestamp`}}",
    "ssh_username": "REDACTED",
    "ssh_password": "REDACTED",
    "disk_size": "40000",
    "remote_host": "REDACTED",
    "remote_datastore": "ISOs",
    "remote_cache_datastore": "ISOs",
    "remote_cache_directory": "ISOs",
    "network": "VM Network",
    "network_adapter_type": "vmxnet3",
    "memory": "8000",
    "remote_type": "esx5",
    "skip_export": true,
    "format": "ova",
    "vnc_disable_password": true,
    "ssh_timeout": "40m"
  }
],
  "provisioners" :[{
    "type": "inspec",
    "profile": "inspec/base-os"
  }]
}
```

vsphere-iso builder template
```
{
  "builders": [{
    "boot_wait": "5s",
    "boot_command": [
      "<esc>",
      "<wait>linux inst.ks=hd:/dev/fd0:ks.cfg<enter>"
    ],
    "floppy_files": [
      "ks.cfg"
    ],
    "type": "vsphere-iso",
    "vcenter_server": "REDACTED",
    "username": "REDACTED",
    "password": "{{ user `vcenter_password`}}",
    "iso_checksum_type": "file",
    "iso_checksum": "http://ftp.ussg.iu.edu/linux/centos/7.7.1908/isos/x86_64/sha256sum.txt.asc",
    "guest_os_type": "centos7_64Guest",
    "iso_urls": "http://ftp.ussg.iu.edu/linux/centos/7.7.1908/isos/x86_64/CentOS-7-x86_64-Minimal-1908.iso",
    "vm_name": "devops-packer-base-centos",
    "ssh_username": "REDACTED",
    "ssh_password": "REDACTED",
    "disk_size": "40000",
    "host": "REDACTED",
    "insecure_connection": "true",
    "datastore": "VM-DATASTORE-2 (1)",
    "network": "VM Network",
    "network_card": "vmxnet3",
    "RAM": "8000",
    "export": {
      "force": true,
      "output_directory": "./output_vsphere"
      }
  }
],
  "provisioners" :[{
    "type": "inspec",
    "profile": "inspec/base-os"
  }]
}
```

### Operating system and Environment details

macOS Catalina 10.15.4

### Log Fragments and crash.log files

Packer build log
```
...
2020/05/01 14:51:13 packer-builder-vmware-iso plugin: [DEBUG] Opening new ssh session
2020/05/01 14:51:13 packer-builder-vmware-iso plugin: [DEBUG] starting remote command: esxcli --formatter csv network vm list
2020/05/01 14:51:14 packer-builder-vmware-iso plugin: [DEBUG] Error getting SSH address: EOF
...
```

**Comment by orcutt989** [comment]
I figured it out! It's because the `network` value on the `vsphere-iso` bulilder is the network name, but the `network` value in the `vmware-iso` builder is for the [Network Configurations](https://www.vmware.com/support/ws4/doc/network_common_ws.html#1061764) or [Network Types](https://www.packer.io/docs/builders/vmware-iso.html#network) as referenced by the Hashicorp docs. I would recommend clarifying this in the Hashicorp docs.

**Comment by nywilken** [comment]
Hi @orcutt989 glad you were able to get the network situation squared away. I'm going to label this as a docs enhancement issue. With that said, and if you're comfortable with it, would you like to open a PR with the relevant documentation changes? I would be happy to review and help you push it through. 

The documentation for Packer builders are auto generated so if you update the cofiguration option  https://github.com/hashicorp/packer/blob/18ce764b97c2cf4904fe378dd21dc034b9a8a90f/builder/vmware/common/hw_config.go#L26  we can update the docs via `make generate`. 


Re: I also had to add, I would need to take a look to see what is going on. 
```
    "vmx_data": {
      "ethernet0.networkName": "VM Network"
    }
```

**Comment by orcutt989** [comment]
I would love to contribute to the docs. I would also like to see if we can maybe match up the values or change the function of the `network` value to match between the two builders. Get `vmware-iso` to use the same function for `network` as the `vsphere-iso` builder. Then that would eliminate the need for the `vmx_data` since it is not needed in the `vsphere-iso` builder.

**Comment by SwampDragons** [comment]
That sounds great. We definitely should try to get the network value to mean the same thing between the two.

**Comment by orcutt989** [comment]
On second thought I think the documentation makes sense unless we determine that `vmx_data` is mandatory for acquiring network information. Then that should be added. Will this be fixed or should we add docs?

**Comment by SwampDragons** [comment]
I can take a look and see if we can fix the vmx_data. I'll try to put this on my TODO list for next week.

**Comment by SwampDragons** [comment]
On a quick review, it does look like the only way to set network name is via vmx_data in the vmware builder.
