### ISSUE TITLE
Build 'vsphere-iso' errored: error creating vm: A specified parameter was not correct: configSpec.guestId

### ISSUE THREAD

**Issue by tbennett6421** [hashicorp/packer#9153]
#### Overview of the Issue
The documentation at https://www.packer.io/docs/builders/vsphere-iso.html doesn't contain any references to guestId or configSpec. I'm unable to find a parameter I can add to my builder to get this to complete successfully.

#### Reproduction Steps
packer build -only=vsphere-iso ubuntu-20.04-amd64.json

### Packer version
Packer v1.5.5

### Simplified Packer Buildfile
https://gist.github.com/tbennett6421/2f558d510c1deebb58fd31e9f8c5401d

### Operating system and Environment details
VMware ESXi 6.0.0
VMware vCenter 6.0.0

### Log Fragments and crash.log files
```
C:\>packer build -only=vsphere-iso ubuntu-20.04-amd64.json
vsphere-iso: output will be in this color.

==> vsphere-iso: Creating VM...
Build 'vsphere-iso' errored: error creating vm: A specified parameter was not correct: configSpec.guestId

==> Some builds didn't complete successfully and had errors:
--> vsphere-iso: error creating vm: A specified parameter was not correct: configSpec.guestId

==> Builds finished but no artifacts were created.
```

**Comment by jhawk28** [comment]
My guess is that "ubuntu-64" is not a valid guest_os_type. Try using "ubuntu64Guest".

**Comment by tbennett6421** [comment]
That allowed the build to begin. It's odd since I used `ubuntu-64` for virtualbox-iso,vmware-iso. 

Is there a way to get a list of these values supported by the vsphere-iso builder?

**Comment by jhawk28** [comment]
The documentation for the field: https://www.packer.io/docs/builders/vmware/vsphere-iso/#create-configuration has a link to the valid list of values. Here is the link for reference: https://code.vmware.com/apis/358/vsphere/doc/vim.vm.GuestOsDescriptor.GuestOsIdentifier.html

**Comment by tbennett6421** [comment]
Thank you kindly!
