### ISSUE TITLE
Build 'vsphere-iso' errored: error typing a boot command: ServerFaultCode: Unable to resolve WSDL method name PutUsbScan

### ISSUE THREAD

**Issue by tbennett6421** [hashicorp/packer#9155]
#### Overview of the Issue
VM is created and powered on, boot commands fail to be sent. Upon failure the VM is powered off and destoryed.

#### Reproduction Steps
packer build -only=vsphere-iso ubuntu-20.04-amd64.json

### Packer version
1.5.6.

### Simplified Packer Buildfile
https://gist.github.com/tbennett6421/666e4b049645c20d04745812c56526ff

### Operating system and Environment details
vSphere 6.0.0.
Esxi 6.0.0

### Log Fragments and crash.log files
https://gist.github.com/tbennett6421/266b1e5ff342938d9983d05d1f211143

**Comment by tbennett6421** [comment]
similar to #8902

**Comment by tbennett6421** [comment]
updated to Packer v1.5.6 and receive the same error messages

**Comment by jhawk28** [comment]
This is related: https://github.com/jetbrains-infra/packer-builder-vsphere/issues/63

**Comment by jhawk28** [comment]
Does `govc vm.keystrokes` work on a vm: https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#vmkeystrokes

**Comment by tbennett6421** [comment]
I'm not sure how to use govc. Do you have a complete example of something you'd like me to try?

**Comment by jhawk28** [comment]
The workaround is to upgrade to vsphere 6.5+, create a template without a boot command, or use the vmware-iso plugin with the esxi 5 connection.

**Comment by SwampDragons** [comment]
We've decided to explicitly support only vSphere 6.5 and above, because those are the versions that the vmWare golang library we use supports. I'm sorry for the inconvenience here, but our team doesn't have the bandwidth to put in the extra work to create special API bindings for vsphere 6.0 and lower.
