### ISSUE TITLE
HCL2: display full source name in ui output

### ISSUE THREAD

**Issue by greg-hellings** [hashicorp/packer#9157]
#### Overview of the Issue

I'm trying to define multiple sources from the same provider. They are all reported by the same name on the console. Sample file:

```
source "qemu" "iso" {
    iso_url = "iso_image.iso"
    qemuargs = []
}

source "qemu" "image" {
    iso_url = "qcow_image.qcow2"
    disk_image = true
    qemuargs = [
        ["-cdrom", "some/path.iso"],
        ["-cpu", "power8"]
    ]
}

build {
    sources = ["qemu.image"]
}

build {
    source = ["qemu.iso"]
}
```

#### Reproduction Steps

* Using a file similar to the above, invoke `pakcer build config`
* Sample output:

```
qemu: output will be in this color.  # In green
qemu: output will be in this color.  # In turquoise

<snip>
```

### Packer version

1.5.5

### Simplified Packer Buildfile

See above for a skeleton

### Operating system and Environment details

Running on Fedora 32, using provided binary builds from Hashicorp packaged into an RPM

**Comment by azr** [comment]
Hello @greg-hellings thanks for opening ! Yes this is something that we want to do and that shouldn't be too crazy to implement. It would be nice to have this for the next release.

**Comment by SwampDragons** [comment]
This was closed by https://github.com/hashicorp/packer/pull/9257 and will be part of the 1.6.0 release 🎉
