### ISSUE TITLE
chef-client provisioning hanging on chef install

### ISSUE THREAD

**Issue by joelmoss** [hashicorp/packer#916]
Running a build of the following template:

``` json
{
  "builders": [{
    "type": "docker",
    "image": "phusion/baseimage:latest",
    "export_path": "image.tar"
  }],
  "provisioners": [{
    "type": "chef-client",
    "server_url": "https://api.opscode.com/organizations/codio",
    "node_name": "packertest",
    "validation_key_path": "~/.chef/codio/validator.pem"
  }]
}
```

Results in this:

``` bash
==> docker: Creating a temporary directory for sharing data...
==> docker: Pulling Docker image: phusion/baseimage:latest
    docker: Pulling repository phusion/baseimage
==> docker: Starting docker container...
    docker: Run command: docker run -d -i -t -v /var/folders/h8/zf79gz151js85j_0y_hf2lvm0000gn/T/packer-docker213656163:/packer-files phusion/baseimage:latest /bin/bash
    docker: Container ID: 1f5ba04631ad63ae5524d123598acb742a8deb55f298d8bab1589244feeab3d5
    docker: Installing Chef...
```

And nothing more. It just hangs forever. I can see the container running. How can I increase verbosity or see the logs to find out what is going on?

**Comment by donfanning** [comment]
So has this issue been corrected?  I'm running into exactly the same issue.

**Comment by Purple90** [comment]
I am also having this issue. @donfanning were you able to solve this?

**Comment by donfanning** [comment]
I began going a different route with docker-compose.  Which version did you upgrade to?  I wouldn't mind seeing if this will work as I think it's silly putting more effort into making my centralized configuration management uncentralized (zero/solo)...

**Comment by Purple90** [comment]
I upgraded to the latest version of Packer (9.0). I actually have Packer + Chef + Docker working to make images atm.
