### ISSUE TITLE
vagrant post-processor does not export additional disks from qemu

### ISSUE THREAD

**Issue by rgl** [hashicorp/packer#9160]
## Overview of the Issue

#7791/#6139 introduced the `disk_additional_size` property to add additional disks to a qemu vm and that works nicely, but the vagrant post-processor is not exporting the additional disks:

```bash
$ tar tvf esxi-7.0-amd64-libvirt.box
-rw-rw-r-- rgl/rgl         814 2020-05-03 22:31 Vagrantfile
-rw-rw-r-- rgl/rgl   561774592 2020-05-03 22:31 box.img
-rw-rw-r-- rgl/rgl          57 2020-05-03 22:31 metadata.json
```

### Packer version

1.5.6

### Simplified Packer Buildfile

```json
  "builders": [
    {
      "name": "esxi-{{user `version`}}-amd64-libvirt",
      "type": "qemu",
      "disk_size": "{{user `boot_disk_size`}}",
      "disk_additional_size": ["{{user `datastore_disk_size`}}"],
      ...
```

The full template is at https://github.com/rgl/esxi-vagrant/blob/feature-upgrade-to-esxi-7/esxi.json

**Comment by nywilken** [comment]
Thanks for bubbling this up @rgl. We'll see if we can take a look at this for the next release. PRs are welcomed if you have some thoughts on the fix. Thanks again!
