### ISSUE TITLE
Need to fetch new IP of VM created by packer

### ISSUE THREAD

**Issue by purnimaY** [hashicorp/packer#9162]
Hi,

We are working on below scenario:
creating a packer JSON file to create a temporarily windows and from here we are calling ansible playbooks using ansible provisioners.  We would like to pass newly created machine IP to ansible main.yml file.

Is there any way to fetch the IP of new machine, after creating it?

Regards,
Purnima

**Comment by nywilken** [comment]
Hi @purnimaY thanks for reaching out. The IP for the newly created machine is made available via the build template engine. Depending on how you are trying to access this information  within ansible you should be able to pass the build template variable into the appropriate field `ansible_env_vars` or `extra_arguements`. Below is an example of how you could pass the IP to a playbook via an environment variable

```json
{                                                                                                                                            
  "type": "ansible",                                                                                                                             
  "use_proxy": false, 
 "ansible_env_vars": ["PACKER_BUILD_NAME={{ build_name }}", "PACKER_HOST={{build `Host`}}"],
 "playbook_file":   "./playbooks/playbook_remote.yml"
}
```

More information on the build template engine is available [here](https://www.packer.io/docs/templates/engine/#build)

If you end up needing more help with this kind of initial configuration, the mailing list or community forum are generally more useful. Issues opened here on the Packer issue tracker are only viewed by a small handful of developers who work on the tool, and we don't always have the most depth or experience when it comes to custom issues with particular build configurations. Cheers!
