### ISSUE TITLE
HCL2: Add a build.source block that allows to override specific builder fields 

### ISSUE THREAD

**Issue by arren-ru** [hashicorp/packer#9167]
Would be good to specify the container name used to build an image as of for now it is fixed for "packer-${source_name}".
This allows the scenario when need to build simultaneously few images from one source.
I would like to propose to add corresponding field to "build" section.

**Comment by nywilken** [comment]
Hi @arren-ru thanks for reaching out. Could you provide an example of the expected build configuration along with what you would expect the build results to be so that we can better understand the intent.  From your description, I can get an idea but it would help to have a visual. Thanks.

**Comment by arren-ru** [comment]
Yeah, sure.
Example build specification might be something similar to this:
```hcl
source "lxd" "arch" {
  image = "archlinux"
}

build {
  sources = [ "lxd.arch" ]

  name = "packer-k8s-${uuid}"
  output_image = "k8s"

  provisioner "shell" {
    inline = [ "pacman -Sy --noconfirm kube{adm,let,ctl} crictl containerd" ]
  }
}

build {
  sources = [ "lxd.arch" ]

  name = "packer-pdns-${uuid}"
  output_image = "pdns"

  provisioner "shell" {
    inline = [ "pacman -Sy --noconfirm pdns postgresql" ]
  }
}
```

Fields are just for example copied from JSON specification.
In addition, I am personally using makefiles with one base specification and different provisioners using variables to define which path to use for input resources.

**Comment by arren-ru** [comment]
Ok, I just found that `output_image` property works fine inside source block, but I still can not specify the 
temporary container name for an image building.

**Comment by azr** [comment]
Hello @arren-ru, could you explain a little more what you are trying to achieve here ? In a broader scope ?

If I am correct I think a possible - not yet implemented - solution  to your first problem would be to allow setting singular `source` blocks, so allow to do something like this for example:

```hcl
source "lxd" "arch" {
  image = "archlinux"
}

build {
  source "lxd.arch" {
     # here the content of a single source block would be merged with the used source
     # allowing to set more specific settings
     output_image = "k8s"
  }

  provisioner "shell" {
    inline = [ "pacman -Sy --noconfirm kube{adm,let,ctl} crictl containerd" ]
  }
}

build {
  source "lxd.arch" {
     output_image = ...
  }

  provisioner "shell" {
    inline = [ "pacman -Sy --noconfirm pdns postgresql" ]
  }
}
```

Currently the way to do this would be to have two different sources that have a different `output_image` field.

**Comment by arren-ru** [comment]
> Hello @arren-ru, could you explain a little more what you are trying to achieve here ? In a broader scope ?
> 
> If I am correct I think a possible - not yet implemented - solution to your first problem would be to allow setting singular `source` blocks, so allow to do something like this for example:
> 
> ```terraform
> source "lxd" "arch" {
>   image = "archlinux"
> }
> 
> build {
>   source "lxd.arch" {
>      # here the content of a single source block would be merged with the used source
>      # allowing to set more specific settings
>      output_image = "k8s"
>   }
> 
>   provisioner "shell" {
>     inline = [ "pacman -Sy --noconfirm kube{adm,let,ctl} crictl containerd" ]
>   }
> }
> 
> build {
>   source "lxd.arch" {
>      output_image = ...
>   }
> 
>   provisioner "shell" {
>     inline = [ "pacman -Sy --noconfirm pdns postgresql" ]
>   }
> }
> ```
> 
> Currently the way to do this would be to have two different sources that have a different `output_image` field.

This is simple – I would like to use one source for all images packer should create.
As I wrote before this is kind of template I would like to use for all builds using one source.

There is two reasons for that:
- I don't need plenty of sources with the same options
- I don't need plenty of specs with the same steps and parameters inside, the difference between them is only one provisioner script between preparation and finalizer-cleaner and also some files that I need to put inside the image.

So for the sequential build of all images for now is all done, but trying to run in parallel it goes to race condition for the name of the packer container and as a result all build are failing.

**Comment by azr** [comment]
Ah, I understand thanks for explaining, yes that makes total sense, the 'output' part of a builder should be settable specifically to avoid any race condition and in that case the example I showed should solve this. I very much would like packer to get this for 1.6 then !

**Comment by azr** [comment]
Hello again, I opened #9291 that will allow for this new feature I described earlier, you can find artifacts here: https://circleci.com/gh/hashicorp/packer/53705#artifacts/containers/0

**Comment by arren-ru** [comment]
> Hello again, I opened #9291 that will allow for this new feature I described earlier, you can find artifacts here: https://circleci.com/gh/hashicorp/packer/53705#artifacts/containers/0

Ok, thank you!
