### ISSUE TITLE
azure-arm - Allow images to be built upon custom shared gallery images

### ISSUE THREAD

**Issue by mikeclearbank** [hashicorp/packer#9171]
#### Feature Description

Currently you can build images based on marketplace images using the `image_publisher`, `image_offer` and `image_sku` properties. You can also publish your image to a shared gallery using the `shared_image_gallery_destination` object.

Can we support basing your image upon a custom image from a shared image gallery.
Example could be:

```
"shared_image_gallery_name": "mikes_gallery"
"shared_image_name": "windows_base"
"shared_image_version": "1.4.3"
```
#### Use Case(s)

- hardening requirements for all your images
- requirement for a set of common tools on all your images
- golden base image

**Comment by nywilken** [comment]
Hi there the Azure provider has an option that allows users to specify a custom managed image as the base image https://www.packer.io/docs/builders/azure/arm/#custom_managed_image_name

Have you tried using the the `custom_managed_image_name` to the name of the particular SIG image version that you would like to use as your base?

**Comment by mikeclearbank** [comment]
when attempting to use both `custom_managed_image_name` and `custom_managed_image_resource_group_name` i would get the following error:

 _Cannot find an image named 'server-core-2019-with-containers' in the resource group 'cbuk-shared-shareddevelopment-images-uksouth'_

i've tried all different combination of name from the resource, but the image can't be found?
```
"custom_managed_image_name": "server-core-2019-with-containers/1.0.160348",
"custom_managed_image_resource_group_name": "cbuk-shared-shareddevelopment-images-uksouth",
```

![image](https://user-images.githubusercontent.com/47777618/81171002-902c2c80-8f93-11ea-957d-0788db4301b4.png)


kind regards,

Mike

**Comment by mikeclearbank** [comment]
looking into the code more. The logic that looks up the image via the `custom_managed_image_resource_group_name` and `custom_managed_image_name` is using the Azure ImagesClient which doesn't find SIG images. 

The solution would also be to use the GalleryImagesClient client if the image isn't found via the ImagesClient.

**Comment by mikeclearbank** [comment]
@nywilken - are you able to confirm what i've suspected is correct so i can go back to my team and confirm its not supported.

**Comment by nywilken** [comment]
Hi @mikeclearbank apologies for the slow response here. 

It turns out that `custom_managed_image_name` is the wrong option to use here. You want the `shared_image_gallery` (NOT `shared_image_gallery_destination`!!) documented [here](https://www.packer.io/docs/builders/azure-arm.html#shared_image_gallery). 

This option is specifically for pulling a source from a shared image gallery. 

I'm going to work on the documentation to bubble up this option. But in the meantime, if you wanted to give it a try it should meet the requirements for this particular issue.

Cheers!

**Comment by nywilken** [comment]
This was closed by https://github.com/hashicorp/packer/pull/9364. The documentation is now listed under the [Azure ARM specific options](https://www.packer.io/docs/builders/azure/arm#azure-arm-builder-specific-options) section.
