### ISSUE TITLE
HCL support: get list of current limitations

### ISSUE THREAD

**Issue by nqb** [hashicorp/packer#9175]
Currently, HCL support is in beta. Some features are supported, some not. From my pont of view, it's hard to know exactly which one.

It would be interesting to have a way to know easily current limitations of HCL support.

I suggest:
- a GitHub issue that can be referenced easily.
- a temporary note in Packer's doc with a reference to that issue (in order to avoid updating documentation each time a new item is done)

**Comment by azr** [comment]
Hey @nqb wonderful idea, like an index issue, I'm creating that now.

**Comment by azr** [comment]
@nqb, I opened https://github.com/hashicorp/packer/issues/9176 for this; please tell me if something's missing there

**Comment by nqb** [comment]
Hello @azr, sounds good.

What do you think about my second proposal:

>     * a temporary note in Packer's doc with a reference to that issue (in order to avoid updating documentation each time a new item is done)

It seems important because new Packer's users will not go on GitHub first.

**Comment by nqb** [comment]
Otherwise, I read this [Announcing HashiCorp Packer 1.5 With HCL2 Support](https://www.hashicorp.com/blog/announcing-hashicorp-packer-1-5-with-hcl2-support/) blog post and I'm not sure variable interpolation is completely done.

**Comment by azr** [comment]
Okay I think this is much better now thanks @nqb ! 🙂
