### ISSUE TITLE
Vsphere-iso build error for video_ram, error is Invalid configuration for device '0'.

### ISSUE THREAD

**Issue by mrdanielmartins** [hashicorp/packer#9177]
### Overview of the Issue

When setting video_ram as an int in MB for vpshere_iso hardware configuration, I get the following error 

> Build 'vsphere-iso' errored: Invalid configuration for device '0'.

I've alternatively tried to use:
```
"configuration_parameters": {
        "svga.autodetect": "false",
        "svga.vramSize": "16384000"
},
```
but that seems to provide no input whatsoever (except if you set svga.autodetect to "true", which still won't set the vram I need.

Do you guys and girls have any other idea how to set the vram? 

### Reproduction Steps

Set video_ram in vsphere-iso builder

### Packer version

Packer version: 1.5.5

### Operating system and Environment details

Windows Server 2016 iso
VMware vSphere 6.7u3

**Comment by sylviamoss** [comment]
I've found the same issue in the previous repo for the vsphere builder https://github.com/jetbrains-infra/packer-builder-vsphere/issues/264. Can you try setting the video_ram in KB instead of MB and tell me what happens? 
I'm asking this because packer sets the value into a vshpere config that, by the name, seems to expect KB. 
https://github.com/hashicorp/packer/blob/master/builder/vsphere/driver/vm.go#L377

If that's the case we might want to update the docs or make the transformation before assigning the config internally.

**Comment by mrdanielmartins** [comment]
> I've found the same issue in the previous repo for the vsphere builder [jetbrains-infra/packer-builder-vsphere#264](https://github.com/jetbrains-infra/packer-builder-vsphere/issues/264). Can you try setting the video_ram in KB instead of MB and tell me what happens?
> I'm asking this because packer sets the value into a vshpere config that, by the name, seems to expect KB.
> https://github.com/hashicorp/packer/blob/master/builder/vsphere/driver/vm.go#L377
> 
> If that's the case we might want to update the docs or make the transformation before assigning the config internally.

Amazingm that actually worked - pardon me, should have tried in KB 🙄!!!

Here is what I did, in the for builders:

`"video_ram": "16384",`

And can now see the VRAM as I had defined:
![image](https://user-images.githubusercontent.com/37153398/81187824-70edc900-8fac-11ea-8971-7c792e0339cd.png)

Correct on that front, the official docs on the Packer website specify for vpshere-iso, the video_ram as an integer in MB https://www.packer.io/docs/builders/vmware/vsphere-iso/#video_ram

**Comment by SwampDragons** [comment]
I'll update the docs to fix this.
