### ISSUE TITLE
Remove-Item Cannot find path of temp scripts

### ISSUE THREAD

**Issue by jpgrall** [hashicorp/packer#9181]
### Overview of the Issue

Using the vsphere-iso builder on Packer 1.5.6, seeing a new issue when finishing a powershell provisioner.   Packer-cleanup-uuid.ps1 script cannot find script-uuid.ps1 files to remove on clean up.

#### Reproduction Steps

Build a Windows image with a powershell provisioner task.

### Packer version

1.5.6

### Operating system and Environment details

docker packer:light

### Log Fragments and crash.log files
<details>
 <summary>Log</summary>
16:44:49 DOCKER: ==> vsphere-iso: Provisioning with powershell script: ./scripts/get-ip.ps1
16:45:15 DOCKER: ==> vsphere-iso: Remove-Item : Cannot find path 'C:\Windows\Temp\script-5eb328c2-39b3-38a7-85eb-ff58af5ee92c.ps1' because it does not
16:45:15 DOCKER: ==> vsphere-iso: exist.
16:45:15 DOCKER: ==> vsphere-iso: At C:\Windows\Temp\packer-cleanup-5eb328c2-8d68-2c83-6532-72f695b5b2ed.ps1:3 char:1
16:45:15 DOCKER: ==> vsphere-iso: + Remove-Item c:/Windows/Temp/script-5eb328c2-39b3-38a7-85eb-ff58af5ee9 ...
16:45:15 DOCKER: ==> vsphere-iso: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
16:45:15 DOCKER: ==> vsphere-iso:     + CategoryInfo          : ObjectNotFound: (C:\Windows\Temp...f58af5ee92c.ps1:String) [Remove-Item], ItemNotFoundEx
16:45:15 DOCKER: ==> vsphere-iso:    ception
16:45:15 DOCKER: ==> vsphere-iso:     + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
16:45:15 DOCKER: ==> vsphere-iso:
16:45:15 DOCKER: ==> vsphere-iso: Remove-Item : Cannot find path 'C:\Windows\Temp\script-5eb328c2-39b3-38a7-85eb-ff58af5ee92c.ps1' because it does not
16:45:15 DOCKER: ==> vsphere-iso: exist.
16:45:15 DOCKER: ==> vsphere-iso: At C:\Windows\Temp\packer-cleanup-5eb328c2-8d68-2c83-6532-72f695b5b2ed.ps1:4 char:1
16:45:15 DOCKER: ==> vsphere-iso: + Remove-Item c:/Windows/Temp/script-5eb328c2-39b3-38a7-85eb-ff58af5ee9 ...
16:45:15 DOCKER: ==> vsphere-iso: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
16:45:15 DOCKER: ==> vsphere-iso:     + CategoryInfo          : ObjectNotFound: (C:\Windows\Temp...f58af5ee92c.ps1:String) [Remove-Item], ItemNotFoundEx
16:45:15 DOCKER: ==> vsphere-iso:    ception
16:45:15 DOCKER: ==> vsphere-iso:     + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
16:45:15 DOCKER: ==> vsphere-iso:
</details>

**Comment by nywilken** [comment]
Hi there thanks for reaching out. We will take a look as soon as we get a chance. There is a `skip_clean` config option that you can set to bypass this cleanup step as a workaround for now. 

Looking at the log I see the name of the script specified in the provisioner `scripts/get-ip.ps1` but I don’t see any log information indicating that it exited successfully before the cleanup step. Do you get the same error if you use an inline powershell provisioner command?

**Comment by jpgrall** [comment]
The error doesn't cause it to fail out, it continues on to the next provisioners properly, so no need for the workaround.  Will need to make some changes to test if throws an error during inline command.

**Comment by jpgrall** [comment]
FYI - Confirmed that the issue does not occur when running inline command.
