### ISSUE TITLE
vpshere post-provisioner urlencoded password problem

### ISSUE THREAD

**Issue by orcutt989** [hashicorp/packer#9184]
As you all know troubleshooting `ovftool` is a nightmare as the logs don't bubble up.

For some reason this only seems to be a problem on import. Export is fine! 

However i've isolated a problem where `ovftool` fails on import whether or not the password is urlencoded or not the only way the ovftool import command sucessfully is to surround the `vi://` URL with single quotes.

```
ovftool output-vmware-iso/devops-packer-base-centos-1588816488.ova 'vi://USERNAME@vsphere.local:PASSWORD@VCENTER.FQDN.OR.IP/DATACENTER/host/ESXI.HOST.FQDN'
```

Or the password will have to be URL encoded before its put into the command, but I am having trouble getting that to consistently work.

Looks like this is brought up here https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/packer-tool/kEdtattbOXQ/EbmyPrjxCAAJ and here 
https://github.com/hashicorp/packer/issues/6091

```
{
  "builders": [{
    "boot_wait": "5s",
    "boot_command": [
      "<esc>",
      "<wait>linux inst.ks=hd:/dev/fd0:ks.cfg<enter>"
    ],
    "floppy_files": [
      "ks.cfg"
    ],
    "type": "vmware-iso",
    "remote_username": "USERNAME",
    "remote_password": "{{user `vcenter_password`}}",
    "iso_checksum_type": "file",
    "iso_checksum": "http://spout.ussg.indiana.edu/linux/centos/7.8.2003/isos/x86_64/sha256sum.txt.asc",
    "guest_os_type": "centos7_64Guest",
    "iso_urls": "http://spout.ussg.indiana.edu/linux/centos/7.8.2003/isos/x86_64/CentOS-7-x86_64-Minimal-2003.iso",
    "vm_name": "devops-packer-base-centos-{{user `unix_timestamp`}}",
    "ssh_username": "USERNAME",
    "ssh_password": "PASSWORD",
    "disk_size": "40000",
    "remote_host": "HOST.IP",
    "remote_datastore": "DATASTORE",
    "remote_cache_datastore": "DATASTORE",
    "remote_cache_directory": "DIRECTORY",
    "network_adapter_type": "vmxnet3",
    "memory": "8000",
    "remote_type": "esx5",
    "format": "ova",
    "vnc_disable_password": true,
    "ssh_timeout": "40m",
    "keep_registered": false,
    "vmx_data": {
      "ethernet0.networkName": "VM Network"
    },
    "ovftool_options":[
      "--X:noPrompting"
    ]
  }
],
  "provisioners" :[{
    "type": "inspec",
    "profile": "inspec/base-os"
  }
],
"post-processors": [{
  "type": "vsphere",
  "cluster":"HOST.FQDN",
  "datacenter":"DATACENTER",
  "host": "VCENTER.FQDN",
  "password": "{{user `url_encoded_password`}}",
  "username": "USERNAME@vsphere.local",
  "datastore": "DATASTORE",
  "vm_name": "imported-devops-packer-base-centos-{{user `unix_timestamp`}}",
  "insecure": "true",
  "keep_input_artifact": true,
  "options":[
    "--X:noPrompting"
  ]
}]
}
```

**Comment by orcutt989** [comment]
I think the difference between the export and the import is this -
Export
https://github.com/hashicorp/packer/blob/eca1aad9b31b15cde3459dcc50097518a2a79046/builder/vmware/common/step_export.go#L53
Import
https://github.com/hashicorp/packer/blob/eca1aad9b31b15cde3459dcc50097518a2a79046/post-processor/vsphere/post-processor.go#L132

**Comment by orcutt989** [comment]
I have verified the following -

WITH single quotes no url escaped username or password ✅ 
```hcl
'vi://USERNAME@vsphere.local:PASSWORD_NOT_ENCODED@VCENTER.FQDN/DATACENTER/host/HOST.FQDN'
```

WITHOUT single quotes no url escaped username or password ❌ 
```hcl
vi://USERNAME@vsphere.local:PASSWORD_NOT_ENCODED@VCENTER.FQDN/DATACENTER/host/HOST.FQDN
```

WITHOUT single quotes and username is URL escaped password is not URL escaped ❌ 
```hcl
vi://USERNAME%40vsphere.local:PASSWORD_NOT_ENCODED@VCENTER.FQDN/DATACENTER/host/HOST.FQDN
```

WITHOUT single quotes and username and password are both url escaped ❌ 
```hcl
vi://USERNAME%40vsphere.local:ENCODED_PASSWORD@VCENTER.FQDN/DATACENTER/host/HOST.FQDN
```

**Comment by orcutt989** [comment]
For some reason IMPORT needs the vcenter username to have the domain `@vsphere.local` appended but EXPORT does not?

**Comment by orcutt989** [comment]
I removed  my pre-encoded`{{user `url_encoded_password`}}` because according to the code its already being encoded, so this is just being encoded again. However, the experiment above is still valid. Nothing seems to work without single quoting the entire `vi://` line.

**Comment by SwampDragons** [comment]
Thanks for the detailed investigation. Does this seem to be a result of specific special characters?

**Comment by orcutt989** [comment]
Yes it absolutely is which I know is VMWare’s fault through OVFTool, but I was hoping we could wrap this section as a workaround. Also only seems to be an issue with the import?

**Comment by SwampDragons** [comment]
yeah, we definitely need to figure out something that works here, even if it is jus ovftool being a bit janky. I was just hoping for an example that I could use to reproduce

**Comment by SwampDragons** [comment]
I refactored the code to correctly use the net/url library to do this instead of the query escape portion: several special characters are now handled differently. They were previously being encoded using url.QueryEscape whereas now they're being properly escaped as passwords. This means that the following special characters which were being percent-encoded, are now being left as-is: `$` `&` `+` `,` `;` `=`, and probably a few more but those are the ones I tested. 

I still need to test this!! BUT, I believe this is what was needed. I'd appreciate if you can grab the binaries from our CI pipeline here: https://circleci.com/gh/hashicorp/packer/66990#artifacts/containers/0 and test your use case, as extra validation for me.

**Comment by SwampDragons** [comment]
The super weird thing is that I don't understand how the export works and the import doesn't: both are escaping passwords and the export is using the same QueryEscape that the import is using; only difference is that the import had been doing some hacky workaround to not percent-encode spaces. (in the import, password was being escaped here https://github.com/hashicorp/packer/blob/eca1aad9b31b15cde3459dcc50097518a2a79046/post-processor/vsphere/post-processor.go#L131)

**Comment by SwampDragons** [comment]
Do your host or datacenter contain special characters??
