### ISSUE TITLE
Openstack,  error setting os-set_image_metadata

### ISSUE THREAD

**Issue by raypettersen** [hashicorp/packer#9190]
## Overview of the Issue
When creating an image on openstack, the last steps fail where it seems packer wants to set some metadata on the image but is unable to do so.

#### Reproduction Steps

Steps to reproduce this issue
Create a build.json with a builder such as:
```
  "builders": [
    {
      "type": "openstack",
      "communicator": "ssh",
      "ssh_pty": true,
      "name": "puppet",
      "flavor": "s2.medium.2",
      "ssh_username": "linux",
      "region": "eu-de",
      "use_blockstorage_volume": true,
      "image_name": "silver-packer-client-{{isotime}}",
      "source_image_filter": {
        "filters": {
          "name": "Standard_CentOS_7_latest"
        },
        "most_recent": true
      },
      "networks": [
        "{{user `network`}}"
      ],
      "floating_ip_network": "0a2228f2-7f8a-45f1-8e09-9039e1d09975",
      "security_groups": ["7217857b-1722-4afe-bbd6-4aeb82d47811"]

    },

```

Build completes, but during final steps of "wrapping up", the following error is displayed:
```
TestPackerBasic 2020-05-08T08:22:33+02:00 command.go:168: 2020/05/08 08:22:33 1588918953,,ui,error,==> puppet: Error setting image metadata: Bad request with: [POST https://openstack_url/v3/de92f894b64f4d1c99803d225315ff62/volumes/5cf66e2d-e970-4a1e-be21-127959bf4f8a/action]%!(PACKER_COMMA) error message: {"badRequest":{"message":"There is no such action: os-set_image_metadata"%!(PACKER_COMMA)"code":400}}
TestPackerBasic 2020-05-08T08:22:33+02:00 command.go:168: 1588918953,,ui,error,==> puppet: Error setting image metadata: Bad request with: [POST https://openstack_url/v3/de92f894b64f4d1c99803d225315ff62/volumes/5cf66e2d-e970-4a1e-be21-127959bf4f8a/action]%!(PACKER_COMMA) error message: {"badRequest":{"message":"There is no such action: os-set_image_metadata"%!(PACKER_COMMA)"code":400}}
```

### Packer version

From `packer version`
Versions tested: 1.5.1, 1.5.6

**Comment by raypettersen** [comment]
Looks to be related to #8429.

**Comment by raypettersen** [comment]
We've made progress. 1.4.2 does the job.

**Comment by SwampDragons** [comment]
Thanks for the report and the investigation. We'll try to fix this regression for the 1.6.0 release.

**Comment by SwampDragons** [comment]
Okay based on the fact that this last worked in 1.4.2, it was probably introduced by https://github.com/hashicorp/packer/pull/7792

**Comment by SwampDragons** [comment]
I wonder if this has to do with the version of Openstack being used; maybe the api call created by the gophercloud sdk call isn't valid for your version of Openstack. 

Probably the right workaround is to make the Packer build not fail even if the metadata isn't set.

**Comment by raypettersen** [comment]
@SwampDragons that was my assumption as well.
A warning instead of an error would be great.
