### ISSUE TITLE
vsphere-iso: option to remove CD-ROM drives before convert to template

### ISSUE THREAD

**Issue by bpfoley45** [hashicorp/packer#9193]
#### Feature Description

Add the ability to selectively remove CD-ROM drives from the image built before converting to template.

#### Use Case(s)

If building an image and installing software, every iso_path added is left as a CD-ROM device in the resultant image (in this case the OS is Windows, but almost any OS will detect available hardware).

Ideally I only need a single optical drive when complete and would like the ability to selectively remove any iso_path I have added.

**Comment by jhawk28** [comment]
are you asking for a way to control the number of cd rom drives are left? It is currently an all or nothing. I think this is a duplicate of #9117

**Comment by sylviamoss** [comment]
I agree with @jhawk28! I will mark it as a duplicate and close this one for now.
@bpfoley45 Let me know if you think otherwise.
