### ISSUE TITLE
vsphere-iso: automatically upload ISOs listed in iso_paths to packer cache and mount

### ISSUE THREAD

**Issue by dustyhorizon** [hashicorp/packer#9194]
#### Feature Description

ISOs listed in iso_paths should ideally be uploaded by the builder to the same folder as packer_cache (same way how the base ISO is uploaded) and mounted for use as so the build can still be "self contained" instead of relying on other cli magicks

#### Use Case(s)

An alternate way to mount cloud-config / preseed files using CDRoms instead of floppies (which are slowly seeing reduced support i.e. Ubuntu does not automount floppies at /media for unattended installation anymore ...)

**EDIT**: I was thinking that this particular feature could work similarly to the existing floppy_* features where we can specify a number of files and packer will generate and mount the generated ISO as a CD and then delete after the build ends

**Comment by orcutt989** [comment]
I like this. Could we do this to an ISO that's located on a datastore? Then could we check the SHA via SSH or some other method instead of having to download the file even if it exists where we need it?

**Comment by dustyhorizon** [comment]
> I like this. Could we do this to an ISO that's located on a datastore? Then could we check the SHA via SSH or some other method instead of having to download the file even if it exists where we need it?

Guessing it would be along the same lines as checking if the installer iso exists remotely else download from url then upload to datastore kind of thing so it should be possible. Gotta wait for the devs to comment on this though.
