### ISSUE TITLE
Azure Resource Manager Builder documentation has an incomplete sentence?

### ISSUE THREAD

**Issue by pvandervelde** [hashicorp/packer#9199]
In the [Azure Resource Manager Builder]() documentation it looks like there is an incomplete sentence.
It is in the Azure ARM builder specific options - Required section under the `custom_managed_image_resource_group_name` item, see image.

![image](https://user-images.githubusercontent.com/96201/81464300-7cdbc400-9214-11ea-9071-a23085ca58c1.png)

I assume the sentence should be:

    If this value is set, image_publisher, image_offer, image_sku, or image_version should not be set. If this value is set custom_managed_image_name must also be set.

I wanted to put a PR in but I couldn't find the correct document

![image](https://user-images.githubusercontent.com/96201/81464317-9da41980-9214-11ea-96b1-6f3818fe8d6c.png)

According to github it's not in the Packer repo :(

**Comment by nywilken** [comment]
Hi @pvandervelde thanks for catching this. Documentation for our builders are autogenerated by the config files. I you update the comment [here](https://github.com/hashicorp/packer/blob/f86170496187a4df255bc593bc465fc791ef7370/builder/azure/arm/config.go#L197) and run `make generate` after you should be able to open a PR with the fix. Thanks in advance for the fix.
