### ISSUE TITLE
Variable value content - backslash

### ISSUE THREAD

**Issue by nalberti** [hashicorp/packer#9206]
I am using packer (v1.5.6) and the integrated vsphere-iso builder 

I started getting a random error when trying to complete a build;

"Error happened while initializing task: SyntaxError: Unexpected token R in JSON at position 113."

I tracked it back to a password update where the new password contained a backslash (\)

Example:

{
 "vsphere_user":"user@domain.com",
 "winadmin_password":"normalPassword",
 "vsphere_password":"87g8g\9239JKB"
}

When I update it with an additional escape backslash like the below, all works fine, e.g;

"vsphere_password":"87g8g\\9239JKB"

Am I quoting the value wrong or am I wrong in thinking that the value should not be attempting to be parsed ?

**Comment by nywilken** [comment]
Hi @nalberti thanks for reaching out. Packer is not doing any additional parsing here. The error you are getting is because the unescaped backslash is not valid JSON so when Packer tries to read the config file it fails. Escaping the backslash like you observe will fix the issue.
