### ISSUE TITLE
Azure-arm post-processor for disk or vhd

### ISSUE THREAD

**Issue by mginster** [hashicorp/packer#9208]
Since azure-arm vhd support is going away eventually, will you be investigating a way to still get a managed disk or vhd output? Currently the only output is a managed image and going from that to a vhd is a few unnecessary steps.

Or can we just extend vhd to vhd support? :)

**Comment by nywilken** [comment]
Hi @mginster thanks for reaching out. This is a good question and one we need to think about. Including @paulmey onto the thread as well so that he is in the loop when we are ready to start looking into this request.
