### ISSUE TITLE
Vagrant post processor using artifice ova file

### ISSUE THREAD

**Issue by Roxyrob** [hashicorp/packer#9210]
It is possible to use an ova file created by virtualbo-ovf to vagrant post-processor using artifice post-processor ?

```
sample code:

  "builders":[
    {
       "name": "vagrant-box",
       "type": "null",
       "communicator": "none"
    }
  ],
  "post-processors": [
    [
      {
        "type": "artifice",
        "files": [ "sample.ova" ]
      },
      {
        "name": "vbox_ova_vagrant_post",
        "type": "vagrant",
        "output": "sample.box"
      }
    ]
  ]
```

I get this error:

> `"Post-processor` failed: Unknown artifact type, can't build box: packer.post-processor.artifice"

what's the difference from vagrant point of view if artifact come from virtualbox-ovf builder o from "null builder + artifice post-processor" ?

**Comment by azr** [comment]
Hey @Roxyrob, thanks for opening; have you considered chaining a [virtualbox-ovf-builder](https://www.packer.io/docs/builders/virtualbox-ovf.html) ( that does nothing ) to a vagrant pp ?

**Comment by azr** [comment]
Otherwise here's the full list of builders the vagrant pp can chain from:

https://github.com/hashicorp/packer/blob/dc31bad53934b564e3fde893cd77e283bc65617e/post-processor/vagrant/post-processor.go#L27-L42

**Comment by Roxyrob** [comment]
I am trying to run image building in stages (isolating stages: build, prov, post - see #9008) so I can reuse input from previous stages to test e.g. prov and post without running always previous stages (mostly build from iso that is very time consuming).

I am trying also to take advantage of ready built from iso image so with only one builder I can have 2 independent branches of provisioning -> post-processor (e.g. for ami image and for vagrant image).

First stage template start with only a irtualbox-iso builder (custom image  from OS iso). My above sample code is the third stage (post-processor for vagrant), with an ova file as input (there is also a post-processor using amazon-import - from same build stage). ova format is right as vagrant post-processor input and it is just ready to be used at this time. As workaround I can use another "needless" virtualbox-ovf taking the ova, Importing in Virtualbox, Starting VM, Doing nothing, Stopping VM, Exporting same ova... not so efficent for space and time consuming. With null builder and artifice it is possible to avoid lot of time/space (the other branch "amazon-import post-processor" works with same null builder / artifice code).

**Comment by SwampDragons** [comment]
Thanks for opening -- I agree this should be possible. I'll push up a PR for you to test before the end of the day.

**Comment by SwampDragons** [comment]
The build linked in the above PR should solve this for you: https://circleci.com/gh/hashicorp/packer/52000#artifacts/containers/0

**Comment by Roxyrob** [comment]
I got "* Post-processor failed: unexpected EOF". Tell me if you need more infos (logs).

**Comment by nywilken** [comment]
> I got "* Post-processor failed: unexpected EOF". Tell me if you need more infos (logs).

Hi @Roxyrob if you could provide a full debug log that would help us get a better idea of the exact issue your are seeing.

Using the sample configuration above I can reproduce the `* Post-processor failed: unexpected EOF` There is validation in place that validates that the post processor is working with one of the supported builders https://www.packer.io/docs/post-processors/vagrant/.

**Comment by Roxyrob** [comment]
Hi @nywilken ,
you are right as error seems "panic: bad provider name: artifice", but that is what is needed: input an ova artifact from artifice post-processor.
Below complete packer template and attached crash.log file.
crash log: [crash.log](https://github.com/hashicorp/packer/files/4650085/crash.log)

template.json
```
{
  "variables":{
    "env_type": "",
    "base_name": "windows2019min",
    "artifacts_path": "../../artifacts/",
    "build_path": "../../builds",
    "build_filename": "packer-{{user `base_name`}}-x86_64"
  },
  "builders":[
    {
       "name": "vagrant-box",
       "type": "null",
       "communicator": "none"
    }
  ],
  "post-processors": [
    [
      {
        "type": "artifice",
        "files": [ "{{user `build_path`}}/{{user `base_name`}}_vbox_ova_vagrant_prov/{{user `build_filename`}}-vbox_ova_vagrant_prov-{{user `env_type`}}.ova" ]
      },
      {
        "name": "vbox_ova_vagrant_post",
        "type": "vagrant",
        "keep_input_artifact": false,
        "output": "{{user `artifacts_path`}}/{{user `base_name`}}_{{.BuildName}}_{{.Provider}}_{{user `env_type`}}.box"
      }
    ]
  ]
}
```

**Comment by SwampDragons** [comment]
Thanks for the feedback @Roxyrob. I modified the PR. Binaries in https://circleci.com/gh/hashicorp/packer/52722#artifacts/containers/0 shouldn't have this issue. But you will have to set a new option,` "provider_override": "virtualbox"` on the vagrant post-processor definition to tell the post-processor which provider to use to create the vm.

**Comment by Roxyrob** [comment]
This version works for me. Great !

**Comment by SwampDragons** [comment]
Glad to hear it. Thanks for working through this with us.
