### ISSUE TITLE
ui error: Upload failed: Process exited with status 1

### ISSUE THREAD

**Issue by ssk199441** [hashicorp/packer#9216]
packer version 1.5.6

{

"variables": {
"aws_access_key": "{{env AWS_ACCESS_KEY_ID}}",
"aws_secret_key": "{{env AWS_SECRET_ACCESS_KEY}}"
},
"builders": [
{
"type": "amazon-ebs",
"access_key": "{{user aws_access_key}}",
"secret_key": "{{user aws_secret_key}}",
"region": "us-east-1",
"source_ami": "ami-fce3c696",
"instance_type": "t2.micro",
"ssh_username": "ubuntu",
"ami_name": "packer_AWS {{timestamp}}"
}
]

"provisioners": [
{
"type": "file",
"source": "../test",
"destination": "/tmp/test"
}
]
}

////////////////////////////////////////////////////////////////////////////////////////////////////
output log
2020/05/13 10:58:38 packer: 2020/05/13 10:58:38 [INFO] 530 bytes written for 'uploadData'
2020/05/13 10:58:38 packer: 2020/05/13 10:58:38 opening new ssh session
2020/05/13 10:58:38 [INFO] 530 bytes written for 'uploadData'
2020/05/13 10:58:38 packer: 2020/05/13 10:58:38 Starting remote scp process: scp -vt /tmp
2020/05/13 10:58:39 packer: 2020/05/13 10:58:39 Started SCP session, beginning transfers...
2020/05/13 10:58:39 packer: 2020/05/13 10:58:39 [DEBUG] scp: Uploading test.sh: perms=C0644 size=530
2020/05/13 10:58:39 packer: 2020/05/13 10:58:39 SCP session complete, closing stdin pipe.
2020/05/13 10:58:39 packer: 2020/05/13 10:58:39 Waiting for SSH session to complete.
2020/05/13 10:58:39 packer: 2020/05/13 10:58:39 non-zero exit status: 1
==> Upload failed: Process exited with status 1
2020/05/13 10:58:39 ui error: Upload failed: Process exited with status 1

when we try to upload the file by provisioner still getting same problems with the packer version 1.5.6

**Comment by azr** [comment]
Hey @ssk199441 ! Thanks for opening, this error you had is not very communicative !

So I opened https://github.com/hashicorp/packer/pull/9217 that makes it more verbose. Could you please try the same thing again with these [binaries](https://circleci.com/gh/hashicorp/packer/51120#artifacts/containers/0) and share the output log with us again ? Thanks !

**Comment by ssk199441** [comment]
Can you guide me how to proceed further

**Comment by ssk199441** [comment]
I am using Linux machine

**Comment by sylviamoss** [comment]
```
WARNING: Your password has expired.
```
Have you tried addressing this?

**Comment by ssk199441** [comment]
I raised an issue regarding this, can you give me some time, will give you an update

**Comment by ssk199441** [comment]
Thanks, guys, it's all set and working fine now, 

How long I can use these binaries?

**Comment by SwampDragons** [comment]
Circle CI doesn't guarantee how long they'll leave the binaries up but we've got nightlies that come out every week now, and anecdotally the binaries in circle last longer than that.
