### ISSUE TITLE
Build packer from source

### ISSUE THREAD

**Issue by Sprbb** [hashicorp/packer#9222]
#### Overview of the Issue
Error when getting the software

#### Reproduction Steps
sudo go get github.com/hashicorp/packer

### Packer version
From `packer version`
1.5.6

### Operating system and Environment details
Linux bas-ThinkPad-X220-Tablet 4.15.0-96-generic #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Log Fragments and crash.log files
Include appropriate log fragments. If the log is longer than a few dozen lines,
please include the URL to the [gist](https://gist.github.com/) of the log or
use the [Github detailed format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d) instead of posting it directly in the issue.
Set the env var `PACKER_LOG=1` for maximum log detail.
```
# github.com/hashicorp/packer/vendor/github.com/hashicorp/go-multierror
go/src/github.com/hashicorp/packer/vendor/github.com/hashicorp/go-multierror/multierror.go:112:16: error: reference to undefined identifier 'errors.As'
  return errors.As(e[0], target)
                ^
go/src/github.com/hashicorp/packer/vendor/github.com/hashicorp/go-multierror/multierror.go:117:16: error: reference to undefined identifier 'errors.Is'
  return errors.Is(e[0], target)
                ^
# github.com/hashicorp/packer/vendor/github.com/hashicorp/go-getter/v2
go/src/github.com/hashicorp/packer/vendor/github.com/hashicorp/go-getter/v2/get_http.go:90:28: error: reference to undefined field or method 'Clone'
   httpReq.Header = g.Header.Clone()
```

**Comment by SwampDragons** [comment]
I booted a fresh install of ubuntu, installed golang, and called `go get github.com/hashicorp/packer`. I can't reproduce this issue. Can you provide some more detail about what command you're running to get that output?

**Comment by Sprbb** [comment]
As a workaround I used the binary.

**Comment by Sprbb** [comment]
Not in scope for me.
