### ISSUE TITLE
vmware-vmx builder ova import functionality

### ISSUE THREAD

**Issue by orcutt989** [hashicorp/packer#9228]
#### Feature Description

Take an OVA artifact form vmware-iso or from anywhere else and use it to provision a machine with the vmware-vmx builder.

```json
"source_path": "vmx or ova file path"
```

#### Use Case(s)

OVA is smaller than VMX format and would take up less space on the datastore. Vcenter/esx both have functionality to import OVA let's extend this to Packer.

**Comment by azr** [comment]
Hello @orcutt989, Packer can do this already and I think https://www.packer.io/docs/builders/virtualbox-ovf.html is what you are looking for.

Don't hesitate to ask the [community](https://www.packer.io/community/) for help ! Cheers !

**Comment by orcutt989** [comment]
@azr That is for VirtualBox not VMWare...

**Comment by azr** [comment]
Ah wait ! You asked for vmware !

**Comment by orcutt989** [comment]
Thanks for reopening :-)

**Comment by azr** [comment]
Sorry again, then my answer is a bit different ! I think this is a good idea and I am unsure if we will have time to work on this any soon but it sounds like really nice to have. As usual PRs welcome 🙂  !

**Comment by arizvisa** [comment]
@orcutt989: In the meantime, `*.ova` files are just tarballs w/ the disks compressed. You can extract the files and then use the `vsphere-vmx` builder as-is. I'm currently wrapping all of my builds in a Makefile and then using `vmware-vmx` to modify templates which should be pretty similar to most workflows.

**Comment by orcutt989** [comment]
That's a great suggestion. However it would be great if Packer could handle that. Right now I'm just using vmx artifacts and passing those around. Thanks to everyone for the help.
