### ISSUE TITLE
Provisioner Salt-masterless breaks on build (HCL2)

### ISSUE THREAD

**Issue by mpearson117** [hashicorp/packer#9233]
#### Overview of the Issue

Running a packer build using HCL2 breaks while using the salt-masterless provisioner

#### Reproduction Steps

`packer build ./`

### Packer version

Packer version: 1.5.6 [go1.14.2 linux amd64]

### Simplified Packer Buildfile
```hcl
build {
  sources = [
    "source.amazon-ebs.centos"
  ]

  provisioner "salt-masterless" {
    local_state_tree = "../scripts/salt"
    skip_bootstrap   = "true"
  }
}
```
### Operating system and Environment details

Ubuntu

### Log Fragments and crash.log files

Error: Failed preparing provisioner-block "salt-masterless" ""
  on build.pkr.hcl line 65, in build:

  65:   provisioner "salt-masterless" {
  on build.pkr.hcl line 65, in build:

  65:   provisioner "salt-masterless" {
1 error occurred:

        * unknown configuration key: "cmd_args"; raws is []interface
1 error occurred:
{}{map[string]interface {}{"packer_build_name":"centos",
        * unknown configuration key: "cmd_args"; raws is []interface
"packer_builder_type":"amazon-ebs"}, map[string]interface
{}{map[string]interface {}{"packer_build_name":"centos",
{}{"bootstrap_args":interface {}(nil), "cmd_args":interface {}(nil),
"custom_state":interface {}(nil), "disable_sudo":interface {}(nil),
"packer_builder_type":"amazon-ebs"}, map[string]interface
"grains_file":interface {}(nil), "guest_os_type":interface {}(nil),
"local_pillar_roots":interface {}(nil), "local_state_tree":"../scripts/salt",
{}{"bootstrap_args":interface {}(nil), "cmd_args":interface {}(nil),
"log_level":interface {}(nil), "minion_config":interface {}(nil),
"custom_state":interface {}(nil), "disable_sudo":interface {}(nil),
"no_exit_on_failure":interface {}(nil), "packer_build_name":interface {}(nil),
"packer_builder_type":interface {}(nil), "packer_debug":interface {}(nil),
"grains_file":interface {}(nil), "guest_os_type":interface {}(nil),
"packer_force":interface {}(nil), "packer_on_error":interface {}(nil),
"local_pillar_roots":interface {}(nil), "local_state_tree":"../scripts/salt",
"packer_sensitive_variables":interface {}(nil),
"packer_user_variables":interface {}(nil), "remote_pillar_roots":interface
"log_level":interface {}(nil), "minion_config":interface {}(nil),
{}(nil), "remote_state_tree":interface {}(nil), "salt_bin_dir":interface
"no_exit_on_failure":interface {}(nil), "packer_build_name":interface {}(nil),
{}(nil), "salt_call_args":interface {}(nil), "skip_bootstrap":true,
"packer_builder_type":interface {}(nil), "packer_debug":interface {}(nil),
"temp_config_dir":interface {}(nil)}}
"packer_force":interface {}(nil), "packer_on_error":interface {}(nil),

"packer_sensitive_variables":interface {}(nil),
 and ctx data is map[interface {}]interface {}{"ConnType":"Build_Type. To set
"packer_user_variables":interface {}(nil), "remote_pillar_roots":interface
this dynamically in the Packer template, you must use the `build` function",
{}(nil), "remote_state_tree":interface {}(nil), "salt_bin_dir":interface
"Host":"Build_Host. To set this dynamically in the Packer template, you must use
{}(nil), "salt_call_args":interface {}(nil), "skip_bootstrap":true,
the `build` function", "ID":"Build_ID. To set this dynamically in the Packer
"temp_config_dir":interface {}(nil)}}
template, you must use the `build` function",
"PackerHTTPAddr":"Build_PackerHTTPAddr. To set this dynamically in the Packer

**Comment by azr** [comment]
Hey @mpearson117 ! Thanks for opening ! I opened https://github.com/hashicorp/packer/pull/9290 that fixes this.
