### ISSUE TITLE
This host does not support "Intel EPT" hardware assisted MMU virtualization.

### ISSUE THREAD

**Issue by mohanr** [hashicorp/packer#9242]
#### Overview of the Issue
I have VirtualBox and a guest Ubuntu OS. Inside that I use packer and VMWare Workstation to build a CentOS VM.
I think this could be a problem because there is already a  virtualized environment. I may have identified this and the `vmware.log` shows the problem..

Is this even possible to do ? I do set `"monitor.allowLegacyCPU": "true"`.
If this is not possible due to some nested virtualization requirement I can use the Windows subsystem for Linux but again that could pose the same problem. 
Is packer's legacy CPU switch the right one or not ?
### Packer version

From `packer version`

### Simplified Packer Buildfile

```
{
  "variables": {
    "vm_name": "centos-7.1-vmware",
    "iso_url": "{{env `ISO_URL`}}",
    "iso_sha256": "27bd866242ee058b7a5754e83d8ee8403e216b93d130d800852a96f41c34d86a",
    "vm_host": "{{ user `vm_host` }}",
    "vm_user": "{{ user `vm_user` }}",
    "vm_pass": "{{ env `vm_pass` }}",
    "vm_dc":   "{{ user `vm_dc` }}",
    "vm_cluster": "{{user `vm_cluster`}}",
    "vm_datastore": "{{user `vm_datastore`}}",
    "vm_folder": "{{user `vm_folder`}}",
    "vm_network": "{{user `vm_network`}}"
  },
  "builders": [
    {
      "headless": false,
      "type": "vmware-iso",
      "boot_command": [
        "<tab> text ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/ks.cfg<enter><wait>"
      ],
      "boot_wait": "10s",
      "disk_size": 8192,
      "guest_os_type": "centos-64",
      "http_directory": "http",
      "iso_url": "{{user `iso_url`}}",
      "iso_checksum_type": "sha256",
      "iso_checksum": "{{user `iso_sha256`}}",
      "ssh_username": "vagrant",
      "ssh_private_key_file": "vagrant_rsa_key",
      "ssh_port": 22,
      "ssh_wait_timeout": "10000s",
      "shutdown_command": "echo '/sbin/halt -h -p' > /tmp/shutdown.sh; echo 'vagrant'|sudo -S sh '/tmp/shutdown.sh'",
      "tools_upload_flavor": "",
      "tools_upload_path": "/tmp/vmware_tools_{{.Flavor}}.iso",
      "vmx_data": {
        "memsize": "1024",
        "numvcpus": "1",
        "cpuid.coresPerSocket": "1",
        "monitor.allowLegacyCPU": "true"
      }
    }
  ],
  "provisioners": [
    {
      "type": "shell",
      "execute_command": "echo 'vagrant'|sudo -S sh '{{.Path}}'",
      "override": {
        "vmware-iso": {
          "scripts": [
            "scripts/base.sh",
            "scripts/vmware.sh",
            "scripts/hgfs.sh",
            "scripts/cleanup.sh",
            "scripts/zerodisk.sh"
          ]
        }
      }
    }
  ],
  "post-processors": [
    {
      "type": "vagrant",
      "override": {
        "vmware": {
          "output": "centos-7.1-x64-vmware.box"
        }
      }
    }
  ]
}
```

### Operating system and Environment details

Host OS is Windows 10 Pro and VirtualBox and a guest Ubuntu OS

## vmware.log
2020-05-16T10:15:54.382+05:30| vmx| I125: ToolsISO: Updated cached value for imageName to 'linux.iso'.
2020-05-16T10:15:54.382+05:30| vmx| I125: ToolsISO: Selected Tools ISO 'linux.iso' for 'centos-64' guest.
2020-05-16T10:15:54.390+05:30| vmx| I125: Vix: [mainDispatch.c:4215]: VMAutomation_ReportPowerOpFinished: statevar=1, newAppState=1873, success=1 additionalError=0
2020-05-16T10:15:54.405+05:30| vmx| I125: Module 'CPUIDEarly' power on failed.
2020-05-16T10:15:54.405+05:30| vmx| I125: VMX_PowerOn: ModuleTable_PowerOn = 0
2020-05-16T10:15:54.407+05:30| vmx| I125: Vix: [mainDispatch.c:4215]: VMAutomation_ReportPowerOpFinished: statevar=1, newAppState=1873, success=1 additionalError=0
2020-05-16T10:15:54.414+05:30| vmx| I125: 
2020-05-16T10:15:54.414+05:30| vmx| I125+ Power on failure messages: This host does not support Intel VT-x.
2020-05-16T10:15:54.414+05:30| vmx| I125+ This host does not support "Intel EPT" hardware assisted MMU virtualization.
2020-05-16T10:15:54.414+05:30| vmx| I125+ Module 'CPUIDEarly' power on failed.
2020-05-16T10:15:54.414+05:30| vmx| I125+ Failed to start the virtual machine.
2020-05-16T10:15:54.414+05:30| vmx| I125+ 
2020-05-16T10:15:54.415+05:30| vmx| I125: Vix: [mainDispatch.c:4215]: VMAutomation_ReportPowerOpFinished: statevar=0, newAppState=1870, success=1 additionalError=0
2020-05-16T10:15:54.415+05:30| vmx| I125: Transitioned vmx/execState/val to poweredOff
2020-05-16T10:15:54.421+05:30| vmx| I125: Vix: [mainDispatch.c:4215]: VMAutomation_ReportPowerOpFinished: statevar=0, newAppState=1870, success=0 additionalError=0
2020-05-16T10:15:54.421+05:30| vmx| I125: Vix: [mainDispatch.c:4253]: Error VIX_E_FAIL in VMAutomation_ReportPowerOpFinished(): Unknown error

**Comment by nywilken** [comment]
Hi @mohanr thanks for reaching out. I'm not entirely sure if this is more of a VMWare configuration issue then it is a Packer thing. But this issue https://github.com/hashicorp/packer/issues/5754 may help in answering your question around `"monitor.allowLegacyCPU"`.

Have you tried reaching out to the community forums? 

For help with this kind of initial configuration, the mailing list or community forum are generally more useful. Issues opened here on the Packer issue tracker are only viewed by a small handful of developers who work on the tool, and we don't always have the most depth or experience when it comes to custom issues with particular build configurations.

**Comment by mohanr** [comment]
I have asked the Google groups.

**Comment by ei-ke** [comment]
I'm using VMware Workstation on Arch Linux and noticed that the ``Module 'CPUIDEarly' power on failed`` error happens after a warm boot or suspend. Took me many weeks to figure out when exactly that error strikes. Maybe this is also happening in your case.

**Comment by mohanr** [comment]
`I have VirtualBox and a guest Ubuntu OS. Inside that I use packer and VMWare Workstation to build a CentOS VM.`
Just clarifying. I have a Windows host and on that I have VirtualBox and a guest Ubuntu OS. Inside that  Ubuntu OS I use packer and VMWare Workstation to build a CentOS VM. So there is a host and VirtualBox and Ubuntu and inside that I have VMWare Workstation( CentOS VM ). 
This layering could be an issue. I wonder.

**Comment by knoxknot** [comment]
I will suggest you install the packer directly on windows machine - OS or WSL. Intialize the "vmware/esxi" vagrant box and run your desired CentOS VM there.
Samuel Nwoye"There is only one good knowledge; one evil ignorance." 

    On Sunday, June 7, 2020, 03:59:14 AM GMT+1, Mohan Radhakrishnan <notifications@github.com> wrote:  
 
 


I have VirtualBox and a guest Ubuntu OS. Inside that I use packer and VMWare Workstation to build a CentOS VM.
Just clarifying. I have a Windows host and on that I have VirtualBox and a guest Ubuntu OS. Inside that Ubuntu OS I use packer and VMWare Workstation to build a CentOS VM. So there is a host and VirtualBox and Ubuntu and inside that I have VMWare Workstation( CentOS VM ).
This layering could be an issue. I wonder.
