### ISSUE TITLE
Latest tag in github release?

### ISSUE THREAD

**Issue by an-sush** [hashicorp/packer#9244]
Tag latest release

#### Feature Description

The hashicorp [checkpoint api](https://checkpoint-api.hashicorp.com/v1/check/packer) and latest [release in github](https://api.github.com/repos/hashicorp/packer/releases/latest) are not pointing to same version. This is causing confusion on which one is stable and to be considered.
#### Use Case(s)

Downloading latest packer based on github [latest tag](https://developer.github.com/v3/repos/releases/#get-the-latest-release) seems to be the industry standard but this doesn't seem to have the same version as the hashicorp's checkpoint api

**Comment by nywilken** [comment]
@an-sush thanks for bubbling this up. The latest tag release has been updated an now points to v1.5.6. We are currently working on improving the release process so for future releases things should be in-sync. Thanks again for the help here.
