### ISSUE TITLE
Set filename for export with virtualbox-vm

### ISSUE THREAD

**Issue by kotofos** [hashicorp/packer#9247]
#### Feature Description
Separate option to set output filename for the ova file.

#### Use Case(s)

I have an existing VM in virtual box (for example 'builder-vm'), and want to use it to build ova (for example 'exported-vm.ova'). "virtualbox-vm" builder has "vm_name" option to specify a name of existing VM. But it will also export ova with the same name as the VM, instead of desired.

```  
"builders": [{
  "type": "virtualbox-vm",
  "vm_name": "base-vm",
  "output_directory": "output-ova",
  "format": "ova",
  ...
```

Or, another use case

1. Build from ova, use vm_name (for example 'builder_vm') to set a displayed name for VM
2. Export to ova, but with a different name than vm_name (for example 'output.ova')

There is --output in virtualbox for that, but it is used by packer itself and can not be overridden.
`Syntax error: You can only specify --output once`
```
     "export_opts":
      [
          "--output", "exported-vm.ova",
      ],
```

**Comment by sylviamoss** [comment]
Hello there! It seems that this was already implemented here https://github.com/hashicorp/packer/pull/9174 and it will go out in the next release. Until then, you can use our [nightly](https://github.com/hashicorp/packer/releases/tag/nightly) release binaries which contains already these changes.
With that you can simply add `"output_filename" : "exported-vm.ova"` to your template.
