### ISSUE TITLE
vsphere-iso parameters to set tools.syncTime and tools.upgrade.policy

### ISSUE THREAD

**Issue by mscheinholtz** [hashicorp/packer#9248]
Please search the existing issues for relevant feature requests, and use the
reaction feature
(https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
to add upvotes to pre-existing requests.

#### Feature Description

In the previous vmware-iso builder the default VMX enabled [tools.syncTime](https://github.com/hashicorp/packer/blob/20541a7eda085aa5cf35bfed5069592ca49d106e/builder/vmware/step_create_vmx.go#L147) and [tools.upgrade.policy](https://github.com/hashicorp/packer/blob/20541a7eda085aa5cf35bfed5069592ca49d106e/builder/vmware/step_create_vmx.go#L148). This request is to make these two parameters configurable.

#### Use Case(s)
The use-cases for these parameters is to force vmware tools to automatically update on reboot and to synch the time with the host.

**Comment by SwampDragons** [comment]
Thanks for opening. As a workaround, you can set VMX values directly via the [configuration_parameters](https://www.packer.io/docs/builders/vsphere-iso.html#configuration_parameters) option
