### ISSUE TITLE
Sharing Packer AMIs in AWS accounts

### ISSUE THREAD

**Issue by mkadali99** [hashicorp/packer#9253]
Hi,
We have a packer project where we build our AMIs using packer and are sharing this among some of our accounts using the directive "ami_users". But as we create new accounts and want to share these AMIs, we are adding the  new account numbers to "ami_users" and running the packer build command again. This is building our AMIs again, which we don't want. Is there any way we can share the AMIs to new accounts, without having to rebuild?

**Comment by ad-m** [comment]
Have you tried use AWS Console and update ami_users. See also https://github.com/hashicorp/packer/blob/da4a5224be55629da2c8dded9b606011afc01eeb/builder/amazon/chroot/builder.go#L448-L457 and https://github.com/hashicorp/packer/blob/9ec8b67392a8e458d802d8245ddb1fc9efea7b51/builder/amazon/common/step_modify_ami_attributes.go#L113-L118 .

**Comment by SwampDragons** [comment]
My recommendation is to do this outside of Packer: Write a script that uses AWS directly to do this. You can find detailed instructions on using the CLI tool or the AWS console here: 

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/sharingamis-explicit.html

The only current way to make this packer-specific would be to create a null builder that uses the shell-local post-processor to add the ami names using the above cli calls, but that would be more bulky and complicated than just writing the shell script, and you'd have to write that shell script anyway for the shell-local post-processor to work.

If you really wanted to go all in on Packer, you could write a [custom post-processor](https://www.packer.io/docs/extending/custom-post-processors/) to update the ami users, but that's not something the core packer team would prioritize.
