### ISSUE TITLE
package_include in vagrant builder does not seem to work as expected

### ISSUE THREAD

**Issue by MichaelKunze** [hashicorp/packer#9256]
#### Overview of the Issue

As soon as you add the option `package_include` to the vagrant builder snippet from the doc the package phase seems to fail. There is no error tho but it only takes seconds and there is no box.

#### Reproduction Steps

Create a file `template.json` (As seen on https://www.packer.io/docs/builders/vagrant):
```
{
  "builders": [
    {
      "communicator": "ssh",
      "source_path": "hashicorp/precise64",
      "provider": "virtualbox",
      "type": "vagrant"
    }
  ]
}
```

Execute:
```
packer build -timestamp-ui -force template.json
```

Leads to:
```
[...]
2020-05-19T13:09:57+02:00: ==> vagrant: Connected to SSH!
2020-05-19T13:09:57+02:00: ==> vagrant: Packaging box...
2020-05-19T13:11:20+02:00: ==> vagrant: destroying Vagrant box...
2020-05-19T13:11:28+02:00: Build 'vagrant' finished.
```
Note! It takes almost 2 minutes to package it.

Then put a `test` file in the folder:
```
$ echo "1" > test 
$ ls -1
template.json
test
```

Add `package_include` to `template.json`. Remember it's an array!
```
{
  "builders": [
    {
      "communicator": "ssh",
      "source_path": "hashicorp/precise64",
      "provider": "virtualbox",
      "type": "vagrant",
      "package_include": ["test"]
    }
  ]
}
```

And execute:
```
packer build -timestamp-ui -force template.json
```

Leads to:
```
[...]
2020-05-19T13:12:59+02:00: ==> vagrant: Connected to SSH!
2020-05-19T13:12:59+02:00: ==> vagrant: Packaging box...
2020-05-19T13:13:02+02:00: ==> vagrant: destroying Vagrant box...
2020-05-19T13:13:11+02:00: Build 'vagrant' finished.
```
Note! It took only 3 seconds to "package". No error is shown.

But no box is created either:
```
$ ls -1 output-vagrant/
Vagrantfile
```

### Packer version

Packer v1.5.6

### Simplified Packer Buildfile

See above

### Operating system and Environment details

```
$ cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
```

### Further findings

After digging around i found out that the path is relative to `output-vagrant` folder
So providing
´´´
   "package_include": ["../test"]
´´´

Indeed works, but is inconsistent with output_vagrantfile!

**Comment by SwampDragons** [comment]
Thanks for opening this. I've opened PR #9260 to fix this, and you can find binaries that contain the patch here: https://circleci.com/gh/hashicorp/packer/52790#artifacts/containers/0
