### ISSUE TITLE
Ubuntu 20.04, VMWare WS and disk_size

### ISSUE THREAD

**Issue by SteveClement** [hashicorp/packer#9268]
Dear

#### Overview of the Issue

I run vmware-iso with VMWare Workstation 15.5 and it seems the 'disk_size' parameter is not considered.

Whatever I set it always creates a 3.9GB root (/) disk.

#### Reproduction Steps

Run packer with ubuntu 20.04

### Packer version

Packer v1.5.6 (same results on nightly)

### Simplified Packer Buildfile

[buildfile.json](https://gist.github.com/SteveClement/2f53ca0dee596b804f3bba26f475bfa2)

### Operating system and Environment details

Debian 10

Example repo: https://github.com/SteveClement/packer-ubuntu-2004

Created [vmx](https://gist.github.com/SteveClement/f7e36b4199a2374634f3f7e94640b632)

Not setting 'disk_size' ([40GB by default according to docs](https://www.packer.io/docs/builders/vmware-iso.html#disk_size)) seems to be the same issue.

3.9GB is pretty close to 40GB though ;)

It might be an "cloud-init" issue:

https://cloudinit.readthedocs.io/en/latest/topics/examples.html

Looking at the examples it seems there are tuneables over there too.
(Search for size and layout ...)

**Comment by SwampDragons** [comment]
Hi, thanks for opening this issue. 

Can you please set the environment variable `PACKER_LOG=1` and rerun your build, and share the output logs? I'm particularly interested in seeing the contents of this logline to make sure that our code delivering your disk size is correct: https://github.com/hashicorp/packer/blob/master/builder/vmware/iso/step_create_disk.go#L50

Just to make sure I fully understand what to look for when reproducing the issue, where is that 3.9 GB size coming from? Are you checking the disk size inside the vm using something like `df -h` or are you looking at the final created disk on the host machine?

**Comment by SteveClement** [comment]
That part seems to work fine:

```
2020/05/22 13:19:07 packer-builder-vmware-iso plugin: [INFO] Creating disk with Path: output-ubuntu-2004/disk.vmdk and Size: 25000M
2020/05/22 13:19:07 packer-builder-vmware-iso plugin: Executing: /bin/vmware-vdiskmanager -c -s 25000M -a lsilogic -t 1 output-ubuntu-2004/disk.vmdk
2020/05/22 13:19:07 packer-builder-vmware-iso plugin: stdout: Creating disk 'output-ubuntu-2004/disk.vmdk'
2020/05/22 13:19:07 packer-builder-vmware-iso plugin: Virtual disk creation successful.
```

In the GUI you also see that it created a 25GB Disk, thus is is the 'auto-install' magic that does not use the entire disk.

And yes, my 3.9GB come from a simple 'df -h'

Thus I guess not really packer related...

**Comment by SteveClement** [comment]
It is an issue with LVM, it only uses 4GB during the autoinstall.
Thus it is not packer related.

```
$ lsblk
NAME                      MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
loop0                       7:0    0   55M  1 loop /snap/core18/1705
loop1                       7:1    0   69M  1 loop /snap/lxd/14804
loop2                       7:2    0 27.1M  1 loop /snap/snapd/7264
sda                         8:0    0 24.4G  0 disk 
├─sda1                      8:1    0    1M  0 part 
├─sda2                      8:2    0    1G  0 part /boot
└─sda3                      8:3    0 23.4G  0 part 
  └─ubuntu--vg-ubuntu--lv 253:0    0    4G  0 lvm  /
sr0                        11:0    1 1024M  0 rom  
```
