### ISSUE TITLE
amazon-ebs filters behavior conflicts with HCL documentation

### ISSUE THREAD

**Issue by mschuchard** [hashicorp/packer#9270]
#### Overview of the Issue

The [documentation](https://www.packer.io/guides/hcl/from-json-v1/) for filters in the amazon-ebs builder conflicts with actual behavior.

#### Reproduction Steps

`packer build`

### Packer version

1.5.6

### Simplified Packer Buildfile

According to the documentation, we can do:

```hcl
source_ami_filter {
  filters {...}
}
```

but this throws:

> Error: Unsupported block type
...
Blocks of type "filters" are not expected here. Did you mean "filter"?

After converting to `filter`, following the documentation to do something like:

```hcl
security_group_filter {
  filter {
    group-name = "name"
  }
}
```

throws:

>Error: Unsupported argument
...
An argument named "group-name" is not expected here.

With some guesswork and staring at #9078, I managed to fix it via:

```hcl
security_group_filter {
  filter {
    name = "group-name"
    value = "name"
  }
}
```

and similarly:

```hcl
source_ami_filter {
  filter {
    key   = "virtualization-type"
    value = "hvm"
  }
}
```

I was also able to guess my way to converting tags to:

```hcl
tag {
  name = "Name"
  value = "name"
}
```

and notice that is consistent with #8684. However, since this nomenclature/syntax is different than before and from the `filter` nomenclature/syntax, and e.g. `security_group_filter` is different than `source_ami_filter`, it would be super helpful to have this also documented.

Update:
Actually, I see now that in #8684 the conversation digressed from tagging in filters to normal tagging, and that tags in filters should be:

```hcl
filter {
  name = "tag:Name"
  value = "name"
}
```

thanks to #8889.

Could the documentation be updated for all of this and any other inconsistencies please and thank you?

### Operating system and Environment details

Ubuntu 18.04

### Log Fragments and crash.log files

N/A

**Comment by SwampDragons** [comment]
Thanks for opening. We'll get the documentation fixed up.
