### ISSUE TITLE
run_volume_tag block missing from amazon-ebs builder

### ISSUE THREAD

**Issue by mschuchard** [hashicorp/packer#9280]
#### Overview of the Issue

The `run_volume_tag` block is currently missing from the `amazon-ebs` builder. `run_volume_tags` is still valid. All other tag blocks (including `run_tag`) that I have tried seem to be functioning. Was this missing from #8889?

#### Reproduction Steps

`packer build`

### Packer version

1.5.6

### Simplified Packer Buildfile

```hcl
run_volume_tag {
  key   = "Name"
  value = "name"
}
```
### Operating system and Environment details

Ubuntu 18.04

### Log Fragments and crash.log files

> Error: Unsupported block type
...
Blocks of type "run_volume_tag" are not expected here.

**Comment by azr** [comment]
Hey @mschuchard Thanks for opening, I'll do that now !

**Comment by azr** [comment]
Hey @mschuchard, #9457 should fix this !
