### ISSUE TITLE
Update docs examples for HCL

### ISSUE THREAD

**Issue by ad-m** [hashicorp/packer#9282]
#### Feature Description

I notice that Packer has a significant amount of documentation currently based on JSON syntax. I think we need to review the documentation and update examples.

For example at page:

https://www.packer.io/docs/post-processors/shell-local/
https://www.packer.io/docs/post-processors/docker-import/
https://www.packer.io/docs/post-processors/vagrant/

It is to be considered whether the examples appearing in the documentation we want to have presented in two formats (for example using tabs) or only in the new format.

I also hope that reviewing all examples in the documentation for the new HCL syntax can provide helpful input for HCL design.

I notice that the scope of the current issue is wide and probably needs to be resolved in several pull requests, but before starting work, several decisions need to be made about the direction of change. Appropriate design and division of the problem will allow it to be labeled "good first issue" and involve community.

#### Use Case(s)

Flattening the learning curve for the new HCL based Packer syntax.

**Comment by ad-m** [comment]
@SwampDragons, could you add label:

- docs
- hcl

, please?

**Comment by ad-m** [comment]
@nywilken , thank you!

**Comment by nywilken** [comment]
You got it @ad-m. Thanks for opening up this issue.

**Comment by SwampDragons** [comment]
The docs specifically referenced in this issue have been updated. I'm going to create a new set of issues for docs for individual plugins to make this more trackable.
