### ISSUE TITLE
min_packer_version JSON key not supported as argument in HCL syntax

### ISSUE THREAD

**Issue by mschuchard** [hashicorp/packer#9284]
#### Overview of the Issue

The `min_packer_version` key could specify the minimum Packer version for a template in JSON. This does not seem to be currently supported in HCL syntax. Since this seems more like functional metadata, I am not sure where eventually it should ideally be specified.

#### Reproduction Steps

`packer build`

### Packer version

1.5.6

### Simplified Packer Buildfile

```hcl
source "source" "name" {
  min_packer_version = "1.5.6"
}
```
or
```hcl
build {
  min_packer_version = "1.5.6"
}
```

### Operating system and Environment details

Ubuntu 18.04

### Log Fragments and crash.log files

> Error: Unsupported argument
...
An argument named "min_packer_version" is not expected here.

**Comment by azr** [comment]
Hey @mschuchard ! Thanks for opening ! I'll make sure to add this to the TODO 🙂. After some thinking I'm thinking of allowing to set this per hcl file at the top-level, for example:

```hcl
min_packer_version = "1.5.6"
build {
  # ....
}
```

We would simply check this value if it's set and error/not read the file in case.

**Comment by azr** [comment]
Update here, I think this should be in a packer block:

```hcl
packer {
  version = "" // < some selector
}
```

**Comment by mschuchard** [comment]
Thank you for expanding upon the original ask, and including the semantic version operator `~>` in the expansion.
