### ISSUE TITLE
No such file or directory : while running hashicorp packer docker image through octopus deploy

### ISSUE THREAD

**Issue by pra89j** [hashicorp/packer#9288]
I am using Hashicorp packer official docker image to validate and create a custom AMI. Below is the command I am using to validate the template2.json file which has the code to create custom AMI. I am using octopus deploy worker pool to execute this command.

docker run -i ee26c209af37 validate template2.json

but it's not able to detect the template2.json file and is giving "No such file or directory". Can you please advise if you guys have faced this kind of scenario.I have tried giving full path before template2.json also but same error.

**Comment by sylviamoss** [comment]
Hey there! Thanks for opening the issue :) 

Is the template2.json inside the container? If it isn't then Packer won't be able to find it. I think you can either copy the file to the container or you can mount a volume in the docker command like: 

```
docker run -it \
    --mount type=bind,source=/absolute/path/to/template2.json,target=/mnt/template2.json \
    ee26c209af37 validate /mnt/template2.json
```

Let me know if one of the solutions works for you!

**Comment by rkdubey720** [comment]
Hi, I am trying to create packer image for azure.

I am using "ansible-local" provisioner.

But getting bellow error logs.

==> azure-arm: Provisioning with Ansible...
    azure-arm: Uploading Playbook directory to Ansible staging directory...
    azure-arm: Creating directory: /tmp/packer-provisioner-ansible-local/5ecbee06-92ab-1e33-9a79-6c02a3f74b30
==> azure-arm: Could not chdir to home directory /home/packer: No such file or directory
==> azure-arm: Provisioning step had errors: Running the cleanup provisioner, if present...
==> azure-arm: Removing the created Deployment object: 'pkrdp244ieki0qn'
==> azure-arm:
==> azure-arm: Cleanup requested, deleting resource group ...
==> azure-arm: Resource group has been deleted.
Build 'azure-arm' errored: Error uploading playbook_dir directory: Process exited with status 255

**Comment by pra89j** [comment]
@sylviamoss sylviamoss
![err](https://user-images.githubusercontent.com/65868732/82870881-4c9f5f80-9f4e-11ea-825b-6a5b09fe14d1.jpg)
I have tried that command also but getting permission denied error. Check the attacked error photo.

![err](https://user-images.githubusercontent.com/65868732/82870800-2974b000-9f4e-11ea-83b1-d7763cc8b5df.jpg)

**Comment by sylviamoss** [comment]
@rkdubey720 you reports doesn't seem related to this issue. 🤔 If it is, give us more information about it, and if it's not, report it as a new issue, please.

**Comment by sylviamoss** [comment]
@pra89j I was thinking, if octopus works like CircleCI then it won't be possible to mount a volume. I don't know how Octopus works here, I might be wrong. Can you try copying the template to the packer conainer and use it from there, without using volumes? 
I almost sure this is some config or behavior of Octopus.

**Comment by pra89j** [comment]
@sylviamoss 
I have tried copying the file to container using docker cp command but it says no such container path.

![cp](https://user-images.githubusercontent.com/65868732/83389376-c41d3500-a40d-11ea-8a73-086da49165bf.jpg)
![err](https://user-images.githubusercontent.com/65868732/83389408-d1d2ba80-a40d-11ea-9813-688a6abb5772.jpg)

**Comment by pra89j** [comment]
@sylviamoss 
I have tried to copy template2.json from host to container using docker cp command but it failed saying container path doesn't exist.

![cp](https://user-images.githubusercontent.com/65868732/83389601-19594680-a40e-11ea-9e92-be5e99e2d8f2.jpg)
![err](https://user-images.githubusercontent.com/65868732/83389612-1d856400-a40e-11ea-82aa-0f328f954de7.jpg)

**Comment by sylviamoss** [comment]
Hi @pra89j, I strongly believe there's something going on not related to Packer. I suggest asking the community about this in the [mailing list](https://groups.google.com/forum/#!forum/packer-tool) or [community forum](https://discuss.hashicorp.com/c/packer), they are generally more useful in these situations. I'll be closing this issue but feel free to reach out to us again.

Issues opened here on the Packer issue tracker are only viewed by a small handful of developers who work on the tool, and we don't always have the most depth or experience when it comes to custom issues with particular build configurations.
