### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by gamethis** [hashicorp/packer#9294]
The documentation found here https://www.packer.io/guides/packer-on-cicd/build-image-in-cicd/

inaccurately states that you must use bare metal for running the installers.

A person can also enablenested virtualization through to allow the use of vm's that you can deploy a virtual machine in.
https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/user-guide/nested-virtualization
https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.vsphere.vm_admin.doc/GUID-2A98801C-68E8-47AF-99ED-00C63E4857F6.html
https://wiki.xenproject.org/wiki/Nested_Virtualization_in_Xen

**Comment by nywilken** [comment]
Hi @gamethis thanks for reaching out. I agree that the document can be updated to call out nest virtualization as an option. But not go into the details of setting it up as the document really just highlights blog entries written by some of our partners. I don't know if we will be able to get to this soon, but pull requests are welcomed if you wanted to help improve the guide. Thanks!
