### ISSUE TITLE
Set tags for launch templates when using spot instances

### ISSUE THREAD

**Issue by evandam** [hashicorp/packer#9299]
#### Feature Description

There doesn't seem to be a way to specify tags for launch templates created by Packer when using spot instances on AWS. Being able to specify `launch_template_tags`, or apply `spot_tags` to launch templates, would be useful.

#### Use Case(s)

IAM permissions for Packer cannot be restricted at all. If we can specify tags for the launch template, IAM policies can be more narrowed instead of allowing a Packer role to be able to delete any launch template.

**Comment by evandam** [comment]
Hey @SwampDragons, any chance there's a fix for this in the pipeline?

I also saw https://aws.amazon.com/about-aws/whats-new/2020/07/amazon-ec2-now-supports-tagging-ec2-spot-instance-requests/, not sure if it would help at all for this or other issues.

**Comment by scalp42** [comment]
It seems that it's now possible to do that see https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-requests.html#concepts-spot-instances-request-tags

**Comment by SwampDragons** [comment]
Thanks for opening this! I'm glad they've added this support, and I'll have a team member take a look when we get a chance.

**Comment by aleksandrserbin** [comment]
I believe this was done in https://github.com/hashicorp/packer/pull/10203

**Comment by nywilken** [comment]
Yes it was thanks @aleksandrserbin. This feature will be available in the next release. To gain access to it before the official release you may download the next nightly release, once available. Cheers!
