### ISSUE TITLE
Setting Custom Attributes in vsphere builder

### ISSUE THREAD

**Issue by mlasevich** [hashicorp/packer#9310]
Trying to use packer to build vsphere templates - and have a question. As I understand, VSphere seems to use custom attributes as metadata to specify things like public key, among other things - data that can then be used by cloud-init to initialize the instance. I am seeing no way to set these custom attributes - unless it is inside largely undocumented [configuration_parameters](https://www.packer.io/docs/builders/vsphere-clone.html#configuration_parameters) parameter.

So is this possible and if so, how? And is there a list of available configuration_parameters anywhere?

Thanks,

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out. 

Wow you're right that's really poorly documented. `configuration_parameters` is a direct passthrough to the VMware API's ConfigSpec: https://pubs.vmware.com/vi3/sdk/ReferenceGuide/vim.vm.ConfigSpec.html

I'll have to update the docs to make that clearer. 

But back to your main question, I don't think configuration_parameters has what you need. I found this guide that suggests the right way to send user-data to cloud-init is via an iso: https://cloudinit.readthedocs.io/en/latest/topics/datasources/altcloud.html#vsphere

In that case, Packer does allow you to set iso_paths to attach extra isos in addition to the installation iso. https://www.packer.io/docs/builders/vsphere-iso.html#cdrom-configuration

Hope this helps.

**Comment by mlasevich** [comment]
Thanks.

I was really trying to avoid the floppy/iso route - but I may have to get back to that. vSphere offers a number of features that are supposed to work with this, including "Custom Attributes" and "Guest Customization" (unclear if these are same or separate) - but documentation is scarce and most I find online is people struggling with it :-( I am surprised this is not more commonly used.

**Comment by SwampDragons** [comment]
I have to admit our official vSphere support is still relatively new so I'm not an expert in their API. We'd love to support this if you can figure out the necessary API reference.

**Comment by mlasevich** [comment]
For those who come across this: - I think found a way - a VSphere plugin for `cloud-init` found [here](https://github.com/vmware/cloud-init-vmware-guestinfo) combined with  using `configuration_parameters` as:

```json
    "configuration_parameters":{
        "guestinfo.metadata": "**output of cat metadata.yaml | gzip | base64 **",
        "guestinfo.metadata.encoding": "gzip+base64",
        "guestinfo.userdata": "**output of cat userdata.yaml | gzip | base64 **",
        "guestinfo.userdata.encoding": "gzip+base64",
        "guestinfo.vendordata": "**output of cat vendordata.yaml | gzip | base64 **",
        "guestinfo.vendordata.encoding": "gzip+base64"
    }
```

If using `vsphere-iso` - need to install cloud-init and the plugin in preseed. If using `vsphere-clone` then you need a template/source image that already has the plugin installed.
