### ISSUE TITLE
HCL2 Ansible Provisioner Playbook No Such File or Directory

### ISSUE THREAD

**Issue by brianpham** [hashicorp/packer#9314]
```
build {
  sources = [
    # there can be multiple sources per build */
    "source.amazon-ebs.example"
  ]
  provisioner "ansible" {
    playbook_file = "./init.yml"
  }
}
```

I am trying to run the following on packer v1.5.6, but running into an error where the playbook_file is not found. Did the path change? I couldn't find much documentation for the ansible provisioner on hcl2

**Comment by azr** [comment]
@brianpham have you tried using a full path ?

**Comment by azr** [comment]
This reminds me that in hcl2 the [`abspath`](https://www.packer.io/docs/from-1.5/functions/file/abspath/) function can be used; it will give you the absolute path of file, if the path is not absolute, it will be joined with the current working directory.

**Comment by brianpham** [comment]
@azr Ah, yes I forgot to mention that the full path worked. I was able to get it working using `abspath` function. Thanks!

**Comment by azr** [comment]
Awesome !
