### ISSUE TITLE
Use kaniko as packer builder to build image on k8s/docker

### ISSUE THREAD

**Issue by yufeiminds** [hashicorp/packer#9315]
#### Feature Description

I want to use packer in Kubernetes cluster, but packer not be supported.

See: [Docker Builder](https://github.com/hashicorp/packer/blob/master/website/pages/docs/builders/docker.mdx#docker-builder)

> The Docker builder must run on a machine that has Docker Engine installed.
Therefore the builder only works on machines that support Docker and _does not
support running on a Docker remote host_. You can learn about what [platforms
Docker supports and how to install onto
them](https://docs.docker.com/engine/installation/) in the Docker
documentation.

I want to add a kaniko builder to read packer `JSON` config, convert it to `DockerFile`, and invoke kaniko to build image.

Is this achievable?

##### Information from official documentation

> [Kaniko](https://github.com/GoogleContainerTools/kaniko) is a tool to build container images from a Dockerfile, inside a container or Kubernetes cluster.

> Kaniko doesn't depend on a Docker daemon and executes each command within a Dockerfile completely in userspace. This enables building container images in environments that can't easily or securely run a Docker daemon, such as a standard Kubernetes cluster.

#### Use Case(s)

- Build a docker image on docker
- Build a docker image on Kubernetes cluster

**Comment by SwampDragons** [comment]
Hi there,

We don't have plans to support Kaniko right now; the team does not have the resources to create and support any more builders right now. However, if you want to create your own custom kaniko builder, we'd love to link it for our community.  https://www.packer.io/docs/extending/custom-builders/

Thanks!
