### ISSUE TITLE
[openstack] expose template variable for instance_id/instance_name

### ISSUE THREAD

**Issue by lmayorga1980** [hashicorp/packer#9324]
#### Feature Description

When running a packer build, it would be nice if I can use the `Instance Id` that is created so later I can `attach` an existing volume to that instance and use some persistent data during the build 

`openstack server add volume <volume_id> <PACKER_OPENSTACK_INSTANCE_ID> --device /dev/vdb`

#### Use Case(s)

* This will be very helpful to add a volume using the `openstack` CLI using the `local` provisioner.

**Comment by lmayorga1980** [comment]
🤔  https://github.com/hashicorp/packer/blob/master/builder/openstack/step_run_source_server.go#L131-L133

so `{{instance_id}}`

**Comment by nywilken** [comment]
Hi @im2nguyen the line you called out is putting the instanceid into a shared state for others steps in the builder to have access to its value. The openstack builder needs to be updated to include the instanceid in generated data so that it can be made available via 
```
{{build `instanceId`}}
```

Let me see if I can find a good example of what the code would look like in case you are interested in making the contribution for this feature request.

**Comment by lmayorga1980** [comment]
I have an interesting use case where I need that `instance_id` to actually run a local provisioner to attach an existing volume that has some data I needed during the packer build. I would like to contribute with the example later this week.

**Comment by lmayorga1980** [comment]
```
...
   {
      "type": "shell-local",
      "command": "openstack server add volume {{ build `ID` }} <MY-VOLUME-ID>"
    },
    {
      "type": "powershell",
      "inline": [ "Start-Sleep -Seconds 120",
                  "Get-Disk",
                  "Set-Disk -Number 1 -IsOffline $False"
                ]
    },
   {
    "type": "powershell",
      "scripts": [ "scripts/script_that_depends_on_volume_data_attached.ps1"
                  ]
   },
    {
      "type": "windows-restart",
      "restart_check_command": "powershell -command \"& {Write-Output 'restarted.'}\""
    },
    {
      "type": "shell-local",
      "command": "openstack server remove volume {{ build `ID` }} <MY-VOLUME-ID>"
    },
...
```

**Comment by nywilken** [comment]
Hi @lmayorga1980 thanks for the follow up here. Your findings are correct. While looking into the provisioning step I found that instance_id is shared with the provisioners via the `ID` build variable https://github.com/hashicorp/packer/blob/793b425dce1bd70e48acfe0374d17555019077a2/common/step_provision.go#L47. I was looking for the generated data to be set in the actual builder not in a shared provisioning step. Apologies for my miscommunication. All supported build variables are documented at https://www.packer.io/docs/templates/engine/#build

I'm going to close this issue as the requested feature has already been implemented. Please feel free to reach out if you have any additional requests or run into an issue which you think may be a bug. Cheers!
