### ISSUE TITLE
Azure ARM does not support boot diagnostics for non public cloud

### ISSUE THREAD

**Issue by davemedvitz** [hashicorp/packer#9333]
#### Overview of the Issue

When setting boot_diag_storage_account when also specifying cloud_environment_name, packer throws an error

vhd: Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details." Details=[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"InvalidParameter\",\r\n    \"message\": \"The blob URL's domain must be blob.core.usgovcloudapi.net.\",\r\n    \"target\": \"bootDiagnostics.storageAccountUri\"\r\n  }\r\n}"}]

### Packer version

Packer version 1.5.6

### Analysis

I did some digging, thinking that I wasn't providing the diag storage account in the right way.

The function SetBootDiag in template_builder.go (line 383 in master @ commit c016f37) hard codes the storage URI suffix.

**Comment by nywilken** [comment]
Hi @davemedvitz thanks for reaching out. In order for use to best help out can you provide a redacted build configuration for reproducing the issue. 

 > The function SetBootDiag in template_builder.go (line 383 in master @ commit c016f37) hard codes the storage URI suffix.

Is this the hard coded URI you are referring to https://github.com/hashicorp/packer/blob/master/builder/azure/common/template/template_builder.go#L391?
