### ISSUE TITLE
EC2 Instance Metadata V2 (IMDSv2) session token 'required' support for amazon builders

### ISSUE THREAD

**Issue by fred-vogt** [hashicorp/packer#9338]
NOTE: I was unable to find any PRs,Issues mentioning EC2 IMDSv2.

#### Feature Description

Support for setting the IMDSv2 session token setting to `required`.

#### Use Case(s)

Some shops may require this setting to be "always" on in a service control policy (IAM policy).

## AWS Links
* https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html
* https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html
  * See section: "IAM policies and SCPs"

## Terraform IMDSv2
For context ~  2019 Nov - `aws_instance` and `aws_launch_template`
* [Support setting EC2 instance metadata to require token (IMDSv2) #10949](https://github.com/terraform-providers/terraform-provider-aws/issues/10949)
  * [terraform-providers/terraform-provider-aws#12491](https://github.com/terraform-providers/terraform-provider-aws/pull/12491)

```hcl
  metadata_options {
    http_tokens = "required"

    http_put_response_hop_limit = 64
  }
```

NOTE: this "session" flow should work weather or not IMDSv2 is on/off,  so requiring it be on is a matter of site policy
```
# Get a session token
IMDSv2_TOKEN=$(curl -X PUT -H "X-aws-ec2-metadata-token-ttl-seconds: N..." -sL "http://169.254.169.254/latest/api/token")

# Query using the session token
curl -H "X-aws-ec2-metadata-token:$IMDSv2_TOKEN" -sL http://169.254.169.254/latest/meta-data/..."
```

**Comment by KevinHock** [comment]
Great suggestion!

**Comment by hubbcaps** [comment]
Any chance this could get picked up? Currently if you have an SCP that enforces IMDSv2 in an account, packer isn't feasible without some sort of security exception in that account.

The ability to be able to set the metadata options would be ideal.

**Comment by KevinHock** [comment]
I have a feeling @willbengtson can pull some strings on this one ;)

**Comment by KevinHock** [comment]
I know there ain't NotResource in the SCP language, but can you make exceptions via tags @hubbcaps? i.e. Only instances tagged as `secure=false` can have IMDSv1.

**Comment by hubbcaps** [comment]
If it were up to me I totally would, but our security team is pretty hard on the No Exceptions policy. I've been getting around this by building images in a sandbox account, and having them elevated to our locked down testing account by a dude with credentials, but as we're about to be getting our actual CI/CD platform online that's not gonna be scalable.

I've been meaning to get some more in depth Go experience, and I've tried taking a look at builder/amazon/ebs/builder.go, and think I can see where I can get the options in, just unsure if that's the only place the extension would be needed, and a little unsure on where the builder config is actually being passed to the the builder object. 

I can see in the struct we define config from class Config I think, but I'm not sure where the config is being actually passed into any of the builder functions to allow us to reference something like b.config is doing in that file.

I'm assuming from my inexperienced reading that there's essentially just a map of EBS config options somewhere I need to expand to include another map of the three metadata options currently available, http_tokens, http_endpoint, and http_put_response_hop_limit, but just not seeing where that might live. and then once it's expanded I think I can see how we can use those options in the actual builder functions.

If you or anyone else could point me in the right direction, I wouldn't mind taking a stab at this over the weekend, just not sure if I'm on the right path or not, or if I should just leave it up to the Hashicorp engineers to bang out eventually.

**Comment by hubbcaps** [comment]
Opened PR #10546 for this, hopefully everyone finds it acceptable and we can get it merged in.
