### ISSUE TITLE
Unstable builds with temporary IAM Profile

### ISSUE THREAD

**Issue by siddhantvirmani** [hashicorp/packer#9344]
#### Overview of the Issue

I'm having this very weird bug where every few builds there is an issue with the IAM profile not being attached to the temporal EC2 instance (which results in `yum` complaining).

#### Reproduction Steps

I run `PACKER_LOG=1 packer build packer/build.json`. _Usually_, immediately rerunning the build works. However, if I wait too long before rebuilding I get the same problem. I haven't been able to find a guaranteed pattern whatsoever.

### Packer version

1.5.5

### Simplified Packer Buildfile

https://gist.github.com/siddhantvirmani/61946abc1e8f9321562186feb60d4b29#file-build-json

### Operating system and Environment details

I run packer on WSL2. Env has aws secrets.

### Log Fragments and crash.log files

Successful log: https://gist.github.com/siddhantvirmani/61946abc1e8f9321562186feb60d4b29#file-successful-packer-log
I cancelled after the successful `aws configure list`. Can confirm that if it finds the credentials, the build succeeds without any issues. I can run a full build and upload that log too if needed.

Unsuccessful log: https://gist.github.com/siddhantvirmani/61946abc1e8f9321562186feb60d4b29#file-unsuccessful-packer-log
Cancelled this one after yum shows the update list - it just hangs there after that.

**Comment by SwampDragons** [comment]
I bet this has to do with that temporary IAM profile not being available to the build thanks to some "eventual consistency" shenanigans. 

We can probably verify this: Try adding `"pause_before": "5m"` to your first provisioner. (see https://www.packer.io/docs/templates/provisioners/#pausing-before-running for details)

If the build seems to consistently pass with that pause, it'll be a big step towards knowing this is a race condition, and I'll do some digging to see if there's anything we can do on the Packer side to make sure we don't try to proceed with a build until after the IAM information has propagated enough to AWS's back end that we are unlikely to hit this.

**Comment by siddhantvirmani** [comment]
Hi @SwampDragons, thanks for the response.

I was _really_ hoping that your suggestion would work, but unfortunately it doesn't. I'm still able to reproduce empty credentials with the 5 minute wait time (on the second try as well). Any other ideas? Should I try a larger wait period?

**Comment by SwampDragons** [comment]
Bummer. I feel like a 10 minute wait should have worked if that was it. 

Does the build work if you use a static, pre-built IAM profile?

**Comment by siddhantvirmani** [comment]
Yeah, I tested 5 times with a static IAM Profile and it worked without a hitch.

**Comment by SwampDragons** [comment]
ok so it's definitely an issue with the temprary profile. @b-b3rn4rd Any chance you can take a look at this, since you originally implemented the feature?

**Comment by b-b3rn4rd** [comment]
Hello, I'm happy to have a look over the weekend, I will try to use the build file provided. Realistically there could only one issue, IAM roles eventual consistency in conjunction with bad timing somewhere. The fact that the instance was launched means that the profile exists and is available, otherwise it would fail launching the instance as you can see in the logs (the instance was launched after retry)

**Comment by siddhantvirmani** [comment]
Hi @b-b3rn4rd, did you have any luck in reproducing this?

**Comment by siddhantvirmani** [comment]
Hi - just following up again! Happy to run any other tests if required :)

**Comment by siddhantvirmani** [comment]
Hi, checking in again - is there an update on this?

**Comment by SwampDragons** [comment]
We'll update the issue once there's an update. Looks like folks haven't had a chance to work on it yet. The workaround for you is to use a static IAM profile.

**Comment by mauriziod** [comment]
I'm actually having the same issue with a static IAM  profile, looks like a bug somewhere.
