### ISSUE TITLE
windows server 2019 provisionning feature installation (openssh server) access denied

### ISSUE THREAD

**Issue by pingooz** [hashicorp/packer#9345]
#### Overview of the Issue

I try to install a windows feature (openssh server) with a powershell script, but I've got an error message : "Add-WindowsCapability : Access denied."
The script work fine if I launch it manually.

### Packer version

v1.5.6

### Simplified Packer Buildfile

windows_2019.json
```json
{
  "builders": [
    {
      "boot_wait": "2m",
      "communicator": "winrm",
      "cpus": 2,
      "disk_size": "{{user `disk_size`}}",
      "floppy_files": [
        "{{user `autounattend`}}",
        "./scripts/disable-winrm.ps1",
        "./scripts/enable-winrm.ps1",
        "./answer_files/2019/unattend.xml",
        "./scripts/sysprep.bat",
        "./scripts/administrators_authorized_keys"
      ],
      "guest_additions_mode": "disable",
      "guest_os_type": "Windows2019_64",
      "headless": "{{user `headless`}}",
      "iso_checksum": "{{user `iso_checksum`}}",
      "iso_checksum_type": "{{user `iso_checksum_type`}}",
      "iso_url": "{{user `iso_url`}}",
      "memory": 2048,
      "shutdown_command": "a:/sysprep.bat",
      "type": "virtualbox-iso",
      "vm_name": "Windows2019",
      "winrm_password": "****",
      "winrm_timeout": "{{user `winrm_timeout`}}",
      "winrm_username": "****"
    }
  ],
  "post-processors": [
    {
      "keep_input_artifact": false,
      "output": "windows_2019_{{.Provider}}.box",
      "type": "vagrant",
      "vagrantfile_template": "vagrantfile-windows_2019.template"
    }
  ],
  "provisioners": [
    {
      "restart_timeout": "{{user `restart_timeout`}}",
      "type": "windows-restart"
    },
    {
      "execute_command": "{{ .Vars }} cmd /c \"{{ .Path }}\"",
      "scripts": [
        "./scripts/set-winrm-automatic.bat",
        "./scripts/uac-enable.bat",
        "./scripts/compile-dotnet-assemblies.bat",
        "./scripts/compact.bat"
      ],
      "type": "windows-shell"
    },
    {
      "scripts": [
        "./scripts/enable-remote-desktop.ps1",
        "./scripts/choco.ps1",
        "./scripts/openssh.ps1"
      ],
      "type": "powershell"
    }
  ],
  "variables": {
    "autounattend": "./answer_files/2019/Autounattend.xml",
    "disk_size": "61440",
    "disk_type_id": "1",
    "headless": "false",
    "iso_checksum": "DC252936122B22743C7C15BBC79E8C7C9F0D1123B4A7743BE46DC6143994E49A",
    "iso_checksum_type": "sha256",
    "iso_url": "/isos/en_windows_server_2019_updated_may_2020_x64_dvd_5651846f.iso",
    "restart_timeout": "5m",
    "winrm_timeout": "3h"
  }
}
```
openssh.ps1

```powershell
Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0

Set-Service -Name sshd -StartupType 'Automatic'
stop-Service sshd

New-ItemProperty -Path "HKLM:\SOFTWARE\OpenSSH" -Name DefaultShell -Value "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -PropertyType String -Force

`Copy-Item a:\sshd_config c:\ProgramData\ssh\ -Force`

Copy-Item a:\administrators_authorized_keys c:\ProgramData\ssh\administrators_authorized_keys

icacls C:\ProgramData\ssh\administrators_authorized_keys /reset
icacls C:\ProgramData\ssh\administrators_authorized_keys /inheritance:r /grant:r administrators:f
icacls C:\ProgramData\ssh\administrators_authorized_keys /grant system:f

start-Service sshd
```

### Operating system and Environment details

Ubuntu 20.04

<details>
  <Summary>Packer log</summary>
1;32m==> virtualbox-iso: Provisioning with powershell script: ./scripts/openssh.ps1<br>
packer-provisioner-powershell plugin: Opening ./scripts/openssh.ps1 for reading<br>
packer-provisioner-powershell plugin: Uploading env vars to c:/Windows/Temp/packer-ps-env-vars-5ed68960-c4b8-8aa4-14b9-0b40f4044477.ps1<br>
packer-provisioner-powershell plugin: [INFO] 116 bytes written for 'uploadData'<br>
[INFO] 116 bytes written for 'uploadData'<br>
packer-builder-virtualbox-iso plugin: Uploading file to 'c:/Windows/Temp/packer-ps-env-vars-5ed68960-c4b8-8aa4-14b9-0b40f4044477.ps1'<br>
packer-builder-virtualbox-iso plugin: #< CLIXML<br>
packer-builder-virtualbox-iso plugin: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>#< CLIXML<br>
packer-builder-virtualbox-iso plugin: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>Uploading file to 'c:/Windows/Temp/script-5ed68960-699c-0260-a9d9-152b55380d1a.ps1'<br>
packer-provisioner-powershell plugin: [INFO] 1252 bytes written for 'uploadData'<br>
[INFO] 1252 bytes written for 'uploadData'<br>
packer-builder-virtualbox-iso plugin: #< CLIXML<br>
packer-builder-virtualbox-iso plugin: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>#< CLIXML<br>
packer-builder-virtualbox-iso plugin: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs><br>
[INFO] starting remote command: powershell -executionpolicy bypass "& { if (Test-Path variable:global:ProgressPreference){set-variable -name variable:global:ProgressPreference -value 'SilentlyContinue'};. c:/Windows/Temp/packer-ps-env-vars-5ed68960-c4b8-8aa4-14b9-0b40f4044477.ps1; &'c:/Windows/Temp/script-5ed68960-699c-0260-a9d9-152b55380d1a.ps1'; exit $LastExitCode }"<br>
ui error: [1;31m==> virtualbox-iso: Add-WindowsCapability : Access is denied.<br>
ui error: [1;31m==> virtualbox-iso: At C:\Windows\Temp\script-5ed68960-699c-0260-a9d9-152b55380d1a.ps1:3 char:1<br>
ui error: [1;31m==> virtualbox-iso: + Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0<br>
ui error: [1;31m==> virtualbox-iso: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~<br>
ui error: [1;31m==> virtualbox-iso:     + CategoryInfo          : NotSpecified: (:) [Add-WindowsCapability], COMException<br>
ui error: [1;31m==> virtualbox-iso:     + FullyQualifiedErrorId : Microsoft.Dism.Commands.AddWindowsCapabilityCommand<br>
ui error: [1;31m==> virtualbox-iso:<br>
</details>

**Comment by nywilken** [comment]
Hi there thanks for reaching out. This looks to be more of a Windows issue than a Packer issue. When you run the script manually are you using an elevated Powershell?

If so you may want to look into using an elevated powershell provisioner https://www.packer.io/docs/provisioners/powershell/#elevated_user for this particular script. 

I also found this non Packer issue that might be helpful https://github.com/MicrosoftDocs/windowsserverdocs/issues/2074

**Comment by pingooz** [comment]
Hi, thanks for your advice.
Yes, I'm using an elevated Powershell. I'll try your links asap.

**Comment by pingooz** [comment]
I've use an elevated powershell provisioner like you suggested, and all is working fine. No need of the second link (that I had already seen).
thanks again.
