### ISSUE TITLE
Support running packer build (azure-chroot) on Azure Virtual Machine Scale Set

### ISSUE THREAD

**Issue by defcyy** [hashicorp/packer#9348]
## Feature Description

Packer azure-chroot builder seems only can run on virtual machine currently. Can packer arm-chroot builder support running on VMSS instance ?

## Use Case(s)

We have a VMSS Azure DevOps Agent pool, running packer build with azure-choort builder on VMSS agent will encounter the error as bellow:

```
compute.VirtualMachinesClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" 
```

The root cause may because packer needs to retrieve the VM information https://github.com/hashicorp/packer/blob/26d768f429455f9ea67ad17bd8b78a775db473d4/builder/azure/chroot/diskattacher.go#L174
But Virtual Machine Scale Set instance cannot be queried with Virtual Machine API. Here is the vmss instance API:
https://docs.microsoft.com/en-us/rest/api/compute/virtualmachinescalesetvms/get

**Comment by szamfirov** [comment]
Hi @defcyy, we are in the exact same situation with running the chroot builder from a VMSS instance. I've added support for it in [this PR](https://github.com/hashicorp/packer-plugin-azure/pull/184). Hopefully it'll be reviewed and merged soon 🤞

**Comment by Chivolta** [comment]
Hi. I have the same problem.
