### ISSUE TITLE
How to disable packer to get ipv6 address while connecting via SSH?

### ISSUE THREAD

**Issue by jiatongw** [hashicorp/packer#9349]
Hi team,

I am using packer vSphere builder to build images from a remote vCenter. VMs will have two IPs: IPv4 and IPv6. I found that it seems like packer will randomly pick one of them - and this may lead problem. 
```
...

==> vsphere: Power on VM...
==> vsphere: Waiting 10s for boot...
==> vsphere: HTTP server is working at http://10.xx.xx.xx:8495/
==> vsphere: Typing boot command...
==> vsphere: Waiting for IP...
==> vsphere: IP address: 2620:124:6020:xxx:xxx:xxx:xxx:xxx
==> vsphere: Using ssh communicator to connect: 2620:124:6020:xxx:xxx:xxx:xxx:xxx
==> vsphere: Waiting for SSH to become available...
```
And if packer picks an IPv6 address, then it hangs there..

Is there an option to disable the IPv6 address picks up? or somewhere could be configurable?

**Comment by jiatongw** [comment]
```
$ packer version
Packer v1.5.6
```

**Comment by jiatongw** [comment]
IP addresses of a VM are in a list and whichever the first comes up, packer will pick up that one. So adding a filter in packer side would be helpful

**Comment by SwampDragons** [comment]
I haven't had a chance to investigate yet, but if it is urgent for you then PRs are welcome.

**Comment by jhawk28** [comment]
@jiatongw added a new field in #9358, but haven't had a chance to test it.

**Comment by jiatongw** [comment]
@SwampDragons @jhawk28 Thanks! I found the problem.

The vendor code of govmomi in packer is not compatible with the latest govmomi code.
Here is the latest govmomi code https://github.com/vmware/govmomi/blob/v0.22.2/object/virtual_machine.go#L238
in the func `WaitForIP`, it has two parameters, `Waits for an IPv4 address if the v4 param is true.`

but in the vendor code: https://github.com/hashicorp/packer/blob/v1.5.6/vendor/github.com/vmware/govmomi/object/virtual_machine.go#L224
there is no `v4 ...bool` parameter.

So I think it will need to update the vendor first, and then update the call of the function `WaitForIP` in https://github.com/hashicorp/packer/blob/v1.5.6/builder/vsphere/common/step_wait_for_ip.go#L114 then I think the problem will be solved.

**Comment by jiatongw** [comment]
If you could tell me how to update the vendor, I can try to do a PR.

@jhawk28 Thanks for jumping in! My thought is updating the vendor fo govmomi is more better. WDYT?

**Comment by jhawk28** [comment]
@jiatongw I think it depends on if we want to fix other cases also: https://github.com/hashicorp/packer/pull/9358#issuecomment-638878740

**Comment by jiatongw** [comment]
@jhawk28 I got your point.

**Comment by jhawk28** [comment]
@jiatongw want to check if the changes fix your issue: https://app.circleci.com/pipelines/github/hashicorp/packer/5441/workflows/20e6a628-b54f-4eb0-8246-671ab8641444/jobs/57289/artifacts

**Comment by jiatongw** [comment]
@jhawk28 Thank you! I'll run some tests and report back to you

**Comment by jiatongw** [comment]
@jhawk28 I ran some tests against vSphere and so far so good! Thank you!

@SwampDragons which version will capture this change? the next `v1.5.7` or wait till `v1.6+`? If it will not be in the next release, I was thinking to cherry-pick this PR

**Comment by SwampDragons** [comment]
It'll be in the 1.6.0 release, which should happen this Tuesday.

**Comment by jiatongw** [comment]
> It'll be in the 1.6.0 release, which should happen this Tuesday.

Thanks!

**Comment by jiatongw** [comment]
> https://app.circleci.com/pipelines/github/hashicorp/packer/5441/workflows/20e6a628-b54f-4eb0-8246-671ab8641444/jobs/57289/artifacts

@jhawk28 Actually I found new issues came up when testing . moving to #9377 since this issue is closed.
