### ISSUE TITLE
unable to run the build azure-arm with data disk

### ISSUE THREAD

**Issue by shashank0033-stack** [hashicorp/packer#9370]
#### Overview of the Issue

When I am creating an image w/ the data disk in azure-arm it's passing an invalid name for the data disk.
below is the snippet I am using. 

    "builders": [
        {
            "type": "azure-arm",
            "client_id": "XXXXXXXXXX",
            "client_secret": "XXXXXXXXXXXXXXXXx",
            "subscription_id": "XXXXXXXXXXXXXXXXXXXXxx",
            "tenant_id": "XXXXXXXXXXXXXXXXXXXXX",
            "ssh_username": "azure",
            "ssh_password": "XXXXXXXXx",
            "os_type": "Linux",
            "image_publisher": "Canonical",
            "image_offer": "UbuntuServer",
            "image_sku": "16.04-LTS",
            "location": "East US",
            "vm_size": "Standard_B1s",
            "disk_additional_size": [
                100
            ],
            "managed_image_name": "RHEL-test-managed-image",
            "managed_image_resource_group_name": "my-test-rg"
it fails with the below error 

I ran the build w/ Packer_LOG=1
-----------
2020/06/08 03:12:18 packer-builder-azure-arm plugin: Azure response body="{\"status\":\"Failed\",\"error\":{\"code\":\"DeploymentFailed\",\"message\":\"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.\",\"details\":[{\"code\":\"BadRequest\",\"message\":\"{\\r\\n  \\\"error\\\": {\\r\\n    \\\"code\\\": \\\"InvalidParameter\\\",\\r\\n    \\\"message\\\": \\\"The entity name 'dataDisk.name' is invalid according to its validation rule: ^[^_\\\\\\\\W][\\\\\\\\w-._]{0,79}(?<![-.])$.\\\",\\r\\n    \\\"target\\\": \\\"dataDisk.name\\\"\\r\\n  }\\r\\n}\"}]}}" status="200 OK" method="GET" request="https://management.azure.com/subscriptions/9cc79726-ef97-4612-b183-77d37b563f85/resourcegroups/pkr-Resource-Group-mh6o87n2iu/providers/Microsoft.Resources/deployments/pkrdpmh6o87n2iu/operationStatuses/08586100210078668230?api-version=2018-02-01" x-ms-request-id="200af2e3-260c-4227-a59c-ebfe86f360d4"
==> azure-arm: Resource group has been deleted.
Build 'azure-arm' errored: Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details." Details=[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"InvalidParameter\",\r\n    \"message\": \"The entity name 'dataDisk.name' is invalid according to its validation rule: ^[^_\\\\W][\\\\w-._]{0,79}(?\u003c![-.])$.\",\r\n    \"target\": \"dataDisk.name\"\r\n  }\r\n}"}]

==> Some builds didn't complete successfully and had errors:
--> azure-arm: Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details." Details=[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"InvalidParameter\",\r\n    \"message\": \"The entity name '**dataDisk.name**' is invalid according to its validation rule: ^[^_\\\\W][\\\\w-._]{0,79}(?\u003c![-.])$.\",\r\n    \"target\": \"dataDisk.name\"\r\n  }\r\n}"}]

------------------------

#### Reproduction Steps

run the build with disk_additional_size [ ], it should fail w/ the above-mentioned error. 

### Packer version

1.5.6
### Simplified Packer Buildfile

    "builders": [
        {
            "type": "azure-arm",
            "client_id": "XXXXXXXXXX",
            "client_secret": "XXXXXXXXXXXXXXXXx",
            "subscription_id": "XXXXXXXXXXXXXXXXXXXXxx",
            "tenant_id": "XXXXXXXXXXXXXXXXXXXXX",
            "ssh_username": "azure",
            "ssh_password": "XXXXXXXXx",
            "os_type": "Linux",
            "image_publisher": "Canonical",
            "image_offer": "UbuntuServer",
            "image_sku": "16.04-LTS",
            "location": "East US",
            "vm_size": "Standard_B1s",
            "disk_additional_size": [
                100
            ],
            "managed_image_name": "RHEL-test-managed-image",
            "managed_image_resource_group_name": "my-test-rg"

### Operating system and Environment details

running on RHEL 7.8

**Comment by shashank0033-stack** [comment]
opened mistakenly

**Comment by shashank0033-stack** [comment]
open

**Comment by sylviamoss** [comment]
Hello there! I strongly believe this was fixed by https://github.com/hashicorp/packer/pull/9251 which will go out on this week's release. You can wait for the release to test it or you can use our nightly binaries here https://github.com/hashicorp/packer/releases/tag/nightly. 

Let me know if you need any other help. :)

**Comment by nywilken** [comment]
This was resolved in the 1.6.0 release. If you are still running into issues please leave a comment on this thread and we will gladly reopen. Cheers!
