### ISSUE TITLE
packer "-except" flag question

### ISSUE THREAD

**Issue by jiatongw** [hashicorp/packer#9377]
Hi,

I was using `Packer v1.6.0-dev (d87e53b8414e14bc482e39d602bd0fd3f81d5d5f)` to do some experiments with vSphere builder, but found an issue.

`packer build -except` is not working. packer still runs what should be excepted when in the post-processors stage. I am not sure if this is a drift of the unofficial `v1.6.0-dev` version, or `-except` flag will do some changes in the coming `v1.6` release?

**Comment by sylviamoss** [comment]
Hey @jiatongw! Thanks for reporting the issue. I confirmed this is not working on 1.6.0-dev and I'll work on this to find the solution.

**Comment by jiatongw** [comment]
@sylviamoss Thanks!
