### ISSUE TITLE
Need to pass CSV file as an argument for windows provisioner

### ISSUE THREAD

**Issue by purnimaY** [hashicorp/packer#9389]
Hello Team,

I am running powersell script using packer provisioners. But now my requirement to pass CSV file as argument in same provisioners. Please let me know how we can do this.

Find my packer Json file below
![image](https://user-images.githubusercontent.com/25564636/84262674-a3ef2380-ab3b-11ea-8a00-7ce6273b5352.png)

Regards,
Purnima

**Comment by nywilken** [comment]
Hi there, since there has been no updates to this question I'm going to assume that the response above was sufficient. If, however, you find that you are running into an issue with the proposed solution feel free to reach out. Cheers!
