### ISSUE TITLE
Creation a RHEL 8.2 VM using a kickstart file provided thru http file server

### ISSUE THREAD

**Issue by superghi64** [hashicorp/packer#9396]
Creation a RHEL 8.2 VM using a kickstart file provided thru http file server.

#### Overview of the Issue

When creating a VM in VMware running RHEL 8.x, I'm not able to access my kickstart file thru my HTTP file server. Keep getting an error at boot time saying:
loading... Failed: File or directory not found. 
From a browser, I'm able to access the KICKSTART file.
Same process but with RHEL 7.x is working.

#### Reproduction Steps

here is my JSON file:

```
{
  "builders": [
    {
      "CPUs": 2,
      "RAM": 16384,
      "RAM_reserve_all": false,
      "boot_command": [
        "<esc> <wait> <wait> vmlinuz initrd=initrd.img init.ks=http://httpsrv01:/KS/rhel82test-ks.cfg <enter>"
      ],
      "boot_order": "cdrom",
      "convert_to_template": false,
      "datacenter": "DC01",
      "datastore": "ant_esxds01",
      "disk_controller_type": "pvscsi",
      "guest_os_type": "rhel8_64Guest",
      "host": "esx17",
      "insecure_connection": "true",
      "iso_paths": [
        "[ant_esx_iso01] ISO/rhel-8.2-x86_64-dvd.iso"
      ],
      "network_adapters": [
        {
          "network": "VM Network",
          "network_card": "vmxnet3"
        }
      ],
      "notes": "Build via Packer",
      "password": "password@",
      "ssh_password": "password",
      "ssh_username": "root",
      "storage": [
        {
          "disk_size": 51200,
          "disk_thin_provisioned": true
        }
      ],
      "type": "vsphere-iso",
      "username": "administrator@vsphere.local",
      "vcenter_server": "vcentersrv01",
      "vm_name": "{{user `vm_name`}}"
    }
  ],
  "variables": {
    "vm_name": "rhel82test"
  }
}
```

### Packer version

1.6.0

### Operating system and Environment details

Packer is running of RHEL 7.8 server

```
2020/06/10 15:58:03 [INFO] Packer version: 1.6.0 [go1.13.12 linux amd64]
2020/06/10 15:58:03 Checking 'PACKER_CONFIG' for a config file path
2020/06/10 15:58:03 'PACKER_CONFIG' not set; checking the default config file path
2020/06/10 15:58:03 Attempting to open config file: /.packerconfig
2020/06/10 15:58:03 [WARN] Config file doesn't exist: /.packerconfig
2020/06/10 15:58:03 Setting cache directory: /dlgl_admin/kickstart/packer/Linux/packer_cache
2020/06/10 15:58:03 Creating plugin client for path: /usr/local/bin/packer
2020/06/10 15:58:03 Starting plugin: /usr/local/bin/packer []string{"/usr/local/bin/packer", "plugin", "packer-builder-vsphere-iso"}
2020/06/10 15:58:03 Waiting for RPC address for: /usr/local/bin/packer
2020/06/10 15:58:03 packer-builder-vsphere-iso plugin: [INFO] Packer version: 1.6.0 [go1.13.12 linux amd64]
2020/06/10 15:58:03 packer-builder-vsphere-iso plugin: Checking 'PACKER_CONFIG' for a config file path
2020/06/10 15:58:03 packer-builder-vsphere-iso plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/06/10 15:58:03 packer-builder-vsphere-iso plugin: Attempting to open config file: /.packerconfig
2020/06/10 15:58:03 packer-builder-vsphere-iso plugin: [WARN] Config file doesn't exist: /.packerconfig
2020/06/10 15:58:03 packer-builder-vsphere-iso plugin: Setting cache directory: /dlgl_admin/kickstart/packer/Linux/packer_cache
2020/06/10 15:58:03 packer-builder-vsphere-iso plugin: args: []string{"packer-builder-vsphere-iso"}
2020/06/10 15:58:03 Received unix RPC address for /usr/local/bin/packer: addr is /tmp/packer-plugin073871711
2020/06/10 15:58:03 packer-builder-vsphere-iso plugin: Plugin address: unix /tmp/packer-plugin073871711
2020/06/10 15:58:03 packer-builder-vsphere-iso plugin: Waiting for connection...
2020/06/10 15:58:03 packer-builder-vsphere-iso plugin: Serving a plugin connection...
2020/06/10 15:58:03 Creating plugin client for path: /usr/local/bin/packer
2020/06/10 15:58:03 Starting plugin: /usr/local/bin/packer []string{"/usr/local/bin/packer", "plugin", "packer-provisioner-shell"}
2020/06/10 15:58:03 Waiting for RPC address for: /usr/local/bin/packer
2020/06/10 15:58:03 Received unix RPC address for /usr/local/bin/packer: addr is /tmp/packer-plugin096846875
2020/06/10 15:58:03 packer-provisioner-shell plugin: [INFO] Packer version: 1.6.0 [go1.13.12 linux amd64]
2020/06/10 15:58:03 packer-provisioner-shell plugin: Checking 'PACKER_CONFIG' for a config file path
2020/06/10 15:58:03 packer-provisioner-shell plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/06/10 15:58:03 packer-provisioner-shell plugin: Attempting to open config file: /.packerconfig
2020/06/10 15:58:03 packer-provisioner-shell plugin: [WARN] Config file doesn't exist: /.packerconfig
2020/06/10 15:58:03 packer-provisioner-shell plugin: Setting cache directory: /dlgl_admin/kickstart/packer/Linux/packer_cache
2020/06/10 15:58:03 packer-provisioner-shell plugin: args: []string{"packer-provisioner-shell"}
2020/06/10 15:58:03 packer-provisioner-shell plugin: Plugin address: unix /tmp/packer-plugin096846875
2020/06/10 15:58:03 packer-provisioner-shell plugin: Waiting for connection...
2020/06/10 15:58:03 packer-provisioner-shell plugin: Serving a plugin connection...
2020/06/10 15:58:03 Preparing build: vsphere-iso
2020/06/10 15:58:03 Build debug mode: false
2020/06/10 15:58:03 Force build: false
2020/06/10 15:58:03 On error: 
2020/06/10 15:58:03 Waiting on builds to complete...
2020/06/10 15:58:03 Starting build run: vsphere-iso
2020/06/10 15:58:03 Running builder: vsphere-iso
2020/06/10 15:58:03 [INFO] (telemetry) Starting builder vsphere-iso
vsphere-iso: output will be in this color.

==> vsphere-iso: Creating VM...
==> vsphere-iso: Customizing hardware...
==> vsphere-iso: Mounting ISO images...
2020/06/10 15:58:04 packer-builder-vsphere-iso plugin: Creating CD-ROM on controller '&{{{} 200 0xc0006af960 <nil> <nil> <nil> 0 <nil>} 0 []}' with iso '[ant_esx_iso01] ISO/rhel-8.2-x86_64-dvd.iso'
2020/06/10 15:58:04 packer-builder-vsphere-iso plugin: No floppy files specified. Floppy disk will not be made.
==> vsphere-iso: Set boot order...
==> vsphere-iso: Power on VM...
==> vsphere-iso: Waiting 10s for boot...
==> vsphere-iso: Typing boot command...
2020/06/10 15:58:15 packer-builder-vsphere-iso plugin: Special code '<esc>' found, replacing with: CodeEscape
2020/06/10 15:58:15 packer-builder-vsphere-iso plugin: Waiting 1 second
2020/06/10 15:58:16 packer-builder-vsphere-iso plugin: Waiting 1 second
2020/06/10 15:58:25 packer-builder-vsphere-iso plugin: Waiting 1 second
2020/06/10 15:58:26 packer-builder-vsphere-iso plugin: Special code '<enter>' found, replacing with: CodeReturnEnter
2020/06/10 15:58:26 packer-builder-vsphere-iso plugin: [INFO] Waiting for IP, up to total timeout: 30m0s, settle timeout: 5s
==> vsphere-iso: Waiting for IP...
![rhel8-packer](https://user-images.githubusercontent.com/64607995/84313100-10662480-ab34-11ea-8c28-1e9999f03ab6.png)
```

after that, I'm getting the error....   so <CTRL-C> to cancel it

**Comment by SwampDragons** [comment]
Are you sure your vm has network access to your http file server? Sounds to me like you don't have access to it somehow.

You could try storing the kickstart locally and adding the kickstart via floppy files instead:

```      "floppy_files": [
        "./rhel82test-ks.cfg
      ],
```

I'm not an expert in bootstrapping rhel systems but with debian you can then pass the argument via the "`file=/media/preseed_hardcoded_ip.cfg` argument to init.rd

**Comment by superghi64** [comment]
Booting a RHEL 7 using the same formula packer/Json/kickstart is working just fine!!!

Envoyé de mon iPhone


Ghislain Lévesque
DLGL
T: (450) 979-4646

[cid:violet_782aadf1-245d-4001-89a8-38920cb80dd9.png]

DLGL launches COVID-20 Trace, an HCM health crisis management support module integrated with VIP.
<http://buzz.dlgl.com/en/2020/04/08/buzz-114-dlgl-launches-covid-20-trace/>[ Read more ]<http://buzz.dlgl.com/en/2020/04/08/buzz-114-dlgl-launches-covid-20-trace/>

DLGL lance COVID-20 Trace, un module de support à la gestion du capital humain lors de crise en santé, intégré à VIP.
<http://buzz.dlgl.com/2020/04/09/buzz-114-dlgl-lance-covid-20-trace/>[ Lire la suite ]<http://buzz.dlgl.com/2020/04/09/buzz-114-dlgl-lance-covid-20-trace/>



Le 11 juin 2020 à 17:07, Megan Marsh <notifications@github.com> a écrit :

﻿

Are you sure your vm has network access to your http file server? Sounds to me like you don't have access to it somehow.

You could try storing the kickstart locally and adding the kickstart via floppy files instead:

        "./rhel82test-ks.cfg
      ],


I'm not an expert in bootstrapping rhel systems but with debian you can then pass the argument via the "file=/media/preseed_hardcoded_ip.cfg argument to init.rd

**Comment by superghi64** [comment]
> 
> 
> Are you sure your vm has network access to your http file server? Sounds to me like you don't have access to it somehow.
> 
> You could try storing the kickstart locally and adding the kickstart via floppy files instead:
> 
> ```
>         "./rhel82test-ks.cfg
>       ],
> ```
> 
> I'm not an expert in bootstrapping rhel systems but with debian you can then pass the argument via the "`file=/media/preseed_hardcoded_ip.cfg` argument to init.rd

RHEL 8.x doesn't support FLOPPY anymore...

**Comment by rjhornsby** [comment]
I'm successfully using packer to kickstart both CentOS 7 and CentOS 8. My suspicion is that you're hitting one of two things -

After the server name, you have an extra `:`:
`init.ks=http://httpsrv01:/KS/rhel82test-ks.cfg`

This might be messing it up because there's a `:` with no port specified. That is, `hostname:` is expected to be followed by an integer. In this case, the parser finds `/` instead of the integer it was expecting.

Second, maybe somehow your RHEL 8 system isn't coming up onto the network properly, and/or cannot resolve `httpsrv01`. Might try the IP address of your http server to see if it's just a name resolution issue.

**Comment by superghi64** [comment]
That was a typo. In my command there is no “:” after http server name and I have also tried with IP address.

Like I mention, same command with RHEL 7 using PACKER/JSON is working perfectly but not HREL 8.

If I create manually a VM in VMware, assign the RHEL 8 ISO and break the boot sequence to specify the HTTP server for the KICKSTART file, it’s working. So it’s not a RHEL issue with HTTP.


Thanks for your help.




Ghislain Lévesque
DLGL
T: (450) 979-4646

[cid:violet_782aadf1-245d-4001-89a8-38920cb80dd9.png]

DLGL launches COVID-20 Trace, an HCM health crisis management support module integrated with VIP.
<http://buzz.dlgl.com/en/2020/04/08/buzz-114-dlgl-launches-covid-20-trace/>[ Read more ]<http://buzz.dlgl.com/en/2020/04/08/buzz-114-dlgl-launches-covid-20-trace/>

DLGL lance COVID-20 Trace, un module de support à la gestion du capital humain lors de crise en santé, intégré à VIP.
<http://buzz.dlgl.com/2020/04/09/buzz-114-dlgl-lance-covid-20-trace/>[ Lire la suite ]<http://buzz.dlgl.com/2020/04/09/buzz-114-dlgl-lance-covid-20-trace/>

**Comment by Isotop7** [comment]
Cant really help other than

```
"boot_command": [
               "<tab> text ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/centos-8.cfg ip=dhcp <enter><wait><wait><enter>"
            ],
```

works on my side. I'm using the builtin http server in packer.

**Comment by nywilken** [comment]
Hi @superghi64 seeing as this is working for RHEL7 and others are able to get the builds working, I suspect this may be a configuration error and not a Packer bug. I am going to close this issue, but if you find more information pointing to a Packer related bug. Please reach out and we will gladly review.
