### ISSUE TITLE
Please adopt semantic versioning

### ISSUE THREAD

**Issue by Fabian1976** [hashicorp/packer#9401]
From version 1.5.x to 1.6.0, you removed parameters from the json file which makes it backwards incompatible. Yes, i read the changelog and it is under "Backwards incompatibilities".
If you use semver, it would be clearer.

I know you have scripts (packer fix) to fix this issues, but it is still backwards incompatible. Pipelines which have version limit like "> 1.x.x < 2.0.0" break when you do not adhere to semver. It requires manual intervention and fixing to make it work again.

Thank you.

**Comment by SwampDragons** [comment]
Sorry this caused you confusion. HashiCorp libraries/modules do their best to follow semver, but our applications don't. For Packer, you can treat 1.x.0 releases as potentially backwards incompatible but 1.x.x releases are backwards compatible.
