### ISSUE TITLE
Add support for specifying key to fetch from Azure Key Vault

### ISSUE THREAD

**Issue by ricardclau** [hashicorp/packer#9404]
#### Feature Description

Very similar to the relatively recent https://github.com/hashicorp/packer/issues/9086 but in this case using Azure KV service

#### Use Case(s)

Same case as the mentioned feature, ability to use passwords or other secrets stored there

Not sure if there is enough interest for such feature but happy to work on this if nobody can step in and other fellow members are interested. The terraform provider can already interact with this so probably most of the heavy work is done there and it would be adapting it to the packer codebase

**Comment by SwampDragons** [comment]
I'd happily merge such a feature, if you want to work on it :)

**Comment by ricardclau** [comment]
Hey, sorry I missed your reply! Yeah, happy to give it a go! 

I started looking into it and would like to have some implementation discussion

In the terraform provider, you usually query for a value using the keyvault id + key (https://www.terraform.io/docs/providers/azurerm/d/key_vault_secret.html) but the keyvault id is a really long string which can be obtained by the resource_group name + keyvault name (https://www.terraform.io/docs/providers/azurerm/d/key_vault.html) which are more meaningful.

Do you think it's worth supporting both syntaxes or just the latter (rg name + kv name + key)?

Also, I am assuming, at least for the first implementation, the interpolation function will obtain the credentials from whatever is configured via az login and not supporting an extra config object for this, right?

These questions don't block me at all (and in fact I need to do some digging as I am not too familiar with the Azure APIs and SDKs) but I think it would be nice to clarify them at some point!

**Comment by SwampDragons** [comment]
I think it'd be worth supporting both syntaxes, ideally.

**Comment by SwampDragons** [comment]
Yes, the AWS secrets manager currently uses the same credentials as the builder, but I think this is an unfortunate limitation. I think it really comes down to how hard it would be to support separate credentials.

**Comment by ricardclau** [comment]
Sorry about the silence here all this time, I finally have a draft version of this working in my computer! 

It would be something like this

```
{
	"variables": {
		"secret1": "{{ azure_keyvault `resource_group` `kvname` `secretkey` }}",
                "secret2": "{{ azure_keyvault `/subscriptions/<subscriptionid>/resourceGroups/<resource_group>/providers/Microsoft.KeyVault/vaults/<kvname>` `secretkey` }}"
	},
	"builders": [
    {
      "type": "null",
      "communicator": "none"
    }
  ],
  "provisioners": [
    {
      "type": "shell-local",
      "inline": [
        "echo {{ user `secret1` }}"
      ]
    },

    {
      "type": "shell-local",
      "inline": [
        "echo {{ user `secret2` }}"
      ]
    }
  ]
}
```

Considering the syntax with 2 parameters contains the same words than the syntax with 3 not sure if it adds much value to have both but up to you of course :)

Regarding authentication I basically took "the terraform approach" as in use whatever is available in the box via env vars, az login, etc... I am basically using some helpers included in "github.com/hashicorp/go-azure-helpers" which of course needs to be added as an extra dependency. Not sure if you need to validate this in deep or considering it is a hashicorp package all would be well.

Azure has so many ways to authenticate and adding all them in this little feature would be really complicated IMHO but again happy to discuss

I will try to polish this in the next days, add some tests and hopefully get your review and eventually a thumbs up!

**Comment by SwampDragons** [comment]
great! looking forward to the PR.

**Comment by kirannhegde** [comment]
Hello @ricardclau Hope you are doing good. Have you been able to test your PR? If so, i look forward to your change that would benefit a lot of the community members.

**Comment by ricardclau** [comment]
I have no excuses whatsoever, I have just pushed an initial version that works locally but has no tests just to test the CI

I know there are a lot of changes in the deps but I just did `go mod vendor` after adding the code changes. I don't do much Golang (surely not with so many deps) so if there is a better way please let me know @SwampDragons

**Comment by kirannhegde** [comment]
Hello @ricardclau  I am assuming that your PR has passed all CI tests now. I can see that at: https://github.com/hashicorp/packer/pull/10118
Is that a correct assumption?  Once merged, when would this change be officially available?

Thanks,
Kiran Hegde

**Comment by ricardclau** [comment]
It will be available when the Packer maintainers feel like merging and tagging a new release, like every other addition to any open source tool. The code is not ready to be merged as there are no tests, no reviews and frankly it needs some refactoring.

If you are in such need, you can always compile my branch

**Comment by nywilken** [comment]
Hi there @kirannhegde thanks for your interest in this feature. We're excited to get it reviewed and merged in time for an upcoming Packer release. Do track the issue for updates; once the feature has been merged this issue will automatically get closed. 


In the meantime, if you are interested in trying out the changes as they get reviewed you can find compiled binaries [here](https://app.circleci.com/pipelines/github/hashicorp/packer/7596/workflows/d36483c1-03e7-4b0a-a676-55e8210a4d9d/jobs/87194/artifacts). Please keep in mind, as mentioned by @ricardclau, this feature still needs to be reviewed and tested so there may be some unexpected behavior with the current builds. 


If you wish to test the binaries please do so in a non-production environment. We look forward to hearing any feedback you might have for us. Cheers!

**Comment by kirannhegde** [comment]
Hello @nywilken  Thanks for letting me know. I will try to use the feature and report back in case i run into issues(i might take some time for the feedback) . @ricardclau Thanks a ton again for the great work so far.

Thanks,
Kiran Hegde

**Comment by ricardclau** [comment]
Just for the record, I have used the azurerm builder combined with the new function in a local MacOSx compiled version with no issues. 

Also other builders (AWS, DO...) don't seem to be affected by this new function as expected. 

So, I guess it should be safe to run some tests in a non-prod env as suggested. Will do some amends before the end of the week as suggested in the PR and add some tests and hcl2 support. 

Thanks for the reviews and comments so far!

**Comment by dcherry88** [comment]
Is there any progress on this? We would love to put this to use for our packer pipeline processes.
