### ISSUE TITLE
Default to using -NonInteractive for powershell scripts

### ISSUE THREAD

**Issue by red8888** [hashicorp/packer#9409]
pretty much this: https://github.com/hashicorp/packer/issues/6175

That was closed but is there any reason not to add -NonInteractive as default? When would you WANT powershell to hang forever in a packer build when a param is missing?

**Comment by nywilken** [comment]
Hi @red8888 thanks for the follow up here. Scanning through the original thread it looks like there are a few unknowns on how things would behave when adding the `-nointeractive` flag that is out of the scope of Packer. So as a workaround the suggestion is to use the `execute_command` option to change the default Powershell command to include the `-nointeractive` flag, as the user setting it would most likely have more knowledge around the need for the flag then just having it added to every command. 

Regarding the command hanging forever, the Powershell provisioner, which might be true for all provisioners, has a `timeout` option that will terminate the provisioner if it doesn't complete within the specified time frame. If you find that provisioners are hanging I would recommend giving the configuration option a try. 

There is currently some work going on in the Powershell provisioner to be better about handling errors which may help out with this issue in the future. 

I'm going to close this issue as we currently have a way to achieve this with the `execution_command` configuration option. But if you think of some other improvements that we should consider please feel free to drop a comment and I will gladly reopen. 

Thanks!
