### ISSUE TITLE
SSL certificate binding breaks on EC2 AMI after running SysprepInstance.ps1

### ISSUE THREAD

**Issue by 0ni0nrings** [hashicorp/packer#9410]
hello all, so most of people reading this will be familiar with Packer, I have a packer template shown below;
```
            "ami_name": "WIN2016-CUSTOM-{{user `build_version`}}",
            "instance_type": "t3.xlarge",
            "user_data_file": "userdata.txt",
            "associate_public_ip_address": true,
            "communicator": "winrm",
            "winrm_username": "Administrator",
            "winrm_port": 5986,
            "winrm_timeout": "15m",
            "winrm_use_ssl": true,
            "winrm_insecure": true
```

The content of ```user_data_file``` is shown below;
```
Remove-Item -Path WSMan:\Localhost\listener\listener* -Recurse
 
# Create self-signed cert for encrypted WinRM on port 5986
$Cert = New-SelfSignedCertificate -CertstoreLocation Cert:\LocalMachine\My -DnsName "packer-ami-builder"
New-Item -Path WSMan:\LocalHost\Listener -Transport HTTPS -Address * -CertificateThumbPrint $Cert.Thumbprint -Force
 
# Configure WinRM
cmd.exe /c winrm quickconfig -q
cmd.exe /c winrm set "winrm/config" '@{MaxTimeoutms="1800000"}'
cmd.exe /c winrm set "winrm/config/winrs" '@{MaxMemoryPerShellMB="1024"}'
cmd.exe /c winrm set "winrm/config/service" '@{AllowUnencrypted="false"}'
cmd.exe /c winrm set "winrm/config/client" '@{AllowUnencrypted="false"}'
cmd.exe /c winrm set "winrm/config/service/auth" '@{Basic="true"}'
cmd.exe /c winrm set "winrm/config/client/auth" '@{Basic="true"}'
cmd.exe /c winrm set "winrm/config/service/auth" '@{CredSSP="true"}'
cmd.exe /c winrm set "winrm/config/listener?Address=*+Transport=HTTPS" "@{Port=`"5986`";Hostname=`"packer-ami-builder`";CertificateThumbprint=`"$($Cert.Thumbprint)`"}"
cmd.exe /c netsh advfirewall firewall add rule name="WinRM-SSL (5986)" dir=in action=allow protocol=TCP localport=5986
cmd.exe /c net stop winrm
cmd.exe /c sc config winrm start= auto
cmd.exe /c net start winrm
```
At the end of the Packer template, I have provisioners for running PowerShell scripts, these are helper scripts located in EC2 by default;
```
"provisioners": [
        {
            "type": "powershell",
            "inline": [
                "C:\\ProgramData\\Amazon\\EC2-Windows\\Launch\\Scripts\\InitializeInstance.ps1 -Schedule",
                "C:\\ProgramData\\Amazon\\EC2-Windows\\Launch\\Scripts\\SysprepInstance.ps1 -NoShutdown"
            ]
        }
    ]
```
The problem is that if I use the ```SysprepInstance.ps1``` script then it *somehow* mucks up the listener and certificate, I am yet to figure out how but it does. I have to run these 3 commands again to get the AMI configured for WinRM 5986 connectivity. Same commands that are run before have to be run again.
```
Remove-Item -Path WSMan:\Localhost\listener\listener* -Recurse
$Cert = New-SelfSignedCertificate -CertstoreLocation Cert:\LocalMachine\My -DnsName "packer-ami-builder"
New-Item -Path WSMan:\LocalHost\Listener -Transport HTTPS -Address * -CertificateThumbPrint $Cert.Thumbprint -Force
```

But if I ```leave out the SysprepInstance.ps1 script``` then the AMI image works fine. I have tried this on different occasions and tested my theory.

I understand that ```SysprepInstance.ps1``` will generalize the AMI image & *maybe* that is the reason that I have to redo the commands to get WinRM 5986 working. Could be wrong though?

My question is, has anyone else come across this situation and if yes then what was the fix?

Even a point at to a GIT repo will help. Thanks.

**Comment by nywilken** [comment]
Hi @0ni0nrings typically speaking Sysprep scripts are usually reserved for the last provisioning step because it often does mess with the WinRM setup and connectivity. The fact that removing the script helps the build seems to imply that it is the issue. But I say  that without knowing the exact details of what the EC2 scripts are doing. 

Here is a similar issue https://github.com/hashicorp/packer/issues/8596#issuecomment-574284030. I don't see any debug logs here so not sure if you are seeing the same error. 

With that said, I recommend you reach out on the [community forum](https://discuss.hashicorp.com/c/packer/) as they are generally more useful. Issues opened here on the Packer issue tracker are only viewed by a small handful of developers who work on the tool, and we don't always have the most depth or experience when it comes to custom issues with particular build configurations.

**Comment by 0ni0nrings** [comment]
thanks @nywilken I have posted the question [here](https://discuss.hashicorp.com/t/ssl-certificate-binding-breaks-on-ec2-ami-after-running-sysprepinstance-ps1/9924)
