### ISSUE TITLE
Packer Oracle Cloud OCI builder-  root block storage size change

### ISSUE THREAD

**Issue by taro-cmd** [hashicorp/packer#9417]
https://www.packer.io/docs/builders/oracle-oci.html - based on the oracle-oci reference, it has no options os size adjustment. Oracle-classic does have the option but oracle-oci does not.

Azure and aws has those options, https://www.packer.io/docs/builders/azure/arm/#os_disk_size_gb.

**Comment by harveylowndes** [comment]
I believe this was covered by https://github.com/hashicorp/packer/commit/72166febee89db489655938a047500a4569c6b3e#diff-7eb140be9e93f54f4c90da15e6fffa09c0def05e62ad174cceb6a8b695f781c6

**Comment by prydie** [comment]
Closed by https://github.com/hashicorp/packer/pull/10017
