### ISSUE TITLE
HCL coalesce function returning the first empty string

### ISSUE THREAD

**Issue by dsolsona** [hashicorp/packer#9419]
## Overview of the Issue

The behaviour of `coalesce` between terraform and packer differs. The packer documentation states

> coalesce takes any number of arguments and returns the first one that isn't null or an empty string.

but what I'm seeing is `coalesce` is returning empty strings, and only working fine with null values.

#### Reproduction Steps

```shell
~$ touch test.pkr.hcl
~$ packer console ./
> "${coalesce("", "should return this")}"
>
> "${coalesce(null, "should return this")}"
> should return this
```

In Terraform `coalesce` gives "should return this" in both invocations.

### Packer version

Packer v1.6.0

### Simplified Packer Buildfile

Can reproduce with an empty test file.

### Operating system and Environment details

Mac OS 10.15.5
Linux Debian 10

### Workaround

I'm using conditional expressions as a workaround

**Comment by juneeighteen** [comment]
🐛 I'm seeing this too. Packer 1.6.1

**Comment by azr** [comment]
good news; https://github.com/hashicorp/go-cty-funcs/pull/5 just got merged, I'm using that new function right now.
