### ISSUE TITLE
Help with -only flag

### ISSUE THREAD

**Issue by vanderboon** [hashicorp/packer#9421]
### Packer version
1.6.0

### Goals
Migrate to HCL & split code into source, builder & variable files so we can write source blocks once and reuse them across any builder.  Building images across providers should just be a case of adding a new source and adding it to the relevant builders files.

### Problem
File layout is:
- hcl/source-amazon-ebs.pkr.hcl
- hcl/builder-alin2.pkr.hcl
- hcl/builder-win2019.pkr.hcl
- hcl/variables.pkr.hcl
- hcl/vars-alin2.pkrvars.hcl
- hcl/vars-win2019.pkrvars.hcl

Each of the hcl/builder-* files has a name attribute e.g. `name = "alin2"`

I expected the command to build a specific OS would be `packer build -var-file=hcl/vars-alin2.pkrvars.hcl -only=alin2 hcl` however nothing is built.

What am I doing wrong?  Or is there an issue with the -only flag?

**Comment by azr** [comment]
Hey @vanderboon, thanks for opening, it is not yet possible to only on a `build` name. For now only/except will solely match the source type and name. I am currently working towards making this part of Packer HCL2 a little bit better and consistent. The issue is this one: #9399

**Comment by vanderboon** [comment]
Thanks for the update.  I'll monitor #9399.
