### ISSUE TITLE
Packer fails on non-existent Shared Image Gallery

### ISSUE THREAD

**Issue by karapuz50** [hashicorp/packer#9423]
When tried to create an image for azure and publish it to Shared Image Gallery packer returned an error:

==> Builds finished but no artifacts were created.
2020/06/15 12:11:25 [INFO] (telemetry) Finalizing.
Build 'azure-arm' errored: the Shared Gallery Image to which to publish the managed image version to does not exist in the resource group azure-infra

Bu SIG does exist:
```shell
~/src$ az sig list
[
  {
    "description": "Shared images and things.",
    "id": "/subscriptions/xxxxxxxxxxxx/resourceGroups/AZURE-INFRA/providers/Microsoft.Compute/galleries/bionic8_image_gallery",
    "identifier": {
      "uniqueName": "xxxxxxxx-BIONIC8_IMAGE_GALLERY"
    },
    "location": "eastus",
    "name": "bionic8_image_gallery",
    "provisioningState": "Succeeded",
    "resourceGroup": "AZURE-INFRA",
    "tags": {
      "component": "images",
      "env": "prod"
    },
    "type": "Microsoft.Compute/galleries"
  }
]
 ~/src$ 
```

Related part in packer JSON is:
```
"shared_image_gallery_destination": {
        "resource_group": "{{user `azure_infra_sg`}}",
        "gallery_name": "{{user `azure_sig_name`}}",
        "image_name": "{{user `name`}}",
        "image_version": "{{user `version`}}",
        "replication_regions": ["East US"]
      },
```

When run in debug mode:

```
==> azure-arm: WARNING: Zone resiliency may not be supported in East US, checkout the docs at https://docs.microsoft.com/en-us/azure/availability-zones/
2020/06/15 12:11:25 packer-builder-azure-arm plugin: Azure request body="" method="GET" request="https://management.azure.com/subscriptions/xxxxxxxxxxxxxxxxxxx/resourceGroups/azure-infra/providers/Microsoft.Compute/galleries/bionic8_image_gallery/images/centos7-3p-beta?api-version=2019-03-01"
2020/06/15 12:11:25 packer-builder-azure-arm plugin: Azure response request="https://management.azure.com/subscriptions/xxxxxxxxxxxxxxxxxxx/resourceGroups/azure-infra/providers/Microsoft.Compute/galleries/bionic8_image_gallery/images/centos7-3p-beta?api-version=2019-03-01" x-ms-request-id="c66f2fb4-efc0-400b-8a5a-8a06611306b7" body="{\"error\":{\"code\":\"ResourceNotFound\",\"message\":\"The Resource 'Microsoft.Compute/galleries/bionic8_image_gallery/images/centos7-3p-beta' under resource group 'azure-infra' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix\"}}" status="404 Not Found" method="GET"
2020/06/15 12:11:25 packer-builder-azure-arm plugin: Azure response status="404 Not Found" method="GET" request="https://management.azure.com/subscriptions/xxxxxxxxxxxxxxxxxxx/resourceGroups/azure-infra/providers/Microsoft.Compute/galleries/bionic8_image_gallery/images/centos7-3p-beta?api-version=2019-03-01" x-ms-request-id="c66f2fb4-efc0-400b-8a5a-8a06611306b7" body="{\"error\":{\"code\":\"ResourceNotFound\",\"message\":\"The Resource 'Microsoft.Compute/galleries/bionic8_image_gallery/images/centos7-3p-beta' under resource group 'azure-infra' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix\"}}"
2020/06/15 12:11:25 [INFO] (telemetry) ending azure-arm
2020/06/15 12:11:25 Waiting on builds to complete...
2020/06/15 12:11:25 machine readable: error-count []string{"1"}
==> Some builds didn't complete successfully and had errors:
2020/06/15 12:11:25 machine readable: azure-arm,error []string{"the Shared Gallery Image to which to publish the managed image version to does not exist in the resource group azure-infra"}
==> Builds finished but no artifacts were created.
2020/06/15 12:11:25 [INFO] (telemetry) Finalizing.
Build 'azure-arm' errored: the Shared Gallery Image to which to publish the managed image version to does not exist in the resource group azure-infra
```
When created an image resourceGroups/azure-infra/providers/Microsoft.Compute/galleries/bionic8_image_gallery/images/centos7-3p-beta  in manual way under the SIG packer did not fail.
Looks like packer verifies the image existence and when not found got it like SIG itself is missing.

 
A paragraph or two about the issue you're experiencing.

#### Reproduction Steps
1. Create a new, empty Shared Image Gallery in  azure
2. try to create an image and publish it to SIG

Steps to reproduce this issue

### Packer version
Packer version = 1.6.0

### Operating system and Environment details

OS: CentoOS 8 ( 4.18.0-147.8.1.el8_1.x86_64)

**Comment by nywilken** [comment]
Hi @karapuz50 thanks for reaching out. I updated the issue description. 

We will try to take a look as soon as we can. Can you please share your full configuration in case we can't reproduce with a simple SIG publishing setup. Thanks again!

**Comment by karapuz50** [comment]
Here is full packer configuration:

{
"type": "azure-arm",
"client_id": "xxxxxxxxxxxxxxxxxxxx",
"client_secret": "xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
"tenant_id": "xxxxxxxxxxxxxxxxxxxxxxx",
"subscription_id": "xxxxxxxxxxxxxxxxxxxxxxx",
"managed_image_resource_group_name": "azure-infra",
"managed_image_name": "{{user `name`}}",
"os_type": "Linux",
"image_publisher": "OpenLogic",
"image_offer": "CentOS",
"image_sku": "7.5",
"location": "East US",
"vm_size": "Standard_D2s_v3",
"shared_image_gallery_destination": {
"resource_group": "azure-infra",
"gallery_name": "bionic8_image_gallery",
"image_name": "{{user `name`}}",
"image_version": "1.0.0",
"replication_regions": ["East US"]
},
"azure_tags": {
"os_version": "CentOS",
"version": "{{user `version`}}",
"packer": "3p",
"Name": "CentOS7-3P"
}
}

**Comment by ashanb** [comment]
@karapuz50 did you managed to solve your issue? I am having a similar issue. Packer v1.6.1

Build 'azure-arm' errored: the Shared Gallery Image to which to publish the managed image version to does not exist in the resource group 'ashanb-gallery-rg'

**Comment by karapuz50** [comment]
Yes, you should create any image manually, upload to the gallery and then
you will be able to use terraform to update the image.

Best wishes,
Dmitry

**Comment by valtos** [comment]
Same problem here, that means we can't automate the creation with packer

**Comment by nmr** [comment]
I have to same problem on the 1.7.2 version.
