### ISSUE TITLE
HCL templates cannot call functions for variable defaults

### ISSUE THREAD

**Issue by jen20** [hashicorp/packer#9430]
#### Overview of the Issue

Using the new HCL template format, there is no way to define a variable which calls a function, which is a regression from the JSON template format.

This is useful when determining a consistent value for (as an example) the time at which an image was built to be used in both the AMI name and also an AMI and snapshot tag.

In the JSON syntax, the following works:

```json
	"variables": {
		"buildtime": "{{isotime \"2006-01-02-1504\"}}"
	},
```

The `buildtime` variable can then be interpolated at other points in the template.

#### Reproduction Steps

In an HCL template:

```hcl
variable "buildtime" {
	default = formatdate("YYYY-MM-DD-hhmm", timestamp())
}

# Rest of the template
```

```shell
$ packer validate template.pkr.hcl
Error: Function calls not allowed

  on template.pkr.hcl line 2, in variable "buildtime":
   2: 	default = formatdate("YYYY-MM-DD-hhmm", timestamp())

Functions may not be called here.
```

### Packer version

`Packer v1.6.0`

### Operating system and Environment details

macOS 10.15.5, Packer v1.6.0, AWS

**Comment by nywilken** [comment]
Hi @jen20 thanks for bubbling this up. There is work being done to improve support for HCL2 variables that may already have this in mind. Linking to https://github.com/hashicorp/packer/issues/9176 for visibility. Thanks again!

**Comment by azr** [comment]
Hey @jen20, quoting this message here https://github.com/hashicorp/terraform/issues/17229#issuecomment-361352965 

> Input variables are constant values [...] and so they cannot contain interpolations or other expressions that do not yield a constant value. [...]
> This separation makes it clear what is expected to be provided by the caller vs. what is generated privately [...].

For this purpose I would recommend instead using a local variable:

```hcl
locals {
  packerstarttime = formatdate("YYYY-MM-DD-hhmm", timestamp())
  # Also here I believe naming this variable `buildtime` could lead to 
  # confusion mainly because this is evaluated a 'parsing-time'.
}
```

I'm going to go ahead and close this issue, please do not hesitate asking more questions, thanks for trying Packer HCL2 !!
