### ISSUE TITLE
Build 'vsphere-iso' errored: Post "https://vcenter.test.com/sdk": Forbidden

### ISSUE THREAD

**Issue by vladanmiljkovic** [hashicorp/packer#9432]
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue
I'm getting an error toward specific version of vSphere. But some other version are working fine.  
Link to issue:
https://kb.vmware.com/s/article/1003218

Not Working:
vSphere version 6.7.0.42000

Working on:
 vSphere version  6.7.0.40000
 vSphere  version 6.5.0.20000

#### Reproduction Steps

Install packer
run the build from github:
I used this with some modifications:
https://github.com/guillermo-musumeci/packer-vsphere-iso-windows

### Packer version

From `1.5.6`

### Simplified Packer Buildfile

{
"builders":  [
                     {
                         "type":  "vsphere-iso",
                         "vcenter_server":  "{{user `vsphere-server`}}",
                         "username":  "{{user `vsphere-user`}}",
                         "password":  "{{user `vsphere-password`}}",
                         "insecure_connection":  "true",
                         "datacenter":  "{{user `vsphere-datacenter`}}",
                         "cluster":  "{{user `vsphere-cluster`}}",
                         "datastore":  "{{user `vsphere-datastore`}}",
                         "folder":  "{{user `vsphere-folder`}}",
                         "communicator":  "winrm",
                         "winrm_username":  "Administrator",
                         "winrm_password":  "{{user `winadmin-password`}}",
                         "pause_before_connecting":  "70m",
                         "convert_to_template":  "true",
                         "vm_name":  "{{user `vm-name`}}",
                         "guest_os_type":  "windows9Server64Guest",
                         "CPUs":  "{{user `vm-cpu-num`}}",
                         "CPU_hot_plug":  true,
                         "RAM":  "{{user `vm-mem-size`}}",
                         "RAM_reserve_all":  true,
                         "RAM_hot_plug":  true,
                         "firmware":  "bios",
                         "notes":  "This template is crated with Packer.",
                         "network_adapters":  [
                                                  {
                                                      "network":  "{{user `vsphere-network`}}",
                                                      "network_card":  "vmxnet3"
                                                  }
                                              ],
                         "disk_controller_type":  "lsilogic-sas",
                         "disk_size":  "{{user `vm-disk-size`}}",
                         "disk_thin_provisioned":  true,
                         "iso_paths":  [
                                           "{{user `os_iso_path`}}",
                                           "[] /vmimages/tools-isoimages/windows.iso"
                                       ],
                         "floppy_files":  [
                                              "autounattend.xml",
                                              "../scripts/disable-network-discovery.cmd",
                                              "../scripts/enable-rdp.cmd",
                                              "{{user `windows-config`}}",
                                              "{{user `ipv4-config`}}",
                                              "../scripts/enable-winrm.ps1",
                                              "../scripts/install-vm-tools.cmd",
                                              "../scripts/set-temp.ps1"
                                          ]
                     }
                 ],
    "provisioners":  [
                         {
                             "type":  "windows-shell",
                             "inline":  [
                                            "rundll32.exe user32.dll,LockWorkStation"
                                        ]
                         },
                         {
                             "type":  "windows-shell",
                             "inline":  [
                                            "PING -n 900 127.0.0.1 \u003e null"
                                        ]
                         },
                         {
                             "type":  "windows-shell",
                             "inline":  [
                                            "SchTasks /delete /tn PSWindowsUpdate /f"
                                        ]
                         }
                     ]
}

### Operating system and Environment details

Windows Server 2016

### Log Fragments and crash.log files

Debug mode enabled. Builds will not be parallelized.
vsphere-iso: output will be in this color.

Build 'vsphere-iso' errored: Post "https://vcenter.test.com/sdk": Forbidden

==> Some builds didn't complete successfully and had errors:
--> vsphere-iso: Post "https://vcenter-test.com/sdk": Forbidden

==> Builds finished but no artifacts were created.

Set the env var `PACKER_LOG=1` for maximum log detail.

**Comment by nywilken** [comment]
Hi @vladanmiljkovic thanks for reaching out. It seems like you are able to get this working in two of your three environments:

>Not Working:
vSphere version 6.7.0.42000
>Working on:
vSphere version 6.7.0.40000
vSphere version 6.5.0.20000

Have you looked at the change log for version 6.7.0.42000 to see what might have changed? 

There might be a chang needed to the config. I recommend you reach out to the [community forum](https://discuss.hashicorp.com/c/packer/). Issues opened here on the Packer issue tracker are only viewed by a small handful of developers who work on the tool, and we don't always have the most depth or experience when it comes to custom issues with particular build configurations.

**Comment by nywilken** [comment]
Hi @vladanmiljkovic since there hasn't been any updates to this issue I am going to go ahead and close it. If you end up needing more help with this kind of configuration, the mailing list or community forum are generally more useful. Issues opened here on the Packer issue tracker are only viewed by a small handful of developers who work on the tool, and we don't always have the most depth or experience when it comes to custom issues with particular build configurations. Cheers!
