### ISSUE TITLE
Add output_directory to file builder

### ISSUE THREAD

**Issue by caldwed** [hashicorp/packer#9445]
#### Feature Description

Add output_directory field to the file builder so custom output directories can be created for artifacts. Right now, the target directory must already exist.

#### Use Case(s)

I am using the file builder in a multi-builder template where all the build artifacts are deposited in a single output tree. My provisioners and post-processors all operate within this tree. Using the output_directory would allow the same safety checks for empty directory to apply.

This would be useful for copying release artifacts to a build directory and for modifying previously created virtual machine disks.

The output_directory field already exists for other builders. This would allow the file builder to have the same function.

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out. This makes sense to me.

We could either create an output_directory template option, or we could go even simpler and just call os.MkDirAll on the `target`'s directory.

**Comment by caldwed** [comment]
Thanks for the reply. Either solution would work for me.

Using the output_directory option would allow for the standard directory checking constructs to be used. Of course, that's more work as well.
