### ISSUE TITLE
VSphere Compact & Thin Disk Image

### ISSUE THREAD

**Issue by HeroCC** [hashicorp/packer#9459]
Apologies if this is already implemented, or is requested in another ticket.

#### Feature Description

Right now, the vmware-(iso|clone) build types have an option to compact disks (or rather, skip compacting disks). The VSphere builders, however, seem to lack such an option. I looked for anything resembling 'compact' or 'thinning' to no avail. Ideally, I'd be able to use a similar flag to thin out free space before finalizing the VM / template. The only other way documented is to [Storage vMotion](https://kb.vmware.com/s/article/1002019) the disk after it's built, but I'm not sure if Packer supports doing that.

#### Use Case(s)

I'm using vsphere-clone on a VM that requires temporarily using a lot of space, but frees much of it
by the end of the buildprocess. I'd like to be able to zero out the free space and replicate something like [`vmkfstools --punchzero`](https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.storage.doc/GUID-CBF31A6B-B36F-4552-B512-CC92B1943902.html). I see this is already [implemented](https://github.com/hashicorp/packer/blob/093cfcfd9fc3ac9b99bf2a7c7fb5b10ba47bdb23/builder/vmware/common/driver_esx5.go#L108-L111) in vmware based builders, and I'd love to be able to use it with the vsphere builders.

Thank you for your time!

**Comment by jhawk28** [comment]
this will only work if you install the vmware tools. we usually use open-vm-tools on the linux side which does not have vmkfstools.

**Comment by HeroCC** [comment]
Most of the VMs have tools installed, but running `sudo vmware-toolbox-cmd disk shrink /` inside the guest doesn't work because it's running on ESXi, which AFAIK doesn't support thinning the disk from the guest.
