### ISSUE TITLE
vsphere-template is not using folder

### ISSUE THREAD

**Issue by Isotop7** [hashicorp/packer#9463]
#### Overview of the Issue

When specifying a `folder` in packer module `vsphere-template`, the vm should be marked as a template and moved to that folder.

#### Reproduction Steps

Use the `packer.json` below and run.

### Packer version

`1.6.0`

### Simplified Packer Buildfile

[packer.json](https://gist.github.com/Isotop7/ffc4e7e9842ad7ed6b5f86c219f6d1dc)

### Operating system and Environment details

Ubuntu 18.04 bionic, VCSA 6.7.0

**Comment by nywilken** [comment]
Hi there, thanks for letting us know. We'll take a look when we get a chance.

**Comment by Isotop7** [comment]
Hi,

this can be closed as it was an error on my side!

Best regards,
Hendrik
