### ISSUE TITLE
Azure unable to refresh token after long provision step

### ISSUE THREAD

**Issue by lovew-lc** [hashicorp/packer#9465]
#### Overview of the Issue

I have a long provision step approx. 75 minutes. After the provision step finishes successfully the following error is thrown:
```
Error: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/.../resourcegroups/pkr-Resource-Group-xqrs6sbgp1?api-version=2018-02-01: 
StatusCode=401 -- 
Original Error: adal: Refresh request failed. Status Code = '401'. Response body: 
{"error":"invalid_client",
"error_description":"AADSTS700024: Client assertion is not within its valid time range. Current time: 2020-06-22T13:39:13.4401725Z, 
expiry time of assertion 2020-06-22T12:55:20.0000000Z. Review the documentation at https://docs.microsoft.com/azure/active-directory/develop/active-directory-certificate-credentials .\r\n...}
```
#### Reproduction Steps

May be possible to reproduce by having a provision step which sleeps for 60-70 minutes. 

### Packer version

1.6.0

### Simplified Packer Buildfile
Tenant/subscription etc have been redacted.
```
{
  "builders": [{
    "type": "azure-arm",
    "client_cert_path": "./tmp2er4h34t.pem",
    "os_type": "Linux",
    "image_publisher": "Canonical",
    "image_offer": "UbuntuServer",
    "image_sku": "18.04-LTS",
  }],
  "provisioners": [
    {
        "inline": [
...
        ],
        "type": "shell"
    },
    {
        "execute_command": "chmod +x {{ .Path }}; {{ .Vars }} sudo -E sh '{{ .Path }}'",
        "inline": [

          "/usr/sbin/waagent -force -deprovision+user && export HISTSIZE=0 && sync"
        ],
        "inline_shebang": "/bin/sh -x",
        "type": "shell"
  }]
}
```

Let me know if more information is needed.

**Comment by SwampDragons** [comment]
Hi, thanks for opening this. Can you share a gist containing the logs you get when you set the environment variable `PACKER_DEBUG=1`? I want to see exactly where this failure is coming from so I can track down which authorizer isn't refreshing. 

In the meantime, is there a way you could work around this bug by making individual provisioning steps shorter?

**Comment by lovew-lc** [comment]
Hi, here is the gist: https://gist.github.com/lovew-lc/1ded35e32ad9bf13d165b4f7d23c32b2
Provisioner used:
```
"provisioners": [
    {
        "inline": [
            "sleep 4200"
        ],
        "type": "shell"
    },
    {
        "execute_command": "chmod +x {{ .Path }}; {{ .Vars }} sudo -E sh '{{ .Path }}'",
        "inline": [

          "/usr/sbin/waagent -force -deprovision+user && export HISTSIZE=0 && sync"
        ],
        "inline_shebang": "/bin/sh -x",
        "type": "shell"
  }]
```

I can't break out the provisioning step unfortunately. For now I worked around it by creating a thread which calls EnsureFresh on the service principal every minute;
```
ch := make(chan string, 1)
go func() {
		for {
			select {
			case <-ch:
				return
			case <-time.After(time.Minute * 1):
				err := spnCloud.EnsureFresh()
				ui.Message("refreshing token")
				if err != nil {
					ui.Message("failed to refresh token: " + err.Error())
				}
			}
		}
	}()

	defer func() {
		ch <- ""
	}()
```

**Comment by lovew-lc** [comment]
As a follow-up. I ran into problems with the workaround posted above as well when I started replicating the images to other regions as the build time substantially increased. To workaround it again I instead increased the lifetime of the JWT here https://github.com/hashicorp/packer/blob/v1.6.0/builder/azure/common/client/tokenprovider_cert.go#L27

**Comment by SwampDragons** [comment]
Thanks for the update. I guess the short-term workaround for folks who experience this is to increase the token lifetime. Long-term we'll need to do a deep investigation of how tokens get refreshed on the Packer side and whether or not we can refresh in the middle of a long-running call like an image copy operation.

**Comment by bnfbiz** [comment]
I am having this problem as well.  Any update on this?

**Comment by SwampDragons** [comment]
No, we haven't had a chance to investigate.

**Comment by lovew-lc** [comment]
I forgot to update the issue. However, we started using client secrets instead of certificates as a workaround. So to narrow the scope somewhat it seems related to authentication with certificates.

**Comment by bnfbiz** [comment]
I did verify that it works w/ username/password but that won't work for automation.  It appears like the token refresh isn't happening in the background like it should.

**Comment by bnfbiz** [comment]
@SwampDragons I am still having problems and need to move this to a job and the security principal.  I looked and don't see a way to increase the token lifetime in the builder (from your comment: short-term workaround for folks who experience this is to increase the token lifetime).  Am I missing something or are you referring to a code change?

**Comment by SwampDragons** [comment]
Looks like it'd be a code change. I'll try to take a look when I can but it's unlikely to make it into this release.

**Comment by SwampDragons** [comment]
Linked is a PR that bumps the timeout to two hours; here's a patch of that build: https://app.circleci.com/jobs/github/hashicorp/packer/89372

I won't be able to debug why the token provider isn't auto refreshing but hopefully that gives you enough of a timeout that you can work around the bug until I can investigate.

**Comment by bnfbiz** [comment]
Thanks @SwampDragons!  I am testing it now, but I suspect I will need longer as I know one of my failures indicated 2hr 57min.  There is alot of work the postprocessor is doing so it takes a while.

**Comment by bnfbiz** [comment]
@SwampDragons  I ran the test and it failed at 3hrs 13 min.  I would probably need 4-5hrs for the timeout.

**Comment by bnfbiz** [comment]
@SwampDragons I was looking at this a bit over break and here is where I am so far:

1.	I first setup my environment to build and develop packer (latest version of the code based on master).
2.	I then changed the timeout from `1 hr` to `5 minutes` and setup a HCL based packer configuration.  

```
variable "az_build_rg" {
  type = string
}

variable "az_client_id" {
  type = string
}

variable "az_client_cert_path" {
  type = string
}

variable "az_gallery_name" {
  type = string
}

variable "az_shared_library_rg" {
  type = string
}
variable "az_subnet_name" {
  type = string
}

variable "az_subnet_rg" {
  type = string
}

variable "az_subscription_id" {
  type = string
}

variable "az_vnet_name" {
  type = string
}

variable "sleeptime" {
  type    = string
  default = "3660"
}
source "azure-arm" "timeouttest" {
  subscription_id           = var.az_subscription_id
  client_id                 = var.az_client_id
  client_cert_path          = var.az_client_cert_path
  polling_duration_timeout  = "10m"

  os_type                   = "Linux"
  image_publisher           = "Canonical"
  image_offer               = "UbuntuServer"
  image_sku                 = "18.04-LTS"

  build_resource_group_name = var.az_build_rg
  shared_image_gallery_destination {
    subscription        = var.az_subscription_id
    resource_group      = var.az_shared_library_rg
    gallery_name        = var.az_gallery_name
    image_name          = "packertimeouttest"
    image_version       = "1.1.1"
    replication_regions = ["Central US"]
}
  managed_image_name                     = "packertimeouttest"
  managed_image_resource_group_name      = var.az_shared_library_rg
  private_virtual_network_with_public_ip = false
  virtual_network_name                   = var.az_vnet_name
  virtual_network_subnet_name            = var.az_subnet_name
  virtual_network_resource_group_name    = var.az_subnet_rg

}

build {
  sources = [ "azure-arm.timeouttest" ]

  provisioner "shell" {
    inline = [
      "sleep ${var.sleeptime}"
    ]
  }
}
```

3.	What I found odd is that it still takes 1hr of run time before it  actually fails (changing the var.sleeptime value.  When it fails it shows the certificate error of:

```
==> azure-arm.timeouttest: The resource group was not created by Packer, not deleting ...
--> azure-arm.timeouttest: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/<subscription id>/resourceGroups/<resourcegroupname>/providers/Microsoft.Compute/virtualMachines/pkrvmqerypa8arw?api-version=2018-04-01: StatusCode=401 -- Original Error:
adal: Refresh request failed. Status Code = '401'. Response body: {"error":"invalid_client","error_description":"AADSTS700024: Client assertion is not within its valid ti
me range. Current time: 2020-12-17T21:57:39.8614717Z, expiry time of assertion 2020-12-17T20:57:03.0000000Z. Review the documentation at https://docs.microsoft.com/azure/
active-directory/develop/active-directory-certificate-credentials .\r\nTrace ID: 6fca1725-5842-4bc4-9fd7-722e06e63100\r\nCorrelation ID: 7ee92bae-6eff-45db-9b83-52c57d449
59a\r\nTimestamp: 2020-12-17 21:57:39Z","error_codes":[700024],"timestamp":"2020-12-17 21:57:39Z","trace_id":"6fca1725-5842-4bc4-9fd7-722e06e63100","correlation_id":"7ee9
2bae-6eff-45db-9b83-52c57d44959a","error_uri":"https://login.microsoftonline.com/error?code=700024"}
```

4.	I see that the tests do not expect a refresh token for a Client Certificate:

https://github.com/hashicorp/packer/blob/v1.6.0/builder/azure/common/client/config_test.go#L191

5.	I have also been reading about Azure AD authentication and for a refresh_token to be provided the scope needs to include offline_access

https://docs.microsoft.com/en-us/azure/active-directory-b2c/tokens-overview#configuration

6.	The packer Azure builder documentation https://www.packer.io/docs/builders/azure#client_jwt which is documented to be the basis of the client_cert_path states “a user-chosen expiry time, limiting the validity of the token”

With this I am wondering what the fix should be, should it be modified to try and use refresh_tokens (not sure how to add the scope to the JWT as I haven’t seen any examples of it) or if the configuration parameter to specify the timeout (similar to polling_duration_timeout)

Thoughts?
