### ISSUE TITLE
[1.6.0] Qemu SSH communicator is not using  guest-detected IP address (found using net_bridge)

### ISSUE THREAD

**Issue by amaczuga** [hashicorp/packer#9475]
https://github.com/hashicorp/packer/blob/b05ca9e9e1989e832e02b5f676917a5b9c683606/builder/qemu/comm_config.go#L49-L51

I suspect that when coupled with:

https://github.com/hashicorp/packer/blob/b05ca9e9e1989e832e02b5f676917a5b9c683606/builder/qemu/ssh.go#L11-L14

this would be the reason qemu ssh communicator fails to use detected guest address:

```
==> postconfig-uefi: Typing the boot command over VNC...
==> postconfig-uefi: Waiting for the guest address to become available in the virbr0 network bridge...
2020/06/24 10:06:29 packer-builder-qemu plugin: Found guest address 192.168.133.76
2020/06/24 10:06:29 packer-builder-qemu plugin: Using host value: 127.0.0.1
==> postconfig-uefi: Using ssh communicator to connect: 127.0.0.1
==> postconfig-uefi: Waiting for SSH to become available...
```

it was working ok with nightly Packer v1.6.0-dev (374f82b978ffb892c1676718fdce4c92df261627)

**Comment by SwampDragons** [comment]
So it was working in the dev version but is not working in the official 1.6.0 release?

**Comment by amaczuga** [comment]
That's my observation, the nightly mentioned before is using the found guest address for ssh communicator. Thanks for your help.
