### ISSUE TITLE
1.6.0 interprets 'null' user variables as errors with -syntax-only flag

### ISSUE THREAD

**Issue by miketimofeev** [hashicorp/packer#9478]
#### Overview of the Issue
We have a bunch of templates where some required user variables are declared as 'null' as described [in the docs](https://www.packer.io/docs/templates/user-variables.html).
```
"variables": {
        "vcenter_server": null,
        "vcenter_username": null,
        "vcenter_password": null,
        "vcenter_datacenter": null,

```
Starting from version 1.6.0 `packer validate -syntax-only` command fails with 
```
Error initializing core: 4 errors occurred:
        * required variable not set: vcenter_password
        * required variable not set: vcenter_username
        * required variable not set: vcenter_server
        * required variable not set: vcenter_datacenter
```

Versions 1.5.6 and below work fine.

#### Reproduction Steps

Run `packer validate -syntax-only <template_path>` against template with 'null' user variables

### Packer version

1.6.0

### Simplified Packer Buildfile

Example in the description

### Operating system and Environment details

Happens both on macOS and windows

### Log Fragments and crash.log files

Validation log provided in the description

**Comment by nywilken** [comment]
Thanks for reaching out! This issue is due to the build script parsing logic that is now used by the validation command. We'll work on getting this fixed for the next release.
