### ISSUE TITLE
ResourceGroupNotFound Resource group pkr-Resource-Group- could not be found

### ISSUE THREAD

**Issue by adamrushuk** [hashicorp/packer#9482]
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

When the cleanup of resources groups are attempted, the following error appears:

`ResourceGroupNotFound : Resource group 'pkr-Resource-Group-<RANDOM>' could not be found`

This error occurs when using the `azure-arm` builder, with multiple base images (ubuntu, rhel, win2012, win2016, win2019).

#### Reproduction Steps

1. Download Packer config: [ubuntu.json](https://github.com/adamrushuk/Packer-Templates/blob/master/azure-test/ubuntu.json)
1. Run [test_packer_cleanup.sh](https://github.com/adamrushuk/Packer-Templates/blob/master/azure-test/test_packer_cleanup.sh)

### Packer version

`v1.6.0`

### Simplified Packer Buildfile

Packer config: [ubuntu.json](https://github.com/adamrushuk/Packer-Templates/blob/master/azure-test/ubuntu.json)

### Operating system and Environment details

`Ubuntu 18.04.4 LTS`

### Log Fragments and crash.log files

See [Packer Log gist](https://gist.github.com/adamrushuk/ce679fe475dce12327b9f43591e48d28)

**Comment by adamrushuk** [comment]
Just wanted to add that I've also tried `"async_resourcegroup_delete": "true"`, but the `ResourceGroupNotFound` error still remains.
The deletion does occur though, so this is more a logging race condition I expect.

**Comment by nywilken** [comment]
I think this issue has to do with the fact that Packer is trying to delete the resource group as part of the StepCreatResourceGroup.#Cleanup step after StepDeleteResourceGroup has been executed and the resource group has been deleted. This looks like an old artifact that needs to be updated.
