### ISSUE TITLE
Add iso_checksum feature to iso_paths

### ISSUE THREAD

**Issue by ctorkington-craven** [hashicorp/packer#9494]
#### Feature Description

The use of a checksum list (like iso_checksum) to validate that all ISOs connected during build using iso_paths have a hash in the iso_checksums list.

I imagine something like:-
"iso_paths":[`
"[datastore1] \Path1\Windows.iso",
"[datastore2] \Path2\VMTools.iso",
],
"iso_checksums":[
"SHA256:###########",
"SHA256:#########"
]

#### Use Case(s)

I work in a highly regulated environment building windows servers, the iso_urls option is not available to me due to security restrictions.
This would allow me to prove that in my Packer json file (version controlled in Git) that the ISO used has not been tampered with .

**Comment by jhawk28** [comment]
I don't think you can get a hash for a file from the datastore without downloading it and calculating it yourself. This is all that is available for the FileInfo:
``` go
type FileInfo struct {
	DynamicData

	Path         string     `xml:"path"`
	FriendlyName string     `xml:"friendlyName,omitempty"`
	FileSize     int64      `xml:"fileSize,omitempty"`
	Modification *time.Time `xml:"modification"`
	Owner        string     `xml:"owner,omitempty"`
}
```

**Comment by ctorkington-craven** [comment]
I raised case with VMware to see if there was a way in the API or powerCLI/esxcli to get access to the md5sum on ESXi. But seems the only way is via ssh direct to ESXi. Never mind.
