### ISSUE TITLE
packer variables which are lists to be interpreted using user variables

### ISSUE THREAD

**Issue by vogxn** [hashicorp/packer#950]
Some of the packer template variables can take a list, for eg: ami_regions. It is not possible right now to specify the regions to copy an AMI to as a user variable. This is because the user variables can only be strings. It would be nice to have a simple comma separated list of strings interpreted as a list when given on the command line or in the user -var-file option. Copying of AMIs is a time-consuming step and during development selectively publishing the AMI to restricted regions can save a lot of time.

``` bash
$packer build -var 'ami_regions=us-east-1,us-west-2,ap-southeast-1' template.json
```

**Comment by rohitagarwal01** [comment]
+1 
Was not able to specify the multiple regions to copy an AMI to, as a user variable
Not sure if the fix is already part of release or not, as I was not able to make it to work.
Will be really helpful if fix can be merged if not done already
