### ISSUE TITLE
.HTTPPort is always 0

### ISSUE THREAD

**Issue by zilti** [hashicorp/packer#9500]
#### Overview of the Issue

At least with an HCL file, .HTTPIP will be set correctly, but .HTTPPort will always be 0, and thus connection fails.

#### Reproduction Steps

Write an HCL2 file that tries to fetch a file using .HTTPIP and .HTTPPort.

### Packer version

Packer v1.6.0

### Simplified Packer Buildfile

Unnecessary

### Operating system and Environment details

OpenSUSE Tumbleweed, VirtualBox 6.1.

### Log Fragments and crash.log files

No relevant log fragments.

**Comment by nywilken** [comment]
Thanks for reaching out.

> At least with an HCL file, .HTTPIP will be set correctly, but .HTTPPort will always be 0, and thus connection fails.

Is the connection you speaking of within the initial boot command step? 

We’ll take a look when we get a chance. If you could provide the build logs and a sample of the configuration you are using that would be appreciated. That information is helpful to us especially in those cases where we may not be able to reproduce. Thanks!

**Comment by zilti** [comment]
There was literally no useful info in the build logs, no error, nothing. Neither IP nor port were mentioned in the verbose log, unfortunately. I tried three times. But if it's nonetheless helpful, I could look again tomorrow.

As for the HCL2 config, it was in the initial boot command, yes:
```hcl
source "virtualbox-iso" "freebsd" {
    guest_os_type        = "FreeBSD_64"
    iso_url              = local.iso_url
    iso_checksum         = local.iso_checksum
    ssh_username         = "vagrant"
    ssh_password         = "vagrant"
    ssh_timeout          = "20m"
    shutdown_command     = "sudo poweroff"
    memory               = 2048
    hard_drive_discard   = true
    hard_drive_nonrotational = true
    hard_drive_interface = "scsi"
    vboxmanage           = [
        ["modifyvm", "{{.Name}}", "--nictype1", "virtio"]
    ]
    boot_wait            = "40s"
    boot_command         = [
        "root<enter><wait>mfsroot<enter><wait3>",
        "setenv INSTALL_TARGET=/dev/da0<enter><wait>",
        "fetch -o /tmp/preinstall.sh http://{{.HTTPIP}}:{{.HTTPPort}}/preinstall.sh<enter><wait>",
        "fetch -o /tmp/install.sh http://{{.HTTPIP}}:{{.HTTPPort}}/install-vagrant.sh<enter><wait>",
        "chmod +x /tmp/preinstall.sh<enter><wait>",
        "chmod +x /tmp/install.sh<enter><wait>",
        "/tmp/preinstall.sh /dev/da0<enter>"
    ]
}
```

**Comment by nywilken** [comment]
Thanks for providing your configuration. I see that that the config does not specify a value for `http_directory`. If `http_directory` is not specified the HTTP server step is skipped and the default value of zero is specified as the HTTPort. 

Have you tried adding in the `http_directory` configuration option?

If the HTTP server is starting you will see a log entry similar to `Starting HTTP server on port ...`. If you are setting a `http_directory` and not seeing that log entry we would need to investigate further; at that point we will need to look at the build logs to see what might be going on. 

If in the event there is an issue with acquiring a specific port there are a few HTTP server options that you can use to manipulate the assigned address and port - see https://www.packer.io/docs/builders/virtualbox/iso#http-directory-configuration for more information

**Comment by zilti** [comment]
Oooh. I have two source blocks in there, and the one that got run first was missing it. Well, that solves it... thanks!
