### ISSUE TITLE
-force does not delete existing artifacts for vsphere-iso builder

### ISSUE THREAD

**Issue by egkelly** [hashicorp/packer#9511]
#### Overview of the Issue

When running packer build -force template.json, the build consistently fails with "The name '_template_rhel_server_7_7' already exists'. From the documentation, I would expect -force to clean up an existing template with the same name, as the template is neither a vm nor is it turned on. 

Appending {{ timestamp }} to the VM name solves this issue, but I have no desire to fill up my storage with templates that I will never return to as we are not currently versioning our templates. Also, this build is apart of a gitlab pipeline that is followed by a terraform build to create two VMs from the packer template, so I would like the template to have a consistent name.

#### Reproduction Steps

`packer build -force -var-file=variables.json template.json`

### Packer version

1.6.0

### Simplified Packer Buildfile

```
{
	"_comment": "rhel_server_7.7",
	"builders": [
	  {
	    "vcenter_server": "{{user `vcenter_server`}}",
	    "username": "{{user `username`}}",
	    "password": "{{user `password`}}",
	    "datacenter": "{{user `datacenter`}}",
	    "datastore": "{{user `datastore`}}",
	    "cluster": "{{user `cluster`}}",
		"folder": "{{user `folder`}}",
		"ssh_password": "{{user `ssh_password`}}",
		"ssh_username": "{{user `ssh_username`}}",

		"CPUs": 4,
		"RAM": 4096,
		"RAM_reserve_all": true,
		"boot_command": [...],
		"guest_os_type": "rhel7_64Guest",
		"host": "x.x.x.x",
		"insecure_connection": "true",
		"iso_paths": [
		  ".../rhel-server-7.7-x86_64-dvd.iso",
		  ".../ISOs/VMware Tools/10.2.5/linux.iso"
		],
		"network_adapters": [
		  {
			"network": "VM-External",
			"network_card": "vmxnet3"
		  }
		],
		"type": "vsphere-iso",
		"vm_name": "_template_rhel_server_7_7"
	  }
	],
	"provisioners": [...]
  }

```

### Operating system and Environment details

RHEL 7 gitlab runner

### Error Output

```
?[1;32mvsphere-iso: output will be in this color.?[0m

?[1;32m==> vsphere-iso: Creating VM...?[0m
?[1;31mBuild 'vsphere-iso' errored: error creating vm: The name '_template_rhel_server_7_7' already exists.?[0m

==> Some builds didn't complete successfully and had errors:
--> vsphere-iso: error creating vm: The name '_template_rhel_server_7_7' already exists.

==> Builds finished but no artifacts were created.
```

**Comment by jhawk28** [comment]
That error means you were able to get past the PreCleanVM call. PreCleanVM is what deletes the artifact if it exists and Force is set to true. I was just using -force today on my environment so its probably something related to the driver.FindVM(path).

What is your vsphere environment like? What does your cluster look like? What does govc show for the path of your currently deployed template? Are you running two packer's in parallel?

**Comment by egkelly** [comment]
We're running two DRS clusters in the environment, *foo and *bar. The template is on *bar with 15 ESXi hosts and 16 resource pools. The template path from the VM view is myvCenter > myDatacenter > Templates > packer-templates

`govc ls /COSIA-Datacenter/vm/Templates/packer-templates` shows _template_rhel_server_7_7 in that path.

This is only a single packer build.

**Comment by jhawk28** [comment]
What is the folder that you are putting in your packer file?

**Comment by egkelly** [comment]
/Templates/packer-templates

**Comment by jhawk28** [comment]
Actually, try the latest nightly. It may be fixed in #9390

**Comment by egkelly** [comment]
Running build -force with Packer v1.6.1-dev (1454f4f6a+CHANGES) does not solve the issue.

**Comment by jhawk28** [comment]
Try changing your folder to "Templates/packer-templates"

**Comment by jhawk28** [comment]
When I used the leading slash in my environment, it had the same problem. See if this build fixes it for you too: https://app.circleci.com/pipelines/github/hashicorp/packer/5973/workflows/802f37a7-167f-4d1d-ae7c-a77102fb6d9c/jobs/64637/artifacts

**Comment by egkelly** [comment]
That worked perfectly, thank you! And thanks for the quick response.

**Comment by mitchellmaler** [comment]
Do you know when 1.6.1 will be released? We cannot use the nightly version.

**Comment by SwampDragons** [comment]
Next week.
