### ISSUE TITLE
Error configuring bastion: Failed to read key

### ISSUE THREAD

**Issue by gowthamakanthan** [hashicorp/packer#9514]
#### Overview of the Issue

We are trying to use the packer via Jenkins to build the image in Vsphere. The credentials have been saved in the Jenkins, When we use the ssh key for bastion host we are getting below error.[using bastion password is working but want to use the key due to security reason]

#### Reproduction Steps

1. Save the necessary credentials in the Jenkins. Including bastion host and end-host keys.
2. Build the image using the bastion host key.

### Packer version

Packer v1.5.6
Provider : vsphere-iso

### Simplified Packer Buildfile

json file: https://gist.github.com/gowthamakanthan/0050acabcab8b50deb86b02f9ac2ef4c
Jenkins Pipeline: https://gist.github.com/gowthamakanthan/b165ee4c4b338607692ca8fa271313b0

### Operating system and Environment details

Packer is running on docker environment. Trying to build a Centos 7 image into Vsphere.

### Log Fragments and crash.log files

Error: https://gist.github.com/gowthamakanthan/8591726fad6c31ea4ba2e08e328e7a3e

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out. I think the issue is that you're both providing the path to the private key, AND setting ssh agent auth to true. Can you try making sure the key is loaded into the ssh-agent, and then leaving the `ssh_bastion_private_key_file` empty?

**Comment by gowthamakanthan** [comment]
Hello @SwampDragons, Thanks for the quick reply. i have tried with '''ssh_bastion_agent_auth: true,''' and getting the following error.

```

**Comment by gowthamakanthan** [comment]
Thanks. That's helped me. Packer is able to access the Bastion with keys. Thanks a lot.
