### ISSUE TITLE
Invalid IAM Instance Profile nameValue when using temporary_iam_instance_profile_policy_document

### ISSUE THREAD

**Issue by isobit** [hashicorp/packer#9516]
When specifying `temporary_iam_instance_profile_policy_document` with an `amazon-ebs` builder, builds on spot instances (e.g. when `spot_price` is specified) always fail due to the following error:

> Build 'amazon-ebs' errored: Error waiting for fleet request (REDACTED) to become ready:Your requested instance type (REDACTED) is not supported in your requested Availability Zone (REDACTED).Value (packer-5efcd988-d497-4c8a-3996-31840bf715cc) for parameter iamInstanceProfile.name is invalid. Invalid IAM Instance Profile nameValue (packer-5efcd988-d497-4c8a-3996-31840bf715cc) for parameter iamInstanceProfile.name is invalid. Invalid IAM Instance Profile name

I believe this is due to eventual consistency with IAM since it may take some time for a newly created IAM role to become visible to another service (e.g. EC2 Spot Fleet). Running with the `-debug` option and intentionally pausing after the `Creating temporary role for this instance` step seems to resolve the issue. It may be possible to fix this bug by either adding a short sleep after the temporary IAM role creation or implementing retry/backoff on the spot fleet/instance creation.

### Packer version

1.6.0

**Comment by nywilken** [comment]
Hi @isobit thanks for bubbling this up. It does sound like an eventual consistency issue. Would you be interested in opening a PR? I would be more than happy to help you push the fix forward.

**Comment by isobit** [comment]
Hi @nywilken, I am actually starting to dig through PR #8247 to learn about how this is implemented get familiar with the codebase more generally, I'd love to contribute if I can. It looks like there is actually already a wait implemented [here](https://github.com/b-b3rn4rd/packer/blob/ec1d70dc44ca8ac6b12fa9ef8aa1a43df1653b22/builder/amazon/common/step_iam_instance_profile.go#L102) that verifies the role exists before continuing... still digging to see if there's a specific issue with that wait or if it makes more sense to investigate the spot fleet request retry/backoff solution.

**Comment by SwampDragons** [comment]
That wait passing probably doesn't mean that the role is available to all services. I think you're right that this has to do with eventual consistency. 

I think the retry/backoff for the fleet request makes sense.
