### ISSUE TITLE
Does vSphere iso on Packer allow adding SCSI Controllers and assigning hard disks to SCSI Controllers?

### ISSUE THREAD

**Issue by amitbhadra** [hashicorp/packer#9518]
From the vSphere UI, I can add "New SCSI Controller". My use case is to create 4 SCSI Controllers. And when I create a new hard disk, I want to assign each hard disk to some SCSI Controller.

So essentially, suppose I have 8 hard disks and 4 SCSI Controllers, and I want to add Hard disks 1 and 2 to SCSI 0 as 0:0 and 0:1, Hard disks 3 and 4 to SCSI 1 as 1:0 and 1:1, etc.

But I see no such option in Packer. When I create 8 Hard disks, they all get assigned to SCSI 0 as 0:0, 0:1, 0:2, 0:3 .. 0:7.

**Comment by jhawk28** [comment]
The https://www.packer.io/docs/builders/vmware/vsphere-iso#disk_controller_type lets you define what kind of controller is used. Currently only one controller is supported.

**Comment by amitbhadra** [comment]
@jhawk28 Do you know if this is possible on Terraform?

**Comment by jhawk28** [comment]
I don't know about Terraform, but my pull request (#9519) should be able to add the capability.

**Comment by jhawk28** [comment]
I'm not sure I got everything 100% so no guarantee, but you can test out the binary here: https://app.circleci.com/pipelines/github/hashicorp/packer/5893/workflows/3fdb01f6-a04d-46d6-9a27-3c610011de18/jobs/63526/artifacts

I made disk controller a list: https://deploy-preview-9519--packer-www.netlify.app/docs/builders/vmware/vsphere-iso#disk_controller_type

Assign the disk to the controller with the index: https://deploy-preview-9519--packer-www.netlify.app/docs/builders/vmware/vsphere-iso#disk_controller_index

**Comment by amitbhadra** [comment]
Hey so will the config now look something like this?

```
"disk_controller_type" : [ "scsi", "scsi"],
"storage": [
    {
      "disk_size": 15000,
      "disk_controller_index": 0
    },
    {
      "disk_size": 20000,
      "disk_controller_index": 0
    },
    {
      "disk_size": 20000,
      "disk_controller_index": 1
    },
    {
      "disk_size": 20000,
      "disk_controller_index": 1
    }
],
```

**Comment by jhawk28** [comment]
exactly

**Comment by amitbhadra** [comment]
Hi, your code changes exactly fit my use case! Thanks so much.
But, I must mention his. I don't know if something messed up the stability of the packer binary. I have tried with almost similar parameters(instead of 4 scsi, I'm working with 4 pvscsi controllers). Out of 7 runs, it errored out 3 times.

The first error out was a "general server fault" but rest assured there was no such fault. This time, it was typing out the boot command and in between, it failed.
Second and third errors happened when it finished typing the boot command and it was stuck at a network unreachable for about 5 mins. This was solved when I stopped the run and started a new run.

It'd be great if there's a stable binary for this.

**Comment by jhawk28** [comment]
this build would include the new boot command stuff: https://github.com/hashicorp/packer/pull/9406
@sylviamoss

**Comment by amitbhadra** [comment]
Thanks, will you have a new Packer official release with these changes any time soon?

**Comment by jhawk28** [comment]
No idea, I just create pull requests. They seem to release about once a month.

**Comment by amitbhadra** [comment]
Please keep this issue open, I'll report back on the stability of the Packer binary you gave me. Or if you deliver newer binaries, I can test them out too.

**Comment by jhawk28** [comment]
I think they would prefer to have a new issue open for the boot stability issues. @SwampDragons would know.

**Comment by amitbhadra** [comment]
I'll make new issues with possible screenshots as and when I get them.

**Comment by SwampDragons** [comment]
Correct, I would like a new issue for any new stability issues. Sounds like this one can be closed once I merge 9519.
