### ISSUE TITLE
HCL2: for_each for source or build blocks

### ISSUE THREAD

**Issue by thor** [hashicorp/packer#9524]
#### Feature Description

Similar to its mechanism in Terraform, it would be useful to create `source` blocks using `for_each` (as the beta docs allude to with regards to resources).

```hcl
locals { 
  similar_builds = {
    "ubuntu-bionic-standard" = {
      vm_name = "foo"
    }
    "ubuntu-xenial-standard" = {
      vm_name = "bar"
    }
  }
}
build {
  source "vsphere-clone.delta" { 
    for_each = local.similar_builds
    vm_name = value.vm_name
  }
}
```
While the example uses `source`, allowing `build` would increase the flexibility to the extent where provisioners and post-processors also could be generated by the `for_each` expression.

Alternatively if the following was possible:
```hcl
build {
  source "vsphere-clone.delta" => {
    for key, value in {'ubuntu-bionic-standard' = { vm_name = "bar" }} : key => value
  }
}
```

#### Use Case(s)

* Allowing for more complex builds represented by simple user-designed interfacer for sources, similar to the role provided by `resource` in Terraform.
* Enabling shorter and more terse configuration files consisting of less redundant content.
* Solving similar issues to merging blocks, but without requiring to actually merge blocks as if they were dictionaries themselves like #9154.

**Comment by azr** [comment]
Hello @thor, thanks for opening. We will be thinking about this; in the meantime, did you see the example folder for hcl: https://github.com/hashicorp/packer/tree/master/examples/hcl/ubuntu ? What do you think of this solution ?

a 'base-builder' can be defined, for example:
https://github.com/hashicorp/packer/blob/03d29386dd92d45ad3ada54dc282f229f7bed526/examples/hcl/ubuntu/source.vmware-iso.pkr.hcl#L1-L17

and be referenced in a singular source block; then all fields of the referenced source are already set and we set only the specific fields:
https://github.com/hashicorp/packer/blob/03d29386dd92d45ad3ada54dc282f229f7bed526/examples/hcl/ubuntu/build.pkr.hcl#L53-L67

**Comment by thor** [comment]
Thanks for getting back to me @azr, it's much appreciated. I'll make my reply in #9154 instead of here, as I think the overall problem or use-case for us is somewhat more flexible than the exact use-cases mentioned in the issue.
