### ISSUE TITLE
Ability to set the "VM Storage Policy" while configuring hard disks using vSphere iso on Packer

### ISSUE THREAD

**Issue by amitbhadra** [hashicorp/packer#9525]
#### Feature Description

From the UI, we can select the VM Storage Policy when setting up the details of a Hard disk. This should be possible on Packer too.
Possibly something like - 
```
"storage": [
        {
          "disk_size": 34816,
          "disk_controller_index": 0,
          "storage_policy": "<storage-policy-dev>"
        },
        {
          "disk_size": 51200,
          "disk_controller_index": 0,
          "storage_policy": "<storage-policy-prod>"
        }
],
```
Why do I have "disk_controller_index"? Because this is another use case already covered in https://github.com/hashicorp/packer/issues/9518. I hope the new PR already has the changes from the previous issue I mentioned.

#### Use Case(s)
Based on whether the VM is dev or prod, the storage policy is changed.

**Comment by amitbhadra** [comment]
Hi @jhawk28 Please have a look at this if you're willing to.

**Comment by jhawk28** [comment]
If you give a mouse a cookie...

**Comment by amitbhadra** [comment]
@jhawk28 I made a meme for you https://drive.google.com/file/d/1JWfrOc_UF-_rJOAlMSy55jDhYJRYlTAg/view?usp=sharing
