### ISSUE TITLE
use_iap tunnel modifies global configuration

### ISSUE THREAD

**Issue by chilversc** [hashicorp/packer#9527]
#### Overview of the Issue

When using the googlecompute builder, setting  `use_iap` to true overwrites the global configuration values for the currently active account and `core.project`.

This behaviour can be dangerous if it is unexpected as a user could  run gcloud commands on the wrong project. Further more, if the user is running packer in parrallel in different shells, changing these settings will affect all the shells.

#### Reproduction Steps

```
gcloud config set project <first project>
gcloud auth login
```

Create a packer deployment that uses a service account  and a different project (e.g. second project).
Set `"use_iap": true` in the deployment file.
Run packer build.

Wait until the log shows "Step Launch IAP Tunnel".

While the build is still running, in a different terminal run:
```
gcloud config get-value project
gcloud auth list
```

Observe that the global configuration has changed in an unrelated terminal, potentially affecting any other commands also running with that user's account.

### Packer version

From `packer version`
* `1.6.0`
* `7ad140e`

### Simplified Packer Buildfile

```json
{
    "builders": [
    {
        "type": "googlecompute",
        "project_id": "{{ user `gcp_project` }}",
        "zone": "europe-west2-c",

        "source_image_family": "debian-10",
        "ssh_username": "packer",
        "image_name": "hello-world-v{{ isotime \"20060102150405\" }}",
        "image_family": "hello-world",
        "machine_type": "f1-micro",
        "disk_size": 10,
        "communicator": "ssh",
        "on_host_maintenance": "TERMINATE",

        "use_iap": true,
        "account_file": "key.json"
    }
    ],
    "provisioners" : [
        {
            "type" : "shell",
            "inline": ["ifconfig"]
        },
        {
            "type": "shell-local",
            "command": "exit 1"
        }
    ]
}
```

### Operating system and Environment details

Fedora f32

**Comment by nywilken** [comment]
Thanks for letting us know. We will take a look.

**Comment by SwampDragons** [comment]
I've tweaked the code and have builds that may fix this here: https://circleci.com/gh/hashicorp/packer/70271#artifacts/containers/0

**Comment by SwampDragons** [comment]
Just tested using your workflow and confirmed that the linked PR does solve this.

**Comment by chilversc** [comment]
The part I still havn't thought of a nice solution to is where it also changes the active authenticated account, which could surpprise someone if they then run a `gcloud` command, as that command would now run as the service account instead of what ever they had previously configured.

This comes from the previous line:
```
gcloud auth activate-service-account --key-file='{{.AccountFile}}'
```

Could also handle the case where the account file is not set (i.e. using application default credentials).

One idea that I havn't had time to test yet is checking the precedence between the active account (as set by `gcloud auth`) and the `GOOGLE_APPLICATION_CREDENTIALS` environment variable. Hopefully the environment variable has higher precedence.

Upside is if we can get rid of that command and replace it with a parameter or environment variable is we can skip needing to create and run a script and just use the gcloud command directly.

**Comment by SwampDragons** [comment]
If you get a chance to test, I'd love to hear whether the env vars take precedence. I think changing the active account is at least a less dangerous change than just quietly changing the project, but it would certainly be nice not to change anything.
