### ISSUE TITLE
Add centralized, root-level cache

### ISSUE THREAD

**Issue by keithhamilton** [hashicorp/packer#953]
I'm working on a library of packer templates for my dev team and have broken them out like so (example names given):

couchdb
--rhel
--ubuntu
--amazon-linux
mysql
--rhel
--ubuntu
--amazon-linux
...
tomcat
--rhel
--ubuntu
--amazon-linux

and each time I build a different template type (mysql, couchdb, etc) that isn't based on an Amazon AMI, I have to redownload the iso into a cache that is localized to the template subfolder. A great feature might be a centralized cache at the root directory of whatever folder is being worked in so that multiple templates can share iso images across a directory structure.

don't know if this is a complete PITA. Could violate the principle of the tool...? Packer is great regardless of this.

Thanks!
Keith

**Comment by derek-adair** [comment]
Is there any reason not to do this by default?  Its how i'd expect it to work.

**Comment by SwampDragons** [comment]
I suspect that the original reasoning behind not having it as a default is wanting to keep Packer within a small footprint on the operating systems running it.  I do think we could do a better job documenting PACKER_CACHE_DIR though.
