### ISSUE TITLE
Packer 1.6.0 gives "No valid credential sources found for AWS Builder." AWS CLI is configured correctly.

### ISSUE THREAD

**Issue by da-edra** [hashicorp/packer#9531]
#### Overview of the Issue

I'm running a Packer file that was working correctly as of March 15 but now it gives me errors regarding credential sources for AWS Builder.
My AWS CLI profile is properly configured and I can access my AWS resources using it.

#### Reproduction Steps

1. Set-up an AWS profile called `personal`.
2. Run [this Packer file](https://github.com/da-edra/irc-bouncer/blob/master/bouncer_image.json).

### Packer version

Packer 1.6.0.

### Simplified Packer Buildfile

[Packer file](https://github.com/da-edra/irc-bouncer/blob/master/bouncer_image.json).

### Operating system and Environment details

Arch Linux, 64 bits.
AWS CLI: aws-cli/1.18.93 Python/3.8.3 Linux/5.7.7-zen1-1-zen botocore/1.17.16

### Log Fragments and crash.log files

[Log fragments](https://gist.github.com/da-edra/6489c0cf7a75e1fa8612c50f237c54b7)

**Comment by nywilken** [comment]
Thanks for reaching out. We’ll take a look when we get a chance

**Comment by da-edra** [comment]
Thanks!

**Comment by nywilken** [comment]
Hi @de-edra you mentioned that your build was working on March 15 which means you would’ve been using an older version. Have you checked that your build still works with previous versions of Packer? Maybe v1.5.4 or before. 


With that said, what happens if you remove the `”profile”` configuration option and instead set the env variable AWS_PROFILE=“personal”? Or try setting the access_key and secret_key with your credentials?

**Comment by nywilken** [comment]
Hello again, I just wanted to follow up here and say that I am unable to reproduce this issue.  I wanted to confirm that there were no regression with using the "profile" configuration option for the `amazon-ebs` builder. If using the `access_key` and `secret_key` options directly results in the same authentication issue I would check that the keys work properly for the given region you are building in. I'm keeping this open until I hear back in case I've missed anything in this issue. Cheers!

**Comment by da-edra** [comment]
hello @nywilken , thank you so much for answering and sorry for my late reply (I've been really busy with work), I'll try it out today and let you know how it works. Thank you. :)

**Comment by da-edra** [comment]
Hello @nywilken , I just tried with another AWS account and it works flawlessly so it must be something with my AWS account (a limitation or something like that).
Thanks for your help. 😄
