### ISSUE TITLE
http_ip is not documented on vsphere

### ISSUE THREAD

**Issue by jhawk28** [hashicorp/packer#9536]
the http_ip field is not documented in BootConfig

**Comment by nywilken** [comment]
Thanks for bubbling this up. I'll get a PR out for this soon.

**Comment by jhawk28** [comment]
I keep meaning to do it every time I need to confirm that it is http_ip. Then I move on to other things and forget that it needs some documentation...

**Comment by nywilken** [comment]
@jhawk28 I added documentation for the http_Ip to the boot configuration section https://deploy-preview-9538--packer-www.netlify.app/docs/builders/vmware/vsphere-iso#http_ip

Let me know if you had something else in mind.

**Comment by jhawk28** [comment]
Yep, thats pretty much it.
