### ISSUE TITLE
VSphere-iso builder: Cannot create EFI VM

### ISSUE THREAD

**Issue by raduad** [hashicorp/packer#9547]
#### Overview of the Issue

Trying to build a VSphere VM with efi (not efi-secure) firmware fails with error `Build 'vsphere-iso' errored: ServerFaultCode: 
Unexpected element tag "efiSecureBootEnabled" seen`

#### Reproduction Steps

Create packer template using vsphere-iso builder. Set firmware to `efi`. Build VM.

### Packer version

1.6.0

### Simplified Packer Buildfile

```
    "builders": [{
        "type": "vsphere-iso",
        "vcenter_server": "{{user `vsphere_server`}}",
        "username": "{{user `vsphere_username`}}",
        "password": "{{user `vsphere_password`}}",
        "insecure_connection": "true",
        "CPUs": "1",
        "cpu_cores": "1",
        "RAM": "1024",
        "firmware" : "efi",
        "vm_name": "{{user `vm_name`}}",
        "host": "{{user `esxi_host`}}",
        "datastore": "{{user `esxi_datastore`}}",
        "boot_order": "cdrom,disk",
        "shutdown_command": "sudo -S /sbin/halt -h -p",
        "iso_url": "{{user `iso_url`}}",
        "iso_checksum": "{{user `iso_checksum_type`}}:{{user `iso_checksum`}}",
        "iso_paths": [
            "[datastore1] ISO/SLES/{{user `vm_name_prefix`}}.iso"
        ],
        "vm_version": "{{user `hardware_version`}}",
        "guest_os_type": "sles12_64Guest",
        "network_adapters": [
            {
                "network": "{{user `vsphere_vm_network`}}",
                "network_card": "vmxnet3"
            }
        ],
        "storage": [
            {
                "disk_size": "{{user `disk_size`}}",
                "disk_thin_provisioned": "true"
            }
        ],
        "communicator": "ssh",
        "ssh_username": "{{user `vm_username`}}",
        "ssh_password": "{{user `vm_password`}}",
        "ssh_port": "22",
        "ssh_timeout": "40m",
        "export": {
            "name": "{{user `vm_name`}}.ova",
            "manifest": "sha1"
        }
    }]
```

### Operating system and Environment details

Red Hat Enterprise Linux Server release 7.4 (Maipo)
Linux ImageBuildEngine 3.10.0-862.11.6.el7.x86_64 #1 SMP Fri Aug 10 16:55:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

```
packr version
2020/07/08 02:51:49 [INFO] Packer version: 1.6.0 [go1.13.12 linux amd64]
2020/07/08 02:51:49 [DEBUG] Discovered plugin: amazon-ami-management = /root/.packer.d/plugins/packer-post-processor-amazon-ami-management
2020/07/08 02:51:49 [DEBUG] Discovered plugin: vmware-vmx-copy = /root/.packer.d/plugins/packer-post-processor-vmware-vmx-copy
2020/07/08 02:51:49 using external post-processors [amazon-ami-management vmware-vmx-copy]
2020/07/08 02:51:49 Checking 'PACKER_CONFIG' for a config file path
2020/07/08 02:51:49 'PACKER_CONFIG' not set; checking the default config file path
2020/07/08 02:51:49 Attempting to open config file: /root/.packerconfig
2020/07/08 02:51:49 [WARN] Config file doesn't exist: /root/.packerconfig
2020/07/08 02:51:49 Setting cache directory: /root/packer_cache
Packer v1.6.0
2020/07/08 02:51:49 machine readable: version []string{"1.6.0"}
2020/07/08 02:51:49 machine readable: version-prelease []string{""}
2020/07/08 02:51:49 machine readable: version-commit []string{"b05ca9e9e+CHANGES"}
2020/07/08 02:51:49 [INFO] (telemetry) Finalizing.
2020/07/08 02:51:50 waiting for all plugin processes to complete...
```

### Log Fragments and crash.log files

[packer with vsphere-iso builder log for efi firmware](https://gist.github.com/raduad/b7b59407d319f24668c28e5202c38751)

**Comment by jhawk28** [comment]
What version of vsphere are you using?

**Comment by raduad** [comment]
VSphere 6.0.0. build 14510545

**Comment by jhawk28** [comment]
I think the issue is due to this code: https://github.com/hashicorp/packer/blob/master/builder/vsphere/driver/vm.go#L501

I suspect that the vSphere 6.0.0 doesn't support the efi-secure flag. The vsphere-iso technically doesn't need to reconfigure the firmware since it does it in the createVM. The simplest solution may be to just set the firmware to "" the hardware config.

**Comment by jhawk28** [comment]
I'm not sure we want to fix the issue this way, but you can test to see if it works: https://app.circleci.com/pipelines/github/hashicorp/packer/6038/workflows/d9738789-5cff-4c19-a1f1-3285fc0e2b8b/jobs/65539/artifacts

**Comment by SwampDragons** [comment]
Yes, looks like this is not supported in esx 6: https://communities.vmware.com/thread/511547

**Comment by SwampDragons** [comment]
Given that the official vmware library we use (govmomi) doesn't support vSphere 6.0, I think it's not realistic for Packer to support it either. https://github.com/vmware/govmomi#compatibility

I will add a note to the docs that vSphere 6.0 is not supported.
