### ISSUE TITLE
[TencentCloud] Add support to retrieve `source_image_id` through source image filter.

### ISSUE THREAD

**Issue by jianzhiteh** [hashicorp/packer#9548]
#### Feature Description

Hi, we noticed that your module requires us to input the exact `source_image_id` when building new image. It may be troublesome in our usage as sometimes the source image we use changes quite frequently due to updates, and it involves manual retrieval of source image id through checking from the TencentCloud console. 

Not sure if it's possible for implementing a filter to retrieve the `source_image_id` based on image name (regex), type (TencentCloud / User Created), etc. Likewise we do not have to query / look for the `source_image_id` every time we try to build a new image. 

Similar implementation has been observed through AWS's packer module - https://www.packer.io/docs/builders/amazon-ebs#filters-1

#### Use Case(s)

Automatic retrieval of `source_image_id` based on input filter categories.

**Comment by SwampDragons** [comment]
cc @likexian

**Comment by likexian** [comment]
Hello @jianzhiteh 
Thanks for your advice, we will implemente it soon.

**Comment by likexian** [comment]
Hello @jianzhiteh 
This has been supported, and should be ready within next release.
Please use `source_image_name` (regexp supported)  argument for search.

**Comment by SwampDragons** [comment]
Closing since this was merged in #9619
