### ISSUE TITLE
Builder Openstack image_min_disk

### ISSUE THREAD

**Issue by possani** [hashicorp/packer#9549]
#### Overview of the Issue

Hi, I am trying to create a new image, but I am getting the following behavior:

When specifying the _image_min_disk_, I would expect to see what the [description](https://www.packer.io/docs/builders/openstack#image_min_disk) says, "Minimum disk size needed to boot image, in gigabytes"; instead, I am setting the disk size.

![Screenshot from 2020-07-08 09-44-05](https://user-images.githubusercontent.com/7349369/86892433-8bedce00-c100-11ea-89b8-5029d381c7f4.png)

_image_min_disk_ and _image_min_ram_ are not available. Instead, the current option should be named _image_size_.

It also takes a very long time to save the image, maybe due to the image size.

#### Reproduction Steps

packer build template.json

### Packer version

Packer v1.6.0

### Simplified Packer Buildfile

```
{
    "builders": [
        {
            "type": "openstack",
            "ssh_username": "ubuntu",
            "image_name": "Ubuntu-18.04-LTS-bionic-packer",
            "image_min_disk": 20,
            "source_image_name": "Ubuntu-18.04-LTS-bionic",
            "insecure": "true",
            ...
            "use_blockstorage_volume": "true"
        }
    ]
}
```

### Operating system and Environment details

NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"

**Comment by SwampDragons** [comment]
Thanks for this suggestion! 

The Openstack builder is one of our community-supported plugins, which means that the HashiCorp maintainers don't spend much engineering time on it; this means that the best way to see your suggestion make it into Packer is to open a PR. We'll gladly give support and pointers if you're interested in taking a shot at it.
