### ISSUE TITLE
PXE / Bare metal builder

### ISSUE THREAD

**Issue by silverfisk** [hashicorp/packer#955]
An idea about a bare metal builder for packer. Perhaps it would be possible to somehow integrate a PXE server or configure an external one. Something like

{
  "builders":
  [
    {
      "type": "baremetal",
      "iso_url": "http://mirror.centos.net/centos/6/isos/x86_64/CentOS-6.4-x86_64-minimal.iso",
      "iso_checksum": "4a5fa01c81cc300f4729136e28ebe600",
      "iso_checksum_type": "md5",
      "HWaddr": "11:22:00:AA:AA:AA"
   "boot_command":
      [
        "",
        " ks=http://10.0.2.2:{{ .HTTPPort }}/centos6-ks.cfg"
      ]
    }
  ]
}

**Comment by azimut** [comment]
+1

**Comment by richard-mauri** [comment]
I see this and related issues are closed.
We are tasked to use packer with bare metal so we can pre-bake like an Ubuntu 14.04 base machine image with custom packages on top, save to a repo like Artifactory and later have PXE be able to use that image. NO application package provisioning done at machine creation time; similar to how ami provisioning is done (at image build time).

Where does this stand today. I see there is some work by @vtolstov that is 2 years old. 

It seems like there are many variables that must be factored out; hostname,locale,disk partitioning etc.

I wonder if I can have a packer builder create an iso image as its artifact?

**Comment by beddari** [comment]
@richard-mauri I got some experience with this and I'd say there is no real reason (at least that I can think of) to do the build step on a physical box. So in my opinion that leaves you with a lesser problem, pxeboot a RAM based image and deploy/write a ready-made image to the box.

If starting today I'd probably go with the The Foreman discovery image as a base.

**Comment by beddari** [comment]
That being said, also probably should mention a new project I found https://github.com/danderson/pixiecore ... which looks like it could form the basis for a baremetal builder.

**Comment by richard-mauri** [comment]
Thanks @beddari 
I'll investigate your approaches, but it seems just a little off target.

Essentially, in high level terms, I want Packer to do a non GUI launch of like an Ubuntu Linux virtual machine (like it does with virtualbox-builder) and then take a path to an iso file that it loop mounts, copies to a writable location and then updates the writable location (adding packages) and then writing a new iso as the final output. Now, it seems that the bkisofs, which is at the heart of mkisofs and isomaster) can do the heavy lifting for the package addition updates. 

Perhaps I have to write a go iso-builder that calls bk.

Again the goal is a Packer template that produces AMI, Vagrant/VBox box and ISO as we will use the first two in the dev phase and the latter in the PROD phase and want the same tooling to do all the provisioning.

I hope that makes sense

**Comment by vtolstov** [comment]
I'm write my own scripts that run in provision after all things done.
One script creates tar file system, download file to host and use tar.gz via artifice to docker push
Second use mksquashfs to create squashfs that booting via pxe.
So i don't understand problems in this issue.
Create that you want inside vm, download and via artifice add this file to artifact list.

**Comment by zrml** [comment]
Any news on this? @richard-mauri: did you ever write anything for bare metal provisioning as yo udescribed?
thanks

**Comment by beddari** [comment]
If all you want to do is just input an iso, modify it, then output a new one ... @vtolstov is right on

1) Boot any VM
2) Download any iso inside that VM and modify it as needed, using any tooling you'd like
3) Use the artifice post-processor https://www.packer.io/docs/post-processors/artifice.html to override the artifact list, thus the build output will be your modified iso

In any case, that is not what this issue originally was about and I think I'm done, good luck :)

**Comment by openface** [comment]
@beddari this is exactly the workflow I'm looking to achieve with Packer.  Do you know of any tutorials or snippets that would help a newcomer, such as myself, put this together?

**Comment by fxfitz** [comment]
@beddari @openface: I'm in the exact same boat. Any leads?

**Comment by viralpoetry** [comment]
@openface @fxfitz 
This is quite old issue, but I partially solved this problem for my use case here:
https://github.com/viralpoetry/packer-bare-metal

Hope that it helps somebody.

**Comment by fxfitz** [comment]
Thanks @viralpoetry!

**Comment by saurabhvashisht** [comment]
@viralpoetry  have you ever done the packer thing on windows 7 image or anyone else
 have done it? I have a urgent need for this

**Comment by saurabhvashisht** [comment]
@vtolstov is it possible to share your script with me as I have very similar requirement

**Comment by vtolstov** [comment]
very simple: install all needed stuff inside vm (for debian live-boot, for fedora/centos dracut with ability to boot from net).
after sthat packer run script (example for debian):
```
#!/bin/sh -ex

apt-get -y install squashfs-tools

mkdir -p /mnt/squashfs /squashfs
mount -o bind / /mnt/squashfs

mksquashfs /mnt/squashfs /squashfs/filesystem.squashfs -comp gzip -no-exports -xattrs -noappend -no-recovery -e /mnt/squashfs/squashfs/filesystem.squashfs
find /boot -name 'vmlinuz-*' -type f -exec cp {} /squashfs/vmlinuz \;
find /boot -name 'init*' -type f -exec cp {} /squashfs/initrd.img \;
```

and in packer download artifacts from vm:
```
    {
      "type": "file",
      "direction": "download",
      "sources": [
        "/squashfs/vmlinuz"
      ],
      "destination": "output/{{user `name`}}-squashfs/{{user `name`}}.vmlinuz"
    },
    {
      "type": "file",
      "direction": "download",
      "sources": [
        "/squashfs/initrd.img"
      ],
      "destination": "output/{{user `name`}}-squashfs/{{user `name`}}.initrd"
    },
    {
      "type": "file",
      "direction": "download",
      "sources": [
        "/squashfs/filesystem.squashfs"
      ],
      "destination": "output/{{user `name`}}-squashfs/{{user `name`}}.squashfs"
    }
```

**Comment by adam-erickson** [comment]
Sorry, but can anybody explain these answers more clearly for a n00b?

**Comment by vtolstov** [comment]
if you combine you question, we can answer it. bare metal is very specific, somebody needs pxe boot, somebody need installer. May be some of users uses rpm-ostree.... =))

**Comment by adespain** [comment]
What do you do with the artifacts?  I'm also a confused n00b on how to implement this so the hardware will boot with the packer image...

**Comment by eduncan911** [comment]
@adespain PXE boot means you setup your DHCP server to answer queries on your network.  This usually involves setting up a TFTP server to host the "artifacts" you build with packer per the processes above.

You configure the remote machine for PXE boot in the BIOS, which will boot and use PXE to ask the DHCP server for an IP and usually includes the PXE instructions to pull an image from and boot it.

DNSmasq is a good bit easier to configure for this since it does both dhcp and dns, and allows for PXE configuration.  You only need to setup an tftp server and be done.

Read up on PXE boot and where to put the images, aka artifacts.

**Comment by adespain** [comment]
Is there a way to not use pxe boot and just install the packer created image from a usb drive or something?

**Comment by rubu** [comment]
I followed the excellent points from @vtolstov here, but as many others I needed to make an ISO for UEFI HTTP boot. I followed the instructions from https://willhaley.com/blog/custom-debian-live-environment/, to make an ISO but it fails to boot (I formulated a question on Server Fault with all the steps - https://serverfault.com/questions/999778/booting-a-squashed-filesystem-from-iso). 

Can anyone explain to me as person which is not that familiar with grub and linux boot process, what am I missing here (since I obviously feel like I am :D). Do I need something in the boot chain (dracut?) that will do smth to load the squashfs and launch the actual OS or is this just a grub configuration issue?

**Comment by rubu** [comment]
So, going through all the stuff on Google, I actually moved a lot forward (leaving this here so that int future anyone who stumbles on this can get through:D):

So in the provision script I added:
```
dracut -a dmsquash-live -N -m "kernel-modules base" --filesystems "squashfs" /dracut/initrd.dracut.img
```

And I put this initrd (not the one from the original system) in the ISO and use dracut parameters `root=live` in the grub boot entry:
```
menuentry "Custom Linux" {
    linux /vmlinuz root=live:/dev/sr0 rd.live.debug=1
    initrd /initrd.img
}
```

So this at least seems to boot the squash fs, but now I get 
```
Warning: /dev/mapper/live-rw does not exist
```
so back to Google
