### ISSUE TITLE
Packer cannot wait for instance to be stopped

### ISSUE THREAD

**Issue by zr5849373** [hashicorp/packer#9562]
Hi:
 I encountered a problem. when i create a ami on aws,first packer will stop the instance and then copy the instance to a ami.but when packer stop the instance ,the instance will cost more than  five mins to stop. then i see that packer show error that "Error creating AMI: InvalidParameterValue: Invalid value 'i-05348a0d76476e460' for instanceId. Instance is not in state 'running' or 'stopped'
==> amazon-ebs: 	status code: 400, request id: *****".
so if there is a parameter to change the timeout value when packer wait for instance to be stop

below is the part of log:

2020/07/10 13:19:57 [INFO] (telemetry) ending shell
==> amazon-ebs: Stopping the source instance...
    amazon-ebs: Stopping instance
==> amazon-ebs: Waiting for the instance to stop...
==> amazon-ebs: Creating AMI test from instance i-05348a0d76476e460
==> amazon-ebs: 	status code: 400, request id: e1f57d04-c22b-4d2f-b50a-409fea3b1194
==> amazon-ebs: Error creating AMI: InvalidParameterValue: Invalid value 'i-05348a0d76476e460' for instanceId. Instance is not in state 'running' or 'stopped'
==> amazon-ebs: 	status code: 400, request id: e1f57d04-c22b-4d2f-b50a-409fea3b1194
==> amazon-ebs: Provisioning step had errors: Running the cleanup provisioner, if present...
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Cleaning up any extra volumes...
==> amazon-ebs: Destroying volume (vol-08a79b5bd61897fd6)...
==> amazon-ebs: Deleting temporary security group...
2020/07/10 13:26:35 [INFO] (telemetry) ending amazon-ebs
	status code: 400, request id: e1f57d04-c22b-4d2f-b50a-409fea3b1194
2020/07/10 13:26:35 machine readable: error-count []string{"1"}
==> Some builds didn't complete successfully and had errors:
2020/07/10 13:26:35 machine readable: amazon-ebs,error []string{"Error creating AMI: InvalidParameterValue: Invalid value 'i-05348a0d76476e460' for instanceId. Instance is not in state 'running' or 'stopped'\n\tstatus code: 400, request id: e1f57d04-c22b-4d2f-b50a-409fea3b1194"}
	status code: 400, request id: e1f57d04-c22b-4d2f-b50a-409fea3b1194
==> Builds finished but no artifacts were created.
2020/07/10 13:26:35 [INFO] (telemetry) Finalizing.
Build 'amazon-ebs' errored: Error creating AMI: InvalidParameterValue: Invalid value 'i-05348a0d76476e460' for instanceId. Instance is not in state 'running' or 'stopped'
	status code: 400, request id: e1f57d04-c22b-4d2f-b50a-409fea3b1194

**Comment by sylviamoss** [comment]
Hey there! Thanks for reaching out. Could you provide a minimal template to let us help reproduce and understand better what is going on?

**Comment by zr5849373** [comment]
Below is last part of our sh script:
export AWS_SOURCE_AMI=$ami_id
   ../common/ami/packer build ../common/ami/aws_ami_ova.json
just use packer to generate a ami

after packer execute the script of json.packer will stop the packer instance,then packer will copy the instance to a ami.
but during wait for instance to be stopped.i can see that the status of instance is shutting down,but not stopped.
my instance type is c5n.metal and shutdown will cost much time,at least more than 5 mins.
below is part of the debug log:

    amazon-ebs: UPDATE 17
    amazon-ebs: UPDATE 8
    amazon-ebs: UPDATE 1
    amazon-ebs: UPDATE 1
    amazon-ebs: UPDATE 1
    amazon-ebs: Step 7: Hotfix Setting
    amazon-ebs: Step 8: Change submit quota
    amazon-ebs: UPDATE 1
    amazon-ebs: Step 9: Active License
    amazon-ebs: {"@location":"\/pages\/enforce_change_password.php","@auto_logout_other_sessions":"false","@is_master":1,"@status":"INFO.OK.0000"}
    amazon-ebs:   "@status": "INFO.OK.0000",
2020/07/10 15:34:35 packer-builder-amazon-ebs plugin: [INFO] RPC endpoint: Communicator ended with: 0
2020/07/10 15:34:35 [INFO] 573 bytes written for 'stderr'
2020/07/10 15:34:35 [INFO] 10219064 bytes written for 'stdout'
2020/07/10 15:34:35 [INFO] RPC client: Communicator ended with: 0
2020/07/10 15:34:35 [INFO] RPC endpoint: Communicator ended with: 0
2020/07/10 15:34:35 packer-provisioner-shell plugin: [INFO] 10219064 bytes written for 'stdout'
2020/07/10 15:34:35 packer-provisioner-shell plugin: [INFO] 573 bytes written for 'stderr'
2020/07/10 15:34:35 packer-provisioner-shell plugin: [INFO] RPC client: Communicator ended with: 0
2020/07/10 15:34:35 packer-builder-amazon-ebs plugin: [DEBUG] Opening new ssh session
2020/07/10 15:34:35 packer-builder-amazon-ebs plugin: [DEBUG] starting remote command: rm -f /tmp/script_6250.sh
2020/07/10 15:34:36 packer-builder-amazon-ebs plugin: [INFO] RPC endpoint: Communicator ended with: 0
2020/07/10 15:34:36 [INFO] RPC client: Communicator ended with: 0
2020/07/10 15:34:36 [INFO] RPC endpoint: Communicator ended with: 0
2020/07/10 15:34:36 packer-provisioner-shell plugin: [INFO] RPC client: Communicator ended with: 0
2020/07/10 15:34:36 packer-builder-amazon-ebs plugin: [DEBUG] Opening new ssh session
2020/07/10 15:34:36 packer-builder-amazon-ebs plugin: [DEBUG] starting remote command: rm -f
2020/07/10 15:34:36 packer-builder-amazon-ebs plugin: [INFO] RPC endpoint: Communicator ended with: 0
2020/07/10 15:34:36 [INFO] RPC client: Communicator ended with: 0
2020/07/10 15:34:36 [INFO] RPC endpoint: Communicator ended with: 0
2020/07/10 15:34:36 packer-provisioner-shell plugin: [INFO] RPC client: Communicator ended with: 0
2020/07/10 15:34:36 [INFO] (telemetry) ending shell
==> amazon-ebs: Stopping the source instance...
    amazon-ebs: Stopping instance
==> amazon-ebs: Waiting for the instance to stop...
==> amazon-ebs: Creating AMI test from instance i-0dfeb326a14cb2aa4
==> amazon-ebs: 	status code: 400, request id: 75605ac9-7939-4040-a0ed-c51dbbe421d8
==> amazon-ebs: 	status code: 400, request id: 75605ac9-7939-4040-a0ed-c51dbbe421d8
==> amazon-ebs: Error creating AMI: InvalidParameterValue: Invalid value 'i-0dfeb326a14cb2aa4' for instanceId. Instance is not in state 'running' or 'stopped'
==> amazon-ebs: 	status code: 400, request id: 75605ac9-7939-4040-a0ed-c51dbbe421d8
==> amazon-ebs: Error creating AMI: InvalidParameterValue: Invalid value 'i-0dfeb326a14cb2aa4' for instanceId. Instance is not in state 'running' or 'stopped'
==> amazon-ebs: 	status code: 400, request id: 75605ac9-7939-4040-a0ed-c51dbbe421d8
==> amazon-ebs: Step "stepCreateAMI" failed, aborting...
==> amazon-ebs: aborted: skipping cleanup of step "StepDeregisterAMI"
==> amazon-ebs: aborted: skipping cleanup of step "StepModifyEBSBackedInstance"
==> amazon-ebs: aborted: skipping cleanup of step "StepStopEBSBackedInstance"
==> amazon-ebs: aborted: skipping cleanup of step "StepCleanupTempKeys"
==> amazon-ebs: aborted: skipping cleanup of step "StepProvision"
==> amazon-ebs: aborted: skipping cleanup of step "StepConnect"
==> amazon-ebs: aborted: skipping cleanup of step "StepGetPassword"
==> amazon-ebs: aborted: skipping cleanup of step "StepRunSourceInstance"
==> amazon-ebs: aborted: skipping cleanup of step "StepCleanupVolumes"
==> amazon-ebs: aborted: skipping cleanup of step "StepIamInstanceProfile"
2020/07/10 15:40:04 [INFO] (telemetry) ending amazon-ebs
	status code: 400, request id: 75605ac9-7939-4040-a0ed-c51dbbe421d8
2020/07/10 15:40:04 machine readable: error-count []string{"1"}
==> Some builds didn't complete successfully and had errors:
2020/07/10 15:40:04 machine readable: amazon-ebs,error []string{"Error creating AMI: InvalidParameterValue: Invalid value 'i-0dfeb326a14cb2aa4' for instanceId. Instance is not in state 'running' or 'stopped'\n\tstatus code: 400, request id: 75605ac9-7939-4040-a0ed-c51dbbe421d8"}
	status code: 400, request id: 75605ac9-7939-4040-a0ed-c51dbbe421d8
==> Builds finished but no artifacts were created.
2020/07/10 15:40:04 [INFO] (telemetry) Finalizing.
==> amazon-ebs: aborted: skipping cleanup of step "StepSecurityGroup"
==> amazon-ebs: aborted: skipping cleanup of step "StepKeyPair"
==> amazon-ebs: aborted: skipping cleanup of step "StepNetworkInfo"
==> amazon-ebs: aborted: skipping cleanup of step "StepSourceAMIInfo"
==> amazon-ebs: aborted: skipping cleanup of step "StepPreValidate"
Build 'amazon-ebs' errored: Error creating AMI: InvalidParameterValue: Invalid value 'i-0dfeb326a14cb2aa4' for instanceId. Instance is not in state 'running' or 'stopped'
	status code: 400, request id: 75605ac9-7939-4040-a0ed-c51dbbe421d8

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Error creating AMI: InvalidParameterValue: Invalid value 'i-0dfeb326a14cb2aa4' for instanceId. Instance is not in state 'running' or 'stopped'
	status code: 400, request id: 75605ac9-7939-4040-a0ed-c51dbbe421d8

**Comment by HTTP500** [comment]
We encountered the same issue and we are using EC2 metal as well (m5.metal)

`
{
  "variables": {
    "aws_access_key": "{{env `AWS_ACCESS_KEY_ID`}}",
    "aws_secret_key": "{{env `AWS_SECRET_ACCESS_KEY`}}",
    "aws_session_token": "{{env `AWS_SESSION_TOKEN`}}",
    "source_ami_name": "{{env `SOURCE_AMI_NAME`}}",
    "source_ami_username": "{{env `SOURCE_AMI_USERNAME`}}"
  },
  "builders": [
    {
      "type": "amazon-ebs",
      "name": "ami",
      "access_key": "{{user `aws_access_key`}}",
      "secret_key": "{{user `aws_secret_key`}}",
      "token": "{{user `aws_session_token`}}",
      "region": "us-west-2",
      "source_ami": "xxx",
      "instance_type": "m5.metal",
      "iam_instance_profile": xxx
      "vpc_id": "vpc-xxx",
      "subnet_id": "subnet-xxx",
      "ssh_username": "{{user `source_ami_username`}}",
      "ssh_clear_authorized_keys": true,
      "ssh_timeout": "30m",
      "ami_name": "xxx",
      "launch_block_device_mappings": [
        {
          "device_name": "/dev/sda1",
          "volume_size": 60,
          "volume_type": "gp2",
          "delete_on_termination": true
        }
      ],
      "temporary_security_group_source_cidrs": [
        "10.0.0.0/8"
      ]
    }
  ],
  "provisioners": [
    {
      "type": "ansible",
      "playbook_file": "xxx",
      "extra_arguments": [
        "-vvv"
      ]
    }
  ],
  "post-processors": [
    {
      "type": "manifest",
      "output": "manifest.json"
    }
  ]
}`

**Comment by zr5849373** [comment]
I used the latest packer 1.6.0

**Comment by SwampDragons** [comment]
If you set these environment variables, Packer will wait longer: https://www.packer.io/docs/builders/amazon#aws_max_attempts

Please note that these override variables are used for all polling that Packer does, so make sure they are set to a high value.

**Comment by HTTP500** [comment]
@SwampDragons Thanks for replying!

Tried setting `AWS_MAX_ATTEMPTS = 100` and `AWS_POLL_DELAY_SECONDS = 20` with no luck

I wonder if this error is not related to those mentioned in https://www.packer.io/docs/builders/amazon#aws_max_attempts

From https://github.com/hashicorp/packer/blob/master/builder/amazon/common/step_stop_ebs_instance.go#L73 it seems that Packer continued code execution since no error was returned from `ec2conn.WaitUntilInstanceStoppedWithContext()`, however for some reason the instance is still not ready

So it will hit https://github.com/hashicorp/packer/blob/master/builder/amazon/ebs/step_create_ami.go#L53, which has nothing to do with those 2 env vars

**Comment by SwampDragons** [comment]
You're right. The code in step_stop_ebs_instance should be ensuring that the instance is stopped, so I wonder if this is an eventual consistency problem. We should probably put that CreateImage call inside a retry. I'll write up a patch to test.

**Comment by SwampDragons** [comment]
Test builds of the fix can be found here: https://circleci.com/gh/hashicorp/packer/66818#artifacts/containers/0
