### ISSUE TITLE
sync_folder leads to "syntax error" report for vagrant builder

### ISSUE THREAD

**Issue by john-forrest** [hashicorp/packer#9564]
#### Overview of the Issue

I am trying to use the vagrant builder with virtualbox instead of the "classic approach" of building ubuntu or whatever from the iso image. This seemingly works until I try and use sync_folder to map a host folder into my environment. I can see this in the doc, although have yet to see what claims to be a working example, so could be I am missing something. If it were that I was missing something, that would imply the doc could be updated.

I suspect the error is coming from vagrant but I am assuming the issue is in packer for now - difficult to tell.

Issue seen is:
vagrant: strconv.Atoi: parsing "": invalid syntax

Mergely removing the "sync_folder" entry removes this issue, but of course does not map the folder as required.

#### Reproduction Steps

I've cut this down from my original to a fairly simple (I believe) example. 

* See attached .zip file and unzip. 
* Go to directory problem-packer2
* Run: packer build --only=vagrant --force --on-error=abort vagrant-builder-example.json

### Packer version

Packer v1.6.0

### Simplified Packer Buildfile

{
        "builders": [
                {
                "type": "vagrant",
                "communicator": "ssh",
                "source_path": "ubuntu/bionic64",
                "add_force": true,
                "provider": "virtualbox",
                "box_name": "problem",
                "synced_folder": "foo"
                }
        ],
        "provisioners": [
                {
                        "type": "shell",
                        "scripts": ["scripts/basic_install.sh"]
                }
        ]
}

### Operating system and Environment details

Vagrant 2.2.9
Virtual Box 6.1
Windows 10 1909

### Log Fragments and crash.log files

==> vagrant: Deleting previous output directory...
==> vagrant: Creating a Vagrantfile in the build directory...
==> vagrant: Adding box using vagrant box add ...
    vagrant: (this can take some time if we need to download the box)
==> vagrant: Calling Vagrant Up (this can take some time)...
==> vagrant: strconv.Atoi: parsing "": invalid syntax
==> vagrant: Step "StepSSHConfig" failed, aborting...
==> vagrant: aborted: skipping cleanup of step "StepUp"
==> vagrant: aborted: skipping cleanup of step "StepAddBox"
==> vagrant: aborted: skipping cleanup of step "StepCreateVagrantfile"
==> vagrant: aborted: skipping cleanup of step "StepOutputDir"
Build 'vagrant' errored: strconv.Atoi: parsing "": invalid syntax

==> Some builds didn't complete successfully and had errors:
--> vagrant: strconv.Atoi: parsing "": invalid syntax

==> Builds finished but no artifacts were created.

**Comment by john-forrest** [comment]
Forgot to attach .zip
[problem-packer2.zip](https://github.com/hashicorp/packer/files/4906842/problem-packer2.zip)

**Comment by SwampDragons** [comment]
I can only reproduce this if the "foo" directory doesn't exist, and then when I enable verbose logging I see: 

```2020/07/14 11:25:56 packer-builder-vagrant plugin: Calling Vagrant CLI: []string{"up", "source", "--provider=virtualbox"}
2020/07/14 11:25:58 packer-builder-vagrant plugin: [vagrant driver] stdout: Bringing machine 'source' up with 'virtualbox' provider...
2020/07/14 11:25:58 packer-builder-vagrant plugin: [vagrant driver] stderr: There are errors in the configuration of this machine. Please fix
2020/07/14 11:25:58 packer-builder-vagrant plugin: [vagrant driver] stderr: the following errors and try again:
2020/07/14 11:25:58 packer-builder-vagrant plugin: [vagrant driver] stderr:
2020/07/14 11:25:58 packer-builder-vagrant plugin: [vagrant driver] stderr: vm:
2020/07/14 11:25:58 packer-builder-vagrant plugin: [vagrant driver] stderr: * The host path of the shared folder is missing: foo
2020/07/14 11:25:58 packer-builder-vagrant plugin: [vagrant driver] stderr:
2020/07/14 11:25:58 packer-builder-vagrant plugin: Calling Vagrant CLI: []string{"ssh-config", "source"}
2020/07/14 11:26:00 packer-builder-vagrant plugin: [vagrant driver] stderr: The provider for this Vagrant-managed machine is reporting that it
2020/07/14 11:26:00 packer-builder-vagrant plugin: [vagrant driver] stderr: is not yet ready for SSH. Depending on your provider this can carry
2020/07/14 11:26:00 packer-builder-vagrant plugin: [vagrant driver] stderr: different meanings. Make sure your machine is created and running and
2020/07/14 11:26:00 packer-builder-vagrant plugin: [vagrant driver] stderr: try again. Additionally, check the output of `vagrant status` to verify
2020/07/14 11:26:00 packer-builder-vagrant plugin: [vagrant driver] stderr: that the machine is in the state that you expect. If you continue to
2020/07/14 11:26:00 packer-builder-vagrant plugin: [vagrant driver] stderr: get this error message, please view the documentation for the provider
2020/07/14 11:26:00 packer-builder-vagrant plugin: [vagrant driver] stderr: you're using.
==> vagrant: destroying Vagrant box...```

**Comment by SwampDragons** [comment]
I'll add prepare() code to stat this path and make sure it exists

**Comment by john-forrest** [comment]
Is the path relative to the vagrant output folder,  so where the Vagrantfile will be, or the packer template?

**Comment by SwampDragons** [comment]
Hm, I just gave the absolute path. In most of our other conventions relative path should be relative to the folder you run Packer from, so I'll check my fix to make sure it also expects that.

**Comment by john-forrest** [comment]
If I change the entry to "../foo" that works, but that is relative to the Vagrantfile and not what I'd expect.

**Comment by SwampDragons** [comment]
I'll fix that now.

**Comment by SwampDragons** [comment]
ok pushed an updated patch to document how relative paths should work, and make it so the expected relative path is relative to the folder running packer not the vagrantfile folder.

**Comment by SwampDragons** [comment]
Bins can be grabbed here: https://circleci.com/gh/hashicorp/packer/66652#artifacts/containers/0
