### ISSUE TITLE
Support for chef-zero provisioner?

### ISSUE THREAD

**Issue by JeanMertz** [hashicorp/packer#958]
I was wondering if Packer can support [chef-zero](https://github.com/opscode/chef-zero) as a provisioner.

Chef-zero is actually implemented in chef-client [since a recent version](using the `-z` flag), so maybe all that is really needed is to make it more accessible by defining a `chef_zero: true` config variable to enable the `-z` flag on the command (as opposed to manually overriding the exec command).

I haven't started using the `chef-client` provisioner yet (waiting for a new release), but I will certainly try this out once it's released. Might be a nice addition so the Chef scripts fully support data bags and search functionality, without having to actually register with a chef server node.

One concern (which I haven't looked into yet) is that chef-zero is more like chef-solo, where it requires the cookbooks and data bags to be physically available on the node, this is more in-line with the `chef-solo` configuration variables in Packer, but the functionality is 
more in-line with chef-client.

Would adding a third provisioner make sense? Or maybe add more options to the chef-client provisioner to point to local data bags / environments / nodes?

**edit:** re-reading my comments, it might be better to test this _before_ a new release, because it might require more config variables to be added to the chef-client provisioner.

**edit 2:** the chef-client config would need to allow for the following options:

```
chef_zero_mode true/false
clients_path
cookbooks_path
data_bags_path
environments_path
nodes_path
roles_path
users_path
encrypted_data_bag_secret_path
```

Looking at [the current chef-client documentation](https://github.com/mitchellh/packer/blob/master/website/source/docs/provisioners/chef-client.html.markdown) none of these are currently available (obviously), but most are available in the chef-solo config, so it'd be easy to port them over.

**Comment by jhmartin** [comment]
For future reference, it is now also required to add skip_clean_client: true  to the chef-client provisioner in addition to the existing skip_clean_node.

**Comment by icberg7** [comment]
FYI there is also a `--recipe-url=RECIPE_URL` command line option to chef-client, which will cause chef to directly download a tarball of cookbooks (e.g. from a `berks package`). This will allow you to skip the `file` provisioner.
https://docs.chef.io/ctl_chef_client.html

**Comment by yoshiwaan** [comment]
I can't find anything else on this, so might as well ask here. Wouldn't it be easier to use the chef-solo provisioner, as that already has options to upload all the necessary directories, and then just change the execute_command on that so that it runs chef-client local mode instead?
Does that not work?

**Comment by icberg7** [comment]
This might be possible. However, for the chef-client provisioner, you normally have to specify a `"server_url": "http://localhost:8889"` option, which is not available with the `chef-solo` provisioner. I believe that's used as a value in the configuration template, however you might be able to use the `-s` switch on the `chef-client` command line to override what gets written to the config file.

**Comment by yoshiwaan** [comment]
In my experience you don't need to specify a server_url when running local mode as it automatically runs and populates a chef-zero instances to connect to using the default http://localhost:8889.

The link below also specifies you only need a cookbooks directory for local mode to define the correct chef repo path:
https://docs.chef.io/ctl_chef_client.html#run-in-local-mode

I'll give it a go when I have some free time but I was hoping someone else had already done it. It seems a little clunky having to push all the files using file provisioners when using the chef-client method.
