### ISSUE TITLE
amazon-import - improvement

### ISSUE THREAD

**Issue by Roxyrob** [hashicorp/packer#9582]
#### Feature Description

amazon-import supporting "import-snapshot" (ami import passing through snapshot.).

#### Use Case(s)

I know support from vendor is important, this case can be an exception. AWS is not declaring support for kernel version present in many new OS (CentOS 8, Fedora 31, ...) and stop vmimport task on ami import stage with error: " Unable to determine kernel version" (see #8302 from where we start to search for a solution/workaround).

AWS does not stop however import task as snapshot (instead ami directly). We succesfully reach a working CentOS8 custom AMI manually starting from an virtualbox ova e.g created with packer virtualbox-iso

* extracting VMDK inside ova (tar -xvf packer-centos8min-x86_64.ova)
* uploading vmdk (aws s3 cp ...)
* importing VMDK to aws as "snapshot" (aws ec2 import-snapshot...)
* Creating AMI from snapshot (aws ec2 register-image...)

ova was made using packer provisioned to set right iniramfs with needed modules to allow root device discovery on boot stages for xen-base es2 instances (xen-blkfront), nitro-based ec2 instances (nvme, ena).

It would be nice if amazon-import can support import-snapshot (using VMDK in ova) automating all image creation steps useful to make custom image of new OS release (when kernel version is not yet supported by AWS as often it is a long time lack).

**Comment by SwampDragons** [comment]
This seems reasonable. Thanks for the suggestion!

**Comment by mdunc** [comment]
This would be useful for us as well.  FWIW though, Amazon finally allows imports of CentOS 8.2 VMs so there's no longer a need to do the manual steps of tweaking initramfs.

**Comment by Roxyrob** [comment]
Hi @mdunc,
I seen AWS supported OS for vmimport now comprise CentOS 8.0 and 8.2:

[VM Import/Export Requirements](https://docs.aws.amazon.com/vm-import/latest/userguide/vmie_prereqs.html)

probably AWS updated this in the very last days as last week max supported CentOS was CentOS7 and we tested 8.2 with usual error.

Actually the problem is not manual tweaking with **initramfs** (always needed as CentOS 8.2 installation does not include by default all you need in initramfs automatically: e.g. nvme, so can be introduced aws specific provisioning step to do that), but are the **kernel checks executed by AWS** at **import ami** stage, returning well-known "**Unable to determine kernel version**".

I agree with you: for this aws issue nature, requested improvement would be useful for future CentOS/RHEL releases and for other distros not yet supported too (e.g Fedora - with its frequent release cycle).
