### ISSUE TITLE
skip post-processor if packer run is canceled

### ISSUE THREAD

**Issue by mitchellmaler** [hashicorp/packer#9588]
#### Feature Description

Currently when I cancel a build it will run my post processor. Since the build never finishes or starts depending on when I cancel it the post-processor scripts fail. My request is to have a way to skip my post processors on specific event like a build error or packer cancel. Another useful thing would be to inject an env var to the called processors that say if the current status if canceling or running that way my script logic can just end since it will fail.

#### Use Case(s)

I provided use cases above but the main goal is to avoid failed post-processor on a cancel event.

**Comment by SwampDragons** [comment]
Can you please share your packer template so we can reproduce?

**Comment by dingus9** [comment]
:+1:
