### ISSUE TITLE
Packer not cleaning up. Azure Image Gallery

### ISSUE THREAD

**Issue by neilhwatson** [hashicorp/packer#9615]
#### Overview of the Issue

Packer leaves behind an interim image (managed_image_name) and sometimes VM resources. Seems to be related to using a pre-existing Azure resource group instead of the auto-generated one.

#### Reproduction Steps

```packer build -var "image_version=${IMAGE_VERSION}" -parallel-builds=2 linux.json```

### Packer version

Packer 1.6.0 found on Github runners: https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu2004-README.md

### Simplified Packer Buildfile

```json
{
   "variables": {
      "image_version": "",
      "subscription_id": "{{ env `AZURE_INFRA_SUBSCRIPTION_ID` }}",
      "client_id": "{{ env `AZURE_INFRA_CLIENT_ID` }}",
      "client_secret": "{{ env `AZURE_INFRA_CLIENT_SECRET` }}",
      "location": "eastus2",
      "regions" : "eastus2,westus2"
   },
   "builders": [{
      "type": "azure-arm",
      "subscription_id": "{{ user `subscription_id` }}",
      "client_id": "{{ user `client_id` }}",
      "client_secret": "{{ user `client_secret` }}",

      "shared_image_gallery_timeout": "20m",
      "shared_image_gallery_destination": {
         "resource_group": "{{ user `location` }}_gdo_image_library",
         "gallery_name": "gdo_image_library",
         "image_name": "linux-github-runner",
         "image_version": "{{ user `image_version` }}",
         "replication_regions": "{{ user `regions` }}"
      },
      "managed_image_name": "linux-github-runner",
      "managed_image_resource_group_name": "{{ user `location` }}_gdo_image_library",
      "build_resource_group_name": "{{ user `location` }}_gdo_image_library",

      "os_type": "Linux",
      "image_publisher": "Canonical",
      "image_offer": "UbuntuServer",
      "image_sku": "18.04-LTS",

      "vm_size": "Standard_DS2_v2"
   }
   ]
}
```

### Operating system and Environment details

https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu2004-README.md

### Log Fragments and crash.log files

```
==> azure-arm: Running builder ...
==> azure-arm: Getting tokens using client secret
==> azure-arm: Getting tokens using client secret
azure-arm: Creating Azure Resource Manager (ARM) client ...
Build 'azure-arm' errored: the managed image named linux-github-runner already exists in the resource group eastus2_gdo_image_library, use the -force option to automatically delete it.
==> Some builds didn't complete successfully and had errors:
--> azure-arm: the managed image named linux-github-runner already exists in the resource group eastus2_gdo_image_library, use the -force option to automatically delete it.
```

**Comment by MSBrett** [comment]
I was able to repro this too.  
The -force option wasn't deleting the managed image so I had to delete it.

**Comment by neilhwatson** [comment]
> I was able to repro this too.
> The -force option wasn't deleting the managed image so I had to delete it.

My expectation is that -force is used to overwrite the image version.  This lingering image is something that should always be removed and -force should not be required.

**Comment by wenesak** [comment]
I been having the same issue seems like the shared image needs to be deleted as part of the post packer run cleanup.

**Comment by peterlindsten** [comment]
Using -force is causing the OLD image to be published to the shared image gallery under a new name for me (at least some of the time) - so this is not a good workaround.

I've verified this by starting a VM from the managed (interim) image which has new changes, but the SIG version does not.
