### ISSUE TITLE
--> vsphere-iso: Timeout waiting for IP.

### ISSUE THREAD

**Issue by zhongc-jiang** [hashicorp/packer#9620]
I can't get the IP. Should I configure or add something else ?

Configuration is as follows:

{
  "builders": [
    {
      "type": "vsphere-iso",

     "vcenter_server":      "*.*.*.*",
      "username":            "ad****@***.com",
      "password":            "********",
	  
      "insecure_connection": "true",
	  "datacenter": "Datacenter",

      "vm_name": "packer-example-unbantu",
	  "host": "43.254.45.38",

      "guest_os_type": "centos7_64Guest",

	  "communicator": "ssh",
      "ssh_username": "root",
      "ssh_password": "password",

      "CPUs":             1,
      "RAM":              1024,
      "RAM_reserve_all": true,

	  "storage": [
		  {
		    "disk_size": 32768,
		    "disk_thin_provisioned": true
		  }
	  ],
		"network_adapters": [
			{
			 "network": "VM Network",
			  "network_card": "vmxnet3"
			}
		],

      "iso_paths": [
        "[datastore1] ISO/CentOS-7-x86_64-Minimal-1611.iso"
		
      ],
	  "floppy_files": [
        "{{template_dir}}/preseed.cfg"
      ], 
      "boot_command": [
         "<enter><wait><f6><wait><esc><wait>",
        "<bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>",
        "<bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>",
        "<bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>",
        "<bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>",
        "<bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>",
        "<bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>",
        "<bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>",
        "<bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>",
        "<bs><bs><bs>",
        " priority=critical",
        "/install/vmlinux",
        " initrd=/install/initrd.gz",
        " priority=critical",
        " locale=zh_CN",
        " file=/media/preseed.cfg",
        "<enter>"
      ]
    }
  ],

  "provisioners": [
    {
      "type": "shell",
      "inline": ["ls /"]
    }
  ]
}

Run the following:

==> vsphere-iso: Creating VM...
==> vsphere-iso: Customizing hardware...
==> vsphere-iso: Mounting ISO images...
==> vsphere-iso: Creating floppy disk...
    vsphere-iso: Copying files flatly from floppy_files
    vsphere-iso: Copying file: D:\helloWorldTools\packer\1.6.0/preseed.cfg
    vsphere-iso: Done copying files from floppy_files
    vsphere-iso: Collecting paths from floppy_dirs
    vsphere-iso: Resulting paths from floppy_dirs : []
    vsphere-iso: Done copying paths from floppy_dirs
==> vsphere-iso: Uploading created floppy image
==> vsphere-iso: Adding generated Floppy...
==> vsphere-iso: Set boot order temporary...
==> vsphere-iso: Power on VM...
==> vsphere-iso: Waiting 10s for boot...
==> vsphere-iso: Typing boot command...
==> vsphere-iso: Waiting for IP...
==> vsphere-iso: Timeout waiting for IP.
==> vsphere-iso: Clear boot order...
==> vsphere-iso: Power off VM...
==> vsphere-iso: Deleting Floppy image ...
==> vsphere-iso: Destroying VM...
Build 'vsphere-iso' errored: Timeout waiting for IP.

==> Some builds didn't complete successfully and had errors:
--> vsphere-iso: Timeout waiting for IP.

==> Builds finished but no artifacts were created.

**Comment by ljkimmel** [comment]
@zhongc-jiang -- I see that you are using the CentOS minimal ISO which, I'm pretty sure, does not include open-vm-tools. You need VMware tools installed to detect the IP address when the system comes online. I like to use the full DVD installer but select the \@minimal package group and also add the 'open-vm-tools' package to be installed during kickstart.

**Comment by SwampDragons** [comment]
Looks like this is a configuration issue rather than a Packer bug, so I'm going to close this. 

If you're struggling to get Packer working for the first time, I'd recommend reaching out to the [community forum](https://discuss.hashicorp.com/c/packer) for help.
