### ISSUE TITLE
vSphere force doesn't work if VM is powered on

### ISSUE THREAD

**Issue by mitchellmaler** [hashicorp/packer#9621]
#### Overview of the Issue

This issue is the same reported at https://github.com/jetbrains-infra/packer-builder-vsphere/issues/234
The problem is that vSphere will not let you delete a VM if it is powered on. This means if a CI build is stopped and a new one starts it cannot delete the old VM and ends with an error that it already exists.

#### Reproduction Steps

Start a build with vsphere-iso or vsphere-clone. Cancel the build mid way and make sure to not clean it up (-on-error=abort).  Start another build with the --force flag. This will result in an error that the vm name already exists. The vsphere builder should be enhanced to fix this issue by checking if the VM was powered on and turn it off first before deleting it when the force flag is provided.

### Packer version

Packer v1.6.0

**Comment by jhawk28** [comment]
this should power off the VM: https://github.com/hashicorp/packer/commit/c43a52aafe53dcbbcc209d8bab62e795e3fc099f#diff-57d6257e1da6868d360bd78403640dd9R114

There was is a fix in 1.6.1 that may fix the vm already existing. I would try with the nightly or wait for the 1.6.1 release.

**Comment by mitchellmaler** [comment]
Ah good news! I’ll give it a try.

**Comment by SwampDragons** [comment]
I'm closing this because I believe it's a duplicate but we can reopen if the nightly doesn't fix it.

**Comment by mitchellmaler** [comment]
Yes it is a duplicate of #9511 
I must have missed that when searching.
