### ISSUE TITLE
Windows Server hangs on 'Waiting for IP' (vsphere-iso)

### ISSUE THREAD

**Issue by ljkimmel** [hashicorp/packer#9624]
#### Overview of the Issue

When building Windows Server templates with Packer about 50% of our builds hang at 'Waiting for IP'. We do not have the same issue with Linux-based templates. Looking at the apparent differences between the two systems I noted that the Windows Servers enable 6to4 tunnels by default and, often, the first IP seen is the 6to4 address. 

I added commands to the Autounattend.xml file to disable 6to4 addresses and this 'seems' to resolve the issue.

I can also see, when using debug output, that the template often initially detects an IP address but, as it retests the ip (ip_settle_timeout), it eventually hangs. 

#### Reproduction Steps

Perform a basic template build with Windows Server 2012r2 (for example).

### Packer version

v1.6

### Simplified Packer Buildfile

{
  "builders": [
    {
      "CPUs": 2,
      "RAM": 8192,
      "RAM_reserve_all": true,
      "boot_order": "disk,cdrom",
      "cluster": "{{user `cluster`}}",
      "communicator": "winrm",
      "convert_to_template": "true",
      "create_snapshot": "false",
      "datastore": "{{user `datastore`}}",
      "disk_controller_type": "pvscsi",
      "floppy_files": [
        "{{template_dir}}/setup/"
      ],
      "folder": "{{user `folder`}}",
      "guest_os_type": "windows8Server64Guest",
      "insecure_connection": "true",
      "iso_paths": [
        "[{{user `datastore_iso`}}] ISO_Images/SW_DVD9_Windows_Svr_Std_and_DataCtr_2012_R2_64Bit_English_-4_MLF_X19-82891.ISO",
        "[{{user `datastore_iso`}}] vmtools/windows.iso"
      ],
      "network_adapters": [
        {
          "network": "{{user `network`}}",
          "network_card": "vmxnet3"
        }
      ],
      "password": "{{user `password`}}",
      "storage": [
        {
          "disk_size": 122880,
          "disk_thin_provisioned": true
        }
      ],
      "type": "vsphere-iso",
      "username": "{{user `username`}}",
      "vcenter_server": "{{user `vcenter_server`}}",
      "vm_name": "Windows-Server-2012R2-{{ timestamp }}",
      "vm_version": 15,
      "ip_settle_timeout": "30s",
      "winrm_password": "{{user `winrm_password`}}",
      "winrm_username": "{{user `winrm_username`}}"
    }
  ],
}

**Comment by jhawk28** [comment]
1.6.1 is gonna have some updated wait for IP logic. It looks at only IPv4 addresses by default. (you can set the CIDR range that you want it to look for) I would recommend trying the nightly or waiting for the release to see if it fixes your issue.

**Comment by ljkimmel** [comment]
Ok. I saw that but just wanted to validate. Thanks.
