### ISSUE TITLE
Issues in git clone packer-maas

### ISSUE THREAD

**Issue by c0DeR2020** [hashicorp/packer#9632]
I'm having issues in doing git clone for packer-maas. Below are the log entries. Is there something I'm missing while executing this command?

Thanks!

---------------------------------------------------------------------
root@LB1EDGSCHATTE02:~# git clone --recurse-submodules git@github.com:canonical/packer-maas.git
Cloning into 'packer-maas'...
The authenticity of host 'github.com (140.82.113.4)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,140.82.113.4' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
-------------------------------------------------------------------------------

**Comment by azr** [comment]
Hey @c0DeR2020; I'd see that with the packer-mass project: https://github.com/canonical/packer-maas but it sounds like your ssh keys are not correctly set on Github, here's a link: https://docs.github.com/en/github/authenticating-to-github/adding-a-new-ssh-key-to-your-github-account

Cheers !
