### ISSUE TITLE
Packer WinRM Timeout AWS EBS Builder

### ISSUE THREAD

**Issue by mailman-2097** [hashicorp/packer#9641]
Issue : Infrequent timeout

For the most part the WINRM works. But occasionally, I encounter a timeout issue. 20% of the builds will fail due to the WinRM error.

I have attached the Packer Json, Packer Debug Log and User Data for your reference. 
To explore additional options, I tried to the pause_before_connecting flag but packer ignores the switch and attempts to communicate to WinRM. So I added wait times in the local-provisioner block, but it seems that this wait time kicks in only after the builder action complete. For good measure, I added a sleep time in the windows user data after the WinRM configuration as well.

Please can you advise. The windows user data config is based on the following. 
https://www.packer.io/docs/builders/amazon-ebs.html#connecting-to-windows-instances-using-winrm

For context, this worked with CIS Level 1 images, but recently the client internal team has provided a new image which is when this problem had surfaced. Initially there was no Administrator user so I added the Admin credential and things worked. To ensure a stable release, I decided to run the multiple tests, which is when the occasional time out happens.

################################Packer Log###############################
·[1;32m==> amazon-ebs: Waiting for instance (i-XXXXXXXXXX) to become ready...·[0m
·[1;32m==> amazon-ebs: Skipping waiting for password since WinRM password set...·[0m
·[1;32m==> amazon-ebs: Using winrm communicator to connect: ip-xx-xxx-xx-xx.ap-southeast-2.compute.internal·[0m
2020/07/23 08:31:09 packer: 2020/07/23 08:31:09 Waiting for WinRM, up to timeout: 30m0s
·[1;32m==> amazon-ebs: Waiting for WinRM to become available...·[0m
2020/07/23 08:31:09 packer: 2020/07/23 08:31:09 Using ssh_host value: ip-xx-xxx-xx-xx.ap-southeast-2.compute.internal
2020/07/23 08:31:09 packer: 2020/07/23 08:31:09 [INFO] Attempting WinRM connection...
2020/07/23 08:31:09 packer: 2020/07/23 08:31:09 [DEBUG] connecting to remote shell using WinRM
2020/07/23 08:31:39 packer: 2020/07/23 08:31:39 [ERROR] connection error: unknown error Post https://ip-xx-xxx-xx-xx.ap-southeast-2.compute.internal:5986/wsman: dial tcp 10.191.63.99:5986: i/o timeout
2020/07/23 08:31:39 packer: 2020/07/23 08:31:39 [ERROR] WinRM connection err: unknown error Post https://ip-xx-xxx-xx-xx.ap-southeast-2.compute.internal:5986/wsman: dial tcp 10.191.63.99:5986: i/o timeout
2020/07/23 08:31:44 packer: 2020/07/23 08:31:44 Using ssh_host value: ip-xx-xxx-xx-xx.ap-southeast-2.compute.internal
2020/07/23 08:31:44 packer: 2020/07/23 08:31:44 [INFO] Attempting WinRM connection...
2020/07/23 08:31:44 packer: 2020/07/23 08:31:44 [DEBUG] connecting to remote shell using WinRM
2020/07/23 08:32:14 packer: 2020/07/23 08:32:14 [ERROR] connection error: unknown error Post https://ip-xx-xxx-xx-xx.ap-southeast-2.compute.internal:5986/wsman: dial tcp 10.191.63.99:5986: i/o timeout
2020/07/23 08:32:14 packer: 2020/07/23 08:32:14 [ERROR] WinRM connection err: unknown error Post https://ip-xx-xxx-xx-xx.ap-southeast-2.compute.internal:5986/wsman: dial tcp 10.191.63.99:5986: i/o timeout
2020/07/23 08:32:19 packer: 2020/07/23 08:32:19 Using ssh_host value: ip-xx-xxx-xx-xx.ap-southeast-2.compute.internal
2020/07/23 08:32:19 packer: 2020/07/23 08:32:19 [INFO] Attempting WinRM connection...
2020/07/23 08:32:19 packer: 2020/07/23 08:32:19 [DEBUG] connecting to remote shell using WinRM
2020/07/23 08:32:49 packer: 2020/07/23 08:32:49 [ERROR] connection error: unknown error Post https://ip-xx-xxx-xx-xx.ap-southeast-2.compute.internal:5986/wsman: dial tcp 10.191.63.99:5986: i/o timeout
2020/07/23 08:32:49 packer: 2020/07/23 08:32:49 [ERROR] WinRM connection err: unknown error Post https://ip-xx-xxx-xx-xx.ap-southeast-2.compute.internal:5986/wsman: dial tcp 10.191.63.99:5986: i/o timeout
2020/07/23 08:32:54 packer: 2020/07/23 08:32:54 Using ssh_host value: ip-xx-xxx-xx-xx.ap-southeast-2.compute.internal
2020/07/23 08:32:54 packer: 2020/07/23 08:32:54 [INFO] Attempting WinRM connection...
2020/07/23 08:32:54 packer: 2020/07/23 08:32:54 [DEBUG] connecting to remote shell using WinRM
2020/07/23 08:33:24 packer: 2020/07/23 08:33:24 [ERROR] connection error: unknown error Post https://ip-xx-xxx-xx-xx.ap-southeast-2.compute.internal:5986/wsman: dial tcp 10.191.63.99:5986: i/o timeout
2020/07/23 08:33:24 packer: 2020/07/23 08:33:24 [ERROR] WinRM connection err: unknown error Post https://ip-xx-xxx-xx-xx.ap-southeast-2.compute.internal:5986/wsman: dial tcp 10.191.63.99:5986: i/o timeout
2020/07/23 08:33:29 packer: 2020/07/23 08:33:29 Using ssh_host value: ip-xx-xxx-xx-xx.ap-southeast-2.compute.internal
2020/07/23 08:33:29 packer: 2020/07/23 08:33:29 [INFO] Attempting WinRM connection...
2020/07/23 08:33:29 packer: 2020/07/23 08:33:29 [DEBUG] connecting to remote shell using WinRM
2020/07/23 08:33:59 packer: 2020/07/23 08:33:59 [ERROR] connection error: unknown error Post https://ip-xx-xxx-xx-xx.ap-southeast-2.compute.internal:5986/wsman: dial tcp 10.191.63.99:5986: i/o timeout
2020/07/23 08:33:59 packer: 2020/07/23 08:33:59 [ERROR] WinRM connection err: unknown error Post https://ip-xx-xxx-xx-xx.ap-southeast-2.compute.internal:5986/wsman: dial tcp 10.191.63.99:5986: i/o timeout
2020/07/23 08:34:04 packer: 2020/07/23 08:34:04 Using ssh_host value: ip-xx-xxx-xx-xx.ap-southeast-2.compute.internal
2020/07/23 08:34:04 packer: 2020/07/23 08:34:04 [INFO] Attempting WinRM connection...
2020/07/23 08:34:04 packer: 2020/07/23 08:34:04 [DEBUG] connecting to remote shell using WinRM
2020/07/23 08:34:34 packer: 2020/07/23 08:34:34 [ERROR] connection error: unknown error Post https://ip-xx-xxx-xx-xx.ap-southeast-2.compute.internal:5986/wsman: dial tcp 10.191.63.99:5986: i/o timeout
2020/07/23 08:34:34 packer: 2020/07/23 08:34:34 [ERROR] WinRM connection err: unknown error Post https://ip-xx-xxx-xx-xx.ap-southeast-2.compute.internal:5986/wsman: dial tcp 10.191.63.99:5986: i/o timeout
2020/07/23 08:34:39 packer: 2020/07/23 08:34:39 Using ssh_host value: ip-xx-xxx-xx-xx.ap-southeast-2.compute.internal
2020/07/23 08:34:39 packer: 2020/07/23 08:34:39 [INFO] Attempting WinRM connection...
2020/07/23 08:34:39 packer: 2020/07/23 08:34:39 [DEBUG] connecting to remote shell using WinRM
2020/07/23 08:35:09 packer: 2020/07/23 08:35:09 [ERROR] connection error: unknown error Post https://ip-xx-xxx-xx-xx.ap-southeast-2.compute.internal:5986/wsman: dial tcp 10.191.63.99:5986: i/o timeout
2020/07/23 08:35:09 packer: 2020/07/23 08:35:09 [ERROR] WinRM connection err: unknown error Post https://ip-xx-xxx-xx-xx.ap-southeast-2.compute.internal:5986/wsman: dial tcp 10.191.63.99:5986: i/o timeout
2020/07/23 08:35:14 packer: 2020/07/23 08:35:14 Using ssh_host value: ip-xx-xxx-xx-xx.ap-southeast-2.compute.internal
2020/07/23 08:35:14 packer: 2020/07/23 08:35:14 [INFO] Attempting WinRM connection...
2020/07/23 08:35:14 packer: 2020/07/23 08:35:14 [DEBUG] connecting to remote shell using WinRM
2020/07/23 08:35:44 packer: 2020/07/23 08:35:44 [ERROR] connection error: unknown error Post https://ip-xx-xxx-xx-xx.ap-southeast-2.compute.internal:5986/wsman: dial tcp 10.191.63.99:5986: i/o timeout
2020/07/23 08:35:44 packer: 2020/07/23 08:35:44 [ERROR] WinRM connection err: unknown error Post https://ip-xx-xxx-xx-xx.ap-southeast-2.compute.internal:5986/wsman: dial tcp 10.191.63.99:5986: i/o timeout
2020/07/23 08:35:49 packer: 2020/07/23 08:35:49 Using ssh_host value: ip-xx-xxx-xx-xx.ap-southeast-2.compute.internal
2020/07/23 08:35:49 packer: 2020/07/23 08:35:49 [INFO] Attempting WinRM connection...
2020/07/23 08:35:49 packer: 2020/07/23 08:35:49 [DEBUG] connecting to remote shell using WinRM
2020/07/23 08:36:19 packer: 2020/07/23 08:36:19 [ERROR] connection error: unknown error Post https://ip-xx-xxx-xx-xx.ap-southeast-2.compute.internal:5986/wsman: dial tcp 10.191.63.99:5986: i/o timeout
2020/07/23 08:36:19 packer: 2020/07/23 08:36:19 [ERROR] WinRM connection err: unknown error Post https://ip-xx-xxx-xx-xx.ap-southeast-2.compute.internal:5986/wsman: dial tcp 10.191.63.99:5986: i/o timeout
2020/07/23 08:36:24 packer: 2020/07/23 08:36:24 Using ssh_host value: ip-xx-xxx-xx-xx.ap-southeast-2.compute.internal
2020/07/23 08:36:24 packer: 2020/07/23 08:36:24 [INFO] Attempting WinRM connection...
2020/07/23 08:36:24 packer: 2020/07/23 08:36:24 [DEBUG] connecting to remote shell using WinRM
·[1;31mBuild 'amazon-ebs' errored: unexpected EOF·[0m

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: unexpected EOF

==> Builds finished but no artifacts were created.
2020/07/23 08:36:29 packer: panic: runtime error: invalid memory address or nil pointer dereference
2020/07/23 08:36:29 packer: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x705f86]
2020/07/23 08:36:29 packer: 
2020/07/23 08:36:29 packer: goroutine 254 [running]:
2020/07/23 08:36:29 packer: net/http.redirectBehavior(0x3e5a6b4, 0x4, 0x0, 0xc0003ca900, 0x0, 0x0, 0x0)
2020/07/23 08:36:29 packer:     /usr/local/Cellar/go/1.13.4/libexec/src/net/http/client.go:422 +0x26
2020/07/23 08:36:29 packer: net/http.(*Client).do(0xc00085d260, 0xc0003ca900, 0x0, 0x0, 0x0)
2020/07/23 08:36:29 packer:     /usr/local/Cellar/go/1.13.4/libexec/src/net/http/client.go:655 +0x436
2020/07/23 08:36:29 packer: net/http.(*Client).Do(...)
2020/07/23 08:36:29 packer:     /usr/local/Cellar/go/1.13.4/libexec/src/net/http/client.go:509
2020/07/23 08:36:29 packer: github.com/masterzen/winrm.clientRequest.Post(0x4452fa0, 0xc0006f8b00, 0xc0000ed300, 0xc000712980, 0x0, 0x0, 0x0, 0x0)
2020/07/23 08:36:29 packer:     /Users/azr/go/pkg/mod/github.com/masterzen/winrm@v0.0.0-20180224160350-7e40f93ae939/http.go:82 +0x3ab
2020/07/23 08:36:29 packer: github.com/masterzen/winrm.ClientNTLM.Post(...)
2020/07/23 08:36:29 packer:     /Users/azr/go/pkg/mod/github.com/masterzen/winrm@v0.0.0-20180224160350-7e40f93ae939/ntlm.go:22
2020/07/23 08:36:29 packer: github.com/masterzen/winrm.(*Client).sendRequest(...)
2020/07/23 08:36:29 packer:     /Users/azr/go/pkg/mod/github.com/masterzen/winrm@v0.0.0-20180224160350-7e40f93ae939/client.go:102
2020/07/23 08:36:29 packer: github.com/masterzen/winrm.(*Client).CreateShell(0xc0000ed300, 0x0, 0x0, 0x0)
2020/07/23 08:36:29 packer:     /Users/azr/go/pkg/mod/github.com/masterzen/winrm@v0.0.0-20180224160350-7e40f93ae939/client.go:81 +0xcc
2020/07/23 08:36:29 packer: github.com/hashicorp/packer/communicator/winrm.New(0xc00082a1e0, 0xc00082a1e0, 0x1, 0x2f)
2020/07/23 08:36:29 packer:     /Users/azr/go/src/github.com/hashicorp/packer/communicator/winrm/communicator.go:59 +0x182
2020/07/23 08:36:29 packer: github.com/hashicorp/packer/helper/communicator.(*StepConnectWinRM).waitForWinRM(0xc0006fd900, 0x44a4c60, 0xc00054a990, 0x44c74a0, 0xc0004ba0c0, 0x0, 0xc0006ecb70, 0xc00083d980, 0x0)
2020/07/23 08:36:29 packer:     /Users/azr/go/src/github.com/hashicorp/packer/helper/communicator/step_connect_winrm.go:134 +0x283
2020/07/23 08:36:29 packer: github.com/hashicorp/packer/helper/communicator.(*StepConnectWinRM).Run.func1(0x44e09c0, 0xc0003874e0, 0xc0006fd900, 0x44a4c60, 0xc00054a990, 0x44c74a0, 0xc0004ba0c0, 0xc000737350, 0xc000737360, 0xc000737370, ...)
2020/07/23 08:36:29 packer:     /Users/azr/go/src/github.com/hashicorp/packer/helper/communicator/step_connect_winrm.go:46 +0x86
2020/07/23 08:36:29 packer: created by github.com/hashicorp/packer/helper/communicator.(*StepConnectWinRM).Run
2020/07/23 08:36:29 packer:     /Users/azr/go/src/github.com/hashicorp/packer/helper/communicator/step_connect_winrm.go:44 +0x1d7
2020/07/23 08:36:29 [INFO] (telemetry) ending amazon-ebs
2020/07/23 08:36:29 machine readable: error-count []string{"1"}
==> Some builds didn't complete successfully and had errors:
2020/07/23 08:36:29 /usr/bin/packer: plugin process exited
2020/07/23 08:36:29 machine readable: amazon-ebs,error []string{"unexpected EOF"}
==> Builds finished but no artifacts were created.
2020/07/23 08:36:29 [INFO] (telemetry) Finalizing.
2020/07/23 08:36:29 waiting for all plugin processes to complete...
2020/07/23 08:36:29 /usr/bin/packer: plugin process exited
2020/07/23 08:36:29 /usr/bin/packer: plugin process exited
2020/07/23 08:36:29 /usr/bin/packer: plugin process exited
2020/07/23 08:36:29 /usr/bin/packer: plugin process exited
2020/07/23 08:36:29 /usr/bin/packer: plugin process exited
2020/07/23 08:36:29 /usr/bin/packer: plugin process exited

[Container] 2020/07/23 08:36:29 Command did not exit successfully PACKER_LOG=${packer_log} /usr/bin/packer build -var-file=vars.json packer.json exit status 1
[Container] 2020/07/23 08:36:30 Phase complete: BUILD State: FAILED
[Container] 2020/07/23 08:36:30 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: PACKER_LOG=${packer_log} /usr/bin/packer build -var-file=vars.json packer.json. Reason: exit status 1
[Container] 2020/07/23 08:36:30 Entering phase POST_BUILD
[Container] 2020/07/23 08:36:30 Phase complete: POST_BUILD State: SUCCEEDED
[Container] 2020/07/23 08:36:30 Phase context status code:  Message: 

################################Packer Log###############################

################################Packer Json###############################
{ 	"builders": [{
	"type": "amazon-ebs",
	"region": "ap-southeast-2",
	"encrypt_boot": true,
	"kms_key_id": "REDACT",
	"instance_type": "t2.medium",
	"source_ami": "ami-XXXXX",
	"ami_name": "image-factory-win-infradev-dev-01-1.1.5",
	"iam_instance_profile": "workload_imagefactory_packer_profile",
	"vpc_id": "vpc-XXXXXXX",
	"subnet_id": "subnet-XXXXXX",
	"security_group_id": "sg-XXXXXXX",
	"user_data_file": "windows_userdata.txt",
	"communicator": "winrm",
	"winrm_username": "Administrator",
	"winrm_password": "**************",
	"winrm_insecure": "true",
	"winrm_use_ssl": "true",
	"winrm_use_ntlm": "true",
	"ssh_interface": "private_dns",
	"pause_before_connecting": "60s",
}],
"provisioners": [{
		"type": "shell-local",
		"environment_vars": [
			"DURATION={{user `sleep_time`}}"
		],
		"inline": [
			"echo \"sleep for $DURATION\"",
			"sleep $DURATION",
			"echo 'awake'"
		]
	},
	{
		"type": "file",
		"source": "packer_context.ps1",
		"destination": "C:\\"
	},
	{
		"type": "powershell",
		"inline": [
			"Write-Host \"SOE WIN Test\""
		]
	}
]
}
################################Packer Json###############################

################################Windows User Data###############################
$Password = "{admin_password}"
New-LocalUser -Name Administrator -Description "WinRM Admin Account" -Password (ConvertTo-SecureString -AsPlainText "$Password" -Force)
Set-LocalUser -Name Administrator -Description "WinRM Admin Password" -Password (ConvertTo-SecureString -AsPlainText "$Password" -Force)

Add-LocalGroupMember -Group "Administrators" -Member Administrator
Add-LocalGroupMember -Group "Remote Desktop Users" -Member Administrator
net user Administrator

# Packer Default WinRM Enable Userdata

write-output "Running User Data Script"
write-host "(host) Running User Data Script"

Set-ExecutionPolicy Unrestricted -Scope LocalMachine -Force -ErrorAction Ignore

# Don't set this before Set-ExecutionPolicy as it throws an error
$ErrorActionPreference = "stop"

# Remove HTTP listener
Remove-Item -Path WSMan:\Localhost\listener\listener* -Recurse

# Create a self-signed certificate to let ssl work
Cert = New-SelfSignedCertificate -CertstoreLocation Cert:\LocalMachine\My -DnsName "packer"
New-Item -Path WSMan:\LocalHost\Listener -Transport HTTPS -Address * -CertificateThumbPrint $Cert.Thumbprint -Force

# WinRM
write-output "Setting up WinRM"
write-host "(host) setting up WinRM"

cmd.exe /c winrm quickconfig -q
cmd.exe /c winrm set "winrm/config" '@{MaxTimeoutms="1800000"}'
cmd.exe /c winrm set "winrm/config/winrs" '@{MaxMemoryPerShellMB="1024"}'
cmd.exe /c winrm set "winrm/config/service" '@{AllowUnencrypted="true"}'
cmd.exe /c winrm set "winrm/config/client" '@{AllowUnencrypted="true"}'
cmd.exe /c winrm set "winrm/config/service/auth" '@{Basic="true"}'
cmd.exe /c winrm set "winrm/config/client/auth" '@{Basic="true"}'
cmd.exe /c winrm set "winrm/config/service/auth" '@{CredSSP="true"}'
cmd.exe /c winrm set "winrm/config/listener?Address=*+Transport=HTTPS" "@{Port=`"5986`";Hostname=`"packer`";CertificateThumbprint=`"$($Cert.Thumbprint)`"}"
Set-Item WSMan:\localhost\Client\TrustedHosts -Value '*' -Force
cmd.exe /c netsh advfirewall firewall set rule group="windows management instrumentation (wmi)" new enable=yes
cmd.exe /c netsh firewall set service remoteadmin enable
cmd.exe /c netsh advfirewall firewall set rule group="remote administration" new enable=yes
cmd.exe /c netsh firewall add portopening TCP 5986 "Port 5986"
cmd.exe /c net stop winrm
cmd.exe /c sc config winrm start= auto
cmd.exe /c net start winrm

Start-Sleep -Seconds "{sleep_duration}"

################################Windows User Data###############################

**Comment by SwampDragons** [comment]
This issue may be due to the fact that you're using winrm quickconfig: 

https://learn.hashicorp.com/packer/getting-started/build-image#warning

**Comment by SwampDragons** [comment]
What version of Packer are you using? This crash looks like one that I fixed over in https://github.com/hashicorp/packer/pull/8369, which was released with v1.5.0.

**Comment by mailman-2097** [comment]
Ok. let me test with that version..

**Comment by mailman-2097** [comment]
Hi, 

Thanks for your input. I updated the packer version to v1.5.0 and it looks good.

Regarding the WinRM quickconfig point, I did read the documentation and tried configuration in combination with v1.6.0. But the registry update failed for the image that our client is using which is based off a AWS Win 2016 AMI and heavily modified with their On-Premise Windows image baking scripts to create their SOE . So at this point not clear why the new configuration failed but possibility that the image baking scripts.

I have recommended an uplift to that configuration.

**Comment by SwampDragons** [comment]
Glad it looks like updating resolved the panic; I'll close this issue since it looks solved. 

It's strange that the registry updates are failing for the newer version of Packer. If you can provide a repro case with a version of windows that I can publicly access, please open an issue for that and I'll take a look.
