### ISSUE TITLE
Add support for exporting to OVA in vsphere-iso builder

### ISSUE THREAD

**Issue by nilic** [hashicorp/packer#9645]
Currently, the `vsphere-iso` builder allows exporting the created template only in OVF format, while `vmware-iso` also has OVA support. OVA is in many cases preferred because of template portability (one file with OVA vs multiple files with OVF) and sometimes required, since some of the automation tooling (such as Terraform provider for vCloud Director) supports only OVA as input for catalog uploads.

**Comment by arogarth** [comment]
Workaround - Use tar in local-shell post-provisioner...

Something like:
```
tar -cf ubuntu-20.04.ova ubuntu-20.04.ovf ubuntu-20.04.mf ubuntu-20.04-disk1.vmdk
```

**Comment by nilic** [comment]
Yeah, that's what I've been using, but it would be nice to have OVA export as an integral part of the `vsphere-iso` builder.
