### ISSUE TITLE
You are using Azure Packer Builder to create VHDs which is being deprecated

### ISSUE THREAD

**Issue by maxim-lobanov** [hashicorp/packer#9647]
Hello,
```
==> azure-arm: Warning: You are using Azure Packer Builder to create VHDs which is being deprecated, consider using Managed Images. Learn more http://aka.ms/packermanagedimage
```
Could you please provide a bit more information what does it mean?
Will VHD support removed in future? If yes, could you please share approximate ETA?
Unfortunately, I didn't find any related information.

**Comment by azr** [comment]
Hello there, thanks for opening; more info can be found here https://github.com/hashicorp/packer/issues/8217#issuecomment-541119078 to quote the message: 

>Azure wants everyone to move to using managed images and managed disks because they hide the complexity with respect to storage account performance. Managed disks can be exported to a VHD.
What if we removed VHD support but added a post-provisioner that can automate the export to a storage account?

>As for a date, we don't have a hard deadline, just a wish to untangle the mess it currently is.

**Comment by maxim-lobanov** [comment]
@azr, thank you for you response. Just was a bit scared by message and fact that our VHD based builds will stop to work suddenly one day :)
P.S. I think it makes to add this information to documentation, at least fact that VHD won't be disabled nearest time.
