### ISSUE TITLE
vsphere Provisioner incorrect error code when build fails

### ISSUE THREAD

**Issue by amitbhadra** [hashicorp/packer#9650]
#### Overview of the Issue

When a Packer build fails, the error code returned should be 1. But `echo $?` returns 0.  I need it to fail so that the CI/CD job fails if Packer fails.

#### Reproduction Steps

Fail any Packer build. 

### Operating system and Environment details

CentOS 7.7

**Comment by sylviamoss** [comment]
Did you mean any provisioner with the vSphere builder?

**Comment by SwampDragons** [comment]
Is it possible that you are using tee or some other tool to process Packer logs and it is losing the exit code? https://github.com/hashicorp/packer/issues/7382#issuecomment-470319060

**Comment by amitbhadra** [comment]
Closing this issue because Packer is giving a failure exit code. I was using a bash script to invoke the Packer build and the bash script wasn't giving an error code due to steps after that. But Packer is indeed giving a failure exit code.
