### ISSUE TITLE
max_retries for provisioners does not allow variable input

### ISSUE THREAD

**Issue by Jazzepi** [hashicorp/packer#9651]
#### Overview of the Issue

When trying to make max_retries configurable for the caller of the packer template, it fails because max_retries expects an int, not a string.

#### Reproduction Steps
Setup a template with a variable with a string integer. Then reference that string integer for the max_retries portion of the provisioners stanza.

### Packer version
Both the following versions show this behavior
1.6.0
1.5.6

### Simplified Packer Buildfile
```
{
  "variables": {
    "max.retries": "3"
  },
  "provisioners": [
    {
      "max_retries": "{{user `max.retries`}}"
    }
  ]
}
```

### Operating system and Environment details
Ubuntu 18.04 , inside an ubuntu 18.04 docker

### Log Fragments and crash.log files
```
Failed to parse template: 1 error occurred:
	* provisioner 1: Error decoding provisioner: 1 error(s) decoding:
* 'max_retries' expected type 'int', got unconvertible type 'string'
```

**Comment by azr** [comment]
Hey @Jazzepi thanks for opening, have you tried unquoting the `"3"` ?:

```json
{
  "variables": {
    "max.retries": 3
  }
}
```

Also, this should just work with HCL2:

```hcl
variable "max_retries" {
  type    = number
  default = 3
}

build {
  # ... sources
  provisioner "shell-local" {
    max_retries = var.max_retries
  }
}
```

**Comment by Jazzepi** [comment]
Sorry the corrolary to this post is that I was trying to use a user variable as input for retry count. This would allow CI systems to retry automatically and developers who are iterating on the template locally to stop after the first failure.

Since the only way to pass variables is with templated strings max_retries does not allow you to pass in a user variable because it does not coerce the string number into an int.

**Comment by azr** [comment]
That's odd, thanks for reporting; we will check that one soon,
