### ISSUE TITLE
"shared_image_gallery_replica_count" not recognised Azure

### ISSUE THREAD

**Issue by mickeyoc76** [hashicorp/packer#9654]
Hi,

Trying to set the replica count per Azure region to 5, I've also tried putting it under the "shared_image_gallery_destination" section but get the same error.  According to your docs it's a valid setting

https://www.packer.io/docs/builders/azure/arm#shared_image_gallery_replica_count

- Getting this during packer validation

Errors validating build 'azure-arm'. 1 error occurred:
	* unknown configuration key: "shared_image_gallery_replica_count"; raws is []interface {}{map[string]interface {}{"azure_tags":map[interface {}]interface

{
  "variables": {
  "client_id": "",
  "client_secret": "",
  "tenant_id": "",
  "subscription_id": "",
  "build_resource_group_name": "",
  "Build_DefinitionName": "",
  "Build_BuildNumber": "",
  "managed_image_resource_group_name": ""
 },

  "builders": [
      {
    "type": "azure-arm",

    "client_id": "{{user `client_id`}}",
    "client_secret": "{{user `client_secret`}}",
    "tenant_id": "{{user `tenant_id`}}",
    "subscription_id": "{{user `subscription_id`}}",
    "managed_image_name": "Win10-19h2-0.0.9",
    "build_resource_group_name": "{{user `build_resource_group_name`}}",
    "managed_image_resource_group_name": "{{user `managed_image_resource_group_name`}}",
    "os_type": "Windows",
    "shared_image_gallery_replica_count": "5",
    "image_publisher": "MicrosoftWindowsDesktop",
    "image_offer": "Windows-10",
    "image_sku": "19h2-ent",

    "shared_image_gallery_destination": {
      "resource_group": "{{user `managed_image_resource_group_name`}}",
      "gallery_name": "ImageGallery",
      "image_name": "Win10-19h2",
      "image_version": "0.0.9",
      "replication_regions": [
          "northeurope",
		  "westeurope",
          "centralus",
          "eastus2"		
      ]

**Comment by sylviamoss** [comment]
Could tell me which Packer version you are using?

**Comment by mickeyoc76** [comment]
Hi,

C:\vstsagent\agent\_work\_tool\packer\1.5.1\x64\packer.exe --version
1.5.1

**Comment by sylviamoss** [comment]
Ok. The option was added here https://github.com/hashicorp/packer/commit/9569d35d14097cbaec33bc0f38782483a90d6baa you need to update your Packer version to be able to use it.

**Comment by mickeyoc76** [comment]
Great, thanks for the quick response.

**Comment by sylviamoss** [comment]
I'm closing this one. In case you find another issue feel free to reach us by opening a new one.

**Comment by mickeyoc76** [comment]
Confirmed, upgraded to 1.5.2 and no longer getting the error.
Thanks!
