### ISSUE TITLE
vagrant builder cannot handle source_path that is URL and ends in `.box`

### ISSUE THREAD

**Issue by tdyas** [hashicorp/packer#9656]
#### Overview / Reproduction

I have HCL2  source config for the vagrant builder with `source_path` set to `"https://cloud-images.ubuntu.com/focal/20200720/focal-server-cloudimg-amd64-vagrant.box"`. This fails with the error:

```
* Source box 'https://cloud-images.ubuntu.com/focal/20200720/focal-server-cloudimg-amd64-vagrant.box' needs to exist at time of config validation! stat https://cloud-images.ubuntu.com/focal/20200720/focal-server-cloudimg-amd64-vagrant.box: no such file or directory
```

This occurs because the code at 
https://github.com/hashicorp/packer/blob/943cb1275ddfdbc698ebad0c87935ba364f7dc69/builder/vagrant/builder.go#L197-L202 checks whether the source_path ends in `.box` and tries to stat it as a filesystem path even when the `source_path` is a URL.

The code in question should first check whether the `source_path` is a valid URL before doing filesystem-specific checks.

### Packer version

1.6.0

### Simplified Packer Buildfile

```
source "vagrant" "ubuntu2004" {
  source_path = "https://cloud-images.ubuntu.com/focal/20200720/focal-server-cloudimg-amd64-vagrant.box"
  box_name    = "devbox"
  provider    = "virtualbox"
  checksum    = "ac3cc7be1de4ee56993d1a79ddec778e944cd6e9398caf8c2db031f55e2e980d"

  communicator = "ssh"
  ssh_username = "vagrant"
  ssh_password = "vagrant"
}
```

### Operating system and Environment details

macOS v10.15.6

**Comment by tdyas** [comment]
I assumed that providing a URL was valid since the documentation states that it is:

> URL of the vagrant box to use, or the name of the vagrant box. hashicorp/precise64, ./mylocalbox.box and https://example.com/my-box.box are all valid source boxes.

https://www.packer.io/docs/builders/vagrant#source_path

**Comment by SwampDragons** [comment]
Yes, this is a regression. I'll figure out the best fix today.
