### ISSUE TITLE
how to used boot_command in packer (vsphere-iso)？

### ISSUE THREAD

**Issue by zhongc-jiang** [hashicorp/packer#9658]
my builders as follows:

 "builders": [
   {
      "type": "vsphere-iso",
      "vcenter_server": "{{user `vsphere-server`}}",
      "username": "{{user `vsphere-user`}}",
      "password": "{{user `vsphere-password`}}",
      "insecure_connection": "true",

      "datacenter": "{{user `vsphere-datacenter`}}",
      "cluster": "{{user `vsphere-cluster`}}",
	  "host" : "{{user `vsphere-host`}}",
      "datastore": "{{user `vsphere-datastore`}}",
	  "usb_controller": "false",

      "vm_name": "{{user `vm-name`}}-{{isotime \"2006-01-02\"}}",
      "vm_version": "{{user `vm-version`}}",
      "notes": "Build via Packer in {{ (isotime | (user `magic_reference_date`)) }}",

      "boot_wait": "100s",
      "boot_order": "disk,cdrom,floppy",

      "guest_os_type": "centos64Guest",

      "ssh_username": "root",
      "ssh_password": "VMware1!",

      "CPUs": "{{user `vm-cpu-num`}}",
      "RAM": "{{user `vm-mem-size`}}",
      "RAM_reserve_all": false, 
      "convert_to_template": true,
	  "storage": [
		   {
			 "disk_size": "{{user `vm-disk-size`}}",
			 "disk_thin_provisioned": true
		   }
		],
	   "network_adapters": [
		   {
			 "network": "{{user `vsphere-network`}}",
			 "network_card": "vmxnet3"
		   }
		],
      "iso_paths": ["{{user `iso_url`}}"],
      "floppy_files": ["ks1.cfg"],
      "boot_command": [
        "<esc><wait>",
        "linux ks=hd:fd0:/ks1.cfg<enter>"
      ]
   }
 ],

test result as follows:

==> vsphere-iso: Creating VM...
==> vsphere-iso: Customizing hardware...
==> vsphere-iso: Mounting ISO images...
==> vsphere-iso: Creating floppy disk...
    vsphere-iso: Copying files flatly from floppy_files
    vsphere-iso: Copying file: ks1.cfg
    vsphere-iso: Done copying files from floppy_files
    vsphere-iso: Collecting paths from floppy_dirs
    vsphere-iso: Resulting paths from floppy_dirs : []
    vsphere-iso: Done copying paths from floppy_dirs
==> vsphere-iso: Uploading created floppy image
==> vsphere-iso: Adding generated Floppy...
==> vsphere-iso: Set boot order...
==> vsphere-iso: Power on VM...
==> vsphere-iso: Waiting 1m40s for boot...
==> vsphere-iso: Typing boot command...
==> vsphere-iso: Power off VM...
==> vsphere-iso: Deleting Floppy image ...
==> vsphere-iso: Destroying VM...
Build 'vsphere-iso' errored: error typing a boot command: ServerFaultCode: Canno
t complete the operation due to an incorrect request to the server.

==> Some builds didn't complete successfully and had errors:
--> vsphere-iso: error typing a boot command: ServerFaultCode: Cannot complete the operation due to an incorrect request to the server.

==> Builds finished but no artifacts were created.

I don't know how to set the values of  boot_command,is there has some example or course about it, thank u.

**Comment by azr** [comment]
Hello there, Google gave me that answer: https://github.com/sbeliakou/packer-centos-template/blob/master/vagrant-centos-8.json, I have not tried it but it should help you out. The important part should be the ks file: https://github.com/sbeliakou/packer-centos-template/blob/master/http/vagrant-8.ks

Please only use GitHub Issues for reporting bugs and feature requests.  For better help follow the links in https://www.packer.io/community/ 

Cheers !

**Comment by zhongc-jiang** [comment]
> 您好，Google给了我这个答案：[https](https://github.com/sbeliakou/packer-centos-template/blob/master/vagrant-centos-8.json) : [//github.com/sbeliakou/packer-centos-template/blob/master/vagrant-centos-8.json](https://github.com/sbeliakou/packer-centos-template/blob/master/vagrant-centos-8.json)，我没有尝试过，但是应该可以帮到您。重要的部分应该是ks文件：[https](https://github.com/sbeliakou/packer-centos-template/blob/master/http/vagrant-8.ks) : [//github.com/sbeliakou/packer-centos-template/blob/master/http/vagrant-8.ks](https://github.com/sbeliakou/packer-centos-template/blob/master/http/vagrant-8.ks)
> 
> 请仅使用GitHub Issues报告错误和功能请求。要获得更好的帮助，[请访问https://www.packer.io/community/中](https://www.packer.io/community/)的链接[](https://www.packer.io/community/)
> 
> 干杯！

thank u
