### ISSUE TITLE
1.6.1 configuration_parameters not applied

### ISSUE THREAD

**Issue by ctorkington-craven** [hashicorp/packer#9684]
#### Overview of the Issue

.json file with 1.6.0 works fine, with packer 1.6.1 no configuration_parameters settings applied. 

There are no errors on packer_log

Is there a change to functionality?

#### Reproduction Steps

Run with .json file with configuration_parameters defined. Check vm advanced settings

### Packer version

From 1.6.1

### Operating system and Environment details

Vcenter and esxi 6.7u3

**Comment by sylviamoss** [comment]
Hey there! Thanks for reaching out. We’ll take a look when we get a chance.

**Comment by sylviamoss** [comment]
Me again! I found the error and I opened a PR to fix it. Do you mind testing the binaries and let me know if works for you, please? 
Here they are: https://circleci.com/gh/hashicorp/packer/71823#artifacts/containers/0

**Comment by ctorkington-craven** [comment]
that works!  :)



Carl Torkington-Craven

Technical Consultant

Windows Support Team



TSYS

+44 1423.580180 O

ctorkington-craven@tsys.com

A Global Payments Company

NOTICE: This email message is for the sole use of the addressee(s) named

above and may contain confidential and privileged information. Any
unauthorized

review, use, disclosure or distribution of this message or any attachments
is

expressly prohibited. If you are not the intended recipient, please contact
the

sender by reply email and destroy all copies and backups of the original
message.


On Wed, 5 Aug 2020 at 14:54, Sylvia Moss <notifications@github.com> wrote:

> Me again! I found the error and I opened a PR to fix it. Do you mind
> testing the binaries and let me know if works for you, please?
> Here they are:
> https://circleci.com/gh/hashicorp/packer/71823#artifacts/containers/0
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__circleci.com_gh_hashicorp_packer_71823-23artifacts_containers_0&d=DwMCaQ&c=Z4P52L0foFKAY1wcP-GmiQ&r=1_ZO5ksZk6ung5eff4URmqXie4DDnjssKqW05M0X1Fk&m=ATNm2E0wRQC6DkVX50bsUJWQ0cCIH9hHA1b1wKjgsNE&s=uTbYeQdAUql-zGRrUpmYAf5b8ezb2ade4sKQwlsl1tE&e=>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_hashicorp_packer_issues_9684-23issuecomment-2D669207197&d=DwMCaQ&c=Z4P52L0foFKAY1wcP-GmiQ&r=1_ZO5ksZk6ung5eff4URmqXie4DDnjssKqW05M0X1Fk&m=ATNm2E0wRQC6DkVX50bsUJWQ0cCIH9hHA1b1wKjgsNE&s=GV5dDubrV6dcFECR5NbDOSQIinfwuyUODadL8lxIqQ8&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AQDCQQMTOR25HGQQASOWWMDR7FQAFANCNFSM4PQS6I6A&d=DwMCaQ&c=Z4P52L0foFKAY1wcP-GmiQ&r=1_ZO5ksZk6ung5eff4URmqXie4DDnjssKqW05M0X1Fk&m=ATNm2E0wRQC6DkVX50bsUJWQ0cCIH9hHA1b1wKjgsNE&s=WROdhm2bYPCWusfbQElNIeInX_iF6TmuF8O2mw3v4cg&e=>
> .
>

-- 
NOTICE: This email message is for the sole use of the addressee(s) named 
above and may contain confidential and privileged information. Any 
unauthorized review, use, disclosure or distribution of this message or any 
attachments is expressly prohibited. If you are not the intended recipient, 
please contact the sender by reply email and destroy all copies and backups 
of the original message.

**Comment by sylviamoss** [comment]
> that works!  :)

@ctorkington-craven good, thanks for letting me know! 
I'm deleting your previous comment because it contains your phone number and other data.
