### ISSUE TITLE
1.6.1 and current git master fail to build from source

### ISSUE THREAD

**Issue by berolinux** [hashicorp/packer#9690]
#### Overview of the Issue

Trying to build either v1.6.1 or current git master from source fails, apparently because of renames in various go modules being pulled in from external sources.
This probably doesn't show up on your boxes because you have the go dependencies installed already -- try with a new user account or after `rm -rf ~/go`

#### Reproduction Steps

`git clone https://github.com/hashicorp/packer`
`cd packer`
`make`

results in

`go: github.com/moul/anonuuid/cmd/anonuuid imports`
`        github.com/codegangsta/cli: github.com/codegangsta/cli@v1.22.4: parsing go.mod:`
`        module declares its path as: github.com/urfave/cli`
`                but was required as: github.com/codegangsta/cli`

After fixing that by doing

`find . -type f |xargs sed -i -e 's,codegangsta/cli,urfave/cli,g'`

it proceeds a little further and barfs at

`go: github.com/moby/buildkit@v0.7.2 requires`
`        github.com/containerd/containerd@v1.4.0-0: reading github.com/containerd/containerd/go.mod at revision v1.4.0-0: unknown revision v1.4.0-0`

### Packer version

Same behavior on 1.6.1 and current git master

### Operating system and Environment details

OpenMandriva Cooker - Linux 5.8-rc7, glibc 2.32, go 1.14.3

**Comment by nywilken** [comment]
hi there thanks for reaching out. I see some build errors when running `make` but they are not related to pkgs.  I need to dive a little deeper to see what is going on. Have you tried following the steps https://learn.hashicorp.com/packer/getting-started/install to build from source? 

The Packer project has a Vagrantfile in the project root that can be used for exactly this so I was able to bring the up the box and build from source on a clean vm without issue. However, it is following the instructions outlined on the Learn site - linked above. 

I also tested outside of the GOPATH on a clean vm with `make dev` and all appears to compile as expected. Please let me know if `make dev` works for you.

**Comment by berolinux** [comment]
Hi, `make dev` works (in 1.6.1 after patching version/version.go to pretend it's a prerelease).
It's just normal `make` that fails.

**Comment by SwampDragons** [comment]
Wow, yeah, the `make` default target is definitely broken. I've pushed up a branch to just have it install dependencies and make binaries.
