### ISSUE TITLE
vmware-vmx: Error starting VM while using 'packer build'

### ISSUE THREAD

**Issue by psantanusaha** [hashicorp/packer#9693]
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue
Host Machine is a MAC VM on ESXI. I am trying to use packer to build a vmx from a base vmx configuration. When running packer build, the operation terminates with an Error: The operation was canceled.

#### Reproduction Steps
run `packer build` with vmware-vmx builder
### Packer version

sh-3.2# uname -a
Darwin SVABuilds-Mac.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 18 21:21:34 PDT 2020; root:xnu-4570.71.82.5~1/RELEASE_X86_64 x86_64

sh-3.2# packer --version
1.6.0

### Simplified Packer Buildfile
`centos_ovf_vmware.json` 
{
    "provisioners": [
      {
        "type": "shell",
        "execute_command": "sudo bash {{ .Path }}",
        "scripts": [ "install.sh" ]
      }
    ],
    "builders" : [{
    "type": "vmware-vmx",
    "source_path" : "{{user `base_image`}}",
    "boot_wait": "30s",
    "headless": true,
    "output_directory": "agent_appliance_vmx-{{user `build_version`}}",
    "vm_name": "SampleName-{{user `build_version`}}",
    "vmx_data": {
          "displayname" : "displayName",
          "memsize": "{{user `memsize`}}",
          "numvcpus": "{{user `cpus`}}",
          "virtualhw.version" : "{{user `hwver`}}",
          "disk_size": 40000
    },
    "ssh_username": "vagrant",
    "ssh_password": "vagrant",
    "ssh_timeout": "600s",
    "shutdown_command": "sudo sh -c 'sed -i 's/vagrant:.*$//g' /etc/shadow && sed -i 's/vagrant:.*$//g' /etc/passwd && rm -f /etc/sudoers.d/vagrant && shutdown -P now'"
    }],
    "variables" : {
      "build_version": "1.15.3.123",
      "memsize": "4096",
      "cpus": "4",
      "hwver":"7",
      "base_image": "output-extdisk-cent7.2/packer-vmware-iso.vmx"
    }
  }

### Packer Build Command

PACKER_LOG=1 packer build -var build_version=3.120 -var memsize=4096 -var cpus=2 centos_ovf_vmware.json

### Log Fragments and crash.log files
`sh-3.2# PACKER_LOG=1 packer build -var build_version=3.120 -var memsize=4096 -var cpus=2 centos_ovf_vmware.json
2020/07/31 15:19:34 [INFO] Packer version: 1.6.0 [go1.14.3 darwin amd64]
2020/07/31 15:19:34 Checking 'PACKER_CONFIG' for a config file path
2020/07/31 15:19:34 'PACKER_CONFIG' not set; checking the default config file path
2020/07/31 15:19:34 Attempting to open config file: /var/root/.packerconfig
2020/07/31 15:19:34 [WARN] Config file doesn't exist: /var/root/.packerconfig
2020/07/31 15:19:34 Setting cache directory: /Users/svabuild/spanva-generic-base/spanva-build-base/packer_cache
2020/07/31 15:19:34 Creating plugin client for path: /usr/local/bin/packer
2020/07/31 15:19:34 Starting plugin: /usr/local/bin/packer []string{"/usr/local/bin/packer", "plugin", "packer-builder-vmware-vmx"}
2020/07/31 15:19:34 Waiting for RPC address for: /usr/local/bin/packer
2020/07/31 15:19:34 packer-builder-vmware-vmx plugin: [INFO] Packer version: 1.6.0 [go1.14.3 darwin amd64]
2020/07/31 15:19:34 packer-builder-vmware-vmx plugin: Checking 'PACKER_CONFIG' for a config file path
2020/07/31 15:19:34 packer-builder-vmware-vmx plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/07/31 15:19:34 packer-builder-vmware-vmx plugin: Attempting to open config file: /var/root/.packerconfig
2020/07/31 15:19:34 packer-builder-vmware-vmx plugin: [WARN] Config file doesn't exist: /var/root/.packerconfig
2020/07/31 15:19:34 packer-builder-vmware-vmx plugin: Setting cache directory: /Users/svabuild/spanva-generic-base/spanva-build-base/packer_cache
2020/07/31 15:19:34 packer-builder-vmware-vmx plugin: args: []string{"packer-builder-vmware-vmx"}
2020/07/31 15:19:34 packer-builder-vmware-vmx plugin: Plugin address: unix /tmp/packer-plugin490380506
2020/07/31 15:19:34 packer-builder-vmware-vmx plugin: Waiting for connection...
2020/07/31 15:19:34 Received unix RPC address for /usr/local/bin/packer: addr is /tmp/packer-plugin490380506
2020/07/31 15:19:34 packer-builder-vmware-vmx plugin: Serving a plugin connection...
2020/07/31 15:19:34 Creating plugin client for path: /usr/local/bin/packer
2020/07/31 15:19:34 Starting plugin: /usr/local/bin/packer []string{"/usr/local/bin/packer", "plugin", "packer-provisioner-file"}
2020/07/31 15:19:34 Waiting for RPC address for: /usr/local/bin/packer
2020/07/31 15:19:35 packer-provisioner-file plugin: [INFO] Packer version: 1.6.0 [go1.14.3 darwin amd64]
2020/07/31 15:19:35 packer-provisioner-file plugin: Checking 'PACKER_CONFIG' for a config file path
2020/07/31 15:19:35 packer-provisioner-file plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/07/31 15:19:35 packer-provisioner-file plugin: Attempting to open config file: /var/root/.packerconfig
2020/07/31 15:19:35 packer-provisioner-file plugin: [WARN] Config file doesn't exist: /var/root/.packerconfig
2020/07/31 15:19:35 packer-provisioner-file plugin: Setting cache directory: /Users/svabuild/spanva-generic-base/spanva-build-base/packer_cache
2020/07/31 15:19:35 packer-provisioner-file plugin: args: []string{"packer-provisioner-file"}
2020/07/31 15:19:35 packer-provisioner-file plugin: Plugin address: unix /tmp/packer-plugin915416830
2020/07/31 15:19:35 packer-provisioner-file plugin: Waiting for connection...
2020/07/31 15:19:35 Received unix RPC address for /usr/local/bin/packer: addr is /tmp/packer-plugin915416830
2020/07/31 15:19:35 packer-provisioner-file plugin: Serving a plugin connection...
2020/07/31 15:19:35 Creating plugin client for path: /usr/local/bin/packer
2020/07/31 15:19:35 Starting plugin: /usr/local/bin/packer []string{"/usr/local/bin/packer", "plugin", "packer-provisioner-file"}
2020/07/31 15:19:35 Waiting for RPC address for: /usr/local/bin/packer
2020/07/31 15:19:35 packer-provisioner-file plugin: [INFO] Packer version: 1.6.0 [go1.14.3 darwin amd64]
2020/07/31 15:19:35 packer-provisioner-file plugin: Checking 'PACKER_CONFIG' for a config file path
2020/07/31 15:19:35 packer-provisioner-file plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/07/31 15:19:35 packer-provisioner-file plugin: Attempting to open config file: /var/root/.packerconfig
2020/07/31 15:19:35 packer-provisioner-file plugin: [WARN] Config file doesn't exist: /var/root/.packerconfig
2020/07/31 15:19:35 packer-provisioner-file plugin: Setting cache directory: /Users/svabuild/spanva-generic-base/spanva-build-base/packer_cache
2020/07/31 15:19:35 packer-provisioner-file plugin: args: []string{"packer-provisioner-file"}
2020/07/31 15:19:35 packer-provisioner-file plugin: Plugin address: unix /tmp/packer-plugin516821642
2020/07/31 15:19:35 Received unix RPC address for /usr/local/bin/packer: addr is /tmp/packer-plugin516821642
2020/07/31 15:19:35 packer-provisioner-file plugin: Waiting for connection...
2020/07/31 15:19:35 packer-provisioner-file plugin: Serving a plugin connection...
2020/07/31 15:19:35 Creating plugin client for path: /usr/local/bin/packer
2020/07/31 15:19:35 Starting plugin: /usr/local/bin/packer []string{"/usr/local/bin/packer", "plugin", "packer-provisioner-file"}
2020/07/31 15:19:35 Waiting for RPC address for: /usr/local/bin/packer
2020/07/31 15:19:35 packer-provisioner-file plugin: [INFO] Packer version: 1.6.0 [go1.14.3 darwin amd64]
2020/07/31 15:19:35 packer-provisioner-file plugin: Checking 'PACKER_CONFIG' for a config file path
2020/07/31 15:19:35 packer-provisioner-file plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/07/31 15:19:35 packer-provisioner-file plugin: Attempting to open config file: /var/root/.packerconfig
2020/07/31 15:19:35 packer-provisioner-file plugin: [WARN] Config file doesn't exist: /var/root/.packerconfig
2020/07/31 15:19:35 packer-provisioner-file plugin: Setting cache directory: /Users/svabuild/spanva-generic-base/spanva-build-base/packer_cache
2020/07/31 15:19:35 packer-provisioner-file plugin: args: []string{"packer-provisioner-file"}
2020/07/31 15:19:35 packer-provisioner-file plugin: Plugin address: unix /tmp/packer-plugin792194358
2020/07/31 15:19:35 packer-provisioner-file plugin: Waiting for connection...
2020/07/31 15:19:35 Received unix RPC address for /usr/local/bin/packer: addr is /tmp/packer-plugin792194358
2020/07/31 15:19:35 packer-provisioner-file plugin: Serving a plugin connection...
2020/07/31 15:19:35 Creating plugin client for path: /usr/local/bin/packer
2020/07/31 15:19:35 Starting plugin: /usr/local/bin/packer []string{"/usr/local/bin/packer", "plugin", "packer-provisioner-file"}
2020/07/31 15:19:35 Waiting for RPC address for: /usr/local/bin/packer
2020/07/31 15:19:35 packer-provisioner-file plugin: [INFO] Packer version: 1.6.0 [go1.14.3 darwin amd64]
2020/07/31 15:19:35 packer-provisioner-file plugin: Checking 'PACKER_CONFIG' for a config file path
2020/07/31 15:19:35 packer-provisioner-file plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/07/31 15:19:35 packer-provisioner-file plugin: Attempting to open config file: /var/root/.packerconfig
2020/07/31 15:19:35 packer-provisioner-file plugin: [WARN] Config file doesn't exist: /var/root/.packerconfig
2020/07/31 15:19:35 packer-provisioner-file plugin: Setting cache directory: /Users/svabuild/spanva-generic-base/spanva-build-base/packer_cache
2020/07/31 15:19:35 packer-provisioner-file plugin: args: []string{"packer-provisioner-file"}
2020/07/31 15:19:35 packer-provisioner-file plugin: Plugin address: unix /tmp/packer-plugin296112930
2020/07/31 15:19:35 packer-provisioner-file plugin: Waiting for connection...
2020/07/31 15:19:35 Received unix RPC address for /usr/local/bin/packer: addr is /tmp/packer-plugin296112930
2020/07/31 15:19:35 packer-provisioner-file plugin: Serving a plugin connection...
2020/07/31 15:19:35 Creating plugin client for path: /usr/local/bin/packer
2020/07/31 15:19:35 Starting plugin: /usr/local/bin/packer []string{"/usr/local/bin/packer", "plugin", "packer-provisioner-file"}
2020/07/31 15:19:35 Waiting for RPC address for: /usr/local/bin/packer
2020/07/31 15:19:35 packer-provisioner-file plugin: [INFO] Packer version: 1.6.0 [go1.14.3 darwin amd64]
2020/07/31 15:19:35 packer-provisioner-file plugin: Checking 'PACKER_CONFIG' for a config file path
2020/07/31 15:19:35 packer-provisioner-file plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/07/31 15:19:35 packer-provisioner-file plugin: Attempting to open config file: /var/root/.packerconfig
2020/07/31 15:19:35 packer-provisioner-file plugin: [WARN] Config file doesn't exist: /var/root/.packerconfig
2020/07/31 15:19:35 packer-provisioner-file plugin: Setting cache directory: /Users/svabuild/spanva-generic-base/spanva-build-base/packer_cache
2020/07/31 15:19:35 packer-provisioner-file plugin: args: []string{"packer-provisioner-file"}
2020/07/31 15:19:35 packer-provisioner-file plugin: Plugin address: unix /tmp/packer-plugin667107782
2020/07/31 15:19:35 packer-provisioner-file plugin: Waiting for connection...
2020/07/31 15:19:35 Received unix RPC address for /usr/local/bin/packer: addr is /tmp/packer-plugin667107782
2020/07/31 15:19:35 packer-provisioner-file plugin: Serving a plugin connection...
2020/07/31 15:19:35 Creating plugin client for path: /usr/local/bin/packer
2020/07/31 15:19:35 Starting plugin: /usr/local/bin/packer []string{"/usr/local/bin/packer", "plugin", "packer-provisioner-shell"}
2020/07/31 15:19:35 Waiting for RPC address for: /usr/local/bin/packer
2020/07/31 15:19:35 packer-provisioner-shell plugin: [INFO] Packer version: 1.6.0 [go1.14.3 darwin amd64]
2020/07/31 15:19:35 packer-provisioner-shell plugin: Checking 'PACKER_CONFIG' for a config file path
2020/07/31 15:19:35 packer-provisioner-shell plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/07/31 15:19:35 packer-provisioner-shell plugin: Attempting to open config file: /var/root/.packerconfig
2020/07/31 15:19:35 packer-provisioner-shell plugin: [WARN] Config file doesn't exist: /var/root/.packerconfig
2020/07/31 15:19:35 packer-provisioner-shell plugin: Setting cache directory: /Users/svabuild/spanva-generic-base/spanva-build-base/packer_cache
2020/07/31 15:19:35 packer-provisioner-shell plugin: args: []string{"packer-provisioner-shell"}
2020/07/31 15:19:35 packer-provisioner-shell plugin: Plugin address: unix /tmp/packer-plugin976644042
2020/07/31 15:19:35 packer-provisioner-shell plugin: Waiting for connection...
2020/07/31 15:19:35 Received unix RPC address for /usr/local/bin/packer: addr is /tmp/packer-plugin976644042
2020/07/31 15:19:35 packer-provisioner-shell plugin: Serving a plugin connection...
2020/07/31 15:19:35 Preparing build: vmware-vmx
2020/07/31 15:19:35 Build debug mode: false
2020/07/31 15:19:35 Force build: false
2020/07/31 15:19:35 On error:
2020/07/31 15:19:35 Waiting on builds to complete...
2020/07/31 15:19:35 Starting build run: vmware-vmx
vmware-vmx: output will be in this color.
2020/07/31 15:19:35 Running builder: vmware-vmx

2020/07/31 15:19:35 [INFO] (telemetry) Starting builder vmware-vmx
2020/07/31 15:19:35 packer-builder-vmware-vmx plugin: Detected VMware version: 11
2020/07/31 15:19:35 packer-builder-vmware-vmx plugin: Testing against vmware driver *common.Fusion6Driver, Success: true
2020/07/31 15:19:35 packer-builder-vmware-vmx plugin: No floppy files specified. Floppy disk will not be made.
==> vmware-vmx: Cloning source VM...
2020/07/31 15:19:35 packer-builder-vmware-vmx plugin: Cloning from: output-extdisk-cent7.2/packer-vmware-iso.vmx
2020/07/31 15:19:35 packer-builder-vmware-vmx plugin: Cloning to: agent_appliance_vmx-3.120/Elastica_SpanVA-3.120.vmx
2020/07/31 15:19:35 packer-builder-vmware-vmx plugin: Executing: /Applications/VMware Fusion.app/Contents/Library/vmrun -T fusion clone output-extdisk-cent7.2/packer-vmware-iso.vmx agent_appliance_vmx-3.120/Elastica_SpanVA-3.120.vmx full
2020/07/31 15:19:39 packer-builder-vmware-vmx plugin: stdout:
2020/07/31 15:19:39 packer-builder-vmware-vmx plugin: stderr:
2020/07/31 15:19:39 packer-builder-vmware-vmx plugin: Found attached disk with filename: Virtual Disk-cl1.vmdk
2020/07/31 15:19:39 packer-builder-vmware-vmx plugin: Found attached disk with filename: disk-cl1.vmdk
2020/07/31 15:19:39 packer-builder-vmware-vmx plugin: Discovered the network type: nat
2020/07/31 15:19:39 packer-builder-vmware-vmx plugin: Configuring VMX...
2020/07/31 15:19:39 packer-builder-vmware-vmx plugin: Setting VMX: 'virtualhw.version' = '7'
2020/07/31 15:19:39 packer-builder-vmware-vmx plugin: Setting VMX: 'disk_size' = '80000'
2020/07/31 15:19:39 packer-builder-vmware-vmx plugin: Setting VMX: 'displayname' = 'Elastica Audit Agent'
2020/07/31 15:19:39 packer-builder-vmware-vmx plugin: Setting VMX: 'memsize' = '4096'
2020/07/31 15:19:39 packer-builder-vmware-vmx plugin: Setting VMX: 'numvcpus' = '2'
2020/07/31 15:19:39 packer-builder-vmware-vmx plugin: Writing VMX to: agent_appliance_vmx-3.120/Elastica_SpanVA-3.120.vmx
2020/07/31 15:19:39 packer-builder-vmware-vmx plugin: Suppressing messages in VMX
2020/07/31 15:19:39 packer-builder-vmware-vmx plugin: Located networkmapper configuration file using Fusion6: /Library/Preferences/VMware Fusion/networking
2020/07/31 15:19:39 packer-builder-vmware-vmx plugin: HostIP discovered device matching nat: vmnet8
2020/07/31 15:19:39 packer-builder-vmware-vmx plugin: Host IP for the VMware machine: 172.16.157.1
2020/07/31 15:19:39 packer-builder-vmware-vmx plugin: Looking for available port between 5900 and 6000
2020/07/31 15:19:39 packer-builder-vmware-vmx plugin: Found available port: 5990 on IP: 127.0.0.1
2020/07/31 15:19:39 packer-builder-vmware-vmx plugin: Found available VNC port: 127.0.0.1:5990
2020/07/31 15:19:39 packer-builder-vmware-vmx plugin: Writing VMX to: agent_appliance_vmx-3.120/Elastica_SpanVA-3.120.vmx
==> vmware-vmx: Starting virtual machine...
    vmware-vmx: view the screen of the VM, connect via VNC with the password "U830BOPi" to
    vmware-vmx: The VM will be run headless, without a GUI. If you want to
    vmware-vmx: vnc://127.0.0.1:5990
    vmware-vmx: view the screen of the VM, connect via VNC with the password "U830BOPi" to
    vmware-vmx: vnc://127.0.0.1:5990
2020/07/31 15:19:39 packer-builder-vmware-vmx plugin: Executing: /Applications/VMware Fusion.app/Contents/Library/vmrun -T fusion start agent_appliance_vmx-3.120/Elastica_SpanVA-3.120.vmx nogui
2020/07/31 15:19:40 packer-builder-vmware-vmx plugin: stdout: 2020-07-31T15:19:40.004| ServiceImpl_Opener: PID 2836
2020/07/31 15:19:40 packer-builder-vmware-vmx plugin: Error: The operation was canceled
2020/07/31 15:19:40 packer-builder-vmware-vmx plugin: stderr:
==> vmware-vmx: Error: The operation was canceled
==> vmware-vmx: Error starting VM: VMware error: 2020-07-31T15:19:40.004| ServiceImpl_Opener: PID 2836
==> vmware-vmx: Error: The operation was canceled
==> vmware-vmx: Waiting 4.43492205s to give VMware time to clean up...
2020/07/31 15:19:44 packer-builder-vmware-vmx plugin: Executing: /Applications/VMware Fusion.app/Contents/Library/vmrun -T fusion list
2020/07/31 15:19:44 packer-builder-vmware-vmx plugin: stdout: Total running VMs: 0
2020/07/31 15:19:44 packer-builder-vmware-vmx plugin: stderr:
2020/07/31 15:19:44 packer-builder-vmware-vmx plugin: failed to unlock port lockfile: close tcp 127.0.0.1:5990: use of closed network connection
==> vmware-vmx: Deleting output directory...
2020/07/31 15:19:44 [INFO] (telemetry) ending vmware-vmx
Error: The operation was canceled
2020/07/31 15:19:44 machine readable: error-count []string{"1"}
==> Some builds didn't complete successfully and had errors:
2020/07/31 15:19:44 machine readable: vmware-vmx,error []string{"Error starting VM: VMware error: 2020-07-31T15:19:40.004| ServiceImpl_Opener: PID 2836\nError: The operation was canceled"}
Error: The operation was canceled
Build 'vmware-vmx' errored: Error starting VM: VMware error: 2020-07-31T15:19:40.004| ServiceImpl_Opener: PID 2836
Error: The operation was canceled
==> Builds finished but no artifacts were created.

2020/07/31 15:19:44 [INFO] (telemetry) Finalizing.
==> Some builds didn't complete successfully and had errors:
--> vmware-vmx: Error starting VM: VMware error: 2020-07-31T15:19:40.004| ServiceImpl_Opener: PID 2836
Error: The operation was canceled

==> Builds finished but no artifacts were created.
2020/07/31 15:19:45 waiting for all plugin processes to complete...
2020/07/31 15:19:45 /usr/local/bin/packer: plugin process exited
2020/07/31 15:19:45 /usr/local/bin/packer: plugin process exited
2020/07/31 15:19:45 /usr/local/bin/packer: plugin process exited
2020/07/31 15:19:45 /usr/local/bin/packer: plugin process exited
2020/07/31 15:19:45 /usr/local/bin/packer: plugin process exited
2020/07/31 15:19:45 /usr/local/bin/packer: plugin process exited
2020/07/31 15:19:45 /usr/local/bin/packer: plugin process exited`

**Comment by SwampDragons** [comment]
Hi, this error comes from vmware and according to their forums often means that your VM is trying and failing to boot from some kind of unclean state: 

https://communities.vmware.com/thread/553731

Are you able to boot the VM without Packer?

**Comment by SwampDragons** [comment]
Closing since I never heard back.
