### ISSUE TITLE
vsphere-iso: Function (F) key combination not working

### ISSUE THREAD

**Issue by ez12a** [hashicorp/packer#9701]
### Overview of the Issue

Following the mac example for vsphere-iso, the boot command based here:
https://github.com/hashicorp/packer/blob/a28edbaa0b93d761d09638a7e8e04dbb81c54950/builder/vsphere/examples/macos/macos-10.13.json#L42

the "Ctrl+F2" function does not work with Packer 1.6.1. It does not appear like either Ctrl or F2 are working within the guest, despite the keys appearing in the packer logs. If I revert to 1.6.0, the ctrl+f2 key is properly pressed within the guest and the installation continues.

#### Reproduction Steps

1. Use Packer 1.6.1
2. Use example: https://github.com/hashicorp/packer/blob/master/builder/vsphere/examples/macos/macos-10.13.json#L42

### Packer version

From 1.6.1

### Simplified Packer Buildfile

https://github.com/hashicorp/packer/blob/master/builder/vsphere/examples/macos/macos-10.13.json

### Operating system and Environment details

Packer builder on Windows Server 2016, x86-64
Template environment: ESXi 6.7U3 16316930

### Log Fragments and crash.log files

https://gist.github.com/ez12a/2d7eb6c6f6faffc5e63f1c88a407678a

**Comment by jhawk28** [comment]
@sylviamoss updated the boot_command to match the rest of the builders in 1.6.1 so that will be a difference.

**Comment by jhawk28** [comment]
I think I found the issue. You can see if it fixes your issue: https://app.circleci.com/pipelines/github/hashicorp/packer/6473/workflows/2536f728-eb02-48a9-bef7-2e798abdbc21/jobs/71600/artifacts
