### ISSUE TITLE
Error waiting for AMI. Reason: <nil>

### ISSUE THREAD

**Issue by georgfedermann** [hashicorp/packer#9705]
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

We are using builder type amazon-ebs to create an AMI on AWS.
Using provisioner type shell we run a build script on an EC2 instance provisioned by packer. When the build succeeds, packer will shut down the EC2 instance and wait for AWS to create an AMI.
During that process at some point, packer will stop waiting and log an error message
```
==> amazon-ebs: Waiting for AMI to become ready...
==> amazon-ebs: Error waiting for AMI. Reason: <nil>
==> amazon-ebs: Error waiting for AMI. Reason: <nil>
==> amazon-ebs: Step "stepCreateAMI" failed
==> amazon-ebs: [c] Clean up and exit, [a] abort without cleanup, or [r] retry step (build may fail even if retry succeeds)? c

```
This will happen in about 2/3 of all cases, while in 1/3 of the cases the packer run will succeed.
In any way, the AMI will be created and listed in AWS EC2 AMI view.

#### Reproduction Steps

Steps to reproduce this issue

### Packer version
1.6.0

### Simplified Packer Buildfile
```
{
    "variables": {
        "aws_access_key": "",
        "aws_secret_key": ""
    },
    "builders": [
        {
            "type": "amazon-ebs",
            "access_key": "{{user `aws_access_key`}}",
            "secret_key": "{{user `aws_secret_key`}}",
            "region": "eu-west-1",
            "source_ami_filter": {
                "filters": {
                    "image-id": "{{user `ami_id`}}"
                },
                "owners": "#####"
            },
            "instance_type": "{{user `instance_type`}}",
            "ssh_username": "{{user `username`}}",
            "ssh_password": "{{user `password`}}",
            "ami_name": "mybox {{user `my_branch` | clean_resource_name}} {{isotime | clean_resource_name}}",
            "run_tags": {
                "Name": "mybox Packer Builder {{user `my_branch` | clean_resource_name}} {{isotime | clean_resource_name}}"
            },
            "tags": {
                "Name": "{{user `instance_type` | clean_resource_name}} {{user `name_tag` | clean_resource_name}}"
            }
        }
    ],
    "provisioners": [
        {
            "type": "shell",
            "script": "scripts/bootstrap.sh",
            "execute_command": "{{ .Path }}  --branch {{user `my_branch`}}"
        }
    ]
}
```
### Operating system and Environment details

packer script is started from a CentOS 7.8 2003 64b box

### Log Fragments and crash.log files

```
==> amazon-ebs: Stopping the source instance...
    amazon-ebs: Stopping instance
==> amazon-ebs: Waiting for the instance to stop...
==> amazon-ebs: Creating #### from instance i-#####
    amazon-ebs: AMI: ami-#####
==> amazon-ebs: Waiting for AMI to become ready...
==> amazon-ebs: Error waiting for AMI. Reason: <nil>
==> amazon-ebs: Error waiting for AMI. Reason: <nil>
==> amazon-ebs: Step "stepCreateAMI" failed
==> amazon-ebs: [c] Clean up and exit, [a] abort without cleanup, or [r] retry step (build may fail even if retry succeeds)? c

```
Set the env var `PACKER_LOG=1` for maximum log detail.

**Comment by SwampDragons** [comment]
I would normally expect a value in that error if it's timeout related, but you could try the suggestions here to see if they also resolve a "nil" error value: https://packer.io/docs/builders/amazon.html#resourcenotready-error

Particularly, check out the user's solution to a similar issue here: https://github.com/hashicorp/packer/issues/6536#issuecomment-407925535. They had to increase the poll attempts to make the timeout longer.

**Comment by georgfedermann** [comment]
Thanks for your help here.
When we set these env vars:
```
AWS_MAX_ATTEMPTS=400
AWS_POLL_DELAY_SECONDS=15
```
we greatly reduce the number of occurrences of the error as stated above.
But occasionally we still get the error message: Error waiting for AMI. Reason: <nil>

Setting ```PACKER_LOG=1``` we still get the error message as listed below.
```
==> amazon-ebs: Waiting for AMI to become ready...
2020/08/06 18:59:36 packer-builder-amazon-ebs plugin: Error waiting for AMI: Failed with ResourceNotReady error, which can have a variety of causes. For help troubleshooting, check our docs: https://www.packer.io/docs/builders/amazon.html#resourcenotready-error
2020/08/06 18:59:36 packer-builder-amazon-ebs plugin: original error: ResourceNotReady: exceeded wait attempts
==> amazon-ebs: Error waiting for AMI. Reason: <nil>
==> amazon-ebs: Error waiting for AMI. Reason: <nil>
==> amazon-ebs: Step "stepCreateAMI" failed
```

**Comment by SwampDragons** [comment]
So, "ResourceNotReady: exceeded wait attempts" means it's still not a long enough wait. Is this a super big file? If you check in the amazon console, is it actually ready? Is it possible that you are using temporary credentials that are expiring during the wait?

**Comment by georgfedermann** [comment]
Increasing the timeout once more worked for us.
We could track how the packer build would finish as soon as the snapshots in AWS EC2 for the given image would become ready.
Awesome, thank you very much for your help, highly appreciated!
The snapshot size is 100GB by the way.

**Comment by SwampDragons** [comment]
Awesome! Glad I could help.
