### ISSUE TITLE
[Feature] vsphere-iso - Pass vmx data to vm 

### ISSUE THREAD

**Issue by arogarth** [hashicorp/packer#9709]
On Windows VM we want to increase vram and max resolution for the VM. See VMware KB https://kb.vmware.com/s/article/1003

The builder vsphere-iso supports vram_size parameter but it seems that is not possible to set svga.* settings.

The vmware-iso builder has `vmx_data` top pass such parameters. Something like this would be nice for vsphere-iso builder ;)

**Comment by thor** [comment]
Does perhaps the [`configuration_parameters` option for `vsphere-iso`](https://www.packer.io/docs/builders/vsphere-iso.html#configuration_parameters) work for that parameter? I know some properties can't be passed through with it, but it might work with the `svga.*` settings.

**Comment by arogarth** [comment]
Increaseing `video_ram` to 20MB does  the trick ;) I can change the resolution in Windows.

The configuration_parameter does not pass it...
