### ISSUE TITLE
Q: Azure Shared Image Gallery (replace version)

### ISSUE THREAD

**Issue by tbugfinder** [hashicorp/packer#9716]
Hello,

I've created an image to an shared image gallery in Azure successfully.
Running this another time ended up in this error message:
```
 ERROR: -> PropertyChangeNotAllowed : Changing property 'galleryImageVersion.properties.publishingProfile.source.managedImage.id' is not allowed.
==> azure-arm:
==> azure-arm: compute.GalleryImageVersionsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="PropertyCha                  ngeNotAllowed" Message="Changing property 'galleryImageVersion.properties.publishingProfile.source.managedImage.id' is not allowed." Target="galleryImageVersion.properties.publishingProfile.source                  .managedImage.id"
==> azure-arm: Provisioning step had errors: Running the cleanup provisioner, if present...
==> azure-arm:
```

Anybody knows how to get rid of that? I suspected that the existing version should be replaced (-force).

Thanks & Best

**Comment by SwampDragons** [comment]
I'm not sure you can change the image associated with a specific version. If you increment the version, it should work though.

**Comment by tbugfinder** [comment]
Indeed, packer doesn't overwrite a version within the shared image gallery / image definition.
Wouldn't that be a feature to be added using also the `-force` switch?

**Comment by SwampDragons** [comment]
We can probably do that, though I'm not sure when we'll get a chance to implement it. This probably wouldn't be too complicated for a community member to implement if y'all decide you don't want to wait for the Packer team or Microsoft to prioritize it. 

The CreateOrUpdate call [here](https://github.com/hashicorp/packer/blob/6d1a1461435512160f56d858c3d4cecc5ae2aaf5/builder/azure/arm/step_publish_to_shared_image_gallery.go#L77)

probably needs to be preceded by a check for the --force flag and a call to that same client's Delete() method to delete the image version if it already exists.
