### ISSUE TITLE
vmware-vmx does not detect vmplayer version and refuses to clone

### ISSUE THREAD

**Issue by fcerbell** [hashicorp/packer#972]
/home/Jaspersoft/DemoVM/packer $ packer --version
Packer v0.5.2
/home/Jaspersoft/DemoVM/packer $ vmplayer -v
VMware Player 6.0.1 build-1379776
/home/Jaspersoft/DemoVM/packer $ LANG=C time packer build -force -only vmware-vmx demovm.json 
vmware-vmx output will be in this color.

==> vmware-vmx: Cloning source VM...
==> vmware-vmx: Deleting output directory...
Build 'vmware-vmx' errored: Cloning is not supported with Player 5. Please use Player 6+.

==> Some builds didn't complete successfully and had errors:
--> vmware-vmx: Cloning is not supported with Player 5. Please use Player 6+.

==> Builds finished but no artifacts were created.
Command exited with non-zero status 1
0.05user 0.02system 0:00.06elapsed 114%CPU (0avgtext+0avgdata 6040maxresident)k
256inputs+0outputs (1major+9838minor)pagefaults 0swaps

**Comment by adamenger** [comment]
@Tehranian thanks for that message, installing the license also fixed my issue.

**Comment by bivas** [comment]
I'm having this issue with Packer 0.7.5 and VMware Player 6.0.3 on Ubuntu Server 14.
I've installed VMware Player bundle without Workstation (with VIX SDK):

```sh
$ vmware-vix.bundle --list-products

Product Name         Product Version
==================== ====================
vmware-player        6.0.3.1895310
vmware-vix           1.13.0.1295980
```

Getting the same `Cloning is not supported with VMWare Player version 5. Please use VMWare Player version 6, or greater.` when running `vmware-vmx` builder.

**Comment by bhumikajain1234** [comment]
Any update on above?
i also installed the below drivers on linux
==================== ====================
vmware-vix           1.17.0.6661328
vmware-player        6.0.1.1379776
 but still getting error ,
Build 'vmware-vmx' errored: Cloning is not supported with VMWare Player version 5. Please use VMWare Player version 6, or greater.

please let me know what need to be done to fix this?
