### ISSUE TITLE
vsphere-clone failed due to network 'xxxx' not found.

### ISSUE THREAD

**Issue by wilber82** [hashicorp/packer#9740]
**Overview of the Issue**
I'm trying to create image with vsphere-clone builder. Packer cannot find the specified network when start cloning.
I used following value in json file:
`"network": "Test-192.168.0.0/24"`
It looks like Packer cannot deals with existing network which contains "/".

**Reproduction Steps**
This is a non-reproduction issue. It only happened on existing network which name contains "/" in my environment.
1. The user I'm using is full admin permission. It can see and change network in vSphere Web Client.
2. Created a new network with similar name format. It works fine.
3. Changed the network name to other existing network which doesn't contain "/" in name. It works fine.
4. Grabbed the problem network information by PowerCLI. It works fine.
5. Tried to use `"network": "Test-192.168.0.0\/24"`. Same error.

**Packer version**
1.6

**Operating system and Environment details**
Windows 10 (Run Packer)
ESXi 6.7
vCenter 6.7

**Log Fragments and crash.log files**
[packer.log](https://github.com/hashicorp/packer/files/5052277/packer.log)

**Comment by jhawk28** [comment]
packer is just passing the network field into the govmomi finder.NetworkList() so the issue may be with the govmomi API. See if it works with the govc command instead of PowerCLI. (https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#find)

**Comment by ChrisAtHashiCorp** [comment]
@wilber82 

Can you try to use the network name in an encoded fashion? For example:
  "network": "Test-192.168.0.0/24"
Becomes:
  "network": "Test-192.168.0.0%2F24"

That's encoding the / as %2F.

Hopefully that will stop munging the URI.

**Comment by wilber82** [comment]
> packer is just passing the network field into the govmomi finder.NetworkList() so the issue may be with the govmomi API. See if it works with the govc command instead of PowerCLI. (https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#find)

Thanks for the replying. I tried to grab network names with govmomi. I can see the network name is listed out.
I used following command to list all networks in the data center:
`.\govc.exe find -dc=[vCenter DC name] -type=n -u=[User Name]:[Password]@[vCenter FQDN] -k=true`

**Comment by wilber82** [comment]
> @wilber82
> 
> Can you try to use the network name in an encoded fashion? For example:
> "network": "Test-192.168.0.0/24"
> Becomes:
> "network": "Test-192.168.0.0%2F24"
> 
> That's encoding the / as %2F.
> 
> Hopefully that will stop munging the URI.

It doesn't work....

**Comment by jhawk28** [comment]
@wilber82 see if you can use the find command to find the specific network, not just all of them

**Comment by wilber82** [comment]
> @wilber82 see if you can use the find command to find the specific network, not just all of them

@jhawk28 , would you mind to provide me the correct command line? I tried few but failed. :-)

**Comment by jhawk28** [comment]
try something like this: `govc find -type n ./network -name "Test-192.168.0.0/24"`

**Comment by wilber82** [comment]
> try something like this: `govc find -type n ./network -name "Test-192.168.0.0/24"`

I have figured it out.
The reason is the network `Test-192.168.0.0/24` is under a network folder in vCenter Server. Packer cannot detects the network.
It works after I moved the network out of the folder.

I'm not sure is this a bug, or something I should specific in json.

**Comment by ChrisAtHashiCorp** [comment]
Did you try to put the full path in and see if Packer can pick it up?

Example:
`"network": "/path/to/Test-192.168.0.0%2f24"`

**Comment by wilber82** [comment]
> Did you try to put the full path in and see if Packer can pick it up?
> 
> Example:
> `"network": "/path/to/Test-192.168.0.0%2f24"`

@ChrisAtHashiCorp , I did a testing again. It works with following format:

`"network": "L1-folder/L2-folder/Test-192.168.0.0/24"`

No need to use %2f. 

Looks like the document need to be improved?

> network (string) - Set the network in which the VM will be connected to. If no network is specified, host must be specified to allow Packer to look for the available network.

**Comment by ChrisAtHashiCorp** [comment]
@wilber82

Fantastic! Glad we were able to work this out.

This has the same issue with folder paths for VM folders, or nested resource pools, etc. You must use the full path, and sometimes it's not entirely clear in the docs or the errors as you've experienced.

We've fixed some of the documentation for this.

Thanks!
