### ISSUE TITLE
Builder:vpshere-iso - content_library_destination does not work as expected 

### ISSUE THREAD

**Issue by mike-19** [hashicorp/packer#9770]
#### Overview of the Issue

content_library_destination  fails with  parsing errors for vpshere-iso, packer fails with the below error 
Error: unknown configuration key: "content_library_destination"

#### Reproduction Step

in packer configuration include the below and run the packer 
 
`"convert_to_template": false`
`      "content_library_destination" : {
        "library": "PackerTemplates"
      },`
    
### Packer version

1.5.6

### Simplified Packer Buildfile

n/a

### Operating system and Environment details
OS is ubuntu Xenial 

### Log Fragments and crash.log files

unknown configuration key: "content_library_destination"; raws is []interface {}{map[string]interface {}{"CPUs":"1", "RAM":"1024", "RAM_reserve_all":false, "boot_command":"<esc> <wait> linux text ks=hd:fd0:/ks.cfg <enter>", "boot_order":"disk,cdrom,floppy", "boot_wait":"20s", "cluster":"lab", "content_library_destination":map[interface {}]interface {}{"library":"PackerTemplates"}, "datacenter":"lab", "datastore":"DS01", "disk_controller_type":"pvscsi", "disk_size":"15000", "disk_thin_provisioned":true, "floppy_files":[]interface {}{"ks.cfg"}, "guest_os_type":"rhel7_64Guest", "insecure_connection":"true", "iso_paths":[]interface {}{"[Templates-DATASTORE-DEPLOY] PackerISO/rhel7-6.iso"}, "network":"deploynetwork", "network_card":"vmxnet3", "password":"TEST", "ssh_password":"TEST", "ssh_username":"loginuser", "username":"administrator", "vcenter_server":"vcenter.test.com, "vm_name":"packer-image"}, map[string]interface {}{"packer_build_name":"vsphere-iso", "packer_builder_type":"vsphere-iso", "packer_debug":false, "packer_force":true, "packer_on_error":"ask", "packer_template_path":"base/packer.json", "packer_user_variables":map[interface {}]interface {}{"":"", "sshCredential":"test", "vCenterCredential":"test"}}}

 and ctx data is map[interface {}]interface {}(nil)

**Comment by nywilken** [comment]
Hello @mike-19 support for `content_library_destination` was added in the v1.6.1 Packer release. Please try running your configuration against the latest version of Packer. 

This should be resolved with the latest release so I am going to close this issue. If after upgrading you are still running into problems post a new comment here and I will gladly reopen. Cheers!

**Comment by mike-19** [comment]
thx for the pointers will try and update here
