### ISSUE TITLE
aws_secretsmanager errors with plaintext secrets

### ISSUE THREAD

**Issue by jgilfoil** [hashicorp/packer#9771]
#### Overview of the Issue

Trying to use aws_secretsmanager to retrive a secret that is stored as plaintext in Secrets Manager gives an error as shown below. This function works fine if the secret is stored as a json key/value pair. I believe this should be either fixed to allow plaintext or the docs updated to indicate secrets need to be stored as json key/value pairs.

#### Reproduction Steps

template.json:
```
{
    "variables": {
      "aws_access_key": "",
      "aws_secret_key": "",
      "password": "{{ aws_secretsmanager `test` }}"
    },
...
```
throws this error:
```
root@0ab2baf2b829:/opt/redash/packer# packer build template.json
Error:
template: root:1:3: executing "root" at <aws_secretsmanager `test`>:
error calling aws_secretsmanager: Error getting secret: invalid character 'T'
looking for beginning of value
```
Secret retrieves from aws cli just fine:
```
root@0ab2baf2b829:/opt/redash/packer# aws secretsmanager get-secret-value --secret-id test
    "ARN": "arn:aws:secretsmanager:us-east-1:REDACTED:secret:test-yKsNsU",
    "Name": "test",
    "VersionId": "a30fe681-6593-41de-a6dc-0472ecd8c357",
    "SecretString": "ThisisThePassword",
    "VersionStages": [
        "AWSCURRENT"
    ],
    "CreatedDate": "2020-08-14T15:09:10.238000+00:00"
}
```

### Packer version
root@8b1a6fa06dda:/opt/redash/packer# packer version 
Packer v1.6.1

### Operating system and Environment details

docker pull ubuntu:bionic-20200311

**Comment by nywilken** [comment]
Thanks for reaching out. The integration with the Secrets Manager currently only works with key/pair secrets. We will take a look to see about updating it to support single string, non key/pair, secrets. In the meantime you could store the secret with no key to have  Packer parse and properly assign the secret key to the variable. 

```json 
{
 "":"ThisIsThePassword"
}
```

**Comment by nywilken** [comment]
I went ahead an opened a PR to support plaintext secrets. You can download test binaries from the following link if you would like to give it a try https://app.circleci.com/pipelines/github/hashicorp/packer/6689/workflows/effd089b-e352-4cd2-b78c-f6edcf9e4d28/jobs/74616/artifacts

In the meantime, I will work on updating the Secrets Manager integration documentation.
