### ISSUE TITLE
VMWare-iso unable to download preconfiguration file

### ISSUE THREAD

**Issue by jonathanbiard** [hashicorp/packer#978]
I am able to start a debian installation for vmware using the vmware-iso builder but when it is time to download the preconfiguration file, it fails to download it. I went to my browser (on the host) and the file is definitely accessible from there. The network adapter for the VM is NAT by default. The debian installation also says that the network configuration was finished successfully.. in fact, it's the last thing it says before waiting for 30 seconds and finally failing with the "unable to download preseed.cfg" message.

Please note that the URL that debian fails to fetch is the exact one that I type to find it in my browser. So the JSON template is definitely doing things correctly since the URL is correct.

``` json
"boot_command": [
    "<esc><wait>",
    "install <wait>",
    "url=http://{{.HTTPIP}}:{{.HTTPPort}}/preseed.cfg <wait>",
    "debian-installer=en_US <wait>",
    "auto <wait>",
    "locale=en_US <wait>",
    "kbd-chooser/method=us <wait>",
    "netcfg/get_hostname={{user `host_name`}} <wait>",
    "netcfg/get_domain={{user `domain_name`}} <wait>",
    "fb=false <wait>",
    "debconf/frontend=noninteractive <wait>",
    "console-setup/ask_detect=false <wait>",
    "console-keymaps-at/keymap=us <wait>",
    "keyboard-configuration/xkb-keymap=us <wait>",
    "<enter><wait>"
]
```

**Comment by stephen-mw** [comment]
Thanks for the tip @madorn. Disabling the firewall worked for me. I was getting a hanging install when using vmware-iso on ubuntu 12.04 when it attempted to download the preseed install.
