### ISSUE TITLE
Packer freezes with SIGTTOU when run as bash background job that generates a progressbar

### ISSUE THREAD

**Issue by brian-maloney** [hashicorp/packer#9786]
* Packer version: 1.6.0
* Host: Linux

This issue is a continuation of #7677.  When running recent Packer builds (I used 1.6.0) in the background, `virtualbox-iso` builder hangs on download, blocked on SIGTTOU.  I am inferring that the fix in GH-8101 does not prevent the progressbar implementation from attempting to write to the TTY.

I was able to work around this by adding `trap '' SIGTTOU` to my build script, so this isn't urgent for me.

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out! Does this still happen if you set the `--machine-readable` flag?

**Comment by brian-maloney** [comment]
@SwampDragons Sorry for not mentioning, the first thing I tried after reading #7677 was `-machine-readable`, but unfortunately it does not help.  I was actually quite surprised that when running in the foreground with `-machine-readable` I still get the very much 'human-readable' progress bar:
```
1597785052,,ui,say,==> virtualbox-iso: Retrieving ISO
1597785052,,ui,say,==> virtualbox-iso: Trying http://<mirror>/centos/7.8.2003/isos/x86_64/CentOS-7-x86_64-NetInstall-2003.iso
1597785052,,ui,say,==> virtualbox-iso: Trying http://<mirror>/centos/7.8.2003/isos/x86_64/CentOS-7-x86_64-NetInstall-2003.iso?checksum=sha256%3A101bc813d2af9ccf534d112cbe8670e6d900425b297d1a4d2529c5ad5f226372
CentOS-7-x86_64-NetInstall-2003.iso 319.23 MiB / 568.00 MiB [=====================================================================>-----------------------------------------------------]  56.20% 00m02s
CentOS-7-x86_64-NetInstall-2003.iso 332.85 MiB / 568.00 MiB [==========================================================================>----------------------------------------------------]  58.60% 3s
```

**Comment by SwampDragons** [comment]
Ah, no, I'm sorry for not checking your version -- we fixed a bug making sure that the progress bar actually doesn't get created when the machine-readable flag is set in v1.6.1: https://github.com/hashicorp/packer/pull/9448

If you upgrade, does that work for you?

**Comment by brian-maloney** [comment]
It does indeed work in 1.6.1, sorry for not trying that first.

I am fine with using `-machine-readable` or trapping the signal in my shell since it gets me working again, but I wonder if the machine-readable approach should actually be considered a "fix" for this issue.  Consider our (presumably very common) workflow - we run Packer in a CICD tool, and in the uncommon case of a failure that isn't resolved by the retries already provided by our CICD system, an engineer will be notified of the failure.  The next step would be the engineer opening the CICD job and reviewing the logs in there, when they'll be faced with "machine-readable" formatted logs.  Naturally in a more mature organization, or an organization where build failures are very common, you'd probably prefer to have a system parse the logs and take some action in response, but I don't expect our organization will be at that point for a long time (unless these builds prove to be more unreliable than I expect).  So to me it feels like having "machine readable" be the officially supported method for running in the background (especially under CICD) isn't really a complete solution.

Unrequested feedback aside (sorry!), I'm going to close this since it appears to be "working as designed" as of 1.6.1.

**Comment by SwampDragons** [comment]
I completely agree that this is not sufficient -- but it helps me to know that the solution we implemented for that flag will also work for a backgrounded process.
