### ISSUE TITLE
Parsing of PKR_VAR_ when variable does not have a type

### ISSUE THREAD

**Issue by jsmcnair** [hashicorp/packer#9789]
#### Overview of the Issue

I noticed I get an error when providing a variable's value using a `PKR_VAR_` environment variable if it doesn't have a declared type. The error varies depending on the value of the environment variable.

I suggest this is a bug as I think at very least the documentation needs to be updated to state the type should be explicit for strings and integers, but the behaviour is inconsistent: strings and integers generate a failure, lists and maps do not. 

I see that it's being parsed an expression if the type is not explicit, but shouldn't it be to parse a string or an int?

#### Reproduction Steps

1. Set an environment variable for a variable that does not have a default value
2. Try to validate the packer file (example below)
3. Observe the errors

There is a different error depending on the value of the variable:
```shell
$ export PKR_VAR_testvar=something
$ packer validate -only "*.example" .
Error: Variables not allowed

  on <value for var.testvar from env> line 1:
  (source code not available)

Variables may not be used here.
```

```shell
$ export PKR_VAR_testvar=/path/to/something
$ packer validate -only "*.example" .
Error: Invalid expression

  on <value for var.testvar from env> line 1:
  (source code not available)

Expected the start of an expression, but found an invalid expression token.
```

```shell
$ export PKR_VAR_testvar=[\"complex\",\"structure\"]
$ packer validate -only "*.example" .
$
```

### Packer version

Nightly build (aa2418c)

### Simplified Packer Buildfile

```hcl
source "null" "example" {
    communicator = "none"
}

variable "testvar" { }

build {
    sources = [ "source.null.example" ]
}
```

### Operating system and Environment details

Mac OSX but saw the same when running in a Docker container

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out. I did recently write some new docs for this here: https://github.com/hashicorp/packer/pull/9743 but haven't pushed them to the prod site yet; do these approximately cover what you were thinking?

I suspect the reason strings/integers fail where maps and lists don't is that strings/integers could be interpreted as variable names whereas maps clearly aren't variable names.

**Comment by jsmcnair** [comment]
@SwampDragons ah yes that's good! I think that covers it but perhaps we should make reference to it in the environment variables section also, to avoid any ambiguity?

**Comment by azr** [comment]
Hello there ! About this, I'd like to add that Terraform sort of guesses it's a string :

```hcl
variable "dnsimple_domain" {
  description = "The domain we are creating a record for."
}
```
```shellsession
$ terraform apply -var dnsimple_domain=potato 

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

It even prompts for it when we don't set anything:

```shellsession
$ terraform apply 
var.dnsimple_domain
  The domain we are creating a record for.

  Enter a value: 
```

**Comment by SwampDragons** [comment]
@azr Do you think we should reopen this and update to behave the same way?

**Comment by azr** [comment]
🤔  Yes ! 🙂
