### ISSUE TITLE
<leftCtrlOn> isn't recognized by vSphere console

### ISSUE THREAD

**Issue by tonyplovich** [hashicorp/packer#9803]
#### Overview of the Issue
I'm attempting to get the RHEL 7.7 DVD to boot into a Kickstarter file using the vsphere-iso builder.  This requires editing the GRUB boot parameters for the kernel, and then pressing 'ctrl-x' to initiate the boot.

Watching from the VM console, Packer updates the boot param correctly, but when it comes time to press ctrl-x it just prints 'x' and hangs.  At this point I can get it to continue by manually connecting to the VM's console, removing the 'x', and hitting ctrl-x myself.

#### Reproduction Steps

1. Setup a vsphere-iso builder using a [CentOS 7 DVD ISO](http://bay.uchicago.edu/centos/7.8.2003/isos/x86_64/CentOS-7-x86_64-DVD-2003.iso)
2. Configure a boot command that edits the grub entry
`"boot_command": [
    "<wait>",
    "<up>e<wait>",
    "<wait><down><wait><down><wait><end>",
    "<leftCtrlOn>x<leftCtrlOff>`
3. Execute a packer build
4. Open a vSphere console to the VM

### Packer version

Packer v1.6.1
VMware ESXi/ vCenter: 6.7.0

PACKER_LOG=1 output:
...
2020/08/23 18:54:14 packer-builder-vsphere-iso plugin: Special code '<leftctrl>' found, replacing with: CodeLeftControl
2020/08/23 18:54:14 packer-builder-vsphere-iso plugin: [INFO] Waiting 1s
2020/08/23 18:54:15 packer-builder-vsphere-iso plugin: Sending char 'x', code CodeX, shift false
2020/08/23 18:54:15 packer-builder-vsphere-iso plugin: Special code '<leftctrl>' found, replacing with: CodeLeftControl
2020/08/23 18:54:15 packer-builder-vsphere-iso plugin: [INFO] Waiting for IP, up to total timeout: 30m0s, settle timeout: 5s
...

**Comment by sylviamoss** [comment]
Hey there, thanks for reaching out! 
This is already fixed for our next release by https://github.com/hashicorp/packer/pull/9739. You can use our nightly pre-release binaries until 1.6.2 is released. Here they are https://github.com/hashicorp/packer/releases/tag/nightly!
