### ISSUE TITLE
ansible-remote fails on windows due to identities only

### ISSUE THREAD

**Issue by gamethis** [hashicorp/packer#9808]
https://github.com/hashicorp/packer/blob/master/provisioner/ansible/provisioner.go#L702-705
causes an issue on windows ssh

#### Overview of the Issue

adding identitiesonly=yes to the ansible-playbook command breaks the ability for windows ssh to connect with ansible
also It can not be overridden by simply adding the environment variable version to `ansible_env_vars`.

calling ansible-playbook without works

#### Reproduction Steps
use default windows ssh in your setup of build 
https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH
use package build from below

### Packer version

From `packer version` 1.6.1

### Simplified Packer Buildfile

```
{
    "variables": {
        "iso_url": null,
        "iso_checksum": null,
        "identifier": null
    },
    "builders": [{
        "name": "windows-build",
        "type": "vmware-iso",
        "disk_size": 100000,
        "disk_type_id": "0",
        "guest_os_type": "windows9srv-64",
        "iso_url": "{{user `iso_url`}}",
        "iso_checksum": "sha256:{{user `iso_checksum`}}",
        "communicator": "ssh",
        "ssh_username": "{{env `ssh_username`}}",
        "ssh_password": "{{env `ssh_password`}}",
        "ssh_timeout": "240m",
        "ssh_handshake_attempts": 100,
        "ssh_read_write_timeout": "240m",
        "headless": "TRUE",
        "floppy_dirs": [
            "{{user `path`}}/floppy/{{user `identifier`}}/*"
        ],
        "shutdown_timeout": "120m",
        "cpus": 4,
        "cores": 1,
        "memory": 8192,
        "network": "nat",
        "network_adapter_type": "vmxnet3",
        "disk_adapter_type": "pvscsi",
        "version": "13",
        "keep_registered": false
    }],
    "provisioners": [{
        "playbook_file": "{{user `path`}}/template.yaml",
        "type": "ansible",
        "ansible_env_vars": ["SSH_EXTRA_ARGS=''"],

        "extra_arguments": ["-vv",
            "-T 1200",
            "--extra-vars",
            "ansible_user={{env `ssh_username`}}",
            "--extra-vars",
            "ansible_password={{env `ssh_password`}}"
        ],
        "groups": "windows",
        "inventory_file": "./inventory.yaml",
        "pause_before": "20s",
        "timeout": "2h"
    }]
}
```
### Operating system and Environment details

running packer on Centos7
against a windows 2019 and windows 2016 servers.

### Log Fragments and crash.log files

fatal: ###.###.###.###]: FAILED! => {"ansible_facts": {}, "changed": false, "failed_modules": {"setup": {"f
ailed": true, "module_stderr": "Warning: Permanently added '###.###.###.###' (ECDSA) to the list of known hosts.\r\nParameter format not correct - ;
\r\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}}, "msg": "The following modules failed to exec
ute: setup\n"}

**Comment by gamethis** [comment]
I would suggest to fix this that we add an option for `ssh-extra-args` which would default to the current value `-o IdentitiesOnly=yes`

**Comment by gamethis** [comment]
alternative would be to add checkArg for the variable as an `extra_arguments` to make sure it was not provided to override

**Comment by SwampDragons** [comment]
I think adding an "ssh-extra-args" field makes sense. Would you be interested in making a PR adding this?

**Comment by gamethis** [comment]
Yeah i would be happy to do that
