### ISSUE TITLE
Centos 7 kickstart file fails with Unkown command: to

### ISSUE THREAD

**Issue by DaniBet** [hashicorp/packer#9817]
I want to create a virtual machine image using Packer with a kickstarter file. It fails everytime with: ```Unkown command: to``` at the first line ```install```. Do you have any idea why?

I post my template even if I think that problems doesn't come from template.json:
```
{
  "builders": [
    {
      "CPUs": 2,
      "RAM": 4096,
      "RAM_reserve_all": true,
      "datastore": "xxx-lds1",
      "disk_controller_type": "pvscsi",
      "folder": "CG",
      "guest_os_type": "centos7_64Guest",
      "insecure_connection": "true",
	  "boot_command": [
    "<tab><wait>",
    " ks=https://.../ks.cfg<enter>"
 ],
      "boot_wait": "5s",
      "iso_paths": [
        "[xxx-lds1] iso/CentOS-7-x86_64-Minimal-2003.iso"
      ],
      "network_adapters": [
        {
          "network": "xxx-VM Network",
          "network_card": "xxx"
        }
      ],
      "password": "{{user `vcenter_password`}}",
      "ssh_password": "xxx",
      "ssh_username": "xxx",
      "storage": [
        {
          "disk_size": 32768,
          "disk_thin_provisioned": true
        }
      ],
      "type": "vsphere-iso",
      "username": "{{user `vcenter_username`}}",
      "vcenter_server": "{{user `vcenter_host`}}",
      "vm_name": "centos7-template",
      "host": "CG/xxx",
      "resource_pool": "Test",
      "datacenter": "XX"
    }
  ],
  "provisioners": [
    {
      "inline": [
        "ls /"
      ],
      "type": "shell"
    }
  ]
}
```

**Comment by nywilken** [comment]
Hi there please provide the full build logs as it may help shed some light on where the issue may be occurring. If you think this is a bug please provide the information requested in the bug report template along with any related screenshots. 

With that said, is the error occurring during the boot command process?

If you haven't already check the ks.cfg for errors and that the boot_command is configured properly. You may find the Chef Packer templates helpful for boot related issues https://github.com/chef/bento/blob/master/packer_templates/centos/centos-7.8-x86_64.json

Lastly, I recommend you reach out to the [community forum](https://discuss.hashicorp.com/c/packer/). Issues opened here on the Packer issue tracker are only viewed by a small handful of developers who work on the tool, and we don't always have the most depth or experience when it comes to custom issues with particular build configurations. Cheers!

**Comment by DaniBet** [comment]
Hello,

The log from packer is stuck in "Waiting for ip" and this error "Unkown command: to" is thrown by the console from Vsphere where I can see the installation process.

**Comment by nywilken** [comment]
Hi @DaniBet thanks for the additional information. It makes sense that Packer would be stuck waiting for an IP as the VM is not in a running state. It is difficult to understand what was the last step executed by Packer for your template or the command that was issued on vSphere without full logs. 

Have you checked the vSphere logs for failing commands or messages?  

I recommend you reach out to the [community forum](https://discuss.hashicorp.com/c/packer/) for additional help so folks with more vSphere experience can chime in.

**Comment by SwampDragons** [comment]
I don't think that's a complete boot command. see how the example in 

https://github.com/chef/bento/blob/master/packer_templates/centos/centos-7.8-x86_64.json#L31

uses `text`? I'm pretty sure that's necessary to get the ks read properly.

**Comment by sylviamoss** [comment]
closing this one because https://github.com/hashicorp/packer/issues/9826 shows that the `text` suggested my @SwampDragons  worked 👍
