### ISSUE TITLE
[vmware-iso] Packer hangs while "Starting virtual machine..."

### ISSUE THREAD

**Issue by arthurschreiber** [hashicorp/packer#982]
I've been using packer to build vagrant baseboxes for virtualbox, without any issues.

I now want to also build vagrant baseboxes for vmware workstation, but I run into some weird issues there.

Basically, I'm using the https://github.com/mitchellh/packer-ubuntu-12.04-docker repo for testing. If I start the packer build through `packer build template.json`, I see the following output:

```
==> vmware-iso: Creating virtual machine disk
==> vmware-iso: Building and writing VMX file
==> vmware-iso: Starting HTTP server on port 8555
==> vmware-iso: Starting virtual machine...
```

And that's it. Nothing happens afterwards, it's just hanging at this step.

I'm running on Windows 7, and I tried to build a vmware boxes with both packer 0.5.2 and 0.4.1, and VMWare Workstation 9.0.3 and 10.0.1 (and any combination thereof).

Any Idea what's going on?

**Comment by dragon788** [comment]
Here's a site with a very nice list of the vmx guest os options for VMware. http://sanbarrow.com/vmx/vmx-guestos.html

**Comment by spuder** [comment]
I also ran into this problem when creating windows 2012 R2 images with vmware

My solution was to change `guest_os_type` to `windows8srv-64`

      "guest_os_type": "windows8srv-64",

Once the guest_os_type is correct, vmware will start properly.

**Comment by dishbreak** [comment]
This is an old thread, but I think it's worth leaving this behind for the next person who runs into this. If you're running packer on a corporate machine, you may have a security suite installed that interferes with vmrun and prevents it from returning. 

https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=2050353

In my case, I had to temporarily disable the firewall and host IPS on my laptop. Once that's done, McAfee allows the procedure to finish.  For me, this wasn't a Packer issue, it was a security software issue.

**Comment by howardjones** [comment]
I've just run into this and took quite a bit of digging in the hostd.log to work out what it was. So, adding for maybe more searchability:

    2017-04-19T19:15:36.254Z error hostd[41744B70] [Originator@6876 sub=Default opID=a8bde297 user=root] Unable to convert Vigor value 'Windows2012_64' of type 'char const*' to VIM type 'Vim::Vm::GuestOsDescriptor::GuestOsIdentifier'

In my case I had moved from a virtualbox template to a vmware one, and didn't really pay attention to this os type value. But the behaviour of just repeatedly trying to start without any error message more specific than "general error" wasn't very enlightening.
