### ISSUE TITLE
ssh: unable to authenticate, attempted methods [none password]

### ISSUE THREAD

**Issue by DaniBet** [hashicorp/packer#9826]
Hello,

After running the kickstater file, it seems that the authentication fails with ```ssh: unable to authenticate, attempted methods [none password] ```

Any ideas?

My template:
```
{
  "builders": [
    {
      "CPUs": 2,
      "RAM": 4096,
      "RAM_reserve_all": true,
      "datastore": "ebuchcg2-lds1",
      "disk_controller_type": "pvscsi",
      "folder": "CG",
      "insecure_connection": "true",
	  "boot_command": [
        "<tab> text ks=https://raw.githubusercontent.com/danibet/things/master/ks.cfg<enter><wait>"
      ],
      "boot_wait": "5s",
      "iso_paths": [
        "[ebuchcg2-lds1] iso/CentOS-8.2.2004-x86_64-dvd1.iso"
      ],
      "network_adapters": [
        {
          "network": "ebuchcg2-VM Network",
          "network_card": "vmxnet3"
        }
      ],
      "password": "{{user `vcenter_password`}}",
	  "shutdown_command":"echo 'centos' | sudo -S shutdown -P now",
      "ssh_password": "vagrant",
      "ssh_username": "vagrant",
      "storage": [
        {
          "disk_size": 32768,
          "disk_thin_provisioned": true
        }
      ],
      "type": "vsphere-iso",
      "username": "{{user `vcenter_username`}}",
      "vcenter_server": "{{user `vcenter_host`}}",
      "vm_name": "centos7-template",
      "host": "XXX",
      "resource_pool": "Test",
      "datacenter": "RD"
    }
  ],
  "provisioners": [
    {
      "inline": [
        "yum update"	
      ],
      "type": "shell"
    }
  ]
}

```
My kickstarter:

```
# Turning on text-mode installation (little quicker than GUI)
text

# Setting up authentication and keyboard
auth --useshadow --enablemd5
keyboard --vckeymap=us --xlayouts='us'

# Installation files source (CentOS-7.0-1406-x86_64-Minimal.iso)
cdrom

# Using only primary disk, ignoring others
ignoredisk --only-use=sda

# Setting up language to English
lang en-US.UTF-8

# Setting up network interface to DHCP
network --bootproto=dhcp --ipv6=auto --hostname=centos-ks.local --activate

# Root password (remember that plaintext only for information purposes)
rootpw --iscrypted 63623900c8bbf21c706c45dcb7a2c083
user --name=vagrant --iscrypted --password=63623900c8bbf21c706c45dcb7a2c083

# Setting up firewall and enabling SSH for remote management
firewall --disabled

# Setting timezone
timezone Europe/Warsaw --isUtc

# Setting up Security-Enhanced Linux into enforcing
selinux --disabled

# Setting up MBR
bootloader --location=mbr --boot-drive=sda

# Setting up Logical Volume Manager and autopartitioning
clearpart --all --drives=sda --initlabel
autopart --type=lvm

# Eject cdrom and reboot
reboot --eject

# Installing only packages for minimal install 
%packages
@Core
chrony
%end

%post
yum update
yum -y install open-vm-tools
%end
```

```
20/08/26 01:50:50 packer_windows_amd64.exe plugin: VM IP is still the same: 10.133.65.31
2020/08/26 01:50:50 packer_windows_amd64.exe plugin: VM IP seems stable enough: 10.133.65.31
==> vsphere-iso: IP address: 10.133.65.31
2020/08/26 01:50:50 packer_windows_amd64.exe plugin: [INFO] Waiting for SSH, up to timeout: 5m0s
==> vsphere-iso: Using ssh communicator to connect: 10.133.65.31
==> vsphere-iso: Waiting for SSH to become available...
2020/08/26 01:50:50 packer_windows_amd64.exe plugin: [INFO] Attempting SSH connection to 10.133.65.31:22...
2020/08/26 01:50:50 packer_windows_amd64.exe plugin: [DEBUG] reconnecting to TCP connection for SSH
2020/08/26 01:50:50 packer_windows_amd64.exe plugin: [DEBUG] handshaking with SSH
2020/08/26 01:50:53 packer_windows_amd64.exe plugin: [DEBUG] SSH handshake err: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain
2020/08/26 01:50:53 packer_windows_amd64.exe plugin: [DEBUG] Detected authentication error. Increasing handshake attempts.
2020/08/26 01:51:00 packer_windows_amd64.exe plugin: [INFO] Attempting SSH connection to 10.133.65.31:22...
2020/08/26 01:51:00 packer_windows_amd64.exe plugin: [DEBUG] reconnecting to TCP connection for SSH
2020/08/26 01:51:00 packer_windows_amd64.exe plugin: [DEBUG] handshaking with SSH
```

**Comment by sylviamoss** [comment]
Is the encrypted password in the kickstarter file the correct/valid hash for `vagrant`? Could you try it as --plaintext to see if it works?

**Comment by robertluwang** [comment]
Same error here using plaintext 
rootpw vagrant
user --name=vagrant --plaintext --password vagrant --groups=vagrant,wheel

packer debug 
==> virtualbox-iso: Using ssh communicator to connect: 127.0.0.1
==> virtualbox-iso: Waiting for SSH to become available...
==> virtualbox-iso: Error waiting for SSH: Packer experienced an authentication error when trying to connect via SSH. This can happen if your username/password are wrong. You may want to double-check your credentials as part of your debugging process. original error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain

packer.exe version
Packer v1.6.1

before packer clean up, I can ssh to 127.0.0.1:3839 to centos8 vm as root/vagrant, will see NAT interface up, but user vagrant not created and .ssh not existing yet.

[root@localhost ~]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:fa:67:fe brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic noprefixroute enp0s3
       valid_lft 85841sec preferred_lft 85841sec
    inet6 fe80::a00:27ff:fefa:67fe/64 scope link noprefixroute
       valid_lft forever preferred_lft forever

[root@localhost ~]# ip r
default via 10.0.2.2 dev enp0s3 proto dhcp metric 100
10.0.2.0/24 dev enp0s3 proto kernel scope link src 10.0.2.15 metric 100

[root@localhost ~]# ls -ltra .ssh
ls: cannot access '.ssh': No such file or directory
[root@localhost ~]# su - vageant
su: user vageant does not exist

**Comment by SwampDragons** [comment]
`vageant` is a typo, so that's one issue. See if you can use vnc to connect to watch the boot command and see if there's an obvious place the kickstart is getting stuck.

This is a kickstart issue, not a Packer issue. If you're struggling to get Packer working for the first time, I'd recommend reaching out to the [community forum](https://discuss.hashicorp.com/c/packer) for help. The github issue tracker is only watched by a small subset of maintainers and is really reserved for bugs rather than questions. You'll have a better chance of finding someone who can help you in the forum.

**Comment by robertluwang** [comment]
You are right , found the real issue for my case, is vagrant user not created from kickstart,

user --name=vagrant --plaintext --password vagrant --groups=**vagrant**,wheel

remove vagrant from group list, then user vagrant created and packer ssh working properly.
