### ISSUE TITLE
Feature Request: Add cleanup_remote_cache feature to vsphere-iso builder

### ISSUE THREAD

**Issue by swerveshot** [hashicorp/packer#9843]
#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

After creating a succesfull build with the vsphere-iso builder I would like to have the option to remove the ISO file that was uploaded to the packer_cache folder on the remote datastore. The exact same functionality was added to the vmware-iso builder in this PR #8917.

#### Use Case(s)

Housekeeping

**Comment by nywilken** [comment]
Hi there thanks for opening up this request. I agree it would be a great feature to have in place, if possible.

I'm not sure how soon we will be able to look into it. But pull requests are welcomed if you are interested in implementing it for the vsphere-iso builder.

**Comment by swerveshot** [comment]
Hi @nywilken! I'd love to implement this myself but unfortunately my coding skills leave a lot to be desired. Never the less I took a look at PR #8917 to see if this is something I could have done myself but I don't feel comfortable writing my own code in go.  I'm okay with waiting for someone else to implement the feature and test it once it's available. I'm truely sorry for this.
