### ISSUE TITLE
Centos8 image creation through packer on azure results in to errors

### ISSUE THREAD

**Issue by zurrehma** [hashicorp/packer#9844]
Can somebody tell me what I am doing wrong here as I am unable to create the image? actually the commands, when I run on my host Centos machine, works fine but when I execute the same commands through packer result into error.
JSON file:

```
{
  "builders": [{
    "type": "azure-arm",
  
    "client_id": "{{user `azure-client-id`}}",
    "client_secret": "{{user `azure-client-secret`}}",
    "tenant_id": "{{user `azure-tenant-id`}}",
    "subscription_id": "{{user `azure-subscription-id`}}",
    
    "managed_image_resource_group_name": "{{user `azure-resource-group`}}",
    "managed_image_name": "CentOS8-Packer",
  
    "os_type": "Linux",
    "image_publisher": "OpenLogic",
    "image_offer": "CentOS",
    "image_sku": "8_2-gen2",

    "location": "{{user `azure-region`}}",
    "vm_size": "{{user `vm-size`}}"
  }],

  "provisioners": [
    {
      "execute_command": "chmod +x {{ .Path }}; {{ .Vars }} sudo -E sh '{{ .Path }}'",
      "script":"ami-script.sh"
      "type": "shell"
    }
  ]
}
```
ami-script.sh content:

```
#!/bin/bash -e
dnf update -y
dnf install terminator xrdp -y
```
Error:

![image](https://user-images.githubusercontent.com/23335310/91495774-7e6ced00-e8d4-11ea-8799-46c29360c1c3.png)
![image](https://user-images.githubusercontent.com/23335310/91495795-89c01880-e8d4-11ea-9326-80b22dd80d12.png)

Also posted [here](https://discuss.hashicorp.com/t/centos8-image-creation-through-packer-on-azure-results-in-to-errors/13448
)

**Comment by nywilken** [comment]
Hi there thanks for posting your question on the community forum. This is not a Packer bug so I will close this issue, but try to help by responding on the forum. Cheers!
