### ISSUE TITLE
packer build stuck after Connecting to VM via VNC (127.0.0.1:5964)

### ISSUE THREAD

**Issue by atileren** [hashicorp/packer#9847]
when I was run packer build over ssh packer stucks the Connecting to VM via VNC (127.0.0.1:5964). I built centos 7.8 machine with headless true option. I have updated packer to 1.6.2. Is there any solution for this?

    vmware-iso: view the screen of the VM, connect via VNC with the password "F8GCrvNX" to
    vmware-iso: vnc://127.0.0.1:5964
    vmware-iso: Waiting 10s for boot...
    vmware-iso: Connecting to VM via VNC (127.0.0.1:5964)

**Comment by sylviamoss** [comment]
Hey there, could you connect to the VM yourself via VNC using the address `127.0.0.1:5964`?

**Comment by cbednarski** [comment]
I've been running into this myself using VMware Fusion Pro 12.1.0 on MacOS Big Sur and it seems like it might be a bug in Go's `cmd.CombinedOutput()` that is triggered by `vmrun`'s `nogui` parameter. I'm using Go 1.16.2.

When I run `vmrun start blah.vmx nogui` I get output from the vmware CLI that looks like this. I have no idea why this output triggers the odd behavior.
```
2021-03-30T20:03:11.633| ServiceImpl_Opener: PID 9935
```

In Go I can do this:
```
cmd := exec.Command("vmrun", "start", "blah.vmx", "nogui")
if err := cmd.Run(); err != nil {
    panic(err)
}
```
However, this call seems to hang:
```
cmd := exec.Command("vmrun", "start", "blah.vmx", "nogui")
out, err := cmd.CombinedOutput()
if err != nil {
    panic(err)
}
fmt.Println(out)
```
Strangely if I write a more verbose implementation of combined output using stdoutpipe and stderrpipe it avoids blocking here. I can only speculate as to the cause but I am guessing that `cmd.CombinedOutput()`'s lazy implementation using the same pointer for stdout and stderr conflicts with the way vmrun forks the virtual machine process under the hood, and the file handle is left open indefinitely so `cmd.Wait()` never returns.

The workaround is to run with `headless: false`, which does not seem to have this problem, for reasons I can't imagine.

**Comment by cbednarski** [comment]
Here's a minimal repro (outside of packer):

```
package main

import (
	"os"
	"os/exec"
	"testing"
)

func cleanup() {
	cmd := exec.Command("vmrun", "stop", os.Getenv("VMRUN_VMX"), "hard")
	cmd.Run()
}

func TestVMRunGuiCmdRun(t *testing.T) {
	t.Cleanup(cleanup)

	cmd := exec.Command("vmrun", "start", os.Getenv("VMRUN_VMX"))
	if err := cmd.Run(); err != nil {
		t.Fatal(err)
	}
}

func TestVMRunNoGuiCmdRun(t *testing.T) {
	t.Cleanup(cleanup)

	cmd := exec.Command("vmrun", "start", os.Getenv("VMRUN_VMX"), "nogui")
	if err := cmd.Run(); err != nil {
		t.Fatal(err)
	}
}

func TestVMRunGuiCmdCombinedOutput(t *testing.T) {
	t.Cleanup(cleanup)

	cmd := exec.Command("vmrun", "start", os.Getenv("VMRUN_VMX"))
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatal(err)
	}
	t.Log(out)
}

func TestVMRunNoGuiCmdCombinedOutput(t *testing.T) {
	t.Cleanup(cleanup)

	cmd := exec.Command("vmrun", "start", os.Getenv("VMRUN_VMX"), "nogui")
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatal(err)
	}
	t.Log(out)
}
```

```
$ VMRUN_VMX=~/path/to/some.vmx go test -v -timeout 30s main_test.go
=== RUN   TestVMRunGuiCmdRun
--- PASS: TestVMRunGuiCmdRun (0.52s)
=== RUN   TestVMRunNoGuiCmdRun
--- PASS: TestVMRunNoGuiCmdRun (1.10s)
=== RUN   TestVMRunGuiCmdCombinedOutput
    main_test.go:40: []
--- PASS: TestVMRunGuiCmdCombinedOutput (1.67s)
=== RUN   TestVMRunNoGuiCmdCombinedOutput
panic: test timed out after 30s
```

**Comment by azr** [comment]
Ah, yes, interesting, `vmrun start blah.vmx nogui 2>&1 | tail` worked here.
