### ISSUE TITLE
vsphere-iso disk_size is documented but missing

### ISSUE THREAD

**Issue by bnfbiz** [hashicorp/packer#9858]
#### Overview of the Issue

The disk_size parameter (found here: https://www.packer.io/docs/builders/vmware/vsphere-clone#disk_size) but is needed for our scenario

#### Reproduction Steps

Add disk_size to a builder configuration for vsphere-clone and attempt to run a `packer build`

### Packer version

Packer v1.6.2

### Simplified Packer Buildfile

source "vsphere-clone" "template" {
  vcenter_server = var.vcenter_server
  username = var.vcenter_username
  password = var.vcenter_password
  datacenter = var.vcenter_datacenter

  create_snapshot = true
  convert_to_template = true
  network = var.vsphere_network

  template = var.src_image_name
  CPUs = 1
  cpu_cores = var.vsphere_cores
  RAM = var.vsphere_ram_mb
  disk_size = var.disk_size * 1024
  firmware = "bios"
  notes = "This is a build vm created by image_factory for the project ${var.project_name} and should be transient"

### Operating system and Environment details

No  special requirements

### Log Fragments and crash.log files

Error: Unsupported attribute

  on packer/sources-vsphere-clone.pkr.hcl line 15:
  (source code not available)

This object does not have an attribute named "disk_size".

Set the env var `PACKER_LOG=1` for maximum log detail.

**Comment by nywilken** [comment]
Hi @bnfbiz thanks for reaching out. This error message is a bit confusing as you have a variable named the same as one of the builder configuration option. But the error actually pertains to the `var.disk_size` not being defined as a variable, and not that the configuration option `disk_size` for the vsphere-clone is missing. 

Do you have a variable block defined for `disk_size`? 

It is considered an error to reference or set a variable via the command line that is not defined as a variable within the source template. We've recently added some documentation around variables usage as HCL does behave a little different then they did in JSON https://www.packer.io/docs/from-1.5/variables#variables-on-the-command-line

**Comment by bnfbiz** [comment]
You are correct, that was my misake.  Sorry for wasting your time and thanks for your assistance.
