### ISSUE TITLE
[feature] Allow to skip qemu-img resize if input file is disk image file

### ISSUE THREAD

**Issue by yamatoRT** [hashicorp/packer#9860]
#### Description

With qemu builder, I would like skip the qemu-img resize step when the iso_url is disk image file because this break my disk.

#### Potential configuration

I image to add new option in qemu builder like `skip_resize` or when `disk_size` is set at 0 or `none` and `disk_image==true` the builder skip the resize.

**Comment by SwampDragons** [comment]
Thanks for this suggestion! The QEMU builder is one of our community-supported builders, which means that the HashiCorp maintainers don't spend much engineering time on it; this means that the best way to see your suggestion make it into Packer is to open a PR. We'll gladly give support and pointers if you're interested in taking a shot at it.
