### ISSUE TITLE
Packer Docker provisioner, cap_add unknown key

### ISSUE THREAD

**Issue by davidmitchell2019** [hashicorp/packer#9861]
#### Overview of the Issue

Packer Docker provisioner, cap_add unknown key, packer version 1.6

#### Reproduction Steps

Packer cannot find the key cap_add for docker provisioner

### Packer version

1.6

### Operating system and Environment details

RHEL

**Comment by sylviamoss** [comment]
Thanks for reaching out. In order for us to best help could you provide the things requested in the issue template; including the simplest Packer configuration and the output logs from your build when you run it with PACKER_LOG set to 1 (`PACKER_LOG=1`).

**Comment by davidmitchell2019** [comment]
Please close, this is not a problem in 1.6.2
