### ISSUE TITLE
Packer build running for past year fails now with no indication of error.

### ISSUE THREAD

**Issue by jknott-terraform** [hashicorp/packer#9867]
We run our jobs through Jenkins. It has worked for the past year and now is failing. I can run the packer job from another VM and it works fine. Here is the error:

`==> amazon-ebs: Waiting for instance (i-04bb12dfd2413f5c0) to become ready...

==> amazon-ebs: Error waiting for instance (i-04bb12dfd2413f5c0) to become ready: ResourceNotReady: failed waiting for successful resource state`

This happens immediately. The instance never gets created. 

This is from the log of the new ami

                    "StateReason": {
                        "Code": "Client.InternalError",
                        "Message": "Client.InternalError: Client error on launch"
                    },

**Comment by SwampDragons** [comment]
Take a look at the debug docs here: https://www.packer.io/docs/builders/amazon#resourcenotready-error and let me know if any of those apply to your situation.

**Comment by jknott-terraform** [comment]
Here is what we have set

AWS_MAX_ATTEMPTS=3000
AWS_POLL_DELAY_SECONDS=30
AWS_TIMEOUT_SECONDS=3000
PACKER_LOG=1
PACKER_LOG_PATH='packer.log'

**Comment by SwampDragons** [comment]
What about the KMS key validity? "it was working for a year and then stopped" sounds kinda like maybe a kms key expired.

**Comment by jknott-terraform** [comment]
It ended up being a problem with the AWS keys used for deployment. Somehow the keys were active and didn't have enough permissions to do what it needed to create the instance. Thank you

**Comment by SwampDragons** [comment]
Glad I could help!
