### ISSUE TITLE
Add ability to mount local/datastore files with the vsphere-clone builder

### ISSUE THREAD

**Issue by rconde01** [hashicorp/packer#9868]
#### Description
The vsphere-iso builder has a floppy_files property(?) which allows you to specify both local files/directories and files located on a vsphere data store. However, vsphere-clone does not have this property.

For local files there are some alternatives:
- File Provisioner
  - This is EXTREMELY slow with winrm (at least in my configuration)
- http_directory property

However, there is no apparent way to do this with files located on a vsphere datastore. It would be useful to have this functionality.

#### Use Case(s)

While the above methods are better than nothing, they have some drawbacks:
- Required files may be very large. Even with the faster methods, transferring them takes significant time.
- Since large files are inappropriate to add to CM (ok...I guess you could use git-lfs) they must be manually acquired and placed in the correct place which increases process complexity.

#### Potential configuration

```
    floppy_files = [
        "file1.bin",
        "file2.bin"
    ]
```

**Comment by sylviamoss** [comment]
Thanks for reaching out! We’ll take a look when we get a chance.

**Comment by rconde01** [comment]
I actually don't think floppy works here...at least for vsphere-iso, it only works for local files afaics. So the desire is the same, but i don't think my proposed solution is valid.

**Comment by sylviamoss** [comment]
Could you explain it better? I'm in the work of adding the same `floppy_files` feature to the vsphere-clone. I did a test for example of adding a script via `floppy_files` and running it with a shell provisioner. It worked. Is that what you're expecting?

**Comment by rconde01** [comment]
I want to be able to access a file on a vsphere datastore from within a VM. For some reason, I thought I had seen this demonstrated with floppy files...but I think I was mistaken. When I tried to do this it didn't work...although it's possible that I messed something up. 

The only solution I've found so far is in vsphere-iso where you can specify isos via iso_paths. This is still not ideal because you have to create isos for your files...but it's better than nothing. So having that ability in vsphere-clone would be useful. If you know a more direct way, that would be good too.

**Comment by sylviamoss** [comment]
It the title you said local/datastore. Are you interested to mount local files as well or only datastore ones?

**Comment by rconde01** [comment]
Both - although cd_files seems fine for local ones. Also, using the http server is fine for local files when the file is small (at least for my use case).

**Comment by sylviamoss** [comment]
If you can create a floppy image and add it to the content library you can used it with [floppy_img_path](https://www.packer.io/docs/builders/vmware/vsphere-iso#floppy_img_path). What about this option?

**Comment by rconde01** [comment]
isn't that limited to the size of a floppy? e.g. like ~3mb?

**Comment by sylviamoss** [comment]
Yes, sorry I forgot you need something for bigger files. 

Anyways, I'm not positive about using files from the Content Library. Any option will require to download the file(s) in order to copy it to inside the VM either via cd or floppy. This is not crucial specially for bigger files. I haven't found anything on vsphere API that would allow us to use files withing a content library item if they are not already in formats such as ISO, flp, OVF and so on.

I'll move forward by allowing `iso_paths` to work with vsphere-clone and then you'll use it as you said, by giving Packer an ISO that you created yourself and uploaded to the Content Library. That's the only available option for us right now.

**Comment by sylviamoss** [comment]
I added the iso_paths to the vsphere-clone and you can try out the solution with these binaries: https://app.circleci.com/pipelines/github/hashicorp/packer/7283/workflows/41b7288e-9e18-4c1a-b49e-be6f97a95727/jobs/82808/artifacts
Could you test it and let me know if works as expected?

**Comment by rconde01** [comment]
So basically it works. The iso is available as a drive. But I ran into an unexpected behavior:

- In my test configuration i do a series of builders. It starts with vsphere-iso and then does a number of vsphere-clone
- In the vsphere-iso I am attaching 3 iso files
- I hadn't noticed before, but afterwards the VMs end up with 3 DVD drives
- Now using vsphere-clone with iso_paths yet another drive is added

Seems like these additional drives should be removed at the end? They're only being ejected, not removed.

**Comment by rconde01** [comment]
I'm confused because there is this:
https://github.com/hashicorp/packer/pull/8690

But I don't see how you actually use it.

**Comment by rconde01** [comment]
ok "remove_cdrom"...which i didn't test but seems correct. I don't see any documentation for it though.

**Comment by rconde01** [comment]
yes - that works...i will add a separate documentation bug.
