### ISSUE TITLE
GCP import post processor: -force option does not work

### ISSUE THREAD

**Issue by cevich** [hashicorp/packer#9872]
#### Overview of the Issue

Importing Fedora image through the (advanced/complex) nested KVM -> googlecompute-import post-processor works fine the first time.  However, when executing packer build a second time, ***while specifying -force option***, we get this error message.

#### Reproduction Steps

qemu *builder* -> shell *provisioner* -> *compress* then googlecompute-import *post-processors*

### Packer version

1.4.5

### Simplified Packer Buildfile

https://github.com/containers/automation_images/blob/master/base_images/gce.yml

### Operating system and Environment details

Host is running CentOS 8 in GCE, but problem is also reproducible locally in a CentOS 8 container (provided GCE application default credentials).

### Log Fragments and crash.log files

```
==> fedora (googlecompute-import): Uploading file /tmp/automation_images_tmp/fedora/disk.raw.tar.gz to GCS bucket packer-import/fedora-1598993532.tar.gz...
==> fedora (googlecompute-import): Creating GCE image fedora-b1598993532...
==> fedora (googlecompute-import): Error creating GCE image
2020/09/01 21:26:49 Deleting original artifact for build 'fedora'
Build 'fedora' errored: 1 error(s) occurred:


* Post-processor failed: googleapi: Error 409: The resource 'projects/libpod-218412/global/images/fedora-b1598993532' already exists, alreadyExists
2020/09/01 21:26:49 machine readable: error-count []string{"1"}
==> Some builds didn't complete successfully and had errors:
2020/09/01 21:26:49 machine readable: fedora,error []string{"1 error(s) occurred:\n\n* Post-processor failed: googleapi: Error 409: The resource 'projects/libpod-218412/global/images/fedora-b1598993532' already exists, alreadyExists"}

* Post-processor failed: googleapi: Error 409: The resource 'projects/libpod-218412/global/images/fedora-b1598993532' already exists, alreadyExists
==> Builds finished but no artifacts were created.
* Post-processor failed: googleapi: Error 409: The resource 'projects/libpod-218412/global/images/fedora-b1598993532' already exists, alreadyExists

==> Some builds didn't complete successfully and had errors:
--> fedora: 1 error(s) occurred:

* Post-processor failed: googleapi: Error 409: The resource 'projects/libpod-218412/global/images/fedora-b1598993532' already exists, alreadyExists

2020/09/01 21:26:49 waiting for all plugin processes to complete...
==> Builds finished but no artifacts were created.
```

**Comment by azr** [comment]
Hello, thanks for opening, not sure if we will have the time to work on this right away but I would use this step from the builder:

https://github.com/hashicorp/packer/blob/e5606d483dcb8efece8f8d2db6454d7cb5abe2f6/builder/googlecompute/builder.go#L54

and that code:

https://github.com/hashicorp/packer/blob/e0cfb404fb60ab8950be51fedee1794148d41d4a/builder/googlecompute/step_create_image.go#L26-L37

**Comment by cevich** [comment]
It's possible we could hit this within automation, but for now I'm only seeing it when we do things manually.  It's more of an inconvenience, and the error messages suggests the workaround, so no rush on my part.  Thanks.
