### ISSUE TITLE
Have vmware-iso builder detect a guest IP address via VMware Tools for non-ESXi hypervisors

### ISSUE THREAD

**Issue by swerveshot** [hashicorp/packer#9873]
#### Community Note
Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description
As far as I know there currently is no way to provision a VM using the `vmware-iso` builder where the VM's IP is set to a static address. The `vsphere-iso` builder has the ability to use the data that is returned by VMware Tools to determine what IP addresses have been configured within the Guest OS. However this feature seems to be lacking for VMware Workstation, Player or Fusion.

#### Environment details
Packer version: `1.6.1`
Builder: `vmware-iso`
OS: `Windows 10 version 1909`
Hypervisor: `VMware Workstation 15.5.2 build 15785246`

#### Reproduce issue
Create a VM which uses a static IP address with the PACKER_LOG environment variable set to 1 and observe the logging where a possible IP address assignment is being read from the `vmnetdhcp.leases file.

#### Possible solutions
I'm not sure if VMware Workstation, Player or Fusion even exposes the IP address assignment via some sort of API like vSphere does. But if this would be possible I'd love to be able to use this as a way to discover IP address assignment for VMs that use static IP addressing.

#### Use Case(s)
Using static IP addresses on VMs

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out. if a vm is using a static IP address, you should be able to use the [ssh_host](https://www.packer.io/docs/communicators/ssh#ssh_host) option and bypass IP detection altogether.

**Comment by swerveshot** [comment]
Hi @SwampDragons! That's a great tip. Thank you for that. But what about Windows hosts?

**Comment by SwampDragons** [comment]
Since this fixes your specific use case, I'm going to close. We can reopen if there's another use case for investigating a different IP detection method.
