### ISSUE TITLE
Packer distribution to AWS china times out on ssh

### ISSUE THREAD

**Issue by dwagner-ops** [hashicorp/packer#9876]
Hi,

I have problems when I try to build a AMI with packer in AWS China region.
In the step Waiting for SSH to become available...
I got the error message: 2020/09/02 16:06:27 packer-builder-amazon-ebs plugin: Using host value: 10.28.121.147
2020/09/02 16:06:31 packer-builder-amazon-ebs plugin: [DEBUG] TCP connection to SSH ip/port failed: dial tcp 10.28.121.147:22: connect: network is unreachable

When I use the -debug flag I'm able to connect per ssh by using the generated .pem file.

I use packer version 1.6.2 on macOSX the image is: ubuntu/images/hvm-ssd/ubuntu-focal-* x86_64
I have now Idea what I can do different.

Can you please help me.

**Comment by nywilken** [comment]
Thanks for reaching out. In order for us to best help could you provide the things requested in the issue template; including the simplest Packer configuration and the output logs from your build when you run it with PACKER_LOG set to 1 (`PACKER_LOG=1`).

The IP `10.28.121.147` looks like a private IP address. Do you have any proxy or vpn connectivity setup in order to SSH to the provided ip?

**Comment by dwagner-ops** [comment]
Hi thank you for your support. This is the packer.json file: 
`{
    "name": "mdx_prod_cn",
    "type": "amazon-ebs",
    "profile": "mdx_prod_cn",
    "region": "cn-north-1",
    "source_ami_filter": {
      "filters": {
        "virtualization-type": "hvm",
        "name": "ubuntu/images/hvm-ssd/ubuntu-focal-*",
        "root-device-type": "ebs",
        "architecture": "x86_64"
      },
      "owners": ["XXXXXX"],
      "most_recent": true
    },
    "launch_block_device_mappings": [{
      "device_name": "/dev/sda1",
      "volume_size": 25,
      "delete_on_termination": true
    }],
    "tags": {
      "Environment": "packer",
      "ManagedBy": "{{user `username`}}",
      "Module": "ec2-factory-docker",
      "Name": "{{user `ami_name`}}",
      "Creator": "{{user `ami_creator`}}",
      "PackerSourceAMI": "{{ .SourceAMI }}",
      "PackerSourceAMIName": "{{ .SourceAMIName }}",
      "Version": "{{user `version`}}"
    },
    "run_tags": {
      "Environment": "packer",
      "ManagedBy": "{{user `username`}}",
      "Module": "ec2-factory-docker",
      "Name": "packer-ec2-factory-docker_{{ isotime `2006-01-02_15.04.05` }}"
    },
    "run_volume_tags": {
      "Environment": "packer",
      "ManagedBy": "{{user `username`}}",
      "Module": "ec2-factory-docker",
      "Name": "packer-ec2-factory-docker_{{ isotime `2006-01-02_15.04.05` }}"
    },
    "instance_type": "t3.micro",
    "ssh_username": "ubuntu",
    "ami_name": "{{user `ami_name`}}",
    "vpc_filter": {
      "filters": {
        "tag:Environment": "cn"
      }
    },
    "subnet_filter": {
      "filters": {
        "tag:Name": "*-private-*"
      },
      "most_free": true,
      "random": true
    }
  }`
Out put with PACKER_LOG=1:
`==> mdx_prod_cn: Waiting for SSH to become available...
2020/09/03 08:37:17 packer-builder-amazon-ebs plugin: Using host value: 10.28.125.109
2020/09/03 08:37:21 packer-builder-amazon-ebs plugin: [DEBUG] TCP connection to SSH ip/port failed: dial tcp 10.28.125.109:22: connect: network is unreachable`

The IP is private and  I have a setup in ~/.ssh/config with the following settings:
`Host 10.2?.*.* 10.5?.*.* 10.15?.*.* 10.16?.*.* *.*.mdxqa.io *.*.mdxprod.io !ssh.shared.mdxprod.io
    User d_wagner
    ProxyCommand ssh ssh.shared.mdxprod.io nc %h %p %r
    StrictHostKeyChecking no`
The build for other AWS regions like Frankfurt or Ireland is working only China does not work for some reason.

**Comment by nywilken** [comment]
> The IP is private and I have a setup in ~/.ssh/config with the following settings:
Host 10.2?.*.* 10.5?.*.* 10.15?.*.* 10.16?.*.* *.*.mdxqa.io *.*.mdxprod.io !ssh.shared.mdxprod.io User d_wagner ProxyCommand ssh ssh.shared.mdxprod.io nc %h %p %r StrictHostKeyChecking no
The build for other AWS regions like Frankfurt or Ireland is working only China does not work for some reason.

Do the instances in Frankfurt and Ireland have internal IPs that require SSH to be proxied as well? 

Packer uses a separate Go pkg for communicating over SSH so any local system configurations set in `~/.ssh/config` are not read. Packer does have support for configuring an external proxy, which might be helpful https://www.packer.io/docs/communicators/ssh#ssh_proxy_host

An alternative is to run Packer from an EC2 instance within the China region to avoid the proxy all together.

**Comment by dwagner-ops** [comment]
Hi thank you for your helping. The problem was our VPN Tunnel. In case of China the route was missing. It works locally because I had an entry in my local ssh config. However it was very helpful for me..
