### ISSUE TITLE
amazon-ebs: Temporary snapshot not tagged causing permission denied

### ISSUE THREAD

**Issue by rednuht** [hashicorp/packer#9894]
#### Overview of the Issue

In our company we use tags to dictate whether a role/user has access to perform actions on a resource.
When packer tries to clean up at the end it is unable to delete the temporary snapshot since it is untagged.

#### Reproduction Steps

Include a policy statement that has a condition on tags:

        {
            "Effect": "Allow",
            "Action": "ec2:*",
            "Resource": "*",
            "Condition": {
                "StringEquals": {
                    "ec2:ResourceTag/Team": "MY_SPECIAL_TAG"
                }
            }
        }

### Packer version

From `1.3.2` and onwards.
(haven't tested with earlier versions)

### Simplified Packer Buildfile

https://gist.github.com/rednuht/f2c62fbc47186e41d0f8e9707954bcc7

### Operating system and Environment details

Not relevant.

### Log Fragments and crash.log files

    2020-09-04T09:44:21+02:00: Build 'amazon-ebs' errored after 52 minutes 56 seconds: Error deleting existing snapshot: retry count exhausted. Last err: UnauthorizedOperation: You are not authorized to perform this operation. Encoded authorization failure message: ENCODED MSG status code: 403, request id: 6b6df0be-3b0d-4eb7-8185-41823465f67d

Important parts from decoded message:

```
{
  "allowed": false,
  "explicitDeny": false,
  "matchedStatements": {
    "items": []
  },
  "failures": {
    "items": []
  },
  "context": {
    "action": "ec2:DeleteSnapshot",
    "resource": "arn:aws:ec2:eu-west-1::snapshot/snap-FOOBAR123",
  }
}
```

**Comment by sylviamoss** [comment]
Hello! Thanks for reaching out. We’ll take a look when we get a chance.

**Comment by nywilken** [comment]
Hello again, can you confirm the version of Packer you are using. When using `snapshot_tags` you should see messages in the logs indicating that the snapshot tags are being created. Something like the following:

```
==> amazon-ebs: Modifying attributes on snapshot (snap-0822d7b65f26c6bdc)...                                                                      
==> amazon-ebs: Adding tags to AMI (ami-0e5d5ed86e1b19ea8)...                                                                                     
==> amazon-ebs: Tagging snapshot: snap-0822d7b65f26c6bdc
==> amazon-ebs: Creating AMI tags
    amazon-ebs: Adding tag: "Name": "Windows SSH Image Test"
    amazon-ebs: Adding tag: "OS": "Windows-2016"
==> amazon-ebs: Creating snapshot tags
    amazon-ebs: Adding tag: "Name": "Windows SSH Image Test"                                                                                      
    amazon-ebs: Adding tag: "OS": "Windows-2016"
    amazon-ebs: Adding tag: "Team": "packer_dev"
```
Do you see something similar in your logs? If so have you checked that the snapshot does indeed have the created tags via the AWS console?

**Comment by rednuht** [comment]
Yes, I see these:

```
==> amazon-ebs: Waiting for AMI to become ready...
==> amazon-ebs: Copying/Encrypting AMI (ami-0d0b04FOO0540c2) to other regions...
    amazon-ebs: Copying to: eu-west-1
    amazon-ebs: Waiting for all copies to complete...
==> amazon-ebs: Adding tags to AMI (ami-0fdf0FOOdcdb8aaa)...
==> amazon-ebs: Tagging snapshot: snap-0f007BARc3354d6
==> amazon-ebs: Creating AMI tags
    amazon-ebs: Adding tag: "BUILDTIME": "20200904T1346"
    amazon-ebs: Adding tag: "Team": "MY_SPECIAL_TAG"
    amazon-ebs: Adding tag: "version": "1.2.3"
==> amazon-ebs: Creating snapshot tags
    amazon-ebs: Adding tag: "Team": "MY_SPECIAL_TAG"
```

Right after this the error that I previously mentioned is printed.

The final AMI is tagged properly though, it's the cleanup that fails and leaves behind an AMI with names like `4pTwBfo`, which are untagged so the role doesn't have permission to delete it.

**Comment by SwampDragons** [comment]
Aha, those are the intermediary snapshots we use for encryption, I think

**Comment by rednuht** [comment]
@SwampDragons @sylviamoss, any movement on this?
If you can point me in the right direction, perhaps I could create a PR myself if that would be helpful.

**Comment by SwampDragons** [comment]
We haven't had a chance to work on this but if you want to, the code for adding tags is here: https://github.com/hashicorp/packer/blob/master/builder/amazon/common/step_create_tags.go#L84-L122

The code that creates our "correct" AMIs from the intermediary ones is here: https://github.com/hashicorp/packer/blob/master/builder/amazon/common/step_ami_region_copy.go#L74

I suspect that inside that if statement instead of just storing the "toDelete" value on the step, we can add it to the state bag using `state.Put("intermediary_ami_name", ami)`. 

Then, in the tagging step, which comes at the very end of the build. We can load that intermediary AMI value out of the state bag using `state.Get(...)` and make sure our tags get applied to it, as well. 

I don't have time to work on this right now but hopefully that gets you started if you do want to give it a try.
