### ISSUE TITLE
SSH time out due to AWS Session Manager tunnel failure (connection refused)

### ISSUE THREAD

**Issue by JosephHobbs** [hashicorp/packer#9897]
#### Overview of the Issue

Attempting to use Packer v1.6.2 to create an Amazon Machine Image (based on a customized Amazon Linux 2 AMI).  I'm using the session_manager communicator but am experiencing a timeout when connecting via SSH.

What I see in the logs is that as soon as the instance is available packer immediately attempts to establish a port forward for SSH via SSM.  SSM reports connection refused (assuming because SSHD isn't listening yet).  Due to this, the SSH never succeeds.

I'm thinking there should be some logic in the session-manager-plugin to detect the failure and retry.  Another option would be to put a (configurable) delay between when the instance reports available and the SSM tunnel is triggered to allow us to adjust for slower booting images.

#### Reproduction Steps

For me it's very repeatable.  My assumption here is that the image I'm basing my build on is slower at starting SSHD than the out of box images.

### Packer version

packer v1.6.2

### Simplified Packer Buildfile

```
{
    "builders": [
        {
            "ami_name": "base-image",
            "availability_zone": "us-east-2c",
            "communicator": "ssh",
            "iam_instance_profile": "AMIBuildAssumeRole",
            "instance_type": "c5.large",
            "region": "us-east-2",
            "security_group_filter": {
                "filters": {
                    "tag:Name": "ami-build-security-group"
                }
            },
            "source_ami_filter": {
                "filters": {
                    "name": "xxx-amzlinux2-standard*",
                    "root-device-type": "ebs",
                    "virtualization-type": "hvm"
                },
                "most_recent": true,
                "owners": ["123456789000"]
            },
            "ssh_interface": "session_manager",
            "ssh_username": "ec2-user",
            "subnet_filter": {
                "filters": {
                    "tag:Name": "my-subnet-name"
                }
            },
            "type": "amazon-ebs",
            "vpc_filter": {
                "filters": {
                    "tag:Name": "my-vpc-name"
                }
            }
        }
    ]
}
```

### Operating system and Environment details

Packer is running on RHEL and I am interacting with AWS in us-east-2.

### Log Fragments and crash.log files

2020/09/04 10:51:26 ui: ==> amazon-ebs: Launching a source AWS instance...
2020/09/04 10:51:26 ui: ==> amazon-ebs: Adding tags to source instance
2020/09/04 10:51:26 ui:     amazon-ebs: Adding tag: "Name": "Packer Builder"
2020/09/04 10:51:28 ui:     amazon-ebs: Instance ID: i-061cf2da2e91c6365
2020/09/04 10:51:28 ui: ==> amazon-ebs: Waiting for instance (i-061cf2da2e91c6365) to become ready...
2020/09/04 10:51:44 packer-builder-amazon-ebs plugin: [INFO] Not using winrm communicator, skipping get password...
2020/09/04 10:51:44 packer-builder-amazon-ebs plugin: Found available port: 8725 on IP: 0.0.0.0
2020/09/04 10:51:44 packer-builder-amazon-ebs plugin: Starting PortForwarding session to instance "i-061cf2da2e91c6365" with following params map[localPortNumber:[0xc0007e5aa0] portNumber:[0xc0007e5a90]]
2020/09/04 10:51:44 packer-builder-amazon-ebs plugin: Retryable error: TargetNotConnected: i-061cf2da2e91c6365 is not connected.
2020/09/04 10:51:45 packer-builder-amazon-ebs plugin: Retryable error: TargetNotConnected: i-061cf2da2e91c6365 is not connected.
2020/09/04 10:51:46 packer-builder-amazon-ebs plugin: Retryable error: TargetNotConnected: i-061cf2da2e91c6365 is not connected.
2020/09/04 10:51:47 packer-builder-amazon-ebs plugin: Retryable error: TargetNotConnected: i-061cf2da2e91c6365 is not connected.
2020/09/04 10:51:49 packer-builder-amazon-ebs plugin: Retryable error: TargetNotConnected: i-061cf2da2e91c6365 is not connected.
2020/09/04 10:51:52 packer-builder-amazon-ebs plugin: Retryable error: TargetNotConnected: i-061cf2da2e91c6365 is not connected.
2020/09/04 10:51:59 packer-builder-amazon-ebs plugin: [DEBUG session-manager-plugin] opening session tunnel to instance "i-061cf2da2e91c6365" for session "fuser-01d660813ae668e44"
2020/09/04 10:51:59 ui:     amazon-ebs: PortForwarding session "i-061cf2da2e91c6365" has been started
2020/09/04 10:51:59 ui: ==> amazon-ebs: Using ssh communicator to connect: localhost
2020/09/04 10:51:59 packer-builder-amazon-ebs plugin: [INFO] Waiting for SSH, up to timeout: 5m0s
2020/09/04 10:51:59 ui: ==> amazon-ebs: Waiting for SSH to become available...
2020/09/04 10:51:59 packer-builder-amazon-ebs plugin: [DEBUG] TCP connection to SSH ip/port failed: dial tcp 127.0.0.1:8725: connect: connection refused
2020/09/04 10:51:59 packer-builder-amazon-ebs plugin: [DEBUG] session-manager-plugin:
2020/09/04 10:51:59 packer-builder-amazon-ebs plugin: [DEBUG] session-manager-plugin: Starting session with SessionId: fuser-01d660813ae668e44
2020/09/04 10:52:00 packer-builder-amazon-ebs plugin: [DEBUG] session-manager-plugin:
2020/09/04 10:52:00 packer-builder-amazon-ebs plugin: [DEBUG] session-manager-plugin:
**2020/09/04 10:52:00 packer-builder-amazon-ebs plugin: [DEBUG] session-manager-plugin: SessionId: fuser-01d660813ae668e44 : Unable to connect to specified port: dial tcp 127.0.0.1:22: connect: connection refused**
2020/09/04 10:52:00 packer-builder-amazon-ebs plugin: [DEBUG] session-manager-plugin:
2020/09/04 10:52:04 packer-builder-amazon-ebs plugin: [DEBUG] TCP connection to SSH ip/port failed: dial tcp 127.0.0.1:8725: connect: connection refused
2020/09/04 10:52:09 packer-builder-amazon-ebs plugin: [DEBUG] TCP connection to SSH ip/port failed: dial tcp 127.0.0.1:8725: connect: connection refused
2020/09/04 10:52:14 packer-builder-amazon-ebs plugin: [DEBUG] TCP connection to SSH ip/port failed: dial tcp 127.0.0.1:8725: connect: connection refused
... and many more times ...
2020/09/04 10:56:59 ui error: ==> amazon-ebs: Timeout waiting for SSH.
2020/09/04 10:56:59 packer-builder-amazon-ebs plugin: [DEBUG] SSH wait cancelled. Exiting loop.
2020/09/04 10:56:59 ui: ==> amazon-ebs: Terminating the source AWS instance...
2020/09/04 10:57:46 ui: ==> amazon-ebs: Cleaning up any extra volumes...
2020/09/04 10:57:47 ui: ==> amazon-ebs: No volumes to clean up, skipping
2020/09/04 10:57:47 ui: ==> amazon-ebs: Deleting temporary keypair...
2020/09/04 10:57:47 [INFO] (telemetry) ending amazon-ebs
2020/09/04 10:57:47 ui error: Build 'amazon-ebs' errored after 6 minutes 23 seconds: Timeout waiting for SSH.

**Comment by JosephHobbs** [comment]
I tried using **pause_before_connecting** to see if it would slow things down, but it isn't in play for this part (instance available to SSM session start) of the process.

**Comment by nywilken** [comment]
Hi there, thanks for reaching out. The session manager integration is responsible for creating a PortForwarding session to the remote instance. Once the PortForwarding session has started Packer will wait until SSH can connect, which is independent of the session manager since that is controlled by the aws session manager plugin running externally to Packer. 

If the PortFowarding session is still active whenever SSHD comes online Packer should be able to connect.  The ssm session, if I'm not mistaken will remain open as long as there is activity flowing through it and it has not been terminated. 

Have you tried extending the SSH timeout to see if that helps?

You can set the timeout to an hour with `"ssh_timeout": 60m` if you think it may be related to a slow SSHD startup.

**Comment by JosephHobbs** [comment]
I've tried adjusting ssh_timeout but haven't had much luck getting around it.  It still just hangs until it times out.

In my experience with SSM, if the port is not listening at the time of session creation it will fail to establish the port forward.  In response, it returns a message similar to what I'm seeing in the packer logs .

```
2020/09/04 10:52:00 packer-builder-amazon-ebs plugin: [DEBUG] session-manager-plugin: SessionId: fuser-01d660813ae668e44 : Unable to connect to specified port: dial tcp 127.0.0.1:22: connect: connection refused
```

So at that point a SSM session has started and packer has moved on to SSHing,  But since the creation of the port forward has failed, SSH will never actually succeed.  There would have to be some sort of error checking in the SSM step (to detect the connection refused) and retry to ensure the session and port forward are present.  Another option would be to just put a brief delay between 'detecting the instance up' and 'establishing the SSM session' to allow for slower images.

Thanks!

**Comment by JosephHobbs** [comment]
Interestingly enough, this looks to have some acknowledgement within the source.  Lines 100 to 106 of builder/amazon/common/ssm_driver.go

```
        This particular logger will continue to run through an entire Packer run.
	The decision to continue logging is due to the fact that session-manager-plugin
	doesn't give a good way of knowing if the command failed or was successful other
	than looking at the logs. Seeing as the plugin is updated frequently and that the
	log information is a bit sparse this logger will indefinitely relying on other
	steps to fail if the tunnel is unable to be created. If successful then the user
	will get more information on the tunnel connection when running in a debug mode.
```

**Comment by JosephHobbs** [comment]
Great!  Thank you for your help!

**Comment by sylviamoss** [comment]
Hey there, I implemented a `pause_before_ssm` configuration where you can define the necessary pause time to wait until the port is available before establishing the SSM session. 
You can try out the solution with these binaries: https://app.circleci.com/pipelines/github/hashicorp/packer/7303/workflows/35cb38d6-6751-4384-bf5f-8aa38129ad91/jobs/83091/artifacts 
Let me know if it works as expected.

**Comment by JosephHobbs** [comment]
I did something similar, but I just hard coded a sleep directly in the code.  My experience with Go is light, so I wasn't sure I'd be able to pull off making it configurable.  With all that said, tossing in a sleep to give it time definitely worked around the issue while an official fix is in the works!
