### ISSUE TITLE
EFI firmware switching to BIOS when destination is vSphere content library

### ISSUE THREAD

**Issue by cmbits** [hashicorp/packer#9898]
#### Overview of the Issue
VM boot firmware issue when using Packer 1.6.2 and specifying the destination to be an OVF in a vSphere content library.  The buildfile is specifying firmware type efi.  The VM created is using efi but something happens when it is cloned to the content library as an OVF causing any new VMs deployed from that content library template switch to using BIOS firmware and can't boot into Windows OS.

#### Reproduction Steps

- Using packer 1.6.2, specifying efi firmware, and destination as an OVF in a vSphere content library I get VMs deployed from the content library using BIOS firmware instead of EFI.

- If I take the same buildfile without the content library destination and packer 1.6.1 I get a VM using EFI firmware.  I can then manually clone to library as OVF and that content library template can be deployed multiple times without boot firmware switching to BIOS.

- I've made sure to specify cdrom_type:sata and convert_to_template:false.

### Packer version

From packer version 1.6.2

### Simplified Packer Buildfile

https://gist.github.com/cmbits/ae9ba8ef31032bc85597a6e5a3485d23

### Operating system and Environment details

Windows 2016/2019 Core/GUI
vSphere 7
vSAN storage

**Comment by sylviamoss** [comment]
Hello, thanks for reaching out! We’ll take a look when we get a chance.

**Comment by cmbits** [comment]
Quick update...  I verified issue still occurs with Packer 1.6.4 and vSphere 7update1.

**Comment by SwampDragons** [comment]
Thanks for checking. It looks a lot like this issue, but you're on a more recent version of vmware that should have resolved it. https://kb.vmware.com/s/article/58921

**Comment by SwampDragons** [comment]
If you look at your vm's VMX file is there a line in it that says `firmware = "efi"`?

**Comment by bpfoley45** [comment]
> If you look at your vm's VMX file is there a line in it that says `firmware = "efi"`?

yes, when looking at the VM artifact that is left behind after importing into the Content Library, I see `firmware=efi`

**Comment by SwampDragons** [comment]
ok, so we know it's not getting wiped out when Packer saves the VM. This is weird.

**Comment by Wav3** [comment]
> yes, when looking at the VM artifact that is left behind after importing into the Content Library, I see `firmware=efi`

I can confirm this on vSphere 6.7.0.45000 using packer 1.6.6.  
Even when looking at the `.ovf` file in the content library the config key exists:

```xml
<?xml version='1.0' encoding='UTF-8'?>
<Envelope xmlns="http://schemas.dmtf.org/ovf/envelope/1" xmlns:ovf="http://schemas.dmtf.org/ovf/envelope/1" xmlns:vmw="http://www.vmware.com/schema/ovf" xmlns:rasd="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData" xmlns:vssd="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData">
  [...]
  <VirtualSystem ovf:id="test-vm">
    [...]
    <VirtualHardwareSection>
      [...]
      <vmw:Config ovf:required="false" vmw:key="bootOptions.efiSecureBootEnabled" vmw:value="false"/>
      <vmw:Config ovf:required="false" vmw:key="firmware" vmw:value="efi"/>
      <vmw:ExtraConfig ovf:required="false" vmw:key="nvram" vmw:value="ovf:/file/file2"/>
    </VirtualHardwareSection>
[...]
</Envelope>
```

But after deploying a new VM from the template the line `firmware = "efi"` is missing in the `.vmx` file of the resulting VM.  
If I manually clone the original VM as a template to the content library and deploy an additional VM from the manually created template, the `firmware = "efi"` is present and the boot is working as expected.  

So I'm not sure if this issue is related to the packer vsphere-iso builder or to vSphere itself.

**Comment by Wav3** [comment]
After some further investigation I've found out, that the following section in the `ovf` file results in this particular issue:

```xml
<vmw:BootOrderSection vmw:instanceId="5" vmw:type="disk">
    <Info>Virtual Hardware device boot order</Info>
</vmw:BootOrderSection>
```

If I remove this section from the `ovf` file and deploy a new VM from the template, the firmware persist to EFI.  
This section is not present in the `ovf` file if I manually clone the original VM as a template to the content library.  

Additionally I've tested the *clone as template to content library* procedure with the [python vSphere automation sdk](https://github.com/vmware/vsphere-automation-sdk-python) which does not lead to this issue.  
So I think this is an issue of [govmomi](https://github.com/vmware/govmomi).

**Comment by xfrny** [comment]
Can confirm the same issue with Packer 1.7.0 and a VSphere 7.0.0 instance.

Removal of the BootOrderSection allows the creation of the VM with the correct firmware type.

**Comment by animatco** [comment]
I noticed that sometime ago, I just added some PowerShell to my
distribution script that handles that (and a possible NVRAM file
missing) to my distribution script.  I do not believe that this is a
Packer issue, it is a vSphere issue.

Steve

xfrny wrote on 2/23/2021 3:49 PM:

**Comment by vantmet** [comment]
Hi,

  As you can see above, I opened an issue with Govmomi to investigate this on their side. They believe the issues is that packer sets Boot order, and doesn't unset it until cleanup. This explains why it is still set during import. They believe the fix is to unset boot order after the shutdown step.

https://github.com/hashicorp/packer/issues/9898#issuecomment-758752272

Please could this be followed up?

A
