### ISSUE TITLE
vsphere-iso: error creating vm: Invalid configuration for device '1'

### ISSUE THREAD

**Issue by bendunne** [hashicorp/packer#9899]
#### Overview of the Issue

When using the vsphere-iso builder to build a machine I get the error "vsphere-iso: error creating vm: Invalid configuration for device '1'" which happens even if I remove as much of the configuration as possible.

#### Reproduction Steps

Please use build file you need to use it against ESXI environment 

### Packer version

From `1.6.1` also tested on `1.6.2` 

### Simplified Packer Buildfile

The original file I was using: https://gist.github.com/bendunne/8162b336b868c7716cee0e63c390a018

The stripped down version after removing possible config that could be the cause: https://gist.github.com/bendunne/31a3a95d182b5ef8443b6d1e26fca8b6

### Operating system and Environment details

I'm running Packer from Windows 2012 R2 and I'm connecting to and ESXI 6.5 environment and I'm trying to deploy Windows Server 2019.

### Log Fragments and crash.log files

**Error Output:**
```
vsphere-iso: output will be in this color.

==> vsphere-iso: Creating VM...
Build 'vsphere-iso' errored after 561 milliseconds 705 microseconds: error creating vm: Invalid configuration for device
 '1'.

==> Wait completed after 561 milliseconds 705 microseconds

==> Some builds didn't complete successfully and had errors:
--> vsphere-iso: error creating vm: Invalid configuration for device '1'.

==> Builds finished but no artifacts were created.
```

https://gist.github.com/bendunne/4d5739bf1ac45815465c3de53a04deaa

**Comment by sylviamoss** [comment]
Hello there! Did your template work with versions before 1.6.1?

**Comment by bendunne** [comment]
Hi. You've got it right the issue was the host didn't have access to the datastore. Thank you for the help :)
