### ISSUE TITLE
When excepting a post-processor, any other post-processor after the skipped one will also be skipped

### ISSUE THREAD

**Issue by TomSDEVSN** [hashicorp/packer#9907]
#### Overview of the Issue

Since packer 1.6.0, we are experiencing the issue when skipping a post-processor, any other post-processor followed after the skipped one will also be skipped.

#### Reproduction Steps

* Create a packer.io JSON file with QEMU as type and two post-processors (same type, but different names)
* Start the build process with except of the first post-processor

### Packer version

```
Packer v1.6.2
```

### Simplified Packer Buildfile

[Github detailed format](https://gist.github.com/TomSDEVSN/59f1acdcbc38f5d6042ea65a460114a8)

### Operating system and Environment details

Packer is running on Arch Linux x86_64 (Kernel 5.8.5-arch1-1, QEMU emulator version 5.1.0). 
I also tried it on a system running Ubuntu 18.04.5 LTS (Kernel 4.15.0-115-generic, QEMU emulator version 4.2.0).

### Log Fragments and crash.log files

[Github detailed format](https://gist.github.com/TomSDEVSN/e39715325ab0f75e02020d691063a104)

**Comment by sylviamoss** [comment]
Thanks for reaching out. We’ll take a look when we get a chance!

**Comment by sylviamoss** [comment]
Hi there! I would expect that by looking at your template. See the example in the docs https://www.packer.io/docs/templates/post-processors#run-on-specific-builds 

> A sequence of post-processors will execute until a skipped post-processor.

Your post-processors are wrapped in a sequence. If you don't want to skip the second post-processor when the first is skipped then you have to extract them from the extra `[]`. Like: 

```
"post-processors": [
      {
        "name": "sparsify",
        "type": "shell-local",
        "inline": [
          "/usr/bin/virt-sparsify --inplace output-{{ user `vm_name` }}/packer-{{ user `vm_name` }}"
        ]
      },
      {
        "name": "tarball",
        "type": "shell-local",
        "inline": [
          "/usr/bin/virt-tar-out -a output-{{ user `vm_name` }}/packer-{{ user `vm_name` }} / - | xz -T4 -k --best > output-{{ user `vm_name` }}/output-{{ user `vm_name` }}.tar.xz"
        ]
      }
  ]
```

I'll close this issue, but feel free to reach out to us if you need more help.
