### ISSUE TITLE
Script disconnected unexpectedly

### ISSUE THREAD

**Issue by workabhaswadhwa** [hashicorp/packer#9908]
#### Overview of the Issue

Experiencing "Script disconnected unexpectedly" many times where as same steps results in successful creation of googlecompute image creation.

### Packer version

Packer version 1.3.3 
and Packer version 1.6.0

### Simplified Packer Buildfile

Part of the packer file where error is suspected is part of provisioner
      {
        "type": "shell",
        "start_retry_timeout": "10m",
        "inline": [
          "echo \"d\nn\n\n\n\n\nw\n\n\" | sudo /usr/sbin/fdisk /dev/sda && true",
          "sudo /usr/sbin/reboot",
          "sleep 60"
        ],
        "expect_disconnect": true,
        "only": [
          "googlecompute"
        ]
      },
      {
        "type": "shell",
        "start_retry_timeout": "10m",
        "inline": "sudo /usr/sbin/xfs_growfs /",
        "only": [
          "googlecompute"
        ]
      },
      {
        "type": "shell",
        "inline": "sudo yum remove -y chef"
      },

### Operating system and Environment details

LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.3.1611 (Core)
Release:        7.3.1611

### Log Fragments and crash.log files

googlecompute: output will be in this color.
googlecompute: Checking image does not exist...
googlecompute: Creating temporary SSH key for instance...
googlecompute: Using image: generic-foundation-image-1597205914-b336-master
googlecompute: Creating instance...
googlecompute: Loading zone: us-east1-d
googlecompute: Loading machine type: n1-standard-1
googlecompute: Requesting instance creation...
googlecompute: Waiting for creation operation to complete...
googlecompute: Instance has been created!
googlecompute: Waiting for the instance to become running...
googlecompute: IP: *.*.*.*
googlecompute: Using ssh communicator to connect: *.*.*.*
googlecompute: Waiting for SSH to become available...
googlecompute: Connected to SSH!
googlecompute: Provisioning with shell script: /tmp/packer-shell666505718
googlecompute: Welcome to fdisk (util-linux 2.23.2).
googlecompute:
googlecompute: Changes will remain in memory only, until you decide to write them.
googlecompute: Be careful before using the write command.
googlecompute:
googlecompute: Device does not contain a recognized partition table
googlecompute: Building a new DOS disklabel with disk identifier 0xe50c7759.
googlecompute:
googlecompute: The device presents a logical sector size that is smaller than
googlecompute: the physical sector size. Aligning to a physical sector (or optimal
googlecompute: I/O) size boundary is recommended, or performance may be impacted.
googlecompute:
googlecompute: Command (m for help): No partition is defined yet!
googlecompute:
googlecompute: Command (m for help): Partition type:
googlecompute:    p   primary (0 primary, 0 extended, 4 free)
googlecompute:    e   extended
googlecompute: Select (default p): Using default response p
googlecompute: Partition number (1-4, default 1): First sector (2048-104443999, default 2048): Using default value 2048
googlecompute: Last sector, +sectors or +size{K,M,G} (2048-104443999, default 104443999): Using default value 104443999
googlecompute: Partition 1 of type Linux and of size 49.8 GiB is set
googlecompute:
googlecompute: Command (m for help): The partition table has been altered!
googlecompute:
googlecompute: Calling ioctl() to re-read partition table.
googlecompute:
googlecompute: WARNING: Re-reading the partition table failed with error 22: Invalid argument.
googlecompute: The kernel still uses the old table. The new table will be used at
googlecompute: the next reboot or after you run partprobe(8) or kpartx(8)
googlecompute: Syncing disks.
googlecompute: Provisioning with shell script: /tmp/packer-shell947863064
googlecompute: meta-data=/dev/sda2              isize=512    agcount=11, agsize=1297792 blks
googlecompute:          =                       sectsz=4096  attr=2, projid32bit=1
googlecompute:          =                       crc=1        finobt=0 spinodes=0
googlecompute: data     =                       bsize=4096   blocks=13055500, imaxpct=25
googlecompute:          =                       sunit=0      swidth=0 blks
googlecompute: naming   =version 2              bsize=4096   ascii-ci=0 ftype=1
googlecompute: log      =internal               bsize=4096   blocks=2560, version=2
googlecompute:          =                       sectsz=4096  sunit=1 blks, lazy-count=1
googlecompute: realtime =none                   extsz=4096   blocks=0, rtextents=0
googlecompute: Provisioning with shell script: /tmp/packer-shell696235097
googlecompute: Loaded plugins: fastestmirror
googlecompute: No Match for argument: chef
googlecompute: Provisioning step had errors: Running the cleanup provisioner, if present...
googlecompute: Deleting instance...
googlecompute: Instance has been deleted!
googlecompute: Deleting disk...
googlecompute: Disk has been deleted!
Build 'googlecompute' errored: Script disconnected unexpectedly. If you expected your script to disconnect, i.e. from a restart, you can try adding `"expect_disconnect": true` or `"valid_exit_codes": [0, 2300218]` to the shell provisioner parameters.

**Comment by nywilken** [comment]
Hi there :wave”, are you still running into issues here? Quickly looking at the logs it appears that the last provisioner is failing to install or find chef 

```
googlecompute: Provisioning with shell script: /tmp/packer-shell696235097
googlecompute: Loaded plugins: fastestmirror
googlecompute: No Match for argument: chef
googlecompute: Provisioning step had errors: Running the cleanup provisioner, if present...
```


If this is no longer an issue please feel free to mark this issue as resolved by closing it.
