### ISSUE TITLE
[feature] Official GitHub action: setup-packer

### ISSUE THREAD

**Issue by danielkubat** [hashicorp/packer#9909]
Please search the existing issues for relevant feature requests, and use the
reaction feature
(https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
to add upvotes to pre-existing requests.

#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description
Hashicorp official provided action: `setup-packer` to run `packer` as part of workflow.

#### Use Case(s)
Formatting, validation and build using `packer` within GitHub Actions

#### Potential References
https://github.com/hashicorp/setup-terraform

**Comment by nywilken** [comment]
Hi @danielkubat this sounds like a great idea. Have you seen the work done at https://github.com/marketplace/actions/packer-github-actions? 

It might be exactly what you are looking for. Let us know.

**Comment by danielkubat** [comment]
@nywilken yeah, this is it. thanks.
