### ISSUE TITLE
OpenStack Builder - Authentication Failed

### ISSUE THREAD

**Issue by zjpiazza** [hashicorp/packer#9910]
Hello,

I am trying to configure Packer to run with my company's OpenStack instance and keep running into an authentication issue. I have already looked at [Basic Example - Private OpenStack Cloud](https://www.packer.io/docs/builders/openstack.html#basic-example-private-openstack-cloud) and [Notes on OpenStack Authorization](https://www.packer.io/docs/builders/openstack.html#notes-on-openstack-authorization). I have confirmed via the CLI that issuing `openstack token issue` command returns a valid token. Here are the environment variables I am setting before executing the `packer build` command:

OS_PROJECT_DOMAIN_NAME
OS_PROJECT_NAME
OS_USER_DOMAIN_NAME
OS_AUTH_URL
OS_REGION_NAME
OS_TENANT_NAME
OS_USERNAME
OS_PASSWORD

Any advice from people who have encountered this situation before?

Thanks

**Comment by nywilken** [comment]
Hi there @zjpiazza thanks for reaching out. If you can provide a redacted Packer template and Packer debug logs `Packer_LOG=1 packer build <template>` we might be able to help in figuring out what is causing the authentication issue. 

Have you confirmed that all of the environment variables are being passed in correctly to Packer? 

If it helps, you can use the null builder with the shell-local provisioner to verify the values for the environment variables. See the  example below. 

```

{
  "variables": {
    "project_name": "{{env `OS_PROJECT_NAME`}}"
  },
  "builders": [
    {
      "type": "null",
      "communicator": "none"
    }
  ],
  "provisioners": [
    {
      "type": "shell-local",
      "inline": [ "echo {{user `project_name`}}"]
    }
  ]
}


⇶  export OS_PROJECT_NAME=Packer 

⇶  packer build template.json   
null: output will be in this color.

==> null: Running local shell script: /tmp/packer-shell709265880
    null: Packer
Build 'null' finished after 6 milliseconds 64 microseconds.

==> Wait completed after 6 milliseconds 105 microseconds

==> Builds finished. The artifacts of successful builds are:
--> null: Did not export anything. This is the null builder
```

 If you're struggling to get Packer working for the first time, I'd recommend reaching out to the [community forum](https://discuss.hashicorp.com/c/packer/) for help. The GitHub issue tracker is only watched by a small subset of maintainers and is really reserved for bugs rather than questions. You'll have a better chance of finding someone who can help you in the forum.

**Comment by zjpiazza** [comment]
@nywilken thanks for the prompt reply. I modified the null builder example you provided and confirmed that packer is indeed able to access those environment variables. I'm wondering if the issue is related to permissions scope. Are the required OpenStack permissions for packer explicitly documented somewhere? In my Self Service tenant I tested that I am able to create instances and create new images. Here is the packer OpenStack template I am attempting to build:

```
{
  "builders": [
    {
      "type": "openstack",
      "ssh_username": "centos",
      "image_name": "nginx_centos7",
      "source_image": "centos7-p9.qcow2",
      "flavor": "m1.medium",
      "security_groups": [
        "default"
      ],
      "networks": [
        "SelfServe"
      ],
      "user_data_file": "{{template_dir}}/../user-data.yaml"
    }
  ],
  "provisioners": [
    {
      "type": "shell",
      "inline": [
        "while [ ! -f /var/lib/cloud/instance/boot-finished ]; do echo 'Waiting for cloud-init...'; sleep 1; done"
      ]
    },
    {
      "type": "ansible-local",
      "staging_directory": "/tmp/packer-ansible",
      "inventory_groups": [
        "default"
      ],
      "command": "ANSIBLE_FORCE_COLOR=1 PYTHONUNBUFFERED=1 ANSIBLE_CONFIG=/tmp/packer-ansible/ansible.cfg ansible-playbook",
      "playbook_file": "{{template_dir}}/../ansible/nginx.yml",
      "playbook_dir": "{{template_dir}}/../ansible",
      "extra_arguments": [
        "-e ansible_python_interpreter=/usr/bin/python3"
      ]
    }
  ]
}

```

**Comment by zjpiazza** [comment]
Fantastic. I figured out the issue. This is a corporate environment so in order to communicate with OpenStack, my requests have to be proxied. Setting the HTTP Proxy in Internet Explorer allowed me to connect with OpenStack in the browser but command line tools were not picking up that configuration. After exporting "HTTP_PROXY" it appears that packer is working. 

*facepalm*
