### ISSUE TITLE
Packer validate isn't returning a result

### ISSUE THREAD

**Issue by evanniedojadlo** [hashicorp/packer#9912]
I am currently using packer `version 1.6.2` on Mac OS `10.15.6` which was installed via HomeBrew and when I run the `packer validate somefile.json` command I am not getting anything returned.

I am expecting a `Template validated successfully.` or something similar but nothing is printed to the terminal.

**Comment by evanniedojadlo** [comment]
understood and thanks, my AMI built successfully so that seems to be a good sign of validation :) 

Take care,

**Comment by nywilken** [comment]
Awesome! Glad to help.
