### ISSUE TITLE
Restrict AWS Security group to the current host's Public IP address according to AWS

### ISSUE THREAD

**Issue by tedivm** [hashicorp/packer#9915]
#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

AWS provides an extremely simple service that you can use to find out what IP address AWS from your machine.

https://checkip.amazonaws.com/

#### Use Case(s)

This would make it so the machine did not have to be open to the world.

#### Potential References

#6735

**Comment by nywilken** [comment]
Hi @tedivm I can see where this can be useful, and think it could be a good idea. But I do think that this may be tricky, even with a service like Amazon's checkip. Packer is executed from various environments some of which are restricted to internal networks, VPNs, and so on. Which could add a little complexity around the maintenance of such an option.

Packer's support for allowing [`temporary_security_group_source_cidrs`](https://www.packer.io/docs/builders/amazon/ebs#temporary_security_group_source_cidrs) or pre-existing security groups via [`security_group_id`](https://www.packer.io/docs/builders/amazon/ebs#security_group_id) are good solutions for this use case.

With all that being said, If a member of the Packer community is interested in opening up a PR that does not add complexity to the Packer code base or user experience we would be happy to review and take it into consideration. Cheers :smile:

**Comment by tedivm** [comment]
Even if it was called from inside of a normal network or a VPN the IP address would still work, since it would be the IP address that the APIs see. If the user is behind a NAT it will be the IP address of the NAT that shows up, for example. I can't think of a single reasonable scenario where AWS would see two separate IP addresses from a single packer instance.

Right now my company uses a wrapper script around packer to deal with the temporary security group settings. However, I think packer should probably have secure defaults that follow the AWS recommended best practices- especially since it's not unheard of for packer to crash partway through (due to expired security tokens, network connections, etc) which would leave machines sitting there open to the world.
