### ISSUE TITLE
Variables inside vagrantfile_template of vagrant postprocessor not replaced

### ISSUE THREAD

**Issue by aacebedo** [hashicorp/packer#9921]
## Overview of the Issue

Variables inside the file pointed by the vagrantfile_template are not replaced during box creation

#### Reproduction Steps

- Add a docker provider
- Add a vagrant post processor
- Create a vagrantfile template with a variable inside for example config.vm.box = {{.Name}}
- Run the build
- Extract the vagrantfile from the box and see that variables are still there.
 
### Packer version

1.6.2`

### Simplified Packer Buildfile

{
  "builders": [
      {
          "type": "docker",
          "image": "ubuntu:latest",
          "commit": "true",
          "pull": "false",
          "run_command": ["-d", "-i", "-t", "--entrypoint=/bin/bash", "--", "{{.Image}}"]
      }
  ],

  "post-processors": 
    [
      {
        "type": "vagrant",
        "keep_input_artifact": true,
        "vagrantfile_template": "Vagrantfile.template"
      }
    ]
}

### Operating system and Environment details

Ubuntu 20.04

### Log Fragments and crash.log files

Unavailable

**Comment by sylviamoss** [comment]
Thanks for reaching out. We’ll take a look when we get a chance!

**Comment by sylviamoss** [comment]
Hey there, I implemented a solution for this and you can test it with these binaries: https://app.circleci.com/pipelines/github/hashicorp/packer/7128/workflows/9d21e444-7712-4abc-ae89-5c13fae1ca94/jobs/80661/artifacts
To interpolate the build name you should use `{{build_name}}` or `{{.BuildName}}` instead of just `{{.Name}}`.
Here the docs for the template engine [build_name](https://www.packer.io/docs/templates/engine#build_name)

**Comment by aacebedo** [comment]
Great I'll do that ! 
Is it working with all the functions of the template engine ! 
My goal here is to retrieve the sha256 of the container produced by the build and use it in the d.image argument of the vagrant filen

**Comment by sylviamoss** [comment]
I think with what we have right now you won't be able to do that. We could try to add a specific docker builder variable with such information, something like `{{ build 'ContainerSha256' }}`, and then you use it in your template like the build name one.

**Comment by aacebedo** [comment]
That would be super useful !

**Comment by sylviamoss** [comment]
Soo, here are the binaries you can use to test the `{{ build 'ImageSha256'}}` variable 
https://app.circleci.com/pipelines/github/hashicorp/packer/7139/workflows/26c1e714-77f7-4ded-abcd-36d5e89521d9/jobs/80812/artifacts
Let me know if works for you!

**Comment by aacebedo** [comment]
Ok that's working thanks
