### ISSUE TITLE
Provide TEMPLATE_PATH and OUTPUT_PATH as environment variables to post-processors(shell-local)

### ISSUE THREAD

**Issue by ltrager** [hashicorp/packer#9926]
#### Description

The full realpath to the template and output artifact should be exported as environment variables to the shell-local post-processor. Currently if a post-processor needs to modify the output it has to guess the path. This requires packer to be run from the same directory as the template. The output path can be used to modify the image after the vendors installer finishes. The template path can be used so the post-processor knows where to copy additional resources from.

#### Use Case(s)

I'm the author of [gh:canonical/packer-maas](https://github.com/canonical/packer-maas). I created a number of Packer templates to create CentOS, RHEL, and VMware images for use with [MAAS](https://maas.io). [MAAS](https://maas.io) requires images to be either a TGZ or DD image. I've created [post-processor scripts](https://github.com/canonical/packer-maas/tree/master/scripts) to handle the conversion. These scripts only work if the user executes Packer in the same directory the template is in because I have to guess the path for the output-image and where I have other resources that need to be copied into the image.

If TEMPLATE_PATH and OUTPUT_PATH were exported as environment variables I could modify my scripts to work no matter where Packer is executed from.

**Comment by sylviamoss** [comment]
Hello there, thanks for reaching out. We'll take a look at this when we get a chance. 
Until there, you could transform your JSON templates to HCL2 using the hcl2_upgrade command and from there you'll be able to use the `path.root` variable which should give you what you need. 
Here the docs for the [path variables](https://www.packer.io/docs/from-1.5/path-variables) and [hcl2_upgrade command](https://www.packer.io/docs/commands/hcl2_upgrade)

**Comment by nywilken** [comment]
Hello there since we're trying to move users off of JSON and onto HCL templates now, I would suggest going with @sylviamoss recommendation. As it is unlikely that we will be implementing this feature in JSON. 

I'm going to close this issue, and I encourage you to reach out if you have any issues migrating to HCL. Cheers!
