### ISSUE TITLE
Add serial mode in qemu builder

### ISSUE THREAD

**Issue by ltrager** [hashicorp/packer#9927]
#### Description

Packer is often run in environments that do not have access to a UI. While Packer supports running headless no output is given to the terminal. A template can be constructed today that shows serial output by adding "qemuargs": [[ "-serial", "stdio" ]] and running Packer with PACKER_LOG=1. See [the CentOS 8 Packer template as an example.](https://github.com/canonical/packer-maas/blob/master/centos8/centos8.json)

While this works "2020/09/11 02:04:16 packer-builder-qemu plugin: Qemu stdout" is often mixed in with output which makes things hard to read. Ideally an official option would be added to Packer which adds "-serial stdio" to the qemu arguments and doesn't prepend each line.

#### Use Case(s)

1. I am working on using [gh:canonical/packer-maas](https://github.com/canonical/packer-maas) to produce the public CentOS images for [MAAS](https://maas.io). I have been given a Jenkins server to do this but have no access to the Jenkins builders. This makes debugging very hard as I can't VNC in, all I get is the terminal output.
2. Users of [gh:canonical/packer-maas](https://github.com/canonical/packer-maas) run Packer on Ubuntu desktop, remotely on an Ubuntu server over SSH, or in a Jenkins job. As such I have [gh:canonical/packer-maas](https://github.com/canonical/packer-maas) set to run headless. I've been asked to show progress while Packer is running as well as add the ability for users to send me logs.

#### Potential configuration

"serial": "true/false"

**Comment by sylviamoss** [comment]
This sounds like a good idea. We’ll take a look when we get a chance.

**Comment by MaxPeal** [comment]
@sylviamoss @azr any Update on this?
