### ISSUE TITLE
vmware-iso builder isn't aware of the reserved SCSI adapter ID 0:7 when adding multiple disks

### ISSUE THREAD

**Issue by zestysoft** [hashicorp/packer#9936]
#### Overview of the Issue

When building a VM with more than 7 disks, VMWare will abort starting the vm if a disk has been assigned the SCSI address 0:7 because that is reserved for the SCSI adapter.  Possible workarounds would be to set the IDs manually or create multiple controllers and assign less than 8 disks per controller (zero indexed), but I don't believe either option is available with vwmare-iso. (I think vsphere-iso has those options?)

#### Reproduction Steps

Build something using vmware-iso that has this in the configuration file:

 "disk_size": 4000,
      "disk_additional_size": [
        2000,
        1000,
        2000,
        1000,
        5000,
        1500,
        500,
        2048
      ],

### Packer version

v1.6.2

### Operating system and Environment details

MacOS Catalina (10.15.6)

### Log Fragments and crash.log files

Popup message from VMWare Fusion Professional 11.5.5 :

"Unable to configure virtual device 'scsi0:7', whose type is disk."

"The virtual device is assigned a SCSI ID which is reserved for the virtual SCSI adapter. Move the virtual device to an unused SCSI ID and try again. Module 'DevicePowerOn' power on failed. Failed to start the virtual machine."

**Comment by sylviamoss** [comment]
Thanks for reaching out. We’ll take a look when we get a chance
