### ISSUE TITLE
Kickstart commands inside boot_command

### ISSUE THREAD

**Issue by DaniBet** [hashicorp/packer#9937]
Hello,

I have the following question. I want to build a Centos 7 imagine using Packer. I want to run the template without a kickstart file .cfg due to some security issues. Is it possible to write all the commands from the kick start file to the template.json?

This is how it actually looks:
```
"boot_command": "<tab> inst.text inst.ks=https://raw.githubusercontent.com/xxx/xxx/xxx/centos-7.cfg <enter><wait>",
```

```
# Turning on text-mode installation (little quicker than GUI)
text

# Setting up authentication and keyboard
auth --enableshadow --passalgo=sha512
keyboard --vckeymap=us --xlayouts='us'

# Installation files source (CentOS-7.0-1406-x86_64-Minimal.iso)
cdrom

# Using only primary disk, ignoring others
ignoredisk --only-use=sda

# Setting up language to English
lang en-US.UTF-8
...
```

And I want something like:
```
text
auth --enableshadow --passalgo=sha512
keyboard --vckeymap=us --xlayouts='us'
cdrom
ignoredisk --only-use=sda
lang en-US.UTF-8"
...
```

Unfortunately, the virtual machine doesn't realize that I am sending these commands as kickstart commands and it starts in the GUI mode.

**Comment by sylviamoss** [comment]
Hello there! Could you share what have you tried already for the boot command? 

Something like: 
```
"boot_command":  [
"<tab> inst.text",
" auth --enableshadow --passalgo=sha512",
" keyboard --vckeymap=us --xlayouts='us'",
" cdrom",
" ignoredisk --only-use=sda",
" lang en-US.UTF-8", 
"<enter><wait>"
...
}
```

Can you type it manually and catch all the actions you have to do like, for example, `<enter>`, `<wait>` and etc? If you can do that, I would guess that you can do it as well via boot_command and would just need to give the right keyboard commands to type.

**Comment by nywilken** [comment]
Hi there :wave: are you still running into issues here?

If this is no longer an issue please feel free to close it so that we know your issue has been resolved. Thanks!

**Comment by SwampDragons** [comment]
I'm closing this since it's been over a month with no reply; we'll reopen if you get a chance to give us more information.
