### ISSUE TITLE
Regarding Multiplatform

### ISSUE THREAD

**Issue by krishna0207** [hashicorp/packer#9947]
Is there a possibility of moving existing images from AWS to Azure using Packer?
I have an ec2 instance with Jenkins builds on it. Now since we are trying to start using Azure, I am a bit concerned over migration. 
I know we have an option on azure migrate, but I want to check if the packer does the same.

**Comment by krishna0207** [comment]
Leave me a comment if possible and also a link if you have to do the same. 
Else let me know if the feature is upcoming...

**Comment by SwampDragons** [comment]
I saw your post on Discuss, and that's a better forum for these general questions so I'm going to close this and answer you there. :)
