### ISSUE TITLE
Deploy to Datatstore Cluster and Cluster rather than Host and Datastore - vmware_content_deploy_template

### ISSUE THREAD

**Issue by jdotsmith** [hashicorp/packer#9957]
Please search the existing issues for relevant feature requests, and use the
reaction feature
(https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
to add upvotes to pre-existing requests.

#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

Currently it looks like the vmware_content_deploy_template module only allows me to deploy a template to an individual host and an individual datastore. I would like the ability to deploy a VM to a Datastore Cluster and a DRS enabled cluster. 

#### Use Case(s)

Datastore Clusters and Cluster names are pretty static. The variables should be the same regardless of how many hosts and/or datastores are added. Makes automating VM builds easier using Datastore clusters and Clusters easier.

#### Potential configuration

```
```

#### Potential References

The vmware_guest module allows deploying to both clusters

**Comment by SwampDragons** [comment]
is vmware_content_deploy_template even a thing in Packer?

**Comment by SwampDragons** [comment]
Thanks for reaching out with this, but I think I need a little more information here. I don't know what the module you're referencing is, and it doesn't appear in the Packer docs anywhere. Can you provide a more specific use case about what you're trying to do here?

**Comment by jdotsmith** [comment]
Just realized I was in the wrong repo when I added the REF. :) This should be in ansible.
