### ISSUE TITLE
Allow googlecompute to not create image after building

### ISSUE THREAD

**Issue by bhundven** [hashicorp/packer#9965]
#### Description

In a test -> build pipeline, it would be nice to "dry run" building a googlecompute image, but not create the new image, in the case of a "test" stage.

#### Use Case(s)

I have a pipeline with the following stages:
* lint
* test
* build
* deploy

I run `packer validate`, `terraform validate`, and `tflint` in the lint stage.
In the test stage, I would like to run terraform build and pass a var to have it not create the image after building it to test that the build will work.

These stages get ran during the "merge request" pipeline, build and deploy only happen in the master/main branch.

When the branch gets merged, it will run all four stages, and during the build stage, the var to not create the image is not passed, so the image does get created.

#### Potential configuration

```
variable "create_image" {
  description = "Create the image by default"
  type        = bool
  default     = true
}

source "googlecompute" "my_image" {
  account_file = var.account_file
  disk_size = "20"
  disk_type = "pd-standard"
  image_description = "My fun test image"
  image_family = "my_image"
  image_name = "my_image-{{timestamp}}"
  project_id = var.project_id
  create_image = var.create_image
  source_image_family = "centos-8"
  ssh_username = "packer"
  subnetwork = "projects/build/regions/us-west1/subnetworks/build-network-us-west1"
  use_internal_ip = true
  zone = var.zone
  tags = [
    "ssh-server"
  ]
}
```

**Comment by sylviamoss** [comment]
Thanks for reaching out. We’ll take a look when we get a chance.

**Comment by azr** [comment]
Hello @bhundven !

One thing you could do is use a post-processor with `keep_input_artifact = false` in the case of a test build. The image will be built, saved but later on destroyed by Packer, for example:

```hcl
build {
    # ....
    post-processor "manifest" {
        keep_input_artifact = false
        output                      = "build-manifest.json"
    }
}
```

**Comment by bhundven** [comment]
@azr It would be nice to not have to wait around for googlecompute to upload the image, and then delete it, but for now this is a worthy work-around!

**Comment by azr** [comment]
Hey @bhundven I looked and only the `artifice`  post processor can help you here !

**Comment by bhundven** [comment]
@azr It's a good idea in thought, but then fails a passing pipeline.
