### ISSUE TITLE
Missing APT lists when provisioning amazon-ebs

### ISSUE THREAD

**Issue by realies** [hashicorp/packer#9966]
#### Overview of the Issue

Occasionally seeing this in the very first steps of provisioning an image. Running Packer for a second time usually resolves it.

> amazon-ebs: E: can not open /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_bionic-backports_InRelease - fopen (2: No such file or directory)

#### Reproduction Steps

Run apt-get install on the latest ubuntu bionic AMI

### Packer version

Packer v1.5.5

### Simplified Packer Buildfile

If the file is longer than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/) of the log or use the [Github detailed
format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d)
instead of posting it directly in the issue.

### Operating system and Environment details

NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
EC2 t2.medium

**Comment by sylviamoss** [comment]
Hey there, thanks for reaching out. Could you provide more details of your template config as well as logs, please? 
Also, we've made some improvements to the amazon builder since v1.5.5, and I strongly suggest you update the version of Packer, even if it doesn't fix your problem for now.
