### ISSUE TITLE
"remove_cdrom" not documented in vsphere-iso (or now vsphere-clone)

### ISSUE THREAD

**Issue by rconde01** [hashicorp/packer#9982]
#### Overview of the Issue

By default, iso files attached using iso_paths create new DVD driver, but only eject them at the end (they don't remove them).  https://github.com/hashicorp/packer/pull/8690 adds "remove_cdrom" option but this doesn't appear in the vsphere-iso documentation (and now this applies to vsphere-clone after  https://github.com/hashicorp/packer/issues/9868).

**Comment by SwampDragons** [comment]
Hi, this was just implemented in https://github.com/hashicorp/packer/pull/9963/files#diff-79f625db17b4c315845803f9945af092 and merged today. We'll release a new website update when we deploy later this week.
