### ISSUE TITLE
Fedora coreos image packer build fail in digitalocean

### ISSUE THREAD

**Issue by milan-dikkumburage** [hashicorp/packer#9986]
Hi Team,

#### Overview of the Issue
we try to deploy fedora coreos custom image through packer in digitalocean.but after execute the packer build its getting fail showing below error message 

![image](https://user-images.githubusercontent.com/35827824/94138113-33b7a400-fe85-11ea-8967-ed6b40b3d83e.png)

we noticed slug is null in custom image in digitalocean . Any idea on this .

#API Response

{
    "image": {
        "id": 70571182,
        "name": "fedora-coreos-custom",
        "distribution": "Fedora",
        "slug": null,
        "public": false,
        "regions": [
            "tor1"
        ],
        "created_at": "2020-09-23T07:30:56Z",
        "min_disk_size": 15,
        "type": "custom",
        "size_gigabytes": 0.89,
        "description": "",
        "tags": [
            "myfedora-coreos"
        ],
        "status": "available",
        "error_message": ""
    }
}

### Packer version
1.6.2

### Simplified Packer Buildfile
packer-fedora.json

{
  "variables": {
    "do_api_token": "{{env `DIGITALOCEAN_API_TOKEN`}}"
  },

  "builders": [
    {
      "type": "digitalocean",
      "api_token": "{{user `do_api_token`}}",
      "image": "fedora-coreos-custom",
      "region": "tor1",
      "droplet_name": "packer-okd",
      "ssh_username": "core",
      "snapshot_name": "fedorabase-okd4-{{timestamp}}",
      "size": "s-1vcpu-1gb"
    }
  ],

  "provisioners": [
    {
      "type": "shell",
      "scripts": ["provisioners/scripts/install-packages.sh"]
    },
    {
      "type": "ansible",
      "playbook_file": "provisioners/ansible/git.yml"
    }
  ]
}

### Operating system and Environment details

fedora coreos support digitalocean https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/32.20200907.3.0/x86_64/fedora-coreos-32.20200907.3.0-digitalocean.x86_64.qcow2.gz

https://getfedora.org/coreos/download?tab=cloud_operators&stream=stable

### Log Fragments and crash.log files

packer debug log 
[log.txt](https://github.com/hashicorp/packer/files/5275517/log.txt)

**Comment by nywilken** [comment]
Hi there @milan-dikkumburage thanks for reaching out. I was able to reproduce the issue, thanks for the provided configuration. 

When using the custom images please set `"name"` to the numeric ID of the image and check that your build region matches the region where the custom image was uploaded to. Otherwise you run into the above error. 

For example, given the following custom image in region sfo2
```
70630748    my-fcos-image                 custom      Unknown                 false     15
```

The Packer template would look like
```
"builders": [                                                                                                                                                                                                                                                                                          
  {                                                                                                                                                                                                                                                                                                    
  "type": "digitalocean",                                                                                                                                                                                                                                                                              
  "api_token": "{{user `do_api_token`}}",                                                                                                                                                                                                                                                              
  "image": "70630748",                                                                                                                                                                                                                                                                                 
  "region": "sfo2",                                                                                                                                                                                                                                                                                    
  "droplet_name": "packer-okd",                                                                                                                                                                                                                                                                        
  "ssh_username": "core",                                                                                                                                                                                                                                                                              
  "snapshot_name": "fedorabase-okd4-{{timestamp}}",                                                                                                                                                                                                                                                    
  "size": "s-1vcpu-1gb"                                                                                                                                                                                                                                                                                
  }                                                                                                                                                                                                                                                                                                    
],
```

Please give the suggested changes a try and let us know if it works. Cheers!

For future reference I used the steps outlined [here](https://docs.fedoraproject.org/en-US/fedora-coreos/provisioning-digitalocean/#_creating_a_digitalocean_custom_image) to upload and test droplet creation outside of Packer.

**Comment by milan-dikkumburage** [comment]
Thanks @nywilken  .i was able to deploy fedora coreos image by changing image ID.
