### ISSUE TITLE
amazon-ebs builder: using source_ami_filter, SourceAMI nor SourceAMIName work in tags

### ISSUE THREAD

**Issue by marcosdiez** [hashicorp/packer#9987]
#### Overview of the Issue

I am using packer 1.6.2 to build EC2 images, more specifically, using the `amazon-ebs` builder.

On the builder settings, I use `source_ami_filter` to get the source AMI.

By doing that, I can't have neither

```
        "run_tags": {
            "SourceAMI": "{{ build `SourceAMI`}}",
            "SourceAMIName": "{{ build `SourceAMIName` }}",
        }
```
nor
```
        "tags": {
            "SourceAMI": "{{ build `SourceAMI`}}",
            "SourceAMIName": "{{ build `SourceAMIName` }}",
        }
```

The error I get is:

```
 Error processing tag: SourceAMIName:{{ build `SourceAMIName` }} - template: root:1:3: executing "root" at <build `SourceAMIName`>: error calling build: Error validating build variable: the given variable SourceAMIName will not be passed into your plugin.
```

Although fixing it on `tags` is MUCH more important, there it manifests only after the AMI is done, while on `run_tags` it happens in the first 30 seconds or so.

**Comment by sylviamoss** [comment]
Hello there, 
The correct way to use those variables there in run_tags and tags is:
```
     "run_tags": {
            "SourceAMI": "{{.SourceAMI}}",
            "SourceAMIName": "{{.SourceAMIName}}",
        }
```
Let me know if it works for you this way. 
The `build` function is used by provisioners and post-processors to access build variables.

**Comment by marcosdiez** [comment]
it did work. thank you
