### ISSUE TITLE
ubuntu 18.04.5 issue on vsphere-iso

### ISSUE THREAD

**Issue by komoreka** [hashicorp/packer#9989]
Packer version:  1.6.2

While deploying: ubuntu-18.04.5-live-server-amd64.iso I am able to pass boot_command to properly configure what I can altough I am unable to load preseed both from floppy or http. I found article that live server does not support loading preseed from boot_command which is not great.

That is why I tried ubuntu-18.04.5-server-amd64.iso.
Whit that file non of the boot_command works properly just like I cannot enter to shell to use it.
Can  anybody assist me on that issue.

Ideally I would continue with live server although if not possible I am open for (non-live).

I searched whole google and tried different boot commands no-where is an answer can anybody assist.

Regards,

**Comment by sylviamoss** [comment]
Hello! We added a feature for the next release which allows adding files through the creation of an ISO that will be mounted in the VM. Maybe that's a good option for the live version. 
You can try the feature with our nightly pre-release binaries https://github.com/hashicorp/packer/releases/tag/untagged-6b67b6bca88813e206c0 and here a preview of the documentation to help you understand how it works https://5f6c952f9b32c3000720beca--packer-www.netlify.app/docs/builders/vmware/vsphere-iso#cd_files

For the server version, I found this repo which contains a boot_command for the same iso you're using 
https://github.com/heizo/packer-ubuntu-18.04. Even though is not a vsphere template, the boot_command should be similar if not the same.

**Comment by komoreka** [comment]
Hi Sylvia,

Thanks for quick reply.
Regarding for server (2nd tip) I tried that and with this I am ending up in GRUB where all commands are getting typed in and stuck there.
Regarding for live tip not sure why this could help since I can mount preseed via floppy or http.

**Comment by sylviamoss** [comment]
I was confused because you said unable to load preseed both from floppy or HTTP, so I guessed you couldn't mount them. What is the error that is telling you can't load the preseed from these two options?

See this comment make by @SwampDragons in another similar issue https://github.com/hashicorp/packer/issues/9970#issuecomment-697981265
I suggest you reach out to the [community forum](https://discuss.hashicorp.com/c/packer/23) or our [mailing list](https://groups.google.com/g/packer-tool) to find more help with the correct boot_command. I believe that's the best option here.

**Comment by komoreka** [comment]
well I can load preseed on vm think.
Although ubuntu live does not accept it according to below https://www.reddit.com/r/devops/comments/gaglte/preseed_file_for_ubuntu_1804_2004_hanging_on/

I will reach mailing list thank you

**Comment by sylviamoss** [comment]
Ok. Hope you get the help you need there! Thanks for reaching out and feel free to come back when needed.
