### ISSUE TITLE
vsphere-clone Multiple Disk Support

### ISSUE THREAD

**Issue by divy4** [hashicorp/packer#9990]
#### Description

In #8749, the ability to add multiple disks was added to the `vsphere-iso` builder. Can this ability be added to the `vsphere-clone` builder as well?

#### Use Case(s)

I have a large number of templates I would like to build with Packer that all use the same OS, but varying number of drives. In order to save time and compute resources, I use the `vsphere-iso` builder to create a template that only installs the OS and then make several templates using the `vsphere-clone` template that make any tweaks needed for each use case. But because  `vsphere-clone` doesn't support configuring multiple drives, I have to make a `vsphere-iso` template for every number of drives that are added to the template. If the ability of adding additional disks was added to `vsphere-clone`, then only 1 `vsphere-iso` template would be needed and each `vsphere-clone` template would add any additional disks that are needed.

#### Potential configuration

The same as `vsphere-iso` builder, specifically the [disk_controller_type](https://www.packer.io/docs/builders/vmware/vsphere-iso#disk_controller_type) and [storage](https://www.packer.io/docs/builders/vmware/vsphere-iso#storage) attributes.

**Comment by sylviamoss** [comment]
Hey there, thanks for reaching out. I think this is possible and we will try to address it for the next release.

**Comment by divy4** [comment]
Just checking in, any updates on this or anything I can help out with?

**Comment by SwampDragons** [comment]
We're working on mostly internal and tech-debt related stuff right now, so the best way to see this merged soon is to open a PR.

**Comment by SwampDragons** [comment]
This has been closed in the linked PR -- you can find binaries here https://app.circleci.com/pipelines/github/hashicorp/packer/8035/workflows/d73dea87-f771-4977-b421-e451373d5be4/jobs/93314/artifacts  or you can wait for Tuesday's "nightly" dev release.

**Comment by divy4** [comment]
Ah, thank you so much! I just got access to my vSphere environment yesterday, so I'll see how it goes!
