### ISSUE TITLE
vsphere-iso: Invalid syntax for CPUs and RAM

### ISSUE THREAD

**Issue by shresthabrijan** [hashicorp/packer#9993]
#### Overview of the Issue

I am trying to build a centos template using vsphere-iso builder but cannot validate the configuration.

#### Reproduction Steps

set cpu and ram variables and call in builders using "{{user `var`}}" for CPUs and RAM parameters

### Packer version

Packer v1.6.2

### Simplified Packer Buildfile
```
{
  "variables": {
    "vsphere_server": "",
    "vsphere_user": "",
    "vsphere_password": "",
    "vsphere_template_name": "",
    "vsphere_folder": "",
    "vsphere_dc_name": "",
    "vsphere_host": "",
    "vsphere_portgroup_name": "",
    "vsphere_datastore": "",
    "root_password": "",
    "cpu_num": "",
    "mem_size": "",
    "disk_size": "",
    "os_iso_path": "",
    "vmtools_iso_path":""
  },
  "sensitive-variables": ["vsphere_password", "root_password"],
  "builders": [
    {
      "type": "vsphere-iso",

      "vcenter_server": "{{user `vsphere_server`}}",
      "username": "{{user `vsphere_user`}}",
      "password": "{{user `vsphere_password`}}",
      "insecure_connection": "true",

      "vm_name": "{{user `vsphere_template_name`}}",
      "folder" : "{{user `vsphere_folder`}}",
      "datacenter":	"{{user `vsphere_dc_name`}}",
      "host":	"{{user `vsphere_host`}}",
      "network": "{{user `vsphere_portgroup_name`}}",
      "datastore": "{{user `vsphere_datastore`}}",
      "convert_to_template": "true",
			"notes": "Build via Packer",
      "guest_os_type": "centos8_64Guest",

      "communicator": "ssh",
      "winrm_username": "root",
      "winrm_password": "{{user `root_password`}}",

      "CPUs": "{{user `cpu_num`}}",
      "RAM": "{{user `mem_size`}}",
      "RAM_reserve_all": false,
      "firmware": "bios",

      "disk_controller_type":  "pvscsi",
      "disk_size": "{{user `disk_size`}}",
      "disk_thin_provisioned": true,

      "network_card": "vmxnet3",

      "iso_paths": [
        "{{user `os_iso_path`}}"
      ],
      "floppy_files": [
        "kickstart.cfg"
      ],
			"boot_command": [        
				"<esc><wait>",        
				"linux ks=hd:fd0:/kickstart.cfg<enter>"      
			]					
    }
  ],

  "provisioners": [
    {
      "type": "shell",
      "inline": ["sudo dnf install -y open-vm-tools"]
    }
  ]
}
```

### Operating system and Environment details

Windows Server 2012 R2 64-bit
Packer v1.6.2
vSphere 6.7

### Log Fragments and crash.log files

```
Error: Failed to prepare build: "vsphere-iso"

2 error(s) decoding:

* cannot parse 'CPUs' as int: strconv.ParseInt: parsing "": invalid syntax
* cannot parse 'RAM' as int: strconv.ParseInt: parsing "": invalid syntax
```

**Comment by sylviamoss** [comment]
Hello! 
CPU and RAM are both an integer, not a string. You must give it a string with a number as a default (`"cpu_num": "0"`) value, otherwise, the template engine won't be able to parse an empty string to a number. This is how JSON works and there's not much we can do here. 

That's a good chance to try out HCL2 by upgrading your template with the [hcl2_upgrade](https://www.packer.io/docs/commands/hcl2_upgrade) command. 
HCL2 will let you define variables with types and default, which makes it easier to work with and validate.
In you variables file you would have something like: 
```hcl
variable "vsphere_server" {
  type    = string
  default = ""
}
// other variables...
variable "cpu_num" {
  type    = number
  default = 0
}
variable "mem_size" {
  type    = number
  default = 0
}
```

I'll close the issue. Hope you find this helpful. Feel free to reach out to us again with any questions/issues.

**Comment by shresthabrijan** [comment]
> helpful. Feel free to reach out to us again with any questions/issues

Hi Sylviamoss,

I have set those variables as string in my variable file. 

```
"cpu_num": "2",
"mem_size": "4096",
```

If using json doesn't work out, I will have no option but resort to HCL I guess.

**Comment by sylviamoss** [comment]
I just ran a JSON build successfully with:

template.json
```json
  "variables": {
    "cpu_num": "",
    "mem_size": ""
  },
  "builders": [
    {
      ...
      "CPUs": "{{ user `cpu_num`}}",
      "RAM": "{{ user `mem_size`}}",
      ...
}]
```

variables.json
```json
{
  "cpu_num": "2",
  "mem_size": "4096"
}
```
Running with command : `PACKER_LOG=1 packer build -var-file variables.json template.json`

Are you sure are you passing the variables file correctly to the build command? The error message shows that the values from your variable file are not assigned.

**Comment by shresthabrijan** [comment]
I hadn't been using  `-var-file` option. Upon passing my var file, the error went away. Sorry for the trouble but I thought packer used to take vars.json from working dir as default variable file earlier.

Thank you for helping me out.

**Comment by sylviamoss** [comment]
No problem! Packer can find variables file inside directories for HCL2 templates only, which is one more reason why HCL2 is super nice 😄
