### ISSUE TITLE
vsphere-iso packer-tmp-created-floppy.flp - contains corrupted files when "too many" files are added to it

### ISSUE THREAD

**Issue by jason-azze** [hashicorp/packer#9998]
#### Overview of the Issue

A vsphere-iso build for Windows VMs that used to work began failing after I added a few more provisioning scripts to it. The specific symptom I encountered was that the Windows setup wizard began to complain that it could not find Autounattend.xml (which is the "answer file" for a quiet Windows installation). I eventually determined that the copy of Autounattend.xml on the packer-tmp-created-floppy.flp was corrupt, as were several other files. So Windows was telling the truth when it would hang during what was supposed to be an unattended setup.

I began to suspect that the provisioning scripts that I had added to my build were at fault because that was the only change I had made. I suspected that something in the file names was causing the data stream to be corrupted during floppy creation, or perhaps I had a weird, unprintable unicode character in my script from a bad copy-paste out of Slack! While I played around with this idea, I began shortening the file names of my new scripts. I eventually discovered (after a generous application of profanity) that a combination of shortening file names and deleting an unneeded file resulted in an uncorrupted flp file and the build was able to proceed. (Note, I checked to be sure was not exceeding the size of a typical floppy.)

So, I think I'm running into something like "too many arguments" for whatever code rolls up the files into the packer-tmp-created-floppy.flp, or perhaps too many total characters. ? 

#### Reproduction Steps

Run a build with *more* than this many characters:
```
ls setup |wc -m
1670
```
or perhaps this many files:
```
ls setup |wc -l
69
```
in your packer-tmp-created-floppy.flp

My build failed because Autounattend.xml happened to be corrupted during the floppy image creation. YMMV.

To prove this to myself, I snagged the temporary .flp file that Packer creates during the build. In my case, the file appears in /tmp. I cracked the file open with Archive Manager  (it's some kind of zip) and tried opening files one by one. Several were corrupted, including Autounattend.xml.

### Packer version

```
packer version
Packer v1.6.2
```
I tried with 1.6.1 and 1.6.0 as well. Same problem.

### Simplified Packer Buildfile

In the reproduction steps above I show that I have 69 files in my setup directory (which works, add more to repro the bug). This is what I use setup for (roughly):
```
  "provisioners": [
    {
      "type": "shell-local",
      "scripts": [
       "setup/test-ssh-dir-get.sh"
      ]
    },
    {
      "type": "windows-shell",
      "inline": ["dir c:\\"]
    },
    {
      "type": "powershell",
      "scripts": [
        "setup/123.ps1"
      ]
    },
    {
      "type": "windows-shell",
      "valid_exit_codes": [0, 3010, 3221227356],
      "scripts": [
        "setup/firewall-off.cmd",
        "setup/network-location-awareness-off.cmd",
        "setup/power-setting.cmd",
        "setup/rdp-enable.cmd",
        "setup/test-user-password-expire-never.cmd",
        "setup/updates-stop-them.cmd",
        "setup/installers-dir-make.cmd",
        "setup/tools-dir-make.cmd",
        "setup/7zip-install.cmd",
        "setup/glorp.cmd",
        "setup/crash-dump-tune.cmd",
        "setup/domain-suffix-set.cmd",
        "setup/file-extensions-and-hidden-files-show.cmd",
        "setup/indexing-turn-off.cmd",
        "setup/timezone-set-local.cmd",
        "setup/windows-annoyances-disable.cmd",
        "setup/windows-defender-disable.cmd"
      ]
    },
    {
      "type": "file",
      "source": "files/.ssh",
      "destination": "C:\\home\\test\\"
    },
    {
      "type": "file",
      "source": "setup/ssh-fix-owner-mode.sh",
      "destination": "C:\\Windows\\Temp\\"
    },
    {
      "type": "file",
      "source": "files/environment",
      "destination": "C:\\Windows\\Temp\\"
    },
    {
      "type": "file",
      "source": "files/sshd_config",
      "destination": "C:\\Windows\\Temp\\"
    },
    {
      "type": "file",
      "source": "setup/ssh-copy-config-files.sh",
      "destination": "C:\\Windows\\Temp\\"
    },
    {
      "type": "powershell",
      "scripts": [
        "setup/cygwin-sshd-config.ps1",
        "setup/pagefile-size.ps1",
        "setup/bginfo-shortcut.ps1",
        "setup/windows-annoyances-and-tweaks.ps1",
        "setup/path-length-longer.ps1"
      ]
    },
    {
      "type": "windows-shell",
      "valid_exit_codes": [0, 3010, 3221549136, 3221227356],
      "scripts": [
        "setup/jenkinsapi-install.cmd",
        "setup/cygwin-setfacl-fix.cmd",
        "setup/drive-map-cleanup.cmd",
        "setup/product-key-fix.cmd",
        "setup/CHANGEME-zero-free-space.cmd"
      ]
    }
  ]
}
```
Notice the files called 123 and glorp? That's me shortening descriptive names.
### Operating system and Environment details

```
cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
```

### Log Fragments and crash.log files
`PACKER_LOG=1`  gives lots of nice detail, but there's no error logged when the floppy is created.

**Comment by nywilken** [comment]
Hi there @jason-azze thanks for reaching out we will need a little time to think about this issue to see what might be causing the corruption. Have you had a chance to post this on the discuss forms to see if anyone has had a similar issue? 

Thanks for checking that the file size did not exceed the size of a floppy. I am curious if instead of exceeding the size of the floppy if Packer is somehow overwriting the contents of the the already persisted floppy. 

In v1.6.3 which is set to go out today there is an new cd_files option that allows for the use of cdrom as opposed to floppy files. When it gets released would you mind checking to see if it fixes the issue for you? 

Wondering if this is related in any way https://github.com/hashicorp/packer/issues/4999.

**Comment by nywilken** [comment]
Hello again v1.6.3 has been released the documentation for the cd_files option is [here](https://www.packer.io/docs/builders/vmware/vsphere-iso#cd_files)

**Comment by jason-azze** [comment]
@nywilken You said, "I am curious if instead of exceeding the size of the floppy if Packer is somehow overwriting the contents of the the already persisted files on the floppy." and that made me take a look at something I'm doing that's probably unnecessary and wrong. I'm not positive yet, I need to run a test.

I did not include in my example code the fact that I have
```
     "floppy_files": [
        "{{template_dir}}/setup/"
      ]
```
in my builder stanza. That superfluous, isn't it? I'm loading all of those provisioning scripts that live in the "setup" directory onto the floppy for no reason. Packer never looks for them there, does it? The only file I need to be present on that floppy is probably Autounattend.xml.

That doesn't mean I haven't stumbled on a bug, but I think when I started using Packer, I had a misunderstanding of what the `floppy_files` option was for. I thought I had to get all of the scripts I was going to use onto the machine before I could execute them, but Packer handles that for me without explicit instructions.

I wonder if, because I've got the same files being sent up to the machine twice, we've got the kind of collision you describe.

I'm going to try the `cd_files` option and report back, but then I'll probably refactor to remove the superfluous floppy files -- unless my boss catches me. I'm supposed to be working on something else today. :-)

**Comment by jason-azze** [comment]
I tested Packer 1.6.3 with the `cd_files` option, and all of the files on the "CD" look OK. No corruption.

This is the syntax I had to use to get my files to be loaded at the root of the resulting CD. Leaving the splat off the end will result in a directory called `setup` being created, which means your boot process won't find what it is looking for. The documentation is clear on this, I'm only pointing it out because the behavior is different from `floppy_files`.

```
      "cd_files": [
        "./setup/*"
      ]
```
Note that using variable interpolation here did not work. That is, this throws an error. This is another difference between `cd_files` and `floppy_files`
```
      "cd_files": [
        "{{template_dir}}/setup/*"
      ]
```
The error is 
```
Error creating temporary file for CD: error creating new directory /tmp/packer_to_cdrom130634943/home/jazze/code/vm-templates/lebanon/w2004/setup: mkdir /tmp/packer_to_cdrom130634943/home/jazze/code/vm-templates/lebanon/w2004/setup: no such file or directory
```
But that's off topic and might require a separate issue.

In case you have arrived here via web search and really need to stick with `floppy_files`, be sure to include only the files you absolutely need on the floppy. In my case those files are Autounattend.xml and two files that Autounattend.xml expects to appear on a:\ , which are setup.ps1 and vmtools.cmd.

I think there's still a bug here with how the floppy is created. I just got lucky that I was making a dumb mistake in thinking I needed to pre-stage all of my scripts on the floppy, so I can get around it.

**Comment by nywilken** [comment]
@jason-azze thanks for testing and for the detailed write up of the issue - super helpful. I didn't get a chance to answer your questions today but will follow up tomorrow. For now I'm going to slate this fix for the next release.

**Comment by SwampDragons** [comment]
I took some time to look into this today. 

Without getting into much architectural stuff here, the root directory a 3.5" floppy disk can contain 224 directory entries. 

When you use long file names (longer than 8 characters), you can require multiple directory entries per file -- a quick look at the Packer implementation at least suggests one entry per 13 characters of your filename. So if you're using a ton of files with long names it's definitely possible to shoot past the maximum number of allowable entries. 

I was able to reproduce a corrupted disk by adding some files with reallllly long file names that in total used ~300 directory entries, and then another set that only used ~215 entries and the disk wasn't corrupted, so I do think there's a good chance this is what's going on here.

Doing a quick bit of math on the files listed in your original config, it looks like they only amount to like 68 directory entries, so you should be way under the limit. Which means I'm not sure why this is falling apart for you unless that setup folder of yours contains way more files than the issue description implies. 

Do you have more files than listed here in your setup folder?
